### ISSUE TITLE
winfixwidth/winfixheightの状態でVim全体のウィンドウサイズを変更するとウィンドウがおかしくなる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#1]
再現手順:

``` vim
vsplit
setlocal winfixheight
split
setlocal winfixheight
```

この後端末やgVimのウィンドウサイズを広げる。
すると以下のようになる。
![結果](http://cdn-ak.f.st-hatena.com/images/fotolife/t/thinca/20110430/20110430204523.png)

**Comment by mattn** [comment]
これなんですが

![番号](http://go-gyazo.appspot.com/8b14ae3010864fae.png)

手順で行けば、2と3は`winfixheight`な訳なので、正しい動きといえば正しい動きな気がしますね。

**Comment by ynkdir** [comment]
私も最初正しいような気がしましたが
たとえ winfixheight でも vsplit してなければ高さは変わるし
スクリーンショットの状態でコマンドラインでなにか入力するとなんかおかしい感じになるので
変な気もしました。

**Comment by ynkdir** [comment]
報告しました。

**Comment by mattn** [comment]
@ynkdir thanks.

**Comment by h-east** [comment]
https://groups.google.com/d/topic/vim_dev/_W7fClpoULk/discussion

todoリスト入り。

> Problem with winfixheight and resizing. (Yukihiro Nakadaira, 2011 Sep 17)
> Patch Sep 18.

**Comment by h-east** [comment]
Patch 7.3.1246 で取り込まれました！1年4ヶ月！
https://groups.google.com/d/msg/vim_dev/Y7uayQBcPnk/DjZj9DX_1nQJ
