### ISSUE TITLE
コマンドラインが勝手にスクロールする様になった

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1003]
## 質問・報告の内容

以前は発生していなかったが、おそらく job/channel/timer が入ったあたりで画面再描画が走る様になっている？

![コマンドラインの動作が勝手にスクロールする様になった](https://cloud.githubusercontent.com/assets/10111/21635801/1c3dcc80-d2a3-11e6-922d-a1cfe470c7e3.gif)

再現方法は、コマンドラインで複数行のマルチバイトを入力します。てか1行目から変ですが。以前(job/channel/timerが入る前の頃？)はちゃんと動いていました。

## Vimのバージョン

8.0.134

## OSの種類/ディストリ/バージョン

*   Windows 7 64bit

## 使用している or 関係していそうなプラグイン

なし

**Comment by mattn** [comment]
ちなみに gvim.exe でも発生します。

**Comment by koron** [comment]
`cmdheight` の値はいくつになっていますか?

手元の `cmdheight=2` の 8.0.142 の gvim.exe では再現しなかったので。

**Comment by koron** [comment]
vim.exe では(壊れ方は異なりますが)再現できました。
なんか…MS IMEの描画が位置がアレなのかなぁ?

**Comment by mattn** [comment]
gvim の場合のキャプチャです。

![gvimの場合](https://cloud.githubusercontent.com/assets/10111/21667520/169affa6-d33d-11e6-907a-69272817e6db.gif)

**Comment by koron** [comment]
ありがとうございます。

でも僕の手元では再現できていませんね。
…なにがちがうんだろう?

**Google IME でのキャプチャ**

![Google IME](https://cloud.githubusercontent.com/assets/468368/21667783/2534b046-d33f-11e6-9166-edc40b04ad8a.gif)

**MS IME でのキャプチャ**

![MS IME](https://cloud.githubusercontent.com/assets/468368/21667792/36ab34bc-d33f-11e6-8686-4fa4de17f251.gif)

**Comment by mattn** [comment]
むむむーーーーーーーーーーー

**Comment by mattn** [comment]
bisect してます。。。

**Comment by itchyny** [comment]
`call timer_start(1000, 'len', { 'repeat': -1 })` したらmacOS (Vim 8.0.142) でも再現しましたが、timerを 発動せずに起こる事象ならば別問題かもしれません。

**Comment by mattn** [comment]
そして HEAD まで戻したら再現しないというアレ

**Comment by mattn** [comment]
再現しなくなってしまったので閉じます。
