### ISSUE TITLE
関数内の ":change" の扱いがおかしい

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1004]
### 1. `:change` のテキストの中に `py <<EOS` など「次行以降がExコマンドではない」コマンドを書くと、`:source` 時にエラーになる。(`EOS` で終端してない場合)

test1a.vim:

```vim
function! F()
  change
py <<EOS
.
endfunction
```

`vim -Nu NONE -S test1a.vim`

```
Error detected while processing /tmp/test1a.vim:
line    6:
E126: Missing :endfunction
```

`:append` や `:insert` では問題ない。

test1b.vim:

```vim
function! F()
  append
py <<EOS
.
endfunction
```

`vim -Nu NONE -S test1b.vim`

### 2. 終端文字 `.` を書かなくてもエラーにならない。

test2a.vim:

```vim
function! F()
  change
123
endfunction
```

`vim -Nu NONE -S test2a.vim`

関数呼び出しも可能。`endfunction` 直前までが `:change` のテキストになる。

```
:call F()
" カーソル下が "123" で置換される
```

`:append`, `:insert` では (期待通り) エラーになる。

test2b.vim:

```vim
function! F()
  append
123
endfunction
```

`vim -Nu NONE -S test2b.vim`

```
Error detected while processing /tmp/test2b.vim:
line    5:
E126: Missing :endfunction
```

## Vimのバージョン

8.0.0142

## 原因

https://github.com/vim/vim/blob/0cdb72a/src/userfunc.c#L2088-L2093
関数定義のパース (`ex_function`) では、`:append`, `:insert` や `:python` など「次行以降がExコマンドではない」コマンドが現れた場合、対応する終端文字まで行をスキップする。
ここで `:change` を扱っていないのが原因。

## その他

`git blame` で見ていくと 7.0 まで遡れた。

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/change-in-func
とりあえず修正だけ。
テストは tes49.vim や test_viml.vim あたりを参考にすればいいでしょうか？

**Comment by ichizok** [comment]
テスト追加して投げました。
https://github.com/vim/vim/pull/1374

**Comment by mattn** [comment]
8.0.0176

https://github.com/vim/vim/commit/70bcd7336f9f19304f32c52a86ed5b4b3de852c2
