### ISSUE TITLE
cursorbind時にcursorline, cursorcolumn が追従しない

### ISSUE THREAD

**Issue by mmisono** [vim-jp/issues#1009]
## 質問・報告の内容

仕様なのかもしれませんが，`set cursorbind`, `set cursorline`, `set cursorcolumn`を2つのウィンドウで設定しているとき，片方のウィンドウでカーソルを動かしてもスクロール等のイベントが発生しない限りもう片方のウィンドウのcursorlineとcursorcolumnが動きません．

![動作例](https://cloud.githubusercontent.com/assets/186170/21763048/3a464a72-d69f-11e6-847e-554f125ca71f.gif)

両方のウィンドウで動いた方が直感的な動作であると個人的には思います．
（その分オーバーヘッドが生じますが)

## Vimのバージョン

8.0.142

## OSの種類/ディストリ/バージョン

*   macOS Sierra 10.12.2

## 使用している or 関係していそうなプラグイン

`vim -N -u NONE`で動作検証しています．

## その他

以下の修正で目的の動作をすることを確認していますが，正しい修正方法かは分からないです．

```diff
diff --git a/src/move.c b/src/move.c
index 912e51ccd..694674b7b 100644
--- a/src/move.c
+++ b/src/move.c
@@ -2841,13 +2841,20 @@ do_check_cursorbind(void)
 	    restart_edit_save = restart_edit;
 	    restart_edit = TRUE;
 	    check_cursor();
+#ifdef FEAT_SYN_HL
+	    if(curwin->w_p_cuc)
+		validate_virtcol();
+#endif
 	    restart_edit = restart_edit_save;
 # ifdef FEAT_MBYTE
 	    /* Correct cursor for multi-byte character. */
 	    if (has_mbyte)
 		mb_adjust_cursor();
 # endif
-	    redraw_later(VALID);
+	    if(curwin->w_p_crb)
+		redraw_later(NOT_VALID);
+	    else
+		redraw_later(VALID);
 
 	    /* Only scroll when 'scrollbind' hasn't done this. */
 	    if (!curwin->w_p_scb)
```

![修正後](https://cloud.githubusercontent.com/assets/186170/21763066/4f08d8a8-d69f-11e6-83a6-33ecd6585cd2.gif)

**Comment by mattn** [comment]
スクロールすると更新されるという動作から、vim としては意図しない動作(バグ)な気もします。

**Comment by h-east** [comment]
@mmisono issue登録ありがとうございます:+1:
私も不具合だと思うのでpatchを投げてみる価値はあると思います。
(patch、ちゃんとチェックしてませんが大丈夫そう)

**Comment by mattn** [comment]
@mmisono 僕も良いと思います。pull-requst 投げて頂いて良いですか？万が一、面倒 or 英語苦手 or 宗教上の理由でNG、などあればご相談下さい。代行可能です。

**Comment by mmisono** [comment]
コメントありがとうございます．
今vimは普通にgithubでpull-request受け付けてるんでしたかね．
少し確認してから投げてみます．

**Comment by mattn** [comment]
8.0.181
https://github.com/vim/vim/commit/519d7785f4437762c07b2e04217f83a069a8c663

**Comment by mmisono** [comment]
あれ，

```diff
+# ifdef FEAT_SYN_HL
+	    if (curwin->w_p_cuc)
+		validate_cursor();
+# endif
```

だと `cursorclumn`設定しているときはいいけれど `cursorline` だけのときは動かないような..

**Comment by h-east** [comment]
@mmisono いまさっきBramに突っ込み入れました。
https://groups.google.com/d/msg/vim_dev/JxpsXs5U77I/1Tb3DKH7BwAJ

**Comment by mattn** [comment]
修正コードがコメント欄で書かれてたからパッチも更新されてたと思ってた疑惑。

**Comment by mmisono** [comment]
ありがとうございます．
今手元で確認しましたがやはり`cursorline` && `cursorbind`だけのときは動かないですね
if文なしで`validate_cursor()`を呼べば`cursorline` && `cursorbind`でもokなことは確認してるんですが

**Comment by mmisono** [comment]
```c
	    if (curwin->w_p_crb
# ifdef FEAT_SYN_HL
	       || curwin->w_p_cuc
# endif
	       )
		validate_cursor();
```

こうしてあげればいいんですかね．
もしかして`validate_cursor()`が `FEAT_SYN_HL`じゃないと呼べないとかあると困りますが..

**Comment by h-east** [comment]
@mmisono `curwin->w_p_crb`は22行上のif文で判定済みなので不要です。

> もしかしてvalidate_cursor()が FEAT_SYN_HLじゃないと呼べないとかあると困りますが..

それはないです。大丈夫です。

正解patch(maybe)を送付済みです。
https://groups.google.com/d/msg/vim_dev/JxpsXs5U77I/-766ESz9BwAJ

**Comment by mmisono** [comment]
あ，`w_p_crb`じゃなくて`w_p_cul`でしたね，ありがとうございます．

**Comment by mmisono** [comment]
patch 8.0.0182
vim/vim@e47683a

結局`cursorline`のときは`NOT_VALID`でredrawするように修正されたようです．
個人的にこの機能が最近欲しいことがあったので良かったです． mattnさん，h-eastさんありがとうございました!

**Comment by h-east** [comment]
patch 8.0.0188
https://github.com/vim/vim/commit/9506cad7a1a6e52a613f356de969cbd980815777

**Comment by mmisono** [comment]
vim-dev送ったのが反映されないと思ったら，初回だったので承認が必要だったんですね
あぁ，メールでも culにしたつもりがcrbになっていた.. (というか一番最初のパッチから間違えてましたね)

**Comment by mmisono** [comment]
あれしかし今度は `#ifdef FEAT_SYN_HL` で囲んでないけどいいんだろうか.. (他で `curwin->w_p_cuc`  読むことろはしている)

関数自体が `#if defined(FEAT_CURSORBIND) || defined(PROTO)` となってるからいいとかそういう話かな

**Comment by h-east** [comment]
@mmisono 私も「ん？」と思ったんですが、Travis CIで`tiny`も含む全featureのビルドがパスしているので大丈夫だと判断しました。。。(続く)

feature.h
```c
#if defined(FEAT_NORMAL) || defined(PROTO)
# define FEAT_SYN_HL
#endif
```
feature.h
```c
#if defined(FEAT_NORMAL) && defined(FEAT_WINDOWS)
# define FEAT_CURSORBIND
#endif
```

でも、直接`FEAT_SYN_HL`をundefされたらアウトですね。やっぱり囲んでおいたほうが良さげです。
patchお願いできますか？

**Comment by mmisono** [comment]
分かりました，送ってみます

**Comment by mmisono** [comment]
vim/vim@1b9750d

今度こそ大丈夫なはず.. (結局h-eastさんのパッチで良かったですね 😅 ）
