### ISSUE TITLE
cursorbind時に'c'オプションで置換した際カーソルが同期しない

### ISSUE THREAD

**Issue by mmisono** [vim-jp/issues#1013]
## 質問・報告の内容

`cursorbind` がonの時に'c'オプション付きで置換を実行した場合，置換が終了するまで片方のウィンドウのカーソルが動きません．

![sub_before](https://cloud.githubusercontent.com/assets/186170/22054531/5e74ec90-dd99-11e6-867e-4fe08157d9b9.gif)

## Vimのバージョン

8.0.206

## OSの種類/ディストリ/バージョン

*   macOS Sierra 10.12.2

## 使用している or 関係していそうなプラグイン

`vim -N -u NONE`で動作検証しています．

## その他

通常のsearchは動きます

![search](https://cloud.githubusercontent.com/assets/186170/22054575/98d102a2-dd99-11e6-8e46-166d6d16473b.gif)

**Comment by mmisono** [comment]
暫定パッチ

```diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 00cac9256..5b9a79f5d 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -5263,6 +5263,7 @@ do_sub(exarg_T *eap)
                    setmouse();         /* disable mouse in xterm */
 #endif
                    curwin->w_cursor.col = regmatch.startpos[0].col;
+                   do_check_cursorbind();

                    /* When 'cpoptions' contains "u" don't sync undo when
                     * asking for confirmation. */
```

![sub_after](https://cloud.githubusercontent.com/assets/186170/22054634/e7894940-dd99-11e6-86af-b80d514978eb.gif)

**Comment by mmisono** [comment]
こうすべきでした

```c
#ifdef FEAT_CURSORBIND
	if (curwin->w_p_crb)
	    do_check_cursorbind();
#endif
```

**Comment by h-east** [comment]
@mmisono  良いと思います:+1:

**Comment by mmisono** [comment]
vim/vim#1396

**Comment by mmisono** [comment]
bram氏に納得してもらって取り込まれました (ﾖｶｯﾀ) vim/vim@41baa79
