### ISSUE TITLE
文字の途中の折り返しで、記号を追加表示したくない

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1015]
## 質問・報告の内容

折り返しが ON だと、文字の途中で折り返される時に、その折り返された位置に記号が表示されます
この表示をなくしたいのですが、そのような設定は可能でしょうか?

これについては、設定がなければ、それで良いのですが、この折り返し時に、見かけ上の次行行頭に「<<」が表示されます
これも表示されるだけなら、まだ良いのですが、カーソル位置と実際の編集箇所が、その余分に表示された「<<」の分だけずれます

再現方法は、
$ vim -N -u NONE +"set wrap linebreak breakat+=>"
で実行し、文字の途中で折り返されるような文字を入力する
例えば、Gvimなら
$ gvim -N -u NONE +"set columns=19 wrap linebreak breakat+=>"
で起動して、
あいうえおかきくけこさしすせそ
と入力すると、「け」の後ろで折り返され「こ」の前に「<<」が表示される
そしてカーソルを「さ」に合わせて [x] をタイプすると、「し」が消える
最後のオプションで「>」が含まれるか否かがトリガーのようです

カーソル位置と別の場所が消えたりするのはバグな気がしますが、取り敢えず「<<」の表示を無くすことは出来ないでしょうか?
:set all
で「<」が設定されてそうな場所を探してみたのですが、解りませんでした
## Vimのバージョン

$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 22:32:42)
適用済パッチ: 1-1829
追加拡張パッチ: 8.0.0056

## OSの種類/ディストリ/バージョン

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
$ uname -a
Linux naonari-note 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## 使用している or 関係していそうなプラグイン

なし

**Comment by Shougo** [comment]
`:help listchars`

listchars オプションが設定されているのだと思います。
私が見た限り行頭に表示されているのは lcs-precedes だと思いますが、その設定を確認してみてはどうでしょう。

> カーソル位置と別の場所が消えたりするのはバグな気がしますが、取り敢えず「<<」の表示を無くすことは出来ないでしょうか?

これはバグに見えますね

**Comment by sgur** [comment]
> listchars オプションが設定されているのだと思います。
私が見た限り行頭に表示されているのは lcs-precedes だと思いますが、その設定を確認してみてはどうでしょう。

冒頭に"折り返しが ON"と明記されておられるので、`list`および `listchars` の `precedes` も関係ないと思います。(`precedes` は `&nowrap` のときのみ有効です)

`&columns` が奇数の時で、かつ、マルチバイト文字を入力したときだけ再現(`<<`が行頭に表示される)ので、そこに関連した不具合に見えます。

**Comment by iranoan** [comment]
回答有り難うございます

>listchars オプションが設定されているのだと思います。
>私が見た限り行頭に表示されているのは lcs-precedes だと思いますが、その設定を確認してみてはどうでしょう。

上記の起動方法だと
:set listchars
の結果は、規定の
listchars eol:$
です

また念の為ですが、
>&columns が奇数の時で、かつ、マルチバイト文字を入力したときだけ再現(<<が行頭に表示される)ので、そこに関連した不具合に見えます。

先に投稿はあくまで例なので
$ gvim -N -u NONE +"set columns=19 wrap linebreak breakat+=>"
ではなく、&columnsを偶数
$ gvim -N -u NONE +"set columns=20 wrap linebreak breakat+=>"
として起動し、例文を
aあいうえおかきくけこさしすせそ
などと折り返し位置に全角文字が来るようにすれば、同様の現象が起きます

とりあえずは、breakatには「>」を入れないでおくしかないのかな？

**Comment by sgur** [comment]
`'breakat'` をヘルプで調べました。その中で、

> Only works for ASCII and also for 8-bit characters when 'encoding' is an 8-bit encoding.

という一文があり、`breakat` オプション自体は日本語のようなマルチバイト文字列を含むバッファでは機能しないようです。 
そのため、今回のような用途には利用できないように思われます。

> 折り返しが ON だと、文字の途中で折り返される時に、その折り返された位置に記号が表示されます
この表示をなくしたいのですが、そのような設定は可能でしょうか?

表示をなくしたいのは、折り返し時の行末の `>` や行頭の `<` の記号でしょうか?

今回の再現条件で、行末に '>', 行頭に `<` が表示される点については、折り返し位置付近にマルチバイト文字が含まれ、その文字の境界ではないカラムで折り返しが発生し、文字を正常に描画できない場合に空いたスペースに強制的に表示しています(ソース内にハードコードされています)。
そのため、それらの表示を消すことはできないようです。


コードを読んでいて気付いたのですが、今回の件にまつわる不具合(行頭に`<<`が表示され、編集位置がずれる)については複数の原因があるように見えてきました…

1. [screen.c#L4550](https://github.com/vim/vim/blob/master/src/screen.c#L4550) で、バッファがマルチバイトエンコーディングかどうかの判定をせずに `vim_isbreak()` の判定を行っている
2.  上記説明のように、行末で桁が満たない場合に `>` を表示しているが、本来バッファにないインジケータとしての  `>` を`breakat` の条件で折り返し判定してしまっており、表示内容と実際のバッファにずれが生じてしまっている。
  ([screen.c#L4178](https://github.com/vim/vim/blob/master/src/screen.c#L4178) や [screen.c#4367](https://github.com/vim/vim/blob/master/src/screen.c#L4367) の `>` をたとえば '#' に書き換えると今回の問題は発生しなくなります)

2 について、もともとマルチバイト文字のバッファでなければ行末に `>` は表示されず、 `breakat` に `>` を追加しても問題は発生しないため、それを想定してコーディングされている可能性もあります。よいかどうかは別として、そうであれば変更しない方がいいのかな…

修正については 1 の点のみであれば簡単そうですが、2も直そうとすると難しそうです。

**Comment by iranoan** [comment]
>表示をなくしたいのは、折り返し時の行末の > や行頭の < の記号でしょうか?

両方ですが、「<<」のみでも十分です

>今回の再現条件で、行末に '>', 行頭に < が表示される点については、折り返し位置付近にマルチバイト文字が含まれ、その文字の境界ではないカラムで折り返しが発生し、文字を正常に描画できない場合に空いたスペースに強制的に表示しています(ソース内にハードコードされています)。
そのため、それらの表示を消すことはできないようです。

この記号については、そもそも設定ではないんですね
ソースコードまで調べて頂きありがとうございます


![wrap](https://cloud.githubusercontent.com/assets/24851657/22289976/b48ad2f4-e341-11e6-952a-9e2c3e10515e.png)
の様に、日本産エディタに比べてvimはマルチバイトの折り返しが弱点ですね
breakatにマルチバイトは指定できないし…(日本語句読点が全てダメorz)
「見かけ上の1,2行目にはもっと文字を表示できるのに」と思ってしまう

修正すべきかどうかも私には分からないので、暫くはbreakatから>を除外して使うことにします

**Comment by ichizok** [comment]
> Only works for ASCII and also for 8-bit characters when 'encoding' is an 8-bit encoding.

これは、 `'breakat'` に指定できるのは ASCII (と `[0x80-0xff]`) に限るという意味ではないでしょうか？
バッファの内容は関係ないと思うのですが。

**Comment by ichizok** [comment]
```diff
diff --git a/src/screen.c b/src/screen.c
--- a/src/screen.c
+++ b/src/screen.c
@@ -4547,7 +4547,8 @@ win_line(
                /*
                 * Found last space before word: check for line break.
                 */
-               if (wp->w_p_lbr && vim_isbreak(c) && !vim_isbreak(*ptr))
+               if (wp->w_p_lbr && vim_isbreak(*(ptr - 1))
+                                                       && !vim_isbreak(*ptr))
                {
 # ifdef FEAT_MBYTE
                    int mb_off = has_mbyte ? (*mb_head_off)(line, ptr - 1) : 0;
```

例示のケースに限ればこれで直りますが、影響範囲が不明（ダメな気がする）

**Comment by ichizok** [comment]
調査中に見つけたバグ

```
printf '\x80\x80' > sample.txt
vim -Nu NONE +'set linebreak breakat+=<' sample.txt
```

表示が `<<<<<<<<` になる。一応、上のパッチで直ります。

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/linebreak_mb.diff
修正＆テスト追加

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/1456
投げました

**Comment by ichizok** [comment]
8.0.0380
https://github.com/vim/vim/commit/38632faf635f6434441827e136bceb5a930c59ad
