### ISSUE TITLE
TeX シンタックスファイルの閉じ括弧抜け

### ISSUE THREAD

**Issue by yamacir-kit** [vim-jp/issues#1017]
## 質問・報告の内容

texファイルを編集しようとしたところ、
`Error detected while processing /usr/share/vim/vim80/syntax/tex.vim`
`line  514:`
`E697: Missing end of List ']':`
`E15:  Invalid expression : s:texMathDelimList + [ ['\\langle' , ' <'] , ['\\rangle' , '> '] ,`
のようにエラー表示が出ました。

https://github.com/vim/vim/blob/master/runtime/syntax/tex.vim
の514行目の閉じ括弧がカンマになっているようで、
該当箇所を適当に書き換えたらエラー表示は出なくなりました。

## Vimのバージョン

8.0.267

## OSの種類/ディストリ/バージョン

Ubuntu 16.04

**Comment by h-east** [comment]
Issue登録お疲れ様です:+1:

vim_dev(とメンテナのDr.Chipさん)に報告しました。
https://groups.google.com/d/msg/vim_dev/v8FfVAZcew0/y7ETf4liDAAJ

**Comment by yamacir-kit** [comment]
ありがとうございました

**Comment by h-east** [comment]
Fixed.
https://github.com/vim/vim/commit/3df0173fa6d0418e89ef4e9c1d04a97c92eec27c#diff-9aa7419d9504f85f995d943175f49e46R514

@YamaCIR-KIT Thanks:+1:
