### ISSUE TITLE
 'LINE SEPARATOR' (U+2028) を含むファイルを開くと文字化けします。

### ISSUE THREAD

**Issue by KusakabeYouichi** [vim-jp/issues#1019]
## 質問・報告の内容
UTF-8 (BOMなし) 改行コードCR/LFのファイルの中に 'LINE SEPARATOR' (U+2028) が含まれているファイルをgvim.exeで開くと、どういうわけかShiftJISと判断して開いてしまい、文字化けします。

なにかいい解決方法はないでしょうか?

## Vimのバージョン
8.0 (2016 Sep 12, compiled Jan 1 2017 13:45:57)

## OSの種類/ディストリ/バージョン
*   Windows 10 Pro 32bit (10.0.10586)

## 使用している or 関係していそうなプラグイン
なし

**Comment by mattn** [comment]
```
:set encoding? fileencodings?
```
の結果を教えて貰えますでしょうか。

**Comment by k-takata** [comment]
ご本人からの反応がありませんし、手元では再現しなかったので閉じます。
