### ISSUE TITLE
win32: 環境変数の取得がユニコードに対応してない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1020]
## 質問・報告の内容

環境変数の取得に wgetenv() を使用していないため、cp932 で表せない文字を正しく取得できません。

## Vimのバージョン

8.0.0280

## OSの種類/ディストリ/バージョン

Windows

## その他

#108 の派生です。

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/4008

**Comment by k-takata** [comment]
これでこんなのが動くようになりました。

```
:let $a='Ā'
:echo $a
Ā
```

ただ、VCでコンパイルした場合、外部で設定したUnicode環境変数を表示させると `?` に化けてしまいました。
`wWinMain()` を使うようにして、Wide版のスタートアップルーチンを使うようにする必要がある模様。
MinGWの場合は、`WinMain()` のままでも問題なさそう。

**Comment by mattn** [comment]
`vim.exe` の方も `wmain` になる感じですか？

**Comment by k-takata** [comment]
試してないですが、おそらくそうです。

**Comment by k-takata** [comment]
本当は `mch_getenv()` の部分でUnicode対応させたいところだが、無理そうだったので、`vim_getenv()` の部分で対応。

**Comment by k-takata** [comment]
8.1.1091: https://github.com/vim/vim/commit/f0908e6fe18943ad4453d7d6772fa43049aff4bc

**Comment by k-takata** [comment]
外部で設定したUnicode環境変数を表示できないのはどうするか…

**Comment by k-takata** [comment]
#1256 を立てたので、こちらは閉じます。
