### ISSUE TITLE
deinでのプラグイン追加（vim-easy-align）

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#1021]
## 質問・報告の内容

Vim歴はそこそこあるのですが，初めてプラグインマネージャーを使う者です。

Qiitaを参考にdeinをインストールしました。
http://qiita.com/yoza/items/2f8bd33a18225754f346

.gvimrcに

`set nocompatible`
`set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim`
`call dein#begin(expand('~/.vim/dein'))`
`call dein#add('Shougo/dein.vim')`
`call dein#add('junegunn/vim-easy-align')`
`call dein#end()`
`filetype plugin indent on`
`if dein#check_install()`
`  call dein#install()`
`endif`
`vmap <CR> <Plug>(EasyAlign)`

と書くとvim起動時にターミナルに

`[dein] Not installed plugins: ['vim-easy-align']`
`[dein] Update started: (2017/02/03 14:03:36)`
`[dein] Updated plugins:`
`[dein]   vim-easy-align(1 change)`
`[dein] Done: (2017/02/03 14:03:43)`

と表示されますが，設定したvmapでは何も起きないです。
このような場合どこから手を付ければよいでしょうか。

## Vimのバージョン

MacVim-KaoriYa 8.0 (2016 Sep 12, compiled Jan 25 2017 16:49:56)
適用済パッチ: 1-237

## OSの種類/ディストリ/バージョン

Mac OS Yosemite 10.10.5

## 使用している or 関係していそうなプラグイン

香り屋版デフォルトだと思われるプラグイン（TOhtmlなど）以外は未使用

**Comment by kashewnuts** [comment]
2点あります。これで想定されていた動作をするかと思います。
- これらの設定は`.gvimrc`でなく`.vimrc`に記述してください。
- `filetype plugin indent on`の直後に`syntax enable`を追記してください。(`syntax on`でも可)

`.gvimrc`はGUIの設定について書くべきものです。
プラグインマネージャーの設定をこちらに書くと動きませんでのでご注意ください。

Qiitaは有用な記事もありますが、公式のドキュメントにあたるのが一番速いことも多いので、
今後プラグインを導入される際はそちらから当たるのが得策かと思います。

- [Shougo/dein.vim: Dark powered Vim/Neovim plugin manager](https://github.com/Shougo/dein.vim)
- [junegunn/vim-easy-align: A Vim alignment plugin](https://github.com/junegunn/vim-easy-align)

**Comment by ghost** [comment]
ありがとうございます。公式サイトも見ていたのですが，`.vimrc`が落とし穴だとは想像もしていませんでした。無事動きました。

`syntax`は明示的に`enable`にはしていないですが，今も拡張子に応じてハイライティングされている（`enable`になっているっぽい）のでよしとしました。`.vimrc`と`.gvimrc`の使い分けは今一度整理するようにします。

ありがとうございました。

**Comment by kashewnuts** [comment]
Thanx!
