### ISSUE TITLE
パッケージ機能でプラグインを読み込むとruntimepathの$VIMRUNTIMEの後にパスが追加される

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#1022]
## 質問・報告の内容

\~/.vim/がシンボリックリンクのときVimのパッケージ機能を使用してプラグインを読み込むと、プラグインのパスがruntimepathに追加されるときに$VIMRUNTIMEの後ろに追加されてしまいます。

そのためプラグインにftplugin/\*.vimが含まれている場合、先に$VIMRUNTIME/ftplugin/\*.vimが実行されてb:did_ftpluginが定義されるので、プラグイン側のftplugin/\*.vimの処理が途中でfinishされてしまいます。

```vim
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1
```

---

### 再現方法

\~/sample/.vim/pack/dist/start/foo/plugin/を作成します。
\~/sample/.vim/pack/dist/opt/bar/plugin/を作成します。
\~/sample/.vim/のシンボリックリンク\~/.vim/を作成します。
```
mkdir -p ~/sample/.vim/pack/dist/start/foo/plugin/
mkdir -p ~/sample/.vim/pack/dist/opt/bar/plugin/
ln -s ~/sample/.vim/ ~/
```

Vim起動
```
vim -c "packadd bar" -c "set rtp"
```

:set rtpの結果
私の環境では/usr/local/share/vim/vim80が$VIMRUNTIMEです。
```
  runtimepath=~/.vim,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim80,/usr/local/share/vim/v
imfiles/after,~/.vim/after,~/sample/.vim/pack/dist/start/foo,~/sample/.vim/pack/dist/opt/bar
```

\~/.vim/がシンボリックリンクではない場合の:set rtpの結果も載せます。
プラグインのパスが$VIMRUNTIMEよりも前に追加されております。

```
  runtimepath=~/.vim,~/.vim/pack/dist/opt/bar,~/.vim/pack/dist/start/foo,/usr/local/share/vim/vimfil
es,/usr/local/share/vim/vim80,/usr/local/share/vim/vimfiles/after,~/.vim/after
```

## Vimのバージョン

8.0.300

## OSの種類/ディストリ/バージョン

*   Linux Debian 8.7 jessie 64bit

**Comment by h-east** [comment]
調査完了しました。
5行くらいのpatchで直ります。今からpatch書きます。

**Comment by h-east** [comment]
patchです。動作確認をお願いします。(エラー処理とか入れたら25行くらいになってしまった。。)
https://gist.github.com/h-east/73f4ace9001bd18ba9719f98082cefa2

testは後で書きます。

**Comment by h-east** [comment]
このバグって「ディレクトリをフルパスに変換するけどシンボリックリンクは辿らない」という関数があれば1行で直るんです。見つけたら(or 作ったら)教えて下さい。

**Comment by norio13** [comment]
ありがとうございます。
vimrcの中でpackadd! barするのとpackloadallも含めて$VIMRUNTIMEより前にパスが追加されるのを確認できました。

**Comment by h-east** [comment]
I add a test and sent to vim_dev.
https://groups.google.com/d/msg/vim_dev/oJ1xtuVNj1k/NI44NizlDQAJ

**Comment by h-east** [comment]
patch 8.0.0308
https://github.com/vim/vim/commit/2f9e575583c2ad3978ee3d0f790eeff7df56bd6c

**Comment by norio13** [comment]
迅速なご対応ありがとうございます。
