### ISSUE TITLE
\%Vを使用して選択範囲内の文字列を検索した場合に選択範囲内の末尾の文字にマッチしない

### ISSUE THREAD

**Issue by rapan931** [vim-jp/issues#1023]
## 質問・報告の内容

(はじめまして。)
\\%Vを使用し、以下の手順で選択範囲内の文字列を検索した場合に
選択範囲内の末尾の文字とマッチしません。

1. vim -Nu NONE
2. ifoo123bar\<ESC\>
3. ggvE\<ESC\>           " foo123barを選択してESC 
4. /\\%Vfoo.*bar\\%V  " -> foo123barと一致してほしいが、一致しない(E486が出る)
5. /\\%Vfoo.*ba\\%V   " -> foo123baとなら一致する
6. /\\%Vr\\%V   " -> rも一致しない(E486が出る)

手順4ではfoo123barと、手順6ではrとマッチすることが期待値だと思ったのですが、
こちら仕様通りの動作なのでしょうか？
すみませんが、確認をお願いします。

## Vimのバージョン

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 13 2016 15:11:28)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-82

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit

## 使用している or 関係していそうなプラグイン

なし

## その他

手順3をggV(行選択)とすると、手順4、手順6でマッチします。
また、手順3をggvEl(r上にカーソルがある状態で一つ右にカーソルを移動)でも手順4、手順6でマッチします。

**Comment by ghost** [comment]
今さっきからまずはコードを眺めてみたところ仕様通りであると思いますが、
どうやらヘルプのどこに書いてあるというものではないようです。

set selection=inclusive (vim -Nu NONE で起動)
の選択状態と
set selection=exclusive (ヘルプの :behave mswin を参照ください)
の選択状態を比較してみてください。
カーソル直下の文字が前者では選択範囲に入り、後者では選択範囲に入りません。
おそらく検索前に ESC を押下せず / で検索を開始することが期待されているのかと思います。

exclusive の状態で ggvE から ESC をすることで検索範囲が inclusive と同じに縮んでしまうことも
仕様のうちのようなコードになっている風に見えますが(範囲を伸ばすようには書かれていません)、
取り急ぎ確認まで…。

**Comment by rapan931** [comment]
@ntak 調査していただきありがとうございます！
また、'selection'というものは初めて知りました。こちらについても情報ありがとうございます。

> おそらく検索前に ESC を押下せず / で検索を開始することが期待されているのかと思います。

こちら手順3を'ggvE'として\<ESC\>せずに手順4の/\\%Vfoo.*bar\\%Vを実行しても
状況変わらずでした。。

**Comment by h-east** [comment]
@rapan931 Issue登録お疲れ様です。これはバグです。
遅くなりましたが、patchを書きましたので確認をお願いします。

https://gist.github.com/h-east/5f9b43d1a07362fd08ad3a9874ffd39f

**Comment by rapan931** [comment]
@h-east 対応ありがとうございます！

vimにpatchあてたことないので、少し時間かかるかもしれませんが、頑張って確認します！

**Comment by rapan931** [comment]
patch適用で期待する動作になる(手順4でマッチする)ことを確認できました。

**Comment by h-east** [comment]
@rapan931 確認Thanks.
上のpatch (rev.3)が不十分だったことに気付きましたorz
```
ifoo123bar<Esc>
0f1vf3<Esc>
/\%V123\%V
```
で見つからないと言われてしまう。
patchを更新しました。(rev.4)
~~~このpatchで良いと思うんですが~~~ ←ダメpatchです、`make test`が`test64`でコケてしまうので今それを調べています。
しばらくお待ちを。

**Comment by ichizok** [comment]
実際のところ、 `\%V` は「`\%V` に続く文字が選択範囲内にあるときにマッチする」という動作になっています。
e.g. `/\%Va` は `a` が選択範囲内の時マッチ
なので、`foo.*bar` が選択範囲にあることを調べるパターンは `\%Vfoo.*ba\%Vr` となります。
この動作を変えない場合、help を修正すべきということになります。

または、`\%V` が「文字の間にマッチする」かのように動作を変更するという方針もあります。
h-east さんのパッチ (rev.4) がこれに相当しますが、このように変更した場合、

```vim
" '123123' を入力
normal i123123
" 最初の '123' を選択
normal 0vf3
/\%V1
```

このように、最初の `123` を選択して `\%V1` を検索すると、2つ目の `1` にもマッチします。
2つ目の `1` の手前（つまり、`3` と `1` の間）まで選択範囲が存在するためです。
これは明らかに動作の互換性を崩します。実際、そのために test64 は失敗します。

**Comment by h-east** [comment]
フォローありがとうございます。
はい、私は前のコメントを書いた後でichizokさんが言われているような問題に気付いたので、コードを解析してローカルでpatchを更新したりしていました。ただ、満足のいくpatchが書けていないのでこちらには状況をコメントしていませんでした。
これ結構ムズいですね。

**Comment by h-east** [comment]
@ichizok 質問です。未patchのVimで
```vim
:set hlsearch
iabc123abc<Esc>
0f1vf3<Esc>0
/\%V
```
で`123`がhighlightするのって「\%V に続く文字が選択範囲内にあるときにマッチする」で説明つきます？

**Comment by ichizok** [comment]
`\%V` に続く文字がないときは `\%V.` のようになってますね...
ただ、他の zero-width atom も同じなので、動作として一貫性はあると思います。

**Comment by h-east** [comment]
ありがとうございます。
なるほど。`h /\%v` ←(小文字のv)のsampleが凄くわかり易いですね。
ということは、報告された件は「仕様通り」で https://github.com/vim-jp/issues/issues/1023#issuecomment-282550533 の通りなので、私は「help を修正すべきということになります。」が正しいという認識になりました。

問題なければ、 @ichizok さんの方でhelp修正patchを書いて頂けますか？
(都合悪ければ言ってもらえれば私の方でpatch書きます)

**Comment by ichizok** [comment]
@h-east 了解です。

**Comment by ichizok** [comment]
投げました。
https://github.com/vim/vim/pull/1533

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/214641f77df6f318a4b3a0b09723c19859a103f4 で取り込まれました。

以下ののコメントにあるとおり、まだ間違いがありますが、次回の更新で直る予定ですので閉じます。
https://github.com/vim/vim/commit/214641f77df6f318a4b3a0b09723c19859a103f4#commitcomment-21158455
