### ISSUE TITLE
[RFC]Windows で環境変数 HOME の設定をやめたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1024]
Windows 版の vim は起動後に内部的に $HOME を $USERPROFILE に設定します。

これにより誤動作を起こすツール類があります。例えば $HOME が設定されている場合は UNIX 的に動作し、設定されていない場合は Windows 的に動作するといった物です。

Vim script から参照する為に内部的に設定されていても良いとは思うのですが、起動前は設定されていなかったというフラグ(を追加したい)を見て、system() や `:!` 時に消す動作になって欲しいと思っています。

**Comment by koron** [comment]
そもそもどうして Vim は $HOME を設定しているんですかね?

`~` の展開では $USERPROFILE にすれば良いんですよね?
ただ互換性を考えると $HOME が設定されていればソレを、
されていなければ $USERPROFILE というふうにするんでしょうか…

**Comment by mattn** [comment]
個人的な推測では `expand('$HOME')` みたいな事をやってるプラグイン(例: Dr なんとか)があるので、いまさら消すのは難しいので vim から抜ける時(`system()` or `:!`) の時に元に戻してあげる(消す)のが良いのかなーと思っています。

**Comment by k-takata** [comment]
知らなかった。
他には、LANG, MYGVIMRC, MYVIMRC, VIM, VIMRUNTIME などが設定されているようですね。

**Comment by mattn** [comment]
https://github.com/vim/vim/issues/1946

**Comment by mattn** [comment]
https://travis-ci.org/mattn/vim/builds/267459170

で検証中

**Comment by k-takata** [comment]
おや、リンクがない。 vim/vim#2013

**Comment by k-takata** [comment]
今日のruntime fileの更新で、ヘルプが修正されてますね。
https://github.com/vim/vim/commit/c572da5f67aa5cdbbc127fc6f1d0a42e38468325#diff-ab1a6feaee576c9e64826bf9649453b6R70
>```
> - For Win32, $HOME is set by Vim if needed, see |$HOME-windows|.
>```

https://github.com/vim/vim/commit/c572da5f67aa5cdbbc127fc6f1d0a42e38468325#diff-9314fb84f930a1648810c882e8247e6fR423
> ```
> 							*$HOME-windows*
> On MS-Windows, if $HOME is not defined as an environment variable, then
> at runtime Vim will set it to the expansion of $HOMEDRIVE$HOMEPATH.
> ```

現状維持？

**Comment by mattn** [comment]
えーw

**Comment by Shougo** [comment]
仕様としてドキュメント化されてしまった？
プルリクエストはクローズされてないのでまだ可能性はあるのだろうか。

**Comment by k-takata** [comment]
> これにより誤動作を起こすツール類があります。

具体的にはどういうものがありますか？ $HOME の有無で動作を変えるようなツールの方が行儀が悪いという気もしなくもないですが。

> 個人的な推測では expand('$HOME') みたいな事をやってるプラグイン(例: Dr なんとか)があるので、いまさら消すのは難しいので

今のPRでは消しちゃってるようですが、問題なし？

**Comment by mattn** [comment]
消すというより、値が空にならない様にしてます。

|条件                        |vim内の$HOME    |外部コマンド上の%HOME%|
|----------------------------|----------------|----------------------|
|HOME を設定せずに vim を起動|HOME=USERPROFILE|HOME未設定            |
|HOME を設定して vim を起動 |HOME=設定値     |HOME=設定値           |

**Comment by mattn** [comment]
emacs がそれです。あと msys/mingw だと mingw32-make すると msys のシェルが起動しますが、その際に HOME があると問題が起きる事があります。そういったアプリケーションが

cmd.exe → それ

と

cmd.exe → vim.exe → :terminal → それ

で動作が変わってしまうのは問題あると思っています。

**Comment by k-takata** [comment]
> 消すというより、値が空にならない様にしてます。

PRのコード差分を軽く見ただけではそういう動作だとは気づきませんでした。(Bramの言っているように必要なコードを削除しちゃってるのではという感想。)
表の通りであれば、Bramの要求通りの動作だと思いますが、Bramにも伝わっていないようなので、そこの動作を説明した方がよいと思います。

**Comment by k-takata** [comment]
ヘルプは $HOME が設定されていなかったら、$HOMEDRIVE$HOMEPATH を見ると書かれていますが、その部分のコードを削除してしまって本当に問題ない？
$USERPROFILE を見るという点はヘルプに追記が必要でしょう。

あと、`vim_setenv`を削除しても問題がないのは、Vimの内部では`homedir_env`が $HOME として扱われているからでしょうか？

**Comment by mattn** [comment]
はい。たぶん次の bram からの返信で HOMEDRIVE HOMEPATH にするか USERPROFILE にするかの議論をしたいと思ってるのでそれまで変更は待つつもりです。

**Comment by mattn** [comment]
>あと、vim_setenvを削除しても問題がないのは、Vimの内部ではhomedir_envが $HOME として扱われているからでしょうか？

はい。設定しない事が大事だと思っていて、たとえばこれ vimproc でも影響がでるはずです。

**Comment by mattn** [comment]
影響が出ると言ったのは、現状 HOME がらみで起きている問題が(もしまだsetenvし続けるのであれば)今回の修正でも直らないという意味です。なのでsetenvをやめたい。

**Comment by k-takata** [comment]
あと、$HOME の中に他の変数への参照が含まれていた場合の処理を削除しているのはどういう理由でしょうか。

**Comment by mattn** [comment]
なおして HOMEDRIVE HOMEPATH 優先、USERPROFILE は fallback にしました。

**Comment by k-takata** [comment]
8.0.1012
https://groups.google.com/d/topic/vim_dev/VdcmP0TwPwo/discussion
マージはされましたが、ヘルプの修正が必要だと思います。
USERPROFILE も見るようにした点と、子プロセスには渡さないようにした点の2点？

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2039

**Comment by k-takata** [comment]
https://groups.google.com/d/topic/vim_dev/uaPmkEhTjeg/discussion
> Just as the comment says, now _viminfo cannot be saved on Windows.

`$HOME\_viminfo` ではなく、`$VIM\_viminfo` に保存されている？

**Comment by k-takata** [comment]
ex_cmds.c の viminfo_filename() で mch_getenv() を使って $HOME  を見て _viminfo の位置を決めている。
vim_getenv() には "HOME" を特別扱いするコードがあるが、それはここでは使っていない。

**Comment by k-takata** [comment]
8.0.1028
https://groups.google.com/d/topic/vim_dev/Uo8yiT3QVj0/discussion
起きたら直ってた。

**Comment by k-takata** [comment]
ヘルプも直ったようなので閉じます。
https://github.com/vim/vim/commit/37c64c78fd87e086b5a945ad7032787c274e2dcb#diff-9314fb84f930a1648810c882e8247e6fR426
