### ISSUE TITLE
:set visualbell の時に画面フラッシュが発生しない

### ISSUE THREAD

**Issue by ryunix** [vim-jp/issues#1026]
## 質問・報告の内容

まず、仕様整理をさせてください。
`:set novisualbell` の時に `h` キーを押し続けるなどでこれ以上カーソルが移動できない時にビープ音がなります。
このビープ音を画面フラッシュにする設定が `:set visualbell` だと理解しています。

この理解が正しい時、`:set visualbell` の時に画面フラッシュが発生しません。

起動時の `t_vb` の値は `t_vb=^[[?5h$<100/>^[[?5l` になっていました。
`:help 'visualbell'` にある通りの値である `<Esc>|f` を設定してみようと思いましたが、入力方法がよく分からず試せていません。(`CTRL-V_CTRL-[` の後に `|f` を入力し、`:set t_vb?` すると `^[` だけになっている...)

## Vimのバージョン

8.0.0314 (MacVim)

## OSの種類/ディストリ/バージョン

- macOS Sierra

## 使用している or 関係していそうなプラグイン

なし

## その他

使用している端末エミュレータは Terminal.app です。
環境変数 TERM は xterm-256color になっています。
gVim でも確認しましたが結果は同じでした。(起動時の `t_vb` の値は `^[|f` になっていました)

**Comment by h-east** [comment]
私の環境では画面フラッシュしました。
```bash
$ vim -Nu NONE +"set vb"
```
して `k` を入力で:sparkles::sparkles::sparkles::sparkles:

環境:
CUI Vim 8.0.0314 on fedora 25 via PuTTY
TERMはxterm-256color
t_vbの値も同じでした。

Terminal.app の設定かなにかあるんですかね？よく知らんけど
これの逆を設定すればいいのかな？
[How to disable flashing terminal in Mac OS](http://superuser.com/questions/201192/how-to-disable-flashing-terminal-in-mac-os/201193)

**Comment by mattn** [comment]
http://stackoverflow.com/questions/11657000/how-to-get-a-visual-bell-in-vim-on-mac

iTerm2.app とか Terminal.app とかは設定しないと駄目っぽいですがどうでしょう？

**Comment by ryunix** [comment]
ありがとうございます。
Terminal.app の設定を見直しましたが、ビジュアルベルを使用する設定になっていました。(既定値)
ただ、「消音時のみ」と言う気になるチェックボックスがあったので外してみましたが変わらずダメでした。
ちなみに、シェルで `<BS>` 連打によるこれ以上消せないよと言う時には画面フラッシュが発生しました。

![2017-02-09 9 43 58](https://cloud.githubusercontent.com/assets/7754313/22764164/4ca0aba2-eeac-11e6-963e-5ca5acb5156f.png)

**Comment by h-east** [comment]
念のため確認します。MacVimを`-Nu NONE +"set vb"`なコマンドライン引数で起動しても結果は同じでした？

**Comment by ryunix** [comment]
はい、それで起動させています。

**Comment by mattn** [comment]
@ryunix 端末で `echo -e "\a"` 実行するとどうなりますか？

**Comment by ryunix** [comment]
@mattn 画面フラッシュが発生しました。

**Comment by mattn** [comment]
なるほど、vim で bell ってない可能性が出てきましたね。

**Comment by ichizok** [comment]
試しに `let &t_vb = "\<Esc>[?5h$<2000/>\<Esc>[?5l"` としてみたら、`<BS>` 入力（visual bell 契機）から2秒後に `CSI ?5h` `CSI ?5l` がまとめて送られるという動作になっていました。
本来 `CSI ?5h` (画面色反転) 2秒後 `CSI ?5l` (戻す) となるべきところ、待機時間の発生位置がおかしいため、色反転が実行されてない (or 短すぎる) と思われます。

Terminal.app on macOS Sierra で確認

**Comment by ichizok** [comment]
vim は `t_vb` 送っているだけなので、端末側の問題かも。

**Comment by ryunix** [comment]
んんー、なるほど...？
Terminal.app を使っている限りはどうしようもないってことですかね。

**Comment by mattn** [comment]
バッファに入ってフラッシュしてないのかな。Terminal.app

**Comment by saitoha** [comment]
このくらいならttyドライバでバッファリングすると思います。
ttyをselect(2)する時に、だいたい1024とか4096byteとかで取ってくるので、
溢れない限りはtimevalで指定した時間待つんじゃないでしょうか。

なお、termiosのVMIN/VTIMEはキー入力の読み出しタイミングに影響する確かめたことがありますが、
出力にどう影響するかどうかは理解していません。

**Comment by saitoha** [comment]
>溢れない限りはtimevalで指定した時間待つんじゃないでしょうか。

・・・という仕様でしたっけ、select(2)。すいません、たぶん違いますね。

**Comment by saitoha** [comment]
どちらにせよ、今のvimの出し方だと一回のバッファ読み出しでもらうことになるので
今のt_vbの設定で意図した通り動く端末はまず無いんじゃないかと思うんですよね・・・

**Comment by mattn** [comment]
つまり2回に分けて書けと

**Comment by k-takata** [comment]
`t_vb` の `$<100/>` は誰が解釈しているのだろう？

**Comment by ichizok** [comment]
詳しく見たら、待機はここの `tputs` の中で起こってました。
https://github.com/vim/vim/blob/65189a129/src/term.c#L2532
で、`tputs(t_vb, 1, out_char_nf)` すると `out_buf` には `\e[?5h\e[?5l` が書き出されて、それが `write` される。
他の環境では `tputs` 後の `out_buf` はどうなるんでしょうか？
`\e[?5h` + (何か sleep 的な処理？) + `\e[?5l` になるのか、あるいは `tputs` の中で visual bell してしまうとか？

**Comment by mattn** [comment]
しかしながら xterm の terminfo の flush が既に `\E[?5h$<100/>\E[?5l,` だからなー。これは端末の不具合としか思えないな。

**Comment by ichizok** [comment]
http://invisible-island.net/ncurses/man/terminfo.5.html#h3-Types-of-Capabilities
`tputs("$<...>", ...)` で millisecond delay がかかるということですか。

**Comment by k-takata** [comment]
> で、tputs(t_vb, 1, out_char_nf) すると out_buf には \e[?5h\e[?5l が書き出されて、それが write される。

最初に(tputs 経由で1文字ずつ) out_char_nf が呼ばれて `\e[?5h` を出力、その後 tputs の中でwaitが入り、その後 out_char_nf が呼ばれて `\e[?5l` を出力。
ただし、out_char_nf の中で flush していないので、実際にはwaitの後で `\e[?5h\e[?5l` がまとめて端末に出力されてしまうということですね。

なので、`t_vb` を出力するときは1文字ずつ flush するようにすれば、flash するようになるのではないかと。

**Comment by h-east** [comment]
私の環境でvisualbell動作するのPuTTYだけでした。
TeraTermとGNOME terminalはvisualbell動作しない。

TeraTermはキー押しっぱなしにするとたまに画面フラッシュします。
GNOME terminalはまったく画面フラッシュしない。特に設定とかなさそうでした。

**Comment by mattn** [comment]
@k-takata wait の前にだけ flush 入れるので良さそうですがどうでしょう？

**Comment by k-takata** [comment]
tputs 中から、コールバックで out_char_nf が1文字ずつ呼ばれるわけですが、wait直前の文字であることの判定はできないのではないかと。

**Comment by mattn** [comment]
なるほど(コード読んで無いのがバレた)

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/visualbell.diff
`out_str_cf()` を作って `$<..>` を特別扱い

**Comment by k-takata** [comment]
`out_char_flush` みたいなのを作って一文字ずつ flush させるしかないかなと考えていたのですが、確かに `$<` を自前で解析すれば、バッファリングを活用できますね。いいと思います。

**Comment by ichizok** [comment]
投げました。
https://github.com/vim/vim/pull/1789

**Comment by ichizok** [comment]
8.0.0683
https://github.com/vim/vim/commit/2e147caa14f622dfd1c1def8e07c113b9b85d4b2
