### ISSUE TITLE
with a buffer for each file とは

### ISSUE THREAD

**Issue by splhack** [vim-jp/issues#1028]
https://github.com/macvim-dev/macvim/issues/457

Vim力が足らず、with a buffer for each fileが何を意味しているのかわからないのですが、コマンドラインオプションなどの指定わかるかたいますでしょうか?

**Comment by h-east** [comment]
```bash
$ vim Make*
```
または
```
$ vim
```
の後に `:args Make*`、

そして
```vim
:tab sall
```
ってことかな？

**Comment by h-east** [comment]
(補足)
tabpagemaxオプションはデフォルト 10 なので必要であれば事前に増やしておいたほうが良さそう。
```vim
set tpm=99
```

**Comment by h-east** [comment]
@splhack Issue立てたんですからある程度はフォローしてもらえると助かります。

**Comment by splhack** [comment]
すみません。休暇中でした。
そして、コメントいただいたのですが、やはりさっぱりわからないので、
with a buffer for each fileと、このコードで、ピンとくるかたいらっしゃいましたらおしえていただければ幸いです。
https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MMAppController.m#L965-L975

**Comment by todashuta** [comment]
arglistに追加せずに、バッファリストには追加されてる状態、を望んでるっぽい？

**Comment by h-east** [comment]
@splhack splhackさんがさっぱりわからないのならここでコメントを貰っても、「ソレだ！」とか「違うかも」等の判断出来ないと思うのです。
私は、元のIssue立てた人(mhainfarecomさん)に聞き倒すのがベストソリューションだと思います。

**Comment by 0xBADDCAFE** [comment]
> arglistに追加せずに、バッファリストには追加されてる状態、を望んでるっぽい？

これだと思います。というのも元の issue の立て方の文が悪くて推測に過ぎないのですが、まず元 issue には 3 つのプラグインが暗黙に登場していて、それぞれ

1. https://github.com/vim-airline/vim-airline （内の tabline 機能）
2. https://github.com/dhruvasagar/vim-prosession
3. https://github.com/tpope/vim-obsession

です。このうち 1. については、Vim 側のタブページが 1 つの場合、バッファリストをタブページのように見せるという機能で、この機能を利用している為外部アプリケーションから渡されたファイルをバッファリストに追加する「Preferences->Open files from applications->in the current window->with a buffer for each file」機能が欲しいと言っているようです。
2. は全く把握していませんがセッション管理のプラグイン（2. は 3. に依存しているというどうでもいい補足がされている）のようで、このプラグインと「Preferences->Open files from applications->in the current window->and set the arglist」設定を併用すると出力されるセッションファイルに不要な arglist が出力される汚染がある為、ワークアラウンドとして「-> with a split for each file」設定を利用しつつ分割ウィンドウを閉じる運用をしているようです。

この issue ではなく元 issue の話なので余談ですが、プラグインの機能を前提にした issue には対応出来ない、もしくはきちんとプラグインの動きの前提を説明するよう徹底して貰いたいところですね。

@splhack もし参考になった上で問題無さそうであればクローズ頂けると助かります。MacVim いつも便利に使わせて頂いています、メンテナの少ない中継続的にリリース頂いていて頭が上がりません。ありがとうございます。

**Comment by k-takata** [comment]
特に進展もないので閉じます。
