### ISSUE TITLE
indent/lua.vim 等 shiftwidth() を使わず &shiftwidth を参照している indent plugin が存在する

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1031]
indent/lua.vim 等 shiftwidth() を使わず &shiftwidth を参照している indent plugin が存在する

## 質問・報告の内容

#714 ならびに vim/vim#578 で直っていたと思われていましたが、まだ参照している indent plugin は沢山存在しました。
以下が修正コミットです。
https://github.com/tyru/vim/commit/a89bc2acb8dfc164a6d98caee20b6787141e64b1

## Vimのバージョン

8.0.0339 のツリーから修正しました。

## その他

thinca さんの Lingr の発言で気付きました。

> うおおお indent/lua.vim が shiftwidth() 使ってない！！！
> http://lingr.com/room/vim/archives/2017/02/15#message-23867077

> そうか、以前一括で直してましたね。つまり修正漏れか…
> http://lingr.com/room/vim/archives/2017/02/17#message-23870876

**Comment by tyru** [comment]
問題はこれをどのように送るか（というか言い方）なんですが、
「以前 https://groups.google.com/forum/#!topic/vim_dev/mRhdDBJh07Y/discussion で直してもらったけど、修正漏れがあったから修正したよ」で送って大丈夫なものでしょうか？

**Comment by k-takata** [comment]
他のは `let sw = exists('*shiftwidth') ? shiftwidth() : &sw` としてあるのでそれに合わせた方がよくないですかね？ https://github.com/vim/vim/commit/89bcfda6834aba724d12554a34b9ed49f5789fd5

> 修正漏れがあったから修正したよ

それでいいと思います。

**Comment by tyru** [comment]
> 他のは `let sw = exists('*shiftwidth') ? shiftwidth() : &sw` としてあるのでそれに合わせた方がよくないですかね？

確かに… ただ vim.vim は単純に `shiftwidth()` に置換してるみたいです。
他にも python.vim や fortran.vim などは以前から shiftwidth() のみを使うようになってるようです。
https://github.com/vim/vim/commit/705ada1aff27ecd9c47c690df817d043c2ceb5e2#diff-59df7be2982b9c340efe6e4d137ffd68

他の indent plugin は（Bram 以外の修正もあると思いますが）一旦変数に保存して参照するよう修正されてるものもあるようです。
https://github.com/vim/vim/commit/89bcfda6834aba724d12554a34b9ed49f5789fd5

**Comment by tyru** [comment]
https://github.com/vim/vim/pull/578 で Bram 自身が

> By now it should be OK to use shiftwidth() directly. It was added in
patch 7.4.694, more than three years ago.

と言っているのを見つけました。

**Comment by tyru** [comment]
送りました。
https://groups.google.com/forum/#!topic/vim_dev/BcDThxEkwNA

**Comment by tyru** [comment]
こんな返答が来ました。

> Wow, that's a lot.  Have you pinged the maintainers?

どう返したものか…

**Comment by thinca** [comment]
「メンテナに連絡したか?」なので、「してない」と答えるしかなさそう。

**Comment by tyru** [comment]
ですね。
ただどうにかして Bram 自身にパッチを一括で適用してもらえる方向にできないかと…

とりあえず文面考えたので今メール返信しました。

**Comment by tyru** [comment]
vim/vim に GH issue 作りました。
https://github.com/vim/vim/issues/1493

あと以前作ったスプレッドシートも更新しました（**シート「2nd」を参照してください**）。
[The List of Vim indent plugin maintainers - Google spreadsheet](https://docs.google.com/spreadsheets/d/1-HeWlsLC-tJDfuXQjtkZmY5UwXakAuYg83z9nz7nl2w/edit?usp=sharing)

**Comment by k-takata** [comment]
直った？ https://github.com/vim/vim/commit/3ec574f2b549f456f664f689d6da36dc5719aeb9

**Comment by tyru** [comment]
帰ったら照らし合わせてみます

**Comment by tyru** [comment]
すみません、今日はきっちり見る気力がないので明日（か明後日）になります…

**Comment by tyru** [comment]
スプレッドシートと照らし合わせるまでもありませんでした。
`git grep -w '&sw' runtime/indent/` と `git grep -w '&shiftwidth' runtime/indent/` してオプションを直接使っている箇所がないか調べましたが、ありませんでした。
よってクローズします。
