### ISSUE TITLE
新しい filetype である tmux の検出パターンが正しくない

### ISSUE THREAD

**Issue by ryunix** [vim-jp/issues#1036]
## 質問・報告の内容

tmux の設定ファイル名は `.tmux.conf` や `tmux.conf` です。

現在の[検出パターン](https://github.com/vim/vim/blob/bb962262eb6b18d93161d7506317d215ae80bfe5/runtime/filetype.vim#L2284)では、`.tmux.conf` の場合 `filetype=tmux` になりません。

```vim
au BufNewFile,BufRead tmux*.conf		setf tmux
```

なぜこのような設定になっているのか、その謎をあきらかにすべく我々は[元となったリポジトリ](https://github.com/ericpruitt/tmux.vim/blob/37b1e21911ef0d9a56127c3733cc6953ce0c3dde/vim/ftdetect/tmux.vim#L1)へ向かった...

```vim
autocmd BufNewFile,BufRead {.,}tmux*.conf* setfiletype tmux
```

`$VIMRUNTIME/filetype.vim` を見渡す感じ、他と合わせての変更({.,}を使わないなど)で消してしまったのかなとは思うのですが...
このような場合、どうすればよいでしょうか？ (そもそも runtime の話をして良かったんだっけな？)

## Vimのバージョン

8.0.0425 (MacVim)

## OSの種類/ディストリ/バージョン

- macOS Sierra

## 使用している or 関係していそうなプラグイン

なし

## その他

これは関係ないけど、元となったリポジトリと[更に元となったリポジトリ](https://github.com/keith/tmux.vim/blob/3abf80104623bd4733138f8860ef1922ba3f914a/ftdetect/tmux.vim#L1)の内容は一致していました。

**Comment by mattn** [comment]
```diff
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 20e9af4a8..df0397be2 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -2281,7 +2281,7 @@ au BufNewFile,BufRead .tidyrc,tidyrc		setf tidy
 au BufNewFile,BufRead *.tf,.tfrc,tfrc		setf tf
 
 " tmux configuration
-au BufNewFile,BufRead tmux*.conf		setf tmux
+au BufNewFile,BufRead {.,}tmux*.conf		setf tmux
 
 " TPP - Text Presentation Program
 au BufNewFile,BufReadPost *.tpp			setf tpp
```

https://groups.google.com/forum/#!topic/vim_dev/j2_40VZtRcI

**Comment by k-takata** [comment]
See: vim/vim#1538

**Comment by ryunix** [comment]
@k-takata Issue 立ててから本家を見に行ってちょうど見つけたところでした... 順番が逆でしたね 🙇

**Comment by ryunix** [comment]
vim/vim の Issue を見た感じ、ちょっと微妙な感じ(?)ですね。
後はどんな反応が来るかと言う感じでしょうか...

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/1529#issuecomment-284158991
Bramが何で `{.,}` がいるの？と質問していましたが、必要性がちゃんと伝わっていなかった模様。
あと、Windowsでは`{,}`がワイルドカードとして使えないので、それを使っていいのか気になるところです。

**Comment by k-takata** [comment]
> Windowsでは{,}がワイルドカードとして使えないので

勘違い。`autocmd` では使えるようですね。

**Comment by ryunix** [comment]
更新されました！ :tada: 
https://github.com/vim/vim/blob/036986f1507d223549d110af300144468bd3a1f7/runtime/filetype.vim#L2287

(追記: patch 8.0.0467の直前のcommit)
