### ISSUE TITLE
f最 の後に ; が効かない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1038]
## 質問・報告の内容

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">vimでf最としたあとに;を打っても次の最を探してくれない。<br>バグ?</p>&mdash; 重城良国 (@YoshikuniJujo) <a href="https://twitter.com/YoshikuniJujo/status/836075444386443264">2017年2月27日</a></blockquote>

手元でも再現を確認。
`enc=utf-8` では発生するが、`enc=cp932` では発生しない。

`最`の文字コードは U+6700。UTF-8 だと 0xE6 0x9C 0x80。
コードポイントの下位8ビットが 0x00 であること、あるいは UTF-8の3バイト目が 0x80 となっていることが原因の可能性あり。

## Vimのバージョン

8.0.442

## OSの種類/ディストリ/バージョン

*   Windows 10

Linux GUIでは、over-the-spotパッチを当てるなど、f の後に漢字を入力できるようにすれば再現の可能性あり。

**Comment by presuku** [comment]
> Linux GUIでは、over-the-spotパッチを当てるなど、f の後に漢字を入力できるようにすれば再現の可能性あり。

手元のLinux環境でも再現しました。

> enc=utf-8 では発生するが、enc=cp932 では発生しない。

こちらも、同様でした。

# Vimのバージョン
8.0.442 with gtk_im_over-the-spot.patch で set imstyle=1
# OSの種類/ディストリ/バージョン
Ubuntu 14.04

**Comment by h-east** [comment]
これで直ります。testは週末に書きます。
```diff
diff --git a/src/search.c b/src/search.c
index d23dde2..f4a5c6d 100644
--- a/src/search.c
+++ b/src/search.c
@@ -1643,7 +1643,11 @@ searchc(cmdarg_T *cap, int t_cmd)
     }
     else		/* repeat previous search */
     {
-	if (*lastc == NUL)
+	if (*lastc == NUL
+#ifdef FEAT_MBYTE
+		&& lastc_bytelen == 1
+#endif
+		)
 	    return FAIL;
 	if (dir)	/* repeat in opposite direction */
 	    dir = -lastcdir;
```

**Comment by k-takata** [comment]
> コードポイントの下位8ビットが 0x00 であること

これが原因でしたか。

**Comment by h-east** [comment]
はい:grimacing:
search.c : 1628
`*lastc = c;`
intをunsigned charに代入したら下位8bitしかコピーされなくて、その値だけで判定してました。

**Comment by h-east** [comment]
Sent to vim_dev
https://groups.google.com/d/msg/vim_dev/WSvsUFJ9Y7o/xVXC2p1vBAAJ

**Comment by h-east** [comment]
patch 8.0.0446
https://github.com/vim/vim/commit/454709baffd3205bf2b7d2519419675a122f2bd2

Issue登録やバグ呟きありがとうございました:+1:

PS
src/testdir/test_charsearch_utf8.vim や src/version.c で内容が重複しているのは報告済み
https://groups.google.com/d/msg/vim_dev/WGVuZWJtYrw/CVm-VCHJBAAJ

**Comment by h-east** [comment]
> src/testdir/test_charsearch_utf8.vim や src/version.c で内容が重複しているのは報告済み

patch 8.0.0456 の１つ手前のcommitで修正されました。
https://github.com/vim/vim/commit/26a280c47a1c6e32cdced79032dc495c60710d0d
