### ISSUE TITLE
did_filetype()の動きがhelpと異なる

### ISSUE THREAD

**Issue by keik8128** [vim-jp/issues#1039]
## 報告の内容

#1034 の実装中に見つけたバグ(or 仕様)です

`:h did_filetype()@ja`より引用

> autocommandが実行されFileTypeイベントが一度でも起こっていれば、|TRUE|が返る。スクリプトのFileTypeイベントが、複数回呼び出されるのを回避するのに使える。 |FileType|
> 他のファイルへ移動すると、このカウンタはリセットされる。よって実際は、カレントバッファに対してFileTypeイベントが発生したかどうかを判定する。他のバッファを開くオートコマンドの中でこの関数を使って 'filetype' を設定し、構文ファイルを読み込むために使える。

「autocommandが実行されFileTypeイベントが一度でも起こっていれば、|TRUE|が返る」とのことですが、実際にはそうなっていません。

### 確認したバージョン

以下全て`vim -u NONE`で起動

* 8.0.433 (./configure CFLAGS="-g -O0")
* 8.0.134 (普段使っているバージョン. configureの引数は不明)

### 例1

```vim
:filetype on
:e test.c
:echo &filetype
" => c (filetypeがセットされているということは、FileTypeが走っているはずであるが...)
:echo did_filetype()
" => 0 (期待しない動作をする)
:setfiletype cpp
:echo &filetype
" => cpp (:setf は上書きしないはずだが、c => cppになっている)
:set filetype=c
:echo did_filetype()
" => 1 (直接set ft=cを叩くと期待する値を返す)
:setfiletype cpp
:echo &filetype
" => c (:setf の本来の動作通り、書き換わらない)
```

### 例2

```vim
:autocmd FileType c let g:autocmd_works = 42    " (*1)
:doautocmd FileType c     " (*2)
:echo g:autocmd_works
" => 42
:echo did_filetype()
" => 0 (期待しない動作)
```

`(*1)`の部分は`:syntax on`でも同じ挙動を示します(その場合は'syntax'がcになっていることで確認できます)。とにかくFileTypeイベントに何かが登録されていることが重要なようです。

`(*2)`の部分は`set ft=c`や`setf c`でも同じ挙動を示します。一つ目の例と違って、この場合は`set ft`を使ってもdid_filetype()は0を返してきます。

### 例3

```vim
:filetype on
:autocmd BufNewFile,BufRead *.c if did_filetype() | let g:did_filetype = 1 | endif
:e test.c
:echo exists('g:did_filetype')
" => 1 (autocommandの中ではdid_filetype()が1を返している)
```

BufNewFileやBufReadには、`$VIMRUNTIME/filetype.vim`や`.vim/ftdetect/*.vim`などで`autocmd BufNewFile,BufRead *.c setf c`のようなautocommandが登録されており、そのコマンドがまさに動いている最中(この例では`setf c`や`if did_filetype() | let g:did_filetype = 1 | endif`)は`did_filetype()`が期待する動作をするようです。
この例3が正しく動いているために、今現在の`$VIMRUNTIME/filetype.vim`は問題なく動作しています。

## 考察

実際の動作から、did_filetype()を正確に言い表すならば、「FileTypeイベントになんのautocommandもない状態で`set ft=`や`setf`した時か、FileTypeイベントが別のイベント(BufNewFileなど)に登録されていたautocommandから`set ft`などで*間接的に*呼ばれた時に、その別のイベントに登録されているautocommandが*実行し終わるまで*はTRUEを返す」関数となりそうです。
これを仕様と呼ぶべきかバグとして直すべきかはわかりませんが、少なくともhelpは修正しておく必要があるように思います。どのように直すべきか皆さんの意見を頂きたいです。

## 挙動またはhelpを修正する場合の関連するソースコード

```c
/* did_set_string_option() in src/option.c */
if セットされたオプションが'filetype'ならば
    did_filetype = TRUE
    FileTypeイベントを発火
```

```c
/* apply_autocmds_group() in src/fileio.c */
if このイベントに登録されているautocommandがなければ /* (*1) */
    return

if FileTypeイベントならば
    did_filetype = TRUE

このイベントに登録されているautocommandsを全て実行 /* (*2) */

if ネストしたイベント(autocmdの中から呼ばれるautocmd)でなければ
    did_filetype = FALSE /* (*3) */
```

「FileTypeイベントになんのautocommandもない状態で`set ft=`や`setf`した時」に`did_filetype()`が動くのは、`(*1)`のところでreturnしているので`(*3)`が実行されないため

filetype detectionを有効にしていると、BufNewFileまたはBufReadがネストしたイベントではない(Vimが直接実行する)ため、`(*3)`が実行される

BufNewFileやBufReadのautocommand実行中に`did_filetype()`が動くのは、(*2)の時点ではまだ(*3)が実行されていないため

**Comment by h-east** [comment]
これは仕様でしょう。
`did_filetype()`も`:setfiletype`もautocommand経由で呼び出された時だけhelpに書かれている動作をするのでしょう。
`:h did_filetype()@en`を見ると最後の文章が`This allows`から始まっているので、その文章を説明したいための前準備としてそれまでの文章がある感じでしょうか。
日本語helpは`This allows`を踏まえた翻訳にした方がいいかもしれません。

`:setfiletype`は日本語helpでもよく読めば、「autocommand経由で呼び出された時だけ有効」だと受け取れますね。
でも、実際にこういう目に合わないと分かんないですよね:smile:

ちなみに、本題と少しズレますが、`例1`で1行目と2行目の間に`:syntax on`を入れると挙動変わります。
(`did_filetype()`が1を返すことがなくなる)
なぜだか分かります？

**Comment by keik8128** [comment]
> `例1`で1行目と2行目の間に`:syntax on`を入れると挙動変わります。

例2の場合と同じで、FileTypeイベントに何らかのautocommandが設定されていると`did_filetype()`の結果が変化するようです。

--------------------------------------------------

`:h :setfiletype`を見ると確かに仕様のようですね。`did_filetype()`は`:setfiletype`と同じ目的にしか使わないということなんでしょうね。素早い回答ありがとうございました。仕様のようですので閉じておきます。
