### ISSUE TITLE
インサートモードの補完が遅い

### ISSUE THREAD

**Issue by daisuzu** [vim-jp/issues#1040]
## 質問・報告の内容

ファイルから候補を生成するタイプの補完が[8.0.0050](https://github.com/vim/vim/commit/01688ad545ff0809ddad5c8fa6b149dc5d67312b)から遅くなっているようです。

* 辞書補完(i_CTRL-X_CTRL-K)
* タグ補完(i_CTRL-X_CTRL-T)
* 行補完(i_CTRL-X_CTRL-L)
* など

ファイルが軽い時はあまり気になりませんが、重くなるとなかなか候補が出なくなります。

## Vimのバージョン

8.0.503でも発生

## OSの種類/ディストリ/バージョン

*   CentOS 7 64bit(ターミナルのvimで確認)
*   macOS Sierra(ターミナルのvimで確認、macvimは問題なし)

## その他

* `yum install words`でインストールした`/usr/share/dict/words`を使用した場合の辞書補完

![ctrl-x_ctrl-k](https://cloud.githubusercontent.com/assets/1222926/24319595/c77b1fcc-1163-11e7-8667-04d8804a8a39.gif)

**Comment by daisuzu** [comment]
8.0.0503に以下のパッチを当てると解消しましたが、他にどのような影響があるかはまだ調べていません。

```diff
diff --git a/src/os_unix.c b/src/os_unix.c
index f0a562172..5ddeef48a 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -402,6 +402,9 @@ mch_inchar(
     ELAPSED_INIT(start_tv);
 #endif
 
+    if (wtime >= 0)
+	did_start_blocking = TRUE;
+
     /* repeat until we got a character or waited long enough */
     for (;;)
     {
```

**Comment by h-east** [comment]
Issue登録&patch作成お疲れ様です。
現象とpatch確認しました。5ヶ月間誰も気付かなかったの凄いです。汗
そのpatchで問題ないとは思うのですが、変数`did_start_blocking`の意味合いを考慮するとこんな感じが良いのかもと思いました。
処理的には同じです。

```patch
diff --git a/src/os_unix.c b/src/os_unix.c
index f0a5621..4efaf8a 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -511,7 +511,7 @@ mch_inchar(
 		|| interrupted
 #endif
 		|| wait_time > 0
-		|| !did_start_blocking)
+		|| wtime < 0 && !did_start_blocking)
 	    continue;
 
 	/* no character available or interrupted */
```

**Comment by daisuzu** [comment]
確認ありがとうございます。
前後関係があまり理解できていなかったので助かりました。
条件のところは`wtime < 0`にしたいと思っていたので直してもらったパッチの方が良さそうですね。
この内容で本家の方にPR投げてみようと思います。

**Comment by h-east** [comment]
8.0.0512
https://github.com/vim/vim/commit/1572e30607e9a3bee9750242bf37168f7d2b6e66

ありがとうございました。

**Comment by daisuzu** [comment]
マージ早！
こちらこそありがとうございました。
