### ISSUE TITLE
インサートモードでCommand+Vを使ったペーストを行うと正常にペーストされない。

### ISSUE THREAD

**Issue by hyuki0000** [vim-jp/issues#1041]
## 質問・報告の内容

 - インサートモードでCommand+Vを使ったペーストを行うと正常にペーストされない。
 - ノーマルモードに戻っているような節がある（けれど、正確に何が起こっているか表現できない）。
 - `:set t_BE=`を入力すると正しくペーストされるようになる。
 - <a href="https://youtu.be/Gve9vCqAM1A">不具合再現&回避動画</a>では、二回のペーストを動画で示しています。一回目は正常にペーストされないもの。二回目は `:set t_BE=`を実行後正しくペーストされるもの。
 - 動画中では`vi`として入力していますが、Vimです。
```
$ type vi
vi is aliased to `/Applications/MacVim.app/Contents/MacOS/Vim'
```
- iTerm2上でコンソール版として使っています。GUI版 `vim -g` では再現しません。
- `:set t_BE=`によって正常にペーストされない現象はなくなりますが、これが正しい対処かどうかわからないので念のためissueとして挙げました。

## Vimのバージョン

Vim 8.0.329
```
$ vim --version | head -4
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 16 2017 04:00:07)
MacOS X (unix) 版
適用済パッチ: 1-329
Compiled by travis@Traviss-Mac-592.local
```

## OSの種類/ディストリ/バージョン

- MacBook Air OS X El Capitan 10.11.6
- Vim 8
```
$ vim --version | head -4
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 16 2017 04:00:07)
MacOS X (unix) 版
適用済パッチ: 1-329
Compiled by travis@Traviss-Mac-592.local
```
- iTerm2 Build 3.0.15

## 使用している or 関係していそうなプラグイン

（特には思いつきません）

## その他

 - `:help xterm-bracketed-paste` を読みました。
 - <a href="https://groups.google.com/forum/#!topic/vim_dev/T5Wz9rI2yZg">Patch 8.0.0210: Vim does not support bracketed paste, as implemented by xterm and other terminals.</a>が関連しているのかと思って `:set t_BE=` を実行しています。
- <a href="https://www.reddit.com/r/vim/comments/5w2rom/paste_escape_sequences_in_vim_8/">Paste escape sequences in vim 8?</a>
 - <a href="https://snap.textfile.org/20170324232756/">関連ブログ記事</a>

**Comment by h-east** [comment]
補足:
一回目は正常にペーストされない == 最初の`A`がペーストされない

**Comment by koron** [comment]
@hyuki0000 参考までに、OSXに標準添付のターミナルで同じことをやった場合にはどうなるか、確認していただけますか?

**Comment by hyuki0000** [comment]
(1) ペーストする文字列が`ABCDEFGHIJKLMNOPQRSTUVWXYZ`の場合、ペーストされる文字列は`BCDEFGHIJKLMNOPQRSTUVWXYZ`になります。
(2) ペーストする文字列が`/Application`の場合、文字列はペーストされず、コマンドラインに`/Application`と表示されます。

推測：(1)の最初の文字が`A`なので、ペーストになっていて、(2)は最初の文字が`/`なので検索風になるのかもしれません。

**Comment by hyuki0000** [comment]
@koron OSXに標準添付のターミナルで同じことをやった場合には、`:set t_BE=`しなくてもインサートモードで正常にペーストされます。

**Comment by mattn** [comment]
動きを見る限り、Command-V + A が ESC の動きをしている様に見えます。`vim -u NONE -N` で同じ動きになるか確認して貰えますか。
もしそれで解決する場合は vim から `:verbose map <c-v>` を入力して貰えると `<c-v>`  から始まるマッピング(何かしらのプラグインが定義している？)が表示されるかもしれません。

**Comment by koron** [comment]
補足: Command-V なので `:verbose map <D-V>` で見てみてください。

**Comment by hyuki0000** [comment]
`vim -Nu NONE`で実行すると正常にペーストできました。他の件は後ほどやってみます。

**Comment by koron** [comment]
もしかしてコレ?

https://github.com/vim/vim/blob/d07969093a9b3051511c478d71c36de6fc33c0d6/runtime/macmap.vim#L54

    nnoremap <special> <D-v> "+gP

**Comment by koron** [comment]
あ、insert mode だからこっちか

    execute 'inoremap <script> <special> <D-v>' paste#paste_cmd['i']

https://github.com/vim/vim/blob/d07969093a9b3051511c478d71c36de6fc33c0d6/runtime/macmap.vim#L57

**Comment by mattn** [comment]
@hyuki0000 いろいろすみません。↑のと合わせて以下を教えて下さい。

```
:echo getchar()
```
これを実行したあと Command-V で表示される数字が知りたいです。

**Comment by k-takata** [comment]
macのマッピングについては、 https://github.com/vim-jp/issues/issues/744#issuecomment-288413854 に書いたものもありますが、今回の件に関係あるかは分かりません。

**Comment by hyuki0000** [comment]
`:verbose map <D-V>`では「マッピングは見つかりませんでした」になりました。

**Comment by hyuki0000** [comment]
@mattn 
以下、クリップボードに`ABCDEFGHIJKLMNOPQRSTUVWXYZ`が入った状態から開始しました。

(`:set t_BE=`)を実行した場合、`:echo getchar()`の後に`Command-V`を入力すると、`65`と表示されます。
(`:set t_BE=`)を実行しなかった場合、`:echo getchar()`の後に`Command-V`を入力すると、`65`と表示されます。

**Comment by k-takata** [comment]
よく考えたら、Command-V は端末ソフトが処理するはずなので、vimには渡らないはずです。

挿入モードで、Ctrl-V を押してから Command-V を入力するとどうなりますか？
bracketed paste modeが有効になって正しく動作しているならば、`^[[200~` の後にクリップボードの内容がペーストされるのが期待値です。（`^[` はエスケープコード。）

**Comment by hyuki0000** [comment]
@k-takata 
以下、クリップボードに`ABCDEFGHIJKLMNOPQRSTUVWXYZ`が入った状態から開始しました。

`:set t_BE=`を実行しないで、挿入モードで、Ctrl-Vを押してからCommand-Vを入力したところ、
`[200~ABCDEFGHIJKLMNOPQRSTUVWXYZ`とペーストされました。

**Comment by k-takata** [comment]
クリップボードの先頭に、`�` がなく、Command-V で入力される先頭の `�` がエスケープならば期待通りですが…。

`:set timeout? ttimeout? timeoutlen ttimeoutlen` の結果も教えてください。

**Comment by hyuki0000** [comment]
原因らしいものがわかりました。
`~/.vimrc`を少しずつ短くしていって、何が原因になっているかを調べてみたところ、以下のコードがあると不具合が発生し、以下のコードをコメントアウトすると正常にペーストされます。

```
if has('unix') && !has('gui_running')
  inoremap <silent> <ESC> <ESC>
endif
```

このコードの意図は自分でもよくわかっていません。このコードがあることで、本件の原因になるでしょうか。

また、このコードは何かのワークアラウンドだったのかなあ……これを抜くことで予想される問題はありますでしょうか。

**Comment by mattn** [comment]
その設定が何を意味しているのか分かりませんが、とりあえずそういう設定をされておられる方が[一定数いる](https://www.google.co.jp/#safe=off&q=%22inoremap+%3Csilent%3E+%3CESC%3E+%3CESC%3E%22&*)のは分かりました。

**Comment by k-takata** [comment]
Escを押したときにすぐに挿入モードを抜けるための設定だったような。

端末ソフトは、カーソルキーなどの特殊キーが押されたとき、Escで始まるコードを送信します。端末上で動作するVimはそのような特殊キーと実際のEscを判別するため、timeoutlen や ttimeoutlen で設定された時間だけ、入力を待ちます。
で、Escがマッピングされていると待たずに即実行する代わりに、特殊キーや今回のbracketed paste modeのような特殊命令が解釈されなくなってしまいます。（確か…）
ただ、標準のターミナルソフトでは問題ないというのがよく分からないですね。

**Comment by k-takata** [comment]
普通は、ttimeoutlen に 50～100 ぐらいの値を設定しておくのが便利でしょう。
（本当は Vim が Application Escape Mode に対応すれば、タイムアウトの設定も不要になるのですが。）

**Comment by hyuki0000** [comment]
少し過去をさかのぼってみると「ESCを押したときに画面の色反映が即時行われるようにする」というコメントがありました。 @k-takata さんが書かれていた「すぐに挿入モードを抜ける」のと近い話に読みました。いまのところ、`inoremap <silent> <ESC> <ESC>`をコメントアウトしていても特に（私には）困ったことはないです。

このissueはcloseしてもいいのでしょうか（よく流儀がわかっていない。私がcloseしていいなら、closeしたいです）

**Comment by mattn** [comment]
close お願いします。

**Comment by h-east** [comment]
ここ数年、local, remote関係なく`set ttimeoutlen=0`で運用していますけど特に問題ないですね。
キーデータが分断されて処理されるような状況にはそうそうならないと思うのです。
(的外れな事を言ってるなら突っ込んでおくれ)

ともあれ、原因が分かってよかったですね:+1:
@hyuki0000 Issue登録お疲れ様でした。

**Comment by hyuki0000** [comment]
ありがとうございました。
