### ISSUE TITLE
screen が invalid 状態のとき，'w0', 'w$' の Position の返す値がおかしい

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#1042]
## 質問・報告の内容

screen が invalid 状態のとき，'w0', 'w$' の Position の返す値がおかしい

#### v8.0.515 以上 (HEAD, v8.0.515)

```
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "echo getpos('w0') getpos('w$')" --cmd quit
[0, 0, 1, 0] [0, -1, 1, 0]
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "call setline(1, range(100))" --cmd "echo getpos('w0') getpos('w$')" --cmd 'quit!'
[0, 1, 1, 0] [0, 0, 1, 0]
```

#### v8.0.515 以前 (v8.0.514)

```
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "echo getpos('w0') getpos('w$')" --cmd quit
[0, 1, 1, 0] [0, 1, 1, 0]
$ vim -X -N -u NONE -i NONE -n -V1 -e -s --cmd "call setline(1, range(100))" --cmd "echo getpos('w0') getpos('w$')" --cmd 'quit!'
[0, 1, 1, 0] [0, 42, 1, 0]
```
(42 はターミナルのheightによる)

再現手順のように 'w0', 'w$' の値が -s を付けて実行した際に [v8.0.515](https://github.com/vim/vim/commit/d5d37537d1fa46fd468bd378af2006dd09840f38) で変わってしまっています．
これは `-s` を付けないと再現しません．

該当行的にはこのあたりです． https://github.com/vim/vim/commit/d5d37537d1fa46fd468bd378af2006dd09840f38#diff-730e42441ff982fa04a4df341a0c3e24L180
`!screen_valid(TRUE)` のチェック位置が変わったせいで挙動が変わってしまっています．

ただ単純に戻すと 8.0.0515 が直した問題が発生してしまうので，どう戻せばいいかちょっとわかりませんでした．

## Vimのバージョン

8.0.515

## OSの種類/ディストリ/バージョン

*   Manjaro Linux

## 使用している or 関係していそうなプラグイン

https://github.com/thinca/vim-themis によるテストなどなどで，w0, w$ の値に依存する
コードを書いてるとテストが落ちるようになる．

## その他

元の挙動が保証されてなかったとしても，現在 line('w$') が -1 を返す場合があるのは少なくともマズそうです．

**Comment by h-east** [comment]
@haya14busa 先にvim_devに報告した方が良さそうな気がします。

**Comment by haya14busa** [comment]
たしかに :crab:

ということで report しました https://github.com/vim/vim/issues/1613

**Comment by h-east** [comment]
patch 8.0.0542
https://github.com/vim/vim/commit/a1d5fa65bc7e8a548858e9c295a192b63dcd011b
