### ISSUE TITLE
特定の文字列を編集して k で移動するとターミナルごと落ちる

### ISSUE THREAD

**Issue by uakms** [vim-jp/issues#1045]
### 質問・報告の内容
Mac の ターミナルでのみの現象ですが、特定の文字列を編集して k で移動するとターミナルごと落ちます。

再現方法：次の例文を開き、p の文字にカーソルを置いて xkk とします。例文中の前後には改行が入っています。

```
ほげほげ

<p>あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ</p>

ふがふが
```
(わかりにくかったので例文を修正しました。前後ではなく上下の方が良かったですね)

### Vim のバージョン
- 8.0.562 (CUI 版です)
- (8.0.0000 でも落ちます)
- (8.0.563 でも落ちます)
- (OS 標準の 7.3 でも落ちます)

### OS の種類/バージョン
- OS X El Capitan 10.11.6
- ターミナル 2.6.1
    - 環境設定「ターミナルの宣言方法」で ansi **以外** に設定した場合 (追記)

### 関係していそうなプラグイン
なし

### その他
[考察資料](http://sci.hateblo.jp/entry/Crash_Vim_on_Terminal)

補足：次の環境では問題ありませんでした。
- OS X Panther 10.3.9
- ターミナル 1.4.6
- Vim 8.0.563

**Comment by thinca** [comment]
- macOS Sierra 10.12.4
- Vim 8.0.0563 Huge 版 with MacVim GUI (端末版)
  - `brew reinstall --HEAD macvim-dev/macvim/macvim`
- 端末
  - ターミナル (Terminal.app) 2.7.2
  - iTerm2 3.0.15
- 操作
  - 空のバッファを開き、例文を貼り付けて実行
  - 事前にファイルを用意し、ファイルを開いて実行

以上の環境で試しましたが再現せず。

**Comment by Shougo** [comment]
>    OS X El Capitan 10.11.6
>    ターミナル 2.6.1

OS が古いようなのでターミナルのバグの可能性があります。
同じバージョンのターミナルの人が検証できればはっきりするのですが。

**Comment by itchyny** [comment]
El Capitan 10.11.6 Terminal 2.6.1 Vim 8.0.563 で確認しましたが再現しませんでした。

**Comment by itchyny** [comment]
こういう手順であってますか。

![vim](https://cloud.githubusercontent.com/assets/375258/25036920/507b3000-2131-11e7-90c7-c59299ecdb06.gif)

**Comment by uakms** [comment]
検証ありがとうございます。
itchyny さんのスクリーンキャスト(のビジュアルベルってる)を見て気がついたのですが、
ターミナル.app の環境設定で「ターミナルの宣言方法」はどうなっているでしょうか？
わたしは普段、xterm-256color にしているのですが、ansi では落ちませんでした。
他に rvxt, vt100, xterm を試してみると落ちました。
お手数ですが、この設定で確認してもらえませんでしょうか？

![crash_vim](https://cloud.githubusercontent.com/assets/1085119/25041365/80635702-214a-11e7-85c9-9dd9b0a0fc90.gif)

**Comment by ichizok** [comment]
ターミナルが終了した時のダイアログで「レポート」を選ぶとスタックトレースが表示されると思いますが、
それをgistかどこかに貼ってもらえますか？

**Comment by uakms** [comment]
クレジットカード番号等のやばそうなものが書いてあったら教えてください。

https://gist.githubusercontent.com/nakinor/dd33c7a6e656fbea5450363c7f0bd640/raw/8d0dcfbe07cff0cca6e6c574668cee82f0a0786f/txt

**Comment by ichizok** [comment]
ありがとうございます。
匿名の障害レポートなので個人情報は入ってないはず...

**Comment by itchyny** [comment]
関係ありますかね？外部ディスプレイは使っておられますか？
https://discussions.apple.com/thread/7778906
http://stackoverflow.com/questions/41864327

**Comment by itchyny** [comment]
alternate screenはVimとかscreenがそういうのって感じで、外部ディスプレイとは別の話っぽい (読み違えました、すみません)
https://discussions.apple.com/message/31417760#message31417760 とか

**Comment by h-east** [comment]
再現しました。
(MacBook (Early 2016)のほぼ弄ってない状態)
MacOS Sierra 10.12.3
ターミナル 2.7.1 (388)
Vim 7.4.8056
```
:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  6 2016 12:07:41)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.
```

とりあえず、homebrew入れてVimのソースコードやら必要なものを入れます。

**Comment by h-east** [comment]
ソフトウェア・アップデートしたら再現しなくなりました。
MacOS Sierra 10.12.4
ターミナル 2.7.2 (388.1)
Vimは同じ

@nakinor ソフトウェア・アップデート実施して確認してもらえないでしょうか。

とりあえず、調査は止めますね。

**Comment by uakms** [comment]
itchyny さん、情報ありがとうございます。
ミカエルさんのケースを試しましたが再現しませんでした。Sierra じゃないからかしら？

higashi さん、OS X El Capitan としては最新版なんですよぉ。

.inputrc を空にしたり、yash, zsh や csh で試してみましたが、やはり落ちてしまいます。また、/usr/bin/vim (OS 標準の v7.3) でも落ちてしまいました。

同じ環境であるにもかかわらず、他の方が再現しないというのは不思議ですね。なんだか自分で自分を信用できひんようになってきましたわ。

とりあえず、ansi タイプにすれば落ちないという回避策が発見できましたので、issue 登録をして良かったです。

他に困っている人はおらへんようなので Close しても良さそう？

**Comment by h-east** [comment]
@nakinor 
> higashi さん、OS X El Capitan としては最新版なんですよぉ。

うぅ、ソフトウェア・アップデートせずに調査すればよかったかなぁ。。
でも、ターミナル 2.7.1 (388) 以前のバグな気がしてます。
http://saitoha.github.io/trachet/ 等を使ってterminal I/Oのログを取ってみては如何でしょうか？
落ちる瞬間のログが取れればそれをもとにAppleに不具合報告できると思います。
trachetのインストールや使い方分からなかったら言って下さい。

**Comment by uakms** [comment]
h-east さん、itchyny さんが保持している全く同様の環境で不具合が発生していないので、これはわたしの環境特有のものかもしれません。ほぼ発生しない(世の中ではこれを 100% という)不具合を追うのは技術の浪費ですし、社会的損失になりませんか？

**Comment by itchyny** [comment]
そこまでは思っていませんでしたが、OSの (Terminal.appの？) アップデートで直りそうですし、 @nakinor さんが困っておられないのなら閉じてよさそうです。

**Comment by uakms** [comment]
itchyny さんのおかげで「ターミナルの宣言方法」を `ansi` にすれば回避できることがわかりました！ありがとうございます。ちなみにオフトピですが、わたしは格安データ SIM で運用している為、5GB 近くの容量をダウンロードするのに半年計画でデータ容量を貯金していかないといけないんです(>_<)

再現性の確認や意見をして下さったみなさま、ありがとうございました。

**Comment by ichizok** [comment]
close済みですが、参考情報として残しておきます。

OS X 10.11 Beta (15A278b)
Terminal.app 2.6 (381)
Vim 8.0.0567 / Vim 7.3 (pre-installed)
で確認しましたが、環境設定の プロファイル＞詳細＞"Unicode 東アジア A（曖昧）の文字幅を W（広）にする" がOFFだと問題なし、ONにすると落ちました。

**Comment by uakms** [comment]
ichizok さん、調査ありがとうございます。
わたしも確認してみましたが、xterm-256color でチェックを OFF にすると落ちませんでした。

El Capitan, Terminal のバージョンが 2.6 or 2.6.1 の環境で、
「ターミナルの宣言方法」が ansi 以外で、かつ
「Unicode 東アジア A（曖昧）の文字幅を W（広）にする」がオンの設定の場合に落ちる

という条件になりますかね。
