### ISSUE TITLE
Windows のコンソール版が色鮮やかになる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1046]
## 質問・報告の内容

Windows10 のクリエーターズアップデートを入れた後から、vim.exe の表示がおかしくなります。
![色鮮やか](https://cloud.githubusercontent.com/assets/10111/25048030/1767db4e-2175-11e7-9500-2758b39f5946.png)

## Vimのバージョン

8.0.554

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.10586)

## 使用している or 関係していそうなプラグイン

なし。vim -u NONE -N で発生。

## その他

IME のオンオフで画面がスクロールアップして、そのタイミングで表示が崩れる事が多いです。

**Comment by koron** [comment]
つまりコンソール関連APIの互換性が崩れた? (；´∀｀)

**Comment by k-takata** [comment]
何か壊れてるらしいですね。 rprichard/winpty#105

**Comment by koron** [comment]
MSVC でビルドした 8.0.0178 + 1703 (Creators Update) でちょっと使ってみた感じは問題発生せず。
+kaoriya に付属の README.txt を split して、別バッファで日本語入力とかできて ??? ってなってる。。

**Comment by koron** [comment]
以下のように設定されていた。

```
encoding=utf-8
termencoding=cp932
```

**Comment by mattn** [comment]
visual bell 時に起こるっぽいです。

**Comment by koron** [comment]
確認できました。そこまでドラスティックではないですが visualbell が発生するたびに少しずつおかしな領域が広がっていくのを確認できました。

**Comment by mattn** [comment]
https://twitter.com/RuRuRuTan/status/850618630127493120

> Creater's updateからcp932でもCOMMON_LVB_LEADING_BYTEやらCOMMON_LVB_TRAILING_BYTEのフラグが立たなくなったのでckwで日本語表示すると画面崩壊となっている模様

**Comment by mattn** [comment]
関連: https://github.com/vim/vim/issues/1739

**Comment by k-takata** [comment]
https://github.com/rprichard/winpty/issues/105#issuecomment-304309517 によると、最新のinsider buildではすでに直っていて、Creators UpdateでもKB4020102 (OS build number 15063.332)で直るとのこと。

**Comment by mattn** [comment]
winpty の方でも workaround はしない方向すね。僕が KB4020102 で修正確認できたら閉じます。

![KB4020102](http://go-gyazo.appspot.com/653def7ef5d8a4f0.png)

**Comment by mattn** [comment]
治ったので閉じます！

**Comment by k-takata** [comment]
閉じます！ということなので閉じます！！
(xlose/3rdpartyproblem などというタグは無いんだっけ、xlose/pluginproblem ならあるけど。)
