### ISSUE TITLE
あいまい幅文字の表示がおかしい

### ISSUE THREAD

**Issue by uakms** [vim-jp/issues#1047]
### 質問・報告の内容
パッチ 543 を適用したところ、「▽」の文字表示がおかしくなりました。

### Vimのバージョン
- 8.0.0543 以降

### OSの種類/ディストリ/バージョン
- OS X El Capitan 10.11.6
- ターミナル 2.6.1
- iTerm2 3.0.15

### 使用している or 関係していそうなプラグイン
skk.vim を使用していますが関係ないものと思われます。

**Comment by h-east** [comment]
@nakinor Issue登録お疲れ様です:+1:

このpatchで直ることは確認しています。(nakinorさんThanks)
https://gist.github.com/h-east/64994cf789ba6ad377fd7c8cbc8b5080

このpatchが妥当か検証し可能ならtestを追加してvim_devに送信します。

(追記)
私の確認環境
MacOS Sierra 10.12.4
ターミナル 2.7.2 (388.1)
Vim 8.0.0566 (Huge, without GUI)

上記vimで▽が表示されず、patchあてたら表示されることを確認しました。

**Comment by h-east** [comment]
Sent to vim_dev
https://groups.google.com/d/msg/vim_dev/A4ZXSrkjyh0/yYkaQdpKFwAJ

**Comment by uakms** [comment]
Higashi さん、パッチありがとうございました。

次の環境でも不具合があり、パッチを適用することによって解消しました。

- Mac OS X Panther 10.3.9
- ターミナル 1.4.6
- Vim 8.0.566

ちなみに次の環境では不具合は生じていませんでした。

- Windows XP SP3
- GVim 8.0.566
- Vim 8.0.566 (CUI 版でエクスプローラーからダブルクリックで起動したもの。もしくはコマンドプロンプトから vim.exe で起動したもの。ただし、MSYS2/MinGW のシェル(mintty？)から `winpty vim.exe` で起動したものはパッチ前後とも<s>半角扱いとなっていました。</s> Options の Text->Locale を ja_JP にすれば全角で表示されました。)

また、OS X (macOS) 上の Visual Studio Code の TERMINAL で起動した Vim はパッチをあてる前でも▽を全角扱いしてくれていました。

ギリシャやロシアの文字「ελληνικ、Здравствуйте」等も表示ができなくなっていたのですが、ちゃんと見えるようになりました。

**Comment by h-east** [comment]
patch 8.0.0567
https://github.com/vim/vim/commit/fc8f1118e7ccd65b0537e47e6323c93a1df6a61a

私のpatchは`may_req_ambiguous_char_width()`内の判定から`starting == 0`を削除するものでしたが、Bram氏のpatchは、terminalへの曖昧文字幅の問い合わせと背景色の問い合わせをシーケンスの後半に移動させるものです。

帰って動作確認してから閉じます。

このpatch、多分今まで微妙な端末とのタイミングで起きていた環境依存の問題も解消される気がする。起動後1行目に変な文字が表示されるやつとか。

**Comment by h-east** [comment]
動作確認OKでした。閉じます。

Thanks:+1:

**Comment by uakms** [comment]
わたしも直ったのを確認しました。
ありがとうございます！

**Comment by h-east** [comment]
@nakinor and All,
Vim 8.0.0611 https://github.com/vim/vim/commit/976787d1f31451ca7a88e774a03e6c24ddc67876 でterminalへの曖昧文字幅の問い合わせの場所が若干移動しました。
Vim 8.0.0611以降で本Issueの問題が再発していないか確認頂けると嬉しいです。

**Comment by uakms** [comment]
0628 で試してみましたが、元に戻ってしまいましたね……
この不具合って私と higashi さんの環境だけで再現するものでしたっけ？
(最新の macOS と Terminal.app では再現しなかった？)

**Comment by h-east** [comment]
( ﾟДﾟ)ﾋｮｴｰ まさか本当にdegradeしているとわ。。
本Issueの現象はMacなら誰でも遭遇します。
帰ったらvim_devに報告します。
帰るの日付変わるかもなので、誰か報告してくれると嬉しい。

**Comment by h-east** [comment]
Reported.
https://groups.google.com/d/msg/vim_dev/vaoOPlY0fGA/T3c0Rv7jCQAJ

**Comment by ichizok** [comment]
これ、「ambiguous width characters を wide で表示する端末上で、'ambiwidth' の自動判別が (double になるべきところ) single になってしまう」という問題だったんですね。
Ubuntu 16.04 の gnome-terminal でも、Profile 設定で 「Ambiguous-width characters : Wide」にすると再現しました。

**Comment by h-east** [comment]
@ichizok そうです。そうです。MacだけじゃなくてLinuxでも問題起きるんでした。

**Comment by h-east** [comment]
patch 8.0.0629 で改善されたことを確認しました。
https://github.com/vim/vim/commit/6b1da3312e15c065b373c9ec2732f31a77cee61f

**Comment by uakms** [comment]
動作確認しました。
ありがとうございました！
