### ISSUE TITLE
複数ファイル編集後、終了時にフリーズ

### ISSUE THREAD

**Issue by hyuki0000** [vim-jp/issues#1048]
## 質問・報告の内容

- 二つのファイルを行き来して編集した後、`:wq` で終了するとフリーズします。
- 再現手順(2017-04-30 13:01)
    - (0) $ touch a b
    - (1) $ /Applications/MacVim.app/Contents/MacOS/Vim -u NONE -N a
    - (2) `ia<ESC>`で一文字入力して`:w`保存
    - (3) `:e b` でファイル`b`に移る
    - (4) `ib<ESC>`で一文字入力して`:w`保存
    - (5) `:e #`でファイル`a`に戻る
    - (6) `oa<ESC>`で一文字追加して`:wq`実行
    - (7) シェルには戻れない（フリーズ）

- (0) で`a`や`b`を作っておかないとフリーズしないようです。
- (7) でフリーズと書きましたが、`^Z`でシェルには行けます。
- iTerm2とターミナルで同じ症状が出ました。
- `-g` を付けてGUIで実行しても同じ症状が出ました。

## Vimのバージョン

version 8.0.567

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 19 2017 05:46:16)
MacOS X (unix) 版
適用済パッチ: 1-567
Compiled by travis@Traviss-Mac-674.local
```

## OSの種類/ディストリ/バージョン

*  OS X El Capitan 10.11.6

## 使用している or 関係していそうなプラグイン

`-u NONE`で実行しましたので関係なさそうかと思います。

## その他

特にVimの設定をいじった記憶がないのに急に出始めたので気になっています。

**Comment by rbtnn** [comment]
さっと試してみたところ、私の環境では再現しなかったです。

__環境__
OS X El Capitan 10.11.6
Vim 8.0.589 ([Github](https://github.com/vim/vim)のソースからビルドしたやつ)

**Comment by h-east** [comment]
@hyuki0000 
Vim -u NONE -N `-i NONE` a
でも再現するでしょうか？

**Comment by hyuki0000** [comment]
@h-east `Vim -u NONE -N -i NONE a` だと再現しません！

ところが、`-i NONE` をつけなくても再現しなくなってしまいました。
さっきMacBookがおかしくなって一回再起動したせいかもしれません。

もうしわけありません。
現在はissueに立てた現象が再現できなくなっている状況です。

**Comment by uakms** [comment]
わたしも次の環境で再現しませんでした。

OS X El Capitan 10.11.6
ターミナル v2.6.1 および iTerm2 v3.0.15
Vim 8.0.567 および 8.0.589 (いずれも Normal)

また、hyuki0000 さんが使っていると思われる
MacVim + KaoriYa
でも再現しませんでした。

**Comment by h-east** [comment]
@hyuki0000 2週間経過して他の方からも現象発生報告ありませんでしたので、`works for me`で閉じさせていただきます。
再現した場合は本Issueを再オープン下さい。
