### ISSUE TITLE
Vimに非同期機能を実装しよう

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#105]
Vimでは if_mzschme においてmzschemeの非同期機能(擬似スレッド)をサポートするために、本体の方にもいくらか細工してある。イメージ的にはWin3.1のプリエンプティブ・マルチタスク。同じ仕組を使えば、限定的とは言えVimスクリプトに非同期機能を実装できるんじゃなかろうか。

**Comment by mattn** [comment]
そもそも、もうmzschemeって提供されてないのではたして動くかどうかw
先日試したらコンパイルエラーでました。

**Comment by koron** [comment]
名前変わってるよねw

まぁ、あくまでif_mzschemeはそれようのコードを差し込む口実と
挟む場所の目安ということで。
Vimのアイドルループ中にmzschemeに処理を渡す感じ。

**Comment by mattn** [comment]
コルーチンのはずなので、アイドリングで動くスレッドならどれでもいけるはず。

**Comment by mattn** [comment]
問題はvimscriptで非同期にするとして、どのレベルでアトミックにするか。
アトミックにしたとして、はたしてコンテキストスイッチでどれだけ遅くなるか。あと処理トランザクション。

**Comment by koron** [comment]
まずは、単に裏プロセス立ち上げて、その終了と結果をアイドリングループで受け取る、的なものでも充分かもね。

**Comment by koron** [comment]
asynsystem({funcref}) みたいな。

**Comment by tyru** [comment]
#19 とかぶってませんか？

**Comment by Shougo** [comment]
すごく……被っています。

**Comment by koron** [comment]
昔のことは忘れたわ…w

**Comment by mattn** [comment]
閉じますか？
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
　
卵で

**Comment by koron** [comment]
#19 にアイデア移植した。
なのでコチラは卵で閉じる。
