### ISSUE TITLE
`vim -c startinsert` で起動すると表示がおかしい

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1051]
## 質問・報告の内容

1. `vim -Nu NONE -c startinsert file` で起動すると、

* 1行目に `-- INSERT --` の表示が出る（描画上だけで、buffer には入っていない）
* ステータス行の表示が正しくない&amp;切れている
  expect: `-- INSERT --`
  actual: `"file" [New ` （`[New File]` が途中で切れている）

2. `vim -Nu NONE -c startinsert`（ファイルを指定しない）で起動した際、
ステータス行の `-- INSERT --` がboldになっていない場合がある。
何か入力するとboldになる。

## Vimのバージョン

8.0.0596

1. は 8.0.0567 以降
2. は macOS でのみ確認。7.4.898 (pre-installed) でも発生する

## OSの種類/ディストリ/バージョン

1. について

* macOS 10.12.4 / Terminal.app / iTerm2.app / [alacritty](https://github.com/jwilm/alacritty)
* Ubuntu 16.04 / gnome-terminal
  現象は発生しているが、すぐに再描画が走って正常画面になるので
  VNC経由等で描画が遅い状態でないと判別できないと思われる。
* CentOS 7 / console

tmux や mosh の上では発生しない。

### 1. について

8.0.0567 (https://github.com/vim/vim/commit/fc8f1118e7ccd65b0537e47e6323c93a1df6a61a) で ambiwidth 判定 (`may_req_ambiguous_char_width()`) のタイミングが変わったため。

説明のため、端末サイズは 80x24 とする。
Vim 起動後、以下のような流れにより現象が発生する。

* カーソルを最下段の (24, 1) に移動し、`"file" [New File]` を描画する
* `may_req_ambiguous_char_width()` 内でカーソルは (1, 1) に移動されるが、
  `term_windgoto()` による移動のため、Vim はこの状態を追跡してない
  (screen.c の `screen_cur_col`, `screen_cur_row` が更新されない)
* Vim 的にはカーソルは最下段にあるので、そのまま (1, 1) に `-- INSERT --` を描画する
* （本来表示されているはずの）`-- INSERT --` の後続桁を消去するためにカーソルを (24, 13) に移動し、
  erase line するので `"file" [New File]` の `File]` 部分が消える

修正案:

`may_req_ambiguous_char_width()` 内で、カーソル移動後に `screen_start()` を呼んで `screen_cur_col`, `screen_cur_row` をリセットする。

https://github.com/vim/vim/compare/master...ichizok:fix/startup-insert.diff
(インデントが変だったのを直したので変更が多いが、実質 `screen_start()` の追加のみ）

### 2. について

最初の `-- INSERT --` が描画される時点で `highlight_attr` 配列が未設定のため。
その後の状態は DA2 Response を受けるタイミングによる (trachet で観察した限りではそのように見える) 。
DA2 Response が端末画面を空白で初期化している最中に来ると、画面初期化後に modeline を再描画する。
この時点では `highlight_attr` は設定済みなので bold になる。
DA2 Response が早すぎると再描画されずそのまま。

## 関連?

vim/vim#1658

**Comment by uakms** [comment]
I can reproduce the problem too.

### 1. について
![problem](https://cloud.githubusercontent.com/assets/1085119/25950731/d579e786-3696-11e7-84ce-bee24a503d72.gif)

ただし Terminal, iTerm2 共に、あいまい幅文字の設定をオフにした場合にのみ発生しました。

- Terminal
<img width="325" alt="terminal" src="https://cloud.githubusercontent.com/assets/1085119/25950965/3fd3b62a-3697-11e7-8745-adb68b82d5f1.png">

- iTerm2
<img width="325" alt="iterm2" src="https://cloud.githubusercontent.com/assets/1085119/25950982/4df1a0aa-3697-11e7-894a-200d8ec3dbde.png">

### 2. について
Terminal でしか試していませんが、やはり設定がオフの場合に細くなるようです。

- オンの時(こちらが正常？)
<img width="325" alt="on" src="https://cloud.githubusercontent.com/assets/1085119/25951175/de3c1cb2-3697-11e7-95c4-7224e836bcba.png">

- オフの時
<img width="325" alt="off" src="https://cloud.githubusercontent.com/assets/1085119/25951206/f53a3246-3697-11e7-9ae9-e93ca8f9ae27.png">

どちらも起動したばかりの画像ですが、オンの時は初期画面が消えていて、オフの時は消えていません。

**Comment by ichizok** [comment]
@nakinor 検証ありがとうございます。
曖昧幅文字の設定をONにすると、起動シーケンスで `ambiwidth` が `double` になって画面が再描画されるので正常画面になりますね。（gnome-terminal での状況と類似）

**Comment by ichizok** [comment]
問題1は 8.0.0611 で直ったようです。
https://github.com/vim/vim/commit/976787d1f31451ca7a88e774a03e6c24ddc67876

**Comment by mattn** [comment]
今見ると太字に見えますがどうでしょうか？太字というかハイライトされてる。

**Comment by uakms** [comment]
8.0.0688 ですが、問題 1 も、問題 2 も、変化はありませんでした。
(以前のスクリーンキャスト・スクリーンショットと同じ状況です)

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/08aac3c6192f0103cb87e280270a32b50e653be1 も入ったし情報が古いので一旦閉じます。まだ問題が残っていれば新しい issue を起こして下さい。
