### ISSUE TITLE
autocmdで自動でcopenした時にBufReadPost quickfixが反応しない

### ISSUE THREAD

**Issue by itchyny** [vim-jp/issues#1056]
## 質問・報告の内容
quickfix/location listのウィンドウを自動で開く設定と、quickfixが開いた時に何かを行うautocmdがあるとします。

`./vimrc`
```vim
autocmd QuickfixCmdPost [^l]* leftabove copen
autocmd QuickfixCmdPost l* leftabove lopen

autocmd BufReadPost quickfix let b:list = getqflist()
```

```
vim -Nu ./vimrc ./vimrc
cadd
echo b:list
```
これでgetqflist()がb:listにセットされている事を期待したのですが、実際にはされません。これは意図した挙動なのでしょうか。

## Vimのバージョン

8.0.662

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

*   macOS Sierra

## 使用している or 関係していそうなプラグイン
なし

## その他
https://github.com/vim/vim/blob/5fe691240bff11e9618252486147f0156e875666/src/quickfix.c#L3433 のforce=TRUEにすると直るようです。

**Comment by thinca** [comment]
nested を使ってください。

```vim
autocmd BufReadPost nested quickfix let b:list = getqflist()
```

詳細は `:help autocmd-nested` を参照してください。

**Comment by thinca** [comment]
あ、付ける方違ったかも。

```
autocmd QuickfixCmdPost nested [^l]* leftabove copen
autocmd QuickfixCmdPost nested l* leftabove lopen
```

こっちかな? (たまに使うとどっちだかわからなくなる)

**Comment by itchyny** [comment]
ありがとうございます！nested完全に忘れてました。(nestedをleftaboveの前に書くと思い通りの挙動になりました) 感謝 🙏
