### ISSUE TITLE
`]による移動が一文字ずれる

### ISSUE THREAD

**Issue by saihoooooooo** [vim-jp/issues#106]
```
aaaa
```

という行で`Ibbbb<ESC>`と打つと、

```
bbbbaaaa
```

の状態になります。
この時に``]`を入力すると先頭のaに移動してしまいます。
`:h `]`を見てみると

```
To the last character of the previously changed or yanked text.
```

とありますので、本来は最後のbに移動するべきだと思うのですがこれは仕様なのでしょうか。
ちなみにヤンク/ペーストした場合の``]`は範囲がずれることはありません。

**Comment by mattn** [comment]
お手数ですが

```
# vim -u NONE
```

でやってみてもらえますか。

**Comment by saihoooooooo** [comment]
最新版では試せていませんがバージョン7.3.3で試したところ同じ結果になりました。

**Comment by mattn** [comment]
んー、再現しないんです...(最新版 on win)

**Comment by ynkdir** [comment]
確認できました
微妙なとこですね

**Comment by saihoooooooo** [comment]
そうですか。。
自分もwinでして香り屋さんとこで7.3.364を落として再度cmd.exeから`vim -u NONE`や`vim -u NONE -N`など叩きましたが発生しますね。

**Comment by mattn** [comment]
タイミングですか？

**Comment by ynkdir** [comment]
タイミングは関係ないですね。

```
call feedkeys("iaaa\<Esc>Ibbb\<Esc>`]")
```

でカーソルが最初の `a` の上にきませんか。

**Comment by mattn** [comment]
feedkeysだとなりますが、手でやると出ませんね。bの先頭に行きます。

**Comment by ynkdir** [comment]
うちでは手動でもなるんですが
なんでしょうね

**Comment by mattn** [comment]
おろ...
msysのvimだと再現した。

**Comment by mattn** [comment]
あ、うそ。逆でした。

**Comment by h-east** [comment]
Win 32bit 7.3.346 +kaoriya のvim と gvim 両方で再現しました。

**Comment by mattn** [comment]
あ！``[` タイプしてたw

**Comment by h-east** [comment]
@mattn --

**Comment by saihoooooooo** [comment]
oh...

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/eb70fdc7c7bc9da3.png)

**Comment by ynkdir** [comment]
vim_devに質問投げました。

**Comment by ynkdir** [comment]
todo.txtに入りました。

**Comment by saihoooooooo** [comment]
> todo.txtに入りました。

どうもありがとうございます。
ところでtodo.txtを見てみたのですがこれ``[`になってしまってるようですが大丈夫でしょうか。

> `[ moves to character after insert, instead of the last inserted character.
> (Yukihiro Nakadaira, 2011 Dec 9)

**Comment by mattn** [comment]
> ところでtodo.txtを見てみたのですがこれ`[になってしまってるようですが大丈夫でしょうか。

![](http://go-gyazo.appspot.com/8cac41983cbfe518.png)

**Comment by h-east** [comment]
todoリスト入り。(ほんとは `] ) 

> `[ moves to character after insert, instead of the last inserted character.
> (Yukihiro Nakadaira, 2011 Dec 9)

**Comment by k-takata** [comment]
> vim_devに質問投げました。

リンクがなかったので追加。
https://groups.google.com/d/topic/vim_dev/Ni6ostp_wT0/discussion

> todoリスト入り。(ほんとは `] ) 

パッチを投げました。
https://groups.google.com/d/topic/vim_dev/DW-LdcA37_M/discussion
