### ISSUE TITLE
`gvim.exe --serverlist`がエラーダイアログで表示される

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#1060]
## 質問・報告の内容

`gvim.exe --serverlist`や`gvim.exe --remote-expr 1+1`などの結果がエラーダイアログで表示されますが、これは期待動作なのでしょうか？

![ss](https://user-images.githubusercontent.com/1814879/28740666-ad8a5d20-7442-11e7-8eb0-d8ccd3a71589.png)

## Vimのバージョン

8.0.799

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit

**Comment by nocd5** [comment]
[パッチ](https://gist.github.com/nocd5/e052699f8eb67fbbce43edf81454f879)を書いてみたものの、`os_mswin.c`の`display_errors()`を呼ぶのではなく`message.c`の`do_dialog`呼んだ方が良い様な気がしてます。

**Comment by mattn** [comment]
何が期待結果でしょうか？ダイアログじゃなく標準入出力で出るのが期待結果でしょうか？ですと他の方法を考えた方がよさそうです。
あと gui.starting はいろいろな箇所に影響するので別のフラグを付けた方が良い気がします。

**Comment by nocd5** [comment]
色々と説明不足で申し訳ありません。
期待動作は分からないのですが、少なくともエラーダイアログではないのではないか、と思い質問いたしました。
`--help`や`--version`はInfoアイコンのダイアログで表示されるので、それに合わせるのも1つの案かと思い書いたのがパッチです。
せめてスクリーンショットは乗せるべきでした、すいません。パッチを当てた結果が以下です。
![ss](https://user-images.githubusercontent.com/1814879/28743470-af7541c0-7485-11e7-8488-9ebaf22dc548.png)

`--remote-expr`などの結果を使うケースがあれば標準出力の方が扱いやすいと思うので、
mattnさんの仰るように標準入出力に出すのが期待結果かもしれません。

**Comment by ghost** [comment]
WIndows の MessageBox() 関数でいうところの MB_ICONSTOP フラグ ( x ) である現状を MB_ICONINFORMATION ( i ) にした方が意味的に合致するのではないか、という話かと根拠なく思いました。

**Comment by mattn** [comment]
なるほど。僕はどちらかというとスクリーンショットの様な事がしたいのであれば

```diff
diff --git a/src/main.c b/src/main.c
index 268c25627..ab92d57e5 100644
--- a/src/main.c
+++ b/src/main.c
@@ -3980,9 +3980,20 @@ cmdsrv_main(
 	didone = TRUE;
 	if (res != NULL && *res != NUL)
 	{
+#ifdef WIN32
+	    if (!isatty(fileno(stdout)))
+		puts((char *)res);
+	    else
+	    {
+		mch_msg((char *)res);
+		if (res[STRLEN(res) - 1] != '\n')
+		    mch_msg("\n");
+	    }
+#else
 	    mch_msg((char *)res);
 	    if (res[STRLEN(res) - 1] != '\n')
 		mch_msg("\n");
+#endif
 	}
 	vim_free(res);
     }
```
こうやってもいいかなーと思いました。

**Comment by nocd5** [comment]
@ntak さん 簡潔に説明していただきありがとうございます。私がイメージしたのはそういう動作です。
@mattn さん のように標準出力に出すのも良さそうですよね。

期待動作と、それが期待動作たる所以を説明できるよう纏まったら改めて相談させて下さい。

**Comment by k-takata** [comment]
こんなパッチはどうだろう？

```diff
--- a/src/os_mswin.c
+++ b/src/os_mswin.c
@@ -616,9 +616,9 @@ display_errors(void)
 	    if (!isspace(*p))
 	    {
 		(void)gui_mch_dialog(
-				     gui.starting ? VIM_INFO :
+				     !gui.in_use ? VIM_INFO :
 					     VIM_ERROR,
-				     gui.starting ? (char_u *)_("Message") :
+				     !gui.in_use ? (char_u *)_("Message") :
 					     (char_u *)_("Error"),
 				     (char_u *)p, (char_u *)_("&Ok"),
 					1, NULL, FALSE);
```

元々のコードは、GUI起動完了後に display_errors() が呼ばれたときにはエラーとして表示し、GUI起動途中ならinfoとして表示するという意図だと思うので。
で、今回の問題はGUI起動前の gui.starting がセットされる前に display_errors() が呼ばれてしまうことでエラーとして表示されていることなので。
まあ、gui.starting をセットするのでもよいのかもしれませんが。

**Comment by k-takata** [comment]
> あと gui.starting はいろいろな箇所に影響するので別のフラグを付けた方が良い気がします。

8.1.1230のVIMDLL対応では、`--serverlist` のダイアログを表示させるために gui.starting の設定位置を前にずらしてしまったので、VIMDLL無効の場合でも同じ位置で設定してしまってもいいかなという気もしてきました。上のパッチとどっちがいいだろう？

```diff
--- a/src/main.c
+++ b/src/main.c
@@ -178,6 +178,8 @@ main
 #ifdef VIMDLL
     // Check if the current executable file is for the GUI subsystem.
     gui.starting = mch_is_gui_executable();
+#elif defined(FEAT_GUI_MSWIN)
+    gui.starting = TRUE;
 #endif
 
 #ifdef FEAT_CLIENTSERVER
```

**Comment by k-takata** [comment]
[8.1.1301](https://github.com/vim/vim/commit/0b75f7c97cd7f2529884c48dca8edb02abda4bc5) に修正を混ぜ込んでしまいました。
