### ISSUE TITLE
:mapclear が <buffer> の補完に対応していない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1061]
## 質問・報告の内容

タイトルの通りです。
`:mapclear <Tab>` とタイプした時に `<buffer>` が挿入されてほしいです。
現状では `:mapclear ^I` のように Tab 文字が直接挿入されてしまいます。

## Vimのバージョン

8.0.0809

**Comment by ghost** [comment]
```diff
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index f913b19..e91fc97 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -4223,6 +4223,17 @@ set_one_cmd_context(
 	case CMD_xunmap:
 	    return set_context_in_map_cmd(xp, cmd, arg, forceit,
 						      FALSE, TRUE, ea.cmdidx);
+	case CMD_mapclear:
+	case CMD_nmapclear:
+	case CMD_vmapclear:
+	case CMD_omapclear:
+	case CMD_imapclear:
+	case CMD_cmapclear:
+	case CMD_lmapclear:
+	case CMD_smapclear:
+	case CMD_xmapclear:
+	    return set_context_in_map_cmd(xp, cmd, arg, forceit,
+						      FALSE, TRUE, ea.cmdidx);
 	case CMD_abbreviate:	case CMD_noreabbrev:
 	case CMD_cabbrev:	case CMD_cnoreabbrev:
 	case CMD_iabbrev:	case CMD_inoreabbrev:
```
気づけばあとは単純作業でしたが、追試は必要かと思います。コードの周囲を見回すに現状こうなっていない理由が何かあるのかもしれないという部分は気になるところであります…。

**Comment by tyru** [comment]
ありがとうございます！
試してみたのですが、`:map` 等と同じ補完の動作になっていると思うのですが、
`:mapclear` は引数として lhs や rhs などの引数は受け取らず、`<buffer>` ぐらいしか受け取らない（他にもあるかもしれませんが）と思うので、`:mapclear <Tab>` と押した時点で即座に `<buffer>` が補完される動作がいいと思うのですが、どうでしょうか？

**Comment by mattn** [comment]
僕も昼間そこまで書いて `<buffer>` の様な修飾しかいらないわとなって捨てました。

**Comment by ghost** [comment]
ワーオ(´ー｀)難易度
`set_context_in_mapclear_cmd()` を書く利益があるのか、あってもパッチとして各方面に受け入れてもらえるのかがまた考えどころのようで…。

**Comment by mattn** [comment]
lang の message/ctype/time があるくらいなので、あってもいいと思います。

**Comment by h-east** [comment]
@ntak `EXPAND_MESSAGES`でgrepすれば、ヒントになると思います。

**Comment by mattn** [comment]
おっ clear しか候補が無いのに補完できる messages さんやw

**Comment by h-east** [comment]
> `EXPAND_MESSAGES`でgrepすれば、ヒントになると思います。

8.0.0034
https://github.com/vim/vim/commit/9e507ca8a3e1535e62de4bd86374b0fcd18ef5b8

**Comment by ghost** [comment]
ワーオをキメてからこっち撤退か継続かといろいろ悩みましたが、寝て起きたらどうでもよくなり、継続して取り掛かることに今決めました。疲れたら休むべき。ご支援ありがとうございますヽ(´ー｀)ノ。

**Comment by ghost** [comment]
拡張性というものが少しわかった気がします。動作より意味合い的なものが気になるお年頃(44)。
https://gist.github.com/ntak/d3c52e35004ee2f0819444e2b24a27e2

**Comment by ghost** [comment]
と決め打ちしてしまっていますが個人的には使ったことがない `mapclear` に対して
`<buffer>` 以外に何が補完できるべきという部分に理解が進んでおりませんで、
今は `<buffer>` 一項目だけを補完する状態ですが、ほかに入れるべき候補は存在しますでしょうか？
いまいち頼りなくてすみません…。

**Comment by tyru** [comment]
@ntak パッチ試しました。バッチリでした！

> 今は <buffer> 一項目だけを補完する状態ですが、ほかに入れるべき候補は存在しますでしょうか？

おそらく `<buffer>` 以外にないかと思います。
念のため不慣れながらも Vim のソースコードを見て、`<buffer>` に関しては `getchar.c` の `map_clear()` で パースされていますが、それ以外の場所で引数の文字列に参照されていなかったので、おそらくないかと思います。

**Comment by ghost** [comment]
よかった(´ー｀)です。
あとはテストを書いて必要があればドキュメントを変更したうえで提出という流れでいきますね。

**Comment by ghost** [comment]
提出しました。技術の進歩とちょっとの取り残され感と…。
https://github.com/vim/vim/pull/1943

**Comment by h-east** [comment]
@ntak :+1:
ドキュメントを更新する必要があります。
(`:h getcompletion()` と `:h :command-completion` )

**Comment by ghost** [comment]
そうでした。何やってるんだろう。ご指摘ありがとうございます。

**Comment by ghost** [comment]
再提出の必要があるかと思ったら push に追従していたというのが今日のびっくりハイライトです。

**Comment by h-east** [comment]
8.0.0878 早い:+1:
https://github.com/vim/vim/commit/cae92dc3d5bdd4009910671328cd01394bfbe2cf

**Comment by mattn** [comment]
速いw

**Comment by ghost** [comment]
わっほい！ヽ(´ー｀)ノありがとうございました！

**Comment by tyru** [comment]
@ntak ありがとうございました！
