### ISSUE TITLE
'indentexpr' が設定されているのに 'smartindent' を設定すると挙動が変わる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#1062]
## 質問・報告の内容
発端
[teratail: Vimのオートインデントがコメントアウトで無効になる](https://teratail.com/questions/86742)

Vim起動
```bash
$ cat aaa.py
def hoge()
    print('Hello world.')
$ vim --clean aaa.py
```
Vimの設定を確認
```vim
:verbose set indentexpr
  indentexpr=GetPythonIndent(v:lnum)
        Last set from ~/product/github/vim/runtime/indent/python.vim
:set si?
nosmartindent
```
以下のコマンドを実行
```vim
Go#<Esc>
```
結果 (期待通り)
```python
def hoge()
    print('Hello world.')
    #
```
設定変更
```vim
set smartindent
```
以下のコマンドを実行
```vim
Go#<Esc>
```
結果 (期待と異なる)
```python
def hoge()
    print('Hello world.')
    #
#                          ← 何で？
```
期待値
```python
def hoge()
    print('Hello world.')
    #
    #
```
根拠
```
:h 'si
			     *'smartindent'* *'si'* *'nosmartindent'* *'nosi'*
'smartindent' 'si'	切替	(既定ではオフ)
	～
	'cindent' がオンか 'indentexpr' が設定されているときは  'si' をオンにし
	ても効果はない。
```

## Vimのバージョン

8.0.0839

**Comment by h-east** [comment]
patch
https://gist.github.com/h-east/aa38a9e1da23a7ccc69417bc174177e4

make testは`ALL DONE`です。
test足さなきゃ。。

**Comment by k-takata** [comment]
> 'cindent' か 'indentexpr' がオンのときは 'si' をオンにしても効果はない。

訳がおかしかったので修正しておきました。 https://github.com/vim-jp/vimdoc-ja-working/commit/0d87d4fd6b0415377a6f733fd74edf3426fd377a

**Comment by h-east** [comment]
test追加してvim_devに送付。
https://groups.google.com/d/msg/vim_dev/i9DXyGKjrzI/CLoWxJs-BgAJ

**Comment by k-takata** [comment]
8.0.0851
https://groups.google.com/d/topic/vim_dev/s5a-zcOzPhw/discussion
