### ISSUE TITLE
Windows 版で引数の解析が2回実行されている

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1066]
```
C:\>vim `test`
```
これを実行すると本来1回だけコマンドが実行されるべきが2回実行されている。Windows の場合、諸事情により fix_arg_enc で引数のエンコーディング修正が行われておりその際にワイルドカードの展開も行われている。(alist_expand がそれ)

しかしその後 main.c でもう一度 alist_expand が呼び出されている。どういう事情でこうなったか良く覚えてないのですが、出来れば main.c 側をカットしたい。

```diff
diff --git a/src/main.c b/src/main.c
index 81eb1a679..f5b7b004e 100644
--- a/src/main.c
+++ b/src/main.c
@@ -227,7 +227,7 @@ main
 
     if (GARGCOUNT > 0)
     {
-#ifdef EXPAND_FILENAMES
+#if defined(EXPAND_FILENAMES) && !(defined(WIN32) && defined(FEAT_MBYTE))
 	/*
 	 * Expand wildcards in file names.
 	 */
```

ちなみに backtick コマンドを実行して正常に終了した場合はその結果が得られてるけど、異常終了した場合は

```
`test`
```
という変な引数が残ってしまうけど、それは別途直したい。

**Comment by k-takata** [comment]
`enc` を設定すると fix_arg_enc が呼ばれますが、逆に `set enc=utf-8` を .vimrc 内で実行しなかった場合もそれで大丈夫でしょうか？

**Comment by mattn** [comment]
良くないすね。あんまり時間取れそうにないので https://github.com/vim/vim/pull/1938 こっちの方にはまだ問題があるとだけ追記しておきました。

**Comment by mattn** [comment]
[8.0.0876](https://github.com/vim/vim/commit/39d21e3c30f3391f3b27f5ddb7e1ad411bdb8f2e)
