### ISSUE TITLE
encoding=utf-8 で印刷時に「ページ」が折り返される。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1069]
![3d5d24441cab7d11](https://user-images.githubusercontent.com/10111/29300314-a85dc038-81af-11e7-8a02-993349d5c0ca.png)

※ xps で印刷した結果

**Comment by k-takata** [comment]
#408 以来の課題です。

**Comment by mattn** [comment]
ねるほど。いっそ英語にしてしまって日本語にしたいユーザには vimrc で設定してもらうって方が良いのかしら。

**Comment by mattn** [comment]
せっかくなのでと思って試したら
![23e4d6e1762eae45](https://user-images.githubusercontent.com/10111/29302169-d7f61b80-81bc-11e7-97e5-07d3a7cab67f.png)
折り返されました。

**Comment by mattn** [comment]
こちら直ってました。

**Comment by k-takata** [comment]
手元では現象が再現しなかったのと、Windowsの印刷関係のコードはここ最近誰もいじっていないような気がするのですが、設定や環境依存だったのでしょうかね？
