### ISSUE TITLE
mingw ビルドが libwinpthread-1.dll を要求する。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1070]
http://lingr.com/room/vim/archives/2017/08/16#message-24216857

>libwinpthread-1.dll が必要な件ですが、
>https://bitbucket.org/k_takata/vim-ktakata-mq/src/e72851da1a90ecdf07f64c10eab1a85a05519eee/mingw-link-libgcc_eh-explicitly.patch?at=default&fileviewer=file-view-default
>先ほどのパッチを当てて、STATIC_STDCPLUS=yes を指定してビルドすれば余計なdllは不要になります。

**Comment by k-takata** [comment]
これですが、MSYS2 MinGW-w64 の gcc が ver.6 だか 7 だかにバージョンアップして以降、このパッチを当てないと libwinpthread-1.dll が必要になってしまいました。
ただ、このパッチを当てると、TDM-GCC-64 でビルドできなくなってしまうと思われます。というのは、TDM-GCC-64 には libgcc_eh が無いようなので。

ということで、複数バージョンの MinGW-w64 でビルドできない問題が解決しない限り、このパッチを vim_dev に出す予定はありません。

**Comment by mattn** [comment]
>TDM-GCC-64 には libgcc_eh が無いようなので。

ふぉwww

ちなみにですが、mingw32-make の引数で変えれるようにも出来ないですっけ？

**Comment by mattn** [comment]
まぁ出来なくないけどニッチすぎるってのがありますね。

**Comment by k-takata** [comment]
> ちなみにですが、mingw32-make の引数で変えれるようにも出来ないですっけ？

もちろんできなくはないですが、そこまでするの？ということですね。あと、するならオプション名はどうするのとか。

libgcc_eh の有無が、gccのバージョンの違いによるものなのか、例外処理の方式の違い（SJLJ, Dwarf2, SEH）によるものなのかは、把握していません。

**Comment by k-takata** [comment]
Related: vim/vim#2827

**Comment by k-takata** [comment]
[MXE (M cross environment)](https://mxe.cc/) で使われている MinGW-w64 GCC 5.5.0 には libgcc_eh があった。
MSYS2 MinGW-w64 の GCC 7.3.0 にもある。
Cygwin MinGW GCC 4.7.3 にもある。
Cygwin MinGW-w64 GCC 6.4.0 にもある。
なぜか TDM-GCC-64 の GCC 5.1.0 にはない。

しかし、`-lgcc_eh` の代わりに `-static-libgcc` などとしても効果がないのが残念。

**Comment by k-takata** [comment]
GCCのバージョンとか、例外処理がSJLJかDW2かというのは関係なく、なぜかTDM-GCC-64だけ libgcc_eh がない。
あっ、TDM-GCC-64を捨てれば解決か！ｗ

**Comment by k-takata** [comment]
> これですが、MSYS2 MinGW-w64 の gcc が ver.6 だか 7 だかにバージョンアップして以降、このパッチを当てないと libwinpthread-1.dll が必要になってしまいました。

そもそもこれの原因は GCC の Thread model が win32 から posix に変わったことだったりするだろうか？（当時のバイナリが手元にないため不明。CygwinのMinGW 4.7.3と、MXEの5.5.0はwin32だが、CygwinのMinGW-w64 6.4.0とTDMの5.1.0とMSYS2の7.3.0はposix。）

**Comment by k-takata** [comment]
32bitターゲットのMinGWの比較

Environment          | GCC Ver. | libgcc_eh | Thread | Exception
---------------------|----------|-----------|--------|-----------
Cygwin MinGW         | 4.7.3    | Yes       | win32  | Dwarf2
TDM-GCC-64 MinGW-w64 | 5.1.0    | No        | posix  | SJLJ(?)
MXE MinGW-w64        | 5.5.0    | Yes       | win32  | SJLJ
Cygwin MinGW-w64     | 6.4.0    | Yes       | posix  | SJLJ
MSYS2 MinGW-w64      | 7.3.0    | Yes       | posix  | Dwarf2

**Comment by k-takata** [comment]
https://bitbucket.org/k_takata/vim-ktakata-mq/src/eb27c934f5637bf7ceb3f5df1ff33852614a0261/mingw-link-libgcc_eh-explicitly.patch?fileviewer=file-view-default
パッチ大幅書き換え。TDM-GCCは `HAS_GCC_EH=no` を指定すればビルドが通るはず。

**Comment by k-takata** [comment]
8.1.0490: https://github.com/vim/vim/commit/eda9e9c2fe4577ad451418253b990a3f60b70444

**Comment by k-takata** [comment]
追加修正 8.1.0861: https://github.com/vim/vim/commit/60f807b3f71a92881e2b3bf48bd016294957130e
