### ISSUE TITLE
% の挙動がバックスラッシュ文字によって変わる不具合

### ISSUE THREAD

**Issue by phonje** [vim-jp/issues#1074]
## 質問・報告の内容

不具合を報告します。

ノーマルモード時、下記のテキストの行頭で % キーをストロークすると意図しない挙動をします。
(\\())
本来なら2つ目の閉じ括弧へカーソルが移動すべきところ、1つ目の閉じ括弧へ移動します。
% によってジャンプできるような文字のペア (括弧など) がバックスラッシュの直後にあると、
その文字がペアとして働かずに無視されるような挙動になります。

また、ビジュアルモード時のキーストローク a( でも同様の不具合が起きました。
(1つ目の閉じ括弧までしか選択されない)

## Vimのバージョン

8.0

## OSの種類/ディストリ/バージョン

Linux / ArchLinux / Linux version 4.12.8-2-ARCH

**Comment by mattn** [comment]
cpoptions の値を教えて下さい。

```
:set cpoptions?
```
`:help cpo` より引用
```
		M	これが含まれていない場合、"%" での括弧の対応にバックス
			ラッシュを考慮に入れる。すなわち "( \( )" や "\( ( \)"
			で外側の括弧同士が対応するようになる。"%" が含まれてい
			る場合はVi互換になり、バックスラッシュは無視される。
```

**Comment by phonje** [comment]
aABceFs でした。

M が含まれていないということは、バックスラッシュが考慮されているということで、
不具合ではなく仕様だったのですね。

お騒がせしました。

**Comment by mattn** [comment]
はい。ありがとうございます。また何か問題見つけたら教えて下さい。
