### ISSUE TITLE
端末をフルスクリーン・最大化するとポップアップメニューの残像が残る

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#1077]
## 質問・報告の内容

カーソル位置から上方向にポップアップメニューが表示されている状態で、端末を最大化・フルスクリーンにするとポップアップメニューの残像が残りました。
端末の縁をマウスドラッグで拡大した場合は再現しません。

sample.vim:
```vim
execute 'normal!' winheight('%') . 'o'
call feedkeys("Gi\<C-x>\<C-v>")
```
Vim起動:
端末を最大化・フルスクリーンされてない状態にしてからVimを起動します。
ポップアップメニューが表示されたら、手動で端末を最大化またはフルスクリーンにしてください。
```
$ vim --clean -S sample.vim
```

![xfce4-terminalで再現した時の画像](https://user-images.githubusercontent.com/18260849/29813807-2dbfbed4-8ce6-11e7-839b-16472ed9d49b.png)

## Vimのバージョン

8.0.1010

## OSの種類/ディストリ/バージョン

*   Linux Debian stretch 9.1 64bit

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/popupmenu.diff
単純に `update_screen` してしまう手。

**Comment by norio13** [comment]
ありがとうございます。
ichizokさんのpatch適用で残像が消えました。

ichizokさんのpatchを適用するまで気付かなかったのですが、
patch未適用のVimで端末のサイズを```フルスクリーン・最大化```から```元のサイズ(小さいサイズ)```に変更すると、ポップアップメニューとカーソルが被ってました。
こちらもpatch適用で修正されているのが確認できました。

xfce4-terminalでポップアップメニューとカーソルが被っている画像:
![xfce4-terminalでポップアップメニューとカーソルが被っている画像](https://user-images.githubusercontent.com/18260849/30061933-560e5f6e-9284-11e7-989b-8b221d4bbcaa.png)

**Comment by ichizok** [comment]
投げました。
https://github.com/vim/vim/pull/2110

**Comment by ichizok** [comment]
todo入り
https://github.com/vim/vim/commit/37c64c78fd87e086b5a945ad7032787c274e2dcb#diff-38d7929bd26d74d92ceddf984bbfc8dbR166

**Comment by mattn** [comment]
テストがこけてるっぽいすね

https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/500/job/kforu9e7r7ld0e2e

**Comment by k-takata** [comment]
See: https://groups.google.com/d/msg/vim_dev/RskqZ2J-040/DBiEWaZTBwAJ

**Comment by ichizok** [comment]
8.0.1161
https://github.com/vim/vim/commit/a5e6621aadadf78c7b344e93a4b328788076f14c

**Comment by norio13** [comment]
ありがとうございます。

2017-12-27 19:28 GMT+09:00 ichizok <notifications@github.com>:
