### ISSUE TITLE
GVimのスナップ状態が解除されることがある

### ISSUE THREAD

**Issue by ichitera** [vim-jp/issues#1078]
## 質問・報告の内容

GVimをWindowsの機能で画面端にスナップしているときにウィンドウの分割・タブの開閉を行うと、
スナップが解除されてしまいます。

この解除を起こさずにウィンドウの分割やタブの開閉操作をしたいです。

再現の手順は次です。

**vsplitの場合**
1. gvim -u NONE -U NONEにてgvim.exeを起動
2. 起動したgvim.exeのウィンドウを画面端に動かしてスナップさせる
3. `:vsplit`を実行
4. (スナップが解除される)
5. 2.を行って再度スナップさせる
5. `:q`を実行
6. (スナップが解除される)

**タブの場合**
1. gvim -u NONE -U NONEにてgvim.exeを起動
2. 起動したgvim.exeのウィンドウを画面端に動かしてスナップさせる
3. `:tabnew`を実行
4. (スナップが解除される)
5. 2.を行って再度スナップさせる
5. `:tabclose`を実行
6. (スナップが解除される)

このスナップ解除が起きているところを撮影したアニメーションが次です。
![animation](https://user-images.githubusercontent.com/31098747/29907076-60219e1e-8e54-11e7-9beb-dfc9a3bb1618.gif)

## Vimのバージョン

8.0.1026 ([vim-win32-installer](https://github.com/vim/vim-win32-installer/)より入手したもの)

## OSの種類/ディストリ/バージョン

Windows 10 Home 64bit (10.0.10586)

## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by k-takata** [comment]
`:vsp` を実行すると左ウィンドウにスクロールバーを表示するためにウィンドウサイズが変更され、`:tabnew` の場合はGUIのタブバーを表示するためにウィンドウサイズが変更されてしまいます。
そして、スナップ状態の時にウィンドウサイズを変更してしまうとスナップが解除されてしまいます。そこで、スナップ状態の時はウィンドウサイズを変更しないようにできればいいのですが、スナップ状態かどうかの判別ができるのかどうかがわかりません。

ただ、設定で何とかする方法も一応あります。
垂直分割に関しては、`set guioptions-=L` で左のスクロールバーを全く表示しないようにすれば、サイズ変更を抑制できます。（あるいは `set guioptions+=l` で常に表示。）
タブに関しても、`set guioptions-=e` で、GUIタブバーを表示しないようにしてしまえば、サイズ変更を抑制できます。

**Comment by ichitera** [comment]
少しだけ気になっていたので報告をしたのですが、実現できるか怪しいかもしれないものなのですね。

オプションについてもありがとうございます。頂いた設定で使っていこうと思います。
(特にタブに関して、`set guioptions-=e`するとマウスで並び替えやクローズができるようになり、便利になりました。ありがとうございます。)

**Comment by k-takata** [comment]
> 特にタブに関して、set guioptions-=eするとマウスで並び替えやクローズができるようになり、便利になりました。

実は4年近く前から、GUIでもマウスで並べ替えできるようにするパッチを提案しているのですが、残念ながらまだ取り込まれていません。 #484

**Comment by k-takata** [comment]
本家で、リサイズを抑制するために guioptions に s フラグを追加するという提案が出ていました。 vim/vim#703

**Comment by k-takata** [comment]
[8.0.1278](https://github.com/vim/vim/commit/8ac441576fd219fb7227349e228d5b68520b204a) で guioptions に k フラグが追加されました。

> 実は4年近く前から、GUIでもマウスで並べ替えできるようにするパッチを提案しているのですが、

こちらもすでに取り込まれています。

**Comment by ichitera** [comment]
k-takataさん、ご対応をありがとうございました。
