### ISSUE TITLE
win32: 環境変数の設定がユニコードに対応してない

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#108]
encoding=utf-8 時に :let $env = 'まるちばいと' で文字化けする

**Comment by mattn** [comment]
やられます？

**Comment by ynkdir** [comment]
私はあんまりすぐにやりたい感じではないので
mattnさんかどなたかもしできそうならお願いします。

**Comment by mattn** [comment]
`termencoding` に変換すべきか、iconv() の to に `char` を指定してロケールにするか。ただ後者の場合、iconvのバージョンが古いと失敗するんですよねー。

**Comment by mattn** [comment]
windows限定なら GetACP() でいいんでしょうねー。ただwindowsだけ特例はあかんって思われそうな気もする。

**Comment by ynkdir** [comment]
私はwindowsだけしか考えてなかったんですけどどうでしょね。

**Comment by koron** [comment]
でも、encのデフォ設定ってOSで決まるでしょ? WindowsならGetACP()で。
同じ理屈なんじゃない?

**Comment by ynkdir** [comment]
私的にはWindowsの文字コードはユニコードなので対応してほしいという程度の意識でした。
unix系はencを変更することはあんまりないと思いますし特に最近はutf-8一択なのであんまり困らないかなと。

**Comment by koron** [comment]
今、これパッチ書こうとして気になったんだけど…

os_win32.h で mch_setenv を setenv にdefineしているんだけど、
今のMSのドキュメントだとWin32にsetenvは無いことになってる。(putenvならある)
なんでsetenvで動いてんだろ?

ちなみにwchar_tでsetenvする関数があれば
os_win32.cにこんな関数を追加すれば比較的簡単に対応できることがわかった。

``` c
    int
mch_setenv(var, value, x)
    char *var;
    char *value;
    int  x;
{
#ifdef FEAT_MBYTE
    if (enc_codepage >= 0 && (int)GetACP() != enc_codepage)
    {
        WCHAR       *wvar;
        WCHAR       *wvalue;
        // TODO:
    }
#endif
    return setenv(var, value, x);
}
```

**Comment by mattn** [comment]
基本的に、環境変数設定は `vim_setenv()` が呼ばれ、それの各OS処理として `mch_setenv()` がありますが、`vim_setenv()` の中身を見てもらえると分かりますが、`HAVE_SETENV` が undefined なので `putenv()` が使われます。

**Comment by koron** [comment]
なるほどややこしいなw

**Comment by koron** [comment]
これ `putenv()` の代わりに `SetEnvironmentVariable()` 使っても大丈夫ですかねぇ?
副作用がないか的な意味で。

大丈夫なら `SetEnvironmentVariableW()` 使えば
os_win32.c内の他の関数と実装パターンが同じにできていい感じなんですが。

**Comment by mattn** [comment]
`enc_to_utf16` すね。提案は出来ると思いますし、きっとOKも出そうな気がします。

**Comment by koron** [comment]
では、基本方針としてはHAVE_SETENV定義して、
os_win32.cで `mch_setenv()` 実装して `enc_to_utf18` を噛ませる方向で。

**Comment by mattn** [comment]
出来ればencを見て動作を変えたいかも。もしかしたら環境変数値に機種依存文字を含んでたり...

**Comment by koron** [comment]
どゆこと? 明示的に iconv 使いたいってこと?

**Comment by mattn** [comment]
enc_utf8 の場合だけ SetEnvironmentVariableW、そうじゃない場合は現状(putenv)もしくは SetEnvironmentVariableA

**Comment by koron** [comment]
それいうなら他のやつも同時に解決したほうが良いのでは?
なんかファイル名絡みとかいろいろありそう。

**Comment by koron** [comment]
ああ、そういえば他のやつはACPが同じならAっぽいのに回るようになってたな。

**Comment by ynkdir** [comment]
SetEnvironmentVariable() で設定した環境変数は getenv() でとれなかったと思いますたしか。

**Comment by ynkdir** [comment]
msvcrtの話です。
他にCランタイムがあればまた違うんだと思いますが。

**Comment by koron** [comment]
あ！たしかにw
私もなんかあったよなぁ、と思ってたんですよ。

**Comment by mattn** [comment]
あれか... environ[] すね。

**Comment by koron** [comment]
パッチ書いた。こんなんでどうだろ?

https://gist.github.com/1486374

**Comment by ynkdir** [comment]
ありがとうございます。
動きました。

あと実はユニコード対応ということだとgetenvの方も多少問題ありっぽいです。
acpの範囲内で使う分には問題なさそうですが。

``` vim
" on cp932 windows

:set encoding=utf-8

:let $a = "\u00E1"    " LATIN SMALL LETTER A WITH ACUTE
:echo $a
a
:echo $a == "a"
1

:let $sun = "\u2600"  " BLACK SUN WITH RAYS
:echo $sun
?
:echo $sun == "?"
1
```

**Comment by mattn** [comment]
このあたり、パッチを出す前に整理した方がいい気がする。
たとえばgrepprgに設定してる値が 

```
C:\プログラム\grep.exe
```

だったとしてencodingの変更でそれも変換されるべきなのかどうなのか...とか。
このパッチを一度出しちゃうと、しまいに全部やらなきゃいけない気がするのです。
それだった、encodingを変えた本人が`iconv`使ってでも直すべきとするとかってのもアリなんかなぁと。

**Comment by ynkdir** [comment]
仮にWindowsでのencodingのデフォルトをユニコードにしたとして、動くかどうか、というのを個人的には考えていまして
encoding変更の副作用の問題とは別物かなと思ってます。

**Comment by koron** [comment]
環境変数については特別と考えたほうが良いのでは?

UNIX系では環境変数系のencodingはユーザ解釈に任されていますが、
Windowsではシステムが面倒みてます。
なのでWindowsに限ってはVimもそのルールに従いましょうね、ということでしょう。

os_win32.cを見てるとファイル名もほぼそんな感じ。

Vimの変数についてはまた別途、かしらねぇ。

**Comment by koron** [comment]
考えてみたら、これWindowsだけやっちゃうとスクリプト的にはキツいね。
OS毎に書き方を変えなきゃいけなくなる。
かといってスクリプト側でiconv挟む方式も、
環境変数に格納する為のencodingをどこからもってくるのかはOS依存じゃまいか?

悩ましいなぁ。

**Comment by koron** [comment]
vim_getenv()はenc=utf-8の時だけ、値をACPから変換してたwww

**Comment by koron** [comment]
これ、そろそろパッチを送るべきかなぁ。

**Comment by koron** [comment]
ん～ vim_dev に問題提起すべき?

**Comment by mattn** [comment]
パッチ付きで提案してみたら？

**Comment by koron** [comment]
おけ。お仕事一段落したら送ります。

**Comment by koron** [comment]
あ、これ送るべきなのか… パッチの最新版は [コレ](https://bitbucket.org/koron/vim-kaoriya-vim-mq-ex/src/03ba6365ad169e7bfb10109b5d3b9d1e1c5236f6/patch-enc_considered_setenv.diff?at=default) で良いのかな。

**Comment by ynkdir** [comment]
wgetenv はどうですかこんな感じで (未テスト) https://gist.github.com/4634974

**Comment by ynkdir** [comment]
むー、HOMEが日本語だとだめか…

**Comment by ynkdir** [comment]
いや、home_replace()がおかしいだけか。
scriptnamesや&rtpがcp932のままなのにutf-8な$HOMEがとれるので置換できない。
これはまあどのみちしょうがない。

mch_getenv() の返り値は単に次回呼び出し時に解放しちゃうとまずいので上の実装はだめですね。
`static char_u *alloced[256]` とかでいいのだろうか。あんまり美しくない。

なんか難しそうなので setenv だけでも全然かまわないです。
すいません。

**Comment by k-takata** [comment]
最新ソース用
https://bitbucket.org/k_takata/vim-ktakata-mq/src/1af3dfb3943f12a8b6fdf313de7cc89068e5f027/win32-setenv-with-encoding.patch?at=default&fileviewer=file-view-default

**Comment by k-takata** [comment]
Posted.
https://groups.google.com/d/topic/vim_dev/LV1Tpa_IKqg/discussion

**Comment by k-takata** [comment]
8.0.0280
https://groups.google.com/d/topic/vim_dev/6HALwrx_nSg/discussion
早い！

**Comment by k-takata** [comment]
wgetenv 対応していないのはどうしよう。
