### ISSUE TITLE
foldmethod=expr なバッファに setbufline() 使った場合の挙動がおかしい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#1080]
## 質問・報告の内容

`foldmethod=expr` が設定されているバッファに対して `setbufline()` 関数を使い、配列を渡して複数行を設定しようとすると、1行目のみが本来の対象バッファに設定され、残りはカレントバッファの指定行(元々指定した先の本来設定されるべき行番号)に残りの行が設定されます。

### 再現手順

```vim
" reproduce.vim
setlocal foldmethod=expr foldexpr=0
new
call setbufline(1, 1, [1, 2, 3])
```

```
$ vim --clean -S reproduce.vim
```

### 期待する動作

bufnr=1 のバッファに、`1 2 3` の3行が表示される。

### 実際の動作

bufnr=1 のバッファには `1` のみが表示され、bufnr=2 のバッファ(カレントバッファ)に `2 3` の行が表示される。

## Vimのバージョン

8.0.1052

## OSの種類/ディストリ/バージョン

*   Gentoo Linux

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/setbufline.diff

`curwin` も退避して、対象バッファの `b_wininfo->wi_win` を `curwin` にしてますが
`hide` したバッファの場合は `b_wininfo->wi_win == NULL` なので `curwin` はそのままです。
window に付随する情報で予期しない変更が発生するかもしれません。

**Comment by thinca** [comment]
@ichizok これって今どういうステータスでしょう? 私の動作確認待ちですか?

**Comment by ichizok** [comment]
@thinca そうですね。

**Comment by thinca** [comment]
@ichizok 返事遅くなりました。パッチ試しました。
最初に報告した現象は直っていました。ありがとうございます！
他に懸念があるようですが、常用して試そうにも現状の `setbufline()` がこの状態なので正直使い物にならず、`setbufline()` を使ったスクリプト自体が普段の環境にないため、常用して試すのも難しそうです。
なのでひとまず提出してしまうのはどうでしょうか?

**Comment by ichizok** [comment]
投げました。
https://github.com/vim/vim/pull/2293

**Comment by thinca** [comment]
取り込まれました！ありがとうございました！

https://github.com/vim/vim/commit/0c4dc88a637a5027209aa00226996af84e248636

patch 8.0.1274
Problem:    setbufline() fails when using folding.
Solution:   Set "curwin" if needed. (Ozaki Kiichi, closes #2293)
