### ISSUE TITLE
warnings with the over-the-spot patch

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1082]
## 質問・報告の内容

#874 の over-the-spot パッチ以降、コンパイル時にwarningが出るそうです。
https://groups.google.com/d/msg/vim_dev/-acKWk-MjIo/QlqPzpQ0DAAJ
以下、 ログからの抜粋

> mbyte.c:4874:5: warning: ‘gdk_screen_get_width’ is deprecated [-Wdeprecated-declarations]
> mbyte.c:4875:5: warning: ‘gdk_screen_get_height’ is deprecated [-Wdeprecated-declarations]
> mbyte.c:4908:5: warning: ‘gtk_widget_modify_font’ is deprecated: Use 'gtk_widget_override_font' instead [-Wdeprecated-declarations]
> mbyte.c:4911:5: warning: ‘gdk_color_parse’ is deprecated: Use 'gdk_rgba_parse' instead [-Wdeprecated-declarations]
> mbyte.c:4912:5: warning: ‘gtk_widget_modify_fg’ is deprecated: Use 'gtk_widget_override_color' instead [-Wdeprecated-declarations]
> mbyte.c:4915:5: warning: ‘gdk_color_parse’ is deprecated: Use 'gdk_rgba_parse' instead [-Wdeprecated-declarations]
> mbyte.c:4916:5: warning: ‘gtk_widget_modify_bg’ is deprecated: Use 'gtk_widget_override_background_color' instead [-Wdeprecated-declarations]

## Vimのバージョン

8.0.1026 以降

## OSの種類/ディストリ/バージョン

*   Linux

**Comment by mattn** [comment]
https://patchwork.kernel.org/patch/9397505/

```diff
+#if GTK_CHECK_VERSION(3, 22, 0)
+        {
+            GdkDisplay *dpy = gtk_widget_get_display(widget);
+            GdkWindow *win = gtk_widget_get_window(widget);
+            GdkMonitor *monitor = gdk_display_get_monitor_at_window(dpy, win);
+            GdkRectangle geometry;
+            gdk_monitor_get_geometry(monitor, &geometry);
+            screen_width = geometry.width;
+            screen_height = geometry.height;
+        }
+#else
+        {
+            screen_width = gdk_screen_get_width(screen);
+            screen_height = gdk_screen_get_height(screen);
+        }
+#endif
```
モニタからジオメトリを取るという修正が必要らしい。

**Comment by mattn** [comment]
GtkCssProvider ってのを使って色は行けそうだけど、フォントを直すとなると PangoFontDescription を生で使うのすら deprecated らしく大改造になりそう。

**Comment by k-takata** [comment]
gdk_screen_get_width/height の対応、そっくりそのままVim向けに直してみました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/b196427eeaccf65b08d07bb69e202322f4eabd4f/fix-warning-of-overthespot.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
8.0.1084
https://groups.google.com/d/topic/vim_dev/XnSvDc6p6j8/discussion
Bramに大幅に書き直されたｗ

**Comment by k-takata** [comment]
残りはGTKのエキスパートが直してくれました。
8.0.1099
https://groups.google.com/d/topic/vim_dev/gw9dcQfsSAI/discussion
