### ISSUE TITLE
iminsert=0 imsearch=0 をデフォルトにしたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1083]
vimtutor を使う日本人であればインサートモードでいきなり日本語入力になってしまうのは問題があると思うので、できれば iminsert=0 imsearch=0 にしたい。

GitHub Issues に RFC 流して意見があれば交換、無理そうだとしてもせめて GetACP() == 932 は 0 とかにしたい。

ちょっと作戦を考えますが、ぜったい変更させる何かいい案があれば教えて下さい。

**Comment by k-takata** [comment]
影響があるのはWindowsのGUIだけでしょうか？

**Comment by mattn** [comment]
<del>はい。その予定です。</del>

実際は vim.h の USE_IM_CONTROL の宣言

```c
#if defined(FEAT_XIM) \
    || (defined(FEAT_GUI) && (defined(FEAT_MBYTE_IME) || defined(GLOBAL_IME))) \
    || (defined(FEAT_GUI_MAC) && defined(FEAT_MBYTE))
# define USE_IM_CONTROL
#endif
```
が通れば B_IMODE_IM が設定され、デフォルト値 2 が設定されるので、影響は Windows, Linux, OSX の GUI 版です。

**Comment by mattn** [comment]
https://github.com/vim/vim/issues/2071

**Comment by k-takata** [comment]
8.0.1114
https://github.com/vim/vim/commit/4cf56bbc85f77846aeb378cfb071677336dfad6d
やりましたね！！！
