### ISSUE TITLE
行の真ん中を示すモーション

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1084]
画面の真ん中を示すモーション `gm` はあるけど行の真ん中を示す物がない。

See http://qiita.com/masayukiotsuka/items/683ffba1e84942afbb97

`gM` で作ってみました。

**Comment by mattn** [comment]
<del>マルチバイトの考慮が無いすね</del>

直した。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2070

**Comment by mattn** [comment]
Bram の提案で `20gM` で 20% の位置を示すモーションになりそう。

**Comment by thinca** [comment]
TODO Listed
https://github.com/vim/vim/commit/5be4ceecea5520265066eac972460ebb1cdf05e7#diff-38d7929bd26d74d92ceddf984bbfc8dbR193

**Comment by thinca** [comment]
(よく見たらすでに載ってて該当コミットは位置が移動しただけだった 😅)

**Comment by h-east** [comment]
patch 8.1.2231
https://github.com/vim/vim/commit/8b530c1ff91f07cf6b0289a536992b7dfbc86598
