### ISSUE TITLE
`vim.exe -` で文字化け

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1087]
## 質問・報告の内容

`.vimrc` で `set enc=utf-8` を設定していると、`vim.exe -` で標準入力から読み込む際のメッセージが文字化けします。

英語メッセージ:

```
Vim: Reading from stdin...
```

翻訳後の(本来表示されるべき)メッセージ:

```
Vim: 標準入力から読込中...
```

問題の個所は fileio.c の readfile() にあります。

```C
	    mch_msg(_("Vim: Reading from stdin...\n"));
```

#931 (#1064) で直ったかと思っていましたが、msg_puts_printf() でエンコーディングを変換してから mch_msg() を呼ぶようにする修正だったため、今回の部分には影響が及びませんでした。

## Vimのバージョン

8.0.1098

## OSの種類/ディストリ/バージョン

*   Windows 10

## 課題

mch_msg() を呼ぶ前にエンコーディングの変換を行うか、あるいは mch_msg() の中で変換を行うように修正すべきか？もし mch_msg() の中で変換するなら mch_err_msg() はどうすべきか。

fileio.c のほかには、main.c の中から `--help` などで mch_msg() を呼んでいますが、`.vimrc` での設定が読み込まれる前のようなので、エンコーディングの変換は行わずとも問題なく表示されています。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/3914

**Comment by k-takata** [comment]
#931 への影響は出ませんか？

**Comment by k-takata** [comment]
チェックすべき項目:

* `vim --help`
* `vim --cmd "set enc=utf-8" -` (本件)
* `vim --cmd "set enc=utf-8" --cmd "call confirm('Foo')" -u NONE` (#931)
* `vim --cmd "set enc=utf-8"` で起動して、`:!deadbeef` を実行 (#1064)

で、文字化けしないこと。（enc=cp932 も見ておいた方がいいかな？）

**Comment by mattn** [comment]
あと `!deadbeef` も足したいです。それと元の問題の確認 `cat | vim -`

**Comment by k-takata** [comment]
`mch_msg()` の呼び出しを `msg_puts()` に変えてしまうのはどうだろう？
Unix系で問題が起きるだろうか？

**Comment by k-takata** [comment]
> Unix系で問題が起きるだろうか？

gVimで標準出力にメッセージが出なくなってしまった。残念。

**Comment by mattn** [comment]
https://github.com/mattn/vim/commit/1960ce370329714695d7b2e2601bfb0c67a17049

これでどうでしょうか。まだツメは甘いと思いますが。

**Comment by k-takata** [comment]
まだ内容を把握できていませんが、とりあえず気になったのは、`USE_CR` はおそらく旧Mac用の定義で、Windowsなら `USE_CRNL` ではないかという点と、コンソールのCPは GetACP() ではなく GetConsoleCP() でチェックすべきではという点です。

**Comment by mattn** [comment]
もろもろ対応

https://github.com/mattn/vim/commits/fix-mch_msg

**Comment by mattn** [comment]
ｷｴｰｯ テストこけるのか。

https://travis-ci.org/mattn/vim/builds/492597745

再ﾁｬﾚ

https://travis-ci.org/mattn/vim/builds/492645445

**Comment by k-takata** [comment]
`msg_puts_printf()` 内の変更は、以前の修正のrevertと何を行ったのでしょうか？
os_mswin.c の修正は何のためのものでしょうか？

あとは、Linuxで `./vim -g -f -` 等の動作が問題ないか確認しておきたいですね。

**Comment by mattn** [comment]
エンコーディングを末端の関数 mch_msg/mch_errmsg で行う修正です。

msg_puts_printf は1文字ずつ出力していたので中で呼び出している mch_msg がエンコード変換できなくなるので行毎に mch_msg を呼び出す様にしています。その方が効率がいいというのもあります。

os_mswin.c の修正は error_ga を表示するコードでしたが、error_ga を追加している箇所はもうなかったので代わりにオリジナルの fflush(stderr) の代わりになる FlushFileBuffers に変更しました。

**Comment by mattn** [comment]
error_ga を使う形にできないか今調べてるとこです。

**Comment by mattn** [comment]
これは前からですが `vim -E > out` して `:echo 1` しても out に出力されないのはバグとして扱うべきですかね。

**Comment by mattn** [comment]
[8.1.0918](https://github.com/vim/vim/commit/9b5c1fcdeae75f82a2083fafbbf75ab220f6ac1e)

**Comment by k-takata** [comment]
8.1.0918: https://github.com/vim/vim/commit/9b5c1fcdeae75f82a2083fafbbf75ab220f6ac1e
