### ISSUE TITLE
[doc] empty() のドキュメントが不親切

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1088]
https://twitter.com/mattn_jp/status/908152437529239552

> ちなみにですが、Vim script は len(str) より empty(str) の方が速いのでどんどん empty(str) 使って行こう。(Vim の話はしていない) 

https://twitter.com/pink_bangbi/status/908188761007075328

> これ、 :help empty() には文字列に対する記述は載っていないが、:if !empty("foo") みたいな example はドキュメントに乗っているので :help empty() にもちゃんと記述するべきではないだろうか #重箱の隅 

という事で empty() の doc に少し手を入れた方が良いかもしれない。現状は以下

```
empty({expr})						*empty()*
		Return the Number 1 if {expr} is empty, zero otherwise.
		- A |List| or |Dictionary| is empty when it does not have any
		  items.
		- A Number and Float is empty when its value is zero.
		- |v:false|, |v:none| and |v:null| are empty, |v:true| is not.
		- A Job is empty when it failed to start.
		- A Channel is empty when it is closed.

		For a long |List| this is much faster than comparing the
		length with zero.
```

`:help TRUE` には一応例がある。

```
							*TRUE* *FALSE*
For boolean operators Numbers are used.  Zero is FALSE, non-zero is TRUE.
You can also use |v:false| and |v:true|.  When TRUE is returned from a
function it is the Number one, FALSE is the number zero.

Note that in the command: >
	:if "foo"
	:" NOT executed
"foo" is converted to 0, which means FALSE.  If the string starts with a
non-zero number it means TRUE: >
	:if "8foo"
	:" executed
To test for a non-empty string, use empty(): >
	:if !empty("foo")
```

**Comment by k-takata** [comment]
いろいろまとめて投げました。
https://groups.google.com/d/topic/vim_dev/KlCEH3dI_rg/discussion

**Comment by k-takata** [comment]
Fixed.
https://github.com/vim/vim/commit/b0d45e7f5354375edd02afafde3bd37dac1515ff#diff-bea881dfa9626bab7141337b0fcdb23eR3464
