### ISSUE TITLE
v8.0.1102以降で :terminal の地の文(?)の文字が意図しない色で表示される

### ISSUE THREAD

**Issue by tkfm-yamaguchi** [vim-jp/issues#1090]
## 質問・報告の内容

後述の環境以外では確認していないのですが, v8.0.1101 と v8.0.1102 とでTerminal ウィンドウ内の文字の色が異なって表示されます. v8.0.1102 で Terminal highlight-group が導入されていますが, そちらは未設定の状態です.

v8.0.1101 での表示:  
![capture 2017-09-15 9 59 26](https://user-images.githubusercontent.com/99848/30462846-50770aca-9a03-11e7-9678-c06dc904ec95.png)

v8.0.1102 での表示:  
![capture 2017-09-15 10 01 33](https://user-images.githubusercontent.com/99848/30462848-5a05c630-9a03-11e7-94fc-f4942cc0dff7.png)

v8.0.1102 以降でも, ターミナル(not in vim)での表示と同じ v8.0.1101 での色で表示されるようにしたいのですが, 対策等コメントいただれば幸いです.

## OSの種類/ディストリ/バージョン

* OS: Ubuntu 16.04.3 (MacOS(10.12.6) の iTerm2(3.0.15) から SSH 経由で接続)
* Shell: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by k-takata** [comment]
terminalの色については、v8.0.1103で再度修正が入っていますので、まずはそちらで確認してみてください。

**Comment by tkfm-yamaguchi** [comment]
コメントありがとうございます. 

v8.0.1103 ではありませんでしたが, v8.0.1106 で改善されていたことを確認いたしました.

![capture 2017-09-15 11 34 24](https://user-images.githubusercontent.com/99848/30463979-def5c47a-9a09-11e7-8d32-f923ea205933.png)

![capture 2017-09-15 11 36 04](https://user-images.githubusercontent.com/99848/30464036-1949f2fe-9a0a-11e7-8da4-d491acda854d.png)

まず最新版で確認すべきでした. お騒がせして申し訳ありません.

v8.0.1106のパッチの内容は Windowsのコンソール向けで, Windowsのレイヤが一切ない自分の環境に影響があったのが不思議ですが, 当初の問題は解決しましたので close いたします.

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/69e8aa75112a0b12811a4f4d11061adceffbbabc#diff-f83301fc7928a73575f006ec59a872b6R2501

この初期化がされてなかったのが原因だと思います。

**Comment by tkfm-yamaguchi** [comment]
コメントありがとうございます.

https://github.com/vim/vim/commit/c71053c61180ed1ad0c98ba6063b769757832932#diff-f83301fc7928a73575f006ec59a872b6R2505

↑で必要な `INVALCOLOR` による初期化が 1106 で入っていたのですね.
