### ISSUE TITLE
FEAT_WINDOWS 削除のおかげで既存パッチの多くがマージ出来なくなっている

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1095]
見つけた物から作者に報告したり、直したりしていくスレッド。

**Comment by mattn** [comment]
[#2060 vim.exe to 24bit color](https://github.com/vim/vim/pull/2060)

これは @ntak さんにお願いしよう

**Comment by mattn** [comment]
[#2069 avoid heavy redrawing while modifying highlight](https://github.com/vim/vim/pull/2069)

これ僕予約

**Comment by ghost** [comment]
今出ました(´ー｀)。

**Comment by mattn** [comment]
この issue、閉じようがない気がしてきたので閉じます。(ntak さんのは追従できてそうなので)
