### ISSUE TITLE
MacでVimの端末を開くと背景色の表示が灰色になる

### ISSUE THREAD

**Issue by KiYugadgeter** [vim-jp/issues#1096]
## 質問・報告の内容

(Stackoverflow日本語版でも質問しましたがここにもあげておきます)

[Vim terminalの背景色を変える - スタック・オーバーフロー](https://ja.stackoverflow.com/questions/37761/vim-terminal%e3%81%ae%e8%83%8c%e6%99%af%e8%89%b2%e3%82%92%e5%a4%89%e3%81%88%e3%82%8b)
Vimの端末機能`:terminal`を起動すると背景色が灰色に表示されてしまいます。

macOSのTerminal.appでterminalを開くと背景色が灰色で表示されます。
Vimはhomebrewで`--HEAD`オプション付きでビルドされていて、`vim --version`は下のようになっています
Terminal.appは256色表示までしか対応していないため
TERM=xterm-256colorとなっており、さらに私はvimrcで`t_Co=256`に指定しています。

## Vimのバージョン

8.0.1127

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 19 2017 21:07:02)
MacOS X (unix) version
Included patches: 1-1127
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -L/usr/local/lib -F/private/tmp/vim-20170919-42330-1w5vwiy/Frameworks -L/usr/local/lib -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.0.0 -lobjc    
```

### 設定値
.vimrc
```
t_Co=256
set notermguicolors
```
環境変数
```
TERM=xterm-256color
```

## OSの種類/ディストリ/バージョン

*   macOS 10.12.6  

 
## 使用している or 関係していそうなプラグイン

`vim -N -u NONE`で起動しても再現したので、なさそう

**Comment by mattn** [comment]
notermguicolor なので

https://github.com/vim/vim/blob/2e6ab18729a634f3223a92be318e98e87b572a7b/src/terminal.c#L2560-L2569

ここに入り、おそらく Terminal ハイライトグループを設定されておられないはずなので id は 0 なんだけど

```c
    void
syn_id2cterm_bg(int hl_id, int *fgp, int *bgp)
{
    struct hl_group	*sgp;

    hl_id = syn_get_final_id(hl_id);
    sgp = &HL_TABLE()[hl_id - 1];	    /* index is ID minus one */
    *fgp = sgp->sg_cterm_fg - 1;
    *bgp = sgp->sg_cterm_bg - 1;
}
```
これ他のシンタックスハイライトを見てしまってないかなー。

```diff
diff --git a/src/syntax.c b/src/syntax.c
index 6361bd7aa..554629fb9 100644
--- a/src/syntax.c
+++ b/src/syntax.c
@@ -9753,6 +9753,12 @@ syn_id2cterm_bg(int hl_id, int *fgp, int *bgp)
     struct hl_group	*sgp;
 
     hl_id = syn_get_final_id(hl_id);
+    if (hl_id == 0)
+    {
+	*fgp = -1;
+	*bgp = -1;
+	return;
+    }
     sgp = &HL_TABLE()[hl_id - 1];	    /* index is ID minus one */
     *fgp = sgp->sg_cterm_fg - 1;
     *bgp = sgp->sg_cterm_bg - 1;
```

**Comment by ichizok** [comment]
GNOME-Terminal on Ubuntu 16.04 でも同様でした。
端末アプリケーション側でウィンドウの背景色を白 (255, 255, 255) にして
シェル上で `printf "\e[48;5;255m \e[0m\n"` (256colorの白) を出力すると灰色っぽいので、
256colorで背景色を設定するとウインドウ自体の背景色と異なってしまうのだと思います。

**Comment by mattn** [comment]
@ichizok えと、仕様通りという事でしょうか？(すいません確認してません)

**Comment by ichizok** [comment]
だと思います。

**Comment by mattn** [comment]
https://github.com/vim-jp/issues/issues/1096#issuecomment-331329877 の件は現状 syn_id2cterm_bg は terminal.c からしか呼んでなくて、かつ id > 0 の時にしか来ないので、不恰好ではあるけど放置します。

**Comment by ichizok** [comment]
> 端末アプリケーション側でウィンドウの背景色を白 (255, 255, 255) にして
> シェル上で printf "\e[48;5;255m \e[0m\n" (256colorの白) を出力すると灰色っぽいので、
> 256colorで背景色を設定するとウインドウ自体の背景色と異なってしまうのだと思います。

すみません、アプリケーション側のANSIカラーパレットの設定が原因でした。
なので、例えば Terminal.app ならプロファイル設定でANSIカラーを調整すれば白背景になります。

**Comment by ichizok** [comment]
@KiYugadgeter お使いの端末アプリケーションでカラーパレットの設定を調整してみてください。

**Comment by KiYugadgeter** [comment]
Terminal.appの環境設定を開いて自分が使っているプロファイルのANSIカラーの`ホワイト (明)`(一番右下)を調整したところ背景色も白くなりました
![2017-09-22 23 52 25](https://user-images.githubusercontent.com/7894040/30750500-b23b3a8a-9ff1-11e7-8db5-2048d0b88b83.png)

**Comment by KiYugadgeter** [comment]
@mattn @ichizok ちなみに`Terminal`のカラーグループを
```
autocmd * ColorScheme highlight Terminal ctermbg=none
```
と設定すれば透明(背景色と同じ)にすることができるということでしょうか?

**Comment by mattn** [comment]
libvterm に透明という属性が無い気がしますので、現状は vim の背景色という事になると思います。(ソースを見た限りです)

**Comment by KiYugadgeter** [comment]
`autocmd * ColorScheme highlight Terminal ctermbg=none`
を設定してみたのですが、下の画像のようにTerminalの背景が白く(Terminal.appのANSIカラーコードでの白色、つまり見た目は灰色)になってしまいます。
これは下のエディタ部分のようにカラーコードに関わらず白(#ffffff)になるのではないのでしょうか?

![2017-09-23 18 06 31](https://user-images.githubusercontent.com/7894040/30771862-abbef526-a08b-11e7-9217-d8e4257f818d.png)

**Comment by KiYugadgeter** [comment]
(コメントを消してしまったので書き直しました)
@mattn terminalでのvimの背景色というのは256colorの白(Terminal.appでは灰色に表示される)ということになるのでしょうか?
ANSIカラーの設定をデフォルトに戻した後に`autocmd * ColorScheme highlight Terminal ctermbg=none`と設定したのですが背景色が白ではなく灰色になります

**Comment by mattn** [comment]
none を設定したとしても、上記で書いた通り libvterm には透明という属性が無いので、何かしらの色を与えてあげなくてはなりません。現状は none なのでカラースキームの背景色、つまり Normal グループの背景色になると思います。こちらも試してはないので、本当かは分かりません。

**Comment by mattn** [comment]
あ、端末版だと Normal グループは無かったですね。すみません、このパッチ試して頂けますか？

```diff
diff --git a/src/syntax.c b/src/syntax.c
index e0736cb63..3e6f80734 100644
--- a/src/syntax.c
+++ b/src/syntax.c
@@ -9762,6 +9762,12 @@ syn_id2cterm_bg(int hl_id, int *fgp, int *bgp)
     struct hl_group	*sgp;
 
     hl_id = syn_get_final_id(hl_id);
+    if (hl_id == 0)
+    {
+	*fgp = -1;
+	*bgp = -1;
+	return;
+    }
     sgp = &HL_TABLE()[hl_id - 1];	    /* index is ID minus one */
     *fgp = sgp->sg_cterm_fg - 1;
     *bgp = sgp->sg_cterm_bg - 1;
```

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:feature/term-no-color.diff
`Terminal` 未設定かNONEで背景と同じになる（色を設定しない）ようにしてみました

**Comment by mattn** [comment]
@ichizok あ、alpha なんてのかあったのか。知らんかった。 👍

**Comment by ichizok** [comment]
@mattn 勝手に追加したんですけど、libvtermのソースいじるのはまずいですかね？

**Comment by mattn** [comment]
あっw libvterm を弄ったかw
Bram の考えなので聞いてみないと分からないす。

**Comment by mattn** [comment]
一回出してみて反応悪そうなら vterm_state_get_default_colors で比較しながらってのもあるかもですね。

**Comment by KiYugadgeter** [comment]
@mattn @ichizok パッチ適用してビルドしてみましたが灰色のままでした

**Comment by ichizok** [comment]
パッチ更新。
@KiYugadgeter 一応、パッチがきちんと当たっているか確認してもらえますか？

**Comment by KiYugadgeter** [comment]
@mattn @ichizok https://github.com/vim/vim/compare/master...ichizok:feature/term-no-color.diff
を適用してデフォルトのANSIカラーコードのprofileでterminalを起動したところ
白く(#FFFFFFで)表示されました。

**Comment by ichizok** [comment]
https://github.com/vim/vim/commit/a0a6f2776eabfbd4d9174fabdf3921beb7348eda#commitcomment-24784964
なぜアプリケーションのfg/bg colorをパススルーしたらダメなのかよくわからない...

**Comment by ichizok** [comment]
8.0.1359 から `:hi Terminal` 未設定または `NONE` の場合にアプリケーション自体の fg/bg color を透過するような動作になりましたが、Bram の意図通りなのかは不明です。

**Comment by ichizok** [comment]
@KiYugadgeter 現状でこれ https://github.com/vim-jp/issues/issues/1096#issuecomment-331603466 は実現できているので、クローズしてもよいでしょうか？
