### ISSUE TITLE
WinBar をクリックするとマウス選択になって使い辛い

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1097]
vim 8.0.1129

```
amenu 1.10 WinBar.TEST1         :echo 'TEST1'<CR>
amenu 1.10 WinBar.TEST2         :echo 'TEST2'<CR>
```
![0ba1186dbbda65ca](https://user-images.githubusercontent.com/10111/30726450-d5fa8e4c-9f85-11e7-84bd-a4a6ee7edb21.png)

TEST1 をクリックしたあと、TEST2 をクリックするとテキスト選択になってしまって使い辛い。

![terminal3](https://user-images.githubusercontent.com/10111/30726475-fad3f26c-9f85-11e7-9379-757424917b80.gif)

**Comment by mattn** [comment]
あとカーソル形状このままでいいのかって問題もある。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2138

**Comment by tyru** [comment]
PR 先はクローズになってるみたいです。

**Comment by mattn** [comment]
[patch 8.0.1138](https://github.com/vim/vim/commit/eb163d73b11c10b461a2839530173a33d7915a33)
