### ISSUE TITLE
tmuxでWindowを切り替えると直前に入力したシングルバイト文字が消える

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#1099]
## 質問・報告の内容

1. tmuxの中で```vim --clean```または```vim -Nu NONE```でVimを起動します。
2. マルチバイト文字を挿入します。
3. 2のマルチバイト文字の前にシングルバイト文字を挿入します。
4. tmuxで別Windowに切り替えてから元のWindowに戻すと、入力したシングルバイト文字が消えます。

入力文字の右隣りにマルチバイト文字が存在すると再現しました。

端末(xfce4-terminal)の背景色を茶色、vimのカラースキームshineにして再現した時の画像を載せます。

Windowを切り替える前の画像:
![Windowを切り替える前の画像](https://user-images.githubusercontent.com/18260849/30798722-9b8bed04-a215-11e7-9137-b8c8831d1a4f.png)

Windowを切り替えた後の画像:
茶色で塗り潰されているように見える箇所の色は、端末の背景色と同色です。
![Windowを切り替えた後の画像](https://user-images.githubusercontent.com/18260849/30798744-a87ae7a4-a215-11e7-899f-6664b0e266de.png)

Vimと関係なかったらすみません。

## Vimのバージョン

8.0.1144

## OSの種類/ディストリ/バージョン

Linux Debian stretch 9.1 64bit

## 使用している or 関係していそうなプラグイン

- xfce4-termnal 0.8.3-1
- tmux 2.5-2~bpo9+1

**Comment by mattn** [comment]
CTRL-L すると再描画されるでしょうか？

**Comment by norio13** [comment]
CTRL-L で再描画されました。
CTRL-L してからWindowの切り替えを行った場合も正常に描画されました。

**Comment by ichizok** [comment]
シェル上の文字入力でも再現したので、tmuxの問題と思います。

**Comment by norio13** [comment]
失礼致しました。
tmuxの方に後ほど報告してきます。
mattnさん、ichizokさん、サポートありがとうございます。
