### ISSUE TITLE
コマンドラインのマップ関数でredirすると先頭の":"が消える。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#11]
vim-ambicmdの様にコマンドラインのキーマップから関数内で

```
redir => cmdlistredir
silent! command
redir END
```

といった事をやると

```
:ssssssss
```

の後でスペースを押すと

```
 ssssssss
```

になってしまう。
vim-ambicmdはスペース発動だが、例えば`X`で発動させると(`ambicmd#expand()`にXを渡すと)

```
Xssssssss
```

となる。
なお、vim-ambicmdでは候補が見つかると`\<bs>`を実行するので、コマンドライン行が書き換えられてうまく行く。
候補が見つからない場合、つまり
1. redirする
2. コマンド行を変更しない、もしくは追加のみする

で再現する。おそらく issue #8 の関連で、redir時にmsg_colの値を書き換えてしまっているのが問題。
redir中lazyredrawでくくって見たけど駄目。

**Comment by thinca** [comment]
私の環境 (7.3.303) で再現しません。他に条件はありますか?

**Comment by mattn** [comment]
vimrcを以下だけにして、bundleディレクトリにvim-ambicmdだけ置いた状態でコマンドライン版vim.exeで再現しました。

```
set nocompatible
exe "set rtp+=".(has('win32')||has('win64') ? '~/vimfiles/bundle/vim-pathogen' : '~/.vim/bundle/vim-pathogen')
call pathogen#runtime_append_all_bundles()
cnoremap <expr> <Space> ambicmd#expand("\<Space>")
cnoremap <expr> <CR>    ambicmd#expand("\<CR>")
finish
```

vimは最新です。

**Comment by thinca** [comment]
Windows版vimで再現しました。
Linux版だと再現せず…。
ちなみに先頭の文字は発動させたキーではなく `ambicmd#expand()` に渡したキー(=返ってくるキー) に変化するようです。

**Comment by mattn** [comment]
です。ちなみに`ambicmd#expand()`の最下行で

```
return "X\<bs>".a:key
```

とやると綺麗に出ます。workaroundですが...

**Comment by thinca** [comment]
ですね。見た目の問題で実害はないので、それはやりたくないですね。

**Comment by mattn** [comment]
パッチ作りました。

https://groups.google.com/d/topic/vim_dev/s6gBfTa47EQ/discussion

あとはBram次第。

**Comment by ynkdir** [comment]
自分の確認方法が悪いのかもしれませんがうちでは以下の手順では再現できません。
windows vista vim-7.3.315 32bit です。
とりあえず念のためご報告。

```
Try following on windows.

---- script1 ----
function! DoSpace()
  return ' '
endfunction
cnoremap <expr> <space> DoSpace()
----

---- script2 ----
function! DoSpace()
  redir => foo
  silent! command
  redir END
  return ' '
endfunction
cnoremap <expr> <space> DoSpace()
----

When run script1 and type ":XXX " in normal mode, you'll see ":XXX ".
But if run script2 and type it, it show " XXX ". You can see ":" is erased in command line.
```

**Comment by mattn** [comment]
cmap/cnoremap系プラグインを併用すると再現しない可能性があるらしいですが、どうでしょうか？

**Comment by ynkdir** [comment]
vim -u NONE
gvim -u NONE
で試してます。

**Comment by mattn** [comment]
あれ...
thincaさんと僕は再現してるので、何かの要因で再現しない条件があるのかな

**Comment by thinca** [comment]
`-N` を付けたらどうなります?

**Comment by ynkdir** [comment]
-N 付きで再現できました。

**Comment by mattn** [comment]
fixed in 7.3.385

https://groups.google.com/d/topic/vim_dev/4mbGeAG0OVo/discussion
