### ISSUE TITLE
Windowsの:terminal上でclsして、<C-w>Nでノーマルモードに移るとclsでクリアした内容が残っている。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#1102]
## 質問・報告の内容

`:terminal`上で`cls`して、`Ctrl-w N`でノーマルモードに移ると`cls`でクリアした内容が残ってしまう。
たぶん、最新のVimであれば、Windowsに関係なく発生すると思われる。

これは仕様なのか？確認したいです。よろしくお願い致します。

## Vimのバージョン

8.0.1159

## OSの種類/ディストリ/バージョン

* Windows 10

**Comment by mattn** [comment]
クリアした内容が残るというのは、スクロールアップすると cls した以前のテキストがが残っているという意味であってますか？
であれば現状は仕様です。winpty から画面のスクロールアップの制御コードが来ると Vim はスクロールバッファに蓄積する様にしています。
また winpty は コンソールスクリーンバッファ=ウィンドウサイズ という動きしか出来ませんので、cls の時に消せるのは ウィンドウサイズでしかないです。

唯一できるとすると、cls の時に飛んでくる `\x1b[2J` をハンドリングしてスクロールバッファも消してしまう事ですが、おそらくこれは Bram の期待する物ではない(スクロールバッファで残したい)と思います。

**Comment by rbtnn** [comment]
> クリアした内容が残るというのは、スクロールアップすると cls した以前のテキストがが残っているという意味であってますか？

そうです。

仕様なら問題ないです。ありがとうございます。
