### ISSUE TITLE
:terminal 経由でインタラクティブな操作をするツールで enter が効かない

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/issues#1103]
## 質問・報告の内容

1. Vim で terminal を起動
```
vim --clean
:terminal
```

2. `gof`, `peco`, `fzf` などのツールを起動
```
$ ls | gof
```

3. ファイル一覧の中から適当に選択し(選択候補が複数ある最初の位置が望ましい) `enter` キーをヒット
4. カーソルが下に移動する(期待する動作はファイルが選択され、プロンプトに表示される)

注: 当然 Vim の `:terminal` 経由でないターミナルでは正常に動作します。

## Vimのバージョン

Linux 8.01149
Mac  8.01098

## OSの種類/ディストリ/バージョン

* Linux Ubuntu 16.04
* macOS Sierra

## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

Vim の `:terminal` の問題なのか、インタラクティブな操作を行うツールの問題なのか切り分けができてないです。

**Comment by k-takata** [comment]
これかな？ vim/vim#1998

**Comment by heavenshell** [comment]
おお、ありがとうございます！

発見した経緯としては vim-fz で MacVim(Terminal.app 経由)で Enter が効かない(Ubuntu では OK)ので `:terminal` 経由で `gof` を動かしたらどうなるんだ？というので発見したんですが、既知な問題なのですね…。
(vim-fz の問題はまた別かとは思いますが)

既知ということで閉じたほうがいいでしょうか？

**Comment by k-takata** [comment]
直ってないですし、openのままでいいと思います。

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/6daeef1933be68055aabe1d55f8467d46a707753/src/terminal.c#L1550-L1556

```c
	    /* Get the current backspace and enter characters of the pty. */
	    if (get_tty_info(fd, &info) == OK)
	    {
		term_backspace_char = info.backspace;
		term_enter_char = info.enter;
		term_nl_does_cr = info.nl_does_cr;
	    }
```

https://github.com/vim/vim/blob/6daeef1933be68055aabe1d55f8467d46a707753/src/terminal.c#L756

```c
	case CAR:		c = term_enter_char; break;
```

ここ、`ICRNL` (と `ONLCR`) の変換を Vim 側で処置する必要ないように思うんですが...
これ消せば直るんじゃないでしょうか？

https://github.com/vim/vim/compare/master...ichizok:fix/term-enter-key.diff

**Comment by rhysd** [comment]
同根か分からないですが，MacVim の :terminal で，zsh 上で Enter を押すと zshrc で Ctrl+j に割り当てているキーバインドが発動してしまう症状を確認しています．カーソルが下に移動するのは Ctrl+j と扱われているからなのかも…？上の @ichizok さんのパッチはちょっと時間ある時に試してみようと思います．

**Comment by tyru** [comment]
自分もこれと類似した事象に出くわしました。
vim の :terminal 内で git commit して起動した vim 内で `:wq<CR>` とタイプしても、`:wq` のままエンターが認識されませんでした (しょうがないので `<Esc>ZZ` して保存・終了させました)。
vim ならコマンドラインで `<CR>` が来ても `<C-j>` が来ても `:wq` が実行されるはずなので、何か違う原因による事象のような気もしますが、よろしくお願いします。

**Comment by tyru** [comment]
すみません、間違えて閉じちゃいました…

**Comment by tyru** [comment]
ちなみに 100% 再現する訳ではありませんでした。
再現する場合としない場合で操作が違った可能性もあるので今度再現したらまた報告します。

**Comment by heavenshell** [comment]
普段使いが zsh なんですが、bash にして Vim(MacVim) を Terminal.app で起動し、`:terminal bash` すると、Enter で カーソルが下に移動しないですね。

zsh から MacVim を起動して同様の動作をしたんですが、再現する場合と再現しない場合があってよく分からない…。

@ichizok さんのパッチは時間が出来た時に試してみます。

**Comment by ichizok** [comment]
@tyru `cmap <C-j>` で何か設定されてませんか？

**Comment by tyru** [comment]
あ！すみません、`lmap <C-j>` に eskk.vim のマッピングがしてあります。

**Comment by tyru** [comment]
あー lmap だけじゃなく cmap もありますね。
`<C-j>` が送られてたら[上記のような動作](https://github.com/vim-jp/issues/issues/1103#issuecomment-336907527)になりますね。

**Comment by k-takata** [comment]
> ここ、ICRNL (と ONLCR) の変換を Vim 側で処置する必要ないように思うんですが...
> これ消せば直るんじゃないでしょうか？

vim_devに投げちゃって様子を見てはどうでしょうか。問題報告が複数上がっているようですし。

**Comment by heavenshell** [comment]
遅くなってすみません。パッチを試してみました。
@ichizok さんに書いていただいたパッチでいけそうです。

パッチ適応前
![none_patch](https://user-images.githubusercontent.com/56591/32273743-0200c7b4-bf47-11e7-91ec-0268a18c742c.gif)

パッチ適応後
![patch](https://user-images.githubusercontent.com/56591/32273763-15461dba-bf47-11e7-827f-759a6d76b590.gif)

**Comment by ichizok** [comment]
投げてみました。
https://github.com/vim/vim/pull/2278

**Comment by heavenshell** [comment]
ありがとうございます！！！

**Comment by rhysd** [comment]
遅くなってしまってすみませんが， @ichizok さんのパッチを試してみたところ私の zsh で Enter が C-j と認識されている問題も起きなくなることを確認しました．

**Comment by h-east** [comment]
Bram氏が ichizok さんのとは違うソリューションのpatchを書きました。こちらで確認をお願いします。

8.0.1261
https://github.com/vim/vim/commit/1232624ae5b56c167c5982a2620f736c4bbc19ef

追記: `:term tig status`で試したら直ってますね:+1:

**Comment by rhysd** [comment]
8.0.1267 で試してみたのですが，zsh の問題は解決していませんでした．Enter や C-m が C-j だと認識されてしまいます．

**Comment by k-takata** [comment]
8.0.1277
https://groups.google.com/d/topic/vim_dev/qshxXROJrl4/discussion

**Comment by mattn** [comment]
やったー

**Comment by heavenshell** [comment]
わーい！ @ichizok さんありがとうございます！！

**Comment by h-east** [comment]
@heavenshell さん報告の件は Vim 8.0.1261 でfixされていますよ。
