### ISSUE TITLE
インクリメンタルサーチ中にすべてのマッチをハイライトしたい

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#1104]
## 質問・報告の内容

表題の通り、インクリメンタルサーチ中にすべてのマッチをハイライトをする機能が欲しいのでパッチを書いてみました。
vim-dev に投げる前にもしよければレビューとか意見いただけると嬉しいです。

https://github.com/haya14busa/incsearch.vim という同等の機能を提供する拙作 Vim pluginがあり、
実は個人的にはこれで全く困ってないし気に入ってるんですが、このプラグインはVimのコマンドラインをVim scriptで模倣するという"パワー"で実装されていることもあり、いくつか対応できてない機能があったり、単に hacky すぎて気に入らないユーザがたくさんいるかと思います。
　しかしすべてのマッチをハイライトする機能自体はとてもベンリなので、ぜひVim でデフォルト対応できたらなぁと思い作りました。

パッチ: https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5

helpはまだ書いてません。

**Comment by haya14busa** [comment]
GitHubのブランチ: https://github.com/haya14busa/vim/tree/incsearch-hi-all

なおこのパッチは @itchyny さんが vim-dev に投稿してたもの[1] をベースにして、キャンセリング対応ができてなかった部分を修正したものになります。 cc/ @itchyny 

[1]: https://groups.google.com/forum/#!searchin/vim_dev/incsearch|sort:relevance/vim_dev/zdp8W-6xUzg/PrqDpP7cilIJ

**Comment by haya14busa** [comment]
その vim-dev のスレッド[1] では Bram さんは IncSearch と Search のハイライトの区別が付けば新しいオプションは必要ないという風なことをいってるかと思いますが、IncSearch/Searchのハイライトに違いが少ないcolorschemeは多々あり、また `.` とか検索して全部がハイライトされたときに文字自体が見づらくなるカラースキームなどもあるので、オプション足すのが丸いかなぁとおもって 'inchlsearch' という名前でオプションを作っています。 ("inc"search 中にインクリメンタルに 'hlsearch' と同様の方法でハイライトを行う)

[1]:https://groups.google.com/forum/#!searchin/vim_dev/incsearch%7Csort:relevance/vim_dev/zdp8W-6xUzg/PrqDpP7cilIJ

**Comment by haya14busa** [comment]
help もやっつけですが書いてみた。

```diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 56697d51d..b52f16bf3 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -4175,7 +4175,7 @@ A jump table for the options with a short description can be found at |Q_op|.
 	'highlight' option.  This uses the "Search" highlight group by
 	default.  Note that only the matching text is highlighted, any offsets
 	are not applied.
-	See also: 'incsearch' and |:match|.
+	See also: 'incsearch', 'inchlsearch' and |:match|.
 	When you get bored looking at the highlighted matches, you can turn it
 	off with |:nohlsearch|.  This does not change the option value, as
 	soon as you use a search command, the highlighting comes back.
@@ -4386,6 +4386,17 @@ A jump table for the options with a short description can be found at |Q_op|.
 	default now.  This should work fine for most people, however if you
 	have any problem with it, try using on-the-spot style.
 
+			*'inchlsearch'* *'ihls'* *'noinchlsearch'* *'noihls'*
+'inchlsearch' 'ihls'	boolean	(default off)
+			global
+			{not in Vi}
+			{not available when compiled without the
+			|+extra_search| features}
+	While typing a search command, all matched strings are highlighted.
+	It works only when both 'incsearch' and 'hlsearch' are on. The type of
+	highlighting is same as highlight of 'hlsearch' and same as highlight
+	of 'incsearch' for the current match.
+
 						*'include'* *'inc'*
 'include' 'inc'		string	(default "^\s*#\s*include")
 			global or local to buffer |global-local|
@@ -4447,7 +4458,7 @@ A jump table for the options with a short description can be found at |Q_op|.
 	match may not be found.  This is to avoid that Vim hangs while you
 	are typing the pattern.
 	The highlighting can be set with the 'i' flag in 'highlight'.
-	See also: 'hlsearch'.
+	See also: 'hlsearch' and 'inchlsearch'.
 	CTRL-L can be used to add one character from after the current match
 	to the command line.  If 'ignorecase' and 'smartcase' are set and the
 	command line has no uppercase characters, the added character is
```

**Comment by k-takata** [comment]
まだ試していませんが、意外と少ない変更で対応できるんですね。

とりあえずコーディングスタイルに関する指摘をいくつか。

https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5/9ff68be963364039bf8cca1900734e14352672da#file-inchlsearch-patch-L51
空行を削除していますが、残したままの方が良いかと。

https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5/9ff68be963364039bf8cca1900734e14352672da#file-inchlsearch-patch-L63
`if` の `{` は次の行に移動してください。ただし、`{}` の中身が1行の時は `{}` は付けないでください。（常に `{}` を付けるようにした方が安全でいいと思うのですが、そういうスタイルですので…。）
他の箇所も同様。

https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5/9ff68be963364039bf8cca1900734e14352672da#file-inchlsearch-patch-L97
変数宣言はブロックの先頭に移動してください。VCでコンパイルが通りません。

https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5/9ff68be963364039bf8cca1900734e14352672da#file-inchlsearch-patch-L187
ここの `#` と `ifdef` の間のスペースは不要だと思います。`#if` 等がネストしている場合には、その階層分だけスペースを入れます。その下の数カ所も同様。
（参考にした `restore_search_patterns()` のインデントが間違っているようですね。一緒に直してしまってもよいと思います。）

https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5/9ff68be963364039bf8cca1900734e14352672da#file-inchlsearch-patch-L213
余計なファイルが混入？

ヘルプについては、オプションを足したときは、quickref.txt 内のオプションリストも更新が必要です。
あとは、runtime/optwin.vim も更新しておいた方が本当はいいのですが、まあ、Bramに任せてもいいでしょう。

**Comment by haya14busa** [comment]
ありがとうございます！！！直しました。ifdef そういう規約だったんですね。知らなかった...

自分の vim のリポジトリにp-r https://github.com/haya14busa/vim/pull/5 して CI チェックしてみています

**Comment by k-takata** [comment]
https://gist.github.com/haya14busa/8c1f33aa9bf16188bc4442a8b78d30a5/09c83b3736b909b7beaa8cda038b9232745cc620#file-inchlsearch-patch-L109
`{` の位置、修正をお願いします。

**Comment by haya14busa** [comment]
oh, 見落としてました 🙇  ありがとうございます。 Fixed

**Comment by mattn** [comment]
pull-req 作成時にアニメーション gif 入れていきましょう。

**Comment by haya14busa** [comment]
GIF撮りました :muscle: :bird:
![peek 2017-10-09 11-01](https://user-images.githubusercontent.com/3797062/31323333-50380816-ace1-11e7-95ed-5165a460ee61.gif)

**Comment by haya14busa** [comment]
投げました ✨  https://github.com/vim/vim/pull/2198

**Comment by h-east** [comment]
@haya14busa 👍 。ご存知だと思いますが、highlightのtestは`screenattr()`を使えば可能っちゃぁ可能です。
参考になるのはどれだろう。testdir/test_match.vim とか test_matchadd_conceal_utf8.vim かなぁ。

**Comment by haya14busa** [comment]
普通のハイライトのテストはできますがインクリメンタルサーチ中のハイライトをテストって出来ますかね……？

あぁーマッピング作ってそこから呼べばもしや可能…？

**Comment by h-east** [comment]
```vim
function! GetScreenAttr(row, col)
    let g:Check_RowColAttr = [a:row, a:col, screenattr(a:row, a:col)]
    return ''
endfunction
```
こんな感じの関数を定義しておいて
```
/set<C-R>=GetScreenAttr(2,1)<CR>
```
とかして、後で`g:Check_RowColAttr`を確認すればイケそう

**Comment by haya14busa** [comment]
んーどうやら今回のパッチだとやはりテストムズカシそう

1. 1文字打つ
2. last regex pattern を保存
3. 検索 -> last regex pattern が入力中のテキストに
4. update_screen  -> 3 で一時的にセットされたregexでハイライト
5. 2 で保存していた regex を restore

していて、テストなどVim script から呼んだとき 4 の update_screen で redraw, スクリーンが再描画するとは限らない。

つまり `<C-r>=` などで関数を呼んだときにハイライトがスクリーンに反映してない。
では、その呼んだ関数で `redraw` すればいいという話になるけど、
5で保存していた regex にすでにrestoreされているので、ハイライトされるパターンは入力中の文字列じゃなくて、最後の検索パターン. => テストできない...

なにかいいアイデアありますかねぇ

**Comment by ichizok** [comment]
`term_start()` で Vim を動かして確認できないでしょうか？（GUI はテストできませんが）
test_popup.vim の `Test_popup_and_window_resize()` はその方法でやりました。

**Comment by haya14busa** [comment]
それはなかなか(変態的で)面白いアイデアですね...! 
Vim 内で Vim 起動してテストできると他のところでも使えるところありそう.

**Comment by h-east** [comment]
@haya14busa `last regex pattern`がよく分からないです。普通に `/set`と入力した時のhighlight状態を数カ所`\<C-R>=GetScreenAttr(～)`で記録しておいて後で確認すればいいと思うのですが、私何か勘違いしてますか？
test時は`redraw`必要なのは理解してます。

**Comment by haya14busa** [comment]
今回のパッチの実装ではいわゆる(?) `@/` を一時的に上書きして hlsearch させることによってすべてのマッチをハイライトしています。この上書き&リストアは一文字入力するごとに行われるので `/set` の `t` を打って次の文字を打つ時点での `@/` の内容は `set` ではなく以前の検索パターンになっています。
なので関数内でredrawしても以前の検索パターンの状態でハイライトされてしまうということです。

**Comment by h-east** [comment]
なるほど。う～む。。。新たにhighlightグループ作るのも煩雑になるしなぁ。。

**Comment by haya14busa** [comment]
`term_start()` でテスト書けました...! :sparkles: 
https://github.com/vim/vim/pull/2198/commits/a552edd17e8601c124d4e7d20179384d52bfad22

ちなみに IncSeach のハイライトもredrawでテストしてたときには消えてたっぽいので別のハイライトグループというのもそうですが、そもそもハイライトの仕方を考えないとダメそうかも...?(この辺は勘で言っています)

**Comment by tyru** [comment]
おめでとうございます！ @haya14busa ++ >[8.0.1238](https://github.com/vim/vim/commit/2e51d9a0972080b087d566608472928d5b7b35d7)

**Comment by haya14busa** [comment]
やりましたー! :muscle: :bird: :sparkles:

みなさまご協力ありがとうございましたっ！！
