### ISSUE TITLE
LUAオプション付きビルド時のmingwでのパス指定について

### ISSUE THREAD

**Issue by bamchoh** [vim-jp/issues#1105]
## 質問・報告の内容

mingw32を用いて、以下の通りにビルドしてみましたところ、lua.hがないと言われました。
https://github.com/vim/vim/blob/master/src/INSTALLpc.txt#L580

LUAオプションの値を `/c/projects/lua53` に変えたところ、ビルドが出来ました。これは私の環境のせいなのでしょうか？それとも、記載間違いなのでしょうか？

`LUA=c:\\projects\\lua53` のように `\` をエスケープするような書き方をしてもビルドは成功するようです。vimというよりmingwの動作仕様のようにも思えるのですが、そのあたりの知識が乏しく、申し訳ないですが、ご教授いただけないでしょうか。

## Vimのバージョン

8.0.1176

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 64bit (10.0.15063)

## 使用している or 関係していそうなプラグイン

* mingw32-make (4.2.1)
* lua (5.3)

## その他

* 特になし

**Comment by bamchoh** [comment]
質問内容にも記載している通り、\ の替わりに / を使用することで解決しておりますので、クローズします。すいませんでした。

**Comment by k-takata** [comment]
bash上から実行するか、cmd.exe上から実行するかで、異なってくると思います。（INSTALLpc.txtにはそのことは書いていないのですが…。）
bashでは `\` はエスケープとして働きますので、2重にするか、`'` でくくるか、`/` に置き換えるかのいずれかが必要です。
両方で使えるようにするには `LUA=c:/projects/lua53` のように `/` を使うように書き直すのが良いかもしれません。

**Comment by k-takata** [comment]
改善の余地ありということで、reopenしておきます。

**Comment by k-takata** [comment]
最新版の INSTALLpc.txt にいろいろと間違いが見つかったので、まとめて投げておきました。
https://groups.google.com/d/msg/vim_dev/2x1bJqOYKEY/KrHdHmnJAgAJ

**Comment by k-takata** [comment]
vim-jp.org に記載しているビルド手順のページも更新。
http://vim-jp.org/docs/build_windows_mingw.html

**Comment by k-takata** [comment]
Fixed by 8.0.1268: https://github.com/vim/vim/commit/3bf8c3c38ff0d24047e2f2979c07a349fb89e557
