### ISSUE TITLE
Win32: 異体字が正しく表示されない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1106]
## 質問・報告の内容

Windows 10 にて IVS ([異体字セレクタ](https://ja.wikipedia.org/wiki/%E7%95%B0%E4%BD%93%E5%AD%97%E3%82%BB%E3%83%AC%E3%82%AF%E3%82%BF)) を使った異体字が正しく表示されません。

サンプルテキスト (ivs_test.txt):

```
葛 (U+845B)
葛󠄀 (U+845B E0100)
葛󠄁 (U+845B E0101)
```

実行方法:

```
gvim -N -u NONE -i NONE --cmd "set enc=utf-8 gfn=MS_Gothic:h20" ivs_test.txt
```

表示結果:

<img width="179" alt="ivs_before_fix" src="https://user-images.githubusercontent.com/840186/31509906-085fe182-afbe-11e7-89f8-8fc818b629db.png">
字形が3つとも変化が無い上に、IVSが四角い枠で表示されてしまっています。<br/><br/>

パッチ:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d71a28fb36b97a57c58d5df31ca475b8acbab680/win32-fix-composing-chars.patch?at=default&fileviewer=file-view-default

パッチ適用後:

<img width="182" alt="ivs_after_fix" src="https://user-images.githubusercontent.com/840186/31509933-1decff58-afbe-11e7-85ad-5e3c6c9133ac.png">
2つめの字形が残りと違うことが確認できます。

## Vimのバージョン

8.0.1185

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.15063)

## 関連パッチ

#293 (7.3.781)

**Comment by k-takata** [comment]
Windows版の文字表示は、合成文字が見つかると、ベースの文字の上に合成文字を重ね合わせて描画する処理になっていました。それをまとめて1回で描画するように変更しています。

**Comment by k-takata** [comment]
よく考えたら、今までは IVS だけでなく、合成用濁点・半濁点もダメでした。

```
が (U+304C)
が (U+304B 3099)
か゚ (U+304B 309A)

ば (U+3070)
ば (U+306F 3099)
ぱ (U+3071)
ぱ (U+306F 309A)
```

**Comment by mattn** [comment]
ちなみに一番下で `ga` した時の表示もおかしい気がする。

![異体](https://go-gyazo.appspot.com/f5a6520e2582abf9.png)

**Comment by k-takata** [comment]
ga は合成用文字もばらして1文字ずつ表示させますから、ある意味仕方がない気がしますね。
対策するとしたら、合成用文字は表示しないようにするか、1個または2個の半角スペースあるいは全角スペースと合成させて表示するか…。

**Comment by mattn** [comment]
あ、いえ。ここ、こうじゃないかなと。

![異体](https://go-gyazo.appspot.com/e95394ff5179c5d9.png)

**Comment by k-takata** [comment]
合成用文字をつけるべきものではないものにつけているせいで、レンダラーの特性上、表示位置がずれているだけだと思います。GDIとDirectWriteを切り替えたり、フォントを変更すると表示が変わったりしますし。
半角スペースあるいは全角スペースと合成させてもあまりうまくいかないようです。

**Comment by k-takata** [comment]
Posted: vim/vim#2206

**Comment by k-takata** [comment]
8.0.1234
https://groups.google.com/d/topic/vim_dev/ZH9U7Tiz55Y/discussion
