### ISSUE TITLE
:terminal + GitBashで256color.pl実行後に文字化け

### ISSUE THREAD

**Issue by shiena** [vim-jp/issues#1107]
## 質問・報告の内容

1. gvimの:terminalからGit Bashを起動する
2. `256color.pl`を実行する
3. `ls`で日本語が文字化けする

Git for Windows付属のminttyでは文字化けは起きませんでした。

![image](https://user-images.githubusercontent.com/1295639/31547295-bfac87ac-b061-11e7-93eb-32ac5b434222.png)

![image](https://user-images.githubusercontent.com/1295639/31547304-c7f6b658-b061-11e7-8f3c-a868c185855a.png)

## Vimのバージョン

8.0.1187

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 64bit (10.0.15063.674)

## 使用している or 関係していそうなプラグイン

特になし

## その他

:terminalで使ったバージョンです。

* Git for Windows 2.14.2.2
* [256color.pl](https://gist.github.com/hSATAC/1095100)

**Comment by k-takata** [comment]
Explorer から bash.exe を実行して試してみたところ、同じ挙動になりましたので、Vim側の問題ではなさそうです。

**Comment by mattn** [comment]
256色のエスケープシーケンスを解釈しない termcap ならそれを間違って解釈してしまって文字化けが発生するという事ならあり得そう。

**Comment by shiena** [comment]
`256color.pl`の出力するエスケープシーケンスを1つずつ確認して、以下が原因と分かりました。

```
perl -e 'print "\x1b[11m\n"'
```

11～19はAlternate fontで何故か11の時だけフォントが変わってしまいます。
この後、Primary(default) fontに切り替える以下のエスケープシーケンスで元に戻せました。

```
perl -e 'print "\x1b[10m\n"'
```

なのでvimの問題ではありませんでした。

**Comment by mattn** [comment]
解析ありがとうございます。また何かありましたらお願いします。
