### ISSUE TITLE
:fileでファイル名を変更した時にタブページのラベルの名前が更新されない

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#1110]
## 質問・報告の内容

tablineが表示されている時、```:file {name}```でファイル名を変更してもタブページのラベルの名前が更新されません。

sample1.vim:
```vim
set showtabline=2
call feedkeys(":file a.txt\<CR>")
```

vim起動:
```
vim --clean -S sample1.vim
```

Ctrl-lを押下すると更新されます。
更新されてない状態で```:echo bufname('')```を実行すると新しいファイル名がメッセージに表示されます。

更新されてない状態でノーマルモードでggとGでスクロールしても更新されるのですが、
```winheight(0)```が5以上で```winheight(0) * 2 - 3 < line('$')```が真の場合にのみ更新されます。
ただし```winheight(0)```が4を返す場合は```line('$')```が```winheight(0) + 1```以上あれば更新されます。
```winheight(0)```が4未満を返すケースは試してないです。

例えば、```winheight(0)```が20で```line('$')```が38以上の状態であれば、```:file a.txt```した後にggやGすると更新されます。
```line('$')```が37以下だとggとGを押下しても更新されません。

sample2.vim:
```vim
set showtabline=2
" 更新される
" execute 'normal! ' . (winheight(0) * 2 - 3) . 'o'
" 更新されない
execute 'normal! ' . (winheight(0) * 2 - 4) . 'o'
call feedkeys(":file a.txt\<CR>gg")
```

```
vim --clean -S sample2.vim
```

tablineを再描画すればよいだけなのか分かりませんが以下のpatchで即時更新されるようになりました。
Linux環境でのみpatchの動作確認をしました。

```diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 60f47bbd2..0c71d2076 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -3002,6 +3002,11 @@ ex_file(exarg_T *eap)
     /* print full file name if :cd used */
     if (!shortmess(SHM_FILEINFO))
 	fileinfo(FALSE, FALSE, eap->forceit);
+
+#ifdef FEAT_GUI
+    if (!gui.in_use)
+#endif
+	update_screen(REDRAW_TOP);
 }

 /*
```

よろしくお願い致します。

## Vimのバージョン

- vim 8.0.1214 (Linux)
- vim 8.0.1213 (vim-win32-installerのgvim_8.0.1213_x86.zip)

再現するのはvimのみです。gvim(GTK2)では問題ありません。

## OSの種類/ディストリ/バージョン

* Linux Debian stretch 9.2 64bit
* Windows 7 Home premium 32bit

**Comment by h-east** [comment]
@norio13 bug report&patch お疲れ様です。
提示のpatchで改善することを確認しました。そのpatchでも良いと思いますが、tablineを描画するのが目的であれば、`redraw_tabline = TRUE`が良いのではないかと思いました。いかがでしょうか？

```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 60f47bb..65bdd5a 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -3002,6 +3002,8 @@ ex_file(exarg_T *eap)
     /* print full file name if :cd used */
     if (!shortmess(SHM_FILEINFO))
 	fileinfo(FALSE, FALSE, eap->forceit);
+
+    redraw_tabline = TRUE;
 }
 
 /*
```

**Comment by h-east** [comment]
@norio13 返事をもらう前に私のpatchをvim_devに送らせて頂きました。すんません。
https://groups.google.com/d/msg/vim_dev/Z8l7aecz8b4/yLpMd9kmCAAJ

**Comment by h-east** [comment]
8.0.1216 で修正されました。
https://github.com/vim/vim/commit/6ce650480844bfaa5410874416b4a2e15f40b870

@norio13 Thanks!

**Comment by norio13** [comment]
@h-east thanks!
