### ISSUE TITLE
検索コマンドラインが空の状態での Ctrl-G/T の挙動があやしい

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#1112]
## 質問・報告の内容

問題1: 空の状態で `<C-g>` したあと `<Esc>`  するとIncSearchのハイライトが残る https://github.com/vim/vim/issues/2267
問題2: 空の状態で `<C-g>` したあと `<Esc>`  するとカーソル位置がもとの検索位置に戻らない。
(ふつうに文字を入力して`<Esc>`した場合はちゃんともとの位置にもどる.

問題(?) 3: ヘルプみるとそもそもコマンドラインが空の状態での ctrl-g/t の仕様については触れられてないようにみえる。これそもそも unexpected な挙動ではないか? 
(unexpected に最後の検索パターンで移動してしまってる)

## Vimのバージョン

8.0.1240 (8.0.1238 #1104 と関連した問題かと見せかけて、1238以前でも再現します)

**Comment by h-east** [comment]
8.0.1250
https://github.com/vim/vim/commit/f8f8b2eadbaf3090fcfccbab560de5dbd501833d

@haya14busa これで見つかっている問題は全部直った？

**Comment by haya14busa** [comment]
確認したところぜんぶ直ってました！ご協力ありがとうございました！
