### ISSUE TITLE
undotree() の返すツリー上の現在位置がおかしい場合がある

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#1113]
## 質問・報告の内容

`undotree()` 関数を使うとアンドゥに関する諸情報が取得できます。

>	  "seq_last"	使用されたアンドゥシーケンス番号の最大値。
>	  "seq_cur"	アンドゥツリーの現在のシーケンス番号。いくつか
>			の変更がアンドゥされた状態だと "seq_last" と違
>			う値になる。
>	  "time_cur"	最後に |:earlier| 系のコマンドが使われた時間。
>			読みやすい形式に変換するには |strftime()| を使
>			う。
>	  "save_last"	最後にファイルが保存された番号。保存がまだなら
>			ゼロになる。
>	  "save_cur"	アンドゥツリー内の現在位置の番号。
>	  "synced"	最後のアンドゥブロックが同期されていれば非ゼ
>			ロ。これはユーザーからの入力を待機しているとき
>			に起こる。|undo-blocks| 参照。
>	  "entries"	アンドゥブロックの情報を表す辞書のリスト。

ですが、このうちアンドゥツリー上の現在のシーケンス番号 `seq_cur` が場合によっては正しくない位置を指しているように思います。再現手順は以下の通りです。

1. 新しいバッファを開く `:new`

* `undotree().seq_cur == 0`
```
  
```

2. 何か入力 `:normal! afoo`

* `undotree().seq_cur == 1`
```
foo
```

3.  さらに何か入力 `:normal! abar`

* `undotree().seq_cur == 2`
```
foobar
```

4. アンドゥ `:normal! u`

* `undotree().seq_cur == 1`
```
foo
```

5. 何か入力 `:normal! abaz`

* `undotree().seq_cur == 3`
```
foobaz
```

6. アンドゥ `:normal! u`

* `undotree().seq_cur == 2` <- !!!
```
foo
```

---

六番目の手順の終了時の `undotree().seq_cur` に期待するのは `1` だと思います。何か勘違いをしていたらすいません。

## Vimのバージョン

8.0.1257

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit

## 使用している or 関係していそうなプラグイン

いくつかあるアンドゥにかかわるプラグインがなぜ動いているのか疑問に思ったので調べたところ [mbbill/undotree](https://github.com/mbbill/undotree) のコードにワークアラウンドに関するコメントがありました。

[mbbill/undotree/autoload/undotree.vim](https://github.com/mbbill/undotree/blob/cdbb9022b8972d3e156b8d60af33bf795625b058/autoload/undotree.vim#L787)

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/undotree.diff
バグのようですね。これでどうでしょうか？

**Comment by machakann** [comment]
ありがとうございます。しばらく試してみましたが問題なく、期待通りの動作をしているようです。

**Comment by machakann** [comment]
すいません、以下の場合におかしいようです。

1. `:new`
2. `:normal! Aabc`
3. `:undo`
4. `:normal! Adef`
5. `:undo`

手順5の終了後に期待する `undotree().seq_cur` は `0` だと思うのですが、 `1` が返ります。

**Comment by ichizok** [comment]
@machakann  確認ありがとうございます。
パッチをアップデートしたので、もう一度試してもらえますか？

**Comment by machakann** [comment]
ありがとうございます、すべて期待通りの動作でした。

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2319
投げました。

**Comment by ichizok** [comment]
8.0.1290
https://github.com/vim/vim/commit/80eaddd3a0bc47cb14168964678420cfe03a2502
