### ISSUE TITLE
macvimの:terminalでファイル名の濁点の位置がおかしい

### ISSUE THREAD

**Issue by shiena** [vim-jp/issues#1114]
## 質問・報告の内容

macvimの:terminalでUTF-8-MACのファイルを表示すると濁点の位置がおかしいです。
下のキャプチャの上はUTF-8-MACの`ユーザ登録`を表示したもの、下はUTF-8の`ユーザ登録`を表示したものです。

<img width="718" alt="macvim-terminal" src="https://user-images.githubusercontent.com/1295639/32495322-8f39a842-c408-11e7-8ef6-b400c54e2c3b.png">

Terminal.appで起動したvimの:terminalで同じファイルを表示すると濁点は正しい位置でした。

<img width="585" alt="termina-vim" src="https://user-images.githubusercontent.com/1295639/32495330-98fc7346-c408-11e7-8da4-b4bad789acc4.png">

## Vimのバージョン

8.0.1272

## OSの種類/ディストリ/バージョン

*   macOS High Sierra

## 使用している or 関係していそうなプラグイン

特になし

## その他

特になし

**Comment by shiena** [comment]
他に濁点がおかしくなる場合がありました。
以下の左下はlsの結果を開いたもの、右下はNetrwで、:terminalでなくても`UTF-8-MAC`の表示がおかしいようです。

<img width="733" alt="macvim-netrw" src="https://user-images.githubusercontent.com/1295639/32528904-caafc562-c478-11e7-98de-996aed9f3e69.png">

**Comment by ichizok** [comment]
MacVim の Core Text レンダラのバグですね。

**Comment by mattn** [comment]
@splhack Can you handle this issue?

**Comment by ichizok** [comment]
https://github.com/macvim-dev/macvim/commit/1496167590507aa8b04b099828b90dafe1e14615 で直ったと思います。

**Comment by shiena** [comment]
確認が遅くなってしまいすみません。
以下のバイナリで濁点が正しく表示できました。
ありがとうございます。
https://github.com/macvim-dev/macvim/releases/tag/snapshot-149
