### ISSUE TITLE
TerminalOpen イベントが欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1116]
http://secret-garden.hatenablog.com/entry/2017/11/14/113127

termkey は個人差がありそうなので対応が難しいですが、filetype はなんとかできるかも？

**Comment by Shougo** [comment]
> termkey は個人差がありそうなので対応が難しいですが、filetype はなんとかできるかも？

filetype に関しては、terminal を内部的に使うプラグイン側が独自のfiletypeを設定できるように意図的にやっているような気はします。

とはいえ、バッファが端末のときの hook がやりづらいというのは確かに思います。
CmdWinEnter のように専用の hook を作るべきかもしれません。

例: TermEnter, TermLeave

**Comment by mattn** [comment]
ここに書くのは良く無いかもだけど、ドキュメントに

```
These are defined like any mapping, but apply only when typing keys that are
sent to the job running in the terminal.  For example, to make Escape switch
to Terminal-Normal mode: >
   tnoremap <Esc> <C-W>N
```
と書かれていて、ちょっとモニョる。このマップはジョブに投げる例じゃないのでふさわしくない。

**Comment by mattn** [comment]
lingr でのヒアリングの結果、terminal はファイルではないし、syntax の適用される対象でもないので、TerminalOpen の様な autocommand を用意するのが良いのではという事に。

**Comment by mattn** [comment]
意見交換 https://github.com/vim/vim/issues/2422

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2484

**Comment by mattn** [comment]
[patch 8.0.1596](https://github.com/vim/vim/commit/b852c3e64d319d6ec47dd780c8654ae095e1d8c2)
