### ISSUE TITLE
端末機能で起動したzshにクリップボードから貼り付けると~が入ったり最後の文字が大文字になったりする

### ISSUE THREAD

**Issue by itchyny** [vim-jp/issues#1117]
## 質問・報告の内容
- `echo hello` をクリップボードに入れておく
- `:terminal` で `zsh` を起動
- クリップボード貼り付け
- `echo hello~` となる
- `bindkey -v` とする
- クリップボード貼り付け
- `echo hellO` となる

<img src=https://user-images.githubusercontent.com/375258/32777341-242a6836-c979-11e7-93c4-219241f8f57e.gif>

## Vimのバージョン

8.0.1290

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

* macOS Sierra
* zsh 5.4.2
* zshrcは空です
* Terminal.app (iTerm2でも再現する)

## 使用している or 関係していそうなプラグイン

なし

## その他
- 貼り付けてすぐにenterを押すとhelloと表示されます (正常に見える)
- `:terminal bash` on Vim on zsh on Terminal.app では再現しません。zshと相性が悪い？

**Comment by hattya** [comment]
`~` が入るのは Bracketed Paste Mode に対応した端末エミュレーターならどれでも再現できそうです。

[RLogin](http://nanno.dip.jp/softlib/man/rlogin/) で Linux に SSH 接続して試してみたら再現しました。

**Comment by hattya** [comment]
`:terminal zsh` で起動後、`unset zle_bracketed_paste` とすれば `~` は入らなくなりますが…。

**Comment by itchyny** [comment]
再現確認ありがとうございます。以下の設定でひとまず運用しようと思います。
```sh
if ! [ -z "$VIM" ]; then
  unset zle_bracketed_paste
fi
```

**Comment by ichizok** [comment]
`CSI [201~` の送信タイミングがおかしいようです。
ペースト内容の最後に付加されるべきところ、ペースト後のユーザ入力と一緒に送信され、echo back で分断されて単なる `~` になっていました。

```
in << CSI [200~ echo hello
out>> echo hello
in << CSI [201~
out>> ~
```

https://github.com/vim/vim/compare/master...ichizok:fix/terminal-bracketed-paste.diff

**Comment by itchyny** [comment]
ありがとうございます。パッチをあてて問題直っていることを確認しました。すごい。

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2341
投げました。

**Comment by ichizok** [comment]
8.0.1299
https://github.com/vim/vim/commit/a42ad57e481d6ed9c34c80c99bd0512d4660515b

**Comment by itchyny** [comment]
ありがとうございました！
