### ISSUE TITLE
XIM/IME が使えない場合でも iminsert=2 は設定できるべき。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1118]
現状は XIM/IME が使えない CUI バージョンは iminsert=2 が設定できません。
しかし imactivatefunc や imstatusfunc が入った今では、外部プログラムを使う事であたかも XIM/IME があったかも？という動作にする事が出来ます。
なので XIM/IME が無い場合でも iminsert=2 は設定できるべきと考えました。

**Comment by mattn** [comment]
https://gist.github.com/35526ec896b3baa9b11e4f78fa2755fb

```vim
scriptencoding utf-8

let s:active = 0

function! IM_activatefunc(active)
  if a:active
    set statusline=IMEおん～
  else
    set statusline=IMEおふ～
  endif
  let s:active = a:active
endfunction

function! IM_statusfunc()
  return s:active
endfunction

set imactivatefunc=IM_activatefunc
set imstatusfunc=IM_statusfunc
set iminsert=2
set laststatus=2
```

```
$ vim -u imf.vim
```

こんな感じで CUI であっても疑似 IME を作る事が出来ます。

**Comment by tyru** [comment]
あれ、すでにパッチ送ったんですか？ >status/patched

**Comment by k-takata** [comment]
送った場合は、status/sent patchです。

**Comment by mattn** [comment]
Bram は試さない（試せない？）オプションなので、しばらくランニングさせて下さい。

**Comment by mattn** [comment]
出しました。 https://github.com/vim/vim/pull/2349

**Comment by mattn** [comment]
[patch 8.0.1336](https://github.com/vim/vim/commit/6315a9ae924d2104b61d1667ea71af3ac7cf48fa)
