### ISSUE TITLE
Windows の :terminal で環境変数 VIM_SERVERNAME が設定されない。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1119]
ドキュメントにある通り、Unix のみ幾らかの環境変数がエクスポートされます(See `:help terminal-unix`)が、VIM_SERVERNAME に関しては Windows でも使いたい。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2360

**Comment by h-east** [comment]
8.0.1330 :+1:
https://github.com/vim/vim/commit/52dbb5ea7fde4a77178bc59e2383ca40df503812
