### ISSUE TITLE
カレントディレクトリのリンクが常に解決される

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#112]
これは仕様かもしれませんが、不便なこともあるので登録します。
例えば、私は ~/.vim を別の場所へのシンボリックリンクにしているのですが、この状態で、

``` vim
:cd ~/.vim
:cd ..
```

とした場合、最初の `:cd` でリンクが解決されて別の場所へ移動してしまい、`..` でホームディレクトリへ戻れません。
これは同一ファイルを別バッファで編集しないようにする措置なのかもしれませんが、一般的なカレントディレクトリの概念からすると明らかに不自然です。

**Comment by mattn** [comment]
> 同一ファイルを別バッファで編集しないようにする措置なのかもしれませんが

その通り。

確か、シンボリックリンクで無限ループが貼れてハングに陥るので、それの対応でこうなってたと記憶してます。(けっこう曖昧)

**Comment by koron** [comment]
別の解決策が提案されない場合は、仕様として飲むしかなさそう、かな?

**Comment by thinca** [comment]
うーん、よく考えずに適当言いますが、そもそもにして、
同じファイルを別のバッファで編集できてしまう場合の問題点は何でしょうか?

また、カレントディレクトリだけでなく編集するファイルのリンクを辿られてしまうと困るケースは他にもあって、
例えば私の作った [localrc.vim](https://github.com/thinca/vim-localrc) なんかは
ファイルの上位パスを見ていくので場所によって意味が変わってしまいます。

**Comment by ynkdir** [comment]
getcwd()を使ってるからですね。

**Comment by h-east** [comment]
> getcwd()を使ってるからですね。

特に反論ないようなので閉じます。

**Comment by koron** [comment]
> 同じファイルを別のバッファで編集できてしまう場合の問題点は何でしょうか?

Vim って、1つのファイルは1つのバッファにマップする、みたいな説明してませんでしたっけ?
またこれは結構なVimの基礎構造に関わる部分でもあります。
よってこれを直した場合は影響はかなり大きいと考えなければならないでしょう。

シンボリックリンクを遡れるようにすることは、果たしてそこまでしてもやるべき内容でしょうか?
私はそうは考えません。

よってこの issue はしばらく経過観察した後に backlog から wontfix に振り替えます。
