### ISSUE TITLE
writefile([...], '/dev/stderr) すると E667: Fsync failed の例外が飛ぶ

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#1121]
## 質問・報告の内容

```vim
:call writefile(['hi!'], '/dev/stderr')
```

## Vimのバージョン

8.0.1333

bad commit は patch 8.0.1305 https://github.com/vim/vim/commit/7567d0b115e332f61a9f390aaccdf7825b891227

## OSの種類/ディストリ/バージョン
* Ubuntu 17.04

## 使用している or 関係していそうなプラグイン

vim-vimlparser のスクリプトで /dev/stderr に writefile することでエラーを表示してたけど v8.0.1305 以降にするとこれが動かなくなる

https://github.com/vim-jp/vim-vimlparser/blob/8c63d1a2bdf8f15960bfb5a5729c49cab319ea8f/js/jscompiler.vim#L907

## その他

v8.0.1305 以前では動いてたので動いてくれるとうれしい

**Comment by mattn** [comment]
https://gist.github.com/mattn/77b1478b48ce7c84ac8694d2e623d431

通常のファイルのみ fsync する様にしました。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2373

**Comment by haya14busa** [comment]
ちょっぱやすぎる！mattn さん ++

**Comment by mattn** [comment]
[8.0.1335](https://github.com/vim/vim/commit/291a9d15ed1eb1094edc8ad6dda00a6da3bd7072)

無視する形になりました。
