### ISSUE TITLE
WindowsのVimにおいて、DLL関数の呼び出し規約はどうなっているのか

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#1122]
## 質問・報告の内容

__経緯__

私のWindows環境にて、以下のようなlibcallnr()で落ちましました。

> echo libcallnr('User32.dll', 'IsZoomed', v:windowid)

libcallnr関数を調べていくと、`GetProcAddress()`の戻り値を`MYINTPROCINT`でキャストしています。その時に関数呼び出し規約が`__cdecl `だったために落ちてしまいました。

> os_mswin.c 857行目付近
> typedef int (*MYINTPROCINT)(int);

この型定義に`__stdcall`を明示的に付与したらlibcallnr()が落ちることなく動作しました。

__質問__

WindowsのVimにおいて、`libcall`もしくは`libcallnr`のDLL関数の呼び出し規約はどうなっているのか。ビルド環境依存に任せてしまっている感じなのでしょうか？

以上、宜しくお願い致します。

## Vimのバージョン

8.0.1333

## OSの種類/ディストリ/バージョン

*   Windows 

## 使用している or 関係していそうなプラグイン

なし

## その他

なし

**Comment by mattn** [comment]
呼び出し規約は C calling conversion です。OS は何ビットですか？Vim が使っている型は int なので 32bit です。かたや渡そうとされているのはウィンドウハンドルで 64bit OS であれば 64bit です。

libcall を使って 64bit の値を渡すには、文字列化して渡すしかありません。例えば `sprintf("%x", ptr)` といった感じで渡し、受け取り側で `sscanf` するなど。

**Comment by rbtnn** [comment]
64-bit operating system, x64-based processor
Windows 10 Pro
です。

**Comment by rbtnn** [comment]
> 呼び出し規約は C calling conversion です。

`__cdecl` ＝ `C calling conversion`が頭の中で紐づきませんでした。
Helpにも書いてありますね。

> libcall を使って 64bit の値を渡すには、文字列化して渡すしかありません。例えば sprintf("%x", ptr) といった感じで渡し、受け取り側で sscanf するなど。

これはC側の話ですよね？ Vim script側では可能なのでしょうか？

**Comment by mattn** [comment]
Vim script の number は(最近は) 64bit なのですが、libcall を呼び出した時点でキャストされてしまいます。

**Comment by mattn** [comment]
IsZoomwin を呼び出すのであれば、IsZoomwin を呼び出す dll を自作するしかないという意味でした。

**Comment by rbtnn** [comment]
> IsZoomwin を呼び出すのであれば、IsZoomwin を呼び出す dll を自作するしかないという意味でした。

なるほど。理解しました。

ありがとうございます。
