### ISSUE TITLE
vim.exe で Shift-Insert でペーストできない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1123]
Pasting with Shift-Insert in Windows console Vim
https://groups.google.com/d/topic/vim_use/G1hB7FJbyAo/discussion

7.3.46 は Shift-Insert でクリップボードからペーストできるが、7.4 以降はできないとの報告が上がっています。
#189 等の修正が影響していないか気になるところです。

**Comment by mattn** [comment]
壊れたのは https://github.com/vim-jp/issues/issues/681 こっちでした。

https://groups.google.com/forum/#!topic/vim_dev/Gu7pDIjS1UE/discussion

最新ソースで引用すると

https://github.com/vim/vim/blob/bdb8139098d170ede2bc79dd4f62e4ed5e778d3e/src/os_win32.c#L1818-L1823

```c
		if (ch2 != NUL)
		{
		    typeahead[typeaheadlen + n] = 3;
		    typeahead[typeaheadlen + n + 1] = (char_u)ch2;
		    n += 2;
		}
```

Patch 7.4.852  で入ったこのコードですが、K_NUL が先行するケースが考慮されてなかった様です。K_NUL が先行するのは、ANSI キーという1文字キーの事です。

https://github.com/vim/vim/blob/bdb8139098d170ede2bc79dd4f62e4ed5e778d3e/src/os_win32.c#L1006-L1007

```diff
diff --git a/src/os_win32.c b/src/os_win32.c
index becbeeee2..c1c297a63 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -1817,9 +1817,18 @@ mch_inchar(
 		    typeahead[typeaheadlen] = c;
 		if (ch2 != NUL)
 		{
-		    typeahead[typeaheadlen + n] = 3;
-		    typeahead[typeaheadlen + n + 1] = (char_u)ch2;
-		    n += 2;
+		    if (c == K_NUL)
+		    {
+			/* fAnsiKey */
+			typeahead[typeaheadlen + n] = (char_u)ch2;
+			n++;
+		    }
+		    else
+		    {
+			typeahead[typeaheadlen + n] = 3;
+			typeahead[typeaheadlen + n + 1] = (char_u)ch2;
+			n += 2;
+		    }
 		}
 
 		if (conv)
```
これで直ると思いますがどうでしょうか。この修正を入れても「森鷗外」は入力出来るので壊してはないと思います。

ところで cp932 で「ﾎﾔ」を入力すると getchar.c で定義してる SHIFT-Insert にマッチしてペーストになるんですね。(便利 :no_good_man: )

**Comment by mattn** [comment]
cp932 の件は類似だけど別件なので別の issue で直したい(直せるの？)

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2381

**Comment by k-takata** [comment]
報告者は 7.4 でも 7.4-1024 でもダメだと言っているので、2段階で壊れていたんですかね？

**Comment by mattn** [comment]
[patch 8.0.1371](https://github.com/vim/vim/commit/feeb4d0901c7b16958e8f02ffcdac83b605b0b43)
