### ISSUE TITLE
ファイルをドロップすると E341: 内部エラー: lalloc(0,) が発生する

### ISSUE THREAD

**Issue by higemaniya** [vim-jp/issues#1127]
## 質問・報告の内容

Windows版 gvim 64bit版 8.0.1383 (nightlyビルド) のウインドウにドラッグアンドドロップでファイルを落とすと、
E341: 内部エラー: lalloc(0,)
が表示され、ファイルを開くことができません。

32bit版では問題は発生しません。
Windows版以外は確認していません。

+kaoriya版 (8.0.0596) では問題なかったので、報告するにあたって状況をよく確認したところ、特殊な状況のようでしかもvim側の問題なのかどうかもはっきりしないのですが、一応報告させていただきます。

上記の通り、8.0.0596 では問題ありませんでしたので、nightlyビルドの中でエラーが発生するようになるバージョンを探してみたところ、
8.0.0956 : OK
8.0.0960 : NG (github.com/vim/vim-win32-installer/releases/download/v8.0.0960/gvim_8.0.0960_x64.zip)
でした。

ただ、エラーにならずにドロップできることもあって不思議に思っていたのですが、ドラッグ元のアプリに依存していることに気づきました。
具体的には、あふw (x86 v1.63) というファイラーからドラッグアンドドロップするときだけエラーになります。エクスプローラや Git Extensions といったツールなど、他のアプリケーションからのドラッグでエラーになるケースは見つけられませんでした。

私は日常的にあふwを使っていて基本的にエラーになる状況なので、こちらに報告してエラーを解消できたら嬉しいと思っているのですが、もしかしたらドラッグ元のアプリ(あふw)で解決すべき問題なのかも？と少し思っています。

参考: あふw http://akt.d.dooo.jp/akt_afxw.html

## Vimのバージョン

github.com/vim/vim-win32-installer の 8.0.0960 以降 64bit版と
特定のアプリ(あふw) との組み合わせのみで発生

## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit (10.0.16299.64)

## 使用している or 関係していそうなプラグイン

コマンドプロンプトから gvim -u NONE -N として起動して確認しました。

**Comment by higemaniya** [comment]
追加で判明したことがありますので、報告の内容を以下のように訂正します。

## 質問・報告の内容

Windows版 gvim 64bit版 8.0.1383 (nightlyビルド) のウインドウに
32bitアプリからドラッグアンドドロップでファイルを落とすと、
E341: 内部エラー: lalloc(0,)
が表示され、ファイルを開くことができません。

gvim 64bit版に64bitアプリからドロップする場合は問題は発生しません。
gvim 32bit版ではアプリが32/64によらず問題は発生しません。
Windows版以外は確認していません。

nightlyビルドの中でエラーが発生するようになるバージョンを探してみたところ、
8.0.0956 : OK
8.0.0960 : NG (github.com/vim/vim-win32-installer/releases/download/v8.0.0960/gvim_8.0.0960_x64.zip)
でした。

あふw 32bit/64bit、FileZilla 32bit/64bitでそれぞれ確認しました。

## Vimのバージョン

github.com/vim/vim-win32-installer の 8.0.0960 以降 64bit版と
32bitアプリ との組み合わせで発生

**Comment by k-takata** [comment]
#552 と同件のように思われます。残念ながら、いまだに原因が分かっていません。
vim/vim-win32-installer では、8.0.0956 までが VC2010、8.0.0960 から VC2015 でビルドしているという違いがあります。

**Comment by higemaniya** [comment]
コメントありがとうございます！
確かに同じ状況のようです。お手数をおかけしてすみません。
重複ということで閉じていただいても構いません。
