### ISSUE TITLE
readdir() が欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1128]
Vim script の glob は suffixes や wildignore の影響を受けたりいろいろと制限があり、Vim script でアプリケーションを作りたい人にとっては使い辛い物になってしまっています。アプリケーションを作りたい人が本当に欲しいのは readdir() だと思いました。

https://github.com/mattn/vim/commits/add-readdir

引数にパスを貰い、ファイルもしくはディレクトリの名前の一覧を List で返します。省略可能な第二引数で

```vim
let dirs = readdir(dir, {x->isdirectory(x)})
```

こんな感じの事も出来ます。あと

https://github.com/vim-jp/issues/issues/167

この issue にある通り、ファイル数が多い場合には中断したくなるはずなので、第二引数が -1 を返した場合は中断としました。

如何でしょうか。

* [x] 実装
* [x] テスト
* [x] ドキュメント

**Comment by thinca** [comment]
かっこよす 🎉 

```vim
let dirs = readdir(dir, {x->isdirectory(x)})
```

この例ですが、`x` は単純なディレクトリ内のアイテムの名前だと思うので、そのまま `isdirectory()` に渡すとカレントディレクトリの影響を受けてまずそうな予感がしますね。

```vim
let dirs = readdir(dir, {x->isdirectory(dir . '/' . x)})
```

こういう感じになりそう。(ちょっとだけめんどい)

**Comment by tyru** [comment]
現状どういう動きか確認できてないのですが、結果はソートされてた方がいいんじゃないでしょうか？
（例：Go の [io/ioutil.Readdir()](https://golang.org/pkg/io/ioutil/#ReadDir) はソートされてるみたいです）

**Comment by mattn** [comment]
ソートする様にしました。

**Comment by mattn** [comment]
テスト通ったら出しちゃおうかな！

※OSX 始まらないので出す

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2439

**Comment by tyru** [comment]
mattn++
ちなみに Win32API に明るくないんですが、 `*.*` ってドット始まりのファイルも列挙されますでしょうか？

**Comment by tyru** [comment]
自分の期待としては全てのファイルが列挙されてほしいです。

**Comment by Shougo** [comment]
この関数を内部的に使えば delete('rf') のバグも直せると思うのですが、それはどうでしょうか。
現在の delete('rf') は内部的に glob() を使っていて、一部のファイルを削除できないなど問題が多いです。

**Comment by thinca** [comment]
Bram さんから返事来てますね。

`glob()` と被るので、`glob({expr}, {dict})` と言う新しい形式作って `{dict}` にオプション渡せるようにしようって言ってますね。ただ肝心の「`glob()` だとノイズが多くて使いづらい」というのが伝わっていない感じもします…。filter にしか注目してなさそう。
目的が達成できるなら `glob()` に統合でも良さそうですが、そうなると更にオプションが必要そうです。

**Comment by thinca** [comment]
本筋と関係ないけど、ラムダ式書く時は `->` の前後にスペースを入れるのが Bram さんの公式見解っぽい (スペースがないと `C` のコードに見えるとのこと)。

**Comment by k-takata** [comment]
8.1.1120: https://github.com/vim/vim/commit/543c9b1921d7605498b54afdef518e312f1b4515
