### ISSUE TITLE
UNCパス上のファイルを開くとかなり遅い

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#113]
昔 vim_dev で ACL がなんちゃらって話があったけど、それが影響してるんかなーとか思いながら調べてません。

**Comment by koron** [comment]
確かに。私は意図的にUNC越しには使わないようにしている。

SambaのACL実装とかと絡んでたりして。Cygwinがやはりそのあたり遅いので。

**Comment by thinca** [comment]
普段使ってるけど、特別遅いと感じたことはないです。samba。
環境に依るのかな?

**Comment by koron** [comment]
Samba2の頃の話だったり? 記憶では3でACLの対応が良くなったような。
あとはswpの置き場とかが原因として思いつく。

**Comment by mattn** [comment]
僕は常時noswapでノーブラです。

**Comment by thinca** [comment]
自宅のsambaのバージョンは確認しないとちょっとわかりませんが、基本最新を使ってるはずなので古いってことはないはずです。
swap は私は1箇所に集めてますね。

**Comment by mattn** [comment]
sambaでなく本物のwin serverなのが問題？

**Comment by mattn** [comment]
原因これでした。

https://github.com/thinca/vim-localrc/pull/1

って事でclose
