### ISSUE TITLE
hl-Terminal のヘルプがない。:hi <C-D>で Ternimal が候補にない。

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#1131]
hl-Terminal は足せば良いと思います。
`:hi <C-D>`で`Ternimal`が候補に出ない件は、`HL_TABLE()` (highlight_init_both[]、highlight_init_light[]、highlight_init_dark[]？)に登録されていないからかな。
一度、`:hi Terminal ctermfg=green` 等を実行すると登録されるので、以後は`:hi <C-D>`で候補に出てきます。
`is_terminal_group`や`set_terminal_default_colors`が関連キーワード？
すなまい。時間取れないのでどなたかお願いします。
8.0.1412

**Comment by ichizok** [comment]
`Terminal` は（`Normal` もそうですが）デフォルト設定が `NONE` なので補完されませんね。
他の highlight group も `hi XXX NONE` すると出てこなくなるので、これは（現状の仕組みでは）仕方ないのではないかと。
`:help highlight-default` に挙がっている group は常に補完対象に入れるように変更してもいいかもしれませんが。

**Comment by h-east** [comment]
`Normal`は`vim -Nu NONE`で起動しても補完されますね。
`Terminal`も`Normal`と同じような感じで設定すれば良いんではないかと思いました。
hl-Terminal help追加だけでもいいです。

> hi XXX NONE すると出てこなくなる

なるほど

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2486
投げました。

> Normalはvim -Nu NONEで起動しても補完されますね。

`FEAT_GUI` が定義されている時は最初から存在するようです。(`:hi Normal gui=NONE`)

**Comment by ichizok** [comment]
https://github.com/vim/vim/commit/df980db69b831381c37c3e2973a6eefa10df305c
`hl-Terminal` 追加されました。

https://github.com/vim/vim/pull/2486
案の定、`Normal` も （GUIなしだと）補完ないよと言われて、それ以上推す理由もなかったので諦めました。

**Comment by h-east** [comment]
@ichizok Thanks:+1: help追加されたので問題ないです。ありがとうございました。
