### ISSUE TITLE
set linebreak+矩形ビジュアルモードで加算、減算、置き換えでおかしな位置が編集される

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1133]
## 質問・報告の内容
set linebreak
を使い実際に折り返しが発生し、更に折り返しより後ろの文字で矩形ビジュアルモードを用いると

- 加算、減算がカーソル位置で行われない
- 置き換えは折り返し前の位置に追加され、更に空白文字が追加される

次のGIFは
> $ vim -u NONE +"set linebreak" sample.txt

で起動後、

1. 空白文字がないことを示すために[l]でカーソル移動して、折り返し先まで移動
2. $&lt;C-v&gt;j&lt;C-a&gt;gvg&lt;C-a&gt;gv&lt;C-x&gt;gvg&lt;C-x&gt;F0r1 で加算、減算、置き換えを実行
3. 折り返し前の行に空白が追加された事を示すために「l」でカーソル移動

の過程です
![vim](https://user-images.githubusercontent.com/24851657/34208665-a73834b8-e5d2-11e7-8c90-d6b7f2f442b5.gif)

折り返されていない時や、linebreakが働いていない時は意図通りの動作をします
またGVimでも同様です
## Vimのバージョン
> $ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)
適用済パッチ: 1-197, 322, 377-378, 422, 550

## OSの種類/ディストリ/バージョン
>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
$ uname -a
Linux xxxxx 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## 使用している or 関係していそうなプラグイン
なし

**Comment by h-east** [comment]
Vim 8.0.1417 on fedora 26 via PuTTY(端末横サイズ 80文字)で再現しました。

sample.txt
```
_______________________________________,__0______________________________________,5
_______________________________________,__0______________________________________,5
```

`$<C-v>j<C-a>`
で2つの`5`が`6`にならないといけないのに、2つの`0`が`1`になってしまいますね。
`'linebreak'`と矩形ビジュアルモードの組み合わせで発生するようです。

**Comment by iranoan** [comment]
すいません
書き込みご見直し忘れていました
やはりバグなんですね
rによる置き換えも原因は同じなんですかね

**Comment by h-east** [comment]
まずは、加算&減算を直してみました。矩形ビジュアルモード以外の加算&減算がおかしくなっている可能性があるかも。いろいろ動作確認してみて下さい。
rによる置き換えおよびYankも同様の修正(オペレータ処理後に curwin->w_p_lbr を元に戻す)をすれば直るんですが、ソースのコメントを見ると「うーん」って感じです。
normal.c: 2078
```
                /* Restore linebreak, so that when the user edits it looks as
                 * before. */
```
もう少し調べてみます。

```diff
diff --git a/src/normal.c b/src/normal.c
index 745a2f68c..379a5edc4 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -2124,11 +2124,11 @@ do_pending_operator(cmdarg_T *cap, int old_col, int gui_yank)
 	    else
 	    {
 		VIsual_active = TRUE;
+		op_addsub(oap, cap->count1, redo_VIsual_arg);
+		VIsual_active = FALSE;
 #ifdef FEAT_LINEBREAK
 		curwin->w_p_lbr = lbr_saved;
 #endif
-		op_addsub(oap, cap->count1, redo_VIsual_arg);
-		VIsual_active = FALSE;
 	    }
 	    check_cursor_col();
 	    break;
```

**Comment by h-east** [comment]
'linebreak'と矩形ビジュアルモードで加算&減算(op_addsub)、置き換え(op_replace)、ヤンク(op_yank)が正しく動作しない件を修正しました。動作確認をお願いします。
https://gist.github.com/h-east/c9043fbc75c599c4cd31003f533f30e5

動作確認中に以下の不具合を発見したので修正しました。(上記patchのsrc/ops.cの部分)
- `bri`でwrapされた行の最初の文字の矩形ビジュアルモードでの加算がおこなわれない
```
$ vim -Nu NONE +"set bri briopt=" +"30vnew" +"norm 4a1234567890" +"norm >>gj"
```
`<C-V><C-A>`しても`3`のままで変化しない。

---
あと、以下の問題があることがわかっています。(maybe 既知の問題)
- `bri`でwrapされた行の最初の文字の矩形ビジュアルモードでのヤンクがおこなわれない
```
$ vim -Nu NONE +"set bri briopt=" +"30vnew" +"norm 4a1234567890" +"norm >>gj"
```
`<C-V>y`しても`3`がヤンクされない。

**Comment by ichizok** [comment]
`OP_APPEND`, `OP_INSERT` も、`<C-V>` で2行以上選択して実行すると2行目以降が壊れます。

https://github.com/vim-jp/issues/issues/1133#issuecomment-353099561 の状況だと `gj<C-V>jAa` で確認できます。

**Comment by iranoan** [comment]
報告したものですが、私はUbuntuの公式リポジトリを使っている軟弱者なので、申し訳ありませんが、皆さん動作確認をよろしくお願いします🙇

**Comment by h-east** [comment]
Related vim_dev thread.
https://groups.google.com/d/topic/vim_dev/xy7eYYZXe_w/discussion

**Comment by k-takata** [comment]
[8.2.0147](https://github.com/vim/vim/commit/03c3bd9fd094c1aede2e8fe3ad8fd25b9f033053) (#1273) で直ったと思われるので閉じます。
