### ISSUE TITLE
elseif 行のプロファイル結果がおかしい

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1134]
## 再現手順

func.vim:

```vim
func! Foo()
  if 0
    let x = 0
  elseif 1
    let x = 1
  endif
endfunc
call Foo()
```

`vim --clean +'profile start prof.log' +'profile func Foo' +'so func.vim' +'qall!'`

prof.log:

```
FUNCTION  Foo()
Called 1 time
Total time:   0.000026
 Self time:   0.000026

count  total (s)   self (s)
    1              0.000007   if 0
                                let x = 0
                              elseif 1
    1              0.000004     let x = 1
    1              0.000003   endif

(snip)
```

通ったはずの `elseif 1` の行がカウントされていない。

## 原因

https://github.com/vim/vim/blob/ae6f865/src/ex_docmd.c#L2018-L2021

ここで `func_line_exec` を通った場合に、その行はプロファイリング対象になる。
問題は if 条件文の `ea.skip` の値で、

https://github.com/vim/vim/blob/ae6f865/src/ex_docmd.c#L2009-L2010

直上のここで計算される。エラーや例外発生を除けば、基本的に直前の状態による。

`cstack->cs_flags[cstack->cs_idx]` の値を見ていくと

```vim
if 0            " CSF_ACTIVE -[条件判定]-> 0 (false)
  let x = 0     " 0
elseif 1        " 0 -[条件判定]-> CSF_ACTIVE|CSF_TRUE (true)
  let x = 1     " CSF_ACTIVE|CSF_TRUE
endif           " CSF_ACTIVE
```

`elseif 1` の行に入る時点で `cstack->cs_flags[cstack->cs_idx]==0 => ea.skip==TRUE` なので、`elseif 1` の行はプロファイリング対象にならない。

`ea.skip` の計算時に、 `:elseif` `:else` 行を考慮する必要があると思われる。

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/profile-line.diff

`find_command()` を前に持ってきて、行が `:elseif` `:else` `:endif` の時は `ea.skip` の計算方法を変える。

**Comment by ichizok** [comment]
`catch` `finally` も考慮する必要がある。
`endfor` `endwhile` は以下のようなケースをどうするか。

```vim
count
    1   while 0
    0     "
    0   endwhile

    1   while 1
    1     return
    0   endwhile
```

実行経路を区別できるようにするため、前者の `endwhile` は1回カウントした方がいいのではないか。

**Comment by thinca** [comment]
loop が発生すれば `while` の行のカウントが増えるはずなので、実行経路の区別はできそうな気がします。

**Comment by ichizok** [comment]
すみません、例がおかしかったんですが、

```vim
func! Foo1()
  while 1
    break
  endwhile
endfunc

func! Foo2()
  while 1
    return
  endwhile
endfunc
```

こういう場合に、今はどちらも `endwhile` は0回になるけど前者は1回にしたいという意見でした。

**Comment by thinca** [comment]
なるほど。区別したい場合があるかはちょっとわからないですが、実際の動作を考えると妥当な気がします。 👍

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2499
投げました。

**Comment by ichizok** [comment]
todolisted
https://github.com/vim/vim/commit/eb3dc87f01391bb075d97aef3d00f91b4e08a25c#diff-38d7929bd26d74d92ceddf984bbfc8dbR630

**Comment by ichizok** [comment]
8.1.0309
https://github.com/vim/vim/commit/7feb35e7782907b44659a2748ff5d7489deeed74
