### ISSUE TITLE
入力補完中にコマンドラインウインドウに表示される"match N of M"といったメッセージを抑制したい

### ISSUE THREAD

**Issue by maskedw** [vim-jp/issues#1137]
## 質問・報告の内容
jedi.vimでは補完したメソッドのシグネチャをコマンドラインウインドウに表示する機能があります。この状態で引数の入力を始めると別の補完が始まり、表題のメッセージが表示されて、表示されていたメッセージが消えてしまいます。
このメッセージを抑制する方法はないでしょうか？できればエラーメッセージはそのまま表示したいです。
![snapcrab_noname_2018-1-2_17-26-28_no-00](https://user-images.githubusercontent.com/1787786/34478240-3d4d32ae-efe3-11e7-937c-53e67e3d098c.png)

## Vimのバージョン
```
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 17 2017 15:01:15)
適用済パッチ: 1-1397
...
```
## OSの種類/ディストリ/バージョン
* Ubuntu16.04

## 使用している or 関係していそうなプラグイン
標準の補完でも表示されるので、プラグインが表示しているのではないはず。

## その他
なし

**Comment by thinca** [comment]
```vim
set shortmess+=c
```

これでどうでしょうか? 補完周りのメッセージが一通り抑制されます。

**Comment by maskedw** [comment]
期待通りの動作になりました。ありがとうございます。
