### ISSUE TITLE
スワップファイルが壊れる

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#1139]
## 質問・報告の内容

大雑把に以下の2つの条件が揃うとスワップファイルが壊れます。

1. ファイルを開いてバッファを編集しvimを強制終了するまでの手順を4秒(オプションupdatetimeの標準値)以内に行う。
2. BufReadCmdに*.*形式で重複しない拡張子をいくつか指定する。

2についてはもう少し細かい条件がある気がします。

エラーメッセージ: `E309: .a.txt.swp からブロック 1 を読込めません`

### 再現方法:

標準プラグインのzipPlugin.vimが使える状態のvimを用意します。

1. `$ vim a.txt` もしくは vimを起動してから`:tabe`や`:e`などでa.txtを開きます。
2. インサートモードで適当に文字を入力します。
3. 別の端末から`$ pkill -n -9 vim`を実行してvimを強制終了させます。ここまでの手順を4秒以内に終わらせます。
4. `$ vim a.txt`してリカバリ画面で r を押下するとE309が出て復元に失敗します。

zipPlugin.vimに依存しないサンプルも載せます。
下記のサンプルを実行すると1秒後にvimのリカバリ画面が表示されますので、そこで r を押下するとE309が出ます。

### 1つずつイベントを追加していく場合のサンプル

sample1.vim:
```vim
augroup sample
    autocmd!
    for i in range(1, 13)
        execute 'autocmd BufReadCmd *.' . i 'echo'
    endfor
augroup END
```

vim --cleanで起動: 13個以上BufReadCmdを設定すると再現します。
```
(sleep 1; pkill -n -9 vim) & vim --clean --cmd 'so sample1.vim' -c 'normal! ii' a.txt; vim --clean a.txt
```

vim -Nu NONEで起動する場合は7個以上あれば再現します。
```
(sleep 1; pkill -n -9 vim) & vim -Nu NONE --cmd 'so sample1.vim' -c 'normal! ii' a.txt; vim --clean a.txt
```

### 1度にイベントを追加した場合のサンプル

sample2.vim:
```vim
augroup sample
    autocmd!
    autocmd BufReadCmd *.1,*.2,*.3,*.4,*.5,*.6,*.7,*.8,*.9,*.10,*.11,*.12,*.13,*.14,*.15,*.16 echo
augroup END
```

vim --cleanで起動: 拡張子16個以上で再現します。
```
(sleep 1; pkill -n -9 vim) & vim --clean --cmd 'so sample2.vim' -c 'normal! ii' a.txt; vim --clean a.txt
```

vim -Nu NONEで起動する場合は拡張子8個以上あると再現します。
```
(sleep 1; pkill -n -9 vim) & vim -Nu NONE --cmd 'so sample2.vim' -c 'normal! ii' a.txt; vim --clean a.txt
```

## Vimのバージョン

8.0.1427

## OSの種類/ディストリ/バージョン

*   Linux Debian stretch 9.3 64bit

## その他

標準プラグインzipPlugin.vimが元でスワップファイルが壊れる場合は、以下の1行をコメントアウトすると再現しなくなります。

```vim
 exe "au BufReadCmd ".g:zipPlugin_ext.' call zip#Browse(expand("<amatch>"))'
```

**Comment by ichizok** [comment]
私の環境 (Ubuntu 16.04) では、SIGKILL 以外の終了シグナルでは再現しませんでした。
SIGKILL では Vim の終了処理が行われないので、状態が壊れるのは仕方ないのではないかと思います。

**Comment by norio13** [comment]
スワップファイルが作成された時点で壊れている気がします。

ファイルの作成・更新時にスワップファイルを連番で保存するシェルスクリプトを書きました。

kansi.sh:
```shell
#!/bin/sh

i=1
while inotifywait -e create -e modify --format "%T %e %f" --timefmt "%H:%M:%S" ./; do
    cp .a.txt.swp "${i}.txt"
    i=$((i+1))
done
```

端末で`sh kansi.sh`を実行します。
別の端末で以下のコマンドを実行します。
```
(sleep 5; pkill -n -9 vim) & vim -Nu NONE --cmd 'so sample1.vim' a.txt
```
最初の報告ではコマンドの部分で-c 'normal! ii'を入れてたのですがこれはなくても再現したので今回は除外しました。
5秒経過してVimが強制終了した後、kansi.shの処理を手動で停止させます。

この段階で、スワップファイル作成時の内容が1.txt、更新時の内容が2.txtに保存されています。
2.txtを.a.txt.swpに名前変更してから`vim a.txt`すればリカバリ出来ますが、1.txtを使用した場合は壊れているのでリカバリに失敗します。

BufReadCmdを除く全てのイベントも確認してみましたが、SIGKILLでVimを強制終了させてもスワップファイルは壊れませんでした。
BufReadCmdの時だけこのようになるのは個人的には違和感がありますが、仕様であれば受け入れます。

**Comment by k-takata** [comment]
`:help Cmd-event` によると、

> BufReadCmd に対して自動コマンドを定義すると、クラッシュしたセッションの復旧が
> 難しくなる。元のファイルから復旧するとき、Vimはスワップファイル内に見つからな
> かった部分のみを読み込む。それは BufReadCmd の自動コマンドを使ったときは不可
> 能なので、コマンド |:preserve| を使って元のファイルが復旧に必要ないようにする
> こと。そうするのはファイルが変更を受けたと判断したときのみでもよい。

ということで、BufReadCmd は、ファイルをバッファ内に読み込む役目を負ってるので、スクリプトが責任をもって処理を行う必要があるということだと思います。

**Comment by norio13** [comment]
仕様ということで納得できました。
ありがとうございます。
