### ISSUE TITLE
'wrap' で折り返したときにインデントする機能が欲しい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#114]
http://d.hatena.ne.jp/takuya_1st/20111222/1324550041
欲しい！

**Comment by tsmd** [comment]
これはまじでほしいです

**Comment by ynkdir** [comment]
Why was the breakindent patch never applied?
http://groups.google.com/group/vim_dev/browse_thread/thread/55d30b572fd94b62/09470ca14f2c0178

パッチはすでにあるみたいです。数年前から。
リンク先はなんで取り込んでくれないの？という議論です。

**Comment by thinca** [comment]
あ、このメールのタイトルは見覚えがありますね…。これがそうだったのか。

**Comment by thinca** [comment]
Bram さんは、バグ修正が優先だから、と言ってますね。これは #54 にも通じる所があるか。

**Comment by koron** [comment]
最終的にパッチは7年前までさかのぼりますね。

http://marc.info/?l=vim-dev&m=109921292009721&w=1

> バグ修正が優先だから

その割に他のメンバーからの急がんでも良いパッチはバカバカと取り込まれてる気もしますが…
(特に補完系のやつ)

レビュー体制だけでも変えると違ってくんのかなぁ。
もしくはML上で我々がパッチをレビューして推薦すればそれで通るかしらね?

**Comment by koron** [comment]
あーいま先のパッチちゃんとみたらこりゃダメだわ。
defineの扱いとかコーディングスタイルとか
取り込んでもらおうという意思が感じられない。

アレを元に作りなおして、すぐに取り込める形にしてあげればすんなり行くんじゃなかろうか?

**Comment by koron** [comment]
こっちが最新か。

https://retracile.net/attachment/wiki/2009/12/22/16.00/vim-7.2-breakindent.patch

コーディングスタイルとかコメントとか、細かいところがそのままかも。

**Comment by mattn** [comment]
ここが最新っぽい

https://retracile.net/wiki/VimBreakIndent

**Comment by wozozo** [comment]
ほしい

**Comment by osyo-manga** [comment]
ほしい

**Comment by k-takata** [comment]
7.4.027 用に更新版を作ってみました。コーディングスタイルも修正済み。
さらに、strdisplaywidth() に行番号を指定するための引数を追加。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/29351a94aa0d0c897af6ccd7a6cb773befcc4072/vim-7.4.027-breakindent.patch

screen.c に残っている FIXME が気になるところです。

**Comment by k-takata** [comment]
@koron 

> defineの扱いとか

これって、どの部分を指しています？ 直してから投げようかと思うのですが。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/SML3mtGd50s/discussion
(投げる直前に、 https://retracile.net/blog/2013/09/12/23.00 で 7.4.016 向けのパッチが出ていたことに気づきましたが…ま、いっか)

**Comment by k-takata** [comment]
todo.txt が更新されました。

> ```
> -   Patch for 'breakindent' option: repeat indent for wrapped line. (Vaclav
>     Smilauer, 2004 Sep 13, fix Oct 31, update 2007 May 30)
>     Version for latest MacVim: Tobia Conforto, 2009 Nov 23
>     More recent version: https://retracile.net/wiki/VimBreakIndent
>     Posted to vim-dev by Taylor Hedberg, 2011 Nov 25
>     Update by Taylor Hedberg, 2013 May 30.
>     Updated for Vim 7.4 by Ken Takata, 2013 Oct 5.
> ```

**Comment by Shougo** [comment]
ついにtodo入りですね。ここはcloseはしないのでしょうか。

**Comment by k-takata** [comment]
ついにというか、このissueが立てられたときには既に入っていて、それが更新されただけですから…どうしましょうか。
他に何かやるべきことがあるかというと、上に書いたように、screen.c の FIXME を直すとか、テストを追加するとか、バグがないか徹底的に叩きまくるとか…

**Comment by Shougo** [comment]
たしかにそういうことはできそうですね。

**Comment by rhysd** [comment]
折り返しが発生している行の一番下の行で g$ すると挙動がおかしいです．

```
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
       aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

上記のテキストが1行を折り返したものだとして，4行目で `g$` を使うとインデント分だけカーソルが余分に右に来てしまいます．

**Comment by k-takata** [comment]
うーん、再現しないです。

**Comment by rhysd** [comment]
あれ，再現しないですか… MacVim だからなのかな…

**Comment by k-takata** [comment]
Christian Brabandt氏による新スレッドが立ちました。
[patch] updated breakindent patch
https://groups.google.com/d/topic/vim_dev/ZGIQQPtVhkI/discussion

**Comment by k-takata** [comment]
7.4.338 でついに取り込まれました。
https://groups.google.com/d/topic/vim_dev/qrhUA-dt7SY/discussion

**Comment by k-takata** [comment]
最初のパッチが2004年ということで10年がかり！

**Comment by thinca** [comment]
ヤッター！

**Comment by rhysd** [comment]
:clap:

**Comment by Shougo** [comment]
やはり Christian Brabandt さんが手直ししてくれたのが大きかったのでしょうね。

**Comment by todashuta** [comment]
:congratulations:

**Comment by tyru** [comment]
:tada:

**Comment by tyru** [comment]
:point_left: TOKYU HANDS :point_right:

**Comment by wozozo** [comment]
Yo

**Comment by eagletmt** [comment]
:star2:

**Comment by haya14busa** [comment]
:sushi:

**Comment by crazymaster** [comment]
:dancers:

**Comment by presuku** [comment]
:100: 
すばらしい！
あとで、パッチを試そうと思っていたら、
こんなに早く本体に取り込まれるとは。
