### ISSUE TITLE
Vim の :terminal で非カノニカルモード (min=1) の read() がブロックする

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1140]
## 質問・報告の内容

ANSI エスケープコードの DSR (Device Status Report) で現在カーソル位置を取得しようと `tcsetattr(3)`  で非カノニカルモード (min=1) にしたのち stdin fd に対して `read(2)` したのですが、WSL の mintty ではブロックせず（入力待ちにならず）に動くプログラムが、Vim の :terminal では `read(2)` でブロックしてしまいます。
`gdb -p <pid>` でアタッチしてバックトレースを表示した所、 `read()` で止まっている事を確認しました。

```c
#include <stdio.h>
#include <termios.h>
#include <unistd.h>

int main(int argc, char const* argv[])
{
  struct termios ttystate, ttysave;
  tcgetattr(STDIN_FILENO, &ttystate);
  ttysave = ttystate;
  ttystate.c_lflag &= ~(ICANON | ECHO);
  ttystate.c_cc[VMIN] = 1;
  ttystate.c_cc[VTIME] = 0;
  tcsetattr(STDIN_FILENO, TCSANOW, &ttystate);

  printf("\x1b\x5b" "6n");
  fflush(stdout);

  char buf[1] = {0};
  read(STDIN_FILENO, buf, 1);

  tcsetattr(STDIN_FILENO, TCSANOW, &ttysave);
}
```

#### mintty で実行

![63f3428e1eccd60a28acf6055dd20b3e](https://user-images.githubusercontent.com/48169/34729930-4e79f828-f5a1-11e7-858b-b93800b2e530.gif)

#### Vim の :terminal で実行

エンターを押して継続しました。

![7de6002d3455a4588ee44e7cf063ed0e](https://user-images.githubusercontent.com/48169/34730768-b31d12ea-f5a3-11e7-9e7e-4b87c923d2d2.gif)

#### Vim の :terminal で実行した後 gdb -p でアタッチ

バックトレースに `dsr.c:19` と出ていて `read()` の行番号と一致しています。

![c6ec6f1d6f672930378b89d487496a9d](https://user-images.githubusercontent.com/48169/34731052-8018f6f6-f5a4-11e7-908d-77f125dd4eab.gif)

## Vimのバージョン

8.0.1428

## OSの種類/ディストリ/バージョン

1. WSL
    * Windows 10 Pro 64bit (10.0.15063)
1. Ubuntu 16.04.3 LTS

## その他

Ubuntu 16.04.3 LTS の方は ssh ログイン、かつ gdb でのアタッチは権限の関係でできませんでした。

**Comment by ichizok** [comment]
1) プログラムが stdout (pty slave) に control sequence を投げる
2) Vim が pty master からそれを読み出し、libvterm に渡す
3) libvterm はレスポンスを作成し、自身の output buffer に載せる
4) Vim は適当なタイミングでそれを取得し、pty master に書き出す
5) プログラムの `read()` で読まれる

現状、3) の「適当なタイミング」は「ユーザ入力があった時」なので、それまで 5) はブロックしてしまいます。

https://github.com/vim/vim/compare/master...ichizok:fix/terminal-ctrl.diff
3) で output buffer に変更があったらその時点で pty に書き出すようにしてみました。

**Comment by tyru** [comment]
ありがとうございます！
今日（11日）の夜帰ったらパッチ当てて試してみます。

**Comment by tyru** [comment]
@ichizok WSL と Ubuntu 16.04.3 LTS で直ってるのを確認できました！ありがとうございます！

**Comment by tyru** [comment]
これってまだパッチ送られてないんでしょうか？

**Comment by ichizok** [comment]
Bram が Vim 活再開したら投げようと思ってます。

**Comment by tyru** [comment]
なるほどすみません！了解です！

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2594
投げました。

**Comment by ichizok** [comment]
8.0.1440
https://github.com/vim/vim/commit/b50773c6df0bc2c9c2ab1afecc78083abc606de0

**Comment by tyru** [comment]
ありがとうございました！
