### ISSUE TITLE
'undo 1' 後に redo すると元に戻るが 'undo 0' 後だと戻らない

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#1142]
以下は gvim 8.0.1428 での結果です。
'mbbill/undotree' プラグインを使いました。

(A) 正しい動きと思われる例： 'undo 1' の場合

新しい window で
```
:norm i1
:norm i2
:norm u
:norm i3
:norm u
:norm i4
```
を実行すると undotree は
```
*   >4<
| *    3
|/
| *    2
|/
*    1
*    0
```
となり、undotree() は
`{'seq_last': 4, 'entries': [{'seq': 1, 'time': 1515830901}, {'seq': 4, 'alt': [{'seq': 3, 'alt': [{'seq': 2, 'time': 1515830909}], 'time': 1515830925}], 'time': 1515830937, 'newhead': 1}], 'time_cur': 1515830937, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 4}
`
を出力します。

ここで
`:undo 1
`
を実行すると undotree は
```
 *   {4}
 | *    3
 |/
 | *    2
 |/
 *   >1<
 *    0
```
となり、undotree() は
`{'seq_last': 4, 'entries': [{'seq': 1, 'time': 1515830901}, {'curhead': 1, 'seq': 4, 'alt': [{'seq': 3, 'alt': [{'seq': 2, 'time': 1515830909}], 'time': 1515830925}], 'time': 1515830937, 'newhead': 1}], 'time_cur': 1515830937, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 1}
`
を出力します。curhead は seq 4 に存在します。

この状態で
`:redo
`
を実行すると undotree は
```
 *   >4<
 | *    3
 |/
 | *    2
 |/
 *    1
 *    0
```
となり、undotree() は
`{'seq_last': 4, 'entries': [{'seq': 1, 'time': 1515830901}, {'seq': 4, 'alt': [{'seq': 3, 'alt': [{'seq': 2, 'time': 1515830909}], 'time': 1515830925}], 'time': 1515830937, 'newhead': 1}], 'time_cur': 1515830937, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 4}
`
を出力します。完全に元に戻ります。

(B) 正しくない動きと思われる例： 'undo 0' の場合

新しい window で
```
:norm i1
:norm u
:norm i2
:norm u
:norm i3
```
を実行すると undotree は
```
 *   >3<
 | *    2
 |/
 | *    1
 |/
 *    0
```
となり、undotree() は
`{'seq_last': 3, 'entries': [{'seq': 3, 'alt': [{'seq': 1, 'alt': [{'seq': 2, 'time': 1515829428}], 'time': 1515829416}], 'time': 1515829437, 'newhead': 1}], 'time_cur': 1515829437, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 3}
`
を出力します。

ここで
`:undo 0
`
を実行すると undotree は
```
 *   [3]
 | *    2
 |/
 | *   {1}
 |/
 *   >0<
```
となり、undotree() は
`{'seq_last': 3, 'entries': [{'curhead': 1, 'seq': 1, 'alt': [{'seq': 3, 'alt': [{'seq': 2, 'time': 1515829428}], 'time': 1515829437, 'newhead': 1}], 'time': 1515829416}], 'time_cur': 1515829437, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 0}
`
を出力します。curhead は seq 1 に存在します (seq 3 であるべきか？)。

この状態で
`:redo
`
を実行すると undotree は
```
 *    3
 | *    2
 |/
 | *   >1<
 |/
 *    0
```
となり、undotree() は
`{'seq_last': 3, 'entries': [{'seq': 1, 'alt': [{'seq': 3, 'alt': [{'seq': 2, 'time': 1515829428}], 'time': 1515829437}], 'time': 1515829416, 'newhead': 1}], 'time_cur': 1515829416, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 1}
`
を出力します。seq 1 に移動してしまい、元の seq 3 に戻りません。

----------------------------

どうやら
`:undo 0
`
を実行した後の curhead の存在位置がおかしいみたいです。
seq 2 から実行しても curhead はやはり seq 1 に存在し、元の seq 2 に戻りません。

**Comment by rickhowe** [comment]
以下のパッチはこの件に関連するかもしれません。
7.4.1574: ":undo 0" does not work
8.0.1290: seq_cur of undotree() wrong after undo

**Comment by ichizok** [comment]
`:earlier N` で 0 に戻した場合も同様のようです。
7.4.1574 の修正の時点でこの動作になっていたと思われます。

https://github.com/vim/vim/compare/master...ichizok:fix/undo-0.diff
0 の状態は自明なのでノードの探索処理は省略できるはず？

**Comment by rickhowe** [comment]
ありがとうございます。直ってますね。

(B) の正しくない動きと思われる例で

`:undo 0`

を実行すると undotree は

```
 *   {3}
 | *    2
 |/
 | *    1
 |/
 *   >0<
```
 
となり、undotree() は

`
{'seq_last': 3, 'entries': [{'curhead': 1, 'seq': 3, 'alt': [{'seq': 2, 'alt': [{'seq': 1, 'time': 1516958465}], 'time': 1516958470}], 'time': 1516958475, 'newhead': 1}], 'time_cur': 1516958475, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 0}
`

を出力します。curhead は seq 3 に正しく存在します。

この状態で

`:redo`

を実行すると undotree は

```
 *   >3<
 | *    2
 |/
 | *    1
 |/
 *    0
```

となり、undotree() は

`
{'seq_last': 3, 'entries': [{'seq': 3, 'alt': [{'seq': 2, 'alt': [{'seq': 1, 'time': 1516958465}], 'time': 1516958470}], 'time': 1516958475, 'newhead': 1}], 'time_cur': 1516958475, 'save_last': 0, 'synced': 1, 'save_cur': 0, 'seq_cur': 3}
`

を出力します。元の seq 3 に正しく戻ります。

なお (A) の正しい動きと思われる例も以前のまま正しく元に戻ります。

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2595
投げました。

**Comment by ichizok** [comment]
8.0.1441
https://github.com/vim/vim/commit/ce46d934af35d0f774be7f996001db03cf0b894a
