### ISSUE TITLE
ハイライトグループ "CursorIM" が反映されない

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#1145]
## 質問・報告の内容

Windows 10 で gvim を使っています。以前はインプットメソッドの状態によってカーソルのハイライトが `Cursor` と `CursorIM` で切り替わっていたと思うのですが、 Vim 8.0.1401 から　`CursorIM` が適用されなくなっているような気がします。

## Vimのバージョン

8.0.1401 から

https://github.com/vim/vim/commit/cb89c98c264b0fe9fd26e3501eab5a062e57c064

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

*   Windows 10 Education 64bit

## その他

* Vim 8.0.1400

![vim8 0 1400](https://user-images.githubusercontent.com/480049/35093941-c51ae2c4-fc7e-11e7-932c-ae7c0e3223fb.gif)

* Vim 8.0.1401

![vim8 0 1401](https://user-images.githubusercontent.com/480049/35093944-c75067a8-fc7e-11e7-990a-52283c3337f2.gif)

**Comment by k-takata** [comment]
Posted.
https://groups.google.com/d/msg/vim_dev/siMzi6qQR0w/s3v9zjlzBAAJ

**Comment by crazymaster** [comment]
これはwindowsでの話だけどLinuxでも似たような問題がありましたね

https://github.com/vim-jp/issues/issues/739

**Comment by k-takata** [comment]
8.0.1471: https://github.com/vim/vim/commit/28944fecff3c40b44325921d45aaf67451b0937f
