### ISSUE TITLE
矩形選択で全角文字への置換が出来ない

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1146]
## 質問・報告の内容
表題通り、矩形選択時にに全角文字への置換が出来ません
それほど使うこともないので、仕様なら仕様で構わないのですが、

- 矩形選択でなければ
- 矩形選択でも半角なら

置き換えられるので気になりました
添付画像は
 . (空白 ピリオド 空白)
と言う内容に対して、
r。uyypk^Vjr,u^Vjr。
をした結果です(^Vは実際にはCtrl-Vです)
![vim](https://user-images.githubusercontent.com/24851657/35229707-69f92fd4-ffd7-11e7-94ff-ed24ece4b66e.gif)
## Vimのバージョン
> $ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 20:13:43)
適用済パッチ: 1-197, 322, 377-378, 422, 550
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
$ uname -a
Linux naonari 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

日本語入力にはfcitx+Mozcの組み合わせで使っています
## 使用している or 関係していそうなプラグイン
添付画像とは別に
> vim -u NONE

も同じなので、関係ないと思います

**Comment by h-east** [comment]
(私もバグだと思って`kind/bug`ラベルを付けていましたが、)
この挙動は仕様通りですね。`:h v_b_r`を参照下さい。
```
Visual-block Replace                                            v_b_r
Every screen char in the highlighted region is replaced with the same char, ie
TABs are split and the virtual whitespace is replaced, maintaining screen
layout.
See v_b_r_example.
```

ちょっと分かりにくいですが、`maintaining screen layout`が肝です。
文字単位のビジュアルモード(`v`)の場合の`r`は文字単位で置き換えしますが、矩形ビジュアルモード(`CTRL-v`)の場合はスクリーンセル単位で置き換えます。

文字単位のビジュアルモード(`v`)の場合:
abcdefg ←テスト用文字列
- `0fcvrあ` → `abあdefg`
- `0fcvlrあ` → `abああefg`
- `0fcv2lrあ` → `abあああfg`
- `0fcv3lrあ` → `abああああg`

矩形ビジュアルモード(`CTRL-v`)の場合:
- `0fc<C-v>rあ` → `ab defg`                          　　　※`あ`が2セルで置き換え対象`c`が1セルで入らないので空白で置き換え
- `0fc<C-v>lrあ` → `abあefg`                         　　　※`あ`が2セルで置き換え対象`cd`が2セルでぴったり入るので`cd`を`あ`で置き換え
- `0fc<C-v>2lrあ` → `abあ fg`                         　　　※`あ`が2セルで置き換え対象`cde`が3セルで1つしか入らないので`cd`を`あ`で置き換えて`e`を空白で置き換え
- `0fc<C-v>3lrあ` → `abああg`                         　　　※`あ`が2セルで置き換え対象`cdef`が4セルで2つ入るので`cd`を`あ`で置き換えて`ef`を`あ`で置き換え

**Comment by iranoan** [comment]
なるほどスクリーン上で置き換える文字幅を指定してやらないと駄目なんですね
しかし矩形選択でなければその必要がないので、解り辛い仕様ですね

ちょっとスレッドをクローズして良いケースなのかどうか良く分からないので、クローズするかどうかは識者にお任せしたいと思います
その仕様だと、フォントによって動作が変わらない? それって良いの? という気がするので

**Comment by h-east** [comment]
> その仕様だと、フォントによって動作が変わらない? それって良いの? 

フォントではなくて文字コードで変わるはずです。
Vimのソースコードから `mb_ptr2cells` を検索下さい。

一旦、仕様通りということでクローズさせていただきます。
問題があれば本Issueをreopenするか新規にIssueを作成下さい、

@yoshinaga-hiroyuki Issue登録ありがとうございました。今後ともよろしくお願いします。
