### ISSUE TITLE
ユーザー定義コマンドの中から i_CTRL-O 内で実行されたかを知りたい

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#1147]
## 質問・報告の内容

ユーザー定義コマンドを実行した際に、
そのコマンドの中から通常のExコマンドで実行されたのか 
挿入モードの `i_CTRL-O` から実行されたのかを知りたい。
バッファにテキストを追加するようなコマンドで、
その実行コンテキストに応じてテキストの内容を微調整する用途を想定している。

簡単に vim のソースコードをチェックしたところ、
その情報は `restart_edit` 変数に記録されており
Vim script からストレートにアクセスする手段はなさそう。

## 実装案

@tyru さんから
`mode(1)` が `"n\<CTRL-O>i"` のような文字列を返してくれると嬉しいのでは
的な提案をもらった。
個人的にはなかなかスマートな解法だと感心したが、
既存の使われ方との互換性がちょっときになる。

**Comment by tyru** [comment]
> 既存の使われ方との互換性がちょっときになる

スクリプトで単にノーマルモードか判定したい時は

* `mode() ==# 'n'`
* `mode(1) =~# '^n'`

のように使うべきだと個人的に思ったので、`mode(1)` で新しい値を返すのは問題ないと思い提案しました。

ちなみに 7.0 で mode() が引数を取れるようになったようですが、まだあまり使われてる印象はないです。

> :help version7.txt
>
> Added argument to mode() to return a bit more detail about the current mode.

**Comment by ujihisa** [comment]
src/evalfunc.c の `f_mode()` の実装見てみました。内部的に2文字分だけ文字列領域確保してごにょごにょやってるみたいですね。 `"n\<CTRL-O>i"` だと3文字なのでcharを1つ増やせばいけるかな・・・。

いま書いてる途中のもの: https://gist.github.com/ujihisa/addd71609e1a3a9eb337e8e3fc2a3390

**Comment by tyru** [comment]
マクロ実行中とかは `reg_executing()` として実装されたので、もしかしたらこれも別の関数にしろって言われる可能性はありそうですね。

**Comment by ujihisa** [comment]
参考資料 https://github.com/vim/vim/issues/1397#issuecomment-273907789

ちなみにお客様の中で、 `挿入モードの i_CTRL-O から実行されたのかを知りたい。` のが実現できたときの具体的なユースケース教えてください! (開発中のプラギンXで使う、とかそういう具体的なやつ)
pullreq投げるときに便利そう

**Comment by ujihisa** [comment]
一旦マクロ実行中かどうかはおいといて、表題のやつができました。

https://github.com/ujihisa/vim/commit/d7a7ae3f353c4d0a8c0220cd2f65abeaa4ca5f37

作法がよくわかっていないのでレビューしてくださるとめっちゃ助かります!

**Comment by h-east** [comment]
@ujihisa Gistにコメントしました。

**Comment by ujihisa** [comment]
神

**Comment by ujihisa** [comment]
https://github.com/ujihisa/vim/pull/1#issuecomment-396147562

**Comment by ujihisa** [comment]
https://github.com/vim/vim/pull/3000
感極まってきました

**Comment by h-east** [comment]
vim_devの反応(取り込まれた or TODOリストに入った or 却下された)があるまではこのissueはオープンにしたままにしておいて下さいね。

**Comment by h-east** [comment]
よく考えたら、`CTRL-O`後のモードがノーマルモードとは限らないですね。
`i<C-O>:` はコマンドモードですし、
`i<C-O>v` はビジュアルモードですし。
なので、Bram氏の言っている `ni` プレフィックスは使えないと思います。

こんな戻り値になるのかなぁ。
`今のモード` `<C-O>` `<C-O>前のモード('I' or 'R' or 'V')`

例:
キー操作 → mode(1)の結果 (`^O`は0xF, `^V`は0x32)
`i<C-O>` → `n^OI`
`i<C-O>:` → `c^OI`
`i<C-O>v` → `v^OI`
`i<C-O>c` → `no^OI`
`R<C-O>` → `n^OR`
`R<C-O><C-V>` → `^V^OR`
`gR<C-O>` → `n^OV`
`gR<C-O>V` → `V^OV`

**Comment by ujihisa** [comment]
うーん、ちょっと考えてみたところそのレベルの網羅性が必要なシーンがあるのか疑問に思ってきました。もともとのユースケースだと、(Bramさんのいうreplace mode / virtual replace modeすらなく) normal modeだけでよかったので

以下こっちが想定してたkoronさんの https://github.com/koron/iferr ぽいもの (たんに自分で手元で検証するのに書いた適当なもの)

```vim
function! Benri() abort
  echomsg string(mode(1))
  if mode(1) == 'niI'
    call append(line('.'), ['{', '}'])
    normal! j
  else " mode(1) == 'n'
    call append(line('.'), ['{', '}'])
  endif
endfunction

command! Benri call Benri()

nnoremap B :<C-u>Benri<Cr>
inoremap B <C-o>:Benri<Cr>
```

**Comment by h-east** [comment]
網羅性？うーん。考え方が違うのかも。私のはスルーでいいです。気が向いたらvim_devでBram氏に質問します。

Vimには入力したキーがそのまま入力されるモードが3つあって(Insert mode, Replace mode, Virtual replace mode)、そこから`<C-O>`で1コマンド実行できる。Bram氏としては`ni`+もとのモード(I, R, V)を返そうと言ってますね。Vimの仕様を踏まえた上での普通の発言だと思います。

もとのモード気にする必要がない局面のユーザーは、`if mode(1) =~# 'ni'` でチェックすればいいですしね:+1:
(I, R, V)はrestart_editに入ってますからそれを使えば実装簡単ですし、、、ってもう実装されてた:yum: Nice!

**Comment by ujihisa** [comment]
フフフ

ちなみに今更感あることを書くと、プラギンレベルでは以下みたいに insert modeの `<C-o>` を経由しないでユーザ定義関数などを実行することで、結局やりたいこと実現できるなあと思いました。

```vim
" before
function! Benri() abort
  if mode(1) == 'niI'
    call append(line('.'), ['{', '}'])
    normal! j
  else " mode(1) == 'n'
    call append(line('.'), ['{', '}'])
  endif
endfunction

command! Benri call Benri()

nnoremap B :<C-u>Benri<Cr>
inoremap B <C-o>:Benri<Cr>
```

```vim
" after
function! Benri(mode) abort
  if a:mode == 'niI'
    call append(line('.'), ['{', '}'])
    normal! j
  else " mode(1) == 'n'
    call append(line('.'), ['{', '}'])
  endif
endfunction

" commandは諦める
nnoremap B :<C-u>call Benri('n')<Cr>
inoremap B <C-o>:call Benri('niI')<Cr>
```

**Comment by k-takata** [comment]
8.1.0225: https://github.com/vim/vim/commit/612cc3888b136e80485132d9f997ed457dbc5501
