### ISSUE TITLE
concealしていると検索時にカーソル位置がずれる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#115]
### 再現手順

```
:help pattern.txt
440G
/line<CR>
```
### 期待する動作

カーソルの下はlで続く文字がineである。
### 実際の動作

カーソルの下はfで続く文字は-lineである。
### 推測される原因

マッチ位置より左にconcealされた要素(文字)があること。
concealされた文字数分、カーソルが実際のマッチ位置よりも左へズレるようだ。

**Comment by thinca** [comment]
マッチ位置と言うより、左に conceal があると常にカーソルがずれますね。
conceal がある行とない行を移動するとよくわかります。
ちなみに `v` などでビジュアルモードにして conceal 文字を表示すると正しく表示されます。

**Comment by Shougo** [comment]
確かにconceal時の挙動には「？」というところがあります。
改善できると良いのですが……。

**Comment by mattn** [comment]
これ絡んでます？

https://groups.google.com/d/topic/vim_dev/fc0p8bfFo2Y/discussion

**Comment by koron** [comment]
説明読んだだけだとドンピシャ。でも、なにげにBramの要求(テスト書いてよ)が高度過ぎる件。
テストスクリプト、これ書けるのかなぁ? /\%vあたりが効いてくれればあるいは?

**Comment by koron** [comment]
`/` で移動後に `col(.)` で拾って明らかに違う位置ってわかるのか。

**Comment by koron** [comment]
ごめん。

Groupのはインデントの話で、本件はマッチ位置の話だった。

**Comment by mattn** [comment]
ここに便乗してついでに直してもらうのがいい気がする。

**Comment by h-east** [comment]
前提条件

``` vim
:syntax enable
:set concealcursor+=n
:set conceallevel=3
```

#### ソース解析内容

conceal関連は以下の条件コンパイルで囲まれている。

``` c
#ifdef FEAT_CONCEAL
#endif
```

関連変数

``` c
curwin->w_p_cocu            //● カレントwindowの `concealcursor`オプション値
curwin->w_p_cole            //● カレントwindowの `conceallevel`オプション値
```

関連関数

``` c
conceal_cursor_line()
conceal_check_cursur_line()
win_line()              //● 指定されたwindowの行を描画する
```

src/screen.c : win_line()
4516～4528行でconceal属性のテキスト非表示の場合のカーソル位置を補正している。
4524行を以下のように修正すると`/`検索時のカーソル位置は正常になるが行内のカーソル移動がちょっとおかしくなる。
(修正前でも行内のカーソル移動はおかしいがそれとはまた別の動作になる)

``` diff
diff -r b161d3c5b588 src/screen.c
--- a/src/screen.c      Tue Oct 23 05:17:38 2012 +0200
+++ b/src/screen.c      Mon Nov 05 22:09:57 2012 +0900
@@ -4521,7 +4521,7 @@
                && conceal_cursor_line(wp)
                && (int)wp->w_virtcol <= vcol + n_skip)
        {
-           wp->w_wcol = col - boguscols;
+           wp->w_wcol = col;
            wp->w_wrow = row;
            did_wcol = TRUE;
        }
```

ということから 変数`boguscols` を更新している部分を追いかければ色々分かってくると思われる。
(5004～5089行あたりが要注目か？)

#268の折り返し関連も同根かなぁ。少なくとも`win_line()`内の修正になるのは間違いない。

どなたか引き継ぎません？`win_line()`は2600行くらいあるけど、defined(FEAT_CONCEAL)で囲まれた部分だけを解析すれば何か見えて来ると思います。
(途中で投げ出してもOK)

**Comment by h-east** [comment]
※vim-jpの皆さんへ。このissueはお試しで @ramu (twitterではramusara)さんに調べてもらっています。いい感じにサポートお願いします。

@ramu さん
このissueに関する質問、調査結果等はココによろしくです。

現象再現しないとのことですが、こちらでは以下の手順で再現しました。(fedora16 64bit, vim ver:7.3.715 on PuTTY)

``` sh
$ cd (vimソースを取得したフォルダ)
$ src/vim -N -u NONE -c "syntax enable" -c "set cocu+=n cole=3" -c "h pattern.txt" +440
```

``` vim
/line<CR>
```

どうでっしゃろ？

**Comment by h-east** [comment]
以下のpatchでconceal関連のtestが追加された。
現在のカーソル位置の情報を返す関数が追加された。screencol() と screenrow()
だぶんbugはそのまま。
Patch 7.3.748
https://groups.google.com/d/topic/vim_dev/80Diqmk-S-o/discussion

**Comment by mattn** [comment]
Patch 7.3.747 じゃなくて？

**Comment by h-east** [comment]
ごめん。見逃してました。
Patch 7.3.747
https://groups.google.com/d/topic/vim_dev/5GADunZjHUc/discussion

**Comment by h-east** [comment]
動作確認しました。patch 7.3.747で治ってる！！
そもそも３月にpatchは出てたのか、、誰か教えてくれよーー。
http://comments.gmane.org/gmane.editors.vim.devel/33830

@ramu さん。。。また別のissueを頑張って下さい。

**Comment by h-east** [comment]
> そもそも３月にpatchは出てたのか、、誰か教えてくれよーー。

まず先にMLの過去の投稿を検索しなかった俺が悪かった。次から改善します。

**Comment by k-takata** [comment]
> そもそも３月にpatchは出てたのか、、誰か教えてくれよーー。

mattnさんが出した https://groups.google.com/d/topic/vim_dev/fc0p8bfFo2Y/discussion は、URLは違うがよく見ると全く同じスレッド…
このパッチで直るのはTabの表示位置だけだと思っていたのですが、同根だったんですね。

まだ、#268 は直っていないのでそちらの方を…。

**Comment by h-east** [comment]
あーっ、このissueの上の方に貼ってあったリンクすら見に行ってなかったｗ。。すんません。
@k-takata 情報ありがとうございます。

> まだ、#268 は直っていないのでそちらの方を…。

そうですね、 @ramu さんにはconcealスペシャリストになってもらいましょう。

**Comment by mattn** [comment]
#268 再現しませんね。

**Comment by mattn** [comment]
あっちにキャプチャ貼っときました。

**Comment by mattn** [comment]
治ったんじゃないの？ 今回ので
