### ISSUE TITLE
マクロ記録中かどうかを取得・判断する手段が欲しい

### ISSUE THREAD

**Issue by koturn** [vim-jp/issues#1152]
## 質問・報告の内容

現状（Vim8.0.1496），マクロ記録中であるかどうかを，Vim scriptで取得・判断する手段が無いように思います．
Vim scriptの組み込み関数等で取得出来れば嬉しいと思います．

## Vimのバージョン

8.0.1496

**Comment by h-east** [comment]
issue立てありがとうございます👍
`mode()`を拡張する形でpatchを書いてみました。マクロ記録中の`mode(1)`は`q`を含んだ文字列を返します。
https://gist.github.com/h-east/be58ab0189088691b8ef889327f3f196
問題なければテストとドキュメント追加してvim_devに提案します。

**Comment by machakann** [comment]
これってちなみにマクロを実行中かどうかは取得できないですかね？

**Comment by koturn** [comment]
@h-east さん
ありがとうございます！僕としては全く問題ありません，完璧です！

**Comment by h-east** [comment]
@machakann マクロ実行中も取得できるようにpatchを更新しました。(Rev.2)
マクロ実行中は`@`を含んだ文字列を返します。
(追記: Rev.3で`q`と`@`両方含んだ場合の表示順を`@q`から`q@`に変更しました)

@koturn 👍。今週は急遽別件(pum)の作業したので来週以降作業する予定です。

**Comment by machakann** [comment]
ありがとうございます。パッチ試してみましたが、期待通りです (gvim on windows 10 64bit)。なにか気が付いたことがあればまたここに書きます。

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/2745

もし「何で要るねん？」とか言われたらフォローお願いします👍

**Comment by h-east** [comment]
https://github.com/vim/vim/pull/2745#issuecomment-375809184
Bram氏から返事があって、`recording()`と`executing()`とかの関数追加する方向になりました。
ただ、`executing()`は他に似たような関数(`executable()`, `execute()`)があるので、これらと並ぶとカオスになりそう。
prefix付けるなら、`reg_`か`register_`かな？
`register_recording()`
`register_executing()`

**Comment by machakann** [comment]
使うことを考えると関数追加の方がありがたい気がしてきました。

関数名は `register_recording()`, `register_executing()` に一票です。

**Comment by h-east** [comment]
`mode()`の変更をrevertして`register_recording()`と`register_executing()`を追加したのをpushしました。

**Comment by h-east** [comment]
todolisted.
> Patch to add reg_executing() and reg_recording(). (Hirohito Higashi, #2745)

https://github.com/vim/vim/commit/ab943431d8fcd856008a025b0e5652dd4b8007fc#diff-38d7929bd26d74d92ceddf984bbfc8dbR127

**Comment by h-east** [comment]
8.1.0020 で入りました。(API名は`reg_executing()`と`reg_recording()`)
https://github.com/vim/vim/commit/0b6d911e5de1a1c10a23d4c2ee1b0275c474a2dd
