### ISSUE TITLE
インサートモード補完ポップアップメニューの表示位置と幅がおかしい

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#1153]
## 再現手順 (on Linux via 端末(サイズ: 80x24))
- Vim のsrcディレクトリに移動する
  $ cd ~/(あなたの)/vim/src
- Vim起動
  $ vim --clean
以下、Vimで操作
```vim
i<Tab><Tab><Tab><Tab><Tab>sc<C-N>
```

## 現象
![popupmenu_ng](https://user-images.githubusercontent.com/518808/36338159-12a94eb2-13eb-11e8-8adf-648289e2143c.png)

- popupmenuの表示カラムがおかしい。
- 表示テキストがpopupmenuの幅を超えている。

## 確認環境
OS: fedora 26
Vim: 8.0.1521

## 備考
Vim 8.0.1491から発生する
`pumwidth`オプション追加で壊しちゃった感じ

**Comment by k-takata** [comment]
Related: vim/vim#2640

**Comment by h-east** [comment]
これで確認をお願いします。
https://gist.github.com/h-east/988fec74d24724662a51234b898ac171

今は、`FEAT_RIGHTLEFT` && `set rightleft`の場合の対応をやっています。

**Comment by h-east** [comment]
> 今は、FEAT_RIGHTLEFT && set rightleftの場合の対応をやっています。

対応完了。Gist更新 Rev.2。

**Comment by h-east** [comment]
Sent patch.
https://groups.google.com/d/msg/vim_dev/VwQb3Chhed4/24CENi4JAAAJ

**Comment by k-takata** [comment]
8.0.1522: https://github.com/vim/vim/commit/4287ed33ddc324d26dd05d3e19596dd74cf479d6
