### ISSUE TITLE
外部プログラムの補完に重複が生じうる

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#1154]
## 質問・報告の内容

`:terminal<Space><Tab>` と打つとファイル名補完が動作するようですが、要素が重複します。

![terminal_completion](https://user-images.githubusercontent.com/480049/36417290-7e22710a-1666-11e8-8ac2-2c8535c58464.png)

## Vimのバージョン

8.0.1525

## OSの種類/ディストリ/バージョン

*   Windows 10 Education 64bit

**Comment by mattn** [comment]
`%PATH%` に同じパスが複数入っているという事はないでしょうか。

**Comment by machakann** [comment]
`vim.exe` へのパス (`C:\Program Files\vim80`) が複数入っていたので、重複を除いて試しましたが同じ結果でした。

**Comment by mattn** [comment]
手元で

```
C:\>mkdir deadbeef
C:\>set PATH=c:\deadbeef;C:\DEADBEEF
C:\>c:\vim\vim.exe -u NONE -N
```

```
:set wildmenu
```

みたいな事をやってみましたが再現しませんでした。vim -u NONE で試して貰えますか。

**Comment by machakann** [comment]
> C:\>mkdir deadbeef
> C:\>set PATH=c:\deadbeef;C:\DEADBEEF
> C:\>c:\vim\vim.exe -u NONE -N
> 
> :set wildmenu

これを試してみたら重複しませんでした。

**Comment by machakann** [comment]
私の環境の問題のようなので閉じます。　`$PATH` の重複についてはもう少し調べてみます。ありがとうございました。

**Comment by machakann** [comment]
すいません、ちょっと試してもらいたいのですが、

> C:>mkdir deadbeef
> C:>set PATH=c:\deadbeef;C:\DEADBEEF
> C:>c:\vim\vim.exe -u NONE -N -c "set wildmenu"

これで起動した後、

`:terminal<Space>de<Tab>`

だと重複は出ませんが、

`:terminal<Space>C:\de<Tab>`

だと重複が現れます。これはそちらの手元で再現しないでしょうか？

**Comment by kuuote** [comment]
こちらの環境でもなるから少し調べてみたらex_docmd.c内でCMD_bangとCMD_terminalを特別扱いしてるのが原因みたいですね、恐らく重複する環境では!でもなるはずです

**Comment by machakann** [comment]
いま!を試してみたところ確かに重複しました。外部プログラムの補完で起こるということですね。

**Comment by mattn** [comment]
試してみました。terminal 関係なしに `:!c:\de` でも再現しますね。あと Windows だけじゃなく UNIX でも再現しました。

**Comment by ichizok** [comment]
`expand_shellcmd`
https://github.com/vim/vim/blob/master/src/ex_getln.c#L5169-L5227

絶対パスを補完する場合に、ここのloopが1回余分に回ってます。

あと、`:!.<TAB>` で補完候補に `./ ../` が `PATH` への登録数+1 表示されます。みっともない。

**Comment by ichizok** [comment]
同一名のコマンドが複数パスにある時も候補が重複するので、重複解消に hashtab を使った。
https://github.com/vim/vim/compare/master...ichizok:fix/expand_shellcmd.diff

このissueの解決だけなら以下でよいと思います。

```diff
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -5125,7 +5125,7 @@ expand_shellcmd(
 {
     char_u     *pat;
     int                i;
-    char_u     *path;
+    char_u     *path = NULL;
     int                mustfree = FALSE;
     garray_T    ga;
     char_u     *buf = alloc(MAXPATHL);
@@ -5147,15 +5147,14 @@ expand_shellcmd(

     flags |= EW_FILE | EW_EXEC | EW_SHELLCMD;

-    /* For an absolute name we don't use $PATH. */
-    if (mch_isFullName(pat))
-       path = (char_u *)" ";
-    else if ((pat[0] == '.' && (vim_ispathsep(pat[1])
-                           || (pat[1] == '.' && vim_ispathsep(pat[2])))))
+    if (pat[0] == '.' && (vim_ispathsep(pat[1])
+                           || (pat[1] == '.' && vim_ispathsep(pat[2]))))
        path = (char_u *)".";
     else
     {
-       path = vim_getenv((char_u *)"PATH", &mustfree);
+       /* For an absolute name we don't use $PATH. */
+       if (!mch_isFullName(pat))
+           path = vim_getenv((char_u *)"PATH", &mustfree);
        if (path == NULL)
            path = (char_u *)"";
     }
@@ -5178,9 +5177,6 @@ expand_shellcmd(
        else if (*s == '.')
            did_curdir = TRUE;

-       if (*s == ' ')
-           ++s;        /* Skip space used for absolute path name. */
-
 #if defined(MSWIN)
        e = vim_strchr(s, ';');
 #else
```

**Comment by machakann** [comment]
@ichizok  パッチありがとうございます。今、 `expand_shellcmd.diff` を試してみていますが、重複なく動いているようです。 (gvim 8.0.1591 on windows 10)

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2733
投げました。

**Comment by ichizok** [comment]
v8.1.0017
https://github.com/vim/vim/commit/62fe66f251263715968442e237742d9d3dfd5fa1
