### ISSUE TITLE
:tjump で一覧から選択してバッファに戻ったときにカーソルアイコンが戻らない

### ISSUE THREAD

**Issue by higemaniya** [vim-jp/issues#1156]
## 質問・報告の内容
時々、あれ？と思うことがあるので、細かいことですが報告させていただきます。

Windows 版 GVim (64bit) で、g CTRL-] (または :tjump) したとき、該当が複数あると
ジャンプ先の選択状態になります。このとき、マウスカーソルを動かすと赤い&#x1f6c7;になっています。

その後、どれかを選択してEnterするとリストが消え、マウスカーソルも消えますが、
マウスカーソルを動かすと赤い&#x1f6c7;のままになっています。操作は普通にできるようです。
そしてなにかの拍子に通常のポインタに戻ります。

## Vimのバージョン

8.0.1592 (https://github.com/vim/vim-win32-installer/releases/download/v8.0.1592/gvim_8.0.1592_x64.zip)

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.16299.248)

## 使用している or 関係していそうなプラグイン

gvim -u NONE -N で起動して確認しました

**Comment by mattn** [comment]
```diff
diff --git a/src/misc1.c b/src/misc1.c
index 135293dd2..725b3fc53 100644
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -3565,6 +3565,9 @@ get_number(
 	else if (c == CAR || c == NL || c == Ctrl_C || c == ESC)
 	    break;
     }
+#ifdef FEAT_MOUSE
+    setmouse();
+#endif
     --no_mapping;
     --allow_keys;
     return n;
```

ask_yesno 等では setmouse しているが get_number だけ無い。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/2709

**Comment by h-east** [comment]
GTK2-GNOMEで再現しました。でも、まっつんさんのpatchでは直らないですね。
```
:ver
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 26 2018 21:52:47)
Included patches: 1-1645
Compiled by h_east@localhost.localdomain
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
```

**Comment by h-east** [comment]
GTK2-GNOMEこれで直りました。
Windowsの方、patchの動作確認お願いします。
```patch
diff --git a/src/misc1.c b/src/misc1.c
index 135293dd2..812ca6acd 100644
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -3594,6 +3594,9 @@ prompt_for_number(int *mouse_used)
     cmdline_row = 0;
     save_State = State;
     State = ASKMORE;	/* prevents a screen update when using a timer */
+#ifdef FEAT_MOUSE
+    setmouse();
+#endif
 
     i = get_number(TRUE, mouse_used);
     if (KeyTyped)
@@ -3608,6 +3611,9 @@ prompt_for_number(int *mouse_used)
     else
 	cmdline_row = save_cmdline_row;
     State = save_State;
+#ifdef FEAT_MOUSE
+    setmouse();
+#endif
 
     return i;
 }
```

**Comment by h-east** [comment]
Windowsでも直っていることを確認したのでThreadにpatchを投げました。
https://groups.google.com/d/msg/vim_dev/GpWQRohxikU/BmbiYWdLFQAJ

**Comment by h-east** [comment]
Fixed by  [patch 8.0.1756](https://github.com/vim/vim/commit/73658317bacd9a0264dfaa32288de6ea1f236fe5)

@higemaniya 報告ありがとうございました:+1:

**Comment by h-east** [comment]
実は報告の症状は [patch 8.0.0722](https://github.com/vim/vim/commit/c9041079a199d753e73d3b242f21cc8db620179a) によるregressionにより起きていたもので、さらに私の書いた [patch 8.0.1756](https://github.com/vim/vim/commit/73658317bacd9a0264dfaa32288de6ea1f236fe5)でCUIと`set mouse=a`で`inputlist()`のマウス選択が出来なくなるというregressionが起きていました。。

新たにpatch送りました。
https://groups.google.com/d/msg/vim_dev/WY7QoL85sBM/OQZPIiZpAQAJ

**Comment by h-east** [comment]
8.1.0328 で一連のregressionが直りました。※但し、`:tjump`時のマウスの形状が:no_entry_sign:や:heavy_multiplication_x:にならなくなっちゃった。
https://github.com/vim/vim/commit/4cbdf155ca7bb6fbdab2d5acafae5fc712fca8b8

あとさらに関連バグが報告されています。
https://github.com/vim/vim/issues/3239#issuecomment-416072335
これは一連のregression前から起きていたものなのですが、最初のregression(8.0.0722)で起きないように蓋されてしまって、今回の8.1.0328でまともになったので発見されてしまったパターンのやつです。

**Comment by h-east** [comment]
関連バグ(起動オプション`-c`で`inputlist()`を呼び出してマウス選択後にカーソル行のバッファとステータスラインにゴミが表示される on xfce4-terminalやxterm)も直りました。
8.1.0329
https://github.com/vim/vim/commit/a06afc7f5e7ba085abf1475a65ae3ea79c961a0e
これにて一件落着(たぶん)。

---
> ※但し、`:tjump`時のマウスの形状が:no_entry_sign:や:heavy_multiplication_x:にならなくなっちゃった。

これ、どなたかチャレンジしてみませんか？案外簡単かも
