### ISSUE TITLE
":autocmd TextChanged * FOO" 自体が TextChanged イベントを発生させる

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#1159]
## 質問・報告の内容

`vim -u NONE -N` で Vim を立ち上げた後、 `:au TextChanged * echom 'foo'`  を実行すると `foo` がすぐに表示されます。 `:au` コマンド自体が `TextChanged` を発生させているようです。実行の前後で `b:changedtick` は変わっていないのでおかしいように思います。

## Vimのバージョン

[8.0.1494 以降](https://github.com/vim/vim/commit/5a093437199001a0d60d8e18e2b9539b99a7757c)

## OSの種類/ディストリ/バージョン

*   Windows 10 Education 64bit
*   Archlinux 64bit

**Comment by machakann** [comment]
![issue1159](https://user-images.githubusercontent.com/480049/37564167-496a4a40-2acb-11e8-972f-0913fd0299fe.gif)

**Comment by h-east** [comment]
これで直ります。が自信なし。

All>
patchのレビューをお願いします。
https://gist.github.com/h-east/db4472b2e104ca79f6dce56974e791d4

**Comment by mattn** [comment]
@h-east ありがとうございます。vim -u NONE -N の場合は直ってる様に見えます。ただ(何が原因か分かってないですが)、`-u NONE -N` を付けない場合は初回の TextChanged が発火しない様です。

**Comment by h-east** [comment]
[patch 8.0.1494](https://github.com/vim/vim/commit/5a093437199001a0d60d8e18e2b9539b99a7757c#diff-803c5170888b8642f2a97e5e9423d399R1204)
バッファを作成した時点で`curbuf->b_last_changedtick`が0、`CHANGEDTICK(curbuf)`が2になっているため上記patchの判定部分で真になってしまい`TEXTCHANGED`イベントが発生しています。
対策としては、バッファ生成時に`curbuf->b_last_changedtick = CHANGEDTICK(curbuf)`してやればいいんじゃないかと考えました。

**Comment by machakann** [comment]
`TextChanged` に自動コマンドを設定するプラグインが存在した場合、上の手順で再現しないみたいですね

**Comment by mattn** [comment]
```vim
au TextChanged * echom 'changed'
```

パッチを適用した後の動作です。

# vim -u NONE -N

起動後 `:so test.vim` を実行してテキストを変更 → changed

# vim (.vimrc は別ファイル名にしておく)

起動後 `:so test.vim` を実行してテキストを変更 → changed 出ない

**Comment by h-east** [comment]
私の環境(fedora 26)だとどちらもchanged出ますね。
> テキストを変更

これどうやってます？私は`Yp`とやっています。

**Comment by mattn** [comment]
`iてきとう<ESC>` で確認しました。

**Comment by h-east** [comment]
それは`TextChangedI` ←I (Insert mode)での話なので`TextChanged`の対象にはならないです。

**Comment by mattn** [comment]
はい。ただ `-u NONE -N` と動作が違うのはなんででしょうかね。

**Comment by mattn** [comment]
たぶん本件とは別の問題なので別に issue 作りますね。

**Comment by mattn** [comment]
すいません #1159 は僕の勘違いでした。 @h-east OK ですのでテスト足して出して貰って良いですか。

**Comment by h-east** [comment]
test追加しました。(Rev. 2)
testこれでええんかな？(いちおうpatch前だとFaildになって、patch後だとSuccessにはなる)
https://gist.github.com/h-east/db4472b2e104ca79f6dce56974e791d4

**Comment by mattn** [comment]
LGTM

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/2742

**Comment by h-east** [comment]
[patch 8.0.1633](https://github.com/vim/vim/commit/8c64a36e40b8746404f7151abe6849393396af10)

@machakann issue登録ありがとうございました。

**Comment by machakann** [comment]
ありがとうございました！
