### ISSUE TITLE
カレントタブ以外に変更されたバッファがある場合に :qa するとカレントタブが変更されたバッファに切り替わる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#116]
kaneshinthさんのツイート
http://twitter.com/#!/kaneshinth/status/151913059672276992
- 対象OS:
  ALL
- 検証Ver:
  Vim　7.3.377 (on fedora linux), GVim 7.3.382 kaoriya(on Win7 64bit) 
- 手順:

`$ vim -N -u NONE -i NONE --noplugin a.txt`

``` vim
:tabedit b.txt                        " タブオープン(ファイル名 b.txt )
:tabedit c.txt                        " タブオープン(ファイル名 c.txt )
iちょんまげ<Esc>                        ” c.txt を編集(ちょんまげ と入力)
```

ここまでの操作でこうなる。
![](https://lh3.googleusercontent.com/-hhptyakRps0/TvrxIbi3HtI/AAAAAAAAAqg/n7g4DeOhH8M/w556-h99-k/vim_post_edit.png)

``` vim
:tabrew                                " カレントタブを1つ目のタブにする
:qa                                    " Vim終了(変更点のあるバッファがなければ)
```

c.txt は変更しているので以下のようにエラーが出る。(想定内)
![](https://lh3.googleusercontent.com/-D7OL5qnzxK0/TvrvQl1uLgI/AAAAAAAAApY/yRWMwEmjGRU/w757-h115-k/vim_qa.png)
そして何かキーを押すと1つ目のタブのバッファが c.txt に切り替わっている！(仕様？バグ？)
（内部で `:bmodified` が実行されているような動き）
![](https://lh6.googleusercontent.com/-pEDX2wPHz5c/TvrxIlvZFrI/AAAAAAAAAqk/WzYw2OWAfLw/w604-h99-k/vim_post_qa.png)
<br>
- 備考:

タブを使わないパターンでも同じような動作になります

`$ vim -N -u NONE -i NONE --noplugin a.txt b.txt c.txt`

``` vim
:set hidden
:last
iおしくらMJ<Esc>
:rew
:qa
```

（エラーメッセージ表示後、1つ目のバッファが c.txt に切り替わる）

※同じ事をjvim3で試したら切り替わらなかったので、どっかで仕様変更になったかもしくはバグなのかどっちでしょうね？

**Comment by koron** [comment]
終了時に未変更のhiddenバッファを前面に出す、ってのはユーザビリティを考えれば納得の動作。

しかしタブを絡めた場合、現在のタブが開いているバッファが変更されるってのは不自然でキモイ。
一般的なユーザ感覚では「未保存のバッファを持ったタブに移動して表示する」のが自然だと思われる。

おそらくタブは内部的にhiddenを使って実装している。このこと(hiddenが前面に来る)をタブ実装時に考慮し忘れたんだと推測。
もしくは時系列的には逆で、タブ実装後にhiddenが前に来るようになったか。
(このあたりは @ynkdir さんが正確なことを突っ込んでくれそうな予感w)

**Comment by ynkdir** [comment]
hiddenはこれですかね

```
version5.txt:
":q!" does not exit when there are changed buffers which are hidden.  Use
":qa!" to exit anyway.
```

**Comment by koron** [comment]
++@ynkdir !

**Comment by ynkdir** [comment]
ウィンドウの場合は
未保存のバッファを開いているウィンドウがあればそのウィンドウに移動する (同じタブページ内)
ということをやっているので、タブページそうしたいとリクエストすれば入れてくれる気がします。

**Comment by h-east** [comment]
ご意見、情報ありがとうございます。

タブ以外での :qa の挙動については現状のままで問題なくて、
タブ使用時はお二人の意見に賛成です。

> 一般的なユーザ感覚では「未保存のバッファを持ったタブに移動して表示する」のが自然だと思われる。

<br>
あと、タブ関連のコマンドで提案です。
- `:tabs` でも hidden なバッファを表示してはどうか？ （`:buffers` のような感じで）
- `:buffers` にタブページ番号を表示するようにしてはどうか？<br>
  もしくは `:buffers` の指定タブ限定版コマンドを追加してはどうか？<br>
  (例) `:tabbuffers` [N]<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;タブページ[N](デフォルト: カレントタブ)内の全バッファを表示する。

**Comment by h-east** [comment]
:qa 時に「未保存のバッファを持ったタブ&バッファに移動する」patch

``` diff
diff -r a96cb758a8d7 src/ex_cmds2.c
--- a/src/ex_cmds2.c    Fri Dec 23 14:56:28 2011 +0100
+++ b/src/ex_cmds2.c    Thu Dec 29 04:20:16 2011 +0900
@@ -1580,6 +1580,7 @@
     buf_T      *buf;
     int                save;
 #ifdef FEAT_WINDOWS
+    tabpage_T  *tp;
     win_T      *wp;
 #endif

@@ -1635,10 +1636,10 @@
 #ifdef FEAT_WINDOWS
     /* Try to find a window that contains the buffer. */
     if (buf != curbuf)
-       for (wp = firstwin; wp != NULL; wp = wp->w_next)
+       FOR_ALL_TAB_WINDOWS(tp, wp)
            if (wp->w_buffer == buf)
            {
-               win_goto(wp);
+               goto_tabpage_win(tp, wp);
 # ifdef FEAT_AUTOCMD
                /* Paranoia: did autocms wipe out the buffer with changes? */
                if (!buf_valid(buf))
```

**Comment by h-east** [comment]
`:bmodified` の挙動は今のままで良いんじゃないかと思います。 **バッファ**コマンドなので。
ただ `:tab bmodified` ってやったら新しいタブを開いて欲しい気はする。（実装漏れ？？）

**Comment by tyru** [comment]
@h-east++

**Comment by ynkdir** [comment]
おつかれさまです。

FOR_ALL_TAB_WINDOWS() のループを break で抜けようとしてますがこのマクロは二重の for 文になるので抜けれてないです。
念のため。
まあ他の場所でも break を使ってるコードありますが…。
動作的には最初に見つかったのと最後に見つかったのとどっちを使うかの選択ですね。

対象の未保存バッファがカレントタブページ内 (の他のウィンドウ) にあっても他のタブページに移動してしまいます。
私的にはどっちでもいいんですが世間的にカレントタブページを優先した方がいいような気がします。

`:bmodified` をタブで開くのは `:tab sbmodified` になっちゃいますね。
`:tab` はウィンドウを作成するコマンドにしか効かないので。

**Comment by h-east** [comment]
@ynkdir 

> FOR_ALL_TAB_WINDOWS() のループを break で抜けようとしてますがこのマクロは二重の for 文になるので抜けれてないです。

わぉ！、まんまと引っかかってしまいましたorz。指摘ありがとうございます。
gotoに変更しました。

``` diff

diff -r a96cb758a8d7 src/ex_cmds2.c
--- a/src/ex_cmds2.c    Fri Dec 23 14:56:28 2011 +0100
+++ b/src/ex_cmds2.c    Thu Dec 29 19:02:55 2011 +0900
@@ -1580,6 +1580,7 @@
     buf_T      *buf;
     int                save;
 #ifdef FEAT_WINDOWS
+    tabpage_T  *tp;
     win_T      *wp;
 #endif

@@ -1635,17 +1636,18 @@
 #ifdef FEAT_WINDOWS
     /* Try to find a window that contains the buffer. */
     if (buf != curbuf)
-       for (wp = firstwin; wp != NULL; wp = wp->w_next)
+       FOR_ALL_TAB_WINDOWS(tp, wp)
            if (wp->w_buffer == buf)
            {
-               win_goto(wp);
+               goto_tabpage_win(tp, wp);
 # ifdef FEAT_AUTOCMD
                /* Paranoia: did autocms wipe out the buffer with changes? */
                if (!buf_valid(buf))
                    return TRUE;
 # endif
-               break;
+               goto buf_found;
            }
+buf_found:
 #endif

     /* Open the changed buffer in the current window. */
```

> `:bmodified` をタブで開くのは `:tab sbmodified` になっちゃいますね。
> `:tab` はウィンドウを作成するコマンドにしか効かないので。

なるほど！勉強になりました。ありがとうございます。

**Comment by h-east** [comment]
あ、このpatch不十分だ。
このpatchは未保存バッファの居るタブページ＆ウィンドウに移動するようにしただけ。
(複数ある)未保存バッファから１つ選択する処理がタブページに対応出来ていない。※1

現状は以下の優先順で未保存バッファを選んでいる。
1. カレントバッファ(==カレントウィンドウで表示されているバッファ)
2. バッファ管理リストループで最初に見つかったバッファ

これを以下の優先順で未保存バッファを１つ選ぶようにしないといけない。
1. カレントバッファ(==カレントウィンドウで表示されているバッファ)
2. カレントタブページ内のウィンドウで表示されているバッファ
3. 他のタブページ内のウィンドウで表示されているバッファ
4. hiddenなバッファ (この場合はカレントウィンドウのバッファをこのバッファにする)

※1
$ vim -N -u NONE -i NONE --noplugin -p a b c
:tablast
iCCC<Esc>
:tabrewind
:sp aa
iAA<Esc>
:wincmd w
:qa
でaaバッファに移動するべき

**Comment by h-east** [comment]
patch書きました。
https://gist.github.com/1808179
未保存のバッファがあれば、以下の優先順で探してカレントウィンドウをそこに移動します。
カレントウィンドウ＞カレントタブページ内ウィンドウ＞他のタブページのウィンドウ
hiddenバッファの場合はカレントウィンドウにそのバッファを表示。

<br>
PS
`:bmodified` `:sbmodified` も同様に対応した方が良いと思う。
誰かやらないか

**Comment by h-east** [comment]
> :bmodified :sbmodified も同様に対応した方が良いと思う。

あいやー、これらは現状の動作で問題ないんだった。
なのでさっきのpatchで問題なさそうならvim_devに送りつけます。
<br>
ところでIssueへラベルの付け外しが出来なくなってるんですがどこバグ？

**Comment by ynkdir** [comment]
簡単な動作確認のみしました。問題なしです。

**Comment by h-east** [comment]
@ynkdir Thanks!!
(コード書き終えて1発目のmake testで無限ループに入っちゃって、調べたら `:q!` `:qa!` で終われなくなってたのはヒミツｗｗ)

**Comment by h-east** [comment]
送った。
https://groups.google.com/d/topic/vim_dev/jMf4jOtsatw/discussion

**Comment by h-east** [comment]
todoリスト入り。

> Patch for improved ":qa" behavior. (Hirohito Higashi, 2012 Feb 18)

**Comment by h-east** [comment]
Patch 7.3.480 で入った！
https://groups.google.com/d/topic/vim_dev/7CITJ2g4BsM/discussion
