### ISSUE TITLE
インサートモードでの変更時に TextChanged (not TextChangedI) が発生する

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1160]
https://github.com/vim-jp/issues/issues/1159 より派生。理由があるなら close します。

#1159 のパッチを当てて(当てないと本来の動作でない為)、以下を実行

```vim
au TextChanged * echom 'changed'
```

パッチを適用した後の動作です。

(1) vim -u NONE -N

起動後 `:so test.vim` を実行してテキストを変更 → changed

(2) vim (.vimrc は別ファイル名にしておく)

起動後 `:so test.vim` を実行してテキストを変更 → changed 出ない

テキストの変更は `isomething<esc>` で行う。

**Comment by machakann** [comment]
Vim 8.0.1616 (#1159  パッチ済み) on Windows 10 64bit で再現しました。 

ついでに試してみたところ、 #1159 の原因と目されているコミットの一つ前の Vim 8.0.1493 (#1159  パッチ無し) でも再現します。

**Comment by machakann** [comment]
`matchparen.vim` の読み込みを止めるとどちらの場合も (1) の動作になります。

vimrc
```vim
let g:loaded_matchparen = 1
```

**Comment by mattn** [comment]
わかりました。その様ですね。

vim -u NONE -N は nocompatible なので matchparen.vim が読み込まれる → テキストの変更時に TextChangedI が発生し、同じトリガで changed が出てしまう。

vim (.vimrc なし) は compatible なので matchparen.vim が読み込まれない → changed は出ない

という事ですね。前者の方が発生して良いのか少しグレーですけど。

**Comment by mattn** [comment]
たぶん動作としては matchparen が TextChangedI,TextChanged で待っており、そのバブリングで TextChanged が誘発、changed という事だと思いますが、それだと TextChangedI だけバブリングして欲しい。

**Comment by mattn** [comment]
タイトル変えました。

**Comment by mattn** [comment]
あ、失礼しました。僕が誤解してました。ESC で戻ってるので TextChanged は発生しますね。

これは仕様ですね。
