### ISSUE TITLE
Vim script に複合代入演算子を追加したい

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1162]
現状は `+=` と `-=` だけしかない。

`*=`, `/=`, `%=` を追加してみました。

https://github.com/vim/vim/compare/master...ichizok:feature/compound-assignment-operators

**Comment by ujihisa** [comment]
期待

**Comment by ichizok** [comment]
PRed
https://github.com/vim/vim/pull/3931

**Comment by ichizok** [comment]
8.1.0902
https://github.com/vim/vim/commit/ff697e6cef8ced7717a21fd525ab3200b2f1724f
