### ISSUE TITLE
'runtimepath' に登録済みのパスに前方一致するパスが :packadd されない

### ISSUE THREAD

**Issue by fw** [vim-jp/issues#1165]
## 質問・報告の内容

※下記の確認は vim -u NONE の状態で行いました。

以下の構成のディレクトリがあったとします。

* ~/temp-vim-pack/pack/foo/opt/foo
* ~/temp-vim-pack/pack/foo/opt/fo

この状態で次のようにパッケージを登録していくと、

    :set packpath+=~/temp-vim-pack
    :packadd foo
    :packadd fo

エラーが出ずに完了しますが、 ~/temp-vim-pack/pack/foo/opt/fo が runtimepath に追加されません。

fo -> foo の順番に packadd すると両方とも追加されます。

    :packadd fo
    :packadd foo

途中のパスが違う場合も問題なく追加されます。

* ~/temp-vim-pack/pack/foo/opt/foo
* ~/temp-vim-pack/pack/zzz/opt/fo

    :packadd foo
    :packadd fo

start 以下に同様の項目を作った場合は追加されますが fo -> foo で処理されているからかもしれません。

* ~/temp-vim-pack/pack/foo/start/foo
* ~/temp-vim-pack/pack/foo/start/fo

## Vimのバージョン

8.0.1389

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (1709)

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/master/src/ex_cmds2.c#L3824
`strstr()` で判定しているため、対象パス文字列が既存パスの一部に含まれていると追加されないですね。

マッチ箇所の前後が delimiter (`,`) または文字列端であることを確認する。
https://github.com/vim/vim/compare/master...ichizok:fix/packadd.diff

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/2817

**Comment by ichizok** [comment]
8.0.1734
https://github.com/vim/vim/commit/f98a39ca57d001ba3e24831bae1e375790fb41f0
