### ISSUE TITLE
Vimのterminal内のcursesを使ったプログラム内でcursesのKEY_RESIZEイベントが取得できない

### ISSUE THREAD

**Issue by tsukkee** [vim-jp/issues#1166]
### 概要
Vimのterminal内でcursesを使ったプログラムを動かして、`CTRL-W_>`、`CTRL-W_<`、`CTRL-W_-`、`CTRL-W_+`などでterminalウィンドウのサイズを変えたとき、そのcursesを使ったプログラム内でcursesのKEY_RESIZEイベントが取得できない。

### 具体的に検証したこと
1. [cursesでKEY_RESIZEがとれているかだけを見るプログラム](https://gist.github.com/tsukkee/95aa071203eccb8656837887aac8f6c3)を使用(C版とPython版それぞれで検証)した。
2. 念のためターミナルはmacOSのTerminal.app、iTerm.app及びXQuarz.app上のxtermの3つの環境で検証した。
3. まず普通に1.のプログラムを動かす→ターミナルをリサイズする画面内に"!"が増えていく。
4. 次にVimのterminal内で1.のプログラムを動かしているとき、そのterminalウィンドウをリサイズしても"!"が表示されない。

### 期待する動作
Vimのterminal内でもcursesのKEY_RESIZEイベントが取得できること。

## Vimのバージョン
* 8.0.1800 (homebrewでインストールしたVim)
* 8.0.1633 (MacVim r146)

## OSの種類/ディストリ/バージョン
*  macOS High Sierra

## 使用している or 関係していそうなプラグイン
特になし。

## その他
Vimのterminalの中のVimはリサイズに対応できているように見えます。

(だいぶ前ですが)[Big Sky :: Vim の :terminal の中から外の Vim を操る方法](https://mattn.kaoriya.net/software/vim/20171219121032.htm "Big Sky :: Vim の :terminal の中から外の Vim を操る方法")で教えて頂いた方法でVimとrangerを連携してみようかと思っていますが、terminalウィンドウをリサイズするとrangerの表示が崩れてしまっているのを最近調べてみてここにたどり着いています。

**Comment by mattn** [comment]
手元で Windows から mintty でサーバにログインし、頂いた curses のプログラムを動かしてみました。

|操作                                                                                       |リサイズイベント|
|-------------------------------------------------------------------------------------------|----------------|
|直接実行して端末をリサイズ                                                                 |○              |
|tmux 上で実行して端末をリサイズ                                                            |○              |
|tmux 上で実行して tmux でリサイズ                                                          |○              |
|Vim の :terminal から実行して端末をリサイズ                                                |○              |
|Vim の :terminal から実行して <kbd>CTRL</kbd>-<kbd>w</kbd> <kbd>+</kbd>でウィンドウリサイズ|○              |

何れも問題無かったのですが、端末ソフトウェアの違いでしょうか？使っておられる端末ソフトウェアを教えて貰えますか。

**Comment by mattn** [comment]
>念のためターミナルはmacOSのTerminal.app、iTerm.app及びXQuarz.app上のxtermの3つの環境で検証した。

すみません。書いてありましたね。

**Comment by tsukkee** [comment]
早速ありがとうございます。
環境依存かも知れませんね。。。他のMacな方がどうなのか気になります。

https://github.com/vim/vim/issues/2798
ちゃんと読めていませんが、こちらも関係しそうな感じで報告者の方はMacユーザっぽいです。

**Comment by tsukkee** [comment]
あと、微妙に書ききれていませんが、MacVimをターミナル上ではなく、いわゆるGVimとして動かしたときもやはりダメです。

**Comment by mattn** [comment]
端末が SIGWINCH  を投げてるはずなんですけどね。もすこしピンポイントなコードを用意してみました。

```c
#include <unistd.h>
#include <stdio.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/ioctl.h>

void
signal_handler(int sig) {
  struct winsize ws;
  if (ioctl(0, TIOCGWINSZ, &ws) == 0)
    printf("cols=%d, rows=%d\n", ws.ws_col, ws.ws_row);
}

int
main() {
  signal(SIGWINCH, signal_handler);
  while(1) sleep(1);
}
```

**Comment by tsukkee** [comment]
あら、そちらのプログラムは動きました！
<img width="922" alt="sigwinch_on_vim_terminal" src="https://user-images.githubusercontent.com/9748/39827267-6fcd2608-53f2-11e8-9e5a-9d96940ae445.png">

**Comment by tsukkee** [comment]
今のところ分かったのは、SIGWINCH受けてioctl(TIOCGWINSZ)でウィンドウサイズ取るとこまでは動いてるようですが、cursesのKEY_RESIZEは発行されてない、というところです。

cursesは、ウィンドウサイズ取るところまでは大筋同じ処理で、その後前回取得時とウィンドウサイズが異なったらKEY_RESIZEを発行するような動きであり、この比較部分が何かしらうまく動いていないのかも知れません。デバッガなどでもう少し追ってみます。

**Comment by ichizok** [comment]
macOS (High Sierra) の ncurses は v5.7 ベースなんですが、このバージョンのウインドウサイズ取得処理 (`_nc_get_screensize`) は

1. 環境変数の `LINES`, `COLUMNS` を確認する。あればその値をウインドウサイズとする
2. 1 が存在しなければ `ioctl` を発行して WINSIZE を取得する

という流れになっていました。
通常、`LINES`, `COLUMNS` はシェル変数ですが環境変数ではないので 2. により正しい値が得られます。
Vim の `:terminal` は起動時に `LINES`, `COLUMNS` を環境変数として設定するため 1. の値が採用されますが、`LINES`, `COLUMNS` を変更するのはシェルなので子プロセス上では値が変化せず、従って子プロセスの curses はウインドウサイズ変更を検知できません。

`:terminal` で `unset LINES COLUMNS` してからプログラムを実行すると正しく動作することが確認できると思います。

**Comment by tsukkee** [comment]
macOS(というかXcode)についてくるncurses 5.7だと上記問題が発生し、ncursesの最新版と思われる6.1を持ってきて [cursesでKEY_RESIZEがとれているかだけを見るプログラムのC版](https://gist.github.com/tsukkee/95aa071203eccb8656837887aac8f6c3#file-curses_test-c)をビルドすると問題が発生しなくなりました。Python版についても、PythonはHomebrewでインストールしたもので、Homebrewは基本的にシステムにあるライブラリはそれを使うはずなので、おそらくncurses 5.7がリンクされているのだと思います。

差し当たって自分の目的からすると、何らかncurses 6.1がリンクされたPython作ってranger動かすのがWork aroundになりそうです。

**Comment by tsukkee** [comment]
すみません、 @ichizok さんのコメントを見ないで一つ前のコメント書いてしまいました。。。
そして、`unset LINES COLUMNS`で確かに期待通りの動作になりました！！ありがとうございました！

**Comment by ichizok** [comment]
一応書いておくと、macOSに限らず、古いncursesを使っている環境では同じ問題が発生すると思います。
