### ISSUE TITLE
statusline上でTerminal windowの行数を表示するとエラーが出る

### ISSUE THREAD

**Issue by ichitera** [vim-jp/issues#1167]
## 質問・報告の内容

statuslineにwindowの行数を表示するときに起こるエラーについて報告をします。
Terminal windowの行数が10000付近のとき、次が起こります。

1. エラーが出る (`E315: ml_get: invalid lnum 9846`) 
2. ~行数の表示が減る (10000の次に9001になる)~ (termwinscrollの期待通りの動作でした)
3. Terminal-Normal modeとTerminal-Job modeを行き来するたびに行数が増える

statuslineを表示する設定には次を使いました。
(以降の再現手順では`vimrc`というファイル名で参照します。)
```VimL
language C
let &statusline="%{printf('%d',line('$'))}"
```

再現手順は次のとおりです。

**1つめのエラーが出る手順:**

1. `vim.exe -u vimrc`を実行 (cmd.exe内で確認しました。)
2. `:term`を入力
3. `yes | head -n 9850` (terminalのwindow内で入力)
4. `<C-w>N`を入力
5. `a`を入力
6. `yes | head -n 9850` (terminalのwindow内で入力)
7. (エラーが出ます (`E315: ml_get: invalid lnum 数字`))

期待動作としては、7でエラーが表示されないものと思っています。

操作のキャプチャ:
![1](https://user-images.githubusercontent.com/31098747/39856431-eb24353a-546a-11e8-9a7f-8f4db32cbcbe.gif)

**~2つめの行数の表示が減る手順:~**
<details>
~
1. `vim.exe -u vimrc`を実行 (cmd.exe内で確認しました。)
2. `:term`を入力
3. `yes | head -n 10004` (terminalのwindow内で入力)
4. (statuslineには10000が表示されます。)
5. `<CR>`を入力
6. (statuslineには9001が表示されます。)

期待動作としては、6で10001が表示されるものと思っています。

操作のキャプチャ:
![2](https://user-images.githubusercontent.com/31098747/39856434-ed0cb48a-546a-11e8-83c8-f343a9e2dc5c.gif)

</details>
   
  
**3つめの行数が増える手順:**

1. `vim.exe -u vimrc`を実行 (cmd.exe内で確認しました。)
2. `:term`を入力
3. `yes | head -n 11000` (terminalのwindow内で入力)
4. (statuslineには9996が表示されます。)
5. `<C-w>N`を入力
6. `a`を入力
7. (statuslineには10010が表示されます。)
8. `<C-w>N`を入力
9. `a`を入力
10. (statuslineには10024が表示されます。)

期待動作としては、7, 10で4と同じ行数9996が表示されるのものと思っています。

操作のキャプチャ:
![3](https://user-images.githubusercontent.com/31098747/39856438-eef98cc8-546a-11e8-8339-b4037aacaf25.gif)

## Vimのバージョン

8.0.1806

## OSの種類/ディストリ/バージョン

(なるべく詳しく書いてください 記述例:)

*   Windows 10 Home 64bit (10.0.17134.48)

## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by mattn** [comment]
ありがとうございます。再現しました。

**Comment by mattn** [comment]
9850 という値から推測すると、terminal は通常のバッファと異なりスクロールバックの量(termwinscroll)しか行を持っていないにも関わらず行数はオフセットの値を保持する作りなので、その値で行を取りに行ってしまうとエラーになるという事だと推測します。

**Comment by mattn** [comment]
2回実行しなくても再現できそうですね。

set termwinscroll=100

で小さめに設定

yes | head -n 200

その後 <kbd>CTRL</kbd>-<kbd>w</kbd> <kbd>N</kbd> と <kbd>a</kbd> <kbd>CR</kbd> を繰り返し数回入力すると出ました。どうやら terminal normal mode に移る際に行がおかしくなるっぽいすね。

**Comment by ichitera** [comment]
ご確認ありがとうございます。
termwinscrollを小さめに設定する方法でも再現しました。

issue報告を訂正します。2つ目の項目は誤報告でした。
`termwinscroll`オプションを知らず、helpを見ると10000→9001行になるのは期待通りの動作ですね。

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/05c4a471d235987b914a9cc3ca44b98c46abd157

これで動作が変わってしまいましたね。エラーにならなくなりました。ただ、 terminal normal mode に移った際に一番上の行に移動してしまっていて、これはバグだと思うのでまだ issue は残しておきます。

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/4d6cd291cec668b991f2b43d76c6feab8b2e7d98

これで直った気がします。(報告も何もしてなかったですが)

**Comment by ichitera** [comment]
ありがとうございます。https://github.com/vim/vim/commit/4d6cd291cec668b991f2b43d76c6feab8b2e7d98 に更新したところ、エラーが起こらなくなりました。
解決されましたのでcloseいたします。
mattnさん、ありがとうございました。
