### ISSUE TITLE
'omnifunc' の第一引数 a:findstart の型に一貫性がない

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#1168]
### 確認方法

1. 以下の内容のファイルを保存し、 `:source` コマンドで読み込む

```vim
function! TestOmni(findstart, base) abort
  echomsg string([a:findstart, type(a:findstart) is# v:t_number])
  if a:findstart == 1
    return -1
  endif
  return []
endfunction
setlocal omnifunc=TestOmni
```

2. インサートモードに入り、 `<C-x><C-o>` と入力

3. ノーマルモードに戻り `:message` コマンドで出力を確認する

---

期待するのは

```
[1, 1]
[0, 1]
```

という出力ですが、実際には

```
['1', 0]
[0, 1]
```

と、一回目の呼び出しでは数字の `1` ではなく文字列の `'1'` が渡されています。 `:help complete-functions` では a:findstart が数値とは明言されていませんが、数値を期待するのが自然かと思います。また、少なくとも数値か文字列かどちらかに統一されている方がよいと思います。

## Vimのバージョン

8.1.10

## OSの種類/ディストリ/バージョン

*   Windows 10 Education 64bit (10.0.17134.48)

**Comment by koron** [comment]
最初に作ったときは数字の 1 のつもりで作りました。

どういう経緯で `"1"` になってしまったのかは謎。

**Comment by ichizok** [comment]
v7.3.614
https://github.com/vim/vim/commit/0cbba94b7e2575ba311d4eab316cc5528ffd5b67
多分ここから動作が変わった (number &rarr; string) のではないかと

**Comment by machakann** [comment]
`call_func_retnr()` の引数を `call_vim_function()` の仕様にあわせて増やす、という方法でどうでしょう？

https://gist.github.com/machakann/ef78414c6fd696ebc68987cfcd85ac77

**Comment by ichizok** [comment]
最初から `argv` を `typval_T` で渡した方がよさそう
https://github.com/vim/vim/compare/master...ichizok:fix/complfunc-args.diff

**Comment by machakann** [comment]
こっちのほうが根本的解決みたいですね。 @ichizok  さんのパッチでお願いします。

**Comment by ichizok** [comment]
PRed.
https://github.com/vim/vim/pull/2993

**Comment by ichizok** [comment]
v8.1.0053
https://github.com/vim/vim/commit/ffa9684150f5441e84d492e7184ef73587bd6c6c

**Comment by h-east** [comment]
8.1.0053
https://github.com/vim/vim/commit/ffa9684150f5441e84d492e7184ef73587bd6c6c
数値に統一。

動作上は問題ないけど、testdir/test_ins_complete.vim に足されたテストの`assert_equal()`の第1引数と第2引数逆ですね。
`{expected}, {actual}`が`{actual}, {expected}`になっている。:relaxed:

(追記: うぉー。被ったｗ)

**Comment by machakann** [comment]
ありがとうございました！

**Comment by ichizok** [comment]
@h-east ありがとうございます。追加で修正出しました
https://github.com/vim/vim/pull/2993#issuecomment-396812579

**Comment by h-east** [comment]
8.1.0055 👍 
https://github.com/vim/vim/commit/52d3aaeea4c85406f46e2051729e4f007f83b35e
