### ISSUE TITLE
:set guioptions+=! のとき v:shell_error が反映されない

### ISSUE THREAD

**Issue by Bakudankun** [vim-jp/issues#1169]
## 質問・報告の内容

`set guioptions+=!`とすると`:sh`や`:!`がGVimのterminalウィンドウ内で実行されるとのことで、試してみたのですが、これを指定するとコマンドの終了ステータスに関わらず`v:shell_error`の値が`0`になってしまいます。

外部コマンドを呼ぶプラグインが困るので、`guioptions`に`!`を含めないときと同様に終了ステータスを反映するようにしていただきたいです。

## Vimのバージョン

Vim+kaoriya 8.1.0005

## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit (10.0.17134.48)

**Comment by ichizok** [comment]
これでどうでしょうか
https://github.com/vim/vim/compare/master...ichizok:fix/go_terminal.diff

**Comment by Bakudankun** [comment]
↑のパッチで期待する動作になっていることを確認しました。

**Comment by ichizok** [comment]
PRed.
https://github.com/vim/vim/pull/2994

**Comment by ichizok** [comment]
8.1.0087
https://github.com/vim/vim/commit/f9c3883b11b33f0c548df5e949ba59fde74d3e7b
