### ISSUE TITLE
FOR_ALL_TAB_WINDOWS()とbreakの関係を検討する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#117]
#116 で @ynkdir さんが言ってる

> FOR_ALL_TAB_WINDOWS() のループを break で抜けようとしてますがこのマクロは二重の for 文になるので抜けれてないです。
> 念のため。
> まあ他の場所でも break を使ってるコードありますが…。

これって潜在的な問題ではなかろか? 要検討。

**Comment by koron** [comment]
擬似コードで書くとこんな感じ。

```
foreach (tab : tabs) {
    foreach (win : tab.windows) {
        break;
    }
    // Point A
}
```

で、 tabsのループを抜けらんなくて、最後のタブが操作対象になるんだろう。
でもこれって計算時間的にはかなりのムダじゃなかろうか。
FOR_ALL_TAB_WINDOWS()が上記のAで示した位置にコードを差し込めないのであれば
breakは常に意図しない動作になるということか。

**Comment by ynkdir** [comment]
aucmd_restbuf() の一ヶ所だけなのでタブ化時の直し忘れだと思いますけど
このてのマクロは間違えやすいですよねぇ…

**Comment by ynkdir** [comment]
直し忘れというより意図的に手を抜いてる可能性もありますが

**Comment by h-east** [comment]
aucmd_restbuf() [fileio.c : 8896]

``` c
if (wp == aucmd_win)
```

↑この条件に合致する wp は1つなので不正な処理がされることはなさそうです。
（条件合致以降もループするのは明らかに無駄ですけどね。）
<br>
一方、[#116のpatch](https://github.com/vim-jp/issues/issues/116#issuecomment-3299469)の場合は

``` c
if (wp->w_buffer == buf)
```

バッファでチェックしてます。バッファは別ウィンドウや別タブで多重に存在できるので、gotoでループを抜ける/抜けないとで処理結果が変わってしまって(ﾟдﾟ)ﾏｽﾞｰでした。

**Comment by koron** [comment]
無駄な処理があるのはVim的には非許容なはずなんで、なんらかの訂正をしたいですね。

**Comment by koron** [comment]
あ、ドキュメントで逃げるってのもありです。マクロの解説にそのことが書いてアレば別に構わない。

**Comment by h-east** [comment]
「FOR_ALL_TAB_WINDOWS()はbreak使っても2重ループは抜けられないです。1箇所修正したよ。それとマクロ定義のとこに注意書き追加したよ」
でvim_devに投げてみる。
コメントの英文添削よろしく。

``` diff
diff -r 9140571d01ab src/fileio.c
--- a/src/fileio.c  Mon Feb 06 00:13:22 2012 +0100
+++ b/src/fileio.c  Mon Feb 06 15:20:54 2012 +0900
@@ -8898,10 +8898,11 @@
            if (tp != curtab)
            goto_tabpage_tp(tp);
            win_goto(aucmd_win);
-           break;
+           goto win_found;
        }
        }
    }
+win_found:

    /* Remove the window and frame from the tree of frames. */
    (void)winframe_remove(curwin, &dummy, NULL);
diff -r 9140571d01ab src/globals.h
--- a/src/globals.h Mon Feb 06 00:13:22 2012 +0100
+++ b/src/globals.h Mon Feb 06 15:20:54 2012 +0900
@@ -535,6 +535,10 @@
 EXTERN win_T   *prevwin INIT(= NULL);  /* previous window */
 # define W_NEXT(wp) ((wp)->w_next)
 # define FOR_ALL_WINDOWS(wp) for (wp = firstwin; wp != NULL; wp = wp->w_next)
+/*
+ * When use this macro, You should NOT use 'break'. Should use 'goto'.
+ * 'break' can not escape the double for-loop.
+ */
 # define FOR_ALL_TAB_WINDOWS(tp, wp) \
     for ((tp) = first_tabpage; (tp) != NULL; (tp) = (tp)->tp_next) \
    for ((wp) = ((tp) == curtab) \
```

**Comment by h-east** [comment]
posted
https://groups.google.com/d/topic/vim_dev/ftLDxHhdDxg/discussion

**Comment by ynkdir** [comment]
おつです！

**Comment by h-east** [comment]
included Patch 7.3.437
https://groups.google.com/d/topic/vim_dev/wWGj67QRY58/discussion
