### ISSUE TITLE
MacVimで標準日本語IMの「Windows風のキー操作」を有効にすると<C-u>や<C-o>が効かなくなる

### ISSUE THREAD

**Issue by LeafCage** [vim-jp/issues#1171]
## 質問・報告の内容
すいません。MacVimのことをここで報告するのは間違っている感じがするのですが、日本語圏の話なのと日本語で報告したいのでここに報告させていただきます。

GUI版だけの現象です。
以下の記事の内容の通り、日本語IMの「Windows風のキー操作」を有効にすると `<C-u>` や `<C-o>` が効かなくなります。
[GPソフト Wiki - Yosemite/MacVimでトラブル](http://gpsoft.dip.jp/hiki/?Yosemite%2FMacVim%E3%81%A7%E3%83%88%E3%83%A9%E3%83%96%E3%83%AB)
日本語IMの `<C-u>` `<C-i>` `<C-o>` `<C-p>` のショートカットが有効になるためだと存じますが、なぜか `<C-i>` や `<C-p>` ではこの問題は生じないようです。

## Vimのバージョン
8.1 (2018 May 17 macOS version, Included patches: 1-39)
homebrew-cask で取得したものなので恐らくkaoriya版ではない。

## OSの種類/ディストリ/バージョン

*   macOS High Sierra (10.13.5)

**Comment by ichizok** [comment]
Ad hoc ですが、未確定文字列がない場合の Control キーとのコンビネーション入力は IM に送らないようにしてみました。
https://github.com/macvim-dev/macvim/compare/master...ichizok:fix/windows-like-shortcuts.diff

**Comment by ichizok** [comment]
[snapshot-152](https://github.com/macvim-dev/macvim/releases/tag/snapshot-152) で修正済み。
