### ISSUE TITLE
`:verbose set xxx?` でファイル名だけでなく行番号も欲しい

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/issues#1174]
## 質問・報告の内容

例: 手元のvimでfiletype=vim なファイルで `:verbose set iskeyword?` みると 

![](https://embed.gyazo.com/7c9957a52bf9b1e5b89b655db01ca2fc.png)

 こうなってたけどguardのどこかわからなくて不便

とりあえずファイル名だけでなく行番号も分かると便利

参考: `:h :verbose` はいまこんなかんじです

```
							*:verbose-cmd*
When 'verbose' is non-zero, listing the value of a Vim option or a key map or
an abbreviation or a user-defined function or a command or a highlight group
or an autocommand will also display where it was last defined.  If it was
defined manually then there will be no "Last set" message.  When it was
defined while executing a function, user command or autocommand, the script in
which it was defined is reported.
```

## Vimのバージョン

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:50:25)
Included patches: 1-22
```

## その他

単純に :verbose の出力文字列を変えてしまうと、それに依存したプラギンがあればそれを壊してしまうので、どうするのがいいかなあ。 (それに依存するのが行儀良いか悪いかというと、それ以外の手法がなさそうなので、依存してるプラギンは守りたいですよねえ)

**Comment by tyru** [comment]
すみません、ちょっとしばらく見れないです。
誰か他の方レビューお願いします。

2018年6月21日(木) 13:16 ujihisa <notifications@github.com>:

**Comment by h-east** [comment]
タイトル `xxx&` --> `xxx?` ？

**Comment by ujihisa** [comment]
おっと、thx!

**Comment by ujihisa** [comment]
無事手元のvimで、defaults.vim使うようにして `:verbose set incsearch?` すると

```
  incsearch
        Last set from /usr/share/vim/vim81/defaults.vim:55
```
が出るとこまでいきました!

diffこんなかんじです https://github.com/ujihisa/vim/pull/3

**Comment by ichizok** [comment]
8.1.0362 で実装されました。
https://github.com/vim/vim/commit/f29c1c6aa3f365c025890fab5fb9efbe88eb1761

```
:verbose set incsearch?
  incsearch
        Last set from /usr/share/vim/vim81/defaults.vim line 55
```
