### ISSUE TITLE
Python 3.7 に関する問題

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1175]
## `PySlice_GetIndicesEx`

https://docs.python.org/3/c-api/slice.html#c.PySlice_GetIndicesEx

関数としての `PySlice_GetIndicesEx` は3.7から deprecated になっており、マクロとして定義されている。

```
if_python3.c:170:10: warning: 'PySlice_GetIndicesEx' macro redefined [-Wmacro-redefined]
# define PySlice_GetIndicesEx py3_PySlice_GetIndicesEx
         ^
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/sliceobject.h:48:9: note: previous definition is here
#define PySlice_GetIndicesEx(slice, length, start, stop, step, slicelen) (  \
        ^
1 warning generated.
```

Patch: https://github.com/vim/vim/compare/master...ichizok:fix/python37.diff

## `imp` モジュール

https://docs.python.org/ja/3.7/library/warnings.html#default-warning-filter

3.7 から `DeprecationWarning` が (`__main__` で) デフォルト有効になったため、if_python3 の初期化処理内で `imp` モジュールをインポートする際に警告が出る。

https://github.com/vim/vim/blob/ad6480961080f80a455b2394f27b02935a2ded52/src/if_py_both.h#L6808

```
:py3 print('')
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

**Comment by h-east** [comment]
vim_devにもissueが立ってますね。vim_devの方が先に立ってそれで対応した感じかな。
https://github.com/vim/vim/issues/3117

**Comment by h-east** [comment]
@ichizok patch投げてみてはどうでしょう？

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/3153
とりあえず warning の件だけで投げました。

**Comment by h-east** [comment]
8.1.0147
https://github.com/vim/vim/commit/3b48b11c07b85520f4ca3566e92c3f6486509b72

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/3163
`imp` を `importlib` に置き換え

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/3163#issuecomment-403282934
`imp` は 3.4 から deprecated なので 3.4 から変えてしまう (`importlib` を使う) べきか。

**Comment by h-east** [comment]
今までのVimとPython 3.6までは`imp`でうまく動いていた実績があるので、`importlib`対応はPython 3.7以降で良いんじゃないでしょうか。(I think)

**Comment by methane** [comment]
PYTHONWARNINGS環境変数を設定して常にDeprecationWarningに気を使っているような
Python開発者がVimを起動したときは、 Python 3.6 以前でも問題になったと思います。

とはいえ、問題報告が上がってこなかったということは、DepreciationWarningはずっっと
無視され続けてきた 😢

**Comment by k-takata** [comment]
> PYTHONWARNINGS環境変数を設定して

具体的な設定例ありますか？
3.4でも同じ警告が出せるのであれば、3.4から対応した方がよいのではないかと思いました。

**Comment by methane** [comment]
`PYTHONWARNINGS=default`, なんですが、この環境変数を読むのは python
コマンドが使っているのと同じ Py_Main() を実行したときで、 vim の使い方だと
この環境変数は使われてなさそうでした。

Ubuntu 18.04 (Python 3.6.5) の vim でこの環境変数を設定しても `py3 print('')`
は警告なしで動きました。

**Comment by ichizok** [comment]
私としては @h-east さんと同じ考えなんですが、CI だと変更分がテストされない (Python 3.7 を使う環境がない) のが難点。

**Comment by ichizok** [comment]
関連: https://github.com/vim/vim/pull/3162

**Comment by ichizok** [comment]
8.0.0201 で `importlib` に置き換えられました。(Python >= 3.7)
https://github.com/vim/vim/commit/79a494d5e2f97c10e74f92ea529552623c314422

ただし、`import` の動作が変わったため Python 3.7 では test87 が NG になります。
https://github.com/vim/vim/pull/3162 が入れば修正されます。

**Comment by ichizok** [comment]
8.1.0247 https://github.com/vim/vim/pull/3162 がマージされました。
https://github.com/vim/vim/commit/447bd5a346b5c4bf4d91280700bdb4b45e0aa667
