### ISSUE TITLE
フォント選択の「スタイル」が `guifont` の直接指定では反映されない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#1177]
## 質問・報告の内容

https://ja.stackoverflow.com/q/45475/208 より

フォント選択の「スタイル」が `guifont` の直接指定では反映されない。

[源真ゴシック](http://jikasei.me/font/genshin/) のようなスタイルに
「標準」以外に「中」があるようなフォントをインストールして
(源真ゴシックでは最低限 Monospace-Medium と ...-Regularの2つをインストールする必要がある)
`:set gfn=*` を用いて「中」を選択する。

ここで `gfn` の値を確認すると以下のようになる。

```
:set gfn?
  guifont=源真ゴシック等幅_Medium:h11:cSHIFTJIS:qDRAFT
```

ここで `gfn` を同じ値で設定すると、Medium (中)ではなく
Regular (標準)相当のフォントである
`源真ゴシック等幅_Regular:h11:cSHIFTJIS:qDRAFT`
が選択されてしまう。
`gfn` の値は Medium になっている。

## Vimのバージョン

8.1.???

## OSの種類/ディストリ/バージョン

*   Windows

## その他

たぶん `gfn` の値から LOGFONT あたりを決めるロジックが機能しないケース。
(要確認)

**Comment by k-takata** [comment]
Same as vim/vim#1723 ?

**Comment by k-takata** [comment]
[8.1.1224](https://github.com/vim/vim/commit/f720d0a77e393990b2171a77210565bdc82064f2) で `:W400` などのようにウェイトを指定できるようになりました。
試してはいませんが、直ったと思われるので閉じます。
