### ISSUE TITLE
:cd []-[]が失敗する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#118]
本日発見したバグ？的挙動。

<pre>:cd `="[]-[]"`</pre>や、`:cd []-[]`を実行すると、

`E16: Invalid range`になります。
エスケープで回避できるか調べたのですが、`:cd \[]-\[]`も失敗してしまい、回避方法が分からず。
内部でexpand()しちゃっているんじゃないかなぁと予想しています。

Linuxで確認。おそらく、Windows他でも再現するはず。

**Comment by thinca** [comment]
`:cd []-[]` は確かにエラーが出ましたが、<pre>:cd `="[]-[]"`</pre> は問題なく成功しました。Linux です。

**Comment by Shougo** [comment]
んー、もう一度やってみました。
一回目は成功しますが、二回目失敗しますね。E16:が出ます。
ちょっとこの挙動がよく分かりません。
あと、vimshell#cd()が失敗します。vimshell#cd()は`=`を使っているので、
本来エスケープなしで動かないといけないはずです。

**Comment by thinca** [comment]
> 一回目は成功しますが、二回目失敗しますね。E16:が出ます。

それは単に cd が成功したので移動先のディレクトリがないだけではないですか。
存在しないディレクトリに対して `:cd` すると E16 がでるようです(何故かはわかりませんが)。

**Comment by mattn** [comment]
windowsですが、2回目出ませんね。
ちゃんとcd出来てます。

**Comment by mattn** [comment]
`:edit`を使ったスクリプトがエスケープもしくは``="[]-[]"``する必要がある様に、`:cd`も対応する必要があるかと思います。

**Comment by thinca** [comment]
色々試してみましたが、E16 が出るのはおかしい気がしますねぇ。
普段は出ないんですが、

```
$ cd '[]-[]'
$ vim
:cd non-exists-dir
```

みたいにカレントディレクトリが(詳しい条件はわかりませんが)アレの場合に E16 が出るっぽいです。
まあ元々 `:cd` できなくてエラー出るので実害はほぼないかとは思いますが。

**Comment by Shougo** [comment]
そのエラーなんですかね？
少なくともエラーメッセージ間違っていますよね。

> :editを使ったスクリプトがエスケープもしくは`="[]-[]"`する必要がある様に、:cdも対応する必要があるかと思います。

うーん、現在 `:cd \`={var}``というようになっているんですが、これではだめなのでしょうか？
editは問題なくできます。しかし、cdが動きません。

**Comment by Shougo** [comment]
<pre>
let hoge = "[]-[]"
cd `=hoge`
</pre>

あれ、これは動作した。なぜ、vimfilerのcdが失敗するんだろう。調べてみます。

**Comment by thinca** [comment]
私のところではそれは動いてます。

**Comment by ynkdir** [comment]
E16: Invalid range は /[z-a] と同じエラーかと思います。範囲指定が start < end になってない。

**Comment by mattn** [comment]
注意：このパッチは入れてはいけません

``` diff
diff -r a96cb758a8d7 src/fileio.c
--- a/src/fileio.c  Fri Dec 23 14:56:28 2011 +0100
+++ b/src/fileio.c  Thu Jan 05 19:29:49 2012 +0900
@@ -10124,6 +10124,8 @@
        case ',':
        case '{':
        case '}':
+       case '[':
+       case ']':
        case '~':
        size += 2;  /* extra backslash */
        break;
@@ -10251,6 +10253,14 @@
            *allow_dirs = TRUE;
        break;
 #endif
+       case '[':
+       reg_pat[i++] = '\\';
+       reg_pat[i++] = '[';
+       break;
+       case ']':
+       reg_pat[i++] = '\\';
+       reg_pat[i++] = ']';
+       break;
        case '{':
        reg_pat[i++] = '\\';
        reg_pat[i++] = '(';
```

これで動いてそげ。要人柱。

**Comment by ynkdir** [comment]
@mattn glob の [] が無効化されます。:edit fileio.[c] など。

**Comment by koron** [comment]
`]-[` で検索してんのコレ?

**Comment by mattn** [comment]
む... これいれると pathogen.vim がちゃんと動かなくなるな。どっちの問題かは不明。

**Comment by mattn** [comment]
@ynkdir あーそんなのもあるか

**Comment by Shougo** [comment]
えーっと、vimshellのcdの件は、こちらのミスです。
自分が使っていたオリジナルcdコマンドがexpand()にうまく対応していなかったため。
修正すると、動くようになりました。
だから、残る問題はエラーメッセージがおかしいことだけですね。

**Comment by thinca** [comment]
えーとつまり、E16 の原因は、`:cd` の際に引数にないカレントディレクトリ部分もワイルドカード(`:help wildcard`)として展開しようとしてしまっているってことですかね?
で、`]-[` と言うのは文字クラスの範囲として認識したけど、これは範囲として無効(ASCII的に `[` < `]` だから)、で、E16 が出る、言うこと?

**Comment by Shougo** [comment]
すみません、もう一つバグっぽい挙動を発見しました。
カレントディレクトリに[]-[]というパスが含まれる状態で、`finddir('.git')`をするとE16が出ます。

[]-[]というファイル名は、Vim的にかなりのトラップのようです。

**Comment by mattn** [comment]
原因は全て `file_pat_to_reg_pat()` な気がする。この関数はフルパスを求める際に使われていて`dos_expandpath()`から呼ばれる。この関数が `[]-[]` をどう表すか。

**Comment by ynkdir** [comment]
'path', 'cdpath' 関連なんですかね。

on linux

```
$ mkdir '[z-a]'
$ cd '[z-a]'
$ vim
:cd NOTEXIST
E16: Invalid range            <- error for [z-a]
E344: Can't find directory "NOTEXIST"  in cdpath
E472: Command failed
```

```
$ mkdir -p '**/xxx/yyy'
$ cd '**'
$ vim
:cd yyy
/path/to/**/xxx/yyy           <- cd succeeded
```

windowsだと :set isfname-=[ で E16 はでなくなりますね。解決にはなりませんが。

**Comment by ynkdir** [comment]
おっと、ディレクトリが存在しててもエラーでした。

```
$ mkdir -p '[z-a]/xxx'
$ cd '[z-a]'
$ vim
:cd xxx
E16: Invalid range            <- error for [z-a]
E344: Can't find directory "xxx"  in cdpath
E472: Command failed
```

**Comment by koron** [comment]
「どーでもいーこと」なんだけど、githubのNotificationsのタイトルが

> Re: が失敗する

になってるのはマークアップかなんかで潰れてるのかなぁ?

**Comment by thinca** [comment]
本当だ。githubのバグですかね。

**Comment by ynkdir** [comment]
バグレポート出します。

フラグ追加してexpandしないようにすればよさそうだけどよくわからないのでださない。

``` diff
diff -r a96cb758a8d7 src/misc2.c
--- a/src/misc2.c   Fri Dec 23 14:56:28 2011 +0100
+++ b/src/misc2.c   Wed Jan 11 00:18:59 2012 +0900
@@ -4265,6 +4265,7 @@
 #endif
      int           ffsc_find_what;
      int           ffsc_tagfile;
+     int           ffsc_is_literal;
 } ff_search_ctx_T;

 /* locally needed functions */
@@ -4500,6 +4501,8 @@
        && search_ctx->ffsc_start_dir[1] == ':')
        search_ctx->ffsc_start_dir[2] = NUL;
 #endif
+
+        search_ctx->ffsc_is_literal = TRUE;
     }

 #ifdef FEAT_PATH_EXTRA
@@ -4941,7 +4944,7 @@
         * Expand wildcards like "*" and "$VAR".
         * If the path is a URL don't try this.
         */
-       if (path_with_url(dirptrs[0]))
+       if (path_with_url(dirptrs[0]) || search_ctx->ffsc_is_literal)
        {
            stackp->ffs_filearray = (char_u **)
                          alloc((unsigned)sizeof(char *));
@@ -5609,6 +5612,7 @@
     search_ctx->ffsc_wc_path = NULL;
     search_ctx->ffsc_level = 0;
 #endif
+    search_ctx->ffsc_is_literal = FALSE;
 }

 #ifdef FEAT_PATH_EXTRA
```

**Comment by mattn** [comment]
ワークアラウンドになってしもた。

**Comment by ynkdir** [comment]
ヒィ、すみません。
なんか簡単ではないみたいですねぇ。

**Comment by mattn** [comment]
これ閉じた方がいいですか？

**Comment by ynkdir** [comment]
閉じていいんじゃないかと思います。閉じます。
