### ISSUE TITLE
hlsearchでハイライトされる範囲がおかしくなる

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#1182]
## 質問・報告の内容

hlsearchとincsearchが有効な状態(`:se hls is`)で
`:2,5s/hoge/fuga/`
のような範囲指定の置換などを実行するとハイライト範囲が2～5行になり、
その後`*`や`#`でカーソル位置の単語を検索しても、上記範囲外はハイライトされません。

例えば
```
abcdef
abcdef
abcdef
abcdef
abcdef
```
に対して`:2,5s/hoge/fuga/`を実行(マッチしないので置換は実行されない)。
カーソルが1行目の状態で`*`を入力しても、2~5行目のみハイライトされ1行目はハイライトされません。

## Vimのバージョン

8.1.0271

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit rs4

## 使用している or 関係していそうなプラグイン

`-u NONE -c "se hls is"`でも再現

## その他

v8.1.0271で:sや:g, :vでもincsearchが有効になったのが原因だと思います。

**Comment by nocd5** [comment]
incsearch終了のタイミングで
search_first_lineとsearch_last_lineを初期化してやると
ちゃんとハイライトされますが、これでよいのか…

```diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 7f748cb..302d161 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -293,10 +293,6 @@ do_incsearch_highlighting(int firstc, incsearch_state_T *is_state,
     if (!p_is || cmd_silent)
 	return FALSE;
 
-    // by default search all lines
-    search_first_line = 0;
-    search_last_line = MAXLNUM;
-
     if (firstc == '/' || firstc == '?')
 	return TRUE;
     if (firstc != ':')
@@ -597,6 +593,10 @@ may_do_incsearch_highlighting(
     if (i != 0)
 	curwin->w_cursor = end_pos;
 
+    // by default search all lines
+    search_first_line = 0;
+    search_last_line = MAXLNUM;
+
     msg_starthere();
     redrawcmdline();
     is_state->did_incsearch = TRUE;
```

**Comment by h-east** [comment]
@nocd5 issue登録&調査&patch作成Thanksです:+1:
incsearch終了時は`finish_incsearch_highlighting()`が呼ばれるのでそこに書くのが良いと思います。
報告のバグとは別に`:nohl`指定がなかった事になるバグを見つけたので合わせてpatchを書きました。
https://gist.github.com/h-east/c352e2d819c746e98f05e204b31450e0

問題なければ、testを追加してvim_devに送付します。(maybe 今晩)

**Comment by nocd5** [comment]
@h-east ありがとうございます。
[h-east/1182.patch](https://gist.github.com/h-east/c352e2d819c746e98f05e204b31450e0)で、この不具合が修正されること確認しました。

**Comment by h-east** [comment]
testを追加しました。
が、Test_incsearch_substitute_10が失敗するんです。
前のtest(〜_09)に影響されてるっぽい。09をコメントアウトすると通るし、09と10を手打ちで実行しても問題ないんです。

何か気付いたら教えてください。

**Comment by ichizok** [comment]
この部分を外すとテスト通りました。

```diff
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -293,10 +295,6 @@ do_incsearch_highlighting(int firstc, incsearch_state_T *is_state,
     if (!p_is || cmd_silent)
        return FALSE;

-    // by default search all lines
-    search_first_line = 0;
-    search_last_line = MAXLNUM;
-
     if (firstc == '/' || firstc == '?')
        return TRUE;
     if (firstc != ':')
```

**Comment by h-east** [comment]
@ichizok うぉー、ありがとThanks!!
今日帰るの遅いので土日に確認します。

**Comment by ichizok** [comment]
patch当てたVimで、

`vim --clean +'set incsearch hlsearch'`

sample.txt

```
foo 1
foo 2
foo 3
foo 4
```

上記内容のバッファに以下の操作をします（`[esc]` はescape key)

`:3,4s/\v[esc]gg*`
 
`:3,4s/` 直後の `\v` (検索パターン部分) を手打ちするかペーストするかで結果が変わります。

手打ち：`*` 入力で全ての `foo` がハイライトされる
ペースト：`*` 入力で 3,4行目の `foo` だけハイライトされる

このため、09 の後の 10 が失敗していました。

**Comment by ichizok** [comment]
`may_do_incsearch_highlighting()`
https://github.com/vim/vim/blob/f6ceaf1e058c64775fd46cbdb8962f5c19ef83e0/src/ex_getln.c#L467-L478
https://github.com/vim/vim/blob/f6ceaf1e058c64775fd46cbdb8962f5c19ef83e0/src/ex_getln.c#L602

`do_incsearch_highlighting()`
https://github.com/vim/vim/blob/f6ceaf1e058c64775fd46cbdb8962f5c19ef83e0/src/ex_getln.c#L370-L381

patch当てた状態で、

**検索パターン (`\v`) 手打ち:**

`\` 入力
&rarr; L467 `do_incsearch_highlighting()==TRUE`
&rarr; L474 `char_avail()==FALSE` 
&rarr; L602 `is_state->did_incsearch = TRUE;`

`v` 入力
&rarr; L370-L381 `empty==TRUE` (検索パターンが `\v` になるため)
&rarr; L467 `do_incsearch_highlighting()==FALSE`
&rarr; L469 `finish_incsearch_highlighting()`, `is_state->did_incsearch==TRUE` より `search_first_line` `search_last_line` クリア

**検索パターン (`\v`) ペースト:**

`\` 入力
&rarr; L467 `do_incsearch_highlighting()==TRUE`
&rarr; L474 `char_avail()==TRUE` (ペーストのため、次の `v` が available)
&rarr; L476-L477 で return し、`is_state->did_incsearch==FALSE` のまま

`v` 入力
&rarr; L370-L381 `empty==TRUE` (検索パターンが `\v` になるため)
&rarr; L467 `do_incsearch_highlighting()==FALSE`
&rarr; L469 `finish_incsearch_highlighting()`, `is_state->did_incsearch==FALSE` より `search_first_line` `search_last_line` クリアされない

**Comment by h-east** [comment]
@ichizok Thank you for commenting on politely.  I understand. 👍 

@nocd5 
> 報告のバグとは別に:nohl指定がなかった事になるバグを見つけたので合わせてpatchを書きました。

ごめん、これ気のせいでした。

ということでpatchを更新してvim_devに送付しました。
https://groups.google.com/d/msg/vim_dev/cF4nAlVVxAQ/H3RJ7PvMAQAJ

**Comment by h-east** [comment]
8.1.0339 👍 
https://github.com/vim/vim/commit/f13daa46da85a80dd05704cdde0660c2b2651a5a

**Comment by nocd5** [comment]
@h-east @ichizok ありがとうございました！
testについ何もできずすいませんでした。
