### ISSUE TITLE
ConPTY を叩く

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#1183]
叩き台は用意しました。
https://github.com/ntak/vim/commit/9bc87c56795a56a9c96632534025a3ff222ac317

現状 ++close が効かないのと Vim 内からの Vim 起動が一部変です。
winpty.dll の非存在がトリガなので、winpty.dll はパスの通らないどこかによけておいてください。

**Comment by ghost** [comment]
例の件は考えすぎておかしくなっていたという解釈でお願いします。申し訳ありませんでした。

**Comment by ghost** [comment]
https://github.com/vim-jp/issues/issues/1181
で無駄な改行が入る件は、Bram さんが拡張したと思われる ```^[]0;%s\a``` のシーケンスの ```\a``` が NL に変換されるのが原因でしたので、非表示文字 ```0x07``` に置換しています。
表示面で乱れなくなっただけで、内部的にどういうことになるのかはまだ追えていません。

**Comment by ghost** [comment]
ConPTY ターミナルを閉じると ```vgetc()``` が呼んだきり戻ってこないのが今の悩みどころです。
winpty ターミナルではちゃんと戻るんですよね…。

**Comment by ghost** [comment]
挙動としては ClosePseudoConsole() で ConPTY コンソールを閉じても ConPTY コンソールに繋がっているパイプ自体は閉じてくれないみたいです。PeekNamedPipe() で ERROR_*_PIPE が返ってこない、閉じる手段がないような。

とりあえず PeekNamedPipe の返値に頼らない方法を考えていく必要がありそうです。
あと STDERR の処置が MS の仕様にないんですが、これ将来どうするんでしょう。

**Comment by k-takata** [comment]
insiderは入れていないので、次のWin10が出てから試すつもりです…。
ConPTYを使うことで、256色対応と速度向上が期待できるのではないかと想像していますが、実際のところどうでしょう？(vim/vim#3427 で勝手に @ntak さんの名前を出してしまいましたが。)

> あと STDERR の処置が MS の仕様にないんですが、これ将来どうするんでしょう。

winptyはどうなってましたっけ。
stdout/stderrを端末につなぐかリダイレクトするかはシェル等の端末の中で動くプログラムが処理することで、ConPTYの出力に届いたデータはすべて表示するデータなのでは？

**Comment by k-takata** [comment]
> 挙動としては ClosePseudoConsole() で ConPTY コンソールを閉じても ConPTY コンソールに繋がっているパイプ自体は閉じてくれないみたいです。

もしかしたら、MSに報告・質問すべき事案かもしれませんね。

**Comment by k-takata** [comment]
> winpty.dll の非存在がトリガ

ConPTYの実装が安定したら、ConPTYの方を優先するようにしたいですね。（簡単に切り替えられる手段があるとデバッグ用には便利かもしれませんが。）

**Comment by ghost** [comment]
パイプを閉じてくれないのではないかという件、 PeekNamedPipe() の前に ClosePseudoConsole() が呼ばれていない可能性もないではないので、そのへんをもう少し追及します。

winpty は stdin/stdout/stderr の分で三本のパイプが提供されているように見えます。

**Comment by ghost** [comment]
取り急ぎ。ConPTY 側のパイプは閉じていました。失礼しました。あいかわらず慎重ではない自分がおります…。
となるとどこで ClosePseudoConsole() を呼ぶかですね、今はそこをやっつけています。

**Comment by ghost** [comment]
in ConPTY terminal:

![image](https://user-images.githubusercontent.com/25808039/45606496-900ab080-ba80-11e8-8b6d-da48000ed0c3.png)

色は出るんですがシーケンス処理でカーソルの横位置がシーケンスの長さ分だけ先に進んでいってしまう(?)ような感じなので必要のない改行が入りました。

あとは Vim 内で Vim の :terminal を実行したときにステータスバー？の色を別の色に変える処理をつなぎ変えるくらいかと思います。
STDERR の件はそういえばそうでした…。

**Comment by ghost** [comment]
名前が出てメール通知が来たのでそこからさらに気合入りました。オールオッケーです。

**Comment by k-takata** [comment]
おー、色が出てますね。

一応、いろいろと色を試してみたい人のために、256color2.pl をバッチファイルに移植したものや24bit色を使ったバッチファイルなどを
https://gist.github.com/k-takata/2d4f562bacf8bae6691973a540970117
に置いています。

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/25808039/45683074-5b305380-bb7d-11e8-996a-640813987842.png)

ヽ(´ー｀)ノよっしゃ！
あとは Vim 内からの Vim 起動をどうにかすれば持ち出せるかな？

**Comment by ghost** [comment]
https://github.com/ntak/vim/commit/f3e839644c1088ad4f84d773eee1daf932ab7bd2
に持ち出しました。
まだ問題はあって、
・ConPTY はおそらく cp932 もしくは cp0
・Vim 内で Vim を数珠に立ち上げると winpty では全インスタンスがルート Vim に所属していたが ConPTY ではそれぞれが独立してしまう
・Vim 内で立ち上げた Vim の .vimrc において set termencoding=(適正な値) をセットした後でないと set encoding= が通らない (内部エラー E950 になる)

PR 出して募ってみたらどうだろうかなという誘惑と
他人の時間は無限ではないのだという葛藤があります、もう少しコードをこねてみます。

**Comment by ghost** [comment]
ここに書いてあるコードページへの言及内容を信じなければならない…。
https://docs.microsoft.com/en-us/windows/console/pseudoconsoles

**Comment by ghost** [comment]
ConPTY での GetConsoleCP() がコードページとして 0 を返してくることがある意味識別方法なのか？
まあ cp932 だろうが UTF-8 だろうが放り込めば UTF-8 として出力するみたいな話のように読めるし、実際ある程度そんな動作だし、そこはまあ 0 でもいいのかもしれない。

**Comment by ghost** [comment]
いやむしろ SetConsoleCP() をどこに入れるのかという話か。ちょっと黙ります。

**Comment by ghost** [comment]
PR 出しました。
https://github.com/vim/vim/pull/3474
新機能たのしいヽ(´ー｀)ノたのしい。たのしかった三週間でした。

**Comment by ghost** [comment]
着手から PR まで一度も gVim をビルドしていなかった件(;´Д`)
gVim での ConPTY については情け容赦のない手詰まり感を頂いております。是の打ちどころなし。
VTP の有効化にはアクティブなコンソールウィンドウに接続された標準出力が必要なので、その仕様がどうにかならなければどうにもならないと思いました。

**Comment by ghost** [comment]
あっはい(;´Д`)
> What we announced in the associated blog post was a Pseudo Console, not a Pseudo Terminal/TTY.
https://github.com/Microsoft/console/issues/235

gVim からは撤収します。

**Comment by k-takata** [comment]
まだ全く実装を見ていないのですが、winptyを使った現行の実装と同じようにConPTYから受け取ったデータはlibvtermに渡しているのでしょうか？

**Comment by ghost** [comment]
えっ(;´Д`)
渡っている動作をしている気はします。いい色が出た画面もそのままバックスクロールできます。
というより、ConPTY がよくできているのか、私がしたことといえば ConPTY のオープンクローズ、あとは channel へのストリームの繋ぎ変えと微修正くらいだと感じてます。

**Comment by k-takata** [comment]
実装を見ていないので、gvimでダメというのが全然想像できていません…。

あと、ConPTYに対して、従来のConsole APIで色を付けたりカーソル位置を設定するとどういう情報が送られてくるのだろうというのが気になっています。

**Comment by ghost** [comment]
ConPTY は VTP (MS では VTE と言ってるアレ) の一部なので、標準出力のハンドルに対して利用フラグを立ててやらないと動作しないんですが、その標準出力のハンドルが「表示状態にあるコンソールウィンドウ」からしか持ってこれないんです。だから AllocConsole() でコンソールウィンドウを作って、そこから GetStdHandle() で標準出力を引っ張ってくる必要がありました。

AllocConsole() を使って gVim のウィンドウの背後にコンソールウィンドウを表示している状態であれば gVim でも ConPTY は動作しますが、この真っ黒なコンソールウィンドウはどうひねっても消せないんですね。SW_HIDE で消すと標準出力も消えるので、VTP の利用フラグが立てられないわけです。
何をしたかは PR の方に書いています。

旧 Console API で描画した情報ですが、ConPTY の全表示範囲をエスケープシーケンスだけで一面全部再描画して表示に至っているようです。状況によっては更新を目で追えます。

**Comment by k-takata** [comment]
> ConPTY は VTP (MS では VTE と言ってるアレ) の一部なので、標準出力のハンドルに対して利用フラグを立ててやらないと動作しないんですが

`CreatePseudoConsole()` を実行するプロセス自身がコンソールウィンドウを持っている必要があるということでしょうか？
ただ、不可視のコンソールウィンドウを使ってるのはwinptyも同じですよね。あれはwinpty-agentという別プロセスがあるからなんとかなってるのかな？

**Comment by ghost** [comment]
コンソールの設計上、まず VTE 利用フラグがあって、それを立てることで以降 VTE の機能が使えるという流れなんですが、利用フラグを立てるために必要な「いま画面に表示されているコンソールウィンドウに結び付けられた標準出力のハンドル」が非表示コンソールウィンドウからは取れないんです。

前段の gVim を撤収するきっかけにした issue の中で winpty のことを pseudo**terminal**、ConPTY は pseudo**console** と言い切っているので、ああそういうものなのかと浅く納得しているところです(深くは納得できていません)。

GUI プログラムで ConPTY を動作させるつもりで設計したのかを MS の方に issue を立てて聞いてみたい状況に心の中ではなっています。

**Comment by ghost** [comment]
```CreatePseudoConsole()``` の呼び元プロセスのアクティブなコンソールに VTE フラグを立てる必要があります。これが GUI アプリでできなくて悩んでいたわけです。

**Comment by mattn** [comment]
winpty も違う[ウィンドウステーション](https://msdn.microsoft.com/ja-jp/library/cc410716.aspx?f=255&MSPPError=-2147217396)で cmd.exe を起動して named pipe で繋いでるだけなので、実質隠しているのと同じです。

**Comment by ghost** [comment]
となるとウィンドウステーション A から手を出してウィンドウステーション B で起動した cmd.exe の標準出力をウィンドウステーション A に持ち込んで VTE フラグを立てた結果生成されるかもしれないウィンドウステーション A の ConPTY が gVim の channel にはめ込めるかという話になってきますけれど、書いててなんだこれって感じになってますね(今から追試します)。

**Comment by ghost** [comment]
追試終了。ウィンドウステーションをこねてみましたが進展はありません。
```CreateConsoleScreenBuffer()``` もコンソールがないのでエラーになります。

必要なのは「カレントプロセスに最初から備わっている、画面にいま実際に表示されているコンソールに最初から結び付けられている標準出力」で、回避策は**ありません**。カレントプロセスにそのようなコンソールが存在しなければ VTE フラグは立ちません。

最初から備わっていることにする API であるところの ```AllocConsole()``` のウィンドウが表示された状態なら ConPTY は gVim でも動作していい色を出します。

**Comment by ghost** [comment]
今読み返したらあきらかに変なテンションで書いてますね、すみません…。

**Comment by ghost** [comment]
gVim でもどうにか動きました。
別のウィンドウステーションに作った SW_HIDE でないコンソールウィンドウのプロセスIDを ```AttachConsole()``` したうえで CONOUT$ を ```freopen()``` して ```CreateFile()``` で HANDLE 化、それを ```SetStdHandle()``` し、そこに VTE フラグを立てました。

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/25808039/46093604-bb18a100-c1f2-11e8-8a1c-4656f09d270d.png)

ウィンドウステーションもなかなかたのしい機能でありますなヽ(´ー｀)ノ。

**Comment by ghost** [comment]
Vim内で :term vim からの :term をした時のステータスラインの色が変わる機能、どこでどうやってるのかを追ったら .vimrc 内の :set termguicolors が起点らしく、これの有無で発動が決まるところまではつきつめられたのですけれど、後がいけないわからない…

**Comment by ghost** [comment]
1809アップデート来ましたね(´ー｀)最新はこちら
https://github.com/ntak/vim/tree/conpty

**Comment by k-takata** [comment]
1809は入れたけど、新インストーラーの方をいじってるせいで、まだ試せてない…

**Comment by ghost** [comment]
conhost.exe がデッドロックするテストと winpty にカスタムされたテストをより分ける作業をしています。本当により分けていいものなのかを判断するために少し時間がかかっています…。

**Comment by ghost** [comment]
死ぬほどコードを読み進めたら一本フラグを立てるだけでよかったというオチがつきました。

ひとつ心残りなのが Vim 内で :term vim したときのステータスラインの色の変化、結局わかっていないのですけれど、どなたか知見がおありでしょうか？

**Comment by ghost** [comment]
色を変更するシーケンスであるところの OSC10; と OSC11; は ConPTY ではサポート外なのでステータスラインの色は変化させられない、という解釈でいいんでしょうかね、たぶん…。

**Comment by k-takata** [comment]
非常に残念ながら @ntak 氏がアカウントを削除してしまったため、パッチを取得することができなくなってしまいました。
"Please use this code freely." とのことでしたが、取得できない以上どうにもならないので、仕方なく手動でパッチを復元しておきました。
https://gist.github.com/k-takata/d743783c86fc80509b0b0b1d56582c5b
（私自身はまだ一切試していませんが…）

**Comment by k-takata** [comment]
> "Please use this code freely." とのことでしたが、取得できない以上どうにもならないので、仕方なく手動でパッチを復元しておきました。

手動ではなく機械的にパッチを復元できる方法があったことに気づきました。

```sh
# PR#3474 を conpty というローカルブランチ名で fetch
$ git fetch origin pull/3474/head:conpty
# master に対する差分確認
$ git diff master...conpty --stat -p
```

PRの内容は `pull/<PR番号>/head` という refspec で参照できるところがポイントです。

**Comment by ghost** [comment]
本当にすみません、追い詰められて三度目のダウンをしてしまいました。
何を言っても言い訳になるのですが、メンタル的にプログラマ向きではないのかなと思い知りました。

何がトリガだったかというと、Vim 内に作った ConPTY コンソールで特定の表示をさせると行が入れ替わるという症状で、これは MS のコンパイラであるところの cl.exe でヘルプ (/?) の表示の最終行付近の表示が粉砕されることで見てとれます。winpty では正常に表示されます。あ、こりゃ直せない → ダウン、と流れてしまいました。

ダウンしている最中もペースを落としていろいろ調べていましたが、原因をつきとめて修正することができたので後ほど issue に持ち出します。ConPTY とは関連がない場所の問題でした。

**Comment by h-east** [comment]
@ntak 私がvim_devでレスしたのをトリガーに振り切れた発言や行動したように取れました。
https://groups.google.com/d/msg/vim_dev/OiqbUTqVJ2E/ztt2r9lfBAAJ
この件にちゃんとコメントください。流石にこちらも辛いです。

**Comment by ghost** [comment]
その時点より少し前に vim_dev で私が書いた(あまり出来のよろしくない)パッチが Yegappan さんに丸ごと持っていかれてがっくり来てたところに wrong 扱いが颯爽とやってきて PC を窓から投げ捨てたくなったのはありましたけど、こちらも人間なのでそうなることもありますよね、というところです。

私は @h-east さんとはソリが合わないところが確かに少しあるんですが(vim-jpで私に対して強い発言をした最初の方ですし)、それはもう過去の話でしかないんで、これからもちょっとこすれ合うことがあるとは思いますが、こんな私が同じ部屋にいてもいいですか？大丈夫ならうれしいです。

**Comment by h-east** [comment]
> こちらも人間なのでそうなることもありますよね

それで済ますと何でもありになってしまいます。
多少のアフターフォローは必要かと思います。相手も人間ですから。

> こんな私が同じ部屋にいてもいいですか？

私にはそれを決める権限はありません。意見としてはノーコメントです。
前回再登場時以降はvim-jpでは会話していないと思います。
今回も必要最低限でいきます。
ですので、「レスする」≒「指摘」になってしまうことはご理解下さい。

**Comment by ghost** [comment]
娘はやらん！

とりあえず持ち出しました。
変数 termmode に 'winpty' か 'conpty' が入ります。
:terminal のオプションに ++winpty と ++conpty を追加しています。
https://github.com/vim/vim/compare/master...ntak:conpty

![image](https://user-images.githubusercontent.com/44701315/50726147-556e7600-114c-11e9-9167-a1b7fe4ff680.png)

**Comment by ghost** [comment]
:mksession で winpty/conpty の混合が起きないようにしました。

**Comment by ghost** [comment]
libvterm で ambiguous width が扱えないと ConPTY でコマンドラインに ambiguous width characters が入力できないという罠…★とか〇あたりがわかりやすいかと。

いや、できるのかもしれないんですが ambi の半ケツ判断ができないのがたぶんこれカーソル位置が libvterm の state に依存してる気がモリモリするわけですよ…。

**Comment by mattn** [comment]
libvterm が内部で使っている wcwidth は vim の関数を使うように修正されています。(僕がやった)
なのでその点に関して言えば内部処理内の不整合はないはず。

**Comment by mattn** [comment]
さらに言うとコマンドプロンプトの文字幅は仕様に依存するのではなくフォントに依存します。MSゴシックとラスターフォントで異なる幅の物があります。

**Comment by ghost** [comment]
文字幅じゃなくてカーソル位置の算出が…うーん、実証した方が早い、どう自分が間違ってるかの理解を進めたいので実装を進めます。

**Comment by mattn** [comment]
ラスターフォントで `┌a┐` を echo した結果です。

![image](https://user-images.githubusercontent.com/10111/50975275-8118a400-1530-11e9-80c9-f0c5c50e99fe.png)

**Comment by ghost** [comment]
いろいろとありがとうございます。結局のところ、単純には解決しそうにないのでドキュメントにその旨書いた版を作って PR にしました。
https://github.com/vim/vim/pull/3794

ambiguous 文字をバックスペースなりで２セル削除したいのに ConPTY から送られてくるシーケンスは１セル削除のものだったりして、どうにもごまかしきれませんでした。
コードページ値が 0 なので、そのへんが影響しているのかとは思います。
でもたしか 0 はインドだった気がするんで、ConPTY の動作が将来変わるかもしれないです。

**Comment by mattn** [comment]
Windows が将来的な物の為になんかやってそうではあります。

https://twitter.com/espresso3389/status/1076588142113611776

**Comment by ghost** [comment]
MS は何を仕込んでるんだろう…

gVim 対応の一連の流れは、API 実装側から見ればなにやってんの状態だったわけで、ばっさり削除できた今となってはどうにも恥ずかしい限りです。いやはや…

**Comment by ghost** [comment]
数々のご協力本当にありがとうございましたヽ(´ー｀)ノ。

あとはMS側の動きがあってから微調整します。以下二件。
https://github.com/Microsoft/console/issues/347
https://github.com/Microsoft/console/issues/359

**Comment by mattn** [comment]
そろそろ MS の人達も新しい cmd.exe が結構ボロボロな事に気付いてくれてるかもですね。

**Comment by k-takata** [comment]
Link: [8.1.0870](https://github.com/vim/vim/commit/aa5df7e3127dff6b7336df0903f5c569a40eb174)

**Comment by ghost** [comment]
ambiguous width の処理がまだ全然できてないのにクローズされてしまったからまた突っ込まねば…

**Comment by ghost** [comment]
chcp で 0 を返す動作はバグだったそうで、今は正確な値が返ってきます。

ところで、２セル占有文字の左１セルだけ 0x20 で消すと右１セルってどうなるのが正解でしたっけ？今の最新 Insider の ConPTY がその動作を修正として出してきてるんですが、まあこれも突っ込みますけれど、実際今の os_win32.c の mch_write ドライバでは ambiwidth=double が再現できてませんで…

**Comment by mattn** [comment]
コマンドプロンプト、いろいろバグがありますね。まぁとりあえずバグの為の実装を vim に入れるのだけは避けたいですね。いずれ直った時に vim も直さないといけなくなりますし、そこでユーザ間で差異が発生してしまいますし。

**Comment by ghost** [comment]
アッアッ(´ー｀)libvtermのとwinptyのとConPTYのとそれぞれのバグ対応を計三か所ほど入れてしまっております…

libvterm: https://github.com/vim/vim/blob/v8.1.0885/src/channel.c#L1758-L1774
winpty: https://github.com/vim/vim/blob/v8.1.0885/src/terminal.c#L2703-L2705
ConPTY: https://github.com/vim/vim/blob/v8.1.0885/src/option.c#L3676-L3681

modern vtp でスクロールリージョンの左右マージンが有効であればいいなと思って Vim 側に実装したら今は無効でした。どこまで VT をサポートしてるのか全部試せないのでそうなりました。残念！

**Comment by ghost** [comment]
振りました。
https://github.com/Microsoft/console/issues/370

まずカーソルキーでカーソルが動かないので、どこでどう完成したとみなしたのかが謎です。

**Comment by mattn** [comment]
https://github.com/vim-jp/issues/issues/1183#issuecomment-462125048

これ Fall creators update あたりから壊れてるのでもしよろしければこれも報告して貰っていいですか？
![screenshot](https://user-images.githubusercontent.com/10111/52535985-3a6cd280-2d98-11e9-97a2-902f4589d309.gif)

**Comment by ghost** [comment]
Win10 1809 で再現しました。
次期 Win10 1903 では同じ手順で再現できませんでした。修正されているものと思われます。

**Comment by mattn** [comment]
まじですか。ずっとバグってて早くなおらないかなと思ってたので嬉しい。

**Comment by k-takata** [comment]
32bit Vimでクラッシュするのを修正 https://github.com/vim/vim/pull/3943

**Comment by ghost** [comment]
修正ありがとうございます。MSDN は話半分で見るべきでした。
64bit だと全引数がレジスタに割り当てられる感じでスタックの問題は表面化しなかったと…

今は aibmguous width でのバックスペース処理のシーケンス不足と、カーソルの消去シーケンスが無視されることの二件が修正待ちになっています。非 CJK 環境での ambi は完成しているんですが、そのへんの処理に関する今の MSKK との力関係はどうなってるんだろうと思わなくもないです。

**Comment by k-takata** [comment]
[8.1.0900](https://github.com/vim/vim/commit/48773f1f83e666c49b9d88ea6a392d50215ca013) で取り込まれました。

ところで、terminal.c の dyn_conpty_init() の中で、has_vtp_working() の結果を見て ConPTY が使用可能かどうかを判定していますが、これは間違っているのではないでしょうか。vim.exe の場合、Win10 1703 以降で has_vtp_working() が TRUE を返しますが、このバージョンでは ConPTY は動きません。

**Comment by ghost** [comment]
ご指摘ありがとうございます。いろいろ混同していました。

has_conpty_working() が欲しいところですね、というとこの先 has_*_working が小宇宙を形成すると思われるので、複数のフラグを一関数にまとめる方向で今この瞬間は考えています。

**Comment by k-takata** [comment]
has_conpty_working() なパッチを https://github.com/vim/vim/pull/3946#issuecomment-463027244 との組み合わせで準備中です。

**Comment by ghost** [comment]
ありがとうございます　ヽ(´ー｀)ノ　両手をあげて♪
なんだかいろいろ報われた感じがしてきました。

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/3949
is_conpty_stable() という関数も用意して、次のWin10が出たら `CONPTY_STABLE_BUILD` を正しく定義し直すという方針。

**Comment by ghost** [comment]
本当にありがとうございます、涙が浮いたのは本当です。
Skip ahead が通った Win10 pro も確保しているので、おいおい挑戦していきます。

ところで、コンソールウィンドウの拡大縮小(マウスホイール)は ConPTY の一部なんですかね…
コンソールウィンドウ全体が内部の体裁を保ったまま非クライアント領域も巻き込んで大きくなったり小さくなったりします(フォントサイズだけ変更されるイメージ)。別 issue にするようかなとも…。

**Comment by k-takata** [comment]
8.1.0909: https://github.com/vim/vim/commit/d9ef1b8d77f304c83241f807c17ffa26c9033778

**Comment by ghost** [comment]
遅れましたが、ありがとうございました。
ちょっと根を詰めて ConPTY が落ちる原因を探してまして、四日間？消費しました。
別件ですが、ウィンドウサイズのパッチでは連名が通らず、すみません…

ConPTY の ambiwidth の件、どうやってもカーソルが半角右にズレるわりに、MS の issue に work item をつけてもらえないのが、どうしたらわかってもらえるかなあと試行を重ねています。

**Comment by k-takata** [comment]
> 別件ですが、ウィンドウサイズのパッチでは連名が通らず、すみません…

version8.txt には追加してもらえることになったので問題ありません。

> ConPTY の ambiwidth の件、

私がコメントを付けるまで、ConPTYの話だと分かってもらえてなかったようですが…。
cp932で問題が起きるとか、そのあたりの基本的なことは伝わっているのでしょうか。

**Comment by k-takata** [comment]
https://github.com/Microsoft/console/issues/347 で直ったのは GetACP() が 0 を返す点だけですか？

**Comment by ghost** [comment]
「すべて直っている」と判断しなければならないようです。追加機能はおそらく望めません。

現状の ConPTY では、バックスペースキーで文字を消すとき、Ambiguous width が１セルの環境でも２セルの環境でも「バックスぺース、スペース、バックスペース」を発行しているんですが、つまり「バックスペースで消したい文字のセル幅に見合った処理」を全部ユーザ側に丸投げしてるわけでして、

残念ながら、絵文字の ZWJ (zero width joiner) で繋いだ各要素をバックスペースで一要素ずつ「剥がしていく」処理のことを考えると、現状の仕様が正しいように思えます。

絵文字、ハングル、デーヴァナーガリーなどなど全部扱えるようにしていかなければならないので、なんかとんでもなくたのしいものに手を突っ込んでしまったなあとは思います。

**Comment by mattn** [comment]
👨‍👩‍👦‍👦 バックスペースを押すごとに1人ずつ減っていくわけですね。楽しそうですね。(棒)

**Comment by k-takata** [comment]
> 現状の ConPTY では、バックスペースキーで文字を消すとき、Ambiguous width が１セルの環境でも２セルの環境でも「バックスぺース、スペース、バックスペース」を発行しているんですが、

普通の全角文字はどうなっているんですか？

**Comment by k-takata** [comment]
> 「すべて直っている」と判断しなければならないようです。追加機能はおそらく望めません。

何をもってそう判断しましたか？ 少なくとも普通のコマンドプロンプトと同じように動かないものはバグとして修正してもらうべきでしょう。
普通のコマンドプロンプトでは絵文字もZWJもちゃんと扱えないので、ConPTYでも1要素ずつ削除されるのは仕方ないでしょうが、Ambiguous widthは普通に動くのですから、ConPTYでも同様に動くべきです。

**Comment by ghost** [comment]
通常の CP932 での全角文字をバックスペースで消すときに ConPTY が出すシーケンスは、「カーソルを２セル左に(^[[y;xH)、(0x20)、(0x20)、カーソルを２セル左に(^[[y;xH)」です。これは合ってると思いますし、os_win32.c のテキストハンドリングでも動作します。

winpty だとバックスぺースが来るとカーソルの左側までを画面左端にいったんカーソルを移動してから再描画しているので、何の心配もなかったんですよね…。

で、ConPTY のレンダラとしての WSL コンソールについてはまだ未検証なので、そちらでも ambiwidth  的な一連の問題が出たら再度 MS の issue (reopenしました)で突っ込みます。

本来的にはユーザが書いた既存のレンダラで完全動作させるのがOSベンダの筋だと思うんですけれど…。どうなんでしょうねこのへん、自分も不具合として修正をかけてほしいですが、うーん…

**Comment by k-takata** [comment]
> 「カーソルを２セル左に(^[[y;xH)、(0x20)、(0x20)、カーソルを２セル左に(^[[y;xH)」です。

ambiwidthを全角幅で表示するときも同じ動作になるべきだと思いますけどね。

**Comment by ghost** [comment]
WSL でも全然ダメですね(;´Д`)さてどっから突っ込んでくれようか…筋道は立てねばならぬ…

**Comment by ghost** [comment]
Windows のシステムロケールが ConPTY に対して cmd.exe のようには反映されていない理由を聞くところから入ってみますか…

ambiwidth が２セル固定で構わない環境はおそらく東部アジアでは CJKV だけの特殊環境なので(他の国では１～ｎセルが混在)、そこを「MS でわかってるんだから MS で対処してほしい」と押せるかどうかという視点もありですね。

(前略)つーかそもそもイタリックも表示でき(中略)コンソールを強化したところで(以下省略)

**Comment by ghost** [comment]
絵文字にしても１セル～３セルの幅があるからなあ…screen.c の最長不倒関数との闘いがいま始まる…
家族を表示してバックスペースで一人ずつ剥がせるようにするための見立てがたのしい(;´Д`)たのしい。

**Comment by ghost** [comment]
ambiwidth=double 的に仮動作できるところまで持っていきました。
:term から立ち上げた Vim の中での ambiguous character の扱いがまだ確定していません。
https://github.com/ntak/vim-1/tree/control_ambiwidth

現状の Insider に合わせているので、次期 Win10 が出たらまた調整するようになるとは思います。

**Comment by mattn** [comment]
https://github.com/vim/vim/commit/08aac3c6192f0103cb87e280270a32b50e653be1 も入ったし情報が古いので一旦閉じます。
