### ISSUE TITLE
`has('patch-8.1')` と `has('patch-8.1.0')` が常に 0 を返す

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1184]
## 質問・報告の内容

8.1 以降の Vim で `has('patch-8.1')` と `has('patch-8.1.0')` が常に 0 を返します。
`has('patch-8.1.1')` など 0 より大きい場合はちゃんと 1 を返しました。

vim-jp slack で @ichizok さんにもらったコメントによると 0 かどうかで回しているからだそうです。

```c
has_patch(int n)
{
    int         i;

    for (i = 0; included_patches[i] != 0; ++i)
        if (included_patches[i] == n)
            return TRUE;
    return FALSE;
}
```

## Vimのバージョン

8.1.366

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.17134)

**Comment by h-east** [comment]
@tyru Issue登録Thanksです。
`has('patch-8.1')`はフォーマットが違うので`0`を返すのは仕様通りだと思います。
`has('patch-8.1.0')`が`0`なのはバグですね。

```patch
diff --git a/src/version.c b/src/version.c
index 95fa7dae3..f351ec8ae 100644
--- a/src/version.c
+++ b/src/version.c
@@ -1568,9 +1568,11 @@ highest_patch(void)
     int
 has_patch(int n)
 {
-    int		i;
+    int		i, len;
 
-    for (i = 0; included_patches[i] != 0; ++i)
+    len = (int)(sizeof included_patches / sizeof included_patches[0]);
+
+    for (i = 0; i < len; ++i)
 	if (included_patches[i] == n)
 	    return TRUE;
     return FALSE;
```
後でtest足します。

**Comment by h-east** [comment]
Sent to vim_dev
https://groups.google.com/d/msg/vim_dev/xjxbMGrJSvo/I3BaVCm2CAAJ

**Comment by h-east** [comment]
以下、Tonyさんから (意訳)
8.1 の patch 0 というものはないよ。最初のpatchは `1` だ。
だから、`has('patch-8.1.0')`は0を返すんだ。
もし、8.2になったら `has('patch-8.1.0')`は1を返すよ。(旧バージョンのpatch levelは管理していないので？)
8.1以降か確認したければ以下を使おう。
`if v:version >= 801`

確かに。

**Comment by h-east** [comment]
@tyru and All : patch取り下げで良いですか？

**Comment by tyru** [comment]
うーんまぁ通常メジャーバージョンのチェックは `version` を見るものの、
`has()` でメジャーマイナー両方確認できた方が統一感あるかと思ったんですが、
has-patch はパッチの有無を調べるものというのも確かなので、反論しづらいですね…  (なので vim_dev じゃなくここで言ってる)
とりあえず納得したので自分は大丈夫です。

**Comment by h-east** [comment]
了解です。ということでpatch取り下げました。
このIsuueも閉じますね。

**Comment by k-takata** [comment]
うーむ、本当にこんな仕様でいいんですか？
8.1 に patch 0000 が存在しないのはそんなの当たり前ですが、`has('patch-8.1.0')` でそんな当たり前のことをチェックしたい人なんてどこにいるんでしょう？

（本当に現状の仕様を維持するのなら、ドキュメントに明記すべきだと思います。）

**Comment by k-takata** [comment]
Bramからも反対意見が出たか…
https://groups.google.com/d/msg/vim_dev/xjxbMGrJSvo/p4ijNdESCAAJ

**Comment by h-east** [comment]
`has('patch-8.1.0')`が何を返すべきかについては意見はありません(どちらでも良いです)

どちらにしてもドキュメントに明記すべきなのは同意です。
