### ISSUE TITLE
外部プログラムをフィルタに使うと文字化けになる

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1186]
## 質問・報告の内容
皆さんのお知恵をいただきたく投稿しすます

> $ grep -v "^\\"" ~/.vim/vimrc

`set fileencodings=iso-2022-jp,cp932,sjis,euc-jp,utf-8 "ファイル・エンコードの自動判定優先順位`

という設定で、
> $ vim

で普通に起動します

その後バッファに
> 時代

とだけ記述します
その後、
`:%!cat`
等外部プログラムでフィルタをかけると
> 譎ゆｻ｣

と文字化け状態になってしまいます
なおここでは「結果が変化しないはず」ということでcatを使っていますが、sedなどで実際に置換されるような組み合わせでで実行しても同じです
予め
> 時代

と UTF-8 で記述しておいたファイルを開くと、文字コードの誤判定で
> 譎る俣

となってしまうので、
`:edit ++enc=utf8`
として開き直し、同じく
`:%!cat`
とすると、今度は開き直す前の
> 譎る俣

になります

どちらにしても、設定が上記のとおりなので、外部フィルタに渡すデータの段階で、fileencodings による文字コード判定の結果、間違った文字コードとしてデータが渡されている結果だともうのですが、こういったことが起きない何か旨い方法ないでしょうか?
素人考えですが、
- 常に fileencoding に従うデータとして渡す
- 新規作成時などで、fileencoding 指定がなければデフォルトの何かを指定できる

といった方法が有れば良いと思うのですが

## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
> 適用済パッチ: 1-1453
## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic
> $ uname -a
> Linux naonari 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
## 使用している or 関係していそうなプラグイン
なし

**Comment by h-east** [comment]
```
set fencs=utf-8
```
とだけ書いた.vimrcだとutf-8一択なので化けないです。
けど、ファイル・エンコードの自動判定は出来ないとダメなのですよね？

ソース見てませんが`:%!`がバグってるかもしれないですね。

**Comment by mattn** [comment]
fileencodings で cp932 よりも後ろに utf-8 があるからかと思います。

2018年9月18日(火) 21:22 h_east <notifications@github.com>:

**Comment by h-east** [comment]
@mattn 

[kaoriya版](https://github.com/koron/vim-kaoriya/blob/master/kaoriya/vim/plugins/kaoriya/encode_japan.vim#L32)や以下のサイトでもcp932 よりも後ろに utf-8 がありますね。
http://www.kawaz.jp/pukiwiki/?vim#p0799eb6
ついでに私のSD誌7月号の記事でもそうです。

**Comment by mattn** [comment]
シフトJISは結構広いのです。

上位バイト 0x81～0x9f、 0xe0～0xef 
下位バイト 0x40～0x7e、 0x80～0xfc 
0xa1～0xdf  半角カタカナ

また UTF-8 の領域は以下になります。

U＋0000～ U＋007F | 0xxxxxxx（00～7F）
-- | --
U＋0080～ U＋07FF | 110xxxxx 10xxxxxx（C2～DF）⁠（⁠80～BF）
U＋0800～ U＋FFFF | 1110xxxx 10xxxxxx 10xxxxxx（E0～EF）⁠（⁠80～BF）⁠（⁠80～BF）
U＋10000～U＋10FFFF | 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx（F0～F7）（⁠80～BF）（⁠80～BF）（⁠80～BF）

例えば「あa」という文字列はバイト列で言うと

e3 81 82 61

ですが上記の cp932 のバイト列に収まってしまうので utf-8 なシェル上で

```
$ echo あa | iconv -f cp932 -t utf-8
縺Ｂ
```
とやっても iconv の終了コードは 0 になります。とはいってもこれ確率の話になります。僕は utf-8 を前に持ってくる派ですが、普段 Shift_JIS を扱う方が多い人は cp932 を前に持ってくる方が失敗が少なくなります。

**Comment by mattn** [comment]
ちなみに UTF-8 の `時代` は

e6 99 82 e4 bb a3

なので同様に正しく変換されて `譎ゆｻ｣` という文字列になります。ですのでこれは仕様です。

**Comment by h-east** [comment]
Linuxでenc=utf-8の人はfencsはcp932はutf-8より後にした方が確率的に幸福度が上がるということですね。(utf-8なファイルを扱うことが圧倒的に多い人にとって)

**Comment by mattn** [comment]
@yoshinaga-hiroyuki

```
set fileencodings=utf-8,iso-2022-jp,euc-jp,cp932
```
でしばらく使ってみて下さい。

**Comment by iranoan** [comment]
fileencodingsの順で確認して外部プログラムに渡すというのは仕様なんですね
自分で書く分はともかく、ひとから受け取る分を考えると、設定をどうするか悩ましいですね

取り敢えず、fileencodingsは変えないで、よく使うフィルタに関しては、
1. 一時的にfileencodingsをutf-8
2. フィルタ処理
3. fileencodingsを元に戻す

を関数化して対処することにします

本題から離れてしまいますが、この機会にお聞きしたいことが有ります
なぜこういった仕様になっているのでしょう?
素人考えですが、外部プログラムへは
1. fileencodingsではなくfileencodingで渡す
2. fileencodingが空ならencoding

で十分な気がするのですが…
「十分」が言いすぎだとしても、今の「表示された状態と別のコードで外部に渡されることが在り得る」は解り難いと思います

「人が目視で確認しないで、スクリプトで一括処理する」場合を考慮してなのでしょうか?
だとしても、誤認識が起きるので、あまり意味がない気がしますし…

このあたり、現在の仕様に至った経緯などご存じの方いらっしゃれば、ご教授頂ければ幸いです

**Comment by mattn** [comment]
> 本題から離れてしまいますが、この機会にお聞きしたいことが有ります
> なぜこういった仕様になっているのでしょう?
> 素人考えですが、外部プログラムへは
> 
> fileencodingsではなくfileencodingで渡す
> fileencodingが空ならencoding
> で十分な気がするのですが…
> 「十分」が言いすぎだとしても、今の「表示された状態と別のコードで外部に渡されることが在り得る」は解り難いと思います

Windows では未だに CUI が cp932 だったり utf-8 だったりします。例えば OS 標準の find コマンドは Vim の grepprog として使われていますが、このコマンドの出力は cp932 です。かたや最近の msys2/cygwin は utf-8 で扱えます。誤爆したくないという方は fileencodings を複数設定せずに運用するべきです。
また UNIX においても euc-jp が使われなくなったのもそんなに昔でもないですし、未だに euc-jp で運用されておられる方もいます。さらにその中には euc-jp だけれども vim の encoding は utf-8 という方もいらっしゃいます。

> 「人が目視で確認しないで、スクリプトで一括処理する」場合を考慮してなのでしょうか?
> だとしても、誤認識が起きるので、あまり意味がない気がしますし…

すみません、この部分の意味が良く分かりませんでした。

**Comment by iranoan** [comment]
納得です
フィルタとなるプログラムに渡す点だけ考えて、帰ってくる=受け取る時の事を考えていませんでした
どんなプログラムで処理されるか分からないので、fileencodingsを使って自動判定を活かすしか無いですね
