### ISSUE TITLE
大文字のマークの消し方

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1187]
## 質問・報告の内容
```mA```
等で付けた大文字のマークを削除するにはどうすれば良いでしょう?
```:delmarks A```
で消えたように見えるのですが、vim を再起動すると復活しています
末尾に動作確認動画を付けました(何度かタイプミスしていますが😅)

~/.viminfo に記録しないようにしては、delmarks を使っていなくてもファイル閉じたら消えますよね

## Vimのバージョン
> $ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
適用済パッチ: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux naonari 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## 使用している or 関係していそうなプラグイン
一旦 ~/.vim/vimrc を全てコメントアウトしても同じ
![vim-mark](https://user-images.githubusercontent.com/24851657/46254545-07eac900-c4cc-11e8-8cf6-b7d0c28ad1ae.gif)

**Comment by h-east** [comment]
`:delmarks A`の後、
```
:wviminfo! | rviminfo
```

すれば消えますね。
普通に考えたら `:wviminfo!` だけで良いような気もしますが、、ちょっとソース見てみます。

**Comment by iranoan** [comment]
私の環境では
```:wviminfo!```
だけで消えるっぽいですが、とにかく消し方が解って良かったです
どうもありがとうございました

**Comment by h-east** [comment]
私の環境でも `:wviminfo!` だけで消えました。
あれ？何だったんだろう。私の勘違いということで:sweat:

**Comment by k-takata** [comment]
[8.2.0050](https://github.com/vim/vim/commit/8cd6cd8087ccf08e4303dbf5f732fc4b82b917e1) でタイムスタンプを見るようになり、`delmarks A` だけで消えるようになった模様。
