### ISSUE TITLE
vim-markで文字列マーク時にエラーが表示される。

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1188]
## 質問・報告の内容
vim初心者です。
プラグインvim-markで文字列をマークしたときに、下記のメッセージが表示されます。
function mark#MarkCurrentWord[13]..mark#DoMark の処理中にエラーが検出されました:

メッセージが表示されたあと、マーク自体は正しく実行されます。
エラーメッセージが気になるので、できれば解決したいです。

vim-markは以下のものです。
https://github.com/inkarkat/vim-mark

## Vimのバージョン
VIM - Vi IMproved 8.1
KaoriyaのGVIMを使っています。

## OSの種類/ディストリ/バージョン
*   Windows 10 Home 64bit

## 使用している or 関係していそうなプラグイン
以下が全てです。
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'
NeoBundle 'inkarkat/vim-mark'

**Comment by ichizok** [comment]
[README](https://github.com/inkarkat/vim-mark/blob/master/README.md) によると [vim-ingo-library](https://github.com/inkarkat/vim-ingo-library) プラグインが必要なようです。
インストールしてみてください。

**Comment by h-east** [comment]
Vimプラグインの問題はそのプラグインにissueを立てて聞いた方が良いかもです。

https://github.com/inkarkat/vim-mark#dependencies に

- Requires the ingo-library.vim plugin ([vimscript #4433](http://www.vim.org/scripts/script.php?script_id=4433)), version 1.035 or higher.

とあるので、それを入れてください。

(追記: あっ、被った。しかも17分も先に書き込まれてたorz)

**Comment by hiro-github** [comment]
ichizokさん、h-eastさん

ご指定のプラグインを導入することで解決しました！ありがとうございます！
今後プラグインのissueもみて解決方法をさがしていきます。
