### ISSUE TITLE
packpathに$HOME/vimfilesを設定した場合と$HOME/aを設定した場合でpackadd実行後のrtpが異なる

### ISSUE THREAD

**Issue by rapan931** [vim-jp/issues#1189]
## 質問・報告の内容

vimrc
``` vim
set packpath=$HOME\a
packadd vim-go
```

vim起動

``` 
vim -Nu NONE -S c:\Users\username\_vimrc
```

私の環境ではD:\vim74が$VIMRUNTIMEです。
(現在vim8.1を使っていますが、ディレクトリは過去からの使い回しのためディレクトリ名はvim74です)

:set rtpの結果
```
C:\Users\username/vimfiles,D:\vim74/vimfiles,D:\vim74,D:\vim74/vimfiles/after,C:\Users\username/vimfiles/after,C:\Users\username\a\pack\m\opt\vim-go
```

vimrcで`set packpath=$HOME\vimfiles`を指定した場合には以下になっていました。
```
C:\Users\username/vimfiles,C:\Users\username\vimfiles\pack\m\opt\vim-go,D:\vim74/vimfiles,D:\vim74,D:\vim74/vimfiles/after,C:\Users\username/vimfiles/after
```

動作として #1022 と似ています。
期待値はプラグイン側のftplugin/*.vimが使われるよう、packaddで追加したパスが$VIMRUNTIMEより先にくることだと思います。

## Vimのバージョン

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 23 2018 22:02:43)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-325

## OSの種類/ディストリ/バージョン

*   Windows 7 Professional 64bit

## 使用している or 関係していそうなプラグイン

vim-goを使用しましたが他のpluginでも発生すると思われます。

## その他

ご確認宜しくお願いいたします。

**Comment by h-east** [comment]
まず、`set packpath=$HOME\a`で
`C:\Users\username\a\pack\m\opt\vim-go`が他の`after`ディレクトリよりも後ろに追加されるのは、[8.1.0353](https://github.com/vim/vim/commit/99396d4cbf78d313a454c7448acc07412d2e45b7)で修正されたと思います。
それ以外は、仕様通りだと思います。
今日は眠いので明日に根拠を書くかもしれません。

**Comment by h-east** [comment]
Linuxの場合で説明します。(Windowsの方は`$HOME/.vim`を`$HOME/vimfiles`に読み替えてください)
- `$HOME/.vim/pack/my/opt/` と `$HOME/a/pack/my/opt/` に `vim-go`をインストール済み。

### packpath=$HOME/.vim の場合

pp_vimrc1
```
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set packpath=$HOME/.vim
packadd! vim-go
```

```
$ vim -Nu pp_vimrc1 foo.go
```

'rtp' はデフォルトで `~/.vim`が1つ目にあるので、`packadd`時にその後ろに足される。
```
:set rtp
  runtimepath=~/.vim,~/.vim/pack/my/opt/vim-go,~/samba/github/vim/vimfiles,~/samba/github/vim/runtime,~/samba/github/vim/vimfiles/after,~/.vim/after
```

なのでpackageの`ftplugin/go.vim`が先に読まれる。
```
:filter @ftplugin/go\.vim@ scriptnames
 25: ~/.vim/pack/my/opt/vim-go/ftplugin/go.vim
 32: ~/samba/github/vim/runtime/ftplugin/go.vim
```

---

### packpath=$HOME/a の場合

pp_vimrc2
```
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set packpath=$HOME/a
packadd! vim-go
```

```
$ vim -Nu pp_vimrc2 foo.go
```

'rtp' に`~/a`がないので、`packadd`時に `after` の前に足される
```
:set rtp
  runtimepath=~/.vim,~/samba/github/vim/vimfiles,~/samba/github/vim/runtime,~/a/pack/my/opt/vim-go,~/samba/github/vim/vimfiles/after,~/.vim/after
```

なので$VIMRUNTIMEの`ftplugin/go.vim`が先に読まれる。
```
:filter @ftplugin/go\.vim@ scriptnames
 25: ~/samba/github/vim/runtime/ftplugin/go.vim
 26: ~/a/pack/my/opt/vim-go/ftplugin/go.vim
```

---

### 結論

これは仕様だと思います。
「'rtp' に追加時はパスが途中まで一致したやつの直後に追加される」という動作がドキュメントに見つからないですが、、

ですので、`packpath`を(`rtp`にも含まれない)デフォルト値以外の値にする時には、`exec "set rtp^=" . &packpath`等として、`rtp` にもその値を含ませてあげる必要があるのではないでしょうか。($VIMRUNTIMEよりも前に設定するのがポイント:+1:)

pp_vimrc3
```
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set packpath=$HOME/a
exec "set rtp^=" . &packpath
packadd! vim-go
```

```
$ vim -Nu pp_vimrc3 foo.go
```
```
:set rtp
  runtimepath=~/a,~/a/pack/my/opt/vim-go,~/.vim,~/samba/github/vim/vimfiles,~/samba/github/vim/runtime,~/samba/github/vim/vimfiles/after,~/.vim/after
```
```
:filter @ftplugin/go\.vim@ scriptnames
 25: ~/a/pack/your/opt/vim-go/ftplugin/go.vim
 32: ~/samba/github/vim/runtime/ftplugin/go.vim
```
なのでpackageの`ftplugin/go.vim`が先に読まれる。

**Comment by rapan931** [comment]
@h-east 確認ありがとうございます。

> これは仕様だと思います。

承知しました。

> ですので、packpathを(rtpにも含まれない)デフォルト値以外の値にする時には、exec "set rtp^=" . &packpath等として、rtp にもその値を含ませてあげる必要があるのではないでしょうか。($VIMRUNTIMEよりも前に設定するのがポイント)

自分の会社環境だとファイルのチェッカーが動いている関係で$HOME配下にvimfilesを置けないので
rtpの文字列を操作して回避するようにします。

> C:\Users\username\a\pack\m\opt\vim-goが他のafterディレクトリよりも後ろに追加されるのは、8.1.0353で修正されたと思います。

こちらについても情報ありがとうございます！
(今後はなるべく最新のvimでちゃんと試してからissue登録するようにします)

では、closeしちゃいます。
ありがとうございました。
