### ISSUE TITLE
Lua 5.2でコンパイルできない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#119]
Vim 7.3.393 + Lua 5.2 でコンパイルできない。
確認したのはWindows版。

とりあえず今からパッチ書きます。

**Comment by koron** [comment]
LUA_ENVIRONINDEX が無くなってる。
そのせいで手こずりそうな予感。

**Comment by koron** [comment]
あとはbufferとwindowオブジェクトだけなんとかすれば良さそうなんだけど…これオリジナルコードかなりマズいんじゃなかろうか? なんかテストを書いたほうが良いかもしれん。

**Comment by koron** [comment]
やっぱし…解放済みメモリの参照を引き起こした。

**Comment by koron** [comment]
解放済みメモリの参照の件は #120 に追加。

**Comment by koron** [comment]
とりあえずコンパイルできるところまでのパッチ。

https://gist.github.com/1574612

単純な `:lua print('Hello Vim')` くらいは動いた。

``` vimL
:lua buf = vim.buffer(1)
:lua print(buf.name)
```

これは動かない。現時点では落ちる原因がプログラミングミスなのか、コンパイラ不一致によるものなのかは定かではない。
(VimをMSVC10、LuaはMinGW) まぁ、ほぼプログラミングミスだけど。

# 変更のポイント

Lua 5.2では「環境テーブル」がなくなってしまった。そのかわりにuserdataにバインドできるuservalueが増えた。

## 変更前

Vimのif_luaでは環境テーブルを使って、bufferとwindowについてVim側の値とLua側での値を保持していた。Vim側の値はそれぞれのポインタ(lightudata)であり、Lua側の値はポインタへのポインタ(udata)だった。環境テーブルには `env[lightudata] = udata` (テーブルA) 及び `env[udata] = true` (テーブルB)を、合わせて持っていた。(ポインタだからどうせかぶらないのでまとめてしまったのだろう)

テーブルAはVim側の値1つに対してLua側の値を1つだけ作るために使い、またVim側の値が無効になった場合には`env[lightudata] = nil` とすることでudataが参照するlightudataの生き死にを管理していた。ただしこの生死をチェックしていない箇所があることは #120 に述べたとおり。

テーブルBはudataの寿命引き伸ばし(GCに回収されるのを防ぐため)に使っている。環境テーブルはvalueについてのweak tableとなっている。そのため仮にテーブルBがない場合、Lua側でudataが参照されなくなると、テーブルAにあるudataが回収されてしまう。それを避ける目的。(ただこのあたりはトリッキー過ぎて、つきつめるとなにか問題が有りそうな気がする)

## 変更後

テーブルAの代替としてuservalueを用いた。uservalueとはuserdataに関連付けられるテーブルのこと。あ、テーブルしかダメなのか…なんか別のものをひっつけた記憶がある。

テーブルBの代替はLua側へ完全に任せることにした。ちょっとこちらは考慮不足。

# 以上

自前でLua 5.2をビルド&配布するのもアレなので、今後の作業優先度をどうするか迷ってる。だれか引き継いでくれるなら歓迎。

**Comment by koron** [comment]
落ちていた原因が判明。uservalueはuserdataに与えられるもので、lightuserdataには与えられない。先のパッチではlightuserdataにこれを与えようとしていた。またLUA_USE_APICHECKをdefineせずにコンパイルするとLuaは実行時に型チェックを行わない。そのためこのことがLua 5.2のソースコードを読むまでわからなかった。

ENVが使えないならREGISTRYを使えば良いという考え方もできるが、それでもENVを使ったのはweak tableの件と無関係ではなさそう。windowやbufferは回収タイミングがあるが、listやdictには(今は)無いんじゃないか?それを自動でやるための施策、と考えるとわかる気がする。シナリオとしてはこう。
1. Luaにコピったlistやdictを回収するタイミングがないなぁ
2. ENVをweak tableにして使えば良いね(REGISTRYはweak tableにできない?)
3. windowとbufferもENVに突っ込むか
4. でも勝手に消えたら困るな…
5. そうだENVにキーとして入れておこう

5があまりにもバカだけどw たぶんこんな感じじゃなかろうか。

**Comment by ynkdir** [comment]
Vim から Lua への list/dict のコピーは copy by value なのに intern (?) を管理してるのはへんですね。

```
let x = {"x": 123}
echo x
=> {'x': 123}

lua x = vim.eval("x")
lua print(x.x)
=> 123

### lua 上で x.x を変更
lua x.x = 999

### vim 上では x.x は 123 なのに
echo x
=> {'x': 123}

### vim.eval("x") で取得すると 999 になっている
lua y = vim.eval("x")
lua print(y.x)
=> 999
```

**Comment by koron** [comment]
さっきわかったんですがたぶんcopyを返すのが仕様です。internは循環参照を切るために一時的に使ってます。なのでweak tableなんですわ。

**Comment by ynkdir** [comment]
あーなるほど。一時的な用途なのに一時的になってないと…。

**Comment by koron** [comment]
@ynkdir その例、非常にいいですね。今、作ってるENVIRON使わない為のパッチの、正当性の根拠になりそうです。

**Comment by koron** [comment]
まずはENVIRON使わないようにするパッチできた。

https://gist.github.com/1577830

このパッチを当てると先の @ynkdir さんの上記の例、最後のところで 123 になります。

**Comment by koron** [comment]
とりあえず第一段 [「ENVIRONを潰せ」](https://groups.google.com/forum/?hl=ja#!topic/vim_dev/g6JU0S5gKkU) を投げた。

**Comment by ynkdir** [comment]
luaV_get_associated_luavalue() 等の関数が "#ifdef DYNAMIC_LUA ... #endif" の内側に入ってるのでlinuxだとコンパイルエラーになります。

**Comment by koron** [comment]
@ynkdir Thanks! MLには訂正版を送信し [Gist](https://gist.github.com/1577830) は更新しました。

**Comment by koron** [comment]
5.2対応のパッチできた https://gist.github.com/1578073
バグ修正パッチ https://gist.github.com/1577830 の後に当てる必要あり。

**Comment by koron** [comment]
現在 https://groups.google.com/forum/?hl=ja#!topic/vim_dev/g6JU0S5gKkU で議論は進行中。ほぼ終わりに近づいていて、現行とほぼ動作が変わらない版と、ListやDictの動作がより洗練された版ができてしもたw。if_luaの作者Luisは後者をえらくプッシュしている状況。

まだ詳しくは見てないけど、後者はListやDictをVimとLua双方向に操作可能なものになっていると思われる。

**Comment by thinca** [comment]
なんか新しいパッチ来ましたね。

**Comment by mattn** [comment]
これclose? #120 も?

**Comment by koron** [comment]
試してないけど多分できるようになっているはず。なので閉じちゃおう。

**Comment by h-east** [comment]
Patch 7.3.494 これかな？
https://groups.google.com/d/topic/vim_dev/A6-ovWAcw8k/discussion

なるべく後で追跡できるようにpatchのリンクやtodoのコピペを張ってcloseしませう。

**Comment by koron** [comment]
@h-east thanks.  今後それらを補う役目をお任せします ( ｰ`дｰ´)ｷﾘｯ

**Comment by h-east** [comment]
@koron ポイント溜まったらお寿司と交換ですし

**Comment by koron** [comment]
@h-east 焼肉とどっちがよかね? http://www.tankiyo.com/top.html

**Comment by thinca** [comment]
迷うなぁ。 ←関係ない人

**Comment by koron** [comment]
では @thinca さんもリンクとか補う係に任命します!

**Comment by mattn** [comment]
ありがとうございます。

**Comment by thinca** [comment]
お任せあれ！ (寿司に1票)

**Comment by koron** [comment]
@mattn さんはパッチとか書く係でお願いします!

**Comment by h-east** [comment]
いつの間にｗｗ
