### ISSUE TITLE
eblook on Vimで表示が化けることがある

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/issues#1193]
## 質問・報告の内容

eblook.vimでの表示が化けたり化けなかったりする

ターゲット 辞書 EDICT 単語 bitとして確認

![d36514af](https://user-images.githubusercontent.com/96727/46517046-3ab80700-c8a8-11e8-8f88-7e8d71b22462.png)

このように化ける

正常にいく場合がある(後述)
![402100a1](https://user-images.githubusercontent.com/96727/46517532-abf8b980-c8aa-11e8-9f3d-91ff74dcc5a3.png)

結論にあるのですが、eblook自体よりは、vimのデコードで処理がブレるように見えるのでIssueにしました。

### 対処について

問題が設定関係の可能性はあります
設定で回避できるならしたい

## Vimのバージョン

chocolatey vim-tux
```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 30 2018 18:51:24)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-442
Compiled by stop_@LAPTOP-E7OHISR4
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
+acl               +emacs_tags        +mouse             +tag_old_static
+arabic            +eval              -mouseshape        -tag_any_white
+autocmd           +ex_extra          +multi_byte        +tcl/dyn
+autochdir         +extra_search      +multi_lang        +termguicolors
+autoservername    +farsi             +mzscheme/dyn      +terminal
-balloon_eval      +file_in_path      -netbeans_intg     -tgetent
+balloon_eval_term +find_in_path      +num64             -termresponse
-browse            +float             +packages          +textobjects
++builtin_terms    +folding           +path_extra        +timers
+byte_offset       -footer            +perl/dyn          +title
+channel           +gettext/dyn       +persistent_undo   -toolbar
+cindent           -hangul_input      -postscript        +user_commands
+clientserver      +iconv/dyn         +printer           +vartabs
+clipboard         +insert_expand     +profile           +vertsplit
+cmdline_compl     +job               +python/dyn        +virtualedit
+cmdline_hist      +jumplist          +python3/dyn       +visual
+cmdline_info      +keymap            +quickfix          +visualextra
+comments          +lambda            +reltime           +viminfo
+conceal           +langmap           +rightleft         +vreplace
+cryptv            +libcall           +ruby/dyn          +vtp
+cscope            +linebreak         +scrollbind        +wildignore
+cursorbind        +lispindent        +signs             +wildmenu
+cursorshape       +listcmds          +smartindent       +windows
+dialog_con        +localmap          +startuptime       +writebackup
+diff              +lua/dyn           +statusline        -xfontset
+digraphs          +menu              -sun_workshop      -xim
-dnd               +mksession         +syntax            -xpm_w32
-ebcdic            +modify_fname      +tag_binary        -xterm_save
      システム vimrc: "$VIM\vimrc"
      ユーザー vimrc: "$HOME\_vimrc"
   第2ユーザー vimrc: "$HOME\vimfiles\vimrc"
   第3ユーザー vimrc: "$VIM\_vimrc"
       ユーザー exrc: "$HOME\_exrc"
    第2ユーザー exrc: "$VIM\_exrc"
  デフォルトファイル: "$VIMRUNTIME\defaults.vim"
コンパイル: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPi
リンク: link  /nologo /subsystem:console /opt:ref /LTCG:STATUS oldnames.lib kerg
```

また関連する設定として

```
encoding=utf-8
termencoding未設定
```

## OSの種類/ディストリ/バージョン

* Windows 10 64bit Pro 1709(16299.665)/64bit Pro 1803(後で追記)

## 使用している or 関係していそうなプラグイン

[eblook.vim](https://github.com/deton/eblook.vim)

### eblook 入手先と設定
[Kazuhiro's blog - eblook 1.6.1+media](http://ikazuhiro.s206.xrea.com/staticpages/index.php/eblook)
32bit/64bit binary

利用は64bit
```
eblook 1.6.1+media-20150724 (with EB 4.4)
```

### 設定
環境ごとで分岐と共通化しているが、Windowsとしては、以下+辞書定義だけ
```vim
let eblookenc='cp932'
```
設定している辞書
[FPWBOOK](http://openlab.ring.gr.jp/edict/fpw/)

## 切り分け
note
- Shift_JIS codepage 932
- Unicode(UTF-8) codepage 65001

同一環境で実施
次の条件で発生している

| 環境                               | バグ発生 |
|:-----------------------------------|:--------:|
| Windows上からgVim起動              |   する   |
| Windows上からVim起動               |   する   |
| cmd(codepage 932)からgVim起動      |  しない  |
| cmd(codepage 932)からVim起動       |   する   |
| cmd(codepage 65001)からgVim起動    |   する   |
| cmd(codepage 65001)からVim起動     |   する   |
| nyagos(codepage 65001)からgVim起動 |   する   |
| nyagos(codepage 65001)からVim起動  |  しない  |

※nyagos(codepage 65001)が普段環境なので、その点を疑い切り分けを行いました

### 手動操作
eblook上でEDICTでbitを検索しての結果
encoding=sjisを付けても同じ
encoding=utf8でも同じ

| 環境                           |  表示  |
|:-------------------------------|:------:|
| cmd(codepage 932)から確認      |  正常  |
| cmd(codepage 65001)から確認    | 化ける |
| nyagos(codepage 65001)から確認 | 化ける |

## コードの解析
via eblook.vim
```vim
" eblookプログラムを実行する
function! s:ExecuteEblook()
  " ++encを指定しないとEUCでの短い出力をCP932と誤認識することがある
  silent execute 'read! ++enc=' . g:eblookenc . ' "' . g:eblookprg . '" ' . s:eblookopt . ' < "' . s:cmdfile . '"'
  "if &encoding !=# g:eblookenc
  "  let &fileencoding = &encoding
  "endif

  silent! :g/^Warning: you should specify a book directory first$/d _
endfunction
```

とあり、cp932でデコードしている分には良いと思うのですが、なぜか差が出ます

このような理由から「vimで環境からの影響で、受け取りデータorデコード処理で問題がでる」のではないかと考えます

**Comment by raa0121** [comment]
辞書のファイルエンコードタイプと、 `++enc=` する際のエンコードタイプが一致しないと、文字化けしそうです。

以下、Slackのログです
```
raa0121 [3:12 PM]
辞書ファイルって全部CP932なんですかね…


yoshitia [3:15 PM]
migemo使った時はcp932の辞書とutf8の辞書あったな

raa0121 [3:15 PM]
ただ、同じ bit でも化ける時と化けない時があるのがつらし

yoshitia [3:17 PM]
システム側の文字コードが色々変更していっても辞書側が対応してなかったらアウトとかありそうだな・・・

mattn [3:28 PM]
見た感じ化けた時の fileencoding が latin-1 とかになってないかな。
cp932 で「ビット」は 83 72 83 62 83 67 で
72 は r、62 は b、67 は g なので、見えてるスクショからすると違うエンコーディングになってる。
https://go-gyazo.appspot.com/5b6fc5e0afb491f8.png
この ?r?b?g の事です。
utf-8 みたいですね。

yoshitia [3:31 PM]
最近SJISの2バイトコード調べたばかりだな

mattn [3:31 PM]
cp932 でビットと書かれたファイルを `:e ++enc=utf-8 bit` で開くとこうなる。
```

**Comment by tsuyoshicho** [comment]
一応、eblookでEDICTの表示をする分にcp932指定で大丈夫なようですが...辞書毎の切り替えについては、ちょとおいて置くということで。

辞書のコーディングは別途しらべてみます。(今は無理)

**Comment by mattn** [comment]
Vim script で
```
let enc = "辞書のエンコーディング"
let res = iconv(system(...), enc, &encoding)
```
しないと文字化けします。eblook.vim に修正が必要です。

**Comment by tsuyoshicho** [comment]
なんか挙動が微妙なので、起動テストを繰り返したところ、g:eblookencがセットされてないことが時々あるようです。
deinのhook_addに記述しているのですが...lazyだから?

諸条件については詳細に調査しないと謎です
とりあえず、eblookencが未定義のときに、手動でセットすれば化けなかったので、基本はそこが疑わしそうです。

それはそれとして、複数辞書で、それぞれの辞書のエンコードをどうにか指定できないとツラいのは変らなそうですね、やっぱり。

(エンコード的問題についてはvim本体とは離れたと思います。ただhook_addの件は環境依存っぽいですがありますので、おまかせします。)

**Comment by mattn** [comment]
本体のバグじゃない事が確定したら教えて下さい。

**Comment by tsuyoshicho** [comment]
本体バグでないことが確定しました。(deinも関係ないはず)

hook_addでセットしているeblookencにg:がなかったので、反映されてなかったようです(hook_addだとl:になる? [^](https://thinca.hatenablog.com/entry/20120619/1340061987))

ただ、たまに反映されてる(echo g:eblookencがcp932になる)のが、よくわかりません。テストコード作って複数回確認を試みましたが、そういう現象はおきませんし...

なので本件クローズとしてくさい。
上記の疑問点現象が再発したら、別途相談するかもしれません。

お手間をおかけしました。
