### ISSUE TITLE
shift + h/l で一番上/下の行に移動しない

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1194]
## 質問・報告の内容
vim初心者です。

shift + h , shift + l
でそれぞれウィンドウ上の一番上の行、一番下の行に移動できるはずですが、
私の環境では、それぞれ一番上から6行目、一番下から6行目に移動します。

どのような要因が考えられますか？

## Vimのバージョン
VIM - Vi IMproved 8.1
Kaoriya GVIM

## OSの種類/ディストリ/バージョン
Windows 10 Home 64bit

## 使用している or 関係していそうなプラグイン
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'
NeoBundle 'inkarkat/vim-mark'

**Comment by k-takata** [comment]
scrolloff が設定されていると思われます。
`:verbose set scrolloff?` を実行して、どこで設定されているか調べてください。
scrolloff の使い方は、`:help 'scrolloff'` で確認してください。

**Comment by hiro-github** [comment]
ありがとうございます。
:set scrolloff=1
の設定で快適にカーソルを移動させることができました。

**Comment by h-east** [comment]
:set scrolloff=0
じゃないと一番上/下に行かないですよ。
