### ISSUE TITLE
ノーマルモードでIMEをOFFにしたい

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1195]
## 質問・報告の内容
ノーマル・モードになった時に必ず IME が OFF にするにはどのような方法が良いでしょうか?
現在 IME に Mozc を使い、そちらのキー割り当てで \<C-S-[Muhenkan]> といった普段使わないキーに IME OFF を割り当て、\~/.vim/vimrc に
```
augroup VIMRC
	autocmd!
	if has('unix') " インサート・モードを抜けた時は必ず日本語 OFF
		autocmd InsertLeave,CmdwinLeave * call system('xvkbd -text "\C\S\[Muhenkan]" > /dev/null 2>&1')
	endif
augroup END
```
として、システムにキー・コードを送って、ノーマル・モードに戻った時に IME を OFF にするようにしています

ただこの方法ですと、プラグイン neocomplete で一部希望道理の動作をしません
具体的には、

1. 補完のキーワードを入力
2. 設定している \<C-u> で補完確定
3. 再び \<C-u> で、キーワードを確定して次の移動位置に移動←本来は「()」の間は空になる
4. 一度 Ctrl を離し、\<C-u> で、キーワードを確定して次の移動位置に移動
5. \<C-[> でノーマル・モード復帰を試みる←失敗して「[」が入力される
6. 一度 Ctrl を離し、\<C-[> で、ノーマル・モードに

と下の動画の様に
![neocomplete_ime](https://user-images.githubusercontent.com/24851657/46912851-ab070c80-cfbb-11e8-8964-19a44752700a.gif)

3, 5 で Ctrl を押していない扱いになってしまいます
4, 6 の様に Ctrl を押しっぱなしにせず、一度離せばこの問題は起きませんが使いが手が悪くなります

- そもそもノーマル・モード時に IME を無効にするより良い方法は有るでしょうか? (IME の状態を保存するのではなく、あくまで無効にするだけ)
- 本当は CmdlineLeave 時も加えたいが、別 deoplete.nvim も組み合わせると、入力自体が遅くなったり、補完が上手く働かず「\<Plug>といった入力されることが有る)

といった点について代価案や改善案を教えて頂ければ幸いです

## Vimのバージョン
>$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
適用済パッチ: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
<snip>

## OSの種類/ディストリ/バージョン
>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux naonari 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## 使用している or 関係していそうなプラグイン
>:r!grep -v "^\s*\"" ~/.vim/vimrc
```
if has('vim_starting')
	if &compatible
		set nocompatible                           "viとの互換性をとらない
	endif
	let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.vim') : $XDG_CACHE_HOME
	let s:dein_dir = s:cache_home . '/bundle'
	let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
	if !isdirectory(s:dein_repo_dir)
		call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
	endif
	let &runtimepath = &runtimepath .",". s:dein_repo_dir
	if dein#load_state(s:dein_dir)
		call dein#begin(s:dein_dir)
		let g:rc_dir = expand('~/.vim/rc')
		let s:toml = g:rc_dir . '/dein.toml'
		let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'
		call dein#load_toml(s:toml, {'lazy': 0})
		call dein#load_toml(s:lazy_toml, {'lazy': 1})
		call dein#end()
		call dein#save_state()
		if dein#check_install()
			call dein#install()
		endif
	endif
endif
filetype plugin indent on
```
>:r!grep -v "^\s*\#" ~/.vim/rc/dein.toml | grep -v "^\s*\""
```
[[plugins]]
repo = 'Shougo/dein.vim'
```
>:r!grep -v "^\s*\#" ~/.vim/rc/dein_lazy.toml | grep -v "^\s*\"" | sed -r 's/ +\#.+//g'
```
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'Shougo/neocomplete'
depends = 'context_filetype.vim'
if   = '''!has('python3') && has('lua')'''
on_event = 'InsertEnter'
hook_source = '''
	let g:neocomplete#enable_at_startup = 1
	let g:neocomplete#enable_ignore_case = 1
	let g:neocomplete#enable_smart_case = 1
	if !exists('g:neocomplete#keyword_patterns')
		let g:neocomplete#keyword_patterns = {}
	endif
	let g:neocomplete#keyword_patterns._ = '\h\w*' "_(アンダーバー)区切りの補完を有効化
	if !exists('g:neocomplete#force_omni_input_patterns')
		let g:neocomplete#force_omni_input_patterns = {}
	endif
	let g:neocomplete#sources#dictionary#dictionaries = { 'default' : '',}
	let g:neocomplete#sources#omni#input_patterns = {}
	let g:neocomplete#force_omni_input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
	let g:neocomplete#sources#omni#input_patterns.tex = '\\cite{\s*[0-9A-Za-z_:]*\|\\ref{\s*[0-9A-Za-z_:]*' "\ref,\cite で補完
	let g:neocomplete#force_omni_input_patterns = {
				 \ 'ruby': '[^. *\t]\.\w*\|\h\w*::'
	      \ }
'''
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_source = '''
	imap <C-u> <Plug>(neosnippet_expand_or_jump)
	smap <C-u> <Plug>(neosnippet_expand_or_jump)
	xmap <C-u> <Plug>(neosnippet_expand_target)
	let g:neosnippet#enable_completed_snippet = 1
	let g:neosnippet#expand_word_boundary = 1    " 補完は単語で←0のままでは記号の後ろで出ない
'''
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
```

**Comment by h-east** [comment]
@yoshinaga-hiroyuki 現象が起きる必要最低限のVim scriptを提示していただくことは可能でしょうか？

**Comment by iranoan** [comment]
```
	imap <C-u> <Plug>(neosnippet_expand_or_jump)
	smap <C-u> <Plug>(neosnippet_expand_or_jump)
	xmap <C-u> <Plug>(neosnippet_expand_target)
```
のキー操作にあたるプラグインの呼び出し部分をスクリプトでどう書けばわからないレベルです
```
		autocmd InsertLeave,CmdwinLeave * call system('xvkbd -text "\C\S\[Muhenkan]" > /dev/null 2>&1')
```
の部分を
```
		autocmd InsertLeave,CmdwinLeave * call system('fcitx-remote -c')
```
といったキーコードの呼び出しではなく、fcitx による切り替えだと上手くいくので、今現在は取り敢えずこの方法を使って入るのですが、これだど現在 Ubuntu で標準の iBus だとどうするのか解らない😅

別にこの方法にこだわっているわけでもないので、他に表題の件を実現するより良い方法が有れば、それを教えていただいても幸いです

**Comment by presuku** [comment]
@yoshinaga-hiroyuki さんの求めているのはIM制御用のIFだと思うのですが、
そのために追加された imactivefunc (imaf) と imstatusfunc (imsf) があります。

しかし、現在、複数の理由から、環境によっては正常に使用できないかもしれません。

理由:
1. #1130 にあるように、Linux GUI版では imaf / imsf が呼ばれない用に変更されている。
1. vim 8.1.0053 から imaf の引数が string から number に変更されており、  
   vim script の書き方や plugin によっては正常動作しない、ないし落ちる。

imaf/imsf を使用して fcitx を制御する方法は
https://qiita.com/sgur/items/aa443bc2aed6fe0eb138
この設定で、 iminsert=0 にすればノーマルモード時にOFFになり、
次回のインサートモードの時もOFFになると思います。

ibus をコマンドでEngineを切り替え
https://qiita.com/ka_/items/dad955fe7423318b7dae
これと imaf/imsf を組み合わせると ibus でも同様に制御できると思います。

余談ですが ibus は IM Engine 内のステートの管理・制御することやめてしまったので、
上記のような Engine の切り替え以外は外から制御できません。
従って、Engine は Mozc 固定で、 Mozc のキーバインドで On/Off をしている場合には、有効な方法ではないです。

私も uim からの移行で、 ibus を検討したのですが、やはり fcitx にしてしまいました。
ibus ではアプリ間で状態を共有しているのでコード書きつつ、ブラウザで日本語入力して vim に戻ってくると日本語入力が On になるのが、やはり使いづらかったです
詳細は kaoriya さんの blog を参照してみて下さい。
https://www.kaoriya.net/blog/2013/10/18/

**Comment by iranoan** [comment]
情報ありがとうございました
何故か私の環境では、
https://qiita.com/sgur/items/aa443bc2aed6fe0eb138
は上手く行きませんでした
使っているプラグインとの組み合わせかな?
