### ISSUE TITLE
内部diffでdiffモードにすると途中から差分のhighlightや折り畳みが出鱈目になる場合がある

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#1199]
diff関連のオプションがデフォルト値(`diffopt=internal,filler`、`diffexpr=`)の状態でdiffモードにすると、途中から差分のhighlightや折り畳みが出鱈目になります。
```
$ vim -d test_old.txt test.txt
```
※ confidentialなテキストデータでバグ発見したしたので、後で再現データ作成して貼り付けます。

gVim 8.1.0500 64bit on Windows 10 (install from [Vim official](https://github.com/vim/vim-win32-installer/releases) gvim_8.1.0500_x64-mui2.exe)
Vim 8.1.0500 64bit on Ubuntu 18.04 (source build)

## その他

「仕事にならんぜ！」という人は `set diffopt-=internal` して回避ください。

**Comment by h-east** [comment]
~~これ、マルチバイト絡みですね。~~
~~文字コードがutf-8のソースコードに対してWindowsのTortoiseSVNでパッチを作成すると、差分情報のIndexに`(リビジョン 1234)`とか`(作業コピー)`が文字コードCP932で埋め込まれる。~~
~~文字コード混在ファイルの出来上がり。このファイルを別の時点のものと内部diff使って差分表示させると表示が狂う。外部diffだと大丈夫なんですよね。直せるかな？~~

**Comment by iranoan** [comment]
検証不十分の単なる情報になってしまいますが、この現象は外部 diff でも起きるかも知れません
[vimdiffでより賢いアルゴリズム (patience, histogram) を使う](https://qiita.com/takaakikasai/items/3d4f8a4867364a46dfa3)
を使って、元のファイルが EUC-JP の時に、異なる部分が上手く表示されないことが有りました
具体的には EBView の設定ファイル dictgroup.xml です

個人的には、Ruby のスクリプトから git, tail, sed, nkf, awk を使ったシェル・スクリプトに書き換えて対処したのですが…

**Comment by h-east** [comment]
分かった！diff形式同士をdiffすると、`@@ -6,7 +11,7 @@`に反応して表示が変になる。
マルチバイト関係なかった。

test_old.txt
```
1
2
3
4
5
 
================
@@ -6,7 +11,7 @@
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
```

test.txt
```
1
2
3
4
5
 
================
```

この2ファイルで
```
$ vim -d test_old.txt test.txt
```
したら再現します。明らかに差分highlightと折り畳みがおかしいです。
![int_diff](https://user-images.githubusercontent.com/518808/47704078-bfa6fe00-dc65-11e8-85ae-9477122e3cf7.png)

`@@ -6,7 +11,7 @@` の部分の `-6`や`+11`の数値を変えると面白いです。
これマズいですよね。

**Comment by h-east** [comment]
xdiffがdiff対象のコンテンツを見てしまってますね。コンテンツ内にhunkヘッダ(例: "@@ -8,17 +7,0 @@")があると、その情報も差分情報として登録&処理しちゃってる。

何で見てるんだろう。。必要な場合があるのだろうか？
とりあえず見ないようにしたら直った。

```patch
diff --git a/src/xdiff/xemit.c b/src/xdiff/xemit.c
index d8a6f1ed3..d1c34bab8 100644
--- a/src/xdiff/xemit.c
+++ b/src/xdiff/xemit.c
@@ -285,6 +285,7 @@ int xdl_emit_diff(xdfenv_t *xe, xdchange_t *xscr, xdemitcb_t *ecb,
 				      func_line.buf, func_line.len, ecb) < 0)
 			return -1;
 
+#if 0   // Do not refer to header (lines beginning with "@@ ") in content.
 		/*
 		 * Emit pre-context.
 		 */
@@ -326,6 +327,7 @@ int xdl_emit_diff(xdfenv_t *xe, xdchange_t *xscr, xdemitcb_t *ecb,
 		for (s2 = xche->i2 + xche->chg2; s2 < e2; s2++)
 			if (xdl_emit_record(&xe->xdf2, s2, " ", ecb) < 0)
 				return -1;
+#endif
 	}
 
 	return 0;
```

**Comment by h-east** [comment]
sent vim_dev.
https://groups.google.com/d/msg/vim_dev/yY2gvIXdZeU/ri-MfsQCAgAJ

**Comment by h-east** [comment]
8.1.0502 👍 
https://github.com/vim/vim/commit/f080d70a82f3a4477f346d9efcdfaec1bc1e1d58

xdiffから呼ばれるcallback内を修正することにより対処。(by Bram氏)

testdir/test_diffmode.vim のcommit/push忘れ？

**Comment by h-east** [comment]
> testdir/test_diffmode.vim のcommit/push忘れ？

8.1.0503
https://github.com/vim/vim/commit/f7acf2b63ce91ea802dbcf0618f0cdee80993468
