### ISSUE TITLE
quickfixウィンドウとlocation listウィンドウを区別する手段がない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#12]
buftype=quickfix のウィンドウが、quickfixウィンドウなのかlocation-listウィンドウなのかVimスクリプトから確実に知る手段がない。
これができないと、getqflist() を使うべきか getloclist() を使うべきかが判断できない。

参考: 無理矢理判定している例
http://d.hatena.ne.jp/h_east/20110825/p1
この例では副作用が完全に防げていない。

**Comment by h-east** [comment]
quickfixとlocation-listって一括りになってたり分けられてたり関係が中途半端ですよね。
おそらくlocation-listが後から機能追加された感じなのでしょうね。

例えば、オートコマンドのeventは分けても良かったんじゃないのかなって思います。
　autocmd QuickfixCmdPost [^l]\* copen
　autocmd QuickfixCmdPost l\* lopen
＃ それを言ったら buftype を分けろよって感じですが(^^ゞ

今から分けると後方互換性が大変だと思うので、quickfixかlocation-listを判定できる組み込み関数を追加するのはありだと思います。

PS
話ちょっとズレますが、quickfixウィンドウでsetloclist(0, []) 出来てしまうのはバグのような気がする。

**Comment by k-takata** [comment]
つい最近、vim_use でも同じ話題が挙がっていました。

What is the best way to distinguish the current buffer is location list or quickfix list?
https://groups.google.com/d/topic/vim_use/tKwGUyYq5OI/discussion

**Comment by h-east** [comment]
Another way
https://groups.google.com/d/msg/vim_use/LwzQJX4o7U4/naEbGERjyZ4J

15ヶ月間、特に誰も動かないし問題視していないので閉じます。
このIssueを見て「やってやるぜ！」という気になった人がいれば再オープン下さい。

**Comment by thinca** [comment]
誰も動いてこそないですけど、私は今でも困ってます。
問題がなくなったわけではないので、急いで閉じる必要はないはずです。

**Comment by h-east** [comment]
じゃあ動け。15ヶ月経過したよ。
自分で出来なきゃ誰かに頼め。

**Comment by h-east** [comment]
なんで困ってるのに15ヶ月も放置しているの？

実際に「やってみようかな」という人が出てきてから再オープンで問題ないので閉じます。

**Comment by thinca** [comment]
何か勘違いをしているように思うのですが、ここは問題を集積して共有する場所であって、必ず解決しなければならない場所ではないです。
開いておけばいつか誰かの目に止まって、その人がやってくれる可能性もあるわけです。閉じると、問題になっていないという認識になってしまい、それもなくなってしまいます。

**Comment by h-east** [comment]
君ひとりしか困っていないということでしょ？

**Comment by thinca** [comment]
そんなことないですよ。例えば[この問題](https://github.com/thinca/vim-qfreplace/issues/5)はこの Issue が解決しないと根本的に解決しません。
あと話が終わってないのにいちいち閉じないで頂けますか?

**Comment by mattn** [comment]
よそでやれ

**Comment by h-east** [comment]
だったら余計に

> じゃあ動け。15ヶ月経過したよ。
> 自分で出来なきゃ誰かに頼め。

ですね。
15ヶ月も動かずにおいてIssue閉じられたからといって変に反応しちゃって。

**Comment by thinca** [comment]
なんで、すぐに解決しないといけないという風潮になっているのか理解できません。

> よそでやれ

大変申し訳ないです。

**Comment by h-east** [comment]
15ヶ月...

**Comment by mattn** [comment]
メールがすごいくるのでtwitterかなんかでやってね。

**Comment by h-east** [comment]
@thinca 仕様提案ぐらいしようよ。黙って誰かがやってくれるのをいつまでも待つの？
んで突いたら「困ってる」って意味が分からん。

**Comment by h-east** [comment]
変数設定するだけなら実質1行追加で済むんやで。

``` diff
diff -r 8cae3b61ce9e src/quickfix.c
--- a/src/quickfix.c    Mon Dec 08 04:16:45 2014 +0100
+++ b/src/quickfix.c    Wed Dec 10 11:02:00 2014 +0900
@@ -2433,6 +2433,8 @@
        set_option_value((char_u *)"fdm", 0L, (char_u *)"manual",
                                   OPT_LOCAL);
 #endif
+       set_internal_string_var("b:qflisttype", (curwin->w_llist_ref == NULL) ?
+                   "quickfix" : "location");
    }

    /* Only set the height when still in the same tab page and there is no
```

``` vim
:echo getbufvar("%", "qflisttype")
```

で`buftype`が "quickfix" の場合は "quickfix" か "location" が返る。

これを参考に自分の納得の行くソリューションを展開してちょうだい。

**Comment by mattn** [comment]
check_changedtick を少し弄って readonly にしちゃいましょう。

**Comment by mattn** [comment]
https://gist.github.com/mattn/6c8942fa063c2f3953bc

**Comment by h-east** [comment]
@mattn 
なんのこっちゃ？と思ったんですが readonlyな変数名`changedtick`が関数名の一部になっててハードコードされていたんですね。Thanks!

**Comment by mattn** [comment]
テスト追加。試してない。

**Comment by koron** [comment]
プロジェクトの運用上、wontfix で閉じること自体は、問題ないでしょう。
closed & wontfix で検索すればよいのだから。

**Comment by koron** [comment]
> closed & wontfix で検索すればよいのだから。

https://github.com/vim-jp/issues/issues?q=label%3Axlose%2Fwontfix+is%3Aclosed

こんな感じのリンクをどっかに貼っとくと良さげ。

**Comment by mattn** [comment]
koron さんに assign されたらしいので後は頼んだ

**Comment by thinca** [comment]
@mattn パッチありがとうございます！参考にします！
@koron wontfix は、直さないって言うラベルなので、意味が違うと思います。

**Comment by mattn** [comment]
@thinca テストもあるしあと出すだけなのでやりますよ。

**Comment by h-east** [comment]
help一応書いたので貼っときます。

``` diff
diff -r 8cae3b61ce9e runtime/doc/eval.txt
--- a/runtime/doc/eval.txt  Mon Dec 08 04:16:45 2014 +0100
+++ b/runtime/doc/eval.txt  Wed Dec 10 13:31:12 2014 +0900
@@ -1158,7 +1158,7 @@
 This kind of variable is deleted when the buffer is wiped out or deleted with
 |:bdelete|.

-One local buffer variable is predefined:
+Two local buffer variables are predefined:
                    *b:changedtick* *changetick*
 b:changedtick  The total number of changes to the current buffer.  It is
        incremented for each change.  An undo command is also a change
@@ -1169,6 +1169,14 @@
            :   call My_Update()
            :endif
 <
+                   *b:qflisttype* *qflisttype*
+b:qflisttype   The quickfix list type of the current buffer.  Only defined when
+       'buftype' set to "quickfix".
+   The value of this variable.
+     quickfix  quickfix list, contains list of errors |:cwindow|
+     location  location list, contains list of locations |:lwindow|
+
+<
                        *window-variable* *w:var* *w:*
 A variable name that is preceded with "w:" is local to the current window.  It
 is deleted when the window is closed.
```

**Comment by mattn** [comment]
あざます！

**Comment by mattn** [comment]
https://gist.github.com/mattn/6c8942fa063c2f3953bc

パッチに取り込みました。

**Comment by h-east** [comment]
@mattn あっ、最初のpatch、80桁に収まってなかったので修正お願いします。

``` diff
diff -r 8cae3b61ce9e src/quickfix.c
--- a/src/quickfix.c    Mon Dec 08 04:16:45 2014 +0100
+++ b/src/quickfix.c    Wed Dec 10 13:31:12 2014 +0900
@@ -2433,6 +2433,8 @@
        set_option_value((char_u *)"fdm", 0L, (char_u *)"manual",
                                   OPT_LOCAL);
 #endif
+       set_internal_string_var("b:qflisttype", (curwin->w_llist_ref
+                       == NULL) ? "quickfix" : "location");
    }

    /* Only set the height when still in the same tab page and there is no
```

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/GIjn9QRyLag

**Comment by h-east** [comment]
@mattn :+1: 乙です。

**Comment by thinca** [comment]
@mattn @h-east ありがとうございます！！

**Comment by h-east** [comment]
@mattn patch更新したので反映をお願いします。
https://gist.github.com/h-east/4d6e0e77413598ffcc8f
28～39行目: 'buftype'のヘルプから `b:qflisttype` に辿れるようにしました。
160行目: テストが通らなかったので `:new`を足しました。

**Comment by k-takata** [comment]
テストですが、`:so small.vim` が必要だったりしませんか？

**Comment by h-east** [comment]
@k-takata `+quickfix`はnormal feature以降なので必要ですね。ありがとうございます。

@mattn 私のgist更新しました。151行目

**Comment by mattn** [comment]
updated

**Comment by koron** [comment]
@thinca 意味は、あとでいくらでも付け足せます。なんなら xlose/backlog を追加してもよいですし。

**Comment by h-east** [comment]
とっくにTODOリスト入ってた。(2014/12/14)

https://github.com/vim-jp/vim/commit/4ef3ea7d06794f1e8b4b46bfaa5736a565549386#diff-38d7929bd26d74d92ceddf984bbfc8dbR486

> Patch to check whether a buffer is quickfix or a location list.
> (Yasuhiro Matsumoto, 2014 Dec 9)

**Comment by h-east** [comment]
patch 7.4.2215
https://github.com/vim/vim/commit/386600f0cbcb8add099c723cf84634f46df2f788

Perfectに判定可能になりました。
以下サンプル:

``` vim
let wi = getwininfo(win_getid())[0]
if wi.loclist
    echo "Curwin is location list"
elseif wi.quickfix
    echo "Curwin is quickfix"
endif
```
