### ISSUE TITLE
ファイル名の補完時に / を使いたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1203]
Windows でまともにシェル連携するには noshellslash になってしまうんですが、例えば html の script タグを書く際に <kbd>CTRL</kbd>-<kbd>x</kbd> <kbd>CTRL</kbd>-<kbd>f</kbd> するとバックスラッシュ区切りになってしまい、最後にスラッシュに書き換えるという事になってしまいます。
出来れば内部処理は noshellslash、挿入モードではスラッシュでファイル名補完という動きにしたい。

**Comment by mattn** [comment]
https://gist.github.com/768851cd7c466033abd0c2ad5ea0242b

completepathslash というオプションを追加。ドキュメントとテストが必要。

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/3612

**Comment by h-east** [comment]
これ、ずっとモニョってるんです。twitterでGIF動画見ても全然ピンと来ないんです。
実践に即したサンプルかGIF動画を見せて欲しいです。
オプションを足すのがベストなソリューションなのか、オプション名は妥当かどうか、よくわからないです。

**Comment by mattn** [comment]
noshellslash だと例えば

```html
<link rel="stylesheet" href="" media="all">
```
この href の部分を補完で埋めると `.\css\style.css` になるので、後から `/` に書き換える必要があるんですが、このオプションがあると最初から `./css/style.css` で編集できるという事です。

**Comment by h-east** [comment]
shellslash 運用がダメな理由ってなんででしょうか？

**Comment by mattn** [comment]
あらゆる物が動かなくなるからです。外部コマンド実行に unix like shell は使いたくないので。

**Comment by mattn** [comment]
例えば shellslash にすると vim はシェルが unix like shell だと認識するので `shellescape()` が UNIX 向けのエスケープをします。そのまま cmd.exe に渡すとエラーになります。

**Comment by h-east** [comment]
私はWindowsで`shellslash`運用してます。`shell`はデフォルトのまま(cmd.exe)です。
特に困ってないですね。まぁ、使うのは、grep.exe, diff.exe, ctags.exeとかぐらいですけど。

あぁ、Vim script経由でなんか動かす時に問題が出るということですね。

**Comment by h-east** [comment]
> 例えば shellslash にすると vim はシェルが unix like shell だと認識するので shellescape() が UNIX 向けのエスケープをします。

この挙動を直すのは無しですか？

:h shellescape()

		MS-WindowsとMS-DOSでは、'shellslash' が設定されていない場合、
		{string}をダブルクォートで囲み、{string}の中のダブルクォートを
		全て二重にする。
		そうでなければ、{string}をシングルクォートで囲み、"'" を
		"'\''" で置き換える。

		↓ (変更)

		MS-WindowsとMS-DOSでは、'shellslash' が設定されていない場合か
		'shell' の値の末尾が "cmd.exe" である場合は、
		{string}をダブルクォートで囲み、{string}の中のダブルクォートを
		全て二重にする。
		そうでなければ、{string}をシングルクォートで囲み、"'" を
		"'\''" で置き換える。

**Comment by mattn** [comment]
Vim がパスをどう扱うかの話と、補完中のパスが / かどうかは別の話だと思います。

**Comment by h-east** [comment]
このIssueの書き出しがこれ↓で、

> Windows でまともにシェル連携するには noshellslash になってしまうんですが、

これに対して、この質問をしたら、
> shellslash 運用がダメな理由ってなんででしょうか？

以下の回答が返ってきました。
> 例えば shellslash にすると vim はシェルが unix like shell だと認識するので shellescape() が UNIX 向けのエスケープをします。そのまま cmd.exe に渡すとエラーになります。


'completepathslash' を追加した動機が上記なのですよね？
だったら、その大元を直しましょうよ。
'completepathslash' オプションの追加は後ろ向きな改善だと感じます。

**Comment by mattn** [comment]
僕が shellslash の話を出したのは、昔 Bram に noshellslash でも / を扱いたいという話を出した時に unix shell を使えばいい、cmd なのであれば noshellslash だと言われてしまったからです。

あと shellslash がまともに動いたとしても僕はこのオプションが欲しいです。なぜなら shellslash を使わないからです。もともと shellslash は unix-like shell の為に用意されています。

```
	オンのときは、ファイル名の展開にスラッシュが使われる。これは
	command.com や cmd.exe の代わりにUnix系のシェルを使うときに便利である。
	'\' も入力できるが、Vimによってスラッシュに変換される。
```

最近の Windows はパスとして / を扱う事も出来ますが、これは引数の話で例えばコマンド名に / を使う事は出来ません。

つまりファイル補完を / で出したいか \ で出したいかは shellslash の値に依存すべきでなく、書こうとしているファイルに依存します。例えば Web 系であれば / を使いますが、バッチファイルであれば \ を使いたいです。これは PR  先で Bram も言ってます。

**Comment by h-east** [comment]
理解しました。
このIssueの書き出しで、「何で shellslash じゃダメなの？」ってところに気持ちが持っていかれました。

> Windows でまともにシェル連携するには noshellslash になってしまうんですが、

これが最初の方にあれば`ガッテンがいった`と思います。
> つまりファイル補完を / で出したいか \ で出したいかは shellslash の値に依存すべきでなく、書こうとしているファイルに依存します。例えば Web 系であれば / を使いますが、バッチファイルであれば \ を使いたいです。

**Comment by Milly** [comment]
8.1.1769
Merged vim/vim@ac3150d
