### ISSUE TITLE
折り畳みのマーカーにcommentstringが反映されない

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#1205]
## 質問・報告の内容

折り畳みの開始行内に `* ` (アスタリスク + 空白)が存在すると、commentstringが反映されないようです。

https://twitter.com/kaitou_ryaku/status/1064241058307956736

## Vimのバージョン

Vim8.1 適用済パッチ: 1-500

## OSの種類/ディストリ/バージョン

*   Windows 7 Home 64bit
*   MSYS2 (32bit版、64bit版ではなく、無印のMSYS2です)

**Comment by h-east** [comment]
### 再現手順
以下の内容の test.c を用意。
```c
int f(int* a) {
    return 0;
}
```
Vim 起動。
```
$ vim --clean +1 +"set foldmethod=marker foldlevel=99" test.c
```
foldマーカーを付与。
```
zfG
```
### 想定する結果
```c
int f(int* a) {/*{{{*/
    return 0;
}/*}}}*/
```
### 実際の結果
```c
int f(int* a) {{{{
    return 0;
}/*}}}*/
```
### 原因
'comments'の`mb:*`(つまり、`* ` (アスタリスクの後に空白))に一致して、コメント内だと判定してしまっている。
その為、`/* */` を付けずに単に 'foldmarker' の開始文字 `{{{` を追加している。
```
:set comments?
  comments=sO:* -,mO:*  ,exO:*/,s1:/*,mb:*,ex:*/,://
```

### 対策
`* `(アスタリスクの後に空白)が見つかっただけでコメント内だと判定するのはガバガバ過ぎるので、もうちょい判定を追加する。
例えば、「`* `が見つかって、かつ、その前または後ろすべてが空白文字ならコメント内」とか。

**Comment by h-east** [comment]
あっ、 @kaitou-ryaku さん、Issue登録ありがとうございます。

**Comment by h-east** [comment]
patch書きました。問題なさそうなら、testを追加してvim_devに提案します。
https://gist.github.com/h-east/060b310576cd87369437eebb753d29ab

**Comment by h-east** [comment]
test追加。(Gist rev.2)

**Comment by h-east** [comment]
Sent patch to vim_dev:+1:
https://groups.google.com/d/msg/vim_dev/towU5ZCb58w/-YMn_GYACgAJ

**Comment by h-east** [comment]
2018-11-25のruntimeファイル更新でTodoリスト入りしていました。
https://github.com/vim/vim/commit/b730f0c7ba36492d795f081b19bbcb85cdf0f50f#diff-38d7929bd26d74d92ceddf984bbfc8dbR131

> Adding a fold with a marker in a C file doesn't add the comment /* */ if the
line contains a * somewhere.  Patch with a fix (Hirohito Higashi, 2018 Nov 22)

**Comment by h-east** [comment]
8.1.0574 で直りました:+1:
(patchの内容は前日にreleaseされた 'commentstring' 関連の[8.1.0570](https://github.com/vim/vim/commit/539328197c51c1586cbbb6b6be3db3c412249b49) をアレンジする内容になっています)
https://github.com/vim/vim/commit/4af7259b2b35e85c590d54908fcd248d2c733be8
