### ISSUE TITLE
端末モード用の :tabbrev がない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1208]
## 質問・報告の内容

`:tmap` はありますが `:tabbrev` がありません。
端末モードでも abbreviation が使えると便利なのでほしいです。

`git diff` とか `git log` の `--name-only` を最近よく使うので、
`tabrrev n@ --name-only` とか他にも `tabbrev s@ git status` とかやりたかったのがきっかけです。
あと類似機能としては zsh の global alias があります。
http://d.hatena.ne.jp/keno_ss/20140214/1392330322

## Vimのバージョン

8.1.536

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.17134)

**Comment by tyru** [comment]
よく考えずに出してしまいましたが、キー入力が実行してるシェルとかに送られた後に書き換えるのどうすればいいのって感じですね… 頭回ってなくて申し訳ないです。
マッピングを追加することにします。

**Comment by ujihisa** [comment]
欲しさでいうと、めちゃくちゃ欲しいです。こういうのが理由でアクティブにvimshell使ってます。

**Comment by tyru** [comment]
一応 `:terminal` とほぼ同時ぐらいに `:h prompt-buffer` っていうのも追加されてるので、vimshell みたいなのも実装しやすくなってると思います。
https://gist.github.com/tyru/448cd0c5839236a2390be2e042b35dd0
