### ISSUE TITLE
type() の結果の定数が欲しい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#121]
`type()` の結果は数値であり、`:help type()` では以下のような使い方をしろと書いてある。

``` vim
:if type(myvar) == type(0)
:if type(myvar) == type("")
:if type(myvar) == type(function("tr"))
:if type(myvar) == type([])
:if type(myvar) == type({})
:if type(myvar) == type(0.0)
```

しかし、
- パッと見わかりづらい
- function は長い
- 定数を得るために関数呼び出しをするのはパフォーマンス上気になる(まあ微々たるもんでしょうが)

などの理由で改めて定数を用意することがよくある。
どうせなら最初から `v:` などに組み込み定数として用意してあると嬉しい。

**Comment by thinca** [comment]
定数名は、一番シンプルに考えるなら型名そのままですかね。長いと結局利便性も落ちるので。

```
v:number
v:string
v:funcref
v:list
v:dict
v:float
```

`dictionary` は長いので `dict` にしてみた。

**Comment by koron** [comment]
v:listとか、多分ほかで使うんじゃないかなぁ。
t:とか新しいprefixを作るかv:t_みたいなほうが良くない?

他の定数を考えるとc:のほうが良いのかしら?

**Comment by thinca** [comment]
うーん、やっぱりそうですかねぇ。

```
v:t_number
v:t_string
v:t_funcref
v:t_list
v:t_dict
v:t_float
```

`c:`とかの新しいプレフィックスを追加するのってやりたいことに対して大仰すぎちゃうかなーって感じちゃうんですが、そこは他の方はどう思うでしょう?
ちなみに`t:` はタブローカルですでに使ってますね。

**Comment by mattn** [comment]
s:true/s:falseネタに近い気もしなくないですね。
僕は c: はあまり好きくない。

**Comment by Shougo** [comment]
そうですね。近い問題ですね。あれも却下されてしまったしなぁ。

**Comment by koron** [comment]
似てるけど #38 は型追加のはなしでしたからね。あと見なおしたらこんなのあった。これがまさに「別issue」のはなしですね。

> constの話とBoolean型は別なので、constが必要なら別にissue建ててください。

**Comment by k-takata** [comment]
作ってみた
https://bitbucket.org/k_takata/vim-ktakata-mq/src/65e91e14e7a002bad5660a2aad59734f4a0d9764/v_type.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
現状、jobとchannelはマジックナンバーを使わざるを得ないので、そこを焦点にすればいけるかもしれない。

**Comment by k-takata** [comment]
https://groups.google.com/d/topic/vim_dev/zsQBAsEzp80/discussion
v:true, v:false, v:null, v:none なんてものも追加されたんだし、ついでに10個ぐらい定数が増えてもいいよね。

**Comment by k-takata** [comment]
todo入りです。

> Patch to define v:t_number etc. (Ken Takata, 2016 Jul 15)

Bram からは、"I like it." という返事ももらっているので、近いうちに入るかもしれません。

**Comment by k-takata** [comment]
7.4.2071
https://groups.google.com/d/topic/vim_dev/fZSq_MhReAI/discussion
