### ISSUE TITLE
テキストプロパティ機能を叩く 

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1210]
Vimに導入されたばかりのテキストプロパティ機能について議論しましょう。

テキストプロパティを叩いてバグを出す。
テキストプロパティ APIの仕様について議論する。
その他、テキストプロパティ機能に関すること何でも。
次のリリースが出たら、このissueは閉じます。

**Comment by mattn** [comment]
要望: バッファを指定するとバッファ内の全てのテキストプロパティ一覧を得られる関数が欲しい。

**Comment by mattn** [comment]
要望: `{lnum}` が引数の箇所は全て `'.'` を指定出来る様にしたい。`{col}` も。

**Comment by mattn** [comment]
highlight が動いてない？

```vim
let s:id = 0
function! s:Add(...)
  let s:id += 1
  call prop_type_add('note' . s:id, {
  \ 'highlight': 'MoreMsg',
  \ 'property': join(a:000, "\n"),
  \ 'bufnr': bufnr('.'),
  \})
  if line("'<") == line("'>")
    call prop_add(line("'<"), col("'<"), {'length': col("'>") - col("'<") + 1, 'type': 'note' . s:id})
  elseif visualmode() == "\<c-v>"
    for i in range(line("'<"), line("'>"))
      call prop_add(i, col("'<"), {'length': col("'>") - col("'<") + 1, 'type': 'note' . s:id})
    endfor
  else
    call prop_add(line("'<"), col("'<"), {'length': col("$") - col("'<") + 1, 'type': 'note' . s:id})
    for i in range(line("'<")+1, line("'>")-1)
      call prop_add(i, 1, {'length': len(getline(i)), 'type': 'note' . s:id})
    endfor
    call prop_add(line("'>"), 1, {'length': col("'>"), 'type': 'note' . s:id})
  endif
  "echo prop_list(line("'<"))
endfunction

command! -range -nargs=+ TextPropAdd call s:Add()
```

テキストを選択して

```
:'<,'>TextPropAdd foo
```
しても色が付かない。

**Comment by h-east** [comment]
`prop_type_add()`のプロパティタイプエントリーの`start_incl`と`end_incl`の1/0での挙動の違いが見たくていろいろ弄ったけど変化ない。ソースコード見たら描画時には未だ参照してなかったww

**Comment by mnishz** [comment]
`:set number` のときと `:set nonumber` のときでハイライトされる位置が変わらないので、行番号が考慮されていないように見えました。

**Comment by mattn** [comment]
あれ？色付きました？

**Comment by h-east** [comment]
`:h E971`のExampleで色つきますよ。

**Comment by mattn** [comment]
あー、通常の syntax よりも弱いのか。

**Comment by mattn** [comment]
![terminal6](https://user-images.githubusercontent.com/10111/50149927-d7af0b80-02ff-11e9-9d01-8b2129829bd9.gif)

**Comment by mattn** [comment]
col と lnum の指定が文字単位でなく可視座標で描画されてるっぽい。

![terminal6](https://user-images.githubusercontent.com/10111/50150455-61aba400-0301-11e9-95f8-dd86a7e21b05.gif)

**Comment by h-east** [comment]
> :set number のときと :set nonumber のときでハイライトされる位置が変わらないので、行番号が考慮されていないように見えました。

8.1.0663 で直りました。
https://github.com/vim/vim/commit/8caa10a8ec6e398fd67c30b8a2bf20638d3c6c0a

あと、`'spell'`セット時の類似バグについても 8.1.0665 で直りました。
https://github.com/vim/vim/commit/c6d86dccc4edff8627e309fb23dc8f810ef36b28

**Comment by h-east** [comment]
> あー、通常の syntax よりも弱いのか。

8.1.0638 で直りました。
https://github.com/vim/vim/commit/48f88ac85be8446a42a03cec45264eac21f9eba8

既存のsyntaxよりも優先して描画されるようになりました。

**Comment by h-east** [comment]
[8.1.0675](https://github.com/vim/vim/commit/b9c67a51c15481d9257e5c26581d17780e9808d5)で
`prop_add()`の第2引数`{col}`と第3引数`{prop_add}`のエントリー`length`の単位がバイトになりましたよ。

**Comment by mattn** [comment]
↑のスクリプトが動き出したので更新しておきました。

**Comment by k-takata** [comment]
8.2 がリリースされたので閉じます。
