### ISSUE TITLE
incsearch設定後の範囲指定:tabで<CR>なしでも E14: 無効なアドレスです と表示される

### ISSUE THREAD

**Issue by rapan931** [vim-jp/issues#1211]
## 質問・報告の内容

incsearchを設定してvimを起動
```
vim.exe -Nu NONE -c "set incsearch | append | hoge"
```

起動後に以下のように範囲選択後`:tab`と入力すると、incsearch設定時は`<CR>`なしでも`E14: 無効なアドレスです`が表示されてしまいます。

```
V:tab
```

incsearch未設定時は範囲選択後`:tab`と入力してもE14が表示されませんでした。
incsearch未設定時、範囲選択後`:tab<CR>`だとE14が表示されます。

E14のエラーメッセージは`<CR>`入力後に出るべきだと思いますので、
incsearch設定時の挙動についてご確認をお願いいします。

## Vimのバージョン

VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 24 2018 23:02:26)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-635

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

Windows 7 64bit

## 使用している or 関係していそうなプラグイン

なし

## その他

set incsearch後に適当に範囲選択して`:<tab>(長押し)`してみましたが、`:tab`だけ、E14が出ているようでした。

**Comment by h-east** [comment]
Issue登録お疲れ様です:+1:
コマンドラインのincsearch処理のコマンドライン修飾子のパース処理なのに、スキップせずに真面目にエラーチェックしてました。

Patch書きました。これで直ります。
https://gist.github.com/h-east/5f829b2cd118b7de5c57e7776744b7be

テストは今晩書く予定です。

(追記: テスト追加完了 Rev.2)

**Comment by h-east** [comment]
Sent to vim_dev
https://groups.google.com/d/msg/vim_dev/9603xLnJh8U/FxC4kwiHEwAJ

**Comment by h-east** [comment]
8.1.0640 で修正されました。
https://github.com/vim/vim/commit/548e5985734e4b216852205879daf9bfb00dbe5a

**Comment by rapan931** [comment]
対応ありがとうございました！！
