### ISSUE TITLE
「aunmenu *」した後に「popup Edit」 すると「E341: Internal error: lalloc(0, )」が発生する

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#1215]
## 質問・報告の内容

以下のように`aunmenu *`した後に`popup Edit` すると`E341: Internal error: lalloc(0, )`が発生してしまいました。
```
aunmenu *
popup Edit
" E341: Internal error: lalloc(0, )
echo getcompletion('*', 'menu')
" ['Edit.']
echo getcompletion('Edit.', 'menu')
" ['Paste']
```

で、私が調べた限りこの根本的な原因は`aunmenu *`が`tlnoremenu`の定義をちゃんと考慮できてないことが原因のようです($VIMRUNTIME/menu.vimには`tlnoremenu`の定義が含まれている)。
 例えば、
```
cnoremenu	 &Edit.&Paste<Tab>"+gP		<C-R>+
tlnoremenu	 &Edit.&Paste<Tab>"+gP		<C-W>"+
aunmenu *      " tlnoremenu以外の定義のみが削除されるっぽい
popup Edit      ” tlnoremenu側の定義が補完されるっぽい
tlunmenu Edit " 削除すれば。。。
popup Edit      ” E337: Menu not found - ...と正常の動作になる
```
のようです。

そもそも、`aunmenu *`は`tlnoremenu`の定義も削除しちゃってよいか？Menu modes(`MENU_TERMINAL_MODE`など)を意識して敢えて削除してないのかなど、そのほかのメニューコマンドと仕様の整合性を取るとなると私一人では無理そうだったので、一旦ここ（vim-jp/issues）に投稿しました。

 以上、よろしくお願いいたします。

## Vimのバージョン

vim 8.1.682

## OSの種類/ディストリ/バージョン

* macOS  Mojava ver10.14.2
* Terminal.app ver2.9.1 (421.1)

## 使用している or 関係していそうなプラグイン

なし

## その他

ちなみに上記の例で`E341: Internal error: lalloc(0, )`したときの発生場所ですが、pum_show_popupmenu関数のalloc_clear関数をpum_size==0で呼び出してしまい、内部のlalloc関数でエラーとなっています。

__popupmnu.c__
```
    void
pum_show_popupmenu(vimmenu_T *menu)
{
    vimmenu_T   *mp;
    int		idx = 0;
    pumitem_T	*array;
#ifdef FEAT_BEVAL_TERM
    int		save_bevalterm = p_bevalterm;
#endif
    int		mode;

    pum_undisplay();
    pum_size = 0;
    mode = get_menu_mode_flag();

    for (mp = menu->children; mp != NULL; mp = mp->next)
	if (menu_is_separator(mp->dname)
		|| (mp->modes & mp->enabled & mode))
	    ++pum_size;

    array = (pumitem_T *)alloc_clear((unsigned)sizeof(pumitem_T) * pum_size);
```

**Comment by h-east** [comment]
@rbtnn Issue登録お疲れ様です。
検討項目が2つありますね。

1. メニュー項目はあるが(現状のモードに則した)サブメニュー項目がない場合のエラー内容について
`E341: Internal error: lalloc(0, )`が出るのはどうなの？`Internal error`と言われるとちょっとびっくりするよ？これっぽい文言に変更してはどうか？

  ```c
  static char_u e_othermode[] = N_("E328: Menu only exists in another mode");
  ```

 2. `:amenu`, `:aunmenu`の仕様について
- `:amenu`は「**端末モード以外**の全てのモードで使えるメニューの項目を1度に定義することができる」とドキュメントに記述がありますね。
```
The ":amenu" command can be used to define menu entries for all modes at once,
except for Terminal mode.
```
- `:aunmenu`は特に記述はありませんが、例にコメントがかかれています。
`:h :unmenu-all`

        :aunmenu *	" remove all menus in all modes
`:amenu`の記述は`:tlmenu`が追加された時に書かれたもので、`:aunmenu`のコメントは修正漏れだと思います。ですので、現状の動作が仕様で、`:aunmenu`のドキュメントを修正すればいいのかなと思っています。

        :aunmenu *	" remove all menus in all modes, except for Terminal mode.
(**端末モード以外**の全てのモードの全てのメニューを取り除く)

ご意見お待ちしてます。

**Comment by rbtnn** [comment]
@h-east 

> static char_u e_notsubmenu[] = N_("E327: Part of menu-item path is not sub-menu");
> static char_u e_othermode[] = N_("E328: Menu only exists in another mode");

1に関して、新しいエラーメッセージを新設するにしてもE327とE328の２つ合体したようなメッセージになってしまうので、E327かE328のどちらかを出力すればよいんじゃないかと私は思います。
親切ではあるけど似たようなメッセージを作っても...と迷いますね。

2に関して、`:aunmenuのドキュメントを修正すればいいのかな`でいいだと思います。

**Comment by rbtnn** [comment]
https://gist.github.com/rbtnn/9b85eae581f80f3b86082bd561782895

エラーメッセージについては要相談したいですが、修正としてはこんな感じでしょうか？

**Comment by h-east** [comment]
エラーメッセージは`E328`で良いんじゃないかと思います。
その場合、menu.cの`static char_u e_othermode[] = N_("E328: Menu only exists in another mode");`を、global.hのL1596に移動させればいいのかな？変数名は`e_menuothermode`に替えた方がいいのかもしれないですね。

あと、`:h :aunmenu`(`:unmenu-all`)は明確に「端末モード以外を削除する」という記述を例以外に記述した方が良いかもしれないですね。

ちょっと酩酊気味です、すいません。

**Comment by rbtnn** [comment]
@h-east 
https://gist.github.com/rbtnn/9b85eae581f80f3b86082bd561782895
更新しました。
修正点としては以下の２つです。レビューよろしくお願いいたします。

1) E328のエラーメッセージを使うようにし、globals.hに移動
2) `:h :aunmenu`については、コメントの箇所は変更せずにNoteとして明記

**Comment by h-east** [comment]
良いと思います👌
例のコメントは変更した方が良いと思いました。お任せします。

**Comment by rbtnn** [comment]
https://github.com/vim/vim/pull/3765

@h-east PR作成しました。あとはBramさんの判断に任せましょう。レビューありがとうございました。

**Comment by h-east** [comment]
👍 

そういえば、以下の補完候補取得時は現在のモードを見ていないのでは現状通りの動作で良いと思います。`:menu <Tab>`で`Edit.`が補完されるのと同じですね。(Enter押したら`E328`)
```vim
echo getcompletion('*', 'menu')
" []
popup
" 補完候補に「Edit」が表示されちゃダメ
```

**Comment by rbtnn** [comment]
@h-east 
>そういえば、以下の補完候補取得時は現在のモードを見ていないのでは現状通りの動作で良いと思いま<す。:menu <Tab>でEdit.が補完されるのと同じですね。(Enter押したらE328)

はい、このissueおよびPRではこの件についてはふれない＆変更しないことにしました。さっき、気が付きましたけど、関連しそうなissueがすでにvim側にありました。

https://github.com/vim/vim/issues/3563

**Comment by h-east** [comment]
8.1.0695 で修正されました:+1:
https://github.com/vim/vim/commit/f42b45d719e03218735b3c2845a74dca9c0efd60
