### ISSUE TITLE
Unicode の欧文半角が正確に表示されない

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#1216]
EN QUAD / EN SPACE / EN DASH が ambiwidth の影響下にある現状を改変しています。
本来的には日本語で言うところの半角と同じ 1 セルで表示されるべき文字です。
https://ja.wikipedia.org/wiki/En_(単位)

**Comment by ghost** [comment]
タイトル入力に失敗しています…

Unicode では EN 系の三文字だけ半角を強制される(ものと理解している)んですが、英論文などでは高頻度で利用されている(と聞いた) EN DASH が ambiwidth に設定したセル幅で表示される場合があります。chcp 932 後の環境なんかがそうですね。

ambiwidth = 2 のとき、EN DASH が混ざった桁数の多い文字列を表示して折り返しをさせると、改行の入るポイントが文字列の末端方向にずれてしまい、最終的に周囲数行の表示順が入れ替わってしまいます。ambiwidth = 1 のときは乱れません。

Windows コマンドラインのコンパイラ cl.exe の日本語ヘルプメッセージの末尾近くにあるハイフンが、なぜか脈絡なく EN DASH になっていたために Vim での ConPTY コンソールの表示が乱れ、問題を認識できました。winpty コンソールでは ambiwidth がどうあれ正常に表示されたと思います。

以下、修正分です。

**Comment by ghost** [comment]
````diff
diff --git a/src/mbyte.c b/src/mbyte.c
index 26233e423..8c9074a61 100644
--- a/src/mbyte.c
+++ b/src/mbyte.c
@@ -1414,6 +1414,15 @@ utf_uint2cells(UINT32_T c)
     int
 utf_char2cells(int c)
 {
+    /* Sorted list of non-overlapping intervals of EN(single width characters
+     * in typesetting) that are not affected by p_ambw and CJKV. */
+    static struct interval singlewidth[] =
+    {
+	{0x2000, 0x2000},
+	{0x2002, 0x2002},
+	{0x2013, 0x2013}
+    };
+
     /* Sorted list of non-overlapping intervals of East Asian double width
      * characters, generated with ../runtime/tools/unicode.vim. */
     static struct interval doublewidth[] =
@@ -1590,6 +1599,8 @@ utf_char2cells(int c)
 #else
 	if (!utf_printable(c))
 	    return 6;		/* unprintable, displays <xxxx> */
+	if (intable(singlewidth, sizeof(singlewidth), c))
+	    return 1;		/* EN chars, forced by typesetting */
 	if (intable(doublewidth, sizeof(doublewidth), c))
 	    return 2;
 #endif
````

**Comment by ghost** [comment]
Linux/Unix 側で歴史的などなんらかの問題が既知であるという情報なりあればご教示ください。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/3775

**Comment by mattn** [comment]
キャプチャが正しい結果の物なのか間違った結果の物なのか分かりづらい気がします。
もし正しくない結果の物であれば、パッチ後の物も見たいです。可能であれば赤かなんかでマーカー入れた方が良さそうですね。(どこを指して言っておられるのか分からなかったので)

**Comment by mattn** [comment]
![image](https://user-images.githubusercontent.com/10111/50752715-8658c300-1292-11e9-9be8-0fa34681c92d.png)
こんな？

**Comment by ghost** [comment]
ありがとうございます。その部分です。マーカーを入れたキャプチャを貼ってきました。
MS のコンパイラ cl.exe のヘルプメッセージの末尾なんですが、その部分だけ EN DASH なんですよね。理由は不明です。

**Comment by mattn** [comment]
http://www.unicode.org/Public/11.0.0/ucd/EastAsianWidth.txt

これによると

`\u2000` は `N` (Neutral)
`\u2002` は `N` (Neutral)
`\u2013` は `A` (Ambiguous)

ですね。

**Comment by mattn** [comment]
mintty も `\u2013` は ambiguous width ですね。

![image](https://user-images.githubusercontent.com/10111/50760903-6635fd80-12ac-11e9-861d-a7dc52b27bbd.png)

**Comment by ghost** [comment]
色々すみません。うーん…
私が Java 部分の読み方を間違えてる感じですね…意味合いが違うのかな…
https://www.fileformat.info/info/unicode/char/2013/index.htm

cmd.exe が特殊なことをしているという話に集約されていくと思うので、変数 enwidth とかこれは今思いついたんですがそういうものを作ってそちらにセル数を設定していく感じですか、たぶん。

とりあえず、出したパッチは一時撤回してきます。要検討というか、ちょっと enwidth 的な話を振ってみます。これをどうにかしないと ConPTY パッチを出しづらいので、早々になんとかしたいです。

**Comment by mattn** [comment]
一度この辺で提案した気がします。

https://github.com/vim/vim/pull/2074

**Comment by ghost** [comment]
読みました。BABEL BABEL BABEL...
COMSPEC からの起動先が cmd.exe の時だけ EN DASH を 1 セルに調整するか、もしくは一切今まで通り何もいじらないか、ですかね…。
どちらにせよ変数 enwidth 的なものは現在の描画状態を知るうえで新設したいかもしれないです。

**Comment by mattn** [comment]
設定したい数が結構多くなる可能性があるんですよねー。なので環境変数はもしかするとオーバーしちゃうかも。

**Comment by ghost** [comment]
設定はテキストファイルにせよ、と誰かが(誰?)いつも言っているような気がするので、ノンプログラマにもわかりやすいようなフォーマットを持ったテキストファイルを読むのが妥当な線かなと思います。
ディレクトリが一つ増えることになるかもしれないですね。
Bram さんの負担にならないように…。

**Comment by h-east** [comment]
> Bram さんの負担にならないように…。

だったら、まずはtest書きましょうよ。ご自身の書いたpatchを守る目的もあります。

私の `Is it difficult to write tests?` のあなたの返しがこれなのですがその場しのぎだったのでしょうか？

> I have not written a test yet.
To write only C is a little loss...

https://groups.google.com/d/msg/vim_dev/arkFB0S5Cq8/MHC2pNMVDgAJ
https://groups.google.com/d/msg/vim_dev/arkFB0S5Cq8/29Xz9DMaDgAJ

**Comment by ghost** [comment]
UCD連邦はすでにセル幅の問題を超越しているというのか…！
とりあえず Unicode 12.0 の仕様、特に ZWJ まわりの話を見るにつけ、セルとはいかに？
後続ワードを見ないとセル幅が決まらない罠があるとは思っておりませんで、しかし様子見はしたくないので、先に ConPTY のパッチを出してしまいます(この際 EN DASH は先送りで)。テストもあるよ！

考えてみたらテキストにしてノンプログラマにいじってもらうような内容でもないし、って考えなくてもわかれという気はしますが。

そもそも俺が折れたのはあんたのせいじゃないよ！外部要因で折れるほど寝ボケちゃいないッ！
これ以上場を汚したくも汚させたくもないので後があるなら直メールでひとつよろしくお願いします。

**Comment by h-east** [comment]
> これ以上場を汚したくも汚させたくもない

何言ってるんです？
今までテスト書いた実績がない人に「テスト書きましょうよ」って言ってるだけなんですが。
普通に OK か NO で返せばいいだけだと思うんですけどね。
汚してるのはどっちなんですかね。

**Comment by ghost** [comment]
私怨四連発乙！issue の話題にちょっとは沿ってね！

なんにせよどのターミナルの上で動作してるかは検出しないといけないので(VCON含む)、これは情報取得シーケンスを送った直後に応答がキーバッファに入ってくるんですが、その時点で先行的に入力されていたキー情報の扱いをどうするかが山なんですね。回避方法の実装には物量的にしばらくかかります。
cmd.exe であれば EN DASH の特例を入れます。

**Comment by ghost** [comment]
MS に直で聞いてみました。
https://github.com/Microsoft/console/issues/353

**Comment by mattn** [comment]
Ref: https://github.com/vim/vim/commit/08aac3c6192f0103cb87e280270a32b50e653be1
