### ISSUE TITLE
ウィンドウがバックグラウンドでもカーソルが点滅してしまう

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1217]
## 質問・報告の内容

再現手順:

Windows版gVimを起動し、すぐに他のウィンドウをフォアグラウンドにする。
カーソルが白抜きになるのを確認する。
'updatetime' の時間（デフォルト 4秒）待つ。
カーソルが点滅を始める。

## Vimのバージョン

8.0.1279 以降

## OSの種類/ディストリ/バージョン

Windows
(GTKは未確認)

## 使用している or 関係していそうなプラグイン

なし

## その他

[8.0.1279](https://github.com/vim/vim/commit/040c1feb212568cf04265e59b26182f8b76057aa) では、gVimの起動を高速化するために、一部のメニュー項目を遅延ロードするようにし、CursorHold, CursorHoldI 自動コマンドでそれらの項目をロードするようにしました。なぜかこれにより、カーソルが点滅を開始するようになってしまいました。

**Comment by h-east** [comment]
Gnome-GTK2 では起きませんでした。
Windowsのguiコードの実装が良くないとおもってます。

**Comment by mattn** [comment]
CursorHold から走る処理を SetupColorSchemes だけにして、さらにその中でやってる処理を縮めていってみましたが `an` または `aunmemu` を実行するとカーソルが点滅し始めました。

```
  for name in names
    exe "an 20.450." . idx . ' &Edit.C&olor\ Scheme.' . name . " :colors " . name . "<CR>"
    let idx = idx + 10
  endfor
  silent! aunmenu &Edit.Show\ C&olor\ Schemes\ in\ Menu
```

**Comment by mattn** [comment]
これですね。

https://github.com/vim/vim/blob/b589f95b38ddd779d7e696abb0ea011dc92ea903/src/menu.c#L2086

出所が 5.4 とかで追跡は無理

https://github.com/vim/vim-history/commit/7310439b8d08bad9b8029a9709e90fc54d21f23b

**Comment by mattn** [comment]
この行消して試してるけど特に問題ないなぁ。コメントによると tearoff メニューよりメインウィンドウにフォーカス与える為にあるらしいけど、だっただらこの行にあるのおかしいし。

追記

gui_mch_tearoff の中でも SetActiveWindow やってるやん。

```
    /*
     * Reassert ourselves as the active window.  This is so that after creating
     * a tearoff, the user doesn't have to click with the mouse just to start
     * typing again!
     */
    (void)SetActiveWindow(s_hwnd);
```

**Comment by mattn** [comment]
ケース|メインウィドウにフォーカスが戻る
-|:-:
`:tearoff Edit` 直後| OK
メニューから破線を選択| OK
tearoff されたメニューのアイテムをクリック直後| OK
tearoff されたメニューのクローズ直後| OK

他どんなケースがありますかね。消してしまいたい。

**Comment by mattn** [comment]
https://github.com/vim/vim/issues/3778

**Comment by h-east** [comment]
8.1.0782 で直りました。mattn++
https://github.com/vim/vim/commit/2d951a486e632f99fe039c0b0a1685f1fe7879b2
