### ISSUE TITLE
ジョブを終了させたシグナルの情報を取れるようにする

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1218]
ジョブのプロセスがシグナルにkillされたとき、現状では `job_info(job).exitval == -1` になる。
ろくに情報がないので、killしたシグナルを取れるようにしたい。

`job_info()` のフィールドに `termsig` を追加しました。
値は `WTERMSIG()` のシグナル名 (`term`, `hup` など) またはシグナル番号 (の文字列) です。
シグナル名については os_unix.c の `signal_info` を参照しています。

https://github.com/ichizok/vim/compare/fix/job-exitval

**Comment by ichizok** [comment]
os_win32.c には対応入れてませんが、何か手段あるでしょうか。

**Comment by mattn** [comment]
Windows には signal は無いので取れないです。UNIX でだけ使えます的なコメントを doc に入れておいて貰えますか。

**Comment by ichizok** [comment]
@mattn 了解です。

**Comment by mattn** [comment]
Windows 版には辞書に termsig 入れずにおいてプラグイン作者も Windows には無い事を意識させた方がいいのかも。

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/3786

**Comment by ichizok** [comment]
v8.1.0863
https://github.com/vim/vim/commit/b3051ce82f2e8af95ce3b6a41867f70aee5ecc82
