### ISSUE TITLE
set cursorcolumn すると curswant がupdateされてしまう

### ISSUE THREAD

**Issue by tkuro11** [vim-jp/issues#1219]
## 質問・報告の内容
CursorHold と CursorMoveで 'cursorcolumn' をオンオフしているのですが、
CursorMoveの set nocursorcolumnで常に curswantがリセットされてしまうため、
空白行で常に行頭に移動してしまいます。
'cursorline'と同様に、flagsをP_RWINONLYにすれば良いと思うのですが、P_RWINに
なっているのに何か理由があるのでしょうか？

```patch
diff --git a/src/option.c b/src/option.c
index 414e65a1f..ca3e3d830 100644
--- a/src/option.c
+++ b/src/option.c
@@ -989,7 +989,7 @@ static struct vimoption options[] =
     {"cursorbind",  "crb",  P_BOOL|P_VI_DEF,
                            (char_u *)VAR_WIN, PV_CRBIND,
                            {(char_u *)FALSE, (char_u *)0L} SCTX_INIT},
-    {"cursorcolumn", "cuc", P_BOOL|P_VI_DEF|P_RWIN,
+    {"cursorcolumn", "cuc", P_BOOL|P_VI_DEF|P_RWINONLY,
 #ifdef FEAT_SYN_HL
                            (char_u *)VAR_WIN, PV_CUC,
 #else
```
## Vimのバージョン

8.1
patches: 1-744

## OSの種類/ディストリ/バージョン

Ubuntu 18.04.1 LTS

**Comment by h-east** [comment]
:+1: そのpatchで良さそうです。
テスト書かれますか？
あと、ご自分でvim_devにpatch送付されますか？

**Comment by tkuro11** [comment]
テストは test_cursor_func.vim に統合したほうが良いのでしょうか？　独立の方がbetter?

```patch
diff --git a/src/testdir/test_cursor_func.vim b/src/testdir/test_cursor_func.vim
index d784e3678..75021a2dd 100644
--- a/src/testdir/test_cursor_func.vim
+++ b/src/testdir/test_cursor_func.vim
@@ -46,3 +46,24 @@ func Test_curswant_with_autocommand()
   quit!
 endfunc
 
+
+" Tests for behavior of curswant with cursorcolumn/line
+func Test_curswant_with_cursorcolumn()
+  new
+  call setline(1, ['01234567', ''])
+  exe "normal! ggf6j"
+  call assert_equal(6, winsaveview().curswant)
+  set cursorcolumn
+  call assert_equal(6, winsaveview().curswant)
+  quit!
+endfunc
+
+func Test_curswant_with_cursorline()
+  new
+  call setline(1, ['01234567', ''])
+  exe "normal! ggf6j"
+  call assert_equal(6, winsaveview().curswant)
+  set cursorline
+  call assert_equal(6, winsaveview().curswant)
+  quit!
+endfunc
```
patch送付はやったことないのですが、普通にココと同じように連絡すれば良いのでしょうか？
＃しかし、特に「絶対に自分で」というほどではないです。

**Comment by h-east** [comment]
@tkuro11 書かれたテスト、ナイスだと思います:ok_hand:

> patch送付はやったことないのですが、普通にココと同じように連絡すれば良いのでしょうか？

はい。
How to reproduce, Expected behavior, Actual behavior 的なものを書いて、patchを添付します。
もしくは、https://github.com/vim/vim にPull Requestを出しても良いです。お好きな方で。

> ＃しかし、特に「絶対に自分で」というほどではないです。

言っていただければ代行させていただきます。

**Comment by tkuro11** [comment]
おもしろそうだったのでpull request してみました. なにか問題ありそうだったら教えてください。https://github.com/vim/vim/pull/3806

**Comment by k-takata** [comment]
GitHubのprofileに本名(っぽいもの)を書いておくとBramの印象がよくなります。
匿名だとパッチの採用を渋られたり、採用されたパッチに名前が載らなかったりする場合があります。

**Comment by h-east** [comment]
8.1.0754 で入りました。おめでとうございます！
https://github.com/vim/vim/commit/177ab9e0262b1b3a6120bea655864ead487210e5

また何かありましたらよろしくお願いします。

**Comment by tkuro11** [comment]
丁寧なアドバイスありがとうございました。助かりました。
