### ISSUE TITLE
neocomplcacheにおいて &l:omnifunc が ClangComplete のとき、  neocomplcache#manual_omni_complete() を使用すると SEGVる。 

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#122]
2chにて報告されていた問題です。

http://toro.2ch.net/test/read.cgi/unix/1322212163/82

> neocomplcacheにおいて &l:omnifunc が ClangComplete のとき、 
> neocomplcache#manual_omni_complete() を使用すると SEGVる。 
> 
> neocomplcache#manual_omni_complete() から 
> omni_complete.vim の s:source.get_complete_words() 内で 
> call('ClangComplete', [0, '']) が呼ばれると 
> g:clang_use_library == 1 のとき ClangComplete() で dllが使用されるとSEGVる。 
> これは g:neocomplcache_enable_prefetch の値に関係なく起こる。 
> gdb 
> Program received signal SIGSEGV, Segmentation fault. 
> 0x004197e3 in ins_compl_next (allow_get_expansion=0, count=1, insert_match=1) 
> at edit.c:4611 
> 4611 else if (compl_shows_dir == BACKWARD 

現在のneocomplcacheはclang_completeのオムニ補完関数に対応していません。
だから、動く保証は全くないのですが、SEGVするのはさすがにVimの問題だと思うためこちらに報告しました。

**Comment by thinca** [comment]
dllでのSEGVはさすがにVimにはどうしようもないのでは?

**Comment by mattn** [comment]
落ちてる箇所がvimのソースなのが少し気になる。

**Comment by koron** [comment]
具体的になにを実行した時になるんだろう?

(特定の状況下で)スクリプトからインサートモードの<C-N>押下をエミュレートした?

**Comment by Shougo** [comment]
最新版では、オムニ補完は`<C-x><C-o>`で呼ぶことができるため、この問題はありません。
