### ISSUE TITLE
:!start </がセパレータの相対パス> でファイルが開けない(E371: コマンドがありません)

### ISSUE THREAD

**Issue by rapan931** [vim-jp/issues#1220]
## 質問・報告の内容

Windowsで `:!start </がセパレータの相対パス>`  の場合にファイルが開けません。
ただ、`:!start </がセパレータの絶対パス>` の場合にはファイルが開けます。

以下は試したことです。

``` vim
" 前提: 拡張子 .vim に gvim.exe で開く設定をしている
" gvim.exe -Nu NONEでvim起動
:cd $VIMRUNTIME
:!start colors\desert.vim              " gvim.exeでファイルを開ける
:!start colors/desert.vim              " エラーでファイルを開けない(E371: コマンドがありません)
:!start D:/path/to/colors/desert.vim   " gvim.exeでファイルを開ける
:! start colors/desert.vim             " gvim.exeでファイルを開ける
:! start D:/path/to/colors/desert.vim  " gvim.exeでファイルを開ける
:! start colors\desert.vim             " gvim.exeでファイルを開ける
```

## Vimのバージョン

 VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 14 2019 23:41:19)
 MS-Windows 64 ビット GUI 版 with OLE サポート
 適用済パッチ: 1-751

## OSの種類/ディストリ/バージョン

Windows 7

## 使用している or 関係していそうなプラグイン

特にありません。

## その他

特にありません。

ご確認宜しくお願いいたします。

**Comment by mattn** [comment]
拡張子 `.vim` に gvim.exe で開く設定をされているという事でよいでしょうか。

**Comment by rapan931** [comment]
> 拡張子 .vim に gvim.exe で開く設定をされているという事でよいでしょうか。

わかりづらくすみません。
はい。その通りです。(質問・報告の内容に記載したコメントも修正しました。)

**Comment by k-takata** [comment]
`ShellExecuteEx` API の仕様がそうなっている感じがします。
`ShellExecuteEx` を使う[自作コマンド](https://github.com/k-takata/startw)でも同じ挙動でしたので。

(`.\colors/desert.vim` だと開けますね。謎…)

**Comment by mattn** [comment]
```
:!start colors\desert.vim              " gvim.exeでファイルを開ける
:!start colors/desert.vim              " エラーでファイルを開けない(E371: コマンドがありません)
:!start D:/path/to/colors/desert.vim   " gvim.exeでファイルを開ける
:! start colors/desert.vim             " gvim.exeでファイルを開ける
:! start D:/path/to/colors/desert.vim  " gvim.exeでファイルを開ける
:! start colors\desert.vim             " gvim.exeでファイルを開ける
```
下の3つは cmd.exe の組み込みコマンド start の仕様です。正直 start が何をやってるかは仕様が公開されていないので分かりません。上3つは ShellExecute の仕様です。

```c
#include <windows.h>

int
main(int argc, char* argv[]) {
  ShellExecute(NULL, "open", argv[1], NULL, NULL, SW_SHOWNORMAL);
  return 0;
}
```
こんなコマンド作って `colors\test.txt` というファイルを作ってテストしたところ↑の上3つの結果の通りでした。

正直、これを直すのは難しい(組み込み start コマンドの仕様が分からない)と思います。

**Comment by mattn** [comment]
元々 `!start` は `cmd /c start` の様に DOS 窓を出さない為に組み込まれた物なので「cmd.exe の start と同じ動作にする為に cmd.exe を使う様に修正する」というのも出来ないので。

**Comment by rapan931** [comment]
@k-takata , @mattn 調査ありがとうございます。

> 正直、これを直すのは難しい(組み込み start コマンドの仕様が分からない)と思います。

承知しました。

個人的にはこの動作でそこまで困っていませんし、
`!start`でファイルを開きたかったら、絶対パス指定 or セパレータ`\`の相対パス指定 で開けるので。このままでも問題ないかと思います。

こちらのIssue、Closeしてしまってもよいでしょうか？
もしくはCloseの判断をお任せしたほうが良いでしょうか？

**Comment by k-takata** [comment]
（Windowsの）仕様ということで閉じましょう。
ShellExecuteに渡す前に `/` を `\` に置き換えてしまうのもよい手だとは思えませんし…
