### ISSUE TITLE
nnoremap で設定した コマンドが Netrwのバッファ上で有効にならない

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1221]
## 質問・報告の内容
nnoremap で設定した コマンドが Netrwのバッファ上で有効になりません。
ウィンドウを分割した際に、 例えば左側のウィンドウにはsh で移動できるように、_vimrcに下記のように設定しています。
"nnoremap sh < C-w >h"
しかし、Netrwのバッファ上では sh が有効になっておらず移動できません。
< C-w >hでは移動が可能です。
Netrwのバッファ上でもコマンドを有効にするには、_vimrcにどのように記載すればよいでしょうか？

## Vimのバージョン

Kaoriya Gvim
( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bitHome
## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by h-east** [comment]
_vimrcに`nnoremap sh <C-W>h`を足した状態でgVimを起動して以下のコマンドを実行してみましょう。

```vim
:rightbelow vsp
:verbose nmap s
```
以下のような感じで表示されると思います。
```
n  sh          * <C-W>h
        Last set from ~/.vimrc line 59
```
まだ、netrwが動いていないので、自分で設定したmapだけが表示されています。

次に、netrwを動かして再度mapを確認します。
```vim
:Ex
:verbose nmap s
```

netrwが起動したので、netrwのmap `s` (ソートの種類変更)が設定されました。
```
n  s           *@:call <SNR>25_NetrwSortStyle(1)<CR>
        Last set from ~/tool/vim/runtime/autoload/netrw.vim line 6045
n  sh          * <C-W>h
        Last set from ~/.vimrc line 59
```

netrwがどんなmap設定をしているか、`Last set from ～`のファイルを開いて確認してみます。
```
   nnoremap <buffer> <silent> <nowait> s        :call <SID>NetrwSortStyle(1)<cr>
```

`<nowait>`指定されてますね。
`<nowait>`が指定されているので、`s`を入力すると即このmapが実行されます。

つまり、`sh`のmapは設定されているが、netrwの既存のmapで`s`を`<nowait>`で設定しているため、`sh`のmapが実行される契機がないということになります。
うーん、無理やり出来なくもないですが、netrwが使用していないキーにmapすることを検討されてはいかがでしょうか？

**Comment by ujihisa** [comment]
こんにちは、vimrcでまさに `"nnoremap sh <C-w>h"` ほかs+{h,j,k,l}してる者です。netrwのこのあたりつらい(ry

幸いにもnetrwのバッファはfiletype=netrwになっているので、例えば僕はいま[こんな設定](https://github.com/ujihisa/config/commit/55e5cf3205b140bd76c10eda8d3135e0a4e560f4)でnetrwのsを上書きしてみました。
(vimrcの外でやるなら ~/.vim/ftplugin/netrw.vimなどを作ってやると `autocmd FileType netrw nunmap <buffer> s` だけでいいのですっきりしそうです)

**Comment by ujihisa** [comment]
とコメント書きつつ、h-eastさんのいうようにプラギン標準キーを上書きしない方が、自分のvimrcのない別のサーバなどでvimるときにも上書きされる前のキーをスムーズに使えるよう自分が上達できるので便利というメリットもあります。

**Comment by hiro-github** [comment]
h-eastさん
詳細な説明をありがとうございます。
開いているバッファによって、キーマッピングの設定が変わることがよくわかりました。
キーマッピングの確認の仕方も知らなかったので、とても勉強になりました。
Netrwと競合しないキーマッピングにしたいと思います。

ujihisaさん
設定のコミットありがとうございます。
ウィンドウ移動時のキーマッピングを別のものにしたほうがよさそうですね。
