### ISSUE TITLE
scriptversion の運用検討

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1225]
Vim script は `a.b` という記法が「文字列の結合」と「辞書のアイテム参照」の2つで許されており AST (Abstruct Syntax Tree)化できない為、高速化を図る事ができません。そこで Perl の `use strict` や JavaScript の `strict` の様に、Vim script の記法を厳密にする為のディレクティブを用意してはどうかと思い付きました。

```
scriptstrict
```

このディレクティブがある場合は以下の制限が掛かります。

* `a.b` という文法では文字列結合は処理しない。したい場合は `a . b` と書く。
* 追加予定

こうする事で AST 化できない理由を潰してしまいます。そしてうまく行った暁には Vim script を AST 化して高速化します。これで速くなるとおそらく皆 `scriptstrict` を付けたがるので次第に `a.b` を使うスクリプトが少なくなる、という構想です。

https://github.com/vim/vim/pull/3857

**Comment by mattn** [comment]
なんとなく動くやつ出来た。これを使うつもりなくて単に Bram にどういう物かを分かってもらう為の物。

https://gist.github.com/mattn/0167afc2e4125dce640c03eb01db0de5

見せるスクリプトはこれ

```vim
" Concating strings: This is OK
let a = 'a'
let b = 'b'
echo a.b

" Reference item in dictionary: This is OK
let a = {'b': 'b'}
echo a.b

" Then, scriptstrict flag on.
scriptstrict

" Concating strings: This is NG
let a = 'a'
let b = 'b'
try
  echo a.b
catch
  echohl ErrorMsg | echo 'Do not use "." for concating strings!' | echohl None
endtry

" Concating strings but include space before dot: This is OK
let a = 'a'
let b = 'b'
echo a .b

" Reference item in dictionary: This is OK
let a = {'b': 'b'}
echo a.b
```

**Comment by h-east** [comment]
```vim
:h Blob
/Dot
```

        Dots can be inserted between bytes (pair of hex characters) for readability,
        they don't change the value:
                :let b = 0zFF00.ED01.5DAF

Blobのこの`.`は`0z` or `0Z`で区別つくので、このIssueの件では気にしなくていいんですよね？

**Comment by mattn** [comment]
そうですね。それよりも

```
:echo 0zFF00.ED01.5DAF
0zFF00ED01.5DAF
:echo len(0zFF00.ED01.5DAF)
6
````
なんだろこれw

**Comment by mattn** [comment]
```
    char_u *
blob2string(blob_T *blob, char_u **tofree, char_u *numbuf)
{
    int		i;
    garray_T    ga;

    if (blob == NULL)
    {
	*tofree = NULL;
	return (char_u *)"0z";
    }

    // Store bytes in the growarray.
    ga_init2(&ga, 1, 4000);
    ga_concat(&ga, (char_u *)"0z");
    for (i = 0; i < blob_len(blob); i++)
    {
	if (i > 0 && (i & 3) == 0)
	    ga_concat(&ga, (char_u *)".");
	vim_snprintf((char *)numbuf, NUMBUFLEN, "%02X", (int)blob_get(blob, i));
	ga_concat(&ga, numbuf);
    }
    *tofree = ga.ga_data;
    return *tofree;
}
```
bram なんでこれ入れたんだろ。

**Comment by mattn** [comment]
4バイト単位で `.` で区切りたかったのかな。。。

**Comment by k-takata** [comment]
そのはず

**Comment by k-takata** [comment]
`0z.12`って書くと文字列結合とみなされてエラーになるのか。

**Comment by tsuyoshicho** [comment]
これ表面的にはどちらか不明確にはなりますが、aが文字列or辞書で一意で、通常動作としてはエラーにははないんですよね...type hintにいきそうになる案件でもあるなあ...

strict導入時に禁則が増えるごとに、vim本体でテストできる+修正できるような補助機能があると嬉しい...かもしれない?
Pythonも苦労したようだし、同じ轍にならないようにしないとですねえ...

**Comment by tsuyoshicho** [comment]
そういえば、以前slackで指摘をうけた

```
 call s:Promise.new({resolve -> s:Job.start(cmd, {
            \ 'stdout': [''],
            \ 'stderr': [''],
            \ 'on_exit':{ exit_status -> resolve(exit_status) },
          \ })
          \})
          \.catch({ exc -> execute('echomsg string(exc)', '') })
          \.finally({->
          \  delete(tags_lock_path)
          \})
```

のresolveのような、定義済み関数を変数名に使う系はどうでしょうね。
パース的にはちゃんとやれば大丈夫だとは思うんですが、これもAST的にはWarningにしたほうがよいです?(識別できるから、不要?)

**Comment by mattn** [comment]
もし安全なら vint 行きな気がしますね。あと thinca さんが言ってた `v:count` を `count` で参照するのも制限したいです。

**Comment by h-east** [comment]
8.1.1114 で文字列の連結を `..` および `..=` でおこなえるようになった。
https://github.com/vim/vim/commit/0f248b006c2574abc00c9aa7886d8f33620eb822

8.1.1116 で`:scriptversion`コマンドが追加された。
https://github.com/vim/vim/commit/558ca4ae55096f8763ab8515a304cda9c57f18a7

**Comment by k-takata** [comment]
> `v:count` を `count` で参照するのも制限したいです。

提案してみました。 https://github.com/vim/vim/pull/4274

**Comment by k-takata** [comment]
Bramはおおむね同意しているが、scriptversionを3に上げろと言っている。そんなにすぐに上げる必要あるかなぁ？

**Comment by mattn** [comment]
scriptversion 65535

**Comment by k-takata** [comment]
8.1.1188: https://github.com/vim/vim/commit/d2e716e6dfd50b605867c7c684373384c8edf707

**Comment by h-east** [comment]
このスレ閉じて良い？

**Comment by k-takata** [comment]
今後のためにさらに制限した方がよい文法とかありますかね？
curly brace変数とか？

**Comment by tsuyoshicho** [comment]
一応、参考までにslackでここ最近話題になった以下もありかなあ、とか

* | などの奇妙なコマンド類のスクリプト内での使用の制限
* リストへ種別の違う値の混在の制限
* (数字のドット繋ぎでの文字列化は、たぶんどうしようもないかな...)

前者については、自分は数字で行飛びは使うw
後者は影響が大きそう(トリッキーに使ってるのは多そう)
※必要とおもっているというより、open/closeのための判断材料の足しです。

もうひとつくらい話題になった、古い仕様の話はあった気がするけど、思いだせず

## 参考

ゴリラさんのslack発言より
https://vim-jp.slack.com/archives/C03C4RC9F/p1555284879151600

```
Viとの互換性のために、以下の奇妙なコマンドがサポートされている。
        :|                      現在行を表示する (":p" と同様)
        :3|                     3行目を表示する (":3p" と同様)
        :3                      3行目に移動する
```

mattnさんのslack発言より
https://vim-jp.slack.com/archives/C03C4RC9F/p1555377608395300

```
[0.1, 0.2, 0.3, 0.4]｀ と書こうとして途中のカンマを1つ ｀.｀ とタイプし間違えて ｀[0.1, 0.2. 0.3, 0.4]｀ と書いたらそのまま通ってしまった
```

**Comment by k-takata** [comment]
> * | などの奇妙なコマンド類のスクリプト内での使用の制限

文法上の曖昧性がなく、AST化ができるなら問題ない気もします。
`:3 | echo "a"` を実行したら、カーソルが3行目に移動し、3行目を表示して、"a" が表示されました。怪しい…

> * リストへ種別の違う値の混在の制限

混在を認める言語はほかにもありますし、今から制限する利点はあまりないように思います。

> * (数字のドット繋ぎでの文字列化は、たぶんどうしようもないかな...)

`:scriptversion 2` ではエラーになるので問題ないはず。

**Comment by mattn** [comment]
タイトル変えました。

**Comment by tsuyoshicho** [comment]
>> (数字のドット繋ぎでの文字列化は、たぶんどうしようもないかな...)

> :scriptversion 2 ではエラーになるので問題ないはず。

おっとそうでしたか、すみません。

まあ上に挙げたのは問題ないものだというところだったと。

**Comment by tsuyoshicho** [comment]
ヘルプ見てて気になったこと: `.` と類似の特性がありそうなものとして、以下もあるかもしれませんね。

> NOTE: mylist[s:e]と書くと変数 "s:e" をインデックスとして使ったと解釈される。
":" の前に1文字の変数を使うときは十分注意すること。必要ならこのようにスペース
を入れるとよい: mylist[s : e].

制限されるとしたら、あいまいになるときはエラーしてくれるようになるとか?

**Comment by tyru** [comment]
@tsuyoshicho 

> 制限されるとしたら、あいまいになるときはエラーしてくれるようになるとか?

多分ここら辺の話は lint の仕事で、scriptversion の仕事は個人的に
「backward compatibility のために仕方なく残っている部分を scriptversion の指定によって直感的に書けるようになる」
という事だと思ってます。

**Comment by tyru** [comment]
#1290 として別に issue 挙げましたが、ここで他に懸念材料なければ close 可能かと思います (たぶん)

**Comment by tyru** [comment]
閉じちゃいます。
