### ISSUE TITLE
ex_cmdidxs.h を更新する為のターゲットが Make_cyg_mingw.mak 等にない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1226]
新しい ex コマンドを追加すると最近では ex_cmdidxs.h を更新する必要があり、これは `create_cmdidxs.vim` を実行して生成されるのだけど Make_cyg_mingw.mak に make target が用意されていない。

```
cmdidxs: ex_cmds.h
	vim -u NONE -i NONE -X -S create_cmdidxs.vim
```
また ex_cmdidxs.h がどのファイルかの依存に指定されていないので更新しても対象のファイルがコンパイルされない。

※ Windows だけの問題です。

**Comment by k-takata** [comment]
PRed: https://github.com/vim/vim/pull/5337

**Comment by k-takata** [comment]
8.1.2413: https://github.com/vim/vim/commit/0ba89ec47c4c43414a89a6944803e2e1331a761d
