### ISSUE TITLE
:Unite file をすると一つ上の階層にしかいけない

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1227]
## 質問・報告の内容
:Unite file を実行すると、
../
がカーソルのすぐ下に出てくるのですが、これを選択して一つ上の階層にいくと、
../
が表示されなくて、これ以上、上の階層にいけません。
何か設定等が必要なのでしょうか？

## Vimのバージョン
Kaoriya GVIM

## OSの種類/ディストリ/バージョン
*   Windows 10 Home 64bit

## 使用している or 関係していそうなプラグイン
Unite.vim

**Comment by mattn** [comment]
https://github.com/Shougo/unite.vim

Unite に有識な方がこちらの方が多いはずなのでこちらで聞くのが良さそうです。

**Comment by hiro-github** [comment]
ありがとうございます。
unite.vimの方で、質問をしました。
