### ISSUE TITLE
gvim.exe起動時、`guioptions+=k`だとウィンドウサイズがおかしい

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#1228]
## 質問・報告の内容

`guioptions`に`k`が与えられていると
gvim.exe起動時のウィンドウサイズが、とても小さい状態で表示されます。

### 再現パターン

```sh
gvim.exe -u NONE --cmd ":se go+=k"
```

![v8.1.0626](https://user-images.githubusercontent.com/1814879/52270777-4403ce00-2985-11e9-8c83-d9f6b768e7d5.png)

## Vimのバージョン

8.1.0626以降。
8.1.0625以前では確認されませんでした。

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 64bit (バージョン1809、OSビルド17763.107)
* コンパイラ: nuwen.net MinGW gcc 8.2.0 (64bit)
* makeオプション: `make -f Make_ming.mak GUI=yes -j 8`

## 使用している or 関係していそうなプラグイン

ありません

**Comment by k-takata** [comment]
Related: https://github.com/vim/vim/issues/3808

**Comment by nocd5** [comment]
@k-takata 本家issue確認してませんでした、すいません。
参照追加ありがとうございます。

**Comment by k-takata** [comment]
8.1.1092: https://github.com/vim/vim/commit/372674fca3250069d8f4943b572474ce077849fd
