### ISSUE TITLE
スクリプトの行連結を高速化できないか

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#123]
Vimスクリプトでは行頭の `\` で行の連結ができますが、これが多い場合にスクリプトの読み込みに時間がかかることが知られています。これを解決できないかと考えています。

遅くなっている原因はex_cmd2.cのgetsourceline()とget_one_sourceline()によりますが、特に行連結に限ればgetsourceline()だけ考えれば良いでしょう。問題のコードはこんな感じです。

``` c
for (;;)
{
    sp->nextline = get_one_sourceline(sp);
    if (sp->nextline == NULL)
        break;
    p = skipwhite(sp->nextline);
    if (*p != '\\')
        break;
    s = alloc((unsigned)(STRLEN(line) + STRLEN(p)));
    if (s == NULL)      /* out of memory */
        break;
    STRCPY(s, line);
    STRCAT(s, p + 1);
    vim_free(line);
    line = s;
    vim_free(sp->nextline);
}
```

要点を整理すると
- 行連結を見つけた際に前後の行をひとつのバッファに合成する/strlenとallocとstrcpy/catが発生する
- 行連結が連続すると上記操作が無駄に繰り返される/同じ行の内容を何度もコピーする

という構造です。経験上、特にstrlenとstrcpy/catが痛いかも。

**Comment by koron** [comment]
対策としては連結行を見つけた場合は、それらをgarray_Tに格納しておいて最後にまとめてひとつに合成する、ことでしょう。ポイントはstrlen的な操作とmemcpy的な操作(走査とコピー)を最小限にすることと、あとメモリ開放をわすれないことになります。なので

``` c
struct {
   char_u* ptr_to_be_free;
   char_u* line_top; /* white skipped. */
   int len;
}
```

こんな構造をgarray_Tにとっとくとよさそうです。

**Comment by mattn** [comment]
少なくとも先に捜査して、そのインデックス内でjoinする様にすればゼロコピーでいけそうな気がする。

**Comment by mattn** [comment]
注意：このパッチは入れてはいけません。

うむ。いくらか差が出るね。

``` diff
diff -r 0dabc2ce136c src/ex_cmds2.c
--- a/src/ex_cmds2.c    Tue Jan 10 22:31:32 2012 +0100
+++ b/src/ex_cmds2.c    Thu Jan 12 10:35:16 2012 +0900
@@ -3437,25 +3437,26 @@
      * contain the 'C' flag. */
     if (line != NULL && (vim_strchr(p_cpo, CPO_CONCAT) == NULL))
     {
+   garray_T    ga;
+
    /* compensate for the one line read-ahead */
    --sourcing_lnum;
+   ga_init2(&ga, (int)sizeof(char_u *), 20);
+   ga_concat(&ga, line);
    for (;;)
    {
        sp->nextline = get_one_sourceline(sp);
        if (sp->nextline == NULL)
        break;
        p = skipwhite(sp->nextline);
-       if (*p != '\\')
+       if (*p != '\\') {
        break;
-       s = alloc((unsigned)(STRLEN(line) + STRLEN(p)));
-       if (s == NULL)  /* out of memory */
-       break;
-       STRCPY(s, line);
-       STRCAT(s, p + 1);
-       vim_free(line);
-       line = s;
-       vim_free(sp->nextline);
+       }
+       ga_concat(&ga, p + 1);
    }
+   ga_append(&ga, NUL);
+   vim_free(line);
+   line = ga.ga_data;
     }

 #ifdef FEAT_MBYTE
```

**Comment by mattn** [comment]
むむー。遅くなるケースもあるのか。

**Comment by mattn** [comment]
あ、開放漏れてた。

**Comment by mattn** [comment]
パッチ更新

``` diff

diff -r 0dabc2ce136c src/ex_cmds2.c
--- a/src/ex_cmds2.c    Tue Jan 10 22:31:32 2012 +0100
+++ b/src/ex_cmds2.c    Thu Jan 12 10:52:53 2012 +0900
@@ -3437,25 +3437,27 @@
      * contain the 'C' flag. */
     if (line != NULL && (vim_strchr(p_cpo, CPO_CONCAT) == NULL))
     {
+   garray_T    ga;
+
    /* compensate for the one line read-ahead */
    --sourcing_lnum;
+   ga_init2(&ga, (int)sizeof(char_u *), 20);
+   ga_concat(&ga, line);
    for (;;)
    {
        sp->nextline = get_one_sourceline(sp);
        if (sp->nextline == NULL)
        break;
        p = skipwhite(sp->nextline);
-       if (*p != '\\')
+       if (*p != '\\') {
        break;
-       s = alloc((unsigned)(STRLEN(line) + STRLEN(p)));
-       if (s == NULL)  /* out of memory */
-       break;
-       STRCPY(s, line);
-       STRCAT(s, p + 1);
-       vim_free(line);
-       line = s;
+       }
+       ga_concat(&ga, p + 1);
        vim_free(sp->nextline);
    }
+   ga_append(&ga, NUL);
+   vim_free(line);
+   line = ga.ga_data;
     }

 #ifdef FEAT_MBYTE
```

**Comment by koron** [comment]
www

**Comment by mattn** [comment]
https://gist.github.com/1598017

のソースを使って

```
:so foo.vim
```

した場合。オリジナルのvimだと

1回目: 0.619650
2回目: 0.622633
3回目: 0.617841

パッチ当てたvimの場合

1回目: 0.544637
2回目: 0.556371
3回目: 0.549445

となった。結構いいかもしれない。

**Comment by koron** [comment]
それだと一行しかないケースで、パフォーマンス悪化しそうなんだけど、なんでそうなってないんだろ?

**Comment by mattn** [comment]
今から1行のテストもしますね。

**Comment by mattn** [comment]
https://gist.github.com/1598072

のソースを使って(長すぎてバイナリ扱いされてますが...)

```
:so bar.vim
```

した場合。オリジナルのvimだと

1回目: 0.094956
2回目: 0.094568
3回目: 0.094608

パッチ当てたvimの場合

1回目: 0.107829
2回目: 0.108217
3回目: 0.108141

となった。まぁ間違いなくga_init2なんかのオーバヘッドなんだろうけど。
ちなみにfoo.vimは4行連結が2000個と2000行連結が1つ、bar.vimは1行連結のパターンが8000個以上あるソース。

**Comment by mattn** [comment]
単一行の時も通る事を考慮すればもすこし速いパッチ書けそう。

**Comment by koron** [comment]
++@mattn !

**Comment by mattn** [comment]
あー、バイト数なのに20はないわー。ないわー。増やしたらbar.vimでも同じ速度だった。
つまり使えるパッチになる。

**Comment by mattn** [comment]
パッチ更新

``` diff
diff -r 0dabc2ce136c src/ex_cmds2.c
--- a/src/ex_cmds2.c    Tue Jan 10 22:31:32 2012 +0100
+++ b/src/ex_cmds2.c    Thu Jan 12 12:08:27 2012 +0900
@@ -3439,22 +3439,30 @@
     {
    /* compensate for the one line read-ahead */
    --sourcing_lnum;
-   for (;;)
+
+   p = NULL;
+   sp->nextline = get_one_sourceline(sp);
+   if (sp->nextline != NULL && *(p = skipwhite(sp->nextline)) == '\\')
    {
-       sp->nextline = get_one_sourceline(sp);
-       if (sp->nextline == NULL)
-       break;
-       p = skipwhite(sp->nextline);
-       if (*p != '\\')
-       break;
-       s = alloc((unsigned)(STRLEN(line) + STRLEN(p)));
-       if (s == NULL)  /* out of memory */
-       break;
-       STRCPY(s, line);
-       STRCAT(s, p + 1);
+       garray_T    ga;
+
+       ga_init2(&ga, (int)sizeof(char_u *), 200);
+       ga_concat(&ga, line);
+       ga_concat(&ga, p + 1);
+       for (;;)
+       {
+       vim_free(sp->nextline);
+       sp->nextline = get_one_sourceline(sp);
+       if (sp->nextline == NULL)
+           break;
+       p = skipwhite(sp->nextline);
+       if (*p != '\\')
+           break;
+       ga_concat(&ga, p + 1);
+       }
+       ga_append(&ga, NUL);
        vim_free(line);
-       line = s;
-       vim_free(sp->nextline);
+       line = ga.ga_data;
    }
     }

```

以下計測予定

**Comment by mattn** [comment]
https://gist.github.com/1598017 の場合(foo.vim)

オリジナル

1回目: 0.619650
2回目: 0.622633
3回目: 0.617841

パッチ済み

1回目: 0.429687
2回目: 0.480521
3回目: 0.447725

https://gist.github.com/1598072 の場合(bar.vim)

オリジナル

1回目: 0.071133
2回目: 0.095809
3回目: 0.095556

パッチ済み

1回目: 0.073162
2回目: 0.097247
3回目: 0.097458

bar.vimは実質、実行コードが変わらないはずなので出てるのは誤差だと思う。
foo.vimは如実に結果が出た。

**Comment by koron** [comment]
bar.vimのほう誤差にしてはコンスタントに上昇している感があるんじゃないかな。
ステップ数が多くなったことでなにかあるのかなぁ?…ちょっと私も修正版作ってみます。

**Comment by koron** [comment]
あ、ga_init2()に渡すsizeofの中身、間違ってない? ただしくはchar_uでいいんじゃないかな?

**Comment by mattn** [comment]
あー、そうすね。直します。

**Comment by mattn** [comment]
``` diff

diff -r 0dabc2ce136c src/ex_cmds2.c
--- a/src/ex_cmds2.c    Tue Jan 10 22:31:32 2012 +0100
+++ b/src/ex_cmds2.c    Thu Jan 12 12:30:55 2012 +0900
@@ -3439,22 +3439,30 @@
     {
    /* compensate for the one line read-ahead */
    --sourcing_lnum;
-   for (;;)
+
+   p = NULL;
+   sp->nextline = get_one_sourceline(sp);
+   if (sp->nextline != NULL && *(p = skipwhite(sp->nextline)) == '\\')
    {
-       sp->nextline = get_one_sourceline(sp);
-       if (sp->nextline == NULL)
-       break;
-       p = skipwhite(sp->nextline);
-       if (*p != '\\')
-       break;
-       s = alloc((unsigned)(STRLEN(line) + STRLEN(p)));
-       if (s == NULL)  /* out of memory */
-       break;
-       STRCPY(s, line);
-       STRCAT(s, p + 1);
+       garray_T    ga;
+
+       ga_init2(&ga, (int)sizeof(char_u), 200);
+       ga_concat(&ga, line);
+       ga_concat(&ga, p + 1);
+       for (;;)
+       {
+       vim_free(sp->nextline);
+       sp->nextline = get_one_sourceline(sp);
+       if (sp->nextline == NULL)
+           break;
+       p = skipwhite(sp->nextline);
+       if (*p != '\\')
+           break;
+       ga_concat(&ga, p + 1);
+       }
+       ga_append(&ga, NUL);
        vim_free(line);
-       line = s;
-       vim_free(sp->nextline);
+       line = ga.ga_data;
    }
     }

```

ちなみに、行数が増えたのは1行の場合にオリジナルと同じ実行コードにする為。1行の場合にはga_init2が走らない。

**Comment by mattn** [comment]
上昇とは違いそうなんですよね。なぜかga_xxxは初回が抜群に速い。

**Comment by koron** [comment]
こうしてみた。

https://gist.github.com/1598475

ga_init2()のオーバーへッドはでるけど値セットしてるだけなので大したことないだろう、という推測。@mattn さんの最初の版との違いは、一行だけのときはgaにコピーせずに通過させた(つもりの)点。

**Comment by mattn** [comment]
僕の、１行の時通過しますよ？

**Comment by mattn** [comment]
最初の

``` diff
if (sp->nextline != NULL && *(p = skipwhite(sp->nextline)) == '\\')
```

がそれ

**Comment by mattn** [comment]
あー、初版との差ですね。
ちなみにそのオーバヘッドが実はまぁまぁ食ったので↑の様にしました。

**Comment by koron** [comment]
> @mattn さんの _最初の版_ との違い

最初の版はga_init2()の直後にga_concat()してたけど、こっちはしてないというだけです。で、今の版との違いは、連結かの判定が2ヶ所であるか1箇所にまとまってるか、という点ね。

> なぜかga_xxxは初回が抜群に速い。

grow時にcopyが走るからじゃないか?

**Comment by koron** [comment]
あ、さっきの僕のパッチ、バグってるw

**Comment by mattn** [comment]
実際、行連結してない行の方がおおいのでこっちの方がBram好みかも。

**Comment by mattn** [comment]
> あ、さっきの僕のパッチ、バグってるw

w

**Comment by koron** [comment]
https://gist.github.com/1598475

pをconcatする前に、ga_dataがNULLならlineを入れなきゃダメだた。

**Comment by mattn** [comment]
そうなんすよね。それをifせずに並べたのが僕の...になるんかな。

**Comment by koron** [comment]
ですね。メンテ的にはわけない方がよいけど、Vimのスピードへの偏向ぶりを考慮すれば分けるのも十分ありなんですが…って、行連結がまったく無い場合(buz.vim?)の速度差があるかどうかで判断したほうが良いかも。bar.vimは各一回だけ行連結してますよね。

ちなみに僕のバージョンはbuzでga_init2()のオーバヘッドがでて、fooでif文のオーバーヘッドがでるハズ。誤差でわかんないかもですがw

**Comment by mattn** [comment]
https://gist.github.com/1598017 の場合(foo.vim)

オリジナル

1回目: 0.619650
2回目: 0.622633
3回目: 0.617841

パッチ済み

1回目: 0.429687
2回目: 0.480521
3回目: 0.447725

https://gist.github.com/1598072 の場合(bar.vim)

オリジナル

1回目: 0.071133
2回目: 0.095809
3回目: 0.095556

パッチ済み

1回目: 0.073162
2回目: 0.097247
3回目: 0.097458

https://gist.github.com/1598628 の場合(baz.vim)

オリジナル

1回目: 0.060940
2回目: 0.060682
3回目: 0.060463

パッチ済み

1回目: 0.060466
2回目: 0.060791
3回目: 0.061160

**Comment by mattn** [comment]
テストをバッチ化して再度やってみた。

# foo.vim

4行連結が2000個、2000行連結が1個のミックス

| original | patched | % |
| --- | --- | --: |
| 0.613521 | 0.327214 | 53.3 |
| 0.573789 | 0.285416 | 49.7 |
| 0.573679 | 0.284159 | 49.5 |

# bar.vim

2行連結が12000個

| original | patched | % |
| --: | --: | --: |
| 0.071625 | 0.071539 | 99.9 |
| 0.070986 | 0.071226 | 100.3 |
| 0.070920 | 0.071064 | 100.2 |

# baz.vim

連結無しが10000個

| original | patched | % |
| --- | --- | --: |
| 0.048327 | 0.045425 | 94.0 |
| 0.045724 | 0.045227 | 98.9 |
| 0.045418 | 0.045434 | 100.0 |

**Comment by koron** [comment]
fooとbazは良いですね。barはやはりなんか理由がある気がしますが、問題にはならないんじゃないですかね。

このデータと合わせて出す価値ありだと考えます。

**Comment by mattn** [comment]
ベンチ用プロジェクト

https://github.com/mattn/vimjp-issue-123

報告の際に使うつもり。

**Comment by mattn** [comment]
報告ed

https://groups.google.com/d/topic/vim_dev/WCwNEgJXlb4/discussion

**Comment by koron** [comment]
Bram氏から前向きな反応きてますよ。ただパッチのインデント直してと言われてるみたいですが…どういうことだろ?
1. 文字通りインデントがetされてた
2. for (;;)内がインデント代えてコピペされていることを勘違い/指摘している

**Comment by h-east** [comment]
@koron 
https://gist.github.com/1600566 をダウンロードしてローカルで `set ts=8 sts=4 sw=4` で開いたら変数宣言部のインデントが一部ずれてるみたい。
https://lh3.googleusercontent.com/-jC4DfRqJho0/TxI4awoZV0I/AAAAAAAAA2w/Eu77hhzNfVM/w500-h413-k/indent.png

**Comment by mattn** [comment]
あれ？でも僕宛ての返信ですよね？

**Comment by h-east** [comment]
@mattn  あっ、ほんとですね。
Bram氏に「どのpatchのこと言うとんねん？」って聞きたい。

**Comment by koron** [comment]
https://groups.google.com/d/topic/vim_dev/0lR7PYTqdhs/discussion

included.
