### ISSUE TITLE
新しい a: スコープの変数を作成できてしまう

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#1231]
## 質問・報告の内容

`:help E742` には以下のように書かれています。

> The a: scope and the variables in it cannot be changed, they are fixed.

> (日本語help)
> a: のスコープとこの変数は固定されており、変更できない。

実際に存在している変数を変更しようとすると上記の通りにエラーになりますが、存在しない変数に代入すると問題なく実行できてしまいます。

```vim
function s:f() abort
  let a:foo = 10
  return a:foo
endfunction

echo s:f()
" => 10
```

## Vimのバージョン

8.10873

## OSの種類/ディストリ/バージョン

* Gentoo Linux

## 使用している or 関係していそうなプラグイン

なし

## その他

これは仕様上おかしいと言うだけで、特に何か困っているという事ではないです。
発見したので念のための報告になります。

**Comment by mattn** [comment]
https://github.com/mattn/vim/commit/10b2a530483b450c1d792b2cabf2d1797ef54e50

set_arg6 だけ行ける様にしています。

```
func s:set_arg1(a) abort
  let a:a = 1
endfunction

func s:set_arg2(a) abort
  let a:b = 1
endfunction

func s:set_arg3(a) abort
  let b = a:
  let b['a'] = 1
endfunction

func s:set_arg4(a) abort
  let b = a:
  let b['a'] = 1
endfunction

func s:set_arg5(a) abort
  let b = a:
  let b['a'][0] = 1
endfunction

func s:set_arg6(a) abort
  let a:a[0] = 1
endfunction
```

**Comment by ichizok** [comment]
`extend()` や `a:[...]` で拡張するケースが防げていません。

```vim
func s:set_arg7(a) abort
  call extend(a:, {'b': 1})
endfunction

func s:set_arg8(a) abort
  let a:['b'] = 1
endfunction
```

https://github.com/ichizok/vim/commit/56bc993ebe7cd0470a5db0c851eef7967ce77015
`VAR_FIXED` が必要と思います。

**Comment by mattn** [comment]
そちらのパッチの方が良さそうなのでそちらで投げて下さい。

**Comment by ichizok** [comment]
了解です。
それはそうと、すみません、
> `extend()` や `a:[...]` で拡張するケースが防げていません。

はパッチの当て方を失敗していたせいでした。

**Comment by ichizok** [comment]
PRed.
https://github.com/vim/vim/pull/3929

**Comment by ichizok** [comment]
8.1.0888
https://github.com/vim/vim/commit/31b816042fca879b11965ddd75287732563ba698

**Comment by ichizok** [comment]
以下で `a:000` が変更できてしまうことに気がついたので、追加で修正します。

```vim
func s:f(...) abort
  let b = a:000
  let b += [0]
endfunc
call s:f()
```

**Comment by ichizok** [comment]
PRed.
https://github.com/vim/vim/pull/3930

**Comment by ichizok** [comment]
8.1.0897
https://github.com/vim/vim/commit/05c00c038bc16e862e17f9e5c8d5a72af6cf7788

**Comment by thinca** [comment]
対応ありがとうございました！
