### ISSUE TITLE
Vim の式評価が適当すぎる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1232]
# 2進数表記

```vim
echo 0b19
```

`0b1` と `9` に分解され `1 9` と表示される。

# 間違った2進数表記で会話できる

```vim
let b99 = 'イェーイ！ujihisa さん見てるぅ？'
echo 0b99
```

```
0 イェーイ！ujihisa さん見てるぅ？
```

# 間違った16進数で会話できる

```vim
let xZZ = 'イェーイ！ujihisa さん見てるぅ？'
echo 0xZZ
```

```
0 イェーイ！ujihisa さん見てるぅ？
```

# C++ ユーザ定義リテラルの様な動作

```vim
let g1e090 = '㍉㍑'
echo 0x912ab30cbg1e090
```
```
38967914699 ㍉㍑
```

# 間違った2進数表記で関数呼び出し

```vim
echo 0b99()
```

# 演算子と符合の区別が甘い

```vim
echo 1 -- 1
```

なお、この挙動は関数呼び出しの引数などでは発動しない。あくまでコマンドラインで複数の引数を取れる `echo` もしくは `execute` で発生する。

オマケ

```
let yen = '円'
echo 100yen
```

**Comment by mattn** [comment]
ちょっと待ってみて直そうとされる方がいなければ、このまま vim/vim/issues に投げようと思います。

**Comment by ujihisa** [comment]
`# 演算子と符合の区別が甘い` とそれ以外でだいぶ違いそうなので、少なくともこれとこれ以外で分けて取り扱うのがよさそう。

**Comment by koron** [comment]
式の終端をどう決めるかがイイカゲンってことかぁ。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/3981

**Comment by mattn** [comment]
[patch 8.1.1355](https://github.com/vim/vim/commit/16e9b85113e0b354ece1cb4f5fcc7866850f3685)
