### ISSUE TITLE
echoで１文字目しか表示されない

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#1233]
## 質問・報告の内容

ちょっと原因もどういうときに発生するかもわかってないですが、Vim 8.0.0671からVim 8.1.0925の間にデグったみたいです。とりあえず報告だけですがよろしくお願いいたします。

_Vim 8.1.0925_
https://wandbox.org/permlink/duhfeBpASSMzXYO9
```
:echo "hoge"
" h
```

_Vim 8.0.0671_
https://wandbox.org/permlink/IWVXOfyRKoTebc0q
```
:echo "hoge"
" hoge
```

## Vimのバージョン

不明

## OSの種類/ディストリ/バージョン

不明

## 使用している or 関係していそうなプラグイン

なし
## その他

なし

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/3969

これで直る予定です。

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/3969 かな？

**Comment by k-takata** [comment]
一足遅かった。

**Comment by rbtnn** [comment]
あ、すでに発見されている問題だったんですね。

**Comment by rbtnn** [comment]
patch 8.1.0969にて直ったの確認できましたので閉じます。ありがとうございました。
https://github.com/vim/vim/commit/97c2c05ead689f4a5de986c82531fcbd09295cda

**Comment by rbtnn** [comment]
もしかしたら、まだ治ってないかもってことで再オープンしました。
この以下のGistのVim scriptがうまくいかないと思われるコードです。
https://gist.github.com/rbtnn/92d74d51f522be95ed059c0a97688aed

**Comment by mattn** [comment]
```
let lines += [ch_read(a:channel)]
```
は良くない気がします。正しくは

```
let lines += split(substitute(ch_read(a:channel), "\r", '', 'g'), "\n")
```
と思います。

**Comment by ichizok** [comment]
ちょっと改変。

```vim
function s:handler_close_cb(channel) abort
    let lines = []
    while ch_status(a:channel, {'part': 'out'}) == 'buffered'
        let lines += [ch_read(a:channel)]
    endwhile
    echomsg lines
endfunction

function s:main() abort
    let cmd = ['printf', '1\n2\n3']
    let job = job_start(cmd, {'close_cb' : function('s:handler_close_cb')})
endfunction

call s:main()
" ['1', '2', '3^@3^@3']
```

mode:nl の出力がNLで終端しない場合、最後のread結果がおかしいという現象。
原因はこのissueとは関係ないです。(#1125 関連?)

jobからの出力 `"1\n2\n3"` をreadしていくと、`node->rq_buffer` を `memmove()` で更新する際にNUL終端していないため後ろの領域の内容が残ってしまう。

**Comment by ichizok** [comment]
8.1.0993 で修正されました。
https://github.com/vim/vim/commit/772153f8d85c83e08427d93460a676d7f079f002
