### ISSUE TITLE
マクロ (complex-repeat) 実行中にバッファを変更すると reg_executing() の返り値が変わる

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#1236]
## 質問・報告の内容

`reg_executing()` 関数はマクロ (complex-repeat) として実行中のレジスタを表す一文字を返しますが、バッファの変更があるとマクロの実行中であっても空文字を返すようです。

例えば、次のようなスクリプトを実行します。

```
function! TestFunc() abort
  echomsg "before: " . reg_executing()
  normal! ia
  echomsg "after: " . reg_executing()
endfunction
nnoremap w :<C-u>call TestFunc()<CR>

messages clear
let @q = "w"
normal! @q
```

期待するのは、

```
before: q
after: q
```

ですが、実際には

```
before: q
after: 
```

となります。`after` の部分もまだマクロの実行中だと考えられるため、`before` の部分と同じ値が返ることが望ましいです。

## Vimのバージョン

8.0.946

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.17763.316)

## 使用している or 関係していそうなプラグイン

特になし

## その他

関連 #1152

**Comment by h-east** [comment]
現状のマクロ終了判定だとそうなってしまいますね。
`vgetorpeek()`のビッグ`do { ～ } while()`の直前の以下のコード。

```c
    if (advance && typebuf.tb_maplen == 0)
        reg_executing = 0;
```

うーん、なにかいい方法があるのかな？
私は今のところ良い案が浮かんでいないです。先にvim_devに報告した方が良いかもしれません。

**Comment by machakann** [comment]
ありがとうございます、内部的には終了していることになるんですね。後ほど vim-dev に報告します。

**Comment by machakann** [comment]
Posted. https://github.com/vim/vim/issues/4066

**Comment by machakann** [comment]
Fixed. https://github.com/vim/vim/commit/cce713ddcc0c9ab29926c28e287cbb587a959b08

**Comment by ichizok** [comment]
これだとダメですね。(`normal! ia` &rarr; `call getchar(0)`)

```vim
function! TestFunc() abort
  echomsg "before: " . reg_executing()
  call getchar(0)
  echomsg "after: " . reg_executing()
endfunction
nnoremap w :<C-u>call TestFunc()<CR>

messages clear
let @q = "w"
normal! @q
```

**Comment by machakann** [comment]
ありがとうございます、確かに失敗しました。コメントしておきます。

**Comment by machakann** [comment]
Fixed. https://github.com/vim/vim/commit/f0fab3046c2b5c4115979347464a802853011220
