### ISSUE TITLE
UNICODEの合成記号とlistオプションの組み合わせについて

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1237]
## 質問・報告の内容

UNICODE には幾つかの結合文字、例えば「が」「ぱ」などに使われる濁点や半濁点の扱いについて質問です
ここでは、
[Unicode 一覧_3000-3FFF](https://ja.wikipedia.org/wiki/Unicode%E4%B8%80%E8%A6%A7_3000-3FFF)
から濁点・半濁点をコピー&ペーストする例でお聞きします
なおここからコピーすると結合文字のために直前に半角空白が入り、更に表形式なので、文字コードで表すと次のデータになるとおもいます
0x20 0x3039 0x09 0x20 0x303A
### 問題・質問の前提の再現方法
1. vim -u NONE
    で Vim 起動
2. コピーした濁点・半濁点を貼り付け←問題なく表示されている
3. :set list listchars+=space:_
    を実行←濁点・半濁点が消え、_で表される半角スペースのみ表示される
4. カーソル移動して、ga コマンドでデータ自体は存在することを確認

#### 上記手順過程動画
![vim](https://user-images.githubusercontent.com/24851657/53470864-49e16080-3aa6-11e9-822a-89d4603d68e3.gif)

## Vim のバージョン
> $ vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)
> 適用済パッチ: 1-1766

### 質問内容

- これは意図してスペースのみを表示する仕様なのでしょうか? 上記過程だと_と濁点・半濁点の結合文字を表示して欲しいのですが
- 仕様でない場合、list, listchars を使いつつ回避する (_は表示されなくても良いので濁点・半濁点を表示する) にはどうすれば良いでしょうか?
- そもそも結合文字を結合しないで、今回の例なら半角スペースと濁点・半濁点を別々に表示する設定は有るでしょうか?

## OS の種類/ディストリ/バージョン

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.10
> Release:	18.10
> Codename:	cosmic
> $ uname -a
> Linux naonari 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## 使用している or 関係していそうなプラグイン
なし

**Comment by mattn** [comment]
バグですかね。

**Comment by mattn** [comment]
修正が足りない様なので後で直します。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/4046

**Comment by iranoan** [comment]
バグだったんですね
ありがとうございました
Ubuntuの公式パッケージを使っているので、そちらで反映されるのを待つことにします

**Comment by mattn** [comment]
[patch 8.1.1110](https://github.com/vim/vim/commit/e5e4e22c1c15c8c22b14935affe969569acc8df9) [patch 8.1.1078](https://github.com/vim/vim/commit/5f8069bbf5d989936a2f4d7a76ae42434017e3a2)
