### ISSUE TITLE
別の型から blob、blob から別の型に変換する方法が無い

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#1239]
ひとまず str2blob, blob2str を足しましたが、blob2nr や nr2blob はいるでしょうか？

https://github.com/mattn/vim/tree/blob2str-str2blob

**Comment by tsuyoshicho** [comment]
https://github.com/tsuyoshicho/vital-codec/blob/187b4752b96b1394ccb2ec66a542ee6bdbe2518e/autoload/vital/__latest__/Data/List/Byte.vim#L15-L21

むりやり自前でlist to blob / blob to listを実装したりしました。in Vim Script
もし早急に必要なら、上記コードが使えると思います。

**Comment by mattn** [comment]
更新忘れてました。この件、PR 出したのですが蹴られてしまいました。

https://github.com/vim/vim/pull/4049

**Comment by mattn** [comment]
他の誰かの強い要望が無ければ閉じます。

**Comment by tsuyoshicho** [comment]
なるほど...実際スクリプトでどうにかなるので自分は要望はあまりないです。

上記のモジュール経由で、str2blob/blob2strもできる、はずなので。

**Comment by mattn** [comment]
ありがとうございました。
