### ISSUE TITLE
vim.exe で termguicolors をオフにしても背景色が残る

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1240]
## 質問・報告の内容

Windows の vim.exe で以下の手順を実行

```
> vim --clean
:set tgc
:colorscheme desert    " 背景色が灰色になる
:set notgc   " 背景色が灰色のままになる
```

`set notgc` を実行した時点で背景色が黒に戻るのが期待値ですが、灰色のままになってしまいます。

## Vimのバージョン

8.1.0985

## OSの種類/ディストリ/バージョン

*   Windows 10 1809

## 使用している or 関係していそうなプラグイン

なし

## その他

なし

**Comment by k-takata** [comment]
vim.exe 起動時は `'t_Co'` は 16 ですが、`:set tgc` を実行すると 256 になり、その後 `:set notgc` を実行しても、`'t_Co'` が 256 のままですね。16 に戻るのが期待値だと思いますが。

**Comment by ghost** [comment]
set tgc する前の t_Co を set notgc 時に復元します。
数日様子を見て(自分の場合あわてると仕損じるので)、PR に仕立てます。

````diff
diff --git a/src/term.c b/src/term.c
index 8ee9264da..736c215f7 100644
--- a/src/term.c
+++ b/src/term.c
@@ -6815,6 +6815,7 @@ swap_tcap(void)
 # ifdef FEAT_TERMGUICOLORS
     static int		init_done = FALSE;
     static int		curr_mode;
+    static int		last_notgc;
     struct ks_tbl_s	*ks;
     struct builtin_term *bt;
     int			mode;
@@ -6843,6 +6844,7 @@ swap_tcap(void)
 	}
 	init_done = TRUE;
 	curr_mode = CMODEINDEX;
+	last_notgc = CMODEINDEX;
     }
 
     if (p_tgc)
@@ -6852,6 +6854,17 @@ swap_tcap(void)
     else
 	mode = CMODEINDEX;
 
+    if (curr_mode == CMODE24 && mode != CMODE24)
+    {
+	int tmp;
+
+	tmp = last_notgc;
+	last_notgc = mode;
+	mode = tmp;
+    }
+    else if (mode != CMODE24)
+	last_notgc = mode;
+
     for (ks = ks_tbl; ks->code != (int)KS_NAME; ks++)
     {
 	bt = find_first_tcap(DEFAULT_TERM, ks->code);
````

**Comment by k-takata** [comment]
t_Co=256 で set notgc の場合、VTPは有効になって256色モードになるんでしょうか？
ちょっと試した範囲では256色モードは動いていないような感じがしましたが。

tgcが16色モードとフルカラーモードを切り替えるだけなら、以下でもいいのかなと思いましたが。

```diff
diff --git a/src/os_win32.c b/src/os_win32.c
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -213,7 +213,7 @@ static int default_console_color_fg = 0x
 # endif
 
 # ifdef FEAT_TERMGUICOLORS
-#  define USE_VTP		(vtp_working && is_term_win32() && (p_tgc || (!p_tgc && t_colors >= 256)))
+#  define USE_VTP		(vtp_working && is_term_win32() && p_tgc)
 # else
 #  define USE_VTP		0
 # endif
diff --git a/src/term.c b/src/term.c
--- a/src/term.c
+++ b/src/term.c
@@ -6847,8 +6847,6 @@ swap_tcap(void)
 
     if (p_tgc)
 	mode = CMODE24;
-    else if (t_colors >= 256)
-	mode = CMODE256;
     else
 	mode = CMODEINDEX;
 
diff --git a/src/terminal.c b/src/terminal.c
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -3495,10 +3495,6 @@ init_default_colors(term_T *term)
 # endif
 # ifdef FEAT_TERMGUICOLORS
 	    || p_tgc
-#  ifdef FEAT_VTP
-	    /* Finally get INVALCOLOR on this execution path */
-	    || (!p_tgc && t_colors >= 256)
-#  endif
 # endif
        )
     {
```

**Comment by h-east** [comment]
testを足すなら`Test_termguicolors()`ですかね？

**Comment by ghost** [comment]
t_Co=256 、notgc で VTP が適用されて 256 色になります。今回のパッチ後でも動作はしています。

:colorscheme default 時の :intro の色調が変わるのでそこで目視判別も可能です。
動作確認には
https://github.com/KKPMW/moonshine-vim
を使っています。256色専用で 16 色でも 24 bit色でも動作しないものなので、微妙に便利です。

テストか…なんとかしないとなあ…

**Comment by k-takata** [comment]
t_Co=256 で VTP 効いていたんですね。気づいていなかった。

@ntak さんのパッチを当てて、colorscheme desert で t_Co=256 にすると背景が灰色になるのですが、mintty上で Cygwin または WSL 版の Vim で同じ設定にしても背景は黒のままなんですよね。256色でdesertの背景は何色が正しいのだろう？

**Comment by k-takata** [comment]
> 256色でdesertの背景は何色が正しいのだろう？

```vim
hi Normal	guifg=White guibg=grey20
```

ってなっているから、GUIとtgcの時だけ背景が灰色になるべきで、256色の時は黒になるべきだと思う。

**Comment by k-takata** [comment]
こうかな？

```diff
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -7230,7 +7230,7 @@ set_console_color_rgb(void)
 	return;
 
     id = syn_name2id((char_u *)"Normal");
-    if (id > 0)
+    if (id > 0 && p_tgc)
 	syn_id2colors(id, &fg, &bg);
     if (fg == INVALCOLOR)
     {
```

**Comment by ghost** [comment]
おお…(;´Д`)言われてみればそこはそれが正しいですね…ややこしさが発生している…
ありがとうございます、別パッチにして名義を確認しつつ私の方で PR 作業をしていいですか？

**Comment by k-takata** [comment]
パッチは別々に出す方がよさそうな気がします。

よく考えると、tgc をオフにしても t_Co=256 なのは別によくて、そもそもVTPが使用可能なら最初から t_Co=256 で起動すべきではという気もしてきました。（影響が大きいか？）
ちなみにUnixだと tgc をオン・オフしても t_Co の値は変更されないですね。t_Co=8 にして tgc をオンにしても t_Co=8 のままでした。（ただ、tgc オンで t_Co < 256 だと、それはそれでちゃんと動かないカラースキームも出てきそうな気もしますが。）

**Comment by ghost** [comment]
では私の方からは私が書いた分だけのものを PR にまとめます。

結局のところどうすべきかを考えてみると、Unix に合わせるのがベターなのかと思いはします。
作り込んでいた当時、とにかく画面の色がバグだかグリッチだかわからない原色になるのをとにかく避けようという思いがあったので、tgc と t_Co が連動する現状の仕様に落ち着きました。

今組み立て直したところ Unix に合わせた方が圧倒的に簡単な感が強くなってまいりました…
試しに組んでみます。

起動時のデフォルトを変えることについては、これはもう聞かないとわからないです。誰に？だろう…。ちょっと保留を。

**Comment by ghost** [comment]
set_termname での t_Co の再設定を抑制してみました。大勝利。
さてテストの書き様があるのかどうか…

````diff
diff --git a/src/option.c b/src/option.c
index b71093b86..35450e965 100644
--- a/src/option.c
+++ b/src/option.c
@@ -7776,7 +7776,16 @@ did_set_string_option(
 #if defined(FEAT_VTP) && defined(FEAT_TERMGUICOLORS)
     if (did_swaptcap)
     {
+	char_u *save;
+
+	highlight_gui_started();
+	control_console_color_rgb();
+
+	save = vim_strsave(T_CCO);
 	set_termname((char_u *)"win32");
+	set_string_option_direct((char_u *)"t_Co", -1, save, OPT_FREE, 0);
+	t_colors = atoi((char *)save);
+
 	init_highlight(TRUE, FALSE);
     }
 #endif
@@ -8801,8 +8810,15 @@ set_bool_option(
 	/* reset t_Co */
 	if (is_term_win32())
 	{
+	    char_u *save;
+
 	    control_console_color_rgb();
+
+	    save = vim_strsave(T_CCO);
 	    set_termname(T_NAME);
+	    set_string_option_direct((char_u *)"t_Co", -1, save, OPT_FREE, 0);
+	    t_colors = atoi((char *)save);
+
 	    init_highlight(TRUE, FALSE);
 	}
 # endif
diff --git a/src/term.c b/src/term.c
index 8ee9264da..b947fb39a 100644
--- a/src/term.c
+++ b/src/term.c
@@ -6788,7 +6788,6 @@ static struct ks_tbl_s ks_tbl[] =
     {(int)KS_CS,  "\033|%d;%dR", "\033|%d;%dR"},
     {(int)KS_CSV, "\033|%d;%dV", "\033|%d;%dV"},
 #  endif
-    {(int)KS_CCO, "256", "256"},	    // colors
     {(int)KS_NAME}			    // terminator
 };
 
````

**Comment by k-takata** [comment]
ああ、tgc をオン・オフすると、swap_tcap() で KS_CCO を書き換えるので、必然的に t_Co が書き換わってしまうのか。

**Comment by k-takata** [comment]
vim_strsave() は不要なのでは？ set_string_option_direct() 自身が vim_strsave() を呼んでいるので。

**Comment by k-takata** [comment]
`set t_Co=256` を実行すると、色がおかしなことに ~~なったうえに、t_Co=16 に~~ なってしまうようです。

**Comment by k-takata** [comment]
勘違い。set_termname() で T_CCO が書き換わるから vim_strsave() を呼んでいるのかな？
色がおかしなことになるのは変わりませんが。(vim --clean で起動して、`set t_Co=256` を実行すると、背景色が緑色になる。Ctrl-L を押せば直る。)

**Comment by ghost** [comment]
先日のこちらのパッチを含めてもやっぱり色はいけないことになりますか？
https://github.com/vim-jp/issues/issues/1240#issuecomment-469552245

いまのところ当方で再現できておりませんで、何が違うんだろう？--clean してるしな、と思っているところではあります。うーん…

**Comment by ghost** [comment]
あっ(;´Д`) free してない…

**Comment by k-takata** [comment]
色がおかしくなるのは、[私のパッチ](https://github.com/vim-jp/issues/issues/1240#issuecomment-469552245)と競合しているみたいです。ただ、私のパッチを外しても一瞬背景が緑色になるのが見えましたが。

**Comment by k-takata** [comment]
少なくとも、元々の desert で t_Co=256, notgc の時に背景が灰色になる問題は私のパッチで直るので、tgc のオン・オフで t_Co が変更される問題は、必ずしも直す必要はないかなという気がしてきました…。

**Comment by ghost** [comment]
当然変更は小さい方がいいので、t_Co はこの際スルーヽ(´ー｀)ノでオールオッケー了解です。
自分のコードが微妙だという部分の再確認としていい機会になりました。一部直したいところもありますが今後の課題として持っておきます。

しかし緑はまずいな…

**Comment by k-takata** [comment]
出しました。https://github.com/vim/vim/pull/4078

**Comment by k-takata** [comment]
ところで、swap_tcap() をもうちょっと単純化できるのではないかと思って、こんなパッチを書いてみたのですが、どうでしょうか。文字列をコピーせず、ポインタを切り替えるだけだと何か問題ありますか？
https://bitbucket.org/k_takata/vim-ktakata-mq/src/530e6df8f244f4b98aa3774ef9e1c2233d73709f/simplify-swap_tcap.patch?at=default&fileviewer=file-view-default

**Comment by ghost** [comment]
それぞれのモード上で t_* へのユーザ設定値を保持したかったのでした。今見るに、もう少し書きようがあった気はしています。ベタすぎる…

**Comment by ghost** [comment]
今むァーッとなっています(;´Д`)何やってたんだろう、コピー先を用意した気になっていただけだった…

**Comment by k-takata** [comment]
8.1.0997: https://github.com/vim/vim/commit/d5a5886ce90a30efc830b0053472735c5bbb4b0f
とりあえず元の問題は直ったので閉じます。

**Comment by k-takata** [comment]
swap_tcap() の簡略化はどうするかな？

**Comment by ghost** [comment]
うちで引き取っていいですか？(;´Д`)なんか別のパッチ(VTP高速化とか)と一緒にしたいかも…

**Comment by k-takata** [comment]
どうぞ、差し上げます。

**Comment by ghost** [comment]
すみません、どうも本気で恥ずかしくて(;´Д`)ありがとうございます。
