### ISSUE TITLE
printencoding=euc-jp/sjis と printmbcharset=MSWINDOWS の組み合わせにおけるヘルプの 記載について

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1243]
## 質問・報告の内容
```
:help pmbcs-option
```
に(下記引用部分は読みやすいようにタブ文字の整形済み)
> 上記の文字セットと 'printencoding' は、決められた組合せのみ利用可能です。可能
な組合せは以下のとおり:
<略>
　　　　　　　　　　 euc-jp sjis ucs-2 utf-8
Japanese　JIS_C_1978　x　x
　　　　　JIS_X_1983　x　x
　　　　　JIS_X_1990　x　　　　x　　x
　　　　　MSWINDOWS x
　　　　　KANJITALK6　x
　　　　　KANJITALK7　x

と記載が有るのですが、
```
$ vim -u NONE +"set printencoding=euc-jp printmbcharset=MSWINDOWS printmbfont=r:Japanese-Mincho-Regular | hardcopy | q!" sample.txt
```
を実行 (ファイルは何でも構いません) すると
> E673: 互換性の無いマルチバイトエンコーディングと文字セットです

とエラーになります

一方、euc-jp→sjis に書き換えた次の要領のコマンドはエラーになりません
```
$ vim -u NONE +"set printencoding=sjis printmbcharset=MSWINDOWS printmbfont=r:Japanese-Mincho-Regular | hardcopy | q!" sample.txt
```

ヘルプの printencoding の euc-jp, sjis における printmbcharset=MSWINDOWS についての記載は逆ではないでしょうか

## Vimのバージョン
> $ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)
適用済パッチ: 1-1766
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
<略>
+balloon_eval      +folding           +multi_byte        +terminfo
<略>
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.10
> Release:	18.10
> Codename:	cosmic

## 使用している or 関係していそうなプラグイン
なし

**Comment by iranoan** [comment]
ヘルプの記載は「xは指定できない」という意味でしょうか?
JIS_X_1983はeuc-jpでもエラーに成らないので、そんなことはないですよね

他にも試してみると、euc-jp でも KANJITALK6, KANJITALK7 がエラーになりますね???
これは OS が Mac じゃないからかな?

**Comment by ichizok** [comment]
実装 (hardcopy.c#L1072-L1093) を見ると、正しくは以下のようになると思われます。

```
                                euc-jp   sjis   ucs-2   utf-8 ~
  Japanese      JIS_C_1978         x       x
                JIS_X_1983         x       x
                JIS_X_1990         x              x       x
                MSWINDOWS                  x
                KANJITALK6                 x
                KANJITALK7                 x
```

**Comment by iranoan** [comment]
> 実装 (hardcopy.c#L1072-L1093) を見ると、正しくは以下のようになると思われます。
>
> ```
>                                 euc-jp   sjis   ucs-2   utf-8 ~
>   Japanese      JIS_C_1978         x       x
>                 JIS_X_1983         x       x
>                 JIS_X_1990         x              x       x
>                 MSWINDOWS                  x
>                 KANJITALK6                 x
>                 KANJITALK7                 x
> ```
```
:help pmbcs-option@en
```
も同じなので、漢字Talk 含めてヘルプの間違いのようですね

ソースで確認して頂きありがとうございました

**Comment by h-east** [comment]
patch 8.1.1194の後のruntmeファイル更新commitで修正されました。
https://github.com/vim/vim/commit/911ead126903aeb9564bad89e46a147ed4959896#diff-482f15514db144c09ee7292c664aa11b

vimdoc-jaも修正済みです。
https://github.com/vim-jp/vimdoc-ja-working/commit/bb783ce0524088cac653cf307f795c6f26d53e1c
