### ISSUE TITLE
Windows版gVimで :shell に色が付かない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1249]
## 質問・報告の内容

（もともとは @mattn さんの指摘 https://github.com/vim-jp/issues/issues/746#issuecomment-468539638 ですが。）
Windows版gVimで、`:set go+=!` を実行し、`:shell` が端末モードで動作するように設定する。
`:shell` を実行し、その中で、色が付くコマンドを実行する。（例: https://gist.github.com/k-takata/2d4f562bacf8bae6691973a540970117 のバッチファイルのどれか。）
色が付くのが期待だが、色が付かない。

`:shell` ではなく `:term` 内で実行した場合には色が付く。
Linux版gVimでは `:shell` でも色が付く。

## Vimのバージョン

8.1.1004

## OSの種類/ディストリ/バージョン

Windows 10 1709等

## 使用している or 関係していそうなプラグイン

なし

## その他

なし

**Comment by ghost** [comment]
gVim には termguicolors がないのでそこからです。当然ただフラグを変えるだけでは効果なし…。
色変更であるところの ^[[38;2; 系統と ^[[38;5; 系統の解釈もないので、そこも、まあある程度作りましたが、効果を出すまでに至ってないです。
直接 ^[[41m などとすれば一応文字色は変わりますが、不具合のある変わり方です。

**Comment by ghost** [comment]
:sh での文字列描画に利用している ```ExtTextOutW()``` は16色限定でした。どうしてやろうか…

**Comment by k-takata** [comment]
`:term` と `:sh` で何か違う描画方法をしていましたか？ `:set go+=!` する限り、どちらも端末モードで動作するはずですが。

**Comment by k-takata** [comment]
`:term` も `:sh` もどちらも terminal.c の cell2attr() が呼ばれて各セルに属性が設定されているらしいことは確認できました。

**Comment by mattn** [comment]
僕も以前追ったんですが、たぶん screen.c とかその先でモードを見てるんじゃないかなーと思ってます。

**Comment by k-takata** [comment]
`:sh` が入力されたときの処理も追ってみたのですが、`mch_call_shell()` の中で 'go' に '!' フラグが立っているのを見つけると、`mch_call_shell_terminal()` が呼ばれて、`term_start()` が `TERM_START_SYSTEM` フラグ付きで呼び出されるという処理は、WindowsもLinuxもほとんど同じでした。

**Comment by ghost** [comment]
:sh が最終的にたどり着くのは gui_w32.c の ```gui_mch_draw_string()``` のようです。ここへ来ないようにルート振りを変えてやれば結果が出るのかな？と思っていたりはします。

**Comment by k-takata** [comment]
`:term` でもそれは同じ気がしますが。(ついでに、DirectWriteを使うときも通るのはその関数。)

**Comment by ghost** [comment]
```gui_mch_draw_string()``` は最終的にエスケープシーケンスを解決する関数ではないので、その呼び出し前に色設定は終わっているわけだから、と…自分はそのへんまだ読みが足りないですね、ちょっといじるだけでいいと思うんだけれど、たどり着いていません。

**Comment by k-takata** [comment]
`:sh` を使った場合でも、libvterm 経由でエスケープシーケンスは解決されているはずです。
そして上に書いたように `cell2attr()` が呼ばれて、`term_line2screenline()` で `ScreenAttrs[]` に属性が設定されています。が、なぜか色が出ない。

**Comment by mattn** [comment]
ひとまず意識統一として。

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 8d05a188e..83f250cad 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -2552,6 +2552,7 @@ cell2attr(VTermScreenCellAttrs cellattrs, VTermColor cellfg, VTermColor cellbg)
     {
 	guicolor_T fg, bg;
 
+	cellfg.red = 255;
 	fg = gui_mch_get_rgb_color(cellfg.red, cellfg.green, cellfg.blue);
 	bg = gui_mch_get_rgb_color(cellbg.red, cellbg.green, cellbg.blue);
 	return get_gui_attr_idx(attr, fg, bg);
```

こうすると `:terminal` の文字は赤くなるけど `:shell` は白のままなので、色は付けようとしてるけど、どこかしらで抜いている、というのが正しそう。つまり ScreenAttrs をどこかで捨てている。

**Comment by mattn** [comment]
いろいろ試してると、どうも色付けてるけどその上から白で塗りつぶしてる気がしてきた。

**Comment by mattn** [comment]
`:shell` して `cls` して色が付く事した場合

![image](https://user-images.githubusercontent.com/10111/54252577-bec89600-458e-11e9-9f0a-ee53078fc003.png)

そして最下行で実行した場合

![image](https://user-images.githubusercontent.com/10111/54252594-ce47df00-458e-11e9-9488-9a45d5980405.png)

**Comment by ghost** [comment]
色がついたのでヽ(´ー｀)ノたのしい一日でした。

````diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 7682931d8..caf0b1501 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -1561,6 +1561,10 @@ do_shell(
      */
     if (cmd != NULL)
 	winstart = (STRNICMP(cmd, "start ", 6) == 0);
+# ifdef FEAT_GUI_MSWIN
+    else
+	winstart = 1;
+# endif
 #endif
 
     /*
````

**Comment by mattn** [comment]
おーすばらしい

**Comment by ghost** [comment]
set termwintype=conpty でさらに色が出ます。
ここまでやって ambiguous character の gVim 対応ができてないことに気づく…

**Comment by k-takata** [comment]
`:!color16.bat` だと相変わらず色が出ませんね。

Windows GUIだと、stoptermcap()/starttermcap() を実行すると色が消えてしまうということですか？

**Comment by k-takata** [comment]
こうすれば色が出た。

```diff
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -1560,7 +1560,15 @@ do_shell(
      * Check if ":!start" is used.
      */
     if (cmd != NULL)
-	winstart = (STRNICMP(cmd, "start ", 6) == 0);
+	winstart = (STRNICMP(cmd, "start ", 6) == 0)
+# if defined(FEAT_GUI) && defined(FEAT_TERMINAL)
+	    || vim_strchr(p_go, GO_TERMINAL) != NULL
+# endif
+	    ;
+# ifdef FEAT_GUI_MSWIN
+    else
+	winstart = 1;
+# endif
 #endif
 
     /*
```

ただ、`winstart` 変数を流用しているのは意味的に微妙な気がします。

**Comment by mattn** [comment]
>ただ、winstart 変数を流用しているのは意味的に微妙な気がします。

そうすね。もう1個変数を足すか別の箇所で ifdef して GUI なら通すようにした方が読み手には伝わりそう。

**Comment by ghost** [comment]
一部拝借しつつ名前を変えた程度という微妙な仕上がりです(;´Д`)。新変数は書いてるうちにわからなくなってきたのでパス。
https://gist.github.com/ntak/764c3f06ed93849a64d8234fc7dcac8e

**Comment by ichizok** [comment]
`MSWIN` がdefineされている時しか `keep_termcap` を見ないので
https://gist.github.com/ntak/764c3f06ed93849a64d8234fc7dcac8e#file-gvimcolor-diff-L11
ここは `#ifdef MSWIN` のままでいいと思います。

なので
https://gist.github.com/ntak/764c3f06ed93849a64d8234fc7dcac8e#file-gvimcolor-diff-L29
ここも `#ifdef MSWIN` の中でよくて、if で `gui.in_use` をチェックする必要があるかと。

**Comment by ghost** [comment]
ご指摘ありがとうございますヽ(´ー｀)ノヒデキ完璧！
https://gist.github.com/ntak/90cfe79eae4500fec1b58e5c398c9b3b

**Comment by k-takata** [comment]
この行は `:!start` 以外の時は実行すべきだと思うのです。
https://gist.github.com/ntak/90cfe79eae4500fec1b58e5c398c9b3b#file-gvimcolor_2-diff-L41

**Comment by k-takata** [comment]
Linuxでは stoptermcap()/starttermcap() を実行しているはずなのに色が出るのはなぜだろう？

**Comment by ghost** [comment]
そうですね、改行を入れた方がしっくりくる感じがあります。
https://gist.github.com/ntak/d483fe1a49cf616222eea963006eac76

termcap の件については、そもそもこの位置に手を入れようと考えた理由が、「続けるにはENTERを押すか…」が出力された瞬間に白黒だった画面全体に色がつくという状況が発生したので、再描画してるな？的な発想が出たからでした。screen.c の USE_REDRAW を screen_del_lines に強制的に設定したときにそうなったと思います。
Linux の方は追ってないので正直わからないです。

**Comment by k-takata** [comment]
8.1.1016: https://github.com/vim/vim/commit/049ca59236d5a981f23cf5dfe40f54536fe7cad2
Patch authorは ntak さんが 1st author だと思うので、version8.txt に記載されたときにでも指摘します。

**Comment by k-takata** [comment]
Link: https://github.com/vim/vim/pull/4117
