### ISSUE TITLE
vim-cmdsrv-noxをpushしないか?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#125]
@ynkdir さんによる http://code.google.com/r/yukihironakadaira-vim-cmdsrv-nox/
Xが無くてもcmdsrv機能が動くようになるというもの。

セキュリティ的な対応もバッチリっぽいのにもかかわらずvim-devでの反応がない? Bram氏のTODOに入ってんのかな?

このissueは取り込まれるように働きかけるためのissueとしましょう。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/dm8nvb5b3do/-SzW7dq4EBIJ

> Thanks.  This is a big change.  I won't have time for this soon.  I hope some others will try it out.

**Comment by koron** [comment]
>  I hope some others will try it out.

サクラをするチャンス! ってか +kaoriya に取り込んで、大量の人柱を立てるか?w

**Comment by Shougo** [comment]
その手はありますね。

**Comment by ynkdir** [comment]
TODOというほどのものでもないんですが気になってることをいちおう書いておきます。
- ソケットへのアクセスはディレクトリの権限で制限してるので getpeer\* はいらない気がするけどなんとなく残している。
- Windowsのnamed pipeのアクセス制限はどうなってるのか。Windowsはマルチユーザーない？
- ソケットファイルの名前をurlエンコードっぽくしてるけど&encをそのまま使ってるのでutf-8にしたほうがいいのか。
- /tmp とかハードコーディングしてる。
- ソケット通信でEOFをデータの終了としてるけど、データサイズを送受信したほうがよさそうな。
- メッセージ書式。今は "Key1<NUL>Value1<NUL>Key2<NUL>Value2<NUL><NUL>" という感じ。パースを楽するため。
- 異常終了するとソケットファイルが残る。/tmp に作ってるけど削除されるかどうかはシステムしだい。
- ドキュメント。
- ぶっちゃけ自分では使ってないので不具合たくさんありそう。日常的に client/server を活用することがない。

**Comment by Shougo** [comment]
> 異常終了するとソケットファイルが残る。/tmp に作ってるけど削除されるかどうかはシステムしだい。

Vimの一時ファイル自体クラッシュすると残ってしまうから、これは仕方ないでしょう。

ハードコードな部分はこれから修正しないとだめでしょうね。
/tmpについては、Vimが使っているテンポラリなディレクトリではだめなんですか？

**Comment by ynkdir** [comment]
各Vimインスタンスが同じパスを参照できればいいのでどこでもいいんですが
Vimが自動で作る一時ディレクトリはインスタンス毎なのでだめだと思います。

で、思い出したんですがサーバー一覧をソケットファイルの一覧からとってるので --serverlist で死んだサーバーがでたりします。まあしょうがないですが。

**Comment by mattn** [comment]
そのソケットファイルのファイル名にプロセスIDが埋まっているなら生死確認は出来るかも。

**Comment by mattn** [comment]
@ynkdir  久々最新取ってwin32で試したんですが、結構遅いすね。調整すれば速くなります？

**Comment by ynkdir** [comment]
むぅそうですか。
なんでしょうねぇ。
調整できそうなポイントはなかったと思います。

**Comment by ynkdir** [comment]
あーあと気になるといえば複数のサーバー間で互いに呼び出し合うような場合に問題ないかどうかきっちり検証できてないです。問題ないとは思いますが。

**Comment by ynkdir** [comment]
あと同時接続数の問題もありました。
 "# define CMDSRV_INSTANCES 5" なんですが。
リクエストを受けて結果を返すまでを一つの接続でやってるので
ちょっとアクセスが立て込んだり互いに呼び出しあったりするだけで制限に到達してしまいます。
受信と送信の接続を分ける (現実装と同じ) といいと思うんですがなんか複雑になりそうなのでとりあえず今の形になってます。

**Comment by ynkdir** [comment]
> そのソケットファイルのファイル名にプロセスIDが埋まっているなら生死確認は出来るかも。

そうするとサーバーIDとパスが一意に定まらないのでタイミングによって同じIDのサーバーができてしまって
それを防ぐにはロックしたりなんなりしないといけなくて面倒くさいと思った記憶があります。

死活チェックのために接続してみてエラーをみるというのもやってみたんですが
IOでウェイトがかかったり同時接続数の制限にかかったり(開放に時間がかかる?)でうまくいきませんでした。

どうしても死活チェックが必要ならそれしかないですかねぇ。

**Comment by mattn** [comment]
#367

**Comment by Shougo** [comment]
これも一年放置されてしまっているので、Vim 7.4が出るときにpushできないですかね？

**Comment by Shougo** [comment]
ようやくVim 7.4の話が出てきているので、パッチの完成度を上げて推すのは今がチャンスだと思いますが……

**Comment by thinca** [comment]
すでに mattn さんが言及してますね。
https://groups.google.com/d/msg/vim_dev/ZWWgK9aXQ2Y/R2-HfFTLs2YJ

**Comment by koron** [comment]
とりあえずpushはしたので、一旦閉じます。
7.4に取り込まれなかったら、あたらしいissue作って再チャレンジ、かな。

**Comment by Shougo** [comment]
そうですね。他のパッチも多いですし……。
