### ISSUE TITLE
インサートモードを Ctrl-C で抜けると "-- INSERT --" 表示が残り続ける場合がある

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#1258]
### 再現手順

`'statusline'` でユーザ定義関数の呼び出しがある場合に問題が発生します。

test.vim
```vim
func StatusLine()
  return ''
endfunc
set statusline=%!StatusLine()
set laststatus=2
```

```
$ vim -Nu test.vim
```

インサートモードから Ctrl-C でノーマルモードに戻ると、ステータスラインの `-- INSERT --` 表示が残り続けます。

## Vimのバージョン

8.1.0822 ~

## その他

```diff
--- a/src/edit.c
+++ b/src/edit.c
@@ -4564,7 +4564,7 @@ ins_esc(
      */
     if (reg_recording != 0 || restart_edit != NUL)
        showmode();
-    else if (p_smd && !skip_showmode())
+    else if (p_smd)
        msg("");

     return TRUE;           /* exit Insert mode */
```

これで直りますが、8.1.0822 の目的からすると (よくわかってませんが) この変更ではダメですかね？

**Comment by k-takata** [comment]
それを消してしまうと https://github.com/vim/vim/issues/2715 が再発しますね。

**Comment by k-takata** [comment]
元々私が[提案](https://github.com/vim/vim/issues/2715#issuecomment-456646223)していた `!global_busy` に書き換えれば良さそうな気がしますが、Bramがもっと最適化できるはずと主張して今の形になったんですよね。#1238 もそうですけど、`global_busy` だけに対処しておけば余計な影響が出なくてすんだのではという気がします。

**Comment by mattn** [comment]
ワークアラウンドですが got_int とかでは見れないんですかね。

**Comment by ichizok** [comment]
> ワークアラウンドですが got_int とかでは見れないんですかね。

よさそうです。

```diff
--- a/src/edit.c
+++ b/src/edit.c
@@ -4564,7 +4564,7 @@ ins_esc(
      */
     if (reg_recording != 0 || restart_edit != NUL)
        showmode();
-    else if (p_smd && !skip_showmode())
+    else if (p_smd && (got_int || !skip_showmode()))
        msg("");

     return TRUE;           /* exit Insert mode */
```

**Comment by k-takata** [comment]
Related: https://github.com/vim/vim/issues/4269

**Comment by ichizok** [comment]
PRed.
https://github.com/vim/vim/pull/4270

**Comment by ichizok** [comment]
8.1.1189
https://github.com/vim/vim/commit/abc7c7fc5a098374f5543a237e6c9dd918848b34

https://github.com/vim/vim/issues/4269 も 8.1.1192 で修正された。
https://github.com/vim/vim/commit/4c25bd785aa8b565bf973cbba12ed36b76daaa4f
