### ISSUE TITLE
join()が遅い

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#126]
らしい。

https://groups.google.com/d/msg/vim_dev/WCwNEgJXlb4/Wh3D59HDfuMJ

ここからのくだり。

``` c
/*
 * "join()" function
 */
    static void
f_join(argvars, rettv)
    typval_T    *argvars;
    typval_T    *rettv;
{
    garray_T    ga;
    char_u  *sep;

    if (argvars[0].v_type != VAR_LIST)
    {
    EMSG(_(e_listreq));
    return;
    }
    if (argvars[0].vval.v_list == NULL)
    return;
    if (argvars[1].v_type == VAR_UNKNOWN)
    sep = (char_u *)" ";
    else
    sep = get_tv_string_chk(&argvars[1]);

    rettv->v_type = VAR_STRING;

    if (sep != NULL)
    {
    ga_init2(&ga, (int)sizeof(char), 80);
    list_join(&ga, argvars[0].vval.v_list, sep, TRUE, 0);
    ga_append(&ga, NUL);
    rettv->vval.v_string = (char_u *)ga.ga_data;
    }
    else
    rettv->vval.v_string = NULL;
}
```

リストのサイズが予め分かってるのに、なぜに80 www

**Comment by mattn** [comment]
あー文字列か...しっけい

**Comment by koron** [comment]
list_join()の中を見るとわかるけど、結局一行一行を文字列化するから、どのくらいずつ伸ばすのが良いかはわからないらしい。あ～でもgrowのタイミングが多ければそれだけ多くmemcpyが走ることに変わりはないか。

**Comment by mattn** [comment]
でもそれ、80はまずいよ

**Comment by mattn** [comment]
``` diff
diff -r 0dabc2ce136c src/eval.c
--- a/src/eval.c    Tue Jan 10 22:31:32 2012 +0100
+++ b/src/eval.c    Thu Jan 12 16:35:10 2012 +0900
@@ -13183,8 +13183,10 @@

     if (sep != NULL)
     {
-   ga_init2(&ga, (int)sizeof(char), 80);
-   list_join(&ga, argvars[0].vval.v_list, sep, TRUE, 0);
+   list_T *l = argvars[0].vval.v_list;
+   int size = l->lv_len;
+   ga_init2(&ga, (int)sizeof(char), size > 80 ? size : 80);
+   list_join(&ga, l, sep, TRUE, 0);
    ga_append(&ga, NUL);
    rettv->vval.v_string = (char_u *)ga.ga_data;
     }
```

これいれただけで

オリジナル:  0.035153
パッチ済み:  0.003007

とかどういうことよ。

**Comment by koron** [comment]
そのサイズの決定もなんかムチャクチャに見えるけど、そんなんはやくなるんだ?w

**Comment by mattn** [comment]
むちゃくちゃというか、リストのサイズに比例していないのがまずいはず。

**Comment by mattn** [comment]
これ、ga_xxx なんか使わない方が速くなるはず。

**Comment by koron** [comment]
リストを先に舐めちゃえば、だいたいのサイズはわかるよね。

**Comment by koron** [comment]
再確保とmemmoveがなくなるだけで、全然変わってくるとは思う。

**Comment by mattn** [comment]
よーしパパ、このissueをkoronさんに投げちゃうぞ！

**Comment by koron** [comment]
まじでかw

**Comment by koron** [comment]
とりあえず作った: https://gist.github.com/1599706

コンパイル通しただけで試験はしてない。

戦略: 最初のループで文字列化したsとtofreeだけを **別のgarray_T** にストックしていき、同時に連結後に必要なサイズを計算してしまう。必要なバッファはサイズ指定で一気に作り、次のループでそこに文字列を構築する。関数を分けたのはreturn FAILのケースで **別のgarray_T** のメモリ解放をキッチリやるため。

特徴: 速度は速くなると思われるが一時的とはいえメモリの利用量が理論上は倍以上になる。またループが増えた分のオーバーヘッドが考えられる。

**Comment by koron** [comment]
どやってテストするのが良いの?

**Comment by mattn** [comment]
とりあえず https://gist.github.com/1599910 で

```
:so join.vim
```

した際の join.log を...

**Comment by koron** [comment]
ちょwww +kaoriya 7.3.401でso join.vimしたら…なにも言わずに落ちたwww

**Comment by koron** [comment]
ああjoin.log吐いて、終了するのか。あせったあせったwww

**Comment by mattn** [comment]
罠です

**Comment by koron** [comment]
バグってた。

```
:echo join(range(10))
9 9 9 9 9 9 9 9 9 9
```

だっておwww

数字のバッファ使いまわしてんのかよ orz

**Comment by koron** [comment]
ただ速度の上げ幅は激烈かも。約100倍?

```
パッチ前:
0.048741
0.049043
0.048773

パッチ後:
0.000655
0.000528
0.000539
```

**Comment by mattn** [comment]
バグってkoronバージョン！？

**Comment by mattn** [comment]
あ、すんません。別のissueと混乱してた。

**Comment by koron** [comment]
Yes. 数字の文字列化はnumbuf使い回してて、帰ってくるsが書き換わってるのw

**Comment by mattn** [comment]
その修正が終ったら僕もためそかな。

**Comment by koron** [comment]
とりあえず何でも vim_strsave() するようにしたら

```
0.001496
0.001678
0.001458
```

さっきより遅くなったけど、元から比べると30倍ってところ。

**Comment by koron** [comment]
とりあえずもう少し刈り込んでみる。

**Comment by koron** [comment]
Rev.2 一応、30倍というところ。

**Comment by koron** [comment]
ちょっと全然違うバリエーションも作ってみるわ。今度はメモリ使わないタイプ。

**Comment by koron** [comment]
https://gist.github.com/1600472 やってみたけどダメだった。全然早くなってなかった。

速度的には r2 だけど、書き換えの量と速度のバランス的には @mattn のやつのほうが良いんじゃないかな。

**Comment by mattn** [comment]
検証あざす！

**Comment by mattn** [comment]
まぁこの閾値をどうするかって問題は残ってますが...

**Comment by koron** [comment]
ああ、そうそう。その閾値だけど、list_joinを使っている場所が3箇所くらいあるから、全部なおさないとアカンかも。もしくは私がやったみたいにlist_join()自体で治しちゃうか。

**Comment by koron** [comment]
せっかくだから、もう一手間だけかけてみるわ。

**Comment by koron** [comment]
Rev.4: https://gist.github.com/1600566

オリジナルよりも平均して90倍くらい速い。Rev.2と比べても3倍。このくらいならだしてもこちらのが良いんじゃなかろうか?

```
0.000525
0.000569
0.000537
```

**Comment by ynkdir** [comment]
total_strlen はリストが空だとマイナスになります。動作的には問題ないのであえてスルーしてるならいいんですが念のため。

**Comment by koron** [comment]
@ynkdir Thanks! たしかに…治すかどうか微妙に迷うところですねぇw 効率的には今のままのほうがカッコヨイんですが…このまま行くにしてもせめてコメントくらいは足すべきか。

**Comment by koron** [comment]
https://gist.github.com/1600566

気持ち悪いので、セパレータの長さを加算するところにそれが必要になる条件(ga_len >= 2)を追加した。

**Comment by h-east** [comment]
todoリスト入り。

> Also an idea to make join() faster. (Yasuhiro Matsumoto, 2012 Jan 11)
> Another one from Taro Muraoka, 2012 Jan 12.

**Comment by koron** [comment]
https://groups.google.com/d/topic/vim_dev/Kgof8b5YnkI/discussion

included.
