### ISSUE TITLE
折り返しされているテキストで折り返し後のテキストのヤンク結果がずれている

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/issues#1273]
## 不具合の内容

折り返しされているテキストで折り返し後のテキストのヤンク結果がずれている
ただ、適切に再現できていないので、報告に止まりますが...

### 現象・ログ

再現に記載

### 再現手順

起動

```
gvim --clean -c "set wrap showbreak=+\  breakindent breakindentopt=min:50,shift:4,sbr foldcolumn=3 number relativenumber signcolumn=yes"
```

ただし、関係しそうなオプションは上記に含めたが、cleanでやると発生せず。
現状再現は自分の環境下のみです。

折り返しが発生するようにテキスト準備
例
```
[![Powered by vital.vim](https://img.shields.io/badge/powered%20by-vital.vim-80273f.svg)](https://github.com/vim-jp/vital.vim)
```

`...vim- *here* 80273...`
上記で折り返しがされていること

折り返しされているテキストで次の操作

1. 最後の括弧のところまでカーソル移動 `svg)[ *here* (http`
2. Ctrl-vでビジュアル矩形選択開始
3. <del>Ctrl-e</del>Eで文末まで選択
4. yでヤンク

ヤンク結果が以下になる
```
)](https://github.com/vim-jp/vital.vi
```

なんとなく showbreak分ズレている?

### 期待動作

視覚的に選択した結果と同じ領域をヤンクする
選択しているのは `(https://github.com/vim-jp/vital.vim)`

## Vimのバージョン

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  2 2019 20:46:56)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-1455

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit 1809

## 使用している or 関係していそうなプラグイン

不明...

**Comment by tsuyoshicho** [comment]
追記
自分の環境下でもft=noneだと~~出ず~~でも出ました、ft=markdownやtextで出たので、シンタックスやインデントのプラグインの影響の可能性は~~ありそうです~~あんまりなさそうです。
ただ、だとしても(concealが増えるならともかく)見た目でのヤンクとズレていることにかわりはありませんが...

また、showbreakをクリアしても同じだったので、そちらは関係ないようです。

**Comment by tsuyoshicho** [comment]
撮影しました。
![2019-06-06-vim1](https://user-images.githubusercontent.com/96727/59009388-583ed580-8868-11e9-8f89-8d7c02a1dab8.gif)

**Comment by tsuyoshicho** [comment]
以下も試してみましたが、発生しませんでした...他が関係してそうですね

```
gvim -u NONE -N  "set nocompatible wrap showbreak=+\  breakindent breakindentopt=min:50,shift:4,sbr foldcolumn=3 number relativenumber signcolumn=yes"
gvim -u NONE -U NONE -N --noplugin  "set nocompatible wrap showbreak=+\  breakindent breakindentopt=min:50,shift:4,sbr foldcolumn=3 number relativenumber signcolumn=yes"
gvim --clean -c "set nocompatible wrap showbreak=+\  breakindent breakindentopt=min:50,shift:4,sbr foldcolumn=3 number relativenumber signcolumn=yes"
```

**Comment by mattn** [comment]
何かプラグインが影響してないでしょうか？
手元で --clean でやってみましたが再現しませんでした。キャプチャは statusline が変わっている様ですし <kbd>CTRL</kbd>-<kbd>e</kbd> というキーが効いている様ですね。

**Comment by mattn** [comment]
あー、失礼。 clean だと再現しないという話ですね。

**Comment by tsuyoshicho** [comment]
はい、自前の環境由来だとは思います...が、ビジュアル選択した状態とヤンクできたものに差ができるのも色々考えにくいことと、それがマズいよなあ...とは思うんですが、追い詰められなくてorz

**Comment by mattn** [comment]
https://github.com/vim-jp/issues/issues/1286 で直る模様。あちらで送った PR がマージされたらこちらも close 予定

**Comment by tsuyoshicho** [comment]
手元でまだ発生していたので、どうにか条件の追い詰めをしていたところ

以下の手順で、現状でも再現させることに成功しました。

## 1.コマンド
オプションはだいぶ追い詰めましたが、まだ不要なものがまじってる気はします

```
gvim --clean -c "set scr=3 bri briopt=min:50,shift:4,sbr sbr=+\  co=86 lines=18 window=17 nu rnu mod fdc=3 hi=50 scl=yes lbr dy=lastline ch=2 lz"
```

画面サイズは以下のはず
```
set co=86 lines=18 window=17
```

この時点で、テストテキストを張り付けし、試行すると正常にyankできる

## 2.リサイズ
以下をコマンドとして入力しリサイズ
```
set co=90 lines=18 window=17
```

再度テキストのyankを行なうとズレが発生する

## 再現バージョンなど

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 24 2019 19:12:24)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-1744
```

一応、上記の再現時のoptionのダンプも付けます
[dump.txt](https://github.com/vim-jp/issues/files/4075708/dump.txt)

**Comment by tsuyoshicho** [comment]
どうも `set co` でのサイズ変更について、英語での折り返しの判定が動き、幅を広げても折り返し条件的に変化がないので計算がずれてる気がします。

また、オプションの追い詰めで、  `set lbr` は必要っぽいので...

**Comment by tsuyoshicho** [comment]
OK
[![Image from Gyazo](https://i.gyazo.com/f959f1802db9044884ee5bba0fd7489a.png)](https://gyazo.com/f959f1802db9044884ee5bba0fd7489a)

NG
[![Image from Gyazo](https://i.gyazo.com/2b8e90e7e7cc13dbaa52d7beab70d191.png)](https://gyazo.com/2b8e90e7e7cc13dbaa52d7beab70d191)

**Comment by tsuyoshicho** [comment]
[![Image from Gyazo](https://i.gyazo.com/45102ffb95aa0604723a7de581ac482b.gif)](https://gyazo.com/45102ffb95aa0604723a7de581ac482b)

**Comment by mattn** [comment]
mksesion です。


[issue1273.zip](https://github.com/vim-jp/issues/files/3446006/issue1273.zip)

**Comment by k-takata** [comment]
`gvim --clean -c "set lbr"` だけで再現しました。ポイントは、ウィンドウ幅と折り返し位置がずれていること、`C-v` でビジュアルモードを開始すること。
`v` でビジュアルモードを開始した場合は再現しませんでした。

**Comment by mattn** [comment]
@k-takata これ duplicated なんでしたっけ

**Comment by k-takata** [comment]
結局違っていたと判断したので duplicated ラベルは外しました。

**Comment by mattn** [comment]
あ、すみません。ラベルを付けたのだと見間違えました。

**Comment by mattn** [comment]
Closed by https://github.com/vim-jp/issues/issues/1286

**Comment by k-takata** [comment]
直っていないようなのでreopenします。

**Comment by tsuyoshicho** [comment]
なんか最近遭遇した気がしたのは気のせいじゃなかったんですね...

**Comment by k-takata** [comment]
`set lbr` した状態で `C-v` で範囲選択した後、`C-a` / `C-x` でインクリメント・デクリメントしたり、`rX` で置換するのも位置がずれている気がします。

```diff
--- a/src/ops.c
+++ b/src/ops.c
@@ -2744,7 +2744,12 @@ block_prep(
     char_u	*line;
     char_u	*prev_pstart;
     char_u	*prev_pend;
-
+#ifdef FEAT_LINEBREAK
+    int		lbr_saved = curwin->w_p_lbr;
+
+    // Avoid a problem with unwanted linebreaks in block mode.
+    curwin->w_p_lbr = FALSE;
+#endif
     bdp->startspaces = 0;
     bdp->endspaces = 0;
     bdp->textlen = 0;
@@ -2863,6 +2868,9 @@ block_prep(
     }
     bdp->textcol = (colnr_T) (pstart - line);
     bdp->textstart = pstart;
+#ifdef FEAT_LINEBREAK
+    curwin->w_p_lbr = lbr_saved;
+#endif
 }
 
 /*
```

こうすれば直るかなと思ったのですが、逆に `C-v` で範囲選択の後 `A` での挿入でずれてしまって、うまくいかないですね…

**Comment by tsuyoshicho** [comment]
この問題、根が深いですね...vimはカーソル表示とコンテンツの対応が取れてると思ってたので、以外です...

**Comment by k-takata** [comment]
パッチができたっぽい。
https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/b7e28ffae21755ab71f420ff489e15650e440619/fix-vimjp-1273.patch

**Comment by k-takata** [comment]
本当にこの修正でいいのかよく分かっていませんが、PR出しました。https://github.com/vim/vim/pull/5524

**Comment by k-takata** [comment]
8.2.0147: https://github.com/vim/vim/commit/03c3bd9fd094c1aede2e8fe3ad8fd25b9f033053

**Comment by tsuyoshicho** [comment]
(8.2.0147で確認、よさそう)
