### ISSUE TITLE
eval.txt に scriptversion 個別のタグがほしい

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1276]
## 内容

eval.txt に scriptversion 個別のタグがほしいです。

### Pros 良くなる点

* 現状バージョンが 3 までしかないのでそんなに行数はありませんが、いずれバージョンが増えて行数が増えた場合にあると便利だと思います。
* :help で示したい時など個別にタグがあると便利だと思います。
     * 例: `This plugin requires |scriptversion-3|`

### Cons 悪くなる点

???

## Vimのバージョン

8.1.1462

**Comment by tyru** [comment]
送りました https://github.com/vim/vim/pull/4512

**Comment by k-takata** [comment]
タグの位置が `>` ... `<` の内側なのはよくないと思います。

**Comment by tyru** [comment]
ありがとうございます！直しました 🙇

**Comment by k-takata** [comment]
Fixed: https://github.com/vim/vim/commit/3ff5f0f05d437a6b3eaf3caa5dc2762b49314617#diff-bea881dfa9626bab7141337b0fcdb23eR13087
