### ISSUE TITLE
gVim: 複数ファイルのドロップ後の展開でハイライトが適用されないことがある

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/issues#1278]
## 不具合の内容

複数ファイルをgVimでD&Dし、その後、バッファを一気にタブにしたとき、ファイルタイプは設定されているが、ハイライトが効いてないバッファ(タブ)がある

### 現象・ログ

概要に記載

### 再現手順

```
gvim --clean
```

で、起動し、vimヘルプなファイルを4個以上くらいドロップします。

その後

```
:bufdo tab split
```

としてタブに展開すると、ハイライトが適用されてないバッファが出ることがあります(4個あればまず確実)
 
### 期待動作

すべてのバッファはハイライトが正しく適用されている状態であること

## Vimのバージョン

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 14:02:25)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-1536
```

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (1809 10.0.17763.557)

## 使用している or 関係していそうなプラグイン

なし

## その他

なし

**Comment by mattn** [comment]
タブ化した時点でハイライトの作成をスキップしているらしくCTRL-L 等では再描画されない(そもそもハイライトが無い)。 `syntax on` や `filetype` の再設定で色が付く。 `need_highlight_changed` が怪しい。

**Comment by tsuyoshicho** [comment]
追記:

引数に複数指定で `-p` とした場合にも類似現象が発生することはあります。
さらにいうとファイルタイプも未検知 ( `filetype detect` すると解決する) こともあります...

**Comment by mattn** [comment]
bufdo や argdo で意図的に Syntax イベントを除けている様でした。

```diff
diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
index a275fb8b7..803a98229 100644
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -1427,9 +1427,6 @@ ex_listdo(exarg_T *eap)
     tabpage_T	*tp;
     buf_T	*buf = curbuf;
     int		next_fnum = 0;
-#if defined(FEAT_SYN_HL)
-    char_u	*save_ei = NULL;
-#endif
     char_u	*p_shm_save;
 #ifdef FEAT_QUICKFIX
     int		qf_size = 0;
@@ -1445,12 +1442,6 @@ ex_listdo(exarg_T *eap)
     }
 #endif
 
-#if defined(FEAT_SYN_HL)
-    if (eap->cmdidx != CMD_windo && eap->cmdidx != CMD_tabdo)
-	/* Don't do syntax HL autocommands.  Skipping the syntax file is a
-	 * great speed improvement. */
-	save_ei = au_event_disable(",Syntax");
-#endif
 #ifdef FEAT_CLIPBOARD
     start_global_changes();
 #endif
@@ -1638,14 +1629,6 @@ ex_listdo(exarg_T *eap)
 	listcmd_busy = FALSE;
     }
 
-#if defined(FEAT_SYN_HL)
-    if (save_ei != NULL)
-    {
-	au_event_restore(save_ei);
-	apply_autocmds(EVENT_SYNTAX, curbuf->b_p_syn,
-					       curbuf->b_fname, TRUE, curbuf);
-    }
-#endif
 #ifdef FEAT_CLIPBOARD
     end_global_changes();
 #endif
```

**Comment by tsuyoshicho** [comment]
あー、じゃあbufdoやargdoなど実施されないものについて

- できればヘルプに記載があると嬉しい
- 適用したければ、自力で解消すること(後からbufdo とかで syntax on や filetype する?)も記載
  - それを自力でやること

ですかね...

```
			Note: このコマンドの実行中、オプション 'eventignore'
			でオートコマンドのイベント Syntax を指定することでそれ
			を無効化できる。こうすると各ファイルの処理がかなり高速
			になる。
			|:windo|、|:tabdo|、|:bufdo|、|:cdo|、|:ldo|、|:cfdo|、
			|:lfdo|も参照。
```
みたいなのあるんだし、オプション制御できるといいように思いますが...

---

>  Don't do syntax HL autocommands.  Skipping the syntax file is a great speed improvement.

って、せめて遅延実施で、その処理を(スピード改善でスキップするVim側で)仕込むとかしてほしいですね...

**Comment by mattn** [comment]
たぶんこの挙動に気付いていないので、一旦投げて、eventignore するのがそもそもマズイって話なら↑のパッチ出します。

**Comment by tsuyoshicho** [comment]
はい、おねがいします。

**Comment by mattn** [comment]
https://github.com/vim/vim/issues/4761

**Comment by mattn** [comment]
[patch 8.1.1795](https://github.com/vim/vim/commit/c7f1e4002184903f4e12e429dd5c6ab731932f86)

僕のパッチではないですが。
