### ISSUE TITLE
scriptversion 2 で、評価されない辞書アクセスがエラーになる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#1279]
## 不具合の内容

`scriptversion 2` を実行したスクリプト内 (`.` による文字列連結の禁止)で、短絡評価で実際に評価されなかった部分に辞書アクセス `dict.foo` があるとエラーになってしまいます。

### 現象・ログ

再現手順を参照。

### 再現手順

sample.vim

```vim
scriptversion 2

let x = {'foo': 0}

if 0 && x.foo
  echo 'foo'
endif
```

```
$ vim -u NONE -i NONE -N -S sample.vim
```

```
/home/thinca/sample.vim の処理中にエラーが検出されました:
行    5:
E15: 無効な式です: 0 && x.foo
```

`0 &&` を `1 &&` にするとエラーは出ずに問題なく動作します。

### 期待動作

エラーが出ない。

## Vimのバージョン

8.1.1583

## OSの種類/ディストリ/バージョン

*   Gentoo Linux

## 使用している or 関係していそうなプラグイン

なし

## その他

スクリプトの未評価部分をスキップする際に文字列連結として扱ってしまっているのかなと思います。scriptversion が 2 以上の場合には `.` は常に辞書アクセスのはずなので、そのようにすれば直せる?

**Comment by kuuote** [comment]
その他の欄に書いてあるとおり、未評価部分のスキップ時に常に文字列連結として処理されるのが原因ですね。
とりあえず、文字列連結を弾いている部分を未評価時に走らないようにすると上手く動いているように見えますが、どうでしょうか。
```diff
diff --git a/src/eval.c b/src/eval.c
index 3cfa4b7a5..6eed46f96 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -4036,7 +4036,7 @@ eval5(char_u **arg, typval_T *rettv, int evaluate)
 	// "." is only string concatenation when scriptversion is 1
 	op = **arg;
 	concat = op == '.'
-			&& (*(*arg + 1) == '.' || current_sctx.sc_version < 2);
+			&& (*(*arg + 1) == '.' || current_sctx.sc_version < 2 || !evaluate);
 	if (op != '+' && op != '-' && !concat)
 	    break;
 ```

**Comment by thinca** [comment]
一旦問題提起でパッチを送ってみるといいかもですね。間違ってたら Bram さんが直してくれるでしょうし。

**Comment by thinca** [comment]
@kuuote パッチ送れますか?

**Comment by kuuote** [comment]
送ってみました、何か問題があれば指摘お願いします。
vim/vim#4704

**Comment by tyru** [comment]
入りました。 [8.1.1722](https://github.com/vim/vim/commit/61343f0c44c8e71df04918d033e0a744c0b7f8aa)
