### ISSUE TITLE
:try と :endtry の内側で assert_fails() が正常に機能しない

### ISSUE THREAD

**Issue by bmtsstl** [vim-jp/issues#1284]
### 現象・ログ

`assert_fails()` で実行されるコマンドでユーザー定義例外が発生すると、通常は `assert_fails()` の内部で捕捉されます。しかし、`:try` と `:endtry` の内側で同様に `assert_fails()` を実行すると、ユーザー定義例外が捕捉されません。このとき、`v:errors` を確認すると、"command did not fail" と記録されており、ユーザー定義例外が認識されていないことが分かります。

なお、この現象は `:throw` によって投げられたユーザー定義例外でのみ発生します。Vim 本体により発生されたエラー（例えば、E492: Not an editor command）は `:try` / `:endtry`  の内側であっても `assert_fails()` によって捕捉されます。

### 再現手順

```viml
try
    call assert_fails('throw "error"', "")
endtry
```

上記のスクリプトを test.vim として保存し、以下のコマンドを実行します。

```sh
vim -u NONE --cmd "source test.vim" --cmd 'echo "v:errors[-1]: " . v:errors[-1]' +qall!
```

出力結果は以下のようになります。

```
Error detected while processing /home/pi/test.vim:
line    2:
E605: Exception not caught: error
v:errors[-1]: /home/pi/test.vim line 2: command did not fail: throw "error"
```

### 期待動作

`:try` / `:endtry` の内側であっても、ユーザー定義例外が捕捉されるべきだと思います。

## Vimのバージョン

8.1.1640

## OSの種類/ディストリ/バージョン

以下の2つの環境で再現しました。

*   Linux raspberrypi 4.19.42-v7+ # 1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
*   Windows 10 Pro 64bit (10.0.18362)

## 使用している or 関係していそうなプラグイン

`vim -u NONE` しても再現するので、プラグインが原因ではないと思います。

## その他

vim-themis のテストスクリプトで `assert_fails()` を使うと同様の現象が起こります。

vim-jp/issues に投稿するのは初めてです。よろしくお願いします。

**Comment by ichizok** [comment]
報告ありがとうございます。
修正投げました。 https://github.com/vim/vim/pull/4639

**Comment by ichizok** [comment]
8.1.1660
https://github.com/vim/vim/commit/7780e5c1c5485a979ab6e3914a43e17912e213a8

**Comment by bmtsstl** [comment]
ありがとうございます！修正されたことを確認しました。
