### ISSUE TITLE
Bug: When blob is coping, flaky failed(probably lock flag uninitialized).

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/issues#1285]
## 不具合の内容

blobのコピーを伴なう動作を行なうと、時々(Flakyに)失敗する

### 現象・ログ

see

- https://vim-jp.slack.com/archives/C03C4RC9F/p1562811297091100
- https://travis-ci.com/tsuyoshicho/vital-codec/builds/118704242

```
Tsuyoshi CHO [11:14]
むう、やっぱり不規則に E742 になる...
｀｀｀Vim(let):E742: Cannot change value of self.v[1] = 0z646f72616e646f6d｀｀｀
https://travis-ci.com/tsuyoshicho/vital-codec/builds/118704242
(テストのエラーがそれぞれ違うこと、前の版は出てなく、ソース差分で見てもらえると分りますが、変更がテストコードにしかない状況で発生などが確認できた)
```

### 再現手順

厳密な再現はできず...

### 期待動作

未lockな変数への代入は常に成功する

## Vimのバージョン

$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 11 2019 02:09:26)
Included patches: 1-1661

## OSの種類/ディストリ/バージョン

*    Ubuntu 14.04.5 LTS Release amd64 in docker

## 使用している or 関係していそうなプラグイン

再現はVital上だが、おそらく関係なし

## その他

Ken Takata さんにより原因と思わしきところ、および修正案あり

https://vim-jp.slack.com/archives/C03C4RC9F/p1562815265091700

```diff
--- a/src/blob.c
+++ b/src/blob.c
@@ -63,6 +63,7 @@ blob_copy(typval_T *from, typval_T *to)
     int	    ret = OK;
 
     to->v_type = VAR_BLOB;
+    to->v_lock = 0;
     if (from->vval.v_blob == NULL)
 	to->vval.v_blob = NULL;
     else if (rettv_blob_alloc(to) == FAIL)
```

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/4648
（本当はテストもあるとよいのだが…）

**Comment by tsuyoshicho** [comment]
ありがとうございます。

たぶん実施するテストは作れても、100%再発するテストが作れないですからね...

未初期化系は、静的解析ツールにかけるくらいしかないですが、vimの規模かつあの複雑さだとチェックしきれなそうなのが厳しい。

**Comment by tsuyoshicho** [comment]
テスト時のコンパイルとしてmallocが非0fillで返すやつをリンクする、とかあればいいのかもしれませんが、そういうものに心当りがないですね...

**Comment by k-takata** [comment]
8.1.1671: https://github.com/vim/vim/commit/b7b9efbccfe17ee3f7b1bb877b7745d5bfbf0804
