### ISSUE TITLE
set signcolumn=numberの時、表示がおかしい

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/issues#1286]
## 不具合の内容

`set signcolumn=number` したとき、画面表示がおかしい

### 現象・ログ

[![Image from Gyazo](https://i.gyazo.com/8690432c5e484c2a997b89269a63cf43.png)](https://gyazo.com/8690432c5e484c2a997b89269a63cf43)

[![Image from Gyazo](https://i.gyazo.com/2425cebcc3b7883d9cffad1237fbbea4.png)](https://gyazo.com/2425cebcc3b7883d9cffad1237fbbea4)

### 再現手順

すみません、後で更新します。

基本は

```vim
set number
set signcolumn=number
```

してsignが発生する状態を観測すればよいはずです。

### 期待動作

以前は正常だった可能性があるので、その時の仕様の維持
おそらく、signがnumberの領域に表示されて、行はすべて同じ位置であること?

## Vimのバージョン

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 12 2019 19:10:02)
MS-Windows 64 ビット GUI/コンソール 版 with OLE サポート
適用済パッチ: 1-1669
```

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 64bit (1809 10.0.17763.557)

## 使用している or 関係していそうなプラグイン

なし、本体機能

## その他

from thincaさん
https://vim-jp.slack.com/archives/CJMV3MSLR/p1563265440160800

> 最近 number の幅の最大値をどうこうする変更があった気がするので考慮漏れかも?

**Comment by mattn** [comment]
sign に表示している文字が ambiguous width な文字の様に見えますが、どんな文字ですか？

**Comment by tsuyoshicho** [comment]
# 記号
nr2char(0x271a) " '✚'
です
[✚ \| heavy greek cross \(U\+271A\) @ Graphemica](https://graphemica.com/%E2%9C%9A)

# 再現

## 設定

```vim:testvimrc.vim
set ambiwidth=double
set number
set signcolumn=number
```

## boot vim
```shell
> gvim -u testvimrc.vim -N 
```

## テストデータ
```text
1
2222
3
```

## test1 single byte (+)
```vim
sign define test text=+
sign place 2 line=2 name=test
```
再現しない

## test2 unicode
```vim
sign define test text=✚
sign place 2 line=2 name=test
```
再現する

signcolumnの切り替えで表示切り替えると良く見えます
ambiwidthを切り替えても表示に変化はないように見えます

**Comment by k-takata** [comment]
U+271a ですが、Vimは半角幅と認識しているようですね。グリフは全角幅ですが。
あと、ambiguous widthでもないですね。

**Comment by mattn** [comment]
文字を ASCII 半角にして正しい動作になるなら仕様通り(納得いかんけど)という事ですかね。

**Comment by tsuyoshicho** [comment]
きびしい...けど解決策なさそうですね
Unicodeの定義が正義ではありますし

ちなみにフォントはCicaです

**Comment by tsuyoshicho** [comment]
あ、ただ、通常に戻したとき `signcolumn=yes` ですが、半分欠ける問題はでますが、表示位置のズレはないんですよ(numberも文章も正常に表示される)

表示の問題という意味では、そこは改善したほうがいい気がします

**Comment by tsuyoshicho** [comment]
```vim
sign define test text=山
sign place 2 line=2 name=test
```

としたとき、あきらかに表示がズレるので、やはり(すくなくとも描画に)問題がある、と思います。

**Comment by mattn** [comment]
すみません。まだいまいち何が問題なのか分かってないです。

**Comment by tsuyoshicho** [comment]
えっと順を追って画像を張ります

[![Image from Gyazo](https://i.gyazo.com/2eb964c748bf880d62f864f718b3093c.png)](https://gyazo.com/2eb964c748bf880d62f864f718b3093c)
設定前

[![Image from Gyazo](https://i.gyazo.com/1a22f8fa407fda5abae5080aede0bcd9.png)](https://gyazo.com/1a22f8fa407fda5abae5080aede0bcd9)
設定時

[![Image from Gyazo](https://i.gyazo.com/78d36a43b0d4483bc1841746d0d67533.png)](https://gyazo.com/78d36a43b0d4483bc1841746d0d67533)
先頭のカーソル

[![Image from Gyazo](https://i.gyazo.com/df53ef685eafc2ce4d8b8766199bd563.png)](https://gyazo.com/df53ef685eafc2ce4d8b8766199bd563)
行選択

[![Image from Gyazo](https://i.gyazo.com/fac603ae6e137cafdb73e3d9d4ffbb94.png)](https://gyazo.com/fac603ae6e137cafdb73e3d9d4ffbb94)
signcolumn=yes

と表示位置/編集位置がずれます。
なお、先頭を選択しているときは、位置はあれでも、先頭自体を編集できます。

---

山は明確に2文字幅ですが、`signcolumn=yes` で正常に表示できるにもかかわらず、 `signcolumn=number` で破綻してしまうのは、一貫性から見てもよくないのではないか、と思います。

\# signcolumn=yesでも破綻するなら、2文字幅を設定するな、で一貫してますが

**Comment by mattn** [comment]
なるほど分かりました。

```vim
set number
set signcolumn=number
sign define test1 text=山
sign define test2 text=a
sign place 2 line=10 name=test1
sign place 2 line=11 name=test2


"xxx
"xxx

```

**Comment by mattn** [comment]
```diff
diff --git a/src/screen.c b/src/screen.c
index 825b7ab0e..c6bc1969a 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -3120,8 +3120,10 @@ get_sign_display_info(
 		{
 		    if (nrcol)
 		    {
-			sprintf((char *)extra, "%*s ", number_width(wp),
-								*pp_extra);
+			sprintf((char *)extra, "%*s ",
+				number_width(wp)
+				    + (*mb_ptr2cells)(*pp_extra) - 1,
+				    *pp_extra);
 			*pp_extra = extra;
 		    }
 		    *c_extrap = NUL;
```
これでどうでしょうか？

**Comment by mattn** [comment]
左寄せの方がいいのであれば

```diff
diff --git a/src/screen.c b/src/screen.c
index 825b7ab0e..315c39820 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -3120,8 +3120,10 @@ get_sign_display_info(
 		{
 		    if (nrcol)
 		    {
-			sprintf((char *)extra, "%*s ", number_width(wp),
-								*pp_extra);
+			sprintf((char *)extra, "%-*s ",
+				number_width(wp)
+				    + (*mb_ptr2cells)(*pp_extra) - 1,
+				    *pp_extra);
 			*pp_extra = extra;
 		    }
 		    *c_extrap = NUL;
```

**Comment by tsuyoshicho** [comment]
現在環境整理中...ためしてみます

いまの表示的には左が様式的に綺麗かなあ?

**Comment by tsuyoshicho** [comment]
修正案ありがとうございます。

[![Image from Gyazo](https://i.gyazo.com/c0dd18fe933e763232e357584a60de57.png)](https://gyazo.com/c0dd18fe933e763232e357584a60de57)

左寄せで修正確認しました。
良いのではないかと思います。

**Comment by tsuyoshicho** [comment]
このオプションの都合、幅不足だと数字側が消えるのはしょうがないでしょうね...

**Comment by tsuyoshicho** [comment]
条件などは少し違いますが、 #1273 は関係している可能性がありそうです。

**Comment by mattn** [comment]
#1273 はあとでもう一度確認して難しそうならもう投げてよいかもですねぇ。

**Comment by tsuyoshicho** [comment]
はい、この修正とは独立して見てみる必要はありそうです...
というかとりこまれたときにどうなるか再確認するくらいかな

**Comment by mattn** [comment]
このパッチで https://github.com/vim-jp/issues/issues/1273 を試してみましたが、直ってるっぽいですね。

**Comment by mattn** [comment]
あとテストを見てて気付いたのですが、どうやら現状が右寄席っぽいです。右寄せで pull-req 投げます。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/4694

**Comment by mattn** [comment]
[patch 8.1.1712](https://github.com/vim/vim/commit/d6bcff457799e491c3d27880858ec08e758e1849)
