### ISSUE TITLE
get() でキーが無かった場合に関数を呼んでその値を返したい

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1288]
## 内容

`get()` はグローバル変数の初期化など、変数が存在しない場合の値の設定によく使われます。

```vim
let g:myplugin_globalvar = get(g:, 'myplugin_globalvar', 42)
```

しかしデフォルト値を遅延して構築したい場合に `get()` だと引数が評価されてしまうので使えません。

```vim
" s:build_lazy() がその場で評価されてしまう
let g:myplugin_globalvar = get(g:, 'myplugin_globalvar', s:build_lazy())
```

そこで `get()` のデフォルト値に Funcref, Partial, string expression (`v:val * 2` のような) を与えて評価した値を返す遅延版 `get_lazy()` を導入したいです。

```vim
" s:build_lazy() は g:myplugin_globalvar が無かった場合だけ実行される
let g:myplugin_globalvar = get_lazy(g:, 'myplugin_globalvar', {-> s:build_lazy()})
```

## Vimのバージョン

8.1.1711

**Comment by tyru** [comment]
https://github.com/vim/vim/pull/4696

**Comment by k-takata** [comment]
vim/vim#4696 はrejectされましたね。
