### ISSUE TITLE
ヒアドキュメントに trim 以外の新しいフラグを追加すると互換性が壊れてしまう

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1293]
## 内容

普通のヒアドキュメントはこのように使いますが、

```vim
  let text =<< trim END
    if ok
      echo 'done'
    endif
  END
```

もし今後改行も文字列のリストに含むようにする `eol` というフラグが追加されたとします。
その場合、以下のように `eol` をマーカーとして使っていたスクリプトはマーカーが見つからないとしてエラーになってしまいます。

```vim
  let text =<< trim eol
    if ok
      echo 'done'
    endif
  eol
```

### 実現方法

マーカーは大文字限定とし、フラグは小文字限定とする、という制限を入れます。
そうする事で上記のような曖昧さはなくなり、互換性を壊す事もなくなります。

## Vimのバージョン

8.1.1711

**Comment by tyru** [comment]
報告しました https://github.com/vim/vim/issues/4705

**Comment by mattn** [comment]
本件修正されているので閉じます。

[patch 8.1.1723](https://github.com/vim/vim/commit/24582007294b0db3be9669d3b583ea45fc4f19b8)
