### ISSUE TITLE
bufnr(name, 1) で作ったバッファに appendbufline() でテキストが足せない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#1299]
## 不具合の内容

`bufnr(name, 1)` を使うと、生成はされたけどまだ開かれていないバッファを作れますが、このバッファに対して `appendbufline(n, 1, ['foo'])` 等でテキストを追加しても失敗(戻り値が 1)になってしまいます。

### 再現手順

```vim
let b = bufnr('foo', 1)
echo appendbufline(b, 1, ['foo', 'bar'])
" => 1
echo getbufline(b, 1, '$')
" => []
```

### 期待動作

```
0
['', 'foo', 'bar']
```

## Vimのバージョン

8.1.1866

## OSの種類/ディストリ/バージョン

*   Gentoo Linux

## 使用している or 関係していそうなプラグイン

なし

## その他

代理報告になります。現象は確認しましたが、これで特別困っていると言うわけではないです。

**Comment by h-east** [comment]
関連Issue
https://github.com/vim/vim/issues/5044

上記issueを踏まえて、appendbufline(), deletebufline(), setbufline() のhelpに以下の文章が追加されました。

https://github.com/vim/vim/commit/2e693a88b24dc6b12883fad78ff2cb9cd4469c98#diff-bea881dfa9626bab7141337b0fcdb23eR2974-R2979

                This function works only for loaded buffers. First call
                bufload() if needed.

ということで、この3関数は「ロードされているバッファに対してのみ動作する」という仕様になりました。

**Comment by thinca** [comment]
コメント今気付きました。回避策があるとのことで問題なさそうですね。ありがとうございます！
