### ISSUE TITLE
IMEのON/OFFをsyntaxで制御する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#13]
ちょっと面白い提案があったので、議論、検討用に転載します。

> ダブルクオートとコメントの中でしか日本語入力をONにできないようにして欲しい

プログラマ的には「わかる」要求。
- スクリプトだけでできるか?
- 本体いじるならどうやるべきか?

**Comment by tyru** [comment]
本体もいじる案を提案したいです。
というか自分自身これで(skk.vim, eskk.vimで)悩んでいるので、
厚かましいですがパッチを書いてくれるのならぜひお願いしたいです...

自分の提案する案は、「VimスクリプトでInsertEnterの時にCommentの中にいたらIMEをonする」という案です。
次のコードはそれを意図したコードです。

```
autocmd InsertEnter *
\     for id in synstack(line('.'), col('.'))
\   |   if synIDattr(synIDtrans(id), 'name') ==# 'Comment'
\   |     let &l:iminsert = 2
\   |   endif
\   | endfor
```

しかし現状この挙動通りにはいかなくて、単純に
`autocmd InsertEnter * let &l:iminsert = 1` のようにしてもインサートモードでlang modeになりません。
`<Esc>i`してインサートモードに入り直すとlang modeになっています。
上のコードが意図通りになればスクリプトから制御できるようになり、便利だと思います。

また逆に「InsertEnterの時にCommentの外にいたらIMEをoffにする」
のような機能がEmacsのddskkというプラグインにあるので、
その機能を実現するためにonするだけでなく`let &l:iminsert = 0`のようにしてoffにすることもできれば可能にしたいです。

**Comment by koron** [comment]
tyruさんの提案はハイブリッドってところですね。
IMEのON/OFFをスクリプトから制御できる方法を用意し、
スクリプトでそれを使って細かく制御しようと。

私の最初の想定ではsyntaxにIME可/不可を設定できるようにして、
その制御までVim側でということも考えていました。

tyru案のほうが本体をいじる手間は少なくてステキそうなんですが、何か他に案はあるでしょうか?

もっとも環境によってIMEのON/OFFの制御は超むずかったりしますけどw

**Comment by thinca** [comment]
ふと思ったのですが、iminsert の変更と実際のIMの状態の変更のタイミングがずれていること自体がバグだったりしないでしょうか。

**Comment by koron** [comment]
いやそれは意図した動作です。
iminsertはIMEの状態にマップされた変数では**無く**
あるタイミングで適用&更新されるだけの値なんですよ。

なのでIME制御用のeval funcを追加するのが確実な気がします。

**Comment by koron** [comment]
なんかiminsertを即時適用しても良い気がしてきた。
ただタイミング次第ではバグになりそう。
- `iminsert` したら非編集モードなのにimeがonになった

みたいな。

**Comment by koron** [comment]
@tyru さん: 私の手元のWindowsだとそのコードで、コメントの中だけ自動的にIMEがONになる(意図どおりに動く)んですが…動かないといった環境を教えてもらえますか?

Vimのソースコードを確認してたら、src/edit.cのedit()の中でautocmd InsertEnterを実行したあとでiminsertの値を実際のIMEのON/OFFに適用するってなってました。私は勘違いでコレが逆になってて動かないだろうなと予測していたんですが、この順番ならInsertEnterで設定したiminsertは正しく反映されます。仮に反映できないとしたら、IME制御がうまくいかないOSとかUI環境があるという話で、また別の問題になります。

あと、もともとの提案はIMEをONにできないようにしたい、という提案とも読める。となるとimdisableでの制御ができるか。

**Comment by koron** [comment]
ちょっとやってみたのだけれど
editモード(CursorMoveI)中のlet &l:imdisable = 0が効かないみたい。
逆のlet &l:imdisable = 1は効いてる。

``` vim
augroup LimitIME
  autocmd!
  autocmd InsertEnter * call s:LimitIME()
  autocmd CursorMovedI * call s:LimitIME()
augroup END

function! s:LimitIME()
  let disable = 1

  for id in synstack(line('.'), col('.'))
    let attr = synIDattr(synIDtrans(id), 'name')
    if attr ==# 'Comment' || attr ==# 'String'
      let disable = 0
      break
    endif
  endfor

  if &l:imdisable != disable
    let &l:imdisable = disable
  endif
endfunction
```
1. こんなスクリプトを*.cでsourceして、
2. コメント内でInsertモードに入りIMEをON
3. Insertモードのままコメント外へカーソルを動かしてIMEがOFFになる
4. Insertモードのままコメント内へカーソルを動かしてもIMEはOFFのまま、IMEをONするキーを押しても変わらない

といった状況。再現環境はWindowsの香り屋版。imdisableの実装内容をチェックしなきゃダメっぽい。

**Comment by koron** [comment]
推測だけど、CursorModeIはiminsertも当然働かないハズ…だよなぁ?

**Comment by koron** [comment]
@tyru さん:
[issue 64](https://github.com/vim-jp/issues/issues/64) に書いたように、
editモード中(特にCursorMovedI)の最中にiminsertをset/getしても正しく動かないのは確認しました。
それに対してInsertEnterでは正しく動作することを確認しています。
(Windowsだけですが)

ところがtyruさんの報告はInsertEnterでも動作しないとのことで、私の推測&観測とはズレています。
ちょっと報告の内容が再現するか確認し、するようなら環境等を細かく報告してください。

**Comment by tyru** [comment]
> @tyru さん: 私の手元のWindowsだとそのコードで、コメントの中だけ自動的にIMEがONになる(意図どおりに動く)んですが…動かないといった環境を教えてもらえますか?

@koronさん すみません、自分の環境(Ubuntu 11.04, Vim 7.3.322)でも正しく動きました。
前のバージョンで動いてなかったのですが、issue登録する前に確認してなかったです。すみませんorz

試してみたら、onするだけでなく、こんな風にoffにするのもできますね。
じゃあこれはもう実現できてるのかもしれません。
ちょっとまた詳しく調べてからcloseにします。(あ、今見たらそもそも権限なかった...)

```
autocmd InsertEnter *
\     for id in synstack(line('.'), col('.'))
\   |   let &l:iminsert = (synIDattr(synIDtrans(id), 'name') ==# 'Comment' ? 1 : 0)
\   | endfor
```

**Comment by tyru** [comment]
> あと、もともとの提案はIMEをONにできないようにしたい、という提案とも読める。となるとimdisableでの制御ができるか。

自分の上のコメントで出した例のようにonとoff両方制御したいです。
なので、自分の要望としては見たとろ実現できているように思います。
eskk.vimでこれをやりたかったので、それで実装してうまく動いているようならcloseします。

**Comment by koron** [comment]
あ、まだcloseしないでください。
なぜならCursorMovedI中のiminsertの制御はかなり変になってるので。

最悪のケースでもwon't fixという分類ができてからcloseしたいです。

**Comment by tyru** [comment]
了解です。

**Comment by koron** [comment]
> CursorMovedI中のiminsertの制御はかなり変

これは変わらないが、そこで変えたいという要求は今のところないので本issueは won't fix として閉じます。

**Comment by tyru** [comment]
#228 を参照してpushしてしまいましたが、以下が動作するのをeskkで確認しました。(遅い)

> @tyru さん:
> issue 64 に書いたように、
> editモード中(特にCursorMovedI)の最中にiminsertをset/getしても正しく動かないのは確認しました。
> それに対してInsertEnterでは正しく動作することを確認しています。
> (Windowsだけですが)
> 
> ところがtyruさんの報告はInsertEnterでも動作しないとのことで、私の推測&観測とはズレています。
> ちょっと報告の内容が再現するか確認し、するようなら環境等を細かく報告してください。
