### ISSUE TITLE
棚卸ししたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#130]
パッチはあるけどポストされてない物があると思うので、出来ればvim_devに送ってしまいたい。

**Comment by thinca** [comment]
kaoriya版に含まれているパッチは、全て1度送ったことがあるのでしょうか?

以前私が独自に調べたもの
http://d.hatena.ne.jp/thinca/20090619/1245338963

"browsefilter にマルチバイト文字が含まれていると化けるバグ" とかは明らかにバグなので送っていれば取り込まれていてもおかしくなさそうな気がしますが…。

**Comment by mattn** [comment]
> 日本語のメッセージや tutor の間違いを修正してある。

これもバグといえばバグ。

**Comment by mattn** [comment]
どうなったの？的な所も含めて...

#49 :help! で E478 が発生する
#30 gVimでIMEオン時のカーソル表示が残る(環境依存)
#64 iminsertとimdisableが直ちには反映されない
#66 QuickRunで落ちるらしい
#70 Issueの管理方法を整理したい
#82 ファイル選択ダイアログでのIM状態がGVimに反映されてしまう
#116 カレントタブ以外に変更されたバッファがある場合に :qa するとカレントタブが変更されたバッファに切り替わる

**Comment by h-east** [comment]
#30 は解決してないです。調査途中のまま。
#82 はpatchあるけど、Windowsのみのバグのくせに message.c を修正してて「それでいいの？」状態です。

**Comment by koron** [comment]
+kaoriyaパッチは基本的に「これ送っても取り込まれる見込みないわ」っていう愚連隊です。

ただMigemoはスクリプトに形を変えればありなんじゃないかとも思ってます。概念的にはpattern_hook_exprみたいな形で。

**Comment by koron** [comment]
メッセージやメニューの翻訳ファイルは時々、本体に反映させてます。タイミング的にはリリースと、あと時間がとれて全部見直せた時など。

**Comment by Shougo** [comment]
個人的に、Migemoは本体に取り込まれてほしいですね。

**Comment by koron** [comment]
#64 はimdisable だけが対応済み。iminsertは未対応。

**Comment by mattn** [comment]
@koron browsefilter は送ってない感じ？

**Comment by mattn** [comment]
ちなみにkaoriya版のdiffって手軽に見れるかしら

**Comment by koron** [comment]
@mattn browsefilterってなんだっけ?w diffはzipに入ってたはず。

**Comment by thinca** [comment]
@koron >>2

**Comment by h-east** [comment]
#116 カレントタブ以外に変更されたバッファがある場合に :qa するとカレントタブが変更されたバッファに切り替わる
↑これもpatchあります。＆vim-jp内でタブ関連の提案をしているけど反応ないなぁ。

**Comment by koron** [comment]
`convert_filterW()` の修正か。だれかIssue化&切り出して送ってもらえませんか。ところでこれ僕が書いたんだっけ?

**Comment by koron** [comment]
昔は機能毎にパッチを分けて管理してたけど、最近はめんどくさくて一枚にしちゃったからいろいろわかりませんなw

**Comment by mattn** [comment]
上記で未解決のissue

#30 gVimでIMEオン時のカーソル表示が残る(環境依存)
#64 iminsertとimdisableが直ちには反映されない
#66 QuickRunで落ちるらしい
#82 ファイル選択ダイアログでのIM状態がGVimに反映されてしまう

**Comment by thinca** [comment]
上記の4つのうち残っているのは #30 だけで、残りは閉じられてますね。

**Comment by koron** [comment]
このIssueは自己言及的ね。一旦閉じちゃいjます。
