### ISSUE TITLE
win_execute()を使って作成したポップアップウィンドウを閉じるとE315エラーが出る

### ISSUE THREAD

**Issue by mityu** [vim-jp/issues#1300]
## 不具合の内容

ポップアップウィンドウを作成した後、`win_execute()` を使ってそのポップアップウィンドウを閉じようとすると E315エラーが出ます。

### 再現手順

```vim
let s:cpoptions_save = &cpoptions
set cpoptions&vim

let s:winID = popup_create('', {})

call win_execute(s:winID, printf("normal! :\<C-u>call popup_close(%d)\<CR>", s:winID))

let &cpoptions = s:cpoptions_save
unlet s:cpoptions_save
```

上記スクリプトを `bug.vim` として保存し、  
`vim -u NONE -c "so path/to/bug.vim"`  
とすると、

```
Error detected while processing /Users/mityu/bug.vim:
line    6:
E315: ml_get: invalid lnum: 1
```

とエラーが出ます。

### 期待動作

エラーが出ない

## Vimのバージョン

8.1.1866

## OSの種類/ディストリ/バージョン

macOS Mojave

## 使用している or 関係していそうなプラグイン

なし

## その他

~~スクリプト内で `set cpoptions&vim` を設定しなければ再現しませんでした。~~

**Comment by h-east** [comment]
再現手順の `vim -u NONE -c "path/to/bug.vim"` は `vim -u NONE -c "so path/to/bug.vim"` ですよね？

こちらでも再現しました。(Ubuntu 18.04.2 64bit, Vim 8.1.1888)
こちらでは、ほぼSEGVで落ちますね。(`set cpoptions&vim`の有無は関係ないようです)

**Comment by mityu** [comment]
色々不備があってすみません...

> 再現手順の `vim -u NONE -c "path/to/bug.vim"` は `vim -u NONE -c "so path/to/bug.vim"` ですよね？

はい、ご指摘の通りです。

> `set cpoptions&vim`の有無は関係ないようです

私が何か勘違いしてたみたいです。こちらも `set cpoptions&vim` なしで再現しました。

**Comment by mattn** [comment]
win_execute なので curwin をすぐずらす訳にもいかないので落ちる箇所だけ実行しない様にしました。

```diff
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index fb07450f8..f9af63846 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -7420,6 +7420,8 @@ ex_mark(exarg_T *eap)
     void
 update_topline_cursor(void)
 {
+    if (!win_valid(curwin))
+	return;
     check_cursor();		// put cursor on valid line
     update_topline();
     if (!curwin->w_p_wrap)
```

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/5345

**Comment by mattn** [comment]
パッチ書いてて気付いたんですが、これはエラーを発生させるべきでした。pull-req は修正済みです。

**Comment by mityu** [comment]
すみません、気付くの遅れました...
バグが修正されているのが確認できたので、このissueは閉じます。
対応ありがとうございました！

**Comment by k-takata** [comment]
8.1.2420: https://github.com/vim/vim/commit/4954019c93a2bb5a0b1af54b5961c933beeb56f4
