### ISSUE TITLE
Windows で &shell にスペースが含まれると外部コマンドが実行できない

### ISSUE THREAD

**Issue by Milly** [vim-jp/issues#1301]
## 不具合の内容

Windows で &shell にスペースが含まれると外部コマンドが実行できない。

* `$SHELL` から自動設定される `&shell` のエスケープが不適切。(現象1)
  *  Windows でも空白がバックスラッシュでエスケープされる。
  * 結果、外部コマンドの実行が失敗する。
* `&shell` にダブルクォートで囲んだパスを指定しても実行できない場合がある。(現象2)
  * `system()` や `:!` で失敗する。
  * GUI版で `set noshelltemp` すると `system()` や `:!` も実行できる。
  * `:term` や `job_start()` では実行できる。
    * `set guioptions+=!` すると `:!` も実行できる(`:term` と同じ)。

### 現象・ログ、再現手順

1. [Git bash](https://gitforwindows.org) を実行。パスは `C:\Program Files\Git\usr\bin\bash.exe` である。
2. bash で `gvim.exe  -u NONE -U NONE` を実行。
3. Vim で `&shell` を確認。(現象1)

       :echo &shell
       C:\Program\ Files\Git\usr\bin\bash.exe
                 ^ ここにバックスラッシュが入っている

4. `&shell` を修正。

       :let &shell = '"'.$SHELL.'"'
       :echo &shell
       "C:\Program Files\Git\usr\bin\bash.exe"

5. 外部コマンドを実行。(現象2)

       :!echo ok
       'C:\Program' は、内部コマンドまたは外部コマンド、
       操作可能なプログラムまたはバッチ ファイルとして認識されていません。

### 期待動作

* `&shell` について。(現象1)
  * ダブルクォートで囲うのが適切であろうか。
* 外部コマンドの呼び出しについて。(現象2)
  * 実行されること。

## Vimのバージョン

Chocolatey `cinst vim-tux` を利用。
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 21 2019 19:50:06)
MS-Windows 64-bit GUI/console version with OLE support
Included patches: 1-1906
Compiled by stop_@LAPTOP-E7OHISR4
```

## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit (10.0.18362)

### `&shell` について。(現象1)

[`set_init_1()` in *option.c*](https://github.com/vim/vim/blob/c1f87c9a31e0c91f2d936661e1c4df8e12e19766/src/option.c#L3332) で `set_string_default_esc()` が呼ばれているが、0x20をバックスラッシュでエスケープするだけでWindowsでは不適切な処理である。

### 外部コマンドの呼び出しについて。(現象2)

* `_wsystem()` に与えるコマンド文字列が不正であるためパースに失敗している。
* [*vimrun.c*](https://github.com/vim/vim/blob/c1f87c9a31e0c91f2d936661e1c4df8e12e19766/src/vimrun.c#L74) と、CUI版の [`mch_system_c()` in *os_win32.c*](https://github.com/vim/vim/blob/c1f87c9a31e0c91f2d936661e1c4df8e12e19766/src/os_win32.c#L4497) で呼ばれている。
* `_wsystem()` は `%COMSPEC%` を参照しているが、*cmd.exe* を前提にしているため `%COMSPEC%` に *bash.exe* を指定しても正常に動作はしない。(`/c` が使われるため)
* コマンド文字列の両端のダブルクォートが `_wsystem()` から呼び出された *cmd.exe* によって削除されてしまっている。
* `(commands ..)` のように括弧で囲めば動作すると思われる。*vimrun.exe* で試せる。

       > vimrun.exe "C:\Program Files\Git\usr\bin\bash.exe" -c "echo ok"
       "C:\Program Files\Git\usr\bin\bash.exe" -c "echo ok"
       'C:\Program' は、内部コマンドまたは外部コマンド、
       操作可能なプログラムまたはバッチ ファイルとして認識されていません。
       shell returned 1

       > vimrun -s ("C:\Program Files\Git\usr\bin\bash.exe" -c "echo ok")
       ("C:\Program Files\Git\usr\bin\bash.exe" -c "echo ok")
       ok

* [`ShellExecuteW()` in *os_win32.c*](https://github.com/vim/vim/blob/c1f87c9a31e0c91f2d936661e1c4df8e12e19766/src/os_win32.c#L3924) も同様か。
  * GUI版で・*vimrun.exe* が存在せず・`set shelltemp guioptions-=!` の場合のみ呼ばれる？(追いきれてません)

### 関連

#1079 vim/vim#2054

**Comment by Milly** [comment]
PRed: vim/vim#4920

したんですが、`system()` をぶっ壊してしまっていました……

**Comment by k-takata** [comment]
`:set shell=C:\Program Files\Git\usr\bin\bash.exe` だと動いたりしませんか？（余計なバックスラッシュもダブルクォーテーションもなし）

**Comment by Milly** [comment]
Vim 側でのコマンドライン構築処理では `&shell` の値はエスケープ済みの前提で実装されており、構築処理側で修正を行うと Unix 側の修正も必要になってしまい影響範囲が広がります。
最終的に `_wsystem()` にコマンドライン文字列として渡されるんですが、そのコマンドラインを解釈するのは `%COMSPEC%` (*cmd.exe*) になるのでクォートされてないと動きません。

```vim
:let &shell = 'C:\Program Files\Git\usr\bin\bash.exe'
:!echo ok
C:\Program Files\Git\usr\bin\bash.exe /c (echo ok)
'C:\Program' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
shell returned 1
```

なおすでに `system()` を壊さない修正を実装済みで、vim/vim#4920 に続けて push する予定です。
(テスト中)

**Comment by k-takata** [comment]
ああ、vim/vim#4923 が動いていたのは `:term` だけでしたか。

**Comment by Milly** [comment]
Job 関係は `_wsystem()` ではなく `CreateProcessW()` が使われています。
コマンドライン構築も別処理なのでスペースが入っていても動作します。
ただし、Vim 起動時の初期化でエスケープがおかしいままだと動作しません。

**Comment by Milly** [comment]
Merged at vim/vim@2efc44b

**Comment by Milly** [comment]
@k-takata PRへのconfirmedありがとうございました！
