### ISSUE TITLE
IMEの状態を取得する機能、状態変更イベントの追加

### ISSUE THREAD

**Issue by Milly** [vim-jp/issues#1303]
## 内容

IMEの状態を取得する機能、状態変更のイベントの追加。

Shougo/deoplete.nvim#1003 にて、未確定のIME入力を非同期に確定させてしまうバグが発生したが、IMEの状態取得ができないので修正を断念した。

特にWindows GUI版において。

### Pros 良くなる点

IME状態に応じて制御を分けるプラグインが開発できる。

### Cons 悪くなる点

とくになし。

### 実現方法

* `getimstatus()` 関数の追加。
  * C関数 `im_get_status()` を呼べばよいか。
    * [in mbyte.c](https://github.com/vim/vim/blob/v8.1.1927/src/mbyte.c#L5853)
    * [in gui_w32.c](https://github.com/vim/vim/blob/v8.1.1927/src/gui_w32.c#L5783)
    * [in gui_mac.c](https://github.com/vim/vim/blob/v8.1.1927/src/gui_mac.c#L6298)
  * 未確定状態の入力があるかどうかも判定したいが難しいか。(Windows MS-IME だけならできそうだが。)
* GUI版で `IMChanged` イベントの追加。
  * `CursorIM` を更新するタイミングで呼べばよいか。

## Vimのバージョン

8.1.1927

## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit (10.0.18362)

### この機能が必要か？

`CursorIM` と同程度に **役に立つ** のではないか。

     *CursorIM*
     IMEの状態に応じてカーソルの色を変えることができる。通常、IMEの状態はデスク
     トップの隅(やタスクバー)に表示されているが、これはあまり確認しやすくないの
     で、この機能が役に立つ。

### 関連

* #739
* #1130
* #1195

**Comment by Milly** [comment]
`getimstatus()` 関数を実装してみました。
Windows では動きました。

vim-jp/vim#5

(vim-jp/vim が vim/vim と乖離してて差分がでかい…。)

**Comment by k-takata** [comment]
> vim-jp/vim が vim/vim と乖離してて差分がでかい…。

更新しておきました。

**Comment by Milly** [comment]
ありがとうございます。
すでに出してしまったPRでは結局でかい差分が表示されっぱなしなんですね。
→forced push したら余分なの消えた。

**Comment by Milly** [comment]
vimにPRするとして、関数追加とイベントの追加は分けて粒度を下げたほうがいいですかね？
機能は関連しているけど密接に結合しているわけではないです。

**Comment by tsuyoshicho** [comment]
分離可能なら小分けにしたほうが、レビューはしやすい&採用されやすい(かもしれない)気はします

**Comment by Milly** [comment]
Add function `getimstatus()`.
PRed: vim/vim#4904
Merged: 8.1.2000 (vim/vim@a3a1246)

イベントについては実装が少し手間なので必要度が上がったらまた考えます。

**Comment by tyru** [comment]
入りましたね。

**Comment by Milly** [comment]
困ってないのでイベントの実装はpendingのままで閉じます。
