### ISSUE TITLE
gdbが入っていないMacで:Termdebugをすると、Vimがフリーズする

### ISSUE THREAD

**Issue by get-me-power** [vim-jp/issues#1305]
## 不具合の内容

IK 15:49

`gdb` がインストールされていない `mac OS Mojave` で、 `:packadd termdebug`  してから  `:Termdebug` するとVimがフリーズする。

また、CPU使用率が暴走する。

`vim/runtime/pack/dist/opt/termdebug/plugin/termbebug.vim` のソースコードを読んだら、該当箇所で `return` をしているので問題なさそう。

brew install gdb して、動かすと問題なく`:Termdebug`が動く。

### 現象・ログ

<img width="554" alt="スクリーンショット 2019-09-05 15 50 58" src="https://user-images.githubusercontent.com/36619465/64320448-8794e800-cff9-11e9-9cad-725a47da269e.png">

<img width="554" alt="スクリーンショット 2019-09-05 15 51 46" src="https://user-images.githubusercontent.com/36619465/64320483-9aa7b800-cff9-11e9-8899-9b5d62bfeb78.png">

### 再現手順

`gdb` が入っていない状態で

1. `:packadd termbebug`

2. `:Termdebug`

### 期待動作

エラーがでて、`Enter`を押せばbufferが閉じる。

## Vimのバージョン

8.1.1972

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

*   macOS Mojave ver 10.14.6

## 使用している or 関係していそうなプラグイン

`termbebug.vim`

(関係していそうなプラグインなどがあればココに書いてください)

## その他

`vim -u NONE` で起動した後でも同じ現象が起きた。

**Comment by kazukazuinaina** [comment]
修正するべき箇所があればどこか知りたいです。

**Comment by ichizok** [comment]
Macに限らず、gdbが入ってない環境で発生するようです。(Ubuntu 18.04で確認)
完全にフリーズする訳ではなく、Ctrl-Cを連打していると戻ります。

**Comment by mattn** [comment]
たしか起動を確認する busy loop が入ってたと思いますね。

**Comment by h-east** [comment]
(ソース見てないけど)実行前に`executable('gdb')`でチェックすればいいのかな？

**Comment by ichizok** [comment]
こんな感じですかね。

```diff
--- a/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
+++ b/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
@@ -107,6 +107,12 @@ func s:StartDebug_internal(dict)
     echoerr 'Terminal debugger already running'
     return
   endif
+
+  if !executable(g:termdebugger)
+    echoerr 'Cannot execute debugger program "' .. g:termdebugger .. '"'
+    return
+  endif
+
   let s:ptywin = 0
   let s:pid = 0
 
```

**Comment by get-me-power** [comment]
`executable('gdb')` のチェックをVim本体のtermdebug.vimに追加してPull Requestを送ればいいですか？

**Comment by tsuyoshicho** [comment]
必須の実行ファイルなら
`if !executable('gdb') | finish | endif` 的なのはあってもいい気はしますね...

**Comment by get-me-power** [comment]
@tsuyoshicho 

わかりました。patchを作成して送りたいと思います。

**Comment by ichizok** [comment]
すみません、私の方でPR済みです。
https://github.com/vim/vim/pull/5000

**Comment by get-me-power** [comment]
わかりました、ありがとうございます。

**Comment by h-east** [comment]
8.1.2103 :+1:
https://github.com/vim/vim/commit/18223a592efa4399e3951c86deeb712a13b05ca5
