### ISSUE TITLE
:lnfile等でSegmentation fault (core dumped)

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1309]
## 不具合の内容
`:lnfile`
や
`:lnext`
で別ファイルを開くタイミングで、セグメンテーション・フォルトで落ちるときが有ります

プラグインに依存の気もしますが、セグメンテーション・フォルトで落ちているので、こちらにご報告をします
### 再現手順
次の環境で、main.tex を開いて
`:lnfile`
をすると落ちます
![tex](https://user-images.githubusercontent.com/24851657/65514423-3b620700-df18-11e9-9095-1964b4f0d3eb.gif)

他にも次の校正・内容だと
`:lnext`
やローカルリストの 2, 3 行目で <Enter> も同様です
### 環境・ファイル構成
`:r!grep -Ev '^\s*"' ~/.vim/vimrc`
```
scriptencoding utf-8
set runtimepath+=~/.vim/bundle/repos/github.com/vim-syntastic/syntastic/
let g:syntastic_check_on_open = 1
let g:syntastic_auto_loc_list = 1
filetype plugin indent on
```
`:put=execute('echo &runtimepath')`
```
/home/xxx/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim81,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,/home/xxx/.vim/after,/home/xxx/.vim/bundle/repos/github.com/scrooloose/syntastic/
```

普段は、プラグインをdeinで管理していますが、以前関係を最小化するためruntimepathの書き換えにけてあります

`r! tree ~/downloads/sample/`
```
/home/xxx/downloads/sample/
├── a.tex
├── b.tex
└── main.tex
```
`:r! cat ~/downloads/sample/main.tex`
```
\documentclass[uplatex]{jsarticle}
\input{not_exist.tex}
\begin{document}
\input{a.tex}
\end{document}
```
`:r! cat ~/downloads/sample/a.tex`
```
\input{b.tex}
\input{b.tex}
```
`:r! cat ~/downloads/sample/b.tex`
```
\begin{description}
	 a != b
\end{description}
```
## Vimのバージョン
`$ vim --version`
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 07 2019 11:42:36)
適用済パッチ: 1-320
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
```
## OSの種類/ディストリ/バージョン

`$ lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```
`$ uname -a`
```
Linux xxx 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
## 使用している or 関係していそうなプラグイン
[vim-syntastic/syntastic](https://github.com/vim-syntastic/syntastic)
`:put=execute('SyntasticInfo')`
```
Syntastic version: 3.9.0-44 (Vim 801, Linux, GUI)
Info for filetype: text
Global mode: active
Filetype text is active
The current file will be checked automatically
Available checker: textlint
Currently enabled checkers: -
```

**Comment by h-east** [comment]
@iranoan Issue登録お疲れ様です。

textlintのインストールが必要ですよね？。そしてtextlintのインストールには npm が必要かな？
textlint (と npm)をインストールして試行錯誤してみたけど駄目でした。

SyntasticInfo の結果の最後から2行目が `Available checker: textlint` にならないです。
`Available checker: -` になります。(他は iranoan さんと同じになりました)

**Comment by iranoan** [comment]
```
SyntasticInfo の結果の最後から2行目が Available checker: textlint にならないです。
Available checker: - になります。(他は iranoan さんと同じになりました)
```
すいません
いろいろ確認していて、間違えて *.txt を開いた時の結果を書いてしまいました

main.tex を開いた時の結果は次のとおりです
`:put=execute('SyntasticInfo')`
```
Syntastic version: 3.9.0-44 (Vim 801, Linux, GUI)
Info for filetype: tex
Global mode: active
Filetype tex is active
The current file will be checked automatically
Available checkers: chktex lacheck
Currently enabled checkers: lacheck chktex
```

lacheck chktex のどちらも、TeXLive に含まれているツールのようで、出力の結果からも、実際に使われているのは lacheck ですね
TeX の環境もないと再現テストが出来ないですよね…

直接 lacheck を使うと次の様になるので、ログ
`:cd ~/downloads/sample/ | r!lacheck ~/downloads/sample/main.tex`
```
** not_exist.tex:
"/home/xxx/downloads/sample/main.tex", line 2: Could not open "not_exist.tex"
** a.tex:
** b.tex:
"b.tex", line 1: Whitespace before punctation mark in " !"
** b.tex:
"b.tex", line 1: Whitespace before punctation mark in " !"
```
をプラグイン使わない様に vimrc を errorformat を含めて書き換えた上で、
`:lgetfile hoge.log`
で読み込んで再現できれば良いのですが、再現しないんですよね

**Comment by ichizok** [comment]
最新 (8.1.2072) では再現せず、8.1.0320, 8.1.0488 で再現確認しました。
8.1.0489 で修正されていると思われます。

**Comment by iranoan** [comment]
> 最新 (8.1.2072) では再現せず、8.1.0320, 8.1.0488 で再現確認しました。
> 8.1.0489 で修正されていると思われます。

再現できてよかったです
Ubuntu にも最新が降りてくることを気長に待つことにします

どうもありがとうございました

**Comment by k-takata** [comment]
Ubuntuのリリースが更新されない限り、通常は新しいパッチは降ってきません。
なので、Ubuntuの次のリリースを待ちたくないのであれば、自分でビルドするか、最新のVimを提供しているPPAを使うなどする必要があります。
