### ISSUE TITLE
+kaoriyaパッチを棚卸ししたい

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#131]
とりあえず今日の時点のパッチは https://gist.github.com/1624100 にあげときました。

基本的にvim-devにだしても見込みがないものの寄せ集めですが、出せるけど時間がなくて忘れてしまったものもあります。今は1枚のdiffになってるけど、mqとかで整理しなおして機能毎に分けたいなぁ、とおもいつつ。

概要は@thinca さんがおおよそまとめてくれています。 http://d.hatena.ne.jp/thinca/20090619/1245338963 ちょっと古くなってるかもなので見る時は注意してください。

**Comment by koron** [comment]
私的メモ: Vim本体以外の+kaoriyaなレポジトリをあとでどこかのhgにアップする。ま、googlecodeでいいか。

方針: とりあえずdiffを機能毎に分割してvim-devに送れるものとそうでないものにわける必要がある。現時点の私には分ける気力(と時間)がないが、やってくれる人が分けるのに必要な質問に対して答えるのはできるはず。

**Comment by mattn** [comment]
githubがいいなぁ

↓ 以下、同文

**Comment by koron** [comment]
@mattn すでにhgで運用しvim本体もhgのため、というあたり。とりあえずは公開すること優先でgitじゃなくても良いんじゃない?gitにする、だと出すのが遅れる。

**Comment by mattn** [comment]
browsefilter のパッチはどれにあたるんだろ...

**Comment by koron** [comment]
@mattn たぶんこれ https://gist.github.com/1624170

**Comment by mattn** [comment]
このパッチ当たってない場合、どうやったら再現できますか？

**Comment by koron** [comment]
> このパッチ当たってない場合、どうやったら再現できますか？

@thinca これわかります?

**Comment by thinca** [comment]
``` vim
let b:browsefilter="Vimスクリプト\t*.vim"
browse e
```

とかでできるはず。今ちょっと手元に素のVimがないので未確認。

**Comment by mattn** [comment]
なるほど化けた。

**Comment by mattn** [comment]
@koron このパッチだけ分離して vim_dev に送って貰えますか。

**Comment by koron** [comment]
@mattn さんのほうでお願いできません?

**Comment by mattn** [comment]
「This patch is written by MURAOKA Taro」でおｋ？

**Comment by koron** [comment]
OKです。無くてもOKなんですが…それだとVim的にはまずいのか?

てか自分で書いたものかどうかもアヤシイのがアレなんですけど、
コードを見ると僕が書いたっぽいw

**Comment by mattn** [comment]
browsefilterの件は送った。

https://groups.google.com/d/topic/vim_dev/64YQ0ei5jB0/discussion

**Comment by koron** [comment]
@mattn Thanks! arigato!

**Comment by thinca** [comment]
7.3.406で入りましたね >browsefilter

**Comment by mattn** [comment]
閉じます。

https://groups.google.com/d/topic/vim_dev/RuL5KJTs0As/discussion

**Comment by koron** [comment]
…このissueって確か+kaoriya全体の話だよね?w

**Comment by mattn** [comment]
あー。そうですね。issue分ければよかった。

**Comment by mattn** [comment]
あとkaoriyaパッチでvim_devに還元しないといけない物ってありました？

**Comment by k-takata** [comment]
20120926版kaoriyaパッチを、25個に解体しました。
何をやっているのかよく分かっていない部分もありますが。

https://gist.github.com/3803353

**Comment by k-takata** [comment]
25個のパッチは以下のようになっています。「？」がついているのはよく理解していません。

0001 .hgignore にファイル追加
0002 .hgtags
0003 tutor.ja 間違い修正
0004 ja.po 修正
0005 mch_print_text_out() の改善？
0006 vim.ico の代わりに vim2.ico を使用（vim2.ico 自体は含まれていない）
0007 uim-fep 対応
0008 C/Migemo 対応
0009 'ambiwidth' オプションの auto 対応
0010 Win32 でキャプション非表示に対応
0011 ランタイムディレクトリをレジストリから取得？（何の目的？）
0012 モードラインの処理を改善し、ff, enc, bin の指定に対応
0013 日本語の自動判別 (guess_encode) 対応
0014 Win32 でウィンドウの半透明表示に対応
0015 字間 'charspace' オプション新設
0016 2html.vim で ftp: もリンクするように
0017 java.vim で日本語の句読点に対応
0018 Win32 でオブジェクトの出力ディレクトリを変更
0019 Win32 で po の Makefile に install-all ターゲットを追加？
0020 Win32 で manifest ファイルに関する処理を追加？
0021 in_history() に処理を追加？（何をやっている？）
0022 Win32 で WinSock の初期化処理を追加（何の目的？）
0023 vim_strchr() の最適化？
0024 検索処理の調整？（何をやっている？）
0025 +kaoriya

**Comment by k-takata** [comment]
0003 の tutor.ja については、他にも誤字脱字、改行位置を修正したい点がありました。

``` diff
diff --git a/runtime/tutor/tutor.ja.sjis b/runtime/tutor/tutor.ja.sjis
--- a/runtime/tutor/tutor.ja.sjis
+++ b/runtime/tutor/tutor.ja.sjis
@@ -117,7 +117,7 @@
             レッスン 1.5: テキスト編集 - 追加


-        ** テキスト追加するには A を押しましょう **
+        ** テキストを追加するには A を押しましょう **

   1. 以下の ---> と示された最初の行にカーソルを移動しましょう。
      カーソルがその文字上にあってもかまいません。
@@ -232,7 +232,7 @@
             レッスン 2.3: オペレータとモーション


-  多くのコマンドはオペレータとモーションからテキストに変更を加ます。
+  多くのコマンドはオペレータとモーションからテキストに変更を加えます。
   削除コマンド d のオペレータは次の様になっています:

    d   モーション
@@ -259,7 +259,7 @@

   1. 以下の ---> と示された行の先頭にカーソルを移動します。

-  2. 2dw をタイプして単語2つ分移動します。
+  2. 2dw をタイプして単語2つ分削除します。

   3. 3e をタイプして3つ目の単語の終端に移動します。

@@ -326,8 +326,8 @@

   ** 最後のコマンドを取り消すには u を押します。U は行全体の取消です。 **

-  1. 以下の ---> と示された行にカーソルを移動し、最初の間違いにカーソ
-     ルを移動しましょう。
+  1. 以下の ---> と示された行にカーソルを移動し、最初の間違いにカーソル
+     を移動しましょう。
   2. x をタイプしていらない先頭の文字を削除しましょう。
   3. さぁ、u をタイプして最後に実行したコマンドを取り消しましょう。
   4. 今度は、x を使用して誤りを全て修正しましょう。
```

**Comment by k-takata** [comment]
tutor.jaの修正はvim_devに投げました。
https://groups.google.com/d/topic/vim_dev/v8VQ4PAFZjc/discussion

**Comment by k-takata** [comment]
#新しいIssueにするほどではないと思うのでとりあえずここで。

kaoriya版で `:Tutorial` コマンドを使うと、enc=cp932以外の場合は、tutor.ja.eucを読み込むようになっていますが、enc=utf-8の場合はtutor.ja.utf-8を読み込むようにした方が良くないでしょうか。

``` diff
--- plugins/kaoriya/plugin/cmdex.vim.org        2012-08-19 09:50:11.000000000 +0900
+++ plugins/kaoriya/plugin/cmdex.vim    2012-11-24 13:43:18.156007500 +0900
@@ -57,7 +57,8 @@
   endif
   " Japan special
   if $LANG =~ '^ja'
-    let tutor = tutor . '.'. (&encoding ==# 'cp932' ? 'sjis' : 'euc')
+    let tutor = tutor . '.'. (&encoding ==# 'cp932' ? 'sjis' :
+      \ (&encoding ==# 'utf-8' ? 'utf-8' : 'euc'))
   endif
   execute "edit! $VIMRUNTIME/tutor/" . tutor
   execute "file TUTORCOPY"
```

**Comment by koron** [comment]
@k-takata : thanks! その修正反映します。ってかそれはissue起こしたほうが良かったかもw

**Comment by koron** [comment]
とりあえず自宅サーバのhgに入ってたソースを https://bitbucket.org/koron/vim-kaoriya に移しました。
ちなみにコレは https://bitbucket.org/koron/vim-kaoriya-vim コッチを参照する形で、
コッチのほうがvimオフィシャルからのブランチになっています。

とりあえずローカルで使ってたそのまんまなんで
オカシイところとかセキュリティ的な問題があったら教えてください。

**Comment by koron** [comment]
…ところでそろそろ k-takata さんにアイコンを設定して欲しいw

**Comment by deton** [comment]
> 0024 検索処理の調整？（何をやっている？）

は、@thincaさんの記事の、

> sentence (:help sentence) の定義として "、" や "。" も使うようになる。

ですね。
sentenceの終わりとして、マルチバイト文字の場合はmb_get_class()の戻り値が1 (punctuation)の文字も考慮するパッチです。

(少し使ってみたところ、)(キーでの移動が快適なので、同様の処理を行うVimスクリプトを作ってみました。)
https://github.com/deton/jasentence.vim

**Comment by koron** [comment]
```
hg qqueue
```

を知って、俄然やる気がでてきた。
https://bitbucket.org/koron/vim-kaoriya-patches
分解してここに移すつもり。

**Comment by koron** [comment]
メモ
-   0000番台 - ビルドとか基本的なところ
-   2000番台 - `src/*.c` をいじるfix
-   4000番台 - `src/*.c` をいじる機能追加
-   8000番台 - それ以外のfix及び機能追加

**Comment by koron** [comment]
0021 はどうも送って取り込まれたパッチの残骸らしい。

検索の履歴を探すときに検索方向を考慮に入れてなかったので入れるようにしたもの。

**Comment by koron** [comment]
0011 はすっごい古い過去の、取り回し目的のコード。
そもそもGvimExt自体を配ってないのでもう要らない。

**Comment by koron** [comment]
0005 は印刷を速くする目的で、透明な文字のTextOutをスキップするもの。
最近はプリンタドライバが頭良いはずなので要らないかもだけど、一応残そう。

**Comment by Shougo** [comment]
> hg qqueue
> を知って、俄然やる気がでてきた。
> https://bitbucket.org/koron/vim-kaoriya-patches
> 分解してここに移すつもり。

!

これは期待

**Comment by koron** [comment]
> 0022 Win32 で WinSock の初期化処理を追加（何の目的？）

記憶では if_ruby がコレを要求しおった。

**Comment by koron** [comment]
> 0023 vim_strchr() の最適化？

メンテナンスビリティ改善目的のリファクタリング。
当時、実はスピードもちょびっとだけ速くなった。

**Comment by koron** [comment]
> 0019 Win32 で po の Makefile に install-all ターゲットを追加？

KaoriYa版のパッケージビルドシステムで使うため。
まぁ「installはあるのにinstall-allが無いのは変」と強弁して本家に提案することもできるか?

**Comment by koron** [comment]
番号付けの方針変更

```
0000番台 - ビルドとか基本的なところ
2000番台 - src/下をいじるはなし
4000番台 - それ以外のfix及び機能追加
5000番以降 - 実験パッチや送ったものを入れる予定
```

**Comment by koron** [comment]
https://bitbucket.org/koron/vim-kaoriya-patches にて [01cd3932](https://bitbucket.org/koron/vim-kaoriya-patches/commits/01cd3932ddc0808d947eb76514b7e6475d34fb5d) までで棚卸完了。

**Comment by koron** [comment]
長かったissueがやっと終わった。

**Comment by koron** [comment]
各パッチがどうなったかは、こんな感じ

---

### Migrated

0005 mch_print_text_out() の改善？
0006 vim.ico の代わりに vim2.ico を使用（vim2.ico 自体は含まれていない）
0007 uim-fep 対応
0008 C/Migemo 対応
0009 'ambiwidth' オプションの auto 対応
0010 Win32 でキャプション非表示に対応
0012 モードラインの処理を改善し、ff, enc, bin の指定に対応
0013 日本語の自動判別 (guess_encode) 対応
0014 Win32 でウィンドウの半透明表示に対応
0015 字間 'charspace' オプション新設
0016 2html.vim で ftp: もリンクするように
0017 java.vim で日本語の句読点に対応
0019 Win32 で po の Makefile に install-all ターゲットを追加？
0020 Win32 で manifest ファイルに関する処理を追加？
0022 Win32 で WinSock の初期化処理を追加（何の目的？）
0023 vim_strchr() の最適化？
0024 検索処理の調整？（何をやっている？）
0025 +kaoriya

### Removed

0018 Win32 でオブジェクトの出力ディレクトリを変更
0011 ランタイムディレクトリをレジストリから取得？（何の目的？）
0021 in_history() に処理を追加？（何をやっている？）
0003 tutor.ja 間違い修正
0002 .hgtags
0004 ja.po 修正
0001 .hgignore にファイル追加
