### ISSUE TITLE
matchitの設定方法

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1311]
## 質問の内容
標準パッケージに含まれているmatchit.vimについて、b:match_wordsはどの様に指定すればよいのでしょうか?

発端は [matchit.vim の動作](https://groups.google.com/forum/?hl=ja&fromgroups#!topic/vim_jp/W-U4UwGnWf0) の投稿を自分でも確認しようと思ったことです
ここの投稿に有るように、HTML の箇条書き関係のタグは、% で開く/閉じるタグを行き来しません
どうやら箇条書き関係のタグをサイクリックに行き来するように特別な処理がされているようです

そこでまず、確認のために次の様に指定しました
`:r!grep -Ev '^\s*"' ~/.vim/vimrc`
> scriptencoding utf-8
> filetype plugin indent on
> set viminfo+=n~/.vim/viminfo
> packadd! matchit
> let b:match_words = '<\(\w\+\)[^>]*>:</\1>,' . &l:matchpairs

`:put=execute('echo &runtimepath')`

> /home/xxx/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim81,/usr/share/vim/vim81/pack/dist/opt/matchit,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,/home/xxx/.vim/after

下記の動画は、次の様子を示しています

1. 適当なサンプルを開く
2. 箇条書き以外の <>, html, head, body の開く/閉じるのタグ間を % で行き来する
3. 箇条書きのタグでは \<dl>→\<dt>→\<dd>→\</dl>→\<dl> とサイクリックに移動する
4. `:let b:match_words = '<\(\w\+\)[^>]*>:</\1>,' . &l:matchpairs` を実行すると、\<dl>\</dl> 間で移動する期待する動きと成る

![matchit](https://user-images.githubusercontent.com/24851657/66369008-82023780-e9d5-11e9-8eb1-0248acc42fb8.gif)

疑問は、
`:let b:match_words = '<\(\w\+\)[^>]*>:</\1>,' . &l:matchpairs`
は vimrc にも書いているのに、開いてから実行するとなぜ動作が変わるのか?

また
> filetype plugin indent on

が無いと、端から \<dl>→\<dt>→\<dd>→\</dl>→\<dl> とサイクリックに移動せずに、\<dl>\<dl> 間で移動するが on のまま、これを活かしつつ、最終的にはファイルタイプ別の設定として \~/.vim/ftplugin/html.vim に記述したいがどうすればよいか?
## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 07 2019 11:42:36)
> 適用済パッチ: 1-320
> Modified by team+vim@tracker.debian.org
> Compiled by team+vim@tracker.debian.org
> Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 19.04
> Release:	19.04
> Codename:	disco
> $ uname -a
> Linux xxxxxx 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
## 使用している or 関係していそうなプラグイン
matchit.vim

**Comment by k-takata** [comment]
> `:let b:match_words = '<\(\w\+\)[^>]*>:</\1>,' . &l:matchpairs`
> は vimrc にも書いているのに、開いてから実行するとなぜ動作が変わるのか?

ファイルを開くときに `$VIMRUNTIME/ftplugin/html.vim` が読み込まれて、その中で `b:match_words` が設定されるからですね。ftplugin の動作を上書きしたい場合は `:help ftplugin-overrule` を見るとよいでしょう。

**Comment by iranoan** [comment]
お返事ありがとうございます
>ファイルを開くときに $VIMRUNTIME/ftplugin/html.vim が読み込まれて、その中で b:match_words が設定されるからですね。ftplugin の動作を上書きしたい場合は :help ftplugin-overrule を見るとよいでしょう。

ヘルプに従って、\~/.vim/after/ftplugin/html.vim に
> scriptencoding utf-8
> if exists('b:did_after_ftplugin_user')
>     finish
> endif
> let b:did_after_ftplugin_user = 1
> let b:match_words = '<\(\w\+\)[^>]*>:</\1>,' . &l:matchpairs

としたのですが、動きは変わりません???

試しに、
echo 'ok'
と入れて、読み込まれているか? の確認はしました

他には runtimepath には、\~/.vim/after が最後に有ることも確認しました

あとはどんなことを確認すればよいのでしょう?

**Comment by tsuyoshicho** [comment]
動きというか、afterありの時の `b:match_words` の値はどうなってますか?

**Comment by iranoan** [comment]
> 動きというか、afterありの時の b:match_words の値はどうなってますか?

`put=execute('echo b:match_words')`
を \~/.vim/after/ftplugin/html.vim の最後に追加して出力させてみると
> <\(\w\+\)[^>]*>:</\1>,(:),{:},[:],<:>

次にHTML ファイル・オープン完了後、同じコマンドを打ち込むと
> <:>,<\@<=[ou]l\>[^>]*\%(>\|$\):<\@<=li\>:<\@<=/[ou]l>,<\@<=dl\>[^>]*\%(>\|$\):<\@<=d[td]\>:<\@<=/dl>,<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>

なので、やはり書き換わっています

なにか普通ではない状況のようなので、vimrc等の設定ファイルの書換だけでなく、\~/.vim/の中身丸ごとを素の状態にして、どこがおかしいか試行錯誤で調べてみます

**Comment by k-takata** [comment]
`:scriptnames` で、どういう順序でファイルが読み込まれているか確認してはどうでしょうか。

**Comment by iranoan** [comment]
原因が特定できました
以前 *.html ファイルを開いた時に、filetype が html と認識されないことが有り、\~/.vim/filetype.vim に
> autocmd BufEnter,BufNewFile,BufRead *.htm,*.html setlocal filetype=html

といった記述をしていたことが原因で、これを無くしたら最低限の記述では再現しなくなりました

ただ普段 dein.vim でプラグイン管理をしており、BufEnter のイベント発生時を読み込み条件にしているものがあります
そこで、BufEnter イベントが有っても、b:match_words が書き換わらない方法が知りたいです
引き続きご教授頂ければ幸いです

まず確認したいのですが、
`:r!grep -Ev '^\s*"' ~/.vim/vimrc`
> scriptencoding utf-8
> filetype plugin indent on
> set viminfo+=n~/.vim/viminfo
> packadd! matchit
> augroup VIMRC
> 	autocmd!
> 	autocmd BufEnter *.html setlocal filetype=html | 2put=execute('echo b:match_words')
> augroup END

`:r!grep -Ev '^\s*"' ~/.vim/after/ftplugin/html.vim`
> scriptencoding utf-8
> if exists('b:did_after_ftplugin_user')
> 	finish
> endif
> let b:did_after_ftplugin_user = 1
>
> let b:match_words = '<\(\w\+\)[^>]*>:</\1>,' . &l:matchpairs
> 0put=execute('echo b:match_words')

`:put=execute('echo &runtimepath')`
> /home/xxx/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim81,/usr/share/vim/vim81/pack/dist/opt/matchit,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,/home/xxx/.vim/after

という設定で、次の動画のように新規の *.html ファイルを開くと確認できるのですが、
![matchit](https://user-images.githubusercontent.com/24851657/66483047-3b98ff80-eadf-11e9-9e50-d9184116bf5a.gif)

`setlocal filetype=html`
をすると、b:match_words が再設定されるのですが、これは正しい動作なのでしょうか?

**Comment by tsuyoshicho** [comment]
再設定でafterが実行されない理由がよくわかりませんが、そもそもとしてhtmlファイルを開いて、filetypeがhtmlにならない(あとで再設定が必要)というのが謎ですね...

(こちらで普通にやる分には、問題なく認識しますし)

当座とりあえずで対応するなら
autocmdでfiletype決定処理の後に設定
```vim
autocmd BufEnter *.html setlocal filetype=html  | let b:match_words = '<(\w+)[^>]*>:</\1>,' . &l:matchpairs | 2put=execute('echo b:match_words')
```
するという手がありそうです(確認はしてない)

---

そもそもとして `.vimrc` で `let b:match_words = '<(\w+)[^>]*>:</\1>,' . &l:matchpairs` だと効果が期待できなかったのがありますね(後で話題に首をつっこんだので気づいてなかったですが)

`b:` は「バッファローカル」な変数のことなので、 `.vimrc` の時点では、開きたいファイル(=バッファ)を書き換えることができませんし

それでもafterがうまく効いてないのがよくわからない... `b:did_after_ftplugin_user` はvimがファイルタイプ再設定で消してないのか? 

あ、他の実装例を見ると ` b:undo_ftplugin` に unlet処理を足してたりするので、それっぽいっですね。
なので、一度そのバッファでafterを実行していたら、再実行されない(b:did_after_ftplugin_userが残るから読めなくなる)のでしょうね

see
https://github.com/elpinal/config/blob/f1a772ad358fe15e9919476a24617f99af55566b/vim/personal/after/ftplugin/haskell.vim

**Comment by iranoan** [comment]
`:help undo_ftplugin`
あたりの対処が必要なんですね

\~/.vim/ftplugin/ のファイルにもにも必要なのかな
動作を見ていると、\~/.vim/after/ 以外にも \~/.vim/syntax/ にも必要っぽい

どちらにしても対処できそうです
どうもありがとうございました
