### ISSUE TITLE
.\caffe/export.hpp(7): fatal error C1083: Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory ninja: build stopped: subcommand failed. ERROR: Build failed

### ISSUE THREAD

**Issue by ashisham** [vim-jp/issues#1312]
[150/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\layers\window_data_layer.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\include\caffe/util/io.hpp(53): warning C4244: 'argument': conversion from 'uint64_t' to 'int', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(31): warning C4812: obsolete declaration style: please use 'caffe::WindowDataLayer<Dtype>::~WindowDataLayer' instead
..\src\caffe\layers\window_data_layer.cpp(31): warning C4812: obsolete declaration style: please use 'caffe::WindowDataLayer<float>::~WindowDataLayer' instead
..\src\caffe\layers\window_data_layer.cpp(31): note: while compiling class template member function 'caffe::WindowDataLayer<float>::~WindowDataLayer(void)'
..\src\caffe\layers\window_data_layer.cpp(477): note: see reference to function template instantiation 'caffe::WindowDataLayer<float>::~WindowDataLayer(void)' being compiled
..\src\caffe\layers\window_data_layer.cpp(472): note: see reference to class template instantiation 'caffe::WindowDataLayer<float>' being compiled
..\src\caffe\layers\window_data_layer.cpp(123): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(37): note: while compiling class template member function 'void caffe::WindowDataLayer<float>::DataLayerSetUp(const std::vector<caffe::Blob<Dtype> *,std::allocator<_Ty>> &,const std::vector<_Ty,std::allocator<_Ty>> &)'
        with
        [
            Dtype=float,
            _Ty=caffe::Blob<float> *
        ]
..\src\caffe\layers\window_data_layer.cpp(124): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(126): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(127): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(128): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(129): warning C4244: '=': conversion from 'int' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(133): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(285): warning C4244: 'argument': conversion from 'float' to 'unsigned __int64', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(228): note: while compiling class template member function 'void caffe::WindowDataLayer<float>::load_batch(caffe::Batch<Dtype> *)'
        with
        [
            Dtype=float
        ]
..\src\caffe\layers\window_data_layer.cpp(290): warning C4244: 'argument': conversion from 'float' to 'unsigned __int64', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(304): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(305): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(306): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(307): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(319): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(320): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
..\src\caffe\layers\window_data_layer.cpp(31): warning C4812: obsolete declaration style: please use 'caffe::WindowDataLayer<double>::~WindowDataLayer' instead
..\src\caffe\layers\window_data_layer.cpp(31): note: while compiling class template member function 'caffe::WindowDataLayer<double>::~WindowDataLayer(void)'
..\src\caffe\layers\window_data_layer.cpp(477): note: see reference to function template instantiation 'caffe::WindowDataLayer<double>::~WindowDataLayer(void)' being compiled
..\src\caffe\layers\window_data_layer.cpp(472): note: see reference to class template instantiation 'caffe::WindowDataLayer<double>' being compiled
..\include\caffe/blob.hpp(74): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\include\caffe/blob.hpp(74): note: while compiling class template member function 'int caffe::Blob<Dtype>::num_axes(void) const'
        with
        [
            Dtype=double
        ]
..\include\caffe/blob.hpp(140): note: see reference to function template instantiation 'int caffe::Blob<Dtype>::num_axes(void) const' being compiled
        with
        [
            Dtype=double
        ]
..\include\caffe/layers/base_data_layer.hpp(77): note: see reference to class template instantiation 'caffe::Blob<Dtype>' being compiled
        with
        [
            Dtype=double
        ]
..\include\caffe/layers/window_data_layer.hpp(25): note: see reference to class template instantiation 'caffe::BasePrefetchingDataLayer<Dtype>' being compiled
        with
        [
            Dtype=double
        ]
[151/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\util\db_leveldb.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[152/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\solvers\adadelta_solver.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[153/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\solvers\adagrad_solver.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[154/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\util\hdf5.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\src\caffe\util\hdf5.cpp(192): warning C4244: 'return': conversion from 'hsize_t' to 'int', possible loss of data
..\include\caffe/blob.hpp(74): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\include\caffe/blob.hpp(74): note: while compiling class template member function 'int caffe::Blob<double>::num_axes(void) const'
..\src\caffe\util\hdf5.cpp(131): note: see reference to function template instantiation 'int caffe::Blob<double>::num_axes(void) const' being compiled
..\src\caffe\util\hdf5.cpp(100): note: see reference to class template instantiation 'caffe::Blob<double>' being compiled
..\src\caffe\util\hdf5.cpp(62): warning C4244: '=': conversion from 'unsigned __int64' to 'int', possible loss of data
..\src\caffe\util\hdf5.cpp(90): note: see reference to function template instantiation 'void caffe::hdf5_load_nd_dataset_helper<float>(hid_t,const char *,int,int,caffe::Blob<float> *,bool)' being compiled
[155/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\util\im2col.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[156/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\util\db_lmdb.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[157/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\syncedmem.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[158/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\solvers\rmsprop_solver.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[159/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\solvers\nesterov_solver.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[160/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\solvers\adam_solver.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[161/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\solvers\sgd_solver.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\include\caffe/util/io.hpp(53): warning C4244: 'argument': conversion from 'uint64_t' to 'int', possible loss of data
[162/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\util\benchmark.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
..\src\caffe\util\benchmark.cpp(77): warning C4244: '=': conversion from '__int64' to 'float', possible loss of data
..\src\caffe\util\benchmark.cpp(99): warning C4244: '=': conversion from '__int64' to 'float', possible loss of data
..\src\caffe\util\benchmark.cpp(105): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
..\src\caffe\util\benchmark.cpp(152): warning C4244: '=': conversion from '__int64' to 'float', possible loss of data
..\src\caffe\util\benchmark.cpp(165): warning C4244: '=': conversion from '__int64' to 'float', possible loss of data
[163/215] Building CXX object tools\CMakeFiles\device_query.dir\device_query.cpp.obj
FAILED: tools/CMakeFiles/device_query.dir/device_query.cpp.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DCAFFE_VERSION=1.0.0 -DCMAKE_WINDOWS_BUILD -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL=__declspec(dllimport) -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport) -DH5_BUILT_AS_DYNAMIC_LIB=1 -DUSE_CUDNN -DUSE_LEVELDB -DUSE_LMDB -DUSE_OPENCV -Iinclude -I. -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\boost-1_61 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I..\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\opencv -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\Include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /FS /MD /O2 /Ob2 /DNDEBUG /FS /showIncludes /Fotools\CMakeFiles\device_query.dir\device_query.cpp.obj /Fdtools\CMakeFiles\device_query.dir\ /FS -c ..\tools\device_query.cpp
.\caffe/export.hpp(7): fatal error C1083: Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory
[164/215] Building CXX object tools\CMakeFiles\upgrade_solver_proto_text.dir\upgrade_solver_proto_text.cpp.obj
FAILED: tools/CMakeFiles/upgrade_solver_proto_text.dir/upgrade_solver_proto_text.cpp.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DCAFFE_VERSION=1.0.0 -DCMAKE_WINDOWS_BUILD -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL=__declspec(dllimport) -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport) -DH5_BUILT_AS_DYNAMIC_LIB=1 -DUSE_CUDNN -DUSE_LEVELDB -DUSE_LMDB -DUSE_OPENCV -Iinclude -I. -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\boost-1_61 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I..\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\opencv -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\Include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /FS /MD /O2 /Ob2 /DNDEBUG /FS /showIncludes /Fotools\CMakeFiles\upgrade_solver_proto_text.dir\upgrade_solver_proto_text.cpp.obj /Fdtools\CMakeFiles\upgrade_solver_proto_text.dir\ /FS -c ..\tools\upgrade_solver_proto_text.cpp
.\caffe/export.hpp(7): fatal error C1083: Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory
[165/215] Building CXX object tools\CMakeFiles\upgrade_net_proto_binary.dir\upgrade_net_proto_binary.cpp.obj
FAILED: tools/CMakeFiles/upgrade_net_proto_binary.dir/upgrade_net_proto_binary.cpp.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DCAFFE_VERSION=1.0.0 -DCMAKE_WINDOWS_BUILD -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL=__declspec(dllimport) -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport) -DH5_BUILT_AS_DYNAMIC_LIB=1 -DUSE_CUDNN -DUSE_LEVELDB -DUSE_LMDB -DUSE_OPENCV -Iinclude -I. -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\boost-1_61 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I..\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\opencv -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\Include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /FS /MD /O2 /Ob2 /DNDEBUG /FS /showIncludes /Fotools\CMakeFiles\upgrade_net_proto_binary.dir\upgrade_net_proto_binary.cpp.obj /Fdtools\CMakeFiles\upgrade_net_proto_binary.dir\ /FS -c ..\tools\upgrade_net_proto_binary.cpp
.\caffe/export.hpp(7): fatal error C1083: Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory
[166/215] Building CXX object tools\CMakeFiles\compute_image_mean.dir\compute_image_mean.cpp.obj
FAILED: tools/CMakeFiles/compute_image_mean.dir/compute_image_mean.cpp.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DCAFFE_VERSION=1.0.0 -DCMAKE_WINDOWS_BUILD -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL=__declspec(dllimport) -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport) -DH5_BUILT_AS_DYNAMIC_LIB=1 -DUSE_CUDNN -DUSE_LEVELDB -DUSE_LMDB -DUSE_OPENCV -Iinclude -I. -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\boost-1_61 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I..\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\opencv -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\Include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /FS /MD /O2 /Ob2 /DNDEBUG /FS /showIncludes /Fotools\CMakeFiles\compute_image_mean.dir\compute_image_mean.cpp.obj /Fdtools\CMakeFiles\compute_image_mean.dir\ /FS -c ..\tools\compute_image_mean.cpp
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
.\caffe/export.hpp(7): fatal error C1083: Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory
[167/215] Building CXX object src\caffe\CMakeFiles\caffe.dir\util\blocking_queue.cpp.obj
C:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\google/protobuf/message_lite.h(247): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[168/215] Building CXX object tools\CMakeFiles\caffe.bin.dir\caffe.cpp.obj
FAILED: tools/CMakeFiles/caffe.bin.dir/caffe.cpp.obj
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DCAFFE_VERSION=1.0.0 -DCMAKE_WINDOWS_BUILD -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL=__declspec(dllimport) -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport) -DH5_BUILT_AS_DYNAMIC_LIB=1 -DUSE_CUDNN -DUSE_LEVELDB -DUSE_LMDB -DUSE_OPENCV -Iinclude -I. -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\boost-1_61 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I..\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\include\opencv -IC:\Users\user\.caffe\dependencies\libraries_v140_x64_py35_1.1.0\libraries\Include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /FS /MD /O2 /Ob2 /DNDEBUG /FS /showIncludes /Fotools\CMakeFiles\caffe.bin.dir\caffe.cpp.obj /Fdtools\CMakeFiles\caffe.bin.dir\ /FS -c ..\tools\caffe.cpp
.\caffe/export.hpp(7): fatal error C1083: Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory
ninja: build stopped: subcommand failed.
ERROR: Build failed

**Comment by mattn** [comment]
Please use issue template.

**Comment by ashisham** [comment]
I am a starter and don't know how to use it! 
Thanks.

**Comment by mattn** [comment]
This repository is vim users group which is not related on your issue. Please find out the official issue tracker or mailing list what you are having issues.
