### ISSUE TITLE
[gvim/Windows] gvim が :tabnew した際に起動時の位置へ移動してしまう

### ISSUE THREAD

**Issue by akif999** [vim-jp/issues#1314]
## gvim が :tabnew した際に起動時の位置へウィンドウが移動してしまう

タイトルの通りです。  
Issue の起票日 (2019/11/16) 時点の最新 ver で発生しました。  
また、:tabnew した tab を閉じた際にも同様の現象が発生します。  

(少し前の ver から発生しているという話を聞いた記憶があるので、重複でしたらすみません。  
vim-jp 内では見当たりませんでした)

### 現象・ログ

![vim_tabnew](https://user-images.githubusercontent.com/21696871/68990203-c534ad80-0893-11ea-9f54-86aacbece9c5.gif)

### 再現手順

以下の手順で再現します。

1. gvim を起動する
2. 起動された場所からウィンドウの位置を変更する
3.  `:tabnew` を実行する

また、tab を閉じる際は以下の手順で再現します。

* 複数の tab がある状態で `:q` で tab を閉じる。

### 期待動作

Window の位置が変更されない。

## Vimのバージョン

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 15 2019 23:02:52)
MS-Windows 64 ビット コンソール 版
適用済パッチ: 1-2301
Compiled by appveyor@APPVYR-WIN
```

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit (ver 1809, build 17763.864)

## 使用している or 関係していそうなプラグイン

プラグインを適用しない状態でも発生したため、ありません。

## その他

ありません。

**Comment by k-takata** [comment]
`:set guioptions+=k` と設定してみてください。

#1078 と同件ですね。

**Comment by akif999** [comment]
@k-takata 

ご回答いただきありがとうございます。
すでに対応済みの課題だったんですね。

> :set guioptions+=k と設定してみてください。

この設定で解決しました。

**Comment by akif999** [comment]
対策方法の確認ができたので閉じます。
