### ISSUE TITLE
tempname() が Windowsで利用できないことがある一時ファイルのパスを返す

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/issues#1316]
## 不具合の内容

Windows上でtempname()を呼ぶと

```vim
echo tempname()
```

```console
C:\Users\tsuyoshi\AppData\Local\Temp\VIH32CF.tmp
```

のような、 `~\AppData\Local\Temp` へのパスを返します。

ここで以下が参考になりますが、

* [AppDataフォルダ直下のLocal／LocalLow／Roamingサブフォルダの違いについて。 \- 量産メモ帳](http://rms-099.hatenablog.jp/entry/20130120/1359218895)
* [Link > 2015\-10\-05 winAppDev > AppData 以下のフォルダ > Local / LocalRow / Roaming \- Qiita](https://qiita.com/7of9/items/0fbec6205a31e5c8ddfd)
  > Local : ユーザから独立 / 危険度が低いもの
  > LocalRow : ユーザから独立 / 危険度が高いもの
  > Roaming : コンピュータから独立 / ユーザに付随

作法としては間違っていないし、普通だと作れるのですが...
確実を取るためにユーザーアプリケーションであるVimが作る一時ファイルは `Roaming` に作るのはどうでしょうか?

とはいえ、このパスで一時ファイルが作れないほうがまずい、というのはあるかもしれません...

### 現象・ログ

この現象に気付いたものとして [vital.vim](https://github.com/vim-jp/vital.vim) を GitHub Actionsで回してみようとした結果のログから、(テスト、コードに変化がないにもかかわらず)大量のテストNGが出たためです。

[ci: Windows re\-enable test · tsuyoshicho/vital\.vim@dec954b](https://github.com/tsuyoshicho/vital.vim/commit/dec954b1e6d7b92c8bb71bc7e4686fb03e08e801/checks?check_suite_id=319645584#step:4:86)

```log
2019-11-20T05:49:38.4347072Z Failures:
2019-11-20T05:49:38.4347236Z 
2019-11-20T05:49:38.4347439Z   1) Vim.Buffer read_content() wipes out tempfile buffer
2019-11-20T05:49:38.4347579Z 
2019-11-20T05:49:38.4347792Z      function 1361() abort dict  Line:2  (~/AppData/Local/Temp/VI68E8A.tmp)
2019-11-20T05:49:38.4347964Z 
2019-11-20T05:49:38.4348188Z      function <SNR>149_read_content(content, ...) abort  Line:33  (d:/a/vital.vim/vital.vim/autoload/vital/__vital__/Vim/Buffer.vim)
2019-11-20T05:49:38.4348344Z 
2019-11-20T05:49:38.4348542Z      
2019-11-20T05:49:38.4348697Z 
2019-11-20T05:49:38.4348889Z      Vim(bwipeout):E94: No matching buffer for C:\Users\RUNNER~1\AppData\Local\Temp\VIBF7B1.tmp
...
```

### 再現手順

GitHub ActionsのWindowsイメージでtempname()を利用するような関数テストを行なう

### 期待動作

上記テストが正常にパスすること
それが、環境差に依存しないこと

そのために、tempname()は確実に利用可能な一時ファイルのパスを返すこと

## Vimのバージョン

Vim 8.0.0596 +kaoriya (2017/05/02)
(vim80/latestなので、たぶん)

## OSの種類/ディストリ/バージョン

* [Windows Server 2019](https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019)

## 使用している or 関係していそうなプラグイン

なし
(テストはvim-themis)

## その他

開発者が普通にVimを使うと、装置の管理者相当なので、たまには制限されたユーザーなども確認しないと不味いことがあるかもしれない...
テストマシンも、ソフトのためかつコンテナなので、案外緩いことはあるかも

**Comment by k-takata** [comment]
コマンドプロンプトから `echo %TMP%` や `echo %TEMP%` を実行して環境変数の値を確認すると `~\AppData\Local\Temp` を指していることが分かります。一時ファイルはマシン間で共有するようなものではないですから、Roaming ではなく Local になるのは普通でしょう。
Vim の `tempname()` は、[GetTempPathW()](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw) 経由で `%TMP%` や `%TEMP%` の値を利用しているだけなので、それらの環境変数が書き込みできないディレクトリを指していると、当然変なことになります。

`%TMP%` の先が書き込みできない場合には、書き込み可能なところに値を変更すればよいと思います。（Vim の中から対処するなら `:let $TMP = '...'`）

**Comment by tsuyoshicho** [comment]
まあ、そちらのほうが正道ですね

書き込みできるかなど確認がんばってみます。
