### ISSUE TITLE
Vimの正規表現のバグ？

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#132]
自分の勘違いかもしれませんが、同じと思われる正規表現のパターンの結果がVimとPerlで違います。
https://gist.github.com/1629848

Perl

```
#!perl
use common::sense;
my $RX = /\A([:alpha:](?:[[:alpha:][:digit:]+.-])*)\Z/;
#1
say 'ftp' =~ $RX;
```

Vim

```
let s:RX_SCHEME = '^\([:alpha:]\%([[:alpha:][:digit:]+.-]\)*\)$'
" 0
echom 'ftp' =~# s:RX_SCHEME
```

**Comment by tyru** [comment]
`set magic?`はonです。(当たり前かもしれませんが...

**Comment by thinca** [comment]
最初の`[:alpha:]`は文字クラスなので`[[:alpha:]]`とする必要があります。

**Comment by koron** [comment]
まだ試してないのですけど `[:{keyword}:]` の解釈の仕様が違うんじゃないですかね?

Vimは `[]` の中でしか機能しない、みたいな。

**Comment by mattn** [comment]
その正規表現、等価じゃないですね。

`[:alpha:]`は文字クラスなので`[]`の中で使われるべきです。`([:alpha:])`は`[]`内で使われていないので`:alpha:`という文字のどれかがマッチし得る単なるグループに相当します。なので

``` vim
:echom 'atp' =~# s:RX_SCHEME
```

ならば1が出るはず。ちなみにちゃんと書くならば

``` vim

let s:RX_SCHEME = '^\([[:alpha:]]\%([[:alpha:][:digit:]+.-]\)*\)$'
" 0
echom 'ftp' =~# s:RX_SCHEME
```

と書くべきです。

**Comment by koron** [comment]
なんでPerlはOKとしてんだろう?昔は違った(使えなかった)と記憶してるんだけど…その理由次第ではVimに移植しても良いんじゃない?

**Comment by tyru** [comment]
@thinca @koron @mattn おおお！無事機能しました！勘違いしてたみたいです。ありがとうございます。

**Comment by matsuu** [comment]
``` perl
my $RX = /\A([:alpha:](?:[[:alpha:][:digit:]+.-])*)\Z/;
```

が間違ってますね。

``` perl
my $RX = qr/\A([:alpha:](?:[[:alpha:][:digit:]+.-])*)\Z/;
```

としないとダメだと思います。前者だと$RXは空になります。
なので、意図した動作にするためには、こんな感じでしょうか。

``` perl
my $RX = qr/\A([[:alpha:]][[:alpha:][:digit:]+.-]*)\Z/;
```

**Comment by tyru** [comment]
@matsuu あーそうか！`my $RX = /.../`は`my $RX = ($_ =~ /.../)`と同じですね。どうもです。
やっぱりPerlでも`[:alpha:]`は`[[:alpha:]]`としなきゃダメのようですね。
