### ISSUE TITLE
:verbose pwd でディレクトリのスコープ (:lcd, :tcd, :cd) を表示してほしい

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1320]
## 内容

Vim 8.1.1218 で `:tcd` が追加されたため、１つのタブページ内で `:lcd` と `:tcd` 両方使っていると
`:pwd` で表示されるディレクトリがどちらで設定された値かわからなくなってしまいます。
`:pwd` の表示を以下のようにすれば分かりやすくなるのではないでしょうか。

2行にするか、1行にするかで迷ったのですが、個人的には `:verbose pwd` を何らかのマッピングに割り当てたいので hit-enter prompt が出ない1行としたいです。
その他右端に表示した方が良い？などもありますが、これは正直最終的には Bram と相談（Bram の好み）になるかと思います。

#### :tcd

```
:verbose pwd
[set by :tcd] /hoge/fuga/foo/bar
```

#### :lcd

```
:verbose pwd
[set by :lcd] /hoge/fuga/foo/bar
```

#### :cd

```
:verbose pwd
[global] /hoge/fuga/foo/bar
```

### Pros 良くなる点

同上

### Cons 悪くなる点

現状は `:pwd` に `:verbose` を付けても意味がないので大丈夫だと思います。

## Vimのバージョン

8.1.2384

**Comment by mattn** [comment]
Bram だと lpwd とか tpwd とか作ってしまいそう (感想です)

**Comment by k-takata** [comment]
`haslocaldir()` を使えば、cd, lcd, tcd のどれで設定されたか分かりますが、neovimとも判別方法が違ったりして面倒ですね。
vim/vim で誰かが書いてて、minpacでも使っている判別方法:

```vim
    if has('nvim')
      let l:cdcmd = haslocaldir() ? 'lcd' : (haslocaldir(-1, 0) ? 'tcd' : 'cd')
    else
      let l:cdcmd = haslocaldir() ? ((haslocaldir() == 1) ? 'lcd' : 'tcd') : 'cd'
    endif
```

**Comment by h-east** [comment]
オフトピックすまそ。Vimの方これで高速化:+1:？
```vim
let l:cdcmd = ['cd', 'lcd', 'tcd'][haslocaldir()]
```

**Comment by tyru** [comment]
ありがとうございます。
Vim script でもどうにかなるっていえばなるんですよね。
ただ :tcd は比較的最近入ったし、:verbose pwd は使われてないみたいだったのでこういう要求もアリなのかもと。
年末の忙しさであちこちに興味・注意が発散してますが、余裕あればパッチ書いてみますね。

**Comment by tyru** [comment]
送りました。 https://github.com/vim/vim/pull/5469

**Comment by mattn** [comment]
> That can be useful.

入る機運

**Comment by rbtnn** [comment]
入った。
https://github.com/vim/vim/commit/950587242cad52d067a15f0f0c83528a28f75731

**Comment by k-takata** [comment]
閉じます。
