### ISSUE TITLE
GVim 8.2.0029にてGUI系オプションが使用できない

### ISSUE THREAD

**Issue by beckorz** [vim-jp/issues#1323]
## 不具合の内容

Windows向けKaoriyaさんビルドの GVim 8.2.0029にてGUI系オプションが使用できない

(koronさん側の[Issue](https://github.com/koron/vim-kaoriya/issues/27)にも立てちゃいましたが、こちらが適切なのかと思い、Issue立てました。(不適切なら削除します))

### 現象・ログ

```
E25: GUIは使用不可能です: コンパイル時に無効にされています
```

のエラーが出てGUIオプションを使用できませんでした。
transparency, guifont等のGUI系のオプション等が使用できない状態になります。なお、以前8.1系までのバージョンでは使用可能でした。

### 期待動作

GUI系オプションが使える事

## Vimのバージョン

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 22 2019 20:42:15)
MS-Windows 64 ビット GUI/コンソール 版
適用済パッチ: 1-29
```

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.18363.535)

**Comment by h-east** [comment]
Officialの 8.2.0045 では問題は起きませんでした。
8.2.0029～8.2.0045までの間にそれ系のバグフィックスはないので、おそらくKaoriya版の問題だと思います。

> (不適切なら削除します)

削除する必要はないです。Issue登録ありがとうございます。

**Comment by koron** [comment]
@beckorz 

報告ありがとうございます `transparency` は +kaoriya 固有だと思いますが
`guifont` はちょっと理由が定かではないですね(一応これかもな、という推測はできますが)

確認なんですがそれらの設定はどこに書いていますか?
 .vimrc ならばそれを .gvimrc (もしくは vimfiles/gvimrc) に移してみてください。
私の手元では `guifont` は gvimrc に書いて動いてます。

@h-east 

おそらく VIMDLL が原因かと思われます。
設定時に `gui.running` をチェックする系のオプションは
VIMDLL 有効化の影響を受けるかもしれません。

**Comment by k-takata** [comment]
自前ビルドでは VIMDLL を有効にしていますが、guifont, guioptions などは問題なく使えていますね。
（.vimrc, .gvimrc のどちらに書いても動くことを確認。）

**Comment by koron** [comment]
@beckorz 

> ```
> E25: GUIは使用不可能です: コンパイル時に無効にされています
> ```

このログは何をした際に観測されましたか?
もしも単に起動しただけであれば .vimrc 及び .gvimrc を見せていただけないでしょうか?

いま手元の 8.2.0029+kaoriya の gvim で試した限り
以下の挙動となり `E25` を確認できませんでした。

設定場所 | `guifont` | `transparency` 
---|---|---
vimfiles/vimrc で設定 | 機能しない(A1) | 機能しない (B1)
vimfiles/gvimrc で設定 | 機能する(A2) | 機能しない (B2)
起動後に cmdline で設定 | 機能する(A3) | 機能する (B3)

上記のケースで明らかにおかしいのは
B2 の transparecy が vimfiles/gvimrc では機能しない点だけで、
それについては https://github.com/koron/vim-kaoriya/issues/27 でやりましょう。
(B1 は vim 全体との整合性をとりたいので微妙)

A1 はまだよくわかりません。

何れにせよ E25 はでてないので、その部分の再現条件も確定させたいです。

**Comment by koron** [comment]
う。ふと思い出して vimfiles/vimrc に `:gui` を書きたしたら E25 出た…

@k-takata VIMDLL化時 `:gui` コマンドはどういう扱いになるんですかね…

**Comment by koron** [comment]
A1 のケース `:verbose set gfn?` で確認したら、$VIMRUNTIME/gvimrc が上書きしてました。
なので gvim 本体としては問題ないけど +kaoriya の設定が ~機能しない~ 悪さしてる 感じなので
https://github.com/koron/vim-kaoriya/issues/27 にてやりましょう。

残るは VIMDLL 化時に vimfiles/vimrc 内の `:gui` コマンドが E25 を出す件だけで
それだけはこちらで継続議論としてください。

**Comment by k-takata** [comment]
`:gui` コマンドは一旦は実装したのですが、Unixと同じ挙動にならないということでお蔵入りになりました。(実験的な機能として、#ifdef で無効化してある状態。)

vim.exe から実行したときに E25 が出るのは正しいですが、gvim.exe の .vimrc で実行したときの挙動は特に何も考えていませんでした。E25 は出ないようにした方がよいかもしれませんね。

**Comment by koron** [comment]
> E25 は出ないようにした方がよいかもしれませんね。

:+1: そうだと助かりそうです。

**Comment by k-takata** [comment]
こんな感じで、VIMDLL 有効の gvim.exe で .vimrc 読み込み時は `:gui` を無視でいいのかな？
VIMDLL 無効時と動作が違ってしまう気がするけど… （従来動作は、.vimrc 内に `:gui` があったら、その時点で GUI の起動を開始して、それが終わったら .vimrc の残りの処理を実施、なのかな？）

```diff
--- a/src/gui.c
+++ b/src/gui.c
@@ -5014,8 +5014,11 @@ ex_gui(exarg_T *eap)
     if (!gui.in_use)
     {
 #if defined(VIMDLL) && !defined(EXPERIMENTAL_GUI_CMD)
-	emsg(_(e_nogvim));
-	return;
+	if (!gui.starting)
+	{
+	    emsg(_(e_nogvim));
+	    return;
+	}
 #else
 	// Clear the command.  Needed for when forking+exiting, to avoid part
 	// of the argument ending up after the shell prompt.
```

.vimrc 内に `:gui` を書く意義が分からない…

**Comment by beckorz** [comment]
@koron san @k-takata san 素早いトラブルシュートありがとうございます。

全ては、koronさんの言う通りだと思います。複数の問題が絡んでいたようで申し訳ありません。
 (設定自体は、%userprofile%/dotfiles/～の gvimrcにGUIと、guifont、transparency等を設定しています。
  :GUIのE25エラーと、guifont系が全部設定が効いていない状態なので、
  E25のエラーメッセージのとおりgui～系全般オプションが全般的に使えない状態なのだと推測しておりましたが・・・

1. :gui に関して
  昔、設定していたのが、なぜそうしていたのか思い出せませんが、消して影響がなければ今後消そうかなと思います。
2. guifontの設定に関して
  +kaoriya
  $VIMRUNTIME/gvimrc を上書きされていると思うと納得しました。(起動後、`set gfn=～` で適用されました)
3. transparencyに関して
  +kaoriya版に関する物との事で理解しました。

お手数ですが、対応していただけると助かります。

※ これを機に、(g)vimrc全般設定に関して、もう一度一から作り直した方が良いように思ってきました。

**Comment by koron** [comment]
@k-takata

> .vimrc 内に :gui を書く意義が分からない…

過去に
「.vimrc に gvim 向けの設定をまとめたい場合には  `:gui` を書いてその後ろに書く」
的なことを2chあたりで書いた記憶がうっすらあります。
それがまわりまわってここにきて牙をむいたのかと。

gvim向けっていうのは特に menu とかそのあたりを考慮して。

**Comment by k-takata** [comment]
あ、こうすれば、従来と同じ動作になるか。

```diff
--- a/src/gui.c
+++ b/src/gui.c
@@ -5014,21 +5014,23 @@ ex_gui(exarg_T *eap)
     if (!gui.in_use)
     {
 #if defined(VIMDLL) && !defined(EXPERIMENTAL_GUI_CMD)
-	emsg(_(e_nogvim));
-	return;
-#else
+	if (!gui.starting)
+	{
+	    emsg(_(e_nogvim));
+	    return;
+	}
+#endif
 	// Clear the command.  Needed for when forking+exiting, to avoid part
 	// of the argument ending up after the shell prompt.
 	msg_clr_eos_force();
-# ifdef GUI_MAY_SPAWN
+#ifdef GUI_MAY_SPAWN
 	if (!ends_excmd(*eap->arg))
 	    gui_start(eap->arg);
 	else
-# endif
+#endif
 	    gui_start(NULL);
-# ifdef FEAT_JOB_CHANNEL
+#ifdef FEAT_JOB_CHANNEL
 	channel_gui_register_all();
-# endif
 #endif
     }
     if (!ends_excmd(*eap->arg))
```

**Comment by k-takata** [comment]
PRed: https://github.com/vim/vim/pull/5408

**Comment by k-takata** [comment]
`:gui` が使えない問題は [8.2.0055](https://github.com/vim/vim/commit/257a396879ff67a0482841a39237f30a8e1e27c5) で直りました。
