### ISSUE TITLE
win_execute(winid, 'close') で Segmentation fault

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#1324]
## 不具合の内容

別のタブページの Window ID を `win_execute(winid, 'close')` のように指定すると落ちる。
`:tabedit` の代わりに `:split`, `:new` では落ちませんでした。

### 再現手順

1. `vim --clean -N`
1. `:let winid = win_getid()`
1. `:tabedit`
1. `:call win_execute(winid, 'close')`
1. Segmentation fault

### 期待動作

落ちないのが正しいと思います。

## Vimのバージョン

8.2.2

## OSの種類/ディストリ/バージョン

*   macOS Catalina 10.15.2

**Comment by ichizok** [comment]
PRed.
https://github.com/vim/vim/pull/5512

**Comment by ichizok** [comment]
8.2.0137
https://github.com/vim/vim/commit/a44b3eeafa57d4904a3de86b132008b93404f0fd

**Comment by tyru** [comment]
あざます！
