### ISSUE TITLE
ジョブのコールバックで input() を使用した際、第２引数 {text} が表示されない

### ISSUE THREAD

**Issue by litom501** [vim-jp/issues#1326]
## 不具合の内容

ジョブのコールバックで input() を使用した際、第２引数 {text} に値を設定しても
初期値として表示されない。

### 再現手順
```
function! OutHandler(channel, message) abort
  call input('test (out) : ', 'ifoo')
endfunction

function! CloseHandler(channel) abort
  call input('test (close) : ', 'ifoo')
endfunction

function! ExitHandler(job, status) abort
  call input('test (exit): ', 'ifoo')
endfunction

" 期待動作
call input('test : ', 'ifoo')

let cmd = 'uname -a'
let job = job_start(cmd, {
      \ "out_cb": "OutHandler",
      \ "exit_cb": "ExitHandler",
      \ "close_cb": "CloseHandler"
      \})
```
## Vimのバージョン
8.2.114

## OSの種類/ディストリ/バージョン
Ubuntu 18.04.3(WSL)

## その他
第２引数のテキストに "ifoo" などを設定すると、"foo" がアクティブなウィンドウに入力されるため
テキストは、ウィンドウに送られている様子です。

**Comment by mityu** [comment]
https://github.com/vim/vim/blob/e770598f31ad88fc98e40ead4b228ebc04afaa5d/src/getchar.c#L3146-L3148
この行が実行されているタイミングでジョブのコールバックが呼ばれていて、そのため、`get_user_input()`内の`vgetorpeek()`の呼び出しが recursive になり、`stuffReadbuffSpec()`で詰めた {text} を引き出せずにいるのが原因の様です。

この先は時間が出来次第見てみます。

**Comment by mityu** [comment]
v8.2.0662 で直りました。

**Comment by litom501** [comment]
修正を確認しました。
パッチ作成、報告ありがとうございました。

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/dfc33a665d3b12689aa971575b8e7de4e5202d83
直ったとのことなので閉じます。
