### ISSUE TITLE
ビルドして作成したGVimのメッセージの日本語化がよくわからない

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1329]
## 質問の内容
下のページを参考に、ビルドしたGVimのメッセージを日本語にしたいのですが、よくわかりません。
https://sites.google.com/site/fudist/Home/vim-nihongo-ban/mingwvim

ページに
>作成した ja.moは vim.mo にリネームして $VIMRUNTIME/lang/ja/LC_MESSAGES へコピーします。

とあり、vim.moは作成できましたが、これ以降の作業がよくわかりません。

$VIMRUNTIME/ というのは、githubから落としてきた vim-kaoriya以下の \vim\runtime\のことであっていますか？
またそうであるとすると、$VIMRUNTIME/lang というフォルダは存在しますが、$VIMRUNTIME/lang/ja/LC_MESSAGES　はないので、自分で作るのでしょうか？
ただしそのフォルダを作って、そこにvim.moをおいても日本語になりませんでした。

初心者ですみません。どなたか方法をご存じでしたらご教授お願いします。

## Vimのバージョン
8.2.148

## OSの種類/ディストリ/バージョン
Windows 10 Home 64bit

**Comment by k-takata** [comment]
> $VIMRUNTIME/ というのは、githubから落としてきた vim-kaoriya以下の \vim\runtime\のことであっていますか？

$VIMRUNTIME はビルド時のディレクトリではなく、インストール後のディレクトリです。
Vim 上から `:echo $VIMRUNTIME` を実行すれば、現在の $VIMRUNTIME を確認できます。
KaoriYa Vimの場合は、`vim82-kaoriya-win64\vim82\` などです。
（ただし、インストールせずにビルド時のディレクトリから直接実行した場合は、vim\runtime\ になります。）

> ただしそのフォルダを作って、そこにvim.moをおいても日本語になりませんでした。

gettext と iconv の DLL はパスの通ったところに置いてありますか？
libintl-8.dll, libiconv-2.dll (32bit版は libgcc_s_sjlj-1.dll も) を入手してください。

**Comment by hiro-github** [comment]
返信ありがとうございます。

教えていただいた方法で、$VIMRUNTIMEがvim\runtime\であることが確認できました。

>gettext と iconv の DLL はパスの通ったところに置いてありますか？

こちらは「MINGWのコンソール上から使えるか？」ということでしょうか？
$gettext --version , $iconv --version
でそれぞれバージョンが確認できたので、通っていると思います。

>libintl-8.dll, libiconv-2.dll (32bit版は libgcc_s_sjlj-1.dll も) を入手してください。

こちらは、gettextとiconvがなければ入手が必要ということでしょうか？

初心者ですみません。。いろいろ壮大な勘違いをしているかもしれません＜〇＞

**Comment by k-takata** [comment]
MSYS2 をインストールしているならば、64bit版は `C:\msys2\mingw64\bin` に、32bit版は `C:\msys2\mingw32\bin` に上記の DLL (2個または3個)があるはずですので、(g)vim.exe と同じ場所にコピーしてください。

**Comment by hiro-github** [comment]
返信ありがとうございます＜〇＞

MSYS2 64bit版を使っています。
`C:\msys64\mingw64\bin` に `libiconv-2.dll` はありましたが、
`libintl-8.dll`　が `C:\msys64` 以下にはどこにも見当たりませんでした。
`libiconv-2.dll`　だけ `gvim.exe` と同じフォルダにおきましたが、メッセージは英語のままです。

「libintl-8.dll ダウンロード」でググると怪しいサイト(関係のないようなのソフトのダウンロードも促すような)しかヒットしなくて
ダウンロードを躊躇しています。

ほかに `libintl-8.dll` を手に入れる方法はありますでしょうか？
もしくは素直にダウンロードをすればよいですか？

何度も本当にすみません。

**Comment by k-takata** [comment]
MSYS2 のコンソールから、以下のコマンドを実行すると gettext (libintl) をインストールできます。

```
pacman -S mingw-w64-x86_64-gettext
```

(32bit版の場合は、mingw-w64-i686-gettext)

**Comment by hiro-github** [comment]
できました！
~~途中から半分あきらめてましたが..~~
ビルドしてGVimを使うって色々とハードルが高いんですね。。少なくとも私にとっては＿|￣|○

大変ありがとうございました！
