### ISSUE TITLE
非同期なsystem()はどうだろうか?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#133]
背景。Vim自身に非同期に機能が欲しいが、スクリプト実行系のレベルにおいて今の構造では絶対に無理。server機能は環境によって使えなかったり、大仕掛けすぎるところもある。で、中間案としてsystem()の非同期版=asystem()を用意するというのはどうか。なおこのasystem()は以下のように段階的に実装すると良いかもしれない。
1. 実行したプログラムの終了を待って関数コールバックする
2. 実行したプログラムが標準出力を(一行)行う度に関数コールバックする

増やす関数はこんな感じだろうか?
- asystem({expr}, {callback_func}, {userdata}, [{callback_mode}]): returns task_id.
- asystem_send({task_id}, {expr}): send {expr} to stdin of the task.
- asystem_kill({task_id}): stop the task.

コールバックの引数はこんな感じを想定
- callback_func({task_id}, {userdata}, {expr}):

ご意見よろしく。

**Comment by thinca** [comment]
`v:shell_error` にあたるものも受け取りたいです。あれ最後の1つしか保持できないので。

**Comment by koron** [comment]
@thinca 外部プロセス終了時のコールバックを規定して、そこに終了コードを入れれば良い感じ?

**Comment by thinca** [comment]
ですね。1. の場合はコールバック関数で直接受け取れるといいんですが、そうなると 2. と関数のシグネチャが変わりますね。
仕様上違っても問題はなさそうですが、使い勝手の面だとどうなんだろう…。

**Comment by koron** [comment]
エンジニアリング的には2のケースはコールバック関数自体を分けろってところですね。Vim本体の実装的には一個のほうが気が楽ですw

**Comment by thinca** [comment]
1 と 2 を明確に分けるのではなく、基本は 1 だけど、オプションでもう1つ関数を渡せば 2 を受け取ることもできるよ、とか。
- `asystem({expr}, {userdata}, {callback_func}, [{callback_for_line}])`

こんな感じで。(関数並べたかったので順番変えてみました)

**Comment by koron** [comment]
```
callback_func({task_id}, {userdata}, {exit_code}, {stdout})

callback_func_line({task_id}, {userdata}, {stdout_line})
```

ってところかしらねぇ。ただcallback_funcのほうのstdoutはテンポラリファイル名にするとか、line利用時にはなくなるとかだと良いのかしら?

逆に一つにまとめるなら

```
callback({task_id}, {userdata}, {stdout}, {exit_code})
```

にして、line時にexit_codeをnilで呼び出す、とかね。

**Comment by thinca** [comment]
nil 欲しいですね…。

**Comment by koron** [comment]
ってnilないんだっけ?w

**Comment by thinca** [comment]
Vim script に nil はありません！

**Comment by ynkdir** [comment]
非同期の話題はMLでも何度か目にしたことがあります。
試してはないですが。

http://article.gmane.org/gmane.editors.vim.devel/28791/

> Original patch (branch asystem) (see wiki)
> http://github.com/bartman/vim
> 
> My changes - which have to be tidied up:
> http://github.com/MarcWeber/vim (branch work)
> 
> An illustration about how a VimL abstraction will look like:
> http://github.com/MarcWeber/vim-addon-async

**Comment by mattn** [comment]
コンテキスト風にするのもありかと。javascript風？

``` vim
let s:ctx = {}

function! s:ctx.online(line)
  echo a:line
endfunction

function! s:ctx.onexit(code)
  echo self.pid " is exited :" code
endfunction

let s:pid = asystem("someprocess", ctx)
```

thincaさんやtyruさんあたりはこっちの方が好きなんじゃなかろうかと勝手に想像。

**Comment by thinca** [comment]
割と好きですが、Bramさんは逆に嫌いそう…。

**Comment by koron** [comment]
私も好き。だけどドキュメントが書きにくそうなのと、Bramが嫌がりそうなのを考慮して、実装が早そうな例をを提案したつもりw

**Comment by mattn** [comment]
こっちの方が拡張性あるんだよねー。あと`asystem`呼ぶと、ctxにメソッド生やしてくれて、そこから

```
call s:ctx.send("foo")
```

なんてのもありかも。OOだねー。Bramに嫌われるだろうけど。

**Comment by koron** [comment]
ctx風のI/Fを導入するのはそれはそれで重要なトピックだよね。

**Comment by koron** [comment]
何気なくキーボードで `e` タイプしたら閉じられたwww

**Comment by mattn** [comment]
結論：lambda欲しい...

こうですか？

**Comment by koron** [comment]
それは意味合いが全然違ってくるwww

**Comment by thinca** [comment]
折角辞書があるのだしそういうUIがあっても良い。と言うか、各種 if_xxx にあるような OO なインターフェース pure Vim script に欲しいですね。完全に別 Issue ですが。

**Comment by mattn** [comment]
おー`e`で閉じれるのか。

**Comment by k-takata** [comment]
job control/channelでこれが実現しつつありますね。

**Comment by koron** [comment]
とりあえず、閉じちゃいましょ。
