### ISSUE TITLE
マルチバイト文字を入力したときにpopup-filterが無効な文字を受け取ることがある

### ISSUE THREAD

**Issue by Bakudankun** [vim-jp/issues#1334]
## 不具合の内容

liuchengxu/vim-clap#320 で指摘されて気づいた現象です。
popupにマルチバイト文字を入力しようとすると、popup-filter関数に無効な文字が渡されることがあります。
feedkey使っても再現するのでたぶんバグと思われます？

### 現象・ログ

入力した文字が（おそらく）特定のバイトを含んでいるとき、その直後に数バイト紛れ込んだ状態でpopup-filterに渡されます。

* `。`　→　`e3 80 fe 58 82`（本来は`e3 80 82`）
* `｛`　→　`ef bd 9b fd 51`（本来は`ef bd 9b`）
* `Ý`（GUIでは`<A-]>`で入力可能）　→　`c3 9b fd 51`（本来は`c3 9b`）

などで再現します。

### 再現手順

encodingがutf-8の状態で↓を `:source`
```vim
function ShowKeyBytes(winid, key) abort
  if a:key == "\<CursorHold>"
    return 0
  endif

  if a:key == 'q'
    call popup_close(a:winid)
  else
    let byte_sequence = range(strlen(a:key))
          \ ->map({k, v -> a:key[k]->char2nr()->printf('%x')})
          \ ->join()
    " call popup_settext(a:winid, [a:key, byte_sequence])
    echo a:key .. "\n" .. byte_sequence
  endif

  return 1
endfunction


echo 'Press q to finish testing.'
call popup_create('', #{
      \   mapping: 0,
      \   filter: function('ShowKeyBytes'),
      \ })


call feedkeys('｛') " ここで検証したい文字を入力
call feedkeys('q')
```
最後の２行をコメントアウトするとフリーにテストできます

### 期待動作

入力した文字がそのまま渡されることを期待します。

## Vimのバージョン

8.2.221 (CUI & GUI)

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (1903)
*   Linux Mint 19.3 Cinnamon 64bit

**Comment by ichizok** [comment]
PRed
https://github.com/vim/vim/pull/5706

**Comment by ichizok** [comment]
8.2.0329
https://github.com/vim/vim/commit/ec084d3356cc2a23f2f44707810c38ab590d2e66
