### ISSUE TITLE
'buftype'がnofile等に設定されているバッファを既に存在するファイルに書き込む時に確認無しに上書きされてしまう

### ISSUE THREAD

**Issue by kuuote** [vim-jp/issues#1337]
## 不具合の内容

`'buftype'`が`nofile`等に設定されているバッファを既に存在するファイルに書き込む時に確認無しに上書きされてしまう

### 現象・ログ

通常、存在する別のファイルに書き込もうとすると`E13:ファイルが存在します`と出てきますが、`nofile`の状態だと、何も出てこなく、そのまま上書きされてしまいます。

### 再現手順

`vim --clean` にて

```vim
:write <filename>
:enew
:setlocal buftype=nofile
:write <filename>
```
を実行すると上書きされます

### 期待動作

通常のバッファと同様に`E13`が出力されてほしいです

## Vimのバージョン

8.2.390

## OSの種類/ディストリ/バージョン

*   Arch Linux x86-64

## その他

vim-jpのslackより

https://vim-jp.slack.com/archives/CJMV3MSLR/p1584581184144900
https://vim-jp.slack.com/archives/CJMV3MSLR/p1584581411150300
https://vim-jp.slack.com/archives/CJMV3MSLR/p1584581444151400

**Comment by tsuyoshicho** [comment]
slackから、この挙動に修正された commit

https://github.com/vim/vim/commit/11717bb0a1275f1e270396aeb1df92d973d4d068

**Comment by tsuyoshicho** [comment]
slackから、nofile の挙動の変化

https://github.com/vim/vim/commit/26910de8b0da6abab87bd5a397330f9cbe483309

**Comment by koron** [comment]
この挙動の導入経緯:

7.1.172 で bt=acwrite の時にファイル実在チェックをしないようにした。
ただし bt_nofile (現在は bt_nofilename) で bt=acwrite をチェックするようにしたので
bt=nofile もファイル実在チェックをしないようになってしまった。

bt=acwrite のときはそもそも :w filename の filename すらチェックしなくてよい
⁼BufWriteCmd で取り扱うはずなのでのでこれで良い。

一方で bt=nofile 他も同じように存在チェックをバイパスしてしまうのはかなり怪しい。

---

7.1.172 の詳細

https://github.com/vim/vim/commit/11717bb0a1275f1e270396aeb1df92d973d4d068

```
Patch 7.1.172
Problem:    When 'buftype' is "acwrite" Vim still checks if the file or
	    directory exists before overwriting.
Solution:   Don't check for overwriting when the buffer name is not a file
	    name.
Files:	    src/ex_cmds.c
```

**Comment by kuuote** [comment]
8.2.403
https://github.com/vim/vim/commit/18a2b87ca27c378a555b20f14a284d2ce3511427
