### ISSUE TITLE
conptyとcoc.nvimを使っているとターミナルを閉じたときにVimが落ちる

### ISSUE THREAD

**Issue by Bakudankun** [vim-jp/issues#1338]
## 不具合の内容

`termwintype=conpty`の状態でcoc.nvimを使用していると、ターミナルを開いた後、ジョブを終了させてターミナルウィンドウを閉じるとvimが落ちます。

### 再現手順

1. `git clone https://github.com/neoclide/coc.nvim.git`
1. `cd coc.nvim`
1. `vim --clean "+set rtp+=%CD% termwintype=conpty" "+runtime plugin/coc.vim"`
1. `:terminal`
1. `exit<CR>`
1. vimが落ちる

### 期待動作

vimが落ちないこと

## Vimのバージョン

[8.2.416](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.0416)

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 1909 64bit
* Node.js v12.16.0

## 使用している or 関係していそうなプラグイン

* [coc.nvim](https://github.com/neoclide/coc.nvim)

## その他

4.で`:terminal`の代わりに`:terminal ++noclose`とした場合は落ちません。
ターミナルのジョブが終了すると同時にターミナルウィンドウが閉じるときに落ちるようです。

**Comment by Bakudankun** [comment]
確認のため何度かVimを落としているうちに上の再現手順では落ちなくなってしまいました……（普段の環境では依然落ちる）
PC再起動して確認します

**Comment by Bakudankun** [comment]
PC再起動してもvimではなぜか落ちなくなってしまいましたが、gvimではまだ落ちます。なんで？

**Comment by Bakudankun** [comment]
`--clean`じゃない（普段のプラグイン類をロードした）vimで試したら落ちました。
処理速度の関係かも

**Comment by ghost** [comment]
再現開始…

**Comment by mattn** [comment]
プラグインのどれかが作用するのであれば、使っておられるプラグインを外していって特定頂く必要があるかも。

**Comment by Bakudankun** [comment]
`gvim --clean "+set rtp+=%CD% termwintype=conpty" "+runtime plugin/coc.vim"`で落ちるのでcocで間違いないとおもいます

**Comment by ghost** [comment]
ヒープダブルフリー…

**Comment by ghost** [comment]
```
BUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ
FAULTING_SOURCE_FILE:  C:\Vim\vim\src\channel.c
FAULTING_SOURCE_LINE_NUMBER:  1727
FAULTING_SOURCE_CODE:  
  1723: 	return NULL;
  1724:     if (outlen != NULL)
  1725: 	*outlen += node->rq_buflen;
  1726:     // dispose of the node but keep the buffer
> 1727:     p = node->rq_buffer;
  1728:     head->rq_next = node->rq_next;
  1729:     if (node->rq_next == NULL)
  1730: 	head->rq_prev = NULL;
  1731:     else
  1732: 	node->rq_next->rq_prev = NULL;
```
一回目はDOUBLE FREEって出たんだがなあ…取り急ぎ…

**Comment by mattn** [comment]
channel_parse_message が2回呼ばれてアウトですね。

**Comment by mattn** [comment]
ch_killing が TRUE の状態で残りに詰まってるデータを取り出すために channel_close_one が呼ばれ、そこから channel_parse_message がもう1回呼ばれて double free

**Comment by ghost** [comment]
channel_clear_one でも落ちてるので channel_peek がうまくないのかなあと…

**Comment by mattn** [comment]
正しいかどうか分からないし、本当は free 中みたいなフラグ立てた方がいいかもしれないけど、とりあえずコメントで意図は伝わると思います。

```diff
diff --git a/src/channel.c b/src/channel.c
index d5240fc25..2f6894378 100644
--- a/src/channel.c
+++ b/src/channel.c
@@ -4456,6 +4456,10 @@ channel_parse_messages(void)
 	{
 	    if (channel->ch_killing)
 	    {
+		// Set killing FALSE for avoiding double-free.
+		// channel_clear_one call channel_parse_messages to get rest
+		// contents. It makes double-free.
+		channel->ch_killing = FALSE;
 		channel_free_contents(channel);
 		channel->ch_job->jv_channel = NULL;
 	    }
```

**Comment by ghost** [comment]
伝わりました…FALSE にしたことによるロジック変化の確認を今夜の作業にしました…

**Comment by ghost** [comment]
````diff
diff --git a/src/channel.c b/src/channel.c
index d5240fc25..6dde107bf 100644
--- a/src/channel.c
+++ b/src/channel.c
@@ -4457,9 +4457,11 @@ channel_parse_messages(void)
 	    if (channel->ch_killing)
 	    {
 		channel_free_contents(channel);
+		channel_free_channel(channel);
 		channel->ch_job->jv_channel = NULL;
 	    }
-	    channel_free(channel);
+	    else
+		channel_free(channel);
 	    // channel has been freed, start over
 	    channel = first_channel;
 	    continue;
````
これで様子を見ます。

**Comment by ghost** [comment]
検証ありがとうございました。

**Comment by k-takata** [comment]
[8.2.0435](https://github.com/vim/vim/commit/dbbb0ef729e392e313ccc63c247bff1b828a214d) で直ったと思われますので、閉じます。

**Comment by Bakudankun** [comment]
最新のVim（8.2.0439）で試してみましたが、まだ落ちてしまうようです……。
ためしにVimのデバッグに挑戦してみます

**Comment by mattn** [comment]
このパッチでは直らないと思いますよ。

**Comment by ghost** [comment]
はい、当時の自分は寝てますね…フラグ立たせっぱではどうにもなりません…

**Comment by Bakudankun** [comment]
一応、最新のやつビルドして落としたときのスクショ取れたので貼っておきまふ
![crash](https://user-images.githubusercontent.com/4504807/77428434-6b348d80-6e1b-11ea-99bd-9f7810855b82.png)

**Comment by ghost** [comment]
````diff
diff --git a/src/channel.c b/src/channel.c
index 6dde107bf..27801f076 100644
--- a/src/channel.c
+++ b/src/channel.c
@@ -4456,6 +4456,9 @@ channel_parse_messages(void)
 	{
 	    if (channel->ch_killing)
 	    {
+		// Suppression of reentry
+		channel->ch_killing = FALSE;
+
 		channel_free_contents(channel);
 		channel_free_channel(channel);
 		channel->ch_job->jv_channel = NULL;
````
スクショにより上記 channel->ch_job の二度漬けを怒られているのが確認できました。

**Comment by ghost** [comment]
https://github.com/vim/vim/pull/5835
で続いている話、あー free_channel した後に NULL 入れてどうすんの感を私が出してますね…

**Comment by Bakudankun** [comment]
Bram氏が自分で直したって言ってますがまだ落ちますね……。（v8.2.0444）

![crash](https://user-images.githubusercontent.com/4504807/77484521-1837f600-6e6e-11ea-83aa-909afd7f1988.png)

**Comment by Bakudankun** [comment]
[patch 8.2.0452](https://github.com/vim/vim/commit/a9c3a30891edd7347d94298c48ea68bb5c165fd7) により落ちなくなったのを確認しました。

**Comment by Bakudankun** [comment]
忘れてた！
対応してくださった皆さん本当にありがとうございました！ 🙇

**Comment by ghost** [comment]
元々は私が書いたコードがふらついていたのが原因でして、安定に一歩近づけてよかったです。
