### ISSUE TITLE
[E227: * というマッピングは既に存在します

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1343]
## 質問の内容
kaoriya の gvim を使用しております。

vimrcに、
下記のように記載すると、
> "nnoremap F *N

gvim起動時に下のエラーメッセージが表示されます。
> E227: * というマッピングは既に存在します

エラーメッセージを出さずに上記コマンドを有効にする方法を
教えていただきたいです。

## Vimのバージョン
kaoriya gvim , windows 10

**Comment by k-takata** [comment]
`:verbose nnoremap *` を実行して、`*` に対するマッピングをどこで行っているか調べてはどうでしょうか。
あとは、.vimrc を gist などにアップロードすると、詳しい回答が得られるかもしれません。

**Comment by hiro-github** [comment]
ありがとうございます＜〇＞

>`:verbose nnoremap *` を実行して、`*` に対するマッピングをどこで行っているか調べてはどうでしょうか。

試してみると、
**vim-mark\plugin\mark.vim 行 296**
と表示されました。プラグインですでに定義されてたんですね。。
mark.vimはいじらずに、vimrcだけを編集してエラーメッセージを消すことはできるのでしょうか？

**Comment by todashuta** [comment]
使っているvim-markはどちらのものでしょうか。
githubのレポジトリなどを少し調べてみましたが、同名のものがたくさんあります。

**Comment by hiro-github** [comment]
https://github.com/inkarkat/vim-mark
です。

やっぱり `.vimrc` はさらしておいた方がいいですね。
こっぱずかしいものがあったので、控えていましたが..
k-takata さんの提案どおり gist というものを使ってみました。
(使い方があってるのか、よくわかってません。。)
https://gist.github.com/hiro-github/dc9fa1baf5e37804ff93391d653917c6

**Comment by todashuta** [comment]
上げていただいたvimrcの、
この行のコメントアウトを外すと、エラーメッセージが出るということでよいでしょうか。

>```vim
>"nnoremap * yiwk$/<C-r>0<CR>
>```
>https://gist.github.com/hiro-github/dc9fa1baf5e37804ff93391d653917c6#file-myvimrc-L122

だとすると、vim-markのこの部分がエラーメッセージを出してるのかと思います。

>```vim
>if !hasmapto('<Plug>MarkSearchNext', 'n')
>	nmap <unique> * <Plug>MarkSearchNext
>endif
> ```
> https://github.com/inkarkat/vim-mark/blob/502dc4fb032006758eef9a917956634b3cfba3a7/plugin/mark.vim#L295-L297

対処としては、vimrcに下記の行を追加すれば良いかと思います。

```vim
nnoremap <SID>dummyMarkSearchNext <Plug>MarkSearchNext
```

`<Plug>MarkSearchNext`に対するダミーのマッピングを定義して、
`!hasmapto('<Plug>MarkSearchNext', 'n') == 0`となるようにして、
L296のマッピングのコマンドの実行を回避しています。

**Comment by hiro-github** [comment]
すみません。現状のvimrcをアップロードしてました。

>上げていただいたvimrcの、
この行のコメントアウトを外すと、エラーメッセージが出るということでよいでしょうか。

はい、お察しのとおりです。

`nnoremap * yiwk$/<C-r>0<CR>`
を追記することで、エラーメッセージが消えて `*` で次の候補に進めずに検索することができました！

> <Plug>MarkSearchNextに対するダミーのマッピングを定義して、
!hasmapto('<Plug>MarkSearchNext', 'n') == 0となるようにして、
L296のマッピングのコマンドの実行を回避しています。

上記に関しては、私にはまだよく理解できてませんが、少しずつ勉強していきます。。

ご教授ありがとうございました！
