### ISSUE TITLE
ctagのオプションに関して..

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1344]
## 質問の内容
すみません。ここで質問する内容ではありませんが、github上で日本語が使える適切なカテゴリ?が見当たりませんでした。

vbのctagに関しての質問です。

https://w.atwiki.jp/310ke/pages/21.html
上記ページに
> ctags -f xxx.tags --excmd=number -R --languages=Basic --langmap=Basic:.frm.bas.cls --Basic-types=-l -L srcList.txt

とありますが、
`--Basic-types=-l` のところはどういった意味でしょうか？
また意味を確認する方法（Webページや `:help`など)もあれば教えていただきたいです。

**Comment by masatake** [comment]
Basic言語における label を収集しないという意味になります。
`--Basic-types=-l`における types の部分を kinds におきかえて、ctagsに付属するmanページを見ると意味がわかります。"types" というのは古いctagsの実装での言い回しのようです。

ある言語について、ctagsがどういった種類の識別子を収集できるかは 
```
$ ctags --list-kinds=<言語名>
```
で確認できます。Basicであれば、
```
$ ctags --list-kinds=Basic
c  constants
f  functions
l  labels
t  types
v  variables
g  enumerations
```
となります。

**Comment by hiro-github** [comment]
> "types" というのは古いctagsの実装での言い回しのようです。

これは気づきませんでした。。
説明のとおり、自分でも確認することができました！
ありがとうございました＜〇＞
