### ISSUE TITLE
プラグインのマッピングの仕方

### ISSUE THREAD

**Issue by hiro-github** [vim-jp/issues#1345]
## 質問の内容
`:map`を実行すると、`W`は下記のように設定されています。
`n  W             <Plug>JaSegmentMoveNW`

vimrcを編集して、`w`に`<Plug>JaSegmentMoveNW` を割り当てたいのですがどのように記載すればよいのかわかりません。
`nnoremap  w <Plug>JaSegmentMoveNW`　のように記載しても、動作しませんでした。

`nmap w W`
とすればひとまずやりたいことはできたのですが、`<Plug>JaSegmentMoveNW`を直接割り当てたいです。

## Vimのバージョン
kaoriya , windows 10

**Comment by k-takata** [comment]
`nnoremap` ではなく `nmap` を使ってください。`<Plug>...` は、プラグインの中でさらに何かにマップされていますので、リマップを許可しないと動きません。

**Comment by hiro-github** [comment]
ありがとうございます！
おかげさまでやりたいことができました＜〇＞
