### ISSUE TITLE
vim-lspでLSPが起動しないケースが有る

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1348]
## 質問の内容
件名通りvim-lspでLSPが起動しない場合が有ります
これは仕様なのでしょうか?
それとも設定が良くないのでしょうか?

まずプラグインなどの設定状況です
`:r!grep -Ev '^\s*".+' \~/.vimrc`
> scriptencoding utf-8
> if has('vim_starting')
> 	if &compatible
> 		set nocompatible
> 	endif
> 	let s:cache_home = empty($XDG_CACHE_HOME) ? expand('\~/.vim') : $XDG_CACHE_HOME
> 	let s:dein_dir = s:cache_home . '/bundle'
> 	let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
> 	if !isdirectory(s:dein_repo_dir)
> 		call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
> 	endif
> 	let &runtimepath = &runtimepath . ',' . s:dein_repo_dir
> 	if dein#load_state(s:dein_dir)
> 		call dein#begin(s:dein_dir)
> 		let g:rc_dir = expand('\~/.vim')
> 		let s:toml = g:rc_dir . '/dein.toml'
> 		call dein#load_toml(s:toml, {'lazy': 0})
> 		call dein#end()
> 		call dein#save_state()
> 		if dein#check_install()
> 			call dein#install()
> 		endif
> 	endif
> endif
> filetype plugin indent on

`:r!grep -Ev '^\s*#.+' \~/.vim/dein.toml`
> [[plugins]]
> repo = 'Shougo/dein.vim'
> [[plugins]]
> repo = 'prabirshrestha/vim-lsp'
> merged = 0
> hook_add = 'let g:lsp_log_file = expand("\~/vim-lsp.log")'
> [[plugins]]
> repo = 'mattn/vim-lsp-settings'
> depends = ['vim-lsp']
> merged = 0

次に希望の動作にならないケースですが、
`$ vim -p sample.{txt,vim}`
と p オプション付きで起動すると、
`:tabnext`
で sample.vim をアクティブにしても
`:LspStatus`
> vim-language-server: not running

に成ります
`$ vim sample.{txt,vim}`
で起動した場合は希望通りの
```
:bnext
:LspStatus
```
> vim-language-server: running

となります
p オプションと組み合わせた時に2つ目以降のファイルで起きます

このときは
`:call lsp#enable()`
してもダメなので、
```
:call lsp#disable()
:call lsp#enable()
```
た時のログの先頭付近は次のとおりです
`:r ~/vim-lsp.log`
> 2020年07月28日 21時25分09秒:["lsp#register_server","server registered","vim-language-server"]
> 2020年07月28日 21時25分10秒:["vim-lsp signs enabled"]
> 2020年07月28日 21時25分10秒:["vim-lsp highlighting enabled (textprop)"]
> 2020年07月28日 21時25分10秒:["s:on_text_document_did_open()",1,"text","/home/user","file:///home/user/sample.txt"]
> 2020年07月28日 21時25分47秒:["vim-lsp signs disabled"]
> 2020年07月28日 21時25分47秒:["vim-lsp highlighting disabled"]
> 2020年07月28日 21時25分58秒:["vim-lsp signs enabled"]
> 2020年07月28日 21時25分58秒:["vim-lsp highlighting enabled (textprop)"]
> 2020年07月28日 21時25分58秒:["s:on_text_document_did_open()",2,"vim","/home/user","file:///home/user/sample.vim"]
> 2020年07月28日 21時25分58秒:["Starting server","vim-language-server",["/usr/local/bin/vim-language-server","--stdio"]]
## OS
`$ lsb_release -a`
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.1 LTS
> Release:	20.04
> Codename:	focal

`$ uname -a`
> Linux pc 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> $ vim --version
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
> 適用済パッチ: 1-2269
## 関係しているプラグイン
prabirshrestha/vim-lsp
mattn/vim-lsp-settings

**Comment by mattn** [comment]
ありがとうございます。どうやら vim で `-p` を使うと `BufReadPost` イベントが2つ実行されないという問題がある様です。

**Comment by mattn** [comment]
すみません。↑は僕の勘違いでした。これで直ると思います。

https://github.com/prabirshrestha/vim-lsp/pull/873

うまく動いてそうなら今日明日中にマージします。

**Comment by mattn** [comment]
マージされました。

https://github.com/prabirshrestha/vim-lsp/commit/04cef02eed7fe861f5fdbf066da1b8b7e270b8a2

**Comment by iranoan** [comment]
ありがとうございました
確認もできました
