### ISSUE TITLE
コマンドラインウィンドウの開閉時にWinLeave,WinEnterイベントが発生しない

### ISSUE THREAD

**Issue by jakalada** [vim-jp/issues#135]
現在使用している[Powerline](https://github.com/Lokaltog/vim-powerline)というプラグインの表示の更新のタイミングが、
イベント発生時のカレントウィンドウの値に依存しているので気づきました。

仕様かもしれないのですが、
コマンドラインウィンドウに入る前にWinLeaveが発生しません。
また、コマンドラインウィンドウを閉じ、他のウィンドウに移ったときWinEnterが発生しません。

CmdwinEnterがBufEnter やWinEnter の代わりに発生することと、
CmdwinLeaveがBufLeave やWinLeave の代わりに発生することは、
ヘルプで把握したのですが、上述のタイミングでイベントが発生しないのは不自然に感じます。

**Comment by koron** [comment]
内部実装から説明するとコマンドラインはウィンドウではない。ウィンドウ登場前のviにすら存在する。それらのイベントはカレントウィンドウが変更になった時に発生する。仮にコマンドラインウィンドウに入った時にカレントウィンドウの変更をしてしまうと、そこで入力したスクリプトは直前にいたカレントウィンドウへの操作を行えなくなって非常に不便である。仮にイベントの発生タイミングを変えた(増やした)場合、問題になるプラグインが山のようにでてくると推測される。

指摘文からは読み取りづらいが「コマンドライン内でカレントウィンドウを変更した時にWinEnter, WinLeaveが発生しない」と言っている可能性が考えられる。仮にそれがあるのだとすれば修正の必要がある。

**Comment by jakalada** [comment]
最初の"コマンドラインはウィンドウではない"は、
"コマンドラインウィンドウはウィンドウではない"と読み替えても間違いはないですか？

`q:`でコマンドラインウィンドウに入ってから、
`:`でコマンドラインに入り、
`echo winnr()`を実行して表示される値は、
コマンドラインウィンドウの番号だと思うのですが、
「カレントウィンドウではない」のでしょうか

**Comment by koron** [comment]
把握。以下、cmdlineとcmdwinと分けて書きましょう。

まだソースを見てないけどセンシティブそうなことは間違いない。cmdwinはカレントウィンドウとしないみたいになってないとやはり困りそうな気はする。cmdlineとcmdwinでカレントウィンドウに対する操作の結果が変わってしまうから。たとえば `echo winnr()` で表示される値はcmdlineだろうとcmdwinだろうと同じじゃないと困る。

**Comment by jakalada** [comment]
分けて書く了解です。

すみません、cmdlineを開いた時点でカレントウィンドウが、
cmdwinになってるのは説明のとおりっぽいです。
cmdwinからcmdlineを開いて`q`を実行するとcmdwinが閉じられるので。

今出先なので、家に帰ってから調べて書こうと思います(>_<)

**Comment by jakalada** [comment]
現在は下記のようなタイミングでイベントが発生しています。

パターン1: win1でwin2を開いて閉じた場合

```
(win1を離れる前)WinLeave -> (win2に入った後)WinEnter
　　　　　　　　　　　　 -> (win2を離れる前)WinLeave -> (win1に入った後)WinEnter
```

パターン2: win1でcmdwinを開いて閉じた場合

```
(win1を離れる前)なし -> (cmdwinに入った後)CmdwinEnter
　　　　　　　　　　 -> (cmdwinを離れる前)CmdwinLeave -> (win1に入った後)なし
```

パターン2の状況でPowelineプラグインがwin1の&l:statuslineの値を更新しないため、
自動コマンドを登録しようとして適切なイベントを探したところ、
(aを離れる前)と(aに入った後)に発生するようなイベントがないことに気づきました。
Powerlineの今のコードには関数を呼び出したときのカレントウィンドウの更新を行なう関数しかないのです。

発生するイベントなど、省略しているところもあるのですが、
説明に間違っているところなどがないか、確認をお願いしますm(_ _)m

**Comment by koron** [comment]
@jakalada 

推測ですが、たぶん内部的な「現在のウィンドウ(以下curwin)」はパターン2では変わってない、というより変えられないんですよね。一方WinEnter/Leaveはcurwinが変わる時にだけ発生する。だからパターン1では発生する。実装の何らかの都合でcmdwinを開いた時にcurwinを変更する(=WinEnter/Leaveを発行する)ことができなかったので、代用品としてCmdwinEnter/Leaveという別のイベントを作ったのかもしれません。そう考えると、直感的にはこのイベント発生のロジック/タイミングは変えるべきではないと考えられます。

Powelineプラグインの作りはわかりませんが、以上を踏まえてプラグイン側でのこんな代替案はどうでしょう。CmdwinEnterでwin1のウィンドウを記憶しておき、CmdwinLeaveで記憶したwin1の&l:statuslineを更新する。もしくはWinEnter毎にlastWinとして覚えておいて、CmdwinLeaveでlastWinを更新するという手も考えられます。それらをやらない/やれない理由はありますか?

**Comment by h-east** [comment]
@koron 同じ事(後半の後者)考えてました。

**Comment by koron** [comment]
> 内部的な「現在のウィンドウ(以下curwin)」はパターン2では変わってない、というより変えられない

正確にはcurwinはcmdwinで実行するコマンドの適用先なのでcmdwinへ変更できない、と書くほうが良いかな?

**Comment by jakalada** [comment]
@koron 

Powerlineの対応はそのような流れになると思います。
cmdwinを開いたときのバッファが、cmdwinのバッファの代替バッファになっているので、
記憶せずに、そういうところから辿れたらいいなぁとか。

"実装の何らかの都合でcmdwinを開いた時にcurwinを変更する(=WinEnter/Leaveを発行する)がことできなかった"について、
私はWinEnter/Leaveを発行することと、curwinを変更することは分けて考えていました。

curwinの定義が違っていないか少し不安ですが、
CmdwinEnter/Leaveで実行される自動コマンドはcmdwinをcurwinとして扱います。
また、cmdwinで開いたcmdlineで`let b:bar = 1`や`let w:bar = 1`を実行するとcmdwinの変数が作られます。
こうした動作から、curwinを変更することができなかった、ということはなく、
内部的にもcurwinはcmdwinに変更されていると考えます。

次に、
cmdwinからcmdlineを開き、editコマンドなどでファイルを開こうとすると、
`E11: Invalid in command-line window; ...`というエラーが出てファイルが開けません。
また、cmdwinから他のウィンドウに移動しようとした際にもエラーが出ることなどから、
通常のウィンドウの実装に対して制約を加えることでcmdwinが実装されていると感じました。
そこから、WinEnter/Leave・BufEnter/BufLeaveを発行できなかったのではなく、
制約として、代わりにCmdwinEnter/Leaveを発行するという決定が、なんらかの理由で行われたと推測します。

上述のような推測から、
`(win1を離れる前)WinLeaveを発行 -> (win2に入った後)WinEnterを発行`に対応する、
`(win1を離れる前)なし -> (cmdwinに入った後)CmdwinEnterを発行`という実装の、
WinLeave、もしくはWinLeaveに対応するcmdwinのためのイベントが発行されない点は、
センシティブな理由によって避けたわけではないなら、
ニーズがなかったから発行しなかっただけだろう、と思っています。

**Comment by koron** [comment]
> WinLeave、もしくはWinLeaveに対応するcmdwinのためのイベントが発行されない点は、センシティブな理由によって避けたわけではないなら、ニーズがなかったから発行しなかっただけだろう、と思っています。

自分がVimの本体のプログラマだったら、そう作るか、そういう経路を辿るかを想像してみてください。きっとそうはしないでしょう?

実際はセンシティブな理由があります。これを考える上でのポイントはVimではまず普通のウィンドウとWinEnterLeaveが実装されて、随分たってからcmdwinが実装されたという点と、cmdwinは普通のウィンドウと性質が大きくことなるという2点です。おそらくcmdwinを作った最初期にはcmdwinに対してもWinEnter/Leaveを発行していたことは推測に難くありません。こうした場合WinEnter/Leaveを使って普通のウィンドウを操作する既存のプラグインの多くがcmdwinに対して誤動作をするようになったハズです。それを受けてcmdwinに対するWinEnter/Leaveを止め、新たにCmdwinEnter/Leaveを新設したと考えるほうが自然です。またこれはVimにとっては「cmdwinに対するWinEnter/Leaveを発行できなかった」のと同じ意味です。

なので「ニーズがなかったからcmdwinにWinEnter/Leaveを発行しない」のではなく、「問題があったからcmdwinにWinEnter/Leaveを発行しない」及び「ニーズがあったからcmdwinにはCmdwinEnter/Leaveを発行している」となります。

ここまでの私の主張をまとめると、ニーズがあってもcmdwinに対してWinEnter/Leaveが発行されることはないだろう、ということになります。

### 本題(最重要)

というわけで、本issueの主題である「コマンドラインウィンドウの開閉時にWinLeave,WinEnterイベントが発生しない」は
- プラグイン側での代替手段がある
- Vim的に変更するのがセンシティブなポイントである
  - 特にそれを想定していない多くの既存プラグインが誤動作をする可能性を避ける

の二点によりworks for meとしてissueを閉じようと考えてますが、良いですか?
(実際は前者だけでも閉じるに十分な理由だとおもいますがw)

**Comment by jakalada** [comment]
> ニーズがあってもcmdwinに対してWinEnter/Leaveが発行されることはないだろう

私もその点を変更してほしいとは思っていません。
CmdwinEnterのヘルプにも"このイベントはイベント BufEnter やWinEnter の「代わりに」発生する"と書かれているので、仕様だと納得しています。

私が不自然に感じているのは、"cmdwinを開いたウィンドウ"に対してイベントが発行されていない点です。
そこを区別した上での判断であれば、閉じていただいて良いです。

**Comment by koron** [comment]
では閉じます。

> 私が不自然に感じているのは、"cmdwinを開いたウィンドウ"に対してイベントが発行されていない点です。

感想ですが、私は不自然に感じません。

**Comment by koron** [comment]
私がなんで不自然と感じないか、少し考えてみましたので以下に補足しておきます。

Vimの実装経緯から考えると、そもそもcmdwinの実装方法と存在が不自然な状態にあります。なのでそれにまつわるイベントが不自然な状態になるのは当然で、逆説的に自然です。

もうひとつ懸念事項が浮かんだのでメモ代わりに。

おそらくcmdwinには操作対象となるウィンドウが設定されています。その「操作対象となるウィンドウ」がcmdwinを開いたまま変更された場合(できるかどうかはわかりませんが)に、しっかりWinEnter/Leaveが出ているかどうか気になります。仮にできるとして&出ていないのだとすれば、それは直さないとダメでしょう。

**Comment by jakalada** [comment]
了解です。
ありがとうございました。
