### ISSUE TITLE
IM の変換エリアにスタイルが設定されない（GTK3）

### ISSUE THREAD

**Issue by mjyut** [vim-jp/issues#1353]
## 不具合の内容
IM で入力中のエリアのフォントや背景色が、Vim の設定と異なり、GTKのデフォルト設定のままになってしまう。

### 現象・ログ
![vim_xim_probrem03_2020_08_16](https://user-images.githubusercontent.com/8846481/90332732-68208080-dffa-11ea-9f36-1edf1f0dfea4.png)

上の画像では解り易くするため、Vimの `guifont` を大きくしてあります。
変換中の「かき」や「下記」という文字のフォントだけが小さいままで、変換エリアの背景色も異なります。GTKのデフォルト設定に従っているようです。

### 再現手順
Vim は `--enable-gui=gtk3` でビルドされた物で、IM は uim を使っています。
fcitx は自前のウィンドウに変換中の文字を描画しているようで、この現象は観察できませんでした。（これはこれでバグなのかも知れませんが fcitx の正常な動作を知らないため、私はよく解りません）

### 期待動作
![vim_xim_probrem04_2020_08_16](https://user-images.githubusercontent.com/8846481/90332945-27c20200-dffc-11ea-9590-a796681a6f6f.png)

上のように、フォントや背景色が周りと同じになって欲しいです。
GTK2 バージョンでは、こうでした。
下の漢字「下記」は背景が黒くなっていますが、これは uim の仕様だと思います。

## Vimのバージョン
v8.2.1456

## OSの種類/ディストリ/バージョン
*  Linux 5.7.15 (Void Linux)
* gtk+3-3.24
* Xfce 4.14
* xorg-server 1.20.8
* uim 1.8.8

## その他
私の環境では以下の変更で直りました。
それらしき所を適当にいじっただけですので、正しい方法かは解りません。

```diff
diff --git a/src/gui_xim.c b/src/gui_xim.c
index e45e1793f..a333c7c6f 100644
--- a/src/gui_xim.c
+++ b/src/gui_xim.c
@@ -251,7 +251,7 @@ im_preedit_window_open()
 #if GTK_CHECK_VERSION(3,16,0)
     {
        GtkStyleContext * const context
-                                 = gtk_widget_get_style_context(gui.drawarea);
+                                 = gtk_widget_get_style_context(preedit_label);
        GtkCssProvider * const provider = gtk_css_provider_new();
        gchar              *css = NULL;
        const char * const fontname
@@ -275,7 +275,7 @@ im_preedit_window_open()
            fontsize_propval = g_strdup_printf("inherit");
 
        css = g_strdup_printf(
-               "widget#vim-gui-preedit-area {\n"
+               "#vim-gui-preedit-area {\n"
                "  font-family: %s,monospace;\n"
                "  font-size: %s;\n"
                "  color: #%.2lx%.2lx%.2lx;\n"
```

**Comment by presuku** [comment]
こちらも fcitx ですが同じ現象があり、同じパッチで直りました。
以前から、同じようなパッチで css の部分を `lable#vim-gui-preedit-area` としてましたが `#vim-gui-preedit-area` でも問題ありませんでした。

* Xubuntu 18.04
* libgtk-3-0:amd64 3.22.30-1ubuntu4
* fcitx 4.2.9.6

**Comment by presuku** [comment]
vim/vim/pull/13972 (https://github.com/vim/vim/commit/b1457d4cb9185b2b8d575b7736eff6d3a97d89eb) で、mjyut さんのパッチと同様のパッチが取り込まれましたので close で問題ないと思います。
