### ISSUE TITLE
:{winnr}resize {-+}N コマンドの挙動がおかしいケースがある

### ISSUE THREAD

**Issue by obcat** [vim-jp/issues#1354]
## 不具合の内容

カレントでないウィンドウ（仮にウィンドウ番号 2 だとします）に対して、 `:2resize +1` のようなコマンドを実行すると上手くリサイズできないことがあります。

### 現象・ログ

`+1` と指定しているのに逆に小さくなったり、 `2` ほど大きくなったりする。

### 再現手順

```vim
$ vim -u NONE
:split
:echo winnr('j')
2
:2resize +1  " 下のウィンドウの高さが 2 大きくなる
:2resize +1  " 下のウィンドウの高さが 2 小さくなる
```

### 期待動作

再現手順の例だと、下のウィンドウの高さが 1 だけ大きくなってほしい。

## Vimのバージョン

8.2.1800

## OSの種類/ディストリ/バージョン

*   macOS Catalina (バージョン 10.15.6)

## 使用している or 関係していそうなプラグイン

なし

## その他

`{winnr}resize 10` のようにサイズを絶対指定したときは `winnr` がカレントウィンドウであるかどうかに関わらずうまくいくようです。また、相対指定であってもカレントウィンドウを対象にした場合はうまくいきます。

**Comment by mattn** [comment]
```diff
diff --git a/src/ex_docmd.c b/src/ex_docmd.c
index 1fc67eaec..418889031 100644
--- a/src/ex_docmd.c
+++ b/src/ex_docmd.c
@@ -6365,7 +6365,7 @@ ex_resize(exarg_T *eap)
     if (cmdmod.split & WSP_VERT)
     {
 	if (*eap->arg == '-' || *eap->arg == '+')
-	    n += curwin->w_width;
+	    n += wp->w_width;
 	else if (n == 0 && eap->arg[0] == NUL)	// default is very wide
 	    n = 9999;
 	win_setwidth_win((int)n, wp);
@@ -6373,7 +6373,7 @@ ex_resize(exarg_T *eap)
     else
     {
 	if (*eap->arg == '-' || *eap->arg == '+')
-	    n += curwin->w_height;
+	    n += wp->w_height;
 	else if (n == 0 && eap->arg[0] == NUL)	// default is very high
 	    n = 9999;
 	win_setheight_win((int)n, wp);
```

ありがとうございます。空き時間にテストを足して pull-req 送ります。

**Comment by obcat** [comment]
迅速なご対応ありがとうございます（とてもはやくてビックリしている）。よろしくお願いいたします！

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/7152

**Comment by mattn** [comment]
[patch 8.2.1856](https://github.com/vim/vim/commit/9668cc57a1e70c99163f90f58202e206d12f40c8)
