### ISSUE TITLE
vim-jp で使っている Travis CI を .org から .com に移行する

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#1359]
## 概要

travis-ci.org は今年の12月31日に終了することが発表されています。
travis-ci.org で動かしている CI があれば、travis-ci.com か他のサービスに移行する必要があります。
機能的な面から最終的には GitHub Actions に移行したいところですが、手間を考えて、まずは travis-ci.com へ移行したいと思います。

## 移行対象

現時点で、vim-jp で Travis CI を使っているリポジトリは以下の 6 個があります。
(vimdoc-en は既に移行が完了しました。)

* [x] https://github.com/vim-jp/vimdoc-en
* [x] https://github.com/vim-jp/lang-ja
* [x] https://github.com/vim-jp/syntax-vim-ex
* [x] https://github.com/vim-jp/vimdoc-ja-working
* [x] https://github.com/vim-jp/vim-vimlparser
* [x] https://github.com/vim-jp/vital.vim

## 移行作業

* travis-ci.com 上での切り替え操作。
   権限を持っている人がここから操作 https://travis-ci.com/organizations/vim-jp/migrate
* リポジトリ内で使用しているツールの更新。(コミットメッセージ内の URL 等)
* README.md 等に貼ってあるバッジの更新。
   (プロジェクトの URL は travis-ci.org/... から travis-ci.com/github/... に変更になるが、バッジの svg の URL には github/ が入らない点に注意。)
* PR のマージに CI がパスすることを必須にしている場合は、チェックに使う CI を変更する。

## 移行による影響

* CI のログの場所やバッジの URL が変わる。
* 面倒を避けるため、切り替え作業中は CI が動くような操作 (PR 作成、コミットのプッシュ) は避けてもらった方がよさそう。

## 移行予定日

未定（今週末辺り？）

## 参考情報

* slack での議論
  https://vim-jp.org/slacklog/CRNLJDTU1/2020/11/#ts-1604893691.138000
* 公式の移行手順書
  https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by k-takata** [comment]
懸念、日程に対する意見、作業内容の不足など、指摘があればコメントをお願いします。

**Comment by tsuyoshicho** [comment]
1つ実施してくださってるので、そのときにやったことを書き下す(気にしたことがあれば)はあってもいいかも。
他の人が代行できるので。

あとは、badge URLとかは事前にマージ用ブランチで準備しておくとよさそう、くらい?

**Comment by tsuyoshicho** [comment]
vital.vimについてはGHA向けブランチはありますが、外の設定を変えるだけだった気がしますので、まあ追従できるし無理はしなくていいでしょうね。

**Comment by h-east** [comment]
- syntax-vim-ex 
travis-ci.com 上での切り替え操作をおこない、README.mdおよびツール内のURLの変更PRを出しました。
確認後、マージをお願いします。

**Comment by k-takata** [comment]
syntax-vim-ex 完了しました。
generator ブランチは CI がパスしていないとマージできない設定になっていましたが、その CI が .org になっていたため、これも .com に変更する必要がありました。

**Comment by k-takata** [comment]
lang-ja, vimdoc-ja-working 完了しました。

**Comment by k-takata** [comment]
Done!

**Comment by k-takata** [comment]
おや、go-vimlparser も移行しないといけないのか。
