### ISSUE TITLE
Win32 マルチスクリーン利用での残課題

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#136]
> vim win32のマルチスクリーン上でのバグ、修正されたのかと思ってたけど不完全だった。セカンドモニタが左に配置されている時、ダイアログがプライマリモニタ側に表示される。

https://twitter.com/#!/_samy_3/status/160101721996148737

twitterで指摘を発見したので転載。直すべきなのか、可能なのか要検討。

**Comment by mattn** [comment]
フックしてWM_INITDIALOGでMoveWindowすれば行けるけど、そこまでやるか的な印象

**Comment by koron** [comment]
普通のプログラムはどうしてんだろうね? 親ウィンドウを指定すれば大丈夫で、Vimは指定していないとか?

**Comment by ynkdir** [comment]
ファイルを開くとかの標準ダイアログは問題ないですよね？
inputdialog()なんかはWM_INITDIALOGでCenterWindow()を呼び出して中央に移動してます。
が、CenterWindow()がマルチモニタ対応してないみたいです。モニタが左でも右でも。

**Comment by koron** [comment]
gui_w48.c の `CenterWindow()` ですね? ということはコイツをマルチモニタに対応させるように直せば良い、ということになるのかな?

一瞬、`CenterWindow()` があるのかとWINAPIにあるのかと思ってMSDNを漁っちゃった。

**Comment by koron** [comment]
MSDNをみたらMFCのCWndやATLのCWindowにCenterWindowメソッドがありました。
こいつらの実装がマルチモニタに対応していたら、パクってくれば楽ちんかも。

**Comment by mattn** [comment]
MFC/ATLのソース見てないけど、これもしソースで解決しなきゃいけない問題ならバグじゃね？な気がする。
親ウィンドウ渡してんだから、真ん中表示しろよ的な。

**Comment by koron** [comment]
だれのバグ? CenterWindow()のバグ、という意味なら同意。で、治すのにMFCかATLの方法が参考になるなら、自分たちで考えるよりパクったほうが速いんじゃないか、というお話。

**Comment by koron** [comment]
くそ。また `e` 押したw

**Comment by mattn** [comment]
Windowsのバグという意味です。

**Comment by koron** [comment]
ややこしいけどVimが使ってるCeterWindow()はWINAPIじゃないよ。Vimが実装している関数です。

MFCやATLはMicrosoftが実装しているけどWindowsではないよね?

**Comment by mattn** [comment]
> ややこしいけどVimが使ってるCeterWindow()はWINAPIじゃないよ。Vimが実装している関数です。

はい。知ってます。
親ウィンドウを与えてて、Windows側で親ウィンドウの位置やサイズまで分かるはずなのにマルチモニタになった途端それが出来ていないのはWindowsのバグだろ...という意味です。

**Comment by mattn** [comment]
os_mswin.c の PrintHookProc で同じ事やってる。これコピれば(もしくは共通化すれば)直る。

**Comment by koron** [comment]
CenterWindowで、メトリクス使って補正してSetWindowPosしてるから、その補正の問題じゃないの? Windowsではなくて。

**Comment by mattn** [comment]
> Windowsでなくて。

自前で作ったウィンドウならそうでしょうね。しかしこれはファイルオープンダイアログ。ファイルを開く(保存)ダイアログを親ウィンドウと違うモニタに表示したい方が特別な例なので、デフォルトの動作がそうなってない方がおかしいっしょw。それのためにフラグ１個弄るだけならまだしも、フックかけないといけないとかアホらしい。そんな機能の為に万人がフックを書いてるのかと思うと...と思った冬のmattnでした。

**Comment by koron** [comment]
つまりダイアログについてはCenterWindowを呼ばなきゃいけない現状がおかしいということね。それは同意。

それはそれとしてCenterWindowの実装がなんか変なのも事実。

実は呼ばなければダイアログは期待する位置に表示されたりして…OSによってはなw

**Comment by mattn** [comment]
MFCのCenterWindowは90ステップもあるのか。置き換えるにしても手数が多くて嫌な感じ。

**Comment by ynkdir** [comment]
CenterWindow()呼び出しなしだと DLGTEMPLATE.[xy] で指定した位置に出ます。

```
gui_w32.c:
3324     add_word(10);       // x
3325     add_word(10);       // y
```

スタイルに DS_CENTER を指定するとオーナーウィンドウのモニタの真ん中に出ます。

オーナーウィンドウの真ん中に出すフラグはないんですねー。

**Comment by k-takata** [comment]
#975 で直っているはず。閉じます。
