### ISSUE TITLE
MinGWで並列コンパイルが失敗する可能性がある

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#1361]
## 不具合の内容

makeを`-j`付きで、並列コンパイルを行うとコンパイルに失敗する場合がある

### 現象・ログ

オブジェクトファイルの依存関係に$(OUTDIR)がないため

```Makefile
$(OUTDIR):
	$(MKDIR) $(OUTDIR)
```

より先に
オブジェクトファイルのコンパイルが実行されエラーになる可能性があります。

```sh
make: Entering directory '/mnt/r/Makeshift/vim/src'
sleep 1; mkdir -p gobjx86-64
x86_64-w64-mingw32-gcc -c -I. -Iproto -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return arabic.c -o gobjx86-64/arabic.o
Assembler messages:
Fatal error: can't create gobjx86-64/arabic.o: No such file or directory
Make_cyg_ming.mak:1139: recipe for target 'gobjx86-64/arabic.o' failed
make: *** [gobjx86-64/arabic.o] Error 2
make: *** Waiting for unfinished jobs....
make: Leaving directory '/mnt/r/Makeshift/vim/src'
```

### 再現手順

WSL上でMinGW-w64を使用する場合

`$(MKDIR) $(OUTDIR)`より先にコンパイルが実行される状態を再現するため
~~Make_cyg_ming.makの`MKDIR`を`sleep 1; mkdir -p`に置き換え、~~
`MKDIR='sleep 1; mkdir -p'`を付け
```sh
make -C src -f Make_ming.mak CROSS_COMPILE=x86_64-w64-mingw32- WINDRES=x86_64-w64-mingw32-windres -j 2 MKDIR='sleep 1; mkdir -p'
```

を実行。

### 期待動作

オブジェクトのコンパイル前に$(OUTDIR)が作られるのが期待動作かと思います

## Vimのバージョン

8.2.1976

## OSの種類/ディストリ/バージョン

*   WSL 1
    *   Windows 10 Pro 64bit (10.0.18363)
    *   Ubuntu-18.04

## 使用している or 関係していそうなプラグイン

なし

## その他

GitHub Actionsを使用し、ubuntu-latest上でMinGW-w64でクロスビルド中にエラーが発生しました。
GitHub Actionsのリソースが2コアなのに、`make -j 6`でビルドしてしまっていたために発生したエラーだとは思いますが、
他の環境でも発生し得るかと思い報告します。

VCでのビルドは試していませんが、
`Make_mvc.mak`は各オブジェクトファイルの依存関係に$(OUTDIR)が入っているようなので、
この現象は起きなさそうです。

**Comment by nocd5** [comment]
GUI=no, GUI=yes, VIMDLL=yes
それぞれの場合でビルドできることを確認

```diff
diff --git a/src/Make_cyg_ming.mak b/src/Make_cyg_ming.mak
index 75021cc..fb60cdb 100644
--- a/src/Make_cyg_ming.mak
+++ b/src/Make_cyg_ming.mak
@@ -1055,13 +1055,19 @@ install.exe: dosinst.c dosinst.h version.h
 uninstall.exe: uninstall.c dosinst.h version.h
 	$(CC) $(CFLAGS) -o uninstall.exe uninstall.c $(LIB) -lole32
 
+$(OBJ): $(OUTDIR)
+
 ifeq ($(VIMDLL),yes)
 $(TARGET): $(OUTDIR) $(OBJ)
 	$(LINK) $(CFLAGS) $(LFLAGS) -o $@ $(OBJ) $(LIB) -lole32 -luuid -lgdi32 $(LUA_LIB) $(MZSCHEME_LIBDIR) $(MZSCHEME_LIB) $(PYTHONLIB) $(PYTHON3LIB) $(RUBYLIB)
 
+$(EXEOBJG): $(OUTDIR)
+
 $(GVIMEXE): $(OUTDIR) $(EXEOBJG) $(VIMDLLBASE).dll
 	$(CC) -L. $(EXELFLAGS) -mwindows -o $@ $(EXEOBJG) -l$(VIMDLLBASE)
 
+$(EXEOBJC): $(OUTDIR)
+
 $(VIMEXE): $(OUTDIR) $(EXEOBJC) $(VIMDLLBASE).dll
 	$(CC) -L. $(EXELFLAGS) -o $@ $(EXEOBJC) -l$(VIMDLLBASE)
 else
@@ -1280,7 +1286,7 @@ $(OUTDIR)/%.o : xdiff/%.c $(XDIFF_DEPS)
 	$(CC) -c $(CFLAGS) $< -o $@
 
 
-$(PATHDEF_SRC): Make_cyg_ming.mak Make_cyg.mak Make_ming.mak
+$(PATHDEF_SRC): $(OUTDIR) Make_cyg_ming.mak Make_cyg.mak Make_ming.mak
 ifneq (sh.exe, $(SHELL))
 	@echo creating $(PATHDEF_SRC)
 	@echo '/* pathdef.c */' > $(PATHDEF_SRC)
```

**Comment by k-takata** [comment]
試してないですが、ぱっと見よさそうに思います。
PR出してはどうでしょうか。

**Comment by nocd5** [comment]
ありがとうございます。PR出してみました。
https://github.com/vim/vim/pull/7287

**Comment by k-takata** [comment]
8.2.1981: https://github.com/vim/vim/commit/8496c9eadbf4ea3bf69e2e01456831eee2bddf0a

**Comment by mattn** [comment]
この変更が入ってから毎回フルビルドが実行される様になったぽいです。

https://github.com/vim/vim/commit/8496c9eadbf4ea3bf69e2e01456831eee2bddf0a#diff-78ae0a7dd81827b3f1436bbc32a15e9fd1ab639d4ad0d1d7177c2b4ebbc23353R1058

この行を抜くと依存関係が戻ってる気がしてます。

**Comment by k-takata** [comment]
雑なレビューですみませんでした。

MSVCだと同じような方法で問題ないので、GNU makeとnmakeでディレクトリのタイムスタンプを見る・見ないなどの違いがあるのだろうかなどと考えています。
`$(OUTDIR)/.dummy` みたいなダミーファイルを作って、それを依存関係に入れるというのはどうでしょうか。

**Comment by k-takata** [comment]
修正案
https://gist.github.com/k-takata/236a3beaf298df2ad979187719ea5d00
(`.dummy` はもうちょっといいファイル名はないだろうか)

**Comment by mattn** [comment]
動作確認しました。よさそげです。 👍

**Comment by nocd5** [comment]
確認不足ですいません、毎回フルビルドが実行されること確認しました。

GNU Makeでは`order-only-prerequisites`という、  
ファイル/ディレクトリが存在しない場合だけ実行する依存関係の指定方法があるようです。

https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html

問題ないか確認中ですが、こちらはどうでしょうか？

```patch
diff --git a/src/Make_cyg_ming.mak b/src/Make_cyg_ming.mak
index 498f34e1f..9e72bff0f 100644
--- a/src/Make_cyg_ming.mak
+++ b/src/Make_cyg_ming.mak
@@ -1055,11 +1055,11 @@ install.exe: dosinst.c dosinst.h version.h
 uninstall.exe: uninstall.c dosinst.h version.h
 	$(CC) $(CFLAGS) -o uninstall.exe uninstall.c $(LIB) -lole32
 
-$(OBJ): $(OUTDIR)
+$(OBJ): | $(OUTDIR)
 
-$(EXEOBJG): $(OUTDIR)
+$(EXEOBJG): | $(OUTDIR)
 
-$(EXEOBJC): $(OUTDIR)
+$(EXEOBJC): | $(OUTDIR)
 
 ifeq ($(VIMDLL),yes)
 $(TARGET): $(OUTDIR) $(OBJ)
```

**Comment by k-takata** [comment]
知らなかった。ドキュメントを見ると、正に今回のような目的のための機能のようですね。

**Comment by mattn** [comment]
こちらの確認 OK でした。

> 2004/01/22 — A new flavor of prerequisites was introduced in GNU make 3.80 called order-only prerequisites.

古いバージョンからあるみたいですし、こちらが良さそうですね。

**Comment by nocd5** [comment]
@mattn @k-takata ご確認頂きありがとうございます。  
もう少し問題ないか確認してからPRを出したいと思います。

- [x] MinGWでのビルド
- [x] MinGW on WSLでのビルド
- [x] 更新のあるファイルだけ再コンパイルされているか
- [x] 並列コンパイル時の問題は解消されているか

pathdef.cの依存関係の修正追加

```patch
diff --git a/src/Make_cyg_ming.mak b/src/Make_cyg_ming.mak
index 498f34e1f..bd9673570 100644
--- a/src/Make_cyg_ming.mak
+++ b/src/Make_cyg_ming.mak
@@ -1055,11 +1055,11 @@ install.exe: dosinst.c dosinst.h version.h
 uninstall.exe: uninstall.c dosinst.h version.h
 	$(CC) $(CFLAGS) -o uninstall.exe uninstall.c $(LIB) -lole32
 
-$(OBJ): $(OUTDIR)
+$(OBJ): | $(OUTDIR)
 
-$(EXEOBJG): $(OUTDIR)
+$(EXEOBJG): | $(OUTDIR)
 
-$(EXEOBJC): $(OUTDIR)
+$(EXEOBJC): | $(OUTDIR)
 
 ifeq ($(VIMDLL),yes)
 $(TARGET): $(OUTDIR) $(OBJ)
@@ -1286,7 +1286,7 @@ $(OUTDIR)/%.o : xdiff/%.c $(XDIFF_DEPS)
 	$(CC) -c $(CFLAGS) $< -o $@
 
 
-$(PATHDEF_SRC): $(OUTDIR) Make_cyg_ming.mak Make_cyg.mak Make_ming.mak
+$(PATHDEF_SRC): Make_cyg_ming.mak Make_cyg.mak Make_ming.mak | $(OUTDIR)
 ifneq (sh.exe, $(SHELL))
 	@echo creating $(PATHDEF_SRC)
 	@echo '/* pathdef.c */' > $(PATHDEF_SRC)

**Comment by k-takata** [comment]
`$(TARGET)`, `$(GVIMEXE)`, `$(VIMEXE)` の依存関係から `$(OUTDIR)` を削除しても良いかもしれないですね。

**Comment by nocd5** [comment]
一通りビルドしてみて問題ないこと確認できたのでPRを出しました。

> 
> 
> `$(TARGET)`, `$(GVIMEXE)`, `$(VIMEXE)` の依存関係から `$(OUTDIR)` を削除しても良いかもしれないですね。

こちらも依存関係の指定が重複しているので不要なこと確認できたので合わせてPRに含めてしまいました。

https://github.com/vim/vim/pull/7311

**Comment by nocd5** [comment]
マージされました、@mattn さん @k-takata さん ありがとうございました。
8.2.1994 https://github.com/vim/vim/commit/c4390fe6c0d1b47b1acd373d7e8ef986412c0600
