### ISSUE TITLE
隠れバッファ読み込み時のメッセージが引き起こす redraw を抑制したい

### ISSUE THREAD

**Issue by obcat** [vim-jp/issues#1363]
## 質問の内容

Vim では任意のファイルを読み込んだとき、そのファイルに関する次のようなメッセージが表示されると思います：

```
"~/xxx.vim" line 48 of 575 --8%-- col 1
```

このメッセージは、隠れバッファを読み込んだときにも表示されますが、
メッセージが表示される直前に redraw 処理のようなものが入り、その前のメッセージがすべて消えてしまいます。

この redraw 処理を抑制する方法はありますでしょうか。

以下、上記挙動の再現手順になります。

### 再現手順

```vim
$ vim -u NONE foo
:set hidden
:autocmd BufLeave * echomsg 'BufLeave!'
:edit bar
" => BufLeave!
" => "bar" [New File]
" => Press ENTER or type command to continue
:bprevious
" => "foo" [New File] --No lines in buffer-- (BufLeave! が表示されない)
```

## Vimのバージョン

8.2.1950

## OSの種類/ディストリ/バージョン

macOS Catalina (バージョン 10.15.7)

## 使用している or 関係していそうなプラグイン

なし

## その他

`shortmess` オプションの `O` フラグが関係してるかと思いましたが、`O` フラグを抜いても変わりませんでした。

```help
O    ファイルの読み込み時のメッセージや Quickfix 関係のメッセージ
     (例えば ":cn") がその前のメッセージを必ず上書きする。
```

**Comment by nb1839** [comment]
:set shortmess=+F ではいかがでしょう？

**Comment by tsuyoshicho** [comment]
```
	  F	コマンドに対する |:silent| のように、ファイルを編集中にファイル
		情報を表示しない。note これは autocommand からのメッセージにも
		影響する
```

効きそうな変りに autocmd BufEnter/BufLeaveにも影響しそうではありますね...(確認はしていない)

**Comment by obcat** [comment]
ありがとうございます。

> :set shortmess=+F ではいかがでしょう？

なるほど、`shortmess+=F` でファイル情報の表示自体を黙らせるということですね。
上記再現手順に `set shortmess+=F` を加えると、たしかに `BufLeave!` が表示されるようになりました。

```vim
$ vim -u NONE foo
:set shortmess+=F
:set hidden
:autocmd BufLeave * echomsg 'BufLeave!'
:edit bar
" => BufLeave!
:bprevious
" => BufLeave!
```

ちなみに、ファイル情報とその前のメッセージを両立させることってできますか...？

**Comment by obcat** [comment]
> 効きそうな変りに autocmd BufEnter/BufLeaveにも影響しそうではありますね...

私もそう思ったのですが、再現手順に `set shortmess+=F` を加えても上記の通り `BufLeave!` は表示されますね。よくわからない...

あと色々試していて気がついたのですが、隠れファイルを読み込むときだけファイル情報が表示されるタイミングが他と違います：

```
== nohidden ==   == hidden ==
BufLeave         BufLeave
BufWinLeave      BufWinLeave
BufUnload        BufHidden
BufReadPre       -
[file info]      -
BufReadPost      -
BufEnter         BufEnter
BufWinEnter      BufWinEnter
-                [file info]
```

仮に仕様だとしても一貫性がなくて気持ち悪いような...

**Comment by nb1839** [comment]
> ちなみに、ファイル情報とその前のメッセージを両立させることってできますか...？

ちょっと処理を追っかけてみましたが `:bp` の方では素の設定などで両立させることはちょっと難しそうです。
そちらの方で試された結果が丁度いいのでそれを使いますが、

* nohidden ではバッファ切り替え時にファイルが読み込まれ、その読み込み処理の中で [file info] が出力される。

```
== nohidden ==
BufLeave
BufWinLeave
BufUnload       <---- nohidden なので unload される。
BufReadPre      <---+
[file info]         | ファイル読み込み
BufReadPost     <---+
BufEnter
BufWinEnter
-
```

* hidden ではバッファを切り替えるだけ。[file info] だけ次の再描画の際に合わせて出力する。

```
== hidden ==
BufLeave
BufWinLeave
BufHidden       <---- hidden するだけ
-               <---+ 
-                   | hidden のバッファを表に出すだけなのでなにもしない。
-               <---+ [file info] は次の再描画の際についでに出力するようにフラグを立てるだけ。
BufEnter                            | 
BufWinEnter                         |
                                    |
(これ以降は :bp とは別の共通処理)   |
                                    |
[file info]     <-------------------+
```

という感じで [file info] の出力タイミングが全く違うので、元の質問でおっしゃっていた通り
redraw が絡むとその前のメッセージは消されてしまうようです。

(ファイル書き込み/ファイル読み込みのタイミングではないため、shortmess の o やら O の制御外となっている模様)

補足: なのでやるとしたら shortmess+=F としておいて、BufEnter あたりで自前でファイル情報を出力するとか小技が必要なるかも？といったところでしょうか。

**Comment by obcat** [comment]
わー、処理まで追っていただいてありがとうございます。

つまり隠れファイルのファイル情報の出力が redraw を引き起こすわけではなく、
それを表示するタイミングが redraw のあとに設定されているということなんですね。

> shortmess+=F としておいて、BufEnter あたりで自前でファイル情報を出力するとか小技が必要なるかも？といったところでしょうか

`file` コマンドを使って試してみたところ、たしかに両立できました。

```vim
$ vim -u NONE
:set shortmess+=F
:set hidden
:autocmd BufLeave * echomsg 'BufLeave!'
:autocmd BufEnter * file
:edit bar
" => BufLeave!
" => "bar" [New File] --No lines in buffer--
" => Press ENTER or type command to continue
:bprevious
" => BufLeave!
" => "foo" [New File] --No lines in buffer--
" => Press ENTER or type command to continue
```

この結果と、調べていただいた、

> [file info] は次の再描画の際についでに出力する

という情報を合わせて考えると、`shortmess+=F` は隠れファイル表示後の redraw も抑制する、ということになるんでしょうか（仮に redraw されていたらすべてのメッセージが消されてしまっているはず...？）
難しい...

ともあれ、素の設定ではこれらのメッセージを両立する手段がない/なさそうだということが分かってよかったです。

またこの挙動はちょっと不便な感じもするので、情報が整理できたら本家 repo に issue を立てようかなと思います (立てたらこちらの issue にコメントします）。

ご回答いただきありがとうございました。
