### ISSUE TITLE
Windows版のgvim.exeで上書き保存するとNTFSの拡張属性(extended attribute)が消えてしまう

### ISSUE THREAD

**Issue by entosen** [vim-jp/issues#1364]
## 不具合の内容

Windows版のgvim.exeで上書き保存するとNTFSの拡張属性(extended attribute)が消えてしまう

### 現象・ログ

Windows 10 で WSL1 で Ubuntu を使っています。
WSL側からWindows側ファイル(c:など、/mnt/c/にマウントされている)を見た場合のファイルパーミッションは、
マウントオプションで `option=metadata` をつけた場合は、NTFSの拡張属性(extended attribute) 内に保存されます。
https://docs.microsoft.com/ja-jp/windows/wsl/file-permissions

WSL内でchmodするとWSL側で見えるパーミッションが変更されますが、
Windows側の gvim.exe で上書き保存するとパーミッションが 777 に戻ってしまいます。
gvim.exeの設定では backupcopy=yes にしています。

### 再現手順

Windows側vimの設定で backupcopy=yes にしておく

WSL1の環境を用意する。/etc/wsl.conf に以下の様に metadata オプションを有効にする
```
[automount]
options = "metadata"
```
WSL1再起動

```
(Windows側) gvim.exeで適当なファイルを新規作成・保存 (foo.txt とします)

(WSL側) ls -li foo.txt
88946092640572611 -rwxrwxrwx 1 MYNAME MYNAME 14457 Jan 22 01:16 foo.txt*

(WSL側) chmod 644 foo.txt
(WSL側) ls -li foo.txt
88946092640572611 -rw-r--r-- 1 MYNAME MYNAME 14457 Jan 22 01:16 foo.txt

(Windows側) gvim.exe で foo.txt を開いて上書き保存

(WSL側) ls -li foo.txt
88946092640572611 -rwxrwxrwx 1 MYNAME MYNAME 14457 Jan 22 01:19 foo.txt*
↑パーミッションが777に戻ってしまう。
```

ちなみに同様のことを gvim.exe ではなく、メモ帳でやるとパーミッションは保持されます。

### 期待動作

Windows側の gvim.exe で上書き保存しても、NTFSの拡張属性が維持される。WSL側でつけたパーミッションが維持される。

## Vimのバージョン

vim82-kaoriya-win64-8.2.1287-20200724.zip

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit (1909, 18363.1256)

## 使用している or 関係していそうなプラグイン

特になし

**Comment by entosen** [comment]
active disk editor というソフトで、NTFSのメタ情報を見た際のキャプチャです。
(厳密には上とは別ファイルですが同様の挙動のときのものです。)

■gvimで保存する前
左カラムに `Attribute $D0`, `Attribute $E0` が存在する。
データの中に `$LXMOD` と 100644 (`4A 81`) があるのが見えます。
![gvimで保存する前](https://user-images.githubusercontent.com/10959822/105381686-9dd52f80-5c52-11eb-9305-74607d55424d.png)

■gvimで保存した後
左カラムの `Attribute $D0`, `Attribute $E0` が消えてしまった。
![gvimで保存した後](https://user-images.githubusercontent.com/10959822/105381719-a594d400-5c52-11eb-83b8-28d39cfbd326.png)

**Comment by k-takata** [comment]
backupcopy=yes の処理が間違っているような気がします。

```diff
--- a/src/bufwrite.c
+++ b/src/bufwrite.c
@@ -1497,6 +1497,9 @@ buf_write(
 #if defined(HAVE_SELINUX) || defined(HAVE_SMACK)
 			mch_copy_sec(fname, backup);
 #endif
+#ifdef MSWIN
+			(void)mch_copy_file_attribute(fname, backup);
+#endif
 			break;
 		    }
 		}
@@ -1909,12 +1912,7 @@ restore_backup:
 
 #if defined(MSWIN)
 	    if (backup != NULL && overwriting && !append)
-	    {
-		if (backup_copy)
-		    (void)mch_copy_file_attribute(wfname, backup);
-		else
-		    (void)mch_copy_file_attribute(backup, wfname);
-	    }
+		(void)mch_copy_file_attribute(backup, wfname);
 
 	    if (!overwriting && !append)
 	    {
```

**Comment by entosen** [comment]
backupdir=. として、backupcopy yes no の両方の場合でパーミッションの変化を調べました。

```
set backupdir=.
set backupcopy=yes

# ファイル新規作成し、一度vimで保存
% ls -li
45598946227128127 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 22:54 foo.txt*
24488322973913775 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 22:54 foo.txt~*

% chmod 644 foo.txt ; chmod 600 'foo.txt~'
% ls -li
45598946227128127 -rw-r--r-- 1 MYANME MYANME 14457 Jan 22 22:54 foo.txt
24488322973913775 -rw------- 1 MYANME MYANME 14457 Jan 22 22:54 foo.txt~

# もう一度、vimで上書き保存
% ls -li
45598946227128127 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 22:57 foo.txt*
23925373020469110 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 22:57 foo.txt~*
```

```
set backupdir=.
set backupcopy=no

# ファイル新規作成し、一度vimで保存
28147497671152823 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 23:00 foo.txt*
35465847065582278 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 22:57 foo.txt~*

% chmod 644 foo.txt ; chmod 600 'foo.txt~'
% ls -li
28147497671152823 -rw-r--r-- 1 MYANME MYANME 14457 Jan 22 23:00 foo.txt
35465847065582278 -rw------- 1 MYANME MYANME 14457 Jan 22 22:57 foo.txt~

# もう一度、vimで上書き保存
% ls -li
35747322042292934 -rwxrwxrwx 1 MYANME MYANME 14457 Jan 22 23:02 foo.txt*
28147497671152823 -rw-r--r-- 1 MYANME MYANME 14457 Jan 22 23:00 foo.txt~
```

**Comment by entosen** [comment]
nobackup, nowritebackup のときも同様になるみたいです。
```
nobackup, nowritebackup
backupcopy=yes
backupdir=.

51228445761403708 -rwxrwxrwx 1 MYNAME MYNAME 14457 Jan 23 13:21 foo.txt*
chmod 644 foo.txt
51228445761403708 -rw-r--r-- 1 MYNAME MYNAME 14457 Jan 23 13:21 foo.txt
gvim.exe で保存
51228445761403708 -rwxrwxrwx 1 MYNAME MYNAME 14457 Jan 23 13:22 foo.txt*

nobackup, nowritebackup
backupcopy=no
backupdir=.

51228445761403708 -rwxrwxrwx 1 MYNAME MYNAME 14457 Jan 23 13:22 foo.txt*
chmod 644 foo.txt
51228445761403708 -rw-r--r-- 1 MYNAME MYNAME 14457 Jan 23 13:22 foo.txt
gvim.exe で保存
51228445761403708 -rwxrwxrwx 1 MYNAME MYNAME 14457 Jan 23 13:25 foo.txt*

```

**Comment by k-takata** [comment]
うーむ、EAってADSの一部として保存されているのかと思ったら別物なのか。

https://github.com/jschicht/EaTools
これを見ると、NtQueryEaFile() とか NtSetEaFile() とかを使ってコピーすることになるのか？

**Comment by entosen** [comment]
backupcopy=no の場合は、実質mvして新規作成なので、
inode(Windowsでの呼び方がちょっとわぁりませんが)も変わるし、EAがなくなってもしようがないかと思います。
backupcopy=yesの場合は、既存のファイルをtrancateして書くだけで、inodeも変わらないので、普通は属性はキープされると思うのですがそうはなっていないみたいですね。

MSYS2 + MinGW で、
buf_write の冒頭に下記コードを仕込んで試してみましたが、これでもEAなくなってしまいました。
O_TRANC で消えてしまっているように見えます。
```
    {
	char_u fname2[] = "C:\\Users\\MYNAME\\home\\tmp\\aaa\\test.txt";
	int fd2;
	fd2 = mch_open((char *)fname2, O_WRONLY |  
		                (O_CREAT | O_TRANC)
				, 0600);
	close(fd2);
    }
```

**Comment by entosen** [comment]
WSL の permission の扱いの詳しいことがここに書いてありました。
- Chmod/Chown WSL Improvements | Windows Command Line
https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/

この中で、
> Important Caveats
> 1. Editing a file using a Windows editor may remove the file’s Linux metadata. In this case, the file will revert to its default permissions

とあるので、Windows側アプリの開き方によってmetadataが消えるかどうかあるみたいです。

VSCodeで似たようなissueが出ているのも見つけました。
- Do not reset WSL permissions metadata on save · Issue #49021 · microsoft/vscode
https://github.com/microsoft/vscode/issues/49021
- Use 'r+' with truncation when saving existing files on Windows by seishun · Pull Request #42899 · microsoft/vscode
https://github.com/microsoft/vscode/pull/42899

どうやら open 時に O_TRUNC を付けると消えてしまうようです。
O_TRANC をなくして、_chsize してみたら、これなら EA 保持されるみたいです。
```
    {
	char_u fname2[] = "C:\\Users\\hiroyuki\\home\\tmp\\aaa\\test.txt";
	int fd2;
	fd2 = mch_open((char *)fname2, O_WRONLY |  
		                (O_CREAT)
				, 0600);
	_chsize(fd2, 0);

	close(fd2);
    }
```

**Comment by entosen** [comment]
WSL の permission の扱いの詳しいことがここに書いてありました。
- Chmod/Chown WSL Improvements | Windows Command Line
https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/

この中で、
> Important Caveats
> 1. Editing a file using a Windows editor may remove the file’s Linux metadata. In this case, the file will revert to its default permissions

とあるので、Windows側アプリの開き方によってmetadataが消えるかどうかあるみたいです。

VSCodeで似たようなissueが出ているのも見つけました。
- Do not reset WSL permissions metadata on save · Issue #49021 · microsoft/vscode
https://github.com/microsoft/vscode/issues/49021
- Use 'r+' with truncation when saving existing files on Windows by seishun · Pull Request #42899 · microsoft/vscode
https://github.com/microsoft/vscode/pull/42899

どうやら open 時に O_TRUNC を付けると消えてしまうようです。
O_TRANC をなくして、_chsize してみたら、これなら EA 保持されるみたいです。
```
    {
	char_u fname2[] = "C:\\Users\\MYNAME\\home\\tmp\\aaa\\test.txt";
	int fd2;
	fd2 = mch_open((char *)fname2, O_WRONLY |  
		                (O_CREAT)
				, 0600);
	_chsize(fd2, 0);

	close(fd2);
    }
```

**Comment by k-takata** [comment]
PRed: https://github.com/vim/vim/pull/7765

**Comment by k-takata** [comment]
8.2.2451: https://github.com/vim/vim/commit/e7bebc495d4014d7bc81f863939c35268cb8e97d
8.2.2450: https://github.com/vim/vim/commit/7781ebe50f6d4daba02be3bd7e6ca08cd459674b
