### ISSUE TITLE
Travis CIが一時的に無効になっている？

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#1371]
## 質問の内容

[vim-jp/syntax-vim-ex](https://github.com/vim-jp/syntax-vim-ex)のgeneratorブランチをcommit&pushするとTravis CIがキックされてmasterブランチが更新されるようになっているのですが、ここ最近のcommit&pushでTravis CIがキックされていない事に気づきました。

[master](https://github.com/vim-jp/syntax-vim-ex/commits/master)の最後の(Travis CIによる)commitは `Feb 16, 2021` ですが、[generator](https://github.com/vim-jp/syntax-vim-ex/commits/generator)にはそれ以降にも `Mar 25, 2021` と `Mar 31, 2021` にcommitしているのです。

[vim-jp OrganisationのTravis CI](https://www.travis-ci.com/organizations/vim-jp/plan)を確認すると、ページ上部に以下の文言が表示されました。

```
Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance.
意訳: (クレジット残高がマイナスであるため、プライベートリポジトリとパブリックリポジトリのビルドが一時的に無効になっています。 プランページに移動して、クレジット残高を補充してください。)
```

- PlanタブのCredits
```
0 available credits (purchase date: March 31, 2021)
You have used 10000 of 10000 credits
```

- PlanタブのOSS only credits
```
0 available credits (next replenish date: March 31, 2021)
You have used 0 of your 0 monthly credits
```

## 知りたいこと

これは `March 31, 2021` を過ぎたら解消されるのでしょうか？
それとも、何か修正が必要？

**Comment by k-takata** [comment]
明日になれば解消されると期待していますが、ふと気になって vimdoc-en を見たら1カ月以上前から止まっていました。全面的に GitHub Actions へ移行することも検討した方がいいかもしれませんね。

**Comment by ichizok** [comment]
クレジットは自動で回復しないので、引き続きTravis-CIを利用する場合は (Free以外のプランで) クレジットを補充する必要があります。

**Comment by tsuyoshicho** [comment]
syntax-vim-ex については、トライアルのGitHub workflowを作ってみました、後程PRします。

---

https://github.com/vim-jp/syntax-vim-ex/pull/23 and https://github.com/vim-jp/syntax-vim-ex/pull/24

---

result
https://github.com/tsuyoshicho/syntax-vim-ex/commit/5581eabd5fbbae111652633fba96c4f81749f179

**Comment by h-east** [comment]
@k-takata 今確認しましたがだめですね。

@ichizok えー！マジですか！？
Freeプランのままじゃ使えなくなるというアナウンスって事前におこなわれていたんでしょうか？
私的には不意に来たのでびっくりしました。
vim-jpの(私が関わっていない)他プロジェクトでは気付いてたんでしょうか？
(さすがに私が第1発見者ではないですよね)

@tsuyoshicho おぉ！ありがとうございます。内容を確認します。

**Comment by tsuyoshicho** [comment]
なにか話題はあった気がするけど、いつのまにやら忘れられてた気がする...

**Comment by ichizok** [comment]
通知自体は 2020/11/20 にあったようです。
https://qiita.com/TomoyukiAota/items/42987f1d20f06abb3b3c

**Comment by tsuyoshicho** [comment]
追加情報: vital.vim の GitHub workflow への変更はここに作ってあります。 https://github.com/vim-jp/vital.vim/pull/701

**Comment by h-east** [comment]
vim-jp/syntax-vim-ex が @tsuyoshicho さんのPRをmergeしてGitHub workflowでうまく動いています。:+1:

以下のプロジェクトもGitHub workflowに移行する必要がありますね。
https://github.com/vim-jp/vimdoc-ja-working
https://github.com/vim-jp/vimdoc-en
https://github.com/vim-jp/lang-ja

**Comment by tsuyoshicho** [comment]
vimdoc-ja-workingでnvcheck/tagのチェックをする奴は出してましたね。(忘れてた)
https://github.com/vim-jp/vimdoc-ja-working/pull/834

vimdoc generatorなやつが問題だな...

**Comment by tsuyoshicho** [comment]
vimdoc-ja の 更新を行うようにする PR を作成しました。
https://github.com/vim-jp/vimdoc-ja-working/pull/901

**Comment by tsuyoshicho** [comment]
vimdoc-en の更新を行う PR
https://github.com/vim-jp/vimdoc-en/pull/15

**Comment by tsuyoshicho** [comment]
syntax-vim-ex をもうちょっとだけ良くするPRも作成 https://github.com/vim-jp/syntax-vim-ex/pull/25
そういえば、merge requirement がTravis CIのままになっている様子...

**Comment by k-takata** [comment]
> そういえば、merge requirement がTravis CIのままになっている様子...

とりあえず解除。GHAはまだ選択できませんでした。

**Comment by tsuyoshicho** [comment]
ここらへんのCIはPRに対してなにかをチェックする項目的なものは、Travisの時点で実質ない様子でした。
なのでGitHub workflowとしてpull_requestをターゲットとして作っていませんし、選択肢に出ないと思われます。

Travisのは実装都合か、全ブランチ、全PRをチェックはすることになったので、結果として選択肢になってたのだと思われます。

**Comment by tsuyoshicho** [comment]
lang-ja を GHA化するPR
https://github.com/vim-jp/lang-ja/pull/132

**Comment by tsuyoshicho** [comment]
上にあがっている3件について、とりあえず動くといえるものが入ったので、このissueとしてはcloseでしょうか?
@h-east さん @k-takata さん

**Comment by k-takata** [comment]
> > そういえば、merge requirement がTravis CIのままになっている様子...
> 
> とりあえず解除。GHAはまだ選択できませんでした。

選択できるようになっていました。
"Check tag name conflict" と "runner / nvcheck" を有効にしておけばいいかな。

**Comment by k-takata** [comment]
Webhooks も Travis CI を外しておくか。

**Comment by k-takata** [comment]
syntax-vim-ex, vimdoc-en, vimdoc-ja-working, lang-ja の Travis CI の Webhook は、Active のチェックを外しておきました。

**Comment by k-takata** [comment]
> "Check tag name conflict" と "runner / nvcheck" を有効にしておけばいいかな。

有効にしてしまうと、作成済みの PR がブロックされてしまうなぁ。(admin権限でマージすることは可能だけど)

**Comment by h-east** [comment]
@tsuyoshicho 
> このissueとしてはcloseでしょうか?

そうですね。
ほぼ、 @tsuyoshicho さん任せになっちゃいましたね:grin:。ありがとうございます。

**Comment by tsuyoshicho** [comment]
1点連絡
vimdoc-enの周期動作ですが、actionタブで初回確認をしないと動かないかと思われます。(動いてないっぽい)

確認お願いします
@h-east さん /@k-takata さん

**Comment by k-takata** [comment]
ん？動いているように見えますが。
https://github.com/vim-jp/vimdoc-en/actions

**Comment by tsuyoshicho** [comment]
あれ…すみません勘違いでした。お騒がせしました。

**Comment by k-takata** [comment]
まだ課題もあるかもしれませんが、一旦閉じます。
対応ありがとうございました。
