### ISSUE TITLE
~/.vim/pack/*/opt で管理しているプラグインの反映方法

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1372]
## 質問の内容
\~/.vim/pack/*/opt に有るプラグインを packadd しても、実行したバッファで反映されません
どの様な方法で反映させるのが望ましいでしょうか?

\~/.vimrc も \~/.vim/vimrc もない

\~/.vim
　　└ pack
　　　　└ github
　　　　　　└ opt
　　　　　　　　└ vim-ft-vim_fold

といった構成で、
> vim +'set foldcolumn=3 | packadd vim-ft-vim_fold | e ~/.vim/pack/github/opt/vim-ft-vim_fold/ftplugin/vim_fold.vim'

と packadd の後に読み込んだファイルは良いのですが、
> vim ~/.vim/pack/github/opt/vim-ft-vim_fold/ftplugin/vim_fold.vim +'set foldcolumn=3 | packadd vim-ft-vim_fold'

と先にファイルを読み込んだ後で packadd すると、先に読み込んでいたファイルには反映されません

当たり前といえばそうなのですが、\~/.vim/vimrc 等で
```
function s:set_vim_ft_vim_fold()
	packadd vim-ft-vim_fold
endfunction
augroup loadVimFold
	autocmd!
	autocmd FileType vim call s:set_vim_ft_vim_fold()
augroup END
```
といった管理をさせたい時に、どんな処理を追加すればよいか教えていただければ幸いです

この vim-ft-vim_fold に関しては、再度 setfiletyp を使えば反映されるところまでは解ったのですが、vim-lsp などそれで上手く行かないケースもあり、汎用性の有る方法が教えて頂きたいです
## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 11 2020 17:00:59)
> 適用済パッチ: 1-716
> Modified by team+vim@tracker.debian.org
> Compiled by team+vim@tracker.debian.org
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)
## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.10
> Release:	20.10
> Codename:	groovy
> $ uname -a
> Linux xxx 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Shougo** [comment]
プラグインマネージャーの設計者として回答します。

> この vim-ft-vim_fold に関しては、再度 setfiletyp を使えば反映されるところまで
> は解ったのですが、vim-lsp などそれで上手く行かないケースもあり、汎用性の有る
> 方法が教えて頂きたいです

setfiletype で再度セットするで正しいです。プラグインマネージャーはなんのために
あるかというと、このようなややこしい処理を自動でやるためにあるのです。
package の仕組みはあくまでプラグインマネージャーを構築するための基本的な枠組み
を提供するものであって、細かい処理は package の機能の外で実装する必要があるので
す。

vim-lsp だとうまくいかないことについてですが、残念ながら、プラグインによって仕
様が異なるので遅延起動に銀の弾丸はありません。私もプラグインの仕様を確認しなが
ら試行錯誤してプラグインの遅延起動を設定しています。そのような手間をかけたくな
いのなら、遅延起動を設定しないほうがよいです。

vim-lsp だとおそらく、FileType の処理以外にもロードが必要になるのではないかと思いますね。

プラグインの設定を完璧に遅延起動させたいなら、素の package を使うより dein.vim を使うことを推奨します。
ただし完璧に遅延起動を設定できるかわりに、その設定は他のプラグインマネージャーより難しいです。
dein.vim を使っていても遅延起動を設定しない人も数多くいます。

そもそも、`:packadd` とはなにかというと、'runtimepath'にプラグインのパスを追加する処理です。
プラグインのパスを追加するだけではプラグインはロードされません。
setfiletype で動くようになるのは、再度ファイルタイプをセットすることで Vim が
filetype のプラグインを再度読み込むためです。

**Comment by Shougo** [comment]
プラグインマネージャーを使わずに Vim の package 機能で頑張るのも問題ないと思いますが、
その場合 package 機能というパッケージマネージャーを使っているのではなく、
「package 機能を用いて自分のプラグインマネージャーを自作している」のだという気持ちでいてください。
それだけ package 機能は原始的なのです。

**Comment by machakann** [comment]
ftplugin 以下のファイルはファイルタイプが設定されるまで読み込まれない、という本来的な遅延読み込みの仕組みなので、opt 以下に入れる必要はないと思います。（むしろ、自分で自動コマンドを設定している分、二度手間かと）安心して start 以下に移すのがよいと思います。

**Comment by iranoan** [comment]
FileTypeに関するのは、setfiletypeを再度実行がセオリーなんですね
今回試してみて、dein.vimの偉大さを改めて思い知りました

ファイルタイプ依存は、starに移すのが素直なんでしょうね

とにかく標準的なやり方が解りました
有難う御座いました

**Comment by Shougo** [comment]
ftpluginだけのプラグインなら遅延は必要ありませんが、ものによってはpluginディレクトリを持っていてそれは遅延して読み込まれないので、これを遅延するならプラグインマネージャーの助けが必要になります
