### ISSUE TITLE
popup_??? 関数の filterオプションで指定する関数の作り方を教えてください

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1373]
## 質問の内容
popup_??? の各種関数で、filter オプションが使えます
特定のキーが押された時はポップアップを閉じ、それ以外は無視する filter 関数を作りたいのですが、どうすればよいのでしょう?

```
function! s:popup() abort
  call popup_atcursor('text', {'filter': function('s:close_popup')})
endfunction

function! s:close_popup(id, key) abort
  if a:key ==? 'x' || a:key ==? 'q' || a:key ==? 'c' || a:key ==? 'p'
    call popup_close(a:id)
    return 1
  endif
  return 0
endfunction

command! POPUP call s:popup()
nnoremap <silent><buffer>p :POPUP<CR>
```

といった関数だと、p をタイプした時にポップアップを閉じることはできるのですが、
> E492: エディタのコマンドではありません: OPUP

とエラーが出てしまいます
## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 15 2021 12:29:39)
> 適用済パッチ: 1-2434

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 21.04
> Release:	21.04
> Codename:	hirsute
> $ uname -a
> Linux xxx 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## 使用している or 関係していそうなプラグイン
~/.vim をリネームしても同じでした

**Comment by skanehira** [comment]
キーマップが適用されているので、 `mapping` を false にしてあげるとエラーがなくなります。

```vim
  call popup_atcursor('text', {'filter': function('s:close_popup'), 'mapping': 0})
```

詳細はヘルプの popup_create-arguments の以下の部分を参照してみてください

```
	mapping		キーマッピングを許可する。FALSEで、かつポップアップが
			表示され、フィルターコールバックがある場合、キーマッピ
			ングは無効になっている。 デフォルト値はTRUEである。
```

**Comment by iranoan** [comment]
一通りオプションについて読んだはずなのですが、このオプションを読み落としていました
どうもありがとうございます
