### ISSUE TITLE
:Man コマンドについて

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1378]
## 質問の内容
\~/.vimrc や \~/.vim/vimrc
に
`runtime ftplugin/man.vim`
を記載しておけば、マニュアル・ページ読み込み前から
:Man {name}
ができます

しかし \~/.vim/ftplugin/man.vim
が存在すると、中身が空であっても Man コマンドが使えなくなります

これは仕様なのでしょうか?
また、なぜこのようなことが起きるのでしょうか?
## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 15 2021 12:29:39)

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 21.04
> Release:	21.04
> Codename:	hirsute
> $ uname -a
> Linux xxxxi 5.11.0-34-generic #36-Ubuntu SMP Thu Aug 26 19:22:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thinca** [comment]
`:runtime` コマンドは `runtimepath`(`$PATH` みたいにディレクトリが列挙してあるオプション) の中から該当ファイルを探し、最初に見つかったファイルを読み込みます。`ftplugin/man.vim` は Vim 本体の runtimepath に用意されているものですが、ユーザー用の `~/.vim` の方が優先度が高いため、`~/.vim/ftplugin/man.vim` が存在する場合は先にこちらが読まれるため指摘された問題が起きます。

このような挙動なので、仕様ということになると思います。

回避策ですが、`:runtimepath!` のように `!` を付けると、見つかったファイルをすべて読みこんでくれるので、`:Man` が使えるようになると思います。

**Comment by iranoan** [comment]
なるほど
\~/.vim/ftplugin/man.vim が先に見つかってしまうので、本体で用意されている ftplugin/man.vim が読み込まれないんですね

ありがとうございました
