### ISSUE TITLE
Vim Script Licenseについて

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#138]
https://groups.google.com/d/topic/vim_dev/U_uA9o416wo/discussion

このスレッドで話されている話題について。
何人かが既に署名（？）してますが、Vim同梱の配布物について、今は作者ライセンスになってる物を扱いやすくする為に`Vim Script License`にしようという動き。
以下、署名のテンプレート

https://groups.google.com/d/msg/vim_dev/U_uA9o416wo/Bx80w-vQbgwJ

またそれに付随して`ca.po`に署名した人も。

https://groups.google.com/d/topic/vim_dev/f-trr_k85FM/discussion

これになぞって日本Vimチームもそうすべきかと思いました。現在Vimに同梱されている配布物で、私達が関係しそうなのは。

koronさん担当の配布物

```
runtime/lang/ja/LC_MESSAGES/ja.po
runtime/lang/ja/LC_MESSAGES/ja.sjis.po (ja.poからの変換物)
runtime/lang/menu_ja.cp932.vim (utf-8のコピー？)
runtime/lang/menu_ja.euc-jp.vim (utf-8のコピー？)
runtime/lang/menu_ja.eucjp.vim (utf-8のコピー？)
runtime/lang/menu_ja.ujis.vim (utf-8のコピー？)
runtime/lang/menu_ja_jp.cp932.vim (utf-8のコピー？)
runtime/lang/menu_ja_jp.euc-jp.vim (utf-8のコピー？)
runtime/lang/menu_ja_jp.eucjp.vim (utf-8のコピー？)
runtime/lang/menu_ja_jp.ujis.vim (utf-8のコピー？)
runtime/lang/menu_ja_jp.utf-8.vim (utf-8のコピー？)
runtime/lang/menu_japanese_japan.932.vim (utf-8のコピー？)
src/dehqx.py
src/po/ja.po
src/po/ja.sjis.po (ja.poからの変換物）
```

mattnのはこれだけ

```
runtime/colors/shine.vim
```

また、これを期に

```
runtime/doc/mbyte.txt
runtime/doc/mlang.txt
```

を直してしまいたいという思いもある。(これは別issueか)

@koron どうします？

**Comment by koron** [comment]
そもそも寄贈したつもりなので基本的には賛成だけど、GPL3互換だったらちょっとイヤかも。
src/dehqx.py ってなんだか一瞬わからなかったけど、たぶん昔Macがらみで使ったんだな…すっかり忘れてた。

具体的に署名ってなにすんの?

ところでVim ScriptでないものもVim Script Licenseなの?w

**Comment by koron** [comment]
```
# Copyright (C) 2003-2012 Ernest Adrogué <eadrogue@gmx.net>.
# This file is distributed under the Vim License.
```

こんなんついてた。私の分は後日、まとめて書き加えて送ります。

**Comment by mattn** [comment]
書き換えなくともファイル一覧を添えてvim_devに上記ライセンス文付けて送ればそれで良さそうな気もする。

**Comment by koron** [comment]
どのみちそろそろ翻訳ファイルは見直さなきゃいけなかったので。

**Comment by koron** [comment]
ところでmbyteとmlangって何をしたいの?

**Comment by mattn** [comment]
メールアドレスを直したいっす

**Comment by koron** [comment]
mbyteのメアドの件は了解。新しいアドレスに変えたい、とかでパッチ作ればOKでしょう。

でmlangは?

**Comment by mattn** [comment]
mlangはデマだった

**Comment by mattn** [comment]
良く考えたらtutorも僕だった。

**Comment by mattn** [comment]
再ライセンス完了

https://groups.google.com/d/topic/vim_dev/xnDhv3lTr54/discussion

**Comment by koron** [comment]
あ～sourceしているだけのファイルもライセンスつけたほうが良いか。

**Comment by koron** [comment]
とりあえず送信終わった。

**Comment by koron** [comment]
翻訳ファイルの変更はtodo listに入ったはずなので閉じます。

**Comment by k-takata** [comment]
7.3.600直後のコミットで修正されていますので、タグを `fixed` に変えておきます。
http://code.google.com/p/vim/source/detail?r=11d40fc82f1154673baca2327796f5152b0df6f5
