### ISSUE TITLE
set や setlocal でオプションを変更すると curswant がリセットされる場合がある

### ISSUE THREAD

**Issue by siaa4fu** [vim-jp/issues#1381]
### 現象・ログ

カーソルの上下移動の際に使われる curswant ですが、 `set` や `setlocal` でオプションを変更するとリセットされることがあります

(curswant については `setpos` や `winrestview` のヘルプを読みました)

### 再現手順

```
gvim.exe -u NONE -U NONE -c "call winrestview({'curswant': 10})" -c "echo getcurpos()" -c "set number&" -c "echo getcurpos()"
```

実行しているコマンドは以下です

```vim
call winrestview({'curswant': 10})
echo getcurpos()
set number&
echo getcurpos()
```

ここでは `number` を `:set-&` しましたが、 `set number` や `set nonumber` でもリセットされました。  
また、 `relativenumber` や `wrap` 等でもリセットされました。

ただし、どんなオプションでもリセットされるわけではないようです。

### 期待動作

再現手順の例で言うと、

```
[0, 1, 1, 0, 11]
[0, 1, 1, 0, 1]
```

と echo 表示されますが

```
[0, 1, 1, 0, 11]
[0, 1, 1, 0, 11]
```

となるのが正しいと思います

## Vimのバージョン

8.2.3565

## OSの種類/ディストリ/バージョン

Windows 10 Home 64bit 21H1 (19043.1288)

## 使用している or 関係していそうなプラグイン

特になし

## その他

\#1219 で報告されている内容が似ているように思いました

**Comment by h-east** [comment]
set_bool_option() の最後辺りの以下の判定が真になると`curswant`が更新されるようです。
```c
    if (curwin->w_curswant != MAXCOL
		     && (options[opt_idx].flags & (P_CURSWANT | P_RALL)) != 0)
	curwin->w_set_curswant = TRUE;
```

つまり、現状では、optionのflagsに P_CURSWANT, P_RWIN, P_RBUF または P_RALL が指定されているものは`curswant`が更新される仕様のようです。

PS
option[] の定義は optiondefs.h の323～3060行にあります。
`number`オプションはflagsに P_RWIN が指定されているので`curswant`が更新されます。1823行目)

PS2
一度は`kind/bug`ラベルをつけさせてもらいましたが、ソースコードを調査した結果、仕様の可能性が濃くなったためラベルを外させてもらいますね。

**Comment by siaa4fu** [comment]
現状で仕様となっていること、及び curswant が更新される仕組みが分かりスッキリ致しました。

個人的に `relativenumber` を `CursorHold` 等でオンオフしていて curswant が変わることに気付きました。  
ただし、どういったオプションを変更したときに変わるのかは見当も付きませんでしたので、見るべき場所を教えていただきありがとうございました。

---

せっかくなので optiondefs.h から curswant が変更されるオプションを抜き出してみました (抜けがあったらすいません) 。

`P_BOOL` または `P_NUM` であり、かつ `P_RWIN` `P_RBUF` `P_RALL` `P_RCLR` のいずれかを持つものです。

```
breakindent     P_BOOL|P_VI_DEF|P_VIM|P_RWIN
cmdheight       P_NUM|P_VI_DEF|P_RALL
columns         P_NUM|P_NODEFAULT|P_NO_MKRC|P_VI_DEF|P_RCLR
compatible      P_BOOL|P_RALL
conceallevel    P_NUM|P_RWIN|P_VI_DEF
diff            P_BOOL|P_VI_DEF|P_RWIN|P_NOGLOB
emoji           P_BOOL|P_VI_DEF|P_RCLR
equalalways     P_BOOL|P_VI_DEF|P_RALL
foldcolumn      P_NUM|P_VI_DEF|P_RWIN
foldenable      P_BOOL|P_VI_DEF|P_RWIN
foldlevel       P_NUM|P_VI_DEF|P_RWIN
foldminlines    P_NUM|P_VI_DEF|P_RWIN
foldnestmax     P_NUM|P_VI_DEF|P_RWIN
hlsearch        P_BOOL|P_VI_DEF|P_VIM|P_RALL
laststatus      P_NUM|P_VI_DEF|P_RALL
linebreak       P_BOOL|P_VI_DEF|P_RWIN
lines           P_NUM|P_NODEFAULT|P_NO_MKRC|P_VI_DEF|P_RCLR
linespace       P_NUM|P_VI_DEF|P_RCLR
list            P_BOOL|P_VI_DEF|P_RWIN
macatsui        P_BOOL|P_VI_DEF|P_RCLR
number          P_BOOL|P_VI_DEF|P_RWIN
numberwidth     P_NUM|P_RWIN|P_VIM
relativenumber  P_BOOL|P_VI_DEF|P_RWIN
rightleft       P_BOOL|P_VI_DEF|P_RWIN
scrolloff       P_NUM|P_VI_DEF|P_VIM|P_RALL
showtabline     P_NUM|P_VI_DEF|P_RALL
sidescrolloff   P_NUM|P_VI_DEF|P_VIM|P_RBUF
spell           P_BOOL|P_VI_DEF|P_RWIN
synmaxcol       P_NUM|P_VI_DEF|P_RBUF
tabstop         P_NUM|P_VI_DEF|P_RBUF
termwinscroll   P_NUM|P_VI_DEF|P_VIM|P_RBUF
textwidth       P_NUM|P_VI_DEF|P_VIM|P_RBUF
weirdinvert     P_BOOL|P_VI_DEF|P_RCLR
wrap            P_BOOL|P_VI_DEF|P_RWIN
```

ちなみに、 `P_CURSWANT` を持つ (= curswant を更新する必要がある) ものは以下であり、

```
aleph           P_NUM|P_VI_DEF|P_CURSWANT
arabic          P_BOOL|P_VI_DEF|P_VIM|P_CURSWANT
foldlevelstart  P_NUM|P_VI_DEF|P_CURSWANT
maxcombine      P_NUM|P_VI_DEF|P_CURSWANT
```

`P_RWINONLY` を持つ (= redraw するが curswant は更新しない) ものは以下でした。

```
cursorcolumn    P_BOOL|P_VI_DEF|P_RWINONLY
cursorline      P_BOOL|P_VI_DEF|P_RWINONLY
```

`hlsearch` なんかでも curswant が変わってしまうのは注意が必要ですね。
