### ISSUE TITLE
imactivatefunc imstatusfuncが設定されている場合に検索でfoldが開かない

### ISSUE THREAD

**Issue by yamam** [vim-jp/issues#1384]
## 不具合の内容
imactivatefuncとimstatusfuncが設定されている状況で検索を行ったい、foldされている部分に検索対象の文字列があってもfoldが自動的に開かれない

### 再現手順

vimrc
``` vim
" {{{
se nocp
function ActivateFunc()
endfunction
function StatusFunc()
    return 0
endfunction
set imactivatefunc=ActivateFunc
set imstatusfunc=StatusFunc
" vim:foldmethod=marker
```
vim -u vimrc --noplugin vimrc
/set{Enter}
でfoldが開かれない

### 期待動作

foldが開かれる

上記ファイルのset imactivatefunc=ActivateFunc
をコメントアウトしたvimrcで実行するとfoldが開かれる

## Vimのバージョン

8.2.5014

## OSの種類/ディストリ/バージョン
```
Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by h-east** [comment]
再現しました。
Ubuntu 16.04.7 LTS via PuTTY 0.76
```
:ver
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 19 2022 14:49:53)
Included patches: 1-4980
Compiled by h_east@vboxu
Huge version with GTK2 GUI.
```

`imstatusfunc`が設定されていれば、`imactivatefunc`は設定有無関係なく発生するようですね。

**Comment by Milly** [comment]
8.2.5014 および 4980 で確認。
`imstatusfunc` と `imactivatefunc` が両方とも設定されてる場合のみ発生します。
環境の違い?

```
:ver
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 25 2022 16:55:38)
Included patches: 1-5014
Compiled by milly@
Huge version without GUI.  Features included (+) or not (-):

> uname -sr
Linux 5.10.102.1-microsoft-standard-WSL2
```

**Comment by Milly** [comment]
直しました。
https://github.com/Milly/vim/tree/save-keytyped-in-imcallback

**Comment by yamam** [comment]
ありがとうございました。
直りました。

**Comment by Milly** [comment]
8.2.5020: vim/vim@c7e54efe4dc2bd8fd86feb4a26b4485b7b4c8578

**Comment by h-east** [comment]
@yamam Thank you for the bug report.
@Milly Thank you for making and reporting a patch.
