### ISSUE TITLE
matchit が TeX で動作しない

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1386]
## 不具合の内容
件名のとおりなのですが、標準プラグインの matchit が TeX のファイルでエラーになります
HTML など他のファイルタイプでは問題ありません

ファイルタイプによって違うので、b:match_words を書き換えても見ましたが、変化はありません

以前は問題なかったのですが、いつからエラーのなるように成ったのかはっきりしません
### 現象・ログ
エラー・メッセージは次のとおりです
> Error detected while processing function matchit#Match_wrapper[161]..<SNR>34_ParseSkip:
> line   10:
> E488: Trailing characters: . strpart(skip,2). "'"
> Error detected while processing function matchit#Match_wrapper:
> line  174:
> E121: Undefined variable: r
> line  176:
> E121: Undefined variable: r
> Press ENTER or type command to continue
### 再現手順
\~/.vimrc や \~/\.vim/ がない状態で
```
set nocompatible
filetype plugin on
packadd! matchit
```
の内容でカレントディレクトリにvimrcを作成して
> LANGUAGE=C vim -u vimrc +'set filetype=plaintex | let b:match_words = "{:}" | normal! i{}' +'normal %'

や
> LANGUAGE=C vim -u vimrc +'set filetype=tex | let b:match_words = "{:}" | normal! i{}' +'normal %'

の様に起動すると再現します
## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)
> 適用済パッチ: 1-3995
> Modified by team+vim@tracker.debian.org
> Compiled by team+vim@tracker.debian.org
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)
## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04 LTS
> Release:	22.04
> Codename:	jammy
> $ uname -a
> Linux xxx 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
## 使用している or 関係していそうなプラグイン
なし

**Comment by todashuta** [comment]
`:scriptversion 4`が指定されているのに、`.`で文字列結合をしている部分が残っていてエラーが出ているようです。

[v8.2.4258](https://github.com/vim/vim/releases/tag/v8.2.4258)で修正されていました。
https://github.com/vim/vim/commit/f10911e5db16f1fe6ab519c5d091ad0c1df0d063#diff-d44bf75ca1b465757ebd5e1c2264f98c2541450418aa985ae5bb22b1fc961afb

関連issue：https://github.com/vim/vim/issues/9600

**Comment by iranoan** [comment]
もう直っているんですね
教えて頂きありがとうございました

closeします
