### ISSUE TITLE
GVim 使用時、Terminal/Normal ハイライトグループがデフォルトで同じにならない

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1388]
## 質問の内容
GVim 使用時の :terminal 背景色はどの様に決まるのでしょうか?

ヘルプに
> 端末内のジョブは端末の色を変更できます。デフォルトの前景色及び背景色はVimの
> Normal ハイライトグループにより決定されます。
>
> カラー端末を開始する際に、背景に白と黒どちらの系統の色を使用するかは、オプショ
> ン 'background' を用いて決定します。

'background' は考慮されているようなのですが、Normal ハイライトグループに関係なく、背景は白黒の何れかにしかなりません
Terminal ハイライトグループで指定できますが、デフォルトで Normal と同じにならないのは正しい動作なのでしょうか?

下図は
```
vim -g -u NONE +'colorscheme desert | terminal'
vim -g -u NONE +'colorscheme peachpuff | terminal'
```
の例です
![desert](https://user-images.githubusercontent.com/24851657/177237310-8338ad96-98d8-46e8-bd7b-09d1a40744ee.png)
![peachpuff](https://user-images.githubusercontent.com/24851657/177237321-4238a7e9-551d-4cc9-af0d-93ce7b23fe1f.png)

## Vimのバージョン

> $ vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)
> 適用済パッチ: 1-3995
> Modified by team+vim@tracker.debian.org
> Compiled by team+vim@tracker.debian.org
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04 LTS
> Release:	22.04
> Codename:	jammy
> $ uname -a
> Linux xxx 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by h-east** [comment]
(コマンドと画像の順番があっていなかったので、コマンドの順番を変えさせていただきました)

こちらでは正しいと思われる色で表示されました。

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```
```bash
$ uname -a
Linux vboxu 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
$ env | grep TERM
TERM=xterm-256color
```
```bash
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul  6 2022 14:41:51)
適用済パッチ: 1-42
Compiled by h_east@vboxu
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
```
![image](https://user-images.githubusercontent.com/518808/177478723-a8eb1382-9790-4760-9748-b8397cd87b89.png)

![image](https://user-images.githubusercontent.com/518808/177478876-4e6cceb6-b250-46b8-83c2-85452d910e7a.png)

**Comment by iranoan** [comment]
確認ありがとうございます
> こちらでは正しいと思われる色で表示されました。
> 
> ```shell
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.7 LTS
> Release:	16.04
> Codename:	xenial
> ```

そういえば、一つ前 (Ubuntu 20.10) の環境では、問題なく Normal と同じ配色がされていた気もします

> ```shell
> $ vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul  6 2022 14:41:51)
> 適用済パッチ: 1-42
この違いかもしれませんが…

OS の違いよりも、Vim のバージョン違いのほうが影響が大きいでしょうか?
それとも GTK の違いでしょうか?
> ```sh
> $ apt list --installed | grep 'libgtk-'
> libgtk-3-0/jammy-updates,now 3.24.33-1ubuntu2 amd64 [インストール済み、自動]
> libgtk-3-bin/jammy-updates,now 3.24.33-1ubuntu2 amd64 [インストール済み、自動]
> libgtk-3-common/jammy-updates,jammy-updates,now 3.24.33-1ubuntu2 all [インストール済み、自動]
> libgtk-4-1/jammy-updates,now 4.6.5+ds-0ubuntu1 amd64 [インストール済み、自動]
> libgtk-4-bin/jammy-updates,now 4.6.5+ds-0ubuntu1 amd64 [インストール済み、自動]
> libgtk-4-common/jammy-updates,jammy-updates,now 4.6.5+ds-0ubuntu1 all [インストール済み、自動]
> ```

Vim9 で試したほうが良いのでしょうが、Vim のビルドはしたことがないんですよね
時間が有る時に一同挑戦してみます

**Comment by h-east** [comment]
~~@iranoan お使いの Vim 8.2.3995 以降でLinuxの backgroundカラー絡みの修正はなさそうなので、Vimのビルドは本当に時間のある時で良いと思います。~~

もう少し他の人からの情報が集まると嬉しいですね。＞ All

**Comment by h-east** [comment]
Vim 8.2.3995 だと再現しました。
8.2.3996 ～ 8.2.5172 のどこかで修正されたようです。

**Comment by iranoan** [comment]
詳しく調べて頂き有難うございました
すでに修正済みということなので、closeします

**Comment by h-east** [comment]
8.2.4953 と 8.2.4954 の間の[runtimeファイルの更新](https://github.com/vim/vim/commit/30ab04e16e1e9e6133590181197b3f8e70cb495e)で標準添付のカラースキームがブラッシュアップされたことにより改善されたようです。

結論:
VIm 8.2の適用済パッチ表記が 1-4954 だとこの更新が含まれているので正しく表示されます。

※当該のカラースキームを ~/.vim/colors/ に配置して使用することもできます。お時間のある時に試してみてください。

**Comment by h-east** [comment]
~/.vimrc に以下を書けば、今お使いのバージョンのVimでもTerminalがNormalと同じ色になります。
```vim
autocmd ColorScheme * hi! link Terminal Normal
```
