### ISSUE TITLE
Vim9 scriptのis/isnotはstringに対して正しく動作しない (ように見える)

### ISSUE THREAD

**Issue by kat0h** [vim-jp/issues#1390]
## 不具合の内容 報告者: @thinca
vim9scriptではis/isnotが正しく動作しない 

```
vim9script
echo 'foo' is 'foo' # => false
echo 'foo' is 'bar' # => false
echo 'foo' isnot 'foo' # => true
echo 'foo' isnot 'bar' # => false
```

## 原因
(要約)
Vim scriptでは文字列同士を比較する際、`typval.c`の`typval_compare_string()`関数を利用する。
is/isnotの比較の場合、[Vim9 scriptの中だった場合のみ引数に渡された二つの値のメモリ上の位置が同じかどうかを確認する](https://github.com/vim/vim/blob/master/src/typval.c#L1608-L1625)。
しかし、Vim9 scriptではスタックに値が積まれた時点で、値のコピーが取られているため仮に同一の変数同士を比較してもメモリ上の位置が異なる。
このため、is/isnotはうまく動作しない。
ただし、値がNULLの場合は例外。

----

- 関数内で変数の値同士を比較する場合：
　vim9scriptのVMはLOAD命令で値をコピーしてスタックに積む。is/isnotはポインタしか比較しないのでコピーした値を比較しても意味がない。
- 定数の場合(畳み込みされる場合)
　それぞれのstringはメモリ上では同一ではない。よってポインタの比較に意味はない

そもそもVim scriptのstringはオブジェクトではないため、従来のVim scriptのisは両辺の型が一致しておりかつ同一の文字列かどうかを判定している
Vim9 scriptでも同様にstringはオブジェクトではないため、現状の仕様は意味がない
 (null_stringとtest_null_string()の返すNULLのstringは特別扱いされているので正しい結果を返す)
```
vim9script
var a = 'foo'
var b = a
a = 'bar'
echo b
```
↑Vim9 scriptのstringはオブジェクトではない

## 修正
該当の誤った(?)コードを削除した。
これまでのVim9 scriptは、null_string is '' はfalseを返していたが、この仕様は削除されtrueを返すようになった

# 再現手順
```
vim9script
echo 'foo' is 'foo' # => true (これまでfalse)
echo 'foo' is 'bar' # => false (false)
var foo1 = 'foo'
var foo2 = 'foo'
var bar1 = 'bar'
echo foo1 is foo1 # => true (false)
echo foo1 is foo2 # => true (false)
echo foo1 is bar1 # => false (false)
```

## Vimのバージョン

9.0 patch 1-176

## OSの種類/ディストリ/バージョン

- Ubuntu
- macOS

**Comment by kat0h** [comment]
パッチ
```diff
diff --git a/src/testdir/test_vim9_expr.vim b/src/testdir/test_vim9_expr.vim
index f30cd8da1..b19a95d6f 100644
--- a/src/testdir/test_vim9_expr.vim
+++ b/src/testdir/test_vim9_expr.vim
@@ -886,11 +886,11 @@ def Test_expr4_compare_null()
       assert_false(null != null_string)
​
       assert_true(null_string is test_null_string())
-      assert_false(null_string is '')
-      assert_false('' is null_string)
+      assert_true(null_string is '')
+      assert_true('' is null_string)
       assert_false(null_string isnot test_null_string())
-      assert_true(null_string isnot '')
-      assert_true('' isnot null_string)
+      assert_false(null_string isnot '')
+      assert_false('' isnot null_string)
​
       var ns = null_string
       assert_true(ns == null_string)
@@ -1271,6 +1271,19 @@ def Test_expr4_is()
                             is 0z1234)
       var otherblob = myblob
       assert_true(myblob is otherblob)
+
+      var va = 'foo'
+      var vb = 'foo'
+      var vc = 'bar'
+      var vd = 123
+
+      assert_true(va is va)
+      assert_true(va is vb)
+      assert_false(va is vc)
+
+      assert_false(va isnot va)
+      assert_false(va isnot vb)
+      assert_true(va isnot vc)
   END
   v9.CheckDefAndScriptSuccess(lines)
 enddef
diff --git a/src/typval.c b/src/typval.c
index 8b69adfcc..f4f0fa5a6 100644
--- a/src/typval.c
+++ b/src/typval.c
@@ -1607,24 +1607,12 @@ typval_compare_string(
        i = ic ? MB_STRICMP(s1, s2) : STRCMP(s1, s2);
     switch (type)
     {
-       case EXPR_IS:       if (in_vim9script())
-                           {
-                               // Really check it is the same string, not just
-                               // the same value.
-                               val = tv1->vval.v_string == tv2->vval.v_string;
-                               break;
-                           }
-                           // FALLTHROUGH
-       case EXPR_EQUAL:    val = (i == 0); break;
-       case EXPR_ISNOT:    if (in_vim9script())
-                           {
-                               // Really check it is not the same string, not
-                               // just a different value.
-                               val = tv1->vval.v_string != tv2->vval.v_string;
-                               break;
-                           }
-                           // FALLTHROUGH
-       case EXPR_NEQUAL:   val = (i != 0); break;
+       case EXPR_EQUAL:
+       case EXPR_IS:       val = (i == 0); break;
+
+       case EXPR_NEQUAL:
+       case EXPR_ISNOT:    val = (i != 0); break;
+
        case EXPR_GREATER:  val = (i > 0); break;
        case EXPR_GEQUAL:   val = (i >= 0); break;
        case EXPR_SMALLER:  val = (i < 0); break;
```

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/10886

---
vim_devにPull Requestを出したり、Issueを立てた場合は、こちらにもリンクを貼っていただくとgoodです。
(もしくは、vim_devのPR/IssueにこちらのURLを添えると自動的にリンクされるのでbetter)

**Comment by kat0h** [comment]
ありがとうございますm(_ _)m


Bramさんから返信をいただいたので、転記します

> This choice was made quite a while ago.  Nearly everywhere a string is
copied before it is passed on, thus "is" would nearly always return
false.  Using that as a reason to fall back to comparing the string value
doesn't make sense either, now two completely unrelated strings may have
"is" return true, just because they happen to have the same value.
> 
> One can argue for one or the other.  In a case like this I rather keep
it as it is.  Changing it now is likely to cause trouble in a few
places, and I don't see it helping much.
>
> Another way to look at it: like you mention, strings are not objects,
thus "is" always returns false.
>
> Yet another way would be to give an error when trying to use "is" on
strings.  But that likely causes even more trouble.
>
> A very complicated way to solve this would be to use reference counting
for strings.  Thus intead of making a copy the strings would indeed be
identical.  The reference counting is needed to make sure the string is
deleted if, and only if, the last reference to it is dropped.  It might
be a bit more efficient to avoid making copies, but then keeping the
reference counts correct adds overhead (which should not be
underestimated).

**Comment by h-east** [comment]
リンクで辿れるようになっていればOKです。
ですので、片方のコメントをもう片方に転載する等しなくっても大丈夫ですよ👌

**Comment by kat0h** [comment]
なるほど、承知しました。勝手がわかっていないものですいません
ありがとうございます！

**Comment by kat0h** [comment]
仕様とのことで、現状の維持が良いだろうとの回答をいただきましたので、これにてissueを閉じさせていただきます。

**Comment by kat0h** [comment]
Bramさんにhelpの記述を追加してもらおうと思うのですが、どのような形に変えてもらうのがいいですかね

**Comment by kat0h** [comment]
いまのvim9.txtは↓の通りです。
https://github.com/vim/vim/blob/113d9dec99/runtime/doc/vim9.txt
演算子に関する記述はない（？）みたいです

**Comment by thinca** [comment]
https://github.com/vim/vim/pull/10886#issuecomment-1214300413 ドキュメント書いてくれ～ :pray: ってお願いしてみました。

**Comment by kat0h** [comment]
相違点について記載いただけるとのことでしたので、このissueをcloseします
