### ISSUE TITLE
imap で、先頭が Ctrl で始まるマッピングを設定すると、タイムアウト時に Ctrl と同時に押したキーがバッファに残る

### ISSUE THREAD

**Issue by mikoto2000** [vim-jp/issues#1392]
## 不具合の内容

`imap` で `<C-Y>` 開始のマッピングを定義すると、 [complete_CTRL-Y](https://vim-jp.org/vimdoc-ja/insert.html#complete_CTRL-Y) で補完候補を決定した際に、補完した文字列の直後に `Y` が挿入される。

### 現象・ログ

![vim_complete_CTRL_Y](https://user-images.githubusercontent.com/345832/186614855-79d8f79a-5b4c-4aca-8fb5-b5325500e7a3.gif)

### 再現手順

1. `gvim.exe -u NONE` で起動
2. `imap <C-Y>t echo "aaa"` を実行
    - ( `<C-Y>` で始まる複数キーのマッピング定義を行う)
4. 補完を行い、 `<C-Y>` ( `complete_CTRL-Y` ) で complete item を決定すると、補完結果の次に `Y` が挿入される
    - (キーマッピング確定直前までの、入力したキーが挿入される)

### 期待動作

選択した complete item の word のみが挿入される。

## Vimのバージョン

* 9.0.228 の `gvim.exe`
* `vim.exe` では期待動作だった

## OSの種類/ディストリ/バージョン

* Windows 11 Pro 64bit 21H2, ビルド 22000.856
* [vim-win32-installer の Release v9.0.228](https://github.com/vim/vim-win32-installer/releases/tag/v9.0.0228) を使用

## 使用している or 関係していそうなプラグイン

特になし

## その他

特になし

**Comment by h-east** [comment]
gvim 9.0.0000 および 9.0.0260 on Windows 10で再現しました。
gvim 8.2.4751では再現しなかったので9.0.0000までのpatchでバグが入り込んだようです。

**Comment by h-east** [comment]
8.2.4815 NG
8.2.4787 OK

**Comment by mikoto2000** [comment]
8.2.4807 NG
8.2.7803 OK
[Release v8.2.4807 · vim/vim-win32-installer](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4807)

**Comment by mikoto2000** [comment]
8.2.4806 OK
以下コミットからのようです。
https://github.com/vim/vim/commit/77fc0b02e53bdc49213900e0055cb6d678ce180d

**Comment by h-east** [comment]
Linux版(GTK2-GNONE GUI)は最新ではOKですが以前NGの時期があったようですね。
9.0.0285 OK
8.2.4787 NG
8.1.0551 OK

**Comment by mikoto2000** [comment]
complete_CTRL-Y は関係なく、以下条件がそろったときに Ctrl と同時押ししたキーがバッファに残るという現象のようです。

1. imap で、先頭が Ctrl で始まるマッピングを設定
2. マッピングの処理がタイムアウトした

以下、確認動画です。
![vim_imap_and_ctrl](https://user-images.githubusercontent.com/345832/188130971-d2d8c853-d018-4b86-8ab1-4b35c9622a1e.gif)
1. 先頭が Ctrl のマッピング
    1. `imap <C-D>t bbb` を設定
    2. `<C-D>` を入力してタイムアウトまで待つ -> `D` がバッファに残る
    3. `<C-D>t` を入力 -> `D` が消えて `bbb` が入力される
2. 先頭が Ctrl でないマッピング
    1. `imap a<C-D>t aaa` を設定
    2.  `a` を入力してタイムアウト -> `a` がバッファに残る
    3. `a<C-D>` を入力してタイムアウト -> `D` が消えて `a` が入力される
    4. `a<C-D>t` を入力 -> `D` が消えて `aaa` が入力される

**Comment by h-east** [comment]
@mattn (Windows版だけで良いので、)vim_devに報告してもらえると助かります。

**Comment by mattn** [comment]
はい。今晩あたり確認します。

**Comment by mattn** [comment]
すみません、今から確認します。

**Comment by mattn** [comment]
https://github.com/vim/vim/issues/11057

**Comment by k-takata** [comment]
直ったらしいです。 https://github.com/vim/vim/commit/c47b16a47063735413ebe3885604c4460f724246

**Comment by mikoto2000** [comment]
9.0385 で問題が解決し、 Ctrl と同時に押したキーがバッファに残らないことを確認しました。
ありがとうございました！
