### ISSUE TITLE
Git for Windows 内のVimの `:terminal` 内で、日本語が化ける (`�`, `U+FFFD`) ことがある

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim-jp/issues#1394]
## 不具合の内容

Git for Windows の GitBash内で Vim を立ち上げ、`:terminal` で シェルのウィンドウ を開きます。

その中で、日本語 が表示される場合、
その一部が `�` (`U+FFFD`) の文字に 化けることがあります。

### 現象・ログ

```bash
#!/bin/bash
# vim: ft=sh et ts=4 sts=4 sw=4

for i in $(seq 0 999); do
    echo -n " $i 日本語"
    #echo -n "日本語"
done
```

```bash
% ./test.sh
 0 日本語 1 日本語 2 日本語 3 日本語 4 日本語 5 日本語 6 日本語 7 日本語 8 日本
語 9 日本語 10 日本語 11 日本語 12 日本語 13 日本語 14 日本語 15 日本語 16 日本
語 17 日本語 18 日本語 19 日本語 20 �本語 21 日本語 22 日本語 23 日本語 24 日本
#                                   ^^

#                                    (snip)
```

ただし、同じ文字列が いつも化けるわけではないようです (前後の文字列 による？)。

上記のスクリプトだと、`echo -n "日本語"` の方 は、文字化けしません。

また、Vimから ではなく；
直接、素の `bash`上で 同じことをする場合、上記の文字化け は 発生しません。

### 再現手順

1. GitBash上で、`vim`コマンド を実行する
2. `:terminal` を実行する
3. その中で、上記のような、日本語を含む出力 を行うコマンド を実行する

### 期待動作

日本語出力時に `�` (`U+FFFD`) に化けない。

## Vimのバージョン

* VIM: Vi IMproved 8.2 (2019 Dec 12, compiled Jun 23 2022 04:01:15)
    - 適用済パッチ: 1-5117

## OSの種類/ディストリ/バージョン

* Microsoft Windows [Version 10.0.19044.1889] (Windows 10 Pro 21H2, 64bits)
* Git Bash: 2.37.3.windows.1
    - もっと以前のver. から、既に発生していました。

## 使用している or 関係していそうなプラグイン

特になし

## その他

https://github.com/vim-jp/issues/issues/1107 が やや関連issue?

ひどいケースだと、`ls -l` の 日付部分 ` 9月  5` の `月` で化けたり；
当然、日本語のファイル名 で化ける、といったケースもあります。

Vim上の `:terminal`特有 です。

何か 改善方法 があると、とても助かるのですが…。

**Comment by mattn** [comment]
native の vim.exe でしょうか。それとも msys2 上の vim.exe でしょうか。

**Comment by KSR-Yasuda** [comment]
Git for Windows の Git Bash に入ってる `/usr/bin/vim` を そのまま実行しているんですが、
それで答えになっているでしょうか？

**Comment by mattn** [comment]
>それで答えになっているでしょうか？

はい、ありがとうございます。

**Comment by mattn** [comment]
再現しました。これを見る限り、20ずつ発生している様に見えるので、そらく内部に持っているバッファを溢れるタイミングがあり、`xx 日本語` の途中でバッファ溢れが発生しているんだと思います。時間取ってソース確認します。

![image](https://user-images.githubusercontent.com/10111/188344122-9ba61f96-a970-481f-9003-f8dedcedfe3a.png)

**Comment by k-takata** [comment]
およそ256バイトっぽいですね。
Cygwinでも再現しました。

**Comment by k-takata** [comment]
```diff
--- a/src/channel.c
+++ b/src/channel.c
@@ -3865,8 +3865,6 @@ channel_read(channel_T *channel, ch_part
 	// Store the read message in the queue.
 	channel_save(channel, part, buf, len, FALSE, "RECV ");
 	readlen += len;
-	if (len < MAXMSGSIZE)
-	    break;	// did read everything that's available
     }
 
     // Reading a disconnection (readlen == 0), or an error.
```
これで直ったように見えるのですが、これでよいのかよく分からないです。
`MAXMSGSIZE` は 4096 になっていますが、Cygwin の `sock_read()` は最大でも 256 bytes しか返してこないように見えます。そのため、まだ読むべきデータが残っている状態でループを抜けてしまい、データが壊れてしまっていたようです。

**Comment by mattn** [comment]
MAXMSGSIZE の値を BUFSIZ に変えたらどうなりますかね。

**Comment by mattn** [comment]
あ、Cygwin は 1024 なのか。失礼しました。

**Comment by mattn** [comment]
うむ。k-takata さんのパッチの様に、1回 channel_wait させた方がいいですね。あってると思います。

**Comment by k-takata** [comment]
`Test_pipe_io_one_buffer()` が無限ループになってしまっているみたい…

**Comment by k-takata** [comment]
これでどうだろう。
https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/c463e9601b1269bfa654a9868dbd5db218e129f5/vim-jp-1392.patch

書き込み側のfdがずっとreadyになってるので、無限ループになってしまってた。書き込むべきデータがあるときのみ書き込み側fdをセットするようにすることで回避。

**Comment by mattn** [comment]
直ってるの確認しました。

**Comment by k-takata** [comment]
PRed: https://github.com/vim/vim/pull/11063

**Comment by k-takata** [comment]
Fixed in [9.0.0394](https://github.com/vim/vim/commit/5903aaf7eb4586cf7e4fa5a219092334b05c89de).
