### ISSUE TITLE
vsnipの補完で、その補完方法によって補完後のモードが異なる

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1397]
## 質問の内容
件名の通り、特定のプラグインの話題ですが、こちらで質問しても大丈夫でしょうか?
そぐわない場合はご指摘いただけると助かります

肝心の質問は件名の通りで、スニペットから補完した時、その方法によって補完モードが異なるのですが、これは正しい動作なのか? が知りたいです

まずテスト用に用意した環境 \~/.vim/vimrc は次のとおりです
```
call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'rafamadriz/friendly-snippets'
call plug#end()
imap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
imap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
smap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'
set viminfo+=n~/.vim/viminfo
set background=dark
colorscheme desert
filetype plugin on
set laststatus=2
augroup InsertStatus
  autocmd!
  autocmd InsertEnter * highlight StatusLine ctermfg=red   guibg=red
  autocmd InsertLeave * highlight StatusLine ctermfg=white guibg=white
augroup END
```

ご覧のようにテスト自体に関係ありませんが、挿入/ノーマル・モードの違いがわかりやすいように、ステータス・バーの色が変わるようにしています

次に具体的な質問ですが、下記に添付した GIF 画像のように
* スニペット・トリガーとなるキーワードをすべて入力して補完→挿入モード
* 入力キーワードによって現れる候補から選択してから補完    →ノーマル・モード

と、その補完直後のモードが違います
![vsni](https://user-images.githubusercontent.com/24851657/194464934-f9c5d6e9-90ff-45b9-ad1b-9a82d0257203.gif)

なお補完後にはどちらも insert とタイプしていますが、後者の補完は、補完直後がノーマル・モードのため i が入力されません
また動画は Gnome Terminal ですが、GVim や他のターミナル (tildaや +tmux) でも同じでした

動画で用いている \<C-L> (vsnip-expand-or-jump) 以外に \<C-J> (vsnip-expand) も同じ様に補完後のモードに違いが出てきます

加えて動画には含まれていませんが、後者の補完では、補完直後の \<Esc> で入力モードになるという Vim としてはかなりイレギュラーな動きをします

補完後は基本的に入力モードになるのが自然と感じるのですが…、仕様なのか? など私にはわかりません

とりあえず vim-vsnip/plugin/vsnip.vim L.96
```
  " This is needed to keep normal-mode during 0ms to prevent CompleteDone handling by LSP Client.
  let l:maybe_complete_done = !empty(v:completed_item) && !empty(v:completed_item.user_data)
  if l:maybe_complete_done
    call timer_start(0, { -> l:ctx.callback() })
  else
```
を次の様に強制的に挿入モードにしてやれば、希望の動作をしているようなのですが、これが本当に正しいのかも…
```
  " This is needed to keep normal-mode during 0ms to prevent CompleteDone handling by LSP Client.
  let l:maybe_complete_done = !empty(v:completed_item) && !empty(v:completed_item.user_data)
  if l:maybe_complete_done
    call timer_start(0, { -> l:ctx.callback() })
    if mode(1) =~# 'n'
      startinsert
    endif
  else
```

## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2022 09:35:02)
> 適用済パッチ: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919
> Modified by team+vim@tracker.debian.org
> Compiled by team+vim@tracker.debian.org
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.1 LTS
> Release:	22.04
> Codename:	jammy
> $ uname -a
> Linux xxxx 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by h-east** [comment]
vim-vsnip の内部の話だと思うので、そちらのリポジトリにIssue立てて問い合わせたほうが良いと思います。
英語が面倒でしたら作者の方にtwitterでDM送ってみるとか？
(このIssue使ってやり取りして頂いて構いませんよ。)

**Comment by iranoan** [comment]
他の方から見ても vim-vsnip の話と判断してよいのですね
そちらで聞いてみます
どうもありがとうございました
