### ISSUE TITLE
選択された補完候補を知る

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#14]
現状、ユーザー定義補完やオムニ補完において、ユーザーが選択し挿入した候補を知ることができません。
これを知ることができれば、eskk.vimやneocomplcacheが選択した候補を学習することができます。

他のプラグインでも応用できるかは、まだよく分かりません。

実装には、専用のhookを導入するのが一番簡単かもしれません。

**Comment by mattn** [comment]
> 実装には、専用のhookを導入するのが一番簡単かもしれません。

いやーhookの実装は結構難しいすよ。
昨日入った補完関数に`on_insert`みたいなの入れてそれを呼ばせるのが一番簡単な気がする。

**Comment by Shougo** [comment]
> 昨日入った補完関数にon_insertみたいなの入れてそれを呼ばせるのが一番簡単な気がする。

ああ、それは良い方法ですね。どうせ新しいVimでないと意味がないし。

> いやーhookの実装は結構難しいすよ。

hookを作ったことがないので、そういったことが分からないんですよね。

**Comment by koron** [comment]
ここでdictにした強みが!

実装もちゃんと拡張しやすいようにしときましたよ。
なのでいったん私が引き取ります。って、assignってどうすれば良いの?w

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/bcba8c49e5db268c.png)

もうやってあるので気付いてると思いますが、ここで...

**Comment by koron** [comment]
一覧からチェックボックス使ってassigneeしてもうたwww

**Comment by Shougo** [comment]
おお、Koronさんが引き取ってくれた。これは期待。

**Comment by mattn** [comment]
@koron

https://groups.google.com/d/topic/vim_dev/PLgu6mQQXoM/discussion

closeするにはこれと何かが必要です？

**Comment by koron** [comment]
@mattn
それは本件には関係無いです。always追加に伴う不具合の解決なので。

**Comment by koron** [comment]
実装はできた。あとはドキュメント。

サンプルスクリプトはこんな感じ。
https://gist.github.com/1238900

onselectedに渡したfuncrefが呼ばれる。

**Comment by Shougo** [comment]
遂にneocomplcacheにまともな学習機能が作れるようになります。ありがとうございます。

**Comment by koron** [comment]
http://groups.google.com/group/vim_dev/browse_thread/thread/da4a289d7d04391

送った。

**Comment by Shougo** [comment]
了解です。取り込まれたら、neocomplcacheの学習ルーチンを作り直します。

**Comment by mattn** [comment]
メンバには通知されてるはずだけど #37 から転載

COMPLETEDONE イベント入ったけど、イベントのエキストラ情報として足りない物があったら言ってほしい

って言ってるので関連する人は今の内に確かめないと互換性がなくなる説。

https://groups.google.com/d/msg/vim_dev/XDFDQ8rkBII/7uHUjwuLghIJ

**Comment by Shougo** [comment]
報告ありがとうございます。私も確認しておきます。

**Comment by Shougo** [comment]
もう最新版に入っているのなら、neocomplcacheに学習機能を実装して確かめたほうが良さそうですね。

**Comment by Shougo** [comment]
あ、でもこれは補完した通知しか無いので、KoRoNさんのパッチのように「補完した候補」と「補完した時のbase」の情報はぜひともほしいです。

**Comment by mattn** [comment]
あれ？動いてる？

``` vim
function! Complete(findstart, base)
  if a:findstart
    return col('.')
  endif
  return ['aaa', 'bbb']
endfunction

function! s:Done()
  echomsg "done"
endfunction

set omnifunc=Complete

augroup CompleteDone
  au!
  au CompleteDone * call s:Done()
augroup END
```

**Comment by Shougo** [comment]
`:autocmd CompleteDone`で確認するとわかるのですが、autocmdの登録がおかしなことになっています。

**Comment by mattn** [comment]
あー、グループ名と同じはまずいか

``` vim
function! Complete(findstart, base)
  if a:findstart
    return col('.')
  endif
  return ['aaa', 'bbb']
endfunction

function! s:Done()
  echomsg "done"
endfunction

set omnifunc=Complete

augroup CompleteDoneGroup
  au!
  au CompleteDone * call s:Done()
augroup END
```

**Comment by Shougo** [comment]
今度は動きました！

**Comment by mattn** [comment]
エキストラ情報についてですが、辞書登録する場合って変換元に対して複数ある候補の内、ある候補を選んだという結果を登録する訳で、つまりは辞書登録に必要なのは
- a:base
- 最後に選んだ候補

になります。CompleteDone イベントは補完関数とは別の関数になるので a:base を参照しようと思えばスクリプトスコープに格納しておく必要があります。
その際、a:findstart も保持しておけば取れるかな。つまり、a:base を外に保持しないといけないという制約がある時点でエキストラ情報を貰う意味って無くなってくる。

``` vim
let s:complete_pos = 0
let s:complete_base = ''

function! Complete(findstart, base)
  if a:findstart
    let s:complete_pos = len(matchstr(getline('.'), printf('^.*\s\+\ze\S\+\%%%dc', col('.'))))
    return s:complete_pos
  endif

  let s:complete_base = a:base
  return filter(['123', '456'], 'stridx(v:val,a:base)==0')
endfunction

function! s:Done(...)
  let base = s:complete_base
  let candidate = getline('.')[s:complete_pos :col('.')]
  echomsg base "=>" candidate
endfunction

set omnifunc=Complete

augroup CompleteDoneGroup
  au!
  au CompleteDone * call s:Done()
augroup END
```

**Comment by Shougo** [comment]
はい。たしかにそれを使ってくればいいですね。
ただし、一つ問題になりそうなのは、どの補完の候補が選択されてイベントが呼ばれたのか
autocmd側でわからないのです。例えば組み込み補完の選択でautocmd関数が呼ばれると、学習機能が誤作動する可能性があります。KoRoNさんの実装では補完関数に紐づいているため、そのような問題はありませんでした。

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/XDFDQ8rkBII/k8IHseuA8ecJ

とりあえずこんな感じで
1. (必須)ユーザがどの単語を選択したか
2. (オプション)a:base の情報

が欲しいと申告しておきました。

**Comment by Shougo** [comment]
ちょっと試してみたのですが、このイベントはやはりオムニ補完やユーザ定義補完以外でも発動しています。
例：ファイル名補完
どの補完が選択されたかがわからないとまずそうです。

**Comment by koron** [comment]
それはスクリプト側で大変だけどなんとかできませんか?
最終候補一覧を覚えておいて照合するようにすれば弾けるし、
逆に言うと通常補完時の選択も学習データとできる、みたいな。

**Comment by mattn** [comment]
単純な `<c-p>` だと補完関数が呼ばれもせずに done だけ走るのか。↑のサンプルだと s:complete_pos とか s:complete_base をクリアしないとまずいな。

**Comment by Shougo** [comment]
> 逆に言うと通常補完時の選択も学習データとできる、みたいな。

それでもいいと思います。neocomplcacheでいえば、通常補完で選択された候補をキャッシュに反映することも可能です。
autocmd方式にはそういう利点があるから採用されたのでしょうかね。

**Comment by koron** [comment]
実装が楽&他に影響がないのが明らか、かもw

**Comment by mattn** [comment]
実装の容易さでしょ

**Comment by koron** [comment]
かぶったw

それに私の版はパッチで入ったらマズイレベルの内容なので。

**Comment by mattn** [comment]
あとgcが必要ってのもあるね。

**Comment by Shougo** [comment]
確かに、KoRoNさんのパッチだと変更点が多かったですね。

**Comment by koron** [comment]
とりあえず私が https://github.com/koron/java-helper-vim を作った限りでは
選択した要素はautocmdでもわかったのでいったん閉じます。

**Comment by Shougo** [comment]
選択された候補のword情報だけでなく、abbrなどの情報も得られると嬉しいと思いました。
これが実現できると、選択した候補の情報をエコーエリアなどに表示させることができます。
今はこういう機能はjediやYCM等で独自に実装されていますが、実装が共通化できるのは利点として挙げられると思います。

https://groups.google.com/d/msg/vim_dev/XDFDQ8rkBII/80JSOIVbnQgJ

> Even better than the number of the select item: the whole dict as
> mentionned on stackoverflow.

dictが得られると良いと、ここにも挙げられてますね。パッチを書けないか検討してみようかな……。

**Comment by Shougo** [comment]
新しいIssueをオープンしました。パッチの改良は上記のIssueでやりましょう。
