### ISSUE TITLE
setcellwidths()関数がヘルプの例でエラーになる

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1400]
## 不具合の内容
setcellwidths() について、ヘルプに次の記載がありますが、エラーになります
```
           setcellwidths([[0xad, 0xad, 1],
                \ [0x2194, 0x2199, 2]])
```
### 再現手順
全く同じではありませんが、最小限の再現GIF画像を添付します
![setcellwidths](https://user-images.githubusercontent.com/24851657/202758622-c2e1a0aa-ba14-4a1a-b42a-5c96277c1698.gif)

## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 23 2022 20:18:58)
> 適用済パッチ: 1-242
> Modified by team+vim@tracker.debian.org
> Compiled by team+vim@tracker.debian.org
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic
> $ uname -a
> Linux xxxx 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tsuyoshicho** [comment]
たしかにそのようですね。

というか、helpに後述されてるので、例が改訂されてないというべきか。

https://github.com/vim-jp/vimdoc-ja/blob/00cc40e5c323376d9ce40e3993f95bd90e0dfbd5/doc/builtin.jax#L7296-L7297

https://github.com/vim-jp/vimdoc-ja/blob/00cc40e5c323376d9ce40e3993f95bd90e0dfbd5/doc/builtin.jax#L7307

これでE1114が出てますからね

**Comment by iranoan** [comment]
他の環境や最新版では直っているかな? とも思ったのですが、そうでもないのですね
例文の文字は上付き添字の1(¹)なので、例文の改定よりプログラムの側、文字コードの範囲で限定するなら、ASCIIコードの0x7Fまでの除外が妥当な気がしています

**Comment by tsuyoshicho** [comment]
範囲については削除文字類があったりするので、ちょっと提案しにくいので、サンプルと範囲を見直してほしい旨でIssueを起すことにします。

https://github.com/vim/vim/issues/11581

**Comment by iranoan** [comment]
ありがとうございます

**Comment by tsuyoshicho** [comment]
サンプルが更新されました。
問題なければclose?

**Comment by iranoan** [comment]
齟齬がなくなったので、とりあえずはcloseで良いと思います
記号・文字の使われ方からすると、0xA0-0xFFは許されて良い気がします
0xA0 no-brek space
0xAD soft hypen
は微妙ですし、ダイアクリティカルマーク付きアルファベットは元々半角幅のようですが…

これを要望として開発サイドに送りたいときは、どのような手順を踏めばよいのでしょう?

**Comment by k-takata** [comment]
https://www.unicode.org/Public/UNIDATA/EastAsianWidth.txt の Field 1 が "A" になっている文字はあいまい幅なので設定できてもよい気がしますね。

**Comment by k-takata** [comment]
0x80-0xFF も許可する PR を作ってみた。
https://github.com/vim/vim/pull/11834

**Comment by iranoan** [comment]
ありがとうございます

**Comment by k-takata** [comment]
[9.0.1223](https://github.com/vim/vim/commit/7193323b7796c05573f3aa89d422e848feb3a8dc) で 0x80-0xFF も許可されるようになりました。
