### ISSUE TITLE
vim の syntax に間違いが有る

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1404]
## 不具合の内容
runtime/syntax/vim.vim L.247

> syn match	vimFunction	"\<def!\=\ze\s*(" contains=@vimFuncList nextgroup=vimFuncBody

が間違っています

関数名を示す部分が抜けていて
```
syn match	vimFunction	"\<def!\=\s\+\%(\i\|[#.]\|{.\{-1,}}\)*\ze\s*(" contains=@vimFuncList nextgroup=vimFuncBody
```
といった修正が必要です
### 現象・ログ
```
set foldmethod=syntax
```
を指定した時に、def による関数が折り畳み対象になりません

### 確認したファイル
> " Last Change:	August 17, 2022
> " Version:	9.0-02

で動作確認しましたが

> " Last Change:	December 20, 2022
> " Version:	9.0-17

も該当箇所は違いがありません

**Comment by tsuyoshicho** [comment]
確認中...

**Comment by tsuyoshicho** [comment]
https://github.com/vim/vim/blob/df8f9473596c8fb18ec893de677dba455e8925b3/runtime/syntax/vim.vim#L246-L247

定義に差がありますし、質問(+こう直しがほうがいいのでは)というIssueを出しておくのがよさそうです。
やってみます。

**Comment by tsuyoshicho** [comment]
https://github.com/vim/vim/issues/11790
出してみました、 Dr. Chip さんが owner なので、対応されるのがいつになるかは不明ですが...

**Comment by iranoan** [comment]
ありがとうございます

**Comment by iranoan** [comment]
> " Last Change:	Jan 08, 2023
> " Version:	9.0-18
で取り込まれているようなので閉じます

**Comment by tsuyoshicho** [comment]
こちらもIssueに結果を入れてCloseします。

**Comment by iranoan** [comment]
あ、そちらもありましたね
よろしくおねがいします
