### ISSUE TITLE
set wrap ほかいくつかの条件の組み合わせでカーソル位置がおかしくなる

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1408]
### 概要

```vim
set wrap
```
ほかいくつかの設定の組み合わせで次の現象が起きます

* 行末方向の文字が表示されない
* 文字カーソル位置が上記の表示されない分だけ下方にずれて表示される

### 再現画像
* 端末でも再現しますが、幅・高さ設定できるので下記の画像、動画は GVim で撮りました
* 後に設定ファイルをを書き込んできますが、次の色で 右下 ruler でもカーソル位置がわかります
	* 文字カーソルはオレンジ
	* 検索ハイライトは薄い緑
	* カーソル行は灰色

### /if で検索した時

![search](https://user-images.githubusercontent.com/24851657/217149394-ca36d5b8-ba21-4a2b-ae98-0f8a373b70d7.png)

### G でファイル終端に移動した時
![EOF](https://user-images.githubusercontent.com/24851657/217149422-f5ecccfb-780f-4c00-9a79-c2f058e15dbc.png)

### 編集動画
![wrap](https://user-images.githubusercontent.com/24851657/217149440-b4c74917-0061-4d87-ae3d-f3868c3923c5.gif)

### 再現手順
下で示す設定以外の条件としては次が必要なようです
* タブ文字が tabstop の数値の整数倍の位置に有る
* タブ文字の後ろに折り返し可能な文字がない

#### サンプル・ファイル
[sample.txt](https://github.com/vim-jp/issues/files/10671613/sample.txt)

#### \~/.vim/vimrx
```vim
scriptversion 4
set linebreak
set list
set listchars+=tab:>-<  " 指定 xyz は x, xy のみでも、他の記号の組み合わせでも再現
set wrap
set number foldcolumn=1 " どちらか一方でも再現
" 以下問題を見やすくする設定
set ruler
set hlsearch
set cursorline
set background=dark
colorscheme habamax
```

### ~/.vim/gvimrc
```vim
set columns=78 lines=24
```
### 期待動作

タブの代わりにスペースがあったときのように、右端に来る適当な文字で折り返されて表示される

## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb  5 2023 01:13:52)
> 適用済パッチ: 1-1278
> Compiled by xxx@xxx
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)

条件がわからず報告していませんでしたが、Ver.8.x の頃にも起きていました

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic
> $ uname -a
> Linux xxx 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 4 12:14:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by iranoan** [comment]
> ```set listchars+=tab:>-<  " 指定 xyz は x, xy のみでも、他の記号の組み合わせでも再現```

のコメントに間違いがありました
正しくは
> " 指定 xyz は xy のみでも、他の記号の組み合わせでも再現

**Comment by h-east** [comment]
再現しました。
調査中です。
表示系なので行き着く先は `win_line()` になります。
が、この関数自体 3000行あって、1文字ごとの処理をする forループが 2300行あるので、gdbでstep実行していると途中で眠ってしまい、また最初から...を繰り返しています(苦笑)
少し時間ください。

```
#0  win_line (wp=0x19b9590, lnum=1, startrow=0, endrow=23, nochange=1, number_only=0) at drawline.c:2845
#1  0x000000000045e33f in win_update (wp=0x19b9590) at drawscreen.c:2484
#2  0x000000000045948d in update_screen (type_arg=0) at drawscreen.c:324
#3  0x0000000000704f2b in main_loop (cmdwin=0, noexmode=0) at main.c:1423
#4  0x00000000007044a0 in vim_main2 () at main.c:887
#5  0x0000000000703bb7 in main (argc=4, argv=0x7ffca43695b8) at main.c:433
```

**Comment by iranoan** [comment]
> この関数自体 3000行あって、1文字ごとの処理をする forループが 2300行

…言葉が出ないですね

> 少し時間ください

こちらこそ調べて頂きありがとうございます
他の環境でも再現することが分かっただけでもありがたいです

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/12065

**Comment by h-east** [comment]
Fixed by [9.0.1373](https://github.com/vim/vim/commit/194555c001f2b8576483ef34511450b6e9b5e3fd).

**Comment by iranoan** [comment]
取り込まれるのを確認してからcloseするつもりでしたが、ありがとうございます
私の環境でも問題が解消されていることを確認しました
