### ISSUE TITLE
最新Vimのシェル・スクリプト・シンタックスがおかしい

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1409]
## 不具合の内容
&amp;runtime/syntax/sh.vim が
> " Last Change:		Nov 25, 2022
> " Version:		204

では問題ないのですが、

> " Last Change:		Dec 20, 2022
> " Version:		205

だとスクリプトの 2 行目以降の色がおかしくなるようです

###  Version: 204 のスクリーンショット
![old](https://user-images.githubusercontent.com/24851657/220373784-30e78078-948d-432e-9a62-ac5125ac300e.png)

###  Version: 205 のスクリーンショット
![new](https://user-images.githubusercontent.com/24851657/220373835-aed41928-3a0e-4203-b3d2-5ad490dddc06.png)

### 再現手順 (\~/.vim/vimrc の内容)
``` vim
scriptversion 4
syntax enable
```

## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb  7 2023 13:25:16)
> 適用済パッチ: 1-1285
> Compiled by xxx@xxx
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic
> $ uname -a
> Linux xxx 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## その他
L.338 を
``` vim
 syn region shCommandSub matchgroup=shCmdSubRegion start="\$(\ze\%([^(]\|$\)"  skip='\\\\\|\\.' end=")"  contains=@shCommandSubList
```
と start の一部をグループ化すれば良いと思うのですが、いかがでしょう?

ちなみにこの部分の start の値は元々次の値です
Ver. 204: \\$(\ze[^(]
Ver. 205: \\$(\ze[^(]\\|$

**Comment by k-takata** [comment]
https://github.com/vim/vim/issues/11937#issuecomment-1421116531
Version 207 が出ていますのでお試しください。

**Comment by iranoan** [comment]
https://github.com/vim/vim.git
より新しいものが有ったんですね

修正されていること確認したので閉じます
ありがとうございました
