### ISSUE TITLE
foldmethod=expr の時に最初に1度だけ走るような処理が書ける機能が欲しい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#141]
`foldmethod=expr` を使うと、`'foldexpr'` に設定した式が毎行に対して呼ばれます。
しかし、毎行に対して式を実行する前にバッファ全体の傾向を調べたりしたいことがままあります。
なので、`'foldexpr'` の前に1度だけ走る処理を書けるようにするか、
もしくはもっといい柔軟な方法が(何か案があれば)欲しいです。

**Comment by thinca** [comment]
書いてて思ったのだけど、`foldmethod=manual` にして `InsertLeave` イベントなどで `:fold` や `:normal!` を駆使して設定すれば柔軟な設定は可能ではある。かなり強引だけど。

**Comment by koron** [comment]
その前に「一度だけ」の定義をハッキリさせたいなぁ。

foldmethodが設定された後? バッファが読み込まれた後?

**Comment by mattn** [comment]
例えばどんな物でしょうか。

**Comment by thinca** [comment]
> その前に「一度だけ」の定義をハッキリさせたいなぁ。

`'foldexpr'` の式が実行される前です。

> 例えばどんな物でしょうか。

具体的には、今 [diff_fold](https://github.com/thinca/vim-ft-diff_fold) をいじろうとしてたんですが、
diff って出力するソフトによって微妙に表記が揺れるんですね。
で、毎行処理する式で毎回それを判定していると重くなるので、
最初にその傾向を掴んでから処理をしたいと思いました。
diff に限って言えば概ねReadOnlyなので最初に判定しても良さそうですが、
似たようなことは以前別の fold プラグインを書いているときも感じた記憶があります。詳細は忘れてしまいましたが。

**Comment by mattn** [comment]
バッファ変数にそこらを持たせるのでは駄目すか？(ﾆｹﾞﾆｹﾞ...)

**Comment by thinca** [comment]
それを持たせるタイミングが欲しいんですよね。
バッファが変更されていた場合、fold の計算を行う前に1度だけその辺りを計算してそのバッファ変数を更新する必要があります。`'foldexpr'` は毎行に対して呼ばれてしまうので、最初かどうかの判定ができません。

**Comment by koron** [comment]
@thinca 一度だけの定義がハッキリしない。正確に言うと、内部で「一度呼び出したら立てる」フラグを管理するとしてそれを寝かせるタイミングが不明。仮にバッファに付随するものなら @mattn さんの言うとおりバッファ変数でも良い気がする。

**Comment by mattn** [comment]
```
if has(b:, "checked_diff_style", 0) || b:checked_diff_style != b:changedtick
  " いろいろ
  let b:checked_diff_style = b:changedtick
endif
```

こんなのはどうでしょ(ﾆｹﾞﾆｹﾞ)

**Comment by thinca** [comment]
> 一度だけの定義がハッキリしない。

`'foldexpr'` の式は、折り畳みの再計算が必要になったときに _各行に対して_ 実行されます。100行あれば100回実行されます。その際、現在何回目の実行なのかを知ることができません。これらの実行の前に1度だけ処理がしたい場合がある、ということです。

@mattn
それは現状での回避策としてはアリですね。ありがとうございます。
ただ、`'foldexpr'` はその処理回数から可能な限り軽くしたいので、できればそのチェックのオーバーヘッドもなくしたいですね…。

**Comment by koron** [comment]
呼び出す関数refを差し替えれば良いのでは?

**Comment by thinca** [comment]
うーん、あれこれ言っておいてアレですが、複雑な計算が必要な折り畳みの生成は
最初に言った方法が強引とは言え処理効率としては一番いい気がしてきました…。
問題があるとすれば、折り畳みの再計算が必要な正確なタイミングがわからないってことですかね。
`InsertLeave` でも概ね機能はしそうですが。

**Comment by koron** [comment]
ふと考えたら `foldmethod` 前回呼び出し以降、バッファ変更があったかなかったかだけわかれば良いんじゃなかろうか? undolist をみることで判別つかないか?

**Comment by mattn** [comment]
@thinca つまりは FoldingStart みたいなイベントが欲しいって事すよね？

**Comment by thinca** [comment]
> 呼び出す関数refを差し替えれば良いのでは?

どういうことでしょう?

> ふと考えたら `foldmethod` 前回呼び出し以降、バッファ変更があったかなかったかだけわかれば良いんじゃなかろうか? undolist をみることで判別つかないか?

それがさっき @mattn さんが示してくれたコードです。

@mattn そういうことですね。

**Comment by koron** [comment]
> > バッファ変更があったかなかったかだけわかれば良いんじゃなかろうか? undolist をみることで判別つかないか?
> 
> それがさっき @mattn さんが示してくれたコードです。

全然違います。あれは「foldexprが以前に呼ばれたかどうか」で、私の言う「前回のfoldexpr呼び出し以降にバッファに変更があったかどうか」とは別物ですよ。

**Comment by koron** [comment]
バッファに変更があったかどうかはundotree()['seq_cur'] あたりで判別可能そう。

**Comment by thinca** [comment]
あのコードは、`b:changedtick` を使うことで「前回のfoldexpr呼び出し以降にバッファに変更があったかどうか」をチェックしてますよ。

**Comment by koron** [comment]
ああなるほど。すまんす。

**Comment by koron** [comment]
タイトルの

> foldmethod=expr の時に最初に1度だけ走るような処理が書ける機能が欲しい

は @mattn さんので満たされませんかね? スピードの件はあのくらいのチェックであればたいしたオーバヘッドとは考えにくく、仮にオーバーヘッドになるという主張ならちゃんと計測に基づくべきだし。

**Comment by thinca** [comment]
そうですね。オーバーヘッドになりそうな予感を除けば、あれで良さそうです。
…Closeした方が良い?

**Comment by mattn** [comment]
一度閉じましょうか。やってみてオーバーヘッドが激しい様ならオーバーヘッドが激しいというお題でもう一度議論しましょう。 :)

**Comment by koron** [comment]
代替手段があるために xlose/worksforme となった。
