### ISSUE TITLE
ユーザ定義イベントが欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#142]
observable observer な仕組みが欲しい。Vimの挙動に対するイベントではなく、例えば特定アプリのバッファに入った際に　MyAppEnter　みたいなイベントが作れればプラグインのプラグイン開発が楽になるんじゃなかろうか。

出きれば敷居を低める意味でも autocmd と同じ仕組みで動くと嬉しい。

**Comment by thinca** [comment]
すでにあります。
`:help User` `:help :doautocmd`

**Comment by koron** [comment]
Userは自動ではNever executedですよね。 @mattn の書きっぷりだとなんか自動実行されるモノっぽい。

**Comment by mattn** [comment]
それは知ってるのですが、それを自由な名前で作れるといいなーという意味す。
例えば`NeoComplCacheEnabled`とか、`CalendarDiaryClosed`とか...

**Comment by mattn** [comment]
要は名前だけ決めて、throwする側とcatchする側を造りたいのです。
そうしないと、受け側はそのアプリが入ってる前提のコードを書かなきゃいけないので...

**Comment by thinca** [comment]
しかしそうすると、Vim 本体が将来イベントを追加したい場合に衝突する恐れがあるのではあるのではないでしょうか?

**Comment by koron** [comment]
@mattn groupで識別するのも限界がある、とかそういう言い方かしらねぇ。

@thinca 名前空間わければ良いだけでは?

**Comment by mattn** [comment]
> しかしそうすると、Vim 本体が将来イベントを追加したい場合に衝突する恐れがあるのではあるのではないでしょうか?

そうそこ。そこをなんとかうまく出来ないかなーという意味なのです。(最初から書けよ)

**Comment by thinca** [comment]
その名前空間が `User` ではないんですかねぇ。
ちなみに念のための補足ですが、`User` イベントはパターンを使って区別します。

``` vim
" プラグイン側
doautocmd User NeoComplCacheEnabled

" ユーザ側
autocmd User NeoComplCacheEnabled echo 'enabled!'
```

**Comment by koron** [comment]
Userと同じ動作でいいなら、group名にu:とかプリフィクスをつけたらeventには自由に命名可能なUserと同等のイベント作れまっせ、ってすれば良いんじゃない?

**Comment by mattn** [comment]
@koron @thinca 今使い方知った！

**Comment by koron** [comment]
名前付けをずらさないとなんか困る気もするけどw

**Comment by mattn** [comment]
User ってイベント名しか使えないのかと思ってたw

**Comment by koron** [comment]
> 名前付けをずらさないとなんか困る気もするけどw

プラグイン間で、という意味ね。
なんかプラグイン同士の住み分けや連携を整えてあげる事は必要な気がしてきた。

**Comment by mattn** [comment]
ただ、今思ったんだけど引数で何か渡したいね

``` vim
doautocmd User ToMyObservers -args=l:hoge
```

みたく。イベント引数？そうなるともう autocmd でやる意味無いか。

**Comment by koron** [comment]
うん。ないねw

C#みたいにdelegateからevent作りましょう、的な話になってくる。

**Comment by mattn** [comment]
こんなので十分か...

autoload/observe.vim

``` vim

let s:observers = {}

function! observe#addObserver(name, func)
  if !has_key(s:observers, a:name)
    let s:observers[a:name] = []
  endif
  let func = type(a:func) == 2 ? string(a:func) : a:func
  if len(filter(copy(s:observers[a:name]), 'v:val==func')) == 0
    call add(s:observers[a:name], a:func)
  endif
endfunction

function! observe#notify(name, ...)
  if has_key(s:observers, a:name)
    for l:F in s:observers[a:name]
      try
        call call(l:F, a:000)
      catch
      endtry
    endfor
  endif
endfunction
```

example.vim

``` vim
function! s:SID()
  return matchstr(expand('<sfile>'), '<SNR>\zs\d\+\ze_SID$')
endfun

function! s:MyEventCatched(arg1, arg2)
    echo a:arg1
    echo a:arg2
endfun

call observe#addObserver("MyEvent",
\ function(printf('<SNR>%d_MyEventCatched', s:SID())))

call observe#notify("MyEvent", 1, 2)
```

**Comment by thinca** [comment]
簡単な文字列程度ならパターン経由で無理矢理渡せなくもないですが。

``` vim
doautocmd User MyEvent:hoge
doautocmd User MyEvent:huga

autocmd User MyEvent:* call s:f()
function! s:f()
  let arg = matchstr(expand('<amatch>'), ':\zs.*')
endfunction
```

まあ面倒だし応用範囲は広くない。
