### ISSUE TITLE
RegExp 最小マッチ (`.\{-}`) が 正しく動作しないケース がある

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim-jp/issues#1421]
## 不具合の内容

RegExp 最小マッチ `.\{-}` に対して、
特定のパターンで 最小でないマッチ を拾ってくるケース があるようです。

```text
    (hoge) fuga (piyo)
#   ^^^^^^      ^^^^^^
# (.\{-})  に対しては、ここがマッチ (OK)

    (hoge) fuga (piyo)
#   ^^^^^^^^^^^^^^^^^^
# (.\{-}o) に対しては、ここ全体 がマッチ (NG)

    (hoge) fuga (piyo)
#               ^^^^^^
# 本来は、最小マッチ なので、ここだけ のマッチになるべき
```

### 現象・ログ

上記の通り。

### 再現手順

上記の通り。

### 期待動作

上記の通り。

## Vimのバージョン

* 9.0.1403 (Windows環境)
* 9.0.749 (Ubuntu環境)

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 22H2 [Version 10.0.19045.3208]
    * Git for Windows SDK環境 で確認
* Ubuntu 18.04.6 LTS

## 使用している or 関係していそうなプラグイン

特になし

## その他

特になし

**Comment by kuuote** [comment]
`:h non-greedy` の結果には `
しかし、早い位置でマッチするものが、短いマッチよりも優先されます。例えば、"a\{-}b" は "xaaab" の "aaab" にマッチします。` と書かれており、今回のケースは恐らくこれに該当する物だと思われます。

**Comment by k-takata** [comment]
Vim に限らず他の多くの正規表現エンジンでも同じ仕様です。
括弧を結果に含めたくない場合には `.\{-}` ではなく `[^()]\{-}` などのように明示的に除外する必要があります。

**Comment by KSR-Yasuda** [comment]
なるほど、『`X\{-}`  で `X` を見つけたら、そこから最短のマッチ を見つける』という仕様で、
行頭の `(` からの最短 を見つけようとした、ということですね。
理解しました。
