### ISSUE TITLE
折り返されていると syntax ... conceal で非表示されない

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1424]
## 質問の内容
``` vim
syntax ... conceal
```

しても折り返されていると、その折り返されている縦方向の空間分はそのまま残りますが、これはカーソル移動によって表示範囲が大きく変わってしまう場合があるので、仕様なのでしょうか?

より具体的な再現方法を示します

``` sh
vim -u NONE +'set conceallevel=3 concealcursor= number cursorline | syntax match ConcealA /a\+/ conceal'
```

で起動したときのテキストと表示は次のようになります

![Screenshot from 2023-08-18 15-23-31](https://github.com/vim-jp/issues/assets/24851657/055a6615-0aac-4954-9464-5cc8b518e65c)
__conceal 文字列がカーソル行にがある時__
![Screenshot from 2023-08-18 15-23-10](https://github.com/vim-jp/issues/assets/24851657/efbdc4fd-bc88-4d5f-a739-8d98a60309e5)
__conceal 文字列がカーソル行にがない時__

``` vim
set number cursorline
```

は解りやすいように加えただけで、再現性に関係はありません

また breakindent が ON の場合、wrap が OFF だと折り返しが一切起きないので再現しません

## Vimのバージョン
> $ vim --version
> VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 18 2023 14:52:39)
> 適用済パッチ: 1-1736
> Compiled by xxx@xxx
> Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)

## OSの種類/ディストリ/バージョン
> $ cat /etc/os-release
> PRETTY_NAME="Ubuntu 23.04"
> NAME="Ubuntu"
> VERSION_ID="23.04"
> VERSION="23.04 (Lunar Lobster)"
> VERSION_CODENAME=lunar
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=lunar
> LOGO=ubuntu-logo
> $ uname -a
> Linux xxx 6.2.0-27-generic #28-Ubuntu SMP PREEMPT_DYNAMIC Wed Jul 12 22:39:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mattn** [comment]
この問題は以前修正を試みた事があります。

issue: https://github.com/vim/vim/issues/9443
pull-request: https://github.com/vim/vim/pull/10442

実際には、カーソルが移動されるたびに行内の見栄えの幅を再計算する必要があり、パフォーマンスを犠牲にしないと現状は直せないというのが原在のステータスです。

**Comment by iranoan** [comment]
本家のissueには有ったんですね
やはり現状ではしようということですか
ありがとうございました
