### ISSUE TITLE
RegExp: `/hoge/` に対して、パターン `\<hoge\>` がヒットしない

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim-jp/issues#1428]
## 不具合の内容

正規表現の `\<`, `\>` (単語の 先頭 / 末尾 にヒット) について、
`/` が 直前 / 直後 に現れる場合、ヒットしないようです。

### 現象・ログ

```
/ hoge /        # Match
/hoge/          # Unmatch

% hoge %        # Match
%hoge%          # Match

. hoge .        # Match
.hoge.          # Match

hoge            # Match
aaa hoge bbb    # Match
```

grepでは ヒットするようなので (i.e. `echo '/hoge/' | grep '\<hoge\>'`),
Vimの正規表現の側のバグ かと思いますが、どうでしょう？

### 再現手順

上記のテキストに対し、`:/\<hoge\>` を実施。

### 期待動作

上記の `/hoge/` のケースでも、正規表現がヒットする。

## Vimのバージョン

VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 04 2024 08:28:51)

## OSの種類/ディストリ/バージョン

* Microsoft Windows [Version 10.0.19045.3930] (Windows 10 Pro 64bit 22H2)
    * MSYS2環境 (`msys/base 2022.06-1`)
        * `msys/vim 9.1.0000-1` パッケージ

## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by k-takata** [comment]
`:set iskeyword?` の結果はどうなっていますか？

**Comment by KSR-Yasuda** [comment]
@k-takata
> `:set iskeyword?` の結果はどうなっていますか？

以下でした：

```vim
:set iskeyword?
iskeyword=@,48-57,_,192-255,*,/,#,$
```

`.vimrc` 等では 特に 変更していないです。

**Comment by KSR-Yasuda** [comment]
`vim -u /dev/null` で実施すると、
`iskeyword=@,48-57,_` で、`/hoge/` にもヒットしますね…。

なにかのプラグインで 変更されてる…？

**Comment by k-takata** [comment]
`:verbose set iskeyword?` でどこで変更されているか確認できます。

**Comment by KSR-Yasuda** [comment]
@k-takata
`verbose set iskeyword?` してみましたが、
ちょいちょい セットしているスクリプト が変わって、特定できないですね。

確認していた Vim の起動直後だと、以下の状態で、`/` は 含まれなくなりました。

```vim
:verbose set iskeyword?
  iskeyword=@,48-57,_,192-255,$
    最後にセットしたスクリプト: ~/.vimrc 行 3

        " `set nocompatible` で変更されている
```

なので、なにかのトリガで スクリプトが読み込まれて、`&iskeyword` が汚染されちゃってるっぽい。

何トリガで設定されちゃってるのか、もう少し 確認してみます。

**Comment by KSR-Yasuda** [comment]
`e scp://REMOTE_MACHINE/*` で、別のマシンのファイルを 2つ 開いたところ、
現象が発生しました。

```bash
# リモートマシン上で、以下で 空ファイル を作成。
% touch ~/a ~/b
```

```vim
" 空の vim をオープン
:verbose set iskeyword?
  iskeyword=@,48-57,_,192-255
    最後にセットしたスクリプト: ~/.vimrc 行 3

" SCPで、リモートマシンのファイル をオープン。
" 中身は 空 で作成。
" このときは 問題ない
: e scp://REMOTE_MACHINE/a
:verbose set iskeyword?
  iskeyword=@,48-57,_,192-255
    最後にセットしたスクリプト: /usr/share/vim/vim91/autoload/netrw.vim 行 1988

" SCPで、リモートマシンの別のファイル をオープン。
" 中身は 空 で作成。
" ここで、現象発生。
: e scp://REMOTE_MACHINE/b
:verbose set iskeyword?
  iskeyword=@,48-57,_,192-255,*,/
    最後にセットしたスクリプト: /usr/share/vim/vim91/autoload/netrw.vim 行 3009
```

----

スクリプトの該当部分 は、以下。

コメント的に、`&iskeyword` 内に `/` が含まれること を気にしている様子ですが、
事前に保存した変数からは 取り除けてなくて 汚染されている気がします。

```vim
/usr/share/vim/vim91/autoload/netrw.vim

2933 " ===========================================
2934 " s:NetrwGetFile: Function to read temporary file "tfile" with command "readcmd". {{{2
2935 "    readcmd == %r : replace buffer with newly read file
2936 "            == 0r : read file at top of buffer
2937 "            == r  : read file after current line
2938 "            == t  : leave file in temporary form (ie. don't read into buffer)
2939 fun! s:NetrwGetFile(readcmd, tfile, method)

                                     (snip)

2994    " rename buffer back to remote filename
2995    call s:NetrwBufRename(rfile)
2996 
2997    " Jan 19, 2022: COMBAK -- bram problem with https://github.com/vim/vim/pull/9554.diff filetype
2998    " Detect filetype of local version of remote file.
2999    " Note that isk must not include a "/" for scripts.vim
3000    " to process this detection correctly.
3001 "   call Decho("detect filetype of local version of remote file<".rfile.">",'~'.expand("<slnum>"))
3002 "   call Decho("..did_filetype()=".did_filetype())
3003 "   setl ft=
3004 "   call Decho("..initial filetype<".&ft."> for buf#".bufnr()."<".bufname().">")

3005    let iskkeep= &isk
3006    setl isk-=/
        ^^^^^^^^^^^
        ここで、設定の `&isk` からは `/` を取り除いているけど、
        保存している `iskkeep` は考慮してないから 汚染されている？

3007    filetype detect
3008 "   call Decho("..local filetype<".&ft."> for buf#".bufnr()."<".bufname().">")

3009    let &isk= iskkeep
        ^^^^^^^^^^^^^^^^^
        ここで汚染

3010 "   call Dredir("ls!","NetrwGetFile (renamed buffer back to remote filename<".rfile."> : expand(%)<".expand("%").">)")
3011    let line1 = 1
3012    let line2 = line("$")

                                     (snip)

3059 endfun
```

**Comment by k-takata** [comment]
3009行目は `let &l:isk= iskkeep` にすべき気がします。現状だと、グローバル値も変わってしまいそう。

**Comment by k-takata** [comment]
@KSR-Yasuda 3009行目を上記のように変更したときに、現象が解消するか試していただけませんか。

**Comment by KSR-Yasuda** [comment]
@k-takata
> 3009行目は `let &l:isk= iskkeep` にすべき気がします。現状だと、グローバル値も変わってしまいそう。

この変更だけで、確認のケースだと `/` は含まれなくなりました。

3005 ⇔ 3006 の順序入れ替え (i.e. `iskkeep` に保存する際にも `/` を除外)
しなくても いけてる理由が ちょっとよくわかんないですが…。

**Comment by k-takata** [comment]
3005行目で現在の 'isk' (おそらく `/` が含まれている) を iskkeep に保存し、3006行目で一時的に 'isk' から `/` を削除し、3009行目で 'isk' を元に戻しています。
問題は、`let &l:` ではなく `let &` を使っていたので、ローカル値を元に戻すだけではなく、グローバル値まで変更されてしまっていたので、そのあとに開くファイルの値に影響してしまっていました。

**Comment by KSR-Yasuda** [comment]
@k-takata
> 3005行目で現在の 'isk' (おそらく / が含まれている) を iskkeep に保存し、3006行目で一時的に 'isk' から / を削除し、3009行目で 'isk' を元に戻しています。
> 問題は、let &l: ではなく let & を使っていたので、ローカル値を元に戻すだけではなく、グローバル値まで変更されてしまっていたので、そのあとに開くファイルの値に影響してしまっていました。

globalの `&iskeyword` が汚染された、というのは わかります。

でも、最初のファイルのバッファは、動かしてみても `/`汚染されてないんですよね
(2番目 開いてから 1番目のバッファに戻しても)。
2番目のファイルのバッファ で初めて汚染されるの が、ちょっとよくわからなくて。

**Comment by KSR-Yasuda** [comment]
Ubuntu環境の v9.0.749 だと、ここ、正しいですね。

v9.0 ～ v9.1 のどこかで エンバグしてる？

```vim
/usr/share/vim/vim90/autoload/netrw.vim

2981    " rename buffer back to remote filename
2982    call s:NetrwBufRename(rfile)
2983 
2984    " Detect filetype of local version of remote file.
2985    " Note that isk must not include a "/" for scripts.vim
2986    " to process this detection correctly.
2987 "   call Decho("detect filetype of local version of remote file",'~'.expand("<slnum>"))
2988    let iskkeep= &l:isk
2989    setl isk-=/
2990    let &l:isk= iskkeep
2991 "   call Dredir("ls!","NetrwGetFile (renamed buffer back to remote filename<".rfile."> : expand(%)<".expand("%").">)")
2992    let line1 = 1
2993    let line2 = line("$")
```

**Comment by k-takata** [comment]
'isk' はバッファローカルなオプションなので、グローバル値が汚染されても、開いたままのバッファのローカル値には影響しません。
新しくバッファを開く際にグローバル値からコピーされるので、次に開くファイルから影響されることになります。

https://github.com/vim/vim/commit/71badf9547e8f89571b9a095183671cbb333d528
v172 からの問題のようですね。

**Comment by KSR-Yasuda** [comment]
upstreamへのpost, ありがとうございます。

てっきり 毎回 この部分を通ってる (i.e. 2番目のファイルも `setl isk-=/` してる) と思ってましたが；
2番目は 別のとこ通ってて、globalの `isk` 引っ張ってきてるだけ、ということなら 理解しました。

**Comment by k-takata** [comment]
取り込まれました。 https://github.com/vim/vim/commit/a262d3f41bc51be697ddebbf04f186e7d193fd6f
