### ISSUE TITLE
CUI 版の Vim で `setcellwidths` を呼び出し `2` を指定しても、描画時の幅が `1` と同じになる

### ISSUE THREAD

**Issue by mikoto2000** [vim-jp/issues#1430]
## 不具合の内容

CUI 版の Vim で `setcellwidths` を呼び出し `2` を指定しても、描画時の幅が `1` と同じになる。

カーソルの移動幅は `2` になっている。

`gvim.exe` では発生していない(GUI 版は Windows でしか確認できていません...)

### 現象・ログ

Windows 版 gvim(※OKな挙動):
![image](https://github.com/vim-jp/issues/assets/345832/7a624485-fe37-411e-9ce5-a6563752c5ce)

Windows 版 vim(※NGな挙動):
![image](https://github.com/vim-jp/issues/assets/345832/229a17da-2cfb-45c3-9763-1c4d7b3863e8)
※文字の描画は黄色矢印のところまでとなっているが、カーソル移動は緑矢印のところまで移動する

Docker 上の Debian Linux の vim(※NGな挙動):
![image](https://github.com/vim-jp/issues/assets/345832/b3531659-00b4-4fa8-ba14-96131a88c649)

### 再現手順

1. 以下のファイルを `test.txt` として作成
    ```txt
    0x279c:
    ➜➜➜➜➜
    ```
2. `vim` でファイルを開く
    ```
    vim -u NONE -N ./test.txt
    ```
3. 文字コードと幅を設定
    ```
    set encoding=utf-8
    call setcellwidths([[0x279c, 0x279c, 2]])
    ```

### 期待動作

`setcellwidths` で幅 `2` を指定した文字が幅 `2` で描画される。

## Vimのバージョン

9.1.282([vim-installer の v9.1.0282](https://github.com/vim/vim-win32-installer/releases/tag/v9.1.0282) で確認)

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

(なるべく詳しく書いてください 記述例:)

*   Windows 11 Pro 64bit 23H2 ビルド: 22631.3296
*   Linux Debian testing 64bit(Docker Image `debian:testing-slim`)

## 使用している or 関係していそうなプラグイン

なし

## その他

なし

**Comment by mikoto2000** [comment]
GUI 版のみで行われている処理として以下に目を付けて、 CUI 版の cellwidth が 2 の場合にも同じ処理を入れました。
https://github.com/vim/vim/blob/master/src/screen.c#L1992-L1995

```diff
diff --git a/src/screen.c b/src/screen.c
index 71ddbca..ba6a40b 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -1999,7 +1999,11 @@ screen_char(unsigned off, int row, int col)
            screen_cur_col = 9999;
        }
        else if (utf_char2cells(ScreenLinesUC[off]) > 1)
+       {
            ++screen_cur_col;
+           out_str((char_u *)"  ");
+           term_windgoto(row, col++);
+       }

        // Convert the UTF-8 character to bytes and write it.
        buf[utfc_char2bytes(off, buf)] = NUL;
```

Linux の CUI 版では改善しているように見えます。
![image](https://github.com/vim-jp/issues/assets/345832/9079bae0-92f7-43db-a93c-71c4f67022d7)

`make test` の結果も、修正前後で変わりませんでした。

```sh
Executed:  5948 Tests
 Skipped:   141 Tests
  FAILED:     3 Tests
```

修正の妥当性・影響範囲がわかっていませんが、ひとまず調べたこと・やったことを報告いたします。

**Comment by mikoto2000** [comment]
![image](https://github.com/vim-jp/issues/assets/345832/fc149974-33e1-4ad9-96ef-bc89c625a022)

前述の対応ではまだ以下の問題が発生するので、もっと根本的(？)な対応が必要そうです。

- 幅 `2` の文字と幅 `1` の文字の境目の描画位置がずれる
- 幅 `2` の文字を使用した行の `colorcolumn` の位置がずれる

**Comment by tsuyoshicho** [comment]
端末エミュレーターの文字幅解釈次第になる問題がありそうです。

**Comment by mikoto2000** [comment]
@tsuyoshicho 
コメントありがとうございます。

Windows Terminal でも、 mintty(wsltty) でも、Linux のターミナルでも起こりますので、端末エミュレーターの文字幅解釈次第という事はなさそうと思いました。

解釈間違いなど、ありそうでしたら指摘いただけるとありがたいです。

**Comment by mikoto2000** [comment]
GUI の処理からさらに、「カーソル位置リセット」の処理も持ってきたら期待通りの動きになりました。

件の文字は「あいまい幅」ではないのでもっとましな修正方法があるはずですが...

https://github.com/vim/vim/blob/master/src/screen.c#L1992-L1999

```diff
diff --git a/src/screen.c b/src/screen.c
index 71ddbca..1226a05 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -1998,9 +1998,19 @@ screen_char(unsigned off, int row, int col)
            // character
            screen_cur_col = 9999;
        }
-       else if (utf_char2cells(ScreenLinesUC[off]) > 1)
+       else if (utf_char2cells(ScreenLinesUC[off]) > 1) {
            ++screen_cur_col;

+           // Clear the two screen cells. If the character is actually
+           // single width it won't change the second cell.
+           out_str((char_u *)"  ");
+           term_windgoto(row, col);
+
+           // not sure where the cursor is after drawing the ambiguous width
+           // character
+           screen_cur_col = 9999;
+       }
+
        // Convert the UTF-8 character to bytes and write it.
        buf[utfc_char2bytes(off, buf)] = NUL;
        out_str(buf);
```
![image](https://github.com/vim-jp/issues/assets/345832/9742ce8d-8756-491e-87de-986c51626875)

**Comment by k-takata** [comment]
文字を全角幅で表示するか半角幅で表示するかは、端末ソフトと使っているフォントで決まり、端末ソフトが認識している文字幅とVimが認識している文字幅が一致していないときに、Vimが認識している文字幅を端末ソフト側に合わせるために使うのが 'ambiwidth' や `setcellwidths()` です。

`➜` の文字幅はUnicode的にはNeutral、つまり規定されていないということになっているので、結局は端末ソフトとフォント次第ということになるかと思います。端末ソフト側が半角幅で認識しているのであれば、今回のような動作になるのが想定通りかと思います。

上記のパッチで意図した通りになるのであればそれもありかもしれませんが、副作用がないかは気になります。

**Comment by mikoto2000** [comment]
@k-takata 
コメントありがとうございます。
自分のあいまい幅の理解と `setcellwidths()` の用途の理解が足りていなかったようです。
「あいまい(Ambiguous)」と「中立(Neutral)」というものがり、それぞれ別種であるというのも今調べて知りました...

`setcellwidths` は、「対象の文字種類にかかわらず指定された幅で表示するようになる」ものだと思っていました。

`ambiwidth` の対象文字(例えば `─`)は、 `ambiwidth=double` を指定すると描画幅、カーソル移動の両方とも幅 2 として扱われていましたので、`setcellwidths` で特定文字(今回の例だと`➜`) の幅を `2` と指定しても同じ挙動になるものだと...

だとすると、自分が欲しいのは新機能で、「文字幅の種類にかかわらず指定した幅で文字を描画できる機能」となりますか...。無理筋感...

**Comment by mikoto2000** [comment]
> 端末ソフト側が半角幅で認識しているのであれば、今回のような動作になるのが想定通りかと思います。

> だとすると、自分が欲しいのは新機能で、「文字幅の種類にかかわらず指定した幅で文字を描画できる機能」となりますか...。無理筋感...

「挙動が GUI と CUI で異なるため、 GUI に合わせるように修正する」という理由なら受け入れられますかね...？

**Comment by k-takata** [comment]
そうですね。それもありかと思います。

(Ambiguous と Neutral で挙動が違うのは何でだっけというのは気になっていますが。)

**Comment by mikoto2000** [comment]
ありがとうございます。
もう少しコードを読んで処理内容の理解をすすめ、ビルドフラグ含めた修正内容の検討をやってみます。

**Comment by mikoto2000** [comment]
ひとまず自分が思いつくパターンでは GUI 版と同様の挙動になりました。
`make test` も修正前後で失敗の数が変わらないことを確認しました。
![image](https://github.com/vim-jp/issues/assets/345832/c0c2c064-646c-4471-a05b-f6eb511d08e5)

```diff
diff --git a/src/screen.c b/src/screen.c
index 71ddbca..ba52d91 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -1999,7 +1999,28 @@ screen_char(unsigned off, int row, int col)
 	    screen_cur_col = 9999;
 	}
 	else if (utf_char2cells(ScreenLinesUC[off]) > 1)
-	    ++screen_cur_col;
+	{
+	    // 2 セルを使って描画するべき文字の場合
+	    // (`setcellwidths` で指定された文字で、文字の幅種別が「あいまい」でない場合もここに入る)
+
+#ifdef FEAT_GUI
+	    if (!gui.in_use)
+	    {
+#endif
+		// 幅種「あいまい」を幅 2 で描画する処理と同じ処理を行う
+		out_str((char_u *)"  ");
+		term_windgoto(row, col);
+		screen_cur_col = 9999;
+#ifdef FEAT_GUI
+	    }
+	    else
+	    {
+		// 元々は GUI/非GUI にかかわらず ++screen_cur_col するだけだったので、
+		// GUI 版では元と同じ処理を行う。
+		++screen_cur_col;
+	    }
+#endif
+	}
 
 	// Convert the UTF-8 character to bytes and write it.
 	buf[utfc_char2bytes(off, buf)] = NUL;
```

以下 2 点が現状の不安点です。

* CUI で Ambiguous と Neutral の挙動が違う理由が不明
* 影響範囲の確認方法がわからない

**Comment by mikoto2000** [comment]
あ、すみません、報告したつもりがコメントできていませんでした。
https://github.com/vim/vim/issues/14539 で Issue と Pull request を作成しました。

**Comment by mikoto2000** [comment]
ありがとうございました。
マージされました。
https://github.com/vim/vim/commit/e20fa59903525e15cecd680a2f32ece8a5d1bc0c
