### ISSUE TITLE
Waylandの対応状況

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1434]
## 質問の内容

質問というより、現状の確認と提案に成るのですが、GVim の Wayland への対応状況はどこまで進んでいると認識すればよいのでしょう?

現状だと、そのまま Wayland の環境で使うとウィンドウ・サイズを変えると、下図の様に描画がおかしくなります

![xorg](https://github.com/vim-jp/issues/assets/24851657/ddb38798-7633-4601-b12d-bb8698554b08)

また下図の様にかな漢字変換がインラインで表示されません

![xorg-nonumber](https://github.com/vim-jp/issues/assets/24851657/0adcfea2-50ce-42dd-9969-7b84cfdb866b)

後者ついては、次のどちらかを設定すれば改善されます

```vim
set number
```

```vim
set foldcolumn=1
```

Vim の Wayland 対応については

```vim
help gui-wayland
```

に GVIM_ENABLE_WAYLAND の記載があります

これをすることで描画が乱れる問題は解決するのですが、下図の様に number, foldcolumn の両方がないと、最初時だけですが入力と予測変換のウィンドウが重なり、非常に入力しづらいです

![wayland-nonumber](https://github.com/vim-jp/issues/assets/24851657/58c57c37-8fe5-471e-800b-37b9f8344d0b)

また GVIM_ENABLE_WAYLAND を未指定や X.org では下図の様に、変換中その対象は他と異なるハイライト表示に成るのですが、

![xorg-number](https://github.com/vim-jp/issues/assets/24851657/22eee8af-0c51-451b-ab67-ed43cbb95e83)

GVIM_ENABLE_WAYLAND を指定された Wayland では下図の様にハイライト表示されず、やはり使いづらいです

![wayland](https://github.com/vim-jp/issues/assets/24851657/f8ef1dfd-7bca-4ebe-b77f-95378f269676)

ネットを見ると、また IM に fcitx5 を指定するとログイン時に表示されるメッセージに従って  [Input Method Panel](https://extensions.gnome.org/extension/261/kimpanel/) をインストールしても改善しませんでした

なおこれについては Ubuntu 24.04 では公式リポジトリからは削除されているようなので、上記リンク先からインストールしました

ただこれについては、ハイライトされるアプリも有るのですが、FirefoxやLibreOfficeといった有名アプリも同様なので Vim の問題とは言い切れないかもしれません

最後にヘルプに書かれていないのですが

```vim
help clientserver
```

関係は使えませんでした
これは Waland による制限だとは思いますが、仕様であるなら gui-wayland の項目に記載があったほうが良いと感じました

## Vimのバージョン

```sh
$ vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jun 23 2024 18:32:02)
適用済パッチ: 1-516
Compiled by xxx@xxx
```

```sh
./configure --with-features=huge --enable-gui=gtk3 --enable-perlinterp=dynamic --enable-python3interp=dynamic --enable-rubyinterp=dynamic --enable-luainterp=dynamic --enable-fail-if-missing CC="$( command which clang )" CFLAGS='-O2'
```

でビルドしたものを使っています

## IM の組み合わせとバージョン

```sh
$ fcitx5 --version
5.1.7
```

mozc Ver.2.28.4715.102

## OSの種類/ディストリ/バージョン

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

```sh
$ uname -a
Linux xxx 6.8.0-36-generic #36-Ubuntu SMP PREEMPT\_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86\_64 x86\_64 x86\_64 GNU/Linux
```

**Comment by Shougo** [comment]
https://github.com/vim/vim/pull/9639

現在の wayland 対応状況は以下を参照してください。あくまで wayland 環境でも動作するように最低限の対応を行ったという認識であり、まだまだ不具合は残っていると思います。OSS は不具合が勝手に直ったりはしません。

> 現状だと、そのまま Wayland の環境で使うとウィンドウ・サイズを変えると、下図の様に描画がおかしくなります

resize の issue は見たところないので vim の issue に報告したほうがよいと思います。

> また下図の様にかな漢字変換がインラインで表示されません

これは日本人くらいしか使わない機能なので、対応されないのも仕方ないと思えます。こういう機能はおそらく日本人が対応を頑張らないといけないです。

clientserver 機能が動作しないのは既知の問題です。

> +clientserver depends on X11 and thus no longer works. It may be replaced by using D-Bus to communicate instead

ドキュメントに現在の制限として記載があったほうがよいとは確かに私も思います。

**Comment by iranoan** [comment]
> 現在の wayland 対応状況は以下を参照してください。あくまで wayland 環境でも動作するように最低限の対応を行ったという認識であり、まだまだ不具合は残っていると思います。OSS は不具合が勝手に直ったりはしません。
そういった状況なのですね

情報源を提供頂きありがとうございました

**Comment by iranoan** [comment]
> ただこれについては、ハイライトされるアプリも有るのですが、FirefoxやLibreOfficeといった有名アプリも同様なので Vim の問題とは言い切れないかもしれません

について、PPA 版にしていたことを思い出して、情報を再度再度検索してわかったのですが、GVIM_ENABLE_WAYLAND を有効にした GVim も含めて

```sh
sudo apt install fcitx5-frontend-gtk3
```

でパッケージを追加してやれば、日本語入力に関しては改善されることが分かりました

**Comment by Shougo** [comment]
なるほど。インライン入力に追加パッケージが必要になるのは理解できる話です

**Comment by iranoan** [comment]
Ubuntu 24.10ではGVIM_ENABLE_WAYLAND無しでも画面が乱れませんし、IMEのインライン入力は上記の通り解決方法がありますのでcloseしておきます
