### ISSUE TITLE
$MYVIMRC, $MYVIMDIRの値について

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1435]
## 質問の内容

dotfiles で管理する関係で、シンボリック・リンクを使っていて気がついたことがあり質問させてください

\~/.vim や ~/.config/vim が別のディレクトリのシンボリックだった場合、$MYVIMRC, $MYVIMDIR がそれぞれ

\~/dotfiles/.vim/vimrc, \~/dotfiles/.vim/
\~/dotfiles/.config/vim/vimrc, \~/dotfiles/.config/vim/

といった値になります

vimrc の中身を空にしても結果は変わらず、また後者については、環境変数に XDG_CONFIG_HOME は未定義です

ヘルプには

> The $MYVIMDIR environment variable is set to the personal 'rtp' directory,

とあり、

```vim
  :echo split(&runtimepath, ',')[0]
  /home/xxx/.config/vim
```

となりシンボリック・リンクは展開されず、ヘルプの記載と齟齬がでる結果になってしまいます

$MYVIMRC, $MYVIMDIR も runtimepath と同じくリンクを展開しないほうが良いともうのですが、皆さんはどう思われるでしょうか?

それほど困ることはないのですが、元々は &runtimepath から $MYVIMDIR を用いてユーザー設定の分を除いてリスト・アップしようとして気が付きました

## Vimのバージョン

```sh
$ vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Sep 14 2024 18:30:05)
適用済パッチ: 1-730
```

## OSの種類/ディストリ/バージョン

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ uname -a
Linux xxx 6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by h-east** [comment]
こちらでも同じ現象になりました。
報告の内容を vim_dev にも報告してはどうでしょうか？
（$MYVIMRC, $MYVIMDIR はシンボリックリンク展開するけど、`'runtimepath'` は展開しないということで、`:h $MYVIMDIR` に記載の以下の文章に齟齬があるということを報告）

```
The $MYVIMDIR environment variable is set to the personal 'rtp' directory,
```

---

おそらく、以前からある `$MYVIMRC` の値がシンボリックリンク展開しているので、`$MYVIMDIR` もそれに合わせたのだと思います。個人的には、今から `$MYVIMRC` や `'runtimepath'` のシンボリックリンクの扱いを変えるのは厳しいのではないかと考えます。

**Comment by h-east** [comment]
ping @iranoan 
> 報告の内容を vim_dev にも報告してはどうでしょうか？

上記をこちらで報告すれば良いです？
それとも、他の意見をお持ちですか？

**Comment by iranoan** [comment]
報告しようとして忘れていました
本家にうまく伝える自信がないので、報告していただけるとありがたいです

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/16257

**Comment by h-east** [comment]
注記(Note)を追加したPRがmergeされました。
https://github.com/vim/vim/commit/af0fed598889cbc2fbf286c1e282c27b92215e8d

**Comment by h-east** [comment]
@iranoan Thanks for reporting!
