### ISSUE TITLE
タブバー　の表示について聞きたいです。

### ISSUE THREAD

**Issue by roverttattsuo7** [vim-jp/issues#1436]
## 質問の内容
![vimsitsumon](https://github.com/user-attachments/assets/b12c2a0e-c619-4655-8900-b80cdd966f8d)

香りや ver で
7.4 -> 8.2 に更新しているのですが、
8.2 のタブバー　tabbar　が読みづらいです。
7.4 の仕様に戻す方法をご存じではないでしょうか。

## Vimのバージョン

8.2 7.4

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.10586)

**Comment by k-takata** [comment]
どこかで 'guioptions' から "e" オプションを削除していないでしょうか。(`:help go-e` を参照)
`:verbose set guioptions?` を実行すれば、どこで 'guioptions' を設定しているか分かるかもしれません。
"e" を削除しているところを直すか、.vimrc (あるいは .gvimrc) の適切な場所に `:set guioptions+=e` を書き足すとよいでしょう。

**Comment by k-takata** [comment]
話は変わりますが、本家のVimは既に9.1が出ています。
v9.1.0 正式版: https://www.vim.org/download.php
ナイトリービルド（毎日自動更新）: https://github.com/vim/vim-win32-installer/releases

香り屋Vimは最近更新されていませんので、新しいものを使いたいなら本家のリリースを使った方がよいでしょう。
（香り屋Vim固有のプラグインや設定は当然本家には含まれていませんので、それらが必要であればコピーするなどの作業が必要になりますが。）

**Comment by roverttattsuo7** [comment]
to k-takakta さん 
返信がおくれて申し訳ありません
ご対応ありがとうございます。　gui オプション e  見落としていました。自分起因ですね。
e ひとつでこんなに使いにくくなるとは、 自分一人では、Vim の森を軽く数日は迷っていたに違いありません。
的確なご指示有難うございます。

vim9 はスクリプト が速くなるとの情報ですが、  今のところ 自分にとって　速くなるメリットはない気がします。(十分速いです。)

**Comment by k-takata** [comment]
解決したようでよかったです。問題なければクローズお願いします。
