### ISSUE TITLE
`vimgrep!` で、`!`指定でも、対象のファイルにジャンプする

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim-jp/issues#1439]
## 不具合の内容

`vimgrep`, `lvimgrep`, および その`add`系のコマンド で、
コマンドに `!` を付けて実行すると、検索後のファイルジャンプ なし だったかと思います。

が、実施すると、`!`あり でも、検索後に ファイルジャンプしています。

外部の grepコマンドを使う `grep` だと、発生せず。
Vimの internal grep の `vimgrep`系 のみ で発生するようです。

### 現象・ログ

上記のとおり。

### 再現手順

```bash
% echo "a" > a
% echo "b" > b
```

```vim
# ファイル `a` をオープン
:e a

# カレント以下で、パターン `b` を検索
:vimgrep! /b/ ./*
# → ファイル `b` が引っ掛かる
# → ファイル `b` にジャンプする (NG)
```

### 期待動作

`vimgrep`系コマンドで、`!`指定 の場合に、検索結果に ファイルジャンプしない。

## Vimのバージョン

9.1.785

## OSの種類/ディストリ/バージョン

* Microsoft Windows 11 Pro 23H2 (Version 10.0.22631.4317)
    - MSYS2 (msys2-runtime 3.5.4-2)

## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

#1415 `vimgrep`時の `pwd`関連の修正 をレポートしていました。
該当コマンドなので、関連があるかも。

**Comment by mikoto2000** [comment]
vimgrep のヘルプを見ると、「先頭にジャンプしない」は検索フラグ `j` を使用するとなっています。
`!` は、「カレントバッファの変更ををすべて破棄する」となっていました。

>                         'j'  フラグ 'j' がない場合、Vim は最初のマッチへジャン
>                             プする。'j' がある場合は quickfix リストが更新さ
>                             れるだけである。[!] を付けるとカレントバッファに
>                             対する変更は全て失われる。

https://vim-jp.org/vimdoc-ja/quickfix.html#:vimgrep より

**Comment by mikoto2000** [comment]
grep の `!` の挙動は、 Note に記載されているのですね...

> Note: 検索結果へのリンク一覧を開くには :copen (:lgrep なら :lopen) が使
> われる。:silent コマンドを使うことで grep の出力が画面いっぱいに表示されるの
> を防ぐことができる。:grep コマンドを ":grep!" 形式で使うと最初のマッチに自動
> 的にジャンプしなくなる。これらのコマンドを組み合わせて NewGrep コマンドを作る
> と次のようになる:

https://vim-jp.org/vimdoc-ja/quickfix.html#grep より

**Comment by KSR-Yasuda** [comment]
え、`:vimgrep!`の挙動、ジャンプ抑制じゃない!?
以前は、そう思って使ってたような…。

`:vimgrep!` で (ジャンプ時に) ファイル変更破棄、って、
`:grep!` の ジャンプ抑制 とも逆だし、危ない感じですね。

**Comment by h-east** [comment]
更に、`'grepprg'` オプションを `internal` にした時の `:grep` の `!` の扱いは、`:vimgrep` の `!` の扱い (カレントバッファの変更を破棄) だという紛らわしさ。 😅

**Comment by h-east** [comment]
以下ブランチのソースコードおよび、ドキュメントを確認しましたが、`:vimgrep` の `!` は現バージョンと同じ仕様ですね。
https://github.com/vim/vim/commit/1423b9d3b8eec56227414417621350ac27af6fd7
```
commit 1423b9d3b8eec56227414417621350ac27af6fd7 (HEAD, tag: v7.0)
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sun May 7 15:16:06 2006 +0000

    updated for version 7.0
```

私が7系以降を使いだしたのは確か7.2だったと思うのですが、:vimgrepの `!` の仕様は変わっていないです。
ということで、:vimgrep の `!` がジャンプ抑制だったというのは @KSR-Yasuda さんの思い違いだと思います。

**Comment by KSR-Yasuda** [comment]
:ok:, ありがとうございます。
元からの仕様問題 ということで納得します。
