### ISSUE TITLE
Tiny版のVimで :set wildoptions=fuzzy 設定時にバッファ名補完で Segmentation fault

### ISSUE THREAD

**Issue by 826814741-6** [vim-jp/issues#1441]
## 不具合の内容

Tiny版のVimで`:set wildoptions=fuzzy`設定時に、バッファ名補完をするとSegmentation faultが起こります。

### 再現手順

```
$ /usr/bin/vim.tiny -u NONE --noplugin
```

起動後

```
:set wildoptions=fuzzy
:e any
:b <S-TAB>
:b any<S-TAB>
```

とすると

```
Vim: Caught deadly signal SEGV
Vim: Finished.

Segmentation fault
```

## Vimのバージョン

```
$ /usr/bin/vim.tiny --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44)
Included patches: 1-1378, 1499
```

ないし、投稿作成時のHEAD版(--with-features=tiny)

```
$ ./vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Dec 10 2024 02:17:02)
Included patches: 1-915
```

## OSの種類/ディストリ/バージョン

```
$ uname -a
Linux pc 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux
```

(Debian bookwormです)

## 一応の考察

buffer.cのExpandBufnames()後段、Tiny版ビルドでは(デフォルトでは)有効にならない、FEAT_VIMINFOで括られる箇所に原因があるように思います。

fuzzy設定時の補完結果は、ローカル変数(`fuzmatch`)に取得されるものの、当該箇所が無効のため、`fuzzymatches_to_strmatches()`によるコピーがなされません。よって補完結果の如何にかかわらず、引数`file`は関数冒頭でNULLに初期化されたままとなってしまい、表題のような結果に至ってしまうように思います。

以下のようなワークアラウンドで一応手元では落ちなくなりました。どなたか症状・パッチ等ご確認いただければ幸いです。

### ワークアラウンドパッチ

```
diff -druN vim.orig/src/buffer.c vim/src/buffer.c
--- vim.orig/src/buffer.c	2024-12-10 00:54:59.803650103 +0900
+++ vim/src/buffer.c	2024-12-10 00:56:33.868452011 +0900
@@ -3013,6 +3013,12 @@
 	if (fuzzymatches_to_strmatches(fuzmatch, file, count, FALSE) == FAIL)
 	    return FAIL;
     }
+#else
+    if (fuzzy)
+    {
+	if (fuzzymatches_to_strmatches(fuzmatch, file, count, FALSE) == FAIL)
+	    return FAIL;
+    }
 #endif
 
     *num_file = count;
```

**Comment by h-east** [comment]
考察あっていると思います。 :+1:
@826814741-6 さんのpatchで問題ないと思いますが、以下のpatchが良いように思います。
(どちらのpatchでも正常動作を確認しました)

```patch
diff --git a/src/buffer.c b/src/buffer.c
index 3b05f25d7..147d20dc7 100644
--- a/src/buffer.c
+++ b/src/buffer.c
@@ -2985,9 +2985,9 @@ ExpandBufnames(
 	    vim_free(patc);
     }
 
-#ifdef FEAT_VIMINFO
     if (!fuzzy)
     {
+#ifdef FEAT_VIMINFO
 	if (matches != NULL)
 	{
 	    int i;
@@ -3007,13 +3007,13 @@ ExpandBufnames(
 	    }
 	    vim_free(matches);
 	}
+#endif
     }
     else
     {
 	if (fuzzymatches_to_strmatches(fuzmatch, file, count, FALSE) == FAIL)
 	    return FAIL;
     }
-#endif
 
     *num_file = count;
     return (count == 0 ? FAIL : OK);
```

**Comment by 826814741-6** [comment]
@h-east さん、検証ありがとうございます 🙇

過不足ない素晴らしいpatchだと思います。ぜひそちらを基に進めていただければと思います。

(元の私の案では、FEAT_VIMINFOの有効・無効でfuzzyの判定方法がそれぞれ異なるロジックになってしまいますし)

**Comment by h-east** [comment]
PRed.
https://github.com/vim/vim/pull/16200

**Comment by 826814741-6** [comment]
[https://github.com/vim/vim/pull/16200#issuecomment-2531058971](https://github.com/vim/vim/pull/16200#issuecomment-2531058971) のtest29.inについてですが、

- tinytestsはcompatibleモードで動作
- 当該Segmentation faultは、文字列の一部を入力してからの補完発火でも発生

することから

```
-:b                   // How do I press Tab to start completion?
+:b b^E
```

とするのはいかがでしょうか。(^Eは`<C-v><C-e>`又は`<C-q><C-e>`での入力の意)

(なお

```
:b ^E^E
```

とすると、手元の環境ではパッチ前でもSEGVなしにテストをすり抜けてしまうため、上記の方法をとりました)

**Comment by h-east** [comment]
@826814741-6 Thanks! 検証している間に ChrisBra さんがよしなに対応してくれました。

**Comment by h-east** [comment]
Merged in [9.1.0918](https://github.com/vim/vim/commit/dff3c9c1a789351a741b6a430862c8b2a0eff383)

**Comment by 826814741-6** [comment]
色々と骨を折っていただき、ありがとうございます 🙇

(師走にほぼほぼ丸投げしてしまうという...なんともはや。感謝感謝です)

**Comment by h-east** [comment]
Thank you for reporting the issue, investigating, and creating the patch!
