### ISSUE TITLE
netrw: URIエンコード部分を含むURI を `gx` で開くと、化ける

### ISSUE THREAD

**Issue by KSR-Yasuda** [vim-jp/issues#1442]
## 不具合の内容

URLエンコード部分を含む、`https://www.example.com/#:~:text=%E3%81%82` のようなURL を、
`gx` (= `NetrwBrowseX`) で開こうとすると、
ブラウザでは、`https://www.example.com/#:~:text=/%E3/%81/%82` と、化けたURL が開かれます。

どこかの段階で、`%`部分を 余分にエスケープしてるような気がします。

### 現象・ログ

上記のとおり。

### 再現手順

1. `https://www.example.com/#:~:text=%E3%81%82` と バッファに記述する。
2. その上に カーソルを持っていき、ノーマルモードで `gx` のキー を入力する。
3. ブラウザで 該当URL を開こうとするが、URLが化けており、正しく開けない。

### 期待動作

記載通りのURL が開く。

## Vimのバージョン

9.1.866

## OSの種類/ディストリ/バージョン

* Windows 11 Pro 64bit 24H2 (Version 10.0.26100.2605)
    * MSYS2 (msys2-runtime 3.5.4-8)
    * Google Chrome v131.0.6778.140

## 使用している or 関係していそうなプラグイン

(関係していそうなプラグインなどがあればココに書いてください)

## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by KSR-Yasuda** [comment]
[ここ](https://github.com/vim/vim/blob/21c37d7f695077efe6df57806ff35da79adce1d5/runtime/autoload/netrw.vim#L5202) の `escape()` で エスケープされてる模様。

最終的に、この値を `shellescape(a:file, 1)` したものを、`g:netrw_browsex_viewer` に渡して実行しているようです。
こちらの環境だと、Windowsなので、`start`コマンド を設定しています。

**Comment by KSR-Yasuda** [comment]
コメントからすると、
`netrw#Open()` での `shellescape()` だと足りないから `escape()`導入した、とのことですが、
必要なんですかね？

手元で確認してみたところ、
`shellescape()` で、`#` `%` をエスケープしたうえで シングルクォートまでしてるので、
`shellescape()` だけで シェルコマンドに渡しても 問題ない状態 になってるような。

```vim
escape('hoge#fuga%piyo!', '#%')
" => hoge\#fuga\%piyo!

shellescape('hoge#fuga%piyo!', 1)
" => 'hoge\#fuga\%piyo\!'

" 現行 (エスケープが 余分？)
shellescape(escape('hoge#fuga%piyo!', '#%'), 1)
" => 'hoge\\#fuga\\%piyo\!'
```

**Comment by Shougo** [comment]
なるほど。これはバグなので本家に報告したほうがよさそうに見えます。

`git blame` で変更を追えるかもしれません。

**Comment by KSR-Yasuda** [comment]
[blame](https://github.com/vim/vim/commit/8b0fa7a565d8aec306e5755307d182fa7d81e65f) 見てみると、関数構成の変更 かなにかの範囲 にかかってるんですよね。
ここの `escape()` が導入されたコミットじゃない。

それ以上 追うのは、ちょっとやってないです。

ちょっと 手元直近、Win + MSYS2 の環境しかないんですが、
ほかの環境だと どうでしょうか？

**Comment by Shougo** [comment]
Vim 9.1.938 の Linux 環境で確認したんですが、`escape()` 結果もその部分のコードも同じなので問題はそのまま残っていると思います。

**Comment by KSR-Yasuda** [comment]
ありがとうございます。
Linux環境でも、ということなので、本家issue (https://github.com/vim/vim/issues/16252) 立てました。

**Comment by KSR-Yasuda** [comment]
(ふぇぇ、紛糾してるよォ… <本家issue)

**Comment by Shougo** [comment]
結局何が問題になっているのかが分からない……

**Comment by KSR-Yasuda** [comment]
まとめると：

『Ubuntu 22.04 with Vim 9.1.919 だと、`#` のエスケープ を取ると バグる』って 物言いがついたんですよね。
なので、`%` のエスケープ は 取っていいけど、`#` は エスケープしたまま、と言われてる。

で、私の Win + MSYS2 の環境で、
『`https://www.example.com/#:~:text=/%E3/%81/%82` と、
エスケープの `\` でなく、`/` に化けてるのは なんぞ？』
と 話が逸れてました。

『これは、多分、MSYS2のパス変換
(MSYS2上は、パスセパレータ `/` だけど、Win上は `\` なので、適宜 変換してる；
`MSYS_NO_PATHCONV` とかで抑制可能)
由来ちゃうか？』
と 私が言ったところ、
そっちに 議論がズレてってた感じ。

でも、結局、余分な `\` でも `/` でも 出てくる時点で ダメではないかな、と。

`#`のみのエスケープ としても、
例えば、`https://www.example.com/#hoge#fuga` のようなURLだと、
`https://www.example.com//#hoge/#fuga` とかにアクセスに行くかと思います (未実験ですが)。

多分、余分な `escape()` で、`#` → `/#` に 軒並み 変換されますが、
パス名部分の 余分な `/` は トリムされて、問題なくなります
(最初の例だと、それで、`#`のエスケープ は 問題なかった；
多分、ブラウザに渡されるまで の時点でも、適当に トリムされてる気がする)。
でも、アンカー名部分の中に 更に `#`が出てくるの は、
アンカー参照の内容自体 変わっちゃうので、やっぱり ダメちゃうか、と思っています。

Linux環境で ご確認いただいて OKだった、とのことですし、
コマンド `:exe '!echo ' .. shellescape('...',1)` で見てみたら 問題なさそうよ？ とのコメもついてますし、
最初の物言い自体 環境要因 ちゃうかな、とも思ったり。

**Comment by Shougo** [comment]
> 『Ubuntu 22.04 with Vim 9.1.919 だと、# のエスケープ を取ると バグる』って 物言いがついたんですよね。
> なので、% のエスケープ は 取っていいけど、# は エスケープしたまま、と言われてる。

これよく分からないですね。最小構成で確認したいんですけど

もしかして、alternate file に誤解されるということかな。
`:e https://www.example.com/#hoge#fuga`
で alternate file エラーが出るのは確かに手元でも確認。

**Comment by KSR-Yasuda** [comment]
でも、そうすると、`%` は OK, というのが よくわからないんですよね。
`#` が alternate file に誤解されるような状況なら、`%` も 誤解されて然るべき。

元々の `escape(fname, '#%')` の導入意図は、多分 そのへんでしょうし。

**Comment by Shougo** [comment]
私の手元でも確認中です

**Comment by h-east** [comment]
9.1.0950 手前で修正されました。
[runtime(netrw): do not double escape Vim special characters](https://github.com/vim/vim/commit/2328a39a54fbd75576769193d7ff1ed2769e2ff9)

**Comment by h-east** [comment]
@KSR-Yasuda 問題無ければ、Close issueお願いします。

**Comment by KSR-Yasuda** [comment]
ありがとうございます。
修正のマージ、確認しました。
