### ISSUE TITLE
vim9script でスクリプトローカルな関数の記載場所を調べる方法は?

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#1443]
## 質問の内容

```vim
:function {1}
```

といった記述で、スクリプト・ローカルな辞書関数の内容を見られますが、vim9script ではどの様に記述するのでしょうか?

```vim
let s:sample = {}

function! s:sample.sample() abort
	return
endfunction
```

といった適当な関数を準備して

```vim
:vim9cmd function {1}
```

とすると

![vim-function](https://github.com/user-attachments/assets/0672df02-c77f-4cf6-b093-4695e9e6c7a7)

の様に同じ引数でも vim9script (``vim9cmd``) ではエラーになってしまいます

``:legacy`` を使うしかないのでしょうか?

## Vimのバージョン

```sh
$ vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Dec 20 2024 16:17:55)
適用済パッチ: 1-949
Compiled by xxx@xxx
Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)
```

## OSの種類/ディストリ/バージョン

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo
$ uname -a
Linux xxx 6.11.0-13-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov 30 23:51:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

## 使用している or 関係していそうなプラグイン

なし

**Comment by tsuyoshicho** [comment]
@iranoan さん

vim9.txt にありますが、呼び出しはできるが、辞書関数のvim9でのサポート、定義は、ないはずです。

以下は vim9.txt の該当箇所と日本語翻訳の抜粋です

```
						*vim9-no-dict-function*
You can use a Vim9 Class (|Vim9-class|) instead of a "dict function".
You can also pass the dictionary explicitly: >
	def DictFunc(self: dict<any>, arg: string)
	   echo self[arg]
	enddef
	var ad = {item: 'value', func: DictFunc}
	ad.func(ad, 'item')

You can call a legacy dict function though: >
	func Legacy() dict
	  echo self.value
	endfunc
	def CallLegacy()
	  var d = {func: Legacy, value: 'text'}
	  d.func()
	enddef

===

						*vim9-no-dict-function*
「辞書関数」の代わりに Vim9 クラス (|Vim9-class|) を使用できます。辞書を明示的
に渡すこともできます: >

...
一方、旧来の辞書関数を呼ぶことはできます: >
```

タグ名的にも英文的にも古い形式であって、vim9でのサポートはないと思います。
ですので、希望の操作はできないのではないかと。

cc: @h-east 、他有識の方がいれば

**Comment by h-east** [comment]
> vim9.txt にありますが、呼び出しはできるが、辞書関数のvim9でのサポート、定義は、ないはずです。

そのようです。

以下をファイル名 vv2.vim で保存して実行すると...
```vim
vim9script

var sample = {}
function sample.sample() abort
    return
endfunction
```
以下エラーが出力されますし。
```
Error detected while processing /path-to-your/vv2.vim:
line    4:
E1182: Cannot define a dict function in Vim9 script: sample.sample() abort
```

---

PS
`:h E1182` が何故か blob のとこに飛ぶのは間違いですね。あとで本家にPR送ります。

**Comment by iranoan** [comment]
定義に関してclassを使えるので不要だと思います
ただ質問内容は定義方法ではなく、「関数の記載場所を調べる方法」です

元々は公開されているプラグインでエラーが発生した時に、その記載ファイル、記述箇所を調べるスクリプトを vim9script で書いていて気がつきました

>				*:fu* *:function* *E128* *E129* *E123* *E454*
側の使い方として

```vim
verbose function {1}
```

に当たる処理をした時、旧来のスクリプトでは問題なのですが、vim9script ではエラーになってしまいます

現状 vim9script 中ではエラーになるで仕方がなく

```vim
legacy verbose function {1}
```

に当たる処理をさせているのですが、より良い方法が有ればと思い質問しました

**Comment by h-east** [comment]
> ただ質問内容は定義方法ではなく、「関数の記載場所を調べる方法」です

失礼しました。

> legacy verbose function {1}

上記 `:legacy` を使う方法がbetter、いやそれしか方法がないのではないかと思います。

**Comment by iranoan** [comment]
そうなんですね
私がヘルプを読み切れていないだけで、ひょっとして{}以外を使う可能性も考えたのですが…
解決したのでcloseします
