### ISSUE TITLE
vi 互換モードで、行頭の 1 文字を c や s で変更する時に $ が表示されない

### ISSUE THREAD

**Issue by hdk1983** [vim-jp/issues#147]
vi 互換モードで、行頭の 1 文字 (タブを除く) を c や s で変更する時に、$ が表示されません。
cpoptions の $ がセットされている時に発生します。

再現手順:
1. vim -u NONE で vim を起動する
2. :set cpoptions+=$
3. hoge という文字列を入力する (ahoge[ESC])
4. 行頭の 1 文字だけを c または s で置き換えて編集する (0s, 0cl, 0lc0 など)
期待される画面表示:

<pre>$oge</pre>

実際の画面表示:

<pre>oge</pre>

ソースを見ると、$ のカーソル位置が行頭になった時に、$ を表示していない時との区別がつかなくなるようです。パッチを作ってみました。
http://code.google.com/r/hdk1983-vim/source/detail?r=2791bbcc1ae2bcf990dc1927389df2faab2d0b5a

**Comment by ynkdir** [comment]
ありがとうございます。
とりあえず動作確認しました。
LGTM

**Comment by h-east** [comment]
こんばんは。GJ!
以下、個人的な意見です。
・`dollar_vcol`の有効無効を表すフラグ変数(例えば)`dollar_vcol_valid`を用意してそれで制御するようにした方がアドホック感がなくなって良いかなと思いました。

**Comment by h-east** [comment]
個人的な意見の続きです。

もしくは
現状、「dollar_vcolが0の時無効。 >0 で有効」
となっているのを、実際は0も有効な値なので、
「dollar_vcolが-1の時無効。 >=0 で有効」
として修正するとかでしょうか。

**Comment by mattn** [comment]
@hdk1983 awesome. LGTM

私も @h-east さんの後者の意見と同じです。
あともし英語での報告をお願いするとしたら可能ですか？

**Comment by hdk1983** [comment]
@h-east さん:
ソースコード中に if (dollar_vcol) あるいは if (dollar_vcol == 0) のように 0 かどうかの判定を行う部分が多数あり、修正内容をシンプルにわかりやすくするためこのような修正にしました。Vim のソースコードを見てこのくらいは許容されるのかなと感じたためでもあります。

@mattn さん:
私が英語で報告してもいいのですが、Vim のヘビーユーザーでもないので、慣れている方が代わりにサクッと報告してくれるとうれしいです。

**Comment by mattn** [comment]
@hdk1983 パッチファイルの先頭に名前を乗せる事になりますが、Hideki EIRAKUさんでよろしいですか？

**Comment by h-east** [comment]
@hdk1983 
dollar_vcolの値の有効範囲が間違っていたのでそれは全体的に修正したほうが良いと思います。
（そうしないと、後でこの部分のソースをみた人々が迷い易くなってしまうので。）
変更箇所が1000カ所あったらさすがに考えますが、20カ所なら(私なら)サクっと修正しちゃいます。

どのようなpatchにしても取り込む判断をするのはもちろんBram氏なので、私の意見はあくまでも参考意見程度に受け取って下さいー。

**Comment by hdk1983** [comment]
@mattn さん: はい、だいじょうぶです。ありがとうございます。

@h-east さん: たしかに 1 画面におさまる程度の量ですので、この際すべて修正するほうがいいという考え方もありますね。どちらでも、Vim ハッカーの方におまかせします。

**Comment by mattn** [comment]
@h-east どっちにするかはお任せします。

**Comment by h-east** [comment]
@mattn 
patch書きました。
https://gist.github.com/1694734

**Comment by mattn** [comment]
@h-east ++

あざす。動作確認して報告しときます。
作業してもらって申し訳ないすが hdk1983 さんのクレジットにさせて貰います。

**Comment by h-east** [comment]
@mattn OKっす。

**Comment by mattn** [comment]
報告ed

https://groups.google.com/d/topic/vim_dev/jerD6deKGH4/discussion

ヘタな英語が心苦しい...

**Comment by hdk1983** [comment]
ありがとうございます!

**Comment by h-east** [comment]
Patch 7.3.426で取り込まれました！
(dollar_vcolの無効判定方法がちょびっとだけ変わったけど^^)
https://groups.google.com/d/topic/vim_dev/6P7TjEfbb5s/discussion

**Comment by mattn** [comment]
@hdk1983++ @h-east++
