### ISSUE TITLE
vi 互換モードで、an Empty region に対するコマンドがエラーになった時の "." コマンドの動作が不正

### ISSUE THREAD

**Issue by hdk1983** [vim-jp/issues#148]
vi 互換モードで、an Empty region に対するコマンドがエラーになった時の . (ピリオド) コマンドの動作が不正です。An Empty region に対する操作がエラーになる、cpoptions E がセットされている時に発生します。
不正というのは、コマンドがエラーになっているにも関わらず、次の . コマンドでエラーになったコマンドが再実行されたり、. コマンドの処理中にエラーが発生しているにも関わらず、. コマンドの処理が中止されません。

再現手順 (1):
まず簡単な例を示します。
1. vim -u NONE で vim を起動する
2. :set cpoptions+=E
3. hoge という文字列を入力する (ahoge[ESC])
4. 行頭で an empty region に対するエラーになる操作を行う (0c0, 0y0, 0d0 など)
5. . (ピリオド)でコマンドを再実行する
期待される結果:
3 のコマンドが再実行され、以下のような表示になる:

<pre>hhogeoge</pre>

実際の動作:
4 で失敗したはずのコマンドが再実行される。

再現手順 (2):
ちょっと複雑な例を示します。
1. vim -u NONE で vim を起動する
2. :set cpoptions+=E$
3. foo という文字列を入力する (afoo[ESC])
4. c0 を使って hogeo という文字列にする。c0 の後にバックスペース等を使わず確実に h を入力する (c0hoge[ESC])
5. 行頭で . (ピリオド) コマンドを実行する (0.)
ビープ音が鳴り何も起きない
6. 行末に移動し . (ピリオド) コマンドを実行する ($.)
期待される結果:
4 のコマンドが再実行される。内容は変化しない。
実際の動作:
c0 だけを入力したのと同じ状態になる。以下のような表示になる:

<pre>hog$o</pre>

実は、5 の時に Vim は h をカーソル移動として実行しようとして失敗し、ここで . (ピリオド) コマンドの実行が中止されています。

再現手順 (3):
ちょっと極端な例を示します。
1. vim -u NONE で vim を起動する
2. :set cpoptions+=E
3. hoge という文字列を入力する (ahoge[ESC])
4. 次のような操作を (間違えてバックスペース等を入力しないように) 行い、文字列を変更する: c0:q![RET][ESC]
画面は以下のようになり、行頭の e のところにカーソルが来る:
<pre>:q!
e</pre>5. . (ピリオド)でコマンドを再実行する
期待される結果:
4 のコマンドの再実行には失敗するので、何も起きない。
実際の動作:
4 のコマンドの再実行に失敗しているにも関わらず後ろの入力である :q! が引き続き処理され、vim が終了する。

vim-tiny で vi 互換モードをよく使っているのですが、癖で c0 という操作をよく使っているようで、見つかりました。. コマンドで入力モードに入ったままになるというのは、traditional vi ではありえない動作なので、結構気になります。
パッチを作ってみたのですが、これで問題ないかどうかの自信はありません。修正内容も、とりあえず気になるところだけ直したので、他にも (例えば互換モードでなくても) . コマンドの問題が起きるパターンがあるかも知れません。
https://code.google.com/r/hdk1983-vim/source/detail?r=f8fd62f7777cf2d0cc1fdd47fbc465e230520877

互換モードユーザーは少ないかも知れませんが、vim はいろんな Linux ディストリビューションで vi の代わりの標準コマンドとして採用されていて、触る機会が多いので、このような互換モードのバグも適切に修正されると嬉しいです。

**Comment by ynkdir** [comment]
こちらも動作確認だけしました。
互換性確認は http://ex-vi.sourceforge.net/ です。これも完全にオリジナルではないみたいですが...
パッチの内容についてはよくわかりません。

**Comment by mattn** [comment]
ありがとうございます。
内容については問題無いと思いますが、コードのスタイルが合ってないかと思いました。

``` c
if (empty_region_error)
    vim_beep(), CancelRedo();
```

は、やはり

``` c
if (empty_region_error)
{
    vim_beep();
    CancelRedo();
}
```

とした方がいいかと思います。また

``` c
while (read_stuff(TRUE) != NUL)
    ;
```

はvimのコードに無いスタイルなので

``` c
while (read_stuff(TRUE) != NUL);
```

が良いと思いました。というか、`CancelRedobuf()` がなぜいままで無かったのか...。

**Comment by hdk1983** [comment]
@mattn さん:
{ } の件、修正しました。
https://code.google.com/r/hdk1983-vim/source/detail?r=e07a94b1cfd8f0273317816da73350dab25ffc65

while () は実は、同じファイル中の flush_buffers() 関数からのコピー &amp; ペーストです。同じファイル中で違う表記というのも変かと思ってそのままにしてあります。

**Comment by mattn** [comment]
okす

**Comment by mattn** [comment]
ヘタな英語で申し訳ないですが、報告しました。

https://groups.google.com/d/topic/vim_dev/m18JK3kW_zU/discussion

**Comment by ynkdir** [comment]
お疲れさまです。

```
Bram wrote:
Your patches often have indent removed.  Would there be a way to avoid
that? 
```

mattnさんのメールはHTMLメール(たぶん)になってて
text/html の方はインデントがついてますが
text/plain の方はタブ文字が削除されてるみたいです。

ブラウザで gmail で見るとインデントは付いてるように見えます (そこからコピペするとタブ文字はなくなりますが...)。
google groups で見るとインデントは付いてないです。

**Comment by hdk1983** [comment]
ありがとうございます!

**Comment by h-east** [comment]
Patch 7.3.429で取り込まれました！
https://groups.google.com/d/topic/vim_dev/8qkwEjFxllY/discussion

**Comment by mattn** [comment]
@hdk1983++
