### ISSUE TITLE
charset.c, digraph.cに非ASCII文字がある

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#15]
MSVCコンパイラが文句言ってる…
これ本家で直されたんじゃなかったっけ?

**Comment by mattn** [comment]
vim-devで見た気がするけど、今コンパイルしても出ますね。

**Comment by mattn** [comment]
これか
https://groups.google.com/d/topic/vim_dev/hGmSqE4hlm8/discussion

**Comment by mattn** [comment]
MSVCってコメント行でも非ASCIIな文字があると警告出るのねw
おせっかいすぎるw

**Comment by mattn** [comment]
リテラル内は patch 7.3.527 で直ったみたい。

https://groups.google.com/d/topic/vim_dev/NHM3t5DKHes/discussion

digraph.c はコメント内なので影響も無いだろうという事で、いったんクローズしますね。
