### ISSUE TITLE
タイマーが欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#150]
バッファローカルupdatetime?

**Comment by Shougo** [comment]
> バッファローカルupdatetime?

そうですね。ただ、updatetimeとは別の仕組みにしたほうがよいと思います。
なぜなら、CursorHoldIをタイマー代わりに使う仕組みがそもそも副作用が大きすぎるからです。
無意味なswapファイルへの書き込みが頻発してしまいます。

できれば、バッファローカルなだけでなく、プラグインローカルとなるような仕組みがほしいですね。
タイムアウトもプラグイン毎に設定したい。
これは比較的大きなパッチになるでしょう。
しかし、多くのプラグインにおいて性能改善や実装の簡単化・競合の解消につながりますし、「マルチスレッド欲しい」という要望に対する一つの解決方法になるのではないかと考えています。

**Comment by thinca** [comment]
この手の話題はvim_devでも以前上がってた気がしますね。どこだったかな…(探したけど見付けられなかった)。
JavaScriptのsetTimeout()的な提案もその中でされていたように記憶しています。

**Comment by mattn** [comment]
これかな？

https://groups.google.com/forum/#!topic/vim_dev/LZGIREwdHfE/discussion

**Comment by Shougo** [comment]
それっぽいですね。RepeatするCursorHoldI = Timerでしょうね。

**Comment by Shougo** [comment]
こんにちは。ヤル気が出たので、まずは仕様を考えてみることにしました。

```
autocmd Timer <time=N> {pat} {cmd}
autocmd TimerI <time=N> {pat} {cmd}
```

タイマーグループはaugroupで代用することにしましょう。
CursorHoldIを参考にすれば実装できると思います。タイマーが呼ばれる時間は`<time=N>`で指定します。
省略されると 'updatetime' の値を使用します。
autocmdのデータ構造に変数を追加する必要があります。

**Comment by Shougo** [comment]
パッチは自分で実装する予定ですが、なにかアドバイスがあればよろしくおねがいします。

**Comment by Shougo** [comment]
タイマー機能のパッチを実装した人が現れたので、ちょっとこちらはどうしましょうか……。

https://github.com/vim-jp/issues/issues/19

今のところは様子見ですが、議論の流れによってはcloseするべきかもしれません。

**Comment by Shougo** [comment]
https://github.com/vim-jp/issues/issues/19

こちらがあるので、ここは重複としてcloseします。
