### ISSUE TITLE
:all! と :sall! が E477になる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#153]
#127 の修正中に発見したバグです。

ヘルプには `!` が付けられる説明になっているけど、実際に使用するとエラー`E477`になります。

patch作成済みです。
:all! とか :sall! したら E477になるのを修正するpatch
https://gist.github.com/1670489

**Comment by h-east** [comment]
今からtest31にこれのテストを追加する作業やってみます。

`src/testdir/` 配下のファイルの説明とかガイドラインとかないんでしたっけ？見よう見まねでやるしかない？？

**Comment by h-east** [comment]
test31にテストを追加しました。
https://gist.github.com/1670489

**Comment by ynkdir** [comment]
お疲れさまです。
テストは見よう見まねでやるしかないですね。
いちおうテスト走らせてみました。okでした。
たいしたことではないんですがパッチファイルの末尾の改行がなくてpatchコマンドがエラーになりました。

**Comment by h-east** [comment]
@ynkdir チェック＆指摘ありがとうございます。

> たいしたことではないんですがパッチファイルの末尾の改行がなくてpatchコマンドがエラーになりました。

あっ、こっそり直しましたｗ。

**Comment by h-east** [comment]
初投稿ed. (メールで2回、Webで2回の計4回のpost ｗｗ。)
https://groups.google.com/d/topic/vim_dev/lFFp9VdQTjI/discussion

**Comment by mattn** [comment]
ゾンビメールがいっぱいw

**Comment by h-east** [comment]
todoリスト入り。

> Patch to allow ! for :all and :sall, as documented. (Hirohito Higashi, 2012
> Jan 30)

**Comment by h-east** [comment]
Patch 7.3.444で入った。
https://groups.google.com/d/topic/vim_dev/OT9vRMuiJ7c/discussion
