### ISSUE TITLE
syntax/vim.vimをなんとかしたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#155]
直してやろうという人いない？

**Comment by Shougo** [comment]
みんなの力を結集すれば……。

各自がいじっているので、その成果をどうにか合わせたいところです。
管理しやすいように、リポジトリを作ってみるという手がありますね。

**Comment by Shougo** [comment]
私はやりたいんですが、もっと修正してくれる人数いないかなと思う次第なのです。

**Comment by koron** [comment]
とりあえずイケてない点を列挙&整理したら?

**Comment by mattn** [comment]
小出しに...
- `let l:read = foo` の read がコマンド扱い
- `let foo = bar / 2` の bar がコマンド扱い
- `let foo = bar + 1` の + はオペレータ扱いなのに `let foo = bar * 2` や `let foo = bar / 2` の */ がオペレータ扱いじゃない

などなど。

**Comment by Shougo** [comment]
確か、thincaさんも以前列挙していた気がしますね。

**Comment by thinca** [comment]
個人的には完全に書き直したいところ。

**Comment by koron** [comment]
全部書きなおしたとしてどのくらいの時間がかかりますか?

**Comment by thinca** [comment]
調整まで含めるとかなりかかるでしょうね。叩き台が丸々1日でできれば御の字と言ったところでしょうか。

**Comment by Shougo** [comment]
あと、callがないときやletがないとき、Error表示にしたいです。初心者はよく忘れるので。

**Comment by mattn** [comment]
> あと、callがないときやletがないとき、Error表示にしたいです。初心者はよく忘れるので。

これはある意味不可能に近いんじゃないかな。

```
ab()
```

はvimコマンドとしてもありえるんだけど（:abbr ())、これを関数として見てしまった場合callが無いと判断する事自体が間違ってるはず。また

```
put="foo"
```

を

```
let put="foo"
```

と誤認識する可能性もあるので、結構難しいかと思いますよ。

**Comment by koron** [comment]
syntaxで書けるかどうかは別として、Vimコマンドのいずれでも無い事を条件にするんかね?w

真に不可能ならVimは動作しないわけだから。

**Comment by mattn** [comment]
そもそもASTとして腐ってますからね。

**Comment by koron** [comment]
AST ってどういう意味? [コレ](http://ja.wikipedia.org/wiki/%E3%82%A2%E3%82%B9%E3%83%91%E3%83%A9%E3%82%AE%E3%83%B3%E9%85%B8%E3%82%A2%E3%83%9F%E3%83%8E%E5%9F%BA%E8%BB%A2%E7%A7%BB%E9%85%B5%E7%B4%A0) なわけないよね?w

**Comment by h-east** [comment]
なわけないｗｗ
たぶん→AST (Abstract Syntax Tree, 抽象構文木)

**Comment by mattn** [comment]
[AST48](http://ja.wikipedia.org/wiki/%E6%8A%BD%E8%B1%A1%E6%A7%8B%E6%96%87%E6%9C%A8)ですが、何か。

**Comment by crazymaster** [comment]
![Screenshot_from_2013-04-27 20:55:58](https://f.cloud.github.com/assets/1528093/435059/472ca35c-af94-11e2-8aea-d177993e1a84.png)
function hoge()の後にスペース空けると解消される。

**Comment by crazymaster** [comment]
![Screenshot_from_2013-04-28 08:47:09](https://f.cloud.github.com/assets/1528093/435061/cf60cfe6-af94-11e2-9178-96b014876b57.png)
なんかいろいろとひどい

**Comment by Shougo** [comment]
> function hoge()の後にスペース空けると解消される。

これは最近のバージョンでそうなるようになりました。理由はわかりませんが、わざとなのかなと思っています。

**Comment by crazymaster** [comment]
変数で`#`があると色がつかないのなんとかして欲しいなあ

**Comment by mattn** [comment]
単純にそこだけ直すなら

``` diff
diff -r 99b2236c037c runtime/syntax/vim.vim
--- a/runtime/syntax/vim.vim    Mon Jun 03 12:17:05 2013 +0200
+++ b/runtime/syntax/vim.vim    Mon Jun 03 20:06:27 2013 +0900
@@ -104,7 +104,7 @@
 " All vimCommands are contained by vimIsCommands. {{{2
 syn match vimCmdSep    "[:|]\+"    skipwhite nextgroup=vimAddress,vimAutoCmd,vimCommand,vimExtCmd,vimFilter,vimLet,vimMap,vimMark,vimSet,vimSyntax,vimUserCmd
 syn match vimIsCommand "\<\h\w*\>" contains=vimCommand
-syn match vimVar        contained  "\<\h\w*\>"
+syn match vimVar        contained  "\<\h[a-zA-Z0-9:#_]*\>"
 syn match vimVar       "\<[bwglsav]:\h\w*\>"
 syn match vimFBVar      contained   "\<[bwglsav]:\h\w*\>"
 syn keyword vimCommand  contained  in
```

**Comment by mattn** [comment]
こういうのの治し方をお教えしておきますので、皆さんぜひpatch authorになって下さい。
1. 正常に色が付くファイルを開く
2. おかしくなる予定の位置にカーソルを移す
3. 以下を実行(今回だと vimVar と出る)
   
   ``` vim
   :echo synIDattr(synID(line("."), col("."), 1), "name")
   ```
4. syntax/vim.vim を開き、先程見つけたIDで検索
   
   ``` vim
   syn match vimVar        contained   "\<\h\w*\>"
   ```
5. `\w` じゃ `#` がマッチしねぇじゃねぇか！と怒る
6. 直す

**Comment by mattn** [comment]
↑の変数のシンタックスが変な件は #420 と一緒に出しました。

https://groups.google.com/d/msg/vim_dev/OTDcirBvxH4/6PbT4ZnqN10J

**Comment by h-east** [comment]
変数のシンタックスが変な件は2013/07/05に直っているので閉じます。 
https://github.com/vim-jp/vim/commit/9592d73105979470e22662bc21fe7433f13626c0#diff-86da060e2153c8ce5dc317a7b4b5a29d

またvim.vimをなんとかしたくなったら新規Issue立てて下さい。

**Comment by crazymaster** [comment]
> こういうのの治し方をお教えしておきますので、皆さんぜひpatch authorになって下さい。
> 1. 正常に色が付くファイルを開く
> 2. おかしくなる予定の位置にカーソルを移す
> 3. 以下を実行(今回だと vimVar と出る)
>    
>    ``` vim
>    :echo synIDattr(synID(line("."), col("."), 1), "name")
>    ```
> 4. syntax/vim.vim を開き、先程見つけたIDで検索
>    
>    ``` vim
>    syn match vimVar        contained  "\<\h\w*\>"
>    ```
> 5. `\w` じゃ `#` がマッチしねぇじゃねぇか！と怒る
> 6. 直す

これどこかにまとめておいて欲しいですね

**Comment by koron** [comment]
> ``` viml
> :echo synIDattr(synID(line("."), col("."), 1), "name")
> ```

昔、これを `<F2>` にマッピングしてたw

> これどこかにまとめておいて欲しいですね

:+1:
