### ISSUE TITLE
E706 は必要ないのではないか

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#157]
現在、自動変換が不可能な型の値を変数に再代入しようとすると E706 エラーが発生します。

``` vim
let a = 0
let a = {}  " E706
```

しかし、辞書の値に対してはこのエラーは発生しません。

``` vim
let a = {}
let a.a = 0
let a.a = {}  " OK!
```

なので、`g:` などを経由すれば最初の例でも回避可能です。

``` vim
let g:['a'] = 0
let g:['a'] = {}  " OK!
```

E706 は必要ない気がします。なくせないでしょうか。

**Comment by koron** [comment]
以下推測。

辞書型の値としての代入はvar_Tのインスタンスの差し替えだけど、変数への代入はvar_Tインスタンスの書き換えになる。
そのため書き換わったことを知らないで動作する奴がいたりして、おかしなことになるんじゃなかろうか。
もちろん知らない奴がいない状態で「var_Tインスタンスの書き換え」できれば良いのだが、
Vimのスパゲティ構造で全部さらうのが大変なのでアウトという感じ。

以上推測終わり。

**Comment by thinca** [comment]
変更箇所が分散していて修正しきるのが難しいってことでしょうかね。
:let する前に :unlet を暗黙で挟むだけで目的は達せられる気もするのですが、やはり実際にやろうとすると難しいってことだろうか…。

**Comment by ynkdir** [comment]
vim_dev, vim_use を E706 で検索するといくつか議論がでますがたんに Bram の好みだと思います。

http://thread.gmane.org/gmane.editors.vim/44665/focus=44844

VimL は動的型付け言語ではなかったんです。

**Comment by mattn** [comment]
E706はおそらくgcの為ですね。どっちかっていうと

``` vim
let foo = {}
let bar = foo
let bar.baz = {}
let bar = 0
```

この時の為です。fooにもbazが出来ているはずなので、barの値を変更した時にgc管理が面倒くさくなるのを懸念してだと思います。まぁ直したい気持ちはすごくわかります。

**Comment by k-takata** [comment]
7.4.1546
https://groups.google.com/d/topic/vim_dev/zZKf6-v3bZM/discussion
