### ISSUE TITLE
テキストオブジェクト拡張(案)

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#159]
テキストオブジェクト拡張(案)を出し合おう。
`:help text-objects`
(案)なので「実装面倒そう」とか考えない。jokeもあり。
- snake_caseなシンボル名の編集用にいかが？

<table><tr>
        <td>a_</td><td>a _。[count] 番目に現れる'_'を検索し、それに対応する'_'までを'_'を含めて選択します。</td>
    </tr>
    <tr>
        <td>i_</td><td>inner _。[count] 番目に現れる'_'を検索し、それに対応する'_'までを'_'を除いて選択します。</td>
    </tr>
</table>

<br>
- いっそのこと `:help whitespace` の文字クラスが指定できるようにするとか

ci\u とか ca\u はCamelCaseなシンボル名の編集に有効かもとか？
hogefuga1234 の f のとこで ci\a とすれば hogefuga部分だけ編集できるとか？

はい、どうそ

**Comment by koron** [comment]
textobjexprで話は終わりじゃない?

**Comment by mattn** [comment]
kanaさんがそんなの書いてましたね。

https://github.com/kana/vim-textobj-user

これつかってURLをテキストオブジェクトにする例

https://github.com/mattn/vim-textobj-url

**Comment by tyru** [comment]
textobjじゃなくてoperatorですが、kanaさんのtextobj-user使ってoperator-camelizeとか書きました。
https://github.com/tyru/operator-camelize.vim

**Comment by h-east** [comment]
うぉー、思てたんと違う(良い意味で)ｗ
編集用途というかインテリジェントに選択するって感じですね。

仮に `textobjexpr` を実装した場合に textobj-user のコード量って減ります？あんまり変わらない？

**Comment by h-east** [comment]
a_ とか i_ だったら omap で簡単に実現出来ちゃう系だからわざわざ本体弄らなくてもええやん系？

**Comment by koron** [comment]
現在行と桁数、それとオブジェクト識別文字を受け取って選択範囲 [start, end] を返すVimスクリプト関数

これをexprとして呼び出すように。あとはスクリプトにまかせる。みたいな

**Comment by h-east** [comment]
@koron うー、よく分かってないけど、それは `'textobjexpr'` というオプションを新設する場合の話をされてます？
それとも omap での <expr> のお話でしょうか？

**Comment by koron** [comment]
> `'textobjexpr'` というオプションを新設する場合の話

こっちです。omapでもいろいろ駆使すればできますが、なんかスマートじゃないので。

**Comment by koron** [comment]
ちなみにこれのメリットは大量のmapを設定しなくて良いこと。
textobj-userみたいなのの実装が楽&自然になる…ハズ
デメリットはtextobjの計算(取得)に、かかる時間がわずかながらも増えること。

`'formatexpr'` の時からそうだったんだけど
Vimの機能との整合性をエミュレートするためにmapで苦労して、
かつ不完全なものしかできないのは見るに忍びない。

**Comment by h-east** [comment]
なるほどです。だいたい理解しました。

**Comment by koron** [comment]
omap で良いのかな、と思ってけどこんな記述を発見。

> To ignore the starting cursor position and select different text, you can have
> the omap start Visual mode to select the text to be operated upon.

つまり omap で作った textobj が開始位置を変えるような場合、vと組み合わせて利用できない。
なんか対策あるのかしら?

**Comment by h-east** [comment]
Patch to utilize undefined text-objects
https://groups.google.com/forum/?hl=ja&fromgroups#!topic/vim_dev/pZxLAAXxk0M

`am{char}` と `im{char}` を追加するpatch
patchのコード部分は実質5行。

**Comment by h-east** [comment]
上のpatch、`todo`入りしているけど進展なし。
https://github.com/vim/vim/blob/master/runtime/doc/todo.txt#L842-L845

> Patch to have text objects defined by arbitrary single characters. (Daniel
> Thau, 2013 Nov 20, 2014 Jan 29, 2014 Jan 31)
> Ben Fritz: problem with 'selection' set to "exclusive".
> Updated to current Vim, not quite right yet. (Ben Fritz, 2014 Mar 27)

vim-jp的には現状ではこれ以上発展しなさそうなので`backlog`で閉じます。
興味ある人はreopenするか新規issue立てて下さい。
