### ISSUE TITLE
変数の名前付けの説明がちゃんとはまとまってない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#16]
helpの話です。

{}の話とか、#のautoloadの話とか、説明箇所が分散していて正解にたどり着くのが大変。
一箇所にまとまっていたほうが良いんじゃないか?

**Comment by thinca** [comment]
help の構成に関しては、恐らくそのばその場で書き足してきただろうと思うので、わかりづらいと思うことはありますね。こんなところに書いてあったのか！ってことは結構あった気がします(具体的には思い出せませんが)。

**Comment by tyru** [comment]
変数名と関数名においてもできれば説明がほしいですね。
`:function dict.key.func(a, b)`みたいな宣言や
`:function s:foo{"bar"}{"baz"}(a, b)`みたいにcurly-braces-namesなど
どこまで許されてるのかきちっと示してほしいです。
(おそらく関数名の部分には完全に式を許すんだろうな...と察しはつくものの)

**Comment by koron** [comment]
具体的な対処方針が示されていない。また、現在も思いつかない。
また直近で良い方法が示される期待値も低いので backlog で閉じておきます。
