### ISSUE TITLE
rename()が大文字小文字区別しないファイルシステムでファイルが消失する（勘違い）

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#160]
rename()を大文字小文字を区別しないファイルシステム(Mac)で使うと、
hogeをHogeにするときのように、大文字小文字しか違わない名前に変更しようとするとファイルが消えるようです。
おそらく、rename()におけるリネーム処理に問題があります。

追記： これは勘違いだったので、訂正。

**Comment by koron** [comment]
以下のような感じと推測
1. リネーム先のファイルがあれば削除
2. リネーム実行

ソースは読んでない。

**Comment by h-east** [comment]
こちらの環境では正常にリネームできました。
Windows 7 SP1 (64bit), GVim 7.3.382
`:call rename("aaa","AAA")`

> おそらく

予想は必須ではないので無理に書かなくて良いです。
それよりも、発生したOS、Vimバージョン、再現手順等の情報提供お願いします。

**Comment by Shougo** [comment]
ちょっと私が再現した訳ではないので正確な情報が書けないのです。
となると、Windows環境は大丈夫なのかな。ちょっと訂正しておきます。

環境はMac, "hoge"を"Hoge"にリネームしたら消えたそうです。

**Comment by Shougo** [comment]
私はMacを使っていないので、他の人のMacのVimでやってみてもらったんですが、ちゃんとリネームできていました。
この症状を訴えていたのは、itchnyさんです。
ちょっと詳しい話を聞いておきます。原因が判明するまで、このIssuesはそのままにしておいてください。

**Comment by ynkdir** [comment]
Windows は 7.3.172 で直った気がします。記憶薄いですが。
Unix 環境だと stat() で st_dev と st_ino を比較して同じファイルの別名かどうか検査してますが
Mac は stat() を使うようになってない? or st_{dev|ino} が機能してない？

**Comment by Shougo** [comment]
Vimが古いという可能性はありそうですね。Vimの詳しいバージョンは聞いていませんので。

> Windows は 7.3.172 で直った気がします。記憶薄いですが。

ああ、そういう問題があったんですね。

ちなみに、試してもらった（正常に動いた）MacのVimのバージョンは7.3.94。

**Comment by Shougo** [comment]
rename()では消えないようです。別の原因だと思われるため、こちらはcloseします。お手数おかけしてすみません。

**Comment by Shougo** [comment]
追記：どうやら、こちらのバグだったようです……。
