### ISSUE TITLE
Vim scriptはもっと巨大な整数を扱えないか？

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#161]
おそらく、実装の簡単さとパフォーマンス上の理由でしょうが、
Vim scriptの整数型が符号付き32bitなので、たまに困ることがあります。

例：2GB以上のファイルをgetfsize()で取得すると負数になる。

64bit型にする、多倍長整数を実装する、など何か良い手はないでしょうか。

**Comment by koron** [comment]
過去のVim Scriptの実装ポリシーとして、テキストエディットに関係のない項目は実装しないというのがあった。今もあるかはわからないが、そのポリシーに基づけば取り込んでもらうのは難しいかもしれない。とはいえfloatもあるしなぁ。

なお例に挙げられたgetfsize()についてはVim全体が意図せず32bitに特化している感じなので、別の問題があると推測している。

いずれにせよちゃんとやろうとするとかなりの作業量になる気がするので、パッチを書き始める前にBram氏に「仮に精度を上げた整数型パッチがあったら取り込む意志があるか?」みたいに聞いておいたほうが良いと思う。

**Comment by mattn** [comment]
`bigint.vim`を書けばおｋ

**Comment by koron** [comment]
getfsizeはダメちゃう? まぁ本質的には別問題だけどw

**Comment by mattn** [comment]
`libcallex-vim` でネイティブに値を取るとか

**Comment by Shougo** [comment]
本体以外でやろうとすると、それも作業量が多くなるのがネックなんですよね……。

> libcallex-vim でネイティブに値を取るとか

そのネイティブライブラリを使わざるをえないというのが問題なのです。
vimprocでもやたらと苦労しているし。
さらに、ネイティブにしても、Vim scriptで扱うときは変換しないといけない。

**Comment by mattn** [comment]
そこで if_python の登場ですよ(ぇ

**Comment by Shougo** [comment]
えっ……。

**Comment by h-east** [comment]
@mattn ∞

**Comment by mattn** [comment]
直す気がない人！ ... はい！

**Comment by koron** [comment]
@mattm (´・ω・`)ノ

**Comment by h-east** [comment]
私がやりましょう！　※但し、年金受給生活に入ってから

**Comment by koron** [comment]
さぁ年金をもらえないフラグが立ちましたよ。

**Comment by mattn** [comment]
ニュー速はここですか？

**Comment by Shougo** [comment]
エディ速Vimと聞いて。

**Comment by thinca** [comment]
せめて64bitになれば…。
`localtime()` も当然 32bit なので、2038年問題がもろに残ってるんですよね。

**Comment by mattn** [comment]
これなんとかしたい。

**Comment by thinca** [comment]
2038年問題は大きな訴求点として使えそうです。いずれ対応しないといけないわけなので。

**Comment by mattn** [comment]
なげた

https://groups.google.com/d/topic/vim_dev/p8Fl_vJDGy8/discussion

**Comment by thinca** [comment]
mattn++

**Comment by koron** [comment]
> I agree with you entirely

とか合いの手を入れる流れ?

**Comment by tyru** [comment]
ステマ...!

**Comment by h-east** [comment]
twitterでちょっと話が出たのでリンクしときます。
https://twitter.com/k_takata/status/418782470947885056

ダイジェスト
h_east

> そろそろ 真64bit対応(64bit WinAPI使うetc...)をやらんといかん気がしてます。linuxって64bit APIってあるのかな？あるっすよね？

k_takata

> linux版はoff_tが64bitになるのででかいファイルの扱いは問題ないはず。fseekoとかftelloとかを使っているようですし。

mattn_jp

> ファイルサイズ取得するAPIは既にでかいファイル扱えませんね

kaoriya

> VimスクリプトのNumberも64bitの扱い考えないと…

**Comment by koron** [comment]
2014年、か…

**Comment by crazymaster** [comment]
magnum.vim - Pure Vim script big integer library
https://github.com/glts/vim-magnum

**Comment by k-takata** [comment]
mattnさんのパッチをベースにいろいろいじってみました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/dffc47a02e84c998727babfec5e511cdfdb304f2/num64.patch?fileviewer=file-view-default
- 最新ソースに追従。
- VC9以前には、stdint.h がないので、その対応。当然、`int64_t`,  `uint64_t` もない。
- `FEAT_NUM64` を定義。
- `:ver` で、`+num64` を表示。
- `has('num64')`
- 0で割ったときの値を調整。 `:help expr-/`
- `float2nr()` の値を調整。

`getfsize()` で、2GiB以上のファイルサイズで正しい値が返ることも確認できました。（4GiB以上は未確認。）

**Comment by h-east** [comment]
@k-takata すげー！:+1: 私がどんだけpatch書いてもそれ以上に k-takataさんがpatch書いてvim_devに投げるから、取り込まれpatch数の差が縮まるどころか逆に開いていく！！あんた何者なんだ！？！？

**Comment by koron** [comment]
:+1: 良さ気

**Comment by mattn** [comment]
:+1: いいね

**Comment by tyru** [comment]
:+1: かっこいい…

**Comment by k-takata** [comment]
テストを動かしたら、test108で死亡。`vim_snprintf()`内の修正は不要そう。

**Comment by k-takata** [comment]
ところで、本件、 #57 とは別扱いということでいいですよね？

**Comment by k-takata** [comment]
放った。
https://groups.google.com/d/msg/vim_dev/p8Fl_vJDGy8/T6aJbgy6BwAJ
どうにでもなーれ。

**Comment by k-takata** [comment]
todo入り

> Patch to support 64 bit ints for Number. (Ken Takata, 2016 Jan 21)

mattnさんの名前があー。
テストの追加やドキュメントの更新など、まだやることがあるので、openのままにしておきます。

**Comment by k-takata** [comment]
あとは、時間周りの64bit対応とか。

**Comment by mattn** [comment]
担当するのは僕じゃなくて k-takata さんなので別にいいですよ(おい

**Comment by k-takata** [comment]
なんですとー

**Comment by k-takata** [comment]
> ところで、本件、 #57 とは別扱いということでいいですよね？

無関係というわけでもなかったので、パッチを更新して、2つに分割。

https://bitbucket.org/k_takata/vim-ktakata-mq/src/ec8fa710e76975724c30d0f84c02e1460e5bb705/num64.patch?at=default&fileviewer=file-view-default
https://bitbucket.org/k_takata/vim-ktakata-mq/src/ec8fa710e76975724c30d0f84c02e1460e5bb705/incdec64.patch?at=default&fileviewer=file-view-default

incdec64.patch が、 #57 の対応です。

**Comment by k-takata** [comment]
7.4.1154対応
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c3b23c0c2274f70b228f1462aec42bd730286266/num64.patch?fileviewer=file-view-default
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c3b23c0c2274f70b228f1462aec42bd730286266/incdec64.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
vim_snprintf を %lld に対応させないといけないなあ。

**Comment by k-takata** [comment]
> vim_snprintf を %lld に対応させないといけないなあ。

Done!
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d1b6fe7c1f38ffc8d7fda03fda31d0dec6a5cbd1/num64.patch?fileviewer=file-view-default
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d1b6fe7c1f38ffc8d7fda03fda31d0dec6a5cbd1/incdec64.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
パッチ更新。
https://groups.google.com/d/msg/vim_dev/p8Fl_vJDGy8/WgoprhIdCwAJ
分割していたパッチを再度統合しました。

**Comment by mattn** [comment]
:+1:

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/p8Fl_vJDGy8/yxOTBCdaHAAJ

> Thanks.  Hopefully I get to including it one of these days.

近日中に入るかもしれない！

**Comment by mattn** [comment]
!!!!

**Comment by k-takata** [comment]
テストをいくつか作りました。作成中にいくつか修正漏れが見つかり、修正済みです。
https://groups.google.com/d/msg/vim_dev/p8Fl_vJDGy8/UnkFb5n5JQAJ
これで range(), min(), max(), sort() で64bit整数を扱えるようになりました。

**Comment by k-takata** [comment]
7.4.1976
https://groups.google.com/d/topic/vim_dev/fSle2Fg-Lc8/discussion
パッチにmattnさんの名前が入ってないなあ。

**Comment by k-takata** [comment]
指摘しておきました。
https://groups.google.com/d/msg/vim_dev/fSle2Fg-Lc8/lbkOXxn0BwAJ
閉じます。

**Comment by machakann** [comment]
`$` コマンドを使用した時の curswant の値と行指向選択した時の `'>` マークの col の値が32bitのintの最大値のままのようです。

**Comment by k-takata** [comment]
確認手順とOSを教えていただけますか？
実装の話でいうと、桁番号を扱う `colnr_T` 型は int なので、Unix系でもWindowsでも32bitです。私としては、今のところ、これを変えるつもりはありません。
一方、行数等の管理に使用している `linenr_T` 型は https://github.com/vim-jp/issues/issues/508#issuecomment-230033592 にも書いたとおり long のままとなっており、64bit Unix系では64bitですが、Windowsでは32bitのままとなっています。

**Comment by machakann** [comment]
ありがとうございます。確認手順は
- ノーマルモードで `$` を押した後、`:echo getcurpos()` を実行
- ノーマルモードで `V<esc>` を押して `:echo getpos("'>")` を実行

Windows 10 で確認しましたが、桁番号が32bitのままであれば現在の挙動が正しいようです。すいませんパッチのことを誤解していました。
