### ISSUE TITLE
スタックトレース時に、前の関数呼び出しの行番号が欲しい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#165]
Vimでは関数がエラーを出した時にスタックトレースを出しますが、そのとき行番号まで表示されるのは最後にエラーを出した関数だけです。その前の呼び出しは関数名しか出て来ません。それではデバッグ時に不便なことがあります。
オプションでもいいから、トレース時に関数呼び出しの行番号をすべて出してくれると、無名関数のデバッグなどに非常に役立つのではないでしょうか。

**Comment by koron** [comment]
直感的には、行情報はあるんだけど表示していないだけ、という感じがする。仮に情報がなかったらちょっとめんどそう。

**Comment by k-takata** [comment]
7.4.879
https://github.com/vim/vim/commit/1d6328ca00fc6cfe37b1f5e038ec23f443258886
