### ISSUE TITLE
glob()/globpath()にtimeout用の引数がほしい

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#167]
Twitter上でのやりとりが発端です。

https://twitter.com/#!/tyru/status/169682392850771968

> これNFSとかでも起きそう タイムアウト実装できたらいいけどめんどくさそう… RT @n_kane: その前に、USBシリアル変換ケーブル引っこ抜いて/dev/tty.usbserialが非常に微妙な状態に陥ってるときに"/dev" とまで書いた後に発症したっぽい。

https://twitter.com/#!/ShougoMatsu/status/169683745970978816

> @tyru glob(), globpath()にタイムアウト欲しいとは思っています。

@n_kaneさんが「発症した」って言ってるのはこれです。

https://twitter.com/#!/n_kane/status/169680928430497792

> 普通にvimで動くパス名補完で固まったっぽいですねぇ。RT @syuu1228: VimShellで ls /devの補完とか？RT @n_kane: 補完効かせたvimも/devの下をあさろうとしたためか固まりおった

**Comment by tyru** [comment]
timeoutしたらtimeoutしたと分かるように返り値ではなく例外を投げるのがよさそうです。
空の返り値とかだとtimeoutしたか結果が空なのか分からないので。

**Comment by Shougo** [comment]
ただ、そういうときに例外を投げるVimの組み込み関数はあまりないですね。
Javaだとそう実装しそうですけど。try catchで囲むのが面倒だという別の問題も……。

**Comment by Shougo** [comment]
既存のglob()であっても、パターンがおかしいのか、中身が空なのかは戻り値では判断つかないですね。

**Comment by tyru** [comment]
パターンがおかしい時は、パターンが悪いので、パターンどおりに動いてるVimの挙動は正しいと思います。
パターンが不正であれば例外を投げるべきだと思いますが、正規表現ならともかく、ワイルドカードの場合不正なパターンってあまり思いつかない・・・
もちろん他にも、パターンの部分にString以外の引数、たとえばListなどが与えられた場合などは例外を投げるべきケースだと思います。

**Comment by tyru** [comment]
> try catchで囲むのが面倒だという別の問題も……。

僕もそう思いました。
が、それ以外にエラーを伝える手段がないというのも事実・・・

**Comment by tyru** [comment]
エラーって言ってますが、timeoutはエラーなのか微妙ですね。
以後単に「timeout」といわせてもらいます。

たった今思いついたのですが、timeoutを伝える方法としてtimeout用のハンドラを設定する、ってのがありますね。
timeoutした場合はそのハンドラ(あるいはVimscriptの式)を評価してその値を返す、みたいな。
その場合引数が増えちゃいますけど。(`v:`変数でもいいけどキモい・・・)

**Comment by ynkdir** [comment]
タイムアウトが便利かどうかはよくわかりませんが
システムコールで刺さってる系だとどっちにしても対応難しそうだなーと思いました。

**Comment by tyru** [comment]
search()だと対象がバッファだけど、glob()はファイルシステムを走査しますもんね・・・
自分はLinuxのシステムコールもWin
APIも詳しくないですが、Linuxのシステムコールだったら適当にreaddir()を毎回呼び出す前と後に時間をチェックすればよさげ・・・？とか思ってみたり・・・

**Comment by mattn** [comment]
今回の場合だと、/dev/xxx でデバイスファイルがロックしてるはずなので、タイムアウトとかは正直vimの仕事じゃない気がする。

**Comment by ynkdir** [comment]
> Linuxのシステムコールだったら適当にreaddir()を毎回呼び出す前と後に時間をチェックすればよさげ・・・？

readdir() の中で固まってるんじゃないかと思います。
実際見てないのでなんとも言えませんが。

**Comment by koron** [comment]
システムコール自身がブロックしてたらお手上げ、っていうことでOK?

OSによっては方法があるかな? タイムアウト有りのシステムコールがあるとか。そっちにスイッチするのは有りだと思う。

WindowsならAsync系とかOVERLAPPEDだっけ、あのあたりになるのかしらねぇ。

**Comment by ynkdir** [comment]
ただまあケーブル抜き差ししたくらいで固まるもんですかね。
/dev/tty.usbserial ってマックなのかな。

**Comment by Shougo** [comment]
いや、MacじゃなくてBSD系だったと思います。ただ、ドライバがまずいという話でした。
そこで固まる件はVimじゃどうにもならないでしょうね。

**Comment by h-east** [comment]
なんだかなぁ。

**Comment by Shougo** [comment]
まぁ、その問題は別として、glob()にタイムアウトが欲しいと思うことはありました。
glob()が大量のファイルをだそうとした場合、Vimが固まるのを防ぐために。

**Comment by tyru** [comment]
readdir() が入ったので閉じます。
