### ISSUE TITLE
string() で E724 (深すぎるネスト) が発生する

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#169]
バグかどうか微妙ですが、`:echo` だとよしなにしてくれるのに `string()` だと E724 が出ます。

``` vim
let a = {}
let a.a = a
echo a
=> {'a': {...}}
echo string(a)
=> E724: 表示するには変数の入れ子が深過ぎます
{'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a':
{'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a':
{'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': {'a': }}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}

```

バグであって欲しいけど、仕様だとしてもドキュメントに明記が欲しいところ。

**Comment by ynkdir** [comment]
:help string()

> the result can be parsed back with eval().

と言っているのでそんな感じでよさそうに思います。

**Comment by ynkdir** [comment]
エラーメッセージは少し変ですが。

**Comment by mattn** [comment]
これはしょうがないというか、僕はこうあって正解だとおもう。 :echo とちがって string() はロジックとして使うので ... で省略されるとこまる物だと思います。
いわば JSON.stringify() なので、失敗したらエラー出てほしいし、勝手に ... で略さないでほしい。

**Comment by thinca** [comment]
なるほど、確かにそうですね、納得しました。
ありがとうございました。

**Comment by koron** [comment]
ネストの深いオブジェクトとしてではなく、循環参照をどう扱うかという問題に読み替えるとちょっと違ってくるかも。

Perl の Data::Dumper だと循環参照はちゃんと検出されてよしなに計らってくれる。あれと同じ仕組はいらないのだろうか?

**Comment by thinca** [comment]
改めて考えると、変数を復元するのが目的ではなく単に変数の概要を表示したい場合もあるので、オプションでもいいのでエラーが出ないで欲しい場合がありますね。
それに復元の観点から言うと Funcref が混じっててもエラーは出ないけどアウトですし。

**Comment by mattn** [comment]
表示したい目的ならば `:echo` で `:redir` という(ry

**Comment by ynkdir** [comment]
オプションはありだと思います

**Comment by thinca** [comment]
議論の余地ありってことで reopen しておきますね。

**Comment by mattn** [comment]
> 変数を復元するのが目的ではなく単に変数の概要を表示したい場合もあるので

それこそ特例になりえるのでredirで良い気がします。頑張りたい人は`maxfuncdepth`弄って下さいという事で。

**Comment by k-takata** [comment]
7.4.1577以降、partialでもE724が発生するようになってしまいましたが、`:help E693`を見ると、

```
To compare partials to see if they bind the same argument and Dictionary
values use string(): >
    echo string(Partial1) == string(Partial2)
```

などと書かれているので、非常によろしくないですね。

**Comment by k-takata** [comment]
> the result can be parsed back with eval().

循環参照だと、どうせ`eval()`で復元できないしなあ。そういえば`json_encode()`はどうなっているかというと、

``` vim
let a = {}
let a.a = a
echo json_encode(a)
=> {"a":{}}
```

**Comment by thinca** [comment]
`channel` や `job` も復元不能ですしねぇ。

**Comment by k-takata** [comment]
partialでE724が発生する例:

``` vim
let obj = {}
function! obj.func() abort
endfunction
let obj.func = obj.func
echo string(obj.func)
```

**Comment by k-takata** [comment]
`string()`の第2引数で、循環参照を省略するか指定できるようにするとか？

**Comment by koron** [comment]
全然関係ないけど、Perlのdumpって循環参照を良い感じでやってくれましたよね。一時変数に入れてそれを参照する感じに。

**Comment by k-takata** [comment]
やる気のないパッチができました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/5c6479f537bd5f2e9d39fc50d12e2e38c4eeabf7/string-avoid-E724.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
E724を発生させないようにしたパッチを投げて、追加パラメータが必要かどうか聞いてみることにしました。
https://github.com/vim/vim/issues/708#issuecomment-200582108

**Comment by mattn** [comment]
Bram のことなので string(x, 1) がお好みな気がする。

ちなみに

``` vim
let a = {}
let a.a = a
let b = deepcopy(a)
echo b.a.a.a.a.a.a
```

これでエラー出ないけど、ほんとに deep なの？w

**Comment by h-east** [comment]
@k-takata さんのpatchで`incsearch.vim`が正常に動作するようになってますね。:+1:

@mattn 
`echo b.a.a.a.a.a.a`は`echo string(b.a.a.a.a.a.a)`じゃなくて？

**Comment by k-takata** [comment]
> これでエラー出ないけど、ほんとに deep なの？w

仕様通りのように見えます。
`deepcopy(a, 1)`とすると、循環参照していても頑張ってコピーしようとするようですね。

**Comment by mattn** [comment]
いつのまに deepcopy に第2引数が！w なら string も第2引数でいいですね。

**Comment by thinca** [comment]
7.4.~~1664~~1644 で、`string()` に再帰構造のデータを渡してもエラーにならないようになりました。みなさんありがとうございました！
https://groups.google.com/d/topic/vim_dev/1JK9Ztc40Lk/discussion

**Comment by k-takata** [comment]
s/7.4.1664/7.4.1646/ ですね。
しかし、第2引数は無しであっさり変更されてしまいました。いいのかｗ

**Comment by k-takata** [comment]
違った、7.4.1644だ。

**Comment by thinca** [comment]
おっと、失礼しました。 >パッチ番号

**Comment by koron** [comment]
# 関係ないけど、オレはなんで4年越しで同じコメントしてんだよw
