### ISSUE TITLE
:callに複雑な式を渡すと「E15: Invalid expression」を出すことがある

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#17]
https://github.com/tyru/caw.vim/pull/12#issuecomment-2063564
上は一例です(他にも`.`で長くメソッドチェインしまくったりすると起こったことが...)。
しかし具体的な再現条件はつかめてません。
だいたい`let _ = expression`みたいにすると回避できます。

**Comment by mattn** [comment]
再現する最小ケースを下さい。

**Comment by tyru** [comment]
すみません、ちょっと再現するコードを作るのに手間取ってます。
eskkでも出た記憶があるので探してみたらこのコミットがヒットしました。
https://github.com/tyru/eskk.vim/commit/3c9fc300f7cd304408bd57191b88a874396d655f
Dictionaryに`[]`でアクセスして関数を呼び出すと起こることが多いんでしょうか...?
単純にそこだけ抜き出しても再現しないので何か別条件が絡んでそうです。

**Comment by koron** [comment]
ああ、再現自体ができないのか。Vimスクリプトの実行のしかたを考えると、
引数として何段も重なってる=トップの関数呼び出し自体が長くなるとアウトかも
という推測はできます。

**Comment by mattn** [comment]
単純に

```
call s:popup_func_table[char](a:stash)
```

charがkeysにないとかそういう話ではなく？

**Comment by tyru** [comment]
その場合`E716: Key not present in Dictionary`が出るはずなので違うと思います。
確かめようにもgit checkoutしてもどういう入力をしてE15が出たのか上のeskkのコミットには書かれてないので検証しようがないです。すみませんorz

**Comment by koron** [comment]
ざっとソースコード見たけどE15出すとこｵｵｽｷﾞﾜﾛﾀ
ただ強制的にabortしたとかthrowしたとかでも出せそうな雰囲気。
実は例外が起きてるけどVimがうまく補足できていないとか…

**Comment by mattn** [comment]
タイミングは100%ですか？

**Comment by mattn** [comment]
おそらくこういう形かと思います。

```
let bar = {}
function! bar.baz(aa) dict
 return "a" . a:aa
endfunction
let foo = {}
let foo.bar = bar " ← ここ
let _ = foo.bar["baz"]("hoge")
```

例えばこの`foo.bar`がdictでなかったとしましょう。すると...

```
行    6:
E15: 無効な式です: foo.bar["baz"]("hoge")
```

と出ます。実行したケースによって

```
let foo.bar = bar
```

が

```
let foo.bar = 0
```

みたくdictで無くなってたり、もしくはこの行がパスしてなかったりしませんか？

**Comment by tyru** [comment]
おそらくですがそれはないと思います。
https://github.com/tyru/caw.vim/blob/1d8f7dcb841766475932376c3b527db75ccbd2ee/autoload/caw.vim#L1150
この通り代入してる箇所は1箇所だけで、スクリプトのロード時のみです。
繰り返しロードされることはないと思うので。

**Comment by tyru** [comment]
再現しました！
https://gist.github.com/1244803
forの中ってところがミソかもしれません。

```
let method = 'do'
call obj[method]()
```

とかやってもエラー出なかったので。

**Comment by mattn** [comment]
なるほど

``` vim

function! s:do(...)
    echomsg 's:do()'
endfunction

function! s:run()
    let obj = {'do': function('s:do')}
    for method in ['do']
        call call(obj[method], [])
    endfor
endfunction
call s:run()
```

だと出ないのか

**Comment by mattn** [comment]
あとこれはokなのね

``` vim

function! s:do(...)
    echomsg 's:do()'
endfunction

function! s:run()
    let obj = {'do': function('s:do')}
    for method in ['do']
        let dummy = obj[method]()
    endfor
endfunction
call s:run()
```

**Comment by mattn** [comment]
どうやら構文解析っぽい

**Comment by koron** [comment]
ダメパターンをそのまま転載:

``` vim
function! s:do(...)
    echomsg 's:do()'
endfunction
function! s:run()
    let obj = {'do': function('s:do')}
    for method in ['do']
        call obj[method]()
    endfor
endfunction
call s:run()
```

あとその出力:

```
s:do()
Error detected while processing function <SNR>182_run:
line    3:
E15: Invalid expression: obj[method]()
```

ところで出力見るとs:do()は一回実行されてますよね。
で、なぜか2回目が回ってる。ということは構文解析に問題があるとすれば、for ～ in ～の方かな?
組み合わせ次第でendforまで上手く飛ばせない、みたいな。

**Comment by mattn** [comment]
スキップ処理だった。

``` diff
diff -r 5e84f6567623 src/eval.c
--- a/src/eval.c    Wed Sep 21 20:09:42 2011 +0200
+++ b/src/eval.c    Tue Sep 27 20:39:37 2011 +0900
@@ -4013,7 +4013,7 @@

     p = skipwhite(arg);
     ret = eval1(&p, rettv, evaluate);
-    if (ret == FAIL || !ends_excmd(*p))
+    if (evaluate && (ret == FAIL || !ends_excmd(*p)))
     {
    if (ret != FAIL)
        clear_tv(rettv);
```

**Comment by mattn** [comment]
これもちょっと寝かせる(何個かスクリプト動作を試す)ので、安定したら提出。

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/XuJcOwNziG0/discussion

**Comment by mattn** [comment]
違うパッチになったけど、入ったのでclose
https://groups.google.com/d/topic/vim_dev/RWJWfL-UxTM/discussion
