### ISSUE TITLE
Vim のコマンドライン引数が取りたい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#170]
Vim のコマンドライン引数が取れると嬉しいです。
singleton.vim を作った際に感じました。

https://github.com/thinca/vim-singleton/blob/c34a4a24c2933a382ac340b7944c36b355b80c30/doc/singleton.txt#L157

具体的な方法や他への応用例などは考えていないので提案としては弱いかもしれないですが、とりあえずするだけしてみます。

**Comment by koron** [comment]
本当に使い道が思いつかないんだけど、
どういう風に使うの?

実装はかんたんそうだけど。

**Comment by thinca** [comment]
`singleton.vim` は、ファイルを開こうと新しく Vim を起動した際にすでに他の Vim が起動していたらそちらに送って自分はすぐに終了するってプラグインです。`--remote` 系の機能に比べて若干の利点があるのだけどそこは省略。
で、`vim file +10` みたいに起動されたときに、ファイルを送った後に 10 行目に移動したいところなんですが、今の Vim だとこれができません。

**Comment by mattn** [comment]
こうですね？わかります。

```
:echo libcall("kernel32.dll", "GetCommandLineA", "")
```

**Comment by thinca** [comment]
環境毎にこれを書いてさらにVimが内部でやっているはずのパースを自前で…ゴクリ。

**Comment by mattn** [comment]
```

function! s:shell_args()
  let str = libcall("kernel32", "GetCommandLineA", "")
  let words = split(str, '\%(\([^ \t\''"]\+\)\|''\([^\'']*\)''\|"\(\%([^\"\\]\|\\.\)*\)"\)\zs\s*\ze')
  let words = map(words, 'substitute(v:val, ''\\\([\\ ]\)'', ''\1'', "g")')
  let words = map(words, 'matchstr(v:val, ''^\%\("\zs\(.*\)\ze"\|''''\zs\(.*\)\ze''''\|.*\)$'')')
  return words
endfunction
```

さらにこうですね？わかります。

**Comment by thinca** [comment]
最初にも書きましたが、他に応用例が思い付かないので押しが弱いという意味でどうしても欲しいって感じではないです。
ただ、提案だけでもすれば他の人が思いもよらない応用例を考えてくれるかも? と思ったのでPOSTしました。

**Comment by thinca** [comment]
解読は諦めましたw

**Comment by mattn** [comment]
Linux版が欲しいですか？こうですね！

```

function! s:shell_args()
  if has('win32')
    let str = libcall("kernel32", "GetCommandLineA", "")
  else
    let str = join(map(filter(split(matchstr(system("xxd -g 0 /proc/self/cmdline"), ':\s*\zs\S*'), '..\zs'), 'v:val!="00"'), 'printf("%c", "0x".v:val)'), '')
  endif
  let words = split(str, '\%(\([^ \t\''"]\+\)\|''\([^\'']*\)''\|"\(\%([^\"\\]\|\\.\)*\)"\)\zs\s*\ze')
  let words = map(words, 'substitute(v:val, ''\\\([\\ ]\)'', ''\1'', "g")')
  let words = map(words, 'matchstr(v:val, ''^\%\("\zs\(.*\)\ze"\|''''\zs\(.*\)\ze''''\|.*\)$'')')
  return words
endfunction

echo s:shell_args()
```

**Comment by thinca** [comment]
なんかもうこれを vital に突っ込めばいい気がしてきた。

**Comment by koron** [comment]
手の込んだいぢめかw

**Comment by mattn** [comment]
あ！xxd で /proc/self/cmdline みたら xxd のコマンドラインになってしまう... バグだーーーーーー！

**Comment by thinca** [comment]
`readfile('/proc/self/cmdline')` こうですね。

**Comment by mattn** [comment]
バイナリなのです...

**Comment by thinca** [comment]
私の環境ではテキストで返って来ました…。

```
$ vim -u NONE -i NONE -N
:echo readfile('/proc/self/cmdline')
['vim
-u
NONE
-i
NONE
-N
']
```

つまり環境によって違う。

**Comment by mattn** [comment]
0x00 入ってると思います。

**Comment by thinca** [comment]
Vim の仕様で 0x00 は改行になりました！

**Comment by thinca** [comment]
`:help readfile()`

> All NUL characters are replaced with a NL character.

**Comment by mattn** [comment]
じゃあsplitでいいのか。解決！

**Comment by h-east** [comment]
Vim本体は弄らずに解決できたようなのでcloseしますね。

**Comment by mattn** [comment]
w
