### ISSUE TITLE
幾らかのヨーロッパロケールで小数点が機能しない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#172]
元ネタはこちら

https://github.com/Shougo/neocomplcache/issues/142

とあるヨーロッパロケールでは小数点表記に `.` でなく `,` を使う為、 `strtod` が `.` を終端と見てしまい、vimscriptのパースがおかしくなるという問題。strtodがロケールに依存しているのが問題。以下既にパッチを書いて投稿。
vim_strtod を書いたので、できれば皆さんテストして欲しい。

https://groups.google.com/d/topic/vim_dev/XunOXkf8Aq8/discussion

https://gist.github.com/1890186

**Comment by ynkdir** [comment]
最初は自前で変換してたのを LC_NUMERIC=C を設定するという前提で strtod() を使うようにしたという経緯みたいです。

Patch to try out: floating point
http://thread.gmane.org/gmane.editors.vim.devel/19268/

Updated floating point patch
http://thread.gmane.org/gmane.editors.vim.devel/19832/

```
Another change is using strtod() instead of our own code for converting
text to a floating point number.  This works much better for overflows.
It does require the LC_NUMERIC value of the locale to be set to "C".
Otherwise a comma might be used in some situations, which would be very
confusing.  Please check if this works correctly:
```

**Comment by ynkdir** [comment]
ちょっと前に PHP の浮動小数点数の無限ループのバグが話題になってたのが記憶にあったので試してみました。
両方ひっかかるぽいです。

```
    /* PHP (slashdot.jp): http://opensource.slashdot.jp/story/11/01/08/0527259/PHP%E3%81%AE%E6%B5%AE%E5%8B%95%E5%B0%8F%E6%95%B0%E7%82%B9%E5%87%A6%E7%90%86%E3%81%AB%E7%84%A1%E9%99%90%E3%83%AB%E3%83%BC%E3%83%97%E3%81%AE%E3%83%90%E3%82%B0 */
    test("2.2250738585072011e-308");
    /* Gauche: http://blog.practical-scheme.net/gauche/20110203-bitten-by-floating-point-numbers-again */
    test("2.2250738585072012e-308");
```

**Comment by mattn** [comment]
テスト足します。あざす。

**Comment by mattn** [comment]
前者は直った。（単純バグ）
後者はINF？

**Comment by mattn** [comment]
両方直しました。

**Comment by h-east** [comment]
@ynkdir +++
@mattn ++

**Comment by mattn** [comment]
ミスってた。

**Comment by ynkdir** [comment]
ありがとうございます。
計算結果を確認しようにも正解が分からなくてくやしい。

うちのubuntuには pt_BR.UTF-8 が入ってないので `setlocale(LC_ALL, "pt_BR.UTF-8")` でエラーがでます。
setlocale() をコメントアウトするとその先の strtod() との比較でエラーがでます。

```
CASE: 2.2250738585072011e-308
ERR: 2.2250738585072011e-308, 計算結果は範囲外の値です
  E1 0.000000, 0, 
  E2 0.000000, 0, 
  E3 0.000000, 2.22507e-308, 
CASE: 2.2250738585072012e-308
ERR: 2.2250738585072012e-308, 計算結果は範囲外の値です
  E1 0.000000, 0, 
  E2 0.000000, 0, 
  E3 0.000000, 2.22507e-308, 
```

**Comment by mattn** [comment]
直したつもりですが... 最後のがエラーになる...

**Comment by mattn** [comment]
locale消しました。
ロケール非依存なのでべつにいらないですね。

**Comment by mattn** [comment]
これ一回蹴られてるので閉じますね。

**Comment by koron** [comment]
具体的な実害があるなら backlog にして、再起を図りたいですが…現在どういう状況なんでしょうね?
