### ISSUE TITLE
*.xul を filetype.vimに含めて欲しい

### ISSUE THREAD

**Issue by teramako** [vim-jp/issues#174]
```
autocmd BufNewFile,BufRead *.xul setf xml
```

`BufRead` 時は大抵行頭に `<?xml verions="1.0"?>` があるため xmlと判定されますが、`BufNewFile` 時には xmlと判定されません。

**Comment by tyru** [comment]
上の1行が$VIMRUNTIME/filetype.vimにないですが、それは追加してほしい1行ですか？
それでBufNewFileの時はxmlと判定されないのでどうにかしたいと。

**Comment by tyru** [comment]
ああすごい頓珍漢なことを言ってた...
BufNewFile時にxmlを判定したいから上の1行を追加してほしい、ってことですよね。(コードあまり見てなかった...)

今メール送りました。
https://groups.google.com/group/vim_dev/browse_thread/thread/43163eaa220f1772?hl=ja

**Comment by h-east** [comment]
↓これで追加されていますね。
チェンジセット:   3410:94601b379f38
ユーザ:           Bram Moolenaar bram@vim.org
日付:             Sun Mar 11 15:57:40 2012 +0100
要約:             Updated runtime files.  Add Dutch translations.

**Comment by tyru** [comment]
@h-east ありがとうございます！
