### ISSUE TITLE
＠ITの「いまさら聞けないVim」の記事の質を向上させたい

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#175]
http://www.atmarkit.co.jp/flinux/rensai/vim11/11a.html

ネタをネタと分かって楽しんでいる方はいいんですが、あまりにも反面教師過ぎるので出来ることなら改善したいです。
とりあえず、著者はネット上の意見をフィードバックしたほうが良い気がします。

**Comment by koron** [comment]
あれを超える連載記事をvim-jpでホストすれば良いのでは?

**Comment by mattn** [comment]
記者がいない

**Comment by mattn** [comment]
vim本体のbugカテゴリに入ってくるのはイヤンな気がしたので外します。

**Comment by h-east** [comment]
連載が2012/2/29を最後にストップしているので一端クローズします。
復活して相変わらずだったらその時に考えましょう。
