### ISSUE TITLE
DLLを複数環境で共有していると問題が発生するかもしれないケースについて考える

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#177]
現在、Vimから自分が64bit/32bitを判別できるのは、Windows環境のみです。
他の環境、たとえばCygwinではこれができません。
32bitで64bitのdllが読めないし、64bitでは32bitのdllは読めないので、そういう事故を防止するためにも、簡単に区別ができると良いのではないでしょうか。

追記：　タイトルがわかりにくいので改名しました。

Dropboxやgithubなどを利用してDLLを共有している環境では、DLL名が同じだと問題になります。
Windows環境ではhas('win32') has('win64')で区別して、適切なDLLを読み込むことができますが、他の環境では32bit/64bitの区別ができません。

**Comment by h-east** [comment]
linuxはfileコマンドで判別できますね。

``` sh
$ file `which vim`
/usr/local/bin/vim: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped
```

Cygwinでも同じはず。

**Comment by mattn** [comment]
事故を防止する方法が間違ってるんじゃないですか？
ファイル名にアーキテクチャを含んでおけばいいだけでは。

**Comment by Shougo** [comment]
はい。それをやろうと思っているんですが、32bit/64bitの区別ができるならしたいと思ったのです。
Windows環境ならhas('win32') has('win64')があるので簡単なのですが、それ以外の環境ではどうしようかと思いまして。

**Comment by Shougo** [comment]
> linuxはfileコマンドで判別できますね。

了解しました。fileコマンドでparseすればいいのかな？
ただ、Vimが持っている自分の実行ファイル名はフルパスでないので、$PATHから自分のパスを検索するしかありません。
それで本当に正しい結果が得られるのでしょうか。

**Comment by koron** [comment]
なんか変ね。hasで検査してるのはアーキテクチャの違いであって、32か64かではないはず。
「アーキテクチャの違いによってリンクするファイル名を変える」ならば有ってる気がするが、
考えてみればWindows以外で困るケースが思い浮かばない。

Windows以外で困る具体的なケースを挙げるべし。

**Comment by ynkdir** [comment]
`printf('%p', '')` でどうかと思ったけど確実ではなかった

**Comment by ynkdir** [comment]
http://msdn.microsoft.com/en-us/library/windows/desktop/aa384274.aspx
PROCESSOR_ARCHITECTURE は cygwin ではどうなんでしょう。

**Comment by Shougo** [comment]
> Windows以外で困る具体的なケースを挙げるべし。

まぁ、あまりないのですが、DLLを複数環境で共有していると問題があるかもしれないと思っただけです。

> PROCESSOR_ARCHITECTURE は cygwin ではどうなんでしょう。

環境変数で区別できれば、かなり楽ですね。

**Comment by h-east** [comment]
> まぁ、あまりないのですが、DLLを複数環境で共有していると問題があるかもしれないと思っただけです。

なんじゃそりゃ。だったら、なんでこの「Windows以外の環境でも64bit/32bitの区別をしたい」というIssueを立てた？

「DLLを複数環境で共有していると問題が発生するかもしれないケースについて考える」とかいうIssueを立てて、ちゃんと状況を説明して議論すればよかったんじゃないの？

**Comment by Shougo** [comment]
うーむ、やはりよく考えるとこれをやっても無意味ですね。
Cygwin環境で使えるかもしれないくらいで。このIssues自体はcloseします。

**Comment by Shougo** [comment]
> なんじゃそりゃ。だったら、なんでこの「Windows以外の環境でも64bit/32bitの区別をしたい」というIssueを立てた？

Windows以外でも64bit/32bitの区別が出来れば、状況に応じて適切なDLLを読み込めると思ったためです。
ただ、Windows以外の環境でどれだけ問題になるかはよくわからないですね。
あまり聞いたことも無いです。だからcloseしたほうがいいのかな、と思ってcloseしました。
混乱させてしまったようですみません。

**Comment by mattn** [comment]
うまく表現出来ない場合は、発生している現象と課題をそのまま書くのがいいと思いますよ。
ただなんとなくvimprocのissueな気がするので、そちらで一度issueを纏めてもしvim側に対応が必要であれば改めてこちらに持ってくるのがいいかと思います。

**Comment by Shougo** [comment]
この問題自体は、vimproc側で解決する予定です。
ただ、Windows以外では32/64bitの判別ができないため、そこを解決するかどうかが問題になっていますね。

**Comment by mattn** [comment]
仮にvimprocのproc.dllをバイナリ配布して問題となったのならば、それはユーザの責任かと思いますが。

「32bitのWindowsに64bitのkaoriya vim入れたらうごかねーよ！ゴルァ」

とか言われてもどうとも出来ません。逆に自分でコンパイル出来る人にこういう問題は発生しない気もしますし。

※いまだこのissueの意味がよくわかってません。

**Comment by koron** [comment]
64bit OSに32bit入れて、動かねーみたいな。あと32bitと64bitでロードすべきDLLの名称が異なるとか?

Windowsでは結構簡単にありそうだけど(Eclipseとかでどハマってるのなんどかみた)…Linuxでどうしたらそうなるのかは良くわからない。

**Comment by Shougo** [comment]
> 仮にvimprocのproc.dllをバイナリ配布して問題となったのならば、それはユーザの責任かと思いますが。

はい。ユーザーの責任というのはたしかにそうなんですが、ハマる人が多いのでこちらでも何とかしたほうがいいのかと思ったのです。

> Windowsでは結構簡単にありそうだけど(Eclipseとかでどハマってるのなんどかみた)…Linuxでどうしたらそうなるのかは良くわからない。

確かに、Windows以外でハマるかと言われると……。ちなみに、自力でコンパイルする人であっても、生成されたバイナリが32bitだったりしてハマる人がいました。
