### ISSUE TITLE
There is not the way to set executed external command encoding.

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#179]
This is from this issue: https://github.com/Shougo/vimproc/issues/14

> Yes, I understand the problem. But it looks like Windows encoding mess is so broken that it cannot be fixed with a simple use of encoding and termencoding.
> 
> For instance, for Russian locale on Windows, common encodings are CP1251 for GUI and CP866 for console applications.
> Consequently, vimproc#readdir works fine only if termencoding is cp1251 (encoding can be of any compatible value).
> Speaking of console applications, there are two cases:
> 1) a console application using CP866. Vimproc works correctly only if enc=tenc=cp866 or enc=cp866, tenc=cp1251. It does not work for enc=utf-8 or other cases.
> 2) a console application using CP1251. The output is shown correctly only if enc=tenc=cp1251. Other combinations of utf-8, cp1251, cp866 show garbage.

What should you do for us?

**Comment by Shougo** [comment]
I think termencoding option have to allow multiple values(like fileencodings).

**Comment by koron** [comment]
これはvimprocがencodingを意識してないことが問題なのでは?

**Comment by Shougo** [comment]
私は、コマンドにより二種類のエンコーディングがあるせいだと思いました。
例えば、ghciやgoshはutf8のエンコーディングを使用します。が、cp932のエンコーディングを使用するコマンドもあります。
両者を現在のVim（やvimproc）の仕組みでは共存させることができません。

同様に、iconv()もできれば複数のエンコーディングを利用した変換に対応させたいですね。
文字化けしたら変換し直すという仕組みで。

**Comment by Shougo** [comment]
もちろん、vimprocのバグでもあります。が、termencodingにエンコーディングを一つしか指定できない現在のVimの仕様上、vimprocを修正できないのです。

**Comment by Shougo** [comment]
確か、system()はtermencodingをencodingに修正しますよね？
おそらくvimprocと同じ問題になると思います。

**Comment by koron** [comment]
vimprocが起動する先と元のエンコーディングがズレているだけでしょ? vimprocがその違いを認識して吸収すりゃいいんじゃない?

termencは現在利用中のtermの特性を示すというその性質上、複数指定できるのは間違いだよ。

**Comment by Shougo** [comment]
> vimprocが起動する先と元のエンコーディングがズレているだけでしょ? vimprocがその違いを認識して吸収すりゃいいんじゃない?

vimproc限定なら専用の変数を作れば可能です。ただ、「正しい変換」というのをどう判定するのかが問題となるのです。
Vimはどうやっているのでしょうか。
あと、system()では変換をどうしているのでしょうか。同じ問題になりますよね？

**Comment by koron** [comment]
> あと、system()では変換をどうしているのでしょうか。同じ問題になりますよね？

その問題を具体的にVimだけで示してみてよ。少なくともここまでvimproc使った時の問題しか書かれていないので、Vimの問題とは思えない。

**Comment by mattn** [comment]
system()を使わずにやってるならなおのことvimprocでfileencodingsの順で変換を試せばいいだけでは？もちろんiconv()は失敗せずに?に変換するのでvimprocのdll側でiconv用のインタフェースを作って、そっちでやる必要がありますが。

**Comment by Shougo** [comment]
Vimに外部コマンド起動用のエンコーディング指定がないのがそもそも問題のような気がしています。
仕方が無いので、vimproc（と多くのVim plugin）はtermencodingを用いていますが、それでは問題が完全に解決しません。

**Comment by Shougo** [comment]
調べてみましたが、system()はエンコーディング変換しないようです。
encoding変換は明示的にスクリプト側が行わないといけないようです。
よって、タイトルを変更しました。
外部コマンドのエンコーディングを指定できないことが問題だと思います。

**Comment by koron** [comment]
「気がしています」ではなく具体的な証拠を示してください。可能な限り単純に、他人を納得させるだけのシンプルな問題点を例示してくれれば、適切な対処方法を考慮します。

**Comment by Shougo** [comment]
> system()を使わずにやってるならなおのことvimprocでfileencodingsの順で変換を試せばいいだけでは？もちろんiconv()は失敗せずに?に変換するのでvimprocのdll側でiconv用のインタフェースを作って、そっちでやる必要がありますが。

はい。vimproc()で変換してみるのはOKです。ただ、iconv()用のインタフェースを作るのは手間がかかりすぎますね……。
うーん。Vim側でサポートしていないとやりづらいです。

**Comment by Shougo** [comment]
根拠、というのはこれまで説明したんですが、プラグイン側でいちいち外部コマンドの出力を変換しなくてはいけないところです。
さらに、外部コマンドの出力エンコーディングを示すオプションがVimに存在しません。
termencodingを用いてもいいのですが、前述のとおりこのオプションは外部コマンドの出力エンコーディングを示すものではないため、セットされていないことも多いです。termencodingは複数のエンコーディングに対応していないため、複数のエンコーディングに対応させるのは大変です。

**Comment by Shougo** [comment]
これがvimprocだけの問題ならいいのですが、外部コマンドを起動するすべてのプラグインで問題になります。
私は外部コマンドを起動するプラグインで、複数のエンコーディングを考慮したものを知りません。

**Comment by koron** [comment]
一般論として外部コマンドの入出力エンコードはその外部コマンドごとに異なります。それに対してVimが何らかの仮定をするのは外部コマンドの自由度を下げることになるため明らかに誤りです。またその外部コマンドを実行したのはプラグインですから、どのようなエンコードであるかをプラグインは知っているべきであり吸収すべきです。既存のプラグインがそれを考慮していないのは、明らかにプラグイン側の瑕疵です。

**Comment by Shougo** [comment]
> その問題を具体的にVimだけで示してみてよ。少なくともここまでvimproc使った時の問題しか書かれていないので、Vimの問題とは思えない。

system()で起動したコマンドの出力をプラグイン側では明示的に変換しなくてはいけません。
プラグイン側で文字コードが分かるならそれでもいいのですが、（特にWindowsでは）環境によって適切なエンコーディングが異なります。termencodingオプションは上述の問題により信用できません。

問題となるのがvimprocだけならオプションを増やして、それを指定してもらえば良いです。しかし、外部コマンドを起動する他のプラグインにまでそのようなオプションを実装するのは煩雑になりすぎる、というのが私の主張です。

**Comment by koron** [comment]
ちなみにmattnさんの書くスクリプトはだいたいエンコード考慮してるよねw

**Comment by Shougo** [comment]
> またその外部コマンドを実行したのはプラグインですから、どのようなエンコードであるかをプラグインは知っているべきであり吸収すべきです。既存のプラグインがそれを考慮していないのは、明らかにプラグイン側の瑕疵です。

はい。一般論として確かにそのとおりです。
ただ、外部コマンドのエンコーディングはlocaleによって異なります。
プラグイン側での適切な対応はオプション変数を作らない限り不可能だと思います。
そして、プラグインそれぞれが同じようなオプションを実装するのは無駄ではないか、というのが私の主張なのです。

**Comment by Shougo** [comment]
> ちなみにmattnさんの書くスクリプトはだいたいエンコード考慮してるよねw

おそらく、termencodingへの変換だと思うのですが……。うまいやり方があるなら、ぜひ教えてください。
ちなみに、「termencodingに依存するのは問題だ」と以前もLingrの話題には上がっていたんですよね。

**Comment by mattn** [comment]
> プラグイン側でいちいち外部コマンドの出力を変換しなくてはいけないところです。
> さらに、外部コマンドの出力エンコーディングを示すオプションがVimに存在しません。

それもしutf-8限定の標準入力しか相手しないアプリケーションにvimの文字列を渡したい場合にいちいち複数設定されていた設定をutf-8だけに変えてsystem()呼び出すとか言ってます？そっちの方が面倒でしょう。設定戻したりもしなきゃいけないし。

ちなみに知ってますか？Windowsアプリケーションはいくら標準入力でutf-8を取り扱うプログラムを書いてutf-8対応！とか言ってみたとしても、引数はACPでしか渡ってこない事を。

> 私は外部コマンドを起動するプラグインで、複数のエンコーディングを考慮したものを知りません。

外部コマンドへの標準出力は自分で考えなきゃいけない。これはプログラムが何を期待してるか分からないから。プログラムAはcp932を扱い、プログラムBがutf-8を扱う場合、個別に適切なエンコーディングに変換して起動するのはプラグイン側の仕事です。この行は言ってる意味が分かりません。
逆にコマンドからの出力を読み取る際にfileencodingsみたいに扱いたいなら仮のバッファを作って `:r!foo` を使えばいい。

> Vim側でサポートしていないとやりづらいです。

それをやるのがハッカーなんじゃないんですか？

いつも思うんですが、issueというか疑問点が自分の中で未熟な内に登録するから反論を食らうんですよ。

**Comment by mattn** [comment]
ちなみに僕がエンコーディング変換しているプラグイン処理で termencoding は使ってないと思いますよ。もしあったとしたら今すぐ直すべきバグです。

**Comment by mattn** [comment]
> ちなみに、「termencodingに依存するのは問題だ」と以前もLingrの話題には上がっていたんですよね。

なので外部コマンドの扱いに termencoding を使う事が間違いなのです。

**Comment by koron** [comment]
> そして、プラグインそれぞれが同じようなオプションを実装するのは無駄ではないか、というのが私の主張なのです。

無駄ではありません。外部コマンドの入出力のlocaleが何になるかについてVim本体は絶対にわかりません。あくまでもその外部コマンドを実行したプラグインで制御すべきことです。

**Comment by Shougo** [comment]
そうですね。ちょっとIssues登録するのが早すぎたかもしれないです。

> 外部コマンドへの標準出力は自分で考えなきゃいけない。これはプログラムが何を期待してるか分からないから。プログラムAはcp932を扱い、プログラムBがutf-8を扱う場合、個別に適切なエンコーディングに変換して起動するのはプラグイン側の仕事です。この行は言ってる意味が分かりません。

はい。そうです。ただ、この「プラグイン側で厳密な判定をする」のが難しいのではないのか、と今回思ったのです。
日本語でWindows限定ならcp932に変換すれば大体うまく行きます。
しかし、外国のコマンドではそうではありません。外国のコマンドでどういう文字コードが使われているのかプラグイン側ではわかりません。

> 逆にコマンドからの出力を読み取る際にfileencodingsみたいに扱いたいなら仮のバッファを作って :r!foo を使えばいい。

たしかにそうですね。readはどうやってエンコーディング変換をやっているのかと思っていましたが、fileencodingsを使っているんですね。ちょっとこの方向でやってみます。

**Comment by Shougo** [comment]
> ちなみに僕がエンコーディング変換しているプラグイン処理で termencoding は使ってないと思いますよ。もしあったとしたら今すぐ直すべきバグです。

了解です。ちょっと見てみます。

**Comment by Shougo** [comment]
すみません。mattnさんのエンコーディング変換しているプラグインの例を教えてもらえないでしょうか。
私も探してみたのですが、外部コマンドのエンコーディング変換をしている例が見つからなかったのです。

**Comment by mattn** [comment]
> 外国のコマンドではそうではありません。外国のコマンドでどういう文字コードが使われているのかプラグイン側ではわかりません。

Windowsの場合ならば

``` vim
:echo "cp".libcallnr("kernel32.dll", "GetACP", 0)
```

で得られる文字列が変換先のエンコーディングです。ただしこれは外部コマンドがACPを扱うという前提での場合です。
また、linux上でも動かしたいならば

```
:echo iconv(str, &encoding, "char")
```

みたいに `char` というショートカットを使うのが良いです。`char` はロケールに対応したエンコーディングを示してます。
後者の方法は僕はよく使います。

**Comment by Shougo** [comment]
！

charは知りませんでした。では、それを利用させてもらいます。

**Comment by Shougo** [comment]
今回は、「iconv()では"char"を使うべき」ということがわかり、この程度ならプラグイン側で対応可能なのでcloseします。
教えていただきありがとうございます。

**Comment by Shougo** [comment]
そもそも、「外部コマンドの出力を正しいエンコーディング変換するノウハウ」がVimmerの中で共有されていないのが一番の問題なんでしょうね。こういうノウハウは、vim-jpのサイトか:helpなどで文書化すべきではないのかと思います。

**Comment by mattn** [comment]
> こういうノウハウは、vim-jpのサイトか:helpなどで文書化すべきではないのかと思います。

iconvをCで扱った事ある人には結構常識だと思うし、これを思いつかない人はきっと `libcall` の思いつくだろうし、それを思いつかない人はvimscriptで設定出来るオプションを作ると思う。

**Comment by koron** [comment]
@mattn charってどのiconvでも使えるの?

**Comment by mattn** [comment]
vimの問題でないし、この方法が普及していないものvim自身の問題でない。
それを広めたいと思ったらぜひご自分のブログでやって下さい。

**Comment by Shougo** [comment]
> iconvをCで扱った事ある人には結構常識だと思うし、これを思いつかない人はきっと libcall の思いつくだろうし、それを思いつかない人はvimscriptで設定出来るオプションを作ると思う。

使ったことがない人がここにいます……。

**Comment by Shougo** [comment]
> vimの問題でないし、この方法が普及していないものvim自身の問題でない。
> それを広めたいと思ったらぜひご自分のブログでやって下さい。

はい。せっかく教えてもらったので、書きます。

**Comment by mattn** [comment]
@koron 1.9だかで動く様になったはず。

@Shougo 

> iconvをCで扱った事ある人には結構常識だと思うし

これはしょうがないでしょう。

> これを思いつかない人はきっと libcall の思いつくだろうし

これもWindowsの知識がいるのでしょうがないかもしれない(調べたらすぐ出てきますが)

> それを思いつかない人はvimscriptで設定出来るオプションを作ると思う。

これをやりました？ここまで来ると「encodingオプションをコマンドプロンプトのACP(日本語Windowsならcp932。chcpで変える事も出来る。)へ文字列変換したいが、そのエンコーディングが分からない。」という問題がはっきり見えてくるはずです。
すぐに過程をすっとばしてvimの問題というからこうなるのです。

**Comment by koron** [comment]
@mattn thx!

**Comment by Shougo** [comment]
> > それを思いつかない人はvimscriptで設定出来るオプションを作ると思う。
> 
> これをやりました？

はい。これを頭の中でやろうと思って今回の問題になったのですが、伝わりませんでしたね……。

> 「encodingオプションをコマンドプロンプトのACP(日本語Windowsならcp932。chcpで変える事も出来る。)へ文字列変換したいが、そのエンコーディングが分からない。」という問題がはっきり見えてくるはずです。

はい。そうですね。私の問題はこれです。
人に説明するのは難しいですね……。

**Comment by Shougo** [comment]
https://twitter.com/#!/mattn_jp/status/177319081261801472

> なんかお悩み相談所になってきたぞ

はい。スレッドを汚してしまってすみません。ただ、こういうケースもありますし、Vimmer向けのお悩み相談所もあったほうがいいとは思うんですよね。「本体の問題なのかよくわからない問題を議論する」場が欲しい。

**Comment by mattn** [comment]
質問場になるかどうかは質問内容によると思うんですよね。このissueが「コマンドプロンプトのエンコーディングを取得したい」という内容ならそうなってたでしょうし、それはそれでこのissuesを使って貰っていいと思うのですが、「termencodingの仕様は問題がある」的な書き方をしたあげくにこうなるとそれも許容し難くなります。
このissuesは登録されると題名を見ただけでvimの問題なら直そうとする人が数名いるので、題名だけでその人達の手を動かしてしまう事になります。

issuesを質問場に使うかどうかは考えないといけないすね。

**Comment by Shougo** [comment]
> このissuesは登録されると題名を見ただけでvimの問題なら直そうとする人が数名いるので、題名だけでその人達の手を動かしてしまう事になります。
> 
> issuesを質問場に使うかどうかは考えないといけないすね。

@kaoriyaさんは「どうせまだ数が少ないからこっちでやっていい」と言っていましたが、私は問題があると思います。
例えばvim-jp/questionsというものを用意して、簡単な質問ならそちらでやったほうがいいと思うのです。
その結果、本体の問題だということになればvim-jp/Issuesに格上げすればいいと思います。
githubを使いたい理由として、ログが残ること、議論に比較的簡単に参加できることが挙げられます。
ある程度ノウハウも蓄積されているし。
バグ議論の場としてだけではなく、Vimのサポートとしてのvim-jpも必要ではないのかな、と。
Vimメーリングリストでいうvim_dev的存在だけではなく、vim_useが必要なのかなと思うのです。

**Comment by koron** [comment]
以後、https://github.com/vim-jp/vim-jp.github.com/issues/33 こっちでやりましょう。

**Comment by Shougo** [comment]
はい。了解です。
