### ISSUE TITLE
autoloadテロの可能性を検討する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#18]
検討内容：
- 厳密な発生手順は?
- どのくらいの影響があるのか、起こせるのか?
- どう対処すべきか

http://twitter.com/#!/mattn_jp/status/114529886911205376

> 例えば dict で作られた foo#bar#baz のメンバの値を確認して動作を変える様な物があれば、そこで読み込まれちゃうんですよね。

**Comment by mattn** [comment]
あたり前の話ですが

autoload/foo.vim

``` vim
let g:foo#value = 1
func! foo#setup()
  " using g:foo#value
endfunction
```

plugin/foo.vim

``` vim
let foo#value = 2
call foo#setup()
```

こうすると、`foo#setup()`では1が使われるので、`let foo#value = 2`実行時には`autoload/foo.vim`は読み込み済みである必要があり、`autoload/foo.vim`が`exists("foo#value")`しているなら良いですが、`plugin/foo.vim`での`let foo#value = 2`やvimrcでのそれにあまりメリットがあるように思えないのも一つ。

**Comment by thinca** [comment]
`exists("foo#value")` は必須で、してないのがまずいと思います。
これは通常のプラグインのオプション変数と同じです。

**Comment by koron** [comment]
たぶんautoloadテロが問題になるとすれば、
modelineの設定によって馬鹿みたいにautoloadが発生して凄く重くなる
的な話くらいだろうと予想しているのですけど
これって可能性ありますか?

modelineはsandboxなのでautoloadを発生させられない
とかであればこれ以上は考える必要がないかなって思います。

**Comment by thinca** [comment]
ちょっとよくわかってないんですが、これはそもそも何が問題なんでしょうか?

**Comment by mattn** [comment]
ぼくもあまり問題が分かってない

**Comment by thinca** [comment]
誰も分かってない説…。
@koron さんもわかってなかったら閉じてしまっていい気がします。

**Comment by koron** [comment]
ファイルを開くなどしたタイミングで、
**利用者が意図しないautoloadを発生させられるか否か**
だけにフォーカスすれば良いです。

可能なら対策を考えるし、不可能ならテロはできないってことで閉じましょう。

**Comment by thinca** [comment]
何を以って利用者が意図しない autoload なのかいまいちよくわからず。
`BufReadPost` などを使っているプラグインなどはファイル読み込み時に autoload が発生する可能性が当然あるわけですが、それが問題ってことはないですよね?

**Comment by koron** [comment]
ちがいます。たとえばmodelineに

```
vim: set someoptions=foo#bar():
```

と書いたファイルを開かせたら、その瞬間にautoload/foo.vim が読まれちゃう感じ。
本来動くべきではない autoload を modeline から実行できないだろうか、というあたりです。
パッと思いつくのはfoldexprとかか?

**Comment by thinca** [comment]
基本的に式を含むオプションはセキュリティのために modeline からは設定できないはずです。

**Comment by koron** [comment]
私が過去に書いた

> たぶんautoloadテロが問題になるとすれば、
> modelineの設定によって馬鹿みたいにautoloadが発生して凄く重くなる
> 的な話くらいだろうと予想しているのですけど
> これって可能性ありますか?

これ、誰か回答できませんかね?

**Comment by mattn** [comment]
つ foldexpr

**Comment by thinca** [comment]
…と思ったけど、できるのもある?

**Comment by mattn** [comment]
まぁただmodeline実行中はsandboxですが

**Comment by thinca** [comment]
sandbox なだけで設定はできますね。勘違い。

**Comment by koron** [comment]
つまり可能性は0ではないってことで良い?

現時点で可能な対処法は sandbox でも設定可能な expr 系のオプションの動作を精査
修正していく、くらい。

そこまでわかればこの Issue は閉じて良いと考えてます。

**Comment by thinca** [comment]
> modelineの設定によって馬鹿みたいにautoloadが発生して凄く重くなる

重くなるとしたら恐らく単にスクリプトが重いわけで、autoload は関係ない気がします。重い関数はどこに書こうが重い。

**Comment by mattn** [comment]
意図的にエラーを発生させてテロっぽくする事は出来ると思います。

```
# vim:set foldexpr=vimproc#system('ls') foldmethod=expr:

{{{
yey!
}}}
```

このファイル開くと...

**Comment by koron** [comment]
まぁ vimproc は例外としてw

modeline から autoload を発生させ、その autoload から次々に別の autoload を、
というのを他のプラグインに隠してできますよね。きっと嫌がらせにすぎないんでしょうが。

**Comment by thinca** [comment]
そもそも、それは autoload 関係ないですよね。`vimproc#system` がたまたま autoload なだけで、`VimprocSystem` でも同じ事。

**Comment by thinca** [comment]
autoload ってことはユーザが意図的に入れたプラグインであるはずなので、発生するとしたら嫌がらせではなくて不幸な事故かなぁ、と。

**Comment by koron** [comment]
プラグインがトロイの木馬である可能性は?

**Comment by thinca** [comment]
その可能性を疑ったら、Vim は基本ファイル操作からなんでもできるので、普通にウィルスですね。
Vimプラグインが安全であるかどうかはユーザが担保する必要があります。

**Comment by koron** [comment]
つまり @thinca さんの主張は
**仮にそれが発生しうるとしてもユーザ責任だから Vim 側でそれについて考える/対策する必要はない**
ということでOK?

**Comment by thinca** [comment]
そうなります。インストールしたプラグインが信頼できるかどうかはユーザが責任を負うしかない。Vimプラグインに限らずソフトウェア全般に言えることかと。

**Comment by mattn** [comment]
↑のサンプル、sandboxでまずいの設定されたら設定クリアした方がいい気がする。実際↑の、カーソル移動を困難にさせる

**Comment by koron** [comment]
私は @mattn さんの

> ↑のサンプル、sandboxでまずいの設定されたら設定クリアした方がいい気がする。

これに賛成なんですよ。どうやるかは別ですがw
つまり  **考える/(可能なら)対策する必要がある** という立場。
autoload にからめてユーザの操作を困難にさせる(もしくはデータを壊す)ような抜け道がないか気になっており
仮にあるなら把握し、できることならば対策を打っておきたいのです。

特に autoload のようなポジティブ・フィードバックな仕組みに対しては
それを食い止めるなんらかのsafetyを
autoload を提供したVim自身が提供すべきという考え方です。
それは modeline の後から sandbox が提供されたようにです。

**Comment by thinca** [comment]
上のサンプルがまずいのは autoload じゃなくて式がエラーを出していることですよね? autoload は関係ない気がしますが。

**Comment by thinca** [comment]
設定クリアされた方が良い、という点には私も賛成です。ただしそれはこの Issue とは別件になるかと。

**Comment by koron** [comment]
> autoload にからめてユーザの操作を困難にさせる(もしくはデータを壊す)ような抜け道がないか気になっており

これが全てです。

**Comment by koron** [comment]
expr のエラーについては #287 立てました。

こっちは

> autoload にからめてユーザの操作を困難にさせる(もしくはデータを壊す)ような抜け道がないか

検討する Issue としましょう。もしくはそのようなパスがないことを証明しましょう。

**Comment by thinca** [comment]
少なくとも私は今のところ思い付かないですね。

> パスがないことを証明

可能なんですかね?
検討するのはもちろんいいことですが、セキュリティホールって大体潰したと思っても後からまた見つかったりするものなので、見つかるたびに対応するしかないのかなぁと思ってます。

**Comment by koron** [comment]
こういうのは、その時に持ってる情報でひととおり検討したよ、といえることが重要です。
その結果として「発生しないと判断した」なら良いんですよ。

**Comment by tyru** [comment]
例えばファイルを読み込んだだけで、modelineでrtpの先頭にパスを追加でき、なおかつautoloadを発生させることができるとかだったら脆弱性と言えそう、とか思いました。実際できないでしょうが。
どこまでがユーザの「意図通り」なのかの線引きが難しいですね。

**Comment by koron** [comment]
今持ってる情報を整理しましょう。
- 変数の読み取りで autoload が発生しうる (←これが発端であり結構問題を孕んでいる気がするが)
- 変数の読み取りを書ける(実行されうる)場所は把握できているか?
  - 仮にmodeline で発生する場合、sandbox で autoload が実行されないか? それとも sandbox 外なのか
  - その他、autoload 側で気を使わなきゃいけないもしくは、気を使ってもどうにもならないタイミングや条件はないか?

この辺が検討尽くせれば、現時点では充分でしょう。

**Comment by koron** [comment]
ふと思いついたんだけど
**autoload の地の文では関数をcallできない**
ってだけでも、対策になるかもしれない。

**Comment by tyru** [comment]
正直自分が言ったような仕様のセキュリティホールよりも、
- modeline中にnullバイト文字
- マルチバイトの上位バイトの次がnullバイト文字
- その他ユーザがVimに読み込ませるファイル、あるいはVimが読み込まざるをえないファイル中にある_不正バイト列によるSEGV_を利用した乗っ取り

の方がVimにとってはありそうかもと思いました。

**Comment by thinca** [comment]
トップレベルで関数が呼べないと動かなくなるスクリプトが大量に出るので互換性の面から無理ですね。

**Comment by tyru** [comment]
Windowsで`con#func()`とか`nul#func()`とかやったらフリーズさせられるかと思ってやってみたけどできませんでした...

**Comment by koron** [comment]
アレをやろうと考えているわけではなく、
アレで解決されていることが問題の本質を捕まえる手がかりになる
と考えているのです。

**Comment by koron** [comment]
> トップレベルで関数が呼べないと動かなくなるスクリプトが大量に出るので互換性の面から無理ですね。

そういえば、過去にはその互換性の面を捨てて sandbox 導入した経緯もあるから、無理とは言えない。
結局のところ影響とのトレードオフなんでしょう。

**Comment by koron** [comment]
Vim がセキュリティについて sandbox アプローチを取っている以上
autoload と sandbox の関係に絞って考えるのが良さそう。

sandbox 環境下で autoload 発生させるようなケースにおいて
- autoload 実行時に sandbox が機能しているか検証する
  - sandbox で実行されて困る可能性はないか
  - sandobx から抜けてしまう(セキュリティホールになる)可能性はないか
- sandbox として追加で制限しなければならない操作はないか

という感じで考えるのが良いだろう。

**Comment by koron** [comment]
なんか sandbox の定義をみていると「新しい関数は定義できない」とあったので、
sandbox 内で autoload が機能するならば、それはそれでおかしい気もするw

**Comment by tyru** [comment]
ww

**Comment by koron** [comment]
考察内容としては https://github.com/vim-jp/issues/issues/18#issuecomment-11688350 に書いたことに絞られたので
とりあえず一旦終了としましょう。

**Comment by koron** [comment]
特にこれ以上のアクションは必要ないので wontfix としました。
「将来、何かあった時の指針として使う」という感じ。
