### ISSUE TITLE
mingwでif_perlのビルドに失敗する

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#180]
gcc4からstaticでないグローバル関数のプロトタイプ宣言がエラーになる。

パッチ提出済み。

https://groups.google.com/d/topic/vim_dev/3KD82kZJwgo/discussion

**Comment by h-east** [comment]
イェイ!
Patch 7.3.474
https://groups.google.com/d/topic/vim_dev/Bbc3wABsJ4k/discussion
