### ISSUE TITLE
タスクバーが上部にある場合にウィンドウ位置が不正になる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#181]
http://twitter.com/Eivy_m/statuses/179803215230009344

> 環境はWindowsXP SP3、20120308版の香り屋vimです。windowsのタスクバーが画面上にある状態で :set lines=200 など、画面いっぱいに表示しようとすると、ウインドウ上部の位置がおかしく、ウインドウ下部が切れてしまいます。

**Comment by koron** [comment]
なるほどw タスクバーが左右にある場合の調整もおかしくなる可能性ありかな。

**Comment by mattn** [comment]
``` c
APPBARDATA barinfo;
SHAppBarMessage(ABM_GETTASKBARPOS,&barinfo);
```

で取れそげ。

**Comment by mattn** [comment]
``` diff
diff -r 2cfb68fa26cd src/gui_w32.c
--- a/src/gui_w32.c Wed Mar 28 20:51:51 2012 +0200
+++ b/src/gui_w32.c Tue Apr 17 14:36:50 2012 +0900
@@ -1667,6 +1667,7 @@
     /* Get position of the screen work area.  This is the part that is not
      * used by the taskbar or appbars. */
     get_work_area(&workarea_rect);
+    OffsetRect(&workarea_rect, -workarea_rect.left, -workarea_rect.top);

     /* Get current posision of our window.  Note that the .left and .top are
      * relative to the work area.  */
```

gui_mch_set_shellsizeは、GetWindowPlacementで得た矩形に対してget_work_areaで得た矩形が収まる様にリサイズする処理だが、GetWindowPlacementは相対座標、get_work_areaは絶対座標となる。最終的に位置設定するAPI、SetWindowPlacementは相対なので、get_work_areaが相対になればうまくまとまる。

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/xRdOvRDM3-Y/discussion

**Comment by mattn** [comment]
@ynkdir ↑のパッチだと問題ありましたか？もしくはそっちの方がスマート？

**Comment by ynkdir** [comment]
より分かりやすいかなというつもりで投稿しましたがよく考えると上のパッチはうまくいかない気がしてきました。
例えばモニターを左右に並べて左（プライマリ）が50x50で右（セカンダリ）が100x100というサイズで、ウィンドウがセカンダリにあるとき、xoffが50になると思います（タスクバーが無いので0にならないといけない）。
今ちょっと試せませんが。

**Comment by mattn** [comment]
SetWindowPlacement はモニタ内座標だったかと思います。

**Comment by ynkdir** [comment]
left=0,top=0 で常にプライマリに移動してしまうということで以前あの辺直したはずなのでモニター相対でなかった気がします。
後で確認します。

**Comment by mattn** [comment]
お願いします

**Comment by ynkdir** [comment]
確認しました。
モニター相対座標ではなかったです。
タスクバーの無いワークエリアでは GetWindowPlacement() と GetWindowRect() は同じ RECT が返ってきます。
で、上のパッチ確認しましたが、ウィンドウがセカンドモニターにあるときにうまく動いてませんでした。
`:set lines=xxx` でリサイズするとウィンドウが二つのモニタの間に移動します。
たぶん解像度が違うとうまく動かないはずです。

**Comment by mattn** [comment]
お手数ですが、もしつっこまれたらその辺を英語(汗)で説明してあげて下さい。

**Comment by ynkdir** [comment]
了解です。一応メール出しときます。

**Comment by k-takata** [comment]
todo入りしていますので閉じます。

```
MS-Windows resizing problems:
- Windows window on screen positioning: Patch by Yukihiro Nakadaira, 2012 Jun
  20.  Uses getWindowRect() instead of GetWindowPlacement()
- Win32: When the taskbar is at the top of the screen creating the tabbar
  causes the window to move unnecessarily. (William E. Skeith III, 2012 Jan
  12) Patch: 2012 Jan 13  Needs more work (2012 Feb 2)
```

**Comment by k-takata** [comment]
最近、このバグによる[質問があった](https://teratail.com/questions/277168)ので、状況を進展させるために PR を出しました。https://github.com/vim/vim/pull/6455
reopenしておきます。

**Comment by k-takata** [comment]
8.2.1226: https://github.com/vim/vim/commit/98af99f2d79b310e81003f5e27862a7b522d8372
