### ISSUE TITLE
コマンドモードでの単語のコピーが正常に動作しない

### ISSUE THREAD

**Issue by kyouryuukunn** [vim-jp/issues#183]
再現法
挿入モードで任意の単語、ここではtestを入力
その単語上でコマンドモードへ
単語の先頭文字を入力、ここではt
C-R,C-Wを入力
ttestとなるはずだが、testとなっている
vim73-kaoriya-win32-20120324を何も設定をいじらない状態でも発生している。
set incsearchを設定するとこうなるようだ。

**Comment by thinca** [comment]
仕様です。

`:help c_CTRL-R_CTRL-W`

> 'incsearch'がセットされてるとき、現在表示されているマッチの末
> 尾のカーソル位置が使われる。CTRL-Wではwordの一部がすでに入力さ
> れているとき、その部分がもう一度入力されることはない。
> (訳註: wordという単語のrの上にカーソルを置き、:wo<C-r><C-w>と
> してみると、'incsearch'の値によって結果が違うことがわかる)

**Comment by kyouryuukunn** [comment]
仕様だったのか。残念

**Comment by mattn** [comment]
閉じますね。

**Comment by thinca** [comment]
一応解決手段を書いておきますね。

``` vim
cnoremap <C-r><C-w> <C-r>=expand('<cword>')<CR>
```
