### ISSUE TITLE
home_replaceが正しく動作していない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#185]
指定するパスが HOME 配下にある場合 `fnamemodify(path, ':~')` で `~/foo/bar` の様なパスに変換してくれるのだけど、Windowsでちゃんと動いていない。
例えば僕はunix系ツールが誤動作しないように HOME 環境変数を `c:/docume~1/mattn` と設定しているのだけど、WindowsのAPIから得た HOME は `C:\Documents and Settings\mattn` になるのでいくら大文字小文字を同一視しても一致しない。もしかしたら WIN32API の`GetShortPathName` を使えば `c:/docume~1` を取る事が出来るかもしれない。
ちなみにこの処理をやってるのが home_replace

**Comment by koron** [comment]
Windows Vista以降はホームディレクトリが C:\Users\koron みたいになるので問題にならんのか?

**Comment by mattn** [comment]
たぶん。

**Comment by mattn** [comment]
``` diff
diff -r 2cfb68fa26cd src/misc1.c
--- a/src/misc1.c   Wed Mar 28 20:51:51 2012 +0200
+++ b/src/misc1.c   Tue Apr 17 14:05:30 2012 +0900
@@ -4284,6 +4284,7 @@
 {
     size_t dirlen = 0, envlen = 0;
     size_t len;
+    char_u pathbuf[MAXPATHL];
     char_u *homedir_env;
     char_u *p;

@@ -4314,6 +4315,10 @@
 #else
     homedir_env = mch_getenv((char_u *)"HOME");
 #endif
+#if _WIN32_WINNT >= 0x0500
+    GetLongPathName(homedir_env, pathbuf, sizeof(pathbuf));
+    homedir_env = pathbuf;
+#endif

     if (homedir_env != NULL && *homedir_env == NUL)
    homedir_env = NULL;
```

安定してたら出す。

**Comment by mattn** [comment]
どうやらこの関数に入ってくるsrc自体がLongPathNameらしいので、homedir_envの方をLongPathNameにした。

**Comment by mattn** [comment]
ちょっと修正

``` diff
diff -r 2cfb68fa26cd src/misc1.c
--- a/src/misc1.c   Wed Mar 28 20:51:51 2012 +0200
+++ b/src/misc1.c   Tue Apr 17 17:10:19 2012 +0900
@@ -4314,6 +4314,13 @@
 #else
     homedir_env = mch_getenv((char_u *)"HOME");
 #endif
+#if _WIN32_WINNT >= 0x0500
+    {
+   char_u  pathbuf[MAXPATHL];
+   if (GetLongPathName(homedir_env, pathbuf, sizeof(pathbuf)) != 0)
+       homedir_env = pathbuf;
+    }
+#endif

     if (homedir_env != NULL && *homedir_env == NUL)
    homedir_env = NULL;
```

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/28bbZcBon18/discussion

**Comment by h-east** [comment]
todoリスト入り。

> Patch: home_replace() does not work whtn 8.3 filename. (Yasuhiro
> Matsumoto, 2012 Apr 18)  Asked for another version of the patch.

**Comment by mattn** [comment]
入った。

7.3.559

https://groups.google.com/d/topic/vim_dev/plGpUcylLBs/discussion

**Comment by mattn** [comment]
@koron 今回の修正は `_WIN32_WINNT >= 0x0500` が必須なのでビルドの際、気を付けて。ちゅうか Windows 98 で vim 使う人もうおらんのちゃう？

**Comment by koron** [comment]
@mattn VC10でコンパイルしてるんだけど、2000とかもうとっくに動かないらしいよ。

**Comment by k-takata** [comment]
@mattn 2年以上も前のパッチですが、問題と思われる点を見つけました。
1. バッファサイズの指定が間違っている。  
   確保しているサイズは、`_MAX_PATH + 1` (=261) ですが、GetLongPathName に渡しているサイズは `MAXPATHL` (=1024) です。バッファオーバーフローするかもしれません。
2. Wide版APIを使っていない。  
   おそらく、enc=utf-8 のとき、パス名にマルチバイト文字が含まれていると正しく動きません。ま、上にあるように Vista 以降は不要なのかもしれませんが。

**Comment by k-takata** [comment]
1.&nbsp;についてはパッチを送付。
https://groups.google.com/d/topic/vim_dev/WJb26FXMG7g/discussion
2.&nbsp;については @mattn さんが何とかしてくれるものと期待しています。

**Comment by k-takata** [comment]
7.4.522
https://groups.google.com/d/topic/vim_dev/iXkOuUWH7VI/discussion
2.&nbsp; については、Bramからも指摘がありました。

**Comment by k-takata** [comment]
4年越しの 2. の修正
https://github.com/vim/vim/pull/4007

**Comment by k-takata** [comment]
8.1.1090: https://github.com/vim/vim/commit/2d04a91d691ae1ea0c3bf9fc522c3fddc2c9746a
