### ISSUE TITLE
system()の実装がwait()することにより、vimprocのwaitpid()内でエラーになることがある

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#188]
これは、@eagletmtさんが発見してくれた問題です。

https://twitter.com/#!/eagletmt/status/186741487076245505

> @ShougoMatsu 原因はわからないですけど、たとえば https://gist.github.com/2281904 を実行すると waitpid() のエラーが出るんですよね

https://gist.github.com/2281904

https://twitter.com/#!/eagletmt/status/186833385979789313

> @ShougoMatsu gist で示した例で発生するのは ECHILD です。他のエラーは今のところ見たことないですね。もうすこし自分のほうで調べてみます。

https://twitter.com/#!/eagletmt/status/186851288502382593

> @ShougoMatsu 原因は system() において Vim が内部で fork して wait するときに回収されるからのようでした。ここを wait でなく waitpid に変えたところ、先程のエラーは発生しなくなりました。

system()の実装がwait()を用いている理由はなぜでしょうか。
この仕様では、KoRoNさんが実装している非同期機構でも（独自に外部プロセスを生成した場合）問題になりそうですがどうでしょうか。
これはVim本体にパッチを投げるべきでしょうか。それとも、vimproc側でなにか対策する方が良いのでしょうか。

**Comment by koron** [comment]
すでに https://github.com/vim-jp/issues/issues/187 でやってます。

**Comment by koron** [comment]
#187 こうかけば良いのかな?

**Comment by Shougo** [comment]
ありがとうございます。
