### ISSUE TITLE
WinコンソールでIMEからの入力が化ける

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#189]
Windows CUIのvimにて

```
set enc=utf-8 tenc=cp932
```

した環境だと、IMEからの入力が文字化けする…なんで?

**Comment by mattn** [comment]
あー、こっちだ。
MSIMEですが、まず入力出来ないっす。

**Comment by k-takata** [comment]
修正案です。
https://gist.github.com/3775677

convert_input() を使っていたために変換できなかった文字が捨てられてしまい、正しく機能していませんでした。
convert_input_safe() を使って書き直しましたが、ちょっと怪しいです。2バイト文字の1バイト目だけを与えて変換すると、戻り値 1 でバッファの中身が "\0" が返ってきてしまいましたがこれは正しい動作なのか？

**Comment by ynkdir** [comment]
パッチ試してみましたが変わらないです

**Comment by k-takata** [comment]
がーん、上記パッチXPだと動いていたのですが、Win7だと動きませんでした。
不正な1バイトをMultiByteToWideCharだかに食わせたときの挙動が違う？

**Comment by mattn** [comment]
http://msdn.microsoft.com/en-us/library/windows/desktop/ms684166(v=vs.85).aspx

これの AsciiChar を使ってますが、UnicodeChar を使えば治るとか。

**Comment by k-takata** [comment]
入力をUnicode APIを使って、terminalencodingを無視してしまうのはそれはそれでありかもしれませんね。
結経修正量が多くなりそうな気がしますが。

**Comment by k-takata** [comment]
とりあえず、ANSI APIのまま修正してみました。Win7とXPでの動作は確認できました。
https://gist.github.com/3775677/30ae5596627c0d165e04c325eec5fad353806841

string_convert_ext()の中をいじってしまったので、他に影響がないかが少し心配なところ。
unconvlenpが指定されているときだけ、不正なマルチバイト文字をエラーとするようにしたので、大丈夫だとは思うのですが。

**Comment by ynkdir** [comment]
＝ (=0x8181)
ー (=0x8185)
などが入力できないです。

**Comment by k-takata** [comment]
自分のところでは問題なく入力できています。何だろう？

**Comment by ynkdir** [comment]
"＝" は勘違いでした。
"ー" が入力できなくて、"ー" 入力後はどの文字も入力できなくなります。

**Comment by ynkdir** [comment]
入力できない状態でいろいろ入力してから
IMEをオフにしてキーをがちゃがちゃやってると入力できるように戻ります。
入力できない状態で入れた文字は?(gaで見ると変換エラー的なコード)で表示されます。

**Comment by ynkdir** [comment]
すいません ー (0x815b) かもしれないです。
長音記号です。

**Comment by ynkdir** [comment]
あ、これパッチなしのノーマルvimでもだめですね。

**Comment by ynkdir** [comment]
5b=<esc> 関係かな

**Comment by k-takata** [comment]
うーん、やはり自分のところでは問題ないです。
0x5b だと [ ですか？

**Comment by ynkdir** [comment]
`<esc>` です。
ちなみに vista です。

**Comment by ynkdir** [comment]
enc は cp932 でも utf-8 でもだめみたいです

**Comment by ynkdir** [comment]
5bはescじゃないや勘違い。
じゃーなんでだろ。

**Comment by ynkdir** [comment]
"。" とか "、" とかもだめですねー
ー 0x815b => `<c-[>`
、 0x8141  => `<c-a>`
。 0x8142 => `<c-b>`
と解釈されてるような感じです。

**Comment by ynkdir** [comment]
コマンドプロンプトのプロパティでフォントの設定を "MS ゴシック" から "ラスタフォント" に変えたら直りました。

MS ゴシック のときに例えば "、" を入力すると、未確定文字は半角で表示され、
そのまま確定すると ReadConsoleInput() で 0x01 というキーが取れるという謎動作。

**Comment by mattn** [comment]
なっ...! なんだってーーーーーーーーーー！

**Comment by ynkdir** [comment]
UnicodeChar が 0x3001 (U+3001, "、") になっててそれで union の AsciiChar が 0x01 になっちゃった感じですね。

**Comment by mattn** [comment]
あー、やっぱりUnicodeChar取らなきゃ駄目なのか

**Comment by ynkdir** [comment]
それが確実だと思います。

上記の問題ですがフォントの大きさも関係あるみたいです。
MSゴシック 12 は OK で 14 は NG でした。

**Comment by k-takata** [comment]
> 上記の問題ですがフォントの大きさも関係あるみたいです。

そんなバナナ。と思って自分の環境（Vista含む）でいろいろ試してみましたが一切問題起きていないですね。
ANSI APIがUnicodeな動作をするなんて意味不明すぎるんですがｗ

と、ここまで書いてmanifestを使ってビジュアルスタイルを有効にすると、ANSI APIがUnicode APIのように動作する問題があったのを思い出しましたが、それが今回の問題と関係するのかどうなのか…

**Comment by ynkdir** [comment]
ReadInputConsoleA()だとDBCS文字は二つのキーイベントで飛んできますが
例えば "あ" と入力すると
1: AsciiChar=0x82 UnicodeChar=0x0082
2: AsciiChar=0xa0 UnicodeChar=0x30a0
となり、二つ目のキーイベントでユニコードの上位バイトとDBCSの下位バイトがまざった値が取れます。
"、" を入力すると UnicodeChar にユニコードがセットされたキーイベントが一つだけ飛んできます。
U+30xx あたりの文字は全部だめみたいです。

**Comment by ynkdir** [comment]
おぉうちだけですか…。なんか壊れてるのかな…。

**Comment by mattn** [comment]
僕は k-tanaka さんのパッチだけでうまく動いてそうです。

**Comment by h-east** [comment]
そんなバナナ++

**Comment by mattn** [comment]
iconvの変換などで「森鷗外」が「森鴎外」とタイプされないかなーと少し期待しましたが「森?外」となりました。まぁ仕方ない。

**Comment by k-takata** [comment]
k-tanakaだと思った？ 残念、k-takataでした。

それはさておき、「森鷗外」対応は、恐らく mch_inchar(), tgetch(), decode_key_event(), win32_kbd_patch_key() 辺りをごっそり書き換えないといけないので結構大変そうです。
ReadConsoleInputW() を使って UnicodeChar を参照して、ToAscii() の代わりに ToUnicode() を使うことになるのでしょう。

**Comment by k-takata** [comment]
vim_devに投げました。
https://groups.google.com/d/topic/vim_dev/fCCAHVurObg/discussion

**Comment by k-takata** [comment]
todo.txt 入りになりました。

> Patch to make multibyte input work on Win32 console when codepage differs from
> 'encoding'. (Ken Takata, 2012 Sep 29)

**Comment by ynkdir** [comment]
あんまり影響ないとは思いますが、
特定のコードページで dwFlags を 0 以外にすると ERROR_INVALID_FLAGS で失敗するらしいです。

MultiByteToWideChar function
http://msdn.microsoft.com/en-us/library/windows/desktop/dd319072.aspx

```
For the code pages listed below, dwFlags must be set to 0. Otherwise, the function fails with ERROR_INVALID_FLAGS.

    50220
    50221
    50222
    50225
    50227
    50229
    57002 through 57011
    65000 (UTF-7)
    42 (Symbol)

Note  For UTF-8 or code page 54936 (GB18030, starting with Windows Vista), dwFlags must be set to either 0 or MB_ERR_INVALID_CHARS. Otherwise, the function fails with ERROR_INVALID_FLAGS.
```

**Comment by k-takata** [comment]
"dwFlags must be set to either 0 or MB_ERR_INVALID_CHARS." なので、今回使った MB_ERR_INVALID_CHARS は問題ないと思います。

**Comment by ynkdir** [comment]
それは UTF-8 と CP54936 の話です。

**Comment by k-takata** [comment]
ああ、勘違いしていました。
CP50220はISO-2022-JPで、他の5022XもISO-2022系のようですね。570XXはインド系文字？
ISO-2022系をカレントコードページに指定して、直接キーボードから入力ということはまずないでしょうが、
570XXがよく分からないですね。

**Comment by koron** [comment]
TODO リストに入ったらしいので閉じておきます。まずかったら開いてください。

**Comment by h-east** [comment]
todoリスト入り。

> Patch to make multibyte input work on Win32 console when codepage differs from
> 'encoding'. (Ken Takata, 2012 Sep 29)

**Comment by k-takata** [comment]
7.3.814 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/FqMPnkbf8Lw/discussion
（Unicodeには対応していないという課題は引き続き残っていますが。）
