### ISSUE TITLE
セキュリティソフトに引っかかるらしい

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#190]
だれかNorton持ってる人いたらちょっと気にしておいてください。一人でもひっかからないことが確認取れた時点で xlose/worksforme に落として良いでしょう。そのとき、どのような環境でひっかからなかったか併記してもらえると助かります。

> Windows版のvimを落としてgvimを起動したら、「怪しい動きをしているアプリケーションが発見されました」というNortonのダイログとともに、アプリが削除された件

https://twitter.com/#!/lizard_isana/status/194290571022573570

**Comment by mattn** [comment]
nortonは持ってないなー

**Comment by thinca** [comment]
別の報告を発見。

> Windowsにvimをインストールして立ち上げようとしたらNortonがvimを勝手に削除しようとするんだが(・・;)

https://twitter.com/#!/okamo_dayo/status/196867782917373952

**Comment by thinca** [comment]
詳しい環境を聞いてみました。
- Windows 7 Ultimate x86
- Vim 7.3.509 +kaoriya 32bit版
  - 本日DLしたとのことなので使用OSと組み合わせると恐らくこれ。
- Norton Internet Security 2012
  - 削除されるらしい

https://twitter.com/#!/okamo_dayo/status/196871140700991488
https://twitter.com/#!/okamo_dayo/status/196872355992174593

**Comment by koron** [comment]
まーじかーw

**Comment by koron** [comment]
シマンテックのフォーラム見てたらこんなんがあった。

http://communityjp.norton.com/t5/forums/forumtopicpage/board-id/NIS_NAV/thread-id/51
http://communityjp.norton.com/t5/forums/forumtopicpage/board-id/NIS_NAV/message-id/74/highlight/true#M74

WS.Reputation.1 ぽいなー

**Comment by mattn** [comment]
これってその後...

**Comment by koron** [comment]
完全にひっかかってますな。

**Comment by koron** [comment]
対策するのもめんどそうだが…

**Comment by koron** [comment]
#246 で記事を書く流れ。なのでこっちは閉じておきます。
