### ISSUE TITLE
less.sh/less.vimの動作をlessに近づける

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#191]
less.sh/less.vimの動作をlessに近づけたいと思い、次のようなパッチを作りました。
https://gist.github.com/2484229

変更内容は以下の通りです。
1. ファイルの末尾でスペースキーを押したときに、Vimを終了せずに、何もしないようにする。(less.vim)
   
   現状の動作は、lessではなくmoreです。
2. 入力がリダイレクトされておらず、ファイル名の指定もないときに、ユーザーからの入力待ちになるのではなく、エラー終了するようにする。(less.sh)
   
   ユーザーから入力されたものを表示しても意味がないと思うので、とりあえずlessと同じように、"Missing filename"と表示するようにしています。
   （ついでに、インデントがおかしかったので修正。（sw=2に統一））

**Comment by ynkdir** [comment]
1 はやるならファイル切り替えの挙動も変えないといけない気がします。

2 は親切でいいと思います。

ただまあこういうどっちもありだなというものは扱いが難しいですねぇ。
気軽にこんなのどうよ？と提案できるスキルが私にあればよかったのですが…。

**Comment by k-takata** [comment]
> 1 はやるならファイル切り替えの挙動も変えないといけない気がします。

s:NextPage()を以下のようにすれば、勝手に次のファイルに行かないようになりますが、そこまですべきかどうかは分からないですね。次のファイルに行ってしまっただけなら、:N で戻ることは可能ですが、終了してしまったら戻りようがないので、それだけは直したいです。

``` vim
fun! s:NextPage()
  if line(".") != line("$")
    exe "normal! \<C-F>"
  endif
endfun
```

**Comment by k-takata** [comment]
おまけで、Windowsユーザー用に、less.shの代わりにless.batを作ってみました。
https://gist.github.com/2517336
less.shとは異なり、標準出力がリダイレクトされているかどうかは判定できないので、その場合の処理は省いています。

**Comment by ynkdir** [comment]
もし vim_dev にもっていくなら最終的には Bram の判断なので好きな方でいいと思います。

**Comment by k-takata** [comment]
https://groups.google.com/forum/?hl=ja#!topic/vim_dev/Zqx6yTRKl_U
パッチを投げてみました。（リンクはこれで合ってるのかな？）

**Comment by ynkdir** [comment]
おつです！
いい反応きてますねー。

**Comment by k-takata** [comment]
どうもです。
どなたか、`status/sent patch`に変更しておいていただければ。

**Comment by thinca** [comment]
取り込まれました。

http://code.google.com/p/vim/source/detail?r=1b584a6f446ccd933002c91b9c3f07cfdf65d886

**Comment by k-takata** [comment]
less.vim で気になる挙動があったので、パッチ送付。
https://groups.google.com/d/topic/vim_dev/bgVylP0j2y0/discussion
