### ISSUE TITLE
日本語ドキュメントへのリンクが載っていない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#194]
:help help-translated と http://www.vim.org/translations.php を見たところ、どちらも日本語ドキュメントへのリンクが載っていません。載せてもらった方がよいのではないでしょうか。

**Comment by koron** [comment]
Requested.

https://groups.google.com/d/msg/vim_dev/CdEFUXoSqQ0/NzF964kYKegJ

**Comment by h-east** [comment]
@k-takata ++
@koron 早っ! おつです。

**Comment by koron** [comment]
たまたまですw

**Comment by h-east** [comment]
Added. Johnさんありがとう。
https://groups.google.com/d/msg/vim_dev/CdEFUXoSqQ0/97i2ZNH-h7MJ

**Comment by koron** [comment]
ハエーよwww

**Comment by k-takata** [comment]
:help help-translated に載っていないのはどうしますか？

**Comment by h-east** [comment]
> :help help-translated に載っていないのはどうしますか？

あっ、すんません。クローズしちゃった＞＜     Reopen？

**Comment by koron** [comment]
patch作って送れば取り込んでくれるでしょう

**Comment by k-takata** [comment]
https://gist.github.com/2559599
パッチを作りましたが、その後どうすれば……状態です。

``` diff
diff -r 1be42b88900e runtime/doc/helphelp.txt
--- a/runtime/doc/helphelp.txt  Thu Apr 26 20:17:03 2012 +0200
+++ b/runtime/doc/helphelp.txt  Tue May 01 01:03:01 2012 +0900
@@ -218,11 +218,12 @@
 This is only available when compiled with the |+multi_lang| feature.

 At this moment translations are available for:
-   Chinese - multiple authors
-   French  - translated by David Blanchet
-   Italian - translated by Antonio Colombo
-   Polish  - translated by Mikolaj Machowski
-   Russian - translated by Vassily Ragosin
+   Chinese  - multiple authors
+   French   - translated by David Blanchet
+   Italian  - translated by Antonio Colombo
+   Japanese - multiple authors
+   Polish   - translated by Mikolaj Machowski
+   Russian  - translated by Vassily Ragosin
 See the Vim website to find them: http://www.vim.org/translations.php

 A set of translated help files consists of these files:
```

**Comment by koron** [comment]
…なんでJapanese以外の行に修正が入ってるのですかね?改行コードか、タブ文字かしら?

必要のないところは変更しないパッチにしたほうが良いです。

**Comment by mattn** [comment]
@k-takata ありがとうございます。ソースを修正するので、patch authorとして名前が必要になります。お名前を教えて下さい。譲渡する場合は私を含む他の人が代理投稿しますがpatch authorはその人になってしまうかと思います。

**Comment by mattn** [comment]
@koron japanese は長いので「-」を位置をずらして頂いたのだと思います。

**Comment by koron** [comment]
@mattn あ、そういうことかw

**Comment by k-takata** [comment]
"Ken Takata"でお願いします。

**Comment by mattn** [comment]
あ...その前に。ご自分でポストされます？

**Comment by k-takata** [comment]
今回は代理でお願いします。

**Comment by mattn** [comment]
了解です。
下手な英語になりますがご了承下さい。

**Comment by uakms** [comment]
本家の Documentation → Vimdoc site のようにたどると http://vimdoc.sourceforge.net に到達します。
ここでの Vim Help File Translations → Japanese Vim documentation のリンク先が www.kaoriya.net になっていますが、リダイレクト処理などはしないのですか？

**Comment by koron** [comment]
Ploneの設定がめんどいのでとりあえずはリンクだけ貼りました。

vimdoc.sourceforge.comのほうに連絡とってみましょう。

**Comment by koron** [comment]
[Requested](https://sourceforge.net/tracker/?func=detail&aid=3522782&group_id=36298&atid=416529)

**Comment by uakms** [comment]
(前回のコメントは言葉使いがラフ過ぎたので訂正しました)
vimdoc.sourceforge.net は休止状態のようなのでリンクの更新は望み薄な感じですね。
リダイレクトではなくリンクの提示だけで十分だと思います。

**Comment by k-takata** [comment]
helphelp.txtの更新は、7.3.518に入ったようですね。

**Comment by thinca** [comment]
[Webサイト](http://www.vim.org/translations.php) と [:help help-translated](http://code.google.com/p/vim/source/diff?spec=svn1b584a6f446ccd933002c91b9c3f07cfdf65d886&old=e8a482a7fa6c0bf25f009b096202795400c9681a&r=1b584a6f446ccd933002c91b9c3f07cfdf65d886&format=unidiff&path=%2Fruntime%2Fdoc%2Fhelphelp.txt) どちらも取り込まれたようなので閉じます。
