### ISSUE TITLE
:help の検索から返ってこないことがある

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#2]
主に日本語のhelpを引く場合、検索が終わらずにフリーズしてしまうことがある。`<C-c>`で抜けられる。
`:set notagbsearch` で改善することから、恐らく `:helptags` で生成される tags ファイルが正常にソートされていない?

**Comment by mattn** [comment]
これ再現パターン見つけ出すのは難しいですか？

**Comment by thinca** [comment]
そうですね…1度見つけるとそのパターンでは確実に発生するのですが、
他の人の環境でも同じワードで発生するとは限らないようです。恐らく入れてるプラグインによってタグ全体が変わるから?
私自身は最近は notagbsearch してしまっているので発生してません。

**Comment by ynkdir** [comment]
:help 'tagbsearch' 末尾

This option doesn't affect commands that find all matching tags (e.g.,
command-line completion and ":help").

:help の検索では二分探索しないらしいのでもしかしたら別の原因かもかもしれませんね。

**Comment by vikke** [comment]
以下の環境で再現ありました。
ubuntu 10.04
$ uname -a
Linux jaco 2.6.32-33-generic-pae #72-Ubuntu SMP Fri Jul 29 22:06:29 UTC 2011 i686 GNU/Linux

vim自体は自前で7.3.322をcompileしました。
configure --with-features=huge --enable-luainterp=yes --enable-mzschemeinterp --enable-pythoninterp --enable-rubyinterp=yes --enable-cscope --enable-multibyte --enable-xim --enable-gtk2-check --with-x 

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep 24 2011 02:03:32)
適用済パッチ: 1-322
Compiled by vikke@jaco
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
+arabic +autocmd +balloon_eval +browse ++builtin_terms +byte_offset +cindent +clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments +conceal +cryptv +cscope
 +cursorbind +cursorshape +dialog_con_gui +diff +digraphs +dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path +float +folding -footer +fork()
 +gettext -hangul_input +iconv +insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap +lua +menu +mksession +modify_fname +mouse +mouseshape
 +mouse_dec -mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse +mouse_xterm +multi_byte +multi_lang +mzscheme +netbeans_intg +path_extra -perl +persistent_undo +postscript 
+printer +profile +python -python3 +quickfix +reltime +rightleft +ruby +scrollbind +signs +smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title +toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo +vreplace +wildignore
 +wildmenu +windows +writebackup +X11 -xfontset +xim +xsmp_interact +xterm_clipboard -xterm_save 
      システム vimrc: "$VIM/vimrc"
        ユーザ vimrc: "$HOME/.vimrc"
         ユーザ exrc: "$HOME/.exrc"
     システム gvimrc: "$VIM/gvimrc"
       ユーザ gvimrc: "$HOME/.gvimrc"
    システムメニュー: "$VIMRUNTIME/menu.vim"
       省略時の $VIM: "/usr/local/share/vim"
コンパイル: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -D_REENTRANT -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12     -g -O2 -D_FORTIFY_SOURCE=1    -DMZ_PRECISE_GC -DINCLUDE_MZSCHEME_BASE -I/usr/include/plt       -DMZSCHEME_COLLECTS=/usr/lib/plt/collects  
リンク: gcc   -L. -Wl,-Bsymbolic-functions -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim   -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -lncurses -lnsl  -lselinux   -L/usr/lib -llua5.1 /usr/lib/libmzscheme3m.a  -L/usr/lib/python2.6/config -lpython2.6 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions   -lruby1.8 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib   

.vimrcの設定や導入しているplugin等は https://github.com/vikke/config に上げてあります。
vimdoc-jaのtags-jaですが、gitからひっぱった物をそのまま使っています。また、念の為:helptagsをvimdoc-jaに対して行ないましたが、differはありませんでした。

検索が出来ない単語はたとえば:mapです。

以上、なにか参考になれば幸いです。

**Comment by koron** [comment]
@vikke: vimdoc-jaのインストール方法ですが、どうやってます? 既存のruntimepathのどれかにファイル群を追加するか、独立したディレクトリに置いてruntimepathに追記する形か。

というのもKaoriYa版にはvimdoc-jaを後者の方法で取り込んでいてかつ問題が発生していないので、そのあたりに切り分けポイントがないか確認したい次第。

**Comment by vikke** [comment]
pathogen使ってます。git submodule addで、bundleの下に入れてます。

**Comment by ynkdir** [comment]
再現できました

```
$ git clone --recursive https://github.com/vikke/config.git
$ cd config/.vim
$ vim -u NONE -N --cmd "set rtp+=$PWD"
:call pathogen#runtime_append_all_bundles()
:call pathogen#helptags()
:help :map
```

**Comment by mattn** [comment]
@ynkdir アサインさせて貰いました。

**Comment by ynkdir** [comment]
了解です。

とりあえず原因はtag検索における "!_TAG_FILE_ENCODING" の取扱いの不具合です。
:help や日本語ヘルプ特有の問題ではありませんが日本語ヘルプのタグ生成ではタグファイルに "!_TAG_FILE_ENCODING" が設定されるため発生していました。

ex_help():
  :help の検索 (find_help_tags) ではバイナリサーチは使われないが
  検索されたタグを開くとき (do_tag) はバイナリサーチが使われる。

find_tags():
  バイナリサーチ中に "!_TAG_FILE_ENCODING" を発見すると無限ループする。

```
$ cat tags
!_TAG_FILE_ENCODING utf-8   //
funnylengthword     dummy.txt   //
$ vim -u NONE
:tag funnylengthword
... endless loop
```

**Comment by ynkdir** [comment]
修正パッチ
https://gist.github.com/1250640

**Comment by ynkdir** [comment]
!_TAG_FILE_ENCODING の処理がもやっとするのでもう少し考えます。

タグ検索では検索パターンを &enc -> tag_file_encoding に文字コード変換して
検索中は tag_file_encoding のエンコーディングで比較してるけど
Vim の正規表現エンジンは &enc で動作するのでどうなのかと。
タグファイルの方を &enc に変換するほうがいいのではないかと。

**Comment by ynkdir** [comment]
やっぱり普通に動かなかった

```
$ cat tags
!_TAG_FILE_ENCODING cp932   //
あいうえお foo.txt /foo.txt
$ vim -u NONE
:tag /.いうえお
E426: tag not found: .いうえお
```

**Comment by h-east** [comment]
@ynkdir
「えっ！helptagsじゃない通常のtagsでも？」と思って試してみました。
タグファイルに「!_TAG_FILE_SORTED ～」の行がないと通常でも無限ループするようです。Vim 7.3.254 (Win64 +kaoriya)で確認。

<code>!_TAG_FILE_SORTED 1   //</code>

**Comment by ynkdir** [comment]
試したタグファイルを見せてもらってもいいですか。

**Comment by h-east** [comment]
https://gist.github.com/1256146
どちらももちろんcp932です。
「!_TAG_FILE_SORTED ～」の行を削除すると無限ループします。

**Comment by ynkdir** [comment]
ありがとうございます。
把握している症例なので大丈夫でした。

無限ループの条件はバイナリサーチ中に !_TAG_FILE_ENCODING 行を読み込む、なので
!_TAG_FILE_SORTED でなくても適当にタグ行を追加したり削除したりして調整すると無限ループになったりならなかったりすると思います。

**Comment by ynkdir** [comment]
無限ループの条件追加
!_TAG_FILE_ENCODING で指定されたエンコーディングが &enc と同じ、または対応してないエンコーディングである。

**Comment by mattn** [comment]
#60 も適当に織り交ぜちゃってもいいんじゃなかろうか

**Comment by ynkdir** [comment]
今のところ修正パッチの副作用として補完には出なくなります > #60
:tag !_TAG_FILE_FORMAT と明示的に指定すると引けます。エラーになりますが。
元の動作を変えないようにするべきか
:tag で not found になるようにするべきか
まぁ出ない方が自然ですかね

**Comment by mattn** [comment]
どう考えても出さない仕様にしてもおかしくないし、やろうと思えばすぐ出来るソースなのになんで出す仕様なんだろ。

**Comment by ynkdir** [comment]
vi 互換説

**Comment by thinca** [comment]
vi の頃から補完ってあるんでしたっけ。

**Comment by ynkdir** [comment]
補完はないですけど
:tag !_TAG_FILE_FORMAT
とかは普通にタグ引けるのでそれがそのまま補完機能に反映されているんだと思います。

**Comment by thinca** [comment]
ははぁ。
そうだったとして、それはviのバグと言えば通る気がしますね。

**Comment by ynkdir** [comment]
Proposal for extended Vi tags file format
http://ctags.sourceforge.net/FORMAT

```
TAG FILE INFORMATION:
...snip
The program reading the tags file should be smart enough to skip over these tags.
```

Bram さんの署名入り!

**Comment by mattn** [comment]
最近、僕の所でも頻繁に起きる様になりました。
今のステータスを確認したいのですが、!_TAG_XXX含むかどうかを決めかねている？
であれば、削除したpatchで出して駄目ならその部分カットで良いのでは。

**Comment by ynkdir** [comment]
gist の最新の版では !_TAG_XXX の動作は変わらないようにしてあります。

https://gist.github.com/1250640#L30

このへんのメモリ管理がなんかいけてないなぁと…。

あと最近は特にBramさんがいそがしそうなので
あんまりプレッシャーをかけるのもあれですし
自分的にももうちょっと間が欲しいかなという思いもあります。

まあでも困っているなら早めに投下してみます。

**Comment by ynkdir** [comment]
あとテスト書こうかなぁどうしようかなぁとか悩んでましたがそれはまあいいか。

**Comment by ynkdir** [comment]
```
tag.c:find_tags()
1363     pat_T       *pats;
1364     pat_T       orgpat;                 /* holds unconverted pattern info */
```

パターンをポインタで持ってマルチバイト動作と切り替えられるようにしてたりするコードももういらないけどほっといていいか…。

**Comment by ynkdir** [comment]
7.3.336 で修正されました。
気になってたところもしっかり清書されててさすが。
