### ISSUE TITLE
キーマッピングの2番目以降に来る <C-c> の挙動が変わる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#201]
例 (プレフィックズの z は何でも良い)

``` vim
nnoremap z<C-c> :echo 'key mapping works'<CR>
```

この状態で `z<C-c>` を押すと、`<C-c>` の動作("Vimを終了するには :quit<Enter> と入力してください" と表示される)になる。
続けて、

``` vim
nnoremap <C-c> <NOP>
```

のように `<C-c>` に適当に何かを割り当てて(`<NOP>` である必要はない) `z<C-c>` を押すと、

```
key mapping works
```

と表示される。
更に、

``` vim
nunmap <C-c>
```

としてキーマッピングを削除してから `z<C-c>` を押すと、

```
key mapping works
```

と表示される。
最初の動作がおかしいように思う。

**Comment by thinca** [comment]
挿入モードでも同じ感じの挙動になってます。他は試してない。

**Comment by k-takata** [comment]
おそらく 7.4.468 で挙動が変更され、アンマップ後は最初と同じ結果になるようになっています。関連 #606
閉じますか？

**Comment by koron** [comment]
@thinca 確認をお願いできますか?

**Comment by k-takata** [comment]
特に異論も無いようなので閉じます。
