### ISSUE TITLE
pirntf

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#202]
vim.po に typo。

これは @koron さんにお願いした方がいいかな？

``` diff

diff -r d915c19ad092 src/po/ja.po
--- a/src/po/ja.po  Fri May 18 21:54:13 2012 +0200
+++ b/src/po/ja.po  Wed May 23 18:19:40 2012 +0900
@@ -3910,7 +3910,7 @@
 msgstr "E807: printf() の引数には浮動少数が期待されています"

 msgid "E767: Too many arguments to printf()"
-msgstr "E767: pirntf() の引数が多過ぎます"
+msgstr "E767: printf() の引数が多過ぎます"

 msgid "W10: Warning: Changing a readonly file"
 msgstr "W10: 警告: 読込専用ファイルを変更します"
```

**Comment by koron** [comment]
ですね。

**Comment by k-takata** [comment]
https://gist.github.com/2819669
ja.poを7.3.524と比較すると、いくつか未訳の部分があったようなので、更新版を作ってみました。（Gistに貼っているため、文字コードがUTF-8になってしまっている点はご注意ください。）
- 未訳部分の翻訳
- pirntf -> printf
- 浮動**少**数 -> 浮動**小**数点数
- ～すぎる -> ～過ぎる に統一
- etc.

問題なければ一緒にマージをお願いします。

**Comment by mattn** [comment]
@k-takata ++

**Comment by koron** [comment]
今、その他とあわせてvim-devへ送るため準備中。

**Comment by mattn** [comment]
koron++

**Comment by koron** [comment]
ライセンスの件も合わせてやってしまおうと思うんだけど、僕が提供してたのってja.poとmenuファイル群だけで良いんだっけ?

# 人に聞くなって話ですがw

**Comment by koron** [comment]
送った。

パッチじゃなくてファイル丸々だけど。

**Comment by koron** [comment]
todoには入ってるはずなので閉じます。

**Comment by k-takata** [comment]
7.3.600直後のコミットで修正されていますので、タグを `fixed` に変えておきます。
http://code.google.com/p/vim/source/detail?r=11d40fc82f1154673baca2327796f5152b0df6f5
