### ISSUE TITLE
listcharsのprecedesを設定すると全角文字でカーソルがずれる

### ISSUE THREAD

**Issue by wiredool** [vim-jp/issues#203]
横にスクロールしprecedesが表示されるとカーソルが半分ずれるようです。
precedesの文字を変えてみても再現しました。

 gvim.exe -u NONE -N
 set nowrap
 set listchars=precedes:<
 i で インサートモードへ
 あああ…あ (横幅以上の全角文字を入力)
 横にスクロールするとカーソルがずれる

確認環境とは別のものですがこのような感じになります。
![](https://p.twimg.com/AuKJrocCIAEK4Kc.png)

確認した環境
WinXp 32bit
Win8CP 64bit
 kaoriya-20120519 GVim(7.3.524)

CentOS 6.2 Vim 7.2.411

**Comment by mattn** [comment]
デグってるw

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/3NmIRP5Qc1w/discussion

screen.c のコードを読むのがめんどくさくて投げたつもりでしたがマルチバイトでしか発生せず、結局自分でパッチを書くハメになってしまいました。

``` diff
diff -r 1c6b099ead89 src/screen.c
--- a/src/screen.c  Sun May 27 00:37:51 2012 +0200
+++ b/src/screen.c  Wed Jun 06 12:12:54 2012 +0900
@@ -4586,6 +4586,14 @@
        }
        else
        mb_utf8 = FALSE;    /* don't draw as UTF-8 */
+
+       if (has_mbyte && (*mb_ptr2cells)(ptr) > 1)
+       {
+       c_extra = '<';
+       n_extra = 1;
+       n_attr = 2;
+       extra_attr = hl_attr(HLF_AT);
+       }
 #endif
        if (!attr_pri)
        {
```

しばらく検証して大丈夫そうなら提出します。

**Comment by wiredool** [comment]
パッチ作成＆ご報告ありがとうございます。

CentOS上で試してたところ、まだズレてしまうことがありました。

vimrc適用時は改善しています。
set listchars=precedes:#
![](https://p.twimg.com/AutWE6xCAAA4k60.png)

こちらはズレてしまいます……
vim -u NONE -N
set nowrap
set list
set listchars=precedes:#
(set ruler)
![](https://p.twimg.com/AutXSZ-CEAEXa-1.png)

CentOS6.2
vim 7.3.540 / bash / gnome

テキストファイル
https://gist.github.com/2881794

**Comment by mattn** [comment]
うむ...再現しない...

**Comment by wiredool** [comment]
もう一度試そうとして、再現に失敗してしまいました…
 # と < が表示されているのでパッチ後のはずなのです。
もう少し調べてみます。

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun  6 2012 21:21:48)
Included patches: 1-540
Compiled by line@localhost.localdomain
Huge version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
+mouse_dec -mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse 
+mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg 
+path_extra -perl +persistent_undo +postscript +printer +profile -python 
-python3 +quickfix +reltime +rightleft -ruby +scrollbind +signs +smartindent 
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/home/line/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim       -lm -ltinfo -lnsl  -lselinux

**Comment by ynkdir** [comment]
おつかれさまです。

同じ症状を見てるかわかりませんが...

```
$ vim -u NONE -N
:set nowrap list listchars=precedes:#
:edit <上のテキストファイル>
```

で、zl でスクロールしていくと、3 行目の全角 A が左端に差し掛かったところでずれます。
"#<" と表示されるはずが "#" と表示されます。
その状態で 3 行目に挿入するとカーソルの表示位置とはずれた位置に挿入されます。

**Comment by ynkdir** [comment]
2 行目の半角 B が端にいったときも、"#" と表示されるはずが "#<" と表示されます。

**Comment by mattn** [comment]
これでどうでしょ？

 https://gist.github.com/2886056

``` diff
diff -r c384f4f5f238 src/screen.c
--- a/src/screen.c  Wed Jun 06 12:06:15 2012 +0200
+++ b/src/screen.c  Thu Jun 07 10:52:46 2012 +0900
@@ -4577,6 +4577,13 @@
        c = lcs_prec;
        lcs_prec_todo = NUL;
 #ifdef FEAT_MBYTE
+       if (has_mbyte && (*mb_char2cells)(mb_c) > 1)
+       {
+       c_extra = '<';
+       n_extra = 1;
+       n_attr = 2;
+       extra_attr = hl_attr(HLF_AT);
+       }
        mb_c = c;
        if (enc_utf8 && (*mb_char2len)(c) > 1)
        {
```

**Comment by mattn** [comment]
あまり遅らせてもまずそうなのでそろそろ↑出しますね。

**Comment by wiredool** [comment]
おつかれさまです。

vim 7.3.547 + 新しいパッチ にて表示の改善を確認しました。

**Comment by mattn** [comment]
あざます！

**Comment by ynkdir** [comment]
遅くなりましたが確認しましたokです。
ありがとうございます!

**Comment by mattn** [comment]
あざます！

**Comment by wiredool** [comment]
おつかれさまです。

https://groups.google.com/d/msg/vim_dev/OfwnFPEISis/p4wKJTvvC0AJ
vim7.3.553にて
precedesと全角文字が重なった際のカーソルのずれ
が改善されたことを確認しました。

ありがとうございます!
