### ISSUE TITLE
コマンドラインで日本語が化ける

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#204]
Cygwin 1.7.15, mintty 1.0.3, Vim 7.3.447
LANG=ja_JP.UTF-8

vim -N -u NONE でVimを起動し、`/スタート` と入力し、矢印キーでカーソルを以下のように動かすと文字化けします。

← を1回。`/スタート` と表示。文字化け無し。カーソルは`ト`の位置。
← をもう1回。`/スター<e3>` と文字化け。カーソルは`ー`の位置。
← をもう1回。`/スタ<e3>3>` と文字化け。カーソルは`タ`の位置。

UTF-8で片仮名の最初のバイトがe3なので、それが表示されているようですが。
何か文字を入力すれば文字化けから回復します。

**Comment by koron** [comment]
`:set enc? tenc?` の結果を書いてください。

**Comment by koron** [comment]
あとは…minttyのバグ、という考え方もありか。

**Comment by k-takata** [comment]
```
  encoding=utf-8
  termencoding=
```

です。
minttyの代わりに、Tera Term 4.74を入れて、cyglaunchから起動しても同じでした。

**Comment by ynkdir** [comment]
再現方法

```
$ vim -u NONE -N
:cnoremap aa <Nop>
:cnoremap ab <Nop>
:SOME_MULTI_BYTE_CHARACTER       " type multi-byte character

そして、<Left> でカーソルを移動して "aa" を入力。
マルチバイト文字の最初のバイトが `<xx>` 形式で表示される。
```

cygwin 以外でもでます。
マップされた文字を入力しているときに Vim は入力途中の文字を表示してくれますが (getchar.c:2741あたり)、
それを元に戻す処理がマルチバイトってませんでした。
cygwin + mintty だと `<Left>` やその他ファンクションキーのキーシーケンス入力で小さい待ちが発生してました。
cygwin環境てきななにかでたまたまカーソルキーで症状がでたんですかね。

``` diff
diff -r 9cb3a75a20b9 src/ex_getln.c
--- a/src/ex_getln.c    Fri Jun 01 22:38:45 2012 +0200
+++ b/src/ex_getln.c    Tue Jun 05 21:01:38 2012 +0900
@@ -2764,6 +2764,11 @@
     msg_no_more = TRUE;
     if (ccline.cmdlen == ccline.cmdpos)
    msg_putchar(' ');
+#ifdef FEAT_MBYTE
+    else if (has_mbyte)
+   draw_cmdline(ccline.cmdpos,
+               (*mb_ptr2len)(ccline.cmdbuff + ccline.cmdpos));
+#endif
     else
    draw_cmdline(ccline.cmdpos, 1);
     msg_no_more = FALSE;
```

投げます。

**Comment by k-takata** [comment]
7.3.538に上記のパッチを当てて直るのが確認できました。

**Comment by mattn** [comment]
ynkdir++

**Comment by mattn** [comment]
7.3.539で入りました。

https://groups.google.com/d/topic/vim_dev/W36gV8pNqzI/discussion

**Comment by h-east** [comment]
ynkdir△!
