### ISSUE TITLE
MSVCなvimで入力した日本語が化ける

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#205]
kaoriya版のvimで `set enc=utf-8 tenc=cp932` の環境で確認。
Google IME

メッセージなど表示する文字は正しいが、IMEで入力した文字は化ける。
tencでコンバートするタイミングがないのかな?

**Comment by mattn** [comment]
vim.exe ?

**Comment by koron** [comment]
Yes. vim.exe

**Comment by koron** [comment]
ちなみにOSはWindows7とWindows Server 2008R2ってもうここまでくるとまず関係ないよね。

**Comment by mattn** [comment]
化けるというか入力出来ないっす。 #MSIME

**Comment by mattn** [comment]
#189 とは違う？

**Comment by koron** [comment]
@mattn さーせんwww まったく同じ事、自分で2回報告するってどういうことだよw
