### ISSUE TITLE
:write >>でファイルを追記するとき追記元と追記先のエンコーディングが異なると日本語(2バイト文字)が文字化けする

### ISSUE THREAD

**Issue by LeafCage** [vim-jp/issues#206]
:edit ++enc=utf-8 file1
適当にバッファに入力
:w
:edit ++enc=cp932 file2
何か日本語(2バイト文字)をバッファに入力
:w >> file1

結果→文字化け

**Comment by mattn** [comment]
`>>` で出力されるファイルがバイナリって事も考えられるのであえてやらないのかも。
バグというよりfeature requestな感じがします。

**Comment by koron** [comment]
`>>` の追記先を一旦読み込んでエンコード判定する、ってことならできるけど、それだとなんだか `>>` のメリットが失われますよねぇ。速度とか意味合いとか。

使い勝手としては `>>` 出力時のエンコードをカレントバッファの `fenc` に依存しないようにするだけでも良いのかなぁ

**Comment by mattn** [comment]
モダンな書き方ならば

``` vim
call writefile(readfile("foo.txt")+readfile("bar.txt"), "foo.txt")
```

で行けるかなーと思います。カレントバッファを追記したいなら

``` vim
call writefile(readfile("foo.txt")+getline(1, '$'), "foo.txt")
```

でしょうか。試してないので分かりませんが。

**Comment by thinca** [comment]
これってつまりエンコーディングが混ざったファイルができるってことですよね。
`:w` が現在のバッファの内容をファイルに追記するにあたって、現在のバッファのエンコーディングで書きだすのは自然かと思います。
書き込み先のファイルのエンコーディングがわかっているならば、`:w ++enc=utf-8 >>file1` で良い気がします。

**Comment by mattn** [comment]
たぶんこれはfeature requestにしたところで取り込まれません。
@LeafCage 閉じて良いですか？

**Comment by mattn** [comment]
@LeafCage 閉じますね。問題あったら新規にissue立てて下さい。
