### ISSUE TITLE
vim-cpp を提案する上での配布形態について

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#209]
vim-jp/issues#69 を vim_dev に push したい。

https://groups.google.com/d/topic/vim_dev/ug_wmWQqyGU/discussion

そこで github.com/vim-jp でホストしたいのだけど、どの様に配布するか。
1. vim のリポジトリごとホストしてブランチとして提供する。
2. 必要なファイルを単体で runtime 形式で提供する。

2の場合、リポジトリ名案も希望。

**Comment by koron** [comment]
私は案2。名称は cpp-vim か c-vim で良いんじゃなかろうか。

```
選ばれたのは綾鷹でした。
```

**Comment by mattn** [comment]
```
+- runtime
  |
  +- syntax
       c.vim
       cpp.vim
```

にするか

```
+- syntax
  c.vim
  cpp.vim
```

にするかというのもあるかな。上書きする syntax ではないし...

**Comment by koron** [comment]
仮に本体に取り込まれなくてもプラグインとして成立するようにする、
には後者のほうが正しくないかな?
docとかもろもろあると良いだろうし。

**Comment by mattn** [comment]
いれた

https://github.com/vim-jp/cpp-vim

**Comment by mattn** [comment]
だした

https://groups.google.com/d/msg/vim_dev/ug_wmWQqyGU/XfdJHt5d26IJ

**Comment by koron** [comment]
@mattn ++

**Comment by mattn** [comment]
ひとまず問題では無くなったので閉じます。
