### ISSUE TITLE
:help modelineが間違っている？

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#21]
これは、ichimalさんからの情報です。

:help modelineを見ると、

モードラインには2つの形式がある。1つ目の形式は次の通りである。
    [text]{white}{vi:|vim:|ex:}[white]{options}

[text]      任意のテキスト、なくても良い
{white}     1個以上の余白 (<Space> または <Tab>)
{vi:|vim:|ex:}  "vi:" か "vim:" か "ex:" という文字列
[white]     空白、なくても良い
{options}   オプション設定が、空白か ':' で区切られて並んだもので、':' の
        間の部分はコマンド ":set" の引数である(空でもよい)

となっていて、Vimテクニックバイブルもそれに基づいて記述されていたのですが、

http://twitter.com/#!/ichimal/status/114958995814494209
「だとすればそのhelpは間違っていますね。{text}省略時に{white}は省略可能なはずです。well known problem であるならば issue 発行してはいかがでしょう?」

という指摘を受けました。ちょっと私はmodelineに詳しくないのですが、:helpが間違っているということなのでしょうか。

**Comment by h-east** [comment]
help@enが間違ってるみたいです。

help@en
        [text]{white}{vi:|vim:|ex:}[white]{options}
[text]      any text or empty
...

修正案(というかichimalさんの指摘そのまま^^; http://twitter.com/#!/ichimal/status/114924189470826496)
        [{text}{white}]{vi:|vim:|ex:}[white]{options}
{text}      any text or empty
...

vim_devへ報告が必要です。
ynkdirさん＞
お願いしちゃっていいでしょうか？

**Comment by ynkdir** [comment]
そのちょっと下

The white space before {vi:|vim:|ex:} is required.  This minimizes the chance
that a normal word like "lex:" is caught.  There is one exception: "vi:" and
"vim:" can also be at the start of the line (for compatibility with version
3.0).  Using "ex:" at the start of the line will be ignored (this could be
short for "example:").

white が省略可能なのは互換性のための例外ということなので微妙な気がします。
ex: のときは省略できませんしね。

**Comment by ynkdir** [comment]
文章で保管してるのがいかんということなのかな

**Comment by Shougo** [comment]
ああ、その仕様は互換性のためだったんですね。だとすると、どうするべきか……。

**Comment by ynkdir** [comment]
vim_dev での議論

Subject: Modelines: First Form
http://thread.gmane.org/gmane.editors.vim.devel/15912

**Comment by h-east** [comment]
なるほどです。
「example:」の略として「ex:」が使われるかもしれないから行頭から始まる ex: は無視するよ　ってことですか。深い。
vi:|vim:|ex: で一緒くたに説明してて下の方にそんな事書いてあるとか。。「引っ掛け問題か！」って感じな気もしますｗ

もし、変えるなら...
↓は既存のままで{white}の説明にちょっと追記するとかでしょうか。
[text]{white}{vi:|vim:|ex:}[white]{options}
{white}の説明に 「[text]を省略して、かつ vi: か vim: を使うのなら{white}は省略できる。」を追記。

**Comment by Shougo** [comment]
ふむふむ。そうですね。ちょっとだけ変更するのが良さそうです。
英語ヘルプも修正するべきですかね。

**Comment by ynkdir** [comment]
私の英語力&コミュニケーション力だと明らかな間違いを指摘するのがせいいっぱいでして…

**Comment by Shougo** [comment]
きっと他の方がなんとかしてくれるはず（他力本願）

**Comment by thinca** [comment]
これ、とりあえず日本語版だけでも訳注入れておきます?

**Comment by thinca** [comment]
``` diff
diff --git a/doc/options.jax b/doc/options.jax
index 2234127..887e078 100644
--- a/doc/options.jax
+++ b/doc/options.jax
@@ -514,6 +514,7 @@ Note 展開されるオプションの値の長さ制限に注意。システム

                                        *modeline* *vim:* *vi:* *ex:* *E520*
 モードラインには2つの形式がある。1つ目の形式は次の通りである。
+{訳注: 例外あり。後の説明を参照}
        [text]{white}{vi:|vim:|ex:}[white]{options}

 [text]         任意のテキスト、なくても良い
```

こんな感じ?

**Comment by mattn** [comment]
オフィシャルから変えるべきかと。

**Comment by thinca** [comment]
むぅ。まあそうですよね…。

**Comment by koron** [comment]
修正そのものは簡単だが、vim-devにおいて説明する英語力の不足が理由で、修正がなされていない。
また内容も「書いてあるがやや不親切。それを少し親切になるように正す」程度であるので
まったくクリティカルではない。

なので backlog へ送ります。
