### ISSUE TITLE
linuxでのmake testがパスしない

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#214]
7.3.530以降のどこかで、fedora15でのmake testがパスしなくなっています。

PuTTYからremote login

``` sh
$ hg clone https://vim.googlecode.com/hg/ vim
$ cd vim
$ ./configure --enable-multibyte --with-features=big
$ make
$ make test
```

```
E233: ディスプレイを開けませんmake[2]: [test16.out] エラー 1 (無視されました)

Test results:
test16 NO OUTPUT
TEST FAILURE
make[2]: *** [report] エラー 1
make[2]: ディレクトリ `/home/h_east/samba/Mercurial/vim/src/testdir' から出ます
make[1]: *** [test] エラー 2
make[1]: ディレクトリ `/home/h_east/samba/Mercurial/vim/src' から出ます
make: *** [test] エラー 2
```

※test16はGUIのテストです。CUIのconfigureなのになぜ実行される？？

補足情報

``` sh
$ uname -a
Linux todoroki 2.6.43.5-2.fc15.x86_64 #1 SMP Tue May 8 11:09:22 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ src/vim --version | head -2
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 21 2012 23:01:47)
適用済パッチ: 1-566
```

7.3.529 でmake testがALL DONEになるのは確認しています。
特に調査とかしてません。
とりあえず報告。

**Comment by wiredool** [comment]
PuTTY で入った AzureのCent62 と
ローカルVMのXのGNOME Terminalではtestパスを確認しました。

``` bash
$ cat /etc/redhat-release
CentOS release 6.2 (Final)

$ uname -a
Linux azcent62vm-v4 2.6.32-220.17.1.el6.x86_64 #1 SMP Wed May 16 00:01:37 BST 2012 x86_64 x86_64 x86_64 GNU/Linux

$ src/vim --version | head -2
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 21 2012 16:49:59)
Included patches: 1-566
```

どちらもuname同じでした…

**Comment by mattn** [comment]
@wiredool 

```
% echo $DISPLAY
```

してもらえますか？puttyでX転送してそうな気がします。

**Comment by wiredool** [comment]
了解です。
後ほど確認してお知らせします。

**Comment by wiredool** [comment]
Azureの方は $DISPLAY が空でした。

``` bash
$ echo $DISPLAY 

```

(以下はおかしなことをしているかもしれません)
また、ローカルの方で

``` bash
cd vimのhgディレクトリ
make clean
make distclean

sudo shutdown now
cd vimのhgディレクトリ
./configure --enable-multibyte --with-features=big
make
make test
```

を行ったところ、最初のテストで通りませんでした。
https://gist.github.com/2972577

その後にXをうごかしてテストすると全て通りました。

``` bash
init 5
cd vimのhgディレクトリ
make test
```

**Comment by h-east** [comment]
あれ？？
`--disable-gui` を付けて ./configure したらmake testをPASSしました。(7.3.566でもOK)
今まで `--disable-gui` 指定したことないんだけどなぁ。
時間のある時に変化点探してみます。

**Comment by h-east** [comment]
うーん。wiredool さんのはよくわかんない。仮想環境とはいえ shutdown now したらshutdownしちゃうんじゃないのかな(_´ω｀_)

**Comment by wiredool** [comment]
`shutdown`後にtestがうまくいかない原因は分かりました。
$HOME がみつからず、.viminfo の書き込みに失敗していたようです。

CentOSでは `-p` などを付けずに `shutdown` を実行するとシングルユーザモードに、
`init 5` を実行するとran level 5 になり、Xやその他いろいろが止まったり走ったりします(するつもりでいます)。

シングルユーザに移行した際に $HOME が消えているのが問題で、存在すれば空でも良いらしく、

``` bash
export HOME=
```

で、テストがすべて通りました。

---

$HOME が無い状態で vim でファイルを開いたときのエラー

```
Vim: Caught deadly signal SEGV
E138: Can`t write viminfo file $HOME/.viminfo!Vim: Finished.
```

**Comment by h-east** [comment]
変化点は7.3.530。この修正が入るとtest16の挙動が変わる。

チェンジセット:   3539:81d5f3a3e27f
タグ:             v7-3-530

``` diff
diff -r 57b2fe37fd5b -r 81d5f3a3e27f src/gui.c
--- a/src/gui.c Fri May 25 13:12:37 2012 +0200
+++ b/src/gui.c Fri May 25 14:06:36 2012 +0200
@@ -102,6 +102,10 @@
     else
 #endif
     {
+   /* If there is 'f' in 'guioptions' and specify -g argument,
+    * gui_mch_init_check() was not called yet.  */
+   if (gui_mch_init_check() != OK)
+       exit(1);
    gui_attempt_start();
     }
```

もともと ./configure には `--with-gnome` を指定してた。(指定しなくってもenable GUI になる)
なので GUIテストのtest16が実行されるのは問題じゃない。
enable GUIでconfigureしたものをCUI環境(PuTTY)でmake testした場合の挙動が7.3.530で変わった。
(厳密には `:gui -f` した場合の挙動が変わった)

7.3.529でtest実施した場合。(test16でE233出るけどそれは無視してALL DONE)

``` bash
$ hg update -r 3538
$ make distclean
$ ./configure --enable-multibyte --with-gnome --with-features=big
$ make
$ make test
(省略)
cp test16.ok test.ok
# Sleep a moment to avoid that the xterm title is messed up
../vim -u unix.vim -U NONE --noplugin -s dotest.in test16.in
E233: ディスプレイを開けません
Test results:
ALL DONE
```

7.3.530でtest実施した場合。(test16でE233出てそれをfail扱いしてTEST FAILURE)

``` bash
$ hg update -r 3539
$ make distclean
$ ./configure --enable-multibyte --with-gnome --with-features=big
$ make
$ make test
(省略)
E233: ディスプレイを開けませんmake[1]: [test16.out] エラー 1 (無視されました)

Test results:
test16 NO OUTPUT
TEST FAILURE
```

src/testdir/test16.in の9行目の `:gui -f` が肝。

test16の冒頭でguiがrunningじゃなかったらtestをすっ飛ばせば良い気がする。

**Comment by h-east** [comment]
その前に、`:gui -f` してディスプレイを開けないからといって
E233出して突然死するのはよろしくないですね。

**Comment by h-east** [comment]
Patch 7.3.687 で改善された模様。
https://groups.google.com/d/topic/vim_dev/FZbJzH_9PgA/discussion

$DISPLAY が設定されていない時はtest16をしないようにするpatch。

**Comment by h-east** [comment]
PuTTY上でテスト結果 `ALL DONE` が確認出来たので閉じます。
