### ISSUE TITLE
ATOKとの組み合わせで未確定文字が不可視色になる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#215]
> kaoriya vimでatokの変換前入力文字が白文字・白背景で見えなくなったのだが，なんか要らん設定してもうたか？ ([出典元](https://twitter.com/masanobuimai/status/219613275191644161))

私はATOKもってないので未確認。IMEの設定とカラースキームがバッティングしている可能性あり。

懸念事項は「最近の変更でIME側の設定(色設定など)を使うようになったのではなかろうか? その際、使い方を間違っているのではないだろうか?」という点。

直感的にはユーザ個別の事例になると推測されるので、だれか試してみて問題ないとわかった時点でworksformeで閉じて、記録に残すことになると考えています。

**Comment by Shougo** [comment]
ATOKは体験版があったと思います。できれば、ATOKのバージョンや設定も知りたいところですが……。

http://www.atok.com/try/

私は一応ATOKを持っていますので（ただし ATOK 2008）、私の環境で試すことは可能です。

**Comment by mattn** [comment]
WindowsのIME APIには色を設定出来るAPIはありません。
IMEがやれるとすれば、ウィンドウの現在のデバイスコンテキストから情報を得るだけです。
情報を得るには

GetObject
http://msdn.microsoft.com/ja-jp/library/cc410355

を使い、最終で SelectObject したペンもしくはブラシを得ます。この値を使って、IMEの候補ウィンドウの色を設定しているはずです。この辺の挙動について最近(数年) vim 側で修正した事はないし、昔ATOK使ってた時にもこんな事になった事は無かった。
あるとすればATOKのバグかなーとは思いますが。

可能性があるとすれば

https://groups.google.com/d/topic/vim_dev/2I-2UaknBW4/discussion

これかもしれない。

**Comment by mattn** [comment]
特に DefWindowProc に渡さず return 1L してるあたりは非常に怪しい。

**Comment by ynkdir** [comment]
同じかわかりませんが

Microsoft Office 2003 SP3を導入すると、入力した文字が見えなくなったり、黒く反転して表示される
http://support.justsystems.com/faq/1032/app/servlet/qadoc?QID=035938

**Comment by koron** [comment]
現在 [確認中](https://twitter.com/kaoriya/status/229565980119011329)

これで解決するなら won't fix で閉じちゃおう。

**Comment by mattn** [comment]
# まさかの長期休暇

**Comment by koron** [comment]
> IMEとは関係なく、gdippの問題でした。gvim.exeをgdippの対象外にする事で問題は解消しました。 [masanobuimai](https://twitter.com/masanobuimai/status/233033588235444226)

なんにせよ解決してよかった。
