### ISSUE TITLE
inoremap 、 , が効かない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#217]
https://twitter.com/sifikinoko/statuses/220414870544330752

この辺りから in-reply-to でさかのぼってもらえればストーリーは見えます。

```
inoremap 、 ,
```

を書いた vimrc (scriptencoding utf8) でタイプしてもダメ。

```
vim -u NONE -N
:inoremap 、 ,
```

でもダメ。

vimのversionは7.3でpatchが1-429まで適応済み
(ubuntuのpackageのもの)
ubuntu 12.04 uim-skk

**Comment by ynkdir** [comment]
ちょっと調べてお手上げだった記憶が…

```
todo.txt:
UTF-8: mapping a multi-byte key where the second byte is 0x80 doesn't appear
to work. (Tony Mechelynck, 2007 March 2)
```

**Comment by mattn** [comment]
windowsなら動くのに...

**Comment by ynkdir** [comment]
windowsでもenc=utf-8だと動かないです

**Comment by mattn** [comment]
oh...

**Comment by mattn** [comment]
K_SPECIAL あたりとかぶるんかな...

**Comment by mattn** [comment]
なんかビンゴっぽいな。

**Comment by ghost** [comment]
これでいいのかな…

``` diff
diff -r e91143b9ad7a src/getchar.c
--- a/src/getchar.c     Wed Feb 05 22:46:52 2014 +0100
+++ b/src/getchar.c     Mon Feb 10 01:51:44 2014 +0900
@@ -2167,7 +2167,7 @@
                                 * multi-byte char.  Happens when mapping
                                 * <M-a> and then changing 'encoding'. */
                                if (has_mbyte && MB_BYTE2LEN(c1)
-                                                 > (*mb_ptr2len)(mp->m_keys))
+                                                 > (int)STRLEN(mp->m_keys))
                                    mlen = 0;
 #endif
                                /*
```

**Comment by ynkdir** [comment]
:inoremap 、 xxx としたとき、
U+3001 = E3 80 81 これの 2 番目のバイト 80 がエスケープされて
mp->m_keys = E3 80 FE 58 81
という形で保存される。
それが utf-8 的に不正なバイト列なので mb_ptr2len(mp->m_keys) が 1 を返す。
ということなので、一時的に 80 FE 58 を 80 に元に戻すのがいい気がします。

個人的にはそこの ifdef 自体いらないと思いますが、まあ通らないでしょうねえ…。

あとなにかあったかな。あんまり覚えてません…。

**Comment by ghost** [comment]
ありものは使おうの方針で…

``` diff
diff -r e91143b9ad7a src/getchar.c
--- a/src/getchar.c     Wed Feb 05 22:46:52 2014 +0100
+++ b/src/getchar.c     Tue Feb 11 00:50:40 2014 +0900
@@ -2166,9 +2166,14 @@
                                /* Don't allow mapping the first byte(s) of a
                                 * multi-byte char.  Happens when mapping
                                 * <M-a> and then changing 'encoding'. */
-                               if (has_mbyte && MB_BYTE2LEN(c1)
-                                                 > (*mb_ptr2len)(mp->m_keys))
-                                   mlen = 0;
+                                {
+                                    char_u  *p;
+                                    p = mp->m_keys;
+                                    p = mb_unescape(&p);
+                                    if (has_mbyte && p != NULL &&
+                                          MB_BYTE2LEN(c1) > (*mb_ptr2len)(p))
+                                        mlen = 0;
+                                }
 #endif
                                /*
                                 * Check an entry whether it matches.
```

**Comment by ynkdir** [comment]
ありがとうございます。よさそうですね。

**Comment by ghost** [comment]
vim_dev に持ち出しました。また別の TODO がある気がしないでもなく…。

https://groups.google.com/forum/#!topic/vim_dev/NRxhBh_t8mc

**Comment by k-takata** [comment]
> また別の TODO がある気がしないでもなく…。

[上で](https://github.com/vim-jp/issues/issues/217#issuecomment-6757185) @ynkdir さんが書いています…。これに対する修正だと書いておいた方がよいでしょう。

**Comment by ghost** [comment]
これのテスト書けますか？的な話になってる気がすごくするのです。
書く技術を今は持っていないし、学んだとしても素人の域は出ようがないので、詰んだ？かな…

**Comment by ynkdir** [comment]
テストは vim/src/testdir を見ればなんとなくわかると思います。

**Comment by k-takata** [comment]
テストの書き方のページはまだ作りかけでしたっけ？
https://github.com/vim-jp/vim-jp.github.com/issues/16
http://vim-jp.org/docs/how_to_write_tests.html

**Comment by h-east** [comment]
@k-takata あぅ、結局書いてないですね。

**Comment by ghost** [comment]
20年前にコードを書く仕事をしていた時に発症した統合失調症が一気に悪化しまして、やはり無理だったかと思っているところです。結構治ってきたと判断してパッチに手を出しましたが、間違いでした。平たく言えば頭がおかしいので、ぶつかる前に引っ込みます。そういう思考が出る程度にはおかしくなっているということです。申し訳ありません。

**Comment by mattn** [comment]
今見たら map や abbr のテストって無いすね。

**Comment by ynkdir** [comment]
@ntak
いえいえ助かりました。

**Comment by mattn** [comment]
@ntak ちなみに、vim-jp ではパッチ書いたら書きっぱなし、投げっぱなしでもokです。誰か暇が出来たらテスト書いてくれたりしますんでテキトーにやって下さい。

**Comment by ghost** [comment]
急性症状(幻聴)がおおむね回復した後によくよく考えたのですけれども、自分潰してもパッチ潰すな、という自己反省に至ったので、このパッチとテストは書き上げます。自分のケツは持たないといかんですね。飛ばしすぎたのが原因なように今は思います。
とここまで書いてまた幻聴出てきてますな(;´Д`)テキトー精神を獲得せねば…

しかしながら文字のテストって全文字噛ますわけにもいかないし…(今はまだ他のテストは未見)

**Comment by ghost** [comment]
ちょっと時間を食いましたがテスト方法とVim scriptは把握しました。
そこまではよかった…
script に書いた "string" が latin-1 かなんかで変解釈されるのが現在の動作ですが(例:"call feedkeys("、") が通らない)、これは変えてしまったら影響が半端ない気がかなりするんで、どうしたもんかと思ってるところで今日に至っております。
テストに feedkeys() を使ってる時典でいかんのかもわからんですけれど、うーん…

**Comment by mattn** [comment]
`scriptencoding utf-8` というのをテストスクリプトの先頭に入れて貰えますか？

**Comment by ghost** [comment]
まずもって最小限で再現するのはこうです。

```
scriptencoding utf-8
STARTTEST
:scriptencoding utf-8
:so small.vim
:so mbyte.vim
:set encoding=utf-8
ggdG
:inoremap 、 ，
:call feedkeys("i、\<Esc>")
:wq! test.out
ENDTEST
```

謎でもなんでもないのかもしれない(evalの付近でmb_系処理が見つけられなかった)。

**Comment by k-takata** [comment]
`:scriptencoding utf-8` は `:set encoding=utf-8` より後にすべきではないでしょうか。（ただ、他のテストは scriptencoding を設定していないですね。例: test95）
`STARTTEST`の前と、`ENDTEST`の後には空行が必要だったような気がします。
で、以上の変更を行った上で試してみたのですが、なぜかうまくいかないですね。
vimを立ち上げて、手で`:inoremap`と`feedkeys()`を実行した場合や、

```
:inoremap あ い
:call feedkeys("iあ\<Esc>")
```

に変えた場合はうまくいくのですが。

**Comment by ghost** [comment]
原因である `K_SPECIAL` 系を escape/unescape する処理をこことあそこに入れてやろうか`Hehehehe.`という状況まで持っていきましたが副作用が心配であること山の如し、`eval[0-7]()` に渡っている `arg` のバイト列からしてなんらかの encode がかかっているのでそこを見て latin-? かなと思った次第です。
よくわかりませんが私もどう説明していいやらまとまってません。追って一報します。

**Comment by ynkdir** [comment]
入力は `:so!` で読み込まれるので 0x80 バイトはエスケープしないといけなかった気がします。
なので `i^Vu3001` (^V は `<C-V><C-V>` で入力した生 CTRL-V) で入力するのがよさげと思います。

**Comment by ghost** [comment]
`:so!` は変えたらいかんですね…
どうも見当が外れていたようでつらみ(;´Д`)皆様いろいろすみません。
数日中に持ち出せる形を作ります。

**Comment by k-takata** [comment]
`i^Vu3001` を試してみましたが、`，`にはなりませんでした。inoremapのマッピング適用対象外ということでしょうか。

**Comment by ynkdir** [comment]
あーほんとですね。すいません。勘違いでした。

**Comment by k-takata** [comment]
これでどうでしょう。

```
Tests for key mapping.

STARTTEST
:so small.vim
:so mbyte.vim
:set nocompatible encoding=utf-8
ggdG
:inoremap <Char-0x3001> <Char-0xff0c>
:call feedkeys("i\u3001\<Esc>")
:wq! test.out
ENDTEST

```

マッピング関連のテストを充実させていくのは、今後の課題となりますかね。
しかし、

> 入力は `:so!` で読み込まれるので 0x80 バイトはエスケープしないといけなかった気がします。

ヘルプを見てみましたが、書いてなさそう…

**Comment by ynkdir** [comment]
よさげですね。

**Comment by k-takata** [comment]
なお、`:call feedkeys("i\u3001\<Esc>")` の代わりに、

```
:let @a="i\u3001\x1b"
@a
```

というのも考えましたが、分かりにくいのでボツ。

あと、念のため既存のマッピング関連のテストを検索したところ、test 15, 34, 75, 88, 94 辺りが見つかりました。しかし、今回の件は enc=utf-8 が必須なので、既存のテストファイルに追加するよりは新規のテストファイルを作った方が良さそうですね。

**Comment by ynkdir** [comment]
コメントがあったほうがいいかもですね。

**Comment by ghost** [comment]
script の場合だけエスケープしないようにわざわざ条件切りしてあったのが実態でした。

``` diff
diff -r 10d35c8b50e3 src/getchar.c
--- a/src/getchar.c Mon Feb 24 03:32:00 2014 +0100
+++ b/src/getchar.c Fri Feb 28 19:53:54 2014 +0900
@@ -2207,9 +2207,13 @@
                /* Don't allow mapping the first byte(s) of a
                 * multi-byte char.  Happens when mapping
                 * <M-a> and then changing 'encoding'. */
-               if (has_mbyte && MB_BYTE2LEN(c1)
-                         > (*mb_ptr2len)(mp->m_keys))
-                   mlen = 0;
+                                {
+                                    char_u *p1 = mp->m_keys;
+                                    char_u *p2 = mb_unescape(&p1);
+                                    if (has_mbyte && p2 != NULL &&
+                     MB_BYTE2LEN(c1) > MB_PTR2LEN(p2))
+                                        mlen = 0;
+                                }
 #endif
                /*
                 * Check an entry whether it matches.
@@ -3133,7 +3137,7 @@
    }
    else
 #endif
-   if (p[0] == NUL || (p[0] == K_SPECIAL && !script
+   if (p[0] == NUL || (p[0] == K_SPECIAL
 #ifdef FEAT_AUTOCMD
            /* timeout may generate K_CURSORHOLD */
            && (i < 2 || p[1] != KS_EXTRA || p[2] != (int)KE_CURSORHOLD)
```

これでテストファイルが動きます。貼れないですね(;´Д`)コードが化ける。
http://ntak.net/vim/test106.zip (test106.in, test106.ok)
で通ります。がテストのためにコードを変えるというのが許されるのか否か…。

**Comment by k-takata** [comment]
> がテストのためにコードを変えるというのが許されるのか否か…。

無しに1票。上に書いたとおり、`<Char-0xXXXX>`と`"\uXXXX"`を使えば動くわけですから。
本当に必要であれば、別パッチにした方が良いのではないでしょうか。

**Comment by ynkdir** [comment]
`:so!` の件はバグというわけではなくて、起動引数の `-w {scriptout}` で記録したスクリプトを `:so!` で実行するんですが、ファンクションキーなんかもそれで記録&再生できるようにそんな感じになってます。

**Comment by k-takata** [comment]
なるほど、そういう目的でしたか。

**Comment by ghost** [comment]
`nocompatible` と `<Char-0xXXXX>` を知らなかったという部分が弱いのでやはりマニュアルには一度目を通した方がいいですねこれは。今後のために…。
`!script` の方は出すにしても別パッチにします。出さない気はしてます。
テストはこちらで仕上げてここで突っ込み入れて頂いた後 vim_dev に持ち出す形でいいでしょうか？

**Comment by ynkdir** [comment]
はい

**Comment by ghost** [comment]
こうなりました。

```
Test for utf8 character map.

STARTTEST
:so small.vim
:if !has("multi_byte")
: e! test.ok
: w! test.out
: qa!
:endif
:so mbyte.vim
:set nocompatible
:set encoding=utf8
ggdG
:" Outside of the range, minimum
:inoremap <Char-0x1040> a
:call feedkeys("i\u1040\<Esc>")
:" Inside of the range, minimum
:inoremap <Char-0x103f> b
:call feedkeys("i\u103f\<Esc>")
:" Inside of the range, maximum
:inoremap <Char-0xf03f> c
:call feedkeys("i\uf03f\<Esc>")
:" Outside of the range, maximum
:inoremap <Char-0xf040> d
:call feedkeys("i\uf040\<Esc>")
:wq! test.out
ENDTEST

```

値域の縁を内外四点分見ています。test*.ok は

```
dcba
```

になります。

**Comment by ynkdir** [comment]
ありがとうございます。いいと思います。

**Comment by ynkdir** [comment]
あ、これいらないですね。マルチバイトなしなら `:so mbyte.vim` が同じことするはずです。

``` vim
:if !has("multi_byte")
: e! test.ok
: w! test.out
: qa!
:endif
```

**Comment by ghost** [comment]
了解しました。その部分を削って提出します。ヽ(´ー`)ノ

**Comment by k-takata** [comment]
コメント部分ですが、

> Test for utf8 character map.

Tests の方が良いかと。

> :" Outside of the range, minimum

the range というのが何の範囲か説明があった方が良いかも。

**Comment by ghost** [comment]
はい(;´Д`)英語～…以前の問題なので変更します。

**Comment by k-takata** [comment]
7.4.204
https://groups.google.com/d/topic/vim_dev/MiQ7PfCcVy8/discussion
テストは、test75への追加という形になりました。

**Comment by mattn** [comment]
@ntak congrats

**Comment by ghost** [comment]
ヽ(´ー｀)ノ

**Comment by k-takata** [comment]
7.4.433 でテストの feedkeys() が :normal に置き換えられてますけど、何でだろう？
https://groups.google.com/d/topic/vim_dev/noU8v5mUuSA/discussion
