### ISSUE TITLE
矩形選択を使用して複数の行に文字を入力した場合のインデントと入力される文字の挙動について

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/issues#221]
仕様なのか、不具合なのか分からなかったので質問します。
## 現象

矩形選択で文字列の前に複数行に文字を入力した際に、意図しない所に文字が入力される

以下の vimrc で発生しました。

``` viml
autocmd!
set nocompatible
syntax enable
filetype plugin indent on
set backspace=indent,eol,start
```
## 再現方法
- 上記の vimrc を利用して vim を起動する
  vim -u ~/.vimrc_simple samle.py
- 以下を入力する

``` python
params = {#ここで改行を入力
                }#自動でインデントが効く
```
- `}` のインデントの位置を変更する

``` python
params = {
}#バックスペース 2 回押して行頭に移動させる
```
- `}`の位置で `<S-o>` を入力して `{}` の間に移動し入力モードに

``` python
params = {
                'foo': 'fooo',
}
```
- `foo` の位置が気に入らないので、`foo` の前にカーソルを持ってきて入力モードで `<BS>` を入力しインデントを戻す

``` python
params = {
        'foo': 'fooo',
}
```
- `<o>` を入力して `foo` の次の行に移動し入力モードになり、`'bar': 'barr'` を入力

`````` python
params = {
        'foo': 'fooo',
        'bar': 'barr'
}

- `fo|oo` | の位置にカーソルを移動し、`<C-v>j<S-i>:` を入力
```python
params = {
        'foo': 'fo|oo',
        'bar': 'barr'
}
``````
- `:` を入力した際に `'foo': 'fo:oo',` が右に一つインデントする

``` python
params = {
                'foo': 'fo:oo',
        'bar': 'barr'
```
- `<ESC>` を入力して、入力モードを抜けると以下の様な結果になる

```
params = {
                'foo': 'fo:oo',
        'bar': 'baoo': 'fo:rr'
}
```
## 質問

この動作は仕様なんでしょうか?
つまり Vim が自動で移動したインデントを手動で変更し、更に複数行に文字を入力したため発生するのでしょうか?
## 環境

MacVim : VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  9 2012 22:42:34) MacOS X (unix) 版 適用済パッチ: 1-515
Linux(SL) のデフォルト : VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Feb 25 2011 09:32:49)適用済パッチ: 1-411

最新の Vim は手元に自由にビルドできる環境がないので試せてません。
帰宅してから最新版をビルドして試してみます。

**Comment by mattn** [comment]
最初に編集を開始したファイルはft=pythonですか？

**Comment by mattn** [comment]
あー書いてました...すみません。

**Comment by heavenshell** [comment]
はいそうです。他の ft で再現するかまでは見てません…。

**Comment by heavenshell** [comment]
ft = javascript や ruby だと再現しないっぽい。
となると Python の問題っぽいですね…。

**Comment by mattn** [comment]
`:` でインデントされるのが起因してますね。`<s-i>` の時点では挿入位置しか知らないので、`<esc>` 時に同じカラム位置の行に対して変更が適用されます。

**Comment by koron** [comment]
- `:` を押すとindent調整が実行される → `indentkeys` による
- 前後の行までインデント修正される → `indentexpr` による

なのでft毎にこれらが設定される場合は、設定した奴の責任なので…
python用のpluginの問題ですね。

**Comment by mattn** [comment]
↑のvimrcで

```
def foo():
```

するとシフト量は1個なので、ブラケット時のインデントが直れば解決するかな。
ブラケット時は2個になってる。

**Comment by h-east** [comment]
(ランタイムdir)/indent/python.vim : 74

``` vim
" When inside parenthesis: If at the first line below the parenthesis add
" two 'shiftwidth', otherwise same as previous line.
" i = (a
"       + b
"       + c)
```

(,{,[の次の行以降のインデント量が2なのは仕様みたいです。

**Comment by mattn** [comment]
仕様じゃ`しよう`がないな。

**Comment by koron** [comment]
で **しょう** ね

**Comment by h-east** [comment]
@heavenshell if (納得) クローズ
`し`らべてみて
`よ`うやく分かった事実
`う`ぉー←感動中

**Comment by koron** [comment]
@heavenshell $VIMRUNTIME/indent/python.vim を治してくれても良いのぜ? インデント量とかconfigurableに **しよう** ぜ!

**Comment by heavenshell** [comment]
仕様なら`し よ う`が無いですね。
困ったら自分でなんとか `し よ う`と考えてみます。

関係ないですけど、今日は`し ょ う`が焼きが食べたい気分になりました!
