### ISSUE TITLE
hgコミットメッセージ用syntaxファイル

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#224]
hgのコミットメッセージ用のsyntaxファイルを作ってみました。
syntaxファイルの書き方もhgもよく分かっていないので、もっとこうした方がいいなど指摘がありましたらお願いします。

https://gist.github.com/3129572

しかし、vimはバージョン管理にhgを使っているのに、hgのsyntaxファイルがないのは何ででしょう。（実は既にある？）

**Comment by ynkdir** [comment]
hg commit syntax file
https://groups.google.com/d/msg/vim_dev/wyGRE90I3-Y/aJonJcikTl4J
提出方法が悪くてほったらかしになってしまったみたいです

**Comment by ynkdir** [comment]
知らん顔して出してしまうのがいいと思います。

**Comment by koron** [comment]
メンテナとライセンスは明記したほうが良いですね。 @ynkdir さんが貼ってくれたやつはまさにそれを指摘されてそのあと音沙汰なしな感じですからw

syntaxの中身は良いですね。GJです。…ところで今は\zsとか\zeとかこの中で使えるのね…楽になったなぁ。

**Comment by k-takata** [comment]
メンテナ、ライセンス、URLを入れました。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/vwRhy-112aE/discussion

今まで何回かvim_devに書き込んだうち、2,3回ほど自分の書き込みが見えなかったことがあるのですが何なんでしょう。
もしかして今回も、と思ってそのことを書いておいたのですが、今回は問題なかったようで…。

**Comment by ynkdir** [comment]
k-takata++

**Comment by koron** [comment]
@k-takata ++

私は vim_dev に送るときはCcにBram入れちゃってますw

**Comment by k-takata** [comment]
hg は、'HG: ' ではなく、'HG:' で始まる行をコメントと見なすようなので、パッチを修正しました。
前回の書き込みに対してBramから返事が来ていないのが…気になります。

**Comment by k-takata** [comment]
7.3.633直後のruntime filesの更新でマージされました。

**Comment by k-takata** [comment]
ラベルの編集権限がないようなので、どなたか `xlose/fixed` の設定をお願いします。

**Comment by h-east** [comment]
@k-takata おめでとうございます。ラベル設定しました。

**Comment by mattn** [comment]
@k-takata added you to owners.
