### ISSUE TITLE
indent/vim.vimがignorecaseオプションを考慮していない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#226]
標準で使用されているインデントプラグインであるindent/vim.vimですが、ignorecaseオプションがセットされている環境を考慮していません。

具体的には、次のようなコードになっています。

```
  elseif getline(lnum) =~ '^\s*aug\%[roup]' && getline(lnum) !~ '^\s*aug\%[roup]\s*!\=\s\+END'
    let ind = ind + &sw
  else
    let line = getline(lnum)
    let i = match(line, '\(^\||\)\s*\(if\|wh\%[ile]\|for\|try\|cat\%[ch]\|fina\%[lly]\|fu\%[nction]\|el\%[seif]\)\>')
    if i >= 0
      let ind += &sw
      if strpart(line, i, 1) == '|' && has('syntax_items')
            \ && synIDattr(synID(lnum, i, 1), "name") =~ '\(Comment\|String\)$'
        let ind -= &sw
      endif
    endif
```

マッチに`=~#`, `!~#`ではなく、`=~`, `!~`を使用しているため、`set ignorecase`されている場合、大文字のコマンドでもインデントされてしまいます。
Vim scriptは大文字小文字を区別するため、この挙動は好ましくないのではないかと思います。
他のインデントプラグインも同様の問題があるかもしれませんが、調べていません。

**Comment by koron** [comment]
たしかに変なことになりそうですね。とりあえず @Shougo さんにアサインしておきました。

**Comment by Shougo** [comment]
了解です。パッチ書くのを目標にします。

**Comment by Shougo** [comment]
https://gist.github.com/3232800

パッチを書きました。diffが多いですが、確実にignorecaseを無効化するため、try~finallyで囲んでいるためです。
動作確認済み。

**Comment by Shougo** [comment]
`=~`は量が多かったのと、match()もignorecaseを見るため、簡単な修正が出来なかったためです。
ignorecaseを直接変更したほうが問題が起きにくいだろうと判断しました。

**Comment by koron** [comment]
try finallyで囲むのにインデント修正するのは見苦しい&本質を見失わせるので
新たな関数を定義したほうが良いんじゃないですか? 
一例としてはこんな感じ。

``` vimL
setlocal indentexpr=GetVimIndent2() " 2になっていることに注意

...

function! GetVimIndent2()
  ...
  try
    return Get
  finally
    ...
  endtry
endfunction

function GetVimIndent()
   ...(いまのまま)
endfunction
```

こうしておくだけでGetVimIndentの中の本質的な修正がはっきりしますよ。

**Comment by Shougo** [comment]
https://gist.github.com/3232800

修正して見ました。これでどうでしょう。

**Comment by koron** [comment]
あ… GetIndentVim の中身は変わってないんですね。なるほど。

@Shougo さんは最初のやつと新しいやつ、どっちのほうが良いと思います?
具体的には、どちらのパッチのほうが受け取った時に
「あ、取り込んで良いな&問題ないな」
って感じますかね。

私は、新しい方ならば議論や検証なしでacceptします。

**Comment by Shougo** [comment]
はい。私も新しいパッチのほうが望ましいと思います。

**Comment by koron** [comment]
二人がそう思うのだから高確率でBramも支持してくれるでしょう。

ぜひvim-devへ投稿すべきです。

**Comment by Shougo** [comment]
分かりました。ちょっと今は無理ですが、今度やっておきます。

**Comment by mattn** [comment]
wrap する意味あるのですか？ GetVimIndent を直接触ると問題があるんでしょうか？

**Comment by koron** [comment]
問題はtry finallyで括るためにインデントが変わるので、diffがわかりづらいっていうだけです。
だったらwrapしたほうがわかりやすいよね、と。

**Comment by Shougo** [comment]
https://groups.google.com/forum/?hl=ja&fromgroups#!topic/vim_dev/FaXHOtRsoFA

パッチを投稿しました。

**Comment by Shougo** [comment]
返信を見たところ、Bramさんも問題点を分かってくれたようです。
案の定、他のインデントプラグインも同様の問題があるらしく、なにか解決策を取ると言っています。

**Comment by k-takata** [comment]
7.3.633 の後の runtime ファイルの更新に取り込まれているようですので、クローズします。

**Comment by Shougo** [comment]
ありがとうございます。
