### ISSUE TITLE
ユーザ補完関数を使用していると、入力した文字列がregister-.に入らない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#23]
最近のVimの補完パッチを適用したVimにおいて、ユーザ補完関数を使用していると
入力した文字列がregister-.に入りません。

個人的にかなり困っているので、再現条件や手順について、もうちょっと詳しく調べようと思います。

**Comment by Shougo** [comment]
再現条件：下記の関数を補完関数にセットします。
そして、&lt;C-x&gt;&lt;C-u&gt;&lt;C-p&gt;したあと任意の文字を入力します。

<pre>
function! CompleteFiles(findstart, base)
    if a:findstart
        " Get cursor word.
        let cur_text = strpart(getline('.'), 0, col('.') - 1)

        return match(cur_text, '\f*$')
    endif

    let words = split(expand(a:base . '*'), '\n')
    let list = []
    let cnt = 0
    for word in words
        call add(list, { 'word' : word, 'abbr' : printf('%3d: %s', cnt, word), 'menu' : 'file_complete' })
        let cnt += 1
    endfor

    return { 'words' : list, 'refresh' : 'always' }
endfunction
</pre>


すると、ポップアップが出ているときに入力された文字列はregister-.に入らないです。

**Comment by Shougo** [comment]
簡単にテストできる.vimrcは以下です。

vim -u test_vimrcで再現できます。

<pre>
function! CompleteFiles(findstart, base)
    if a:findstart
        " Get cursor word.
        let cur_text = strpart(getline('.'), 0, col('.') - 1)

        return match(cur_text, '\f*$')
    endif

    let words = split(expand(a:base . '*'), '\n')
    let list = []
    let cnt = 0
    for word in words
        call add(list, { 'word' : word, 'abbr' : printf('%3d: %s', cnt, word), 'menu' : 'file_complete' })
        let cnt += 1
    endfor

    return { 'words' : list, 'refresh' : 'always' }
endfunction

set nocompatible

let &completefunc='CompleteFiles'
</pre>

**Comment by koron** [comment]
```
:reg .
```

して、補完で入力した文字が表示されるのが期待する動作
にも関わらず表示されない、ということで良いですか?

**Comment by Shougo** [comment]
「補完で入力した文字」ではなく、「ポップアップウインドウが出ているときに入力した文字」が表示されるのが期待する動作です。それには、「補完が確定したときの文字」も当然含まれます。
ちなみに、補完で選択した文字はregister-.に入ります。ポップアップが出ているときにユーザーが入力した絞り込み文字列は入りませんでした。

**Comment by koron** [comment]
ああ。内部的には補完に使ってる変数をリセットしてるんで、
そこに巻き込まれて飛んでるんですね。
ソースコードみなくても想像がついてきました。

**Comment by Shougo** [comment]
となると、容易に修正できそうですね。現在はneocomplcacheで新しい補完が使えない状態です。修正を待っています。

**Comment by koron** [comment]
かなりadhocな対応だけどパッチはできたっぽいので
Bram氏&vim-devに投げてみます。

**Comment by Shougo** [comment]
了解です。取り込まれたら試します。

**Comment by mattn** [comment]
ネオコン関係ないのでタイトル修正しました。

**Comment by Shougo** [comment]
了解です。

**Comment by koron** [comment]
7.3.319で取り込まれました。
https://groups.google.com/forum/#!topic/vim_dev/PLgu6mQQXoM/discussion

**Comment by Shougo** [comment]
了解です。試します。

**Comment by Shougo** [comment]
動きました！
対応ありがとうございます。
