### ISSUE TITLE
windowsでalt-tabでのフォーカス切り替えがモタつく

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#231]
https://gist.github.com/3212747

``` diff
diff -r 0fc0108517a8 src/os_win32.c
--- a/src/os_win32.c    Sun Jul 29 12:55:32 2012 +0200
+++ b/src/os_win32.c    Tue Jul 31 11:06:26 2012 +0900
@@ -3319,8 +3319,7 @@
        {
        TranslateMessage(&msg);
        pDispatchMessage(&msg);
-       }
-       if (WaitForSingleObject(pi.hProcess, delay) != WAIT_TIMEOUT)
+       } else if (WaitForSingleObject(pi.hProcess, delay) != WAIT_TIMEOUT)
        break;

        /* We start waiting for a very short time and then increase it, so
```

UIの処理を優先しないとメッセージ量が多い場合にもたつく。

**Comment by koron** [comment]
コーディングスタイルがー

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/ELnDs9Jka4s/discussion

@koron 他のところを見るとこのスタイル使ってる箇所もー

**Comment by koron** [comment]
あ、ごめん。Javaと勘違いしてた。

**Comment by koron** [comment]
あ、いいんだよ。vimは {} は行変えるんだから…なんか疲れてるなぁ。モルダーなのかなぁ。

**Comment by mattn** [comment]
モルダーあなた疲れてるわ！

![](http://blogimg.goo.ne.jp/user_image/72/09/8b8319a609850b45df906b1ffb6eadc3.jpg)

**Comment by h-east** [comment]
Patch 7.3.619 で入りました。(patch内容がちょっと変わりました)
https://groups.google.com/d/topic/vim_dev/oSdGbe3A2_k/discussion
