### ISSUE TITLE
Vim 7.3.604からinput()のキャンセルの挙動がおかしい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#233]
Vim 7.3.604より、input()のキャンセル時の動作がおかしくなっています。

再現コード：

```
let hoge=input('', '', 'dir')
```

input()をキャンセルするとhogeにdirが代入されてしまいます。
これまでは空文字列の代入でした。第三引数が省略時の文字列になってしまっています。
今までと互換性がない挙動ですし、ドキュメントにも記述がありません。

Vim 7.3.604の変更を見てみたところ、
https://groups.google.com/forum/?fromgroups#!topic/vim_dev/zO8uvpafgSU
「inputdialog()における省略時の文字列をうまく動くようにした」らしいです。
おそらく、input()とinputdialog()が同じ関数で実装されていて、input()の挙動を壊して実装してしまったのだと思います。

**Comment by h-east** [comment]
脊髄反射的に作成してみたpatchです。
`input()`の挙動は前の動作になりました。
`inputdialog()`の動作確認はしてないです。

``` diff
diff -r 6581d543a54c src/eval.c
--- a/src/eval.c    Thu Aug 02 21:48:24 2012 +0200
+++ b/src/eval.c    Mon Aug 06 00:37:03 2012 +0900
@@ -12966,7 +12966,7 @@
        rettv->vval.v_string =
        getcmdline_prompt(inputsecret_flag ? NUL : '@', p, echo_attr,
                  xp_type, xp_arg);
-   if (rettv->vval.v_string == NULL
+   if (inputdialog && rettv->vval.v_string == NULL
        && argvars[1].v_type != VAR_UNKNOWN
        && argvars[2].v_type != VAR_UNKNOWN)
        rettv->vval.v_string = vim_strsave(get_tv_string_buf(
```

**Comment by h-east** [comment]
vim_devに投げました。
https://groups.google.com/d/topic/vim_dev/3VNATm1Css8/discussion

**Comment by h-east** [comment]
あ、CUIでの`inputdialog()`のキャンセル動作が7.3.604のままであることは確認済みです。

**Comment by mattn** [comment]
ぼんみすか

**Comment by Shougo** [comment]
h-east: ありがとうございます。
パッチが入ったら閉じますね。

**Comment by h-east** [comment]
Patch 7.3.624 で入りました。
https://groups.google.com/d/topic/vim_dev/ERl2wmfIbWU/discussion

@Shougo 模範的な不具合報告ありがとうございました。おかげでpatch作成時間が1分で済みました。Thanks!

**Comment by Shougo** [comment]
こちらこそ、ありがとうございます。
自分でもパッチを書こうかと思っていたくらいなので、パッチを書いてもらってありがたかったです。
