### ISSUE TITLE
windows 2000 をサポートすべきか

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#234]
https://twitter.com/kazken3/status/232287042049028096

ここからのスレッド。kaoriya 版は Visual Studio 2010 を使っているので`現状`は windows 2000 で使えるバイナリは吐けない。
Visual Studio 2010 で windows 2000 対応バイナリを吐ける方法もある。

http://blog.livedoor.jp/blackwingcat/archives/1453055.html

しかし
- 1個のバイナリを配布するのであれば、XP以降で最適化がなくなるはず
- 2個のバイナリを配布するのは koron さんのタスクが増える
- 動作確認出来る環境がない
- mingw を使えば対応バイナリは吐けるはず

この辺を議論したい。

個人的な意見では、Visual Studio 2010 が起因する問題でなく、vim 本体で dynamic loading 出来る程度の物であれば対応するつもりだったけど、そうでない今は微妙なところです。

**Comment by koron** [comment]
win32.mak使ってるなら、コンパイル時にWIN_VERの定義下げれば行けそうな気もするけど、使っているWindows SDKのバージョン次第ではそもそも下げられなさそうねw

あとタスクが増えること自体は自動化すれば解決だよねって話なのかな。

ただ個人的には、2000はもういいだろ、って言いたい。

**Comment by mattn** [comment]
いろいろ面倒みたいよ

http://blog.livedoor.jp/blackwingcat/archives/1453055.html

**Comment by koron** [comment]
うん。いま見てた。

そもそもmsvcr100.dllってWindows 2000で動くのかしらねぇ…あとiconvとかも全部やらなきゃダメなんだよね。

**Comment by Shougo** [comment]
Windows 2000はそもそも、マイクロソフト社のサポートも切れて危険なので、サポート出来なくてもしょうがないと個人的には思います。どうしても必要なら古いバージョンを使ってもらう、とか。

**Comment by mattn** [comment]
僕個人の意見はmingwでビルドしてね。
でいいと思う。

**Comment by koron** [comment]
VS2012もでていることだし、W2Kは切りましょう。

vim-jpとしての決定事項
- 古いWindowsに向けてのバイナリは基本的に用意しない
- そのような用途にはMinGWでのビルドを推奨し、できればその情報を拡充する

よってこのissueは閉じます。
