### ISSUE TITLE
:mksession で落ちる

### ISSUE THREAD

**Issue by spurzz** [vim-jp/issues#235]
``` vim
let &rtp .= ',' . repeat('a', 2048)
mksession
```
- `'sessionoptions'` に `options` が含まれていると、ものすごく長いオプション値があった場合にバッファが足りずに Segmentation falt で落ちる。
- 実際のバッファサイズは環境にもよるが 1024 程度の模様。
- `'runtimepath'` で試したが、それ以外でも起きそう。

**Comment by thinca** [comment]
しまったテスト用のアカウントで…＞＜
見なかったことにしてください。

**Comment by mattn** [comment]
!

**Comment by koron** [comment]
![spur](http://www.tatsuzine.com/wp-content/uploads/2011/05/g6BeahxLxqzr2maugDGxTmQao1_500.jpg)

**Comment by mattn** [comment]
![](http://data.tumblr.com/ZvHWLiZ7k5yhf16sngAdagbn_400.jpg)

**Comment by thinca** [comment]
おいやめろ

**Comment by h-east** [comment]
![](http://stat.ameba.jp/user_images/20120225/10/fukko-yatai/05/7d/j/o0480048011814953456.jpg)
