### ISSUE TITLE
rtpにMAXPATHL以上の文字列をセットすると set rtp の表示が途切れる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#236]
``` vim
let &rtp .= ',' . repeat('a', 2048)
mksession
```
- `'sessionoptions'` に `options` が含まれているとき、長いオプション値があると segmentation fault で落ちる。
- バッファをオーバーしている模様。バッファサイズは環境にもよるが 1024 くらい。
- `'runtimepath'` で確認したが、恐らく他のオプションでも起きる(未確認)。

**Comment by h-east** [comment]
これって私のとこではlinuxでもWin7でも再現しなかった。(issue登録時の話)
@thinca OS, Vim ver, 再現手順を提示して貰えませんか？

**Comment by thinca** [comment]
今試したら、こちらでも落ちませんでしたね。どこかのバージョンで直ったかな? 要確認。
最近メモリリークを修正したのってありましたっけ。

**Comment by h-east** [comment]
抜粋して再掲。

> (issue登録時の話)
> OS, Vim ver, 再現手順を提示して貰えませんか？

せめてOSくらいは教えて欲しいところ。

**Comment by thinca** [comment]
すいませんでした。
再確認した際の環境は Gentoo Linux Vim 7.3.629 です。
最初に試した際はOSは同じですが、Vim のバージョンは覚えてません。すいません。
確認手順は最初に示してあるとおりです。

**Comment by h-east** [comment]
ありがとうございます。

備忘録的に処理の流れを書いておきます。
- `:mksession` を実行すると ex_mkrc() が呼ばれる。
- makeset() でグローバルオプション値をファイルに書き込む。[ex_docmd.c:9113]
- 文字列オプションの書込みは put_setstring() [option.c:9221]
- P_EXPAND付きのオプションはoption.c:9284～9293 でalloc()して展開処理がおこなわれる。

落ちるとしたらここかなあ？
`runtimepath`オプションは P_EXPAND 付いてるし。
おや？その前に`runtimepath`オプションはフォルダを複数指定できるのに option.c:9284 で alloc(MAXPATHL) っておかしい！！
今のソースだと、Winは1024、linuxは4096でぶった切られるんじゃなかろうか。

**Comment by thinca** [comment]
確かにぶった切られてますね！ >linuxで4096
実際には 4095 文字でした。NULL文字かな?
とりあえずクラッシュは最新版では直ってるようですね。最近クラッシュバグの修正があった気がしないでもないので(うろ覚え)、それで直ったんですかね。(確認めんどい)

**Comment by h-east** [comment]
このissue登録時の最新Verが7.3.622ですから、落ちなくなった修正はそれ以前に入っているはず。
(私がissue登録時に最新Verで試して落ちなかった事実があるので)

**Comment by tyru** [comment]
> おや？その前にruntimepathオプションはフォルダを複数指定できるのに option.c:9284 で alloc(MAXPATHL) っておかしい！！
> 今のソースだと、Winは1024、linuxは4096でぶった切られるんじゃなかろうか。

思いっきりこれにひっかかりました。>Windowsでは1024でぶった切られる
これ別issue作った方がよくないでしょうか？

**Comment by tyru** [comment]
そこまでプラグイン入れてる＆Windowsな人が少ないってことなんでしょうか... まぁそれはともかく。

**Comment by h-east** [comment]
@tyru このissueで良いんじゃないかと思います。

**Comment by tyru** [comment]
あ、タイトルに:mksessionって入ってるので勘違いしてました。
元からruntimepathの話だったんですね。

**Comment by tyru** [comment]
すみません、一昨日・昨日と疲れて帰宅後即ベッドインで10時間ほど寝る生活だったので、先ほどは元気が有り余ってしまい変なテンションで書きこんでしまって問題をよく分かってませんでした。
問題を整理した結果、問題と呼べるべきものは以下の1点だけのようです。

### 問題

Windowsで1024文字を超える文字列をruntimepathにセットすると、プラグインはロードされているようですが、`:set rtp`の出力が次のように途中で切れています。

> $MYVIMDIR/bundle/vim-singleton,$MYVIMDIR/bundle/autodate.vim,$MYVIMDIR/bundle/capture.vim,$MYVIMDIR/bundle/caw.vim,$MYVIMDIR/bundle/codingstyle.vim,$MYVIMDIR/bundle/concealedyank.vim,$MYVIMDIR/bundle/cpp-vim,$MYVIMDIR/bundle/current-func-info.vim,$MYVIMDIR/bundle/detect-coding-style.vim,$MYVIMDIR/bundle/dutil.vim,$MYVIMDIR/bundle/emap.vim,$MYVIMDIR/bundle/fileutils.vim,$MYVIMDIR/bundle/foldCC,$MYVIMDIR/bundle/ftl-vim-syntax,$MYVIMDIR/bundle/gist-vim,$MYVIMDIR/bundle/grass.vim,$MYVIMDIR/bundle/gravit.vim,$MYVIMDIR/bundle/hatena-vim,$MYVIMDIR/bundle/instant-markdown-vim,$MYVIMDIR/bundle/kirikiri.vim,$MYVIMDIR/bundle/neocomplcache,$MYVIMDIR/bundle/nextfile.vim,$MYVIMDIR/bundle/ohmygrep.vim,$MYVIMDIR/bundle/open-browser-github.vim,$MYVIMDIR/bundle/open-browser.vim,$MYVIMDIR/bundle/operator-camelize.vim,$MYVIMDIR/bundle/operator-html-escape.vim,$MYVIMDIR/bundle/operator-reverse.vim,$MYVIMDIR/bundle/quickey.vim,$MYVIMDIR/bundle/quickfixstatus,$MYVIMDIR/bundle/ref-plugins,$MYVIMDIR/bundle/restart.vim,$MYVIMDIR/bund

(`$MYVIMDIR`はLinuxでは`~/.vim`で、Windowsでは`~/vimfiles`です)

インサートモードで`<C-r>=&rtp<CR>`したら全てのプラグインのパスが入っていたので、`:set rtp`の出力だけがおかしいのだと思います。

**Comment by tyru** [comment]
`:mksession`で落ちるのはどこかのバージョンで直ったみたいですし、タイトル変えるのはどうでしょう？

**Comment by h-east** [comment]
任せた！:cat2::dash:

**Comment by tyru** [comment]
変えました。

前：:mksession で落ちる？
後：rtpにMAXPATHL以上の文字列をセットすると set rtp の表示が途切れる

**Comment by h-east** [comment]
文字列オプションの最大 **設定**データ長には特に制限は無さそう。
（do_set() [option.c: 4698 ~ 4704辺り]）

最大 **表示**データ長はP_EXPAND属性の有無に関係なく、MAXPATHL -1 になってますね。
（showoneopt()から呼ばれている option_value2string() [option.c: 10981 ~ 10987辺り]）
<br>
`:help options` には表示データ長の制限の事は特に記述がないようです。

これは仕様なのかバグなのか...

**Comment by tyru** [comment]
とりあえず報告しておきました。
https://groups.google.com/group/vim_dev/browse_thread/thread/9bfaaa1ea4b7494c?hl=ja

**Comment by h-east** [comment]
乙です。あっ私の名前出てるw
構わないっすけどこれくらいなら名前出さなくてもおkですよー。
いちいち「俺が調べたやんけ！ワレー！」とか言いませんw
patchパクられたら悲しいですけど:smile:

**Comment by tyru** [comment]
ありがとうございます :)

2013/5/12 h_east notifications@github.com

**Comment by k-takata** [comment]
数ヶ月前に `:help 'rtp'` に以下の記載が入りました。

```
	More entries are added when using |packages|.  If it gets very long
	then `:set rtp` will be truncated, use `:echo &rtp` to see the full
	string.
```

`:set rtp` だと切り捨てられるので `:echo &rtp` を使えということなので、現時点では仕様のようです。閉じます。

**Comment by k-takata** [comment]
まあ、`:set` で切り捨てられないように修正することを否定されているわけではないので、`backlog` タグも付けておきますか。
