### ISSUE TITLE
'errorbells'がおかしい？

### ISSUE THREAD

**Issue by LeafCage** [vim-jp/issues#237]
set noerrorbells
にしても、ビープ音が鳴る。
つまり 'noerrorbells' は無効なオプションではないだろうか。
環境はWindows XP sp3

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jul 30 2012 08:25:08)
MS-Windows 32 ビット GUI 版
適用済パッチ: 1-618

今まで
set visualbell
set t_vb=
で凌いでいたが、
そもそもset noerrorbellsでビープ音を鳴らさないように出来るならそれで良かったのではないだろうか。

**Comment by h-east** [comment]
'errorbells' のヘルプを見ると

> このオプションはエラーメッセージにのみ適用され、...

と書かれているので全てのビープ音を制御するものではないようです。
このオプションで制御出来るのは例えば

``` vim
:aaa
```

と入力したときに

``` vim
E492: Not an editor command: aaa
```

とエラーメッセージが表示されますが、この時に 'errorbells' だとビープ音が鳴って、 'noerrorbells' の時には鳴らないということだと思います。

**Comment by LeafCage** [comment]
すいません。私の認識違いでした。
ありがとうございます。
