### ISSUE TITLE
Windows環境下にて「sign unplace * file=C:\...\hoge.vim」が動かない。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#238]
Windows環境下にて

> sign unplace \* file=C:\Users\naru\Desktop\hoge.vim

を実行すると
 ![](https://p.twimg.com/A0FD9N7CYAEWuD0.png)
とエラーになってしまいます。
同じく、

> sign unplace \* 

と*の後に空白を入れて実行すると同じエラーを返します。（空白を入れなければ正常に動作します。）

---

OK:　sign unplace 1 file=C:\Users\naru\Desktop\hoge.vim
OK:   sign unplace 1 file=C:/Users/naru/Desktop/hoge.vim
NG:　sign unplace \* file=C:\Users\naru\Desktop\hoge.vim
NG:　sign unplace \* file=C:\\Users\\naru\\Desktop\\hoge.vim
NG:　sign unplace \* file=C:/Users/naru/Desktop/hoge.vim
NG:   sign unplace 1 file=C:\\Users\\naru\\Desktop\\hoge.vim

---

**Comment by ynkdir** [comment]
ご報告ありがとうございます。

7.3.629 で試してみましたがエラー出ませんでした。

`:sign unplace * file={fname}` という書式は 7.3.596 で導入されたので、もしかしてそれ以前のバージョンをお使いではないですか。

```
NG: sign unplace 1 file=C:\\Users\\naru\\Desktop\\hoge.vim
```

最後のこれは私のとこでもエラー出ます。 `E158: Invalid Buffer name: ...`

**Comment by thinca** [comment]
あ、そんな最近だったんですね。
実は私も事前に確認したんですが、もしかしたら私の Windows の Vim も古かったかもしれません。(今ちょっと確認できないですが)

**Comment by rbtnn** [comment]
> :sign unplace \* file={fname} という書式は 7.3.596 で導入されたので、...

確かに、自分のVimは7.3.596より前のバージョンでした。 : [gvim73_46.exe](ftp://ftp.vim.org/pub/vim/pc/gvim73_46.exe)

**Comment by thinca** [comment]
私のところではバージョンを上げたら Windows でも問題ありませんでした。

@rbtnn 問題ないようならば `worksforme` で閉じてしまってください。

**Comment by rbtnn** [comment]
ご回答ありがとうございました。
