### ISSUE TITLE
rで日本語に書き換えができない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#239]
[ココ](https://twitter.com/_atton/status/234876271153266688) とか [ココ](https://twitter.com/supermomonga/status/232550927628902401) に報告があった。

過去に同様の問題があったと記憶しているが確か直していたはず。それが再発したか?

「Windowsはそんなことないだろ」と思って試してみたら、 **一回だけ** 発生した。IMEはGoogleのβ版のほう。「号」という文字の上で r してIME ONにして「合」にするため「gou」とタイプしたら、

```
g
u
```

ってなった。ただ一回だけ。再現しない。

要追試。

**Comment by ynkdir** [comment]
CursorHold イベントが定義してあると発生します。

**Comment by ynkdir** [comment]
とおもったけど違ったみたいです。。。

**Comment by ynkdir** [comment]
しばらく試して再現せず。ただの入力ミスだったようです。失礼しました。

**Comment by koron** [comment]
私のWindowsのほうも操作ミスってことで良いとして(ほんとか?w)

LinuxはIMとの組み合わせによっては起きないか、気になります。

**Comment by ynkdir** [comment]
CUIは端末しだいですがまあ大丈夫だと思います。
GUI(のon-the-spot)はどのIMでもrでは日本語入力できないです。Vimの実装的に。

**Comment by k-takata** [comment]
8.0.1026で直ったはず。
