### ISSUE TITLE
ドラッグ&ドロップで開いたファイルのバッファを削除すると落ちる

### ISSUE THREAD

**Issue by hattya** [vim-jp/issues#24]
KaoriYa版Vim 7.3.315 (win32)で`colorcolumn`が設定してある場合、
ドラッグ&ドロップで開いたファイルのバッファを削除すると落ちます。
KaoriYa版Vim 7.3.303 (win32)では同じ条件でも落ちません。

個人的にはバッファの実装に変更を加えている[7.3.306](http://code.google.com/p/vim/source/detail?r=0787bb5f387b79842d5c9353ae3541a992d1b9f1)が気になっています。

**Comment by h-east** [comment]
再現手順です。
gvim.exe -N -u NONE -U NONE -i NONE --noplugin -c "set cc=+1"
:e a
:new
:only!
:bd

補足情報
・aというファイルは既存でも新規でもOKです。
・オリジナル(Not KaoriYa)でも再現します。
・WindowsのCUI(vim.exe)でも再現します。
・linuxのCUI(vim)でも再現します。

hattyaさん＞
報告ありがとうございます。

**Comment by mattn** [comment]
チェック関数がNULL参照してますね。
私がパッチ書きます。

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/-kGOxYuf0Q8/discussion

done.

**Comment by h-east** [comment]
@mattn GJ!

**Comment by mattn** [comment]
マージされたので閉じます。
https://groups.google.com/d/topic/vim_dev/CzxEthsQXfw/discussion
