### ISSUE TITLE
Windowsのシンボリックリンクを正しく扱えるようにしたい

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#241]
WindowsでもVista以降ではシンボリックリンクが扱えるようになりました。
しかし、`:set backupcopy=auto` の時、シンボリックリンクを認識せず、リンクを切ってしまいます。
修正案(仮)を以下に置きました。
https://gist.github.com/3415752

ただ、このパッチだといくつか課題があります。
1. シンボリックリンクは切れなくなったが、ファイルを保存するとリンク先ファイルの属性がリードオンリーになってしまう。
2. シンボリックリンクかどうかの判定が簡易的。`FILE_ATTRIBUTE_REPARSE_POINT` フラグが立つのは、シンボリックリンクだけでなくジャンクションの場合もある。（ディレクトリは除外するようにしたので問題はないはずですが。）
3. `backupcopy` が `breaksymlink` の場合に対応していない。（元々Windows版は `breakhardlink` にも対応していないようですが。）

1が致命的なのですが、今のところ原因が分かっていません。

**Comment by koron** [comment]
パッチを見る限り、

> Vimのファイル書き込みロジックに「シンボリックリンク先のファイルを書くとパーミッションがおかしくなる」バグがあるが、
> そのパッチを当てる前は顕在化しない状況だった。ところがパッチをあてたことで顕在化した

という風に見えますね。autoのケースでの書き込み時、特にmch_is_linkを使った後の流れを追えば何か分かりそうです。

ただ… @mattn さんが得意そうな領域な予感w

**Comment by mattn** [comment]
実は @k-takata さんも windows hacker なのであった。

**Comment by k-takata** [comment]
buf_write()を見ていますが難しい… vim hackerではありませぬゆえ。

めも
- [Symbolic Links (Windows)](http://msdn.microsoft.com/ja-jp/library/aa365680.aspx)
- [Symbolic Link Effects on File Systems Functions (Windows)](http://msdn.microsoft.com/ja-jp/library/aa365682.aspx)
- [ReplaceFile function (Windows)](http://msdn.microsoft.com/ja-jp/library/aa365512.aspx) -- いっそバックアップの作成処理をWindowsにまかせてしまうのもあり？

**Comment by ynkdir** [comment]
[Patch] Re: 'backupcopy' and Windows Vista symbolic links
https://groups.google.com/d/msg/vim_dev/qF8Y3xtUP-w/W1x7mZ4FrnkJ

これはどうですか

**Comment by ynkdir** [comment]
↑vim_devのパッチ動作確認してみました。属性の問題も大丈夫みたいです。

**Comment by k-takata** [comment]
ちょうどいいタイミングで本家で同じ話題が上がるとは。

パッチの投稿者がGoogle Code上で新しいコードを公開していたので、それを適用して動作確認しました。
1カ所メモリリークを起こしていると思われる場所があったのでそれも修正しました。問題なく動いているようです。
https://gist.github.com/3436380

**Comment by k-takata** [comment]
IO_REPARSE_TAG_SYMLINK の値を直に書いてあったのが気になったので修正しました。

あとは、mch_getperm() の先頭部分で、パス末尾の '\' を切り落としている処理がちょっと気になったり。
実はこのための関数が用意されていたりしませんか？

**Comment by h-east** [comment]
@k-takata `vim_ispathsep()` は使ったほうが良さげですね。

**Comment by k-takata** [comment]
なるほど。
それもありますけど、char_u という型は UTF-8 なのでしょうか。もし、Shift_JIS が入るような場合があるとこのコードではダメだと思いますが。

**Comment by h-east** [comment]
vim_ispathsep()の上に `gettail()`、`gettail_dir()`、`gettail_sep()` 等があり、マルチバイト対応してるようですよ。

**Comment by ynkdir** [comment]
mch_stat() (=vim_stat()) で同じことしてます。

**Comment by k-takata** [comment]
そうだと、mch_getperm() から mch_stat() を呼んじゃうのが良さそうですね。

**Comment by k-takata** [comment]
パッチ更新しました。
https://gist.github.com/3436380/70e3e808ba65a2d3eba6c20b9ee2717223e6d2ab

mch_is_linked() でディレクトリへのsymlinkは除外していないが大丈夫なんだろうか。上位で除外されてるのかな。

**Comment by k-takata** [comment]
パッチ更新しました。`breaksymlink`, `breakhardlink` に対応しました。
https://gist.github.com/3436380/927920a415c0a33bfc0555df04005ee3c30cdba0

ところで mch_ って何を意味するプレフィックスなのでしょう？

**Comment by koron** [comment]
@k-takata 

> ところで mch_ って何を意味するプレフィックスなのでしょう？

マシン(OSとかCPU)とか、そういう環境の違いを吸収する関数に付けられます。

**Comment by k-takata** [comment]
なるほど。
さて、vim_devにパッチ投げてみたいと思います。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/qF8Y3xtUP-w/opEIDRL94qoJ

**Comment by ynkdir** [comment]
グッジョブ！

**Comment by k-takata** [comment]
今更ながら todo.txt を見ると、載っていました。ちゃんと見ないとダメですね。

> Patch for 'backupcopy' default behavior for symlinks on Windows. (David Pope,
> 2012 Mar 21, update Mar 31)

**Comment by k-takata** [comment]
todo.txt が更新されました。

> Patch for 'backupcopy' default behavior for symlinks on Windows. (David Pope,
> 2012 Mar 21, update Mar 31)
> With fix for memory leak: Ken Takata, 2012 Aug 24

**Comment by koron** [comment]
@k-takata: #257 の件、調査&必要ならば修正をお願いできますか?

**Comment by h-east** [comment]
Patch 7.3.1182 で取り込まれました。(todo入りから9ヶ月後!!)
https://groups.google.com/d/msg/vim_dev/vI8gjclL-48/fmkZ5aTt7y0J

**Comment by Shougo** [comment]
取り込まれるのにすごいかかってる……。

**Comment by k-takata** [comment]
自分が最初に投げたVim本体に対するパッチが、実はこれ。
(runtimeファイルに対するパッチはこの前にもいくつか投げていますが。)

**Comment by Shougo** [comment]
ほう、記念すべきマージですね。

**Comment by koron** [comment]
> 32-bit gVim 7.3.1182 (features=normal) on 64-bit Win7+SP1 freezes when I attempt to edit any file in a directory that is hard linked to another directory. After killing the process, a second attempt to edit the same file reveals that a swap file was created. backupcopy is not changed from its default value in my configuration.
> 
> There are no such problems with 7.3.1181

ってな情報が 7.3.1182 のパッチに来てるけど、何かわかる?

https://groups.google.com/d/msg/vim_dev/vI8gjclL-48/3KJlK0iEjOkJ

**Comment by k-takata** [comment]
再現せず、分かりません。

```
mkdir foo1
echo foo1 > foo1\foo1.txt
mkdir foo2
mklink /h foo2\foo2.txt foo1\foo1.txt
gvim -N -u NONE -U NONE foo1\foo1.txt
gvim -N -u NONE -U NONE foo2\foo2.txt
```

**Comment by k-takata** [comment]
> I attempt to edit any file in a directory that is hard linked to another directory.

ディレクトリへのハードリンクを作ったといっているように見えるが、そんなのできないしなぁ!?

**Comment by k-takata** [comment]
間違いだったようです。
https://groups.google.com/d/msg/vim_dev/vI8gjclL-48/SssO3L33WMEJ

**Comment by koron** [comment]
:+1:

**Comment by ynkdir** [comment]
↑の問題とは関係ないかもしれませんが
もしかして mch_is_symbolic_link() は enc がデフォルトコードページだと機能しないくないですか？
FindClose(hFind) で未初期化ハンドル渡してたり。
動かして確認はしてませんが。

**Comment by k-takata** [comment]
げ。こんな感じ？
https://bitbucket.org/k_takata/vim-win32-mq/src/f69e511e671eabbe45aef54a6ec60717de30d1a4/fix-7.3.1182.patch

**Comment by ynkdir** [comment]
そんな感じだと思います。
これ動作確認はどういう手順でやればいいですか。

**Comment by ynkdir** [comment]
すいませんわかりました。動作確認できました。

**Comment by k-takata** [comment]
投げました。Ajit氏に確認してもらうのが一番？
https://groups.google.com/d/msg/vim_dev/vI8gjclL-48/2KspIu5AcL4J

修正前の実行ファイル(VC10)で enc=cp932 にしてシンボリックリンクになっているファイルを編集したところ、リンクが切れてしまいました。ハングしなかったのはコンパイラの違いでしょうか。

一応、手順を書いておきます。

```
touch foo.txt
mklink /s bar.txt foo.txt
gvim -u NONE -U NONE bar.txt
```

bar.txt の中身を適当に編集すると、foo.txt の中身も一緒に変わるのが期待値です。

**Comment by k-takata** [comment]
7.3.1210、はやっ！
https://groups.google.com/d/msg/vim_dev/vy9XcnldzpM/mOJ9vYKAqN8J

**Comment by ynkdir** [comment]
ありがとうございます!

**Comment by koron** [comment]
これは速いw

**Comment by h-east** [comment]
おつです。patch投稿後14分で取り込まれてるw

**Comment by k-takata** [comment]
無事直ったようです。
https://groups.google.com/d/msg/vim_dev/vI8gjclL-48/PwdFGTbHuQEJ
