### ISSUE TITLE
e_noroomの翻訳を修正する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#242]
私的なメモに近い: 翻訳がわかりにくいので直そう、という話。

> 最近Vim に『E36: 充分な容量がありません』って言われることが多いんだが…。 [manga_osyo](https://twitter.com/manga_osyo/status/238011215937433601)

原文は

> E36: Not enough room

で、globals.hにおいてe_noroomとして定義され、window.c内で6箇所利用されている。

`room` を `容量` と訳しているが window.c で使われていることから、スペース=ウィンドウの幅や高さの意味だと推測される。よってメッセージから原因が推測しにくい翻訳となってしまっているので要修正。

**Comment by koron** [comment]
案1: 具体的にしてみた。具体的な分、使われている場所のコンテキストとはズレる可能性があるので、念のため確認したほうが良いかも。

```
ウィンドウに十分な高さもしくは幅がありません
```

案2: 抽象的なまま、訳語だけ変えてみた。訳してもカタカナのままだと結局わかりにくいかもしれないが、領域とか余白とか場所とか言ってもやっぱりイマイチ感は拭えない。

```
十分なスペースがありません
```

**Comment by h-east** [comment]
あー、ステータスライン複数行対応でソースいじってるとよく目にします。e_noroom

```
(あなたが)入り込む余地などありません
```

**Comment by osyo-manga** [comment]
エラーメッセージから勝手にメモリ周りのエラーかと思ってたら全然違ってた…。
客観的に見ると

```
ウィンドウに十分な高さもしくは幅がありません
```

ぐらい具体的な方が分かりやすくていいですね。

**Comment by h-east** [comment]
> あー、ステータスライン複数行対応でソースいじってるとよく目にします。e_noroom

あっ、そういえば指定されたステータスラインの高さがwindowに収まらないときも `e_noroom` にするんですが、この場合でも

```
ウィンドウに十分な高さもしくは幅がありません
```

で意味が通じるので↑に +1 です。

**Comment by koron** [comment]
了解。では

```
ウィンドウに十分な高さもしくは幅がありません
```

にします。とはいっても…ja.poは更新しても本家になかなか反映されないからなぁw とりあえず+kaoriyaでは次回分から直します。

**Comment by koron** [comment]
gistにパッチ貼ろうとしたが、エンコード混在でひどい目にあうなこりゃ。

**Comment by koron** [comment]
手元は修正済み。

本家に入れるのは別の問題として扱うべき。
