### ISSUE TITLE
ACLが保存・復帰されない (Cygwinの属性の保存)

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#244]
os_win32.c には、mch_get_acl(), mch_set_acl() という関数がありますが、これらが機能していないことに気づきました。
問題点は以下の通り。
1. mch_get_acl() で Owner, Group, DACL, SACL を取得しようとしているが、SACL を取得するには、SE_SECURITY_NAME 権限が有効になっていなければならない。（admin権限でプログラムを起動した上に、プログラム自身で SE_SECURITY_NAME 権限を有効化しなければならない。）
2. Owner, Group は通常権限で取得・設定が可能とは限らない。
3. そもそもマルチバイトファイル名に全く対応していない。

修正パッチを作ってみました。
https://gist.github.com/3489193

処理の概要は次の通り。
1. 初期化時に SE_SECURITY_NAME 権限の有効化を試みる。
2. Owner, Group, DACL, SACL の取得を試みる。権限不足で失敗した場合は、DACL のみ取得する。
3. セキュリティ情報設定の際は、取得できたものだけを設定する。(DACL のみの設定であれば、自分が Owner のファイルは admin 権限は不要。)
4. DACL 設定の際は、親ディレクトリの DACL を継承しないようにする。
5. マルチバイト文字に対応。

このパッチにより、`:set backupcopy=auto` でも Cygwin のパーミッションが保持されます。（644 が勝手に 755 に変わったりしない。）
なお、Owner, Group の取得・設定にはどういう権限が必要かは、まだよく把握していません。
SACLが何なのか、保存が必要かどうなのかもまだよく分かっていません。

**Comment by h-east** [comment]
GJ! 
コーディングスタイルについてのみのチェックです。patchの57行目と236行目、開始ブロック(`{`)が行末になってます。
(次行のインデント先頭が正しいですよね)

**Comment by k-takata** [comment]
修正しました。ついでに win32_enable_privilege() を #ifdef で囲みました。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/OOs94wJKFPc/discussion

**Comment by koron** [comment]
GJ

**Comment by k-takata** [comment]
todoリスト入りということは、取り込まれるまで時間が掛かりそうな感じがしますね。

**Comment by koron** [comment]
TODOに入った、それだけでは判断できません。数日後に出てきたこともありますし、数ヶ月経っても出てこないこともあるのでw

**Comment by koron** [comment]
おっと。TODOに入ったので todolisted で閉じます。

**Comment by h-east** [comment]
close＆タグ付けは実際に runtime/doc/todo.txt が更新されてからという運用にしております。

Issueを閉じる手順
https://github.com/vim-jp/issues/wiki/Member

そういえば上記ページの「タグの付け方」は「あとで @koron さんが書く」状態のままだ(´・ω・｀)

**Comment by koron** [comment]
それは失礼&了解。

書くのは気力が出ない _(：3 」∠ )_

**Comment by k-takata** [comment]
親ディレクトリのDACLを継承しているファイルについては、継承している状態を維持するようにパッチを更新しました。

**Comment by k-takata** [comment]
todo.txt に入りました。

> MS-Windows ACL support doesn't work well.  Patch from Ken Takata, 2012 Aug 29.
> Update Aug 31.

**Comment by k-takata** [comment]
todo.txt が更新されていますので、メモしておきます。
MinGW でビルドすると ACL サポートが無効になっていたので、修正パッチを送付済みです。

> MS-Windows ACL support doesn't work well.  Patch from Ken Takata, 2012 Aug 29.
> Update Aug 31.
> Another patch for MingW, 2012 Dec 29.

**Comment by k-takata** [comment]
7.3.1267, 7.3.1268 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/u06C-h7ugRc/discussion
https://groups.google.com/d/topic/vim_dev/9DhnWnGPNyU/discussion

**Comment by mattn** [comment]
GJ
