### ISSUE TITLE
iconv.dllがノートンにウィルスと誤認&削除された

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#246]
[出典](http://lingr.com/room/vim/archives/2012/09/02#message-11737348)

> Win 32bit 20120902をダウンロードして解凍したのですが iconv.dllがヒューリスティックウィルスとしてノートンに削除されました

```
脅威: Suspicious.Cloud.7.F
____________________________
____________________________
コンピュータの評価日 2012/09/03 3:31:49
前回の使用 2012/09/03 3:31:49
起動項目 いいえ
起動済み いいえ
____________________________
____________________________
不明
このファイルを使った Norton コミュニティのユーザー数: 不明
____________________________
不明
このファイルの更新日は現在不明です。
____________________________
高
これは危険度が高いファイルです。
____________________________
脅威の詳細
脅威の種類: ヒューリスティックウイルス検出。 マルウェアヒューリスティックに基づく脅威の検出。
____________________________
____________________________
ファイル処理
ファイル: c:\users\hideo\downloads\vim73-kaoriya-win32-20120902\vim73-kaoriya-win32\iconv.dll
遮断しました
____________________________
ファイルサムプリント - SHA:
16289c9b8150d2210419c8de13316a7e6885dcf32ebb47dbac244e32844f9622
____________________________
ファイルサムプリント - MD5:
a18166afa0e4ae768bbbbeaa0d72aa63
```

後日調査するために、こっちへ転載しました。

**Comment by koron** [comment]
現時点では方針立たず。

**Comment by koron** [comment]
#190 はvim本体。やはりあちらもノートンだった。

**Comment by ynkdir** [comment]
http://www.symantec.com/index.jsp

Security Response / CONTACT / Report a Suspected Erroneous Detection (False Positivfe)

誤検知報告フォームはいちおうあるようです

**Comment by koron** [comment]
ユーザさん本人に報告してもらうのが良いのかな?

**Comment by koron** [comment]
とりあえずMicrosoft Security Essentialsをかけた限りではiconv.dllに問題はありませんでした。

**Comment by koron** [comment]
https://submit.symantec.com/false_positive/ ここからSymantecへ報告して、と報告者に伝える方向で。

**Comment by koron** [comment]
ちなみにこのURLに行くには http://www.symantec.com/ja/jp/ から **セキュリティレスポンス** → **セキュリティレスポンス
問い合わせ** → **誤検知の疑いを報告(英語)** という手順。

**Comment by ynkdir** [comment]
それがいいと思います。

**Comment by koron** [comment]
とりあえずオンラインスキャンサービスかけてみた。以下はその結果へのURL
- virustotal
  - [Win 32bits](https://www.virustotal.com/file/d519c485f898e8e72c7a2d389bbb22ba9f91df0fbf51f9d0f31314e521bf1c06/analysis/1346750674/)
  - [Win 64bits](https://www.virustotal.com/file/d9f3c37e7bcc68098f5a732cafe51a63b01a058a13ecb47ff1060ab1acad410d/analysis/)
- Metascan online
  - [Win 32bits](http://www.metascan-online.com/results/twumumvuyyv45btn0ehtyzq2lp7oufw3)
  - [Win 64bits](http://www.metascan-online.com/results/u0zffiyorcnt5cao52i599hwi790ean3)

virustotal の 64bits は誰かが2日前にやってくれたらしいw

**Comment by koron** [comment]
「もしもノートンに削除されたら」とかそういう記事を書いておきたい。

**Comment by thinca** [comment]
これは記事を書いたら close?

**Comment by koron** [comment]
may be.

**Comment by koron** [comment]
アクションのしようが無いので閉じます。
