### ISSUE TITLE
:cfileしたときにfencsが効かない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#249]
MSVCのコンパイルログ(cp932)をenc=utf-8なVimで`:cfile`したら文字化けして悲しかった。

fencs みてちゃんとしてほしい。

**Comment by thinca** [comment]
これは `:cfile` でいいんですよね?
`<cifle>` もあって紛らわしかったのでタイトルと本文直しておきました。違ったらすいませんが再修成してください。

**Comment by thinca** [comment]
多分関連: #9

**Comment by koron** [comment]
修正箇所的には別の場所になりそうな悪寒w

**Comment by mattn** [comment]
fencs効かせる事になると`:cfile ++enc=xxx`もいるなー。

**Comment by k-takata** [comment]
`:make` も `:cfile` も同じ箇所でファイルを読んでいることが判明しましたので、同一案件として閉じようと思います。なお、ファイルは一行ずつ読んでいるため、`fencs`を効かせるのは難しそうです。
