### ISSUE TITLE
ポップアップが出ているときに、<C-r>のマッピングが無効化される

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#25]
表題の通りで、ポップアップが出ているとき、&lt;C-r&gt;のマッピングが効きません。
この制限により、ユーザーが&lt;C-r&gt;に機能を割り当てることが事実上できなくなっています。
どうにか修正できないでしょうか。
他のキー、例えば&lt;Down&gt;/&lt;Up&gt;などは普通にマッピングできるので、&lt;C-r&gt;ができないのはおかしいと個人的に思います。

ref: #26

**Comment by h-east** [comment]
ご使用のVimのバージョンを教えて下さい。
7.3.284(Win32 kaoriya)では再現しませんでした。(マッピング効いた)

**Comment by Shougo** [comment]
Vim 7.3.322 in Linuxです。

**Comment by Shougo** [comment]
あ、こちらで試してみたところ、&lt;C-n&gt;/&lt;C-p&gt;では効かず、&lt;C-x&gt;&lt;C-u&gt;では再現しました。
ユーザー定義補完では再現するので、Vimのバグ疑惑です。
下記の.vimrcで起動して、:inoremap &lt;C-r&gt; aとします。
&lt;C-x&gt;&lt;C-u&gt;した状態で&lt;C-r&gt;するとバグが発現します。

<pre>
function! CompleteFiles(findstart, base)
    if a:findstart
        " Get cursor word.
        let cur_text = strpart(getline('.'), 0, col('.') - 1)

        return match(cur_text, '\f*$')
    endif

    let words = split(expand(a:base . '*'), '\n')
    let list = []
    let cnt = 0
    for word in words
        call add(list, { 'word' : word, 'abbr' : printf('%3d: %s', cnt, word), 'menu' : 'file_complete' })
        let cnt += 1
    endfor

    return { 'words' : list, 'refresh' : 'always' }
endfunction

let &compeltefunc=CompleteFiles
</pre>

**Comment by mattn** [comment]
バグでは無いですね。

getchar.c:2035くらいから抜粋

```
* Don't look for mappings if:
* - no_mapping set: mapping disabled (e.g. for CTRL-V)
* - maphash_valid not set: no mappings present.
* - typebuf.tb_buf[typebuf.tb_off] should not be remapped
* - in insert or cmdline mode and 'paste' option set
* - waiting for "hit return to continue" and CR or SPACE
*    typed
* - waiting for a char with --more--
* - in Ctrl-X mode, and we get a valid char for that mode
```

以下の時にはマッピングを見ない
- マップが無効な状態(CTRL-V)
- マッピングが提供されていない
- リマップされるべきではないキー
- インサートもしくはコマンドモードで`paste`オプションが設定されている時
- `hit return to continue`でのCRもしくはSPACE
- `--more--`でキーを待っている時

で、次が重要
- CTRL-Xモードの時。モードに対して正常なキーを取る。

つまり、`<c-x><c-u>`はCTRL-Xモード中なので、キーはマップ変換されないのが仕様です。

**Comment by Shougo** [comment]
> CTRL-Xモードの時。モードに対して正常なキーを取る。

あれ？ それはおかしくないでしょうか。`<Up><Down>`などは普通にマッピングされます。
というか、私的にはマッピング変換されたほうが嬉しいのですが……。

**Comment by Shougo** [comment]
ということは、`<C-x><C-*>`ってマッピングが効かない特殊なモードになってしまっているということですね。
そこのマッピングをユーザーが設定できないのこと自体がおかしいのではないでしょうか。
私的には、popup modeが欲しいです。ポップアップが出ているときのマッピングを設定したいです。

**Comment by mattn** [comment]
> あれ？ それはおかしくないでしょうか。`<Up><Down>`などは普通にマッピングされます。
> というか、私的にはマッピング変換されたほうが嬉しいのですが……。

ですからCTRLモードです。`<up><down>`にはCTRL修飾が付いてないですよね。なのでmap変換されます。
タイトルにもある`<c-r>`や #26 の `<c-u>` はCTRLモードの続きになるのです。

**Comment by mattn** [comment]
`おかしい`はShougoさんの勝手な仕様であって`欲しい`とか`したい`は希望ですよね。苦笑
vimのバグではないです。なので`feature request`です。
ご希望に沿えなくて残念ですが、僕はバグ修正の方を優先したいです。

なおShougoさんがpatchを書く分には止めたりはしません。:)

**Comment by thinca** [comment]
本題と趣旨がずれますが、ソースコードの記述のみでドキュメントに記述されていないのは問題だと思います。

**Comment by mattn** [comment]
`:help popupmenu-completion`と`:help popupmenu-keys`には`状態1`という名称で綺麗に書かれているのに、`:help insert_expand`は今一つですね。

**Comment by mattn** [comment]
あ、`:help complete_CTRL-Y`に書いてありますね。

> Note: The keys that are valid in CTRL-X mode are not mapped.  This allows for
> ":map ^F ^X^F" to work (where ^F is CTRL-F and ^X is CTRL-X).  The key that
> ends CTRL-X mode (any key that is not a valid CTRL-X mode command) is mapped.
> Also, when doing completion with 'complete' mappings apply as usual.

日本語ドキュメントだと

> Note: CTRL-Xモードでの有効なキーはマップされない。これは":map ^F ^X^F"な指定を
> 可能にする(^Fと^XはそれぞれCTRL-FとCTRL-Xの意味)。これに対して、CTRL-Xモードを
> 終了させるキー(つまりCTRL-Xモードのコマンドとして有効ではないキー)はマップされ
> る。'complete'を使って補完をするとき、マップは通常通りに適用される。

**Comment by thinca** [comment]
更にその下に、`CTRL-R` は例外として `CTRL-X` モードを終了しない、とありますね。
つまりまとめると、
- `CTRL-X` モードに割り当てられていないキーは `CTRL-X` モードを終了する
- `CTRL-R` は例外で `CTRL-X` モードを終了しない
- `CTRL-X` モードを終了するキーはマッピングが有効。それ以外は無効

ってことですね。ややこしい…。

**Comment by Shougo** [comment]
> vimのバグではないです。なのでfeature requestです。
> ご希望に沿えなくて残念ですが、僕はバグ修正の方を優先したいです。

はい。当初はバグかと思ったのですが、feature requestですね。

> なおShougoさんがpatchを書く分には止めたりはしません。:)

できれば書きたいですけど、どのあたりをいじればいいのか分かりません……。
上記の仕様もなぞ。というのは、マッピングされない挙動がよければ`:imap`ではなく、
`:inoremap`を使えばよいはずで、上記の仕様の回避方法がないのが問題だと思うのです。

バグというほど致命的ではないですが、補完を使っていてかなり不便だと感じましたね。どうにかしたい……。

**Comment by koron** [comment]
**解説**

<kbd>ctrl</kbd> + <kbd>x</kbd> 補完時に <kbd>ctrl</kbd> + <kbd>r</kbd> にだけ map できない
という仕様に対してのチャレンジでした。仕様そのものは、わかりにくいけれども documented でした。

**裁定**

必要性と実現期待値の低さから backlog 送りとします。
