### ISSUE TITLE
i(nore)?mapが発動するとIMEが勝手にOFFになってしまう

### ISSUE THREAD

**Issue by ledyba** [vim-jp/issues#251]
はじめまして。
Windows Vista32bit版とWindows7 64bit版で、公式のバイナリとKaoriya 32/64ビット版のgvimで確認したのですが、

&#105;&#110;&#111;&#114;&#101;&#109;&#97;&#112;&#32;&#60;&#85;&#80;&#62;&#32;&#60;&#99;&#45;&#92;&#62;&#60;&#67;&#45;&#79;&#62;&#103;&#107;&#10;
&#105;&#110;&#111;&#114;&#101;&#109;&#97;&#112;&#32;&#60;&#68;&#79;&#87;&#78;&#62;&#32;&#60;&#99;&#45;&#92;&#62;&#60;&#67;&#45;&#79;&#62;&#103;&#106;&#10;

と設定すると、IMEオンで入力中に上下移動するとIMEが勝手にオフになってしまうようです。
i(nore)?mapを使わずに手動でコマンド入力するとIMEはOFFにならず、コマンド入力前の状態を保持してくれるので、i(nore)?map特有のバグだと思うのですが、他に症状を確認された方などいらっしゃいますか？

&#35; どこに投げれば良いのか分からなかったのですが、ここで良かったのでしょうか…？

**Comment by Shougo** [comment]
InsertLeave時に、IMEをオフにする設定があるのではないでしょうか。
まだ詳しい確認はしていませんが、`<C-o>`を実行した時に一度Insertmodeを抜けるのでInsertLeaveが呼ばれるのではないかと思います。

**Comment by Shougo** [comment]
`<C-o>`時に、InsertLeaveイベントが呼ばれるのを確認しました。

```
autocmd InsertLeave * echomsg 'hoge'
```

を実行しておくと確認できるはずです。おそらくバグではなく、仕様だと思います。

**Comment by koron** [comment]
ちょっと遠回りな解決策ですが i_<C-Down> に「見た目行」での下移動(gj相当)が実装されてても良いかもですね。Vim本体に機能追加、という形で。

**Comment by ledyba** [comment]
こんにちは。ありがとうございます。

> Shougoさん

vimrc/gvimrcを削除して素の状態にして確認してみました。
仰るとおり、手動の&#60;&#67;&#45;&#79;&#62;&#103;&#106;で移動した場合も、i(nore)?mapで移動した場合も、どちらも挿入モードから一旦抜けてまた入る扱いみたいです。
手動の<C-O>gjの場合はIMEがONの状態で挿入モードに戻るので、やはりmap特有の何かがあるように思うのですが…。

> koronさん

私もそう思います。

**Comment by koron** [comment]
@ledyba 

> 手動のgjの場合はIMEがONの状態で挿入モードに戻るので、やはりmap特有の何かがあるように思うのですが…。

手で i_<C-o> した時はイベントが発生しないけど、マップ経由で行った時は発生するみたいなルールがあってもおかしくないですね。いずれにせよ現在のところ @ledyba さんの目的を達成する正当な手段はないでしょう。

**Comment by koron** [comment]
あ～ちがう。わかったわかった。
- iminsertの値を更新するのは、ESCでinsertモードを抜けた時だけ
- iminsertの値を適用するのは、<C-O>後にinsertモードに戻った時にも

ってなってます。その証拠に、IME ONのままESCでinsertモードを抜けて、その後再度insertモードで<Down>すれば、こんどはIMEがOFFにならない。

なので、Vimの実装のバグですね。C-Oで抜けるときもiminsertを更新するようにする、ってのが簡単に思いつく解決策だが…なんか副作用有りそうw

**Comment by koron** [comment]
@だれか: 過去にiminsertの更新タイミングについて議論していた場所があったと思ったんだけど見つけられません。知っていたら教えて下さい。

**Comment by koron** [comment]
> IME ONのままESCでinsertモードを抜けて、その後再度insertモードで<Down>すれば、こんどはIMEがOFFにならない。

ついでに、この状態でIME OFFにしてから<Down>するとIMEがONになるはずw

**Comment by ledyba** [comment]
@koronさん
なるほど…。

> IME ONのままESCでinsertモードを抜けて、その後再度insertモードですれば、こんどはIMEがOFFにならない。
> ついでに、この状態でIME OFFにしてからするとIMEがONになるはずw

私の環境でも両方とも再現しました…。

**Comment by h-east** [comment]
> @だれか: 過去にiminsertの更新タイミングについて議論していた場所があったと思ったんだけど見つけられません。知っていたら教えて下さい。

「 #64 iminsertとimdisableが直ちには反映されない」ですね。
Githubのsearch機能が腐ってるっぽいですｗ

**Comment by koron** [comment]
@h-east Thanks! 検索で日本語が使えるようになった時にindexが飛んだのかしらね?w

**Comment by koron** [comment]
iminsert の件は #228 へ続いていた。

**Comment by koron** [comment]
duplicated #228 なのでこっちは閉じます。
