### ISSUE TITLE
Cygwinビルドで +perl/dyn, +python/dyn が動かない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#252]
Cygwinで +perl/dyn, +python/dyn でビルドすると、これらが正常に動作しません。
configureは以下の通り。

```
$ ./configure --with-features=huge --enable-perlinterp=dynamic --enable-pythoninterp=dynamic
```

まずはperlですが、perlのDLLが無い状態で起動しようとすると以下のようなエラーになります。

```
$ ./vim
/cygdrive/c/....../vim/src/vim.exe: error while loading shared libraries: cygperl5_14.dll: cannot open shared object file: No such file or directory
```

dynamicを指定しているにもかかわらず、cygperl5_14.dll の PL_thr_key 関数を参照してしまっています。対策を調べてみましたが、分かりませんでした。

次に、pythonの方ですが、`:python print "hello"` を実行すると次のようなエラーが出ます。

```
E370: ライブラリ libpython2.6.dll.a をロードできませんでした
E263: このコマンドは無効です,ごめんなさい: Pythonライブラリをロードできませんでした.
```

こちらは、libpython2.6.dllではなくlibpython2.6.dll.aをロードしようとしているのが原因です。src/configure.in の中に、

```
    @echo "python_INSTSONAME='$(INSTSONAME)'"
```

という部分があるのですが、Cygwinの場合は $(INSTSONAME) ではなく、$(DLLLIBRARY) を参照すべきと思います。（これらの値は /usr/lib/python2.6/config/Makefile の中で設定されています。）
Cygwinとそれ以外で、DLLLIBRARYとINSTSONAMEを切り替えるのをどのように書くべきかが分かっていません。

**Comment by h-east** [comment]
srcの下に `Make_cyg.mak` があるんですが、もしかして通常はこれを使うのではないすかね？

**Comment by h-east** [comment]
あー、Make_cyg.makの冒頭にこれ書いてあるから、やっぱ configure 使うのが正解ですね。すまそ。

> This compiles Vim as a Windows application.  If you want Vim to run as a
> Cygwin application use the Makefile (just like on Unix).

**Comment by koron** [comment]
まず大前提として*/dynはWindows向けの機能です。一方CygwinがUNIXなのかWindowsなのかは微妙なところで、configure使ったときはUNIX的にmakeされると考えるのが自然で、Make_cyg.makを使ったときはWindows的になるのでは。

なのでconfigure使った時には*/dynは正しく機能しないんじゃないでしょうか。

*/dynはMSVC用に作成されたので、たぶんMinGWくらいまでがサポートすべき境界でしょう。

**Comment by koron** [comment]
これWindowsのバグとは言いがたいです。むしろUNIXのバグ。

**Comment by k-takata** [comment]
./configure --help とすると、

```
  --enable-perlinterp=OPTS     Include Perl interpreter.  default=no OPTS=no/yes/dynamic
  --enable-pythoninterp=OPTS   Include Python interpreter. default=no OPTS=no/yes/dynamic
  --enable-python3interp=OPTS   Include Python3 interpreter. default=no OPTS=no/yes/dynamic
  --enable-rubyinterp=OPTS     Include Ruby interpreter.  default=no OPTS=no/yes/dynamic
```

と出ます。*/dyn は元々Windows向けに作られたのかもしれませんが、Windows専用というわけではないでしょう。
先ほど、Linuxでも動作を試してみましたが、+python では、pythonの.soが無いと起動できませんでしたが、+python/dyn であれば、.soが無くとも起動でき、期待通りの動作をしました。

少なくとも +ruby/dyn に関しては Cygwin でも期待通り動作しましたし、+python/dyn に関してもDLLの名前さえ（手で）修正すれば期待通り動作しました。

**Comment by koron** [comment]
ということは内部的に*/dynには実装がWindows系とUNIX系があるのでしょうね。

それでCygwinのconfigureを使ったときはUNIX系が選択されているが、
その実装に不備がある、ただしくはCygwin(Windows)との相性がよろしくない形になっていると。

**Comment by k-takata** [comment]
その通りだと思います。
で、+python/dyn に関しては、最初に書いたように configure.in 内の python_INSTSONAME (or python3_INSTSONAME) の設定の部分さえCygwinと他のUnix系で分岐できれば良いはずです。
（configure や GNU make の書き方がよく分かっていないのでどう書くべきか分かっていませんが。）
+perl/dyn の方は .xs の仕組みが全く分かっていないため、お手上げです。

**Comment by k-takata** [comment]
+python/dyn に関しては次のパッチでうまくいきそうです。autoconf で src/auto/configure を更新する必要があります。

``` patch
diff -r b47bfbb388b1 src/configure.in
--- a/src/configure.in  Sat Sep 15 22:32:20 2012 +0900
+++ b/src/configure.in  Sun Sep 16 23:25:26 2012 +0900
@@ -889,6 +889,7 @@
    @echo "python_LIBS='$(LIBS)'"
    @echo "python_SYSLIBS='$(SYSLIBS)'"
    @echo "python_LINKFORSHARED='$(LINKFORSHARED)'"
+   @echo "python_DLLLIBRARY='$(DLLLIBRARY)'"
    @echo "python_INSTSONAME='$(INSTSONAME)'"
 eof
        dnl -- delete the lines from make about Entering/Leaving directory
@@ -909,6 +910,9 @@
        fi
    ])

+   if test "X$python_DLLLIBRARY" != "X"; then
+     python_INSTSONAME="$python_DLLLIBRARY"
+   fi
    PYTHON_LIBS="${vi_cv_path_python_plibs}"
    if test "${vi_cv_path_python_pfx}" = "${vi_cv_path_python_epfx}"; then
      PYTHON_CFLAGS="-I${vi_cv_path_python_pfx}/include/python${vi_cv_var_python_version} -DPYTHON_HOME=\\\"${vi_cv_path_python_pfx}\\\""
@@ -1082,6 +1086,7 @@
    @echo "python3_BASEMODLIBS='$(BASEMODLIBS)'"
    @echo "python3_LIBS='$(LIBS)'"
    @echo "python3_SYSLIBS='$(SYSLIBS)'"
+   @echo "python3_DLLLIBRARY='$(DLLLIBRARY)'"
    @echo "python3_INSTSONAME='$(INSTSONAME)'"
 eof
           dnl -- delete the lines from make about Entering/Leaving directory
@@ -1094,6 +1099,9 @@
           vi_cv_path_python3_plibs=`echo $vi_cv_path_python3_plibs | sed s/-lffi//`
       ])

+      if test "X$python3_DLLLIBRARY" != "X"; then
+   python3_INSTSONAME="$python3_DLLLIBRARY"
+      fi
       PYTHON3_LIBS="${vi_cv_path_python3_plibs}"
       if test "${vi_cv_path_python3_pfx}" = "${vi_cv_path_python3_epfx}"; then
         PYTHON3_CFLAGS="-I${vi_cv_path_python3_pfx}/include/python${vi_cv_var_python3_version}${vi_cv_var_python3_abiflags} -DPYTHON3_HOME=L\\\"${vi_cv_path_python3_pfx}\\\""
```

（タブは4文字に展開されて表示されてしまう？）
（9/17 10:08 +python3/dynのパッチが間違っていたので修正。）

**Comment by k-takata** [comment]
+perl/dyn は、Linux でも同じようです。
Ubuntu 12.04 で --enable-perlinterp=dynamic で configure して make し、objdump で確認すると、libperl.so.5.14 が必須な状態になっていました。

```
$ objdump -p ./vim | grep perl
  NEEDED               libperl.so.5.14
```

**Comment by ynkdir** [comment]
-DOLD_PTHREADS_API で動くみたいですがなんかあやしいです。

関係ないですが vista + msvc10 + active perl 5.16 は :perl 実行で落ちました。

**Comment by koron** [comment]
> 関係ないですが vista + msvc10 + active perl 5.16 は :perl 実行で落ちました。

一応issue起こしてもらえます? 手元の5.14では問題なさそうです。

**Comment by ynkdir** [comment]
了解です。

**Comment by koron** [comment]
@ynkdir thanks!

**Comment by k-takata** [comment]
Cygwin では、+perl/dyn は次のパッチでうまくいっているようです。
Linux での動作は未確認、Perl のバージョンチェックがこれで合っているかどうかも未確認です。

``` diff
diff --git a/src/if_perl.xs b/src/if_perl.xs
--- a/src/if_perl.xs
+++ b/src/if_perl.xs
@@ -225,6 +225,9 @@
 # define Perl_call_list dll_Perl_call_list
 # define Perl_Iscopestack_ix_ptr dll_Perl_Iscopestack_ix_ptr
 # define Perl_Iunitcheckav_ptr dll_Perl_Iunitcheckav_ptr
+# if (PERL_REVISION == 5) && (PERL_VERSION >= 14)
+#  define PL_thr_key *dll_PL_thr_key
+# endif

 /*
  * Declare HANDLE for perl.dll and function pointers.
@@ -336,6 +339,9 @@
 static SV* (*Perl_Isv_yes_ptr)(register PerlInterpreter*);
 static void (*boot_DynaLoader)_((pTHX_ CV*));
 static perl_key* (*Perl_Gthr_key_ptr)_((pTHX));
+#if (PERL_REVISION == 5) && (PERL_VERSION >= 14)
+static perl_key* dll_PL_thr_key;
+#endif

 /*
  * Table of name to function pointer of perl.
@@ -454,6 +460,9 @@
     {"Perl_Gthr_key_ptr", (PERL_PROC*)&Perl_Gthr_key_ptr},
 #endif
     {"boot_DynaLoader", (PERL_PROC*)&boot_DynaLoader},
+#if (PERL_REVISION == 5) && (PERL_VERSION >= 14)
+    {"PL_thr_key", (PERL_PROC*)&dll_PL_thr_key},
+#endif
     {"", NULL},
 };

```

**Comment by ynkdir** [comment]
おつかれさまです。
ubuntuで動作確認しました。okです。

**Comment by k-takata** [comment]
動作確認ありがとうございます。vim_devに投げました。

+python/dyn does not work on Cygwin
https://groups.google.com/d/topic/vim_dev/WsRO0sfHF8M/discussion

+perl/dyn does not work well on Cygwin and Linux
https://groups.google.com/d/topic/vim_dev/JEPdD-EMAp4/discussion

**Comment by k-takata** [comment]
7.3.668, 7.3.669で取り込まれました。早っ！
