### ISSUE TITLE
Windows で ActivePerl 5.16 を使うと落ちる

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#254]
Vista + ActivePerl 5.16.1.1601 + msvc10 でコンパイルした vim で `:perl` コマンドを実行すると落ちます。
静的リンクと動的リンク両方。

perl 5.14 は大丈夫です。

Linux は perl 5.16 の環境を持ってないので試してません。

**Comment by ynkdir** [comment]
Ubuntu で perl 5.16 をビルドして試してみましたが大丈夫でした。
perlxxx.so をビルドする方法がわからなかったので静的リンクだけ。

Windows で mingw でビルドすると落ちませんでした。
mingw + msvcr100 でビルドすると落ちたので
msvcrt のバージョン不一致が原因ぽい気がします。
ので閉じます。

**Comment by koron** [comment]
つまり ActiveState の Perl 5.16 が MinGW でコンパイルされているってことかしら?

あとその理由が正しいとして、どうして 5.14 までは大丈夫だったのか? 5.14 まではMSVC10でコンパイルされていたけど、5.16 からは MinGW に変わったってのはちょっと考えにくいんだけど…

**Comment by koron** [comment]
とりあえず wontfix としておきます。

**Comment by ynkdir** [comment]
ActiveState は msvcrt.dll を使ってるみたいですね。
mingw か msvc かはわかりませんが。
perl5.14 + msvcr100 がなんで大丈夫なのかはなぞですね…。
テストは単に :perl VIM::Msg(...) を実行してみただけなので、一見大丈夫なようで実際に使ってみると実は問題ありという可能性もあります。

**Comment by ynkdir** [comment]
http://www.nntp.perl.org/group/perl.xs/2011/08/msg2644.html
たぶんこれと同じ。

-D_USE_32BIT_TIME_T を追加で動くようになりました。

msvc8 (visual studio 2005) から time_t はデフォルトで 64bit になったのでそのせいだったみたいです。
ほかにもなにかあるかもしれませんね。

**Comment by ynkdir** [comment]
いやでもそれだと5.14でも動かないはず。
やっぱりたまたま動いてただけかなあ。

**Comment by koron** [comment]
> perl5.14 + msvcr100 がなんで大丈夫なのかはなぞですね…。

それぞれの世界で作った(特殊な)ものを反対側に持って行くことがなければ基本は動きますよね。5.16で落ちる瞬間をデバッガで捕まえれば良いのかしら?

**Comment by ynkdir** [comment]
if_perl.xs から生成された if_perl.c には以下のコードが含まれていて

``` c
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
```

5.14 だと call_list() が呼ばれなくて 5.16 だと呼ばれます。
5.14 でもこれを呼ぶようにすると落ちます。

PL_xxx はマクロで `((PerlInterpreter*)context)->Iunitcheckav` みたいなコードに展開される。
PerlInterpreter 型は time_t 型のメンバを持っている。
Iunitcheckav は time_t 型のメンバの後ろにある。
activeperl で使ってる time_t 型は 32bit。 msvc10 の time_t 型は (デフォルトでは) 64bit。
なので call_list にずれたポインタが渡される。
ということだと思いますたぶん。

といわけで time_t 型のメンバよりも後ろの PL_xxx を参照しているコードは 5.14 でも動かないです。
例えば `:perldo $_ = 'xxx'`。

なんで unitcheck 呼ばれるようになったかはこれっぽい気がしますがよくわかりません。

http://perldoc.perl.org/perl5160delta.html

```
Special blocks called in void context

Special blocks (BEGIN , CHECK , INIT , UNITCHECK , END ) are now called in void context. This avoids wasteful copying of the result of the last statement [perl #108794].
```

**Comment by ynkdir** [comment]
いや 5.14 でも 5.16 でも context->Iunitcheckav は間違った場所を指してるから
call_list が呼ばれるかどうかはたまたま違いがでただけか

**Comment by koron** [comment]
いずれにせよVimのコンパイル時に

> -D_USE_32BIT_TIME_T を追加で動くようになりました。

これを付けるべきですね?

**Comment by ynkdir** [comment]
んーそうですね
他に影響がなければ…
なんとも言えませんね…

**Comment by ynkdir** [comment]
64bit windows はどうなるんだろ

**Comment by ynkdir** [comment]
vim-jp のバイナリ配布的には Strawberry Perl と ActiveState Perl が動かないととりあえずダメですよね

**Comment by ynkdir** [comment]
まあ影響するとすれば if_xxx くらいですし
どっちみちバイナリ互換てきに全部は対応できないのでとりあえず `-D_USE_32BIT_TIME_T` をつけとくのがいい気がします。

**Comment by koron** [comment]
> vim-jp のバイナリ配布的には Strawberry Perl と ActiveState Perl が動かないととりあえずダメ

どっちか一般的なほうだけにしたいなw

> バイナリ互換てきに全部は対応できないので

Python や Ruby あたりと喧嘩して涙目な展開が予想できますねw どこかで64bit化しとかんと2038年問題が… (´・ω・`)

**Comment by ynkdir** [comment]
あーそっか python の公式バイナリは msvc ビルドか。
if_python と if_ruby は time_t のサイズが影響しそうなとこはぱっと見ないのでかろうじて大丈夫だとは思いますがまー心配ですね。
逆に言えばmingwでビルドしたvimでif_pythonやif_rubyが動かないということもあるはずですがそういう話は聞きませんね。

**Comment by ynkdir** [comment]
Building on Windows 7 - Perl crashes
https://groups.google.com/d/topic/vim_dev/30UmOJhYY_M/discussion

これも同じ問題かなぁ

**Comment by ynkdir** [comment]
ちがった。これは 7.3.623 だ。

**Comment by ynkdir** [comment]
いややっぱりおんなじだ。
7.6.623 はworkaroundで対処してる。
構造体直アクセスから関数呼び出しでのアクセスに変更か。
これで全部書き換えるのは大変だなぁ。

**Comment by koron** [comment]
> 構造体直アクセスから関数呼び出しでのアクセスに変更か。
> これで全部書き換えるのは大変だなぁ。

でもやっといたほうが安全?

> 64bit windows はどうなるんだろ

やってみた。コンパイルエラーになった。

**_USE_32BIT_TIME_T と _WIN64 の両方を定義することはできません。**

詳細はココ http://msdn.microsoft.com/ja-jp/library/bb763169(VS.90).aspx

**Comment by koron** [comment]
64bit版はUSE_32BIT_TIME_T使わなくても問題なく動作した。設定できない以上、当然の結果だけど。

**Comment by koron** [comment]
とりあえず次から32bit版は _USE_32BIT_TIME_T 付けます。そしてActivePerl 5.16.1にアップデート。

**Comment by ynkdir** [comment]
> >   構造体直アクセスから関数呼び出しでのアクセスに変更か。
> >   これで全部書き換えるのは大変だなぁ。
> 
> でもやっといたほうが安全?

``` c
#ifdef AVOID_PL_ERRGV
    err = SvPV(perl_get_sv("@", GV_ADD), length);
#else
    err = SvPV(GvSV(PL_errgv), length);
#endif
```

7.3.623 ではこういう感じで置き換えてますが、
PL_errgv => perl_get_errgv() みたいな単純な変更ではないのでこの方法で直すのはもしかしたら無理かもしれないです。
自動生成される分もあるのでなかなか厳しいと思います。

> 64bit版はUSE_32BIT_TIME_T使わなくても問題なく動作した。設定できない以上、当然の結果だけど。

64bit は大丈夫なんですね。よかった。

**Comment by koron** [comment]
7 .3.666、PerlとLuaをバージョンアップして出しちゃったw

**Comment by k-takata** [comment]
ActivePerl 5.14 32bit版は（おそらく）MSVC6でビルドされてます。PEヘッダのlinker versionが6.0になっているので。
MinGWだと2.22とかになっているはずです。(binutilsのバージョンかな?)

perl.h（あるいはif_perl.xs）だけ _USE_32BIT_TIME_T でコンパイルすることは可能なのかどうなのか…。

**Comment by koron** [comment]
すでに32bit版については全部 `_USE_32BIT_TIME_T` しちゃってますw

**Comment by ynkdir** [comment]
Windows Compilers for Perl Modules
http://community.activestate.com/faq/windows-compilers-perl-modules

x86=VC6
x64=Windows 2003 Platform SDK
のようです。

**Comment by koron** [comment]
VC6…だと…?

**Comment by k-takata** [comment]
ちゃんと公式に書いてあったんですね。

**Comment by koron** [comment]
まとめ。

Win 32bit では _USE_32BIT_TIME_T=1 でコンパイルしないとコケることがある。
だから vim-dev に反映させたほうが良い (ゴール)

**Comment by k-takata** [comment]
Vim 7.4a の公式バイナリは VC9 でビルドされており、(Active?)Perl 5.14にリンクしているので、この問題に引っかかりますね。

> 例えば `:perldo $_ = 'xxx'`。

確かに動きませんでした。落ちはしませんでしたが。

**Comment by k-takata** [comment]
直すならこんな感じでしょうか。
https://bitbucket.org/k_takata/vim-win32-mq/src/2c01d7a9f0015a4e8ab98202472b3852d47f2885/use_32bit_time_t.patch

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/bZuA4g7cJuM/discussion

**Comment by k-takata** [comment]
> OK.  Is _USE_32BIT_TIME_T only used by Perl or does it affect the whole
> of Vim?
> 
> Would there be a way to handle it in the code somehow, with
> sizeof(time_t)?

まあ、当然そういう疑問は出ますわなあ。

**Comment by k-takata** [comment]
if_perl.xs だけ _USE_32BIT_TIME_T するパッチを作ってみました。
https://bitbucket.org/k_takata/vim-win32-mq/src/762f44d868d5e67714b694a9df20840dc604d810/use_32bit_time_t-only-in-if_perl.patch
どっちがいいだろう？

**Comment by ynkdir** [comment]
おつかれさまです。

ソースで定義するよりはメイクファイルで対応するほうがよさげな気がします。

結局応急処置しかできないので
個人的には既知の問題としてどこかに書いといてお茶をにごすのが無難かなあという気もしますが
まあむずかしいとこですね・・・

**Comment by k-takata** [comment]
> ソースで定義するよりはメイクファイルで対応するほうがよさげな気がします。

あー、そのまま投げちゃいました。その方が良かったかも。

**Comment by k-takata** [comment]
7.4b.007 で、if_perl.xs だけ _USE_32BIT_TIME_T するパッチが採用されました。
https://groups.google.com/d/topic/vim_dev/MBVyUs-AwhI/discussion

**Comment by k-takata** [comment]
ActivePerl 5.16まではVC6でビルドされていましたが、ActivePerl 5.18はMinGWでビルドされていることが分かりました。
https://groups.google.com/d/topic/vim_dev/YWnfI9wFFoA/discussion
今後、VCで if_perl を有効にしてビルドするのは面倒になるかもしれません。

**Comment by koron** [comment]
まじか…めんどいなぁ。

**Comment by k-takata** [comment]
上記スレに書いたように、if_perl.xs の修正以外に、`C:\Perl\lib\CORE\config.h` に1カ所パッチを当てる必要がありました。

**Comment by k-takata** [comment]
既に本題からずれてしまっていますが、ActivePerl 5.18対応のパッチが 7.4.117, 7.4.120 でマージされました。
https://groups.google.com/d/topic/vim_dev/9jQN82LU-9k/discussion
https://groups.google.com/d/topic/vim_dev/wCHEgf8E9DQ/discussion
VCでビルドする際、ActivePerlのヘッダにパッチを当てる必要がある点は変わっていません。

``` diff
--- C:\Perl\lib\CORE\config.h.org        Sat Nov 30 04:07:14 2013
+++ C:\Perl\lib\CORE\config.h        Sat Nov 30 04:31:24 2013
@@ -2441,7 +2441,7 @@
  *                static              (c89 compilers)
  */
 #define HAS_STATIC_INLINE                                /**/
-#define PERL_STATIC_INLINE static __inline__        /**/
+#define PERL_STATIC_INLINE static __inline        /**/

 /* USE_STDIO_PTR:
  *        This symbol is defined if the _ptr and _cnt fields (or similar)
```

**Comment by koron** [comment]
これってVim側でそのヘッダを include するまえに諸々の条件判断した上で

``` c
#define __inline__   __inline
```

するんじゃダメなんですが?

**Comment by koron** [comment]
もしくはincludeした直後に

``` c
#undef PERL_STATIC_INLINE
#define PERL_STATIC_INLINE static __inline
```

**Comment by k-takata** [comment]
> `#define __inline__   __inline`

soreda!

**Comment by k-takata** [comment]
7.4.128で取り込まれました。
https://groups.google.com/d/topic/vim_dev/tIkBllCXSVk/discussion
これでVCでもそのままビルドが通るようになりました。

**Comment by k-takata** [comment]
> 7.4b.007 で、if_perl.xs だけ _USE_32BIT_TIME_T するパッチが採用されました。

7.4.1925 で問題が起きてしまいました。場当たり的なパッチは作ってみましたが、どうしたものだか。
https://groups.google.com/d/msg/vim_dev/7A2AVxlL0LY/pvSFn12lKAAJ

**Comment by k-takata** [comment]
もうちょっとまともなパッチ。
https://groups.google.com/d/msg/vim_dev/7A2AVxlL0LY/f01LwCS3KAAJ

**Comment by koron** [comment]
reopen、もしくは別issue建てなくて良いですか?

**Comment by k-takata** [comment]
reopenしておきます。

**Comment by k-takata** [comment]
7.3.623 を元に戻すパッチも送付。
https://groups.google.com/d/msg/vim_dev/7A2AVxlL0LY/noVjkAEJKQAJ

**Comment by k-takata** [comment]
7.4.1955 (time_t サイズ不一致の対処)
https://groups.google.com/d/topic/vim_dev/oRtzhR-ER0Y/discussion
7.4.1957 (7.3.623 を元に戻す)
https://groups.google.com/d/topic/vim_dev/BFve1dQT2_g/discussion
7.4.1958 (if_perl.xs インデント修正)
https://groups.google.com/d/topic/vim_dev/CmkQv3d7nCc/discussion

**Comment by k-takata** [comment]
7.4.1955  で、VCを使う場合は、VC2005が必須になりました。
