### ISSUE TITLE
Windowsでenc=utf-8の時、ファイル名に日本語を含むファイルを編集すると、スワップファイルが削除されない

### ISSUE THREAD

**Issue by sgur** [vim-jp/issues#257]
Windows でしか検証していないため、他の環境で発生するかは未確認です。

デフォルトでは、なにかファイルを開くと同じディレクトリにスワップファイルが作成され、スワップファイルはVimの終了時に削除されます。

しかし、`set encoding=utf-8`の状態でファイル名に日本語を含むファイルを開いた場合、スワップファイルが Vim の終了時に削除されず残ってしまいます。

また、ファイル名に日本語を含むファイルを開いた状態で`:e`しただけで、スワップファイルが見つかった旨のメッセージが表示されてしまいます。

**Comment by koron** [comment]
さしずめ、スワップファイルの取り扱い部分にエンコード変換が入ってない、っていうところかしらね。

私もenc=utf-8で常用しているけど、日本語を含むファイル名を取り扱わないので気が付かなかった。

**Comment by koron** [comment]
いま、ざっくり手元でやってみたらちゃんと消えた。なんか消えないトリガーが別にあるかも。

@sgur: プラグインや設定を消した素の状態でなるか確認してもらえませんか。あとどのようなファイル名でやったのかも教えてください。

**Comment by sgur** [comment]
kaoriya版を使ったところ、再現しませんでした。

手元でビルドするときにあてたパッチが影響しているようなので、もう少し調査します。

**Comment by sgur** [comment]
手元での再現条件がわかりました。

#241 の [symlinkfix-update.diff](https://gist.github.com/3436380/) のパッチを適用していると再現するようです。パッチ詳しく読んでないのでどこが原因かはわかりませんが…

**Comment by k-takata** [comment]
まだ詳しくは調べていませんが、私が修正する前の symlinkfix.diff でもダメなようです。

**Comment by k-takata** [comment]
あああ、mch_remove() がマルチバイトに対応していませんｗ

**Comment by koron** [comment]
www

**Comment by k-takata** [comment]
パッチを当てる前から mch_remove() がマルチバイトに対応していなかったのに、何で今まで問題が起きていなかったのかが分からないですね。別の方法で削除していたのでしょうか。

**Comment by k-takata** [comment]
パッチを更新しました。mch_remove() のマルチバイト対応と win32_setattrs() の戻り値がおかしかったのを修正です。win32_setattrs() の戻り値は使われていませんが。

**Comment by ynkdir** [comment]
オリジナルの mch_remove() はもともと DeleteFileW() を使ってます。
新しいパッチは同じコードを書き直す感じになってます。

**Comment by k-takata** [comment]
あ、確かにそうですね。見落としてました。
オリジナルのコードを生かす形で、再修正します。

**Comment by k-takata** [comment]
修正パッチを投げました。
https://groups.google.com/d/msg/vim_dev/qF8Y3xtUP-w/bJ7hWYgakxUJ

**Comment by sgur** [comment]
修正を確認しました。

**Comment by h-east** [comment]
クローズされていたのですがxlose属性ラベルが付けられていなかったので、xlose/duplicatedラベルを付けました。(#241 と重複)
(#241 は2012/9にtodoリスト入り)
