### ISSUE TITLE
:cwindow で quickfix ウィンドウが開かない

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#258]
quickfix にデータが出力されている場合に :cwindow で quickfix ウィンドウが開きません。
日本語の help には

```
認識されたエラーがあるときQuickFixウィンドウを開く。
```

と、記述されているのですが、認識されたエラーとは具体的にどこを参照しているのでしょうか。
- 再現コード

```
cgetexpr "homuhomu"
cwindow
```

上記の場合ですと、`:copen` では quickfix ウィンドウが開き "homuhomu" が表記されます。
また `getqflist()` でもデータの取得が行えます。
- vim-version

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Sep 20 2012 23:03:48)
MS-Windows 32 ビット GUI 版
適用済パッチ: 1-666
```

**Comment by ynkdir** [comment]
認識されたエラーは 'errorformat' にマッチしたものということだと思います。

例えば

``` vim
:set errorformat=homuhomu
:cgetexpr "homuhomu"
:cwindow
```

で開きます。

**Comment by koron** [comment]
@ynkdir: つまり **quickfix(が利用しているコンパイラや実行系)が吐くエラーがerrorformatにマッチしていなかった** ということ?

**Comment by osyo-manga** [comment]
あーなるほどそういう事でしたか。
ありがとうございました。

**Comment by koron** [comment]
xlose/invalid で閉じときます。

**Comment by h-east** [comment]
`:help getqflist()` の真ん中あたり

```
    valid   0以外: エラーメッセージが認識されている
```

とあります。では、「認識されていない状態」というのはどういう状態かというのは
`:help setqflist()` の真ん中あたりに書かれています。

```
    "filename" と "bufnr" の両方ともない場合、また
    は "lnum" と "pattern" の両方ともない場合、その要素はエラー行
    として扱われない。
```

このことから、「認識されている状態」というのは
QuickFixリスト中に1つでも以下の条件の要素が存在することになります。
- "filename" か "bufnr" がセットされている。かつ、"lnum" か "pattern" がセットされている。<p>
  （条件が合致すると "valid" が 1 になる）

<nr>
再現コードの直後に getqflist() を実行すると "valid" が 0 なので「認識されていない状態」というのが分かります。

``` vim
:cgetexpr "homuhomu"
:echo getqflist()
[{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'homuhomu'}]
```

ここでQuickFixリストに認識される要素に無理やり変更してみます。

``` vim
:let ql = getqflist()
:let ql[0].lnum = 1
:let ql[0].bufnr = 1
:call setqflist(ql)
:echo getqflist()
[{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'type': '', 'pattern': '', 'text': 'homuhomu'}]
```

"valid" が 1 になったのでQuickFixリストとしては「認識されている状態」となりました。
これで `:cwindow' を実行するとquickfix ウィンドウが開きます。

以上、QuickFixリストの認識されている/されていない のお話でした。

どうして`:cwindow' だけこんな制限が付いているんでしょうね？。
場合によってはソース修正が必要？？

**Comment by h-east** [comment]
わー、クローズされてたｗｗ

**Comment by koron** [comment]
@h-east: ごめんwww

**Comment by osyo-manga** [comment]
丁寧にありがとうございます＞＜

**Comment by h-east** [comment]
しかもynkdirさんの回答が的確。

**Comment by k-takata** [comment]
> xlose/invalid で閉じときます。

仕様だったという場合は worksforme または wontfix の方が適切だと思います。
worksforme に変更しておきます。
