### ISSUE TITLE
 IMEに設定するフォント

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#259]
Windowsにてguifontとguifontwideを指定した場合、IMEに設定されるフォントは前者のものになるらしい。そのため日本語が設定されてないフォントをguifontに指定した場合、入力中の未確定文字のサイズが崩れてとても悲しい気分になる。Windows的にはフォントリンクを正しく設定しろという話なのかもしれないが、Vimにguifontwideの設定がある以上それを有効活用する形の解法があっても良い気がした。

guifontwide指定時にはIMEに対してguifontより優先して設定する、というアイデアについて意見を聞かせてください。

**Comment by koron** [comment]
ちなみに私自身は普段 guifontwide 使わないのでまず困らない。

**Comment by Shougo** [comment]
guifontwideを使用していますが、この問題には気づきませんでした。

> guifontwide指定時にはIMEに対してguifontより優先して設定する、というアイデアについて意見を聞かせてください。

guifontwideはマルチバイト文字用のフォントなので、マルチバイトが表示されると思われるIME入力時に使用されるという仕様はとても自然だと思います。

**Comment by koron** [comment]
> guifontwideを使用していますが、この問題には気づきませんでした。

参考までに普段使っているguifontとguifontwideの値を教えてもらえますか?

**Comment by Shougo** [comment]
Linux 用：

```
  " For Linux.
  set guifontwide=VL\ Gothic\ 11
  set guifont=Courier\ 10\ Pitch\ 11
```

Windows用：

```
  "set guifontwide=VL\ Gothic:h11
  "set guifontwide=MigMix\ 1M:h11
  set guifontwide=Ricty:h12

  set guifont=Ricty:h12
  "set guifont=Anonymous\ Pro:h11
  "set guifont=Courier\ New:h11
  "set guifont=MS\ Gothic:h11
  "set guifont=VL\ Gothic:h11
  "set guifont=Consolas:h12
  "set guifont=Bitstream\ Vera\ Sans\ Mono:h11
  "set guifont=Inconsolata:h12
  "set guifont=Terminal:h10:cSHIFTJIS
```

Windowsではguifontwideをあまり活用できていないですね。

**Comment by koron** [comment]
> set guifont=Inconsolata:h12

この設定を有効化すると、問題がよくわかる予感w

**Comment by Shougo** [comment]
確かに、IMEのフォント問題があって無効化したのかもしれないです。

**Comment by sgur** [comment]
自分はWindowsでもguifont=Ubuntu_Mono, guifontwide=IPAゴシックを利用しているので、この問題は是非とも解決してもらいたいです。
確かに fontlink すれば済みますが、すべてのVimユーザがレジストリをいじれる権限をもっているとは限りませんし。

**Comment by koron** [comment]
とりあえずパッチ作ってみた。

https://gist.github.com/3805843

**Comment by koron** [comment]
もう送っちゃった。
https://groups.google.com/forum/?fromgroups=#!topic/vim_dev/wcfcPZg8M2k

**Comment by k-takata** [comment]
todo.txt入りしていますので、閉じておきます。

> Win32: use 'guifontwide' for IME composition. (Taro Muraoka, 2012 Sep 30)
> Update Oct 2.

**Comment by k-takata** [comment]
パッチを見ると、update_im_font() の中で get_logfont() を呼んでLOGFONTを生成していますが、gui.wide_font から GetObject() を使って取得する方がすっきりしているのではないかと思いました。

**Comment by koron** [comment]
こっそり修正しておきますかw

**Comment by thinca** [comment]
7.3.782 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/hXFW0uLiFWc/discussion

**Comment by k-takata** [comment]
7.3.784 で追加修正が取り込まれました。
https://groups.google.com/d/topic/vim_dev/YmooQYmuP4Y/discussion
(after 7.3.781) と書かれているが、 (after 7.3.782) の間違いのはず。
