### ISSUE TITLE
ユーザ定義補完のポップアップが出ているとき、<C-u>のマッピングがVimに取られてしまう

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#26]
表題の通りです。ユーザー定義補完のポップアップが出ているとき、&lt;C-u&gt;は次の候補の選択に強制的に割り当てられ、事実上、ユーザーのマッピングや行頭まで削除の機能が無効化されてしまいます。
おそらく、&lt;C-x&gt;&lt;C-u&gt;を使ったとき、&lt;C-u&gt;を連続で押して選択できるように、という配慮じゃないかと思いますが、個人的に邪魔と感じることが多く、便利でないです。
せめてオプションで無効化できるようにするのが良いのではないかと思うのですが、どうでしょうか？

**Comment by mattn** [comment]
#25 と同じだと思います。

**Comment by Shougo** [comment]
はい。そうですね。そこの特殊なモードのマッピングをユーザーが指定できないので、困ってしまいます。
これは#25と同じで、根本的な改修がいるのかもしれません。

**Comment by mattn** [comment]
#25 と同件なのでこちらはcloseします。

**Comment by Shougo** [comment]
はい。OKです。
