### ISSUE TITLE
if_python のおかしな挙動

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#264]
見つけたので。。。

[Vim] if_python のおかしな挙動 - ゆり日記
http://d.hatena.ne.jp/chikatoike/20120929/1348969103

``` vim
:py import vim
:py print(vim.eval("matchstr('', 'x')"))
None
```

``` vim
:py import vim
:py vim.bindeval("matchstr('', 'x')")
SEGV
```

**Comment by ynkdir** [comment]
報告しました。

https://groups.google.com/d/topic/vim_dev/TjWvvFLYTgo/discussion

**Comment by h-east** [comment]
おつかれさまです。

**Comment by h-east** [comment]
早速 Patch 7.3.683 で入りました。
https://groups.google.com/d/topic/vim_dev/uqzR7vJFTuU/discussion

**Comment by ynkdir** [comment]
ありがとうございます。
