### ISSUE TITLE
autofmt を vim-jp に置きたい

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#265]
というわけで置かせていただきます。
なにかありましたら勝手に変更してください。
よろしくお願いします。

**Comment by koron** [comment]
License だけは追加で記載しとくと良いかも。

**Comment by ynkdir** [comment]
了解です。readmeに書きました。とりあえずpublic domainです。

**Comment by thinca** [comment]
これはもうcloseして良い?

**Comment by ynkdir** [comment]
すみません。閉じます。
