### ISSUE TITLE
rN が効かない？

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#267]
ノーマルモードで rN ってやっても効かない。誰か再現する人います？

**Comment by h-east** [comment]
7.3.704から7.3.709で発生します。
7.3.710で治りました。

**Comment by koron** [comment]
まっつんさん、仕事で忙しくて気が付かなったと見たw

**Comment by h-east** [comment]
クローズしますね。
後で関連するvim_devの投稿のリンクを貼っときますわ。(今、移動中)

**Comment by mattn** [comment]
うひ

**Comment by h-east** [comment]
Problem by updating from 692 to 709
https://groups.google.com/d/topic/vim_dev/lk3haSrg8cY/discussion
Issue 88 in vim: fn; jumps to top of document
https://groups.google.com/d/topic/vim_dev/Jq7MqquyXX8/discussion
要は7.3.704で`gn`と`gN`時に特別な処理をさせるような条件を追加したけど、`cmdchar`のチェックをしてなかったのでノーマルコマンドで第一パラメータが n か N の場合(fn, fN, tn, TN, rn, rN 等)もその条件に当てはまってしまってoh...ってことでした。

Patch 7.3.710 でfixされました。
https://groups.google.com/d/topic/vim_dev/jDopV6Jm7Jc/discussion
