### ISSUE TITLE
Concealがあると折り返し位置が変

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#268]
英語版のヘルプの `:diffpatch` を見ると変な場所で折り返されてしまう。
以下の例は columns=80 時

期待する見え方

```
:diffp[atch] {patchfile}                 E816 :diffp :diffpatch
```

実際の見え方

```
:diffp[atch] {patchfile}                 E816 :diffp :diffp
atch
```

本来は折り返しが必要ないのに、実際よりも左側で折り返されてしまっている。
おそらく折り返し位置の計算にconcealされた文字数が換算されていない。

**Comment by h-east** [comment]
#115 もconceal絡み。

**Comment by mattn** [comment]
治ってると思う

![](http://go-gyazo.appspot.com/ff3393b8e042a037.png)

**Comment by k-takata** [comment]
私のところだと直っていません。
7.3.751で以下のようになります。（←の部分で80桁）

:se cole=0

```
:diffp[atch] {patchfile}                                 *E816* *:diffp* *:diffp←
atch*
```

:se cole=2

```
:diffp[atch] {patchfile}                                 E816 :diffp :diffp     ←
atch
```

**Comment by h-east** [comment]
私のとこでも治ってないです。(fedora16 on PuTTY)
concealが使われている行は、まだ余裕あるのにconnceal非表示文字数分先に改行される感じです。

**Comment by mattn** [comment]
あれ？確認ミスか？

**Comment by itchyny** [comment]
はじめまして.

concealで「えっ」と思い, おそらくこのissueに相当すると思ったので書いておきます.
concealされた文字が, windowの幅より多い時に問題が生じます.

``` sh
vim -N -u NONE -c 'so test.vim'
```

``` vim
" test.vim
echo has('conceal')
syntax enable
set concealcursor+=n
set conceallevel=3
call setline(1, 'l' . repeat('-', 5) . 'r')
call setline(2, 'l' . repeat('-', 20) . 'r')
call setline(3, 'l' . repeat('-', winwidth(0) * 1 - 2) . 'r')
call setline(4, 'l' . repeat('-', winwidth(0) * 1 - 1) . 'r')
call setline(5, 'l' . repeat('-', winwidth(0) * 5) . 'r')
syntax match Con '-' conceal
```

```
lr
lr
lr
lr
lr
```

となるのを期待したのですが,

```
lr
lr
lr
l
r
l



r
```

のようになってしまいます.

また, nowrapの時のカーソルの位置がconceal文字の文を計算していないです.

``` vim
" test.vim
echo has('conceal')
syntax enable
set concealcursor+=n
set conceallevel=3
set nowrap
call setline(1, 'l' . repeat('-', 5) . 'r')
call setline(2, 'l' . repeat('-', 20) . 'r')
call setline(3, 'l' . repeat('-', winwidth(0) * 1 - 2) . 'r')
call setline(4, 'l' . repeat('-', winwidth(0) * 1 - 1) . 'r')
call setline(5, 'l' . repeat('-', winwidth(0) * 5) . 'r')
syntax match Con '-' conceal
call cursor(1, 1)
```

これを読み込むと

```
lr
lr
lr
lr
lr
```

のようになります(OK). 続けて

``` vim
call feedkeys('$jjjj', 'n')
```

すると,

```




r                                              ■
```

のように, カーソルがずれます.

```
lr
lr
lr
lr
lr■
```

となるのを期待します.

**Comment by mattn** [comment]
これ、さっさと報告して7.4出るまでになおしちゃわないとマズくない？

**Comment by ynkdir** [comment]
問題は知ってると思いますよ。
https://groups.google.com/d/msg/vim_dev/ZQTXsL4Tdyg/erjZuCrsPnwJ
https://groups.google.com/d/msg/vim_dev/Npa8ob7Uosg/e4GCQhYmnjQJ

**Comment by k-takata** [comment]
同様のissueがWontFixになっていました。

Issue 260: Concealed text causes vim to wrap before window width
https://code.google.com/p/vim/issues/detail?id=260

> This is how it is expected to work.  Wrapping works on the actual characters, no matter whether they are not visible or replaced by another character.
> It would be possible to add an option to make it behave the other way, but it's going to be a lot of work (and slow).

あと、元々の問題であった `:help :diffpatch` については、すでにヘルプが修正されており、変な位置で折り返さないようになっています。
閉じますか？

**Comment by koron** [comment]
手を付けたい (修正したい) 人がいたら、再開してください。
