### ISSUE TITLE
コマンドが存在しなかった時に実行されるイベントが欲しい

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#269]
未定義の関数が呼ばれた時に実行されるイベントはある。 FunctionUndefined  それのコマンド版が欲しい。 at ujihisa.vim #3

**Comment by tyru** [comment]
ujihisa.vim行ってなかったので分からないんですが、どんな場合に欲しいと思うんでしょうか？

**Comment by koron** [comment]
ちゃんと聞いてなかったんだけど、
多分bashみたいに、インストールすべきパッケージを
サジェストできるんじゃないかな?
2012/11/03 18:32 "tyru" notifications@github.com:

**Comment by tyru** [comment]
なるほど。
まぁ色々と使えそうだし用途は後から考えればいいですね…！(自分で聞いておいて)

**Comment by Shougo** [comment]
まぁ、neobundleで使う場合も、どうやってプラグイン名を検索するのか問題にはなりますが……。
検索するのはプレフィクスを部分マッチ書ければいいか。対応できないケースは手動で登録してもらうしか無い。

**Comment by Shougo** [comment]
考えてみたのですが、コマンドのhookだけだとグローバルなキーマッピングを用意するプラグインに対応できません。
例えばvisual-starとかsmart-word。

プラグインキーマッピングもフックできると、夢が広がるのではないでしょうか。
ただ、優先度的にはコマンド `>>` キーマッピングだと思います。

**Comment by Shougo** [comment]
キーマッピングの件は、本体だと終了判定ができないので厳しそう。neobundle側でマッピングを提議すれば現状のVimでも行けそうなのでちょっとやってみます。

**Comment by Shougo** [comment]
neobundle ver.3 にて、関数・マッピング・filetype・コマンドを事前に登録することによりプラグインを自動的にロードできるようにしました。後は、CommandUndefinedがあればコマンド名をいちいち登録しなくても良くなるのですが……。

**Comment by Shougo** [comment]
neobundleを更に更新し、autoload関数のprefixを登録することで自動ロードが可能になりました。
あとはCommandUndefinedさえあれば……。誰かやってくれませんか？

**Comment by mattn** [comment]
https://gist.github.com/4582948

``` diff
diff -r 5cf390d4fbe1 src/eval.c
--- a/src/eval.c    Thu Jan 17 18:34:06 2013 +0100
+++ b/src/eval.c    Mon Jan 21 10:15:14 2013 +0900
@@ -360,6 +360,7 @@
     {VV_NAME("searchforward",   VAR_NUMBER), 0},
     {VV_NAME("oldfiles",    VAR_LIST), 0},
     {VV_NAME("windowid",    VAR_NUMBER), VV_RO},
+    {VV_NAME("command",         VAR_STRING), VV_RO},
 };

 /* shorthand */
diff -r 5cf390d4fbe1 src/ex_docmd.c
--- a/src/ex_docmd.c    Thu Jan 17 18:34:06 2013 +0100
+++ b/src/ex_docmd.c    Mon Jan 21 10:15:14 2013 +0900
@@ -2145,6 +2145,16 @@
     {
    if (!ea.skip)
    {
+#ifdef FEAT_AUTOCMD
+       if (has_commandnotfound())
+       {
+       set_vim_var_string(VV_COMMAND, *cmdlinep, -1);
+       int ret = apply_autocmds(EVENT_COMMANDNOTFOUND, NULL, NULL, FALSE, curbuf);
+       set_vim_var_string(VV_COMMAND, NULL, -1);
+       if (ret)
+           goto doend;
+       }
+#endif
        STRCPY(IObuff, _("E492: Not an editor command"));
        if (!sourcing)
        append_command(*cmdlinep);
diff -r 5cf390d4fbe1 src/fileio.c
--- a/src/fileio.c  Thu Jan 17 18:34:06 2013 +0100
+++ b/src/fileio.c  Mon Jan 21 10:15:14 2013 +0900
@@ -7658,6 +7658,7 @@
     {"CmdwinEnter",    EVENT_CMDWINENTER},
     {"CmdwinLeave",    EVENT_CMDWINLEAVE},
     {"ColorScheme",    EVENT_COLORSCHEME},
+    {"CommandNotFound",    EVENT_COMMANDNOTFOUND},
     {"CompleteDone",   EVENT_COMPLETEDONE},
     {"CursorHold", EVENT_CURSORHOLD},
     {"CursorHoldI",    EVENT_CURSORHOLDI},
@@ -9143,6 +9144,16 @@
     return (first_autopat[(int)EVENT_INSERTCHARPRE] != NULL);
 }

+/*
+ * Return TRUE when there is an CommandNotFound autocommand defined.
+ */
+    int
+has_commandnotfound()
+{
+    return (first_autopat[(int)EVENT_COMMANDNOTFOUND] != NULL);
+}
+
+
     static int
 apply_autocmds_group(event, fname, fname_io, force, group, buf, eap)
     event_T    event;
diff -r 5cf390d4fbe1 src/proto/fileio.pro
--- a/src/proto/fileio.pro  Thu Jan 17 18:34:06 2013 +0100
+++ b/src/proto/fileio.pro  Mon Jan 21 10:15:14 2013 +0900
@@ -45,6 +45,7 @@
 int has_cursormoved __ARGS((void));
 int has_cursormovedI __ARGS((void));
 int has_insertcharpre __ARGS((void));
+int has_commandnotfound __ARGS((void));
 void block_autocmds __ARGS((void));
 void unblock_autocmds __ARGS((void));
 char_u *getnextac __ARGS((int c, void *cookie, int indent));
diff -r 5cf390d4fbe1 src/vim.h
--- a/src/vim.h Thu Jan 17 18:34:06 2013 +0100
+++ b/src/vim.h Mon Jan 21 10:15:14 2013 +0900
@@ -1300,6 +1300,7 @@
     EVENT_TABENTER,        /* after entering a tab page */
     EVENT_SHELLCMDPOST,        /* after ":!cmd" */
     EVENT_SHELLFILTERPOST, /* after ":1,2!cmd", ":w !cmd", ":r !cmd". */
+    EVENT_COMMANDNOTFOUND, /* command not found */
     NUM_EVENTS         /* MUST be the last one */
 };

@@ -1870,7 +1871,8 @@
 #define VV_SEARCHFORWARD 53
 #define VV_OLDFILES    54
 #define VV_WINDOWID    55
-#define VV_LEN     56  /* number of v: vars */
+#define VV_COMMAND 56
+#define VV_LEN     57  /* number of v: vars */

 #ifdef FEAT_CLIPBOARD
```

**Comment by mattn** [comment]
しかしながら、エラーを握るコマンドはあまり追加したくないな。

**Comment by mattn** [comment]
やるなら汎用的なのが欲しい。

**Comment by koron** [comment]
sha256が混ざってる?

**Comment by mattn** [comment]
たぶんそのコメントを書いた頃に消し去った

**Comment by Shougo** [comment]
> しかしながら、エラーを握るコマンドはあまり追加したくないな。

まぁ、乱用するとRubyのmethod_missingのようになりますからね。
Vimに新しいコマンドを擬似的に追加することも可能になるかもしれません……。

**Comment by mattn** [comment]
個人的には

```
autocmd Error E429 ...
```

みたいな事が出来ればなーとは思います。

**Comment by Shougo** [comment]
確かに、それがあると便利そうですね。

**Comment by Shougo** [comment]
@mattn もう半年経っていますが、このパッチはvim_devに送らないのでしょうか？　プラグインの遅延起動の実装が簡略化されるので、個人的にはとても欲しい機能です。

**Comment by mattn** [comment]
↑に書いた様にアドホックなものよりエラーハンドラ的な物の方がうれしいなーと。

**Comment by Shougo** [comment]
確かにそちらのほうが応用効きそうなのですが、実装に時間がかかりそうに思えたのです。そんなに難しくないのなら、エラーハンドラ的な機能が完成するのを待ちます。

**Comment by Shougo** [comment]
@mattn 

汎用的なエラーハンドラについて考えていました。
アイディア自体は素晴らしいのですが、それを CommandUndefined に対しても適用するのは難しいです。
- CommandUndefinedではFuncUndefinedのように、もしその autocmd 内でコマンドが定義されなかったらエラーになって欲しいですが、汎用的なエラーハンドラだと難しいと思います
- 汎用的なエラーハンドラの場合、autocmd 側にはエラーメッセージしか取れないはずです。存在しなかったコマンド名をエラーメッセージより取得するには autocmd 側でパースするしかありませんが、このエラーメッセージは Vim のロケールによって異なります。パースは困難です

そこで、私は CommandUndefined に関してはこのままの形で vim_dev に提案し、汎用的なエラーハンドラは別 issue で実装を行うべきだと思います。

**Comment by mattn** [comment]
出すのは簡単なんですが、出来ればここは皆さんの意見が欲しいところ。中途半端に機能入れて使われないのもアレだし。

**Comment by Shougo** [comment]
了解です。

@mattn 一度Vimにパッチを当ててみて、neobundleの実装に使えるかどうか試してみてみたいのですが、よろしいでしょうか。

**Comment by h-east** [comment]
neo neo うるさい

**Comment by Shougo** [comment]
@mattn 最新版のソースコードにはパッチがうまくあたりませんでした。こちらで修正します。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/90f0c0b67653764d33b3

最新パッチで適用できるようにしてみました。

**Comment by Shougo** [comment]
こちらで試しました。
以下の問題点があります。
1. autocmd 内でコマンドを定義しなかった場合エラーにならない
2. autocmd 内で定義したコマンドは再度呼ばれない
3. ドキュメントがない

1,2 はこちらでも直せないか調べてみます。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/90f0c0b67653764d33b3

1,2 を修正しました。私的にはこれで良いと思いますかどうでしょうか。

**Comment by mattn** [comment]
このアドホックなパッチが良いかどうか(欲しいの Shougo さんだけ？)ってのが意見が聞きたいです。そうであれば提案するつもりはないです。

**Comment by mattn** [comment]
ちなみにパッチに関係ない物が混じってます。

**Comment by Shougo** [comment]
あ、すみません。作業後の hg diff をそのまま出力したので変なのが混じっていたようです。
修正しました。

**Comment by thinca** [comment]
イベント名、`FuncUndefined` に倣って `CommandUndefined` の方が良くないですか?

**Comment by ynkdir** [comment]
Re: CmdUndefined
http://marc.info/?l=vim-dev&m=100887940823495

RE: automatic loading of scripts
http://marc.info/?l=vim-dev&m=110788023426405

**Comment by k-takata** [comment]
todo.txt にも載っているんですね。

```
-   Add events to autocommands:
    Error       - When an error happens
        ....
    CmdUndefined    - Like FuncUndefined but for user commands.
        ....
```

**Comment by mattn** [comment]
うむ。じゃぁパッチ書き換えて送りますか。しばしお待ちを。
v:command じゃなくて v:rhs なのね。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/4yaOcZK6Z9M

**Comment by Shougo** [comment]
:+1:

**Comment by h-east** [comment]
多少Bram氏の手直しは入ったけど取り込まれた。
Patch 7.4.414
https://groups.google.com/d/msg/vim_dev/fRcvB3CBIDg/6hpmnmaF1qwJ

**Comment by h-east** [comment]
コンパイルエラー出る:sweat_smile:
既に報告されているのでそのうち直るでしょう。

**Comment by k-takata** [comment]
直りました。
7.4.415
https://groups.google.com/d/topic/vim_dev/9UqOz7cv-DU/discussion

**Comment by Shougo** [comment]
:+1:

**Comment by Shougo** [comment]
Vim 7.4.415 にて動作を確認しました。完璧です。
