### ISSUE TITLE
改行を背景色ありでハイライトして cursorline すると表示がおかしくなる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#27]
詳しい条件は要検証。

test.vim

``` vim
syntax on
call matchadd('Error', '\n')
setlocal cursorline
```

```
vim -u NONE -i NONE -N -S test.vim
```

現在行(cursorlineでハイライトされている行)の行末が2文字分、別の色でハイライトされます。

**Comment by mattn** [comment]
僕の環境(Windows/vim.exe)では先頭がおかしいw

![](http://go-gyazo.appspot.com/7d1e0e64e0a170d0.png)

**Comment by thinca** [comment]
改行が先頭にあるのだと思います。
適当に文字を入力してみてください。

**Comment by thinca** [comment]
わかりにくかったですね。おかしくなるのは改行部分です。

**Comment by thinca** [comment]
あ、追加情報。
このおかしくなった2文字分が縦分割の境目に来るように調節すると、縦分割が崩れます。

**Comment by mattn** [comment]
@thinca スクショ下さい

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/99ec2ed95c6893af.png)

こうですか？

**Comment by thinca** [comment]
いや、すいません。縦分割というのは、ウィンドウの縦分割です。 `:vsp`

**Comment by thinca** [comment]
![](http://gyazo.com/95d8cc482fbfb5797913ff2efd1df3ed.png?)
![](http://gyazo.com/95d8cc482fbfb5797913ff2efd1df3ed.png)
こんな感じです。

**Comment by mattn** [comment]
僕のはこうなる

![](http://go-gyazo.appspot.com/a61412dd56a5676e.png)

**Comment by thinca** [comment]
``` vim
syntax on
5vsplit
call matchadd('Error', '\n')
call setline(1, '    ')
setlocal cursorline
```

これでどうでしょう。
実行後にカーソルを左右に動かすなどしてみてください。

**Comment by mattn** [comment]
`\n`が宜しくないみたいですね`\r`だとうまく行ってるっぽいです。
僕見ます。

**Comment by thinca** [comment]
`\r` は `^M` にマッチするからまた別なんですかね。ちなみに `\%1l` や `\_.` などのパターンでも発生します。要はVim内での改行部分にマッチすれば発生するようです。

**Comment by thinca** [comment]
これって何か進展あったでしょうか?
ちなみに今 7.3.761 で試したところ、まだ発生する模様。

**Comment by mattn** [comment]
これみたいにカラムがずれますか？

https://github.com/vim-jp/issues/issues/27#issuecomment-2169526

Windows CUIだとならないっぽい。

**Comment by mattn** [comment]
あ、うそ。
なった。

**Comment by mattn** [comment]
難易度高そう。
投げた方が良い気がした。

**Comment by mattn** [comment]
これ、直ってますね。 @thinca

**Comment by h-east** [comment]
直ってないです。 CUI Vim 7.4.1342 on fedora via PuTTY

**Comment by k-takata** [comment]
s/tinca/thinca

**Comment by thinca** [comment]
同じく確認しましたがまだ再現しますね。
CUI Vim 7.4.1345 on Gentoo via PuTTY / tmux 2.1

**Comment by mattn** [comment]
あれ。すいませんすいません。

**Comment by koron** [comment]
本件は依然問題として残っているため、 assign は解除し open としました。

**Comment by ichizok** [comment]
これ、どうなるのが正しいんでしょうか？

```vim
normal! iabcd
call matchadd('Search', '\n')
set cursorline
```

現状) 行末2文字がハイライト無し (`screenattr(1, 5) == screenattr(1, 6) == 0`) 、右端までハイライト+underline

![hl-eol 0](https://cloud.githubusercontent.com/assets/943423/26298632/00010762-3f13-11e7-90b2-16f3046342b0.png)

a) 行末1文字がハイライト無し (`screenattr(1, 5) == 0`) 、右端までハイライト+underline

![hl-eol 1](https://cloud.githubusercontent.com/assets/943423/26298638/02bc324c-3f13-11e7-8f34-5e23630bc9ee.png)

b) 行末から右端までハイライト＋underline

![hl-eol 2](https://cloud.githubusercontent.com/assets/943423/26298649/0ac8ecc8-3f13-11e7-915f-99a343595190.png)

c) 行末1文字がハイライト+underline、右端までunderline

`nocursorline` の状態に underline をかぶせた形。

![hl-eol 3](https://cloud.githubusercontent.com/assets/943423/26298658/0ea09a08-3f13-11e7-9023-a2fc442c7dee.png)

d) その他

**Comment by ichizok** [comment]
報告しました。
https://github.com/vim/vim/issues/1792

**Comment by ichizok** [comment]
`:set list` した場合と合わせるなら (b) にすべきか。

![vim-hi](https://user-images.githubusercontent.com/943423/28301631-1f208794-6bc3-11e7-86c6-381e9ee1d62d.png)

**Comment by ichizok** [comment]
GUIなど、`cursorline` が背景色だと `:set list` は (c) の状態になる。

```vim
hi CursorLine cterm=NONE ctermbg=242
setl list
```

![vim-hl](https://user-images.githubusercontent.com/943423/28301597-d6b52b04-6bc2-11e7-8cb8-20b5ea0495e3.png)

**Comment by ichizok** [comment]
https://github.com/vim/vim/compare/master...ichizok:fix/hl-eol

**Comment by ichizok** [comment]
投げました。
https://github.com/vim/vim/pull/2111

**Comment by ichizok** [comment]
todo入り
https://github.com/vim/vim/commit/37c64c78fd87e086b5a945ad7032787c274e2dcb#diff-38d7929bd26d74d92ceddf984bbfc8dbR169

**Comment by ichizok** [comment]
8.0.1168
https://github.com/vim/vim/commit/0aa398f55a327282c70f56e0bac2dcb9521da378

追加修正
https://github.com/vim/vim/pull/2177

**Comment by ichizok** [comment]
8.0.1169
https://github.com/vim/vim/commit/5ece3e359c4b96d0f9bf1ce690223545f40f34b8

underline + `set list` の時のハイライトも変更されています。
（https://github.com/vim-jp/issues/issues/27#issuecomment-303034410 の (c) になった）
