### ISSUE TITLE
Vim script の再帰回数について

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#270]
次のような Vim script を実行すると次のようなエラーが出力されます。
- ソース

``` vim
set maxfuncdepth=1000

function! s:func(n)
    if a:n
        call s:func(a:n-1)
    endif
endfunction
call s:func(198)
```
- エラー

```
function <SNR>294_func..<SNR>294_func..（中略）<SNR>294_func..<SNR>294_func の処理中にエラーが検出されました:
行    1:
E169: コマンドが再帰的過ぎます
```

関数の再帰回数は `maxfuncdepth` で設定できるんですが、上記の場合はそれよりも少ない数でエラーになってしまいます。
エラーコードを見る限りではコマンドの再帰でエラーになっているぽいです。
これはこういう仕様なんでしょうか？
ちなみに `set maxfuncdepth=100` した場合は `E132` が発生します。

**Comment by koron** [comment]
[ex_docmd.c:801](https://github.com/vim-jp/vim/blob/master/src/ex_docmd.c#L801) ですね。
execute や source などでコマンドラインコマンドが再起するのを防ぐため
200回(ハードコーディング) という制限がある模様。

ドキュメントに明示するか、オプション化しておいたほうが良いかも。

**Comment by koron** [comment]
maxfuncdepth の適用範囲はevalであり、cmdlineではないってことなんだろうなぁ。

call そのものはcmdline であってeval ではないので maxfuncdepth の適用対象外。
ただその先で呼ばれる関数はmaxfuncdepth の対象となる。

が今の実装仕様ですね。

**Comment by mattn** [comment]
これそっちもmaxfuncdepthにした方がうれしいなー

**Comment by mattn** [comment]
まぁ違うオプションでもいいけど200を変えれないのは痛い

**Comment by thinca** [comment]
コマンドの再帰数が200に制限されているのは、`:help E169` に書いてありますね。
ただ、関数を呼び出すにはまずコマンドを実行しなくてはいけないので、
`'maxfuncdepth'` を 200 以上にしても先にコマンドの制限に引っ掛かってしまうのがアレですね。

**Comment by mattn** [comment]
とりあえず、このままほっとくと沈みそうなので提案してみます？

**Comment by koron** [comment]
evalの右辺で再帰すればいけそうw

提案するに +1
2012/11/05 13:40 "mattn" notifications@github.com:

**Comment by k-takata** [comment]
8.0.137 で `'maxfuncdepth'` の値が適用されるようになりました。
https://groups.google.com/d/topic/vim_dev/v1_h1YdQ_vg/discussion

**Comment by tyru** [comment]
これで悩んでましたが解消しました。ありがとうございます！
(http://vim-jp.org/redirects/ の "Latest Vim official binary for Windows x64" (8.0.142) で確認済み)
