### ISSUE TITLE
ファイル保存時によくSEGVでクラッシュする

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#271]
> 野良ビルドのvim 7.3.729使ってるけど、7.3.715 以降かな、ファイル保存時によくSEGVでクラッシュするようになった。とくにshファイル保存時。syntasticとかも関係あるのかなぁ。。。家のOSXでも現場のLinuxでもおんなじ。。。戻そうか。。。

from https://twitter.com/yoshikaw/status/273291491588337664

**Comment by h-east** [comment]
issue登録あざっす！

**Comment by tyru** [comment]
「Patch 7.3.715」ってスレッドで同じ事象(syntasticが発動すると落ちる)が報告されてます。
Christianさんの作ったパッチで「直ったっぽい」って返事も返って来てるので、もうすぐ取り込まれるものと思われます。

**Comment by yoshikaw** [comment]
そのような事象が報告されているんですね。

https://groups.google.com/forum/?fromgroups=#!topic/vim_dev/4C1CSHfJ_QI

今のところsyntasticのチェックに助けられる場面はそれほどないので、取り込まれるまでは無効にしておこうと思います。

**Comment by tyru** [comment]
7.3.730で取り込まれたみたいです。

https://groups.google.com/forum/?fromgroups=#!topic/vim_dev/5c59UDnXNBw

**Comment by yoshikaw** [comment]
おお！さっそく試してみます。

**Comment by mattn** [comment]
seems to be left yet another problem.

On 11/28/12, Kazuhiro YOSHIKAWA notifications@github.com wrote:

> $B$_$_!*$5$C$=$/;n$7$F$_$^$9!#(B
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/271#issuecomment-10805216

## 
- Yasuhiro Matsumoto

**Comment by h-east** [comment]
7.3.730 で治ったけどMemory Leakが起きるようになってて、

Patch 7.3.746 でMemory Leakをfixした。
https://groups.google.com/d/topic/vim_dev/qN6azlJgtyY/discussion

...けど:vimgrepとの併用時になんかよろしくなさそうで そのpatchがTODOリストのtopにある状態。（ややこしいｗ）

@yoshikaw とりあえず落ちなくなっていたらクローズしちゃって下さい。(確認したVer報告よろしくです)

**Comment by yoshikaw** [comment]
報告が滞り申し訳ありません。

7.3.730 を使い始めてから Syntastic を有効にしても保存時にクラッシュすることは無くなりました。

メモリリークや:vimgrepの件については気づいていませんが、現在使用している ７．３．754 でも落ちませんので安心して保存できるようになりました。

githubに不慣れですので、 https://github.com/vim-jp/issues/wiki/Member をみましたが「Close & Comment」のボタンが見つけられませんでした。お手数ですがクローズしてください。

**Comment by koron** [comment]
works for me
