### ISSUE TITLE
eval.txt に不正なシーケンス

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#272]
runtime/doc/eval.txt の 2300行目に不正なシーケンスを発見。

> ```
>   The current 'encoding' is used.  Example for "utf-8": >
>       char2nr("?")        returns 225
>       char2nr("?"[0])     returns 195
> ```

`"?"` の部分は 0xe1 になっていて、どっかで変換に失敗して情報が失われたっぽい。
とりあえず以下のように直せばよさそうだが…イマイチ自信がない。

> ```
>   The current 'encoding' is used.  Example for "utf-8": >
>       char2nr("á")       returns 225
>       char2nr("Ã"[0])        returns 195
> ```

コメントお願いします。

**Comment by koron** [comment]
http://www.vim.org/sources.php の vim-7.3.tar.bz2 の中で既におかしくなっていた。

**Comment by koron** [comment]
6.0までさかのぼって、ずっと変わってないことがわかった。

ということはここはlatin1で書かれているのね…

だから正しくはこう見えるべき。しかもUTF-8であるべき。

> ```
>   The current 'encoding' is used.  Example for "utf-8": >
>       char2nr("á")       returns 225
>       char2nr("á"[0])        returns 195
> ```

つまりこの例は、同じ文字列でもマルチバイトならばぶった切れば違う値がでてくるよ、ということが言いたいと。

latin1 から UTF-8 に変換して修正するのが良いと思うが、いかがか?

**Comment by koron** [comment]
helphelp.txt に

> Help files must use latin1 or utf-8 encoding.  Vim assumes the encoding is
> utf-8 when finding non-ASCII characters in the first line.  Thus you must
> translate the header with "For Vim version".

って書いてあるなぁ… (´・ω・`)

UTF-8 にしたいなぁ。

**Comment by thinca** [comment]
うちの環境では `latin1` で開かれて、特に化けませんね。

**Comment by thinca** [comment]
まあただ、私も個人的には全部 UTF-8 に統一したいですねw

**Comment by koron** [comment]
本件は問題ではなかったんだな。UTF-8に統一するのは、やるなら別でだわ。
