### ISSUE TITLE
:!による外部コマンド実行結果が:redirで取得できない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#274]
前は

```
let cmd = "!ls"
redir => output
silent execute cmd
redir END
```

で`output`に`ls`の結果が含まれていた気がしたんですが、今7.3.729で実行してみるとコマンド出力結果が含まれないようになっています。

自分は`:Capture`って単に引数のExコマンドを実行して結果をバッファに出力してるだけのコマンドを定義していて、これで`:Capture !ls`とかして外部コマンドの出力もバッファに取ってこれたような気がしてたのですが... (ちなみに主に@thincaさんが単一プラグイン化してほしいって言ってたのでつい最近[リポジトリ](https://github.com/tyru/capture.vim)作りました)

**Comment by tyru** [comment]
出力結果書いてませんでした。
7.3.729で次のような結果になります。
`:!echo hello`とコマンド実行した出力はあるんですが、`hello`の出力がないです。

```
redir => output
silent !echo hello
redir END
echom string(output)
'^@^@:!echo hello^M^@^@'
```

**Comment by h-east** [comment]
7.3.471 や 7.2.001 や 7.0aa で確認してみましたがすべて helloの出力なしでした。
うーむ。。。helloの出力がされるバージョンってあります？

# 勘違いだった、に1票

**Comment by tyru** [comment]
あれ...勘違いでしたか...すみません。
うーん7.0でも確認してくれたなら、きっと勘違いだったんだと思います...すみませんcloseします。
