### ISSUE TITLE
let g:netrw_liststyle=3でディレクトリ移動ができない

### ISSUE THREAD

**Issue by ompugao** [vim-jp/issues#275]
7.3.754にて .vimrcを

```
let g:netrw_liststyle=3
```

だけにして、:e .すると、適当なディレクトリの表示される行で[Enter]してもディレクトリ移動ができません。

どのpatchで動かなくなったか追っていませんが、修正をお願いしたいです。

よろしくお願いします。

**Comment by h-east** [comment]
私の環境では正しく動いているように見えます。(fedora16 on PuTTY. Vim7.3.754. netrw v145)
@ompugao さんの環境＆netrwのバージョンを教えて頂けますか？

**Comment by koron** [comment]
うちでは報告通りディレクトリの選択ができません。
ファイルはできます。

+kaoriya 754 win64

**Comment by mattn** [comment]
うちは動く。

windows xp mingw32 netrw-v146 野郎

**Comment by koron** [comment]
+kaoriya バイナリか。原因調査までは私がやったほうがよさそうですね。

**Comment by koron** [comment]
`|` で始まってるかどうかが悪さしてそう。

`|` で始まってない `../` は選択できるので実際にそれを選択すると、ディレクトリ内容を表示するのではなく NetrwTreeListing 1 とかいうROなバッファを開いてしまう。その後、ディレクトリを `:e` してもその内容は表示されなくなる。

**Comment by koron** [comment]
…もう読みたくないお。このソース、読む気をくじくお。

**Comment by ompugao** [comment]
ubuntu 12.04,vim7.3.754,netrw v146です

べたっと貼ります
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec  9 2012 19:48:10)
適用済パッチ: 1-754
Compiled by sifi@lycium
Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
+arabic +autocmd +balloon_eval +browse ++builtin_terms +byte_offset +cindent 
+clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con_gui +diff 
+digraphs +dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi 
+file_in_path +find_in_path +float +folding -footer +fork() +gettext 
-hangul_input +iconv +insert_expand +jumplist +keymap +langmap +libcall 
+linebreak +lispindent +listcmds +localmap -lua +menu +mksession +modify_fname 
+mouse +mouseshape +mouse_dec -mouse_gpm -mouse_jsbterm +mouse_netterm 
+mouse_sgr -mouse_sysmouse +mouse_urxvt +mouse_xterm +multi_byte +multi_lang 
-mzscheme +netbeans_intg +path_extra +perl +persistent_undo +postscript 
+printer +profile +python -python3 +quickfix +reltime +rightleft +ruby 
+scrollbind +signs +smartindent -sniff +startuptime +statusline -sun_workshop 
+syntax +tag_binary +tag_old_static -tag_any_white -tcl +terminfo +termresponse
 +textobjects +title +toolbar +user_commands +vertsplit +virtualedit +visual 
+visualextra +viminfo +vreplace +wildignore +wildmenu +windows +writebackup 
+X11 -xfontset +xim +xsmp_interact +xterm_clipboard -xterm_save 
      システム vimrc: "$VIM/vimrc"
        ユーザ vimrc: "$HOME/.vimrc"
         ユーザ exrc: "$HOME/.exrc"
     システム gvimrc: "$VIM/gvimrc"
       ユーザ gvimrc: "$HOME/.gvimrc"
    システムメニュー: "$VIMRUNTIME/menu.vim"
       省略時の $VIM: "/home/sifi/share/vim"
コンパイル: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -I/usr/local/include  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  
リンク: gcc   -L. -L/usr/local/rvm/usr/lib -rdynamic -Wl,-export-dynamic  -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -lnsl   -lncurses -ldl    -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.14/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions   -Wl,-R -Wl,/usr/local/rvm/rubies/ruby-1.9.3-head/lib -L/usr/local/rvm/rubies/ruby-1.9.3-head/lib -lruby -lpthread -lrt -ldl -lcrypt -lm  -L/usr/local/rvm/rubies/ruby-1.9.3-head/lib

**Comment by koron** [comment]
なんだーkaoriya特有じゃなかったのか…

**Comment by koron** [comment]
正しい動作がわかってないので、何が間違ってるのかすぐにはわからない。

``` vimL
   elseif exists("w:netrw_liststyle") && w:netrw_liststyle == s:TREELIST && exists("b:netrw_curdir")
```

こんな感じのif文はたくさんあるから、その中がおかしいかif文が期待通りに機能してないかのどちらかだとは推測している。

**Comment by koron** [comment]
とりあえずここまでの調査結果を書いておきます。
- `<CR>` を叩くと以下の3つの関数が順次起動する
  - s:NetrwGetWord
  - s:NetrwBrowseChgDir
  - netrw#LocalBrowseCheck
- 最初の2つはちゃんと動いているっぽい。その内容はおおまかに言って以下のとおり:
  - カーソル下のディレクトリを抽出
  - 必要なデータの一部更新を行い(ここがやっかいかもしれない)、ディレクトリを確定する
- netrw#LocalBrowseCheck の引数としての入力はディレクトリパスだが、それ以外にもウィンドウ変数やバッファ変数も入力に相当しているため、やっかい

以上のことから、現時点での推測は
- s:NetrwBrowseChgDir で必要な変数の修正が適切に行われていない
- netrw#LocalBrowseCheck から先の処理がこけているか

どちらの場合でも `exists("w:netrw_liststyle") && w:netrw_liststyle == s:TREELIST` このようなチェックが関係しているので、絞り込みはしやすいはず。

以上

**Comment by thinca** [comment]
そもそも `i` で表示モード切り替えようとするとエラーが出る…。このクオリティで標準とはひどい。

**Comment by thinca** [comment]
`:help netrw-i` のサンプルコードも間違えてる。`let g:netrw_liststyle= 4` でツリーモードになると書いてある。`:help g:netrw_liststyle` を見ると、取りうる値は 0,1,2,3 のどれか。
色々ひどい。

**Comment by mattn** [comment]
しかもツリーの動作いろいろ(おっと誰か来た

ってくらいひどい

**Comment by koron** [comment]
by @thinca: https://github.com/vim-jp/issues/issues/276#issuecomment-11181227

> とりあえず #275 については誰かが vim_dev に報告してしまうのが手っ取り早いんですかね。

**Comment by koron** [comment]
イマイチ、発生のトリガーがわかってないのが痛いかも。

**Comment by ynkdir** [comment]
v145=ok v146=ng

autoload/netrw.vim:2991行目
- return 1
- return 0

でとりあえず動くみたいです。

https://groups.google.com/forum/#!topic/vim_dev/GzHRxSrJ4mI/discussion

別件ですが g:netrw_liststyle=3 のバグ報告出てるのでついでに直りそうなきもします。

ちなみに最新版の v147b だと上記の変更でも動かないです。というか壊れてます。

**Comment by h-east** [comment]
@ynkdir :100:

**Comment by koron** [comment]
@ynkdir :+1: Thanks!

**Comment by koron** [comment]
> ちなみに最新版の v147b だと上記の変更でも動かないです。というか壊れてます。

アホすwww

**Comment by h-east** [comment]
あれ？でもまっつんさんはnetrw-v146でちゃんと動いてるから辻褄が合わない。

そもそも vim をhg pull --updateして入るnetrwはv145ちゃいますのん？
v146ってどっから仕入れてはるんですか？

**Comment by mattn** [comment]
> v146ってどっから仕入れてはるんですか？

闇市

**Comment by ynkdir** [comment]
r3920 で v146 になりました。

v147b は g:netrw_xstrlen の設定がおかしくなってるみたいで自分で設定して let g:netrw_xstrlen=0 (0以外可) と上記の変更でいちおう動きます。
ただ上記の変更が正しいかはわかりません。

**Comment by mattn** [comment]
なかなか、ひどそうね... ｺﾞｸﾘ...

**Comment by ompugao** [comment]
おーっ 動きました
ありがとうございます

**Comment by h-east** [comment]
あーっ、開発用のrtp設定がコメントになってた。 :stuck_out_tongue_winking_eye:

``` vim
set rtp^=(hg のvimフォルダ)/runtime
```

v146で動かないのを確認しました。そして2991行目の修正で動いたのを確認しました。 :clap:

**Comment by koron** [comment]
これ、なおってるっぽいので閉じちゃっていいのかな?
# 別の問題が発生している可能性は否めないけどw

**Comment by koron** [comment]
っていうか閉じちゃいます。間違ってたらまた開いて。
