### ISSUE TITLE
msvcrt.dllのバージョンが違うiconv.dllが使えない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#277]
現在のVimは、(lib)iconv.dllのエラーを見るために、msvcrXX.dllがエクスポートしている `_errno` のアドレスを取得して使用しています。
しかし、msvcrXX.dllのバージョンはコンパイル時に決まってしまうため、別のバージョンのmsvcrXX.dllにリンクされたiconv.dllを持ってきても使うことができません。

iconv.dllが実際に使っている `_errno` のアドレスを取得して使うパッチを作ってみました。
https://gist.github.com/4292446

API hookでよく使われる方法の流用です。
別のiconv.dllを使えるようにするためだけに、ここまでする必要があるのかという問題がありますが…。

**Comment by koron** [comment]
gistのほうに書いちゃったw

:+1:

**Comment by k-takata** [comment]
投げてみました。
https://groups.google.com/d/topic/vim_dev/GFIJhL5I0Js/discussion

**Comment by mattn** [comment]
あーなんか思い出してきたぞ

**Comment by mattn** [comment]
これたしかまずいんですよ。
この方法使っても。
E2BIG とか EILSEQ とかの値は、コンパイラによって違ったりするのです。

**Comment by mattn** [comment]
6.1.216で関与してた。
http://mirror.dejanseo.com.au/pub/vim/patches/6.1.216

**Comment by k-takata** [comment]
うへぇぇ！
とりあえずMSVC互換でビルドされたDLLのみ対応ということで…

**Comment by k-takata** [comment]
いくつか調べてみたところ、こんな感じでした。

<table>
    <tr>
        <th> </th><th>VC/MinGW</th><th>Cygwin</th><th>BCC</th>
    </tr>
    <tr>
        <td>E2BIG</td><td>7</td><td>7</td><td>20</td>
    </tr>
    <tr>
        <td>EINVAL</td><td>22</td><td>22</td><td>19</td>
    </tr>
    <tr>
        <td>EILSEQ</td><td>42</td><td>138</td><td>-</td>
    </tr>
</table>

MinGWはmsvcrt.dllを使っている以上、VCと同じでないと動かないですよね。

_追記_
2013/01/12 BCCの値を記載

**Comment by mattn** [comment]
afaik, bcc has different values. but i wonder bcc is able to build
latest vim at least...

On 12/18/12, K.Takata notifications@github.com wrote:

> $B$$$/$D$+D4$Y$F$_$?$H$3$m!"$3$s$J46$8$G$7$?!#(B
> 
> <table>
>     <tr>
>         <th> </th><th>VC/MinGW</th><th>Cygwin</th>
>     </tr>
>     <tr>
>         <td>E2BIG</td><td>7</td><td>7</td>
>     </tr>
>     <tr>
>         <td>EINVAL</td><td>22</td><td>22</td>
>     </tr>
>     <tr>
>         <td>EILSEQ</td><td>42</td><td>138</td>
>     </tr>
> </table>
> 
> MinGW$B$O(Bmsvcrt.dll$B$r;H$C$F$$$k0J>e!"(BVC$B$HF1$8$G$J$$$HF0$+$J$$$G$9$h$M!#(B
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/277#issuecomment-11445824

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
あぁ、そんな予感もしていましたが、わざわざインストールする気も起きなかったので…

**Comment by k-takata** [comment]
7.3.767で取り込まれました。
https://groups.google.com/d/topic/vim_dev/eKepPscGhF0/discussion

**Comment by mattn** [comment]
落ちますね。WinXP 32bit

**Comment by mattn** [comment]
```
        if (strcmp(pImpName->Name, funcname) == 0)
```

ここで落ちてる。

**Comment by koron** [comment]
pImpName == NULL?

**Comment by mattn** [comment]
いや違う

**Comment by mattn** [comment]
分かった。パッチ書く。

**Comment by mattn** [comment]
とりあえず落ちない様にした物

``` diff
diff -r 5cf390d4fbe1 src/mbyte.c
--- a/src/mbyte.c   Thu Jan 17 18:34:06 2013 +0100
+++ b/src/mbyte.c   Fri Jan 18 11:59:42 2013 +0900
@@ -4315,7 +4315,7 @@
     pImpDesc = (PIMAGE_IMPORT_DESCRIPTOR)(pImage
        + pPE->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT]
                                .VirtualAddress);
-    for (; pImpDesc->FirstThunk; ++pImpDesc)
+    for (; pImpDesc->OriginalFirstThunk; ++pImpDesc)
     {
    pIAT = (PIMAGE_THUNK_DATA)(pImage + pImpDesc->FirstThunk);
    pINT = (PIMAGE_THUNK_DATA)(pImage + pImpDesc->OriginalFirstThunk);
```

**Comment by k-takata** [comment]
FirstThunk != 0 だけど OriginalFirstThunk == 0 という場合があるんですかね？
OriginalFirstThunk == 0 の場合は、continue するとどうなりますか。

**Comment by mattn** [comment]
``` diff
diff -r 5cf390d4fbe1 src/mbyte.c
--- a/src/mbyte.c   Thu Jan 17 18:34:06 2013 +0100
+++ b/src/mbyte.c   Fri Jan 18 17:10:20 2013 +0900
@@ -4317,6 +4317,8 @@
                                .VirtualAddress);
     for (; pImpDesc->FirstThunk; ++pImpDesc)
     {
+   if (!pImpDesc->OriginalFirstThunk)
+       continue;
    pIAT = (PIMAGE_THUNK_DATA)(pImage + pImpDesc->FirstThunk);
    pINT = (PIMAGE_THUNK_DATA)(pImage + pImpDesc->OriginalFirstThunk);
    for (; pIAT->u1.Function; ++pIAT, ++pINT)
```

落ちなくはなりますが、エントリは見つけれないっぽいですね。
たぶんですが、GetModuleFileNameしてVirtualAllocしないと取れない気がする。

**Comment by k-takata** [comment]
うーむ。使っている iconv.dll はどれでしょうか。

**Comment by mattn** [comment]
旧kaoriyaで配ってた奴かも

**Comment by mattn** [comment]
ちがうっぽい。

**Comment by mattn** [comment]
gnuwin32とかkaoriyaのはバージョン情報付いてるけど、この問題でてる奴ってバージョン情報付いてないんですよね。
結構古いのかも。

**Comment by mattn** [comment]
ttp://mattn.kaoriya.net/tmp/iconv.dll.zip

置きました。

**Comment by k-takata** [comment]
現象はこのdllだけで起きているのでしょうか。（中身の確認は後で）

**Comment by mattn** [comment]
gnuwin32、kaoriya、コレを試しましたが、コレだけっぽいですね。

**Comment by mattn** [comment]
たぶんmsvcrtとリンクしてないのかも。

**Comment by mattn** [comment]
dependency walkerで見たら確かにmsvcrtとリンクはしてる。やっぱりdelay load?

**Comment by k-takata** [comment]
あー、昔何か似たようなことがありました。
k-takata/ijexp32@d051c73e2ffaceb2a0f48868f226a18f0d6f8b6a
k-takata/ijexp32@0df47ab1f0a32302b7f8ed488ad74843cb6884dc
そのときは、Borlandのリンカが出力した実行ファイルの情報が取れないというものでした。

普通は、OriginalFirstThunk の方にシンボル名へのポインタが入っていて、ロード後 FirstThunk には関数のアドレスが入るのですが、OriginalFirstThunk が 0 の場合は、FirstThunk の方にシンボル名へのポインタが入っていて、ロード後はそれが関数のアドレスに置き換わるようです。
そのため、このタイプの場合、ロード後は errno のアドレスを知ることはできません。

修正方法としては、continue する方で良いと思います。

**Comment by k-takata** [comment]
今回のiconv.dllですが、ずいぶんファイルサイズが小さいですね。Win32 APIを使って文字コード変換を行い、I/Fだけiconvに合わせてあるのでしょうか。

ビルド日時は以下の通りでした。ファイルの中身を見ると、MinGWで作られているような感じなのですが、Linker versionを見ると何か合っていないような感じがします。(binutils は現在 2.23 が最新のようなので。)

Link time stamp, 2010/05/06 08:46:49 (4be20369)
Linker version, 2.56

**Comment by ynkdir** [comment]
これwiniconvですたぶん

**Comment by k-takata** [comment]
http://code.google.com/p/win-iconv/
おお、こんなプロジェクトがあったのですね。確かにそのようです。
もっとも自分でビルドしても、問題の起きるDLLはできなかったのですが。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/eKepPscGhF0/xoSZIAiluqoJ

**Comment by k-takata** [comment]
7.3.773 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/AEsz-wOw71w/discussion

**Comment by k-takata** [comment]
win-iconvでも同じようなことをやってるんですね。
http://code.google.com/p/win-iconv/source/browse/trunk/win_iconv.c?r=39#1226

**Comment by ynkdir** [comment]
はい。
しかし関数ポインタ直に取れるとは知りませんでした。

**Comment by k-takata** [comment]
7.3.778 で追加修正が入りました。
https://groups.google.com/d/topic/vim_dev/kPSLy_CrOqQ/discussion
VC6 では AddressOfData がポインタとして定義されているせいで、キャストしないとコンパイルエラーになってしまいます。
