### ISSUE TITLE
年末大掃除したい (2012)

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#279]
Issues の大掃除がしたいです。
- なんとなく流れが止まっている Issues を掘り返して現状の確認したり可能なら話を進めたりとかそんな感じで
- 特に進められるのがなかったとしてもキニシナイ
- issues リポジトリに立てたけど、対象は vim-jp 内の全リポジトリ
- この issue 自体はメンバーの意識共有等が目的。特に他の issue と紐付けたりなどはしない
- よって、この issue は作業の進捗/作業自体の有無に関わらず年末ないし年始に閉じる

こんな感じでどうでしょ。

**Comment by koron** [comment]
:+1:

**Comment by mattn** [comment]
+1

**Comment by h-east** [comment]
±0

**Comment by tyru** [comment]
+1

**Comment by thinca** [comment]
(提案するだけしておいてほとんど自分は動けてない…)

**Comment by thinca** [comment]
関連? #130

**Comment by thinca** [comment]
軽く見ていたのだけど、 #171 とか #173 とか、パッチを送ったけど Bram さんの反応がまったくないってのがありますね。こういうのはどうすればいいんだろう。MLで「なんでスルーされているの?」とか聞くべき?

**Comment by Shougo** [comment]
私はそもそも、パッチを書いたけど送っていません。そろそろどうにかしないとだめかな…。

https://github.com/vim-jp/issues/issues/245

安定して動作することは人柱して確認済み。
さて、最新版でも動作するか確認をしないと。

**Comment by thinca** [comment]
もう年明けてだいぶ経つのでこいつは閉じます。
