### ISSUE TITLE
'foldopen' が all でないと :help で折り畳みが開かれない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#28]
仕様確認も兼ねたいのですが、help に折りたたみがある場合、`'foldopen'` に all がないと `:help` 実行後に折り畳みが開かれません。
all 以外の全てのキーワードを含めてもダメです。all はその他全てを指定したのと同じではないということでしょうか。
ちなみに挙動を確認したい場合は @Shougo さんのプラグインの help を開くと良いです。

**Comment by mattn** [comment]
modelineに以下を設定してみました。

```
vim:tw=78:ts=8:ft=help:norl:noet:fen:fdl=0:fdm=marker:foldopen=block,hor,mark,percent,quickfix,search,tag,insert,undo,jump:
```

この状態でfold上で`l`押したら展開されました。何か条件が作用するのかな？

**Comment by thinca** [comment]
`l` だと "hor" があるので開くのは当然かと思います。
あと一応ですが、`'foldopen'` はグローバルオプションです。

**Comment by mattn** [comment]
```
set foldopen=block,hor,mark,percent,quickfix,search,tag,insert,undo,jump
```

を書いて置けば、ファイルを開いた時に一つもfoldされていないはずという意味ですか？
それともそのfoldに含まれる牽引にジャンプしても開かないという意味ですか？

**Comment by thinca** [comment]
後者です。
つまり、modeline に `dfl=0` があると全ての折り畳みが閉じられた状態でバッファが開かれるわけですが、
`'foldopen'` が all の場合はその効果によってジャンプ先の折り畳みが開かれます。
all 以外の全てが指定されていた場合は、全ての折り畳みは閉じられたままです。
そもそも all 以外の項目に help に該当するものがないような気がします。(あるとしたら tag?)

**Comment by mattn** [comment]
パッチ書きました。
直し方が複数ありえるのでこのまま取り込まれるかは分かりません。

https://groups.google.com/d/topic/vim_dev/eHOK5qQ8GnI/discussion

**Comment by mattn** [comment]
入ったのでclose
https://groups.google.com/d/topic/vim_dev/QmbEVLXbLXo/discussion
