### ISSUE TITLE
make configがうまく動かない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#280]
Unix系のソフトの場合、`./configure`して`make`するというのが一般的なビルド手順だと思いますが、Vimの場合は`src/Makefile`に書いてあるように、そのファイルを編集してから`make`または`make config && make`を実行し、その中で自動的に`./configure`が実行されるというのが、想定された手順のようです。

このmake機構には、`src/auto/configure`などが更新されて`./configure`の再実行が必要な場合、自動的にそれを実行するという機能があるのですが、どうもこれがうまく動かないようです。

たとえば、1回`make`した後で、最新のソースを取得して`src/auto/configure`が更新された場合、次に`make`を実行すると次のようなエラーが出てしまいます。

```
configure: loading cache auto/config.cache
configure: error: `CFLAGS' has changed since the previous run:
configure:   former value:  `-g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1'
configure:   current value: `-g -O2 -U_FORTIFY_SOURCE  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1'
configure: error: `LDFLAGS' has changed since the previous run:
configure:   former value:  `-L.       -L/usr/local/lib -Wl,--as-needed'
configure:   current value: `-L.      -L.       -L/usr/local/lib -Wl,--as-needed -Wl,--as-needed'
configure: error: in `/cygdrive/c/WORK/vim/src':
configure: error: changes in the environment can compromise the build
configure: error: run `make distclean' and/or `rm auto/config.cache' and start over
Makefile:1657: recipe for target `config' failed
make: *** [config] Error 1
```

> run `make distclean' and/or `rm auto/config.cache'

と表示されているので、その通りに`make distclean`を実行しようとしても、distcleanの前にconfigureが走ってしまい、再度同じエラーが表示されます。
`rm auto/config.cache`を実行してから`make config`した場合にはそのときはちゃんと通るのですが、`src/auto/configure`が更新されてconfigureが走るたびに同様のエラーが表示されます。そのたびに`rm auto/config.cache`を実行して`make config`すると、`CFLAGS`と`LDFLAGS`がどんどん長くなっていくという現象が発生します。

**Comment by k-takata** [comment]
この問題の修正パッチを作ってみました。
https://gist.github.com/4292458

まず、`make distclean`を実行しようとしてもその前にconfigureが走ってしまう問題ですが、`Makefile`が`auto/config.mk`をincludeしており、さらに依存関係に`auto/config.mk`が入っているために、最初にconfigureが走ってしまうようです。
とりあえず`auto/config.mk`を依存関係から外して、代わりに`auto/config.cache`を指定してみました。

次に、`CFLAGS`と`LDFLAGS`がconfigureのたびに長くなっていく問題ですが、前回実行時の値が`auto/config.mk`に入っており、その値に毎回オプションを足していくのでだんだん長くなっていました。
必要なオプションが既に含まれていれば、新たに追加しないようにしてみました。

**Comment by koron** [comment]
気になっているのは本来 autotools がやるべき仕事をやろうとしてないか、という点。
Vim 自体が autotools に見えてかなり違ったりするのでアレですが。

**Comment by k-takata** [comment]
> 気になっているのは本来 autotools がやるべき仕事をやろうとしてないか、という点。

makeの中でconfigureまでやろうとしている時点で、そういう方向に行ってしまっているような気が。

> Vim 自体が autotools に見えてかなり違ったりするのでアレですが。

`configure`の実体が`auto/`の下にあるとか、`configure.in`を編集したら、`autoconf`を実行するのではなく、`make autoconf`を実行するとかいろいろびっくりです。

**Comment by k-takata** [comment]
> とりあえず`auto/config.mk`を依存関係から外して、代わりに`auto/config.cache`を指定してみました。

config.cacheは毎回更新されないようなので、config.statusに変更しました。
また、2回目のmake configが必ず失敗するのを修正しました。(暫定的)

**Comment by koron** [comment]
> makeの中でconfigureまでやろうとしている時点

これは autoconf & configure で作成した Makefile でもやってくれませんでしたっけ?
configure.in とか書き換えると自動で再生してくれ(たまにコケる)たような。

> configureの実体がauto/の下にあるとか、configure.inを編集したら、autoconfを実行するのではなく、make autoconfを実行するとかいろいろびっくりです。

たぶん…自動生成されるファイルをautoしたに閉じ込めたいんでしょうね。
だとすれば気持ちはわかりますw

**Comment by k-takata** [comment]
> これは autoconf & configure で作成した Makefile でもやってくれませんでしたっけ?

あ、できましたね。

Gistで編集をミスって一部のTABがスペースに変換されてしまったり、2回目のmake configが必ず失敗するのを修正したつもりが全く直っていなかったのを（数日前に）修正しました。

**Comment by k-takata** [comment]
> 2回目のmake configが必ず失敗するのを修正したつもりが全く直っていなかったのを（数日前に）修正しました。

まだ直ってなかったので、再修正しました。
auto/config.mk を削除してしまうと、makeできなくなってしまうバグも見つかったので修正しました。
https://gist.github.com/4292458/338344d722bd97d9c56c47ee1266a291268526dd

**Comment by k-takata** [comment]
依存関係から auto/config.mk を外してしまうと、ちゃんとビルドされない場合があるようです。
`CFLAGS`と`LDFLAGS`がどんどん長くなっていく現象の修正と、auto/config.cache が古い場合には自動で削除するだけにしました。
https://gist.github.com/4292458/832d481425a8f8421044601ec6dd3c01e975fd64

make distcleanを実行しようとしてもその前にconfigureが走ってしまう問題が残ってしまいますが、自動で走ったconfigureがエラーになることはなくなったので、多少はましになったかと。

**Comment by k-takata** [comment]
安全のため、変数`ac_cv_env_CFLAGS_value`が存在しているかを先に確認するように変更。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/e09a74f02fcef2177998f6cee829fa99112cd89f/fix-make-config.patch

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/L7-eXk0Slds/discussion

**Comment by k-takata** [comment]
7.3.1221 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/C6kClH3kuak/discussion

**Comment by mattn** [comment]
乙

**Comment by k-takata** [comment]
> make distcleanを実行しようとしてもその前にconfigureが走ってしまう問題が残ってしまいますが、

この問題がこれで直るはず。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/04bd428f32f0f32ac68c65afe1adf01a5253ce2c/fix-make-clean.patch
効果があるのは GNU make を使った場合のみだと思いますが、他の make への悪影響はないはず。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/AfB7WtiF9Z0/discussion

**Comment by k-takata** [comment]
7.4.217
https://groups.google.com/d/topic/vim_dev/itQ1f5SfSWo/discussion

**Comment by k-takata** [comment]
make autoconf と make reconfig も対応しておいた方が良さそう。
https://groups.google.com/d/msg/vim_dev/itQ1f5SfSWo/1rW7w2oX7x4J

**Comment by k-takata** [comment]
> make autoconf と make reconfig も対応しておいた方が良さそう。

7.4.273
https://groups.google.com/d/topic/vim_dev/4pkR0aT3cIo/discussion

**Comment by k-takata** [comment]
`make config` を実行すると、毎回 `src/auto/config.cache` が削除されてキャッシュが効いていなかったことが発覚。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a985784dccf66689f092e8bb3d2d33a9d3dea00e/fix-config_cache-removal.patch
最初からこうだったのか、autoconf のバージョンアップの影響なのか…。

**Comment by mattn** [comment]
> make config を実行すると、毎回 src/auto/config.cache が削除されてキャッシュが効いていなかったことが発覚。

www

**Comment by k-takata** [comment]
7.3.1221 からずっとそうだったことが判明ｗ

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/tgZv-e1ZtNI/discussion

**Comment by k-takata** [comment]
Bramから返答。

> I think that's intentional.  Using the cache is not reliable, if
> something changed in the environment it may result in a half-cooked
> config. 

いや、確かにキャッシュは信頼できない場合があるかもしれないけど、キャッシュを毎回削除するのは意図した動作ではないわけで。
本当に毎回キャッシュを削除すべきなら、条件判定自体削除すべきだなぁ。

**Comment by k-takata** [comment]
7.4.300
https://groups.google.com/d/topic/vim_dev/L2CBZmHQh2E/discussion
問答無用で毎回キャッシュを削除するようになりました。
