### ISSUE TITLE
gvim で tabline の表示が崩れる

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#284]
下記の手順で再現しました。

``` vim
:set showtabline=2
:e testtesttesttesttest
:e test
```

![tab](https://f.cloud.github.com/assets/214488/21929/74030ca8-49dd-11e2-984d-428fa9ab6aa2.PNG)

上記の画像のように1つ前のタブ表示が再描画されずに残っています。
再現環境は以下のとおりです。
- WindowsXP
- Kaoriya Vim 7.3.761

**Comment by h-east** [comment]
Patch 7.3.762 で修正されました。(maybe)

**Comment by thinca** [comment]
@osyo-manga 確認して直っていたら閉じてもらえると。

**Comment by osyo-manga** [comment]
まだ Kaoriya Vim が更新されていないので、わたしの方で確認するにはもう少し時間がかかるかも知れません。
わたしの環境で動作確認でき次第閉じようと思っていますが、他の方の環境で動作確認が出来れば閉じていただいても構いませぬ。

**Comment by thinca** [comment]
@koron 先生、出番です！

**Comment by koron** [comment]
さーせん。ちかいうち更新します。

**Comment by koron** [comment]
@osyo-manga 更新しました。確認お願いします。

**Comment by osyo-manga** [comment]
ありがとうございます！
問題なく動作することを確認しました。
