### ISSUE TITLE
Windows のシンボリックリンクが上書きされる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#285]
Vim が Windows のシンボリックリンクを認識しない関係で、シンボリックリンクされたファイルを開いて保存すると、`'backupcopy'` が `yes` でもリンクではなく実ファイルになってしまいます。
ちなみにここで言うシンボリックリンクは Windows Vista 以降に使用可能な mklink コマンドで作れるやつです。

**Comment by koron** [comment]
「シンボリックリンクされたファイル」で良いですか?
パス指定の間に「シンボリックリンクされたディレクトリ」を含む場合は期待通りに動きますよね?

**Comment by k-takata** [comment]
todo入りしています。 #241

**Comment by thinca** [comment]
おっと。重複してましたか。失礼しました。

**Comment by koron** [comment]
まだ入ってなかったのか…
