### ISSUE TITLE
cursorline が効きません

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#286]
すいません教えてください。

hi NumBold gui=bold
match NumBold /\d+/
set cursorline

とした場合、数字 (\d+) の部分は
cursorline の背景色が変わらないのですが、
対策を教えてください。

**Comment by thinca** [comment]
Vim の正規表現では `\+` と書く必要があります。

``` vim
hi NumBold gui=bold
match NumBold /\d\+/
set cursorline
```

`:help /\+` も参照してみてください。

**Comment by thinca** [comment]
おっと。ちゃんと質問を読んでませんでした。すいません。
`cursorline` については今のところ対策はちょっと無理かと思います。

**Comment by rickhowe** [comment]
さっそくありがとうございます。
すいません、書き間違えていました。
\d\\+ でダメです。

**Comment by mattn** [comment]
ctermbg か guibg を指定していないからでは？
cursorline の色を上書きしたいという事ですか？ちなみに hi で指定出来る背景色は、マッチ部分右端から画面右端までは塗れないのであしからず。

**Comment by rickhowe** [comment]
この例の場合、数字の部分も cursorline の効果をそのまま維持したいのですが、無理でしょうか？

**Comment by mattn** [comment]
試した感じだと無理そうですね。

**Comment by thinca** [comment]
これは、そういうことができるようになって欲しい、と言う本体への「要望」ってことでいいんでしょうか?
もしそうであればIssueのタイトルをわかりやすいものに変更してもらえるといい感じです。

**Comment by mattn** [comment]
hsとかheみたいな感じでeolまで描くのが欲しい。

**Comment by thinca** [comment]
欲しいですね。
unite.vim とかは、行末までハイライトするためにわざわざ行末までスペースを埋めてます。涙ぐましい…。

**Comment by Shougo** [comment]
はい。私もそういう機能が欲しいです……。

**Comment by rickhowe** [comment]
syn match Num "\d\+"
hi def Num gui=bold
set cursorline

でできたようです。

**Comment by mattn** [comment]
# 深読みしすぎ

**Comment by thinca** [comment]
行末までハイライトの件は別途Issue立てた方が良さそうですね。

**Comment by rickhowe** [comment]
間違って close を押してしまいました。すいません。

**Comment by mattn** [comment]
@ZBryce 意図が違ってて、ZBryceさん個人のissueが解決したのならば閉じた方が良いです。
