### ISSUE TITLE
日本語メッセージファイルの修正

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#288]
日本語メッセージファイルでいくつか気になるところがありましたので修正案を記載します。
1. 文体の統一
   1文の中で文体が混じっているのが気になります。

``` diff
--- a/src/po/ja.po
+++ b/src/po/ja.po
@@ -5208,11 +5208,11 @@

 #, c-format
 msgid "E384: search hit TOP without match for: %s"
-msgstr "E384: 上まで検索したけれど該当箇所はありません: %s"
+msgstr "E384: 上まで検索しましたが該当箇所はありません: %s"

 #, c-format
 msgid "E385: search hit BOTTOM without match for: %s"
-msgstr "E385: 下まで検索したけれど該当箇所はありません: %s"
+msgstr "E385: 下まで検索しましたが該当箇所はありません: %s"

 msgid "E386: Expected '?' or '/'  after ';'"
 msgstr "E386: ';' のあとには '?' か '/' が期待されている"
```
1. コマンドラインヘルプの表示修正

``` diff
--- a/src/po/ja.po
+++ b/src/po/ja.po
@@ -3290,7 +3290,7 @@
 "使用法:"

 msgid " vim [arguments] "
-msgstr " vim [引数]"
+msgstr " vim [引数] "

 msgid ""
 "\n"
```

`vim --help` を実行すると、`[引数]` の後ろにスペースが無いせいで以下のように、次のオプションがくっついて表示されてしまっています。

```
使用法: vim [引数][ファイル..]    あるファイルを編集する
   もしくは: vim [引数]-               標準入力からテキストを読込む
   もしくは: vim [引数]-t タグ         タグが定義されたところから編集する
   もしくは: vim [引数]-q [errorfile]  最初のエラーで編集する
```
1. 漢字・ひらがなの混在
   `見つかる` と `みつかる` が混在しています。
   個人的には `:%s/み\(つ[か-こ]\)/見\1/g` で前者に統一しておきたいです。

**Comment by k-takata** [comment]
追加です。

```
msgid "E23: No alternate file"
msgstr "E23: 副ファイルはありません"
```

`:help E23` すると、`オルタネートファイル` という表記になっていたのでどちらかに統一した方がよいかもしれません。

**Comment by koron** [comment]
1. ありがとうございます。直します。
2. `/msgid .*\s\+"\nmsgstr.*\S"$` こんなパターンで検索して、追加で幾つか直しておきました。
3. ありがとうございます。探したら漢字表記のほうが少ないことにちょっと驚きましたがw
4. `副ファイル` に統一したほうが良いと考えてます。 `オルタネートファイル` って翻訳になってませんし `オルタネート` っていう単語に日本人は馴染みがないでしょう。

**Comment by koron** [comment]
直した commit はこんな感じ。

https://bitbucket.org/koron/vim-kaoriya-vim/commits/b061305a512c05e61fb87bead84c17388c02b04d

本家に送るのはもう少し先にします。

**Comment by k-takata** [comment]
> `副ファイル` に統一したほうが良いと考えてます。

そうなると、ヘルプの修正が必要ですね。

> 直した commit はこんな感じ。

bitbicketでpull requestした方がよかったでしょうか?

**Comment by koron** [comment]
この程度なら良いです。
というか考え方が示されててとても助かります。

**Comment by bsed** [comment]
怎么解决
