### ISSUE TITLE
Vim-jpにVimへのパッチの書き方のページが欲しい＋Vimのソースコードを簡単に紹介したページが欲しい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#29]
私はkaoriyaさん、mattnさんに対する要望なのですが、Vimへのパッチの書き方を解説したページがVim-jpに是非とも欲しいと思っています。
なぜなら、私のようなVim ソースコード初心者はパッチをどのように書けばよいかがよく分からないからです。
お二人はこれまでにいくつもパッチを書いていて、経験も豊富なので、ぜひその知識をみんなに紹介してもらいたいと考えています。

それと、この話題とは若干関係ないかもしれないですが、Vimのソースコードを簡単で良いから解説したページも欲しいです。
昔、私がReal Vim Hacksで若干まとめましたが、やはり現状Webに載っているVimのソースコードの情報は少なすぎます。
http://vim-users.jp/real-vim-hacks-project/
初心者にはどこを変更すればよいのかが分かりにくいです。

**Comment by Shougo** [comment]
そういえば、Vimにパッチを書く場合、
https://github.com/vim-jp/vim-jp.github.com
このリポジトリからforkした方がよいのでしょうか。
githubなら同期しやすいのですが……。

**Comment by mattn** [comment]
まず vim のリポジトリは http://code.google.com/p/vim/ です。最新ソースを取得するには[mercurial](http://mercurial.selenic.com/)をインストールして

```
hg clone https://code.google.com/p/vim/
```

とします。 http://code.google.com/p/vim/source/clones でcloneも作れますが、bramは1つの変更毎に1つのchangesetを作るので、cloneを作る程は必要ないと思います。中平さんの様にbig patchを書かれるならcloneした方が良いかもしれませんが。

この変は、余裕があれば後日ドキュメント化します。

なお https://github.com/vim-jp/vim-jp.github.com は http://vim-jp.org/ のソースです。現状、vim-jpが管理するプロジェクトにはvimのソースは入っていません。これはgithub自身に上記リポジトリを逐次同期する仕組みがないからです。

**Comment by mattn** [comment]
ちなみに簡単な物であれば既にドキュメント化されています。

http://vim-jp.org/docs/build_windows_mingw.html
http://vim-jp.org/docs/build_windows_msvc.html

**Comment by Shougo** [comment]
了解です。まとめを楽しみにしています。
さすがに補完関係は自分でパッチを書くべきだと思うので……。

**Comment by mattn** [comment]
書きました http://vim-jp.org/docs/how_to_write_patches.html
ソースの説明については後日。

**Comment by mattn** [comment]
ソースは後日とは書きましたが、おそらく網羅は出来ないですし、たぶん読んだ方が速いです。

**Comment by Shougo** [comment]
ありがとうございます。助かります。

> ソースは後日とは書きましたが、おそらく網羅は出来ないですし、たぶん読んだ方が速いです。

それでも、資料があるのと無いのでは違うので……。

**Comment by koron** [comment]
@mattn さんもだとは思いますが、正直なところ簡単に解説できるほど習熟はしていません。
というのも自分の仕事でもないですから隅々までは覚えて無いので、必要な時にソースコードを読み返して、
ほとんどの場合、必要以上に広範囲に読んで修正パッチを作ってます。
このあたりはVimとは関係無いくコードリーディング能力ですので、
本で言えばCode Readingあたりで基礎知識を身につけて
ひたすら実践すれば自然と身につくでしょう。というかそれ以上の近道は無いです。

書いたパッチの妥当性についてはレビューをあげてくれれば見ますよ。
基本的には業務でもよくあるタイプのパッチの書き方です。
なぜそれが必要なのか、なぜそれがうまく機能するのか、このあたりが一目でわかることが重要です。
あとは特に既存機能を壊すタイプは避けること、くらいですかね(w

**Comment by Shougo** [comment]
はい。とりあえず、練習がてら一つくらいパッチを作ってみたいところです。
パッチを作る前に、まずIssuesを作ります。
