### ISSUE TITLE
タグジャンプがSEGVで落ちる事がある

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#290]
元記事
なんかvimがセグメンテーションフォルト吐いたんですけど。。
http://kokukuma.blogspot.jp/2013/01/vim-vim.html

OSはlinux(fedora?)でPoderosaでログイン。

いろいろやってみたけど私の環境(fedora16 64bit, vim7.3.761 on PuTTY)では再現せず。

PS
落ちる件とは別に
`:help ctrl-o`
`:help ctrl-i`
を覚えると痙攣して椅子から転げ落ちるよというのはtwitterで連絡済みです。

**Comment by mattn** [comment]
うちも落ちないなー。

**Comment by mattn** [comment]
返事がない

**Comment by koron** [comment]
しかばねのようだ

**Comment by h-east** [comment]
連絡取れないですし、他で同様の報告ありませんのでクローズします。
