### ISSUE TITLE
Kaoriya 版の Vim(GUI) で :set ft すると 「E218: autocommandの入れ子が深過ぎます 」が発生する

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/issues#292]
Kaoriya 版の GUI Vim で起動直後に `:set ft=vim` とすると、以下のエラーが発生します。

```
function <SNR>98_VerifyEncoding の処理中にエラーが検出されました:
行 6:
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
E32: ファイル名がありません
行 7:
E218: autocommandの入れ子が深過ぎます
```
## 再現手順

``` viml
autocmd!
set nocompatible

autocmd FileType * doautoall BufRead " doautocmd でも発生

set fileencoding=utf-8
```
1. 上記の vimrc を作成し、GUI Vim を起動する
2. Vim 起動後に `:set ft=vim` と入力する
3. エラーが表示される

`vimrc` の `:set fileencoding=utf-8` を消せば発生しません。
プラグインで `autocmd FileType * doautoall BufRead` を行っている例として、[vim-unbundle](https://github.com/sunaku/vim-unbundle) というプラグインがあります。
https://github.com/sunaku/vim-unbundle/blob/master/unbundle.vim#L35

`<SNR>98_VerifyEncoding` は kaoriya 版のプラグインの `verifyenc.vim` に定義されてます。
## 質問

`autocmd` で `doautoall` や `doautocmd` を二度行う事で発生したのでしょうか?
これは仕様なのでしょうか?
## 環境

Kaoriya 版の GUI Vim で発生(Windows(適応済みパッチ1-762), MacVim Kaoriya)

**Comment by h-east** [comment]
`E218` については VerifyEncoding() が再帰呼び出ししているのでそれを防げばOK。

再帰呼び出しの流れ
(1)
vim/plugins/kaoriya/plugin/verifyenc.vim : 35
でBufReadPostイベント発生時にVerifyEncoding()が呼ばれるように設定している。

``` vim
autocmd BufReadPost * silent call <SID>VerifyEncoding()
```

(2)
vim/plugins/kaoriya/plugin/verifyenc.vim : 58
でfileencodingオプション設定かつ空ファイル時に自らBufReadPostイベントを発生させている

``` vim
  " Check if empty file.
  if &fileencoding != '' && line2byte(1) < 0
    edit! ++enc=                                       " ※1
    doautocmd BufReadPost
    return
  endif
```

(3)
つまり、fileencodingオプションが設定されており、空ファイル(またはno file)でvimを起動させた後に VerifyEncoding() が呼び出されるような操作をおこなうと再帰呼び出しが起きてエラー(E218)が発生する。

修正patch

``` diff
--- verifyenc.vim.orig  2013-01-09 22:47:05.770059400 +0900
+++ verifyenc.vim   2013-01-09 22:38:33.322749100 +0900
@@ -56,7 +56,10 @@
   " Check if empty file.
   if &fileencoding != '' && line2byte(1) < 0
     edit! ++enc=
+    let g:verifyenc_enable_save = g:verifyenc_enable
+    let g:verifyenc_enable = 0
     doautocmd BufReadPost
+    let g:verifyenc_enable = g:verifyenc_enable_save
     return
   endif
   " Check whether multibyte is exists or not.
```

<br>
エラーE32については名前の付いていないバッファに対して `edit!` を実行しているから。「上記(2)の※1」
名前付いていなかったら処理しないように修正するとかでしょうか。

**Comment by heavenshell** [comment]
@h-east さん
解説 & パッチありがとうございます!
なるほど、再帰してたからでしたか。

> 名前付いていなかったら処理しないように修正するとかでしょうか。

``` diff
--- verifyenc.vim.orig  2013-01-10 00:28:55.000000000 +0900
+++ verifyenc.vim   2013-01-10 00:29:56.000000000 +0900
@@ -55,8 +55,13 @@
   endif
   " Check if empty file.
   if &fileencoding != '' && line2byte(1) < 0
-    edit! ++enc=
+    if bufname('%') != ''
+      edit! ++enc=
+    endif
+    let g:verifyenc_enable_save = g:verifyenc_enable
     doautocmd BufReadPost
+    let g:verifyenc_enable = 0
+    let g:verifyenc_enable = g:verifyenc_enable_save
     return
   endif
   " Check whether multibyte is exists or not.
```

こんな感じにしてみたらエラーが出なくなりました。

**Comment by koron** [comment]
こうするつもりだけど、どうだろう?

``` diff
diff -r 5fb71ee812d8 kaoriya/vim/plugins/kaoriya/plugin/verifyenc.vim
--- a/kaoriya/vim/plugins/kaoriya/plugin/verifyenc.vim  Sun Dec 30 22:33:40 2012 +0900
+++ b/kaoriya/vim/plugins/kaoriya/plugin/verifyenc.vim  Thu Jan 10 00:42:53 2013 +0900
@@ -4,7 +4,7 @@
 "   Verify the file is truly in 'fileencoding' encoding.
 "
 " Maintainer:  MURAOKA Taro <koron.kaoriya@gmail.com>
-" Last Change: 27-Jul-2003.
+" Last Change: 10-Jan-2013.
 " Options: 'verifyenc_enable'  When 0, checking become disable.
 "      'verifyenc_maxlines'    Maximum range to check (for speed).
 "
@@ -49,13 +49,24 @@
   echo 'Verify encoding is *'.(g:verifyenc_enable ? 'ON' : 'OFF').'*'
 endfunction

+function! s:IsDisabled()
+  if !has('iconv') || &modifiable == 0 || g:verifyenc_enable == 0 || exists('b:verifyenc')
+    return 1
+  else
+    return 0
+  endif
+endfunction
+
 function! s:VerifyEncoding()
-  if !has('iconv') || &modifiable == 0 || g:verifyenc_enable == 0
+  if s:IsDisabled()
     return
   endif
   " Check if empty file.
   if &fileencoding != '' && line2byte(1) < 0
-    edit! ++enc=
+    if len(bufname('%')) != 0
+      edit! ++enc=
+    endif
+    let b:verifyenc = 'SUPPRESSED'
     doautocmd BufReadPost
     return
   endif
```

**Comment by heavenshell** [comment]
あ、勘違いしてた。自分のパッチだめです orz

**Comment by heavenshell** [comment]
@koron さん
ありがとうございます! パッチを適応してみた所、エラーが発生しませんでした!

**Comment by h-east** [comment]
@heavenshell 再現手順の確立お疲れ様でした。大変助かります。
@koron おまかせしまーす。

**Comment by koron** [comment]
@heavenshell & @h-east 報告&調査&提案 謝謝!

https://bitbucket.org/koron/vim-kaoriya/commits/fe190480a44237eb9b828cd99c717e2f3cfbd27d

次のリリースにはこの修正版を含めます。

**Comment by mattn** [comment]
@koron please update verifyenc's repo also.

**Comment by koron** [comment]
@mattn 「そんなのあったっけ?」と思ったら https://github.com/koron/verifyenc-vim とか作ってたのね…
すっかり忘れてたw

**Comment by koron** [comment]
Merged koron/verifyenc-vim@28b635cc9ea8e78ad901724a833ff0ae453eabe3 and [vim-kaoriya@eeb37d4](https://bitbucket.org/koron/vim-kaoriya/commits/eeb37d43af6d364a516a6a8b208cc3da4a3f298b)

@heavenshell Please test [this](https://github.com/koron/verifyenc-vim/raw/master/plugin/verifyenc.vim)

っていうか完全に失念してたw

**Comment by koron** [comment]
@mattn Thanks to make me remind it!

**Comment by heavenshell** [comment]
@koron さん
試しました。エラー発生しません。

**Comment by koron** [comment]
@heavenshell Thanks again!

**Comment by thinca** [comment]
https://gist.github.com/3666285#file-vimrc-L2411
これを消す日がついに…! (気付いてたのなら報告しろ)

**Comment by koron** [comment]
リリース済み版 (Windowsのみ) で修正したので閉じます。

**Comment by heavenshell** [comment]
:+1:
