### ISSUE TITLE
gfw 設定時の描画処理が潜在的に遅い

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#293]
#262 より派生

> > DirectWriteだけではなく、通常の描画でも gfw を使うことで遅くなりうるってわけですね?
> 
> だと思います。GDIはDWに比べて1回当たりのオーバーヘッドが少ないのでしょう。

調査の結果 https://github.com/vim-jp/vim/blob/master/src/gui.c#L2410 にある

``` c
if (i + cl >= len || (comping && i > start) || dowide
```

により dowide が設定されている時に常に実行されるため
1文字ずつの描画になっていることが原因だとわかりました。
ここの突入条件を dowide の切れ目までうまく遅延させられれば
まとめて描画され綺麗に決まります。

**Comment by koron** [comment]
https://bitbucket.org/koron/vim-kaoriya-vim-mq-ex/raw/ff3b708f71f4e65523dc9cc54e647a8db863a716/patch-efficient_gfw.diff

こんなパッチ作ってみたけど、どうだろうか?
ざっと書いただけで細部はおかしいのだけど、基本コンセプトはこんな感じ、ということで。

**Comment by koron** [comment]
とりあえず手元で速くなることは確認できました。
dwriteパッチを適用して、本来なら遅くなる状態で。

**Comment by koron** [comment]
[パッチを更新](https://bitbucket.org/koron/vim-kaoriya-vim-mq-ex/src/981479e648db3671da3f33b4466ae30575cf990e/patch-efficient_gfw.diff?at=default)しました。

文字幅が切り替わる所で、切り替わった後の文字を1文字だけ先に描画していたのを止めて、
次の文字幅の切り替わりまでまとめて描画するように修正しました。
`1111122222` という文字列(数字は文字の幅を示す)があった場合、
修正前は `11111` `2` `2222` と3回に分けて描画されてましたが、
修正後は `11111` `22222` と2回で描画します。
描画回数が減るため速度向上が見込めます。

**Comment by k-takata** [comment]
``` diff
+           wide_changed = curr_wide != prev_wide;
```

この行ですが、ループの初回に`prev_wide`の設定が行われていない状態で値を参照しています。

**Comment by koron** [comment]
おっと。宣言位置で初期化したつもりだったw

@k-takata Thanks!

**Comment by koron** [comment]
> ループの初回に`prev_wide` の設定が行われていない状態で値を参照しています。

最新版で修正しました。

**Comment by koron** [comment]
とりあえずこれは投稿した。

https://groups.google.com/d/topic/vim_dev/mJFaMo2ZFoA/discussion

**Comment by k-takata** [comment]
:+1:

**Comment by thinca** [comment]
7.3.781 で速攻で取り込まれました。早いw
https://groups.google.com/d/topic/vim_dev/yChYtjP5wpA/discussion

**Comment by koron** [comment]
これで777狙うべきだったw
