### ISSUE TITLE
netrwが重かったのでパッチを書きました。

### ISSUE THREAD

**Issue by hdoi** [vim-jp/issues#295]
少し軽くなりました。
netrw v142　での事です。
netrw.vim　で

``` diff
7366,7367c7366,7367
<     let filename = substitute(matchstr(filelist,'^.\{-}\n'),'\n', '', 'e')
<     let filelist = substitute(filelist,'^.\{-}\n','','e')

---
>     let filename = substitute(filelist,'\n.*$','','e')
>     let filelist = substitute(filelist,'^.\{-}\n\(.*\)$','\1','e')
```

これで、1万ファイルが入ったディレクトリを開く時、
使用前　70秒
使用後　5秒
という感じになりました。

どなたか、このパッチを公式に知らせてくださいませんか？
誰に知らせたら良いのかわからなかったので、こちらに書かせて頂きました。

**Comment by tyru** [comment]
plugin/netrwPlugin.vimにメンテナのメールアドレス書いてありました。

> Maintainer:   Charles E Campbell, Jr NdrOchip@ScampbellPfamily.AbizM-NOSPAM

drchip at campbellfamily.biz ですね。

**Comment by hdoi** [comment]
ありがとうございました。
送ってみます。

**Comment by mattn** [comment]
vim-dev もCC(逆でもok)して貰えると助かります。

**Comment by mattn** [comment]
あと、出来れば  unified diff で貼った方が良いです。

**Comment by mattn** [comment]
手元の v146 では↑のパッチと同じになってますね。

**Comment by k-takata** [comment]
リンク載せておきます。
https://groups.google.com/d/topic/vim_dev/q8m2UhN1iT0/discussion

**Comment by hdoi** [comment]
見ました。
whileでの処理がforの処理に置き換わっていました。
よりスマートになって良かったです。

**Comment by mattn** [comment]
一旦閉じますか?

**Comment by hdoi** [comment]
そうしましょう。
