### ISSUE TITLE
GVim で set visualbell set t_vb='' したら描画がおかしくなる 

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/issues#299]
以下のように .gvimrc に設定します。

``` viml
set visualbell
set t_vb=''
```
1. GVim を起動します
2. `123` と入力する
3. `<ESC>` でノーマルモードになる
4. `llll` と 左に移動をする
5. 画面に `'` が表示される
6. 以降 `i` 以外を入力すると `'` が画面に表示される

Ubuntu 12.04
Vim7.3 1-547(Aptitude で入れた Vim)

MacVim で同様の設定を行った所、
文字の一部が `'` になります。
カーソルをその文字の位置に移動すると元に入力した文字が表示されます。

**Comment by heavenshell** [comment]
あ、ひょっとして

``` viml
set t_vb=
```

が正しい設定なんですかね…。

**Comment by h-east** [comment]
たぶんそうです。
set t_vb=''
とすると '' というtermコードを発行してしまうのではないかと思いまっす

**Comment by heavenshell** [comment]
ヘルプにもちゃんと書いてました orz

**Comment by heavenshell** [comment]
仕様なので閉じます。
