### ISSUE TITLE
入力文字列を変更してもcompletefuncが呼ばれない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#3]
文字入力後にユーザ関数補完でポップアップを出した後、入力文字列を変更しても補完関数が呼ばれない

vim-dev にて @koron 氏がbram氏と議論中

https://groups.google.com/d/topic/vim_dev/CuJiNWnc08U/discussion

https://groups.google.com/d/topic/vim_dev/LnzUVtYnGoE/discussion

**Comment by koron** [comment]
Bramと議論してcompletefuncにdictを返そうということになりました。
arrayならば既存の動作、dictならば新しい動作。

返すdictの内容のはこんな感じ

```
{
    "refresh": "always",
    "words": [ "foo", "bar", "blah" ]
}
```

こうすれば将来補完時の動作を拡張する際にも対応できるだろう、
という結論です。

**Comment by mattn** [comment]
将来的には、今後作られるAPIなんかも引数や戻り値にdict使っていった方がいいのかもしれないすね。

**Comment by Shougo** [comment]
あー、確かにそっちが柔軟ですね。
となると、大きな仕様変更となるので、Vimのメジャーアップデートくらいで取り込まれる感じになるんですよね。

**Comment by koron** [comment]
いいえ。この仕様変更なら既存のプラグインに影響を与えないのですぐに取り込めます。

**Comment by Shougo** [comment]
もしかして、リストを返すと今までの動作、dictを返すと新しい動作になるということですか。
それなら大丈夫そうです。

**Comment by koron** [comment]
Yes

https://github.com/vim-users-jp/bts/issues/3#issuecomment-2030558 にも

> arrayならば既存の動作、dictならば新しい動作。

書いたとおりです。

**Comment by Shougo** [comment]
あ、確かにそう書いてありますね。となると、あとは実装するだけと。

**Comment by koron** [comment]
実装はできた。あとdocの差分も作んなきゃ、やっぱダメだよなぁ…

**Comment by koron** [comment]
docも適当にでっち上げて送りました。

**Comment by Shougo** [comment]
おお、それはマージが楽しみです。マージされたら真っ先に試します。

**Comment by tyru** [comment]
7.3.311で取り込まれたみたいですね。
https://groups.google.com/group/vim_dev/browse_thread/thread/b4fa552bd731e8c8?hl=ja

**Comment by mattn** [comment]
@koron 閉じますか？

**Comment by koron** [comment]
ああ、ごめんなさい。閉じます。

なんか「ニンニク乗せますか?」みたいだった。
