### ISSUE TITLE
if_ruby 複数バージョン対応化

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#300]
Rubyを複数バージョンに対応させる方法が存在します。
-   https://github.com/splhack/macvim/blob/master/src/if_ruby.c#L18-L26
-   https://github.com/splhack/macvim/blob/master/src/if_ruby.c#L1387-L1475
-   https://github.com/splhack/macvim/blob/master/src/if_ruby19.c

ちゃんとやるか検討しましょう。

**Comment by koron** [comment]
個人的にはrubyは…ねぇ?w

**Comment by mattn** [comment]
起動時に1.8か1.9を動的判断する、という意味でいいですか?

**Comment by koron** [comment]
互換性でゴタゴタしないためにはpyのようにruby18とruby19ってな感じにコマンド分けたほうが良いかも。
まぁこれは理想論ね。
2013/01/30 9:17 "mattn" notifications@github.com:

**Comment by k-takata** [comment]
ruby 1.8ってもうすぐサポート切れますよね？

**Comment by mattn** [comment]
python は py2 と py3 を用意して、`py=py3` みたいな事ができればなーと思う。
それと同じ様に今の ruby は ruby18 にして `ruby=ruby18` から `ruby=ruby19` にスイッチできればなーとか。

**Comment by koron** [comment]
> ruby 1.8ってもうすぐサポート切れますよね？

加えて if_ruby を使ったプラグインが少ないから、やるだけ時間の無駄とも言えるかもw

> python は py2 と py3 を用意して、py=py3 みたいな事ができればなーと思う。

私はそれには反対します。py(2)用に書かれたスクリプトがpy3で実行されると逆に困ると思う。
具体的にはプラグイン作者への問い合わせが増えてめんどそう。

```
py=py3 設定していませんか? 設定していたら外してください
```

みたいなやりとりが発生しそう。

**Comment by koron** [comment]
あ、ちなみに言い出しといてなんですが、個人的にはやらんで良いと思ってます。
なおRubyのWindows(MSVC)版バイナリを公式が配ってたら違う判断をします。

**Comment by mattn** [comment]
```
いつまで py は py2 なんだ
```

って意見がいずれでそう。

**Comment by koron** [comment]
Python 3 を py3 にマップした時の議論ってvim-devに残ってそう (ﾁﾗｯﾁﾗｯ

**Comment by koron** [comment]
ただし py を py3 にマップしちゃうのはVimが提供する互換性の観点からは好ましくないと考えます。

**Comment by raa0121** [comment]
ruby-2.0.0-p0 が出ましたけど、こっちはどうなんでしょうね…

**Comment by mattn** [comment]
かなり難しいと思う。if_ruby.c を if_ruby18.c と if_ruby19.c と if_ruby20.c に分割すれば行けそうだけどw

**Comment by koron** [comment]
やはりそれを必要としている人がどれだけいるか(反語
ってところじゃないですかねぇ

**Comment by koron** [comment]
とりあえず vim-jp としては no touch 決め込みましょう。

やりたい人が現れたらまた開けば良い。

**Comment by Shougo** [comment]
はい。Pythonの場合はそういうモチベーションがあったのかなと。Ruby 1.8自体サポートが切れていて、次はRuby 1.9もサポートが切れる……という状態ですし。
