### ISSUE TITLE
64bit版Vimから一部の64bit版のPythonモジュールを呼び出せない？

### ISSUE THREAD

**Issue by torakichi-jp** [vim-jp/issues#302]
64bit版のVimから、Python for Windows extensionsのモジュールを呼び出そうとすると、R6034エラーが発生します。

環境は

Windows7 64bit
Python2.7 64bit
Vim香り屋版 64bit
Python for Windows extensions (Build 218 win-amd64-py2.7)

です。

経緯ですが、VimからVisual Studioを利用したくて、visual_studio.vim (mattnさんの日本語対応版 http://mattn.kaoriya.net/software/vim/20080819093347.htm) を導入しようとしてうまく行かず。
必要なPythonモジュールがインストールされていなかったということはすぐにわかったのですが、モジュールを入れたら、今度は

---

Runtime Error!

Program: [path to gvim.exe]

R6034
An application has made an attempt to load the C runtime
library incorrectly.
Please contact the application's support team for more
information.

---

というダイアログが出てきてしまいます。
プラグインから import pywintypes しようとしているところで発生しているようです。

事実、Vimから
:py import pywintypes
と実行すると、同じダイアログが出てきました。

pythonインタプリタからのインポートは問題なくできているようでしたので、VimのPythonインタフェースの不具合ではないかなと思います。

**Comment by koron** [comment]
32bit版のVimとPythonの組み合わせなら、動いてそう(少なくともimport)では止まらない、ってことでOKですかね?

**Comment by koron** [comment]
> gvim.exeだけ32bit版に入れ替えたら動くことは動きました

https://twitter.com/torakichi_jp/status/298284550579167233

ありゃPythonは64のままか?

**Comment by torakichi-jp** [comment]
そうですね、Pythonは64のままで、Vimのバイナリだけ32に差し替えたら一応動きました。

**Comment by mattn** [comment]
wow64 ?

**Comment by k-takata** [comment]
自ビルドの64bit GVimで試してみたところ、R6034は出なかったのですが、pywintypes27.dllがロードできないというエラーになりました。
![pywintypes_error](https://f.cloud.github.com/assets/840186/142824/d68363aa-7322-11e2-8fba-191dacae38bf.png)
pywintypes27.dll は C:\Windows\System32 にあるのでなぜロードできないのか不明。
代わりに pywintypes27.dll を python.exe が置いてあるディレクトリにコピーしたところ、`:py import pywintypes`でエラーは出なくなりました。

**Comment by koron** [comment]
補足: ダウンロードはこのへんから http://sourceforge.net/projects/pywin32/files/pywin32/

**Comment by koron** [comment]
VS2010のデバッガでロードしてその出力をキャプチャした。

```
(前略)
'gvim.exe': 'C:\Windows\System32\python27.dll' を読み込みました。Cannot find or open the PDB file
'gvim.exe': 'C:\Windows\winsxs\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcr90.dll' を読み込みました。Cannot find or open the PDB file
'gvim.exe': 'C:\Local\Python\Python27\Lib\site-packages\win32\_win32sysloader.pyd' を読み込みました。Cannot find or open the PDB file
'gvim.exe': 'C:\Windows\System32\pywintypes27.dll' を読み込みました。Cannot find or open the PDB file
'gvim.exe': 'C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64\msvcr90.dll' を読み込みました。Cannot find or open the PDB file
```

ここまで出た所でエラーで止まった。
その後、ダイアログを進めるとこんな感じ。

```
'gvim.exe': 'C:\Windows\System32\pywintypes27.dll' をアンロード
'gvim.exe': 'C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64\msvcr90.dll' をアンロード
```

その後OpenCL SDKを無効化して再度試したら、こんどはMercurialのに引っかかった。

**Comment by koron** [comment]
MSVCR90.DLLが2回ロードされることが原因っぽい。
同じ事を python.exe についてやると

```
(前略)
'python.exe': 'C:\Windows\winsxs\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcr90.dll' を読み込みました。Cannot find or open the PDB file
'python.exe': 'C:\Windows\System32\imm32.dll' を読み込みました。Cannot find or open the PDB file
'python.exe': 'C:\Windows\System32\msctf.dll' を読み込みました。Cannot find or open the PDB file
'python.exe': 'C:\Local\Python\Python27\Lib\site-packages\win32\_win32sysloader.pyd' を読み込みました。Cannot find or open the PDB file
'python.exe': 'C:\Windows\System32\pywintypes27.dll' を読み込みました。Cannot find or open the PDB file
'python.exe': 'C:\Windows\System32\ole32.dll' を読み込みました。Cannot find or open the PDB file
'python.exe': 'C:\Windows\System32\oleaut32.dll' を読み込みました。Cannot find or open the PDB file
```

こんな感じになって2度めの Load は発生しない。

**Comment by koron** [comment]
pywintypes27.dll を読み込むときに、
本来なら MSVCR90.DLL は **SxS から読み込み済み** としてスルーしなきゃいけないのに
Vim からやった場合は無いものとして PATH から読み込もうとしているっぽい。

こっから先はなんでそうなるのか、誰か詳しい人頼む

**Comment by k-takata** [comment]
pywintypes27.dll の埋め込みマニフェストが変なことになってるとかですかね？

**Comment by k-takata** [comment]
[Resource Hacker](http://www.angusj.com/resourcehacker/) で確認したところ、pywintypes27.dll には SxS 用のマニフェストが埋め込まれていませんでした。

**Comment by koron** [comment]
つまりざっくり整理&推理すると… **exe に SxS マニフェストが含まれている場合は該当 DLL の2重ロードは回避され、含まれない場合は2重ロードが起こってしまう** っていうことですかね。

だとすれば pywintypes27.dll にマニフェスト無理矢理埋め込んじゃうのが良いのかな?

**Comment by k-takata** [comment]
> だとすれば pywintypes27.dll にマニフェスト無理矢理埋め込んじゃうのが良いのかな?

埋め込んでみたところ、問題なくロードされました。（埋め込まずに外部マニフェストでも良かったのかもしれませんが、未確認。）
ということで、Python for Windows extensionsの64bit版DLLにマニフェストが埋め込まれていないのが原因と考えて問題ないでしょう。

**Comment by koron** [comment]
では **マニフェスト埋め込んでもらってよ～** で FA ということで閉じましょう。

**Comment by koron** [comment]
@torakichi-jp さん: というわけで Python for Windows extension 側に対応してもらうか、手元でマニフェスト埋め込んで対応してみてください。

@k-takata さん: 埋め込む手続きのインストラクションをざっと書き下せますかね?

**Comment by k-takata** [comment]
以下を pywintypes27.dll.manifest という名前を付けて保存。

``` xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC90.CRT" version="9.0.21022.8" processorArchitecture="amd64" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```

Resource Hacker で pywintypes27.dll を開いて、メニューから Action → Add a new resource。
Open file with new resource ボタンを押して、pywintypes27.dll.manifest を選択。
ダイアログに以下のように入力。

Resource Type: 24
Resource Name: 2
Resource Language: 1033

Add Resouce ボタンを押下。
メニューから File → Save。

**Comment by koron** [comment]
@k-takata :+1: Thank you very much!

**Comment by torakichi-jp** [comment]
了解です。ご対応くださりありがとうございました。

**Comment by torakichi-jp** [comment]
あ、ちなみに32ビット版のほうは、そもそもhas('python')が0だったのでVim側からは呼べるはずがなかったのでした。
この場合、スクリプトが直接Pythonを呼んでいたために呼び出せていたように見えていただけで、VimのPythonサポートとは全然無関係でした。
お騒がせしました。

**Comment by k-takata** [comment]
Linking against the multithreaded DLL runtime
https://groups.google.com/d/topic/vim_dev/2_HEyaYJnkk/discussion
よく似た話題がvim_devに。しかし、その直し方はどうかと。

**Comment by k-takata** [comment]
Issue 7833: bdist_wininst installers fail to load extensions built with Issue4120 patch - Python tracker
http://bugs.python.org/issue7833
この件、python (pywin32)側のバグとして登録されているようですね。長くて結論がどうなったのかよく分かりませんが。

**Comment by koron** [comment]
Vim 外で対応すべき問題であったため worksforme に振り替えておきます。
