### ISSUE TITLE
+kaoriya版の :Tutorial 実行時にSyntaxErrorが発生する

### ISSUE THREAD

**Issue by maaru** [vim-jp/issues#303]
#131 の中で修正されたコードにSyntax Errorがあるようで、実行時に

「余分な文字が後ろにあります」といったエラーが表示されます。
else if -> elseif に修正したところ、正しく動作しているようです。

```
  " Japan special
  if $LANG =~ '^ja'
    let enc = 'utf-8'
    if &encoding ==# 'cp932'
      let enc='sjis'
    else if &encoding =~ 'euc'
      let enc = 'euc'
    endif
```

**Comment by koron** [comment]
Thanks! 今夜にも直します。

**Comment by koron** [comment]
遅くなって申し訳ない。修正完了。

**Comment by koron** [comment]
リリースしました。

**Comment by koron** [comment]
修正したコミット: https://bitbucket.org/koron/vim-kaoriya/commits/e50d63090519684407dc76fadc6c0916

**Comment by maaru** [comment]
修正ありがとうございます！
早速、Vimのチュートリアルから勉強中です。
また何か見つけたら報告します。

**Comment by koron** [comment]
@maaru 報告ありがとうございます&今後もよろしくお願いいたします!
