### ISSUE TITLE
:simalt ~<CR>でウインドウメニューを表示させた後、<Esc>を押すと入力待ちになる

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#304]
## 再現方法
1. `:simalt ~<CR>`でウインドウのメニューを表示
2. `<Esc>`を押す
3. `getchar()`を呼んだ時みたく、1文字だけ入力待ちの状態になります
4. 何か1文字入力すると、ノーマルモードに戻ります
## 環境

Windows 7
Vim +kaoriya 7.3.797 (現時点での64bit版最新バイナリ)

**Comment by mattn** [comment]
なんか余計なキー待ちしてるのかな。

**Comment by k-takata** [comment]
スペースとかカーソルキーを押してみると分かりますが、メニューバーにフォーカスがある状態のようですね。仕様？

**Comment by mattn** [comment]
SC_CLOSEが取れないな

**Comment by ynkdir** [comment]
Alt-F などの普通のメニューでも同じです
notepad も同じ動作です。

**Comment by mattn** [comment]
ほんまや。メモ帳も1文字食われてる。
って事でclosable?

**Comment by mattn** [comment]
それよりも、すごく昔からあるバグなんやけど `:simalt ~x` すると

![](http://go-gyazo.appspot.com/148179d0c6edd214.png)

こうなるバグを直したい。

**Comment by ynkdir** [comment]
うちはならないですね > `:simalt ~x`

feedkeysもどきできた `:simalt ~r:echo~'hello'<C-V><CR><CR>`

**Comment by mattn** [comment]
```
:simalt ~r:echo~'hello'^M
```

で良くないすか？

**Comment by mattn** [comment]
ちなみに↑の、たまにだけなるんですよ。イベントが交錯してるのかと。

**Comment by ynkdir** [comment]
`<C-V><CR>` は `^M` のつもりで書きました。

たまにですか。やっかいですね。

**Comment by tyru** [comment]
> Alt-F などの普通のメニューでも同じです
> notepad も同じ動作です。

おお・・・本当だ・・・
じゃあissue自体は閉じちゃって構わないですか？ >ALL

**Comment by mattn** [comment]
ok

**Comment by tyru** [comment]
ちなみに自分のだとなりませんでした。>`:simalt ~x`
