### ISSUE TITLE
Ctrl-x modeのメッセージを出さずにポップアップメニューのみ表示したい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#305]
https://github.com/Valloric/YouCompleteMe/issues/39

ここで挙げられていた要望です。

確かに、自動補完をしていると Ctrl-x modeのメッセージ領域はうるさく感じられます。
現在は補完がキャンセルされた時のみメッセージを出さないことはできますが、メッセージを出さずにポップアップのみを出すことはできません。

ただ、これを実装するにはいろいろと難点もあり、
1. メッセージを出さないのはオプションにするのか、それとも他の方法なのか（例：feedkeys()をsilentで呼び出した時など）
2. ポップアップが出ていない時も、Ctrl-x modeに入っている時がある。メッセージがないと判別ができなくなり、妙な挙動に見える可能性が……。（別Issue にしました。 https://github.com/vim-jp/issues/issues/307）
3. そもそも Bram 氏を説得できるのか？

**Comment by koron** [comment]
本件、私はあまり乗り気ではないので、アドバイスだけ。
- 自動補完に絡めず
- OmniやUser definedな補完の時にどういう補完が実行されているのかわからないのは不便だ
- だからメッセージを補完関数の方から指定できるようにすれば便利だよね

という文脈であれば賛同を得やすいと考えます。

**Comment by Shougo** [comment]
> だからメッセージを補完関数の方から指定できるようにすれば便利だよね

はい。私も単純にメッセージを表示しないというのではなく、実はこのような提案が欲しかったのです。
KoRoNさんも度々指摘されているように、現在の補完機構は自由度が少ないので、我々の手でより良い仕様を考えていければと。

> ポップアップが出ていない時も、Ctrl-x modeに入っている時がある。メッセージがないと判別ができなくなり、妙な挙動に見える可能性が……。

そもそも、この問題に関しては「ポップアップメニューが出ていなくてもCtrl-x modeのままであるときがある」仕様に問題があると考えています。本件とは別に議論したいところです。

**Comment by Shougo** [comment]
Ctrl- x modeに入りっぱなしになる件は別のIssueにしました。

https://github.com/vim-jp/issues/issues/307

**Comment by Shougo** [comment]
KoRoNさんが以前追加してくれた、補完関数のdictを拡張してメッセージメンバを追加すると良さそうです。

message or description : 省略されるとデフォルトのまま。補完時に表示されるメッセージを指定できる。空文字列を渡すとメッセージを消せる。

最近、ユーザ定義補完を使用するプラグインも増えてきているため、自動補完以外にも応用できるはずです。

**Comment by Shougo** [comment]
補完時のメッセージを消したいだけなら、こうする手もあることに気づきました。

```
hi ModeMsg guifg=bg guibg=bg
```

まぁ、挿入モード時のメッセージも消えますが……。

**Comment by tyru** [comment]
なるほど。その発想はなかった。

**Comment by Shougo** [comment]
ただ、これだと「Back to the original」等のメッセージはまだ残ります。根本的な解決にはならないかと。

**Comment by Shougo** [comment]
http://blog.basyura.org/entry/2013/08/17/154700

> ただ、これだと「Back to the original」等のメッセージはまだ残ります。根本的な解決にはならないかと。

「Back to the original」は

```
hi WarningMsg guifg=bg
```

で消去できるようです。WarningMsgはそれなりに使用されるので、弊害も多そうですが……。

**Comment by Shougo** [comment]
最近、自動補完と絡めずにこの機能がほしいと感じました。
補完時にコマンドラインが上書きされますが、この機能により補完時に上書きされないようにできれば
コマンドラインに関数の引数を表示したり、コマンドライン部分の応用範囲が広がるように感じます。

**Comment by Shougo** [comment]
色々検討したのですが、補完関数にオプションをつけるよりも 'showpummode' というオプションを追加したほうが良いのではないかと思いました。任意の補完時にメッセージを表示してほしい人としてほしくない人がいると考えたためです。ソースコード上でもそちらのほうが修正が少なくて済みます。モード情報を表示しない'showmode'の派生オプションと考えれば問題はないのではないでしょうか。

当然補完状態の判別は見た目付きづらくなりますが、showmodeもそれは同じですし自己責任でしょう。

**Comment by mattn** [comment]
shortmess に別の値追加する方が楽じゃないかな。

**Comment by Shougo** [comment]
あ、たしかにそのとおりですね。ありがとうございます。
早速実装をやってみようと思います。

```
フラグ   効果  ~
      p            ポップアップメニュー (|ins-completion-menu|) 表示時のメッセージを表示しない
```

こんなかんじで。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/7703062

実装しました。shortmessにcを追加すると有効になります。
一応動作することを確認していますが、なぜか`set noshowmode`されている場合には効果がありません。
できればそちらにも対応したいですが、どう修正すればよいかが分からず……。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/7703062

shortmessの問題を解決しました。更に、コマンドラインウインドウのクリア処理はshortmessの値をチェックするようにしました。これで無駄な再描画を抑制できます。
ほぼ完成です。できれば、他の方にも動作確認をおねがいします。

**Comment by Shougo** [comment]
https://groups.google.com/forum/#!topic/vim_dev/WeBBjkXE8H8

パッチを投稿しました。

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/WeBBjkXE8H8/s0CRGNAQKMQJ

返信がきました。

> Thanks.  I think the help for the flag needs some more explanation. An example would be best. 

とあるので、ドキュメントに追記しようと思います。
例には自動補完をあげてよいのだろうか？

**Comment by Shougo** [comment]
ドキュメントのdiffのみ更新しました。もう一度提出します。

**Comment by Shougo** [comment]
再提出Done

https://groups.google.com/d/msg/vim_dev/WeBBjkXE8H8/bXm3dvpMQvcJ

**Comment by Shougo** [comment]
Bram氏のレビューは終わりました。近々、todoリストに入るのではないかと思います。
todoリストに入り次第、こちらはクローズします。

**Comment by h-east** [comment]
TODOリストに入りました。

> Patch to add flag to shortmess to avoid giving completion messages.
> (Shougo Matsu, 2014 Jan 6)

**Comment by Shougo** [comment]
確認ありがとうございます。

**Comment by Shougo** [comment]
https://groups.google.com/forum/#!topic/vim_dev/k0PZmZ1DXzs

Vim 7.4.314 に入りました！
