### ISSUE TITLE
VimのDLL化 for Windows

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#306]
gvim.exe と vim.exe には共通のバイナリコードが多い。
その部分を vim.dll みたいにできないだろうか。
できれば配布サイズが(少しは)小さくなる。

UNIXは1バイナリで、起動時の名前変えるだけでできるのだから。

**Comment by raa0121** [comment]
これはやってみたいですねぇ
MingwやCygwin、VC++のMakefileと*nixなMakefileを両方読んで、
かつVimのコードに手を付けないといけないんでしょうね…

**Comment by koron** [comment]
@raa0121 やって～。とりあえずVCだけかMinGWだけで動くもの作って、公開したらみんながいじってくれるかも。

**Comment by ujihisa** [comment]
raa0121++

**Comment by thinca** [comment]
raa0121++

**Comment by raa0121** [comment]
早速包囲されてる…
今Make_mvc.makを読んでます…

**Comment by raa0121** [comment]
https://github.com/vim-jp/vim/blob/master/src/main.c#L153 に
`# ifdef VIMDLL` を発見 これはすでに計画はされていたってことですかね

**Comment by k-takata** [comment]
> `# ifdef VIMDLL` を発見 これはすでに計画はされていたってことですかね

Make_bc5.mak を見ると、VIMDLL に関する設定がありますね。現状、gvim の DLL 化しかできない様子。
（そもそも今のバージョン、BorlandC 5.5でビルドしてもまともに動きませんがｗ）

**Comment by koron** [comment]
これ、誰か過去にやってみた人、いませんか?
やってみたけどココがダメで諦めたみたいな情報があると嬉しいです。

**Comment by mattn** [comment]
だいぶ昔ですが、一度ビルドできた記憶はあります。単にメンテされなくなったってだけかも。

**Comment by koron** [comment]
Borland 使ってた頃です?w

**Comment by mattn** [comment]
ですw

**Comment by k-takata** [comment]
Embarcadero C++でビルドできたけどDLLは試してない。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/1adb80be73e3273124f1a447d37c1cb95116408e/embarcadero.patch?at=default

**Comment by k-takata** [comment]
方針としては、`#if(n)def FEAT_GUI(_MSWIN)` なコードは `VIMDLL` がdefineされているときはすべて有効にした上で、必要に応じて `if (gui.in_use)` で処理を切り替えるといった感じかな。

**Comment by k-takata** [comment]
[8.1.1066](https://groups.google.com/d/topic/vim_dev/1iII4HlJSCk/discussion) で `VIMDLL` は削除されました。
関連: https://github.com/vim/vim/pull/4171#issuecomment-477773991

**Comment by k-takata** [comment]
vim-jp/vim リポジトリに vimdll ブランチを作って、作りかけをコミットしてみました。 vim-jp/vim#4
今のところ、MSVCのみの対応。一応 gvim.exe と vim.exe はできて起動はするものの、vim.exe 上のターミナルなど一部動作がおかしいところがあります。

参加したい方は勝手に vimdll ブランチを伸ばしていって構いません。

**Comment by k-takata** [comment]
できたDLLのサイズは元のgvim.exeとほぼ同じで、gvim.exeとvim.exeのサイズはどちらも90KB弱なので、トータルのファイルサイズは、ほぼ元のvim.exeの分だけ減っています。

**Comment by k-takata** [comment]
だいたい動くようになった気がします。
ただ、vim.exe を 256色モードで動かすと(`:set t_Co=256 notgc`)、ターミナルの色がR/B逆になってしまいます。`RGB`マクロの定義がGUI/CUIで逆になっているのが問題なのですが、どこをどう直せばいいのかがさっぱり分かりません。

**Comment by ghost** [comment]
256色のインデックスカラーと RGB マクロの正逆に関連性はないので、terminal.c の ansi_index の赤青逆転をしている部分は ifdef ごと削除できます。

**Comment by k-takata** [comment]
これのことを言っていますか？ https://github.com/vim-jp/vim/pull/4/commits/dedd34dedeab1719e4da0c0d14454c59e8b83162
これを入れないとなぜか16色モードでR/Bが逆転するんですよね。
どこかで根本的に不整合が起きているのかもしれませんが、どこかが分からず…。

**Comment by ghost** [comment]
conhost の16色モードは、本来簡単には色は出せません。Vim 独自のもどきシーケンス ```(^[|%dm)``` が ```mch_write``` での fake bios による解釈にかかり、最終的に ```SetConsoleTextAttribute()``` に落とし込まれて発色しています。

本来なら ```notgc``` で ```ENABLE_VIRTUAL_TERMINAL_PROCESSING``` をオフにして ```^[48;5;%dm``` 系の 
 SGR シーケンスを無効にするのが筋として正しいことにさっき気づきましたが、そこまで突っ込んではいませんでした。

現状なぜ逆転するのかは、conhostV2 の内部仕様の問題なので、Vim などのアプリケーションレイヤでは根本対処はできないと思われます。

**Comment by k-takata** [comment]
GUIとCUIのコードを1つのDLLにまとめたところ、R/Bが逆転するようになったわけで、アプリケーションレイヤで対処ができないというのは理屈が通らないと思います。

**Comment by ghost** [comment]
あーいえ、16色モードにはエスケープシーケンスは存在しません、という話でして、vim.exe が t_Co=16 の時に :terminal の方は t_Co=256 で運用しなければならないということなんでしょうか？(;´Д`)

**Comment by ghost** [comment]
さらに検討してきます。すみません…。

**Comment by k-takata** [comment]
> これのことを言っていますか？ [vim-jp/vim@dedd34d](https://github.com/vim-jp/vim/commit/dedd34dedeab1719e4da0c0d14454c59e8b83162)
> これを入れないとなぜか16色モードでR/Bが逆転するんですよね。

16色モードのみR/Bを入れ替えて256色モードではそのままにしたら意図した色が出ました。が、なぜそうなるのかが分からない…。

**Comment by tsuyoshicho** [comment]
https://github.com/vim-jp/vim/blob/e4fa975987cdd0755ca42cbaaf814d9678e01ea2/src/terminal.c#L3574-L3616

ntakさんが話題にしてるのがこれかな(気になったので)

**Comment by tsuyoshicho** [comment]
あと1点気になった所...

[Vim patchダイジェスト \[2019/02\] \- Qiita](https://qiita.com/h_east/items/5d7ee6ddddda2669c409)
patch 8.1.0949: https://github.com/vim/vim/commit/0472b6d149445579e3a63519b15f099f9adda3f7
の修正的に MS-Windows GUIで FEAT_GUIは定義されないように思うので

https://github.com/vim-jp/vim/blob/e4fa975987cdd0755ca42cbaaf814d9678e01ea2/src/ex_docmd.c#L9372-L9373

の変更ってアリなんでしょうか? (元のソース的にはMSWINなら無条件にやってるような https://github.com/vim-jp/vim/blob/905dd905debfde403b2a18178ccc1f8e118f4f2b/src/ex_docmd.c#L9372-L9376 )

see comp https://github.com/vim-jp/vim/compare/master...vim-jp:vimdll

**Comment by k-takata** [comment]
`FEAT_GUI_MSWIN` (やその他の `FEAT_GUI_*`) が define されているなら vim.h で `FEAT_GUI` が define されます。

**Comment by tsuyoshicho** [comment]
う...すみません、お手数かけました。
patch ダイジェストの説明+変更から類推してしまったのはよくなかったです。

**Comment by k-takata** [comment]
一応把握していた問題は全て解消しました。
（しかし、16色モードでterminalの色が逆になる原因は相変わらず不明。）

**Comment by k-takata** [comment]
今頃気づいたのですが、そもそもVIMDLL対応前の元々の状態で、16色モードでR/Bが逆転しているようです。

**Comment by k-takata** [comment]
こうすべき？

```diff
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -2434,7 +2434,7 @@ color2index(VTermColor *color, int fg, i
     {
 	/* First 16 colors and default: use the ANSI index, because these
 	 * colors can be redefined. */
-	if (t_colors >= 16)
+	if (t_colors != 16)
 	    return color->ansi_index;
 	switch (color->ansi_index)
 	{
```

ANSIエスケープシーケンスのインデックスとWindowsの16色のインデックスはそもそも一致していないので調整が必要なのに、それが効いていなかったみたい。

**Comment by ghost** [comment]
１文字！(;´Д`)深い…

**Comment by k-takata** [comment]
16色モードでR/B逆転の件はPRを出しました。 https://github.com/vim/vim/pull/4229

**Comment by k-takata** [comment]
vim.exe でマウスが動かないことが判明…

**Comment by k-takata** [comment]
マウス直った。

**Comment by k-takata** [comment]
`vim.exe -g` でGUIウィンドウが開くようになりました。コンソールを切り離さないので実用性はありませんがｗ

**Comment by k-takata** [comment]
`vim -g` を実行したときに `FreeConsole()` でコンソールを切り離してみたが、プロセスが終了するまで cmd.exe のプロンプトが戻ってこないようなので、やはり実用性がない。残念。
関連: #602

**Comment by nocd5** [comment]
すごい、`:gui`ができる！

**Comment by k-takata** [comment]
`:gui -f` は実現できるかもしれませんね。`:gui -b` は、gvim.exe を別プロセスで起動しなおす方法でなければ実現は無理そうです。

**Comment by k-takata** [comment]
何もせずに `:gui` が動いた！（forkしないので、`:gui -f` 相当だけどｗ）

**Comment by k-takata** [comment]
`vim -g` で、コマンドラインをそのまま `gvim.exe` に渡してGUIを起動するようにした。
`:gui` では、セッションを一時ファイルに保存して、`gvim.exe` を起動してセッションを復元するようにした。
`vim -gf`, `:gui -f` は今まで通り、vim.exeが直接ウィンドウを表示。

**Comment by k-takata** [comment]
現状のファイルサイズ (VC2015 32bit版、スタティックリンク):

| | VIMDLL=no | VIMDLL=yes |
|-|-------:|-------:|
| gvim.exe | 2,841,088 | 85,504 |
| vim.exe | 2,679,296 | 88,064 |
| vim32.dll | - | 2,867,712 |
| **Total** | 5,520,384 | 3,041,280 |

2.4MBほどの削減になってます。

**Comment by k-takata** [comment]
MinGW にも対応しました。

**Comment by k-takata** [comment]
PRed: https://github.com/vim/vim/pull/4287

**Comment by nocd5** [comment]
`9d18c1168`しか確認できてませんが
`gvim.exe --serverlist`でダイアログが表示されません。
`vim.exe -g --serverlist`だと標準出力に出力されます。
`--help`はダイアログが表示されます。
もしかしたら #1060 関係ありますかね？

**Comment by k-takata** [comment]
https://github.com/vim-jp/vim/pull/4/commits/01763d7b316ed336834b5648b5c95f33ca911b5a#diff-ec6011c80b211a3eb412c834fa37f1b0R625
ここの条件判定で、`gui.in_use` も `gui.starting` もどちらも FALSE になっていますね。困りました。

**Comment by k-takata** [comment]
main() の中で、exec_on_server() の後、parse_command_name() を呼んでいるのを、逆順にすると出るようになりますが、それでいいのか微妙です。
サーバー関連の引数は他の引数より先に、exec_on_server() の中で解析されているようです。

**Comment by k-takata** [comment]
実行ファイルのsubsystemを解析して、GUIならば exec_on_server() より前に gui.starting フラグを立ててしまうのがいいかな。これならWindows以外には影響ないので。

**Comment by k-takata** [comment]
上に書いた方法で強引に直しました。（gui.starting を設定する位置を前にずらしたことによる影響が若干心配。）
副作用で、VIMDLL有効の場合に限り #1060 がエラーではなくinfoとして表示されるようになります。

**Comment by nocd5** [comment]
ついて行けてない上に手元に動作環境もなく、言うだけになってしまいすいません…

**Comment by k-takata** [comment]
8.1.1230: https://github.com/vim/vim/commit/afde13b62b8fa25dac4635d5caee8d088b937ee0

**Comment by k-takata** [comment]
追加修正
8.1.1239: https://github.com/vim/vim/commit/a9dd2d3c759c1eafb9c0572c5707852ed3d38162 (https://github.com/vim/vim/pull/4318)

**Comment by k-takata** [comment]
追加修正
8.1.1269: https://github.com/vim/vim/commit/ed5ab2a95972b5ef588bdafab9f197e1dcf0c1df (https://github.com/vim/vim/pull/4330)

**Comment by k-takata** [comment]
追加修正
8.1.1301: https://github.com/vim/vim/commit/0b75f7c97cd7f2529884c48dca8edb02abda4bc5 (https://github.com/vim/vim/pull/4361)

**Comment by k-takata** [comment]
Windows以外用追加修正
8.1.1358: https://github.com/vim/vim/commit/386b43e59498cc7b52a60f09f74bdb44df99386c (https://github.com/vim/vim/pull/4396)

**Comment by k-takata** [comment]
追加修正
8.1.1369: https://github.com/vim/vim/commit/294d9bf966bbbcb0b49affb9b15534d5b9c93801 (https://groups.google.com/d/topic/vim_dev/CNIODLeIt54/discussion)

**Comment by k-takata** [comment]
追加修正
8.1.1380: https://github.com/vim/vim/commit/fa8f861957f4f9f7a0946d9d61fe90a9882f54e6 (https://github.com/vim/vim/pull/4422)

**Comment by k-takata** [comment]
追加修正
8.1.1595: https://github.com/vim/vim/commit/88c47aa692a4b1061f86624ea2503f31314f3975 (https://github.com/vim/vim/pull/4588)

**Comment by k-takata** [comment]
追加修正
8.1.2361: https://github.com/vim/vim/commit/310c32e8920140f0db747c6c6eb06b1ee53cdb5a (https://github.com/vim/vim/pull/5283)

**Comment by k-takata** [comment]
追加修正
8.2.0055: https://github.com/vim/vim/commit/257a396879ff67a0482841a39237f30a8e1e27c5 (https://github.com/vim/vim/pull/5408)
