### ISSUE TITLE
Windows で gvim -f が効かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#309]
OS は Windows 7 64bit、Kaoriya版 gVim 7.3.806 64bit 版で確認。

```
gvim -u NONE -i NONE -f
```

これで gvim を実行してみたところ、gVim が起動したあとに端末側では処理が戻ってきてしまいます。-f が効いてないっぽいです。

**Comment by koron** [comment]
極論、これはUNIXで期待されるようには実装できないはずなので、制限事項としてドキュメント更新したほうが良さそう。

過去に試した限りでは -f を(一見)使えるようにすると、通常の起動時に毎回使いもしない(使えもしない)コンソールが開くとかそういうことになった。

**Comment by koron** [comment]
起動時に常に [GetConsoleWindow](http://msdn.microsoft.com/en-us/library/windows/desktop/ms683175.aspx) でコンソールの有無を確認して
あれば FreeConsole して、あっても -f なら FreeConsole しないみたいなロジックで実装できるんだろうか?

**Comment by mattn** [comment]
エクスプローラ等から起動された時点でWinMainなプロセスは親プロセスからデタッチされてると思うので、コンソール無いと思う。一瞬コンソールが見えていいなら、解決方法が無い訳ではないが、これをやるとjvimの二の舞になる。

**Comment by koron** [comment]
http://msdn.microsoft.com/ja-jp/library/vstudio/fcc1zstk.aspx

ココに書かれているLINKのSUBSYSTEMの値次第で、起動時にCONSOLEが作られるか、切られるかが決まったはず。
選択できる値は具体的には CONSOLE か WINDOWS のみ。

記憶では…
-   CONSOLE の場合、親プロセスに CONSOLE があればそれを継承&利用する。
  なければ常に作成して CONSOLE が表示される。
-   WINDOWSの場合、親プロセスに CONSOLE があれば FreeConsole する。
  なければそのまま起動。

後者はもしかしたらブートストラップコードの中で FreeConsole してたかも。
ならそこをすげ替えればうまくいく? だれか詳しい人プリーズ。

**Comment by koron** [comment]
@mattn 

> これをやるとjvimの二の舞になる。

((((；ﾟДﾟ))))ｶﾞｸｶﾞｸﾌﾞﾙﾌﾞﾙ

**Comment by mattn** [comment]
ちなみにパイプを使うとシェル(cmd.exe)がデタッチせずにプロセスを起動してくれるので、

```
dir | gvim -
```

はできてるはず。

**Comment by koron** [comment]
> パイプを使うとシェル(cmd.exe)がデタッチせずにプロセスを起動してくれる

それってつまり CreateProcess で「おっとコイツはデタッチしないでね」みたいに制御できるってことですか?

**Comment by mattn** [comment]
`DETACHED_PROCESS`

**Comment by mattn** [comment]
ちなみにjvimがやってたのはこれ

http://d.hatena.ne.jp/hasegawayosuke/20091207/p1

```
if( IsGUI() ){ // 親プロセスが cmd.exe でなければTRUE
    ShowWindow( GetConsoleWindow(), SW_HIDE );
    // Run as GUI application
```

なので一瞬アレが見える。

**Comment by k-takata** [comment]
待ちたいなら、Windowsだと呼び出す側が制御しないといけないんですよね。

```
start /wait gvim -u NONE -i NONE
```

とか。

**Comment by koron** [comment]
ここまでの情報を鑑みると、やはりWindows においては -f を実装するすべが無いということで
制限事項としてドキュメントに記載する方向で良いだろう。

異論があれば書いてください。

**Comment by mattn** [comment]
@thinca 閉じて良いです？

**Comment by thinca** [comment]
> ここまでの情報を鑑みると、やはりWindows においては -f を実装するすべが無いということで
> 制限事項としてドキュメントに記載する方向で良いだろう。

この方向かと思ったんですが、なにもしないんですか?

**Comment by mattn** [comment]
あードキュメント弄るのね

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/040urJoJLQE/xAA9sdspN98J

適当に送っといた。

**Comment by k-takata** [comment]
7.3.998 と 7.3.1087 直後のコミットでドキュメントが修正されました。
上記のスレッドで -f が効くと言っている人がいましたが、そのようなバッチファイルが入っていたとのことです。
