### ISSUE TITLE
libcall()の改善

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#31]
現在のlibcall()は引数を一つしか取れません。
そのうえ、戻り値が一つのみで、まともに使うにはパースが必要です。

vimproc()はそれを回避するべく内部でエンコード・デコードをしていますがその代償に処理が遅くなっています。
libcall()の引数をリストにできるようにしたいと思っています。
さらに、戻り値としてリストを返せる関数を用意したいです。
ただ、実装はかなり難しそう……。

**Comment by mattn** [comment]
libcallを弄らなくても実現可能です。

https://github.com/mattn/libcallex-vim
http://mattn.kaoriya.net/software/vim/20100618013325.htm

**Comment by Shougo** [comment]
うーん、非標準なのが難点ですね。一緒にビルドしないといけないし。
どうにか本家に取り込ませることはできないんですか？
libcall()の改善についてはtodo.txtにも書いてあるわけですし。

**Comment by mattn** [comment]
> うーん、非標準なのが難点ですね。一緒にビルドしないといけないし。

それはvimprocも同じですね。

引数が１つだから戻り値が１つ...っという部分の意味が分かりません。C言語を知っておられるなら「意味が分からない」と言ってる意味分かってもらえるかと思います。

それとも配列の事言ってます？そうだとすれば、配列のサイズはどうするんですか？固定配列？配列のメモリを動的確保した場合、誰が開放する？配列の型は？libcallの戻り値が配列である事をどうやって認識する？

とおそらく思っておられる程、簡単な問題じゃないです。

**Comment by Shougo** [comment]
> それはvimprocも同じですね。

はい。そうなんですけど、例えばvimprocがlibcall_exを使おうとすると依存関係が大変になるのです。
だから標準にならないかなーと思っています。

> 引数が１つだから戻り値が１つ...っという部分の意味が分かりません。C言語を知っておられるなら「意味が分からない」と言ってる意味分かってもらえるかと思います。

つまり、デコード・エンコードが手間と言うことです。

> それとも配列の事言ってます？そうだとすれば、配列のサイズはどうするんですか？固定配列？配列のメモリを動的確保した場合、誰が開放する？配列の型は？libcallの戻り値が配列である事をどうやって認識する？

Vim script側はともかくとして、C言語側が問題ですね。
はい。だから簡単そうではないとはじめに書いているのです。
しかし、mattnさんがすでに実現した、ということであればVim本体で使えるようになればいいなぁ、と思ったのです。

**Comment by mattn** [comment]
> つまり、デコード・エンコードが手間と言うことです。

エンコードは分かりますが、デコードは型を教えない限り無理です。
戻り値の型を把握しているのは使用者でしかないですからね。

で、なぜlibcall/libcallnrが現状のままかと言うと、そういう拡張を入れて使用方法を間違えてしまうと落ちるからです。
例えば、libcallの引数に戻り値の型を教えてあげられる引数が入ったとして、vimはその通りにデコードしても実は間違っている可能性があるからです。

libcallに対するパッチ、もしくはlibcall2みたいな実装でパッチを書いて送っても、TODOのまま進むかと思います。

一番の問題は、型の話でも引数の話でもなく、どうbram氏を説得するかです。

**Comment by Shougo** [comment]
> で、なぜlibcall/libcallnrが現状のままかと言うと、そういう拡張を入れて使用方法を間違えてしまうと落ちるからです。
> 例えば、libcallの引数に戻り値の型を教えてあげられる引数が入ったとして、vimはその通りにデコードしても実は間違っている可能性があるからです。

そうですね。型チェックは事実上無理ですからね。
Pythonなんかだと、一種のプロトタイプ宣言をしていますけど……。

> 一番の問題は、型の話でも引数の話でもなく、どうbram氏を説得するかです。

確かに、それは難しい。

**Comment by tyru** [comment]
> さらに、戻り値としてリストを返せる関数を用意したいです。

mattnさんの言う通り返り値のデコードは難しいとしても、

> libcall()の引数をリストにできるようにしたいと思っています。

せめてlibcallex.vimみたいに複数引数を受け取れる機能だけでも取り込まれないでしょうかね。

libcallex.vimみたいにインラインアセンブラを使ったパッチだと移植性の問題からまず取り込まれないだろうし、
かといってCでやるとしたら引数の数をずらずら書いて分岐するパッチを書くのも現実的ではない、
となるとVimスクリプトの関数で複数の引数をlibcall()に渡せるように引数のリストをpackする関数がほしいですね。

**Comment by tyru** [comment]
あぁそうか、そしたらC側でunpackしないといけないですね。
CのAPIはVimは提供しないだろうし...(作るにしてもvim.hとか？まず取り込まれないですね...

**Comment by mattn** [comment]
まず第一に、落ちる可能性のあるAPIを簡単には出さないだろうし、今後Bramのスタイルが変わるとは思えない。

**Comment by koron** [comment]
テーマの設定が変わるんじゃないかなぁ。
多分「Vimスクリプトにネイティブ拡張機能を追加するかどうか」になる。

libcallの拡張じゃなくてif_*の延長としてif_cを整備しましょう、ということになるんじゃない?

**Comment by mattn** [comment]
if_rubyやif_perl、if_pythonでCの関数は呼び出せるし、そっちで呼べばいいって言われそう。

**Comment by koron** [comment]
「if_c以外は言語が要るけど、if_cは要らないじゃん。そっちのがポータブル」でいけるでしょう。
あとVimの基本以外の機能もif_cの向こう側に押しやれれば、将来的にすっきりするんじゃないかな。

**Comment by ynkdir** [comment]
+ffi: Enhanced Native Call Propose
https://groups.google.com/d/msg/vim_dev/F2z5I9tayKY/UNGZ1-kSvq4J

**Comment by Shougo** [comment]
それは私も期待しているんですが、他の誰からも反応がないんですよね……

**Comment by koron** [comment]
個人的には if_ffi みたいなのを作って libffi を Vim script から直接使えるようにしてしまう、というアイデアを推します。

しかし以下の理由で、必要性も実現性も低いと考えられます。
- job/channel でええやん
- pythonで ctypes 使えばええやん
- rubyでもpythonでも、ネイティブモジュールは、非同期を抱えると問題の原因だよね

故に backlog 送りとします。
