### ISSUE TITLE
completeopt=previewを設定していると候補選択時に画面がチラつく

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#310]
completeopt=previewを設定し、補完候補にプレビュー文字列がある場合、プレビューウインドウの内容を切り替えるときに画面がちらつきます。内部的に:redraw!が実行されているようです。
completeopt=previewはデフォルトの設定ですし、pythoncompleteなどデフォルトでプレビューウインドウを使用するオムニ補完もあるため、改善できるなら改善したほうが良いように思えます。

**Comment by h-east** [comment]
GVim 7.3.762 for Win64 kaoriya で補完関係はデフォルトの状態で `<C-X><C-O>` して `<C-O>` キーリピートさせてみました。
赤で囲んだ部分がチラつくなぁと感じました。認識合ってますか？

![complete_preview_2](https://cloud.githubusercontent.com/assets/518808/3400534/268087b2-fd46-11e3-9300-eb440d222df3.png)

GUIウィンドウタイトルとプレビューwindowのステータス行がピクピクッってなるのはなんだろう。一瞬違うもの描いてそうな気がする。

**Comment by h-east** [comment]
あー、一瞬プレビューwindowがカレントwindowになってるのか。
その時の画面更新をやめさせれば良いですな。

**Comment by mattn** [comment]
@h-east ++

**Comment by h-east** [comment]
edit.c : 5525 の ins_compl_show_pum() 呼び出しをコメントアウトすると、ポップアップメニューは表示されなくなるけど、GUIウィンドウタイトルとプレビューwindowのステータス行はピクピクッしなくなる。
この関数内のどこかをいい感じに修正すれば直るかもしれない。

コールスタック貼っときます。
https://gist.github.com/h-east/4360424#comment-776412

**Comment by h-east** [comment]
確定申告とか見積もりx2とか高プレッシャーとか低モチベとか納品で年度末までは超忙しいので、誰か引き継いでちょーだい。
 :cat2: :dash:

**Comment by h-east** [comment]
pum_set_selected() → prepare_tagpreview() で（プレビューwindowが無ければ作成して）プレビューwindowをカレントwindowに設定しているよ。
popupmnu.c : 638～674 辺りの制御がキモな気がします。

**Comment by Shougo** [comment]
調査ありがとうございます。
私の方でも調べたいのですが、私も現在本業が忙しく、3月になるまで手を付けられそうにありません。

**Comment by Shougo** [comment]
ちょっと調べてみましたが、そもそも候補を選択するだけで補完ウインドウのちらつきがありますね。これもどうにかしたい……。

**Comment by h-east** [comment]
一時的にpreview windowがカレントwindowになることによる以下の更新が抑えられればOK。
1. (GUI)windowタイトル
2. preview windowのステータスライン
3. 補完中でpopup menuが表示されているwindowのステータスライン

ということで、1.、2.のpatchを書きました。
1.は`++RedrawingDisabled;`して`prepare_tagpreview()`を呼ぶことでwindowタイトル更新関数`maketitle()`の処理を抑制することで問題解消。（win_enter()→win_enter_ext()→maketitle()）
It's いい感じ。

2.はpreview windowに`win_enter()`するとpreview windowのステータスライン更新フラグが立ってしまうので無理やりOFFってみた。（curwin->w_redr_status = FALSE;）
It's ad hoc。vim_devには投げない。参考出展。

``` diff
diff -r dd88acaa1a57 src/popupmnu.c
--- a/src/popupmnu.c    Thu Jun 26 22:33:51 2014 +0200
+++ b/src/popupmnu.c    Sat Jun 28 23:54:58 2014 +0900
@@ -567,11 +567,16 @@
        g_do_tagpreview = 3;
        if (p_pvh > 0 && p_pvh < g_do_tagpreview)
        g_do_tagpreview = p_pvh;
+       ++RedrawingDisabled;
        resized = prepare_tagpreview(FALSE);
+       --RedrawingDisabled;
+
        g_do_tagpreview = 0;

        if (curwin->w_p_pvw)
        {
+       if (!resized)
+           curwin->w_redr_status = FALSE;
        if (curbuf->b_fname == NULL
            && curbuf->b_p_bt[0] == 'n' && curbuf->b_p_bt[2] == 'f'
            && curbuf->b_p_bh[0] == 'w')
```

2.、3.はキー入力バッファを見てリピート（この場合は<C-O>）の入力がある時は全ステータスラインの更新を抑制する仕組みが必要。

**Comment by h-east** [comment]
> 2.、3.はキー入力バッファを見てリピート（この場合は<C-O>）の入力がある時は全ステータスラインの更新を抑制する仕組みが必要。

いや、違うな。popup menu表示中はステータスラインの表示更新は遅延されるはずだ。
（`win_redr_status()`で`pum_visible()`を見てる）
それなのになぜ更新されるかを突きとめるべきですね。

**Comment by Shougo** [comment]
@h-east おおお、調査ありがとうございます！

**Comment by h-east** [comment]
`pum_visible()`は`pum_do_redraw`がTRUEだったらFALSEを返すようになっとる。。
`pum_set_selected()`で明示的にセットして画面更新してる。[popupmnu.c: 658~]
(もうちょっと上手く条件付けして何とかなりそうな気がしないでもない)

``` c
                        /* Update the screen before drawing the popup menu.
                         * Enable updating the status lines. */
                        pum_do_redraw = TRUE;
                        update_screen(0);
                        pum_do_redraw = FALSE;

                        if (!resized && win_valid(curwin_save))
                            win_enter(curwin_save, TRUE);

                        /* May need to update the screen again when there are
                         * autocommands involved. */
                        pum_do_redraw = TRUE;
                        update_screen(0);
                        pum_do_redraw = FALSE;
```

10ヶ月前にvim_devで @mattn さんが議論していて、その時はBenさんが「Patch 7.3.807でpooupメニューの再描画を追加したから、再描画を削除するのはちょっと心配だなぁ」と言ってました。
Completion popup window flicker while typeing keys
https://groups.google.com/d/msg/vim_dev/kFmrNmdnpSs/GMCMHodLflEJ

必要な描画がされないくらいなら、ちょっとくらいチラついても良いって感じですかね。
やっぱり、これ↓？

> 2.、3.はキー入力バッファを見てリピート（この場合は<C-O>）の入力がある時は全ステータスラインの更新を抑制する仕組みが必要。

**Comment by Shougo** [comment]
> 10ヶ月前にvim_devで @mattn さんが議論していて、その時はBenさんが「Patch 7.3.807でpooupメニューの再描画を追加したから、再描画を削除するのはちょっと心配だなぁ」と言ってました。

確かに、再描画が必要な場合もあるから慎重に実装を進めないといけなさそうです。

> 必要な描画がされないくらいなら、ちょっとくらいチラついても良いって感じですかね。

その気持ちは分からなくもないです。

**Comment by h-east** [comment]
vim_devにも同様の指摘が来ましたな。
https://groups.google.com/d/msg/vim_dev/z-ABEOyJMFc/qdw3iRGxrFkJ

**Comment by h-east** [comment]
window titleとtask iconのちらつきの分はpatch付きで返信した。
なんか指摘のタイミングが良すぎない？もしかして、ネオ軍団？:zap::e-mail::o2:

**Comment by Shougo** [comment]
私は知らない人です……。デフォルトで補完のプレビューが有効になっているため、この問題に困っている人は意外と多いようです。

**Comment by h-east** [comment]
autocmdでイジワルされなければこれでいいんじゃなかろうか？

あと気になってるのはポップアップ部分の再描画がチラつくこと。
(ポップアップ下のを描画したあとポップアップを描画してる感じ)
GVimだと顕著。タグ補完等ではチラつかないのになぁ。
明日時間取れたら調べてみます。

``` diff
diff -r b8f703a4e55f src/popupmnu.c
--- a/src/popupmnu.c    Fri Jul 04 16:43:17 2014 +0200
+++ b/src/popupmnu.c    Sun Jul 06 01:54:53 2014 +0900
@@ -567,11 +567,16 @@
        g_do_tagpreview = 3;
        if (p_pvh > 0 && p_pvh < g_do_tagpreview)
        g_do_tagpreview = p_pvh;
+       ++RedrawingDisabled;
        resized = prepare_tagpreview(FALSE);
+       --RedrawingDisabled;
+
        g_do_tagpreview = 0;

        if (curwin->w_p_pvw)
        {
+       if (!resized)
+           curwin->w_redr_status = FALSE;
        if (curbuf->b_fname == NULL
            && curbuf->b_p_bt[0] == 'n' && curbuf->b_p_bt[2] == 'f'
            && curbuf->b_p_bh[0] == 'w')
@@ -645,30 +650,21 @@
            validate_cursor();
            redraw_later(SOME_VALID);

+           win_enter(curwin_save, TRUE);
            /* When the preview window was resized we need to
             * update the view on the buffer.  Only go back to
             * the window when needed, otherwise it will always be
             * redraw. */
            if (resized)
-           {
-               win_enter(curwin_save, TRUE);
                update_topline();
-           }

            /* Update the screen before drawing the popup menu.
             * Enable updating the status lines. */
-           pum_do_redraw = TRUE;
+           if (resized)
+               pum_do_redraw = TRUE;
            update_screen(0);
-           pum_do_redraw = FALSE;
-
-           if (!resized && win_valid(curwin_save))
-               win_enter(curwin_save, TRUE);
-
-           /* May need to update the screen again when there are
-            * autocommands involved. */
-           pum_do_redraw = TRUE;
-           update_screen(0);
-           pum_do_redraw = FALSE;
+           if (resized)
+               pum_do_redraw = FALSE;
            }
        }
        }
```

**Comment by Shougo** [comment]
ありがとうございます。

> あと気になってるのはポップアップ部分の再描画がチラつくこと。
> (ポップアップ下のを描画したあとポップアップを描画してる感じ)
> GVimだと顕著。タグ補完等ではチラつかないのになぁ。
> 明日時間取れたら調べてみます。

これも修正できると良いですね。

**Comment by Shougo** [comment]
https://groups.google.com/forum/#!topic/vim_dev/Am8NR79h66Q

Vim 7.4.361で修正されたようです。おめでとうございます。

**Comment by Shougo** [comment]
> window titleとtask iconのちらつきの分はpatch付きで返信した。

とあったので、現在のものはまだ完全ではないと判断し、まだ Open のままにしておきます。

**Comment by h-east** [comment]
@Shougo あざっす。

> 現在のものはまだ完全ではないと判断し、まだ Open のままにしておきます。

That's exactly.

**Comment by Shougo** [comment]
Vim 7.4.361 の修正を試しました。
確かに、タイトルのチラツキはなくなっているようです。
しかしステータス行のチラツキはかなり気になりますね。

> あと気になってるのはポップアップ部分の再描画がチラつくこと。
> (ポップアップ下のを描画したあとポップアップを描画してる感じ)
> GVimだと顕著。タグ補完等ではチラつかないのになぁ。

この問題はcompleteoptにpreviewがなくても発生するので、previewとは全く関係ない問題ですね。
ステータス行のチラツキほど気にはならないですが、確かに高速に候補をスクロールさせると若干ちらつきます。

**Comment by h-east** [comment]
completeoptにpreivewが含まれている時の補完時に既にpreview windowが開かれていたらpreview windowのステータスラインの再描画をしないようにするpatchを試しに送ってみた。
https://groups.google.com/d/msg/vim_dev/z-ABEOyJMFc/S_BahPHBDjAJ
どんな反応が返ってくるんだろう。wkwk

``` diff
diff -r f37b2f0479ca src/popupmnu.c
--- a/src/popupmnu.c    Wed Jul 16 15:18:27 2014 +0200
+++ b/src/popupmnu.c    Wed Jul 16 23:18:54 2014 +0900
@@ -574,6 +574,10 @@

        if (curwin->w_p_pvw)
        {
+       /* If there was already a preview window open, skip status line
+        * redrawing */
+       if (!resized)
+           curwin->w_redr_status = FALSE;
        if (curbuf->b_fname == NULL
            && curbuf->b_p_bt[0] == 'n' && curbuf->b_p_bt[2] == 'f'
            && curbuf->b_p_bh[0] == 'w')
```

**Comment by Shougo** [comment]
:+1:

**Comment by h-east** [comment]
Bram氏からの返事

> Looks tricky.  What if the popup menu was covering the status line 
> before, and now reveals (part of) it?  Does the check for "resized" 
> catch that? 

誰か https://github.com/vim-jp/issues/issues/310#issuecomment-49176630 のpatch試してここにコメントして貰えると嬉しい。
特にlightline.vimとかのステータスラインリッチ系プラグイン使っている人で`completeopt`に`preview`を含む設定の人とか。
プレビューウィンドウのステータスラインがチラつかなくなるだけのpatchなんだけど、特に問題なければ推していこうと思ってます。

**Comment by Shougo** [comment]
私自身試すのは問題ないんですが、ステータスのリッチ系プラグインは使ってないので……。
LingrのVim部屋で人柱を募集してみます。

Edit: 宣伝 done.

**Comment by h-east** [comment]
@shougo たのんます。
私もlightline.vim入れて試してみました。あきらかに改善が実感できました。
あとは、いじわるな設定や動作の確認ですね。

**Comment by Shougo** [comment]
@h-east 私の環境で試しました。preview windowのステータス行の再描画はたしかにないようです。
ただ、カレントウインドウのステータスライン行はまだ再描画されますね。これさえなければ完璧ですが…。
プレビューウインドウが存在する時、カレントウインドウのステータス行が再描画されるのはなぜなのでしょうか。

> 赤で囲んだ部分がチラつくなぁと感じました。認識合ってますか？

現在は赤で囲まれたうち、カレントウインドウのステータス行のみが再描画されているように見えます。

メインの Vim にパッチを適用したので、このまま様子を見てみます。

**Comment by Shougo** [comment]
カレントウインドウのステータス行再描画はウインドウ移動が内部的に発生しているからのようですね。

確かに、ステータス行がウインドウ移動時に更新されるのは妥当。
これもどうにか特別扱いできるとよいのですが。

**Comment by h-east** [comment]
@Shougo

> プレビューウィンドウのステータスラインがチラつかなくなるだけのpatchなんだけど

なのでそういう動作であってます。

**Comment by Shougo** [comment]
了解です。パッチを分割して、問題をひとつずつ解決していく方針なのですね。

**Comment by Shougo** [comment]
Vim 7.4.383

https://groups.google.com/d/msg/vim_dev/2RPXhQC4v8s/Vyg9RjsxT78J

:+1:

**Comment by h-east** [comment]
`completeopt`オプションに`preview`が設定されている時限定のチラつきはなくなりました。(ウィンドウタイトル、preview windowのステータスライン)
ですのでこのIssueは閉じて正解す。

後はpopupmenu自体のチラつきとカレントwindowのステータスラインのチラつきが残っています。
妥当な既存Issueあった気がするんですけどどれでしたっけ？

**Comment by Shougo** [comment]
おそらく、これだと思いますが

https://github.com/vim-jp/issues/issues/401

既に close されてしまっているし、議論が長いので別 issue を立てたほうが良いように思うのですが、いかがでしょう。
