### ISSUE TITLE
mklink すると .vimrc が読み込まれない?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#311]
> mklinkでDropboxにあるVim関連のファイルを紐付けてたんだけどそれが悪さしてたみたい。。。一回リンクされたファイルを消してリンクしなおしたら治った。

https://plus.google.com/101164025057236789338/posts/11eNPuFt9uk より

要調査。問題が観測されれば直し、なければ xlose/worksforme へ。

**Comment by raa0121** [comment]
`$HOME/dotfiles/.vimrc` を `$HOME/.vimrc` に `mklink` してますが、
WinなVimじゃシンボリックリンクで読み込めません って帰ってきますね。
cygwinなVimだと読み込めるんですが…
(WindowsVista 32Bit Vim7.3.806)

**Comment by koron** [comment]
@raa0121 `$HOME/.vimrc` を メモ帳とかで開けますかね?

**Comment by raa0121** [comment]
@koron 開けますね
Vim以外でシンボリックリンクで困ったことは無いです。

**Comment by koron** [comment]
あれれ? 今、私の手元で試したら、問題なくできちゃった。
なんか「単にシンボリックリンクである」以上のトリガーがありそう。

ちなみにシンボリックリンク経由で編集すると `backupcopy` 関連の問題があるかも。

**Comment by raa0121** [comment]
`!<symlink>d^@o^@t^@f^@i^@l^@e^@s^@/^@.^@v^@i^@m^@r^@c^@^@^@`
うちのcmdから `vim .vimrc`を叩いたらこうなりました

`backupcopy`は`auto`でした

**Comment by k-takata** [comment]
それ、Cygwin で作成した symlink だと思います。

**Comment by koron** [comment]
@k-takata ですよね～。ちょうど確認をお願いしようと思ってました。

**Comment by koron** [comment]
@raa0121 cmd の `mklink` で作るシンボリックリンクと Cygwin の `ln -s` で作るシンボリックリンクは全くの別物です。Cygwin の Vim は後者を扱えますが、 Window ネイティブの Vim は扱えません。

**Comment by raa0121** [comment]
@koron @k-takata 管理者権限の`cmd`で作ったシンボリックリンクだったはずなんですけどねぇ…
今作りなおしてみたらアクセスできました… 何だったんだろう…

**Comment by mattn** [comment]
もう少し調査などやって際限しない様ならcloseしといて下さい。

**Comment by koron** [comment]
drikin さんには別途問い合わせておきました。

なにか進展があったら reopen とします。
