### ISSUE TITLE
日本語メニューのスクリプトでグローバル変数が定義されている

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#312]
https://code.google.com/p/vim/source/browse/runtime/lang/menu_ja_jp.utf-8.vim#304

**Comment by koron** [comment]
パッチ作ってもらえます?

**Comment by koron** [comment]
そろそろ [これ](https://bitbucket.org/koron/vim-kaoriya-vim/issue/1/update-japo) と合わせて更新版をBram氏へ送ります。

**Comment by thinca** [comment]
ちょっと気になったんですが、このメニューって sjis, euc-jp, utf-8 で同じ内容のものがエンコード違いで用意されていますが、これは共通のものが使えない事情があるということでしょうか?

**Comment by koron** [comment]
@thinca: `-iconv` とりあえずはUTF-8版だけあれば他はこっちでやりますよ～

**Comment by thinca** [comment]
`+iconv` は `iconv()` 関数だけかと思ってたんですが、そんなことないんですかね。`:scriptencoding` には、`+multi_byte` が必要としか書いてないですし、ちょっと気になっております。
とりあえずパッチは utf-8 のだけ作っておきます。(全部作ると文字化けしてアレなので)

**Comment by thinca** [comment]
https://gist.github.com/thinca/4984353

**Comment by mattn** [comment]
vim は結構いっぱいやってます > iconv
- 入力
- 画面表示
- メニュー
- scriptencoding
- iconv()
- ファイルパス

**Comment by thinca** [comment]
@mattn なるほど、そんな気はしていたんですが、やはりそうなんですね。(`help +iconv` には `+iconv Compiled with the iconv() function` としか書いてなかったので…)

**Comment by koron** [comment]
@mattn さんと私は +iconv が実装された瞬間に立ち会ってますからねw

**Comment by koron** [comment]
> https://gist.github.com/thinca/4984353

@thinca Thanks!

**Comment by thinca** [comment]
ｶｯｺｲｲ!

**Comment by koron** [comment]
@thinca Thanks! merged at [here](https://bitbucket.org/koron/vim-kaoriya-vim/commits/d11bdeceb8c0c32f8120cb40af9031e8824352da)

**Comment by koron** [comment]
あとは [コイツ](https://bitbucket.org/koron/vim-kaoriya-vim/issue/1/update-japo) と合わせてパッチおくるだけ。

**Comment by koron** [comment]
送ったが、Googleグループにスレが表示されていない。
メールでToにBram、Ccにvim-dev@vim.org を指定して送ったからだろうか?

**Comment by h-east** [comment]
わたしのとこでは表示されちょります。 :+1:

**Comment by koron** [comment]
Thanks! こっちからも見えるようになりました。

https://groups.google.com/d/topic/vim_dev/BywLMWIu1aM/discussion

**Comment by thinca** [comment]
取り込まれていました。
https://code.google.com/p/vim/source/detail?r=7ffc704cb7c10d53445d47528c647fd3f8c8afe0
