### ISSUE TITLE
Make_cyg.mak を Make_ming.mak と統合したい

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#314]
Make_cyg.mak は、Cygwin上でWin32用のVimをビルドするためのMakefileですが、MinGW用のMakefileである Make_ming.mak を使ってビルドすることも可能です。（Perlインターフェースのビルドには[一部問題があります](https://github.com/vim-jp/issues/issues/262#issuecomment-12544780)が、簡単な修正をすることで対処可能です。）

Make_ming.mak と Make_cyg.mak の内容は似ていますが、微妙に違っているところもあり、そのようなものを管理するのは大変です。実際、Make_cyg.mak は、Ruby 1.9 用のビルドができなかったり（7.3.815で修正済み）、7.3.640 の XPM 対応の修正に追従できていなかったりと、いくつか問題が出ています。
このようなことを避けるため、Make_cyg.mak を Make_ming.mak に統合したいと思います。

修正案です。
https://gist.github.com/k-takata/5018169

**Comment by koron** [comment]
コンセプトは良いと思います。

が、mingをベースにするのではなく、共通部品を切り出したほうが良いかも。
- cyg_ming_common.mak
  - Make_cyg.mak
  - Make_ming.mak

みたいな感じで。

いまのその構成だとMinGW向けの修正がCygwinに悪影響をおよぼした場合に角が立ちます。
共通部品としてくくりだしておけば
**「ここを弄るときはMinGWとCygwin両方を意識しろ」**
というのが際立ちます。

あ、別に共通部分の上の名前にはこだわりはありません。重要なのは

> **「ここを弄るときはMinGWとCygwin両方を意識しろ」**

これが分かることです。

**Comment by mattn** [comment]
mingwはcygwinや、msys使った場合と違ってシェル展開される物が異なるのでかなり注意しないとビルドできなくなる人が出てきそう。

**Comment by k-takata** [comment]
お試し版扱いで、パッチを紹介。
https://groups.google.com/d/msg/vim_dev/YWnfI9wFFoA/BDlXPHiAdmYJ

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/w82YHvMXxV0/x8p3ofvzf50J

> Merging Make_cyg.mak and Make_ming.mak might be a bit difficult, but
> perhaps we can at least move the parts that are the same to a common
> file and include it in both?  We could gradually move more lines there.

Bramからも同じ意見が出てきました。
そろそろ何とかしよう。

**Comment by k-takata** [comment]
1. 元の Make_ming.mak を cyg_ming.mak にリネーム  
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d6c19c16f640973471974c618cd51f7edac3e31/01-rename-ming-mak.patch?at=cyg_ming
2. 古い Make_cyg.mak を削除  
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d6c19c16f640973471974c618cd51f7edac3e31/02-remove-old-cyg-mak.patch?at=cyg_ming
3. 新しい Make_ming.mak と Make_cyg.mak を作成  
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/7d6c19c16f640973471974c618cd51f7edac3e31/03-merge-cyg-ming-mak.patch?at=cyg_ming

**Comment by k-takata** [comment]
Posted.
https://groups.google.com/d/msg/vim_dev/w82YHvMXxV0/n9HdS71dnLAJ

**Comment by k-takata** [comment]
共通部分のファイル名は Make_cyg_ming.mak に変更になりました。

**Comment by k-takata** [comment]
7.4.496
https://groups.google.com/d/topic/vim_dev/T6tKzCamxLA/discussion

**Comment by k-takata** [comment]
追加修正 7.4.507
https://groups.google.com/d/topic/vim_dev/FuIXU2VUPRc/discussion
