### ISSUE TITLE
if_ruby が ruby2.0 でビルド出来ない。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#315]
ruby2.0 の ABI は 1.9 系なので

```
RUBY=c:/ruby200 DYNAMIC_RUBY=yes RUBY_VER=20 RUBY_VER_LONG=2.0.0
```

を指定。

```
obji386/if_ruby.o: 関数 `rb_num2ulong_inline' 内:
c:/ruby200/include/ruby-2.0.0/ruby/ruby.h:599: `rb_num2ulong' に対する定義されていない参照です
collect2.exe: エラー: ld はステータス 1 で終了しました
Make_ming.mak:688: recipe for target 'vim.exe' failed
mingw32-make: *** [vim.exe] Error 1

C:\vim\src>endlocal
```

**Comment by mattn** [comment]
おっ、でも今みたら API_VERSION が 2.0.0 になってるな。これでなんとかなる。

**Comment by mattn** [comment]
パッチ

https://gist.github.com/mattn/5035142

修正して最小になったと思う。

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/PEBVWLgogjo/discussion

**Comment by h-east** [comment]
:+1:

**Comment by h-east** [comment]
早速 7.3.834 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/zWzM4WbwooM/discussion

**Comment by koron** [comment]
:+1:

**Comment by k-takata** [comment]
VC10でLTCG使ってると、7.3.834でも不十分で、rb_cFloat が見つからないというエラーになります。(ただし実際には rb_cFloat への参照は、最適化後には消えてしまうようでLTCGを使わなければエラーになりません。)

https://bitbucket.org/k_takata/vim-win32-mq/src/3f2e55fed7f39144ce4ffa332757127ae489216f/fix-ruby20-msvc.patch?at=default

このパッチを適用後、[ActiveScriptRuby 2.0.0-p0](http://www.artonx.org/data/asr/) + VC10 で、以下の指定で動作することを確認しました。

```
RUBY=C:\Progra~2\Ruby-2.0.0 RUBY_VER=20 RUBY_VER_LONG=2.0.0 DYNAMIC_RUBY=yes RUBY_PLATFORM=i386-mswin32_100 RUBY_INSTALL_NAME=msvcr100-ruby200
```

(RUBY_PLATFORM と RUBY_INSTALL_NAME を手動で指定しないといけないのが面倒。)

**Comment by mattn** [comment]
> VC10でLTCG使ってると、7.3.834でも不十分で、rb_cFloat が見つからないというエラーになります。

ｷﾀｰw

**Comment by mattn** [comment]
これを入れた状態でmingwもビルド可能でok?

**Comment by k-takata** [comment]
まだ試してません。
Ruby Installerの方のDLLもrb_cFloatはエクスポートしていたので大丈夫だとは思いますが。

**Comment by k-takata** [comment]
32bit版はOKでした。64bit版は未確認。

**Comment by k-takata** [comment]
x64 ダメっぽい。

``` shell
$ make -f Make_cyg_new.mak RUBY=c:/ruby200-x64 DYNAMIC_RUBY=yes RUBY_VER=20 \
RUBY_VER_LONG=2.0.0 CROSS_COMPILE=x86_64-w64-mingw32- ARCH=x86-64 \
RUBY_INSTALL_NAME=x64-msvcrt-ruby200 RUBY_PLATFORM=x64-mingw32
```

```
if_ruby.c:361:15: error: conflicting types for ‘rb_num2ulong’
c:/ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:583:7: note: previous declaration of ‘rb_num2ulong’ was here
Make_ming.mak:763: recipe for target `gobjx86-64/if_ruby.o' failed
make: *** [gobjx86-64/if_ruby.o] Error 1
```

**Comment by mattn** [comment]
ひぃw

**Comment by koron** [comment]
LLP64 だからかなぁ?w

**Comment by k-takata** [comment]
if_ruby.c の rb_num2ulong() の戻り値の型を ruby.h に合わせて unsigned long から VALUE に変えれば良さそう？

**Comment by mattn** [comment]
そうかも

**Comment by k-takata** [comment]
修正パッチ
https://bitbucket.org/k_takata/vim-win32-mq/src/a578f841d7e21bb04778c1e17502ef951bc7aeab/fix-ruby20-x64-and-msvc.patch?at=default
x64 で、わざわざ RUBY_INSTALL_NAME と RUBY_PLATFORM を指定しなければならなかったのも修正。
ただし、mingw版のみの考慮。mswin版はバイナリが公開されていないので無視。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/zWzM4WbwooM/Eu6QE7xBxt0J

**Comment by k-takata** [comment]
7.3.848 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/VyZtRTIbqAE/discussion
