### ISSUE TITLE
toml-vim 作って

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#316]
<blockquote class="twitter-tweet" lang="ja"><p>github創業者のmojomboがYAMLの代替フォーマットを作って、2日ですでに12の言語に移植されているようだ。 <a href="https://t.co/31D7tMNu6q" title="https://github.com/mojombo/toml">github.com/mojombo/toml</a></p>&mdash; yhara (Yutaka HARA)さん (@yhara) <a href="https://twitter.com/yhara/status/306258257847128065">2013年2月26日</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by heavenshell** [comment]
https://github.com/cespare/vim-toml 出来たみたいです。

**Comment by mattn** [comment]
syntaxっすね

**Comment by heavenshell** [comment]
あ、パーサ作ってって事ですか。誤読してましたw

**Comment by mattn** [comment]
いやKoRoNさんの真意はわからんw

**Comment by koron** [comment]
主にパーサだったけど、syntaxも(・∀・)ｲｲﾈ!!

**Comment by crazymaster** [comment]
vital.vim に Text.TOML 入ったので閉じてもいいんじゃなイカ？
https://github.com/vim-jp/vital.vim/pull/227

**Comment by crazymaster** [comment]
![default](https://cloud.githubusercontent.com/assets/1528093/9041676/4580160a-3a44-11e5-8237-84bee4bfb059.jpg)
