### ISSUE TITLE
scala シンタックス

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#317]
scala のシンタックスを本体に含めたい。

いま scala 読もうとしてシンタックスがないのに面食らった。

**Comment by thinca** [comment]
Scala の syntax ファイルはすでに存在しますが、作者側から連絡がないと無理、と Bram が言ってますね。
https://groups.google.com/d/topic/vim_dev/91sa4vYeRSk/discussion

**Comment by mattn** [comment]
# 連絡つかないっスカラ！

**Comment by thinca** [comment]
Yet Another Scala Syntax を作るしかない！

**Comment by koron** [comment]
そういう状況なら License を正して vim-jp でホストしちゃったら?

**Comment by h-east** [comment]
![](http://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mil_Mascaras_1.jpg/800px-Mil_Mascaras_1.jpg)

**Comment by koron** [comment]
# それは ミル・マスカラス!

**Comment by mattn** [comment]
![](http://blogimg.goo.ne.jp/user_image/44/4e/b211c2347560b9c99d2d0ff887b54c21.jpg)

スカラー、君の言ってる事が何時も正しい訳じゃない

**Comment by koron** [comment]
# それはスカリー!

**Comment by koron** [comment]
http://tiqav.com/search/%E3%82%B9%E3%82%AB%E3%83%A9

**Comment by mattn** [comment]
![](http://blogimg.goo.ne.jp/user_image/7b/0c/b2749f2f5fe047e9d6f87d7c0116a81d.jpg)

**Comment by k-takata** [comment]
> Yet Another Scala Syntax を作るしかない！

略してYASS…犯人はヤス!?

**Comment by koron** [comment]
さてこいつも golang と一緒ね。

> vim-jp として本件にどう関わっていくか、そろそろ判断しよう。
> -   オリジナルメンテナを説得していく
> -   vim-jp で fork してそちらのメンテナということで vim-dev へ推す
> -   めんどうなのでやめる
> 
> 選択肢はこのくらいかな。

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/e4a3bcf28d92d0bde9ca227ccb40d401038185e5
去年の8月にscala syntaxが取り込まれました。
