### ISSUE TITLE
INSTALLpc.txtの改行コードを<CR><LF>に

### ISSUE THREAD

**Issue by raa0121** [vim-jp/issues#318]
諸Vimmerの皆さんなら、テキストファイルはVimで開くものだと思いますが、
たまたまエクスプローラーで`INSTALLpc.txt`をダブルクリックしてしまったら、メモ帳で開けてしまうことがありますね。

Windowsの標準改行コードは`<CR><LF>`で、メモ帳で`<LF>`なファイルを開くと1行に全てがあるように見えます。
初心者に対しても少し不親切だと思うのでWindowsで開くことを想定されている`INSTALLpc.txt`は`<CR><LF>`であったほうがいいと思います。

**Comment by koron** [comment]
基本は賛成ですが、提案するとなにか一悶着ありそうな気がしないこともないですね。

過去に svn か hg に入れるときのWin向け改行コード全般でなんか有った気がするw

**Comment by k-takata** [comment]
`.hgeol` で改行コードを設定するようにして必要な人は[eol エクステンションを有効](http://d.hatena.ne.jp/flying-foozy/20111205/1323065152)にするのか、CRLFでコミットしてしまうのか、少なくとも2通りの方法がありますね。

# INSTALLpc.txt ってコンパイルの仕方が書かれているので、初心者が読むようなものではないような気も。

**Comment by koron** [comment]
前に揉めた時は、Windowsは .hgeol で取り出せよ、みたいな主張を見た気がします。

個人的にはこのファイルに関しては CRLF でコミットで良いと思いますが…まぁ内容的にはあんまし意味ないですねw

**Comment by k-takata** [comment]
どちらかというと、README_dos.txt, README_bindos.txt の方？

**Comment by h-east** [comment]
`INSTALLpc.txt` はソースコードをcloneして初めて見れるものですよね。( ./vim/src/INSTALLpc.txt )
ソースコードは基本すべてLFになっているので「初心者に対して～」という理由でCRLFに修正されるものではないんじゃないかなぁ。

「ソースコードを取得する行動を取ったということは初心者ではない」と思いますので、
テキストファイルはVimで開くように環境を整えましょう :+1:

**Comment by h-east** [comment]
なんか私がIssueストッパーみたいになってるｗ
@raa0121  このissue閉じてしまって良いですか？

**Comment by raa0121** [comment]
すっかり忘れてました。 みなさんご意見ありがとうございました。
@h-east 閉じました
