### ISSUE TITLE
CygwinでビルドしたVimが make test を通らない

### ISSUE THREAD

**Issue by raa0121** [vim-jp/issues#319]
題名通りです。
`configure`の設定は

```
./configure
\ --with-features=huge
\ --with-compiledby="raa0121 <raa0121@gmail.com>"
\ --enable-multibyte --enable-rubyinterp --enable-pythoninterp
\ --enable-perlinterp --enable-luainterp --enable-python3interp
\ --enable-gpm --enable-xim --enable-cscope --enable-fontset
```

`make test` の結果は
https://gist.github.com/raa0121/5048644

Linuxでのビルドはまだ試してないです。
" Cygwinを未だに使っている方はどれだけ居るのでしょうか…
" おすすめのUnixツールとかあったら教えて下さい

**Comment by h-east** [comment]
Vimのソースコードのバージョンはいくつですか？ 7.3.843？

**Comment by raa0121** [comment]
v7-3-831 ですね。
hgのリポジトリから拾ってきたのがちょっと古いみたいです

**Comment by k-takata** [comment]
7.3.843で試しましたが、test1で失敗ということにはなりませんでした。
一通りテストが流れて、test55 だけが失敗しました。

```
rm -rf test55.failed test.ok test.out X* viminfo
cp test55.ok test.ok
# Sleep a moment to avoid that the xterm title is messed up
../vim.exe -u unix.vim -U NONE --noplugin -s dotest.in test55.in
# For flaky tests retry one time.
# Check if the test.out file matches test.ok.
18c18
< Vim(call):E737: ▒
---
> Vim(call):E737: 3
116c116
< Vim(call):E737: ▒
---
> Vim(call):E737: a
rm -rf X* test.ok viminfo

Test results:
test55 FAILED
```

**Comment by k-takata** [comment]
test55 は、testdirディレクトリで`LANG=C make test55.out`で実行したところ、パスしました。
test55.in の適当な場所に`:lang C`を加えるべきかもしれません。

**Comment by raa0121** [comment]
7.3.843 を`make` `make test`しても同じエラーになります…
うごご…

**Comment by k-takata** [comment]
src/testdir ディレクトリで `make test1.out` のように1つずつ実行して何が起きているのか調べるのが良いのではないでしょうか。

**Comment by k-takata** [comment]
test55 が失敗するのはこれでいいかな？ (Cygwin以外未確認)

``` diff
--- a/src/testdir/test55.in
+++ b/src/testdir/test55.in
@@ -3,6 +3,7 @@
 STARTTEST
 :so small.vim
 :fun Test(...)
+:lang C
 :" Creating List directly with different types
 :let l = [1, 'as''d', [1, 2, function("strlen")], {'a': 1},]
 :$put =string(l)
```

**Comment by h-east** [comment]
`+multi_lang` が無効の場合を考慮する必要があるかも？

`:lang` ってコマンドがあるのを初めて知りました :satisfied:

**Comment by k-takata** [comment]
`:lang` は、test55 内の下の方でも使っているので、それを上の方にも足しただけです。（下の方は削除しても良いかも。）

**Comment by k-takata** [comment]
test55の問題は別issueにしました。

**Comment by raa0121** [comment]
`make test` が通らない理由が分かりました。
vim直下で `./configure ; make ; make test` してたからでした。
src の中に入って`configure`からやり直した結果、testも通りました。
お騒がせしました。

**Comment by mattn** [comment]
いや、それバグやと思います。

**Comment by h-east** [comment]
> vim直下で ./configure ; make ; make test してたからでした。

@k-takata これは今でも通らないんでしたっけ？

**Comment by k-takata** [comment]
私のところでは1回も再現していません。

**Comment by mattn** [comment]
so close this

**Comment by koron** [comment]
古いバージョンの話であり再現しないとのことから、invalidではなくworksformeに付け替えます。
