### ISSUE TITLE
マルチバイト文字を含む行選択時の r がおかしい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#320]
```
あああ
あああ
```

`Vjrx`

```
xxx
xああ
```

文字数や行数を変えて試してみたけどまだいまいち法則性が掴めず。

**Comment by h-east** [comment]
現象が発生したときのOS, Vim ver. を添える癖をつけましょう。

**Comment by thinca** [comment]
失礼しました。
- MS Windows Vim 7.3.831 +kaoriya 64bit
- Gentoo Linux Vim 7.3.831 +kaoriya 64bit

共に 'encoding' は utf-8 です。

**Comment by mattn** [comment]
`あ` を `a` に書き換えると、終端となる位置の補正(-1)を行う必要があるんですが、本来それは現行の行に対してのみ行われるべきで

```
あああ
いいい_
```

`あああ` を処理している間は `_` の位置は補正しなくていいはずです。
って事でパッチ

``` diff
diff -r 8b86b69546a9 src/ops.c
--- a/src/ops.c Wed Feb 20 21:26:00 2013 +0100
+++ b/src/ops.c Thu Feb 28 14:41:31 2013 +0900
@@ -2194,7 +2194,9 @@
        {
            /* This is slow, but it handles replacing a single-byte
             * with a multi-byte and the other way around. */
-           oap->end.col += (*mb_char2len)(c) - (*mb_char2len)(n);
+
+           if (curwin->w_cursor.lnum == oap->end.lnum)
+           oap->end.col += (*mb_char2len)(c) - (*mb_char2len)(n);
            n = State;
            State = REPLACE;
            ins_char(c);
```

https://gist.github.com/5054510

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/hYwThAotx0Y/discussion

**Comment by k-takata** [comment]
7.3.853 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/WX83xWfAJMk/discussion
