### ISSUE TITLE
バグ報告テンプレ欲しい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#322]
環境とかを書き忘れることが結構あるので、テンプレ化してあると初めての利用の人も私みたいなうっかりさんも安心かなーと思いました。
この Issue で議論すべき内容
- そもそも必要か or テンプレ化可能か
- テンプレに含める項目
- どこに掲示するか(初めての人でもすぐわかるところ…)

**Comment by h-east** [comment]
一応wikiページに記述があるのでリンク貼っときますね。
https://github.com/vim-jp/issues/wiki/Reporter

**Comment by thinca** [comment]
ふむふむ。となると
- 他に必要な項目がないか
- 可能であればコピペ可能なテンプレ化
- 周知

ですかね。最後が一番難しい。

**Comment by k-takata** [comment]
これも貼っておきます。
[Vimの問題を見つけた時の報告のしかた — KaoriYa](http://www.kaoriya.net/blog/2011/12/20111228)

**Comment by mattn** [comment]
github の issues にテンプレ機能、あってもいいと思った。
オフトピ失礼

**Comment by h-east** [comment]
閉じます。
最低限のことはwiki(https://github.com/vim-jp/issues/wiki/Reporter) に書いてますし、
現状ではgithub に issues にテンプレ機能ないですし、
なによりも、Issue登録時にそのIssueを読む人の気持ちになって考えると自ずとどういう情報を出せば良いかは多少は分かりますしおすし。

人間同士のコミュニケーションは完璧じゃなくっていいんです。
相手のことをちょっとだけでも思いやることができていればそれでいいんです。

**Comment by koron** [comment]
github のテンプレが登場したことにより、 wontfix から fixed へ振替となりました!
