### ISSUE TITLE
fileencodingsオプションの解析が遅い

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#324]
デフォルトのVimだと高速なのに、自分のVimは巨大ファイルを開いた時に遅いので調べていました。
すると、fileencodingsオプションをセットした時に、やたらと遅くなることがわかりました。

320 MBのファイルをVimで開くときに、
fileencodings='ucs-bom'（デフォルト) -> 7.5 秒
fileencodings='ucs-bom,iso-2022-jp-3,euc-jisx0213,euc-jp,cp932,utf-8' -> 42.4 秒
これくらいの違いがあります。（私の.vimrcでの設定なので、他の環境では数値が異なります）

fileencodingsオプションがファイルを読み込むときにエンコーディング変換をしているためだと思うのですが、この変換をタイムアウトできるようにすれば問題は改善されるのではないでしょうか。

**Comment by koron** [comment]
verifyenc入ってます?
入ってたらはずして計測してみてください。

**Comment by Shougo** [comment]
verifyencは使っていないですね。
ちなみに、デフォルトのvimでは1.2秒程度でファイルを開けました。

**Comment by mattn** [comment]
FileReadPre とかが走ってるんじゃないすかね。

**Comment by Shougo** [comment]
いや、この遅い現象は.vimrcをfileencodingsのセットだけで再現したので、これが原因だと思います。

**Comment by h-east** [comment]
@Shougo 他の人が検証できるようにもう少し情報を出しましょう。
- OS、Vim ver.は？ kaoriya版？
- encodingオプションの値は何ですか？
- 320 MBのファイルのエンコードは何でしょう？そのファイルをどこかにアップしてURL晒すことは可能ですか？
- `gvim -N -u NONE -U NONE -i NONE --noplugin hoge.txt` と<br>`gvim -N -u NONE -U NONE -i NONE --noplugin -c "set fileencodings=ucs-bom,iso-2022-jp-3,euc-jisx0213,euc-jp,cp932,utf-8" hoge.txt`<br>でも同様に違いが出ますか？<br>（`encoding`がデフォルト以外の場合は `-c "set enc=utf8"` みたいに足してください）

**Comment by Shougo** [comment]
> OS、Vim ver.は？ kaoriya版？

検証に使用したのはKaoriya版です。詳しいバージョンは覚えていませんが、今年リリースされたもの。

> encodingオプションの値は何ですか？

utf-8です。

> 320 MBのファイルのエンコードは何でしょう？そのファイルをどこかにアップしてURL晒すことは可能ですか？

ファイルのエンコード自体はASCIIです。ファイルは残念ながら晒せません。検証用に、大容量のファイルを簡単に作る方法はありますでしょうか。

> gvim -N -u NONE -U NONE -i NONE --noplugin hoge.txt と
> gvim -N -u NONE -U NONE -i NONE --noplugin -c "set fileencodings=ucs-bom,iso-2022-jp-3,euc-jisx0213,euc-jp,cp932,utf-8" hoge.txt

違いが出るのではないかと思いますが、手元にファイルがないので今は試せないですね。大容量のテキストファイルがあれば確認できると思いますが……。

**Comment by Shougo** [comment]
これを試したときは、.vimrcを最小化、自分のプラグインは読み込まないようにしていたものの、--no-pluginしていなかったため他のプラグインが原因かもしれません。これについては、もうちょっと調べてみます。

**Comment by Shougo** [comment]
遅くなりましたが、調査結果を報告します。

Vim 7.3.831 Kaoriya版 309MB 1368391行のASCIIファイル（test.result）を開いた時のVimの起動時間です。

`gvim -N -u NONE -U NONE -i NONE --noplugin test.reslt：Vimの起動1263ms`
`gvim -N -u test.vimrc -U NONE -i NONE --noplugin test.result：Vimの起動42697ms`

test.vimrcの中身は以下です。

```
set fileencodings=ucs-bom,iso-2022-jp-3,euc-jisx0213,euc-jp,cp932,utf-8
```

ちなみに、`gvim -N -u NONE -U NONE -i NONE --noplugin -c "set fileencodings=ucs-bom,iso-2022-jp-3,euc-jisx0213,euc-jp,cp932,utf-8" hoge.txt`はダメでした。なぜなら、-cオプションはファイルを開いた後に評価されるからです。set encoding, set fileencodingsはファイルを開く前にセットしないと意味がありません。（これはドキュメントに載っています）

以上の結果より、fileencodingsオプションの解析が遅いと結論づけました。encodingオプションが何であるかは関係無いようです。Windows環境以外ではどうなのかはわかりません。

**Comment by k-takata** [comment]
> -cオプションはファイルを開いた後に評価されるからです。

`--cmd` なら先に評価されます。
ファイルを開いた後、`fenc` は何になっています？

**Comment by Shougo** [comment]
> --cmd なら先に評価されます。

了解。これはやってみます。

> ファイルを開いた後、fenc は何になっています？

これも調べておきます。

**Comment by h-east** [comment]
> -cオプションはファイルを開いた後に評価されるからです。

そうでした。 @k-takata さんが言及している `--cmd` でした。すんません。

> 309MB 1368391行のASCIIファイル

この情報から1行が237バイトのtest.result(仮) を作成(※1)して確認したところ、

```
gvim.exe -N -u NONE -U NONE -i NONE --noplugin test.result
```

で 2118msec、

```
gvim.exe -N -u NONE -U NONE -i NONE --noplugin --cmd "set fileencodings=ucs-bom,iso-2022-jp-3,euc-jisx0213,euc-jp,cp932,utf-8" test.result
```

で 31104msec となり @Shougo さんの結果にかなり近いものになりました。
(GVim 7.3.831 win64 +kaoriya)

※1
`235aA<Esc>Y309000000p:w test.result<CR>`
環境によっては固まるかもｗｗ

以上、報告まで。

**Comment by mattn** [comment]
test.result は dd かなんか？

**Comment by k-takata** [comment]
> `235aA<Esc>Y309000000p:w test.result<CR>`

Yの後の桁が多すぎません？ 1000000 ぐらいでいいような。
で、試してみたのですが、文字コードの変換に時間が掛かっているのではないかと思います。
`--cmd` で `enc=cp932 fencs=cp932` や `enc=utf-8 fencs=utf-8` を指定して、文字コードの変換が起きないようにして読み込んだところ、2秒程度だったのですが、`enc=utf-8 fencs=cp932` のように文字コードの変換が発生するようにしたところ、10秒以上掛かるようになりました。

**Comment by h-east** [comment]
> > 235aA<Esc>Y309000000p:w test.result<CR>
> 
> Yの後の桁が多すぎません？ 1000000 ぐらいでいいような。

ほんまや！
`235aA<Esc>Y1368391p:w test.result<CR>`
でした:sweat_smile: ご指摘thanks!

**Comment by mattn** [comment]
@k-takata iconv() で失敗した時点で抜ける処理だった気がしますが。

**Comment by koron** [comment]
このケースは失敗しないので、デカイファイルを iconv() に通すのに時間がかかるという話かな?

Vimを通さずに素のiconv 使ってどのくらいかかるかは見ると良いのかも。

**Comment by Shougo** [comment]
遅くなりました。追加の調査結果を報告します。

`--cmd='set fileencodings=cp932' -> 1.560s`
`--cmd='set fileencodings=cp932,utf-8' -> 1.560s`
`--cmd='set fileencodings=euc-jp,cp932,utf-8' -> 39.280s`
`--cmd='set fileencodings=euc-jisx0213,euc-jp,cp932,utf-8' -> 68.624s`
`--cmd='set fileencodings=iso-2022-jp,euc-jisx0213,euc-jp,cp932,utf-8' -> 99.404s`
`--cmd='set fileencodings=ucs-bom,iso-2022-jp,euc-jisx0213,euc-jp,cp932,utf-8' -> 99.200s`

`&fenc`はどれもcp932です。--cmdを使うと、より遅くなるという結果に……
変換がかからないset fileencodings=cp932はかなり高速です。fileencodingsが増えると順調に遅くなるのがわかります。
ucs-bomが高速なのは、すぐに失敗するから？

**Comment by Shougo** [comment]
素のiconvコマンドで測ってみたところ（Linux環境）、変換には3.6秒程度かかっています。
これはどの文字コードでも同じです。

**Comment by ynkdir** [comment]
ASCIIファイルなら最初の変換で成功するはずなのでなにかがおかしいですね

**Comment by mattn** [comment]
うち、その現象でませんね。3秒程度で開く。 ubuntu 12.04
開いた後は、fileencodingsの先頭になってる。

**Comment by ynkdir** [comment]
あーすいませんうちでもでてないです。
なのでShougoさんのとこのなにかがこわれてるのではと…

**Comment by h-east** [comment]
@Shougo test.resultは以下の手順で作成したものでお願いします。(皆で再現手順＆使用ファイルを統一したい為)

```
235aA<Esc>Y1368391p:w ++ff=dos test.result<CR>
```

**Comment by koron** [comment]
うちで配ってるiconv.dllのせい? 今はもう手を入れてないはずだけど…

**Comment by koron** [comment]
いや、手を入れてない はウソだったわ。

**Comment by koron** [comment]
あ～やっぱうちの iconv っぽい。
Vim に同梱の iconv.dll を使った iconv.exe とMinGWのiconvを比較したら
20sec と 5sec くらいで4倍の差がついた。

**Comment by h-east** [comment]
@koron oh...

**Comment by koron** [comment]
ちなみに

```
118aあ<Esc>Y1368391p:w test.result<CR>
```

として作った euc-jp なファイルを cp932 に変換する試験だと
13sec と 11sec でほとんど差がつかなかった。
たぶんASCII領域はテーブル通さないでucs4_tに変換してるんだと思う。

**Comment by koron** [comment]
とりあえず明日にでも簡単な対策をした iconv.dll を作りますので、
その時は追試ヨロです。って、ソースのレポジトリとかどうなってんやろ?w

**Comment by koron** [comment]
https://github.com/koron/libiconv このレポジトリのバイナリがコンパイルしてあったので [ココに置きました](http://files.kaoriya.net/var/libiconv-20120909.dll) 。
時間のあるときに `iconv.dll` にリネームして計測してみてもらえますか?

このレポジトリなんですが、私が独自に足した libiconv のコードを捨て去るために
1.14 ベースでMSVC10を使ってコンパイルできるようにしてたんですが
配布しているものは古いコードベースだったというオチかも。

なお私の手元では倍くらい(所要時間が半分くらい)にはなってるっぽい。

**Comment by h-east** [comment]
こんなん表示されました。(Win7 64bit , GVim 64bit)
このdllは64bitですよね？
![](https://lh4.googleusercontent.com/-UXwFtMI01Ps/UUSbJ0VbF0I/AAAAAAAADV0/q-bHlMPiqEU/s492/iconv.png)

**Comment by koron** [comment]
さーせん。64bitだと思いますがデバッグ版だったみたい。ちょっと差し替えます。

**Comment by koron** [comment]
http://files.kaoriya.net/var/libiconv-bin-3a86958.zip

こっち使ってください。32と64、同梱しておきました。あとiconv.exeも。

**Comment by h-east** [comment]
検証しました。GVim 7.3.831 (Win64 +kaoriya)
(値は3回計測の平均です)
(test.resultは `235aA<Esc>Y1368391p:w ++ff=dos test.result<CR>` で作成したものを使用)

```
gvim.exe -N -u NONE -U NONE -i NONE --startuptime st.txt --noplugin test.result
```

orig: 1968 msec
new:  1965 msec
※これが早いのはデフォルトのfencsの先頭にguessが入っているから
  (fileencodings=guess,ucs-bom,ucs-2le,ucs-2,iso-2022-jp-3,utf-8,euc-jisx0213,euc-jp)
<br>

```
gvim.exe -N -u NONE -U NONE -i NONE --startuptime st.txt --noplugin --cmd "set fileencodings=euc-jp,cp932,utf-8" test.result
```

orig: 37374 msec
new:   7283 msec
<br>

```
gvim.exe -N -u NONE -U NONE -i NONE --startuptime st.txt --noplugin --cmd "set fileencodings=euc-jisx0213,euc-jp,cp932,utf-8" test.result
```

orig: 28962 msec
new:   7505 msec
<br>

```
gvim.exe -N -u NONE -U NONE -i NONE --startuptime st.txt --noplugin --cmd "set fileencodings=iso-2022-jp,euc-jisx0213,euc-jp,cp932,utf-8" test.result
```

orig: 29217 msec
new:   8350 msec
<br>

```
gvim.exe -N -u NONE -U NONE -i NONE --startuptime st.txt --noplugin --cmd "set fileencodings=ucs-bom,iso-2022-jp,euc-jisx0213,euc-jp,cp932,utf-8" test.result
```

orig: 29197 msec
new:   8215 msec
<br>
すごい！`fencs`に`guess`未指定時の動作が 3.5倍から5倍くらい早くなりました！
Vimはiconvをいろんなとこで使っているのでエンコード変換が発生する場面では全体的に動作が早くなる予感。

ところで@Shougoさんの検証結果では`fileencodings`オプションの値が変わると時間がどんどん掛かっていっているのですが、その現象はこちらでは発生していません。
検証で使用しているファイルにASCII以外の文字が入っている可能性はないでしょうか？

**Comment by koron** [comment]
@h-east Thanks! いま 1.14 に差し替えるべく準備中。
intl.dllがiconv.dllに相当依存していたのを忘れてて苦闘中w
ただ目処はたった。

**Comment by koron** [comment]
とりあえず差し替えました。

**Comment by h-east** [comment]
@koron :+1: おつです。

あとは↓を解明&fixすればクローズできますね。 @Shougo さんよろしくです。

> ところで@Shougoさんの検証結果ではfileencodingsオプションの値が変わると時間がどんどん掛かっていっているのですが、その現象はこちらでは発生していません。

**Comment by Shougo** [comment]
Kaoriyaさんの最新版で試しました。

> gvim.exe -N -u NONE -U NONE -i NONE --startuptime st.txt --noplugin test.result

1357 ms

その他： 4000〜4600 秒

どうやら、試すたびに大幅に数字が変わってしまうようです。今回の問題は解決できたと思います。
ありがとうございます。

**Comment by h-east** [comment]
うーん、なんかうやむや感でもやもやする:stuck_out_tongue_closed_eyes:
本人がそれで良いなら構わないけど

**Comment by Shougo** [comment]
> うーん、なんかうやむや感でもやもやする:stuck_out_tongue_closed_eyes:
> 本人がそれで良いなら構わないけど

以前のDLLだと、fileencodingsを変更するごとに大幅に時間が変わるように見えました。が、今回のDLLではそういうことはありませんでした。
