### ISSUE TITLE
search() で stoppos を利用するとカーソルのある位置が検索対象から外れる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#326]
+kaoriya 7.3.831 win64 で確認しました。

`search()` で `stopline` を指定するとカーソルのある位置が検索対象から外れるようです。
下のようなテキストで `f` の位置にカーソルがある時に

```
foo
bar
```

ここで `stopline` を使わない場合は期待通りに検索できて

``` viml
:echo search('foo', 'n')
1
```

こうなりますが、ここで `stopline` を使うと

``` viml
:echo search('foo', 'n', 1)
0
```

検索に失敗します。 `search()` のヘルプには

> The search starts at the cursor position (you can use |cursor()| to set it).

とありますし、前者は成功することから後者も成功すべきと期待しています。

**Comment by koron** [comment]
あちなみに `foo` の前に半角スペースを置いてそこにカーソルを合わせた状態で

```
 foo
bar
```

`stopline` を使うと成功します。

``` viml
:echo search('foo', 'n', 1)
1
```

なので `stopline` の有無でカーソル下の文字が検索対象になるかならないかが決定していると推測しました。

**Comment by thinca** [comment]
カーソル位置のマッチは `c` オプションを入れた場合のみです。wrap でヒットしているだけだったりしませんか?

**Comment by koron** [comment]
デフォルトwrapだっけ?

**Comment by thinca** [comment]
デフォルトは `'wrapscan'` オプションに依存します。依存しないようにするには `w` か `W` を指定します。

**Comment by koron** [comment]
あ～了解。ためしたら確かに。んでは私の勘違いということで閉じます。

**Comment by k-takata** [comment]
xloseラベルを[invalid](https://github.com/vim-jp/issues/wiki/Member#invalid-)から[worksforme](https://github.com/vim-jp/issues/wiki/Member#worksforme-)に変更しておきます。
