### ISSUE TITLE
complete_check()が補完関数外からの呼び出しを想定されていない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#33]
まだcomplete_check()の実装を見ていないので確信は持てませんが、
complete_check()は補完関数外からの呼び出しを想定されていないようです。
具体的には、補完関数外から呼ぶと、ポップアップが開かれていないのに１を返したりします。
これはおそらく、バグだと思うのですが……。

**Comment by Shougo** [comment]
やっぱり、ソースコードを見たところグローバル変数をチェックしています。
ポップアップが出ているかどうかをチェックしていません。

**Comment by Shougo** [comment]
なんとなくバグが分かりました。
ins_compl_check_keys(frequency)は

```
if (using_script())
return;
```

となっていますが、

f_complete_check()は

```
int     saved = RedrawingDisabled;

RedrawingDisabled = 0;
ins_compl_check_keys(0);
rettv->vval.v_number = compl_interrupted;
RedrawingDisabled = saved;
```

となっていて、キャッシュされた戻り値をクリアしていません。これはバグるわけだ。
つまり、ins_compl_check_keys(0)の中でcompl_interruptedをクリアするか、
この関数がスクリプトから呼び出されたことを検知して、0を返すかする必要があります。

**Comment by mattn** [comment]
@koron 引き取りますか？

**Comment by koron** [comment]
None. 今、溜まってる方を優先します。

このまま @Shougo さんにパッチまで作ってもらえれば良いんじゃないでしょうか。

**Comment by Shougo** [comment]
パッチを書きました。一応エラーなどはないようです。
レビューをお願いします。

https://gist.github.com/1237553

**Comment by koron** [comment]
あとはProblemに相当する文章があれば、そのままvim-devに投げて大丈夫かと。

ただVimのせいですけどusing_script()って、なんかしっくり来ないですねw

**Comment by Shougo** [comment]
Problem: complete_check doesn't check called from script
Solution: check called from script

こんな感じでしょうか？

**Comment by mattn** [comment]
vim_devの他の報告を見て、不具合報告をどの程度書けば伝わるか読んだ方がいいかもですね。

**Comment by Shougo** [comment]
パッチ投稿しました。レビュー待ちです。

**Comment by mattn** [comment]
例を示してと言われてますよ。

**Comment by Shougo** [comment]
うーん、例と言ってもneocomplcacheくらいしか思いつきません。
一応書きましたけど、これで分かってもらえるかなぁ。

**Comment by koron** [comment]
「こんなスクリプトを書く時にcomplete_check()の動作が違う時に困るんだ」という限りなく最小の例を示したほうが良いですよ。
でないと相手に余計な負荷を押し付けてしまい「あーそんなに大変なら後回しね」という回答を引き出しやすくなります。

どこかのボブ(画家)じゃないですけど「ほら簡単でしょ?」という状況にしないと、取り込めるものも取り込めなくなってしまいます。

**Comment by Shougo** [comment]
> 「こんなスクリプトを書く時にcomplete_check()の動作が違う時に困るんだ」という限りなく最小の例を示したほうが良いですよ。

neocomplcacheくらいでしか思いつかなくて、「どうしよう」と考えているところです。
neocomplcacheのような補完関数を直接呼び出すスクリプトがもっとあれば問題になるんですけど……。

**Comment by thinca** [comment]
vim_dev への投稿のリンクがなかったので、後から辿れるように貼っておきます。
https://groups.google.com/d/topic/vim_dev/ZoinhH2h_24/discussion

**Comment by Shougo** [comment]
とりあえず、この方向は諦めているのでcloseします。
