### ISSUE TITLE
7.3.859 が Mac で問題が出てるらしい

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#332]
https://twitter.com/nakinor/status/311950551543844865

> Vim を 7.3.861 にアップデートしたのだけど、起動直後に(勝手に) REPLACE
> モードになってしまうようになった。MinGW でビルドしたやつはそんなことない
> んだけどなぁ。Esc を押せばいいだけなんだけど、なんだか気持ち悪い。

https://twitter.com/nakinor/status/312294790748319744

> vim-jp から clone したやつをビルドしてもダメだった...。設定ファイルはい
> じってないし、やっぱり、855 から 861 のどれかの patch が影響しているのか
> なぁ。Windows では問題がなくて Mac で問題が出てるってのもなぁ...。

@saitoha さん、わかりますでしょうか。

**Comment by saitoha** [comment]
おお、おしらせありがとうございます。
Patch 7.3.859で私のambiguous width自動設定パッチが入っていましたが、これの問題のような気がします。
カーソル位置報告シーケンス(CPR)というのが端末->vimの方向で来るのですが、この形式は

> ESC [ {y} ; {x} R

となっています。
この"R"の部分をキーインプットと誤認している(Rを押したと同じ効果となる)可能性が高いです。
いろいろうかがって再現させてみようと思います。

**Comment by uakms** [comment]
この度はお世話になります。
今回の現象が生じた環境は以下の通りです。

```
OSは MacOSX 10.3.9 (Panther)
端末は Terminal 1.4.6
SIMBL, ssh, screen, tmux すべて NO。
echo $TERM -> ansi
```

**Comment by saitoha** [comment]
ありがとうございます。
動作するppc macと該当Terminalのバージョンが手元にないので、いろいろ検討してみます。

**Comment by saitoha** [comment]
あ、あと$TERM_PROGRAMと$TERM_PROGRAM_VERSIONの値、

> stty -a

と打って出てくる結果を貼り付けていただければありがたいです。

**Comment by uakms** [comment]
echo $TERM_PROGRAM

```
Apple_Terminal
```

echo $TERM_PROGRAM_VERSION

```
100.1.8
```

stty -a

```
speed 9600 baud; 24 rows; 80 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
        -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
        -extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel -ignbrk
        brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
        -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
        eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
        min = 1; quit = ^\; reprint = ^R; start = ^Q; status = <undef>;
        stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

となりました。

**Comment by ynkdir** [comment]
ubuntuのgnome-terminalでも `$ TERM=ansi vim -u NONE -N` で置換モードになりますね

**Comment by mattn** [comment]
もし件のパッチで動作が変わったのが明確なら、vim-devに問題がある事、直せる見込みなど報告しておいて貰えると助かります。
すみません環境がないもので…

On 3/16/13, Yukihiro Nakadaira notifications@github.com wrote:

> ubuntuのgnome-terminalでも `$ TERM=ansi vim -u NONE -N` で置換モードになりますね
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/332#issuecomment-14997239

## 
- Yasuhiro Matsumoto

**Comment by saitoha** [comment]
あ、こちらでも

> TERM=ansi vim -u NONE -N

この条件で再現しました。
Mac/Linuxであればおそらく端末によらず再現するので、ひとまず報告しておきます。

**Comment by saitoha** [comment]
@nakinor @ynkdir 
対策入れてみたつもりなのですがいかがでしょう。HEADに対するパッチです。
https://gist.github.com/saitoha/5175048

**Comment by ynkdir** [comment]
直りました

**Comment by saitoha** [comment]
@ynkdir ありがとうございます

**Comment by saitoha** [comment]
う、問題の本丸はTERM=ansiの時に"ESC ["というtermcodeが登録されてしまっていることっぽい

**Comment by mattn** [comment]
対応速い！

On 3/16/13, Hayaki Saito notifications@github.com wrote:

> う、問題の本丸はTERM=ansiの時に"ESC ["というtermcodeが登録されてしまっていることっぽい
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/332#issuecomment-15000559

## 
- Yasuhiro Matsumoto

**Comment by saitoha** [comment]
Quick fixとして投げておきました
https://groups.google.com/forum/?fromgroups=#!topic/vim_dev/CuwxGqHMlUQ

**Comment by ynkdir** [comment]
GJ!

**Comment by uakms** [comment]
遅くなりましたが、こちらでも直りました。
ありがとうございます。

**Comment by h-east** [comment]
7.3.863で取り込まれました。素早い対応お疲れ様でした。
https://groups.google.com/d/msg/vim_dev/Mxm3Mw-2QpA/iD3u5FVy1JkJ

**Comment by mattn** [comment]
おつかれさまでした
