### ISSUE TITLE
Patch 7.3.872で入った 'fileignorecase' オプションの挙動が変かも？

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#333]
`set fic`時の `i_<C-X><C-F>` の挙動(補完候補の並び)がおかしい気がします。
後で細かい手順等コメントしますが、先に発見された方、報告よろしくお願いします。

**Comment by h-east** [comment]
私だいぶ花粉症でヤラれているので。。幻覚を見ている可能性もあります。
その際はご容赦下さい。
「でも私見たんです！」

**Comment by tyru** [comment]
ログ用に経緯となった会話貼っておきます。

https://twitter.com/h_east/status/314224156768104449

> @tyru vim -c "set fic" だと I.s j.s J.s i.s になりました。あれ？タイムスタンプ関係あるのか？いやおかしい。未だバグありそうな気がしてきたｗｗ

https://twitter.com/h_east/status/314225501449383936

> @h_east @tyru うん、おかしい。拡張子無かったら 'fileignorecase' のon/offで挙動が変化しないし。。set ficの時の順番がなんか変だ。(fedora17で確認)で

**Comment by h-east** [comment]
再現できました。(Vim 7.3.874 64bit on fedora17 64bit)

``` sh
$ mkdir test_fic
$ cd !$
$ touch I1.txt  I2.txt  J3.txt  J4.txt  i1.txt  j3.txt
$ ls
I1.txt  I2.txt  J3.txt  J4.txt  i1.txt  j3.txt
```

```
vim -N -u NONE -i NONE --noplugin -c "set nofic"
```

`i<C-X><C-F>` でファイル名補完すると下図のようにcase sensitiveで正しく表示されますが、
![](https://lh4.googleusercontent.com/-C3Dt-osUA4s/UUmItOdv_aI/AAAAAAAADWk/qsOs1Y-cNNU/s139/nofic.png)
<br>

```
vim -N -u NONE -i NONE --noplugin -c "set fic"
```

で同様にファイル名補完すると下図のようになり、case insensitiveでもcase sensitiveでもない並びになります。
![](https://lh4.googleusercontent.com/-iv8Qqq4InAs/UUmItFyfsJI/AAAAAAAADWg/7LvV4bs8-MQ/s140/fic.png)
<br>

ファイル名がcase sensitiveなOSで大文字小文字だけの違いのファイル名(例: I1.txt と i1.txt)が存在すると発生するみたいです。

**Comment by ynkdir** [comment]
私のとこでは再現できないので予想ですがこのへんですか
toupper(p[i]) - toupper(q[i]) じゃないといけないとか

```
misc2.c:pathcmp():6134
6134             return ((char_u *)p)[i] - ((char_u *)q)[i];     /* no match */
```

**Comment by h-east** [comment]
@ynkdir ありがとうございます。
助言を踏まえて以下のように修正したら直りました。

``` diff
diff -r d2571e334983 src/misc2.c
--- a/src/misc2.c   Tue Mar 19 18:31:49 2013 +0100
+++ b/src/misc2.c   Wed Mar 20 21:12:40 2013 +0900
@@ -6131,7 +6131,9 @@
        return -1;
        if (vim_ispathsep(q[i]))
        return 1;
-       return ((char_u *)p)[i] - ((char_u *)q)[i];     /* no match */
+       return p_fic ? TOUPPER_LOC(((char_u *)p)[i])
+           - TOUPPER_LOC(((char_u *)q)[i])
+           : ((char_u *)p)[i] - ((char_u *)q)[i];  /* no match */
    }
     }
     if (s == NULL) /* "i" ran into "maxlen" */
```

影響範囲デカいですが直前のif文でp_ficを参照しているので上記のように修正するべきですよね？

``` c
if ((p_fic ? TOUPPER_LOC(p[i]) != TOUPPER_LOC(q[i]) : p[i] != q[i])
```

**Comment by ynkdir** [comment]
そうですね、そんな感じだと思います

**Comment by h-east** [comment]
vim_devにpatch送りました。
https://groups.google.com/d/msg/vim_dev/H-aMlxlv8PU/rgrhPZRpFr4J

**Comment by ynkdir** [comment]
おつです！

**Comment by h-east** [comment]
あー、どうせなら並び順のポリシーを統一したかったな。
(大文字が先で小文字のは後とかのやつ)

**Comment by mattn** [comment]
乙

**Comment by h-east** [comment]
patch 7.3.874 で当該箇所にマルチバイト対応が入った。
それとは関係なく、自分のpatchはなんか違う気がしてきた。
週末に再検証します。
花粉どっかいけ

**Comment by h-east** [comment]
7.3.875でも再現しました。
これ、私以外に再現する人いらっしゃいませんか？ いらっしゃいませ～

**Comment by h-east** [comment]
このpatchやっぱり必要です。
例えば`set fic`な設定でpatch修正対象関数pathcmp()の引数pが "i1.txt"、qが "J1.txt"、maxlenが6の場合。
forループの1回目で以下のifの中に入る。（TOUPPER_LOC('i') != TOUPPER_LOC('J') → 'I' != 'J' → 0x49 != 0x4A なので）

``` c
if ((p_fic ? TOUPPER_LOC(p[i]) != TOUPPER_LOC(q[i]) : p[i] != q[i])
```

そしてreturn値は文字コードの差を返している。 'i' - 'J' → 0x69 - 0x4A → 0x1F
整数を返しているということは 引数pが文字コート的にデカいということなんだけど、`fic`の場合は間違い。
TOUPPERして 'I' - 'J' → 0x49 - 0x4A → -1
負数(引数qが文字コート的にデカい)を返してあげないといけない。
そうしないとファイル名の並びが変になる。

あと↓は嘘だったすまそ。

> ファイル名がcase sensitiveなOSで大文字小文字だけの違いのファイル名(例: I1.txt と i1.txt)が存在すると発生するみたいです。

なので
`$ touch I2.txt  J3.txt  i1.txt  j4.txt` だけで違いが出る。
'fic' and pre my patch → I2.txt  J3.txt  i1.txt  j4.txt
'fic' and post my patch → i1.txt  I2.txt  J3.txt  j4.txt

さらに↓も嘘だったｗ

> patch 7.3.874 で当該箇所にマルチバイト対応が入った。

ただ、この関数pathcmp()はPatch 7.3.872でTOUPPER系を使うようになったので、patch 7.3.874で他の関数に対して行なったようなマルチバイト対応がこの関数にも必要。

**Comment by h-east** [comment]
マルチバイト対応patch書いた。
for抜けてからのとこの修正がちょっとあやしいかも。チェックよろしく。

``` diff
diff -r acf7368a2acc src/misc2.c
--- a/src/misc2.c   Thu Mar 21 22:53:50 2013 +0100
+++ b/src/misc2.c   Mon Mar 25 04:11:54 2013 +0900
@@ -6099,52 +6099,59 @@
     int maxlen;
 {
     int        i;
+    int        c1, c2;
     const char *s = NULL;

-    for (i = 0; maxlen < 0 || i < maxlen; ++i)
+    for (i = 0; maxlen < 0 || i < maxlen; i += MB_PTR2LEN((char_u *)p + i))
     {
+   c1 = PTR2CHAR((char_u *)p + i);
+   c2 = PTR2CHAR((char_u *)q + i);
+
    /* End of "p": check if "q" also ends or just has a slash. */
-   if (p[i] == NUL)
+   if (c1 == NUL)
    {
-       if (q[i] == NUL)  /* full match */
+       if (c2 == NUL)  /* full match */
        return 0;
        s = q;
        break;
    }

    /* End of "q": check if "p" just has a slash. */
-   if (q[i] == NUL)
+   if (c2 == NUL)
    {
        s = p;
        break;
    }

-   if ((p_fic ? TOUPPER_LOC(p[i]) != TOUPPER_LOC(q[i]) : p[i] != q[i])
+   if ((p_fic ? MB_TOUPPER(c1) != MB_TOUPPER(c2) : c1 != c2)
 #ifdef BACKSLASH_IN_FILENAME
        /* consider '/' and '\\' to be equal */
-       && !((p[i] == '/' && q[i] == '\\')
-           || (p[i] == '\\' && q[i] == '/'))
+       && !((c1 == '/' && c2 == '\\')
+           || (c1 == '\\' && c2 == '/'))
 #endif
        )
    {
-       if (vim_ispathsep(p[i]))
+       if (vim_ispathsep(c1))
        return -1;
-       if (vim_ispathsep(q[i]))
+       if (vim_ispathsep(c2))
        return 1;
-       return ((char_u *)p)[i] - ((char_u *)q)[i];     /* no match */
+       return p_fic ? MB_TOUPPER(c1) - MB_TOUPPER(c2)
+           : c1 - c2;  /* no match */
    }
     }
     if (s == NULL) /* "i" ran into "maxlen" */
    return 0;

+    c1 = PTR2CHAR((char_u *)s + i);
+    c2 = PTR2CHAR((char_u *)s + i + MB_PTR2LEN((char_u *)s + i));
     /* ignore a trailing slash, but not "//" or ":/" */
-    if (s[i + 1] == NUL
+    if (c2 == NUL
        && i > 0
        && !after_pathsep((char_u *)s, (char_u *)s + i)
 #ifdef BACKSLASH_IN_FILENAME
-       && (s[i] == '/' || s[i] == '\\')
+       && (c1 == '/' || c1 == '\\')
 #else
-       && s[i] == '/'
+       && c1 == '/'
 #endif
        )
    return 0;   /* match with trailing slash */
```

**Comment by h-east** [comment]
vim_devへ再投稿
https://groups.google.com/d/msg/vim_dev/H-aMlxlv8PU/AwP8fxNWR60J

**Comment by mattn** [comment]
h-east++

**Comment by koron** [comment]
Todo listed.

> Patch to fix sorting order when 'fileignorecase' is set. (Hirohito Higashi,
> 2013 Mar 20)  Update Mar 24.

**Comment by h-east** [comment]
Patch 7.3.888 で取り込まれました。
https://groups.google.com/d/msg/vim_dev/7kQe4IYH6g0/BnjpR6i2z34J
