### ISSUE TITLE
macvim-kaoriyaのみ？で filetype=vim の時だけ正規表現がマッチしない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#334]
tyru/open-browser.vim#22

再現する環境としない環境があるみたいです... (上記issueに表有り)
共通しているのはシステムにデフォルトでインストールされているVmだと問題ないようです。(@yoshikawさんと@yonchuさんに確認済み)

@yoshikawさんが作ってくれた再現スクリプトは以下です。
https://gist.github.com/yoshikaw/5178771

**Comment by tyru** [comment]
再現スクリプトのgistの
- 「いつものvimを起動してからスクリプトをsourceして実行」
- 「コマンドラインからスクリプトファイルのみを実行」

の2つの結果が違っていたので、runtimeに'magic'の値が書き換えられてるのかと思い、[@yoshikawさんに確認してもらいましたが](https://github.com/tyru/open-browser.vim/issues/22#issuecomment-15005009)、`filetype=vim`の場合とそうでない場合と比べて変わってなかったようです。

**Comment by ynkdir** [comment]
ft=vim では iskeyword の値に `:` が含まれているため `'http://...' =~ '^http\>'` が false になります。つまり `:` が単語区切りになりません。

**Comment by tyru** [comment]
あーなるほど！iskeywordも影響してるとは気付きませんでした。
自分の`~/.vim/after/ftplugin/vim.vim`で`iskeyword`から`:`取り除いてました...orz
runtimeのバグかと思ってvim-jpに報告してしまった...
確認して自分の勘違いだということがわかったらcloseします...すみません。

**Comment by ynkdir** [comment]
no problem

**Comment by h-east** [comment]
@ynkdir ちょ～おっとこまえ:+1:

**Comment by tyru** [comment]
tyru/open-browser.vim#22 で問題を再現＆修正できたので閉じます。
@ynkdir さんありがとうございました！
