### ISSUE TITLE
python3インターフェイスの vim.eval() で日本語のPython文字列を扱えない

### ISSUE THREAD

**Issue by msmhrt** [vim-jp/issues#335]
【発生環境】
Vim: KaoriYa版 7.3.865 (2013/03/17版)
OS: Windows 7 Starter 32bit版

【概要】
python3インターフェイスの vim.eval() で、
- 日本語文字列を受け取れない
- 日本語のPython文字列を渡すと文字が化ける

【再現手順】
- 日本語文字列を受け取れない

```
（バッファの一行目に「あ」と入力しておく）
:py3 import vim
:py3 vim.eval('getline(1)')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid
start byte
```
- 日本語のPython文字列を渡すと文字が化ける

``` python
:py3 import vim
:py3 vim.eval('setline(1, "α")')
（バッファの一行目に「ﾎｱ」と出力される）
```

【その他】
Vimの内部エンコーディングとしてUTF-8以外のエンコーディングを想定していない箇所がありそうな感じですが、python3インターフェイスが有効で内部エンコーディングがUTF-8なVimは手元になかったので確認はしていません。

**Comment by koron** [comment]
ほ、ほーっ、ホアアーッ!! ホアーッ!!

( `set enc?` は cp932 ですか?)

**Comment by koron** [comment]
たぶんVimとPython3でブリッジするときに enc と UTF-8 の間で相互変換するだけ、と予測。

ただ何を変換して何をしないのかが難しいケース、それと取りこぼしがポロポロでるかも。

**Comment by koron** [comment]
手元の `enc=utf-8` なVimで試したら現象は発生しない。なので

> enc と UTF-8 の間で相互変換するだけ

これで対応できると考えて良いだろう。

**Comment by msmhrt** [comment]
encoding=cp932 でした。
＞ただ何を変換して何をしないのかが難しいケース、それと取りこぼしがポロポロでるかも。
Python 3インターフェイスを使ってバイト列を送受信したい時に面倒になるかもしれませんね。

**Comment by Shougo** [comment]
> Python 3インターフェイスを使ってバイト列を送受信したい時に面倒になるかもしれませんね。

私はvinariseでそういうことをやっていますね。Python3インタフェースはまだ使っていませんが、移植予定です。
vinariseで問題になるかどうかは見ておきたいところ。

**Comment by msmhrt** [comment]
Vimでは複数のエンコーディングが混在する文字列や不正なシーケンスを含む文字列も存在するようですが、Python 3の文字列型であるstr 型ではそのような文字列を扱えないのが厄介ですね。

str型よりはバイト列型であるbytes 型を使った方が良いのかもしれませんが、vim.eval() の引数と戻り値を常にbytes 型にするのであれば、

```
import codecs
import vim

VIM_ENCODING_DICT = {} 


def vim_eval(vim_script, raw=True):
    vim_eval.encoding = None

    def vim_encoding():
        if vim_eval.encoding is not None:
            return vim_eval.encoding
        encoding = vim.eval("&encoding".encode('ascii')).decode('ascii')
        vim_encoding = VIM_ENCODING_DICT.get(encoding, encoding)
        try:
            codecs.lookup(vim_encoding)
        except LookupError:
            raise UnicodeError("unknown vim encoding: " + vim_encoding)
        vim_eval.encoding = vim_encoding
        return vim_eval.encoding

    if not isinstance(vim_script, bytes):
        vim_script = vim_script.encode(vim_encoding())
    result = vim.eval(vim_script)
    if not raw:
        result = result.decode(vim_encoding())
    return result
```

のような wrapper を使わないと不便だと思います。

私は上記の wrapper のように、
- vim.eval() の引数はbytes 型とstr 型のどちらでも可
- vim.eval() の戻り値は基本的にstr 型 
- vim.eval(script, raw=True) のように raw=True を指定した時の戻り値はbytes 型
- 戻り値をstr 型に変換できなかった場合は、UnicodeEncodeError が発生

という仕様が好みです。

**Comment by Shougo** [comment]
うーむ。Python3インタフェースの実装を直すしか無いですね。

**Comment by msmhrt** [comment]
仮に vim.eval() の戻り値をbytes型で渡されても、PythonがVimと同じ文字エンコーディングを使える保証はないという問題もありますので、enc と UTF-8 はPython 3インターフェイス内で相互変換するのがベストでしょうね。

**Comment by h-east** [comment]
よくわかってないんですが、他のインタフェース(perl, ruby等)でも同様の問題は起きるのですか？

**Comment by mattn** [comment]
python3の文字列は全部unicodeのシーケンスなんですよ。なのでvim.evalは本来ならbytesじゃなくて文字列で返すべきなんですが、バグってるんだと思います。

```
vim.eval(x).decode(vim.eval("&encoding"))
```

で行けそうな気がしますが試してません。

**Comment by Shougo** [comment]
> 仮に vim.eval() の戻り値をbytes型で渡されても、PythonがVimと同じ文字エンコーディングを使える保証はないという問題もありますので、enc と UTF-8 はPython 3インターフェイス内で相互変換するのがベストでしょうね。

vinariseでは、文字列を相互に変換しています。

**Comment by msmhrt** [comment]
現状の `vim.eval()` はstr 型の文字列を返しますので

``` python
:py3 print(vim.eval('"a"'))
a
:py3 print(type(vim.eval('"a"')))
<class 'str'>
:py3 vim.eval('"a"').decode(vim.eval("&encoding"))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'
```

のようになります。

回避するだけであれば、日本語文字列を受け取れない問題は、

```
（バッファの一行目に「あ」と入力しておく）
:py3 import vim
:py3 print(vim.eval('iconv(getline(1), &encoding, "utf-8")') == chr(0x3042))
True
```

のようにVim側で `iconv()` を使ってUTF-8エンコーディングに変換すれば回避できます（`chr(0x3042)` は `"あ"` と同じです。）し、日本語のPython文字列を渡すと文字が化ける問題の方は、
- [Vimのpython3で日本語表示するの面倒くさすぎワロタｗｗｗ](http://qiita.com/items/791bd2b39424379d914c)

の方法で回避できます。

**Comment by Shougo** [comment]
今でもPython3インタフェースがこの状態では移行がかなりためらわれますね。もうVim 7.4が来る時代だというのに…。

**Comment by msmhrt** [comment]
基本的にはPython 3インターフェイスの実装時にencが非UTF-8な環境もあることが忘れられていたという話のようですので、
@koron さんの

> VimとPython3でブリッジするときに enc と UTF-8 の間で相互変換するだけ

で改善するはずです。

Python 3は文字列とバイト列を区別する言語なので、特殊なVim文字列を渡された場合にPython 3の文字列型では受けられないという別問題もありますが、PerlやRubyは文字列とバイト列の区別がない（ですよね？）ので大丈夫だと思います。

**Comment by Shougo** [comment]
> Python 3は文字列とバイト列を区別する言語なので、特殊なVim文字列を渡された場合にPython 3の文字列型では受けられないという別問題もありますが、PerlやRubyは文字列とバイト列の区別がない（ですよね？）ので大丈夫だと思います。

Rubyは1.9から区別したような気がする……。

**Comment by ynkdir** [comment]
`vim_eval = vim.bindeval('function("eval")')`

**Comment by msmhrt** [comment]
戻り値がbytes型な vim.eval() があったんですね...orz

``` python
:py3 print(repr(vim.bindeval(r'"\xff"')))
b'\xff'
```

**Comment by k-takata** [comment]
> - 日本語文字列を受け取れない
> - 日本語のPython文字列を渡すと文字が化ける

7.4a.1 で試してみました。
- enc=utf-8 の場合、getline(), setline() ともに問題なし。
- enc=cp932 の場合、getline() はUnicodeDecodeError、setline() は問題なし。

**Comment by k-takata** [comment]
vim.eval() の実体は、if_py_both.h の VimEval()。
その中で、VimToPython() を使って、VimL の戻り値を Python の型に変換しているらしい。

VimToPython() の中の、ここが原因？

``` c
    if (our_tv->v_type == VAR_STRING)
    ret = PyString_FromString(our_tv->vval.v_string == NULL
                    ? "" : (char *)our_tv->vval.v_string);
```

**Comment by k-takata** [comment]
こうだろうか？

``` diff
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -86,7 +86,8 @@
 #ifndef PyString_Check
 # define PyString_Check(obj) PyUnicode_Check(obj)
 #endif
-#define PyString_FromString(repr) PyUnicode_FromString(repr)
+#define PyString_FromString(repr) \
+    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, NULL)
 #define PyString_FromFormat PyUnicode_FromFormat
 #ifndef PyInt_Check
 # define PyInt_Check(obj) PyLong_Check(obj)
```

PyString_FromString() を使っている箇所全てに影響するが、これが正しいのかどうか不明。

**Comment by msmhrt** [comment]
手元で確認した限りでは大丈夫そうです。
Vimのエンコーディング名をそのままPythonのC APIに渡して大丈夫なのか少し不安になったのですが、既にそういう使い方をしている箇所があったんですね。
あと、FEAT_MBYTE が未定義の時は、PyUnicode_DecodeLatin1() にしておくと、シングルバイト圏の人達が喜ぶかもしれません。

**Comment by k-takata** [comment]
> あと、FEAT_MBYTE が未定義の時は、PyUnicode_DecodeLatin1() にしておくと、シングルバイト圏の人達が喜ぶかもしれません。

FEAT_MBYTE が未定義の時は、ENC_OPT が "latin1" になっていますのであまり気にする必要もなさそうな気がします。

**Comment by msmhrt** [comment]
あ、PyUnicode_DecodeLatin1() ならエンコーディングがlatin1固定なので、PyUnicode_Decode() で "latin1" を指定するよりは早いに違いないと思ったのでした。

**Comment by k-takata** [comment]
そのまま投げてしまいました。
https://groups.google.com/d/topic/vim_dev/PEqq6D5Z1ls/discussion

現状のコードは Latin1 固定の関数は全く使っておらず、関数のアドレスすら取得していないので、それを使うようにするのは面倒ですね。

**Comment by k-takata** [comment]
7.4a.008
https://groups.google.com/d/topic/vim_dev/IEcHN_a04lg/discussion
早すぎっ！

**Comment by h-east** [comment]
@k-takata :+1:
