### ISSUE TITLE
DirectWriteパッチ、完成させるよ。

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#337]
#262 で作ってきた DirectWrite のパッチをそろそろ終わらせたい。

とりあえず今までの成果を一つのパッチにまとめてみました。

[patch-direct_write-r3.diff](https://bitbucket.org/koron/vim-kaoriya-vim-mq-ex/src/a4fb89fcfead2e48d959e94d339e44e5ebe76abe/patch-direct_write-r3.diff?at=default)

@k-takata & みなさま: 確認をお願い致します。

**Comment by koron** [comment]
とりあえず r3 は送りました: https://groups.google.com/d/msg/vim_dev/t-v0_mJlogc/UQMfbvBnwWUJ

**Comment by Shougo** [comment]
そういえば、これとは別にWindows用のantialiasパッチというのも出てきているんですがあれとの違いはどこにあるんでしょうか。

**Comment by koron** [comment]
@Shougo いまみました。 [コレ](https://groups.google.com/d/msg/vim_dev/znyO3AEEIhw/jQyyKJUKt4MJ) ですね。

アレは「使用するフォントをアンチエイリアス指定するもの」なのに対し、
コッチは「フォントレンダリングにDirectXを使う」です。

書道で乱暴に例えると、筆を変えるのがあのパッチで、書く人を変えるのがこのパッチです。

**Comment by k-takata** [comment]
お疲れ様です。
私がRuby関連で Make_cyg.mak をいじったのが本体に取り込まれたせいで一部不整合が出てしまっています。修正パッチです。
https://bitbucket.org/k_takata/vim-win32-mq/src/62eb76089174fc828bcc62ae973180ef772341ef/fix-directwrite-Make_cyg.diff

gui_mch_set_rendering_options() のプロトタイプ宣言は、まだ gui_w32.pro には移動していないのですね。

**Comment by Shougo** [comment]
> アレは「使用するフォントをアンチエイリアス指定するもの」なのに対し、
> コッチは「フォントレンダリングにDirectXを使う」です。

あっちはWindows XP環境でも動くんですかね？
ClearTypeが有効になるのかな？

**Comment by koron** [comment]
@k-takata Thanks!

> gui_mch_set_rendering_options() のプロトタイプ宣言は、まだ gui_w32.pro には移動していないのですね。

これは最終的に Bram 任せで良いと考えてます。

**Comment by koron** [comment]
> あっちはWindows XP環境でも動くんですかね？

フォント次第では。

ただRicty&小さなサイズでは満足の行くレンダリングにはならないかも。
結局書いているのはGDIなので。

**Comment by Shougo** [comment]
GDIでできるだけ頑張る、というパッチなんですね。
どちらも本体に入ると良いですね。

**Comment by koron** [comment]
> 私がRuby関連で Make_cyg.mak をいじったのが本体に取り込まれたせいで一部不整合が出てしまっています。修正パッチです。
> https://bitbucket.org/k_takata/vim-win32-mq/src/62eb76089174fc828bcc62ae973180ef772341ef/fix-directwrite-Make_cyg.diff

本件修正し、レポジトリへの反映 & MLへの連絡を完了しました。

**Comment by h-east** [comment]
:+1: おつです。

**Comment by k-takata** [comment]
> これは最終的に Bram 任せで良いと考えてます。

りょーかい

**Comment by koron** [comment]
7.3.875 + r3a の [コンパイル済みバイナリ](http://files.kaoriya.net/var/vim73-kaoriya-dw96d-20130324.zip) を用意しました。

**Comment by Shougo** [comment]
！

**Comment by wiredool** [comment]
`:set` の実行により、 `gvim` が落ちたのでご報告です。

DirectWrite版(rev. d) にて、以下のコマンドで落ちました。

```
gvim-dw32.exe -N -u NONE -U NONE -i NONE --noplugin -c "set"
```

以下は問題なく実行できました。

```
gvim-dw32.exe -N -u NONE -U NONE -i NONE --noplugin -c "set all"
gvim.exe -N -u NONE -U NONE -i NONE --noplugin -c "set"
gvim.exe -N -u NONE -U NONE -i NONE --noplugin -c "set all"
```

実行環境
Windows Vista Business SP2 32bit
適用済パッチ: 1-875 香り屋 通常版 / DirectWrite版(rev. d)

エラー内容

```
[Window Title]
Microsoft Windows

[Main Instruction]
Vi Improved - A Text Editor は動作を停止しました

[Content]
問題が発生したため、プログラムが正しく動作しなくなりました。プログラムは閉じられ、解決策がある場合は Windows から通知されます。

[プログラムの終了(C)]
```

**Comment by k-takata** [comment]
こうですかね？

``` diff
--- a/src/option.c
+++ b/src/option.c
@@ -2086,7 +2086,7 @@
 #ifdef FEAT_RENDER_OPTIONS
     {"renderoptions", "rop", P_STRING|P_COMMA|P_RCLR,
                (char_u *)&p_rop, PV_NONE,
-               {(char_u *)0L, (char_u *)0L} SCRIPTID_INIT},
+               {(char_u *)"", (char_u *)0L} SCRIPTID_INIT},
 #endif
     {"report",     NULL,   P_NUM|P_VI_DEF,
                (char_u *)&p_report, PV_NONE,
```

# P_ALLOCEDフラグもいるのかよく分からない。

**Comment by koron** [comment]
@wiredool & @k-takata Thanks!

**Comment by koron** [comment]
@k-takata `P_VI_DEF` が必要だった。

**Comment by koron** [comment]
``` diff
--- a/src/option.c
+++ b/src/option.c
@@ -2103,9 +2103,9 @@
                (char_u *)&p_remap, PV_NONE,
                {(char_u *)TRUE, (char_u *)0L} SCRIPTID_INIT},
 #ifdef FEAT_RENDER_OPTIONS
-    {"renderoptions", "rop", P_STRING|P_COMMA|P_RCLR,
+    {"renderoptions", "rop", P_STRING|P_COMMA|P_RCLR|P_VI_DEF,
                (char_u *)&p_rop, PV_NONE,
-               {(char_u *)0L, (char_u *)0L} SCRIPTID_INIT},
+               {(char_u *)"", (char_u *)0L} SCRIPTID_INIT},
 #endif
     {"report",     NULL,   P_NUM|P_VI_DEF,
                (char_u *)&p_report, PV_NONE,
```

**Comment by koron** [comment]
直してパッチ更新しました。

**Comment by koron** [comment]
[描画位置がズレるって報告](https://groups.google.com/d/msg/vim_dev/t-v0_mJlogc/KQLxwcZ_KkMJ) が来ているけど、
[環境を可能な限り合わせても](https://groups.google.com/d/msg/vim_dev/t-v0_mJlogc/mXzhW2Qh0l8J) 手元で再現しないのでよくわからない…

**rop使用前**
![](http://i.imgur.com/zYIZo6s.png)

**rop使用後**
![](http://i.imgur.com/lssJh3p.png)

スクリーンショット上は確かにベースラインがおかしくなっているように見える。

**Comment by k-takata** [comment]
私もフォント関連の設定を合わせて試してみましたが再現しないですね。

**Comment by ynkdir** [comment]
もしかしたらこれっぽい？
-    mDpiScaleX = ::GetDeviceCaps(screen, LOGPIXELSX) / 96.0f;
-    mDpiScaleY = ::GetDeviceCaps(screen, LOGPIXELSY) / 96.0f;

VistaですがDPIを120にしたら下にずれました。
non directx では普通に表示されます。

**Comment by koron** [comment]
DPIか! 聞いてみます!

ってどこで調べりゃいいんだ?w

**Comment by ynkdir** [comment]
私が変更したのは `コントロールパネル/デスクトップのカスタマイズ/個人設定/フォントサイズ(DPI)の調整(左ペインのメニュー)` これです。

コマンドラインからだと `wmic DESKTOPMONITOR GET PixelsPerXLogicalInch,PixelsPerYLogicalInch` これで見れると思います。

**Comment by ynkdir** [comment]
↑ うちは Vista なので Windows7 は違うかもしれませんが

**Comment by koron** [comment]
やっぱDPIだったって!

> Aah, yes DPI setting!!
> 
> For the NG machine, DPI set to 125%, while OK machine is at default, 100%.

で、どうしたら良いのコレ?w

**Comment by k-takata** [comment]
DPI変えたらちゃんと動くのだろうかという疑問は前々からかすかにあったのですが、見事にはまってしまいましたかｗ
どうしたらいいんでしょう？ しかし、元にしたMSDNのサンプルコードってDPI awareだと思っていたのですが。
どこかで、Y方向の座標変換足りていないのか、2重に変換してしまっているのか…

**Comment by koron** [comment]
DirectWriteでメモリに書いてからBitBltしてるじゃないですが、
その座標計算で左下基準にしなきゃいけないのに右上基準にしちゃてる、とか?

**Comment by k-takata** [comment]
CreateGdiCompatibleTextLayout() に指定する幅高さは、物理ピクセル単位ではなく DIP (Device Independent Pixel) 単位だったのかも。

``` diff
--- a/src/gui_dwrite.cpp
+++ b/src/gui_dwrite.cpp
@@ -670,8 +670,8 @@
    BitBlt(memdc, 0, 0, w, h, hdc, x, y, SRCCOPY);

    hr = mDWriteFactory->CreateGdiCompatibleTextLayout(
-       text, len, mTextFormat, static_cast<FLOAT>(w),
-       static_cast<FLOAT>(h), mDpiScaleX, NULL, TRUE, &textLayout);
+       text, len, mTextFormat, static_cast<FLOAT>(w)/mDpiScaleX,
+       static_cast<FLOAT>(h)/mDpiScaleY, mDpiScaleX, NULL, TRUE, &textLayout);

    if (SUCCEEDED(hr))
    {
```

これで正しく表示できてるっぽいです。

**Comment by k-takata** [comment]
ちゃんと直すなら、こうですかね？

``` diff
diff --git a/src/gui_dwrite.cpp b/src/gui_dwrite.cpp
--- a/src/gui_dwrite.cpp
+++ b/src/gui_dwrite.cpp
@@ -409,6 +409,7 @@
     void DrawText(HDC hdc, const WCHAR* text, int len,
    int x, int y, int w, int h, int cellWidth, COLORREF color);

+    float PixelsToDipsX(int x);
     float PixelsToDipsY(int y);

     void SetRenderingParams(
@@ -670,8 +671,8 @@
    BitBlt(memdc, 0, 0, w, h, hdc, x, y, SRCCOPY);

    hr = mDWriteFactory->CreateGdiCompatibleTextLayout(
-       text, len, mTextFormat, static_cast<FLOAT>(w),
-       static_cast<FLOAT>(h), mDpiScaleX, NULL, TRUE, &textLayout);
+       text, len, mTextFormat, PixelsToDipsX(w),
+       PixelsToDipsY(h), mDpiScaleX, NULL, TRUE, &textLayout);

    if (SUCCEEDED(hr))
    {
@@ -686,7 +687,7 @@
            mRenderingParams);
        GdiTextRendererContext data = {
        color,
-       (FLOAT)cellWidth / mDpiScaleX,
+       PixelsToDipsX(cellWidth),
        0.0f
        };
        textLayout->Draw(&data, renderer, 0, 0);
@@ -702,6 +703,12 @@
 }

     float
+DWriteContext::PixelsToDipsX(int x)
+{
+    return x / mDpiScaleX;
+}
+
+    float
 DWriteContext::PixelsToDipsY(int y)
 {
     return y / mDpiScaleY;
```

**Comment by k-takata** [comment]
更新済みパッチ:
https://bitbucket.org/k_takata/vim-win32-mq/src/68749ecfe8a41912db1f8fe3e66e5724b32bad73/patch-direct_write-r3d.diff

参考リンク:
[高 DPI アプリケーションの記述方法](http://msdn.microsoft.com/ja-jp/library/ms969894.aspx) -- 12年も前の文章だった

**Comment by koron** [comment]
@k-takata Thanks! あっち(Luaトランスレータ)やってて出遅れたw 向こうにも送ってくれたみたいでありがとうございます。

で、パッチ見ました。おおむねOKですが、
メソッド定義の間の空行とZero Divide を事前に防ぐコードを追加して
私のパッチを更新しました。

**Comment by koron** [comment]
なんか上のスクリーンショット、丁寧にちゃんと見たらDPIだって気づいても良かったねw

**Comment by k-takata** [comment]
> Zero Divide を事前に防ぐコード

X  を２回チェックしてて、Y をチェックしていません。

**Comment by koron** [comment]
thanks!w

**Comment by ynkdir** [comment]
動作確認しました。問題なしです。

**Comment by k-takata** [comment]
もう1件、コメントにtypo発見。
https://bitbucket.org/k_takata/vim-win32-mq/src/1ba9a64d2412fd8c83c9bedc0d0b66e721587b08/fix-dwrite-typo.patch

> なんか上のスクリーンショット、丁寧にちゃんと見たらDPIだって気づいても良かったねw

何かフォントサイズが大きいなとは思っていたんですがねｗ

**Comment by k-takata** [comment]
todo.txt 更新されましたが、閉じますか？

> Patch to use directX to draw text on Windows.  Adds the 'renderoptions'
> option.  (Taro Muraoka, 2013 Jan 25, update 2013 Apr 3)

**Comment by koron** [comment]
@k-takata 閉じます&閉じました!

**Comment by extendash** [comment]
Kaoriya様で配布されているDirectWrite版(rev. d)にて、「:set」を実行すると落ちる現象は既知でしょうか？
「:set all」や「:set renderingoptions」のようにパラメータを渡すと問題ないです。
![Image1](https://f.cloud.github.com/assets/4117102/369497/c1fb11b8-a2d8-11e2-9324-6fabbb801afb.jpg)

なお、Vim 7.3.882 (2013/04/06版)の方では問題ありませんでした。
![Image2](https://f.cloud.github.com/assets/4117102/369502/dd49e688-a2d8-11e2-8fdb-2c63c9a97906.jpg)

**Comment by k-takata** [comment]
バイナリは、[上で指摘されている](#issuecomment-15396681)ものから更新されていないはずです。

**Comment by extendash** [comment]
@k-takata 失礼しました、このissueの中で既にご報告済みの内容でしたか。。。勢いに任せて書かずに、ちゃんと確認しておくべきでした。大変申し訳ありません。

**Comment by koron** [comment]
@extendash Thanks & sorry.  気になさらずガンガン書いてください。

**Comment by Shougo** [comment]
いつの間にかtodoリストに入っていたんですね。Vim 7.4行きかな？

**Comment by k-takata** [comment]
ちょっとした修正パッチ
https://bitbucket.org/k_takata/vim-win32-mq/src/8e7ee33791e68c8f674b324957100604024a792a/direct_write-use-ifdef-consistently.patch
- #if defined() ではなく #ifdef を使用。（#ifdef が使用可能な部分はそちらを使っていたと思いますので。）
- スペースでインデントしていたところをタブに修正。
- 末尾の空白削除。

**Comment by koron** [comment]
@k-takata Thank you! I have included just now.

**Comment by k-takata** [comment]
https://github.com/vim-jp/issues/issues/262#issuecomment-12990370 で指摘されていた問題ですが、GDIでも発生するものだと思っていたのですが、 https://github.com/vim-jp/issues/issues/450#issuecomment-30753235 に書いたとおり、DirectWrite版の不具合だと分かりました。

修正パッチです。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c916bbbdd6dcb31c44ac9d63146229a24bdd9c26/fix-dwrite-italic-overhang.patch
常に、右側1文字分余計に描画するようにしています。サブピクセルレンダリングを考えると、イタリック以外でも本来の文字の幅をはみ出して描画される可能性があるため、これで問題ないと思います。

**Comment by k-takata** [comment]
ドキュメントにミスを2カ所発見。
https://bitbucket.org/koron/vim-kaoriya-patches/src/44ecfe340d3038c2532b806408fd16e084cf0a58/X001-direct_write-r3.diff?at=default#cl-11
https://bitbucket.org/koron/vim-kaoriya-patches/src/44ecfe340d3038c2532b806408fd16e084cf0a58/X001-direct_write-r3.diff?at=default#cl-103
`'directx'` オプションは `'rop=type:directx'` に変更になりましたが、古い名前が残ったままになっています。

**Comment by k-takata** [comment]
ドキュメント修正案。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/e15545bd4f4a6cb7734728bb2ed8955016356de2/directwrite-update-docs.patch

**Comment by h-east** [comment]
だいぶ前だけどtodoリスト入り。

> Patch to use directX to draw text on Windows.  Adds the 'renderoptions'
> option.  (Taro Muraoka, 2013 Jan 25, update 2013 Apr 3, May 14)

いったん閉じますね。

**Comment by koron** [comment]
あードキュメントの修正やってないやー

**Comment by k-takata** [comment]
以下の2つのパッチがkaoriya patchにマージされていないので、そのためにreopenしていました。

https://bitbucket.org/k_takata/vim-ktakata-mq/src/c916bbbdd6dcb31c44ac9d63146229a24bdd9c26/fix-dwrite-italic-overhang.patch
https://bitbucket.org/k_takata/vim-ktakata-mq/src/e15545bd4f4a6cb7734728bb2ed8955016356de2/directwrite-update-docs.patch

**Comment by h-east** [comment]
(githubなんか変っすね。)
日にち経ってたので閉じましたが起こすアクションがあればreopenして活動して頂ければと思います。

**Comment by k-takata** [comment]
> (githubなんか変っすね。)

数日前に問題になってたやつですね。githubアカウントが日本語しゃべってびっくり。
https://twitter.com/github/status/491410847831298049
コメントを編集して、適当に半角スペースを追加してみたら、絵文字ではなくなったのですが、半角スペースを元に戻すと絵文字も元に戻ってしまいますね。

**Comment by h-east** [comment]
@k-takata あぅ、それもあるんですけど、
さっきopen issue数が0、closed issue数が18とかになりました。
再読み込みしてもダメでした。

**Comment by h-east** [comment]
> さっきopen issue数が0、closed issue数が18とかになりました。

すんまそん、自分でフィルタ掛けてました(苦笑い)

**Comment by koron** [comment]
www

**Comment by k-takata** [comment]
Windows incorrect rendering of international characters
https://groups.google.com/d/topic/vim_dev/PKYJhoWjZ0A/discussion
DirectWiteパッチが話題に…。

**Comment by k-takata** [comment]
7.4.393
https://groups.google.com/d/topic/vim_dev/KBk2ojpNNK0/discussion
上の残り2個のパッチのうち、ドキュメントのパッチは無くてもよい感じに修正されました。

**Comment by k-takata** [comment]
イタリックの末尾が切れる問題は投げました。
https://groups.google.com/d/msg/vim_dev/KBk2ojpNNK0/V2GU2DCOcXwJ

**Comment by k-takata** [comment]
7.4.394
https://groups.google.com/d/topic/vim_dev/LHg_2nVAJoQ/discussion

**Comment by Shougo** [comment]
取り込まれるの早い……

**Comment by h-east** [comment]
:+1: 

> Please keep an eye out for any other problems.  It's a big patch.

<⚫︎> <⚫︎>ｷﾗﾘ
