### ISSUE TITLE
64bit かつ ruby 2.0.0 の環境で、--enable-rubyinterp=dynamic でビルドできない

### ISSUE THREAD

**Issue by eagletmt** [vim-jp/issues#339]
手元の 64bit の Linux 環境では以下の修正でビルドが通りました。32bit の Linux 環境でのビルドも壊れていなさそうです。
どなたか Windows 環境等でも確認してもらえませんか。

``` diff
diff -ur vim-7-3-875.orig/src/if_ruby.c vim-7-3-875/src/if_ruby.c
--- vim-7-3-875.orig/src/if_ruby.c  2013-03-22 06:53:50.000000000 +0900
+++ vim-7-3-875/src/if_ruby.c   2013-03-25 00:30:38.070168877 +0900
@@ -184,6 +184,7 @@
 #if SIZEOF_INT < SIZEOF_LONG /* 64 bits only */
 #define rb_fix2int         dll_rb_fix2int
 #define rb_num2int         dll_rb_num2int
+#define rb_num2int_inline      dll_rb_num2int_inline
 #define rb_num2uint            dll_rb_num2uint
 #endif
 #define rb_lastline_get            dll_rb_lastline_get
@@ -284,6 +285,7 @@
 #if SIZEOF_INT < SIZEOF_LONG /* 64 bits only */
 static long (*dll_rb_fix2int) (VALUE);
 static long (*dll_rb_num2int) (VALUE);
+static long (*dll_rb_num2int_inline) (VALUE);
 static unsigned long (*dll_rb_num2uint) (VALUE);
 #endif
 static VALUE (*dll_rb_lastline_get) (void);
```

**Comment by k-takata** [comment]
試していませんが、Ruby 1.9で問題ないかが気になります。

```
#if defined(DYNAMIC_RUBY_VER) && DYNAMIC_RUBY_VER >= 20
...
#endif
```

が必要かも。

**Comment by eagletmt** [comment]
すみません、上のパッチは完全に間違っていました…
`rb_num2long()` や `rb_int2big()` で似たようなことをやっているのを見つけたのでそれを真似しました。64bit Linux 環境で ruby 1.9.3-p392, ruby 2.0.0-p0 共に `:ruby p Vim::Buffer[0]` が問題無く実行できることを確認しました。

``` diff
diff -ur vim-7-3-875.orig/src/if_ruby.c vim-7-3-875/src/if_ruby.c
--- vim-7-3-875.orig/src/if_ruby.c  2013-03-22 06:53:50.000000000 +0900
+++ vim-7-3-875/src/if_ruby.c   2013-03-25 03:35:47.871111239 +0900
@@ -88,6 +88,13 @@
 # define rb_int2big rb_int2big_stub
 #endif

+#if defined(DYNAMIC_RUBY_VER) && DYNAMIC_RUBY_VER >= 20 && SIZEOF_INT < SIZEOF_LONG
+/* Ruby 2.0 defines a number of static functions which use rb_fix2int and
+ * rb_num2int if SIZEOF_INT < SIZEOF_LONG (64bit) */
+# define rb_fix2int rb_fix2int_stub
+# define rb_num2int rb_num2int_stub
+#endif
+
 #include <ruby.h>
 #ifdef RUBY19_OR_LATER
 # include <ruby/encoding.h>
@@ -352,6 +359,16 @@
 {
     return dll_rb_int2big(x);
 }
+#if defined(DYNAMIC_RUBY_VER) && DYNAMIC_RUBY_VER >= 20 && SIZEOF_INT < SIZEOF_LONG
+long rb_fix2int_stub(VALUE x)
+{
+    return dll_rb_fix2int(x);
+}
+long rb_num2int_stub(VALUE x)
+{
+    return dll_rb_num2int(x);
+}
+#endif
 #if defined(DYNAMIC_RUBY_VER) && DYNAMIC_RUBY_VER >= 20
 VALUE
 rb_float_new_in_heap(double d)
```

**Comment by mattn** [comment]
環境によってはstubが足りんということか。

**Comment by k-takata** [comment]
#315 では LLP64 は確認してましたが、LP64 は確認してなかったですね。

**Comment by k-takata** [comment]
新パッチ、MSVC 32bit + ruby 2.0 と MinGW 64bit + ruby 2.0 で問題ないことを確認しました。

**Comment by mattn** [comment]
@eagletmt 送って頂いて構いませんし、こちらで代行可能です。(もちろん無料！観客：えぇ！)

**Comment by koron** [comment]
> 新パッチ、MSVC 32bit + ruby 2.0 と MinGW 64bit + ruby 2.0 で問題ないことを確認しました。

@k-takata 本題とはそれますけど、そのMSVCと組み合わせた ruby 2.0 は rubyinstaller (mingw)のものですか?
ならば配ってるバイナリも rubyinstaller へ切り替えようかしら…

**Comment by mattn** [comment]
今のrubyって自前ビルド？

**Comment by koron** [comment]
http://www.garbagecollect.jp/ruby/mswin32/ これ。

MSVCでの自前ビルドがすんなりできるのは試したので知ってるけど、僕がRubyバイナリ配るのもカオスというかw

**Comment by k-takata** [comment]
> そのMSVCと組み合わせた ruby 2.0 は rubyinstaller (mingw)のものですか?

ちゃいます。https://github.com/vim-jp/issues/issues/315#issuecomment-14172116 に書いたとおり ActiveScriptRuby 2.0.0-p0 です。

**Comment by koron** [comment]
Thanks!

…64ビット版ェ

Python ならば「ランタイム違ってもたぶんなんとかなるだと」と無理やり繋げてみるところだけど
Rubyだもんなぁ…まず間違いなくダメだよなぁ…

**Comment by mattn** [comment]
僕は rubyinstall です。

**Comment by koron** [comment]
MSVC+rubyinstallでちゃんと動いたら良いですなぁ。

**Comment by eagletmt** [comment]
@k-takata @mattn ありがとうございました。自分で送ってみます。

**Comment by koron** [comment]
@eagletmt :+1:

**Comment by h-east** [comment]
@eagletmt :+1: vim_dev投稿お疲れさまです。
https://groups.google.com/d/msg/vim_dev/P8l30hk9hyE/GFSinV_gHWAJ
Bram氏から「名前教えて頂戴。誰のかわからんソースは取り込めないよー」って言われてますね。

**Comment by mattn** [comment]
おっと...

thinca で通ってしまっている件...

https://groups.google.com/forum/#!searchin/vim_dev/thinca/vim_dev/AC3BsnFQCBA/gZN2L_sX_y4J

**Comment by h-east** [comment]
tyruさんもtyruで通したんじゃなかったっけ？ｗ

**Comment by tyru** [comment]
@h-east
ギリギリ人名だと思われたんじゃないでしょうか。
Tyrusって人もいますし。

**Comment by thinca** [comment]
私の時はメールのフッタに名前を入れてたので、それが使われたのではないでしょうか。メールアドレス=名前ではないですし。

https://groups.google.com/d/msg/vim_dev/kGMRZ1P1qBg/PxtdbNFD3O4J

**Comment by k-takata** [comment]
todo.txt 入りしました。

> Patch to make building with Ruby 2.0 on 64 bit system work. (eagletmt (Kohei
> Suzuki), 2013 Mar 25)

**Comment by k-takata** [comment]
7.3.889 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/DoMXPleOg_k/discussion

**Comment by eagletmt** [comment]
ありがとうございました!
