### ISSUE TITLE
権限設定の見直し

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#34]
@mattn & @thinca
よくわからないままissuesプロジェクトにwriter Teamを追加しちゃいました。
これでwriterへのassignはできるようになりましたが、
「よくわからないまま」やってしまったことに一抹の不安を覚えているので、
チェック&修正してください。

仕事を増やして申し訳ないです。

**Comment by mattn** [comment]
writer権限は記事を書ける人の位置づけなので、developerというチームを作りました。
メンバは
- これまでvim_devにパッチを送った事がある人
- 送りたいと思ってる(思ってそう)な人

で選別しました。

**Comment by mattn** [comment]
あまり知られてないけど実はtyruさんCONTRIBUTE AUTHOR

**Comment by koron** [comment]
Thanks. 閉じますね。
