### ISSUE TITLE
ifdef のインデント修正する?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#341]
https://gist.github.com/koron/5250637

このスクリプト使うと、Vimのソースコード内のpragmaのインデントが
ifdefのネストを正しく考慮したものに修正できる。

これvim_devに問うか?

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/D4mMcMFP7ak/CfBEp_lCxcIJ

投げるだけは投げてみた。

**Comment by h-east** [comment]
Patch 7.3.876
https://groups.google.com/d/msg/vim_dev/YwJU1dkwWUA/pUZULDBtKnQJ

報告分は取り込まれました。ので閉じます。
