### ISSUE TITLE
バッファ系のコマンド(:ls, :bnext, :brewind, etc...)がタブページ使用時を考慮していない

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#342]
@rbtnn さんのツイート
https://twitter.com/rbtnn/status/316753496856731648

> なんでvimはタブがバッファを持つ形になっていないのだろう？bnextとかやると別のタブで開いたバッファが出たりして不便。

(私はバッファもタブページも活用していないマルチインスタンスVim使いなのですけども)
確かにそう思います。

以前 https://github.com/vim-jp/issues/issues/116#issuecomment-3291393 でこんな提案というか呼び掛けしたけど無反応だった。

> あと、タブ関連のコマンドで提案です。
> 
> :tabs でも hidden なバッファを表示してはどうか？ （:buffers のような感じで）
> :buffers にタブページ番号を表示するようにしてはどうか？
> もしくは :buffers の指定タブ限定版コマンドを追加してはどうか？
> (例) :tabbuffers [N]
>               タブページ[N](デフォルト: カレントタブ)内の全バッファを表示する。

変更するとしたら
- 既存のバッファ系のコマンドの挙動を現状 or タブページ考慮か切り替えれるオプション(`'cpoptions'`オプションに追加？)を用意する。
- タブページ考慮版のバッファコマンドを新規に作る。(例えば :tabls, :tabbnext, :tabbrewind 等)
- その他

まずは愚痴でも何でも良いので意見を出しまくりましょう:smile:

**Comment by mattn** [comment]
例えばだけど、bnext した時に別タブで開かれてたらタブ移動するかどうかのオプション新設とか。

ただタブが後付けなので、こういう物という納得感はある。

vimスクリプトで :Bnext とか作れるだろうし。

On 3/27/13, h_east notifications@github.com wrote:

> @rbtnn さんのツイート
> https://twitter.com/rbtnn/status/316753496856731648
> 
> > なんでvimはタブがバッファを持つ形になっていないのだろう？bnextとかやると別のタブで開いたバッファが出たりして不便。
> 
> (私はバッファもタブページも活用していないマルチインスタンスVim使いなのですけども)
> 確かにそう思います。
> 
> 以前 https://github.com/vim-jp/issues/issues/116#issuecomment-3291393
> でこんな提案というか呼び掛けしたけど無反応だった。
> 
> > あと、タブ関連のコマンドで提案です。
> > 
> > :tabs でも hidden なバッファを表示してはどうか？ （:buffers のような感じで）
> > :buffers にタブページ番号を表示するようにしてはどうか？
> > もしくは :buffers の指定タブ限定版コマンドを追加してはどうか？
> > (例) :tabbuffers [N]
> >               タブページ[N](デフォルト: カレントタブ)内の全バッファを表示する。
> 
> 変更するとしたら
> - 既存のバッファ系のコマンドの挙動を現状 or タブページ考慮か切り替えれるオプション(`'cpoptions'`オプションに追加？)を用意する。
> - タブページ考慮版のバッファコマンドを新規に作る。(例えば :tabls, :tabbnext, :tabbrewind 等)
> - その他
> 
> まずは愚痴でも何でも良いので意見を出しまくりましょう:smile:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/342

## 
- Yasuhiro Matsumoto

**Comment by h-east** [comment]
> 例えばだけど、bnext した時に別タブで開かれてたらタブ移動するかどうかのオプション新設とか。

私はタブ内のバッファのみを対象にする感じをイメージしました。タブは移動させず、現タブ内の世界。

> ただタブが後付けなので、こういう物という納得感はある。

はい、それは同意です。でもそういう背景知らないニュートラルな人からしたらやっぱちょっと不自然に思われるんじゃないかと。

> vimスクリプトで :Bnext とか作れるだろうし。

そういえば `:ls` じゃタブの情報分かんないんですけどVim pluginerはどうやってバッファとタブの関係をゲットしてるのでしょうか？
`gettabvar()` や `gettabwinvar()` とか？

**Comment by osyo-manga** [comment]
どうもタブ多用しているマンです。
具体的には1つのバッファに1つのタブ（ウィンドウ）を割り当てて使用しています。

> なんでvimはタブがバッファを持つ形になっていないのだろう？bnextとかやると別のタブで開いたバッファが出たりして不便。

`:bnext` ではないんですがファイルを開く際は `:tab drop` を使用していますね。
これで開くファイルが他のタブで開いているとそこへ移動するのでそこまで不便とは感じていません。

> ただタブが後付けなので、こういう物という納得感はある。

わたしもそういうものだと思っているのであまり違和感がありませんね。
（どちらかというと"バッファ"というものを意識したくない感がありますが。

> そういえば :ls じゃタブの情報分かんないんですけどVim pluginerはどうやってバッファとタブの関係をゲットしてるのでしょうか？

タブが保持しているバッファ番号一覧は `tabpagebuflist` で取得出来るので、それを使用するとこんな感じですかね。

``` vim
function! GetBufnr2Tabnr(bufnr)
    let result = []
    for tabnr in range(1, tabpagenr("$"))
        for bufnr in tabpagebuflist(tabnr)
            if bufnr == a:bufnr
                call add(result, tabnr)
            endif
        endfor
    endfor
    return result
endfunction

" バッファ1 が開かれているタブ番号は [1, 3, 3, 4]
" GetBufnr2Tabnr(1) => [1, 3, 3, 4]
```

タイトルとは関係ないですが個人的にはウィンドウ内タブが欲しいと思っていたり（ﾎﾞｿ

**Comment by Shougo** [comment]
一応私もタブを使用している一人です。

私のタブの使用方法はプロジェクトごとにタブを切り替えることです。

> タイトルとは関係ないですが個人的にはウィンドウ内タブが欲しいと思っていたり（ﾎﾞｿ

ウインドウ内タブをイメージしづらいので、具体例を上げたほうが良いかと。

タブの話については、私自身はこの仕様に納得しています。
ウインドウを複数合わせたものがタブという認識だからです。
ただ、そのイメージは他のエディタにおけるタブとは明らかに仕様が異なり、そちらの仕様のほうが自然と考えている人たちにとって混乱を与えているという事はあると思います。

タブの変わった仕様と言えば、タブのウインドウが一つしか無いとき、:quitや:bdeleteするとタブが閉じてしまうことですかね。
これも、ウインドウと挙動が同じですけど。おそらく、Bram氏的にも実装的にもタブとウインドウは同じ概念なんでしょう。

※：そういえば、タブ番号がバッファ番号のような絶対番号でないのもウインドウの仕様に合わせたのだろうか……

**Comment by osyo-manga** [comment]
> > タイトルとは関係ないですが個人的にはウィンドウ内タブが欲しいと思っていたり（ﾎﾞｿ
> 
> ウインドウ内タブをイメージしづらいので、具体例を上げたほうが良いかと。

例えば、上がソースファイルウィンドウ、下がエラー一覧ウィンドウ（quickfix）みたいなレイアウトはよくあると思います。
こういう時にレイアウトを保持したままソースファイルウィンドウ上でソースファイルの一覧をタブで表示し、移動出来れば便利かなーと。
今はこんな感じでタブラインにウィンドウ内のタブを表示させていたりします。

![windowtab](https://f.cloud.github.com/assets/214488/311394/ac625e1a-973e-11e2-9a55-f71fdbb8e69f.PNG)

**Comment by h-east** [comment]
タブとウィンドウの関係性の話ではなくって、
タブ使用時のバッファ系コマンドの挙動についての話がメインです。
もちろんウィンドウも関係しますけども、あくまでもバッファが主役ということでお願いします。

**Comment by h-east** [comment]
「ウィンドウの話はしないで」と言っているわけではなく、「主役を踏まえてね」ってことです。

**Comment by osyo-manga** [comment]
すみません。。。

**Comment by thinca** [comment]
私は、@mattn さんも言っているようにプラグインで対処すれば良いと思います。
`BufReadPost` などで開いたバッファの ID をタブページ変数に記録しておけば可能かと思います。
実際、`unite-buffer_tab` なんかはそのようにしていたと思います。

**Comment by h-east** [comment]
@osyo-manga 主役を踏まえていればなんでもありです。ネタ画像貼り付けもありです。
踏まえてなくても後で誰かが方向修正すればおkですし。
って、ちゃんと「タイトルとは関係ないですが」と前置きされてましたね。こちらこそすんません。
tabpagebuflist()は知らなかったです。thanks.

**Comment by koron** [comment]
> もちろんウィンドウも関係しますけども、あくまでもバッファが主役ということでお願いします。

せっかくやからウィンドウ(+タブ)が主役の話もissue化しとけば?

**Comment by h-east** [comment]
> せっかくやからウィンドウ(+タブ)が主役の話もissue化しとけば?

ウィンドウとタブの関係は私は現仕様に文句はないです。
気になる人はissue立てちゃって下さい。

**Comment by Shougo** [comment]
> タブとウィンドウの関係性の話ではなくって、
> タブ使用時のバッファ系コマンドの挙動についての話がメインです。
> もちろんウィンドウも関係しますけども、あくまでもバッファが主役ということでお願いします。

了解です。ただ、私は現在の仕様に満足してしまっているので、どのあたりが不満なのか、どう改善しようと考えているのかが見えていなかったりするのです。

**Comment by h-east** [comment]
特に誰も困っていないのと、どうすべきかの方向性も定まらなかったので`worksforme`で閉じます。
