### ISSUE TITLE
help原文の「viにはない」の表記ゆれの統一を検討する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#343]
[元](https://github.com/vim-jp/vimdoc-ja/issues/73#issuecomment-15674071) より。
@nakinor さんが作ってくれたパッチ: https://gist.github.com/nakinor/5277479

---

ヘルプファイル(farsi.txt)の先頭にある

> {Vi does not have any of these commands}

は

> {Vi does not have any of these features}

としたほうが良いんじゃないか、という提案があり、
[farsi.txt を直してもらった](https://gist.github.com/nakinor/5277479) のですが、どうも他にもありそうだと気になったので
簡単に(間違いがあるかも)ですが調べてみました。

```
Using "{Vi does not have any of these commands}" phrase at top of the file.

  * arabic.txt
  * autocmd.txt
  * digraph.txt
  * eval.txt
  * farsi.txt
  * filetype.txt
  * gui.txt
  * gui_x11.txt
  * hebrew.txt
  * if_cscop.txt
  * if_lua.txt
  * if_mzsch.txt
  * if_ole.txt
  * if_perl.txt
  * if_pyth.txt
  * if_ruby.txt
  * if_sniff.txt
  * if_tcl.txt
  * quickfix.txt
  * remote.txt
  * rileft.txt
  * spell.txt
  * syntax.txt
  * tabpage.txt
  * windows.txt

Using "{Vi does not have any of these features}" phrase.

  * debugger.txt
  * mlang.txt
  * netbean.txt
  * sign.txt
  * workshop.txt

Using other phrase.

  * diff.txt {not in Vi}
  * fold.txt {Vi has no Folding}
  * gui_w16.txt {Vi does not have a Windows GUI}
  * gui_w32.txt {Vi does not have a Windows GUI}
  * hangulin.txt (should have)
  * pi_gzip.txt {Vi does not have any of this}
  * print.txt {Vi has None of this}
  * visual.txt {Vi has no Visual mode, the name "visual" is used for Normal mode, to
```

vim-dev に相談したほうが良いかな?

**Comment by mattn** [comment]
https://github.com/vim-jp/vimdoc-ja/issues

こっちの方が良くない？

**Comment by thinca** [comment]
vimdoc-ja は日本語 help で、この問題は本体の help だからって話だったおぼろげな記憶が。

**Comment by thinca** [comment]
全部消えた。 〜完〜

https://github.com/vim/vim/commit/25c9c680ec4dfbb51f4ef21c3460a48d3c67ffc8

> patch 8.1.1280: remarks about functionality not in Vi clutters the help
>
> Problem:    Remarks about functionality not in Vi clutters the help.
> Solution:   Move all info about what is new in Vim or already existed in Vi to
>             vi_diff.txt.  Remove {not in Vi} remarks. (closes #4268) Add
>             "noet" to the help files modeline.  Also include many other help
>             file improvements.

**Comment by thinca** [comment]
実は1箇所消し忘れがあるようだが…。

https://github.com/vim/vim/blob/0522ba0359c96a8c2a4fc8fca0d3b58e49dda759/runtime/doc/syntax.txt#L43
