### ISSUE TITLE
vim-jp.org名刺が欲しい

### ISSUE THREAD

**Issue by raa0121** [vim-jp/issues#349]
http://lingr.com/room/vim/archives/2013/04/01#message-14552477

> vim-jp名刺あると便利そうです
> 画像部分は硬派にvimロゴだけで
> 名前とか連絡先とかに行番号つけたいです

この一声からレイアウトを考えてみました
![名刺](http://gyazo.cre.jp/data/dea3cd596001f01707d5d96bdeef5979.png)

また、http://lingr.com/room/vim/archives/2013/04/03#message-14578007

> 名刺の裏面気になる。

とのことなので、裏面のデザインを募集します

PSDファイル置いておきますね

https://dl.dropbox.com/u/10753402/vim-jp.org%E5%90%8D%E5%88%BA.psd

**Comment by koron** [comment]
Vimロゴのアスペクト比が1:1じゃないように見えるんですか、わざと？
それともメール経由でみているせいかな…？

**Comment by heavenshell** [comment]
ちゃんと 1 : 1 に見えます。
多分メール経由が原因じゃないですかねー:-)

**Comment by koron** [comment]
今はgmailのAndroidでみてます。
あとでpcから見直してみます。

**Comment by heavenshell** [comment]
私の目が今おかしいので 1:1 じゃない時はごめんなさいw

**Comment by raa0121** [comment]
一応1:1に調整したつもりですが… 微妙にずれがあるかもしれません。
元ファイルはこちらです
http://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Vimlogo.svg

**Comment by h-east** [comment]
本人の体型に合わせてアスペクト比変えるアイデア素晴らしい！

**Comment by koron** [comment]
(´・ω・`)

**Comment by raa0121** [comment]
そういえば、vim-jp.orgのメールアドレスって作ってもらえるんでしょうか？
名刺に載せるならそっちのアドレスのほうがかっこいいかなと思っただけなので、無理なら無理でいいです。

**Comment by mattn** [comment]
google apps ならいけたけど、有料になっちゃったしね

**Comment by mattn** [comment]
こんなのはあるけど https://domains.live.com/ 送信メールに広告入るらしい。

**Comment by koron** [comment]
あ～Google Appsに登録するつもりで忘れてた。まぁ、先着何名様になっちゃうけどね…

**Comment by koron** [comment]
あ、やっぱVimのロゴ、歪んでるな。
以下のどちらかベースで作り直せますか?

https://github.com/vim-jp/vim/blob/master/runtime/vimlogo.pdf
https://github.com/vim-jp/vim/blob/master/runtime/vimlogo.eps

あと、これHTMLとCSSで構成できませんかね?
印刷用のCSSがあればvim-jp.org上でジェネレータをホストするのも有りかなと。

**Comment by raa0121** [comment]
![eps版](http://gyazo.cre.jp/data/55fc3c18fd1fdce6ee96d97a996b04eb.png)
![pdf版](http://gyazo.cre.jp/data/823673604ef357d15734fe519d25f632.png)
差し替えてみました

**Comment by koron** [comment]
![](https://a248.e.akamai.net/assets.github.com/images/icons/emoji/+1.png)

**Comment by thinca** [comment]
個人のアイコンも欲しいですね。裏面に入れるといい感じかな?

**Comment by raa0121** [comment]
@koron 

> あと、これHTMLとCSSで構成できませんかね?
> 印刷用のCSSがあればvim-jp.org上でジェネレータをホストするのも有りかなと。

CSSは苦手なので誰かが作ってくれると嬉しいなぁ…

@thinca 

> 個人のアイコンも欲しいですね。裏面に入れるといい感じかな?

裏面まで印刷すると高いんですよねぇ…

**Comment by supermomonga** [comment]
http://vimcard.herokuapp.com/

とりあえずリアルタイムプレビューまで作りました。

TODOとしては
- 複数デザイン対応
- Canvas化
- Canvasのbase64化でクライアント側のみで画像生成

があります。
VimConfまでには間に合わせたいです。

デザイン用のPSDは
https://dl.dropboxusercontent.com/u/330501/resource/vim/vimcard-sample.psd
です。ガイド引いてあります。

**Comment by k-takata** [comment]
ロゴのアスペクト比が…

**Comment by supermomonga** [comment]
> ロゴのアスペクト比が…

@raa0121 さんさんからもらったPSDを元にしてるので、
らぁさんがアスペクト比正しいの投下してくれると直りそう

**Comment by raa0121** [comment]
> https://github.com/vim-jp/vim/blob/master/runtime/vimlogo.pdf
> https://github.com/vim-jp/vim/blob/master/runtime/vimlogo.eps

@supermomonga こちらから差し替えましょう

**Comment by supermomonga** [comment]
アッハイ

**Comment by h-east** [comment]
いい感じに出来上がったようですので閉じます。
