### ISSUE TITLE
WindowsのMinGW環境にて、xxdのmakeに失敗する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#35]
最新版のVimのsourceをコンパイルしようとしたところ、xxdのmakeの途中で以下のようなエラーが出てmakeが止まってしまいました。
gvim.exeはできていますが、vim.exeはできていないですね。

cc1.exe: error: unrecognized command line option '-mno-cygwin'
E:/MinGW/bin/mingw32-make.exe -C xxd -f Make_cyg.mak CC=gcc

どうやら、最近のMinGW gccコンパイラには-mno-cygwinオプションが実装されていないようです。
これはMakefileを修正するべきではないでしょうか？

GCCのバージョンは以下の通りです。

gcc.exe (GCC) 4.6.1
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mattn** [comment]
これ、もしかして通常のmingwなのにcygwinから使ってませんか？

だとしたら、cygwin版じゃないgccをcygwin依存なオプションを指定してエラー出るのは当たり前です。
Make_cyg.makを使うならmingw版のgccじゃなくて、cygwin付属のgccを使うべきですね。

**Comment by Shougo** [comment]
Cygwinは使っていません。
MinGWのパスを先頭に持ってきているため、Cygwinは使われないはずです。

と、コマンドライン履歴を見ていて気づきました。
Make_ming.makではなく、Make_cyg.makになってますね……。もう一度試します。

**Comment by Shougo** [comment]
げ、Make_ming.makを指定しているのに、勝手にMake_cyg.makを使おうとしているようです。
これはバグでは……。

% mingw32-make.exe -f Make_ming.mak GUI=yes IME=yes MBYTE=yes ICONV=yes DEBUG=no
E:/MinGW/bin/mingw32-make.exe -C xxd -f Make_cyg.mak CC=gcc
mingw32-make.exe[1]: Entering directory `H:/Work/vim/src/xxd'
gcc -O2 -Wall -DWIN32 -mno-cygwin -s -o xxd.exe xxd.c

**Comment by mattn** [comment]
あー、Make_ming.makが横着してMake_cyg.makを使ってるんですね。
それと同時にmingw付属のgccが4.6に変わって-mno-cygwinがobsolute扱いになったっぽいですね。

http://lists.gnu.org/archive/html/mingw-cross-env-list/2011-03/msg00119.html

週明けまで誰もパッチ書かなかったら僕が書きますが、Shougoさん書きますか？
であればassignしますが。

**Comment by Shougo** [comment]
ちょっとこれについては、練習がてら私にやらせてください。
初パッチを書いてみたいのです。

**Comment by Shougo** [comment]
GVimExtも-mno-cygwinを使っていて、間違っていたので修正しました。
MinGW環境ではコンパイルできましたが、Cygwinなどではどうなのか分かりません。

**Comment by Shougo** [comment]
パッチを書きました。レビューをお願いします。

https://gist.github.com/1237467

**Comment by mattn** [comment]
今Windows無いので試せないですが...

まだこの先gcc4.5(-mno-cygwinが動く)を使う人もいるのでMake_mingw.makのコメント

> Can be used for Cygwin and MingW (MingW don't ignore -mno-cygwin)

はどちらかと言うと

> Don't use for Cygwin.

として「Make_ming.makは今後cygwinから使うな」という仕様としてMake_cyg.makを別途作る方が良いと思います。
で、Make_cyg.makの方は現状の-mno-cygwinの付いたMake_ming.makをコピーする形で良いと思います。(コメントは修正する必要ありますが)

**Comment by koron** [comment]
どうでも良い指摘を2点しておきました。

ところでなんかレビューシステムないんですかね?
行ごとにコメント付けられるようなの。

**Comment by mattn** [comment]
gistじゃなくてgithubならcommit上にインラインコメントが書けるのですが...

http://codereview.appspot.com みたいなのがベスト。

**Comment by koron** [comment]
vimのソースがgithub上にないのが問題か?
ってか誰か最新版のコピー維持してたりしないのかな?

**Comment by Shougo** [comment]
誰かがミラーしていたような気はします。

**Comment by Shougo** [comment]
ありました。例えば、こことか。

https://github.com/b4winckler/vim

**Comment by Shougo** [comment]
もう、これからforkして管理した方がよいような気がしてきました……。

**Comment by mattn** [comment]
んー。forkするかについては意見が分かれそうな気がする。

**Comment by koron** [comment]
修正をレビューする目的ならforkで良いんじゃないですか?
vim-jpの配布物を作るため、となると @mattn さんの言うとおり考えたほうが良いかもですが。

**Comment by Shougo** [comment]
とりあえず、指摘された点は修正しました。しかしgitの方がgithubでの管理はしやすいですね……。

**Comment by mattn** [comment]
あとは
- mingwのgcc4.6で-mno-cygwinがobsoluteになった
- Make_ming.makは今後cygwin用で使うべきでない

という点をうまく英語で伝えられれば良いですね。
good luck

**Comment by Shougo** [comment]
そうですね……。レビューありがとうございました。

**Comment by Shougo** [comment]
パッチ投稿しました。レビュー待ち。

**Comment by Shougo** [comment]
Bramさんから返信がきました。が、意味が分かりません……。
どういうことなんでしょうか？

> It looks like you rely on making a copy of GvimExt/Make_ming.mak to 
> GvimExt/Make_cyg.mak.  Before you make the change to Make_ming.mak. 
> The copied version of xxd/Make_ming.mak is included, the copy in 
> GvimExt/ not. 

GvimExt/Make_ming.makが入っていない、と言っていますが、
パッチを見ると変更点は入っていますよね。

**Comment by ynkdir** [comment]
GvimExt/Make_cyg.mak がない、じゃないかと

**Comment by Shougo** [comment]
あ、確かにない気がしますね。
addし忘れたのかな。修正します。

**Comment by mattn** [comment]
この件と、 #33 のレスに応答はしないんですか？ #33 はtodo行きになるだろうけど、この件はすぐパッチがリリースされる類のもので、何人かのmingwユーザはShougoさんのスレッドみて待機してるかも。

**Comment by Shougo** [comment]
あれー返信したはずですが。
と思っていたら、Bramさんに直接返信していた……。
返信を送り直しました。

**Comment by tyru** [comment]
7.3.326 で取り込まれましたね。
https://groups.google.com/group/vim_dev/browse_thread/thread/45c3472732e9deb?hl=ja

**Comment by Shougo** [comment]
確認しました。closeします。

**Comment by mattn** [comment]
んー。patchはokだけどbramがhgに`src/xxd/Make_ming.mak`入れ忘れてるなー。
すんませんけど、直るまで(忘れない意味で)reopenしますね。
(Shougoさんのせいじゃないすよ)

**Comment by koron** [comment]
hg addし忘れたんかw

**Comment by Shougo** [comment]
これは指摘してあげる必要が。
というか、私と全く同じミス……。

**Comment by mattn** [comment]
既に指摘済みですよ。

**Comment by ujihisa** [comment]
なんというオチ

**Comment by mattn** [comment]
入れてくれたらしいので閉じます
