### ISSUE TITLE
foldmethod="syntax"またはfoldmethod="expr"の状態でバッファを変更をすると非常に遅い

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#350]
https://github.com/Shougo/neocomplcache/issues/368

前々から気づいていた問題なのですが、原因をもっと詳しく調べたいのでここに報告しておきます。
foldmethod="syntax"またはfoldmethod="expr"の状態で自動補完をすると、耐えられないほど遅いです。foldmethodを"manual"に変更すると解消しますが、今度はfoldmethodを元に戻すコストが発生します。

この問題はなぜ起こっているのでしょうか。
ちなみに自動補完以外では、特に遅くなっているように見えないので、ポップアップを開くときに問題となるのでしょうか。

追記：その後の調査の結果、自動補完やポップアップは一切関係がなく、バッファを変更するだけで起こることが発覚しました。

**Comment by Shougo** [comment]
自分で試してみたところ、自動補完が原因ではないですね。
filetype=vimにおいて、foldmethod=syntaxとして"("を入力したりすると入力が非常に重く感じられます。
どうやらバッファの内容が変化するごとに再計算を行なっているようです。
それと自動補完のオーバーヘッドが重なり、非常に遅く感じられます。
foldmethod=syntaxやfoldmethod=exprの再計算のタイミングを入力時ではなく、インサートモード・ノーマルモードの切替時等に制限すればこの問題は改善できるかもしれません。

※：自動補完が原因ではないので、タイトルを変更しました。

**Comment by Shougo** [comment]
neocomplcacheでは仕方ないので、syntaxやexprの時には一時的にfoldmethodをmanualに変更しているのですが
foldmethodの切り替えのコストも馬鹿になりません。

**Comment by h-east** [comment]
「感じられます」だとどれくらい遅いのか分からないので数値(msec)で提示してもらえますか？
(ストップウォッチで測ってもいいですし)

**Comment by mattn** [comment]
あとPCのスペック、OS、使用プラグイン一覧もできれば書いて下さい。Shougoさんのは色んなプラグインが絡み合っててvim本体のバグと言い辛い可能性もあります。

**Comment by Shougo** [comment]
速報値：autoload/neocomplcache.vimにおいて、neocomplcacheを無効にし(を入力した状態。
ストップウォッチで測定したところ、1文字の入力で1.47sかかっています。

OS: Ubuntu 13.04
Vim: 7.3.884
CPU: Intel(R) Pentium(R) CPU G630 @ 2.70GHz 2 Core

今度はプラグインなしの状態で測定してみます。

**Comment by Shougo** [comment]
この問題は本体のバグと言えるかは微妙ですが、個人的にはfoldmethod=syntax, foldmethod=exprが使い物にならないくらいのインパクトがあります。

**Comment by mattn** [comment]
neoなんたら専用のissuesでないので、出来ればneoなんたらと絡めない状態で報告いただきたいです。

**Comment by Shougo** [comment]
現在設定を最小化して実験しているんですが、この状態では再現できないですね。
自分のプラグインや設定が影響を与えているのかもしれません。

**Comment by Shougo** [comment]
設定を最小化して再現できました。以下のファイルの編集時に、1文字の入力あたり0.85秒かかります。
私の設定時よりもかかる時間は減っていますが、異様に時間がかかることに変わりありません。

https://gist.github.com/Shougo/5334465

$ gvim -u test.vimrc -U NONE -i NONE --noplugin neocomplcache.vim

**Comment by mattn** [comment]
再現スクリプト、もうすこしなんとかなりませんか

**Comment by koron** [comment]
だいたい、自動更新される系の `foldmethod` なんて遅くなることがわかりきってるので、正直使おうとは思わない。

**Comment by thinca** [comment]
> だいたい、自動更新される系の `foldmethod` なんて遅くなることがわかりきってるので、正直使おうとは思わない。

それは個人の感想で本件とは関係ない気が。

**Comment by Shougo** [comment]
> 再現スクリプト、もうすこしなんとかなりませんか

gistの.vimrcを減らしました。多分これが最小のはず。

> だいたい、自動更新される系の foldmethod なんて遅くなることがわかりきってるので、正直使おうとは思わない。

確かに現在の仕様だと個人的には使いませんが、オーバーヘッドが（ほとんど）なしに使えるなら便利です。
重要なのはオーバーヘッドを改善できるかどうかではないかと。

**Comment by mattn** [comment]
> gistの.vimrcを減らしました。多分これが最小のはず。

いえ逆の方です。原因がネオコンかどうかを調べる為に、ネオコンを切り離した状態にしてもらいたいのです。

**Comment by Shougo** [comment]
> gvim -u test.vimrc -U NONE -i NONE --noplugin neocomplcache.vim

下で実行しているので、neocomplcacheは関係がありません。プラグインも最小限しか読み込んでいません。
今回の問題は、巨大なファイルでオーバーヘッドが大きいため、それをわかりやすくするためにneocomplcacheのソースコードを編集して確かめているだけです。

**Comment by mattn** [comment]
gistにあるneocomplcache.vimが再現確認にはデカすぎるという意味です。こんなにいらないはずです。

**Comment by mattn** [comment]
何度も言いますが、ここはネオなんたら専用のissuesじゃないのでネオなんたらで困った事があった場合にそのまま持ってこられると困るのです。多少は許容しますが、このパターンがShougoさん多すぎる。

**Comment by thinca** [comment]
この `neocomplcache.vim` は、編集対象としてのファイルで、実行対象ではないですね。別にどのファイルでもいいと思います。単に大きめのファイルじゃないと速度面の問題が出にくいからこのファイルにしたんじゃないでしょうか。ちょっと紛らわしいですが。

**Comment by Shougo** [comment]
> gistにあるneocomplcache.vimが再現確認にはデカすぎるという意味です。こんなにいらないはずです。

再現するための（巨大な）入力ファイルは必要です。neocomplcache.vimである必要はないですが。
体験上、数千行以上のファイルでないとオーバーヘッドの実感ができないためです。

> この neocomplcache.vim は、編集対象としてのファイルで、実行対象ではないですね。別にどのファイルでもいいと思います。単に大きめのファイルじゃないと速度面の問題が出にくいからこのファイルにしたんじゃないでしょうか。ちょっと紛らわしいですが。

私が持っているfiletype=vimなファイルで巨大だったのがたまたまneocomplcache.vimであっただけでこの問題はneocomplcacheとは関係がありません。

> 何度も言いますが、ここはネオなんたら専用のissuesじゃないのでネオなんたらで困った事があった場合にそのまま持ってこられると困るのです。多少は許容しますが、このパターンがShougoさん多すぎる。

はい。今回の問題はneocomplcacheでなくても発現したのでここに立てました。
確かに流れとしてはわかりにくかったかと思います。再現環境をもう少し整えてから立てるべきでした。

**Comment by mattn** [comment]
> 私が持っているfiletype=vimなファイルで巨大だったのがたまたまneocomplcache.vimであっただけでこの問題はneocomplcacheとは関係がありません。

間違えたの僕やけど紛らわしいw

ちなみに確認しましたが、再現しませんでした。

**Comment by Shougo** [comment]
再現手順を書きます。

1: `37G`で37行目に移動
2: `o`でInsert modeに入る
3: `(`を入力する
4: その状態で、任意の文字列を入力する

これで再現するはずです。

**Comment by mattn** [comment]
最初に書いてw

**Comment by mattn** [comment]
私の環境では、少しもっさりはしますが気になる程ではないです。Shougoさんと同程度のスペックです。
ちなみに気になると言ったのは、1文字0.1秒もかかってない体感という意味です。

**Comment by thinca** [comment]
私の所では再現しました。体感で1文字入力するのに1,2秒くらいかかってますね。

**Comment by mattn** [comment]
linux?

**Comment by thinca** [comment]
一応環境を。
OS: Gentoo Linux 64bit
Vim: 7.3.884 CUI
CPU: Intel(R) Core(TM)2 Duo CPU     E7400  @ 2.80GHz
メモリ: 4GB(空きは十分にあり)

**Comment by mattn** [comment]
んー僕が windows なので linux 依存なのかな

**Comment by koron** [comment]
> それは個人の感想で本件とは関係ない気が。

vimのfoldmethodの実装を知る者の感想ですw

**Comment by Shougo** [comment]
> 最初に書いてw

失敬。忘れていました。

> 私の環境では、少しもっさりはしますが気になる程ではないです。Shougoさんと同程度のスペックです。
> ちなみに気になると言ったのは、1文字0.1秒もかかってない体感という意味です。

うーん、Windowsでは問題にならないんですかね。
Vimのバージョンはいくつでしょうか。

ちなみに私が試したのはGVimです。thincaさんの結果のように、CUI Vimではより遅そうです。

> 実装を知る者の感想ですw

!?

**Comment by thinca** [comment]
Windows でもだいたい同じ感じの結果でした。
OS: Windows 7 Home Premium SP1 64bit
Vim: 7.3.854 GUI
CPU: Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz
メモリ: 8GB

**Comment by Shougo** [comment]
もしかすると、syntax/vim.vimが古くてfoldmethod=syntaxが使われていないのかもしれません。

**Comment by thinca** [comment]
実装を知らない者の感想ですが、挿入モード時には fold の更新処理を行わないようにすればかなり改善されそうな気がします。

**Comment by mattn** [comment]
> Vimのバージョンはいくつでしょうか。

最新、パッチなしです。

**Comment by koron** [comment]
> 実装を知らない者の感想ですが、挿入モード時には fold の更新処理を行わないようにすればかなり改善されそうな気がします。

知って&直してw

その方法なら fold の更新処理の前に `if` 文いれてガードするだけでできそう。
オプション化すれば受け入れられる気がする。

**Comment by mattn** [comment]
foldmethodもsyntaxだし、thincaさんの環境より低いスペックだけど再現しないな。

**Comment by thinca** [comment]
@mattn fold 自体は生成されてますか? `:set foldcolumn=2` とかするとわかりやすいかと。

**Comment by Shougo** [comment]
> 最新、パッチなしです。

7.3.884ということでしょうか？
7.3の後半でfiletype=vimのfoldmethod=syntaxが実装されたので、比較的新しいVimでないと再現できません。

> 知って&直してw
> その方法なら fold の更新処理の前に if 文いれてガードするだけでできそう。
> オプション化すれば受け入れられる気がする。

!
それは良さそうですね。

> foldmethodもsyntaxだし、thincaさんの環境より低いスペックだけど再現しないな。

多分fold自体が存在しないのだと思います。

**Comment by k-takata** [comment]
> 1: `37G`で37行目に移動
> 2: `o`でInsert modeに入る
> 3: `(`を入力する
> 4: その状態で、任意の文字列を入力する

その先に、`zR`で折りたたみを広げておいたら再現しました。
Windows7 7.3.875 32bit

**Comment by mattn** [comment]
> 7.3.884ということでしょうか？

私は常に最新です。パッチが出たらなるべく次の日にはビルドします。

> 多分fold自体が存在しないのだと思います。

foldありますよ。

![](http://go-gyazo.appspot.com/6a5f1ef79b2c1755.png)

**Comment by mattn** [comment]
> その先に、zRで折りたたみを広げておいたら再現しました。

それっぽいすね。

@Shougo ちゃんと書いてw

**Comment by thinca** [comment]
たしかに私も `zo` で折りたたみ開いた。37行目に移動とあったので。(折りたたまれてると37行目行けないw)

**Comment by Shougo** [comment]
あ、確かに私も無意識でfoldを開いていたことに気づきませんでした……。
すみません。

**Comment by mattn** [comment]
確かに速度アップはするけど、仕様として期待する動きになってるかは分からない。

``` diff
diff -r a079ef0ce001 src/fold.c
diff -r a079ef0ce001 src/fold.c
--- a/src/fold.c    Sat Apr 06 17:26:26 2013 +0200
+++ b/src/fold.c    Mon Apr 08 18:12:43 2013 +0900
@@ -857,13 +857,14 @@
    ++fp;
     }

-    if (foldmethodIsIndent(wp)
+    if ((State & INSERT) == 0
+       && (foldmethodIsIndent(wp)
        || foldmethodIsExpr(wp)
        || foldmethodIsMarker(wp)
 #ifdef FEAT_DIFF
        || foldmethodIsDiff(wp)
 #endif
-       || foldmethodIsSyntax(wp))
+       || foldmethodIsSyntax(wp)))
     {
    int save_got_int = got_int;

```

**Comment by Shougo** [comment]
!

**Comment by Shougo** [comment]
とりあえずこの状態でパッチを出してみて、なにか言われたらオプションにすることを検討してみるのはどうでしょう。
私にはinsert mode中でfoldを更新する明確な理由が思いつきません。

**Comment by mattn** [comment]
<del>矢印キーで下を押せばfoldが展開される動作を期待してるんじゃないですかね</del>

ちょっとソースみないと分からない

**Comment by mattn** [comment]
以下、ソースから読めるありえる可能性(逐次更新)
- インサートモードでマーカーを消したらfold更新が必要
- インサートモードでマーカーを書いたらfold更新が必要
- インサートモードでfoldlevelが変わる様な動作をしたらfoldの更新が必要

**Comment by mattn** [comment]
↑こんなところかな

**Comment by mattn** [comment]
> とりあえずこの状態でパッチを出してみて

気が早すぎる

**Comment by Shougo** [comment]
私は「とりあえず出す」という気が早い人間なので……。
Bram氏に直接聞いてみたほうが早い気もしますし。

> インサートモードでマーカーを消したらfold更新が必要
> インサートモードでマーカーを書いたらfold更新が必要
> インサートモードでfoldlevelが変わる様な動作をしたらfoldの更新が必要

markerの場合は処理コストも少ないので、insert mode中で更新するようにしても良いかと思います。
ただ、exprやsyntaxは処理コストが大きいのでinsert mode中に毎回評価されると重過ぎます。
indentについてはどうするべきなのかちょっとわかりません……。

**Comment by mattn** [comment]
37Gzo で s:initialize_script_variables を開いた状態で ( をタイプすると s:initialize_autocmds の fold が開く動作を期待しているので、今回のパッチは仕様をまげる事になる。

**Comment by thinca** [comment]
挿入モード時に編集している箇所の折りたたみは決して閉じられることはないので、挿入モードを抜けた時に更新されれば十分な気はします。

**Comment by mattn** [comment]
> 挿入モード時に編集している箇所の折りたたみは決して閉じられることはないので、挿入モードを抜けた時に更新されれば十分な気はします。

閉じられる話よりは、現在行より下方向で、自動で開かれる動作をどうするかですね。

**Comment by thinca** [comment]
> s:initialize_script_variables を開いた状態で ( をタイプすると s:initialize_autocmds の fold が開く動作を期待している

これはどの仕様のことを指していますか?

**Comment by mattn** [comment]
> これはどの仕様のことを指していますか?

どのOSSでもある話ですが、docに書かれてなければ、現状(ソース)が仕様ですかね。
foldMarkAdjustRecurse がモードを見ていて、foldUpdateIEMS が見てないとすれば意図的な可能性もあるかと思います。

**Comment by mattn** [comment]
> どのOSSでもある話ですが、docに書かれてなければ、現状(ソース)が仕様ですかね。

なのでこれを vim-dev に出すならば RFC として出すのが良いかと思います。

**Comment by Shougo** [comment]
はい。現在の仕様だとどういう場合に問題になるかを挙げ、vim_devの人たちとより良い仕様を検討できれば良いと思っています。
今回のpatchは参考情報として投げる形で。

**Comment by mattn** [comment]
もうちょっと他の人の意見が聞きたい。

**Comment by ynkdir** [comment]
vim だけなら syntax を直すという選択も
c とかでも遅くなるんですかね

``` diff
diff -r a079ef0ce001 runtime/syntax/vim.vim
--- a/runtime/syntax/vim.vim    Sat Apr 06 17:26:26 2013 +0200
+++ b/runtime/syntax/vim.vim    Mon Apr 08 20:27:00 2013 +0900
@@ -152,7 +152,7 @@
 syn cluster    vimOperGroup    contains=vimEnvvar,vimFunc,vimFuncVar,vimOper,vimOperParen,vimNumber,vimString,vimRegister,vimContinue
 syn match  vimOper "\(==\|!=\|>=\|<=\|=\~\|!\~\|>\|<\|=\)[?#]\{0,2}"   skipwhite nextgroup=vimString,vimSpecFile
 syn match  vimOper "||\|&&\|[-+.]" skipwhite nextgroup=vimString,vimSpecFile
-syn region vimOperParen    matchgroup=vimParenSep  start="(" end=")" contains=@vimOperGroup
+syn region vimOperParen    matchgroup=vimParenSep  start="(" end=")" contains=@vimOperGroup oneline
 syn region vimOperParen    matchgroup=vimSep   start="{" end="}" contains=@vimOperGroup nextgroup=vimVar,vimFuncVar
 if !exists("g:vimsyn_noerror") && !exists("g:vimsyn_noopererror")
  syn match vimOperError    ")"
```

この修正じゃだめでしょうけど。

``` vim
" COMBAK: vimOperParen used to have "oneline"
```

むかしは oneline だったようです。

どちらで変更されたのかわかりませんがどちらか
[Syntax highlighting problem with vim scripts]
https://groups.google.com/d/msg/vim_dev/rmKpkkhzn6E/ac9z0EtM_JIJ
[some vim syntax fixes for multi-lined commands]
https://groups.google.com/d/msg/vim_dev/j0CnXTtipw4/sA6Ac-3dAvYJ

**Comment by ynkdir** [comment]
あとはペーストやアンドゥも遅くなるのでインサートモードだけの対処でよいのかなど

**Comment by mattn** [comment]
ですね。いっそ !KeyTyped でいいのかも。

**Comment by mattn** [comment]
そもそも foldUpdate の呼び出し位置を再考すべきなんかもしれないですね。

**Comment by ynkdir** [comment]
> 閉じられる話よりは、現在行より下方向で、自動で開かれる動作をどうするかですね。

これはsyntax更新で折畳みが変わって `function! s:initialize_script_variables()` 以下が全部一つの折畳みになるための動作なので問題ない気がします。

**Comment by ynkdir** [comment]
整形の話

todo.txt: Patch to make fold updates much faster. (Christian Brabandt, 2012 Dec)

[Re: Fold expression called too often]
https://groups.google.com/d/msg/vim_dev/pBS8-8TA55c/7Qc0U4LMjt8J

**Comment by mattn** [comment]
misc1.c のパッチって事はノーマルモード時ですな

**Comment by mattn** [comment]
もしかしてINSERTモード時のfoldUpdateは後から入れたんかな？

**Comment by ynkdir** [comment]
メーリングリストでこの話題がでると FAQ が参照されます。

[FAQ: 29.7. I have enabled syntax based folding. Why is Vim so slow?]
https://vimhelp.appspot.com/vim_faq.txt.html#faq-29.7

C は syntax で対処したみたいです。

[C syntax highlighting, faster syntax based folding and a bug]
https://groups.google.com/d/msg/vim_dev/dwUfdn1-SKU/eqBjqutgfEQJ

スルーされる Christian Brabandt
https://groups.google.com/d/msg/vim_dev/AuIwMfsQ75U/-klaGjkMjEQJ

**Comment by koron** [comment]
> スルーされる Christian Brabandt

www

**Comment by mattn** [comment]
提案してもいいかもですね　＞ vim自身でのfold更新抑制

**Comment by ynkdir** [comment]
あーやっぱりsyntaxで対処は無理っぽいです
入力中の中途半端なテキストだけで発生すると思ってましたが単純に

``` vim
function F()
  ... 1000行
endfunction
```

とかでも遅くなりますね

**Comment by mattn** [comment]
で、どうしましょうか。vim-jpとして「カレント行に対する変更」(ここどうするか議論が必要)だけであれば、全体のfoldを展開する様な動作(foldUpdate)は行わないと主張するかどうか。

**Comment by ynkdir** [comment]
個人的には FAQ 的な案でいいかなと思います。
autocmd でインサートモードのときだけ無効化してもらうか
適当なタイミングで `:set foldmethod=syntax | redraw | set foldmethod=manual` で更新してもらうか

**Comment by mattn** [comment]
Windowsな人は

```
vim -c ^"call feedkeys(repeat(""":so foo.vim\<CR>""", 10000))^"
```

**Comment by ynkdir** [comment]
もしかしたらソースの方で改善の余地もあるかもしれないですね
例えば syntax.c:syntax_start() は一文字入力するごとに同じ行に対して何回も呼ばれてますし
しかし syntax.c むずかしいです...

**Comment by mattn** [comment]
できれば手を出したくないところですね苦笑

**Comment by Shougo** [comment]
https://github.com/vim/vim/blob/4575876dc865d4160f20d61bd822fbe7cafbec41/runtime/doc/todo.txt#L219

パッチ送付済み、既に todo リスト入りしているので閉じます。
