### ISSUE TITLE
if_luaでVimが落ちるらしい？（一度凍結）

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#351]
https://twitter.com/Mi_Sawa/status/321304823892942848

> vimからlua呼び出すやつ, 辞書に関数への参照が入ってたりすると, invalid type とかで死ぬのは僕だけですか?

これはif_luaのバグのような気がします。再現スクリプトを書いていないので、私の環境ではまだ未確認。

**Comment by thinca** [comment]
Linux 環境で試したところ、Funcref が入っていたところには nil が入っていますが、落ちたりはしないですね。
# 関係ないけど、Func ユーザーデータとかあると便利そう。

**Comment by Shougo** [comment]
https://twitter.com/Mi_Sawa/status/321310617854164992

> @ShougoMatsu uniteのlua部で,candidateに関数が登録されているとinvalid typeで落ちてしまいます.また,配列が1-baseっぽくて,#a-1,0,-1じゃなくて#a,1,-1にしなければならないっぽいです.お暇な時に対処頂けると嬉しいです.

https://twitter.com/Mi_Sawa/status/321314170752598017

> @ShougoMatsu 申し訳ないです, 先ほどのリプライですが, help luaを見る限り, 僕の環境がおかしいっぽいです.

どうやら、unite.vimで使用しているif_luaで再現するようです。
が、私の環境ではまだ確認できていません。

**Comment by Shougo** [comment]
※：これとは別に、if_luaの挙動はなんか怪しい気がしていて、SEGVが頻発しているので今度SEGVしたら原因を調べようかと思っています。

**Comment by Shougo** [comment]
> Linux 環境で試したところ、Funcref が入っていたところには nil が入っていますが、落ちたりはしないですね。

これ、Vim scriptの方に戻ったときは復元されるんでしょうか。

**Comment by mattn** [comment]
落ちないね。

**Comment by Shougo** [comment]
じゃあ環境の問題ですかね。私もそのエラーは起こった事無いです。原因不明のSEGVはあるんですが。

https://twitter.com/Mi_Sawa/status/321306669541912576

> あとluaの配列は1-baseっぽいんだけど, 配列と連想配列的なのが混同されてる感じで, そのサイズがよくわからん事になってる気がする.

if_luaの配列の挙動は確かに私もよくわかっていません。

**Comment by mattn** [comment]
挙動というか、仕様です。luaの配列(テーブル)は1-baseです。

**Comment by Shougo** [comment]
> 挙動というか、仕様です。luaの配列(テーブル)は1-baseです。

いや、本来のLuaの配列はそうなんですが

if_luaのVim scriptから取ってきたリストの場合は0 originです。

```
o "#l" is the number of items in list "l", equivalent to "len(l)"
    in Vim.
o "l[k]" returns the k-th item in "l"; "l" is zero-indexed, as in Vim.
    To modify the k-th item, simply do "l[k] = newitem"; in
    particular, "l[k] = nil" removes the k-th item from "l".
o "l()" returns an iterator for "l".
```

**Comment by h-east** [comment]
今日のお昼は 1オリジン弁当に決定:smile:

**Comment by Shougo** [comment]
0-originと1-originが混ざるので、かえって混乱する仕様の気はしなくもないです。

**Comment by h-east** [comment]
このissueは「憶測」と「願望」の比率が高過ぎません？
問題報告者の環境(OS, Vim Ver, ...)と問題再現コード＆手順が提示されていないし、
報告者以外がunite.vimで再現出来ていないので、原因がプラグインかVim本体かの切り分けが出来ていない。
こんな状態でissue立てられてもみんなが時間を浪費するだけ。※エスパーを除く

「完璧に再現手順を確立して切り分け出来てからissue立てろや(ﾟДﾟ)ｺﾞﾙｧ!!」とまでは言わないけど、もう少し情報を整理してからでいいんじゃなかなと思った。

**Comment by Shougo** [comment]
はい。ちょっとここの問題は一度凍結します。
それとは別に、私の環境でSEGVが発生したので（多分if_lua？）、それは別のIssueを立てておきます。

**Comment by koron** [comment]
本題関係ないけど、Luaは0 originな配列も扱えますよ。なので1 originは仕様ではなく(かなり強い)慣習ですね。
文字列のインデックスが1 originでそれに合わせるとか、そんな感じかもです。
さらになんで1 origin推奨かというと

[Why do Lua arrays(tables) start at 1 instead of 0?](http://stackoverflow.com/questions/2785704/why-do-lua-arraystables-start-at-1-instead-of-0)

> People not trained in computing think it is damned weird to start counting at zero.

らしいです。

**Comment by Shougo** [comment]
unite.vimにおいて、Variable type mismatchエラーが発生することを確認しました。
該当するsourceはfile_mruです。ただ、neocomplcacheのデバッグ中に発生したため、これが今回報告されたエラーなのか
わかっていません。もう少し調べる必要があります。

**Comment by Shougo** [comment]
これ、メモリ破壊が原因のような気がしますね……。他のエラーも頻発し、Vimの動作全体がおかしくなっているように見えます。一度閉じて、SEGV問題と一緒に議論します。

**Comment by koron** [comment]
# 切り分けるのが定石じゃないか?

**Comment by Shougo** [comment]
> # 切り分けるのが定石じゃないか?

できることなら切り分けたいんですが……。まずはif_luaのSEGVをどうにかしないと現状ではどうにもならないですね。

**Comment by Shougo** [comment]
とりあえず、さっき出ていたエラーのメモを残しておきます。

file_mruのon_post_filter()で型が合わないエラー。
post filterはif_luaのフィルタが呼ばれたあとに呼ばれるので、Vim script-> lua -> Vim scriptで型情報が壊れている？

**Comment by koron** [comment]
せっかく小さくしといたのに h1 にされたw

**Comment by Shougo** [comment]
あちらの問題は修正してみたので、こっちも様子見状態です。

**Comment by h-east** [comment]
> まずはif_luaのSEGVをどうにかしないと現状ではどうにもならないですね。

考え方間違ってる。順番が逆。
不具合を直す為に切り分けをするんだよ。

**Comment by Shougo** [comment]
少なくとも今回の問題は、unite.vimをif_lua化するまでは見ていないです。
更に、エラーが起こっている場所がif_luaの処理が走った後の変数に対する処理であるため、if_luaが原因である可能性は高いように見えます。
#351が#352 と同じ原因かどうかは #352 を対処してみて、 #351が発生しなくなるかどうかで判断すれば良いと思うのですがどうでしょうか。

**Comment by koron** [comment]
unite.vim で発生している問題のissueはその原因がどこにあるにせよ unite.vim で管理したら?
いろんなことがごっちゃ混ぜになっていて非常によろしくない。
当事者の @Shougo さんには全部見えているのかもしれないですが、
他の人達には単品で見えているのでそのあたりを考えた議論をお願いします。

#352 はvimの問題として程よく切りだされているので良いと思います。

**Comment by Shougo** [comment]
はい。ごっちゃになっていたので一度closeしました。
とりあえず、この問題自体は再現したらunite.vimで議論しようかと思います。

**Comment by Shougo** [comment]
問題を忘れないように、unite.vim側にIssueを立てました。

**Comment by koron** [comment]
[この基準](https://github.com/vim-jp/issues/wiki/Member#%E3%82%BF%E3%82%B0%E3%81%AE%E4%BB%98%E3%81%91%E6%96%B9) に基づいて
invalid というよりは worksforme だろう、と判断してタグを変更しました。
