### ISSUE TITLE
Ubuntu 13.04でPython3のconfigディレクトリを見つけられない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#353]
https://github.com/vim-jp/vim-jp.github.com/issues/56#issuecomment-16153351 より

Ubuntu 13.04ではPython3のconfigディレクトリの位置が変更になったらしく、configureスクリプトがそのディレクトリを見つけられないようです。`--with-python3-config-dir` を指定すればコンパイルはできますが、configureを修正した方がよいだろうと思います。

Python3のconfigディレクトリは以下のコマンドで取得できるようですので、configureの中でまずこのコマンドを実行し、ダメだったら従来のルーチンに飛ばすようにした方がよいのではないかと思います。

``` sh
$ python3 -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('LIBPL'))"
```

**Comment by mattn** [comment]
++

**Comment by k-takata** [comment]
@Shougo 上記のコマンドで、Python3のconfigディレクトリが正しく取得できるか確認していただけませんか？

**Comment by k-takata** [comment]
こんな感じ？（動作未確認ｗ）
Python2 の方も対応した方がいいのでしょうか？
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/925da100d651c682f022d3b2f5de9c8d33f2dd3f/python3-config-dir.patch

**Comment by Shougo** [comment]
> @Shougo 上記のコマンドで、Python3のconfigディレクトリが正しく取得できるか確認していただけませんか？

はい。OKです。

Python2はこれでOKでした。

`python -c "import distutils.sysconfig; print distutils.sysconfig.get_config_var('LIBPL')"`

**Comment by k-takata** [comment]
Python2 も対応。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/ca4e140d578de2d9f190a0c731e53a5e3a03fe3a/python-config-dir.patch

**Comment by Shougo** [comment]
ありがとうございます。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/_5vNGhPbPzc/discussion

**Comment by k-takata** [comment]
todo.txt入りしました。

> Configure doesn't find Python 3 on Ubuntu 13.04. (Ken Takata, Apr 13)

**Comment by h-east** [comment]
Patch 7.3.1101 で取り込まれました。GJ！
https://groups.google.com/d/msg/vim_dev/zghHy2bWK1o/MvD_Bwr8DW4J
