### ISSUE TITLE
Linuxで+lua/dyn時に正しいライブラリ名が取得できない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#354]
元ネタ: [fedora17 で +lua/dyn なvimをビルドする - h_east’s blog](http://d.hatena.ne.jp/h_east/20130409/p1)

Ubuntu 12.04 64bit でも試してみましたが、本来のライブラリ名が liblua5.1.so.0 のところが liblua.so.5.1 になってしまっていました。

問題は2点ありました。
1. /usr/lib/ にあるライブラリを探そうとしているが、/usr/lib64/ や /usr/lib/x86_64-linux-gnu/ にある場合がある。
2. ライブラリが見つかったときに、2重forループの内側のみbreakで抜けており、もう一度外側のループを回って変数が上書きされる場合がある。

とりあえず修正案です。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/73f8b9ac2485b82bf8dc9c0f26ed0fa7dbc692e7/linux-lua-dyn.patch

# x86_64-linux-gnu というディレクトリ名を configure スクリプトに直接書いているところは何とかしたい。

**Comment by k-takata** [comment]
@h-east よく見ると、Fedoraの方のライブラリ名は liblua5.1.so ではなく liblua-5.1.so ですか？

**Comment by h-east** [comment]
はい、liblua-5.1.so です。

**Comment by k-takata** [comment]
となると、一番外側の for ループは

``` sh
    for LUA_SOVER in "${vi_cv_version_lua}.so" "-${vi_cv_version_lua}.so" ".so.${vi_cv_version_lua}"; do
      ～
    done
```

にでもした方がいいんですかね？

**Comment by h-east** [comment]
GJ! 。これでメジャーどころのディストリは網羅出来ているのかな？

あとちょっと話それますが...
今って64bit Linux で 32bit Vim作れるんでしたっけ？
ふと思ったんですけど 64bit Linuxのライブラリは  /usr/lib/ が32bitで、 /usr/lib64/ か /usr/lib/x86_64-linux-gnu/ が64bit だとすると
64bit Vimビルド時に /usr/lib/ を参照したら問題が出るケースがあるんじゃないでしょうか？
(32bitライブラリはあるけど 64bitライブラリは無いケース ←超レアケースw)

**Comment by h-east** [comment]
あぅ、説明グダグダになっちゃったw
64bit Linux で32bit/64bit Vimビルドちゃんとごちゃ混ぜにならずに出来るの？ってことを気にしました。

**Comment by k-takata** [comment]
今回の .so のファイル名って /dyn の場合だけ必要ですし、/dyn であればヘッダファイルさえあればビルドは通るはずなので、.so はファイル名さえ合っていれば中身はどうでもいいのではないかという疑惑。

liblua-{ver}.so に対応したはず:
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/0734a9db14a34659942fe82b28de74efeedcf9d5/linux-lua-dyn.patch

**Comment by k-takata** [comment]
> # x86_64-linux-gnu というディレクトリ名を configure スクリプトに直接書いているところは何とかしたい。

`dpkg-architecture -qDEB_HOST_MULTIARCH` で取得できるっぽいですね。

**Comment by k-takata** [comment]
こんな感じでどうでしょう。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/6a178c266161ad3433c799fe6d3227bbcb33ee87/linux-lua-dyn.patch

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/hiFuJPOoNb0/discussion
（Fedoraに言及しながら、テストしたリストにFedoraが載ってないけど…）

**Comment by h-east** [comment]
あっ、しまった
昨日patchあてて動かしたけどfedoraでは思てたんと違う結果になったのでデバッグしてたんすけど、
飲みに行って帰ってきてそのまま寝ちゃったw
せめてここにコメントすればよかったですね。
デバッグ完了後にpatch貼ります。

**Comment by k-takata** [comment]
ありゃ。

**Comment by h-east** [comment]
@k-takata ちょっと教えてください。
src/configure.in を変更したら
`make autoconf; make` が正解ですか？

**Comment by koron** [comment]
あれ? それどこかに書いてなかったっけ?

**Comment by h-east** [comment]
@koron http://vim-jp.org/docs/build_linux.html には書いてなかった。どこだろう...

普通に
$ autoconf
ってやったら configure がなんかよくわからん中途半端な感じになったので
$ make autoconf
が正解なのかなぁとおもた。

**Comment by koron** [comment]
@h-east あったあった。 https://github.com/vim-jp/issues/issues/280#issuecomment-11492842

**Comment by h-east** [comment]
@koron Thanks!

**Comment by k-takata** [comment]
make config, make reconfig, make autoconf 辺りは Makefile の中には書いてありますが、それ以外ではあまりちゃんと説明しているところはないですね。
make autoconf は、パッチの書き方のページに補足として入れるのがいいですかね？

**Comment by h-east** [comment]
@k-takata 賛成です。

あと、お待ちかねのfedoraもOKなpatchです。チェックお願いします。

``` diff
diff -r a079ef0ce001 src/configure.in
--- a/src/configure.in  Sat Apr 06 17:26:26 2013 +0200
+++ b/src/configure.in  Sat Apr 13 12:32:00 2013 +0900
@@ -494,17 +494,26 @@
       if test -f "${vi_cv_path_lua_pfx}/bin/cyglua-${vi_cv_version_lua}.dll"; then
    vi_cv_dll_name_lua="cyglua-${vi_cv_version_lua}.dll"
       else
-   dnl Determine the SONAME for the current version, but fallback to
-   dnl liblua${vi_cv_version_lua}.so if no SONAME-versioned file is found.
-   for LUA_SOVER in "${vi_cv_version_lua}.so" ".so.${vi_cv_version_lua}"; do
-     for i in 0 1 2 3 4 5 6 7 8 9; do
-       if test -f "${vi_cv_path_lua_pfx}/lib/liblua${LUA_SOVER}.$i"; then
-         LUA_SONAME=".$i"
-         break
-       fi
+   multiarch=`dpkg-architecture -qDEB_HOST_MULTIARCH 2> /dev/null`
+   if test "X$multiarch" != "X"; then
+     lib_multiarch="lib/${multiarch}"
+   fi
+   dnl Determine the sover for the current version, but fallback to
+   dnl liblua${vi_cv_version_lua}.so if no sover-versioned file is found.
+   for subdir in ${lib_multiarch} lib64 lib; do
+     if test -z "$subdir"; then
+       continue
+     fi
+     for sover in "${vi_cv_version_lua}.so" "-${vi_cv_version_lua}.so" ".so.${vi_cv_version_lua}"; do
+       for i in .0 .1 .2 .3 .4 .5 .6 .7 .8 .9 ""; do
+         if test -f "${vi_cv_path_lua_pfx}/${subdir}/liblua${sover}$i"; then
+       sover2="$i"
+       break 3
+         fi
+       done
      done
-     vi_cv_dll_name_lua="liblua${LUA_SOVER}$LUA_SONAME"
    done
+   vi_cv_dll_name_lua="liblua${sover}$sover2"
       fi
       AC_DEFINE(DYNAMIC_LUA)
       LUA_LIBS=""
```

前提条件というか既知の事実
- luaの共有ライブラリ名<br>fedora17は`liblua-5.1.so`<br>Ubuntu 12.04は`liblua5.1.so.0`。
- `dpkg-architecture`コマンドがあるのはDebian系だけ？

修正ポイント
- ループの順番を`if test -f "${vi_cv_path_lua_pfx}/${subdir}/liblua${sover}$i"; then`での出現順に並び替えた。
- `${lib_multiarch}` が "" の場合のsubdirループで余計な処理をしないようにした。
- fedora17の場合ライブラリ名にはminor番号 `.0等` が付いていないので `for i in .0 .1 .2 .3 .4 .5 .6 .7 .8 .9 ""; do` でそれを考慮。
- ループ変数が大文字なのを小文字に変更。(なんとなく)

@k-takata 気に入らんところあれば好きに変えちゃって下さい。

**Comment by k-takata** [comment]
> - `${lib_multiarch}` が "" の場合のsubdirループで余計な処理をしないようにした。

`for`のリストに`${lib_multiarch}`を`""`でくくらずに書いていたので、余計な処理は起こらないと思っていたのですが、違いましたか？ まあ、リストの部分もくくっておいて、ループの中で空文字かどうかチェックする方が安全そうですね。

> - fedora17の場合ライブラリ名にはminor番号 `.0等` が付いていないので 

見落としてました。

更新版です。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/2d785b8b2a4920026dafb5e3ecdb6d8fc79fffc6/linux-lua-dyn.patch

**Comment by k-takata** [comment]
再度投げました。
https://groups.google.com/d/msg/vim_dev/hiFuJPOoNb0/zLU7LfZbNrcJ

**Comment by h-east** [comment]
> forのリストに${lib_multiarch}を""でくくらずに書いていたので、余計な処理は起こらないと思っていたのですが、違いましたか？

あっ、そこまでは動作確認してないです。コード見て「ん？」と思ったので回避処理追加しちゃいました。
(そんな暗黙のテクニックがあったとは...勉強になった)

> 再度投げました。

おつです。

**Comment by k-takata** [comment]
7.3.897 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/lxi_Dr--xT0/discussion

**Comment by h-east** [comment]
@k-takata :+1: 
後で私のブログ記事に補足文章足します。→Done.
