### ISSUE TITLE
ラーメン画像を貼るスレ

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#355]
LuaJIT はライブラリファイル名が libluajit-X.X.so なので
ライブラリを見つけられないほかdynでもリンクできていません。

configureを直してしまいたい。

**Comment by k-takata** [comment]
お、重複？ #348

**Comment by koron** [comment]
ｻｰｾﾝ ボケてた。

**Comment by koron** [comment]
以後このスレはラーメン画像を貼るスレとします。

**Comment by Shougo** [comment]
!?

**Comment by koron** [comment]
[冨白](http://ramendb.supleks.jp/s/54909.html) の鳥豚タンメン+味玉850円

![IMG_20130411_120018](https://f.cloud.github.com/assets/468368/365733/6bede4b0-a258-11e2-9982-d91d62cbbb9a.JPG)

**Comment by heavenshell** [comment]
尾道の壱番館の角煮ラーメン 890 円
![尾道の壱番館](https://pbs.twimg.com/media/BHeFFumCIAAju-e.jpg)

**Comment by Shougo** [comment]
Lua, Lua, Lua, Lua, Lua麺, Lua麺, ラーメンということですか？

**Comment by koron** [comment]
[つしま](http://ramendb.supleks.jp/s/1415.html)

![14 - 2](https://f.cloud.github.com/assets/468368/365780/fde86748-a25b-11e2-8b63-62a3f2ea34e5.jpg)

**Comment by koron** [comment]
[支那そば 亀戸ラーメン](http://ramendb.supleks.jp/s/63638.html)

![19 - 2](https://f.cloud.github.com/assets/468368/365783/37189812-a25c-11e2-8a5b-ab6569103dd3.jpg)

**Comment by koron** [comment]
あれ? これどこだっけ?

---

[雷 本店](http://ramendb.supleks.jp/s/22754.html)だったw

![21 - 2](https://f.cloud.github.com/assets/468368/365789/6ddc3930-a25c-11e2-8d23-24dbf6f3f9d1.jpg)

**Comment by koron** [comment]
[青島食堂](http://ramendb.supleks.jp/s/21725.html)

![24 - 1](https://f.cloud.github.com/assets/468368/365790/7d9d0e26-a25c-11e2-8407-5188a895cee8.jpg)

**Comment by h-east** [comment]
揚子江ラーメン
![image](https://f.cloud.github.com/assets/518808/365848/dd66b1cc-a261-11e2-9f55-5ab821169c70.jpg)
ようすこ！

**Comment by koron** [comment]
@h-east この写真、逆さじゃね?w

**Comment by h-east** [comment]
そういう器なんですよ！。(Bad往生際)

**Comment by koron** [comment]
レンゲが空中に刺さってるよ!w

**Comment by koron** [comment]
[饗 くろ㐂](http://ramendb.supleks.jp/s/34438.html) 特製みそラーメン

![IMG_20130403_133820](https://f.cloud.github.com/assets/468368/366129/4ccd7462-a274-11e2-89b4-bce615076f20.JPG)

**Comment by mattn** [comment]
:ramen:

**Comment by noriprince** [comment]
ラーメン凪 at 新宿ゴールデン街
![2014-06-12 01 50 23](https://cloud.githubusercontent.com/assets/7898908/3283583/32bfc36e-f51a-11e3-9699-61854712280a.jpg)

**Comment by todashuta** [comment]
山頭火 旭川醤油らーめん

![photo sep 06 5 12 26 pm](https://cloud.githubusercontent.com/assets/1555633/4174971/3ffce95e-35b5-11e4-9f2c-4509b6e02c3b.jpg)

**Comment by raa0121** [comment]
[らーめん 吉山商店](http://www.yosiyama-shouten.com/index.php)
![豚骨白湯塩ラーメン](https://cloud.githubusercontent.com/assets/237271/4175187/5e3d8810-35c4-11e4-8fe1-5391c7090544.jpg)

**Comment by callmekohei** [comment]
福岡の玉屋というパチンコ屋さんに入ってるラーメン屋さんのラーメン
かなり美味しい

![img_5423](https://user-images.githubusercontent.com/17691683/42019465-31e30da6-7af0-11e8-898f-294378dd6a3f.jpg)

**Comment by syuilo** [comment]
![bd4a531f-edb9-4be1-8702-cf760d86a442](https://user-images.githubusercontent.com/4439005/43247123-c0f4252a-90ee-11e8-833f-e39268dcd327.jpeg)
丸源

**Comment by revcomm-saito** [comment]
![IMG_2677](https://user-images.githubusercontent.com/110585471/190141550-84cc5529-ec0a-438e-beb9-e85246d5937d.png)

鶏松

**Comment by tomoya** [comment]
10周年おめでとうございます!! 
記念カキコ

![alisue-ramen](https://user-images.githubusercontent.com/18009/232719469-045c403a-e9d6-4732-bca5-12028b9f36e0.jpg)
サッポロ一番みそラーメン（自宅）

**Comment by lambdalisue** [comment]
リアルに CONFUSED ですね

**Comment by gamoutatsumi** [comment]
こんなんあったんだ
先月卒業式の帰りに食べたラーメン
![PXL_20230315_061648473~2.jpg](https://user-images.githubusercontent.com/47162587/232744727-dcc130d1-2747-42ea-a3ce-33b7e4a0fb1c.jpg)

**Comment by takunm** [comment]
山岡家の特製味噌チャーシュー麺
![yamaokaya](https://github.com/vim-jp/issues/assets/130290648/3be72832-94f3-4eb3-b539-8b7ff6118747)

**Comment by hidehiro98** [comment]
野猿二郎
![IMG_6190](https://github.com/user-attachments/assets/34301c7e-401f-459d-8a45-e6927f56c33f)

**Comment by shmokmt** [comment]
![image](https://github.com/user-attachments/assets/8fb4340f-928e-43ca-8862-650f52982727)
大分市にある大黒という店のラーメンです。

**Comment by ObuchiYuki** [comment]
Contributor外から失礼いたします。

趣旨とは少し異なるかもしれませんが、失敗して茶碗蒸しのようになってしまったインスタントラーメンです。

![IMG_6563](https://github.com/user-attachments/assets/f619a37e-5a77-45b8-a5e1-6b588b312567)
![IMG_6567](https://github.com/user-attachments/assets/33802937-033c-486a-a715-ee0313062581)

**Comment by mattn** [comment]
塩元帥
![image](https://github.com/user-attachments/assets/e13aaf61-1960-4d8c-bd0b-cba3656d5f51)

**Comment by Hima-Zinn** [comment]
[光来](https://s.tabelog.com/tokyo/A1304/A130401/13009180/)っていうところのラーメンです。
![image](https://github.com/user-attachments/assets/d26d529e-55a4-4dce-b773-c07f262747fc)

**Comment by mattn** [comment]
麺屋たけ井
![image](https://github.com/user-attachments/assets/4c6acfd8-bd97-4b30-be6f-f6cd72d8abdd)

**Comment by mattn** [comment]
東大に行ってきました
![image](https://github.com/user-attachments/assets/31eed329-f723-4ccf-8151-66db6bbd59fd)

**Comment by XxGodmoonxX** [comment]
![image](https://github.com/user-attachments/assets/1d20da8c-69fa-457a-9309-7e780d374f64)

野方駅にある次男房の鶏白湯ラーメン

**Comment by mattn** [comment]
まこと屋
![image](https://github.com/user-attachments/assets/e130ed35-6bc7-4346-807f-d97cff9f184a)

**Comment by mattn** [comment]
東大にもう1度行ってきました。
![image](https://github.com/user-attachments/assets/d9d8e056-86ab-4e69-9a02-47df7523aaa8)

**Comment by mattn** [comment]
神戸牛らーめん 八坐和
![image](https://github.com/user-attachments/assets/78dfc551-dcc3-49f6-a0f2-5021540063b3)

**Comment by mattn** [comment]
神戸牛らーめん 八坐和 (ローストビーフ付き)
![image](https://github.com/user-attachments/assets/bb2c06c6-786d-465e-b04d-b4623a244c7d)

**Comment by ujihisa** [comment]
VimConf 2024のため来日中に、嫁が東京の神田担々麺・陳麻婆豆腐 雲林坊 という店にいってきました。僕はVimConf参加中だったのと、時間的にラーメンを食べる機会がなかったので、一度も食べられず... 蕎麦は3回食べれたのでよし

https://bsky.app/profile/sandkat.bsky.social/post/3lblrofdx2c2z

![](https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:q4dlzgquqys4fk77u2ejmppg/bafkreief6qm4o5uipndbg4pzpzd3ct23cyujvcbekcv6fkso5dfqwvjpbu@jpeg)

**Comment by shmokmt** [comment]
家系中華蕎麦 家道です。
戸越銀座駅の近くにあります。
<img width="1264" height="1686" alt="Image" src="https://github.com/user-attachments/assets/5363c619-2b20-4a53-82b5-3a7cd39c1fb3" />
