### ISSUE TITLE
getbufvar() で取得した辞書が bwipeout で不正になる

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#357]
```
$ vim -u NONE
:let x = getbufvar(1, '')
:new
:1bwipeout
:echo x
SEGV   (落ちないこともあり)
```

**Comment by ynkdir** [comment]
getwinvar() も同じ。

```
$ vim -u NONE
:let x = getwinvar(1, '')
:new
:wincmd w
:quit
:echo x
```

gettabvar() は辞書取得できませんね。

**Comment by mattn** [comment]
> gettabvar() は辞書取得できませんね。

ん？取れませんか？

```
$ vim -u NONE
:let t:foo = {"bar": "baz"}
:let s:nr = tabpagenr()
:tabnew
:let g:foo = gettabvar(s:nr, "foo")
:exe s:nr "tabmove"
:bw!
:redraw
:echo g:foo
{'bar': 'baz'}
```

繰り返しやったら落ちるかもしれませんが。

**Comment by ynkdir** [comment]
いえ、gettabvar(nr, '') で `t:` が取れないということです。

**Comment by h-east** [comment]
> gettabvar() は辞書取得できませんね。

はい、そういう仕様のようです。

https://github.com/vim-jp/issues/issues/245#issuecomment-11797998 の6行目

**Comment by mattn** [comment]
あ、なるほど。バグですね。

**Comment by mattn** [comment]
> はい、そういう仕様のようです。

mjsk

**Comment by ynkdir** [comment]
あぁこれ getbufvar() とか関係なくて :b :w :t を直接取れば落とせました。

**Comment by ynkdir** [comment]
```
$ vim -u NONE
:let x = [b:, w:, t:]
:tabnew
:1bwipeout
:echo x
```

**Comment by ynkdir** [comment]
関係ないですけど

```
$ vim -u NONE -g
:tabnew
:1bwipeout
```

ですぐにタブが消えないです。。。
L で更新すると消えます。
CUI は大丈夫っぽいです。

**Comment by Shougo** [comment]
> あぁこれ getbufvar() とか関係なくて :b :w :t を直接取れば落とせました。

うぉ、それはひどい……

**Comment by mattn** [comment]
この辺、非常に弱いな。

**Comment by ynkdir** [comment]
報告しました。

https://groups.google.com/d/msg/vim_dev/Sl3Cn8iszxE/osYqlvQtPkQJ

**Comment by mattn** [comment]
乙

**Comment by h-east** [comment]
Patch 7.3.893 で取り込まれました。
https://groups.google.com/d/msg/vim_dev/ASa5wX4Vduo/okijDm3hPoIJ

**Comment by ynkdir** [comment]
thanks!

**Comment by h-east** [comment]
> 関係ないですけど
> 
> $ vim -u NONE -g
> :tabnew
> :1bwipeout
> ですぐにタブが消えないです。。。

vim_devへpatch投稿
https://groups.google.com/d/msg/vim_dev/LfUrevkxtao/r-U0saUNOAQJ

上記の件は Patch 7.3.902 で修正されました。niceです。
https://groups.google.com/d/msg/vim_dev/JcG1efxSLq4/6QCaLWwG7UoJ
