### ISSUE TITLE
コマンド履歴が正常にviminfoに記録されない(7.3.880～)

### ISSUE THREAD

**Issue by DeaR** [vim-jp/issues#358]
> 7.3.880  new viminfo history lines may be replacd with old lines

で仕様が変わった関係なのかviminfoに存在しないコマンドを使用して終了すると記録されずに最古の物が繰り上がってきます
###### 再現方法
1. .vimrc, .viminfo を退避
2. 新規で下記を記述した .vimrc を用意
   
   ``` vim
   set nocompatible
   set history=5
   ```
3. 起動して下記のコマンドをそれぞれ実行
   
   ``` vim
   :echo 1
   :echo 2
   :echo 3
   :echo 4
   :echo 5
   ```
4. `<C-W>q` で終了
5. .viminfo のコマンド履歴が下記の様になっている
   
   ``` vim
   :echo 5
   :echo 4
   :echo 3
   :echo 2
   :echo 1
   ```
6. 起動して下記のコマンドを実行
   
   ``` vim
   :q
   ```
7. .viminfo のコマンド 履歴が下記の様になっている(`:q` が記録されていない)
   
   ``` vim
   :echo 1
   :echo 5
   :echo 4
   :echo 3
   :echo 2
   ```
###### 確認環境
- 7.3.882 x64 +kaoriya (windows7 x64)
  … 再現
- 7.3.880 自己ビルド (windows7 x64)
  … 再現
- 7.3.884 自己ビルド (windows7 x64)
  … 再現
- 7.3.888 自己ビルド (windows7 x64)
  … 再現
- 7.3.888 自己ビルド (ubuntu server 12.04LTS x86)
  … 再現
- 7.3.879 自己ビルド (windows7 x64)
  … 大丈夫

**Comment by h-east** [comment]
@DeaR 報告ありがとうございます。こちらでも再現しました。調べます。

**Comment by mattn** [comment]
むちゃくちゃ丁寧なissue登録有難うございます。

On 4/13/13, DeaR notifications@github.com wrote:

> > 7.3.880  new viminfo history lines may be replacd with old lines
> 
> で仕様が変わった関係なのかviminfoに存在しないコマンドを使用して終了すると記録されずに最古の物が繰り上がってきます
> 
> ###### 再現方法
> 1. .vimrc, .viminfo を退避
> 2. 新規で下記を記述した .vimrc を用意
>    
>    ``` vim
>    set nocompatible
>    set history=5
>    ```
> 3. 起動して下記のコマンドをそれぞれ実行
>    
>    ``` vim
>    :echo 1
>    :echo 2
>    :echo 3
>    :echo 4
>    :echo 5
>    ```
> 4. `<C-W>q` で終了
> 5. .viminfo のコマンド履歴が下記の様になっている
>    
>    ``` vim
>    :echo 5
>    :echo 4
>    :echo 3
>    :echo 2
>    :echo 1
>    ```
> 6. 起動して下記のコマンドを実行
>    
>    ``` vim
>    :q
>    ```
> 7. .viminfo のコマンド 履歴が下記の様になっている(`:q` が記録されていない)
>    
>    ``` vim
>    :echo 1
>    :echo 5
>    :echo 4
>    :echo 3
>    :echo 2
>    ```
> 
> ###### 確認環境
> - 7.3.882 x64 +kaoriya (windows7 x64)
>   … 再現
> - 7.3.880 自己ビルド (windows7 x64)
>   … 再現
> - 7.3.884 自己ビルド (windows7 x64)
>   … 再現
> - 7.3.888 自己ビルド (windows7 x64)
>   … 再現
> - 7.3.888 自己ビルド (ubuntu server 12.04LTS x86)
>   … 再現
> - 7.3.879 自己ビルド (windows7 x64)
>   … 大丈夫
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/358

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
これか

http://ftp.vim.org/pub/vim/patches/7.3/7.3.880

**Comment by h-east** [comment]
一応今gdbで追っかけている最中です。
なんか分かったらすぐコメント下さい。寝ますからｗ

**Comment by mattn** [comment]
あーいま遊んでるので

**Comment by koron** [comment]
つまり「寝るな」ですね。

**Comment by h-east** [comment]
なんとか解明。

### 原因

A. 再現手順の`6.`の`:q`を実行すると add_to_history() が呼ばれます。その直後の **Vim内部の**コマンド履歴は以下のようになっています。

```
:q
:echo 5
:echo 4
:echo 3
:echo 2
```

B.  **~/.viminfoファイル内の**コマンド履歴は再現手順`5.`と同様以下の内容になっています。

```
:echo 5
:echo 4
:echo 3
:echo 2
:echo 1
```

C. 実際の`:q`の処理時に~/.viminfoを再読み込みして **Vim内部の**履歴を最新の状態にする処理がおこなわれます。(7.3.880で入ったやつ)

```
:echo 5
:echo 4
:echo 3
:echo 2
```

までは既にVim内部の履歴に存在しますからスルーしますが、`:echo 1`に関しては（`:q`の追加によりVim内部の履歴からは消えているので）「おっ！外部で更新されたからVim内部の履歴を更新！」と勘違いをしてVim内部の履歴を再現手順`7.`のような情報に更新してそれを最終的に~/.viminfoに書き出してしまっています。

### 対策

`C.`の処理にて各履歴毎に読み込む行数で制限を掛けて不必要な履歴更新を回避すればよさそうです。
`set history=5`と自分自身で更新した履歴(`:q`)1件ですから 5件 - 1件 で頭の4件のみ照合しそれ以降は照合しないロジックを入れるのだ！

**Comment by h-east** [comment]
このpatchでいろいろ確認お願いします。

``` diff
diff -r 9b772e48f79e src/ex_getln.c
--- a/src/ex_getln.c    Fri Apr 12 15:09:51 2013 +0200
+++ b/src/ex_getln.c    Sun Apr 14 03:21:10 2013 +0900
@@ -5998,9 +5998,10 @@
 #endif

 #if (defined(FEAT_VIMINFO) && defined(FEAT_CMDHIST)) || defined(PROTO)
-static char_u **viminfo_history[HIST_COUNT] = {NULL, NULL, NULL, NULL};
-static int viminfo_hisidx[HIST_COUNT] = {0, 0, 0, 0};
-static int viminfo_hislen[HIST_COUNT] = {0, 0, 0, 0};
+static char_u **viminfo_history[HIST_COUNT] = {NULL, NULL, NULL, NULL, NULL};
+static int viminfo_hisidx[HIST_COUNT] = {0, 0, 0, 0, 0};
+static int viminfo_hislen[HIST_COUNT] = {0, 0, 0, 0, 0};
+static int viminfo_readcnt[HIST_COUNT] = {0, 0, 0, 0, 0};
 static int viminfo_add_at_front = FALSE;

 static int hist_type2char __ARGS((int type, int use_question));
@@ -6065,6 +6066,7 @@
        len = 0;
    viminfo_hislen[type] = len;
    viminfo_hisidx[type] = 0;
+   viminfo_readcnt[type] = 0;
     }
 }

@@ -6082,7 +6084,8 @@
     char_u *p;

     type = hist_char2type(virp->vir_line[0]);
-    if (viminfo_hisidx[type] < viminfo_hislen[type])
+    if (viminfo_readcnt[type]++ < viminfo_hislen[type]
+   && viminfo_hisidx[type] < viminfo_hislen[type])
     {
    val = viminfo_readstring(virp, 1, TRUE);
    if (val != NULL && *val != NUL)
```

**Comment by h-east** [comment]
crazy englishでvim_devに投稿しました。
https://groups.google.com/d/msg/vim_dev/uV0EhMW2c1M/5VUTOftHcgEJ

**Comment by DeaR** [comment]
バッチリです:+1:
原因及び対策的にも納得:yum:

**Comment by ynkdir** [comment]
これ例えばこういう場合はどうなりますか

``` sh
$ vim
:echo 1
:echo 2
:echo 3
:echo 4
:echo 5
<C-W>q

# history:
# :echo 5
# :echo 4
# :echo 3
# :echo 2
# :echo 1

$ vim
# ここで他のvimで作業
<C-Z>
$ vim
:echo 999
:echo 2
:echo 3
:echo 4
:echo 5
<C-W>q

# history:
# :echo 5
# :echo 4
# :echo 3
# :echo 2
# :echo 999   <- 新しい履歴

$ fg
# 戻ってきた
:q

# history:
# :q
# :echo 5
# :echo 4
# :echo 3
# :echo 2
```

**Comment by DeaR** [comment]
いや、複数起動すると結構滅茶苦茶ですね…
1. 起動
   
   ``` vim
   :echo 1
   :echo 2
   :echo 3
   :echo 4
   :echo 5
   <C-W>q
   ```
2. 起動
   
   ``` vim
   :echo 6
   :echo 7
   ```
3. もう1個起動
   
   ``` vim
   :echo 8
   :echo 9
   ```
4. 1個目の方
   
   ``` vim
   <C-W>q
   ```
5. 2個目の方
   
   ``` vim
   <C-W>q
   ```
6. .viminfo
   
   ``` vim
   :echo 6
   :echo 8
   :echo 5
   :echo 4
   :echo 7
   ```

正直ｓｈｅｌｌのhistoryのように時間が残ってないので結構しんどい気が…

それこそ`add_to_history()`される度に再読み込みでもすれば必ず1個追加される、
という分かりやすい状況になり、どうにかできそうですが仕様変更レベルですしねぇ…
(しかもhistoryが大きいと負荷が凄い…多分)

**Comment by h-east** [comment]
うぅ、修正が不十分だったですね。

Vim終了時の read_viminfo_up_to_marks() → read_viminfo_history()の中で、
読み込んだ履歴文字列を自分が持っているか in_history() で判断して持ってなかったら
viminfo_history[type][] に登録する処理していますが、
そんな判断せずに
`履歴MAX数('history'オプションの値) － 自分が内部で作成した履歴数`(上記の場合 3) を.viminfoから読み込んだらいいんちゃいますかね？
自分が持っていない履歴情報だけをセットして後でなんとかしようとするから余計ややこしくなっている気がします。

**Comment by ynkdir** [comment]
そうですね。

**Comment by h-east** [comment]
Patch 7.3.892 でバグ解消されたようです！(fedora17で確認)
(patchはBram氏が完全書き下ろし)
https://groups.google.com/d/msg/vim_dev/_EXmrjhpuiw/qTZk7umsy0oJ

(Patch 7.3.891 もviminfo関連ですが本issueのバグに直接影響するものではないみたい)
https://groups.google.com/d/msg/vim_dev/wPLyvWW2wHM/bpDbpUzNODIJ

**Comment by h-east** [comment]
@DeaR 7.3.892で動作確認して問題ないようでしたらissueクローズしちゃってください。
報告ありがとうございました。また何かありましたらよろしくお願いします。

**Comment by DeaR** [comment]
こちらでも修正されている事を確認しました
