### ISSUE TITLE
7.3.831で追加されたtest91でvalgrindがエラーを出す

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#359]
https://groups.google.com/d/msg/vim_dev/8DTyapKDH48/LSckb8-kpQIJ

@h-east 

> 「7.3.831で追加されたtest91でvalgrindがエラーを出すぞ(ﾟДﾟ)ｺﾞﾙｧ!! 」と言われてます。
> https://groups.google.com/d/msg/vim_dev/8DTyapKDH48/LSckb8-kpQIJ
> Vim 7.3.888 on fedora17で再現しました。
#245 の修正での関連問題のようです。

**Comment by h-east** [comment]
@Shougo issue立て乙。

たぶん...
もともとvalgrindがエラーを出すようなコードになっていたけど、
7.3.831以前はgetbufvar(), getwinvar(), gettabwinvar() を使用したtestが無かった。(gettabvar()はtest62で使用されていた)
そして7.3.831で上記関数を使用したtest91が追加されたので顕著化した。

という事だと思います。
対策考えます。

**Comment by Shougo** [comment]
ふむふむ。元々のコードがバグっていたというわけですね……。

**Comment by h-east** [comment]
Patch 7.3.895 で修正されました。(Bram氏書き下ろしのpatch)
https://groups.google.com/d/msg/vim_dev/S6s2A6rTdoQ/PWOxb1Xfz7YJ

今晩調べようと思っていたので助かった:smile:

**Comment by Shougo** [comment]
おお、それは良かったです。最近Bram氏のcontributeが増えてきた気がする……。
爆速でパッチが取り込まれるようになったし。

**Comment by h-east** [comment]
＆ Patch 7.3.898
https://groups.google.com/d/msg/vim_dev/TBJEwMcb68o/JEwcEVQBT0MJ
