### ISSUE TITLE
vim-jp/vim で vim の最新版コピーを維持したい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#36]
どうやるかは別として...

**Comment by koron** [comment]
git svnがあるならgit hgがあっても良さそうなものだね。

**Comment by koron** [comment]
http://d.hatena.ne.jp/tyru/20100429/git_hg_and_hg_fast_export

tyruさんが記事書いてんぞw

**Comment by mattn** [comment]
あると思うんですが、問題はどうやってcronするかですかねー

**Comment by koron** [comment]
cronについてはとりあえずうちのサーバ使えば良いのでは?

**Comment by mattn** [comment]
負荷かからないですか？

**Comment by koron** [comment]
やってみてダメならまた考える。

**Comment by mattn** [comment]
ちょっと試します

**Comment by koron** [comment]
うちの環境でインストールしなきゃいけないものがあったら言ってください。
ちゃんとシステムレベルで入れたほうが困らない。

ruby以外ならwww

**Comment by mattn** [comment]
これ、パスワード入力どうやって回避してるんだろう
http://bl.ogtastic.com/2008/8/2/mirroring-to-github

**Comment by koron** [comment]
github使うのにパスワード(フレーズ)って要るの?

**Comment by mattn** [comment]
これが一番よさげ
http://exyr.org/2011/git-mirrors/

**Comment by mattn** [comment]
再起動したらssh-agent消えますよね？

**Comment by mattn** [comment]
あ、こっちか？
http://cweiske.de/tagebuch/mirror-sourceforge-git-github.htm

**Comment by hattya** [comment]
ご存知かもしれませんがhg-gitというのもあります
http://hg-git.github.com/

そのものずばりな説明を見つけました
http://hgtip.com/tips/advanced/2009-11-09-create-a-git-mirror/

**Comment by mattn** [comment]
@hattya あざす。
だいたい同じ様な内容なのですが、問題はパスワード入力をどうやって回避するか。
再起動後に初回にssh-agentにどうやって渡すか。
とかですね。
key-chainとか使った方がいいのかしら。

**Comment by koron** [comment]
つまりmercurialの内容をgitに反映させるスクリプトはできていて、
あとはssh鍵、主に運用の問題だけが残ってる状態?

だとしたら私が引き継ぎましょうか?

**Comment by mattn** [comment]
現状のvimリポジトリは

http://cweiske.de/tagebuch/mirror-sourceforge-git-github.htm

を読んでhgとgithubに置き換えてやっただけなのでcronとか走らせてません。
初回はpushに凄く時間が掛かりましたが(1時間かかった)、次回以降は差分だけなので速いはずです。

って事でkoronさんにバトンタッチ

**Comment by koron** [comment]
了解。わかんないことあったら聞きます。

**Comment by koron** [comment]
githubには300MBの容量制限がある。
ところがVimのレポジトリをgitに変換すると500MBにもなってしまう。
(mercurialでは50MB以下にも関わらず!)
とはいえ25$/monthかけてBronzeにアップグレードするのは
少々コストに見合わない。

githubに乗せられないのであれば、
githubの各種ツールとの連携という恩恵は受けられないので
vimのレポジトリをvim-jpで独自に持つ魅力がなくなってしまう。

gitに変換する意味もなくなり、google codeでclone作ったほうがマシということになるだろう。
あわせてうちのマシンでcronを動かすメリットも失せてしまう。
ならば本件は一旦「Won't fix」という形で閉じてしまうということでも良いだろう。

もしくは「独自コピーを維持したい」とした要求を洗いなおして、
より適切なサービスとgithubとの併用を考えるべき。
その時サービスでmercurialが利用可能なら、それを使うようにしたほうが良い。
同期コストが低いのと、容量が小さくて済むことがその理由。

**Comment by ynkdir** [comment]
自分は使ったことないんですが `git gc` とかでいくらか小さくなるもんでしょうか。

容量制限は
https://github.com/plans
もしくは
Account Settings のページのディスク使用量のグラフのところの `soft limit`

```
GitHub does not have any hard storage limits. We have soft limits for each plan to prevent abuse. We find almost everyone uses a small fraction of this limit. If you find yourself needing more disk space for a legitimate use, email support@github.com.
```

abuse でなければなんとかしてもらえそうな雰囲気です。

まぁ今のところ容量オーバーしててもすぐにどうなるもんでもないらしいですが。(ぐぐる調べ)

**Comment by koron** [comment]
オーバーしててどうにかなったから消したんじゃないの？

**Comment by ynkdir** [comment]
あーそうなんですか。
自分はそのへん見てないもので。
すみません。

**Comment by mattn** [comment]
もっかい置いてみた＆githubに緩和してほしいってお願いしてみた。

**Comment by mattn** [comment]
サポートから回答貰った。

> As long as you keep your repos under 1GiB each, you shouldn't have any troubles.

って事でどんどん使っていきましょう。

@thinca limit超えてる様に見えますが大丈夫みたいです。
@tyru って事なのでbitbucket(ry
@koron cronよろしくです。

しばらくこれで運用してみるって事でこのissue閉じます。

**Comment by tyru** [comment]
@mattn www orz...

**Comment by mattn** [comment]
皆さん大丈夫だとは思いますが周知しときます。cronでマージするのでマスタブランチは触らないで下さい。

**Comment by ynkdir** [comment]
mattn++
参考になる

**Comment by koron** [comment]
私がcron設定するまでreopenしときます。

あと…push前にgit gcってやる意味あるかな? リモート上でgcしないと意味なし?

**Comment by thinca** [comment]
リモートには必要なファイルのみが送られるので、意味はないですね。

**Comment by mattn** [comment]
一応`git gc`してからpushしたけど意味無かったのね

**Comment by koron** [comment]
今作業中。期待して待て。

**Comment by koron** [comment]
```
$ hg pull https://vim.googlecode.com/hg/
```

してから .hg/hgrc の [path]セクションに

```
github = git+ssh://git@github.com/vim-jp/vim.git
```

コレを追加して、まずは

```
$ hg pull github
```

してみたら

```
git+ssh://git@github.com/vim-jp/vim.git から取り込み中
exporting hg objects to git
```

こうなって

```
last pid:  1223;  load averages:  1.00,  0.88,  0.52   up 24+01:01:36  22:08:57
44 processes:  2 running, 42 sleeping
CPU: 20.6% user,  0.0% nice,  4.8% system,  0.3% interrupt, 74.4% idle
Mem: 75M Active, 1300M Inact, 1244M Wired, 35M Cache, 404M Buf, 1149M Free
Swap: 8192M Total, 172K Used, 8192M Free

  PID USERNAME  THR PRI NICE   SIZE    RES STATE   C   TIME   WCPU COMMAND
 1182 koron       1 103    0   121M 54616K CPU3    3  10:58 100.00% python2.7
```

こうなっている真っ最中。

**Comment by koron** [comment]
先に進んだ。

```
["git-upload-pack '/vim-jp/vim.git'"]
```

だってさ。 pull なのに upload ってのが解せない。あとマージどうなるんだろう…ちゃんと良きに計らってくれるかなぁ?

**Comment by koron** [comment]
終わったので

```
$ hg push -f github
```

している最中。 `-f` がないと abort する。

**Comment by koron** [comment]
hg-git ではなく git-hg を試してみたが、mercurialのバージョンとの間で相性がありそう。

```
from mercurial import repo
```

がコケていた。

**Comment by koron** [comment]
githubの中身はヒドイ状態になってるw

**Comment by koron** [comment]
もうちょっと実験したあとで正式運用前に、 vim-jp/vim はいったんリセットしたほうが良いかも。

**Comment by koron** [comment]
ポイントは、更新作業を別のマシン or 環境に移す時。hg から取り出したものを git に1から変換しても、履歴をうまくマージしたい。

上記で行った私の作業のミス&問題は、hg-git でpushした際に履歴が2本になってしまったこと。しかも私の方はdeadheadになってる。しかもタグは私の履歴の方に移ってる。

ひとことで言うと超ヒドイ

**Comment by koron** [comment]
あ、deadheadどころか根っこがズレてるなw あ～コイツは極悪だわ…ｻｰｾﾝ

**Comment by koron** [comment]
https://github.com/vim-jp/vim で始めた。なので close

ミラーのcronも一応は動いてるっぽい。ただ実際に変更があった時にどうなるかはまだ見れていない。

**Comment by koron** [comment]
すったもんだして旧 vim-jp/vim が vim-jp/vim1 になったのは許してほしい。

**Comment by koron** [comment]
一応、ミラーの方法を書いておいた。 https://github.com/vim-jp/vim/wiki/HowToMirror 今後、ミラー作業を移行する場合の参考に。

**Comment by methane** [comment]
bitbucketに移行したらいいのに…

**Comment by koron** [comment]
7.3.692 のミラーを確認。cronもちゃんと動作している。
