### ISSUE TITLE
ja.po の typo 修正

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#361]
よろしくお願いします。

diff -r 9b772e48f79e src/po/ja.po
--- a/src/po/ja.po  Fri Apr 12 15:09:51 2013 +0200
+++ b/src/po/ja.po  Sun Apr 14 12:52:21 2013 +0900
@@ -685,7 +685,7 @@
 msgstr "E730: リスト型を文字列として扱っています"

 msgid "E731: using Dictionary as a String"
-msgstr "E731: 変数型を文字列として扱っています"
+msgstr "E731: 辞書型を文字列として扱っています"

 msgid "E806: using Float as a String"
 msgstr "E806: 浮動小数点数を文字列として扱っています"

**Comment by koron** [comment]
Thanks!

**Comment by koron** [comment]
https://bitbucket.org/koron/vim-kaoriya-patches/src/d398d61884e7f56639381d1987fc90057256c2b8/4901-ja_po-20130417.diff?at=default

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/cAONy9i7UeE/K66BSF77SwoJ

送った。

**Comment by ynkdir** [comment]
Thanks!

**Comment by k-takata** [comment]
7.3.919直前のruntimeファイルの更新で取り込まれました。

**Comment by ynkdir** [comment]
Thanks!
