### ISSUE TITLE
if_python の例外をVim側でトラップする

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#362]
<blockquote class="twitter-tweet" lang="ja"><p>Vim の Python / Python 3 インターフェイスで、raise SystemExit すると Vim ごと終了するのってマズいんじゃね？</p>&mdash; Masami HIRATAさん (@msmhrt) <a href="https://twitter.com/msmhrt/status/323418655893385217">2013年4月14日</a></blockquote>

JavaだとJNIのC側でトラップしたりできたはずなので、同じ事が if_python でできないだろうか?
例えばVimの例外に読み替えるのでも可。

突然の死に備える。

**Comment by msmhrt** [comment]
"[Catching SystemExit in C API code when embedding Python?](http://bytes.com/topic/python/answers/687009-catching-systemexit-c-api-code-when-embedding-python)" というページをみつけました。

PyErr_Occurred() したら、PyErr_ExceptionMatches で PyExc_SystemExit かどうかをチェックして、PyErr_Clear() するという手順のようですね。

**Comment by mattn** [comment]
https://gist.github.com/mattn/5385037

こんなところでしょうか。

**Comment by mattn** [comment]
誰か python3 での確認お願いします。

**Comment by koron** [comment]
今夜試す。

**Comment by Shougo** [comment]
ちょうどPython3が有効になっているので、時間があれば私も試してみます。

**Comment by Shougo** [comment]
+python3の環境で試して見ました。

`:py3 raise SystemExit`とすると、"E864: Can't handle SystemExit of python 3 exception in vim"と出ますが、この動作で良いですか？　落ちることはないことは確認できました。

パッチを読んでみたところ、この動作が想定通りなのかな。

**Comment by mattn** [comment]
> パッチを読んでみたところ、この動作が想定通りなのかな。

はい。ありがとうございます。このまま出します。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/B-mXfV6sCSM/VxlTvQqZxYwJ

**Comment by Shougo** [comment]
mattn++;

**Comment by koron** [comment]
私の方はやらんでもええかな?

**Comment by Shougo** [comment]
やらなくて良いと思います。

**Comment by koron** [comment]
メッセージをまとめろ言うてますな。

ただどのメッセージのことだ? `E863` と `E864` の違いを見逃しているのかな?

**Comment by mattn** [comment]
%s で python or python3 ってやれって意味かな

**Comment by koron** [comment]
そんなの、他のメッセージも全部同じこといえるんだよね…

**Comment by Shougo** [comment]
そういえば、このエラーについてドキュメントは更新しないのでしょうか。
Bram氏がこんなことを言っていますが……。

> It would be good to explain to the user that SystemExit is the wrong way
> to exit Vim and mention the right way.  Most users don't read the source
> code :-).

**Comment by mattn** [comment]
SystemExit で vim を終了するのは良くない方法だ、と説明し正しい方法について言及するのがいい。殆どのユーザはソースは読まないからね。

という意味です。とはいいつつもこれ以上説明すると1行越えるので doc に書こうかな。

**Comment by mattn** [comment]
更新

**Comment by Shougo** [comment]
> という意味です。とはいいつつもこれ以上説明すると1行越えるので doc に書こうかな。

はい。それが良いかと思います。

**Comment by msmhrt** [comment]
この問題に引っかかる場合、sys.exit() で終了する上品な Python スクリプトを実行したら Vim ごと落ちたというパターンが一番多いんじゃないかなーと思いました。
[内部的に raise SystemExit している sys.exit()](http://hg.python.org/cpython/file/4a6b8f86b081/Python/sysmodule.c#l227) を除けば、わざわざ raise SystemExit と書くことって滅多になさそうです。

**Comment by msmhrt** [comment]
すみません。訂正します。grepしたら結構ありましたｗ

**Comment by mattn** [comment]
ww

**Comment by k-takata** [comment]
todo.txt入りしましたが、最後の行が…

> Python SystemExit exception is not handled properly.  Patch to catch the
> exception and give an error. (Yasuhiro Matsumoto)
> Does not work, tests fail.

**Comment by h-east** [comment]
たぶん @mattn さん、↓を見逃している気がする。
https://groups.google.com/d/msg/vim_dev/B-mXfV6sCSM/8aCwqbeCsHMJ

> Unfortunately, with the current source code this makes the tests fail. 
> Hopefully this can be fixed.

**Comment by mattn** [comment]
見逃してないすよ。
「俺、直しとくから」的に捉えました。(え

**Comment by h-east** [comment]
@mattn :cat2::dash: 手伝おうとしたけど上手くpatchが当てられなくって断念 :sweat_smile:
if_python*.c さすがにめっちゃ変わってるｗｗ

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/o1f80vhBqso/inVW-aHe3uUJ

> This is what I currently have at the top of the todo list.  Unless I get
> a patch soon, I'll move these down and it will have to wait until after
> the 7.4 release.

すぐにパッチを出さなければ7.4のリリースの後に回されてしまいます。

**Comment by mattn** [comment]
音速でpatch更新した

**Comment by k-takata** [comment]
:+1:
でも、E863 ってもう使われていたような。

**Comment by mattn** [comment]
*.c *.h で grepったけどなかったので使いました。

**Comment by k-takata** [comment]
*.po にはありますね。残骸でしょうか。

```
msgid "E863: return value must be an instance of str"
```

**Comment by mattn** [comment]
E879 に変えます

**Comment by mattn** [comment]
うひっつかわれてたw

**Comment by mattn** [comment]
E880 あいてた

**Comment by mattn** [comment]
デバッグコードうめこんだままだったw

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/o1f80vhBqso/ENuL7pICJJQJ

> On Ubuntu 12.10 this doesn't work, tests 86 and 87 fail.

だそうで。

**Comment by k-takata** [comment]
Windows でも test86, 87 が失敗しました。

https://gist.github.com/mattn/5385037#file-gistfile1-diff-L84
Py_eval_input を Py_file_input に変更していますが、この変更は不要じゃないでしょうか。
ただ、これを戻しても test86, 87 が失敗します。（改善はしているのですが。）

**Comment by mattn** [comment]
Py_eval_input のままだと1回のコンテキストで閉じてしまうのです。Py_file_input は PyRun_SimpleString の中身を見て置き換えています。

**Comment by k-takata** [comment]
よく分かっていませんが、その部分は元々 Py_eval_input なので1回のコンテキストで閉じるのが期待値では？

**Comment by mattn** [comment]
ですねー。直しました。

**Comment by k-takata** [comment]
PyRun_SimpleString() の実装と見比べたところ、エラーになったときに PyErr_Print() を呼ぶ処理が抜けていたっぽいです。
PyErr_Print() は PyErr_PrintEx(1) と同じらしいので、それを呼ぶようにしてみました。
https://groups.google.com/d/msg/vim_dev/o1f80vhBqso/OzKzm3JN6LEJ
あと、Python 3.3で失敗する件も一言追加。

**Comment by mattn** [comment]
あざます

**Comment by k-takata** [comment]
typo の指摘きた。

> I think you mean "endorsed" in this sentence.

:set spell してなかった。不覚。

**Comment by k-takata** [comment]
https://gist.github.com/mattn/5385037/bb5cb52eeff934f3b76203908dbb527f75f86063#file-gistfile1-diff-L84
ここの部分、E880 が出たあと、E858 が出てしまう気がしますが、意図したものでしょうか。

**Comment by mattn** [comment]
明日まで見れそうにないので、もし見れそうなら良しなにお願いします

On 7/1/13, K.Takata notifications@github.com wrote:

> https://gist.github.com/mattn/5385037/bb5cb52eeff934f3b76203908dbb527f75f86063#file-gistfile1-diff-L84
> ここの部分、E880 が出たあと、E858 が出てしまう気がしますが、意図したものでしょうか。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/362#issuecomment-20284219

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
7.3.1287 で入ってしまいました。
https://groups.google.com/d/topic/vim_dev/EwqKqIcXgFU/discussion

**Comment by k-takata** [comment]
> ここの部分、E880 が出たあと、E858 が出てしまう気がしますが、意図したものでしょうか。

E880 が出ていれば十分な気がするので、修正案です。
https://bitbucket.org/k_takata/vim-win32-mq/src/a449bd5ecf4c4af791231cb4fb2597e58ea97da9/python-run_eval.patch
PyRun_String() の戻り値が NULL だった場合で、PyErr_Occurred() が false になる場合があるのかよく分かりませんが、他の部分と統一するなら PyErr_ExceptionMatches() の前にはチェックしておいた方が良さそうな気もします。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/EwqKqIcXgFU/viMZB6AXUe4J
@mattn ご確認ください。

**Comment by k-takata** [comment]
7.3.1312 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/EDx7Gilpvxk/discussion

**Comment by koron** [comment]
あ…翻訳が必要なメッセージ増えてる (´・ω・`)

**Comment by k-takata** [comment]
あれ？そうでしたっけ。
