### ISSUE TITLE
src/po/Make_*.mak が不完全

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#363]
Make_mvc.mak において vim.pot の基になるソースがMakefileよりも少ないため
下手に `*.po` を更新してしまうといくつかの翻訳が失われる。

気がついたのはGvimExtだけど他にもあるかも。

**Comment by k-takata** [comment]
Makefile:

```
$(PACKAGE).pot: ../*.c ../if_perl.xs ../GvimExt/gvimext.cpp ../globals.h ../if_py_both.h
```

Make_mvc.mak:

```
files:
    $(LS) $(LSFLAGS) ..\*.c ..\if_perl.xs ..\globals.h > .\files
```

GvimExt/gvimext.cpp と if_py_both.h が足りないようですね。

**Comment by k-takata** [comment]
Posted.
https://groups.google.com/d/topic/vim_dev/Jhm_ZMzTdeE/discussion

**Comment by k-takata** [comment]
8.0.1252
https://groups.google.com/d/topic/vim_dev/bHfexSA-PAw/discussion
