### ISSUE TITLE
ja.po のエンコード

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#364]
ja.po のエンコードを euc-jp から utf-8 に変えるべきだと考えているんだけどどうでしょう?

ja.sjis.po の生成部分を除いて何か懸念事項はありますか?

特に無ければ 7.4a が出たら提案しようと思う。

**Comment by msmhrt** [comment]
ja.po で EUC-JP では表現できない文字を使いたかったという話でなければ、いわゆる機種依存文字やUnicode文字を使っていないことをチェックする仕組みが必要なんじゃないかなと思いましたが、今時必要ないですかね？

**Comment by ynkdir** [comment]
+1

**Comment by mattn** [comment]
基本問題ないと思いますが。

> いわゆる機種依存文字やUnicode文字を使っていないことをチェックする仕組み

そういう意味で逆に、一番低スペックなEUC-JPのままに、というのも一つの案かと思いました。

**Comment by msmhrt** [comment]
エンコーディングが UTF-8 じゃないと GitHub で閲覧しにくいという理由なのかな？と思ってました。

**Comment by koron** [comment]
> そういう意味で逆に、一番低スペックなEUC-JPのままに、というのも一つの案かと思いました。

`ja.sjis.po` 作る時点で検出できちゃうんじゃないですかね?

> エンコーディングが UTF-8 じゃないと GitHub で閲覧しにくいという理由なのかな？と思ってました。

一番の理由は「時代遅れなEUC-JPのままにしとくのは問題だ」と思っただけですw

**Comment by msmhrt** [comment]
いわゆる波ダッシュ問題については大丈夫でしょうか？

euc-jp のままなら問題なかったのに、utf-8 にしたことによって一部の環境でエンコーディングの変換時にエラーが発生、あるいは文字化けするという状況を懸念しています。

**Comment by mattn** [comment]
Makefile の最後に

```
iconv -f utf-8 -t cp932 ja.po > /dev/null 2>&1 && iconv -f utf-8 -t euc-jp ja.po > /dev/null 2>&1
```

で書いておけばチェックにはなりそうですけどね。

**Comment by koron** [comment]
@msmhrt 
そもそも euc-jp で使う奴は少なくなってるから utf-8 にしましょうね、っていう話なんで
未だに euc-jp にしがみついてて問題が発生する可能性もその重要度も低く捉えてるんです。

だから問題は発生したらその時に考えましょう。

@mattn 
コンパイルのたびにそれをやらせるのは馬鹿馬鹿しいでしょ。
必要ならMakefileにチェック用のターゲット作って
ドキュメントに一言「翻訳修正したらこれでエンコードチェックしてね」
みたいに書いておけばいいんじゃないかな。
必要かどうかが、そもそも疑問だけど。

**Comment by msmhrt** [comment]
@koron 
心配しているのは、euc-jp にしがみついている環境ではなく cp932 にしがみついている環境の方でした。
euc-jp -> cp932 が utf-8 -> cp932 になることによって、OSの違いや iconv の方言が問題を引き起こすのではないか？と思っていたのです。
しかし、今朝になって、Windows 以外のOSで cp932 にしがみつく必要はほとんどなさそうだし、cp932な環境が Windows だけなら問題ないのではないか？と思い直しました。よって、

> だから問題は発生したらその時に考えましょう。

に同意します。

**Comment by koron** [comment]
ねじ込んだ。受け入れてくれるかは不明。

https://groups.google.com/d/msg/vim_dev/7fR2Z--YJSE/fUe3eJayU0oJ

**Comment by koron** [comment]
Bram氏から「ja.euc-jp.so として残したほうが良いのでは」との提案。

私からは EUC-JP ユーザ向けにドキュメント書くから。と返した。

**Comment by k-takata** [comment]
7.3.999 直前のコミットで取り込まれました。
# 7.4 向けなのにｗ

**Comment by Shougo** [comment]
> 7.3.999 直前のコミットで取り込まれました。
> # 7.4 向けなのにｗ

吹いた。Vim7.4は出るんですかね……。
