### ISSUE TITLE
f,F,t,Tの展開関数

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#365]
`f{char}` した時の `{char}` を展開できるようにするのはどうか。

Vimスクリプトで `{char}` 受け取って文字列を返す関数を与えると、
`f{char}` の時に呼び出されて文字列の中から最初に現れた文字までジャンプする。

これを使うと日本語の上で `f{char}` するのを簡単にするプラグインを無理なく作れる。

**Comment by mattn** [comment]
omap?

**Comment by mattn** [comment]
http://mattn.kaoriya.net/software/vim/20130311100125.htm
https://github.com/mattn/wiseman-f-vim
http://ascii.io/a/2301

こういうのではなく？

**Comment by koron** [comment]
fa って打ったら a だけじゃなく
ä にも あ にも 安 にも飛べる感じ。
そういうプラグインを書きやすくする。

**Comment by mattn** [comment]
書けると思う。 omap で `<expr>` にして自分で `/[aäあ]/` な事をやればいいかと。wiseman-f はそれをやってる。

**Comment by koron** [comment]
今移動中なので自分で試せてないけど…
c3fa とかしたときは 3 と a が expr に渡る感じ?

**Comment by tyru** [comment]
ちなみに本題とは関係ないし知ってると思いますが、langmapはfの引数にも適用されます。
langmapがオンになっててかつkeymap=kanaだと、faとか打つと「あ」を検索します。

**Comment by koron** [comment]
自分も昔なんか作った記憶があるけど…
覚えてないやw

**Comment by koron** [comment]
omap はなんかちょっと違うかも。

いややりたいことはできるだろうけど、
分かりやすさが足りないというか手間が多い感じ。

単に入力文字と検索対象の文字のマッピングだけ書かせたら
書けたらどうだろうか、という提案。

langmap のほうがその意味では近い。
でもあれは入力1つに対して検索対象が1つしか出てこないから、
その点では違う。

---

優先度は高くないけど、
カーソルの左右移動を無理なく拡張&カスタマイズできないか
という視点からでてきた issue です。

**Comment by koron** [comment]
普段使いでそんなに便利そうな気はしないので wontfix で閉じます。

結局のところ「プラグイン書くのに便利な機能」は意義が少ない。
特に代替手段(omap)がある場合には。
