### ISSUE TITLE
CUIのVimで日本語入力すると縦分割したウインドウがずれるらしい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#366]
私の環境では発生したことがありませんが、こういう報告を見かけました。

https://twitter.com/meganetaaan/status/324709678997180418

> Vimで日本語入力使うときのこれなんとかなりませんか /

 http://twitpic.com/ck3ku6

Macの端末固有の問題かもしれません。LinuxのGNOME Terminal では再現せず。

**Comment by mattn** [comment]
ターミナル上での日本語入力がeskkの様なvim側の物でないなら、端末側が原因かと。

**Comment by Shougo** [comment]
表示を見る限り、Vim側のものではないですね。となると、Vim側でできることはないか……。
バグがある端末なんですかね。スクリーンショットを見てみるとMacの標準的な端末のようです。

**Comment by Shougo** [comment]
https://twitter.com/meganetaaan/status/324715275645755393

> @uchan_nos @ide_an homebrewで入れたvim。mac標準の方も同じ現象おきる。gVimはうまくいった。ありがとう！

端末を変えるようにアドバイスしたほうがいいですかね。

**Comment by itchyny** [comment]
MacのTerminal.app(2.3), vim(7.3, 1-887)で再現しました.
同MacのiTerm2では再現しません.
左側のウィンドウの入力中(変換途中)にずれ, 変換決定すると表示が正常になります.

Terminal.appが悪いです.

+multi_byte です (関係あるのかな...)

**Comment by h-east** [comment]
@itchyny フォロー(事実確認の報告)ありがとうございます。

Vimの旧Ver.とTerminal.app 2.3 でも起きていたのかとか、
Vim 7.3.887とTerminal.appの旧Ver.でも起きていたのかとかが気になる所です。

**Comment by itchyny** [comment]
Mac標準のVimとTerminal.app 2.3の組み合わせも, 同じ問題が生じます.

```
:version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 20 2012 13:16:02)
Compiled by root@apple.com
```

Mac標準のVimとiTerm2の組み合わせは, この問題は生じません.

**Comment by itchyny** [comment]
![変換中](https://f.cloud.github.com/assets/375258/395349/481ffde6-a7fa-11e2-9851-2ce485085057.jpg)
![ABC](https://f.cloud.github.com/assets/375258/395352/4b1edbac-a7fa-11e2-9f0e-5294469e5d8f.jpg)

**Comment by mattn** [comment]
おもいっきり文字幅分ずれてますねw

**Comment by itchyny** [comment]
https://twitter.com/meganetaaan/status/324798185509892098

> @itchyny iTerm2で先程のVimの問題が解決しました。ご親切にアドバイスをありがとうございます！これを機会にiTerm2に乗り換えようと思います

この人については解決.
ですが, Terminal.appはMacのデフォルトの端末という点で, 気になります.

Emacsでも同じ事が起こることを確認したので, Vimのバグではありません. (最初からこうすれば良かったですね)
vim-jpとしては閉じてもいい気がして来ました.
![Untitled](https://f.cloud.github.com/assets/375258/395510/8a2681a4-a801-11e2-8e55-2f5144eab400.jpg)

**Comment by Shougo** [comment]
了解です。閉じました。

**Comment by Shougo** [comment]
@saitoha さんによると、Terminal.appの仕様らしいです。
