### ISSUE TITLE
How to use vim-cmdsrv-nox

### ISSUE THREAD

**Issue by Forethinker** [vim-jp/issues#367]
Hi, sorry for jumping into Japanese Vim page with English, but the I think this community is most familiar with `vim-cmdsrv-nox` (VCN) If you point me to right direction, I can post on other places. I know VCN is in developmental phase and it has not been reviewed to be a part of vim package, but I could not find the documentation on how to use it. I am just trying to mimic `--remote-tab` flag for vim with `+clientserver` enabled. I tried compiling with the following options:  
    ./configure --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-cscope --enable-multibyte --with-features=huge --enable-gui --prefix=/usr

But it is does not have `+clientserver` enabled. Am I suppose to use different keywords other than `--remote`?

**Comment by mattn** [comment]
Hi, vim-cmdsrv-nox is unofficial patch that @ynkdir wrote.

https://code.google.com/r/yukihironakadaira-vim-cmdsrv-nox/

And it is suggested to vim-dev to merge as official.

https://groups.google.com/forum/#!msg/vim_dev/dm8nvb5b3do/-SzW7dq4EBIJ

As you know, `+clientserver` is using X11 protocol on unix. So it depend on X11 even though if you don't want, and it doesn't work without X display that opened. vim-cmdsrv-nox provides non-dependencies to X11. it use unix domain socket on unix, and use namedpipe on windows. If you want to try this, checkout repo, and build it as same as original vim.

```
$ hg clone https://code.google.com/r/yukihironakadaira-vim-cmdsrv-nox/
$ ./configure
```

vim-cmdsrv-nox doesn't provide new option or commands. it just replace protocol of that.

Thank you for your interesting.

**Comment by koron** [comment]
#125 will be discussing "How to strongly push vim-cmdsrv-nox patch to vim-dev".

**Comment by Forethinker** [comment]
Thank you for your responses. So I cannot use `+clientserver` features even with copmiled `vim-cmdsrv-nox` in windows. I had no trouble compiling even with all the options, but I got confused to thinking that X11 and X server are the same thing. I thought that it mimic X server in Windows. Haha. I wish to use xterm vim instead of gVim for everything, but I know I am dreaming the impossible. Thanks again.
