### ISSUE TITLE
:wviminfo 時に Vim が落ちる

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#369]
:wviminfo を行った際に Vim が落ちるケースがあったので報告。
- 環境
  - Vim : KaoriyaVim 7.3.905
  - OS : WindowsXP SP3
  - _vimrc/_gvimrc : 空（中身が空でファイルは存在する）
- 再現手順
  test.vim は予め削除しておく。また _viminfo が読み込まれていない場合は再現しない。

``` shell
$ gvim
:wviminfo test.vim
```

以下、把握している範囲で再現しないケース
- gvim ではなく vim を使用する
- gvim -u NONE を使用
- 既に test.vim が存在している
- home にある _viminfo ファイルを削除してから gvim を起動させる
- _vimrc ファイルと _gvimrc ファイルが存在しない（ファイルが存在し、中身が空の状態だと再現する

再現しないケースが多いんですが（上記以外にもあるかも）、他にも再現する方はいますでしょうか。

**Comment by mattn** [comment]
再現しました。　on XP SP3

**Comment by mattn** [comment]
先日入ったviminfo関連のバグですかね。

``` diff
diff -r ef341d8811b2 src/ex_getln.c
--- a/src/ex_getln.c    Mon Apr 15 22:22:58 2013 +0200
+++ b/src/ex_getln.c    Mon Apr 22 09:31:10 2013 +0900
@@ -6230,7 +6230,8 @@
            && !(round == 2 && i >= viminfo_hisidx[type]))
        {
            p = round == 1 ? history[type][i].hisstr
-                          : viminfo_history[type][i];
+                  : viminfo_history[type] ?
+                   viminfo_history[type][i] : NULL;
            if (p != NULL && (round == 2 || !history[type][i].viminfo))
            {
            --num_saved;
@@ -6261,7 +6262,7 @@
        }
    }
    for (i = 0; i < viminfo_hisidx[type]; ++i)
-       vim_free(viminfo_history[type][i]);
+       if (viminfo_history[type]) vim_free(viminfo_history[type][i]);
    vim_free(viminfo_history[type]);
    viminfo_history[type] = NULL;
    viminfo_hisidx[type] = 0;
```

**Comment by h-east** [comment]
> 先日入ったviminfo関連のバグですかね。

はい。 #358 関連ですね。

↓mattnさんのpatch、これと全く同じっぽい？ということは "How to reproduce" を投稿すればおｋかな？
patch for viminfo crashing
https://groups.google.com/d/msg/vim_dev/xrXWPVVfcr0/C6Sk0JQDIF8J

**Comment by mattn** [comment]
同じパッチ書いてしまった。。。

**Comment by h-east** [comment]
いえいえGJです。あのpatchが正しいことが証明されました。

**Comment by k-takata** [comment]
7.3.913で直りました。
https://groups.google.com/d/topic/vim_dev/goj6iopTfng/discussion
