### ISSUE TITLE
Vim内部の補完候補をVim scriptから取得できるようにする

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#37]
現状、Vimはいろんな補完を組み込みで持っていますが、それらをVim scriptから取得する方法がありません。
だから、neocomplcacheでは候補を自前で取得することになっていたり、コマンドの実行結果をパースしたりと、
かなり実装が煩雑になってしまっています。

やはり、Vimの補完候補はVim scriptで取得できるべきだと思います。

---

村岡注: ここで言う補完は`ins-completion`ではなく`command-completion`のこと。

**Comment by koron** [comment]
私にとっては根拠が薄い。なので私としてはノータッチ。

そもそも補完プラグインがVimと同じ結果を出して欲しいという要求は、ユーザからしたらかなり特殊にみえる。
なぜならユーザは自分でVimのネイティブ補完を選んで使うことができるから、必要なら最初からそっちを使えばよい。
だからそれをプラグイン側に回すことはエンドユーザにとってメリットが薄いと考える。
プラグイン作者にとっては要求がある、という視点では
用途が特殊かつ既に実装できてるならそれで良いじゃんという考え方もある。

Vimが持ってるロジックの流用という視点では、
補完関数自体をyield的なものに差し替えないとうまく齟齬しないだろう。
幾つかのVimネイティブ補完はあらん限りのファイルを全スキャンして、順次結果を増やしていく。
よって補間関数に候補群をリストで渡す方式はそぐわずyield的なものが要る。

**Comment by koron** [comment]
あと気になったのは、その機能って neocomplcache の実装を楽にするためだけのものになってないか、ってこと。
逆に考えると neocomplcache みたいなプラグインを大量に生み出すための機能とも考えられる。

neocomplcache にしてみれば楽するための機能なのかもだけど、ライバルを増やすための機能でもあるよね。
それって本当に必要? ユーザにとってneocomplcacheみたいなプラグインがいくつもあるのは便利なのかな?

**Comment by Shougo** [comment]
> 私にとっては根拠が薄い。なので私としてはノータッチ。

はい。誰も賛同者がいなければ、自分がやるしかないのかなぁとは思っています。

> あと気になったのは、その機能って neocomplcache の実装を楽にするためだけのものになってないか、ってこと。
> 逆に考えると neocomplcache みたいなプラグインを大量に生み出すための機能とも考えられる。
> いいえ、neocomplcacheのためだけに欲しいのではありません。

http://vim.g.hatena.ne.jp/ka-nacht/20080722/1216706724

> それ以外の場合は-complete=file相当の補完を行う(ただこの手の補完処理はVim scriptレベルに関数として公開されていない。v:command_complete_file()のような形で使えれば便利なので、この点については今度パッチを書いてvim_devにポストする予定)。

とあるように、kanaさんも欲しいと言っていました。別にneocomplcacheに限らず、応用例はいろいろ考えられると思います。

> Vimが持ってるロジックの流用という視点では、
> 補完関数自体をyield的なものに差し替えないとうまく齟齬しないだろう。
> 幾つかのVimネイティブ補完はあらん限りのファイルを全スキャンして、順次結果を増やしていく。
> よって補間関数に候補群をリストで渡す方式はそぐわずyield的なものが要る。

おっしゃっている意味がよく分からないのですが、私としては何らかの関数で現在の候補のリストが得られれば十分で、
yield的なものは必要ないと思います。

KoRoNさんはVimにおけるtag補完やインクルード補完のことと勘違いしているみたいですね。
私が欲しいのは、ins-command-completionの候補を取得したいのではなく、command-completionの候補が欲しいのです。こちらはyieldではないし、目的にも合致していると思います。

あと、実装が楽になるというだけではなく、Vimの候補を取得できれば、高速化もできると考えられます。
そういう意味でも私にとって必要なのです。

**Comment by koron** [comment]
> KoRoNさんはVimにおけるtag補完やインクルード補完のことと勘違いしているみたいですね。
> 私が欲しいのは、ins-command-completionの候補を取得したいのではなく、command-completionの候補が欲しいのです。

なるほど。だとすれば説明文にそう書いておいたほうが良いです。

あと、確かにinsでなければyieldはほとんど要らなそうではあります。
(いやもしかしたら結局は同じかも、だけどw)

**Comment by koron** [comment]
Vimでソースコードが開きっぱなしだったので、ざっくりどうすれば良いかは見ておきました。

おそらくex_getln.cのExpandFromContext()がターゲットになります。
こいつをevalから使えるようにしてあげれば良いはずです。
同ファイルに何箇所か使っている場所があるので、パラメータはそこから推測できるでしょう。

以上、参考まで。

**Comment by Shougo** [comment]
> なるほど。だとすれば説明文にそう書いておいたほうが良いです。
> あと、確かにinsでなければyieldはほとんど要らなそうではあります。
> (いやもしかしたら結局は同じかも、だけどw)

確かにそうですね。

> おそらくex_getln.cのExpandFromContext()がターゲットになります。
> こいつをevalから使えるようにしてあげれば良いはずです。
> 同ファイルに何箇所か使っている場所があるので、パラメータはそこから推測できるでしょう。

アドバイスありがとうございます。
ちょっと時間のあるときに実装しておきます。

とりあえず、実装予定の関数のプロトタイプでも。

completelist({completion} [, {expr}])

引数{completion}はこの入力において利用できる補完の種類を指定する。
対応している補完の種類は、ユーザ定義コマンドにおいて引数"-complete="で指
定するものと同じである。詳しくは|:command-completion|を参照。
省略可能引数{expr}は補完に使用する入力文字列を指定する。この引数が与えられた場合、
{expr}にマッチする候補のみが返る。
結果は文字列のリストで返る。

**Comment by tyru** [comment]
`-complete=customlist`に指定できるような引数にしなくて大丈夫ですかね？
@ShougoさんのAPIだと直感的ですが位置とか違うと結果も違うcommand-completionはあるはず...

**Comment by Shougo** [comment]
当然、customlistも指定できます。input()もcustomlistは指定できるので考慮する必要があります。

**Comment by Shougo** [comment]
了解しました。となると、

completelist({completion} [, {arglead} [,{cmdline} [,{cursorpos}]])

とする必要がありますね……。

**Comment by tyru** [comment]
一応外出中に@Shougoさんに送ったreplyを転載。
http://twitter.com/#!/tyru/status/119276078048096256

```
@ShougoMatsu 今外出中なので書き込めないですがcustomlistを指定できるようにという意図ではなくcompletelist()の第２引数以降をcustomlistに指定する関数が受けとる引数と同じにしないと関数の柔軟性がなくなるのではないか、という意見です #37
```

**Comment by ynkdir** [comment]
`complete_check()` と要求がかぶってますね。

**Comment by Shougo** [comment]
要求が被っているとは、どういうことでしょうか。

**Comment by ynkdir** [comment]
こっちがあればあっちはいらないんじゃないかと。
ビルトインの補完候補を得る手段がないので自前でなんとかしなくちゃならなくて
そのハックを実現するためにアドホックな修正を入れるというのは本末転倒で
だったらそもそもの要求であるビルトインの補完候補を得る手段を入れる
という話をした方がわかりやすいのではないか
後でこっちの話をしたときにじゃあcomplete_check()でごちゃごちゃいってたのはなんなんだよってなるだろな
と思ったんですがこっちはcommand-completion限定の話なんですね。
失礼しました。

**Comment by Shougo** [comment]
あー、はい。補完関数の対象が違います。
complete_check()はcompletefunc, completelist()はcommand-completionにしか使えません。

KoRoNさんも最初勘違いしていましたね……。
あと、complete_check()でごちゃごちゃ言っているのは、
complete_check()が補完関数外で使えないから残念だなーということです。

**Comment by ynkdir** [comment]
ちなみにcomplete_check()のほうは
既存の(つまりcompletefuncに設定されている)ユーザー定義補完関数を自前で呼び出してその補完候補の一覧を得たいから
という理解であってますか。

**Comment by Shougo** [comment]
はい。そうです。

**Comment by koron** [comment]
@Shougo さん: 注は入れましたが…誤解する人が2人目ということでw、これは書き方、説明の仕方に原因があると考えたほうが良いでしょう。

なにも@Shougoさんに限ったことではないですが、今後は少し説明のしかたを考えていただければと、思った次第ですw

**Comment by Shougo** [comment]
はい……。人に説明するのはなかなか難しいと思っている次第です。

**Comment by ynkdir** [comment]
> はい。そうです。

なるほどわかりました。ありがとうございます。
ここに書くのもあれですが
complete_check()はcomplete_add()とセットで使われるので結局動かないんじゃないかなぁ
というのはvim-devで書いたとおりです。

**Comment by Shougo** [comment]
確かにそうですね。complete_check()は無理かなぁと思い始めています。

**Comment by thinca** [comment]
todo.txt 3782行目にこんなの見つけました。

> 8   Custom completion of user commands can't use the standard completion
>     functions.  Add a hook to invoke a user function that returns the type of
>     completion to be done: "file", "tag", "custom", etc.

**Comment by Shougo** [comment]
やはりtodoにあったんですね。最近ソースコードを追っていたんですが、これの実装は楽じゃないですね。
補完のコードはコマンドラインモードに過度に依存しています。
だから今までパッチを書く人がいなかったんだろうなぁ。

**Comment by mattn** [comment]
COMPLETEDONE イベント入ったけど、イベントのエキストラ情報として足りない物があったら言ってほしい

って言ってるので関連する人は今の内に確かめないと互換性がなくなる説。

https://groups.google.com/d/msg/vim_dev/XDFDQ8rkBII/7uHUjwuLghIJ

**Comment by koron** [comment]
あれは #14 の方かも。

**Comment by koron** [comment]
#835 で再提案されました。

リセットの意味で、こちらは duplicated で閉じて #835 に引き継ぎます。
