### ISSUE TITLE
Windows 7で複数ファイルをgvimにドラグ&ドロップしても1つしか開かない

### ISSUE THREAD

**Issue by KusakabeYouichi** [vim-jp/issues#373]
Windows 7で複数ファイルを開こうとドラグ&ドロップしても
gvim → 1つしか開かない
サクラエディタ → 1つしか開かない
TeraPad → 複数開く
です。右クリックの『開く』ならばちゃんと複数開きます。

あと、XPではとくに問題なかったはずです。7でドラグ&ドロップの場合だけ?

**Comment by koron** [comment]
私の手元では `:help drag-n-drop` に書かれている通り `:drop` したのと同じようになってます。

> 3.7 Drag and drop                     _drag-n-drop_
> 
> You can drag and drop one or more files into the Vim window, where they will
> be opened as if a |:drop| command was used.

日本語訳はこちら。
http://vim-jp.org/vimdoc-ja/gui.html#drag-n-drop

**Comment by koron** [comment]
Vim の仕様上は正しく動作しているので閉じます。

**Comment by mattn** [comment]
よくみたらvoidさん...
こんにちわw
