### ISSUE TITLE
go言語のプラグインをVimにバンドルする

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#375]
goに付属のプラグイン misc/vim をVimにバンドルしようって提案したら
「author から Bram にメールを送るよう」にとの御沙汰。

https://groups.google.com/d/msg/vim_dev/lMIYR_QAZFg/qkutGtNfk9oJ

…みると go authors と書いてあるがどうするのが良いだろう?
- go関係者(できればオリジナルのauthor?)に代表してメールを書いてもらう
- BSDだからプラグイン部分だけフォークして…

**Comment by thinca** [comment]
以前Scalaで同じ提案があって全く同じ展開になってましたね。
Goなら mattn さんがコミッタだった気がするので mattn さんが言えば何とかなったりは…?

**Comment by mattn** [comment]
misc/vim の一部のプラグインは僕が書いた物だけど、僕が書いた部分については(気持ち的には)okだけどねー。

ちなみにあれはgoogleにコードを寄与している扱いなので今後、主導権を握りたいって話ならそれは難しいかも。コピーを配布したいって話なら提案は出来ます。

**Comment by koron** [comment]
もちコピーで十分!

goもvimファミリー(!?)に入ってて欲しいだけです。

**Comment by mattn** [comment]
説得する際のメリットが欲しいです

**Comment by koron** [comment]
第1に **ユーザの利便性** 。第2に初学者への配慮。

追加オペレーション無しにgoのシンタックスハイライト他が
ほぼLinuxに標準でインストールされているVimから利用できることのメリットは計り知れない
ってのはどうでしょうか。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/golang-dev/UyOORFMEbus/a-EggrMzznYJ

**Comment by mattn** [comment]
vim の runtime files の更新の遅さを逆に指摘されましたがwww

**Comment by mattn** [comment]
ちなみにこの人、misc/vim を総括してる人

**Comment by koron** [comment]
もうどーしろっちゅーんだw

**Comment by Shougo** [comment]
> vim の runtime files の更新の遅さを逆に指摘されましたがwww

個人的には、Vimはruntimeの更新を頑張っている方だと思いますが……。
「Vimにおけるgoのruntimeのアップデートは○○○が責任を持って更新版をvim_devに投げる」くらい言わないといけないんでしょうか
Vimのruntimeの更新を誰が保証するのか（一種のディストリビュータが必要？）、という話なのですかね。
確かに別のところで更新されているファイルをVimに同梱する場合、誰かが最新版をvim_devに送付する必要があります。

**Comment by mattn** [comment]
あと

> Is there much benefit to shipping misc/vim with Vim itself? misc/vim 
> is of limited use unless you have Go installed anyway. 

予想通り、vim自身から配布する意味を問われてますね。scalaもそうでしたが。

```
ln -s /path/to/go/misc/vim ~/.vim/bundle/golang
```

出来る環境はいいですが、それが出来ないwindowsだとめんどくさいとかその辺が言えばいいんだろか。

**Comment by thinca** [comment]
そもそも bundle 自体標準ではないし、各ユーザが最新に追従するのは(bundleユーザなら別ですが)大変そうです。
あと、vim本体に bundle するなら ftdetect も本体に統合したい。これによってほーーーんの少し速くなるはず(読み込むファイル数が減るので)。

**Comment by Shougo** [comment]
Goの事情はよくわからないのですが、もしGoの処理系をAPT等でインストールした場合、Goに配布されているVimプラグインはVimから使用出来るのでしょうか。使用できないのなら、Vim本体に同梱する意味は十分あると思います。
Goの使用者の誰もが配布場所から最新版を取ってこれるわけではないし、Go本体に同梱されているVimプラグインをきちんとインストールできる知識を持つ人は限られています。

現在のVimは標準でパッケージ管理プラグインがインストールされていないため、そういう意味でもシンタックスファイルを本体に同梱するのは良いことだと思います。

**Comment by mattn** [comment]
goのftdetectはちょっとめんどくさいことしてるんですよね。

**Comment by thinca** [comment]
見てみた。これ ftplugin でできないですかね?

**Comment by mattn** [comment]
go言語の場合、fileencoding は utf-8、fileformat は unix しかありえないんです。
で、ソースを新規に開いた場合に latin-1 や cp932 になられると困るという前提があって、:e ++enc=utf-8 で開きなおすというのは嫌われそうな雰囲気だったのでこうしてます。
ftplugin だと遅かったりしませんか？

**Comment by thinca** [comment]
filetype が適用されるのがファイル開いた後なので、やはり ftplugin だと遅いですね。
この辺り妙なhackしなくてもちゃんとできるような仕組み欲しいなぁ。
あ、この話は本題とは関係なさそうなのでこの辺で。

**Comment by koron** [comment]
論点:
- vimのheadのruntimeは更新遅くないよ
- 各ディストリが古いvimを出すのは各ディストリの問題だからvimもgoも関係ないよ
  - Ubuntuだってオフィシャルなgoは1.0.2だし
- goの将来のユーザにとって、vimに含まれているのは有望じゃないかな
- goから直接プラグインが提供できないならvimに取り込むためにforkするかも

くらいかな。

**Comment by mattn** [comment]
> vimのheadのruntimeは更新遅くないよ

netrw とか phpcomplete とか pythoncomplete とか....

> 各ディストリが古いvimを出すのは各ディストリの問題だからvimもgoも関係ないよ
> Ubuntuだってオフィシャルなgoは1.0.2だし

goのリリース、vimのリリース、それぞれのタイミングでエンドユーザに最新が届くのは少し先になるんじゃないの？ってのを心配されてるのかな。

> goの将来のユーザにとって、vimに含まれているのは有望じゃないかな

それはもちろん同意。

> goから直接プラグインが提供できないならvimに取り込むためにforkするかも

駄目だとは言って無いし、どちらかと言えば心配されてる感じ。

**Comment by koron** [comment]
> netrw とか phpcomplete とか pythoncomplete とか....

それらはメンテナが更新しないからだよねw

> それぞれのタイミングでエンドユーザに最新が届くのは少し先になるんじゃないの？

加えて vim にバンドルされているのが古くて go にとって害になる可能性も考えているかも。憶測だけど。

**Comment by Shougo** [comment]
> それらはメンテナが更新しないからだよねw

アップストリームが存在する場合は、そこから自動的に更新できるような仕組みが欲しいですね。
そのためにはパッケージ管理システムのような仕組みが必要だと思いますが……。
そういう方面からもVim標準のパッケージ管理システムの必要性は言えるかもしれません。

現在でもたまにVimのruntime fileの更新がありますが、あれはどういう仕組みで最新版が送付されているんでしょうか。
ちょっと私はよくわかっていません。

**Comment by koron** [comment]
vim-jp として本件にどう関わっていくか、そろそろ判断しよう。
-   オリジナルメンテナを説得していく
-   vim-jp で fork してそちらのメンテナということで vim-dev へ推す
-   めんどうなのでやめる

選択肢はこのくらいかな。

**Comment by mattn** [comment]
- オフィシャル配布物として同梱された
- 補助プラグインとして vim-go-extra を公開した

この2点により本件closeします。
