### ISSUE TITLE
1.0[0] で「"E695: Cannot index a Funcref」が出る。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#376]
https://gist.github.com/5495114

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/Xf-yMrRSpeo/cYfDn65olrwJ

**Comment by k-takata** [comment]
todo入りしています。

> Patch to avoid wrong error message for 1.0[0]. (Yasuhiro Matsumoto, 2013 May
> 1)

**Comment by h-east** [comment]
Patch 7.3.1181 で取り込まれました。Yeah!
https://groups.google.com/d/msg/vim_dev/tIs-HzEiQMM/KfaYlrk6z44J
