### ISSUE TITLE
:xmap と :smap のコマンドライン補完が存在しない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#377]
とりあえず報告だけ。
すみません。

**Comment by ynkdir** [comment]
報告しました。

https://groups.google.com/d/msg/vim_dev/-m5UzVFpt7o/OJawnsILa38J

**Comment by tyru** [comment]
ありがとうございます！
2013/05/05 17:50 "Yukihiro Nakadaira" notifications@github.com:

**Comment by ynkdir** [comment]
7.3.931 で修正されました。
