### ISSUE TITLE
malloc()を使った関数に __attribute__((alloc_size)) を付けるようにすべき？

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#378]
Vimでも`_FORTIFY_SOURCE`はコンパイル時に付けてますが、`__attribute__((alloc_size))`を使わないと`malloc()`ではなく、`malloc()`をラップした関数を使ってる場合検出してくれないらしいです。
Vimでも`alloc():src/misc2.c`等の関数が当てはまるので、gccでコンパイルしてる場合はつけた方がいいのではないでしょうか。
### 参考記事

[`__attribute__(alloc_size)` を使わないと`_FORTIFY_SOURCE` を活かせないよ。という話](http://mkosaki.blog46.fc2.com/blog-entry-1228.html)

**Comment by tyru** [comment]
タイトルが分かりにくかったので変更。

前：Vimでも `__attribute__((alloc_size))` を使うようにすべき？
後：malloc()を使った関数に `__attribute__((alloc_size))` を付けるようにすべき？

**Comment by k-takata** [comment]
参考までに、Rubyでの対応方法:
http://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=40572&view=revision

Vimの場合、cprotoを使ってプロトタイプ宣言 (*.pro) を自動生成していますが、どうやって __attribute__ を付けるかというのが問題かもしれません。
cprotoが __attribute__ をどう扱うのか分かりませんが、Makefileの中で、自動生成後にsedでも使って付けるのがいいんですかね？

**Comment by tyru** [comment]
すいません、ちなみに未だにcprotoとかVimのconfigure, Makefile周りが分かってないので私は対応不可能です...orz

**Comment by tyru** [comment]
報告してみました。
https://groups.google.com/group/vim_dev/browse_thread/thread/b43caf2d923ec0a?hl=ja

**Comment by Shougo** [comment]
tyru++;

**Comment by k-takata** [comment]
Bram氏から、無駄だよーとの返事。

https://groups.google.com/d/msg/vim_dev/C0PK8tkj7Ao/6_2ltrASU9YJ

> Please don't waste time on it.  For Vim _FORTIFY_SOURCE doesn't really
> work.  There are many structures that are allocated larger than they are
> defined.  It will just be a lot of work to create false alarms.

本当に無駄なのかというのはちょっと気になりますが。

**Comment by tyru** [comment]
ふむ。とりあえず回答はもらえたので閉じます。

2013/05/13 2:22 "K.Takata" notifications@github.com:

**Comment by koron** [comment]
提案したけど、既に通った道で無駄だとわかっていた、故に wontfix とした。
