### ISSUE TITLE
ファイルマーク(A-Z)が :delmarks A-Z しても :wviminfo で復活してしまう

### ISSUE THREAD

**Issue by DeaR** [vim-jp/issues#379]
タイトルの通りですが、880や892で実装されたviminfoのmergeにより
delmarksでファイルマーク(A-Z)が消す事が出来なくなりました
※無名バッファで対象のマークを上書きすれば消せるといえば消せる
　また、普通のマーク(a-z)はmergeじゃなく上書きのようで消える
##### 簡単な再現手順

``` vim
:mark A
:marks A
  mark   行   列 ファイル/テキスト
   A      0    0 ~/.vimrc

:wviminfo
:delmarks A
:marks A
  E283: "A" に該当するマークがありません

:wviminfo
:marks A
  mark   行   列 ファイル/テキスト
   A      0    0 ~/.vimrc
```

**Comment by ynkdir** [comment]
その動作は意図的らしいです。
消したいときは :wviminfo! するといいみたいです。

[BugReport] Mark deletion doesnt persist between Vim sessions
https://groups.google.com/d/msg/vim_dev/kre4oyzMRDU/twin224WTQsJ

**Comment by DeaR** [comment]
なるほど。納得しました:+1:

**Comment by h-east** [comment]
> その動作は意図的らしいです。

あら、そうだったのですか。今晩辺りpatch書こうかと思ってました。汗。
ちょっと気になっているのは、そのスレッドは7.3.880(viminfo merge動作搭載)前の話なので
after 7.3.880だとまた話が違ってくるんじゃないかなぁ、と思ったりしました。
まぁ、ええっかｗ。

**Comment by k-takata** [comment]
[8.2.0050](https://github.com/vim/vim/commit/8cd6cd8087ccf08e4303dbf5f732fc4b82b917e1) でタイムスタンプを見て消すようになった模様。
