### ISSUE TITLE
Vim scriptにBoolean型を追加する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#38]
これはかなり地味な変更ですが……。

Vim scriptにはBoolean型が現状ありません。
そこで1か0で代用することになるのですが、そうすると、
foo(1)やfoo(0)などとなってソースコードが見づらくなります。

kanaさんなどはそれを嫌って、
foo(s:TRUE), foo(s:FALSE)などを定義しています。
が、これは標準ではないので、いちいち定義するのが面倒です。

互換性を確保するため、v:true, v:falseを定義するのはどうでしょうか。1, 0に変換されます。
変数が増えるだけなので、それほど大きな変更にもなりません。

**Comment by koron** [comment]
基本的な着想は良い。変更量も手頃。説得材料にはやや欠けるか。
もしかしたら本体よりは標準スクリプトライブラリの仕事かも。

注意点として、TRUEであることを調べる時にv:trueとの直接比較ってのはやるべきではない。
というのはCでは一般的に0=FALSE、not zero=TRUEのため-1だったりする場合があり
この場合v:true(1)との==比較だと決してマッチしない。

そういう問題を助長しかねないところが懸念点。

**Comment by koron** [comment]
本来ならチェックまで関数化するところですがね。

**Comment by Shougo** [comment]
確かに、そういう問題はありますね。
true == not falseですからね。

**Comment by mattn** [comment]
ちょっと余談だけど const は欲しいと思った事がある。

```
const false = 0
const true = !false
```

**Comment by Shougo** [comment]
あー、確かにKanaさんとかはスクリプト中で定数を定義するようにしていますからね。
なかなか面白いのではないのでしょうか。

**Comment by koron** [comment]
constの話とBoolean型は別なので、constが必要なら別にissue建ててください。

でboolean型を導入するとしてメリットあるかなぁ? 予想される「intの運用で回避できるからいらん」というのを覆せるだけの何か。
それがなければFar FutureのMilestoneに分類するか、そもそもinvalidとして閉じるかっていう判断も必要かなと。

**Comment by mattn** [comment]
可読性だけの問題ならばclose。JSON互換性とか、その変まで詳しくissueとして上げられるならば残す。
というのでどうでしょ。

**Comment by Shougo** [comment]
ふーむ。他の応用ができるかどうかということですね。

**Comment by koron** [comment]
とりあえず有効な応用がでるまでFar Futureに分類しましょう。

**Comment by Shougo** [comment]
はい。

**Comment by k-takata** [comment]
JSON対応の一環で `v:true`, `v:false`が入りました。閉じていいですかね？

**Comment by koron** [comment]
閉じましょ。
