### ISSUE TITLE
正規表現の高速化パッチを検証する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#380]
7.4 に入りそうな正規表現の高速化パッチに、
マルチバイト的な問題がないか検証してください。

https://code.google.com/p/vim-soc2008-regexp/

締め切りは 7.4 に間に合わせるなら今月中です。

**Comment by mattn** [comment]
ビルド中

**Comment by mattn** [comment]
mignwでビルドとおらん

**Comment by mattn** [comment]
動いた。でも落ちる。

**Comment by koron** [comment]
うはw

**Comment by koron** [comment]
SoC (しかも5年前) だからかなーw

**Comment by mattn** [comment]
コード読んだけど、一応マルチバイト意識してくれてるっぽい。

**Comment by koron** [comment]
追加修正の必要なし?

**Comment by mattn** [comment]
regexp.c の差分

https://gist.github.com/5545669

**Comment by mattn** [comment]
regexp_nfa.c 読んでる。

**Comment by mattn** [comment]
あー、ありえるNFA作っちゃおうぜ大作戦なのか。

**Comment by koron** [comment]
NFAを追加して、入力された正規表現によって元々のDFAと振り分ける感じ?

**Comment by mattn** [comment]
んーこわいなーw

**Comment by koron** [comment]
落ちそう的な意味で?

**Comment by mattn** [comment]
- マルチバイト考慮の漏れ
- Bramのマージ失敗
- 最近入ったregexp.cパッチのデグレード

などなど。

**Comment by koron** [comment]
とりあえず我々でいじくり回してrevise版作って提出するしかないんじゃない?
でなきゃ反対して却下してもらうか。

**Comment by mattn** [comment]
https://code.google.com/p/vim-soc2008-regexp/source/browse/wiki/Regexp_Interface_Both_Engines.wiki?spec=svn2&r=2

**Comment by mattn** [comment]
進化としては良いと思ってる。あとそれほど大きなパッチじゃないけど月末までは足りないわ。

**Comment by mattn** [comment]
ひーーーww

https://code.google.com/p/vim-soc2008-regexp/wiki/nfa_bugs

**Comment by koron** [comment]
www

「問題あるし我々で直すよ」って言う?
「もしくは7.4に入れるのは待って」?

**Comment by mattn** [comment]
ひとまず動かんよとは報告しました。

**Comment by koron** [comment]
見ましたw

参ったねどうも。
正規表現が速くなるなら欲しいけど
あと2週間くらいであれをマルチバイト化&目立ったバグが無いようにできるかしらね?

@k-takata さんの感想が聞きたいところ。

**Comment by k-takata** [comment]
> NFAを追加して、入力された正規表現によって元々のDFAと振り分ける感じ?

元々のはDFAではなく、バックトラック型NFAだと思います。

> あと2週間くらいであれをマルチバイト化&目立ったバグが無いようにできるかしらね?

2週間は無理じゃないですか？ まだほとんど見ていませんが(ぉぃ

ところで、最終的なコードはどれなんでしょう。 [svn/trunk/vim72-re](https://code.google.com/p/vim-soc2008-regexp/source/browse/#svn%2Ftrunk%2Fvim72-re) 以下を見ればいいんですかね。

**Comment by k-takata** [comment]
svn を使うのがつらいので、 https://github.com/k-takata/vim-soc2008-regexp にコピーを作りました。
`git diff vim72 vim72-re` でこのパッチの差分が見れます。master ブランチでインデント等を修正しています。

**Comment by mattn** [comment]
++

**Comment by k-takata** [comment]
ようやく Vim 7.3.929 ベースで、VC10 でコンパイルが通るようになりました。
https://bitbucket.org/k_takata/vim-soc2008-regexp-mq/src/438636dfa7c6faa41b5f1281c7a931f6938c64df/vim-soc2008-regexp.diff?at=default

test64 を動かしてみましたが、いくつかエラーが出ています。

```
224c224
< ERROR: pat: "[^[=a=]]\+", text: "ddaﾃ｣ﾃ｢bcd", match: "aﾃ", expected: "dd"
---
> OK - [^[=a=]]\+
230,231c230,231
< ERROR: pat: "[[:alpha:][=a=]]\+", text: "879 aiaﾃ｣ﾃ｢aiuvna ", match: "aia", expected: "aiaﾃ｣ﾃ｢aiuvna"
< ERROR: pat: "[[=a=]]\+", text: "ddaﾃ｣ﾃ｢bcd", match: "a", expected: "aﾃ｣ﾃ｢"
---
> OK - [[:alpha:][=a=]]\+
> OK - [[=a=]]\+
234c234
< ERROR: pat: "[犧｡[:alpha:][=a=]]\+", text: "879 aiaﾃ｣犧｡ﾃ｢犧｡aiuvna ", match: "aia", expected: "aiaﾃ｣犧｡ﾃ｢犧｡aiuvna"
---
> OK - [犧｡[:alpha:][=a=]]\+
```

`enc=utf-8` になっていないのでは、という疑いがありますが、未確認。

**Comment by k-takata** [comment]
一旦投げました。
https://groups.google.com/d/msg/vim_dev/ZWWgK9aXQ2Y/JdA7TK4EvBcJ

**Comment by k-takata** [comment]
> enc=utf-8 になっていないのでは、という疑いがありますが、未確認。

test64.in に `:set enc=utf-8` を追加したところ、パスしました。

**Comment by k-takata** [comment]
> - マルチバイト考慮の漏れ
> - 最近入ったregexp.cパッチのデグレード

やはり心配なのはこの辺りですかね。
enc != utf-8 の場合の動作の確認も必要でしょうね。（not utf8 だと従来のエンジンを使っているのかもしれませんが。）
あとは、7.2 以降に入った regexp.c への変更内容を精査して、regexp_nfa.c にも反映が必要かを確認するべきなのでしょうが…

**Comment by koron** [comment]
:+1:

メールで返信送ったのにgithubに反映されてないことがあるのか… (´・ω・`)

**Comment by k-takata** [comment]
enc=utf-8 と enc=cp932 で簡単に試してみたところ、一応マルチバイト文字には対応しているようで、少なくとも文字の一部にマッチしたりすることはありませんでした。
例えば、enc=cp932 で "瑞草" (90 90 91 90) に "髄" (90 91) はマッチしませんでした。

これを試している際に、`\%xab` や `\%uabcd` といった文字コードの指定が、無効化されていることに気づきました。
https://github.com/k-takata/vim-soc2008-regexp/commit/961e4e448f31f4a24ac4b0d3318296d6ec81142c#L3L690
1つ前のコミットで文字コード指定に対応しているのをなぜ無効化したのかはよく分かりません。

**Comment by koron** [comment]
検証してレポートはしてくれたわけだから、もう閉じますね。

**Comment by Shougo** [comment]
そういえば、このパッチはどの程度高速化に効果があるのかデータはないんでしょうか？
Bram氏がいれようと思うくらいなので、よほどのインパクトがあるはずなのですが……。

**Comment by k-takata** [comment]
全然中身は理解していませんが、[Regular Expression Matching Can Be Simple And Fast](http://swtch.com/~rsc/regexp/regexp1.html) が言うところの Thompson NFA と同様の実装なんだと思います。
このページによると、a?<sup>n</sup>a<sup>n</sup> を a<sup>n</sup> にマッチさせる場合、バックトラック型エンジンでは時間が指数関数的に増大しますが、Thompson NFA だと線形です。（n=29 で1分 vs. 20μ秒）

今回の新エンジンの測定結果は知りませんが、パターンによっては逆に新エンジンの方が2倍くらい遅い場合もあると、Bram氏が言っていましたね。

**Comment by Shougo** [comment]
調べてみると、Thompson NFAは一般的なパターンで高速になるようです。よく使われるパターンが高速になるなら、一部遅くなるのは仕方ないかなと思います。

**Comment by k-takata** [comment]
7.3.970 (+7.3.973) に入ってしまいました。
https://groups.google.com/d/topic/vim_dev/niZ0QTP1ucw/discussion
# 翻訳しないといけないメッセージがまた増えた…

**Comment by Shougo** [comment]
> 7.3.970 (+7.3.973) に入ってしまいました。

なぜ7.4aにならなかったんだろう……。
不具合を見つける上では本体に入れたほうが効率が良いというのもわかるんですが、今回の場合混乱が増えるような気がしますね。
