### ISSUE TITLE
Kaoriya 版 Vim で Ruby 1.9.3 の DLL が読み込まれない

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#381]
Kaoriya 版の仕様なのか Vim の不具合なのかが分からなかったのでこちらに書かせてもらいます。

Ruby 1.9.3p194 をインストールしている状態で`:ruby puts RUBY_VERSION`を行うと

``` vim
E370: ライブラリ msvcrt-ruby200.dll をロードできませんでした
E266: このコマンドは無効です,ごめんなさい: Rubyライブラリをロードできませんでした.
```

と出力され、if_ruby が使用出来ませんでした。
（Ruby 2.0 をインストールしている状態では問題なく使用する事が出来ました。

Ruby 2.0 ではなくて Ruby 1.9.3 を使用する方法はあるのでしょか？
- 環境
  - Kaoriya 版 Vim 7.3.923
  - WindowsXP SP3
  - Ruby 1.9.3p194 と Ruby 2.0p0
- 状況

``` vim
" Ruby 1.9.3 の場合
echo has("ruby")
" => 0
ruby puts RUBY_VERSION
" => E370:～（上の書いたエラー）
" -----------------------------------------------------------------
" Ruby 2.0 の場合
echo has("ruby")
" => 1
ruby puts RUBY_VERSION
" => 2.0.0
```

また Vim 7.3.918 では Ruby 1.9.3 と Ruby 2.0 の両方の環境で問題なく動作しました。

**Comment by Shougo** [comment]
http://www.kaoriya.net/blog/2013/04/28/

それはここに書いてある話だと思うので、Kaoairya版の仕様ではないでしょうか。

**Comment by osyo-manga** [comment]
なるほど。
RubyInstaller 版を試してみます。

**Comment by osyo-manga** [comment]
あー RubyInstaller 版を使用すれば Ruby 1.9.3 でも問題ないと思ったけど最新版の KaoriyaVim だと Ruby 2.0 じゃないとダメなのかな…。
うむむ…。

**Comment by Shougo** [comment]
コンパイルした時に対応するバージョンは確定するので、Ruby 2.0用にコンパイルした場合はRuby 1.9では動作しないはず。

**Comment by osyo-manga** [comment]
ふむ、なるほど理解しました。
ありがとうございました:)
