### ISSUE TITLE
7.4 に向けたメッセージの修正

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#382]
7.4 リリースに向けて私が管理している各種日本語メッセージファイルに対して
要望・提案があったら書いてください。
- メッセージの翻訳
  - `src/ja.po`
  - `src/ja.sjis.po`
- メニューの翻訳
  - `runtime/lang/menu_ja_jp.utf-8.vim`
  - `runtime/lang/menu_ja_jp.euc-jp.vim`
  - `runtime/lang/menu_japanese_japan.932.vim`

遅くとも来週末には Bram に送るのでその範囲でおさまる作業量のものだけの採用となることを
あらかじめご承知おきください。

**Comment by koron** [comment]
**すでに決めてること**
- メニューの翻訳からは「エンコード指定」を削除します。

**Comment by k-takata** [comment]
スペルチェック有効時に出るポップアップメニューが日本語化されていないことに気づきました。
![popup-spell](https://f.cloud.github.com/assets/840186/492406/22c6a518-baa6-11e2-9d39-359ba315c838.png)
menu.vimの中で動的に生成しているようなので、簡単に対応できそうにはなさそうな気もしますが。

**Comment by koron** [comment]
> menu.vimの中で動的に生成しているようなので、簡単に対応できそうにはなさそうな気もしますが。

(´・ω・`)

**Comment by k-takata** [comment]
> (´・ω・`)

menu.vim の 888行目辺りからごちゃごちゃやっていますが、私にはよく分かりませんでした。

> メニューの翻訳からは「エンコード指定」を削除します。

どういう理由でしょうか？

**Comment by koron** [comment]
> > メニューの翻訳からは「エンコード指定」を削除します。
> 
> どういう理由でしょうか？
- メニュー翻訳において新しい項目を追加することは本来想定されていない
- 追加していたことで過去に問題を起こしたことがあった
- 今となっては個別プラグインで提供すべきような内容

というところでしょうか。

**Comment by koron** [comment]
> 今となっては個別プラグインで提供すべきような内容

ということで切り出してみた。
メニュー項目の位置が変わったけど、これで十分じゃなかろうか。

https://gist.github.com/koron/5562203

**Comment by msmhrt** [comment]
各種日本語メッセージファイルの現時点の最新版は、本家のリポジトリのファイルでしょうか？
もっと新しいファイルを公開しているようでしたら場所を教えてください。

**Comment by koron** [comment]
@msmhrt ほとんど本家レポジトリと差分はありませんが https://bitbucket.org/koron/vim-kaoriya-patches ここのMQレポジトリを本家レポジトリに適用してください。

面倒くさければ kaoriya版の最新バイナリから取り出したほうが速いでしょう。

**Comment by msmhrt** [comment]
了解です。
念のためカタカナの表記揺れを確認してみます。

**Comment by msmhrt** [comment]
大丈夫そうですね。
vimdoc-ja の方で外来語の表記ルールの話題があったと思いますけど、あれは特に進展してないですよね？

**Comment by koron** [comment]
Issue #384 で ja.sjis.po を消すことを画策中。あっちは間に合わないかも。

**Comment by koron** [comment]
関連して Issue #364 で ja.po を UTF-8 にしちゃうことも画策中。こっちは無理やりねじ込めるか?

**Comment by koron** [comment]
いや #364 はこのタイミングがベストか。Makefileもいじるから。

**Comment by koron** [comment]
現時点のパッチ。
- [4902-fix_translations_ja-vim74.diff](https://bitbucket.org/koron/vim-kaoriya-patches/src/45863396b0be2965db47a736b5168b341947f2b0/4902-fix_translations_ja-vim74.diff?at=default)
- [4903-utf8_japo.diff](https://bitbucket.org/koron/vim-kaoriya-patches/src/45863396b0be2965db47a736b5168b341947f2b0/4903-utf8_japo.diff?at=default)

うまくまとめて送るつもり。

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/7fR2Z--YJSE/fUe3eJayU0oJ

送った。

> うまくまとめて送るつもり。

まとめたが、うまくはなかったw

**Comment by koron** [comment]
7.3.969 までの間にPython絡みで結構追加があった。
この先7.4がリリースされるまでさらに増える可能性があるので、
このIssueは閉じないで置いときます。

**Comment by k-takata** [comment]
NFA正規表現エンジン絡みで追加がありますね。

**Comment by koron** [comment]
今の文言、そもそも最終版じゃないよね…

**Comment by k-takata** [comment]
7.4 がリリースされましたので閉じますか？

> スペルチェック有効時に出るポップアップメニューが日本語化されていないことに気づきました。

これ、どうしよう。

**Comment by koron** [comment]
> > スペルチェック有効時に出るポップアップメニューが日本語化されていないことに気づきました。
> 
> これ、どうしよう。

別途 Issue 建ててください。
