### ISSUE TITLE
mapした n を実行した場合に折り畳みが開かれない

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#383]
#### 環境

fedora 17 (x86_64)
Vim 7.3.931
#### 再現手順

``` vim
vim -N -u NONE -i NONE --noplugin -c "nnoremap s n"
```

``` vim
4Oabc<ESC> ← カーソルのある行の上に abc という4行を追加。
kzfk ← 2～3行目を折り畳む(folding)。
gg ← カーソルを1行目に移動。
/c ← カーソルが1行目の c の位置に移動する。
n ← 再検索。折り畳みが開かれ、カーソルが1行目の c の位置に移動する。(※1)

zm ← 2～3行目を再度折り畳む。
gg ← カーソルを1行目に移動。
s ← n をmapしたキーで再検索。カーソルが1行目の c の位置に移動する。
s ← n をmapしたキーで再検索。折り畳みは開かれず、カーソルは折り畳まれた行の先頭に移動する。(※2)
```
#### 現象

オリジナルの n (※1)と mapした n (※2)で折り畳みに対する挙動が異なる。
mapした n の場合でも折り畳みは開かれるべきではなかろうか？
それともなんか変な仕様とかあったっけ？

**Comment by mattn** [comment]
ソースレベルですが、foldの展開にはkeytyped(本当にキーが押されたかどうか)が必要だった気がします(負荷対策?)。
feedkeys だと展開されるんじゃないかと思います。(ただしい対処かどうかは別として)

**Comment by tyru** [comment]
どんな時に折り畳みを開閉するか決めるfoldopen, foldcloseってオプションありませんでしたっけ？
2013/05/14 13:28 "mattn" notifications@github.com:

**Comment by DeaR** [comment]
helpの `'foldopen'` の所にしっかり書いとりますね

> NOTE: コマンドがマッピングの一部として実行されたときは、このオプション
> は使われない。同じ効果を得るには、マッピングにコマンド |zv| を加えるこ
> と。
> (理由: 折り畳みを開くかどうかはマッピング自身でコントロールできたほう
> がいい)

**Comment by tyru** [comment]
なるほど >理由

**Comment by h-east** [comment]
@DeaR thanks!

あぁ！ `'foldopen'オプションに指定されたキーワードに属する`コマンドがマッピングの一部として実行されたときは～
ということか。

``` vim
set foldopen?
  foldopen=block,hor,mark,percent,quickfix,search,tag,undo
```

n コマンドは`foldopen`オプションにデフォルトで指定されているキーワード searchに属しているから、 mapしたn は折り畳みが開かれないのは仕様ということですね。
納得です。
