### ISSUE TITLE
ja.sjis.po ってまだ要るのかなぁ?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#384]
いやそもそも何に使ってるんだっけ?

**Comment by koron** [comment]
> # Note: ja.sjis, *.cp1250 and zh_CN.cp936 are only for MS-Windows, they are
> # not installed on Unix

Windowsで必要と書いてあるがもはやよくわからない。
おそらくWindowsでgettextだけ入っててiconvが入ってない状況を想定してのことだとは思う。
でもgettextがiconvに依存しているのは、少なくとも日本語圏ではもう鉄板と言って良いのではないか。

**Comment by mattn** [comment]
断定するのは危険だな。

**Comment by koron** [comment]
7.4 で外すのは無理にしても、どういう意図で存在しているのかは確認しておきたいです。
なんで足したんだっけ?

**Comment by mattn** [comment]
> なんで足したんだっけ?

↑でkoronさんが言ってる様に gettext.dll、intl.dll、が libiconv.dll や iconv.dll を使ってない場合があるからですね。古い win32 unix 環境使ってる人だとなかなか dll を更新できない事は多いかな。あと人によっては windows で LANG=ja.SJIS もしくは LANG=ja_JP.SJIS してる人もいるのであながち外せないかも。
変換できない状態でも正しく出せるし、変換しても正しく出せるなら残す理由になるかと思います。

**Comment by koron** [comment]
> windows で LANG=ja.SJIS もしくは LANG=ja_JP.SJIS してる人

これは gettext が iconv を使ってれば救えるのでは?

**Comment by mattn** [comment]
> これは gettext が iconv を使ってれば救えるのでは?

フォルダ runtime/lang/ja/ で utf-8 のとバッティングするかと。

**Comment by koron** [comment]
ん? どういうこと?
まっつんさんは「こういうケースは動かないかも」と示してくれていると思うんだけど、
そのケースがよくわからない。

さっき気がついたんだけどkaoriya版はeuc-jpなvim.mo配っててw、
でもiconvのおかげでcp932でもutf-8でもちゃんと動いているみたい。
だからgettext+iconvさえしっかりしていれば
vim.moの文字コードはなんでも良いと考えてます。

**Comment by mattn** [comment]
僕がそうだったんだけど、gettext.dll の dll を依存の関係で更新できないままでいて、runtime/ja/LC_MESSAGES/vim.mo を自分で生成してたんです。その時の gettext.dll は iconv.dll 非依存で、ja.sjis.po を使う必要がありました。
つい最近までそのPC使ってたので、世の中まだ使ってる人いるんじゃないかなーと思った次第。

**Comment by koron** [comment]
了解。とりあえず想像通りではあるし、外すことを7.4で提案するのはやめときましょう。

> runtime/ja/LC_MESSAGES/vim.mo を自分で生成し

これ、できる&やる人、日本にどのくらいいるのかなぁ…w

**Comment by koron** [comment]
残すことにしたので閉じます。

**Comment by koron** [comment]
これ ja.po (utf-8) だけにしたい、という意味。
(なんか他の場所でも見た気がする)
年々 エンコード別のを保持する意味は低くなっているので backlog にします。

**Comment by k-takata** [comment]
> (なんか他の場所でも見た気がする)

https://github.com/vim-jp/lang-ja/issues/38#issuecomment-178615847
