### ISSUE TITLE
第一候補を自動選択しない補完オプションの提案

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#385]
現在のインサートモード補完は`<C-x><C-u>`などを押した時に必ず第一候補が選択されます。
しかし、それを選択しないオプションがあっても良いはずです。

私はcompleteselectというオプションにより、その挙動を変えられるようにすることを提案します。

例：
completeselect=0 : 第一候補を選択し、挿入する。`<C-x><C-u>`と同じ挙動
completeselect=1 : 第一候補を選択する。`<C-x><C-u><C-p><Down>`と同じ挙動
completeselect=2 : 第一候補を選択しない。`<C-x><C-u><C-p>`と同じ挙動

時間が無いですが、5/31までにパッチを送付するのを目標にします。

**Comment by koron** [comment]
反対ではないけど実装するほど賛成でもないので私は no touch で。

**Comment by Shougo** [comment]
この機能は私が提案しているので、私が実装する方向で考えています。

自分に対してassignしておきました。

**Comment by Shougo** [comment]
今 edit.c中の補完の実装をチェックしています。`ins_complete()`が補完の実装のようですね。
その中の5378行目付近ins_completion_next()が候補の選択処理のように見えます。

`ins_complete()`は補完の処理を全て担っているように見えます。Ctrl-x mode時のキーの処理が全てこちらへ行くので。

**Comment by Shougo** [comment]
ある程度ソースコードはわかるようになって来ましたが、どこを修正すればよいかについてはまだ把握しきれていません。

**Comment by ujihisa** [comment]
+1

**Comment by DeaR** [comment]
作業したのでhttps://gist.github.com/DeaR/5652245
取り敢えずオプションは良くわからないので実処理部分だけですが

L4617付近の
`#define COMPLETE_SELECT 0` で

> completeselect=none : 第一候補を選択しない。`<C-x><C-u><C-p>`同じ挙動

`#define COMPLETE_SELECT 1` で

> completeselect=select : 第一候補を選択する。`<C-x><C-u><C-p><Down>`と同じ挙動

`#define COMPLETE_SELECT 2` 等の0と1以外の値で

> completeselect=insert : 第一候補を選択し、挿入する。`<C-x><C-u>`と同じ挙動

正直、`#define COMPLETE_SELECT 1`の際の処理は微妙感MAX

---

注：7.3.969のソースで作業した

**Comment by Shougo** [comment]
ありがとうございます！

> 取り敢えずオプションは良くわからないので実処理部分だけですが

オプションの追加方法はわかるので、そこは私が作業します。

ちょっとパッチをチェックさせてもらいますね。

> 注：7.3.969のソースで作業した

最新版でも動くかチェックさせてもらいます。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5654189

オプションを使用するようにして書き直しました。Vim 7.3.1029で動作確認済みです。

既知の問題点：
- completeselect=2が動いていない
- ドキュメントがまだない

**Comment by Shougo** [comment]
そもそも、元のパッチにcompleteselect=2相当の処理が無いような……。@DeaRさん、確認してもらえませんか？

**Comment by DeaR** [comment]
> そもそも、元のパッチにcompleteselect=2相当の処理が無いような……。

あれ？ そもそも現行処理が `第一候補を選択し、挿入する。` なのでは？

あとパッと見ですが下記の方が良いかと思います
特にstartedは1でないと色々マズいです
(動作確認は昼くらいには何とか出来ると思います)

``` diff
- started = (p_cselect == 1) ? compl_started : 0;
+ started = (p_cselect == 1) ? compl_started : 1;
```

``` diff
- if (p_cselect == 1) {
- if (started)
- compl_enter_selects = !insert_match && compl_match_array != NULL;
- else
- compl_enter_selects = compl_match_array != NULL;
- } else {
- compl_enter_selects = !insert_match && compl_match_array != NULL;
- }
+ if (started)
+ compl_enter_selects = !insert_match && compl_match_array != NULL;
+ else
+ compl_enter_selects = compl_match_array != NULL;
```

**Comment by Shougo** [comment]
> あれ？ そもそも現行処理が 第一候補を選択し、挿入する。 なのでは？

ああ、そういうことか……。だとすると、もうちょっといじらないとまずそうですね。

**Comment by Shougo** [comment]
候補の挿入互換性を守るため、このオプションの初期値を 0 にして、0のときの挙動を「候補の選択・挿入あり」にしようかと思っています。
上記の修正を試して見ましたが、0のときと2のときの挙動が同じに見える…（候補の挿入・選択がされない）

**Comment by Shougo** [comment]
@DeaRさんの修正を取り込みました。ドキュメントを修正しました。

既知の問題点：
completeselect=0が動いていない（第一候補の挿入・選択がなされない）

ドキュメントに関しても、これで良いのかコメントを頂きたいです。

**Comment by DeaR** [comment]
確認しました

https://gist.github.com/Shougo/5654189#file-i385-diff-L89
`ins_compl_delete();`が残ってます
(残っていると1の時の挙動が変になるので削除)

https://gist.github.com/Shougo/5654189#file-i385-diff-L70
`if (p_cselect != 2 && advance)` で0と2が逆転する
(docは逆転しているが実処理部分がそのままになってる)

> ドキュメントに関しても、これで良いのかコメントを頂きたいです。

説明不足感が否めないですが、私の英語力では役立てそうにないです…:astonished:

**Comment by Shougo** [comment]
上記の修正を試して見ましたが、
1. completeselect=0のとき、`<C-x><C-p>`が2番目の候補を選択・挿入する（本来は1番目の候補になるべき）
2. completeselect=1のとき、`<C-x><C-p>`が2番目の候補を選択する（本来は1番目の候補になるべき）
3. completeselect=2のとき、`<C-x><C-p>`は何も選択しない（仕様通りの挙動）

でした。

とりあえず、gistは更新しました
https://gist.github.com/Shougo/5654189

> 説明不足感が否めないですが、私の英語力では役立てそうにないです…:astonished:

ujihisaさんを呼んでくるしかないですかね？

**Comment by Shougo** [comment]
もしかして`<C-x><C-p>`で最後の候補が選択されるのはそういう仕様？
`<C-x><C-n>`はちゃんと動きました。

それにしても候補が一つしかないときの`<C-x><C-p>`の動作は変なような気がする。
=> あ、再現しなくなった……。

**Comment by Shougo** [comment]
パッチを試してくれる人柱とドキュメントをレビューしてくれる人を募集しています。

neocomplcacheもこのオプションに対応させてみようかな。

**Comment by DeaR** [comment]
> あれ、もしかして`<C-x><C-p>`で最後の候補が選択されるのはそういう仕様？

みたいですね

> それにしても候補が一つしかないときの<C-x><C-p>の動作は変なような気がする……。

こちらでも確認
ちと処理を追って対策考えてみます

**Comment by Shougo** [comment]
はい。よろしくお願いします。

**Comment by DeaR** [comment]
`completeselect=0` の時は現行そのままの処理なので割愛するとして

`completeselect=1` や `completeselect=2` 時に候補が1つの際はどういう動きが良いのだろう？
`completeopt` の `menuone` も関わってきます
- `menuone` を無視し、挿入は行わずにメニューを出す(これは多分簡単)
- `completeselect` を無視し、挿入を行う(`num_matches` の取得タイミングをずらしたりと色々怖くなりそう)

**Comment by Shougo** [comment]
completeselect=1のとき、候補を挿入せず選択するだけ
completeselect=2のとき、メニューを出すだけ

とできませんか？

**Comment by Shougo** [comment]
うーん、やはり候補が一つの時、completeselect=1の挙動がおかしいですね……。

**Comment by DeaR** [comment]
> うーん、やはり候補が一つの時、completeselect=1の挙動がおかしいですね……。

まだ今の単語自体が候補に並ぶというバグ有りですが
L4868くらい

``` diff
        vungetc(c);
        }
    }
     }
-    if (compl_pending != 0 && !got_int)
+    if (compl_pending != 0 && !got_int && p_cselect != 1)
     {
    int todo = compl_pending > 0 ? compl_pending : -compl_pending;

    compl_pending = 0;
```

**Comment by Shougo** [comment]
修正ありがとうございます。取り込んでおきます。

> まだ今の単語自体が候補に並ぶというバグ有りですが

これ、Vim側の仕様なんですかね？
neocomplcacheでは補完関数内で除外しています。正直必要ないんですが……

ちょっと質問。neocomplcacheの自動補完を呼ぶときに一時的にcompleteselectを書き換えて、completefunc側で復元するということを考えています。何かおかしくなる可能性はありますでしょうか。

**Comment by DeaR** [comment]
> completeselect=1のとき、候補を挿入せず選択するだけ
> completeselect=2のとき、メニューを出すだけ

L2870付近

``` diff
     int        cur = -1;
     colnr_T    col;
     int        lead_len = 0;

-     if (!pum_wanted() || !pum_enough_matches())
+     if ((!pum_wanted() || !pum_enough_matches()) && p_cselect == 0)
    return;

 #if defined(FEAT_EVAL)
     /* Dirty hard-coded hack: remove any matchparen highlighting. */
```

**Comment by Shougo** [comment]
ありがとうございます。こちらも取り込んでおきます。

**Comment by DeaR** [comment]
> > まだ今の単語自体が候補に並ぶというバグ有りですが
> 
> これ、Vim側の仕様なんですかね？

`completeselect=2` はそもそも方向を0にする事(増減する所をskip)で対応できたので問題なかったが
`completeselect=1` は本来 現在単語を削除→マッチ単語を追加 のような作業が発生している所をskipさせてる為
削除されていない現在単語も検索に引っ掛かってしまう、といった原因だと思います、多分。

**Comment by Shougo** [comment]
ふむふむ。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5654189

パッチを更新しました。neocomplcacheをcompleteselect対応させてみましたが、こちらの意図通りに動作するようになりました。

**Comment by ujihisa** [comment]
召喚されました。ドキュメントあとで確認しときます

**Comment by Shougo** [comment]
よろしくお願いします。neocomplcache(ver.8.1)の動作確認もおねがいします。

今回の更新で、completeselectオプションが有効ならcomplete_check()を使用できるようにしました。
擬似的な非同期補完が使用できます。自動補完の動作も安定するはずです。

**Comment by DeaR** [comment]
https://gist.github.com/DeaR/5652245
思いのほか変更点が多くなったのでこっちで更新
(以前変更してた部分が要らなくなった)
よく考えれば別に現在単語を追加させれば良かっただけでした

次は `:help ins-completion` に載ってる一通りの補完を確認しないとですね
# 基本、NeoComplCache任せで `<C-X><C-U>` と `<C-X><C-O>` しか使った事無かったです…

**Comment by Shougo** [comment]
ありがとうございます。
とりあえず、こちらでも動くことを確認しました。

**Comment by Shougo** [comment]
@DeaR さん
近々、一度vim_devにパッチを投げてみる予定ですがパッチのクレジット表記はどうしましょうか。

**Comment by DeaR** [comment]
> 近々、一度vim_devにパッチを投げてみる予定ですがパッチのクレジット表記はどうしましょうか。

お任せします
敢えて言うならfull nameではないどころか、本名でなくHNなのでどうなんだろう…

**Comment by Shougo** [comment]
本名を出したくないのなら、私単独で名前を出しますが……。ハンドルネームを無理にパッチのクレジットに入れてもBram氏のポリシー的にややこしくなりそうなので。

**Comment by Shougo** [comment]
@DeaR さんはこれまでにパッチを出したことはありましたっけ。その時はどうしていましたか？

**Comment by DeaR** [comment]
> 本名を出したくないのなら、私単独で名前を出しますが……。

それでお願いします。
絶対的に駄目というわけではないですが、ずっとネットでは匿名でやってきてたので

> @DeaR さんはこれまでにパッチを出したことはありましたっけ。その時はどうしていましたか？

#67 で1回出しましたけどBram氏からは返信も無くスルーされましたね
(ファイルサイズとかも守ってなかったので尚更)

**Comment by Shougo** [comment]
Oh....

発起人は私ですし、パッチ自体は私単独で出しましょう。

**Comment by thinca** [comment]
ちなみに私は thinca って名前でクレジットされてますね。
https://code.google.com/p/vim/source/detail?name=v7-3-488
https://code.google.com/p/vim/source/detail?name=v7-3-516

**Comment by mattn** [comment]
苗字が Thinca で名前が Manbou です。

**Comment by Shougo** [comment]
なるほど……

**Comment by Shougo** [comment]
Vim7.4が出る前にパッチを出したいので、明日の夜にvim_devにパッチを提出予定です。なにか問題があれば今のうちに報告をおねがいします。

**Comment by Shougo** [comment]
https://groups.google.com/forum/#!topic/vim_dev/tVsk0pdOGvs

vim_devにパッチを提出しました。Vim 7.4に入ると良いですが、ギリギリなのでわかりません。

**Comment by Shougo** [comment]
vim_devのパッチをsyntax/vim.vimに追加するように更新しました。

https://gist.github.com/Shougo/5654189

**Comment by DeaR** [comment]
https://groups.google.com/d/msg/vim_dev/tVsk0pdOGvs/xjSeZo4h5FoJ

> From your description, I think I'd rather see this as an additional value or values supported in 'completeopt'.
> Currently the only control over what gets inserted is "longest".
> If it's there, only part of the match text gets inserted, otherwise, the whole first match gets inserted.
> Why not add a "noinsert" or something, and maybe a "noselect"?

に対応させてみた
https://gist.github.com/DeaR/5652245
ちなみに`noinsert`と`noselect`が両方指定された場合は`noselect`で動く

**Comment by Shougo** [comment]
ありがとうございます。こちらで試してみてからパッチを送ることにしますね。

**Comment by Shougo** [comment]
動作を確認できたので、アップデートしたパッチを投稿しました。diffが小さくなったので、なかなかよいと思います。

**Comment by Shougo** [comment]
neocompleteを新パッチに対応させました。

**Comment by h-east** [comment]
なんかいろいろムカついてきた。

**Comment by mattn** [comment]
おっと... 東様を怒らせてしまったようだな。

**Comment by Shougo** [comment]
> なんかいろいろムカついてきた。

Patchのauthorの件でしょうか。確かに、私もこの場合どうするべきなのか決めかねています。
良い案があればぜひ教えてください。

**Comment by Shougo** [comment]
私としても本来の作者である@DeaR さんの名前は出したいのですが、この場合ハンドルネームをどう扱うべきかが難しいのです。

**Comment by h-east** [comment]
そっち(patch authorの件)もあるけどそれよりも↓だよ。

> neocompleteを新パッチに対応させました。

ここ(vim-jp/issues)では君のプロダクトの動向はどうでもいい。というか関係ない。
自分の所でやってくれ。mattnさんにも何回か突っ込まれてるでしょ。
ワザとか？

**Comment by Shougo** [comment]
> ここ(vim-jp/issues)では君のプロダクトの動向はどうでもいい。というか関係ない。
> 自分の所でやってくれ。mattnさんにも何回か突っ込まれてるでしょ。

確かに、ここはvim-jpのIssueなので、自分のプロダクトの変更を載せるのは適切ではありませんでした。
申し訳ありません。次からは気をつけます。

> ワザとか？

確かに私は無意識のうちに不適切な行為を行なっていましたが、ワザと（他人を不快にさせるために）やっていた訳ではないことは分かって欲しいです。

**Comment by Shougo** [comment]
neocompleteの話題は上記スレッドに分離させました。

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/tVsk0pdOGvs/Kx1CfxayTAkJ

> Don’t know how it is useful, but don’t use magic numbers here. Possible values should be something like “select,insert”, “select” or just empty string. With error or no-op with just “insert” (nothing selected=nothing to insert) and +=/-= support.

返信があったけれど、これはどういう意味だろう。

"noinsert", "noselect"というよくわからない名前ではなく、"insert","select"というオプションをサポートしたほうが良いのでは、という意見かな。気持ちはわかる。

ただ、これだと

```
set completeopt=menuone,preview
```

のような設定を.vimrcに書いていた場合、今までと挙動が異なるので、互換性を壊すことになる。

**Comment by DeaR** [comment]
> > Don’t know how it is useful, but don’t use magic numbers here. 

`compl_select_type` が下記のマジックナンバーで制御されてる件ですね

> 0: select & insert
> 1: noinsert
> 2: noselect

**Comment by zhaocai** [comment]
how about `autoinsert` and `autoselect` instead of `noinsert` and `noselect`? Add `autoinsert, autoselect` to the default of `completeopt` to keep compatibility.

**Comment by Shougo** [comment]
整数オプションだった時の名残ですね。文字列に変換するのは私の手元でもできるかと思います。
どうしますか？

@DeaR これが正式に取り込まれた際は、パッチ作者として名前を入れたいので、名前を考えてもらえませんか。

@zhaocai Thanks!

**Comment by Shougo** [comment]
この件は、手元でもやってみます。

**Comment by h-east** [comment]
@Shougo 了解しました。迅速な対応ありがとうございました。

**Comment by Shougo** [comment]
> how about autoinsert and autoselect instead of noinsert and noselect? Add autoinsert, autoselect to the default of completeopt to keep compatibility.

It seems good name. But, "autoinsert" is default behavior. This change breaks compatibility.

**Comment by zhaocai** [comment]
> It seems good name. But, "autoinsert" is default behavior. This change breaks compatibility.

Add `autoinsert,autoselect` to the default of `completeopt` to keep compatibility.

**Comment by Shougo** [comment]
> Add autoinsert,autoselect to the default of completeopt to keep compatibility.

No. Users can customize option value. I don't change default behavior.

**Comment by DeaR** [comment]
> 整数オプションだった時の名残ですね。文字列に変換するのは私の手元でもできるかと思います。
> どうしますか？

`compl_select_type` を `compl_no_insert` と `compl_no_select` に分割する感じかなと
但し両方TRUEで今の処理のままだと誤動作するので注意
作業準備はしてあるのでどちらでも構わないです

> これが正式に取り込まれた際は、パッチ作者として名前を入れたいので、名前を考えてもらえませんか。

やはり本名の封印(?)を解かざるを得ないですかね？:worried:

**Comment by zhaocai** [comment]
> No. Users can customize option value. I don't change default behavior.

the original value of `completeopt` is `menu,preview`; now `menu,preview,autoinsert,autoselect`. It will produce the same compatible behavior.

( `noinsert`) `set completeopt-=autoinsert` to disable `autoinsert`:

**Comment by Shougo** [comment]
> やはり本名の封印(?)を解かざるを得ないですかね:worried:

thincaさんのようにIdentityがあるのなら本名じゃなくて仮の名前でも良いです。

> ( noinsert) set completeopt-=autoinsert to disable autoinsert: 

Yes. But, if users uses below settings, it will break backward compatibility.

```
set completeopt=preview
```

**Comment by Shougo** [comment]
> compl_select_type を compl_no_insert と compl_no_select に分割する感じかなと
> 但し両方TRUEで今の処理のままだと誤動作するので注意
> 作業準備はしてあるのでどちらでも構わないです

なるほど。そちらのほうが良さそうですね。
この程度の作業なら、私の方でやります。

**Comment by zhaocai** [comment]
> Yes. But, if users uses below settings, it will break backward compatibility.

```
set completeopt=preview
```

Is it really necessary to keep 100% backward compatibility? To add preview, the setting should be 

```
set completeopt+=preview
```

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5654189

パッチをアップデートしました。変数をcompl_no_insert, compl_no_selectに分割しました。

**Comment by Shougo** [comment]
> Is it really necessary to keep 100% backward compatibility? To add preview, the setting should be 

I think it is "yes".

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/tVsk0pdOGvs/wKuYTZzgkZwJ

> Sorry, missed this part of the discussion when writing my previous reply.

ZyX氏が言っていたのは内部実装の話ではなかったんですね。
整数オプション時代の仕様の話をしていたようです。
とはいえ、ソースコード中にマジックナンバーを埋め込むのは良くないですが……。

**Comment by DeaR** [comment]
> thincaさんのようにIdentityがあるのなら本名じゃなくて仮の名前でも良いです。

まぁ `DeaR` は一般英単語と同じ綴り故に微妙なのは確かですね
ある程度個人特定させやすいHNは `nayuri aohime` くらいですね(twitterやGmailで使ってるので)

> パッチをアップデートしました。変数をcompl_no_insert, compl_no_selectに分割しました。

なんかtagsが出力されてますね

> とはいえ、ソースコード中にマジックナンバーを埋め込むのは良くないですが……。

同意

**Comment by Shougo** [comment]
> まぁ DeaR は一般英単語と同じ綴り故に微妙なのは確かですね
> ある程度個人特定させやすいHNは nayuri aohime くらいですね(twitterやGmailで使ってるので)

分かりました。その名前を使いましょう。
さて、MLではどのようにすればいいかな……。

> なんかtagsが出力されてますね

あ、確かに……。なんでだろう。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5654189

tags を除外しました。

**Comment by Shougo** [comment]
@DeaR これで問題なければ、パッチをアップデートしてvim_devに提出しようと思いますがどうでしょうか。

https://twitter.com/nayuri_aohime/status/340357002733707264

この件のフォローもしておきたいところですね。

**Comment by DeaR** [comment]
> 分かりました。その名前を使いましょう。

余談ですがweb検索だと `github nayuri` より `github dear` とかの方が見つけやすかったりします
(`nayuri` は一部アカウント名にしか使って無い為)

# thincaさんやZyXさんの様に vim online にもDeaRで登録しとけばいけそうな気もしなくもないとか考えた:stuck_out_tongue_closed_eyes:

> このフォローもしておきたいところですね。

jedi-vimのくだり以外は下記と大体同じじゃないですかね

> Yes. But, if users uses below settings, it will break backward compatibility.

**Comment by Shougo** [comment]
> # thincaさんやZyXさんの様に vim online にもDeaRで登録しとけばいけそうな気もしなくもないとか考えた:stuck_out_tongue_closed_eyes:

それはあるかもしれませんね。（そういえば、ZyX氏の本名を知らない……。パッチではどうなっていたかな）
パッチに使う名前と普段使っているハンドルネームが違う人も多いので、あまり気にしなくても良いとは思います。

> jedi-vimのくだり以外は下記と大体同じじゃないですかね

そうですが、具体例を上げたほうがわかりやすいのではないかと思いました。
あとは、互換性を気にするVimの文化も。

**Comment by DeaR** [comment]
> そういえば、ZyX氏の本名を知らない……。パッチではどうなっていたかな

同じく。
vim onlineやパッチでは`ZyX`、githubでは`ZyX-l`みたいですね

> そうですが、具体例を上げたほうがわかりやすいのではないかと思いました。
> あとは、互換性を気にするVimの文化も。

確かに。
`jedi-vim`に限ればそれを直せば済むとはいえ、
githubで`completeopt`で検索するだけで直接設定してる物がいっぱい出てきますしね:astonished:

**Comment by Shougo** [comment]
> 同じく。
> vim onlineやパッチではZyX、githubではZyX-lみたいですね

そうなんですね。このハンドルネームは問題ないのかな……。

> 確かに。
> jedi-vimに限ればそれを直せば済むとはいえ、
> githubでcompleteoptで検索するだけで直接設定してる物がいっぱい出てきますしね:astonished:

はい。ちょっとその阿鼻叫喚をどうにかできるとは到底思えないです。

問題ないなら、今から新しいものを提出します。

**Comment by DeaR** [comment]
>  vim online にもDeaRで登録

取り敢えずどちらの名前でも大丈夫な感じで作成しておきました
http://www.vim.org/account/profile.php?user_id=66623

**Comment by Shougo** [comment]
ありがとうございます。メール中にもそのアドレスを参照するようにします。

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/tVsk0pdOGvs/fCzBbPkA4w0J

投稿しました。これで分かってもらえるかな……。

**Comment by Shougo** [comment]
Marc Weber氏がパッチのリストを作っていたので、このパッチもリストに加えてもらえるよう頼んでみました。

https://groups.google.com/forum/#!topic/vim_dev/PUmHYrdO2YU
http://vim-wiki.mawercer.de/wiki/vim-development/recent-work.html

**Comment by Shougo** [comment]
@DeaR neocompleteとこのパッチとの絡みで、調べたい挙動があるのですが、以下のスレッドで原因の解明に協力してもらえないでしょうか。

https://github.com/Shougo/neocomplete.vim/issues/3

**Comment by 0xBADDCAFE** [comment]
私はコマンドラインモードの代替でコマンドラインウィンドウを使っているのですが、`:cd`する際などに
ファイル名を見るため一旦`<TAB>`する(`set wildmode=list`的な使い方)ことが多くあり、この場合
第一候補が自動で補完されてしまうと以降絞り込みができず、不便に感じています。

この Issue で議論している機能では、こういったケースでも機能するでしょうか。
もしそれが可能であれば、コマンドラインウインドウで`set wildmode=list`相当の機能を実現するという
意味でもこの機能は有用に感じます。

**Comment by Shougo** [comment]
> この Issue で議論している機能では、こういったケースでも機能するでしょうか。

機能します。

> もしそれが可能であれば、コマンドラインウインドウでset wildmode=list相当の機能を実現するという
> 意味でもこの機能は有用に感じます。

応援してくれるのは嬉しいです。しかし、ここではともかく、vim_devでの反応が意外と薄かったんですよね……。

**Comment by Shougo** [comment]
Vim7.4.103でこのパッチを使用しているとSEGVします。
Vimのソースなど、巨大なファイルを編集していると起こりやすいようです。
パッチを適用解除したところ安定しました。最近補完関連のパッチが入ったので競合しているかも知れません。
Vim7.4.66では問題ありませんでした。
@DeaR さん、確認してもらえないでしょうか。

**Comment by Shougo** [comment]
本日、このパッチがtodoリストに入っていることを確認しました。
Bram氏は一応チェックしているようです。
ただ、今のバージョンのVimで問題が起きないか私が確認できていないので、このissueはまだオープンしておきます。
問題がないことを確認できたらcloseします。

**Comment by Shougo** [comment]
現在、自分のVimを最新版にし、このパッチを利用しながら様子を見ています。
何事もなければよいのですが……。

**Comment by Shougo** [comment]
ちなみに、todo.txt の該当行は以下です。

```
Patch to add 'completeselect' option.  Specifies how to select a candidate in
insert completion. (Shougo, 2013 May 29)
Update to add to existing 'completeopt'. 2013 May 30
```

**Comment by Shougo** [comment]
パッチを有効にしてしばらく使っていましたが、問題ないようです。
todoリストにも入っていますし、一度closeします

**Comment by Shougo** [comment]
Vim 7.4.775

https://groups.google.com/forum/#!topic/vim_dev/9BGZNGA7Ucg
