### ISSUE TITLE
7.4 リリースに向けて不具合発見時の対処を考えよう。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#387]
7.4そろそろ近いですね。
不具合発見したらまず報告するフェーズに入るのはどうかというのを認識合わせたい。

**Comment by koron** [comment]
> まず **vim-dev へ** 報告する

ね? 賛成。

とりあえず #386 をか。

**Comment by Shougo** [comment]
今回は7.4aが出るのではなくて、なぜか突然7.3本体に機能追加パッチが入っているような気がするのですが……。

**Comment by k-takata** [comment]
無事 7.4 がリリースされましたので、閉じたいと思います。
https://groups.google.com/d/msg/vim_dev/knOQ_t_H5to/gIBNilbv8t4J
