### ISSUE TITLE
Windows で起動時に $HOME\vimfiles\plugin\*.vim~ が読み込まれる

### ISSUE THREAD

**Issue by msmhrt** [vim-jp/issues#389]
【発生環境】
Vim: KaoriYa版 7.3.969 (2013/05/19版)
OS: Windows 7 Starter 32bit版

【概要】
- Vim の起動時に`$HOME\vimfiles\plugin\test.vim~`というファイルが存在すると、拡張子が`.vim`ではないのに、なぜか読み込まれてしまう。
- 同じディレクトリ内に`test.vim`が存在すれば、`test.vim~`は読み込まれない。
- `*.vim~`だけでなく、`*.vimmar`等のファイルも同様に読み込まれる。
- `test.vim~`と`test.vimmer`がどちらも存在する場合は、両方とも読み込まれる。
- `*.vim.bak`等は読み込まれない。

【確認手順】
1. `$HOME\vimfiles\plugin\` に、`test.vim*`が存在しないことを確認する
2. `$HOME\vimfiles\plugin\` に、空ファイル`test.vim~`を置く
3. Vim を起動して`:scriptnames`で確認すると、`~\vimfiles\plugin\test.vim~`が読み込まれている
4. Vim を終了する
5. `$HOME\vimfiles\plugin\`に、空ファイル`test.vim.bak`を置く
6. Vim を起動して`:scriptnames`で確認すると、`~\vimfiles\plugin\test.vim~`だけが読み込まれている
7. Vim を終了する
8. `$HOME\vimfiles\plugin\`に、空ファイル`test.vimmer`を置く
9. Vim を起動して`:scriptnames`で確認すると、`~\vimfiles\plugin\test.vim~`と`~\vimfiles\plugin\test.vimmer`の両方が読み込まれている
10. Vim を終了する
11. `$HOME\vimfiles\plugin\`に、空ファイル`test.vim`を置く
12. Vim を起動して`:scriptnames`で確認すると、`~\vimfiles\plugin\test.vim`だけが読み込まれている

【その他】
- 今のところ Windows でしか再現できない
- `$HOME\vimfiles\plugin\` だけでなく、`$HOME\vimfiles\after\plugin\` でも再現する
- Vim を `vim -u NORC -N` で起動しても再現する

**Comment by koron** [comment]
追試の結果

`~/vimfiles/plugin/*.vim` が1つでもあれば `~/vimfiles/plugin/*.vim~` は読み込まれない。
すなわち `~/vimfiles/plugin/*.vim~` しか無いときに読み込まれる。

ということが判明。glob関連かな?

**Comment by ynkdir** [comment]
#68

**Comment by koron** [comment]
duplicated #68, closed.

**Comment by ynkdir** [comment]
なにやら WIndows の次世代ファイルシステムの ReFS (windows8に搭載されたんですか？) はショートファイル名はないらしいのであと数年で気にしなくてもよくなるーとなればいいですね

**Comment by thinca** [comment]
Win8 ユーザですが、NTFS使ってますね。

**Comment by ynkdir** [comment]
まあ今でも無効化はできるので試してみるのもいいかもしれません
なかなか怖いですが
