### ISSUE TITLE
sidを取得する汎用的な方法がない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#39]
現在のVim scriptでは、sid（実行中のスクリプトID）を簡単に取得できません。
これは不便なので、多くのプラグインが

function! s:SID_PREFIX()
  return matchstr(expand('<sfile>'), '<SNR>\d+_\zeSID_PREFIX$')
endfunction

のようなHackを駆使しています。
もちろんこれでも良いのですが、この手法だとソースコード内に毎回記述することになり煩雑となります。
getsid()のような関数を用意したいところです。

**Comment by koron** [comment]
+1 これは簡単に取り込まれんじゃない?

**Comment by Shougo** [comment]
後は誰が実装するか、ですよね。
簡単そうなら、私がやってみたいところですけど……。

**Comment by koron** [comment]
直感は簡単だとささやいてます。
とりあえず @Shougo さんにassignしときますね。

**Comment by Shougo** [comment]
了解しました。

**Comment by tyru** [comment]
https://gist.github.com/1256877
@Shougoさんがassignされてますが、ちょっと気になったので実装してしまいました。

**Comment by koron** [comment]
@tyruさん:
31行目と32行目を一行で書かない理由はありますか?
なければスタイルを合わせるために一行にしておいたほうが良いでしょう。
あとdocumentのdiffも欲しいですね。

**Comment by tyru** [comment]
@koronさん レビューありがとうございます。修正しました＆document追加しました。

**Comment by koron** [comment]
Great! vim_devに new feature proposal として送るべき。

**Comment by tyru** [comment]
送りました。
https://groups.google.com/group/vim_dev/browse_thread/thread/aeb82e920aacfda5?hl=ja

**Comment by mattn** [comment]
assign変えました。

**Comment by tyru** [comment]
Bramさんこのパッチの有用性がわからないためにみんなの反応をうかがってるように見える...
Vimscripterとしては書く量が減って便利だと思うんですが...

**Comment by ynkdir** [comment]
私もよくわかんないです。
ヘルプにハック載せとくよりはいいと思いますが。

**Comment by tyru** [comment]
うーむ...まぁ確かに新しいVimでしか使えないし(慣れたので)`s:SID()`でいいとは思うんですが...必須って訳じゃない気もしますね...(自分でパッチ作っといて

**Comment by mattn** [comment]
7.4行きという事かな？

**Comment by tyru** [comment]
7.4で取り込まれるならそれでもいい気がしますねー。
ついでにいろいろVimスクリプトがもうちょっと便利になるような変更も取り込んでほしいです。(必須ではないにしろ)

**Comment by ynkdir** [comment]
`getsid()` より `expand('<sid>')` のほうが一貫性的によさそうかなーという感想を持ちました。
まあどっちもどっちですけどねー。

**Comment by h-east** [comment]
なるほどです。

(This is joke)
では <code>expand('<nancy>')</code> で何を返せば愉しくなるでしょうかね？＾＾；

**Comment by ynkdir** [comment]
既出だったみたいです。

`expand("<SID>")`
http://tech.groups.yahoo.com/group/vimdev/message/27703

むー、gmane にはこのへんのログはないのか。

これ以降も sid の話題がたまに出てて却下かスルーかされてる感じですね。

**Comment by mattn** [comment]
@h-east 僕のvimだと

```
:echo expand('<nancy>')
sex pistols
```

って出ました。

**Comment by mattn** [comment]
あれかな。bramはスクリプト書きじゃないから存在意義が伝わってないんだと思う。

**Comment by Shougo** [comment]
やっぱりBramさんはVim script書いてないんですね。
本体の保守で精一杯なんだろうなぁ。

**Comment by h-east** [comment]
@mattn△cool.

**Comment by ujihisa** [comment]
expand('またMa')

**Comment by h-east** [comment]
todoリスト入り。

> Patch to add getsid(). (Tyru, 2011 Oct 2)  Do we want this?  Update Oct 4.
> Or use expand('<sid>')?

**Comment by Shougo** [comment]
お、これは期待！

**Comment by h-east** [comment]
@Shougo 日付を見てもらえれば分かりますがtodoリストに入ったのは去年です。
今、新設ラベル `xlose/todolisted` でissueを整理中なのです。
