### ISSUE TITLE
NFAエンジンを直そう

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#391]
#390 より分離。あちらは報告、こちらは直すほうをめざす。

NFAエンジンに対して以下のいずれかを目指す
-   徹底的に叩いて、直して使えるようにする
-   ~~徹底的に叩いて、不具合報告で押しつぶして 7.3 からは取下げさせる(もしくはデフォルトをBTエンジンに切り替えさせる)~~

~~いずれにせよ再現しやすい例を示したほうが良い。~~

---

~~#386 から残っている問題~~ 残課題:
- 優先度: 高
  -  ~~`[[:cntrl:]]` にマルチバイト文字がマッチする。~~
  -  ~~幾らかのプラグインで誤動作が見られる(Vimに付属のものが引っかかってくれると嬉しい)~~
  - ~~`[[:alpha:]]` とかの判定がおかしい。 `check_char_class()` の中で、マルチバイト文字もお構いなしに `isalpha()` などに放り込んでる。~~
  - ~~`\%u` 等のコード指定が無効化されている。~~
  - ~~`*` がアスタリスク文字として判断するというVim仕様が引き継がれていない。~~
  - utf-8時に文字列内の `\xFF` がパターン `\xFF` でマッチしない。
- 優先度: 低
  - ~~`if (*regparse == 'n' || *regparse == 'n')`~~
  - ~~test64 にマルチバイトのテストが混ざっている。~~
  - ~~test95 が enc=utf-8 以外だと通らない。~~

**Comment by mattn** [comment]
動作していないパターン: @k-takata さんより

コメント中に not supported などと書いてあるもの。
`\_[` `\~` `\1`～`\9` `\z1`～`\z9` `\z(` `\%d` `\%o` `\%x` `\%u` `\%U` `\%^` `\%$` `\%#` `\%V` `\%#` `\@!` `\@<` `\@>`、その他 `\%` 系

`\1`～`\9` などの後方参照は、バックトラックじゃないと無理なんでしょうが。

**Comment by mattn** [comment]
僕はまず `\#%` と `\%33c` と `\33l` 治しますね。

**Comment by mattn** [comment]
`\#%` は治った。

**Comment by mattn** [comment]
これパラメータのpush/popはNFAのだとどうやるんだろ。既に分かってる人いたら教えて。

**Comment by h-east** [comment]
お疲れ様です。

> - `if (*regparse == 'n' || *regparse == 'n')`

7.3.1001 で修正されました。
https://groups.google.com/d/msg/vim_dev/ImIrTS-EvZI/WB9DdOVtdewJ

> - test95 が enc=utf-8 以外だと通らない。

7.3.986 で修正されました。
https://groups.google.com/d/msg/vim_dev/kqygPi6Dmrc/pmPTGEr6QA4J

**Comment by k-takata** [comment]
> 7.3.986 で修正されました。
> https://groups.google.com/d/msg/vim_dev/kqygPi6Dmrc/pmPTGEr6QA4J

自分の環境 (Windows) だと https://github.com/vim-jp/issues/issues/390#issuecomment-18203569 に書いたとおり、7.3.986 でもエラーが出ていたのですが、enc=utf-8 以外で通らないのとは別件と判明しました。
`\i` がWindowsとそれ以外で違っていました。

```
                                                *'isident'* *'isi'*
'isident' 'isi'         string  (default for MS-DOS, Win32 and OS/2:
                                           "@,48-57,_,128-167,224-235"
                                otherwise: "@,48-57,_,192-255")
```

どうしてWindowsとそれ以外が違っているのかが分かっていないので、どう直すべきかもよく分かりません。

**Comment by h-east** [comment]
@k-takata すんません。あちらのコメント見逃してました。
Windowsでもそれ以外でも同じ結果になるようにtestを変更する感じでしょうかね？

**Comment by h-east** [comment]
https://github.com/vim-jp/issues/issues/390#issuecomment-18258869 と https://github.com/vim-jp/issues/issues/390#issuecomment-18265092 は↓のpatchで直る。make testもALL DONE。
でも、これが正しいのか自信はない。

``` diff
--- a/src/regexp_nfa.c  Tue May 21 22:38:18 2013 +0200
+++ b/src/regexp_nfa.c  Wed May 22 17:56:05 2013 +0900
@@ -2931,8 +2931,10 @@
            c = *reginput;
            n = 1;
        }
-       if (c == NUL)
+       if (c == NUL) {
            n = 0;
+           reginput_updated = FALSE;
+       }

        /* swap lists */
        thislist = &list[flag];
```

**Comment by h-east** [comment]
自信はないけど問題提起も兼ねてvim_devにpatch送りました。
https://groups.google.com/d/msg/vim_dev/ec71SWian0I/wEVPRmyQAUMJ

**Comment by k-takata** [comment]
:+1:

**Comment by Shougo** [comment]
@h-east ++;

**Comment by mattn** [comment]
:+1:

**Comment by mattn** [comment]
ひとまず第一弾。

https://gist.github.com/mattn/5626661

`\%#` と `\%23c`, `\%<23c`, `\%>23c` が治ったはず。もうちょいテストが必要。

**Comment by mattn** [comment]
今回使った方法を使えばたぶん後方参照出来る気がする。

**Comment by Shougo** [comment]
！

どんどんNFAエンジンが実用的に。
`set re=0`で常用できる日は近いですね。

**Comment by h-east** [comment]
@mattn 乙です。帰ったら試すす。

**Comment by mattn** [comment]
syntax/html.vim が使ってるの、これで揃ったから前のスレの https://gist.github.com/mattn/5619512 が速くなる予定だったんだけど、まだ何か残ってるらしい。まったく速くならない。

**Comment by mattn** [comment]
あー `\_[` かー。

**Comment by koron** [comment]
# たまには https://github.com/vim-jp/vim のことも思い出してあげてください (´・ω・`)

**Comment by k-takata** [comment]
https://gist.github.com/mattn/5626661#file-gistfile1-diff-L87
s を間接参照したあとで、 if (s == NULL) してるのは順番の入れ替えが必要ですね。

**Comment by k-takata** [comment]
> 自信はないけど問題提起も兼ねてvim_devにpatch送りました。

改行関連の問題は違った形で修正されたようです。(7.3.1005)
https://groups.google.com/d/topic/vim_dev/3Zh1R5X4tVs/discussion

**Comment by h-east** [comment]
@k-takata Thanks!
vim_devに「7.3.1005でもまだ直ってないぞ(ﾟДﾟ)ｺﾞﾙｧ!!」と言ってる人がいますが、彼の勘違いだと思う:smile:

**Comment by Shougo** [comment]
> 改行関連の問題は違った形で修正されたようです。(7.3.1005)

了解です。バージョンアップしたら、`set re=0`で使い続けてみます。

**Comment by k-takata** [comment]
> どうしてWindowsとそれ以外が違っているのかが分かっていないので、どう直すべきかもよく分かりません。

Windows は cp437、それ以外は iso-8859-1 を元に `'isident'` の値が決められているようですね。
結局test95 には修正すべき点が3つ見つかりました。
1. `set nocp` して `set nomore` してないせいで、テストの途中で入力待ちになってしまう。
2. `§` (0xa7) が Windows で `\i` にマッチしてしまう。`¨` (0xa8) にでも変える？
3. `\f\+` と `\%#=1\f\+` で違いがないことを確認するはずがなぜか `\i` になっている。

``` diff
--- a/src/testdir/test95.in
+++ b/src/testdir/test95.in
@@ -7,7 +7,7 @@
 STARTTEST
 :so small.vim
 :so mbyte.vim
-:set nocp encoding=utf-8 viminfo+=nviminfo
+:set nocp encoding=utf-8 viminfo+=nviminfo nomore
 :" tl is a List of Lists with:
 :"    regexp pattern
 :"    text to test the pattern on
@@ -30,10 +30,10 @@
 :call add(tl, ['\p\+', 'ìa', 'ìa'])

 :"""" Test recognition of some character classes
-:call add(tl, ['\i\+', '&*§xx ', 'xx'])
-:call add(tl, ['\%#=1\i\+', '&*§xx ', 'xx'])
+:call add(tl, ['\i\+', '&*¨xx ', 'xx'])
+:call add(tl, ['\%#=1\i\+', '&*¨xx ', 'xx'])
 :call add(tl, ['\f\+', '&*fname ', 'fname'])
-:call add(tl, ['\%#=1\i\+', '&*fname ', 'fname'])
+:call add(tl, ['\%#=1\f\+', '&*fname ', 'fname'])

 :"""" Combining different tests and features
 :call add(tl, ['[^[=a=]]\+', 'ddaãâbcd', 'dd'])
diff --git a/src/testdir/test95.ok b/src/testdir/test95.ok
--- a/src/testdir/test95.ok
+++ b/src/testdir/test95.ok
@@ -8,5 +8,5 @@
 OK - \i\+
 OK - \%#=1\i\+
 OK - \f\+
-OK - \%#=1\i\+
+OK - \%#=1\f\+
 OK - [^[=a=]]\+
```

**Comment by h-east** [comment]
@k-takata :+1: 
そういえば昨日make test した時に途中で入力待ちになってたので、スペースキーをポンと叩いた気がするw

**Comment by mattn** [comment]
> スペースキーをポンと叩いた気がするw

w

**Comment by mattn** [comment]
長いhtmlがre=1より遅くなってるんだけどなんだろな。

**Comment by mattn** [comment]
疲れたので一旦出しました。
https://groups.google.com/d/msg/vim_dev/ec71SWian0I/9fhj3Fck8F4J

**Comment by k-takata** [comment]
test95の修正を投げました。
https://groups.google.com/d/topic/vim_dev/xLnxuNnH22I/discussion

**Comment by k-takata** [comment]
test95の修正は、7.3.1008で取り込まれました。
https://groups.google.com/d/topic/vim_dev/VPM7RNwzCgs/discussion

……よく見たら、nomoreの修正が取り込まれてない。

**Comment by mattn** [comment]
w

**Comment by k-takata** [comment]
> ……よく見たら、nomoreの修正が取り込まれてない。

7.3.1010で取り込まれました。
https://groups.google.com/d/topic/vim_dev/FQFYZ2VNEo4/discussion

**Comment by mattn** [comment]
テスト書くので苦しんでる

**Comment by koron** [comment]
@mattn 苦しみの原因は量的なところ? それとも技術的なところ?

**Comment by msmhrt** [comment]
与えた正規表現の内部表現を知る手段がデバッグ出力以外にないっぽいのが辛いとか？

**Comment by mattn** [comment]
`\%#` なのでカーソル位置を作るのがめんどくさい、というところ。

**Comment by mattn** [comment]
https://gist.github.com/mattn/5654549

こんなの書いたけど、うまく動かない。

**Comment by Shougo** [comment]
> \%# なのでカーソル位置を作るのがめんどくさい、というところ。

`call cursor()`を使うのはダメでしょうか。`call setpos()`でもほとんど同じとは思います。

**Comment by mattn** [comment]
問題はそこではなかったのですでにパッチ送りました。

**Comment by h-east** [comment]
Patch 7.3.1039 で @mattn さんのpatchが取り込まれました。
(新エンジンへの `\%4l` とか `\%>4l` とか `\%<4l` とかの対応にBram氏が `\%4c` とか `\%4v` とかの対応を足したやつ)
https://groups.google.com/d/msg/vim_dev/JfbTedtmSuc/W-oP9pQh2OkJ

**Comment by mattn** [comment]
> (新エンジンへの \%4l とか \%>4l とか \%<4l とかの対応にBram氏が \%4c とか \%4v とかの対応を足したやつ)

対応は僕のほうでやってたんだけど、僕が今後の為にステートに2値保持するようにしてたのを1値で置き換えられた、という結果ですね。
まぁいいかー的な。

**Comment by mattn** [comment]
冒頭文書き換えました。

**Comment by mattn** [comment]
上記の2点が片付いたら、いったんこのissueを閉じようと思います。

**Comment by msmhrt** [comment]
> 上記の2点が片付いたら、いったんこのissueを閉じようと思います。

3点のTYPO?

**Comment by mattn** [comment]
3点です

**Comment by crazymaster** [comment]
https://groups.google.com/d/msg/vim_dev/MGxxB4UpH3w/ilFLxMS1LdwJ
Bram氏のチューニング力すごい

**Comment by mattn** [comment]
Bramの｢Regexp engine work｣をvim-jpで翻訳したいと思っていますが、やってみたいという希望者がいればお願いします。
作業がバッティングしない様、先に名乗り出て貰えると助かります。

半日くらい希望者居なければ僕やります。

https://groups.google.com/d/msg/vim_dev/YOnT1yHMHUI/uugIVzc2D9AJ

On 6/9/13, master notifications@github.com wrote:

> https://groups.google.com/d/msg/vim_dev/MGxxB4UpH3w/ilFLxMS1LdwJ
> Bram氏のチューニング力すごい
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/391#issuecomment-19165586

## 
- Yasuhiro Matsumoto

**Comment by koron** [comment]
> Bramの｢Regexp engine work｣

U・R・L! U・R・L! (画像自重

**Comment by koron** [comment]
Word が re=1 で 0.49、チューニング後の re=2 で 2.31 と遅くなってるのは
今まではstrcmp一発みたいな感じだったのが、状態マシンを辿るようになったからかしらね…
触るメモリが広くなった的な意味で。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/YOnT1yHMHUI/uugIVzc2D9AJ

**Comment by mattn** [comment]
これ、本題関係なくてすまそなコメントなんだけど、ここ数日でre=0でちょっぱやになってない？かなりビビるわ。もうそろそろre=2で置き換える日が来るんじゃない?w

**Comment by Shougo** [comment]
はい。私も昨日になって、Vimがやたらと高速になったのに気づきました。
しばらくは比較のために残るのでしょうが、`set regexpengine=1`が廃止になる日も近いですね。

**Comment by mattn** [comment]
希望者が居なかったので｢Regexp engine work｣の翻訳、ポストしときました。

**Comment by crazymaster** [comment]
:+1:

**Comment by koron** [comment]
です・ます調への統一、ワーディング、あとtypoの修正しときました。

**Comment by mattn** [comment]
あざます

**Comment by tyru** [comment]
ちょっとだけワーディング(って「言い回し」って意味なんですね)とtypoの修正しました。

**Comment by mattn** [comment]
あざます。`:` は意図的でしたがどっちゃでもいいです。

**Comment by tyru** [comment]
すみません、syntaxのせいで見づらくて`.`に見えて、「。と表記ゆれしてるなー」と思って変えたんですが、その後気付いてすぐ直しました。

**Comment by mattn** [comment]
いえいえ

**Comment by ynkdir** [comment]
> \%u 等のコード指定が無効化されている。

fixed by 7.3.1019

> `*` がアスタリスク文字として判断するというVim仕様が引き継がれていない。

fixed by 7.3.1087

で ok ですか

**Comment by k-takata** [comment]
7.4 が出たことですので、閉じたいと思います。
以降は個別 issue にしましょう。
