### ISSUE TITLE
Vimが挿入モードのまま操作不能になることがある

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#393]
これはかなり前から気づいていましたが、忘れないように書いておきます。

タイトルの通り、Vimが挿入モードのまま操作不能になることがあります。詳しい発生条件は不明です。
症状としては、Vimが挿入モードのままになりキーボードの入力を受け付けなくなります。ただし、マウスを使用すると挿入モードのままカーソルの移動が可能です。ノーマルモードに戻ることはできません。Vimを終了するとき、保存するかどうか尋ねてくるダイアログが出ますが、その時はキーボード入力が可能です。

Vim 7.3.1008 でも発生。気のせいか、最近頻度が高いような……。
GVimではよく発生しますが、コンソールのVimで発生したことは記憶上ありません。

この現象が発生した時、調べて欲しい情報があったらぜひ教えてください。
再現した時に試してみます。

この現象が発生した環境は主にLinux環境です。Windows環境は最近Vimの使用頻度が低いので、覚えていません。
環境: Ubuntu Linux 13.04
Vim : 7.3.1008(if_lua, if_python3, if_ruby)
使用プラグイン：
- neocomplcache
- echodoc
- neobundle.vim
- unite.vim
- vimshell
- vimfiler
- neosnippet
- vimproc
- vim-versions
- eskk.vim
- autofmt
- vim-surround

正規表現エンジン:`set re = 1`

**Comment by koron** [comment]
OSとか導入プラグインとか書いておいてください。

私は自前の7.3.969でプラグインなしですが、
そのような現象にあったことはありません。
なので原因はプラグイン+evalにあると考えています。

**Comment by Shougo** [comment]
> OSとか導入プラグインとか書いておいてください

全部挙げると大変なことになるので、とりあえず主なものを挙げました。

> 私は自前の7.3.969でプラグインなしですが、
> そのような現象にあったことはありません。
> なので原因はプラグイン+evalにあると考えています。

ちなみに、一番怪しい（Vimの秘孔をついている）と思われるのはneocomplcacheです。

**Comment by Shougo** [comment]
つい先程再現しました。
インサートモードで`<CR>`を入力した時に発現するみたいです。

マウスでカーソルを移動させると自動補完は発動します。プラグインはちゃんと動いているみたいです。
右クリックのマッピングも動きました。キーボードのみ効きません。

**Comment by Shougo** [comment]
`<CR>`の定義

```
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return neocomplcache#smart_close_popup() . "\<CR>"
endfunction
function! neocomplcache#mappings#close_popup() "{{{
  let neocomplcache = neocomplcache#get_current_neocomplcache()
  let neocomplcache.complete_str = ''
  let neocomplcache.skip_next_complete = 2
  let neocomplcache.candidates = []

  return pumvisible() ? "\<C-y>" : ''
endfunction
```

**Comment by Shougo** [comment]
すみません、この問題は私のプラグインのバグの可能性が出てきました。
その問題をプラグイン側で対処したので、また同じ問題が再現するまで本件はcloseしておきます。
`<C-c>`でも抜けられなかったのは、if_luaの中で固まってたからだと思われます。

**Comment by mattn** [comment]
> つい先程再現しました。
> インサートモードで<CR>を入力した時に発現するみたいです。
> 
> その問題をプラグイン側で対処したので、また同じ問題が再現するまで本件はcloseしておきます。

それでは何も解決しないのでは。
再現する方法があると書いたならどちらのバグかはっきりして貰えるとissueが1個減って助かるのですが。

**Comment by koron** [comment]
補完のluaん中で無限ループしちゃってたんでしょ?

**Comment by Shougo** [comment]
了解しました。問題のコードを上げますので、しばらくお待ちください。

**Comment by Shougo** [comment]
```
let test_string = 'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh'

let pattern = substitute(test_string, '\w', '\0.*', 'g')

lua << EOF
do
  local pattern = vim.eval('pattern')
  local word = vim.eval('test_string')
  print(string.find(word, pattern, 1))
end
EOF
```

以上のコードを `:source %` すると Vim がフリーズします。

ただ、この状態だと完全なフリーズなので私がここで報告していた「キーボードの入力を受け付けなくなる」とはちょっと異なる気もしています。

**Comment by Shougo** [comment]
上記の修正後、この問題が手元でまた再現したので、原因は別の部分にあることが分かりました。
自動補完が無効な状態でも挿入モード中に止まることがあります。

そのときは、if_luaを内部で使用しているunite.vimを使用していたのでif_luaが原因かもしれません。

**Comment by koron** [comment]
これ、微妙だなぁw

ここまでの流れのまとめ。
1.  lua使ってると操作不能になることがある
2.  1つ目のサンプルコードは、再現性の難しさがある
3.  2つ目のサンプルコードは、そもそも別の問題っぽい(それはそれで直さなきゃあかん)

**Comment by Shougo** [comment]
2つ目のサンプルコードは手元のバージョン 7.4.540 でもフリーズすることを確認しました。

**Comment by k-takata** [comment]
> 2つ目のサンプルコードは、そもそも別の問題っぽい(それはそれで直さなきゃあかん)

確認しましたが、`h.*h.*h.*h.* ...` というパターンになっており、単にバックトラックが大量発生する正規表現を使っているために、処理が終わらないだけですね。

1つ目については新たな情報もないようですし、invalidで閉じちゃっていいかな？

**Comment by k-takata** [comment]
1つ目のサンプルコードは再現が難しく、2つ目のサンプルコードは正規表現の書き方の問題だったので、invalidで閉じます。
