### ISSUE TITLE
Why Bram Moolenaar don't use git? 

### ISSUE THREAD

**Issue by UncleBill** [vim-jp/issues#394]
And put `vim` onto Github :100:

**Comment by Shougo** [comment]
I think it is because Mercurial has MQ feature.
This is very easy for patch management(You must management patches if you want to extend Vim).

But, Mercurial has performance disadvantage....

Note: You should put this post in vim_dev.

> And put vim onto Github :100:

Yes. Github is very useful service for git.

**Comment by koron** [comment]
Because he love python, I believe so.

**Comment by koron** [comment]
Please ask him directly.

**Comment by koron** [comment]
github に移ってしまったので、この issue は wontfix からfixed に変更しましたw
