### ISSUE TITLE
:py3<Tab> で補完が効かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#395]
`:py<Tab>` だと `py3do` や `py3file` などの候補が補完できますが、`:py3<Tab>` だと補完できません。`<Tab>` の代わりに `<C-d>` でも同様です。
Linux 64bit 7.3.969 で確認。

**Comment by koron** [comment]
ex_cmds.h 内での cmdnames の並び順のせいだと推測。
修正してみて現在テスト中。

**Comment by koron** [comment]
あれ? 違った。

**Comment by mattn** [comment]
ex_docmd.c で find_command が ASCII_ISALNUM で見てるからかも

**Comment by koron** [comment]
@mattn なんかそこまでも到達してないっぽい。

**Comment by koron** [comment]
`ex_docmd.c` の `set_one_cmd_context()` だった。

https://gist.github.com/koron/5685200

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/LJTvNu7UntA/ukleIOR84A4J

posted.

**Comment by thinca** [comment]
原因を把握していないんですが、これってコマンドの中に数字が含まれていたら起きるのかなぁと想像していたんですが、そういうわけではないのでしょうか?
今後同じように数字付きのコマンドが追加されても、別途対応する必要はない?

**Comment by koron** [comment]
それぞれ要特別対応です。

そもそも `py3*` 自体が別の場所 `find_command()` で特別対応されていました。
なので一般的にコマンドが数字を含む場合を考える必要は、今はないとの判断です。

**Comment by thinca** [comment]
なるほど。元々特別扱いだったんですね。

**Comment by koron** [comment]
ぶっちゃけ **「ひどい」** w

**Comment by thinca** [comment]
はい。パッチ見てびっくりしましたw これでいいの!?w って

**Comment by h-east** [comment]
Patch 7.3.1102 で取り込まれました。イェイ！
https://groups.google.com/d/msg/vim_dev/cB8i0MJjWes/8aygP7eScgsJ
