### ISSUE TITLE
sort の比較関数を書きたくない。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#397]
`filter` や `map` なんかでは `v:key` `v:val` を使って文字列を式として比較出来ますが、なぜか `sort` に至っては関数を用意しないといけないです。

かなりめんどくさいので、式を渡せる様にしてみました。

https://gist.github.com/mattn/5684747

ご意見下さい。

**Comment by mattn** [comment]
```
:echo sort([{"foo":3},{"foo":2},{"foo":4}], "v:rhs.foo < v:lhs.foo")
```

この様にして使います。

**Comment by koron** [comment]
:+1:

**Comment by mattn** [comment]
ドキュメント付けた。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/32Wk542f_cs/FxHt16odPv0J

**Comment by tyru** [comment]
@mattn ++

**Comment by tyru** [comment]
これでソート処理を書くのがソートー楽になりますね。

**Comment by ujihisa** [comment]
@mattn++

こっちのほうがパフォーマンスが良いのでVitalのData.List.sortも書き換えれそうですね。
(バージョン判定入りで)

**Comment by thinca** [comment]
`v:lhs` / `v:rhs` と `a:a` / `a:b` で変数が違うので無理かと。 変換する手はありますが、かなり複雑になりそうです。

**Comment by k-takata** [comment]
todo入りしました。

> Patch to support expression argument to sort() instead of a function name.
> Yasuhiro Matsumoto, 2013 May 31.
> Or should we add a more general mechanism, like lambda functions?

(まだ議論が続いているようですので、とりあえず閉じずに残しておきます。)

**Comment by Shougo** [comment]
スレッドはlambda機能の議論になっちゃってますね。どういう結論になるだろうか。

**Comment by Shougo** [comment]
https://github.com/vim-jp/issues/issues/40

無名関数の議論がそろそろ必要かも知れないですね。
mattnさんのこのパッチはsort()の問題しか解決ができないので。

**Comment by k-takata** [comment]
文字列の式の代わりに lambda が入りました。
例:

```
echo sort([{"foo":3},{"foo":2},{"foo":4}], {a, b -> a.foo - b.foo})
```

ということで閉じます。もし、文字列が使えないといやだという人がいればreopenしてください。
