### ISSUE TITLE
'scrolloff'オプションのカーソルジャンプ系コマンド専用版(例えば 'jumpoff') とかあってもいいかも

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#398]
['scrolloff'オプション](http://vim-jp.org/vimdoc-ja/options.html#'scrolloff')のカーソルジャンプ系コマンド専用版(例えば 'jumpoff') とかあったらそこそこ需要ある気がする。

https://groups.google.com/d/msg/vim_dev/TPAwTad3qIc/r4WF7cJNmSEJ

> > :h scrolloff 
> 
> Thank you for the suggestion, but I don't want to keep my cursor in 
> the middle of the screen.  I just want it there after jumping. :-) 

https://twitter.com/h_east/status/340458030430842880

> 「カーソルジャンプ動作時に自動でウィンドウの真ん中にカーソルが来るようにしたいけどmapでzzコマンド足しまくっても不完全！」とかいう人に「set なんちゃら=999で出来るよ」のなんちゃらをいつも忘れる。scrolloff ですね。でもこれはこれでキモいw

例えば、

``` vim
set scrolloff=0
set jumpoff=999             " 新設オプション
```

の場合、`j`,`k`の移動ではカーソルはウィンドウの端まで移動できる。
でも、ジャンプ系コマンド(*1)を実行するとカーソル行がウィンドウの中心になるように調整してくれる感じ。

*1
`/`,`?`,`n`,`N`,`*`,`#`,`<C-]>`,`g<C-]>`,`g]`,`<C-T>`,
`:tag`,`:pop`,`:tselect`,`:stselect`,`:tjump`, ....

ノープランで先ずはissue立てた。

**Comment by thinca** [comment]
`:set scrolljump=-50` とは違いますか?

**Comment by h-east** [comment]
@thinca 違います。

ジャンプ系コマンド(*1)によるカーソル移動時の挙動が変わる的なもの。

**Comment by thinca** [comment]
なるほど、通常の `j`/`k` などでは飛んで欲しくないんですね。
今スクリプトで map 使わずにやるとしら、 `CursorMoved` でジャンプを検出して `zz` とかですかね。イメージとしてはこれで合ってます?

**Comment by h-east** [comment]
vim_devの例のスレッドのGaryさんの意見を踏まえていい感じのソリューションを提案してみてはどうでしょうか？
私は「Vim本体を改良するなら」の方向で妄想を膨らませます。

**Comment by h-east** [comment]
ジャンプ系コマンド(_1) に追加。たくさんあるので全部を網羅するのは無理だこりゃｗ
`'a`,`'z`,`'A`,`'Z`,`'0`,`'9`,
`g;`,`g,`,`%`,`[(`,`[{`,`])`,`]}`,`]m`,`]M`,`[m`,`[M`,`[#`,`]#`,`[_`,`[/`,`]*`,`]/`,
`[[`,`]]`,`[]`,`][`,`{`,`}`, ....

ヘルプのカテゴリ的には対象はこんな感じか。
[search-commands](http://vim-jp.org/vimdoc-ja/pattern.html#search-commands), [object-motions](http://vim-jp.org/vimdoc-ja/motion.html#object-motions), [mark-motions](http://vim-jp.org/vimdoc-ja/motion.html#mark-motions), [jump-motions](http://vim-jp.org/vimdoc-ja/motion.html#jump-motions), [various-motions](http://vim-jp.org/vimdoc-ja/motion.html#various-motions), tag([tag-commands](http://vim-jp.org/vimdoc-ja/tagsrch.html#tag-commands), [tag-stack](http://vim-jp.org/vimdoc-ja/tagsrch.html#tag-stack), [tag-matchlist](http://vim-jp.org/vimdoc-ja/tagsrch.html#tag-matchlist)), [include-search&definition-search](http://vim-jp.org/vimdoc-ja/tagsrch.html#include-search)

つまり、[left-right-motions](http://vim-jp.org/vimdoc-ja/motion.html#left-right-motions), [up-down-motions](http://vim-jp.org/vimdoc-ja/motion.html#up-down-motions), [word-motions](http://vim-jp.org/vimdoc-ja/motion.html#word-motions), [scroll-down](http://vim-jp.org/vimdoc-ja/scroll.html#scroll-down), [scroll-up](http://vim-jp.org/vimdoc-ja/scroll.html#scroll-up)の移動以外は対象になっちゃうのか。
そしてカテゴリ毎に有効無効が設定出来ればベストと。

**Comment by h-east** [comment]
誰も食いつかないし、必要性もないので閉じます。
興味がある人が出てきたら再オープンお願いします。
