### ISSUE TITLE
7.3.919以降、*.ja が開けない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#399]
7.3.919以降、*.ja (例えば README.ja) を開こうとすると次のようなエラーが出るようになってしまいました。

```
***error*** (zip#Browse) unzip not available on your system
```

runtime/plugin/zipPlugin.vim が更新されたことにより、*.ja を zip 形式で扱おうとするようになったことが原因です。
（unzip コマンドをインストールしていれば、ファイルを解凍できなかった場合にはプレーンテキストとして開けるようですが、このマシンにはインストールしていません。）

対策としては、以下の内のどれかになると思います。
1. runtime/plugin/zipPlugin.vim から "*.ja" を除外してもらう。
2. zipPlugin が扱う拡張子を設定できるようにしてもらう。
3. unzip コマンドが見つからない場合にはエラーを出すのではなく、*.ja をプレーンテキストとして開くようにしてもらう。

7.4 も迫っていることですし、zipPlugin の作者本人と vim_dev の両方にまとめて報告した方がいいでしょうか？

# ところで、拡張子 ja で zip 形式のファイルって何のファイルでしょう？

**Comment by koron** [comment]
zipPlugin に特定の拡張子除外のためのオプションを追加するパッチ書くと良いと考えます。

> # ところで、拡張子 ja で zip 形式のファイルって何のファイルでしょう？

jar ファイルの typo 対応だったりしたら怒るよねw

**Comment by koron** [comment]
> runtime/plugin/zipPlugin.vim から "*.ja" を除外してもらう。

http://www.file-extensions.org/ja-file-extension

このへんを根拠に外せと要求するのもありかも。

**Comment by koron** [comment]
> Jet Archive
> Game file used by N3V Games' (previously Auran) Jet engine

http://www.fileinfo.com/extension/ja

こんなのもあるのかw

**Comment by k-takata** [comment]
とりあえず、投げてみました。
https://groups.google.com/d/topic/vim_dev/3bX-xuEiYhk/discussion

> zipPlugin に特定の拡張子除外のためのオプションを追加するパッチ書くと良いと考えます。

どう書けばいいのか分かっていないので、これは今後の課題ということで。

> Jet Archive

そんなの知らないｗ

**Comment by mattn** [comment]
ひどい話だw

On 6/1/13, K.Takata notifications@github.com wrote:

> とりあえず、投げてみました。
> https://groups.google.com/d/topic/vim_dev/3bX-xuEiYhk/discussion
> 
> > zipPlugin に特定の拡張子除外のためのオプションを追加するパッチ書くと良いと考えます。
> 
> どう書けばいいのか分かっていないので、これは今後の課題ということで。
> 
> > Jet Archive
> 
> そんなの知らないｗ
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/399#issuecomment-18783053

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
ファイル先頭の `PK` シグネチャを見てはどうかとの提案が出ました。
https://groups.google.com/d/msg/vim_dev/3bX-xuEiYhk/NithyhGlIrwJ

**Comment by mattn** [comment]
｢PK戦｣で始まるテキストが誤動作する件について

On 6/1/13, K.Takata notifications@github.com wrote:

> ファイル先頭の `PK` シグネチャを見てはどうかとの提案が出ました。
> https://groups.google.com/d/msg/vim_dev/3bX-xuEiYhk/NithyhGlIrwJ
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/399#issuecomment-18785182

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
> ｢PK戦｣で始まるテキストが誤動作する件について

シグネチャを見てzip形式と判定して、unzipコマンドに渡しても、実際にはzip形式ではなかった場合のことを考えると、あまり意味はなさそうですね。

3.を少し変更して、unzipコマンドが見つからない場合はエラーメッセージを出しつつ、普通にファイルを開けばいいのではと思いました。
少し下にある、unzipでファイルが解凍できなかった場合に、普通に開く処理をコピってきたところ、一応開けるようになりました。が、自分の環境だと意図せずエラーメッセージが上書きされて消えてしまっていました。（ま、どっちでもいいんですが。）

``` diff
diff --git a/runtime/autoload/zip.vim b/runtime/autoload/zip.vim
--- a/runtime/autoload/zip.vim
+++ b/runtime/autoload/zip.vim
@@ -75,6 +75,12 @@
    echohl Error | echo "***error*** (zip#Browse) unzip not available on your system"
 "   call inputsave()|call input("Press <cr> to continue")|call inputrestore()
    let &report= repkeep
+   keepj sil! %d
+   let eikeep= &ei
+   set ei=BufReadCmd,FileReadCmd
+   exe "keepj r ".fnameescape(a:zipfile)
+   let &ei= eikeep
+   keepj 1d
 "   call Dret("zip#Browse")
    return
   endif
```

この方法だと、vimrc_example.vim に載っている、[前回終了時のカーソル位置に移動する設定](http://vim-jp.org/vimdoc-ja/usr_05.html#restore-cursor)が使えないのがちょっと残念です。

**Comment by k-takata** [comment]
前述のパッチを投げました。
https://groups.google.com/d/msg/vim_dev/3bX-xuEiYhk/VNkFkZ7FhJcJ

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/3bX-xuEiYhk/dpQB_LfLlwYJ
v27a で、zip形式として扱う拡張子が設定できるようになり、"PK" シグネチャも見るようになりました。
しかし、zip形式で扱われるファイルが "PK" で始まってなかった場合に、ファイルを読み込む処理を
行っていないので空のファイルが開かれてしまいます。こんなパッチを送りました。

``` diff
diff --git a/runtime/autoload/zip.vim b/runtime/autoload/zip.vim
--- a/runtime/autoload/zip.vim
+++ b/runtime/autoload/zip.vim
@@ -63,6 +63,12 @@
   " sanity check: insure that the zipfile has "PK" as its first two letters
   "               (required for proper zip file format)
   if readfile(a:zipfile, "", 1)[0] !~ '^PK'
+   keepj sil! %d
+   let eikeep= &ei
+   set ei=BufReadCmd,FileReadCmd
+   exe "keepj r ".fnameescape(a:zipfile)
+   let &ei= eikeep
+   keepj 1d
 "   call Dret("zip#Browse : not a zipfile<".a:zipfile.">")
    return
   endif
```

**Comment by mattn** [comment]
@k-takata ++

**Comment by k-takata** [comment]
いつのまにか v27b が公開されていたのですが、デバッグメッセージが有効になっているせいかまともに動かないです。
http://www.drchip.org/astronaut/vim/index.html#ZIP
(デバッグメッセージを無効化すれば動いているようです。)

**Comment by mattn** [comment]
品質が問われる...

**Comment by k-takata** [comment]
デバッグメッセージが無効化された v27c が公開されました。正常に動作しています。
https://groups.google.com/d/msg/vim_dev/3bX-xuEiYhk/_Du9ssUamJMJ

Vim本体のリポジトリに入ったらクローズしようと思います。

**Comment by k-takata** [comment]
7.3.1308 と一緒に v27 がコミットされて直りました。
