### ISSUE TITLE
無名関数に対応させたい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#40]
これは比較的大きな変更となりそうですが……。
以前から要望されているのでここに挙げておきます。

Vim scriptには無名関数がありません。
Dictionary functionで無名関数（のようなもの）を定義することはできます。

例えば、sort()に無名関数が使えると、関数の定義を簡略化できて便利かと思います。

問題は、いつ関数を解放するかですが、Dictionary functionはどうやっているんですかね？

**Comment by koron** [comment]
内部的にすべての関数が名前でハンドリングされているので、現時点では実質的に不可能。
以前 @mattn さんが指摘していたけど、Funcrefって実はただの名前。
VAR_FUNCの時にv_stringを使えってのには面食らった。

無名関数を扱えるようにするってのは最終的に、[第一級関数](http://ja.wikipedia.org/wiki/%E7%AC%AC%E4%B8%80%E7%B4%9A%E9%96%A2%E6%95%B0) にすることに等しくなるから、今の構造ではかなり無理が生じるのも事実。Vim的にはかなりのやっつけになるが…どうすんだコレ?

**Comment by tyru** [comment]
@Shougo 無名関数の構文はどんなのになるんでしょうか。

そういえば微妙にというかまったく関係ない話なんですが
`sort()`はPatch 7.3.224で第3引数に{dict}渡せるようになってたりします。(`self`にバインドするDictionaryを渡せる)
https://groups.google.com/forum/#!topic/vim_dev/raNRS86On-8
ただ考えてみれば使い道が比較関数の中で動的に処理を切り替えるぐらいしか思いつかないし
要素以外の情報渡されてもあんまうれしくないですね。
比較関数が重くなったら元も子もないし...

**Comment by Shougo** [comment]
> @Shougo 無名関数の構文はどんなのになるんでしょうか。

lambda('return 3+3')みたいな感じで使えるといいかなーと思います。

> 無名関数を扱えるようにするってのは最終的に、第一級関数 にすることに等しくなるから、今の構造ではかなり無理が生じるのも事実。Vim的にはかなりのやっつけになるが…どうすんだコレ?

ただ、そういうことはあるので、もうLuaを組み込みにするとか、もっと踏み込んだ話にする必要があるかな……。

**Comment by koron** [comment]
ちょっと考えていたんですが、
Vimは関数の中身も文字列で実行時解釈だから逆にそういうのはやりやすい、という考え方もできますね。
もともと遅いからオーバヘッドも実は無いかもしれない。。
関数の内容を文字列として渡してくれるならカリー化もできるといえばできることになりますが…

あとは関数名がIDになってる点だけ、一段マップテーブル挟めば、実験はできるかも…ってところまで考えて
executeがなんか近いなと思ったり。

**Comment by mattn** [comment]
まだ作りかけなんだけど、実際lambdaとは言えど関数リファレンスを持っておく必要がある訳だから、それをvim内部に持つか、スクリプトに持つかの問題だったりする。

作りかけだけど（キャッシュクリアとか）、これでそれ相当は出来るはず

https://github.com/mattn/funcutil-vim/blob/master/example.vim#L15

**Comment by Shougo** [comment]
ふむふむ。あとはそれを内部で実装する方法を考えればよいのかもしれませんね。

> Vimは関数の中身も文字列で実行時解釈だから逆にそういうのはやりやすい、という考え方もできますね。

はい。というか、map()とかもあれは本来Funcrefですよね。

現在だと、execute functionでそれっぽいこともできますが、あとは関数の参照をどう削除するのか、ということになりますかね。

**Comment by koron** [comment]
関数の削除自体はdelfuncもあるしどうとでもなるんじゃ。

あと面白いのと有用なのとは別な気がしますね。
よほど有用なシーンがなければacceptされないような規模になりそう。
とりあえずFar Futureに分類しておきます。

**Comment by mattn** [comment]
内部でやる必要の無いものはなかなか取り入れられない。それは皆が内部でやって欲しいと思う様に、Bramも外でやって欲しいと思ってる。

**Comment by Shougo** [comment]
まぁ、Vim script側でぐちゃぐちゃやるよりは、Vim Scriptを今後どうするのかといった、より重要な問題を解決したほうがよさそうです。
私としては、言語の記述力がもっと上がればよくて、それがVim Scriptであろうが、Luaなどの外部インタフェースであろうがあまり違いはないかな。どうせ書きなおしになるし。

**Comment by mattn** [comment]
キャプチャされるのは現在実行スコープでよいので、 s: ディクショナリに見えない関数を作ってしまえばいいのかな。
この方式は github.com/mattn/lambda-vim
でやってる方式だけど、いかんせん文字列リテラルは隠せない。

**Comment by Shougo** [comment]
新しい構文を作ると、新しいVimでしか動作しなくなるのが玉に瑕です。
Vimのメジャーバージョンアップくらいがころあいなんですかねー。

**Comment by Shougo** [comment]
sort()の議論を見るに、Bram氏も無名関数実装へのやる気はあるみたいです。
他の人も欲しがっているし、パッチさえあればすんなり受け入れられるのでは？と思います。

**Comment by koron** [comment]
#632 で無名関数は実現されました。ただし、報告はしたけど vim-dev では no actions な状態です。

といったところなのでコチラは duplicated で閉じます。
