### ISSUE TITLE
補完の絞り込み時のチラツキを改善する(Vim標準の絞り込み)

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#401]
Vimで補完を絞り込むとき、絞り込んでも候補に変化がないにもかかわらず補完ウインドウがちらつきます（ちらつかないこともあります）。補完候補が多い時に再現しやすいようです。

再現しやすい例：

`neob<C-x><C-n><C-p>` と入力して、
"NeoBundleXXXX"の補完候補を出し、そのまま"neobu"と絞り込みを続ける。

補完関数がそのときに再度呼ばれてはいないことは確認しているので、これはVimの絞り込みの再描画処理に問題があるのではないかと考えています。

このスレッドではVimの補完絞り込み時の挙動を調べ、再描画処理を改善するのを目標とします。

再現しやすい例

**Comment by Shougo** [comment]
そろそろこれの作業に手を付けたいと思います。

**Comment by Shougo** [comment]
ソースコードを呼んでみて、おおよそVimがやっていることがわかりました。

どうやら、ユーザーが入力し絞り込みが発生するたびにcomplという補完候補リストからマッチをチェックして
ポップアップメニューに表示するということをやっているようです。
要素数のチェックなどはやっていないので、毎回再描画されることになります。

**Comment by Shougo** [comment]
ポップアップを削除しているのは、絞り込み時に呼ばれる ins_compl_new_leader()。ins_compl_del_pum()がそれ。
ただ、ポップアップを削除しないようにしてポップアップを再描画しようとするとSEGVする。なかなか難しいなぁ。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5743202

とりあえずのパッチができました。

絞り込み結果に変化がない場合は再描画しないようになっています。
副作用がないかわからないので、試してくれる人募集中。私はこのパッチを使用してみます。

**Comment by saitoha** [comment]
私も当ててみました。しばらく使用してみます。

**Comment by Shougo** [comment]
おお、ありがとうございます。私も使用しています。
ちなみに、端末のVimだとパッチの効果はあまりありません。GVimでのチラツキがひどかったです。

**Comment by saitoha** [comment]
たしかに効果が無いですね。端末で意図的に「絞り込み結果に変化がない場合」をつくってみても全部再描画しています。

**Comment by saitoha** [comment]
でもおかしいなあ。これ端末版でも通る場所ですよね。
![2013-06-09 20 48 56](https://f.cloud.github.com/assets/1162739/628817/df41d4aa-d0fa-11e2-94bd-13c7f000f245.png)
ちょっと上のスクリーンショットでは状況はわかりにくいかと思いますが、候補
- abcd
- abcdefg
- abcdk
- abcdefgg
  がある状況で、「ab」「abc」「abcd」あたりの補完をさせています。
  「abcd」までは候補が4つで増減は無いはずです。(が、実際は全部書き直されてしまっている)
  パッチレベルは1119を使っています。

**Comment by Shougo** [comment]
GVimでも試してもらえますか。
今回のパッチでさぼったのはあくまで補完ウインドウを絞り込み時に再描画する部分で、他のところで再描画が発生していればさぼることはできません。もともとVimだと補完ウインドウでのチラツキを感じることができなかったので、明らかにGVimとは別のルーチンが動いているのだと思います。

**Comment by Shougo** [comment]
Vimだと画面全体を直しているのかも知れません。経験上、候補ウインドウだけ再描画しているとチラつくのですが、画面全体を直すとほとんどチラつきません。

**Comment by Shougo** [comment]
絞り込み時に呼ばれるのはedit.cのins_compl_new_leader()です。この中に再描画と思われる関数がいくつか存在します。
それらをコメントアウトしてみて、この再描画の原因がどの関数なのか調べてもらえますか？
update_screen()は個人的に怪しいと思ってます。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5743202

再描画するときはupdate_screen()をしないようにしてみました。とりあえず、この変更が悪さをしているようには見えなかったですが、調べてもらえますか。

**Comment by saitoha** [comment]
@Shougo ありがとうございます
しかし、update_screenは削っても影響はありませんでした。

まず、このif節はちゃんと機能していることを確認しました。

> if (ins_compl_match_size() != compl_match_arraysize) {

先の例でいうと「ab」->「abc」のときは 4 != 4 となり、このif文のなかは通っていません。

それにもかかわらず再描画はおこります。
再描画がおきる領域は、ポップアップの矩形範囲全体です。

そこでいまは、色々な場所にちらばっている
ins_compl_del_pum と ins_compl_show_pumをコメントアウトして、
どこがどう出力に影響しているのか、動きをたしかめているところです。

**Comment by saitoha** [comment]
@Shougo あと、GVimでの確認ですが、macでのビルド方法をよく理解していなくてまだやっていません。
GVimと端末のvimでは、ひょっとしたらスクリーンの更新タイミングや更新のコストが違うかもしれないので、Shougoさんと私が問題視している現象自体が違うものを指しているかもしれません。

**Comment by alpaca-tc** [comment]
僕の環境でもちらつきが出てたんですが、設定を変えるとちらつかなくなりました。
powerline環境で
set laststatus=2 -> 0 or 1
おそらく、毎回再描写する関数がある場合の相性がよくないんでしょうね。

関係ある方もいるかもしれないので、念のため。

**Comment by mattn** [comment]
ステータス行の更新がどこかに含まれてて、ステータスに含まれるeval系を再実行してるからですかね。

**Comment by Shougo** [comment]
> @Shougo あと、GVimでの確認ですが、macでのビルド方法をよく理解していなくてまだやっていません。
> GVimと端末のvimでは、ひょっとしたらスクリーンの更新タイミングや更新のコストが違うかもしれないので、Shougoさんと私が問題視している現象自体が違うものを指しているかもしれません。

はい。描画関連のコードは端末とGUIで異なる可能性が高いです。

> それにもかかわらず再描画はおこります。
> 再描画がおきる領域は、ポップアップの矩形範囲全体です。

だとすると、絞り込みルーチン以外でどこかにポップアップメニューの再描画を行うコードがあるのだと思います。

> そこでいまは、色々な場所にちらばっている
> ins_compl_del_pum と ins_compl_show_pumをコメントアウトして、
> どこがどう出力に影響しているのか、動きをたしかめているところです。

分かりました。パッチはとりあえずこのままにしておきます。@saitohaさんの調査で何か分かりましたら、結果をマージすることにしましょう。

> 僕の環境でもちらつきが出てたんですが、設定を変えるとちらつかなくなりました。
> powerline環境で
> set laststatus=2 -> 0 or 1
> おそらく、毎回再描写する関数がある場合の相性がよくないんでしょうね。

これは端末のVimでしょうか。それともGVimでしょうか。

> ステータス行の更新がどこかに含まれてて、ステータスに含まれるeval系を再実行してるからですかね。

vimrcを最小状態にして、どれが影響を与えるのか試してみると良いかもしれないですね。

**Comment by mattn** [comment]
よくわからんのですが、これ普通のポップアップで絞り込む事を言ってます？
それともプラグイン使ってrefreshとか使っての話をしてます？再現サンプルスクリプト貰えると修正に参加するかもしれません。
ちなみに普通のポップアップで絞り込む場合にはまったくチラツキなど発生しませんね。うちの環境(Win7)では。

**Comment by Shougo** [comment]
> よくわからんのですが、これ普通のポップアップで絞り込む事を言ってます？
> それともプラグイン使ってrefreshとか使っての話をしてます？再現サンプルスクリプト貰えると修正に参加するかもしれません。
> ちなみに普通のポップアップで絞り込む場合にはまったくチラツキなど発生しませんね。うちの環境(Win7)では。

補完関数の種類によらない、普通のポップアップでの話です。チラついている時、補完関数は呼ばれていないことを確認しています。Vim標準での補完（例：バッファ補完）でも再現します。
サンプルスクリプトは用意してみます。
私が試しているのはUbuntu 13.04です。Windowsでの確認はしていません。ただ、@manga_osyoさん(Windowsユーザ)からもチラついているという報告があります。
@mattn さんの環境で再現しないのは、このチラツキが発生するのは「絞り込みで候補が変わらないとき」というある種限定的な状況でのみ起こるからだと思います。候補が変わらない時だけ、なぜチラつくのかは私もよく分かっていません。

ちなみに、補完関数がrefresh=alwaysのときは「絞り込みで候補が変わらないとき」のチラツキよりもはるかにひどくちらつきます。この問題は別のIssuesで改善を考えたいところです。

**Comment by Shougo** [comment]
再現テキストを用意しようとしたのですが、このチラツキはやはりマシンパフォーマンスに極めて依存するようです。別のマシンではなかなか再現ができませんでした。特に、動作が高速な素のVimなどで試すと再現ができないと思われます。

**Comment by Shougo** [comment]
私の環境では素のVimでも再現できたので、Gist化しました。

https://gist.github.com/Shougo/5746197

`gvim -U NONE -i NONE -u NONE test.txt -c "set ignorecase" --no-plugin`
でテキストファイルに書いてある操作を試してみてください。

**Comment by mattn** [comment]
候補数の変更で見るのはちょっと弊害があるないの判断が出来ないのでShougoさんのパッチは賛同し兼ねるけど、その目的ならコード調べられそう。メシ食いながら調べます。

**Comment by Shougo** [comment]
ありがとうございます。

> 候補数の変更で見るのはちょっと弊害があるないの判断が出来ないのでShougoさんのパッチは賛同し兼ねるけど、その目的ならコード調べられそう。メシ食いながら調べます。

本当なら、もっと賢い挙動をするようにしたかったのですが、それだと変更点が多くなりそうなのでやっていません。

**Comment by mattn** [comment]
``` diff
diff -r 198cf88374c8 src/edit.c
--- a/src/edit.c    Sun Jun 09 20:51:00 2013 +0200
+++ b/src/edit.c    Mon Jun 10 12:23:59 2013 +0900
@@ -2890,9 +2890,6 @@
     do_cmdline_cmd((char_u *)"if exists('g:loaded_matchparen')|3match none|endif");
 #endif

-    /* Update the screen before drawing the popup menu over it. */
-    update_screen(0);
-
     if (compl_match_array == NULL)
     {
    /* Need to build the popup menu list. */
```

これで速くなると思う。
まず、補完の開始終了、ポップアップの出し閉じ時に呼ばれる `ins_compl_show_pum` には既に `update_screen(0)` (もしくはそれ相当)が既に、呼ばれていて補完候補を弄る `ins_complete` では画面を予め確定しておく必要はない。
なので呼ばなくてok。

どうでもいいけど例文の頭にNeobundle付けた意味は宣伝ですか？w
宣伝はよそでやってw (もう毎回言ってるから免疫付いたかもしれないけどそろそろ言わなくてもわかってよ)

**Comment by Shougo** [comment]
> どうでもいいけど例文の頭にNeobundle付けた意味は宣伝ですか？w
> 宣伝はよそでやってw (もう毎回言ってるから免疫付いたかもしれないけどそろそろ言わなくてもわかってよ)

宣伝ではないです。もっと他の例で再現したかったんですが、私の手元で再現できたのがアレだったのです。
大文字小文字が混じった候補の状態でignorecaseで絞りこませないとチラツキが再現できませんでした。

**Comment by mattn** [comment]
まじすかw 僕んとこはこれでも再現したけどなー。

```
asdf1
asdf12111
asdf121222
asdf121322
asdf121322
asdf13
asdf2
```

**Comment by Shougo** [comment]
宣伝と思われるのは本意ではないのでテストファイルを修正しました。

https://gist.github.com/Shougo/5746197

> これで速くなると思う。
> まず、補完の開始終了、ポップアップの出し閉じ時に呼ばれる ins_compl_show_pum には既に update_screen(0) (もしくはそれ相当)が既に、呼ばれていて補完候補を弄る ins_complete では画面を予め確定しておく必要はない。
> なので呼ばなくてok。

そのパッチを試してみます。が、このパッチだと@saitohaさんの再描画問題は解決しなさそうですね。以前のパッチでもこのルーチン自体は呼ばれず、その状態でも@saitohaさんの環境だと再描画するようなので。

**Comment by Shougo** [comment]
> まじすかw 僕んとこはこれでも再現したけどなー。

私のところでは、それだと無理でした。それよりもっと長い文字列で30個くらい用意しましたがチラつきません。

**Comment by mattn** [comment]
パッチ適用後のコードを見れば分かりますが、解決してますよ。途中でreturnで抜けている部分。

**Comment by mattn** [comment]
全体の書き換えは無くなったはずです。ポップアップ内を再構成しない様にするならもう少し弄った方がいいですが。

**Comment by Shougo** [comment]
> パッチ適用後のコードを見れば分かりますが、解決してますよ。途中でreturnで抜けている部分。

それが指す行がわからないのですが、ここでしょうか。

```
    if (!pum_wanted() || !pum_enough_matches())
    return;
```

https://gist.github.com/Shougo/5743202

mattnさんのパッチでそのまま置き換えました。

> 全体の書き換えは無くなったはずです。ポップアップ内を再構成しない様にするならもう少し弄った方がいいですが。

この「ポップアップ内を再構成しない」、とはどういう意味でしょうか。

もうちょっと確認をしてもらってvim_devに出してしまっても良いと思います。
ただVim 7.4が出そうですし、今パッチを出してもすぐに取り込まれる可能性は低そうなので、パッチの改良ができるならしてよいかもしれません。

**Comment by mattn** [comment]
あーでも僕のこのパッチまずいな。

**Comment by mattn** [comment]
キータイプしたらカーソルが動くのでステータス行を書き換えるのに update_screen(0) を呼ぶのは必須だな。
もしくはステータス行のみ書き換えるか。

**Comment by Shougo** [comment]
`:redrawstatus`があるくらいなので、ステータスラインの再描画には専用の関数があるかと思います。

> まず、補完の開始終了、ポップアップの出し閉じ時に呼ばれる ins_compl_show_pum には既に update_screen(0) (もしくはそれ相当)が既に、呼ばれていて補完候補を弄る ins_complete では画面を予め確定しておく必要はない。

`update_screen()`相当は既に呼ばれていたのではないでしょうか？

**Comment by mattn** [comment]
パッチは出来ててコメント書き＆確認中なのでもうちょっとまって。
update_screen は呼ぶ必要無いけどステータス行だけ更新が必要。

**Comment by mattn** [comment]
``` diff
diff -r 198cf88374c8 src/edit.c
--- a/src/edit.c    Sun Jun 09 20:51:00 2013 +0200
+++ b/src/edit.c    Mon Jun 10 13:08:39 2013 +0900
@@ -2890,8 +2890,14 @@
     do_cmdline_cmd((char_u *)"if exists('g:loaded_matchparen')|3match none|endif");
 #endif

-    /* Update the screen before drawing the popup menu over it. */
-    update_screen(0);
+    /* Update status line en before drawing the popup menu over it.
+     * NOTE: No need to call update_screen(0).
+     * update_screen(0) is called when popup is open or closed, resized
+     * already. So while inserting for completion, it don't need to update
+     * whole screen. But cursor should be moved. So just call
+     * redraw_statuslines() here.
+     */
+    redraw_statuslines();

     if (compl_match_array == NULL)
     {
```

こうかな。ポップアップの表示が必要まで到達してステータス行を更新しない理由が特に見つからないので呼ぶ条件は変えてません。

**Comment by mattn** [comment]
提出するなら変更の意味を書かないと伝わらないと思う。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/5743202

更新しました。パッチは今から確認します。

> 提出するなら変更の意味を書かないと伝わらないと思う。

mattnさんパッチのコメントに書いてある文章を使えば、変更の意味は伝わるのではないでしょうか。

**Comment by mattn** [comment]
`en` typo があるので取っておいて下さい。

**Comment by mattn** [comment]
ちゅうか、僕送りますか？w

**Comment by Shougo** [comment]
> ちゅうか、僕送りますか？w

このパッチを作成したのはmattnさんなので、mattnさんが送ったほうが良いと思います。

**Comment by mattn** [comment]
送る前に、出来れば↑のどちらかの方に効果が出るかを確認して頂きたいのですが @saitoha さん、@taichouchou2 さん、どちらか試して頂けませんか。

**Comment by saitoha** [comment]
patch level 1155にgistのrevision 4を当てました。
vimは「-u NONE -N」をつけて起動しました。
結果としては、私が不要だと考えている該当領域の再描画(一回ポップアップを消してもう一回最初から塗り直す)はあいかわらず起きています。
が、私の問題としている意味のちらつきはShougoさんや私やmattnさんが挙げた例ではおこりませんので、別件であつかうべきものかな、とも考えています。
単純に出力量が無駄に増えることでvim側あるいは端末側のバッファが溢れやすくなるためにおこるものなので、あるていど大きなポップアップではないと顕在化することは無いとおもいます。

**Comment by Shougo** [comment]
> が、私の問題としている意味のちらつきはShougoさんや私やmattnさんが挙げた例ではおこりませんので、別件であつかうべきものかな、とも考えています。
> 単純に出力量が無駄に増えることでvim側あるいは端末側のバッファが溢れやすくなるためにおこるものなので、あるていど大きなポップアップではないと顕在化することは無いとおもいます。

分かりました。別の問題だと思うので、これに関しては別のIssueを立ててもらえますか？
そちらで議論しましょう。

**Comment by mattn** [comment]
なるほど。僕が↑で言ってた「ポップアップ内を再構成しない」の意味の方ですね。
それは入れてません。

```
[]A[]
[][]A
```

に

```
[][]
[]A[]
```

をかぶせる場合、どこがマルチバイトの切れ目かを判断しないといけないので、処理時間を食って逆に重くなる懸念があったので。

ともあれ簡単に解決できる問題でも無い気がするので、別でやりましょう。

**Comment by Shougo** [comment]
私だとその問題をうまく説明できる気がしないので、@saitohaさんか@mattnさんにissueを立てるのをお願いしたいのですが、よろしいでしょうか。

**Comment by Shougo** [comment]
mattnさんのパッチですが、私が問題にしていたチラつきがないことが確認できました。

> en typo があるので取っておいて下さい。

typoは取りました。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/kFmrNmdnpSs/GMCMHodLflEJ

**Comment by Shougo** [comment]
投稿ありがとうございます。Bram氏から返答があれば、ここは一度closeしますね。

**Comment by mattn** [comment]
飛躍的に改善出来そうなパッチ書いてみました。

``` diff
diff -r 8c8cdda36022 src/popupmnu.c
--- a/src/popupmnu.c    Wed Aug 14 14:18:41 2013 +0200
+++ b/src/popupmnu.c    Thu Aug 15 20:53:27 2013 +0900
@@ -653,18 +653,14 @@

            /* Update the screen before drawing the popup menu.
             * Enable updating the status lines. */
-           pum_do_redraw = TRUE;
            update_screen(0);
-           pum_do_redraw = FALSE;

            if (!resized && win_valid(curwin_save))
                win_enter(curwin_save, TRUE);

            /* May need to update the screen again when there are
             * autocommands involved. */
-           pum_do_redraw = TRUE;
            update_screen(0);
-           pum_do_redraw = FALSE;
            }
        }
        }
```

**Comment by mattn** [comment]
ポップアップが更新されなくて不正なメモリ参照で落ちたので、方針変えて遅延再描画にした。

https://gist.github.com/mattn/6240621

**Comment by mattn** [comment]
あー、でもステータス行が再描画されなくなるのか... 困ったな。

**Comment by saitoha** [comment]
ご参考までに、mattnさんのパッチを当てた状態での端末版の再描画の様子です。
http://www.youtube.com/watch?v=gBYw4VOUCYU
- asdf1
- asdf12111
- asdf121222
- asdf121322
- asdf121322
- asdf13
- asdf2

を候補とし、「a」→「as」としたときの再描画の様子をゆっくりステップ実行しました

**Comment by mattn** [comment]
Vimの出力する内容って端末に優しくないですよね。
結構書き換えが発生します。コマンドラインとか1文字追加するだけで全部書き換えてますし。

**Comment by Shougo** [comment]
> Vimの出力する内容って端末に優しくないですよね。
> 結構書き換えが発生します。コマンドラインとか1文字追加するだけで全部書き換えてますし。

実を言うと、Vimだけでなくシェルの描画でさえも端末にやさしいとは言えないです。
一文字挿入するだけでコマンドライン消したりしていますし。
汎用性を高めることを重視していて、こういうことになってしまっているのかと。

**Comment by k-takata** [comment]
ずいぶん前にtodo入りしてました。

> Patch to remove flicker from popup menu. (Yasuhiro Matsumoto, 2013 Aug 15)

closeable?

**Comment by Shougo** [comment]
私が立てたのでcloseしておきました。報告ありがとうございます。

**Comment by Shougo** [comment]
このパッチを最新のVimで有効にすると補完時にクラッシュするように見えます。
誰か他の方も確認してもらえないでしょうか。

**Comment by 0xBADDCAFE** [comment]
どういう形で確認すればいいか分かりませんが、
https://gist.github.com/mattn/6240679
このパッチのみを以下のバージョン

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 23 2013 01:07:43)
MS-Windows 32-bit GUI version
Included patches: 1-131
```

へ適用し、vim_dev に投稿されていた操作を実行しました。

```
--------------
asdfasdf1
asdfasdf1211
asdfasdf12222
asdfasdf123222
asdfasdf123223
asdfasdf13
asdfasdf2
--------------

1. type <c-x><c-n><c-p> at empty line
  show popup window and clear candidate.

2. type 'asdf12' immediately
```

ひとまず上記の操作ではクラッシュしませんでした。

**Comment by Shougo** [comment]
> ひとまず上記の操作ではクラッシュしませんでした。

これだけでは再現しないと思います。
自動補完のプラグインを使うなどして、補完機能を何度も呼ばないと再現しませんでした。

しばらく使ってみてもらえませんか。

**Comment by h-east** [comment]
俺達はエスパーじゃないYO:alien::zap:
12/16の時点でクラッシュした時の状況や手順を情報として書いといてくれないと。
再現性100%じゃない場合でも「これこれこういう設定でこういう操作をN回くらいやったら落ちた」とかでいいので。

**Comment by Shougo** [comment]
個人的な環境でしか試していないので（最小構成を作っていない）、その情報を出してよいのか分からなかったので
報告していませんでした。すみません。

私が落ちた時の状況は、
1. eskk.vim + neocomplete.vimで自動補完をさせていた
2. J6uil.vimでLingrにチャットをしていた

時に発生しました。SEGVなのでタイミングはランダムなのですが、数十回ほどeskk+neocompleteによる自動補完をやっていた時に落ちました。

自動補完を使わなくても再現できるとは思いますが、すぐにSEGVするわけではないので自動補完を連続で行ったほうが再現させやすいとは思います。

**Comment by Shougo** [comment]
私の方でももう一度このパッチを有効化して試してみます。それで落ちるようならもうちょっと詳しい手順を調べます。

このパッチを外した状態なら安定していることは確認済みです。

**Comment by h-east** [comment]
@Shougo 了解です。お手数ですがよろしくお願いします:thumbsup:

**Comment by Shougo** [comment]
了解です。現在使用中ですが、少し使っただけではSEGVする気配がないので、もうちょっとガッツリ使用した上でSEGVするかどうか確認する必要がありそうです。

Edit: パッチはこれを使用しています。

https://gist.github.com/mattn/6240679

**Comment by Shougo** [comment]
自動補完を何度も入力していて、その後eskkでの日本語入力中にクラッシュしたので報告します。
パッチを有効化していない状態ではこういうクラッシュは起こっていませんでした。

やはりこのパッチはクラッシュするようです。もうちょっと調べます。

Edit: プラグインと設定なし、手動補完で延々と入力していましたが、クラッシュしません。ちょっとneocomplete+eskkの最小構成を作ってみます。

**Comment by Shougo** [comment]
``` vim
" .vimrc
set nocompatible

set runtimepath+=~/.bundle/neocomplete.vim
set runtimepath+=~/.bundle/eskk.vim

let g:neocomplete#enable_at_startup = 1

filetype plugin indent on
syntax enable

set completeopt+=menuone
set completeopt-=preview

let g:eskk#large_dictionary = {
      \   'path': expand('~/SKK-JISYO.L'),
      \   'sorted': 1,
      \   'encoding': 'euc-jp',
      \}
```

この上記.vimrcで40〜50回ほどeskkの補完とひらがなの入力を繰り返したところ落ちることを確認しました。
落ちるまではそれなりの時間がかかるようです。

edit: 標準の補完でも再現できないかやってみましたが、全然再現せずかなり厳しいです。メモリを大量に消費する必要がある？

**Comment by Shougo** [comment]
eskkを使わず、neocompleteだけならどうなのか見てみましたがこちらも全然クラッシュの気配がないです。
前はコード編集中にクラッシュしていたので、こちらも時間をかければクラッシュするはずとは思います。

私が試した限りだと、eskk+neocompleteが一番手間なくクラッシュさせる方法のようです。

**Comment by Shougo** [comment]
すみません、私のパッチリストにここの古いパッチが混じっていたようです。

> ポップアップが更新されなくて不正なメモリ参照で落ちたので、方針変えて遅延再描画にした。
> https://gist.github.com/mattn/6240621

パッチリストが 別のパッチ1 -> 別のパッチ2 -> top -> ここのパッチ（旧） -> ここのパッチ（新）
という順番になっており、私がSEGV入りのパッチをリストから削除していなかったのが原因です。

12/16のときは、
別のパッチ1 -> 別のパッチ2 -> ここのパッチ（旧） -> top とパッチを当てた時にSEGVしていて、
常用する際はパッチを当てる順番を変えて 別のパッチ1 -> 別のパッチ2 -> top  -> ここのパッチ（旧） としていたのですが
今回試すときに 別のパッチ1 -> 別のパッチ2 -> ここのパッチ（旧） -> ここのパッチ（新） -> topとなってしまっていて SEGVしたのが真相みたいです。

旧パッチを除外して試しているんですが、安定しているように見えます。
というわけでこのSEGV問題は解決済みとさせていただきます。申し訳ありません。

**Comment by h-east** [comment]
よく分かってないけど:sweat_smile:、解決したのならよかったです。
