### ISSUE TITLE
:mapにおいて<Nul>がXと表示される

### ISSUE THREAD

**Issue by DeaR** [vim-jp/issues#406]
``` vim
:map <Nul> nul
:map X xxx
:map
   X             xxx
   X             nul
```

で修正パッチが以下

``` diff
diff -r 1b5ca3e53566 src/message.c
--- a/src/message.c Wed Jun 05 21:42:53 2013 +0200
+++ b/src/message.c Thu Jun 06 18:50:09 2013 +0900
@@ -1577,7 +1577,7 @@
    {
        c = TO_SPECIAL(str[1], str[2]);
        str += 2;
-       if (c == K_ZERO)    /* display <Nul> as ^@ */
+       if (c == KS_ZERO)   /* display <Nul> as ^@ */
        c = NUL;
    }
    if (IS_SPECIAL(c) || modifiers) /* special key */
```

只のtypo疑惑:fearful:

**Comment by mattn** [comment]
@DeaR パッチ送って頂いても僕が代送してもokですが、どうされます？

僕はよく代送して「このパッチはDeaRからもらった」と書いてます。
その際にauthorが、DeaR さんになるか僕になるかはBram次第だったりますが。

**Comment by DeaR** [comment]
@mattn 送って頂けると個人的には嬉しいです

英語での文面を考えるのが個人的には一番の問題で…:sob:

**Comment by mattn** [comment]
了解です。僕のへたっぴな英語で送ります。

**Comment by mattn** [comment]
送りました。

https://groups.google.com/forum/#!topic/vim_dev/3BjBMt17byA

**Comment by Shougo** [comment]
mattn++;

**Comment by h-east** [comment]
DeaR ++

**Comment by mattn** [comment]
Mr. X というジャパニーズオッサンジョークに誰からもツッコミが入らない件

**Comment by h-east** [comment]
あれジョークだったんすか！ｗｗ

**Comment by DeaR** [comment]
7.3.1143で取り込まれました
名前のように見えない、言われました。ですよねー:fearful:

**Comment by k-takata** [comment]
7.3.1143へのリンクを載せておきます。
https://groups.google.com/d/topic/vim_dev/qN6WVx6G5tA/discussion

**Comment by Shougo** [comment]
> 7.3.1143で取り込まれました
> 名前のように見えない、言われました。ですよねー:fearful:

vim_devではnayuri aohimeを使用するようにしてはどうでしょう。

**Comment by DeaR** [comment]
> vim_devではnayuri aohimeを使用するようにしてはどうでしょう。

はい、そのつもりです
既にgithubのusernameも変更しちゃったりしてます

**Comment by mattn** [comment]
残念 & すみません ...

また今度。
