### ISSUE TITLE
関数 rmdir() を追加する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#41]
現在のdelete()はディレクトリを削除できません。
ディレクトリをmkdir()で作成できる以上、delete()でディレクトリを削除できてもよいのではないでしょうか。
ただし、中身のファイルが存在する場合もディレクトリを削除できてよいのか、という部分に関してはなかなか難しいところです。

**Comment by koron** [comment]
rmdir()の追加で良いのでは?

一般的には中身は消さないが、オプションで制御できて悪いことはない。

**Comment by koron** [comment]
あ、非sandbox限定を忘れずに。

**Comment by Shougo** [comment]
そうですね。rmdir()を追加する、ということで。中身まで削除するかどうかは、オプションで制御という形になりそうですね。

**Comment by thinca** [comment]
`mkdir()` のオプションにならうなら、`rmdir('dir', 'r')` とかですかね。

**Comment by koron** [comment]
タイトルを「delete()をディレクトリを削除できるようにする」から「関数 rmdir() を追加する」に変更しました。

**Comment by koron** [comment]
ちょっとパッチ作ってみる。

**Comment by koron** [comment]
うわ。windowsではmch_rmdirが定義されてないのかw

**Comment by koron** [comment]
とりあえず一段のrmdirはできた。が、この先は面倒なので一旦手を引きます。

https://gist.github.com/1647644

recursiveは想像以上に大変。ディレクトリエントリを列挙する機能がmch_*に無いみたいw
`glob()` 相当の機能(ExpandInit と ExpandOne)を使うこともできそうだが…再帰的に使うのはちょっと不安がある。
で、たぶん `mch_opendir()` `mch_readdir()` `mch_closedir()` を実装するのが一番良いハズ。

もしくは再帰なしで出しちゃうか。

**Comment by mattn** [comment]
開放漏れてない？

**Comment by koron** [comment]
あ。wdirnameの解放ね。忘れてた。

**Comment by koron** [comment]
ズバリな質問が vim_use にw パッチを出すなら今がチャンス!

https://groups.google.com/forum/?fromgroups=#!topic/vim_use/6sjI-7HzlGw

**Comment by Shougo** [comment]
> recursiveは想像以上に大変。ディレクトリエントリを列挙する機能がmch_*に無いみたいw

vimprocでは、ディレクトリにあるファイルの列挙をC言語で実装しています。実装の参考にならないでしょうか。

https://github.com/Shougo/vimproc.vim/blob/master/autoload/proc_w32.c#L942

**Comment by koron** [comment]
実装の参考になるならないではなく
下回りのAPIについて合意を取るというプロセスが面倒なんですね。
実装だけならいくらでもできます。

**Comment by Shougo** [comment]
ああ、そういうことですか。とりあえずvim_devに機能についてpostしてみて合意を取るというのはダメなのでしょうか？

**Comment by koron** [comment]
それもメンドイ。

**Comment by k-takata** [comment]
実装については、fileio.c / vim_deltempdir() を参考にするのが良さそうな気がします。
ディレクトリを再帰的に消すようにはなっていないので、mch_isdir() + 再帰呼び出しの追加が必要ですが。

**Comment by k-takata** [comment]
> vimprocでは、ディレクトリにあるファイルの列挙をC言語で実装しています。

本題からずれてしまいますが、ANSI API を使っているということは enc=utf-8 には対応していない？

**Comment by koron** [comment]
@k-takata さんのアドバイスに従って更新してみた。

https://gist.github.com/koron/1647644

Windows+MSVCでは動いた。
誰か他の環境でテストプリーズっていうかtestスクリプト書いてくれてもOK

**Comment by koron** [comment]
たぶん多階層でそれぞれに大量のファイルがあるとメモリ馬鹿食いなんだよね…気に喰わないのはそこだけ。

**Comment by k-takata** [comment]
mch_rmdir() の修正案。
- 先頭にコメント追加。
- *.c には __ARGS(()) は不要。
- 上で指摘のある解放漏れ。
- rmdir() の仕様に合わせて、失敗時は -1 を返すように変更。

``` c
/*
 * Remove a directory.
 * Returns 0 for success, -1 for failure.
 */
    int
mch_rmdir(const char *dirname)
{
    BOOL result = FALSE;

#ifdef FEAT_MBYTE
    if (enc_codepage >= 0 && (int)GetACP() != enc_codepage)
    {
    WCHAR   *wdirname = enc_to_utf16((char_u *)dirname, NULL);
    if (wdirname != NULL)
    {
        result = RemoveDirectoryW(wdirname);
        vim_free(wdirname);
    }
    }
    else
#endif
    {
    if (dirname != NULL)
        result = RemoveDirectoryA(dirname);
    }

    return result != FALSE ? 0 : -1;
}
```

# 直貼りだと、tabがつぶれてインデントがずれるのが良くないですね。

**Comment by koron** [comment]
@k-takata pull request please. https://bitbucket.org/koron/vim-kaoriya-patches/src/b33bb87bab7eba1047e69e92a87bc350ff625824/X004-eval_rmdir.diff?at=default

**Comment by koron** [comment]
あ、更新した gist 貼ってもらってもよいです。

**Comment by k-takata** [comment]
更新後のパッチではなく、上記指摘のみの差分ですが
https://gist.github.com/k-takata/6343336

**Comment by k-takata** [comment]
あと、rmdir_sub() の中で alloc() の戻り値のチェックを追加しておきました。

vim_deltempdir() を、rmdir_sub() を使うように修正というのは不要ですかね？
（その場合、rmdir_sub() をもうちょっと別の名前にした方が良さそうですが。）

**Comment by k-takata** [comment]
eval.txt に typo があったのでパッチ更新。

**Comment by k-takata** [comment]
> たぶん多階層でそれぞれに大量のファイルがあるとメモリ馬鹿食いなんだよね…気に喰わないのはそこだけ。

これをどうにかするとなると、rmdir_sub() を丸ごと mch_ にしてしまうのが楽ですかね？
上にある mch_opendir() mch_readdir() mch_closedir() とどちらがよいか…。

**Comment by koron** [comment]
理屈上は opendir ですが、まぁこの程度のメモリ使用量を気にするのは好みの問題なのでw

**Comment by koron** [comment]
@k-takata あ、追加パッチ、ありがとうございます!

> vim_deltempdir() を、rmdir_sub() を使うように修正というのは不要ですかね？

今、これを踏まえた修正をしてます。

**Comment by koron** [comment]
https://gist.github.com/koron/1647644
-   rmdir_sub を misc2.c へ移動
-   rmdir_sub を vim_rmdir_r に名称変更

以上を更新しました。あとはテストかしらね。

**Comment by koron** [comment]
> vim_deltempdir() を、rmdir_sub() を使うように修正というのは不要ですかね？

これなんですが…別パッチにしたほうが良い & vim_deltempdir のほうは末尾に pathsep が付いてる…

**Comment by k-takata** [comment]
今更ですが、gen_expand_wildcards() を使った場合、dotfile は列挙されるのかどうかが気になりました。

よく考えると、ディレクトリへの symlink (またはジャンクション) かどうかの判定が必要ですね（少なくともWindowsは）。
XPのように、リンク先も一緒に消えてしまったら目も当てられません。

**Comment by koron** [comment]
> ディレクトリへの symlink (またはジャンクション) かどうかの判定が必要ですね（少なくともWindowsは）

パッチ書いて～

**Comment by k-takata** [comment]
とりあえず書いてみました。
https://bitbucket.org/k_takata/vim-win32-mq/src/8126f6573e55dcad4eb19e045ea8d3444c1c1ad6/update-rmdir.patch
ドキュメントは、`*rmdir()*` がタグになっていなかったので修正、サンドボックスについて追記。

> 今更ですが、gen_expand_wildcards() を使った場合、dotfile は列挙されるのかどうかが気になりました。

dotfiles は列挙されないようですね。そのため、dotfiles があるディレクトリは削除できません。

**Comment by koron** [comment]
これ Win でシンボリックリンクの時 mch_rmdir を呼び出すことになってますけど、これでええの?
Winの mch_rmdir ってリンクだけ消すんでしたっけ?

**Comment by k-takata** [comment]
Windowsのシンボリックリンクは、ファイルの場合 DeleteFile() で、ディレクトリの場合 RemoveDirectory() で消しますので問題ないのですが……よく確かめると、gen_expand_wildcards() の結果になぜかディレクトリへのシンボリックリンクが含まれていないですねorz
ファイルへのシンボリックリンクと、ディレクトリへのジャンクションは正しく消えてくれましたが。

**Comment by k-takata** [comment]
> よく確かめると、gen_expand_wildcards() の結果になぜかディレクトリへのシンボリックリンクが含まれていないですねorz

原因判明。VC10 の _stat() のソースを確認したところ、ディレクトリへのシンボリックリンクはエラーが返ってしまうことが分かりました。（バグ？）
mch_getperm() か vim_stat() でディレクトリへのシンボリックリンクを別処理してエラーではない値を返すべきか？

**Comment by k-takata** [comment]
VC11 では _stat() は正しく動作しそうです。
VC10 の対処を入れたパッチを作ってみましたが、ずいぶん大きくなってしまいました。
https://bitbucket.org/k_takata/vim-win32-mq/src/577d881e3df107c3a19edfb0f204d7358440e429/update-rmdir.patch

**Comment by koron** [comment]
以後は vim_rmdir_r の問題を以下の2つに分けて考えましょう。
1.  ディレクトリ内を列挙する方法
2.  シンボリックリンクへの対応

また vim_rmdir_r のゴールは「コマンドラインの `rm -r` と同じ動作をすること」としましょう。

**Comment by koron** [comment]
で、その前提に立つと
vim_rmdir_r にシンボリックリンクを渡した時は、リンクだけを消してリンク先の中身は消さないというのが正しいのですね。

**Comment by koron** [comment]
だとすると
https://bitbucket.org/k_takata/vim-win32-mq/src/8126f6573e55dcad4eb19e045ea8d3444c1c1ad6/update-rmdir.patch#cl-49
この部分、ループの内側でのシンボリックリンクかどうかの判定は不要となりそうですが…

@k-takata どうですか?

**Comment by koron** [comment]
@k-takata 2 「シンボリックリンクへの対応」 について考えた結果 vim_rmdir_r 自体はこんな感じにしてみました。
https://gist.github.com/koron/6367784/72490b13cebc191f4c82ce657bec417b7c201546

FEAT_SYMBOLIC_LINKS が設定された場合は以下を満たす、と定義してます。
-   関数 mch_is_symbolic_link が提供される
-   関数 mch_remove はディレクトリへのシンボリックリンクを、正しくリンクだけ消せる

こんな風にできるでしょうか?

ちょっと FEAT_SYMBOLIC_LINKS っていうのとは意味合いが違う気がしますが
プラットフォーム (mch_*) がシンボリックリンクをサポートしているかどうかのフラグという意味です。
もっと良い名前があったら是非変えてください。

**Comment by koron** [comment]
> vim_rmdir_r のゴールは「コマンドラインの `rm -r` と同じ動作をすること」としましょう

唯一違うのは `rm -f SOMEFILE` とした時に失敗する(vim_rmdir_r)か成功する(コマンドライン)か。

**Comment by koron** [comment]
https://gist.github.com/koron/6367784/19d5dffbbfbac34a654a52709cd93b8dd8ef0870

1の「ディレクトリ内を列挙する方法」を個別に実装・改良できるように vim_listdir_sub 関数としてくくりだしてみました。
path には呼び出し側の責任でディレクトリだけが渡される想定です。

あ、動作確認はしてません。

**Comment by koron** [comment]
`rm -r` に寄せたほうが綺麗になった。

https://gist.github.com/koron/6367784/7fdbd86af911db5f8ba6bfc0ab37529dbbfb0f79

それに伴い vim_rmdir_r を vim_remove_r に名称変更してみた。

**Comment by koron** [comment]
[パッチ更新しました](https://bitbucket.org/koron/vim-kaoriya-patches/src/cfc910d25fa178f24ec82ef4a46d2d61852cba7b/X004-eval_rmdir.diff?at=default)。
上記に加えてコメントの修正とevalからの呼び出しの意味が違っちゃったのを修正。

あ、docの修正取り込んでないや…今日はここまで。

**Comment by k-takata** [comment]
追加パッチを更新しました。Windowsでは動いているようです。
https://bitbucket.org/k_takata/vim-win32-mq/src/7ee30dacbcfecbb1278826c89a41d8df4bfebac4/update-rmdir.patch
- vim_listdir_sub() の中で、ga_grow() の戻り値をチェックしていなかったのを修正。
- vim_listdir_sub() の中で、gap->ga_len の値を増やしていなかったのを修正。
- #define FEAT_SYMBOLIC_LINKS を追加。(os_unix.h, os_win32.h)
- os_win32.c / mch_remove() を、Unix と同じように、ディレクトリへのsymlink (or junction) を削除できるように修正。

vim_listdir_sub() って、わざわざ末尾に _sub を付けずとも vim_listdir() でもよくありませんか。

**Comment by koron** [comment]
> vim_listdir_sub() って、わざわざ末尾に _sub を付けずとも vim_listdir() でもよくありませんか。

引数を mch_isdir() で チェックする vim_listdir() を作って vim_listdir_sub() を呼びたいなと。

**Comment by k-takata** [comment]
なるほど。

**Comment by k-takata** [comment]
Linuxでの動作も確認できました。Macは持っていないので分かりません。

**Comment by koron** [comment]
https://bitbucket.org/koron/vim-kaoriya-patches/src/bcbd27985906a91f0e2170f996f5af22c7250fbd/X004_02-win_stat_simplify.diff?at=default

Win の stat のパッチ、こんな風に関数に切り出したほうが見通しが良いです。

**Comment by k-takata** [comment]
> Win の stat のパッチ、こんな風に関数に切り出したほうが見通しが良いです。

そうですね。そうしましょう。
stat_symlink_aware() と wstat_symlink_aware() でコメントの位置が違っているのと、引数の型が違っているのがちょっと気になりました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a8b2853bad9338492fddbb4d4211b8af0126855e/update-rmdir.patch

あとは、MacOS Xの場合に、#define FEAT_SYMBOLIC_LINKS をどこに追加すべきなのかが気になっていますが、os_mac.h なのでしょうか？

**Comment by koron** [comment]
_wstat は struct _stat なので、 wstat_symlink_aware も struct _statであるべきじゃないですかね?
加えて、もとからあるソースコードにはなるべく手を付けないほうが、変更点が強調されて読むときにわかりやすいかなと。

あとの課題はMacVimと、listのところか…

**Comment by koron** [comment]
あ。MacVimは一応MBA持ってるのでコンパイルできると思うけど
コンパイル手順まったく知らない&構築している時間がない。
だれかまとまった情報しりません?

**Comment by k-takata** [comment]
> _wstat は struct _stat なので、 wstat_symlink_aware も struct _statであるべきじゃないですかね?

そうかも。では、コメントの順番だけ修正をお願いします。

> listのところか…

list？

**Comment by koron** [comment]
glob 使ってて (´・ω・`) なところ。

なんかあれは後々ハマる気がする。

**Comment by koron** [comment]
> _wstat は struct _stat なので、 wstat_symlink_aware も struct _statであるべきじゃないですかね?

wstat_symlink_aware 内の stp のキャストは外すべきだったw
直します。

**Comment by koron** [comment]
os_win32.c の `mch_remove(char_u *name)` の

``` c
if (mch_isdir(name) && mch_is_symbolic_link(name))
    return mch_rmdir(name);
```

ここ、スゴい不自然に感じるんですがこういうものなんですかね。
関数の位置づけとしては
「ディレクトリへのシンボリックリンクならばリンクだけを削除、ディレクトリの実体は維持」にも関わらず
ソースコード上は「～ならばディレクトリとして削除(実体も削除されちゃう?!)」っていう風に読めます。

**Comment by k-takata** [comment]
> glob 使ってて (´・ω・`) なところ。

ああ、そういうことですか。

> ここ、スゴい不自然に感じるんですがこういうものなんですかね。

上にも書いたように、ディレクトリへのシンボリックリンクをリンクだけ削除するのに使うのは RemoveDirectory() API なので、素直に現状の mch_\* を使って実装するとそうなってしまうと思います。
確かに、コードを読むとギョッとしてしまうのでコメントを追加しておくのが親切なのでしょうが。

**Comment by koron** [comment]
了解。一応コメント入れておきました。

https://bitbucket.org/koron/vim-kaoriya-patches/src/1bf5a02f95dbc25e97ce053adbfa2447f63e46e0/X004_01-rmdir_support_symlinks.diff?at=default#cl-237

**Comment by koron** [comment]
ちなみに私の手元で symlink 対応のパッチと rmdir-r のパッチを分けているのは
「symlink だけ先に本家へマージさせる手もあるかもなぁ」
と考えているからです。

**Comment by k-takata** [comment]
分けた方が修正意図が明確になって分かりやすいと思います。
が、symlink 単体だとこれを使っているものがないので、先にマージしてもらうメリットがない気も…

後はテストですか。

**Comment by koron** [comment]
> symlink 単体だとこれを使っているものがない

symlink 使ってると mch_remove が Win と UNIX で動作違うよ、みたいなコンテキストが作れると良いんですけどね。

> 後はテストですか。

ですね。

**Comment by k-takata** [comment]
コメントの修正です。list upは和製英語だそうです。

``` diff
--- a/src/misc2.c
+++ b/src/misc2.c
@@ -6643,7 +6643,7 @@
 #endif

 /*
- * List up entries in the directory into garray_T, for internal usage.
+ * List entries in the directory into garray_T, for internal usage.
  *
  * Return OK or FAIL.
  */
```

**Comment by koron** [comment]
あざすw

**Comment by k-takata** [comment]
7.4.235でX004_01-rmdir_support_symlinks.diffとコンフリクトが発生したため、要修正です。
https://bitbucket.org/k_takata/vim-ktakata-mq/commits/172ca38165a5320a7e678e9e666d17df40203c6e

**Comment by k-takata** [comment]
rmdir()
https://groups.google.com/d/topic/vim_dev/3hVDTWmjSaY/discussion

>    Is there any particular reason why there is a VimL function to
> delete files (equivalent of unlink(2)), but there isn't any function to
> remove directories (equivalent of rmdir(2))?

**Comment by h-east** [comment]
patch 7.4.1107
https://github.com/vim/vim/commit/da440d21a6b94d7f525fa7be9b1417c78dd9aa4c

Can we close this issue?

**Comment by h-east** [comment]
patch 7.4.1109
https://github.com/vim/vim/commit/4cf7679383dca81a4a351e2b0ec333c95d6d9085

 だが、AppVeyorでコケてる。path separator...

```
From test_alot.vim:
Found errors in Test_with_directories():
function Test_with_directories line 15: Expected 'Xdir3/Xdir4/file' but got 'Xdir3\Xdir4\file'
function Test_with_directories line 17: Expected 'Xdir?/*/nofile' but got 'Xdir3\Xdir4\file'
TEST FAILURE 
NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.
Command exited with code 2
```

**Comment by h-east** [comment]
patch 7.4.1111
https://github.com/vim/vim/commit/f60b796fa9870bdfc4cdeb91653bac041916077d

AppVeyor pass:+1:

**Comment by k-takata** [comment]
パッと見たところディレクトリへのsymlinkの考慮がされてないようなので、どうすべきか検討が必要ですね。

**Comment by k-takata** [comment]
メモ：
Linuxのコマンドラインから、ln -s dir1 dir2 として、ディレクトリ dir1 へのシンボリックリンクを作成した場合、rm -rf dir2 では dir2 のみが削除されるが、rm -rf dir2/ では dir2 は削除されず、リンク先の dir1 が中身を含めてすべて削除される。

追記：
rm -rf dir2/ で、リンク先の dir1 の中身がすべて削除された場合でも、dir1 の中に他へのシンボリックリンクが含まれていた場合、そのリンク先は削除されない。

**Comment by k-takata** [comment]
7.4.1114でsymlink対応が入りましたが、Windowsでの対応が不十分です。
修正パッチを投げました。
https://groups.google.com/d/msg/vim_dev/edBTg-JSK9E/mEl2XC6aBgAJ

**Comment by k-takata** [comment]
7.4.1128
https://groups.google.com/d/topic/vim_dev/BlPeuSkYwOs/discussion
