### ISSUE TITLE
Travis CIでVimのビルドテストをする

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/issues#410]
vim_devで[要望](https://groups.google.com/d/msg/vim_dev/OlkOgDEDAq0/pz6M3_gM4-UJ)があがっていたので、おもむろにやってみました。
https://github.com/crazymaster/vim
https://travis-ci.org/crazymaster/vim

**Comment by msmhrt** [comment]
通常ビルドがコケるのは珍しいですけど、デバッグビルドがコケることは結構あるみたいですね。

**Comment by crazymaster** [comment]
やるとしたらこんな感じかな

```
git fetch upstream
git rebase master upstream/master
git branch tmp
git checkout master
git merge tmp
git branch -d tmp
```

**Comment by crazymaster** [comment]
今hg-git使ってるのか
https://github.com/vim-jp/vim/wiki/HowToMirror
git-hg...

**Comment by mattn** [comment]
いいかんじすねー。

https://travis-ci.org/crazymaster/vim/builds

**Comment by crazymaster** [comment]
とりあえずこれでいいかな。
報告の通りテストはコケるけど。

**Comment by koron** [comment]
.travis.yml と vim-jp/vim の submodule したレポジトリを作るのはどうだろう?

vim-jp/vim の webhook で travis-ci をトリガーできれば、vim-jp/vim に触らずにできるのでええ感じじゃないですかね。

**Comment by koron** [comment]
一応作っては見た。

https://github.com/vim-jp/vim-ci
https://travis-ci.org/vim-jp/vim-ci

**Comment by koron** [comment]
なんかそう簡単では無さそうw

**Comment by mattn** [comment]
`git submodule update --init && cd vim && ...`

**Comment by mattn** [comment]
submodule を `git@` で作らず `git://` で作るといいです。

**Comment by mattn** [comment]
おぉ？

**Comment by koron** [comment]
ん…変えてみたけどダメっぽい?

**Comment by mattn** [comment]
あぁ、志村ー！スラッシュ！

**Comment by mattn** [comment]
`git://github.com:vim-jp/vim.git` → `git://github.com/vim-jp/vim.git`

**Comment by koron** [comment]
スマヌーサ ///

**Comment by mattn** [comment]
ゴクリ...

**Comment by koron** [comment]
で、あとは vim-jp/vim が更新された時に vim-jp/vim-ci をビルドする設定があれば…(ﾟＡﾟ;)ｺﾞｸﾘ

**Comment by koron** [comment]
`git submodule update --init`

なんかコレは勝手にやってくれるみたいね。

**Comment by mattn** [comment]
完走はしたっぽい

https://travis-ci.org/vim-jp/vim-ci/jobs/8003283

**Comment by crazymaster** [comment]
> なんかコレは勝手にやってくれるみたいね。

http://about.travis-ci.org/docs/user/build-configuration/#Updating-Git-Submodules

**Comment by crazymaster** [comment]
vim-jp/vimが更新されたら、vim-jp/vim-ciでpullしてcommitする感じですかね。

**Comment by koron** [comment]
ああ、それでいいのか。

**Comment by crazymaster** [comment]
http://vim-wiki.mawercer.de/wiki/vim-development/development.html

> Adding .patch to a pull request yields the diff file
> Currently two exist:
>    https://github.com/vim-jp/vim (very current, only master branch)
>    https://github.com/b4winckler/vim (lacks behind 2 days - on 5. Juni 2013, all brannches)
> TODO: Which one should we prefer making pull requests against for what reasons? 

とあったので、pull requestした時にテストが実行されると嬉しいかなと思っていたけど、
まあこれはこれでいいか,,,

**Comment by koron** [comment]
> pull requestした時にテストが実行されると嬉しいかなと思っていた

vim-jp/vim (本家) に `.travis.yml` を入れて貰えれば vim-jp/vim-ci はそもそも要らなくなるし
加えて pull request でテストが走りますから、それで良いのでは?

**Comment by crazymaster** [comment]
その手があったか:exclamation:

**Comment by mattn** [comment]
githubに限った物じゃないし、サブディレクトリじゃない版、vim_devに送ってみたらどうだろ。運良く取り込まれたらvim-jp/vim
には手を付けなくても良くなる。

On 6/12/13, MURAOKA Taro notifications@github.com wrote:

> > pull requestした時にテストが実行されると嬉しいかなと思っていた
> 
> vim-jp/vim に `.travis.yml` を入れて貰えれば vim-jp/vim-ci はそもそも要らなくなるし
> 加えて pull request でテストが走りますから、それで良いのでは?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/410#issuecomment-19321260

## 
- Yasuhiro Matsumoto

**Comment by koron** [comment]
> githubに限った物じゃないし

ここのところ詳しく。 
code.google.com/p/vim から直接とって実行できたら
スゴイ嬉しいんだけど…

**Comment by koron** [comment]
このテストがコケてるのはなんでなんだぜ?
むしろそれはそれでなおさんと。

**Comment by koron** [comment]
@crazymaster とりあえず送ってみませんか?

このファイルを置いてくれれば travis-ci にそのままかけられて cool なんだがどうだ?

みたいな感じで。

**Comment by crazymaster** [comment]
> githubに限った物じゃないし、サブディレクトリじゃない版、vim_devに送ってみたらどうだろ。

今の所githubだけしか使えないような

**Comment by crazymaster** [comment]
あー、こんなものを見つけてしまったんですけど
[drone.ioで継続的インテグレーション — そこはかとなく書くよん。](http://tdoc.info/blog/2013/04/02/droneio.html)
使い勝手とかどうなんだろう

**Comment by crazymaster** [comment]
drone.io は pull request でテストが走らないぽいな
https://github.com/drone/docs.drone.io/pull/15

**Comment by mattn** [comment]
あ、でしたっけ…残念

On 6/12/13, master notifications@github.com wrote:

> > githubに限った物じゃないし、サブディレクトリじゃない版、vim_devに送ってみたらどうだろ。
> 
> 今の所githubだけしか使えないような
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/410#issuecomment-19322970

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
drone.io いいすよ。めちゃ使ってます。

On 6/12/13, master notifications@github.com wrote:

> あーこんなものを見つけてしまったんだが
> [drone.ioで継続的インテグレーション —
> そこはかとなく書くよん。](http://tdoc.info/blog/2013/04/02/droneio.html)
> 使い勝手とかどうなんだろう
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/410#issuecomment-19323608

## 
- Yasuhiro Matsumoto

**Comment by koron** [comment]
https://drone.io/github.com/vim-jp/vim/1

いまビルド中だが、コケそうな予感。

**Comment by koron** [comment]
ちなみに設定はコレだけ。

```
./configure --with-features=huge --enable-perlinterp --enable-python3interp --enable-rubyinterp --enable-luainterp --enable-fail-if-missing
make
make test
```

apt-get install も入れといたほうが良かったなぁ、と後悔中w

**Comment by koron** [comment]
入れて再 build 中

https://drone.io/github.com/vim-jp/vim/2

**Comment by crazymaster** [comment]
> https://drone.io/github.com/vim-jp/vim/2

ブラウザが固まるなあ

**Comment by koron** [comment]
固まりますなぁw

**Comment by koron** [comment]
ブラウザだけじゃなく、ビルドプロセスも止まってるくさい?

**Comment by koron** [comment]
とりあえず Vim では drone.io 使えないっぽい。
テスト時の表示が多すぎるのが原因かもだから /dev/null に捨てちゃおっか?

**Comment by koron** [comment]
Build の cancel もできないお…

**Comment by crazymaster** [comment]
実機でやってみたらtest86がコケて、スワップファイルから復元するかどうかきかれますね。
たぶんそこでとまっているのでしょう。
これタイムアウトがないっぽいから、いつまでもテストが終わらないんじゃなかろうか :dizzy_face:

**Comment by koron** [comment]
テストの時はスワップファイル作らない設定にすれば良い、のか?

**Comment by koron** [comment]
vim-jp/vim-ci ですが、あとで vim-jp/vim を更新する時に自動更新するようにしてみます。
その他いくつか試したいことが。

**Comment by h-east** [comment]
> 実機でやってみたらtest86がコケて、スワップファイルから復元するかどうかきかれますね。

あー、以前追加したテストコードのデバッグしている時、鬱陶しいなぁ、なんとかしたいなぁと思ってました。
このpatchで直るはず。

``` diff
diff -r a1c85064b551 src/testdir/Makefile
--- a/src/testdir/Makefile  Wed Jun 12 17:12:24 2013 +0200
+++ b/src/testdir/Makefile  Thu Jun 13 01:47:49 2013 +0900
@@ -49,7 +49,7 @@

 $(SCRIPTS) $(SCRIPTS_GUI): $(VIMPROG)

-RM_ON_RUN = test.out X* viminfo
+RM_ON_RUN = test.out X* viminfo .test*.in.sw?
 RM_ON_START = tiny.vim small.vim mbyte.vim mzscheme.vim lua.vim test.ok
 RUN_VIM = $(VALGRIND) $(VIMPROG) -u unix.vim -U NONE --noplugin -s dotest.in
```

> テストの時はスワップファイル作らない設定にすれば良い、のか?

それが正解かも:+1:

**Comment by crazymaster** [comment]
> @crazymaster とりあえず送ってみませんか?
> このファイルを置いてくれれば travis-ci にそのままかけられて cool なんだがどうだ?
> みたいな感じで。

お任せします :)

**Comment by crazymaster** [comment]
vim-ciのコミットメッセージ、過去のが残ってしまっているみたい

**Comment by koron** [comment]
> vim-ciのコミットメッセージ、過去のが残ってしまっているみたい

もう直ってます。
コミットメッセージを作るのに14 までは間違って `git log -l 1` してたので
全部(--depth=50 してるので過去50個)出てました。
15 からは `git log -n 1` に直しました。

**Comment by crazymaster** [comment]
vim-jp/vim-ci で一応実現したので閉じます？

**Comment by koron** [comment]
@crazymaster ですね。ありがとうございます!

**Comment by koron** [comment]
https://gist.github.com/koron/5994247

今後の資料として mirror に使ってるスクリプト貼っておきます。
[ミラーレポジトリをつくる手順](https://github.com/vim-jp/vim/wiki/HowToMirror) にも記載済み。
あ vim-ci の作り方みたいなのも書いたほうが良いか?

**Comment by koron** [comment]
> あ vim-ci の作り方みたいなのも書いたほうが良いか?

そのうち。

**Comment by crazymaster** [comment]
``` bash
vim_dir='/home/koron/vim/vim-hg'
ci_dir='/home/koron/vim/vim-ci'
```

のところですけど

``` bash
vim_dir='$PWD/vim/vim-hg'
ci_dir='$PWD/vim/vim-ci'
```

の方が良くないですか？

まあ、どっちでもいいか

**Comment by koron** [comment]
やるなら config ファイルの外出しでしょう。が、私の方でやる予定はしばらくありません。
