### ISSUE TITLE
ノーマルモードでのマルチバイト文字列の入力はそのまま挿入してほしい

### ISSUE THREAD

**Issue by ayechan** [vim-jp/issues#412]
お初にお目にかかります。

Vim を愛用しています。Vimがこうだったら良いなと思うことがあるのですが、どのようにすれば実現出来るのか分からずこちらに投稿してみます。

VIm はモードを持つのですが、IMEもまたモードを持つので、日本語テキストの編集を行おうと思うと、Vim をインサートモードにしてその後、IMEをオンにする必要があり、厄介です。

例えば、ノーマルモードであっても、マルチバイト文字が入力されたら、それをカーソル位置に挿入するということはできないでしょうか？

これが可能であれば、IMEのオンオフにのみ注意を払えば良いので、日本語入力がずっと楽になります。そのようなことは可能でしょうか？Vim本体に修正が必要な案件になりますでしょうか？

（日本語入力固定モードを提供するプラグインやノーマルモードに戻ったらIMEを自動的にオフにする方法あるのは知っています。もっと踏み込んで日本語入力を楽にする方法として上のようなことが出来れば良いと思いました。）

**Comment by thinca** [comment]
@kana さんが独自にパッチを作っているようです。
http://repo.or.cz/w/vim-kana.git?a=shortlog;h=hack/ncmdundefined
https://github.com/kana/config/blob/master/vim/personal/dot.vimrc#L2326
このパッチは、ノーマルモードで存在しないコマンドが実行された時に発生する `NCmdUndefined` イベントを新しく追加し、これを利用してマルチバイト文字が入力された時には自動で挿入モードになるような設定が vimrc で行われています。
本家にはないパッチなので、使う場合は独自に当てる必要があるかと思います。

**Comment by ayechan** [comment]
@thinca さん、早速のコメントありがとうございます。
要望を叶えられるパッチがすでに存在するのですね。
時間を見つけてビルドを試してみたいと思います。
もし、これを本家に採用してもらおうと思った場合は、どんな風に働きかけるのが適切でしょうか？

**Comment by mattn** [comment]
背景含めて別解(パッチはないです)。

まずご存知の様にvimは世界で使われているテキストエディタで、日本人が想像しない使い方をしている人も海外にはいます。たとえばenc=latin-1やutf-8でモードの無い入力機構を使ってウムラウトを直接入力し、そのウムラウトをnmapして何かのアクションにしている人もいます。この状況でマルチバイトだから確定前にインサートモードに戻すのは難しいです。
またその人たちは`fFtT`でウムラウトを検索したりもします(おかげで`cf。`も動作します)。つまり安直に提案するとノーマルモードだから…という前提だけで覆される可能性もあります。ワークアラウンドを除いては。

で、現実的なパッチで対応するとした場合、入力されたコード範囲で判定するかIME状態で判定するかになります。CursorIMが表示されたかを判定してされてればインサートモードに戻すという手もあります。ただし端末版で使えないという弱点があります。
ちなみにご存知の様にIMEの状態は取得する事は出来ても設定はWindows
GUI以外出来ないので、ついでにIMEのモードも、というのは色んなワークアラウンドを使わないと出来ません。

残るワークアラウンドは一番最初に出てきたワークアラウンドの話で、コード値を見てインサートモードに戻す動作を設定できるオプションを新設すると言うものです。そのコード値の範囲を設定出来るのがベストな気がします。
以上が、マルチバイトに限定で反応するインサートモードへ戻すパッチ草案です。
携帯から打つの疲れた。

**Comment by koron** [comment]
「日本語入力で楽ができるから」ではない別の理由を付けられれば確率は高まるでしょう。

そもそも「入力モードにした時に連動してIMEをONにし、また出るときにOFFにする機能」ならば既にあります。
だから「それのalternativeになるよ」という提案は往々にして「なんでいるの?」となります。

**Comment by koron** [comment]
補足

> IMEの状態は取得する事は出来ても設定はWindows GUI以外出来ない

Ubuntuの ibus (+mozc) では簡易パッチで一応できてる。たまにバグるけどw

**Comment by ayechan** [comment]
皆様、詳細な事情説明ありがとうございました。
私が最初に考えていたほど単純な問題ではないことがわかりました。
ひとまずは、クローズさせていただこうと思います。

**Comment by koron** [comment]
面白い提案ではあった。
それを実現するパッチも存在した。
ただし vim-dev に働きかけるほどの求心力はなかった。
故に wontfix となった。
