### ISSUE TITLE
make test を使い勝手良く

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#414]
travis-ci などに組み込む時に欲しいと思った要件を列挙します。
-   入力待ちで止まるのを避けたい
-   コンソールへの出力内容を減らしたい
  -   成功時は寡黙に、失敗時は饒舌に
  -   ~~ログファイルに吐いてあるとなお良い~~
-   ~~テスト結果の一覧が欲しい~~

**Comment by koron** [comment]
https://github.com/vim-jp/issues/issues/410#issuecomment-19340225

> > 実機でやってみたらtest86がコケて、スワップファイルから復元するかどうかきかれますね。
> 
> あー、以前追加したテストコードのデバッグしている時、鬱陶しいなぁ、なんとかしたいなぁと思ってました。
> このpatchで直るはず。

``` diff
diff -r a1c85064b551 src/testdir/Makefile
--- a/src/testdir/Makefile  Wed Jun 12 17:12:24 2013 +0200
+++ b/src/testdir/Makefile  Thu Jun 13 01:47:49 2013 +0900
@@ -49,7 +49,7 @@

 $(SCRIPTS) $(SCRIPTS_GUI): $(VIMPROG)

-RM_ON_RUN = test.out X* viminfo
+RM_ON_RUN = test.out X* viminfo .test*.in.sw?
 RM_ON_START = tiny.vim small.vim mbyte.vim mzscheme.vim lua.vim test.ok
 RUN_VIM = $(VALGRIND) $(VIMPROG) -u unix.vim -U NONE --noplugin -s dotest.in
```

**Comment by koron** [comment]
test87を見る限り、スワップファイルはテストケース毎に先頭で無効化する方針かも。漏れがあることが問題か。

> テスト結果の一覧が欲しい

UNIXでは test.log に吐いておいて最後に report ターゲットで出してた。
Windows (Make_dos.mak) には同様の機構は無い。

**Comment by koron** [comment]
> > テスト結果の一覧が欲しい
> 
> UNIXでは test.log に吐いておいて最後に report ターゲットで出してた。
> Windows (Make_dos.mak) には同様の機構は無い。

https://gist.github.com/koron/5791477

作った。今から vim-dev に投げる。

**Comment by koron** [comment]
> 今から vim-dev に投げる。

https://groups.google.com/d/msg/vim_dev/FIK_R5f-85A/Erl_uSVZFPkJ

Done it.

**Comment by h-east** [comment]
@koron GJ!
vim_devは3連続日本人投稿だw

**Comment by k-takata** [comment]
7.3.1212 で取り込まれました。
https://groups.google.com/d/msg/vim_dev/PsKXXZipDqg/vJi4IzY5XYAJ

**Comment by koron** [comment]
あとは

> コンソールへの出力内容を減らしたい

コレをどうするか、ってところですかねぇ。

**Comment by k-takata** [comment]
Unix だと test が失敗すると、test??.failed というファイルが作成されるのですが、Windows だと作成されないのでテストの実行結果が分かりにくいです。あと、テストが成功しても、ファイルが見つからない等の不要なエラーメッセージが表示されるのが邪魔です。
https://bitbucket.org/k_takata/vim-win32-mq/src/4e5d388ca2e2b742f1b734f02404a9cada6ad042/update-make_dos.patch

**Comment by koron** [comment]
@k-takata :+1: 送っちゃってください。

> ファイルが見つからない等の不要なエラーメッセージが表示されるのが邪魔

これの対応のために rename を move に変えたってことですか?

**Comment by koron** [comment]
> コンソールへの出力内容を減らしたい

これなんだけど UNIX なら /dev/null に、 Win なら NUL にリダイレクトしちゃえばかなり軽減された。やるべきだろうか?
やってみて Bram の判断を仰いじゃったほうが良いかな?

**Comment by k-takata** [comment]
> これの対応のために rename を move に変えたってことですか?

そうです。他のところでは if exist ～ にしているところもありますが、move /y ならエラーメッセージも出さずに一発なので。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/FIK_R5f-85A/9Ex38GYH8lcJ

**Comment by k-takata** [comment]
7.3.1218 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/QyrvBDYiX60/discussion

**Comment by mattn** [comment]
closable?

**Comment by koron** [comment]
あとこれ。

> コンソールへの出力内容を減らしたい

コンソールに出さなきゃテスト実行速度上がる、みたいなコンテキストで出したい。
*.failed があることで、失敗した時にどうやって情報取るんだ、ってところはクリアできる。
あとは失敗時に止まっちゃうテストをなんとかすれば、いけるんじゃなかろか。

**Comment by k-takata** [comment]
vim_dev でテストの改善提案が出ています。
https://groups.google.com/d/msg/vim_dev/5rCtB5zTZu4/zB7FFc3bJQ4J

**Comment by koron** [comment]
そろそろ具体的な課題のissueにわけて、コイツ自体は閉じる時期かな?

**Comment by koron** [comment]
closed.
