### ISSUE TITLE
tablineオプションに指定した関数内でgettabwinvar()を使用しているとその後に作成したタブでビジュアルモードに入れなくなる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#415]
@daisuzu さんのブログより。
[Vimでビジュアルモードに入れなくなった](http://daisuzu.hatenablog.com/entry/2013/06/15/005716)

> Vimを更新したら新規タブを開いた後にv系のキーが効かなくなった。
> 確認したのはMac、Linux(Gentoo)、Win7。
> ...
# 

こちらでも再現しました。(fedora17 64bit, Vim 7.3.1195)
~/vimrc_foo

``` vim
set tabline=%!Foo()
set guioptions-=e                        ” GVim時のみ必須
function! Foo()
    return gettabwinvar(1, 0, 'foo')
endfunction
```

```
$ vim -N -u ~/vimrc_foo --noplugin -c tabnew
```

これでビジュアルモードに入れなくなります。

備考:
- 最初のタブ(`tabfirst`)ではビジュアルモードに入れる。
- ~/vimrc_fooの`set tabline=%!Foo()`の代わりに`set statusline=%!Foo()`でも発生する。
- `gettabwinvar(1, 0, 'foo')`を`gettabvar(1, 'foo')`にした場合は発生しない。

**Comment by h-east** [comment]
画面再描画地獄(screen redraw of hell)が起きてます。
1. `:tabnew` でタブページが追加され、カレントタブページが`2`になる。
2. タブページ追加されたので画面全体の再描画がおこなわれる。`update_screen()`
3. 画面全体なので当然tabline部分の描画処理も走る。`draw_tabline()`
4. tablineオプションの設定に基づき、ユーザ関数`Foo()`経由で `gettabwinvar()` が呼ばれる。
5.  `gettabwinvar()`の第1引数は1番目のタブページを指定している(カレントタブページ`2`と異なる)ので内部的にタブページ&ウィンドウの切り替えが発生。`switch_win()`
6. タブページ切り替えが発生すると **ビジュアルモードがキャンセル**される。<br>`switch_win()`→`leave_tabpage()`→`reset_VIsual_and_resel()`→`end_visual_mode()`
7. 同様に全描画フラグが立てられる。<br>`switch_win()`→`goto_tabpage_tp()`→`enter_tabpage()`<br>must_redraw = CLEAR;        /\* need to redraw everything */ [window.c:3782]
8. 一連の`update_screen()`処理完了。
9. ユーザの`V` 入力により、ビジュアルモード移行処理が呼ばれる。
10. `update_screen()`で必要な部分だけ画面更新と思いきや `must_redraw = CLEAR` になってしまっているので、画面全体の再描画になってしまう。[screen.c:340]
11. `3.`～`8.`を処理する。が、`6.`でビジュアルモードがキャンセルされる！！ヒィィィィ
12. 以後殆どの操作で`3.`～`8.`が走る。まさに画面再描画地獄！ヒヤァァァァ

# 

うーん、`switch_win()`経由の`enter_tabpage()`や`leave_tabpage()`ではビジュアルモードをキャンセルしたり全描画フラグを立てたりしないように制御すれば良いだけかな？影響範囲デカいなｗ

**Comment by h-east** [comment]
このpatchで直るのを確認＆test ALL DONEを確認。
ちょっとビミョー。
`getwinvar()`をPatch 7.3.963適応前に戻した感じに近い。
組み込み関数getwinvar()は[Patch 7.3.963](https://groups.google.com/d/msg/vim_dev/JhQt4e7kBnA/xS7FmWLyPeIJ)の修正思想をモロに反映させなくても良いと思うのです。
指定タブページ内のウィンドウのウィンドウローカル変数値を取得するだけなので、そのためだけに(一時的にカレントタブページが変化したからといって)ビジュアルモードがキャンセルされたり画面全体の再描画がされたら堪らない。
7.3.963の修正思想として一応処理を`block_autocmds()` ～ `unblock_autocmds()`で囲っておいた。
これをenglishで説明するのが大変だｗ

``` diff
diff -r c1170f618303 src/eval.c
--- a/src/eval.c    Fri Jun 14 22:48:54 2013 +0200
+++ b/src/eval.c    Sun Jun 16 03:37:34 2013 +0900
@@ -11950,9 +11950,15 @@

     if (win != NULL && varname != NULL)
     {
+# ifdef FEAT_AUTOCMD
+   block_autocmds();
+# endif
    /* Set curwin to be our win, temporarily.  Also set the tabpage,
     * otherwise the window is not valid. */
-   switch_win(&oldcurwin, &oldtabpage, win, tp);
+   oldcurwin = curwin;
+   curwin = win;
+   curbuf = win->w_buffer;
+

    if (*varname == '&')    /* window-local-option */
    {
@@ -11972,7 +11978,11 @@
    }

    /* restore previous notion of curwin */
-   restore_win(oldcurwin, oldtabpage);
+   curwin = oldcurwin;
+   curbuf = curwin->w_buffer;
+# ifdef FEAT_AUTOCMD
+   unblock_autocmds();
+# endif
     }

     if (!done && argvars[off + 2].v_type != VAR_UNKNOWN)
```

**Comment by Shougo** [comment]
@h-east++

まぁ、もともとは（一時的にタブを切り替えればいいという）gettabwinvar()の強引な実装が原因のような気はしますね……。

**Comment by h-east** [comment]
お得意のCRAZY Englishで投稿しました。
https://groups.google.com/d/msg/vim_dev/mPeVWEN0muo/QeviuqTvMXAJ

**Comment by h-east** [comment]
Patch 7.3.1204 で修正されました。
https://groups.google.com/d/msg/vim_dev/BM6MAtzU2EQ/hQOJyBa6cfoJ

私のアドホックなpatchではなく、Bram氏が正当なpatchを速攻で書き上げてくれました。感謝。

**Comment by ynkdir** [comment]
おつです!

**Comment by daisuzu** [comment]
ありがとうございました！
