### ISSUE TITLE
Python が片方だとテストに失敗する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#416]
タイトル変更 ~~test87 が失敗する人います?~~ の再利用。

Python 2.X だけ使った場合 (test86) が失敗し、Python 3.X だけ使った場合 (test87) が失敗することがある。

Windows で 3.3.2 だけ使った場合は失敗しなかったが(@koron 調べ)、
Ubuntu 12.04 で 3.2.3 だけ使った場合は失敗した (@k-takata 調べ)。
## 

以下、旧内容

いたら環境を教えてください。知りたいのは主にOSとPython 3のバージョン。

travis-ci (vim-jp/vim-ci#2) 上で発生するエラーを解消したいと考えています。
が、手元の環境では発生させられず原因を突き止められず糸口も無い状態です。

**Comment by k-takata** [comment]
Ubuntu 12.04 (32bit/64bit), Python 3.2.3, Vim 7.3.1196 +python/dyn +python3/dyn で再現せず。
同じ環境で、-python +python3 に変更したところ、再現しました。

**Comment by koron** [comment]
つまり ubuntu 12.04 で、かつ -python +python3 かつ 3.2.3 の時である、ってのが条件になりそうなのね。

**Comment by koron** [comment]
Winでも試してみっか?

**Comment by k-takata** [comment]
同じ環境で、python 2.7.3 で +python -python3 にすると test86 が同様に失敗します。

**Comment by koron** [comment]
if_python_both あたりですかねぇ…

**Comment by koron** [comment]
Vimの問題としてチケットを再利用します。

**Comment by k-takata** [comment]
片方かどうかではなく、/dyn かどうかが影響しているようです。両方使う場合は必然的に /dyn になるので成功すると。
（Windowsは /dyn ではないビルドは試したことがないので未確認。）

**Comment by koron** [comment]
Windows で Python 2.7.5 と 3.3.2 それぞれにstatic リンクで試してみたけど、問題は発生しませんでした。
UNIX系固有の問題っぽいですね。

**Comment by Shougo** [comment]
Windowsはなんと言うか、共有DLL文化なだけあって、こういう問題には非常に強いですね。

**Comment by ynkdir** [comment]
if_python と regex は丸投げしちゃった方が解決が速い気がします。

**Comment by k-takata** [comment]
Bram氏自身によって報告が挙がりました。
https://groups.google.com/d/topic/vim_dev/CEaL812aLNI/discussion

**Comment by koron** [comment]
:laughing:

**Comment by ynkdir** [comment]
動的リンクで関数ポインタとるのがどうとかあるんですかね
zyx氏のとこでは動くらしいので
ubuntu固有の問題なのかもしれず

``` c
#include <Python.h>
#include <stdio.h>
int main() { return printf("%p\n", &_PyObject_NextNotImplemented); }
```

``` sh
$ cc `python-config --cflags` a.c `python-config --ldflags` -o a.out

$ readelf -W --dyn-syms a.out
シンボルテーブル '.dynsym' は 20 個のエントリから構成されています:
   番号:      値         サイズ タイプ  Bind   Vis      索引名
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
     2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.2.5 (2)
     3: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
     4: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __printf_chk@GLIBC_2.3.4 (3)
     5: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _Jv_RegisterClasses
     6: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
     7: 00000000004007b0     0 FUNC    GLOBAL DEFAULT   13 _start
     8: 0000000000400740     0 FUNC    GLOBAL DEFAULT   11 _init
     9: 0000000000400960     4 OBJECT  GLOBAL DEFAULT   15 _IO_stdin_used
    10: 0000000000601048     0 NOTYPE  GLOBAL DEFAULT   24 _edata
    11: 0000000000400954     0 FUNC    GLOBAL DEFAULT   14 _fini
    12: 0000000000601038     0 NOTYPE  GLOBAL DEFAULT   24 __data_start
    13: 0000000000601048     0 NOTYPE  GLOBAL DEFAULT   25 __bss_start
    14: 0000000000601050     0 NOTYPE  GLOBAL DEFAULT   25 _end
    15: 00000000004008c0   137 FUNC    GLOBAL DEFAULT   13 __libc_csu_init
    16: 00000000004007a0     0 FUNC    GLOBAL DEFAULT  UND _PyObject_NextNotImplemented
    17: 0000000000400950     2 FUNC    GLOBAL DEFAULT   13 __libc_csu_fini
    18: 0000000000601038     0 NOTYPE  WEAK   DEFAULT   24 data_start
    19: 00000000004008a0    22 FUNC    GLOBAL DEFAULT   13 main

$ ./a.out
0x4007a0   <- pyobjectの初期化で使われる &_PyObject_NextNotImplemented (tp_iternext) の値と違う
```

``` sh
$ cc `python-config --cflags` a.c `python-config --ldflags` -fPIC -o a-pic.out

$ readelf -W --dyn-syms a-pic.out
シンボルテーブル '.dynsym' は 20 個のエントリから構成されています:
   番号:      値         サイズ タイプ  Bind   Vis      索引名
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
     2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.2.5 (2)
     3: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
     4: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __printf_chk@GLIBC_2.3.4 (3)
     5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _PyObject_NextNotImplemented
     6: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _Jv_RegisterClasses
     7: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
     8: 00000000004007a0     0 FUNC    GLOBAL DEFAULT   13 _start
     9: 0000000000400740     0 FUNC    GLOBAL DEFAULT   11 _init
    10: 0000000000400950     4 OBJECT  GLOBAL DEFAULT   15 _IO_stdin_used
    11: 0000000000601040     0 NOTYPE  GLOBAL DEFAULT   24 _edata
    12: 0000000000400944     0 FUNC    GLOBAL DEFAULT   14 _fini
    13: 0000000000601030     0 NOTYPE  GLOBAL DEFAULT   24 __data_start
    14: 0000000000601040     0 NOTYPE  GLOBAL DEFAULT   25 __bss_start
    15: 0000000000601048     0 NOTYPE  GLOBAL DEFAULT   25 _end
    16: 00000000004008b0   137 FUNC    GLOBAL DEFAULT   13 __libc_csu_init
    17: 0000000000400940     2 FUNC    GLOBAL DEFAULT   13 __libc_csu_fini
    18: 0000000000601030     0 NOTYPE  WEAK   DEFAULT   24 data_start
    19: 0000000000400890    26 FUNC    GLOBAL DEFAULT   13 main

$ ./a-pic.out
0x7f6ecf9559d0    <- ok
```

**Comment by koron** [comment]
ubuntu ではない @h-east さんや @thinca さんによる検証が待たれる?

**Comment by h-east** [comment]
python(2.7.3)しか入っていなかったので、今 python3(3.2.3)をインスコした。ｗｗ on fedora17
今から検証しまつ。

**Comment by h-east** [comment]
``` bash
$ uname -r
3.8.13-100.fc17.x86_64
$ python --version
Python 2.7.3
$ python3 --version
Python 3.2.3
```

Vim verは7.3.1223

+python
-python3
---> ALL DONE

+python/dyn
-python3
---> ALL DONE

# 

+python3はconfigureでエラーになる。`--with-python3-config-dir=`の指定とか要る感じ？
ちょっと待ってて。

**Comment by h-east** [comment]
> +python3はconfigureでエラーになる。--with-python3-config-dir=の指定とか要る感じ？

python3-devel のinstallを忘れてた(・ω<)

``` bash
sudo yum install python3-devel
```

(続き)
-python
+python3
---> ALL DONE

-python
+python3/dyn
---> ALL DONE

+python/dyn
+python3/dyn
---> ALL DONE

fedora17では問題なしでした。

**Comment by crazymaster** [comment]
そもそもDebain系だと同時利用できないですよね
Pythonを--enable-sharedでビルドし直さない限り

#301
[vim-jp » Linuxでif_pythonを使う際のtips](http://vim-jp.org/tips/if_python.html)

**Comment by crazymaster** [comment]
Ubuntu 13.04 64bit vim 7.3.1223で +python/dyn +python3/dyn だと
同時利用以前に使おうとするとエラーが出るんですけど...

:py print(sys.version) / :py3 print(sys.version)
E448: ライブラリの関数 _PyArg_Parse_SizeT をロードできませんでした
E263: このコマンドは無効です,ごめんなさい: Pythonライブラリをロードできませんでした.

**Comment by koron** [comment]
@crazymaster コンパイルオプションわかります? vim-jp に書いてある方法ですか?

**Comment by crazymaster** [comment]
vim-jp に書いてある方法です
vim-ciのと同じやつです

**Comment by koron** [comment]
ありがとうございます。

う〜んそうすると travis-ci がなにで動いているのかが疑問になりますかね?
場合によっては Ubuntu のバージョン次第でそもそも if_py2+3 が機能しないってことですよね。

**Comment by crazymaster** [comment]
[Travis CI: The Build Environment](http://about.travis-ci.org/docs/user/ci-environment/)
Travis CI virtual machines are based on Ubuntu 12.04 LTS Server Edition 64 bit.

ちなみに実機でif_py2+3でもテストは通ります

**Comment by ynkdir** [comment]
http://docs.python.org/2/extending/embedding.html#linking-requirements
リンクには LINKFORSHARED を付けるらしいので
コンパイルには CFLAGSFORSHARED を付けるのではないかと
ドキュメントがない…

``` sh
$ python -c 'import distutils.sysconfig; print(distutils.sysconfig.get_config_var("CFLAGSFORSHARED"))'
-fPIC
```

**Comment by ynkdir** [comment]
fedora だと python の configure で -fPIC 指定してるみたいです

```
On Fedora 18
$ python -c 'import distutils.sysconfig; print(distutils.sysconfig.get_config_var("CONFIG_ARGS"))'
'--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-ipv6' '--enable-shared' '--enable-unicode=ucs4' '--with-dbmliborder=gdbm:ndbm:bdb' '--with-system-expat' '--with-system-ffi' '--with-dtrace' '--with-tapset-install-dir=/usr/share/systemtap/tapset' '--with-valgrind' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CC=gcc' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4  -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv  ' 'LDFLAGS=-Wl,-z,relro   ' 'CPPFLAGS=-I/usr/lib64/libffi-3.0.10/include  '
```

**Comment by ynkdir** [comment]
-Wl,-Bsymbolic-functions が原因

**Comment by ynkdir** [comment]
Linux の共有ライブラリの挙動について
http://d.hatena.ne.jp/dayflower/20080523/1211531833
What exactly does -Bsymblic do? -- update
http://www.technovelty.org/c/what-exactly-does-bsymblic-do-update.html
Linux 動的ライブラリーの徹底調査
http://www.ibm.com/developerworks/jp/linux/library/l-dynamic-libraries/

なんかよくわかりませんが。。。
動的リンクの場合はPLTエントリというのを経由して間接的に関数にアクセスするらしいです。
例えばfoo()という関数があったらfoo@pltというエントリができる。
で、-Bsymbolicを指定すると、同じライブラリの中の関数は他のモジュールによって上書きされないことが分かるのでpltエントリが省略される。
しかしそのライブラリを使う側はあいかわらずfoo@plt経由でアクセスしている。
その状態でそれぞれの中で関数ポインタを取ると、ライブラリ側は &foo、プログラム側は &foo@plt となって違うアドレスになる (のかな？)。

ubuntu で -Bsymbolic-functions を使わないようにしてもらうか、PyIter_Check() をマクロではなく関数にしてもらうか、vim を -fpIC or -fPIE でコンパイルするか。めんどくさそう。

ubuntu の他のプログラムも動かないはずなんですけど PyIter_Check() とかあんまり使わないんですかね。まあ使わなそうですね。。。

**Comment by k-takata** [comment]
7.4a.010
https://groups.google.com/d/topic/vim_dev/KsDKS8hszpM/discussion
直ったということでいいんでしょうかね？

**Comment by koron** [comment]
@k-takata and others: 追試可能ですか?

**Comment by k-takata** [comment]
Ubuntu 12.04.2 (x86)で、+python, +python3 それぞれで test86, test87 が通ることが確認できました。

**Comment by koron** [comment]
@k-takata ありがとうございます!
