### ISSUE TITLE
msvc で失敗するテスト 

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#417]
素の 7.3.1203 を MSVC でビルドし src/testdir で `nmake -f Make_dos.mak win32` した時に失敗するテスト一覧
-   ~~test17~~ (#409)
-   ~~test71~~
-   ~~test77~~
-   ~~test50~~

特に test17 は入力待ちになってしまい `:q!` とかしないとテストがスタックする。

**Comment by k-takata** [comment]
関連 #409

**Comment by koron** [comment]
test17 を **直す** のは #409 に任せるとして、 **入力待ちにしない** だけなら
https://bitbucket.org/koron/vim-kaoriya-patches/src/07bc456b11557c835e2d1e6a89e52951dd8b667b/test17-continuous.diff?at=default
こんな手もある。

自動でCIを回す観点で言うと `:e` については他のテストについても確認して `:e!` へ修正しておいたほうが良いかも。

**Comment by k-takata** [comment]
test71はこんなパッチで通りました。
https://bitbucket.org/k_takata/vim-win32-mq/src/87dbe66f718d38c260f50fdd64df8e8e77e90d3c/fix-test71.patch

**Comment by koron** [comment]
> test71はこんなパッチで通りました。

通るって、成功として通るんですか?
だとしたらなんか別の問題が隠れている気がするけどw

**Comment by k-takata** [comment]
もちろん成功としてです。
`:bwipe` に `!` を付けたのは、test17 と同じく dotest.in の `:set ff&` で改行コードが書き換えられてしまっているから。(test71.in は、fixff による改行コード変更の対象外。)
enc=latin1 の部分は、utf-8 だとダメでした。なぜ Unix で enc 設定無しで成功するのか分かりません。

**Comment by koron** [comment]
latin1 と utf-8 の間には確か特殊な変換ロジック(iconvを迂回)が挟まってた気がする。

**Comment by koron** [comment]
つーかよく見たら最初の `bwipe` だけ `!` 無しなのね…なんでやねんw

**Comment by koron** [comment]
test71.in について
[最初のバージョン](https://code.google.com/p/vim/source/browse/src/testdir/test71.in?spec=svnf60a0c9cbe6ceb3a575ee49815c8155cd1aeb482&r=f60a0c9cbe6ceb3a575ee49815c8155cd1aeb482) と [その次のバージョン](https://code.google.com/p/vim/source/browse/src/testdir/test71.in?r=c493d6bfde09997446ee92dc72a7e54abf3f24cc) を見比べると、なんかつけ忘れっぽくも見えますなぁ。

**Comment by koron** [comment]
+kaoriya にしたら 44 と 95 が失敗したっぽい(1214)… あるぇ?w

**Comment by k-takata** [comment]
自分のところだと test77 は失敗しませんでした。
cksum コマンドが PATH の通ったところにあるかどうかで、処理が分かれるようですが、どちらでも問題なしです。

**Comment by koron** [comment]
test77 今、内容を見ました。

cksum があるケースで成功するのはおかしいように見受けられます。
18行目で `ff=unix` しているので 26行目の `:.w! test.out` は ff=unix になってしまい
fixff で ff=dos になってる test77.ok と一致するのは変です。

@k-takata 調査、お願いします。

**Comment by koron** [comment]
test50 は `C:\x.x.y` が fnamemodify の `:p:8` で `C:/XX2235~1.Y` (マジックナンバー) に展開されることを期待している。
が実際のところ私の手元では `C:/XX9B80~1.Y` になってる。
この展開に何か環境依存の動作があるのだけどそれを考慮しきれていないみたい。

**Comment by k-takata** [comment]
> fixff で ff=dos になってる test77.ok と一致するのは変です。

あ、fixff やってなかったｗ
hg で変更として検出されてしまうので、fixff がすごい邪魔なんですよね。

**Comment by k-takata** [comment]
> この展開に何か環境依存の動作があるのだけどそれを考慮しきれていないみたい。

OSのバージョンですかね。

**Comment by koron** [comment]
> hg で変更として検出されてしまうので、fixff がすごい邪魔なんですよね。

ですね。超邪魔

**Comment by koron** [comment]
> OSのバージョンですかね。

そもそも決め打ちなのがマズイんじゃないか?

**Comment by koron** [comment]
http://elm-chan.org/docs/fat.html ここの 「SFNの生成と添字の付加」 ただしいかどうかわからんけど、なんか違いそう。

**Comment by k-takata** [comment]
9x 系と、古い NT 系と、Vista 以降でアルゴリズムが違うと予想。
XP で `x.x.y` を作ると `XX2235~1.Y` になりました。

**Comment by koron** [comment]
:shit:

**Comment by koron** [comment]
test50, 77 については修正パッチを投げました。→ [fix tests for DOS/Windows](https://groups.google.com/d/msg/vim_dev/zv9natTmHxo/mmK7nLv3CSgJ)

@k-takata それらもこのスレに投げちゃうってのはどうでしょう?

**Comment by koron** [comment]
> +kaoriya にしたら 44 と 95 が失敗したっぽい(1214)… あるぇ?w

[2007-refactor_vim_strchr.diff](https://bitbucket.org/koron/vim-kaoriya-patches/src/abaff817c68a3bdaf7be518bd6be8af578b403e9/2007-refactor_vim_strchr.diff?at=default) コイツだった。外した。

**Comment by k-takata** [comment]
test17, test71 投げました。
https://groups.google.com/d/msg/vim_dev/zv9natTmHxo/ExlYLOCdSugJ

**Comment by k-takata** [comment]
7.3.1223 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/c303AiUaimU/discussion
が、test71 はまだ失敗します。

```
0a1,10
> 01234567890123456789012345678901234567
> line 2  foo bar blah
> line 3 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> OK 01234567890123456789012345678901234567
> OK line 2  foo bar blah
> OK line 3 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 1234567890
> a畸bccdde・f
> asdfasdfasdf
> 0001112223333
```

enc=latin1にすると今度はUnixで失敗するらしいです。

**Comment by k-takata** [comment]
> enc=latin1にすると今度はUnixで失敗するらしいです。

enc=latin1 にしてから、リロードするようにしてみた。
https://groups.google.com/d/msg/vim_dev/zv9natTmHxo/2dkz5UfVZg0J

**Comment by koron** [comment]
1223で test17 失敗した…あるぇ?

test17.failed (ff=unix, first three ^M=CR)

```
This file is just to test "gf" in test 17.^M
The contents is not important.^M
Just testing!^M


--- Included files in path ---
Xdir1/dir2/foo.a
Xdir1/dir2/foo.a -->
  Xdir1/dir2/bar.a
  Xdir1/dir2/bar.a -->
    Xdir1/dir2/baz.a
    Xdir1/dir2/baz.a -->
      "foo.a"  (Already listed)


--- Included files in path ---
Xdir1/dir2/foo.b
Xdir1/dir2/foo.b -->
  Xdir1/dir2/bar.b
  Xdir1/dir2/bar.b -->
    Xdir1/dir2/baz.b
    Xdir1/dir2/baz.b -->
      foo  (Already listed)


--- Included files in path ---
Xdir1/dir2/foo.c
Xdir1/dir2/foo.c -->
  bar.c^M^@  NOT FOUND

```

**Comment by k-takata** [comment]
> 1223で test17 失敗した…あるぇ?

#409 に書いたのでこっちにはわざわざ書きませんでしたが、test17 は最後のテストがまだ失敗します。

**Comment by k-takata** [comment]
> enc=latin1 にしてから、リロードするようにしてみた。

これに対して、以下のような返事が来ました。
https://groups.google.com/d/msg/vim_dev/zv9natTmHxo/o4MoNa9ykicJ

> When running the tests reloading is not an option.
> 
> Perhaps explicitly setting 'fenc' would work? 

リロードはダメと言われてしまったようですが、リロードしないことには直らない気がするのですが…。
あるいはバイナリ部分を別ファイルにするか。

Unix系の場合、以下のようになっているため修正前のもので問題なく動作します。
- 起動時の enc は utf-8。
- test71.in を fenc=latin1 として読み込み。enc=utf-8 なためバイナリ部分もデータ欠落無しにそのまま読み込まれる。

Windowsの場合、以下のようになり、問題が起きます。
- 起動時の enc は cp932。
- test71.in を読み込んだ時点で、バイナリ部分のデータ欠落発生。fenc をあとから変更しても、欠落したデータは回復不可能。

**Comment by h-east** [comment]
--cmd "set enc=utf-8" 的な起動て無理でしたっけ？

**Comment by k-takata** [comment]
Make_dos.mak を書き換えて、test71 だけはそれを付けて起動するというのは可能なんでしょうけど、他にそんなやり方をしているテストは無いですし、あまりいいやり方には思えません。
やっぱり、↓かなぁ。

> あるいはバイナリ部分を別ファイルにするか。

**Comment by k-takata** [comment]
test71のバイナリ部分を別ファイルにしてみました。
https://bitbucket.org/k_takata/vim-win32-mq/src/dae5fb2c79c85fc662879dc9e9a3d09b6b1a1701/fix-test71.patch

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/zv9natTmHxo/hLAKn_qdMmkJ

**Comment by h-east** [comment]
Patch 7.3.1283 で取り込まれました。ナイスです。
https://groups.google.com/d/msg/vim_dev/vb9Um7dqGPI/30F0FEiD3hUJ

**Comment by k-takata** [comment]
@koron まだ test17 が残っていますが、専用 issue がありますし、入力待ちになってしまう問題は 7.3.1223 でとっくに直っているので閉じちゃいますか？ それとも、↓の確認が終わってから？

> 自動でCIを回す観点で言うと `:e` については他のテストについても確認して `:e!` へ修正しておいたほうが良いかも。

**Comment by koron** [comment]
Thank you all! I agree to close.
