### ISSUE TITLE
相対行番号表示時に関数内のredrawがうまく動いていない？

### ISSUE THREAD

**Issue by saihoooooooo** [vim-jp/issues#418]
関数の中でハイライトON → 再描画の組み合わせをしようとした時に、相対行番号表示状態だとうまく動いてくれません。
最小の.vimrcの例を書きます。

``` vim
set relativenumber
nnoremap t :<C-u>call <SID>test()<CR>
function! s:test()
    let @/ = 'a'
    set hlsearch
    redraw
endfunction
```

上記の`set relativenumber`をコメントアウトすると問題なく動作します。

**Comment by h-east** [comment]
@saihoooooooo Issue登録ありがとうございます。

こちらでも再現しました。(fedora17 64bit, Vim 7.3.874, 7.3.944, 7.3.1223)
`'hlsearch'オプション`も`@/`レジスタも正しく設定されているのにhighlightされないですね。
`t`押下後に手動で `:redraw` や `<C-L>` しても変化なし。
でも、同様に手動で `:set hlsearch` とするとhighlightされる。

`'relativenumber'オプション`がonの時に関数内で`:set hlsearch`をしたときは画面描画更新用の某かの情報が更新されない。
って感じでしょうか。

**Comment by saihoooooooo** [comment]
なるほど、`redraw`でなくて`set hlsearch`に問題があるかもしれないという事ですか。

あと補足で一応、関数内のみという証明を。
これなら`relativenumber`が効いていても意図した通りに動きます。

``` vim
set relativenumber
nnoremap t :<C-u>call <SID>test()<CR>:<C-u>set hlsearch<CR>
function! s:test()
    let @/ = 'a'
endfunction
```

**Comment by h-east** [comment]
ソースコードを追いかけたところ、どうやら仕様みたいです。
[:help 'hlsearch'](http://vim-jp.org/vimdoc-ja/options.html#'hlsearch') からの
[:help :nohlsearch](http://vim-jp.org/vimdoc-ja/pattern.html#:nohlsearch)

```
    このコマンドはオートコマンド中は機能し
    ません。オートコマンドを実行する時に強調表示の状態を保
    存し、実行後に元に戻すからです。|autocmd-searchpat|
    ユーザー関数を呼び出したときも同様。
```

[:help autocmd-searchpat](http://vim-jp.org/vimdoc-ja/autocmd.html#autocmd-searchpat)

```
    自動コマンドの中で ":nohlsearch" を使って、検索語の強調表示を無効にすることはできない。
```

# 

'relativenumber'オプションがoffの時にユーザー関数抜けた後もhlsearchが有効になって見えるのは以下の流れだと思われます。
- `nohlsearch状態`を退避。(on ← 検索文字をhighlightしない)('hlsearch'オプションのon/offとは別)
- ユーザー関数に入る。
- `set hlsearch`で`'hlsearch'オプション`がonになり`nohlsearch状態`もoff (検索文字をhighlightする)になる。
- `redraw`で表示更新が`nohlsearch状態`がoff状態でおこなわる。(`a`がhighlightされる)
- ユーザー関数を出る。
- `nohlsearch状態`を復元。(on)
- その後、特に表示更新はおこなわれないので`a`がhighlightされたまま。

ここで `:redraw!` か `<C-L>`を実行すると元の表示に戻ります。

'relativenumber'オプションがonの時はユーザー関数抜けた後にカレントウィンドウの表示更新処理がおこなわれているので一応仕様に則った動作と言えます。
(ウィンドウ分割して試すと分かりますが、カレントウィンドウ以外は`a`がhighlightされた状態ですｗ)

**Comment by saihoooooooo** [comment]
そうでしたかー。。
該当のヘルプは目を通したことがあるので知っていましたが、`set nohlsearch`を設定する時だけの話かと思ってました。

> ここで :redraw! か <C-L>を実行すると元の表示に戻ります。

これは決定的ですね。
むしろ表示更新が行われないと状態が残ったように見えるのがある種の不具合のような。

当初やりたかったことはビジュアルモードで選択中のテキストをハイライトする関数を作りたかったのですが。
別の方法がないか模索してみます。
