### ISSUE TITLE
コマンドラインモードで <C-]> がそのまま入力される

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#419]
挿入モードとコマンドラインモードで `<C-]>` は短縮入力を展開するコマンドですが、挿入モードでは短縮入力を展開できない場合は何も起きないのに対し、コマンドラインモードでは展開できない場合に `^]` が入力されてしまいます。
これだと、とりあえず展開してみる、と言うことができません。

**Comment by ynkdir** [comment]
報告しました。
https://groups.google.com/d/msg/vim_dev/3HHa6hN-1zs/d0LEp_tbXJUJ

**Comment by ynkdir** [comment]
7.3.1235 で修正されました。

**Comment by thinca** [comment]
はや！あざす！
