### ISSUE TITLE
generic :end

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#42]
https://nicht.jottit.com/vim/hacking にのっていたネタです。

> generic :end - いちいち:endforとか:endwhileとか書き分けるのは馬鹿らしい。全部:endで済ませたい。

確かにすべて:endで済ませることができると記述を簡略化できると思います。
補完を使っているものの、:endfunctionはさすがに長いです。

実装は面倒なのかな……。

**Comment by koron** [comment]
parseの構造上たぶん無理。もしくは極端に可読性が下がる。

**Comment by Shougo** [comment]
そうなんですか……。というか、他の言語には普通にgenericなparseがありますよね。
あれはどうやっているんだろう。

**Comment by koron** [comment]
たぶん考えられる問題は2つ
1. endfuncを見つける方法が複雑化し、parseにかかる時間が増える
2. できたソースコードの可読性が下がる

後者は、他の言語が大丈夫だから問題ないという言い方はできるかもだけど、
それで納得するかは別の話というところ。

**Comment by Shougo** [comment]
> できたソースコードの可読性が下がる

これは、matchit.vimなどを併用することでも大丈夫だと思います。
あと、そもそもVim scriptで一画面に収まらないソースコードはまずいと思います。
自戒も含めて……。

**Comment by koron** [comment]
「今現在、リテラルに区別が付くものを付かないようにしましょう」という提案は受け入れられないと予測してます。
あるプラグインが助けてくれるから良い、という程度では覆らないでしょう。

単純にそうしなければならない合理的な理由に乏しいんですよね。

**Comment by Shougo** [comment]
ふむ。まぁ、それほど重要な機能でもないし、望み薄ですかね。

**Comment by tyru** [comment]
ラベルが `joke` www
