### ISSUE TITLE
7.3.1200以降でexpressionレジスタを使用するとundo履歴がおかしくなる

### ISSUE THREAD

**Issue by DeaR** [vim-jp/issues#421]
事の発端は Shougo/neocomplete.vim#16 ですが、
表題の通りで7.3.1200でexpressionレジスタを使用した際になった為
下記の様な構成・操作でundo履歴がおかしくなります
#### .vimrc

``` vim
set nocompatible
function! s:test()
  return "\<CR>"
endfunction
inoremap <script> <CR> <C-R>=<SID>test()<CR>
```
#### 操作概要(アニメGIF)

![1220_4](https://f.cloud.github.com/assets/1154870/692222/9168bcfc-dc0e-11e2-8b05-0b41f73d7493.gif)
#### 確認環境

7.3.1220+kaoriya win7x64
7.3.1203+kaoriya win7x64
7.3.1189+kaoriya win7x64
7.3.969+kaoriya win7x64
7.3.1200独自ビルド win7x64
7.3.1199独自ビルド win7x64
#### 7.3.1200関係のトピック

https://groups.google.com/d/topic/vim_dev/YHMNTfsI5-c/discussion
https://groups.google.com/d/topic/vim_dev/vkyl-D70wcM/discussion
https://groups.google.com/d/topic/vim_use/yRcEE2eO8TQ/discussion

---

完全に余談ですが[NeoComplete](https://github.com/Shougo/neocomplete.vim), [NeoComplCache](https://github.com/Shougo/neocomplcache.vim)だけではなく
[AutoComplPop](https://github.com/othree/vim-autocomplpop), [SuperTab](https://github.com/ervandew/supertab)でもこの症状の関係でundo履歴が滅茶苦茶になっちゃったりします

**Comment by h-east** [comment]
再現しました。(7.3.1203+kaoriya win7x64)
既存のファイルを読み込んだバッファでのみ発生するみたいですね。
新規バッファ(:new)では発生しない。

**Comment by Shougo** [comment]
SuperTabは外国でよく使われているプラグインなので、この問題の影響は大きいでしょう。`<C-r>=`はマッピングでもよく使われます。おそらく、そこでもUndo履歴への副作用が起こると思われます。

これは明らかにプラグインの実装と衝突する仕様なので修正するべきとは思いますが、どのような方針にするのがよいですかね。
1. 完全にrevertする
2. 条件付きでundo履歴を保存する

この機能自体には要望があった以上、できることなら単純なrevertよりも条件を厳しくした実装にしたいですが、うまい条件が思いつかず……。

**Comment by DeaR** [comment]
``` vim
set nocompatible
function! s:test()
  return "\<CR>"
endfunction
inoremap <script> . <C-R>=<SID>test()<CR>
" 例の操作概要で <CR> の代わりに . で改行させる→発生する
```

``` vim
set nocompatible
function! s:test()
  return "\<Space>"
endfunction
inoremap <script> <CR> <C-R>=<SID>test()<CR>
inoremap . <CR>
" 例の操作概要で <CR> の代わりに <CR> . と入力して改行させる→発生する
" 例の操作概要で <CR> の代わりに . で改行させる→発生しない
```

やはり`<C-R>=`が使われてた際に発生しますね
undo更新自体がおかしいのか、undo更新するタイミングがおかしいのか:disappointed_relieved:

インサートモード中はexpressionレジスタだろうとundo更新しない、なんて手も思いつきますが
それでパッチ投げても質問攻めにあって結局「根本を直そうぜ」となるだろうなぁ、と思ってたりします

---

ただ入力中にしょっちゅうundo更新は重そう、と思わなくもないですが:sweat:

**Comment by Shougo** [comment]
パッチ投げても荒れそうなので、まずはvim_devに問題を提起したほうが良いのでは？
あのパッチが取り込まれたのも、たまたま問題を解決するパッチが投稿されたからで特に副作用の検証は行われていないと思います。

**Comment by h-east** [comment]
7.3.1200ちょっと変だ。
新規バッファもしくは既存ファイル(改行１つ)の場合と、既存ファイル(改行2つ以上)で挙動が違う！なんだこれ？
vim 7.3.1223 on fedora 17

---

#### 新規バッファの場合

``` bash
$ vim -N -u NONE --noplugin
```

で以下の操作

``` vim
ia<Esc>o1<Esc>a2<C-R>=setline('.','1234')<CR><CR><Esc>
```

こうなる。

```
a
120
34
```

初回の`u`でこうなる。

```
a
12
34
```

2回目の`u`でこうなる。(この挙動がpatch 7.3.1200で修正されたもの)

```
a
1
```

---

#### 既存ファイル(改行2つ以上)の場合

``` bash
$ echo -e "\n" > foo
$ od -t x1c foo
0000000  0a  0a
         \n  \n
0000002
$ vim -N -u NONE --noplugin foo
```

で新規バッファ時と同様の操作でこうなる。

```
a
120
34

```

初回の`u`でこうなる。

```
a
12
34

```

2回目の`u`でこうなる。

```
a
1                              ●あれ？
34

```

3回目の`u`でこうなる。

```
a
34                              ●あれ？？

```

---

つまり、patch 7.3.1200は本題の`<C-R>=setline()`の修正が不完全なパッチということになります。
この問題が直れば表題の件も直る気がする。

**Comment by h-east** [comment]
Reported.
https://groups.google.com/d/msg/vim_dev/YHMNTfsI5-c/rH5i04AbmOMJ

**Comment by mattn** [comment]
++

**Comment by DeaR** [comment]
:+1:

**Comment by h-east** [comment]
昨日のpatchラッシュではスルーされちゃいました。
私の報告だけだと「7.3.1200のpatchが不完全だよ」としか言っていないので優先度低いのかも。
早く直してもらわないと困る人は「他にも影響出てるんじゃ！こんな感じでな...」のような報告をvim_devにした方が良いかも

**Comment by k-takata** [comment]
スルーされてませんよ。todo 入りしてます。

> Patch 7.3.1200 doesn't fix the problem in all cases. (Hirohito Higashi, 2013
> Jun 24)

**Comment by h-east** [comment]
@k-takata あっ、そうでしたか。ありがとうございます。

**Comment by DeaR** [comment]
7.3.1253で修正されました

**Comment by Shougo** [comment]
了解です。早くに修正されてよかったですね。

**Comment by h-east** [comment]
Patch 7.3.1253 で修正されました。
https://groups.google.com/d/msg/vim_dev/uyKlGcIUxU0/295qbhx8I7IJ

リンクを貼ろうぜよ:metal:
[Issueを閉じる手順](https://github.com/vim-jp/issues/wiki/Member#issue)

**Comment by DeaR** [comment]
> リンクを貼ろうぜよ:metal:
> [Issueを閉じる手順](https://github.com/vim-jp/issues/wiki/Member#issue)

了解、以後気を付けます
