### ISSUE TITLE
Kaoriya版で配布しているVimをhugeバージョンにして欲しい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#422]
Vim pluginのパフォーマンスボトルネックを調べるのに、`:profile`によるプロファイリング機能はとても効果的です。
Linux環境では自前でビルドするので良いのですが、Windows環境ではVimをビルドするのが大変です。もし、Kaoriyaさんが配布しているVimがhugeバージョンならばプロファイリング機能を使うのがとても楽になるのですが、hugeバージョンにする予定はないのでしょうか。

**Comment by koron** [comment]
検討します。

**Comment by Shougo** [comment]
よろしくお願いいたします。

**Comment by koron** [comment]
次のリリースから HUGE になります。

https://bitbucket.org/koron/vim-kaoriya/src/0311428f451e4e65df6331b9cfd9c7de4b2f6531/build/msvc/vim.mak?at=default#cl-4

**Comment by Shougo** [comment]
ありがとうございます。
