### ISSUE TITLE
confirm() でマルチバイト文字があるとウィンドウの幅がおかしい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#423]
恐らくマルチバイト文字の幅を考慮してません。

![](http://cache.gyazo.com/41c8b3ef97cab33f81f8ec6b4f39b814.png)

![](http://cache.gyazo.com/21d84a5ae867ba444351e1f6eb47bbdf.png)

**Comment by thinca** [comment]
環境書き忘れてました。そして最新じゃなかったので、後で最新でも確認してみます(もしくはどなたか…)。

Windows 8 64bit
7.3.969 Kaoriya

**Comment by thinca** [comment]
Linux だと大丈夫そげ。

7.3.969 Huge 版 with GTK2 GUI.

![](http://cache.gyazo.com/22017ef51b8dba3624372319f815dfb2.png)

**Comment by thinca** [comment]
あ、↑のLinux のは X server は Windows の Xming です。

**Comment by sgur** [comment]
Win7 64bit 7.3.1242 64bitビルドですが同様です。

``` viml
echo confirm('あいうえおかきくえこさしすせとたちつてと')
```

![snapshot-0](https://f.cloud.github.com/assets/255021/706625/02312000-ddf4-11e2-98d9-f610df92e0b8.png)

**Comment by mattn** [comment]
幅を計算して表示してるんですが、表示はcp932で行ってるのに幅計算がutf-8のままですね。
encoding=utf-8 で使ってる場合のみ発生しますね。

**Comment by mattn** [comment]
これで治るかと。

https://gist.github.com/5863733

``` diff
diff -r 5759342cde79 src/gui_w32.c
--- a/src/gui_w32.c Mon Jun 24 22:33:30 2013 +0200
+++ b/src/gui_w32.c Wed Jun 26 09:28:25 2013 +0900
@@ -3216,7 +3216,7 @@
        if (l == 1 && vim_iswhite(*pend)
                    && textWidth > maxDialogWidth * 3 / 4)
        last_white = pend;
-       textWidth += GetTextWidth(hdc, pend, l);
+       textWidth += GetTextWidthEnc(hdc, pend, l);
        if (textWidth >= maxDialogWidth)
        {
        /* Line will wrap. */
```

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/NaHU-JxszeM/AmnobLBb2pcJ

**Comment by mattn** [comment]
ちょっとパッチ更新。

**Comment by mattn** [comment]
Patch 7.3.1244

https://groups.google.com/d/msg/vim_dev/-cYHY3Lgb9o/s6JxHOX-54EJ

**Comment by h-east** [comment]
And Patch 7.3.1245
https://groups.google.com/d/msg/vim_dev/3HGvvOI8Hb0/DQHDvi3irQgJ

@mattn GJ! クイックル!
