### ISSUE TITLE
Vim 7.3.1260以降でコマンドラインのユーザー定義補完が動作しない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#425]
Vim 7.3.1260の変更により、ユーザー定義のコマンドライン補完が動作しなくなりました。

https://groups.google.com/forum/#!topic/vim_dev/8COzR05n3fQ

ドキュメントサンプルにもあるような、単純なサンプルですら動作しません。
デバッグメッセージを仕込んでみましたが、該当する関数が呼ばれている気配すらありません。

```
command -nargs=1 -bang -complete=customlist,EditFileComplete
      \ EditFile edit<bang> <args>
function EditFileComplete(A,L,P)
  return split(globpath(&path, a:A), "\n")
endfunction
```

みなさんの環境ではこの問題は再現するでしょうか。

再現環境： Ubuntu Linux 13.04, Vim 7.3.1270

**Comment by k-takata** [comment]
既に報告が挙がっているようです。
https://groups.google.com/d/topic/vim_dev/QX_792wgUQ8/discussion

**Comment by Shougo** [comment]
私が見た時には報告がなかったのですが、やはり報告されていたんですね。おそらくすぐに修正されると思うので、様子を見ます。

**Comment by k-takata** [comment]
7.3.1271 で直った？
https://groups.google.com/d/topic/vim_dev/_bgHWPc74_g/discussion

**Comment by h-east** [comment]
Yes! Marcinさんの再現手順にてバグが修正されていることを確認しました。

Shougo氏のは再現手順が全て提示されていないのでよくわからないけど、以下の手順で 'path' の値が候補に出て来たのでOKっしょ。

``` sh
$ cat ~/vimrc_cc
```

``` vim
command -nargs=1 -bang -complete=customlist,EditFileComplete
      \ EditFile edit<bang> <args>
function EditFileComplete(A,L,P)
  return split(globpath(&path, a:A), "\n")
endfunction
```

Vim起動

``` sh
$ vim -N -u ~/vimrc_cc
```

'path'オプションの値を確認

``` vim
:set path?
  path=.,/usr/include,,
```

ユーザ定義のコマンドライン補完発動！(なんちゃらデュエルっぽく言う)

``` vim
:EditFile ^D
```

'path'オプションの値が候補に出て来るのでOK

```
./             /usr/include/
```

**Comment by Shougo** [comment]
@h-east わかりにくくてすみません。はい。手順はそれで問題ないと思います。

> 7.3.1271 で直った？
> https://groups.google.com/d/topic/vim_dev/_bgHWPc74_g/discussion

問題が致命的だと、修正が早いですね……。
