### ISSUE TITLE
ftplugin/ocaml.vim を改善したい

### ISSUE THREAD

**Issue by cohama** [vim-jp/issues#426]
デフォルトの OCaml の ftplugin なのですが、
- nnoremap すべきところが nmap になっている
- ftplugin なのにグローバルにマッピングを定義している箇所がある
- z マークを潰しているところがある
- オプションの一貫性がない (g:no_ocaml_map を定義しても一部のマッピングしか無効にならないなど)

などです。
修正は自分でできると思いますが、本家にも取り入れてもらいたいです。

**Comment by h-east** [comment]
issue登録ありがとうございます。

一番大事なやつ忘れてます↓
「言語名は Ocalm じゃないぜ！ OCalm だぜ！」

**Comment by koron** [comment]
``` vim
" Maintainer:  David Baelde        <firstname.name@ens-lyon.org>
"              Mike Leary          <leary@nwlink.com>
"              Markus Mottl        <markus.mottl@gmail.com>
"              Pierre Vittet       <pierre-vittet@pvittet.com>
"              Stefano Zacchiroli  <zack@bononia.it>
"              Vincent Aravantinos <firstname.name@imag.fr>
" URL:         http://www.ocaml.info/vim/ftplugin/ocaml.vim
```

だれがメンテナなのかわからないけど
http://www.ocaml.info/ を見ると Markus Mottl がメインなのかなぁ。
Markus と vim-dev と Bram へ送ってみると良いと思います。

**Comment by thinca** [comment]
OCaml、ねw

**Comment by cohama** [comment]
> OCaml、ねw

はい。Ocaml でも OCalm でもなく OCaml ですね。

> Markus と vim-dev と Bram へ送ってみると良いと思います。

う、もしかしなくても英語ですよね。

**Comment by koron** [comment]
Bram はオランダ語でも大丈夫なはずです。 :joy_cat:

**Comment by h-east** [comment]
よしっ、作戦成功:wink: OCaml

**Comment by cohama** [comment]
英語とオランダ語・・・。英語がいいです。とりあえず、他の人のを真似しながら送ってみます。

**Comment by koron** [comment]
読むだけでメリットが伝わるパッチなら、

> 私はOCamlのプラグインを進歩させました。
> 添付したパッチを是非チェックしてください。

くらいを英語で書けば、なんとかなりますよ。気楽にどうぞ。

**Comment by cohama** [comment]
おお、ありがとうございます。その作戦で行きます！

**Comment by h-east** [comment]
https://twitter.com/c0hama/status/352047023849078785

> そういえば Vim で OCaml 書くときに、インサートモードで ASS と打つと面白いことが起こる

ftplugin/ocaml.vim : 66 にこんなものが！

``` vim
iabbrev <buffer> ASS (assert (0=1) (* XXX *))
```

これはちょっとキモい設定かも。
ということで、他の言語用ftpluginでも iabbrev が設定されているのか調べてみました。
設定されているのは ocaml.vim 以外だと ada.vim と zimbu.vim の2ファイルでした。

ada.vim は予約後の短縮形を登録している感じ。
`ret` --> `return`
`proc` --> `procedure`
`pack` --> `package`
`func` --> `function`

zimbu.vim は予約後を片っ端から大文字に変換するための登録がわんさか(46個)。
(一部抜粋)
iabbr <buffer> <expr> alias GCUpperSpace("alias")
iabbr <buffer> <expr> arg GCUpperDot("arg")

iabbrev にアクロバティックな設定をしているのは ocaml.vim だけっぽい。
なので作者に「このibbrevキモいからやめてくれないか？他言語ではこんなキモい設定やってないよ」とお願いすればやめてくれるかもしれません:grin:

**Comment by cohama** [comment]
ちょっと時間がかかってしまいましたが、vim_dev にメールを送りました。

**Comment by h-east** [comment]
@cohama :+1: 
こちらにpatch貼り付けてディスカッションするのもありです。

**Comment by cohama** [comment]
おっと、ちょっと先走っちゃいましたかね。

ちなみに、送ったパッチはこんなかんじです。結局 Ocaml は直してません...
https://gist.github.com/6054064

**Comment by h-east** [comment]
> おっと、ちょっと先走っちゃいましたかね。

No problem。 vim_devに送る前にこちらに修正内容を晒しておけば誰かがtypoやコーディングミスを指摘してくれるかも...くらいの感じです。

vim_devの投稿のリンク貼り付けておきます。
https://groups.google.com/d/msg/vim_dev/2FF0Vyqaw-8/FpGagJmo7ikJ

**Comment by k-takata** [comment]
7.4a.047 直前のコミットで取り込まれました。

**Comment by cohama** [comment]
おお！
みなさん、いろいろとアドバイスありがとうございました。

**Comment by crazymaster** [comment]
https://github.com/vim-jp/vim/commit/f36af01f7727f5f91aa44823eb840825de788d92#diff-4
