### ISSUE TITLE
Windowsでテスト実行時に改行コードが変更されるのを何とかしたい

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#427]
https://github.com/vim-jp/issues/issues/417#issuecomment-19547810 より

> > hg で変更として検出されてしまうので、fixff がすごい邪魔なんですよね。
> 
> ですね。超邪魔

Windowsでテスト実行時、fixff ターゲットにて改行コードが変更されて hg で差分として検出されるのを何とかしたいです。

対策案:
1. 改行コードの変更を hg に差分として検出させないようにする。  
   hg の [eol エクステンション](http://d.hatena.ne.jp/flying-foozy/20111205/1323065152)で何とかできる？
2. 簡単に改行コードを元に戻せるようにする。  
   hg revert でも戻せるが、make clean で改行コードが戻ると楽。

**Comment by koron** [comment]
私は fixff を fixff_dos と fixff_unix にわけてサンドイッチするようにしています。

https://bitbucket.org/koron/vim-kaoriya-patches/src/097a7854bd626905b832c87f380df55cbff7e3a6/test-improve_dos_framework.diff?at=default

ただ最近は1テスト実行毎に、対象を fixff_dos & fixff_unix するようにしたほうが良いかなとも思ってます。

もしくは dos では入力用に別拡張子&別ファイルを生成するように、っていうのもありかな。

**Comment by k-takata** [comment]
私の方では、とりあえず、make clean で戻るようにしてみました。
https://bitbucket.org/k_takata/vim-win32-mq/src/fa31d7f0651a0be1dd5ce017bc5b2f33d7a55578/restoreff.patch

eolエクステンションも試してみましたが、Vimのテストファイルは、LFの無いCRが混じっていたりして純粋なテキストファイルとは言えないので、どうも相性が悪いようです。

> ただ最近は1テスト実行毎に、対象を fixff_dos & fixff_unix するようにしたほうが良いかなとも思ってます。

それが良いかもしれません。一部変換してはいけないものをうまく除外できれば良いのですが。

**Comment by koron** [comment]
> 一部変換してはいけないものをうまく除外できれば良いのですが。

これを考えると

> 入力用に別拡張子&別ファイルを生成するように

っていうのが選択肢として出てくるんですよね。
こんな感じで

``` make
*.din: *.in
    # convert EOL *.in to *.din

*.dok: *.ok
    # convert EOL *.ok to *.dok

.din.dout:
    # run a testcase.
```

**Comment by k-takata** [comment]
そういえば、Make_ming.mak のことをすっかり忘れていたことに気づきました。
この前の、テストに失敗したらログに出したり *.failed にリネームする対策が入っていないですね。

**Comment by koron** [comment]
[こんなの](https://bitbucket.org/koron/vim-kaoriya-patches/src/21899b8432cbe3368afc60fe1d4898f32dcf0131/test-improve_dos_framework2.diff?at=default) 作ってみました。 

```
$ nmake -f Make_dos2.mak win32
$ nmake -f Make_dos2.mak test84.out
```

みたいにして使えます。
元ファイルの `ff` はいじらず src/testdir/tmp ディレクトリ下に
実際に vim とのやり取りに使う `ff` で保存するというポリシーです。
比較時は `ff=unix` に変換しつつ src/testdir/test_.out へコピーし src/testdir/_.ok と直接 diff します。
今は tmp 下は全部 `ff=dos` ですが、必要なら `ff=unix` にするよう
`Make_dos2.mak` の末尾に依存関係を追加する目論見です。

**Comment by koron** [comment]
あ、こうしたことでいくつかのテストが失敗するようになってます。
たぶん別の test*.in を読むようなやつかしらね。

**Comment by k-takata** [comment]
いくつか、テストの入力ファイル名に依存しているものがありますね。(test13, 86, 87)
あとは、コマンドがないなど条件が整っていない場合には、test.ok を test.out にコピーして無理矢理成功させるものが、test.ok が無いために失敗します。(test11, 77, 85???)

**Comment by koron** [comment]
@k-takata ありがとうございます。指摘箇所を修正して [こんな感じ](https://bitbucket.org/koron/vim-kaoriya-patches/src/316adb306a9688458cada43286a139132a2d684e/test-improve_dos_framework2.diff?at=default) になりました。

良さそうなら提案してみます。

**Comment by k-takata** [comment]
https://bitbucket.org/koron/vim-kaoriya-patches/src/316adb306a9688458cada43286a139132a2d684e/test-improve_dos_framework2.diff?at=default#cl-76
修正後のバージョンはまだ試していないのですが、

``` sh
        $(VIMPROG) -u dos.vim --noplugin "+set ff=dos|f $@|wq" $(*B).in
```

ここの部分は、wq ではなく、wq! の方が良いと思います。
test_.in を更新してからテストを実行すると、tmp/test_.in を更新しようとして途中で止まってしまいました。

**Comment by koron** [comment]
@k-takata [75行目](https://bitbucket.org/koron/vim-kaoriya-patches/src/316adb306a9688458cada43286a139132a2d684e/test-improve_dos_framework2.diff?at=default#cl-75) で消してます。

私も同じ目にあったのでw

**Comment by koron** [comment]
ついでに必要ないかもだけど 95行目 でも同様に消す念の入れよう。

**Comment by k-takata** [comment]
なんとｗ

**Comment by koron** [comment]
[Posted](https://groups.google.com/d/msg/vim_dev/220ha-wcmdM/GI6dKzvzVjwJ)

**Comment by k-takata** [comment]
:+1:
テストの入力ファイル名に依存している部分はどうやって解決しているのかと思ったら、MOVE コマンドで元のファイルを test_.in.bak に待避でしたか。
既に test_.in.bak が存在していたときには失敗してしまうと思いますが、それは無視でいいですかね？

**Comment by koron** [comment]
いまのところはレアケースってことで目を瞑ってます。

普通の使用でそうなる時は、本来の test*.in がなくなってますからね。
復帰のためには hg revert しなきゃいけないんです。

**Comment by k-takata** [comment]
Vim以外のエディタ（ぉぃ）で test_.in を編集すると test_.in.bak ができる場合があったりｗ
まあ、無視していいとは思いますが。

**Comment by koron** [comment]
TODO リスト入り。

**Comment by k-takata** [comment]
7.3.1314 直後のコミットで todo.txt に入りました。

> MS-Windows: Patch to make tests copy files to avoid changing the fileformat of
> the files under version control. (Taro Muraoka, 2013 Jul 5)

**Comment by k-takata** [comment]
パッチを当てる前は、出力結果の testXXX.out を削除すると、テストが再実行できたのですが、パッチを当てるとそのやり方では再実行できなくなってしまいます。

追加パッチを投げてみました。
https://groups.google.com/d/msg/vim_dev/220ha-wcmdM/T1LCYdqxt8UJ

**Comment by k-takata** [comment]
todo listed.

> On MS-Windows running tests with Mercurial has problems when the input files
> are changed. (Ken Takata, Taro Muraoka, 2014 Sep 25)

なぜか別項目として追加されました。

**Comment by k-takata** [comment]
7.4.497でコンフリクト発生
https://bitbucket.org/k_takata/vim-ktakata-mq/src/38751ed77dc57ff7f84f7e31856a76bf1d9321fa/improve_dos_test.diff

**Comment by k-takata** [comment]
7.4.498向けに再修正
https://bitbucket.org/k_takata/vim-ktakata-mq/src/85cbd767023a/improve_dos_test.diff

**Comment by k-takata** [comment]
投げました。（追加パッチの方は修正ありません）
https://groups.google.com/d/msg/vim_dev/220ha-wcmdM/dOP5TzN2xbkJ

**Comment by k-takata** [comment]
7.4.647
https://groups.google.com/d/topic/vim_dev/uFsx1KJ54EQ/discussion

以下のコメント付きですが。

> [Note: this may break the tests on MS-Windows, please send me a fix if
> you can]

**Comment by k-takata** [comment]
Bramがマージをミスってたものと思われます。修正を投げました。
https://groups.google.com/d/msg/vim_dev/uFsx1KJ54EQ/1WacdPTQZFgJ

**Comment by k-takata** [comment]
7.4.648
https://groups.google.com/d/topic/vim_dev/JOn7Tx-u59w/discussion
