### ISSUE TITLE
undo が正しく動作しない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#428]
7.3.1287 Linux 64bit

``` vim
" test.vim
put ='aaa'
put ='bbb'
put ='ccc'
```

Vim を起動して、

`:source test.vim`

```

aaa
bbb
ccc
```

`u`

```
aaa
```

`u`

```
(メッセージ)既に一番古い変更です
```

最初の undo でバッファの内容がすべて消える(Vimを開いた直後に戻る)のが期待される動作です。

**Comment by h-east** [comment]
@thinca Thanks for report.

``` sh
$ vim -N -u NONE
```

``` vim
:put ='aaa'
u
```

だけで発生しました。(Vim 7.3.1273 on fedora 64bit via PuTTY)
現象: 1行目に `aaa` と表示されてしまう。再度`u`で`Already at oldest change`.
期待動作: バッファの内容がすべて消える(Vimを開いた直後に戻る)。再度`u`で`Already at oldest change`.

#421 に関連すると思われます。
なので、7.3.1199, 7.3.1200, 7.3.1253での挙動がどうなるか確認したいところ。

**Comment by ichizok** [comment]
7.3.1270の変更でエンバグしています。

``` diff
diff --git a/src/ops.c b/src/ops.c
--- a/src/ops.c
+++ b/src/ops.c
@@ -3497,7 +3497,9 @@
 #endif
        if (dir == FORWARD)
            ++lnum;
-       if (u_save(lnum - 1, lnum) == FAIL)
+       /* In an empty buffer the empty line is going to be replaced, include
+        * it in the saved lines. */
+       if ((bufempty() ? u_save(0, 1) : u_save(lnum - 1, lnum)) == FAIL)
            goto end;
 #ifdef FEAT_FOLDING
        if (dir == FORWARD)
```

VCSのログには

```
updated for version 7.3.1270
Problem:    Using "Vp" in an empty buffer can't be undone. (Hauke Petersen)
Solution:   Save one line in an empty buffer. (Christian Brabandt)
```

とありますが、直るどころか `p`, `P` でも同じ現象になっているようです。

``` diff
diff --git a/src/ops.c b/src/ops.c
--- a/src/ops.c
+++ b/src/ops.c
@@ -3499,7 +3499,7 @@
            ++lnum;
        /* In an empty buffer the empty line is going to be replaced, include
         * it in the saved lines. */
-       if ((bufempty() ? u_save(0, 1) : u_save(lnum - 1, lnum)) == FAIL)
+       if ((bufempty() ? u_save(0, 2) : u_save(lnum - 1, lnum)) == FAIL)
            goto end;
 #ifdef FEAT_FOLDING
        if (dir == FORWARD)
```

これでどうでしょうか？

**Comment by h-east** [comment]
@ichizok ++
イケてます。testもALL DONEです。7.3.1270だったのね。
vim_dev投稿お願い出来ますか？

**Comment by ichizok** [comment]
了解です。

**Comment by h-east** [comment]
@ichizok さんはvim_dev投稿経験済みの方ですか？
もし初投稿の場合は初回のみBram氏の承認が必要で最大24時間くらい投稿が反映されない事があるのでご注意ください。(私は同じ文章を何回も投稿しちゃって後で恥ずかしい思いをしましたｗ)

**Comment by h-east** [comment]
@ichizok さんはvim_dev投稿経験済みの方ですか？
もし初投稿の場合は初回のみBram氏の承認が必要で最大24時間くらい投稿が反映されない事があるのでご注意ください。(私は同じ文章を何回も投稿しちゃって後で恥ずかしい思いをしましたｗ)

**Comment by koron** [comment]
> 同じ文章を何回も投稿しちゃって

ここでもそうなる強運の持ち主w

**Comment by h-east** [comment]
> ここでもそうなる強運の持ち主w

メールで見てたから「何のこっちゃ？」状態だったけど、ブラウザでアクセスしてやっと把握できたww

**Comment by k-takata** [comment]
見えるようになりました。
https://groups.google.com/d/topic/vim_dev/dN51Lw4-Ios/discussion

**Comment by k-takata** [comment]
7.3.1293 で取り込まれました。おめでとうございます。
https://groups.google.com/d/topic/vim_dev/cOx0-nrNfLQ/discussion

**Comment by mattn** [comment]
速い！

**Comment by h-east** [comment]
@ichizok Nice! あっさり取り込まれた！ Contribute Authorおめでとうございます。

**Comment by ichizok** [comment]
ありがとうございます。

> もし初投稿の場合は初回のみBram氏の承認が必要で最大24時間くらい投稿が反映されない事があるのでご注意ください。

初めてだったので焦りましたw

**Comment by thinca** [comment]
報告だけして放置してしまいましたが、ありがとうございました！

**Comment by koron** [comment]
テスト、作りませんかね。
