### ISSUE TITLE
msvc で失敗するテスト その2

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#429]
7.3.1302

| test | description |
| --- | --- |
| 87 | ~~difference between Python 3.2 and 3.3 (#424)~~ |
| 89 | ~~path separator ([vim-dev posted](https://groups.google.com/d/msg/vim_dev/XnTQSMKdrYs/7rIAN2zoyYcJ))~~ |
| 96 | ~~result of Test C is printed twice~~ |
| 98 | ~~only gvim stops at middle (added at 7.4a.005)~~ |

**Comment by koron** [comment]
Previous: #417

**Comment by k-takata** [comment]
Related: #424

**Comment by koron** [comment]
posted about test89: https://groups.google.com/d/msg/vim_dev/XnTQSMKdrYs/7rIAN2zoyYcJ

**Comment by koron** [comment]
changes for test89 was included.

**Comment by k-takata** [comment]
> 96    result of Test C is printed twice

Result of Test B is also printed twice on my environment.
It seems that the name of buffer causes this problem.
It doesn't occur when I change the name from `test://` to `test:##`
I don't know why it occurs and the behavior is expected or not.

**Comment by koron** [comment]
[Posted a patch](https://groups.google.com/d/msg/vim_dev/thdK_BeuYmY/OQxgOoGPsoAJ) for test87.

**Comment by koron** [comment]
あとは96だけかぁ

**Comment by koron** [comment]
test96 はどうも Test B と Test C が2回ずつ実行されているっぽい。試しにこんな Test D を追加したところ…

``` vim
STARTTEST
:let g:c96 += 1
:lopen
:b test.out
:call append(line('$'), "Test D:")
:call append(line('$'), "  " + g:c96)
:w
:wincmd o
:b 1
ENDTEST
```

こんな結果が出力されました。

```
Test D:
1
Test D:
2
```

**Comment by koron** [comment]
ちなみに `lopen` と `wincmd o` をやめると 1 回だけ実行されます。
なのでこの1セットのコマンド実行でテストのプログラムカウンタに相当する部分が1度だけ巻き戻されているもよう。

**Comment by koron** [comment]
`:b 1` で戻った後の現在行が巻き戻ってる。

例えば Test B の:lrewind の前の test96.in での行数は **112** (Test Bの直後) だが
その後テストが進み `:b 1` の直後に **87** (Test Bの直前) になってしまっている。
Test Bの2回めの実行後は `:b 1` の直後に **112** になって、正しくテストが Test C へ移行してた。

**Comment by koron** [comment]
うげぇ…何かのタイミング依存っぽい。

dotest.in のほうで `so Xdotest` する前後にスリープ `sleep 1` 挟むだけで発生しなくなる。

```
:set cp
:map dotest /^STARTTEST^V^Mj:set ff=unix cpo-=A^V^M:.,/ENDTEST/-1w! Xdotest^V^M:set ff& cpo+=A^V^M:sleep 1^V^Mnj0:so! Xdotest^V^M:sleep 1^V^Mdotest
dotest
```

**Comment by koron** [comment]
以下推測

CUIなvimのイベントループに、UNIXとWinで作り方の違いがあって
そのせいで test96 に関連する処理、特に lopen や b によるバッファ切り替え、
あたりを構成する処理の実行タイミングもしくは順序が微妙に違うっぽい。
それが test96 の失敗 = 同じテストブロックが複数回実行されるということになってる。
sleep はそのズレを修正する効果があるのだろう。

修正方法は、現時点でわからない。
Vimの構造に関わるところが関係していると考えているので
誰かやる気のある人が着手しないならば、とっとと vim_dev に報告したほうが良さげ。

**Comment by koron** [comment]
recursive な map 処理かもなぁ…

**Comment by k-takata** [comment]
バッファ名に `/` が含まれているのとは無関係ですか。難しすぎ。

**Comment by koron** [comment]
関係ないとも言い切れないのがVimの怖いところですねw
バッファ切り替えに難あり、その途中にファイル名がトリガーになってタイミング問題が発生する、とか考えられます。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/N8jzif4e9L8/fRVjWl02JQsJ
Macでも同じような現象が起きたようです。（Test Bが重複）

**Comment by k-takata** [comment]
最近(7.4a.005)追加された test98 が途中で入力待ちになって止まってしまいます。(7.4a.009で確認)

**Comment by koron** [comment]
> 最近(7.4a.005)追加された test98 が途中で入力待ちになって止まってしまいます。(7.4a.009で確認)

これ 017 では発生してないけど、直ったのかな?

**Comment by koron** [comment]
test96 の失敗は xubuntu でも確認した。何かわかりやすいトリガーがあるっぽい。

**Comment by k-takata** [comment]
> これ 017 では発生してないけど、直ったのかな?

018 で発生しています ＞＜

**Comment by koron** [comment]
@k-takata 

> 018 で発生しています ＞＜

こっちでは発生しない。

**Comment by k-takata** [comment]
> こっちでは発生しない。

自分の場合は2つの環境で試して2つとも発生しています。
test98a.in の中身を1行ずつ手で実行すると発生しなかったので、これもタイミング的な問題の可能性も。

**Comment by ynkdir** [comment]
端末の大きさとか関係ありますか。
うちは ubuntu ですけど端末のウインドウが小さいと途中で `-- 継続 --` が出たりして 37 47 92 93 が失敗します。

**Comment by k-takata** [comment]
> 端末の大きさとか関係ありますか。

分かりませんが、vimだと成功して、gvim だと失敗することが分かりました。
`nmake -f Make_dos.mak VIMPROG=..\gvim test98.out` で実行しています。

> 37 47 92 93 が失敗します。

`:set nomore` すべきなんですかね？

**Comment by h-east** [comment]
> 端末のウインドウが小さいと途中で `-- 継続 --` が出たりして 37 47 92 93 が失敗します。

半年前の情報ですが一応リンク貼っておきます。
https://gist.github.com/h-east/4360424#comment-688226

**Comment by koron** [comment]
> 端末のウインドウが小さいと

どのくらいのサイズですか? 私の手元、80x24 ならとりあえず問題はでてないです。

**Comment by koron** [comment]
まとめてみた < https://gist.github.com/h-east/4360424#comment-688226

| Size\test | 13 | 31 | 37 | 47 | 62 | 84 | 88 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 80x24 | OK | OK | OK | OK | OK | OK | OK |
| 80x20 | OK | OK | OK | OK | OK | OK | OK |
| 80x15 | OK | OK | NG | NG | OK | OK | OK |
| 80x10 | OK | OK | NG | NG | OK | OK | OK |
| 80x5 | NG | NG | NG | NG | NG | NG | NG |

**Comment by koron** [comment]
> vimだと成功して、gvim だと失敗する

こっちでも確認しました。

**Comment by koron** [comment]
test96 は逆に gvim だと成功するなwww

**Comment by ynkdir** [comment]
ubuntu でも確認。
最小。

```
$ cat a.vim
:call feedkeys("\n", 't')
:echo '<- echo がノーマルコマンドとして解釈されて挿入モードに入りこのテキストが挿入される'
$ gvim -u NONE -N -s a.vim
```

feedkeys("\n") とか feedkeys("<Esc>") とかで次の行の `:` が飛んじゃう感じ

**Comment by ynkdir** [comment]
あーちがう
次の行の `:` の直後に feedkeys() のキーが挿入されるような動作

```
:call feedkeys('echo', 't')
:'hello, world'
```

で hello, world が出力される。

**Comment by ynkdir** [comment]
getcmdline() -> setmouse() -> update_mouseshape() -> char_avail() という流れ。
GUI だと getcmdline() の最後でカーソル表示の更新で char_avail() が呼ばれるので feedkeys() の実行前に次の `:` が読み込まれてタイプアヘッドバッファに入る。という感じだと思います。
これは直せないんじゃないですかね。
なんでfeedkeys()使ってるのか。

**Comment by k-takata** [comment]
確かに Ubuntu でも gvim だと途中で止まりますね。

> なんでfeedkeys()使ってるのか。

scrollbindのテストなので↓でいいと思うんですが何なんでしょう？

``` VimL
setl scb
wincmd w
```

**Comment by k-takata** [comment]
test98 で feedkeys() を使わないようにするパッチを投げました。
https://groups.google.com/d/topic/vim_dev/uT0Y-flppwo/discussion

feedkeys() の動作については理解していないので、適宜補足をお願いします。

**Comment by k-takata** [comment]
7.4a.021 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/hgaW_JmWuYg/discussion

**Comment by ynkdir** [comment]
GJ!

**Comment by k-takata** [comment]
feedkeys() じゃないとダメらしい。（が、理解できていません。）
https://groups.google.com/d/topic/vim_dev/PoyfCcO-HG0/discussion

**Comment by ynkdir** [comment]
```
:setl scb
:wincmd w
```

を test98.in の :source の直後にもってくればいいんじゃないですかね。
`:source` をまたぐかどうかがトリガー？

**Comment by koron** [comment]
いま手元のWindowsで `nmake -f Make_dos.mak win32` したら `ALL DONE` になった。

もしや全部直ったの? この issue 閉じちゃってええの?

**Comment by koron** [comment]
あ、もう1回ためしたら test96 が失敗した。なんだよCUI版でもタイミングで成功したりするのか…

**Comment by koron** [comment]
GUI版で実行した時の test96.out が残ってた可能性は否定できない。

**Comment by k-takata** [comment]
自分のところでは 96 は相変わらず失敗します。(gvim)

**Comment by ynkdir** [comment]
``` diff
diff -r 3f65dc9c8840 src/window.c
--- a/src/window.c  Sun Jul 21 18:59:24 2013 +0200
+++ b/src/window.c  Mon Jul 22 23:49:51 2013 +0900
@@ -4609,7 +4609,7 @@
     if (wp != aucmd_win)
 #endif
    win_remove(wp, tp);
-    vim_free(wp);
+    //vim_free(wp);

 #ifdef FEAT_AUTOCMD
     unblock_autocmds();
```

test96 はこれで成功になりますか。

テストが失敗するのは buflist_getfpos() が返す位置がおかしいから。
win_free() しても buf->b_wininfo にはアドレスが残っている。
後で win_alloc() したときに同じアドレスが使われる。
buf->b_wininfo を検索するときに curwin と比較しているが、上記の理由で同じアドレスであっても別のウインドウということがある。
そのため、メモリアロケーションの動作状況によって結果が変わる。
Macでも失敗報告あるし、おそらくLinuxでも環境によっては失敗するのではないか。
という予想。

**Comment by koron** [comment]
@ynkdir :+1: すげぇ…乙であります (｀･ω･´)ゞ

でもこれ…`vim_free()` しなくてリークしないんですか?

**Comment by ynkdir** [comment]
これはただの確認用ですので

修正は全探索して開放とかになるんですかねぇ

**Comment by ynkdir** [comment]
よくわからないので丸投げました。

**Comment by k-takata** [comment]
7.4a.044
https://groups.google.com/d/topic/vim_dev/kYUyk6ftK3Y/discussion
test96が直ったようです。close?

端末サイズが小さいと失敗するテストについては、別issue立てた方がいい？（直す直さないは別として）

**Comment by koron** [comment]
Great!

**Comment by koron** [comment]
>  端末サイズが小さいと失敗するテストについては、別issue立てた方がいい？（直す直さないは別として）

Agreed
