### ISSUE TITLE
補完候補の絞り込み時、第一候補の選択状態が継続されない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#430]
パッチバージョンがいつの頃からかはわかりませんが、補完候補の絞り込みを行った時に、第一候補の選択状態が継続されません。

環境：
Vim 7.3.1302
追加パッチなし

再現方法：

```
1. `vim -u NONE -U NONE --noplugin -i NONE`
2. `:set completeopt=menuone`を実行する。
3. バッファに"kdurant"と入力
4. インサートモードで `kd<C-n><C-p><Down>`を入力
5. "u"を入力して絞り込み
6. 第一候補"kdurant"の絞り込みが解除される
7. インサートモードで`kd<C-p><C-n><Down>`を入力
8. "u"を入力して絞り込み
9. 第一候補"kdurant"の絞り込みが解除されない
```

`<C-p>`だとなぜか候補の選択状態が継続されており、動作の一致という観点からも今の状態は好ましくないと考えています。

**Comment by k-takata** [comment]
Issue with popup menu: first item becomes unselected
https://groups.google.com/d/topic/vim_dev/2-EC7vM8-vo/discussion

同一の問題じゃないでしょうか？ （再現しないと言っている人もいますが。）
まずはどのバージョンからの問題かをはっきりさせるのが解決の近道だと思います。

**Comment by Shougo** [comment]
同一の問題だと思います。

> まずはどのバージョンからの問題かをはっきりさせるのが解決の近道だと思います。

これが結構辛いですね。とはいえ、Vim 7.3.800〜Vim 7.3.1300くらいの変更が怪しいのは確かです。

**Comment by Shougo** [comment]
http://code.google.com/p/vim/source/detail?r=350239b0e9eb063d9f84dfa4bc7a2b47d78e9afb#

怪しい変更を発見しました。おそらく、これが原因だと思います。

```
updated for version 7.3.1269
Problem:    Insert completion keeps entry selected even though the list has
            changed. (Olivier Teuliere)
Solution:   Reset compl_shown_match and compl_curr_match. (Christian Brabandt)
```

**Comment by Shougo** [comment]
Vim 7.3.1268で再現せず、Vim 7.3.1269で再現すればビンゴのはずですが、どうやって試すのが良いでしょうか。

**Comment by k-takata** [comment]
両方のバージョンをビルドして試すしかないのでは？
特定のバージョンを取り出す方法が分からないという話であれば、`hg up -r v7-3-1268` のように実行してみてください。
# そういえば、vim-jpのビルド方法のページには、特定のバージョンを取り出す方法が書かれてないですね。

**Comment by Shougo** [comment]
> 特定のバージョンを取り出す方法が分からないという話であれば、hg up -r v7-3-1268 のように実行してみてください。

ふむ。では、試してみます。

**Comment by h-east** [comment]
@Shougo この流れでthanks的な言葉もなしに「ふむ。」って言われたら私はムカつきますね。
「ふむふむ」って2回言われたら家中のコップを投げ割って「ふむ ってなんやねーーん！ボケがぁ！」と叫びますよ。
「ありがとう」をなるべく言わないで生きるゲームでもしてんの？

**Comment by Shougo** [comment]
はい。確かにお礼を言うのを忘れていました。

@k-takata ありがとうございます。

> 「ありがとう」をなるべく言わないで生きるゲームでもしてんの？

そういうわけではないのですが、もはや口癖みたいになっていて、なかなか治らないのです。

**Comment by Shougo** [comment]
@k-takata 試して見ました。Vim 7.3.1268では再現せず、Vim 7.3.1269では再現します。よって、Vim 7.3.1269のパッチでのエンバグだと考えられます。vim_devの上記スレッドに報告しようと思います。情報有り難うございました。

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/2-EC7vM8-vo/SUC0683KmmoJ

報告完了しました。そもそも、このエンバグした Vim 7.3.1269の変更はどういう意図で追加されたのでしょうね。調べてみます。

**Comment by h-east** [comment]
@Shougo :+1: Niceです。

**Comment by Shougo** [comment]
ちなみに、今回エンバグしたパッチ番号を調べるのに、vim-jpのVim Magazineが役に立ちました。@ynkdirさんありがとうございます。

**Comment by Shougo** [comment]
該当スレッドを調べました。2/26と、かなり昔の投稿です。

https://groups.google.com/d/msg/vim_dev/AcTTNQzfB2o/P5mLewGpyk4J

パッチが入ったのが6/29。

このスレッドの内容を解読していこうかと思います。

**Comment by k-takata** [comment]
私の調査結果:
https://groups.google.com/d/msg/vim_dev/2-EC7vM8-vo/plYF5bHuZLsJ

**Comment by Shougo** [comment]
どうやら、あのパッチの目的は「`<BS>`を押してリストが再構築された時に選択状態が解除されない」ことを修正するのが問題だったようです。確かに、私もそれを防ぐため自前でマッピングしていたことを思い出します。
しかし、それがエンバグして「絞り込みをした時も選択状態が解除される」ことになってしまっています。
本来の目的である、「`<BS>`を押してリストが再構築されると選択状態が解除される」ことは手元で確認できています。

**Comment by Shougo** [comment]
@k-takata 調査ありがとうございます。

```
In this thread, Christian Brabandt sent two patches, and the first patch
has this problem. The second patch didn't have such problem and it was merged
as the patch 7.3.854. But four months later, the first patch was merged as
the patch 7.3.1269! I think 7.3.1269 should be reverted.
What do you think, Christian? 
```

つまり、パッチが間違って取り込まれてしまったのが問題だったようですね。Bram氏が間違えたのかな……。

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/2-EC7vM8-vo/2nfnnqyveVQJ

@k-takata さんのレポートの通り、Vim 7.3.1269はrevertして問題ないようです。

**Comment by k-takata** [comment]
7.4.018
https://groups.google.com/d/topic/vim_dev/z7t9rxSHnkk/discussion

**Comment by Shougo** [comment]
情報ありがとうございます。

（Bram氏は該当スレッドを確認していたんですね。一切コメントはしていないようでしたが……）

こちらでも直ったかどうかの確認はしておきます。

**Comment by Shougo** [comment]
Vim 7.4.18でこの問題が解決したことを確認しました。調査に協力してくれた皆さん、ありがとうございます。

**Comment by k-takata** [comment]
今回のポイントはやはりこれですかね↓

> まずはどのバージョンからの問題かをはっきりさせるのが解決の近道だと思います。

2ヶ月放置されていた問題が数時間で原因が判明し、2日経たずに直りました。

**Comment by Shougo** [comment]
そうですね……。エンバグした変更に関しては、該当コミットさえ発見できれば後は簡単に修正できますからね。
