### ISSUE TITLE
file-searching の ; が動かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#432]
`:help file-searching` の上向き検索 `;` が動いていないように見えます。

``` vim
:w foo.txt  " 適当にファイルを作る
:echo findfile('foo.txt', getcwd() . '/foo/bar;')
```

7.3.969 だと `foo.txt` と表示されます。7.3.1302 だと何も表示されません。

**Comment by ichizok** [comment]
7.3.1297 の変更が原因ですが、`getcwd() . '/foo/bar'` のディレクトリが存在する場合は `foo.txt` 表示されますね。

`:echo findfile('foo.txt', 'foo/bar;')` は 7.3.969 でも結果が空になりますが、これは仕様通りなんでしょうか？

**Comment by h-east** [comment]
ichizok さんの指摘通り 7.3.1297が変化点。
7.3.1296, 7.3.1297 とも存在するディレクトリ+上向き検索`;`を指定した場合の挙動は同じ。
存在しないディレクトリ+上向き検索`;` の場合、
7.3.1296 以前はディレクトリ存在チェックをおこなわず上向き検索をおこなっていく。
7.3.1297以降 はディレクトリ存在チェックをおこなうのでそこで終了。って感じですね。

linux上で確認。

``` bash
$ cd ~/vim/src
$ ls -F window.c
window.c
$ ls -Fd testdir
testdir/
$ ls -Fd aaa
ls: aaa にアクセスできません: そのようなファイルやディレクトリはありません
```

7.3.1302の場合

``` bash
$ vim -N -u NONE
```

``` vim
:echo findfile('window.c', getcwd().'/testdir;')
window.c
:echo findfile('window.c', getcwd().'/aaa;')
                                ←●aaaディレクトリ無いので上向き検索を止めた。
```

7.3.969の場合

``` bash
$ vim -N -u NONE
```

``` vim
:echo findfile('window.c', getcwd().'/testdir;')
window.c
:echo findfile('window.c', getcwd().'/aaa;')
window.c                        ←●aaaディレクトリ無いけど上向き検索を続けた。
```

**Comment by thinca** [comment]
なるほど。まずはこれが仕様変更かどうかが気になるところですね。まあ動作が変わって動かなくなるプラグインが少なからず出てくることを考えると仕様変更であって欲しくないですが…。
私は`finddir('.git', expand('%:p') . ';')` のように使っていたので、`{path}` がファイル名になっていたのでうまく動かなかったようです。ファイルの場合は存在していてもうまく動かないようですね。
`expand('%:p:h')` のようにすれば一応回避は可能です。

**Comment by h-east** [comment]
7.3.1297で`findfile()`でワイルドカード(*)がちゃんと動くようにした絡みでディレクトリ存在チェックが入った感じなので私は仕様変更と捉えています。いままでがチェックが甘くてたまたま使えていたという認識です。

「色んなpluginで影響が出ているから前の仕様に戻してくれないとヤバいよー」という事であれば直接vim_devへ投稿してBram氏を説得してみて下さい。応援はしませんが:grin:

**Comment by Shougo** [comment]
hrsh7thさんの作成したvim-versionsというプラグインや、私がforkした版のvcs.vimの場合はこの仕様でも動作しているようです。プラグイン側で多少の実装を変更すれば動作する訳で、別にこの問題は修正される必要はないかと思います。

thincaさんのプラグインのみで問題が起こっているという現状では、修正を強要するのは難しいと思いますね。

**Comment by thinca** [comment]
私は別に直して欲しいと言っているわけではなくて、意図した変更なのかどうかを確認したかっただけです。Bramさんに直接聞かないと結論は出なさそうですね。(しかし面倒くさい…)
回避方法もあるわけなので、仕様なら仕様でいいと思ってます。

**Comment by Shougo** [comment]
> 私は別に直して欲しいと言っているわけではなくて、意図した変更なのかどうかを確認したかっただけです。Bramさんに直接聞かないと結論は出なさそうですね。(しかし面倒くさい…)

そういうことなら、thincaさんがvim_devで報告してみるしかないかと思いますね。

**Comment by ynkdir** [comment]
報告しました。
https://groups.google.com/d/msg/vim_dev/-vA__ACLeVs/vqhlrNXHpy0J

**Comment by Shougo** [comment]
@ynkdir++;

**Comment by thinca** [comment]
@ynkdir++
報告しようか面倒なので閉じようか迷ってたところです :sweat_smile:

**Comment by h-east** [comment]
todo.txtをfindfileで検索してみた。
関係ないかもしれんけど一応貼っときます。

> Bug: findfile("any", "http://;") returns http://any. (Andrew Pimlott, 2013 May
> 7)  Not sure if that can be fixed, but when using "file://" it should be
> possible to check if the file exists.

## 

> Problem with stop directory in findfile(). (Adam Simpkins, 2009 Aug 26)

**Comment by ynkdir** [comment]
たぶん今のままでokぽい感じみたいです

**Comment by thinca** [comment]
特に返事がないってことはそういうことなんですかね。Bramさん割と華麗にスルーするから判断つかないこと結構あるような…(´・ω・`)

**Comment by thinca** [comment]
仕様ってことで閉じます。

**Comment by ynkdir** [comment]
https://groups.google.com/d/msg/vim_dev/Gv0_nyNOVcM/8Y83Ue58BAAJ
Patch 7.4.885 
Problem:    When doing an upwards search without wildcards the search fails if 
            the initial directory doesn't exist. 
Solution:   Fix the non-wildcard case. (Stefan Kempf) 
Files:      src/misc2.c
