### ISSUE TITLE
set number を設定した場合に column 位置がずれる

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/issues#433]
GVim で .gvimrc に set number を設定している場合、columns 数値と実際のウインドウサイズが異なります。

``` viml
set columns=100
set lines=50
set number
set laststatus=2
```

.vimrc は何も設定してません。

![gvim](https://f.cloud.github.com/assets/56591/750140/8279a8e6-e4bf-11e2-84c1-5fd848fcba8e.png)

set number の分だけずれていると思いますが、これは仕様なんでしょうか?
添付の画像は ウインドウの幅が 100 だけど、実際の column 位置が 2 行目に来ています。
set nonumber だと columns の値とウインドウの幅の値が一致します。
(column 100 の位置が 1 行目の右端になる)

set number で右にずれてるから仕様な気がしないでもないですが、help に関連する記述を特に見つけられませんでした。

環境
Ubunts 12.10
GVim: 7.3.545(Aptitude でインストールした GVim)

**Comment by h-east** [comment]
うーん、仕様だと思います。同じくhelpに記述を見つけられなかったけどｗ

あくまでも `columns`や`lines`は画面上の列幅、行数を設定するものであって、入力されたテキストを表示する部分の列幅、行数を指定しているわけではないと思います。
`lines`が説明しやすいので`lines`で説明します。

GVimを以下のオプションで起動します。

``` bash
gvim -N -u NONE -U NONE -c "set lines=7 ls=2 ch=2"
```

windowの高さが4行、ステータス行の高さが1行、コマンド行の高さが2行で画面上の行数が7行になっています。
つまり、全体の行数が7行。そこからステータス行が1行、コマンド行が2行使用するので 7-1-2=4 で残りがwindowの高さになります。
ですので`columns`も同様に全体の列幅を指定しているだけと考えると辻褄が合います。
どうでしょうか？

誰かhelpから記述見つけて来てー

**Comment by koron** [comment]
仕様でしょうね。

> 実際のウインドウサイズ

まずは用語の定義をしっかりしたほうがよいかも。

そもそも **Vimのウィンドウ (:help window)** のサイズと
`columns` & `lines` に直接的な関係はありません。
columns は **アプリのウィンドウ** のサイズを決定し、
そこからVimにとって必要なパーツを確保した残りが
**Vimのウィンドウ** のサイズを決定します。
そういう間接的な関係になっています。

`number` 以外にその **必要なパーツ** に類するものとして
- ウィンドウを仕切る線
- コマンドライン行
- `foldcolumn`

とかとか。

書いてあるかわかりませんが、ドキュメントから仕様を読み解く時には
このあたりを考慮しないと読み取りきれないと思います。

あとこのこと、ここに書いとくと良いかも、とかそういう提案があれば是非。

**Comment by Shougo** [comment]
はい。columns, linesはおそらく物理的な幅を表し、端末だと最大の幅や高さが決まっていることから来ているのだと思いますね。ウインドウの大きさとcolumns, linesを混同するとVimの設定によって挙動が変化する厄介な問題になるので、ちゃんと計算する必要があります。

> 書いてあるかわかりませんが、ドキュメントから仕様を読み解く時には
> このあたりを考慮しないと読み取りきれないと思います。
> あとこのこと、ここに書いとくと良いかも、とかそういう提案があれば是非。

このあたりはバッドノウハウになっている気がするので、「ウインドウ幅や高さを計算するにはcolumns, linesを使用してはいけない」とcolumns, linesオプションのドキュメントにでも書いておくと良いかもしれません。

ほとんどの場合はwinwidth(), winheight()を使うほうが無難です。

**Comment by Shougo** [comment]
> set number で右にずれてるから仕様な気がしないでもないですが、help に関連する記述を特に見つけられませんでした。

これですが、set numberやset relativenumberがあると、ウインドウの表示エリアはnumberwidthの値もしくは最高の桁幅までずれます。これは仕様です。

桁幅を計算するために、`max(len(line('$'), &l:numberwidth)`という式がよく使われます。

**Comment by heavenshell** [comment]
> columns は アプリのウィンドウ のサイズを決定し、
> そこからVimにとって必要なパーツを確保した残りが
> Vimのウィンドウ のサイズを決定します。

あーなるほど。
`:h columns` で

```
VimがGUI内やサイズ変更可能なウィンドウ内で実行されているときは、
このオプションを変更するとウィンドウサイズも変更される。
```

とあったので、columns の値を変更すると **Vimのウィンドウ** サイズを変更するのかと思ってました。

> あとこのこと、ここに書いとくと良いかも、とかそういう提案があれば是非。

:h columns の所ですかねぇ。
注記としてあったら親切かもしれませんね。

**Comment by heavenshell** [comment]
仕様という事なので閉じます。

**Comment by koron** [comment]
> Number of columns of the screen.

一文目にこう書いてあるなぁ。

**Comment by heavenshell** [comment]
あー。
完全に見落としてました。
となると特に追記も要らないですかね。
