### ISSUE TITLE
簡易モードがCUIのVimで動かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#435]
Gentoo Linux 64bit 環境
Vim 7.3.1308 Huge 版 with GTK2 GUI.

```
$ DISPLAY= vim -u NONE -i NONE -N -y
E233: ディスプレイを開けません

$
```

`:help easy` によると、

> The GUI is started when available.

とのことなので、利用可能でなければ CUI で起動するのが期待する動作だと思います。

**Comment by mattn** [comment]
easyモードはクリップボード必須だからかな？仕様はわからんけど

On 7/6/13, thinca notifications@github.com wrote:

> Gentoo Linux 64bit 環境
> Vim 7.3.1308 Huge 版 with GTK2 GUI.
> 
> ```
> $ DISPLAY= vim -u NONE -i NONE -N -y
> E233: ディスプレイを開けません
> 
> $
> ```
> 
> `:help easy` によると、
> 
> > The GUI is started when available.
> 
> とのことなので、利用可能でなければ CUI で起動するのが期待する動作だと思います。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/435

## 
- Yasuhiro Matsumoto

**Comment by ynkdir** [comment]
ちょっと違う話ですがBramの見解

[patch] -G prevents starting the gui
https://groups.google.com/d/msg/vim_dev/d0vDLrT7pnI/rjVtDdfaMakJ

**Comment by k-takata** [comment]
> I'm not sure how useful this is.  Easy mode really only works in the
> GUI, because it requires the menus to be there.  Otherwise you can't
> save a file or quit.

メニューなしだと保存も終了もできないのでGUIが必要というのがBramの見解ですし、それでも端末上で起動したければ `-v` を指定すれば良いので、仕様ということで閉じましょう。

> The GUI is started when available.

この表現は改善の余地ありとは思いますが…。
