### ISSUE TITLE
:ver に +acl と +xpm を新設したい

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#436]
Unix 系の場合、ACL と XPM 機能については、ビルド時にライブラリがインストールされていれば自動的に有効化されます。逆に、ライブラリがインストールされていなければ、特にエラーも出ず、黙って無効化されます。

ACL と XPM が有効化されているかどうかは、:ver でリンカオプションを表示したときに、-lacl や -lxpm が指定されているかどうかで分かる場合もありますが、非常に分かりにくいです。
:ver で表示される features リストに +acl と +xpm を新設したいです。

パッチ:
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/a856af09bf834ab94cb82c3c639615036daef438/version_acl_xpm.patch?at=default

ドキュメントの修正が重要だと思われますが、手付かずです。
（あとは、+xpm_w32 を +xpm とまとめてしまえないかとか…）

**Comment by koron** [comment]
:+1:

**Comment by k-takata** [comment]
ドキュメントをちょっと修正。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/393c559671cb8fb6bf0c2ce7b5225803f020bff4/version_acl_xpm.patch
Windowsでは、has('xpm_w32') が 1 になるなら has('xpm') も 1 になるように修正。

**Comment by k-takata** [comment]
has('xpm_w32') は、後方互換用に変更。
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/8c4e8b4832709ee16e2d1ca2acb2e81a55b3c39b/version_acl_xpm.patch
+xpm_w32 も +xpm に変更しようかとも思いましたが、ドキュメントの修正が面倒になるのでやめましたｗ

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/FCSA_60mLPI/discussion

**Comment by k-takata** [comment]
> Looks easy enough to include now and it's kind of a bug. 

7.4 までに入りそう。

**Comment by k-takata** [comment]
> ACL と XPM が有効化されているかどうかは、(snip) 非常に分かりにくいです。

実はこれのせいで、 [vim-jp » Linuxでのビルド方法](http://vim-jp.org/docs/build_linux.html) に書いた、パッケージを個別にインストールする方法でビルドしても ACL と XPM が有効になりません。（apt-get build-dep だと問題ないのですが。）

**Comment by k-takata** [comment]
todo.txt に入りました。

> Patch to add "acl" and "xpm" as a feature. (Ken Takata, 2013 Jul 8)

**Comment by k-takata** [comment]
7.4.011 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/L9yxm1LcNVM/discussion
ただし、ドキュメントの修正はまだ取り込まれていません。
