### ISSUE TITLE
Vim 7.3.1314 で sunday.vimが正しく動作しない

### ISSUE THREAD

**Issue by robotan** [vim-jp/issues#438]
Windows でKaoriYa版Vimを愛用しております。
7.3.1314版が出ていたのでそれを使ったところ、
sunday.vimプラグイン([github.com/nishigori/vim-sunday](https://github.com/nishigori/vim-sunday) ) が正しく動作しなくなりましたので、報告させて頂きます。(KaoriYa版 windows(64bit) Vim7.3.1314)

sunday.vimは、_vimrcに、

```
let g:sunday_pairs = [
  \ ['月','火','水','木','金','土','日'],
  \ ['↑','→','↓','←'],
  \ ['abcd','efgh','ijk','lmn','op','qr','stuvw','xyz'],
  \ ['ＡＡＡ','ＢＢＢ'],
  \]
```

のように書けば `<C-a>`,`<C-x>`でトグルできて便利に利用させていただいております。
1314版では、ファイルの
月
のところにカーソルを置いて `<C-a>`すると
mon
になり、`<C-x>`だと
sun
という表示になってしまいます。
(sunday.vimファイルの let s:default_pairs の初期値の文字列になる?)

月でなく他の日本語の文字列でも同じ現象になります。
ただし、半角英数字の文字列は正しく動作しています。

969版では日本語文字列でも正しく動作することは確認しました。

スクリプトとか中身はわかりませんが、報告させて頂きました。
以上です。

**Comment by mattn** [comment]
同じくwindowsで再現しました。
正規表現内のマルチバイト文字関連っぽいですね。

**Comment by DeaR** [comment]
``` vim
" 7.3.969+kaoriya Win7(x64) enc=utf-8
:echo matchstr('月火水木金土日', '\i')
=>
:echo matchstr('月火水木金土日', '\i\+')
=> 月火水木金土日

" 7.3.1314+kaoriya Win7(x64) enc=utf-8
:echo matchstr('月火水木金土日', '\i')
=>
:echo matchstr('月火水木金土日', '\i\+')
=>
```

`\i`っぽいですね

余談だが`\k`や`\f`だとmatchし、`\i`や`\p`はmatchしない
但し969だと`\i\+`はmatchする(`\p\+`はmatchしない)

**Comment by mattn** [comment]
まず vim-sunday のソースを見てみましたが、どうやらこれマルチバイト文字にちゃんと対応していない様です。
例えば private/Private を実現する為に、2文字目以降を2バイト目以降という感じに処理してしまっています。

で、なぜ動作が変わったかといいますと、この vim-sunday がちゃんとマルチバイト文字に対応していない事で「月」(e6 9c 88)という文字が先頭1バイト削られ(9c 88)というバイト列になります。vimの旧エンジンではこの 0x9c 0x88 をオリジナルのマルチバイト文字の一部とマッチしませんでしたが、新エンジンの一部に問題があるのか「月」の一部にマッチしてしまっています。あと `\i` にもマッチしてません。
この vim の正規表現エンジンの動作に依存なくお使いになられたいのであれば、vim-sunday に以下のパッチをあてて下さい。
新正規表現の問題に関してはこちらで調査します。

``` diff
diff --git a/plugin/sunday.vim b/plugin/sunday.vim
index 0ee610d..009a592 100644
--- a/plugin/sunday.vim
+++ b/plugin/sunday.vim
@@ -65,11 +65,11 @@ function! sunday#addPairs(lists)  "{{{
 endfunction "}}}
 function! s:AddPair(word1, word2) "{{{
   let w10 = tolower(a:word1)
-  let w11 = toupper(matchstr(w10, '.')) . matchstr(w10, '.*', 1)
+  let w11 = toupper(matchstr(w10, '.')) . matchstr(w10, '^.\zs.*')
   let w12 = toupper(w10)

   let w20 = tolower(a:word2)
-  let w21 = toupper(matchstr(w20, '.')) . matchstr(w20, '.*', 1)
+  let w21 = toupper(matchstr(w20, '.')) . matchstr(w20, '^.\zs.*')
   let w22 = toupper(w20)

   let s:words = s:words . w10 . ':' . w20 . ','
@@ -91,9 +91,9 @@ function! s:IncDec(inc_or_dec) "{{{
     while i < N
       let w = expand('<cword>')
       if s:words =~# '\<' . w . ':'
-        let n = match(s:words, '\<' . w . ':\i\+\C')
+        let n = match(s:words, '\<' . w . ':[^,]\+\C')
         let n = match(s:words, ':', n)
-        let a = matchstr(s:words, '\i\+', n)
+        let a = matchstr(s:words, '[^,]\+', n+1)
         execute "normal ciw" . a
       else
         nunmap <c-a>
```

**Comment by mattn** [comment]
そもそも昔ので `\i` がマルチバイトにマッチしてたのがおかしい気がしますねw

**Comment by DeaR** [comment]
> そもそも昔ので \i がマルチバイトにマッチしてたのがおかしい気がしますねw

同意。`\i`だとmatchせず`\i\+`だとmatchする謎挙動

しかし、別件になっちゃいますが969でも1314でも`\p`がmatchしないのが気になりました
`:help 'isprint'`

> 文字コードが 256 以上のマルチバイト文字は常に含まれることになっている
> ので、文字コードが 255 以下の文字のみをこのオプションに指定する。

**Comment by mattn** [comment]
@DeaR

そっちはコード見ますね。

@robotan 

vim-sunday の方に後で↑のパッチ送っておきます。

**Comment by k-takata** [comment]
> 同意。`\i`だとmatchせず`\i\+`だとmatchする謎挙動

旧エンジンのこの挙動は 7.3.981 で修正されていますね。

**Comment by mattn** [comment]
@k-takata さんは `\i` はマルチバイトにマッチすべきだと思いますか？

↑でそうは言ってみたものの、実は `\i` がマルチバイトにマッチしないと `\<\i\+\>` でマルチバイトを含んだトークンを拾えなくなるので、やはりマッチすべきかなーと思いはじめてます。

**Comment by mattn** [comment]
あー、旧エンジンでもマッチしない様になった！？

**Comment by k-takata** [comment]
> `\i` はマルチバイトにマッチすべきだと思いますか？

切り替えられた方が便利だと思ったのですが、`'isident'` には 255 までの値しか指定できないんですね。

**Comment by mattn** [comment]
`expand('<cword>')` のもう少し賢い版が欲しいですね。カーソル付近じゃなくて、ちゃんとカーソル位置が含まれる動作の。

**Comment by nishigori** [comment]
issue & PR ありがとうございます :)

自分がマルチバイトで使ってない + 確認してませんでしたorz

**Comment by mattn** [comment]
@robotan `\p` の件は別にした方が良いと思うので、いったん閉じます。

**Comment by k-takata** [comment]
> いったん閉じます。

閉じられていないので閉じます。

**Comment by robotan** [comment]
早速の対応していただき、みなさん、ありがとうございました。

**Comment by tyru** [comment]
なるほどsundayじゃねーの

**Comment by h-east** [comment]
![kuma](https://f.cloud.github.com/assets/518808/793414/357b059e-ec03-11e2-8266-027536b8013b.png)
