### ISSUE TITLE
正規表現の \p でマルチバイト文字がマッチしない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#439]
関連 #438

**Comment by k-takata** [comment]
文字クラスやコレクションについては、 #413 とか、新旧エンジン問わずにマルチバイト文字関連の問題がまだありそうです。（仕様・実装共に）

**Comment by ynkdir** [comment]
報告しました。
https://groups.google.com/d/msg/vim_dev/ghesxaJe3oM/G3f8puxYzs4J

**Comment by ynkdir** [comment]
7.4a.036 で修正されました。

**Comment by k-takata** [comment]
リンク: https://groups.google.com/d/topic/vim_dev/ccwVlETQt5c/discussion
