### ISSUE TITLE
Windowsで : 入りのバッファを変更するとゴミファイルが作られる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#44]
詳細条件は要検証。

test.vim

``` vim
edit foo:bar
put ='hoge'
qa!
```

```
vim -u NONE -i NONE -N -S test.vim
```

これで `foo` と言うファイルが作成される。
バッファを変更したタイミングで生成される模様。`:put` である必要はない。

**Comment by ynkdir** [comment]
おそらくNTFSの代替ストリーム関係ですね

**Comment by thinca** [comment]
すいません。今確認したら、バッファの変更すら必要なくファイルが生成されてました。
`:edit foo:bar` で ファイル `foo` が隠しファイルで生成されて、Vimを終了すると `foo` が通常のファイルになっていました。

**Comment by koron** [comment]
@ynkdir そう見えますねぇ。

NTFSではファイルが複数のストリームから構成されています。で、本ストリームはファイル名そのものなのですが、代替ストリームは「ファイル名:ストリーム名」という名称で識別され、本ストリームが消えたり移動したりすると一緒に消えたり移動したりできます。

…これWindowsでは2つめ以降の ':' をバッファ名に使えないようにするとか、そういう解決方法になるのか?

**Comment by koron** [comment]
余談: Vimはwriteの時に上書きじゃなくてコピーしたりできるので「代替ストリームのあるファイルを変更したら代替ストリーム消えた」ってバグがそのうち報告されそうですねw

**Comment by thinca** [comment]
余談: [Vim で NTFS の代替データストリームを読み書きする - 永遠に未完成](http://d.hatena.ne.jp/thinca/20091210/1260455246)

**Comment by ynkdir** [comment]
VIM and NTFS streams
http://thread.gmane.org/gmane.editors.vim.devel/18567

ファイルが消えたーという話ではなさそうかな？

I don't think it's a good idea to support them in Vim directly.
らしいです。

**Comment by ynkdir** [comment]
notepad foo:bar
でも作られるのでそういうもんなんじゃないですかね。

**Comment by koron** [comment]
本件の対応方法で思いつくのは
- ２つ目の`:`を禁止文字とする
- ドキュメント(TIPSとか)に記載する
- 何もしない

くらいだと考えますが、どうでしょうか。
私は何らかのドキュメントに記載してあれば十分かと思ってます。

あと、ふと気になったんだけどスワップファイルが代替ストリームにできたりしないかしら?

**Comment by mattn** [comment]
メモ帳でそうなるなら、vimもそのままの方がいい気もする。

**Comment by thinca** [comment]
foo:bar が foo と言うファイルの副ストリームなので、まず foo が作られるってことですね。理解しました。
ただ、メモ帳で私も試しましたが、メモ帳はそもそも存在しているファイルしか編集できない仕様らしく、存在していないファイルを開いた場合はその場で作成するか聞かれます。
Vimの場合、まだ存在していないファイルを開いた時点で、保存もしていないのにファイルが生成されるのが問題かと思います。

**Comment by mattn** [comment]
僕の環境ではファイル作られませんね。
`も　し　か　し　て　swapfile　が　foo:bar.swp　を　つ　く　ろ　う　と　し　て　い　る`

**Comment by thinca** [comment]
`:edit` の前に `:set noswapfile` 入れたら生成されなくなったので、恐らくそれが原因ですね。

**Comment by mattn** [comment]
ビンゴ!って事でバグですね。

**Comment by thinca** [comment]
もうちょっと動作を追って見ました。
`:edit foo:bar` の時点で、`foo:.bar.swp` と言う副ストリームが作成されていますね。終了すると副ストリームは消えますが、ファイルは残ります。
`:edit foo:bar` すると `[New DIRECTORY]` と出るので、どうやら `foo` をディレクトリとして認識しているようです。

**Comment by koron** [comment]
バグだとしてどう解決するの？

**Comment by mattn** [comment]
スワップファイルの作成時点で本来`foo`のスワップファイルとして`foo.swp`を作るはずが`foo:bar.swp`を作っていてこれが`foo`を作る原因なので、これを正しく`foo.swp`に保存する様にすれば
- `foo.swp`は終了後に消える
- `foo`は`:w`しない限り保存されない
- みんな幸せ

になるはず。

**Comment by mattn** [comment]
僕やりますね

**Comment by koron** [comment]
コメント入れておいたほうが良いんじゃない?
あとで読み返した時になんでこんなことすんのか、殆どの人はわかんないから。

**Comment by ynkdir** [comment]
調べていて `:swapname` なんてコマンドを始めて知った…。

細かいようですが

普通のファイルを開いた場合
`foo.txt` を開くと `.foo.txt.swp` が作成される。

代替ストリームを開いた場合
`foo:bar` を開くと `foo:.bar.swp` が作成される (`.foo:bar.swp` ではなく)。

という違いが問題で、その原因が

`foo:bar` が `foo` ディレクトリの `bar` ファイルと認識されてしまう。

ということなんだと思いますがどうでしょう。

つまり普通のファイルを開いたときに合わせるなら

Vim が `foo:bar` をファイル名として認識し、
`foo:bar` を開くと `.foo:bar.swp` が作成される。

というのが期待する動作な気がします。
この場合 .foo が作成されてしまうという新たな問題が出そうですが。

ちなみに `mkdir foo` 後に `:edit foo:bar` をすると [新ファイル] とでます。

あと例えば `c:foo.txt` は c ドライブのカレントディレクトリの foo.txt という意味にならしいのでそういうのもあってコロンの扱いはややこしそうですね。

**Comment by ynkdir** [comment]
あ、「期待する動作」とか書いてますがそのように直した方がいいと思っているわけでわなくて
私自身は代替ストリームはサポート外でいいと思ってます。

**Comment by mattn** [comment]
そうなんですよ。ディレクトリだと`c:.`はvalidなんですよね。

**Comment by koron** [comment]
foo:barの時って、Vimはfooをドライブ名だと思ってるってことかしら?

**Comment by ynkdir** [comment]
どうなんですかね。
単純にパス区切りにはなってるみたいです。

misc1.c

``` c
/*
 * return TRUE if 'c' is a path separator.
 */
    int
vim_ispathsep(c)
    int c;
{
#ifdef UNIX
    return (c == '/');      /* UNIX has ':' inside file names */
#else
# ifdef BACKSLASH_IN_FILENAME
    return (c == ':' || c == '/' || c == '\\');
# else
#  ifdef VMS
    /* server"user passwd"::device:[full.path.name]fname.extension;version" */
    return (c == ':' || c == '[' || c == ']' || c == '/'
        || c == '<' || c == '>' || c == '"' );
#  else
    return (c == ':' || c == '/');
#  endif /* VMS */
# endif
#endif
}
```

**Comment by mattn** [comment]
紛らわしいのでいったんコメント欄のパッチ削除。
vim_ispathsepおおざっぱだなーw

**Comment by k-takata** [comment]
todo.txt 内の代替ストリーム関連の項目。（代替ストリームということ以外は直接関連はないですが。）

> Win32, NTFS: When editing a specific infostream directly and 'backupcopy' is
> "auto" should detect this situation and work like 'backupcopy' is "yes".  File
> name is something like "c:\path\foo.txt:bar", includes a colon.  (Alex
> Jakushev, 2008 Feb 1)

**Comment by Shougo** [comment]
私も、プラグインで:を使用したバッファを作成していて引っかかりました……。
Vim標準のnetrwでhttp://なファイルを開いた時にもこの問題は発生するのでしょうか？
だとすると、かなり問題な気がします。

**Comment by mattn** [comment]
``` diff
diff -r 477b4f701156 src/memline.c
--- a/src/memline.c Sun Aug 25 17:46:08 2013 +0200
+++ b/src/memline.c Tue Sep 03 16:12:06 2013 +0900
@@ -4014,6 +4014,15 @@
     else
    retval = concat_fnames(dname, tail, TRUE);

+#ifdef WIN3264
+    if (retval)
+    {
+   for (t = gettail(retval); *t != NUL; mb_ptr_adv(t))
+       if (*t == ':')
+       *t = '%';
+    }
+#endif
+
     return retval;
 }

diff -r 477b4f701156 src/misc1.c
--- a/src/misc1.c   Sun Aug 25 17:46:08 2013 +0200
+++ b/src/misc1.c   Tue Sep 03 16:12:06 2013 +0900
@@ -4931,7 +4931,7 @@
     return (c == '/');     /* UNIX has ':' inside file names */
 #else
 # ifdef BACKSLASH_IN_FILENAME
-    return (c == ':' || c == '/' || c == '\\');
+    return (c == '/' || c == '\\');
 # else
 #  ifdef VMS
     /* server"user passwd"::device:[full.path.name]fname.extension;version" */
```

本来ファイル名として `foo:bar` が扱われて `foo%bar` とエスケープしたいけど今の仕組みだと `foo:bar` というファイル名で gettail (最後のセパレータ以降つまりファイル名だけ取得)を呼び出すと `bar` がファイル名となり `foo:` が残ってしまう。
本来 gettail は `foo:bar` が取れるべきなのでその修正と、ファイル名に対して `:` を `%` に入れ替える修正。

他の所に影響が出そうだけど、今の所使ってて問題なし。

**Comment by Shougo** [comment]
おお、それは良さそうですね。

**Comment by k-takata** [comment]
`c:foo.txt` など、ドライブ名付きの相対パスは大丈夫でしょうか。

**Comment by mattn** [comment]
悩んだんですが、`coo:bar` と `c:bar` の区別は vim に付けられないんじゃないかなーと思ったのです。

**Comment by k-takata** [comment]
`:` の位置を見ないと正しく判別できないですよね。
gettail() の中で Windows の場合は、アルファベット1文字 + `:` で始まる場合はドライブ名としてスキップするとか。
特別扱いがそこだけでよいかが課題…

**Comment by mattn** [comment]
mch_isFullName とかは結構しっかり見てるんですよね。

**Comment by k-takata** [comment]
これと組み合わせたらどうですかね？ 動作未確認。

``` diff
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -4800,7 +4800,7 @@

     if (fname == NULL)
    return (char_u *)"";
-    for (p1 = p2 = fname; *p2; )   /* find last part of path */
+    for (p1 = p2 = get_past_head(fname); *p2; )    /* find last part of path */
     {
    if (vim_ispathsep(*p2))
        p1 = p2 + 1;
```

**Comment by mattn** [comment]
良さげですね。てかなんでそれを使ってないの、という

**Comment by mattn** [comment]
``` diff
diff -r 477b4f701156 src/memline.c
--- a/src/memline.c Sun Aug 25 17:46:08 2013 +0200
+++ b/src/memline.c Tue Sep 03 18:42:25 2013 +0900
@@ -4014,6 +4014,15 @@
     else
    retval = concat_fnames(dname, tail, TRUE);

+#ifdef WIN3264
+    if (retval)
+    {
+   for (t = gettail(retval); *t != NUL; mb_ptr_adv(t))
+       if (*t == ':')
+       *t = '%';
+    }
+#endif
+
     return retval;
 }

diff -r 477b4f701156 src/misc1.c
--- a/src/misc1.c   Sun Aug 25 17:46:08 2013 +0200
+++ b/src/misc1.c   Tue Sep 03 18:42:25 2013 +0900
@@ -4800,7 +4800,7 @@

     if (fname == NULL)
    return (char_u *)"";
-    for (p1 = p2 = fname; *p2; )   /* find last part of path */
+    for (p1 = p2 = get_past_head(fname); *p2; )    /* find last part of path */
     {
    if (vim_ispathsep(*p2))
        p1 = p2 + 1;
@@ -4931,7 +4931,7 @@
     return (c == '/');     /* UNIX has ':' inside file names */
 #else
 # ifdef BACKSLASH_IN_FILENAME
-    return (c == ':' || c == '/' || c == '\\');
+    return (c == '/' || c == '\\');
 # else
 #  ifdef VMS
     /* server"user passwd"::device:[full.path.name]fname.extension;version" */
```

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/5hdAo9mcTjs/3BO7_5IamXYJ

**Comment by Shougo** [comment]
@mattn++;
ラベルを更新しました。

**Comment by k-takata** [comment]
ようやくパッチを試したのですが、`:e foo:bar` したら、保存せずとも `foo` ができるという状況は直っていないように見えるのですが…

**Comment by mattn** [comment]
Oh,...

**Comment by mattn** [comment]
原因掴んだ。直します。

**Comment by mattn** [comment]
うーん。いろいろ考えたんだけど、Windowsの場合は `:` を含むファイルは開けない様にした方がいいかもしれない。
もちろん実ファイルの場合。

**Comment by k-takata** [comment]
> 原因掴んだ。

何でしたか？

**Comment by koron** [comment]
> Windowsの場合は : を含むファイルは開けない様にした方がいいかもしれない。

エクスプローラーからは作れないですよね。
ただ「Vimのバッファ名として使えない」だと困りそう。
なので「バッファ名としては使えるがファイルに保存はできない」くらいが好ましいのかな。

**Comment by mattn** [comment]
>  何でしたか？

ロックかける為にダミーファイルを作ってるんだけど、そっちはスワップファイル名じゃなくて本物のバッファ名で作る。

**Comment by mattn** [comment]
あ、もしかしたら作れる様にして、削除の部分だけ小細工したら治るんじゃない？

**Comment by mattn** [comment]
あー、ファイルを開くのには fopen を使っていて、ファイルを削除するのには DeleteFile 使ってるのね。そりゃ整合性合わないわ。

**Comment by mattn** [comment]
これunlinkでいいんじゃね

**Comment by mattn** [comment]
なおったそげ

``` diff
diff -r d17ef148ada4 src/memline.c
--- a/src/memline.c Fri Aug 30 17:29:16 2013 +0200
+++ b/src/memline.c Thu Sep 05 12:51:20 2013 +0900
@@ -4014,6 +4014,15 @@
     else
    retval = concat_fnames(dname, tail, TRUE);

+#ifdef WIN3264
+    if (retval)
+    {
+   for (t = gettail(retval); *t != NUL; mb_ptr_adv(t))
+       if (*t == ':')
+       *t = '%';
+    }
+#endif
+
     return retval;
 }

diff -r d17ef148ada4 src/misc1.c
--- a/src/misc1.c   Fri Aug 30 17:29:16 2013 +0200
+++ b/src/misc1.c   Thu Sep 05 12:51:20 2013 +0900
@@ -4800,7 +4800,7 @@

     if (fname == NULL)
    return (char_u *)"";
-    for (p1 = p2 = fname; *p2; )   /* find last part of path */
+    for (p1 = p2 = get_past_head(fname); *p2; )    /* find last part of path */
     {
    if (vim_ispathsep(*p2))
        p1 = p2 + 1;
@@ -4931,7 +4931,7 @@
     return (c == '/');     /* UNIX has ':' inside file names */
 #else
 # ifdef BACKSLASH_IN_FILENAME
-    return (c == ':' || c == '/' || c == '\\');
+    return (c == '/' || c == '\\');
 # else
 #  ifdef VMS
     /* server"user passwd"::device:[full.path.name]fname.extension;version" */
diff -r d17ef148ada4 src/os_win32.c
--- a/src/os_win32.c    Fri Aug 30 17:29:16 2013 +0200
+++ b/src/os_win32.c    Thu Sep 05 12:51:20 2013 +0900
@@ -5510,16 +5510,33 @@
     WCHAR  *wn = NULL;
     int        n;
 #endif
-
-    win32_setattrs(name, FILE_ATTRIBUTE_NORMAL);
+    char   *p = name;
+
+    if (!mch_isFullName(p))
+    {
+   char *t;
+   p = (char *)vim_strsave(name);
+   for (t = gettail(p); *t != NUL; mb_ptr_adv(t))
+   {
+       if (*t == ':')
+       {
+       *t = 0;
+       break;
+       }
+   }
+    }
+
+    win32_setattrs(p, FILE_ATTRIBUTE_NORMAL);

 #ifdef FEAT_MBYTE
     if (enc_codepage >= 0 && (int)GetACP() != enc_codepage)
     {
-   wn = enc_to_utf16(name, NULL);
+   wn = enc_to_utf16(p, NULL);
    if (wn != NULL)
    {
        n = DeleteFileW(wn) ? 0 : -1;
+       if (p != name)
+       vim_free(p);
        vim_free(wn);
        if (n == 0 || GetLastError() != ERROR_CALL_NOT_IMPLEMENTED)
        return n;
@@ -5527,7 +5544,10 @@
    }
     }
 #endif
-    return DeleteFile(name) ? 0 : -1;
+    n = DeleteFile(p) ? 0 : -1;
+    if (p != name)
+   vim_free(p);
+    return n;
 }


```

**Comment by mattn** [comment]
おっとdouble freeありえる

**Comment by k-takata** [comment]
Alternate Data Stream を削除する際に、元ファイルまで勝手に消すのはまずくないですか。

**Comment by mattn** [comment]
あー、tskn

**Comment by mattn** [comment]
そうなると自分で作ったのかどうかを覚えておかないといけないのか...

**Comment by mattn** [comment]
そうか、dummyfdだけ `:` 避ければいいな

**Comment by mattn** [comment]
更新ed

https://gist.github.com/mattn/6444548

**Comment by k-takata** [comment]
Bramから指摘が来てますね。
https://groups.google.com/d/msg/vim_dev/5hdAo9mcTjs/AZxbgDkEVMAJ

> It would be better to only make a copy of the file name when needed,
> thus first check if there is a colon.  That avoids the copy in most
> cases. 

gettail() したところに `:` が含まれていれば、コピーして書き換えるのがいいんですかね。

**Comment by mattn** [comment]
この修正、UNCでちゃんと動かないので調査中なのです。

On 9/7/13, K.Takata notifications@github.com wrote:

> Bramから指摘が来てますね。
> https://groups.google.com/d/msg/vim_dev/5hdAo9mcTjs/AZxbgDkEVMAJ
> 
> > It would be better to only make a copy of the file name when needed,
> > thus first check if there is a colon.  That avoids the copy in most
> > cases.
> 
> gettail() したところに `:` が含まれていれば、コピーして書き換えるのがいいんですかね。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/44#issuecomment-23976628

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
> この修正、UNCでちゃんと動かないので調査中なのです。

軽く試したのですが、再現できませんでした。
一応 todo 入りしました。

> Patch to avoid problem with colon in file name. (Yasuhiro Matsumoto, 2013 Sep
> 5) Only copy file name when needed.

**Comment by mattn** [comment]
UNC上にあるzipファイルを開いてzip.vimでブラウズするとパッチを当てた方だとブラウズ出来ないのです。

**Comment by mattn** [comment]
やたー！
UNCで動かない原因やっと見つけた

https://gist.github.com/6493881

**Comment by k-takata** [comment]
:+1:
それ以外の、vim_ispathsep() を使っている部分は大丈夫だろうかというのが気になってきました。

**Comment by koron** [comment]
:+1:

**Comment by mattn** [comment]
一応一通り試したつもり

**Comment by k-takata** [comment]
todo.txt 入りしていました。

>  Patch to avoid problem with colon in file name. (Yasuhiro Matsumoto, 2013 Sep
> 5) Only copy file name when needed: Sep 9.

**Comment by k-takata** [comment]
7.4.066
https://groups.google.com/d/topic/vim_dev/FWdftOhBcZ8/discussion
