### ISSUE TITLE
日本語manファイルを本家に取り込んでもらう

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#440]
https://github.com/vim-jp/vimdoc-ja/tree/master/doc にある以下の日本語manファイルを本家に取り込んでもらってはどうでしょうか。
- evim-ja.UTF-8.1
- vim-ja.UTF-8.1
- vimdiff-ja.UTF-8.1
- vimtutor-ja.UTF-8.1
- xxd-ja.UTF-8.1

ここに置いてあるだけだと、誰も使っていないのではないかと…

**Comment by k-takata** [comment]
修正案 (manファイル以外):
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/7eb54d4f0bb37ff353451c88c5aaca99a518935d/add-man.ja.patch?at=default

manファイル追加用パッチ:
https://bitbucket.org/k_takata/vim-cygwin-linux-mq/src/7eb54d4f0bb37ff353451c88c5aaca99a518935d/add-man.ja-2.patch?at=default

Ubuntu 12.04 にインストールして、`man vim` で日本語manページが表示されることを確認しました。

**Comment by ynkdir** [comment]
ありがとうございます。
おまかせしてもいいですか。

**Comment by k-takata** [comment]
翻訳者はどのように言いましょうか。 vim-jp.org?
vim-jp の英語名称（英語説明）って決まってましたっけ？

`*-ja.UTF-8.1` だけ用意して、`*-ja.1`を用意していないのはちょっと気になりますが、大丈夫でしょうかね？

**Comment by ynkdir** [comment]
> 翻訳者はどのように言いましょうか。 vim-jp.org?
> vim-jp の英語名称って決まってましたっけ？

個人的にはこういうのは `I` がいいと思います。
やっぱり書いた人が出すのがスジかなと。
私が書いたんでしたっけ。
まあほとんどk-takataさんの赤ペンが入ってるのでk-takataさんでも構わないと思うんですが。
どうするのがいいんでしょうね。なんだったら私が出します。

> _-ja.UTF-8.1 だけ用意して、_-ja.1を用意していないのはちょっと気になりますが、大丈夫でしょうかね？

あんまり仕組みがよくわかってないんですが、そのへんはbramにおまかせで…

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/2CfkJA0RyOI/discussion

**Comment by k-takata** [comment]
翻訳者は "Yukihiro Nakadaira, I and vim-jp.org members" としておきました。

**Comment by ynkdir** [comment]
すみませんありがとうございます

**Comment by k-takata** [comment]
7.4a.015 に入りました。
https://groups.google.com/d/topic/vim_dev/Q9jsZa1463g/discussion

**Comment by k-takata** [comment]
気にしていた翻訳者は Ken Takata, Yukihiro Nakadaira, et al. となりました。
これなら特に問題ないですね。

**Comment by ynkdir** [comment]
ありがとうございます。
私の分についてはクレジットはどうでもいいんですけどそのへんちゃんとしとかないともしものときに自分のまずい仕事のせいで他人に不名誉がかかるのが忍びない…。

**Comment by crazymaster** [comment]
manファイル表示が崩れてません？
![screenshot_from_2013-07-15 07 49 18](https://f.cloud.github.com/assets/1528093/795062/aa3c8626-ecd7-11e2-842f-83956d5fd83c.png)

**Comment by k-takata** [comment]
たぶん man コマンドの問題だと思います。
欧米の言語に合わせて、空白以外の部分では改行しようとしないのでは。

**Comment by crazymaster** [comment]
他のでは問題ないので書き方の問題ですかね？
![screenshot_from_2013-07-15 11 54 42](https://f.cloud.github.com/assets/1528093/795470/ffda1f40-ecf9-11e2-8d56-17ff7f6cb4b8.png)

**Comment by ynkdir** [comment]
例えば ubuntu の /usr/share/man/ja/man1/su.1.gz は man su で表示すると大丈夫なのに
その内容を手元にコピーして (~/tmp/su.1 とか) から man で表示すると崩れるので
システムの設定かなにかが効いてるきがします

**Comment by ynkdir** [comment]
vim-ja.UTF-8.1 を /usr/share/man/ja/man1/vim.1 に置いて man vim で表示したら崩れずに表示されました。

**Comment by ynkdir** [comment]
http://nukino.github.io/blog/2012/02/04/Cygwinman/
ディレクトリ名が関係するんですかね

**Comment by k-takata** [comment]
/usr/share/local/man/ja.UTF-8/ を ja/ にリネームしてみたところ、崩れなくなりました。ええぇぇっ!?

``` diff
--- a/src/Makefile
+++ b/src/Makefile
@@ -1402,7 +1402,7 @@
 DEST_MAN_IT = $(DEST_MAN_TOP)/it$(MAN1DIR)
 DEST_MAN_IT_I = $(DEST_MAN_TOP)/it.ISO8859-1$(MAN1DIR)
 DEST_MAN_IT_U = $(DEST_MAN_TOP)/it.UTF-8$(MAN1DIR)
-DEST_MAN_JA_U = $(DEST_MAN_TOP)/ja.UTF-8$(MAN1DIR)
+DEST_MAN_JA_U = $(DEST_MAN_TOP)/ja$(MAN1DIR)
 DEST_MAN_PL = $(DEST_MAN_TOP)/pl$(MAN1DIR)
 DEST_MAN_PL_I = $(DEST_MAN_TOP)/pl.ISO8859-2$(MAN1DIR)
 DEST_MAN_PL_U = $(DEST_MAN_TOP)/pl.UTF-8$(MAN1DIR)
```

インストール先のディレクトリ名から .UTF-8 を取ってしまった方がいいんですかね？

**Comment by ynkdir** [comment]
謎ですねえ。ここはmanにがんばってほしいきがしますけど…

**Comment by k-takata** [comment]
man というか groff の問題のようです。
こうしたら、ja.UTF-8/ のままできれいに表示されるようになりましたが…、man/groff で何とかしてもらいたいところ。

``` sh
$ cd /usr/share/groff/1.21/tmac/
$ sudo cp ja.tmac ja.UTF-8.tmac
```

**Comment by ynkdir** [comment]
eureka!
ubuntu の vim-common パッケージだと例えば vim-fr.UTF-8.1 を fr/ に入れてるのでそのへんはパッケージャがよきにはからってくれるのではないかと思います。
まあでも手っ取り早く ja にかえちゃってもいいですけどね。問題なければ。
マナーがよくわからない…。

**Comment by k-takata** [comment]
> マナーがよくわからない…。

同じく…。

**Comment by k-takata** [comment]
Linux以外だとどうなんだろうという疑問もありますが、投げました。
https://groups.google.com/d/topic/vim_dev/eAM3II6PJ7Y/discussion

**Comment by ynkdir** [comment]
ありがとうございます。

**Comment by k-takata** [comment]
7.4b.013 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/-J0JVdJMbOU/discussion

**Comment by crazymaster** [comment]
ja.UTF-8にも入っていてそっちが優先されているっぽい

**Comment by k-takata** [comment]
前回インストール時のがそのまま残っているだけではないでしょうか。
取り込まれる前の Makefile で一旦 make uninstall しておくか、手動で削除しておく必要があると思います。

**Comment by crazymaster** [comment]
あー、そういえばそうかもしれません

**Comment by crazymaster** [comment]
削除してやり直したけど、どうやら ja.UTF-8 の方を参照してるみたいですね
そしてファイルがないからエラーになる

**Comment by crazymaster** [comment]
もういっそ [manpages-ja](http://sourceforge.jp/projects/linuxjm/) に入れてもらった方がいいような気がしないでもない

**Comment by ynkdir** [comment]
おつかれさまです。
私のとこでは動作okです。 ubuntu-13.04

**Comment by crazymaster** [comment]
> 私のとこでは動作okです。 ubuntu-13.04

ということは私の環境の問題？
まあめったに使わないからいいのだけれど...

**Comment by ynkdir** [comment]
キャッシュ的な話ですかね
man -u vim とか
