### ISSUE TITLE
libintl.dll だけでなく intl.dll もロードするようにする

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#441]
gettext は、libintl.dll をロードするようになっていますが、intl.dll もロードできるようにしたいです。
iconv は、iconv.dll のロードを試し、ダメだったら libiconv.dll をロードするようになっています。

todo.txt を見ると、以下のような記述があります。

> -   Load intl.dll too, not only libintl.dll. (Mike Williams, 2006 May 9, docs
>   patch May 10)

このパッチ、どこかに公開されていないでしょうか。

自分では、以下のようなパッチを当てて使っています。
https://bitbucket.org/k_takata/vim-win32-mq/src/76bc67551eb9a59dd1b8799ef4de89536d73fd08/support-alt-gettext-dll.patch?at=default

**Comment by koron** [comment]
http://marc.info/?l=vim-dev ＜このへんあさってみたけど見当たらなかった。

**Comment by ynkdir** [comment]
ユーザー側の対処でよければリネームか forwarding dll というのもあるらしいです。
https://gist.github.com/ynkdir/3698918

**Comment by koron** [comment]
> forwarding dll というのもある

:+1: これ、面白いですねぇ

**Comment by k-takata** [comment]
> forwarding dll

Advanced Windowsにも載ってました。「20.4 関数フォワーダ」
（第6版は「インサイドWindows」でしたか。）

**Comment by k-takata** [comment]
#778 では、iconv.dll, libiconv.dll, libiconv2.dll (gnuwin32), libiconv-2.dll (msys2)の順に検索することになりました。
gettextのDLL名も同様に、intl.dll (kaoriya), libintl.dll (Vim7.4 公式バイナリ), libintl3.dll (gnuwin32), libintl-8.dll (msys2) の少なくとも4つがあります。

**Comment by k-takata** [comment]
7.4.1106で、libintl.dll と libintl-8.dll を認識するようになりました。intl.dll はどうしよう。

**Comment by k-takata** [comment]
パッチを送って、
https://groups.google.com/d/topic/vim_dev/4ZZ5JFFS68k/discussion
8.1.0452 で取り込まれました。(todoに載ってることを言及するのは忘れてたｗ)
https://groups.google.com/d/topic/vim_dev/hcMqt1jJC8Y/discussion
ドキュメントはBramが更新してくれました。

**Comment by k-takata** [comment]
> このパッチ、どこかに公開されていないでしょうか。

Bramによると、

> It was a message directly to me.
> 
> Looks like I'm only 12 years behind including patches :-).

ということでした。そりゃ、公開されてるわけないわｗ
