### ISSUE TITLE
Macにおける lua/dyn のライブラリ名が適切でない

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#442]
Mac上で --enable-luainterp=dynamic でビルドすると、dlopenするライブラリ名が liblua***.so になります。
拡張子は .dylib であるべきです。

**Comment by ichizok** [comment]
#348 のパッチでは対応されています。
https://gist.github.com/shirosaki/5663617#file-vim_luajit-patch-L313

**Comment by ichizok** [comment]
対応部分だけ抜き出してpatchにしました。
https://gist.github.com/ichizok/6005211

**Comment by k-takata** [comment]
7.4a.045 で LuaJIT 対応を含めて取り込まれました。
https://groups.google.com/d/topic/vim_dev/4neHRqy2TgQ/discussion
