### ISSUE TITLE
luaがない時に不正なconfig.mkが作られる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#443]
#348 より派生

キッカケ

> > ダイナミックリンク先が libluajit.so になる(実際にインストールされているのは libluajit-5.1.so)だが
> 
> 正確には `libluajit.so.` になってた。
> 原因は実行ファイル `luajit` がPATH上になかったことだった。

方針

> luajit が見つからない時に `libluajit.so.` (末尾のピリオドが余分)になってしまうのは避けたほうが良い。
> configure時に luajit が見つからなければエラーで止めるか
> もしくは `libluajit.so` を使うとかはできないだろうか?

調査 ([結果詳細](https://github.com/vim-jp/issues/issues/348#issuecomment-20935862))

> patchなしでふつうのluaを使ったビルドでも、luaがPATHになくて、*.soを見つけられない
> 
> for loop で*.soの絶対パスを探している処理があるのですが、最後まで見つからないと、
> 最後に試したパターンが使われるようになっているため

**Comment by h-east** [comment]
liblua(jitじゃないほう)が見つからない場合はエラーにするようにしました。(--enable-fail-if-missing指定時)

``` diff
diff -r c015eedb9b4a src/configure.in
--- a/src/configure.in  Sun Jul 14 15:06:50 2013 +0200
+++ b/src/configure.in  Mon Jul 15 02:32:01 2013 +0900
@@ -494,6 +494,7 @@
       if test -f "${vi_cv_path_lua_pfx}/bin/cyglua-${vi_cv_version_lua}.dll"; then
    vi_cv_dll_name_lua="cyglua-${vi_cv_version_lua}.dll"
       else
+   vi_cv_dll_name_lua=""
    multiarch=`dpkg-architecture -qDEB_HOST_MULTIARCH 2> /dev/null`
    if test "X$multiarch" != "X"; then
      lib_multiarch="lib/${multiarch}"
@@ -507,13 +508,16 @@
      for sover in "${vi_cv_version_lua}.so" "-${vi_cv_version_lua}.so" ".so.${vi_cv_version_lua}"; do
        for i in .0 .1 .2 .3 .4 .5 .6 .7 .8 .9 ""; do
          if test -f "${vi_cv_path_lua_pfx}/${subdir}/liblua${sover}$i"; then
-       sover2="$i"
+       vi_cv_dll_name_lua="liblua${sover}$i"
        break 3
          fi
        done
      done
    done
-   vi_cv_dll_name_lua="liblua${sover}$sover2"
+   if test "$fail_if_missing" = "yes" -a -z "$vi_cv_dll_name_lua"; then
+     AC_MSG_ERROR([NOT FOUND!
+   You need to install a shared lua library])
+   fi
       fi
       AC_DEFINE(DYNAMIC_LUA)
       LUA_LIBS=""
```

PS
src/auto/configureの差分は送らなくていいですよね？
（使ってるautoconfのver(2.69)が元のver(2.65)と違うので盛大に差分出てるｗ）

**Comment by k-takata** [comment]
> src/auto/configureの差分は送らなくていいですよね？

不要です。私も送っていません。

**Comment by h-east** [comment]
@shirosaki さんが今日vim_devに投げたpatchでこの件も対応しているようなので、そちらにおまかせします。
https://github.com/vim-jp/issues/issues/348#issuecomment-20945496

↓のコメントの感じだと元patch書いたk-takataさんか私がpatch書くべき?と思ってpatch書いたけど、心配無用だった:grin:
https://github.com/vim-jp/issues/issues/348#issuecomment-20935862

**Comment by k-takata** [comment]
7.4a.045 で LuaJIT 対応を含めて取り込まれました。
https://groups.google.com/d/topic/vim_dev/4neHRqy2TgQ/discussion
