### ISSUE TITLE
Windowsで $HOME/.vim/{vimrc,gvimrc} が読み込まれない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#445]
7.3.1178 で、$HOME/.vim/{vimrc,gvimrc} が読み込まれるようになり、設定を1つのディレクトリにまとめることができるようになりましたが、Windows の場合、$HOME/vimfiles/{vimrc,gvimrc} のみが読み込まれて $HOME/.vim/{vimrc,gvimrc} は読み込まれません。

vimrc 以外についてはWindows でも、$HOME/.vim/ も読み込まれることから、vimrc についても同じようにした方が良いと思います。

**Comment by thinca** [comment]
> vimrc 以外についてはWindows でも、$HOME/.vim/ も読み込まれる

そんなことはなかったと思いますが…。

**Comment by k-takata** [comment]
mjd?
おおっと、`:help 'runtimepath'` 見たら完全に私の勘違いっぽいので取り下げます。

**Comment by koron** [comment]
仕様の勘違いによる起票。
よって wontfix ではなく worksforme へ振り替えます。
