### ISSUE TITLE
Windowsでマウスポインタが消えたままになる

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#446]
todo.txt に以下のような記載があります。

> 8   Win32: When mouse is hidden and in the toolbar, moving it won't make it
>     appear. (Sami Salonen)

マウスポインタがツールバーの中にあって、文字入力でポインタが消えると、マウスを動かしてもポインタが再表示されません。ツールバーだけでなくタブラインでも同様です。

パッチを作ってみました。ツールバーとタブラインのWndProcをフックしてマウス関連のイベントが発生したらポインタを再表示するようにしています。

https://bitbucket.org/k_takata/vim-win32-mq/src/0d7a07a41cd1ae32066eab90a4efd83b8022f3a1/fix-mouse-hidden-in-tabline-and-toolbar.patch

# 実は、スクロールバーについても同様なのですが、今回は対応していません。

**Comment by mattn** [comment]
再現しないなー

**Comment by k-takata** [comment]
そうですか？

再現手順:
1. マウスポインタをツールバーに合わせる。
2. 何かキーをタイプすると、マウスポインタが消える。
3. ツールバーからマウスが出ない程度に、マウスを動かすと、ポインタは消えたまま。ツールバーから出れば表示される。

**Comment by mattn** [comment]
あーそういう意味なのか

2013/7/16 K.Takata notifications@github.com

> そうですか？
> 
> 再現手順:
> 1. マウスポインタをツールバーに合わせる。
> 2. 何かキーをタイプすると、マウスポインタが消える。
> 3. ツールバーからマウスが出ない程度に、マウスを動かすと、ポインタは消えたまま。ツールバーから出れば表示される。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vim-jp/issues/issues/446#issuecomment-21041603
> .

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
SubclassWindow() とか CallWindowProc() とか W版を使っていないが、大丈夫だろうか？
一応 Win7 では、タブラインには Unicode ファイル名も正しく表示されたが。

**Comment by k-takata** [comment]
自分のところでは問題ないので、投げてしまいました。
https://groups.google.com/d/topic/vim_dev/ZGSBopGLuO4/discussion

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/ZGSBopGLuO4/7uTq2M4kjJMJ

> Thanks.  I'll have to decide if this is safe to include in this stage of
> beta-testing...  Any chance this will fail in some configuration?

何か返事した方がいいのだろうか？

**Comment by k-takata** [comment]
7.4a.037 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/_OuvmrekQNw/discussion
