### ISSUE TITLE
端末のウインドウが小さいと失敗するテストがある

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#447]
#429 からの派生です。

> 端末のウインドウが小さいと途中で `-- 継続 --` が出たりして 37 47 92 93 が失敗します。
> 
> まとめてみた < https://gist.github.com/h-east/4360424#comment-688226

| Size\test | 13 | 31 | 37 | 47 | 62 | 84 | 88 | 92 | 93 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 80x24 | OK | OK | OK | OK | OK | OK | OK |  |  |
| 80x20 | OK | OK | OK | OK | OK | OK | OK |  |  |
| 80x15 | OK | OK | NG | NG | OK | OK | OK |  |  |
| 80x10 | OK | OK | NG | NG | OK | OK | OK |  |  |
| 80x5 | NG | NG | NG | NG | NG | NG | NG |  |  |

**Comment by mattn** [comment]
いっそ `:set nomore` で...

**Comment by h-east** [comment]
最新Ver.(Vim 7.4a.44) で再度確認。 (on fedora 18 via PuTTY)

| Size\test | 13 | 31 | 37 | 47 | 62 | 84 | 88 | 91 | 92 | 93 | 96 | 備考 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 80x24 | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK | OK |  |
| 80x20 | OK | OK | OK | OK | OK | OK | OK | OK | **NG** | **NG** | OK |  |
| 80x15 | OK | OK | **NG** | **NG** | OK | OK | OK | OK | **NG** | **NG** | OK |  |
| 80x10 | OK | OK | **NG** | **NG** | OK | OK | OK | OK | **NG** | **NG** | OK | `-- 継続 --` 2回 |
| 80x5 | **NG** | **NG** | **NG** | **NG** | **NG** | **NG** | **NG** | **NG** | **NG** | **NG** | **NG** | `-- 継続 --` 8回 |

わぉ！test92, test93は失敗すると test92.in, test93.in が上書きされて中身空っぽになるので以後80x24でtestしても `E486`でエラーになってまう！(苦笑)
これはこれで直したほうがいいですね:grin:

**Comment by k-takata** [comment]
`-- 継続 --` が出るのは、`:set nomore` しておいた方が良さそうですね。

>  test92.in, test93.in が上書きされて中身空っぽになる

ひどいｗｗｗ
画面の高さが足りないと、`:new test.out` に失敗して、`:w` で test*.in に上書きしてしまうということですか。
`:w test.out` にでもしておけば良さそう?

**Comment by h-east** [comment]
@mattn @k-takata 
`:set nomore` 賛成。
たしかtestってデフォで`set compatible`(== set nomore)ですよね。`-- 継続 --`が出てるってことは`set nocompatible`で動かしてるってことになりますね。
ということは`set nocp`してるとこを見つけては`set nocp nomore`に変えればOKっすかね？

> ひどいｗｗｗ

最初何が起きているのか分からんかったですよｗｗ。

私はここ最近、当局に進捗をdailyでチェックされているのであんまり時間取れませんのでどなたかお願いします。
(もうすぐhourlyでチェックされそうｗｗ)

**Comment by Shougo** [comment]
> 私はここ最近、当局に進捗をdailyでチェックされているのであんまり時間取れませんのでどなたかお願いします。
> (もうすぐhourlyでチェックされそうｗｗ)

それは怖い……。私も胃が痛くなりそうです。

**Comment by h-east** [comment]
お久しブリーフ:jeans:
当局から信頼を得ましたがおっさん問題が勃発し昨日解決に至りました。

k_takataさんの

> :w test.out にでもしておけば良さそう?

でtest92.in, test93.inの中身が空っぽになるのは直りました。

テスト開始前に`columns`と`lines`チェックして80x24未満の場合は「サイズ広げないとテストやらねぇぞ(#ﾟДﾟ)ｺﾞﾙｧ!!」的な文言出して終了するとかどうだろう？

``` diff
diff -r a83960ec9e6d src/testdir/test92.in
--- a/src/testdir/test92.in Sun Sep 08 20:00:48 2013 +0200
+++ b/src/testdir/test92.in Wed Sep 11 00:58:38 2013 +0900
@@ -33,7 +33,7 @@
 :mksession! test.out
 :new test.out
 :v/\(^ *normal! 0\|^ *exe 'normal!\)/d
-:w
+:w test.out
 :qa!
 ENDTEST

diff -r a83960ec9e6d src/testdir/test93.in
--- a/src/testdir/test93.in Sun Sep 08 20:00:48 2013 +0200
+++ b/src/testdir/test93.in Wed Sep 11 00:58:38 2013 +0900
@@ -33,7 +33,7 @@
 :mksession! test.out
 :new test.out
 :v/\(^ *normal! 0\|^ *exe 'normal!\)/d
-:w
+:w test.out
 :qa!
 ENDTEST
```

**Comment by h-east** [comment]
`make test`開始時に`columns`と`lines`をチェックして 80x24未満なら

```
test1 FAILED - Terminal width and/or height are too small
Please change terminal size to 80x24 or larger
```

というメッセージを出してエラー終了するようにしてみた。

英文の添削とかもしてくれると有難いです。

``` diff
diff -r a83960ec9e6d src/testdir/Makefile
--- a/src/testdir/Makefile  Sun Sep 08 20:00:48 2013 +0200
+++ b/src/testdir/Makefile  Thu Sep 12 00:37:44 2013 +0900
@@ -50,7 +50,8 @@
 $(SCRIPTS) $(SCRIPTS_GUI): $(VIMPROG)

 RM_ON_RUN = test.out X* viminfo
-RM_ON_START = tiny.vim small.vim mbyte.vim mzscheme.vim lua.vim test.ok
+RM_ON_START = tiny.vim small.vim mbyte.vim mzscheme.vim lua.vim test.ok \
+             wrongtermsize
 RUN_VIM = $(VALGRIND) $(VIMPROG) -u unix.vim -U NONE --noplugin -s dotest.in

 clean:
@@ -59,7 +60,12 @@
 test1.out: test1.in
    -rm -rf $*.failed $(RM_ON_RUN) $(RM_ON_START)
    $(RUN_VIM) $*.in
-   @/bin/sh -c "if diff test.out $*.ok; \
+   @/bin/sh -c "if test -e wrongtermsize; \
+       then echo; \
+       echo test1 FAILED - Terminal width and/or height are too small; \
+       echo Please change terminal size to 80x24 or larger; \
+       echo; exit 1; \
+       elif diff test.out $*.ok; \
        then mv -f test.out $*.out; \
        else echo; \
        echo test1 FAILED - Something basic is wrong; \
diff -r a83960ec9e6d src/testdir/test1.in
--- a/src/testdir/test1.in  Sun Sep 08 20:00:48 2013 +0200
+++ b/src/testdir/test1.in  Thu Sep 12 00:37:44 2013 +0900
@@ -21,6 +21,10 @@
 :" Write a single line to test.out to check if testing works at all.
 :%d
 athis is a test:w! test.out
+:" If columns or lines are small, make wrongtermsize empty.
+:" (Some tests will fail. When columns and/or lines are small)
+:if &lines < 24 || &columns < 80 | sp another | w! wrongtermsize | q | endif
+:"
 :" Create small.vim and tiny.vim empty, create mbyte.vim to skip the test.
 0D:w! small.vim
 :w! tiny.vim
diff -r a83960ec9e6d src/testdir/test92.in
--- a/src/testdir/test92.in Sun Sep 08 20:00:48 2013 +0200
+++ b/src/testdir/test92.in Thu Sep 12 00:37:44 2013 +0900
@@ -33,7 +33,7 @@
 :mksession! test.out
 :new test.out
 :v/\(^ *normal! 0\|^ *exe 'normal!\)/d
-:w
+:w test.out
 :qa!
 ENDTEST

diff -r a83960ec9e6d src/testdir/test93.in
--- a/src/testdir/test93.in Sun Sep 08 20:00:48 2013 +0200
+++ b/src/testdir/test93.in Thu Sep 12 00:37:44 2013 +0900
@@ -33,7 +33,7 @@
 :mksession! test.out
 :new test.out
 :v/\(^ *normal! 0\|^ *exe 'normal!\)/d
-:w
+:w test.out
 :qa!
 ENDTEST

```

**Comment by h-east** [comment]
Englishをちょっと手直しして送った。
https://groups.google.com/d/msg/vim_dev/-U309gcEArU/OYM0U4wKSeoJ

**Comment by mattn** [comment]
@h-east ++

**Comment by k-takata** [comment]
7.4.033 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/1_cRB0iW84M/discussion

**Comment by h-east** [comment]
あざす。
小ちゃいpatchやのにEnglishいっぱい修正されたw
でも真意は伝わって取り込まれたからOK。
