### ISSUE TITLE
ctags.exe のパスが通ってないのに executable("ctags.exe") が 1 を返す

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#449]
ctags.exe へのパスが通ってない（$PATH にない）状況でも `executable("ctags.exe")` が 1 を返します。
#### 再現環境
- WindowsXP SP3
- Kaoriya 版 Vim 7.3.969 / 7.3.1314 / 7.4b BETA

``` vim
" ctags.exe へのパスが通っていない状態で
echo executable("ctags.exe")
" => 1

echo system("ctags.exe")
"'ctags.exe' は、内部コマンドまたは外部コマンド、^@操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

他にも `curl.exe` や `xxd.exe` で試してみましたが `ctags.exe` でのみ再現しました。
他にも再現する方はいますでしょか。

<br>
#### 追記

以下の環境では再現しない
- Windows8 Kaoriya 版 Vim 7.3.969 
- Windows7 kaoriya 版 Vim 7.3.1314

**Comment by raa0121** [comment]
Windows8 Kaoriya 版 Vim 7.3.969 においては 再現しませんでした

**Comment by Shougo** [comment]
他の人が再現できていないので、osyoさんの環境の問題という可能性が大変濃厚です。osyoさんは他に再現できるWindows環境はありますか？

**Comment by Shougo** [comment]
executable()の実装には`SearchPath()`が使用されています。
lingrにも書きましたが、osyoさんの環境で`SearchPath()`を使ってctags.exeを検索するプログラムを書いてみて、結果を調べてみてください。

**Comment by osyo-manga** [comment]
追記しました。

**Comment by Shougo** [comment]
> 追記しました。

追記された情報だけ見ると、Windows XPのみで再現するようですが、理由が謎ですね。

**Comment by osyo-manga** [comment]
> 追記された情報だけ見ると、Windows XPのみで再現するようですが、理由が謎ですね。

今のところはそうですね。
わたし以外の WindowsXP 環境でも再現しなければ環境固有の問題という事になるんですけども。

**Comment by mattn** [comment]
```
:!ctags --help
```

やってみてもらえますか

**Comment by osyo-manga** [comment]
> :!ctags --help
> やってみてもらえますか

`system()` と同様に『コマンドが見つからない』と出力されますね。

**Comment by Shougo** [comment]
> わたし以外の WindowsXP 環境でも再現しなければ環境固有の問題という事になるんですけども。

Windows XP環境が手元にないので厳しいですね。

**Comment by mattn** [comment]
```
where ctags*
```

ってやってみて貰えます？

**Comment by mattn** [comment]
ちなみに僕の環境だと ctags.exe をリネームしたら executable が 0 を返しているので、何かしら環境の要因が大きいです。

**Comment by osyo-manga** [comment]
すみません、解決しました。
やはりわたしの環境が原因だったみたいです。
元々は ctags.exe が `C:\WINDOWS\system32\ctags.exe` に保存されていたんですが、`C:\WINDOWS\system32` へのパスが通っていない状態でも `C:\WINDOWS\system32` に ctags.exe が存在していれば `executable("ctags")` が `1` を返していたようです。
が、実際には `C:\WINDOWS\system32` へのパスは通っていないので ctags.exe の呼び出しに失敗していた模様です。
お騒がせしました…。

**Comment by koron** [comment]
ん～ちょっとひかかりますね。

PATHの通ってない `C:\WINDOWS\system32` が `executable()` にひっかかるのは
Windows の問題なのか Vim の問題なのかって点がひっかかります。
仮に後者なら Vim で対策できますよね。

ちょっと調査の必要があると思うので reopen しておきます。

**Comment by osyo-manga** [comment]
Vim が内部で使用している `SearchPath()` が system と system32 も参照しているのが今回の原因みたいですね。
[参照](http://lingr.com/room/vim/archives/2013/07/30#message-16038799)

**Comment by koron** [comment]
[MSDN: SearchPath](http://msdn.microsoft.com/ja-jp/library/cc429699.aspx) の3番目

> Windows 95：Windows のシステムディレクトリ。このディレクトリのパスは、 関数で取得できます。
> 
> Windows NT/2000：32 ビットの Windows システムディレクトリ。このディレクトリのパスは、GetSystemDirectory 関数で取得できます。このディレクトリの既定の名前は、SYSTEM32 です。

これか…
この SearchPath と実行時の使われる検索パスがズレてるってことになりますねぇ。

[MSDN: CreateProcess](http://msdn.microsoft.com/ja-jp/library/cc429066.aspx) を見ると
lpCommandLine の説明に同じことが書いてあるので、このレベルではズレてはいなさそう。
Vim が実行時になんかやってんのかな?

**Comment by DeaR** [comment]
`!`や`system`の際は実際のプロセスを起動するのは`cmd /c`だから、ですかね？

**Comment by k-takata** [comment]
もしかして、mattnさんのこのパッチで直ったりしません？

todo.txt:

> Win32: use different args for SearchPath()? (Yasuhiro Matsumoto, 2009 Jan 30)

https://groups.google.com/d/topic/vim_dev/eEBXYLz0NHI/discussion

**Comment by ynkdir** [comment]
直りますね

**Comment by mattn** [comment]
@osyo-manga ping

**Comment by osyo-manga** [comment]
pong

**Comment by koron** [comment]
ching

**Comment by k-takata** [comment]
@mattn さんのパッチですが、

``` diff
+            wcscpy(wnewpath, L";.;");
```

ここ、最初の`;`は不要な気がするのですがどうでしょう？

**Comment by k-takata** [comment]
とりあえず報告done。
https://groups.google.com/d/topic/vim_dev/shn22nGcOVo/discussion
上記のセミコロンについては今回は報告していません。

**Comment by osyo-manga** [comment]
@k-takata ++

**Comment by k-takata** [comment]
@mattn さんからの反応がありませんでしたが、余計なセミコロンを削除したパッチを投げました。
https://groups.google.com/d/msg/vim_dev/shn22nGcOVo/WjsijA2h148J

**Comment by mattn** [comment]
あー、おくれました。すみません。

**Comment by k-takata** [comment]
todo入りしました。

> Win32: use different args for SearchPath()? (Yasuhiro Matsumoto, 2009 Jan 30)
> Also fixes wrong result from executable().
> Update from Ken Takata, 2014 Jan 10.

**Comment by k-takata** [comment]
7.4.235以降でコンパイルエラーになるので、修正版を投げました。
https://groups.google.com/d/msg/vim_dev/shn22nGcOVo/G3I2Gx_iOnwJ

**Comment by mattn** [comment]
パッチを少し変えて問題を明確にするようにしました。

https://groups.google.com/forum/#!topic/vim_dev/eEBXYLz0NHI/discussion

**Comment by k-takata** [comment]
あれ？ それだと初っ端のパッチと同じじゃないですか？
https://groups.google.com/d/msg/vim_dev/eEBXYLz0NHI/AVYKLYP7u1sJ

**Comment by mattn** [comment]
カレントディレクトリはスキップされてもいいかな、と思いました。
以前 libcall でセキュリティバグが発生した際に、カレントディレクトリから読み込ませない様にする仕組みが入ったのと同じ感じです。

**Comment by mattn** [comment]
あとで説明追記しておきます。

**Comment by k-takata** [comment]
そうしてしまうと、! や system() の動作と食い違いが出てきてまずい気がします。

**Comment by mattn** [comment]
あー。確かに。もいちど push しておきました。

**Comment by k-takata** [comment]
7.4.428
https://groups.google.com/d/topic/vim_dev/o1qvoysSodI/discussion
