### ISSUE TITLE
引数の変数名が重複していると内部エラーが出る

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#45]
https://gist.github.com/1242627
以下の手順で再現できます。

  $ git clone git://gist.github.com/1242627.git repo
  $ cd repo
  $ sh step.sh

**Comment by tyru** [comment]
辞書`a:`に突っ込む時存在確認をしてないのが原因ですね。
こんなパッチ作りましたが「エラーメッセージはどうする？」
というのとあと「エラー番号(E123みたいなの)はどの番号にすればいいんだろう」
という疑問がでてきました...

以下未完成パッチ
https://gist.github.com/1242679

**Comment by tyru** [comment]
あと本来これは関数を呼んだ時点ではなく`:function`で宣言した時点で検出すべきですが、
eval.cの`ex_function()`では,で区切られた変数を単純に配列にaddしてくだけだったので
重複した引数の検出のためだけにhashtab追加していいのかな...
となんとなく不安になったのですが、いいんでしょうか？

**Comment by koron** [comment]
画像だと見るのに面倒なので、可能な限りテキストに起こしてくれれば。ということで補足

> function! foobar(param, param)
> endfunction

といったように、引数に同じ名称を利用すると関数の定義時ではなく実行時にエラーとなる、ということですね。
しかもそのエラーが

> E685: Internal error: {関数名}

で、なんだかわかりにくい、と。

対応策は2つ。
- わかりやすいエラーとする: 「同じ名前の引数は使えないよ」
- 定義時(読み込み時)にエラーに落とす

**Comment by tyru** [comment]
すみません。
補足ありがとうございます。

**Comment by tyru** [comment]
しれっとコンパイルできないパッチ上げてしまった...直しました。

**Comment by tyru** [comment]
> 定義時(読み込み時)にエラーに落とす

こっちのパッチも[書いてみました](https://gist.github.com/1242833)。
以下がこのパッチで出力されるエラーメッセージです。
(:endfunctionのエラーはどうにかならないんだろうか...)

  /home/takuya/hoge/tes.vim の処理中にエラーが検出されました:
  行    6:
  E???: Duplicated argument variables: a
  行    7:
  E193: 関数の外に :endfunction がありました
  行    8:
  E117: 未知の関数です: <SNR>1_foo
  続けるにはENTERを押すかコマンドを入力してください

**Comment by tyru** [comment]
問題はどちらのパッチもエラー番号が`E???`なことですね...
これはどういう番号をつければいいんだろう...
単純に`使われてる中で一番大きい数 + 1`でいいんでしょうか？

列挙してみました。 https://gist.github.com/1242880
けっこう空きがありますが、`使われてる中で一番大きい数 + 1`は`E853`のようですがこれでいいのかどうか...

**Comment by tyru** [comment]
とりあえず`E853`にしてパッチ投げてリアクション見ることにしました。
https://groups.google.com/group/vim_dev/browse_thread/thread/c16f33ace69e79dc?hl=ja

**Comment by koron** [comment]
Nice work!

**Comment by mattn** [comment]
`feature request`外しました

**Comment by mattn** [comment]
パッチ見ましたが

```
for (n = 0; n < newargs.ga_len; n++)
{
    if (STRCMP(((char_u **)(newargs.ga_data))[n], arg) == 0)
      break;
}
if (n < newargs.ga_len)
{
  EMSG2(_(e_dupargvar), arg);
  goto erret;
}
```

でも良い様に見えますが、どうでしょ？（ちゃんと見てないよ）

**Comment by tyru** [comment]
パッチレビューありがとうございます！
ああそうか、関数の引数程度ならforで回しても問題ないですね。
LL脳なので`hashtab_T`でやってしまいました...

**Comment by tyru** [comment]
@mattnさんの言った通りになったw
https://groups.google.com/d/topic/vim_dev/QMb3ff-h0bE/discussion
