### ISSUE TITLE
除算で0で割ったときエラーが出ない

### ISSUE THREAD

**Issue by longicalycinus** [vim-jp/issues#452]
https://github.com/vim-jp/vital.vim/issues/99
にも書きましたが乗数が0の場合、エラーが出ないどころか
0以外の数値で無理矢理計算を進められます。

:echo 1 / 0  => 2147483647

**Comment by thinca** [comment]
仕様のようです。

`:help expr-/`

```
When dividing a Number by zero the result depends on the value:
          0 / 0  = -0x80000000  (like NaN for Float)
         >0 / 0  =  0x7fffffff  (like positive infinity)
         <0 / 0  = -0x7fffffff  (like negative infinity)
        (before Vim 7.2 it was always 0x7fffffff)
```

**Comment by longicalycinus** [comment]
ありがとうございます。
仕様という言葉を使えば何でも許されるのですね。
明らかにバグと思うのですが。
私はVim以外でエラーを出さない言語を見たことがありません。

それにしても、すぐに:helpのどこに書いてあるのか分かるのは
すごいですね。

**Comment by thinca** [comment]
> 明らかにバグと思うのですが。

:help に記述があるということは、意図した挙動であるということです。つまり仕様です。
Vim script は数学の演算を正確に行うことを目的としているわけではないので、そこのところを考慮してもらえればと思います。

**Comment by longicalycinus** [comment]
やっぱり気になったので、thincaさんがヒントをくれたおかげでeval.cを書き換えて
エラーを出すようにしました。

**Comment by mattn** [comment]
説得出来る理由があればvim-devに伝えるべきですね。
issueを閉じるのはそのあとで良いかも。

**Comment by Shougo** [comment]
> 私はVim以外でエラーを出さない言語を見たことがありません。

例外がない言語ではエラーが出ない言語もあるでしょう。言いたいことは分かりますが、エラーをどう考えるかは言語によります。

**Comment by Shougo** [comment]
> やっぱり気になったので、thincaさんがヒントをくれたおかげでeval.cを書き換えて
> エラーを出すようにしました。

パッチを書いたのなら、一度ここに出してチェックを受けたほうが良いと思いますよ。もちろん、vim_devに投稿せず自分のVimだけで完結するという方法もあるので、パッチを出さないという方向性もありです。

**Comment by koron** [comment]
パッチが公開されていない、賛同者がいないということで wontfix としています。

**Comment by mattn** [comment]
今の vim 的には 1/0 は INF なので仕様です。

**Comment by mattn** [comment]
ちなみに nodejs で 1/0 と入力すると例外ではなく Infinity と表示されるはずです。

**Comment by koron** [comment]
あ、仕様が変わったのかw
