### ISSUE TITLE
Vim 7.4.14b BETA で GUI タブが表示されない場合がある

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#454]
Vim 7.4 14b BETA を使用した場合に GUI タブが表示されないケースがあったので報告します。
#### 再現環境
- WindowsXP SP3
- Kaoriya 版 Vim 7.4.14b BETA

<br>
#### 再現手順
1. `gvim -u NONE -U NONE --noplugin` で gvim を起動
2. 以下の `hogehoge_test.vim` を `:source`する
3. `close` or `<C-w><C-q>` でタブページを消していく
4. ウィンドウの左までタブページを消していくと表示されなくなる

``` vim
" hogehoge_test.vim
" 適当にタブページを大量に開く
for i in range(15)
    tabnew hogehoge_test.vim
endfor
```

![gui](https://f.cloud.github.com/assets/214488/916237/895708ee-fe86-11e2-9820-8c58d4a35d2c.gif)

<br>
#### 備考

Vim 7.3.1314 では再現しませんでした。

**Comment by k-takata** [comment]
7.4a.034 の悪影響ですかね。どう直せばいいのやら。

**Comment by mattn** [comment]
TabCtrl_AdjustRect?

**Comment by mattn** [comment]
ちがうっぽい

**Comment by mattn** [comment]
http://recui.googlecode.com/svn/trunk/other/NotepadPlusPlus/PowerEditor/src/WinControls/TabBar/TabBar.cpp
なんかバグ踏んだ臭い。

**Comment by k-takata** [comment]
7.4a.034 で直そうとしていたちらつきは、タブを追加するときのみ発生していて、今回の問題はタブを削除するときに発生しているので、タブを追加するときのみ 7.4a.034 の順序で処理をして、それ以外は以前の順序にしておけば、とりあえずは回避できそう。
https://bitbucket.org/k_takata/vim-win32-mq/src/8e5a793a40b01ad650e577f182faa7ab5068e4fa/fix-tabline-update.patch
こんなんでいいのかｗ？

> なんかバグ踏んだ臭い。

どこを見ればいいのか分かりませんでした。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/XOc6_41avgE/discussion

**Comment by k-takata** [comment]
7.4b.019 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/Ran6AWpzzMk/discussion

**Comment by osyo-manga** [comment]
ありがとうございました:)
