### ISSUE TITLE
enc=utf-8で正しく動作しない処理 (Windows)

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#455]
#453 に関連して、enc=utf-8 のときに正しく動作しない処理がないか調べたところ、いくつか問題がありそうなものが見つかりました。
- ~~os_win32.c / fname_case()~~ (7.4.016)  
  ~~ファイルを開く際、ファイル名の大文字小文字を実際に存在するファイルに合わせる処理。ファイル名にマルチバイト文字が含まれると正しく動作しない。~~
- ~~os_win32.c / mch_get_user_name()~~  (7.4.123)  
  ~~ユーザー名にマルチバイト文字を使う場合はあまりないとは思いますが。~~
- ~~os_win32.c / mch_get_host_name()~~  (7.4.124)  
  ~~ホスト名にマルチバイト文字が使えるのかどうか分かりませんが。~~
- ~~os_win32.c / mch_nodetype()~~ (7.4.014, 7.4.015)  
  ~~NODE_NORMAL が返るだけなので、修正しなくとも影響なさそう？→デバイスファイルを含むパスをフルパスで指定したときに影響あり。~~
- ~~os_win32.c / mch_system_piped()~~ (7.4.125)  
  ~~メッセージループがANSI APIで処理されている。pPeekMessage, pDispatchMessage を使うべき？~~
- ~~os_mswin.c / mch_isFullName(), vim_stat()~~ (7.4.013)  
  ~~UTF-8 用のバッファサイズが不足。漢字などで約80文字を超えるファイル名が正しく扱えない。~~
- ~~os_mswin.c / mch_resolve_shortcut()~~ (7.4.012)  
  ~~正しく動作しない。VimL の resolve() にも影響。~~

os_mswin.c, gui_w48.c, gui_w32.c なども確認が必要と思われますが、未確認です。

**Comment by koron** [comment]
> ユーザー名にマルチバイト文字を使う場合はあまりないとは思いますが。

そう思うでしょ? 結構あるっぽいよ。

**Comment by cohama** [comment]
> ユーザー名にマルチバイト文字を使う場合はあまりないとは思いますが。

自分、Windows PC のユーザ名は普通に漢字にしています。

あと、印刷するときに文字化けするのもこの問題に含まれますか？

**Comment by k-takata** [comment]
> あと、印刷するときに文字化けするのもこの問題に含まれますか？

#408 にあるように、基本的には 7.3.1211 で直っているはずですが、`'printheader'` は自分で設定しておく必要があります。
7.3.1211 以降で直っていないようであれば、詳しい状況の報告をお願いします。

**Comment by mattn** [comment]
一旦報告して7.4までに直したい意思を表明しとくべきですかね。

On 8/10/13, cohama notifications@github.com wrote:

> > ユーザー名にマルチバイト文字を使う場合はあまりないとは思いますが。
> 
> 自分、Windows PC のユーザ名は普通に漢字にしています。
> 
> あと、印刷するときに文字化けするのもこの問題に含まれますか？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/455#issuecomment-22399993

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
一部パッチを作りました。が、どこで使われているのか（本当に直す必要があるのか）、よく分かっていません。

> - os_win32.c / mch_get_user_name()

https://bitbucket.org/k_takata/vim-win32-mq/src/28b4a84d59e219ccb601a457ea9f523e3a9ce39f/fix-utf8-username.patch
修正未確認。

> - os_win32.c / mch_get_host_name()

https://bitbucket.org/k_takata/vim-win32-mq/src/28b4a84d59e219ccb601a457ea9f523e3a9ce39f/fix-utf8-hostname.patch
`hostname()` がASCII文字でデグレを起こしていないことは確認。ホスト名にマルチバイト文字を使えるのかどうかは未確認。

> - os_win32.c / mch_system_piped()

https://bitbucket.org/k_takata/vim-win32-mq/src/28b4a84d59e219ccb601a457ea9f523e3a9ce39f/fix-utf8-msgloop.patch
修正未確認。

**Comment by k-takata** [comment]
直した方が良さそうなのは fname_case() ですが、意外と複雑でやる気が起きませんｗ

**Comment by cohama** [comment]
最新版にしたら印刷の文字化け直っていました。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/UsAv0LIIEug/xlZN1hiuAy8J

**Comment by k-takata** [comment]
todo 入りしました。

> Several Win32 functions are not using Unicode.
> Patches to fix this. (Ken Takata, 2013 Aug 9)

が、fname_case() の問題が残っているので、patches welcome として閉じずに残しておきたいと思います。

**Comment by koron** [comment]
> `printheader` は自分で設定しておく必要があります。

これVim側でなんとかして欲しいよね… いまちょうど体験したw

**Comment by k-takata** [comment]
> - os_win32.c / mch_nodetype()  
>   NODE_NORMAL が返るだけなので、修正しなくとも影響なさそう？

fileio.c / readfile() の中から呼んでるはずなのに、呼ばれないなと思ってよく見ると、Windows 関連の処理なのに `#ifdef UNIX` の中に入っていた！

**Comment by k-takata** [comment]
> - os_win32.c / fname_case()

パッチを作ってみました。
https://bitbucket.org/k_takata/vim-win32-mq/src/96100afa35da7d0f5c0ac51ebad436083bf701a3/fix-utf8-fname_case.patch

パッチを書いている途中に、`_MAX_PATH` の扱いで気になる点が見つかりました。Windowsでは、（特別な対応をしなければ）UTF-16LE で _MAX_PATH 文字までのパスが扱えるわけですが、それを UTF-8 に変換した場合は、最大で _MAX_PATH \* 3 バイトになる可能性があります。しかし、現状、`char_u` の固定長バッファは _MAX_PATH バイトになっている部分があるようです。
（なお、ANSI API を使った場合は、パスの最大長は _MAX_PATH バイトになります。）

**Comment by mattn** [comment]
++

**Comment by k-takata** [comment]
> Windows 関連の処理なのに `#ifdef UNIX` の中に入っていた！

パッチ5
https://bitbucket.org/k_takata/vim-win32-mq/src/5ac9bea8445125dddf03f6980bdb4f39ba1ce265/fix-device-check-on-Windows.patch
`con` や `nul` などを開こうとしたときに、デバイスファイルを開こうとしていると警告を出してくれるようになります。

> - os_win32.c / mch_nodetype()

パッチ6
https://bitbucket.org/k_takata/vim-win32-mq/src/54bcdfe31710bfc3019fdf848b7bff60b498deea/fix-utf8-nodetype.patch

パッチ5と6を当てると、`C:\ほげ\nul` というファイルを開こうとしたときに、デバイスファイルを開こうとしていると警告を出してくれるようになります。でも、`C:\ほげ\con` だと警告が出ないという中途半端さ。`CreateFile()` で `GENERIC_WRITE` を指定して開こうとしているからなのでしょう。

> `_MAX_PATH` の扱いで気になる点が見つかりました。

パッチ7
https://bitbucket.org/k_takata/vim-win32-mq/src/03c2c3d8b098e44e0cd5f5f9ac5839d74a845d42/fix-utf8-buffer-length.patch

さらに、os_mswin.c / mch_resolve_shortcut() が正しく動作しないことが判明しました。
パッチ8
https://bitbucket.org/k_takata/vim-win32-mq/src/864a9b9956e8a544eac9156db63a82e5d5a351e7/fix-utf8-mch_resolve_shortcut.patch

**Comment by k-takata** [comment]
パッチを一部更新。

パッチ7
https://bitbucket.org/k_takata/vim-win32-mq/src/98d42e4cde77d200ededbbd14e71f60f6705ff98/fix-utf8-buffer-length.patch
パッチ8
https://bitbucket.org/k_takata/vim-win32-mq/src/98d42e4cde77d200ededbbd14e71f60f6705ff98/fix-utf8-mch_resolve_shortcut.patch

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/UsAv0LIIEug/Ux4KcVC9dWsJ

**Comment by h-east** [comment]
:+1:

**Comment by k-takata** [comment]
> でも、`C:\ほげ\con` だと警告が出ないという中途半端さ。`CreateFile()` で `GENERIC_WRITE` を指定して開こうとしているからなのでしょう。

違っていました。gvimだと `*\con` を `CreateFile()` で開こうとすると `ERROR_FILE_NOT_FOUND` になっていました。
vimだと `CreateFile()` は成功し、意図通り、デバイスファイルであるとの警告が出ます。
`mch_nodetype()` の実装については、これ以上追求してもしょうがない気がするので、この辺にしておきます。

**Comment by k-takata** [comment]
コマンドラインで、カレントコードページで扱えない文字を指定すると、正しく扱えないことに気付きました。
例:

```
> vim ☀.txt
```

~~コマンドラインの解析は `:set enc=utf-8` をする前に行われるので、`vim ?.txt` として解釈されてしまいます。同じディレクトリに `a.txt` があったりするとそちらが開かれてしまいます。
直すのはかなり難しそうな予感。~~

**Comment by k-takata** [comment]
> コマンドラインで、カレントコードページで扱えない文字を指定すると、正しく扱えないことに気付きました。

すみません。勘違いだったようです。別の環境だとちゃんと動きました。

**Comment by k-takata** [comment]
> > `printheader` は自分で設定しておく必要があります。
> 
> これVim側でなんとかして欲しいよね… いまちょうど体験したw

とりあえずの対策であれば、香り屋版の
https://bitbucket.org/koron/vim-kaoriya/src/70bb01306babb1c195d67d54c9e41e023237bf69/kaoriya/vim/plugins/kaoriya/encode_japan.vim?at=default#cl-64
で `rtp` と一緒に `printheader` も変換しておけばいいんでしょうかね？
根本的な対策は #229 ということになるのでしょうが。

**Comment by mattn** [comment]
やりはじめたら収集つかなくなりそうで怖い > 変換

**Comment by k-takata** [comment]
パッチ8を更新。#if~#endif が正しくインデントされていませんでした。
https://bitbucket.org/k_takata/vim-win32-mq/src/c040acc974cc89478ec253c9daef56c09023218c/fix-utf8-mch_resolve_shortcut.patch

**Comment by k-takata** [comment]
いろいろ取り込まれました。

7.4.012
https://groups.google.com/d/topic/vim_dev/_wHrBxy3wgw/discussion
7.4.013
https://groups.google.com/d/topic/vim_dev/oIei7J3zUg8/discussion
7.4.014
https://groups.google.com/d/topic/vim_dev/sjHgQoyEd-U/discussion
7.4.015
https://groups.google.com/d/topic/vim_dev/oEUp0lK3ZuQ/discussion
7.4.016
https://groups.google.com/d/topic/vim_dev/0uIYdk6DzkQ/discussion

**Comment by k-takata** [comment]
> todo 入りしました。
> 
> > Several Win32 functions are not using Unicode.
> > Patches to fix this. (Ken Takata, 2013 Aug 9)
> 
> が、fname_case() の問題が残っているので、patches welcome として閉じずに残しておきたいと思います。

fname_case() の問題は既に直っているので閉じます。
まだ直っていないのは以下の3件です。
- os_win32.c / mch_get_user_name()
- os_win32.c / mch_get_host_name()
- os_win32.c / mch_system_piped()

**Comment by k-takata** [comment]
全て取り込まれました。

7.4.123
https://groups.google.com/d/topic/vim_dev/S97f4QMLBRk/discussion
7.4.124
https://groups.google.com/d/topic/vim_dev/xaEamQRW6l0/discussion
7.4.125
https://groups.google.com/d/topic/vim_dev/zxDYpWvXhn8/discussion
