### ISSUE TITLE
スペルチェックのポップアップメニューが日本語化されていない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#457]
https://github.com/vim-jp/issues/issues/382#issuecomment-17770950 より

> スペルチェック有効時に出るポップアップメニューが日本語化されていないことに気づきました。
> ![popup-spell](https://f.cloud.github.com/assets/840186/492406/22c6a518-baa6-11e2-9d39-359ba315c838.png)
> menu.vimの中で動的に生成しているようなので、簡単に対応できそうにはなさそうな気もしますが。

**Comment by k-takata** [comment]
翻訳のための仕組みが入ったようです。
https://github.com/vim/vim/commit/7c63fbc46e218cad266641a743a6c1353c2f00d4#diff-0bf1822437d77cb156948e808487340dR952
元スレッド: https://groups.google.com/d/topic/vim_dev/Dw-Y89DJgIs/discussion

**Comment by mattn** [comment]
こうなると gettext(x) が欲しくなりますね。

**Comment by k-takata** [comment]
それぞれの言語のメニューファイルで

```vim
let g:menutrans_spell_change_ARG_to = 'Change\ "%s"\ to'
let g:menutrans_spell_add_ARG_to_word_list = 'Add\ "%s"\ to\ Word\ List'
let g:menutrans_spell_ignore_ARG = 'Ignore\ "%s"'
```

を翻訳した値を設定しておけばいいのかな。

> こうなると gettext(x) が欲しくなりますね。

Vim scriptも翻訳用メッセージのソースに使うということでしょうか？

**Comment by mattn** [comment]
ですです。あ、でも xgettext と相性悪いすね。

2018年5月19日(土) 23:34 K.Takata <notifications@github.com>:
