### ISSUE TITLE
オートロード変数（型は辞書）の中身の関数を、変数未定義の状態でcallするとオートロードしない

### ISSUE THREAD

**Issue by LeafCage** [vim-jp/issues#460]
以下のファイルをautoload/foo.vimとして作成してください。

``` vim
let foo#bar = {}
function! foo#bar.baz()
  echo 'ok'
  return ''
endfunction
```

そして以下のスクリプトをsourceしてください。

``` vim
call g:foo#bar.baz()    "NG

let s:foo = g:foo#bar
call s:foo.baz()        "OK
unlet s:foo

call g:foo#bar.baz()    "foo#barが読み込まれてからはOK
```

すると、1行目で、`E121: 未定義の変数です: g:foo#bar`
というエラーが出ます。
すなわちオートロード変数を、はじめに`:call`に書くとエラーになるのです。
オートロード変数のくせにオートロードしにいってくれないのです。

`:let`の右辺としての利用は許可されます。また、autoload/foo.vimがsourceされたなら
`call g:foo#bar.baz()` は問題を生じなくなります。

ちなみに、autoload/foo.vimがsourceされていなくても、
`:echo`や`:let`ならば、呼ばれたときに自動でautoload/foo.vimを読みに行き、g:foo#bar.baz() は実行されます。
すなわち、

``` vim
:echo g:foo#bar.baz()
```

``` vim
:let g:foo#bar.baz()
```

これらはsourceされていなくても実行できます。

また、変数の引数としてg:foo#bar.baz()を与えた場合もオートロードされます。
すなわち、

``` vim
:call type(g:foo#bar.baz())
```

これもsourceされていなくても実行できます。

さらに、`:eval()`の中身として評価するときにもオートロードされます。
すなわち、

``` vim
:call eval('g:foo#bar.baz()')
```

これもsourceなしから実行できます。

sourceされていない状態で実行できないのは、知る限りでは`:call g:foo#bar.baz()`だけです。
私は、オートロード変数に詰められた辞書関数が、素の`:call`でも定義をsourceされていない状態から実行できるべきだと思います。

**Comment by ynkdir** [comment]
todo.txt に入ってます。
悩み中みたいです。

```
Using ":call foo#d.f()" doesn't autoload the "foo.vim" file.
That is, calling a dictionary function on an autoloaded dict.
Works OK for echo, just not for  ":call" and ":call call()". (Ted, 2011 Mar
17)
Patch by Christian Brabandt, 2013 Mar 23.
Not 100% sure this is the right solution.
```

**Comment by LeafCage** [comment]
そうでしたか。todoに入っているのでしたら、いったんcloseしてもよさそうですね。

**Comment by LeafCage** [comment]
閉じました
