### ISSUE TITLE
FileType イベントでpeditを開くと、閉じるときに落ちる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#464]
https://gist.github.com/niw/6364121 に詳細情報あり。

以下、再現方法の転載

---

```
$ cat >> ~/.vimrc
autocmd MyAutoCommands BufNewFile,BufRead *.hoge set ft=hoge
autocmd MyAutoCommands FileType hoge wincmd s | pedit /dev/null

$ vim /tmp/hoge.hoge
```

You will see an unexpected blank preview window. Then close the current window.

``` vim
:q
```

This will cause `Vim: Caught deadly signal SEGV`.

**Comment by koron** [comment]
私の環境ではこれを `~/.vimrc` の最後に追加した。

```
augroup MyAutoCommands
  au!
  autocmd BufNewFile,BufRead *.hoge set ft=hoge
  autocmd FileType hoge wincmd s | pedit /dev/null
augroup END
```

**Comment by koron** [comment]
私の環境だと落ちはしなかったけどウィンドウの分割がおかしくなった。
特に添付画像の赤文字で示した部分、文字が表示されない領域になってしまった…

![captured](https://f.cloud.github.com/assets/468368/1041470/960ccb20-0fd2-11e3-8c94-5af2edf86d34.png)

noequalalways とか関係有るだろうか?

**Comment by koron** [comment]
> You will see an unexpected blank preview window. 

だからここまでは報告通りか。

> Then close the current window.
> This will cause `Vim: Caught deadly signal SEGV`

とあるけど Windows では落ちなかった。

**Comment by koron** [comment]
> とあるけど Windows では落ちなかった。

```
set equalalways
```

してから :q したら落ちた。

**Comment by koron** [comment]
あ、一回落としたら、そのあとは set noequalalwasy でも落ちるようになった。

**Comment by ynkdir** [comment]
7.4.007 で直った気配が

**Comment by koron** [comment]
Thanks.  I'll try it.

**Comment by koron** [comment]
確認できました。ありがとうございます。

ftp://ftp.vim.org/pub/vim/patches/7.4/7.4.007

**Comment by k-takata** [comment]
ラベルは `xlose/invalid` よりも `xlose/fixed` (または `xlose/worksforme`) の方が良くないですか？
https://github.com/vim-jp/issues/wiki/Member

**Comment by koron** [comment]
任せます。

**Comment by k-takata** [comment]
fixed に変えておきました。
