### ISSUE TITLE
Windows でシンボリックリンクのディレクトリに :cd できない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#468]
Vim 7.4.16 Kaoriya版で確認。
`mklink /d` で作成したシンボリックリンクのディレクトリに対して `:cd` や `:lcd` で移動しようとすると、

```
E344: cdpathには "(:cdで指定したディレクトリ)" というファイルがありません
E472: コマンドが失敗しました
```

と言うエラーが出て移動できません。
シンボリックリンク内にあるディレクトリに対しては移動できます。
また、起動時にシンボリックリンクのディレクトリにいた場合は現在のディレクトリは問題なくシンボリックリンクのディレクトリになっています。

**Comment by thinca** [comment]
Linux ではシンボリックリンクのディレクトリはそもそも常に解決するようになっているので(#112 参照)、動作を合わせるとしたら Windows でも同様にすべき?

**Comment by k-takata** [comment]
VC10 だと、ディレクトリへのシンボリックリンクに対して vim_stat() がエラーを返すからですね。
#41 の vim_stat() に対するパッチを当てれば直るようです。

**Comment by k-takata** [comment]
ちなみに、VC の stat() の動作は以下のようになっています。(VC9は不明)
- VC8 以前  
  シンボリックリンクは全く考慮していない。stat() は、シンボリックリンクそのものの情報を返す。
- VC10  
  ファイルのシンボリックに対しては、リンク先ファイルの情報を返す。ディレクトリのシンボリックに対しては常にエラーが返る。
- VC11  
  ファイル・ディレクトリのシンボリックに対しては、共にリンク先ファイルの情報を返す。

X004_01-rmdir_support_symlinks.diff から、vim_stat() の修正だけを抜き出して、別パッチにした方が良いかもしれませんね。

**Comment by koron** [comment]
分離に賛成。

**Comment by k-takata** [comment]
パッチを2つに分割しました。

https://bitbucket.org/k_takata/vim-ktakata-mq/src/726ca2dc502ae5d7393053e945a5b52b03eb59a1/X004_01-rmdir_support_symlinks.diff
https://bitbucket.org/k_takata/vim-ktakata-mq/src/726ca2dc502ae5d7393053e945a5b52b03eb59a1/fix-vc10-vim_stat.patch

ついでに (w)stat_symlink_aware() を少し修正して、VC8 以前でも VC11 と同じ動作になるようにしました。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/7YcCsZEN69k/discussion

**Comment by Shougo** [comment]
すぐにパッチが投稿されていて素晴らしい。

**Comment by k-takata** [comment]
> ちなみに、VC の stat() の動作は以下のようになっています。(VC9は不明)

VC9 は、VC8 以前と同じ動作でした。

**Comment by k-takata** [comment]
todo.txt 入りしました。

> Patch to fix that VC10 does not stat() a symlink to a directory.
> (Ken Takata,, 2013 Sep 20)  Update Sep 21

**Comment by k-takata** [comment]
> Linux ではシンボリックリンクのディレクトリはそもそも常に解決するようになっているので(#112 参照)、動作を合わせるとしたら Windows でも同様にすべき?

クローズしてしまいましたが、これはどうすべきですかね。Windows だと、リンク先のディレクトリを知る手軽方法がない気がするので。一応、[リンク/ジャンクション作成ツール](http://homepage1.nifty.com/emk/symlink.html)で使っている方法でリンク先は分かりますが、変なプレフィックスが付いていたりします。

**Comment by k-takata** [comment]
7.4.039 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/bZL2kC0C44w/discussion

**Comment by k-takata** [comment]
このパッチが当たった状態で、ディレクトリに対するシンボリックリンクに対して getftype() を呼ぶと 'file' が返ってきてしまうことに気づきました。VC11, VC12でもバグっています。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/86a91f76fad5c064902a4336ce08df5880862296/fix-7.4.039-S_IFDIR.patch
MinGWのstat()もVC9以前と同様にsymlinkに対応していないので、コンパイラの種類・バージョン関係無しに同じ処理にしてしまった方が良さそう。

**Comment by k-takata** [comment]
> ディレクトリに対するシンボリックリンクに対して getftype() を呼ぶと 'file' が返ってきてしまうことに気づきました。VC11, VC12でもバグっています。

VC14 (VC2015) でようやく直ったようです。パッチを修正しなければ。

**Comment by k-takata** [comment]
7.4.1139で取り込まれました。
https://groups.google.com/d/topic/vim_dev/ih15eMPJJl8/discussion

**Comment by thinca** [comment]
:tada:
