### ISSUE TITLE
ctags のクローンを vim-jp 下に置くのはどうだろうか?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#473]
sourceforge のオリジナルはツラぽよ。
もう独自に発展させても良い気がす。

特に @h-east さんのご意見を聞きたす。

**Comment by Shougo** [comment]
確かに、オリジナルは2009年以降リリースが無いですからね。
SVNのtrunkも参照しましたが、2012年12月以降の変更がありません。

http://sourceforge.net/p/ctags/code/HEAD/tree/

forkしたほうが発展できる見込みがあるのなら、forkするのは手かと思います。

**Comment by h-east** [comment]
goodです。とりあえずやってみましょう。
でも、各対応プログラム言語の最新規格(仕様)に対応するのは面倒そう。
簡易対応対象プログラム言語(内部で正規表現でテキトーに対応してるもの)はそのまま(正規表現だけの対応)でいいのなら楽かも。
問題は、マジ対応(自前で構文解析)してるC, C++, java, C# だっけ？ の方か。。

個人的には
・マルチバイト完全対応。少なくともutf-8
が必要な気がす。
どこかのforkで対応してないですかね？

**Comment by Shougo** [comment]
> でも、各対応プログラム言語の最新規格(仕様)に対応するのは面倒そう。

syntaxファイルでも問題は同じですからね……。

> 問題は、マジ対応(自前で構文解析)してるC, C++, java, C# だっけ？ の方か。。

C++でいうと、C++11に対応するのは大変そうですね。個人的にはD言語への対応が欲しいですし、@mattnさんならGoへの対応が欲しいといいそう。

https://github.com/lyosha/ctags-go

Go対応しているのはfork版があるみたいです。D言語は昔にパッチがあったかな。

**Comment by osyo-manga** [comment]
関係あるかどうかわかりませんが、LLVM/Clang で実装された ctags がありますね。
使ったことがないのでどの程度使えるのか未知数ですが…。

https://github.com/drothlis/clang-ctags

**Comment by mattn** [comment]
LLVM/Clang で実装された、のではなく、clang のパース機能を使って tags を生成する python スクリプトといったところ？

**Comment by h-east** [comment]
@Shougo @osyo-manga @mattn 情報thanksです。

コンパイラやスクリプト言語のパースを使って本気解析してtags作るのはありだと思うし、コンパイラやスクリプト言語は標準でそういう機能を持って欲しい。(もうそういう流れになりつつある？)

ctagsの位置付けとしては...
- 自前で構文解析するので完璧じゃないけどある程度いい感じにtags作成するよ。だからコンパイラ等の環境がなくってもソースコード解析気軽にできまーす。

なのかなと思ってます。
ということで`完璧未満のいい感じ`をキープすればいいんちゃいますかね。
人によって`いい感じ`の定義が大分違うと思いますがｗ

**Comment by DeaR** [comment]
D言語パッチは
http://www.prowiki.org/wiki4d/wiki.cgi?ReferenceForTools/ExuberantCtags
にあったりはします

しかしながら問題は
- D言語自体のverに追いついて無さそう(な気がする)
- License等々の連絡つけにくそう

**Comment by Shougo** [comment]
> D言語自体のverに追いついて無さそう(な気がする)
> License等々の連絡つけにくそう

はい。そういう問題があると思います。昔見た感じだとC++？かなんかのパーサをベースに簡易的に実装した程度だったので
別にこれをfork版にマージする必要はなく、参考にする程度でよいかと思います。

> コンパイラやスクリプト言語のパースを使って本気解析してtags作るのはありだと思うし、コンパイラやスクリプト言語は標準でそういう機能を持って欲しい。(もうそういう流れになりつつある？)

clangが持っている機能（補完、定義元ジャンプ）はおそらく内部でctags的なことをしているのでそれはトレンドだと思います。Goにも似たようなツールがあるようですし。言語ごとで独自ツールを作成する流れにはなってきていますね。

> ということで完璧未満のいい感じをキープすればいいんちゃいますかね。
> 人によっていい感じの定義が大分違うと思いますがｗ

分かります。汎用性とメンテナンス性を重視するとそうなるかと。
ただ、要望としてはいろんな物が来ると思いますので、それらをどう取捨選択するかが今後の課題となりそうですね。

> 自前で構文解析するので完璧じゃないけどある程度いい感じにtags作成するよ。だからコンパイラ等の環境がなくってもソースコード解析気軽にできまーす。

そういう意味では、C++, Javaとかのctags実装は頑張り過ぎなんですが、そうでもしないと解析できないんでしょうかね。

**Comment by h-east** [comment]
@DeaR 情報Thanks.

---

@Shougo 

> C++？かなんかのパーサをベースに簡易的に実装した程度だったので

DeaRさんが教えてくれたところのpatch見ましたが内部の構文解析部分にがっつり手を加えています。すごいです。
簡易的には見えなかったよー。

> そうでもしないと解析できないんでしょうかね。

ある程度はまともにパースしないと無理だと思います。
余談ですが、C/C++の場合はプリプロセッサ(#if, #ifdef)があるので余計に面倒くさい。
ctagsは#if 0だけを特別視してあとは全部「真」として処理してます。

---

プログラム言語のEBNFとどれをタグ出力して欲しいかの指定を食わせると自前で取り込んで自己進化するプログラム下さい！

**Comment by Shougo** [comment]
> DeaRさんが教えてくれたところのpatch見ましたが内部の構文解析部分にがっつり手を加えています。すごいです。
> 簡易的には見えなかったよー。

そうだったのですか。私も昔読んだだけなので曖昧で、ctagsの内部構造もよくわかっていないので、勘違いしていたようです。すみません。だとすると、どうにかコンタクトを取ってパッチを取り込めると良いかもしれません。

> ある程度はまともにパースしないと無理だと思います。
> 余談ですが、C/C++の場合はプリプロセッサ(#if, #ifdef)があるので余計に面倒くさい。
> ctagsは#if 0だけを特別視してあとは全部「真」として処理してます。

そうですね。ほとんどコンパイラみたいなことしないとダメですもんね。

> プログラム言語のEBNFとどれをタグ出力して欲しいかの指定を食わせると自前で取り込んで自己進化するプログラム下さい！

私も欲しいです。Boost.Spiritあたりがそれに近いんですかね？

**Comment by Shougo** [comment]
D言語のパッチに関しては、オリジナルのパッチ製作者であるるびきちさんにはコンタクトが取れそうな感じはします。
その後のパッチはコンタクトを取るのは大変でしょうね……。

**Comment by DeaR** [comment]
> > DeaRさんが教えてくれたところのpatch見ましたが内部の構文解析部分にがっつり手を加えています。すごいです。
> > 簡易的には見えなかったよー。
> 
> そうだったのですか。私も昔読んだだけなので曖昧で、ctagsの内部構造もよくわかっていないので、勘違いしていたようです。すみません。だとすると、どうにかコンタクトを取ってパッチを取り込めると良いかもしれません。
- 予約語の追加
- D特有のkindを追加
- C/C++/C#/VeraのC系言語用パーサーにDの判定を追加

パッチを分類分けすると少ないですが同じように言語追加を自作する気は起きないです。凄いです。

また、5.6と5.8のパッチを比べるとDのVerUpで追加された予約語が増えてるくらいで根本は変わってないですね。
結局コンタクトを取りたい事には変わりませんが…

**Comment by heavenshell** [comment]
Objective-C は @splhack さんが手を加えられてたはず…。
https://github.com/splhack/ctags-objc-ja
MacVim Kaoriya 版に組み込まれていたと思います。

**Comment by Shougo** [comment]
それはうまいこと統合しておきたいですね。

**Comment by h-east** [comment]
@heavenshell 実は本家のリポジトリにもObjective-C対応のコミットはされているんだけど、リリースされていないのであります(苦笑)

**Comment by Shougo** [comment]
それは……。Objective-Cプログラマは現在多いようなので、こっちでforkしたバージョンで対応できるなら喜ばれそうですね。

**Comment by koron** [comment]
ちょっと方向性について決めてしまいましょう。私は以下のように考えていますがいかがでしょうか?
1.  ctags の fork を vim-jp でメンテする
2.  fork した版は最新の言語をガンガンフォローアップしていく
3.  設定ファイルとか書かなくても多くの言語に対応できるようにプリセットする

**Comment by koron** [comment]
この最低限の3つに異論がある人は意見をお願いします。

**Comment by Shougo** [comment]
異論ありません。ただ、このforkしたバージョンが完成したら、vim_devでも宣伝するのかは気になっています。

**Comment by h-east** [comment]
@koron 
1 賛成
2 私は必要最低限の対応で済ませたい。
3 私はある程度メジャーになった言語を追加する感じでいいかなと考えている。

こんにちは。ラガード東です。

**Comment by koron** [comment]
> ある程度メジャーになった

これの客観的な指標、なにか考えられます?
主観でやるならグループで管理する以上、早晩無制限になりますよ。

**Comment by koron** [comment]
あ、私の「最低限の方針」は技術的な実現可能性は度外視してるね。申し訳ない。

**Comment by h-east** [comment]
> これの客観的な指標、なにか考えられます?

ノープランでした。
Githubの統計のTop 30 プログラム言語に入ったら...とかどうです？

**Comment by koron** [comment]
緩くするならパッチや設定とテストが提供されたら、というのでも良いかも。

**Comment by Shougo** [comment]
> これの客観的な指標、なにか考えられます?
> 主観でやるならグループで管理する以上、早晩無制限になりますよ。

需要があるかどうか、というところですね。少なくとも複数人が欲しい、と思う必要があります。

**Comment by koron** [comment]
反対って人がいないので作りました。 https://github.com/vim-jp/ctags

以後は向こうで相談ってことで。

**Comment by h-east** [comment]
@koron ++

**Comment by crazymaster** [comment]
これ、新しい言語に対応するときに参考にできそう
https://github.com/majutsushi/tagbar/wiki

**Comment by Shougo** [comment]
いいですね。確か私もVim scriptの関数名に対応させるためにプラグイン側でctagsに引数を渡して対応してたりします。
できればそれも取り込んでもらおうかな。

**Comment by h-east** [comment]
ctagsの事はctags/issuesで議論しましょ。必要ならissue立てちゃってください。
https://github.com/vim-jp/ctags/issues

よろしくお願いします。

**Comment by koron** [comment]
:+1:

**Comment by Shougo** [comment]
> ctagsの事はctags/issuesで議論しましょ。必要ならissue立てちゃってください。

了解です。
