### ISSUE TITLE
'equalalways'オプションがonなのにウィンドウ分割時にウィンドウサイズが均等にならない事がある

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#474]
バグかどうか微妙なところだけど登録しとく。

GVim 7.4.16 (Win64 +kaoriya) on Win7 64

```
$ gvim -N -u NONE -U NONE -i NONE --noplugin
```

手順

```
<C-W>s
<C-W>1_
<C-W>p
<C-W>s                  ←NG!? 均等じゃない！
<C-W>s                  ←均等
```

'equalalways'オプションのhelpの最後の2行に該当してそう(内部的に)

```
    新規ウィンドウ作成時にウィンドウサイズが指定された場合、ウィンドウサイ
    ズは等しくならない(これは複雑だが、将来は実装されるかもしれない)。
```

**Comment by koron** [comment]
`noequalalways` 運用なのでパス!

**Comment by Shougo** [comment]
ウインドウ分割はプラグイン側で対応するときも苦労させられるので、実装が難しいとわかっている以上、対応は非常に難しいのではないでしょうか……。

**Comment by ynkdir** [comment]
意図的みたいです。

patch 7.1.068
https://groups.google.com/d/topic/vim_dev/aVi1xE4Hr7E/discussion

**Comment by ynkdir** [comment]
`:split` のバグ修正のつもりで直したので `:split` のヘルプの方に書いたらしいです。

**Comment by h-east** [comment]
@ynkdir 情報ありがとうございます！
リンク先を粗く読んだけど理解出来なかった。汗。
あとでも一回読みます。

**Comment by h-east** [comment]
仕様です。閉じます。
