### ISSUE TITLE
日本語をスペルチェックから除外する

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#476]
`:set spell` でスペルチェックを行うと、日本語が間違いとして検出されてしまいます。
todo.txt にも以下の記載がありますが、これを何とかしたいです。

> Have an option for spell checking to not mark any Chinese, Japanese or other
> double-width characters as error.  Or perhaps all characters above 256.
> (Bill Sun)  Helps a lot for mixed Asian and latin text.

---

> -   have some way not to give spelling errors for a range of characters.
>   E.g. for Chinese and other languages with specific characters for which we
>   don't have a spell file.  Useful when there is also text in other
>   languages in the file.

とりあえずオプション化せず、東アジアの文字をスペルチェックから除外するだけのパッチ。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/f77ba41c22c8f1f132c6a75936db3d85c72f4c0e/exclude-east-asian-chars-from-spell-checking.patch

**Comment by Shougo** [comment]
はい。私はオプション追加に反対なので、それで良いと思います。

**Comment by mattn** [comment]
これは取り入れられそうなので早速送った方がよさそう。

**Comment by alpaca-tc** [comment]
+1

**Comment by k-takata** [comment]
Warningが出ていたので、直して投げました。
https://groups.google.com/d/topic/vim_dev/svbOqepFBFE/discussion

**Comment by k-takata** [comment]
Hmm, これはオプションにすべきという流れか。

**Comment by k-takata** [comment]
`'spelllang'` に "nocjk" を追加すると、CJK の文字をスペルチェックから除外するようにしてみました。
https://groups.google.com/d/msg/vim_dev/svbOqepFBFE/3JGfeFJy0jgJ

**Comment by k-takata** [comment]
"nocjk" ではなく "cjk" にすべきだと言われたので修正しました。
https://groups.google.com/d/msg/vim_dev/svbOqepFBFE/HhNqpO6H1zwJ

**Comment by k-takata** [comment]
todo入りしました。

> ```
> -   Have an option for spell checking to not mark any Chinese, Japanese or
>     other double-width characters (or CJK characters) as error.
>     Helps a lot for mixed Asian and latin text.
>     More general: Have some way not to give spelling errors for a range of
>     characters.
> Patch to add "cjk" to 'spelllang'. (Ken Takata, 2013 Oct 8, second one)
> ```

**Comment by k-takata** [comment]
課題はこれですね。

> More general: Have some way not to give spelling errors for a range of characters.

**Comment by mattn** [comment]
便利なので早く入ってほしい

**Comment by k-takata** [comment]
便利なので早く入ってほしい（自画自賛）

**Comment by Shougo** [comment]
Vim 7.4.88でマージされたようです。

https://groups.google.com/forum/?hl=ja&fromgroups#!topic/vim_dev/z6D1x9jKSgg

**Comment by mattn** [comment]
やったー

**Comment by koron** [comment]
:+1:

**Comment by k-takata** [comment]
Vim 7.4.092で追加修正です。FEAT_MBYTEがoffの場合に不備がありましたorz
https://groups.google.com/d/topic/vim_dev/5Ee4Iw4QU_s/discussion

**Comment by k-takata** [comment]
todo.txtが更新されて、

> More general: Have some way not to give spelling errors for a range of characters.

も含めて削除されました。ま、いっか。
