### ISSUE TITLE
strikethroughパッチを改良する

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#478]
Christian Brabandt 氏による [strikethrough パッチ](https://groups.google.com/d/topic/vim_dev/yUyvmKIG8-Q/discussion)というものがあり、これを使うと、打ち消し線を表示できるようになります。

> I am a Unix gui and can't say for sure the code for Windows
> and Mac is actually correct and works, though.

とのことですが、Windows でも試してみたところ、問題なく動作しているようでした。

```
> gvim -N -u NONE -U NONE foo.html
:syn enable
:setf html
:syn region htmlStrike start="<del\>" end="</del>"me=e-6 contains=@htmlTop
:hi def htmlStrike term=strikethrough cterm=strikethrough gui=strikethrough
i<del>foo</del>
```

次に気になるのがこれ。

> Secondly, I am unsure about the changes to term.c and term.h
> I don't know, if these changes are actually needed, so I simply took the
> undercurl code as an example and changed it so it would fit for
> strikethrough.

term.c, term.h については私も全く分かっていませんが、undercurl と同じようにするのであれば `t_Cs`, `t_Ce` に相当するオプションの追加が必要ではないかと思います。ただ、何という名前にすべきか分かりません。

最後に、`highlight` オプションにも strikethrough モードの追加が必要ではないかと思います。とりあえずフラグ名を `t` としました。

ということで、作りかけの追加パッチです。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/b4efa6cac61890ed0cb80bbb0c07f8cf988d9b9d/update-strikethrough.patch

**Comment by h-east** [comment]
Nice aggressive! 素晴しす！

**Comment by saitoha** [comment]
現在手に入る端末でも、ECMA-48/ISO-6429標準で定義されている打ち消し線を実装しているものがいくつかありますので、端末用に t_?? 形式のオプションを定義してやる意義は十分にあると思います。

??の部分はtermcapのcap名が入るようですので
X/Open cursesやman terminfoで名前を調べてみようと試みましたが、
どうやら打ち消し線に相当するアトリビュートは無いようでした。
http://pubs.opengroup.org/onlinepubs/9693989999/toc.pdf
https://groups.google.com/forum/#!topic/comp.terminals/KWn-OGUzjd4

したがって、既存のcap名と衝突しないような独自の名前を選ぶとして、
t_SS / t_SEとするのが適当ではないかと考えています。

```
    let &t_SS="\e[9m"
    let &t_SE="\e[29m"
```

としてやれば、

RLogin( http://nanno.dip.jp/softlib/man/rlogin/ )や
pangoterm( https://launchpad.net/pangoterm/ )等の端末で、
打ち消し線が出るようになると思います。

**Comment by saitoha** [comment]
パッチを見たところ、option.cの方もいじってt_??を追加した方がよいと思います。

**Comment by k-takata** [comment]
> したがって、既存のcap名と衝突しないような独自の名前を選ぶとして、
> t_SS / t_SEとするのが適当ではないかと考えています。

undercurl を参考に、t_Ts, t_Te にでもしようかと考えていましたが、どうしようかな…。

option.c の修正は完全に見落としていました。
undercurl のコードを参考にしていたのですが、t_Cs / t_Ce がヘルプには載っているにも関わらず、option.c の修正が抜けています。

打ち消し線に対応する端末はあるが、termcap では対応する cap が無いということなので、term.c の set_termname() の修正は元に戻した方が良さそうですね。（undercurl も同様？）

**Comment by saitoha** [comment]
一応screenとtmuxの独自拡張の方も見てみましたが、t_Ts, t_Teでも衝突は無いようです。

> 打ち消し線に対応する端末はあるが、termcap では対応する cap が無いということなので、term.c の set_termname() の修正は元に戻した方が良さそうですね。（undercurl も同様？）

 set_termname() の修正はユーザがtermcapをいじることを考えて、残した方がいいんじゃないかと思います。

**Comment by k-takata** [comment]
> 一応screenとtmuxの独自拡張の方も見てみましたが、t_Ts, t_Teでも衝突は無いようです。

確認ありがとうございます。

t_Ts, t_Te な版。highlight オプションの strikethrough 用フラグ名は t。
(t_SS, t_SE にするなら、highlight オプションのフラグ名は S ですかね。)
option.c を修正し、strikethrough とあわせて undercurl の t_Cs, t_Ce も追加。
(undercurl が使える端末なんてあるんでしょうか。)
https://bitbucket.org/k_takata/vim-ktakata-mq/src/580abbf0fd160eb92e4f185b3cad6e20181c108f/update-strikethrough.patch

**Comment by saitoha** [comment]
当ててみました。これを足せば端末で動くと思います。

``` diff
diff -r 92c9748e0ccb src/screen.c
--- a/src/screen.c  Sun Oct 06 17:46:56 2013 +0200
+++ b/src/screen.c  Sat Oct 12 00:46:24 2013 +0900
@@ -225,7 +225,7 @@
     else
 #endif
    /* Use attributes that is very unlikely to appear in text. */
-   screen_attr = HL_BOLD | HL_UNDERLINE | HL_INVERSE;
+   screen_attr = HL_BOLD | HL_UNDERLINE | HL_INVERSE | HL_STRIKETHROUGH;
 }

 /*
@@ -7523,6 +7523,9 @@
        out_str(T_CZH);
        if ((attr & HL_INVERSE) && T_MR != NULL)    /* inverse (reverse) */
        out_str(T_MR);
+       if ((attr & HL_STRIKETHROUGH) && T_STS != NULL)
+                          /* strikethrough */
+       out_str(T_STS);

        /*
         * Output the color or start string after bold etc., in case the
@@ -7626,6 +7629,13 @@
        else
            out_str(T_CZR);
        }
+       if (screen_attr & HL_STRIKETHROUGH)
+       {
+       if (STRCMP(T_STE, T_ME) == 0)
+           do_ME = TRUE;
+       else
+           out_str(T_STE);
+       }
        if (do_ME || (screen_attr & (HL_BOLD | HL_INVERSE)))
        out_str(T_ME);


```

**Comment by saitoha** [comment]
あと

> +#define HL_ALL                 0x4f

を

> +#define HL_ALL                 0x7f

に変えた方がいいと思います。

**Comment by saitoha** [comment]
とり急ぎ端末側でもアトリビュートを実装して動作確認しました。

![2013-10-12 0 39 29](https://f.cloud.github.com/assets/1162739/1315767/646f6c36-328b-11e3-82d8-da5bbf2b6c1d.png)

**Comment by k-takata** [comment]
マージしました。念のため確認をお願いします。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/9e0053bbcd95b89b0673a57af143c88118f2a2ea/update-strikethrough.patch

**Comment by saitoha** [comment]
確認しました。動いてます。
あとドキュメントのterm.txtで気になったんですが、
t_Ce / t_Cs は 「Added by Vim」の項にもってきちゃっていいんじゃないでしょうか
標準のcapabilityではないし、実際の端末で見たこともないですし。

**Comment by k-takata** [comment]
> option.c を修正し、strikethrough とあわせて undercurl の t_Cs, t_Ce も追加。

やはり t_Cs, t_Ce を追加するのはやめることにしました。そこだけ追加しても端末でundercurlが使えるわけではないので。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/afa7600d9d7135ed0115f7bb1c8e456771b223cd/update-strikethrough.patch

**Comment by k-takata** [comment]
> t_Ce / t_Cs は 「Added by Vim」の項にもってきちゃっていいんじゃないでしょうか

移動しました。 が、t_Te, t_Ts も移動した方が良さそうと思ったり思わなかったり…。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/44d856ae2dc81b5982bb63d52a45026371e0239a/update-strikethrough.patch

**Comment by k-takata** [comment]
t_Te, t_Ts も移動して、元のパッチとマージした上で投げました。
https://groups.google.com/d/msg/vim_dev/yUyvmKIG8-Q/Fe-TQzal_EMJ
何かあれば補足をお願いします。

**Comment by k-takata** [comment]
todo.txtが更新されました。

>  Patch to support strikethrough next to bold and italic. (Christian Brabandt,
> 2013 Jul 30)  Update from Ken Takata, 2013 Oct 12.

**Comment by saitoha** [comment]
[xterm patch#305](http://invisible-island.net/xterm/xterm.log-contents.html#xterm_305)でstrikethrough(crossed-out)が入ったので、今後追従する端末は増えると思います。
このパッチが問題無く動作しています。

![2014-06-04 0 22 58](https://cloud.githubusercontent.com/assets/1162739/3162298/d08496ec-eb33-11e3-9494-900e8b0fc937.png)

**Comment by k-takata** [comment]
vim_dev にも報告しておくとよいのではないでしょうか。

**Comment by k-takata** [comment]
minttyでも打ち消し線が使えることが確認できました。

**Comment by k-takata** [comment]
一方、RLoginでは使えませんでした。

**Comment by saitoha** [comment]
>    一方、RLoginでは使えませんでした。

あとでみてみます。

**Comment by k-takata** [comment]
8.0.1038
https://groups.google.com/d/topic/vim_dev/ldWIhkf6RiA/discussion
