### ISSUE TITLE
autocmd.txtのautocmd一覧にTextChangedがない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#481]
日本語helpの方に報告しようと思いましたが、まず原文に存在しないためこちらに報告します。

`:help autocommand-events` で確認できるautocmdの一覧に最近追加されたと思われるTextChangedが存在しません。他のautocmdは一覧にあるため、おそらく追加し忘れているのだと思います。ちなみに、`:help TextChanged`自体は存在します。

Vim 7.4.66で確認。

**Comment by k-takata** [comment]
TextChangedが追加されたのは7.3.867、autocmd.txtが更新されたのはその少し後のruntimeファイルの更新時で、確かに一覧は更新されてないですね。
（ところで、ドキュメントがパッチと一緒に更新される場合と、runtimeファイルとして更新される場合があるのは何なんだろう。）

**Comment by Shougo** [comment]
> （ところで、ドキュメントがパッチと一緒に更新される場合と、runtimeファイルとして更新される場合があるのは何なんだろう。）

おそらく、パッチ製作者がドキュメントを変更している場合と、変更していない場合があるのだと思います。

**Comment by ynkdir** [comment]
報告しました
https://groups.google.com/d/msg/vim_dev/fxHdlW1BHTw/mAeNuvtpMUkJ

**Comment by Shougo** [comment]
ありがとうございます

**Comment by k-takata** [comment]
7.4.125直後のコミットで取り込まれました。
http://code.google.com/p/vim/source/detail?r=7818ca6de3d07439571bc1fe788a3efff6979531

**Comment by Shougo** [comment]
ありがとうございました
