### ISSUE TITLE
行末が揃ってないバッファで矩形選択で$Aして挿入すると余計な文字が挿入される

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#482]
報告元 https://twitter.com/ATA911/status/402424739601215488

7.4.92 (+kaoriyaパッチ) で確認。
生Vimで発生するかは試してないので分からない。
# 今の +kaoriya パッチが以下の様な悪さをするとは考えにくいが…

テキストが以下のような時、カーソルが `2` にあるとする。

```
123
4567
```

`C-V` で矩形選択モードに入り `j$A` として行末挿入モードに入る。
この時、選択されているテキストは

```
23
567
```

となる。ここまでは問題ない。

ここで `ab` の2文字を挿入 `<ESC>` するとテキストは以下の様な状態になった。

```
123ab
45623ab7
```

2行目に挿入された`23`は明らかにユーザが望んでない編集操作。

なお `ab` ではなく `a` の1文字だけを挿入した場合

```
123a
456a7
```

となる。2行目の `a` の挿入位置がこれで良いかは判断に迷う。要ドキュメント確認。
ただ余計な文字は挿入されないので、本現象のトリガーが
挿入文字が選択範囲の行末を超えるか否か
なのではないかと推測はできる。

**Comment by thinca** [comment]
7.4.83 では再現せず、7.4.94 に上げたところ再現しました。この間で入ったエンバグっぽいですね。

**Comment by thinca** [comment]
```
updated for version 7.4.085
Problem:    When inserting text in Visual block mode and moving the cursor the
            wrong text gets repeated in other lines.
Solution:   Use the '[ mark to find the start of the actually inserted text.
            (Christian Brabandt)
```

これがすごく怪しいですね。

**Comment by koron** [comment]
ああ、ほんまや。

テストでひっかかってないのも気になりますなぁ。

**Comment by h-east** [comment]
patch送った。
ビジュアルモードの選択で '$' が使われた場合は patch 7.4.085 の処理をスルーするようにした。
https://groups.google.com/d/msg/vim_dev/r9R9x_20DF4/b6_rZewVLIIJ

後はよしなにしてくれるでしょう。

**Comment by mattn** [comment]
h-east++

**Comment by k-takata** [comment]
正しい結果は、

```
123ab
4567ab
```

です。(`:help v_b_A` 参照)

> patch 7.4.085 の処理をスルー

スルーさせるべきブロックが間違っているようです。修正パッチ送付済み。
https://groups.google.com/d/msg/vim_dev/r9R9x_20DF4/Ejm_s5K6RvkJ

**Comment by h-east** [comment]
h-east--
k-takata++

@k-takata フォローありがとうございます。

**Comment by koron** [comment]
thank you all!

ところでこれって自動テスト作れますかね?

**Comment by h-east** [comment]
お昼に書きます。

**Comment by koron** [comment]
@h-east :+1: Thank you very **macho**!

**Comment by h-east** [comment]
テスト追加patchをvim_devへ投稿DONE. マッチョ！

**Comment by koron** [comment]
@h-east ありがとまっちょ!

**Comment by k-takata** [comment]
7.4.099
https://groups.google.com/d/msg/vim_dev/6DucMvnHDM0/R1hsWr2W0SEJ

**Comment by h-east** [comment]
お疲れ様でした> 各位
k-takataさんと初めての連名だ :cat2:
