### ISSUE TITLE
zG で作成された一時ファイルが終了時に削除されない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#483]
スペルチェックを使い、[zG](http://vim-jp.org/vimdoc-ja/spell.html#zG) で、単語を[内部単語リスト](http://vim-jp.org/vimdoc-ja/spell.html#internal-wordlist)に追加すると、WindowsではVimを終了しても一時ファイルが削除されず、残ったままになってしまいます。

Linux等では、`/tmp/(somedir)/(num){,(enc).spl}` というファイルが作成されますが、Vim終了時には`memline.c` の `ml_close_all()` で `/tmp/(somedir)/` ディレクトリごと削除されます。
一方Windowsでは、TEMPディレクトリの直下に `VIs(hex).tmp{,(enc).spl}` というファイルが作成されて、それがそのまま残ってしまいます。

一時ファイルの作成は、`spell.c` の `spell_add_word()` で行われています。`spell_free_all()` には一時ファイルを削除する処理がありますが、Vimの終了時には呼ばれないようです。(`EXITFREE` を define していない場合)

修正案としては、`spell_free_all()` の一時ファイルの削除処理を関数化し、`ml_close_all()` で呼ぶなど？

7.4.094 にて確認。

**Comment by k-takata** [comment]
パッチ
https://bitbucket.org/k_takata/vim-ktakata-mq/src/0767096c68f0ab5e02819ed0ea0f8e7ee94d0819/spell-delete-wordlist.patch
(diffのアルゴリズムの問題なのか、何だか見にくい差分になってしまっていますが…)

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/8Ew5HbF-8lM/discussion

**Comment by k-takata** [comment]
todo入りしました。

> Patch to fix that "zG" leaves temp files around. (Ken Takata, 2013 Nov 22)

**Comment by k-takata** [comment]
7.4.108で取り込まれました。
https://groups.google.com/d/topic/vim_dev/VS3d4oQfRZQ/discussion

**Comment by mattn** [comment]
GJ
