### ISSUE TITLE
GUIタブページのD&Dによる並び変え機能追加の提案

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#484]
K.Takataさんにこちらで相談してみてはどうか
と助言をいただき、初投稿させていただきます。

提案する追加機能は以下の2点
1. D&Dでのタブの並び替え
2. マウスミドルクリックでタブクローズ

叩き台として以下のパッチを作ってみました。
https://gist.github.com/nocd5/7565874

**Comment by Shougo** [comment]
この機能ですが、Windowsだけ対応だとなんだかもったいないですね。
どうせ実装するなら、他のGUI版Vimでも機能を使えるようにしたいところです。

**Comment by nocd5** [comment]
やはり、全GUIで対応が望ましいですよね。
全GUIでとなると、まずは挙動の仕様決めが先ですね。

K.TakataさんがLinuxでは出来るようなことを呟いてましたが、
gtk側の機能でしょうか？後ほど確認してみたいと思います。

**Comment by koron** [comment]
内容は :+1: です。

コーディングスタイルを、 twitter で k-takata さんもつぶやいていましたが、Vimのスタイルにキッチリ合わせるべきです。

**Comment by k-takata** [comment]
ごめんなさい。Linuxのgvimでできるというのは勘違いだったかもしれません。
ただ、CUI版であればD&Dできます。また、GUI版(Win/Linux)でも`:set guioptions-=e`とすれば、テキスト表示のタブになり、D&Dできます。
なので、それをWindows GUI版でも使えるようにしたという点を強調すれば採用される可能性は高いと思います。

CUI版だと、ミドルクリックで閉じるようにはなっていないので、ミドルクリックは別パッチにした方が良いかもしれません。

**Comment by k-takata** [comment]
あと、ウィンドウプロシージャ (MyTabControlProc) を追加していますが、既に tabline_wndproc があるので、その中に入れてしまえばよいと思います。

**Comment by k-takata** [comment]
lParamから座標を取り出すのは、GET_X_LPARAM(), GET_Y_LPARAM() を使うべきです。
case WM_LBUTTONUP: でブロックの途中で tp 変数を宣言していますが、ブロックの最初で宣言しないとVC++でコンパイルが通りません。

とりあえず、こんなところでしょうか。

**Comment by mattn** [comment]
gtk版はGtkNotebookだと思うのでたぶん出来ますよ。

**Comment by mattn** [comment]
gtk_notebook_set_tab_reorderable 呼び出すだけかと。

**Comment by nocd5** [comment]
koronさん
ありがとうございます。
ちょっと :help coding-style してきます。

**Comment by nocd5** [comment]
k-takataさん
色々とチェックして頂きありがとうございます。
MyTabControlProcんを追加したのは、
既存の関数にこんなにコードを追加することに不安が合ったためです。
しかし、確かに無駄なことをしているので
tabline_procに処理追加するようにしてみます。

**Comment by nocd5** [comment]
:set guioptions-=e 知りませんでした…
上記オプションの挙動と同じになるよう、見直してみます。

**Comment by nocd5** [comment]
gtk_notebook_set _reorderableの動作も確認したいですね

**Comment by Shougo** [comment]
Linux環境は手元にありますか？
手元にないなら、他の人に確認してもらうという手はあります。

**Comment by k-takata** [comment]
ドラッグ開始のスレッショルドは [GetSystemMetrics()](http://msdn.microsoft.com/en-us/library/windows/desktop/ms724385.aspx) に、SM_CXDRAG, SM_CYDRAG を指定して取得するのがよいでしょう。（横方向なので、SM_CXDRAG だけで十分かな？）
ドラッグ開始して、マウスカーソルを変更した場合だけ、ドロップ時にタブ順を入れ替えるようにした方が良いでしょう。

**Comment by nocd5** [comment]
Shougoさん
手元にあるのはWindowsXPのみなので、
どなたかにヘルプをお願いしたいです。
最悪、会社ならGTK環境はありますが・・・
motifとmacに関しては全くです。

**Comment by nocd5** [comment]
1. コーディングスタイル
   :help coding-style
   を参考にコーディングスタイルを合わせました。
2. パッチの分割
   タブの並び変えと、ミドルクリックでタブを閉じるコードを分割。
3. 記述等の修正
   k-takataさんに頂いた助言を元に記述の修正
4. 並び変え動作の変更
   :set guioptions-=eで表示されるテキストベースのタブの挙動に合わせました。

https://gist.github.com/nocd5/7579548

**Comment by nocd5** [comment]
並び変え動作の変更内容は、
マウスドラッグ中もカーソル位置に合わせて随時タブを移動させるようにしました。

ただ、テキストベースのタブの場合
移動するタブ:Aの幅が移動先のタブ:Bの幅より小さい時
タブ:B上でカーソルを動かす度にタブ:Aとタブ:Bがガチャガチャ入れ替わる
という動作をしていました。
これは期待される動作ではないだろうと思い、これを回避するようにしています。
具体的にはタブ:Bの中心でタブ:Aの移動先を切り替えています。

ご意見・ご指摘いただければ幸いです。

**Comment by nocd5** [comment]
GTKはこれでいけちゃったりするんでしょうか？
https://gist.github.com/nocd5/7580100

**Comment by k-takata** [comment]
試してみました。なかなかいい感じですね。
主にコーディングスタイルに関して、いくつか直した方が良さそうな点がありました。
- tabline_wndproc() 内の HandleMouseHide() の呼び出しは switch の前の方が、他のウィンドウプロシージャと統一が取れて良いと思います。（動作には影響ないはずですが。）
- GetSystemMetrics() の呼び出しは、case WM_MOUSEMOVE: の中に持ってきた方が良くないでしょうか。
- 1行は80文字を越えないようにしましょう。（コメントの書き方が難しいですが。）
- LoadCursor() の第1引数は 0 より NULL の方が良さそう。（他のコードに合わせる意味で）
- 変数宣言と、実行行の間は1行空けた方がよいでしょう。変数宣言は、変数名の位置を揃えた方が良いです。

ミドルクリックに関しては、取り込んでもらう場合、ドキュメントの更新も必要だと思います。

**Comment by k-takata** [comment]
> GTKはこれでいけちゃったりするんでしょうか？

残念ながらそれだとダメですね。
代わりに、以下のようにするとタブはD&Dできるようになるのですが、表示されている順序と、Vimが管理している順序に食い違いが出るのか、タブをクリックすると元の順序に戻ってしまいます。

``` diff
--- a/src/gui_gtk_x11.c
+++ b/src/gui_gtk_x11.c
@@ -3016,6 +3016,9 @@
            page,
            event_box,
            nr++);
+       gtk_notebook_set_tab_reorderable(GTK_NOTEBOOK(gui.tabline),
+           page,
+           TRUE);
    }

    event_box = gtk_notebook_get_tab_label(GTK_NOTEBOOK(gui.tabline), page);
```

**Comment by nocd5** [comment]
k-takataさん
ありがとうございます。

> 主にコーディングスタイルに関して、いくつか直した方が良さそうな点がありました。

確かにご指摘頂いたとおりです。
自分の方でももう少し確認してみます。

> ミドルクリックに関しては、取り込んでもらう場合、ドキュメントの更新も必要だと思います。

こちらの方は今回はやめようかと思いはじめました。
この動作は一般的ではないので、本家に送るのは如何なものか？というのが理由です。

**Comment by Shougo** [comment]
ミドルクリックに関しては、効果も限定的なのでパッチを分割したほうが良いと思いますね。

**Comment by nocd5** [comment]
やっぱりGTKはそんな簡単には行きませんか
tabpage_Tは連結リストで繋がってるようなので
windowsと同じように、並び変える必要がありそうですね。
確認していただき有難うございます。

ゴールをタイトル通りWindows版だけにするか
GTKくらいは対応にするか考えなければいけませんね。

**Comment by nocd5** [comment]
> ミドルクリックに関しては、効果も限定的なのでパッチを分割したほうが良いと思いますね。

そうですね。この動作は個人的な趣味だと、今は感じてます。

たとえばタブブラウザの設定で、ミドルクリックをタブのロックに割り当ててる人がいたら
混乱を招くだけになってしまいますし、やるとしたら、
マウスアクションへのタブ動作割り当て設定(割り当てるほど動作の種類ありませんが)
の追加でしょうか？ちょっとVimっぽくないですね。

**Comment by k-takata** [comment]
[page-reordered](https://developer.gnome.org/gtk2/2.24/GtkNotebook.html#GtkNotebook-page-reordered)シグナルで並べ替え処理すれば良さそう？

**Comment by k-takata** [comment]
何かできたっぽい？
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a278a9e28417c4acb4d29cf5f2782ba6500ec0e3/tabline-dnd-linux.patch

**Comment by k-takata** [comment]
最初のタブがD&Dできなかったので、修正。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/5484feb5587129a91c58a904584ffcf2918b1b0c/tabline-dnd-linux.patch

**Comment by k-takata** [comment]
インデックスが間違っていました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d47f233848dc7660dc97288545f8d45ef5b7bd4e/tabline-dnd-linux.patch

**Comment by nocd5** [comment]
おお！ばっちり動いてますね。
想像以上にハンドラの中シンプルでした。

gtkでタブドラッグ中もマウスカーソルの表示は変わっていないので
windowsの方も変更しないようにしようと思います。

1点だけ、コメント部分で"tags"となってるところはtypoでしょうか。

**Comment by k-takata** [comment]
> gtkでタブドラッグ中もマウスカーソルの表示は変わっていないので
> windowsの方も変更しないようにしようと思います。

残しておいてよいのではないでしょうか。
GTKの方は、ドラッグ中にタブがアニメーションするのでドラッグできることが一目で分かるのですが、Windowsではそうはなっていないのでカーソルを変えるなどしないと分かりにくいと思います。

> 1点だけ、コメント部分で"tags"となってるところはtypoでしょうか。

がーん。修正しました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d4fb9debb8cd30778d64b4375497f659e9e81660/tabline-dnd-linux.patch

**Comment by nocd5** [comment]
k-takataさんにご指摘いただいた点を修正しました。
ドラッグ中のマウスカーソル変更残しました。

https://gist.github.com/nocd5/7600961

**Comment by nocd5** [comment]
k-takataさんにGTKでのタブ並び替えのコードを書いていただいたので、
タイトルをwindows限定ではなく
**GUIタブページのD&Dによる並び変え機能追加の提案**
等に変更した方がよいでしょうか？

**Comment by k-takata** [comment]
タイトル変更しました。

パッチをマージしました。MSVCでコンパイルが通らない点と、若干のスタイルの修正も行いました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/fe4c0f123f3de674f5f79bac29e7f9da14b0beef/tabline-dnd.patch

私がまとめてvim_devに投げようかと思うのですが、お名前はどうしましょうか。（できれば本名が望ましいです。中にはハンドルで通している人もいますが。）

**Comment by k-takata** [comment]
コメントを修正しました。コードの意図を明確にした方がよいですので。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c181fd2b63d02dcacf371e7ac1e617e5dfe24999/tabline-dnd.patch
ついでにもう一カ所コーディングスタイルを修正しました。（条件文で定数を左辺に書くのは好まれないようなので。）

**Comment by nocd5** [comment]
タイトル変更、パッチのマージと修正ありがとうございます。

> 私がまとめてvim_devに投げようかと思うのですが、お名前はどうしましょうか。（できれば本名が望ましいです。中にはハンドルで通している人もいますが。）

申し訳ありませんがよろしくお願いいたします。
名前は
Masamichi Abe
です。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/LnZVZYls1yk/discussion

**Comment by nocd5** [comment]
> 投げました。

ありがとうございます！

今回は大変勉強になりました。
k-takataさんをはじめ、コメントを下さった皆様
ありがとうございました。

**Comment by Shougo** [comment]
:+1:

**Comment by nocd5** [comment]
大変申し訳ありません
SetCursorの位置を間違えていました。
マウスの移動量がドラッグ判定の閾値を超えたあとに
実行するのが正しいと思います。
https://gist.github.com/nocd5/7610771

まずはvim_devの方に
私の方から一言報告しておくべきでしょうか？

**Comment by k-takata** [comment]
修正版を投げておきました。
https://groups.google.com/d/msg/vim_dev/LnZVZYls1yk/fj_Gz0vhnrsJ

**Comment by nocd5** [comment]
ありがとうございます。
すいませんでした。

**Comment by k-takata** [comment]
todoリストに追加されることになりました。気長に待ちましょう。
https://groups.google.com/d/msg/vim_dev/LnZVZYls1yk/dTBxTUNa45MJ

> Thanks.  I'll add it in the todo list.

**Comment by nocd5** [comment]
本当だ！ありがとうございます。

**Comment by k-takata** [comment]
todo.txtに入りましたので閉じます。

> Patch for drag&drop reordering of GUI tab pages reordering.
> (Ken Takata, 2013 Nov 22, second one, also by Masamichi Abe)

便利なので、私はこれを当てたものを常用することにしました。

**Comment by nocd5** [comment]
issueが閉じててもコメントできたんですね。

k-takataさん、みなさん、ありがとうございました。

**Comment by k-takata** [comment]
いえいえ、こちらこそ有用なパッチをありがとうございました。

ちなみに、[こんなパッチ](https://bitbucket.org/k_takata/vim-ktakata-mq/src/18a195752382d07dcb92d005972fb7c40c44e7e8/tabline-dnd-mark.diff)を当てておくと、`:ver`を実行した際に`追加拡張パッチ:`というものが表示され、何のパッチを当てているかが分かりやすくなります。
![vim-extpatches](https://f.cloud.github.com/assets/840186/1647622/e6dbf5d2-594a-11e3-8078-57af876d38c5.png)

**Comment by Shougo** [comment]
タイマーがしれっと有効になっている……

**Comment by k-takata** [comment]
> タイマーがしれっと有効になっている……

あ、外すの忘れてた。外そう。

**Comment by Shougo** [comment]
Oh...

**Comment by nocd5** [comment]
なるほど、僕もやってみます！

**Comment by nocd5** [comment]
7.4.709の:tabmoveの修正に伴い
D&Dでのタブの並び替えの挙動が変わったのでpatchを修正しました。
Windowsだけでなく
@k-takataさんが書かれたGTKの方も修正が必要だったので、
私の方で修正したので、お手数ですがご確認いただけないでしょうか？
https://gist.github.com/nocd5/165286495c782b815b94

**Comment by k-takata** [comment]
すぐには確認できそうにないので、とりあえずreopenだけしておきます。

**Comment by nocd5** [comment]
仮想環境ですが、私の方でGTK版も期待通りにタブの並び替えができる事を確認しました。
確認した環境は
- OS
  - Windows7 64bit
  - Ubuntu 14.04.2 64bit (VirtualBox上)
- ベースとしたVimのリビジョン
  - 7.4.709
  - 7.4.854(2015/09/02時点で最新)
- guioptions
  - `:set guioptions+=e`
  - `:set guioptions-=e`

patchは
[nocd5/tabline-dnd.patch](https://gist.github.com/nocd5/165286495c782b815b94)
と
[h-east/tabpage_drug_to_right_fix.patch](https://gist.github.com/h-east/cec839c03da41613c6a0)
の両パッチを当て確認しました。

@h-east さんのパッチを当てている理由ですが、
このissueをreopenして頂いた経緯が
1. 7.4.709以降、本件のパッチの挙動がおかしくなった
2. 7.4.709以降、CUIのタブ(`:set guioptions-=e`)のD&Dの挙動も変わっている事に気付く
3. @h-east さん「2.は7.4.709のエンバグでした」「パッチ書きました」

となっているため、両方のパッチを当てています。

**Comment by h-east** [comment]
@nocd5 :+1:
私のpatchも`tabpage_index()`を使うように修正しよう。今晩。

**Comment by h-east** [comment]
> 私のpatchもtabpage_index()を使うように修正しよう。今晩。

Done. (Rev. 2)
https://gist.github.com/h-east/cec839c03da41613c6a0

9/4の晩くらいにvim_devに投げるつもりです。

**Comment by nocd5** [comment]
> Done. (Rev. 2)
> https://gist.github.com/h-east/cec839c03da41613c6a0

今試せる環境が異なり、**Windows8.1 64bit**のみですが、
念のため7.4.854+Rev.2でも確認しました。

パッチ送付お願いします。

**Comment by k-takata** [comment]
@h-east 
ファイル名が… s/drug/drag/

**Comment by h-east** [comment]
@k-takata あっ、警察にpatchを押収されてまうｗ (Fixed. Thanks)

そういえば昨日動作確認していてちょっと違和感があったんです。今patch見たら間違ってる気がする。

``` c
c1 < tabpage_index(curtab)
↓
c1 <= tabpage_index(curtab)
```

今確認出来ないので帰ってから。

**Comment by nocd5** [comment]
> ```
> c1 < tabpage_index(curtab)
> ↓
> c1 <= tabpage_index(curtab)
> ```

どちらでも同じではないでしょうか?
例えばカレントタブとカーソル位置のタブが共に3だった場合、
`tabpage_move(2)`(3を2の右に移動)も
`tabpage_move(3)`(3を3の右に移動)も
タブの移動は起こりませんよね?
`c1 == tabpage_index(curtab)`の場合は`tabpage_move`しない、でもいい気がします。

**Comment by h-east** [comment]
> 今patch見たら間違ってる気がする。

私の勘違いでした。すんません。

vim_devに投げました。
https://groups.google.com/d/topic/vim_dev/_X0cpMreBiw/discussion

**Comment by nocd5** [comment]
ありがとうございます！:+1:

**Comment by nocd5** [comment]
[7.4.857](https://groups.google.com/forum/#!topic/vim_dev/JLkb9P4UZhg)で7.4.709の修正が取り込まれたので、このタイミングでこのissueもcloseしたいと思います。

**Comment by k-takata** [comment]
todoが更新されていないのが不安になったので、Bramをつついてみました。
https://groups.google.com/d/msg/vim_dev/LnZVZYls1yk/JwfPPyiZAAAJ

**Comment by nocd5** [comment]
@k-takata 
ありがとうございます:pray:

**Comment by k-takata** [comment]
GTK3対応でパッチを更新しました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/2c8406f7530549515edad255d3ac1d25aedda6e8/tabline-dnd.patch?fileviewer=file-view-default
が、GTK3でのビルド未確認です。

**Comment by k-takata** [comment]
Bramをつついてみたらtodoリストの順位は上がったものの、いつになったら入るのかなぁ…。
https://github.com/vim/vim/commit/24a98a0eb77245adc50facad8b735b20bfd31a7e#diff-38d7929bd26d74d92ceddf984bbfc8dbR180

**Comment by k-takata** [comment]
8.0.1211
https://groups.google.com/d/topic/vim_dev/roDkJv6jYec/discussion
3年11ヶ月掛かって、ようやく取り込まれました。
@nocd5 さん、初パッチおめでとうございます。

**Comment by nocd5** [comment]
時間がかかってしまいましたが、@k-takata さん始め、みなさんのお陰で初パッチマージされました。
ありがとうございました！
