### ISSUE TITLE
clang 3.3でvimがビルドできない？

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/issues#485]
https://travis-ci.org/vim-jp/vim-ci/jobs/14306926

**Comment by k-takata** [comment]
```
checking whether the C compiler works... no
```

って、一体どういうことなんでしょう？

**Comment by crazymaster** [comment]
> clang のときにも CFLAGS とかを設定しちゃってるせいかもね。
> https://github.com/vim-jp/vim-ci/issues/5#issuecomment-29002340

clangの場合でもCFLAGS=-coverage LDFLAGS=-coverageをしてしまっていました。
おそらくこれが原因なようです。
（3.2では問題なかったのですが...）

**Comment by koron** [comment]
Vimではなくclangの問題だったので wontfix から worksforme へ振り替えます。
