### ISSUE TITLE
VV_VERSIONの初期化位置がおかしい。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#488]
Related issue #487 

上記issueで直そうとしたけど、別のパッチにすべき。
ソースがバッティングするのでちょっと様子見。

**Comment by k-takata** [comment]
7.4.1223で直ったのかな。
https://groups.google.com/d/topic/vim_dev/bSVGRl554uQ/discussion

**Comment by mattn** [comment]
閉じました
