### ISSUE TITLE
`:h mode()@en`内にtypo。（表記が統一されていない。）

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#492]
`:h mode()@en`内の「mode([expr])」は「mode([{expr}])」です。

**Comment by ynkdir** [comment]
報告しました
https://groups.google.com/d/msg/vim_dev/fxHdlW1BHTw/mAeNuvtpMUkJ

**Comment by rbtnn** [comment]
ありがとうございます。
このパッチが出たらクローズします。

**Comment by ynkdir** [comment]
Bram は [expr] の方が好みとのことでした。

**Comment by k-takata** [comment]
[expr] の形で7.4.125直後のコミットで取り込まれました。
http://code.google.com/p/vim/source/detail?r=7818ca6de3d07439571bc1fe788a3efff6979531

**Comment by rbtnn** [comment]
> Bram は [expr] の方が好みとのことでした。

なるほど。

**Comment by thinca** [comment]
それだと `spellbadword([{sentence}])` や `tabpagebuflist([{arg}])` や `tabpagenr([{arg}])` など、他の部分と統一されなくなってしまいますね。

**Comment by thinca** [comment]
改めて見てみると、`getchar([expr])` や `mode([expr])` などがあり、そもそも統一されていない。
