### ISSUE TITLE
removing bevel (inset) borders. (Windows)

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#496]
こんなメールを受け取った。

> I'm using your 7.4 binaries and as I see you are commited to Vim's development I would like to ask you about removing this legacy bevel borders. How hard it would be ?

![annoying borders in vim](https://f.cloud.github.com/assets/468368/1729760/be9644fc-62c7-11e3-9307-eeebb91cbc82.png)

たぶんウィンドウ内側(inset)の3Dボーダーのことだとおもう。
これを消したいとのこと。

**Comment by koron** [comment]
1. guioptionsに追加して
2. ウィンドウスタイル変えて
3. ウィンドウサイズ計算を修正
4. ドキュメント書く

すれば良いはず。誰かたのむ。

**Comment by k-takata** [comment]
> 2.ウィンドウスタイル変えて

静的に変えるだけならこうですね。

``` diff
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -1516,7 +1516,7 @@
        return FAIL;
     }
     s_textArea = CreateWindowEx(
-   WS_EX_CLIENTEDGE,
+   0,
    szTextAreaClass, "Vim text area",
    WS_CHILD | WS_VISIBLE, 0, 0,
    100,                /* Any value will do for now */
```

動的に変える場合は、`GetWindowLong()`, `SetWindowLong()`, `SetWindowPos()`辺りを使うことになるのでしょう。
誰か頼む。

**Comment by mattn** [comment]
静的に変えた場合のキャプチャプリーズ

**Comment by sgur** [comment]
![image](https://f.cloud.github.com/assets/255021/1730484/bc456fd8-62e1-11e3-8aee-fc25984fdd44.png)

いま作ってみました。左がinsetアリ、右がナシです。
なんか、これWindowsだけならなくてもナシ版がデフォルトでもいい気がします。

**Comment by k-takata** [comment]
> 3.ウィンドウサイズ計算を修正

これ、省略できるのではと思ったのですが、ちゃんと直さないとダメそうですね。
マウスでウィンドウサイズを変更すると、ゴミが残ってしまいました。

**Comment by koron** [comment]
https://bitbucket.org/koron/vim-kaoriya-patches/src/6658116d59073a4471a83fea41a0791718773a96/2004-caption_switch.diff

このパッチが参考になるはずです。

**Comment by koron** [comment]
> なんか、これWindowsだけならなくてもナシ版がデフォルトでもいい気がします。

Aeroスタイルなら、ってところでしょうね。

**Comment by k-takata** [comment]
> Aeroスタイルなら、ってところでしょうね。

あるいは、もう少しさかのぼってXPのビジュアルスタイルなら良さそう。

**Comment by sgur** [comment]
あー、なるほど。
ウィンドウのデコレーションの具合によりますね…

**Comment by koron** [comment]
> マウスでウィンドウサイズを変更すると、ゴミが残ってしまいました。

これに簡易的に対応したパッチ

``` diff
--- a/src/gui_w32.c Fri Dec 13 02:10:50 2013 +0900
+++ b/src/gui_w32.c Fri Dec 13 02:39:30 2013 +0900
@@ -1516,7 +1516,7 @@
        return FAIL;
     }
     s_textArea = CreateWindowEx(
-   WS_EX_CLIENTEDGE,
+   0,
    szTextAreaClass, "Vim text area",
    WS_CHILD | WS_VISIBLE, 0, 0,
    100,                /* Any value will do for now */
@@ -1565,7 +1565,7 @@
     /*
      * Start out by adding the configured border width into the border offset
      */
-    gui.border_offset = gui.border_width + 2;  /*CLIENT EDGE*/
+    gui.border_offset = gui.border_width;  /*CLIENT EDGE*/

     /*
      * Set up for Intellimouse processing
```

**Comment by k-takata** [comment]
起動時に IsThemeActive() で Visual Style が有効か確認して、ウィンドウスタイルを設定するようにしてみました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/3464dd23125447d86e80199413001ad712e5eba2/remove-client-edge.patch
…が、WM_THEMECHANGED を受けて動的にスタイルを変えた方がいいのだろうかと思ったり。
あとは、やはり手動で設定できるようにオプションを付けるべきかと思ったり。

**Comment by koron** [comment]
:+1: 

テーマにしたがって自動で決めるなら
WM_THEMECHANGED はあると良いでしょうね。 (nice to have程度)
ただVim的ではない気もする。

Vim的という意味では
`go` で設定できるようにして、初期値は現在のテーマで決まる
という選択肢もあるとは思います。

**Comment by crazymaster** [comment]
Linux でも気になります。
![screenshot from 2014-06-18 19 00 04](https://cloud.githubusercontent.com/assets/1528093/3312267/7a0da2fc-f6cf-11e3-9149-a9c9f6ca6eee.png)
Ubuntu 14.04, gvim

14.04からウィンドウのボーダーがなくなったので、下端のボーダーが特に目立ちます。

**Comment by Shougo** [comment]
言われて初めて気づきました。確かに気になる人がいるかも知れません。
上記のパッチも Windows にしか対応していないようですね。

**Comment by crazymaster** [comment]
あと、最大化した時に変な余白ができてしまいますね。

**Comment by koron** [comment]
最大化したときの余白は、仕方ないかなぁ。

私が気になったのはこの図に示したメニューとクライアント領域の間の1ドット

![02](https://cloud.githubusercontent.com/assets/468368/3788811/aa644c4e-1a79-11e4-8a38-32e63b5a1d2f.png)

あと `guioptions` 化はしなくても良いだろうか?

**Comment by koron** [comment]
この1ドット、メニュー側のものっぽい。

**Comment by koron** [comment]
> この1ドット、メニュー側のものっぽい。

本当にそうなら諦めても良いか。

**Comment by 0xBADDCAFE** [comment]
koron さんに依頼して作ってもらった、本パッチ適用済みのバイナリです。koron さんに OK 頂いたので、試してみたい方のために貼っておきます。

32bit http://files.kaoriya.net/vim/snapshots/vim74-kaoriya-win32-snapshot-20140803.zip
64bit http://files.kaoriya.net/vim/snapshots/vim74-kaoriya-win64-snapshot-20140803.zip

個人的にこのパッチを適用してビルドしたものを使い続けているのですが、見た目的にもこちらがいいですし特に違和感や問題は感じていません。ただメニュー側の 1 ドット、メニュー消してるのでずっと気づきませんでした。

動的変更/guioptinon 化については、個人的には動的に変えるほうがしっくり来るかと感じていました。visualstyle を変えることで見た目に違和感が出るというのが良くないと感じるので。ただ、Vim 的という考え方があまりわからないのもあるので、より受け入れられやすい形にするのがいいと思いました。むしろ visualstyle を変更するシーンも稀なので、含めなくていいとも思います。

https://github.com/vim-jp/issues/issues/496#issuecomment-46440788

> あと、最大化した時に変な余白ができてしまいますね。

これは Win/Linux 問わずでしょうか。Win でもAeroSnap など使って最大化・ウィンドウサイズの変更をしたら変な余白は出来るんですが、このパッチにかかわらずできています。

**Comment by mattn** [comment]
並べてみた。
下がオリジナル。

![](http://go-gyazo.appspot.com/f3e89a695004fb00.png)

**Comment by crazymaster** [comment]
``` diff
diff --git a/src/gui_gtk_x11.c b/src/gui_gtk_x11.c
index 97ad6b0..f338a04 100644
--- a/src/gui_gtk_x11.c
+++ b/src/gui_gtk_x11.c
@@ -3178,7 +3178,7 @@ gui_mch_init(void)
 #endif

     /* Initialize values */
-    gui.border_width = 2;
+    gui.border_width = 0;
     gui.scrollbar_width = SB_DEFAULT_WIDTH;
     gui.scrollbar_height = SB_DEFAULT_WIDTH;
     /* LINTED: avoid warning: conversion to 'unsigned long' */
```

とすると、勝手にウィンドウのサイズが小さくなってしまいます。
1なら問題ないのですが...

**Comment by koron** [comment]
Linuxは別Issue立てたほうがよいかも。実装が複雑化する懸念があるので。
オプションを追加して共通化するなら、またソレ専用にissueがいるかもだけど。

**Comment by crazymaster** [comment]
別issue建てたのでLinuxは今後そちらで

**Comment by koron** [comment]
@crazymaster  ありがとうございます :bow:

**Comment by koron** [comment]
さーせん。こっちでした。

![vim-margin](https://cloud.githubusercontent.com/assets/468368/3929330/4fb6fa04-241e-11e4-8056-824f004671cd.png)

7.4.404 との組み合わせで下に枠がでてしまいました。389では発生していません。

**Comment by crazymaster** [comment]
> https://github.com/vim-jp/issues/issues/496#issuecomment-46440788
> 
> > あと、最大化した時に変な余白ができてしまいますね。
> 
> これは Win/Linux 問わずでしょうか。Win でもAeroSnap など使って最大化・ウィンドウサイズの変更をしたら変な余白は出来るんですが、このパッチにかかわらずできています。

@0xBADDCAFE 私が確認したのはLinuxなので、これでWin/Linux 問わずということになりますね

**Comment by crazymaster** [comment]
@koron さんの最初の簡易的に対応したパッチと同じのがvim-devに...
https://groups.google.com/d/msg/vim_dev/6f4WS-xk66I/dcj8N6CiQg8J

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/6f4WS-xk66I

**Comment by k-takata** [comment]
そのスレッドに私のパッチを投げてみました。
https://groups.google.com/d/msg/vim_dev/6f4WS-xk66I/jl8JdgNT8hMJ
が、Bramはedgeありの方が良いと思っているようなので、どうなるやら。

**Comment by crazymaster** [comment]
Patch 7.4.930
https://groups.google.com/d/msg/vim_dev/u6qOL1xF4oU/B7ZiXXvvBgAJ
