### ISSUE TITLE
test100 is failed on Windows

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#497]
Windows はテストを基本的に ff=dos で実行する。
しかし test100 に含まれる redir & echo は
ff の値に関係なく LF (ff=unix相当) なファイルを吐くらしい。

``` vim
:redir >>test.out | echo "global value shouldn't be changed and still be 5!" | echo 'ONE: expecting global undolevels: 5, local undolevels: -123456 (default)'|:setglobal undolevels? | echon ' global' | setlocal undolevels? | echon ' local' |echo "" |redir end
```

test100 ではこれ以外にも ff=dos として test.out に出力するので改行コードが混在してしまい、
いまのままテスト用のMakefileをいじるだけではどうにもできない。

---

いまのところ考えられる対応方法は
-   test100 の該当部分の出力方法を変える。
-   `redir >> {ファイル}` 時に ff を見て出力改行コードを決定するようにvimを修正する

ほかに良い手はあるだろうか?

**Comment by koron** [comment]
2 でやるなら message.c の redir_write() で putc() しているところ(3166行目付近)、
そこで判断&変換を噛ませる必要がありそう。

**Comment by koron** [comment]
適当なパッチ作ったら、こんどは test17 でコケたw

あ～そういうことか…

**Comment by koron** [comment]
test100 の :w してるところの前全部に :set ff=unix 足せば良さそう。

**Comment by koron** [comment]
Sent https://groups.google.com/d/msg/vim_dev/3oUotJXDhqU/gZhbHf6LeuAJ

**Comment by k-takata** [comment]
ずいぶん前に todo.txt に入っていました。

> Patch to make test 100 work on MS-Windows. (Taro Muraoka, 2013 Dec 12)

**Comment by koron** [comment]
これ、まだマージされてへんのか… (´・ω・｀)

**Comment by k-takata** [comment]
7.4.406
https://groups.google.com/d/topic/vim_dev/7H2EKtZZn9I/discussion
