### ISSUE TITLE
v:oldfilesの状態がおかしい。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#498]
http://lingr.com/room/vim/archives/2013/12/13#message-17817414

> $ vim -i NONE
> :let v:oldfiles += ['foo']
> E685: 内部エラーです: set_var()
> 内部エラー頂きました。

v:oldfilesの状態がどうもおかしいみたいなのでとりあえずissuesに登録しておきます。

よろしくお願いします。

**Comment by ichizok** [comment]
コードを見るに、`v:oldfiles` は `let` で変更できない設計なので、エラーになること自体は問題ない (仕様) と思います。
実際、普通に起動しても `:let v:oldfiles += ['foo']` はエラーになります。

ただ、`-i NONE` や読み込むべきviminfoがない状態で起動すると `v:oldfiles` には配列領域がアロケートされません。
(確保しても変更不可で無駄なので、これ自体は妥当かと思います)

このため、`v:oldfiles` に対してforループを回そうとすると `E714: List required` のエラーになりますが、
このエラーが導出される他の箇所と比べると、配列領域がない場合に上記エラーになるのはちょっと厳しすぎるし、
不親切なエラーメッセージであると思います。

エラー出さないようにしました。
https://gist.github.com/ichizok/7950767

**Comment by itchyny** [comment]
```
# E15
vim -u NONE -i NONE -N -c 'let x = deepcopy(v:oldfiles) + ["foobar"]'

# no error
vim -c 'let x = deepcopy(v:oldfiles) + ["foobar"]'
```

**Comment by ichizok** [comment]
ということは、配列領域はアロケートしておかないとだめですね..

**Comment by mattn** [comment]
あまり難しく考えずに

``` diff
diff -r 92c9748e0ccb src/main.c
--- a/src/main.c    Sun Oct 06 17:46:56 2013 +0200
+++ b/src/main.c    Sat Dec 14 23:32:24 2013 +0900
@@ -701,6 +701,10 @@
    read_viminfo(NULL, VIF_WANT_INFO | VIF_GET_OLDFILES);
    TIME_MSG("reading viminfo");
     }
+# ifdef FEAT_EVAL
+    if (get_vim_var_list(VV_OLDFILES) == NULL)
+   set_vim_var_list(VV_OLDFILES, list_alloc());
+# endif
 #endif

 #ifdef FEAT_QUICKFIX
```

でいいんじゃないかな。

**Comment by mattn** [comment]
内部エラーは別として、いったん初期化されないって件で送ろうかと思いますが、どうでしょう？＞all

**Comment by ichizok** [comment]
＜異議なし

**Comment by itchyny** [comment]
お願いします

**Comment by thinca** [comment]
すでに投げられていたのでリンク貼っておきます。
https://groups.google.com/d/topic/vim_dev/QamxovCtF-g/discussion
なんかレス付いていますね。もう少し説明した方が良さそう。(後は任せた)

**Comment by ichizok** [comment]
> https://groups.google.com/d/topic/vim_dev/QamxovCtF-g/discussion

vimの起動オプションが `-i NONE` でなく `-u NONE` になってます

**Comment by ichizok** [comment]
あ、`-u NONE` でも同じか..

**Comment by h-east** [comment]
TODOリストに入りました。

> Patch to initialize v:oldfiles. (Yasuhiro Matsumoto, 2013 Dec 15)

**Comment by h-east** [comment]
Patch 7.4.146 で入りました！
https://groups.google.com/d/msg/vim_dev/lKRKAHNPpOg/wzAoSiugj7oJ
