### ISSUE TITLE
quickfixウィンドウだけになったときにbwipeout!する設定すると、Vimが死んでしまう。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#499]
以下の.vimrcと手順で行うとVimが死んでします。

**.vimrc**

```
augroup vimrc
  autocmd!
augroup END
autocmd vimrc WinEnter * :execute ( (winnr('$') == 1) && (&filetype ==# 'qf') ? 'bwipeout!' : '')
```

**手順**
1. vim -i NONE で起動。
2. copen
3. Ctrl-w Ctrl-k
4. bwipeout

**環境**

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 13 2013 23:37:11)
MS-Windows 32-bit GUI version
Included patches: 1-126
```

**Comment by h-east** [comment]
@rbtnn 報告ありがとうございます。
2点修正させてもらいました。
- `autocmd vimrc WinEnter * ～` の行の余分な空白を削除しました。
- 手順の`3. Ctrl-k` を `3. Ctrl-w Ctrl-k` に修正しました。

Fedora 19の自前ビルドVim 7.4.131でも再現しました。

```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```

**Comment by mattn** [comment]
消された後で元のバッファに戻ろうとしているみたい。

``` diff
diff -r 7818ca6de3d0 src/buffer.c
--- a/src/buffer.c  Wed Dec 11 18:53:29 2013 +0100
+++ b/src/buffer.c  Mon Dec 16 10:52:33 2013 +0900
@@ -312,6 +312,8 @@
 {
     buf_T  *bp;

+    if (buf == NULL)
+   return FALSE;
     for (bp = firstbuf; bp != NULL; bp = bp->b_next)
    if (bp == buf)
        return TRUE;
@@ -1359,7 +1361,10 @@
     }

     /* Go to the other buffer. */
-    set_curbuf(buf, action);
+    if (buf_valid(buf))
+    {
+   set_curbuf(buf, action);
+    }

 #if defined(FEAT_LISTCMDS) \
    && (defined(FEAT_SCROLLBIND) || defined(FEAT_CURSORBIND))
```

**Comment by mattn** [comment]
誰か試して貰えると助かります。

**Comment by ynkdir** [comment]
おつかれさまです。

```
$ vim -u NONE
:new
:autocmd WinEnter * bwipeout
:bwipeout
```

quickfix 限定ではなさそうです。
mattn さんのパッチで落ちなくなりました。
make test も通ります。

この動作順序でいいのかは気になりました。

```
$ vim -u NONE
:new
:put ='hello'
:autocmd WinEnter * bwipeout
:bwipeout!        <- buffer 2 残る
:bwipeout!        <- buffer 2 の内容消える
```

**Comment by mattn** [comment]
ありがとうございます。
確かに変ですね。

**Comment by h-east** [comment]
これ、期待する動作は何でしょうか？
window1つでバッファ1つ(無名バッファ)になるでOK？

**Comment by ynkdir** [comment]
そんな感じだと思います

**Comment by h-east** [comment]
追記情報
`:bwipeout`しようとしているバッファの`bufhidden`が　unload or delete or wipe の場合はSEGVしないようです。
つまりデフォルトの "" もしくは 'hide' の時にSEGVする。

**Comment by h-east** [comment]
unload or delete or wipe の共通点は close_buffer() [buffer.c : 339]の冒頭で unload_buf が TRUE にセットされる事。

**Comment by h-east** [comment]
issueに書いてある手順での流れ
登場物
- buffer  
  buf1: 無名バッファ (current buffer)  
  buf2: quickfixバッファ
- window
  win1: 上段の無名buffer表示してるwindow (current window)
  win2: 下段のquickfixを表示してるwindow

~~1. win1に対して`:bw`~~
~~2. win1が閉じられてwin2がcurrent windowになる~~
~~3. autocmd EVENT_WINENTER が走って buf2 がwipe!される~~
~~4. buf1がwipeされる。(バッファがひとつも無い状態になってしまう)~~
~~5. win2にバッファをアサインしようとするがバッファがひとつも無いので変なメモリアクセスをしてSEGV~~

~~バッファがひとつも無い状態になってしまうことがマズい事と思いますので、どうしてもバッファが無い状態の時には無名バッファを作成するようにしました。~~

`--No lines in buffer--` が表示されるけどこれはいいのかな？
make testがALL DONEなのは確認しています。
いろいろ試して貰えると助かります。

``` diff
diff -r 2f856c7c1d43 src/buffer.c
--- a/src/buffer.c  Sun Dec 15 10:02:33 2013 +0100
+++ b/src/buffer.c  Tue Dec 31 21:12:04 2013 +0900
@@ -1309,6 +1309,13 @@
        else
        buf = curbuf->b_prev;
    }
+   if (buf == NULL)    /* Still no buffer, just create one */
+   {
+       retval = do_ecmd(0, NULL, NULL, NULL, ECMD_ONE,
+                     forceit ? ECMD_FORCEIT : 0, curwin);
+       if (retval == OK)
+       buf = curbuf;
+   }
     }

     /*
```

良いお年を:smile:

**Comment by ynkdir** [comment]
変更ありのときバッファが消えてないです。

``` vim
$ vim -u NONE
:new
:put ='foo'
:autocmd WinEnter * bwipeout
:bwipeout!
:ls!
  2u#    "[No Name]"                    line 1
  3 %a   "[No Name]"                    line 1
```

**Comment by h-east** [comment]
@ynkdir 指摘ありがとうございます。

処理の流れの説明が間違っていたので修正。
1. win1に対して`:bw`
2. win1が閉じられてwin2がcurrent windowになる
3. autocmd EVENT_WINENTER が走って buf2 がwipe!される
4. buf1(==current buffer)をwipe!するための前準備としてwipe!後のcurrent buffer候補を探すがバッファはbuf1しかないので見つからない。(buffer.c:1362の段階で buf が　NULL)
5. buffer.c:1362のset_curbuf()が引数buf←NULL、action←DOBUF_WIPEで呼ばれる。  
   current buffer(buf1)をwipeして新current bufferをNULLにして無理やり処理が進む。
6. NULLポインタアスセスをしてSEGV

4.で次current bufferがどうしても見つからない場合は新規にバッファを作成してそれが次current bufferになるような引数でset_curbuf()を呼び出すようにしました。

あと私、set_curbuf()の第1引数の意味を勘違いしてました。

``` diff
diff -r 2f856c7c1d43 src/buffer.c
--- a/src/buffer.c      Sun Dec 15 10:02:33 2013 +0100
+++ b/src/buffer.c      Thu Jan 02 17:41:46 2014 +0900
@@ -1309,6 +1309,22 @@
            else
                buf = curbuf->b_prev;
        }
+       if (buf == NULL)        /* Still no buffer, just create one */
+       {
+           if (action == DOBUF_UNLOAD)
+           {
+               EMSG(_("E90: Cannot unload last buffer"));
+               return FAIL;
+           }
+
+           bp = curbuf;
+           retval = do_ecmd(0, NULL, NULL, NULL, ECMD_ONE,
+                                         forceit ? ECMD_FORCEIT : 0, curwin);
+           if (retval == FAIL)
+               return FAIL;
+           buf = curbuf;
+           curbuf = bp;
+       }
     }

     /*
```

**Comment by ynkdir** [comment]
ありがとうございます。
別件かもしれませんがbwipeoutの後 new or split できないです。

```
$ vim -u NONE
:new
:autocmd WinEnter * bwipeout
:bwipeout
:new
```

**Comment by h-east** [comment]
@ynkdir うぅ:tired_face:...後で調べます。

**Comment by h-east** [comment]
> 別件かもしれませんがbwipeoutの後 new or split できないです。

`:autocmd WinEnter * bwipeout` 設定以降の `:new` や `:split` はWinEnterイベントが発生して古いバッファがwipeされるのでこの動きで正しいと思います。どうでしょうか？

**Comment by ynkdir** [comment]
あーすみません。それですね。:au! したら大丈夫でした。

**Comment by h-east** [comment]
了解です。Thanks.
あとは `--No lines in buffer--` を出なくすれば完成!?。

**Comment by h-east** [comment]
patch更新。
基本的に buffer.c: 1159 ~ 1180 と同等の事をしてるだけなのでなるべく処理内容をそちらに合わせました。

> あとは `--No lines in buffer--` を出なくすれば完成!?。

`need_fileinfo` をFALSEにすれば表示されなくなる。
けど buffer.c: 1159 ~ 1180 では特に設定されていない。
どこでTRUEになっているか調べたら autocmd EVENT_WINENTER 内のbwipeout! 処理中にセットされていました。
なので再度FALSEにする処理をpatchに追加してます。
特に問題なければ数日中にvim_devに投げます。
よろしくどうぞ。

``` diff
diff -r 2f856c7c1d43 src/buffer.c
--- a/src/buffer.c      Sun Dec 15 10:02:33 2013 +0100
+++ b/src/buffer.c      Mon Jan 06 01:14:30 2014 +0900
@@ -1309,6 +1309,28 @@
            else
                buf = curbuf->b_prev;
        }
+       if (buf == NULL)        /* Still no buffer, just create one */
+       {
+           if (action == DOBUF_UNLOAD)
+           {
+               EMSG(_("E90: Cannot unload last buffer"));
+               return FAIL;
+           }
+
+           buf = curbuf;
+           setpcmark();
+           retval = do_ecmd(0, NULL, NULL, NULL, ECMD_ONE,
+                                         forceit ? ECMD_FORCEIT : 0, curwin);
+           /*
+            * do_ecmd() may create a new buffer, then we have to delete
+            * the old one.  But do_ecmd() may have done that already, check
+            * if the buffer still exists.
+            */
+           if (buf != curbuf && buf_valid(buf) && buf->b_nwindows == 0)
+               close_buffer(NULL, buf, action, FALSE);
+           need_fileinfo = FALSE;  /* Don't display file info after redraw */
+           return retval;
+       }
     }

     /*
```

**Comment by mattn** [comment]
++

**Comment by ynkdir** [comment]
GJ!

**Comment by koron** [comment]
https://twitter.com/h_east/status/420192599064866816

報告メールのtitle案: **crush when using :bwipeout in autocmd**

**Comment by h-east** [comment]
@koron Thank youです！
本文はいつものいい感じで書きます。

**Comment by h-east** [comment]
送りました。
Thanks for reading my crazy english.
https://groups.google.com/d/msg/vim_dev/WlDpL1cAIT4/-wvS3Zqx6zUJ

**Comment by h-east** [comment]
TODOリストに入りました。

> Patch to fix crash when using :bwipeout in autocmd. (Hirohito Higashi, 2014 Jan
> 6)

**Comment by h-east** [comment]
Patch 7.4.140
https://groups.google.com/d/msg/vim_dev/Q8JQ6aWXis4/EOBlrzqmZYQJ

Bram氏が重複処理を関数化してくれた。この辺りがVimが長生きの1つの要因かも。
お疲れ様でした。＞各位
