### ISSUE TITLE
X server が死ぬと Clipboard 繋いでた CUI の Vim のキーマッピングが効かなくなる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#5]
再現した環境は以下:
1. ローカルはWindowsで、XmingでXサーバを立てる。
2. Linux のサーバに対してputtyで接続し、$DISPLAY にはローカルのアドレスを入れておく。
3. putty 内で CUI の Vim を起動。CUI版でもXがあればClipboardとか使える。
4. Xming を終了させる。
5. 3 で起動した Vim でキーマッピングが一切効かなくなる。`:map` によると設定自体は残っている。

**Comment by koron** [comment]
キー入力から実行までの間に、X Serverへの「お伺いフェーズ」がmap処理と同列であるのかなぁ…?

**Comment by ynkdir** [comment]
map は getchar.c:vgetorpeek() で処理されている。
vgetorpeek() では関数の最初と最後で ++vgetc_busy と --vgetc_busy を実行してフラグを管理している。
vgetorpeek():2790 の inchar() 呼び出しでキー入力待機中に X の接続が切れると setjmp/longjmp の大域ジャンプが発生する。
そのため vgetc_busy がクリアされず常に vgetc_busy > 0 となる。
vgetorpeek() は vgetc_busy > 0 ならなにも処理せずに NUL を返す。
save_vgetc() は文字を取れなかったときは直接キー入力を取得する。

大域ジャンプ後に vgetc_busy をクリアすればとりあえずは直りますがなんとも微妙な感じはします。

```
diff -r 15b934a16641 src/main.c
--- a/src/main.c    Wed Sep 14 19:04:40 2011 +0200
+++ b/src/main.c    Sun Sep 25 18:50:43 2011 +0900
@@ -1009,6 +1009,7 @@
    skip_redraw = FALSE;
    RedrawingDisabled = 0;
    no_wait_return = 0;
+   vgetc_busy = 0;
 # ifdef FEAT_EVAL
    emsg_skip = 0;
 # endif
```

```
os_unix.c:
1518     static int
1519 x_IOerror_handler(dpy)
1520     Display *dpy UNUSED;
1521 {
1522     xterm_dpy = NULL;
1523     x11_window = 0;
1524     x11_display = NULL;
1525     xterm_Shell = (Widget)0;
1526
1527     /* This function should not return, it causes exit().  Longjump instead. */
1528     LONGJMP(x_jump_env, 1);
1529 # ifdef VMS
1530     return 0;  /* avoid the compiler complains about missing return value */
1531 # endif
1532 }
```

 |
 | ジャンプ
 v

```
main.c:
994 #if defined(FEAT_X11) && defined(FEAT_XCLIPBOARD)
995     /* Setup to catch a terminating error from the X server.  Just ignore
996      * it, restore the state and continue.  This might not always work
997      * properly, but at least we don't exit unexpectedly when the X server
998      * exists while Vim is running in a console. */
999     if (!cmdwin && !noexmode && SETJMP(x_jump_env))
1000     {
1001         ...
```

```
getchar.c:
1760 /*
1761  * Like vgetc(), but never return a NUL when called recursively, get a key
1762  * directly from the user (ignoring typeahead).
1763  */
1764     int
1765 safe_vgetc()
1766 {
1767     int c;
1768
1769     c = vgetc();
1770     if (c == NUL)
1771         c = get_keystroke();
1772     return c;
1773 }
```

**Comment by koron** [comment]
大域ジャンプ時にvgetorpeekを飛び越えちゃう、ということですね?

だとすれば本来ならvgetorpeekでトラップしてbusyを落としたいですねぇ。
上げた人に落とさせるのが常套ですから。

**Comment by ynkdir** [comment]
そういうことです。
ちゃんとした修正方法についてはよくわかりませんが。
自分の場合は再現手順の関係でvgetorpeek内で発生してましたが他のタイミングで発生すれば他の問題が起こるんじゃないかなぁという気がします。
そもそもこれXが死ぬという異常事態でmapが直ったからといってそのまま作業続行するんですかね。

**Comment by ynkdir** [comment]
あぁそうかクリップボードだけ使ってるならXが落ちたくらいでどうこうなって欲しくないか。
エラーハンドラ無効化すればいいのかな。

**Comment by ynkdir** [comment]
http://groups.google.com/group/vim_dev/browse_thread/thread/f7c0464b9f400c21
vim_dev で同じ問題を他の方が報告していたので解決に向かうと思われます。

**Comment by ynkdir** [comment]
Patch 7.3.330
http://groups.google.com/group/vim_dev/browse_thread/thread/362ec50faa7e05f4

vgetc_busy をリセットするだけの ad-hoc な修正が採用されました。
のでいったん閉じます。
不都合があったら再開してください。
