### ISSUE TITLE
virtualedit=block で矩形選択中に表示行移動がおかしい場合がある

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/issues#502]
再現バージョン
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 14 2013 23:04:18)
MS-Windows 32/64 ビット GUI/CUI 版
適用済パッチ: 1-131

再現方法
1. vim -u NONE で起動
2. `set virtualedit=block` を設定
3. 以下のようなテキストを用意する。

```
 aaaaaaaaaaaaaaaaaaa
 bbbbbbbbbbbbbbbb
 cccccccccccc
```

1行で矩形選択を開始し、`$`で行末に移動。`gj`を押すと、カーソルが 2 行目の表示末尾に飛んでしまう。

![vimissue](https://f.cloud.github.com/assets/599164/1783809/911615aa-68c8-11e3-8bd1-1ea5eac82507.gif)

**Comment by h-east** [comment]
@0xBADDCAFE 報告ありがとうございます！

Fedora 19のVim 7.4.131(自前ビルド) でも再現しました。

**Comment by 0xBADDCAFE** [comment]
こちらこそ、ご協力助かります。あとタグ付け気付いていませんでした、ありがとうございます。
個人的にこの issue では、gj が流行ると思っています。

**Comment by h-east** [comment]
矩形ビジュアルモード(ctrl-v) かつ 'wrap' かつ '$' 入力後に左右カーソル移動がない場合の gj および gk の挙動を修正しました。
それ以外の動作には影響を与えていないはず。
試してもらえると助かります。

``` diff
diff -r 2f856c7c1d43 src/normal.c
--- a/src/normal.c      Sun Dec 15 10:02:33 2013 +0100
+++ b/src/normal.c      Sat Dec 21 01:51:11 2013 +0900
@@ -4644,7 +4644,10 @@
     }
 #endif

-    coladvance(curwin->w_curswant);
+    if (virtual_active() && atend)
+       coladvance(MAXCOL);
+    else
+       coladvance(curwin->w_curswant);

 #if defined(FEAT_LINEBREAK) || defined(FEAT_MBYTE)
     if (curwin->w_cursor.col > 0 && curwin->w_p_wrap)
```

TODO:
test追加！

**Comment by h-east** [comment]
現状のtestはALL DONEなのを確認してます。

**Comment by 0xBADDCAFE** [comment]
GJ :+1:
自分で書いた以上 GJ やらねばならない使命感にかられ、恥ずかしさで後悔している次第です。

それはそれとして、パッチ試してみました。
右端に飛んでしまう挙動がなくなったことを確認しました。

`gj`後の移動先ですが、この修正では次の行の行末に移動しています。
この操作を行う際は`:set virtualedit=block`が設定されているので、移動先は
カーソル位置の真下とならないでしょうか。
あらかじめ期待される挙動として明記しておくべきでした、すいません。

**Comment by 0xBADDCAFE** [comment]
すいません、上記の挙動について勘違いしていました。
行末に移動しているのでこの修正後の挙動であっていました。
確認した範囲ですべて問題なしでした。

**Comment by h-east** [comment]
@0xBADDCAFE 確認ありがとうです。
何もなければ20時間後くらいにvim_devにpatchを送る予定です。

**Comment by mattn** [comment]
++

**Comment by h-east** [comment]
testも追加してvim_devに送りました。
https://groups.google.com/d/msg/vim_dev/F2KoCT1ZXpQ/aRNmuZufoe4J

**Comment by h-east** [comment]
TODOリストに入りました。

> Patch to fix cursor movement. (Hirohito Higashi, 2013 Dec 21)

**Comment by 0xBADDCAFE** [comment]
確認しました、ありがとうございました。

**Comment by h-east** [comment]
Patch 7.4.147 で入りました！
https://groups.google.com/d/msg/vim_dev/VBgk05544HE/mznMc18Z05oJ
