### ISSUE TITLE
runtime/menu.vim内のtypo. Se&T Compiler

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#504]
```
-&Tools.Se&T\ Compiler
+&Tools.Se&t\ Compiler
```

じゃないでしょうか？
他には特にショートカットだからといって大文字にしている箇所はありません。

尚合わせてlangファイルを全て修正する必要があります。

**Comment by nocd5** [comment]
runtime/menu.vimとruntime/lang/menu*.vimの修正パッチ
https://gist.github.com/nocd5/8115153

何箇所か&Set\ Compilerとか&SeT\ Compilerとなっている箇所も修正しています

**Comment by ynkdir** [comment]
意図的みたいです。

[Menu Misspelling]
http://thread.gmane.org/gmane.editors.vim.devel/12324/

**Comment by nocd5** [comment]
ありがとうございます。その情報みつけられませんでした。
ちょっと違和感はありますが、意図的だったんですね。

解決ということで閉じさせていただきます。
ynkdirさんありがとうございました。

**Comment by koron** [comment]
typo だと思ったら意図的だった、という話ですので、 worksforme へ振り替えます。
