### ISSUE TITLE
getregtype()の挙動がヘルプファイルに書かれているものと違う

### ISSUE THREAD

**Issue by LeafCage** [vim-jp/issues#505]
ドキュメントでは、「空、または未知のレジスタ」の場合、`0`が返されることになっていますが、
実際には、
- レジスタが空の場合→空文字が返る
- 未知のレジスタの場合→無名レジスタ（または`v:register`？）のtypeが返る

という挙動になっているようです。

レジスタが空の場合は空文字が返るというのを仕様とするべきでしょうか。
また、未知のレジスタの場合に無名レジスタのtypeが返るのは修正するべきでしょうか。

**Comment by ynkdir** [comment]
ありがとうございます。報告しました。
https://groups.google.com/d/msg/vim_dev/-N5uY0t9IxE/z6LzIllpG_8J

**Comment by h-east** [comment]
TODOリストに入りました。

> Patch to make getregtype() work as documented. (Yukihiro Nakadaira, 2013 Dec
> 26)

**Comment by h-east** [comment]
Patch 7.4.145 で入りました！
https://groups.google.com/d/msg/vim_dev/HaLrXFQfV-g/kkcu2Zg06qUJ
