### ISSUE TITLE
mingw4.6.1でビルドしたlua5x.dllとneocomplete

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#506]
Vim本体やneocompleteの不具合ではありませんが、一応報告しておきます。

mingw4.6.1(小生使用は正確にはTDM-GCCです)でビルドしたlua5x.dllを使用し、
「表示」や「表現」などの`表＋マルチバイト文字`の単語を含むファイルで
neocompleteが動作するとVimが落ちます。
mingw4.8.1ビルドのlua5x.dllではこの症状は現れません。

luaとmingw4.6.1の組み合わせでの不具合は以前他のソフトでも起こったことがありました。

環境としては稀なので不要かとも思いましたが、
もしかしたら今後luaを使用するプラグインでも同様の現象が起こるかもしれないので情報として残しておきます。

**Comment by nocd5** [comment]
特にアクションはありませんので閉じます。

**Comment by koron** [comment]
スタックトレース取れます?
あとluaの詳細なバージョンも。

直感的にはエスケープシーケンスが突き抜けているんだとはおもいますが…

**Comment by nocd5** [comment]
Luaのバージョンは5.2.0、5.2.2、5.2.3で落ちます。
件名で`lua5x.dll`としてしまいましたが5.1.4は大丈夫のようです。

すいませんスタックトレースはほとんどやったことがなく、
gdbでやってみようと思ったのですがうまくいかず見れませんでした。
lua52.dllもvimも`gcc -d`でコンパイルしたのですが
肝心の落ちるところのデバッグシンボルが取得できず

```
Program received signal SIGSEGV, Segmentation fault.
0x77be554a in ?? ()
```

と関数名など見えず、断念しました。
