### ISSUE TITLE
autoload 変数に関数参照が設定されている場合に autoload 関数を呼ぶと内部エラーが発生する

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/issues#507]
内部エラーが発生したので報告します。
autoload 変数に関数参照が設定されている場合にそのスクリプトの autoload 関数を呼ぶと内部エラーが発生しました。
あと最初に書いておくと再現するスクリプトは Vim script 的に間違った記述方法になっているかもしれません（autoload 変数名とファイル名が完全に一致していないので。
#### 再現用スクリプト
- [vim-bug20131231](https://github.com/osyo-manga/vim-bug20131231)

再現を行う場合は予めローカルにコピーして置いて下さい。
#### エラー内容

``` vim
D:/vim-bug20131231/autoload/bug20131231.vim の処理中にエラーが検出されました:
行   12:
E685: 内部エラーです: hash_add()
```
#### 再現手順
- 1.`$ vim -u NONE -N -c "set rtp+=D:/vim-bug20131231"` で Vim を起動
  - `'runtimepath'` に `vim-bug20131231` のパスを設定しておく
- 2.`:call bug20131231#hoge()` で autoload 関数を呼ぶ
- 3.内部エラーが発生
#### 現状わかっている事
- `g:Bug20131231#funcref` ではなくて `g:Bug20131231#funcref` で定義されていればエラーは発生しない
- `bug20131231#hoge()` ではなくて `g:Bug20131231#funcref` を参照した場合はエラーは発生しない
#### 再現環境
- Kaoriya 版 Vim 7.4.92
- WindowsXP SP3

**Comment by ynkdir** [comment]
報告ありがとうございます。
うちでも再現できます。

メモ

``` vim
" autoload/Foo.vim   (大文字注意。windowsは小文字可)
function s:x()
endfunction
let Foo#x = function('s:x')   " function('tr') なら E705:


$ vim -u NONE -N
:let Foo#x = function('tr')
E685: 内部エラーです: hash_add()
```

``` vim
" 1. 代入で autoload 発動
let Foo#x = function('tr')


" 2. autoload ファイル名大文字小文字 (windows)
call foo#x()     " => autoload/[Ff]oo.vim
call Foo#x()    " => autoload/[Ff]oo.vim


" 3. exists('*func') の挙動
function G()
endfunction

function s:S()
endfunction

let RefBuiltin = function('tr')
let RefGlobal = function('G')
let RefScript = function('s:S')

echo printf('RefBuiltin = %d', exists('RefBuiltin'))
echo printf('RefGlobal = %d', exists('RefGlobal'))
echo printf('RefScript = %d', exists('RefScript'))
echo printf('*RefBuiltin = %d', exists('*RefBuiltin'))
echo printf('*RefGlobal = %d', exists('*RefGlobal'))
echo printf('*RefScript = %d', exists('*RefScript'))
" RefBuiltin = 1
" RefGlobal = 1
" RefScript = 1
" *RefBuiltin = 1
" *RefGlobal = 1
" *RefScript = 0
```

**Comment by ynkdir** [comment]
バグレポートだしました
https://groups.google.com/d/msg/vim_dev/IGl-wwr7vHY/bJdDExX6NSoJ

とりあえず internal error だけ

**Comment by osyo-manga** [comment]
@ynkdir++

**Comment by h-east** [comment]
TODOリストに入りました。

> Patch to avoid E685 internal error. (Yukihiro Nakadaira, 2014 Jan 1)
> Restore no_autoload?
> Alternative: Avoid no_autoload. (ZyX, 2014 Jan 6)

**Comment by h-east** [comment]
Patch 7.4.149
https://groups.google.com/d/msg/vim_dev/IhVRhvCnJKs/Rn8tFDZLHLMJ

PS
514は別件でした。ごめんなさい。

**Comment by h-east** [comment]
追加。Patch 7.4.154 
https://groups.google.com/d/msg/vim_dev/q6lKeGP8_EQ/2g3pVCiJT04J

**Comment by crazymaster** [comment]
7.4.167 でテストが追加されました
https://groups.google.com/d/topic/vim_dev/dimRBX3R1hI/discussion
