### ISSUE TITLE
UNCパス上のファイルを上書き保存するとReadOnly属性になる

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#510]
7.4.96以降で症状あり。

os_win32.c

``` cpp
/*
 * Get file permissions for "name".
 * Return mode_t or -1 for error.
 */
    long
mch_getperm(char_u *name)
{
    struct stat st;
    int     n;

    if (name[0] == '\\' && name[1] == '\\')
    /* UNC path */
    return (long)win32_getattrs(name); // ① Windows APIのGetFileAttributesの戻り値
    n = mch_stat(name, &st);
    return n == 0 ? (long)st.st_mode : -1L; // ② stat::st_modeの値
}
```

上記の①と②で異なる表現の属性値を返しているので
~~(この条件分岐が必要であれば)~~UNCパスにcdできない不具合に対するパッチでした
win32_getattrs()の戻り値を
st_modeに合わせるて返す必要があると思います。

**Comment by k-takata** [comment]
こんな感じでどうでしょう。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a31d403c9f2c0e62845e83de9e08dd07aef537ea/fix-unc-perm.patch
VCのstat()は、通常のディレクトリの末尾には`\`を付けてはいけないが、ルートディレクトリには（ローカル、UNCともに）末尾に`\`を付けなければならないようです。

**Comment by nocd5** [comment]
自宅なのでローカルの共有フォルダでの確認ですが、
上記パッチで
- ReadOnly属性に変更されなくなった
- UNCのルートパスに`:cd`できる

確認できました:+1:
ありがとうございます！

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/wpSp7PXvgD4/discussion

**Comment by nocd5** [comment]
おつかれさまです。

**Comment by k-takata** [comment]
7.4.136
https://groups.google.com/d/topic/vim_dev/iXsSjxQFHSk/discussion

**Comment by nocd5** [comment]
ありがとうございました
