### ISSUE TITLE
vimの起動時に「マッピングが見つかりませんでした。」というエラーがでる。

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#515]
タイトル通りにvimの起動時に「マッピングが見つかりませんでした。」というエラーがでます。この原因として_vimicが原因であるということはわかるのですが、まだ初心者であるのでコードの読み方が完璧でなくエラー箇所がわかりません。どなたかご教授お願いします。
自分の_vimicのリンクを貼ります
https://www.dropbox.com/s/3dxhhnjhk4q012p/_vimrc

**Comment by h-east** [comment]
ようこそ。vim-jpへ。
~~おそらく原因は 550行目の~~
~~`map! <C-j><plug>(skk-toggle-im)`~~
~~だと思います。~~
~~SKKをNeoBundle等のプラグインマネージャで読み込んでいないのにSKK関連の関数を指定しているからでしょう。~~

``` vim
"map! <C-j><plug>(skk-toggle-im)
```

~~と先頭に `"` を書いてコメントにすれば直ると思います。~~

すいません。説明間違ってました。下のynkdirさんの説明が正しいです。
https://github.com/vim-jp/issues/issues/515#issuecomment-32589185

**Comment by h-east** [comment]
うーん、この _vimrc は有志の方が毎週開催しているvimrc読書会に参加して読んで貰ったほうがいいかもです。
理解が進みますよ:smile:
http://vim-jp.org/reading-vimrc/

**Comment by rhysd** [comment]
こんにちは．
このリポジトリの issue は Vim 本体のバグ報告や要望を議論する場所ですので，質問等は Lingr の vim 部屋でするのが良いと思います．

http://lingr.com/room/vim

**Comment by koron** [comment]
いやべつに何書いてもええですよ。
より適切な場所があるならそちらをその都度紹介すれば良いですから。
今回のように。

**Comment by h-east** [comment]
ラーメン画像貼ってもいいですよ～

**Comment by rhysd** [comment]
@koron 
そうだったんですか．失礼しました．
リポジトリの説明文に

> 有志で既知のバグや要望を検討・管理し、オフィシャルへの還元をしていきます。

とあったので勘違いしていました．指摘ありがとうございます．

**Comment by koron** [comment]
でもvimclip の話題はかんべんな! ＞＜

**Comment by h-east** [comment]
そいえば現状のVimで`マッピングは見つかりませんでした (No mapping found)`がどのファイルのどの行で起きたか表示させる方法ってあるんだろうか？

ない場合、エラー表示にファイル名＆行番号を追加するpatchを書くのは簡単なんだろうか？
(`E492: Not an editor command: ～` の場合はファイル名＆行番号してますね)

あと`Exxx:`の表示がないのはええのん？

**Comment by InoueReo0406** [comment]
皆さん、解答ありがとうございます。

``` vim
map! <C-j><plug>(skk-toggle-im)
```

をコメントアウトさせることによりエラーが解消されました。
ただ最終的な目標、easymotionの起動がいまだ出来ないです。こちらについても教えていただけますか。プラグインのキーの混同とかでは無そうであったので、マッピングが原因かと思いましたが違うようでこまりました。

**Comment by ynkdir** [comment]
`map! <C-j><plug>(skk-toggle-im)`

:help :map_l

{rhs} が指定されてないので、{lhs} で始まるマッピングを表示、しようとしてメッセージがでてます。

**Comment by h-east** [comment]
@ynkdir すんません。それが正解ですね。ありがとうございます。

**Comment by InoueReo0406** [comment]
> ynkdir
> {rhs} が指定されてない

とのことであすがその場合、どうすれば良いのでしょうか。正直な話、何をどうすればよいか呼んでも理解することができません。

**Comment by thinca** [comment]
``` vim
map! <C-j> <plug>(skk-toggle-im)
```

こうすればよいです。`<C-j>` と `<plug>(skk-toggle-im)` の間にスペースがなかったので、全部まとめてキーマッピング元(`{lhs}`) と解釈されていました。

**Comment by Shougo** [comment]
こんにちは。おそらく、

``` vim
map! <C-j> <plug>(skk-toggle-im)
```

とするのが正解です。

マッピングは `:map {lhs} {rhs}` のように指定します。
が、@inouReoさんの.vimrcではスペースがないので `:map {lhs}` の構文と解釈されます。
これは `{lhs}` のマッピングの内容を確認するためのコマンドです。
Vimは `{lhs}` のマッピングを確認しようとしましたが、そのようなマッピングは当然存在しないため、
「マッピングが見つかりませんでした」というメッセージが出たのが真相です。
（かぶった……）

**Comment by InoueReo0406** [comment]
なるほど、そういうことですか、一瞬違いがわかりませんでしたが理解することができました。ありがとうございます。

**Comment by Shougo** [comment]
@InouReo 解決したらcloseしてください。
