### ISSUE TITLE
、や。のマッピング

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#524]
挿入モード時に、や。を, . に置き換えたいのですが以下のようだと上図に置き換わりません。なにが原因なのでしょうか。
inoremap 、 ,
inoremap 。 .

**Comment by k-takata** [comment]
#217 と同件ですかね？

**Comment by InoueReo0406** [comment]
ありがとうございます。
一緒みたいですね。UTF-８の出力の場合は出来ないみたいですね。ありがとうございます。

**Comment by k-takata** [comment]
#217 にも書きましたが、7.4.204で直りました。
