### ISSUE TITLE
vim 突然落ちる現象

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#527]
---

:set encoding=cp932

:echo match('foo', '$', 0, 111111111111111111111111111)

---

Vim: Caught deadly signal SEGV

Vim: Finished.

Segmentation fault

---

7.2 セグフォ落ち。

7.3 セグフォ落ち

7.4 [179] セグフォ落ち

※[パッチ数]

---

 (cygwin ssh)

 centOS release 6.5 (Final) x86_64 x  
./configure --prefix /root/vim74/vim74/src/bin/
make install です

同じ現象の方いらっしゃいましたら。お願いします。

**Comment by Shougo** [comment]
https://github.com/vim-jp/issues/issues/526

おそらくこちらと同じ現象です。さすがに、クラッシュはまずいですね。メモリ破壊が起きているのだと思います。

**Comment by h-east** [comment]
#526 と同根バグです。#526 のpatchで直ることを確認しました。

**Comment by h-east** [comment]
ということでこちらのissueはduplicatedとしてクローズします。
以後は #526 へコメントお願いします。
