### ISSUE TITLE
改行コードCR/LFが条件によって変換されてしまう(?)

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#528]
### 再現手順
1. `let @" = "\n"`
2. `echo strtrans(@")` => "^@"
3. コマンドラインで`<C-r>"` => "^M"
4. `echom getreg('"')` => "^@"

3で何故か結果が変わってしまいます。なにか分かる方いらっしゃったらよろしくお願いします。

(追記: 2,3,4は順不同です。)

**Comment by mattn** [comment]
https://github.com/vim-jp/vim/blob/master/src/ops.c#L1593

変わっているというよりも、コマンドライン上だと改行が表現出来ないという理由で `\r` で強制している、というところでしょうか。

**Comment by mattn** [comment]
あ、意味を取り違えてるな僕

**Comment by ynkdir** [comment]
この説明であってるのかわかりませんが…

実際にレジスタに入ってるのは ^@ でもなく ^M でもなく改行です。

``` vim
:let @" = "\n"
:registers "
--- レジスタ ---
""   ^J
```

^J と表示されてますが 0x0A バイトという意味ではなくもっと抽象的なものです。レジスタの内部表現は行の配列なので ["line1", "line2"] これのカンマみたいなもの。

文字列とレジスタは内部表現が違います。文字列は NUL 終端文字列です。レジスタを文字列に変換すると改行は NL に変換されます。そして、strtrans() は NL を ^@ として表示します。

コマンドラインで `<C-r>"` すると、レジスタの中身は改行なので ^M が入力されます。`<C-V><CR>` と同じです。

**Comment by haya14busa** [comment]
@mattn さん、 @ynkdir さん、解説ありがとうございます

なるほど

##### レジスタの改行:
- CRやLFといった改行コードではなく『改行』というもっと抽象的な物が入っている
- 内部表現: 行の配列

##### 文字列の改行:
- CR(0x0D),LF(0x0A)などを表現できるが、レジスタから文字列に変換された場合は`NL`に変換され、これは`^@`というふうに表示される(`strtrans()`や`echom`など)
- 内部表現: NULL 終端文字列

##### コマンドラインの改行:
- これは`strtrans()`などと違って文字列に変換して出力されているわけではないので(?)、そのまま改行(`^M`)が表示される
- コマンドライン上だと改行が表現出来ないという理由で \r で強制している

という感じですかね...?
ややこしいけどぼんやりわかってきた気がします。もっと勉強しよう。

ありがとうございます!

**Comment by haya14busa** [comment]
閉じ忘れed。改めてありがとうございました
