### ISSUE TITLE
vim-latexの表示について

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#529]
こんにちわ、いつもお世話になっています。以前はvim-latexの質問で本当に助かりました。ありがとうございます。
恥ずかしながらvim-latexについて質問です。自分のvim-latexの表示についてです。数式eqnarrayについての表示なのですが例えば以下の文を打ち込んだとします。

\begin{eqnarray}
    F(f)=\int^{\infty}_{-\infty} f(t)exp(-j2{\pi}t)dt
\end{eqnarray}

すると二文目　\int　や　{\pi} という表示が白く変換して表示されます。これは仕様なのでしょうか。もし仕様であればこの表示方法を治したく(変換させないでただの文字としてvim上で表示)syntaxなどをいじってみたのですがわかりませんでした。
よろしくお願いします。

![snapcrab_noname_2014-2-20_8-44-16_no-00](https://f.cloud.github.com/assets/6427472/2213404/c9645f52-99bf-11e3-8275-53065abfc5a3.jpg)

**Comment by thinca** [comment]
filetypeが `tex` なら、`~/.vim/after/ftplugin/tex.vim` (Windows なら `~/vimfiles/after/ftplugin/tex.vim`)というファイルを作って、

``` vim
setlocal conceallevel=0
```

としてみてください。

**Comment by InoueReo0406** [comment]
ありがとうございます。おかげさまで治すことが出来ました。
このような簡単な設定があることを知りませんでした。1ヶ月ほどこの機能の改善で悩んでいたので本当に助かりました。

**Comment by todashuta** [comment]
これは，vim-latex ではなく vim に付属している tex 用構文ハイライトファイルが原因です。

conceallevel を変えずに

`let g:tex_conceal = ''`

と書いておくことで無効化することもできます。

参考: http://vim-jp.org/vimdoc-ja/syntax.html#g:tex_conceal
