### ISSUE TITLE
--enable-perlinterp=dynamic かつ非 USE_ITHREAD で if_perl がビルド出来ない(was: Perl 5.19 で if_perl がビルドできない)

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#530]
確認した環境
OS: Gentoo Linux 3.8.13
Vim: 7.4.192
Perl: 5.19.8

```
if_perl.xs:389:1: エラー: 不明な型名 ‘perl_key’ です
```

関係あるかわかりませんが、直前で警告も出ています。

```
if_perl.xs:172:0: 警告: "Perl_croak_nocontext" が再定義されました [デフォルトで有効]
/home/thinca/.anyenv/envs/plenv/versions/5.19.8/lib/perl5/5.19.8/x86_64-linux/CORE/embed.h:1818:0: 備考: ここが以前の宣言がある位置です
```

**Comment by mattn** [comment]
windows で 5.16 で動かしてるんですが、5.16 でも perl_key (dll_perl_key) をインポートしなくても動きますね。どの環境が perl_key のシンボル解決しないと動かない環境なんだろ。

**Comment by mattn** [comment]
```
:ver
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 24 2014 15:18:42)
Included patches: 1-192
Compiled by mattn@isokaze
Normal version with X11-Athena GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           -mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
-cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             -rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
-dnd             +modify_fname    +signs           +xfontset
-ebcdic          +mouse           +smartindent     +xim
-emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            -mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_ATHENA     -I/home/ma
ttn/perl519/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim -lXaw -lXmu -lXe
xt -lXt -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -ldl  -lm -ltinfo -lnsl
-ldl   -Wl,-E  -fstack-protector -L/usr/local/lib  -L/home/mattn/perl519/lib/5.1
9.0/x86_64-linux/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lc
```

64bit linux でビルドしてみましたが、ビルドエラーにはなりませんでした。

**Comment by thinca** [comment]
plenv がまずいのかも。何か気を付けないといけないポイントとかってあったりしますか?

**Comment by mattn** [comment]
ローカルインストールなので

```
CFLAGS=-I/home/mattn/perl519 ./configure --enable-perlinetrp して make しました。
```

しました。

**Comment by thinca** [comment]
書いてませんでしたが、 `--enable-perlinterp=dynamic` でビルドしていました。そして色々 mattn さんに試してもらったところ、どうやらこれがビルドコケる条件の模様。

**Comment by mattn** [comment]
https://gist.github.com/mattn/9183235

時間あったら試して下さい。

**Comment by mattn** [comment]
あと、plenv を使ってるのでたぶん perl が libperl.so.5.19.XXXX 形式で出力されないビルド形式になっているかも。`Configure -Duseshrplib`して共有ライブラリ吐いて下さい。

**Comment by mattn** [comment]
https://gist.github.com/9201108
- linux perl 5.14 の --enable-perlinterp=yes (確認済み)
- linux perl 5.14 の --enable-perlinterp=dynamic (確認済み)
- linux perl 5.16 の --enable-perlinterp=yes (確認済み)
- linux perl 5.16 の --enable-perlinterp=dynamic (確認済み)
- linux perl 5.18 の --enable-perlinterp=yes (確認済み)
- linux perl 5.18 の --enable-perlinterp=dynamic (確認済み)
- linux perl 5.19 の --enable-perlinterp=yes (確認済み)
- linux perl 5.19 の --enable-perlinterp=dynamic (確認済み)
- windows perl 5.16 の DYNAMIC_PERL=yes (確認済み)

**Comment by mattn** [comment]
ステータス更新ed

**Comment by k-takata** [comment]
CygwinとLinuxのPerl 5.14では、`dll_PL_thr_key`が無いとdynamicを指定してもスタティックリンクされてしまっていました。余計なシンボルがリンクされていないか、objdump -pで確認しておくと良いでしょう。
https://groups.google.com/d/topic/vim_dev/JEPdD-EMAp4/discussion
それ以降のバージョンは未確認。

**Comment by mattn** [comment]
5.18、5.19 は確認出来たので 5.14、5.16 が確認出来ればいいですかね？

**Comment by mattn** [comment]
ステータス更新 5.16 追加

**Comment by mattn** [comment]
あとは 5.14 か

**Comment by k-takata** [comment]
お疲れ様です。ところでこの2箇所の #ifndef って合ってます？
どちらも DYNAMIC_PERL 用のファンクションテーブルなので、 #ifndef で囲むということは、そもそも要らなかったということになってしまいます。(少なくとも dll_PL_thr_key の方は Perl 5.14では必須なはず。)

``` diff
+#ifndef DYNAMIC_PERL
     {"Perl_croak_nocontext", (PERL_PROC*)&Perl_croak_nocontext},
+#endif
```

``` diff
+# ifndef DYNAMIC_PERL
     {"PL_thr_key", (PERL_PROC*)&dll_PL_thr_key},
+# endif
```

あと気になるのは、Perl 5.19は開発版のはずなので、正式版の5.20が出るまでにどうなるのかという点ですね。

※コメント一部修正。

**Comment by mattn** [comment]
あれ？ Perl_croak_nocontext と PL_thr_key、5.14 から 5.19 まで試したけどどれも必要無かった。これいらんのとちゃう？

**Comment by mattn** [comment]
5.14 も確認終わり。

**Comment by mattn** [comment]
最終的なパッチはこちら

https://gist.github.com/9201108

**Comment by k-takata** [comment]
dynamicリンク時、objdumpでlibperl.soへのリンクが含まれていないことも確認済みでしょうか。

```
$ objdump -p ./vim | grep perl
  NEEDED               libperl.so.5.14
```

7.3.668以降の if_perl.xs の修正でいつの間にか必要なくなった？

**Comment by k-takata** [comment]
本当に、PL_thr_key が不要なら 7.3.668 を revert しても問題ないはずですね。

**Comment by mattn** [comment]
> dynamicリンク時、objdumpでlibperl.soへのリンクが含まれていないことも確認済みでしょうか。

はい。

> 7.3.668以降の if_perl.xs の修正でいつの間にか必要なくなった？

どうなんでしょ。

**Comment by mattn** [comment]
cygwin はちょっと環境そろえれないなー。

**Comment by ynkdir** [comment]
> Perl_croak_nocontext PL_thr_key

perl が -Dusethreads -Dusemultiplicity 付きだと動かない気がします。

``` sh
$ tar xvf perl-5.19.9.tar.bz2
$ cd perl-5.19.9
$ ./Configure -des -Dusedevel -Dcc=gcc -Duseshrplib -Dusethreads -Dusemultiplicity -Dprefix=$HOME/tmp/pl5 && make install
$ cd ~/tmp/pl5/bin
$ ln perl5.19.9 perl
$ export PATH=$HOME/tmp/pl5/bin:$PATH
$ cd ~/tmp/vim
$ ./configure --enable-perlinterp=dynamic && make
$ src/vim -u NONE -N
:perl $curbuf->Append()
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault (コアダンプ)
```

ubuntu ですが vim のリンカオプションに -lperl が付いてるのでビルドが通ってますが-lperl を外すとビルド通らないです。

**Comment by mattn** [comment]
って事は https://github.com/vim-jp/issues/issues/530#issuecomment-35965240 を USE_ITHREADS の ifdef に返ればokかな？

**Comment by mattn** [comment]
こうなってくるともうパズルだな。

**Comment by ynkdir** [comment]
そうですね。Perl_croak_nocontext は PERL_IMPLICIT_CONTEXT で。
完璧にするのは無理そうなのであるていどでいいと思いますが。
dynamic は windows + activeperl が動けば。
if_perl 厳しいですね…。

**Comment by mattn** [comment]
最終パッチ

https://gist.github.com/mattn/9202034

**Comment by k-takata** [comment]
結局、Perlのバージョンではなく、configurationに依存した問題だったということでしょうか。それともバージョンも関係あり？

**Comment by mattn** [comment]
バージョン関係なしです。USE_ITHREADS の時におかしくなるという事でした。

**Comment by mattn** [comment]
タイトル修正done

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/230v4INmTwI

**Comment by k-takata** [comment]
:+1:

> USE_ITHREADS の時におかしくなる

逆ですか？ パッチ前は -Dusethreads 無し(かつUnix系)だとコンパイルが通らなかったのですよね。

**Comment by mattn** [comment]
あー、逆です。英文直してきます。

**Comment by ynkdir** [comment]
Perl_croak_nocontext は USE_ITHREADS じゃなくて PERL_IMPLICIT_CONTEXT じゃないですか

**Comment by mattn** [comment]
あざます。

**Comment by ynkdir** [comment]
GJ!

**Comment by k-takata** [comment]
todo入りしました。

> Can't build Vim with Perl when -Dusethreads is not specified for building
> perl, and building with --enable-perlinterp=dynamic.
> Patch by Yasuhiro Matsumoto, 2014 Feb 24.

**Comment by k-takata** [comment]
7.4.198
https://groups.google.com/d/topic/vim_dev/Ud7oZNZGc5I/discussion
