### ISSUE TITLE
perl5.19.9 の signatures でプロトタイプのsyntaxがエラー色になる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#531]
http://blog.64p.org/entry/2014/02/24/141557

``` perl
sub bar($class, $a, $b = sub(){ warn "foo" }) {
}
```

これが通るので、もはや `$` や `@` だけではパースは不可能。って事で無効にする変数追加。

https://gist.github.com/mattn/9185175

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/IK2YGgYzoco

**Comment by k-takata** [comment]
Perl 5.20が出ましたが、結局これはどうなったんでしょう？
https://github.com/vim-perl/vim-perl にはマージされたが、Vim 本体には取り込まれていない状態でしょうか。

**Comment by mattn** [comment]
パッチは送ってあるのですが、本体マージがまだの様です。
https://github.com/vim-perl/vim-perl/pull/151

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/37c64c78fd87e086b5a945ad7032787c274e2dcb#diff-4c994c396c44b299fda02dd9795815adR368
`let perl_sub_signatures=1` とすればエラーにはならないことを確認。
