### ISSUE TITLE
vimのlatexの書き方　、や。の扱い

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#532]
こんにちわ、いつもお世話になっています。texを使っている皆さんに質問です。自分は論文などをかくとき「、」や「。」（句読点）について「, 」「. 」と書くようにしています。しかし毎回全てを書き終えてから:%sで置換を行っていて非常に不便です。だからinoremapにて「、」や「。」を置換させようと思いましたが過去の質問から、また自分で試した結果無理だとわかりました。皆さんはどのようにしているかお教え下さい。また置換を行える方法やプラグインなどがありましたら教えて下さい。お願いします。

**Comment by h-east** [comment]
私ならIMEの方の設定を変更すると思います。

どうしてもVimでやるなら `InsertCharPre`イベントを使うことになるのかな？

とりあえずサンプル
これ↓を .vimrc (Winなら _vimrc)に書けば、拡張子が .tex の時にお望みの動作になります。

``` vim
augroup filetype_latex
    autocmd!
    autocmd InsertCharPre *.tex call InsertCharReplace()
augroup END

func! InsertCharReplace()
    if (v:char ==# "。")
        let v:char = "．"
    elseif (v:char ==# "、")
        let v:char = "，"
    endif
endfunc
```

プラギン兄さん達＞
間違ってるとこあったら指摘して下さい。

**Comment by osyo-manga** [comment]
tex は使っていないので『わたしならこうするかなー』という提案ですが。
わたしなら置換するコマンドを定義したり保存時に置換するようなスクリプトを書いちゃうかな。

``` vim
" 置換用のコマンドを定義
" 明示的に置換する場合はこのコマンドを呼び出す
command! ReplaceTexDot
\   %s/\./。/g | %s/,/、/g


" filetype が tex の場合に
" バッファを保存する時に自動的に置換する
function! s:filetype_tex()
    augroup filetype-tex
        autocmd! * <buffer>
        autocmd BufWrite * ReplaceTexDot
    augroup END
endfunction

augroup my-group
    autocmd!
    autocmd FileType tex call s:filetype_tex()
augroup END
```

いちいちこういうコマンドを呼び出すのが手間であれば @h-east さんみたいに `InsertCharPre` でゴニョゴニョするのもよいと思います。

**Comment by InoueReo0406** [comment]
お二方、回答ありがとうございます。二人の回答により無事置換を行うことが出来ました。
自分も暇が出来ればvimのプログラミングを勉強していきたいです。
