### ISSUE TITLE
Test 86 and 87 failed with 7.4.193

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#536]
https://travis-ci.org/vim-jp/vim-ci/builds/20349732

7.4.193 以降、travis-ci上でテスト86と87が失敗してました。

[該当パッチ](https://groups.google.com/d/msg/vim_dev/b2TiuZbqwUU/HiZpa1TfYBMJ) を見る限り、Python関連かな?

**Comment by koron** [comment]
コード中のエラーメッセージの文言のtypoが治って
テストのほうでは治ってないってことかしらね?

**Comment by koron** [comment]
直して投げた。

https://groups.google.com/d/msg/vim_dev/b2TiuZbqwUU/AOFwYvJyXkQJ

**Comment by koron** [comment]
あとはヨロ

**Comment by k-takata** [comment]
7.4.195
https://groups.google.com/d/topic/vim_dev/0J1mZqPOPWY/discussion

**Comment by koron** [comment]
パッチ公開から閉じるまでが素早いw

**Comment by k-takata** [comment]
高速クローズ！
