### ISSUE TITLE
vim-over

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#537]
vim-overを使うと以下の現象が起きます。どのように直したらよいでしょうか。
1. vim起動
2. ある文字列に対してsを押す。
3. カーソル上の文字を削除して挿入モードにならない。
4. なにかキーを押す(例えばleft)を押すとsと4で押したキーが同時に実行される。

_vimrc
https://gist.github.com/InouReo/9567961

**Comment by mattn** [comment]
https://github.com/osyo-manga/vim-over/issues

こちらに聞くと良いと思います。

**Comment by haya14busa** [comment]
https://gist.github.com/InouReo/9567961#file-gistfile1-vim-L239

`nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>`

でsキーが潰されているのが原因だとおもいます

**Comment by InoueReo0406** [comment]
お二人かだ、回答ありがとうございます。
このような場合はどのように対処すれば良いのでしょうか。
またnnormapでマップしたspaceでも同じ現象が出ます

**Comment by haya14busa** [comment]
`nnoremap sub {hoge}`などのマップをしてしまうと、`s`を押した時点ではVimデフォルトの`s`をおそうとしているのか`sub`を押す途中なのかわからず、Vimは次の入力を一定時間待ちます。(同様に`subp`というマップも`sub`と干渉してしまいます)

なのでマップなら`<Leader>sub`などといったprefixをつけてコンフリクトしないようにするのが１つの対処方です。

**Comment by InoueReo0406** [comment]
なるほど、そういうことが起こっていたのですね。
親切にありがとうございます。predixをつけることで混同を避けようと思います。

**Comment by Shougo** [comment]
@InouReo 問題が解決したなら、ここを閉じてください。

> https://github.com/osyo-manga/vim-over/issues
> こちらに聞くと良いと思います。

とありますように、プラグイン側にIssuesの報告窓口がある場合はまずそこに報告してください。
