### ISSUE TITLE
if_python3 コンパイル時の警告について

### ISSUE THREAD

**Issue by uakms** [vim-jp/issues#539]
> clang --version
> Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
> Target: x86_64-apple-darwin13.1.0
> Thread model: posix

上記の環境で `--enable-python3interp=yes --with-python3-config-dir=/usr/local/lib/python3.4/config-3.4m` 他オプションにてビルドをすると、下記の警告が(6個)出ます。

```
In file included from if_python3.c:773:
./if_py_both.h:2331:27: warning: incompatible pointer types passing
      'PySliceObject *' to parameter of type 'PyObject *'
      (aka 'struct _object *') [-Wincompatible-pointer-types]
        if (PySlice_GetIndicesEx((PySliceObject *)idx, ListLength(self),
                                 ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/python3.4m/sliceobject.h:43:48: note: passing argument to
      parameter 'r' here
PyAPI_FUNC(int) PySlice_GetIndicesEx(PyObject *r, Py_ssize_t length,
...
```

警告にあるように、`/usr/local/include/python3.4m/sliceobject.h` では

```
PyAPI_FUNC(int) PySlice_GetIndicesEx(PyObject *r, Py_ssize_t length,
                                    Py_ssize_t *start, Py_ssize_t *stop, 
                                    Py_ssize_t *step, Py_ssize_t *slicelength);
```

となっていて、引数の型が(似ているけど)違っているようです。

vim-jp にある vim リポジトリの log を追っていくと 7.4.153 での変更が原因のようで、試しに 7.4.152 にしてビルドをすると警告は出ませんでした。しかしここで、コミットログを見ると Compiler warning for pointer type. となっていて、他の人のコンパイラでは警告が出ないようにするための修正だったようなので謎です。

単に if_py_both.h の idx の部分を (PyObject *) でキャストすれば良かっただけじゃないの？と思い、gist (https://gist.github.com/nakinor/9780409) のように修正してみると警告は出なくなりました。ビルドも最後まで通り、make test も ALL DONE です。

このような変更をしてプログラム的に問題は出ないでしょうか？C 言語は良く知りませんので、Mac を持っている方に教えて頂きたいです。

**Comment by k-takata** [comment]
PySlice_GetIndicesEx でググってみたところ、この関数の第1引数の型は Python 3.1 までは (PySliceObject *) で、3.2 から (PyObject *) になったようですね。

**Comment by mattn** [comment]
また if_perl と同じ道をたどるのか...

**Comment by uakms** [comment]
Mac 関係なかったんですね！
これは ZyX さんに任せよう...

**Comment by uakms** [comment]
プリプロセッサの機能？を使って泥縄式に場合分けしてみましたが、もっとスマートな方法はないでしょうか？

**Comment by k-takata** [comment]
ググってたまたま見つかったプロジェクトの中には (void *) でキャストしているものがありました。
https://gitorious.org/blenderprojects/blender/commit/4a2efef
どっちがいいかというと…どっちでしょうね？

**Comment by k-takata** [comment]
あるいは、こんな感じにして `PySliceObject_T` を使うようにするか。

``` C
#if PY_VERSION_HEX >= 0x030200f0
typedef PyObject PySliceObject_T;
#else
typedef PySliceObject PySliceObject_T;
#endif
```

**Comment by uakms** [comment]
typedef を使うと変更が少なくて済みますし、読みやすくなりました。
でも...別名が増えてしまうのが微妙です。

**Comment by k-takata** [comment]
> でも...別名が増えてしまうのが微妙です。

まあ、しょうがないんじゃないでしょうか。これが最良だと思います。

**Comment by uakms** [comment]
あとは同じ症状の人が現れたら、もしくは Python の各種バージョンをインストールしていて MBA(clang) を持っている人に動作確認をしてもらうのを待つだけですね...。

**Comment by k-takata** [comment]
もう投げちゃっていいんじゃないですか？

**Comment by uakms** [comment]
ずっと奈幾乃でやってきちゃってますので...
typedef のアイデアや引数の型が 3.2 で変更になったという情報は k-takata さんですし、代わりに投稿してもらえませんでしょうか？

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/P5t2Hm_yNj8/2CeY9NyeFU4J
gistへのリンクの形で投げてしまいました。

**Comment by k-takata** [comment]
7.4.228
https://groups.google.com/d/topic/vim_dev/u6cLvkCE-U0/discussion
Bram氏により一部修正が入りました。

**Comment by uakms** [comment]
警告がなくなったのを確認しました。
手続きありがとうございました。
(ところで、Python2 系は関係ないのに if_python.c にも修正が入っているのはなぜなのでしょう？)

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/P5t2Hm_yNj8/MYzYO8W5h04J

> This doesn't work, because PySliceObject_T is used in if_python3.c
> before including if_py_both.h.  I'll move the #if to if_python3.c to
> make it work.

ということなので、if_python.cの方にもtypedefが必要になったようです。

**Comment by uakms** [comment]
なるほど！
複数のファイルを読み込みながらビルドするにはいろいろと調整が必要なのですね。
ありがとうございます。
