### ISSUE TITLE
Vimの開発体制を改善する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#54]
現在のVimは、開発が停滞しています。
実際には、パッチはよく送られるのですが、Bramさんがそれをうまく処理できないためです。
最近todo.txtが膨れあがりすぎています。

一年ちょっとでVimに取リこまれたパッチは330にものぼるので、Bramさん独りで処理している以上しかたありません。というより、これをほとんど一人で回してきた事実が異常です。

これを読むと、Emacsも長い間バザールモデルだったようです。Stallmanが抜けてから体制は変わったようですが。
Vimは完全に伽藍モデルですね。

http://cruel.org/freeware/cathedral.html

このままでは、来年には行われると思われるVim 7.4(8.0)の開発が心配です。
Bramさんに時間がなければ開発ブランチが切れないためです。

最悪はEGCSのようにforkするしかないのですが、できればそれは避けたいところです。
vim-jpの皆さん、良い方法を考えましょう。

個人的には、開発版のブランチを恒久的に用意し、それはBramさんと別の人が管理するべきだと思います。

**Comment by mattn** [comment]
停滞している様に見えますが、実はずっとこの調子です。突然のメジャーバージョンアップで見たこともないコードが突然やってきます。
6.0の時も、7.0の時も、はたまたマイナーバージョンの時もそうでした。

だからこそBramのリーダーとしての地位も確立され、逆にうまく行っていると僕は思ってますね。苦笑

**Comment by Shougo** [comment]
> 突然のメジャーバージョンアップで見たこともないコードが突然やってきます。

それはそれでどうなんですかね……。
つまり、Bramさんが秘密裏にコードを開発していたりするということですよね。

**Comment by mattn** [comment]
> つまり、Bramさんが秘密裏にコードを開発していたりするということですよね。

ずばりそうです。

**Comment by Shougo** [comment]
確かにVim 7のDictionaryや補完ポップアップ、タブ機能はBramさんが実装したような気がしますね。
それができているうちはいいんですけど、それができなくなったらと思うと……。
我々も何かしら対策を考えたほうがよいのかなーと思います。
あらかじめ考えておけば、問題が起こったら、即座に対処できます。

**Comment by crazymaster** [comment]
https://groups.google.com/forum/?fromgroups=&hl=ja#!topic/vim_dev/9tggyPAX7sY
どうやらBramさんはリポジトリを使ったチームメンテナンスに否定的なようだ

**Comment by Shougo** [comment]
VimにもLinuxのような強固なコミュニティ体制ができると良いのですけどね。
複数ブランチを持つようにすれば良いような気もするけど、それには開発者数が足りない。

**Comment by crazymaster** [comment]
[Managing patches - proposal - Google グループ](https://groups.google.com/forum/?fromgroups&amp;hl=ja#!topic/vim_dev/OlkOgDEDAq0)

**Comment by Shougo** [comment]
ふーむ。githubのような開発体制ができると、色々と楽になりそうです。
ただ、Bram氏は保守的なのであまり簡単に移行するとは思えませんが……。

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/OlkOgDEDAq0/gM9_g-lD8bAJ

Bram氏からコメントがあった。

> 1. It shows explicit intent to have the patches included with Vim.  When
>    I download something from the internet I have no idea about copyright or
>    even who wrote it.  It would require going the way of having the author
>    or authors sign a form (on paper, email won't do!).  That gets messy.
> 2. With an emailed diff we both know (the sender and I) what I'm
>    including exactly.  When pulling from some repository I never know what
>    state the change is in.  I sometimes get an email with "try now", but
>    it's not clear what "now" is.
> 
> The current method worked very well for me, I don't see a reason to
> change.
> 
> Note that if people want to distribute (experimental) patches to share
> with other users, then using something like github works very well.

ふむ。Bram氏が現在のやり方を気に入っている以上、移行はやはりありえないようです。
（前も似たようなやり取りがあったな……）

Bram氏にとって、各自がpatchをgithubで管理するというのはアリということですね。それこそvim-jpでやっている作業だと思います。

**Comment by Shougo** [comment]
MarcWeber氏が議論をここにまとめています。

http://vim-wiki.mawercer.de/wiki/vim74/devs-workflows.html

**Comment by Shougo** [comment]
https://groups.google.com/forum/#!topic/vim_dev/PI2JuAmkvXs

Bram氏はZimbu推しのようです。
VimがZimbuで書きなおされる時がくる……？

**Comment by Shougo** [comment]
あのあと議論が進んで、数年は書きなおされる可能性は無さそうです。
ただ、Vimの一部をZimbu化する可能性はあるみたいです。
Bram氏の考え（互換性、移植性、速度）を全て満たすのは私もZimbuくらいしか思いつかないので、Vimが別の言語で書きなおされるならZimbuしかないのでしょう。

ひょっとするとLuaというウルトラCがあるかもしれませんが……。

**Comment by mattn** [comment]
Bramのメールのくだりの Zimbu の部分は Joke だと思ってたけどw

**Comment by Shougo** [comment]
Jokeだったんですか……。ひさしぶりにZimbuの話題があったので。

**Comment by k-takata** [comment]
Vim development process is utterly broken
https://groups.google.com/d/topic/vim_dev/PoyfCcO-HG0/discussion

**Comment by Shougo** [comment]
Oh……。また荒れそうな話題が。

**Comment by k-takata** [comment]
improving Vim - Kickstarter - brainstorming - goals - who wants to join?
vim_use: https://groups.google.com/d/topic/vim_use/IKha1xx6V8Y/discussion
vim_dev: https://groups.google.com/d/topic/vim_dev/IKha1xx6V8Y/discussion

**Comment by koron** [comment]
( ´Д｀)=3

**Comment by Shougo** [comment]
https://groups.google.com/d/msg/vim_dev/IKha1xx6V8Y/tfHDcVcU0Y8J

> I do think that C is an old language and writing high level code in it
> is tough.  Especially when it needs to be portable.  A possible way out
> is to write code in Zimbu, which compiles into C, so that parts can be
> (re)written in Zimbu while still using existing code in C.  But Zimbu
> isn't ready yet... 

Bram氏がいまだにVimをZimbuで書きなおす気満々の件について

**Comment by k-takata** [comment]
おかしいな、誰も貼ってないなんて。
Neovim
https://groups.google.com/d/topic/vim_dev/x0BF9Y0Uby8/discussion

そして、日本語で言うところの縁起でもない…
Bram, if you got hit by a bus tomorrow..
https://groups.google.com/d/topic/vim_dev/h8AL-n8rWIQ/discussion

**Comment by mattn** [comment]
まず病院に行きますね

**Comment by Shougo** [comment]
> おかしいな、誰も貼ってないなんて。

貼ろうかと思ったんですが、そういえば忘れてました。

**Comment by k-takata** [comment]
Vim development model
https://groups.google.com/d/topic/vim_dev/m1RMplyIbug/discussion

**Comment by koron** [comment]
起票時から状況が変わったので整理します。
時系列は考慮していません。

まず github に移りました。
そしていまではCIが回っています。
さらに現在はパッチリリースも相当に活発です。
相変わらず、チャレンジングなパッチに対しても開発ブランチは切られません。

徐々にではありますが、体制は改善されていますし、
本issueは明確なゴールが設定されていませんでしたので
現時点をゴールとみなして fixedで閉じます。

開発ブランチの導入については別 issue を建てます。
