### ISSUE TITLE
help に *String* タグがない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#541]
`*Number*` `*Float*` `*Funcref*` `*List*` `*Dictionary*` はあるんですが、`*String*` がないです。あった方が良い気がします。

**Comment by thinca** [comment]
取り急ぎ備忘のために登録。

**Comment by crazymaster** [comment]
``` diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 78237ec..74a6c2f 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -47,7 +47,7 @@ Float     A floating point number. |floating-point-format| *Float*
        Examples: 123.456  1.15e-6  -1.1e3

 String     A NUL terminated string of 8-bit unsigned characters (bytes).
-       |expr-string| Examples: "ab\txx\"--"  'x-z''a,c'
+       |expr-string| *String* Examples: "ab\txx\"--"  'x-z''a,c'

 Funcref        A reference to a function |Funcref|.
        Example: function("strlen")
```

**Comment by mattn** [comment]
Post it to vim-dev please

**Comment by crazymaster** [comment]
Posted
https://groups.google.com/d/msg/vim_dev/kz4-pbCiURs/0hgLMp35AOUJ

**Comment by crazymaster** [comment]
修正は入りましたが、7.4.250の後のコミットでタグが追加されました。
https://code.google.com/p/vim/source/detail?r=755931e042e41a3331380adc74a8a912c234c354

**Comment by crazymaster** [comment]
あ、`*string*`は入ったけど`*String*`が入ってなかった。
ref. vim-jp/vital.vim#266

**Comment by crazymaster** [comment]
https://groups.google.com/d/msg/vim_dev/iXy9-kB1ZoM/dkv1HWP9rxYJ

**Comment by h-east** [comment]
↓のどさくさに紛れて入りました。 @crazymaster :+1: 
https://groups.google.com/d/msg/vim_dev/l_re7ENamB4/5V45z_crCwkJ

https://github.com/vim-jp/vim/commit/77fa9def63e00655be190553145c73207bbd113a#diff-bea881dfa9626bab7141337b0fcdb23eR1008
