### ISSUE TITLE
cwについて

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#542]
ノーマルモードのcwはカーソル位置の単語を削除して挿入モードを開始とあるサイトでは書いてありました。しかし、自分のvimでは以下のような操作になります。これは自分のvimrcがおかしいのでしょうか。
1. vim起動
2. 以下の文字がかいてあるファイルを開く
   
   above
3. カーソルをノーマルモードにてoに置く
4. cwを入力
5. 以下のようになる
   
   ab

自分はカーソルが単語上のどこにいてもそのカーソル上の単語を削除して挿入モードに入るという機能だと思っているのですがどうなのでしょうか。またそのような機能はありますか？

**Comment by koron** [comment]
> カーソルが単語上のどこにいてもそのカーソル上の単語を削除して挿入モードに入るという機能だと思っている

@InouReo さんの認識が間違ってます。

cw は c+w です。
c は「現在のカーソル位置から、次に移動した場所までの文字を削除し、挿入モードを開始する」機能です。
そして「w は次の単語の先頭へ移動する」です。
なので cw は「カーソルから単語の末尾までを削除し、挿入モードを開始する」になります。

> カーソルが単語上のどこにいてもそのカーソル上の単語を削除して挿入モードに入る

これをやりたいなら ciw もしくは caw を使ってください。
これは c+aw で、awによりcの意味が先に上げたのと少し変わって
望みどうりの動作ができるでしょう。

**Comment by k-takata** [comment]
`cw` はカーソル位置から現在の単語の末尾までを削除して挿入モードを開始しますのでその動作で正しいです。

> またそのような機能はありますか？

[テキストオブジェクト](http://vim-jp.org/vimdoc-ja/motion.html#text-objects)というものがあります。`ciw` で現在の単語を削除して挿入モードに入ります。`caw` で前後の空白も含んで単語を削除して挿入モードに入ります。

---

ぜひ `:help` の読み方をマスターしましょう。今回まず見るべきなのは [`:help c`](http://vim-jp.org/vimdoc-ja/change.html#c) です。

> {motion} のテキストを [レジスタ x にいれ] 削除し、挿入を始める。

[`{motion}`](http://vim-jp.org/vimdoc-ja/intro.html#{motion}) について知りたければ、カーソルをそこに持って行き、`Ctrl+]` を押すとその項目にジャンプします。（`Ctrl+O`で戻る。）

> カーソル移動コマンド。これらは、|motion.txt| で説明されています。

ということですので、`|motion.txt|` にカーソルを持って行き`Ctrl+]`を押せば、[詳細な説明](http://vim-jp.org/vimdoc-ja/motion.html)が読めます。
後は、[`w`](http://vim-jp.org/vimdoc-ja/motion.html#w)の項目を読めば、`cw`が分かるはず…と言いたいところですが、実は`cw`は特別で、[`:help cw`](http://vim-jp.org/vimdoc-ja/change.html#cw) も見ておく必要があります。

> 特別な場合: "cw" と "cW" は、カーソルが単語の上にあるとき、単語のあとにつづく
> 空白を含めず、単語の末尾までを変更する("ce" と "cE" と同じ働きをする)。

ということで、仕様通りの動作だということが分かります。

**Comment by InoueReo0406** [comment]
回答ありがとうございます。
vimの使い方についてまだまだ至らぬ点が多いみたいです。helpを参照しながら理解を深めていきたいです。
