### ISSUE TITLE
7.4.227 「options」コマンド実行後エラー発生

### ISSUE THREAD

**Issue by fantaro** [vim-jp/issues#543]
7.4.227にアップデートしたところ、コマンドモードで「options」を実行後エラーが発生してしまいます。

エラー情報：
E118：関数の引数が多過ぎます：<SNR>47_OptionL

エラー発生するファイル：
optwin.vim

**Comment by crazymaster** [comment]
7.4.201での変更が原因ですね
https://github.com/vim-jp/vim/commit/2817291f942ff7a44a3b9ec868782b31ffb8a8b6#diff-1

**Comment by crazymaster** [comment]
``` diff
diff --git a/runtime/optwin.vim b/runtime/optwin.vim
index 89ebe26..2668438 100644
--- a/runtime/optwin.vim
+++ b/runtime/optwin.vim
@@ -855,7 +855,7 @@ if has("lispindent")
   call append("$", "\t(local to buffer)")
   call <SID>BinOptionL("lisp")
   call append("$", "lispwords\twords that change how lisp indenting works")
-  call <SID>OptionL("lw", &lw)
+  call <SID>OptionL("lw")
 endif


```

**Comment by mattn** [comment]
Post it to vim-dev please

**Comment by crazymaster** [comment]
Posted
https://groups.google.com/d/msg/vim_dev/AXWalJt-RNQ/QV0y-Rg9m44J

**Comment by crazymaster** [comment]
7.4.230で入りました
https://groups.google.com/d/topic/vim_dev/wJlVtKq3FpA/discussion

**Comment by crazymaster** [comment]
7.4.231でテストが追加
https://groups.google.com/d/topic/vim_dev/p2P71KYGgug/discussion

**Comment by fantaro** [comment]
@crazymaster 
ありがとうございました。
