### ISSUE TITLE
os_unix.c:2818にて型修飾子が間違っている。

### ISSUE THREAD

**Issue by mopp** [vim-jp/issues#544]
> static const char const *smack_copied_attributes[] = ...

のようになっており

> static const char \* const smack_copied_attributes[] = ...

だと思われます。
パッチ 7.4.238
https://groups.google.com/forum/?hl=ja&fromgroups#!searchin/vim_dev/const%7Csort:date/vim_dev/hFEBIaGFq9E/negM6YrluqMJ
で追加されたようです。

些細なことかもしれませんが
ここに投稿してみたかったので報告です。

**Comment by raa0121** [comment]
https://github.com/vim-jp/vim/commit/f677ba718ddf454fd2c1284a3a4d6d234e68bc6a#diff-b68adb4fa34020d8d7f0ab40a2704335R2818
git 的にはここですね
というか、Cはよくわかってないんですが、const って2回出てきていいんですかね？

**Comment by thinca** [comment]
文脈読んでないので型修飾子が間違っているかはわからないですが、const が2回出てくるのは問題ないです。ポインタ自体に対する const と、ポインタが指している先に対する const ですね。

**Comment by mopp** [comment]
ポインタの指す型に対するconstとポインタ変数自体のconstがあるので
ポインタを使うときは2つ出てきて大丈夫です。

**Comment by mattn** [comment]
VC?

**Comment by mattn** [comment]
よくわかりませんが、issue closeしてよい話です？

**Comment by mopp** [comment]
環境はarch linuxでclangです。

**Comment by rhysd** [comment]
> > static const char const *smack_copied_attributes[] = ...

そこに const を2つ付けるのは本来は駄目で，おそらく警告は出ますがコンパイルエラーにはならなかった気がします．多分実害は出ていないのだと思いますが，`smack_copied_attributes` は今は意図せず書き換え可能な状態になっています．

**Comment by ynkdir** [comment]
報告しました
https://groups.google.com/d/msg/vim_dev/L8hxDNVFfC0/Hn1_9KsWEkYJ

**Comment by mopp** [comment]
ありがとうございます！

**Comment by k-takata** [comment]
7.4.259で直りました。
https://groups.google.com/d/topic/vim_dev/G3NwcISmQ40/discussion
