### ISSUE TITLE
gvim on Linux で f の後に日本語を指定できない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#546]
どうやら IM から来る未確定文字の入力 を1文字として認識し
それを検索してしまってる。

f だけでなく t など、1文字の入力を受け取る系は全部そうなってるハズ。

**Comment by koron** [comment]
既出な気がしたけど、とりあえず入れておきます。
そうなら閉じてください。

**Comment by k-takata** [comment]
8.0.1026で直ったはず。
