### ISSUE TITLE
set nocompatibleしてある環境で:sだけ実行するとSEGV

### ISSUE THREAD

**Issue by ryo7000** [vim-jp/issues#549]
``` vimrc
set nocompatible
```

vim -u .vimrc.testで起動して、:sするとSEGVします。

gdbで見たところ、ex_cmds.c:4428

``` c
if (STRCMP(pat, "\\n") == 0 && STRLEN(pat) == 2
```

で止まっており、patがNULLのようでした。
この部分が入ったのが、7.4.232のようです。

追う余裕がないので、とりあえずここで報告だけさせて頂きます。

**Comment by mattn** [comment]
ex_cmds.c:4428 にその様なコードが無いのですが、どのバージョンのコードでしょうか？

**Comment by ryo7000** [comment]
vim-7.4.244で試したのですが、245ですでに修正入っていました。
先に最新をチェックすべきでした、すみません。
修正されているので、Closeさせて頂きます。
