### ISSUE TITLE
neobundleのインストール

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#550]
こんにちわ、いつもお世話になっています。
今回、Neobundleをインストールを行おうとしたところ、以下のエラーが出ました。
"git" command is not installed,
このような場合、どのように解決すればよいでしょうか。

自分がやったこととしては
Gitのインストール
.vimフォルダ以下にbundleフォルダを作成
git bushにて以下のコマンドの実行
　$ mkdir -p ~/.vim/bundle
　$ git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

です。よろしくお願いします。
https://gist.github.com/InouReo/10572436

**Comment by raa0121** [comment]
PATH に git の場所を通すか、git bash から vim を起動してください
エラーはその名の通り、PATH の中に git コマンドが無いということです

**Comment by InoueReo0406** [comment]
git bash から vim を起動で解決することが出来ました。
ありがとうございます。

**Comment by InoueReo0406** [comment]
gitよりvimを実行、:NeoBudneInstallでインストールをしようとしたのですが以下のエラーのためインストール出来ません。これはプロキシのエラーですかね。
^@fatal: unable to connect to github.:^@github.com[0: 192.30.252.131]: errno=No error

**Comment by Shougo** [comment]
neobundleの作者です。このIssueに関しては、ここではなく neobundle のほうに立ててください。

> gitよりvimを実行、:NeoBudneInstallでインストールをしようとしたのですが以下のエラーのためインストール出来ません。これはプロキシのエラーですかね。

そもそも git cloneが正常に実行できるかを試してください。
その git が https に対応していない可能性はあります。httpsに対応していない場合、gitプロトコルを用いる必要があります（デフォルトはhttpsプロトコル）。

``` vim
let g:neobundle#types#git#default_protocol = 'git'
```
