### ISSUE TITLE
tabedit での :mksession! が不正

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#551]
tabedit をしている状態から :mksession! で出力される不正な Session.vim の内容を最小限にしたコードです。

```
edit Makefile
exe 10
normal! zt
20
tabnew
tabnext 1
```

Makefile を開き、行番号 10 に飛び、その行を画面最上部に移動、行番号 20 までカーソルを移動、タブを開き、元の画面に戻る

という動作ですが、tabnew があると Makefile のスクロール位置が狂います。なければ期待通りの位置になります。

**Comment by ghost** [comment]
上記症状の修正パッチです。

``` diff
diff -r 94df797ed6b0 src/ex_docmd.c
--- a/src/ex_docmd.c    Sat Apr 12 13:12:24 2014 +0200
+++ b/src/ex_docmd.c    Wed Apr 16 01:44:06 2014 +0900
@@ -10868,17 +10868,13 @@

    /* Restore the cursor line in the file and relatively in the
     * window.  Don't use "G", it changes the jumplist. */
-   if (fprintf(fd, "let s:l = %ld - ((%ld * winheight(0) + %ld) / %ld)",
-           (long)wp->w_cursor.lnum,
-           (long)(wp->w_cursor.lnum - wp->w_topline),
-           (long)wp->w_height / 2, (long)wp->w_height) < 0
-       || put_eol(fd) == FAIL
-       || put_line(fd, "if s:l < 1 | let s:l = 1 | endif") == FAIL
-       || put_line(fd, "exe s:l") == FAIL
-       || put_line(fd, "normal! zt") == FAIL
-       || fprintf(fd, "%ld", (long)wp->w_cursor.lnum) < 0
-       || put_eol(fd) == FAIL)
-       return FAIL;
+        if (fprintf(fd, "exe %ld", (long)wp->w_topline) < 0
+                || put_eol(fd) == FAIL
+                || put_line(fd, "normal! zt") == FAIL
+                || fprintf(fd, "%ld", (long)wp->w_cursor.lnum) < 0
+                || put_eol(fd) == FAIL)
+            return FAIL;
+
    /* Restore the cursor column and left offset when not wrapping. */
    if (wp->w_cursor.col == 0)
    {
diff -r 94df797ed6b0 src/window.c
--- a/src/window.c  Sat Apr 12 13:12:24 2014 +0200
+++ b/src/window.c  Wed Apr 16 01:44:06 2014 +0900
@@ -5748,10 +5748,11 @@
        wp->w_wrow -= sline;
        }
    }
-   set_topline(wp, lnum);
-    }
-
-    if (wp == curwin)
+        if (sline != 0)
+            set_topline(wp, lnum);
+    }
+
+    if (wp == curwin && sline != 0)
     {
    if (p_so)
        update_topline();
```

こうなりました。

**Comment by ghost** [comment]
一週間程度、運用して様子を見ます。

**Comment by ynkdir** [comment]
簡単にですが動作確認しました。
GJ!

**Comment by ghost** [comment]
どうも遅れました。

このパッチは二つの同様な不具合をパッチする用を成しています。今思えば分割すべきでした。

ex_docmd 部は巨大なファイルの場合計算式の端数が出る関係で画面上端に来る行が一行下にずれる症状を改善し、
window 部は tabnew を利用した際にカーソル行の数値が入った変数が加工されずに画面上端として適用されてしまう間違いを修正します。

今回、「一行下に必ずずれる」条件を明確にできず説得力が発生しなかったので ex_docmd 部のパッチ提出は条件が確定できるまで見送ります。

window 部の方を先に提案してきます。

**Comment by ghost** [comment]
https://groups.google.com/forum/#!topic/vim_dev/xSwp1kRbb9Q

**Comment by mattn** [comment]
Merged on 7.4.280 https://groups.google.com/forum/#!topic/vim_dev/SSh39M2sRos

**Comment by ghost** [comment]
微妙で重要な修正：

``` diff
diff -r 32de51778c27 src/window.c
--- a/src/window.c  Tue May 13 20:23:24 2014 +0200
+++ b/src/window.c  Sat May 17 21:09:55 2014 +0900
@@ -5748,7 +5748,7 @@
        lnum++;
        wp->w_wrow -= line_size + sline;
        }
-       else if (sline > 0)
+       else if (sline >= 0)
        {
        /* First line of file reached, use that as topline. */
        lnum = 1;
```

https://groups.google.com/d/msg/vim_dev/SSh39M2sRos/GIUiXCiBTJAJ

**Comment by k-takata** [comment]
7.4.301
https://groups.google.com/d/topic/vim_dev/XsTSXryCZqI/discussion

**Comment by crazymaster** [comment]
7.4.301 でエンバグしてしまったようです。
再現方法：
1. 適当なファイルを開き、ある程度スクロールする
2. `:help` を実行する
3. 開いていたファイルが最初の行に移動してしまう。

**Comment by ghost** [comment]
把握しました。
sline == 0 のときの処理を今のスコープに乗っけたのが敗因なのかな…。
修正に入ります。

**Comment by crazymaster** [comment]
補足

> 最初の行に移動してしまう。

表示位置がファイルの最初の行にずれるという意味です。
ちなみにhelp画面を閉じたり、フォーカスを移したりすると元の行に戻ります。

**Comment by crazymaster** [comment]
あと、当然ですが垂直分割では起きません。

**Comment by h-east** [comment]
fedora19にssh接続しているPuTTY(端末サイズ**80x24**)上のCUI Vim で確認

``` sh
$ cd (vimのソース展開フォルダ)/src
$ vim -N -u NONE -i NONE --noplugin -c "set helpheight=12" Makefile
```

`[Enter]`はリターンキーを叩くってことね

``` vim
/Rem[Enter]
zb
:help[Enter]
```

Vim 7.4.131
- `# (*)  Remarks: {{{`の行が下のWindowの最下行に表示されている。←OK
- `<C-W>w`しても最下行。←OK
- `<C-W>t<C-W>q`してヘルプWindowを閉じても最下行。←OK

Vim 7.4.307
- 下のWindowはMakefileの1行目から表示されている。(Remarksの行が表示されていない)←NG1
- `<C-W>w`するとWindowの真ん中に`# (*)  Remarks: {{{`の行が表示される。←NG2
- `<C-W>t<C-W>q`してヘルプWindowを閉じてもWindowの真ん中に`# (*)  Remarks: {{{`の行が表示される。←NG2

NG1とNG2は同根ではなさそうな気がします。

**Comment by ghost** [comment]
このIssueで最初に出したパッチがそのままの形では通らなかったので、形を変えたこのパッチが通るのかはわかりませんが、とりあえず当該現象は改善したように思います。

``` diff
diff -r 54d96e3b2eec src/window.c
--- a/src/window.c  Thu May 22 21:22:19 2014 +0200
+++ b/src/window.c  Sat May 24 11:21:45 2014 +0900
@@ -5710,8 +5710,9 @@
            --wp->w_wrow;
        }
        }
+            set_topline(wp, lnum);
    }
-   else
+   else if (sline > 0)
    {
        while (sline > 0 && lnum > 1)
        {
@@ -5748,14 +5749,15 @@
        lnum++;
        wp->w_wrow -= line_size + sline;
        }
-       else if (sline >= 0)
+       else if (sline > 0)
        {
        /* First line of file reached, use that as topline. */
        lnum = 1;
        wp->w_wrow -= sline;
        }
+
+            set_topline(wp, lnum);
    }
-   set_topline(wp, lnum);
     }

     if (wp == curwin)
```

**Comment by h-east** [comment]
vim_devにも不具合報告がありました。
https://groups.google.com/d/msg/vim_dev/ZVCxFLGZFKQ/5p5CHkFyiaUJ

**Comment by h-east** [comment]
@ntak そのpatchで改善されているようなのでvim_devに投げちゃっていいんじゃないでしょうか。

**Comment by ghost** [comment]
投げました：
https://groups.google.com/d/msg/vim_dev/ZVCxFLGZFKQ/K8P7VHhJXRsJ

vim_dev の方で少し議論になりそうな予感はします。

**Comment by h-east** [comment]
:+1:

**Comment by k-takata** [comment]
7.4.309
https://groups.google.com/d/topic/vim_dev/SMvgZ2JFEYQ/discussion

**Comment by ghost** [comment]
テストをどうにも書きようがない部類のパッチだということがうっすら伝わったのかもしれない…

**Comment by h-east** [comment]
私の再現手順(https://github.com/vim-jp/issues/issues/551#issuecomment-44075329) をベースにして、'lines'の値によって'helpheight'オプションの値を変えるようにすれば対応可能かと思います。

**Comment by h-east** [comment]
または、

``` vim
:3wincmd s
や
:5sp
```

のようにWindow分割時に('lines'の値に応じた)新しいWindowの高さを指定するとかですかね。

---

追記
初っ端に'lines'の値によって'cmdheight'オプションの値を変えるのが楽かもです。

**Comment by h-east** [comment]
test107を作ってvim_devに送りました。
https://groups.google.com/d/msg/vim_dev/ZVCxFLGZFKQ/MZSNBnDC_ksJ

私が上に書いてることとまったく違う内容になっちゃったけど:sweat: これでいける筈。

**Comment by ghost** [comment]
ありがとうございます、そっちから攻めればよかったんですね…いやはや手のつけようがなかったので eval.c とにらめっこしたり色々やってはみたんです、やっぱり一つこと(:tabnew)にこだわってしまうのは歳か…

**Comment by k-takata** [comment]
7.4.315
https://groups.google.com/d/topic/vim_dev/tLIBN8_ko5w/discussion

**Comment by crazymaster** [comment]
関係者各位、お疲れ様でした :+1:
