### ISSUE TITLE
Chrome からのファイル D&D で内部エラー E341

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/issues#552]
google chrome でファイルをダウンロードすると以下の画像のような、ダウンロード一覧の枠がウィンドウ下部に表示されます。
![chromefile](http://i.imgur.com/2RtNYX4.png)
ここからファイルをドラッグするなどして操作できますが、このファイルを Vim にドラッグして開こうとすると `E341: 内部エラー: lalloc(0,)` となります。
`chrome://downloads/` で開けるダウンロード一覧からのドラッグでも同様でした。

環境： 
Windows8
Vim 7.4 253 64bit GUI 版 Huge 版 With GUI.
Google Chrome バージョン 34.0.1847.116 m

以下のバージョンを確認 (Google Chrome バージョン 35.0.1916.69 beta-m に更新)
## 32bit 版

いずれのバージョンでも問題なし (再現せず)。
- 7.4.227、7.4.265 (VS2013 ビルド)
- 7.4.264 ([VS2010](http://tuxproject.de/projects/vim/))
- 7.4.227 (Kaoriya 版 Vim)
## 64bit 版

以下のバージョンで再現。
- 7.4.227、7.4.265 (7.4.VS2013 ビルド)
- 7.4.265 ([VS2013](https://bintray.com/veegee/generic/vim_x64/view/files))

以下のバージョンで再現せず
- 7.4.227 (Kaoriya 版 Vim)

**Comment by raa0121** [comment]
Windows8 Kaoriya Vim 7.4 227 GUI 版 Huge 版 With GUI. 
では `chrome://downloads/` からのDnDで開けました…
Google Chrome バージョン 35.0.1916.47 beta-m

**Comment by 0xBADDCAFE** [comment]
うちでも Kaoriya Vim 7.4 227 で試したところ開けました。
ちょっと原因がわからない為、また何か分かれば報告します。

**Comment by 0xBADDCAFE** [comment]
https://bintray.com/veegee/generic/vim_x64/view/files

こちらのバイナリをお借りして 7.4.265 64bit  でテストしたところ再現しました。
Chrome のバージョンも raa さんに試していただいた環境に寄せてベータアップデートし、バージョン 35.0.1916.69 beta-m を使用しましたが再現しました。
また、バージョンの差異も考慮し、7.4.227 64bit をビルドし試してみましたが、再現しました。
複雑になるのでまとめると、以下のようになっています。

## 32bit 版

いずれのバージョンでも問題なし (再現せず)。
- 7.4.227、7.4.265 (VS2013 ビルド)
- 7.4.264 ([VS2010](http://tuxproject.de/projects/vim/))
- 7.4.227 (Kaoriya 版 Vim)

## 64bit 版

以下のバージョンで再現。
- 7.4.227、7.4.265 (7.4.VS2013 ビルド)
- 7.4.265 ([VS2010](https://bintray.com/veegee/generic/vim_x64/view/files))

以下のバージョンで再現せず
- 7.4.227 (Kaoriya 版 Vim)

いずれも環境は Windows8、Google Chrome バージョン 35.0.1916.69 beta-m です。

**Comment by h-east** [comment]
@0xBADDCAFE 切り分けお疲れ様です。
再現する環境でVisual Studioでデバッグ実行させた場合でも再現しますか？
再現する場合、`E341`を出力している箇所(*1)にブレークポイントをセットしデバッグ実行して再現させてブレークした時のバックトレース(関数コールスタック)の情報を教えて下さい。

*1 src/misc2.c : 894行目辺り

``` c
EMSGN(_("E341: Internal error: lalloc(%ld, )"), size);
```

**Comment by 0xBADDCAFE** [comment]
確認したところ、デバッグ実行でも再現しました。
これで情報が足りているかわかりませんが、とってみました。

https://gist.github.com/0xBADDCAFE/920ced41cb439696af1d#file-callstack-txt

**Comment by k-takata** [comment]
`_OnDropFiles()` のこの部分ですが、

``` C
    UINT    cFiles = DragQueryFile(hDrop, DRAGQVAL, NULL, 0);
```

ドロップされたファイル数を`cFiles`に取得しているのですが、なぜか0になっているということでしょうかね？
enc=utf-8 と cp932 の場合で動作が変わったりしますか？（あまり関係なさそう）

**Comment by h-east** [comment]
ありがとうございます！

ファイルをドロップされたのでWindowsメッセージが発生して
`_OnDropFiles()` [src/gui_w48.c] が呼ばれたのに、
3699行目でドロップされたファイル数を調べたら `0` ！？なぜ？

``` c
UINT    cFiles = DragQueryFile(hDrop, DRAGQVAL, NULL, 0);
```

その `0` を使ってメモリ確保しようとして件のメッセージが出力されています。

``` c
fnames = (char_u **)alloc(cFiles * sizeof(char_u *));
```

スーパーWindowsプログラマ＞
ファイルドロップイベント発生しといてドロップファイル数 `0` ってあり得るんです？
ドロップファイル数取得時の`DragQueryFile`は`DragQueryFileW`にしなくて良い？

**Comment by h-east** [comment]
あっ、かぶった:smile:

**Comment by h-east** [comment]
@0xBADDCAFE src/gui_w48.c : 3699行目の`DragQueryFile`を`DragQueryFileW`に変更して動作確認をお願いします。

``` c
UINT    cFiles = DragQueryFileW(hDrop, DRAGQVAL, NULL, 0);
```

**Comment by mattn** [comment]
http://msdn.microsoft.com/ja-jp/library/cc422048.aspx

```
iFile
問い合わせ対象のファイルのインデックス番号を指定します。0xFFFFFFFF（言い換えると -1）を指定すると、DragQueryFile は、ドロップされたファイルの総数を返します。0～ドロップされたファイルの総数未満のいずれかの値を指定すると、DragQueryFile は、lpszFile パラメータが指すバッファに、その値に対応するファイルの名前を格納します。
```

L3690

``` c
# define DRAGQVAL 0xFFFFFFFF
```

これ64bit UINTで-1なんだっけ

**Comment by mattn** [comment]
``` c
(UINT)-1
```

の方が安全な気がする。

**Comment by k-takata** [comment]
> これ64bit UINTで-1なんだっけ

64bit環境でもUINTは32bitなので大丈夫なはず。

**Comment by 0xBADDCAFE** [comment]
> @0xBADDCAFE src/gui_w48.c : 3699行目のDragQueryFileをDragQueryFileWに変更して動作確認をお願いします。

試してみましたが変わらずでした。

https://gist.github.com/0xBADDCAFE/588bcd264f3be9203b58#file-callstack2-txt

> enc=utf-8 と cp932 の場合で動作が変わったりしますか？（あまり関係なさそう）

こちらも試しましたが変化なしでした。ちなみにこれまでの環境は全て Windows 上デフォルトで試しているので、`enc=cp932` の環境での結果です。

あとこの Chrome から D&D しているファイルは、エクスプローラなどから Vim に投げ込むとエラーせずに普通に開けるというもの (数ファイル試験済) で、Chrome 側の渡し方が不正なのかというのもあるかもしれません。
ファイルのパスはいずれも 256 字以下、スペースを含まないアルファベット・アンダースコアのみの文字です。

**Comment by k-takata** [comment]
少し試したのですが、OSも違うためか再現しませんでした。
Windows 7
Google Chrome 34.0.1847.131 m
Vim 7.4.273 (VS2010, 独自パッチ無し)
https://bintray.com/veegee/generic/vim_x64/view/files の 7.4.265 でも再現せず。
ファイルのURLなどは関係ありますか？

**Comment by mattn** [comment]
いちど -1 を直値で渡してみてもらえますか

On 5/2/14, 0xBADDCAFE notifications@github.com wrote:

> > @0xBADDCAFE src/gui_w48.c :
> > 3699行目のDragQueryFileをDragQueryFileWに変更して動作確認をお願いします。
> 
> 試してみましたが変わらずでした。
> 
> https://gist.github.com/0xBADDCAFE/588bcd264f3be9203b58#file-callstack2-txt
> 
> > enc=utf-8 と cp932 の場合で動作が変わったりしますか？（あまり関係なさそう）
> 
> こちらも試しましたが変化なしでした。ちなみにこれまでの環境は全て Windows 上デフォルトで試しているので、`enc=cp932`
> の環境での結果です。
> 
> あとこの Chrome から D&D しているファイルは、エクスプローラなどから Vim に投げ込むとエラーせずに普通に開けるというもの
> (数ファイル試験済) で、Chrome 側の渡し方が不正なのかというのもあるかもしれません。
> ファイルのパスはいずれも 256 字以下、スペースを含まないアルファベット・アンダースコアのみの文字です。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/552#issuecomment-41947772

## 
- Yasuhiro Matsumoto

**Comment by 0xBADDCAFE** [comment]
> ファイルのURLなどは関係ありますか？

今のところ試した範囲では関係無いようです。以下のファイルで試しました。

```
https://raw.githubusercontent.com/gcmt/dotfiles/2afa347cffe1de895b4349c86258d753ff9ab0f0/vim/.vimrc
https://www.google.co.jp/ (index.htm)
http://ftp.jaist.ac.jp/pub/sourceforge/s/se/sevenzip/7-Zip/9.20/7z920.exe
```

保存ファイルの保存場所をドライブごと変えてみたりしましたが変わらず。

> いちど -1 を直値で渡してみてもらえますか

試し次第また結果を書きます。

**Comment by ghost** [comment]
Chrome からの D&D に限り、Vim 内の pGetMessage() の直後で HDROP の上位32bit が 0xFFFFFFFF になっています。その場合の下位32bit は不定です。その値がクラッカーを通過して件の場所に到達しています。DragQueryFile は無効ハンドルエラーでゼロを返しているようです。

explorer からの D&D は cmd.exe と notepad.exe で期待通りに動きますが、
Chrome からの D&D は cmd.exe でも notepad.exe でもアクションが起こりません。

Chrome からの D&D は explorer.exe にはアクションが起こるので権限かと思ったのですが、どちらにせよ Undocumented なふるまいですね、DragQueryFile 呼び出しの返値がゼロという状況つまりエラーでゼロなのかファイル数がゼロなのかはっきりしないという仕様であるため、Vim 該当所の cFiles がゼロなら無視するようにロジックを変えるのが現実的対応のようには思います。

**Comment by ghost** [comment]
DragQueryFile について (言い換えると -1) という記述は MSDN.en-us にはありません。また、Return value が A nonzero value indicates a successful call. ときっちり書いてあるので、ゼロならエラーです。MSDN.ja-jp はどうなっているのでしょうか…。

**Comment by k-takata** [comment]
> Chrome からの D&D は explorer.exe にはアクションが起こるので

OLEでドロップを受け取れば動くんですかね？

**Comment by h-east** [comment]
仕事用に充てがわれてるPC(Windows 7 64bit)にVS2010入ってたのでWindows SDK入れてVimビルドしてみたけど再現しなかった。

Windows 8 か 8.1でビルドしないと発生しない？
Windows SDKのバージョンとかかぁ？

お手数ですがみなさんの環境(Win ver., VS ver., 現象再現有無, SDK ver.)教えてください。
(SDK ver.はnmake実行前に `set WindowsSdkDir` で確認お願いします)

私の環境(Windows 7 64bit, VS2010, 現象再現せず)
WindowsSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\

**Comment by mattn** [comment]
Windows7, mingw32, vc10 どれも再現せず。

**Comment by 0xBADDCAFE** [comment]
> いちど -1 を直値で渡してみてもらえますか

試したところ変化なし (再現する) でした。

自前でビルドしたものに関しては
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\8.1\
です。

あとさきにあげていた点で訂正したいのですが、
https://bintray.com/veegee/generic/vim_x64/view/files
こちらで配布されているバイナリは VS2010 ではなく VS2013 でビルドされていたようです。別の配布と混同していたようでした、すいません。

私のところで再現している状況としては、
- Windows8 64bit 上 (Windows7 上では k-takata さんのところで再現せず)
- VS2013 でビルドした 64bit バイナリ (VS2013 32bit では再現せず)

となっています。もしくは別の、環境依存の問題でしたら厳しいですが。

**Comment by ghost** [comment]
Windows8.1 の VS2013 Express、
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\8.1\ で再現。
コンパイラは
Microsoft(R) C/C++ Optimizing Compiler Version 18.00.30324 for x64
です。Make_mvc.mak CPU=AMD64 で仕上げています。

-1、0xFFFF、0xFFFFFFFF、~0ul と試していますがどれも WM_DROPFILES の wParam に無効な HDROP が入ってきます。DragQueryFile() で 0 が返ってきても構うことなしにパスの取得手順を試みましたが失敗しました。

**Comment by mattn** [comment]
これ Chrome のバグじゃないすかね

**Comment by h-east** [comment]
> これ Chrome のバグじゃないすかね

今のところWindows 8(.1)でしか起きないのでWindows SDK 8.1がバグっていると思ってます。
Win7でWindows SDK 8.1を使ってビルドする方法が分からんです。

**Comment by ghost** [comment]
仕様に暗に記されている「DragQueryFile() の返値 0 はエラー」を処理していない Vim の仕様漏れがここになって出てきたという解釈をしています。

Chromeが変なHDROPを出していて→WinSDK8.1が生値をそのまま通すように変更されていて→Vimで内部エラー、みたいな三段オチだとわかりやすいんですが、そんな気がするという程度の根拠しか持ち合わせていないのでアレです。妄想の域を出ません。

Chrome のソースを小一時間ほど眺めてみます。

**Comment by ghost** [comment]
眺めましたが、ドラッグが発生した時点の座標値とクライアント/非クライアントのフラグを Chrome はセットしていません。
これから検証しますが、position 値とフラグの格納されるメモリが GlobalAlloc() の Moveable でゼロクリアしてない(意図的にしていない？)アドレスにあるので、これらを WinSDK8.1 で正常な値域かどうか見るようになったのであれば、変態的な値が入っているので FAILED(HDROP) の意味で 0xFFFFFFFF???????? にしているのかもしれないという流れです。
外れていることを祈ります。
GetLastError() には「無効なハンドルです。」が返っています。

**Comment by h-east** [comment]
@ntak お疲れ様です。
https://github.com/vim-jp/issues/issues/552#issuecomment-41947772 の場合だと正常そうな値(上位が0xFFFFFFFFでない)でもエラーになっているようです。
(まぁ、DragQueryFileをDragQueryFileWに変更して実行した結果なので微妙ですが)

**Comment by h-east** [comment]
備忘録
Using the Windows 8 SDK with Visual Studio 2010 – configuring multiple projects
http://blogs.msdn.com/b/vcblog/archive/2012/11/23/using-the-windows-8-sdk-with-visual-studio-2010-configuring-multiple-projects.aspx

**Comment by ghost** [comment]
いま長々と書いてたんですが、結局予想でしかないので割愛して現実のコードに戻ります。

Chrome で WM_DROPFILES に対してセットするファイル名は wchar_t で固定でした(struct DROPFILES.fWide に TRUE を代入している)。
20時ごろから試しに gVim に対して壊れたパラメータを含んだ HDROP を投げかけてみます。

**Comment by ghost** [comment]
失礼しました。勘違いをしていた書き込みを一つ消して明日に持ち越します。コード量についてのOLE畏れ…。

**Comment by ghost** [comment]
今書きあがった最低限のコードを 64bit でコンパイルすると gVim.64bit にドロップできますが
同じコードを 32bit でコンパイルすると gVim.64bit にはドロップできず例の内部エラーになります。
Windows コードのフルアクセス権が欲しい…

> マイクロソフトは、32ビットABIのコードと64ビットABIのコードとの相互な呼び出しを禁止している
> http://ja.wikipedia.org/wiki/WOW64

えー…(;´Д`)

> 32ビットアプリケーションと64ビットアプリケーションの間には、実行ファイル以外のコンポーネント群を互いに利用することができない深い溝がある

ワーオ(;´Д`)

**Comment by mattn** [comment]
詰みフラグ

**Comment by ghost** [comment]
一つ詰んでは皆のため～(´Д`)ハァ～ドッコイショ～

**Comment by k-takata** [comment]
Win8 の問題なんですかね？ しかし、Kaoriya版で発生しないのはなぜだろう。

**Comment by 0xBADDCAFE** [comment]
何分知識がないので判断できないのですが、D&D についてはランタイムライブラリは関係するでしょうか。

http://msdn.microsoft.com/ja-jp/library/2kzt1wy3.aspx

私がビルドしたものや、上記の配布バイナリは /MT スイッチでビルドされていますが、kaoriya 版は /MD スイッチでビルドされています。
/MD スイッチでビルドを試そうと思ったのですが、src に同梱されている xpmlib がリンクできず現在後回しにしています。

**Comment by 0xBADDCAFE** [comment]
詰みフラグが出ていたので、今更ながら本件についての私のスタンスを明示しておきます。

この件について、chrome 起因の動作のような気はしていたのですが、少なくとも内部エラーという状況は Vim 的にも好ましくなく、報告する必要があるかとひとまず検討する意味で Issue を立てました。

現状厳しい実害があるわけではないので、どういう形まで持って行きたい、という方針はあまり考えていませんでした。
ですので、修正が難しく負担を負っている方はすいません。こういった事象があるということを周知できたことでひとまずはと考えています。

**Comment by mattn** [comment]
コケない方向のパッチでお茶を濁すのがいいかな。この説明、vim-devにするのめちゃくちゃ面倒そう。

**Comment by koron** [comment]
> Win8 の問題なんですかね？ しかし、Kaoriya版で発生しないのはなぜだろう。

@h-east さんが既に書いてるとおり、Windows SDKのバージョンじゃないですか?
うちは VS2010 + WinSDK 7.0Aでコンパイルしてますゆえ。

**Comment by koron** [comment]
> /MD スイッチでビルドを試そうと思ったのですが、src に同梱されている xpmlib がリンクできず

私が使っているプリコンパイルバイナリは
https://bitbucket.org/koron/vim-kaoriya/src/1b4115f260f7cc504179914c324e4b19478d736c/contrib/xpm/?at=default
にあります。

そのソースは https://github.com/koron/libXpm-win32 です。

**Comment by koron** [comment]
手元にはVS2010と2012はインストールしてあるけど、2013はしてないな…

**Comment by koron** [comment]
> この説明、vim-devにするのめちゃくちゃ面倒そう。

DragQueryFile() が 0 を返すような、もっと簡単な手順を作れないかしら。
ファイルではないものをD&Dして 0 を返させるイメージ。
そうすれば cFiles のチェックは納得してもらえそう。

**Comment by koron** [comment]
Spy++ を使ってD&Dした時にVimが受け取ってるメッセージを
-  問題の発生しないVimと
-   問題が発生しているVimで

比べたりしましたか?

 特に問題の発生しないVimが
WM_DROPFILES時にどのような wParam (=HDROP)を受け取ってるか
が気になります。

**Comment by koron** [comment]
VS2013を使って +kaoriya 版を作ってみました。
@0xBADDCAFE & @ntak 再現できるか試してみてもらえますか?

http://files.kaoriya.net/var/gvim-vc12-amd64-20130510T1119.zip

VS2013を使う関係で幾つか異なっている箇所があります:
-   if_ruby の無効化
-   INCLUDE に Windows SDK v7.1Aを足している (win32.makのため)

**Comment by koron** [comment]
WINDOWSSDKDIR は `C:\Program Files (x86)\Windows Kits\8.1\` でした。

**Comment by koron** [comment]
> VS2013を使う関係で幾つか異なっている箇所があります:
-   +kaoriya パッチあたってなかった(単に同じビルドスクリプトを使っただけ)

**Comment by koron** [comment]
Surface PRO の8.1 + gvim-vc12-amd64 で再現した。

**Comment by koron** [comment]
うーん +kaoriya パッチの有無が効くとは思えない…が試したほうが良いかなぁ?

**Comment by koron** [comment]
MSVCRT同梱版、置いときます: http://files.kaoriya.net/var/gvim-vc12-amd64-20130510T1201.zip

**Comment by koron** [comment]
ノーマル、+kaoriya、MSVCRT を同梱したもの、置いときます
http://files.kaoriya.net/var/gvim-vc12-amd64-20130510T1208.zip

**Comment by koron** [comment]
おっけー。ぼくの手元では +kaoriya でも発生した。
ほぼ Win 8.1 + 8.1 SDK のせいっぽい。

**Comment by koron** [comment]
Spy++の導入、めんどいなぁw

**Comment by h-east** [comment]
@koron おつです！Windows 7SP1 64bitだとノーマル、+kaoriyaどちらも発生しませんでした。

> ほぼ Win 8.1 + 8.1 SDK のせいっぽい。

っぽい++

**Comment by ghost** [comment]
こちらでもノーマル、+kaoriya ともに再現しました。
検証に使っていた最低限のソースは
http://ntak.net/vim/c.cpp
に置きました。
cl.exe /MT c.cpp か cl.exe /MD c.cpp どちらでもコンパイルできます。

**Comment by 0xBADDCAFE** [comment]
遅くなってしまいすいません。休日留守にしていました。

@koron バイナリありがとうございます。当方でもノーマル、+kaoriya 再現しました。

**Comment by koron** [comment]
私はSpy++でメッセージ眺めるつもりでしたが、まだ手付かずです。
なお、コンパイルにつかったVS2013はPremiumの無updateでした。

**Comment by koron** [comment]
でもなー8.1SDKが原因だとしても、どうしてそうなるのかまったく理由が説明できませんね。
なんなんこれ?

**Comment by k-takata** [comment]
#1127 にて、VC2010 でビルドした 8.0.0956 では発生せず、VC2015 でビルドした 8.0.0960 では発生するという報告がありました。

**Comment by k-takata** [comment]
手元でも再現しました。こちらでの再現条件は、

* Vimの64bit版をVC2012以降 (2012, 2013, 2015) でコンパイル
* D&D元は、春Mという32bitアプリ

でした。Vimを32bitでコンパイルした場合は発生せず、また、64bitでもVC2010でコンパイルした場合も発生していません。64bitでVC2015を使い、Windows SDK 7.1Aを使ってXPでも動作するようにコンパイルした場合は発生しました。ということでSDKのバージョンは関係なさそうです。

HDROPの値を確認したところ、エクスプローラからD&Dした場合は、44bit程度の値が入っていたのですが、現象が発生したときは、32bitに切り詰めた値を符号拡張したと思われる値が入っていました。
どうも32bitアプリから64bit VimにD&Dしたときの動作が怪しい気がします。(2014年だとChromeはまだ32bitだろうか？)
しかし、VCのバージョンで変わる理由が分からない…。

**Comment by k-takata** [comment]
判明！
PEヘッダの `IMAGE_OPTIONAL_HEADER64.DllCharacteristics` の `IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA` フラグを落としたら、VC2015 でビルドした 64bit Vim でも 32bit アプリから D&D を受け付けるようになった。(0x8160 だったのを 0x8140 に変更)

**Comment by k-takata** [comment]
https://msdn.microsoft.com/ja-jp/library/jj835761.aspx
リンカーオプションに `/HIGHENTROPYVA:NO` を指定すれば無効化できるのかな？

**Comment by koron** [comment]
ASLR を弱くしないとダメってことなんですね。

**Comment by k-takata** [comment]
そうなりますね。

**Comment by koron** [comment]
> HDROPの値を確認したところ、エクスプローラからD&Dした場合は、44bit程度の値が入っていたのですが、現象が発生したときは、32bitに切り詰めた値を符号拡張したと思われる値が入っていました。

これなんですが、gui_w32.c で `typedef int HDROP;` してるんで、それが関係してないですかね?
実は 64bit では HDROP は int には収まらないとか?

**Comment by k-takata** [comment]
それは cproto 用のダミー定義です。64bit では前述の通り、int には収まりません。

**Comment by koron** [comment]
ああ、ありがとうございます。

ということはOSの不具合か不可避な仕様で、強いASLRとのトレードオフって感じになっちゃうんですね。

**Comment by koron** [comment]
とはいえこんな記事もあるのかw

<http://www.itmedia.co.jp/enterprise/articles/1711/21/news060.html>
>  WindowsのASLRに脆弱性、米セキュリティ機関が対策呼び掛け (2017年11月21日 09時15分 公開)

**Comment by koron** [comment]
↑の記事は、Windowsには強制的にASLRを有効化する手段があるのだけど、そこにバグがあって実は有効化できてないってことらしい。記事内のopt-in ASLR ってのは、まさにこのissueで紹介されたPEのフラグで設定される、実行ファイル毎のASLRのことらしい。

**Comment by k-takata** [comment]
その記事で言っているのは `/DYNAMICBASE` の方で、それと組み合わせて使う `/HIGHENTROPYVA` についてではなさそうですね。

**Comment by k-takata** [comment]
https://github.com/vim-jp/issues/issues/552#issuecomment-42522878
> GetLastError() には「無効なハンドルです。」が返っています。

現象発生時に `DragQueryFile()` 実行後の `GetLastError()` の値を見ると、`ERROR_INVALID_HANDLE` (6) が返ってきていることがこちらでも確認できました。

あと、`IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA` フラグを落とした時の HDROP の値を見ると、（フラグが立っている時とは異なり）32bit に収まっているようです。

https://github.com/vim-jp/issues/issues/552#issuecomment-42136664
> Chrome からの D&D は explorer.exe にはアクションが起こるので

Win10 の explorer.exe を見ると、High Entropy VA フラグが立ってなかった！(0xC1C0)

**Comment by mattn** [comment]
explorer 攻めてるな。強い。

**Comment by k-takata** [comment]
しかし、explorer がフラグを立ててないなら、Vimも立てる必要はないのではという気がしますね。
こんな感じでどうだろう。

```diff
--- a/src/Make_mvc.mak
+++ b/src/Make_mvc.mak
@@ -1181,6 +1181,13 @@ LINKARGS1 = $(LINKARGS1) /LTCG:STATUS
 !endif
 !endif
 
+!if $(MSVC_MAJOR) >= 11 && "$(CPU)" == "AMD64" && "$(GUI)" == "yes"
+# This option is required for VC2012 or later so that 64-bit gvim can
+# accept D&D from 32-bit applications.  NOTE: This disables 64-bit ASLR,
+# therefore the security level becomes as same as VC2010.
+LINKARGS1 = $(LINKARGS1) /HIGHENTROPYVA:NO
+!endif
+
 all:	$(VIM).exe \
 	vimrun.exe \
 	install.exe \
```

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/2504

**Comment by k-takata** [comment]
8.0.1473: https://github.com/vim/vim/commit/511ffdd65d48b0597ed10614d161b5e811342058
