### ISSUE TITLE
コマンドラインのマッピングについて

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#553]
コマンドモードでのマッピングを行おうとして:eを押すと:e ++enc=cp932　を実行するマップを行おうとしました。以下のようにしたのですが上手に出来ません。どうしたらよろしいですか。
cnoremap :e :e ++enc=cp932

**Comment by rbtnn** [comment]
先頭のコロンがいらないですね。
cnoremap e     e ++enc=utf-8

**Comment by koron** [comment]
eを含むファイル名をタイプできなくなりそうな予感w

**Comment by rbtnn** [comment]
あ、utf-8のところは任意でお願いします。

**Comment by rbtnn** [comment]
<C-e>などCtrlキーなどの修飾キーのマッピングにしたほうがいいかもしれないですね。

**Comment by torakichi-jp** [comment]
マップするよりも、cnoreabbrev で展開させるようにした方がいい気がします。
cnoreabbrev @e e ++enc=cp932
とかどうでしょう。

**Comment by osyo-manga** [comment]
> 先頭のコロンがいらないですね。
> cnoremap e e ++enc=utf-8

`:e` で変換したいといということなので

``` vim
cnoremap :e e ++enc=cp932<CR>
```

が、正しいのではないでしょうか。

**Comment by InoueReo0406** [comment]
皆様、回答ありがとうございます。
koron様が仰ってくれたように、また自分がeをノーマルモードにて使用しているためマップするキーを変えようと思います。
そのため以下のようにコードを書いてみたのですが1,2,3と名前のついた新しいファイルが生成されました。何が間違ってますでしょうか。

cnoremap :e1 set fenc=utf-8<CR>
cnoremap :e2 set fenc=cp932<CR>
cnoremap :e3 set fenc=shifjis<CR>

**Comment by thinca** [comment]
コマンドラインモードのキーマッピング `:cnoremap` は、コマンドラインモードでのみ適用されます。つまり上記のキーマッピングを発動させるには、
1. `:` を押してコマンドラインモードに入る
2. `:e1` と入力する

とすることで初めて `set func=utf-8` に展開されます。つまりノーマルモードの状態からは `:` を 2 回押す必要があります。

改めて、具体的にやりたいことは何でしょうか? 途中までは `:e ++enc=utf-8` だったのに、今のだと `:set fenc=utf-8` になっており、やろうとしていることが変わっているように見えます。
表題どおりコマンドラインモードでのキーマッピングの挙動について知りたいのか(そしてここで挙げているのはただの例なのか)、具体的にやりたいことがあるのか、によって教えられることが変わってくると思います。

**Comment by InoueReo0406** [comment]
すみません、説明不足でした。
やりたいこととしては文字のエンコーディングの方法をutf-8やshiftjisに変更するショートカットを行いたいと考えています。その過程でset関数を使用と考えました。
thinca様が仰ってくれたようなマッピングで行いたいと思います。
ありがとうございます。
