### ISSUE TITLE
Startifyの使い方

### ISSUE THREAD

**Issue by InoueReo0406** [vim-jp/issues#554]
vim-startifyの使い方で質問があります。
startifyのスタート画面がありますよね。(https://raw.githubusercontent.com/mhinz/vim-startify/master/startify.png)
vimを開始したあとでもこの画面に移れるようなマッピングを考えました。
例　innoremap a g:startify_session_dir
https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt の関数を参照しても
どれがそれに当たるかがわかりませんでした。
どの関数を割り振れば良いのでしょうか。

参考サイト
https://github.com/mhinz/vim-startify

**Comment by thinca** [comment]
https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L431

**Comment by InoueReo0406** [comment]
ありがとうございます。

**Comment by 0xBADDCAFE** [comment]
close している案件にレスポンスする形で申し訳ないですが、失礼します。

#550 #537 等で提案いただいているよう、プラグインの報告・質問は該当のリポジトリが Issues を開いているのであればそちらにされてはいかがでしょうか。
また #515 で、質問により適切な場所として、Lingr の Vim 部屋や読書会を紹介頂いているかと思います。是非一度ご覧になられてください。

質問に対する直接の答えではないかもしれませんが、これらも回答された方の貴重な意見に思えます。こういった意見に反応がないと極論、自分に必要な意見にしか耳を貸さないように、人によっては見えてしまうかもしれません。
もちろんこの Issues に何を書いても構わないですので、ここを選ぶ理由があるのであれば明記されると答える側としても提案する必要がなくなります。

以上、ご一考ください。
