### ISSUE TITLE
E416番の日本語エラーメッセージのtypo

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#555]
Windows 7 上にて kaoriya 版 gvim を使わせていただいています。
`:highlight String link` のような間違った `highlight` コマンドを使ったときにE416エラーを見たのですが、エラーメッセージが「等号ががありません」となっており「が」が重なっているようです。一応画像をお付けします。
![typo](https://cloud.githubusercontent.com/assets/480049/2870835/34e7841e-d2e3-11e3-9bcb-abf3ffa94b6b.png)

**Comment by koron** [comment]
ありがとうございます。

**Comment by koron** [comment]
最新版で直しました。

![fixed](https://cloud.githubusercontent.com/assets/468368/2872969/210cbe84-d386-11e3-8b27-e05f73347e41.png)

パッチは [ココ](https://bitbucket.org/koron/vim-kaoriya-patches/src/1c4498bb3737eb455692460f59101c7ba497400f/5001-update-translations-ja.diff?at=default) に置いてありますが
vim-dev への投稿はまだ予定してません。
そろそろpotとかも更新したいので。

**Comment by koron** [comment]
とりあえず閉じときます。

**Comment by machakann** [comment]
ありがとうございます。
lang-ja レポジトリがあったんですね。こっちに建てるのが適切でした、覚えておきます。

**Comment by k-takata** [comment]
> lang-ja レポジトリがあったんですね。

いえ、先ほどできたばかりです。

**Comment by machakann** [comment]
なるほど。
