### ISSUE TITLE
nnoremap <silent>で呼ぶ関数の中でechoを使うと文字が途切れ途切れになることがある

### ISSUE THREAD

**Issue by itchyny** [vim-jp/issues#558]
### `vimrc`

``` vim
set nocompatible
filetype off
nnoremap <silent> <Plug>(echoline) :<C-u>call EchoLine()<CR>
nmap <C-g> <Plug>(echoline)
function! EchoLine()
  redraw
  echo getline('.')
endfunction
filetype plugin indent on
syntax enable
```
### `test`ファイル

```
ああああああああああ
aaaaaaaaaa
```
### 手順

```
$ vim test -u ./.vimrc
<C-g>   " 「ああああああああああ」と表示される
j
<C-g>   " 「 a a a a a」と表示される。
```

「aaaaaaaaaa」と表示されることを期待します。
マルチバイトの文字をechoした後に、英数字をechoすると起こる現象です。
### スクリーンショット

![bc9xszfihpt](https://cloud.githubusercontent.com/assets/375258/2935134/f0a9b3ee-d7f1-11e3-8477-0a19f3c95648.gif)
### 環境
- Mac OS X
- Vim 7.4
- iTerm 2、Terminal.app 共に再現します
### 再現性

いつも再現できるわけではないのです。何度もやっていると1/3くらいの確率でこの問題が生じます。私も混乱しています。
### `redraw`について

`redraw` → 再現する
`redraw!` → 再現しない
`redraw`の行を消す → 再現する
### 再現できた環境
- Mac OS X 10.9, Vim 7.4 CUI, iTerm2 / Terminal.app (itchyny)
- Cygwin64 + Vim コンソール版 7.4.283 + mintty (ntak様)
- Mac OS X 10.9, Vim 7.4.258 / 7.3, ssh (higemaniya様)
- Mac OS X, Vim 7.3 (saitoha様)
### 再現できなかった環境
- Vim 7.4.283 on fedora19 via PuTTY 0.63 (h-east様)
- mintty/putty で ssh 経由でつないだ linux の 7.4.193 (mattn様)
- Ubuntu 12.04, Vim 7.4.227, 標準端末 / terminator (itchyny)

**Comment by mattn** [comment]
問題の切り分けをしたいので `redraw!` で試して貰えますか。

On 5/10/14, itchyny notifications@github.com wrote:

> ### `vimrc`
> 
> ``` vim
> set nocompatible
> filetype off
> nnoremap <silent> <Plug>(echoline) :<C-u>call EchoLine()<CR>
> nmap <C-g> <Plug>(echoline)
> function! EchoLine()
>   redraw
>   echo getline('.')
> endfunction
> filetype plugin indent on
> syntax enable
> ```
> 
> ### `test`ファイル
> 
> ```
> ああああああああああ
> aaaaaaaaaa
> ```
> 
> ### 手順
> 
> ```
> $ vim test -u ./.vimrc
> <C-g>   " 「ああああああああああ」と表示される
> j
> <C-g>   " 「 a a a a a」と表示される。
> ```
> 
> 「aaaaaaaaaa」と表示されることを期待します。
> マルチバイトの文字をechoした後に、英数字をechoすると起こる現象です。
> 
> ### スクリーンショット
> 
> ![bc9xszfihpt](https://cloud.githubusercontent.com/assets/375258/2935134/f0a9b3ee-d7f1-11e3-8477-0a19f3c95648.gif)
> 
> ### 環境
> - Mac OS X
> - Vim 7.4
> 
> ### 再現性
> 
> いつも再現できるわけではないのです。何度もやっていると1/3くらいの確率でこの問題が生じます。私も混乱しています。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/558

## 
- Yasuhiro Matsumoto

**Comment by itchyny** [comment]
`redraw!`にすると、問題は生じませんでした。
`redraw`がない場合は問題が生じます。

**Comment by ghost** [comment]
:echo "０１２３４５６７８９" がうまくいかないのもこの流れですかね…

**Comment by k-takata** [comment]
他のターミナルソフトやgvimを使った場合にどうなるのかも気になります。

**Comment by itchyny** [comment]
端末について書くのを忘れていました。
使ったのはiTerm 2です。
VimはCUI版です。
また、Mac標準のTerminalを用いても、同じ現象が起こりました。

**Comment by ghost** [comment]
とりあえず前述の０１２３…がうまくいってない部分と同じコードを通っていないかと思って修正をかけたら自分のそれだけ治ってタイトルの問題が治ってないという…今夜追及します。
ヒントになるかもしれないので一応そのパッチ：

``` diff
diff -r f051f3af15d8 src/screen.c
--- a/src/screen.c  Fri May 09 20:33:04 2014 +0200
+++ b/src/screen.c  Sun May 11 17:22:50 2014 +0900
@@ -7142,7 +7142,7 @@
        }
        if (mbyte_cells == 2)
        {
-           ScreenLines[off + 1] = 0;
+           ScreenLines[off + 1] = ' ';
            ScreenAttrs[off + 1] = attr;
        }
        screen_char(off, row, col);
```

環境は mintty と Cygwin のコンソール版です。

**Comment by ghost** [comment]
治っていないと思ったら治っていて make test も通った、何を言っているのか(略

**Comment by h-east** [comment]
@ntak 

> :echo "０１２３４５６７８９" がうまくいかないのもこの流れですかね…

これだけだと再現手順、実際の結果が分からないです。
再現方法が本Issueのものに近いのであればここで補足をお願いします。
そうでない場合は別Issueを立てて貰えますか？

# 

このIssueの現象、私の環境(Vim 7.4.283 on fedora19 via PuTTY 0.63)では再現出来てないです。

**Comment by ghost** [comment]
Cygwin で Vim の Console 版を立ち上げて :echo "０１２３４５６７８９" と入力すると最下行に
０１２
だけしか表示されてこないという現象ですね。根を同じくした表示属性の設定ミスだろうと思って最小手順を記しただけですが、お気に障ったようですね。謝罪いたします。申し訳ありませんでした。

**Comment by itchyny** [comment]
現象を再現できる人を探しています。
特にMacのCUI版Vimを用意できる人は試して欲しいです。
MacVimでは再現できませんでした。

**Comment by ghost** [comment]
当方では Cygwin64 + Vim コンソール版 7.4.283 + mintty で再現できています。
前述のパッチにより、当方では現象が発生しなくなりました。

**Comment by ghost** [comment]
別Issueに分けてきました。

**Comment by h-east** [comment]
@ntak 

> お気に障ったようですね。

いえ、私の環境では本Issueのもntakさんのも再現出来なかったのでもう少し情報が欲しかったのであのような言い回しになりました。

> 別Issueに分けてきました。

ありがとうございます。

私としては、まず再現する環境、条件を確立させたいと思っています。

**Comment by Shougo** [comment]
> いえ、私の環境では本Issueのもntakさんのも再現出来なかったのでもう少し情報が欲しかったのであのような言い回しになりました。

unite.vim でも redraw で問題が起こっているらしく、この問題と関連しているのではないかと思っているのですが私の環境で再現しません。そこの .vimrc で指定されているマッピングではやはり `nnoremap <silent>` を利用しています。

**Comment by itchyny** [comment]
どう関連すると判断したのか分かりません。
このissueは「文字が途切れ途切れになる現象」です。

**Comment by Shougo** [comment]
私は「途切れ途切れになる -> 改行される -> echo で意図しない Hit Enter が発生する」
と判断しました。

**Comment by mattn** [comment]
んー。関係ない気がするなー。改行に値する文字含んでないし。。。

**Comment by mattn** [comment]
- mintty で ssh 経由でつないだ linux の 7.4.193 では再現しなかった。
- putty で ssh 経由でつないだ linux の 7.4.193 では再現しなかった。

**Comment by itchyny** [comment]
友人のUbuntuでも再現できませんでした。

再現できた環境
- Mac OS X, Vim 7.4 CUI, iTerm2 / Terminal.app (itchyny)
- Cygwin64 + Vim コンソール版 7.4.283 + mintty (ntak様)

再現できなかった環境
- Vim 7.4.283 on fedora19 via PuTTY 0.63 (h-east様)
- mintty/putty で ssh 経由でつないだ linux の 7.4.193 (mattn様)
- Ubuntu 12.04, Vim 7.4.227, 標準端末 / terminator (itchyny)

**Comment by mattn** [comment]
@ntak さんは再現してるのかな？

**Comment by mattn** [comment]
あ、押してもうた。ごめんなさい。

**Comment by itchyny** [comment]
@ntak 「当方では Cygwin64...再現できています」というのは別のissue(echo "０１２３")のことですか。それともこのissueが再現出来たということですか？

**Comment by higemaniya** [comment]
Mac OS X 10.9 で
- MacVim 7.4 のコンソール版(適用済パッチ 1-258) 
  `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  1 2014 13:37:27)`
- macportsで入れたバイナリ(適用済パッチ 1-258) 
  `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 22 2014 17:58:09)`
- OSのVim 7.3
  `VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Aug 24 2013 18:58:47)`

で試してみたところ、全てで現象が起きました。
再現性も同じで必ず起きるわけではないようです。

ちなみに、ターミナルアプリ上ではなくて、sshでログインしています。
参考になれば幸いです。

**Comment by ghost** [comment]
この Issue が動画のとおりに再現できています。

文字の表示属性が端末に届いてないと判断したので(入力履歴は途切れないから)、そういえばこの問題もそうだなと最短手順(:echo "０１…")を出した経過です。

**Comment by itchyny** [comment]
higemaniyaさん、確認をとって頂き大変ありがとうございます。

情報がバラバラになると見にくいので、再現できた環境とできなかった環境を、一番上のコメントに追記していきます。

**Comment by itchyny** [comment]
ntakさん、ありがとうございます。再現できている環境として、一番上のコメントに環境を書かせて頂きました。

**Comment by h-east** [comment]
うーん、再現しない。端末の設定なのかなぁ。。
@itchyny さん、端末(iTerm2)で以下のコマンドの実行結果を教えて貰えますか？

``` bash
$ echo $TERM
$ stty -a
```

**Comment by itchyny** [comment]
以下のようになります。

``` sh
 $ echo $TERM
xterm-256color
```

``` sh
 $ stty -a
speed 38400 baud; 43 rows; 193 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
    -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
    -extproc
iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
    -ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
    -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
    eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
    min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
    stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

**Comment by saitoha** [comment]
今macbookを変えたばかりで、最新のvimを入れてないんですが、
OSXにデフォルトインストールされているvimで再現しました。

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec 19 2013 15:19:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses

stty -aはitchynyさんと同じです。

**Comment by itchyny** [comment]
saitohaさん、確認をとって頂き大変ありがとうございます。

**Comment by saitoha** [comment]
すこし状況が見えてきたので、ご報告します。
ステータスラインに何も書かれていない時は、このように素直にaaaa...が出力されます。

![2014-05-12 14 04 22](https://cloud.githubusercontent.com/assets/1162739/2940983/da49153c-d994-11e3-9ab3-8f23eb6bbe73.png)

しかし、「あああああ...」のような全角文字がすでにステータスラインにあると、
スペースで前の文字を消しながら出力します。

![2014-05-12 14 03 38](https://cloud.githubusercontent.com/assets/1162739/2940991/18e11254-d995-11e3-80c6-b79b6c5632a8.png)

今回の問題が起きるときは、このようにBSとSPの順序が逆転しています。

![2014-05-12 14 05 14](https://cloud.githubusercontent.com/assets/1162739/2940998/4c8f717c-d995-11e3-988b-f9e1a5c46226.png)

**Comment by itchyny** [comment]
オフトピですが、そのかっこいいソフトは何なんですか

**Comment by saitoha** [comment]
@itchyny trachetといいます。
http://saitoha.github.io/trachet/

**Comment by itchyny** [comment]
@saitoha ありがとうございます！

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/546

原因が別だったので、こちらとは無関係であることが分かりました。すみません。

**Comment by mattn** [comment]
linux の gnome-terminal でも再現せず。ubuntu 14.04

**Comment by saitoha** [comment]
元々再現性が無い不具合なので自信が無いんですが

```
stty bs0
```

で直ったような気がしています。

**Comment by h-east** [comment]
もしかして端末の通常文字がボールド(太字)になってます？

**Comment by saitoha** [comment]
@h-east なってなかったです

**Comment by saitoha** [comment]
あ、やっぱりさっきの"stty bs0"は関係なかったです。
何度もやっていたらまた再現してきました。

**Comment by h-east** [comment]
再現していない私の環境の端末情報を貼り付けます。

``` bash
$ echo $TERM
putty-256color または xterm-256color
```

``` bash
$ stty -a
speed 38400 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke
```

---

※私(PuTTY)のだけに存在するパラメータ
-xcase
-iuclc
-ocrnl
-ofill
-ofdel
nl0 cr0 tab0 bs0 vt0 ff0
swtch = <undef>;
rprnt = ^R;
flush = ^O;

※itchynyさん(iTerm2)のだけに存在するパラメータ
-altwerase
-flusho
pendin
-nokerninfo
-oxtabs
-dsrflow
-dtrflow
-mdmbuf
discard = ^O;
reprint = ^R;
status = ^T;

※両者に共通するパラメータだが設定が異なるもの
h_east:    ixon, -ixany, -imaxbel, -iutf8, -brkint, -hupcl
itchyny:  -ixon,  ixany,  imaxbel,  iutf8,  brkint,  hupcl

**Comment by saitoha** [comment]
hgでvimの最新版のとってきてビルドして、やっぱり再現しました。
再現しないときとするとき、まったく同じ動きをさせてログとって読んでみたら、
再現しないときは、^[[24;1H という移動シーケンスを出し、
再現するときは、^[[24;2H という移動シーケンスを出すような部分がありました。
vimの内部の状態に違いがあることを示唆していると思います。

**Comment by ichizok** [comment]
OS X 10.9.2 / Vim 7.4.282 で調べてみました。

``` diff
diff --git a/src/screen.c b/src/screen.c
--- a/src/screen.c
+++ b/src/screen.c
@@ -6976,7 +6976,7 @@
     max_off = LineOffset[row] + screen_Columns;
 #endif
     while (col < screen_Columns
-           && (len < 0 || (int)(ptr - text) < len)
+           && (len < 0 || (long)(ptr - text) < len)
            && *ptr != NUL)
     {
        c = *ptr;
```

**Comment by saitoha** [comment]
@ichizok おそらく直りました。すごい！

**Comment by ichizok** [comment]
`ptr`、`text` が64bitポインタであるため、`ptr < text` の場合でも両者の値によっては
int キャストで `(int)(ptr - text) > 0` となり、意図しないタイミングでループを抜けてしまうのが原因のようです。

Ubuntu, CentOS (64bit) で確認した限りでは、 `ptr`, `text` ともに32bitアドレスの範囲に配置されるため、問題が出ないのだと思います。

**Comment by mattn** [comment]
@ichizok パッチ提出お願い出来ますか。

**Comment by k-takata** [comment]
Windowsだとlongも32bitなのでその直し方でいいのかが気になります。

**Comment by k-takata** [comment]
`&& (len < 0 || ptr < text + len)` がよい？

**Comment by ichizok** [comment]
見直すと、`screen_puts_len()` の中で他にも `(int)((text + len) - ptr)` とかあって、

screen.c:7171

``` c
            if (clear_next_cell)
                ptr = (char_u *)" ";
```

`clear_next_cell==TRUE` でここを通った後に `ptr` と `text` を比較計算しているのが危うい。
#559 の修正方法のほうが良いでしょうか。

**Comment by k-takata** [comment]
> `clear_next_cell==TRUE` でここを通った後に `ptr` と `text` を比較計算しているのが危うい。

`ptr - text` が int の範囲を超えるのが不思議だったのですが、そういうことでしたか。

**Comment by itchyny** [comment]
ichizokさん、大変ありがとうございます。
`ptr = (char_u *)" "` で `text` と別の文字列のポインターになってしまったのに `ptr - text`を使っているのがまずいんですね…

**Comment by mattn** [comment]
これそもそも `" "` にしてるけど以降の文字全部スペースにするつもりの処理だろか。それもと1文字だけつもりだろか。後者だとしたらバグ？

**Comment by mattn** [comment]
んー、long に直すだけだとまずそう。

**Comment by k-takata** [comment]
```
        /* When at the end of the text and overwriting a two-cell
         * character with a one-cell character, need to clear the next
         * cell.  Also when overwriting the left halve of a two-cell char
         * with the right halve of a two-cell char.  Do this only once
         * (mb_off2cells() may return 2 on the right halve). */
```

文字列の最後が1セルの文字で、2セルの文字の前半を上書きする場合、後半を半角スペースで上書きするという処理ですね。なので、最後の1文字の後のスペース1つだけ処理すればよいということになります。
#559 の修正方法で良さそう。

**Comment by ghost** [comment]
おーポインタサイズ…これは気づかなかった…
もう少し書き込みを緩募してから今夜まとめます。

**Comment by mattn** [comment]
ntak さんの `len = -1` はこれを回避してるつもりだと思ってました。

**Comment by ghost** [comment]
ポインタサイズの回避のつもりは実はまったくなくて、パッチした関数 screen_puts_len() の

> When "len" is -1 output up to a NUL.

を利用してみて動作して make test も通ったのでどうかな、と思った次第です。

**Comment by h-east** [comment]
@saitoha Nice tool!
@ichizok Nice investigation!
@ntak Nice patch!

**Comment by ghost** [comment]
まとめて掲出しました：
https://groups.google.com/d/msg/vim_dev/goIcj5RSY-8/9JTz8aAnvlsJ

マルチポスト的になるのは板の仕様としては避けようがあったりなかったりしますか？(;´Д`)

**Comment by itchyny** [comment]
この問題は32bit環境では再現できないという理解でいいのでしょうか。

**Comment by h-east** [comment]
@itchyny 処理系依存です。ほとんどの処理系では大丈夫だと思いますけど。
ptr(" ")はデータセクション内のアドレスが格納されて、text(引数)はスタックエリアのアドレスが格納されます。
普通の処理系では `データセクションアドレス < スタックエリアアドレス` の関係になるはずです。
その場合は `(int)(ptr - text) < len` が真になるので正しい処理がされます。
`データセクションアドレス < スタックエリアアドレス` の関係じゃない処理系だとアウトですね。

間違ってたら突っ込みPlease。

**Comment by itchyny** [comment]
@h-east ありがとうございます。私には難しいですが何となく分かりました。

**Comment by k-takata** [comment]
7.4.303
https://groups.google.com/d/topic/vim_dev/YQlXb21wnxM/discussion

**Comment by itchyny** [comment]
皆様、ありがとうございました。
