### ISSUE TITLE
画面最下行での utf8 文字列の表示結果が不正確

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#559]
コンソール版 Vim を立ち上げて 
`:echo "ああああ"` 
と入力した場合、結果として画面最下行に
`あああ`
と表示され、情報が欠落します。
正確性は、以前最下行に表示されていた文字列の内容に左右されるようです。
Cygwin64 + コンソール版 Vim + mintty で 100% 再現。

**Comment by ghost** [comment]
修正パッチ：

``` diff
diff -r f051f3af15d8 src/screen.c
--- a/src/screen.c  Fri May 09 20:33:04 2014 +0200
+++ b/src/screen.c  Sun May 11 17:22:50 2014 +0900
@@ -7142,7 +7142,7 @@
        }
        if (mbyte_cells == 2)
        {
-           ScreenLines[off + 1] = 0;
+           ScreenLines[off + 1] = ' ';
            ScreenAttrs[off + 1] = attr;
        }
        screen_char(off, row, col);
```

**Comment by mattn** [comment]
ntak++

On 5/11/14, ntak notifications@github.com wrote:

> 修正パッチ：
> 
> ``` diff
> diff -r f051f3af15d8 src/screen.c
> --- a/src/screen.c  Fri May 09 20:33:04 2014 +0200
> +++ b/src/screen.c  Sun May 11 17:22:50 2014 +0900
> @@ -7142,7 +7142,7 @@
>         }
>         if (mbyte_cells == 2)
>         {
> -           ScreenLines[off + 1] = 0;
> +           ScreenLines[off + 1] = ' ';
>             ScreenAttrs[off + 1] = attr;
>         }
>         screen_char(off, row, col);
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/559#issuecomment-42768205

## 
- Yasuhiro Matsumoto

**Comment by ynkdir** [comment]
screen.c のファイル先頭のコメント

> When the character occupies two display cells the next byte in ScreenLines[] is 0.

とあるので、そこを変えるのはまずい気がします。

**Comment by mattn** [comment]
画面を書き換える時に、オリジナルの値と比べる方式を取っているので、2セル文字の先頭に `a` を書き、後続セルに次の `a` を書く際に何かしら問題があるのでしょう。おそらくその際に、1セル飛ばしてしまってるのかと。

**Comment by ghost** [comment]
コードを追ってる最中に全く別の箇所で「半角空白でフラッシュしている」という意図のコメントがあったのでここもその通りにしてみたら表面の動作は正常に見て取れるようになった、のが今回の流れです。
その記述がある箇所がどこだったか、もう一度見ます。周辺に何か書いてありそう…。

**Comment by ghost** [comment]
ならばこちらから…

``` diff
diff -r f051f3af15d8 src/screen.c
--- a/src/screen.c  Fri May 09 20:33:04 2014 +0200
+++ b/src/screen.c  Mon May 12 13:27:19 2014 +0900
@@ -7169,7 +7169,10 @@
        col += mbyte_cells;
        ptr += mbyte_blen;
        if (clear_next_cell)
+            {
        ptr = (char_u *)" ";
+                len = -1;
+            }
    }
    else
 #endif
```

前のパッチは撤回します。

**Comment by ynkdir** [comment]
気づいたんですが、そのへんのコードは text <= ptr < text + len を想定してるので、そこの if (clear_next_cell) を通った後は
これとか
 6979             && (len < 0 || (int)(ptr - text) < len)
これとか
 6988                 mbyte_blen = utfc_ptr2len_len(ptr, (int)((text + len) - ptr));
その他全部だめですね

**Comment by ghost** [comment]
えー…と
本当に駄目なんですかね…
そのロジックは通ってないと思うんですが…

**Comment by ynkdir** [comment]
あーなるほど、それで len = -1 で ok ってことですか。失礼しました。

**Comment by mattn** [comment]
この修正でよさげ。

**Comment by mattn** [comment]
@ntak パッチ送る時にコメント入れておいた方がよさげです。

**Comment by ghost** [comment]
了解しました。

**Comment by ghost** [comment]
掲出しました：
https://groups.google.com/forum/?hl=ja&fromgroups#!topic/vim_dev/goIcj5RSY-8

**Comment by ynkdir** [comment]
おつです！

**Comment by h-east** [comment]
#558 と同根

**Comment by h-east** [comment]
おつです。
vim_dev投稿のリンクはPermalink(って呼び方でいいの?)にした方がいいです。
![permlink](https://cloud.githubusercontent.com/assets/518808/2958749/424540f8-daac-11e3-9e82-bd475a511924.png)

ということでペタリ
https://groups.google.com/d/msg/vim_dev/goIcj5RSY-8/9JTz8aAnvlsJ

**Comment by h-east** [comment]
重複ということでこちらのIssueは閉じます。
(別でIssue立てろといったのは私ですが、、すんません。)

**Comment by h-east** [comment]
@ntak ちょっと教えて下さい。Vim起動直後に

```
:echo "ああああ" 
```

として100%再現するのでしょうか？

Issue本文に

> 正確性は、以前最下行に表示されていた文字列の内容に左右されるようです。

と書かれているように、ソースの`screen_puts_len()`内のフラグ`clear_next_cell`がTRUEになる条件は以前表示されていた文字の情報 `ScreenLines[]` に関係すると思うのです。
もしかして `:echo "ああああ"`を2回実行すれば確実に再現する感じですか？
もしくは他に手順が必要だったりしません？

**Comment by h-east** [comment]
あー、自己解決。
`:echo "ああああ"`が以前表示されていた文字の情報になるんですね。

```
以前の文字→:echo "ああああ"
今回の文字→ああああ
```

今回の4つ目の`あ`が以前の文字の最初の`あ`と重なるからなんだかんだで`clear_next_cell`がTRUEになって現象発生ってことですね。

このバグ今まで残ってたのスゴイ:cat2:
