### ISSUE TITLE
コマンドラインで`../^I`が挿入される

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#56]
$ ls -F
foo/
$ vim --noplugin -i NONE
1. `cnoremap <C-p> <Up>`
2. `:e <Tab>`
3. `:e foo/`
4. `:e foo/<S-Tab>`
5. `:e`
6. `:e <C-p>`
7. `:e ../^I`

こんな風に`../^I`が挿入されてしまいます。^Iはタブ文字です。
7.3.260, 7.3.322で再現しています。

**Comment by tyru** [comment]
`../^I`の`^I`はタブ文字です。

**Comment by mattn** [comment]
全部コマンドライン入力ですか？`z:`は何？

**Comment by tyru** [comment]
ああすみません。typoです。s/z:/:/

**Comment by mattn** [comment]
再現しないすね。WinXP 32で`-u NONE -N`です。

**Comment by h-east** [comment]
--noplugin -i NONE でも発生します？

**Comment by tyru** [comment]
`--noplugin -i NONE`では再現されました。
`-u NONE -i NONE -N`では再現されませんでした。
`-u NORC -i NONE`では再現されませんでした。

自分の.vimrcとか環境はこんな感じです。(デカすぎて出す意味あまりないかもしれません...)
https://github.com/tyru/dotfiles/

**Comment by tyru** [comment]
`<Tab>`か`<S-Tab>`でディレクトリを補完したあと、`<Tab>`の場合は`<S-Tab>`、`<S-Tab>`の場合は`<Tab>`、を押して戻って、`<C-p>`すると発生するようです。
...あ。`cnoremap <C-p> <Up>`されてた...後出し情報すみませんorz

あと`<C-p>`を押した後、連続して押すたびに

```
../^I
../../^I
../../../^I
```

みたいに挿入されていきます。

あと--nopluginした場合でもなぜかunite.vimが起動できるのが謎...
なにかやり方間違ってるかもしれません...
ソース見たら`&loadplugins`がオンの時`plugin/**/*.vim`を読むらしいので
`autoload/unite.vim`をマッピングとかから読んでるのかと思ったけど
`plugin/unite.vim`にある`:Unite`コマンドが定義されている...
(`autoload/unite.vim`とか`autoload/unite/**/*.vim`にも`plugin/unite.vim`を読むコードはありませんでした)

**Comment by mattn** [comment]
あー、`:e`とかで始めるってことですよね？それを書かないとww

**Comment by mattn** [comment]
って、事で不具合の詳細を

> `:e <up>`とすると、`../^I`が挿入されて`:e ../^I`になる

と変えるべきかと

**Comment by tyru** [comment]
@mattn ごめんなさい！orz

あれ...`cnoremap <C-p> <up>`してるけど`<C-p>`と`<up>`の挙動が違う...
ということでそこも追記しておきました。
情報後出しすぎてすみませんorz

**Comment by h-east** [comment]
えーーーっ！

> あー、:eとかで始めるってことですよね？それを書かないとww

なんで分かったんすか？？

**Comment by mattn** [comment]
@h-east `:`からディレクトリの補完は出来ないので...

**Comment by tyru** [comment]
ですよねー...しまった...

**Comment by h-east** [comment]
なるほどー。Good洞察力！
でも「再現されまんでした。」が見れたので良しとします。←しつこいｗ

**Comment by koron** [comment]
とりあえずbugに分類したけど、違ったらゴメン。

**Comment by tyru** [comment]
@koron ありがとうございます。

**Comment by mattn** [comment]
これが正しい動きかどうかは分からんけど`<down>`の時と合わせてみた。

``` diff
diff -r fb6b43d55773 src/ex_getln.c
--- a/src/ex_getln.c    Fri Sep 30 18:35:57 2011 +0200
+++ b/src/ex_getln.c    Mon Oct 03 17:14:54 2011 +0900
@@ -589,7 +589,12 @@
            c = p_wc;
        }
        }
-       else if (c == K_UP)
+       else if (c == K_UP
+           && ccline.cmdpos > 0
+           && ccline.cmdbuff[ccline.cmdpos - 1] == PATHSEP
+           && (ccline.cmdpos < 3
+           || ccline.cmdbuff[ccline.cmdpos - 2] != '.'
+           || ccline.cmdbuff[ccline.cmdpos - 3] != '.'))
        {
        /* go up a directory */
        int found = FALSE;
```

**Comment by mattn** [comment]
ぜんぜん違うパッチになったけどclose

https://groups.google.com/d/topic/vim_dev/mNHDzGqyUVM/discussion

てかあれは分からんわw
