### ISSUE TITLE
「プログラムから開く」に登録できない(らしい)

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#561]
ref: https://groups.google.com/forum/#!topic/vim_jp/lhk8KtJiV-g

**Comment by koron** [comment]
gvimext は関係無いんじゃないか?

ちなみに私はgvimextコンパイルしなくなって久しい。

**Comment by mattn** [comment]
あー、「プログラムから開く」か。じゃぁパスか。

**Comment by mattn** [comment]
タイトル修正ed

**Comment by koron** [comment]
かも。

いま手元(7-64bits)で試したらできた。

**Comment by koron** [comment]
MuiCacheとか関係してるかも? ちょっとわかんない。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_jp/lhk8KtJiV-g/SRSYb9JIkg4J

> ここで、7.3のgvim.exeを「プログラムから開く」の一覧から削除するのに
> レジストリを直接いじったことを思い出し、
> 試しに、CCleanerでレジストリを掃除してみました。

解決したとのことですので閉じます。
