### ISSUE TITLE
configure を 2 回実行すると if_python が有効にならない

### ISSUE THREAD

**Issue by syngan** [vim-jp/issues#563]
私の手順が間違っているのかもしれませんが、はまったので報告します。

`--enable-pythoninterp` をつけて `./configure` を 2 回実行すると、 `config.cache` の情報をつかってしまうため、`configure.in` の以下の部分、`python_INSTSONAME` をとってくる処理が動きません。
そのため、`make` 時に `-DDYNAMIC_PYTHON_DLL=\"\"` となって `has('python')=0` となってしまいます。

```
    dnl -- we need to examine Python's config/Makefile too
    dnl    see what the interpreter is built from
    AC_CACHE_VAL(vi_cv_path_python_plibs,
    [
        pwd=`pwd`
        tmp_mkf="$pwd/config-PyMake$$"
        cat -- "${PYTHON_CONFDIR}/Makefile" - <<'eof' >"${tmp_mkf}"
__:
    @echo "python_BASEMODLIBS='$(BASEMODLIBS)'"
    @echo "python_LIBS='$(LIBS)'"
    @echo "python_SYSLIBS='$(SYSLIBS)'"
    @echo "python_LINKFORSHARED='$(LINKFORSHARED)'"
    @echo "python_DLLLIBRARY='$(DLLLIBRARY)'"
    @echo "python_INSTSONAME='$(INSTSONAME)'"
eof
```

**Comment by k-takata** [comment]
こんな感じでどうでしょう。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/e7a4d5e7cfe9b61afff04739b9f1ab9b1475ab6b/fix-configure-python-soname.patch
パッチを当ててから、`make autoconf && ./configure && make` でビルドできます。
(これの調査中に #280 にバグが発覚…)

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/tgZv-e1ZtNI/discussion

**Comment by k-takata** [comment]
あ、"I found two issues" って、見つけたの私じゃないのに嘘書いてしまいました。ごめんなさい。

**Comment by syngan** [comment]
対応ありがとうございました。

> あ、"I found two issues" って、見つけたの私じゃないのに嘘書いてしまいました。ごめんなさい。

無問題です

**Comment by k-takata** [comment]
7.4.299
https://groups.google.com/d/topic/vim_dev/KtreLTZPpLM/discussion
