### ISSUE TITLE
helpの motion.txt 中の '[, `[, '], `] に関する記述がわかりにくい

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#564]
motion.txt によると

> '[  `[         To the first character of the previously changed
>               or yanked text.  {not in Vi}
> 
> ']  `]         To the last character of the previously changed or
>               yanked text.  {not in Vi}

とそれぞれ同じ機能の提供のように書いてありますが、実際には `'[`, `']` は直近の変更の最初か最後の行へ、 ``[`, ``]` は直近の変更の最初か最後の文字へ移動というように別の機能が割り当てられているように思います。

続く記述に

> After executing an operator the Cursor is put at the beginning of the text that was operated upon.  After a put command ("p" or "P") the cursor is sometimes placed at the first inserted line and sometimes on the last inserted character.  The four commands above put the cursor at either end.  Example: After yanking 10 lines you want to go to the last one of them: "10Y']".  After inserting several lines with the "p" command you want to jump to the lowest inserted line: "p']".  This also works for text that has been inserted.

と、それをほのめかすような記述もありますが正直かなりわかりにくいかと思います。また、そのような記述があるにしても `'<` や ``<` などは正しく分けて表記されているのを見ると改善できないか、と思います。

**Comment by ynkdir** [comment]
いちおうその節の最初に説明があります。

```
7. Marks                    *mark-motions* *E20* *E78*

Jumping to a mark can be done in two ways:
1. With ` (backtick):     The cursor is positioned at the specified location
              and the motion is |exclusive|.
2. With ' (single quote): The cursor is positioned on the first non-blank
              character in the line of the specified location and
              the motion is linewise.
```

**Comment by machakann** [comment]
ほんとですね、見逃してました。各動作の説明からほんのり読み取ってましたけど、ちゃんとした記述があるのなら大丈夫ですね。この issue は閉じようかと思います。ありがとうございました。
