### ISSUE TITLE
<C-V>$ で作成された矩形に対するオペレータ

### ISSUE THREAD

**Issue by syngan** [vim-jp/issues#565]
`:h g@` に `CountSpaces()` の例がありますが、この方法では一番下の行が一番長い行でない場合に正しくスペースの数をカウントすることができません。これはどうやって実現するのが正解でしょうか
- ヘルプの内容が不十分だと思います。 `<C-V>$` の場合は対応していないとコメントを書くか、対応させるべきだと思います

**Comment by h-east** [comment]
確かにあの例だと指摘通りダメですね。

```
a a
 b b b b
cc
```
- `:h  g@`にあるサンプルを`.vimrc`にコピペしてVim起動
- 上記のバッファに対して `<C-V>G$`して`<F4>`押すと`3`と表示されてしまう。(正解は5)

`gv`コマンドを使うようにサンプルを変更するというのはどうでしょうか？

``` diff
diff -r 54d96e3b2eec runtime/doc/map.txt
--- a/runtime/doc/map.txt   Thu May 22 21:22:19 2014 +0200
+++ b/runtime/doc/map.txt   Sat May 24 12:31:15 2014 +0900
@@ -828,8 +828,8 @@
      let &selection = "inclusive"
      let reg_save = @@

-     if a:0  " Invoked from Visual mode, use '< and '> marks.
-       silent exe "normal! `<" . a:type . "`>y"
+     if a:0  " Invoked from Visual mode, use gv command.
+       silent exe "normal! gvy"
      elseif a:type == 'line'
        silent exe "normal! '[V']y"
      elseif a:type == 'block'
```

**Comment by syngan** [comment]
良くわかっていないのですが,  `a:type='block'` のときには `<C-v>$` なものってありえないのでしょうか？
それがないのなら、 `gv` で良いと思います。

**Comment by h-east** [comment]
ノーマルモードで`<F4>`が押された時に呼ばれる`CountSpaces()`の引数は1つです。
(`:h g@`に`関数の引数には、文字列が一つ渡されます:`と記述あります)
ビジュアルモード選択時に`<F4>`が押された時のみ `if a:0`が真になります。
(サンプルの `vmap`で`CountSpaces()`に引数を2つ指定しているため)

ですのでビジュアルモード選択時の挙動は`if a:0`が真の部分のみ考慮すれば良いということになります。

**Comment by syngan** [comment]
はい。ビジュアルモード選択の挙動が `if a:0` のところしか通らないことは理解しています。

> `a:type='block'` のときには `<C-v>$` なものってありえないのでしょうか？

ビジュアルモード選択以外のときに `<C-V>$` で作った矩形はありえないのか？
`<C-v>$` の矩形を返すテキストオブジェクトは作れそうな気がしますが、どうなのかなという疑問でした。

と。試してみます。

**Comment by syngan** [comment]
:h g@

> ```
>                        "block" {motion} は矩形 |blockwise-visual|
>                     "block" はたまにしか使われません。ビジュアルモードの場
>                     合だけ渡されるのですが、"g@" と合わせてもそれほど便利
>                     ではないからです。
> ```

ん？？そもそも `a:type=='block'` の判定自体がいらない感じですか？？？？

**Comment by h-east** [comment]
~~この件でいろいろ操作していたらビジュアルモードのバグ見つけたのでIssue登録しました。ピャー~~
~~#568~~

**Comment by h-east** [comment]
> ん？？そもそも a:type=='block' の判定自体がいらない感じですか？？？？

たぶんいらないと思います。

上のpatch(https://github.com/vim-jp/issues/issues/565#issuecomment-44076784) に
「`a:type=='block'`の条件いらないんじゃね？」と添えて投稿してみます。

**Comment by h-east** [comment]
vim_devに送りました。
https://groups.google.com/d/msg/vim_dev/zsMZoKEjhgk/PViI4Tv3DWoJ

**Comment by h-east** [comment]
`elseif a:type == 'block'`のブロック要るん？に対してBramから返信があった。

> Right, it can be removed.  I wonder if there is an example where "block" 
> would matter.  Perhaps when changing text, e.g. adding a number to all 
> numbers in the selected area.  That's much more complicated though.

後半がよく分かんないだけど何か返した方がいいですか？

**Comment by syngan** [comment]
vim_dev への報告ありがとうございました。

> 後半がよく分かんないだけど何か返した方がいいですか？

私も良くわからんですし、放置で構わないです。。

**Comment by h-east** [comment]
rev.5968:92751673cc37 で取り込まれました。
`elseif a:type == 'block'`の部分も削除されました。

https://github.com/vim-jp/vim/commit/999af5d7c2d7e5bff53177445e24ce1156d66861#diff-28587d36c24b61c33d4d01601f5974eeL831

@syngan Issue登録ありがとうございました:+1:
