### ISSUE TITLE
:e scp://user@host/するとuserhostに繋ぎにいく

### ISSUE THREAD

**Issue by ompugao** [vim-jp/issues#566]
.vimrcを空にした状態でvimを起動し、

```
:e scp://user@host/
```

するとnetrwのbufferに
ssh: connect to host userhost port 22: Connection refused
と表示されます。

```
:e scp://user@host/hoge/
```

などと存在するディレクトリを指定するときちんと動きます。

homebrewでいれたversion 7.4.273と
ubuntu12.04に自前コンパイルしたversion 7.4.246や7.4.307で動かないことを確認できました。
ubuntu12.04にaptでいれたversion 7.3.429では動きます。

プロvimmerの方々、どうぞよろしくお願いいたします。

//どのversionから動かなくなったか調べるのはどうすれば楽できるんでしょうか

**Comment by k-takata** [comment]
> ubuntu12.04に自前コンパイルしたversion 7.4.246や7.4.307で動かないことを確認できました。

netrw のバージョンは、7.4.246 が v151、7.4.307 が v152 ですので、v149, v150 辺りがどうなのかが気になります。
以下のバージョンを調べていただけますか。
7.4.155 (v149)
7.4.156 (v150)

> //どのversionから動かなくなったか調べるのはどうすれば楽できるんでしょうか

基本は二分探索でしょう。
hg bisectを使えば自動で二分探索してくれるので楽らしいです。(私は使ったことありませんが。)

**Comment by ompugao** [comment]
調べてみました。
7.4.155 (v149): 動く
7.4.156 (v150): 動かない
v150からみたいですね

**Comment by mattn** [comment]
https://code.google.com/p/vim/source/diff?spec=svn350272cbf1fd8371aeb93a12fbf0d11708fb2776&r=350272cbf1fd8371aeb93a12fbf0d11708fb2776&format=side&path=/runtime/autoload/netrw.vim#sc_svn605c9ce57ec378fe0e4c15a8bdd9923182064f08_9265

ここの

``` diff
@@ -9537,12 +9809,12 @@
 fun! s:RemotePathAnalysis(dirname)
 "  call Dfunc("s:RemotePathAnalysis(a:dirname<".a:dirname.">)")

-  let dirpat  = '^\(\w\{-}\)://\(\w\+@\)\=\([^/:#]\+\)\%([:#]\(\d\+\)\)\=/\(.*\)$'
+  let dirpat  = '^\(\w\{-}\)://\(\(\w\+\)@\)\=\([^/:#]\+\)\%([:#]\(\d\+\)\)\=/\(.*\)$'
   let s:method  = substitute(a:dirname,dirpat,'\1','')
-  let s:user    = substitute(a:dirname,dirpat,'\2','')
-  let s:machine = substitute(a:dirname,dirpat,'\3','')
-  let s:port    = substitute(a:dirname,dirpat,'\4','')
-  let s:path    = substitute(a:dirname,dirpat,'\5','')
+  let s:user    = substitute(a:dirname,dirpat,'\3','')
+  let s:machine = substitute(a:dirname,dirpat,'\4','')
+  let s:port    = substitute(a:dirname,dirpat,'\5','')
+  let s:path    = substitute(a:dirname,dirpat,'\6','')
   let s:fname   = substitute(a:dirname,'^.*/\ze.','','')

 "  call Decho("set up s:method <".s:method .">")
```

これですね。番号が合ってない気がする。

**Comment by ghost** [comment]
全体的に眺めていると user から @ を取り除く試みがいくつか見られますが、場所によって user と machine を '@' でつなぎ直す処理をしていたりいなかったりするので、全プロトコルの全箇所にその視点で目を入れるのはちょっと骨かなとは思います。

ftpurm、scpurm などの正規表現で一発デコードする試みもわりと失敗してますし、相当鍛え直す覚悟が必要かという気はします。

**Comment by mattn** [comment]
だいいち項目取り出すのに matchstr でなく substitute 使ってるのも危険ですしね。

**Comment by ghost** [comment]
そのへんはプログラマとスクリプタの微妙なセンスの問題かもしれません。

当面 let s:user = の \3 を \2 にすることで「'@'でつなぎ直し忘れているバグ(?)」をうまく利用した正常動作になるのかなと。ftp:// の方はそれでどうにかなるようです。scp:// もどうにかなることを薄く期待します。

**Comment by k-takata** [comment]
試してませんが、こんな感じですかね。
https://gist.github.com/k-takata/0cb149f4b6b3cb8bd978

**Comment by ompugao** [comment]
k-takataさんのpatchをv7.4.307にあてるときちんと動きました
ありがとうございます

**Comment by k-takata** [comment]
Charles Campbell氏宛にメールで報告しておきました。
以前、[あまりvim_devに投げないでほしいと言われた](https://groups.google.com/d/msg/vim_dev/iEiInCavWKc/8ytDomu8wTEJ)からなのですが、それ以外に他の人にも見える場所が無いのか聞いておきました。

**Comment by mattn** [comment]
githubで開発してくれたらいいのに

**Comment by k-takata** [comment]
> I believe that this issue has already been resolved.  Please try v153d of netrw, which you may get from my website:
> 
>   http://www.drchip.org/astronaut/vim/index.html#NETRW
> 
> (I believe the problem was resolved with netrw v151, actually)

v150以降でダメだと言ったところ、v152 でもダメだということを言わなかったために、こう返されてしまいました。v153d で試してくれとのことですが、たぶんダメですよね？

**Comment by k-takata** [comment]
> githubで開発してくれたらいいのに

激しく同意。

**Comment by k-takata** [comment]
私も試してみたところ、v152 に私のパッチを当てない状態で scp://user@host/ は開けました。
それ以外のプロトコルは未確認です。(もう一回状況を整理した方が良さそう。)

**Comment by k-takata** [comment]
@ompugao v153e が公開されました。お試しください。

**Comment by k-takata** [comment]
> Charles Campbell氏宛にメールで報告しておきました。
> 以前、あまりvim_devに投げないでほしいと言われたからなのですが、

ちょっと誤解していたようで、「vim_devに投げてもいいけど、そのときは、メールの宛先に自分を入れてほしい。見落とすといけないので。」という話でした。

**Comment by Shougo** [comment]
> githubで開発してくれたらいいのに

おそらく、サポートが大変になるからやらないのでしょう。
わざと敷居を高くしている可能性がありそうです。

**Comment by k-takata** [comment]
7.4.566直後のコミットにNetrw v153が取り込まれました。
この修正も含まれています。
