### ISSUE TITLE
<C-a>でintの最大値に対してインクリメントした場合値が戻る

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#57]
再現手順：バッファに”4294967295"と書いてその上で`<C-a>` => "-4294967295"
うまく文字列のままでインクリメントできないですかね...

**Comment by koron** [comment]
BigIntの実装を書けば良い。BCDとか真面目にやらないで、文字列ベースでも十分。
int64_tにするのは問題の先送りに過ぎないので意味が無いだろう。

**Comment by tyru** [comment]
とりあえず知識がまったくないので自分には書けそうにないですね...(すぐには

**Comment by koron** [comment]
https://gist.github.com/1256879

文字列ベースで足し算&引き算するサンプルを書いた。
計算結果がマイナスになるケース(正確には符号が反転するというべき)だけ未実装。

```
$ gcc numstr.c
$ ./a.out 9999999999999999 + 1
9999999999999999 + 1 = 10000000000000000
$ ./a.out  10000000000000000 - 1
10000000000000000 - 1 = 9999999999999999
```

実行するとこんな感じで、メモリの許す限りの桁数の足し算、引き算ができる。

あとはコレを整理してVimに突っ込むだけ。

**Comment by tyru** [comment]
おお！

あとは
1. マイナスになるケース
2. octal,hexとかにも対応
とかでしょうか。

**Comment by koron** [comment]
マイナスになるケースはソースコード中のFIXMEのところ参照して実装してください。

octalとhex(もしくはそれ以外の基数)は、digitとnとの相互変換、それに桁あふれの処理だけ直せば対応できます。
本当はそれらはコールバックで与えたいところですね。ただhexとoctalは元の桁を超えないほうが良いかもとは思います。
そららが必要になるプログラミングのユースケースでは、32bitが勝手に64bitになるっていうのは嫌われそう。

**Comment by koron** [comment]
あ、ちなみに私はこの件にはこれ以上の関与をしないつもりなので、上記サンプルは好きに使ってください。

**Comment by koron** [comment]
あと…Vimに組み込む場合は src/ops.c の do_addsub() 関数が修正対象になります。

**Comment by tyru** [comment]
了解です。ちょっと挑戦してみようと思います。

**Comment by thinca** [comment]
Vim script レベルでもなんとかなりそう…とか思ったり。

**Comment by h-east** [comment]
話ちょっとそれますが、曜日とか全角数字とかctrl-a ctrl-x 出来るとおもしろいかも。
Vim scriptでもうあったりするの？

**Comment by thinca** [comment]
monday.vim や toggle.vim というのがありますね。ただ、どちらもカスタマイズ性に難ありなので改良版を作る、と、私の TODO リストに書いてあります(どうでもいい)。

**Comment by k-takata** [comment]
これ、数値をunsigned longで扱っていたんですね。なので、64bit Linuxだと 2<sup>64</sup> - 1 まで扱えますが、Windowsだと 2<sup>32</sup> - 1 までしか扱えないと。

**Comment by k-takata** [comment]
https://github.com/vim-jp/issues/issues/161#issuecomment-173893352 にも書きましたが、64bit 整数を使うようにしたパッチを書いてみました。

> そららが必要になるプログラミングのユースケースでは、32bitが勝手に64bitになるっていうのは嫌われそう。

気になるのは、これですね。全環境統一して64bitの方がいいんじゃないのとは思いますが。

**Comment by tyru** [comment]
確かに64bit対応させればほぼこちらも対応は必要無くなりそうですね…

**Comment by koron** [comment]
材料はそろっていてあとは組み込むだけの状態。
また代替手段 (64bit 対応) も提案(vim-devにまで行ってる)されている。

故にコレは duplicated で閉じます。
