### ISSUE TITLE
vim-users.jp の過去記事掲載について

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#571]
vim-users.jp のドメインが失効した様です。
過去記事ですがなかなか良い物もあり、出来れば復元してあげたいと思っています。

私のほうで webarchive から拾い、jekyll のポスト形式(本文とヘッダ)に復元しましたが。私の単独で決めるのはどうかと思いましたので、以下アンケートを取りたいと思います。

:+1: (`:+1:`)もしくは :-1: (`:-1:`)でお答えください。ご意見も募集します。

**Comment by thinca** [comment]
記事の執筆者全員に転載許可を得るという前提付きで :+1: 
私の記事についてはもちろんOKです :smile:

**Comment by mattn** [comment]
記事著者を grep しますんで少しお待ちを。

**Comment by thinca** [comment]
一応確認ですが、復元する、と言うのは、vim-jp.org 以下に転載する、と言うことで良いでしょうか?
だとしたら vim-jp/vim-jp.github.com の Issue にした方が良かったかも?

**Comment by mattn** [comment]
あー、失礼
