### ISSUE TITLE
substitute()での '\<\|\>'で文字化け

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#572]
let l = 'あxい'
let p = '\<\|\>'
で
echo split(l, p)
を実行すると、['あ', 'x', 'い'] が期待どおり出力されるが、
echo substitute(l, p, '@', 'g')
を実行するとバイト単位で処理されて文字化けする。
utf-8でもcp932でも同じ現象です。
コマンドラインでの
s/\<\|\>/@/g
は文字単位で正しく処理されます。

version 7.4.274
version 7.3.1314

**Comment by mattn** [comment]
Ubuntu 14.04 で再現しました。

**Comment by rickhowe** [comment]
'\zs' でも、
s/\zs/@/g
は文字単位
substitute(l, '\zs', '@', 'g')
はバイト単位で処理されます。

**Comment by mattn** [comment]
#503 と絡んでる気がしますがどうでしょう？ @ynkdir

**Comment by rickhowe** [comment]
'ABC' などの1バイト文字のみの場合でも、
s/\zs/@/g   ->  `@A@B@C`
substitute(l, '\zs', '@', ’g')   -> `@A@B@C@`
のように、最後の @ に違いがあります。

**Comment by k-takata** [comment]
`do_string_sub()` の中の以下の処理ですが、`tail`を1バイトではなく1文字進めないといけないのではないですかね？

```
            *((char_u *)ga.ga_data + ga.ga_len) = *tail++;
```

(`:s///`の処理ってどこでやっているのでしたっけ。)

**Comment by mattn** [comment]
`s:///` は nv_subst でやってます。

**Comment by mattn** [comment]
本体は `do_sub` すね。

**Comment by k-takata** [comment]
> 本体は do_sub すね。

do_string_sub() との差分を見ようかと思ったら…、魔境だった。そっ閉じ。

**Comment by ynkdir** [comment]
こん感じで…

``` diff
diff -r bed71c37618c src/eval.c
--- a/src/eval.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/eval.c    Wed Jun 04 20:27:40 2014 +0900
@@ -24848,8 +24848,11 @@
        if (zero_width == regmatch.startp[0])
        {
            /* avoid getting stuck on a match with an empty string */
-           *((char_u *)ga.ga_data + ga.ga_len) = *tail++;
-           ++ga.ga_len;
+           i = MB_PTR2LEN(tail);
+           mch_memmove((char_u *)ga.ga_data + ga.ga_len, tail,
+                                   (size_t)i);
+           ga.ga_len += i;
+           tail += i;
            continue;
        }
        zero_width = regmatch.startp[0];
```

**Comment by ynkdir** [comment]
投げました
https://groups.google.com/d/msg/vim_dev/Cicq5a1GtwI/sLPX7TiqYxIJ

**Comment by ynkdir** [comment]
末尾の違いはいちおう報告済みですが伝わってるのやらないのやら

**Comment by k-takata** [comment]
修正前のコードもそうですが、ga のサイズを増やさずにコピーしていますが、大丈夫ですか？
ga_grow() を呼ぶ必要があるような。

**Comment by ynkdir** [comment]
下のところで確保してるので大丈夫なはず…です

**Comment by k-takata** [comment]
あー、ここに来るのは初回以外だから必ず下で確保されている訳ですか。
前回のループでマッチした部分より後の文字列の分のメモリは確保してあるから大丈夫と。

**Comment by h-east** [comment]
vim_devで `#ifdef FEAT_MBYTE` を使わないの？って言われてますね。

**Comment by k-takata** [comment]
7.4.323
https://groups.google.com/d/topic/vim_dev/sDShsNCbcvU/discussion

**Comment by mattn** [comment]
@ynkdir ++
