### ISSUE TITLE
cmd.exe 版で「ﾎﾞ」が入力出来ない。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#573]
どうも何かのキーと間違われているらしく、「ﾎﾞ」を入力すると「1」になる。
vgetorpeek の中で「ﾎ」(0xCE) 正しく返らない。ちなみに「ﾎ」だけだとOK。濁点が入る(2バイト以上？)とNG。
時間が無いので後で調査しますが、解析出来る人よろしく。

**Comment by tyru** [comment]
ﾎﾞ

**Comment by mattn** [comment]
1

**Comment by mattn** [comment]
そもそも termcode がかぶりまくってるのなんなの

![](http://go-gyazo.appspot.com/cc46f642110d5894.png)

**Comment by k-takata** [comment]
keymap.h

``` C
/*
 * For MSDOS some keys produce codes larger than 0xff. They are split into two
 * chars, the first one is K_NUL (same value used in term.h).
 */
#define K_NUL                   (0xce)  /* for MSDOS: special key follows */
```

うーん。

**Comment by mattn** [comment]
この 0xCE を他の値にしないと解決できそうにない。
もしくは mch_inchar で K_NUL でエスケープしちゃうか。

**Comment by k-takata** [comment]
os_msdos.c には、"K_NUL -> K_NUL, 3" なんてコメントが。
同じようにエスケープすれば良さそう？

**Comment by mattn** [comment]
それか、0xce って特に決まった値じゃないと思うので 0xff あたりに直すのもありかも。

**Comment by mattn** [comment]
まずは K_NUL を 0xff にするパッチ

https://gist.github.com/b6341a1d272aa80431c5

**Comment by mattn** [comment]
ちなみに↑ので「ﾎﾞ」は入力出来ました。もう1個のパッチ、エスケープはunicodeと非常に相性が悪そう。。。

**Comment by k-takata** [comment]
> エスケープはunicodeと非常に相性が悪そう。。。

そういえば mch_inchar って何か見覚えがあるなと思ったら、 #189 でいじった関数だった。
確かにエスケープするとエンコーディング変換が面倒ですね。かと言ってUnicode APIでの書き直しも簡単ではないですし。

**Comment by 0xBADDCAFE** [comment]
https://github.com/vim-jp/issues/issues/573#issuecomment-45050471

パッチを適用して、「ﾎﾞ」 や 「ﾎﾚﾎﾚ」 が入力できました。他に試しておいたほうがいいことはあるでしょうか。

```

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  4 2014 22:44:54)
MS-Windows 64-bit console version
Included patches: 1-316
Huge version without GUI.  Features included (+) or not (-):

```

on Windows8 64bit です。

**Comment by mattn** [comment]
`<home>` などて map 出来るでしょうか？

On 6/4/14, 0xBADDCAFE notifications@github.com wrote:

> https://github.com/vim-jp/issues/issues/573#issuecomment-45050471
> 
> パッチを適用して、「ﾎﾞ」 や 「ﾎﾚﾎﾚ」 が入力できました。他に試しておいたほうがいいことはあるでしょうか。
> 
> ```
> 
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  4 2014 22:44:54)
> MS-Windows 64-bit console version
> Included patches: 1-316
> Huge version without GUI.  Features included (+) or not (-):
> 
> ```
> 
> on Windows8 64bit です。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/573#issuecomment-45092491

## 
- Yasuhiro Matsumoto

**Comment by 0xBADDCAFE** [comment]
すいません、意図がつかめていないところがあります。

``` vim:
inoremap <HOME> ﾎﾞ
inoremap ﾎﾞ <HOME>
```

こういうのがきちんと map されるかどうか、ということでしょうか。
上記は試して、`:map` できちんと登録されているのは確認できました。

<s>(cmd.exe で `<HOME>` を動かす方法がわからなかったマン)</s>

**Comment by 0xBADDCAFE** [comment]
すいません、今再度試したら普通に `<HOME>` 動きました。
なので、`:inoremap <HOME> ﾎﾞ` して `<HOME>` でﾎﾞが入力できている状態です。

**Comment by mattn** [comment]
たすかります。いけてそうです。

**Comment by k-takata** [comment]
[ISO 8859-1](http://ja.wikipedia.org/wiki/ISO/IEC_8859-1) などでは 0xFF には文字が割り当てられていますね。（0xCE にも割り当てられていますが。）

**Comment by mattn** [comment]
むむむーどうしよう。

**Comment by mattn** [comment]
投げた方がいいかな。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/cMthzbnBWBo

**Comment by k-takata** [comment]
> What is supposed to happen is that 0xce is replaced by K_NUL 3.
> What is the reason that is not working?  Perhaps the translation of 0xce
> to K_NUL and 3 is missing somewhere?
> 
> Changing K_NUL to 0xff will only move the problem to another character.

0xce は K_NUL 3 に置き換えるのを想定していて、0xff に変更するのは問題を別の文字に変えるだけだと。

**Comment by ghost** [comment]
こんなんでどうでしょう…

``` diff
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Fri Jun 06 19:23:40 2014 +0900
@@ -1785,12 +1785,19 @@
 #endif
        {
        int n = 1;
-
+                int     s = 0;
+
+                if (typeaheadlen > 0 && typeahead[typeaheadlen - 1] == K_NUL)
+                {
+                    typeahead[typeaheadlen] = 3;
+                    n++;
+                    s++;
+                }
        /* A key may have one or two bytes. */
-       typeahead[typeaheadlen] = c;
+       typeahead[typeaheadlen + s] = c;
        if (ch2 != NUL)
        {
-           typeahead[typeaheadlen + 1] = ch2;
+           typeahead[typeaheadlen + s + 1] = ch2;
            ++n;
        }
 #ifdef FEAT_MBYTE
```

**Comment by h-east** [comment]
@mattn 確認です。以前は ﾎﾞ と入力出来ていたのがどこかVer.の時点で入力出来なくなったのですか？それとも今までずっとおかしかったのですか？

**Comment by mattn** [comment]
たぶんこのコードだとずっとおかしかったんだと思います。

**Comment by mattn** [comment]
@ntak 

```
typeahead[typeaheadlen], 3;
```

この行、どういう意味でしょうか？

**Comment by k-takata** [comment]
`typeahead[typeaheadlen] = 3;` の間違い？

**Comment by ghost** [comment]
`typeahead[typeaheadlen] = 3;` を意図したタイプミスです…(;´Д`)いやー…

**Comment by mattn** [comment]
↑のntakさんのコメント治しました。

**Comment by mattn** [comment]
パッチ試し中です。しばらくお待ちを。

**Comment by mattn** [comment]
@ntak んー、だめっぽいす。

「ﾎ」だけ入力 → タイムアウト後に「ﾎ」だけ入力
「ﾎﾞ」を入力 → タイムアウト後に「ﾎ」しか入力されない

**Comment by ghost** [comment]
ありがとうございます、さらに追及してみます…。

**Comment by k-takata** [comment]
まず、decode_key_event() の中で 0xce を K_NUL,3 に変換する処理が必要ではないでしょうか。
あとは、getchar.c の vgetc() も対策必要？
`enc=utf-8` の場合、変換後が 0xce を含んでいたらどうなるのだろう？

**Comment by ghost** [comment]
いま k-takata さんと書き込みが前後しまして、いったん撤回したんですが一応記録として現況を。
os_msdos.c の K_NUL の少なさからいって手を入れる箇所は少ない気がしてはみたんです。
あと、「タイムアウト」の再現手順をいただけますか？いまいちわかっておりませんで失礼を…。

``` diff
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Fri Jun 06 21:03:29 2014 +0900
@@ -1636,7 +1636,7 @@
 #endif

     /* First use any typeahead that was kept because "buf" was too small. */
-    if (typeaheadlen > 0)
+    if (typeaheadlen > 0 && typeahead[typeaheadlen - 1] != K_NUL)
    goto theend;

 #ifdef FEAT_SNIFF
@@ -1785,12 +1785,19 @@
 #endif
        {
        int n = 1;
-
+                int     s = 0;
+
+                if (typeaheadlen > 0 && typeahead[typeaheadlen - 1] == K_NUL)
+                {
+                    typeahead[typeaheadlen] = 3;
+                    n++;
+                    s++;
+                }
        /* A key may have one or two bytes. */
-       typeahead[typeaheadlen] = c;
+       typeahead[typeaheadlen + s] = c;
        if (ch2 != NUL)
        {
-           typeahead[typeaheadlen + 1] = ch2;
+           typeahead[typeaheadlen + s + 1] = ch2;
            ++n;
        }
 #ifdef FEAT_MBYTE
```

**Comment by k-takata** [comment]
> まず、decode_key_event() の中で 0xce を K_NUL,3 に変換する処理が必要ではないでしょうか。

やっぱり必要なかったかも。すみません。

**Comment by mattn** [comment]
この方が簡単じゃないです？変換後の文字列に対しても有効ですし。
(あ、でも途中にあるとどうだろ)

``` diff
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Fri Jun 06 21:58:17 2014 +0900
@@ -1805,6 +1805,14 @@
                n + unconverted, TYPEAHEADLEN - typeaheadlen,
                rest == NULL ? &rest : NULL, &restlen);
        }
+       if (typeahead[typeaheadlen] == K_NUL)
+       {
+           int i = 0;
+           for (i = TYPEAHEADLEN-1; i > typeaheadlen; i--)
+           typeahead[i] = typeahead[i-1];
+           typeahead[typeaheadlen + 1] = 3;
+           n++;
+       }
 #endif

        /* Use the ALT key to set the 8th bit of the character
```

**Comment by mattn** [comment]
デバッガで見て、とりあえずBramの言うとおり、つまり

`ﾎﾞ` ならば `ﾎ` `0x03` `ﾞ` となる様になったのですが、やっぱりうまく行きませんね。

**Comment by mattn** [comment]
あーわかった。

``` diff
diff -r bed71c37618c src/getchar.c
--- a/src/getchar.c Thu May 29 14:36:29 2014 +0200
+++ b/src/getchar.c Fri Jun 06 22:35:36 2014 +0900
@@ -1699,7 +1699,7 @@
        c = CSI;
 #endif
    }
-#ifdef MSDOS
+#if defined(MSDOS) || (defined(WIN3264) && !defined(FEAT_GUI))
    /*
     * If K_NUL was typed, it is replaced by K_NUL, 3 in mch_inchar().
     * Delete the 3 here.
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Fri Jun 06 22:35:36 2014 +0900
@@ -1838,6 +1838,16 @@
            typeahead[typeaheadlen++] =  modifiers;
        }

+#ifdef FEAT_MBYTE
+       if (typeahead[typeaheadlen] == K_NUL)
+       {
+           int i = 0;
+           for (i = TYPEAHEADLEN-1; i > typeaheadlen; i--)
+           typeahead[i] = typeahead[i-1];
+           typeahead[typeaheadlen + 1] = 3;
+           n++;
+       }
+#endif
        typeaheadlen += n;

 #ifdef MCH_WRITE_DUMP
```

**Comment by mattn** [comment]
下の部分は変換後文字列内に 0xCE があった場合にちゃんとシフトする様にしないといけない。

**Comment by mattn** [comment]
最終パッチ

``` diff
diff -r bed71c37618c src/getchar.c
--- a/src/getchar.c Thu May 29 14:36:29 2014 +0200
+++ b/src/getchar.c Fri Jun 06 22:51:58 2014 +0900
@@ -1699,7 +1699,7 @@
        c = CSI;
 #endif
    }
-#ifdef MSDOS
+#if defined(MSDOS) || (defined(WIN3264) && !defined(FEAT_GUI))
    /*
     * If K_NUL was typed, it is replaced by K_NUL, 3 in mch_inchar().
     * Delete the 3 here.
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Fri Jun 06 22:51:58 2014 +0900
@@ -1805,6 +1805,21 @@
                n + unconverted, TYPEAHEADLEN - typeaheadlen,
                rest == NULL ? &rest : NULL, &restlen);
        }
+
+       /* Convert K_NUL in input characters. */
+       {
+           char_u  *p = typeahead + typeaheadlen;
+           char_u  *e = typeahead + TYPEAHEADLEN;
+           while (*p && p < e) {
+           if (*p == K_NUL) {
+               p++;
+               mch_memmove(p, p + 1, 1);
+               *p = 3;
+               n++;
+           }
+           p++;
+           }
+       }
 #endif

        /* Use the ALT key to set the 8th bit of the character
```

**Comment by mattn** [comment]
でもこれだと `<home>` とか `<pagedown>` なんかが動かなくなった。

**Comment by ynkdir** [comment]
2バイト目が 0xCE の文字も引っかかります "ば" とか

**Comment by mattn** [comment]
2バイト目が 0xCE でも入力は出来てるのですが、その後でノーマルモードに戻るみたいな動きをしてますね。

**Comment by ghost** [comment]
どうも `vim -u NONE -U NONE --noplugin` で再現しました、基本を忘れておりました…。
でその再現する分については、直前の私のパッチと mattn さんの ifdef を合わせるとなんとなく解消するようではあります。まとめてみると：

``` diff
diff -r bed71c37618c src/getchar.c
--- a/src/getchar.c Thu May 29 14:36:29 2014 +0200
+++ b/src/getchar.c Fri Jun 06 23:19:46 2014 +0900
@@ -1699,7 +1699,7 @@
        c = CSI;
 #endif
    }
-#ifdef MSDOS
+#if defined(MSDOS) || (defined(WIN3264) && !defined(FEAT_GUI))
    /*
     * If K_NUL was typed, it is replaced by K_NUL, 3 in mch_inchar().
     * Delete the 3 here.
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Fri Jun 06 23:19:46 2014 +0900
@@ -1636,7 +1636,7 @@
 #endif

     /* First use any typeahead that was kept because "buf" was too small. */
-    if (typeaheadlen > 0)
+    if (typeaheadlen > 0 && typeahead[typeaheadlen - 1] != K_NUL)
    goto theend;

 #ifdef FEAT_SNIFF
@@ -1785,12 +1785,19 @@
 #endif
        {
        int n = 1;
-
+                int     s = 0;
+
+                if (typeaheadlen > 0 && typeahead[typeaheadlen - 1] == K_NUL)
+                {
+                    typeahead[typeaheadlen] = 3;
+                    n++;
+                    s++;
+                }
        /* A key may have one or two bytes. */
-       typeahead[typeaheadlen] = c;
+       typeahead[typeaheadlen + s] = c;
        if (ch2 != NUL)
        {
-           typeahead[typeaheadlen + 1] = ch2;
+           typeahead[typeaheadlen + s + 1] = ch2;
            ++n;
        }
 #ifdef FEAT_MBYTE
```

**Comment by ghost** [comment]
あっ変換後の方…

**Comment by mattn** [comment]
KeyTyped 見た方がいいのかな

On 6/6/14, Nobuhiro Takasaki notifications@github.com wrote:

> あっ変換後の方…
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/573#issuecomment-45343322

## 
- Yasuhiro Matsumoto

**Comment by ghost** [comment]
私の方では変換前に0xCE を潰してますんで、ここでやってる termencode -> encode の変換作業で 0xCE を一バイト目に含まないマルチバイト文字が変換後 0xCE が一バイト目に来るような文字に化けるケースは超々レア、言い換えればゼロという扱いで通ったらいいなあとは思います。
そんなロケールもあるかもしれないけど、あったらその時にあらためて考えようという感じで…。

**Comment by k-takata** [comment]
UTF-8 で　0xCE を含むのは CE 80 ～ CE BF、コードポイントで言うと U+0380 ～ U+03BF。
ギリシャ文字らしい。 http://utf8-chartable.de/unicode-utf8-table.pl?start=896&number=128
Shift_JIS だとギリシャ文字は 83xx の辺りなので、日本語環境なら問題なさそう。

**Comment by ghost** [comment]
変換後の文字をいじるとてきめん駄目ですねなんか…。
0xCE 0x03 の 0x03 が Ctrl+C に見えてますかね、あまりよくありません。
ここは K_NUL にすることでコードの変換をスキップさせたいという意図だと思うので、これは変換後は見ずに通してしまってもいいかなと思わなくもないです。

**Comment by ghost** [comment]
キリル文字と混同してました(;´Д`)このツラ文字のクチ部分(Д)。大丈夫そうですね。
vim_dev への提出にあたって付け足すべきことを緩募します。何かあればお願いします。

なんか横から入って持っていくみたいな形になってしまってますが、どうもすみません…。

**Comment by ynkdir** [comment]
ntak さんのパッチも "ば" (2バイト目が0xCEの文字) の入力がうまくいかないです。

**Comment by ghost** [comment]
あれ(;´Д`)やってもうた…再考します、ってこればっかですな、落ち着かないといかん…

**Comment by ghost** [comment]
「ば」は潰しました。他の不具合があれば…。

``` diff
diff -r bed71c37618c src/getchar.c
--- a/src/getchar.c Thu May 29 14:36:29 2014 +0200
+++ b/src/getchar.c Mon Jun 09 01:28:39 2014 +0900
@@ -1699,7 +1699,7 @@
        c = CSI;
 #endif
    }
-#ifdef MSDOS
+#if defined(MSDOS) || (defined(WIN3264) && !defined(FEAT_GUI))
    /*
     * If K_NUL was typed, it is replaced by K_NUL, 3 in mch_inchar().
     * Delete the 3 here.
@@ -1798,6 +1798,10 @@
            if (vgetorpeek(TRUE) == (int)KE_CSI && c == KS_EXTRA)
            buf[i] = CSI;
        }
+#if defined(WIN3264) && !defined(FEAT_GUI)
+                else if (buf[i] == K_NUL)
+                    (void)vgetorpeek(TRUE);
+#endif
        }
        --no_mapping;
        c = (*mb_ptr2char)(buf);
diff -r bed71c37618c src/os_win32.c
--- a/src/os_win32.c    Thu May 29 14:36:29 2014 +0200
+++ b/src/os_win32.c    Mon Jun 09 01:28:39 2014 +0900
@@ -1785,12 +1785,19 @@
 #endif
        {
        int n = 1;
-
+                int     s = 0;
+
+                if (c == K_NUL)
+                {
+                    typeahead[typeaheadlen + 1] = 3;
+                    n++;
+                    s++;
+                }
        /* A key may have one or two bytes. */
        typeahead[typeaheadlen] = c;
        if (ch2 != NUL)
        {
-           typeahead[typeaheadlen + 1] = ch2;
+           typeahead[typeaheadlen + s + 1] = ch2;
            ++n;
        }
 #ifdef FEAT_MBYTE
```

**Comment by mattn** [comment]
変換後に「ば」になる様なケースってないんですっけ。

**Comment by mattn** [comment]
あと 0x3 を入れる事で変換出来なくなるケースとか。

**Comment by ghost** [comment]
変換後の「ば」は日本語環境に限定すれば `set termencoding=(cp932以外のなにか) encoding=cp932` でないと発生しないもので、かつ termencoding は cmd.exe なので cp932 限定である(っけ?)関係から、ないと判断して差し支えないと思います。
0x03 についてはそうですね、見るように変更します。

**Comment by ghost** [comment]
いまだ `:imap a ﾎﾞ` で a をタイプすると `1` になりますね、これも潰さないと…

**Comment by ynkdir** [comment]
"ば" 確認しました。ありがとうございます。
ただこんどはカーソルキーとかのファンクションキーが効かなくなってます。

気づいたんですが
K_NUL 3 に置き換えだと `:call feedkeys("iﾎ\<C-C>")` ができなくなりますが
これはしょうがないですね。

**Comment by mattn** [comment]
そこで KeyTyped を見た方がいいのかなーと思ってます。

**Comment by ynkdir** [comment]
あーそか K_NUL 3 に置き換えても feedkeys("ﾎﾞ") はだめなのか。
imap と同じか。
たぶん imap はどうしようもないですねこれ。

> KeyTyped

なるほどー。

termcap のほうをいじるのはありですかね
termcap の設定を unix 風にして mch_input() で変換する
めんどいですね…

**Comment by ghost** [comment]
今 `:imap a ﾎﾞ` を潰してきたところですが、`:call feedkeys("iﾎﾞ")` がいけてませんね…
なんだか無理線をひた走っている気がしないでもないです…。
https://gist.github.com/ntak/3dddde1b3f2d09deff18

カーソルキーなどの不具合はこのまま手を詰めていけば取れるような感じではあります。
KeyTyped が現状よくわかってないのでわかるように見ていきます。

**Comment by ynkdir** [comment]
win32 の termcap て windows の仕様じゃなくて vim が定義してるのか。
なら変えるのもありなような…。

**Comment by mattn** [comment]
一番最初に↑書いたパッチがそれですね。

**Comment by ynkdir** [comment]
あーほんとだ(汗
0xFF に変えるだけがだめなら unix 風に ^[ﾎｹﾞ みたいに 3,4 バイトならどうかなと思いました。

**Comment by ynkdir** [comment]
> 今 :imap a ﾎﾞ を潰してきたところですが、:call feedkeys("iﾎﾞ") がいけてませんね…

K_NUL 3 にエスケープする方法はアドホックな対応なので個人的にはある程度で妥協するのがいいのではと思います。
imap feedkeys はしょうがないでいいのかなと。

**Comment by ynkdir** [comment]
というより imap や feedkeys で端末コードを生入力したら端末コードとして認識されるのがおそらく正解なので対応しちゃうのはまずい

**Comment by ghost** [comment]
巻き戻します。

**Comment by ghost** [comment]
とりあえずの形にはなりました。シンプルに：
https://gist.github.com/ntak/2cec8243a9236a2d5b81

**Comment by ynkdir** [comment]
お疲れさまです
"ﾎﾞ"、"ば"、ファンクションキーの入力を enc=cp932, enc=utf-8 で確認しました。OKだと思います。

たぶんmattnさんのtermcap変更パッチが王道だと思うんですが
あとはbramしだいですか…

**Comment by ghost** [comment]
一部明確でなかった部分に手を入れました。(URLが同じだな…)
https://gist.github.com/ntak/2cec8243a9236a2d5b81

**Comment by mattn** [comment]
`imap a ﾎﾞ` 動きます？

**Comment by ghost** [comment]
今のロジックの原理上、コード変換が起きないときには動かないはずです `imap a ﾎﾞ`…
termencoding、encoding ともに cp932 の時に動かないのが再現できてます。
比較的すぐ修正できると思います。根は浅いかなと。

**Comment by ghost** [comment]
思ったら深かった…。
(encodeではなくmapの)文字列変換をする部分が CONV_NONE の時におそらく故意に働いてないです。
だから termencoding == encoding か、まっさら起動で何も設定がない状態では map が効いてないわけで…CONV_NONE の意味合いがそれ map の CONV も NONE だからヨロシク、という定義的な話になる気もします。
つーかこのパッチ、横道的ですか？(;´Д`)うーん…termcap 変更に時間を割くべきなのかな…

**Comment by ghost** [comment]
今気がついた(;´Д`)横すぎる、K_NUL 3 の用法が違う…なんか誤解してた
まあ動くけど妥当ではない気がすごくしている…採用されるパッチではないなこれ

**Comment by ghost** [comment]
一日がんばった結果、私はお手上げということにします。力及ばず…すみません。

**Comment by mattn** [comment]
たぶん方針的な物もあるので vim-dev に問題点報告して投げますか？ @ynkdir

**Comment by ynkdir** [comment]
そうですねー。おまかせします。

**Comment by ghost** [comment]
ふと思いついたので再挑戦した結果 CONV_NONE がなんとかいう話はなくなりました、termcode を変えてるのでこれは出せるかな…
https://gist.github.com/ntak/ef52ffe72ecad353ce91

**Comment by ghost** [comment]
あれ？っと、見直していたらまた似たような轍を踏んでいる気が…いや動くんですけども.
decode_key_event を三バイトに拡張しなくてもいいんじゃないの疑惑が発生しており、追試します。

追記：やはり拡張する必要はなかったので、gist の方をアップデートしておきました。
だいぶシンプル。

**Comment by mattn** [comment]
おかえりなさいまし

On 6/19/14, ntak notifications@github.com wrote:

> あれ？っと、見直していたらまた似たような轍を踏んでいる気が…いや動くんですけども.
> decode_key_event を三バイトに拡張しなくてもいいんじゃないの疑惑が発生しており、追試します。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/573#issuecomment-46452537

## 
- Yasuhiro Matsumoto

**Comment by ghost** [comment]
恥ずかしながら帰還いたしました(;´Д`)毎度難儀しております…

パッチの方ですが、termcodeを変えたらあの苦労はなんだったのかという感じで簡単に書けてしまったので、微妙な心持ちではあります。

**Comment by ghost** [comment]
持ち出しました：
https://groups.google.com/d/msg/vim_dev/cMthzbnBWBo/udEAq5xv1yIJ

**Comment by k-takata** [comment]
7.4.363
https://groups.google.com/d/topic/vim_dev/kvb-p4OmN2s/discussion
