### ISSUE TITLE
マルチバイトでのワードの区切り

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#574]
#572 と関連しますが、w や \< などでマルチバイト文字上でカーソルを動かすと、漢字、カタカナ、ひらがな、全角記号、ハングルの境界がワードとして認識されます。split() でも同様に分割されます。これは仕様でしょうか？それとも現実装でそうなっているだけでしょうか？ヘルプを探しても記述が見つかりません。gvim -u NONE でも同じ動きでしたので、文字クラスの定義がハードコードされているのでしょうか？

**Comment by mattn** [comment]
仕様です。unicodeの文字クラスから境界を判定しています。
(実装上仕様というレベルです)

**Comment by rickhowe** [comment]
ありがとうございます。確認ですが、現実装の文字クラスは、.NETと同様に、http://www.unicode.org/Public/UNIDATA/Blocks.txt での定義に基づき分類しているということでしょうか。

**Comment by k-takata** [comment]
実装は、mbyte.c の [dbcs_class()](https://code.google.com/p/vim/source/browse/src/mbyte.c?r=bed71c37618c11240596390f277d4f5e60d35ebc#903) と [utf_class()](https://code.google.com/p/vim/source/browse/src/mbyte.c?r=bed71c37618c11240596390f277d4f5e60d35ebc#2475) を参照してください。
Block.txt だと 16 文字のブロック単位になってしまいますので、Script.txt 辺りに基づいているのだと思いますが、どのUnicodeのバージョンかは知りません。

**Comment by mattn** [comment]
@ZBryce えと、何か問題があるんでしょうか？もし問題があるならその解決方法を考える事も出来ます。

**Comment by mattn** [comment]
問題が明確になったらお手数ですが再度openして下さい。
