### ISSUE TITLE
Perl 5.20 on windows のビルドに失敗する

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#575]
まーたーかーよー

**Comment by k-takata** [comment]
まーたーだーよー
https://groups.google.com/d/topic/vim_dev/6eB8k1pFD9A/discussion

**Comment by mattn** [comment]
Oh, GJ

**Comment by k-takata** [comment]
なお、Strawberry Perl 5.20 + MSVC の組み合わせでビルドすると、上記のパッチだけだと VC2012 まではコンパイルが通りません。(VC2013 は未確認だがおそらく通るはず)
stdbool.h をインクルードしようとするのですが、VC が stdbool.h に対応したのは VC2013 からなので。
一応、c:\strawberry\perl\lib\CORE\config.h をいじって `#define I_STDBOOL` を無効化すれば VC2012 以前でも通るようにはなります。
ActivePerl 5.20はまだ出ていないのでどうなるか分かりませんが、ActivePerl もコンパイラが MinGW になったので、同様の可能性が高いと思います。

**Comment by mattn** [comment]
ん？
ちなみに k-takata さんからパッチの所在を教えて貰う前に、まったくおんなじパッチが書けてたのですが、ビルド通ってましたよ？w

**Comment by k-takata** [comment]
VCのバージョンはいくつですか？

**Comment by mattn** [comment]
VS2012 です。

**Comment by k-takata** [comment]
ビルドが通らないのを確認したのは VC10 でした。
でも、VC11 にも stdbool.h は無いはずなのになぜ？

**Comment by k-takata** [comment]
VS2012 がインストールしてあったことに気づいて試してみました。

```
c:\strawberry\perl\lib\core\handy.h(77) : fatal error C1083: include ファイルを
開けません。'stdbool.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0
\VC\BIN\cl.EXE"' : リターン コード '0x2'
Stop.
```

やっぱりダメでした。
以下のパッチをperlに当てれば通ります。

``` diff
--- lib/CORE/config.h.orig  2014-06-06 22:36:37.584537600 +0900
+++ lib/CORE/config.h   2014-06-07 18:26:35.765691900 +0900
@@ -4290,7 +4290,7 @@
  * This symbol, if defined, indicates that <stdbool.h> exists and
  * can be included.
  */
-#define    I_STDBOOL       /**/
+/*#define  I_STDBOOL       / **/

 /* I_SUNMATH:
  * This symbol, if defined, indicates that <sunmath.h> exists and
```

**Comment by mattn** [comment]
変ですね。僕は何も出ませんでしたね。

On 6/7/14, K.Takata notifications@github.com wrote:

> VS2012 がインストールしてあったことに気づいて試してみました。
> 
> ```
> c:\strawberry\perl\lib\core\handy.h(77) : fatal error C1083: include ファイルを
> 開けません。'stdbool.h': No such file or directory
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio
> 11.0
> \VC\BIN\cl.EXE"' : リターン コード '0x2'
> Stop.
> ```
> 
> やっぱりダメでした。
> 以下のパッチをperlに当てれば通ります。
> 
> ``` diff
> --- lib/CORE/config.h.orig    2014-06-06 22:36:37.584537600 +0900
> +++ lib/CORE/config.h 2014-06-07 18:26:35.765691900 +0900
> @@ -4290,7 +4290,7 @@
>   *   This symbol, if defined, indicates that <stdbool.h> exists and
>   *   can be included.
>   */
> -#define  I_STDBOOL       /**/
> +/*#define    I_STDBOOL       / **/
> 
>  /* I_SUNMATH:
>   *   This symbol, if defined, indicates that <sunmath.h> exists and
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/575#issuecomment-45405886

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
7.4.321
https://groups.google.com/d/topic/vim_dev/K2jxv7NHMUw/discussion

**Comment by mattn** [comment]
@k-takata ++

**Comment by k-takata** [comment]
> ActivePerl 5.20はまだ出ていないのでどうなるか分かりませんが、ActivePerl もコンパイラが MinGW になったので、同様の可能性が高いと思います。

ActivePerl 5.20が出ていたので試してみましたが、やはりVC10だとstdbool.hが無いためコンパイルエラーとなりました。[上記のパッチ](https://github.com/vim-jp/issues/issues/575#issuecomment-45405886)を当てれば問題ありません。

**Comment by mattn** [comment]
ActivePerl 向けにダミーの stdbool.h を用意するってのはどうでしょう？
ActivePerl の場合だけ -I でパスを通しす。みたいな。

**Comment by k-takata** [comment]
config.hのパッチで十分かと考えていましたが、そういう手もありですかね。

> ActivePerl の場合だけ

上で書いているようにStrawberry Perlも同じです。mattnさんの環境では、どこの stdbool.h が参照されているのかが気になります。

**Comment by k-takata** [comment]
7.4.1011
https://groups.google.com/d/topic/vim_dev/a-ltRSaVh2Q/discussion
lib/CORE/config.h へのパッチは不要になりました。
