### ISSUE TITLE
Vim起動時にreplace modeになる

### ISSUE THREAD

**Issue by itchyny** [vim-jp/issues#578]
### 現象

Vimを起動すると、replace modeになる。
ソース: https://twitter.com/ayafmy/status/477406705274220545
### 期待する挙動

Vim起動後はnormal mode。
### 方法

```
 $ vim
```

(vim -u NONEでは起こらない)
### 環境
- Arch Linux
- awesome
- vim 7.4.307
### scriptnames

```
:scriptnames
/etc/vimrc
/usr/share/vim/vimfiles/archlinux.vim
~/.vimrc
/usr/share/vim/vimfiles/plugin/autoclose.vim
/usr/share/vim/vim74/plugin/getscriptPlugin.vim
/usr/share/vim/vim74/plugin/gzip.vim
/usr/share/vim/vim74/plugin/matchparen.vim
/usr/share/vim/vim74/plugin/netrwPlugin.vim
/usr/share/vim/vim74/plugin/rrhelper.vim
/usr/share/vim/vim74/plugin/spellfile.vim
/usr/share/vim/vim74/plugin/tarPlugin.vim
/usr/share/vim/vim74/plugin/tohtml.vim
/usr/share/vim/vim74/plugin/vimballPlugin.vim
/usr/share/vim/vim74/plugin/zipPlugin.vim
```
### ~/.vimrc

空ファイル
### /etc/vimrc

``` vim
!runtime archlinux.vim
```
### archlinux.vim

https://twitter.com/ayafmy/status/477425534536646657
同じものかと→ https://github.com/w0ng/builds/blob/master/vim/archlinux.vim
### autoclose.vim

autoclose.vimが原因かと思った ( https://github.com/tpope/vim-pathogen/issues/102 ) ので、ファイル消したが、意味がなかった (ファイルを消しても現象が再現)。
### :map &lt;esc&gt;

`:map <esc>`の結果はNo mapping found。

**Comment by mattn** [comment]
archlinux.vim に finish を入れて少しずつずらして行ってみて欲しいですね。

**Comment by itchyny** [comment]
archlinux.vim見てみても、そんな変な要因ないように思われたが…

**Comment by mattn** [comment]
scriptnames が欲しいですね。

追記: 書いてある！w

**Comment by mattn** [comment]
`foo.vim`

```
so /etc/vimrc
finish
so /usr/share/vim/vimfiles/archlinux.vim
finish
so ~/.vimrc
finish
so /usr/share/vim/vimfiles/plugin/autoclose.vim
finish
so /usr/share/vim/vim74/plugin/getscriptPlugin.vim
finish
so /usr/share/vim/vim74/plugin/gzip.vim
finish
so /usr/share/vim/vim74/plugin/matchparen.vim
finish
so /usr/share/vim/vim74/plugin/netrwPlugin.vim
finish
so /usr/share/vim/vim74/plugin/rrhelper.vim
finish
so /usr/share/vim/vim74/plugin/spellfile.vim
finish
so /usr/share/vim/vim74/plugin/tarPlugin.vim
finish
so /usr/share/vim/vim74/plugin/tohtml.vim
finish
so /usr/share/vim/vim74/plugin/vimballPlugin.vim
finish
so /usr/share/vim/vim74/plugin/zipPlugin.vim
```

これを `vim -u foo.vim` で起動して、再現するまで finish を消していってほしいす。

**Comment by ynkdir** [comment]
vimrc の先頭に `set t_u7=` と書くととりあえず症状はおさまると思います。
`set t_RV=` もあったほうがいいかもしれません。

**Comment by ayafmy** [comment]
えっと、vimrcに`set t_u7=`  と`set t_RV=`を書くと症状は収まりました。

上のfinishを消していくーって方については、その通りやってみましたが最初の時点でReplace modeで起動しました。

**Comment by itchyny** [comment]
なぜこういう現象が起きるのか、 @ynkdir さんに解説して頂けると幸いです。よろしくお願い致します。

**Comment by ynkdir** [comment]
'ambiwidth' を自動設定するために端末のカーソル位置をリクエスト (t_u7 のコードを出力) しているんですがそのレスポンスが `<Esc>[{row};{col}R` こんなコードです。
で、`<Esc>` を map したりするとちゃんと解釈できなくなって最後の R で置換モードになります。
`vim -u NONE -N` でもなるなら端末関係かもしれないです (`vim -u NONE` だと自動設定走らないです)。
レスポンスがおかしいのか termcap の設定がおかしいのか…。
termcap の設定は `:set termcap` で見れます。

**Comment by ynkdir** [comment]
あとはリモートだと通信の関係でタイミング的な問題がある可能性もあります。

**Comment by itchyny** [comment]
`<Esc>`をmapしているとおかしくなることがあるとどこかに書いてあったので、`:map <Esc>`の結果を聞いてみたのですが、何もmapされていないようでした。
なるほど。 リモートだと起きる可能性もあるんですね。 よく分かりました。 ありがとうございます。

**Comment by ynkdir** [comment]
リモートじゃなくても起きるかもしれませんし確証があって言ってるわけではないです。
vim_dev でも再現できないけどレースコンディションかなんかか…みたいな話がありましたが
そのへんは再現できる環境で調べてみないとなんとも…。

**Comment by saitoha** [comment]
今回の件とは関係無いかもしれませんが、

src/term.c:4246 の

```
if (j == 1 && tp[i] == 'R' && row_char == '2' && col >= 2)
```

っていうのはあきらかにまずいですね。

正しくカーソル位置報告シーケンスを返さない端末がいくつか知られていて、
たとえばjfbtermはゼロオリジンで位置を返したりするので、
以前はあえて曖昧な読み方をしていましたが、shift-F3の問題などの経緯があって、
変更されたのだと思います。

**Comment by saitoha** [comment]
> タイミング的な問題

最初に思いつくのは入力側のESCのタイムアウト設定なので、
その環境でカーソルキーやファンクションキーが正しく認識されているか調べてみた方がいいかもしれません
あと、わりと昔のtmuxで報告されてたんですが、応答シーケンスが必ず分割したパケットとしてtmuxから出力されてしまうという問題もありました。

**Comment by mattn** [comment]
@saitoha パッチの提案可能ですか？

**Comment by saitoha** [comment]
@mattn はい。少なくともdvtm-0.8まではデフォルトの$TERMがrxvt-256colorとされているのでt_u7が設定されてしまい、ゼロオリジンの問題と組合わさってREPLACEモードで起動することを確認したので、具体的な問題として報告できそうです。

**Comment by mattn** [comment]
助かります。宜しくお願いします。

**Comment by saitoha** [comment]
もう少しテストして大丈夫だったら、これで出そうと思っています
https://gist.github.com/saitoha/7149d02fb524ac2c1b90

termresponseを読む条件とマウスコードの兼ね合いがうまくいっていないバグが古くからあったのですが、
それに気付かないままカーソル位置報告シーケンスを読むパッチを提案していました。
さらに、7.3.863(r4223) の場当たり修正により傷口がひろがってしまいました。
以降、このREPLACE起動問題に対する対策が何度も講じられましたが、最初の根本的なバグを直していないため、色々な副作用を生んでいたようです。
7.4.305(r5927), 7.4.307(r5932), 7.4.539(r6039)は、revertした方が良いと判断しました。
7.4.207により、前述のdvtm-0.8の問題が発生したため、応答の読み方を修正しています。

**Comment by ynkdir** [comment]
saitoha++

**Comment by k-takata** [comment]
同様の報告
Issue 241 in vim: vim starts in REPLACE mode
https://groups.google.com/d/topic/vim_dev/vg_q5N7RVNU/discussion

**Comment by saitoha** [comment]
遅くなりました。QNX pterm mouseとかDEC locator mouse時の端末でデグレが起こらないか気になっていたんですが、ひととおりの端末でテストが終わったので出します。

**Comment by saitoha** [comment]
出しました。
https://groups.google.com/d/topic/vim_dev/aIQ0Y_cGsvw/discussion

**Comment by k-takata** [comment]
:+1:

**Comment by mattn** [comment]
:+1:

**Comment by k-takata** [comment]
7.4.389
https://groups.google.com/d/topic/vim_dev/06REeb0ev2I/discussion

**Comment by h-east** [comment]
@saitoha カッコイイ！:+1:
