### ISSUE TITLE
7.3.315からgvimを開くと処理がシェルに戻らない

### ISSUE THREAD

**Issue by ryo7000** [vim-jp/issues#58]
7.3.315からgvimを開くと、処理がシェルに戻らず、gvimを終了する時も時間が掛かるようになりました。
Ctrl-Cすれば、gvimはそのまま閉じられずに使えますが、cscopeでE262, E259が出てしまいます。

7.3.314までは問題なかったようです。

**Comment by mattn** [comment]
動作環境、vimの導入経路(KaoriYa? ソースからビルド?)を教えて下さい。
あと、7.3.315と書いて頂きましたが、7.3.314なら大丈夫とか、そういう意味でしょうか？
それともKaoriYa7.3.315にしたら挙動が変わったという意味でしょうか？

もし分かれば、正しく動いていたバージョンがあると助かります。

**Comment by ryo7000** [comment]
情報足らなくてすみません。
普段使っているのは、もう少し他のconfigureのオプションつけていますが、CentOS5.1環境で
ソースに7.3.315までのパッチを当てて、
./configure --with-features=huge --enable-gui=gtk2 --with-x=yes 
でビルドして、src/vim -gで起動して確認しました。
一つでも、他のgvimが起動していると問題ないようです。

7.3.315のパッチだけ戻して同様にビルドすると問題ないため、7.3.315の影響なのでは？と思っています。

**Comment by ryo7000** [comment]
すみません、間違ってcloseしてしまったのでreopenしました。

**Comment by mattn** [comment]
うむ。解析に少し時間がかかりそうです。
情報共有の為にリンク貼っておきます。

https://groups.google.com/d/topic/vim_dev/SptVxRhHpE8/discussion

**Comment by mattn** [comment]
シェルは何をお使いですか？

**Comment by mattn** [comment]
試しているのですが、再現出来ないです。Ubuntu11.4です。
まぁ無いとは思いますが、一度KaoriYaパッチ外して試してもらえますか。

**Comment by ryo7000** [comment]
シェルは、zsh-4.3.11, bash-3.1.16でも試してみましたが、同様でした。
vim -g -u NONE -U NONE
としても同じでした。

KaoriYaパッチはあててません。

**Comment by mattn** [comment]
うむ。ubuntuでやってみました。

```
# src/vim -g -u NONE -U NONE
```

ですが直ぐにシェルに制御が戻ってますね。

**Comment by mattn** [comment]
試してもらいたい事があるのですが

```
touch foo
cat foo | src/vim -g -U NONE -U NONE -
```

これでどうなりますか？

```
touch foo
cat foo | src/vim -gf -U NONE -U NONE -
```

の結果も教えて下さい。

**Comment by ryo7000** [comment]
両方とも
 Vim: Reading from stdin...
の表示が出たままで、シェルに制御は戻りませんでした。

**Comment by mattn** [comment]
ほうほう...
fooは空ファイルなのでEOF時点で画面が(空で)更新されるのですが、壊れてるっぽいですね。

**Comment by ryo7000** [comment]
ちなみに、すでに他のgvimが起動していると、
-g の方は、シェルに制御が戻ってきましたが、-gfはだめでした。
両方とも、gvim自体は起動はしています。

**Comment by mattn** [comment]
お...それがキーポイントですか。

もしかしてgvim一つ動かしておいて、違う端末から

```
vim --remote foo.txt
```

ってやって普通に動きますか？あと気になるのでDISPLAY環境変数の値を教えて貰えますか

**Comment by ryo7000** [comment]
長いこと放置してしまってすみません。

```
vim --remote foo.txt
```

は動きましたが、最初に起動したgvimの処理はシェルには戻りませんでした。

また、DISPLAY環境変数は

```
:0.0
```

となっていました。

**Comment by ynkdir** [comment]
CentOS5.1をさらでインストールするもビルドに必要なライブラリ等をインストールできず…。
yum updateするとCentOS5.7になってしまいましたがこの環境だと普通に動きます。

**Comment by ryo7000** [comment]
CentOS5.1を1からインストールして、ビルド環境を作ってみましたが、再現しませんでした…。
自分の環境でしか起こらないようなので、一度取り下げさせて下さい。
お騒がせしました。

**Comment by ryo7000** [comment]
http://vim-jp.org/2011/10/21/patch_7.3.344.html

私の再現する環境でも、7.3.344で解決したようです。
vim-jpのエントリで気づくことができました。色々ありがとうございました。
