### ISSUE TITLE
$ や h や w で画面右スクロールするとハングする

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#581]
https://gist.github.com/mattn/8ee63af5c2b989586df4

``` diff
diff -r 6973f595e1e9 src/screen.c
--- a/src/screen.c  Tue Jun 17 23:18:01 2014 +0200
+++ b/src/screen.c  Wed Jun 18 18:30:37 2014 +0900
@@ -7367,7 +7367,7 @@
 {
     linenr_T   l;
     colnr_T    matchcol;
-    long   nmatched;
+    long   nmatched = 0;

     if (shl->lnum != 0)
     {
```

7.4.330 でデグったらしい。報告済み。

https://groups.google.com/forum/#!topic/vim_dev/Lu0lErdkT3w

**Comment by k-takata** [comment]
このパッチと同じです？
https://groups.google.com/d/topic/vim_dev/ZbjRibxlchg/discussion

**Comment by mattn** [comment]
結果は同じなんですが、そちらはvalgrindで他の(本件以外)も見つけてる様ですね。

**Comment by k-takata** [comment]
7.4.334
https://groups.google.com/d/topic/vim_dev/q1U0clZG8ZI/discussion
