### ISSUE TITLE
html用のautoload関数が呼ばれなくてエラー

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#584]
htmlファイルを開いたとき、最近のコミット(https://github.com/vim-jp/vim/commit/1b9171f66870327e0913fbdcb9a50b7e4535ac58) の`htmlcomplete#DetectOmniFlavor()`が何故か見つからないとエラーを吐いてしまいます。

関数名は正しいようにみえるし、同じファイルの別のautoload関数はちゃんと呼べるのですがイマイチ原因がわかりません。

よろしくお願いします。

**Comment by haya14busa** [comment]
#### エラーメッセージ

```
Error detected while processing /usr/local/share/vim/vim74/ftplugin/html.vim:
line   25:
E117: Unknown function: htmlcomplete#DetectOmniFlavor
```

#### 環境
- Ubuntu 14.04

**Comment by haya14busa** [comment]
申し訳ありません。本体がおかしいのではなく https://github.com/othree/html5.vim というプラグインが `autoload/htmlcomplete.vim`を上書きしていたせいのようでした...閉じます。

**Comment by crazymaster** [comment]
あ、私もそのプラグイン入れていた...

**Comment by mattn** [comment]
ネームスペースが浅すぎるよねー

**Comment by cstrahan** [comment]
(Sorry for my ignorance, as I do not speak Japanese)

I had this problem too; could one of you tell me what your solution was? (in English, please :smile:)

**Comment by thinca** [comment]
Update html5.vim to latest version.

**Comment by cstrahan** [comment]
Aha! Easy enough :). Thanks!

**Comment by itsNikolay** [comment]
it's solved my issue too, many thanks to japanese guys!
