### ISSUE TITLE
全角と半角で matchaddpos() の動きが違う

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#586]
abcde
あいうえお
のテキストに、call matchaddpos("Title", [[1,1], [2,1]]) を行うと、
1行目は a のみですが、2行目は行すべてがハイライトされます。

vim 7.4 patch 346

**Comment by h-east** [comment]
再現しました。(Fedora19 Vim 7.4.347 enc=utf-8)
確かにおかしいですね。
マルチバイト対応漏れもしくは対応が中途半端かな？
~~数値3個のリストの場合、3つ目の数値は`the third number gives the length of the highlight in screen cells.`とヘルプにあるけども、「あ」だけhighlightさせるには現状だと`3`を指定しないと駄目ですし。~~
~~(screen cellは2なのに文字バイト数(utf-8: 3)になっとる)~~

``` vim
" 「あ」だけhighlight
:call matchaddpos("Title", [[2,1,3]])
" 「い」だけhighlight
:call matchaddpos("Title", [[2,4,3]])
```

**Comment by h-east** [comment]
あっ、古いhelp見てた。
最新のhelpは`the length of the highlight in bytes.`ってなっているから数値3個のリストの場合の3つ目の数値はあってますね。すんません。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/p6sDO4qw5dA

**Comment by k-takata** [comment]
7.4.362 で直ったものと思われます。
https://groups.google.com/d/topic/vim_dev/3PNuYKQ9EAk/discussion
