### ISSUE TITLE
signに全角文字を指定するとvisual選択時にハイライトされない

### ISSUE THREAD

**Issue by sgur** [vim-jp/issues#587]
## 確認環境
- Windows 版 gvim 7.4.347 (64bit; 独自ビルド)
- Windows 版 gvim 7.4.274 (32bit, 64bit; kaoriya版)
## 再現方法

`gvim -u NONE` で起動して、下記ファイル (utf-8で保存) を source する

``` vim
set encoding=utf-8
scriptencoding utf-8
sign define test text=あ texthl=WarningMsg
execute ':sign place 2 line=1 name=test buffer=' . bufnr('%')
```

`set encoding=cp932` では発生しないようです。
## 症状

sign がついた行に対して visual 選択をすると、以下のようになります。
- GUI 版では
  - linewise な visual 選択 (`V`) をすると、ハイライトされない
  - 行頭文字を characterwise な visual選択 (`v`) すると、ハイライトされない (2桁目からは可能)
- CUI では
  - Visual できるが、sign つきの行と signなしの行をまたぐと、signつきの行の方のハイライトが消える

**Comment by osyo-manga** [comment]
手元の環境でも試してみました。
同じ現象かわかりませんが、以下のような感じでハイライトがずれました。

![](http://gyazo.com/ec1450f12d09cfa9d1e7214c6f9a7521.png)

## 確認環境
- Ubuntu 13.10
- Vim 7.4.345

**Comment by osyo-manga** [comment]
あ、わたしが試したのは gvim です。

**Comment by sgur** [comment]
`<C-v>` で選択すると osyo-manga さんと同じようになります。

![gvim-issue 587](https://cloud.githubusercontent.com/assets/255021/3465639/9b7e5f42-026b-11e4-86ea-554c2da36aaf.png)

↑ は1行目で `V` して、`j` した時です。
1行目がハイライトされていません。

**Comment by mattn** [comment]
元々、sign って半角文字なんですが utf-8 の記号を許す様になりました。
ただ英語圏の人からすれば倍角の文字なんてないのでその動作がこういう結果になってます。

**Comment by mattn** [comment]
つまり厳密に言うと「あ」が設定出来るのが間違い、という意味です。

**Comment by mattn** [comment]
でも :help には `>>` とかあるな...

**Comment by sgur** [comment]
> `>>`

半角2文字ならOKなんですね…

**Comment by sgur** [comment]
個人的には理由がわかったので Close してもよいと思うのですが、
- Fullwidth文字でも大丈夫なようにコード修正する
- Fullwidth文字を受け付けないようにコード修正する
- helpに追記する

のいずれかの方向で進めた方がよいのでしょうか？

**Comment by mattn** [comment]
個人的には 2cell 扱えるので1番目かなーと思いますが、いかがでしょう > all

**Comment by thinca** [comment]
1が良い気がします。

**Comment by sgur** [comment]
これ、colorcolumnの表示位置の計算の時も同様にミスしているようです。
いろいろ根が深い…

![2014-07-08 17_27_23-vimrc _vimfiles - gvim](https://cloud.githubusercontent.com/assets/255021/3507047/bd64bf7c-0679-11e4-8b6b-859eafc8ba92.png)

**Comment by sgur** [comment]
ver.7.4.1710 で再確認したところ、本問題は直っていましたので Close します。

![2016-04-07 11_16_14-test_issue_587 vim - gvim1](https://cloud.githubusercontent.com/assets/255021/14338429/37113c80-fcb2-11e5-89fa-739488567ae1.png)

**Comment by k-takata** [comment]
どのパッチで直ったのだろう？

**Comment by ichizok** [comment]
7.4.949 で直っていました。
https://github.com/vim/vim/commit/32a214e78df0120f92fe049eab1385c60f0cdb0b
