### ISSUE TITLE
:cquit [code] で終了コードを指定できるようにする

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#589]
パッチを書いてみました。パッチ書き慣れてないのでレビューしてもらえると嬉しいです。

https://gist.github.com/thinca/5cfc8390d691b8fc5639
- 手抜きした結果 `:10cquit` とかも通るけど、Vim 的にアリなのか
  - help の `:[code]cquit` の `[code]` がハイライトされないので気になった
- help が適当、と言うか説明文書いてない
  - 英語難しいのでどんな感じが良いかアドバイスを…
- テストないけど、そもそも書けるのかどうかわからない
- 思い付きで書いたので、あると便利な理由とか突っ込まれると苦しい

その他まずそうなところとかもっといい書き方とかあったらご指摘頂けると助かります。

**Comment by koron** [comment]
バグが有るかどうかは別として(みてない)、これはとっとと提案して良いと思う。
ドキュメントもあるし、あとはちゃんとメールに
(Bram が出すパッチと同じように)
Problem と Solution を書いとけば意図はしっかり伝わるので。

**Comment by koron** [comment]
> あると便利な理由とか突っ込まれると苦しい

これが非常に重要。

**Comment by koron** [comment]
> 英語難しいのでどんな感じが良いかアドバイスを

```
If `[code]` is provided, vim returns that code at exit.
```

とかそんな感じの段落を足せばよいハズ。
まず日本語でも良いから、どんな内容の文章を足したいのか、方針を示すと良いでしょう。

**Comment by thinca** [comment]
ありがとうございます。とりあえず頂いた英文そのまま足しました。
あと、 `:qcuit 0` で `ゼロカウント` って出ちゃう問題を発見したので、やはり実装観直してみます…。
![](http://i.gyazo.com/35fc69d76ffc4e43adce013a982d6441.png)
(どうでもいいけどこれエラー番号ないんですね…)

**Comment by k-takata** [comment]
> help の `:[code]cquit` の `[code]` がハイライトされないので気になった

ヘルプの他の部分で数値を示す場合は `N` や `[N]` になっていたと思います。

**Comment by k-takata** [comment]
`ゼロカウント` は、ここでしょうかね。 https://github.com/vim-jp/vim/blob/96e1ec11adf7999955c6c5421d64aea3668187e5/src/ex_docmd.c#L2499
`ZEROR` フラグが立っていれば、ゼロも受け付けるみたい？

**Comment by thinca** [comment]
アドバイスありがとうございます！最近忙しくて止まってたので、週末辺りにでもボチボチやってみようかと思います。

**Comment by mattn** [comment]
ping!

**Comment by thinca** [comment]
pong!
全然作業進んでません…。
今週末機会があるので挑戦してみます！
あ、一応言っておくと、絶対自分でやりたいとかはないので、この機能欲しいけど待ちきれんわって人いたらおとなしく譲ります…(その方が早そう)。

**Comment by thinca** [comment]
Gist 更新しました。
https://gist.github.com/thinca/5cfc8390d691b8fc5639
- @k-takata さんのアドバイス通り、`ZEROR` フラグで 0 行けました！ありがとうございます。
- コメントが幅を超えていたっぽいので、位置を変えてみました。
- `:crewind` などが、実は `[nr]` をコマンド前に置けるけど help にはなかったので、`:cquit` でも記述を単純にするために `:[code]cquit` を help から取り除きました。

軽く試した感じ期待通りです。

```
:cquit
" => exit at 1
:cquit 10
" => exit at 10
:10cquit
" => exit at 10
:cquit hoge
E488: 余分な文字が後ろにあります
:cquit 0
" => exit at 0
```

問題なければ出そうと思います。

**Comment by mattn** [comment]
:+1:

パッチは見てない

On 9/6/14, thinca notifications@github.com wrote:

> Gist 更新しました。
> https://gist.github.com/thinca/5cfc8390d691b8fc5639
> - @k-takata さんのアドバイス通り、`ZEROR` フラグで 0 行けました！ありがとうございます。
> - コメントが幅を超えていたっぽいので、位置を変えてみました。
> - `:crewind` などが、実は `[nr]` をコマンド前に置けるけど help にはなかったので、`:cquit` でも記述を単純にするために
>   `:[code]cquit` を help から取り除きました。
> 
> 軽く試した感じ期待通りです。
> 
> ```
> :cquit
> " => exit at 1
> :cquit 10
> " => exit at 10
> :10cquit
> " => exit at 10
> :cquit hoge
> E488: 余分な文字が後ろにあります
> :cquit 0
> " => exit at 0
> ```
> 
> 問題なければ出そうと思います。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/589#issuecomment-54706650

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
提案のパッチなので気長に待ちましょう。

On 9/6/14, thinca notifications@github.com wrote:

> Gist 更新しました。
> https://gist.github.com/thinca/5cfc8390d691b8fc5639
> - @k-takata さんのアドバイス通り、`ZEROR` フラグで 0 行けました！ありがとうございます。
> - コメントが幅を超えていたっぽいので、位置を変えてみました。
> - `:crewind` などが、実は `[nr]` をコマンド前に置けるけど help にはなかったので、`:cquit` でも記述を単純にするために
>   `:[code]cquit` を help から取り除きました。
> 
> 軽く試した感じ期待通りです。
> 
> ```
> :cquit
> " => exit at 1
> :cquit 10
> " => exit at 10
> :10cquit
> " => exit at 10
> :cquit hoge
> E488: 余分な文字が後ろにあります
> :cquit 0
> " => exit at 0
> ```
> 
> 問題なければ出そうと思います。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/589#issuecomment-54706650

## 
- Yasuhiro Matsumoto

**Comment by thinca** [comment]
英文メールが辛くて長らく放置してましたが、さっきようやくパッチ投げました。パッチは投稿前に最新の Vim との差分に更新しました。

https://groups.google.com/d/topic/vim_dev/_PjyNbUKyRc/discussion

なんか変なところとかあったらフォローしてもらえると助かります…。

**Comment by thinca** [comment]
いきなりタイトルと本文でコマンド名を間違えるという失態を犯した…。隣に座っていた kana さんが即座に指摘してくれて訂正メールを送りました。

**Comment by thinca** [comment]
v7-4-479 の直後の runtime 更新で todo リストに追加されました。
https://code.google.com/p/vim/source/detail?r=31f7581068a9c3119e3bd2cd74160eb8282c3c6e

> Patch to add argument to :cquit. (Thinca, 2014 Oct 12)

**Comment by k-takata** [comment]
8.2.0095: https://github.com/vim/vim/commit/1860bde9d31bbb0ba857f6284f6332a7134030dd
