### ISSUE TITLE
ウィンドウリサイズ時にgvimが落ちる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#59]
http://twitter.com/#!/yo_i_jewelry/status/120721733291491328

> @kaoriya さんの最新64ビルドビルドで:Unite -no-split file_mru を実行してOSのウィンドウ端をマウスでドラッグしてリサイズすると、高確率で落ちます。

http://twitter.com/#!/yo_i_jewelry/status/120722493639098368

> で、ソース持ってきてデバッグ実行した所ScreenLinesとScreenAttrsでバッファを超えてアクセス（書きこみ）して落ちてしまうところまでわかって、アロックのサイズを２バイト多めに取るようにした所、症状が収まっています。

http://twitter.com/#!/yo_i_jewelry/status/120724438542061568

> さっきのツイートで（書きこみ）と書きましたが読み込みだったかもしれません。記憶が定かでなかったです。

**Comment by koron** [comment]
@mattn さんが得意そうな内容だw

**Comment by ynkdir** [comment]
関係あるか分かりませんが &columns と &lines を変更しまくると落ちるというのが実はけっこう前からありました。

``` vim
" $ vim -u NONE -g -S thisfile.vim

" msvcrt rand
let s:RAND_MAX = 32767
let s:seed = 0
function! s:rand()
  let s:seed = s:seed * 214013 + 2531011
  return (s:seed < 0 ? s:seed - 0x80000000 : s:seed) / 0x10000 % 0x8000
endfunction

function! s:random()
  return s:rand() / (s:RAND_MAX * 1.0)
endfunction

" Return a random integer N such that a <= N <= b.
function s:randint(a, b)
  return float2nr(a:a + ((a:b - a:a + 1) * s:random()))
endfunction

while 1
  let &columns = s:randint(1, 1000)
  let &lines = s:randint(1, 1000)
endwhile
```

今ためしたら OS (or X) まきこんで死ぬみたいですが… on ubuntu

**Comment by koron** [comment]
「また無茶しやがって」w

でもむかしもこんなんあったよね。

**Comment by mattn** [comment]
そこまで出来てるならば、もうそろそろgdbで食わして...まではやっているはず！

**Comment by ynkdir** [comment]
osごと落ちるのでデバッグできるんだろうか…
前試したときはすなおに SEGV したんですが
そのときは ScreenLines がNULLだったか未初期化だったかでそれにアクセスして落ちてました。

**Comment by h-east** [comment]
いたるところにfprintf() ww like #30

**Comment by ynkdir** [comment]
むはー、それはきついw

ulimit -c unlimited でも core 吐かないし
どうもやっぱりvimより先にXが落ちてるようで
このissueとは別問題だったかもしれません。

**Comment by koron** [comment]
起票より時間が経過し、類似報告は受けておらず、また再現方法も確立されていません。

よって一旦 invalid で閉じ、一定期間経過後に worksforme へ移します。
めどは…2016年9月末で良いでしょう。

**Comment by k-takata** [comment]
> よって一旦 invalid で閉じ、

閉じます。

**Comment by koron** [comment]
:bow:
