### ISSUE TITLE
高さ調整が効いていない？

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#592]
> .gvimrc で set line=9999 で縦最大化して起動していますが、画面下にめり込みます。

http://www.kaoriya.net/software/vim/#comment-1487563855 より

要詳細。

**Comment by ynkdir** [comment]
タスクバーが画面上にあるならこれですかね
https://groups.google.com/d/msg/vim_dev/xRdOvRDM3-Y/fhlb--KfkTUJ
以前は動いていたとかいう話はよくわかりませんが。そうでしたっけ。

**Comment by ynkdir** [comment]
関連 #181 #308
ぜんぜんおぼえてない…

**Comment by koron** [comment]
以前のレベルが7.3なのがいやらしいですなw

**Comment by k-takata** [comment]
関連しそうなのは 7.3.393 とか？

**Comment by ynkdir** [comment]
oh...なんかそんな感じですね...

**Comment by koron** [comment]
ところで…再現できました?

**Comment by ynkdir** [comment]
再現できました。
7.3.338 ok
7.3.393 ng
元の人のタスクバーの位置が不明なのであれですが上ならこれですね。

**Comment by koron** [comment]
3度めか。どのパッチ当てるのが良いですかね。

**Comment by koron** [comment]
これ…

https://gist.github.com/mattn/2412212

は obsolete?

**Comment by mattn** [comment]
そのパッチ、一応タスクバー上にして確認したやつではあるけど、今のソースだと当たらないかも。

**Comment by ynkdir** [comment]
https://groups.google.com/d/msg/vim_dev/xRdOvRDM3-Y/Ej-vJ0dWzPoJ
昔の私がマルチモニタ環境でどうのといってパッチ投げてます。中身は覚えてませんが。

**Comment by koron** [comment]
> https://groups.google.com/d/msg/vim_dev/xRdOvRDM3-Y/Ej-vJ0dWzPoJ

このパッチを、最新版+枠線消すパッチ済みに当てたら、こんな余白ができるようになりました。

![vim-margin](https://cloud.githubusercontent.com/assets/468368/3929330/4fb6fa04-241e-11e4-8056-824f004671cd.png)

**Comment by koron** [comment]
ごめんなさい。これが原因ではないようです。
ハズしても発生したので。

**Comment by koron** [comment]
8.1.1436 のパッチなしで gvimrc の最後に `set lines=9999` を追加したところ
ちゃんと縦方向最大化して起動できました。

また詳細な再現方法もわからないので worksforme で閉じます。

**Comment by k-takata** [comment]
Duplicate of #181. Fixed in 8.2.1226.
