### ISSUE TITLE
VimからPythonを使うと落ちる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#594]
正確なタイトルは「Vim 64bit からPython 32bit を使おうとすると落ちる」

なんも言わずに落ちた。以下、詳細な状況
- OS は Windows 7 (64bit)
- Vim は64bit
- Python は 2.7.6/3.4.0 の 32/64bit 系4バージョンインストール済み
- Path は 2.7.6 の 64bit に通ってる

手順:
1.  `C:\Windows\System32\python27.dll` を `python27.dll~` にリネームして読めないように
2.  gvim を起動して `py import sys; print(sys.version)` を実行
3. 落ちた。システムデバッガも拾ってくれない

備考:
- `python34.dll` のほうで同様に `py3 import sys; print(sys.version)` した時は、落ちずにDLLが読めないとエラーが出た

---
#### 修正方針
- [x] `Py_NoSiteFlag` を立てる at before `Py_Initialize()`
- [ ] `go fail;` した後は、pythonを使えないように、フラグ管理する in `Python_Init()`
- [x]  `import site` は各モジュールの初期化の最終段階で、自前でやる at begin/end of `populate_module()`

**Comment by koron** [comment]
32bit 版 Vim から 64bit Python を読むのは未テスト。

**Comment by koron** [comment]
#66 からの派生

**Comment by koron** [comment]
デバッガで追って確認したんだけど
32bit の DLL に対して LoadLibrary と GetProcAddress は成功しちゃうのね。
すごい。

**Comment by ynkdir** [comment]
それたぶん tortoisehg か mercurial 付属の dll を読み込んでませんか

**Comment by koron** [comment]
あざす! そうっぽいですね。

いま「64から32読めるわけねーだろ」と思って
仮に読めるとしたらどんな仕組みで読んでるのがググってましたが
集まるのは逆の証拠ばかりでしたw

**Comment by koron** [comment]
#66 から転載

---

確認はしてませんがこれだと思います。

Python-2.7.8/Python/pythonrun.c

``` c
/* Import the site module (not into __main__ though) */

static void
initsite(void)
{
    PyObject *m;
    m = PyImport_ImportModule("site");
    if (m == NULL) {
        PyErr_Print();
        Py_Finalize();
        exit(1);
    }
    else {
        Py_DECREF(m);
    }
}
```

**Comment by koron** [comment]
さらに #66 より転載

---

py2exe は python27.dll に細工してました。
python27.dll の winver(1000) というリソースを変更してます。
python はレジストリの HKLM\Software\Python\PythonCore{WINVER} に PYTHONPATH を取りにいくので py2exe の dll は普通には使えない。

**Comment by koron** [comment]
その後に確認したこと。
1. system と Mercurial の python27.dll を inhibit して Vimから Python実行 → DLLロードエラーで正しく止まった
2. system の python27.dll だけを inhibit して、インストールしてある Python 2.7.6 を実行 → Mercurlal の Python 2.7.5 が実行された

**Comment by koron** [comment]
現状の理解と疑問
- デバッガが拾わないことから exit が呼ばれている可能性が高い
- ynkdir さんが上げてくれた `initsite` で止まってる可能性が濃厚
- だとしたらあるケースが落ちないのが不明: あるケース=system の python27.dll だけを inhibit して、インストールしてある Python 2.7.6 を実行

**Comment by koron** [comment]
PYTHONPATHか…

**Comment by ynkdir** [comment]
vim.exe で試すと出るメッセージはこれです "ImportError: No module named site"

**Comment by koron** [comment]
PYTHONPATH に関してさらにやったこと:
1. Mercurial の python27.dll を活かし system のは inhibit
2. 環境変数 PYTHONPATH に `HKLM\SOFTWARE\Python\PythonCore\2.7\PythonPath` からコピった値を設定
3. Vimを 起動し `import sys; print(sys.version)` を実行 → Mercurial のPython 2.7.5 が実行されるのを確認

以上からわかったこと:
- python27.dll は必須モジュール(site)のロードに失敗すると exit してしまう
- 必須モジュールの読み込みPATHは最終的にレジストリにfallbackするが、py2exe を通した python27.dll はそのfallback機構が機能しない
  - 参照しているレジストリは `HKLM\SOFTWARE\Python\PythonCore\2.7\PythonPath`
  - 環境変数 `PYTHONPATH` が設定されていれば fallback 機構は動作しない

こんな感じですかね?

**Comment by koron** [comment]
crt0dat.c の doexit (exitの本体) 見てる。介入できないか、と。

**Comment by koron** [comment]
[ExitProcess](http://msdn.microsoft.com/ja-jp/library/cc429099.aspx) をフックすれば止められそうだけど、atexit が全部実行されちゃうからなぁ…

**Comment by koron** [comment]
もうこうなると FAQ 化しちゃうのが良さ気かなぁ…

**Comment by k-takata** [comment]
msvcr*.dll にリンクしているので exit にフックを仕掛けることはできそうですが、そこまでするかという感じが。

**Comment by koron** [comment]
Vim自身は msvcr100.dll で Python は msvcr90.dll なんですよね…
こういう時ってどうなるんです?

**Comment by k-takata** [comment]
python*.dll が msvcr90.dll を参照する際に使っているインポートテーブルを書き換えることになりますので、python が呼ぶ exit だけをフックできるはずです。

**Comment by koron** [comment]
Pythonのソース見た。

`initsite()` は デフォで `import site` するもので、
`Py_NoSiteFlag` を立てればデフォではしなくなる。
実際 Module/main.c でも `-S` オプションで立ててる。

これ…立てるべきだろうか? ってVimから立てられるかこれ?

**Comment by koron** [comment]
https://gist.github.com/koron/aa53ddf11510e9d8942d

こんなパッチを試したら `PythonMod_Init` がコケて
2回めの `Python_Init` の呼び出しがエラーになるというw

**Comment by koron** [comment]
> こんなパッチを試したら

これは 「Mercurial の python 使おうとしたら」 の意味。

**Comment by koron** [comment]
以下の条件を満たせればやる価値あり
-   `go fail` 後のエラーハンドリングをしっかりする
-   if_python において NoSite の副作用が無いことを確認できる

**Comment by koron** [comment]
実際に失敗しているのは if_py_both.h の `PyImport_ImportModule("os")` だった。
PYTHONPATH が無いから当然か。

**Comment by koron** [comment]
https://twitter.com/methane/status/490875720445345793 より

> pip install とかでインストールした、標準ライブラリ以外のライブラリがほぼ import できなくなる。

びみょーw 落ちるよりはマシかもだけど…

**Comment by mattn** [comment]
exit フックするより `m = PyImport_ImportModule("site");` 自前で実行してエラーなら python 無効でいいと思う。

**Comment by koron** [comment]
**方針決定**
- [ ] `Py_NoSiteFlag` を立てる at before `Py_Initialize()`
- [ ] `go fail;` した後は、pythonを使えないように、フラグ管理する in `Python_Init()`
- [ ]  `import site` は各モジュールの初期化の最終段階で、自前でやる at begin/end of `populate_module()`

**Comment by koron** [comment]
@mattn 同じこと考えてた。

**Comment by koron** [comment]
あとは `import site` のタイミングをズラしたことによる弊害があるかどうか、か。
ざっくり眺める限り、エンコードがらみで変なことしてなきゃ大丈夫に見える。

**Comment by koron** [comment]
https://gist.github.com/koron/aa53ddf11510e9d8942d/52662223b31cd5f27fb8362dd1c8b6ed96b372e4

とりあえずコレで良さそう。やったのは以下の2つだけ。
- `Py_NoSiteFlag` を立てる at before `Py_Initialize()`
- `import site` は各モジュールの初期化の最終段階で、自前でやる at after `Py_Initialize()`

**Comment by koron** [comment]
https://gist.github.com/koron/aa53ddf11510e9d8942d/e870c50e5fb9cdc4e6d77317dee66ead55f8f367

Python3 も対応した。とりあえず、コレで送るか?

**Comment by koron** [comment]
あ、Python3 はexit を呼んでないぞこれw

**Comment by koron** [comment]
送った。

https://groups.google.com/d/msg/vim_dev/8Q7gq1InUk0/ps4a2dnvj5MJ

対応したのは 2.7 だけ。

https://gist.github.com/koron/aa53ddf11510e9d8942d/52662223b31cd5f27fb8362dd1c8b6ed96b372e4

3.x のソース見たらexitしてなかったので。

**Comment by koron** [comment]
> go fail; した後は、pythonを使えないように、フラグ管理する in Python_Init()

これは本質と関係ない&みあう価値がないので見送ります。

**Comment by koron** [comment]
2.7 以降だけに適用するように変更。

https://gist.github.com/koron/aa53ddf11510e9d8942d/037d9c05453def9cc42849d44dba830268b2938d

ソースをチェックした結果、そこに exit があるのは 2.7 だけだった…なんだこれ?w

**Comment by ynkdir** [comment]
python3 も exit してませんか。 python 3.4.1 見てます。

**Comment by ynkdir** [comment]
python 3.2 から exit してるみたいです

**Comment by ynkdir** [comment]
memo: cx_Freeze は pythonXX.dll に細工なし。

**Comment by ynkdir** [comment]
Issue13533: Would like Py_Initialize to play friendly with host app
http://bugs.python.org/issue13533

**Comment by koron** [comment]
@ynkdir Thanks!  svn にある 3.0 あたりのソース見て「え、ウソ?ないの?」って思ってとりあえず2.xだけ出しとくかーでした。
もうちょい議論が進んだら送ります。

**Comment by koron** [comment]
> Issue13533: Would like Py_Initialize to play friendly with host app

くっそ… `exit()` しちゃうほうが not friedly だっつーのw

**Comment by h-east** [comment]
Patch 7.4.380
https://groups.google.com/d/msg/vim_dev/d4Iz0vdPJ48/HZzSJ-fVTOcJ

**Comment by k-takata** [comment]
Python 3.xがまだ直っていないのでは?

**Comment by mattn** [comment]
python3の方はエラーが出るんですよね？

**Comment by k-takata** [comment]
mercurial 付属の dll は 2.7 なので、3.4 の dll は無いため 3.4 ではエラーになっているのだと思います。
3.4 のオフィシャルでない dll があれば、3.4 でもエラーにならず落ちるのかもしれません。

**Comment by mattn** [comment]
だれか確認出来る人いますか？

**Comment by tyru** [comment]
以前はTortoiseHgのDLLが2.7だったので再現できましたが、
3.4となるとPython3でpy2exeで適当なPythonスクリプトをexe化すればpython34.dllも一緒に吐かれそうですね。
それをPATHに含めれば検証できそうです。
2014/07/24 9:20 "mattn" notifications@github.com:

**Comment by ynkdir** [comment]
python34.dll があって python3 のライブラリ等がないときは abort() するみたいです。
`Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'`

**Comment by koron** [comment]
ああテストするだけならsite.pyを退避すれは良いんだわw
今になって気がついた。

**Comment by k-takata** [comment]
> python34.dll があって python3 のライブラリ等がないときは abort() するみたいです。

python33.dll でもそうなることが確認できました。
@koron さんのpython3用パッチでabortしなくなるかどうかは未確認。

> ああテストするだけならsite.pyを退避すれは良いんだわw

そんな手があったとは。*.pycも退避しないと。

**Comment by koron** [comment]
@ynkdir 

> Issue13533: Would like Py_Initialize to play friendly with host app
> http://bugs.python.org/issue13533

教えてもらったコレを読む限り、
2.x系は2.7から、3.x系は3.3から変更になったように読めるんですが
3.2からと判断した根拠はソースまでみた結果でしょうか?

**Comment by ynkdir** [comment]
> 3.2からと判断した根拠はソースまでみた結果でしょうか?

はい

**Comment by koron** [comment]
@ynkdir ありがとうございます!

**Comment by ynkdir** [comment]
あーただ、↑にも書いてますが python3 の場合は initsite の前に codec の初期化で落ちるのでこれは回避できなさげです

**Comment by koron** [comment]
ありゃま。2.7ではinitsiteのあとにcodecの初期化してたみたいでしたね…変わったのか。

**Comment by koron** [comment]
ん? ということは py2exec したモノでもcodecは初期化できるのでは?

**Comment by koron** [comment]
いや違うか。
-   PYTHONPATHの設定が不正で読み込めない

ってケースでしたね。

**Comment by koron** [comment]
#610 に継続しました。こちらは閉じます。
