### ISSUE TITLE
Vim のエラーが出た後に Ex モードのまま終了するとVimの終了コードが1になる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#598]
``` sh
$ vim -u NONE -i NONE -N -e -c NonExistCommand -c qall
$ echo $?
1
```
- `NonExistCommand` は Vim のエラーを出すためのもので、エラーが出れば何でも良さそうです。(`'echo non_exist_var'` とか)
- `-c` を使わずに、手動で入力しても発生します。
- 普通に起動した後にエラーを出して `Q` で Ex モードに入って、そのまま終了しても発生します。エラーを出すのは Ex モードに入る前でも後でもいいようです。
- `:silent!` や `try - catch` でエラーを抑制しても、内側でエラーが起きていれば発生するようです。
- `:visual` で Ex モードを抜けて終了すれば発生しません。

あまりにも一貫した挙動なので、仕様かもと思いましたが、こういう仕様は聞いたことがないので、もし知ってる方いたら教えてください。

**Comment by koron** [comment]
FreeBSDの `man ex` より。

>  Ex/vi exits 0 on success, and greater than 0 if an error occurs.

これかしらねぇ?

**Comment by koron** [comment]
やっぱそれっぽい。

``` c
/* When running in Ex mode an error causes us to exit with a non-zero exit
 * code.  POSIX requires this, although it's not 100% clear from the
 * standard. */
if (exmode_active)
    exitval += ex_exitval;
```

https://github.com/vim-jp/vim/blob/3ea8d84f1ba16914854c8aef679d2319788cf9df/src/main.c#L1367-L1371 から抜粋。

**Comment by koron** [comment]
ちなみに `ex_exitval` は message.c の `emsg()` で設定されてた。
リセットする場所は無いっぽい。
なので一度でも `emsg()` が呼ばれてる & `exmode_active != 0` ならexit codeが1(非0)になるって仕組み。

**Comment by thinca** [comment]
なるほど、やはり仕様ありましたか。ありがとうございます。
ただ、

> `:silent!` や `try - catch` でエラーを抑制しても、内側でエラーが起きていれば発生するようです。

この挙動どうなのかなぁと思うんですが、どうでしょう?

**Comment by koron** [comment]
それらは Vim による後付だからねぇ。

私はパス。

**Comment by koron** [comment]
ちなみに `ex_exitval` をセットしているのは [ココ](https://github.com/vim-jp/vim/blob/3ea8d84f1ba16914854c8aef679d2319788cf9df/src/message.c#L593)

この後ろで `silent` や `try` の判定してるっぽい。
なので更に後ろにズラせばexitコードを変えないようにはできそう。
私はパスだけど。

**Comment by koron** [comment]
#599 で提案issueに振り替えました。

こちらはそういう仕様だということで閉じます。

**Comment by thinca** [comment]
ありがとうございます！
