### ISSUE TITLE
タグ補完でtagsのコメントも候補に出る

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#60]
tagsファイル内の `!_TAG_` で始まる行はコメントであり、これは `:help tags-file-format` でも明記されているが、`<C-x><C-]>` によるタグ補完でこれらが候補として現れる。

**Comment by thinca** [comment]
よく見たらコメントとは書いてなかった。でも、補完される行ではないはず。

**Comment by mattn** [comment]
間違いなく @ynkdir さんのパッチ(#2)とバッティングする

``` diff
diff -r fb6b43d55773 src/tag.c
--- a/src/tag.c Fri Sep 30 18:35:57 2011 +0200
+++ b/src/tag.c Mon Oct 03 16:14:40 2011 +0900
@@ -1870,6 +1870,8 @@
        continue;
        }
 #endif
+       if (!STRNCMP(lbuf, "!_TAG_", 6) > 0)
+       continue;

        /*
         * Figure out where the different strings are in this line.
```

**Comment by ynkdir** [comment]
あらためてこっちに書きます。

Proposal for extended Vi tags file format
http://ctags.sourceforge.net/FORMAT

```
TAG FILE INFORMATION:
...snip
The program reading the tags file should be smart enough to skip over these tags.
```

ということで Bram 曰く、賢いプログラムはそれらのタグをスキップすべし、とのことです。

別のものなので私としては分けて出したい感じです。

**Comment by ynkdir** [comment]
そのパッチは :tag コマンドでバイナリサーチが走ると無限ループします。

**Comment by mattn** [comment]
ようやく時間とれたけどもうこんな夜中...
なんかtag.cきたないなー。

**Comment by ynkdir** [comment]
tags completion items
http://thread.gmane.org/gmane.editors.vim.devel/22556

無反応

Omni Completion : Notes and issues
http://thread.gmane.org/gmane.editors.vim.devel/10749

```
> * !_TAG_FILE_FORMAT and it's ilk are listed in the global completions.

Thanks for the remarks, I'll add them to my todo list.
```

todo.txt にはないので入れ忘れたかそれとも解決済みなのか...

**Comment by ynkdir** [comment]
いったん todo.txt にははいった

ftp://ftp.vim.org/pub/vim/unstable/snapshot/vim-7.0158.zip

```
todo.txt:
- !_TAG_FILE_FORMAT and it's ilk are listed in the global completions
```

**Comment by ynkdir** [comment]
ftp://ftp.vim.org/pub/vim/unstable/snapshot/vim-7.0173.zip
で再現できなくなり

```
todo.txt:
- !_TAG_FILE_FORMAT and it's ilk are listed in the global completions
    Can't reproduce it right now...
```

ftp://ftp.vim.org/pub/vim/unstable/snapshot/vim-7.0189.zip
で消された

**Comment by mattn** [comment]
すごい... ynkdir++

**Comment by koron** [comment]
@ynkdir△

**Comment by Shougo** [comment]
ちなみに、neocomplcacheでは自力でパースしているのでスキップしています。

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/t_KRzujHVfE/discussion

@ynkdir さんにアサインしますね。

**Comment by ynkdir** [comment]
#2 7.3.336 でついでに修正されました。
補完候補には出ないけど :tag ... で明示的に指定すればタグを引けるという形です。
