### ISSUE TITLE
Windowsでvim -gしたらgvimを起動する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#602]
> WindowsのVimはvim -gに対して GUI無効 とかしょっぱいこと言わずにGVimをキックしてくれてもいいと思う。:guiもまた然り

(https://twitter.com/nocd5/status/494440133156810752 より)

`:gui` はともかく `-g` は確かにそんな気がする。
1. gvim.exe を探す、なければ現在でてるエラーを出して終了
2. 自分が受け取ったオプションから -g を除き、gvim.exe にそのまま渡して起動する
3. 自分自身は終了

こんな動作をしてくれても良さそう。

**Comment by mattn** [comment]
```
C:\>dir | vim -g
```

で標準入出力をパイプしないといけないので、簡単ではなさそう。

**Comment by koron** [comment]
Winってプロセス起動する時、自分のもってる標準入力を引き渡せなかったっけ?

まぁ、全部対応できる必要はない、ってのが本音だけど。

**Comment by mattn** [comment]
これ、`vim -g` はいいけど、`vim -gf` は死ねないのでちょっと考えないとなー。

**Comment by k-takata** [comment]
#306 で `vim -g`, `vim -gf`, `:gui`, `:gui -f` が動くようになりました。
標準入力からの読み込みも動いています。

**Comment by k-takata** [comment]
パッチ投げたけど、VIMDLLが有効じゃなければ動かないのは仕方ないか。
頑張ればVIMDLL無効でも、`vim -g`, `:gui (-b)` だけなら動くようになるかもしれないけど。

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/4287#issuecomment-485894425
Bramに、完璧に動かないなら `:gui` はいらないと言われてしまった。

まあ、`:gui`の実装に使った`:mksession`ではセッションを完璧に復元することはできないし、`:gui -f`はWindowsだと使い道ないし、仕方ないか。

**Comment by k-takata** [comment]
[8.1.1230](https://github.com/vim/vim/commit/afde13b62b8fa25dac4635d5caee8d088b937ee0) で `VIMDLL=yes` でビルドすれば `vim -g` は動くようになりました。
（gui.h の `#define EXPERIMENTAL_GUI_CMD` を有効化すれば `:gui` もそれっぽく動くようになりますが、完璧ではないため無効化してあります。）
`VIMDLL=no` では動きませんが、とりあえず閉じます。
