### ISSUE TITLE
vim 7.4.364 で hlsearch と cursorline をオンにしていると描画が遅くなった

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#603]
例えば 'abcdef' が 100 行ある画面で、

```
\%1l\%(abcde\)\%2l\%(abcde\).....\%100l\%(abcde\)
```

のように、各行を指定してから abcde (abcdef ではない) を検索するパターンの場合、
すべての行の abcde に hlsearch がハイライトされますが、cursorline をオンにして、
この画面を最初から最後までカーソルを移動させると描画が遅いです。

``` vim
function! T()
    call cursor(1, 1)
    let t = reltime()
    for l in range(1, line('$'))
        call cursor(l, 1)
        redraw
    endfor
    echo reltimestr(reltime(t))
endfunction
```

で Windows 7 で計測すると、

| バージョン | 計測時間 |
| --- | --: |
| vim 7.3.1314 | 0.07 |
| vim 7.4.274 | 0.08 |
| vim 7.4.364 | 0.48 |

で、相当遅くなっています。

vim 7.4.364 では

| 状態 | 計測時間 |
| --- | --: |
| hlsearch オフ | 0.07 |
| cursorline オフ | 0.10 |
| 両方オフ | 0.06 |

になるので、これらのオプションが影響している可能性があります。

ちなみに、検索パターンはこれで生成しています。

``` vim
function! S()
    let s = []
    for l in range(1, line('$'))
        let s += ['\%' . l . 'l\%(abcde\)']
    endfor
    let @/ = join(s, '\|')
endfunction
```

**Comment by mattn** [comment]
Windows で試してみましたが、それほど気になりませんでした。

**Comment by rickhowe** [comment]
これは問題を再現するための例でして、同じ仕組みで動いているスクリプトが遅くて使いものにならないので困っています。

**Comment by mattn** [comment]
例えばどのプラグインでしょうか？
遅いのを確認したいのですが。

**Comment by rickhowe** [comment]
自作のスクリプトです。英語と日本語の文章をタブで左右に分けて、右側にある数字や英単語を左側と照合して、スペルミスなどを検証するものです。パッチ274では問題ないので、それ以降のパッチで何かあったのでしょうか？

**Comment by rickhowe** [comment]
手元にあった最近のバイナリで試したところ、7.4.353 では問題なく、7.4.364 で発生しますので、以下のいずれかのパッチが原因のようです。どなたか心当たりはありますでしょうか？また。どこかにバイナリがありましたらその入手方法を教えてください。
7.4.354  compiler warning
7.4.355  several problems with Javascript indenting
7.4.356  mercurial does not ignore memfile_test
7.4.357  after completion some characters are not redrawn
7.4.358  (after 7.4.351) sort is not always stable
7.4.359  if 'ttymouse' set to 'uxterm' xterm version is not requested
7.4.360  pattern with "$" followed by [vV] is not used as end-of-line
7.4.361  flickering when filling the preview window for 'omnifunc'
7.4.362  short length in matchaddpos() highlights until end of the line
7.4.363  in Windows console typing 0xCE does not work
7.4.364  no error message when the viminfo file can't be renamed

**Comment by mattn** [comment]
7.4.362  short length in matchaddpos() highlights until end of the line

おそらくこれですね。

On 8/5/14, ZBryce notifications@github.com wrote:

> 手元にあった最近のバイナリで試したところ、7.4.353 では問題なく、7.4.364
> で発生しますので、以下のいずれかのパッチが原因のようです。どなたか心当たりはありますでしょうか？また。どこかにバイナリがありましたらその入手方法を教えてください。
> 7.4.354  compiler warning
> 7.4.355  several problems with Javascript indenting
> 7.4.356  mercurial does not ignore memfile_test
> 7.4.357  after completion some characters are not redrawn
> 7.4.358  (after 7.4.351) sort is not always stable
> 7.4.359  if 'ttymouse' set to 'uxterm' xterm version is not requested
> 7.4.360  pattern with "$" followed by [vV] is not used as end-of-line
> 7.4.361  flickering when filling the preview window for 'omnifunc'
> 7.4.362  short length in matchaddpos() highlights until end of the line
> 7.4.363  in Windows console typing 0xCE does not work
> 7.4.364  no error message when the viminfo file can't be renamed
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/603#issuecomment-51075200

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
``` vim
function! g:T()
    call cursor(1, 1)
    let t = reltime()
    for l in range(1, line('$'))
        call cursor(l, 1)
        redraw
    endfor
    echo reltimestr(reltime(t))
endfunction
set cursorline
set hlsearch
let @/='m'
```

このスクリプトを実行した後、`:e mbyte.c` `:syntax on` して `:call g:T()` してみました。
私の環境 Windows7 で 3.8 秒程度らしいのですが、 @ZBryce さんの環境だとどうでしょうか？

**Comment by rickhowe** [comment]
Windows 7 ですが、7.4.353 でも 7.4.364 でも 5.0～5.2 秒程度で変わりません。
検索パターンで '\%1l' のように、行を指定する場合に問題が発生するようなのですが。
もう一度最初に示した例を試してみましたが、7.4.353 で 0.1 秒ほど 7.4.364 では 1.3秒で、10 倍以上遅いです。

**Comment by h-east** [comment]
CUI Vim on Fedora19(64bit) via PuTTYで再現しました。

### 再現手順

以下の内容の `~/test603.vim`を用意。

``` vim
function! T()
    call cursor(1, 1)
    let t = reltime()
    for l in range(1, line('$'))
        call cursor(l, 1)
        redraw
    endfor
    echo reltimestr(reltime(t))
endfunction

function! S()
    let s = []
    for l in range(1, line('$'))
        let s += ['\%' . l . 'l\%(abcde\)']
    endfor
    let @/ = join(s, '\|')
endfunction

:set hlsearch
:set cursorline
:call setline(1, repeat(['abcdef'], 100))
:call S()
:call T()
```

以下の感じで実行。

```
$ vim -N -u ~/test603.vim
```

すると下から2行目に`1.130022`のように処理時間が表示される。
(Vimの終了は`:q!`でよろしく)

### 計測結果

| Ver. | elapsed |
| --- | --- |
| 7.4.131 | 0.045500 |
| 7.4.361 | 0.046550 |
| 7.4.362 | 1.136427 |
| 7.4.398 | 1.135489 |

mattnさんの予想通り 7.4.362 から遅くなってます。（当社比 約25倍）

**Comment by h-east** [comment]
うはー、7.4.362は実質1文字しか変わっていないｗｗ
しかも日本人らしき人が「MacVimでスクロールさせたらめっちゃCPU食うんすけど」って7月10日に報告してる。

https://groups.google.com/d/msg/vim_dev/3PNuYKQ9EAk/ZD9vuxSVHgoJ

**Comment by k-takata** [comment]
7.4.362の変更は以下の通りですが、

``` diff
--- a/src/screen.c
+++ b/src/screen.c
@@ -3852,7 +3852,7 @@ win_line(wp, lnum, startrow, endrow, noc
            {
                shl->attr_cur = shl->attr;
            }
-           else if (v == (long)shl->endcol)
+           else if (v >= (long)shl->endcol)
            {
                shl->attr_cur = 0;
                next_search_hl(wp, shl, lnum, (colnr_T)v, cur);
```

これを `else if ((v == (long)shl->endcol) || (v == (long)(shl->endcol + 1)))`  に変えたらどうですかね？（動作未確認）

**Comment by h-east** [comment]
@k-takata マルチバイトを考慮しないとあかんぽいです。
上記patchを適用して

```
aあbc
```

の行に対して

``` vim
:highlight MyGroup ctermbg=green guibg=green
:let m = matchaddpos("MyGroup", [[1,2,1]])
```

とやると行末までハイライトされました。(utf-8)

**Comment by ynkdir** [comment]
ちょっとずれますが ubuntu の gnome-terminal, mlterm, xterm で上の再現スクリプトを実行すると vim 終了後も cursorline が消えない事象

$ vim -N -u test603.vim
:q!

![screenshot from 2014-08-14 16 39 03](https://cloud.githubusercontent.com/assets/142094/3917121/d96a4c58-2386-11e4-87bf-7f9171afe8ec.png)

**Comment by h-east** [comment]
@ynkdir うわー:grin:

CUI Vim on Fedora19(64bit) via PuTTY(TERM=putty-256color) では発生しませんでしたが、
CUI Vim on Fedora19(64bit) via PuTTY(TERM=xterm-256color) で発生しました。

**Comment by h-east** [comment]
これで機能はそのままに処理時間がほぼ元に戻ったはず。

```
$ vim -N -u ~/test603.vim
```

Vim 7.4.404 on fedora19で`0.053999`になったよ！
(7.4.361に比べて16%ほど遅くなっているけど、7.4.361は処理が不足していたのでそこから若干処理時間が増加するのはしょうがないです。)

``` diff
diff -r 18fd959b07ef src/screen.c
--- a/src/screen.c  Wed Aug 13 22:05:54 2014 +0200
+++ b/src/screen.c  Fri Aug 15 23:07:22 2014 +0900
@@ -3856,9 +3856,20 @@
                && v >= (long)shl->startcol
                && v < (long)shl->endcol)
            {
+               int vlen;
+
                shl->attr_cur = shl->attr;
+#ifdef FEAT_MBYTE
+               if (has_mbyte)
+               {
+               int vlen = (*mb_ptr2len)(line + v);
+
+               if (shl->endcol - shl->startcol < vlen)
+                   shl->endcol = shl->startcol + vlen;
+               }
+#endif
            }
-           else if (v >= (long)shl->endcol)
+           else if (v == (long)shl->endcol)
            {
                shl->attr_cur = 0;
                next_search_hl(wp, shl, lnum, (colnr_T)v, cur);
```

@ZBryce 検証お願いします。ってpatchあててバイナリ作成する環境ないんでしたっけ？

**Comment by Shougo** [comment]
:+1:

**Comment by h-east** [comment]
vim_devに投稿しました。
https://groups.google.com/d/msg/vim_dev/3PNuYKQ9EAk/F2u-iKTUY8YJ

**Comment by ynkdir** [comment]
選択範囲が文字をまたぐ場合にうまくいかないです

``` vim
:call setline(1, 'aあaaa')
:call matchaddpos('Error', [[1, 1, 2]])
```

**Comment by h-east** [comment]
@ynkdir うー。必要でしたらvim_devにも報告お願いしますm(_ _)m

**Comment by ynkdir** [comment]
報告しました

**Comment by h-east** [comment]
@ynkdir ありがとうございます。
しっかしこの`win_line()`関数も結構カオスですね。

**Comment by h-east** [comment]
ynkdirさん指摘の分は直ったと思います。

あと開始桁がマルチバイト文字の途中からだった場合にハイライト長が長くなるというバグが残ってます。
出かけなきゃいけないのでとりあえずここまで。

``` diff
diff -r 18fd959b07ef src/screen.c
--- a/src/screen.c  Wed Aug 13 22:05:54 2014 +0200
+++ b/src/screen.c  Sat Aug 16 13:01:55 2014 +0900
@@ -2912,6 +2912,7 @@
     int        mb_utf8 = FALSE;    /* screen char is UTF-8 char */
     int        u8cc[MAX_MCO];      /* composing UTF-8 chars */
 #endif
+    int        hl_len = 0;
 #ifdef FEAT_DIFF
     int        filler_lines;       /* nr of filler lines to be drawn */
     int        filler_todo;        /* nr of filler lines still to do + 1 */
@@ -3832,6 +3833,12 @@
         * priority).
         */
        v = (long)(ptr - line);
+#ifdef FEAT_MBYTE
+       if (has_mbyte)
+           hl_len += (*mb_ptr2len)(ptr);
+       else
+#endif
+           ++hl_len;
        cur = wp->w_match_head;
        shl_flag = FALSE;
        while (cur != NULL || shl_flag == FALSE)
@@ -3857,10 +3864,15 @@
                && v < (long)shl->endcol)
            {
                shl->attr_cur = shl->attr;
+#ifdef FEAT_MBYTE
+               if (shl->endcol < hl_len)
+               shl->endcol = hl_len;
+#endif
            }
-           else if (v >= (long)shl->endcol)
+           else if (v == (long)shl->endcol)
            {
                shl->attr_cur = 0;
+               hl_len = 0;
                next_search_hl(wp, shl, lnum, (colnr_T)v, cur);
                pos_inprogress = cur == NULL || cur->pos.cur == 0
                                  ? FALSE : TRUE;
```

**Comment by h-east** [comment]
> あと開始桁がマルチバイト文字の途中からだった場合にハイライト長が長くなるというバグが残ってます。

```
:call setline(1, 'aあbcんde')
:call matchaddpos('Error', [[1, 3, 5]])
```

で「`bcん`がハイライトされてしまう...あかん！」と思ってたんですが、私のpatch適用前でも`bcん`なのでこれで良しとします。

特に問題がなければ(ソース整理して)今晩再投稿します。

**Comment by h-east** [comment]
投稿予定patch

``` diff
diff -r 18fd959b07ef src/screen.c
--- a/src/screen.c  Wed Aug 13 22:05:54 2014 +0200
+++ b/src/screen.c  Sat Aug 16 20:13:23 2014 +0900
@@ -2911,6 +2911,7 @@
     int        mb_c = 0;       /* decoded multi-byte character */
     int        mb_utf8 = FALSE;    /* screen char is UTF-8 char */
     int        u8cc[MAX_MCO];      /* composing UTF-8 chars */
+    int        hl_len = 0;
 #endif
 #ifdef FEAT_DIFF
     int        filler_lines;       /* nr of filler lines to be drawn */
@@ -3832,6 +3833,10 @@
         * priority).
         */
        v = (long)(ptr - line);
+#ifdef FEAT_MBYTE
+       if (has_mbyte)
+           hl_len += (*mb_ptr2len)(ptr);
+#endif
        cur = wp->w_match_head;
        shl_flag = FALSE;
        while (cur != NULL || shl_flag == FALSE)
@@ -3857,10 +3862,17 @@
                && v < (long)shl->endcol)
            {
                shl->attr_cur = shl->attr;
+#ifdef FEAT_MBYTE
+               if (has_mbyte && shl->endcol < hl_len)
+               shl->endcol = hl_len;
+#endif
            }
-           else if (v >= (long)shl->endcol)
+           else if (v == (long)shl->endcol)
            {
                shl->attr_cur = 0;
+#ifdef FEAT_MBYTE
+               hl_len = 0;
+#endif
                next_search_hl(wp, shl, lnum, (colnr_T)v, cur);
                pos_inprogress = cur == NULL || cur->pos.cur == 0
                                  ? FALSE : TRUE;
```

**Comment by ynkdir** [comment]
コードはよくわからないですが
簡単な手動テストで問題なしです

**Comment by h-east** [comment]
@ynkdir 動作確認ありがとうございます。

vim_devに再投稿しました。
https://groups.google.com/d/msg/vim_dev/3PNuYKQ9EAk/F2u-iKTUY8YJ

vim_useでも問題になっていたようです。
https://groups.google.com/d/msg/vim_use/V6cRWX4c13E/9LTU7lrrflsJ

**Comment by k-takata** [comment]
7.4.405
https://groups.google.com/d/topic/vim_dev/-n0Id0aFn3s/discussion
別の修正方法が来ました。（直ったかどうかは未確認です。）

**Comment by h-east** [comment]
直ってます。
「そんな単純な修正で良かったのかぁぁぁ！」って感じです:smile:

**Comment by h-east** [comment]
@ZBryce Issue登録ありがとうございました。
@ynkdir アドバイスありがとうございました。ところで https://github.com/vim-jp/issues/issues/603#issuecomment-52153259 の件、別Issue立てますか？

**Comment by ynkdir** [comment]
いちおう立てときます

**Comment by rickhowe** [comment]
7.4.408 で当初の問題が発生しないことを確認しました。ありがとうございました。
