### ISSUE TITLE
$でカーソルを行末尾に移動直後にcurswantの値がおかしい

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#604]
カーソルを縦方向に動かす際、マルチバイト文字やタブ文字、あるいは現在のカーソル桁よりも短い行を通過するときでも本来あるべきカーソル桁を保存するために `curswant` という値があります。これは `winsaveview()` 関数、あるいはVim 7.4 patch-313番が当たっていると `getcurpos()` 関数で取得できます。

この値がノーマルモードの `$` コマンドで移動直後に上記関数で取得すると不適切と思われる値を返します。私の手元では次の手順で再現します。

``` vim
new
normal! $
echomsg string(winsaveview())
" -> {'lnum': 1, 'leftcol': 0, 'col': 0, 'topfill': 0, 'topline': 1, 'coladd': 0, 'skipcol': 0, 'curswant': 2147483647}
```

文字の有無は関係ないようで、空バッファでも再現します。お手の空いている方がいらっしゃいましたら、再現するか試していただけませんか？

**Comment by mattn** [comment]
どんな行末よりも右側を意味する値です。intの最大値ですね。

On 8/4/14, machakann notifications@github.com wrote:

> カーソルを縦方向に動かす際、マルチバイト文字やタブ文字、あるいは現在のカーソル桁よりも短い行を通過するときでも本来あるべきカーソル桁を保存するために
> `curswant` という値があります。これは `winsaveview()` 関数、あるいはVim 7.4 patch-313番が当たっていると
> `getcurpos()` 関数で取得できます。
> 
> この値がノーマルモードの `$` コマンドで移動直後に上記関数で取得すると不適切と思われる値を返します。私の手元では次の手順で再現します。
> 
> ``` vim
> new
> normal! $
> echomsg string(winsaveview())
> " -> {'lnum': 1, 'leftcol': 0, 'col': 0, 'topfill': 0, 'topline': 1,
> 'coladd': 0, 'skipcol': 0, 'curswant': 2147483647}
> ```
> 
> 文字の有無は関係ないようで、空バッファでも再現します。お手の空いている方がいらっしゃいましたら、再現するか試していただけませんか？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/604

## 
- Yasuhiro Matsumoto

**Comment by machakann** [comment]
ああ、なるほど。ということは、必ず行末へ行くようにそうなっているという仕様ということでしょうか？

**Comment by mattn** [comment]
はい。その仕様です。

On 8/4/14, machakann notifications@github.com wrote:

> ああ、なるほど。ということは、必ず行末へ行くようにそうなっているという仕様ということでしょうか？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/604#issuecomment-50993285

## 
- Yasuhiro Matsumoto

**Comment by machakann** [comment]
ちなみに後出しになって申し訳ないんですが、 `getcurpos()` 関数だと負数が帰るのですがこれはどういうことなんでしょう？

``` vim
new
normal! $
echomsg string(getcurpos())
" -> [0, 1, 1, 0, -2147483648]
```

**Comment by machakann** [comment]
あ、すいません。何か勘違いしていたみたいです。どうも、 `winsaveview()` 関数が返す `curswant` と `getcurpos()` 関数の返す `curswant` は微妙にちがうみたいです。後者は常に前者+1されています。なので2147483647+1でintの最小値へ循環しているだけですね。

疑問が解けました、ありがとうございます。

**Comment by haya14busa** [comment]
> getcurpos() 関数だと負数が帰る

(実装はまだ見ていませんが...)これ、 @machakann さんがおっしゃってる理由, 常に `winsaveview()`における `curswant + 1` が返ってきてるせいで最小値になっているということは理解できるのですが、これは直してもいい挙動なのではないでしょうか?

~~`curswant` の値がintの最大値から一転してマイナスになってしまうということは, カーソルが必ず**行末**に移動する挙動から, 必ず**行頭**に移動する挙動に変わってしまうことになっています。~~

これでは`getcurpos`における `curswant`の値を使ってるすべてのスクリプトで意図しない挙動が起こってしまう可能性があることになり、回避したければ必ず値がネガティブになっているか確認する or `winsaveview()`使えということになってしまいます

**Comment by haya14busa** [comment]
> curswant の値がintの最大値から一転してマイナスになってしまうということは, カーソルが必ず行末に移動する挙動から, 必ず行頭に移動する挙動に変わってしまうことになっています。

すいません、試したところカーソル移動の挙動に関しては `curswant` が `-2147483648` の状態でも行末に移動しました...

ただ例えば`:call winrestview({'curswant': -100})`しても`curswant`の値は`0`にリセットされるようだし, やはり個人的な希望としてはそもそも負数になってほしくなかったり

**Comment by machakann** [comment]
`winsaveview()` と比較して `getcurpos()` が後発であることを考えるとそんなに不自然でもないと思っていましたが、 `getcurpos()` の挙動だけで見ると確かに不自然のような気もしてきました。せめて、 help に記載がないと、予期しがたい挙動ですね。

**Comment by machakann** [comment]
該当するソースは eval.c の11936行目

``` c
    if (getcurpos)
        list_append_number(l, (varnumber_T)curwin->w_curswant + 1);
```

ここでしょうか。

もし、修正するとしたら `getcurpos()` の場合も桁あふれをする場合はこれを防いで、intの最大値に設定するという感じでしょうか。それでも問題はなさそうな気はします。

**Comment by haya14busa** [comment]
> もし、修正するとしたら getcurpos() の場合も桁あふれをする場合はこれを防いで、intの最大値に設定するという感じでしょうか。それでも問題はなさそうな気はします。

僕はそうなると良いと思いました。

桁溢れしている状態だとこういうケースでも問題になりました

### 再現手順
1. `vim -N -u NONE`
2. `:normal! $`
3. `:let pos = getcurpos() " pos == [0, 1, 1, 0, -2147483648]`
4. `:normal! 0`
5. `:call setpos('.', pos)`
6. `:echo (getcurpos() == pos) " Result: 0, Expect: 1`

##### 追記

この時 `:echo getcurpos() " => [0, 1, 1, 0, 1]` になっています.
`[0, 1, 1, 0, 2147483647]` になって`(getcurpos() == pos)` がfalseになったというわけではないので、その後`j`,`k`で移動したときなどの挙動も変わってしまっています

### winsaveview()の場合はok
1. `vim -N -u NONE`
2. `:normal! $`
3. `:let w = winsaveview()`
4. `:normal! 0`
5. `:call winrestview(w)`
6. `:echo (winsaveview() == w) " Result: 1, Expect: 1`

`:h getcurpos()` の例を見る限り, `getcurpos()`を `setpos()`でリストアする使用方は間違っていないと思います.
そこで、`getcurpos()`の`curswant`値がマイナスだと`setpos()`したときに`curswant`の値が負数になっているせいで変更されてしまい、curswantの値を`getcurpos` & `setpos`では正しく再現できなくなってしまっています.

**Comment by mattn** [comment]
問題があるっぽいので re-open しますね。

**Comment by h-east** [comment]
とりあえず @machakann さんが指摘している部分のpatchを書きました。
`w_curswant`でgrepすると他にも怪しそうな箇所はあるので見つけた人は教えて下さい。
(私も明日ひと通りチェックはします)

``` diff
diff -r 661e95466448 src/eval.c
--- a/src/eval.c    Sun Nov 23 15:57:49 2014 +0100
+++ b/src/eval.c    Mon Nov 24 04:24:38 2014 +0900
@@ -11937,7 +11937,8 @@
 #endif
                                  (varnumber_T)0);
    if (getcurpos)
-       list_append_number(l, (varnumber_T)curwin->w_curswant + 1);
+       list_append_number(l, (curwin->w_curswant == MAXCOL) ?
+           (varnumber_T)MAXCOL : (varnumber_T)curwin->w_curswant + 1);
     }
     else
    rettv->vval.v_number = FALSE;
```

**Comment by machakann** [comment]
@h-east さんパッチありがとうございます。
パッチあてて試してみました。(32bit 版 gvim 7.527 on Windows 7 64bit) @haya14busa さんの提示されているケースで問題ないことを確認しました。

**Comment by h-east** [comment]
特に指摘がなければ1week以内に上記patchをvim_devに投げようと思います。

**Comment by h-east** [comment]
sent vim_dev イェーア:thumbsup:
https://groups.google.com/d/msg/vim_dev/CMAGD6obzKo/tGUr7i-s-DIJ

**Comment by haya14busa** [comment]
ありがとうございます！ :+1:

**Comment by h-east** [comment]
2014/12/14にtodo入りしてましたわ。
https://github.com/vim-jp/vim/commit/4ef3ea7d06794f1e8b4b46bfaa5736a565549386#diff-38d7929bd26d74d92ceddf984bbfc8dbR111

> Patch to fix that getcurpos() returns a negative number, instead of MAXCOL.
> (Hirohito Higashi, 2014 Dec 8)

**Comment by h-east** [comment]
Patch 7.4.578
https://groups.google.com/d/msg/vim_dev/2JqJBjIJXP4/z4pibMFjbFQJ

**Comment by haya14busa** [comment]
おつかれさまです :+1:

**Comment by machakann** [comment]
ありがとうございます！
