### ISSUE TITLE
Vim script の実行に CTRL-C で割り込めなくできる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#606]
<blockquote class="twitter-tweet" lang="ja"><p>Vim script実行中にCTRL-Cすると割り込み入って停止する。だけど、nnoremap &lt;C-C&gt; &lt;C-C&gt;をしていると割り込み入らなくなった。なんでだろ？</p>&mdash; katono (@katono123) <a href="https://twitter.com/katono123/statuses/498095756310364160">2014, 8月 9</a></blockquote>

ちょっと気になったので。

**Comment by k-takata** [comment]
Issue 26 - vim - Ctrl-C doesn't perform interrupt after map/unmap
https://code.google.com/p/vim/issues/detail?id=26
Ctrl-C をマップしているときは、割り込みを無効化しているらしい？

**Comment by mattn** [comment]
Patch 7.4.468
https://groups.google.com/forum/#!topic/vim_dev/7oPW8GcG0dc
