### ISSUE TITLE
updatetime の間隔で謎のキーシーケンス <80><fd>` が送られてくる

### ISSUE THREAD

**Issue by rhysd** [vim-jp/issues#607]
端末の Vim で下記のスクリプトを実行したあと，`f` を押したあと入力待ちのまま置いておくと，コマンドライン `<80><fd>`` が表示されます．どうやら`<expr>` マッピング実行中に端末からそのシーケンスが送信されてきて，`getchar()` が勝手にそれを食ってしまっているようなのですが，この挙動がバグなのかどうなのか分からないのですが，何かご存知の方いらっしゃいますでしょうか？

``` vim
augroup hogehoge
    autocmd!
    autocmd CursorHold,CursorHoldI,WinEnter * setlocal cursorline
augroup END

function! s:foo()
    echomsg getchar()
    return ''
endfunction

nnoremap <expr>f <SID>foo()
```
### Vim

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  2 2014 14:10:13)
MacOS X (unix) version
Included patches: 1-383

**Comment by osyo-manga** [comment]
別の issues でも話題になっていたのでリンク貼っておきます

https://github.com/osyo-manga/vital-over/pull/48

**Comment by rhysd** [comment]
ありがとうございます！

**Comment by rhysd** [comment]
https://twitter.com/kefir_/status/498286234855145472

> @linda_pp 端末ですか？マウスコードで入力側に出ることが有り得るシーケンスだと思いますが、前後の状況とかがわからないとむずかしいです。

**Comment by osyo-manga** [comment]
こっちにも別の issues で再現したコードを貼っておきますね。

``` vim
if has('vim_starting')
    set nocompatible
endif

augroup test
    autocmd!
    autocmd CursorHold * echom "CursorHold"
    " これが定義されていない場合は再現しない
     autocmd CursorHold * call feedkeys("g\<ESC>")
augroup END


function! s:check()
    echom "chech start"
    " <expr> から呼び出された場合、<80><fd>` が入力される
    let char = getchar()
    echom "getchar() : " . char
    echom "check finish"
    return ""
endfunction

" <expr> でマッピングした場合、getchar() 時に意図しない文字（<80><fd>`）が入力される
nnoremap <expr> <f8> <SID>check()

" <expr> でない場合は再現しない
nnoremap <f9> :call <SID>check()<CR>


set updatetime=500
```

**Comment by saitoha** [comment]
CursorHold版で再現しました。
同時に端末からは何もキーシーケンスが送られていないことを確認したので、vim内部から出ていると思います。

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 28 2014 09:45:33)
MacOS X (unix) version
Included patches: 1-383

**Comment by saitoha** [comment]
すいません。もういちどやったら再現がとれず、さっきどのvimを起動してたか微妙になってしまったので、
再現報告は一旦白紙でお願いします。

**Comment by rhysd** [comment]
あれっ，すみません，上記のサンプルスクリプト，自分の設定を読み込んで実行していました… `vim -u NONE` で起動した Vim で再現しませんでした…

**Comment by saitoha** [comment]
mapとかgetchar周りで、K_SPECIAL(0x80)とかKS_EXTRA(0xfd)を一旦エスケープして格納してから元に戻す、みたいなことをやってるので、このへんかなという気もします。

**Comment by rhysd** [comment]
`CursorHold` イベントをフックしていると起きることが分かりました．

``` vim
augroup hogehoge
    autocmd!
    autocmd CursorHold,CursorHoldI,WinEnter * setlocal cursorline
augroup END
```

上の再現例を更新しておきます．

**Comment by h-east** [comment]
Vim 7.4.398 on fedora19(64bit) via PuTTY(xterm-256color or putty-256color)で100%再現しました。
(7.4.388, 7.4.389でも再現)
再現手順

(1) Issue本文にあるスクリプトを `~/test.vim` に保存。
(2) Vim起動。

```
vim -N -u ~/test.vim
```

(3)  一度インサートモードに入ってすぐ抜ける。 （これをしないと再現しないっぽい）

```
i<Esc>
```

(4) `f` を押下して5秒ほど待つ。

するとコマンドラインに `<80><fd>`` が表示される。

**Comment by saitoha** [comment]
出してる箇所はみつけたんですが、わざと入れてるみたいなので、getcharのこの仕様なのでは

```
                [expr] が省略されたときや [expr] が0のときは、文字全体または特
                殊キーを返す。それが8ビット文字なら戻り値は数値である。これを
                文字列に戻すにはnr2char()を使う。8ビット文字でないならばエン
                コードして文字列にして返す。
                特殊キーとは0x80(10進数で128)で始まるバイト列である。これは
                文字列 "\<Key>" と同じ値である(例: "\<Left>")。戻り値は文字列
                であり、修飾キー(shift, control, alt)は含まれない
```

つまり、CursorHoldが呼ばれたことを示す特殊キーか何かの可能性はないでしょうか。

**Comment by rhysd** [comment]
@h-east 
再現手順ありがとうございます…！

@saitoha 
解析ありがとうございます．
イベントが呼ばれたときに特殊キーが飛ぶというのはヘルプでも見たこと無いですし，初耳です…

**Comment by saitoha** [comment]
@rhysd 
たとえば、マウスイベントなんかでは特殊キーが飛んでいます。
CursorHoldの場合は、KE_CURSORHOLDという特殊キーが送られています。
https://github.com/vim-jp/vim/blob/master/src/os_unix.c#L424
これは、間違ってこうなっちゃったとはとても思えないので、仕様のような気がしました。
問題があるとすれば、文字列 \ ＜CursorHold>でこれを参照できていないということだと思うので、こっちを直すという手はあるのでは。

**Comment by h-east** [comment]
補足。
saitohaさんのコメントのリンク先のL427からの3行がまさに  <80><fd>` `0x80 0xfd 0x60`を送ってますね。

```
427     buf[0] = K_SPECIAL;
428     buf[1] = KS_EXTRA;
429     buf[2] = (int)KE_CURSORHOLD;
```

saitohaさんの言ってるようにgetchar()の仕様だと思います。

> 問題があるとすれば、文字列 \ ＜CursorHold>でこれを参照できていないということだと思うので、こっちを直すという手はあるのでは。

script内でgetchar()への入力が`0x80 0xfd 0x60`(CursorHold)の場合を判定出来る仕組みがあれば良いとうことでOKですか？＞ @rhysd @osyo-manga

**Comment by h-east** [comment]
`0x80 0xfd 0x60`を "<CursorHold>" で参照出来るようにするpatch。

``` diff
diff -r 913d16b4904c src/misc2.c
--- a/src/misc2.c   Thu Aug 07 13:55:10 2014 +0200
+++ b/src/misc2.c   Sun Aug 10 23:32:29 2014 +0900
@@ -2470,6 +2470,7 @@
     {K_SNR,        (char_u *)"SNR"},
 #endif
     {K_PLUG,       (char_u *)"Plug"},
+    {K_CURSORHOLD, (char_u *)"CursorHold"},
     {0,            NULL}
 };
```

scriptはこんな感じ。

``` vim
augroup hogehoge
    autocmd!
    autocmd CursorHold,CursorHoldI,WinEnter * setlocal cursorline
augroup END

function! s:foo()
    let c = 0
    while c == "\<CursorHold>"
        let c = getchar()
    endwhile
    echomsg c
    return ''
endfunction

nnoremap <expr>f <SID>foo()
```

これでgetchar()がCursorHoldに邪魔されなくなる。これでOK？

**Comment by rhysd** [comment]
@saitoha @h-east 
ありがとうございます．シーケンスが何者かすら分からなかったので助かります．

> script内でgetchar()への入力が0x80 0xfd 0x60(CursorHold)の場合を判定出来る仕組みがあれば良いとうことでOKですか？

はい，僕はそういう認識です．
おっしゃるように，CursorHold のシーケンスが参照できないのが問題だと思います．（keymap.c に `K_CURSORHOLD` 自体は存在するようですが，それが外から見られない状態というわけですね）．
上で言及されているように，`"\<CursorHold>"` で `0x80 0xfd 0x60` が識別できるのが，`<Left>` などの実装に加えるだけで良く，良さそうに見えますが，いかがでしょうか．

**Comment by h-east** [comment]
投稿しました。
https://groups.google.com/d/msg/vim_dev/IkvEcbVXUFk/QyzgHKRnI8QJ

**Comment by haya14busa** [comment]
すいません、自分が無知なだけなのかもしれませんが質問をさせてください。

> たとえば、マウスイベントなんかでは特殊キーが飛んでいます。
> CursorHoldの場合は、KE_CURSORHOLDという特殊キーが送られています。

イベントが特殊キーが送られてくることで処理されているということはわかったのですが,
今回の `<80><fd>`` `が`getchar()`に勝手に入力される問題は`<expr>`マッピングを
使っている場合のみであって、普通に`call`で読んだ場合は再現しません。

```
nnoremap <silent> F :call <SID>foo()<CR>
```

これは、 普通(`<expr>`を使わない場合)は `getchar()`中に `CursorHold` が呼ばれない
けど, `<expr>` マッピングだとイベント呼ばれて 特殊キーが送られて来ているということなんでしょうか?

**Comment by saitoha** [comment]
@haya14busa なんでそういう挙動になってるのか、ちょっと調べてみましたが、ちょっとややこしい話になっていて、expr付きと無しとでは、基本的には同じノーマルモードで実行されているようなのですが、内部的には違うモードというか、異なる状態で実行されています。
具体的には、普通のNORMALと、コマンド実行中を表わすNORMAL_BUSYという状態があるらしく、expr付きのときは、NORMAL_BUSYで実行されるため、CursorHoldイベントが発行されるようになります。
この挙動のどこまでが仕様なのか、という話になりますが、そもそも常識的に考えて、この2つの状態を、Vimユーザには意識させてはいけないと思うので、たぶん不具合があると思います。
ただ、NORMAL_BUSYを導入した経緯とか、CursorHoldイベントの発行タイミングの正確な仕様を把握していないので、どう直せばいいのかについては、私では手に余る感じです。

**Comment by saitoha** [comment]
副作用があるかもしれないですけど、expr無しの状態で挙動を統一するパッチです。

``` diff
diff -r 0f0a94348ba7 src/getchar.c
--- a/src/getchar.c Sat Jul 12 21:41:49 2014 +0900
+++ b/src/getchar.c Mon Aug 11 23:03:25 2014 +0900
@@ -4607,6 +4607,7 @@
     pos_T  save_cursor;
     int        save_msg_col;
     int        save_msg_row;
+    int        save_State;

     /* Remove escaping of CSI, because "str" is in a format to be used as
      * typeahead. */
@@ -4632,6 +4633,9 @@
     save_cursor = curwin->w_cursor;
     save_msg_col = msg_col;
     save_msg_row = msg_row;
+    save_State = State;
+    if (State == NORMAL_BUSY)
+   State = NORMAL;
     p = eval_to_string(expr, NULL, FALSE);
     --textlock;
 #ifdef FEAT_EX_EXTRA
@@ -4640,6 +4644,7 @@
     curwin->w_cursor = save_cursor;
     msg_col = save_msg_col;
     msg_row = save_msg_row;
+    State = save_State;

     restore_cmdline_alloc(save_cmd);
     vim_free(expr);
```

**Comment by mattn** [comment]
@saitoha さんのパッチに賛成です。

**Comment by h-east** [comment]
@saitoha :+1: 
`make test`はOKでした。

```
Test results:
ALL DONE
```

私のvim_dev投稿に対して「それよりもこうじゃね！？」って感じでお願いします。

**Comment by saitoha** [comment]
imapとかvmapの時の検討ができていなかったので、1行追加しました。

**Comment by saitoha** [comment]
@h-east すみません、もうちょっと考えます。
主に、NORMAL_BUSYってそもそも何よ、っていうところがわかってないのと、expr有りの方の挙動に合わせるべきかも、というところです。

**Comment by h-east** [comment]
ありがとうついでにBram氏に質問してみた:grin:
https://groups.google.com/d/msg/vim_dev/IkvEcbVXUFk/go8f3Z7j9QsJ

> BTW, Why getchar() catch up K_CURSORHOLD only in specify <expr>?
> What difference of NORMAL state and NORMAL_BUSY state?

**Comment by saitoha** [comment]
@h-east :+1:
回答を待ちましょう

**Comment by haya14busa** [comment]
@saitoha さん @h-east さんありがとうございます!!! :100:

なるほど `<expr>`  マッピング中は NORMAL_BUSY という違った状態になっていたんですね。
`getchar()`であえて特殊キーを受け付けたいということはなさそうだし、`<expr>`なしの
状態で統一されるといいなぁ。

**Comment by rhysd** [comment]
@h-east @saitoha 

おお，パッチ&詳細ありがとうございます…！

**Comment by mattn** [comment]
NORMAL_BUSY はユーザの入力を抑制する働きがある(それと一緒になっちゃってる)ので、そのままは使えないと思います。

**Comment by k-takata** [comment]
7.4.457
https://groups.google.com/d/topic/vim_dev/VUQPZjdIeW4/discussion
直ったのかな？

**Comment by h-east** [comment]
@k-takata あぅ...patch送付後の質問をスルーされてpatchだけ取り込まれてしまった:sweat:
回答もらってから @saitoha さんのpatchを推そうと思ってたのにorz

Patch 7.4.457だと`<expr>`使った時だけCursorHoldイベントが発行されるので、https://github.com/vim-jp/issues/issues/607#issuecomment-51716851 のサンプルのように自分で意識して捨てないといけないです。

**Comment by mattn** [comment]
仕様になってしまったらしい。

https://github.com/vim-jp/vim/commit/542d7043d900d20f3ef5c27580278d8d83d1016f#diff-0fe7b6318b0164afddbf8e6aa4b95874R519

**Comment by h-east** [comment]
閉じてもよかですか？ > all

それとも <expr> の有無に関わらずCursorHoldイベントが発行されないように働きかける？

**Comment by rhysd** [comment]
@h-east 
この issue が開いたままになっているのを把握できていませんでした．すみません．
仕様ということになったのであれば，こちら側で対処するようにするので，僕は閉じてしまっても大丈夫です．

**Comment by haya14busa** [comment]
仕様になってしまったようなので僕も閉じてしまってもokです。
あえて言うなら, 自分はわかってるのでいいのですが, `:h getchar()`の部分に`<expr>`で呼ぶと
`\<CursorHold>` が飛んでくるかもしれないという注意書きがないと, 知らない人は同様にハマってしまうのではないかと思いました。

**Comment by h-east** [comment]
@rhysd 了解です。

@haya14busa 

> :h getchar()の部分に<expr>で呼ぶと<CursorHold> が飛んでくるかもしれないという注意書き

確かに！同意です。
haya14busaさん(かどなたか)やって頂けません？
(私の英語力は知ってるでしょ:alien:)

**Comment by haya14busa** [comment]
``` diff
diff --git runtime/doc/eval.txt runtime/doc/eval.txt
index eb7fcbc..2329930 100644
--- runtime/doc/eval.txt
+++ runtime/doc/eval.txt
@@ -3304,6 +3304,16 @@ getchar([expr])                      *getchar()*
            :    endif
            :  endwhile
            :endfunction
+<      WARNING: If you call getchar() in an expression mapping, it
+       may see |<CursorHold>|.
+       This function avoid to get this character with getchar(): >
+           :function! s:getchar()
+           :  let c = 0
+           :  while c == "\<CursorHold>"
+           :    let c = getchar()
+           :  endwhile
+           :  return c
+           :endfunction

 getcharmod()                       *getcharmod()*
        The result is a Number which is the state of the modifiers for
```

僕も英語自信ないですが, 一応書いてみました。こんな感じですかね...?

**Comment by mattn** [comment]
この関数、CursorHold が来ない場合に常に 0 になりませんか？
あと英文ですが、もっと簡素な方がいい気がしました。僕も英語、自信無いですが。

```
WARNING: When calling getchar() in an expression mapping, you need to handle
|<CursorHold>|. For example, below's function avoid to get |<CursorHold>|.
```

**Comment by h-east** [comment]
> この関数、CursorHold が来ない場合に常に 0 になりませんか？

ウヒョー。私が3ヶ月前に書いたコードの時点で間違えてますやん＞＜

**Comment by haya14busa** [comment]
ｱｰ

**Comment by haya14busa** [comment]
数字(0)と文字列を比較してるのでtrueになってるんですね. 確認時に動いてたのはそういうことか

**Comment by haya14busa** [comment]
他の関数が書いてあるhelpの例を見ると`Example:`とかでも十分っぽいですかね...?

``` diff
diff --git runtime/doc/eval.txt runtime/doc/eval.txt
index eb7fcbc..a35be7f 100644
--- runtime/doc/eval.txt
+++ runtime/doc/eval.txt
@@ -3305,6 +3305,16 @@ getchar([expr])                      *getchar()*
            :  endwhile
            :endfunction

+<      WARNING: When calling getchar() in an expression mapping, you
+       need to handle |<CursorHold>|. Example: >
+           :function! s:getchar()
+           :  let c = getchar()
+           :  while c == "\<CursorHold>"
+           :    let c = getchar()
+           :  endwhile
+           :  return c
+           :endfunction
+
 getcharmod()                       *getcharmod()*
        The result is a Number which is the state of the modifiers for
        the last obtained character with getchar() or in another way.
```

**Comment by haya14busa** [comment]
(再帰で書きたい感あるけどmaxfuncdepthですよね...)

``` vim
:function! s:getchar()
:  let c = getchar()
:  return c == "\<CursorHold>" ? s:getchar() : c
:endfunction
```

**Comment by h-east** [comment]
do 〜 while () さえあれば...

**Comment by h-east** [comment]
@mattn 

> この関数、CursorHold が来ない場合に常に 0 になりませんか？

偶然このコード書いたんですけど、動作確認これでやったのでちゃんと動いてるんですよ。ほんとたまたまなんですけど。(苦笑)
例としてはよくないので修正には同意です。

**Comment by h-east** [comment]
@haya14busa Nice!

```
WARNING: When calling getchar() in an expression mapping,
```

のところ

```
WARNING: When calling getchar() in a mapping with <expr>,
```

としたほうが`<expr>`でジャンプ出来ていいかもと思いました。

**Comment by haya14busa** [comment]
確かにジャンプできたほうがよさそうですね。修正しました

``` patch
diff --git runtime/doc/eval.txt runtime/doc/eval.txt
index 4e349a6..f287c49 100644
--- runtime/doc/eval.txt
+++ runtime/doc/eval.txt
@@ -3305,6 +3305,16 @@ getchar([expr])                      *getchar()*
            :  endwhile
            :endfunction

+<      WARNING: When calling getchar() in a mapping with <expr>, you
+       need to handle |<CursorHold>|. Example: >
+           :function! s:getchar()
+           :  let c = getchar()
+           :  while c == "\<CursorHold>"
+           :    let c = getchar()
+           :  endwhile
+           :  return c
+           :endfunction
+
 getcharmod()                       *getcharmod()*
        The result is a Number which is the state of the modifiers for
        the last obtained character with getchar() or in another way.
```

**Comment by h-east** [comment]
@haya14busa そろそろvim_devに投げませんか？:smile:

**Comment by haya14busa** [comment]
> @haya14busa そろそろvim_devに投げませんか？:smile:

レスポンス遅くて申し訳ないです :bow:

これって僕から投げてみてもいい or 言い出しっぺの僕が出すべきですかね...?

**Comment by h-east** [comment]
@haya14busa 

> これって僕から投げてみてもいい

もちのろんです！お願いします。

**Comment by haya14busa** [comment]
ありがとうございます、投げてみました...! が、最初に投げる時とかって承認されるまでは表示されないのですかね?(間違ったかな...)

**Comment by h-east** [comment]
> 最初に投げる時とかって承認されるまでは表示されないのですかね?

その通りです。私は知らなくて6回くらい送信したのでえらい事になりましたｗ

**Comment by haya14busa** [comment]
6回すごいw ありがとうございます, では再送信とかせずに待っておきます...!

**Comment by h-east** [comment]
haya14busaさんのvim_dev投稿無事表示されました。 
https://groups.google.com/d/msg/vim_dev/MCpscf0LLlI/D12Q7BFhN-gJ

Bram氏の返事もいい感じなので取り込まれますよきっと:+1:

**Comment by k-takata** [comment]
https://github.com/vim-jp/vim/commit/dc5d9fcffb86711540568b88cba0d414f6066b5e#diff-bea881dfa9626bab7141337b0fcdb23eR3307
少し変更が入った上で取り込まれました。

**Comment by haya14busa** [comment]
ありがとうございましたー
