### ISSUE TITLE
ex履歴が更新されているか検証する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#61]
http://twitter.com/#!/thinca/status/120827820149719040

> ちゃんと検証してないんですが、:<C-p><C-p><C-p><CR> みたいにして履歴を実行した際に、履歴が更新されないことがあるような気がするんですよね。

過去に、検索履歴において方向を正しく考慮するように修正した変更が悪さをしている可能性がある。
その変更は、履歴内に検索方向を記憶しておき、履歴呼び出し時にその内容に応じた振る舞いをする、というものだった。
1. 上記修正が悪さをしてないことを確認する
2. ex履歴の異常動作について、さらに詳細な情報を観測する

**Comment by h-east** [comment]
「上記修正」に対するGoogle+での議論です。
https://plus.google.com/109717999406712153715/posts/6nVh2LrQbB2?hl=ja

**Comment by koron** [comment]
@h-east: Thanks!

修正パッチはコレ。
https://groups.google.com/forum/#!topic/vim_dev/jIImih0iTiE

**Comment by tyru** [comment]
パッチが取り込まれたので、これcloseしてもいいんじゃないでしょうか？

**Comment by h-east** [comment]
> パッチが取り込まれたので、これcloseしてもいいんじゃないでしょうか？

そのパッチというのはkoronさんが貼りつけた修正パッチのことでしょうか？
https://groups.google.com/forum/#!topic/vim_dev/jIImih0iTiE

これはissue本文の

> 過去に、検索履歴において方向を正しく考慮するように修正した変更が悪さをしている可能性がある。

の「修正した変更」のパッチです。
ですので、

> 履歴が更新されないことがあるような気がする

は手付かず状態のような気がします。

**Comment by tyru** [comment]
あ、なるほど。すみません。

**Comment by h-east** [comment]
特に問題起きてなさそうなので閉じます。
何かあれば再オープンお願いします。
