### ISSUE TITLE
複数行を削除した時のメッセージが重複している？

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#612]
複数行を削除した時、日本語だと `*行 削除しました` と、英語だと `* fewer lines`のようなメッセージが表示されますが、 `:messages` コマンドで確認すると一度の動作に対し二回メッセージが発行されているように見えます。

再現スクリプト

``` vim
normal! 3o
normal! d2k
messages
```

環境
windows 7 64bit, kaoriya版　32bit gvim 7.4.389

特に困るわけではないですが報告までに。

**Comment by h-east** [comment]
7.4.415: NG
7.4.131: NG
7.4.029: NG
7.3.777: NG
7.3.099: NG
7.2.099: NG
7.1.099: NG
7.0.099: NG

伝統的なバグっぽいです。
fix案は持ってます。

**Comment by machakann** [comment]
すごい、こんなに遡れるとは…。地味なのでだれも気にしなかったんでしょうね。

**Comment by h-east** [comment]
関連todoリスト

> Some quickfix messages appear twice. (Gary Johnson, 2014 Feb 16)
> Patch by Christian Brabandt, 2014 Feb 17.

https://groups.google.com/d/msg/vim_dev/5To2u8_CrKE/UTrIKMf_7QAJ

このIssueの現象も根は同じ。

**Comment by h-east** [comment]
ほい。これで直る。todoリストのやつも直る。

``` diff
diff -r babc6a1d4c27 src/main.c
--- a/src/main.c    Sat Aug 23 15:31:19 2014 +0200
+++ b/src/main.c    Mon Aug 25 00:02:59 2014 +0900
@@ -1243,7 +1243,6 @@
        /* msg_attr_keep() will set keep_msg to NULL, must free the
         * string here. */
        p = keep_msg;
-       keep_msg = NULL;
        msg_attr(p, keep_msg_attr);
        vim_free(p);
        }
```

`msg_attr()`というか`msg_attr_keep()`を呼び出す前に`keep_msg`を弄ると`add_msg_hist()`による2重追加を回避するロジックが効かなくなるので`keep_msg`は弄ってはだめ。
`keep_msg`の値(アドレス)を退避させておいて`msg_attr()`呼び出し後にfree()するだけで良いはず。

**Comment by mattn** [comment]
これ p いらんのとちゃう？

**Comment by h-east** [comment]
@mattn msg_attr()の第1引数に`keep_msg`を指定するということですか？
どの道msg_attr()抜けた時点で`keep_msg`はNULLになっているのでアドレス覚えておかないとfree()出来ずメモリリーク発生しちゃいます。

**Comment by mattn** [comment]
あー、中で弄ってるの... すんまそんすんまそん(コメント嫁、俺)

**Comment by machakann** [comment]
パッチあてて症状が改善するのを確認しました。しばらく使ってみましたが、手元では問題なさそうです。

**Comment by h-east** [comment]
posted to vim_dev
https://groups.google.com/d/msg/vim_dev/rEz6PruGXkU/hGKJOL7U29AJ

**Comment by mattn** [comment]
Patch 7.4.439 :+1:
https://groups.google.com/forum/#!topic/vim_dev/rHuILn_gb0E

**Comment by machakann** [comment]
ありがとうございました！
