### ISSUE TITLE
filetype indent on を設定し行挿入を行うと意図してないコマンドが実行される

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/issues#614]
.vimrc に以下のように設定します。

``` viml
autocmd!
set nocompatible
filetype indent on

nnoremap <silent> F :Sample<CR>
function! Sample()
  echomsg 'sample'
endfunction
command! -buffer -range=0 Sample call Sample()
```

html を作成し保存します

``` html
<div class="">
  <div class="overlay">test</div>
</div>
```

`:2<ESC>o`で 2 行目の div の下の行に新たに行挿入を行います。
`:messages` を実行すると、`sample` という文字が表示されます。
注: `o`, `O` で発生するようです。`i`, `a` など他の挿入モードに入る場合は実行されません。

少し挙動を追った所、
.vimrc に `filetype indent on` を定義すると `nnoremap <silent> F` にマッピングされた関数が実行されるようです。
`filetype plugin on` だと発生しません。

再現環境:
Ubuntu ソースコードをコンパイルしたもの Patch バージョンが 1-412
Mac MacVim-KaoriYa 20140805版で再現 Patch バージョンが 1-383
Mac MacVim-KaoriYa 20140514版(Patch バージョンが1-258)では再現しませんでした。

**Comment by machakann** [comment]
indent/html.vim の 500行目あたり(関数 s:FreshState() 内)の

``` vim
normal F<
```

が原因ではないでしょうか。

``` vim
normal! F<
```

でも再現するでしょうか？

**Comment by machakann** [comment]
> " History:
> " 2014 June    (v1.0) overhaul (Bram)
> " 2012 Oct 21  (v0.9) added support for shiftwidth()
> " 2011 Sep 09  (v0.8) added HTML5 tags (thx to J. Zuckerman)
> " 2008 Apr 28  (v0.6) revised customization
> " 2008 Mar 09  (v0.5) fixed 'indk' issue (thx to C.J. Robinson)

とあるので2014年6月のオーバーホールで入ったコードなのかもしれませんね。

**Comment by heavenshell** [comment]
@machakann 
おお! ありがとうございます!

```
normal! F<
```

> でも再現するでしょうか？

`!` を付けると再現しませんね。
とりあえず ~/.vim/indent/html.vim に `!` を当てたパッチを置いて回避する事にします。
ありがとうございます!

**Comment by machakann** [comment]
よく見ると901行目もnormalコマンドに!が抜けてますね。

以外とFキーにマッピングしているプラグインがあったりするみたいなので一応、vim_devに報告しておきました。でも初めての報告なので反映までに時間がかかるかもしれないです。

**Comment by k-takata** [comment]
見えるようになりました。
https://groups.google.com/d/topic/vim_dev/KadMbZp7oG0/discussion

**Comment by heavenshell** [comment]
@machakann @k-takata 
ありがとうございます!!!

**Comment by h-east** [comment]
rev. 6159:babc6a1d4c27 で取り込まれました。
https://github.com/vim-jp/vim/commit/fd2995bea16cbfe29503b25167c458f6e9a7ca23#diff-c5802b9fe6ca7e175ecf7f5f3bea690eR500

@machakann :+1:

**Comment by machakann** [comment]
早い！よかったです。

**Comment by heavenshell** [comment]
@machakann :+1:
