### ISSUE TITLE
プロセス置換ファイルオープン時のfileencodingsの振る舞いについて

### ISSUE THREAD

**Issue by tac-et** [vim-jp/issues#615]
初めまして。

bash/zshのプロセス置換を利用してファイルを開くとき、
fileencodingsの先頭の文字コードでiconvによる判定・変換エラーとなった場合？、
2個目以降に妥当な文字コードを指定していても再判定は行われず、空のバッファが開きます。
-   手順  
  
  ```
  $ export LANG=ja_JP.utf8
  $ vim -u NONE --cmd "set fileencodings=cp932,utf-8" <(echo "テスト")
  ```
-   結果  
  バッファに文字列が何も表示されない状態でvimが起動する(ファイル自体は`/dev/fd/`配下のものを開いている)。
-   期待する結果  
  utf-8で開かれ、バッファに`テスト`と表示される。  
-   期待する結果が得られる例  
  -   明示的にutf-8と指定  
    
    ```
    $ vim -u NONE --cmd "e ++enc=utf-8" --cmd "set fileencodings=cp932,utf-8" <(echo "テスト")
    ```
  -   =()での一時ファイルを使った場合(zsh限定)  
    
    ```
    $ vim -u NONE --cmd "set fileencodings=cp932,utf-8" =(echo "テスト")
    ```
  -   標準入力リダイレクト  
    
    ```
    $ echo "テスト" | vim -u NONE --cmd "set fileencodings=cp932,utf-8" -
    ```
-   確認環境  
  -   vim 7.4.415 +iconv +multi_byte
  -   CentOS6.5/bash, Mac OSX 10.9/zsh

プロセス置換の仕組み上、妥当な振る舞いのようには思うのですが、
直感的な挙動では無かったので、何か回避策など無いかと思い、チケットを起こしました。
(`$ vimdiff -R <(grep foo fileA) <(grep foo fileB)`のような使い方が出来なかったので…)

**Comment by mattn** [comment]
返事が遅れてすみません。

プロセス置換といいますか、標準入力からの読み取りですね。vim はファイルを読む時に変換しつつバッファに足しているのですが(メモリに持つと巨大なファイルで困るので)、標準入出力は seekable でないので、iconv で失敗した場合にファイルの先頭にシークオフセットを移動出来ないんです。
コードを読む限り、ここはあきらめる様にコーディングされている事から仕様と思われます。

一度テンポラリファイルに出力し、それを(引数で)読み込ませる様にすると、おそらく機能すると思います。

**Comment by k-takata** [comment]
> プロセス置換といいますか、標準入力からの読み取りですね。

例で挙げられているとおり、標準入力からは問題なく読めているようですが。

**Comment by mattn** [comment]
あーすみません。勘違いしてた。 `<(echo あああ)` だった。`/dev/fd/63` みたいな仮想デバイスファイルですね。
これが seekable じゃないのかな。

**Comment by mattn** [comment]
てかステータスラインに書いてあった。fifo/socket らしい。
![](http://go-gyazo.appspot.com/93215d1244262d36.png)

**Comment by k-takata** [comment]
標準入力はシーク出来ないことを前提に動いており、それ以外はシーク可能な前提で動いているもののプロセス置換ではシークが出来ないのでエラーになっているのでしょうかね？

**Comment by mattn** [comment]
pipe は seekable ではありません。`man lseek(2)` でエラーになると書いてあります。

**Comment by mattn** [comment]
@tac-et なので vim 単体では現状救いようが無いと思います。
fileencodings を正しい物に設定するか、コマンド側を

```
$  vim -u NONE <(echo "テスト" | nkf -w)
```

等とするのが良いと思います。

**Comment by k-takata** [comment]
シークできないはずの標準入力がちゃんと読めるのはどういう仕組みなんでしょう。
1回メモリに読み込んだデータに対して、コード変換をかけ直している？

**Comment by mattn** [comment]
どちらも同じなんですが、標準入力(`-` の場合)は途中で断念してないだけだと思います。
それは明確に `-` という指定があるから出来るんですが、今回の場合だとファイル名(でも実際はfifo/socket)を与えられているので seekable であるだろうと判断していて、失敗したからエラーという流れだと思います。

とここまで書きましたがファイル名が付与されているけど、実は seekable じゃない(errno = ESPIPE)て場合は stdin と同様のパスを通す的な対応を入れればもしかしたら行けるかもしれませんね。

**Comment by tac-et** [comment]
> てかステータスラインに書いてあった。fifo/socket らしい。

すみません。ステータスバーに出ていた情報についても記載しておくべきでした。

> fileencodings を正しい物に設定するか、コマンド側を
> 
> ``` sh
> $  vim -u NONE <(echo "テスト" | nkf -w)
> ```
> 
> 等とするのが良いと思います。

頂いた上記対策方法ですが、fileencodingsで、utf-8よりも先にcp932を指定しているのがこの現象の問題点なので、`nkf -x -W --oc=cp932`のような感じですかね(cp932にしてしまえば、1つ目で判定成功)。
utf-8を前に持ってきたいところではあるのですが、cp932はutf-8でもエラー無しで変換できてしまうことが多いので、fileencodingsはこの順にしています。

**Comment by mattn** [comment]
対応すべきかどうかの判断もありそうなのでひとまず報告するのがよさそうですね。

**Comment by mattn** [comment]
https://groups.google.com/d/msg/vim_dev/AF7gm1c5dW4/WsQLUiNBKtMJ

**Comment by k-takata** [comment]
これ、何とかしたいですね。

> シークできないはずの標準入力がちゃんと読めるのはどういう仕組みなんでしょう。
> 1回メモリに読み込んだデータに対して、コード変換をかけ直している？

どうやらそのようです。

バッファをオープンすると、buffer.c / open_buffer() が呼ばれます。標準入力の場合は、引数 `read_stdin` が 1 となっており、fileio.c / readfile() を 2 回呼んでいます。
1. `READ_NEW + READ_STDIN` フラグを指定し、標準入力からバッファにデータを読み込む。
2. `READ_BUFFER` フラグを指定し、バッファのデータを変換。

fifo/socket かどうかの判定は、mch_getperm(), S_ISFIFO(), S_ISSOCK() を使えばできそう。(あるいは、実際に seek できるか試すほうが良い？)

**Comment by k-takata** [comment]
作ってみた。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/3a72a57685527f1ad51e05f7d611beee12711610/read-fifo.patch?at=default

**Comment by k-takata** [comment]
autocommand の挙動が心配だが、面倒でテストしていない。

**Comment by k-takata** [comment]
BufReadPost が呼ばれていなかったので修正。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/6e10bcc010661194a2314a0cf1e5982f3167c667/read-fifo.patch?at=default

**Comment by k-takata** [comment]
投げた。
https://groups.google.com/d/topic/vim_dev/5Ec3b9avZzA/discussion

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/5Ec3b9avZzA/G9iuzHQKAQAJ

テストがほしいと言われてしまったが、どうやってテストすれば良いのか…？

**Comment by koron** [comment]
テスト内から別の vim を起動するテストを書く(既存のテストに似たようなのないかしら?)か、
そもそも Makefile レベルであたらしいテストを追加するかって感じに見えますね。

**Comment by koron** [comment]
> 既存のテストに似たようなのないかしら

ざっくり検索 (`system\(`) しても見当たらなかった (´・ω・`)

**Comment by k-takata** [comment]
Bramはtest49で同じようなことをやっていると言っていますが、簡単にできそうな気がしなかった…

**Comment by mattn** [comment]
v:progpath を使えば実行中の vim が取れるので `system([v.progname, '-c', '!echo あああ', '-c', 'qall!'])` みたいなので出来ませんかね。

**Comment by h-east** [comment]
patch 7.4.2178 でtestが追加された？
https://github.com/vim/vim/commit/3a938383396d4ab352bbb4d806938302debdae2c

**Comment by k-takata** [comment]
7.4.2189
https://groups.google.com/d/msg/vim_dev/-eTmozpc_ho/lUXuAUQMAgAJ
