### ISSUE TITLE
'set t_ut='時、'hi Normal ctermbg'の指定が右下半角1文字分効かない

### ISSUE THREAD

**Issue by tac-et** [vim-jp/issues#617]
タイトルの通りですが、`set t_ut=`を指定(tmux環境での背景描画の対策)していると、
`hi Normal ctermbg`の指定が右下半角1文字分だけ効かず、ターミナルの背景色そのままと
なります。
デフォルト値`set t_ut=y`の場合は再現しません。
-   手順  
  
  ``` sh
  $ vim -u NONE --cmd "hi Normal ctermbg=127" --cmd "set t_ut="
  ```
-   確認環境  
  -   vim-7.4.415/vim-7.3 Mac OSX 10.9/terminal
  -   vim-7.4.415(kaoriya版) Windows7/コマンドプロンプト

**Comment by ynkdir** [comment]
直接的な原因はこれだと思います。直せるかはわかりませんが。

``` c
screen.c:screen_char():
 7881     /* Outputting the last character on the screen may scrollup the screen.
 7882      * Don't to it!  Mark the character invalid (update it when scrolled up) */
 7883     if (row == screen_Rows - 1 && col == screen_Columns - 1
 7884 #ifdef FEAT_RIGHTLEFT
 7885             /* account for first command-line character in rightleft mode */
 7886             && !cmdmsg_rl
 7887 #endif
 7888        )
 7889     {
 7890         ScreenAttrs[off] = (sattr_T)-1;
 7891         return;
 7892     }
```

typo...

**Comment by ynkdir** [comment]
補足

"bce" (back color erace) - 端末をクリア ('t_cl' とか 't_ce' とか) したときに現在の背景色で塗り潰す機能。

tmux は "bce" をサポートしていない。

Vim では 't_ut' の設定で "bce" の使用を切り替える。

"bce" が使える端末であれば端末のクリア命令で画面をクリアできる。"bce" が使えないときでも Normal の背景色と端末の背景色が一緒であればクリア命令が使える。"bce" が使えなくて Normal の背景色が変更されているときは ' ' を出力することで自分で背景色で塗りつぶさないといけない。

画面の一番右下に文字を出力すると画面がスクロールしてしまう (かもしれない。そういう端末がある)。ので、Vim は画面の一番右下に文字を出力しないようにしている。

**Comment by ynkdir** [comment]
man terminfo 見たところ端末に `auto_right_margin (terminal has automatic margins)` この機能があるときは右端に文字を出力しても大丈夫な予感。

**Comment by saitoha** [comment]
auto_right_margin(am)はオートラップをすることを表わすので、逆に無い方が出しても大丈夫かなと思います。この場合見るべきはxenlというグリッチかなと思います。
man terminfoのxenlの説明がちょっと正しくないので、こちらを参考にしてください。
http://twilog.org/ttdoda/date-120624

**Comment by ynkdir** [comment]
なるほどー。ありがとうございます。

**Comment by saitoha** [comment]
これ結局どうしましょうか（直す必要があるかどうかの判断も含めて）。
xenlを見にいくようにする手もありますが、不適切なTERM設定などで判定をミスった時のインパクトが大きそうです。
文字挿入(ich)を使えばそういった状況を回避できそうですが、描画ロジックの分岐が増えます。

**Comment by ynkdir** [comment]
すみません私の手には余りそうなので放置してしまいました。
キレイに表示できるにこしたことはないと思うのでやる人がいればという感じですかね。
ただいろいろ簡単にはいかなそうなら直さなくてもいいかなと思います。
致命的な問題ではないと思うので。

**Comment by saitoha** [comment]
とりあえずxenl(xn)を導入する方針で書いてみました。
https://gist.github.com/saitoha/aa6485b2533639843508

ichを使う方法やオートラップ(am)を一時的に無効にする方法も模索しましたが、
真にポータブルというわけでもないので現状諦めています。

**Comment by ynkdir** [comment]
ありがとうございます！
とりあえず tmux,xterm,gnome-terminal で簡単に確認しましたがいい感じですね。

**Comment by ynkdir** [comment]
windows vista でも確認。
term.c の builtin_termcaps[] に t_xn の設定を入れないとかもですね。 (まあでも t_ut= て使わないと思うんですが windows では)

**Comment by saitoha** [comment]
@ynkdir "win32" のところに「{(int)KS_XN, "y"},」を足すとt_ut=でもうまくいく感じでしょうか。大丈夫なら有効にします。他のbuiltin capsについて、"vt320"はxenlであることが知られているので有効にしていいと思っています。
"amiga" や "beos-ansi"(beterm?) 、"ansi"、"os2ansi/pcansi"(nansi.sys?)、"iris-ansi"、"pcterm"(ansi.sys?)等は [ncursesのterminfo.src](http://invisible-island.net/ncurses/terminfo.src.html)上にbceの記載が無くvimのbuiltinの記載と異なっているのでterminfoを信用したくありません。xenlに関しては安全側に倒して何も書かない、という手で逃げようと思っています。
"xterm"も本来xenlですが実際は有象無象の端末の可能性があるので安全側に倒そうと思います。

**Comment by ynkdir** [comment]
> "win32" のところに「{(int)KS_XN, "y"},」を足すとt_ut=でもうまくいく感じでしょうか。

はい。それで大丈夫です。

**Comment by k-takata** [comment]
コメントのtypoも一緒に直しちゃったらいいんじゃないでしょうか。
Don't to it! -> Don't do it!

**Comment by saitoha** [comment]
Built-in capsの追加とtypoの修正をとりこみました。
しばらく色んな端末で試してみます。

**Comment by saitoha** [comment]
こんな感じで投稿しようと思いますが、英文の意味がちゃんと通ってますでしょうか。

タイトル：Improved background color support for non-bce terminals (GNU Screen/tmux)

Hi, lists

In non-bce terminals(such as GNU Screen/tmux), only the bottom-right cell in vim screen did not respect "ctermbg" setting.
We can reproduce it with the following command.

```
$ TERM=screen vim -u NONE --cmd "hi Normal ctermbg=4"
```

screenshot: http://zuse.jp/misc/ctermbg-on-non-bce-terminal.png

The reason why vim does so, is the fear of causing unexpected scroll by writing something to the bottom-right cell of the terminal screen.

I wrote a patch that adds support for well-known terminal capability "xn"(termcap) or "xenl"(terminfo).
This termcap flag gives vim enough confident to write something safely to the bottom-right cell and provides improved background color support.

This patch also fixes a typo in screen.c:

   Don't to it! -> Don't do it!

---

スレ違いですがvim_dev@vim.org宛てに送ったメールが反映されないことがあるのは私だけの症状でしょうか。
送信側で以下を確認しています。
- postfixのログでstatus=sentになっている
- 送信者ドメインのSPFを正しく設定している(試しにgmail宛てに送ると、googleがヘッダに「Received-SPF: pass」をつけて配送してくることを確認)。
- DNSBLで送信IP(49.212.4.59)がブラックリストに登録されていないことも確認
- 送信者アドレスはいつも投稿しているuser at zuse.jpで、一度Bram氏に連絡して明示的に許可してもらったこともある。

現状なおる見通しが立っていないので、どなたか代理で投稿頂けるとありがたいです。

**Comment by saitoha** [comment]
すみません、お騒がせしました。
vim_dev@vim.orgではなく、vim-dev@vim.orgに送らなければいけないのではないかと思い、やってみたらできました。
手元のvim で :h bugs したら vim_dev@vim.org に送れということになっていましたが、最新ではvim-dev@vim.orgに改訂されていました。

**Comment by h-east** [comment]
@saitoha ++

> 手元のvim で :h bugs したら vim_dev@vim.org に送れということになっていましたが、最新ではvim-dev@vim.orgに改訂されていました。

ほんとだ！しかも3日前(2015/01/25)！
https://github.com/vim-jp/vim/commit/03716ffa1ebe679e38c13128b5aca65df713b4c1#diff-0c035b0a8597a0a87f61ae3d128f81d9L138

私はいつもブラウザでgoogleグループにアクセスしてそこから投稿しているので気付かなかったです。
http://www.vim.org/community.php を [web.archive.orgで2002年まで遡っても](http://web.archive.org/web/20021007185208/http://www.vim.org/maillist.php) メールアドレスはvim-dev@vim.orgだったので `:h bugs`に記載してあるメールアドレスだけが間違ってたんですね。

**Comment by saitoha** [comment]
todo.txtに入りました。("tn" は "xn" の typo)

> Patch to add "tn" termcap feature, whether Vim can write in the last screen cell. (Hayaki Saito, 2015 Jan 28)

**Comment by k-takata** [comment]
7.4.627
https://groups.google.com/d/topic/vim_dev/CcKvKAkv9pM/discussion
