### ISSUE TITLE
setbufline()がない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#62]
getbufline()があるけどsetbufline()がありません。
kanaさんとかも試してたように思いますが、実装が難しいらしいです。

これができればバッファを他バッファから更新できるので[multitail](http://www.vanheusden.com/multitail/)(複数のファイルをtailfするプログラム)みたいなことがvimでできるようになります。
いろいろ応用効きそうです。

**Comment by koron** [comment]
難しい理由がようわからんですな。

curbufへの操作ができてotherbufへの操作ができないと解釈すれば、
curbufだけに行われる特別な処理があり、それらが隠蔽されているからか?

**Comment by thinca** [comment]
if_python ではできるようなので、実現自体はできそうな気がしますね。

**Comment by tyru** [comment]
あれ...検索してみたけどkanaさんそんなこと言ってない予感...
もしかしたら自分が脳内補完したかもしれません。すみませんすみません&gt;&lt;

検索したらmattnさんがvimスクリプトで実装したやつがでてきました。
https://gist.github.com/571731
そういえばlingrで何度か話題に上がったんですよね。
その時のだと予想。

getbufline()が組み込み関数としてあるのでできればsetbufline()も組み込み関数として欲しいです。

**Comment by koron** [comment]
ありだと思います。むしろない理由が不思議。

**Comment by tyru** [comment]
あとこれも見つけました。Real Vim Hacks Project懐しい。今vim-jpのおかげで実現できてるような気がしますね。
[Real Vim Hacks Project](http://vim-users.jp/real-vim-hacks-project/)

**Comment by Shougo** [comment]
はい。というか、Real Vim Hacks Projectから私もいくつかアイディアをこちらにポストしています。
ようやく、皆がReal Vim Hacksにやる気になってくれたということですね。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/64bdc92aed19ec9001dd
試しに書いてみました

**Comment by mattn** [comment]
ichizok++

On 2/28/15, ichizok notifications@github.com wrote:

> https://gist.github.com/ichizok/64bdc92aed19ec9001dd
> 試しに書いてみました
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/62#issuecomment-76518322

## 
- Yasuhiro Matsumoto

**Comment by h-east** [comment]
@ichizok 乙です。

Vimはバッファを変更する時は「そのバッファに移動して」編集するというポリシーがユーザ操作でもVim scriptでも貫かれているんじゃないでしたっけ？
違ったらゴメン。

そうだとすると今回のpatchはそのポリシーを崩す事になるのでいろいろ考えないといけないかもしれないです。
まず思いつくのは、指定バッファがカレントバッファ以外の場合に`BufEnter`イベント、`BufLeave`イベントは発生させなくてもいいかということですね。(場合によっては`WinEnter`、`WinLeave`、`TabEnter`、`TabLeave`も)
仮に今回のpatchで`BufEnter`、`BufLeave`等を発生させるようにしたとしてもイベント処理の内容によっては元のカレントウィンドウ&カレントバッファに戻って来れないかもしれない。

# 

イベントに焦点をあてて動作確認してみました。

``` bash
$ cat ~/62.vim
au BufEnter * echom "BufEnter" bufnr("")."(".bufname("").")"
au BufLeave * echom "BufLeave" bufnr("")."(".bufname("").")"
au WinEnter * echom "WinEnter" "tab:".tabpagenr() "win:".winnr() "buf:".bufnr("")."(".bufname("").")"
au WinLeave * echom "WinLeave" "tab:".tabpagenr() "win:".winnr() "buf:".bufnr("")."(".bufname("").")"
au TabEnter * echom "TabEnter" tabpagenr()
au TabLeave * echom "TabLeave" tabpagenr()
au CursorMoved * echom "CursorMoved"
au CursorMovedI * echom "CursorMovedI"
au TextChanged * echom "TextChanged"
au TextChangedI * echom "TextChangedI"
```

patch無しVim 7.4.648

``` bash
vim -N -u ~/62.vim -p aaa bbb
```

``` vim
:tabnext
:call setline(1, "BBB")
:tabnext

:messages
TabLeave 2
TabEnter 1
TabLeave 1
TabEnter 2
TabLeave 2
TabEnter 1
BufEnter 1(aaa)
TabLeave 1
TabEnter 2
TabLeave 2
TabEnter 1
CursorMoved                         ” ここまでは起動時に発生したイベント
BufLeave 1(aaa)
WinLeave tab:1 win:1 buf:1(aaa)
TabLeave 1
WinEnter tab:2 win:1 buf:2(bbb)
TabEnter 2
BufEnter 2(bbb)
CursorMoved
TextChanged
BufLeave 2(bbb)
WinLeave tab:2 win:1 buf:2(bbb)
TabLeave 2
WinEnter tab:1 win:1 buf:1(aaa)
TabEnter 1
BufEnter 1(aaa)
```

patchありVim 7.4.648

``` bash
vim -N -u ~/62.vim -p aaa bbb
```

``` vim
:call setbufline("bbb", 1, "BBB")

:messages
TabLeave 2
TabEnter 1
TabLeave 1
TabEnter 2
TabLeave 2
TabEnter 1
BufEnter 1(aaa)
TabLeave 1
TabEnter 2
TabLeave 2
TabEnter 1
CursorMoved                         ” ここまでは起動時に発生したイベント
CursorMoved
```

以下の点が気になりました。
- tab, window, bufferのイベントが発生していないけどOK？
- `CursorMoved`イベントが発生しているけどカレントバッファ(aaa)ではカーソルは移動していない。
- `TextChanged`イベントが発生していないけどOK？(たしかにカレントバッファ(aaa)は変更していないけど..)

Discussionしましょう。

**Comment by mattn** [comment]
それがですね、if_python では随分前から出来てたというアレでして…

On 3/1/15, h_east notifications@github.com wrote:

> @ichizok 乙です。
> 
> Vimはバッファを変更する時は「そのバッファに移動して」編集するというポリシーがユーザ操作でもVim scriptでも貫かれているんじゃないでしたっけ？
> 違ったらゴメン。
> 
> そうだとすると今回のpatchはそのポリシーを崩す事になるのでいろいろ考えないといけないかもしれないです。
> まず思いつくのは、指定バッファがカレントバッファ以外の場合に`BufEnter`イベント、`BufLeave`イベントは発生させなくてもいいかということですね。(場合によっては`WinEnter`、`WinLeave`、`TabEnter`、`TabLeave`も)
> 仮に今回のpatchで`BufEnter`、`BufLeave`等を発生させるようにしたとしてもイベント処理の内容によっては元のカレントウィンドウ&カレントバッファに戻って来れないかもしれない。
> 
> # 
> 
> イベントに焦点をあてて動作確認してみました。
> 
> ``` bash
> $ cat ~/62.vim
> au BufEnter * echom "BufEnter" bufnr("")."(".bufname("").")"
> au BufLeave * echom "BufLeave" bufnr("")."(".bufname("").")"
> au WinEnter * echom "WinEnter" "tab:".tabpagenr() "win:".winnr()
> "buf:".bufnr("")."(".bufname("").")"
> au WinLeave * echom "WinLeave" "tab:".tabpagenr() "win:".winnr()
> "buf:".bufnr("")."(".bufname("").")"
> au TabEnter * echom "TabEnter" tabpagenr()
> au TabLeave * echom "TabLeave" tabpagenr()
> au CursorMoved * echom "CursorMoved"
> au CursorMovedI * echom "CursorMovedI"
> au TextChanged * echom "TextChanged"
> au TextChangedI * echom "TextChangedI"
> ```
> 
> patch無しVim 7.4.648
> 
> ``` bash
> vim -N -u ~/62.vim -p aaa bbb
> ```
> 
> ``` vim
> :tabnext
> :call setline(1, "BBB")
> :tabnext
> 
> :messages
> TabLeave 2
> TabEnter 1
> TabLeave 1
> TabEnter 2
> TabLeave 2
> TabEnter 1
> BufEnter 1(aaa)
> TabLeave 1
> TabEnter 2
> TabLeave 2
> TabEnter 1
> CursorMoved                         ” ここまでは起動時に発生したイベント
> BufLeave 1(aaa)
> WinLeave tab:1 win:1 buf:1(aaa)
> TabLeave 1
> WinEnter tab:2 win:1 buf:2(bbb)
> TabEnter 2
> BufEnter 2(bbb)
> CursorMoved
> TextChanged
> BufLeave 2(bbb)
> WinLeave tab:2 win:1 buf:2(bbb)
> TabLeave 2
> WinEnter tab:1 win:1 buf:1(aaa)
> TabEnter 1
> BufEnter 1(aaa)
> ```
> 
> patchありVim 7.4.648
> 
> ``` bash
> vim -N -u ~/62.vim -p aaa bbb
> ```
> 
> ``` vim
> :call setbufline("bbb", 1, "BBB")
> 
> :messages
> TabLeave 2
> TabEnter 1
> TabLeave 1
> TabEnter 2
> TabLeave 2
> TabEnter 1
> BufEnter 1(aaa)
> TabLeave 1
> TabEnter 2
> TabLeave 2
> TabEnter 1
> CursorMoved                         ” ここまでは起動時に発生したイベント
> CursorMoved
> ```
> 
> 以下の点が気になりました。
> - tab, window, bufferのイベントが発生していないけどOK？
> - `CursorMoved`イベントが発生しているけどカレントバッファ(aaa)ではカーソルは移動していない。
> - `TextChanged`イベントが発生していないけどOK？(たしかにカレントバッファ(aaa)は変更していないけど..)
> 
> Discussionしましょう。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/62#issuecomment-76539171

## 
- Yasuhiro Matsumoto

**Comment by Shougo** [comment]
setbufline()実行時のイベントに関しては、if_pythonやif_luaでも同じことができるので、そちらに挙動を合わせるのはいかがでしょう。

**Comment by ichizok** [comment]
h_east さんのスクリプトで試した限りでは、if_python や if_lua の別バッファ書き込みも同じ動作になっているようですね (CursorMoved のみ発生)

**Comment by h-east** [comment]
@mattn 

> それがですね、if_python では随分前から出来てたというアレでして…

if_pythonやif_luaで(TextChangedイベント発生なしに)別バッファ変更が可能なのcheatっぽい。
その仕様をそのままVim本体に持っていってもBram氏は受け入れないと思う。
バッファ変更とイベントの関係のポリシーをきっちり決めないとマズいんじゃない？

今は`TextChanged`イベントはカレントバッファ専用になっているのでBufferのEnter/Leaveイベントを発生させないと辻褄が合わないですよね。

私は、「別バッファ変更時はTextChangedイベント発生させなくていい」という方向はないと思ってます。
これ許したら無法地帯になってまう。ﾑﾎｰ!

@ichizok 検証Thanksです。

**Comment by mattn** [comment]
> if_pythonやif_luaで(TextChangedイベント発生なしに)別バッファ変更が可能なのcheatっぽい。
> その仕様をそのままVim本体に持っていってもBram氏は受け入れないと思う。
> バッファ変更とイベントの関係のポリシーをきっちり決めないとマズいんじゃない？

ポリシー決めないといけないのは同意です。ただ既に動いちゃってる物を使えなくするのはBramは間違いなくやらないのでVim scriptからだけ使えないという理由が拒絶されるかは分からないですね。

**Comment by h-east** [comment]
上の私の検証で

``` vim
:tabnext
:call setline(1, "BBB")
:tabnext
```

と

``` vim
:call setbufline("bbb", 1, "BBB")
```

で同じイベント発生状況になればOKですよね？(もちろん`setbufline`側を前者に合わせる)

**Comment by h-east** [comment]
2006/10のvim_devのスレッド発見。patch作られてた。

missing setbufline()? 
(1) http://vim.1045645.n5.nabble.com/missing-setbufline-td1155970.html
(2) http://vim.1045645.n5.nabble.com/Re-missing-setbufline-td1200781.html
※(2)だけ読めば分かると思う。

marks、jumplist、再描画等いろいろな影響が起きることを懸念しているみたい。

> > The setbufline() implementation is similar to the one used in
> > if_perl.xs (Set) , if_python.c (SetBufferLine), if_ruby.c (set_buffer_line)
> > if_mzsch.c (set_buffer_line_list) and if_tcl.c (BUF_SET) interface
> > files. These problems should also be seen with those
> > interfaces also. 

に対してBram氏はこんな事を言っている:satisfied:

> There also have been bugs in this implementation.  I don't know if there are any others, it does not appear to be used much. 

そしてこれ

> OK, so you can.  But this doesn't mean it actually works properly,
> without any undesired side effects.  This code is only included
> optionally.  For the main Vim code I'm more careful. 

たぶんsetbufline()が入ることはないっぽい。

私も↓は守ったほうが良いと思う。

> Vimはバッファを変更する時は「そのバッファに移動して」編集するというポリシー

**Comment by mattn** [comment]
9年も前か。情勢変わってるしなー。やるだけやってみて良いと思いますよ。僕は。

**Comment by h-east** [comment]
こちらはvim_dev主要メンバの興味深いdiscuss in 2010/10

How to append lines to background buffer ?
https://groups.google.com/d/msg/vim_dev/td1mNkW4q3I/mNiT8gQPd2QJ

**Comment by mattn** [comment]
https://groups.google.com/forum/#!msg/vim_dev/SJ69apKf25A/T6DupXQhEwAJ

これが動いてしまった以上、もう setbufline が無い理由にならなくなってしまった気がします。

どうでしょう push してみます？

**Comment by koron** [comment]
:+1:

**Comment by thinca** [comment]
:+1:

**Comment by mattn** [comment]
パッチを今風に更新してドキュメントとテスト足しました。↑のコメントで報告済み。

https://gist.github.com/mattn/23c1f50999084992ca98

**Comment by tyru** [comment]
:+1:

**Comment by ichizok** [comment]
テスト入ってないような...
あと、関数が K&R style のままですね（私がパッチアップデートしてないせいですが

**Comment by mattn** [comment]
あれ。たぶん違うのを出してしまってると思います。月曜に見直します。

**Comment by mattn** [comment]
修正しました。 https://gist.github.com/mattn/23c1f50999084992ca98

**Comment by k-takata** [comment]
ずいぶん前にtodo入りしているのでクローズします。

> Patch to add setbufline(). (email from Yasuhiro Matsumoto, patch by Ozaki
> Kiichi, 2016 Feb 28)
> Update Mar 8: https://gist.github.com/mattn/23c1f50999084992ca98
> Update Mar 13: https://gist.github.com/mattn/23c1f50999084992ca98

**Comment by h-east** [comment]
おっと！(自分的には)禁断の`setbufline()`が[8.0.1039](https://github.com/vim/vim/commit/b31cf2bb0be95d106bd8eef93cc07550591c1d0d)で入ってしまった。
