### ISSUE TITLE
cygwin/msys/Linux で enc=cp932 ft=diff とするとエラー

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/issues#620]
syntax/diff.vim の中にエンコード出来ない文字列が含まれており、エラーとなるようです。

```
/usr/share/vim/vim74/syntax/diff.vim の処理中にエラーが検出されました:
行  128:
E401: パターン区切りが見つかりません: "^\\ ????????????????????????????????????? ???? ???????
E475: 無効な引数です: diffNoEOL^I"^\\ ????????????????????????????????????? ???? ???????
```

但し Win32 版 (CUI 版含む) では発生しませんでした。
私は cygwin/msys を使用していて発見しましたが、Linux 上での再現も伺っています。
## 再現手順
- cygwin/msys: 以下で vim を起動。
  `vim -u NONE -N -c "set enc=cp932" -c "syntax on" -c "set ft=diff"`
- Win32 版 (CUI 版含む): 再現せず。

Linux 上で `enc=cp932` の Vim を使うことはそうないですが、cygwin については windows のネイティブエンコードが cp932 である以上まだ遭遇しうる問題だと思います。

syntax/diff.vim が utf-8 エンコード前提で作成されているのではないかということと、なぜ Win32 版では発生しないのかは不明です。

**Comment by mattn** [comment]
iconv で失敗したら `?` にするっての、かなり危険すな。これを辞めないと根本解決しない気がする。

**Comment by mattn** [comment]
こういうのどうだろ。

https://gist.github.com/mattn/d9432fbd6eadca91e1d6

**Comment by 0xBADDCAFE** [comment]
なるほど、思いつきませんでした。問題無さそうです。

163 行目と 286 行目に `endif` が抜けているようです。
追加した上で問題ありませんでした。

**Comment by mattn** [comment]
あとは $LANG でいいのかって問題もありますね。LC_MESSAGES を使ってメッセージだけ変えてる場合とかも考慮が必要かもしれないです。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/7Nnb8GraZ1w

**Comment by k-takata** [comment]
Win32版で発生しないのは何でなんですかね？発生しても良さそうな気がしますが。

**Comment by mattn** [comment]
Win32 版の場合は utf-8 to cp932 は MultiByteToWideChar/WideCharToMultiByte でやってるからじゃないですかね。

**Comment by k-takata** [comment]
あー、なるほど。

**Comment by 0xBADDCAFE** [comment]
ありがとうございま寿司 :sushi:

**Comment by k-takata** [comment]
diff.vimの128行目の末尾2byteを見ると、0x97, 0x22 (") となっていて、これがSJISの1文字として扱われてしまってエラーになっているように見えます。ただ、本来 0x22 はSJISの2byte目にはならないので、そこが問題な気もします。

**Comment by k-takata** [comment]
todo入り

> Patch to avoid problems with encoding conversion with diff.vim.
> (Yasuhiro Matsumoto, 2014 Sep 1.
> Depends on current language, language of file can be different.

**Comment by k-takata** [comment]
Bramからのコメント

> This makes the highlighting depend on the current language.  However,
> the diff files I edit may be in any language, not necessarily matching
> the current language.
> 
> Can we think of another way to avoid the problems you experienced?
> Perhaps only skip the lines that have characters that don't work in the
> current encoding? 

現在の言語に依存しているが、ファイルの言語は異なる場合があるので別の方法がないかということのようです。

**Comment by k-takata** [comment]
ひっそりと todo.txt から削除されていました。
https://github.com/vim-jp/vim/commit/65ef1269bd3aecb81919843ee36668db9bff06bd#diff-38d7929bd26d74d92ceddf984bbfc8dbL66

本質的な問題は、[上に](https://github.com/vim-jp/issues/issues/620#issuecomment-54109098)書いたとおり、不正なバイト列を間違ってSJIS 1文字として扱っていることにあると思います。（iconvの変換失敗ではなく。）

**Comment by mattn** [comment]
> ひっそりと todo.txt から削除されていました。

Bram から私の方に直メールが来てまして、そこで「これは Vim 本体の問題じゃないよ」と説明したからですね。

> 本質的な問題は、上に書いたとおり、不正なバイト列を間違ってSJIS 1文字として扱っていることにあると思います。（iconvの変換失敗ではなく。）

はい。なので if によるスキップしか無いのです。

**Comment by k-takata** [comment]
いや、今はSJISの先頭バイトのみを見て1バイト文字か2バイト文字かを判定しているのでしょうが、ちゃんと2バイト目も見て、0x97, 0x22 を 1バイトの断片 + 1バイト文字と判定するように本体を直すのもありかなと。どの程度の修正量になるのか分かりませんが。

**Comment by k-takata** [comment]
修正案を2つ思いついたので投げてみました。
https://groups.google.com/d/msg/vim_dev/7Nnb8GraZ1w/2prKSHJzmIIJ

**Comment by k-takata** [comment]
diff.vimの128行目の末尾の `"` がマルチバイト文字の一部として扱われてしまい、`"`が認識されないのが問題なので、
1. 128行目の末尾に `| "` を付け足す。
2. 128行目のパターンの末尾に、空の正規表現 `\%(\)` を足す。

のどちらかで、エラーが回避できます。

**Comment by mattn** [comment]
それかバイナリ表記 `\xXX` するってのもアリかもですね。

**Comment by k-takata** [comment]
さすがに案1はトリッキーすぎてBramには伝わらなかったか。
https://groups.google.com/d/msg/vim_dev/7Nnb8GraZ1w/b88rueNcLDgJ
案3. パターン末尾に `.\?` を足す。

よくよく挙動を確認してみると、diff.vim には、`scriptencoding utf-8`が書かれており、Cygwin/Win32 ともに `enc=cp932` に設定した状態で `:syn` でシンタックスのリストを表示すると、`match /^.* のみに存在: .*/` のように日本語のルールも文字化けせずに登録されています。
しかし、utf-8 から cp932 に変換が行われているなら E401 が出るのは変です。変換せずに読み込んで E401 のエラーが出た後で、もう一度 utf-8 から cp932 に変換して読み直しているのでしょうか？

**Comment by k-takata** [comment]
7.4.516の後のコミットで直りました。
https://github.com/vim-jp/vim/commit/e6c2b15a81c9c803b279416f7a9947d46fdc58f8#diff-7
結局、最後の文字を `.` に置き換える形になりました。
