### ISSUE TITLE
'cedit' を <C-c> に設定すると Vim が固まる

### ISSUE THREAD

**Issue by rhysd** [vim-jp/issues#621]
vim-easymotion の [issue #177](https://github.com/Lokaltog/vim-easymotion/issues/177) で発見されたバグです．
@osyo-manga さんに協力してもらって本体のバグっぽいということになったのでこちらに報告します．
## 問題

`cedit` を `<C-c>` にしていると Vim の挙動がおかしくなる場合がある．
## 手順1
1. `vim -u NONE -N` で起動
2. `:set cedit=<C-c>`
3. `:normal! :`

コマンドラインがチカチカ点滅し，CPU利用率が100%になり，Vim が固まります．SIGKILL でないと殺せなくなります．
## 手順2
1. `vim -u NONE -N` で Vim を起動
2. `:set cedit=<C-c>`
3. `:echo input('')`
4. `<C-c>` を入力

結果として，Vim の挙動がおかしくなります．ウィンドウの端に`@`が挿入されたり，コマンドラインウィンドウが2つになったり，謎のリストが出たりします．
現象も決定的でなく，ウィンドウの端に`@`が出るだけで何も他には起きなかったり，再現回数は少ないですが SEGV した場合もありました．
手順1の場合と原因が同じかはわかっていません．

再現時の一例です：
![](https://dl.dropboxusercontent.com/u/2753138/bug.png)
## 再現環境
- @rhysd
  - OS X 10.9.4
  - Vim 7.4 p383
  - CUI
- @osyo-manga
  - Ubuntu 13.10
  - Vim 7.4 p415
  - GUI

**Comment by mattn** [comment]
``` diff
diff -r aeafe78fc869 src/ex_getln.c
--- a/src/ex_getln.c    Fri Aug 22 13:13:28 2014 +0200
+++ b/src/ex_getln.c    Fri Aug 29 11:15:54 2014 +0900
@@ -757,7 +757,7 @@
    }

 #ifdef FEAT_CMDWIN
-   if (c == cedit_key || c == K_CMDWIN)
+   if (KeyTyped && (c == cedit_key || c == K_CMDWIN))
    {
        /*
         * Open a window to edit the command line (and history).
```

これで直りますか？

**Comment by rhysd** [comment]
@mattn 
ありがとうございます．
試してみたところ，手順2のほうは固まらなくなりましたが，コマンドラインウィンドウを開くマッピングを

``` vim
set cedit=<C-c>
noremap ; :<C-c>i
```

と定義したところ，インサートモードに入るようになってしまいました．（`KeyTyped` かどうかで見るとマッピング時が考慮されていない？）

また，

``` vim
noremap ; q:i
```

のように定義すると，`;` 入力時にコマンドラインウィンドウでなくコマンドラインが開き， `<t \<fd>T>i` が入力されるようになってしまいました．

**Comment by mattn** [comment]
``` diff
diff -r aeafe78fc869 src/ex_getln.c
--- a/src/ex_getln.c    Fri Aug 22 13:13:28 2014 +0200
+++ b/src/ex_getln.c    Fri Aug 29 20:46:40 2014 +0900
@@ -762,8 +762,11 @@
        /*
         * Open a window to edit the command line (and history).
         */
-       c = ex_window();
-       some_key_typed = TRUE;
+       if (ex_normal_busy == 0)
+       {
+       c = ex_window();
+       some_key_typed = TRUE;
+       }
    }
 # ifdef FEAT_DIGRAPHS
    else
```

たぶんこれでやりたいであろう動作になると思います。

**Comment by rhysd** [comment]
@mattn 

ありがとうございます．
今週末回線があまり安定しない場所にいるため，来週明けに試してみます．

**Comment by rhysd** [comment]
@mattn 

> たぶんこれでやりたいであろう動作になると思います。

遅くなってすみません．
手順1 のほうについて期待動作になっていることを確認しました！
ありがとうございます．
ついでに `make test` もパスすることを確認しました．

**Comment by mattn** [comment]
あ、なんか変ですね。

**Comment by mattn** [comment]
手順２の事気にしてませんでした。

**Comment by mattn** [comment]
手順2に対応しました。

https://gist.github.com/mattn/2511755e15510b7b0b0f

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/Ptahp8bNkhM

**Comment by rhysd** [comment]
手順1も手順2も期待動作になっている&テストが通ることも確認しました…！
ありがとうございます！

**Comment by mattn** [comment]
Patch 7.4.441
https://groups.google.com/forum/#!topic/vim_dev/lrNHz8khMkE
