### ISSUE TITLE
gettabvar(1, '') はスコープの辞書を返して欲しい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#622]
`getbufvar()` と `gettabwinvar()` は、`{varname}` に空文字列を渡すと、対象のスコープの辞書を取得できますが、`gettabvar()` だけはなぜかできません。
一貫性がないと混乱するし、何より不便なので、`gettabvar()` も同じ挙動だと嬉しいです。

**Comment by koron** [comment]
おそらくここで第2引数に0を渡しているのが原因。

https://github.com/vim-jp/vim/blob/master/src/eval.c#L12087

``` c
    /* look up the variable */
    v = find_var_in_ht(&tp->tp_vars->dv_hashtab, 0, varname, FALSE);
    if (v != NULL)
```

`f_getbufvar()` ではこうなってる。

``` c
        /* Let getbufvar({nr}, "") return the "b:" dictionary. */
        v = find_var_in_ht(&curbuf->b_vars->dv_hashtab,
                             'b', varname, FALSE);
        if (v != NULL)
```

だから代わりに `'t'` を渡したらうまくいくかもしれない。

**Comment by koron** [comment]
ドキュメントの追記も必要ね。

**Comment by thinca** [comment]
> だから代わりに 't' を渡したらうまくいくかもしれない。

実を言うとこれ試してみたんですが、なぜかうまく行かなかったんですよね…。空文字列が返ってきちゃう。
あと `find_var_in_ht()` の中身をチラ見したんですが、常にカレントのタブの値を返してるっぽいですね。バッファやウィンドウもそうだけど、呼び出し元で一時的にバッファやウィンドウを移動している模様。

**Comment by koron** [comment]
ああ、じゃあ `find_var_int_ht()` にフラグの種類を追加して、実装もするってかんじですね。

**Comment by koron** [comment]
あとこれ。

> 実を言うとこれ試してみたんですが

時系列的にどうなっているか不明だけど、
起票時に試し済みなら、その内容はissueに書いておいたほうが良いです。

**Comment by thinca** [comment]
確かに。次から気をつけます。

**Comment by koron** [comment]
> `find_var_int_ht()` にフラグの種類を追加して、実装もする

安全のためには、呼び出し側の `f_gettabvar()` のほうでやってパッチだしたほうが良さ気。

**Comment by mattn** [comment]
https://gist.github.com/mattn/c2c8cb10f08aaf68d657

これでうまくいったよ？テスト中に tabnr が変わっちゃったんじゃない？

**Comment by thinca** [comment]
あーすいません。変更したコードと全く別の場所にあるソースをビルドしていました…そりゃ変わらないわけだ…。
ただ、やはり常にカレントタブの値が返ってきちゃってますね。指定したタブの値が返ってくるように色々やらないとダメそうです。

**Comment by mattn** [comment]
やりかけたので引き取りますね

On 8/30/14, thinca notifications@github.com wrote:

> あーすいません。変更したコードと全く別の場所にあるソースをビルドしていました…そりゃ変わらないわけだ…。
> ただ、やはり常にカレントタブの値が返ってきちゃってますね。指定したタブの値が返ってくるように色々やらないとダメそうです。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/622#issuecomment-53951557

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
https://gist.github.com/mattn/f606cccc62d2171ad6d1

テストがいるかな。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/MPsdl78a0ys

**Comment by mattn** [comment]
バグだと思うので `new features` から `bug` にしました。

**Comment by thinca** [comment]
:+1:
ところで、`b:` と `w:` の `find_var_in_ht()` の呼び出しでは、直前の行に

``` c
/* Let getbufvar({nr}, "") return the "b:" dictionary. */
```

みたいなコメントがあるので、今回の場所にもあった方が良さそう?

**Comment by mattn** [comment]
done

**Comment by mattn** [comment]
Patch 7.4.434
https://groups.google.com/forum/#!topic/vim_dev/i5pvK9KoHwc

Patch 7.4.442
https://groups.google.com/forum/#!topic/vim_dev/zXk52RKBQJ8
