### ISSUE TITLE
E888 が重複している

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#624]
E888 が `/\zs` と `/\ze` で重複している。
そのため helptags すると怒られる。

**Comment by koron** [comment]
https://groups.google.com/d/msg/vim_dev/m4YGi3s2UQ8/TpSUeDosqWQJ

**Comment by koron** [comment]
+kaoriya ではパッチで一時的に E888 を片方消した。

https://bitbucket.org/koron/vim-kaoriya-patches/src/340434b3c4f53ef88d3e7bda9b1eec9bbadb03c4/GH624-remove-duplicated-e888.diff?at=default

**Comment by k-takata** [comment]
7.4.441 直後のコミットで直りました。
https://github.com/vim-jp/vim/commit/007a19c3ac59e8e0c171995bd2f695036293e4a2#diff-2fe866632f9a6aa5e9f6196649a07e68R837
