### ISSUE TITLE
Windows で encoding=utf-8 時にワイルドカード展開が iconv 変換されていない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#625]
○: 「あ.txt」が無い場合に`vim あ.txt`とすると新規ファイル扱い
○: 「あ.txt」が無い場合に`vim あ*`とすると「あ*」というバッファ名で新規ファイル扱い
×: 「あ.txt」がある場合に`vim あ*`とすると「<82><a0>.txt」というバッファ名で新規ファイル扱い

正しくは「あ.txt」というバッファ名で既存ファイル扱い

**Comment by mattn** [comment]
``` diff
diff -r dde8ff798ed9 src/os_win32.c
--- a/src/os_win32.c    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/os_win32.c    Mon Sep 01 22:29:16 2014 +0900
@@ -6568,7 +6568,31 @@
        || used_file_indexes == NULL
        || used_file_count == 0
        || used_alist_count != GARGCOUNT)
+    {
+   // Only pass on non-GUI vim. non-GUI vim has already expanded filenames.
+   // So it don't need to rewind files. Just convert filenames.
+   if (GARGCOUNT > 0)
+   {
+       int i;
+       char_u **new_arg_files;
+       new_arg_files = (char_u **)alloc((unsigned)(sizeof(char_u *) * GARGCOUNT));
+       if (new_arg_files == NULL)
+       return;
+       for (i = 0; i < GARGCOUNT; ++i)
+       {
+       char_u *p = GARGLIST[i].ae_fname;
+       char_u *pp;
+       int len;
+       acp_to_enc(p, (int)STRLEN(p), &pp, &len);
+       new_arg_files[i] = pp;
+
+       buf_set_name(GARGLIST[i].ae_fnum, pp);
+       }
+       alist_set(&global_alist, GARGCOUNT, new_arg_files,
+                          TRUE, NULL, NULL);
+   }
    return;
+    }

     /* Remember the buffer numbers for the arguments. */
     fnum_list = (int *)alloc((int)sizeof(int) * GARGCOUNT);
```

これ、GUI の場合は `:rewind` してるんだけどこれ意味あるんだっけ？あるなら CUI 版もしないといけない。

**Comment by mattn** [comment]
あー、そうか。GUI の場合は encoding の違いによってワイルドカードで展開されるファイル名が異なるはずだろうから expand しなおしてるのか。CUI の場合は既に展開済みだから args とバッファ名が変換されれば良いと思うんだけど、違う？

**Comment by mattn** [comment]
あ、まずいな。もう1回 encoding 変更したら化けるだろなこれ。

**Comment by mattn** [comment]
こうだ。

``` diff
diff -r dde8ff798ed9 src/main.c
--- a/src/main.c    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/main.c    Tue Sep 02 09:52:14 2014 +0900
@@ -276,6 +276,10 @@
     TIME_MSG("locale set");
 #endif

+#ifdef defined(FEAT_WINDOWS) && defined(FEAT_MBYTE)
+    handle_cmd_argsW(argc, argv);
+#endif
+
 #ifdef FEAT_GUI
     gui.dofork = TRUE;         /* default is to use fork() */
 #endif
@@ -1497,6 +1501,10 @@
    garbage_collect();
 #endif

+#ifdef defined(FEAT_WINDOWS) && defined(FEAT_MBYTE)
+    free_cmd_argsW();
+#endif
+
     mch_exit(exitval);
 }

diff -r dde8ff798ed9 src/os_win32.c
--- a/src/os_win32.c    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/os_win32.c    Tue Sep 02 09:52:14 2014 +0900
@@ -6449,6 +6449,28 @@
 static int used_file_diff_mode = FALSE;  /* file name was with diff mode */
 static int used_alist_count = 0;

+    void
+handle_cmd_argsW(int argc, char* argv[])
+{
+    nArgsW = argc;
+    ArglistW = malloc(nArgsW * sizeof(WCHAR *));
+    if (ArglistW != NULL)
+    {
+   int i;
+   for (i = 0; i < argc; ++i)
+   {
+       LPWSTR  widestr;
+       int     outlen;
+       MultiByteToWideChar_alloc(GetACP(), 0,
+           (LPCSTR)argv[i], STRLEN(argv[i]), &widestr, &outlen);
+       ArglistW[i] = widestr;
+   }
+    }
+    if (argc > 0)
+   used_file_indexes = malloc(argc * sizeof(int));
+    global_argc = argc;
+    global_argv = argv;
+}

 /*
  * Get the command line arguments.  Unicode version.
diff -r dde8ff798ed9 src/proto/os_win32.pro
--- a/src/proto/os_win32.pro    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/proto/os_win32.pro    Tue Sep 02 09:52:14 2014 +0900
@@ -51,6 +51,7 @@
 int mch_copy_file_attribute __ARGS((char_u *from, char_u *to));
 int myresetstkoflw __ARGS((void));
 int get_cmd_argsW __ARGS((char ***argvp));
+void handle_cmd_argsW __ARGS((int argc, char* argv[]));
 void free_cmd_argsW __ARGS((void));
 void used_file_arg __ARGS((char *name, int literal, int full_path, int diff_mode));
 void set_alist_count __ARGS((void));
```

**Comment by k-takata** [comment]
Vim, GVim 7.4.430 ともに再現しないです。

**Comment by mattn** [comment]
encoding=utf-8 ですか？ GUI 版は再現しないはずです。

**Comment by k-takata** [comment]
yes

.vimrc の先頭で set enc=utf-8 しています。

**Comment by mattn** [comment]
引数リストを変換していないので vimrc で encoding=utf-8 を設定すると fix_arg_enc が実行されるんですが CUI 版はスルーなので `:args` とすると化けるはずなんですが。

**Comment by mattn** [comment]
最少の再現手順

```
C:\>vim -u NONE -N あ
:args
[あ]
:set encoding=utf-8
:args
[<82><a0>]
```

**Comment by mattn** [comment]
パッチがちょっとマズってる。

**Comment by k-takata** [comment]
再現しました。一方、`-c`で enc=utf-8 にした場合は化けてないです。

```
C:\>vim -u NONE -N あ -c "set enc=utf-8 tenc=cp932"
:args
[あ]
```

ただし、swapファイルが残ってしまう謎な現象が発生。

**Comment by mattn** [comment]
starting という変数を使って起動中かどうか見て fix_arg_enc を呼ぶかどうか見てるからだと思います。

**Comment by k-takata** [comment]
> ただし、swapファイルが残ってしまう謎な現象が発生。

`-c "set enc=utf-8"` だとswapファイルが残るが、`--cmd "set enc=utf-8"` だと問題なし。Vim/GVim共通。

**Comment by mattn** [comment]
あー、FEAT_WINDOWS を御用してる

**Comment by mattn** [comment]
別問題っぽいですね > swap が残る

**Comment by mattn** [comment]
``` diff
diff -r dde8ff798ed9 src/main.c
--- a/src/main.c    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/main.c    Tue Sep 02 10:26:20 2014 +0900
@@ -280,6 +280,10 @@
     gui.dofork = TRUE;         /* default is to use fork() */
 #endif

+#if defined(WIN32) && defined(FEAT_MBYTE)
+    handle_cmd_argsW(argc, argv);
+#endif
+
     /*
      * Do a first scan of the arguments in "argv[]":
      *   -display or --display
@@ -1497,6 +1501,10 @@
    garbage_collect();
 #endif

+#if defined(WIN32) && defined(FEAT_MBYTE)
+    free_cmd_argsW();
+#endif
+
     mch_exit(exitval);
 }

diff -r dde8ff798ed9 src/os_win32.c
--- a/src/os_win32.c    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/os_win32.c    Tue Sep 02 10:26:20 2014 +0900
@@ -6449,6 +6449,28 @@
 static int used_file_diff_mode = FALSE;  /* file name was with diff mode */
 static int used_alist_count = 0;

+    void
+handle_cmd_argsW(int argc, char* argv[])
+{
+    nArgsW = argc;
+    ArglistW = GlobalAlloc(GMEM_FIXED, nArgsW * sizeof(WCHAR *));
+    if (ArglistW != NULL)
+    {
+   int i;
+   for (i = 0; i < argc; ++i)
+   {
+       LPWSTR  widestr;
+       int     outlen;
+       MultiByteToWideChar_alloc(GetACP(), 0,
+           (LPCSTR)argv[i], STRLEN(argv[i]), &widestr, &outlen);
+       ArglistW[i] = widestr;
+   }
+    }
+    if (argc > 0)
+   used_file_indexes = malloc(argc * sizeof(int));
+    global_argc = argc;
+    global_argv = argv;
+}

 /*
  * Get the command line arguments.  Unicode version.
diff -r dde8ff798ed9 src/proto/os_win32.pro
--- a/src/proto/os_win32.pro    Sat Aug 30 18:10:19 2014 +0200
+++ b/src/proto/os_win32.pro    Tue Sep 02 10:26:20 2014 +0900
@@ -51,6 +51,7 @@
 int mch_copy_file_attribute __ARGS((char_u *from, char_u *to));
 int myresetstkoflw __ARGS((void));
 int get_cmd_argsW __ARGS((char ***argvp));
+void handle_cmd_argsW __ARGS((int argc, char* argv[]));
 void free_cmd_argsW __ARGS((void));
 void used_file_arg __ARGS((char *name, int literal, int full_path, int diff_mode));
 void set_alist_count __ARGS((void));
```

これでよさげ。

**Comment by mattn** [comment]
@k-takata ワイルドカード展開するか、ファイルが存在するかしないかで挙動が変わるので面倒ですが確認お願いします。

**Comment by k-takata** [comment]
cp932 で扱えないファイル名をコマンドラインで渡したときに正しく扱えないようです。

**Comment by mattn** [comment]
argc/argv を使うのはダメかな。wmain にするか GUI 版と同じくコマンドラインから引数を再生成するしかないか。
両論ありそうだけど、どう思います？ @k-takata @koron

**Comment by k-takata** [comment]
今までの CUI 版は、どこから Unicode なコマンドラインを取ってきていたかというと…、os_mswin.c の mch_early_init() の中ですか。
get_cmd_argsW() を呼ぶタイミングの問題だったりします？

**Comment by mattn** [comment]
あー、呼んでたのかー。じゃぁそっちでいった方がいいな。

**Comment by k-takata** [comment]
> 最少の再現手順

GUI版を試すのを忘れていたので試したところ、同じ動作でした。

> starting という変数を使って起動中かどうか見て fix_arg_enc を呼ぶかどうか見てるからだと思います。

起動中に enc をセットしてしまえば正しく動くので、このままで問題ないのではという気がしてきました。

**Comment by mattn** [comment]
あーw FEAT_GUI だw

**Comment by mattn** [comment]
CommandLineToArgvW はワイルドカード展開前の `あ*` が格納されてるけど argv は展開済みが入ってるのでその差異から used_file_arg 内の

```
if (STRCMP(global_argv[i], name) == 0)
```

が全滅して used_file_count が 0 のままというのが現状らしい。ってことで CUI 版も argv 捨ててしまうか、↑の方法を取るしかない。

**Comment by k-takata** [comment]
起動中に enc を設定した場合でも、問題が起きるパターンがあるということですか？

**Comment by mattn** [comment]
GUI 版の場合はオリジナルの引数を保持しておいて encoding が変わったら変換してさらに rewind という動き、CUI 版は argv に頼っていたという動きですね。
なんかごちゃごちゃしてますね。

> 起動中に enc を設定した場合でも、問題が起きるパターンがあるということですか？

CUI 版の場合は今まで問題視されていなかったという方が正しそうです。

**Comment by mattn** [comment]
個人的には↑のパッチの方が修正量が少ない気がします。

**Comment by mattn** [comment]
当てやすい様に gist 化

https://gist.github.com/mattn/a5e0156f8d5a31f39d92

**Comment by k-takata** [comment]
free_cmd_argsW() が2回呼ばれています。

> cp932 で扱えないファイル名をコマンドラインで渡したときに正しく扱えないようです。

これはどうなりました？

**Comment by mattn** [comment]
変なパッチのあたり方してた... m(_ _;)m

> > cp932 で扱えないファイル名をコマンドラインで渡したときに正しく扱えないようです。
> 
> これはどうなりました？

これは別途考えないといけなくて、wmain にするなら handle_cmd_args の引数を変えてしまえばいいかな。
GUI 版と同じく CommandLineToArgvW  にするのはちょっと無理があるなーと思ってます。
ここは意見が欲しいです。

**Comment by mattn** [comment]
そうか、引数で貰わずに GUI 同様に CommandLineToArgvW  から作ってみるか。

**Comment by mattn** [comment]
> cp932 で扱えないファイル名をコマンドラインで渡したときに正しく扱えないようです。

https://gist.github.com/5e41152ac0963d4d4f17

これでどうでしょう？

**Comment by mattn** [comment]
argc と nArgsW の min を持っておいた方がよさそうだけど

**Comment by k-takata** [comment]
再現手順はどうなります？ [上の方法](https://github.com/vim-jp/issues/issues/625#issuecomment-54100135)は問題なしだと思いますが。

**Comment by mattn** [comment]
https://gist.github.com/mattn/7e5fe4146561a9ff7664

これ使って `:w` して `森鷗外.txt` が保存されている事をエクスプローラから確認出来ました。

**Comment by mattn** [comment]
出すかな

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/il9V-ERBk-E/discussion

**Comment by k-takata** [comment]
パッチ未適用状態でも、以下のコマンドで正しく`森鷗外.txt`が保存されますが、何か問題だったのでしょうか。

```
vim -u NONE -N 森鷗外.txt --cmd "set enc=utf-8" -c "wq"
```

# リンクがおかしかったので直しておきました。

**Comment by mattn** [comment]
> パッチ未適用状態でも、以下のコマンドで正しく森鷗外.txtが保存されますが、何か問題だったのでしょうか。

https://github.com/vim-jp/issues/issues/625#issuecomment-54102403

これを受けて確認しただけです。
ただ、未パッチ状態だと`鷗`はcp932で表現出来ないはずなんですよね。例えば

``` c
#include <stdio.h>
#include <string.h>
int
main(int argc, char* argv[]) {
  printf("%s, %d\n", argv[1], strlen(argv[1]));
  return 0;
}
```

これに `森鷗外` って渡すと `森?外` と表示され、strlen は5になるんです。ってここまで書いて、もしかして未パッチ状態は `森?外.txt` になってワイルドカード展開されて `森鷗外.txt` が復活したんじゃなかろうな？とエスパーしてます。

リンク修正の件、ありがとうございました。

**Comment by k-takata** [comment]
`森鷗外.txt` が存在しない状態で、`森鷗外.txt` が作成されますのでワイルドカードが展開されたわけではありません。
未パッチ状態でも`get_cmd_argsW()`でUnicode APIでコマンドラインを取得しているので、問題ないはずです。

**Comment by mattn** [comment]
あれ？ !FEAT_GUI だった。見間違ったー。

**Comment by mattn** [comment]
ちょっとパッチ、キャンセルしてきます。

**Comment by mattn** [comment]
あーわかりました。

GUI版は get_cmd_argsW を呼んだあと、自分でワイルドカード展開している(get_cmd_args)
CUI版は get_cmd_argsW を読んだあと、展開していない(mch_early_init -> get_cmd_argsW)

つまりCUI版は global_alist は空のまま。で、そのまま set_alist_count を呼んでしまってるのでused_alist_count が0のままとなり、いくら fix_arg_enc を呼び出しても最初の if に引っかかって抜けてしまう。

こうですね。

**Comment by k-takata** [comment]
再現手順教えてください。

**Comment by mattn** [comment]
再現点順は↑の通りですね。

**Comment by mattn** [comment]
もう少し詳しく説明しますのでちょっと待って下さいね。

**Comment by mattn** [comment]
コマンドライン版は、get_cmd_argsW を呼び出してはいるけど `あ*` を展開しないまま残している。なので used_file_arg の `if (STRCMP(global_argv[i], name) == 0)` この部分が通らない。
`global_argv[i]` は `あ*` のまま name は `あ.txt`
なので used_file_argc が 0 のままとなります。で、fix_arg_enc の最初の if で失敗する。

**Comment by mattn** [comment]
ただ困った事に main.c では ansi 版の argc, argv を使って params に入れてファイル名展開をしちゃってるもんだから相違が出てるんですよね。

**Comment by k-takata** [comment]
> ×: 「あ.txt」がある場合にvim あ*とすると「.txt」というバッファ名で新規ファイル扱い

ん－、やっぱりこれが再現しないです。
`vim -u NONE -N あ* --cmd "set enc=utf-8 tenc=cp932"` で `あ.txt` が開かれます。

**Comment by k-takata** [comment]
コンパイラの違いとかあるのかな？

**Comment by mattn** [comment]
あー、すみません、もしかして `<>` が消えてます？↑

https://github.com/vim-jp/issues/issues/625#issuecomment-54100135

起きている事象はこれと同じです。

**Comment by mattn** [comment]
https://gist.github.com/mattn/a628af2a16214367c41b

これで直りました。

結論から言うと、argc と argv を CommandLineToArgrv を使った物に置き換えないと
- argv はランタイムがワイルドカードを展開しちゃう
- かたや main.c ではこれから params を使ってファイル名を展開しようとしている

という点で差異が発生してしまう。

**Comment by k-takata** [comment]
> あー、すみません、もしかして <> が消えてます？↑

いえ、書いてあるとおりです。リダイレクトは使っていません。

> 起きている事象はこれと同じです。

これについては私の方でも GUI/CUI ともに同じ現象が再現していますが、Vimの起動完了後に enc を変更してもコマンドラインのエンコーディングが変換されないのは意図した動作であり問題ではないですよね？ （それが本当に適切な動作かどうかは別として。）

> argv はランタイムがワイルドカードを展開しちゃう

MinGWはそうなんでしたっけ？ VCはデフォルトでは展開しません。(w)setargv.obj をリンクすれば展開するようになります。
http://msdn.microsoft.com/ja-jp/library/vstudio/ms235330.aspx

**Comment by mattn** [comment]
setargv.obj はコンパイラの実装で異なるので、揺らぎがありますね。たしか前、thinca さんと clang の実装も見ましたがそちらも差異があった記憶があります。
GUI 版とも共通になったし、どのコンパイラを使っても揺るぎの無い結果になったのでこの修正の価値はあると思いましたがどうでしょう？

**Comment by mattn** [comment]
> これについては私の方でも GUI/CUI ともに同じ現象が再現していますが、Vimの起動完了後に enc を変更してもコマンドラインのエンコーディングが変換されないのは意図した動作であり問題ではないですよね？ （それが本当に適切な動作かどうかは別として。）

これどういう意味ですか？encoding 変更時には意図的に fix_arg_enc を呼んで引数のエンコーディングを変更しています。

**Comment by k-takata** [comment]
> これどういう意味ですか？encoding 変更時には意図的に fix_arg_enc を呼んで引数のエンコーディングを変更しています。

これって、

> starting という変数を使って起動中かどうか見て fix_arg_enc を呼ぶかどうか見てるからだと思います。

なのですよね？ startingではなくなったら enc を変更しても fix_arg_enc は呼ばれない。なので、GUIだろうとCUIだろうと、起動後に手で `:set enc=utf-8` を入力しても `:args` の結果は化けたままと。

**Comment by k-takata** [comment]
> GUI 版とも共通になったし、どのコンパイラを使っても揺るぎの無い結果になったのでこの修正の価値はあると思いましたがどうでしょう？

MinGWのランタイムがワイルドカードを展開していたことが原因だったということであれば、それでよさそうです。
（逆に、MinGWでワイルドカード展開を抑制する方法ってあるんですかね？）

**Comment by mattn** [comment]
調べたところ

``` c
#ifdef __MINGW32_SETARGV
int _CRT_glob = __MINGW32_SETARGV;
#endif
```

これで切れる様ですが、かなりアドホックですな。非公開APIっぽいので変わる可能性あり。

**Comment by mattn** [comment]
スレッドに付け加えときました。

**Comment by k-takata** [comment]
7.4.432
https://groups.google.com/d/topic/vim_dev/IdUG2FandPc/discussion

**Comment by k-takata** [comment]
Related: https://github.com/vim/vim/issues/670
