### ISSUE TITLE
スコープ消滅時にスコープ変数がクリアされる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#628]
仕様かバグかわからないので、知っている人がいたら教えてください。
スコープ変数(辞書)を保持しておいて、その後でスコープ(ウィンドウなど)を閉じると、スコープ変数がクリアされます。

``` vim
let w:foo = 10
let w = w:
echo w
" => {'foo': 10}
new
only
echo w
" => {}
```

古いバージョンでは、閉じた後に w にアクセスした時点で SEGV を起こすようですが、最近のバージョンだと特にそういうことは起きないようです。また、試した感じだと少なくとも 7.3.478 without GUI では落ちます。しかし 7.3.478 with GUI だと落ちませんでした。しかし w に要素を追加しようとすると内部エラーが起きるので、内部状態は壊れているようです。7.4.430 では、クリアはされますが、内部エラーが起きたりすることはないようです。

改めて、
- この挙動は仕様なのか
- SEGV しなくなったのは意図的に修正されたのか、たまたま直ったのか
  - 直ったのはどのバージョンか

この辺り知っている方いたら教えてもらえると助かります。

**Comment by mattn** [comment]
意図的に直されたかどうか分かりませんが、期待通り(仕様通り)に動いている様には思えますね。

**Comment by thinca** [comment]
ドキュメントに記述はあるでしょうか?

**Comment by mattn** [comment]
`:help w:`

```
                        *window-variable* *w:var* *w:*
A variable name that is preceded with "w:" is local to the current window.  It
is deleted when the window is closed.
```

`current window`、`close` というキーワードから仕様だろうなと思いました。

**Comment by thinca** [comment]
お、なるほど。仕様であることは把握しました。ありがとうございます。
あとはできればどこで直ったか知りたい…(自分で調べろ案件?)

**Comment by thinca** [comment]
閉じてないのに xlose ラベルを付けられた…。どちらかと言うと forksforme では?

**Comment by mattn** [comment]
あ、xlose だった。直さなくていいってステータス欲しい。

**Comment by ynkdir** [comment]
SEGV が直ったのは #357 です。
変数がクリアされるのは CVS の一番古い版からなのでおそらくスコープ変数が入ったときからだと思います。

**Comment by mattn** [comment]
古すぎるwww

**Comment by tyru** [comment]
l: だけじゃなく、g:以外のスコープは全てdeepcopy()した方が安全ですねぇ…

**Comment by ynkdir** [comment]
今はスコープ変数の実装が辞書になったので変数を削除しないで辞書の参照だけ切り離すというのもありなのかもしれません。必要なら。

**Comment by thinca** [comment]
みなさんいろいろありがとうございます。

> SEGV が直ったのは #357 です。

この情報非常に助かりました。7.3.893 ですね。

> 今はスコープ変数の実装が辞書になったので変数を削除しないで辞書の参照だけ切り離すというのもありなのかもしれません。

これはこれで良さそうですが、とりあえず私がやりたかったことに対してはこれは特に必要ないので、やるとしたら別件ですかね。

とりあえずこの Issue は解決と言うことで閉じようと思います。ありがとうございました。
