### ISSUE TITLE
[提案]Vim に好きなアイコンを設定出来るパッチ

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#629]
https://gist.github.com/mattn/9e18383d71d9932685e7

どうでしょう？

![](http://go-gyazo.appspot.com/1c88fbea4abafb5a.png)

rtp 上に `bitmaps/vim.ico` を置いておけば勝手にロードする作戦

**Comment by koron** [comment]
`.ico` って何気に作るの面倒なんだよなぁ…

**Comment by mattn** [comment]
bmp の透過にするパッチにしてもいいよ。

On 9/3/14, MURAOKA Taro notifications@github.com wrote:

> `.ico` って何気に作るの面倒なんだよなぁ…
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/629#issuecomment-54296031

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/1AgMcjcdag8

**Comment by mattn** [comment]
評判悪ければ諦める。良ければ開発続行。

**Comment by deris** [comment]
:+1:

**Comment by sgur** [comment]
:+1:

**Comment by tyru** [comment]
:+1:

**Comment by k-takata** [comment]
> Patch to allow for a different icon on MS-Windows. (Yasuhiro Matsumoto, 2014
> Sep 7).

todo入りしましたね。この後はどうします？

**Comment by k-takata** [comment]
7.4.459
https://groups.google.com/d/topic/vim_dev/GecSUewV7CI/discussion
入ってしまいました。ドキュメントもないのにいいんですかね!?

**Comment by koron** [comment]
www

**Comment by k-takata** [comment]
残件かもしれないもの
- ドキュメント
- icoの代わりにbmp

**Comment by mattn** [comment]
mjd...

**Comment by tyru** [comment]
便利

**Comment by mattn** [comment]
ドキュメントは足してくれたようだ。

https://groups.google.com/forum/#!topic/vim_dev/GecSUewV7CI

更新されてないっぽいけど。。。

**Comment by k-takata** [comment]
https://ci.appveyor.com/project/k-takata/vim-ci/build/1.0.31#L80

> 84 gui_w32.c(1670) : warning C4047: 'function' : 'LPARAM' differs in levels of indirection from 'HANDLE'
> 85 gui_w32.c(1670) : warning C4024: 'SendMessageA' : different types for formal and actual parameter 4

warning出てますね。

**Comment by k-takata** [comment]
Warning 修正パッチ
https://groups.google.com/d/msg/vim_dev/GecSUewV7CI/wRIV5mPoKTAJ

**Comment by k-takata** [comment]
7.4.464
https://groups.google.com/d/topic/vim_dev/4HtkqIAynd4/discussion
はやっ！
