### ISSUE TITLE
Cygwinのclangでif_perlがリンクエラー

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#633]
http://lingr.com/room/vim/archives/2014/09/08#message-20138223

> clang 上の clang で if_perl を有効にするとビルド通らないんですがご存知の方いるでしょうか。

ログ: https://gist.github.com/0xBADDCAFE/7f4f8ed53c4b42f9c1bc#file-log

とりあえず作ってみたパッチ: https://bitbucket.org/k_takata/vim-ktakata-mq/src/5dd1e87f2ad5af4740b9d02d4467f2108b453694/fix-clang-cygwin-perl.patch

**Comment by 0xBADDCAFE** [comment]
cygwin on win7 32bit、clang 3.4 でビルド確認出来ました、ありがとうございます。

**Comment by k-takata** [comment]
このやり方で本当にいいのかというとよく分かりません。
本当は clang か Perl が修正すべき問題かも？

**Comment by ynkdir** [comment]
Bug 19939 - Clang fails to export __declspec(dllexport) symbols
http://llvm.org/bugs/show_bug.cgi?id=19939

最新の clang では直ってるらしいです。

**Comment by k-takata** [comment]
CygwinにClang 3.5が来ていたので試してみたところ、確かにこの問題は直っているようでした。
ただし、今度はconfigure時に別のエラーが出ていました。

```
clang: error: unknown argument: '-fdebug-prefix-map=/mnt/share/maint/perl.x86/build=/usr/src/debug/perl-5.14.4-3'
clang: error: unknown argument: '-fdebug-prefix-map=/mnt/share/maint/perl.x86/src/perl-5.14.4=/usr/src/debug/perl-5.14.4-3'
```

以下のパッチを当てた上で、以前のパッチを外したところ、ビルドできました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/b56795eb68a229e73131b52d258bc3e06e7821e2/cygwin-clang-3.5.patch

**Comment by k-takata** [comment]
Clang 3.5でif_perlが有効にならない問題はパッチを投げました。
https://groups.google.com/d/topic/vim_dev/TACuLw49OlA/discussion
Clang 3.4でリンクエラーになる問題はなかったことにしてもいいかな？

**Comment by k-takata** [comment]
7.4.750
https://groups.google.com/d/topic/vim_dev/Uc-Rw9X9H8A/discussion
Clang 3.5でif_perlが有効にできるようになったので閉じます。
