### ISSUE TITLE
ヒアドキュメント作ろうぜ！

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#634]
「ぶっヒアドキュメントする」…そんな言葉は使う必要がねーんだ。
なぜなら、オレや、オレたちの仲間は、
その言葉を頭の中に思い浮かべた時には！
実際に相手をヒアドキュメントっちまって、もうすでに終わってるからだッ！
だから使った事がねェーッ。
mattn、オマエもそうなるよなァ～～～、オレたちの仲間なら…
わかるか？オレの言ってる事…え？
『ぶっヒアドキュメントした』なら、使ってもいいッ！

オレらの思いはただこれだけだ。これを動かしたいッ！

``` vim
let F = lambda(`
  let x = shougo#kisamamasaka(a:1)
  let y = shougo#sonomasakada(a:1)
  return shougo#fuhahahahaha(x, y)
`)
```

パッチはまだない。
- [ ] 実装
- [ ] ドキュメント
- [ ] テスト

**Comment by tyru** [comment]
let F = lambda(`
\let x = shougo#kisamamasaka(a:1) |
\let y = shougo#sonomasakada(a:1) |
\return shougo#fuhahahahaha(x, y)`)

で、現状でもうこう書けばいけるような気がします。
ヒアドキュメントが欲しいのには同意です。

**Comment by mattn** [comment]
出来るのはみんな分かってて、クォート内でクォートのエスケープを書きたくないってのが一番だと思います。

**Comment by koron** [comment]
ちょっとアレなんですが、lambdaの中にはlambda書きたいなぁw

**Comment by k-takata** [comment]
`:python` などのヒアドキュメントっぽい機能はどうやっているのかちょっと見たところ、ex_getln.c の script_get() で解析しているらしい。

**Comment by ichizok** [comment]
関数定義のパース時は関数の中身を真面目に読んでないので、行がヒアドキュメント内にあるかどうかを判定するのが困難です。
https://github.com/vim/vim/compare/master...ichizok:feature/raw-string

```vim
function! F()
  let foo = `
alice
in " :insert と解釈されて終端の `.` が見つかるまで行スキップ、結果 `Missing :endfunction` エラーになる
wonderland`
endfunction
```

`:heredoc` を作る、`:append` に変数代入のオプションを追加する、などコマンドベースなら比較的簡単そうですが、利便性は...

```vim
:heredoc => foo " 変数 `foo` に代入 (:redir と同様. >{file} や @{a-z} なども)
abc
123
:heredoc END
```

```vim
:append => foo " 変数 `foo` に代入 
abc
123
.
```

**Comment by k-takata** [comment]
[8.1.1354](https://github.com/vim/vim/commit/f5842c5a533346c4ff41ff666e465c85f1de35d5)でheredocが入りました。`:let` 専用で、改行区切りではなく、文字列のリストを返すというちょっと変わった仕様のようですが。
