### ISSUE TITLE
winrestview()に渡すtoplineに0以下の値を設定すると描画が崩れる

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#637]
- [:h winrestview()](http://vim-jp.org/vimdoc-ja/eval.html#winrestview%28%29)
### 再現手順
1. `vim -N -u NONE`
2. `:set number` (任意. 行番号がマイナスになる)
3. `:normal! ivim`
4. `:call winrestview({'topline': -10})`

![screenshot from 2014-09-23 00 08 12](https://cloud.githubusercontent.com/assets/3797062/4358540/27392c44-426b-11e4-97ab-4e7ea117c130.png)
### NOTE

プラグインから使っていて発見した時は Vimの`E38`のエラーが出たのですが, エラーも吐く再現する最小構成がわかりませんでしたのでまた見つかったら追記します.

**Comment by mattn** [comment]
かっこいい

On 9/23/14, haya14busa notifications@github.com wrote:

> - [:h
>   winrestview()](http://vim-jp.org/vimdoc-ja/eval.html#winrestview%28%29)
> 
> ### 再現手順
> 1. `vim -N -u NONE`
> 2. `:set number` (任意. 行番号がマイナスになる)
> 3. `:normal! ivim`
> 4. `:call winrestview({'topline': -10})`
> 
> ![screenshot from 2014-09-23 00 08
> 12](https://cloud.githubusercontent.com/assets/3797062/4358540/27392c44-426b-11e4-97ab-4e7ea117c130.png)
> 
> ### NOTE
> 
> プラグインから使っていて発見した時は Vimの`E38`のエラーが出たのですが,
> エラーも吐く再現する最小構成がわかりませんでしたのでまた見つかったら追記します.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/637

## 
- Yasuhiro Matsumoto

**Comment by haya14busa** [comment]
``` patch
diff --git src/move.c src/move.c
index 42f7784..3ffe230 100644
--- src/move.c
+++ src/move.c
@@ -528,6 +528,8 @@ set_topline(wp, lnum)
     win_T  *wp;
     linenr_T   lnum;
 {
+    if (lnum < 1)
+        lnum = 1;
 #ifdef FEAT_FOLDING
     /* go to first of folded lines */
     (void)hasFoldingWin(wp, lnum, &lnum, NULL, TRUE, NULL);

```

一応これでなおることは確認しましたが、いいのかはよくわかりません。すみません

**Comment by h-east** [comment]
@haya14busa お疲れ様です。

`winrestview()`は`winsaveview()`とセットで使用される事を前提としているので、再現手順のような`winsaveview()`を使用しない使い方はヘルプに書かれている通り(結果は予測できない)ではないかと思います。

```
winrestview({dict})
        |winsaveview()|が返す辞書|Dictionary|を使ってカレントウィンド
        ウの表示状態を復元する。
        この値を手動で変更した場合、結果は予測できない。
        ウィンドウサイズが変更されていると、結果は必ずしも元通りになら
        ない。
```

`winsaveview()`とセットで使用していて変な動作になった場合は明らかにバグですのでその手順を書いて下さい。

---

貼ってもらったpatchは問題無いとは思うのですが、影響範囲がデカいので`winrestview()`の動作だけを変更する形にした方がいいかもしれません。

``` diff
diff -r 47b1887483da src/eval.c
--- a/src/eval.c    Fri Sep 19 22:38:48 2014 +0200
+++ b/src/eval.c    Tue Sep 23 23:21:47 2014 +0900
@@ -19576,7 +19576,7 @@
 # endif
    changed_window_setting();

-   if (curwin->w_topline == 0)
+   if (curwin->w_topline <= 0)
        curwin->w_topline = 1;
    if (curwin->w_topline > curbuf->b_ml.ml_line_count)
        curwin->w_topline = curbuf->b_ml.ml_line_count;
```

**Comment by mattn** [comment]
エラーにすべきかどうかは Bram 次第ですな

**Comment by haya14busa** [comment]
> winsaveview()とセットで使用していて変な動作になった場合は明らかにバグ

##### :h winsaveview()

> ```
>   Note: {dict} は |winsaveview()| の返り値に含まれる値をすべて
>   持っていなくても構わない。値がない場合はその設定は復元されな
>   い。次のようにできる: >
>       :call winrestview({'curswant': 4})
> ```

確かに, 基本的に `winsaveview()`と組み合わせて使うものだとは思いますが、helpの例を見る限り, 手動で変更すると結果が予測できないと警告しているだけで, 単体(または `winsaveview()`で得た辞書を改変して)使うケースは想定されてるかと思います。

そして、この行がマイナスになる結果は使用者の予測の範囲外というよりも, Vim自体の予測の範囲外かと考えたので報告させていただきました.

> 影響範囲がデカいのでwinrestview()の動作だけを変更する形

確かにそちらのほうがよさそうですね、ありがとうございます!

**Comment by h-east** [comment]
vim_devにpatch送りました。
https://groups.google.com/d/msg/vim_dev/6InfDcsaWjI/Ft8Phjjp0FcJ

**Comment by haya14busa** [comment]
@h-east さんありがとうございます! :+1:

**Comment by h-east** [comment]
Patch 7.4.491
https://groups.google.com/d/msg/vim_dev/X4WfshXk52o/wb4nm8K6S1EJ

@haya14busa 報告ありがとうございました。

**Comment by haya14busa** [comment]
お疲れ様です。ありがとうございました！:100:
