### ISSUE TITLE
Windows で複数部数を印刷すると、増える

### ISSUE THREAD

**Issue by AkihaTohno** [vim-jp/issues#639]
はじめまして。
Windows7 32Bit上の香り屋版Vimで複数枚印刷の設定を行うとなぜか、指定した枚数の倍の枚数
印刷されてしまいます。一枚の場合は問題ありません。

対処をお願いします。

---

**@koron による補足** 
- `hardcopy` 実行時のダイアログの「部数」に2を指定することで発生。それ以上は試していない
- +kaoriya パッチの有無には関係なく発生した
- vim/gvim は関係なく発生した
- 32/64ビット は関係なく発生した
- プリンタ依存の可能性がある。Photosmart 5520では発生したが、XPS Document Writerでは発生しなかった
- 試すときは要注意。紙がスゴい勢いで減るw

**@mattn による補足**
- mingw32 でビルドした vim.exe で物理プリンタを使用して再現せずだった

**Comment by mattn** [comment]
こちら(Win7 32bit)で確認(非kaoriya)しましたが、再現しませんでした。

![](http://go-gyazo.appspot.com/8a0d43cacefd25b7.png)

これの2を指定している部分の事で良いでしょうか？

**Comment by koron** [comment]
@AkihaTohno 念のためプリンタのメーカー&型番を教えてもらえますか?

**Comment by koron** [comment]
`:hardcopy` して部数に2を選択すると gvim +kaoriya, 32 & 64 どちらでも再現した。
非パッチでどうなるかはこれから試す。

プリンタは HP Photosmart 5520
キューをみてると 1/2 ってなってるんだけど、そのうち 3/2 になるw

**Comment by koron** [comment]
非パッチ64bitのgvimで試したが、発生した。
# なんだかんだで15枚、紙を無駄にしましたわw

@mattn gvim でやりました? 物理的なプリンタでやってみました?

@AkihaTohno やはり一応、プリンタのメーカーと型番を教えておいてください。

**Comment by koron** [comment]
一応、わかりやすいように最初のコメに今わかってることを追記しておきました。

**Comment by mattn** [comment]
vim.exe でやりました。さっき物理プリンタでやりましたが再現せずでした。

**Comment by koron** [comment]
@mattn プリンタメーカーと型番をおねがいします。

**Comment by mattn** [comment]
D でおくりまーす。

**Comment by koron** [comment]
ウン百万する業務用複合機はお帰りください (´・ω・`)

w

**Comment by AkihaTohno** [comment]
こんにちは。
こちらの環境はCanon LBP8630になります。
gvimですね

**Comment by koron** [comment]
@mattn 民生のインクジェットプリンタで試せます?
あと使ってる vim.exe どっかに置いておいてもらえますか?
例の鯖でも良いです。

@AkihaTohno ありがとうございます。
[LBP8360 の仕様](http://cweb.canon.jp/pls/webcc/wc_show_contents.EdtDsp?i_cd_pr_catg=002&i_cd_pr=&i_cd_qasearch=Q000054000&i_cl_form=01&i_tx_search_pr_name=&i_tx_contents_dir=%2Fe-support%2Ffaq%2Fanswer%2Flbp&i_tx_contents_file=54000-1.html&i_tx_keyword=&i_tx_qasearch_url=javascript%3Adocument.getElementById%28%27searchResult%27%29.submit%28%29%3B&i_cd_transition=1&i_fl_edit=1)

**Comment by mattn** [comment]
今手元にないですー。次のチャンスにやります。

**Comment by koron** [comment]
レーザープリンタでも発生するのは、ちょっと意外。

あと念のため HP Officejet Pro L7500 でも発生することを確認。

@mattn あ、うちのvim.exeかgvim.exeで、その大丈夫だったプリンタで試せます?

**Comment by mattn** [comment]
あーーーーーーーーーーーーーーーーーーーーーーーっ

すいませんすいません。複合機の画面に2ページって出てたので「あー2Pかー」と削除ボタンを押しましたが、さっき紙に出してみたら 2部 x 謎の2 で4枚出た。

**Comment by k-takata** [comment]
試してないのですが、実は、3部指定したら9ページ出たりしません？
n_collated_copies と n_uncollated_copies の両方に、prt_dlg.nCopies 代入してるけど…。

**Comment by mattn** [comment]
> n_collated_copies と n_uncollated_copies の両方に、prt_dlg.nCopies 代入してるけど…。

どちらかにしか nCopies は入らない様です。

**Comment by k-takata** [comment]
あ、見間違えてた。条件が逆になってますね。

**Comment by mattn** [comment]
https://github.com/vim-jp/vim/blob/master/src/hardcopy.c#L701

ページ毎にこんな事やってるけど、いいんだっけ。
settings そのまま渡ってるけど。

**Comment by mattn** [comment]
うむ。ひとまず大丈夫そげ。原因は他。

**Comment by koron** [comment]
> さっき紙に出してみたら 2部 x 謎の2 で4枚出た。

www

**Comment by k-takata** [comment]
http://msdn.microsoft.com/en-us/library/windows/desktop/ms646843.aspx

> When making calls to GDI, you must ignore the value of nCopies, consider the value as 1, and use the returned hDC to avoid printing duplicate copies.

ん？どういうこと？

**Comment by mattn** [comment]
PD_USEDEVMODECOPIESANDCOLLATE これ？

**Comment by mattn** [comment]
これで直ったっぽい。誰か試してー。

``` diff
diff -r e861ee614a3a src/os_mswin.c
--- a/src/os_mswin.c    Wed Sep 24 10:58:20 2014 +0900
+++ b/src/os_mswin.c    Fri Sep 26 17:25:09 2014 +0900
@@ -1673,16 +1692,22 @@
      */
     psettings->chars_per_line = prt_get_cpl();
     psettings->lines_per_page = prt_get_lpp();
-    psettings->n_collated_copies = (prt_dlg.Flags & PD_COLLATE)
-                           ? prt_dlg.nCopies : 1;
-    psettings->n_uncollated_copies = (prt_dlg.Flags & PD_COLLATE)
-                           ? 1 : prt_dlg.nCopies;
-
-    if (psettings->n_collated_copies == 0)
+    if (prt_dlg.Flags & PD_USEDEVMODECOPIESANDCOLLATE)
+    {
+   psettings->n_collated_copies = (prt_dlg.Flags & PD_COLLATE)
+                           ? prt_dlg.nCopies : 1;
+   psettings->n_uncollated_copies = (prt_dlg.Flags & PD_COLLATE)
+                           ? 1 : prt_dlg.nCopies;
+
+   if (psettings->n_collated_copies == 0)
+       psettings->n_collated_copies = 1;
+
+   if (psettings->n_uncollated_copies == 0)
+       psettings->n_uncollated_copies = 1;
+    } else {
    psettings->n_collated_copies = 1;
-
-    if (psettings->n_uncollated_copies == 0)
    psettings->n_uncollated_copies = 1;
+    }

     psettings->jobname = jobname;

```

**Comment by koron** [comment]
やった! 2枚しかでなかった!w

**Comment by koron** [comment]
@mattn というわけでそれで治ってます :+1:

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/WDRaMYJGLPM

**Comment by rbtnn** [comment]
Patch 7.4.461
~~http://ftp.vim.org/vim/patches/7.4/7.4.461~~
https://groups.google.com/d/msg/vim_dev/BANNZsL1L4U/vkmoKMN6P3gJ

**Comment by k-takata** [comment]
早い！
