### ISSUE TITLE
iminsertとimdisableが直ちには反映されない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#64]
edit中にiminsertやimdisableを変更しても、直ちには反映されない。
またiminsertについてはIMEのON/OFFを切り替えても、editモード中は期待する値を保持しない。
### 背景

この2つのオプションはもともとeditモード外で変更されることを想定して作られていた。
その後CursorMoveIなどのautocmdが追加され、edit中にもスクリプトが実行されるようになった。
そのようなシチュエーションでiminsertやimdisableが変更されても実際には反映されない。
### 影響

特に以下のような不具合がある
- editモード中にimdisableを1→0にしても、手動ですらIMEをONにできない
- iminsert=0の状態でeditモードに入り、IMEをONにしてもeditモード中はiminsertは0のまま
- editモード中にiminsert=2にしても、IMEがONにならない
### 解説

Windowsではsrc/gui_w32.cのim_set_active()の中で、
p_imdiableを見てHIMCを繋いだり切ったりしてimdisableを実現している。
一方src/options.cではimdisableを変更した場合に、
imdisable=1の時はim_set_active()を呼び出しているが、
imdisable=0の時は呼び出していない。
そのためにHIMCが切られたままでIMEをONできなくなる。

editモード外でimdiableを操作した場合は、
editモード突入時に必ずim_set_active()が呼ばれるのでこの問題はおこらない。
### 備考

[issue 13](https://github.com/vim-jp/issues/issues/13) を追っててわかった。

**Comment by koron** [comment]
imdisableの件は比較的通りやすそうなので、とりあえずのパッチを送ってみる。

**Comment by koron** [comment]
imdisable の件だけ投稿した。

https://groups.google.com/forum/#!topic/vim_dev/6KORMEwLxEU

**Comment by h-east** [comment]
便乗で質問です。

<code>gvim -N -u NONE -U NONE -i NONE --noplugin</code>
だとinsertモード抜けた時のIM状態を覚えていてくれるけど、

<code>gvim -N -u NONE -U NONE -i NONE --noplugin -c "inoremap <Esc> <Esc><C-l>" </code>
の場合は覚えていてくれない。(insertモードに入ると常にIMオン)

これもこのIssueに関係ありますか？
そして現状で回避策ありますか？

**Comment by koron** [comment]
@h-east: 関係ない。回避策はInsertLeaveでCTRL-Lしたらどう?

覚える処理はim_save_status()でやってるが

> ```
> * Also don't save when inside a mapping, vgetc_im_active has not been set
> * then.
> ```

とあるので、mappingでeditから出ること自体がアウトなんだろう。

**Comment by h-east** [comment]
@koron なるほどです。勉強になった。

**Comment by tyru** [comment]
7.3.335で取り込まれたようです。

https://groups.google.com/group/vim_dev/browse_thread/thread/cf487c99cb941ec4?hl=ja

> Patch 7.3.335
> Problem:    When 'imdisable' is reset from an autocommand in Insert mode it
>             doesn't take effect.
> Solution:   Call im_set_active() in Insert mode. (Taro Muraoka)

**Comment by koron** [comment]
補足: 取り込まれたのはimdisableを設定するようにしたパッチ。

iminsert についてはパッチ自体作成していない。チケット割るべきかな。

**Comment by tyru** [comment]
あ、なるほど。
勘違いしてました。

**Comment by koron** [comment]
継続issueを立てたのでコチラは imdisable に関して終わったということで閉じます。
