### ISSUE TITLE
count関数の引数の順番が間違っている。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#642]
helpのtypoを見つけたので報告します。
- 内容

`:help functions`のcount関数の引数の順番が間違っています。
`count( {list}, {expr} [, {start} [, {ic}]])`じゃなくて`count( {list}, {expr} [, {ic} [, {start}]])`が正しいと思われます。
- 場所

> https://github.com/vim-jp/vim/blob/007a19c3ac59e8e0c171995bd2f695036293e4a2/runtime/doc/eval.txt#L1754
- 備考

関数の説明部分は正しいようです。

> https://github.com/vim-jp/vim/blob/007a19c3ac59e8e0c171995bd2f695036293e4a2/runtime/doc/eval.txt#L2555

vimdoc-jaも同様。

> https://github.com/vim-jp/vimdoc-ja/blob/41d4b0ed05f2202a029b20ae69e07da629b5f741/doc/eval.jax#L1707

以上、よろしくお願い致します。

**Comment by ynkdir** [comment]
報告しました。
https://groups.google.com/d/msg/vim_dev/YYYBW2-48oQ/D1op5VIyM44J

**Comment by rbtnn** [comment]
ありがとうございます。

**Comment by k-takata** [comment]
Fixed.
https://github.com/vim-jp/vim/commit/542d7043d900d20f3ef5c27580278d8d83d1016f#diff-bea881dfa9626bab7141337b0fcdb23eL1754
