### ISSUE TITLE
vim7.4.456以降でmkviewの後loadviewするとエラーになる。

### ISSUE THREAD

**Issue by magicdrive** [vim-jp/issues#643]
vim7.4.456以降で、mkviewにて作られるファイルにsetlocal backup=とあります。
そのままloadviewすると

```
E474: Invalid argument: backupcopy=
```

とエラーが出てしまいます。

**Comment by magicdrive** [comment]
手元で確認したところ、vim7.4.455以前ではsetlocal backupcopy=の一文はmkviewで作られるファイルに存在しないようです。

**Comment by h-east** [comment]
@magicdrive Issue登録ありがとうございます。

Vimのバグです。ちょっと説明します。
'backupcopy'オプションは元々グローバルオプションだったのですが、7.4.456でグローバル/バッファローカルオプションに変更になりました。
あと'backupcopy'オプションは以前から以下の制約があります。(ヘルプには書いていない:sweat_smile:)
- "yes" か "no" か "auto" の何れかを含んでいなければならない。

つまり空は許されない訳です。
ですが、グローバル/ローカルオプションになったことでちょっと困ったことになってしまっています。
というのもグローバル/ローカルオプションはローカル値が空の場合にグローバル値を使う仕組みになっているので空が許されないオプションだとその判定が出来ないことになってしまいます。

グローバル値は`auto`

``` vim
:setglobal backupcopy?
  backupcopy=auto
```

ローカル値は空 ←'backupcopy'オプション的にはNG

``` vim
:setlocal backupcopy?
  backupcopy=
```

グローバル値を表示(ローカル値が空なので)

``` vim
:set backupcopy?
  backupcopy=auto
```

ローカル値に値をセット

``` vim
:setlocal backupcopy=no
```

ローカル値を表示(ローカル値が空ではないので)

``` vim
:set backupcopy?
  backupcopy=no
```

...ということで報告の件は以下の手順で`E474`が出ることと原理は同じです。

``` vim
:setlocal backupcopy=
```

対策はこれでイケるじゃないですかね？
- `setlocal backupcopy=`された時は値が空を許容する。(グローバル値に有効な値がはいっているので)

**Comment by h-east** [comment]
``` diff
diff -r 1b74025a66e7 src/option.c
--- a/src/option.c  Sat Sep 27 11:18:20 2014 +0200
+++ b/src/option.c  Mon Sep 29 00:40:24 2014 +0900
@@ -5742,15 +5742,18 @@
        flags = &curbuf->b_bkc_flags;
    }

-   if (opt_strings_flags(bkc, p_bkc_values, flags, TRUE) != OK)
-       errmsg = e_invarg;
-   if ((((int)*flags & BKC_AUTO) != 0)
-       + (((int)*flags & BKC_YES) != 0)
-       + (((int)*flags & BKC_NO) != 0) != 1)
-   {
-       /* Must have exactly one of "auto", "yes"  and "no". */
-       (void)opt_strings_flags(oldval, p_bkc_values, flags, TRUE);
-       errmsg = e_invarg;
+   if (!((opt_flags & OPT_LOCAL) && *bkc == NUL))
+   {
+       if (opt_strings_flags(bkc, p_bkc_values, flags, TRUE) != OK)
+       errmsg = e_invarg;
+       if ((((int)*flags & BKC_AUTO) != 0)
+           + (((int)*flags & BKC_YES) != 0)
+           + (((int)*flags & BKC_NO) != 0) != 1)
+       {
+       /* Must have exactly one of "auto", "yes"  and "no". */
+       (void)opt_strings_flags(oldval, p_bkc_values, flags, TRUE);
+       errmsg = e_invarg;
+       }
    }
     }
```

**Comment by magicdrive** [comment]
おおお！ご対応ありがとうございます！

**Comment by ghost** [comment]
すみません(;´Д`)うちでも困ったんでこれを出した後にここを見たらという流れで…
https://groups.google.com/d/msg/vim_dev/x3t4oemwkXc/-VFR6kt4bugJ

**Comment by ghost** [comment]
私のは Incorrect ですね、なんかこんなんばっかでやっばり自分には適正ないなと…。
撤回してきます。

**Comment by h-east** [comment]
@ntak 連絡ありがとうございます。
今晩帰ってからpatch投げようと思います。
まぁそれまでに誰かが同じpatch投げるとは思いますけどねw
可能でしたら ntakさんが投げて頂いても構いませんよ？:smile:

**Comment by ghost** [comment]
「帰ってから投げたpatch」と「ntakさんが投げるパッチ」が絶対ぶつかる！
ぶつかるかなと思ってやったことは全部ぶつかる星の元に産まれてきた感あるので
全面的にお願いします(;´Д`)

**Comment by h-east** [comment]
vim_devに投稿しました。
https://groups.google.com/d/msg/vim_dev/x3t4oemwkXc/61k26s1Pf1gJ

@ntak :stuck_out_tongue_closed_eyes:

**Comment by h-east** [comment]
Patch 7.4.462
https://groups.google.com/d/msg/vim_dev/3u0PKRJrSjU/48W88Q6mLJ4J

Bram氏の手直しが入った。フラグをクリアするのを忘れていた(汗)
