### ISSUE TITLE
n/N で normal!, noremap した時とデフォルトのfoldの扱いが違う

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#644]
### TL;DR
- デフォルト`n`/`N` => カーソル下のfoldを開く
- `:normal! n` => foldを開かない (開いて欲しいけど仕様?)
- `:nnoremap <Leader>n n` して `<Leader>n` => foldを開かない(開いて欲しい)
#### test.txt

```
" vim: foldmethod=marker

destination

fold {{{
    inner fold {{{
        destination
    }}}
}}}
```
1. `vim -N -u NONE test.txt`
2. `/destination`
3. `n` => fold が開かれる(なお`normal! n`だと開かれないので直接打つ)
4. `:normal! NzM`
5. `:nnoremap <Leader>n n`
6. `<Leader>n` => foldが開かれない

`normal!`だと直接打った場合と違う仕様になってるというのは他のマップでもそういうものがあるので問題ないとは思うのですが、`:noremap` によって挙動が変わってしまうのは混乱を招くと思われます

**Comment by mattn** [comment]
```
:set foldopen?
```

の値も教えて下さい。

**追記**
あーデフォルトか。自分で調べます。。。

```
'foldopen' 'fdo'    string (default: "block,hor,mark,percent,quickfix,
                                 search,tag,undo")
```

**Comment by mattn** [comment]
`foldopen=all` にしたら飛びますね。どれがそれにあたるか分かりませんが。

**Comment by haya14busa** [comment]
> :h 'foldopen'
> 
> NOTE: コマンドがマッピングの一部として実行されたときは、このオプション
> は使われない。同じ効果を得るには、マッピングにコマンド |zv| を加えるこ
> と。

なるほど 'foldopen' のヘルプにマッピングとして実行されたときはこのオプションは
使われないと書いてあるので仕様だったということですね。申し訳ありません。

ただ `:set foldopen=all` するとマッピングの一部でも上記の`NOTE:`関係なく飛ぶと
いうことのようですかね...

**Comment by h-east** [comment]
`foldopen`オプションのキーワードって
all == block, hor, insert, jump, mark, percent, quickfix, search, tag, undo
だと思い込んでいたんですが違うんですね！驚き。

src/option.h : 468

``` c
# define FDO_ALL                0x001
# define FDO_BLOCK              0x002
# define FDO_HOR                0x004
# define FDO_MARK               0x008
# define FDO_PERCENT            0x010
# define FDO_QUICKFIX           0x020
# define FDO_SEARCH             0x040
# define FDO_TAG                0x080
# define FDO_INSERT             0x100
# define FDO_UNDO               0x200
# define FDO_JUMP               0x400
```

FDO_ALL でソースをgrepするとFDO_ALL単独での比較しか出てこないｗ

**Comment by mattn** [comment]
せめて any にしてほしいww
