### ISSUE TITLE
kaoriya版64bitのzipファイル

### ISSUE THREAD

**Issue by sporty** [vim-jp/issues#646]
kaoriya64bit版のzipファイルの内容がおかしいようです。

http://files.kaoriya.net/goto/vim74w64

からダウンロードした

vim74-kaoriya-win64-20140916.zip

を解凍しましたが、gvim.exeが入っていません。どうも32bit版と比べてもディレクトリ構造が違う気がします。

**Comment by thinca** [comment]
きちんと入っているように見えます。
ダウンロードに失敗していないでしょうか?
このファイルのサイズは 15,614,010 バイトです。

**Comment by sporty** [comment]
確認ありがとうございます。
IEではなぜかダウンロードできず、chromeでは正しくダウンロードできたようです。環境の問題のようですね。大変失礼いたしました。
