### ISSUE TITLE
helpでcursor関数の第3引数の名前が違う。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#647]
helpのtypo(?)を見つけたので報告します。
- 内容

help上のcursor関数の第3引数の名前が違っています。
`cursor( {lnum}, {col} [, {coladd}])`と`cursor({lnum}, {col} [, {off}])`。
どっちかに合わせたほうがいいと思われます。
- 場所

> https://github.com/vim-jp/vim/tree/542d7043d900d20f3ef5c27580278d8d83d1016f/runtime/doc/eval.txt#L1758
> https://github.com/vim-jp/vim/tree/542d7043d900d20f3ef5c27580278d8d83d1016f/runtime/doc/eval.txt#L2604

以上、よろしくお願い致します。

**Comment by ynkdir** [comment]
ありがとうございます。
まあ間違いでもないのでなにかのついでに混ぜ込めたらと思います。

**Comment by k-takata** [comment]
ドキュメント関連の修正がいくつかあったので、まとめて投げておきました。
https://groups.google.com/d/topic/vim_dev/fvkU9fuaZ1U/discussion

**Comment by ynkdir** [comment]
ありがとうございます！

**Comment by k-takata** [comment]
取り込まれました。
https://github.com/vim-jp/vim/commit/a0cfe225debeb5fc9cff4f1dda77dbb72b0a83aa#diff-bea881dfa9626bab7141337b0fcdb23eL1758
