### ISSUE TITLE
substitute(foo, "\n", "", "g") が遅い

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#648]
https://github.com/vim-jp/vital.vim/pull/211

**Comment by ichizok** [comment]
プロファイル取りました。
https://gist.github.com/ichizok/dc82b7f3da46d4c778c3
http://i.imgur.com/mGbyfIR.png
http://i.imgur.com/laoRTg5.png

スクリプト
https://gist.github.com/ichizok/f279a2a3c35109432ead

eval.c:25125 で毎回 `STRLEN()` しているのが原因のようなので、文字列終端を保存して算出
https://gist.github.com/ichizok/d6a494d4fb7babdf41ff

**Comment by mattn** [comment]
良いと思います。

**Comment by h-east** [comment]
@ichizok お疲れ様です。ichizokさんのpatch適用前と適用後の処理時間が見たいです。

**Comment by ichizok** [comment]
```
CentOS 7 / Vim 7.4.463
unpatched:
substitute()  3.405360
join(split()) 0.025872

patched:
substitute()  0.017540
join(split()) 0.024036
```

`\n` を消すだけなら `join(split())` より速くなっています。

**Comment by h-east** [comment]
@ichizok :+1: スゲー!!

**Comment by mattn** [comment]
@ichizok パッチ送付お願いします。

**Comment by ichizok** [comment]
提出しました。
https://groups.google.com/forum/#!topic/vim_dev/W5Oo26uP78Q

**Comment by koron** [comment]
:+1:

**Comment by k-takata** [comment]
todo入り

> substitute() can be slow with long strings.  Patch by Ozaki Kiichi, 2014 Oct
> 12.

**Comment by k-takata** [comment]
7.4.499
https://groups.google.com/d/topic/vim_dev/P_lDjLNGr28/discussion

**Comment by h-east** [comment]
@ichizok :+1:
