### ISSUE TITLE
:redirがネストできない (capture関数の追加)

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#65]
現状`:redir`がネストできないので`:redir`を使う恐れのある処理を`:redir`から呼び出せません。(呼び出すとエラーになります)
quickrunは['verbosefile'を使って回避した](https://github.com/ujihisa/vital.vim/issues/1#issuecomment-2282579)ようですが、ネストできるとhackを使わずに済みます。(`:redir`自体(関数からなどではなく)出力から無理矢理情報を取得せざるを得ない場合に使うのでhackっぽいといえばそうですが...)

**Comment by thinca** [comment]
+1

> `:redir`自体(関数からなどではなく)出力から無理矢理情報を取得せざるを得ない場合に使う

ですね。`:redir` 自体のネストは結局欲しいですが、本来ならここを根本的に解決したいところです。別 Issue で登録しておく?

**Comment by tyru** [comment]
@thinca うーむ範囲が広いと思われるのでどういうタイトルで登録するのかが問題ですね...
「全ての:redirが必要な部分を消し去りたい」とか一生closeされなさそう...

**Comment by thinca** [comment]
とりあえず広い範囲の Issue を登録して、後で細かい Issue に分割するとかどうでしょう。

**Comment by koron** [comment]
少なくとも以下はわけるべきでしょう。
- そもそもredirを使わないで済むようにすべきじゃないか
- redirのネストをサポートする

私は前者を優先すべきだと考えてます。redirはおそらくデバッグ目的で作られ、
表示される内容については「変更されない保証はない」というあたりから、
それをスクリプトで正機能として使うのは好ましくないです。

**Comment by thinca** [comment]
今見つけたんですが、`:help scriptnames-dictionary` と言うのがありますね。
ここには、「`:scriptnames` の結果を取得できるような関数や変数は滅多に使わないから用意してない。欲しければ `:redir` 使え」とあります。
滅多に使われないと言う理由だけで直接アクセスする関数を用意してもらえないような方針だと、`:redir` を使わないように、と言うのはかなり険しい道になりそうです…。

**Comment by Shougo** [comment]
現状、:redirを使わないとvimの内部構造にアクセスできませんからね……。
後付けだからでしょうが、Vim scriptは関数が少なすぎます。

**Comment by Shougo** [comment]
verbosefileをredirの代わりに使うことは可能ですが、現在のverboseファイルの仕様だと冗長な出力を含めて全て出力されてしまいます（verboseレベルが無視される）。この仕様を何とかしない限り、redirのネスト問題を解決するのは難しいです。

とりあえず、私は実装を見てみます。

**Comment by Shougo** [comment]
verbosefileの実装はsrc/message.c中のverbose_open()とverbose_stop()ですね。
verbose_fdという変数にファイルポインタが格納されています。
message.cを読んでみたものの、verbosefileだと全てのメッセージが表示される理由はわからず……。

verbosefileはもともとデバッグ用の実装な感じがしますね。これを:redirの代わりに流用する場合には既存の互換性を壊さない仕様にする必要があるのかな。

**Comment by Shougo** [comment]
p_verboseがverboseオプションの本体でした。verbosefileに書き込まれる部分はだいたいわかったので、あとはp_verboseで振り分けている部分を調べれば良いはずだと思い調べてみたところ、各ソースコードでp_verboseのレベルによりメッセージを出すかどうか振り分けているようです。 verbosefileオプションをセットするとp_verboseが一時的に大きくなるのかと思っていたんですが、そういうコードは見当たらないなぁ……。

**Comment by Shougo** [comment]
最新版のVimの挙動がよくわからないので、再現コードを用意してみましょう。

**Comment by Shougo** [comment]
```
  let verbose = tempname()
  let [verbosefile_save, verbose_save] = [&verbosefile, &verbose]
  try
    let &verbosefile = verbose
    let &verbose = 0

    for command in split(join(a:args), '\n')
      silent! execute command
    endfor
  finally
    let [&verbosefile, &verbose] = [verbosefile_save, verbose_save]
  endtry

  let _ = join(readfile(verbose), "\n")[1:]
  call delete(verbose)
```

@thinca, @tyru 
んー、vimshellのvexeコマンドではこうやっていますね。とりあえず、これで代用してはいかがでしょう。

実装を見て見ましたが、グローバル変数がふんだんに使われており、redirのネストを許すのはまず無理です。

**Comment by mattn** [comment]
verboseに拘るから問題になるんじゃないですか？
例えば扱うアプリが統一されているならこういう方法もあるんじゃないですかね。

https://github.com/mattn/redir-vim

**Comment by koron** [comment]
なんだかこの機能(redirのネスト可能化)の考察は不毛に見える。

というのは私は今までの話から「redirを使う=Vimの内部情報を取得する」という感じに捉えてて、
だったらその「欲しい内部情報をredirではない直接的な方法で取得できるようにする」をやったほうが
マシ(早い&安全)なんじゃないかと。

逆に「Vimの内部情報を取得する」 **以外のユースケース** があるなら是非書いておいて欲しい。

**Comment by koron** [comment]
って、書くの二回目かw 前書いたの忘れてたw

**Comment by mattn** [comment]
![](http://www.odoru-legend.com/negotiator/news/img/dvd_mashita_l.gif)

**Comment by koron** [comment]
> 滅多に使われないと言う理由だけで直接アクセスする関数を用意してもらえない

過去に使われなかったから現在も使われないとするのは誤り&早計です。

加えてなぜそうなったのかを分析し、覆すだけの根拠を用意するのも取りうる方策の1つです。

**Comment by Shougo** [comment]
> なんだかこの機能(redirのネスト可能化)の考察は不毛に見える。
> 
> というのは私は今までの話から「redirを使う=Vimの内部情報を取得する」という感じに捉えてて、
> だったらその「欲しい内部情報をredirではない直接的な方法で取得できるようにする」をやったほうが
> マシ(早い&安全)なんじゃないかと。

はい。:redirが必要になるほとんどのケースに関してはそのとおりです。

> 逆に「Vimの内部情報を取得する」 以外のユースケース があるなら是非書いておいて欲しい。

ユースケースなのかは微妙ですが、必要になったのはvexeの実装ですね。これはコマンドの出力をバッファに出力する必要があったため、:redirの機能が必須でした。特殊ケースであり、一応verbosefileで対応できているのであまり考慮に入れる必要はないかと思います。

**Comment by Shougo** [comment]
> verboseに拘るから問題になるんじゃないですか？
> 例えば扱うアプリが統一されているならこういう方法もあるんじゃないですかね。
> https://github.com/mattn/redir-vim

はい。ただ、特別なredirを使うのを強制させるのは汎用的にコマンドの出力を取りたかった場合に問題になりそうです。
自分のプラグインの中で閉じている場合はそれでも良いかと。

**Comment by tyru** [comment]
> ユースケースなのかは微妙ですが、必要になったのはvexeの実装ですね。

補足ですが、vimshellのvexeのことですよね。

vimshellのvexeとはどういう機能かというと、`$`がvimshellのプロンプトだとすると、`$ :echo "hi"`のように`:`が先頭についている文字列をコマンドラインに入力してエンターを押すと`:`に続く文字列がExコマンドとして解釈され、echoなどの出力は(あたかも通常の外部コマンドの出力と同じように)プロンプトに続いて以下のように出力される便利機能だと聞きました。

```
$ :echo "hi"
hi
$
```

このケースは特殊化した関数を用意して解決するケースではないと思うので、自分もKoRoNさんの言う「『Vimの内部情報を取得する』 **以外のユースケース** 」だと思います。

> 逆に「Vimの内部情報を取得する」 **以外のユースケース** があるなら是非書いておいて欲しい。

**Comment by tyru** [comment]
あ、vimshellのvexeの話してたからvimshellの機能というのは伝わるか...余計なお節介でした... (機能までは書いてなかったけど)

**Comment by tyru** [comment]
> 今見つけたんですが、:help scriptnames-dictionary と言うのがありますね。
> ここには、「:scriptnames の結果を取得できるような関数や変数は滅多に使わないから用意してない。欲しければ :redir 使え」とあります。
> 滅多に使われないと言う理由だけで直接アクセスする関数を用意してもらえないような方針だと、:redir を使わないように、と言うのはかなり険しい道になりそうです…。

thincaさんが見つけたこのhelpの記載によると滅多に使わないとのことですが、以前[textobj-user](https://github.com/kana/vim-textobj-user)でまさにこの`:scriptnames`の出力を使っていて、いつだったか出力に含まれるパスが相対パスから絶対パスに仕様が変更されて、 **textobj-userを使ったプラグインが全滅** した記憶があります。
確かにtextobj-userみたいにkanaさんみたいなVimscript上級者しか`:scriptnames`の出力は使わないと言えば使わないですが、 **textobj-userはライブラリなので、影響範囲が結構でかいです。**
そこをなんとか説得材料として使えないかなーと思いました。微妙かもしれませんが。

**Comment by koron** [comment]
特殊な使い方の例(vimshell の vexe)をありがとうございます。
でもそれって execute() を新設すれば良いだけの話では?

**Comment by koron** [comment]
redir のネストを実装するのに近い手間になるかもだけどw

**Comment by tyru** [comment]
あーその発想はなかったです。
たしかにそれなら良さそうです。
もしそんな関数追加されたらかなりVimscriptの書き方変わりそうｗ

**Comment by thinca** [comment]
> execute()

redir のネストと本質的には同じですね。今回の目的の範囲だとこちらの方が便利そうです。

**Comment by koron** [comment]
内部状態の取得を関数化するのは、Vimの出力(gettexted)のパースを回避するためにはそれはそれで必要なので。
execute() とは別ということで。

**Comment by tyru** [comment]
あと、そういえば「`:redir`を使うのではなく、専用の関数がほしい」と思う部分として、マッピング周りで特に感じます。

#368 の[このコメント](https://github.com/vim-jp/issues/issues/368#issuecomment-16854591)の`s:create_mapopt()`みたいな関数を[eskk.vim](https://github.com/tyru/eskk.vim)や[emap.vim](https://github.com/tyru/emap.vim)で書いてるんですが、正直<del>このような関数</del><ins>(この関数は下で示す関数とはちょっと違いますが...)</ins>は組み込みであるとうれしいです...
もっと具体的に言うと、マッピングを作成する関数が欲しいです。

```
mapadd({dict}) or
mapadd({lhs}, {rhs}, {mode}, {opt})
{dict}：`maparg()`の返すものと同じ構造のDictionary
```

作成があるなら当然削除もほしいです。

```
mapdelete({dict}) or
mapdelete({lhs})
{dict}：`maparg()`の返すものと同じ構造のDictionary
```

参照は`maparg()`がすでにあるので要らないです。

**Comment by tyru** [comment]
ちょっとソースコード読んでできそうだったらパッチ書きます...>mapadd(), mapdelete()
今日は寝ます。

**Comment by mattn** [comment]
そもそもvimの評価系関数は式しか受け取らないってのが前提だと思ってます。(経験則)
なのでexecute()は蹴られる可能性がありますね。

**Comment by Shougo** [comment]
> そもそもvimの評価系関数は式しか受け取らないってのが前提だと思ってます。(経験則)
> なのでexecute()は蹴られる可能性がありますね。

そうなんですか。確かにVim scriptの関数は{expr}しか見たことが無いです。
ただ、実装前にアイディアだけ提示するというのは悪くはないと思います。

**Comment by Shougo** [comment]
> ちょっとソースコード読んでできそうだったらパッチ書きます...>mapadd(), mapdelete()
> 今日は寝ます。

確かに、動的なマッピングの生成だと現在はexecuteを使わないといけないので、関数でできるとかなり便利だと思います。

**Comment by koron** [comment]
おいおい。みんな大事なことを忘れてないかい?

「それテキスト編集の何に役立つんだよ」

これがないとどんな変更もアウトだぜ。

**Comment by Shougo** [comment]
> おいおい。みんな大事なことを忘れてないかい?
> 「それテキスト編集の何に役立つんだよ」
> これがないとどんな変更もアウトだぜ。

これはどっちについての話でしょうか。execute()? mapadd()/mapdelete()?

だいぶ話が分裂してきたので、このIssues自体は閉じてしまって、別のアプローチによるIssueを建てなおしたほうが良いような気がしています。本題である、:redirのネスト機能の実装は不可能でしょう。

**Comment by koron** [comment]
どちらもw

**Comment by mattn** [comment]
vimの評価関数(foldexpr)とかは、かならず関数呼び出しもしくは式になっていて、コマンドは実行できないようにしてるんです。

**Comment by koron** [comment]
@mattn 

> vimの評価関数(foldexpr)とかは、かならず関数呼び出しもしくは式になっていて、コマンドは実行できないようにしてるんです。

そうしているにも関わらず `execute()` でコマンドを実行できるようにすると
アーキテクチャ上の矛盾が生じるよ、と言いたいのですね。

だったら sandbox では `execute()` 実行できない or 失敗する、とかはどうか。

**Comment by mattn** [comment]
@koron いえいえそうじゃなくて、自分で関数作って関数呼び出しにすればいいよって話です。つまり自分で関数が作れる人にとってexecute()は意味がないという意味です。

**Comment by koron** [comment]
execute() にはコマンドを実行する機能だけではなく、そのアウトプットを安全にキャプチャーする機能を想定しています。
このissueの本意から後者のキャプチャーのほうがより重要で、redirをネスト可能にする修正や運用をするよりも筋が良いと考えています。

以上を考慮に入れてもなお

> execute()は意味がない

ですか?

**Comment by mattn** [comment]
それはもちろん意味があります。

**Comment by mattn** [comment]
ただ、 execute() という関数名は評価値を返す様に連想するので capture() がいいかな。

**Comment by koron** [comment]
`:execute` との対比(混乱)もありますしね。名前は追々。

**Comment by koron** [comment]
あと `eval()` もかw

**Comment by Shougo** [comment]
`:redir`は`:redir END`までのコマンドを全てキャプチャしますが、execute()は単一のコマンドしか実行できないという制限があると思います。そのかわり、redirよりは実装が簡単になるかと。

> どちらもw

!

**Comment by Shougo** [comment]
> おいおい。みんな大事なことを忘れてないかい?
> 「それテキスト編集の何に役立つんだよ」
> これがないとどんな変更もアウトだぜ。

プラグインの実装をするときに、その機能があると楽になるという変更なので、「直接テキスト編集の役に立つ」とはなかなか言えないです。

**Comment by koron** [comment]
編集の役に立つんだ、っていう理屈をでっち上げてください。

**Comment by tyru** [comment]
> > ただ、 execute() という関数名は評価値を返す様に連想するので capture() がいいかな。

@mattn 同意です。

> > :redirはredir ENDまでのコマンドを全てキャプチャしますが、execute()は単一のコマンドしか実行できないという制限があると思います。

@Shougo 確かに複数のExコマンドをListかなんかで渡せるとうれしいですね。

**Comment by Shougo** [comment]
> 編集の役に立つんだ、っていう理屈をでっち上げてください。

でっち上げる……。

**Comment by mattn** [comment]
ほいさ

https://gist.github.com/5449425

**Comment by mattn** [comment]
まだsandboxは入ってない。

**Comment by tyru** [comment]
> > 編集の役に立つんだ、っていう理屈をでっち上げてください。

ふと思ったのですが、
「redirをネスト可能にするのはとても難しいから、安全に出力を取得するために新しく関数追加するのはどう？」ってvim_devに投稿すれば案外Christianさん辺りが気合でredirをネスト可能にするパッチ書いてしまう気がしてきました…

**Comment by tyru** [comment]
@mattn 早い！

**Comment by mattn** [comment]
sandbox入れた。

**Comment by Shougo** [comment]
> ふと思ったのですが、 「redirをネスト可能にするのはとても難しいから、安全に出力を取得するために新しく関数追加するのはどう？」ってvim_devに投稿すれば案外Christianさん辺りが気合でredirをネスト可能にするパッチ書いてしまう気がしてきました…

そういう手もありますね。

> https://gist.github.com/5449425

早い。そしてこんな簡単に実現できるんだ、と思いました。:redirの実装はかなり複雑になっているので……。

**Comment by mattn** [comment]
ドキュメントも足した。一応、配列引数もサポート。

**Comment by Shougo** [comment]
はやい……

**Comment by mattn** [comment]
例外発生したときにいろいろ漏れてるので、やりたい人はテスト希望

**Comment by mattn** [comment]
あとたぶん

```
:echo capture("echo input('foo')")
```

とかいろいろ問題でると思う。

**Comment by koron** [comment]
素朴な疑問なんだけど強制 silent 状態にするのって妥当なのかなぁ?
画面にもでるけどキャプチャもするよ、みたいな動作は要らない?

**Comment by mattn** [comment]
なんとなくだけど、↑の僕の redir-vim を vim 自身がやれば全て解決する気がしてきた。

**Comment by koron** [comment]
あ、そうか。このパッチ capture() の中で capture() しちゃうと期待通りには動かないんじゃ?

**Comment by Shougo** [comment]
> 素朴な疑問なんだけど強制 silent 状態にするのって妥当なのかなぁ?
> 画面にもでるけどキャプチャもするよ、みたいな動作は要らない?

redir, verbosefileが画面に出さないので、この機能は画面に出さないとしても良いと思います。

**Comment by mattn** [comment]
> あ、そうか。このパッチ capture() の中で capture() しちゃうと期待通りには動かないんじゃ?

動くと思いますよ。

**Comment by koron** [comment]
期待する動作がどっちかわからないけど

``` vim
let a = capture("call capture(\"echo foobar\")")
```

みたいなことした時に `a` には `foobar` 入ります?

**Comment by mattn** [comment]
入らないですね。

```
let a = capture("echo capture(\"echo foobar\")")
```

なら入りますが。

**Comment by koron** [comment]
入らないならredirでやるのと、機能的には大差ないです。
たぶん redir-vim 的な「入る」動作が好ましいんじゃないですかね。

いや私には使う予定がないので指摘が正しいか保証できませんけどw

**Comment by mattn** [comment]
入らないのが欲しい機能だと思いましたが。

**Comment by Shougo** [comment]
あ、このパッチ動作がおかしいです。
capture()を呼ぶと恒久的にコマンドライン出力が表示されなくなってしまいます。
フラグを元に戻していないのかと。

**Comment by mattn** [comment]
↑でも書きましたが、エラーが出たり input() で誤動作するのは既知です。
ちょっと飽きたのでまた後で直しておきます。

**Comment by Shougo** [comment]
> 例外発生したときにいろいろ漏れてるので、やりたい人はテスト希望

了解です。例外をキャッチする必要があるんですね。

`let a = capture('ls')`
みたいなのはちゃんと動きました。redirを使う時と比べて、とてもわかりやすいですね。

**Comment by mattn** [comment]
メッセージが表示されなくなる件は直しました。

msg_silentってエラー起きると内部で++されっぱなしなのかw

**Comment by Shougo** [comment]
ありがとうございます。

> msg_silentってエラー起きると内部で++されっぱなしなのかw

なんと……。

**Comment by tyru** [comment]
> `let a = capture("call capture(\"echo foobar\")")`

で`a ==# 'foobar'`とならない動作を期待してた派です。
万が一ネストした`capture()`を書きたい場合、全部の出力を返す仕様より、引数で明示的に返したい(出力したい)文字列を選択できるので、そっちのがよさそうです。

> 素朴な疑問なんだけど強制 silent 状態にするのって妥当なのかなぁ?
> 画面にもでるけどキャプチャもするよ、みたいな動作は要らない?

`system()`も外部コマンドの出力が返らないので、`capture()`も自動的にsilentになるのがいいと思います。
そもそも関数はユーザ側で使う機能ではないと思うので、余計な出力はユーザに見せてほしくないです。

なので「今のパッチ + 誤動作を修正」したバージョンでいいと思います。

**Comment by mattn** [comment]
メッセージが表示されない件は直ってるので、input() をどうするかですかね。

**Comment by tyru** [comment]
↑まだ`mapadd()`しか作ってないですが、別issueとして立てました。

**Comment by tyru** [comment]
Vimscriptのinputsave()/inputrestore()に対応する関数を開始/終了時に呼ぶとinput()とかを呼び出されてもうまく行くでしょうか？
2013/04/24 20:48 "mattn" notifications@github.com:

**Comment by Shougo** [comment]
@tyruさん

懸念があるなら、サンプルコードを上げてみてはどうでしょうか。
コードがあれば私も試してみようかと思っています。

**Comment by tyru** [comment]
了解です。forkして修正してみます。
(その前にMQの使い方ググってみます。 #374 の修正もまだcommitしてない状態なので)

**Comment by tyru** [comment]
MQについて調べてみました。MQ便利。
[Mercurial MQ について](http://d.hatena.ne.jp/dayflower/20090520/1242794877)

mattnさんのgistを`hg import -f gistfile.diff`して適用しました。
forkもしましたが、その前に動作確認したところ、なんだか戻り値がおかしいです。

```
:echo capture('echo "hi"')
" "hii"と出力される
:echo capture('echo "hoe"')
" "hoeoee"と出力される
```

**Comment by mattn** [comment]
あれ、なんか変ですね。
動いてたと思ったけど。

**Comment by mattn** [comment]
あーわかった。

**Comment by mattn** [comment]
直しました。

**Comment by mattn** [comment]
```
:echo capture("echo input('foo')")
```

で落ちるな。

**Comment by mattn** [comment]
落ちる件は修正。あとは input() を画面に出すかどうか。

**Comment by mattn** [comment]
現状のパッチの作りだと、プロンプトの表示もキャプチャ対象になっちゃうのでもし出すならやり方変えないといけないかな。

**Comment by tyru** [comment]
最新パッチ試したら出力直ってました。

> ```
> :echo capture("echo input('foo')")
> ```
> 
> で落ちるな。

自分の所では落ちないですが戻り値か出力か分かりませんが、コマンドラインに`echo input('foo')aaaaaa`みたいに表示されます。
どっちにしてもやり方変えないといけないんですかね。(forkしといてどう直せばいいのか見当ついてない)

**Comment by mattn** [comment]
元々の動きとして

```
:silent let a = input("foo")
```

のfooは表示されないので、それと同じ動きになっているだけの話です。

**Comment by tyru** [comment]
なんと...!
知りませんでした。

**Comment by mattn** [comment]
silent 時の input() はこのパッチとは関係なかったりするので、一度提案してみようと思いますが、どうでしょう？

**Comment by Shougo** [comment]
パッチを出すことに賛成します。Vim 7.4に入ると良いですね。

**Comment by mattn** [comment]
時期的にもう入らないんじゃないかと

**Comment by Shougo** [comment]
現在の7.3に新機能は難しいですが、7.4のときのマージウインドウが開いた時なら可能性はあるかと思います。

**Comment by mattn** [comment]
よく見たら本来の目的の `capture("function")` が取れてないすな。

**Comment by mattn** [comment]
なるべくグローバル変数増やしたくなかったけどしょうがない...

**Comment by mattn** [comment]
治った。提案文書きます。

**Comment by mattn** [comment]
投げました。

https://groups.google.com/d/msg/vim_dev/H3Z3ChSUh_4/beZs6KzYdBsJ

**Comment by mattn** [comment]
タイトル修正しました。

**Comment by Shougo** [comment]
mattn++;

**Comment by Shougo** [comment]
本日、vim_devの該当スレッドに援護射撃しようと思います。

vim_devの論客二人とのガチバトル（英語）となるので、できれば利点をまとめておいてくれると嬉しいです。

とりあえず、私が思うところだと
1. コマンド(`:redir`)よりも関数(`capture()`)のほうがプラグイン内で使いやすい
2. `:redir`に手を加えないので、既存のスクリプトが動かなくなる可能性はない
3. そもそも、`:redir`の修正にはパッチがない（ですよね？）。今ここにあるパッチのほうが重要性が高い。
4. `:redir`を直したいなら、別で議論すべき
5. `:redir`よりもやりたいことがわかりやすい
6. そもそも`:redir`はデバッグ目的なのでは？

**Comment by osyo-manga** [comment]
個人的に思いついた `capture()` を使用する利点や使用したいケースを上げておきます。
何かの参考になればと。
- `:redir` を使用するよりもコードが簡潔である
- 関数なので Vim script で扱いやすい
- コマンドから直接呼び出すことが出来る
  - コマンドから直接変数に設定したり
  - `:let hoge = capture(":mes")`
- 関数の引数の式に渡すことが出来る
  - `:echo remote_expr("GVIM1", "capture(':mes')")`

**Comment by Shougo** [comment]
了解です。確かに具体例があるとわかりやすいですね。

**Comment by Shougo** [comment]
mattnさんがvim_devに投稿していたので、私も援護射撃をしてきました。さて、あとは流れがどう変わるか……。

**Comment by k-takata** [comment]
7.4.1996 で `evalcmd()` というものが入りましたが、これってもしかして!?
https://groups.google.com/d/topic/vim_dev/UYo8EBugQgI/discussion

**Comment by k-takata** [comment]
`capture()` とは違って、文字列のリストは受け付けないのか。ただ、"\n" で区切れば複数コマンドを渡せるみたい。

**Comment by k-takata** [comment]
`capture()` とは違ってコマンドの出力は表示される。
あと、サンドボックスのチェックが入っていない。

**Comment by mattn** [comment]
> あと、サンドボックスのチェックが入っていない。

そ　れ　は　こ　わ　い

**Comment by mattn** [comment]
silent を付ければいいって事なんかな。ところで redir を弄ってるのでネストできない件は同じな気がするなー。

**Comment by k-takata** [comment]
サンドボックスと、文字列のリストについては指摘しました。
https://groups.google.com/d/msg/vim_dev/UYo8EBugQgI/keUzmMPiCQAJ
ネストしたときの動作はよく把握していないので、必要ならば指摘をお願いします。

**Comment by k-takata** [comment]
7.4.2000
https://groups.google.com/d/msg/vim_dev/Qlldv0enUI8/F56OmJ7-CQAJ
evalcmd() の中で :redir は許可しないのか。

**Comment by k-takata** [comment]
Bramはサンドボックスのチェックは不要だと言っていますがそういうものなのかな？
あと、evalcmd() の中で :redir は許可していないのは、入れ子になったときの仕様をちゃんと定義していないので、まずはエラーにしているらしい。

**Comment by mattn** [comment]
indentexpr なんかで指定しても、その中で実行するコマンドがsandboxだったら問題ないだろ？って事なんですかね。

**Comment by k-takata** [comment]
7.4.2008で execute() に名前が変わって文字列のリストも受け付けるようになったようです。
https://groups.google.com/d/topic/vim_dev/eW-PiiWQCrI/discussion

**Comment by k-takata** [comment]
`:redir` がネストできない仕様は変更ありませんが、`execute()` が追加されてネストできるようになっているので、閉じます。
(`execute()` の中で `:redir` が使えない点は注意。)
