### ISSUE TITLE
encodeing=cp932(or sjis)でファイル名が260Byte以上のファイルを開くと内容を消失する

### ISSUE THREAD

**Issue by nocd5** [vim-jp/issues#650]
Windowsでファイル名が『あああ…(×128).txt』など260Byte以上のファイルを
vimのencoding=cp932またはShift-JISの状態で開くと
ファイルの内容が消えます。
これは保存するか否かに関わらず、開いた時点で内容が消えます。
encoding=utf8の場合はバグは発生しません。

以下の環境で不具合動作を再現
- vim 32bit 7.4.000@Windows8.1 64bit
- vim 32bit 7.4.465@Windows8.1 64bit
- vim 32bit 7.4.465@Windows7sp1 64bit
- kaoriya版vim64bit 7.4.444@Windows8.1 64bit

`-n`でファイルが消えないのでスワップファイルが悪さしてる？
○:正常動作 ×:不具合動作

| encoding | 起動オプションなし | -R | -n | OSで読み出し専用設定 | -c "se enc=utf8" | -c "se enc=cp932" |
| :-: | :-: | :-: | :-: | :-: | :-: | :-- |
| cp932 | × | ○ | ○ | ○ | × | - |
| utf-8 | ○ | ○ | ○ | ○ | - | ○ |

**Comment by mattn** [comment]
ランタイムが扱えるファイル名の長さの最大が _MAX_PATH (260) だからです。encoding=utf8 の場合でも同じ問題、もしくはほかの箇所で問題は出るかと思います。

http://blogs.wankuma.com/tocchann/archive/2007/05/17/77107.aspx

**Comment by k-takata** [comment]
ANSI APIを使っているはずなのに、260byte以上のファイル名が作成されるというのが不思議ですね。
`mch_fopen()` が上書きモード `"w"` で呼ばれて、そこでファイルが 0 バイトにクリアされているようです。`fopen()`の内部でANSI -> Unicode変換しているのでしょうか。
260byteに満たないファイル名だと、`mch_fopen()` が呼ばれないようです。

**Comment by k-takata** [comment]
encoding=utf8 の場合は、WCHARに変換した状態で 260文字 まで扱えるのが期待値でしょう。
しかし、swapfile 名がぶった切られているようです。

**Comment by k-takata** [comment]
むむむ、CreateFileA で 260byte を超えるファイル名が作成できるぞ!? 知らなかった。

**Comment by k-takata** [comment]
ファイルが空になる原因が判明した模様。
memline.c の `findswapname()` の以下の部分で、

``` C
    /*
     * If we start editing a new file, e.g. "test.doc", which resides on an
     * MSDOS compatible filesystem, it is possible that the file
     * "test.doc.swp" which we create will be exactly the same file. To avoid
     * this problem we temporarily create "test.doc".  Don't do this when the
     * check below for a 8.3 file name is used.
     */
    if (!(buf->b_p_sn || buf->b_shortname) && buf_fname != NULL
                         && mch_getperm(buf_fname) < 0)
    dummyfd = mch_fopen((char *)buf_fname, "w");
```

`mch_getperm()` が 260byte 以上のファイル名を扱えず、ファイルの有無に関わらずエラーを返すので、上書きモードで `mch_fopen()` が呼ばれます。その中で最終的に `CreateFileA()` が呼ばれるわけですが、なぜか 260byte 以上のファイル名も扱えて、空のファイルで上書きされてしまいます。

**Comment by k-takata** [comment]
encoding != utf-8 の時は、`mch_fopen`, `mch_open` でファイル名の長さをチェックして `_MAX_PATH` 以上の時はエラーにするのがいいだろうか？

**Comment by nocd5** [comment]
たまたま他のソフトの不具合対応で遭遇したバグなので通常は遭遇しないと思いますが、開いた瞬間ファイル内容が消えるのは痛いと思うので、エラーにしてくれた方がいいと思いますね

**Comment by k-takata** [comment]
こんな感じにしますか？
https://bitbucket.org/k_takata/vim-ktakata-mq/src/62e89004e11c65d17d2a8397792311916c2b33a9/fix-long-filename-with-ANSI-API.patch
まだ動作確認していませんが。

**Comment by ynkdir** [comment]
なんかあちこち問題でそうなケースですね。

CreateFile() で試した感じだと MAX_PATH の制限はバイト数じゃなくて文字数で、絶対パスの長さみたいです (相対パスを指定した場合でも)。stat() が失敗してるのはおそらく中で FindFirstFileEx() が失敗してるからでこっちは MAX_PATH はバイト数みたいです (WIN32_FIND_DATA.cFileName[MAX_PATH] これ関係？)。

関係ないですが挿入モードのファイル名補完で落ちました。

```
> echo hello, worldl > あ...x150....txt
> gvim -u NONE --cmd "set enc=utf-8"
i<C-X><C-F>nnnnnnnn...
SEGV
```

あとこういう手順も

```
c:\Users\yukihiro\tmp\あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ>echo hello, world > aaaaaaa.txt
c:\Users\yukihiro\tmp\あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ>gvim -u NONE --cmd "set enc=utf-8" aaaaaaa.txt
SEGV
```

**Comment by ynkdir** [comment]
k-takata さんのパッチ試してみました。
`:e ...` => (ファイルが開けないので) 新規ファイルあつかい。スワップファイルが開けないエラー。
`:w` => E212: Can't open file for writing

**Comment by nocd5** [comment]
私もパッチを試してみました。
`enc=cp932`で(あ×128).txtを開いた場合

```
$ vim (あ×128).txt    => E303エラー
$ vim -n (あ×128).txt => 新規ファイル扱い。:wはE212エラー
$ vim -R (あ×128).txt => 新規ファイル扱い。:w!はE212エラー
```

いずれの場合もファイル内容が消えることはありませんでした。
`enc=utf8`の場合はこれまで通りファイルの読み書き可能でした。

ファイル内容が消えるのが一番致命的な問題だった思うので、僕自身はこのパッチでOKだと思います。

**Comment by ynkdir** [comment]
常にW系を使うようにするのはどうですか

``` diff
diff -r b53b469a7bea src/os_mswin.c
--- a/src/os_mswin.c    Thu Sep 11 22:50:09 2014 +0200
+++ b/src/os_mswin.c    Sat Oct 11 12:08:56 2014 +0900
@@ -633,1 +633,1 @@
-    if (enc_codepage >= 0 && (int)GetACP() != enc_codepage
+    if (enc_codepage >= 0
```

まあこれもあやしいですが

**Comment by k-takata** [comment]
それは1回試したのですが、`setlocale()` をどこかで呼んでおかないと w系のCRT関数はちゃんと動かないという問題がありました。で適当にそれを呼んだ上で、`fopen`, `open`, `stat` を、w系を使うようにしてみたのですが、別のところでエラーが出てしまいました。

**Comment by ynkdir** [comment]
setlocale() は初期化で呼ばれないですか。でもまあ呼んでもエラーでるならどっちみちだめですねえ。

上のクラッシュの件は2番目はソースを最新にしたらクラッシュしなくなりました。ただしファイルを開けない/保存できないという動作になります。

**Comment by k-takata** [comment]
コメントをちょっと修正。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c369f75efa255de035553fc834aa44a42fbfb51a/fix-long-filename-with-ANSI-API.patch
MAX_PATH バイト以上、MAX_PATH 文字未満の長いファイル名を扱いたいときは、enc=utf-8 で使うということでいいんじゃないですかね。

**Comment by ynkdir** [comment]
はい、いいと思います。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/N10OYqPMvy0/discussion

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/N10OYqPMvy0/OAEvzzUGUPQJ

> Can't we fix the places that are restricted to MAX_PATH bytes?  If this
> is 256 bytes that's quite short.  Perhaps we can change a few places to
> use MAX_PATH \* 2, since this appears to be a problem with double-byte
> encodings only.
> 
> We could check somewhere that MAX_PATH is 256, and then define another
> variable to 512.  Perhaps MAX_PATH_BYTES. 

さて、何て返しますか。
とりあえず、MAX_PATH は 256 ではなく、260 ですね。

**Comment by nocd5** [comment]
> とりあえず、MAX_PATH は 256 ではなく、260 ですね。

ファイル名の最大長256文字と勘違いしているのかもしれませんね。

ゴールがちょっと違うのでしょうか。
ファイル名が260バイト以上のファイルが存在するなら それも扱えるようにしたい、と考えているのであればMAX_PATH*2にしてしまうのも理解できますかね。

**Comment by k-takata** [comment]
MAX_PATH \* 2 にしたところで、結局全てのファイル入出力API/CRT関数をWide版に変更しないと、根本解決にはならないですよね。で、そこまでやるくらいなら enc=utf-8 でいいんじゃないかと。

**Comment by k-takata** [comment]
返信done
https://groups.google.com/d/msg/vim_dev/N10OYqPMvy0/r2dxi-Crr60J
同じことをもう1回書いただけのような気もしますが…。

**Comment by ynkdir** [comment]
> とりあえず、MAX_PATH は 256 ではなく、260 ですね。

ファイル名の長さの制限 (255 + 1) とたぶんごっちゃになってそう。

サロゲートペアとか考えてませんでしたが MAX_PATH は UTF-16 での長さみたいなので気にしなくてもよさげ。

ちなみに MAX_PATH は NUL 終端を含んだ長さで 259 + 1 ぽいですね。だから char/wchar_t buf[MAX_PATH + 1] はまずいのかもしれないです。

**Comment by k-takata** [comment]
MSが言うところの MAX_PATH 文字とは、UTF-16 の code unit の数（code point ではなく）、あるいは WCHAR の数と考えればよいはずです。

> だから char/wchar_t buf[MAX_PATH + 1] はまずいのかもしれないです。

バッファを余分に確保しておく分にはあまり問題はないと思います。
逆に、enc=utf-8 の時に1文字足りないパターンが見つかりました。（別issueにした方がいいかも）
https://bitbucket.org/k_takata/vim-ktakata-mq/src/70c4e9b371665fd4a40b101cd0c1550e0315d116/fix-opening-259-chars-filename.patch
パスが259文字だと、ファイルが正しく開けず、空のファイルとして開かれてしまいました。（元々の問題とは異なり、データの破壊はされません。）

**Comment by k-takata** [comment]
> （別issueにした方がいいかも）

ということで、別issueを立てました。

**Comment by k-takata** [comment]
todo入り

> Fix that on MS-Windows MAX_PATH in bytes causes problems for file names
> between MAX_PATH and double that for double-byte encodings. (Ken Takata, 2014
> Oct 15)

**Comment by k-takata** [comment]
7.4.505
https://groups.google.com/d/topic/vim_dev/MdEMSrQp0u8/discussion
