### ISSUE TITLE
modifiedでhiddenなバッファaがある場合、modifiedなバッファbから:q!を繰り返しても、バッファaとbが交互に出てきてvimを終了できない

### ISSUE THREAD

**Issue by deton** [vim-jp/issues#651]
期待した動作と違って気になったので報告します。
こういう仕様なのかもしれないとも思いつつ。
## 再現手順

```
vim -u NONE --noplugin -o a b
" (1)バッファaとbを編集
aa\<ESC>\<C-W>jab\<ESC>
" (2)バッファbだけ表示。バッファaはhide
:only!
" (3)バッファbを保存せず閉じる。バッファaがactiveになる
:q!
" (4)バッファaを保存せず閉じる
:q!
```
## 期待する動作

(4)でvimが終了
## 実際の動作

(4)の後バッファbがactiveになり、(3)に戻る。
:q!を繰り返すだけではvimを終了できない。
## 回避方法
- :sp #した後2回:q!すればvim終了可能。
- (3)で:q!のかわりに:bunload!や:bdelete!すれば、(4)でvim終了。
- :qa!ならvim終了可能。
## 環境

vim 7.4.430, Debian GNU/Linux sid (i686)

**Comment by mattn** [comment]
これが仕様だと言われるかもしれませんが、一応パッチ。

https://gist.github.com/mattn/cb146874e4bfb663f150

**Comment by deton** [comment]
ありがとうございます。
パッチを試してみましたが、(3)の時点でvimが終了するようになってしまいました。

ヘルプ等の記述を見ても:qa!を使ってくれ、という雰囲気な気もします。>仕様
(でも:qa!だとうっかり必要な編集まで破棄しそうなので、:q!で確認しつつ閉じて行きたい気はします)

**Comment by mattn** [comment]
b で `q!` した時に b を閉じてしまうのがいいんでしょうかね。

**Comment by mattn** [comment]
https://gist.github.com/mattn/e618a8923dbba4da73ea

裏にバッファがある場合は bw! 相当にしてみました。

**Comment by h-east** [comment]
`:quit`のヘルプに「カレントウィンドウを閉じる」と書いてあるので、現状の動作で良いと思いました。
`:q!`して`E162`が出たら、`:w` するか `:bw!` するか丸ごと `:qa!`する感じで。

E162のヘルプに`:bw!` の記述を追加すると親切かも。

**Comment by deton** [comment]
> 裏にバッファがある場合は bw! 相当にしてみました。

期待通りの動作になりました。
(:splitしている場合と同様に、modifiedなバッファの両方で:q!すればvim終了)

**Comment by koron** [comment]
僕は @h-east さんの意見に :+1: です。

`:q!` の動作を `:bw!` に変えるのは筋悪だと感じました。
それが必要なら最初から `:bw!` 使えば良いので。

**Comment by 0xBADDCAFE** [comment]
スクリプトでよしなに出来そうな感じもあります。

現状の動作であるべきだと思うんですが、

> :sp #した後2回:q!すればvim終了可能。 

これと同じ動きで無いのは気になります。どちらかというとウインドウを
閉じるという役割上は、`:sp #` した後 2 回 `:q!` しても vim が終了
されないと一貫性があるような気はするんですが。

`:q!` がウィンドウを閉じるといいつつバッファも破棄するパターンがある
のがややこしいんですよね。

あとパッチについて些細なことではあるんですが、対象が無名バッファでない、
既に存在するファイルを編集しているパターンを考えると `:bd!` でなくて
いいのかどうかというのがありそうです。1 枚目を閉じた後、`<C-^>` 出来るか
どうかという程度ですが。

**Comment by koron** [comment]
基本的な動作の話なんで、
互換性の観点からは変えるべきでない、
ということもできますね。

ならばオプションで変更可能、くらいやればacceptableだろうと、
言い換えることもできそうです。

**Comment by h-east** [comment]
ヘルプの真意が分かった気がする。

``` vim
:q[uit]!                Quit without writing, also when visible buffers have
                        changes.  Does not exit when there are changed hidden
                        buffers.  Use ":qall!" to exit always.
```

これを補足付きで日本語訳にすると以下になります。

``` vim
:q[uit]!                可視なバッファ(==カレントバッファ)に変更点があっても書き込み
                         をせずにカレントウィンドウを閉じる。
                        (ウィンドウが1つの時は)隠れバッファに変更点があると(Vimを)終
                        了しない。(かつ変更のある隠れバッファへ移動する。)
                        必ず(Vimを)終了するにはコマンド ":qall!" を使うこと。
```

隠れバッファに変更点があるかどうかのチェックはウィンドウが1つの時しかおこなわれないです。
これを踏まえると各動作すべて辻褄があっていると思います。

> :sp #した後2回:q!すればvim終了可能。

この場合は、`:sp #`でウィンドウが2つになりますから最初の`:q!`ではバッファbが破棄される。次の`:q!`はウィンドウが1つなのですが、隠れバッファがない(==隠れバッファに変更点がない)のでVimが終了される。

ということで、現状の動作はそのままの方が良いのではないかと思います。
`:q!`のhelp(English)を加筆修正した方が良い気はします。

**Comment by h-east** [comment]
反応が欲しいですね。

**Comment by deton** [comment]
現状の動作はこういう仕様と言われれば理解できなくはないので、
こういうものと思うことにします。
ありがとうございました。

積極的に変えたほうがいいという意見も出ないようなので、クローズします。

**Comment by h-east** [comment]
@deton 了解しました。ありがとうございます。
:q! のhelpに補足するpatchを投げてみようかと思ってます。

**Comment by mattn** [comment]
Bram に動作についても説明した方が良さそうですね。もしかしたら期待してる動作じゃないかもしれないし。

**Comment by h-east** [comment]
help修正案です。どうでしょうか。
(help修正ミッションの為、Issue reopenします)

``` diff
diff -r 9dff716fb9aa runtime/doc/editing.txt
--- a/runtime/doc/editing.txt   Thu Nov 06 10:03:01 2014 +0100
+++ b/runtime/doc/editing.txt   Sun Nov 09 06:39:37 2014 +0900
@@ -1080,9 +1080,11 @@
            the last file in the argument list has not been
            edited.  See |:confirm| and 'confirm'.  {not in Vi}

-:q[uit]!       Quit without writing, also when visible buffers have
-           changes.  Does not exit when there are changed hidden
-           buffers.  Use ":qall!" to exit always.
+:q[uit]!       Quit without writing, also when current buffers have
+           changes.  Does not exit when this is the last window
+           and there are changed hidden buffers. In this case,
+           current buffer change to the changed hidden buffer.
+           Use ":qall!" to exit always.

 :cq[uit]       Quit always, without writing, and return an error
            code.  See |:cq|.  Used for Manx's QuickFix mode (see
```

@mattn 了解です。

**Comment by h-east** [comment]
vim_devにdocument patchを投げました。
https://groups.google.com/d/msg/vim_dev/GNHCrlAkD3Y/j-5eTajH2JsJ

**Comment by h-east** [comment]
Bram氏から返事があって @deton さんの期待する動作に仕様変更になりそうです。
patchは私が週末に書くつもりです:muscle:

**Comment by mattn** [comment]
僕のパッチの DOBUF_DEL を DOBUF_UNLOAD にすればその動きになる気がする。

**Comment by mattn** [comment]
https://gist.github.com/mattn/d112b0449456fdb3c2da

```
vim -o a.txt b.txt c.txt 
:bufdo set modified
:hide  (a.txt を隠す。まだmodified) 
:buffers
:buffers
  1 #h + "a.txt"                        line 1
  2 %a + "b.txt"                        line 1
  3  a + "c.txt"                        line 1
:q!    (b.txt のmodifiedが外れて c.txt が見える) 
:buffers
  1  h + "a.txt"                        line 1
  2 #    "b.txt"                        line 1
  3 %a + "c.txt"                        line 1
:q!    (c.txt のmodifiedが外れて a.txt が見える)
:buffers
  1 %a + "a.txt"                        line 1
  2      "b.txt"                        line 0
  3 #    "c.txt"                        line 1
:q!    (終了) 
```

**Comment by k-takata** [comment]
h-east さんの指摘が反映されたので、ドキュメントの再修正も必要ですね。

**Comment by mattn** [comment]
@h-east これでよければ「ドキュメント、戻しておいて」というコメントと共に送ってしまいますが、いかがでしょうか？

**Comment by h-east** [comment]
@mattn 今、動作確認したりソース見まくれる環境にないので夜まで待ってもらえますか？
patchについて1点、ここではdo_bufdel()よりはclose_buffer()を呼んだ方がいい気がします。

**Comment by mattn** [comment]
パッチ更新しておきました。帰ったらチンして食べて下さい。

　　　　　　　　　　　　　　　　　　　　　　　　　母より

**Comment by h-east** [comment]
母ちゃんありがとう!
ついでに`curbuf = buf;`の行要らなくなるのと、close_buffer()の第2引数が`buf`になるんちゃうかと思いました。母ちゃんなら分かってくれると思ってた...

**Comment by koron** [comment]
ﾏｻﾞｺﾝ…

**Comment by mattn** [comment]
check_changed_any、curbuf を壊すのよ。

**Comment by h-east** [comment]
あー、そうですね。失礼。
私はcheck_changed_any()呼ぶ前にclose_buffer()を呼ぶソリューションを考えていたのですが(構想のみ)、むずいですかね？

**Comment by h-east** [comment]
@mattn 今日は仕事場の飲み会だったのすっかり忘れてましたー。すんません。
patch送っちゃってくだっしー。ヒャッハー

**Comment by mattn** [comment]
> 私はcheck_changed_any()呼ぶ前にclose_buffer()を呼ぶソリューションを考えていたのですが(構想のみ)、むずいですかね？

そこ見てみます。

**Comment by h-east** [comment]
mattnさんが昨日vim_devにpatchを投げたのですが、今朝いい感じの修正方法を思いついたのでpatchを作って投げました。(ドキュメントの修正も含む)
https://groups.google.com/d/msg/vim_dev/GNHCrlAkD3Y/CRpODEJHtegJ

**Comment by k-takata** [comment]
todo入りです。

> ":q!" should reset modified flag for current buffer, if another buffer is
> modified no need to abandon it again.
> Patch from Yasuhiro Matsumoto, 2014 Nov 21.
> Update from Hirohito Higashi, 2014 Nov 21.
> With test, Nov 23.

**Comment by h-east** [comment]
Issue立ってから1年ちょっと経ちましたがようやく取り込まれました。ありがとうございました。

Patch 7.4.1037
https://groups.google.com/d/msg/vim_dev/phZkt78-eKQ/9xrMQ0MBAgAJ

**Comment by 0xBADDCAFE** [comment]
この issue 最近見た気がするのにもう 1 年経ってたなんて…。
