### ISSUE TITLE
循環参照表現が正しくない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#652]
``` vim
let a = {}
let a["a"] = a
echo a
```

```
{'a': {...}}
```

これはOK。しかし

``` vim
let a = {}
echo [a,a,a]
```

```
[{}, {...}, {...}]
```

これや

``` vim
echo repeat([[]], 3)
```

```
[[],[...],[...]]
```

これはNG。
循環参照を copyID で確認しているけど、それを戻していないので１番目の copyID がそのまま使われている。

https://gist.github.com/mattn/d9deb113d7325d7119fe

**Comment by thinca** [comment]
:+1:

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/LfMh2WGpx2o

**Comment by k-takata** [comment]
7.4.1862
https://groups.google.com/d/topic/vim_dev/JC9UepBYEjw/discussion
