### ISSUE TITLE
バッファを閉じたあと previewwindow が伝搬する

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#654]
再現手順

```
$ vim -u NONE -N
sp
setlocal previewwindow
bw!
```

残ったウィンドウは nopreviewwindow であるべきだが previewwindow になっている。
previewwindow はウィンドウローカルなので、`bw!` で閉じられた後の残ったウィンドウには伝搬しないと思うのですが、伝搬してしまっている。
これが原因で以下のよくあるコーディング風景でエラーが出る。
1. `set completeopt=menu,preview`
2. 適当なファイル foo.c を開く
3. 適当なコード補完を行う(プレビューウィンドウが表示される)
4. コード補完をやめる(プレビューウィンドウは表示されたまま)
5. タグジャンプ等で別のバッファを一面で開く
6. `bw!` (プレビューウィンドウが見える) (そもそもここがおかしい感)
7. プレビューウィンドウでも `bw!`
8. 残った foo.c が previewwindow になっている。
9. そのまま補完を行うと E37 (No write since last change (add ! to override))

**Comment by ynkdir** [comment]
普通のウィンドウが先に閉じてるみたいです。
同じバッファを開いている他のウィンドウを閉じてからカレントウィンドウを処理するみたいな感じでしたっけたしか。わかりませんが。

``` vim
$ vim -u NONE -N
:let w:id = 1
:sp
:let w:id = 2
:setlocal previewwindow
:bw!
:echo w:id
2
```

**Comment by mattn** [comment]
コーディング風景でいえば同じバッファじゃないので変な感じですね。

On 10/17/14, Yukihiro Nakadaira notifications@github.com wrote:

> 普通のウィンドウが先に閉じてるみたいです。
> 同じバッファを開いている他のウィンドウを閉じてからカレントウィンドウを処理するみたいな感じでしたっけたしか。わかりませんが。
> 
> ``` vim
> $ vim -u NONE -N
> :let w:id = 1
> :sp
> :let w:id = 2
> :setlocal previewwindow
> :bw!
> :echo w:id
> 2
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/654#issuecomment-59518289

## 
- Yasuhiro Matsumoto

**Comment by ynkdir** [comment]
手順はこんな感じであってますか。

``` vim
$ cd /path/to/vim/src
$ ctags -R .
$ vim -u NORC -N --cmd "filetype plugin on" eval.c
### +------+
### |eval.c|
### +------+
Ocurwin-><C-X><C-O><Esc>u
### +-------+
### |preview|
### +-------+
### |eval.c |
### +-------+
:tag curwin
### +---------+
### |preview  |
### +---------+
### |globals.h|
####+---------+
:bw!
### +-------+
### |preview|
### +-------+
:bw!
### +------+
### |eval.c|
### +------+
```

**Comment by mattn** [comment]
はい。previewwindow の設定だけあればokです。

On 10/18/14, Yukihiro Nakadaira notifications@github.com wrote:

> 手順はこんな感じであってますか。
> 
> ``` vim
> $ cd /path/to/vim/src
> $ ctags -R .
> $ vim -u NORC -N --cmd "filetype plugin on" eval.c
> ### +------+
> ### |eval.c|
> ### +------+
> Ocurwin-><C-X><C-O><Esc>u
> ### +-------+
> ### |preview|
> ### +-------+
> ### |eval.c |
> ### +-------+
> :tag curwin
> ### +---------+
> ### |preview  |
> ### +---------+
> ### |globals.h|
> ####+---------+
> :bw!
> ### +-------+
> ### |preview|
> ### +-------+
> :bw!
> ### +------+
> ### |eval.c|
> ### +------+
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/654#issuecomment-59526864

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
現状の仕様を踏襲するのであれば window local option を退避した後で復帰するしかなかそうですかね。

**Comment by ynkdir** [comment]
あんまり違和感を感じなかったのでよくわからないです。
`:q` なら preview も閉じて終了ですが `:bw` ならこんな感じかなあと。
preview はほとんど使わないのであれですが。

**Comment by mattn** [comment]
ynkdir さんにい書いてもらった例だと、eval.c と previewwindow はそもそも同じバッファじゃないので、previewwindow で bw! しても eval.c には無関係だと思ったのです。

**Comment by ynkdir** [comment]
ローカルオプションの復元の話ですか？
ウィンドウにバッファをロードしたときに以前のローカルオプションが復元されるはずなのにローカルオプションである 'previewwindow' が元に戻らない、とうことですかね。

**Comment by mattn** [comment]
はい。その意味でした。

**Comment by ynkdir** [comment]
eureka!
でもそれだと逆にプレビューで開いたファイルを後で開いたらプレビューになるのは微妙な感じがします。

``` vim
:pedit foo
:pclose
:edit foo
:setl previewwindow?
```

**Comment by mattn** [comment]
うーむ。なんかこれで解決するのでそれでいいかーって感じがしてきました。

``` vim
autocmd BufWipeout * let &previewwindow = 0
```
