### ISSUE TITLE
showbreakを設定して三行以上折り返すと行頭付近でカーソル位置がおかしくなる

### ISSUE THREAD

**Issue by miyakogi** [vim-jp/issues#657]
おそらくVim本体のバグだと思うので、報告させていただきます。
現象はタイトルのとおりです。

再現手順

`vim -u NONE -N --noplugin`でvimを起動
`:set showbreak=----`
`200aa<ESC>`（画面幅に応じて値調整、三行以上の折り返しになるように）

三行目以降の行頭近くにカーソルを持って行くと、カーソルが突然showbreakの記号の上に飛びます。
カーソルが飛ぶ位置はshowbreakの文字数と同じようです。

![vim_showbreak1](https://cloud.githubusercontent.com/assets/3213998/4780060/d68cee98-5c55-11e4-93fd-8ec98d3247d7.png)

GVim、端末の両方で発生しました。
- 環境
  - (G)Vim 7.4.488 on Ubuntnu 14.04 64bit
  - kaoriya版 GVim 7.4.475 on Windows 7 64bit

**追記**
Vimのバージョン 7.4.472では発生しませんでした。
473のパッチでshowbreakが全体的におかしくなり、478のshowbreakの修正で本件が直りきっていないようです。

**Comment by h-east** [comment]
@miyakogi Issue登録ありがとうございます。こちらでも再現しました。
miyakogiさんがtwitterで呟いている通り、7.4.472では発生せず、7.4.473で発生します。

Patch 7.4.473
https://groups.google.com/d/msg/vim_dev/PT5NYPU_jIE/K6UF_2PEdHQJ

上記Patchの元の投稿が以下です。(`2)`の部分)
[patch] several problems with drawing overlong lines
https://groups.google.com/d/msg/vim_dev/oX0ZyQfoem8/gkqq8hZjdioJ

**Comment by miyakogi** [comment]
ご確認ありがとうございます。
twitterの件、最初の投稿の末尾に追記しました。

**Comment by h-east** [comment]
追記ありがとうございます。

いろいろ試してみたんですけどPatch 7.4.473で何が直ったのかよくわかんなかったです。

``` sh
$ vim -N -u NONE -c "se sbr=----" -c "se nu"
```

や

``` sh
$ vim -N -u NONE -c "se sbr=----" -c "se fdc=7"
```

を7.4.472, 7.4.473でいろいろ試してみたんですけど挙動の違いが見つけられなかった。

違いの分かる方情報下さい。

**Comment by h-east** [comment]
あー、`sbr`に空白文字設定したら違いがでるのかも？
外出中なので晩に試そう。

**Comment by miyakogi** [comment]
7.4.472で何が問題だったのかはわかりませんでしたが、最初に送られているパッチと7.4.473のパッチで条件判定の順番が違うことがバグの原因のようです。
順番を最初のパッチと同じにした所、三行目以降のカーソル位置の問題は修正できました。

7.4.478で同じ箇所にマルチバイト文字の修正が入っていたので、それも含めて最新のパッチ(7.4.488)で`src/charset.c` の1187行めあたりを以下のように変更したところ、とりあえずカーソル位置は修正されているようです。

``` diff
diff -r 8bb4ca7fba40 src/charset.c
--- a/src/charset.c Wed Oct 22 22:09:01 2014 +0200
+++ b/src/charset.c Sun Oct 26 16:03:19 2014 +0900
@@ -1184,14 +1184,14 @@
    {
        col -= W_WIDTH(wp);
        numberextra = W_WIDTH(wp) - (numberextra - win_col_off2(wp));
+       if (numberextra > 0)
+       col = col % numberextra;
        if (*p_sbr != NUL)
        {
        colnr_T sbrlen = (colnr_T)MB_CHARLEN(p_sbr);
        if (col >= sbrlen)
            col -= sbrlen;
        }
-       if (numberextra > 0)
-       col = col % numberextra;
    }
    if (col == 0 || col + size > (colnr_T)W_WIDTH(wp))
    {
```

コードは全く理解せずに順番だけ入れ替えたので、不具合あるかもしれません。
申し訳ありませんが、ご確認お願いいたします。

**Comment by h-east** [comment]
@miyakogi 

> 最初に送られているパッチと7.4.473のパッチで条件判定の順番が違うことがバグの原因のようです。

鋭い！！それビンゴです。
`make test`も`ALL DONE`でしたし、私もやっとその辺りのソースの意味が理解出来てこのpatchで問題ないと判断しました。
patchをvim_devへ送りましょう。ご自分でされますか？

**Comment by miyakogi** [comment]
ご確認ありがとうございます。

> patchをvim_devへ送りましょう。ご自分でされますか？

送らせていただけるのであれば嬉しいのですが、私から送ってもよろしいでしょうか？
ほとんど @h-east さんにやっていただいたような気がします。
あと英語のメールなので少し時間がかかってしまうかもしれません・・・明日中には送れるように努力しますが・・・

**Comment by h-east** [comment]
今回は私が送りましょうか？
Patch書いたのはmiyakogiさんなのでAuthor名を教えて下さい。
あと折角なので`col = col % numberextra;` を `col %= numberextra;` に修正しません？

**Comment by miyakogi** [comment]
それでは、申し訳ありませんがお言葉に甘えさせていただいて、patchの送付お願いします。
名前を出していただけるのであれば、 "Hiroyuki Takagi" でお願いします。

> あと折角なのでcol = col % numberextra; を col %= numberextra; に修正しません？

その方がスッキリして良さそうですね。
Vimの慣習などで問題なければ修正お願いします。

**Comment by h-east** [comment]
vim_devに送信しました。
https://groups.google.com/d/msg/vim_dev/PT5NYPU_jIE/Ku0MjRGKjX8J

**Comment by miyakogi** [comment]
早い！名前まで入れていただいてありがとうございます！

**Comment by k-takata** [comment]
7.4.489
https://groups.google.com/d/topic/vim_dev/J41QbTRP26Y/discussion
前半しか入っていないようですが、合っているのかな？

**Comment by h-east** [comment]
@k-takata 

> 前半しか入っていないようですが、合っているのかな？

ほんとは後半部分も反映(削除)して欲しかったですが、特に害はないですし放っておこうと思います。

https://groups.google.com/d/msg/vim_dev/PT5NYPU_jIE/yIDbpoAUwaYJ
で

> Please look out for any other problems, this code has too many combinations of options.

と言っているので、落ち着いた頃に「もういい感じなのでこれ消そうぜ！？」とpatch投げるつもりでいます。:smile:

ということで閉じます。
@miyakogi 報告、調査、patchありがとうございました。Contribute Authorおめ:clap:
