### ISSUE TITLE
writefile() で append したい。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#658]
- vim で redir に依存しないでログ出力したい
- verbosefile は余計な物がでる

``` vim
call writefile(["foo"], "foo.log", "a")
call writefile(["bar"], "foo.log", "a")
```

これで

```
foo
bar
```

こう出力されて

``` vim
call writefile(["foo"], "foo.log", "ab")
call writefile(["bar"], "foo.log", "ab")
```

これで

```
foobar
```

こう出力されて欲しい。

**Comment by mattn** [comment]
https://gist.github.com/3c7bdb1fa2ace107888f

**Comment by thinca** [comment]
:+1:

**Comment by tyru** [comment]
:+1:

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/QT7yoI4QlA0

**Comment by Shougo** [comment]
:+1:

**Comment by k-takata** [comment]
todo入り

> Patch to add append mode to writefile(). (Yasuhiro Matsumoto, 2014 Nov 1)

**Comment by k-takata** [comment]
7.4.503
https://groups.google.com/d/topic/vim_dev/N63OtmjZwY8/discussion

**Comment by k-takata** [comment]
testdir以下のmakefileに修正漏れがあったようなので、パッチを投げました。
https://groups.google.com/d/topic/vim_dev/MppBKE3h6e4/discussion

**Comment by k-takata** [comment]
7.4.943
https://groups.google.com/d/topic/vim_dev/ANx1faQOMqs/discussion
