### ISSUE TITLE
特定の条件で関数内の関数が関数として認識されない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#659]
``` vim
function! s:x()
  echo 'before'
  let _a = {}
  function! _a.func()
  endfunction
  echo '<sfile>: ' . expand('<sfile>:~')
endfunction
```

ただ関数を定義するだけのはずですが、このファイルを `:source ~/test.vim` すると、以下のようになります。

```
<sfile>: /home/thinca/test.vim
/home/thinca/test.vim の処理中にエラーが検出されました:
行    7:
E193: 関数の外に :endfunction がありました
```

関数内であるはずの `echo '<sfile>: ' . expand('<sfile>:~')` の行が実行されています。
どうやら、 `function! _a.func()` の行が関数の始まりとして認識されていないようです。
以下、雑多な条件など。
- 辞書変数の名前が `_` で始まる場合のみ発生するようです。
  - 辞書変数の名前を `a` や `a_` などにしても問題ありませんでした。
- 辞書変数が `s:` のスコープの場合でも、同様に `_` で始まる名前(つまり `s:_a` など)で発生します。
- 辞書変数のスコープに `g:`、`b:`、`w:`、`t:`、`l:`(明示的につける) を指定した場合は発生しません。
- 外側の関数はグローバル関数でも同様でした。

**Comment by thinca** [comment]
すいません。辞書関数じゃなくても、`_` で始まっていれば `s:_a()` みたいな普通のスクリプトローカル変数でも発生するようです。

**Comment by ichizok** [comment]
`{x}()`, `s:{x}()`, `s:0()` とかもダメですね。

``` diff
diff --git a/src/eval.c b/src/eval.c
--- a/src/eval.c
+++ b/src/eval.c
@@ -22271,15 +22271,11 @@ ex_function(eap)
            {
                if (*p == '!')
                    p = skipwhite(p + 1);
-               p += eval_fname_script(p);
-               if (ASCII_ISALPHA(*p))
-               {
-                   vim_free(trans_function_name(&p, TRUE, 0, NULL));
-                   if (*skipwhite(p) == '(')
-                   {
-                       ++nesting;
-                       indent += 2;
-                   }
+               vim_free(trans_function_name(&p, TRUE, 0, NULL));
+               if (*skipwhite(p) == '(')
+               {
+                   ++nesting;
+                   indent += 2;
                }
            }

```

**Comment by thinca** [comment]
:+1:
余裕ができたらパッチ当てて確認してみたいですが、今ちょっと余裕がないので、問題なさそうなら vim_dev に投げちゃって良いと思います！(識者の人が見てくれると心強い)

**Comment by ichizok** [comment]
報告しました。

https://groups.google.com/forum/#!topic/vim_dev/M1xSekhmfHQ

**Comment by h-east** [comment]
@ichizok 報告後にすんません。
以前勝手レビューしたときに「最低限の構文エラーチェックはした方がいいかも」と思ったけどここに書くのを忘れてました。

trans_function_name()を使って関数名のチェックができたはず...

細かい部分は家に帰ってメモを見ないと思い出せない(汗)...夜帰ってから書きます。

**Comment by h-east** [comment]
家に帰ったけどメモなんかなかった...あれ？

trans_function_name()は呼んでいるけど戻り値をチェックしていないのでチェックした方が良いかもと思ったけど、その後 '(' のチェックしているので構文チェック的には問題なさそうですね。失礼しました。忘れて下さい。

Bram氏から返信ありましたね。

> Thanks, I'll check it out. 
> 
> Could you turn that example into a test?

**Comment by ichizok** [comment]
> Could you turn that example into a test?

こういう場合は `src/testdir` に新規で作成すればよいのでしょうか

**Comment by k-takata** [comment]
既存のテストによく似たものがあればそのファイルに追加するのがよいのでしょうが、無ければ新規追加でよいでしょう。（既存のものに追加するのは結構大変ですし。）
しばらく前までは、テストのファイル名は連番でしたが、最近は分かりやすい名前を付けるようになっています。

**Comment by k-takata** [comment]
todo入りです。

> Patch to fix recognizing function name. (Ozaki Kiichi, 2014 Nov 28)

**Comment by ichizok** [comment]
テストはこんな感じでいいでしょうか？
https://gist.github.com/ichizok/267bae46f179d72b27dc
https://gist.github.com/ichizok/e4787725e785e839f4ec

**Comment by ynkdir** [comment]
いいと思います。
gist のファイルを raw でダウンロードしたらファイル末尾の改行が付いてなくてそのままだとテストが失敗しました。

**Comment by ichizok** [comment]
> gist のファイルを raw でダウンロードしたらファイル末尾の改行が付いてなくてそのままだとテストが失敗しました。

修正して投稿しました。

**Comment by thinca** [comment]
7.4.549 で取り込まれたようです。

```
Patch 7.4.549
Problem:    Function name not recognized correctly when inside a function.
Solution:   Don't check for an alpha character.
```

しかしパッチにコントリビュータの名前が入ってないのが気になる…。

**Comment by k-takata** [comment]
リンク
https://groups.google.com/d/msg/vim_dev/wN1itj19WTU/ApfNxTdDkeoJ

**Comment by ichizok** [comment]
@k-takata ありがとうございます。

**Comment by mattn** [comment]
名前を入れ忘れたとのこと
