### ISSUE TITLE
カーソルキーの左、以降しかドットレジスタに記録されない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#661]
Ubuntu 7.4.x のgvimの入力モードで
`abc<LEFT>def` と入力すると dot register がdefだけになる。
そのためにシンプルな、閉じカッコ入力補完設定が動かない。

**Comment by koron** [comment]
なんか、そういう仕様にした背景があった記憶がなくもない。

**Comment by cohama** [comment]
`<Left>` だけではなさそうですね。少なくとも `<Right>` `<Up>` `<Down>` も同じです。
全部確認したわけではないですが、`help ins-special-special` に載っているキーは同じ現象になりそうな予感です。

**Comment by h-east** [comment]
Visual Blockモードで複数行選択されている場合を考慮しないといけないので結構大変かもです。
Visual Blockモードではない素のインサートモードの場合だけ挙動を変えるのはどうだろう？混乱を招く気がする。。

Visual Blockモードの事も考慮した理想的な解決方法は↓です。大分難しいですけど。
https://github.com/vim-jp/issues/issues/630#issuecomment-56343663

**Comment by nb1839** [comment]
Lingrの方で反応してしまいましたが、挿入モードでの矢印キーはstop_arrow()の中でredoバッファがクリアするようになっているので変更は厳しそうな気がします。ちなみに昔からそのような実装っぽい(うちはvim3.0で確認)。特定の条件のときだけ矢印キーをredoバッファに追加しないでクリアをしないようにすれば何とかなるのかな…。

**Comment by h-east** [comment]
Patch 7.4.849
https://groups.google.com/d/topic/vim_dev/uZbngIYTl5M/discussion

`i_CTRL-G_U`が追加されました。`i_CTRL-G_U`後のカーソル移動でundoバッファが分断されないようになったのでこのIssueの件fixされたんちゃう？

使用例:
`inoremap ( ()<C-G>U<Left>`

**Comment by h-east** [comment]
皆さんが所望(しょもう)の動作になっているのが確認出来たので閉じます。
有効活用下さい。
