### ISSUE TITLE
Vim の補完で入力に一致した候補が出てくる

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#662]
Vim の補完機能ですが、なぜか入力と一致した候補が現れます。
この現象は最初に補完を呼び出した時だけでなく、絞り込みを行った時も同じです。

再現 .vimrc

``` vim
set nocompatible

set completeopt=menuone

call append(1, "hoge")
```

再現方法：
1.  `$ vim -u test.vimrc -U NONE --noplugin`
2. `hoge<C-x><C-p>` と入力
3. 入力と完全一致した "hoge" が補完候補に現れる。
4. `<ESC>o` を入力
5. `ho<C-x><C-p><C-p>ge` と入力（絞り込み入力をhogeとする）
6. 絞りこみ文字列と完全一致した "hoge" が補完候補に現れる。

私は入力や絞り込みに完全一致する補完候補は不要だと考えています。
この挙動を変えるのはそこまで難しくないはずなので、私がパッチを書く予定です。

追記：手順を修正しました

**Comment by mattn** [comment]
その再現方法、ほんとに再現しますか？何か手順が足りない気がしますが。

**Comment by Shougo** [comment]
すみません。修正しました。手順のキーマッピングでエスケープを忘れていたようです。

**Comment by h-east** [comment]
「すいません」より「修正しました」より「ありがとう」じゃないかな？

**Comment by Shougo** [comment]
@mattn 指摘ありがとうございます。

**Comment by Shougo** [comment]
パッチを作成しました。

https://gist.github.com/Shougo/1a7d7a53a7c56ca48a85

このパッチは 6. の問題（絞りこみ文字列と同じ文字列が候補に現れる）を解決したものとなります。

3.の問題も一緒に解決しようと手を尽くしましたが、どうにもうまくいきませんでした。
edit.c の `ins_compl_add_tv()` で候補の文字列とカーソル入力の文字列をどうにか比較できればうまくいきそうなところまで分かったのですが、無念……。

私にとっては 6. の問題のほうが重要なので、この段階で vim_dev に提出したいのですがいかがでしょうか。

**Comment by k-takata** [comment]
> 1. の問題も一緒に解決しようと手を尽くしましたが、

# 意味が分からない、と思ってソースを見たら、"3. の問題も～" と書いてあった…。こっそり修正。

**Comment by Shougo** [comment]
コメントの修正ありがとうございます。

**Comment by Shougo** [comment]
https://gist.github.com/Shougo/1a7d7a53a7c56ca48a85

`3.` の問題（入力と一致した候補が現れる）を修正しました。
`compl_first_match` にカーソル文字列が暗黙的に代入されるらしいということがソースよりわかったので
それと比較するようにしました。

もっと良い方法があればぜひ教えてください。

Edit: リストの修正

**Comment by k-takata** [comment]
# 行が、<任意の数字><半角ピリオド><半角スペース> で始まっていると、1. から始まるリストになってしまいますよ。

**Comment by Shougo** [comment]
指摘ありがとうございます。直しておきます。

**Comment by Shougo** [comment]
修正しました。

**Comment by k-takata** [comment]
# お、半角スペースを詰めるんじゃなくて `3.&#32;`と書けばいけそうだ。
3.&#32;の問題

**Comment by mattn** [comment]
時間出来たら確認しますんで、送るのまって貰えますか。

**Comment by Shougo** [comment]
私は自分でパッチを適用して試しますので、よろしくお願いします。

**Comment by h-east** [comment]
"Thanks" だけ強要して中身見てませんでした。すんません。
今Issueの内容を確認しました。この動作は仕様だと思います。
hogeというポップアップメニューが表示されるということは「hogeというキーワードが存在する」という確認が出来たということになります。

patchをあてると「手順3.」でコマンドラインに "Pattern not found" と出るのはマズいです。hogeというキーワードは存在しているのですから。

分かりやすいのは<C-X><C-]>ですかね。
Vimのソース適当に開いてインサートモードで
start_search_hl<C-X><C-]>
とやってみて下さい。実在する関数なのにpatchあてたVimだとポップアップメニューが表示されずにコマンドラインに "Pattern not found" と表示されてしまいます。おかしいと思いません？

**Comment by Shougo** [comment]
@h-east チェックありがとうございます。「手順 3.」についての考えは分かりました。「手順 6.」についてはどうでしょうか。

私は補完は省入力のためのもので、「キーワードが存在する確認」のためではないと思っています。
省入力にはなんの役にも立たない候補が存在するのは意味がないので、候補から外したほうがよいと主張しているのです。

これは考え方の違いなので、オプションにしたほうが良いのかも知れません。
やるとすれば、completeopt でしょうか。

set completeopt=nobase

```
   nobase  Do not complete the keyword in front of the cursor
```

**Comment by h-east** [comment]
「手順 6.」についても仕様だと思いますよ。

> これは考え方の違いなので

そうではないです。全体の整合を崩す修正は受け入れられないでしょう。
もしもやるなら整合を取った仕様を提示して下さい。
("Pattern not found" をどういう場合に表示させないか等)

**Comment by Shougo** [comment]
その問題に関してはオプションにすればよいと思っています。
デフォルトで現在の（カーソル行のキーワードも候補に表示する）挙動、わかっている人だけ completeopt で変更できれば問題は起きないかと。

メッセージに関する変更まで入れるとなると diff が大きくなり、そのほうが受け入れられないと思います。

**Comment by h-east** [comment]
> メッセージに関する変更まで入れるとなると diff が大きくなり、そのほうが受け入れられないと思います。

私には理解不能です。
このIssueについてはノータッチにすることにします。

**Comment by Shougo** [comment]
私は最初から完璧なものを作る必要はないと思っています。
このパッチはあくまでプロトタイプ的なものなので、もっと良いアイディアが他の人より提供されるかも知れません。
機能のオプション化は必須なので、そこまでは私の手でやる予定ですが、それが終わったら vim_dev に一度投げて反応を見ます。
vim_devで否定された場合は、また別の手を考えます。

**Comment by mattn** [comment]
遅くなりましたがパッチの動作確認しました。
パッチの内容ですが９行目、10行目は STRCMP で良いと思います。つまり10行目が要らない。
また、19行目20行目も元々の動きを壊すつもりなら、22行目２３行目もSTRCMPにして引数lenを削るくらいしないといけません。でないとSTRLEN分だけ処理が増えてますからね。

**Comment by mattn** [comment]
ちなみに、元々の動作を壊す訳なので動作を変えるオプション等がいるかと思いますよ。

**Comment by Shougo** [comment]
チェックありがとうございます。今は忙しくてパッチの更新をやっていませんが、私的に基づいて更新しようと思います。

**Comment by Shougo** [comment]
このパッチを有効にすると、補完候補と入力文字列が一致した場合、ポップアップメニューが pumvisible() であることになっているにも関わらず、ポップアップメニューが存在しない状態になるという副作用があることが分かりました。
このままでは使い物にならず、回避方法も今のところ思いつかないので、パッチを一度取り下げます。
