### ISSUE TITLE
GVim で <Left> にマッピングを定義すると日本語入力がおかしくなる

### ISSUE THREAD

**Issue by cohama** [vim-jp/issues#663]
Linux 環境 (Ubuntu 12.04 で確認) の GVim で日本語入力に mozc を利用している時に、下記のようなマッピングを定義すると、予測変換からの入力が2重に入力されてしまいます。

``` vim
inoremap <Left> <Nop>
```

![1](http://i.gyazo.com/0f6ac6038e134723bec44b73ff240fe5.png)
![2](http://i.gyazo.com/00028c8b76402126f75c86f75c30a1d3.png)
#545 とも関連するのかはよく分かっていませんが、送られてくる `<Left>` 等のキーシーケンスを再マップしないようにできれば良いのかなぁと思いました。

**Comment by mattn** [comment]
im_add_to_input
add_to_input_buf_csi

がそれです。昔その変の実装をやった時に、マップしない様にしたはずなんですけどね...
デグったかな？

**Comment by presuku** [comment]
#545 との関連はわかってないとのことだったので、こちらの環境でも調べて見ました。
ディストリは Ubuntu 12.04で、日本語入力環境はuim-mozcです。

素の GVim 7.3.429 で再現しました。
自前ビルドの GVim 7.4.516 でも再現しました。
#545 の ynkdirさんのパッチ (実際にはkoronさんの[これ](https://bitbucket.org/koron/vim-kaoriya-patches/src/45cc1c3f34722efc56ac3da20b10393633d29478/X012-ynkdir-im_over_the_spot.diff)のみ) を適用した GVim 7.4.516 では再現しませんでした。

over the spotのパッチ当てれば再現しないようです。

**Comment by mattn** [comment]
はい。OnTheSpot の場合に走る im_commit_cb というコールバックから上記の関数が呼ばれます。
OverTheSpot の場合は呼ばれません。この関数は本来、map が実行されない想定だったんですが...

**Comment by presuku** [comment]
>  im_commit_cb というコールバックから上記の関数が呼ばれます。

なるほど。
ソース確認してないのが、モロバレでしたね…

これはこれで、修正された方が良いと思いますが、
OnTheSpotで、このまま行くのもつらい感じがしますね。

**Comment by mattn** [comment]
実は過去にいろんなマルチバイト圏(僕を含む)の人から色んなパッチが送り込まれて Bram が IM 関連に嫌気をさした(と思われる)事があって、その時に「IM はもう触らない」的な事を言われてしまったんですよね。

**Comment by cohama** [comment]
この問題、自分で立てといて放置してましたすみません。

> その時に「IM はもう触らない」的な事を言われてしまったんですよね。

なんと...！
確かに ynkdir さんの送ったパッチも華麗にスルーされてますね...

例えばですけど、map されないようにするパッチだけ作れたとしても望み薄でしょうか。

**Comment by k-takata** [comment]
8.0.1026で直ったはず。

**Comment by mattn** [comment]
今更ですが imstyle=0 時のこの挙動、これで治る気がします。

```diff
diff --git a/src/getchar.c b/src/getchar.c
index 78bd39d..d4b6c8b 100644
--- a/src/getchar.c
+++ b/src/getchar.c
@@ -1598,7 +1598,11 @@ vgetc(void)
       {
    int did_inc = FALSE;

-   if (mod_mask)       /* no mapping after modifier has been read */
+   if (mod_mask
+#if defined(FEAT_XIM) && defined(FEAT_GUI_GTK)
+       || im_is_preediting()
+#endif
+       )       /* no mapping after modifier has been read */
    {
        ++no_mapping;
        ++allow_keys;
```

**Comment by mattn** [comment]
もちろん :terminal の時に IM が変になるのは変わらないので現状 imstyle=1 がベストです。

**Comment by mattn** [comment]
一応パッチ出しときます。

https://github.com/vim/vim/issues/2063

**Comment by k-takata** [comment]
8.0.1060 で取り込まれました。
https://groups.google.com/d/topic/vim_dev/3aAZcAvfACc/discussion
> Problem:    When imstyle is one, mapping \<Left> breaks preediting.

s/one/zero/

**Comment by mattn** [comment]
ひとまず `:terminal` でまともに日本語出来る様になったのは確認しました。
