### ISSUE TITLE
ｷﾘ番ｹﾞｯﾄ!

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#666]
![](http://imgcc.naver.jp/kaze/mission/USER/20131102/39/3251749/0/420x290x4d4d77928448b3d6a4e91df4.jpg)

---

[素材集収にどうぞ](https://www.google.co.jp/search?q=%E3%82%BA%E3%82%B6%E3%83%BC&tbm=isch)

**Comment by mattn** [comment]
![](http://i.imgur.com/HZf449o.gif)

ｳﾜｰｯ!

**Comment by h-east** [comment]
き、きさま、まさか！？
![](https://lh4.googleusercontent.com/-byhZ6z7Un-4/VGd8XqwLRfI/AAAAAAAAG3k/itbeHBb7fCE/w741-h422-no/16%2B-%2B3)

**Comment by h-east** [comment]
そのま....zZＺ
![](https://lh6.googleusercontent.com/-UcOE3bMAES8/VGd8Xs6_t7I/AAAAAAAAG3c/uZ3dso01vZQ/w650-h487-no/16%2B-%2B1)

**Comment by raa0121** [comment]
![](http://img.7netshopping.jp/bks/images/i1/07044830.JPG)

**Comment by 0xBADDCAFE** [comment]
![1984532i](https://cloud.githubusercontent.com/assets/599164/5058665/48a2f1c4-6d3d-11e4-8a9c-74157512a215.jpg)

**Comment by rhysd** [comment]
![](http://pic.non117.com/z/CM.gif)

**Comment by koron** [comment]
Thank you all!
