### ISSUE TITLE
C の #define 文で 0 が現れるとハイライトが壊れる

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/issues#667]
魔窟 `c.vim` で発見されました。

```
Date:   Thu Oct 2 01:41:41 2014 +0200

    Update runtime files.
```

の際の変更で入ったようです。

``` c
#define TEST_0 "foobar"
```

のような、`#define` 以降に 0 が現れる構文で 0 以降がコメントアウト色となります。

c.vim 64 行目

``` VimL
syn region  cCppOut2    contained start="0" end="^\s*\(%:\|#\)\s*\(endif\>\|else\>\|elif\>\)" contains=cSpaceError,cCppSkip
```

で start が 0 になっているからのようですが、どのように修正するのが適切か分かりません。
`#if 0` 構文に絡むようなので `if\s\+0` とかしてしまってもいいものでしょうか。

**Comment by itchyny** [comment]
https://groups.google.com/d/msg/vim_dev/IWh1TezoLHw/wuCZZdMdfqsJ これでしょうか

**Comment by mattn** [comment]
お手数ですが https://github.com/vim-jp/cpp-vim こちらに再投稿願えますか？

**Comment by 0xBADDCAFE** [comment]
> itchyny

その件と同一のようです、確認ありがとうございます。

> mattn

再投稿しました。https://github.com/vim-jp/cpp-vim/issues/29
移管した、かつ vimdev でも把握されているので close しておきます。
duplicated もしくは worksforme で管理でしょうか。
