### ISSUE TITLE
7.4.497 以降でregexengine=0の時にSEGVが起こる

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#668]
これ (https://github.com/vim-jp/issues/issues/664#issuecomment-63670723) の最小構成がわかったので報告させていただきます.
##### segv_regex.vim

``` vim
:syntax on
:h options
:set regexpengine=0
:let m = matchadd('Error', '\_.*')
```
1. `vim -N -u NONE -S segv_regex.vim`
2. `:call matchdelete(m)`
   - EDIT: `matchdelete()` じゃなくても `<C-f>`や`jjjjj..`で最初に見えてる画面の行数よりも後ろを表示するようにしても再現しました
3. Vim: Caught deadly signal SEGV  
   Vim: Finished.
##### 環境

Ubuntu 14.04 CUI Vim 7.4.525
EDIT: gvimでも再現しました(同じバージョン)
##### NOTE
- regexengineを1や2にすると発生せず0のときだけ起こる
- 7.4.496 時点では発生しない
- :h options のような巨大なファイルの時に再現する
- mattnさんの パッチ (https://groups.google.com/forum/#!msg/vim_dev/IUX03WQgo-I/tNqhwGPkO0sJ) を当てたら SEGV は起こらないようになりましたが, `matchadd()`が正しく動かず全体がハイライトされない
- `matchadd()` を呼ぶ時点でのカーソルからバッファの末尾までの行数(マッチ数?) が多い時に起こるようで, `:set regexpengine=0`のあとに`:$` を挟むとSEGVは起こらなくなる

**Comment by lesguillemets** [comment]
> `:set regexpengine=0`のあとに `:$` を挟むとSEGVは起こらなくなる

`matchadd()` を呼んだあとカーソルをバッファ先頭へ近づけていくと同様に再現するようです．

**Comment by k-takata** [comment]
7.4.526で追加修正が入りましたが、どうでしょうか。
https://groups.google.com/d/topic/vim_dev/ptDDZJ-laBM/discussion

**Comment by haya14busa** [comment]
パッチ 526 試してみましたが同環境で落ちました

**Comment by nb1839** [comment]
手元の win8.1 環境上でパッチ 525 では発生していましたが、527 まで上げると発生しなくなったような感じです。
ただ、NFA が上記パターンでは expensive でなくなったので二重解放の条件に合致しなくなっただけ
というような気もしますが…。

**Comment by haya14busa** [comment]
こちらの環境では 527 でもまだ落ちますね

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 26 2014 05:20:57)
Included patches: 1-527
Compiled by haya14busa@haya14busa-ThinkPad-X200s
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python/dyn      +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  +python3/dyn     +tag_old_static  +vreplace
+balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
+browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         -tcl             +wildmenu
++builtin_terms  +dialog_con_gui  -footer          +lua/dyn         +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      +ruby            +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     +X11
+clientserver    +dnd             -hangul_input    +modify_fname    -netbeans_intg   +signs           +title           -xfontset
+clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     +toolbar         +xim
+cmdline_compl   +emacs_tags      +insert_expand   +mouseshape      +perl            -sniff           +user_commands   +xsmp_interact
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       +xterm_clipboard
+cmdline_info    +ex_extra        +keymap          +mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          +xpm
```

もしや32bitだということも関係あったり?(ただの勘)

**Comment by lesguillemets** [comment]
(K)ubuntu  14.04, 32 bit, 64 bit のいずれでも 527 で再現しました． Vim は konsole で起動した CUI 版ですが， GVim でも同様です．

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2014 17:36:01)
Included patches: 1-527
Compiled by lesguillemets@lesguillemets-LN
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +comments        +ex_extra        +jumplist        +mouseshape      +path_extra      +signs           +textobjects     +writebackup
+arabic          +conceal         +extra_search    +keymap          +mouse_dec       -perl            +smartindent     +title           +X11
+autocmd         +cryptv          +farsi           +langmap         +mouse_gpm       +persistent_undo -sniff           +toolbar         -xfontset
+balloon_eval    +cscope          +file_in_path    +libcall         -mouse_jsbterm   +postscript      +startuptime     +user_commands   +xim
+browse          +cursorbind      +find_in_path    +linebreak       +mouse_netterm   +printer         +statusline      +vertsplit       +xsmp_interact
++builtin_terms  +cursorshape     +float           +lispindent      +mouse_sgr       +profile         -sun_workshop    +virtualedit     +xterm_clipboard
+byte_offset     +dialog_con_gui  +folding         +listcmds        -mouse_sysmouse  -python          +syntax          +visual          -xterm_save
+cindent         +diff            -footer          +localmap        +mouse_urxvt     +python3         +tag_binary      +visualextra     +xpm
+clientserver    +digraphs        +fork()          +lua             +mouse_xterm     +quickfix        +tag_old_static  +viminfo         
+clipboard       +dnd             +gettext         +menu            +multi_byte      +reltime         -tag_any_white   +vreplace        
+cmdline_compl   -ebcdic          -hangul_input    +mksession       +multi_lang      +rightleft       -tcl             +wildignore      
+cmdline_hist    +emacs_tags      +iconv           +modify_fname    -mzscheme        +ruby            +terminfo        +wildmenu        
+cmdline_info    +eval            +insert_expand   +mouse           +netbeans_intg   +scrollbind      +termresponse    +windows         
```

また，頓珍漢なことを言っていたらごめんなさいなのですが，　64, 32 bit いずれでも同様の操作でSEGV でなく `Caught deadly signal ABRT` と言い残して落ちることがあり，その際このようなメッセージを吐くことがあります．

```
Vim: Caught deadly signal ABRT
*** Error in `vim': malloc(): smallbin double linked list corrupted: 0x09b27020 ***
    Vim: Finished.
Vim: Double signal, exiting
```

試したところでは， 32 bit のほうで konsole 上に vim を上記の方法で起動したあと `<C-w>o` でこうなる "ことがある" のですが，再現条件をつかめていません．

**Comment by nb1839** [comment]
ああ、やっぱり 527 でも駄目でしたか；；
NFA_TOO_EXPENSIVE の調整を入れてるっぽいので 526 との合わせ技で
直ったんじゃないかと期待したのですが…。

一応、パッチ 525 での再現で何が二重解放しているかはほぼ特定は出来ていて、原因としては

win_line()
│  ハイライト検索で search_hl と w_match_head (コピーの方)の
↓  それぞれで検索を実施
next_search_hl()
│  ここでコメントに /\* don't free regprog in the match list, it's a copy */
↓  と書いてあるにも関わらず… (この match list が w_match_head のこと)
vim_regexec_multi() 
    ここで regexpengine = 0 の場合に検索に時間が掛かりすぎて
    NFA_TOO_EXPENSIVE になると w_match_head かどうかに関係なく
    regprog を解放して差し替え。(vim_regfree())

そしてこの後 match_delete() で w_match_head (オリジナル)の方の
regprog を解放しようとするが既に解放されているのでアボート。

という流れのようです。

なので、暫定対応としては (ハイライトがおそらく正常に機能しないだろうことに目を瞑れば)
#664 の mattn さんのパッチも「あり」だと思います。

これを根本的に直そうと思ったら、

(a) vim_regexec_both() と vim_regexec_multi() の引数を調整して
    vim_regfree() して良いものかどうかを識別できるようにする。
(b) vim_regexec_both() と vim_regexec_multi() の戻り値を調整して
    呼び出し側で vim_regfree() の可否を判断する。
    (next_search_hl() の層ならそもそも識別可能なので)
(c) regmatch_T 自体にフラグを持たせて解放の可否を判断出来るようにする。

あたりかなぁと思っています。
ただ、(ちょっと構造的な問題なので)どのパターンも修正箇所が多くなりそうですごく悩ましい…。

**Comment by nb1839** [comment]
ちなみに BACKTRACKING_ENGINE に切り替わった瞬間に
ちょっと regprog がリークする(かもしれない)ことくらいどうってことない、
という場合には

``` patch
--- a\src\regexp.c  2014-11-25 00:24:26.964091200 +0900
+++ b\src\regexp.c  2014-11-26 22:56:00.686866100 +0900
@@ -8185,7 +8185,7 @@
    char_u *pat = vim_strsave(((nfa_regprog_T *)rmp->regprog)->pattern);

    p_re = BACKTRACKING_ENGINE;
-   vim_regfree(rmp->regprog);
+   /* vim_regfree(rmp->regprog); */
    if (pat != NULL)
    {
 #ifdef FEAT_EVAL
@@ -8283,7 +8283,7 @@
    char_u *pat = vim_strsave(((nfa_regprog_T *)rmp->regprog)->pattern);

    p_re = BACKTRACKING_ENGINE;
-   vim_regfree(rmp->regprog);
+   /* vim_regfree(rmp->regprog); */
    if (pat != NULL)
    {
 #ifdef FEAT_EVAL
```

これでハイライトもうまくいくし、SEGV もしないという状況には
持っていけるんじゃないかと思います。。。

本家にはまず絶対このパッチは通らないと思いますが…

**Comment by mattn** [comment]
w_match_head をマイグレーションするパッチが出されたけど
https://groups.google.com/forum/#!topic/vim_dev/ptDDZJ-laBM/discussion

これ、全部のウィンドウの w_match_head をマイグレーションしなくていいんだろうか

**Comment by nb1839** [comment]
match_add() は単一の win_T (この場合は curwin) に閉じるので
全部のウィンドウは見なくても大丈夫だと思います。
なので URL で提示されたパッチ(matchlist_clear.diff)でも直ることは直りますが…
う～ん、そうきたかーという感じですね。
インタフェースを変更しないで修正箇所を最小限にするには
確かにこのやり方でも合っているんですけど、
指先の血行を直すのに心臓から直接パイプを繋げてる感じでちょっと好みじゃないです＾＾；

vim のソースが汚いと言われる所以が増えそうでちょっと…

**Comment by nb1839** [comment]
失礼、パッチ 528 が来てたんですね。気付いてませんでした。
ぱっと見た感じ vim_regexec_multi() の呼び出し側で
先にコピーを作成して対処しようとしているっぽい。

どちらかというとこっちの方が直し方としてしっくりきます。。。が、あれ？

これ後でコピーしてません？
vim_regexec_multi() の中で NFA_TOO_EXPENSIVE が発生した際に
差し替えで vim_regcomp() された regprog が置き去りにされてしまうような気が…

**Comment by mattn** [comment]
> match_add() は単一の win_T (この場合は curwin) に閉じるので
> 全部のウィンドウは見なくても大丈夫だと思います。

syntax 定義に正規表現が指定出来るので、これを更新する処理がいるのでは、と思いました。
もうパッチが出てしまっていますので、それは別途検証します。

**Comment by nb1839** [comment]
> syntax 定義に正規表現が指定出来るので、これを更新する処理がいるのでは、と思いました。
> もうパッチが出てしまっていますので、それは別途検証します。

ああ、ひょっとして SEGV の話ではなくて
engine が切り替わったのだから NFA_TOO_EXPENSIVE になった正規表現だけではなくて
それ以外の正規表現も vim_regcomp() し直さなければならないのでは？という話ですよね？
それなら同意します(多分必要そう & 直すの大変そう。。)

**Comment by nb1839** [comment]
> それ以外の正規表現も vim_regcomp() し直さなければならないのでは？という話ですよね？
> それなら同意します(多分必要そう & 直すの大変そう。。)

失礼、これ私の勘違いでした。
vim_regexec_multi() ですぐに p_re = save_p_re で差し戻しているので
該当する正規表現だけ engine が差し替わるっぽい動きになりそうです。

**Comment by mattn** [comment]
元々 https://github.com/vim-jp/issues/issues/664 は `match_add()` でなく `:syntax` で出た問題なので、そちらを考慮するなら全てのウィンドウ(バッファ?)の定義済み正規表現も直さなくて大丈夫かな、という危惧です。

**Comment by haya14busa** [comment]
落ちなくなったことを確認しました。@nb1839 さん, @mattn さんありがとうございました！

他のウィンドウでどうなるかはまだ確認できてません。

**Comment by nb1839** [comment]
> 元々 #664 は match_add() でなく :syntax で出た問題なので、そちらを考慮するなら
> 全てのウィンドウ(バッファ?)の定義済み正規表現も直さなくて大丈夫かな、という危惧です。

うちだとパッチ 498 まで落としても #664 のがうまく再現しないので箇所が特定できていないのですが
https://groups.google.com/forum/#!topic/vim_dev/IUX03WQgo-I
の途中にある Daniel Hahler 氏のスタックトレースの箇所だと仮定すると

(パッチ 537 のソースで確認)
(1) syn_current_attr() で syn_block->b_syn_patterns.ga_data から
    regprog のポインタをコピーして (regmatch.regprog = spp->sp_prog)
    syn_regexec(&regmatch, ...) を呼び出す。
(2) syn_regexec() ではそのまま vim_regexec_multi() を呼ぶ。
    (ここで regprog の差し替えが発生する可能性がある)
(3) 但し、syn_regexec() からの復帰直後に
    syn_block->b_syn_patterns.ga_data の方のポインタも
    差し替えられたポインタで書き戻し (spp->sp_prog = regmatch.regprog)

としているようなので大丈夫そうに見えます。(519 パッチの 422 行目で修正)

同じ意味で改めて見るとパッチ 528 の方も

``` c
    if (regprog_is_copy)
        cur->match.regprog = cur->hl.rm.regprog;
```

これが w_match_head のポインタを更新していると考えられるので

> vim_regexec_multi() の中で NFA_TOO_EXPENSIVE が発生した際に
> 差し替えで vim_regcomp() された regprog が置き去りにされてしまうような気が…

これは完全に杞憂でした。(逆の意味で読んでた…＾＾；) パッチ 528 も正しく直っていると思います。

**Comment by lesguillemets** [comment]
同じく落ちなくなったことを確認しました．ありがとうございます

**Comment by h-east** [comment]
Patch 7.4.528
https://groups.google.com/d/msg/vim_dev/kVHNmeLjHjI/HI-5ajuXpX0J

本Issue閉じて良いのかな？

**Comment by haya14busa** [comment]
個人的には直ったと思うので閉じてもokです. ありがとうございました...!
 コード的に他の問題があるかも..?という部分はすいませんが正直わからないのでなんとも言えないです.

**Comment by h-east** [comment]
閉じます。
