### ISSUE TITLE
syntax/netrw.vimにscriptencoding指定されていない。

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#669]
syntax/netrw.vimに`│`というマルチバイト文字が使用されているのですが、このファイルに`scriptencoding`の指定がされてません。
そのため、以下のvimrcでかつ、netrwバッファが存在する状態で`syntax on`すると以下エラーが出てしまいます。
`scriptencoding utf-8`をsyntax/netrw.vimの先頭で宣言することでこのエラーは出なくなりました。
（環境はWindowsです。）

**vimrc**

> let &fileencodings = 'utf-8,cp932,euc-jp,default,latin'
> syntax on

**エラー**

> Error detected while processing C:\vim\runtime\syntax\netrw.vim:
> line   27:
> E401: Pattern delimiter not found: "^\%([-+|笏・ )+"^I^I^I^I^Icontains=netrwTreeBarSpace^Inextgroup=@netrwTreeGroup
> E475: Invalid argument: netrwTreeBar^I^I"^\%([-+|笏・ )+"^I^I^I^I^Icontains=netrwTreeBarSpace^Inextgroup=@netrwTreeGroup

**エラー該当行**

> https://github.com/vim-jp/vim/blob/1986c3419e692881aa58cf384094337e40548ec4/runtime/syntax/netrw.vim#L27

以上、よろしくお願い致します。

**Comment by ynkdir** [comment]
あーすみません。
その件は #636 で報告済みで、メンテナの方に次のアップデートで直すよーという回答をいただいてます。

**Comment by rbtnn** [comment]
なるほど、了解しました。

**Comment by crazymaster** [comment]
https://github.com/vim-jp/vim/commit/9e29e825eda66310900d9d0935713bb93d6bd0bb#diff-247fe5c3bf0183edc75cbeccac7b00b1
