### ISSUE TITLE
'cursorline' でハイライトされた部分の 'listchars' などの色がおかしい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#67]
`'cursorline'` でハイライトされた部分にある `'listchars'` の文字の色がおかしくなります。
1つ外側のハイライトの色になる感じです。例えば、コメント内ならコメントの色に、文字列内なら文字列の色になります。

**Comment by thinca** [comment]
画像が必要そうなら後で貼ります。今はちょっと無理なので…。

**Comment by mattn** [comment]
これ画像お願いします。

**Comment by thinca** [comment]
![](http://gyazo.com/ca3ad89ba0b5eb304d3510745436c0dd.png)

真ん中の行だけ行頭の `^` の色がコメントのものに変わっています。
この例はコメントですが、コメントに限らず発生します。

**Comment by DeaR** [comment]
使っていて気になってるので私も画像をペタリ

![issue67](https://f.cloud.github.com/assets/1154870/428922/31af9194-ae2a-11e2-8d51-16a33c8fac40.png)

環境は 7.3.905 x64 +kaoriya (windows7 x64)
下記が1段目の設定値です。

```
:hi CursorLine
CursorLine     xxx term=underline cterm=underline guibg=#293739

:hi CursorColumn
ColorColumn    xxx term=reverse ctermbg=4 guibg=#232526

:echo &listchars
eol:$,tab:>-,extends:>,precedes:<,trail:~  

:set cursorline cursorcolumn
```

2段目は1段目から `hi clear CursorLine` したもの
3段目は2段目から `hi CursorLine gui=underline` したもの

`cursorline` では起こるが `cursorcolumn` は大丈夫なようです
まぁ、実装時期も実装処理も違うでしょうし参考にはならなそうですが

**Comment by DeaR** [comment]
`cursorline` は visual mode と大体似た処理を通してる様でそっちでも同様に `listchars` の色がおかしくなります

大胆に条件式を削ったら tab, trail, precedes を正常に表示出来ました
extends は元から問題無しで、nbsp は `cursorline` では大丈夫だけど visual mode では駄目:sweat:
eol も出そうとしたら eol の後は元に戻す的な処理に入っちゃったりﾖｰﾜｶﾗﾝ:persevere:
(eol 以降の空白部分がハイライトされなくなっちゃった)

---

追記：でかいし邪魔なんでｐａｔｃｈは https://gist.github.com/DeaR/5467343 に移動

**Comment by DeaR** [comment]
https://gist.github.com/DeaR/5467343

なんか一通りの `listchars` が正常表示できるようになった気がします。
結局の所 nbsp 以外はどれも `attr_prio` を無視するようにしただけです。
nbsp は `area_attr` と `search_attr` を無視。

---

但し、わざわざ条件になっていたものを無視するようにしたので何が起こるやら。

**Comment by ynkdir** [comment]
cursorline 以外にも hlsearch や :match でも同じみたいです。
hlsearch で /\t を検索した図。

![foo](https://f.cloud.github.com/assets/142094/430966/d8b98732-ae7b-11e2-906b-099b3734ad7f.png)

DeaR さんのパッチは hlsearch, :match も直ります。

副作用は…どうなんでしょうね…

**Comment by ynkdir** [comment]
fg が反映されなくなりますね。
例えば
:hi CursorLine guifg=blue
:hi Search guifg=blue

**Comment by DeaR** [comment]
> fg が反映されなくなりますね。
> 例えば
> :hi CursorLine guifg=blue
> :hi Search guifg=blue

まぁ、searchだろうが、何だろうがNonTextやSpecialKeyで上書き合成しますからねぇ
なので、同時に下記のように設定すれば青くはなりますね

``` vim
:hi clear SpecialKey
:hi clear NonText
:hi SpecialKey gui=underline
:hi NonText gui=underline
```

ただ、個人的には、ですが所詮非表示文字なんで本来の文字と区別がつく別の色に常になっていた方が良いような気はします

**Comment by DeaR** [comment]
導き出される弊害
- SpecialKey でbg,fg両方を設定するとSearch・CursorLineから完全に上書きされてしまい見えない

付属のcolorsは大丈夫だが、配布されている物にはそういう設定もあるだろう

---

余談だが上記の現象は全角スペースの表示としてよく紹介されている下記の様なのでも起きてしまう

``` vim
:hi QuadSpace guifg=blue gui=underline
:match QuadSpace /　/
```

**Comment by ynkdir** [comment]
表示系は難しいですね…

パッチなし

:hi clear SpecialKey
![a](https://f.cloud.github.com/assets/142094/431255/12ac7bd6-ae84-11e2-8954-a8166aff86eb.png)

:hi SpecialKey guifg=blue guibg=NONE
![c](https://f.cloud.github.com/assets/142094/431317/791160de-ae85-11e2-8abc-2780919b3b01.png)

:hi SpecialKey guifg=NONE guibg=green
![e](https://f.cloud.github.com/assets/142094/431327/c07852fc-ae85-11e2-8116-5aa853dc0301.png)

:hi SpecialKey guifg=blue guibg=green
![g](https://f.cloud.github.com/assets/142094/431339/09b23870-ae86-11e2-9907-5334e92ede23.png)

パッチあり

:hi clear SpecialKey
![b](https://f.cloud.github.com/assets/142094/431256/18a5ada0-ae84-11e2-8eb7-5e0300ff98cc.png)

:hi SpecialKey guifg=blue guibg=NONE
![d](https://f.cloud.github.com/assets/142094/431325/9c763fa4-ae85-11e2-82ed-5a603c26a344.png)

:hi SpecialKey guifg=NONE guibg=green
![f](https://f.cloud.github.com/assets/142094/431336/e64abc0e-ae85-11e2-8d71-13d82be87fd0.png)

:hi SpecialKey guifg=blue guibg=green
![h](https://f.cloud.github.com/assets/142094/431341/2955cda4-ae86-11e2-9826-8fa012b7fd79.png)

**Comment by DeaR** [comment]
これはひどい
またscreen.cにダイブしてきます λ....

**Comment by DeaR** [comment]
何となく弄ってみてる限りでは適用順が、
Syntax→CursorLine→SpecialKeyの順だからCursorLineがある時はSpecialKeyの適用を止めてたのかな。
で、私のパッチは無理やりSpecialKeyを表示するから滅茶苦茶になってる。

https://gist.github.com/DeaR/5467343/9a217fd68fe600ed724d82abba960378c8f4ea9b

``` vim
:hi clear SpecialKey
:hi SpecialKey guifg=NONE guibg=green
```

これらもカーソル行以外の表示は良い感じになった
カーソル行の表示は相変わらず

そして、Syntax→SpecialKey→CursorLineな適用順になれば一番気持ちいい表示になりそうだが
どの辺をどの辺に移動すればいいのやら:weary:

気長にTry&Errorするしかないか…:sob:

**Comment by ynkdir** [comment]
。。。お疲れさまです

**Comment by DeaR** [comment]
https://gist.github.com/DeaR/5467343/75b6da51451d7a6057fb5aea338ae02c0ed72b92
取り敢えず修正。
相変わらずCursorLine等よりSpecialKeyが優先な事には変わりなく、またゴッソリとブロックを移動させたので色々危ない

**Comment by ynkdir** [comment]
nice!

**Comment by DeaR** [comment]
https://gist.github.com/DeaR/5467343/195c2abb27dcf1af32aa087aa848b900bbb754c8
良い感じになったような気がします

> Syntax→CursorLine→SpecialKeyの順だからCursorLineがある時はSpecialKeyの適用を止めてたのかな。

ではなく、まずCursorLineを適用し、SyntaxがあればSyntaxに現在の物をmergeする(逆方向)だったみたいなので、
同様にCursorLineを適用し、SpecialKeyに現在の物をmergeし、Syntaxは無視する、的な感じにしてみました
結果的には Syntax＜SpeciaｌKey＜CursorLine という優先順に出来た
故にdelekのようにVisualでbg,fg両方指定してある場合、今と同様SpecialKeyとTextと区別がつかなくなります:yum:

**Comment by DeaR** [comment]
<del>:set list listchars=eol:$,trail:~,nbsp:%</del>

:set list listchars=eol:$,tab:>-,trail:~,nbsp:%
:hi clear SpecialKey
![clear](https://f.cloud.github.com/assets/1154870/435664/95655e86-aff5-11e2-9eef-eef791ffa64b.png)
:hi SpecialKey guifg=blue guibg=NONE
![fg](https://f.cloud.github.com/assets/1154870/435665/9cf55c5a-aff5-11e2-9ad4-823011dd894e.png)
:hi SpecialKey guifg=NONE guibg=green
![bg](https://f.cloud.github.com/assets/1154870/435666/9feb0090-aff5-11e2-8d5f-8b6d018bd9df.png)
:hi SpecialKey guifg=blue guibg=green
![bgfg](https://f.cloud.github.com/assets/1154870/435667/a3337d04-aff5-11e2-9118-d14774b7bfbf.png)

---

https://gist.github.com/DeaR/5467343/75b6da51451d7a6057fb5aea338ae02c0ed72b92
なら CursorLine＜SpecialKey
https://gist.github.com/DeaR/5467343/195c2abb27dcf1af32aa087aa848b900bbb754c8
なら SpecialKey＜CursorLine

微妙に好みの範囲ともいえる

---

追記
あ、IndentLine残ってる:scream:

**Comment by DeaR** [comment]
適当に比較画像作成

![issue67](https://f.cloud.github.com/assets/1154870/435727/dfa806fc-affe-11e2-90f5-b8f3ab322ada.png)

:colorscheme delek
:set cursorline list listchars=eol:$,tab:>-,trail:~,nbsp:%

SpecialKey overrides CursorLine
 -> https://gist.github.com/DeaR/5467343/75b6da51451d7a6057fb5aea338ae02c0ed72b92

CursorLine overrides SpecialKey
 -> https://gist.github.com/DeaR/5467343/195c2abb27dcf1af32aa087aa848b900bbb754c8

---

並べて見ると個人的には一番右

**Comment by ynkdir** [comment]
おつかれさまです！
私も一番右がいいと思います。

**Comment by mattn** [comment]
おーすばらしい。
たぶん一番右がよいと思いますが、どっちも投げてみてはどうでしょう。

**Comment by thinca** [comment]
私も一番右がいいと思います！

**Comment by DeaR** [comment]
https://groups.google.com/d/topic/vim_dev/oYeTcHINrrg/discussion
投稿しました

---

GingerとGoogle翻訳の力だけで説明できる気がしないので画像まで添付:sweat_smile:

**Comment by ynkdir** [comment]
gj!

**Comment by DeaR** [comment]
バグ発見

:set list listchars=eol:$ conceallevel=1 concealcursor=nvic
:syntax match NonText / / conceal cchar=.

で行末がスペースだとeolやcursorline色々表示されない
探ってきます λ....

**Comment by DeaR** [comment]
修正完了
- ConcealCharもSpecialKeyと同じ感じに書くようになった(SpecialKeyと同じようにCursorLineを上書きしたりされたり)
- `char_attr` に代入する処理だけを移動することによりパッチがスリムになった

SpecialKey overrides CursorLine version 2

<del>-> https://gist.github.com/DeaR/5467343/94c70662b9825c925d16cfe547a603570e351bd2#file-cursorline_overrides_specialkey_ver2-patch</del>

-> https://gist.github.com/DeaR/5467343/0d98302d85d02b6c8a196ce31fbf0037bb38fc7b#file-specialkey_overrides_cursorline_ver2-patch

CursorLine overrides SpecialKey version 2

<del>-> https://gist.github.com/DeaR/5467343/94c70662b9825c925d16cfe547a603570e351bd2#file-specialkey_overrides_cursorline_ver2-patch</del>

https://gist.github.com/DeaR/5467343/0d98302d85d02b6c8a196ce31fbf0037bb38fc7b#file-cursorline_overrides_specialkey_ver2-patch

---

<del>なんかファイル名左の×押しても空の登録が残るせいでファイル削除できない…</del>

**Comment by presuku** [comment]
CursorLine overrides SpecialKey version 2を
もう、これ無しでは違和感があるほど常用してます。

そこで、 `ft=gitconfig` なファイルの Syntax で
表示が壊れる不具合があり、自信ないですが直せたっぽいので報告します。
- 現象
  表示が乱れる
- 再現方法
  1. 適当なバッファを開く
  2. `set ft=gitconfig` 、 `set noexpand` する
  3. `<TAB>url =` (<TAB>はハードタブのことです) と入力し、 
     後につづけて入力すると `url` 辺の表示が壊れる
  4. その後、 `url` を検索してハイライトさせたり、他の行にカーソルを移すと元に戻ります。
  5. `gitconfig` の Syntax file が 無い場合には、
     `:syn match Comment "\%(^\s*\)\@<=\a\k*\%(\s*\%([=#;]\|$\)\)\@="` としてください。
- 修正箇所
  [CursorLine_overrides_SpecialKey_ver2.patch](https://gist.github.com/DeaR/5467343/0d98302d85d02b6c8a196ce31fbf0037bb38fc7b#file-cursorline_overrides_specialkey_ver2-patch) で説明します。
  パッチの51〜52行目の、下記2行を削除してしまうとダメなようです。
  
  ``` diff
  -           line = ml_get_buf(wp->w_buffer, lnum, FALSE);
  -           ptr = line + v;
  ```
  
  [SpecialKey_overrides_CursorLine_ver2.patch](https://gist.github.com/DeaR/5467343/0d98302d85d02b6c8a196ce31fbf0037bb38fc7b#file-specialkey_overrides_cursorline_ver2-patch) でも同様の箇所で直ります。
- 修正済みのパッチ
  下記のGistに上げておきました
  https://gist.github.com/presuku/d3d6b230b9b6dcfc0477

**Comment by mattn** [comment]
@DeaR  ping の意味でもっかい突きます？

**Comment by DeaR** [comment]
作りっ放し且つ、完全に存在を忘れてた系
正直もう数ヶ月は検証やら英文章作成含めロクに時間的余裕が作れそうにないので宜しく進めてくれるとありがたいなぁ、という他力本願状態だったりします:tired_face:
でっか過ぎな添付ファイルや7.4やNFAなんかで完全スルー状態な感じでしたしね
(更に当時は名義も`nayuri aohime`ではなかったりとフルコンボ:persevere:)

**Comment by noscript** [comment]
Great patch. Have you tried to submit it to neovim as well?

**Comment by usagi** [comment]
困って気になってググったらここに辿り着いたけど本体のバグだったのか。なぜ未だに取り込まれないんだ。

**Comment by mattn** [comment]
突っついときました。

**Comment by k-takata** [comment]
presukuさんのパッチも投げておいた方がよさそう。

**Comment by k-takata** [comment]
mattn++

presakuさんのパッチを更にforkしたパッチがありました。
https://gist.github.com/kadzuya/ebc3047079566569d227
最新ソースだと、こっちじゃないと当たらないのかな。（未確認）

**Comment by presuku** [comment]
7.4.527で失敗しないようにアップデートしました。
(hg mqで普段使ってる奴を持ってきただけですけが…)
https://gist.github.com/presuku/d3d6b230b9b6dcfc0477

**Comment by k-takata** [comment]
todo入りです。

> Patch to fix display of listchars on the cursorline. (Nayuri Aohime, 2013)
> Update suggested by Yasuhiro Matsumoto, 2014 Nov 25:
> https://gist.github.com/presuku/d3d6b230b9b6dcfc0477

**Comment by presuku** [comment]
いつの間にかこの問題が直っていたのは自覚していて放置してたんですが、
いつまでも修正された問題が（自分のgist url付きで）todo.txtに残っているのも、良くないと思い、
今更ですが、削除依頼のissue立てときました。

**Comment by presuku** [comment]
https://github.com/vim/vim/commit/017ba07fa2cdc578245618717229444fd50c470d  の patch 8.1.2029 で CursorLine overrides SpecialKey で修正され、
https://github.com/vim/vim/commit/4700398e384f38f752b432e187462f404b96847d の Update runtime files  で todo.txt から削除されました。
