### ISSUE TITLE
:h col() が実際の挙動と異なる

### ISSUE THREAD

**Issue by syngan** [vim-jp/issues#671]
すいません、ミスりました。。。。ミスついでに。。

`col()` のヘルプでは可能な position として以下が定義されていますが、
実際には `line()` と同じ `var2fpos()` 関数と使って処理していて、
`v` なども受け入れられるように見えます。 

```
col({expr})     The result is a Number, which is the byte index of the column
                position given with {expr}.  The accepted positions are:
                    .       the cursor position
                    $       the end of the cursor line (the result is the
                            number of bytes in the cursor line plus one)
                    'x      position of mark x (if the mark is not set, 0 is
                            returned)
```

https://github.com/syngan/vim-vimlint/issues/63

**Comment by ynkdir** [comment]
ありがとうございます。報告しました。
https://groups.google.com/d/msg/vim_dev/IEGbh2-LNTo/5ACPsTeLbk4J

**Comment by syngan** [comment]
対応ありがとうございます。

**Comment by ynkdir** [comment]
修正されました。

**Comment by crazymaster** [comment]
https://github.com/vim-jp/vim/commit/4ef3ea7d06794f1e8b4b46bfaa5736a565549386#diff-0
