### ISSUE TITLE
unix 用の ctermfg/ctermbg を cmd.exe 版に食わせるとサイケデリックになる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#672]
![](http://go-gyazo.appspot.com/4d46070908059830.png)

これは SetConsoleTextAttribute, FillConsoleTextAttribute が WORD でしかも 0xff までしか値が取れないのにそれよりも大きな値を渡している為。

以下パッチ。

https://gist.github.com/mattn/8ac8917f310c4db4665c

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/MxFXGD_QLL8

**Comment by k-takata** [comment]
修正後のスクリーンショットも見たいです。

**Comment by mattn** [comment]
修正後。

![](http://go-gyazo.appspot.com/d7fcdbcbf5bfb5fb.png)

同じ colorscheme、inkpot を gui で設定した場合。

![](http://go-gyazo.appspot.com/1fbefd718d6aef52.png)

# ぜんぜんちがじゃない！

まぁそれは colorscheme のせい。

**Comment by k-takata** [comment]
:+1:

**Comment by sgur** [comment]
:+1:

**Comment by todashuta** [comment]
:+1:

**Comment by k-takata** [comment]
todo入りです。

> Patch to allow values greater than 255 for ctermfg/ctermbg on Windows.
> (Yasuhiro Matsumoto, 2014 Dec 5)

**Comment by mattn** [comment]
7.4.679
https://groups.google.com/forum/#!topic/vim_dev/n2cQKdHPzco
