### ISSUE TITLE
複数行に渡る検索の hlsearch のハイライトが正しくない

### ISSUE THREAD

**Issue by presuku** [vim-jp/issues#673]
下記の画像の様に `bc\na` を検索しているのに、
v7-4-405 では、最後の行の `a` ハイライトされません。
環境は Ubuntu 12.04 / 14.04 です。
- v7-4-404 の結果 OK!
  ![v7-4-404](https://cloud.githubusercontent.com/assets/7233193/5318784/54591dfa-7ce6-11e4-83f1-4bfd6fe16e62.png)
- v7-4-405 の結果 NG...
  ![v7-4-405](https://cloud.githubusercontent.com/assets/7233193/5318785/545e37ea-7ce6-11e4-8991-7a9173980768.png)
- 再現方法
  vim -g -u NONE -U NONE -S reproduce.vim
- reproduce.vim
  
  ``` viml
  :norm! 3aabc
  :set hlsearch
  /bc\na
  ```

[v7-4-405](http://ftp.vim.org/vim/patches/7.4/7.4.405) は、  #603 の報告より [v7-4-362](http://ftp.vim.org/vim/patches/7.4/7.4.362) による
速度低下対策として取り込まれた様なのですが、そこで regression してる様です。
また、その時 v7-4-405 は #603 の h-eastさんの[パッチ](https://github.com/vim-jp/issues/issues/603#issuecomment-52390403)の代わりに取り込まれましたが、
h-eastさんのパッチだと、この問題は起きませんでした。

最新の v7-4-540 で当たるパッチ:
https://gist.github.com/presuku/a42e19b17268e4a2149b

**Comment by h-east** [comment]
@presuku Issue登録、検証、patch更新ありがとうございます。
こちらでも現象再現しました。

``` vim
:help @en
:set hls
/\nClose
```

とすると、"Close～" の行全てがhighlightされちゃいますね。:sweat_smile:
vim_devに報告するのでちょっとお待ちを。

**Comment by h-east** [comment]
@presuku 確認です。presukuさんが更新したpatchだと私の元のpatchの以下の処理が3845行目辺りから4310行目辺りに移動されているのですが意図したものでしょうか？

``` c
#ifdef FEAT_MBYTE
        if (has_mbyte)
            hl_len += (*mb_ptr2len)(ptr);
#endif
```

**Comment by presuku** [comment]
@h-east 
確認ありがとうございます。

> とすると、"Close～" の行全てがhighlightされちゃいますね。:sweat_smile:
> vim_devに報告するのでちょっとお待ちを。

ホントですね、色々とおかしい感じですね。
報告お願いします。

> 元のpatchの以下の処理が384行目辺りから4310行目辺りに移動されているのですが意図したものでしょうか？

あれ移動されてましたか？ 特に、意図したものではないです。
patch あてたら失敗したので、その修正をミスった可能性が高いです…

また、余談ですが、
上記の reproduce.vim は、 `:norm! 3aabc` の後の  `i_CTRL_V<CR>` が消えてますね…
こういう時は、

``` viml
:append
abc
abc
abc
.
```

とか

``` viml
:call append(0, "abc")
:call append(1, "abc")
:call append(2, "abc")
```

が、良いのかなぁ (Vim script 難しい。。。)

**Comment by presuku** [comment]
@h-east 
すみません、確かに移動されていました。
指摘された点を直しました。
https://gist.github.com/presuku/a42e19b17268e4a2149b

**Comment by h-east** [comment]
了解です。Thanks!

**Comment by h-east** [comment]
あー、私のpatchは改行入りの `/` のhighlightは直るけど、`matchaddpos()`でマルチバイトの途中byteから指定すると行末までhighlightされちゃいます。

```
ああああ
いいいい
```

上記バッファ(fenc=utf-8)に対して `/\nい` は正しくhighlightされるけど

``` vim
:echo matchaddpos('Error', [[2,3,2]])
```

が行末までhighlightされてしまう。

**Comment by h-east** [comment]
603の時のpatchは大分ボケてたので新しいpatch書きました。
これで確認してもらえると嬉しいです。

``` diff
diff -r 4604a182f04c src/screen.c
--- a/src/screen.c  Sun Nov 30 22:51:06 2014 +0100
+++ b/src/screen.c  Sun Dec 07 05:54:58 2014 +0900
@@ -3864,9 +3864,15 @@
                && v >= (long)shl->startcol
                && v < (long)shl->endcol)
            {
+#ifdef FEAT_MBYTE
+               int tmp_col = v + MB_PTR2LEN(ptr);
+
+               if (shl->endcol < tmp_col)
+               shl->endcol = tmp_col;
+#endif
                shl->attr_cur = shl->attr;
            }
-           else if (v >= (long)shl->endcol && shl->lnum == lnum)
+           else if (v == (long)shl->endcol)
            {
                shl->attr_cur = 0;
                next_search_hl(wp, shl, lnum, (colnr_T)v, cur);
```

なんで複数行の検索でおかしくなったかはscreen.c 3877行目辺りのコメントを見れば明白ですね。汗。

``` c
/* Need to get the line again, a multi-line regexp
 * may have made it invalid. */
```

**Comment by h-east** [comment]
@presuku 

> また、余談ですが、...

``` vim
:call setline(1, repeat(['abc'], 3))
```

とか、あと空行を気にしなければ
3Oabc<Esc>
とかですかね。

**Comment by h-east** [comment]
sent vim_dev.
https://groups.google.com/d/msg/vim_dev/48Ib2OE6h6c/YmYZ0CGn3CcJ

**Comment by mattn** [comment]
> なんで複数行の検索でおかしくなったかはscreen.c 3877行目辺りのコメントを見れば明白ですね。汗。

確信犯かww

**Comment by presuku** [comment]
@h-east :+1: 
vim_devへの報告ありがとうございます。
また、新しいパッチの確認遅くなって、すみません :sweat: 
こちらでも、直っていること確認できました。

> :call setline(1, repeat(['abc'], 3))

nrhd ! 勉強になります。

@mattn 

> 確信犯かww

ｗｗｗ

**Comment by h-east** [comment]
Patch 7.4.545
https://groups.google.com/d/msg/vim_dev/HA2Lc7FTkLw/cLrcrK483-cJ

@presuku ありがとうございました。presukuさんに検証いただいたおかげで短時間で対応することが出来ました。

**Comment by presuku** [comment]
@h-east いえいえ、こちらこそ報告ありがとうございました！
早速修正されたようで、良かったです。
