### ISSUE TITLE
mingw64 でビルドに失敗する

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#674]
gcc.exe 等は x86_64-w64-mingw32-gcc.exe がある為、アーキテクチャ指定するのが一般的ですが、windres.exe につていはそもそも出力される内容が決まっているので `x86_64-w64-mingw32-` というプレフィックスは不要です。(というか `x86_64-w64-mingw32-windres.exe` はありません)

**Comment by k-takata** [comment]
Cygwin版のMinGW-w64には`x86_64-w64-mingw32-windres.exe`があるので、通常版にないとは知りませんでした。

**Comment by mattn** [comment]
単に windres.exe でいいかもしれませんね。

**Comment by k-takata** [comment]
Cygwin版だと単にwindresだとダメでした。

**Comment by k-takata** [comment]
> /usr/lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld: i386 アーキテクチャ (入力ファイル`gobjx86-64/vimrc.o') は i386:x86-64 出力と互換性がありません

というエラーになりました。アーキテクチャによって、windresの出力は異なっているようです。
こんなのはどうでしょうか。

``` diff
--- a/src/Make_cyg_ming.mak
+++ b/src/Make_cyg_ming.mak
@@ -366,7 +366,11 @@ endif
 endif
 CC := $(CROSS_COMPILE)gcc
 CXX := $(CROSS_COMPILE)g++
+ifeq ($(UNDER_CYGWIN),yes)
 WINDRES := $(CROSS_COMPILE)windres
+else
+WINDRES := windres
+endif
 WINDRES_CC = $(CC)

 #>>>>> end of choices
```

本当は `x86_64-w64-mingw32-windres.exe` にパスが通っているかどうかで判断したいところですが。

**Comment by mattn** [comment]
coff omf で違うのか。そうですね。そのパッチでよさそうです。

On 12/7/14, K.Takata notifications@github.com wrote:

> > /usr/lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld:
> > i386 アーキテクチャ (入力ファイル`gobjx86-64/vimrc.o') は i386:x86-64 出力と互換性がありません
> 
> というエラーになりました。アーキテクチャによって、windresの出力は異なっているようです。
> こんなのはどうでしょうか。
> 
> ``` diff
> --- a/src/Make_cyg_ming.mak
> +++ b/src/Make_cyg_ming.mak
> @@ -366,7 +366,11 @@ endif
>  endif
>  CC := $(CROSS_COMPILE)gcc
>  CXX := $(CROSS_COMPILE)g++
> +ifeq ($(UNDER_CYGWIN),yes)
>  WINDRES := $(CROSS_COMPILE)windres
> +else
> +WINDRES := windres
> +endif
>  WINDRES_CC = $(CC)
> 
>  #>>>>> end of choices
> ```
> 
> 本当は `x86_64-w64-mingw32-windres.exe` にパスが通っているかどうかで判断したいところですが。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/674#issuecomment-65929555

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
> coff omf で違うのか。

そうではなさそうです。

```
$ objdump -f gobji686/vimrc.o

gobji686/vimrc.o:     ファイル形式 pe-i386
アーキテクチャ: i386, フラグ 0x00000039:
HAS_RELOC, HAS_DEBUG, HAS_SYMS, HAS_LOCALS
開始アドレス 0x00000000
```

```
$ x86_64-w64-mingw32-objdump -f gobjx86-64/vimrc.o

gobjx86-64/vimrc.o:     ファイル形式 pe-x86-64
アーキテクチャ: i386:x86-64, フラグ 0x00000039:
HAS_RELOC, HAS_DEBUG, HAS_SYMS, HAS_LOCALS
開始アドレス 0x0000000000000000
```

上記のリンクエラーメッセージと見比べると、アーキテクチャが`i386`と`i386:x86-64`で異なっているのが原因と思われます。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/ZkEJ9xEkZy4/discussion

**Comment by k-takata** [comment]
7.4.548
https://groups.google.com/d/msg/vim_dev/wN1itj19WTU/jA9gMXFNVbYJ

**Comment by mattn** [comment]
:+1:
