### ISSUE TITLE
Windows で長いファイル名のファイルがあるフォルダに対して、ワイルドカードを使うと落ちることがある

### ISSUE THREAD

**Issue by tobynet** [vim-jp/issues#675]
落ちるのでご報告。
# 環境:
- OS: Windows 8.1 Pro (64bit)
- Vim: 7.4.475 Modified by koron.kaoriya＠略
# 再現手順
1. PowerShell を開き、十分に長いファイル名のファイルを作るため、以下を実行する
   
   ``` powershell
   PS C:\> mkdir C:\tmp
   PS C:\> echo "" > C:\tmp\ジジャジャバジャババババジャバジャジャバジャジャバジャジャバジャジャ-ジジャジャバジャババババジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャジャバジャババババババババババババジャバジャバ.txt
   ```
2. http://www.kaoriya.net/software/vim/ から Windows 64bit版Vimをダウンロードする。
   
   これ: http://files.kaoriya.net/goto/vim74w64
3. ダウロードした `vim74-kaoriya-win64-20141012.zip` を `C:\opt\vim74-kaoriya-win64-20141012` に解凍する
4. `~/.vimrc-for-issue` という 中身が `set encoding=utf-8` のみのファイルを作成する。
   - UTF-8Nで作成する
5. ダウンロードしてある gvim.exe をコマンドとともに起動する
   
   ``` powershell
   PS C:\> cd opt\vim74-kaoriya-win64-20141012\vim74-kaoriya-win64\
   PS C:\opt\vim74-kaoriya-win64-20141012\vim74-kaoriya-win64> 
   PS C:\opt\vim74-kaoriya-win64-20141012\vim74-kaoriya-win64> .\gvim.exe -N -u ~/.vimrc-for-issue -U NONE -i NONE --noplugin -c ":e /tmp/*"
   ```
6. Vim は起動するが以下のダイアログとともにすぐさま動作を停止する
   
   ```
   [Window Title]
   Vi Improved - A Text Editor
   
   [Main Instruction]
   Vi Improved - A Text Editor は動作を停止しました
   
   [Content]
   問題が発生したため、プログラムが正しく動作しなくなりました。プログラムは閉じられ、解決策がある場合は Windows から通知されます。
   
   [プログラムの終了(C)]
   ```
   
   ※ 上記のコマンドで落ちない場合は数回くりかえす

vim.exe (CLI版)でも同様に落ちました。

環境によって、落ちないかもしれませんがご報告。

**Comment by k-takata** [comment]
再現しました。
enc=cp932 では落ちなかったので、どこかに MAX_PATH バイトでバッファを確保しているところがありそうです。utf-8 だと MAX_PATH \* 3 バイト必要なのですが。

**Comment by k-takata** [comment]
ここが原因のようです。
https://github.com/vim-jp/vim/blob/b7c8de674b227c674c4ec9a3a174b0059b0dd6e9/src/misc1.c#L9719

``` c
    buf = alloc((int)STRLEN(path) + BASENAMELEN + 5);
```

`BASENAMELEN + 5` を `MAX_PATH * 3` に書き換えたところ、落ちなくなるのは確認しましたが、どう直すのが正しいのやら。

**Comment by tobynet** [comment]
k-takataさん、確認、ありがとうございます。
なるほど、バッファ確保周りでしたか。

他の箇所をみるとUTF-8N対応では k-takata さんの通りのようですが、ぼくもこの対応でいいのかと疑問があります。
https://github.com/vim-jp/vim/blob/f2cbd8ba4e36c091d5579f8e84759f96aba2a008/src/os_mswin.c#L453-L462

BASENAMELEN が適切でないと考えることもできそうです。
https://github.com/vim-jp/vim/blob/3ea8d84f1ba16914854c8aef679d2319788cf9df/src/os_win32.h#L120

**Comment by mattn** [comment]
どういう理屈で -5 なんだろ

**Comment by tobynet** [comment]
> どういう理屈で -5 なんだろ

2004年の vimboss さん[誰？] に聞いてみないといけませんね。

https://github.com/vim-jp/vim/blame/3ea8d84f1ba16914854c8aef679d2319788cf9df/src/os_win32.h#L120

**Comment by k-takata** [comment]
vimboss = Bram で、7.0001 ということは、6.x 以前から引き継がれてきたコードだということになりますね。

`alloc(MAXPATHL);` でいいんじゃないのという気もしなくもない…。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/069J-CMnt6s/discussion
結局、`MAXPATHL` にしてしまいました。

**Comment by k-takata** [comment]
7.4.903
https://groups.google.com/d/topic/vim_dev/pOJYF8bjThI/discussion
もう取り込まれた。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/069J-CMnt6s/8ef8OK4KAQAJ

> Thanks.  Is there any corner case where we would need a few more bytes
> than MAXPATHL?

何と回答しよう。本来ここの部分では MAX_PATH \* 3 bytesあれば十分なはず。

**Comment by k-takata** [comment]
Windows版Vimにおけるパスの長さについての私の理解は…
- `MAXPATHL`: Vim内部におけるパスの最大長(1024)。`char_u`型の要素数。文字コードは`'encoding'`で指定されたもの。
- `MAX_PATH`: Win32 APIにおけるパスの最大長(260)。ANSI APIならば`CHAR`型の要素数、Wide APIならば`WCHAR`型の要素数。文字コードは、カレントコードページ(ANSI)またはUTF-16LE(Wide)。
- `_MAX_PATH`: WindowsのCRTにおけるパスの最大長(260)。`char`または`wchar_t`の要素数。

パスの最大長は、OS共通部分で`char_u`型で扱っている間は`MAXPATHL`バイト、Win32 APIを呼び出す部分は`MAX_PATH`要素というのが基本的な考え方。
Win32固有部分で、かつUTF-8で扱う部分に関しては、`MAX_PATH` \* 3バイト。

**Comment by tobynet** [comment]
ありがとうございました :+1:
