### ISSUE TITLE
mapgroup 欲しい？

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#677]
augroup の map 版が欲しいなーと思ったので試しに実装。

https://gist.github.com/mattn/ca264155959f476bc8dd

``` vim
nnoremap <leader>foo :<c-u>echo "foo"<cr>

function! s:StartMapGroup()
  mapgroup SuperMomonga
    mapclear
    nnoremap <leader>bar :<c-u>echo "bar"<cr>
  mapgroup END
endfunction

function! s:EndMapGroup()
  mapgroup SuperMomonga
    mapclear
  mapgroup END
endfunction

command StartMapGroup :call <SID>StartMapGroup()
command EndMapGroup :call <SID>EndMapGroup()

```

``` vim
:StartMapGroup
```

これを呼び出すと `<leader>bar` が使える

``` vim
:EndMapGroup
```

これを呼び出すと `<leader>bar` が消える。
でも `<leader>foo` は消えない。

mapgroup 外で mapclear するといままでの動作。mapgroup 内で mapclear すると、mapgroup 内で map した物だけ mapclear。

あくまで提案用なのでドキュメントとかいろいろ足りてないですが、こんなのあったら便利ですかね？

残課題
- [ ] ドキュメント
- [ ] syntax highlight

**Comment by koron** [comment]
コンセプトはありだと思います。

異なるmapgroupで同じキーをマップしちゃった場合どうなりますかね?
特にあとから定義したマップのmapgroupを消した場合の動作が気になります。

``` vim
mapgroup A
  mapclear
  noremap <leader>ma :<c-u>echo "foo"<cr>
mapgroup END

mapgroup B
  mapclear
  noremap <leader>ma :<c-u>echo "bar"<cr>
mapgroup END

mapgroup B
  mapclear
mapgroup END
```

**Comment by mattn** [comment]
mapclear 時は ID 指定で消すので、 B のマップが成功しても失敗しても mapclear で A のは消えません。

**Comment by mattn** [comment]
map の更新は中身だけ書き換えるらしいので KoRoN さんの例だと "bar" です。ID も差し替えないとなー。

**Comment by mattn** [comment]
期待する動作(bar が出なくなる)に修正しました。

**Comment by mattn** [comment]
メリットとしては一括で消せるくいしかないですなw

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/du6TOLfgtj0

**Comment by tyru** [comment]
vimrc 再読み込みとかした時に、古いマッピングも残らず確実に消せるので便利ですね (一部の人向け？)。

**Comment by h-east** [comment]
@mattn 
K&R style関数定義あります。
https://gist.github.com/mattn/ca264155959f476bc8dd#file-mapgroup-diff-L84
https://gist.github.com/mattn/ca264155959f476bc8dd#file-mapgroup-diff-L139
https://gist.github.com/mattn/ca264155959f476bc8dd#file-mapgroup-diff-L151
https://gist.github.com/mattn/ca264155959f476bc8dd#file-mapgroup-diff-L177

**Comment by mattn** [comment]
あー。忘れてましたね。

**Comment by mattn** [comment]
更新ed

**Comment by h-east** [comment]
:+1: LGTM

**Comment by k-takata** [comment]
todo入りしているので閉じます。

> Patch to add :mapgroup, put mappings in a group like augroup.
> (Yasuhiro Matsumoto, 2016 Feb 19)

**Comment by k-takata** [comment]
Vim 8.0に入れてもらうようpushした方がいいのだろうか？
