### ISSUE TITLE
xlose/backlog の導入

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#678]
アナウンスするのに良い場所が思いつかなかったのでこのissueで代用します。
良い場所があったら転記してください。

ある程度の期間放置されて直近に解決の見込みが無いissueについて、
[`xlose/backlog`](https://github.com/vim-jp/issues/labels/xlose/backlog) のタグを付けて閉じることができるようにしましょう。タグはもう作成しました。
no action な issueがopenのまま放置されているのは好ましくないという観点で、
それらを閉じて隔離する、もしくはactionを起こしてもらうことが目的です。

閉じる前にはpingを打つことが好ましいです。
また実際に閉じる際にはassignを外しましょう。

このissueは1～3ヶ月程度の周知期間を経たら、fixedもしくはworksformeで閉じてください。

**Comment by h-east** [comment]
賛成です。
「status/paches welcome」も上手く使って運用していければと思います。

**Comment by koron** [comment]
https://github.com/vim-jp/issues/wiki/Member ここに書けば良かったのか。
忘れてた。あとで転記します。

**Comment by h-east** [comment]
ちなみに昨日のClose/Reopen連打は私ではありません。私がPCから目を離している隙にうちの◯◯が勝手にやったことです。ちゃんと言い聞かせましたのでもう連打は発生しません。

**Comment by koron** [comment]
https://github.com/vim-jp/issues/wiki/Member#backlog-%E4%BF%9D%E7%95%99%E4%BD%95%E3%81%8B%E3%81%82%E3%81%A3%E3%81%9F%E3%82%89%E3%81%95%E3%82%89%E3%81%86

書いた。書き始めはinvalidとの違いが不明瞭だったが
わけわかんないけど **重要だと判断** できるかどうか、とした。

**Comment by koron** [comment]
invalid は見なおして整理した。結果、なくなった。

**Comment by h-east** [comment]
@koron xlose/backlogの背景色は #000000 ですが他の既存の xlose/\* の背景色はすべて #444444 になっています。意図したものでしょうか？

**Comment by koron** [comment]
no

**Comment by h-east** [comment]
> no

I just fixed.

**Comment by mattn** [comment]
特に問題なさそうだし反論も無さそうなので閉じます。
