### ISSUE TITLE
Windows のコンソールでも「森鷗外」を表示したい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#681]
現状、Windows の gvim では termencoding が空の時にワイド文字APIが使われて encoding=utf-8 でもちゃんと「森鷗外」が表示されますが、コンソール版の方はワイド文字APIが使われていない為に「森?外」という表示になってしまいます。
以下、森鷗外パッチ

![](http://go-gyazo.appspot.com/23b8d7f30f144e70.png)

https://gist.github.com/mattn/2d55b50ad2044247269a

ただし問題が残ってて、現状入力側に対応出来ていないので、「森鷗外」を入力すると化け文字が出る。
あと毎回 alloc してるのでなんとかしたい。

**Comment by h-east** [comment]
WIP == work in progress. 進行途中。

ってさっき知りました。

**Comment by mattn** [comment]
work in progress ラベル欲しい

**Comment by k-takata** [comment]
> 現状入力側に対応出来ていないので、「森鷗外」を入力すると化け文字が出る。

#189 以来の課題ですね。

**Comment by koron** [comment]
[status/wip](https://github.com/vim-jp/issues/labels/status%2Fwip) 足しました。

**Comment by k-takata** [comment]
mattnさんのパッチをかなりいじりました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/7723b1dcb344ef6b401d705631fcba178d274641/vim-jp-681-type2.diff
- termencoding は無視。（gui_w32.c と同様。）
- バッファは、gui_w32.c / gui_mch_draw_string() と同様に、足りなくなったら確保するように変更。
- FillConsoleOutputAttribute() をセル数ではなく文字数で呼んでいたのを修正。
- g_coord.X の算出が変だったのを修正。
- write_charsW() を write_chars() に統合。

**Comment by k-takata** [comment]
元々のwrite_chars()が出力した文字数を返す仕様なのに、戻り値の型がBOOLになってた…。DWORDに変更。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/b7212f1e907964185c29c62a8e53cb2b203fdaa6/vim-jp-681-type2.diff

**Comment by mattn** [comment]
@k-takata ++

**Comment by k-takata** [comment]
tencを殺したはずが死んでなかったので修正。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/73b7443e9674ed883d270c59aeae22f0e94510c2/vim-jp-681-type2.diff

**Comment by k-takata** [comment]
そして、Unicode入力パッチ
https://bitbucket.org/k_takata/vim-ktakata-mq/src/48fd29dd51519b3493de8b31a89bc7b42aac2906/unicode-input.patch

**Comment by k-takata** [comment]
よく考えると、Unicode入力パッチを入れると、 #189 は要らなくなるのか。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/83f263137c01a69f205f321afc3e354c9c55618f/unicode-input.patch

**Comment by k-takata** [comment]
パッチファイル名を修正
https://bitbucket.org/k_takata/vim-ktakata-mq/src/35b1a87ec692b6e959c38e7bd6d81d577a13dc56/win32console-unicode-display.patch
https://bitbucket.org/k_takata/vim-ktakata-mq/src/35b1a87ec692b6e959c38e7bd6d81d577a13dc56/win32console-unicode-input.patch
https://bitbucket.org/k_takata/vim-ktakata-mq/src/35b1a87ec692b6e959c38e7bd6d81d577a13dc56/win32console-unicode-input_remove-unused-part.patch

**Comment by k-takata** [comment]
ドキュメントの修正を忘れていました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/bf44cbdcc2c9aa568f269993c9c270779e9f5dc8/win32console-unicode-io-doc.patch

**Comment by h-east** [comment]
@k-takata ++
最高の夏にしようぜ:+1:

**Comment by k-takata** [comment]
出したった。
https://groups.google.com/d/topic/vim_dev/9JIamxm-W1M/discussion
mattnさんの名前を出し忘れていてすんません。

**Comment by mattn** [comment]
> mattnさんの名前を出し忘れていてすんません。

いえいえ、パッチまったく変わってしまってるしどうぞどうぞ。

**Comment by k-takata** [comment]
TODO listed:

```
Patch to improve IME handling in the MS-Windows console.
(Ken Takata, 2015 Aug 8)

Patch to support Unicode I/O in the MS-Windows console.
(Ken Takata, 2015 Aug 8)  Also by Yasuhiro Matsumoto.
```

**Comment by k-takata** [comment]
7.4.852
https://groups.google.com/d/topic/vim_dev/Gu7pDIjS1UE/discussion

**Comment by mattn** [comment]
おおおおおおおおおおおおおおおおおお！！！！ @k-takata ++++++++++++++++++++++++++++++++++
