### ISSUE TITLE
complete() を用いて補完を行うと <C-l> で補完候補を選択してしまう

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#682]
``` vim
set nocompatible

inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(col('.'), ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```

再現手順：
1. 上記の .vimrc を用いて Vim を起動する
2. Insert mode で `<F5>` を押す
3. 補完ウインドウが表示された状態で `<C-l>` を連打する
4. `<C-p>` や `<C-n>` を押しているわけではないのに、なぜか補完候補が切り替わる。`<C-p>`と同じ挙動をしてしまっているように見える。ちなみに、`<C-l>`のマッピングは無視される

この挙動は `:help complete()` の仕様に見当たらないので、予期せぬ挙動のように思うのですがどうでしょうか。

```
complete({startcol}, {matches})         *complete()* *E785*
        挿入モード補完の候補を設定する。
        挿入モードでのみ使用できる。CTRL-R = |i_CTRL-R|と組み合わせて
        マッピングを作る必要がある。CTRL-Oの後や、<expr>マッピングの中
        では正しく動作しない。
        {startcol}は補完すべき単語の開始位置を示す、行内のバイトオフセッ
        トである。その位置からカーソルまでのテキストが補完すべき単語と
        なる。
        {matches}はリスト|List|でなければならない。リストの各要素が1つ
        の候補となる。この要素として許される値については
        |complete-items|を参照。
        Note この関数を呼んだ後は補完を停止させるようなテキストの挿入
        をしないように注意しなければならない。
        この関数で設定した候補は普通の挿入モード補完と同じ様にCTRL-Nと
        CTRL-Pで選択できる。設定されていればポップアップメニューが表示
        される。|ins-completion-menu|を参照。
        例: >
    inoremap <F5> <C-R>=ListMonths()<CR>
    func! ListMonths()
      call complete(col('.'), ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
      return ''
    endfunc
<       この例はそれほど役には立たないが、使い方を示している。Note 0が
        挿入されてしまわないように空文字列を返していることに注意。
```

**Comment by mattn** [comment]
https://github.com/vim-jp/vim/blob/f1957ad7bdace5d57e7bd537c7d1e6ebfeffcb69/src/edit.c#L4903

**Comment by Shougo** [comment]
確かに `<C-l>` が特別扱いされているように見えます。これの理由は分かりますでしょうか。

**Comment by mattn** [comment]
行補完の Ctrl_L がポップアップ表示時にも効いてるんだと思います。
パッチ書きます。

**Comment by Shougo** [comment]
では意図しない挙動ということですね。ありがとうございます。

**Comment by mattn** [comment]
https://gist.github.com/mattn/2c83d5a17c9e9505e43d

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/R7i2fb_yynY

**Comment by Shougo** [comment]
ありがとうございます。mattn++;

**Comment by presuku** [comment]
@mattn さんの https://gist.github.com/mattn/2c83d5a17c9e9505e43d を
当てると、普通の行補完がCtrl_Lの連打で候補が切り替わらなくなり、
行補完を多用する場合に、不便になります (個人的な感想ですが)。

また、Ctrl_Lでの候補の切り替えを行わないようにする場合でも、
ステータスラインの `-- Whole line completion (^L^N^P)` のメッセージも直す必要があると思います。

**Comment by mattn** [comment]
そうですね。これ連打で次候補を出せる仕様ですね。パッチ取り消してきました。

On 1/5/15, presuku notifications@github.com wrote:

> @mattn さんの https://gist.github.com/mattn/2c83d5a17c9e9505e43d を
> 当てると、普通の行補完がCtrl_Lの連打で候補が切り替わらなくなり、
> 行補完を多用する場合に、不便になります (個人的な感想ですが)。
> 
> また、Ctrl_Lでの候補の切り替えを行わないようにする場合でも、
> ステータスラインの `-- Whole line completion (^L^N^P)` のメッセージも直す必要があると思います。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/682#issuecomment-68696170

## 
- Yasuhiro Matsumoto

**Comment by Shougo** [comment]
普通の行補完とcomplete()による補完を区別する必要があるのではないでしょうか。

**Comment by mattn** [comment]
んー。complete() 自身が行選択モードで実行されてるのでフラグ用意しないと無理でしたね。

https://gist.github.com/mattn/bd3f2a5ad0dda78da451

１日寝かしますね。

**Comment by Shougo** [comment]
了解です

**Comment by h-east** [comment]
`<F5>`押下後の補完ポップアップメニュー表示中かつ候補が挿入された状態で`<C-L>`を押下した場合は`<C-L>`がそのまま入力されるのが仕様ではないでしょうか？

※根拠
`:help popupmenu-completion`

> ポップアップメニューには 3 つの状態がある:
> 1. 候補が挿入された状態。例えば CTRL-N や CTRL-P の後。

`:help popupmenu-keys`

> 状態1では以下のキーは特別な意味を持つ:

~

> 特殊文字でない任意の文字:
>          候補を変更せずに補完を停止し、入力された文字を挿入する。

# 

`complete()`を呼んだ時点でポップアップメニュー 状態1になり、状態1での<C-L>は`特殊文字でない任意の文字`なのでそのまま入力される。はず。

実際既存のシチュエーション(インサートモードで`<C-P>`入力後に`<C-L>`を入力)だと`<C-L>`がそのまま入力されます。(表示は`^L`)

**Comment by h-east** [comment]
ついでにアドホックじゃないpatch書いてみました。
https://gist.github.com/h-east/be555467ddfc3dfb8d54

**Comment by mattn** [comment]
`ctrl_x_mode == CTRL_X_WHOLE_LINE || ctrl_x_mode == CTRL_X_EVAL` これ多いのでマクロにしませんか

**Comment by h-east** [comment]
@mattn やります。

**Comment by h-east** [comment]
Done.:+1:

**Comment by mattn** [comment]
:+1:

**Comment by Shougo** [comment]
:+1:

**Comment by presuku** [comment]
:+1:

**Comment by Shougo** [comment]
Christian Brabandt  氏がパッチを書いてくれたようです。
こちらのほうが格段に短いようですが、どうでしょうか。

https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/td_FVnHgasAJ

**Comment by h-east** [comment]
https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/Kqs74-R1L5QJ

**Comment by Shougo** [comment]
@h-east 氏のパッチが長いのはマクロによる条件文の置換えも含んでいるからでしょうかね。

**Comment by h-east** [comment]
> パッチが長いのはマクロによる条件文の置換えも含んでいるからでしょうかね。

それ見た目だけの感想ですね。
もう少し踏み込んで考えてみましょう。

**Comment by Shougo** [comment]
- `CTRL_X_COMPLETE` か `CTRL_X_EVAL` かという違い
- @h-east 氏のパッチはマクロを用いて行補完とcomplete()の処理が同等になるように（互換性を壊さないように）しているが、Christian氏のパッチはそうではない。

そもそも、`complete()`の実装に行補完が使われていた理由がよくわからないのです。
そこに理由があるのなら@h-east氏のパッチが正しいですし、そうでないならChristian氏のほうが正しいように見えます。

```
/* Handle like dictionary completion. */
ctrl_x_mode = CTRL_X_WHOLE_LINE;
```

元々のコードはコメントでは dictionary completion なのに、コードは line completion なのも気になります。

**Comment by mattn** [comment]
いや、ちゃんとコード追ってないでしょw

**Comment by mattn** [comment]
@h-east これ ctrl_x_msgs 足さなくて問題無いですか？

**Comment by h-east** [comment]
@mattn あっ、足さないとダメですね。Thanks!
文言どうしましょ？(たぶん表示されることはないと思うんですけど)
" Builtin function completion (^N^P)" でよかですか？

**Comment by mattn** [comment]
![](http://livedoor.blogimg.jp/elvis003/imgs/9/3/93e9c540.jpg)

**Comment by h-east** [comment]
こらーwww OK牧場!

**Comment by mattn** [comment]
それか NULL でもよさげです。

**Comment by h-east** [comment]
@mattn 撤回。`set_complete()`経由の場合は`compl_started = TRUE`してから`ins_complete()`を呼び出しているので、ctrl_x_msgs[]参照処理(5381行目辺り)は通らないので足さなくてもいいですね。

でも気持ち悪いっちゃぁー気持ち悪いですのでNULL足しときますか。

**Comment by mattn** [comment]
17番足す人の為に16に穴開けといた方がいいすね。

**Comment by h-east** [comment]
Updated Gist. (Added line 19)

**Comment by mattn** [comment]
LGTM

![](http://slot2ch.net/wp-content/uploads/2013/09/e39597268ba150c7693c9ee6d51a1a8c.jpg)

**Comment by Shougo** [comment]
パッチの変更とedit.c のコードを追ってみました。
- 4200 行付近：`complete()`による補完の時もcompleteオプションを参照して補完先を決めているようですが、これは`complete()`にも必要なのでしょうか
- 4200 行付近：コメントは`^X^L`となっており、`complete()`について触れられておりません
- 3805 行付近：行補完または`complete()`のときline breakをしないようですが、これだと`complete()`の補完の挙動が他（オムニ補完やcompletefunc補完）と異なってしまいます。`complete()`に関しては他に合わせてline breakするべきだと思います。
- 5348 行付近：行補完または`complete()`のときインデント保持、コメント無視となっています。行補完に関しては処理が妥当と思いますが、`complete()`に対しても同様に処理するのはなぜでしょうか。

**Comment by Shougo** [comment]
パッチの動作確認も行いました。

@h-east 氏のパッチで `<C-l>` のマッピングは動作するようになっているようです。ありがとうございます。

Christan 氏のパッチも試しました。こちらも `<C-l>`のマッピングが動作するようになりましたが、`complete()`による補完ウインドウが表示されている時に`<C-h>`を入力すると"Internal error: ins_complete" となります。
@h-east 氏のパッチではこのような問題はありませんでした。

**Comment by h-east** [comment]
@Shougo 話の流れとコードの流れを掴みましょう。

●本Issueの主題
「`complete()`の時に`<C-L>`が次候補に切り替わるのおかしいので直しましょう」 

●コード修正の流れ
1. `complete()`は行補完のロジックを通す形で実装されている。(ctrl_x_mode ← CTRL_X_WHOLE_LINE)
2. もちろんキー入力による制御処理も同じ。
3. では内部的にモードを分けましょう。(`complete()`時はctrl_x_modeに新設のCTRL_X_EVALをセットするようにした)
4. キー入力制御部分でCTRL_X_EVALとCTRL_X_WHOLE_LINEで処理を分けることにより本Issueの主題を解消。
5. キー入力制御部分以外のロジックは今までの動作と同じになるようにCTRL_X_EVALとCTRL_X_WHOLE_LINEで同じ処理をさせましょう。(後方互換のため機械的に修正)

4 でこのIssueの主題は解消されているし、todoリストにも記載されたのでクローズしようと思っています。
君が質問しているのは 5 に関してのことでありそこは私のpatchの有無に関係なく同じ動作をするところです。本Issueの主題からずれてると思うので別Issue立てて頑張って下さい。

# 

質問に対する質問 (行番号はpatchあてた場合のもの)
- `complete()`呼び出しで実際に4219行目や3816行目や5356行目のロジックに入ることを確認しましたか？

**Comment by Shougo** [comment]
> キー入力制御部分以外のロジックは今までの動作と同じになるようにCTRL_X_EVALとCTRL_X_WHOLE_LINEで同じ処理をさせましょう。(後方互換のため機械的に修正)

特に深い意味はなく、互換性のために機械的に修正したということですね。それは分かりました。
`complete()` における line break の問題に関しては私の方で困っておりますので、別の Issue を立てます。他に関しては実際に問題が出てから Issue を立てることにします。

> complete()呼び出しで実際に4219行目や3816行目や5356行目のロジックに入ることを確認しましたか？

これは正式にこちらでも確認を行いますが、少なくとも 3816 行に関しては `complete()` だと line break にならないのでロジックに入っているはずです。

**Comment by Shougo** [comment]
```
Using CTRL-L while popup menu is visible behaves like CTRL-P, which is wrong.
Patch by Yasuhiro Matsumoto, 2015 Jan 5.
Is this right?  Comment from Amadeus Demarzi.
Another patch from Christian, Jan 6.
Comment from Hirohito Higashi, Jan 6.
```

7.4.567 にて Todo リスト入りを確認しました。この問題自体の解消も確認したので閉じます。

**Comment by Shougo** [comment]
確認作業を行いました。

> complete()呼び出しで実際に4219行目や3816行目や5356行目のロジックに入ることを確認しましたか？

3816 行目と 4219 行目のロジックに関しては `complete()` 呼び出しだけでは到達できず、
https://github.com/vim-jp/issues/issues/685 により行補完になった時にのみ到達するようです。

5356 行目の到達はそもそも確認できませんでした。

> complete() における line break の問題に関しては私の方で困っておりますので、別の Issue を立てます。他に関しては実際に問題が出てから Issue を立てることにします。

処理タイミングが違うようなので、今の段階で line break に関する別 issue を立てるのはやめておきます。お騒がせしました。

**Comment by h-east** [comment]
todoリスト更新された。
https://github.com/vim-jp/vim/commit/9440f7f9dc4ac854667419918a6c056080681258#diff-38d7929bd26d74d92ceddf984bbfc8dbR128

`complete()`の第1引数と`backspace`オプションにstartがない場合の仕様不整合の件も別途todoリストに入った。
https://github.com/vim-jp/vim/commit/9440f7f9dc4ac854667419918a6c056080681258#diff-38d7929bd26d74d92ceddf984bbfc8dbR111

**Comment by Shougo** [comment]
ありがとうございます。

※：このissueとは関係無いですが、vim-jp/vimのtodo.txtの該当部分を明示してくれるのは非常にわかりやすくて助かります。

**Comment by h-east** [comment]
Patch 7.4.653
https://groups.google.com/d/msg/vim_dev/ZEQzTII6eRg/GVTiWtFUwkcJ

**Comment by Shougo** [comment]
修正を確認しました。対応ありがとうございました。
