### ISSUE TITLE
complete()による先頭マッチしない補完を連続で行った場合、ドットレジスタの値がおかしくなる

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#683]
``` vim
set nocompatible

call append(1, 'aa11')
call append(1, 'aa11')

inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(1, ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```

再現手順：
- 上記 .vimrc を利用する
- `/11<CR>` により aa11 に飛ぶ
- `cw` でインサートモードに入る
- `<F5><C-p>2<F5><C-p>2<ESC>` （手動補完を出しつつキャンセルして 2 を入力することを 2 回繰り返す）
- `n.`

予想される結果:

```

aa22
aa22
```

実際の結果：

```

aa22
aa2
```

Edit: 現在この現象は `complete()`でのみ確認しているため、タイトルを変更しました。

**Comment by Shougo** [comment]
再現した環境： Vim 7.4.542
Ubuntu 14.04 です。

**Comment by Shougo** [comment]
追記：

#682 のパッチを適用した状態でも、この問題は再現することを確認しました。

**Comment by ghost** [comment]
まずは素の7.4.567で再現確認しました。Cygwin、DOS窓。

**Comment by Shougo** [comment]
確認ありがとうございます。

**Comment by ghost** [comment]
#682 の追加でも再現はします。
つーか最後の一文字しかドットレジスタに入ってこないのが問題という解釈でいいんですかねこれ…
2,2 ではなくたとえば今思い付きで 2,1,0 としてみたら 0 だけがドットレジスタに入ってくるけれど
2,1 はどこ行っちゃったのという部分をどうにかしないと困る局面を知ってみたいです。ある意味。

**Comment by ghost** [comment]
あ、cw0か…どうなんですかね、本当どこ行っちゃってんだろ…最後の一文字だけってわけでもないか
補完キャンセル直後に打った文字が食われてる感あるのでちょっと見てみます。ちょっとだけよ。

**Comment by h-east** [comment]
これは`complete()`の問題というよりインサートモードとカーソルキーの組み合わせの既知の問題だと思いますよ。
vim-jpにもいくつかissue上がってます。今出先なので番号までは書かないけど。

**Comment by ghost** [comment]
あら、なら見るのはちょっと待ちます。
というかいわゆる「取り急ぎ修正が必要なバグ」では「ない」という話ですね…。

**Comment by Shougo** [comment]
> これはcomplete()の問題というよりインサートモードとカーソルキーの組み合わせの既知の問題だと思いますよ。
> vim-jpにもいくつかissue上がってます。今出先なので番号までは書かないけど。

これでしょうか。

https://github.com/vim-jp/issues/issues/545

Issue を作成する前に既存のものをチェックしていましたが、今回の話は日本語入力とは関係がなかったので別の問題として認識しておりました。

**Comment by presuku** [comment]
#661 じゃないかな？

**Comment by h-east** [comment]
@presuku それです！フォローありがとうございます。

All>
あくまでも現時点での予測です。
本Issueが本当に661と同根かは調査しないと分からないです。
「調査してやるぜ！」って方歓迎します。

**Comment by Shougo** [comment]
情報ありがとうございます。#661 を確認しました。そちらもドットレジスタがクリアされるので、確かに症状としては似ています。
しかし、今回の場合は特殊キーの入力のタイミングでドットレジスタがクリアされるのではなく、`complete()` を呼んだタイミングでクリアされるようでした。

具体的には、`<F5><C-p>2<F5><C-p>2<ESC>` のうち `<F5><C-p>2` を押したタイミングでは、ドットレジスタに "2" が格納されています。しかし、二度目の `<F5><C-p>2` では `<F5>` を押した時にドットレジスタがクリアされ、その後 "2" が格納されるようです。よって、ドットレジスタには "22" ではなく "2" が入ります。

**Comment by Shougo** [comment]
> あくまでも現時点での予測です。
> 本Issueが本当に661と同根かは調査しないと分からないです。
> 「調査してやるぜ！」って方歓迎します。

実際に調査しました。#661 と同様に、`complete()` の呼び出しで `ResetRedobuff()` が呼ばれるのが今回の症状の原因のようでした。どこから呼ばれたのか調査したところ、edit.c の `edit()` における `ResetRedobuff()` 呼び出し（440 行目）が原因だと思われます。いかがでしょうか。

```
    int
edit(cmdchar, startln, count)
    int     cmdchar;
    int     startln;    /* if set, insert at start of line */
    long    count;
{
...
    if (cmdchar != NUL && restart_edit == 0)
    {
    ResetRedobuff();
    AppendNumberToRedobuff(count);
#ifdef FEAT_VREPLACE
    if (cmdchar == 'V' || cmdchar == 'v')
    {
        /* "gR" or "gr" command */
        AppendCharToRedobuff('g');
        AppendCharToRedobuff((cmdchar == 'v') ? 'r' : 'R');
    }
    else
#endif
    {
        AppendCharToRedobuff(cmdchar);
        if (cmdchar == 'g')         /* "gI" command */
        AppendCharToRedobuff('I');
        else if (cmdchar == 'r')        /* "r<CR>" command */
        count = 1;          /* insert only one <CR> */
    }
    }
```

**Comment by Shougo** [comment]
調査結果２です。

前回の調査の後、`ResetRedobuff()`の呼出しを無効化しましたが、この問題に対して効果はありませんでした。今回の問題の原因はこれでないことになります。

その後、コードをコメントアウトしながら問題を追っていたところ edit.c 内の ins_complete() で `ins_compl_next()` を呼ぶとこの現象が起こることを発見しました。
`ins_compl_next()` 中の `ins_bytes()` でレジスタの破壊が起こっているようなのですが、私にはこれ以上の調査が出来ませんでした。

```
/*
 * Do Insert mode completion.
 * Called when character "c" was typed, which has a meaning for completion.
 * Returns OK if completion was done, FAIL if something failed (out of mem).
 */
    static int
ins_complete(c)
    int     c;
{
    char_u  *line;
    int     startcol = 0;       /* column where searched text starts */
    colnr_T curs_col;       /* cursor column */
    int     n;
    int     save_w_wrow;

...
    /*
     * Find next match (and following matches).
     */
    save_w_wrow = curwin->w_wrow;
    n = ins_compl_next(TRUE, ins_compl_key2count(c), ins_compl_use_match(c));

...
```

私の乏しい知識ではここまでが限界だったのですが、どなたかもっと詳しい調査をお願いできないでしょうか。

**Comment by mattn** [comment]
補完中に走る ins_redraw から apply_autocmds が呼ばれ、apply_autocmds_group の中で呼んでる saveRedobuff でリドゥバッファ(. レジスタの事)が途中段階ながら保存されます。なので

```
<F5><C-p>2<F5><C-p>3<ESC>
```

1回目と2回目の間で ins_redraw が実行され、結果 saveRedobuf が呼ばれます。
vim の補完はバッファを実際に編集しながら行う補完なので、この辺の流れを変えるのは難しいし、バッファを変えないタイプの補完へ変更を提案するのは拒絶されると思う。

**Comment by mattn** [comment]
まぁ、一度補完が実際に終わっていてバッファも変更されているから redraw でリドゥバッファ保存されてしかりだとは思うけど

``` diff
diff -r fee313e21905 src/fileio.c
--- a/src/fileio.c  Wed Dec 10 14:54:50 2014 +0900
+++ b/src/fileio.c  Mon Jan 19 20:20:26 2015 +0900
@@ -9430,7 +9430,8 @@
     if (!autocmd_busy)
     {
    save_search_patterns();
-   saveRedobuff();
+   if (!ins_compl_active())
+       saveRedobuff();
    did_filetype = keep_filetype;
     }
```

これを試して問題が無ければアタリかもね。

**Comment by Shougo** [comment]
ありがとうございます。試してみます。

**Comment by Shougo** [comment]
こちらで該当ソースを直接変更して試しました。
完璧です。mattn さんありがとうございます。

vim_dev への投稿をお願いできないでしょうか。

**Comment by mattn** [comment]
同じ結果だとしても手を入れる箇所が妥当かどうかの判断は要ります。

**Comment by Shougo** [comment]
ここでパッチを寝かせておくより、 vim_dev にパッチを投稿して、皆に変更の妥当性を判断してもらったほうが良いと思いますがいかがでしょうか。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/HwQECMOtgLM

**Comment by h-east** [comment]
早っ！もう取り込まれた。

**Comment by mattn** [comment]
いや、Bram の加えた修正で直ってないです。

**Comment by mattn** [comment]
7.4.630
https://groups.google.com/forum/#!topic/vim_dev/oYAnQp7tZOA
7.4.633
https://groups.google.com/forum/#!topic/vim_dev/C_0i9CVhYYs

**Comment by Shougo** [comment]
投稿ありがとうございます。
今回はマージが早かったですね。
