### ISSUE TITLE
complete()による補完時に<C-h>を押すと行補完になる

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#685]
```
set nocompatible

call append(1, 'aa11')
call append(1, 'aa11')

inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(1, ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```
- 上記 .vimrc を利用する
- 一行目でインサートモードに入り`aa<F5>`を押す
- 補完された文字列を`<C-p>`でキャンセル、`<C-h><C-h>`でaaを削除する
- 補完文字列がなくなった時、ステータス行になぜか行補完を示すメッセージが表示される

おそらく、`complete()`の実装に行補完を利用していることによる副作用だと思います。

https://github.com/vim-jp/issues/issues/682 のパッチを利用した場合、 `<C-h><C-h>` を押した時（aa を削除する）には補完ウインドウが出ず症状は改善されているようですが、 `<C-h>` を一度だけ押した時（a のみを削除する）はやはり行補完となってしまいます。Vim 7.4.567 in Ubuntu 14.04 にて検証。

Edit:  申し訳ありません。手順が間違っていたので訂正しました。

Edit: 682 のパッチを適用した時の検証結果を更新しました。

**Comment by h-east** [comment]
682パッチの有無に関係なく再現しないよ。

**Comment by ghost** [comment]
素の7.4.567で再現できてません。普段使ってる二つ、Cygwin と DOS窓どちらもです。

**Comment by Shougo** [comment]
申し訳ありません。手順が間違っており、最初示した手順では再現に不十分だったようです。
手順を訂正したのでもう一度試してもらえますでしょうか。

**Comment by h-east** [comment]
> #682 のパッチを利用した状態でも確認しましたが、#682のパッチでも直っていないようです。

Please reconfirm this.

**Comment by h-east** [comment]
682patchなしだと再現するけど、682patchありでは再現しないです。
(Vim 7.4.567 on Ubuntu 12.04)

もいっかい私のGistから682patch引っ張ってきてあて直して確認してもらえますか。
(最終更新日は2015/01/07 11:02)
https://gist.github.com/h-east/be555467ddfc3dfb8d54

**Comment by Shougo** [comment]
検証ありがとうございます。こちらでも 682 patch を適用して、再度試しました。
結果を更新しましたので、確認をお願いできますでしょうか。

**Comment by h-east** [comment]
682patchありでは再現しないです。(Vim 7.4.568 on Ubuntu 12.04)

正直このpatchでその現象起きようがないはずなんですけどね。
あなたのあてている682patchは正しいですか？(Gistに貼る等して正当性を証明してもらえますか)
もしくはpatchあてた時にwarning出ませんでした？

もしくは再現手順に不足があるか。

# 

再現手順の伝達ミス多過ぎません？
もしかして「再現手順を作成後に一時的に`アホ`になってその状態で再現手順を実行する」という割と基本的なテクニックをマスターしていないのですか？

それと再現手順を一部日本語で書くと実際にどう入力すればいいかブレるのでやめたほうがいいです。
(日本語で補足するのはもちろんOK)
以下のように、使用するファイルの内容、Vim起動時のコマンドライン、入力文字を書けばほぼ100%伝わります。(ある程度のIT知識を必要としますが)
あとは「期待する動作」「実際の動作」を書けば完璧でしょう。

```
$ cat ~/test685.vim
set nocompatible

call append(1, 'aa11')
call append(1, 'aa11')

inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(1, ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```

Vim起動

``` bash
$ vim -u ~/test685.vim
```

Vimで以下を入力

``` vim
iaa<F5><C-P><C-H>
```

**Comment by Shougo** [comment]
> 正直このpatchでその現象起きようがないはずなんですけどね。
> あなたのあてている682patchは正しいですか？(Gistに貼る等して正当性を証明してもらえますか)
> もしくはpatchあてた時にwarning出ませんでした？

patch をあてたときのメッセージです。

```
$ patch -p1 <682_east.patch
patching file src/edit.c
patch unexpectedly ends in middle of line
Hunk #19 succeeded at 5354 with fuzz 1.
```

使用したパッチは https://gist.github.com/Shougo/c1f212fdff7a5a3b1ae5 です。

パッチを当てた後、 #682  の問題が直っていることは確認しています。

**Comment by Shougo** [comment]
> 682patchありでは再現しないです。(Vim 7.4.568 on Ubuntu 12.04)

![complete](https://cloud.githubusercontent.com/assets/41495/5738622/b72f4534-9c31-11e4-9ae0-fb00db3cdcc0.png)

私の環境ではこうなりました。これは行補完にしか見えないのですがいかがでしょうか。

**Comment by Shougo** [comment]
> 再現手順の伝達ミス多過ぎません？
> もしかして「再現手順を作成後に一時的にアホになってその状態で再現手順を実行する」という割と基本的なテクニックをマスターしていないのですか？
> 
> それと再現手順を一部日本語で書くと実際にどう入力すればいいかブレるのでやめたほうがいいです。
> (日本語で補足するのはもちろんOK)
> 以下のように、使用するファイルの内容、Vim起動時のコマンドライン、入力文字を書けばほぼ100%伝わります。(ある程度のIT知識を必要としますが)
> あとは「期待する動作」「実際の動作」を書けば完璧でしょう。

ミスが多い点については申し訳ありません。
できるだけ日本語を使わずに再現手順を組み立てるように努力します。

**Comment by h-east** [comment]
おいおい、最初の不具合動作内容は

> 補完文字列がなくなった時、ステータス行になぜか行補完を示すメッセージが表示される

で、私が再現しないと返したら

> 申し訳ありません。手順が間違っており、最初示した手順では再現に不十分だったようです。
> 手順を訂正したのでもう一度試してもらえますでしょうか。

と「手順」だけ修正したといっているけど「不具合動作内容」も変わってるやん！

> <C-h> を一度だけ押した時（a のみを削除する）はやはり行補完となってしまいます。

しかも「やはり行補完」という文言で「不具合動作内容」が変わっているって認識出来る訳がないよ。
自分で不具合動作内容変わったと認識してるんだからそれをちゃんと分かりやすく伝えないと。

# 

そしてこの動作内容については
https://github.com/vim-jp/issues/issues/682#issuecomment-69136376 の5に該当するので頑張ってpatch書いて下さい。

# 

patchあてる時にwarningが出る件は修正しました。

**Comment by Shougo** [comment]
> しかも「やはり行補完」という文言で「不具合動作内容」が変わっているって認識出来る訳がないよ。
> 自分で不具合動作内容変わったと認識してるんだからそれをちゃんと分かりやすく伝えないと。

確かに、不親切でした。申し訳ありません。

> そしてこの動作内容については
> #682 (comment) の5に該当するので頑張ってpatch書いて下さい。

分かりました。

> patchあてる時にwarningが出る件は修正しました。

修正ありがとうございます。

**Comment by h-east** [comment]
既存のバグを踏んでしまったようです。patch送付済み。
https://groups.google.com/d/msg/vim_dev/m7i3wZSFwtA/STPQOorfmDIJ

要は`<C-H>`で単語全体が消されたらオムニ補完以外は補完動作を終了させないといけないのに、変な条件になっていたので 16`CTRL_X_EVAL`の時に変な状態のまま再補完が動き出してたってことです。

**Comment by h-east** [comment]
あっ、上のpatchあてても再現するね。ごめん、眠い。一旦寝る。

**Comment by h-east** [comment]
ちょっと整理。
1. このIssueの問題を修正するためには`ins_compl_bs()`内で`ins_compl_restart()`を呼ばれないようにすれば良いと思っている。
2. 解析し始めたら変なコードを発見してしまったのでvim_devにpatch送付。  
   https://github.com/vim-jp/issues/issues/685#issuecomment-70337102 (※このpatchでは本Issueの現象は直らない)
3. 頑張って本Issueの現象を直そうと思ったら類似の不具合を見つけてしまった & 月曜日がやって来た。

ということでまた来週(^^)/~~~

**Comment by h-east** [comment]
類似の不具合の再現手順だけは書いておこう。

``` bash
$ cat ~/test685.vim
```

``` vim
inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(1, ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```

Vim起動

``` bash
$ vim -N -u ~/test685.vim
```

操作

``` vim
iab<Esc>a<F5><C-H><C-H><C-H><C-H><C-H><C-H><C-H>
```

期待する動作: すべての文字が削除される。(?? よくわからん)
実際の動作: 7回目の<C-H>押下時、先頭の`J`が削除されない。

ソース解析前の考察:
`backspace`オプションに`start`が含まれていれば再現しない。このオプションと`complete()`の第一引数が`1`(インサートモード開始よりも前の位置)の場合との調停がうまく出来ていない？

**Comment by Shougo** [comment]
再調査ありがとうございます。

> 要は<C-H>で単語全体が消されたらオムニ補完以外は補完動作を終了させないといけないのに、変な条件になっていたので 16CTRL_X_EVALの時に変な状態のまま再補完が動き出してたってことです。

Christian 氏のパッチだと `complete()` が行補完と別の扱いになるのでこの問題はありませんが、
今度は補完の絞り込みや補完のポップアップウインドウでの候補選択が出来ないなど、内部状態がおかしくなることを確認しています。
やはり現在の実装をベースに問題を少しずつ治していく @h-east 氏のアプローチが正しいように感じます。

**Comment by h-east** [comment]
Patch 7.4.590
https://groups.google.com/d/msg/vim_dev/qD12fwsR3W8/5E5dZl_kzi8J

補足:
連番っぽい値を持つ変数に対してbit ANDしていた件 (https://github.com/vim-jp/issues/issues/685#issuecomment-70337102) がfixされただけであり本Issueには直接的には関係ないです。

本Issueのfixは今週末やるぜ!!(maybe)

**Comment by h-east** [comment]
patch更新。これで本Issueの件は直ったと思うので確認お願いします。
https://gist.github.com/h-east/be555467ddfc3dfb8d54
今回の変更箇所は82行目のみ。`complete()`補完の場合は`<BS>`押されても再補完動作`ins_compl_restart()`をおこなわないようにした。

# 

ただ私が報告した分( https://github.com/vim-jp/issues/issues/685#issuecomment-70414954 )は挙動は変わったけど直っていない。
これは`ソース解析前の考察`に書いてあるとおりで仕様的にどうするか決めないといけない。

> `backspace`オプションに`start`が含まれていれば再現しない。このオプションと`complete()`の第一引数が1(インサートモード開始よりも前の位置)の場合との調停がうまく出来ていない？

仕様案
1. `complete()`の第1引数`startcol`を現在のカラムと`backspace`の値を踏まえて調整してから補完を開始する。  報告内容の場合、`startcol`は1だが内部で3に変更して補完開始。  
2. `complete()`開始後の`<BS>`キー押下時は`backspace`の値に関わらず`startcol`まで削除可能とする。

私は `1.` が良いと思ってる。`2.`はいろいろ弊害が起きそう。
What do you think?

**Comment by Shougo** [comment]
ありがとうございます。パッチについて確認しておきます。

> 私は 1. が良いと思ってる。2.はいろいろ弊害が起きそう。
> What do you think?

`2.` は仕様変更になってしまうので、`1.`が妥当だと思います。

**Comment by h-east** [comment]
`1.`も仕様変更ですよ。

**Comment by Shougo** [comment]
たしかにそうですね。`1.` の方は開始時にのみ挙動が変わりますが、`2.`は`complete()`中に`<BS>`を押した時全てに影響が出るので影響範囲が大きく、副作用がどの程度あるのか予想が難しいです。
よって `1.` の方が良いと思います。

**Comment by h-east** [comment]
いつも微妙にズレた返しをするよね〜。放置。

**Comment by Shougo** [comment]
パッチを当てることにより、このバグが治っていることを確認しました。問題ありません。

**Comment by h-east** [comment]
#692 に統合するので閉じます。

**Comment by Shougo** [comment]
了解です
