### ISSUE TITLE
eval('$') は 0 でなくエラーになるべきではないか

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#687]
`eval('not_defined_variable')` はエラーになるのだから `eval('$')` はエラーになるべきなのではないか。

**Comment by haya14busa** [comment]
ありがとうございます. ~~おそらくですが, `$` 以降に何を書いてもエラーにならないようになっているようです. `eval('$hogefoovim')`~~ EDIT: `:echo $hogefoovim`が動くので後ろに文字をつけた場合はこの挙動で正しいようです

**Comment by haya14busa** [comment]
あーということは環境変数として扱われてるってことかな

**Comment by mattn** [comment]
環境変数名が無い時にエラーを出していない。

``` diff
diff -r ab36689121ad src/eval.c
--- a/src/eval.c    Wed Dec 17 21:00:49 2014 +0100
+++ b/src/eval.c    Sat Jan 10 01:31:54 2015 +0900
@@ -7867,7 +7867,10 @@
     if (evaluate)
     {
    if (len == 0)
-           return FAIL; /* can't be an environment variable */
+   {
+       EMSG2(_(e_invexpr2), name-1);
+       return FAIL; /* can't be an environment variable */
+   }

    cc = name[len];
    name[len] = NUL;
```

**Comment by haya14busa** [comment]
ありがとうございます! mattn さんのパッチをあてて `:echo eval('$')`でエラーが出ることを確認しました. :+1:

```
:echo eval('$')
E15: Invalid expression: $
0
```

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/UrC8oc3LtB4

**Comment by mattn** [comment]
7.4.574

https://groups.google.com/forum/#!topic/vim_dev/5Ea1EuFNEvg

**Comment by haya14busa** [comment]
ありがとうございました. mattnさん++ :+1:
