### ISSUE TITLE
`set breakindent`かつ折り返し行の先頭が半角空白の場合、行をまたいだ矩形選択での削除でずれて削除される

### ISSUE THREAD

**Issue by hail2u** [vim-jp/issues#689]
![temp](https://cloud.githubusercontent.com/assets/68940/5894136/685dfb86-a540-11e4-8b88-a447518bd1cd.gif)
- `set breakindent`
- 折り返しの行頭が半角空白

この場合に矩形選択を使って削除した場合に削除される文字がずれることがある。アニメーションGIFの例だと、本来は“5”まで削除されるべきだが、削除されない。vimrc読み込みなし・プラグインなし(`gvim -u NONE`)で起動した後に`set breakindent`するだけで再現した。`shiftwidth`などのインデント系の設定は関係なさそう。

Tested on: Vim 7.4 MS-Windows 64 ビット GUI 版
適用済パッチ: 1-475

**Comment by h-east** [comment]
@hail2u Issue登録ありがとうございます。こちらでも再現しました。

All>
これでいろいろ試してもらえると嬉しいです。

``` diff
diff -r 435956324539 src/ops.c
--- a/src/ops.c Sun Jan 25 13:02:57 2015 +0100
+++ b/src/ops.c Mon Jan 26 16:27:36 2015 +0900
@@ -5308,10 +5308,7 @@
        {
        /* Count a tab for what it's worth (if list mode not on) */
        prev_pend = pend;
-       /* TODO: is passing prev_pend for start of the line OK?
-        * perhaps it should be "line". */
-       incr = lbr_chartabsize_adv(prev_pend, &pend,
-                             (colnr_T)bdp->end_vcol);
+       incr = lbr_chartabsize_adv(line, &pend, (colnr_T)bdp->end_vcol);
        bdp->end_vcol += incr;
        }
        if (bdp->end_vcol <= oap->end_vcol
```

自信なさげなコメントの通りで第1引数は`line`じゃないとダメです。:smile:
行頭からの文字列を渡してあげないと`breakindent`を実施していいかの判定がおかしくなる。

```
/* TODO: is passing prev_pend for start of the line OK?
* perhaps it should be "line". */
```

**Comment by h-east** [comment]
vim_devに投げました。
https://groups.google.com/d/msg/vim_dev/B8k0AVlqMUU/qKXeY8srpGcJ

**Comment by h-east** [comment]
Patch 7.4.594 :metal:
https://groups.google.com/d/msg/vim_dev/mYVZ3z0OifM/iWYwfzBEVMAJ

**Comment by hail2u** [comment]
ありがとうございました！
