### ISSUE TITLE
complete() で補完を行うと自動折り返しが無効になる

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#692]
`complete()` を用いて補完を行うと自動折り返し機能が無効になります。
インサートを一度抜けるまで無効のままです。

``` vim
set nocompatible
set textwidth=5

inoremap <F5> <C-R>=ListMonths()<CR>

func! ListMonths()
  call complete(1, ['January', 'February', 'March',
        \ 'April', 'May', 'June', 'July', 'August', 'September',
        \ 'October', 'November', 'December'])
  return ''
endfunc
```

再現方法：
1. `vim -u test.vimrc`
2. `iabcde<F5><C-p> fghij`

期待される結果：

```
abcde
fghij
```

実際の結果：

```
abcde fghij
```

※： `abcde<F5><C-e> fghij` だと、自動折り返しが無効にならないようです。

**Comment by ghost** [comment]
Cygwin 7.4.591 で確認しました。ちょっと見てみます。

**Comment by Shougo** [comment]
よろしくお願いします。

`complete()`の実装に使われている行補完は自動折り返しを無効にするようなので、それが影響しているようです。

**Comment by ghost** [comment]
ちょっと見てました。
`set formatoptions+=a` がキモかと思ってたらそうでもなかったパターン…
それ以上のまとまった情報はいまのところありませんで、しばらく寝ます。0600時あたりから再開。

**Comment by mattn** [comment]
@ntak https://github.com/vim-jp/vim/blob/master/src/edit.c#L3804-L3831

これかと思います。

**Comment by h-east** [comment]
Gist更新。まっつんさん指摘箇所を`complete()`時には入らないように修正。
https://gist.github.com/h-east/be555467ddfc3dfb8d54

**Comment by ghost** [comment]
オオーウ(;´Д`)助かりました、ありがとうございます…考え方を改めないといかんようですね…
正直まだよくわかっておりませんで、よっていろいろ研究してみます。

**Comment by h-east** [comment]
@ntak `complete()`は内部的に行補完と同じロジックで動いているというのが #682 で判明したので、`complete()`処理と行補完処理を処理を分離させるpatchを書きました。ただ、完全に分けるのは時間と労力が大変なので#682の対応に必要な箇所だけ最低限分離させてその他は今まで通りになるように機械的に修正しました。
https://github.com/vim-jp/issues/issues/682#issuecomment-69136376
`機械的に修正した`部分に対応漏れがあるかもしれないのは承知で、それは発覚した時点で私のpatchを修正していけば良いとShougoさんには伝えたつもりなんだけど伝わってないや。

> 君が質問しているのは 5 に関してのことでありそこは私のpatchの有無に関係なく同じ動作をするところです。本Issueの主題からずれてると思うので別Issue立てて頑張って下さい。

ですので、私のpatchをあてずに`complete()`と行補完が混ぜこぜになるのは当然であり、私のpatchをあてた状態で検証しないのは無駄であります。

何が良いたいかというと...
私のpatchをあてていないVimで発生した「`complete()`と行補完が混ぜこぜになる不具合」Issueを登録し、私のpatchのことに言及しない& #682 のリンクも貼らないShougoさんお疲れですか？

**Comment by ghost** [comment]
あらまあややつこしい…(;´Д`)空足踏んだのかしら…
ただまあいろんなひとがいてたのしい人生ヽ(´ー｀)ノですからして。

**Comment by Shougo** [comment]
> 私のpatchをあてていないVimで発生した「complete()と行補完が混ぜこぜになる不具合」Issueを登録し、私のpatchのことに言及しない& #682 のリンクも貼らないShougoさんお疲れですか？

これまでの議論に関しては皆がわかってると思い省略してしまいましたが、
確かに、言及しておくべきでした。@ntak さんには要らぬ苦労をさせたようで、申し訳ありません。
「Shougoさんお疲れですか？」という問いには「私事で大変疲れております」とお答えします。

> > 君が質問しているのは 5 に関してのことでありそこは私のpatchの有無に関係なく同じ動作をするところです。本Issueの主題からずれてると思うので別Issue立てて頑張って下さい。
> 
> 機械的に修正した部分に対応漏れがあるかもしれないのは承知で、それは発覚した時点で私のpatchを修正していけば良いとShougoさんには伝えたつもりなんだけど伝わってないや。

申し訳ありませんが、@h_east さんのリンクしておりますissues のコメントからは「この問題は解決したから別のIssueでやってくれ」というところまでは理解できますが、本来の意図である「機械的に修正した部分に対応漏れがあるかもしれないのは承知で、それは発覚した時点で私のpatchを修正していけば良い」とまでは伝わりませんでした。私は空気を読むのや行間を読むのが苦手なので、そういう意図に関しては直接書いてもらえると助かります。

**Comment by Shougo** [comment]
> Gist更新。まっつんさん指摘箇所をcomplete()時には入らないように修正。
> https://gist.github.com/h-east/be555467ddfc3dfb8d54

パッチありがとうございます。早速適用して試しましたが、今回の問題は直っておりません。

今回の問題に関しては、補完を開始した時ではなく、補完を終了しても（補完キャンセル時は除く）自動折り返し機能が無効になる状態が続くというのが問題となっています。
@mattn 氏が指摘したコードに関しては、確かに現状おかしいのですが、そこだけが問題ならば補完終了したら自動折り返し状態は元に戻るはずです。

行補完が続くことと関連して、自動折り返し状態を制御する何らかのフラグがおかしくなっているのではないかと思い、こちらでも調べてみたのですがそれらしいフラグは見つからず残念ながら私には原因を特定するまでには至りませんでした。

以前、Christian 氏のパッチをベースに出来ないか調べていたのでそのときに Christian 氏のパッチの挙動を確認していました。Christian 氏のパッチは完全に行補完とcomplete()の実装を分離するものです。
Christian 氏のパッチではこの問題は起こっていません。
Christian 氏のパッチは他の挙動に問題がありすぎるので、採用には至りませんでしたが、解決の糸口になるかも知れません。

**Comment by h-east** [comment]
@Shougo 
:eyes:をかっぽじっても一回ちゃんと https://github.com/vim-jp/issues/issues/682#issuecomment-69136376 を読んで欲しい。
空気を読むとか行間を読むとかのレベルの話じゃないと思うんだけどなぁ。
あなたは話の流れもコード(既存の`complete()`部分、私のpatch、Christian氏のpatch)も理解してないやん。

コメント`1.`の「complete()は行補完のロジックを通す形で実装されている。」が理解できていれは、`complete()`関連のバグ報告で動作確認対象が無patchのVimだけにはならないはずなのよ。

それと、少なくともpatchの概要を理解していれば以下のズレた発言はしないよ。

> Christian 氏のパッチは完全に行補完とcomplete()の実装を分離するものです。

それとも私がエスパーしなさすぎなの？でも私も非常に疲れているのです。

**Comment by h-east** [comment]
Gist更新。これで直ったはず。確認よろしくです。
https://gist.github.com/h-east/be555467ddfc3dfb8d54
おそらく、`CTRL_X_MODE_LINE_OR_EVAL`マクロを削除して元に戻しても大丈夫な気がする。時間がある時に試して欲しい。

本Issueが直ったとしたら以下の仕様不整合の件をどうするかBram氏(vim_dev)に決めてもらって、それに応じたpatchを書いて再度vim_devにpatch投げて`complete()`の件は終わり。(にしたい)(にしこり)
https://github.com/vim-jp/issues/issues/685#issuecomment-70414954

**Comment by mattn** [comment]
何処かにしこりでもあるんですか？

**Comment by Shougo** [comment]
> Gist更新。これで直ったはず。確認よろしくです。
> https://gist.github.com/h-east/be555467ddfc3dfb8d54

Vim 7.4.617 + 上記パッチで試しましたが、直っておりません。@h-east 氏の環境ではどうでしょうか。
確認をおねがいします。

> おそらく、CTRL_X_MODE_LINE_OR_EVALマクロを削除して元に戻しても大丈夫な気がする。時間がある時に試して欲しい。

パッチを見たところこのマクロで置き換えられる部分が多いようなので、このままで良いと私は思います。

> 何処かにしこりでもあるんですか？

にしこり選手と掛けた高度なギャグだと思っています。

**Comment by Shougo** [comment]
> コメント1.の「complete()は行補完のロジックを通す形で実装されている。」が理解できていれは、complete()関連のバグ報告で動作確認対象が無patchのVimだけにはならないはずなのよ。

確かにこの Issue の冒頭で @h-east 氏のパッチについて書かなかった、パッチ適用次の状態を書かなかったのは私のミスですのでそこは申し訳ありません。
一応捕捉しておきますと、もちろん私はこの Issue を作成する前に @h-east 氏のパッチも既に試していて、その状態でも問題が再現するため、報告を行いました。

**Comment by mattn** [comment]
@h-east さんなら説明しなくても分かるからw (僕のもギャグになってるのに先に気付くべき)

**Comment by h-east** [comment]
> Vim 7.4.617 + 上記パッチで試しましたが、直っておりません。

直ってるってば。(Vim 7.4.617 + my patch on Ubuntu 12.04)
誰か他の人チェックお願い！。
再現手順の`2.`で`f`を押した時に`f`が2行目先頭に移動すればOKです。

**Comment by mattn** [comment]
よっしゃ、おっちゃんに任しとき

**Comment by mattn** [comment]
直ってると思うけど。

![](http://i.imgur.com/G932UKw.gif)

**Comment by h-east** [comment]
@Shougo 
https://github.com/vim-jp/issues/issues/682#issuecomment-69009150

> Christan 氏のパッチも試しました。こちらも <C-l>のマッピングが動作するようになりましたが、complete()による補完ウインドウが表示されている時に<C-h>を入力すると"Internal error: ins_complete" となります。

Christan氏のpatch ( https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/td_FVnHgasAJ )で "Internal error: ins_complete" になる再現手順をここに書いてもらえますか？

**Comment by h-east** [comment]
@mattn Thanks!

**Comment by Shougo** [comment]
> 直ってるってば。(Vim 7.4.617 + my patch on Ubuntu 12.04)
> 誰か他の人チェックお願い！。
> 再現手順の2.でfを押した時にfが2行目先頭に移動すればOKです。

申し訳ありません。別のマシンでもう一度試したら直っていました。
そのパッチで問題ないです。

**Comment by Shougo** [comment]
> Christan氏のpatch ( https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/td_FVnHgasAJ )で "Internal error: ins_complete" になる再現手順をここに書いてもらえますか？

再現方法：
- `vim -u test.vimrc`
- `iaa<F5><C-p><C-h>`

test.vimrc はこの Issue に載っているものと同一です。

**Comment by h-east** [comment]
@Shougo Thanks. 7.4.621 + Christan's patchで "Internal error: ins_complete" になるの再現出来ました。

んで、結局行補完と同じルートを通さなくても問題なさそうなので、CTRL_X_MODE_LINE_OR_EVALマクロを削除したpatchを作ってみた。いろいろ試したけど問題なさそう。
このpatchで問題なければこっちを採用します。

``` diff
diff -r b0a227941705 src/edit.c
--- a/src/edit.c    Tue Feb 03 19:13:34 2015 +0100
+++ b/src/edit.c    Wed Feb 04 10:15:49 2015 +0900
@@ -34,6 +34,7 @@
 #define CTRL_X_OMNI        13
 #define CTRL_X_SPELL       14
 #define CTRL_X_LOCAL_MSG   15  /* only used in "ctrl_x_msgs" */
+#define CTRL_X_EVAL        16  /* for builtin function complete() */

 #define CTRL_X_MSG(i) ctrl_x_msgs[(i) & ~CTRL_X_WANT_IDENT]

@@ -55,6 +56,7 @@
     N_(" Omni completion (^O^N^P)"),
     N_(" Spelling suggestion (s^N^P)"),
     N_(" Keyword Local completion (^N^P)"),
+    NULL,   /* CTRL_X_EVAL doesn't use msg. */
 };

 static char e_hitend[] = N_("Hit end of paragraph");
@@ -2267,6 +2269,8 @@
 #endif
    case CTRL_X_SPELL:
        return (c == Ctrl_S || c == Ctrl_P || c == Ctrl_N);
+   case CTRL_X_EVAL:
+       return (c == Ctrl_P || c == Ctrl_N);
     }
     EMSG(_(e_internal));
     return FALSE;
@@ -2773,8 +2777,7 @@
            -1, p_ic, NULL, NULL, 0, ORIGINAL_TEXT, FALSE) != OK)
    return;

-    /* Handle like dictionary completion. */
-    ctrl_x_mode = CTRL_X_WHOLE_LINE;
+    ctrl_x_mode = CTRL_X_EVAL;

     ins_compl_add_list(list);
     compl_matches = ins_compl_make_cyclic();
@@ -3394,7 +3397,7 @@
      * allow the word to be deleted, we won't match everything. */
     if ((int)(p - line) - (int)compl_col < 0
        || ((int)(p - line) - (int)compl_col == 0
-       && ctrl_x_mode != CTRL_X_OMNI))
+       && ctrl_x_mode != CTRL_X_OMNI) || ctrl_x_mode == CTRL_X_EVAL)
    return K_BS;

     /* Deleted more than what was used to find matches or didn't finish
```

Christan's patchとあんまり変わらなくなったけど肝はdiff最後の `|| ctrl_x_mode == CTRL_X_EVAL` 、これで再補完(`ins_compl_restart()`)が呼ばれるのを防いでる。これがあるから "Internal error: ins_complete" は発生しない。

# 

> > おそらく、CTRL_X_MODE_LINE_OR_EVALマクロを削除して元に戻しても大丈夫な気がする。時間がある時に試して欲しい。
> 
> パッチを見たところこのマクロで置き換えられる部分が多いようなので、このままで良いと私は思います。

面倒くさがったか:grin:。多いけど要は元に戻すということなので作業は簡単です。

vimフォルダは未patch状態、
hoge.patch が vim フォルダの1つ上にあるとして...

``` bash
$ cd vim/
$ vim src/edit.c
```

``` vim
:vert diffpatch ../hoge.patch
```

これでdiffモードになるので `zR` で全foldを開いて、 `]c` で変更箇所を確認しながら必要な部分だけを `dp` すればいいので30秒で出来ます。

**Comment by h-east** [comment]
vim_devに最終patch投げて仕様不整合の件を質問したけどスルーされ気味。
https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/oO1u4L_Wf_QJ

**Comment by Shougo** [comment]
> んで、結局行補完と同じルートを通さなくても問題なさそうなので、CTRL_X_MODE_LINE_OR_EVALマクロを削除したpatchを作ってみた。いろいろ試したけど問題なさそう。
> このpatchで問題なければこっちを採用します。

試すのが遅くなりましたが、動作を確認しました。
「自動折り返し」、「`<C-h>`時の補完継続」に関しては問題ありません。
ただし、「complete()中の`<C-l>`」に関しては不思議な挙動をするようです。

再現方法：

この Issue にある test.vimrc を用いて Vim を起動、次のコマンドを入力する。

`<F5><C-l><C-l><C-l>`
なぜか候補が絞りこまれます。

更に、もう一度 test.vimrc を用いて Vim を起動、次のコマンドを入力する。
`abcd<F5><C-p><C-l>`
入力文字列が abcda となります。第一候補の `January` の a が入力されているようです。
あらかじめインサートモードの `<C-l>` を remap していた場合はこの問題は発生しません。
remap したキーが呼び出されます。

> vim_devに最終patch投げて仕様不整合の件を質問したけどスルーされ気味。

それは残念です。今回のパッチは入って欲しいので私も援護しようかと思います。

**Comment by h-east** [comment]
確認どうもです。

> `<F5><C-l><C-l><C-l>`

絞り込まれないなぁ。
`i<F5><C-p><C-l><C-l><C-l>` の間違いでは？これなら候補が絞りこまれた。

2つ目のやつは再現しました。(最初に`i`が足りないよ)

# 

やっぱりなるべく行補完と同じ処理をさせないといけないようなので https://github.com/vim-jp/issues/issues/692#issuecomment-73013322 のpatchは取り下げて https://gist.github.com/h-east/be555467ddfc3dfb8d54 を正とします。
vim_dev には夜送ります。

**Comment by Shougo** [comment]
> 絞り込まれないなぁ。

すみません。インサートモード前提で確認していたため、最初の i を手順に追加するのを忘れていました。

> やっぱりなるべく行補完と同じ処理をさせないといけないようなので #692 (comment) のpatchは取り下げて https://gist.github.com/h-east/be555467ddfc3dfb8d54 を正とします。

動作を確認しました。特に問題ないようです。

**Comment by h-east** [comment]
> インサートモード前提で確認していたため

再現手順を提示するときには暗黙の前提条件や手順があったらダメなんだって。
https://github.com/vim-jp/issues/issues/685#issuecomment-69903117 
「再現手順を作成後に一時的にアホになってその状態で再現手順を実行する」テクニック

再現手順を実行する時はアホモードになっているのでImplicitな情報があったら爆発するんですよ？

**Comment by h-east** [comment]
最終patch送付済み
https://groups.google.com/d/msg/vim_dev/R7i2fb_yynY/zTsaMN_mkPUJ

`complete()`の第1引数と`backspace`オプションに`start`がない場合の仕様不整合の件 https://github.com/vim-jp/issues/issues/685#issuecomment-71378757 は以下の様な流れになって止まってる。
1. Bram氏は`2.`推し。
2. 私がいざ`2.`を実装しようとしたら既に補完モード終わった状態で`ins_bs()`に来る為に判定が困難だったので理由を説明して`1.`を推してみた。
3. Bram氏に「その方法はいろいろ問題が起きると思うよ」と言われた。けど実装してみたらやっぱり問題が起きた。Vim BOSSスゲー!!
4. `2.`の実装方法が私には思いつかないのでBram氏に投げた。

**Comment by h-east** [comment]
todoリスト更新されたのでclose。
#682 参照。

**Comment by Shougo** [comment]
ありがとうございます。
