### ISSUE TITLE
status/helpwanted の追加

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#694]
事後報告になりますが。

他のプロジェクトで見かけて、これいいなーってのがあったので `status/helpwanted` ラベルを追加しました。
もしかすると色(statusでなく?)は変えた方がいいかもしれませんが。

**Comment by thinca** [comment]
今色が `status` じゃなくて `related` のものになってますね。
個人的には `kind/helpwanted` に一票。状況に応じて変わるものでもないと思うので。

**Comment by mattn** [comment]
すいません。related にするつもりでした。直しました。

**Comment by thinca** [comment]
:+1:
