### ISSUE TITLE
--term=mlterm オプション付きで起動した mlterm で Vim の背景が乱れる

### ISSUE THREAD

**Issue by msmhrt** [vim-jp/issues#697]
【概要】
--term=mlterm オプション付きで起動した mlterm で Vim の背景が乱れる

【発生環境】
OS: Ubuntu 14.04.1 LTS (amd64)
Vim: 7.4.608
mltem: version 3.4.2 post/2015-02-01

【詳細】
mlterm はデフォルトでは `TERM=xterm` と申告し `BCE` を使えるのですが、`--term=mlterm` オプション付きで起動するか `.mlterm/main` で `term=mlterm` を指定すると、`TERM=mlterm` を申告するようになり、`BCE` が使えなくなります。

しかし、Vim は `TERM=mlterm` を申告する端末が `BCE` を使えるとみなすために、結果として Vim の背景色が乱れてしまいます。

これは修正されるべきだろうというのが私の意見です。

【再現手順】
`~/.mlterm` をリネーム等で一時的に退避してから、`mlterm --term=mlterm` を起動して、`vim -u NONE -U NONE -c "colorscheme blue"` を実行すると、一行目の背景色が青になりません。

なお、`mlterm` を一度起動すると `~/.mlterm` が作成されますので、元に戻す際はご注意ください。

**Comment by saitoha** [comment]
以下がきのう@msmhrt  さんとtwitterでやりとりしていて、出てきた修正案になります。

https://gist.github.com/saitoha/dd656291153a815e0a2b
1. vim_is_xterm("mlterm") をFALSEにして、TERM=mlterm 時にxtermのビルトインcapsを使わなくする。
2. use_xterm_like_mouse("mlterm") と use_xterm_mouse("mlterm") の返値をTRUEのままにするような修正を入れ、termresponseを使ったマウスプロトルの判定とttyfastオプションの自動設定がいままで通り効くようにする。

他の課題として、ktermも非bce端末なので、同様の修正を入れる必要があるはずです。
nxtermはよく知らないのですが、少なくともterminfo上は非bceです。

あと、このようにktermやmltermなどを特別扱いをするコードが、そもそもどのような経緯でvimに入ったのかを明らかにしておきたいので、どうにかして@seiichiさんに思い出して頂くとありがたいです。

**Comment by msmhrt** [comment]
@saitoha さんの patch で背景色が（ https://github.com/vim-jp/issues/issues/617 の右下隅が欠ける問題を除いて）正しく表示されることを確認しました。

**Comment by saitoha** [comment]
経緯：
https://twitter.com/seiichi/status/561886489923960832
https://twitter.com/seiichi/status/561887045270786048
https://twitter.com/seiichi/status/561888311011053572
https://twitter.com/seiichi/status/561888561138388993
https://twitter.com/seiichi/status/561889502583472131
https://twitter.com/seiichi/status/561891570048176128
https://twitter.com/seiichi/status/561892974116605952
https://twitter.com/seiichi/status/561894834621784064
https://twitter.com/seiichi/status/561895735252090880

**Comment by saitoha** [comment]
問題無ければ、先のパッチでいこうと思います。
非`bce`を想定したvimの挙動は`bce`端末に対しても互換性があるはずなので、非`bce`側に倒しておくのが無難かと思います。

**Comment by msmhrt** [comment]
念のため、
- `~/.mlterm/termcap` と `mlterm.ti` を無理やり編集して `TERM=mlterm` でも bce 端末になるようにした mlterm
- 先のパッチをあてた Vim

の組み合わせで試してみましたが、パッチをあてない Vim と比較して、
- 起動している最中、編集画面が表示される前にエラー等で入力待ちになった場合にメッセージ部分以外の背景色が変わらない

という差分以外に目で見て分かるような違いはありませんでしたし、この差分についても問題視する必要はないと思われます。

**Comment by saitoha** [comment]
すみません、閉じ忘れです。パッチを投げていて入っていたので閉じます。
https://groups.google.com/forum/#!topic/vim_dev/fYM-GAhmPg8
http://ftp.vim.org/vim/patches/7.4/7.4.627

**Comment by msmhrt** [comment]
私もすっかり忘れてました。
ありがとうございました。m(__)m
