### ISSUE TITLE
7.4.615 以降のGCの挙動を検証する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#698]
なんかここ数日、不安定という噂が立っている。
原因として真っ先に思いつくのはGCくらいなので [7.4.615](http://ftp.vim.org/vim/patches/7.4/7.4.615) を中心に調べる。

私も lambda のおかげで以前よりも Vim の GC について深く理解しているので、
以前とは違った懸念が発見できるかもしれないので。

**Comment by koron** [comment]
あ、他の人がやってくれても、良いのよ?

**Comment by mattn** [comment]
僕は落ちた事ないなー

**Comment by koron** [comment]
僕も落ちてないけど、そんなに大量にプラグイン使ってないからかなぁ、とか考えています。

**Comment by koron** [comment]
軽いレビューでは、メモリー解放からのSEGVみたいなことはなさそう。
一方、解放が遅れる可能性(一時的にリークする)は残るけど、それだって落ちることにはならなそうj。

**Comment by koron** [comment]
「Vimがもともと持っていたバグを顕在化させた」
という可能性を考慮にいれて再レビューしたけど、その疑いも否定できた。

なので 7.4.615 にかけた疑義は全て晴れました。

**Comment by koron** [comment]
となると、次はLuaですかねぇ…

仮にそうだとすれば unite ユーザー方面から落ちるという報告がたくさんありそう。
なので現時点では、この噂をまじめに受け止める必要はないだろう。

**Comment by koron** [comment]
一応、あとで見る人の助けになるかもしれないので、GCというかメモリ管理周りでわかっていることを書いておきます。

現在のところ、Vimスクリプトの辞書とリストは、それぞれがメモリ管理専用の双方向連結リストで管理されています。

辞書で言うと `dict_alloc()` のたびに、新しい要素を `first_dict` (リストの先頭を示すポインタ)に設定し、古い `first_dict` を新しい要素の `dv_used_next` に設定します。また同時に、古い要素の `dv_used_prev` は、新しい要素を指すようにしています。

既存の要素の削除は `dict_free()` において、`first_dict`, `dv_used_next` および `dv_used_prev` を適切に書き換え、リストの整合性を保つようになっています。

リストの方も `dict` を `list` に、`dv` を `lv` に替えて、まったく同じ構造になっています。まぁ、同じ構造なのにコードが分かれているのはイケていないのですが、それはそれこれはこれ。

以上です。

**Comment by koron** [comment]
あーとはいえ `dict_free` も `list_free` も、同じポインタに対して2回呼ばれたら、アウトかーw
いずれにせよ既存のコードにバグがあるとか、バグがあった時に落ちてしまうというだけ。
