### ISSUE TITLE
プログラマーがじゃぶじゃぶコード書きたく鳴るような射幸心を煽りまくるvimの説明文

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#699]
<blockquote class="twitter-tweet" lang="ja"><p>プログラマーがじゃぶじゃぶコード書きたく鳴るような射幸心を煽りまくるvimの説明文</p>&mdash; とめすけ (@tomesuke) <a href="https://twitter.com/tomesuke/status/563873089667096577">2015, 2月 7</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

を、考えましょう。

**Comment by ujihisa** [comment]
すごい大事そうです

**Comment by koron** [comment]
_Vimでコードを書いていたら背が伸びました_

とか

_Vimでコードを書いていたらやせました_

とか…射幸心、足りないか。

**Comment by mattn** [comment]
30億のデバイスで走るJava…を書いたエンジニアの一部が使ったかもしれないエディタ、Vim

**Comment by crazymaster** [comment]
[`:h quotes.txt`](http://vim-jp.org/vimdoc-ja/quotes.html)

**Comment by koron** [comment]
特に煽られなかったので閉じます。
