### ISSUE TITLE
スクリプト内で :global や :substitute などを使った場合でも検索パターンが更新される

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#7]
インタラクティブな入力でない場合でも、`:global` や `:substitute` を使うと常に検索パターンが履歴に追加される。

**Comment by mattn** [comment]
難しい所だけどfeature requestにしました。

**Comment by mattn** [comment]
これ、@/ が変わっちゃうって事でok？

**Comment by thinca** [comment]
そうです。加えて、履歴 (q/ や histget() で見れる) にも追加されます。

**Comment by thinca** [comment]
久々に最新版(7.3.1212)で確認したら、`@/` は変わらず、履歴にだけ追加されるみたいです。

**Comment by mattn** [comment]
これ閉じれます？

**Comment by thinca** [comment]
まだ何も解決してないと思うんですが、閉じる理由はなんでしょ?

**Comment by mattn** [comment]
あ、`変わらず` ですか失礼

**Comment by thinca** [comment]
`7.4.083` で `:keeppatterns` が追加され、私自身はまだ未確認ですが、多分これで解決できる気がするので閉じます。(なんか問題あったらまた開きます)
