### ISSUE TITLE
VIM::evaluate の説明が古い

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#700]
[VimのRubyインタフェースのVIM::evaluateの戻り値の謎](http://www.xmisao.com/2014/05/07/if-ruby-vim-evaluate-memo.html) より転載。

`:help ruby-evaluate` には以下のように書いてある。

> Returns the expression result as a string.

にも関わらず実際には辞書とリストがちゃんと変換される。
-    ドキュメントを更新する/vim-devに報告して更新してもらう
-   いつからズレたのか、経緯を確認する

# たぶんPythonとLuaが同様のことで頑張ってた前後だとは思うが…

**Comment by ynkdir** [comment]
7.2.374 で変更されたみたいです。
報告しました。
https://groups.google.com/d/msg/vim_dev/U98Xr57h52Q/yazgx0izUncJ

**Comment by koron** [comment]
ありがとうございます :bow: & :+1:

**Comment by crazymaster** [comment]
https://github.com/vim-jp/vim/commit/9440f7f9dc4ac854667419918a6c056080681258#diff-ec8aeb82ec71935b8714b2c135b86402
