### ISSUE TITLE
cygwin上でvimコマンドを入力しても何も起こらない

### ISSUE THREAD

**Issue by dazaga** [vim-jp/issues#702]
cygwin，vimともに全くの初心者です（ついでにGithubも初心者です）．
vimをkaoriyaさんのサイトからダウンロードし，.vimrcファイルを作り，
スタンドアローンで動くようにしてから，いざcygwin上で動かそうとすると動きません．
type vimで　vim is /cygdrive/c/Program Files/vim/vim と表示されるので，
コマンドのパスは通っていると思うのですが…
また，コマンドプロンプト上でvimと入力すると，きちんと.vimrcファイルの設定を反映した
vimがスクリーン上に出ます．
.vimrcファイルにはcygwinに関係するような命令は一切書いていません．
情報不足かもしれませんが，どなたか助言を下さると幸いです．

**Comment by Shougo** [comment]
Cygwin アプリケーションと Win32 ネィティブアプリケーションは仕組みが異なります。混ぜるべきではありません。Win32 の Vim はコマンドプロンプト上での動作を前提としているので Cygwin の端末では動作しません。
この場合、Cygwin で Vim を使いたいのなら Cygwin の Vim をインストールするべきです。

**Comment by ghost** [comment]
Cygwin のインストーラで Vim を選択し、インストールしてください。
Cygwin の端末、たとえば mintty などで動作する版の Vim はそちらから入ります。

**Comment by mattn** [comment]
@dazaga まず切り分けたいのですが、mintty 上で実行されたのでしょうか？それもとコマンドプロンプトからでしょうか？

**Comment by mattn** [comment]
vim.exe は一応、`vim -T ansi` とか `vim -T vt100` という起動方法も出来るので、それをフォールバック出来ると考えています。

**Comment by dazaga** [comment]
ご回答ありがとうございます．
vimのパスを全て表示させると，
vim is /cygdrive/c/Program Files/vim/vim
vim is /cygdrive/c/MinGW/msys/1.0/bin/vim
となりました．前者は，kaoriyaさんのWin64用vimだと思います．
今回の質問で「何も起こらない」，と述べたのは前者のvimです．

minttyというのは，もしや後者のvimでしょうか（あまり入れた記憶がないのですが）．
こちらをcygwinで起動すると，例えば「矢印キーによる入力が，ABCDと表示される」といった
バグが発生します．

**Comment by mattn** [comment]
mintty は仮想コンソールです。ウィンドウの左上が

![](http://go-gyazo.appspot.com/df741abffa2bb049.png)

こんな感じになってませんか？もしくは ssh 越しだったりしませんか？

**Comment by dazaga** [comment]
@mattn 
ならないです．
「ssh越し」かどうかは不明ですが，少なくともリモートアクセス等しているわけではないです．

**Comment by mattn** [comment]
コンソール版の vim は、cygwin の shell 上であっても、ウィンドウが cmd.exe 上であれば起動するはずなのです。
出来ればスクリーンショットと、`which vim` とやった結果を頂けますか。

**Comment by ghost** [comment]
後者の Vim は MinGW 下に入っているのならおそらく msys-vim だろうと思います。
msys-vim は MinGW 下で正常に動作する版です。

Kaoriya 版 Vim は Windows の cmd.exe ウィンドウで動作する vim.exe
Cygwin 版 Vim は Cygwin のウィンドウ(私は mintty と言ってしまいましたが)で動作する vim.exe
MinGW 版 Vim は MinGW のウィンドウで動作する vim.exe
と、とりあえず大きくわけて三種類あるので、私も混乱した記憶があります。

Cygwin で Vim を使うときは Cygwin のインストーラから入る Vim.exe を利用してください。(´ー｀)

**Comment by dazaga** [comment]
@mattn 
cygwin上でcmdして，vimコマンドを使った際のスクリーンショットは以下になります
（この状態で止まります）．
一部モザイク処理を施しています．
![image](https://cloud.githubusercontent.com/assets/5533562/6242014/36fd742c-b76a-11e4-97c7-a1c0567bed6e.png)

which vimの結果は，
/cygdrive/c/Program Files/vim/vim
となりました．

**Comment by dazaga** [comment]
@ntak ありがとうございます，インストールしてみます．

**Comment by ghost** [comment]
Kaoriya 版については日本語などの付加要素があるので、それを利用するにはどうしたらいいかという話であれば…、どうなんでしょう？
このへんの話がまとまった html があったような記憶がないでもないですが、詳細は忘れました(;´Д`)。

**Comment by k-takata** [comment]
Cygwinをインストールしたのがここ1，2年以内であれば、”Cygwin Terminal” のショートカットで起動するのは mintty のウィンドウです。（昔は、Cygwinも cmd.exe 上で動くのがデフォルトでした。）
スクリーンショットを見ても mintty のようですね。

> 「矢印キーによる入力が，ABCDと表示される」

compatible モードで動作しているときの典型的な症状です。Cygwin版のvimをインストールしても同じ症状が出た場合は、ホームディレクトリに（空でもよいので） .vimrc を作成してください。

**Comment by mattn** [comment]
@dazaga mintty の様です。すぐに解決したい場合は、@ntak さんの言うように cygwin 版の vim をインストールして下さい。

**Comment by dazaga** [comment]
@k-takata  @mattn 
Cygwin版のvimをインストールしました．
矢印キーがABCDと表示されるバグは解消しましたが，.vimrcの内容が反映されません．
例えば，colorschemeとしてjellybeansを設定しているのですが，反映されません．

こちらが，.vimrcファイルです．
https://github.com/dazaga/VimError/blob/master/.vimrc
こちらが，エラーメッセージです．
https://github.com/dazaga/VimError/blob/master/errormessage

**Comment by raa0121** [comment]
`^M` とは Windowsの改行コード `<LF><CR>` の `<LF>` のことです。
その状態で `.vimrc` を開いて `:%s/\r\n/\n/` をして保存してVimを開き直すと正しく動くと思います。

**Comment by dazaga** [comment]
@raa0121 
エラーが出てしまいます．
![image](https://cloud.githubusercontent.com/assets/5533562/6243560/282c5eaa-b787-11e4-8165-20d0cb60d91e.png)

**Comment by ghost** [comment]
:%s/\r\n/\n/g かな？と一瞬思いましたが、違う感じもします。
Cygwin には dos2unix というまんまな名前の改行文字コンバータが setup で提供されていてインストールできるので、それで一発です。

**Comment by ntak** [comment]
私が導入当時ハマったポイントですが、.vimrc は C:\Users\[ユーザ名]\ ではなく Cygwin 上の ~/ に置くと vim が見てくれるようになります。
このにょろっとしたやつ(~)が Windows やってるとなかなか慣れないんですよね…。

**Comment by dazaga** [comment]
@ntak 
現在は.vimrcはC:\Users[ユーザ名]\ にあるんですが，vimはこれを見てくれていないんですか？
見ているからこそエラーを吐いているような気がするのですが．

**Comment by dazaga** [comment]
@ntak 
dos2unixをインストールしましたが，改行文字を読んでくれません．
where dos2unixすると，
C:\cygwin64\bin\dos2unix.exe
C:\MinGW\msys\1.0\bin\dos2unix.exe
と返ってきます．

**Comment by ghost** [comment]
あっ(;´Д`)コメント消去と前後しましたね、消さなくてもよかったかな…

Cygwin 版 vim は Cygwin をインストールしたフォルダの下にある .vimrc だけを見に行きます。
C:\cygwin にインストールしているなら Cygwin 版 vim は C:\cygwin\home[ユーザ名].vimrc を見ます。

Cygwin から見ると Windows の C:\Users[ユーザ名]\ は /cygdrive/c/Users/[ユーザ名]/ になっています。
即効の解決策としては、Cygwin で `cp /cygdrive/c/Users/[ユーザ名]/.vimrc ~/` と入力してください。
ホームディレクトリという概念とそれを表す ~/ というパス名について Cygwin は説明が足りない気がします。私も迷いましたし。

ちょっと離席しますね… ((((´ー｀)

**Comment by ghost** [comment]
MinGW にも dos2unix あるんだ….
とりあえずそれは抜きにして上記 cp を実行してみてください。親に呼ばれている…

**Comment by dazaga** [comment]
mistpcをユーザ名として，
$ cp /cygdrive/c/Users/mistpc/.vimrc ~/
とすると，
cp: `/cygdrive/c/Users/mistpc/.vimrc' と`/cygdrive/c/Users/mistpc/.vimrc' は同じファイルです
と返ってきます．

**Comment by k-takata** [comment]
通常、Cygwinのホームディレクトリは、`C:\cygwin\home\<ユーザー名>` ですが、`HOME`環境変数を設定しているとそちらが優先されたりします。Cygwinとそれ以外でホームディレクトリを共有することも出来なくはないですが、トラブルの元なのでよく分かっていなければ止めた方がよいでしょう。

**Comment by dazaga** [comment]
@k-takata 
確かに，環境変数HOMEが設定されており，値はC:\Users\ <ユーザー名> となっています．
Cygwinは，デフォルトでHOME変数の値を参照するものと思っていました．

「HOME環境変数のせいで，Cygwinが本来参照するべき場所ではなく，
Cygwin以外の参照するホームディレクトリを参照しており，
それがトラブルの原因になっている可能性がある」
といった理解でよろしいでしょうか．

すると，分からないのは，以下の2点です．
1.HOME環境変数の値がCygwin以外のホームディレクトリを表すならば， 
   Cygwinのホームディレクトリはどこで決めているのか.
2.HOME環境変数を具体的にどう弄れば，適切な設定ができるのか．

**Comment by k-takata** [comment]
Cygwinは、`cygwin1.dll`があるディレクトリの1つ上のディレクトリをルートディレクトリと見なし、そこからの相対位置でホームディレクトリを決めていたはずです。しかし、HOME環境変数が設定されていればそちらが優先されます。
個人的には、HOME環境変数は設定しないのがよいと思います。（他にそれを必要としているアプリがなければですが。）

**Comment by dazaga** [comment]
@k-takata 
不明点2点，了解しました．
これらを受けて，HOME環境変数を消去しました．
その後cygwinを開くと，以下のメッセージが表示されました．

![image](https://cloud.githubusercontent.com/assets/5533562/6245047/cf5ecb7a-b79d-11e4-9c1b-973ea3ede330.png)

cygwinを開き直すと，このメッセージは表示されなくなりました．
ここで，.vimrcファイルと bundleの入った .vimディレクトリをC:\cygwin\home<ユーザー名>に移しました．
vimコマンドを打つと，
https://github.com/dazaga/VimError/blob/master/errormessage
と同様のエラーメッセージが表示されました．
行番号が表示されることから，set命令は通っているようですが，
一方でcolorschemeやNERDTreeなど，NeoBundleに関係する命令は一切通っていないようです．

**Comment by dazaga** [comment]
改行コードに問題があるならば，.vimrcの改行位置すべてに同様の警告が出ると思われます．
しかし，エラーメッセージと .vimrcを照らし合わせると，
そのような一貫性のある警告がなされていないように思え，混乱しています．

**Comment by mattn** [comment]
HOME を弄るといろいろ問題が出るので、僕は mklink で _vimrc と vimfiles を .vimrc と .vim にジャンクションリンクするのがオススメと思うのですが、どうでしょう > all

**Comment by ghost** [comment]
あら環境変数…失礼しました…
Windows パスと Cygwin パスが混在するとややっこしいことこの上なし(;´Д`)

Cygwin 側の Vim から :NeoBundleUpdate を実行しても…駄目そうですな…何がいかんのだろう…
NeoBundle なら :NeoBundleInstall した時点のステートがベタコピーされたらアカン気もしばし。
いや、ジャンクションが通るならそうでもないのか…

みっちり書いても読みやすい導入ガイド的なものがあるとお役立ち感高まるので書いてみますね
(まずは私のneovim.jpの方で Issue を立てつつ)。

**Comment by rbtnn** [comment]
上記以外に`^M`を削除する方法として、`:%s/『Ctrl+v』『Enter』//g`をvimrcを開いてから実行すると削除できます。
『～』は文字として入力するのではなく、そのキーを入力するという意味です。

**Comment by dazaga** [comment]
@rbtnn 
驚くことに，^Mというパターンは見つからないそうです．
vimでは ^Mはエディタのコマンドではないと叱られるんですが．．．

**Comment by dazaga** [comment]
@mattn 
すみません，既にHOME環境変数は削除してしまいました．
表示された警告
![image](https://cloud.githubusercontent.com/assets/5533562/6247050/363a8540-b7b3-11e4-847e-d983feb16cb6.png)
は，表示されているファイルのパスが変更されたということでしょうか．

これらのファイルのパスを変更して，HOMEをもう一度設定し直せば，
元の状態に戻りますでしょうか．

**Comment by dazaga** [comment]
@ntak 
すみません，よろしくお願いします．

**Comment by k-takata** [comment]
> 表示された警告

HOME環境変数を削除したことで、ホームディレクトリが `C:\Users\...\` から `C:\cygwin\home\...\` に変更されたので、一部の設定ファイルをデフォルトの設定で新規作成したというだけですね。無視しても構いませんし、必要であればそれらの設定ファイルを元のホームディレクトリからコピーしてきたらよいでしょう。

これで、WindowsのホームディレクトリとCygwinのホームディレクトリが分離されたので、改めて次の2つのコマンドを実行してみてください。

``` sh
# .vimrc をCygwinのホームディレクトリにコピー
cp /cygdrive/c/Users/mistpc/.vimrc ~/
# .vimrc の改行コードをDOS形式からUnix形式に変換
dos2unix ~/.vimrc
```

**Comment by dazaga** [comment]
@k-takata 
できました！ 問題なく動くみたいです．
本当にありがとうございます！

**Comment by k-takata** [comment]
@raa0121 @rbtnn
改行コードの変換はそのやり方ではダメでしょう。というのは、起動時に .vimrc を読み込むときは、改行コードがUnix形式であることを前提に読み込んで ^M が余計な文字として扱われてしまうのですが、普通に .vimrc を開いたときは、改行コードの自動判別が行われることで fileformat=dos として読み込まれるので ^M が単独の文字として扱われることはないからです。
vim を使って改行コードを変換したい場合は、`vim ~/.vimrc` でファイルを開いたら、 `:set fileformat=unix` でUnix形式に設定してから保存すればよいです。（dos2unix の方が簡単だと思いますが。）

^M とか \r を置換で削除するのは、1つのファイル内にDOS形式とUnix形式の改行が混じっているような場合には有効です。

**Comment by rbtnn** [comment]
> 改行コードの変換はそのやり方ではダメでしょう。というのは、起動時に .vimrc を読み込むときは、改行コードがUnix形式であることを前提に読み込んで ^M が余計な文字として扱われてしまうのですが、普通に .vimrc を開いたときは、改行コードの自動判別が行われることで fileformat=dos として読み込まれるので ^M が単独の文字として扱われることはないからです。

確かにそうですね。失礼しました。

**Comment by dazaga** [comment]
@k-takata 
疑問点があります．
１．vimの導入後，C++でプログラムを組んで g++コンパイラを Cygwin上で使う予定があります．
パスを考慮し，MinGWをC:\cygwin\home...\に丸ごと移すべきでしょうか．
2．C:\cygwin\home...\ ではなく，もとのホームディレクトリのC:\Users...\ には .bash_historyや .gitconfig
などの，重要そうなファイル（私には用途は不明ですが，.vimrcと似た設定を書き込むファイルでしょう）が
入っています．これらは他の場所に移す必要はないのでしょうか．

**Comment by k-takata** [comment]
動いて良かったです。

私が、Cygwin と Windows のホームディレクトリを共有しない方がよいと考える理由は、Cygwin と通常の Windows では、今回のように改行コードやパスの扱いが異なっており、それがトラブルの原因となり得るからです。もちろん、十分に注意すれば .vimrc などの共有は可能ですが、そういうのは両者の違いが十分に分かってからでも遅くはないでしょう。

**Comment by dazaga** [comment]
@k-takata 
Unix ベースとWindows ベースの微妙な違いが混乱のもとになるというわけですね．

**Comment by k-takata** [comment]
おっと、閉じるのは早かったですか？

> １．vimの導入後，C++でプログラムを組んで g++コンパイラを Cygwin上で使う予定があります．
> パスを考慮し，MinGWをC:\cygwin\home...\に丸ごと移すべきでしょうか．

MinGWとCygwinは（似ていますが）別物です。こちらも混ぜて使うのはトラブルの元です。
Cygwin の gcc でコンパイルしたファイルは実行時に、cygwin1.dll が必要ですが、MinGW の gcc でコンパイルしたファイルは cygwin1.dll は不要です。gcc が動けば何でも良いのか、Windows向けのネイティブなプログラムを作りたいのかで、どの gcc を使うかを決めてください。

> 2．C:\cygwin\home...\ ではなく，もとのホームディレクトリのC:\Users...\ には .bash_historyや .gitconfig
> などの，重要そうなファイル（私には用途は不明ですが，.vimrcと似た設定を書き込むファイルでしょう）が
> 入っています．これらは他の場所に移す必要はないのでしょうか．

Unixでは `.` で始まるファイルは基本的に設定ファイルだと考えてよいでしょう。（Cygwin初心者ということであれば、今までの設定を捨てて新規にやり直しても大したことはないのではという気もしますが、正直お任せしますとしか…）

**Comment by dazaga** [comment]
@k-takata 
わかりました．
こういう場所で質問するのは初めてで，正直不安もあったのですが，非常に助かりました．
どうもありがとうございました．

**Comment by k-takata** [comment]
参考までに、こんな記事も書いています。
[CygwinからWin32版GVimを起動する - Qiita](http://qiita.com/k-takata/items/311a81f1fdf4ef01eb38)
