### ISSUE TITLE
mintty 上でも native vim.exe を動かせる様にしたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#703]
#702

`vim -T ansi` が出来るのでもう少し頑張ればちゃんと動くだろうし、`MSYSTEM` 等の環境変数を見て自動でフォールバック出来るんじゃなかろうか。

**Comment by dazaga** [comment]
@mattn 
すみません，本当にずぶの素人で，
vim自体，殆ど使ったことがなく（これから使い始めるために設定しています），
簡単な修正しかできません．．．

**Comment by ghost** [comment]
Cygwin + (Cygwin付属)mintty では ./configure; make; make install した vim が動きます。
MinGW + (MSYS付属)mintty は msys-vim (古い! 7.3.*) が動きます。
MinGW でも ./configure は pdcurses を使えば通ります。make が通らないことは確認しましたが、追及はしていません。

このリンク先をある程度参考にしています。
http://dogwood.skr.jp/blog/2013/11/406/
一見動くんですが、:q! としたときの ! が表示されないとか、ちょっとありますね。

**Comment by ghost** [comment]
@dazaga 大丈夫です。気楽にいきましょうヽ(´ー｀)ノ。

**Comment by mattn** [comment]
@dazaga 大丈夫です。修正は僕らオッチャンがやります。ヽ(´ー｀)ノ。

```
＿人人人人人人人人人人人人人人人＿
＞　僕らオッチャンがやります。　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣
```

**Comment by dazaga** [comment]
@mattn @ntak 
お二方，大変心強いです．
私としても，導入段階でつまづいてvimを諦める気になれないので，
絶対にうまく使えるところまでもっていきたいです．
どうぞよろしくお願いします．

**Comment by mattn** [comment]
この issue は、本来 mintty では動かせない非 cygwin 版 vim を mintty
でも動く様にパッチを書いてオフィシャルに取り込んで貰おうという issue です。dazaga さんの今の課題とは少し異なるかと思います。

On 2/18/15, dazaga notifications@github.com wrote:

> @mattn @ntak
> お二方，大変心強いです．
> 私としても，導入段階でつまづいてvimを諦める気になれないので，
> 絶対にうまく使えるところまでもっていきたいです．
> どうぞよろしくお願いします．
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/703#issuecomment-74862652

## 
- Yasuhiro Matsumoto

**Comment by ghost** [comment]
なんとなく見るに
1) ウィンドウを大きくしてもスプラッシュスクリーンが追従しない → 画面サイズが取れてない
2) 入力した文字が Vim 本体に伝わってない感
3) Ctrl+C で何事もなく終了できる → シグナルハンドラとかその方面が働いてない
っぽいので、ヤマとしてはまず標準入出力をどう Vim につなぐかなのかとは思いますけれど、
現状の msys-vim が完全動作するっぽいのでなにか別の手段を取った方がいいのかもしれません…。
mintty でも動作している msys-vim の構造を知りたい感マシマシ(´ー｀)で。

**Comment by k-takata** [comment]
まず、mintty上でWin32アプリを動かすと、isatty()が0を返すのですよね。
一方、cygwinアプリはコンソール入出力は(Win32 APIを直接使わない限り)全てcygwin1.dllを介して行うので、cygwin1.dllが差分を全て吸収してくれるわけです。
で、Win32 コンソールAPIをがんばってcygwin1.dllにつないでいるのがwinptyの処理のはずです。

winptyにがんばってもらえばそれでいいんじゃないですかね。
もっとも、mintty上でWin32 vim.exeを動かすと反応がなくなってしまうのは不親切なので、エラーメッセージを出して終了するように出来ないだろうかとは思いますが。

**Comment by mattn** [comment]
winpty にゆだねるのは構いませんが、winpty で動いてたけど動かなくなるよってのは vim-dev で言っておいた方がいいと思います。実際にやってる人がいてもおかしくないですからね。

**Comment by k-takata** [comment]
Standard streams in mintty
http://sourceforge.net/p/msys2/wiki/Porting/#standard-streams-in-mintty
MSYS2公式Wikiのmintty(とwinpty)に関する説明。

**Comment by k-takata** [comment]
https://github.com/k-takata/ptycheck
とりあえず、mintty上で動いているかどうかを知る方法が分かりました。
（標準入出力が全てリダイレクトされていると分かりませんが。）

**Comment by k-takata** [comment]
表題とは逆に、mintty上で動いていることを検出した場合は、`--not-a-term` が指定されていない限り、エラーメッセージを出して終了するようなパッチを作ってみました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/2f74e9d4f259f3834e49c438d410f3764cd5eeb8/add-check-for-cygwin-pty.patch?fileviewer=file-view-default
検出機構は、上記の ptycheck の最新版を組み込んでいます。

なお今回のパッチでは、minttyが検出可能なのは、Vista以降のみです。XPに対応させるのはビルドが面倒なので、vim自体は動くものの、minttyの検出はできないようにしています。

**Comment by mattn** [comment]
試さず言ってすみませんが mintty + winpty + vim でも大丈夫でしょうか。

**Comment by k-takata** [comment]
winptyを介していると、今まで通りmintty上ではないと判定されます。なので、今まで通り動こうとします。

で、今winptyを試したところ、以前に比べて動作がかなり改善されている印象を受けました。

**Comment by k-takata** [comment]
上で挙げられていた、Win32版をwinpty上で動かした際の問題ですが、

> 1) ウィンドウを大きくしてもスプラッシュスクリーンが追従しない → 画面サイズが取れてない

Win32版では、マウスでウィンドウサイズの変更はできないですから、これは仕方がない気がします。minttyの画面サイズを変更できなくするなら、なお良いのですが。
逆に、`set co=90` などとして Vim の方からウィンドウサイズを変更してみようとしたのですが、mintty のウィンドウは追従しませんでした。

> 2) 入力した文字が Vim 本体に伝わってない感

軽く試した範囲では問題なさそう。サロゲートペアも入力できましたし。

> 3) Ctrl+C で何事もなく終了できる → シグナルハンドラとかその方面が働いてない

Ctrl+C では終了しなくなっていました。

**Comment by mattn** [comment]
僕も最近 winpty を使って良くなっているのを確認しました。多分後は標準入力くらいだっと思います。

```
$ echo 123 | winpty vim -
```

**Comment by k-takata** [comment]
minttyでVimを使いたければ普通はCygwin or MSYS2のVimを使えば良いですし、そうでなくても、winpty + Win32 Vimでそこそこ動くので、Win32 Vimがminttyに自前で対応する必然性はほとんど無くなった気がします。

**Comment by mattn** [comment]
:+1: これは winpty の問題なので僕らは mintty 上でハングや操作不可にさえならなければokすね。

**Comment by k-takata** [comment]
投げてみた。
https://groups.google.com/d/msg/vim_dev/4AvebNRfAZ8/pZoqWPFsKAAJ

**Comment by k-takata** [comment]
入った。7.4.1963
https://groups.google.com/d/msg/vim_dev/r78RJPGnIA8/4EBa64NvBgAJ

さて、このissueどうしますか？
minntyが検出できるようになったのでOKとするか、それともmintty上でnativeに動くまで頑張るか…。

**Comment by k-takata** [comment]
ちなみに、これの影響でVCでコンパイルする場合には、VC2008以降が ~~必須~~ 推奨となりました。
(VC2005でもコンパイルは可能ですが、mintty 検出機能は無効化されます。)

**Comment by mattn** [comment]
> Running Win32 Vim in mintty does not work. 

って書かれちゃうとうーん。

**Comment by k-takata** [comment]
> Running Win32 Vim in mintty does not work.

winptyを介さないと応答がなくなってしまうのは、動かないと言っていい気がします…。

> さて、このissueどうしますか？
> minntyが検出できるようになったのでOKとするか、それともmintty上でnativeに動くまで頑張るか…。

私としてはこれ以上の対応は不要と考えていますが。

**Comment by k-takata** [comment]
いろいろと検討しましたが、minttyを検出する以上の対応は困難との結論に達しました。Win32 nativeアプリから、minttyの入力をrawモードに切り替える現実的な方法がないためです。（winptyのような何らかのCygwinのヘルパーアプリが必要です。）
ハングアップしなくするという最低限の修正は入っているため、クローズします。
