### ISSUE TITLE
vimrun.exe がないと system() を実行できない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#705]
<blockquote class="twitter-tweet" lang="ja"><p><a href="https://twitter.com/kaoriya">@kaoriya</a> 先生！前から気になってたんですが、winのvimで、gitとかpythonとか使ったプラグインが何か外部コマンド的なものを呼び出すときにタスクバーに一瞬アイコンが出るんですが、これ消せないっすかね。実害は全くなく気分的な問題なんですが、、、</p>&mdash; Kohichi Aoki (@drikin) <a href="https://twitter.com/drikin/status/570385010546450432">2015, 2月 25</a></blockquote>

こんな質問を受けて、そういえばDOS窓が開くのはWin9x絡みのslowdown対策で、今は必要ないんじゃないか&たしか vimrun.exe を消せば出なかったような(←これは自体はただの勘違い、たぶん)…と思い、実験してみたところ「テンポラリファイルが見つかりませんでした」みたいなエラーがでて、そもそも実行できませんでした。

推測ですが、実行そのものはできているけど結果を格納すべきテンポラリファイルを取得できなかったんじゃないかと。実行したコマンドは以下のような単純なもの。

```
:echo system('go version')
```

ドキュメントには vimrun が無くても実行できるよと書いてあるので、ドキュメントか本体を修正する必要があるでしょう。

> If "vimrun" cannot be found, the command is executed directly, but then the DOS window closes immediately after the external command has finished.

**Comment by koron** [comment]
発生しているエラーはE484。

```
E484: ファイル "(省略).tmp" を開けません
```

**Comment by mattn** [comment]
vimrun は、CUI 版だと CTRL-C で止められるけど GUI 版だとプロセス止めれないので必要になりますね。
CUI 版は vimrun.exe 無くても動くんですが、GUI 版はこのエラーになりますね。
ドキュメントではそこまで厳密にはうたってない様です。
ちなみにドキュメント、pif とかいつの時代やねんみたいな事が書いてあるので更新しないとですね。。。

**Comment by koron** [comment]
となるとGUI版は例のWinネイティブな `:shell` があれば解決できますかね?

**Comment by drikin** [comment]
おお、いつの間にこんな素晴らしいスレが！
全く根拠はないんですが、このプロセス起動が起きる系の操作が妙に重い気がして(たぷんウイルスソフト系との相性なんですが)何かvim側でできる良い対策は無いかなぁと思ったりしたのが発端です。

**Comment by drikin** [comment]
例えば
https://github.com/907th/vim-auto-save/blob/master/README.md

これとか入れて200ms起きに:wするみたいな事させると、ガツガツキー操作がブロックされて実質操作不能になります。

もちろんローカルで対策するのが正しいんですが、オフィスのパソコンだと自分ではウイルスソフトとか変えられなくて、いかんともしがたいなぁと、、、

**Comment by drikin** [comment]
ちなみに、:wするだけでプロセスが立ち上がってるように見えるんですが、それって正しい挙動？
うちの環境（セキュリティー強化させられてる）依存だったりするのかちょっと気になってます。

**Comment by mattn** [comment]
そういう仕様ですね。

https://github.com/907th/vim-auto-save/blob/master/plugin/AutoSave.vim#L53

**Comment by mattn** [comment]
で、vim-ctags の方は vim-dispatch を使って非同期にプロセスを起動してます。

https://github.com/szw/vim-tags/blob/master/plugin/tags.vim#L213-L217

vimproc 使ったパッチを書いてあげると DOS 窓も開かないので皆が幸せになれる気がします。

**Comment by drikin** [comment]
なるほど。情報ありがとうございます。
まぁ実害はないんですがなんとなく気持ちが悪い感じだけですね。。。

**Comment by mattn** [comment]
vim-dispatch は確か windows でも動作したと思うので `g:vim_tags_use_vim_dispatch` を設定すると DOS 窓は消えるかもしれません。

**Comment by k-takata** [comment]
vimrun.exe の有無でどういうコマンドが実行されるか調べてみました。(`:echo system('dir')` を実行)
os_win32.c の mch_call_shell() の中でコマンドを組み立てて mch_system() を呼んでいますが、その引数をダンプしています。

vimrun.exe あり

```
C:\work\vim-msvc\src\vimrun -s C:\WINDOWS\system32\cmd.exe /c (dir ^>C:\Users\user\AppData\Local\Temp\VIo6DF5.tmp 2^>^&1)
```

vimrun.exe なし

```
C:\WINDOWS\system32\cmd.exe /c (dir ^>C:\Users\user\AppData\Local\Temp\VIo33B1.tmp 2^>^&1)
```

vimrun.exe はさらに `_wsystem()` でコマンドを実行していますので、vimrun.exe が無い場合に比べると cmd.exe の処理が1回多いことになります。
vimrun.exe が無い場合は `^` によるクォートが余計なんではないでしょうか。（未確認）

**Comment by k-takata** [comment]
mch_system() の実体は、GUI 版は CreateProcess() で、CUI版は _wsystem()。
そのためCUI版は vimrun.exe を介していなくとも cmd.exe の処理が1回加わるので正常に動くと。

7.3.450近辺のクォート処理の変更の前はvimrun.exeなしでも動いてたんですかね？

**Comment by mattn** [comment]
すいません。記憶にないっすねー。() を使ってるのでどちみち vimrun ありかなしかでクオート方法変えないといけない感じします。

**Comment by k-takata** [comment]
`cmd /c cmd /c ...` というように cmd を2重にしてみたらいけるのではと思ったのですが、ダメでした。ぐぬぬ

**Comment by k-takata** [comment]
単にバッファが足りていないだけでした。直したら動いた。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/dcdee16ab79de35fb476723fe7a8967bc382bf48/fix-quotation-without-vimrun.patch?at=default&fileviewer=file-view-default
こんな直し方でいいのか？ｗ

あと、vimrun.exeがないときのwarningメッセージが、enc=utf-8だと化けてしまう問題が発覚しています。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/dcdee16ab79de35fb476723fe7a8967bc382bf48/fix-encoding-of-vimrun-warning.patch?at=default&fileviewer=file-view-default

**Comment by mattn** [comment]
> あと、vimrun.exeがないときのwarningメッセージが、enc=utf-8だと化けてしまう問題が発覚しています。

既存から、という事ですね？

**Comment by k-takata** [comment]
Yes. 以前からです。そっちはパッチ投げました。
https://groups.google.com/d/topic/vim_dev/hxKIPNGd6Qc/discussion

**Comment by k-takata** [comment]
> あと、vimrun.exeがないときのwarningメッセージが、enc=utf-8だと化けてしまう問題が発覚しています。

8.0.0094 で直りました。早い。
https://groups.google.com/d/topic/vim_dev/d4gVxs-7Cnw/discussion

**Comment by k-takata** [comment]
PRed: https://github.com/vim/vim/pull/4355

**Comment by k-takata** [comment]
8.1.1295: https://github.com/vim/vim/commit/98ffe4c6d8bded840436cfec0f26dd9c9bce4939
