### ISSUE TITLE
'cursorlineopt' オプションの追加

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#706]
http://lingr.com/room/vim/archives/2014/12/10#message-20810130

現状、行番号をハイライトするために 'cursorline' か 'relativenumber' の設定が必要だが、
単独で設定するオプションが欲しいという話。

https://gist.github.com/ichizok/8d016c1e4c791499d092

```
'cursorlinenr' 'culn'  boolean (default: 未設定 (-1) )
                       local to window

現在行のハイライトの設定。
未設定の場合は従来通り ( 'cursorline' or 'relativenumber' による ) 。
off の場合は  'cursorline' , 'relativenumber' の値によらずハイライト無効。
on の場合は  'cursorline' , 'relativenumber' の値によらずハイライト有効。
```

という感じです。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/8d016c1e4c791499d092
ドキュメント追加

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/dQ-5znirV4Y
提案しました。

**Comment by koron** [comment]
:+1: great work!

**Comment by ichizok** [comment]
やはり boolean なのに unset が初期値なのはどうなんだ、と思って number に変えてみたんですが

> Using the magic numbers is hard to understand.  New options are probably
> better done with string values, such as "on", "off", and empty for not
> set.  Perhaps in this case "number", "line" and "both"?  But then naming
> it 'cursorlineopt' would be better.

ということで、`'cursorlineopt'` で書いてみました。

https://gist.github.com/ichizok/691aa7e848afd4aa8229c7a51aec895b

@itchyny どう思われますか？

**Comment by itchyny** [comment]
なるほど、よいと思います。状態が多い (`3*2*2=12`かな) ので表を書いて確認しないと既存の挙動が壊れていないかとかよくわからないですね。 `cursorlineopt=both` をデフォルトにしてしまうと、 `nocursorline norelativenumber` の挙動が変わってしまったりしないのでしょうか。一案ですが `cursorlineopt` が空の時は既存の通り `cursorline` or `relativenumber` にして、 `cursorlineopt` が空ではない時には `cursorline`, `relativenumber` に関わらず反映されるというのはどうでしょう？ (最初の `cursorlinenr` のアイディアと同じだと思いますが…) 状態が`4*2*2`に増えますが、空なら元の挙動で `cursorlineopt` が強いということであればそんなに大変ではないかなという印象です。

**Comment by ichizok** [comment]
> cursorlineopt=both をデフォルトにしてしまうと、 nocursorline norelativenumber の挙動が変わってしまったりしないのでしょうか。

`cursorlineopt` は `cursorline` (と `relativenumber`) の挙動を変えるオプションなので、`nocursorline` の時は何もしません (と解釈して実装しました)。
行番号だけをハイライトしたい場合は `set cursorline cursorlineopt=number` となります。

`cursorlineopt` | "line" | "number" | "both"
----------------|------|-----------|--------
**`cursorline` のハイライト対象** | 行の内容だけ | 行番号だけ | 両方 (現状の動作)
**`relativenumber` の動作の変化** | 行番号をハイライトしない | 現状と同じ | 現状と同じ

**Comment by itchyny** [comment]
すみません、勘違いしてしまいました。その挙動なら既存の動作を壊していないし大丈夫ですね。ありがとうございます。

**Comment by ichizok** [comment]
v8.0.0118 で todo に入りました。
https://github.com/vim/vim/blob/v8.0.0118/runtime/doc/todo.txt#L182
> Patch for 'cursorlinenr' option. (Ozaki Kiichi, 2016 Nov 30)

**Comment by k-takata** [comment]
[8.1.2019](https://github.com/vim/vim/commit/410e98a70bc00ea4bed51e55a8fe20e56a72c087) で取り込まれました。(vim/vim#4693)
