### ISSUE TITLE
showmatch for ruby is too slow

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#708]
gvim +kaoriya 7.4.648 (+ruby/dyn だけど Ruby 自体のpathが通ってないので、利用不可)

`showmatch` を設定 & `syntax on` にした状態で、以下の内容の ruby ファイル を開きカーソルを動かすと、カーソルがカッコの上に重なる時=showmatchが稼働する時に、明らかに遅くなる。

``` ruby
def foo
  return call_very_long_long_long_long_long_long_long_long_long_long_long_long_func({
                                                                                      aaa: 111,
                                                                                      bbb: 222,
                                                                                      ccc: 333,
                                                                                      ddd: 444,
                                                                                      eee: 555,
                                                                                      fff: 666,
  })
end
```

ポイントはインデントが深い、もしくは1行が長いことだと推測される。その根拠として、以下の、内容は一緒だがインデントが浅い、ファイルに対して同様の操作を行なっても、この問題は発生しない。

``` ruby
def foo
  return call_very_long_long_long_long_long_long_long_long_long_long_long_long_func({
    aaa: 111,
    bbb: 222,
    ccc: 333,
    ddd: 444,
    eee: 555,
    fff: 666,
  })
end
```

付け加えて、以下のようにJavaScriptでインデントの深いファイルに対しては問題が発生しないことから、ruby(ftplugin or syntax?)特有の問題であると推測される。

``` javascript
function foo() {
  return call_very_long_long_long_long_long_long_long_long_long_long_long_long_func({
                                                                                      aaa: 111,
                                                                                      bbb: 222,
                                                                                      ccc: 333,
                                                                                      ddd: 444,
                                                                                      eee: 555,
                                                                                      fff: 666
  });
}
```

**Comment by koron** [comment]
windows 以外、+kaoriya以外で発生するかどうかは、現時点で未調査です。

**Comment by mattn** [comment]
関連ありそうな部分

syntax/ruby.vim

``` vim
  syn region rubyMethodBlock start="\<def\>"    matchgroup=rubyDefine end="\%(\<def\_s\+\)\@<!\<end\>" contains=ALLBUT,@rubyNotTop fold
```

関数ブロックを探す為に、次のブロック end 部分を探し、それが含まれていない(ALLBUT)前方の def という探し方をしてる。そりゃ遅い。

**Comment by mattn** [comment]
まぁ、ruby の場合、なんでも end で終わろうとするか仕方ないのかな？

**Comment by koron** [comment]
遅くなるファイルから `def/end` を消しても同様に遅くなる。
あと618の時点では、そんなことがなかった気がしているので、この間に何かあったのかも。

**Comment by koron** [comment]
なお、長い行を含む少し大きめのファイルを作ると、
その箇所をカーソル動かすのすら苦痛になるほど遅くなった。
あとは…矩形選択とかも地獄。

**Comment by ichizok** [comment]
CentOS 7 デフォルトの vim-7.4.160 で試しても同様に遅かったです。

```
$ /usr/bin/vim -u NONE -N +'runtime plugin/matchparen.vim' +'runtime syntax/ruby.vim' +'set showmatch' test.rb
```

**Comment by todashuta** [comment]
Mac OS X で homebrew でインストールしている vim-7.4.488 で試しても同じく遅かったです。

```
$ /usr/local/bin/vim -u NONE -N +'runtime plugin/matchparen.vim' +'runtime syntax/ruby.vim' +'set showmatch' ~/tmp/test.rb
```

---

古い正規表現エンジン`set regexpengine=1`は、遅くなかったです。

```
$ /usr/local/bin/vim -u NONE -N +'runtime plugin/matchparen.vim' +'runtime syntax/ruby.vim' +'set showmatch regexpengine=1' ~/tmp/test.rb
```

**Comment by mopp** [comment]
Arch Linuxでビルドした7.4.648でも遅くなりました。
しかし、@todashuta さんが検証してる正規表現エンジン切り替えもやってみました
これについては、両方共に重くなりました。

``` ruby
def foo
  return call_very_long_long_long_long_long_long_long_long_long_long_long_long_func({
                                                                                      aaa: 111,
                                                                                      bbb: 222,
                                                                                      ccc: 333,
                                                                                      ddd: 444,
                                                                                      eee: 555,
                                                                                      fff: 666,
#ここから
  })
end
#ここへ
```

特に上記コードのコメントで囲ってある部分の移動だけ重たい感じがしました。

**Comment by koron** [comment]
現時点で疑わしき原因は以下のとおり。
-   plugin/matchparen.vim
-   syntax/ruby.vim
-   regexpengine=1

組み合わせかどうか、切り分けたいところ。

**Comment by koron** [comment]
調査記録 その1

   :augroup matchparen
   :au!
   :au END

で plugin/matchparen.vim を無効化すると、問題は停止し、発生しなくなる。

```
:set noshowmatch
```

だけだと効果はなし。

```
:set regexpengine=1
```

だけでも効果はなし。

**Comment by todashuta** [comment]
`:syntime`で調べてみました。

```
  TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  0.180515   9      0       0.034964    0.020057  rubyPredefinedConstant \%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(STD
ERR
  0.146247   9      0       0.027419    0.016250  rubyPredefinedConstant \%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(Mat
chi
  0.112675   9      0       0.019565    0.012519  rubyPredefinedConstant \%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(DAT
A\|
  0.083423   9      0       0.018985    0.009269  rubyPredefinedConstant \%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(RUB
Y_\
  0.009272   15     6       0.009075    0.000618  rubySymbol         []})\"':]\@<!\%(\h\|[^\x00-\x7F]\)\%(\w\|[
  0.002593   15     6       0.002023    0.000173  rubySymbol         \%([{(,]\_s*\)\@<=\l\w*[!?]\=::\@!
  0.000317   15     6       0.000069    0.000021  rubySymbol         \%([{(,]\_s*\)\@<=[[:space:],{]\l\w*[!?]\=
  0.000202   9      0       0.000044    0.000022  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(not\|or\|redo

  0.000185   9      0       0.000036    0.000021  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(public\|requi

  0.000184   21     12      0.000037    0.000009  rubyInteger        \%(\%(\w\|[]})\"']\s*\)\@<!-\)\=\<\%(0[dD]
  0.000180   9      0       0.000045    0.000020  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(load\|loop\|p

  0.000180   9      0       0.000038    0.000020  rubyConstant       \%(\%([.@$]\@<!\.\)\@<!\<\|::\)\_s*\zs\u\w
  0.000175   9      0       0.000042    0.000019  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(extend\|fail\

  0.000173   9      0       0.000030    0.000019  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(elsif\|end\|e

  0.000171   9      0       0.000031    0.000019  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(alias\|and\|b

  0.000170   9      0       0.000032    0.000019  rubyKeywordAsMethod \%(\%(\.\@<!\.\)\|::\)\_s*\%(undef\|unless

-- More --
```

sytax/ruby.vim (https://github.com/vim-jp/vim/blob/a2e15c376747f7309e204f2c247142a77f66611e/runtime/syntax/ruby.vim#L120-L122
)

``` vim
syn match rubyPredefinedConstant "\%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(MatchingData\|ARGF\|ARGV\|ENV\)\>\%(\s*(\)\@!"
syn match rubyPredefinedConstant "\%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(DATA\|FALSE\|NIL\)\>\%(\s*(\)\@!"
syn match rubyPredefinedConstant "\%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs\%(STDERR\|STDIN\|STDOUT\|TOPLEVEL_BINDING\|TRUE\)\>\%(\s*(\)\@!"
```

この3つで時間がかかっているようです。

で、vim-ruby のコミットをみると、これらのパターンに変更(改善?)が入ってて、最新のもので試したところ、こちらの環境では改善されているのが確認できました。

https://github.com/vim-ruby/vim-ruby/commit/b60da6c63bba329aa0327a2859639f9a02afc3ed

**Comment by koron** [comment]
syntax/ruby.vim だけ無効化した状態では、問題は発生せず。

ftplugin/ruby.vim だけ無効化した状態では、問題継続。

以上から plugin/matchparen.vim + syntax/ruby.vim の合わせ技で発生するっぽい。

**Comment by h-east** [comment]
@todashuta :+1: Nice!
でもそのvim-ruby のコミットって2013/6ですね。それが本家に反映されていないってことなんでしょうか？

**Comment by koron** [comment]
**計測方法**: `return` のある行の先頭にカーソルを置いた状態で `:syntime on` し、`$` で行末にカーソルを移動してから、`:syntime off` & `:syntime report` で計測。

これで比較すると `rubyPredefinedConstant` の SLOWEST が、matchparenの有無(`augroup matchparen | au! | au END`)で10倍位違ってました。なのでほぼ、それが確定でよいでしょう。

あと対策を行うのに必要なのは matchparen の有無がなぜ `rubyPredefinedConstant` に繋がるのか、くらいかなぁ。

**Comment by koron** [comment]
# まちがえたw

**Comment by todashuta** [comment]
@h-east はい。runtimeに入ってるのがどのコミットのバージョンか、とかまではわからないですが、2013/6よりは確実に古そうです。

**Comment by koron** [comment]
plugin/matchparen.vim の https://github.com/vim-jp/vim/blob/9ce3a1758ae7fd5d4a6e96dd91743328e9dc3057/runtime/plugin/matchparen.vim#L105-L106 この部分がsyntaxにアクセスしていそう。

**Comment by koron** [comment]
vim側の syntax/ruby.vim の最終更新は [13 Jun 2013](https://github.com/vim-jp/vim/blob/master/runtime/syntax/ruby.vim)

**Comment by koron** [comment]
とりあえず vim-ruby のほうに、bundled with vim を更新するように、issue 建てるべきかなぁ…

**Comment by koron** [comment]
追加で納得行かないのは、matchparenのせいで
カーソル移動のたびに <kbd>Ctrl</kbd> + <kbd>L</kbd> による再描画と同程度のsyntax処理が起動されうる
っていう点だなぁ。

**Comment by koron** [comment]
> カーソル移動のたびに <kbd>Ctrl</kbd> + <kbd>L</kbd> による再描画と同程度のsyntax処理が起動されうる

これ不可避だった。 plugin/matchparen.vim が `s:Highlight_Matching_Pair()` の最後にやってる `matchaddpos()` が再描画相当の処理を引き起こしている。なので syntax 側を十分高速であるようにメンテするか、plugin/matchparen を使わないようにするべき。

個人的には plugin/matchparen を使わないだけで十分だが…

**Comment by koron** [comment]
(セッション中での) matchparen の無効化は `:NoMatchParen` で良い。

augroup で潰す必要はなかった。

**Comment by h-east** [comment]
私の.vimrcには20世紀から

``` vim
let loaded_matchparen = 1
```

が書かれております。

**Comment by koron** [comment]
`showmatch` があるのに、どして matchparen があるのか ??? ってなってるところw

**Comment by koron** [comment]
ちなみに matchparen がやってるのは、文字列とか特定の syntax 内の文字が match しないように、くらい。

**Comment by h-east** [comment]
`showmatch`はインサートモードで`)`等を入力した時に対応する`(`等に一瞬カーソルを移動させる機能。
matchparenはノーマルモード時にカーソルが')'等に移動した時にそれ自身と対応する`(`等をhighlightする機能。
って感じですね。
私はどっちも必要としていないので両方offってます。

**Comment by koron** [comment]
とりあえずvim-rubyに調度良いissueもあったので、
ダメもとで「更新したら?」ってに書いてきました(sent report 扱い)。

で vim-jp としては、現時点ではなにもできることはないと判断して、wontfixで閉じておきます。
状況が変わったらタグを付け替えるか、reopenしましょう。

**Comment by h-east** [comment]
@koron お疲れ様です:+1:

**Comment by koron** [comment]
あと、正規表現の解析もしとく。

@h-east :bow:

**Comment by koron** [comment]
```
\%(\%(\.\@<!\.\)\@<!\|::\)\_s*\zs
```

これのうちの `\%(\.\@<!\.\)\@<!\_s*\zs` から、かなりヤバイ印象を受ける。

連続した空白がある& `\zs` の後ろがマッチしない場合に、
 `\_s*` の部分が1文字ずつ短くなってマッチを試みそう。

つまり `\%(\.\@<!\.\)\@<!\_s*\zsFOO` みたいな正規表現は、

```
SSSSFOO
```

に対して(`S` は空白)、 `SSSSFOO` としてマッチしてすぐに次の文字列を見に行ける。
しかしマッチしない場合には `S` を短くしつつ何度もトライする。

```
SSSSBAR
```

このような文字列に対しては `SSSSB` までみてマッチ失敗 & 開始位置を1文字すすめる。
次に `SSSB` まで見てマッチ失敗 & 開始位置を1文字すすめる…
次に `SSB` まで見てマッチ失敗 & 開始位置を1文字すすめる…
以下、同じことの繰り返し。

てなことが起こっているのでは、なかろうか。

---

ちなみに `\%(\.\@<!\.\)\@<!\_s*\zs` から、最初の前読み(?)否定を取り除いて
`\%(\.\)\@<!\_s*\zs` こうしたところ現象は発生しなくなった。

そこから
「前読み否定を含む前読み否定」 + 「前者がマッチしうるstar」
が問題を引き起こすと、一般化できるんじゃなかろか(推測)。

**Comment by h-east** [comment]
3日前に `syntax/ruby.vim` を更新しているんですけど、反応がないですねぇ。
https://github.com/vim-ruby/vim-ruby/issues/245

**Comment by koron** [comment]
ruby.vim が更新されたことで修正された。
手元の 8.0.0003 でも再現せず。

xclose/fixed に張り替えた。
