### ISSUE TITLE
vimでカーソルの表示位置がずれる

### ISSUE THREAD

**Issue by kyouryuukunn** [vim-jp/issues#712]
vim, gvimにおいて、アルファベットと日本語を同じ行で使用して、なおかつ画面幅より行が長くするとカーソルの表示位置と実際の位置がずれます。

**再現方法**
1.  1行に以下の文を入力する。
   
   ```
   あああああああaああああああああ
   ```
   
   (画面幅より長くなるように)
   aが行頭と末尾の時、またアルファベットの数が偶数の時も問題は発生しなかった。
2. その行上で、$で末尾に移動する。
3. カーソルが一つ前に表示される。

**使用環境**
-   Kaoriya 版vim 32bit 7.4.648
-   Windows7 64bit

**関係あるかもしれない問題**
-   相対行表示にするとカーソルの表示位置がずれる (#94)

**Comment by koron** [comment]
@kyouryuukunn 試してみましたが、以下のGIFアニメーションでわかるように、再現できているとは考えられません。

![01](https://cloud.githubusercontent.com/assets/468368/6633234/d74cfe7c-c988-11e4-82ce-ebe75adb0898.gif)

なにか、報告されていない設定や操作が関係している可能性があります。
各種の設定等を報告していただくか、発生時のスクリーンキャスト(GIFアニメ)などを作成&添付してもらえますか?

なお私がスクリーンキャストの作成につかったのは http://www.cockos.com/licecap/ です。

**Comment by kyouryuukunn** [comment]
set nowrap が必要だったようです。
![sample](https://cloud.githubusercontent.com/assets/1556311/6633867/bd23190a-c992-11e4-8d31-eb962ae28f50.gif)

**Comment by mattn** [comment]
vimrc を貰えませんか。もしくは再現する最少の vimrc を下さい。

**Comment by kyouryuukunn** [comment]
どうもwrapがオフの時にlinebreakがオンだと問題が発生するようです。

1: gvim -u NONE でデフォルト状態で起動
2: あああああああaああああああああ
を入力
3: 以下の設定をする
set nowrap
set linebreak

**Comment by todashuta** [comment]
MacVim、iTerm上のVimで再現しました。

発生条件
- `set nowrap`
- `set linebreak`
- 横スクロールする
- 行中のマルチバイト文字が、画面左端に字幅の半分だけ入ってる行(実際はそのように表示されないが)

起動

```
$ vim -u NONE -i NONE -N
:set nowrap linebreak
```

バッファをこの内容にする。

```
あaaaaaaaaaaaa
aあaaaaaaaaaaa
aaあaaaaaaaaaa
aaaあaaaaaaaaa
aaaaあaaaaaaaa
aaaaaあaaaaaaa
aaaaaaあaaaaaa
aaaaaaaあaaaaa
aaaaaaaaあaaaa
aaaaaaaaaあaaa
aaaaaaaaaaあaa
aaaaaaaaaaaあa
aaaaaaaaaaaaあ

あああああああ

aaaaaaaaaaaaaa
```

この状態で、`zl`で横スクロールしていく。
- 上半分の`あ`をずらして並べているほうは、ずれる行が下に移動していく。
- `あ`だけの行は、ずれる・ずれないが交互に起こる。
- `a`だけの行はずれが発生しない。

**Comment by h-east** [comment]
最小手順みつけました。( @todashuta ヒントThanks!)

``` bash
$ vim -N -u NONE -c "set nowrap linebreak"
```

``` vim
iああ<Esc>zl
```

`enc`が`utf-8`の場合はこんな感じになります。(Vim 7.4.662 on fedora20 via PuTTY)
![linebreak_bug](https://cloud.githubusercontent.com/assets/518808/6650982/302162b0-ca72-11e4-9498-ddeafa3cf82c.png)

`cp932`の場合はこんな感じ。(GVim 7.4.648 kaoriya 64bit on Windows7sp1)
![linebreak_bug_cp932](https://cloud.githubusercontent.com/assets/518808/6651004/5e32acf8-ca73-11e4-9583-1ce68f3a7fd6.png)

正常な表示はこれ。
![linebreak_bug_ok](https://cloud.githubusercontent.com/assets/518808/6651045/87b90ac6-ca74-11e4-932f-4ea120997f81.png)

横スクロールにより表示開始位置がマルチバイト文字の途中な場合は`<`を表示して調整するのですが、`linebreak`がマルチバイトに対応しそこねている箇所があるようです。

**Comment by mattn** [comment]
ここや

https://github.com/vim-jp/vim/blob/master/src/screen.c#L4485-L4510

**Comment by mattn** [comment]
まずはずれる問題

``` diff
diff -r a0198cebc8f4 src/screen.c
--- a/src/screen.c  Fri Mar 13 15:03:00 2015 +0100
+++ b/src/screen.c  Sat Mar 14 23:40:00 2015 +0900
@@ -4486,7 +4486,7 @@
        {
            char_u *p = ptr - (
 # ifdef FEAT_MBYTE
-               has_mbyte ? mb_l :
+               has_mbyte ? (*mb_head_off)(ptr, ptr - 1) :
 # endif
                1);
            /* TODO: is passing p for start of the line OK? */
```

**Comment by mattn** [comment]
なんか既存の動きがおかしい。

```
$ vim -N -u NONE -c "set nowrap linebreak"
```

```
i<tab>zz
```

![](http://go-gyazo.appspot.com/927d350b7f5a7957.png)

**Comment by mattn** [comment]
あ、僕の間違いだった。

**Comment by mattn** [comment]
``` diff
diff -r a0198cebc8f4 src/screen.c
--- a/src/screen.c  Fri Mar 13 15:03:00 2015 +0100
+++ b/src/screen.c  Sat Mar 14 23:56:44 2015 +0900
@@ -4486,7 +4486,7 @@
        {
            char_u *p = ptr - (
 # ifdef FEAT_MBYTE
-               has_mbyte ? mb_l :
+               has_mbyte ? (*mb_head_off)(line, ptr - 1) + 1 :
 # endif
                1);
            /* TODO: is passing p for start of the line OK? */
```

これで治る気がします。

**Comment by mattn** [comment]
`<` が表示されてないのは別途治す必要あり。

**Comment by mattn** [comment]
``` diff
diff -r a0198cebc8f4 src/screen.c
--- a/src/screen.c  Fri Mar 13 15:03:00 2015 +0100
+++ b/src/screen.c  Sun Mar 15 00:35:05 2015 +0900
@@ -4484,11 +4484,15 @@
         */
        if (wp->w_p_lbr && vim_isbreak(c) && !vim_isbreak(*ptr))
        {
+# ifdef FEAT_MBYTE
+           int off = has_mbyte ? (*mb_head_off)(line, ptr - 1) : 0;
+#endif
            char_u *p = ptr - (
 # ifdef FEAT_MBYTE
-               has_mbyte ? mb_l :
-# endif
-               1);
+           off +
+# endif
+           1);
+
            /* TODO: is passing p for start of the line OK? */
            n_extra = win_lbr_chartabsize(wp, line, p, (colnr_T)vcol,
                                    NULL) - 1;
@@ -4496,7 +4500,11 @@
            n_extra = (int)wp->w_buffer->b_p_ts
                       - vcol % (int)wp->w_buffer->b_p_ts - 1;

+# ifdef FEAT_MBYTE
+           c_extra = off ? MB_FILLER_CHAR : ' ';
+# else
            c_extra = ' ';
+# endif
            if (vim_iswhite(c))
            {
 #ifdef FEAT_CONCEAL
```

こんなのでどうでしょうか？

**Comment by h-east** [comment]
@mattn :+1: LGTM

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/0zRuaOBzI2Q

@h-east 画像拝借しました。

**Comment by h-east** [comment]
Patch 7.4.665
https://groups.google.com/d/msg/vim_dev/-OOveDAFnsY/4qzqjbXYxGsJ

@kyouryuukunn Issue登録ありがとうございました:+1:
