### ISSUE TITLE
ordered-dict の実装

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#713]
https://gist.github.com/ichizok/a23a24158dcce3ecab58
dict をordered-dict にしました。
`dict_T`, `dictitem_T` に linked-list 構造を追加する形で実装しています。
- `items(dict)`, `keys(dict)`, `values(dict)` で取れる配列
- `copy(dict)`, `extend(dict1, dict2)` の結果
- `echo dict`, `string(dict)` 等による表示

が、dict への追加順になります。

`g:`, `s:` 等の組み込み dict には対応していません。

https://gist.github.com/ichizok/6b97f9cd529c1b47fe2e
ベンチマーク。

https://gist.github.com/ichizok/6b97f9cd529c1b47fe2e#file-gistfile1-txt
要素数の少ない時 (~10000) は 5%前後、要素数100000では 10%以上速くなっています。

追記: &uarr; は `items()` の計測結果です。

https://gist.github.com/ichizok/6b97f9cd529c1b47fe2e#file-gistfile2-txt
dict に 要素数100000を追加する計測では、ordered-dict が 3~5%程度遅いです。

**Comment by ujihisa** [comment]
:+1:

**Comment by h-east** [comment]
:+1:

> goto iterate;
> ordered_loop:;

これはさすがにマクロにした方が良い気がする:sweat_smile:
ジャンプ2回と分岐1回がなくなるのでもうちょっとだけ早くなるかも

**Comment by ichizok** [comment]
> これはさすがにマクロにした方が良い気がする

そうですね、整理していく予定です

> ジャンプ2回と分岐1回がなくなるのでもうちょっとだけ早くなるかも

ループ処理 (`iterate:`) の中身を for の中に展開するということでしょうか？

**Comment by h-east** [comment]
``` c
iterate:
    {
        di = dictitem_alloc(DI2HIKEY(oi));
        ～
        ～
    }
```

を

``` c
#define DICT_COPY_PROC()    \
    do  \
    {   \
        di = dictitem_alloc(DI2HIKEY(oi));  \
        ～ \
        ～ \
    }   \
    while (0)
```

等のマクロにして、

``` c
    goto iterate;
    ordered_loop:;
```

や

``` c
    goto iterate;
    hashtab_loop:;
```

をそれぞれ

``` c
    DICT_COPY_PROC();
```

にするという意味です。

**Comment by ichizok** [comment]
この場合、ループ内の処理は関数の主要部分で、コード上明白にしたい箇所であり、
そこをマクロ化するのは記述的に粗すぎるのではないかと思うのです。
- つまり、純粋にCとして読み書きしたい、メンテナンス性を良くしておきたい箇所  
  （行末 '\' とか気にしないで良いように）ということです
- 泥臭い部分を抽象化して処理の意味を明確にするのがマクロの役割と考えています

とは言え、Vim のスタンスとしては（動作環境の多さを考えると）処理効率を優先すべきでしょうか？

**Comment by h-east** [comment]
個人的には...
メンテナンス性＞処理効率 の場合は関数にしますね。
処理効率＞メンテナンス性 の場合はマクロにすることもあります。

少なくとも今のコード(gotoで飛んでgotoで戻ってくる)はないんじゃないかなぁ。

OFF TOPIC
某MLを見てこれに返事していないのを思い出しました。:smile:
`:wincmd x`を試すといいかもです。

**Comment by koron** [comment]
goto&gotoには、私も反対しておきます。
流れを見たわけではないのですが…

ところでどうしてそうなっているのです?

**Comment by ichizok** [comment]
パッチを更新しました。
ループ内をクロージャっぽく見えるように（小手先ですが）

> ところでどうしてそうなっているのです?

2種類のイテレータに同じ処理を行わせたい場合、処理を一箇所にまとめる方法としては
- 関数化
- マクロ化
- goto

が挙げられると思いますが、
- 関数化は呼び出しコストが高い
- マクロ化は処理内容の記述性が低下する  

ということで、goto で、かつ処理の構造をコード上明確にすることを意図しました。

**Comment by koron** [comment]
`DICT_ITER_ERR` を使うときに
以下のようになるのが、ちょっと気持ち悪いですね。

``` c
DICT_ITER_ERR()
{
    dict_unref(copy);
    return NULL;
}
```

機能するかどうかではなく、読む/メンテする時の「驚き最小の原則」を考慮した意見です。

> 関数化は呼び出しコストが高い

それに関してはインライン化を期待すれば良いのではないでしょうか?

---

個人的な印象ですが、Vimは初期に書かれたコアの、少しでも遅くなると全体の操作感に影響が及ぶ箇所では、速度について考慮した書き方がされていますが、Vim scriptにまでくるとそこまで神経質ではないように感じます。

ですから「現在よりも遅くない or 速くなるから、ordered-listをマージしてよ」っていうアピールをするために、下手に最適化した書き方をしてメンテナンス性を下げるよりは、「ordered-list すっごい便利だろ、ちょっと速度は下がっちゃうけど、本当に問題だったらあとで考えようぜ」で、誰でもメンテしやすいコードを維持するほうがずっと良いと、私は考えます。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/100f0aecafa80309dcda
ループ内を関数化しました。

> それに関してはインライン化を期待すれば良いのではないでしょうか?

このサイズの処理で2回呼び出しがあると、`-O3` 以上でないとインライン化はなさそうです。
(gcc-4.8/4.9, clang-3.4/3.5 で検証)

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/a23a24158dcce3ecab58
元のパッチはマクロにしました。

関数化の処理速度は&plusmn;5%ほどの変化でした。

環境:
Ubuntu 14.10 / Core i5 2.5GHz / on VMware Fusion
OS X 10.10.2 / Core i5 2.5GHz

**Comment by koron** [comment]
私の意見は、本当にそれが良い機能の提案ならば(私は良い提案だと考えています)、速度を稼ぐためだけのような技巧的な部分は極力避け、メンテしやすい状態で早々のマージを狙うべきだ、ということです。

こういうのはまずマージされることがもっとも大事かつ大変だと考えています。マージの際にはレビューされているわけですから、そこで発生しうる抵抗感は少なくすることが、早々のマージには肝要です。いったんマージされてしまえば、あとからパフォーマンスチューニングだと言って、計測方法と結果を添付して最適化のコードを追加提案するのは、比較的に易しいと考えています。

**Comment by h-east** [comment]
引数なしのマクロはそこまで読みにくくないし、メンテナンス性も悪くないと思います。
修正されたpatchを見てもそう思いました。これでいいんじゃないですかね:+1:

Cの`inline`はmaybeなのであまり使わないですね。(特に組み込み系では)
Vimのソースコードでも使われていないです。

**Comment by koron** [comment]
このあたりは個人の見解の相違なのでアレですが、
(私が見た時点の) goto使ってそれをマクロで隠しなおかつ標準的な文法から離れたように見えてしまう版はよろしくない
という意見です。

現在の最新版(rev10)は、良いバランスになったと思います。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/a23a24158dcce3ecab58
update. 追加したが使ってなかった変数を削除

@h-east @koron レビューありがとうございます。

> こういうのはまずマージされることがもっとも大事かつ大変だと考えています。マージの際にはレビューされているわけですから、そこで発生しうる抵抗感は少なくすることが、早々のマージには肝要です。いったんマージされてしまえば、あとからパフォーマンスチューニングだと言って、計測方法と結果を添付して最適化のコードを追加提案するのは、比較的に易しいと考えています。

そうですね...こういう視点に欠けてました。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/dfacb32910b63a9e32ab
テスト結果の差分

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/2uYnVttQt-w
提案しました。

**Comment by koron** [comment]
:+1:

**Comment by ichizok** [comment]
todo に入りました。
https://github.com/vim-jp/vim/commit/0031847675d61157ebf9907d077a90ac60d5011c#diff-38d7929bd26d74d92ceddf984bbfc8dbR298

> Patch for ordered dict. (Ozaki Kiichi, 2015 May 7)
