### ISSUE TITLE
set shiftwidth=0 の場合に対応していないインデントファイルが存在する

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#714]
`:help 'shiftwidth'`には

> When zero the 'ts' value will be used.  Use the |shiftwidth()|
> function to get the effective shiftwidth value.

とありますが、実際には`shiftwidth()`が使われていないものがindent/以下に存在するため`set shiftwidth=0`という設定は事実上機能していないように思います。ひとまず`indent/vim.vim`のパッチを書いてみました、これを手本に作られているものもあるようなので。`:help shiftwidth()`の項に例のある`s:sw()`を使っています。もし問題があれば教えていただけると幸いです。

``` diff
diff -r 3bd553b9e4bf runtime/indent/vim.vim
--- a/runtime/indent/vim.vim    Sat Mar 14 15:35:52 2015 +0100
+++ b/runtime/indent/vim.vim    Sun Mar 15 14:16:29 2015 +0800
@@ -58,19 +58,19 @@
     if exists("g:vim_indent_cont")
       let ind = ind + g:vim_indent_cont
     else
-      let ind = ind + &sw * 3
+      let ind = ind + s:sw() * 3
     endif
   elseif prev_text =~ '^\s*aug\%[roup]' && prev_text !~ '^\s*aug\%[roup]\s*!\=\s\+END'
-    let ind = ind + &sw
+    let ind = ind + s:sw()
   else
     " A line starting with :au does not increment/decrement indent.
     if prev_text !~ '^\s*au\%[tocmd]'
       let i = match(prev_text, '\(^\||\)\s*\(if\|wh\%[ile]\|for\|try\|cat\%[ch]\|fina\%[lly]\|fu\%[nction]\|el\%[seif]\)\>')
       if i >= 0
-   let ind += &sw
+   let ind += s:sw()
    if strpart(prev_text, i, 1) == '|' && has('syntax_items')
          \ && synIDattr(synID(lnum, i, 1), "name") =~ '\(Comment\|String\)$'
-     let ind -= &sw
+     let ind -= s:sw()
    endif
       endif
     endif
@@ -82,7 +82,7 @@
   let i = match(prev_text, '[^\\]|\s*\(ene\@!\)')
   if i > 0 && prev_text !~ '^\s*au\%[tocmd]'
     if !has('syntax_items') || synIDattr(synID(lnum, i + 2, 1), "name") !~ '\(Comment\|String\)$'
-      let ind = ind - &sw
+      let ind = ind - s:sw()
     endif
   endif

@@ -90,12 +90,22 @@
   " Subtract a 'shiftwidth' on a :endif, :endwhile, :catch, :finally, :endtry,
   " :endfun, :else and :augroup END.
   if cur_text =~ '^\s*\(ene\@!\|cat\|fina\|el\|aug\%[roup]\s*!\=\s\+[eE][nN][dD]\)'
-    let ind = ind - &sw
+    let ind = ind - s:sw()
   endif

   return ind
 endfunction

+if exists('*shiftwidth')
+  func s:sw()
+    return shiftwidth()
+  endfunc
+else
+  func s:sw()
+    return &sw
+  endfunc
+endif
+
 let &cpo = s:keepcpo
 unlet s:keepcpo

```

**Comment by mattn** [comment]
個人的には専用の autoload 関数を作って全てそれを使う修正にした方がいいかなーと思います。

**Comment by machakann** [comment]
以前のバージョンで動かなくなる心配をしましたが、runtimeファイルはまとめて更新されるので問題ないですね。しかし、後方互換を考えなくていいなら単純に`&sw`を`shiftwidth()`で置換すればいい気もしてきました。

**Comment by mattn** [comment]
https://gist.github.com/mattn/f2d00a2b26044d840a4c

結構ありますね(汗)

**Comment by machakann** [comment]
思ったより多いです…せめてgrepしてから発言すべきだった…

**Comment by machakann** [comment]
ひとまず`:argdo`で機械的にやりましたが、表記ゆれなどあるかもしれないので後で確認します。

https://gist.github.com/machakann/3ddc492f2884d50ad2ba#file-update_indent_files-patch

**Comment by crazymaster** [comment]
ping

**Comment by crazymaster** [comment]
https://github.com/vim/vim/pull/578#issuecomment-174314013

**Comment by k-takata** [comment]
> Please send patches to each maintainer.

つらい

**Comment by mattn** [comment]
丸投げｷﾀｰ

On 1/25/16, K.Takata notifications@github.com wrote:

> > Please send patches to each maintainer.
> 
> つらい
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/714#issuecomment-174349951

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
> I think shiftwidth() function wrapper is not necessary.
> Because runtime files should not be distributed with an older Vim.

wrapperが必要かどうかは結局各メンテナーの判断次第になってしまいますね。

**Comment by machakann** [comment]
すいません、すっかり忘れていました。
各メンテナーにメールか…

**Comment by tyru** [comment]
とりあえず送りました…
https://groups.google.com/forum/#!topic/vim_dev/R046Odhv8rY

GitHubのURLが書いてあるindent pluginなんかもあったけど、個別でPR送るとかは流石に面倒…
(でもPR出してくれはメンテナの誰かから言われそうな気はする…うっ)

**Comment by tyru** [comment]
> wrapperが必要かどうかは結局各メンテナーの判断次第になってしまいますね。

これはBramさんの判断に基づいて削除しました。
が、メンテナによっては削除するべきでないと言う可能性はありますね。

**Comment by tyru** [comment]
すぐには返信来なさそうです…
まぁ自分には来ないでBramさんにだけ返信した可能性もありますが…

Vimインデントプラグインメンテナ一覧
https://docs.google.com/spreadsheets/d/1-HeWlsLC-tJDfuXQjtkZmY5UwXakAuYg83z9nz7nl2w/edit?usp=sharing

**Comment by tyru** [comment]
Vimインデントプラグインメンテナ一覧更新しました。
- メンテナ一覧に取り込まれたパッチ番号とGitHubのコミットへのリンクを記載しました。
- メンテナからの「連絡あり」が「○」でパッチ番号のセルが空(=まだ取り込まれてない、つまりBramさんがまだ適用していない)のものについて、パッチ番号のセルを赤で表示するようにしました。
- (リストを作る前にすでにマージされていた)vim.vimが抜けていたので追記しました。

**Comment by k-takata** [comment]
Syntax files: Removed check for version < 600
https://groups.google.com/d/topic/vim_dev/mRhdDBJh07Y/discussion
Bram氏自らによるバージョンチェックの削除と、HiLinkの削除が入りました。

> If you maintain a syntax file, please compare with the version currently
> in the repository and update your local copy, if needed.  You can also
> remove the use of the HiLink command and use ":hi def link" directly.

`'sw'` については言及されていませんが、同様に修正されていますね。
本当に全部直っているかは確認していませんが、おそらく大丈夫だろうということで閉じます。

**Comment by tyru** [comment]
Bram氏自ら…
もう runtime も Vim のリポジトリで管理するようにして、連絡の付かないメンテナの人に振り回されるのを無くしたいですね。
今提案するのは無理ですかね…（「もうVimリポジトリで管理するようにしない？」って仄めかす位のメールなら…とかちょっと思いましたが）

**Comment by tyru** [comment]
（reactions 付いてたので）

> （「もうVimリポジトリで管理するようにしない？」って仄めかす位のメールなら…とかちょっと思いましたが）

ちなみに送ってもお前今それ言うかみたいな対応になると予想してるので自分はやらないです！

**Comment by machakann** [comment]
よかったです。Vim 8.0 から心置きなく `set shiftwidth=0` が使えるのは気分がいいですね。
