### ISSUE TITLE
WindowsのgVimでスクロールするとゴミが残る

### ISSUE THREAD

**Issue by yoheie** [vim-jp/issues#715]
WindowsのgVimでホイールスクロールすると、別の行の文字がゴミとして残ってしまう場合があります。

![](https://pbs.twimg.com/media/B_4xVhdU0AAYJu-.png:large)

> 発生条件はまだ明確になっていない。ウィンドウを分割した下の方で出やすい気がするけど気のせいかもしれない。 
> カーソルがいた場所にあった文字が、マウスホイールでスクロールした後の場所に表示として残ってしまうことがある、という現象のようだ。
> 今のところ、水平分割したウィンドウでしか発生していない。それとマウスホイールでのスクロールのみで、hjklとかでは発生していない。
> ウィンドウ分割は関係ないようだ。行数が特定の範囲の時に発生するっぽい。 

カーソルがいた場所にあった文字が、マウスホイールでスクロールした後の場所に表示として残ってしまっているようです。

確認環境:
- OS : Windows 7 32bit
- Vimのバージョン : 7.4.648 Kaoriya版

確認手順:
1. 各行の文字数が揃っていないテキストファイルをgVimで開く。
2. $でカーソルを行末へ移動。
3. 適当にホイールスクロールする。

表示行数が一定の範囲内のとき発生するようです。
私の環境ではホイールスクロールの行数が5行になっていて、表示行数が8行〜33行のときに発生しています。

_vimrc・_gvimrcは消した状態でも発生しています。

**Comment by mattn** [comment]
お手数ですが `test.txt` を頂けますか。

**Comment by mattn** [comment]
いくらか引用させて頂きました。問題ありましたら消しますのでご指摘下さい。

**Comment by yoheie** [comment]
> お手数ですが test.txt を頂けますか。

gist に置いておきました。

https://gist.github.com/yoheie/7c12e39e512104efb527

**Comment by mattn** [comment]
うむ。僕の環境では再現しなかったでです。 
OS : Windows 7 32bit
自家製ビルド
誰か他の人、再現確認してもえらますか。

**Comment by hokorobi** [comment]
僕の環境でも再現しませんでした。
OS : Windows 7 64bit
Vimのバージョン : 7.4.648 Kaoriya版

**Comment by mattn** [comment]
@yoheie 何かオプションが絡んでませんか？`gvim -u NONE -N test.txt`  で確認して頂けますか。

**Comment by LeafCage** [comment]
私はメイリオを使っていたときにその問題に悩まされた記憶があります。
フォントを変更してMigu_1Mを使うことで発生しなくなりました。
相性の悪いフォントがあるのだと思います。
yoheieさんの 'guifont' オプションの値を教えてもらいたいですね。

**Comment by yoheie** [comment]
あらためて確認しましたところ、全く同じ設定でも別のPCでは問題が発生しませんでした。
発生するPCでは `gvim -u NONE -N test.txt` でも発生します。
guifontはどちらの環境でもMS_Gothic:h10:cSHIFTJISです。

特定の環境でしか発生しないことが分かりましたので、まずは私の方で環境側の要因を調べてみます。

**Comment by yoheie** [comment]
経過報告です。

現時点で問題が発生する PC は 2台、発生しない PC は 2台です。 4台とも Windows 7 32bit です。
(発生する PC はいずれも Professional 、発生しない PC はいずれも Ultimate ですが、これは多分関係ないでしょう…)
発生する環境側要因はまだ明らかになっていません。

問題が発生する 2台目の PC では、ホイールスクロールの行数は 3行で、表示行数が6～38行のときに発生します。

guifont は下記を試しましたが、どのフォントでも発生します。
(`gvim -u NONE -N test.txt` で起動、 `set guifont=` でフォントを変更後ホイールスクロールして確認)
- MS_Gothic
- MS_Mincho
- Terminal
- IPAゴシック
- IPA明朝
- Migu_1M

**Comment by koron** [comment]
renderoptionsでDirectX使ってますか?

**Comment by koron** [comment]
ああ `-u NONE` でも発生するのか。スマンす。

**Comment by koron** [comment]
@yoheie 関係ないかもですが、グラフィックカードのメーカー(チップ)やドライバーのバージョン番号って、わかりませんかね?

発生する環境には、何か共通項があるんじゃないかと推測しています。

**Comment by koron** [comment]
> 問題が発生する PC は 2台、発生しない PC は 2台です。 4台とも Windows 7 32bit です。
> 発生する PC はいずれも Professional 、発生しない PC はいずれも Ultimate です

って、これ関係あるんじゃないかな… 綺麗に分かれてるんだし。

**Comment by yoheie** [comment]
すみません、その後調べていたらUltimateの1台でも出ました…
グラフィックは、問題の出るPCは全部Intelでした。
チップやドライバのバージョンはバラバラだったと思いますが、今すぐ確認できるPCが1台だけなのでまた後で確認します。

**Comment by yoheie** [comment]
問題が出る環境:
- Intel(R) HD Graphics Family 8.15.10.2418
- Intel(R) G45/G43 Express Chipset 8.15.10.2119
- Mobile Intel(R) 4 Series Express Chipset Family 8.15.10.1883

問題が出ていない環境:
- NVIDIA GeForce 7600 GS 9.18.13.908

でした。

**Comment by koron** [comment]
つまり Intel か。私もあとで試してみます。

**Comment by koron** [comment]
とりあえず以下の環境で試したが再現しなかった (´・ω・`)
- Windows 7 64bit
- Intel(R) HD Graphics 4000 (ドライバー 10.18.10.3958)
- Vim 7.4.674 +kaoriya ([snapshot版](https://github.com/koron/upgorade))

ドライバーのバージョンかしら?

**Comment by koron** [comment]
ちなみに最新のドライバーは 15.X とかみたいw

**Comment by yoheie** [comment]
考えられるのは
- ドライバのバージョンにも依存
- 32bit版のみで発生
- 実はまったく別の原因が存在

といったところでしょうか。

**Comment by mattn** [comment]
@yoheie マウスはOEM提供ドライバでしょうか？物によっては WM_MOUSEHWHEEL だったりスクロールバーにメッセージを送ったりする物だったり色々だった気がします。

**Comment by tyochiai** [comment]
64 bit 版で起きてるので環境投下します。
(gvim -u NONE -N test.txt にて確認)
- Windows 8.1 Pro 64 bit
- Intel(R) HD Graphics 4600 (ドライバー 10.18.10.3621)
- Kaoriya Vim 64 bit 版 (適用済みパッチ: 1-648)

マウスのドライバは OS のをそのまま使ってるみたいです。

**Comment by yoheie** [comment]
マウスのドライバは、発生しないPCと発生するPCのうちの1台はメーカー独自、残りの2台はWindows標準のものです。

別の要因、あるいは複合的な要因である可能性を考えて、私の確認した4台で発生する環境と発生しない環境の相違点を調べてみました。
- Microsoft Office (2007 or 2010) がインストールされている
- Visual Studio (Express 2010・2012・2013) がインストールされている

が候補として挙げられるかもしれません。

**Comment by yoheie** [comment]
ご報告が遅くなってしまいましたが、

> Microsoft Office (2007 or 2010) がインストールされている
> Visual Studio (Express 2010・2012・2013) がインストールされている

これらにつきましては未インストールのPCで発生することを確認しました。
やはり共通点はIntelのグラフィックということになりそうです。

**Comment by yoheie** [comment]
だいぶ経ってしまいましたが追加情報です。
- ホイールスクロールだけでなくスクロールバーによるスクロールでも発生します。
- vim.org で公開されている [gvim74.zip](http://ftp.vim.org/pub/vim/pc/gvim74.zip) の gvim.exe でも発生します。

**Comment by yoheie** [comment]
すみません、間違って閉じちゃったので開き直しました…
ホイールスクロールに限らないのでタイトルを修正しました。

**Comment by mattn** [comment]
ちなみに ClearType の設定を変えてますでしょうか？

**Comment by yoheie** [comment]
特に設定を変えたということはなかったと思います。
ClearTypeは有効になっています。

**Comment by ynkdir** [comment]
windows10 ですが、以下の手順でたまに出ます。 (`...PPP     O`)
タイミングの問題なので再現性があれですが。
screenchar() ではキャッチできないので発生したら停止とかはできず。

```
> gvim -u NONE test.txt
:set lines?
  lines=25
:echo v:windowid
12345

という状況で

> a.exe 12345
```

``` c
// a.c
#include <windows.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
    HWND hwnd = (HWND)atoi(argv[1]);
    SetForegroundWindow(hwnd);
    SendMessage(hwnd, WM_CHAR, 'g', 0);
    SendMessage(hwnd, WM_CHAR, 'g', 0);
    SendMessage(hwnd, WM_CHAR, '$', 0);
    for (;;) {
        for (int i = 0; i < 25; ++i) {
            SendMessage(hwnd, WM_MOUSEWHEEL, 0x80000000 /* down */, 0);
            Sleep(1);
        }
        Sleep(1000);
        for (int i = 0; i < 25; ++i) {
            SendMessage(hwnd, WM_MOUSEWHEEL, 0x10000000 /* up */, 0);
            Sleep(1);
        }
        Sleep(1000);
    }
    return 0;
}
```

**Comment by mattn** [comment]
Windows 8.1 ですが再現しないすね。

**Comment by ynkdir** [comment]
自動で止まる版

``` c
#include <windows.h>
#include <stdlib.h>
#include <stdio.h>

HWND s_textArea;

static BOOL CALLBACK findtextarea(HWND hwnd, LPARAM lParam);

int main(int argc, char **argv) {
    HWND hwnd = (HWND)atoi(argv[1]);
    EnumChildWindows(hwnd, findtextarea, 0);
    SetForegroundWindow(hwnd);
    SendMessage(hwnd, WM_CHAR, 'g', 0);
    SendMessage(hwnd, WM_CHAR, 'g', 0);
    SendMessage(hwnd, WM_CHAR, '$', 0);
    for (;;) {
        for (int i = 0; i < 25; ++i) {
            SendMessage(hwnd, WM_MOUSEWHEEL, 0x80000000 /* down */, 0);
            Sleep(1);
        }
        // FIXME:
        int y = 5;
        HDC hdc = GetDC(s_textArea);
        for (int x = 390; x < 400; ++x) {
            if (GetPixel(hdc, x, y) != 0xFFFFFF) {
                ReleaseDC(s_textArea, hdc);
                return 0;
            }
        }
        ReleaseDC(s_textArea, hdc);
        Sleep(1000);
        for (int i = 0; i < 25; ++i) {
            SendMessage(hwnd, WM_MOUSEWHEEL, 0x10000000 /* up */, 0);
            Sleep(1);
        }
        Sleep(1000);
    }
    return 0;
}

static BOOL CALLBACK findtextarea(HWND hwnd, LPARAM lParam) {
    char buf[100];
    GetClassName(hwnd, buf, sizeof(buf));
    if (lstrcmp(buf, "VimTextArea") == 0) {
        s_textArea = hwnd;
        return FALSE;
    }
    return TRUE;
}
```

**Comment by ynkdir** [comment]
> Windows 8.1 ですが再現しないすね。

むぅ、そうですか。

**Comment by mattn** [comment]
あ！再現しました。↑のテキストじゃないと再現しないのかな。

**Comment by mattn** [comment]
えーっと、カーソルが一番左にあると再現しないです。つまり want の位置が行末よりも右側にある行がスクロールされると再現しますね。

**Comment by mattn** [comment]
![](http://i.imgur.com/cyAk6F6.gif)

**Comment by ynkdir** [comment]
ｷﾞﾌﾞｱｯﾌﾟ

スクロールかカーソル描画のあたりだろうなと思って見てたんですがよくわからないです。

試しに ScrollWindowEx() 呼び出しの直前にスクロールで消えるはずの場所にテキストを描画してみたらこれもたまに残ります。なぞ。

``` diff
diff --git a/src/gui_w48.c b/src/gui_w48.c
index 1096ec8..5ff799f 100644
--- a/src/gui_w48.c
+++ b/src/gui_w48.c
@@ -3013,6 +3013,7 @@ gui_mch_delete_lines(
     rc.top = FILL_Y(row);
     rc.bottom = FILL_Y(gui.scroll_region_bot + 1);

+    gui_mch_draw_string(0, 55, "X", 1, 0);
     ScrollWindowEx(s_textArea, 0, -num_lines * gui.char_height,
                    &rc, &rc, NULL, NULL, get_scroll_flags());

```

**Comment by h-east** [comment]
普段、ノートPCのタッチパッドでスクロール操作とかしないのでこの現象に遭遇したことなかったですが、いざスクロール操作をおこなうと簡単に再現しますやん。

ちょっと傾向が分かったのでお伝えします。

```

AAAAAAAAAA
____________________
//////////////////////////////
||||||||||||||||||||||||||||||||||||||||||||||||||
```

上記5行をGVimにコピペして`5Y200P`等で増殖させて下さい。
そして`$`した後、マウスホイールでスクロール動作をします。
結構頻繁にゴミが表示されると思います。
でも、ゴミの表示される場所が5箇所しかないんですよ。
その場所は各行の行末です。(1, 10, 20, 30, 50カラム)

おそらく、ホイールスクロールしてカーソルのある行が画面表示領域から外れた時にスクロール後の画面表示内の行にカーソルを移動させる処理が、Windowsイベント(ホイールスクロール)と排他制御されていないとかじゃないかなーと思ってます。(テキトー言ってます)
Windowsのビルド&デバッグ環境構築していないので直ぐには追いかけれないです。

**Comment by h-east** [comment]
私が書いてる事 @yoheie さんがIssue本文に書いてるし、検証用テキストデータもそれを踏まえたものになっていますね。すんません。

私の予測をも一回整理して言うと、「mainループで`update_screen()`等の画面描画更新処理の最中に、Windowプロシージャに`WM_MOUSEWHEEL`イベントが発生してその処理中(`_OnMouseWheel()`)に`update_screen()`が参照している変数を直接変更したりしてるんじゃないか。」説です。

**Comment by mattn** [comment]
可能性としてビンゴかもしれませんね。

``` diff
diff --git a/src/screen.c b/src/screen.c
index b1af862..82fb488 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -475,11 +475,16 @@ update_screen(type)
 #if defined(FEAT_SEARCH_EXTRA) || defined(FEAT_CLIPBOARD)
     int        did_one;
 #endif
+    static int updating = FALSE;

     /* Don't do anything if the screen structures are (not yet) valid. */
     if (!screen_valid(TRUE))
    return;

+    if (updating)
+   return;
+    updating = TRUE;
+
     if (must_redraw)
     {
    if (type < must_redraw)     /* use maximal type */
@@ -504,6 +509,7 @@ update_screen(type)
    must_redraw = type;
    if (type > INVERTED_ALL)
        curwin->w_lines_valid = 0;  /* don't use w_lines[].wl_size now */
+   updating = FALSE;
    return;
     }

@@ -732,6 +738,7 @@ update_screen(type)
    gui_update_scrollbars(FALSE);
     }
 #endif
+    updating = FALSE;
 }

 #if defined(FEAT_CONCEAL) || defined(PROTO)
```

これで再現しなくなりました。
update_screen の中で読んでる関数のどれかが、もう一度 update_screen を呼び出す可能性がある様です。

**Comment by h-east** [comment]
マジですか！:+1: 
試せないのがもどかしい。
私は描画更新処理を`mutex`とかで排他制御しないといけないんじゃないかと思ってました。
(mainループ、Windowプロシージャ別スレッドだし)

**Comment by mattn** [comment]
> (mainループ、Windowプロシージャ別スレッドだし)

PeekMessage 使って回してるだけで別スレッドではないと思いますよ。

**Comment by h-east** [comment]
あれ？じゃぁこれはどう解釈すればいいんでしょう。
gui.h : 61

``` c
/*
 * On some systems scrolling needs to be done right away instead of in the
 * main loop.
 */
#if defined(FEAT_GUI_MSWIN) || defined(FEAT_GUI_MAC) || defined(FEAT_GUI_GTK)
# define USE_ON_FLY_SCROLL
#endif
```

by Google翻訳
一部のシステムではスクロールがメインループではなく、すぐに実行する必要があります。

**Comment by mattn** [comment]
USE_ON_FLY_SCROLL はスクロールイベントを受け取った時に、自前で描画を更新しちゃうか、いったん KS_VER_SCROLLBAR を発動させてスクロールさせるかの切り替えかと思います。(たぶん)

Windows のプログラミング自体、GetMessage でメッセージを取り出して、TranslateMessage して...という流れなので、通常はこのセットをループさせるんですが、vim 等のアプリケーションは他のイベントも拾う必要があり、PeekMessage してメッセージが無かったら他の処理、あればイベント処理(実際はコールバック)という処理をやっていますね。

**Comment by h-east** [comment]
@mattn 解説ありがとうございます。なんとなくですが理解しました。
ということはVimはシングルスレッドだから一筆書き的に動いているのでまっつんさんのpatchでOKということですね。

**Comment by ynkdir** [comment]
mattn さんのパッチ当てても発生しました。

**Comment by mattn** [comment]
おろろ。確認が甘かったかな。。。出直してきます。

**Comment by mattn** [comment]
なんでか僕んとこパッチ前でも再現しなくなっちゃった。 win8.1

**Comment by ynkdir** [comment]
> 試しに ScrollWindowEx() 呼び出しの直前にスクロールで消えるはずの場所にテキストを描画してみたらこれもたまに残ります。なぞ。

ちなみにこれの最小限のコード。
https://gist.github.com/ynkdir/18b8bb9e517d94ebc747

Windows 10 Home 64bit
Intel(R) HD Graphics 3000 2015/05/27 9.17.10.4229

**Comment by yoheie** [comment]
> ちなみにこれの最小限のコード。
> https://gist.github.com/ynkdir/18b8bb9e517d94ebc747

私のところでも確認しました。これで出るということはVim側の処理じゃなくて
Intelのドライバに何か問題がある可能性が高いですかね...

Windows 7 Ultimate 32bit
Mobile Intel(R) 4 Series Express Chipset Family 8.15.10.1883
VC++ 2010 Express でビルド

**Comment by ynkdir** [comment]
Vim のコードあんまり把握できてないのでなんとも言えないですが

もしかしたら同じ話かも

スクロール時のゴミ表示について
http://www.maruo.co.jp/turukame/3/x07939_.html

**Comment by yoheie** [comment]
> スクロール時のゴミ表示について
> http://www.maruo.co.jp/turukame/3/x07939_.html

リンク先の情報をもとに、 gui.c gui_update_cursor() の最後に
GetPixel() を入れてみると問題が発生しなくなりました。

``` diff
diff --git a/src/gui.c b/src/gui.c
index fc2981c..02dbc1b 100644
--- a/src/gui.c
+++ b/src/gui.c
@@ -1046,6 +1046,10 @@ gui_check_pos()
    gui.cursor_is_valid = FALSE;
 }

+#ifdef FEAT_GUI_MSWIN      /* Workaround for Intel GPU bug(?) */
+extern void gui_intel_gpu_workaround(int x, int y);
+#endif
+
 /*
  * Redraw the cursor if necessary or when forced.
  * Careful: The contents of ScreenLines[] must match what is on the screen,
@@ -1285,6 +1289,9 @@ gui_update_cursor(force, clear_selection)
 #endif
    }
    gui.highlight_mask = old_hl_mask;
+#ifdef FEAT_GUI_MSWIN      /* Workaround for Intel GPU bug(?) */
+   gui_intel_gpu_workaround(FILL_X(gui.col), FILL_Y(gui.row));
+#endif
     }
 }

diff --git a/src/gui_w48.c b/src/gui_w48.c
index 1096ec8..4135996 100644
--- a/src/gui_w48.c
+++ b/src/gui_w48.c
@@ -4041,3 +4041,9 @@ done:
     *argvp = argv;
     return argc;
 }
+
+    void
+gui_intel_gpu_workaround(int x, int y)
+{
+    GetPixel(s_hdc, x, y);
+}
```

**Comment by ynkdir** [comment]
gui_undraw_cursor() のほうも必要かなと思います。
個人的には ScrollWindowEX() の直前でやるのがよさそうかと思いましたわかりませんが。

**Comment by mattn** [comment]
直ってるのを確認しました。
なんで直るのかわからずいろんなAPIで代替してみましたがダメでした。

**Comment by mattn** [comment]
たぶん家のノートで再現しなかったの、ホイールを使わなかったからだと思います。

**Comment by h-east** [comment]
@yoheie :+1: 素晴らしい！
patch提出時は `gui_intel_gpu_workaround()`のプロトタイプ宣言は `src/proto/` の `gui_w16.pro` と `gui_w32.pro` にそれぞれ書いた方が良いと思います。(16 + 32 = 48 ですんで)

**Comment by mattn** [comment]
てかこのまま vim-dev に持って行ってはたして取り込んでくれるだろうか

**Comment by h-east** [comment]
@mattn 皆で「俺のPCでも起きてて困ってたんだけど、このpatchで直ったぜ！Awesome!!」射撃しましょう！

**Comment by mattn** [comment]
とりあえず僕がやったこと
- GdiFlush だめ
- GetBkMode だめ
- ReleaseDC(s_hwnd, GetDC(s_hwnd)) だめ
- InvalidateRect(最終引数TRUE) だめ

しかもこの GetPixel、書き直した位置(X_FILL/Y_FILL)じゃないと直らない。

**Comment by yoheie** [comment]
gui_update_cursor() の最後だと、スクロールと関係ないときにも
カーソルの再描画で毎回実行してしまうと思うので、どこに入れるのが
適切かはちゃんと検討しないとならないと思っていますが、
まだソースコードを追いきれていないです。

ScrollWindowEx() ですが、 gui_mch_delete_lines()・gui_mch_insert_lines() からしか
呼んでいなくて、スクロールのときは実行されていないように思えるのですが…

**Comment by ynkdir** [comment]
> ScrollWindowEx() ですが、 gui_mch_delete_lines()・gui_mch_insert_lines() からしか
>  呼んでいなくて、スクロールのときは実行されていないように思えるのですが…

スクロールメッセージを受け取ったら直接は画面更新せずに curwin なんかの内部状態を更新してその後 update_screen() あたりから画面更新用のメッセージが生成 (screen_del_lines()のout_char("\n")) されて gui_write() から呼ばれます。私もよくわかってませんが。

**Comment by ynkdir** [comment]
回避方法ですが 'renderoptions' で directx を指定すると発生しなくなるかもしれません。

**Comment by koron** [comment]
うちのマウス、タッチマウスでスクロールが良い感じでピーキーなので
Intel のグラフィックでも発生しないのかも (；´∀｀)

# 参加できなくて寂しい

**Comment by yoheie** [comment]
> 回避方法ですが 'renderoptions' で directx を指定すると発生しなくなるかもしれません。

私の環境ではこの方法でも回避できませんでした。

パッチですが、 @ynkdir さんのご指摘どおり ScrollWindowEx() の直前で行うようにしてみました。
https://gist.github.com/yoheie/9630ef5008870fb6378e
問題無さそうであれば vim_dev にパッチを提出するつもりで、メールの原稿も書いてみました。
添削お願いいたします。

**Comment by ynkdir** [comment]
> 私の環境ではこの方法でも回避できませんでした。

いちおう確認したいんですがenc=utf-8とttfフォントも指定しましたか
`:set enc=utf-8 guifont=MS_Gothic:h12:cANSI renderoptions=type:directx`

**Comment by ynkdir** [comment]
> 添削お願いいたします。

よさげに思います。

**Comment by yoheie** [comment]
@ynkdir 

> いちおう確認したいんですがenc=utf-8とttfフォントも指定しましたか
> `:set enc=utf-8 guifont=MS_Gothic:h12:cANSI renderoptions=type:directx`

gvim.exe -u NONE -N で起動後 enc・guifont・renderoptions 全てをそのとおり
指定したところ回避できました。
どれか1つ指定しないだけでも発生していました。

**Comment by h-east** [comment]
@yoheie patch＆メール内容問題ないと思います。:+1:
このバグ、仕事先のDELLのdesktop(Windows 7 64bit)、自宅のGateway ノートPC(Windows 10 64bit)でも起きているので、その情報も足しておいても良いかもしれません。

**Comment by yoheie** [comment]
directx が有効だと問題が発生しないようなので、intel_gpu_workaround()の先頭に
チェックを入れておいた方が良いでしょうか。

```
intel_gpu_workaround(void)
{
#if defined(FEAT_DIRECTX)
    if (IS_ENABLE_DIRECTX())
        return;
#endif
    GetPixel(s_hdc, FILL_X(gui.col), FILL_Y(gui.row));
}
```

もう1点気になる点として、この問題、16bit Windowsでは発生するのでしょうか。
さすがに私の方では環境を用意できないです…

**Comment by yoheie** [comment]
あ、encとフォントもチェックしないとダメですね。

**Comment by yoheie** [comment]
これでどうでしょう。

```
intel_gpu_workaround(void)
{
#if defined(FEAT_DIRECTX)
    if (enc_utf8 && IS_ENABLE_DIRECTX())
    {
        TEXTMETRIC tm;

        GetTextMetrics(s_hdc, &tm);
        if (tm.tmPitchAndFamily & (TMPF_TRUETYPE | TMPF_VECTOR))
            return;
    }
#endif
    GetPixel(s_hdc, FILL_X(gui.col), FILL_Y(gui.row));
}
```

**Comment by ynkdir** [comment]
問題があるとかでなければチェックしなくてもいいかなと思いますが。お好きなほうで。

**Comment by k-takata** [comment]
GetTextMetrics() と GetPixel() の処理時間がどのくらいか分かりませんが、フォントまで調べる必要は無いのではないかという気がします。

**Comment by mattn** [comment]
GetPixel は何かを変更するAPIでもないし、GetTextMetricsの方が明らかに計算量が多いので、encとdirectx だけ避けておけばいいと思います。

**Comment by yoheie** [comment]
全部の条件が揃ったときだけ return したいので、フォントのチェックだけ除くというわけにはいかないかと。
directx 有効の場合のチェックは抜きにして、 gist に上げた当初のパッチで vim_dev に提出します。

**Comment by k-takata** [comment]
リンク
https://groups.google.com/d/topic/vim_dev/NpTfb5c1Rc0/discussion
@yoheie ++

**Comment by ynkdir** [comment]
:+1:

**Comment by mattn** [comment]
パッチもすっきりで良いですね。

**Comment by yoheie** [comment]
7.4.869 で取り込まれました。
https://github.com/vim/vim/commit/3b59755862f4604ded8155404a1fe4c84c606829
皆さんどうもありがとうございました。
特に @ynkdir さんには、色々と調べていただきとても助かりました。

**Comment by h-east** [comment]
@yoheie :+1: お疲れ様でした。

**Comment by ynkdir** [comment]
:tada:

**Comment by todashuta** [comment]
:congratulations:
