### ISSUE TITLE
'breakindent'オプションを使用時に長い行でカーソルの位置がずれる

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#716]
およそタイトルの通りですが、`breakindent`オプションをオンにしてウィンドウに表示可能な文字量よりも長い行を表示させた際にカーソルがずれます。表示が絡むのでうまくいくかわかりませんが、私の環境では次のスクリプトを読み込むことで再現します。

``` vim
set wrap
set breakindent
set breakindentopt=shift:4

split
vsplit
resize 3
vertical resize 25

normal! 67ia
startinsert!
```

実行するとカーソルのあるウィンドウが67文字のaでちょうど埋まるだけのはずなのですが、実際にはカーソルは行末を越えて次の行へ移っています。さらに何文字か打ち込んでみてもらえると、カーソルの表示位置と編集位置がずれているのがわかりやすいかと思います。どうも、`breakindentopt`の`shift`の値だけずれているように思います。

**Comment by mattn** [comment]
キャプチャを貰ってもいいですか

**Comment by machakann** [comment]
キャプチャとりました。上のスクリプトを実行後にわかりやすいように`:set list`しました。~~右上~~左上のウィンドウにカーソルがあるのですが、カーソルが行末を越えています。
![bug_cursor](https://cloud.githubusercontent.com/assets/480049/6751031/f75e4ec0-cf3a-11e4-82cf-95967b422d2c.png)
書き忘れていましたがWindows 7上のgvim 7.4.648 32bitです。

**Comment by machakann** [comment]
すいません、コメントを修正しました。

**Comment by mattn** [comment]
ありがとうございます。こちらでも再現しました。

![](http://go-gyazo.appspot.com/dc912dda1bb6e005.png)

**Comment by mattn** [comment]
何か所か文字を変えてみました。

挿入モード前
![](http://go-gyazo.appspot.com/573af85f3a628b0f.png)

挿入モード後
![](http://go-gyazo.appspot.com/5c7a60a3372fd74c.png)

**Comment by machakann** [comment]
まさにそんな感じです。
ノーマルモードに戻った後も4文字分行末を越えて動けますけど、いったん`0`コマンドで行頭に戻った後はまたインサートモードに入るまで行末を越えなくなりますね。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/40f92fa0dfc81685d504
- ウインドウ先頭でも継続行の場合は shift を入れる

挿入モード後

original:

```
aaaaaaaaaaaaaaaaaaaaaaaaa
____aaaaaaaaaaaaaaaaa
____|
```

patched:

```
____aaaaaaaaaaaaaaaaaaaaa
____aaaaaaaaaaaaaaaaaaaaa
____|
```

`|`: カーソル位置

**Comment by machakann** [comment]
ありがとうございます！@ichizok さんのパッチで症状が改善しました、パッチ後の表示も妥当だと思います。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/tzNKP7EDWYI
報告しました。

**Comment by ichizok** [comment]
8.0.0090
https://github.com/vim/vim/commit/6c896867c4f5d759616028ef7cbfce2a9ed32600

Christian Brabandt 氏の patch で修正されました。
https://groups.google.com/forum/#!topic/vim_dev/gsCnTUrkCXc
