### ISSUE TITLE
exコマンド :qflistdo と :loclistdo の追加

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#717]
https://twitter.com/h_east/status/578808297978888192

> # vim :argdo みたいな感じで :qflistdo と :loclistdo があるといい感じじゃね？

https://twitter.com/kaoriya/status/578815474244308992

> @h_east +1.  please add it as issue.

ということでIssue立てました。

```
:qflistdo[!] {cmd}                 quickfixリスト内の全てのファイルで {cmd} を実行する。

:loclistdo[!] {cmd}                locationリスト内の全てのファイルで {cmd} を実行する。
```

コマンド名は既存のやつが `c～` `l～` で統一されているので、 `clistdo` `llistdo` が良いかも？

**Comment by k-takata** [comment]
Patch to add the :cdo and :ldo commands
https://groups.google.com/d/topic/vim_dev/dfyt-G6SMec/discussion
もしかして、これがまさにそれですか。

**Comment by h-east** [comment]
@k-takata Oh! まさにそれです。Thanks.
しかもつい数時間前にpatch更新されてますね。

**Comment by h-east** [comment]
あのpatch、`:cdo`と`:cfdo` (と`:ldo`と`lfdo`)足してるけど`:cdo`って要る？
他のdoと同じバッファ(ファイル)単位のやつだけで良いと思うんです。

```
okome ken
kome kome club
```

という内容のkome.txtというファイルをVimで開いて、

``` vim
:grep kome %
```

でgrepしたら(grepprgは"grep -rnIH")、`quicfix window`は

```
kome.txt|1| okome ken
kome.txt|2| kome kome club
```

となるけど、`kome`は実際には3つあるわけで。。(`:cnext`でも一緒だけどこっちはｗｉｎｄｏｗに表示される)
あと `{cmd}`の内容によっては検索時の行&カラム位置に該当物がない場合もあるわけで。
だからあんまり使い道無い気がする。

なので`:cdo`をなくして`:cfdo`を`:cdo`(か`:clistdo`)にした方がいいと思う。

**Comment by h-east** [comment]
Patch 7.4.858 
Problem:    It's a bit clumsy to execute a command on a list of matches. 
Solution:   Add the ":ldo", ":lfdo", ":cdo" and ":cfdo" commands. (Yegappan 
            Lakshmanan) 
https://groups.google.com/d/topic/vim_dev/AEu69ovGCmE/discussion
