### ISSUE TITLE
通常操作で cursorline の残像が残る

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#719]
```
:set cursorline
```

```
O<ESC>O<ESC>O<ESC>O<ESC>
```

![](http://go-gyazo.appspot.com/d481166ff92b22ea.png)

**Comment by mattn** [comment]
ちょっと雑な気もしなくないけど

``` diff
diff -r 88b829656499 src/normal.c
--- a/src/normal.c  Tue Mar 24 18:22:42 2015 +0100
+++ b/src/normal.c  Wed Mar 25 08:35:23 2015 +0900
@@ -8483,6 +8483,8 @@
        /* When '#' is in 'cpoptions' ignore the count. */
        if (vim_strchr(p_cpo, CPO_HASH) != NULL)
        cap->count1 = 1;
+       if (curwin->w_p_cul)
+       redraw_later(NOT_VALID);
        invoke_edit(cap, FALSE, cap->cmdchar, TRUE);
    }
     }
```

**Comment by h-east** [comment]
Vim 7.4.682 (Huge) on GNOME term on Ubuntu 12.04  ~~で再現しなかったです。~~

**Comment by mattn** [comment]
推測ですが linux 端末の場合は scroll region を設定の上で領域をシフトしているので数行上の update_single_line が実行されて行が書き変わるのですが、Windows や GUI の場合は対象行を自前で書き換えてる(書き換えないといけない)と思うのでこの現象になってるのかと思います。
ちなみに vim.exe gvim.exe 両方で発生しました。

**Comment by todashuta** [comment]
Vim 7.4.648 (MacVim Kaoriya) on iTerm2 で再現しました。同じMacVimのGUIでも再現しています。

**Comment by h-east** [comment]
あっ、こちらでも再現しました。
`O`じゃなくて`o`でやってました。すいませんすいません。

**Comment by saitoha** [comment]
縦分割してみました。
:set cursorline<CR>:vsp<CR>O<ESC>O

![2015-03-26 0 02 47](https://cloud.githubusercontent.com/assets/1162739/6827567/83698d8a-d34b-11e4-8143-edc4ae283d6c.png)

**Comment by mattn** [comment]
って事は端末依存の不具合ではないという事ですね。

**Comment by mattn** [comment]
報告
https://groups.google.com/forum/#!topic/vim_dev/TpU11u7SqWo

**Comment by mattn** [comment]
Patch 7.4.732
https://groups.google.com/forum/#!topic/vim_dev/X-alH82Bdzw

**Comment by crazymaster** [comment]
tinyでコンパイルエラー
https://travis-ci.org/vim-jp/vim-ci/jobs/66086337#L650

```
normal.c:8496:18: error: no member named 'w_p_cul' in 'struct window_S'
            if (curwin->w_p_cul)
                ~~~~~~  ^
```

**Comment by h-east** [comment]
@crazymaster Nice.

``` diff
diff -r 7a8dcf699b22 src/normal.c
--- a/src/normal.c  Tue Jun 09 21:33:31 2015 +0200
+++ b/src/normal.c  Wed Jun 10 16:07:28 2015 +0900
@@ -8487,9 +8487,11 @@
        /* When '#' is in 'cpoptions' ignore the count. */
        if (vim_strchr(p_cpo, CPO_HASH) != NULL)
        cap->count1 = 1;
+#ifdef FEAT_SYN_HL
        if (curwin->w_p_cul)
        /* force redraw of cursorline */
        curwin->w_valid &= ~VALID_CROW;
+#endif
        invoke_edit(cap, FALSE, cap->cmdchar, TRUE);
    }
     }
```

今からvim_devに投げる。

**Comment by h-east** [comment]
> 今からvim_devに投げる。

Done.
https://groups.google.com/d/msg/vim_dev/X-alH82Bdzw/EaNvJRzvk8gJ

**Comment by crazymaster** [comment]
Patch 7.4.738
https://groups.google.com/d/msg/vim_dev/60sLY7cIkJU/Y1uCkcxfB3MJ

**Comment by todashuta** [comment]
:+1:
