### ISSUE TITLE
autoload関数の補完結果がおかしい

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#72]
これはみなさんも周知の事実だと思いますが、autoload関数をコマンドラインで補完させると結果がおかしいです。

:call neo<Tab>

neocomplcache#……系の関数が現れる。

:call neocomplcache#au<Tab>

なぜか、neocomplcache#の部分が無視され、auから始まる普通の関数が候補となる。

~~ちなみに、:letの補完は大丈夫でした。~~→やはりだめでした。

**Comment by mattn** [comment]
letも駄目な気がする

**Comment by Shougo** [comment]
あれ、軽くやってみた感じでは大丈夫でしたけど……。

**Comment by mattn** [comment]
`vim -u NONE -N`で

```
let foo#bar = 1
```

としたあと

   let foo#b

で補完すると

```
let foo#b:changedtick
```

と出ます。どんな確認してます？

**Comment by Shougo** [comment]
あ、確かにletもおかしいです……。

**Comment by ynkdir** [comment]
todoにあります。

```
todo.txt:
If the variable "g:x#y#z" exists completion after ":echo g:x#" doesn't work.
```

**Comment by tyru** [comment]
numbered functionとか補完候補から消したいですね
`neocomplcache#<Tab>` -> `neocomplcache#1(`

**Comment by mattn** [comment]
@tyru #71 で消えます

**Comment by tyru** [comment]
おおう、#71見てなかったです。情報ありがとうございます。
Private Feedは爆発してるのでvim-jp/issues/issuesのフィードを別に取得したい...

**Comment by Shougo** [comment]
ふむふむ。todoにはあるんですね。ということは、誰かが実装をしてしまえば……。

**Comment by mattn** [comment]
autoload変数はまだ読んでない場合、読むかどうかの議論もありそう。

**Comment by Shougo** [comment]
ふむ。確かにそれはあるかも。読まないと言うことでも良さそうですが……。

**Comment by mattn** [comment]
これ今試すと直ってる様ですが、どうでしょうか。

**Comment by Shougo** [comment]
直っていることを確認しました。
Vim 8.0.844 です。
