### ISSUE TITLE
vimdiffを提供する良い方法

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#723]
vimdiffをバンドルしてくれというリクエストが(英語で)来てました。

> Just one request. If you could kindly include gvimdiff and vimdiff as well, it will be great.

vimdiff それ自身は vim からのリネームに過ぎませんが、
実際に機能させるには ed スタイルの diff を生成するプログラムが必要です。
とはいえそのためにcygwinやmsys/mingwをインストールさせるのも
あまりに大げさかなと。

そこで [ynkdir/vim-diff](https://github.com/ynkdir/vim-diff) をバンドルすることを思いつきました。
vim-diff をバンドルして起動時に diff.exe が見つからなかったら自動的に diffexpr を設定する
というアイデアです。

なにかこうしたら良いとか、アドバイスがあったらお願いします。

**Comment by h-east** [comment]
私はdiff.exeは[DiffUtils for Windows](http://gnuwin32.sourceforge.net/packages/diffutils.htm)のを使ってます。

もしかしてその外国人さん、vimの`-d`オプションを知らないとか、`:vert diffsplit`を知らないとかはないですよね？

**Comment by crazymaster** [comment]
> [DiffUtils for Windows](http://gnuwin32.sourceforge.net/packages/diffutils.htm)

バージョンが古いんですよねえ

**Comment by h-east** [comment]
@crazymaster あっ、ほんとだ。上記サイトで配布してるの 2.8.7 だけど最新は 3.3 ですね。

**Comment by koron** [comment]
> Yes, I am using gnu utils for windows. I have infact installed them in the same directory as vim and done some additions to the paths so that vimdiff will use the gnu diff.

ってそのあとのメールで言ってました。

単に diff.exe (を別に入れるの面倒だから) 一緒に入ってたら、もっと便利なんじゃないか
っていう suggestion だと捉えています。

なので MSVC でコンパイル(できるならば)した diff.exe を入れるか vim-diff かくらいが良いのかなぁ、と。

**Comment by h-east** [comment]
@koron 理解しました。そして全部同意:+1:
vim-diffは使ったことないのですけど、処理速度はdiff.exeと比べてどうなんでしょう。
そこまで違いがなければvim-diffでいいかも。

**Comment by koron** [comment]
以前試した時は、小さなファイルだと気にならない & 大きなファイルだと、うーんみたいな
予想の範囲だとは思います。

diff.exe を入れる場合は場合は…やっぱMSVCランタイム使いたいですよね。

**Comment by koron** [comment]
…vim-diffからC89レベルに再移植するって考え方もあるかw

**Comment by h-east** [comment]
ちょっとだけ関係ありそうなのでリンク貼っておく。

How to force Vim to use more advance diff between two files?
https://groups.google.com/d/msg/vim_use/oeHABkm94hM/Wk9ohW2XAGoJ

**Comment by k-takata** [comment]
Bramが、外部プログラムを使わないようにできれば最善だろうと。
https://groups.google.com/d/msg/vim_dev/dAXpcpHmVw4/5WUM6Y6gAQAJ

> BTW: If someone wants to spend time on this, the best solution would be
> not to use an external diff program.  Writing the temp files, invoking
> diff and parsing the result has a lot of overhead. 

で、それに対して、やってみたいという人が。
https://groups.google.com/d/msg/vim_dev/dAXpcpHmVw4/YRTt1h0sBAAJ

**Comment by mattn** [comment]
関連?

https://groups.google.com/forum/#!topic/vim_dev/kKqMdCGLfhg

**Comment by h-east** [comment]
@mattn なんで急にAppVeyorがエラーになったんでしょうか？

**Comment by mattn** [comment]
わかんないんです。一瞬

https://groups.google.com/forum/#!topic/vim_dev/bZwZ_PD263U

これでテスト足された物の中に失敗する in/out/ok がいるのかな？と思ったんですが(これまで失敗してなかった
だけ？)、そうでもなさそうですしね。

**Comment by h-east** [comment]
@mattn 発端のpatch(7.4.1554)が自分が書いたpatchだったので焦りました。特にtrickyな変更を入れたつもりは無かったので(汗)

**Comment by k-takata** [comment]
AppVeyorのビルドイメージの更新があったようで、その際にデグレしたように思われます。すでに直ったようですが。

**Comment by k-takata** [comment]
ちなみに、AppVeyorでは（確か）少なくとも4つ、diff.exeが入っています。
- Git for Windows 同梱
- Cygwin
- MSYS2
- MSYS

で、Git for Windowsの`C:\Program Files\Git\usr\bin\` がPATHに入っています。

**Comment by k-takata** [comment]
@koron closable?

**Comment by koron** [comment]
yes, thank you 🙇

**Comment by koron** [comment]
+kaoriya版では diff.exe を添付することで対応しました。
