### ISSUE TITLE
リストの map() が極端に遅くなる

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#724]
リスト内の値を操作するのに map() や filter() を愛用しているのですが、
一つ一つ操作する方法と map() で操作する方法の
次のサンプルを WIndows 7 で比較したところ、
Kaoriya の 7.4.648
0.091604
0.279884
https://tuxproject.de/projects/vim/ の 7.4.691
0.097171
0.014423
となり、Kaoriya の map() が 20 倍ほど遅いようなのですが、
何か使い方を間違っていますでしょうか?

``` viml
let n = 10000
let l = []
for i in range(n) | let l += [localtime() % 10] | endfor

let t = reltime()
        for i in range(len(l)) | let l[i] += 1 | endfor
echo reltimestr(reltime(t))

let t = reltime()
        call map(l, 'v:val + 1') 
echo reltimestr(reltime(t))
```

**Comment by koron** [comment]
私の手元でも確認できました。

使い方は間違ってないです。
なんで遅い&速いかは現時点では不明です。

**Comment by koron** [comment]
+kaoriya パッチ無しでも、私のところでコンパイルしたのは同じような速度。

**Comment by koron** [comment]
テストに使っているのはコレ。

https://gist.github.com/koron/b61af22ed359f56aee00

```
vim -u NONE --noplugin -c "so bench-724.vim"
```

こんな感じで実行してます。

**Comment by koron** [comment]
とりあえず vs10 と vs12 でコンパイルしたけど

```
0.020095
0.159023
```

と、ほぼ変わらない感じ。ループで回すのに対し、mapのほうが8倍くらい遅い。
対して tuxproject の vim.exe ([DL](https://tuxproject.de/projects/vim/x64/vim.exe)) は

```
0.022933
0.002955
```

と、逆転してmapのほうが8倍くらい速い。ちょっと極端過ぎる。

**Comment by koron** [comment]
`tv_check_lock()` を使ってる [この2行(開くのにちょっと時間がかかるので要注意)](https://github.com/vim-jp/vim/blob/v7-4-691/src/eval.c#L10873-L10874) を無効化したら

```
0.020636
0.002904
```

ほぼ同じくらい速くなった…なんでや? なんかキャッシュとかあふれるんか?

なお `tv_check_lock()` の中身を無効化して、
常にFALSEを返すようにした場合には遅いまま。
関数呼び出しによってL1とかのキャッシュから外れちゃうのかな?

**Comment by koron** [comment]
とりあえず私の調査はココまで。 

わかっていること
-    vs10, vs12 は遅くなる(=その他の環境では試してない)
-    +kaoriya パッチの有無は関係ない(=未パッチ状態でも発生する)
-    `tv_check_lock()` の呼び出しを止めると速くなる
-    同じループ内の`filter_map_one()` の呼び出しを止めても(もちろんmapは正しく機能しなくなる)速くならない
-    `tv_check_lock()` 内の動作を簡略化しても速くならない

以上。だれか続き頼む。

**Comment by h-east** [comment]
あんまり参考にならないかもしれないけどLinuxでの結果を載せときます。
CPU: ~~AMD Athlon II N330 2.3GHz~~ Intel Core2 Duo E4500 2.2GHz
memory: ~~8GB~~ 1GB
OS: fedora 20 (64bit)
Vim: 7.4.648 / 7.4.692

``` bash
$ hg update -r v7-4-648   # 最新(7.4.692)の場合は hg update
$ make distclean
$ ./configure --with-features=huge --enable-fail-if-missing
$ make
$ src/vim -N -u NONE -c "so ~/bench-724.vim"
```

VimのVersionに関係なく以下のような傾向でした。(map()の方が6倍近く速い←tuxproject版と同様の傾向)
  0.038964
  0.006526

# 

@koron 念のため検証したVimのVerを教えて下さい。

**Comment by mattn** [comment]
kaoriya は非依存って事でいいですか？

**Comment by koron** [comment]
@h-east
tuxと(偶然)同じ 7.4.691 です。

@mattn
Yes 私が観測する限りは +kaoriya パッチ有無とは関係ありませんでした。

**Comment by uakms** [comment]
Vim 7.4.692 での結果です。

OSX Core i7 llvm 3.5svn
./configure; make
  0.029063
  0.003997

OSX PowerPC gcc 3.3
./configure; make
  0.308756
  0.156226

WinXP PentiumM MinGW gcc 4.8.1
mingw32-make -f Make_ming.mak GUI=no
  0.084031
  0.006250

WinXP PentiumM VisualStudioExpress2008
msvc2008.bat; nmake -f Make_mvc.mak GUI=no
  0.058790
  0.006993

普通の結果でした。

**Comment by koron** [comment]
ppcの結果が少し気になりますね。

あと698のパッチ、少し関係しそう。

**Comment by koron** [comment]
> あと698のパッチ、少し関係しそう。

薄々わかってたんだけど `map` では関係無かった。`filter` は速くなりそう。

```
0.020603
0.172032
```

**Comment by ynkdir** [comment]
gettext 関係?

```
        if (tv_check_lock(li->li_tv.v_lock, (char_u *)_(arg_errmsg)))
            break;
```

**Comment by ynkdir** [comment]
あーですね。intl.dll をリネームして読み込まないようにしたら速くなりました。

**Comment by mattn** [comment]
それかーw
僕は普段 intl 使ってないんで、なんか皆と速度ちがうなーと思ってました。

On 4/14/15, Yukihiro Nakadaira notifications@github.com wrote:

> あーですね。intl.dll をリネームして読み込まないようにしたら速くなりました。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/724#issuecomment-92817988

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
変動しないなら予め取得しておけますね。それよりこれ関連、他にも結構ありそうな気がしますね。

On 4/14/15, Yukihiro Nakadaira notifications@github.com wrote:

> gettext 関係?
> 
> ```
>       if (tv_check_lock(li->li_tv.v_lock, (char_u *)_(arg_errmsg)))
>           break;
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/724#issuecomment-92816946

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
tv_check_lock を軽くみただけでも

```
eval.c:8922:        && !tv_check_lock(l->lv_lock, (char_u *)_("add() argument"))
eval.c:10545:   if (l1 != NULL && !tv_check_lock(l1->lv_lock, (char_u *)_(arg_errmsg))
eval.c:10581:   if (d1 != NULL && !tv_check_lock(d1->dv_lock, (char_u *)_(arg_errmsg))
eval.c:10808:       || tv_check_lock(l->lv_lock, (char_u *)_(arg_errmsg)))
eval.c:10814:       || tv_check_lock(d->dv_lock, (char_u *)_(arg_errmsg)))
eval.c:10873:       if (tv_check_lock(li->li_tv.v_lock, (char_u *)_(arg_errmsg)))
eval.c:13726:       && !tv_check_lock(l->lv_lock, (char_u *)_("insert() argument")))
eval.c:15814:       && !tv_check_lock(d->dv_lock, (char_u *)_(arg_errmsg)))
eval.c:15834:       && !tv_check_lock(l->lv_lock, (char_u *)_(arg_errmsg)))
eval.c:16178:       && !tv_check_lock(l->lv_lock, (char_u *)_("reverse() argument")))
```

**Comment by uakms** [comment]
iBook(PowerPC) だけ +gettext になってました。

**Comment by mattn** [comment]
意図的にギリギリまで `_(x)` しない作りが逆効果だったようですね。eval.c だけ `_(x)` をループ内使用している箇所を見ました。関数またぎは見ていません。

``` diff
diff -r a0651f2537f5 src/eval.c
--- a/src/eval.c    Mon Apr 13 20:52:37 2015 +0200
+++ b/src/eval.c    Tue Apr 14 23:48:36 2015 +0900
@@ -10497,7 +10497,7 @@
     dictitem_T *di1;
     hashitem_T *hi2;
     int        todo;
-    char   *arg_errmsg = N_("extend() argument");
+    char_u *arg_errmsg = _("extend() argument");

     todo = (int)d2->dv_hashtab.ht_used;
     for (hi2 = d2->dv_hashtab.ht_array; todo > 0; ++hi2)
@@ -10532,8 +10532,8 @@
        }
        else if (*action == 'f' && HI2DI(hi2) != di1)
        {
-       if (tv_check_lock(di1->di_tv.v_lock, (char_u *)_(arg_errmsg))
-             || var_check_ro(di1->di_flags, (char_u *)_(arg_errmsg)))
+       if (tv_check_lock(di1->di_tv.v_lock, arg_errmsg)
+             || var_check_ro(di1->di_flags, arg_errmsg))
            break;
        clear_tv(&di1->di_tv);
        copy_tv(&HI2DI(hi2)->di_tv, &di1->di_tv);
@@ -10817,21 +10817,21 @@
     int        rem;
     int        todo;
     char_u *ermsg = (char_u *)(map ? "map()" : "filter()");
-    char   *arg_errmsg = (map ? N_("map() argument")
-                  : N_("filter() argument"));
+    char_u *arg_errmsg = (map ? _("map() argument")
+                  : _("filter() argument"));
     int        save_did_emsg;
     int        idx = 0;

     if (argvars[0].v_type == VAR_LIST)
     {
    if ((l = argvars[0].vval.v_list) == NULL
-         || (!map && tv_check_lock(l->lv_lock, (char_u *)_(arg_errmsg))))
+         || (!map && tv_check_lock(l->lv_lock, arg_errmsg)))
        return;
     }
     else if (argvars[0].v_type == VAR_DICT)
     {
    if ((d = argvars[0].vval.v_dict) == NULL
-         || (!map && tv_check_lock(d->dv_lock, (char_u *)_(arg_errmsg))))
+         || (!map && tv_check_lock(d->dv_lock, arg_errmsg)))
        return;
     }
     else
@@ -10871,10 +10871,8 @@
            --todo;
            di = HI2DI(hi);
            if (map &&
-               (tv_check_lock(di->di_tv.v_lock,
-                            (char_u *)_(arg_errmsg))
-               || var_check_ro(di->di_flags,
-                            (char_u *)_(arg_errmsg))))
+               (tv_check_lock(di->di_tv.v_lock, arg_errmsg)
+               || var_check_ro(di->di_flags, arg_errmsg)))
            break;
            vimvars[VV_KEY].vv_str = vim_strsave(di->di_key);
            r = filter_map_one(&di->di_tv, expr, map, &rem);
@@ -10883,10 +10881,8 @@
            break;
            if (!map && rem)
            {
-           if (var_check_fixed(di->di_flags,
-                            (char_u *)_(arg_errmsg))
-               || var_check_ro(di->di_flags,
-                            (char_u *)_(arg_errmsg)))
+           if (var_check_fixed(di->di_flags, arg_errmsg)
+               || var_check_ro(di->di_flags, arg_errmsg))
                break;
            dictitem_remove(d, di);
            }
@@ -10900,8 +10896,7 @@

        for (li = l->lv_first; li != NULL; li = nli)
        {
-       if (map && tv_check_lock(li->li_tv.v_lock,
-                            (char_u *)_(arg_errmsg)))
+       if (map && tv_check_lock(li->li_tv.v_lock, arg_errmsg))
            break;
        nli = li->li_next;
        vimvars[VV_KEY].vv_nr = idx;
```

**Comment by mattn** [comment]
このパッチだけで速度が 2/3 になった。
前

```
0.032272
0.007035
```

後

```
0.034316
0.004772
```

**Comment by koron** [comment]
@ynkdir :+1: & :bow:

**Comment by koron** [comment]
@mattn +gettext 使ってないのにも関わらず、パッチをあてると速くなったってことですかw

**Comment by mattn** [comment]
いや、速度アップは linux で確認しました。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/zE52NTjFCbQ

**Comment by ynkdir** [comment]
:+1:

**Comment by h-east** [comment]
Patch 7.4.708
https://groups.google.com/d/msg/vim_dev/Qj1Mj-XeF_E/4gpV4GIxVbgJ

tv_check_lock()その他3関数に`use_gettext`引数を追加して制御する形になりました。

**Comment by koron** [comment]
:+1:
