### ISSUE TITLE
round() の第二引数に桁が欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#726]
http://hail2u.net/blog/software/vim-round-and-replace-decimal.html

> round()
> 小数の丸めには3種類あるが、四捨五入したい場合はround()を使う。しかしこれは強制的に整数へ(.0付きで)丸められるため、事前に維持したい桁数だけ少数点をずらしておく必要がある。ここでは3桁維持するとして、まず1000を掛けておき、round()した後に1000で割って戻す。

第二引数に桁を指定出来る物が欲しい。

**Comment by mattn** [comment]
https://gist.github.com/mattn/8591d5316b990fc4d7d5

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/5SQvfby_nCY

**Comment by ujihisa** [comment]
vital.vimには導入されました、これで古いvimでも安心です https://github.com/vim-jp/vital.vim/pull/297

**Comment by crazymaster** [comment]
todoリスト入り
https://github.com/vim-jp/vim/commit/0031847675d61157ebf9907d077a90ac60d5011c#diff-38d7929bd26d74d92ceddf984bbfc8dbR291

> Patch to add digits argument to round(). (Yasuhiro Matsumoto, 2015 Apr 26)
