### ISSUE TITLE
Vim 7.4.711でtest_listcharsがFAILする。

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#727]
7.4.710で`listchars`オプションに`space`が追加されたんだけど、`:set list`は対応しているけど`:list`の対応が漏れている。
でも`test_listchars`はどっちのテストもやっているのでFAILになっている。正当なFAIL。

対策： `space`を`:list`にも対応させる。

**Comment by h-east** [comment]
``` diff
diff -r 3790fb70e04c src/message.c
--- a/src/message.c Tue Apr 21 19:10:49 2015 +0200
+++ b/src/message.c Wed Apr 22 12:16:42 2015 +0900
@@ -1737,6 +1737,11 @@
        c = lcs_nbsp;
        attr = hl_attr(HLF_8);
        }
+       else if (c == ' ' && list && lcs_space != NUL)
+       {
+       c = lcs_space;
+       attr = hl_attr(HLF_8);
+       }
        else if (c == NUL && list && lcs_eol != NUL)
        {
        p_extra = (char_u *)"";
```

**Comment by h-east** [comment]
あー、`lcs_trail`の方を優先させないといけないな。
これでtest ALL DONE！

``` diff
diff -r 3790fb70e04c src/message.c
--- a/src/message.c Tue Apr 21 19:10:49 2015 +0200
+++ b/src/message.c Wed Apr 22 12:29:28 2015 +0900
@@ -1761,6 +1761,11 @@
        c = lcs_trail;
        attr = hl_attr(HLF_8);
        }
+       else if (c == ' ' && list && lcs_space != NUL)
+       {
+       c = lcs_space;
+       attr = hl_attr(HLF_8);
+       }
    }

    if (c == NUL)
```

**Comment by k-takata** [comment]
[bug] test_listchars fails in vim-7.4.711
https://groups.google.com/d/topic/vim_dev/WVzx5j8mk00/discussion
報告は既に上がっています。(パッチはまだ)

**Comment by h-east** [comment]
vim_devに投げました。
https://groups.google.com/d/msg/vim_dev/qcgMUKuz_Jg/cVkIIV93riUJ

Dominiqueさんにも返信しときました:+1:

**Comment by k-takata** [comment]
:+1:

**Comment by h-east** [comment]
Patch 7.4.712
https://groups.google.com/d/msg/vim_dev/9eO5_Drx8nE/Pnr1dYoTDvUJ

私の書いたpatchと同じものがOｒiginal patchにはちゃんと含まれていて、Bram氏がcommitし忘れた模様。
https://code.google.com/p/vim/issues/detail?id=350

**Comment by crazymaster** [comment]
windowsでは7.4.712でもfailしているっぽい
https://ci.appveyor.com/project/k-takata/vim-ci/build/277

**Comment by h-east** [comment]
改行コードで差分が出てる感じですね。
(Linuxではtest ALL DONEでした)

**Comment by crazymaster** [comment]
Patch 7.4.733 で修正
https://groups.google.com/d/msg/vim_dev/EJup4hbdeY8/Tg-xNAPtiAUJ
