### ISSUE TITLE
Vim基本セットのjavascript環境をちょっといい感じにする

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#729]
出来る範囲で改善しましょう。

https://github.com/vim-jp/issues/issues/701#issuecomment-76518463

> 確認していて思ったんですが、javascript の cinkeys に 0] が欲しいですね。

現在 `$VIMRUNTIME/indent/javascript.vim` にはMaintainerいません。 

> " Maintainer: None!  Wanna improve this?

私は`javascript`はほぼ書かないので書いている人アドバイスお願いします。

# 「JSのプラギン別途まともなヤツあるよ」と言ったらシバ（略

**Comment by h-east** [comment]
indentはこんな感じ？

``` diff
diff --git a/runtime/indent/javascript.vim b/runtime/indent/javascript.vim
--- a/runtime/indent/javascript.vim
+++ b/runtime/indent/javascript.vim
@@ -12,5 +12,8 @@
 " C indenting is not too bad.
 setlocal cindent
 setlocal cinoptions+=j1,J1
+setlocal cinkeys&
+setlocal cinkeys-=0#
+setlocal cinkeys+=0]

 let b:undo_indent = "setl cin<"
```

**Comment by crazymaster** [comment]
> # 「JSのプラギン別途まともなヤツあるよ」と言ったらシバ（略

確かに検索したらたくさん見つかりますね。
そして最初に出てくるのがコレですか。
https://github.com/pangloss/vim-javascript

[Improved Javascript indenting and syntax for inclusion - Google グループ](https://groups.google.com/d/topic/vim_dev/EBDKCCBl7F0/discussion)
includeするように提案されていますが...

**Comment by koron** [comment]
だれかメンテナ立てて vim-jp に移管しちゃう? 

あと、もう cinkeys は書下しちゃったほうが良いんじゃないかな。

``` viml
setlocal cinkeys=0{,0},0),:,!^F,o,O,e,0]
```

みたいに。

**Comment by h-east** [comment]
@crazymaster 情報Thanks. たぶんAuthor本人がアプローチしないとBram氏は反応しないんじゃないですかね。

@koron $VIMRUNTIME/indent/README.txt に

> To trigger the indenting after typing a word like "endif", add the word to the
> 'cinkeys' option with "+=".

とあるので上書きはしない方がいいと思う。

**Comment by koron** [comment]
@h-east 

``` viml
setlocal cinkeys&
```

これが無いなら同意です。
しかし、ある(しかも`cin`1つに対して設定が3行にもわたってしまう) ならば
直接全部設定してしまったほうが、
「JSはこういう設定なんだぜ」
っていうのを、1行で明示できて、後のメンテ時にわかりやすくなると考えます。

**Comment by crazymaster** [comment]
> @crazymaster 情報Thanks. たぶんAuthor本人がアプローチしないとBram氏は反応しないんじゃないですかね。

あれ、投稿はauthor本人ではないですか？

**Comment by h-east** [comment]
@koron 最初は入れるつもりなかったけど、他のを見てみたらやってたんで入れました。
crazymasterさんがlinkしてるpangloss/vim-javascript はcinkeys= で上書きしてますね。

@crazymaster あ、本当だ。ごめん。テキトー斜め読みでこれですよ！？

**Comment by h-east** [comment]
スレッドストッパーh_eastです。

``` vim
setlocal cinkeys-=0#
setlocal cinkeys+=0]
```

を出してみて良い？

**Comment by h-east** [comment]
vim_devに投げました。
https://groups.google.com/d/msg/vim_dev/OXPA5QxOq_I/LhvubDnBQT8J

**Comment by h-east** [comment]
patch 7.4.733の前のcommitで取り込まれました。
https://github.com/vim-jp/vim/commit/0031847675d61157ebf9907d077a90ac60d5011c#diff-737260430acbe76222505f784f2fcba8

ファイルヘッダの`Maintainer`コメントが`None!  Wanna improve this?`から`Going to be Darrick Wiebe`に変わっています。
私の投稿がきっかけで https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim に置き換えられる流れになっていい感じです。

**Comment by crazymaster** [comment]
:+1:

**Comment by todashuta** [comment]
:+1:

**Comment by sgur** [comment]
:+1:
