### ISSUE TITLE
vim.exe を起動する際、起動前にコンソールに表示されたワイド文字が終了後に復元されない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#732]
![](http://go-gyazo.appspot.com/b0b74367ac3bc198.png)

vim.exe を起動して終了

![](http://go-gyazo.appspot.com/cd4bbe024a70d35c.png)

**Comment by k-takata** [comment]
os_win32.c の SaveConsoleBuffer, RestoreConsoleBuffer が Wide API を使っていないのが原因ですかね？

**Comment by mattn** [comment]
ですね。

**Comment by k-takata** [comment]
``` diff
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -2246,7 +2246,7 @@ SaveConsoleBuffer(
     */
    ReadRegion.Top = Y;
    ReadRegion.Bottom = Y + Y_incr - 1;
-   if (!ReadConsoleOutput(g_hConOut,   /* output handle */
+   if (!ReadConsoleOutputW(g_hConOut,  /* output handle */
        cb->Buffer,         /* our buffer */
        cb->BufferSize,         /* dimensions of our buffer */
        BufferCoord,            /* offset in our buffer */
@@ -2319,7 +2319,7 @@ RestoreConsoleBuffer(
    WriteRegion.Top = 0;
    WriteRegion.Right = cb->Info.dwSize.X - 1;
    WriteRegion.Bottom = cb->Info.dwSize.Y - 1;
-   if (!WriteConsoleOutput(g_hConOut,  /* output handle */
+   if (!WriteConsoleOutputW(g_hConOut, /* output handle */
        cb->Buffer,         /* our buffer */
        cb->BufferSize,         /* dimensions of our buffer */
        BufferCoord,            /* offset in our buffer */
```

Win9x... 何それ、おいしいの？

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/9fc53772a5b04197.png)

LGTM

**Comment by mattn** [comment]
メモリ確保量同じなんだしこれデフォでいいじゃんって気はしなくないです(独り言

**Comment by k-takata** [comment]
確か、7.4がWin9xをサポートする最後のバージョンということになってましたよね。
（実際には、公式バイナリはVC2008でコンパイルされているせいでWin9xでは動かないのですが。）
パッチをどうするかはお任せします。

**Comment by k-takata** [comment]
> 確か、7.4がWin9xをサポートする最後のバージョンということになってましたよね。

Bramの発言がようやく見つかりました。

[patch] Move base Windows support to WinXP
https://groups.google.com/d/msg/vim_dev/dZQo_Ux9jjo/6Y7a7m8sY4cJ

> So how about this: 7.4.000 will be released with MS-Windows binaries
> that still support the old systems.  Once it's out and it looks OK we
> drop support for older systems.  That way 7.4 is what needs to be used
> for old systems.  It includes a lot of bug fixes since the last binary
> release.  And then 7.4.001 and further can add stuff that is not
> possible when building for the older systems. 

これで確定したわけではなさそうですが。

**Comment by mattn** [comment]
引数同じだし、関数ポインタ用意して

``` c
pReadConsoleOutput = g_PlatformId == VER_PLATFORM_WIN32_NT ? ReadConsoleOutputW : ReadConsoleOutputA;
pWriteConsoleOutput = g_PlatformId == VER_PLATFORM_WIN32_NT ? WriteConsoleOutputW : WriteConsoleOutputA
```

ってのはどうでしょうか？

**Comment by mattn** [comment]
それとも 9x だと W がリンク出来ないんでしたっけ

**Comment by Shougo** [comment]
https://github.com/vim-jp/issues/issues/253#issuecomment-8591291

> Win9xも、W系のシンボルだけは用意されています。中身はエラーを返すだけになっていますが。

のようです。Windows9x ではワイド関数が実質使い物にならないと思います。

**Comment by mattn** [comment]
``` diff
diff -r 3790fb70e04c src/os_win32.c
--- a/src/os_win32.c    Tue Apr 21 19:10:49 2015 +0200
+++ b/src/os_win32.c    Mon May 25 12:37:33 2015 +0900
@@ -584,6 +584,11 @@
    SECURITY_INFORMATION, PSID *, PSID *, PACL *, PACL *,
    PSECURITY_DESCRIPTOR *);
 # endif
+typedef BOOL (*PRCOUTPUT)(HANDLE, PCHAR_INFO, COORD, COORD, PSMALL_RECT);
+typedef BOOL (*PWCOUTPUT)(HANDLE, CONST CHAR_INFO*, COORD, COORD, PSMALL_RECT);
+
+static PRCOUTPUT pReadConsoleOutput = ReadConsoleOutputA;
+static PWCOUTPUT pWriteConsoleOutput = WriteConsoleOutputA;

 static HANDLE advapi_lib = NULL;   /* Handle for ADVAPI library */
 static PSNSECINFO pSetNamedSecurityInfo;
@@ -708,7 +713,7 @@
     */
    if (g_PlatformId == VER_PLATFORM_WIN32_NT)
    {
-       HANDLE kernel32 = GetModuleHandle("kernel32");
+       HMODULE kernel32 = GetModuleHandle("kernel32");
        pSetHandleInformation = (PSETHANDLEINFORMATION)GetProcAddress(
                        kernel32, "SetHandleInformation");

@@ -2243,7 +2248,7 @@
     */
    ReadRegion.Top = Y;
    ReadRegion.Bottom = Y + Y_incr - 1;
-   if (!ReadConsoleOutput(g_hConOut,   /* output handle */
+   if (!pReadConsoleOutput(g_hConOut,  /* output handle */
        cb->Buffer,         /* our buffer */
        cb->BufferSize,         /* dimensions of our buffer */
        BufferCoord,            /* offset in our buffer */
@@ -2316,7 +2321,7 @@
    WriteRegion.Top = 0;
    WriteRegion.Right = cb->Info.dwSize.X - 1;
    WriteRegion.Bottom = cb->Info.dwSize.Y - 1;
-   if (!WriteConsoleOutput(g_hConOut,  /* output handle */
+   if (!pWriteConsoleOutput(g_hConOut, /* output handle */
        cb->Buffer,         /* our buffer */
        cb->BufferSize,         /* dimensions of our buffer */
        BufferCoord,            /* offset in our buffer */
@@ -2495,6 +2500,17 @@
    create_conin();
     g_hConOut = GetStdHandle(STD_OUTPUT_HANDLE);

+    if (g_PlatformId == VER_PLATFORM_WIN32_NT)
+    {
+   HMODULE kernel32 = GetModuleHandle("kernel32");
+   if (!(pReadConsoleOutput = GetProcAddress(kernel32,
+           "ReadConsoleOutputW")))
+       pReadConsoleOutput = ReadConsoleOutputA;
+   if (!(pWriteConsoleOutput = GetProcAddress(kernel32,
+           "WriteConsoleOutputW")))
+       pWriteConsoleOutput = WriteConsoleOutputA;
+    }
+
 #ifdef FEAT_RESTORE_ORIG_SCREEN
     /* Save the initial console buffer for later restoration */
     SaveConsoleBuffer(&g_cbOrig);
```

**Comment by k-takata** [comment]
> それとも 9x だと W がリンク出来ないんでしたっけ

いや、リンクできるので、それで問題ないはずです。
`ReadConsoleOutputW`の存在をチェックするやり方だと、Win9xでもW系を使おうとしてしまうので、逆に正しく動かないと思います。

**Comment by k-takata** [comment]
あー、`if (g_PlatformId == VER_PLATFORM_WIN32_NT)` してるから問題ないのか。

**Comment by mattn** [comment]
```
if (g_PlatformId == VER_PLATFORM_WIN32_NT)
```
Win9x ってこれパスするんですっけ

**Comment by k-takata** [comment]
> Win9x ってこれパスするんですっけ

しません。

**Comment by mattn** [comment]
弄ったところじゃない修正があるのであとで綺麗にします。

**Comment by mattn** [comment]
ちょこっと触ってみて今日中に出します。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/z4nmjdUT5yA

**Comment by mattn** [comment]
パッチを送った後気付いたんですが、これまずいすね。
今の処理がカラム数=文字幅という前提で作られていて、ワイド文字だと破綻してますね。なので落ちる。
ReadConsoleOutput だとしんどいので ReadConsoleCharacter/ReadConsoleAttribute を使った方が良さげ。

**Comment by k-takata** [comment]
> 今の処理がカラム数=文字幅という前提で作られていて、ワイド文字だと破綻してますね。なので落ちる。

コードのどの部分か分かりませんでした。あと、再現手順もあれば、…

**Comment by mattn** [comment]
**長くなりますがお付き合いください。**

まず再現方法ですが、スクロールバーがいっぱい出来るくらいバッファ行数を取って、そのスクロールバーが一番下にくるくらい改行を打ちます。
その後、nyagos 等でワイド文字をコンソール表示した後に vim を起動して終了。

原因ですが、ANSI API の場合は例えば「あ」という文字を ReadConsoleOutput で読み取ると、CHAR_INFO 2つにそれぞれ SJIS の先頭バイトと後続バイトが入ります。
ですがワイド文字 API の場合は「あ」が CHAR_INFO 1つにそのまま入ります。
ANSI 版だと横幅80のコンソールを読み取るのに CHAR_INFO が80個要ります。
しかしワイド文字版だと、表示されている内容により必要となる CHAR_INFO が変わってきます。

**(そろそろ ｱｯ ｱｯ してる頃かと思いますが、続けます)**

それでも一度に全部読み取って一気に書き戻せば行けるじゃん、と思われるかもしれませんが ReadConsoleOutput は一度に 12000 個しか読み取れないという制限があり、
vim ではこれを回避する為に分割して読み取っています。

しかし前述の様に CHAR_INFO の場所が ANSI 版と異なるので `cb->Buffer` のどの位置にさっき読み取った部分が入っているか分かりません。
上記の様にバッファが大きいと複数回に分けて読み取られるのですが、その際に差異が発生し少しずつずれてきます。

**(そろそろ ｱｯ ｱｯ してる頃かと思いますが、続けます)**

最終的にはまったく設定されていない CHAR_INFO が読み取られてしまい、時には表示が左右にずれたり、時にはクラッシュしたりします。

**Comment by koron** [comment]
_ｱｯｱｯ_

**Comment by k-takata** [comment]
ReadConsoleOutput/WriteConsoleOutput で **ｱｯ ｱｯ** するのはやめて、バッファ自体を切り替えた方がいいんじゃないですかね。ということで、実験パッチ。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/568ca62cb83ea711e13c75633894a259ea4d03d0/win32-create-screen-buffer.patch
今までとは逆に 'resotrescreen' がoffの時に、終了直前のvimの画面を元の画面にコピーするという処理が必要になってしまいましたが。

**Comment by mattn** [comment]
いいと思います。ただ僕は結構スクロールバックを取るのでその時にメモリが枯渇しなければいいなーという程度です。

**Comment by k-takata** [comment]
今までVimが自前でメモリを確保して画面を保存していた分をOSに任せるようになったので、Vim自身が確保する量は減りますし、まあ、トータルでは対して変わらないんじゃないですかね。（適当
今までCreateConsoleScreenBuffer()を使ってなかった理由って何かありますか？

**Comment by mattn** [comment]
telnet 越しに使えないとかですかね（適当

**Comment by k-takata** [comment]
パッチを整理。
CreateConsoleScreenBuffer()を使うようにするためのパッチと、古いコードを削除するためのパッチ。（一緒にしてしまうとdiffが見にくかったので。）

https://bitbucket.org/k_takata/vim-ktakata-mq/src/f32a21102cb8becb2304ec48919e12b34c19b52f/win32-create-screen-buffer.patch
https://bitbucket.org/k_takata/vim-ktakata-mq/src/f32a21102cb8becb2304ec48919e12b34c19b52f/win32-create-screen-buffer_remove-unused-part.patch

動作確認をお願いしたいです。

**Comment by mattn** [comment]
このパッチとは無関係ですが、telnetd 上で vim 動かなくなってますね。

**Comment by k-takata** [comment]
パッチファイル名を修正
https://bitbucket.org/k_takata/vim-ktakata-mq/src/35b1a87ec692b6e959c38e7bd6d81d577a13dc56/win32console-create-screen-buffer.patch
https://bitbucket.org/k_takata/vim-ktakata-mq/src/35b1a87ec692b6e959c38e7bd6d81d577a13dc56/win32console-create-screen-buffer_remove-unused-part.patch

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/z4nmjdUT5yA/IAc5fw3vBgAJ

**Comment by k-takata** [comment]
Bramより返事

> I'll await comments for a little while before including this patch.

ということで、動作確認された方はコメントをお願いします。

> I don't think we need to support Windows 95 and 98 anymore.  I don't
> have a computer anymore that runs it (and thus can't play some old
> games...).
> 
> Windows XP is also deprecated, but it's still used in many places.
> Thus Windows XP is the oldest we need to support.

Win9xは切り捨てて、サポートはXP以降にしようとのこと。

**Comment by k-takata** [comment]
CreateConsoleScreenBuffer/SetConsoleActiveScreenBuffer を使う前は、mintty上でwinptyを使うとそこそこ動いていたのですが(#703)、変更後は全く動かなくなってしまいました。
おそらくwinptyのエミュレーションが不完全ということで、winptyにがんばってもらう必要がありそうです。

**Comment by mattn** [comment]
あーそれだ。なんか思い出せないのがあるなーと思ってた。

**Comment by mattn** [comment]
`CONOUT$` を開けば Active Console Handle になるんだろうけどうまく sync 出来ないかもしれないですね > winpty

**Comment by mattn** [comment]
ただ winpty 呼び出されてる(もしくは他の何か)ってわかれば既存コード通すって手はありますね

**Comment by k-takata** [comment]
そこまでしてmintty上でWin32版vim.exeを動かしたい人がいるかな？という疑問。

**Comment by mattn** [comment]
mintty はよくわからないですが、昔 cygwin で native vim.exe を使おうとする人は結構見ましたね。どのくらいいるかは僕には分からないけど。

**Comment by k-takata** [comment]
たぶんTODO入り？ #681 と混じっているような気もしますが。

```
Patch to fix that wide characters do not work properly after exiting.
(Yasuhiro Matsumoto, 2015 May 24) Better patch to come.

Patch to support Unicode I/O in the MS-Windows console.
(Ken Takata, 2015 Aug 8)  Also by Yasuhiro Matsumoto.
```

**Comment by k-takata** [comment]
winpty上で CreateConsoleScreenBuffer/SetConsoleActiveScreenBuffer を使ったプログラムが動かない問題を報告。
https://github.com/rprichard/winpty/issues/34

**Comment by k-takata** [comment]
7.4.851
https://groups.google.com/d/topic/vim_dev/Gu7pDIjS1UE/discussion

**Comment by mattn** [comment]
@k-takata +++++++++++++++++

**Comment by nocd5** [comment]
Windows7 64bit Pro SP1 + KB2458000 の環境で
vim終了後にvim起動前のコンソールの表示内容が復元されなくなりました。
ただ、hotfix適用前に復元されていたか はきちんと確認しておらず
hotfix適用前後で発生したかは確信がもてません、すいません。

ぱっと思いついたところで
`CreateConsoleScreenBuffer`/`SetConsoleActiveScreenBuffer`を使ってる
mattnさんのlv for windowsを試したところ
こちらはコンソールの内容が復元されています。

不具合原因の切り分けがちゃんと出来ていないので
申し訳ありませんが、報告だけいたします。

**Comment by ynkdir** [comment]
同じ問題かどうかわかりませんが
Win10で
dir を実行したりしてコマンドプロンプトがスクロールするくらい出力がある状態で

```
vim -u NONE
:!hoge (終了コードがエラーになるコマンド)
:q
```

でプロンプトの位置が出力の中に復帰します。
こんな感じ

```
C:\Users\ynkdir\tmp\vim\src>261,643 edit.c
2015/09/07  18:30           581,459 eval.c
2015/09/07  18:30           193,109 ex_cmds.c
2015/09/07  17:43            53,109 ex_cmds.h
2015/09/07  18:30           102,630 ex_cmds2.c
2015/09/07  18:30           281,252 ex_docmd.c
```

:!hoge 実行時の表示位置はパッチ以前からおかしい感じです。

**Comment by ghost** [comment]
プロンプトの位置に関して、修正してみたので別 issue を立てます。
おそらく別の問題かと思われます。

**Comment by nocd5** [comment]
#766 と同じ問題でした。@ntakさんのパッチで直りました。

デバッグ用にif_luaを付けずにビルドしたにも関わらず
`-u NONE`を付けずに起動してしまっていて(不手際があり申し訳ありませんでした)
.vimrc読み込み時にエラーとなり
結果、ynkdirさんと同じ状態になっていたようです。

**Comment by Shougo** [comment]
@k-takata 今回の変更により、neocomplete から vimproc を用いて Vim を起動すると
呼び出した Vim がクラッシュするという報告を受けています。
vimproc に issue を作りますので対応をお願いします。

**Comment by k-takata** [comment]
Windowsのバグなのは明らかなわけですが、簡単に直りそうな見込みはないし、7.4.851はrevertした方がいいんじゃないかという気がしてきました。

**Comment by k-takata** [comment]
neocompleteで報告があったのはWin10ですか。Win10でも直ってないとなるとますます深刻ですが、 #764 でWin8.1ではクラッシュしないという話があってよくわからないですね。

**Comment by k-takata** [comment]
> winpty上で CreateConsoleScreenBuffer/SetConsoleActiveScreenBuffer を使ったプログラムが動かない問題を報告。
> rprichard/winpty#34

修正されたようです。

**Comment by mattn** [comment]
そんな手のこんだ修正が必要だったんかーw

**Comment by k-takata** [comment]
7.4.902
https://groups.google.com/d/topic/vim_dev/6bGV04XzMs0/discussion

> Revert patches 7.4.851, 7.4.876 and 7.4.886 until we find a better solution.

**Comment by k-takata** [comment]
> このパッチとは無関係ですが、telnetd 上で vim 動かなくなってますね。

関係大ありでした…
