### ISSUE TITLE
conceallevelを0以外にしていると、cmdwinからcmdlineに<C-c>で移るときに、cmdwin左端のcmdwin-charが消える

### ISSUE THREAD

**Issue by todashuta** [vim-jp/issues#733]
以下の手順では conceallevel=1 ですが 2や3 でも同じように発生します。

手順:

起動

```
$ vim -u NONE -i NONE -N +'set conceallevel=1'
```

操作

```
q:<C-c>
```

この操作でカーソルがコマンドラインウインドウからコマンドラインに移動しますが、同時に`<C-c>`以前にコマンドラインウインドウ上でカーソルがあった行の左端の`:`が消えてしまいます。`q/`や`q?`でも同様に`/`や`?`が消えます。

環境: MacVim-Kaoriya 7.4.712 on iTerm2

**Comment by h-east** [comment]
コマンドラインwindowでCtrl-Cを押した後の端末の入出力を @saitoha さん作の[trachet](https://github.com/saitoha/trachet)で見てみました。

conceallevel=1

```
<<<  <ETX>                    ETX / Ctrl-C
>>>   CSI ?25l                DECRST 25 - DECTCEM / hide cursor
>>>   CSI 0m                  SGR 0 / reset attributes
>>>   CSI 16;1H               CUP / move cursor to (row=16, col=1)
>>>   CSI K                   EL 0 / erase line: from the cursor through the end of the line
>>>   CSI 24;2H               CUP / move cursor to (row=24, col=2)
>>>   CSI ?25h                DECSET 25 - DECTCEM / show cursor
```

---

conceallevel=0

```
<<<  <ETX>                    ETX / Ctrl-C
>>>   CSI ?25l                DECRST 25 - DECTCEM / hide cursor
>>>   CSI 24;2H               CUP / move cursor to (row=24, col=2)
>>>   CSI ?25h                DECSET 25 - DECTCEM / show cursor
```

`conceallevel=1`の時はあきらかにカーソルをコマンドラインwindowの1行目の1桁目に移動して行eraseをおこなっていますね。

# 

これどうしたらいいんだろう。どっちかですかね？
1. コマンドラインwindow作成時に現バッファの`conceallevel`を引き継がないようにする。
2. コマンドラインwindowからfocus移動時に(`conceallevel`に関係なく)行eraseを端末に発行しないように抑制する。

ご意見お待ちしております。

**Comment by h-east** [comment]
あー、`conceallevel>0`かつコマンドラインwindowの場合は、`CSI 16;1H`じゃなくって`CSI 16;2H`にすればいいのか。

**Comment by h-east** [comment]
これで直った。他にもっとふさわしい修正方法がある気はするけど、このpatchは影響範囲が少なくて確実かなと思ってます。

``` diff
diff --git a/src/ex_getln.c b/src/ex_getln.c
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -6611,6 +6611,10 @@
    /* Don't execute autocommands while deleting the window. */
    block_autocmds();
 # endif
+# ifdef FEAT_CONCEAL
+   /* Avoid command-line window first character erasure. */
+   curwin->w_p_cole = 0;
+# endif
    wp = curwin;
    bp = curbuf;
    win_goto(old_curwin);
```

**Comment by todashuta** [comment]
@h-east 対応ありがとうございますm(_ _)m

**Comment by h-east** [comment]
vim_dev
https://groups.google.com/d/msg/vim_dev/k5bqzg7KS4M/Z8qdU_l-9voJ

**Comment by h-east** [comment]
@todashuta 
そういえば `$ vim -u NONE -i NONE -N +'set conceallevel=1'` の `+'set conceallevel=1'` って
`vim --help`にも載っていない気がするんですがどこ出典ですか？

**Comment by todashuta** [comment]
@h-east `:h -+c`ですです

**Comment by h-east** [comment]
@todashuta なるほど Thanks No problem!

**Comment by h-east** [comment]
Patch 7.4.758
https://groups.google.com/d/msg/vim_dev/gt2pLBNsQjw/fEiqHQ_JBXQJ

**Comment by todashuta** [comment]
@h-east :+1:
