### ISSUE TITLE
matchlist() が9個までしか返せない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#74]
これはそもそもVimの正規表現が`\(\)`によるキャプチャを9個までしか作れないのが問題で、
'\1' などは仕方ないにしても `matchlist()` は任意の数のマッチを返してくれると嬉しい。

**Comment by ynkdir** [comment]
関連してそうなのでとりあえず

[Patch] allow more than 10 capturing groups
http://thread.gmane.org/gmane.editors.vim.devel/29287/

```
todo.txt:
Patch to add up to 99 match groups. (Christian Brabandt, 2010 Dec 22)
Also add named groups: \%{name}(re)  and \%{name}g
```

**Comment by thinca** [comment]
これはすでにTODOリストに入ってたってことで閉じます。

**Comment by mattn** [comment]
閉じますと言っておられるので閉じます。

**Comment by thinca** [comment]
おりょ、閉じれてませんでしたか。さーせん&あざす。
