### ISSUE TITLE
07 インクリメント 010 ？

### ISSUE THREAD

**Issue by JuraCureMihawk** [vim-jp/issues#740]
1. 編集モードになって 07 を入力して、ノーマルモードに戻る。
2. 07 の上にカーソルを置いて、Ctrl-A。
3. 08 になるのを期待したが 010 となる。

[環境]
- Windows7 32bit
- gvim 7.4.648

**Comment by itchyny** [comment]
次コマンドを試してみてください。

``` vim
set nrformats-=octal
```

**Comment by koron** [comment]
詳しくは [ユーザーマニュアル 26.2 加算と減算](http://vim-jp.org/vimdoc-ja/usr_26.html#26.2) を参照してください。

**Comment by h-east** [comment]
直接関係ないけど...
@koron そのマニュアルの `八進数` に違和感があったので `8進数` に変更しました:cat2::dash:
https://github.com/vim-jp/vimdoc-ja/commit/b07eef4dd912fa884a90b708c926b47c3e276e1f#diff-81d7344922b1d3e3ba08f101674ecd55

数十分経てば反映されます。

**Comment by JuraCureMihawk** [comment]
ありがとうございます。理解できました！
