### ISSUE TITLE
test_increment FAILED

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#743]
#### Envrionment

Vim 7.4.763
Compiler MSVC 10 64bit (Microsoft(R) C/C++ Optimizing Compiler Version 16.00.40219.01 for x64)
Without any patches
#### test_increment.failed

```
# Test 1
S1======
foobar-10
E1======

foobar-9
foobar-9
foobar-11
foobar
foobar-
# Test 2
S2=====
10
20
30
40
E2=====

11
21
31
41


# Test 3
S3=====
10

20

30

40
E3=====

12

24

36

48

8

16

24

32

# Test 4
S4=====
foobar-10
E4=====

foobar-10

ENDTEST
```
#### diff with test_increment.ok

``` diff
--- test_increment.ok   2015-06-28 21:50:09 +0900
+++ test_increment.failed   2015-06-28 21:54:45 +0900
@@ -6,10 +6,8 @@
 foobar-9
 foobar-9
 foobar-11
-foobar-11
-foobar-9
-
-
+foobar
+foobar-
 # Test 2
 S2=====
 10
@@ -23,10 +21,6 @@
 31
 41

-9
-19
-29
-39

 # Test 3
 S3=====
```

**Comment by koron** [comment]
これが悪さしているみたい。

```
:verbose vmap <C-X>
v  <C-X>         "-d

:verbose vmap Q
Q             gq
    Last set from D:\Vim\vim74-kaoriya-win64\vim74\vimrc_example.vim
```

これ (`v_C-X`) 、誰が設定してるんだ?
`Q` のほうは `verbose` が機能していることの証明。

**Comment by k-takata** [comment]
同件？
https://groups.google.com/d/msg/vim_dev/5u4nnnUbA70/xtdvu1I9RNcJ

**Comment by koron** [comment]
そうみたい。このマップ、誰が設定してるのか、不明だけれども…
たぶんWinのソース本体なんだろうなぁ。

**Comment by koron** [comment]
[getchar.c の initmappings](https://github.com/vim-jp/vim/blob/318083ec08ce7b586ba564deccd0a59256e632d9/src/getchar.c#L5308-L5356) だった (´・ω・`)

**Comment by koron** [comment]
パッチ作り、投稿しました。 https://gist.github.com/koron/0d2cbab00c6b3eba7cf1

**Comment by koron** [comment]
Patch released as 7.4.764

https://groups.google.com/d/msg/vim_dev/dVxvq883nsA/4f65aqWpRCcJ

**Comment by mattn** [comment]
:+1:
