### ISSUE TITLE
dos-standard-mappings の記述不足

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#744]
#743 に関連して

環境によって自動的に設定されるマッピングがあります。
ソースコードで言うと https://github.com/vim-jp/vim/blob/318083ec08ce7b586ba564deccd0a59256e632d9/src/getchar.c#L5306 このあたり。

ヘルプとしては [`:help dos-standard-mappings`](http://vim-jp.org/vimdoc-ja/os_dos.html#dos-standard-mappings) ([thank you @thinca!](http://lingr.com/room/vim/archives/2015/06/28#message-22091513)) に書いてありますが、
記述項目が足りないように見受けられます。
なので精査して足りなければ書き足しましょう。

MacOS についても定義されるようですが、こっちは…いらないかな? 要検討

**Comment by zchee** [comment]
Macについては
https://github.com/vim-jp/vim/blob/318083ec08ce7b586ba564deccd0a59256e632d9/src/getchar.c#L5358-L5367
の部分でお間違いないでしょうか?

記述項目が足りないissueということですので、Macの定義についても一応+1させて頂きます。

**Comment by koron** [comment]
`MACOS` が、「(懐かしの)MacOS9の意味であってOSXではない」可能性を考えました。
詳細を忘れてしまったので。

もしも OSX の場合が含まれるならば当然ドキュメントを書いたほうが良いです。
含まれない(=MacOS9用の設定)ならば、別に良いかなぁってw

**Comment by k-takata** [comment]
> MACOS が、「(懐かしの)MacOS9の意味であってOSXではない」可能性を考えました。

vim.hを見ると、

``` c
#if defined(MACOS_X) || defined(MACOS_CLASSIC)
# define MACOS
#endif
```

となっているので、新旧両方のように見えます。

**Comment by koron** [comment]
:bow:

**Comment by k-takata** [comment]
`v_CTRL-X` について、投げました。
https://groups.google.com/d/topic/vim_dev/2zTn_PgJ_Ys/discussion
Macについては、（書くのが面倒だったので）ヘルプに記載されていないことを指摘するにとどめています。

**Comment by k-takata** [comment]
> ソースコードで言うと https://github.com/vim-jp/vim/blob/318083ec08ce7b586ba564deccd0a59256e632d9/src/getchar.c#L5306 このあたり。

vim-jp/vim が、vim-jp/vim-obsoleted に移動したことでリンクが切れてしまって悲しい。

**Comment by k-takata** [comment]
当初の dos-standard-mappings に関しては修正済み。
https://github.com/vim/vim/commit/e0fa3742ead676a3074a10edadbc955e1a89153d
MacについてはMacを分かっている人に書いてもらいたいところ。

https://groups.google.com/d/msg/vim_dev/2zTn_PgJ_Ys/ndBIfKMaEAAJ

> I hope someone can do that.  I like complete docs.

**Comment by k-takata** [comment]
macのマッピングについても記載しました。macユーザーの方は確認をお願いします。
https://groups.google.com/d/msg/vim_dev/2zTn_PgJ_Ys/nuyHjCgHDwAJ

ところで、挿入モードで Command-v は `<C-R>*` にマッピングされているようですが、Windowsと同様に `<C-R><C-O>*` にマッピングした方がよくないでしょうか？
ペーストする際はオートインデント等は無効化されている方がいい気がします。

**Comment by k-takata** [comment]
macのマッピングについての記載が取り込まれました。
https://github.com/vim/vim/commit/e0720cbf63eb3045be8d965e3182c0c392c7b5e9
