### ISSUE TITLE
Visual mode で <C-x> や <C-a> を押すと落ちる場合がある (Patch 7.4.765)

### ISSUE THREAD

**Issue by miyakogi** [vim-jp/issues#745]
以下の状態で `v` を押して両方の行を選択し、 `<C-x>` または `<C-a>` を押すと Vim が落ちます。

```
-1
1
```

終了時のメッセージ

```
Vim: Caught deadly signal ABRT
Vim: preserving files...
Vim: Finished.
```

`1, -1` の順では大丈夫でした。
環境は Ubuntu 15.04, Vim 7.4.768 です。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/hnr4LinXVjI

報告しておきました。

**Comment by ichizok** [comment]
7.4.782 で修正されていると思います。
http://ftp.vim.org/vim/patches/7.4/7.4.782

**Comment by miyakogi** [comment]
手元でも修正されていることを確認しました。
ご対応ありがとうございました。
