### ISSUE TITLE
gui で :sh 時にエスケープシーケンスを除去出来ないか

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#746]
Linux の gui 版で :sh すると gui 上で shell が起動します。dumb 端末なのである程度の操作だけ出来ればいいとは思うんですが、エスケープシーケンスを除去しないと正直使い物にならない。

**Comment by k-takata** [comment]
`:set go+=!` で、`:sh` で端末モードが動くようになったので、閉じてもよい？

**Comment by mattn** [comment]
1点気になるのが色が付かないんですよね。

**Comment by k-takata** [comment]
Windows版だと色が付かないけど、Linux版だと色が付きました。
