### ISSUE TITLE
特定の引数の組み合わせで search()/searchpos() 関数がカーソル直下の Unicode文字を検索できない

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#747]
http://vim-jp.org/vimdoc-ja/eval.html#search()

第三引数 flags に `'bce'` を与え、第四引数 stopline も同時に渡した場合にカーソル直下の Unicode 文字の検索に失敗します。(`search()` 関数は `0` を、`searchpos()` 関数は `[0,0]` を返す)

flags の組み合わせを変えたり、 stopline を与えなかったりすると正しく働くようです。

再現スクリプト : Unicode文字なら何でもいいと思いますが `“` を例にとります。

``` vim
new
call setline(1, '“')
echo [
      \   search('“', 'bce', 1),
      \   search('“', 'bc', 1),
      \   search('“', 'ce', 1),
      \   search('“', 'bce')
      \ ]
" -> [0, 1, 1, 1]
```

**Comment by ynkdir** [comment]
これで直ると思います。
https://gist.github.com/ynkdir/388f69a870dfe78f79db

**Comment by machakann** [comment]
パッチを当てて正しく動くことを確認しました！

**Comment by ynkdir** [comment]
確認ありがとうございます。報告しました。
https://groups.google.com/d/msg/vim_dev/XPY4cZaKUag/2jS8NAJvYeoJ

**Comment by mattn** [comment]
:+1:

**Comment by mattn** [comment]
再現性突き止めて無かったですが、これ何度か遭遇した事ありました。

**Comment by ynkdir** [comment]
7.4.771 で修正されました。
https://groups.google.com/d/msg/vim_dev/JckBTr7CpDY/AyouJCxJJAoJ

**Comment by machakann** [comment]
ありがとうございました。
