### ISSUE TITLE
UTF-8 以外で DirectWrite を有効にできないか

### ISSUE THREAD

**Issue by okapixel** [vim-jp/issues#748]
こんにちは、Kaoriya版Vim7.4を使用中ですがフォントレンタリングで要望があります
WIndows付属のフォントレンタリング機能であるCleartypeを使うと、Rictyなどのフォントがつぶされてしまい、非常に見づらいです。
しかし、Cleartypeを無効にすると非常にきれいに表示されます。
CleartypeはUIやブラウザのメイリオに多用されていて常時OFFにするのは好ましくありません。
GVim上だけでCleartypeを阻止出来たら非常にうれしいです。
自分はプログラミングはできないので、申し訳ございませんが

ご検討よろしくお願い申し上げます。

[Cleartypeあり]
![blodg](https://cloud.githubusercontent.com/assets/13287230/8636067/12453dba-2888-11e5-9652-1495b6a0c957.jpg)

[Cleartypeなし]
![blodg](https://cloud.githubusercontent.com/assets/13287230/8636072/6f4e5d98-2888-11e5-8422-7bdc3b694aac.jpg)
Cleartypeをオフにしているので、タイトルバーやメニューバーの文字が見づらいです

**Comment by nb1839** [comment]
vim の ClearType をオフにする、のとは逆ですが
vim の DirectWrite が有効になっていないというお話だったりしませんか？
http://www.kaoriya.net/blog/2013/05/05/

**Comment by okapixel** [comment]
あ、文字コードをutf8にしたら出来ました、ありがとうございます！

**Comment by mattn** [comment]
utf-8 でしか動作しないという問題として reopen した方が良いかと

On 7/13/15, okapixel notifications@github.com wrote:

> Closed #748.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/748#event-353882787

## 
- Yasuhiro Matsumoto

**Comment by okapixel** [comment]
reopenさせていただきました
マニュアルにはutf8のみで動作とありましたが、utf8以外でも動いていただければ嬉しいです
ご検討よろしくお願いします

**Comment by Shougo** [comment]
@okapixel タイトルを「UTF-8 以外で DirectWrite を有効にできないか」と変更したほうがよいと思います。

**Comment by okapixel** [comment]
了解です

**Comment by k-takata** [comment]
DirectWriteの実装時、UTF-8以外の対応は面倒だったのと、UTF-8以外のエンコーディングは今後レガシー扱いになる（orすべき）という判断で、対応は行いませんでした。
もし、enc=utf-8に設定することで何らかの問題が起きるため、DirectWriteを使うことができないという人がいれば、そちらの問題の方を修正すべきと考えています。

ということで、対応しないということで閉じたいと思います。
ただ、どなたかがSJIS対応のパッチを作ることを否定するわけではないということで、backlogとしておきたいと思います。

**Comment by koron** [comment]
🙇
