### ISSUE TITLE
utf-8時に外部コマンドの出力が文字化けする

### ISSUE THREAD

**Issue by okapixel** [vim-jp/issues#749]
たびたび申し訳ございません。utf-8時に文字化けが発生します。

環境：Kaoriya版GVim 7.4 
switches/enabled フォルダに utf-8.vim を導入し utf-8化
状況：cppコードをgvimのメニューからメイク（:make）した

![blodg](https://cloud.githubusercontent.com/assets/13287230/8638447/7137a95c-28f6-11e5-99d9-fc0ef3f758c8.jpg)
（メッセージ最終行）

Vimのメッセージぐらいですと何となくわかりますが、QuickRunなどのプラグイン使用時にも同様に文字化けし、困っております。
どなたか解決していただけましたらうれしいです。

**Comment by mattn** [comment]
```
:set termencoding=char
```

をvimrcに書いてみて貰えますか。

**Comment by okapixel** [comment]
ありがとうございます。しかし変化はありませんでした。

**Comment by mattn** [comment]
すみません。

```
set termencoding=cp932
```

だとどうでしょか？

**Comment by okapixel** [comment]
変化なし、です

**Comment by mattn** [comment]
fileencodingsに何を設定されておられますか？

**Comment by okapixel** [comment]
:set fileencodingsで
fileencodings=guess,iso-2022-jp-3,cp932,euc-jisx0213,ucs-bom

と出ました

**Comment by k-takata** [comment]
#9 と同件ですね。

**Comment by okapixel** [comment]
まったく同じで驚きました。結局fileencodingsが反映されるようになったのでしょうか？私のfileencodingsに何か問題がありますか？

**Comment by k-takata** [comment]
> 結局fileencodingsが反映されるようになったのでしょうか？

残念ながらなっていないはずです。

**Comment by mattn** [comment]
あー、msvc ですか。最近 mingw しか使って無かったので気付かなかった。

**Comment by okapixel** [comment]
どなたか実装をお願い出来ましたら幸いです...非力で申し訳ございません

**Comment by mattn** [comment]
いえいえ、ユーザ的な目線でご意見下さる事で十分助かります。

**Comment by ghost** [comment]
これだったらいいなという部分、貼り付けます
http://vim-jp.org/vimdoc-ja/quickfix.html

QuickFixCmdPost を使ってエンコーディングを修正する

 ビルドプログラムが出力するメッセージと 'encoding' の値が異なる場合がある。この
例は、Vim がそのエラーメッセージを読み込んだ後でエンコーディングを変換する方法
を示している:

```
    function QfMakeConv()
        let qflist = getqflist()
        for i in qflist
           let i.text = iconv(i.text, "cp936", "utf-8")
        endfor
        call setqflist(qflist)
     endfunction


    au QuickfixCmdPost make call QfMakeConv()
```

 (Faque Cheng による例)

**Comment by mattn** [comment]
@okapixel  make で実行されるプログラムを手動で実行することは可能でしょか？であれば一度 `set makeprg` で make コマンドを確認頂きコマンドプロンプトから

```
nmake > output
```

※nmake の部分は上記の確認結果でお願いします。

を実行、その output がどんなエンコーディングになっているか確認頂けますか。

**Comment by okapixel** [comment]
当方アホすぎて分かりません…
とりあえず
:set makeprg=make
でした。ここからどうすればよろしいでしょう？

**Comment by mattn** [comment]
```
:sh
```

でコマンドプロンプトに入って `make > output.log` とし、他のエディタ等で `output.log` がどんなエンコーディングが確認頂けますか。

**Comment by okapixel** [comment]
makeが内部パッチとして認識されていないと出たのですが…

**Comment by mattn** [comment]
あ、そうなのですね。どのコンパイラをお使いかわかりませんが、 Visual Studio ならば `set makeprg=nmake`、mingw をお使いならば `set makeprg=mingw32-make` として試してください。

**Comment by k-takata** [comment]
スクリーンショットを見る限り、明らかにcp932ですね。

```
'make' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

と出たのではないでしょうか。

**Comment by okapixel** [comment]
k-takataさんのおっしゃる通りのメッセージが出ました。
あと申し訳ないのですが、nmakeもmingw32-makeも同様のメッセージでした...本当申し訳ないです。
えっと、参考になるか分かりませんが、確かコンパイラはgcc？かg++というのを使ってるんだぜという話を聞いたことがあるような気がします。
この面はド素人の癖にネットから見よう見まねで頑張っているのであまりしっかりした知識が身についていなくてお恥ずかしいです...一応Cygwinでコマンドを入れまくってパスを通して使っているだけなのですが、いかがでしょうか？mingw32というものも入れるべきなのでしょうか？

**Comment by mattn** [comment]
結論で言いますと設定不備という事になります。
cygwinですとmakeになります。makeを入手して頂いた上で出力結果を確認し、そのエンコーディングをtermencodingに設定して下さい。
make が無い場合(かつcygwinでないvimの場合)はコマンドプロンプトのエラーメッセージ(こちらは sjis 固定)が出ますが、そちらは make が出力するエンコーディングと異なる場合があります。
これは私の経験則ですが cygwin や msys を使う場合は cygwin/msys に付属の vim を使った方が良いです。また逆に cygwin/msys でない vim を使う場合は cygwin/msys 系のツールを使わない方が良い(mingw32 や mingw64 を検討)です。

**Comment by k-takata** [comment]
> そのエンコーディングをtermencodingに設定して下さい。

Win32版でenc=utf-8時に、`:make`の実行結果が文字化けするのは、tenc, fencs等を設定しても改善しないのではないでしょうか。設定すべきは以下の2点だと思います。
1. PATH等を適切に設定して、makeコマンドが正常に動作するようにする。
2. https://github.com/vim-jp/issues/issues/749#issuecomment-120825496 の指摘を適用する。
   ただし、makeコマンドのエンコーディングに合わせて、`"cp936"` の部分を適切に修正する必要あり。

**Comment by mattn** [comment]
個人的には、コンパイラが吐く出力はコンパイラベンダ次第だし、gcc の場合それすらも変更可能なのでユーザがmakeprgで対応すべきだと思います。(vimは対応すべきではない)

**Comment by mattn** [comment]
例えば出力utf-8を強制したいなら

https://github.com/mattn/utf8run

これを使って

```
:set makeprg=utf8run\ make
```

っていう方法はありますね。

**Comment by sgur** [comment]
もし、英語のメッセージを読むのがそれほど苦でないのであれば、
.vimrc の先頭に、

```
let $LC_ALL="C"
let $LANG="C"
```

と書いてしまって、makeを含む、cygwinのコマンドが出力するメッセージを全て英語化してしまうのも一つの手です。

**Comment by k-takata** [comment]
#9 と同一案件のため、閉じます。
