### ISSUE TITLE
多言語のヘルプがある場合の :help の補完

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#75]
多言語のヘルプがインストールされている環境、例えば英語と日本語のヘルプがある場合、

```
:help expr-str<Tab>
```

とすると、候補は `expr-string@en` と `expr-string@ja` の2つがあるため、
`'wildmode'` が `longest` の場合は

```
:help expr-string@
```

と補完される。ここで `<CR>` すると、

```
E149: 残念ですが expr-string@ にはヘルプがありません
```

と言われる。非常に残念なのでなんとかしたい。

**Comment by koron** [comment]
具体的にどうなるべき? 個々の仕様は簡潔で完結しているので、問題はなさそうにみえる。

たとえば`'helplang'`から補う、とか?

**Comment by thinca** [comment]
`:help expr-string@` で `expr-string` が開くといいんじゃないか、と考えてます。

**Comment by koron** [comment]
+1

**Comment by mattn** [comment]
これはよい練習台

**Comment by mattn** [comment]
こういう意味ですか？

``` diff
diff -r f530aef0d959 src/ex_cmds.c
--- a/src/ex_cmds.c Wed Oct 12 22:02:14 2011 +0200
+++ b/src/ex_cmds.c Fri Oct 14 11:32:52 2011 +0900
@@ -5546,6 +5546,8 @@
     p = arg + STRLEN(arg) - 1;
     while (p > arg && vim_iswhite(*p) && p[-1] != '\\')
    *p-- = NUL;
+    if (*p == '@')
+   *p = NUL;

 #ifdef FEAT_MULTI_LANG
     /* Check for a specified language */
```

**Comment by thinca** [comment]
ソースコードの前後の文脈を見てないのでわかりませんが、無条件で消すと `:help @` などができなくなりませんか?

**Comment by thinca** [comment]
あ、「こういう感じの意味?」と言う事なら、そうです。

**Comment by mattn** [comment]
1文字は残るwhileなのでokなのですが`@@`が検索出来ないですね。
あとで直します。

**Comment by h-east** [comment]
練習

``` diff
diff -r 5e84f6567623 src/ex_cmds.c
--- a/src/ex_cmds.c     Wed Sep 21 20:09:42 2011 +0200
+++ b/src/ex_cmds.c     Fri Oct 14 13:06:27 2011 +0900
@@ -5544,6 +5544,9 @@
     while (p > arg && vim_iswhite(*p) && p[-1] != '\\')
        *p-- = NUL;

+    if (*arg != '@' && *p == '@')
+       *p = NULL;
+
 #ifdef FEAT_MULTI_LANG
     /* Check for a specified language */
     lang = check_help_lang(arg);
```

**Comment by mattn** [comment]
このissueは技術力よりも英語力を問われそう

**Comment by h-east** [comment]
し、しまった！罠にかかってしまったｗ
勘弁して下さい。

**Comment by thinca** [comment]
`@` で終わるタグは他にも、`:@` `g@` `let-@` `i_CTRL-@` など多数あり、`TwitVim-Leader-@` などプラグインで増える可能性もあるので、
検索してタグが見付からなかった場合のみ、最後が `@` だったら外して再試行、が良さそうです。

**Comment by h-east** [comment]
@thinca なるほど。さすがです。

**Comment by h-east** [comment]
俺、たった今
```diff
～
```
を覚えたばかりのおっさんです。

**Comment by mattn** [comment]
リトライ

``` diff
diff -r f530aef0d959 src/ex_cmds.c
--- a/src/ex_cmds.c Wed Oct 12 22:02:14 2011 +0200
+++ b/src/ex_cmds.c Fri Oct 14 14:00:47 2011 +0900
@@ -5507,6 +5507,7 @@
 #ifdef FEAT_MULTI_LANG
     int        len;
     char_u *lang;
+    int        try_noatmark = FALSE;
 #endif
 #ifdef FEAT_FOLDING
     int        old_KeyTyped = KeyTyped;
@@ -5558,22 +5559,32 @@

     /*
      * Check if there is a match for the argument.
+     * If no matches, try to find tag without last '@'.
      */
-    n = find_help_tags(arg, &num_matches, &matches,
+    while (1)
+    {
+   n = find_help_tags(arg, &num_matches, &matches,
                         eap != NULL && eap->forceit);

-    i = 0;
+   i = 0;
 #ifdef FEAT_MULTI_LANG
-    if (n != FAIL && lang != NULL)
-   /* Find first item with the requested language. */
-   for (i = 0; i < num_matches; ++i)
-   {
-       len = (int)STRLEN(matches[i]);
-       if (len > 3 && matches[i][len - 3] == '@'
-                 && STRICMP(matches[i] + len - 2, lang) == 0)
-       break;
-   }
-#endif
+   if (n != FAIL && lang != NULL)
+       /* Find first item with the requested language. */
+       for (i = 0; i < num_matches; ++i)
+       {
+       len = (int)STRLEN(matches[i]);
+       if (len > 3 && matches[i][len - 3] == '@'
+               && STRICMP(matches[i] + len - 2, lang) == 0)
+           break;
+       }
+#endif
+   if (i < num_matches || n == FAIL || *p != '@' || try_noatmark == TRUE)
+       break;
+   /* Retry after remove '@' at last. */
+   *p = NUL;
+   try_noatmark == TRUE;
+    }
+
     if (i >= num_matches || n == FAIL)
     {
 #ifdef FEAT_MULTI_LANG
```

**Comment by mattn** [comment]
どうしようかな。 #84 が直るなら、これってもしかして必要ない？

**Comment by ynkdir** [comment]
多少話はずれますが `@xx` を補完に出さないというのもありますね。
en と ja の二つくらいならまだ大丈夫ですがたくさんの言語ファイルがあった場合に
foo@en foo@ja foo@it foo@fr ...
と延々と出るよりは
foo
と、一個だけのほうがすっきりです。
まだちゃんとあら探ししてません。
これまたcより英語が必要な提案ですが…。

**Comment by h-east** [comment]
@ynkdir +=3

**Comment by thinca** [comment]
それは十分ありですね。`@en` と `@ja` だけでも正直ちょっと鬱陶しいと感じてました。この程度の文字数なら手で入力しても大差ないし。
あ、もしくは、`foo` まで補完された後手動で `@` を入力して `<Tab>` するとさらに候補が出るってのも挙動としてはありですね。(すごく面倒そうだけど)

**Comment by tyru** [comment]
@ynkdir +1

**Comment by thinca** [comment]
これ今ラベルが `status/patched` になってますけど、 @ynkdir さんの案を採用するとなるとまだパッチはない?

**Comment by koron** [comment]
なさげ。

**Comment by thinca** [comment]
`status/patches welcome` にしておきました。

**Comment by mattn** [comment]
投げました。

https://groups.google.com/forum/#!topic/vim_dev/HSSZx16yHa4

**Comment by thinca** [comment]
おおお、ありがとうございます！
とりあえず今の挙動はどうなのよっていう確認ですね。

**Comment by k-takata** [comment]
vim_devの方の反応が全くありませんが、補完の候補から `@en` を削除してしまうのはどうでしょう。
最初の例で行くと、`expr-string@ja` と `expr-string` が候補として表示され、`longest` の場合は、`expr-string` までしか補完されません。
欠点は、`@en` を候補から選ぶことができなくなってしまうため、英語を表示したい場合は、必ず`@en`を手で入力しなければならない点ですが…。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/898a197d8901ddc93935877c96984e446b317e8a/omit-en-from-help.patch?fileviewer=file-view-default

ynkdirさんの案は、どうすれば実現できるのか分かりませんでした。

**Comment by tyru** [comment]
helplangを設定してるなら`@en`も`@ja`も削除しちゃうのもアリな気がします。
helplangを設定しているって事は明示的に指定しない限りはhelplangの言語で開かれてほしいはずなので。

**Comment by k-takata** [comment]
しばらく使ってみましたが、`@en`を削除してしまうと英語の項目を候補から選べなくなり、動作が変わってしまうので良くないです。
先頭の候補が、`'helplang'`で指定した最初の言語と一致していれば、`@`以降を削除するようにすると、今までとほとんど動作も変わらず、良さげな感じです。

**Comment by k-takata** [comment]
上記のパッチ
https://bitbucket.org/k_takata/vim-ktakata-mq/src/2bbbc98ac09438eaa9d2466526de36cb208d5807/omit-helplang.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/HSSZx16yHa4/Hu6XSI1LHAAJ

**Comment by k-takata** [comment]
7.4.1671
https://groups.google.com/d/topic/vim_dev/JXQEvU9AUtw/discussion
閉じます。

**Comment by mattn** [comment]
関係してる気がする(しないかもしれない)

patch 7.4.1818
https://github.com/vim/vim/commit/89c79b99328b66f77f1d12dc8c6701dfe2c57f15

**Comment by k-takata** [comment]
思いっきり関係していますね。
https://groups.google.com/d/topic/vim_dev/1XNj-09SOEA/discussion
余計な `@en` がつくという指摘ですが、何か問題でも？という気がします。

で、日本語ヘルプをインストールした状態で、7.4.1818 でtabで補完すると `@ja` も `@en` もついていない項目が、2つ同じものが表示されてしまってよろしくないですね。

例: `:h screenrow()` で tab を押すと、`screenrow()` が2つ表示される。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/x859DVNBq5E/eafPH9KMBQAJ

> > BTW, I think that adding `@en` to all matches is harmless.
> 
> Although this would be harmless, the `@en` should not be added when it's
> not needed, the matches look different from the actual help tag. 

`@en` が無害だとしても必要ない時には表示されるべきではないというのは確かにそうですが、`screenrow()` が2つ表示されるのはどう考えても問題なのですが…。

**Comment by h-east** [comment]
変更分岐点のpatch(7.4.1671, 7.4.1818)の後、中、前の挙動を調べて纏めました。
@k-takata どういう挙動を期待していますでしょうか？
`set helplang=ja ヘルプファイル:en, ja`の挙動をどうするかの話だけだと、仮に 7.4.1670 に合わせると、結局 7.4.1671 は何だったのかって話になっちゃいそう:smile:

ヘルプファイル:en → `$ LANG=en_us.utf-8 vim -Nu NONE`
ヘルプファイル:en, ja → `$ LANG=en_us.utf-8 vim -Nu NONE -c "set rtp+=~/vimdoc-ja"`

Vim 7.4.1818
- set helplang= ヘルプファイル:en

```
:h screenc<C-D>
screencol()   screenchar()
```
- set helplang= ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()@en   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=en ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()@en   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=ja ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()   screenchar()  screenchar()
```

# 

Vim 7.4.1671
- set helplang= ヘルプファイル:en

```
:h screenc<C-D>
screencol()      screenchar()@en
```
- set helplang= ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()@en   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=en ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()      screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=ja ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()      screencol()@en   screenchar()@ja  screenchar()@en
```

# 

Vim 7.4.1670
- set helplang= ヘルプファイル:en

```
:h screenc<C-D>
screencol()   screenchar()
```
- set helplang= ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()@en   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=en ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()@en   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=ja ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()@ja   screencol()@en   screenchar()@ja  screenchar()@en
```

**Comment by k-takata** [comment]
こうですかね？
- set helplang= ヘルプファイル:en

```
:h screenc<C-D>
screencol()   screenchar()
```
- set helplang= ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=en ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()@ja   screenchar()@en  screenchar()@ja
```
- set helplang=ja ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()@en   screenchar()@ja  screenchar()@en
```

repoenしておきますか。

**Comment by DeaR** [comment]
7.4.1818の方向性を鑑みるに`'helplang'`の最初の値(無指定時は`en`)を常に削除辺りが
一番納得してくれそうな気がします
- set helplang= ヘルプファイル:en

```
:h screenc<C-D>
screencol()   screenchar()
```
- set helplang= ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()@ja   screenchar()  screenchar()@ja
```
- set helplang=en ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()@ja   screenchar()  screenchar()@ja
```
- set helplang=ja ヘルプファイル:en, ja

```
:h screenc<C-D>
screencol()   screencol()@en   screenchar()  screenchar()@en
```

**Comment by h-east** [comment]
@DeaR さん提案の挙動になるpatchを書いてみました。

``` patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 26fed59..286b2df 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -4501,18 +4501,15 @@ static void cleanup_help_tags(int num_file, char_u **file);
     static void
 cleanup_help_tags(int num_file, char_u **file)
 {
-    int        i, j;
+    int        i;
     int        len;
-    char_u buf[4];
-    char_u *p = buf;
+    char_u buf[] = "@en";

-    if (p_hlg[0] != NUL && (p_hlg[0] != 'e' || p_hlg[1] != 'n'))
+    if (p_hlg[0] != NUL)
     {
-   *p++ = '@';
-   *p++ = p_hlg[0];
-   *p++ = p_hlg[1];
+   buf[1] = p_hlg[0];
+   buf[2] = p_hlg[1];
     }
-    *p = NUL;

     for (i = 0; i < num_file; ++i)
     {
@@ -4520,23 +4517,8 @@ cleanup_help_tags(int num_file, char_u **file)
    if (len <= 0)
        continue;
    if (STRCMP(file[i] + len, buf) == 0)
-   {
        /* remove the default language */
        file[i][len] = NUL;
-   }
-   else if (STRCMP(file[i] + len, "@en") == 0)
-   {
-       /* Sorting on priority means the same item in another language may
-        * be anywhere.  Search all items for a match up to the "@en". */
-       for (j = 0; j < num_file; ++j)
-       if (j != i
-           && (int)STRLEN(file[j]) == len + 3
-           && STRNCMP(file[i], file[j], len + 1) == 0)
-           break;
-       if (j == num_file)
-       /* item only exists with @en, remove it */
-       file[i][len] = NUL;
-   }
     }
 }
 #endif
```

**Comment by k-takata** [comment]
set helplang=ja ヘルプファイル:en の場合どうなります？

```
:h screenc<C-D>
screencol()   screenchar()
```

となるようにするのが 7.4.1818 の修正ですが、それだと元に戻ってしまうと思います。

**Comment by h-east** [comment]
> set helplang=ja ヘルプファイル:en の場合どうなります？

私のpatchだと

```
:h screenc<C-D>
screencol()@en   screenchar()@en
```

になりますが、これで良いんじゃないかと思ってます。
(`helplang`の最初の言語を省略する。未設定の場合は`@en`を省略する。)
ダメ？

**Comment by k-takata** [comment]
> これで良いんじゃないかと思ってます。

私もそう思うのですが、Bramにダメと言われたのでダメです。残念ながら。

**Comment by h-east** [comment]
それでは、私のpatchに
- 最初に`helplang`に指定の言語を順番に探して、見つかった言語を省略対象にする。(どれもなければ`@en`を省略対象にする)

という処理を最初におこなう。というのはどうでしょう？

**Comment by k-takata** [comment]
よさそうな感じがします。

**Comment by h-east** [comment]
これで。
(後修正: 関数コメントを修正しました)

``` patch
diff --git a/src/ex_getln.c b/src/ex_getln.c
index 26fed59..c747d9a 100644
--- a/src/ex_getln.c
+++ b/src/ex_getln.c
@@ -4493,26 +4493,39 @@ expand_cmdline(
 #ifdef FEAT_MULTI_LANG
 /*
  * Cleanup matches for help tags:
- * Remove "@ab" if the top of 'helplang' is "ab" and the language of the first
- * tag matches it.  Otherwise remove "@en" if "en" is the only language.
+ * Remove "@ab" if the 'helplang' included "ab" and the language of the first
+ * tag matches at least one.  Otherwise remove "@en".
  */
 static void    cleanup_help_tags(int num_file, char_u **file);

     static void
 cleanup_help_tags(int num_file, char_u **file)
 {
-    int        i, j;
+    int        i;
     int        len;
-    char_u buf[4];
-    char_u *p = buf;
+    char_u buf[] = "@xx";
+    char_u *omit_lang;
+
+    /* decide the omit target language */
+    for (omit_lang = p_hlg; *omit_lang != NUL; omit_lang += 3)
+    {
+   buf[1] = omit_lang[0];
+   buf[2] = omit_lang[1];

-    if (p_hlg[0] != NUL && (p_hlg[0] != 'e' || p_hlg[1] != 'n'))
+   for (i = 0; i < num_file; ++i)
+   {
+       len = (int)STRLEN(file[i]) - 3;
+       if (len <= 0)
+       continue;
+       if (STRCMP(file[i] + len, buf) == 0)
+       break;
+   }
+    }
+    if (*omit_lang == NUL)
     {
-   *p++ = '@';
-   *p++ = p_hlg[0];
-   *p++ = p_hlg[1];
+   buf[1] = 'e';
+   buf[2] = 'n';
     }
-    *p = NUL;

     for (i = 0; i < num_file; ++i)
     {
@@ -4520,23 +4533,8 @@ cleanup_help_tags(int num_file, char_u **file)
    if (len <= 0)
        continue;
    if (STRCMP(file[i] + len, buf) == 0)
-   {
-       /* remove the default language */
+       /* remove the omit target language */
        file[i][len] = NUL;
-   }
-   else if (STRCMP(file[i] + len, "@en") == 0)
-   {
-       /* Sorting on priority means the same item in another language may
-        * be anywhere.  Search all items for a match up to the "@en". */
-       for (j = 0; j < num_file; ++j)
-       if (j != i
-           && (int)STRLEN(file[j]) == len + 3
-           && STRNCMP(file[i], file[j], len + 1) == 0)
-           break;
-       if (j == num_file)
-       /* item only exists with @en, remove it */
-       file[i][len] = NUL;
-   }
     }
 }
 #endif
```

**Comment by k-takata** [comment]
helplang=ja の時でも `@en` が削除されているような？

**Comment by DeaR** [comment]
Bramは7.4.1671では先頭候補以外は`'helplang'`をどうしようと`@en`が出てくるのを
嫌がったんだと読み取ったのだけどなぁ

> - set helplang= ヘルプファイル:en
> 
> ```
> :h screenc<C-D>
> screencol()      screenchar()@en
> ```
> - set helplang=en ヘルプファイル:en, ja
> 
> ```
> :h screenc<C-D>
> screencol()      screencol()@ja   screenchar()@en  screenchar()@ja
> ```

**Comment by h-east** [comment]
> helplang=ja の時でも @en が削除されているような？

:sweat_smile: 修正しました。
https://gist.github.com/h-east/de328bd034bd212fd910d5f98eb7a295

test追加出来るかな？

**Comment by h-east** [comment]
> - 最初に`helplang`に指定の言語を順番に探して、見つかった言語を省略対象にする。(どれもなければ`@en`を省略対象にする)

うーん、やっぱりこれはキモい気がしますね。タグの検索結果で省略する対象が変わりますからユーザーには優しくないですし。

**Comment by k-takata** [comment]
helplangの最初の言語だけ削除対象にするならまだ予測可能な気もします。

**Comment by h-east** [comment]
Vim 7.4.1818 の以下の挙動を修正するだけのpatchも作ってみました。
(ループを2回実施。1回目→単独`@en`を消す。2回目→`helplang`の最初の言語(`@??`を消す)
https://gist.github.com/h-east/425d3ad1a249bffc2e6bba2804ebc071
- set helplang=ja ヘルプファイル:en, ja

patch前

```
:h screenc<C-D>
screencol()   screencol()   screenchar()  screenchar()
```

patch後

```
:h screenc<C-D>
screencol()      screencol()@en   screenchar()     screenchar()@en
```

これなら反対する人いないのでは？

**Comment by h-east** [comment]
testを追加してvim_devに送りました。
https://groups.google.com/d/msg/vim_dev/x859DVNBq5E/GjIhI90gBgAJ

**Comment by h-east** [comment]
速攻でincludeされただ👍
patch 7.4.1820
https://github.com/vim/vim/commit/9ccaae04c6f263e6db14fc403bca2404a7871114

再closeします。

**Comment by h-east** [comment]
WindowsのtestがfailsになってたのをBram氏がfixしてくれた:+1:
patch 7.4.1821
https://github.com/vim/vim/commit/4ed6b2e2d7fd5959fb9b9f608935d47305c4bbe4
