### ISSUE TITLE
Windows10 の vim.exe で IME エコーバックが機能しない

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#751]
速攻解決

``` diff
diff --git a/src/os_win32.c b/src/os_win32.c
index 1e1214b..0090405 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -3774,6 +3774,9 @@ mch_settmode(int tmode)

     GetConsoleMode(g_hConIn, &cmodein);
     GetConsoleMode(g_hConOut, &cmodeout);
+
+    cmodein &= ~(0x0080); /* ENABLE_EXTENDED_FLAGS */
+
     if (tmode == TMODE_RAW)
     {
    cmodein &= ~(ENABLE_LINE_INPUT | ENABLE_PROCESSED_INPUT |
```

過去未使用ビットであった Win10 で追加されたフラグを潰しています。
この方法だと OS に依存しないはずです。
今わたしの手元には Windows10 しかないので他の OS での動作確認は必要かもしれません。

**Comment by ghost** [comment]
他の Windows OS での確認をお願いできますでしょうか？
日本語入力がいつもと同じように打てれば問題はないと考えます。
未パッチ vim.exe は Win10 では入力中の全角文字が全く表示されてきません。

**Comment by k-takata** [comment]
`tmode == TMODE_RAW`かどうかに関わらず、フラグを落とすのですか？

**Comment by k-takata** [comment]
Win7では`ENABLE_EXTENDED_FLAGS`を落としても問題なく動いているように見えます。

**Comment by k-takata** [comment]
`ENABLE_EXTENDED_FLAGS`は、VC7.1ではdefineされていないが、VC10ではdefineされていることを確認。

**Comment by k-takata** [comment]
どこかに、

``` c
#ifndef ENABLE_EXTENDED_FLAGS
#define ENABLE_EXTENDED_FLAGS 0x0080
#endif
```

とした方がいいでしょうね。

**Comment by ghost** [comment]
ありがとうございます。
RAW が存在しているという実装の現実を尊重すべきでした。修正します。
define はそのとおりですね、これも追加します。
BOOL win10_or_later での場合分けを導入したいところでしたが、わりときりがないので割愛していました。この点については現行のまま、場合分けなしでいこうと思います。

**Comment by ghost** [comment]
``` diff
diff --git a/src/os_win32.c b/src/os_win32.c
index 1e1214b..a056b30 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -3761,6 +3761,9 @@ handler_routine(
     }
 }

+#ifndef ENABLE_EXTENDED_FLAGS
+# define ENABLE_EXTENDED_FLAGS 0x0080 /* from Windows 10 SDK */
+#endif

 /*
  * set the tty in (raw) ? "raw" : "cooked" mode
@@ -3787,6 +3790,9 @@ mch_settmode(int tmode)
     }
     else /* cooked */
     {
+   /* disable <Control> key shortcut */
+   cmodein &= ~ENABLE_EXTENDED_FLAGS;
+
    cmodein |= (ENABLE_LINE_INPUT | ENABLE_PROCESSED_INPUT |
            ENABLE_ECHO_INPUT);
    cmodeout |= (ENABLE_PROCESSED_OUTPUT | ENABLE_WRAP_AT_EOL_OUTPUT);
```

現状この形になっています。ほかに問題になりそうな点はありますでしょうか。

**Comment by ghost** [comment]
あれ、失敗してますね…
RAW でも COOK でもない場合(あるのか?)にかかってるのかな…

**Comment by k-takata** [comment]
Vim動作中はRAWじゃないですか？

**Comment by ghost** [comment]
とっちらかるのは悪い癖で、まずは RAW 側に移動したところ最初の例のように動作しました。

``` diff
diff --git a/src/os_win32.c b/src/os_win32.c
index 1e1214b..74dd7cb 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -3761,6 +3761,9 @@ handler_routine(
     }
 }

+#ifndef ENABLE_EXTENDED_FLAGS
+# define ENABLE_EXTENDED_FLAGS 0x0080 /* from Windows 10 SDK */
+#endif

 /*
  * set the tty in (raw) ? "raw" : "cooked" mode
@@ -3776,6 +3779,9 @@ mch_settmode(int tmode)
     GetConsoleMode(g_hConOut, &cmodeout);
     if (tmode == TMODE_RAW)
     {
+   /* disable <Control> key shortcut */
+   cmodein &= ~ENABLE_EXTENDED_FLAGS;
+
    cmodein &= ~(ENABLE_LINE_INPUT | ENABLE_PROCESSED_INPUT |
             ENABLE_ECHO_INPUT);
 #ifdef FEAT_MOUSE
```

これでいけるかな…

**Comment by ghost** [comment]
いけなかった…
:intro を日本語にしているとうまくいかないかなにかで、もうちょっと整頓してから出直します。
そういう :intro がどうこうの関連性はないような気はするのですけれど…。

**Comment by ghost** [comment]
複数ポストされたキーボードイベントを一気読みしないといけなかった Win8 の仕様、Win10 では Win7 以前の方法、イベントを一個ずつ読み取っても動作するように変更されているようで…
画面更新のタイミングのような気もしてきているので追試しています。

**Comment by ghost** [comment]
よっしゃ取れた

``` diff
diff --git a/src/os_win32.c b/src/os_win32.c
index 1e1214b..d782a9d 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -259,6 +259,9 @@ read_console_input(
     int tail;
     int i;

+    if (nLength == -2)
+   return (s_dwMax > 0) ? TRUE : FALSE;
+
     if (!win8_or_later)
     {
    if (nLength == -1)
@@ -303,7 +306,7 @@ read_console_input(
     }

     *lpBuffer = s_irCache[s_dwIndex];
-    if (nLength != -1 && ++s_dwIndex >= s_dwMax)
+    if (!(nLength == -1 || nLength == -2) && ++s_dwIndex >= s_dwMax)
    s_dwMax = 0;
     *lpEvents = 1;
     return TRUE;
@@ -322,6 +325,30 @@ peek_console_input(
     return read_console_input(hInput, lpBuffer, -1, lpEvents);
 }

+    static DWORD
+msg_wait_for_multiple_objects(
+    DWORD    nCount,
+    LPHANDLE pHandles,
+    BOOL     fWaitAll,
+    DWORD    dwMilliseconds,
+    DWORD    dwWakeMask)
+{
+    if (read_console_input(NULL, NULL, -2, NULL))
+   return WAIT_OBJECT_0;
+    return MsgWaitForMultipleObjects(nCount, pHandles, fWaitAll,
+                    dwMilliseconds, dwWakeMask);
+}
+
+    static DWORD
+wait_for_single_object(
+    HANDLE hHandle,
+    DWORD dwMilliseconds)
+{
+    if (read_console_input(NULL, NULL, -2, NULL))
+   return WAIT_OBJECT_0;
+    return WaitForSingleObject(hHandle, dwMilliseconds);
+}
+
     static void
 get_exe_name(void)
 {
@@ -1459,10 +1486,10 @@ WaitForChar(long msec)
 #ifdef FEAT_CLIENTSERVER
        /* Wait for either an event on the console input or a message in
         * the client-server window. */
-       if (MsgWaitForMultipleObjects(1, &g_hConIn, FALSE,
+       if (msg_wait_for_multiple_objects(1, &g_hConIn, FALSE,
                 dwWaitTime, QS_SENDMESSAGE) != WAIT_OBJECT_0)
 #else
-       if (WaitForSingleObject(g_hConIn, dwWaitTime) != WAIT_OBJECT_0)
+       if (wait_for_single_object(g_hConIn, dwWaitTime) != WAIT_OBJECT_0)
 #endif
            continue;
    }
```

以前 Win8 で IME 入力ができなかったときにここまでパッチしないといけなかった編
というかやっぱり一気読みはしないといけませんでした、寝ぼけていた模様

**Comment by ghost** [comment]
Windows10 と Windows8.1 では動作を確認しました。
度々で本当に申し訳ありません、Windows7 以前の OS での確認をお願いできますか？

**Comment by k-takata** [comment]
ENABLE_EXTENDED_FLAGS のパッチと両方必要ですか？
新しいパッチが何をやっているのか、簡単に説明していただけるとありがたいです。

**Comment by ghost** [comment]
すみません、肝心なところが不足していました。
ENABLE_EXTENDED_FLAGS のパッチは必要ありません。
WaitFor- を含む方だけでお願いします。

内容ですが、端的に言うとコンソール入力待ち部分についての私による修正漏れです。

Vim 本体に取り込まれた私が提出したパッチ 7.4.142 で Win8 の ReadConsoleInput() の仕様変更に対応する際、まだ Vim 本体への理解が進んでいなかったので見逃していた部分がありまして、結果的にその不足分を補てんするものになっています。

以下補足：

コードは、Vim がコンソール入力のハンドル g_hConIn に WaitFor 系関数を使うことでキー入力イベントの有無を調べている部分 (WAIT_OBJECT_0 が返ればコンソール入力バッファにイベントがある)を置き換え、7.4.142 で追加したコンソール入力イベントバッファリング関数 read_console_input() が内部に持っている static な入力イベントバッファに対し、コンソール入力イベントのストックがあるかないかを問い合わせる動作を追加しています。

今回のパッチで、read_console_input() の中にまだ未処理の独自にバッファリングしているコンソール入力イベントがあるにもかかわらず、WaitFor 系関数が監視している本来のコンソール入力イベントバッファが空になっているため、適切に制御を返してこない…という異常な状態を解消することができていると思います。

**Comment by k-takata** [comment]
試しました。Win7でも問題なく動いているように見えます。

Win8でUnicode版のReadConsoleInputW()を使った場合はこんな面倒なことしなくても済むんですかね？
それともサロゲートペアが入力されたら、やはりANSI版と同じようにWCHAR 2つ分を一回の呼び出しで取得しないとダメなんですかね。

ふと思ったのですが、WaitForで待ってからPeekConsoleInputで先頭のイベントを読んで、leadingバイトだったらReadConsoleInputで2つ分読んで、それ以外なら1つ分読むというのだとうまくいったりしませんかね。

**Comment by ghost** [comment]
確認ありがとうございます。
1イベントを構成するレコード群は分割せず一気に読まないといけないというルールがあるならあるで一言書いていてくれればいいのにと思わなくもないです…。

たぶん Vim がやっている1レコードずつだけ読み込む方法のほうが例外的なんだと思います。

**Comment by ghost** [comment]
ReadConsoleInputW でも同様に一回の呼び出しで読み切らないと別のデータが来てしまっていた覚えがあります。

PeekConsoleInput の方はどうなんでしょう、海外の IME も含めたユニバーサル的解決策を考えたときには一気読みが一番確実な気もします。

**Comment by ghost** [comment]
vim_dev に持ち出しました。
https://groups.google.com/d/msg/vim_dev/1DdoppGoopg/0RmgIsvYBgAJ

**Comment by k-takata** [comment]
7.4.808
https://groups.google.com/d/topic/vim_dev/SdP0hVtubNc/discussion
