### ISSUE TITLE
Ctrl-V Ctrl-Aの動作がおかしい

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#752]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">vim のバグ踏んだくさいが、どうだろ？&#10;&#10;z&lt;tab&gt;10&#10;&lt;tab&gt;20&#10;&#10;（ようは桁が不揃いな行末をタブで揃えて二桁の数値を入れる）&#10;&#10;で10と20を矩形選択して&lt;c-a&gt;</p>&mdash; tAkihiko (@ATA911) <a href="https://twitter.com/ATA911/status/628135153622085632">2015, 8月 3</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Vim 7.4.811 で、

```
z       20
        21
```

となることを確認。

**Comment by h-east** [comment]
対応中。

**Comment by h-east** [comment]
動作確認してもらえると嬉しいな。
test ALL DONE.は確認してます。

概要: visual block時はcolじゃなくてvcolを基準にしないとタブ文字を含む行でズレが生じます。

https://gist.github.com/h-east/ad3d22c13188de1466d3

**Comment by ichizok** [comment]
```
vim -u NONE -N
iz<TAB>10<CR><TAB>-1<Esc>hk<C-V>jl<C-X>
```

```
z       10
        -1
```

```
z       9
        -0
```

さらに `gv<C-X>` すると `-0` &rarr; `--1` になります。

**Comment by h-east** [comment]
@ichizok 動作確認Thanks!
patch 更新しました。
https://gist.github.com/h-east/ad3d22c13188de1466d3

**Comment by ichizok** [comment]
`linkbreak` と `showbreak` が設定されているとうまく動きません。

ウィンドウ幅 28 で実行。

```
vim -u NONE -N
:echo winwidth(0)
28
:set linkbreak
:set showbreak=+    
iz<TAB><TAB><TAB><TAB>10<CR><TAB><TAB><TAB><TAB>-1<Esc>hk<C-V>jl<C-X>
```

```
z                           
+    10

+    -1
```

```
z                           
+    1-1

+    -0
```

`showbreak` が2文字以上だと `<C-A>`, `<C-X>` しても変化しません。

**Comment by h-east** [comment]
@ichizok Thanks again. さすが分かってらっしゃる:+1:
patch更新しました。(Rev. 3)

**Comment by h-east** [comment]
「Visual選択時の`<C-A>` or `<C-X>`は選択範囲内のみ変化しうる。選択範囲外は変更されない」みたいな仕様にした方が良い気がするんですがどうなんでしょうか？

``` sh
vim -N -u NONE
iz 1<CR>2 3<Esc>gg<C-V>j<C-A>
```

Before

```
z 1
2 3
```

今はpatchの有無に関係なく以下のようになります。(選択範囲外の1行目の後ろの`1`もインクリメントされる)
After(Actual)

```
z 2
3 3
```

実はこの方が良いんじゃないかと。(2行目の先頭の`2`のみインクリメント)
After(I think)

```
z 1
3 3
```

**Comment by mattn** [comment]
blockwise が 123 の 12 に被ってたりすると面倒そうですね。

**Comment by h-east** [comment]
@mattn もうちょい具体的に書いて貰わないとdiscuss進まないですよ。

**Comment by mattn** [comment]
@h-east 
![](https://gyazo.com/b506e3b37160e5d4ff89cff892de70bb.png)

こういう時にどうするかって意味です。

**Comment by h-east** [comment]
```
-033
104
194
4-56
```

で良いと思います。(`nrformats`がデフォの場合)
今でも基本は選択範囲でなんとかしようとしているはずです。

...っていうのをBram氏とChris.B氏含めてdiscussします。
事前にここでdiscussするかもしれません。

**Comment by h-east** [comment]
```
vim -N -u NONE
i0x123456<Esc>0<C-V>f3<C-A>
```

で

```
0x123466
```

になるのはあかん。選択範囲先頭が`0x`の場合は`vim_str2nr()`の最後の引数を`-2`してあげないといかん。

本当に「Visual選択時の<C-A> or <C-X>は選択範囲内のみ変化しうる。選択範囲外は参照and変更しない」というポリシーにしてその通り動作するpatchを作って仕様を提出します。

あと追加仕様→「桁上りしたり or 桁下がりしたら次回の`gv`もそれに連動する。
こういうこと↓

```
vim -N -u NONE
i90<Esc>0<C-V><C-A>
```

で

```
100
```

になる且つ`gv`したら`10`がvisual選択される。(現verは`1`がvisual選択される)

# 

ポリシー
「Visual選択時の<C-A> or <C-X>は選択範囲内のみ変化しうる。選択範囲外は参照and変更しない」

「こういう場合にポリシー守れないんじゃないの？」って懸念されるパターンがあったらここにガシガシ書いてください。よろしくお願いします。

**Comment by thinca** [comment]
```
vim -N -u NONE
i10<CR>9<ESC><C-v>k<C-a>
```

この場合の `gv` はどうなるのでしょう?

**Comment by h-east** [comment]
@thinca  visual block-wiseの場合の桁上り or 桁下がりの仕様検討お願いします。

**Comment by thinca** [comment]
どうなるべきなのが正しいのか(もしくは便利なのか)、かなり難しいですね…。
「複数行で片方だけ桁上りが発生する」限り、`gv` を調整するのは難しそうな気がしてます。連続で数字を増減させたい場合は `[count]` を使えばいいわけなので、`gv` はいじらなくてもいい気もします。

**Comment by h-east** [comment]
> ポリシー
> 「Visual選択時の<C-A> or <C-X>は選択範囲内のみ変化しうる。選択範囲外は参照and変更しない」

上記に対応したpatch。
https://gist.github.com/h-east/ad3d22c13188de1466d3
(既知の問題: undo した時のカーソル位置が微妙な場合がある)

桁上り/桁下がり とその時の `gv`拡張関連はいじってない。

・「visual block-wise時は選択範囲の範疇でのみ桁上り/桁下がりする」という仕様もありかもしれない。

**Comment by h-east** [comment]
あぁ、上記patchにはvim_devに報告済みの以下のpatchが含まれています。(test以外)
[[patch] Unexpected result of visual blockwise increment, when selected part of hexadecimal.](https://groups.google.com/forum/#!topic/vim_dev/UmC4JPUHn2Y)

**Comment by h-east** [comment]
あー、このpatchダメだ。一旦保留。

**Comment by h-east** [comment]
patch更新。(Rev. 6)
https://gist.github.com/h-east/ad3d22c13188de1466d3

blockwise `<C-A>`/`<C-X>`後のrepeat(`.`)の処理を修正する必要がある。

**Comment by h-east** [comment]
patch更新。(Rev. 7)
https://gist.github.com/h-east/ad3d22c13188de1466d3

修正内容
- blockwise `<C-A>`/`<C-X>`後のカーソル位置がおかしくなることがあるのを修正。
- blockwise `<C-A>`/`<C-X>`後のundoでカーソル位置がおかしくなることがあるのを修正。
- characterwise `<C-A>`/`<C-X>`で最後の行の処理が正しく行われていないのを修正。

既知の問題等
- repeat(`.`)時にカーソル位置がおかしくなることがある。
- repeat(`.`)動作の仕様を明確にする。

**Comment by h-east** [comment]
repeat(`.`)時の動作がおかしいのこのpatch関係ない。Vim 7.4.898 no patchでも変だ。
最初

```
1 23
4 56
```

`ggf2<C-V>jl<C-A>`

```
1 24                " カーソル位置が 2 に移動するのは仕様
4 57
```

`.`

```
1 34                  " 1 25 では？ しかもカーソル位置が1と3の間に移動する
4 67                  " 4 58 では？
```

`nv_addsub()`の`if (visual) { ～ }`の中を調査しよう。

**Comment by ichizok** [comment]
``` diff
--- a/src/normal.c
+++ b/src/normal.c
@@ -3632,7 +3632,7 @@ prep_redo_visual(cap)
        else if (curbuf->b_visual.vi_end.col > curbuf->b_visual.vi_start.col)
        {
            AppendNumberToRedobuff(curbuf->b_visual.vi_end.col
-                                        - curbuf->b_visual.vi_start.col - 1);
+                                        - curbuf->b_visual.vi_start.col);
            AppendCharToRedobuff(' ');
        }
     }
```

例示のケースで確認。
(`make test` passed)

```
1 23
4 56
```

`ggf2<C-V>jl<C-A>`

```
1 24
4 57
```

`.`

```
1 25
4 58
```

`.`

```
1 26
4 59
```

**Comment by h-east** [comment]
@ichizok Thanks! Good timing:+1:
お風呂から:hotsprings:上がって一息ついて今からまさにInvestigationする直前でした。

こちらの確認もOKです。vim_devに投げて頂けるとありがたいです。

本Issueの私のpatchはその辺りもvcol対応しないといけないので別で作業します。

**Comment by ichizok** [comment]
`[count].` がダメですね...

**Comment by ichizok** [comment]
まずはこれだけでも投げたほうがいいでしょうか？

**Comment by h-east** [comment]
`[count]`の数字は`<C-A>`の直前に`AppendNumberToRedobuff()`するようにすればいいんじゃないかな？

**Comment by h-east** [comment]
あっ、ごめん。今のは忘れて下さい。

**Comment by h-east** [comment]
redoバッファ: `<C-V>1j1 1<C-A>`
の状態で`3.`とすると `3<C-V>1j1 1<C-A>`を実行するんですけど、`3<C-V>`が変な!?仕様になっているからですね。`:h ctrl-v`
これはほっといてさっきのpatch投げた方が良いと思います。

**Comment by ichizok** [comment]
https://groups.google.com/d/msg/vim_dev/OdcI-cHv1dw/PXCqc14ODgAJ
投稿しました。

> redoバッファ: <C-V>1j1 1<C-A>
> の状態で3.とすると 3<C-V>1j1 1<C-A>を実行するんですけど、3<C-V>が変な!?仕様になっているからですね。:h ctrl-v

なるほど。やるとしたら dot-repeat の処理自体に手を加えないとダメそうですね。

**Comment by h-east** [comment]
@ichizok ++ お疲れ様です。
最初、patchを「表示」で見ていたら「あれ？ctrlコードがあれ？」ってなったんですが、「ダウンロード」してブラウザで見たら想定通りのpatchでした。:+1:
testdir/test*.in はctrlコード直書き止めたいなぁ。。

**Comment by h-east** [comment]
ichizok さんのpatch、Todo入り。
https://github.com/vim/vim/commit/a0f849ee40cbea3c889345256786b640b0becca2#diff-38d7929bd26d74d92ceddf984bbfc8dbR148

このIssueは`<TAB>`混じりでも正しく動作することを目的としているのでオープン状態を維持します。

**Comment by h-east** [comment]
patch更新。(Rev. 8)
https://gist.github.com/h-east/ad3d22c13188de1466d3

修正内容
- カーソル位置が数字以外の文字の場合にblockwiseおよびcharacterwiseの <C-A>/<C-X>が処理されないのを修正。
- ichizok さんのpatch取り込み。

**Comment by h-east** [comment]
patch更新。(Rev. 9)
repeat(.)時の動作がおかしいのを修正。

一応ソースコードはこれでfixの予定。
`set rightleft` 時の動作がおかしいけどこれは元から。Linux CUI Vimではノーマルモード時の`rightleft`時のカーソル位置がおかしい。この件は別途なんとかする。

いろいろ試して頂けるとSo Happy

**Comment by h-east** [comment]
> `set rightleft` 時の動作がおかしいけどこれは元から。Linux CUI Vimではノーマルモード時の`rightleft`時のカーソル位置がおかしい。この件は別途なんとかする。

:h rileft のBugsに動かないと明記されてた。でも、ちょっと頑張ってみる。

```
o  Does not handle CTRL-A and CTRL-X commands (add and subtract) correctly
   when in rightleft window.
```

#799

**Comment by h-east** [comment]
> でも、ちょっと頑張ってみる。

http://www.sonydna.com/sdna/solution/pr_loc/blog/20131120.html
アラビア語は右から左だけど文中に現れる数字や英語は左から右なのか。。じゃぁ超ムズですやん。すんません。

patch更新。(Rev. 10)
・do_addsub()の既存の中途半端なright-to-left対応を削除。

**Comment by ichizok** [comment]
`vim -u NONE -N`
`i<TAB>10<CR><TAB><Space>0<ESC>`

```
<TAB>10
<TAB> 0
```

`<C-V>kh<C-A>`

```
<TAB>11
<TAB> 0
```

2行目がインクリメントされません。

**Comment by ichizok** [comment]
test_increment が失敗します (Test17)

**Comment by h-east** [comment]
@ichizok 指摘ありがとうございます。

patch更新。(Rev. 11)
・TEST ALL DONE。
・prep_redo_visual()をvcol対応(その2)
・ちょっとRefactor

既知の問題
・TAB混じりで下から上とか右から左にCharacter-wise、Block-wise選択して<C-A>した後のカーソル位置がおかしい場合があるし、redo(`.`)がおかしい場合がある。
redo情報セットする時に大小関係で入れ替えているけど、入れ替えたらダメな気がしてる。

もうちょっとやってみます。

**Comment by h-east** [comment]
```
$ vim -Nu NONE
```

`i<TAB>123<CR>    456<Esc>F4<C-V>kf3<C-A>`
とか並べ替えたらredo(`.`)無理やん><
(456の前はスペース4つ)

**Comment by h-east** [comment]
バグ発見したのでpatch(Rev. 12)でfix.

```
$ vim -Nu NONE
```

`i<TAB>123<CR>456<Esc>k<C-V>j$<C-A>`

Expect:

```
    124
457
```

Actual:

```
    123
457
```

**Comment by h-east** [comment]
patch更新。(Rev. 14)
もろもろ直した。
redo(`.`)以外でおかしいところあったら指摘下さい。

## 

・visual<C-A>/<C-X>のredo(`.`)は基本的に`gv`して再<C-A>/<C-X>する事 っていうのをhelpに書くのがいいと思う。
・`prep_redo_visual()`の`VIsual_mode == Ctrl_V`の部分はvcol対応が必要かも。
・そろそろNew style test書こう。

**Comment by h-east** [comment]
patch更新。(Rev. 15)
- test_incrementをNew style testで書き換えた。(まずは既存のtest項目を書き換えたのみ。test項目追加は未だ)

**Comment by h-east** [comment]
patch更新。(Rev. 16)
https://gist.github.com/h-east/ad3d22c13188de1466d3
- vcol対応(本issue)関連のtestを6つほど追加。

**Comment by h-east** [comment]
patch更新。(Rev. 17)  Release Candidate Patch
- redo(`.`)もvcol対応。

但し、blockwise-visualでblock選択順が左上→右下ではない、かつ、選択範囲に<TAB>と<SPACE>混在している場合のredo(`.`)は正しく動かない事がある。仕様的に無理だと思う。
これは後でhelpに追記する予定。

**Comment by h-east** [comment]
勢いそのままにrefactorしたpatchをvim_devに送っちゃった。
https://groups.google.com/d/msg/vim_dev/rrTPmy_0OGA/BvbIq-cnAwAJ

**Comment by h-east** [comment]
TODO:
op_addsub()でoap->line_countではなくdid_countを用意してそれを参照するようにする。

**Comment by mattn** [comment]
パッチがでかすぎて敬遠されないかちょっと心配。

**Comment by h-east** [comment]
https://github.com/vim-jp/issues/issues/752#issuecomment-150778902 のichizokさんのpatchやっと取り込まれました。:+1:
Patch 7.4.1084
https://groups.google.com/d/topic/vim_dev/OZcF6mBD9Zg/discussion

**Comment by h-east** [comment]
https://github.com/vim-jp/issues/issues/752#issuecomment-169359124 のpatchを小分けにしたpatchを作成し、最終的に全部取り込まれました。:+1:

Patch 7.4.1071
https://groups.google.com/d/topic/vim_dev/p6IAS6bPFDU/discussion

Patch 7.4.1072
https://groups.google.com/d/topic/vim_dev/_K0eQkIB5aY/discussion

Patch 7.4.1076
https://groups.google.com/d/topic/vim_dev/TOHFHDxek34/discussion

Patch 7.4.1087
https://groups.google.com/d/topic/vim_dev/XiAYqZwUIK0/discussion

**Comment by mattn** [comment]
:+1:

**Comment by sgur** [comment]
すごい！そしてお疲れ様でした！！ :+1:

**Comment by h-east** [comment]
Thanks!

早速、Normal modeの<C-A>のredo(.)が効かない(redo-bufferをセットしていない)バグが発見されたので修正しました:sweat:
https://groups.google.com/d/topic/vim_dev/2Dhf_y57cZM/discussion

**Comment by h-east** [comment]
上のコメントのバグ、patch出ました。
Patch 7.4.1089
https://groups.google.com/d/topic/vim_dev/pOH2rZ7NMg4/discussion
