### ISSUE TITLE
css fileで"rebeccapurple"がハイライトされるようにする

### ISSUE THREAD

**Issue by KiYugadgeter** [vim-jp/issues#753]
Firefox, Chrome, Safariで既に実装されているようです。(IE, Edgeは未確認)
[本の虫: rebeccapurpleがCSS 4 colorに提案された経緯](http://cpplover.blogspot.jp/2014/06/rebeccapurplecss-4-color.html)によるとCSS 4 colorにもなっているようです。

**Comment by crazymaster** [comment]
[CSS Color Module Level 4](https://drafts.csswg.org/css-color/)自体はまだDraft段階なので、
ハイライトを入れるのは時期的には微妙ですね。

CSS Color Module Level 4対応に向けた準備としてメンテナに提案してみてもいいかもしれませんね。
https://github.com/JulesWang/css.vim

**Comment by crazymaster** [comment]
ハイライトが入ったので閉じます。
https://github.com/JulesWang/css.vim/issues/57
