### ISSUE TITLE
Lua ファイル中で elseif が = によって正常にインデントされない

### ISSUE THREAD

**Issue by popkirby** [vim-jp/issues#754]
vimrc_test:

``` vim
set nocompatible
filetype plugin indent on
```

test.lua:

``` lua
if foo then
bar
elseif foofoo then
barbar
end
```

再現手順: 
1. `vim -u vimrc_test -i NONE test.lua`
2. `=G`

期待する結果:

``` lua
if foo then
        bar
elseif foofoo then
        barbar
end
```

実際の結果:

``` lua
if foo then
        bar
        elseif foofoo then
                barbar
        end
```

Mac OS X 10.10.4 + iTerm 2.1.1 + Vim 7.4.826 で確認しました。
おそらく以下の変更で治ると思います。

``` diff
diff --git a/indent/lua.vim.orig b/indent/lua.vim
index 5f049d4..393994c 100644
--- a/indent/lua.vim.orig
+++ b/indent/lua.vim
@@ -54,7 +54,7 @@ function! GetLuaIndent()

   " Subtract a 'shiftwidth' on end, else (and elseif), until and '}'
   " This is the part that requires 'indentkeys'.
-  let midx = match(getline(v:lnum), '^\s*\%(end\>\|else\>\|until\>\|}\)')
+  let midx = match(getline(v:lnum), '^\s*\%(end\>\|else\>\|elseif\>\|until\>\|}\)')
   if midx != -1 && synIDattr(synID(v:lnum, midx + 1, 1), "name") != "luaComment"
     let ind = ind - &shiftwidth
   endif
```

**Comment by mattn** [comment]
ありがとうございます。

https://github.com/vim-jp/vim/blob/master/runtime/indent/lua.vim#L3-L4

現在のメンテナは Marcus Aurelius Farias 氏、github を探してみましたが見当たらないのでメールでのやり取りになりそうです。パッチの中身は良さそうなのでもし @popkirby さんがコントリビュートされるのであれば vim_dev に送って頂けたらと思います。その際、上記のリンクにある Marcus Aurelius Farias 氏のメアドにCCして頂ければと思います。※あとニックネームは推奨されてなかったりしますのでその辺、公開でも良ければになります。
もし代行してよろしいならばこちらでさせて頂きます。

**Comment by k-takata** [comment]
リンク: [patch] fixed "elseif" indentation problem with Lua
https://groups.google.com/d/topic/vim_dev/uXHoW2eXdgs/discussion

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/acb4f221c715a333f4c49a2235a8006c6ac6e4d5
直ったようです。
