### ISSUE TITLE
mapをCtrl+Shift+Bのような登録はできないでしょうか？

### ISSUE THREAD

**Issue by CARBO-Nara-CTP** [vim-jp/issues#756]
いつもWindows上でメモ帳の代わりにgVimを使わさせて頂いています。
感謝感謝です。

さて、本題です。
Windows 8.1 32bitでvim74-kaoriya-win32-20150728.zipのgVimを使っています。
_vimrc内で以下のように設定しています。

`map <C-S-B> :!javac %<CR>m`

設定ファイルエラーは発生しませんが、実際にmapされたのは

 `<C-B>         :!javac %<CR>`

です。
Shiftが認識されていません。

Ctrl+Bはスクロールコマンドとバッティングするので避けたいのですが、Bを別の文字に変えたくもありません（Visual Studioと同じにしたいため）。
何か手立てはないでしょうか？

以上、よろしくお願いします。

**Comment by ynkdir** [comment]
たぶん Vim の仕様なのでなんともならないです。

ワークアラウンドでよければ例えばこういう DLL を用意して

``` c
// cl /LD getkeystate.c user32.lib
#include <windows.h>
__declspec(dllexport) int getkeystate(int key) {
    return GetKeyState(key);
}
```

こんな感じとか

``` vim
nnoremap <expr> <C-B> CtrlShiftB()

function CtrlShiftB()
  if GetKeyState(s:VK_LSHIFT) || GetKeyState(s:VK_RSHIFT)
    " <C-S-B>
    return ":!javac %\<CR>"
  else
    " <C-B>
    return "\<C-B>"
  endif
endfunction

let s:VK_LSHIFT = 0xA0
let s:VK_RSHIFT = 0xA1

function GetKeyState(key)
  let r = libcallnr('/path/to/getkeystate.dll', 'getkeystate', a:key)
  return !!and(r, 0x8000)
endfunction
```

CUI の vim.exe だと動かないですが。(vim が ctrl-shift-b を認識できてない)

**Comment by h-east** [comment]
もしくはNeovim使うかですね。

**Comment by ynkdir** [comment]
> CUI の vim.exe だと動かないですが。(vim が ctrl-shift-b を認識できてない)

認識できてないことはなかった。ただしうまくハンドルできてない。

**Comment by DeaR** [comment]
`map <S-^B> :!javac %<CR>m`でmapする事は出来ました(`^B`は`<C-Q><C-B>`で入力)
但し、7.4.798+kaoriya windows7(x64)で
vim.exeでは実際に`<C-S-B>`の入力で認識しましたが
gvim.exeでは認識しませんでした(`<C-B>`が反応する)

ちなみに`map`で一覧表示するとlhsは`<C-S-B>`と表示されてました

**Comment by ynkdir** [comment]
>  `map <S-^B> :!javac %<CR>m` でmapする事は出来ました( `^B は <C-Q><C-B>` で入力)

なるほど

**Comment by ynkdir** [comment]
> let s:VK_LSHIFT = 0xA0
> let s:VK_RSHIFT = 0xA1

let s:VK_SHIFT = 0x10

でよかった

**Comment by CARBO-Nara-CTP** [comment]
ynkdirさん

vimの仕様なんですね。自作dllは極力使いたくないのですが、最悪教えて頂いた方法でdll作ってみます。
ありがとうございます。

h-eastさん

Neovimというのがあるのは初めて知りました。
しかし、ちょっと敷居が高そうですね。

DeaRさん

> map <S-^B> :!javac %<CR>m でmapする事は出来ました( ^B は <C-Q><C-B> で入力)
> おぉ！！
> 確かにきちんとmapは出来ているっぽいですが、おっしゃる通り、gVimでは動作せず、Vimでは動作するのですが、コンパイル画面がもとの画面の混ざって残念な感じでした。
> あと、Windows上ではgVimしか使ったことがなかったのですが、Windows側のクリップボードの使い方がわかりませんでした。おそらく使えないのかな？
> gVimだとメニューから使えたので、重宝していたのですが。

みなさま

本家の掲示板ももう少しあさってみようと思います。
恐らく同じ希望を持った方がいるでしょうから。
本家Vimの方針で対応しないという結論がすでに出ているかもですが...
そうしたらynkdirさんのdll自作で対応してみます。

何か情報見つけましたらこちらにも再度ポストして情報共有いたします。

ありがとうございました。

**Comment by ynkdir** [comment]
gvim でも `map <S-^B> ...` と書けるやつ

https://gist.github.com/ynkdir/17e5c0bcbbc5041b5409

**Comment by ynkdir** [comment]
仕様かどうかはよくわからずに言ってしまいました。すみません。

**Comment by DeaR** [comment]
余談ですがAlt+Ctrl+BやAlt+Ctrl+Shift+Bも
`<M-^B>` `<M-S-^B>`とやるとmapは出来ますがvim.exeでも反応しませんでした
ですが、feedkeysを使うと反応しているので(mapが出来てる時点で当然といえば当然な気はしますが)
@ynkdir さんのdllと同様の手段で可能なのではないかとは思います

**Comment by Shougo** [comment]
> Neovimというのがあるのは初めて知りました。
> しかし、ちょっと敷居が高そうですね。

@CARBO-Nara-CTP 残念ながら、neovim の Windows 対応は現在作業中なので、
実用できる状態ではありません。
@CARBO-Nara-CTP さんの環境で Vim の代わりに neovim を使うことはできないと思います。

**Comment by CARBO-Nara-CTP** [comment]
@ynkdir さん

すごい！！フルバージョン作ってくださったんですね。
ありがとうございます。
明日さっそく試してみます。

@DeaR さん

設定できるのに反応してくれないっていうのは、なんだかなぁって感じですね。

@Shougo さん

なるほど、Neovimはまだ発展途上なのですね。

みなさん、
ちなみにvim.orgに行って見ましたが、githubに移行予定ということで、新たなissueを立てることが禁止されていました。なので、移行が完了したらissueを立てて対応してもらおうかと思っています。
なお、検索した限りでは困っている人がいないっぽいのと、mapの例で`<C-S-ほにゃらら>`を挙げている人も数人いて、ちょっと困惑です。

**Comment by Shougo** [comment]
@CARBO-Nara-CTP 今なら vim_dev にメールを出すのがよいと思います。

**Comment by CARBO-Nara-CTP** [comment]
@Shougo さん、

別スレ（#757）を見るとかなり昔に話が上がっているみたいでした。

@ynkdir さん、

コンパイルできたのですが、各ファイルの配置がわかりませんでした。
gVim.exeと同じフォルダーにdllを、vim74直下にvimファイルを置いてみたのですが、動作せず。
autoloadフォルダーにも移動してみましたが、同様でした。

どこかにvimファイルを読み込ませるような指定がいるのでしょうか？

初心者レベルのご質問で申し訳ないです。

**Comment by mattn** [comment]
@CARBO-Nara-CTP ctrlshiftkey.vim と同じ位置に置きます。

**Comment by CARBO-Nara-CTP** [comment]
@mattn さん

ご教授ありがとうございます。
しかし、やはり動作しませんでした。
試した場所は以下の3か所で、dll,vimの両ファイルとも同じ場所に配置しました。
・gvim.exeと同じ場所
・vim74配下
・vim74\autoload配下

ちなみにmapは @DeaR さんに教えて頂いた、
`map <S-^B> :!javac %<CR>`
で行っています。

**Comment by DeaR** [comment]
@CARBO-Nara-CTP ~/vimfiles/plugin 下、もしくは_vimrcから直接sourceして下さい

**Comment by CARBO-Nara-CTP** [comment]
@DeaR さん

ご教授ありがとうございます。
少し進歩しましたが、動きませんでした。

~/vimfiles/plugin配下に2つのファイルを配置し、gVimを実行したところ起動時に以下のエラーが出ます。

`function <SNR>13_init の処理中にエラーが検出されました:`
`行     2:`
`ctrlshiftkey_load: error`

これはもしかして、dll作成がうまくいってないという線もあるのでしょうか？

**Comment by ynkdir** [comment]
もしかしてホームフォルダが日本語で、vim の 'encoding' が utf-8 ですか？

これで動くと思います。

``` diff
diff --git a/ctrlshiftkey.vim b/ctrlshiftkey.vim
index 34f3af4..555303e 100644
--- a/ctrlshiftkey.vim
+++ b/ctrlshiftkey.vim
@@ -4,6 +4,7 @@ if !has('gui_running')
 endif

 let s:dll = expand('<sfile>:p:h') . '\ctrlshiftkey.dll'
+let s:dll = iconv(s:dll, &encoding, 'default')

 function! s:init()
   if libcall(s:dll, 'ctrlshiftkey_load', s:dll) != 'ok'
```

**Comment by CARBO-Nara-CTP** [comment]
@ynkdir さん、

度々すみません。
いえ、ホームディレクトリのフルパスの中のどこにも日本語は含まれていませんし、エンコーディングも指定していません。
もう帰宅してしまったので、確認はできませんが...

ロードでエラーが出ているのはもしかしてNTFSのアクセス権限とかも関係するのでしょうか？
特にデフォルトからいじってはいないのですが...
gVimを管理者権限で起動すると上手くいくとか...

いずれにせよ、来週また試してみます。

**Comment by ynkdir** [comment]
ctrlshiftkey.dll のコンパイルは `cl /LD ctrlshiftkey.c user32.lib` をコマンドラインで手打ちですか？それとも Visual Studio かなにかでやりましたか。

**Comment by CARBO-Nara-CTP** [comment]
Visual studio 2015でc++のdllのからのプロジェクトをctrlshiftkeyという名前で作成してからソースを取り込んでx86リリースモードでコンパイルして出来たdllを使いました。

**Comment by ynkdir** [comment]
もしかしたらプロジェクトの設定で UNICODE が定義されていて LoadLibraryW を呼び出しちゃってるのかもしれません。たぶんコンパイル時に warning がたくさん出てると思います。

**Comment by CARBO-Nara-CTP** [comment]
なるほどです。
家に環境ないので、月曜日にまた確認してみます。

**Comment by CARBO-Nara-CTP** [comment]
@ynkdir さん

度々申し訳ありません。
仰る通り、UNICODEが定義されていました。そちらを設定なしにしましたところ、Ctrl+Shift+Bでdllを呼び出せるようにはなりましたが、gVim自体が落ちてしまいます。

Debugモードでコンパイルし、プロセスアタッチしてみたところ、55行目のSendMessageでこけているようです。
hVimServerとhwndの値がどちらもunusedで「メモリを読み取れません」と表示されているのですが、関係ありますでしょうか？

**Comment by CARBO-Nara-CTP** [comment]
一応エラー時に画面キャプチャを取りました。
![default](https://cloud.githubusercontent.com/assets/13867249/9432277/88194460-4a5b-11e5-891e-cbaf2fb85073.JPG)

**Comment by CARBO-Nara-CTP** [comment]
よくよくエラーを見てみると、bufの差してる静的領域に書き込もうとしてエラーになってます？
bufを動的領域にすればOKですか？
ちょっとやってみます。
C言語忘れかけてますが...
(^_^;)

**Comment by CARBO-Nara-CTP** [comment]
動くようになりました。
string.hをincludeして、bufの定義を以下のように変えました。

`char *strtemp = "feedkeys(\"\\<S-\x02>\")";`
`int len = strlen(strtemp) + 1;`
`char *buf = (char *)malloc(len);`
`strcpy_s(buf, len, strtemp);`

@ynkdir さん
ほんとにほんとにありがとうございました。
_(._.)_
