### ISSUE TITLE
CTRL-A 及び CTRL-X が '[, '] マークを変更しない

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#758]
テキストの数字をインクリメント・デクリメントする `<C-a>`、`<C-x>` コマンドはヘルプの change.txt で解説されており、直感的にも編集行為だと感じるのですが直近の編集位置を示す `'[`, `']` マークを更新しません。

困るというほどではないのですが、更新したほうが妥当に感じます。

**Comment by ynkdir** [comment]
ありがとうございます。
報告しました。
https://groups.google.com/d/msg/vim_dev/IsAFNykCINE/ZC0jnmxYBgAJ

**Comment by machakann** [comment]
ありがとうございます。パッチを当ててみましたが期待通りに動いています。

**Comment by h-east** [comment]
todolisted.
https://github.com/vim/vim/commit/88774fdd23f08355297bb8cda78856859051d3c7#diff-38d7929bd26d74d92ceddf984bbfc8dbR183

**Comment by h-east** [comment]
Patch 7.4.1085
https://groups.google.com/d/msg/vim_dev/wtcpTgS8oLA/ONXPLiVvBAAJ
