### ISSUE TITLE
scriptタグの中のJavaScriptのハイライトが消える

### ISSUE THREAD

**Issue by KiYugadgeter** [vim-jp/issues#760]
htmlのscriptタグのjsのハイライトが消えることがあります。

scriptタグ内の行数がとても多い場合に、ファイル上部の行から`G`などを使って一気に下に移動すると起こるようです。

https://gist.github.com/Kimura1/4869192b9371f224a300
上のコードで発生を確認しました。
このコードをvimで開き`G`で最後の行に移動するとscriptタグ内のハイライトが消えます。

**Comment by h-east** [comment]
mattnさんが2007年にブログで対処方法を書いてます。
[意外と知られていないvimのtips(開発に便利な設定)](http://mattn.kaoriya.net/software/vim/20070821175457.htm)
`長いブロックや複数ブロックがある言語の開発` の部分。

`html`ファイルも対象にしてあげればOKです。

``` vim
autocmd FileType html,jsp,asp,php,xml,perl syntax sync minlines=500 maxlines=1000
```

**Comment by KiYugadgeter** [comment]
少し気になったのですが、このbugは2007年時点でわかっているのに、なぜ、未だにfixされないのでしょうか?

**Comment by h-east** [comment]
これはbugではないです。仕様です。処理時間とのトレードオフでデフォルト値は`minlines=10`、`maxlines=100`になっています。
「これが少ないと思ったら変更してね」ということが`:h :syn-sync-maxlines`に書かれています。

**Comment by koron** [comment]
補足ですが、この値が大き過ぎるとvimの動作が著しく遅くなるので、控えめな数字になっています。
どの程度まで実用に耐えるかはユーザーの利用環境次第ですので、
デフォルトを大きくするのは現実的な選択肢とはなりません。

**Comment by h-east** [comment]
@Kimura1 本Issue、閉じてもよろしいでしょうか？

**Comment by KiYugadgeter** [comment]
回答ありがとうございました。
closeします。

**Comment by h-east** [comment]
@Kimura1 :+1: また何かありましたらご利用下さい。
