### ISSUE TITLE
レポジトリの変更についての報告

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#761]
本家vimがgithubに移行したことに伴い、レポジトリについて幾つか作業をしましたので報告いたします。
報告内容は大きく分けて3つです。
1.   旧 vim-jp/vim は [vim-jp/vim-obsoleted](https://github.com/vim-jp/vim-obsoleted) に名前を変更しました。
   
   code.google.com からのミラーリングは、当然停止しています。
   近い将来、削除する予定です。
2.   vim-jp/vim-ci は自動更新を停止し、各種webhookやserviceを削除しました。
   
   上記のミラーリング停止に伴い、こちらの自動更新は意味のないものになりました。
   相談した後になるとは思いますが、こちらも削除するのが好ましいでしょう。
3.   CI 実行用に新たに [vim-jp/vim](https://github.com/vim-jp/vim) を作成しました。
   
   このレポジトリは vim/vim からのクローンで、
   本家に変更があれば自動的に master+ci と master へ反映されます。
   詳しくは [wiki](https://github.com/vim-jp/vim/wiki) などを参照してください。
   足りない設定や説明がありましたら、適宜追加するか、指摘してもらえると助かります。
   こちらの寿命は「本家 vim/vim が CI を有効化するまで」となります。

なお vim-jp/vim の master+ci は @k-takata さんの [enable-ci](https://github.com/vim/vim/pull/401) を元にしています。
あらためてありがとうございました。 :bow:

**Comment by koron** [comment]
最後に、この issue は 2015/09末 に閉じてください。

**Comment by 0xBADDCAFE** [comment]
closable?
