### ISSUE TITLE
is# のパースが 'isident' の影響を受けて失敗することがある

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#762]
https://github.com/vim/vim/blob/d43f0951bca162d4491d57df9277b5dbc462944f/src/eval.c#L4434

`is#` や `is?` をパースする際に、ここで `vim_isIDc` を使用していて、これは `'isident'` の値を参照するので、例えば`'isident'` に `#` が含まれていると `is#` が変数として認識されてしまい、パースに失敗します。

**Comment by mattn** [comment]
GJ

On 8/29/15, thinca notifications@github.com wrote:

> https://github.com/vim/vim/blob/d43f0951bca162d4491d57df9277b5dbc462944f/src/eval.c#L4434
> 
> `is#` や `is?` をパースする際に、ここで `vim_isIDc` を使用していて、これは `'isident'`
> の値を参照するので、例えば`'isident'` に `#` が含まれていると `is#` が変数として認識されてしまい、パースに失敗します。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/762

## 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
``` diff
From 4fbc8908cdda21a88c2d25ac71f0cd2b448959c1 Mon Sep 17 00:00:00 2001
From: Yasuhiro Matsumoto <mattn.jp@gmail.com>
Date: Sun, 30 Aug 2015 08:28:20 +0900
Subject: [PATCH] don't check with ident symbols

---
 src/eval.c | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/src/eval.c b/src/eval.c
index 3650c34..4070b0f 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -4429,9 +4429,11 @@ eval4(arg, rettv, evaluate)
            break;
    case 'i':   if (p[1] == 's')
            {
+           int c;
            if (p[2] == 'n' && p[3] == 'o' && p[4] == 't')
                len = 5;
-           if (!vim_isIDc(p[len]))
+           c = p[len];
+           if (!isalnum(c) && c != '_')
            {
                type = len == 2 ? TYPE_EQUAL : TYPE_NEQUAL;
                type_is = TRUE;
```

もう1か所、環境変数 `$FOO_BAR` を判定している箇所がありそちらも `vim_isIDc` を使ってますが、そちらはOSによって異なる環境変数名があり得るので残しました。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/I09LH4d-PLw

**Comment by thinca** [comment]
@mattn ++

> 環境変数 $FOO_BAR を判定している箇所

これは一応 help にも明記されています。
http://vim-jp.org/vimdoc-ja/options.html#%27isident%27

> Identifier に使われる文字を指定する。Identifier は、環境変数の認識とオ
> プション 'define' のマッチしたところの後に使われる。

ただ、`'define'` の方だけを変えたいのに環境変数の認識も変わってしまうのは正直不便そうな予感はします…。(滅多に変えないでしょうけど)

**Comment by crazymaster** [comment]
Patch 7.4.844
https://groups.google.com/d/msg/vim_dev/GzovINleaa8/JxfZl11GBAAJ
