### ISSUE TITLE
FilterWritePre イベントが発生しない場合がある

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#765]
何らかのファイルを 2 つ開き、たとえば
au FilterWritePre \* if &diff | set nu | endif
と定義しておきます。
そこで
windo diffthis
や
windo set diff
や
windo let &diff = 1
を実行すると diff モードになり、FilterWritePre イベントが発生して set nu が実行されますが、
call setwinvar(1, "&diff", 1)
call setwinvar(2, "&diff", 1)
を実行すると diff モードになりますが、イベントは発生しません。
これは setwinvar() の仕様でしょうか?
vim7.4.843 と vim7.3.1314 で再現します。

**Comment by mattn** [comment]
```
windo let &diff = 1
```

では発火しませんね。

**Comment by mattn** [comment]
```
windo set diff
```

も発火しません。

**Comment by mattn** [comment]
```
windo diffthis
```

は発火しました。

**Comment by h-east** [comment]
@ZBryce さん報告の通りの挙動になることを確認しました。(Vim 7.4.861 on fedora21)

指定されたwindowのオプションやwindowローカル変数の値を取得したり設定したりする場合(`settabwinvar()`, `setwinvar()`, `gettabwinvar()`, `getwinvar()`)は、そのwindowを一時的にカレントwindowにしてから処理をおこない、元のwindowに戻すということをVim内部でしています。
その一時的にカレントwindowを変更している最中はautocommandイベントが禁止されています。
(window関連の値を取得/参照するだけで`WinLeave`や`WinEnter`等のイベントが発生するのは微妙だから？)

各`settabwinvar()`, `setwinvar()`, `gettabwinvar()`, `getwinvar()`のヘルプにautocommandイベント禁止だよということは書いておいたほうが良い気がします。

あと、`winnr`が`0`の時やカレントwindowの番号だった場合はautocommandイベント禁止しなくても良いかもと思いました。少なくとも`WinLeave`や`WinEnter`イベントは発生しないので。要検討です。

**Comment by rickhowe** [comment]
ありがとうございます。他の window の変数を操作する場合はイベントがブロックされるかも？と思っていましたが、
windo call setwinvar(winnr(), "&diff", 1)
でも発生しないので、自分の window からでもブロックされていたので構想がよくわかりませんでした。
この動きは setwinvar() の仕様ということで了解です。
ただ、option の値を変更することで発生する FileType、Syntax、EncodingChanged イベントなども、同じように setwinvar() では発生しないようですので、こちらのほうが実害があるかもしれません。できれば、vim 内部で window を切り替える直前直後にイベントのブロックを切り替え、変数の操作時は発生するようにしたほうが一貫性があるように思えます。

**Comment by h-east** [comment]
autocommandイベントトリガ辺りのポリシーはよく分かんないです。
#62 

> できれば、vim 内部で window を切り替える直前直後にイベントのブロックを切り替え、変数の操作時は発生するようにしたほうが一貫性があるように思えます。

とりまpatch書いてみました。
https://gist.github.com/h-east/9b0764b5c30e1583466b

あと、対象がカレントwindowの場合はautocommandイベントを禁止しないようにするpatch
https://gist.github.com/h-east/a26febcb48eb868b0676

**Comment by h-east** [comment]
vim_devに関連する話題が出たので後者のpatchをsuggestしてみた。
https://groups.google.com/d/topic/vim_dev/JQPWhn8DeRE/discussion

**Comment by h-east** [comment]
settabwinvar(), setwinvar(), gettabwinvar(), getwinvar() の対象がカレントwindow (and カレントtab-page)の場合はautocommandをブロックしないpatchが取り込まれました。

Patch 7.4.888
https://groups.google.com/d/msg/vim_dev/UlPl5EXOSv8/4wWG7RuMBAAJ

@ZBryce Issue登録ありがとうございました。patchを確認いただき問題があればReopenお願いします。
