### ISSUE TITLE
外部コマンドを実行した際のプロンプトの開始位置が乱れる

### ISSUE THREAD

**Issue by ghost** [vim-jp/issues#766]
#732 からの派生です。

```
vim -u NONE
!hoge
:q!
```

と入力した際、特に !hoge (エラーになるコマンドなら何でも可) の実行時に、コンソールバッファ内のカーソル位置が先頭方向に巻き戻ってしまい、結果として画面が乱れます。

**Comment by ghost** [comment]
おそらくはこれで解決できていると思われます。
Vim が実行直後に保存した「Vim 実行前のバッファ」のカーソル位置を移植しています。
カーソルの形状を変える Win32 関数に対して適切なカーソル位置を与えなければならないのですが、この位置情報が g_coord (Vim 実行後の画面のカーソル位置) であったことが原因だったかと思います。

私のあいかわらずですが、おそらく何か不足している気がしますし、過去も実際その傾向がありましたので、数日寝かせて様子を見ることにします。

``` diff
diff --git a/src/os_win32.c b/src/os_win32.c
index 7695e93..94571ad 100644
--- a/src/os_win32.c
+++ b/src/os_win32.c
@@ -228,6 +228,8 @@ static int win32_getattrs(char_u *name);
 static int win32_setattrs(char_u *name, int attrs);
 static int win32_set_archive(char_u *name);

+static void set_console_cursor_position(void);
+
 #ifndef FEAT_GUI_W32
 static int suppress_winsize = 1;   /* don't fiddle with console */
 #endif
@@ -1392,7 +1394,7 @@ mch_set_cursor_shape(int thickness)

     SetConsoleCursorInfo(g_hConOut, &ConsoleCursorInfo);
     if (s_cursor_visible)
-   SetConsoleCursorPosition(g_hConOut, g_coord);
+   set_console_cursor_position();
 }

     void
@@ -6702,3 +6704,12 @@ fix_arg_enc(void)
     set_alist_count();
 }
 #endif
+
+    static void
+set_console_cursor_position(void)
+{
+    CONSOLE_SCREEN_BUFFER_INFO i;
+
+    GetConsoleScreenBufferInfo(g_cbNonTermcap.handle, &i);
+    SetConsoleCursorPosition(g_hConOut, i.dwCursorPosition);
+}
```

**Comment by ghost** [comment]
あっ寝ぼけてる…
カーソルの形状とはまた別の話で、形状をセットしたあとにカーソルを明示的に表示する際、カーソルの正しい位置も必要になるということでした。
この位置情報をどこかから拾ってこないといけないので、試した結果として、最終的に g_cbNonTermcap から引っ張ることにしたという経緯です。

**Comment by ynkdir** [comment]
ありがとうございます。直りました。

特に動作がおかしくなったとかではないんですが mch_set_cursor_shape() は例えば挿入モードに入ったときとかにも呼ばれてると思うので大丈夫なのかなと気になりました。

**Comment by ghost** [comment]
今回 g_hConOut にカーソル位置の情報を無区別に渡していますが、元のコードでの g_coord の内容は呼び出し元となるカーソルアップデートのロジックでは問われていないように思うので(直後に位置を設定しなおしているようなのでここは .X=0,.Y=0でもいいはず)、大丈夫かと思います。
一つのルーチンに二つのこと(アップデート、ポジションセット)をさせようとしているけれども、本来的にはこの二つはしっかりと二つの別個のルーチンで行うべきことなんだと思います。

**Comment by ynkdir** [comment]
了解です。ありがとうございます。

**Comment by ghost** [comment]
vim_dev に持ち出しました。
https://groups.google.com/d/msg/vim_dev/zul_u1oYm50/W9KXkewABwAJ

**Comment by ynkdir** [comment]
:+1:

**Comment by mattn** [comment]
@koron @k-takata 
このパッチは、CreateConsoleScreenBuffer を使う様になった事で必要なくなった？それともまだ必要？

**Comment by k-takata** [comment]
逆で、CreateConsoleScreenBuffer を使う際にバグっちゃったんだと思います。今試したところ、カーソル位置が変になってしまったので、必要と思われます。

**Comment by mattn** [comment]
@k-takata 

https://groups.google.com/forum/#!topic/vim_dev/zul_u1oYm50

Bram から質問来てますね。具体的にどんな風に変になります？

**Comment by k-takata** [comment]
最初の手順に書いてあるとおりですね。
コマンドプロンプトに何十行か文字を表示した状態でvim.exeを起動し、`:!hoge` を実行すると、カーソルが1行目に戻ってしまいます。vimを終了すると、プロンプトが1行目に表示されます。

**Comment by mattn** [comment]
僕の環境だと戻らないすね。。。

**Comment by koron** [comment]
関係あるかわかりませんが
バッチからVimのテスト実行して終わったら echo すると、
なんか描画結果がおかしいので…
後で試してみます。

![result](https://cloud.githubusercontent.com/assets/468368/10182869/6bd5f322-6764-11e5-8f13-be8ee55c47d8.png)

`echo` している内容が、nmake の出力にかぶるようになってしまってるんですよね…。

```
----
SUCCEEDED: 04-etst-asis.bat
```

バッチは単体では完結してないんですが、一応貼っておきます。
なお [完全なソースはココ](https://github.com/koron/vim-kaoriya/tree/master/build/msvc)

``` bat
@ECHO OFF

SET DATE_VER=%date:~-10,4%%date:~-5,2%%date:~-2,2%
SET CURDIR=%~dp0
SET VIMDIR=%~dp0..\..\vim

REM Build and test pure vim.
CD "%VIMDIR%"
CALL :TEST_RUN %CURDIR%target\test-%DATE_VER%-asis.log
IF %ERRORLEVEL% NEQ 0 GOTO :FAILURE

REM Test end.
CD "%CURDIR%"

:SUCCESS
ECHO ----
ECHO SUCCEEDED: %~nx0
PAUSE
EXIT /B 0

:FAILURE
ECHO ----
ECHO FAILED: %~nx0
PAUSE
EXIT /B %ERRORLEVEL%

REM ========================================================================
REM SUB-ROUTINES

:TEST_RUN
SETLOCAL
CD "%CURDIR%"
CMD /C "%CURDIR%tools\msvc-nmake.bat" amd64 vim-clean vim-build
IF %ERRORLEVEL% NEQ 0 GOTO :TEST_FAILURE
CD "%VIMDIR%\src\testdir"
CMD /C "%CURDIR%tools\msvc-nmake.bat" amd64 -f Make_dos.mak clean win32
IF %ERRORLEVEL% NEQ 0 GOTO :TEST_FAILURE
CMD /C "%CURDIR%tools\msvc-nmake.bat" amd64 -f Make_dos.mak clean
:TEST_SUCCESS
CD "%CURDIR%"
EXIT /B 0
:TEST_FAILURE
SET SAVED_ERRORLEVEL=%ERRORLEVEL%
IF EXIST %VIMDIR%\src\testdir\test.log COPY %VIMDIR%\src\testdir\test.log %1
CD "%CURDIR%"
EXIT /B %SAVED_ERRORLEVEL%
```

**Comment by ynkdir** [comment]
> 関係あるかわかりませんが

私がこの問題に気づいたのも make test でした。
テストの中で rm とかあとなにかあった気がしますがまあ unix コマンドを実行してエラーになってて↑の再現方法と同じことになってます。

**Comment by mattn** [comment]
再現しないって言われてます。

https://groups.google.com/forum/#!topic/vim_dev/zul_u1oYm50

**Comment by ynkdir** [comment]
7.4.902 (revert 7.4.851) でひとまず直ってます。

**Comment by k-takata** [comment]
では、閉じちゃいましょう。
