### ISSUE TITLE
cmap 評価中にgetchar() を呼んで<S-Space><C-Space><C-Tab>等を入力すると全てのマッピングが無効になる。

### ISSUE THREAD

**Issue by LeafCage** [vim-jp/issues#768]
``` vim
function! GetChar() "{{{
  call getchar()
  return "\<Esc>"
endfunction
"}}}
cnoremap <expr><C-t> GetChar()
```

これを `:source` して `<C-t>` で呼んだ `getchar()` 中に `<C-Space>` `<S-Space>` `<C-Tab>` など、`"\x80\xfc"` から始まるキーを入力するとコマンドラインを抜けた後、すべてのキーマッピングがリセットされます。

**Comment by ynkdir** [comment]
ありがとうございます。報告しました。
https://groups.google.com/d/msg/vim_dev/AgpWUGEUybM/__M9sFf1BwAJ

**Comment by ynkdir** [comment]
7.4.870 で修正されました。
https://groups.google.com/d/msg/vim_dev/6b1LKhtG6f0/qdTt4WKaCAAJ
