### ISSUE TITLE
Windows で DYNAMIC_PYTHON=yes かつ DYNAMIC_PYTHON3=no のときビルドに失敗する

### ISSUE THREAD

**Issue by sgur** [vim-jp/issues#769]
最新(v7.4.873) のソースコード、Windows7、VisualStudio 2012 でのビルドで確認しました。

タイトルの通り、 `DYNAMIC_PYTHON=yes` 、 `DYNAMIC_PYTHON3=no` の組み合わせでビルドエラーとなります。

以下はビルドに使用したバッチファイル

``` BatchFile
@setlocal
@set BASEDIR=%CD%
@set VS2012_64_VCVARS="c:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat"
@call %VS2012_64_VCVARS% amd64

cd %BASEDIR%\src
nmake -f make_mvc.mak PYTHON="C:\Python27" PYTHON_VER=27 DYNAMIC_PYTHON=yes  PYTHON3="C:\Python34" PYTHON3_VER=34 DYNAMIC_PYTHON3=no
```

以下がエラーメッセージです。

```
        cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE       -DWINVER=0x0400 -D_WIN32_WINNT=0x0400 /Fo.\ObjCYHAMD64/ /Ox /GL -DNDEBUG  /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_PYTHON -DDYNAMIC_PYTHON  -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DFEAT_BIG /Fd.\ObjCYHAMD64/ /Zi /I "C:\Python34\Include" /I "C:\Python34\PC" if_python3.c
if_python3.c
if_python3.c(835) : error C2065: 'hinstPy3' : undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.
```

確認したところ、エラーになるのは件の組合せのみで、他の場合はビルドエラーになりません。

| DYNAMIC_PYTHON | DYNAMIC_PYTHON3 | 結果 |
| --- | --- | --- |
| yes | yes | OK |
| yes | no | NG |
| no | yes | OK |
| no | no | OK |

おそらく、以下のようなパッチで修正できると思うのですが、なにぶんビルドスイッチの依存関係が追い切れないので、ご確認頂けないでしょうか？

``` diff
--- a/src/if_python3.c  Fri Sep 18 11:11:13 2015 +0900
+++ b/src/if_python3.c  Fri Sep 18 11:12:21 2015 +0900
@@ -828,7 +828,7 @@
     --recurse;
 }

-#if (defined(DYNAMIC_PYTHON) && defined(FEAT_PYTHON)) || defined(PROTO)
+#if (defined(DYNAMIC_PYTHON3) && defined(FEAT_PYTHON)) || defined(PROTO)
     int
 python3_loaded()
 {
```

**Comment by h-east** [comment]
@sgur :+1: 

`python_loaded()`が以下のようになっているので、`python3_loaded()`は @sgur さんの修正で良いように思います。

``` c
#if (defined(DYNAMIC_PYTHON) && defined(FEAT_PYTHON3)) || defined(PROTO)
    int
python_loaded()
{
    return (hinstPython != 0);
}
#endif
```

**Comment by h-east** [comment]
@sgur さんのpatch、自らの検証で正当性が証明されているのでvim_devに投げて問題ないと思います。
もしも、代行をお願いする場合はpatch author名を教えて下さい。

**Comment by sgur** [comment]
遅ればせながら、vim_dev に投稿しました。
リストに表示されたらまたリンクを貼ります。

**Comment by sgur** [comment]
Posted.
https://groups.google.com/forum/#!topic/vim_dev/UnXHS4PmS0E

**Comment by h-east** [comment]
@sgur :+1:

**Comment by mattn** [comment]
関連? https://github.com/vim/vim/commit/094454fa708d3297db744f095cd2b7b155a8b6ad (Patch 7.4.890)

**Comment by h-east** [comment]
`defined(UNIX)`を足されてしまった。これはアカンのちゃう？

**Comment by h-east** [comment]
https://groups.google.com/forum/#!topic/vim_dev/UnXHS4PmS0E

@sgur フォローお願いします。

**Comment by sgur** [comment]
手元でビルドして確認しました。

確かに Patch 7.4.890 の修正でWindowsでビルド可能になりますね。
`+python/dyn` かつ `+python3` でビルドできて
`:py print("Hello")` も `:py3 print("Hello")` もエラーにならないようです。

とりあえず、これで OK ですかねぇ…

**Comment by sgur** [comment]
元々の目的は patch 7.4.890 の修正で達成されましたので、Close します。
