### ISSUE TITLE
remoteを受け付けない仕組み

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#77]
必須ではないと思いますが、今日 [vimgolf](http://vimgolf.com/) というキー操作をgolfしてランキングを楽しむサービスを見ていて、もしかしてこれremoteを使うとインチキ出来たりするんじゃ...と思って試したら、インチキ出来てしまいました。今後vimをアプリケーション連動させるなら **remoteを受け付けない仕組み** って必要かもと今日なんとなく思いました。
例えば

http://vimgolf.com/challenges/4d1db1b8de2f897c2a00014a

であれば @h_east さんの推測では

```
!!c<CR>ZZ
```

で、`c`というプログラムから`~/.vimgolf/put/*.output`を書いてしまうという物です。おそらく6ステップでクリアしている某ヒゲのオジサンはその方法かと思います。
さらに`remote`を使うとステップ0でクリア出来てしまうので、例えば

```
vim --no-remote
```

みたいにリモートを拒否出来れば...と思いました。

もちろん、コマンドレベルやTCPレベルでインチキすればいくらでも可能なのですが、vimgolfとは関係なく、`--no-remote`みたいなオプションあってもいいかなレベルのissueです。

本気でvimgolfみたいな物を考えて行くならば、外部コマンドも発行出来ない様にすべきとは思いましたが、ひとまずremoteについて。

**Comment by thinca** [comment]
仕様かどうかわかりませんが、`vim --servername ""` でできませんか?

> 外部コマンドも発行出来ない様に

制限モードがあります。

`:help restricted-mode`
`vim -Z`

**Comment by mattn** [comment]
おぉ。ひとまずそれでvimgolfにpull-reqしてみます。＆close

**Comment by h-east** [comment]
このissue今気付いた^^;
GJ!

**Comment by h-east** [comment]
Mergeされましたね。
https://github.com/igrigorik/vimgolf/commit/167f8c9be4b0ed44beeac9a2b0da46d539e735bc
