### ISSUE TITLE
windows で shellslash でも :e http://example.com/ をエラーなく開きたい。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#777]
msys2 や cygwin でない windows で shellslash を使うのは自己責任なのですが、いかんせん使いたいものは使いたい訳で、以前 shellescape を直すパッチを蹴られたのでせめて netrw だけでも直したいと思っています。

https://gist.github.com/mattn/0799137eea35ed4e789d

説明するときに、バグを直したとは言わずに「unix tool を使っていない場合の windows 上で shellslash の場合でも netrw を動く様にしたよ」程度で出そうかなと思っています。

**Comment by mattn** [comment]
まぁぶっちゃけ、最近の windows だと / パスセパレータのままでも動いてしまう訳ですが。

```
/windows/system32/notepad
```

XPはダメだけど、Windows10ならこれでもメモ帳起動します。

**Comment by 0xBADDCAFE** [comment]
:+1:

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/1JbJZfZ69Mw

**Comment by h-east** [comment]
:sparkles::sparkles::sparkles::sparkles::sparkles:
:sparkles::seven::seven::seven::sparkles:
:sparkles::sparkles::sparkles::sparkles::sparkles:

**Comment by k-takata** [comment]
> https://groups.google.com/forum/#!topic/vim_dev/1JbJZfZ69Mw

CC: のメールアドレスが間違ってます。'N', 'O', 'S', 'P', 'A', 'M' の各文字を取り除いてください。

**Comment by mattn** [comment]
oops. 再送ed

**Comment by mattn** [comment]
7.4.898
https://groups.google.com/forum/#!topic/vim_dev/MDRCgXAL8m4
