### ISSUE TITLE
windows の iconv.dll/libiconv.dll のほかに libiconv2.dll も読み込んだ方がいいかを検討

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#778]
https://github.com/vim/vim/issues/440

たしかに最近 iconv.dll や libiconv.dll のまま配布している箇所は少ない。
ただし msys2 に至っては iconv.dll でも libiconv.dll でも libiconv2.dll でもなく libiconv-2.dll です。。。

**Comment by k-takata** [comment]
#441 も一緒に検討したいですね。

**Comment by mattn** [comment]
msys2 の intl は libintl-8.dll ですね。今後もバージョン番号が上がっていく可能性を考えると msys2 は捨てたい気もする。。。

**Comment by k-takata** [comment]
そこの番号は、libtoolの`-version-info`オプションで指定した値を元に決まる番号です。

iconvは https://github.com/koron/libiconv/blob/a05b7493aa14b7c8bc2b793f84f65efa03d86bb2/lib/Makefile.in#L51-L53 で、
gettextはhttps://github.com/koron/gettext/blob/a94c69758ea4c56500027896683d6e5e127ac837/gettext-runtime/intl/Makefile.in#L162-L169 で設定されています。

`-version-info`オプションと、その番号の関係については、以前調べたことがあります。 https://github.com/k-takata/Onigmo/issues/37
簡単に言うと、APIに互換が無くなるとそこの番号が変わることになります。

**Comment by k-takata** [comment]
7.4.892
https://groups.google.com/d/topic/vim_dev/b1BZCGNJs8s/discussion
結局、iconv.dll, libiconv.dll, libiconv2.dll, libiconv-2.dll の順に検索する仕様になりました。

**Comment by k-takata** [comment]
さて、libintlの方はどうするか…
