### ISSUE TITLE
if_rubyなどでdynamic loadingする場合のshared libraryのパス

### ISSUE THREAD

**Issue by splhack** [vim-jp/issues#781]
Windows以外で、if_rubyなどでdynamic loadingする場合、dlopenを使ってshared libraryを探すわけですが、configureで指定したshared library path(フルパス、相対パス、ファイル名だけ)以外が使いたいケースがあったりします。

(configureで指定したものがファイル名だけで、同じファイル名を特定のパスから検索させるだけなら、LD_LIBRARY_PATHを指定するだけですが、OS X El Capitanから、デフォルトでLD_LIBRARY_PATH, DYLD_*環境変数が設定できなくなったので、それもできず)

MacVim-KaoriYaでは、以下の様な改造を施して、ユーザーがshared libraryを指定できるようにしているのですが、いかがなものでしょうか。他にもっといい方法があるでしょうか。
https://github.com/splhack/macvim/blob/de48f5b09968c6757d29db53165f556b699cee54/src/if_ruby.c#L679-L681

**Comment by splhack** [comment]
WindowsとMacVim-KaoriYa以外では、まったくdyn使われてない感じですかね...

**Comment by splhack** [comment]
optionにしてみました。doc追加してpull requestしてみます。
https://gist.github.com/splhack/10dab30444c1c7e5ef73

**Comment by splhack** [comment]
https://github.com/vim/vim/pull/452

**Comment by koron** [comment]
1度 load しちゃった後に、オプションを変更すると当然無効なわけですが、
そこんとこ配慮したほうが良いかもですね。
できればエラーか警告を出すのが好ましいのかもですけれど、
ドキュメントのほうが良いでしょうか。

あとは .so が読まれる前に設定しなきゃいけない
というセンシティブな感じですから、どの設定ファイルで設定すべきみたいな説明も
あったほうが良いのではないでしょうか。

基本的なルールはこんな感じですかね。
「(プラグインより前にするため)vimrcで設定すること」
「コマンドライン引数で(.soを)読んでしまった場合は機能しない」

**Comment by mattn** [comment]
環境変数とかではまずいんですかねー

**Comment by h-east** [comment]
Todolisted.
https://github.com/vim/vim/commit/a0f849ee40cbea3c889345256786b640b0becca2#diff-38d7929bd26d74d92ceddf984bbfc8dbR125

PS
patchをvim_devに投げた場合はIssueは直ぐに閉じずに、vim_dev側の反応(patchが取り込まれた or todo.txtに入った or etc...)で閉じるようにお願いします。

**Comment by h-east** [comment]
Patch 7.4.907
https://github.com/vim/vim/commit/d94464ee294a351ce7b6ba18e8bd3f24f1bef920

**Comment by k-takata** [comment]
7.4.918
https://groups.google.com/d/topic/vim_dev/h7mePlmLZEw/discussion
オプション名が `'python3dll'` から `'pythonthreedll'` に変更になりました。
オプション名に数字は使えなかったのですね。

さらに追加で、7.4.919, 7.4.920 で、optwin.vim に対する修正が入っています。
https://groups.google.com/d/topic/vim_dev/SPPLiG_45hI/discussion
https://groups.google.com/d/topic/vim_dev/Be9DaDpVW3Q/discussion
