### ISSUE TITLE
Python 3.5 で test87 が失敗する

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#783]
if_python3 に python 3.5.0 を使うと、test87 が失敗します。

https://gist.github.com/ichizok/e0d45d97111f0c26dc1d

Ubuntu 15.10, OS X 10.11 で確認。

原因:

https://bugs.python.org/issue22215

NUL を含む文字列を扱った例外が `TypeError` から `ValueError` に変更された。

**Comment by mattn** [comment]
バージョンで切り分けるなどしないと無理なんですかね。

**Comment by k-takata** [comment]
#424 と同様な対処？

**Comment by koron** [comment]
#424 は [こんなパッチ](https://bitbucket.org/koron/vim-kaoriya-patches/src/7e5076069ce9443e20d1b637e669734f14802dfc/test87_python33_workaround.diff?at=default&fileviewer=file-view-default) で対応したのだけれど…
自分で作っておきながら、コイツぁadhocでヒデェやw

とはいえ、それくらいしか対応方法はなさそうね。

**Comment by koron** [comment]
[test87.ok と test87.failed のdiff](https://gist.github.com/koron/b43c4bd385f1acbf7ae5)

**Comment by koron** [comment]
Sent a patch https://groups.google.com/d/msg/vim_dev/kBKHjxSSggM/IKbT0jt4EwAJ

**Comment by koron** [comment]
Released http://ftp.vim.org/vim/patches/7.4/7.4.1456

**Comment by koron** [comment]
Verified with 7.4.1459

全部パスしたのは、なんか久しぶり。
