### ISSUE TITLE
vim.exe を起動する際、起動前にコンソールに表示されたワイド文字が終了後に復元されない［再］

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#785]
#732 の続きです。

7.4.851では CreateConsoleScreenBuffer/SetConsoleActiveScreenBuffer を使って、コンソールを復元しようとしましたが、 #764 を初めとして複数の問題を引き起こしたため、7.4.902で(#772 も含めて)revertされました。

実はVim 5.xの頃は CreateConsoleScreenBuffer/SetConsoleActiveScreenBuffer を使っていたものの、telnetで動かないという問題があったため、Vim 6でそれを使わない実装になっていたそうです。
https://groups.google.com/d/msg/vim_dev/ZSklyGjhUAw/1_Nqe_fUAAAJ

何とかして、ReadConsoleOutputW/WriteConsoleOutputW （あるいは、ReadConsoleCharacter/ReadConsoleAttribute）でバッファを保存・復元するようにする必要がありそうです。

**Comment by k-takata** [comment]
ついに直りました!!!
https://bitbucket.org/k_takata/vim-ktakata-mq/src/378b825971eb7de7692cad5072001c41cab54b29/restore-unicode-chars.patch?fileviewer=file-view-default
何で何ヶ月もこのやり方に気づかなかったのか…

**Comment by mattn** [comment]
一括じゃなくベタで書き直す作戦すね。 GJ!

**Comment by k-takata** [comment]
分割して保存したのなら分割して書き戻せば良い、それだけのことでした。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/z4nmjdUT5yA/oy91455tCAAJ

**Comment by k-takata** [comment]
Bramの反応がない…

**Comment by h-east** [comment]
todo入りしました。
https://github.com/vim/vim/commit/c95a302a4c42ec8230473cd4a5e0064d0a143aa8#diff-38d7929bd26d74d92ceddf984bbfc8dbR198

**Comment by mattn** [comment]
突っつきed

**Comment by k-takata** [comment]
terminalに絡めて突っつきed
terminalでの問題はどちらかというとwinptyの問題だと思われるが、そこはあえて言わないｗ

**Comment by k-takata** [comment]
8.0.0905
https://groups.google.com/d/topic/vim_dev/TUw81r52htw/discussion
長かった…。

**Comment by mattn** [comment]
やった！粘り勝ちw

On 8/12/17, K.Takata <notifications@github.com> wrote:
> 8.0.0905
> https://groups.google.com/d/topic/vim_dev/TUw81r52htw/discussion
> 長かった…。
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/785#issuecomment-321947253


-- 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
[color24.bat](https://gist.github.com/k-takata/2d4f562bacf8bae6691973a540970117#file-color24-bat)を実行してから、vim.exeを実行&終了すると、color24.batの色が16色に丸められてしまいますね。
MSは24bit色対応のためのAPIを用意する予定はないらしいので、どうすることもできないですが…。
（SetConsoleActiveScreenBufferが使えてればなー。）
