### ISSUE TITLE
HomebrewでvimのHEADをインストールしようとすると失敗する

### ISSUE THREAD

**Issue by KiYugadgeter** [vim-jp/issues#787]
HomebrewでvimのHEADをインストールしようとすると、`make install`で失敗してしまいます。
`brew install vim --with-python3 --with-lua --override-system-vi --HEAD`として実行すると失敗します。

`brew install vim --with-python3 --with-lua --override-system-vi`というふうにHEADなしでinstallすると、うまくインストールされます。

エラーを見ると
[vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH](https://github.com/Homebrew/homebrew/issues/33705)
この辺りのissueが関係しているようです。

エラー

<pre>
Last 15 lines from /Users/yuya/Library/Logs/Homebrew/vim/03.make:
cd ../runtime/syntax; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/syntax
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/syntax; chmod 644 *.vim README.txt
cd ../runtime/indent; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/indent
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/indent; chmod 644 *.vim README.txt
cd ../runtime/autoload; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload; chmod 644 *.vim README.txt
cd ../runtime/autoload/xml; cp *.vim /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload/xml
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/autoload/xml; chmod 644 *.vim
cd ../runtime/plugin; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/plugin
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/plugin; chmod 644 *.vim README.txt
cd ../runtime/ftplugin; cp *.vim README.txt logtalk.dict /usr/local/Cellar/vim/HEAD/share/vim/vim74/ftplugin
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/ftplugin; chmod 644 *.vim README.txt
cd ../runtime/compiler; cp *.vim README.txt /usr/local/Cellar/vim/HEAD/share/vim/vim74/compiler
cd /usr/local/Cellar/vim/HEAD/share/vim/vim74/compiler; chmod 644 *.vim README.txt
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
vim  7.4.488 build fails if Homebrew ruby is installed but /usr/bin/ruby comes first in PATH https://github.com/Homebrew/homebrew/issues/33705
</pre>

**Comment by mattn** [comment]
おそらく homebrew の問題なので vim の問題ではないと思いますね。
