### ISSUE TITLE
getcwd() でカレントウィンドウ以外のローカル cwd を取りたい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#790]
https://gist.github.com/thinca/9e705a090a56649e7160

パッチ書いてみました。
`getcwd()` に引数を追加して `getcwd( [{winnr}, [ {tabnr}]])` としたのと、ついでに `haslocaldir()` も同じように `haslocaldir( [{winnr}, [ {tabnr}]])` としました。
関数のシグネチャは `arglistid()` を参考にしました。
英語やコードの作法など自信がないので、細かい部分でも構わないので指摘してもらえると助かります。

**Comment by mattn** [comment]
With なんとかってのは違う気がします。

```
If only 'xxx' is set, ～
```

かと思いましたがどうでしょう？ @ujihisa

**Comment by thinca** [comment]
説明文も概ね `arglistid()` をパクり、もとい参考にしましたが、もっと良い表現があれば直します！

**Comment by rbtnn** [comment]
上記のgist L29だけ`[, {tabnr}]`という表記で、他は`, [ {tabnr}]`になっている。
統一したほうがいいと思います。

**Comment by thinca** [comment]
> 統一したほうがいいと思います。

done.

**Comment by h-east** [comment]
この挙動、説明出来ます？同じ結果になった方が良い気がします。

``` bash
$ vim -N -u NONE
```

``` vim
:new a
:echo winnr()
1                               " window番号1
:echo getcwd()                  " 引数なし
/home/h_east/work
:echo getcwd(1)                 " window番号指定
                                " 空
```

**Comment by thinca** [comment]
@h-east 確かに、`haslocaldir()` も変更してローカルなのがあるかは取れるので、そちらの方が良さそうですね。修正します！

**Comment by thinca** [comment]
Gist updated.
`getcwd()` に引数を与えてウィンドウを指定した場合は、該当ウィンドウで引数なしで `getcwd()` した場合と同じような結果になるようにしてみました。(理解が間違っていなければなってるはず)

**Comment by h-east** [comment]
LGTM:+1:

test書いたよー。後はvim_devに投げるだけですね。
https://gist.github.com/h-east/6019b1c8b3a84a67d547

**Comment by thinca** [comment]
ありがとうございます！

@mattn @ujihisa 

> With なんとかってのは違う気がします。

これどうしましょ?

**Comment by mattn** [comment]
arglistid のをパクったのなら大丈夫ですね。すいません。

**Comment by h-east** [comment]
@thinca すんごい細かいんですけど、ブロック`{ ～ }`の中が1行の場合はブロック消した方がいいです。
https://gist.github.com/thinca/9e705a090a56649e7160#file-getcwd-diff-L159-L162
https://gist.github.com/thinca/9e705a090a56649e7160#file-getcwd-diff-L200-L203

**Comment by thinca** [comment]
おっと、本当だ。ありがとうございます！直します！

**Comment by thinca** [comment]
done.

**Comment by thinca** [comment]
Sent https://groups.google.com/d/topic/vim_dev/T7hAwOUAgkQ/discussion

**Comment by h-east** [comment]
:+1:

**Comment by ujihisa** [comment]
英語良さそうです (ついにgithubにアクセスできるようになった来日中)

**Comment by h-east** [comment]
todolisted.
https://github.com/vim/vim/commit/e392eb41f8dfc01bd13634e534ac6b4d505326f4#diff-38d7929bd26d74d92ceddf984bbfc8dbR172

**Comment by h-east** [comment]
patch 7.4.1126
https://github.com/vim/vim/commit/c970330676eaae7ba7cd05cfa46df5a413853ef9

お疲れ様でした:+1:

**Comment by mattn** [comment]
:+1:

**Comment by thinca** [comment]
:tada:
