### ISSUE TITLE
補完の絞り込みチラつき改善

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#794]
neovim のパッチ https://github.com/neovim/neovim/pull/2674 からの移植です。
レビューをお願いします。

このパッチは補完の絞り込みに作用します。
組み込み補完でもチラつきが解消されるのではないかと期待していますが、検証していません。

https://gist.github.com/Shougo/344a41fcd0bf488c2527

再現方法：
- vim -Nu test.vim
- インサートモードで "Ju" と入力
- パッチ前は絞り込み時にチラつきがある。パッチ後はチラつきが解消される

test.vim :

``` vim
fun! CompleteMonths(findstart, base)
  if a:findstart
    " locate the start of the word
    let line = getline('.')
    let start = col('.') - 1
    while start > 0 && line[start - 1] =~ '\a'
      let start -= 1
    endwhile
    return start
  else
    " find months matching with "a:base"
    let ret = []
    for m in split("January February March April May June July Auguest September October November December")
      if m =~ '^' . a:base
        call add(ret, m)
      endif
    endfor
    echom "return words"
    sleep 400m  " simulate searching for next match
    return {'words':ret, 'refresh':'always'}
  endif
endfun

set completefunc=CompleteMonths
set omnifunc=CompleteMonths
aug mytest
  au!
  au CursorMovedI <buffer> echom 'moveed' | call feedkeys("\<C-x>\<C-u>\<C-p>", 'n')
aug end
```

関連 issue

https://github.com/vim-jp/issues/issues/597

**Comment by mattn** [comment]
試したけどあんまり効果が見えないすね。

**Comment by Shougo** [comment]
Vim は絞り込みを行うときに毎回補完ウインドウを消しているようです。
ただ、Vim 自身の絞り込みは非常に早いのでマシンが遅いか、
refresh_always機能により絞り込みで長時間待たされない限り、チラつきは感知できません。
@mattn さんのところで違いがあまり見えないのもそれが原因かと。
パッチ自身に問題がなければ、vim_dev に投げようと思います。

**Comment by Shougo** [comment]
大変もうしわけありませんが、一身上の都合によりこの issue は閉じさせていただきます。
これまでありがとうございました。
