### ISSUE TITLE
set listcharsのspacesに何か設定して set list linebreak するとlinebreakされない且つカーソル位置がズレる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#796]
https://plus.google.com/+HiroyukiYoshinaga/posts/4z7oKuyUXrC
Google+ からのBug報告を元に条件を絞り込んでIssue登録させて頂きます。

Vim 7.4.960 on fedora via PuTTY.

```
$ vim -N -u NONE -c "set listchars=space:_ list linebreak"
```

```
ia a<Esc>yl80p
```

![linebreak_bug](https://cloud.githubusercontent.com/assets/518808/11608555/fe9d2c32-9baf-11e5-971c-a1658342561d.png)
カーソル位置が（｀ェ´）ﾋﾟｬｰな位置に!!

**Comment by h-east** [comment]
patch書いてvim_devに投げた。
https://groups.google.com/d/msg/vim_dev/UNKfGW9kBg4/J50VWvYpBAAJ

**Comment by k-takata** [comment]
7.4.977
https://groups.google.com/d/topic/vim_dev/qenIGNZxAC4/discussion
