### ISSUE TITLE
オレオレsyntax/vim.vim generatorを自動実行して最新ファイルをWeb上に置いておきたい

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#797]
https://github.com/h-east/vim/tree/gen_syn_vim/

作成動機:
- `runtime/syntax/vim.vim`のメンテナはCharles(Dr.Chip)さん。自分のWebページで公開する形態を取っている。
- Vim本体にオプションやコマンドが追加された場合に`syntax/vim.vim`の更新が必要になる。
- vim_devに`syntax/vim.vim`の修正patchを投げてもBram氏はChipさんがファイル更新するまで基本放置。
- Chipさんのファイル更新が遅い事が多い。
- Chipさんは`syntax/vim.vim`の更新に`mkvimvim`という自前の自動生成ツールを使っているらしい(`syntax/vim.vim`のコメントに書かれている)、が、ソースコードが公開されていない！なんでやねん。

↓

Vimのソースコードをparseして`syntax/vim.vim`を自動生成するVim scriptを書いてみよう。
`src/Makefile`からそいつを実行させて修正があった時だけ`syntax/vim.vim`を変更するようにすれば、Bram氏が即対応出来るからみんなハッピーになれるのでは？
もちろんソースコード公開するから不具合あったら誰でも対応出来るぜ:+1:
(ちなみにNeo～はZyXさんがluaでgeneratorを作成してた)

↓

できた！
2015/11/11 にvim_devに投稿済み。
https://groups.google.com/d/topic/vim_dev/ZSUw8grrOhw/discussion

Bram氏はChipさんに委ねた。Chipさんはスルー。別のスレッドで突っ込んだが「俺もうgenerator持ってるよ」で終わり。みんなもっとフォローしてよ～。
# 

作成後に分かったこと:
- Chip版はソースコードではなくhelpファイルをparseしているようだ。  
  (helpの間違いがそのままsyntax/vim.vimに反映されていたため)
- Chip版はExコマンドの抽出結果が微妙。Exコマンドは省略可能(例:`append`は`a`でOK)なので、`:syntax keyword`で`a[ppend]`のようにカギ括弧を付けて指定しているが、だいぶ無理やり感がある。重複していたり、highlightが付かないパターン結構あると思う。
# 
#### このIssueを立てた目的:

https://github.com/h-east/vim/tree/gen_syn_vim/ を自動実行化して常に最新の`runtime/syntax/vim.vim`をWeb上のどこかに置くようにしたいです。リポジトリは`vim-jp`に移動させても構わないです。
よろしくお願いします。

**Comment by crazymaster** [comment]
:+1:

**Comment by koron** [comment]
急ぎです?

うちのサーバでcron走らせるとかできますが、
なかなか作業時間が取れず時期をお約束できません。
なのでさっくりやれる人がいたら譲ります。

**Comment by koron** [comment]
いちおう僕にアサインしておきました。

できる人がいたら奪って or 言ってください。

**Comment by h-east** [comment]
急いでないです。
そういえばウチでもfedoraが連続稼働してるんだった:sweat_smile:

**Comment by koron** [comment]
一応参考まで。

https://gist.github.com/koron/1c050af4331d7efe4ddc#file-update-vim-ci2-sh-L17

こんな感じでfetchしたあとに log master...origin/masterの差分数を見ると更新があったかどうかは検出可能です。
あとはゴニョゴニョすればorigin/masterの変更に追従してcronで何かするってのはできるな
って考えてます。

**Comment by koron** [comment]
githubならAPIで更新があったかを見るのもできるはず。
自分ではやってない & 本家のAPIkey取れないから、アレかもですが。

**Comment by h-east** [comment]
@koron Thanks! お正月案件ということにします。
もちろん先にやってもらえると嬉しいです。

**Comment by mattn** [comment]
vim-jp にリポジトリ移したいという話であれば、移動してもらっても、そのままにして頂いてもどちらでも構いません。SEO 的に vim-jp が良いという事であれば vim-jp で紹介出来ます。

**Comment by koron** [comment]
@h-east src/gen_syntax_vim だけ、別のプロジェクトとして切り出しませんか? 良ければコチラでやりますが、first commiterは h-east さんであるべきだと思うので…

Travis CIを設定しようと思うのですが、それを設定したり他の人が試すのに、分けてあったほうが扱いやすそうだと思ったので。

**Comment by koron** [comment]
プロジェクトを作って、MakefileとVim scriptsだけ置いてくれれば、あと必要なものは私の方でPRしていきます。

**Comment by h-east** [comment]
@koron :+1: vim-jpに作りました。https://github.com/vim-jp/gen_syn_vim

**Comment by koron** [comment]
thx!

**Comment by h-east** [comment]
koronさんの~~好意~~厚意 :muscle: により自動で出来るようになりました。(更新トリガーだけ手動)
20日ほど運用していますが特に問題起きていないのでこちらは閉じます。

なにかあれば↓へお願いします。
https://github.com/vim-jp/gen_syn_vim/issues
