### ISSUE TITLE
+conceal機能がright-to-leftに対応していない

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#799]
``` bash
$ vim -Nu NONE -c "set rightleft cole=1 cocu=n"
```

```
iabc<Esc>
```

カーソルが逆側(左側)に移動してしまう。

案
1. 対応する。
2. `:h rileft` の`Bugs`に`right-to-leftウィンドウではconceal機能は正しく動かない`と書く。既存で書かれている以下の様な感じで。  
-  "右左" ウィンドウではCTRL-AとCTRL-X(足し算、引き算)コマンドは正しく働かない。

個人的には`:help`の左右カーソル移動が残念になっているので対応してあげたいなと思っていますが、修正ボリュームは見積もれていません。
# 

~~余談ですが`CTRL-AとCTRL-X(足し算、引き算)コマンド`はちょっと修正すればright-to-leftウィンドウでも機能するようになることは把握しています。~~

**Comment by h-east** [comment]
Vimで世界を平和にしていきましょう:smile:

**Comment by h-east** [comment]
vim_devには今晩送る。

``` diff
diff --git a/src/screen.c b/src/screen.c
index 5610d8a..d34c4b2 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -4976,7 +4976,12 @@ win_line(wp, lnum, startrow, endrow, nochange)
        && conceal_cursor_line(wp)
        && (int)wp->w_virtcol <= vcol + n_skip)
    {
-       wp->w_wcol = col - boguscols;
+#  ifdef FEAT_RIGHTLEFT
+       if (wp->w_p_rl)
+       wp->w_wcol = W_WIDTH(wp) - col + boguscols - 1;
+       else
+#  endif
+       wp->w_wcol = col - boguscols;
        wp->w_wrow = row;
        did_wcol = TRUE;
    }
```

**Comment by mattn** [comment]
お。意外とパッチ小さめで素敵。

**Comment by h-east** [comment]
@mattn ありがとー。今、testどうしようか調べ中。 'rightleft' のtestってこのまえ私が書いた `test_increment.vim` 以外やってないっぽい？

**Comment by h-east** [comment]
Post to vim_dev
https://groups.google.com/d/msg/vim_dev/qNYgvyuuKC8/MVyxFB1jBQAJ

```
> p.s. 
> I believe Vim makes world peace. 

I hope so. 
```

patch 7.4.1101
https://github.com/vim/vim/commit/e39b3d9fb4e4006684c33847d1ef6a0d742699dd

テスト書きます！世界平和のために:smile:
