### ISSUE TITLE
Kaoriya版VimでNetrwからファイルに移動すると、終了できなくなる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#801]
https://teratail.com/questions/23348 から転載

> 普段VimのファイラーはNetrw v149を使用しているのですが、エンターキーを押して同じウィンドウ内でファイルを開いた後、<c-o>で元のNetrwに戻ってしまうと、:qや:q!でVimが終了できなくなります。そうなると、:qa!コマンドを叩かない限りVimが終了できなくなってしまっています。

**Comment by crazymaster** [comment]
> Netrw v149

バージョンが古いですね

**Comment by h-east** [comment]
Kaoriya版最新(7.4.884)と同梱のNetrw v153 だと私の環境(Win7 64bit + Vim 64bit)では問題発生しませんでした。

**Comment by crazymaster** [comment]
> 最新版に更新してしばらく使ってみたところ、再現しなくなったようなので
