### ISSUE TITLE
Ruby 2.3.0 で +ruby/dyn のビルドに失敗する

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#802]
```
objects/if_ruby.o: In function `buffer_new':
/home/user/trunk/vim/src/if_ruby.c:1037: undefined reference to `rb_data_object_wrap'
objects/if_ruby.o: In function `window_new':
/home/user/trunk/vim/src/if_ruby.c:1253: undefined reference to `rb_data_object_wrap'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
```

Vim 7.4.979 / CentOS 7

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/1c8c4485bb00cb68a298

とりあえず

**Comment by k-takata** [comment]
別方向のアプローチとして、こんなパッチを作ってあったりします。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/f9662e03304e1d4edc6135e3a60c75a80715fbdd/if_ruby-use_typeddata.patch
https://bitbucket.org/k_takata/vim-ktakata-mq/src/f9662e03304e1d4edc6135e3a60c75a80715fbdd/if_ruby23-use_typeddata.patch
が、ruby 2.3ではコンパイルが通ることを確認したのみで、動作確認はしていません。

ruby 2.2からは、 Data_XXX マクロがdeprecatedだと言われるので、その対策です。

**Comment by k-takata** [comment]
ま、TypedData対応は後回しでもいいと思いますが。

**Comment by ichizok** [comment]
私としては @k-takata さんのパッチ (TypedData 対応) でお願いしたいと思ってます。

**Comment by k-takata** [comment]
@ichizok さんの環境で動作確認をお願いしてもいいですか？

**Comment by ichizok** [comment]
if_ruby を利用しているプラグインを探して少し使ってみましたが、特に問題なさそうです。
- [rubyjump.vim](https://github.com/xmisao/rubyjump.vim)

OS X 10.11.2

**Comment by k-takata** [comment]
確認ありがとうございます。投げました。
https://groups.google.com/d/topic/vim_dev/7hjKZvKV0KA/discussion

**Comment by ichizok** [comment]
:+1: ありがとうございます

**Comment by k-takata** [comment]
7.4.985
https://groups.google.com/d/topic/vim_dev/waLZpSVLPl8/discussion
7.4.987 Bramによる追加修正
https://groups.google.com/d/topic/vim_dev/wAjGufFi2uQ/discussion
