### ISSUE TITLE
if_mzsch が動かない

### ISSUE THREAD

**Issue by ynkdir** [vim-jp/issues#803]
https://gist.github.com/ynkdir/e6a353bb208879397283
いちおう動いたんですがよくわからず。立てるだけ立てときます。

**Comment by k-takata** [comment]
そもそもif_mzschありでビルドしたことがないので、まずはビルド手順を調べるところから始めないと…。

**Comment by ynkdir** [comment]
上のパッチは C:\Racket63 にインストールした前提でハードコードしてて
lib /DEF:C:\Racket63\lib\libracket3m_9z0ds0.def
nmake -f Make_mvc.mak MZSCHEME=C:\Racket63 MZSCHEME_VER=3m_9z0ds0
でコンパイル可です。

考えたこと
1. tls_space 使っていないので落ちる問題。win32 でしか使えなかったが racket-6.3 で win64 でも使えるようになった。
2. (current-library-collection-paths) と (current-library-collection-links) の初期化がうまくいかない問題。ざっくり変えても大丈夫なのか。他の バージョン/OS とか。MZSCHEME_COLLECTS がコンパイル時定数なのは DYNAMIC_MZSCHEME対応 や バイナリ配布を考えるとよろしくない。ライブラリがよきにはからってくれたりはしない。
3. DYNAMIC_MZSCHEME はどうなってるのかな

参考
http://docs.racket-lang.org/inside/embedding.html?q=embed
https://github.com/racket/racket/blob/master/pkgs/racket-test/tests/racket/embed-in-c.c

> On Windows, when support for parallelism is enabled in the Racket build (as is the default), then before calling scheme_main_setup, your embedding application must first call scheme_register_tls_space:

**Comment by ynkdir** [comment]
4 新しいバージョンでは INCLUDE_MZSCHEME_BASE がいらなくなっているらしい。

**Comment by ynkdir** [comment]
linux (ubuntu) でも動かなかったので題名変えました。

> 初期化がうまくいかない問題

なんとかなった。OSX の ifdef を消したけど未確認。

> MZSCHEME_COLLECTS がコンパイル時定数なのは DYNAMIC_MZSCHEME対応 や バイナリ配布を考えるとよろしくない。

$PLTCOLLECTS を設定してもらえば動く。

windows では `(current-library-collection-links)` の設定はデフォルトで `<collects>/../share/links.rktd` を読んでくれるようなのでなんとなく動いている。linux では scheme_set_config_path を設定しないと動かなかった。

> DYNAMIC_MZSCHEME

windows では動くようになった。linux は試してない。

例えば C:\Racket63 にインストールしていた場合は
set PLTCOLLECTS=C:\Racket63\collects
set PATH=%PATH%;C:\Racket63\lib
を設定してもらう形になる。

dll の名前 (libracket3m_9z0ds0.dll) がハッシュぽいのでリリースごとにかわりそう。

racket は main 関数をトランポリンで呼ばないといけないので起動時に dll ロードして失敗したら if_mzscheme を無効化している。

> INCLUDE_MZSCHEME_BASE がいらなくなっているらしい

なくても動く。
ただし、パスの設定が悪いとかでライブラリが読み込めなかった場合に落ちる (エラー処理入れる？)。 INCLUDE_MZSCHEME_BASE を使っていれば組み込んだ機能だけ最低限動くっぽい。

ubuntu は racket パッケージには librackeXXX がない。racket-dev みたいなパッケージもなく。自前ビルドしないといけない。

あとは
make_mvc.mak と configure (-lpthread をつけるのと MZSCHEME_COLLECTS と MZSCHEME_CONFIGPATH の取得) の調整が必要。

**Comment by ynkdir** [comment]
done

> $PLTCOLLECTS を設定してもらえば動く。

これは dll ではやってくれないらしく vim の方で $PLTCOLLECTS と $PLTCONIGDIR を読むようにしました。

**Comment by mattn** [comment]
むちゃむちゃ修正量多いw

**Comment by ynkdir** [comment]
投げました
https://groups.google.com/d/msg/vim_dev/qg7R7HeGq50/l-R74zATAwAJ

**Comment by k-takata** [comment]
`scheme/base`がロードできなかった時に`racket/base`をロードするというのを試しに書いてみたのですが、意味ありますかね？
https://bitbucket.org/k_takata/vim-ktakata-mq/src/4aada59279aa3aa454eb8bfa25726bb40f095e08/mzscheme_base_module.patch?fileviewer=file-view-default

**Comment by ynkdir** [comment]
`racket/base` だけでもたぶんいいんですが、互換性を保ちつつ更新していくという意味で 1 `racket/base`  2 `scheme/base` の順番が個人的にはいいと思います。基本的には同じものみたいです。
http://docs.racket-lang.org/scheme/scheme_base.html

**Comment by k-takata** [comment]
racket/baseを先に読むように修正しました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d2b34c2918f89b9fb6caf6043ea2ab6622632d11/mzscheme_base_module.patch?fileviewer=file-view-default

**Comment by ynkdir** [comment]
ありがとうございます。いちおう k-takata さんのパッチ二つをマージしたのを投げときました。

appveyor で落ちてるのきびしいですね……

**Comment by k-takata** [comment]
ローカルでは落ちていないので、何なのかさっぱりです…

**Comment by k-takata** [comment]
RacketのDLLをPATHから外すと落ちないですね。
https://ci.appveyor.com/project/k-takata/vim/build/115/job/572ehtp2k5twe99j

**Comment by ynkdir** [comment]
https://gist.github.com/ynkdir/e6a353bb208879397283
これを試してもらってもいいですか。
あんまり期待できないですがいちおう。
_tls_index を使うようにしてみました。

**Comment by k-takata** [comment]
残念、ダメでした。
https://ci.appveyor.com/project/k-takata/vim/build/119/job/u6a2u11hb766r8p3

**Comment by ynkdir** [comment]
ありがとうございます。むぅぅ。

**Comment by k-takata** [comment]
> RacketのDLLをPATHから外すと落ちないですね。
> https://ci.appveyor.com/project/k-takata/vim/build/115/job/572ehtp2k5twe99j

このとき、以下の実行ファイルができたので、ローカルにダウンロードしてきてテストを実行してみました。
https://github.com/k-takata/vim/releases/tag/v7.4.1087-test7
結果、0xc0000005は発生しませんでした。

ローカルと、AppVeyorの違いはRacketがminimalかどうかというのがありますが、関係あるかどうか…。

**Comment by ynkdir** [comment]
私のところは minimal ですが大丈夫ですね…

**Comment by k-takata** [comment]
通常版インストーラに変更してみましたが、あえなく撃沈…
https://ci.appveyor.com/project/k-takata/vim/build/120/job/c91wwf4h6syhmvcg
AppVeyorという実行環境固有の問題がありそうですが、いろいろ試すのも簡単ではないですし、AppVeyorで落ちるのは見なかったことにしたい気分ですｗ

**Comment by ynkdir** [comment]
https://gist.github.com/ynkdir/e6a353bb208879397283
url 同じですが

Precise GC のときは DYNAMIC_MZSCH_DLL と DYNAMIC_MZGC_DLL に同じ dll を設定するという手抜きをしてたんですが、これがよくなかったみたいで DYNAMIC_MZGC_DLL=NULL にしてちゃんと 1 回だけ LoadLibrary() するようにしたら落ちなくなりました。
2 回 LoadLibrary() するとなぜ落ちるのかはよくわからないです。

**Comment by ynkdir** [comment]
↑は関係なかったです。
落ちなくなったのは dynamic_mzscheme_end() をコメントアウトしてたからでした。

**Comment by ynkdir** [comment]
トランポリンでmainを呼んでるからそこから出る前に開放すると落ちちゃうということかな。
vim が exit じゃなくて main から return して終了してるのかはよくわかりませんがたぶん。

**Comment by k-takata** [comment]
起動時のシーケンスは、
main -> mzscheme_main -> scheme_main_setup (DLL内) -> mzscheme_env_main -> vim_main2 -> main_loop

終了時は、getout -> mzscheme_end の後に、mch_exit で終了となっているようですね。exit で終了しているのなら問題なさそうな気もしますが。

タイマーが動いている可能性はないだろうかと思い、以下の変更を入れてみたのですが、ダメでした。

``` diff
--- a/src/if_mzsch.c
+++ b/src/if_mzsch.c
@@ -952,6 +952,8 @@ notify_multithread(int on)
     void
 mzscheme_end(void)
 {
+    if (timer_id != 0)
+   remove_timer();
 #ifdef DYNAMIC_MZSCHEME
     dynamic_mzscheme_end();
 #endif
```

そうなると、TRAMPOLINED_MZVIM_STARTUP のときは、dynamic_mzscheme_end() を呼ばないようにするくらいですかね。

**Comment by ynkdir** [comment]
racket が 2 個くらいスレッドを使ってるぽいのでそれかもしれないです。

**Comment by ynkdir** [comment]
scheme_free_all() というそれっぽい関数を見つけたので試したら 2,3 回はテストが通ったけどやっぱりだめでした。
dynamic_mzscheme_end() のコメントアウトもいまのところテストが通ってますがどうなるか。

**Comment by ynkdir** [comment]
TerminateThread() で止めるのでも動きそうな感じでした。

**Comment by k-takata** [comment]
7.4.1104
https://groups.google.com/d/topic/vim_dev/y76BAcr-R7k/discussion
お疲れさまでした。

**Comment by ynkdir** [comment]
ありがとうございました。

**Comment by ynkdir** [comment]
https://gist.github.com/ynkdir/04938888faebc9cc48b1

FreeLibrary() で落ちる件、いちおう appveyor 上でクラッシュダンプを取ってみました。
スレッドは関係なくて racket が登録している例外ハンドラとかatexit関係みたいです。

crash1.txt: FreeLibrary() を呼んだとき。
Racket が AddVectoredExceptionHandler() で例外ハンドラを登録している。
ntdll!RtlpCallVectoredHandlers() が呼ばれたときに libracketxxx.dll がアンロードされていると、それによってさらに例外が発生して例外ハンドラが呼ばれて、と、再帰が起きてスタックオーバーフローが起こる。
なんで例外ハンドラが呼ばれてるかは謎。
これは scheme_free_all() (の中の GC_free_all()) でハンドラを RemoveVectoredExceptionHandler() しているので scheme_free_all() を呼べば問題ないはず。

crash2.txt: scheme_free_all() を読んでから FreeLibrary() したとき 1
これも例外ハンドラのスタックオーバーフローだけどよくわからない。ハンドラ解除しているはずなのに。

crash3.txt: scheme_free_all() を読んでから FreeLibrary() したとき 2
FreeLibrary() が呼ばれたときに atexit() で登録した関数 scheme_run_atexit_closers_on_all() が呼ばれて
1841   scheme_current_thread->error_buf = &newbuf;
で落ちている。

scheme_free_all() を読んでから FreeLibrary() したときのダンプは nmake が止まった時点でなぜか 10 個くらいクラッシュダンプができててよくわからず。

まあ FreeLibrary() しないというのが正解ぽかったです。

**Comment by ynkdir** [comment]
ローカルではいまだに再現できないので appveyor 固有の問題という可能性もなくはないのかな。よくわかりませんが。

**Comment by ynkdir** [comment]
あと、gvim と racket はローカルで msvc14 でコンパイルしたのを appveyor にもっていって使ったので若干違いがあるかもしれません。

**Comment by k-takata** [comment]
すごい

**Comment by ynkdir** [comment]
訂正: racket のスレッドがスタックオーバーフローしてるのやはりスレッド関係でしたね

**Comment by ynkdir** [comment]
メモ。cdb.exe を使うと appveyor のコンソールにバックトレースを出せるので便利そうです。

クラッシュダンプの設定をして
クラッシュさせて
cdb でバックトレースを表示して
適当に dmp, pdb, exe などを収集する

```
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpFolder /t REG_EXPAND_SZ /d C:\CrashDumps /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpCount /t REG_DWORD /d 10 /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpType /t REG_DWORD /d 2 /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v CustomDumpFlags /t REG_DWORD /d 0 /f
nmake -f Make_dos.mak VIMPROG=..\gvim
if errorlevel 1 (
  for %%i in (C:\CrashDumps\*.dmp) do (
    "C:\Program Files (x86)\Windows Kits\8.1\Debuggers\x64\cdb.exe" -z "%%i" -y "SRV*C:\Symbols*http://msdl.microsoft.com/download/symbols;%APPVEYOR_BUILD_FOLDER%\src" -c "!analyze -v; ~*kp; q"
    appveyor PushArtifact "%%i"
  )
  appveyor PushArtifact ..\gvim.exe
  appveyor PushArtifact ..\gvim.pdb
  exit 1
)
```

racket のパッケージは mingw コンパイルで pdb ファイルがないので関数名の表示ができなくて不便。

**Comment by ynkdir** [comment]
ああそか、関数名出ないのはunloadされてるからかな。よくわからない。

**Comment by ynkdir** [comment]
ダンプファイルは Visual Studio でも開けるんですね。でも .reload はできないみたい。

WinDbg で dll をリロードするとアンロードされた dll も表示できました。
.reload /unl libracket3mxxxxxxx.dll

```
racket/src/port.c:
static long WINAPI ITimer(void *data)
  XFORM_SKIP_PROC
{
  ITimer_Data *d = (ITimer_Data *)data;

  WaitForSingleObject(d->semaphore, INFINITE);

  while (!d->done) {
    if (WaitForSingleObject(d->semaphore, d->delay / 1000) == WAIT_TIMEOUT) {    <--- ここ
      *d->fuel_counter_ptr = 0;
      *d->jit_stack_boundary_ptr = (uintptr_t)-1;
      if (!d->done)
    WaitForSingleObject(d->semaphore, INFINITE);
    }
  }

  ReleaseSemaphore(d->done_semaphore, 1, NULL);

  return 0;
}
```

例外発生元はここで、デバッガで見ると data=0x000000eeea3f0190 d=0x000000000000000d でした。
ITimer() は scheme_start_itimer_thread() から CreateThread() で呼ばれています。
green thread 関係。

```
start /LOW /affinity 1 /wait %~dp0\vim.exe %*
```

こういう vim1.bat を用意して `nmake -f Make_dos.mak VIMPROG=..\vim1.bat` で手元の PC でも落とすことに成功しました。
コアの数かPC負荷かわかりませんがそのへんの条件みたいです。
ちなみに appveyor は Open-Source (Free)  CPU = 1 core shared or full  MEMORY = 1.7 GB to 3.5 GB らしいです。

スレッド動かしてるライブラリを FreeLibrary() すると落ちる話
What is the point of FreeLibraryAndExitThread?
https://blogs.msdn.microsoft.com/oldnewthing/20131105-00/?p=2733

**Comment by uakms** [comment]
Windows の話でなく申し訳ないのですが、OSX 10.11.2, Racket v6.3(公式配布のバイナリ版 racket-6.3-x86_64-macosx.dmg を開いて /Applications にコピー) にて動作することを確認できました。
1. `/Applications/Racket v6.3` を `/Applications/Racket` にリネーム
2. `.bashrc` に `export DYLD_FRAMEWORK_PATH=/Applications/Racket/lib` を追記
3. `vim/src/auto/configure` の `MZSCHEME_LIBS="-framework Racket"` を `MZSCHEME_LIBS="-F${path} -framework Racket"` に修正
4. ./configure へのオプションに `--with-plthome="/Applications/Racket"` を追加
5. `make; make install`
6. Vim を起動して確認

```
:mz (print "こんにちは") -> こんにちは
:mz (+ 10 20) -> 30
:mz (require setup/dirs)
:mz (display (find-include-dir)) -> /Applications/Racket/include
:mz (display (find-lib-dir)) -> /Applications/Racket/lib
```

warning 等は長いので gist に張っておきます。
https://gist.github.com/nakinor/6cd697b9137e2b22f06d#%E3%83%93%E3%83%AB%E3%83%89%E6%99%82%E3%81%AE%E8%AD%A6%E5%91%8A%E3%82%92%E3%83%A1%E3%83%A2%E3%81%A3%E3%81%A6%E3%81%8A%E3%81%8F

以上です。

**Comment by ynkdir** [comment]
確認ありがとうございます。

-F とパスの空白対応が必要ですかね。あと警告。

'mzschemedll' オプションとか追加したいんですが vimrc を読み込む前にロードしないといけないので使えず。さいあく環境変数ですか。DYLD_FRAMEWORK_PATH でなんとかなるならなによりです。

**Comment by ynkdir** [comment]
unix は DYNAMIC_MZSCHEME はもともとないからそれはいいのか

**Comment by uakms** [comment]
すみません、私の場当り対処だと `make test` が実行できなくなってしまいました…… `DYLD_FRAMEWORK_PATH` を設定しなかった時と同じように `Library not loaded:` で死んでしまいました(Racket.framework/ を testdir にコピーすると動く)。
