### ISSUE TITLE
$VIMRUNTIME/indent/vim.vim の GetVimIndent() がshiftwidth=0に対応していない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#806]
# 問題

shiftwidthを0に設定すると、filetype=vimの時の`gg=G`するとインデントが~~亡くなり~~無くなります。
# 修正箇所

https://github.com/vim/vim/blob/e3faf44bef029d07f37a457bd0050653b628058f/runtime/indent/vim.vim#L34-L97
# 修正方法

`&sw`の代わりに`shiftwidth()`関数を使う必要があります。
runtimeファイルの修正はこの関数が追加された後なので、
この関数が使えるかのバージョンチェックも不要で、ただ置換すれば良いと思います。
# 会話ログ

@rbtnnさんが見つけてくれました。

http://lingr.com/room/vim/archives/2016/01/23#message-22976509

**Comment by tyru** [comment]
Pull Request投げました。 vim/vim#578

**Comment by crazymaster** [comment]
実は shiftwidth() を使っていないのが結構あってですね :sweat: 
#714 参照

**Comment by tyru** [comment]
oh...

**Comment by crazymaster** [comment]
https://github.com/vim/vim/commit/705ada1aff27ecd9c47c690df817d043c2ceb5e2#diff-59df7be2982b9c340efe6e4d137ffd68

**Comment by tyru** [comment]
あ、あのPRの最初のコミットのみ取り込まれちゃったのか。
2コミット目で全てのindentプラグインの修正をしたのですが。
まぁおそらく`indent/vim.vim`のdiffはスキップしてもらえば大丈夫かな…
