### ISSUE TITLE
エクスプローラのコンテキストメニューの項目が日本語表示されない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#808]
６４bit版Windowsに、公式のインストーラでVimをインストールすると、エクスプローラの右クリックメニューで表示される "Edit with Vim" などの項目が日本語表示されません。
（32bit Windowsであれば問題ありません。）

原因：
インストーラでインストールされるVimは32bit版であり、同梱されているgettextのDLLも32bit版である。
一方、64bit Windowsでは、右クリックメニューの項目表示を行うgvimext.dllは、64bit版がインストールされる。
gvimext.dllは日本語表示を行うためにgettextをロードしようとするが、DLLは32bit版であるためロードできず、日本語表示できない。

**Comment by k-takata** [comment]
関連todo

> Windows installer should install 32-bit version of right-click handler also on
> 64-bit systems. (Brian Cunningham, 2011 Dec 28)

あとは #508 も。

**Comment by k-takata** [comment]
> （32bit Windowsであれば問題ありません。）

最新ナイトリービルドの、
https://github.com/vim/vim-win32-installer/releases/tag/v7.4.1194
を使うと、32bit Windowsでもメニュー項目が日本語化されません。

原因:
- 同梱しているgettext DLLの名前が、libintl.dll から libintl-8.dll に変更されたが、GvimExtがそれに対応できていない。
- gettext DLLがiconv DLLに依存しているバージョンに変更されたが、iconv DLLがDLLの検索パス上に存在しないため、iconv DLLがロードできず、その結果gettext DLLがロードできない。

**Comment by mattn** [comment]
ディレクトリ直指定は1個でいいかな。

``` diff
diff --git a/src/GvimExt/gvimext.cpp b/src/GvimExt/gvimext.cpp
index e644443..81d4cfc 100644
--- a/src/GvimExt/gvimext.cpp
+++ b/src/GvimExt/gvimext.cpp
@@ -158,6 +158,7 @@ HBITMAP IconToBitmap(HICON hIcon, HBRUSH hBackground, int width, int height)
 # define VIMPACKAGE "vim"
 # ifndef GETTEXT_DLL
 #  define GETTEXT_DLL "libintl.dll"
+#  define GETTEXT_DLL_ALT "libintl-8.dll"
 # endif

 // Dummy functions
@@ -206,6 +207,10 @@ dyn_libintl_init(char *dir)
     if (!hLibintlDLL)
     {
    hLibintlDLL = LoadLibrary(GETTEXT_DLL);
+#ifdef GETTEXT_DLL_ALT
+   if (!hLibintlDLL)
+       hLibintlDLL = LoadLibrary(GETTEXT_DLL_ALT);
+#endif
    if (!hLibintlDLL)
        return 0;
     }
```

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/608

**Comment by k-takata** [comment]
残念ながらそれでは不十分なのです。

**Comment by mattn** [comment]
どの件でしょうか？

**Comment by k-takata** [comment]
これです。

> gettext DLLがiconv DLLに依存しているバージョンに変更されたが、iconv DLLがDLLの検索パス上に存在しないため、iconv DLLがロードできず、その結果gettext DLLがロードできない。

現象の説明としては、以下が分かりやすいですね。
DLLからDLLを呼ぶのはこんなに難しい - kawanon
http://d.hatena.ne.jp/m_kawanon/20110731/1312116123

gvimext.dll は、explorer.exe (あるいは同様のファイラー等) のプロセスで動くので、DLLの検索パスには、gvim.exe のあるディレクトリは含まれない点がはまりどころです。
パッチは準備中。

**Comment by mattn** [comment]
なるほど。パッチお願いします。

**Comment by k-takata** [comment]
このパッチを投げました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/479934b94fd56b064c9e4bd8737585c5df69d56a/fix-gvimext-loadlibrary.patch?fileviewer=file-view-default
PATHの先頭に、一時的にVimのruntimeディレクトリを追加してから、libintl.dll, libintl-8.dll の順でロードを試みます。

**Comment by k-takata** [comment]
64bit Windowsで日本語表示されない問題は、32bit版の問題が修正されてからレポート予定。
どう直すか（そもそも直すのか）はvim_devの反応しだいかなー。

**Comment by k-takata** [comment]
7.4.1383
https://groups.google.com/d/topic/vim_dev/VLAesI_qfwI/discussion
32bit版は直りました。

**Comment by k-takata** [comment]
Related: k-takata/vim-win32-installer#1

**Comment by k-takata** [comment]
gvimext.dll の 32/64bit版両方をインストールするようにするパッチ。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c6f0bdb8c24cd02f54ee6b2e97c44020204a9979/win32-intstall-gvimext3264.patch?at=default&fileviewer=file-view-default

インストール後のディレクトリ構成はこんな感じ。

```
vim80\
  gvim.exe       (32-bit or 64-bit, depends on the zip package or the self-installer)
  vim.exe        (same as above)
  libiconv-2.dll (same as above)
  libintl-8.dll  (same as above)
  libgcc_s_sjlj-1.dll (32-bit only)

  GvimExt32\
    gvimext.dll    (32-bit)
    libiconv-2.dll (32-bit)
    libintl-8.dll  (32-bit)
    libgcc_s_sjlj-1.dll (32-bit)

  GvimExt64\       (No need to install on a 32-bit OS)
    gvimext.dll    (64-bit)
    libiconv-2.dll (64-bit)
    libintl-8.dll  (64-bit)
```

**Comment by k-takata** [comment]
アンインストール処理を少し修正。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a797771dd0314182bf1472547596af2ec1ae78e3/win32-intstall-gvimext3264.patch?at=default&fileviewer=file-view-default

iconvとgettextのDLLが2種類、3セットインストールされるのはビミョーな感じがしますが、32bitインストーラ、32bit/64bit zipパッケージのどれでも同じように動かせるようにするには、こうするのが一番楽かなと思います。

**Comment by k-takata** [comment]
Posted: vim/vim#2144

**Comment by k-takata** [comment]
todo listed: https://github.com/vim/vim/commit/24a98a0eb77245adc50facad8b735b20bfd31a7e#diff-38d7929bd26d74d92ceddf984bbfc8dbR38

```
MS-Windows build and installer improvements:
- Switch to VC2015 for building. (Ken Takata, 2017 Sep 21)
  Check resulting binary on XP.
- Patch to install 32 and 64 bit Gvimext and related dll files. (Ken Takata,
  2017 Sep 23, #2144)
```

**Comment by k-takata** [comment]
Fixed by 8.0.1191
https://groups.google.com/d/topic/vim_dev/siTwBk6WykM/discussion
