### ISSUE TITLE
vim.exe で channel が有効にならない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#809]
非サポート扱いの様だったので直しました。

https://gist.github.com/mattn/49add004c951329fdf37

既知の問題点として(gvimでもあり得る)、json を使う場合、1回の受信で2回分受信してしまった時に json_decode がエラーになる(当然)ので、処理性能の遅い vim.exe が急にソケット受信するとエラーになる。

どなたか検証お願いします。

**Comment by tyru** [comment]
:+1:

**Comment by k-takata** [comment]
試していませんが、HAVE_SELECT の定義の仕方が気になりました。
select() があるかどうかの定義なので、GUI/CUI で定義を変えるのは不自然だと思います。

**Comment by mattn** [comment]
FEAT_GUI_W32 の場合は HAVE_SELECT じゃないパスなんですよね。。。

**Comment by k-takata** [comment]
長くなってしまいますが、 `defined(HAVE_SELECT) && !defined(FEAT_GUI_W32)` でいいんじゃないでしょうか。こっちの方が分かりやすいと思います。

**Comment by mattn** [comment]
> 長くなってしまいますが、 defined(HAVE_SELECT) && !defined(FEAT_GUI_W32) でいいんじゃないでしょうか。こっちの方が分かりやすいと思います

どの部分でしょうか？

**Comment by mattn** [comment]
あ、わかりました。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/607

**Comment by k-takata** [comment]
あれ、vim.h の HAVE_SELECT のdefine部分はそのままですか？

**Comment by mattn** [comment]
Windows だと HAVE_SELECT は自分で定義する必要があるのです。
Windows GUI は HAVE_SELECT に依存していないので、Windows Console の場合は自分で定義しています。

**Comment by k-takata** [comment]
GUIでも select() を使いたくなったときに、はまりそうです。CUI/GUIで分けないほうがよいと思います。
channel_wait() の動作が HAVE_SELECT で変わりそうですが、大丈夫ですか？

そして、appveyorが落ちていますね。
https://ci.appveyor.com/project/chrisbra/vim/build/472

**Comment by mattn** [comment]
gvim.exe と vim.exe で channel の実装方式が違うのです。
コード読んでもらえると分かるのですが、gvim はウィンドウハンドルを使って select する方式を取っています。
**channel の目的では** 混ぜる事はないと思います。

**Comment by mattn** [comment]
extern かな。直しておきます。

**Comment by mattn** [comment]
GUI 版は channel_wait に来た時点で select は完了しているので(そもそもトリガがウィンドウハンドルによるselect)、敢えて HAVE_SELECT を実行してないんだと思います。

**Comment by k-takata** [comment]
7.4.1195
https://groups.google.com/d/topic/vim_dev/0Z_c4M9gtVA/discussion

**Comment by mattn** [comment]
↑に書いたJSONを2回受け取るとパースが出る件はBramが直してくれた。
