### ISSUE TITLE
WindowsでASCIIなファイルを含む:helptagsが失敗する

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#81]
`vimdoc-ja`で`make html`した時に気付いたのですが、buildhtml.vimでやっている`helptags .`がWindowsだと失敗している。
どうやらASCIIだけで書かれている`tags.jax`が原因で

```
E670: 1つの言語のヘルプファイルに複数のエンコードが混在しています: .\tags.jax
```

というエラーが出ている模様。

**Comment by thinca** [comment]
すいません。その `tags.jax` はどこにあるものですか?

**Comment by mattn** [comment]
あ... `runtime/doc/tags.jax` にあるやつはリポジトリ内のファイルじゃないのか。
いつ作っちゃったんだろ。

**Comment by ynkdir** [comment]
makehtml.vim 内で作ってます。
順番としては :helptags の後で作成されるので
make html ではエラーはでないはずだと思います。
tags-ja から tags.html を生成するための中間ファイルみたいなもんです。

**Comment by ynkdir** [comment]
> make html ではエラーはでないはずだと思います。
> buildhtml.vim の先頭で一旦全ファイルを削除してるので。

あー、runtime/doc/tags.jax にコピーが存在してるんですね。。。

**Comment by mattn** [comment]
閉じます
