### ISSUE TITLE
let v:['errors'] = 123 | call assert_equal(1,2)でSEGVする

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#810]
タイトルのままですが、

```
let v:['errors'] = 123
call assert_equal(1,2)
```

でSEGVしました。

**環境**
Vim 7.4.1204

**Comment by rbtnn** [comment]
**追記**

> ```
>               *v:errors* *errors-variable*
> ```
> 
> v:errors   Errors found by assert functions, such as |assert_true()|.
>       This is a list of strings.
>       The assert functions append an item when an assert fails.
>       To remove old results make it empty: >
>   :let v:errors = []
> <      If v:errors is set to anything but a list it is made an empty
>       list by the assert function.

ヘルプには最後の1文で「v:errors にどんな値がはいっていようとassert関数が空のリストを設定してくれる」っぽいみたいです(私の英語解釈が間違いでなければw)。

**Comment by mattn** [comment]
触ったのちに投げます。

``` diff
diff --git a/src/eval.c b/src/eval.c
index 7679251..ee4106a 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -20641,7 +20641,9 @@ set_vim_var_string(
     void
 set_vim_var_list(int idx, list_T *val)
 {
-    list_unref(vimvars[idx].vv_list);
+    if (vimvars[idx].vv_type == VAR_LIST)
+   list_unref(vimvars[idx].vv_list);
+    vimvars[idx].vv_type = VAR_LIST;
     vimvars[idx].vv_list = val;
     if (val != NULL)
    ++val->lv_refcount;
```

**Comment by mattn** [comment]
同類の修正もありそうなのでチェックします。

**Comment by mattn** [comment]
https://gist.github.com/mattn/ad144a036917da633ca7

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/aDQKl_Y-zZw

**Comment by h-east** [comment]
patch 7.4.1223
https://github.com/vim/vim/commit/a542c680a8b42cb766e64d4ee7374ef4dacb7832
