### ISSUE TITLE
ヘルプ内のtypo

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#811]
> ```
>       :if type(myvar) == type(v:none
> ```

最後の閉じカッコがありませんでした。

**Comment by crazymaster** [comment]
eval.txtで見つけたのでついでに
関数一覧でmatchadd(),matchaddpos()の引数追加が反映されてないです

**Comment by rbtnn** [comment]
> assert_false({actual} [, {msg}])               _assert_false()_
>       When {actual} is not false an error message is added to
>       |v:errors|, like with |assert_equal()|.
>       A value is false when it is zero. When "{actual}" is not a
>       number the assert fails.
>       When {msg} is omitted an error in the form "Expected False but
>       got {actual}" is produced.
> 
> assert_true({actual} [, {msg}])                    _assert_true()_
>       When {actual} is not true an error message is added to
>       |v:errors|, like with |assert_equal()|.
>       A value is true when it is a non-zero number.  When {actual}
>       is not a number the assert fails.
>       When {msg} is omitted an error in the form "Expected True but
>       got {actual}" is produced.

細かいですが、上記の関数の説明で「When {actual}」と「When "{actual}"」と表記の違いがありました。

**Comment by rbtnn** [comment]
> ```
>               *matchadd()* *E798* *E799* *E801*
> ```
> 
> matchadd({group}, {pattern}[, {priority}[, {id} [, {dict}]]])
> ...
>           conceal     Special character to show instead of the
>                   match (only for |hl-Conceal| highlighed
>                   matches, see |:syn-cchar|)

s/highlighed/highlighted/

**Comment by uakms** [comment]
eval の原文・訳文共にですが、allinks が 2 つ、alllinks が 4 つあります。

globpath の説明部分(ろ)が typo だと思うのですが、仮に allinks と alllinks が別の概念であるとすると、globpath の関数一覧部分(い)の方を allinks に変更しないと辻褄が合わないと思います(しかし紛らわしい)。

(い) 組み込み関数一覧の部分では下記のようになっている

```
glob( {expr} [, {nosuf} [, {list} [, {alllinks}]]])
globpath( {path}, {expr} [, {nosuf} [, {list} [, {alllinks}]]])
```

(ろ) 各説明では下記のようになっている

```
glob({expr} [, {nosuf} [, {list} [, {alllinks}]]])      *glob()*
        ただし、{alllinks} 引数が存在し、それが非ゼロである場合はすべ
        てのシンボリックリンクが含まれる。

globpath({path}, {expr} [, {nosuf} [, {list} [, {allinks}]]])
        {allinks} は|glob()|の場合と同様に扱われる。
```

**Comment by k-takata** [comment]
@nakinor typoでしょう。

**Comment by h-east** [comment]
from https://github.com/vim-jp/vimdoc-ja/pull/182#discussion_r51507468

https://github.com/vim/vim/blob/master/runtime/doc/repeat.txt#L493

>   frame N     Goes to N bactrace level. + and - signs make movement

s/bac\zs\zetrace/k/

**Comment by h-east** [comment]
ここに挙がっている分をまとめて修正してvim_devに投げました。
https://groups.google.com/d/msg/vim_dev/EzXOVGARtgs/W3wRGVt8DgAJ

**Comment by crazymaster** [comment]
Thanks! :+1:

**Comment by uakms** [comment]
typo で間接的に初 contribute！
小物感♡

**Comment by h-east** [comment]
2016/2/16の早朝に全部反映されました。
(実際には殆どがv7.4.1310で修正されていました)
https://github.com/vim/vim/commit/38a55639d603823efcf2d2fdf542dbffdeb60b75

みなさんありがとうございました:+1:
@nakinor :tada:

閉じます。また(vim_devに報告が必要な)typoを発見された場合は本Issueを再オープンするか新規Issueを立てる等お願いします。

**Comment by rbtnn** [comment]
ありがとうございます。
