### ISSUE TITLE
connect()に{timeout}がないのでミスると1,2分くらいなにもできなくなる

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#812]
http://lingr.com/room/vim/archives/2016/01/29#message-22995661

> connect()にタイムアウト時間が欲しい。
> connect()の引数にhelpを見ながら設定していき遊んでいるんだけど、ちょっとミスるとconnect()で1,2分くらいなにもできなくなる。Ctrl-cも受け付けない感じ
> (なのでCのソース読んでいる..

これってどうなったんでしたっけ？ @rbtnn

**Comment by mattn** [comment]
出来れば引数増やしたくないので

```
connect("localhost:12345, "raw")
```

とは別の指定で

```
connect("localhost:12345, {"type":"raw", "timeout": 3000})
```

が出来ると便利そう。

**Comment by tyru** [comment]
便利そうです :+1:

**Comment by mattn** [comment]
もしくは

```
connect("localhost:12345?timeout=3000", "raw")
```

もあるかも。

**Comment by mattn** [comment]
https://gist.github.com/mattn/867a635e14ac2360613a

```
connect("localhost:12345?timeout=3000", "raw")
```

こっちの方で書きました。

**Comment by mattn** [comment]
accept 後の windows console の反応が悪い。

**Comment by mattn** [comment]
別件だった。
https://groups.google.com/forum/#!topic/vim_dev/0Z_c4M9gtVA

**Comment by mattn** [comment]
ドキュメントも更新ed

https://gist.github.com/mattn/867a635e14ac2360613a

**Comment by thinca** [comment]
`{address}` に文字列で渡すのは、動的に渡したい場合に文字列操作が入って煩わしいので、辞書で渡す方が個人的には好みです。
また、`{address}` は address であって URI ではないので、`?` でアドレス以外のパラメータを渡すのも違和感があります。

**Comment by rbtnn** [comment]
> これってどうなったんでしたっけ？ @rbtnn

すみません。これと言った進捗はありません。

> 出来れば引数増やしたくないので
> 
> connect("localhost:12345, "raw")
> とは別の指定で
> 
> connect("localhost:12345, {"type":"raw", "timeout": 3000})
> が出来ると便利そう。

辞書で渡す方++

**Comment by tyru** [comment]
同じく文字列操作が煩わしいので辞書で第2引数に渡す方が良いと思います。

**Comment by mattn** [comment]
一回 bram に見せて委ねますね。

**Comment by h-east** [comment]
選択肢を増やしときます。

案3: 'connecttimeout' オプション方式

``` vim
set connecttimeout=3000
call connect("localhost:12345", "raw")
```

**Comment by mattn** [comment]
ホストAは3秒、ホストBは2秒、みたいな時に気持ち悪くなる。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/Q9v3w9qJSO4

**Comment by koron** [comment]
普通に省略可能な3番目の引数が増えそうw

**Comment by mattn** [comment]
既に3番目が省略引数というアレ

**Comment by koron** [comment]
あ、そうか。でも第2引数の type をオプションにしたら、定義上は省略可になっちゃって混乱しそう。

**Comment by mattn** [comment]
dict にするコードは書けたけど
- 文字列形式で mode を受け取るのは廃止したいのか、どっちも受けれる様にしたいのか
- Bram は dict にも callback 入れよう言ってるけどその場合第三引数さんはさようなら？

あたりが読めない。

**Comment by mattn** [comment]
パッチ更新。あとは↑の件がクリアになれば...

**Comment by h-east** [comment]
`cursor()`みたいな感じでAPIのI/F 2種類用意する感じだと思います。

```
cursor({lnum}, {col} [, {off}])
cursor({list})
```

```
connect({address}, {mode} [, {callback}])
connect({address}, {dict})
  {dict} with the following entries:
    mode            default "json"
    callback        default: none
    waittime        default: zero (waiting for the server)
    timeout         default: 1 second (waiting for response)
```

**Comment by mattn** [comment]
API 名変わったので更新、追従。

https://groups.google.com/forum/#!topic/vim_dev/cHijt3DRDao

https://gist.github.com/mattn/867a635e14ac2360613a

**Comment by h-east** [comment]
:+1: 

helpは`cursor()`みたいに書くのがAPI I/Fが2つあると分かりやすくて良いと思った。

```
cursor({lnum}, {col} [, {off}])             *cursor()*
cursor({list})
```

あと、すげーー細かいけど↓
https://gist.github.com/mattn/867a635e14ac2360613a#file-gistfile1-diff-L466
s/()/(void)/

**Comment by h-east** [comment]
@mattn 修正Thanks.

私が思っていたhelpの最終形はこれです。

``` diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 4a298df..10b4d00 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -1813,6 +1813,7 @@ ceil( {expr})         Float   round {expr} up
 ch_close( {handle})        none    close a channel
 ch_open( {address}, {mode} [, {callback}])
                Number  open a channel
+ch_open( {address}, {dict})    Number  open a channel with {dict}
 ch_sendexpr( {handle}, {expr} [, {callback}])
                any send {expr} over JSON channel {handle}
 ch_sendraw( {handle}, {string} [, {callback}])
@@ -2671,6 +2672,7 @@ ch_close({handle})                    *ch_close()*
        Close channel {handle}.  See |channel|.

 ch_open({address}, {mode} [, {callback}])      *ch_open()*
+ch_open({address}, {dict})
        Open a channel to {address}.  See |channel|.
        Returns the channel handle on success.  Returns a negative
        number for failure.
@@ -2684,6 +2686,15 @@ ch_open({address}, {mode} [, {callback}])        *ch_open()*
        {callback} is a function that handles received messages on the
        channel.  See |channel-callback|.

+       When there is second argument {Dict} this is used as a Dict
+       with four item:
+           mode        default "json"
+           callback    default: none
+           waittime    Specify connect timeout value for the
+                       server as seconds. default: 0 second
+           timeout     Specify read timeout value as seconds.
+                       default: 1 second
+
 ch_sendexpr({handle}, {expr} [, {callback}])       ch_*sendexpr()*
        Send {expr} over JSON channel {handle}.  See |channel-use|.

```

まっつんさんが取り込まない場合はその旨私に伝えて下さい。私がvim_devに提案してみます。

`s/()/(void)/`の件一度修正されましたがrev.7でもとに戻っています。

あと、コンパイルwarning出ています。

```
eval.c: 関数 ‘f_ch_open’ 内:
eval.c:9769:30: 警告: 互換性のないポインタ型から 2 番目の ‘strtol’ の引数に渡しています
     port = strtol((char *)p, &rest, 10);
                              ^
In file included from os_unix.h:33:0,
                 from vim.h:274,
                 from eval.c:14:
/usr/include/stdlib.h:183:17: 備考: expected ‘char ** __restrict__’ but argument is of type ‘char_u **’
 extern long int strtol (const char *__restrict __nptr,
```

`rest`の型を`char *'にしたら直りました。

**Comment by mattn** [comment]
えと、ch_open の第三引数は無くなる予定なのでそれでもまずいです。

**Comment by mattn** [comment]
void と警告を直しました。

**Comment by h-east** [comment]
(第2引数が Dict の時は) 第3引数要らないよ。

って返信だと思います。

**Comment by mattn** [comment]
> There won't be a third argument. 

だとすると Then か if {mode} is specified in 2nd argument. って言うと思うんですよね。

**Comment by h-east** [comment]
うーん、まっつんさんが Dict の
時限定で質問してますし、
それに既存のi/fを変える必要性が見当たらないです。
ま、patch取り込まれればはっきりしますよね:+1:

**Comment by k-takata** [comment]
7.4.1263
https://groups.google.com/d/topic/vim_dev/4AFbMAEwmck/discussion

**Comment by mattn** [comment]
3つめ残すんかー

On 2/6/16, K.Takata notifications@github.com wrote:

> Closed #812.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/812#event-541293808

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
いや、残ってなさそうですが。

**Comment by mattn** [comment]
あらみまちがい すみません

On 2/6/16, K.Takata notifications@github.com wrote:

> いや、残ってなさそうですが。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/812#issuecomment-180613695

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
なお、第2引数は省略可能になりました。

**Comment by h-east** [comment]
:+1: 

> なお、第2引数は省略可能になりました。

そう来ましたか。
あと、時間の単位がsecじゃなくてmsecになりましたね。

**Comment by mattn** [comment]
waittime が 0 デフォルトだけど、localhost なら十分かもだけどインターネットの場合は間違いなくタイムアウトしますね。。。

**Comment by h-east** [comment]
`0` って永遠に待つ (==タイムアウトしない) んじゃないんですか？

**Comment by k-takata** [comment]
負の値がタイムアウト無しのようですね。

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/f416086/src/eval.c#L9804

`ch_open` では、負値 `waittime` はエラーですが、

https://github.com/vim/vim/blob/f416086/src/channel.c#L401

`channel_open` 側は負値 `waittime` でタイムアウトなし
あと、単位が sec になっています

**Comment by h-east** [comment]
https://linuxjm.osdn.jp/html/LDP_man-pages/man2/select.2.html

> timeval 構造体の両方のフィールドが 0 の場合、 select() はすぐに復帰する (この機能はポーリング (polling) を行うのに便利である)。 timeout に NULL (タイムアウトなし) が指定されると、 select() は無期限に停止 (block) する。

waittimeが0の時は「タイムアウトなし」という仕様にして、`select()`の第5引数にNULLを渡すようにするというのはどうでしょう？
もしくはwaittimeのデフォルト値を2000にするか。

**Comment by h-east** [comment]
情報Thanks!

> あと、単位が sec になっています

あっ、`:h ch_open`のwaittimeの単位はmillisecondsって書いてあるけど、そのままtv_secに突っ込んでるｗ

``` c
tv.tv_sec = waittime;
```

**Comment by mattn** [comment]
ぼっ... ぼくは最初から second のつもりで送ったんだからねっ！

https://gist.github.com/mattn/867a635e14ac2360613a#file-gistfile1-diff-L38

**Comment by h-east** [comment]
Of course I know.
Bram氏が変えたのは把握しております。

**Comment by mattn** [comment]
正直 ms のタイムアウト値はいらん気がする。

**Comment by h-east** [comment]
tweetした内容を貼っときます。

> 以下要整合
> 1. waittimeとtimeoutの単位は何？
> 2. 「無限待ち」と「待ちなし(poll)」を意味する値は何？
> 3. 「待ちなし(poll)」って要る？

**Comment by h-east** [comment]
patch 7.4.1268
https://github.com/vim/vim/commit/26dfc41335ef47fe765643148ae980be388084ec

ドキュメント通りにソースコードもwaittimeがmsecで運用されるようになりました。

``` c
tv.tv_sec = waittime / 1000;
tv.tv_usec = (waittime % 1000) * 1000;
```

あと、`0`はpolling(no wait)という仕様です。「無限待ち」は無し。
https://groups.google.com/forum/#!topic/vim_dev/4AFbMAEwmck
