### ISSUE TITLE
変数v:noneは必要か？

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#814]
以前 @thinca さんがLingrで言ってた件ですが、
`v:none`はもしかして不要かもしれないという意見がありました。
というのも、おそらくこの変数が追加されたのは、`jsondecode("[1,,3]")`の様な不正なJSONをパースした際に、何もない要素を`v:none`で置き換える為だという推測が出ました。
もしそうであれば、`v:none`は`v:null`と紛らわしい為、削除しても良いのではないかというのが本件の(私と@thincaさんの)主張です。
# ポイント
- `v:none`が追加された理由についての推測は本当に正しいか？
- もし正しいのであれば、そもそも不正なJSONをパースする意義を見いだせない事、また`v:null`と紛らわしく両者の混同が予想される事を考え、`v:none`は削除して構わないのではないか？
# タスク
- [x] Lingrのリンクを探して貼る
- [x] とりあえず本issueの本文で書いた内容をvim_devに送る
  - 本issueは英文書く前に自分の中で考えをまとめる意味もあった

**Comment by itchyny** [comment]
https://groups.google.com/d/msg/vim_dev/9rf5_YmPn28/qZKB3rKvCAAJ
ご参考に。

**Comment by 0xBADDCAFE** [comment]
Lingr のリンクはこの辺りからでしょうか。
http://lingr.com/room/vim/archives/2016/02/01#message-23006073

**Comment by tyru** [comment]
@itchyny @0xBADDCAFE ありがとうございます！お二人ともめっちゃ助かります！

**Comment by tyru** [comment]
送りました。
https://groups.google.com/forum/#!topic/vim_dev/jtQ1tsHSAhg

**Comment by tyru** [comment]
なんかこれ、恐らくBramさんはもっとフィードバックがほしいんだろうけど、自分とZyXさん以外返事がないので、このままだといつも通り無視してそのままになってしまいそうな予感。

**Comment by tyru** [comment]
私「これに関してどう思ってる？」
ってpingしたらBramさんから返事返ってきて、
Bram「`v:none`と`v:null`はJavaScriptの`undefined`と`null`に合わせたいからどっちも必要だよ。ぶっちゃけ今これに関して時間が惜しいのであんまり議論したくない」

私「JSONよりJavaScriptに合わせたいのは理解できた。
ただJSONはJavaScriptのためだけのものじゃない。
スクリプトや外部コマンドとの連携全般に対して使われると思う。
また、今は `jsonencode({"key": v:none})`が`{"key":}`を返すが、これは正しいJavaScriptの構文ですらない。
ZyXさんの言うようにhuman readableなフォーマットはYAML等に任せて、(Vimに入れる)JSONはただ他プログラムとの連携の仕事をするべきだ」
と言ったら

Bram「おそらく`jsencode()` / `jsdecode()`を追加すべきだとは思う」

と来たので、上2つの関数とテストを書いたパッチを提出すれば、`json*()`関数はJSON標準に準拠した物になる可能性が上がってきました！（同時に私のテンションも上昇中）

で、今書いてる途中に思ったのが、`js*()`関数を追加するとは言ったけど、`json*()`関数をJSON標準に準拠した物にするとは言ってないなと。
ただ、2つ追加すると言うことはおそらくJSON標準に準拠した関数を入れるべきだという認識はあるように思われるので、
- [ ] `json*()`関数をJSON標準に準拠した物にするという明確な言質を取る
- [ ] `js*()`関数のパッチを書く

が目下のタスクですかね。

**Comment by tyru** [comment]
ちなみに`jsonencode({"key": v:none})`が`{"key":}`を返す件に関して 7.4.1269 で修正が入ってたので確認した所、

``` viml
:echo jsonencode({"key": v:none})
E474: Invalid argument
{"key":}
```

という風にエラーは出るんですが依然として戻り値として返ってきてしまっている状態です。
この結果が意図的なのかどうかは質問して、回答 / パッチ待ちです。

**Comment by tyru** [comment]
> この結果が意図的なのかどうか

（Bramさん自身返すべき適切な値を検討中だったりして）意図的だったら、空のDictionaryなり何なりとにかくJSONとして正しい文字列を返した方が良いと個人的には思うので、そう提案してみるつもりです。
（Vim scriptの仕様上？ただ例外を投げて終わり、って形にできないのが面倒ですね…
`delete()`なんかもエラー出力と`-1`を返すという形になってますし）

**Comment by tyru** [comment]
> 返すべき適切な値

Lingrでコメント書いてて思い付いたけど、今なら空のDictionaryを返すより `v:null` を返した方がよさそうな気がしますね。

**Comment by tyru** [comment]
> `jsonencode({"key": v:none})`が`{"key":}`を返す件

7.4.1270 で異常時には `v:none` が返るようになりました。
`v:none`は`js*()`関数を入れるという妥協案を示してくれている以上、
これ以上「削除して！」とは言えないのでこれに関しては概ね予想通りです。
Bram++

**Comment by tyru** [comment]
> 7.4.1270 で異常時には `v:none` が返るようになりました。

おっと…
これに関して今朝(7.4.1273)また `git pull && make` して確認したところ、
Bramさんは特に意図して修正した訳ではないようで、

> When there is an error it returns what it has.  Would it be better to
> return nothing?

と返ってきました。
なので、`v:none`を返すのが良いと思うよ、と返しておきました。

あと「もし私が`jsencode()`と`jsdecode()`の関数のパッチを書いたら取り込んでくれるか？」という問に対しては "Feel free to make a patch." という事で、取り込んでくれるつもりではあるようです。

**Comment by tyru** [comment]
エラーの時は空文字が返るようになりました！
`v:none`や`v:null`じゃない理由は

> Well, let's just return an empty string.  Returning a different type 
> often makes it more complicated.

との事で、その通りだと思いました(変数に入っている値の型が違うと再代入の際にエラーが出るため？)。

**Comment by tyru** [comment]
`js*()`関数のパッチは`json*()`関数がJSON標準になるようテストファーストで進めていく必要がありそう。
結構面倒だぞこれ…

**Comment by thinca** [comment]
とかなんとか言ってるうちに `jsencode()` と `jsdecode()` が入りましたね。

https://groups.google.com/d/topic/vim_dev/WrqeOI6Wwm0/discussion

```
Patch 7.4.1279
Problem:    jsonencode() is not producing strict JSON.
Solution:   Add jsencode() and jsdecode().  Make jsonencode() and jsondecode()
            strict.
```

**Comment by tyru** [comment]
ヤッター！

# indent pluginsでやる気を見せてから要求が通りやすくなった気がするぞい
