### ISSUE TITLE
分割されたウインドウで 'set scroll&' するとエラーになる

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#815]
https://twitter.com/h_east/status/677152178671247360

```
vim -Nu NONE
:split
:set scroll&
E49: Invalid scroll size: scroll&
```

条件 : `winheight(0) < Rows/2` のときエラーになります。

`Rows` : (Vim 起動時の) 画面行数

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/4b6a6dc/src/option.c#3784

ここで `scroll` のデフォルト値 (`options[*].def_val[VI_DEFAULT]`) が `Rows >> 1` に設定されます。
この値がウインドウによらずプロセス中固定値になることが原因です。

https://github.com/vim/vim/blob/4b6a6dc/src/option.c#4556

`set scroll&` すると上記の値が設定されますが、

https://github.com/vim/vim/blob/4b6a6dc/src/option.c#8843

ここで検証され `curwin->w_height` より大きい場合はエラーになります。

また、(端末サイズを変更するなどして) Vim の表示行数を減らした場合も `scroll` のデフォルト値は変わらないため、この状態ではウインドウ分割なしでも `set scroll&` はエラーになります。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/393a939d48c26a03768c

`set scroll=0` すると `win_comp_scroll()` で (本来の仕様の) デフォルト値 = `w_height/2` になるので、`options[*].def_val[VI_DEFAULT]` を設定する必要はないのでは、という変更。

**Comment by h-east** [comment]
あっ、すっかり忘れてた。↓見て思い出したけどまた忘れっちゃった。follow-upありがとうございます。:stuck_out_tongue_winking_eye:
https://groups.google.com/d/topic/vim_dev/Njb5RruNQ2Q/discussion

patch LGTM:+1:です。
testを添えるとperfectですね。

**Comment by ichizok** [comment]
ありがとうございます。
あとで test 出しておきます。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/0f99eaee993a58ef9487

test.
ウインドウの状態が違うので単独と `test_alot.vim` 両方に入れましたが、片方だけで十分？

書いてて気づいたんですが、patch 前は `&scroll` の初期値と `set scroll&` 後の値が違いました。

80x24 の端末上で

```
vim -Nu NONE
:set scroll?
11
:set scroll&
12
```

初期値は `w_height/2` でデフォルト値は `Rows/2` だからですね

**Comment by ichizok** [comment]
投げました。
https://github.com/vim/vim/pull/2104

**Comment by ichizok** [comment]
todo入り
https://github.com/vim/vim/commit/37c64c78fd87e086b5a945ad7032787c274e2dcb#diff-38d7929bd26d74d92ceddf984bbfc8dbR202

**Comment by ichizok** [comment]
8.0.1237
https://github.com/vim/vim/commit/af2d20c6285c1d2973e3d9b5e8f727e3ed180493
