### ISSUE TITLE
ファイル選択ダイアログでのIM状態がGVimに反映されてしまう

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#82]
<code>:browse w</code> 等でファイル選択ダイアログを出し、IMをONにしてダイアログを閉じると、GVimにIM状態が反映されてしまいます。
ノーマルモードでIMがONになってしまうのはよろしくないので修正すべきだと思います。

GVim 7.3.284 +kaoriya Win32 on WinXPで確認しました。

他OSではどうなるのかも気になります。
<code>:help :browse</code> には<code>{only in Win32, Athena, Motif, GTK and Mac GUI}</code>と書かれてます。

**Comment by h-east** [comment]
こうですか？全OS対応。
WinXPのみ動作確認OK。

``` diff
diff -r f530aef0d959 src/message.c
--- a/src/message.c     Wed Oct 12 22:02:14 2011 +0200
+++ b/src/message.c     Sat Oct 15 18:31:07 2011 +0900
@@ -3720,6 +3720,9 @@
     static char_u      *last_dir = NULL;    /* last used directory */
     char_u             *tofree = NULL;
     int                        save_browse = cmdmod.browse;
+# ifdef USE_IM_CONTROL
+    int                        org_im_stat = im_get_status();
+# endif

     /* Must turn off browse to avoid that autocommands will get the
      * flag too!  */
@@ -3855,6 +3858,11 @@
        }
     }

+# ifdef USE_IM_CONTROL
+    /* Restore the Input Method. */
+    im_set_active(org_im_stat);
+# endif
+
     vim_free(tofree);
     cmdmod.browse = save_browse;
```

**Comment by ynkdir** [comment]
linux + gtk2 で動作確認。
linux + gtk2 ではパッチなくても off になります。
というよりダイアログでのIMのon/offはgvim本体に影響しないみたいです。
ということで gtk2 では動作に影響なさそうなので大丈夫だと思います。

**Comment by h-east** [comment]
@ynkdir 確認ありがとうございます。

Windows特有の問題なら gui_w48.c の gui_mch_browse() に持っていった方が良いですね。
そもそもなんで本体のim状態が変わるのか？Ownerのウインドウプロシージャが呼ばれてるんかな？
<code>fileStruct.hwndOwner = s_hwnd;</code>

どなたかMacの人、(Athena, Motifの人)、再現する/しないの連絡お待ちしてます。

**Comment by mattn** [comment]
vimのソース的には、`org_im_stat`より`old_im_stat`の方がいいかも。

**Comment by mattn** [comment]
> @h-east: patchあるけど、Windowsのみのバグのくせに message.c を修正してて「それでいいの？」状態です。 in #130

これは一度提案した方がいいと思う。bramの好き嫌いもあるだろうし。

**Comment by mattn** [comment]
僕はこのパッチで問題ないと思います。

**Comment by h-east** [comment]
送りました。
https://groups.google.com/d/topic/vim_dev/_tweFRjNNTM/discussion

**Comment by mattn** [comment]
@h-east ++

**Comment by h-east** [comment]
todoリスト入り。

> Patch for input method status. (Hirohito Higashi, 2012 Apr 18)
