### ISSUE TITLE
matchstrpos() の提案 

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#822]
https://gist.github.com/ichizok/4601620f1630ad15e720

**動機**

文字列に対して繰り返しパターン検索＆処理を行いたい場合、マッチ位置 (or マッチ文字列) とマッチ終端を求めるのに `match() or matchstr()` と `matchend()` で二度同じ検索をする必要がある。

``` vim
while 1
  let ret = matchstr(str, pat, idx)
  if ret ==# '' | break | endif
  " ret について何か処理
  let idx = matchend(str, pat, idx)
endwhile
```

マッチ情報をまとめて返せば、無駄を省ける。

**`matchstrpos({expr}, {pat} [, {start} [, {count}]])`**

`{expr}` が string の時 `[{マッチ文字列}, {マッチ位置}, {マッチ終端}]` を返す。

``` vim
echo matchstrpos("testing", "ing")    " result: ['ing', 4, 7]
```

`{expr}` が list の時 `[{マッチ文字列}, {list の index}, {文字列中の index}]` を返す。

``` vim
echo matchstrpos([1, '__x'], '\a')    " result: ['x', 1, 2]
```

**Comment by tyru** [comment]
どうせなら戻り値の1番目は `matchlist()` の戻り値と同じにするのはどうでしょうか？ (ちょっとやり過ぎ？)

**Comment by ichizok** [comment]
> どうせなら戻り値の1番目は matchlist() の戻り値と同じにするのはどうでしょうか？ (ちょっとやり過ぎ？)

`matchstr + match + matchend` に比べて処理が増える (list に詰め込む) のがちょっと、と思ったんですが、Vim script 関数を二度呼ぶのに比べれば微々たるものでしょうし、返せる情報は全部返してもいい...?

**Comment by machakann** [comment]
これ何度か欲しいと思ったことがありました。特に `match()` と `matchend()` をセットで呼ぶことが多かったような気がします。ちなみに `match()` `matchend()` `matchstr()` をそれぞれ呼ぶよりもかなり速くなるんでしょうか？

**Comment by machakann** [comment]
ちょっと胡乱な感じですが試してみました。

テストコード
[test_matchstrpos.vim](https://gist.github.com/machakann/711c4c70c758731b807c)

結果

```
*** matchstr, match, matchend ***
0.338151
*** match, matchend (without packing to a list) ***
0.225985
*** matchstrpos ***
0.113947
```

別々に呼ぶより三倍、`match()` `matchend()` だけよりも二倍ぐらい速くてとてもよさそう。もしかして関数を呼ぶだけでかなり時間かかっている？

**Comment by ichizok** [comment]
`match()`, `match()`, `matchlist()`, `matchstr()`, `matchstrpos()` の内部はほぼ同じ処理なので、ベンチマークが呼び出し回数に比例するのは直観通りですね。

**Comment by machakann** [comment]
戻り値を

```
[{match()の戻り値}, {matchend()の戻り値}, {matchlist()の戻り値1}, {matchlist()の戻り値2}, ...]
```

と12要素のリストにするというのはどうでしょう？

**Comment by machakann** [comment]
と、言ったはいいものの3要素のほうが使いやすいような気がしてきました。

**Comment by ichizok** [comment]
いっそ `matchlist()` の各要素にマッチ開始／終端位置を追加することもできます。

```
[ [{\0}, {start_idx0}, {end_idx1}], [{\1}, {start_idx1}, {end_idx1}], ...]
```

ここまでやるなら別の関数がよさそうですが...

**Comment by machakann** [comment]
便利そうですけど、確かに別物になっていますね。(`matchlistpos()` とか？)

個人的にはもとの `matchstrpos()` があれば `map()` と組み合わせてほぼ同じことができるのでいいかな、と思います。もちろん遅くはなるでしょうけど、数の制限はないですし。私はあまり `matchlist()` を使ったことがなかったのでこう考えるのかもしれません。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/1_QhLgRzueA

結局、最初の形で提案しました。

**Comment by tyru** [comment]
@ichizok ++

**Comment by machakann** [comment]
楽しみです！

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/328da0d/runtime/doc/todo.txt#L107
todo に入りました。

**Comment by machakann** [comment]
[patch 7.4.1685](https://github.com/vim/vim/commit/7fed5c18f8577b75404b80d8b9a9907b1bbd27e4) これですかね？

**Comment by ichizok** [comment]
ですね。
list を渡した時の戻り値は `[{マッチ文字列}, {list の index}, {マッチ位置}, {マッチ終端}]` になりました。

``` vim
echo matchstrpos([1, '__x'], '\a')    " result: ['x', 1, 2, 3]
```

**Comment by ichizok** [comment]
index は最後に置いたほうがきれいだったかも

**Comment by h-east** [comment]
@ichizok patch今ならまだ間に合いますよ:+1:

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/xy1VRwNQbqA

そのように提案してみました。
