### ISSUE TITLE
pythonのバージョンが違うと落ちる?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#823]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">+kaoriya版のVimでVimFilerを使っててドライブ選択でC:やらを選択するとVimが落ちていた(Win7 64bit)。色々調べたら、python34.dllが必要なのにPythonのバージョンを3.5にしたのが原因っぽかった。もっと勉強せねば。 <a href="https://twitter.com/hashtag/vim?src=hash">#vim</a></p>&mdash; クローチェ (@croce1) <a href="https://twitter.com/croce1/status/698901146102947840">2016, 2月 14</a></blockquote>

仮に観測が正しくて python が理由だとしても、落ちるのはマズイ。
エラーになって落ちるならわかる。あえて合理的な理由を考えるなら、 
VimFilter にネィティブなコンパイル済み python モジュールが同梱されてて
みたいなパターンだろうか。

あと python 絡みなら、たぶん +kaoriya は関係ない。

**Comment by Shougo** [comment]
呼ばれたような気がしたので来ました。

上記の報告で vimfiler を使用すると落ちているのは、ファイルリストの日付の取得に if_python3 を使用しているためです。
ネィティブなコンパイル済みモジュールなどは使用していません。
だから上記の環境では vimfiler を使わなくても、普通に `:python3` を実行するだけで落ちるはずです。

**Comment by mattn** [comment]
たぶん僕が直した[コレ](https://groups.google.com/forum/#!topic/vim_dev/6XZjcVLH8GY)じゃない？知らんけど。

**Comment by k-takata** [comment]
> たぶん僕が直したコレじゃない？知らんけど。

VCだと関係ない気が。
#610 かなあ？微妙に違う気もしますが…

**Comment by h-east** [comment]
@mattn ツイート日が2/14なので2/16リリースの Patch 7.4.1332 は無罪です。

**Comment by mattn** [comment]
なるほど

**Comment by koron** [comment]
> #610 かなあ？微妙に違う気もしますが…

あぅ、こんなのありましたねぇ… 知らないうちにpy2exeか…

**Comment by koron** [comment]
一応、当人に調査を依頼しました。
python34.dllがパスのどこかに無いか、問い合わせています。

**Comment by koron** [comment]
#610 でした。

Python 3.4 をアンインストールした際に python34.dll だけが C:\Windows\System32 に残っていた模様。

やはり何かしら対策が必要そうですね。

**Comment by koron** [comment]
#610 の duplicated としてこちらは閉じます。
