### ISSUE TITLE
job_getchannel が Windows で動かない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#824]
https://gist.github.com/mattn/7669319349f19a1773b6

``` vim
let job = job_start("tee")
let handle = job_getchannel(job)
echo ch_sendraw(handle, "echo something\n")
call ch_close(handle)
call job_stop(job)
```

このスクリプトで `echo something` が戻ってくる事は確認しました。

**Comment by mattn** [comment]
現状の問題点として ch_close してからじゃないと job_stop (非 kill) が効かないという物があります。

**Comment by mattn** [comment]
なんかこう channel と job が絡んでくると、はたしてソケットをオープンする ch_open という関数名はこれでいいんだろうか、という気になってくる。

**Comment by k-takata** [comment]
`saAttr.bInheritHandle = TRUE` しているのに、さらに `SetHandleInformation` で `HANDLE_FLAG_INHERIT` を指定しないといけないのでしょうか。

**Comment by k-takata** [comment]
すみません、勘違いです。
継承しないように、フラグを落としていたのですね。

**Comment by k-takata** [comment]
test_channel.vim の Test_pipe() を有効化するパッチも一緒に入れたほうがいいんじゃないでしょうか。

**Comment by mattn** [comment]
ありがとうございます。修正しました。

**Comment by k-takata** [comment]
> 現状の問題点として ch_close してからじゃないと job_stop (非 kill) が効かないという物があります。

もしかして、job_getchannel() を実行するかどうかに関係なく効かなかったりします？
test_channel.vim 実行したら python.exe が大量に残ってしまいました。

https://gist.github.com/mattn/7669319349f19a1773b6#file-vim-job-control-fix-diff-L328
`HANDLE process` 不要ですね。

**Comment by mattn** [comment]
job にひもづいてる channel を close してから終了する様にしました。問題も消えました。

**Comment by k-takata** [comment]
```
From test_channel.vim:
Found errors in Test_pipe():
function Test_pipe line 9: Expected 'something^@' but got 'something^M^@'
function Test_pipe line 11: Expected 'Goodbye!^@' but got 'Goodbye!^M^@'
```

うーむ、改行コードの違いが…

**Comment by mattn** [comment]
あれ？なんだろ。僕の所では出ません。

**Comment by ynkdir** [comment]
WaitForSingleObject() は pipe 待てましたっけ?

**Comment by mattn** [comment]
PeekNamedPipe を使うという意味ですか？

**Comment by mattn** [comment]
UNIX でもひもづいてる channel を close する様にしました。

**Comment by ynkdir** [comment]
> PeekNamedPipe を使うという意味ですか？

それか overlapped io とかですか。
どうするのがいいんですかね。
すみませんよくわからないです。

**Comment by mattn** [comment]
OverwrappedResult で取る様にしてみました。

**Comment by mattn** [comment]
おっと CloseHandle

**Comment by k-takata** [comment]
> あれ？なんだろ。僕の所では出ません。

msys2のpythonだとLF改行になっているとか？
pythonの改行コードをLFに固定するか、test_channel.vimでCRを削除してから比較するかのどちらかですかね。(後者の方が簡単？)

**Comment by mattn** [comment]
後者にしましょうか。

**Comment by mattn** [comment]
手を入れました。といっても僕んとこで再現しないので未検証です。

**Comment by k-takata** [comment]
数行上の ch_readraw(handle) の方も対応必要です。
"\n" まで削るとまずいと思います。

**Comment by mattn** [comment]
なんかわかった気がする。僕んところ、1つもテストが走ってない。

**Comment by k-takata** [comment]
> "\n" まで削るとまずいと思います。

ああ、結果のほうからも削っていましたか。

> なんかわかった気がする。僕んところ、1つもテストが走ってない。

ｗｗｗ

**Comment by mattn** [comment]
うわーーーー

``` vim
if has('unix')
  " We also need the job feature or the pkill command to make sure the server
  " can be stopped.
  if !(executable('python') && (has('job') || executable('pkill')))
    finish
  endif
elseif has('win32')
  " Use Python Launcher for Windows (py.exe).
  if !executable('py')
    finish
  endif
else
  " Can't run this test.
  finish
endif
```

**Comment by mattn** [comment]
そりゃ動かんわw

**Comment by mattn** [comment]
これ py じゃなきゃダメな理由ってあるんですっけ

**Comment by k-takata** [comment]
特に無し。

**Comment by mattn** [comment]
うひw

**Comment by mattn** [comment]
出た

```
From test_channel.vim:
Found errors in Test_pipe():
Caught exception in Test_pipe(): Vim(let):E896: read from channel: The operation completed successfully. @ function Test_pipe, line 10
```

**Comment by k-takata** [comment]
一応、こんな風に直そうかなというパッチは用意していますが。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/ac87ef399d7bcc732f5c0a8409c738f32c162f7f/use-py-exe-if-available.patch?fileviewer=file-view-default
（Test_pipeには未対応）

**Comment by k-takata** [comment]
> 特に無し。

しいて言えば、公式のインストーラを使ってデフォルトオプションでインストールすると、py.exe はPATHの通ったところにインストールされますが、python.exe にはPATHが通らないので。

**Comment by k-takata** [comment]
前から思っているのですが、テストがスキップされたときは何らかのメッセージが表示されてほしいですね。

**Comment by mattn** [comment]
あ！NGなのは僕がNGになる様に弄ったからでした。これで正しいテストが出来る。

**Comment by mattn** [comment]
こうしたら通りました。

``` diff
diff --git a/src/testdir/test_channel.vim b/src/testdir/test_channel.vim
index 0e87899..eb85b4c 100644
--- a/src/testdir/test_channel.vim
+++ b/src/testdir/test_channel.vim
@@ -14,8 +14,7 @@ if has('unix')
     finish
   endif
 elseif has('win32')
-  " Use Python Launcher for Windows (py.exe).
-  if !executable('py')
+  if !executable('python')
     finish
   endif
 else
@@ -34,7 +33,7 @@ func s:run_server(testfunc)
     if has('job')
       let s:job = job_start("python test_channel.py")
     elseif has('win32')
-      silent !start cmd /c start "test_channel" py test_channel.py
+      silent !start cmd /c start "test_channel" python test_channel.py
     else
       silent !python test_channel.py&
     endif
@@ -77,7 +76,7 @@ func s:kill_server()
       unlet s:job
     endif
   elseif has('win32')
-    call system('taskkill /IM py.exe /T /F /FI "WINDOWTITLE eq test_channel"')
+    call system('taskkill /IM python.exe /T /F /FI "WINDOWTITLE eq test_channel"')
   else
     call system("pkill -f test_channel.py")
   endif
@@ -280,16 +279,21 @@ func Test_connect_waittime()
 endfunc

 func Test_pipe()
-  if !has('job') || !has('unix')
+  if !has('job')
     return
   endif
   let job = job_start("python test_channel_pipe.py")
   call assert_equal("run", job_status(job))
   try
     let handle = job_getchannel(job)
+
     call ch_sendraw(handle, "echo something\n", 0)
-    call assert_equal("something\n", ch_readraw(handle))
+    let reply = ch_readraw(handle)
+    let reply = substitute(reply, '\r', '', '')
+    call assert_equal("something\n", reply)
+
     let reply = ch_sendraw(handle, "quit\n")
+    let reply = substitute(reply, '\r', '', '')
     call assert_equal("Goodbye!\n", reply)
   finally
     call job_stop(job)
```

すみませんが、test_channel.vim については py の部分と合わせて送ってもらえますか。

**Comment by k-takata** [comment]
> すみませんが、test_channel.vim については py の部分と合わせて送ってもらえますか。

では帰宅後にでも。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/KVUDn6uBBXE

お願いしまーす

**Comment by mattn** [comment]
> if !has('job') || !has('unix') || !has('win32') || !has('win64')

UNIX 消しましたがこういう方が良いのかな。お任せします。

**Comment by k-takata** [comment]
https://gist.github.com/mattn/7669319349f19a1773b6#file-vim-job-control-fix-diff-L32-L33
ここ、if が false だと、CloseHandleが2回呼ばれません？

**Comment by ynkdir** [comment]
GetOverlappedResult() が hEvent を使うみたいなのでその前に閉じるのはまずそうな気がします。
あとたぶんタイムアウトで抜けるときは CancelIO() が必要かと思います。

```
fd_read():
  72             DWORD res = WaitForSingleObject(ol.hEvent, timeout);
  73             CloseHandle(ol.hEvent);
  74             if (res == WAIT_OBJECT_0
  75                     || GetOverlappedResult(buf, &ol, &nread, FALSE))
  76                 return nread;
```

**Comment by mattn** [comment]
@ynkdir これでどうでしょうか？

``` c
    int
fd_read(sock_T fd, char_u *buf, size_t len, int timeout)
{
    DWORD nread = (DWORD) -1;
    OVERLAPPED ol;
    ZeroMemory(&ol, sizeof(ol));
    ol.hEvent = CreateEvent(0, 0, 0, 0);
    if (!ReadFile(fd, buf, len, &nread, &ol))
    {
    if (GetLastError() == ERROR_IO_PENDING)
    {
        if (WaitForSingleObject(ol.hEvent, timeout) == WAIT_OBJECT_0)
        GetOverlappedResult(buf, &ol, &nread, FALSE);
        else
        CancelIo(fd);
    }
    }
    CloseHandle(ol.hEvent);
    return (int) nread;
}
```

**Comment by ynkdir** [comment]
いいと思います。

**Comment by mattn** [comment]
あざます。

**Comment by ynkdir** [comment]
warning がたくさんでてますね

**Comment by mattn** [comment]
まーじーでー

**Comment by ynkdir** [comment]
vim.exe はコンパイル通らないです

**Comment by mattn** [comment]
なんで mingw だと警告1つも出ないんや

**Comment by mattn** [comment]
なおしました。

**Comment by mattn** [comment]
union でやった方がきれいだったかな。。。

**Comment by k-takata** [comment]
MinGWは警告握りつぶしていますからねー。多少余計に警告が出ようとも有効にしたほうがいいのではという気がしています。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/ac87ef399d7bcc732f5c0a8409c738f32c162f7f/mingw-enable-warnings.patch?fileviewer=file-view-default

**Comment by mattn** [comment]
そっちもお願いしときます。なんで無効になってたんやろ。。。

**Comment by ynkdir** [comment]
ありがとうございます。
いちおうまだ警告でてます。動作には支障なさげですが。
キャストしても警告でるので困りますね。

```
channel.c(68): warning C4267: '関数': 'size_t' から 'DWORD' に変換しました。データが失われているかもしれません。
channel.c(86): warning C4267: '関数': 'size_t' から 'DWORD' に変換しました。データが失われているかもしれません。
channel.c(1381): warning C4311: '型キャスト': ポインターを 'sock_T' から 'int' へ切り詰めます。
channel.c(1386): warning C4311: '型キャスト': ポインターを 'sock_T' から 'int' へ切り詰めます。
channel.c(1799): warning C4311: '型キャスト': ポインターを 'sock_T' から 'int' へ切り詰めます。
channel.c(1800): warning C4311: '型キャスト': ポインターを 'sock_T' から 'int' へ切り詰めます。
channel.c(1801): warning C4311: '型キャスト': ポインターを 'sock_T' から 'int' へ切り詰めます。

channel.c(68): warning C4267: '関数': 'size_t' から 'DWORD' に変換しました。データが失われているかもしれません。
channel.c(86): warning C4267: '関数': 'size_t' から 'DWORD' に変換しました。データが失われているかもしれません。
channel.c(393): warning C4047: '関数': 間接参照のレベルが 'SOCKET' と 'sock_T' で異なっています。
channel.c(393): warning C4024: 'WSAAsyncSelect': の型が 1 の仮引数および実引数と異なります。
channel.c(457): warning C4047: '関数': 間接参照のレベルが 'SOCKET' と 'sock_T' で異なっています。
channel.c(457): warning C4024: 'WSAAsyncSelect': の型が 1 の仮引数および実引数と異なります。
```

**Comment by mattn** [comment]
型変えました。

**Comment by ynkdir** [comment]
__int64 はたぶん mingw でだめっぽいです

**Comment by k-takata** [comment]
そうでしたっけ？

**Comment by mattn** [comment]
修正前は __int64 でした。

**Comment by mattn** [comment]
mingw32 かな？

**Comment by ynkdir** [comment]
あれ、そうですか。勘違いかもです。

**Comment by mattn** [comment]
いちおう WIN64 に戻しておきました。

**Comment by ynkdir** [comment]
すいません勘違いでした。
vim のコンパイルではなく簡単なテストプログラムを cc でコンパイルしたらエラーがでたのでダメかと思ったんですが gcc なら大丈夫でした。

**Comment by ynkdir** [comment]
> いちおう WIN64 に戻しておきました。

WIN64 は定義されてないみたいなので _WIN64 か WIN32 に戻すかでお願いします。すみません。

**Comment by k-takata** [comment]
_WIN64 がよいと思います。

**Comment by mattn** [comment]
パッチ当てる前が WIN64 だったけど良くない？

**Comment by k-takata** [comment]
意図通り動いていなかった可能性…

**Comment by ynkdir** [comment]
ReadFile() がブロックしちゃいますね。

**Comment by ynkdir** [comment]
oh...

Anonymous Pipe Operations
https://msdn.microsoft.com/en-us/library/aa365141(VS.85).aspx

> Asynchronous (overlapped) read and write operations are not supported by anonymous pipes. This means that you cannot use the ReadFileEx and WriteFileEx functions with anonymous pipes. In addition, the lpOverlapped parameter of ReadFile and WriteFile is ignored when these functions are used with anonymous pipes.

**Comment by mattn** [comment]
ってことは PeekNamedPipe 使ってグルグル回せと

**Comment by ynkdir** [comment]
たしか Named Pipe はノンブロッキングできます。

**Comment by mattn** [comment]
PeekNamedPipe でグルグル回すようにしました。

**Comment by ynkdir** [comment]
GUI=yes のときにコードが有効になってないです。
sleep はなくて大丈夫ですかね。どうなんでしょう。
fd_read() の timeout が削除し忘れてます。

**Comment by ynkdir** [comment]
channel_gui_register_one() でパイプに対して WSAAsyncSelect() が呼ばれてます。

**Comment by ynkdir** [comment]
関係ないですけど channel_wait() で GUI でも select() しないとタイムアウトが機能しないような

**Comment by k-takata** [comment]
いろいろ取り込まれました。

7.4.1323: Do not get warnings when building with MingW.
https://groups.google.com/d/topic/vim_dev/pvup8Tx8m50/discussion
7.4.1324: Channels with pipes don't work on MS-Windows.
https://groups.google.com/d/topic/vim_dev/sZqktDqPvV4/discussion
7.4.1327: Channel test doesn't work if Python executable is python.exe.
https://groups.google.com/d/topic/vim_dev/58EI57aF1fs/discussion

**Comment by k-takata** [comment]
そして、7.4.1324でコンパイルできないという指摘。
https://groups.google.com/d/topic/vim_dev/n6Syi7Rs8qI/discussion
なぜだ？

**Comment by ynkdir** [comment]
vim.exe が CHANNEL=no でコンパイルできないです

**Comment by ynkdir** [comment]
gvim.exe もでした > CHANNEL=no でコンパイルできない

**Comment by mattn** [comment]
追加修正依頼 https://gist.github.com/mattn/baec9ece5749d2d90368

**Comment by mattn** [comment]
> 関係ないですけど channel_wait() で GUI でも select() しないとタイムアウトが機能しないような

別件でやりましょう。

**Comment by k-takata** [comment]
7.4.1330: fd_read() has an unused argument.
https://groups.google.com/d/topic/vim_dev/skG5rjP733M/discussion
7.4.1335: Can't build on MS-Windows with +job but without +channel.
https://groups.google.com/d/topic/vim_dev/zAsTYPEZ2Vs/discussion

お疲れさまでした。閉じます。
