### ISSUE TITLE
channel の動作を統一したい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#825]
job_start、job_getchannel で得た handle を非同期に読み込みたいが、ch_readraw に callback が指定出来ない。ただしコード上、省略引数になっているので Bram がやりかけの可能性あり。

**タイトル修正**
- callback を指定していない時はブロッキング
- callback を指定している時は非同期

という動きにしたい。

**Comment by mattn** [comment]
https://gist.github.com/mattn/d6198b38d9b18edcb2aa

これで

``` vim
function! Callback(id, msg)
  echo a:msg
endfunction
let g:job = job_start("tail -f logfile")
let handle = job_getchannel(job)
call ch_readraw(handle, {"callback": "Callback"})
```

こんな事が出来るようになった！これちょこっとだけ改造すれば別バッファでログを見ながらコーディング出来る様になる！

**Comment by mattn** [comment]
あかん。カーソル劇重や

**Comment by mattn** [comment]
sendraw/sendjson も対応、ただしGUIはトリガが無いので今の所 select 系でしか動作しない。
カーソル劇重については4回に1回処理するハックで対応。

**Comment by mattn** [comment]
Windows は暫定的にカーソルのブリンクで発動させるようにした。
なんとかしたいけど思いつかない。スレッド？

**Comment by mattn** [comment]
カーソルブリンクはフォーカス外れると走らないのでやはり CUI と同じ様にループ内に入れました。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/qtw5LdCrHJQ

**Comment by mattn** [comment]
Bram とちょっと方針が違った様なので閉じます。

**Comment by k-takata** [comment]
閉じますということなので閉じます。

**Comment by koron** [comment]
Bram との方針の違い & 開発が活発な機能についてのバグ・提案ということだったので、wontfixに分類しました。
