### ISSUE TITLE
mingw で警告が大量に出る

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#826]
https://gist.github.com/mattn/6542c52e98dce6923fc3

**Comment by mattn** [comment]
char\* と char_u\* は許して欲しい感ある

**Comment by mattn** [comment]
os_mswin.c がまだ。あと言語拡張系はどうしても取れない。

**Comment by k-takata** [comment]
https://gist.github.com/mattn/6542c52e98dce6923fc3#file-gistfile1-diff-L523
ここ、コンマの後に空白を入れたほうがよいでしょう。（元がそうでしたが。）

**Comment by mattn** [comment]
os_mswin.c 済。残は

https://gist.github.com/mattn/cc9284dc20cb714f424b

言語拡張は放置で。

**Comment by k-takata** [comment]
os_mswin.c 以外に対するパッチが消えているようです。

**Comment by mattn** [comment]
失礼しました。.oO(ブランチにコミットしたの忘れて git diff しちゃったなんて)

**Comment by mattn** [comment]
VCでビルドエラーになった。 → 直しed

**Comment by mattn** [comment]
あと3つ！

```
getchar.c: In function 'check_map':
getchar.c:5221:7: warning: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Wstrict-overflow]
    if (len + 3 > mp->m_keylen)
       ^
undo.c: In function 'u_save_cursor':
undo.c:268:6: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
      || top >= bot
      ^
In file included from uninstal.c:21:0:
dosinst.h:456:1: warning: 'add_pathsep' defined but not used [-Wunused-function]
 add_pathsep(char *name)
 ^
```

**Comment by mattn** [comment]
YATTA! 警告消えた

**Comment by k-takata** [comment]
https://gist.github.com/mattn/6542c52e98dce6923fc3#file-remove-warnings-diff-L267-L269
https://gist.github.com/mattn/6542c52e98dce6923fc3#file-remove-warnings-diff-L278
ここは、`#ifdef __GNUC__` か何かで囲ったほうがいいです。VCでwarningが出るので。

**Comment by mattn** [comment]
なるほどあざます

**Comment by mattn** [comment]
疲れてきたので出しed

https://groups.google.com/forum/#!topic/vim_dev/-2lLZ5Z2cPM

**Comment by k-takata** [comment]
7.4.1334
https://groups.google.com/d/topic/vim_dev/QhWsvbK8bj4/discussion
7.4.1339
https://groups.google.com/d/topic/vim_dev/ghGgkkSGKXA/discussion
お疲れさまでした。

**Comment by k-takata** [comment]
Bramが一部取り込まなかった部分がありますが、どうしますかね？
https://groups.google.com/d/msg/vim_dev/-2lLZ5Z2cPM/QQWIf225DwAJ

（そのせいもあって）まだいくつかwarningが出ているようです。
https://groups.google.com/d/topic/vim_dev/6ta3sQG1WlA/discussion
https://groups.google.com/d/topic/vim_dev/0MJxiUUlR1Q/discussion
https://groups.google.com/d/topic/vim_dev/YtFXCrtG0TA/discussion
https://groups.google.com/d/topic/vim_dev/ZnGSvwOJZ_4/discussion

**Comment by k-takata** [comment]
```
patch 7.4.1339
Problem:    Warnings when building the GUI with MingW. (Cesar Romani)
Solution:   Add type cats. (Yasuhiro Matsumoto)
```

よく見ると、猫を追加したそうだｗ

**Comment by mattn** [comment]
ww

**Comment by koron** [comment]
猫ってそれかw パッチの中見てもわからなかったから、なんなんだろって思ってたwww

**Comment by mattn** [comment]
一旦閉じますかね。
