### ISSUE TITLE
Windows GUI で channel_read がハングし得る

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#827]
#824 より。GUI では select していないのでいきなり read するとブロックする。

**Comment by ynkdir** [comment]
ソケットは read でブロックではなく channel_read_json_block() の待ちループで入力が来るまでぐるぐるしてます。
ch_sendexpr() は response が来るまで返らない。
ch_readraw() は入力がない場合にタイムアウトを待たずに即座に返る。

パイプは ch_sendexpr() も ch_readraw() も read でブロックします。

ここの FEAT_GUI_W32 を外すだけでいいんですが

``` c
1367     static int
1368 channel_wait(channel_T *channel, sock_T fd, int timeout)
1369 {
1370 #if defined(HAVE_SELECT) && !defined(FEAT_GUI_W32)
```

Some problems with channel 
https://groups.google.com/d/msg/vim_dev/BwmhkJIm6bo/E12aXPewCwAJ

メッセージループを止めるのがいやということですね。

**Comment by mattn** [comment]
個人的な意見で言うと、callback が指定されて無かったら blocking でもいいかなーと思います。

**Comment by mattn** [comment]
#825 のパッチでやりたいと思います。
