### ISSUE TITLE
templates for vim/vim

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#830]
## 質問・報告の内容

新たに導入された issue と PR の templates を、[vim/vim](https://github.com/vim/vim) に提案しませんか?
https://github.com/blog/2111-issue-and-pull-request-templates
## その他

どんなテンプレートが良いのかは研究の余地があります。

**Comment by thinca** [comment]
新機能便利そう…!
まずはこのリポジトリ(`vim-jp/issues`)で試しに導入してみてもいいかもしれないですね。
(不具合報告なのか、新機能提案なのか、わからないことの相談なのかで、テンプレート変えたい場合とか出てきそう)

**Comment by thinca** [comment]
> まずはこのリポジトリ(vim-jp/issues)で試しに導入してみてもいいかもしれないですね。

あ、すでにやってますね…(#829)。見落としてましたw

**Comment by koron** [comment]
そしてこのissue自体が、テンプレートを使って作られたものでしたw

**Comment by mattn** [comment]
項目数を増やし過ぎても誰もやらなくなるメソッドだと思うのでgolangがやってたくらいがちょうどかなと覆いました。

```
What steps will reproduce the problem?


What do you see instead?


Which compiler are you using (5g, 6g, 8g, gccgo)?


Which operating system are you using?


Which revision are you using?  (hg identify)

```

vim で言えば

```
What steps will reproduce the problem?


What do you see instead?


Which version of vim are you using?


Which operating system are you using?
```

これくらいだろうか。

**Comment by koron** [comment]
@mattn :+1: 良さそう。

**Comment by k-takata** [comment]
GitHubのジェネレーターを使って作ったテンプレートをもとにPRを出してみた。
https://github.com/vim/vim/pull/4183
Bug reportとFeature request用の2つ。

**Comment by k-takata** [comment]
8.1.1067: https://github.com/vim/vim/commit/723d165c2fcd9f94af4e8719feda3b70c8f46868
取り込まれたので、閉じます。
