### ISSUE TITLE
ヘルプ pattern.txt にリンクを追加の提案

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#831]
## 質問・報告の内容

[pattern.txt 1105行目](https://github.com/vim-jp/vimdoc-ja-working/blob/master/en/pattern.txt#L1105-L1108)

> ```
> These items only work for 8-bit characters, except [:lower:] and
> [:upper:] also work for multi-byte characters when using the new
> regexp engine.  In the future these items may work for multi-byte
> characters.
> ```

新しい正規表現エンジンへの言及があるので `|two-engines|` などのリンクがあると親切ではないでしょうか。two-engines タグは同一ファイル内ですが、およそ800行ほど上なのでタグジャンプなどでこの記述にたどり着いた方にはわかりづらいかと思います。ほとんどの人は二つの正規表現エンジンを意識せずにVimを使っていると思うのであったほうが親切かと思います。

``` diff
diff --git a/runtime/doc/pattern.txt b/runtime/doc/pattern.txt
index 2a3d2c4..7a49bc1 100644
--- a/runtime/doc/pattern.txt
+++ b/runtime/doc/pattern.txt
@@ -1104,8 +1104,8 @@ x A single character, with no special meaning, matches itself
      '/', alphabetic, numeric, '_' or '~'.
      These items only work for 8-bit characters, except [:lower:] and
      [:upper:] also work for multi-byte characters when using the new
-     regexp engine.  In the future these items may work for multi-byte
-     characters.
+     regexp engine. |two-engines| In the future these items may work for
+     multi-byte characters.
                            */[[=* *[==]*
    - An equivalence class.  This means that characters are matched that
      have almost the same meaning, e.g., when ignoring accents.  This
```
## その他

https://github.com/vim-jp/vimdoc-ja-working/issues/5#issuecomment-185736810 から誘導されてきました。

**Comment by koron** [comment]
nice catchです! :+1: :cake:

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/03413f44167c4b5cd0012def9bb331e2518c83cf#diff-2fe866632f9a6aa5e9f6196649a07e68R1107
修正済みですので、閉じます。
