### ISSUE TITLE
MingW ではなく MinGW である事をどの様に Bram に伝えるか

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#832]
vim-dev を見る限り、Bram は MinGW を MingW と書き間違えている。
どの様にして気付いて貰うか。

**Comment by k-takata** [comment]
重要な課題だｗ

**Comment by ujihisa** [comment]
15文字で表現すると、 `s/MingW/MinGW/g` とか

**Comment by crazymaster** [comment]
**Min**imalist **G**NU for **W**indows の略ですからねw

**Comment by anekos** [comment]
```
abbr MingW MinGW
```

**Comment by mattn** [comment]
@anekos www

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/4KDITY-fg2s/Jmcs7o6TEAAJ

ん～、それで通じますかね。BramはMingWが正しいと思っているじゃないですかね。

**Comment by tyru** [comment]
「元の単語から言って MingW じゃなく MinGW が正しいんじゃないか」位で指摘しちゃった方が良い様な気がします。

**Comment by mattn** [comment]
伝わっていなかった
https://groups.google.com/forum/#!topic/vim_dev/e0-njBqgP5I

**Comment by tyru** [comment]
ww

**Comment by k-takata** [comment]
もしかしてミッションコンプリート!?
https://groups.google.com/d/topic/vim_dev/QAke2rRdxOE/discussion

> Problem:    Can't build with older MinGW compiler.

**Comment by koron** [comment]
`status/patched` 付けちゃったw

**Comment by mattn** [comment]
感動のフィナーレ
