### ISSUE TITLE
twitter アカウントの vim_jp さんが最近 issues をポストしなくなった。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#833]
僕は vim_jp さんじゃないので良く知らないのですが、どうやら yahoo! pipes を使ってたのが原因って言ってました。

**Comment by tyru** [comment]
vim_jp さんかっこいい

**Comment by mattn** [comment]
作ったので渡しておきます。

https://github.com/vim-jp/post_issues

**Comment by mattn** [comment]
無事に復活された様です。

https://twitter.com/vim_jp/statuses/700574276928217089

**Comment by tyru** [comment]
:tada:

**Comment by k-takata** [comment]
> https://github.com/vim-jp/post_issues

せんせー、description も README もないのでぜんぜんわかりません！
