### ISSUE TITLE
:command-complete のそれぞれの補完を Vim script から取得できるようにしたい

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#835]
## 質問・報告の内容

タイトルの通り、:command-complete のそれぞれの補完を Vim script から取得できるようにしたいです。
`complete=customlist,Func` の `Func()` の中でしばしば組み込みのExコマンド補完(`augroup,buffer,...`)を使用したい時があります。
なので、それらの関数を Vim script でも扱えるようになると嬉しいです。
引数は -complete=customlist に指定する関数と同じ `(ArgLead, CmdLine, CursorPos)` が良いです。
## Vimのバージョン

新機能の提案です。
## OSの種類

全ての OS で使用できると嬉しいです。

**Comment by koron** [comment]
タイトルと、本文の書き出しを修正しました。

要望なのに疑問形で終わるのと、「タイトル通りです。」が主文なのは、おかしかったので。

**Comment by tyru** [comment]
ありがとうございます！

**Comment by koron** [comment]
https://github.com/vim-jp/issues/issues/37#issuecomment-6881757

> todo.txt 3782行目にこんなの見つけました。
> 
> > 8   Custom completion of user commands can't use the standard completion
> >     functions.  Add a hook to invoke a user function that returns the type of
> >     completion to be done: "file", "tag", "custom", etc.

**Comment by tyru** [comment]
それを関数から使えるようにするのはどうか？ってBramさんに提案すればいいんですかね。

**Comment by tyru** [comment]
投げました。
https://groups.google.com/forum/#!topic/vim_dev/KOjY_Sass6E

**Comment by mattn** [comment]
一応貼っておきます。

https://github.com/mattn/vim-completer

**Comment by thinca** [comment]
7.4.2011 で `getcompletion()` が追加されました。

> 引数は -complete=customlist に指定する関数と同じ (ArgLead, CmdLine, CursorPos) が良いです。

この条件は満たしてませんが、`ArgLead` にあたる `{pat}` が渡せるので、十分かと思います(問題があればリオープン or 新規 Issue お願いします)。

https://groups.google.com/d/topic/vim_dev/nLkIZLmHNAc/discussion

```
patch 7.4.2011
Problem:    It is not easy to get a list of command arguments.
Solution:   Add getcompletion(). (Yegappan Lakshmanan)
```
