### ISSUE TITLE
なぜruntime/doc/tagsをgitの管理下に置いているのか？

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#836]
質問です。

なぜ、bramさんはruntime/doc/tagsをgitの管理下に置いているのか？
理由をすでにご存知の方がいましたら教えてください。

宜しくお願い致します。

**Comment by tyru** [comment]
自分も疑問です。

Vim 起動時に `'runtimepath'` の全てのパスに対して `:helptags` しているので、
Vim のリポジトリの tags が毎回 modified になってしまってます。
(逆に言うと tags が最新でないから modified になっているのですが、そもそも tags は含めなくて良いはず)

**Comment by h-east** [comment]
「:helptags しなくてもちゃんと :help が索けるように」ですかね？
「毎回ちゃんとhelpのtagsも更新してcommitしてくれよー」ってBramにお願いするだけじゃダメ？

**Comment by tyru** [comment]
あーそうか。
普通に考えて $VIMRUNTIME は *nix では書込専用だし、`:help` で引くためには事前に tags がないとダメですね。
ただ make install 時に tags を生成してくれればいいような気もしますが、
tags 含めておけば runtime を cp するだけでいいんですね。

**Comment by rbtnn** [comment]
@h-east 

> 「毎回ちゃんとhelpのtagsも更新してcommitしてくれよー」ってBramにお願いするだけじゃダメ？

この方法でもよいと思います。@tyru さんと同じくtagsがmodifiedになるのが気になるだけなので。

**Comment by h-east** [comment]
了解です。意図は分かりました。 (vim_devに投稿するとは言っていない)

**Comment by h-east** [comment]
`make` か `make test` の時に `:helptags ../runtime/doc` を実行するように仕込みましょうか。

**Comment by rbtnn** [comment]
> make か make test の時に :helptags ../runtime/doc を実行するように仕込みましょうか。

:+1:

**Comment by h-east** [comment]
あれ？ 今でも `vim/src` で `make installvim` とか `make installruntime` ってやると更新されますね。やってないのかな？

**Comment by h-east** [comment]
どっちにしてもBram氏にお願いすべきですね。

**Comment by rbtnn** [comment]
`src/configure.in` で生成はしているっぽい？

**Comment by k-takata** [comment]
runtime/doc/tags は通常のパッチではほとんど更新されず、基本的にはruntimeファイルの更新のタイミングで更新されてますね。
意図的なのかどうかは分かりませんが。

**Comment by tyru** [comment]
Bram さんにお願いしてみました。
https://groups.google.com/forum/#!topic/vim_dev/4hTzoRmYMcQ

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/ArzKA6Ff7C4

**Comment by k-takata** [comment]
@mattn 7.4.1415は、AppVeyorでtagのpush時にビルドしないようにしただけです。

検索してみると、今までに何回か話題に上がっていますね。
runtime/doc/tags under Mercurial control.
https://groups.google.com/d/topic/vim_dev/qBkRDaXd9sk/discussion
Is it possible to ignore runtime/doc/tags in .hgignore?
https://groups.google.com/d/topic/vim_dev/sB49rhMSTFk/discussion
runtime/doc/tags not ignored.
https://groups.google.com/d/topic/vim_dev/2hWFvsIShk4/discussion

**Comment by mattn** [comment]
はい。閉じずに関連リンクとして書いたつもりで tag 違いでした。

**Comment by rbtnn** [comment]
patch 7.4.1556
https://github.com/vim/vim/commit/a3442cb5056ca62fc71fa03f68a9395e4391caf4

**Comment by mattn** [comment]
閉じますか？

**Comment by rbtnn** [comment]
はい
