### ISSUE TITLE
json_decode がサロゲートペアを扱えない。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#838]
json_encode はエスケープしてないので放置。

https://gist.github.com/mattn/6f6c9349c6c4130277ca

あとでテスト足します。 :sushi:

**Comment by mattn** [comment]
ついでにマルチバイトの仕様変えました。
json_encode された文字列は utf-8 である必要がある。なぜならば `\u` 表記と混合出来るし、だとすると enc=utf-8 以外だと壊れてしまう。json_decode も utf-8 を貰う前提にしてあります。

**Comment by 0xBADDCAFE** [comment]
:sushi:  :sushi:  :sushi:

**Comment by mattn** [comment]
てか、json なんだから FEAT_MBYTE 関係ないんじゃないかなー。
FEAT_MBYTE じゃない場合に `\uXXXX` が `\uXXXX` って文字列にデコードされて嬉しい人おらんで。

**Comment by k-takata** [comment]
一応todo.txtには、記載されていますね。

```
- json: implement UTF-16 surrogate pair.
```

**Comment by k-takata** [comment]
そろそろFEAT_MBYTEは常に有効になりませんかね。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/jYUO1bHl1lg

テストに寿司絵文字をねじ込んでやった。

**Comment by k-takata** [comment]
test_channel.vim の修正が紛れ込んでいます。

**Comment by mattn** [comment]
oops

**Comment by k-takata** [comment]
Related: https://github.com/vim/vim/issues/584 https://github.com/vim/vim/issues/613

**Comment by k-takata** [comment]
直そうとして直っていないように見えます。

**Comment by mattn** [comment]
gist のエディタって CTRL-F から検索できないのつらい。

**Comment by k-takata** [comment]
7.4.1434
https://groups.google.com/d/topic/vim_dev/fQz1QeTPX94/discussion

**Comment by k-takata** [comment]
テストが変な位置に追加されていました。
https://groups.google.com/d/msg/vim_dev/fQz1QeTPX94/R7-JH6NzEwAJ
