### ISSUE TITLE
job-options の exit-cb ハンドラーが実行されるまでに10秒以上かかる場合がある

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#839]
## 質問・報告の内容

現在[実行した外部プログラムをバッファに表示する簡単なVimプラグイン](https://github.com/tyru/jobby.vim)を作っています。
しかし例えば `sleep 2` 等を実行してみても`exit-cb`ハンドラーが実行されるまでに10秒以上かかる場合があります。

![c224bce9e62f6cb0e9dae0b439606597](https://cloud.githubusercontent.com/assets/48169/13319213/7cac9c14-dc03-11e5-8422-1681a8475d8b.png)

`:help job-exit-cb` には Vim はプロセスの生死を10秒毎にチェックするとあり仕様通りという事は理解したのですが、これを SIGCHLD 等で代替することはできないでしょうか？
(Windows や他OSでの実装が難しい？)
## Vimのバージョン

7.4.1412
## OSの種類
-   Linux
## OSのディストリ

Arch Linux
## 使用している or 関係していそうなプラグイン

https://github.com/tyru/jobby.vim

**Comment by tyru** [comment]
ping
今のコードでは実装が難しいのでしょうか？

**Comment by koron** [comment]
単純にまだ興味の範囲外なんじゃないでしょうか。
Linux限定であれば実装は、ちょっと面倒な部分はあるものの、
そう難しくはないでしょう。

SIGCHLDを受けるにしても、どのジョブが終わったか(または本当に終わったか)はわかりませんから、
Vimは管理している全部のジョブのステータスを確認する必要がありそうです。
そのためパフォーマンスが想定以上に悪くなる可能性があります。

一方でVimスクリプト関数の `job_status()` を呼べば、強制的に即座にチェックできそうです。
頻繁に呼び出してみてパフォーマンス上の問題がでなければ
実装してみる価値はあるかもしれません。(私自身は実装するつもりはありませんが :wink:)

また単にジョブの終了にセンシティブなプラグインを作りたいのであれば、
`job_status()` を頻繁に呼んでしまうだけのほうが、手っ取り早いでしょう。

なおWindowsでは一筋縄でいかないのはそのとおりです。

**Comment by tyru** [comment]
@koron なるほどです。ありがとうございます！！

**Comment by mattn** [comment]
おそらくチェックはシグナルでなくポーリングになると思いますがプロセスの生き死にチェックも若干はコストなので現状は10秒になってます。管理するプロセスが多くなるとテキスト編集中に刺さるのでいまは興味の対象外になってしまってますね。

**Comment by tyru** [comment]
なるほど。
とりあえず`job_status()`で逐一確認することにします。
ありがとうございます。

**Comment by mattn** [comment]
あ、open のままでいいです

**Comment by koron** [comment]
特定のプロセスが終わったって、通知的に分かる方法があると良いんですけどねぇ。
シグナルに対象となるプロセスIDが乗ってくるだけでも違う。

**Comment by mattn** [comment]
WaitForMultipleObject すればできるんでしょうけどね。

**Comment by thinca** [comment]
これ可能なら Vim 8.0 までに欲しいですが、やはり難しいですかね…?
もしくは 10 秒の部分をオプションにするとかなら行けるでしょうか(ユーザーの責任で変更と言う感じで)。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/fe9743f46822a9015ed2f7d65238c5db
os_unix: `waitpid(-1, &status, WNOHANG)` を呼ぶ
os_win32: `WaitForMultipleObjects` を `[実行 job 数] / MAXIMUM_WAIT_OBJECTS(==64)` 回呼ぶ
としてみました。
win32 は `WaitForMultipleObjects` を複数回呼ぶのが難 (というか、これで正しいのかも不明)

**Comment by ichizok** [comment]
AppVeyor が test_channel で止まる...
https://ci.appveyor.com/project/ichizok/vim/build/126
追記: `mch_detect_ended_job` が無限ループになっていた

**Comment by ichizok** [comment]
とりあえず動いています。
`job_check_ended` 内で `waitpid` は高々 `MAX_ENDED_JOB_COUNT(==8)` 回、
`WaitForMultipleObjects` も多くの場合は高々 1*`MAX_ENDED_JOB_COUNT` 回呼び出しで済むと思うので、
パフォーマンスへの影響は限定できると見ています。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/VeMBWwOPtms
提案しました。

**Comment by ichizok** [comment]
8.0.0036 で入りました。
https://github.com/vim/vim/commit/97792de2762cc79cc365a8a0b858f27753179577

**Comment by tyru** [comment]
ありがとうございます！！

**Comment by h-east** [comment]
`:h job-exit_cb`の以下の記述は変更した方がよさそうですね。

> Vim checks about every 10 seconds for jobs that ended.

どなたかお願いします。

**Comment by h-east** [comment]
`exit_cb`は今まで通り10秒周期でチェックされていて、job終了後即時コールされていないという認識ですがあっていますか？
(8.0.0036で直ったのは明らかに`exit_cb`呼ばれるまでに10秒以上掛かっているのが直ったという認識です)
(今後、10秒周期を短くする提案をするのはあり)

jjj.vim

``` vim
func! JobExitCallback(job, stat)
    echom reltimestr(reltime(g:job_start_time)) "sec"
endfunc

func! JobGo(cmd)
    let g:job_start_time = reltime()
    let job = job_start(["sh", "-c", a:cmd], {"exit_cb": "JobExitCallback"})
    echom job
endfunc
```

$ vim -Nu NONE -S jjj.vim
:call JobGo("sleep 1")

`4.005714 sec`

引数 "sleep 0.1" ～ "sleep 3.9" の場合は常に4秒ちょい、
"sleep 4.0" ～ "sleep 9.9" の場合は常に10秒ちょい、
"sleep 10" だと 16秒ちょい

※試した環境: fedora 23 x86_64, CUI Vim 8.0.45 on PuTTY

**Comment by h-east** [comment]
Windows環境で試そうと`job_start()`の第1引数を`["cmd", "/C", "timeout /T 5 /NOBREAK"]`で呼んだら、`JobExitCallback()`が即呼ばれて第2引数(exit status)が1なんですがどうすればいいですか？

**Comment by mattn** [comment]
last_check で10秒判定するロジックは削除されているので少なくとも「10秒以内」といったリテラル値は無いと思います。
即時というのにも表現誤差がありますが、SIGCHLD 等を使っている訳ではないので完全な即時ではないです。
イベントループで parse_queued_messages が呼ばれるタイミングになるので、sleep が終了して次のアイドルタイムが終了検知のタイミングになります。なので`プロセス終了までの時間+アイドルまでの時間`になります。

**Comment by ichizok** [comment]
job の参照が外れると `(10000 - &updatetime)` msec の間隔でチェックされるようです。
調査します。

**Comment by mattn** [comment]
@ichizok マークされてるのは速いけど、マークされなかった奴は gc まで待たされて遅くなる、という事ですか？

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/master/src/os_unix.c#L492-L506
GCではないようですが、jjj.vim の場合、この部分で終了チェックされていました。

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/master/src/os_unix.c#L5712-L5722
ここの `channel_poll_setup()` &rarr; `poll()` で job-channel の EOF が検出できるんですが、
job の参照がないと job から channel が detach されてしまうのでそれが不可になると。

**Comment by ichizok** [comment]
ということは、先に stdout, stderr を閉じておくと (job の参照があっても) 即時検出はできないですね...

``` vim
let g:job = job_start(['python', '-c', 'import os,time;os.close(1);os.close(2);time.sleep(1)'], {'exit_cb': 'JobExitCallback'})
```

(検出まで4秒くらい)

**Comment by h-east** [comment]
> https://github.com/vim/vim/blob/master/src/os_unix.c#L492-L506
> GCではないようですが、jjj.vim の場合、この部分で終了チェックされていました。

調査ありがとうございます。
コメントと実装があっていないような気がしますね。。

**Comment by mattn** [comment]
これって unix だけなんすかね

**Comment by h-east** [comment]
@mattn ↓の対処法教えて下さい～
https://github.com/vim-jp/issues/issues/839#issuecomment-254791024

**Comment by mattn** [comment]
@h-east timeout コマンドが標準入力をサポートしてないんだと思います。

```
C:\dev\vim\src>echo 1 | c:\windows\system32\timeout /T 5 /NOBREAK
エラー: 入力のリダイレクトはサポートされていません。今すぐプロセスを終了します。

C:\dev\vim\src>echo %ERRORLEVEL%
1
```

```
let s:job = job_start(["cmd", "/C", "start /wait c:\windows\system32\timeout /T 5 /NOBREAK"], {"exit_cb": "JobExitCallback"})
```

で行けるかと思います。窓が気になる場合は `/min` などを。

**Comment by mattn** [comment]
Windows だとほぼ即時ですね。

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/bb09ceb/src/os_win32.c#L1349-L1353
Windows は 100msec 間隔でチェックしているようです。
- unix でも `has_pending_job()==TRUE` の条件下で 100msec 間隔でチェックする
  https://gist.github.com/ichizok/c7daad6267816173ac5c38f4c8848dd2  

`has_pending_job()` は
- `exit_cb` を持つが channel 資源がない (== job-channel の EOF がプロセス終了検出のトリガーにならない) job があるか確認

に変更しました。

テストですが、`sleep` の中で 100msec 間隔の終了チェックしているので
修正前でも fail にできないですね...
https://gist.github.com/ichizok/c7daad6267816173ac5c38f4c8848dd2/09fc683dacb244f0051f74e205ce4fed6f3d09cd#file-job-alive-check-patch-L157-L165

**Comment by h-east** [comment]
@ichizok :+1:
issue reopenしますね。

**Comment by ichizok** [comment]
@h-east 了解です。

`getchar()` で待って、timer で `feedkeys()` するとfailにできました。
https://github.com/ichizok/vim/blob/fe28589/src/testdir/test_channel.vim#L1388-L1405

**Comment by ichizok** [comment]
https://groups.google.com/d/msg/vim_dev/VeMBWwOPtms/CYgUQPnFBgAJ
報告しました。

**Comment by h-east** [comment]
`:h job-exit_cb`の3行目

```
            Vim checks about every 10 seconds for jobs that ended.
```

は削除するか値を`100msec`に変更するかした方が良い？

**Comment by ichizok** [comment]
100msec は特定の状況下ですし、削除でもいいような気はします。

**Comment by h-east** [comment]
patch 8.0.0050 :+1:
https://github.com/vim/vim/commit/01688ad545ff0809ddad5c8fa6b149dc5d67312b

**Comment by mattn** [comment]
ドキュメントの10秒は修正の必要がありそう？

**Comment by h-east** [comment]
@mattn ichizokさんが報告済みなので次回のUpdated runtime files時に反映されるはずです。

**Comment by koron** [comment]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">8.0.0050から、test_channel.vimで無限待ちに落ちてる...? GUIだけ?</p>&mdash; sakamoto.kazuki (@splhack) <a href="https://twitter.com/splhack/status/791864834706935808">2016年10月28日</a></blockquote>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">Test_exit_callback_interval、MacVimのウインドウがアクティブじゃないと、帰ってこない。Travis-CIのGUI環境がどうなってるかわからないけど、おそらく同じ現象。</p>&mdash; sakamoto.kazuki (@splhack) <a href="https://twitter.com/splhack/status/791866634512113664">2016年10月28日</a></blockquote>

これら、関係しているかしら?

**Comment by splhack** [comment]
MacVim GUIで`GUI_FLAG=-fg make test_channel`する場合に限りますが、patch 8.0.0049までは問題なかったです。50以降、GUIがアクティブじゃないと帰ってこなくなります。メッセージループがまわってないとダメかなと。

**Comment by ichizok** [comment]
https://github.com/vim/vim/blob/14207f4/src/testdir/shared.vim#L139-L165
8.0.0050 で追加したテストでは `getchar()` と `feedkeys()` を使って wait するんですが、
MacVim だと、ウィンドウがアクティブでないと `getchar()` が返ってきませんでした。
(8.0.0046 で確認)
なので、この issue 自体は関係ないですね。

sample.vim:

``` vim
fu! TimerCb(timer)
  echom 'TimerCb' reltimestr(reltime(g:start))
  call feedkeys(' ', 'nt')
endfu
fu! TimerStart(msec)
  let g:start = reltime()
  let g:_timer = timer_start(a:msec, 'TimerCb')
  call getchar()
  echom 'Finish.' reltimestr(reltime(g:start))
endfu
call TimerStart(2000)
```

```
:so sample.vim
TimerCb   2.005716
Finish.  35.613325
```

`:so sample.vim` してからウィンドウを非アクティブにすると、2秒後に `TimerCb` は表示されるが
`Finish.` はウインドウをアクティブにするまで表示されない。

**Comment by mattn** [comment]
getchar に問題があるなら macvim ではそのテストをスキップしてもらう方がいいのかな

**Comment by splhack** [comment]
ありがとうございます。skipするようにしました https://github.com/macvim-dev/macvim/commit/a6a61ecb87339341bc05ca2d0f69d0ee09252966

**Comment by h-east** [comment]
[vim/vim] Strange value of v:shell_error when calling system() with silent (#1196)
https://groups.google.com/d/msg/vim_dev/4aCzjHijM-o/hOyEmYJcAQAJ
これの現象がgit bisectの結果、[patch 8.0.0036](https://github.com/vim/vim/commit/97792de2762cc79cc365a8a0b858f27753179577)からのようです。

追記:
私の環境(fedora 23 64bit, CUI Vim 8.0.0045)では再現しませんね。

**Comment by ichizok** [comment]
&uarr;のスレッド、最初のいくつかのメッセージ発信者がなぜか私になっているんですが
私の環境だけでしょうか？（それともよくあること？）

**Comment by mattn** [comment]
どれでしょうか？

**Comment by ichizok** [comment]
https://groups.google.com/d/msg/vim_dev/4aCzjHijM-o/U0rbOhEJCAAJ (chrisbra)
https://groups.google.com/d/msg/vim_dev/4aCzjHijM-o/hOyEmYJcAQAJ (hexchain)
私の環境だとこの2つが発信者ichizokになっているんですが、正しく見えてますか？

**Comment by h-east** [comment]
@ichizok 以前vim_devに報告したことがあります。よく起こるという認識です。
The mail sent to the vim_dev by the trigger a comment write, to the github are sometimes mistakes a contributor.
https://groups.google.com/d/msg/vim_dev/Ih7PQP8ssbc/Fa68nRa-BgAJ

google groupsのバグらしいです。なかなか直らないですね。
どこに報告したらいいんだろう。

**Comment by mattn** [comment]
あー、vim-dev の話ですね。よく起きます。

**Comment by ichizok** [comment]
そうなんですか。github 側の issue は github で見ていたので気づかなかった...

**Comment by h-east** [comment]
https://github.com/vim-jp/issues/issues/839#issuecomment-257074582 の件、 @ichizok さんが書いたpatchが取り込まれました:+1:

patch 8.0.0071
https://github.com/vim/vim/commit/c4d4ac22f78fb1394c79eccc8a1e6812c0c7d8a7
