### ISSUE TITLE
wildmode=longest:fullで<Tab>を押した時の見た目がよくない

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#84]
#75 を見ていて思い出したのですが、`wildmode=longest:full`において`<Tab>`を押した時、

最初の項目がハイライトされていて選択されてるかのような印象を受けます。

http://d.hatena.ne.jp/tyru/20110114/vim_cmdline_completion
の「longest:fullの欠点」から引用

```
あ、今「longest:full」の新たな欠点に気がついた。
UIの問題なんだけど、longest:fullで<Tab>を押した時、
最初の項目がハイライトされてて選択されてるかのような印象を受ける(上の画像でも分かる通り)。
でもコマンドラインに挿入されてはいないので誤解する。
たとえば「:help c_ctrl-d<Tab>」と入力した場合、<Tab>によって次のような状態になる(:helpじゃなく:Helpになってるけど)。
```

![c_CTRL-D@](http://cdn-ak.f.st-hatena.com/images/fotolife/t/tyru/20110114/20110114202447.png)

```
見てわかる通り、このままエンターを押せば「c_CTRL-D@ のような項目はない」と言われる。
これはあと一回分の<Tab>が足りないためにこうなるわけで、誤解させるUIが悪いと思う。
慣れればコマンドラインのみを見て今は挿入されてないと判断できるのかもしれないけど。
```

解決案としてはハイライトさせずに他の候補と同じように背景白で表示させるのがいいかと思います。

**Comment by koron** [comment]
@tyru: +1

**Comment by mattn** [comment]
+1

**Comment by k-takata** [comment]
8.0.0528
https://groups.google.com/d/topic/vim_dev/n5J_QihUUuk/discussion
