### ISSUE TITLE
Windows の GVim で絵文字(サロゲートペア)を表示するとセルがずれる

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#840]
これは ambiwidth の問題ではなく描画の問題で、僕の記憶だと10年以上昔からあったバグ。
utf-8 で描画される場合は [ExtTextOutW](https://msdn.microsoft.com/ja-jp/library/windows/desktop/dd162713%28v=vs.85%29.aspx) が使われるのですが、この lpString の数と lpDx の数が異なっている事でズレが生じています。

問題のソース箇所は gui_w32.c の gui_mch_draw_string

``` c
for (i = 0; i < len; )
{
    c = utf_ptr2char(text + i);
    if (c >= 0x10000)
    {
        /* Turn into UTF-16 encoding. */
        unicodebuf[wlen++] = ((c - 0x10000) >> 10) + 0xD800;
        unicodebuf[wlen++] = ((c - 0x10000) & 0x3ff) + 0xDC00;
    }
    else
    {
        unicodebuf[wlen++] = c;
    }
    cw = utf_char2cells(c);
    if (cw > 2)                /* don't use 4 for unprintable char */
        cw = 1;
    if (unicodepdy != NULL)
    {
        /* Use unicodepdy to make characters fit as we expect, even
         * when the font uses different widths (e.g., bold character
         * is wider).  */
        unicodepdy[clen] = cw * gui.char_width;
        ↑ココ
    }
    cells += cw;
    i += utfc_ptr2len_len(text + i, len - i);
    ++clen;
}
```

本来、unicodebuf と unicodepdy で同じバイト位置に値が入らないといけないけど、サロゲートペアの場合にずれている。 

``` diff
diff --git a/src/gui_w32.c b/src/gui_w32.c
index edfe24e..e1a0d8b 100644
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -6658,7 +6658,13 @@ gui_mch_draw_string(
        /* Use unicodepdy to make characters fit as we expect, even
         * when the font uses different widths (e.g., bold character
         * is wider).  */
-       unicodepdy[clen] = cw * gui.char_width;
+       if (c >= 0x10000)
+       {
+           unicodepdy[wlen-2] = cw * gui.char_width;
+           unicodepdy[wlen-1] = 0;
+       }
+       else
+           unicodepdy[wlen-1] = cw * gui.char_width;
        }
        cells += cw;
        i += utfc_ptr2len_len(text + i, len - i);
```

この修正でズレなくなった。

**Comment by mattn** [comment]
家に帰ったら試せるけど今 Win10 機が無いので誰か試して貰えませんか。

**Comment by mattn** [comment]
あー、出たわー。

![](http://go-gyazo.appspot.com/c2b100b69297f493.png)

**Comment by k-takata** [comment]
> 10年以上昔からあったバグ。

`set rop=type:directx` してると問題ないので知りませんでした。

**Comment by sgur** [comment]
試してみました。(Win10 x64、gVim は mingw64 の gcc でビルド、renderoptionsなし)

表示しているのは[SKK-JISYO.emoji.utf8](https://github.com/uasi/skk-emoji-jisyo/blob/master/SKK-JISYO.emoji.utf8)です
- パッチ未適用
  ![no-patched](https://cloud.githubusercontent.com/assets/255021/13345622/979b43c2-dca3-11e5-9f54-0b7dac57298b.png)
- パッチ適用済
  ![patched](https://cloud.githubusercontent.com/assets/255021/13345628/ab141848-dca3-11e5-8f0f-1e8177341e97.png)

未適用の場合だと、カーソルが当たっているときに後ろにある`/`がズレて表示されますが、パッチ適用後は正常に表示されています。

**Comment by mattn** [comment]
あざます！

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/fAGaj23IhD4

**Comment by k-takata** [comment]
7.4.1429
https://groups.google.com/d/topic/vim_dev/jsaVNHkRAeY/discussion
