### ISSUE TITLE
gui_dwrite.cpp のコンパイルで警告が出る。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#841]
```
gui_dwrite.cpp:348:13: warning: deleting object of polymorphic class type 'GdiTextRenderer' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
      delete this;
```

``` diff
diff --git a/src/gui_dwrite.cpp b/src/gui_dwrite.cpp
index 08b81c4..52de208 100644
--- a/src/gui_dwrite.cpp
+++ b/src/gui_dwrite.cpp
@@ -237,7 +237,7 @@ public:
    AddRef();
     }

-    ~GdiTextRenderer()
+    virtual ~GdiTextRenderer()
     {
    SafeRelease(&pRenderTarget_);
    SafeRelease(&pRenderingParams_);
```

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/k16bga7YwhM

**Comment by koron** [comment]
:bow: & :+1: & :cake:

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/ZnGSvwOJZ_4/op_lUvpXEAAJ
このパッチでも別の方法で対応済み。どちらがよいかは知りません。
なお、if_oleでも同様の警告が出ます。

**Comment by mattn** [comment]
どちらでもいいと思います。IDWriteTextRenderer (もしくはその基底クラス)のデストラクタに virtual が付いてないのがそもそもなので。

**Comment by k-takata** [comment]
7.4.1428
https://groups.google.com/d/topic/vim_dev/C4sT49TCcQs/discussion
virtualの方が短くてC++ 11も必要ないということで、そっちが採用されました。

**Comment by k-takata** [comment]
if_ole.cppに対する類似修正 7.4.1442
https://groups.google.com/d/msg/vim_dev/HcS3yR_AEds/7WfgMVgwEwAJ
そしてなぜか私のパッチも採用 7.4.1610
https://groups.google.com/d/msg/vim_dev/CsZFmdgFL9c/Cd6l4M2eGQAJ
どちらかだけでよかったのに。
