### ISSUE TITLE
normal 以上のビルドに C99 が必要

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#842]
## 質問・報告の内容

json.c で `isinf()`, `NAN`, `INFINITY` の C99 features を使用しているため、
コンパイラが C99 対応でないとビルドできませんが、特に記載がないようです。
## Vimのバージョン

7.4.1407 以降
## その他

gcc は 4.1.3 ~ 4.4.7 の間のどこかでデフォルト設定 (`-std=gnu89`) が `C99 無効→有効`に変化しました。
それ以前では明示的に `-std=gnu99` を指定する必要があります。

デフォルト状態でビルドできない環境:
- CentOS 5
  - デフォルトコンパイラが gcc 4.1.2 なので、`-std=gnu99` が必要
- Solaris (OpenIndiana で確認)
  - ~~`-std=c99` のほか、`-D_XPG6 -D__EXTENSIONS__` のマクロも必要~~ `-std=gnu99` が必要

**Comment by h-east** [comment]
あら。

> gcc は 4.1 ~ 4.4 の間でデフォルト設定 (-std=gnu89) が C99 入りになっていました。

この文章の後半がよく分かんないです。

**Comment by k-takata** [comment]
BramはC89のつもりでやっているだろうから、指摘しておいたほうがいいでしょう。

**Comment by ichizok** [comment]
> > gcc は 4.1 ~ 4.4 の間でデフォルト設定 (-std=gnu89) が C99 入りになっていました。
> 
> この文章の後半がよく分かんないです。

すみません、`-std=gnu89` を指定すると C99 機能も有効になるという意味です。

**Comment by h-east** [comment]
なるほど。その流れでいくとCentOS 5のデフォルトコンパイラが `gcc 4.1.x`なのにNGなのがよく分からないです。

**Comment by ichizok** [comment]
> なるほど。その流れでいくとCentOS 5のデフォルトコンパイラが gcc 4.1.xなのにNGなのがよく分からないです。

重ね重ねすみません、つまり、

4.1.x &rarr; `-std=gnu89` 指定しても C99 機能は無効
4.4.x &rarr; `-std=gnu89` 指定すると C99 機能が有効

なので、4.1 ~ 4.4 の間で `-std=gnu89` の設定に変更があった、ということです。

CentOS 5 : gcc 4.1.2
CentOS 6 : gcc 4.4.7

で確認しています。

**Comment by h-east** [comment]
なるほどです。理解しました。
gcc は 4.1.3 ~ 4.4.7 の間のどこかでデフォルト設定 (-std=gnu89)の挙動が変更になった(C99 機能が無効→有効)ので、 gcc 4.1.2な`CentOS 5`はデフォルト状態でビルドできない。
ってことですね。

@ichizok Issue本文を修正させていただきました。

**Comment by syohex** [comment]
下記の enumの定義の末尾のカンマも C99からの機能です.

https://github.com/vim/vim/blob/a260b87d9da17f605666630f18c1ed909c2b8bae/src/alloc.h#L20

> -std=gnu89 を指定すると C99 機能も有効になるという意味です。
> gnu89 ⊃ c99

-std=gnu89はドキュメントにあるとおり一部の c99の機能を有効にするのであってC99機能の全てが使えるわけではありません. 例えば `for`文の初期化部での変数定義は c99では OKですが, gnu89ではNGです. (例: `for (int i = 0; i < n; ++i)`)

> gnu89
>    GNU dialect of ISO C90 (including some C99 features). This is
>    the default for C code.

**Comment by h-east** [comment]
> gcc は 4.1.3 ~ 4.4.7 の間のどこかでデフォルト設定 (-std=gnu89)の挙動が変更になった(C99 機能が無効→有効)ので、 gcc 4.1.2なCentOS 5はデフォルト状態でビルドできない。

なんか順序が違う＞俺

こうですね。
- CentOS 5 (gcc 4.1.2) だとコンパイルエラー (事実)
- CentOS 6 (gcc 4.4.7) だとOK (事実)
- gccはどちらも`-std`オプション指定なし。(デフォルトの`-std=gnu89`) (事実)
- →ということは 4.1.3～4.4.7の間のどこかで`-std=gnu89`の影響範囲が変わった？ (推測)
- その辺の追求はさておき、C89でビルドしていると思っているBram氏に報告しましょ。 (目的設定)

@syohex 情報thanksです。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/I2IVqA3CQv4
報告しました。

@syohex ありがとうございます。alloc.h の件も提示しました。

**Comment by ichizok** [comment]
@h-east 本文修正ありがとうございます。

**Comment by k-takata** [comment]
7.4.1427
https://groups.google.com/d/topic/vim_dev/OSq52N9Oz2k/discussion
7.4.1437
https://groups.google.com/d/topic/vim_dev/9olc_nsUcT4/discussion
7.4.1440
https://groups.google.com/d/topic/vim_dev/Kva7bAZQlMY/discussion
