### ISSUE TITLE
gvimからpythonが実行できない

### ISSUE THREAD

**Issue by sirokumasann** [vim-jp/issues#843]
## 質問・報告の内容

gvimからpython print(1)を実行すると、エラーE877が出て実行されません。
gvim、pythonとも、32bit版、64bit版それぞれ試しましたが、結果は同じでした。
## Vimのバージョン

7.4.???
( `:version` で確認できます)

:versionでリビジョンがどこに表示されているかわからなかったので、
ダウンロードしたzipファイル名を上げておきます。
vim74-kaoriya-win32-20160124.zip
vim74-kaoriya-win64-20160124.zip
## OSの種類
-   Windows
## OSのバージョン

windows 10 pro
## 使用している or 関係していそうなプラグイン

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
## その他

gvim、pythonとも、インストール直後で試しました。

**Comment by k-takata** [comment]
> エラーE877が出て実行されません。

E887の間違いだとすれば、Python 2.7.11のバグです。
- https://github.com/vim/vim/issues/526
- http://bugs.python.org/issue25824

以下のいずれかを試してみてください。
- Python 2.7.10に戻す。
- `PYTHONHOME` 環境変数に Python をインストールしたディレクトリを設定する。
- 以下のコマンドを実行し、レジストリのデータを修正する。

```
reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32
reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64
```

1行目が32bit用、2行目が64bit用です。

**Comment by sirokumasann** [comment]
回答ありがとうございます。

Python 2.7.10に戻してpythonが実行されることが確認できました。

**Comment by k-takata** [comment]
解決したようで何よりです。
一応 `:version` の確認方法を書いておきます。
以下のように表示されていると思います。

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 24 2016 13:30:36)
MS-Windows 32 ビット GUI 版
適用済パッチ: 1-1161
        ...
```

適用済パッチの部分の最後の数字が 1161 であることから、 7.4.1161 ということになります。

**Comment by sirokumasann** [comment]
ご教示ありがとうございます。
基本的な部分から教えていただき大変助かります。

**Comment by youkidearitai** [comment]
（ここに書いたほうがいいのかはわかりませんが、一応）

2.7.11で同じ問題に遭遇しまして、2.7.12で問題なくPythonがGvimから使えるようになりました。
ありがとうございます。

**Comment by k-takata** [comment]
報告ありがとうございます。本家にも報告しておきました。 https://github.com/vim/vim/issues/526#issuecomment-229792978
