### ISSUE TITLE
runtimepathとpackpathで検索パターンが異なる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#848]
## 質問・報告の内容

'runtimepath' オプション内の`plugin`下の`*.vim`検索パターンは`"plugin/**/*.vim"`だが、
'packpath' オプション内の同検索パターンは`"pack/*/ever/*/plugin/*.vim"`や`"pack/*/opt/name/plugin/*.vim"`となっており、`plugin`フォルダ直下に`*.vim`がない(けど`plugin/foo/bar.vim`はある)時の挙動が異なる。
この事で一部のプラグインがpackpath運用できない。

提案:
'packpath' オプション内の検索パターンを`"pack/*/ever/*/plugin/**/*.vim"`と`"pack/*/opt/name/plugin/**/*.vim"`に変更すべきか？
(ソースコード source_packages()とex_loadplugin（）の冒頭)
## Vimのバージョン

7.4.1444
## OSの種類

All

**Comment by miyakogi** [comment]
> この事で一部のプラグインがpackpath運用できない。

packpath運用できないプラグインですが、[vim-textobj-user](]https://github.com/kana/vim-textobj-user)を使っているプラグインが該当します。
例えば https://github.com/sgur/vim-textobj-parameter や https://github.com/h1mesuke/textobj-wiw などです。
他にも[こちら](http://d.hatena.ne.jp/osyo-manga/20130717/1374069987)で色々列挙されています。

**Comment by h-east** [comment]
Reported.
https://groups.google.com/d/msg/vim_dev/Myp-UUdfzxY/A5ffIy6iFAAJ

**Comment by h-east** [comment]
これを見る限り、分かっててやっている気がする。
https://groups.google.com/d/msg/vim_use/j1tBBhf8hVk/R-BjYhTcAwAJ

**Comment by h-east** [comment]
Bram氏からの回答
https://groups.google.com/d/msg/vim_dev/Myp-UUdfzxY/srGLOuSrFAAJ
やっぱり分かっててやってた。この件はもうちょっとDiscusされそう。

# 

それとは別で
Vim 7.4.1480で `:packadd`コマンドが追加されました。
このコマンドは指定されたパッケージ(`pack/*/opt/(パッケージ名)`)が 'packpath' オプションのpathから見つかれば、それを 'runtimepath' オプションに追加するものです。`*.vim`の有無は関係ないです。

このコマンドで賄えるようになったからクローズしていい？

**Comment by miyakogi** [comment]
ありがとうございます。
vim_devでの議論の結果次第な気がするので、私は一旦クローズしてしまっていいと思います。

**Comment by h-east** [comment]
Vim 7.4.1486で :loadpluginコマンドが廃止されて、:packaddコマンドに`!`が指定できるようになりました。
https://github.com/vim/vim/commit/f3654827368e6204608036353a0360e9e7c21e02

指定されたパッケージが 'packpath' オプションのpath + `pack/*/opt/(パッケージ名)`という構成で見つかれば、それを 'runtimepath' オプションに追加する。
`!`なしの場合は見つかったpath下の`plugin/*.vim`と`ftdetect/*.vim`を`source`する。但し、`ftdetect/*.vim`については、ファイルタイプ検出（これは通常、.vimrcファイル内の`syntax enable`か`filetype on`でおこなわれる）がまだ有効になっていなかった場合にのみおこなわれる。

**Comment by h-east** [comment]
patch 7.4.1699
https://github.com/vim/vim/commit/71fb0c146bef08dc276fc5793bd47366e6e0f32a

`:packadd`の`plugin`ディレクトリ下の検索パターンが`runtime`と同じ`plugin/**/*.vim`に変更になりました。

packpath運用できないと報告されていたプラグイン、例えば`vim-textobj-parameter`も`.vimrc`に以下のように書いてsourceされるようになりました。

``` vim
packadd vim-textobj-user
packadd vim-textobj-parameter
```

このIssueの問題は解消されたのでクローズします。

**Comment by h-east** [comment]
あー、`pack/*/start/`以下の場合、Vim起動時に自動的に`pack/*/start/{パッケージ名}/plugin/**/*.vim`を探してsourceされるから、依存関係あるパッケージはstartディレクトリ下に置けないですね。

依存関係を確実に解消させるにはoptディレクトリ下に置いて、一つ上のコメントのように明示するしかない？
