### ISSUE TITLE
役目を終えたレポジトリを削除する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#850]
## 質問・報告の内容

役目を終えた以下のレポジトリを削除したいです。
- https://github.com/vim-jp/vim
- https://github.com/vim-jp/vim-ci
- https://github.com/vim-jp/vim-obsoleted

反対意見がなければ 2016/03/31 を due date とします。

**Comment by k-takata** [comment]
vim-jp/vim は消してしまって構わないと思いますが、vim-jp/vim-obsoleted を消すのには反対です。古いissueには、旧vim-jp/vimへのリンクがあるものが多数あり、消してしまうと辿れなくなってしまいます。むしろ vim-jp/vim-obsoleted を vim-jp/vim に戻した方がよいのではないかとも思っています。

vim-ci は、不要になったとはいえ、2年間の歴史を葬るのはもったいない気もしますが…。

**Comment by koron** [comment]
現時点の「ほぼ決定」事項
- vim-jp/vim は消す
- vim-jp/vim-obsoleted は vim-jp/vim に名称変更。あわせて説明の修正も要る。

未決事項
- vim-jp/vim-ci どうしよう?

vim-ci に関わってた人間として「もったいない」は共感する。
ただノスタルジィみたいな感傷だけで、レポジトリを存続させるのにも疑問がある。
とくに事情を知らない人が見た時に、それが動いていない状況で放置されているか、
疑問に思うくらいならば無いほうが良いだろう。

説明に memorial で残してあるよ、と書けばそれで良いのだろうか。
誰か、どちら方向でも良いので、別の視点からの意見はないだろうか。

**Comment by koron** [comment]
vim-jp/vim の master+ci ブランチを削除しました。

**Comment by k-takata** [comment]
最近 archive という機能ができたようだし、vim-ci は archive にするのもありかな？

> むしろ vim-jp/vim-obsoleted を vim-jp/vim に戻した方がよいのではないかとも思っています。

vim-jp/vim を共同作業用リポジトリとして使いたいという意見もあるので、これは取りやめかな。

**Comment by koron** [comment]
ですね。vim-jp/vim は最新にして維持しましょう。

vim-ci とあわせて obsoleted も archive してしまっても良いかもしれない。

**Comment by koron** [comment]
まず vim-ci をアーカイブしてみます。
その結果がどうなるか見て、vim-obosleted を archive するか考えましょう。

**Comment by k-takata** [comment]
あ、vim-jp/vim-obsoleted の中身を orphan ブランチとして vim-jp/vim に入れてしまえば、古いissueにある旧vim-jp/vimへのリンクもそのままたどれるようになる？
（あまり変なことはしない方がいいかｗ）

**Comment by koron** [comment]
archived https://github.com/vim-jp/vim-ci

**Comment by koron** [comment]
vim-ci を archive してみて、vim-obsoleted も archive で良いかなと考えていますが、どうでしょうか?

**Comment by k-takata** [comment]
いいと思います。

**Comment by koron** [comment]
やりました。結果、こうなりました。

* vim-jp/vim 最新の vim/vim の fork として存続
* vim-jp/vim-ci アーカイブして readonly
* vim-jp/vim-obsoleted アーカイブして readonly

**Comment by koron** [comment]
アーカイブ機能増えててよかった。

**Comment by k-takata** [comment]
1年半放置した甲斐があったｗ
