### ISSUE TITLE
test 時の出力を寡黙に

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#851]
## 質問・報告の内容

continue from #414 

travis-ci でのテスト実行時、画面出力が頻繁にあることで、ログが見難くなっています。
加えてテストが遅くなっている可能性があります。
これを寡黙にすることで、テストにかかる時間を短縮したり、ログを見やすくできないでしょうか。
## OSの種類
-   Travis-Ci
-   Linux

**Comment by k-takata** [comment]
drone.io 上で現行のテストを動かしたらログが多すぎてエラーとなってしまいました。
こんな感じで出力を消したら、drone.io でも通るようになりました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/941c6bc7cdc5563330af79dd89b5864ac8df1908/test_reduce_test_log.patch?fileviewer=file-view-default
本当に消しても問題ないのかというのは気になるところですが。

**Comment by k-takata** [comment]
ついでに、Windows版のテストを少し静かにするパッチ
https://bitbucket.org/k_takata/vim-ktakata-mq/src/941c6bc7cdc5563330af79dd89b5864ac8df1908/make-tests-silent.patch?fileviewer=file-view-default

**Comment by koron** [comment]
output が tty じゃないことで、何かバグを踏むかってあたりですよね…

**Comment by k-takata** [comment]
ですね。ただ、Travisなどで出力をキャプチャしてWebに出していることを考えると実は変わらないのだろうかと思ったり思わなかったり。

**Comment by koron** [comment]
あ、その意味で言うと本当に怖いのは、ttyに繋がないことでなにかバグを見逃しうていないかって方なんですね。

**Comment by k-takata** [comment]
Windowsの方は投げました。
https://groups.google.com/d/topic/vim_dev/x40o6-lOiHE/discussion

**Comment by k-takata** [comment]
8.0.0145
https://groups.google.com/d/msg/vim_dev/UWEVCUfwTmA/1JvxIIaQBQAJ
Windowsの方は取り込まれました。

**Comment by k-takata** [comment]
2年越しのパッチを投げてみた。
vim/vim#3456

> あ、その意味で言うと本当に怖いのは、ttyに繋がないことでなにかバグを見逃しうていないかって方なんですね。

この懸念は残ったままですが。

**Comment by k-takata** [comment]
8.1.0424: https://github.com/vim/vim/commit/e76d7a63dfe916c321e248fbfc97bd948d6fbabb

**Comment by k-takata** [comment]
デフォルトではテスト中の画面表示は `/dev/null` に捨てられますが、`REDIR_TEST_TO_NULL` を空に設定することでリダイレクトを止めさせることができます。
