### ISSUE TITLE
sort() の {func} に 0 を渡しても string compare にならない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#852]
## 質問・報告の内容

ドキュメントによると

> When {func} is omitted, is empty or zero, then sort() uses the
> string representation of each item to sort on.  Numbers sort
> after Strings, |Lists| after Numbers.  For sorting text in the
> current buffer use |:sort|.

とあるが実行すると

```
E117: Unknown function: 0
E702: Sort compare function failed
```

というエラーが発生する。
## Vimのバージョン

7.4.1459

**Comment by mattn** [comment]
``` diff
diff --git a/src/eval.c b/src/eval.c
index a208b2a..40b9f64 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -19192,7 +19192,9 @@ do_sort_uniq(typval_T *argvars, typval_T *rettv, int sort)
        i = get_tv_number_chk(&argvars[1], &error);
        if (error)
            goto theend;    /* type error; errmsg already given */
-       if (i == 1)
+       if (i == 0)
+           info.item_compare_ic = FALSE;
+       else if (i == 1)
            info.item_compare_ic = TRUE;
        else
            info.item_compare_func = get_tv_string(&argvars[1]);
```

https://groups.google.com/forum/#!topic/vim_dev/Ap6ghQRDkM8

**Comment by k-takata** [comment]
7.4.1464
https://groups.google.com/d/msg/vim_dev/6dCbXPjywyY/KlLqnc7NEwAJ
7.4.1468
https://groups.google.com/d/topic/vim_dev/LdiHnE4QoJU/discussion
