### ISSUE TITLE
`:packadd`で無効な名前を指定してもエラーにならない（何も表示されない）

### ISSUE THREAD

**Issue by miyakogi** [vim-jp/issues#853]
## 質問・報告の内容

`:packadd`で無効な名前が指定されても何も表示されないため、typoしても気づきません。
エラーにするか、せめてロードできなかった等のメッサージが表示されると親切な気がします。
## Vimのバージョン

7.4.1486
## OSの種類

Kubuntu 15.10 64bit
## その他

有効な名前が限定されているので、タブ補完で有効な名前が表示されると便利だと思いました。
既存の機能だと`:colorscheme`のようなイメージです。
今は`:packadd<space><tab>`と入力するとカレントディレクトリ(?)のファイルが表示されます。
# 

備考:
Vim 7.4.1480で :packaddコマンドが追加され、Vim 7.4.1486で :loadpluginコマンドが廃止されたのでタイトル及びIssue本文を修正しました。

**Comment by h-east** [comment]
> 有効な名前が限定されているので、タブ補完で有効な名前が表示されると便利だと思いました。

:+1: 確かに！

**Comment by h-east** [comment]
`:loadplugin<space><tab>`時の補完動作、鋭意製作中。
実装終わってデバッグ中。

**Comment by h-east** [comment]
> :loadpluginで無効な名前が指定されても何も表示されないため、typoしても気づきません。

現状では `set verbose=3`でメッセージ出ます。
:loadplugin の場合は「not found」のエラーと「n plugin(s) loaded」等のメッセージは出した方が良いですね。

**Comment by h-east** [comment]
> :loadplugin<space><tab>時の補完動作

https://gist.github.com/h-east/493946fa91773dbb6e5b
#848 で`plugin/**/*.vim`に変更になったらちょっと賢く探すように変更しないといけないかも。

メッセージは今夜以降。

**Comment by h-east** [comment]
~~TODO: コマンド補完の表示フォルダ名決定処理はsource_pack_plugin()の実装を参考にして修正する。~~

**Comment by h-east** [comment]
:loadplugin廃止と:packadd追加に追従。test書かなきゃ。
https://gist.github.com/h-east/493946fa91773dbb6e5b

**Comment by h-east** [comment]
test追加。
https://gist.github.com/h-east/493946fa91773dbb6e5b

**Comment by h-east** [comment]
`:packadd` のコマンドライン補完対応は取り込まれました。
patch 7.4.1492
https://github.com/vim/vim/commit/35ca0e7a1cb6e6daef8e0052a8437801226cef19

**Comment by h-east** [comment]
エラー処理出力追加patchをvim_devに送りました。
https://groups.google.com/d/msg/vim_dev/EV2Y1Gfsjik/vrZ5-X1tFQAJ

**Comment by miyakogi** [comment]
:+1:

**Comment by h-east** [comment]
patch 7.4.1499
https://github.com/vim/vim/commit/be82c254862e475a582c0717455e1db6bf96b0d0

これで本Issueでの問題点は解決したのでクローズします。
@miyakogi Issue登録ありがとうございました:+1:
