### ISSUE TITLE
vim の python の扱いについて

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#858]
Ubuntu 16.04 から python3 が標準となり python2 は purge 対象となるので vim でどう扱われるべきか検討したい。
## Q1. has("python") の扱い

``` vim
has("python")
```

は python2 or python3 にすべきか
## Q2. has("python2")

``` vim
has("python")
```

が python3 を返す場合

``` vim
has("python2")
```

が取れる様にした方がいいか。`:python2` は？など。

**Comment by crazymaster** [comment]
ちなみにですけど、vim-xxxを入れると3系のみ有効、vim-xxx-py2を入れると2系のみ有効でした

**Comment by methane** [comment]
へー。 -py2 なんてのもできたんですね。
YouCompleteMeの中の人が頑張ってるけど、それ以外にもロングテール的に python2 only な
vim の plugin が、 Ubuntu パッケージに入ってしまってたから、仕方ないか。

**Comment by methane** [comment]
Python のライブラリでは Python 2/3 どちらでも動くコードを書くやり方が一般化してきていて、
vim の `:py` と `:py3` や `:pyfile` と `:py3file` を使い分けたりする vim スクリプトを書くほうが
Python 2/3 両対応の Python 書くよりずっと面倒なので、 Python 2/3 どちらでも動くプラグインを
開発しやすい仕組みがあると良いんですが。

その辺の仕組み、 vim_dev で以前に ZyX さんが中心になって提案されてたと思うのですが、
結局どうなったのか記憶が…

**Comment by koron** [comment]
@mattn 
**A1**: `has('python')` は今の仕様のまま、いじらないほうが良いかと。
**A2**: `has('python2')` はじめ、 `:py2`, `py2file` を追加するのは良い案だと思います。

理想案をいうと、 `:py` (無印)系は、インストールしてある Python のうちより新しいものを使い、
`:py2` 及び `:py3` では特定のバージョンの Python を使う、ってのが、
将来にわたっての保守はしやすいんではないかと考えてます。
とは言え、こうすると無印の動作を変えることになってしまうんですよね。

python2 の将来がどこまであるかは、別ですが :sweat_smile:

**Comment by k-takata** [comment]
> その辺の仕組み、 vim_dev で以前に ZyX さんが中心になって提案されてたと思うのですが、

どこかで、`:pyx`, `:pyxfile` というコマンドの提案を見たような気がするのですが…
これかな？
https://groups.google.com/d/topic/vim_dev/QUlI0fpMlFI/discussion

**Comment by k-takata** [comment]
上記の pythonx パッチを最新ソースに当たるように直してみた。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/dddc3db429664ac65e95edf32124182dde6da49b/pythonx.patch?fileviewer=file-view-default
コーディングスタイルとかドキュメントとかもいろいろ修正。

**Comment by k-takata** [comment]
あー、Bramのこの指摘を全く反映してなかった…
https://groups.google.com/d/msg/vim_dev/QUlI0fpMlFI/EaXvPLbiCpwJ

**Comment by k-takata** [comment]
オプション名を `'pythonxversion'` に変更。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/c861d978882ce218b9d8292797ffd0569a60094a/pythonx.patch?fileviewer=file-view-default

Bram 曰く、

> The default for 'pythonx' should be zero when build with both Python 2
> and 3.  Then the first Python command sets it.

このコメントから3年も経ったし、今時 3 がデフォルトでいいんじゃないかな。

**Comment by k-takata** [comment]
反応を見るために投げてみた。
https://groups.google.com/d/msg/vim_dev/QUlI0fpMlFI/Sh-ZNRpzAwAJ

**Comment by k-takata** [comment]
'pythonxversion' をセットするときに値をチェックするようにしたが、実はチェックしない方が良かったりするだろうか？ （`+python`, `-python3` な Vim で `:set pyx=3` とするとエラーになってしまう。）
あと、has('pythonx') の実装もこれで良いのか微妙。'pythonxversion' で指定されたバージョンの python が使えるかどうかだけをチェックしているが、別バージョンもチェックすべきだろうか？

**Comment by k-takata** [comment]
一応todo入り

> Patch for :pyx, run python commands depending on the supported version.
> (Marc Weber, update from Ken Takata, 2016 Sep 19)

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/QUlI0fpMlFI/TTr3KAh1AwAJ
OS Xは未だにpython 2がデフォルトなんですか!?

**Comment by methane** [comment]
会社で El Capitan 使ってるんですが、、、そうなんですよ。
しかも、 /usr/bin/python2 すら存在しなくて頭痛のタネ。

でも問題は、両方存在するときにどっちを優先するかであって、 python2 しか存在しない
システムでは pyx は Python 2 を使うんですよね？（多分）

**Comment by k-takata** [comment]
> でも問題は、両方存在するときにどっちを優先するかであって、 python2 しか存在しない
> システムでは pyx は Python 2 を使うんですよね？（多分）

今のパッチだと、python2/3両方有効でビルドされていて、ユーザーが `'pyx'` を設定していないと python3 を使おうとして失敗します。そのため、ユーザーが明示的に `:set pyx=2` としておく必要があります。
python2のみ有効でビルドされていれば、何も設定せずともpython2が使われます。

**Comment by k-takata** [comment]
パッチ更新。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d0e692a5253f7151fa198f091fc9a7f77292a4b0/pythonx.patch?at=default&fileviewer=file-view-default

* テスト追加。
* ドキュメント修正。
* userfunc.c / ex_function() で `:pyx` （と `:py3`）を認識するように修正。
* shebang のチェック方法を修正。

今のパッチでは、`:pyx` で使用可能な python のバージョンを自動検出したりはしませんが、使用者が .vimrc に以下のように書いておけば判定できるので、これで十分かな？

Python 3を優先する場合:

```vim
if !has('pythonx')
  silent! set pyx=2
endif
```

Python 2を優先する場合:

```vim
silent! set pyx=2
if !has('pythonx')
  silent! set pyx=3
endif
```

**Comment by h-east** [comment]
@k-takata パッと見て `Python \(2\|3\)を優先する場合:`の文言が逆？と思いました。

**Comment by k-takata** [comment]
todo listed

```
Patch for :pyx, run python commands depending on the supported version.
(Marc Weber, update from Ken Takata, 2016 Sep 19, 2017 Jan 6)
```

クローズしてOK?

**Comment by k-takata** [comment]
related: #1008

**Comment by k-takata** [comment]
8.0.0251
https://groups.google.com/d/msg/vim_dev/cXFM4F7RJSQ/8oskc_R0CwAJ
上に書いたのとは少し異なった仕様となりましたが、無事入りました。

* 'pythonxversion' は、'pyxversion' にリネーム。
* +python または +python3 のどちらか一方のみでコンパイルされているとき、'pyx' の設定には関係なく、コンパイルされたバージョンで、:pyx は動作する。
* +python, +python3 の両方でコンパイルされた場合は、'pyx' の初期値は 0。その場合、:py または :py3 を実行すると、2 または 3 に設定される。:pyx を実行すると、python 3 と 2 のどちらが使えるか確認し、使える方のバージョンをセット。
