### ISSUE TITLE
RFC: デフォルトのプラグインを &runtimepath に追加しない仕組みが欲しい

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/issues#859]
とても個人的な要望ですが、デフォルトのプラグイン（例: `netrw`）を `&runtimepath` に追加しないような仕組みが欲しいです。
たしかに `let g:loaded_netrw = 1` などで起動時間はほぼ無視できますが、全く使わないため無駄な感じがします。

個人的には
1. コンパイルオプションで無効化（例: `configure --no-default-plugins`）
2. デフォルトプラグインを `runtime/opt/` に移動 (https://twitter.com/ShougoMatsu/status/704101989018304512)

あたりが良いかと考えています。

賛成・反対・別意見等ありましたらおねがいします。ある程度まとまったら本家に報告したいと思っています（報告方法すら知りませんが）。

**Comment by koron** [comment]
インストール後に消す自前のスクリプトでも走らせれば良いんじゃないですか?
configure から make install して不要なファイルを消す、自前のビルドスクリプトを用意して
それを使って毎回インストールすれば済む話でしょう。

Vimが今以上にサポートする意義は薄いと考えます。

**Comment by lambdalisue** [comment]
> インストール後に消す自前のスクリプトでも走らせれば良いんじゃないですか?
> configure から make install して不要なファイルを消す、自前のビルドスクリプトを用意して
> それを使って毎回インストールすれば済む話でしょう。

なぜそれを思いつかなかった自分（笑。そのとおりですね閉じます。

**Comment by tyru** [comment]
それか自作runtime directoryを作って `$VIMRUNTIME` で指定するとかでしょうか。
http://tyru.hatenablog.com/entry/2016/02/23/031425

**Comment by koron** [comment]
自前のラッパースクリプトでできる話であり、Vimでやるまでもないことから wontfix としました。
