### ISSUE TITLE
コンパイルすると src/vim.lib が作成される

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#861]
## 質問・報告の内容

MSVC10を用いて、Active Perl 5.22.1 を使って +if_perl でコンパイルすると
src/vim.lib が生成され clean の対象にも .gitignore の対象でもない
ゴミファイルとして扱われます。

clean するようにし、 .gitignore にも加えたほうが良いでしょう。
## Vimのバージョン

7.4.1485
## OSの種類
-   Windows
## その他

vim.lib でエクスポートされているシンボルは `boot_VIM` でした。

Active Perl 5.20.1 の時は発生していませんでした。
5.22.1 とで if_perl.c の中身を比較して、理由を抑えておくほうが良いかもしれません。

**Comment by koron** [comment]
直接は関係ないけど、
いま src/testdir で `nmake -f Make_dos.mak win32 clean` したら
channellog が残ってた (；´Д｀)

**Comment by koron** [comment]
> channellog が残ってた (；´Д｀)

1485 で入ったみたい。

[ココ](https://github.com/vim/vim/commit/014069a7ac51557e531eb3c8b94e36f2193f6c21#diff-0df32bc2f6721af01944a6045df14b1fR486)をみるとインデントもおかしいし、デバッグ用に追加して消し忘れかな。

**Comment by koron** [comment]
以下2点は間違いでした。申し訳ない。

> - clean の対象で～ない
> - Active Perl 5.20.1 の時は発生していませんでした。

よって .gitignore に足せば十分でしょう。

**Comment by k-takata** [comment]
> 以下2点は間違いでした。申し訳ない。

おや、Perlのバージョンアップによるものだと思っていましたが。
少なくとも ActivePerl 5.16では発生しておらず、5.22では発生しているという認識。

**Comment by koron** [comment]
あ、ごめん。やっぱどっちも当初の報告通りで良いのかも。

clean についてはラップしているビルドスクリプトで消してた。
5.20 については、xsを実行するperlが5.22のままだった。

**Comment by koron** [comment]
再度確認しました。当初の報告どおりで間違いないです。
5.20.1 でビルドすると vim.lib はできません。

**Comment by koron** [comment]
lib/CORE/XSUB.h のこの差分が原因っぽい。

``` diff
--- Perl-5.20.1-64/lib/CORE/XSUB.h  2014-04-16 03:56:36.000000000 +0900
+++ Perl-5.22.1-64/lib/CORE/XSUB.h  2015-06-01 16:45:32.000000000 +0900
@@ -128,7 +128,7 @@
 #undef XS
 #undef XS_EXTERNAL
 #undef XS_INTERNAL
-#if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
+#if (defined(__CYGWIN__) || defined(WIN32)) && defined(USE_DYNAMIC_LOADING)
 #  define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
 #  define XS_INTERNAL(name) STATIC XSPROTO(name)
 #endif
```

**Comment by koron** [comment]
この差分、perl5の本体(ミラー)を見る限り、[5.23.8 にも存在しない](https://github.com/Perl/perl5/blob/v5.23.8/XSUB.h#L132)。
つまり Active Perl 特有の変更っぽい (；´Д｀)

**Comment by koron** [comment]
http://downloads.activestate.com/ActivePerl/releases/ からActivePerlのソースをDLして確認したところ
2002 (5.20.2) では WIN32 を含まなかったものの、ソレ以外の 2003, 2200, 2201 の全てで WIN32 のチェックが追加されていた。

よって src/vim.lib が作成されるのは Windows で最新の ActivePerl を用いて +if_perl を作成した場合に限られる。

**Comment by k-takata** [comment]
こういうのはどうだろう。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/f07c30fadaeecde71181c058f6edaccbb81af57f/stop-generating-vim-lib.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
1年半ぶりに放出 vim/vim#3462

**Comment by k-takata** [comment]
8.1.0420: https://github.com/vim/vim/commit/1f402806b88f4187e17c0105b4604f425f41dd1c

**Comment by k-takata** [comment]
今後 Strawberry Perl に移行していくなら要らないんですけどねｗ
