### ISSUE TITLE
g:loaded_LogiPatの大文字小文字の差異

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#862]
## 質問・報告の内容

`loaded_logipat`のletとexists()とで大文字小文字が間違っています。

```
if &cp || exists("loaded_logipat")
 finish
endif
let g:loaded_LogiPat = "v3"
```

https://github.com/vim/vim/blob/master/runtime/plugin/logiPat.vim#L42
## Vimのバージョン

$VIMRUNTIME/plugin/logiPat.vim加わった7.4.748あたりから。
## OSの種類
-   Windows
-   MacOSX
-   Linux
-   Others
## OSのディストリ

特になし。
## OSのバージョン

特になし。
## その他

特になし。

**Comment by h-east** [comment]
ひと月ほど前にmattnさんがpatch送ったけど、結局伝わらずじまいですね。
https://groups.google.com/forum/#!searchin/vim_dev/loaded_logipat/vim_dev/v00y1305Eng/TOko-Zj2CgAJ

**Comment by rbtnn** [comment]
あーそうなんですか。

**Comment by h-east** [comment]
あっ、違いました。
Chipさんのサイトのやつは直っていますね。Vimに同梱の奴のVersionを上げてもらわないとダメですね。
http://www.drchip.org/astronaut/vim/index.html#LOGIPAT

**Comment by h-east** [comment]
Bram氏に依頼出しました。
https://groups.google.com/d/msg/vim_dev/v00y1305Eng/wz8n4-VEFQAJ

**Comment by rbtnn** [comment]
ありがとうございます。

**Comment by h-east** [comment]
再Push. (なんだかなー)
https://groups.google.com/d/msg/vim_dev/v00y1305Eng/zgKlzRp1HgAJ

**Comment by k-takata** [comment]
> Who is not accomplish this task?
> Bram or Charles?

普通に考えて Charles だと思いますよ。
Bram にファイルを送ったら、たいてい次の runtime file の更新のタイミングで取り込んでくれますし。

**Comment by h-east** [comment]
はい、そうだと思っていますけど大人な聞き方をしました:grin:
syntax/vim.vimも最終リリース 2/25 ですし。おすし。
もう、Mr.ボトルネック と読んでも良いかもしれない。

**Comment by mattn** [comment]
Mr ボトルネック、ネーミングかっこいい。
「俺が、この流れを止めてみせるぜ」

**Comment by h-east** [comment]
止めないで下さいｗ みんなで疾走しましょう！

**Comment by h-east** [comment]
ついでに言うとくけど、syntax/vim.vimの最終リリース 2/25はdegradeが発生している。
'nobri' とかなくなってる。もうあの人にsyntax/vim.vimは任せられへん って感じです。

**Comment by k-takata** [comment]
ようやく直りました。
https://github.com/vim/vim/commit/939a1abe935a539f2d4c90a56cb0682cbaf3bbb0#diff-cf50c2e3c908fb06a84c8193e2398371L39

**Comment by mattn** [comment]
やった
