### ISSUE TITLE
Netrwのファイラウィンドウがアクティブにならない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#863]
## 質問・報告の内容

from https://gist.github.com/0xrofi/1a5cd7427292f056aab5

以下の条件でファイラのウィンドウがアクティブにならない
1. :Explorer でNetrwを起動する
2. ファイルにカーソルを合わせvで縦分割で開く（このときカーソルは自動的に開いたファイルのバッファに移る）
3. C-W C-Wで元のファイラウィンドウにカーソルを移動させようとしても移動しない
## Vimのバージョン

7.4.1161
## 使用している or 関係していそうなプラグイン

netrw.vim
## その他

転載者注： 元記事では+kaoriyaを指定しているが、netrwは変更していないので本体に問題があると推定される。また最新版ではまた事情が異なっている可能性がある。

**Comment by 0xrofi** [comment]
本体の方は確認していませんが、現時点での香り屋Vim最新版（Vim 7.4.1490 (2016/03/05版)）ではnetrwのバージョンが154から155に上がっておりこの現象は発生しませんでした
なので修正されているようです

**Comment by h-east** [comment]
patch 7.4.1368の直前のcommitでv154からv155に上がっていますね。https://github.com/vim/vim/commit/e0fa3742ead676a3074a10edadbc955e1a89153d

**Comment by h-east** [comment]
こちらでもv155で正常動作確認出来ましたので本Issueクローズします。
@0xrofi 検証&報告ありがとうございました。

**Comment by koron** [comment]
:+1:

**Comment by k-takata** [comment]
どこかでこの話題を見ていた気がしたのですが、本家で挙がっていました。
https://groups.google.com/d/topic/vim_dev/xrkwm035gKE/discussion
（で、作者の回答がGitHubにリダイレクトされていないという…）
