### ISSUE TITLE
MSVCRT_NAME の値が VC14 のそれとは一見異なる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#864]
## 質問・報告の内容

VisualStudio 2015/VC14 でのビルド時に
src/Make_mvc.mak 内の `MSVCRT_NAME` の値が正しくならない。

期待する値: `vcruntime140` もしくは `vcruntime140.dll`
実際の値: `msvcr140`
## Vimのバージョン

7.4.1490
## OSの種類
-   Windows
## その他

直さなくても動くかもだけど、誤解を招く。
また他にも`DYNAMIC_MSVCRT_DLL` とか、
幾つか不整合があるかもしれない。

**Comment by koron** [comment]
もしかして…
`MSVCRT_NAME` は Ruby のランタイム決定のためにしか使われてないから、
そっちを明示的に指定している場合は、意味ないのかな?

`DYNAMIC_MSVCRT_DLL` は、iconvとのやりとりのために
どのみちコンパイル時に明示してやらないとならなさそう。

**Comment by k-takata** [comment]
`MSVCRT_NAME`は、RubyのDLLの名前を決めるための変数ですが、RubyはまだVC14でのビルドに対応していません。RubyがVC14に対応して、DLLの名前が決まった時点で適切に修正する必要があります。

**Comment by koron** [comment]
@k-takata だとすれば、そもそも

``` make
# Base name of the msvcrXX.dll
!if $(MSVCRT_VER) <= 60
MSVCRT_NAME = msvcrt
!else
MSVCRT_NAME = msvcr$(MSVCRT_VER)
!endif
```

この部分をRubyの以下の場所に移したほうが良いのかもしれませんね。

``` make
!ifndef RUBY_MSVCRT_NAME
# Base name of msvcrXX.dll which is used by ruby's dll.
RUBY_MSVCRT_NAME = $(MSVCRT_NAME)
!endif # RUBY_MSVCRT_NAME
```

**Comment by koron** [comment]
直接 `RUBY_MSVCRT_NAME` を定義する形にして、 `MSVCRT_NAME` 自体は、無いほうが良いのかも。

**Comment by k-takata** [comment]
`DYNAMIC_MSVCRT_DLL` は #277 によって必須ではなくなっています。（うまくいかないDLLもありますが。）

> 直接 RUBY_MSVCRT_NAME を定義する形にして、 MSVCRT_NAME 自体は、無いほうが良いのかも。

そうとも言えるかもしれないです。

**Comment by k-takata** [comment]
Ruby 2.4.0をVC2015でビルドしたところ、DLL名が`vcruntime140-ruby240.dll`となることが確認できたので、これでよさそう。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d0768c51e95d2a867ce34c69dda35a1431d20b6f/fix-msvcrt-name-with-vc2015.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
Posted.
https://groups.google.com/d/topic/vim_dev/jL30INyxwGk/discussion

**Comment by k-takata** [comment]
8.0.0279
https://groups.google.com/d/topic/vim_dev/AapzKUlww9g/discussion
