### ISSUE TITLE
本家helpのtypo報告スレ

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#865]
本家help(`runtime/doc/*.txt`)のtypoを報告するスレです。
その都度vim_devに報告するとウザいのである程度溜まってから報告します。

typo発見時のVimバージョン(`7.4.xxxx`)も添えていただけると助かります。

**Comment by h-east** [comment]
:h 'nobri' のジャンプ先がwrapされている。(インデントが1つ多い)

```
                                'breakindent' 'bri' 'nobreakindent' 'nobr
i'
```

**Comment by todashuta** [comment]
typoと言っていいか微妙なんですが、

:h 'backupskip' 中の設定例について、

> ```
>    :let backupskip = escape(expand('$HOME'), '\') . '/tmp/*'
> ```

上記のように、グローバル変数か関数ローカル変数に代入してるような例になってますが、下記のようにオプションの変数に代入する例にしたほうが自然かと思います。いかがでしょうか。

```
   :let &backupskip = escape(expand('$HOME'), '\') . '/tmp/*'
```

**Comment by h-east** [comment]
@todashuta Yes, 指摘正しいです。Thanks!:+1:

**Comment by crazymaster** [comment]
リダイレクトされるけど一応

``` diff
diff --git a/runtime/doc/todo.txt b/runtime/doc/todo.txt
index c6c38e1..d84d865 100644
--- a/runtime/doc/todo.txt
+++ b/runtime/doc/todo.txt
@@ -27,7 +27,7 @@ Priority classification:
 See |develop.txt| for development plans.  You can vote for which items should
 be worked on, but only if you sponsor Vim development.  See |sponsor|.

-Issues can also be entered online: http://code.google.com/p/vim/issues/list
+Issues can also be entered online: https://github.com/vim/vim/issues
 Updates will be forwarded to the vim_dev maillist.  Issues entered there will
 not be repeated below, unless there is extra information.

```

**Comment by crazymaster** [comment]
ついでに #831 の報告もしてもらえますか？

**Comment by machakann** [comment]
@crazymaster ありがとうございます。

typo ではないのですが、現在の最新 (patch-7.4.1529) の `index.txt` では以下の新しめのキーマッピングが漏れています。
- i_CTRL-G_U
- v_g_CTRL-A, v_g_CTRL-X

**Comment by k-takata** [comment]
7.4.1559

``` diff
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -1898,7 +1898,7 @@ foldlevel( {lnum})        Number  fold level at
 foldtext()         String  line displayed for closed fold
 foldtextresult( {lnum})        String  text for closed fold at {lnum}
 foreground()           Number  bring the Vim window to the foreground
-function({name} [, {arglist}] [, {dict}])
+function( {name} [, {arglist}] [, {dict}])
                Funcref reference to function {name}
 garbagecollect( [{atexit}])    none    free memory, breaking cyclic references
 get( {list}, {idx} [, {def}])  any get item {idx} from {list} or {def}
```

`(` と `{` の間にスペースがないとタグジャンプできません。

**Comment by h-east** [comment]
@k-takata :+1:
これも`find_help_tags()`のロジックを見なおせばスペース開けなくてもよくなりそうですね。
- タグの途中に`(`が出現してその次の文字が`{`か`[`だったらタグ文字列を`(`までとする。

今現在、runtime/doc/tagsには`({`や`([`を含むタグはありません。

**Comment by h-east** [comment]
これで:+1:

``` patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 8a763c9..f610b6b 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -6206,6 +6206,12 @@ find_help_tags(
        *d++ = *s;

        /*
+        * If tag contains ({ or ([, Tag is set to terminate the (
+        */
+       if (*s == '(' && (s[1] == '{' || s[1] =='['))
+       break;
+
+       /*
         * If tag starts with ', toss everything after a second '. Fixes
         * CTRL-] on 'option'. (would include the trailing '.').
         */
```

**Comment by h-east** [comment]
これも要修正。
https://github.com/vim-jp/issues/issues/873#issuecomment-199083619

**Comment by k-takata** [comment]
`:help wildcard` の最後の部分、

```
as a wildcard when "[" is in the 'isfname' option.  A simple way to avoid this
is to use "path\[[]abc]".  Then the file "path[abc]" literally.
```

`"path[abc]"` は `"path\[abc]"` ではないだろうか。

**Comment by k-takata** [comment]
> 今現在、runtime/doc/tagsには({や([を含むタグはありません。

もしプラグインのヘルプで`({`や`([`を含むタグがあったら、引けなくなるのではと今さらながら気になりました。

**Comment by h-east** [comment]
うぅ、すでに取り込まれている分だと `('`で始まるタグには飛べない(苦笑)
Surround系のモーションコマンドでありそう。。

**Comment by miyakogi** [comment]
細かいですが、jobのオプションの修正漏れがありました (Vim 7.4.1655)

``` diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 642f0ad..5ea30a8 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -4631,7 +4631,7 @@ job_status({job})                 *job_status()* *E916*
            "fail"  job failed to start
            "dead"  job died or was stopped after running

-       If an exit callback was set with the "exit-cb" option and the
+       If an exit callback was set with the "exit_cb" option and the
        job is now detected to be "dead" the callback will be invoked.

        For more information see |job_info()|.
```

**Comment by h-east** [comment]
> > 今現在、runtime/doc/tagsには({や([を含むタグはありません。
> 
> もしプラグインのヘルプで({や([を含むタグがあったら、引けなくなるのではと今さらながら気になりました。

@k-takata vim_devにコメントしました。不足等ありましたらフォローお願いします。
https://groups.google.com/d/msg/vim_dev/fH5gsRE-EjE/6b4vIWC0GwAJ

**Comment by tyru** [comment]
repeat.txt の packages 機能を翻訳していて見つけたのでコメントします。
以下は全て repeat.txt に対する指摘です。
- `Error`が先頭でないにも関わらず大文字になってます。

``` diff
-           An Error only causes sourcing the script where it
+           An error only causes sourcing the script where it
```
- ` を使っている個所がいくつかありますが、タグが用意されている場合は `|` 使ったほうがいいのではないでしょうか。
- 以下は `s/or not loaded/is not loaded/` の間違いではないでしょうか。

```
Note that the files under "pack/foo/opt" or not loaded automatically, only the
ones under "pack/foo/start".  See |pack-add| below for how the "opt" directory
is used.
```
- 以下の文の意図が汲み取れませんでした (always.vim とは…)。

```
This could be done inside always.vim, if some conditions are met.  Or you
could add this command to your |.vimrc|.
```

**Comment by tyru** [comment]
上記は新機能の help ということもあり、今すぐ指摘したほうがいいでしょうか？

**Comment by k-takata** [comment]
すでに指摘が入っています。（全部かどうかは未確認）
https://groups.google.com/d/msg/vim_dev/VXSJLb_boRQ/WgsNYu-NGwAJ

**Comment by tyru** [comment]
ありがとうございます。ちょうどスレッドが立てられてるようなので報告しました。

**Comment by k-takata** [comment]
> ` を使っている個所がいくつかありますが、タグが用意されている場合は | 使ったほうがいいのではないでしょうか。

7.3の途中でexコマンドには ` が使われはじめましたが、どういう場合に ` を使っているのか、helpには明記されていないですね。

**Comment by tyru** [comment]
そうですね… 最近使われ始めた印象があります。 >`

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/7db8f6f4f85e5d0526d23107b2a5e2334dc23354

> `"path[abc]"` は `"path\[abc]"` ではないだろうか。

vim/vim#700 で指摘しておいたところ、直りました。

> Errorが先頭でないにも関わらず大文字になってます。

これも直りました。

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/4f3f668c8486444e53163c29d2fc79bf47eb3c82

> 以下は s/or not loaded/is not loaded/ の間違いではないでしょうか。

are に直っています。

> 以下の文の意図が汲み取れませんでした (always.vim とは…)。

直っています。

**Comment by tyru** [comment]
ありがとうございます。

**Comment by itchyny** [comment]
`:h cursor()` の以下の項目ですが、

```
        When there is one argument {list} this is used as a |List|
        with two, three or four item:
            [{lnum}, {col}, {off}]
            [{lnum}, {col}, {off}, {curswant}]
        This is like the return value of |getpos()| or |getcurpos()|,
        but without the first item.
```

こういう感じに二つの時の行があると分かりやすかったです。

``` diff
        with two, three or four item:
+           [{lnum}, {col}]
            [{lnum}, {col}, {off}]
```

最初、上の文章をちゃんと見てなくてlnumとcolだけ渡しても動くけど渡していいのか不安になりました。
typoかどうか微妙ですけどネ。

**Comment by k-takata** [comment]
> - v_g_CTRL-A, v_g_CTRL-X

v_CTRL-A, v_CTRL-X もないですね。

**Comment by h-east** [comment]
@k-takata はい。実はそろそろpatch書いて送ろうと昨日の昼に作業したんですけど、その辺のチェックが面倒になってやめちゃった:grin:

**Comment by h-east** [comment]
machakannさんの(`index.txt`のキー追加漏れ)以外の未報告分でpatch作って投げました。
https://groups.google.com/d/msg/vim_dev/J_eNFOGkujI/7diA8AknHgAJ

Anyone>
`index.txt`のキー追加漏れ どなたか纏めて頂けると助かります。

**Comment by k-takata** [comment]
7.4.1710

``` diff
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -5052,7 +5052,7 @@ A jump table for the options with a shor
    without a limit.
    On 64 bit machines higher values might work.  But hey, do you really
    need more than 2 Gbyte for text editing?  Keep in mind that text is
-   stored in the swap file, one can edit files > 2 Gbyte anyay.  We do
+   stored in the swap file, one can edit files > 2 Gbyte anyway.  We do
    need the memory to store undo info.
    Also see 'maxmem'.

```

**Comment by k-takata** [comment]
index.txt と、その他いくつかの修正をまとめて投げました。
https://groups.google.com/d/msg/vim_dev/QlcBo8pTrf0/IK7YsE9jBQAJ

**Comment by k-takata** [comment]
> 7.3の途中でexコマンドには ` が使われはじめましたが、どういう場合に ` を使っているのか、helpには明記されていないですね。

`:help help-writing` (helphelp.txt) に記載が追加されました。

**Comment by k-takata** [comment]
7.4.1728
https://groups.google.com/d/topic/vim_dev/n44Atord7uk/discussion
( と { の間のスペースは削除されました。

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/aa3b15dbebf333282503d6031e2f9ba6ee4398ed いろいろ直りました。

**Comment by h-east** [comment]
:+1:
https://github.com/vim/vim/commit/aa3b15dbebf333282503d6031e2f9ba6ee4398ed#diff-38d7929bd26d74d92ceddf984bbfc8dbL156

**Comment by h-east** [comment]
`:h function-list`がメンテされていないです。
例えば、`job_～`、`js_～`、`json_～`がない。
名称変更前の`jsonencode()`, `jsondecode()`がある等々。

**Comment by h-east** [comment]
> `:h function-list`がメンテされていないです。

不足分纏めました(from Vim 7.4.1847)。どなたかこれを元にpatch作成しませんか？

抜けているもの:
ch_evalexpr()
ch_evalraw()
ch_getbufnr()
ch_getjob()
ch_info()
ch_log()
ch_logfile()
ch_read()
ch_readraw()
ch_setoptions()
ch_status()
getcharsearch()
glob2regpat()
isnan()
job_getchannel()
job_info()
job_setoptions()
job_start()
job_status()
job_stop()
js_decode()
js_encode()
setcharsearch()
setfperm()
strcharpart()
test_alloc_fail()
test_disable_char_avail()
test_garbagecollect_now()
test_null_channel()
test_null_dict()
test_null_job()
test_null_list()
test_null_partial()
test_null_string()
timer_start()
timer_stop()
win_findbuf()
win_getid()
win_gotoid()
win_id2tabwin()
win_id2win()

要リネーム:
jsondecode() --> json_decode()
jsonencode() --> json_encode()

**Comment by k-takata** [comment]
xxx_for_testing 関数はリネームの可能性があるので注意した方がいいです。

**Comment by h-east** [comment]
@k-takata 7.4.1838で`garbagecollect_for_testing()`が`test_garbagecollect_now()`にリネームされましたね。
(上の纏めコメントを7.4.1842ベースで更新しました)

あと、「`disable_char_avail_for_testing()`と`alloc_fail()`はリネームしないの？」と突っ込み済みです。
https://groups.google.com/d/msg/vim_dev/B1kF0wQM2Iw/ENxBdM-2HwAJ

**Comment by h-east** [comment]
> あと、「disable_char_avail_for_testing()とalloc_fail()はリネームしないの？」と突っ込み済みです。

Renamed on patch 7.4.1844.
https://github.com/vim/vim/commit/8e8df251bf2505e5decf258397c6069fbe5e2e01

(上の一覧も更新済み)

**Comment by k-takata** [comment]
`:help 'writedelay'`

```
    The number of microseconds to wait for each character sent to the
```

microseconds ではなくて milliseconds のような気がします。
（ちなみに日本語訳は「1万分の1秒単位」になってて全然合ってません。）

**Comment by h-east** [comment]
> :h function-listがメンテされていないです。

https://github.com/vim-jp/issues/issues/865#issuecomment-220831320

今朝修正されました。(抜けチェックはしていません)
https://github.com/vim/vim/commit/c95a302a4c42ec8230473cd4a5e0064d0a143aa8#diff-46f53421a06e0a19bb5416273231c104L1

**Comment by thinca** [comment]
`:help Number` の Examples:

> Examples:  -123  0x10  0177

`:help expr-number` の説明

> Decimal, Hexadecimal (starting with 0x or 0X), or Octal (starting with 0).

それぞれに、2進数リテラル `0b1101` の例や説明がありません。

**Comment by rbtnn** [comment]
https://github.com/vim/vim/blob/master/runtime/doc/eval.txt#L3111

> "waittime"    only applies to "ch_open()|

`"`と`|`の整合性が取れていません。

**Comment by k-takata** [comment]
> "と|の整合性が取れていません。

reported.
https://groups.google.com/d/msg/vim_dev/USr_pUG8eV8/8LyyUn5BBAAJ

**Comment by k-takata** [comment]
> それぞれに、2進数リテラル 0b1101 の例や説明がありません。

done.
https://groups.google.com/d/msg/vim_dev/USr_pUG8eV8/sh22kaNCBAAJ

**Comment by koron** [comment]
とりあえず 8.0 リリースに向けてラストスパートで、リリースされたら issue 仕切りなおすと良さそう。

**Comment by crazymaster** [comment]
``` diff
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
index 30ea88d..17b5faf 100644
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -2633,7 +2633,7 @@ A jump table for the options with a short description can be found at |Q_op|.
        uhex            Show unprintable characters hexadecimal as <xx>
                        instead of using ^C and ~C.

-       When neither "lastline" or "truncate" is included, a last line that
+       When neither "lastline" nor "truncate" is included, a last line that
        doesn't fit is replaced with "@" lines.

                                                *'eadirection'* *'ead'*
```

reported. https://groups.google.com/d/msg/vim_dev/OEX8_SOhyYQ/wStaodiJAQAJ
fixed by https://github.com/vim/vim/commit/d07969093a9b3051511c478d71c36de6fc33c0d6#diff-9314fb84f930a1648810c882e8247e6f

**Comment by machakann** [comment]
```diff
diff --git a/runtime/doc/term.txt b/runtime/doc/term.txt
index 0bfe4eb0b..2b4c3e92d 100644
--- a/runtime/doc/term.txt
+++ b/runtime/doc/term.txt
@@ -424,8 +424,8 @@ Note: Use the <> form if possible
 	t_KK	<k8>		keypad 8		 *<k8>*	*t_KK* *'t_KK'*
 	t_KL	<k9>		keypad 9		 *<k9>*	*t_KL* *'t_KL'*
 		<Mouse>		leader of mouse code		*<Mouse>*
-	t_PS	start of bracketed paste |xterm-bracketed-paste|  *t_PS* 't_PS'
-	t_PE	end of bracketed paste |xterm-bracketed-paste|    *t_PE* 't_PE'
+	t_PS	start of bracketed paste |xterm-bracketed-paste|  *t_PS* *'t_PS'*
+	t_PE	end of bracketed paste |xterm-bracketed-paste|    *t_PE* *'t_PE'*
```

アスタリスクでの囲み忘れ？ 文章中の `'t_PS'` および `'t_PE'` からジャンプできなくなっています。

`conceal` 機能なしだと78桁目を超えてしまうので調整した方がいいかもしれないです。

**Comment by crazymaster** [comment]
```diff
diff --git a/runtime/doc/usr_02.txt b/runtime/doc/usr_02.txt
index 48dede8..f9f47cf 100644
--- a/runtime/doc/usr_02.txt
+++ b/runtime/doc/usr_02.txt
@@ -663,7 +663,7 @@ Summary:                                    *help-summary*  >
 22) Autocommand events can be found by their name: >
        :help BufWinLeave
 <    To see all possible events: >
-       :help autocommands-events
+       :help autocommand-events
 
 23) Command-line switches always start with "-".  So for the help of the -f
     command switch of Vim use: >
```
タグと異なるのでジャンプできない。

**Comment by k-takata** [comment]
上記2件投げました。
https://groups.google.com/d/msg/vim_use/P7vqtt73gvY/UsZJ069NAQAJ
(vim_dev に投げるつもりが、間違って vim_use に…)

**Comment by k-takata** [comment]
> とりあえず 8.0 リリースに向けてラストスパートで、リリースされたら issue 仕切りなおすと良さそう。

Vim 8.0 用の issue を新しく立てました。 #1032
以後はそちらで。
