### ISSUE TITLE
feedkeys('', 'x') が動かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#866]
## 質問・報告の内容

`:help feedkeys()` によると、

```
                'x'     Execute commands until typeahead is empty.  This is
                        similar to using ":normal!".  You can call feedkeys()
                        several times without 'x' and then one time with 'x'
                        (possibly with an empty {string}) to execute all the
                        typeahead.
```

`x` モードを空文字列で呼んでも良い、とありますが、実際に空文字列で呼び出しても何も起きません。
修正するパッチとテストを書いたので、どなたか添削をお願いします。

https://gist.github.com/thinca/4d24fa3d5fa70d67ec56
## Vimのバージョン

7.4.1522

**Comment by h-east** [comment]
CソースはLGTM:+1:
testの内容も特に問題ないと思います。

`src/Makefile` の2000行目くらい(`/^test_arglist`で検索)に`test_feedkeys`の追加をお願いします。

ここからは個人的な意見です。
今回のような小規模なtestは`src/testdir/test_alot.vim`に属させた方が良いと思いました。
(`src/testdir/Make_all.mak`を弄らずに上記ファイルを弄る)

※どちらにしても`src/Makefile`への追加は必要です。

**Comment by h-east** [comment]
> src/Makefile の2000行目くらい(/^test_arglistで検索)にtest_feedkeysの追加をお願いします。

これをすると、`src`ディレクトリで `$ make test_feedkeys`が実行出来て結果も表示してくれるので楽です。

**Comment by thinca** [comment]
アドバイスありがとうございます！gist 更新しました。
`src/Makefile` に追加と、`src/testdir/Make_all.mak` の代わりに `src/testdir/test_alot.vim` へ追記です。

**Comment by h-east** [comment]
It maybe perfect:+1:

**Comment by thinca** [comment]
投げました。

https://groups.google.com/d/topic/vim_dev/nBUdXg9BuJ4/discussion

**Comment by thinca** [comment]
元の Gist は日本語でコメントを入れてしまっていて余計な混乱をさせてるかもしれなかったので、報告に使った Gist は作りなおしました。

**Comment by h-east** [comment]
patch 7.4.1533 :tada: 
https://github.com/vim/vim/commit/74c5bbf13435a7ab1e3461078bbcb1200f0451e1

私の指摘したとこ入らなかった:grin:
おかしいなぁ、test_alot.vimの中の項目も`join`以外はMakefileに書かれているのになぁ。

(このpatchに関係なく)、Bram氏も言っていますが、'x'使うと1秒刺さる事が多いです。調査した方がいいですね:mag:

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/5250612f53f705a3.png)

豆腐？

**Comment by h-east** [comment]
1秒delayが入る件、patch 7.4.1535 で直りました。
https://github.com/vim/vim/commit/9e496854a9fe56699687a4f86003fad115b3b375

src/Makefieの件は、Bram氏に質問したら以下の返事があったのでそのうち入るでしょう。
「src/Makefieは局所的な変更が多いからpatchに含めるのはしばらくの間待ってからにしてます」(意訳)
https://groups.google.com/d/msg/vim_dev/-LuFHnB4RPI/DJiW-84lFwAJ

**Comment by h-east** [comment]
> 私の指摘したとこ入らなかった:grin:
> おかしいなぁ、test_alot.vimの中の項目もjoin以外はMakefileに書かれているのになぁ。

patch 7.4.1555 で入った。
https://github.com/vim/vim/commit/fff341eb5960f656529b56c949043f041eddbb1e

これで`src/`で`make test_feedkeys等個別にテスト出来る。
