### ISSUE TITLE
:messages を消す方法がない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#867]
```
for _ in range(200) | echom '' | endfor
```

で無理やり消すという方法が無くはないですが、出来れば綺麗にやりたいので

```
:messages!
```

で消せる様にしてみました。
https://gist.github.com/mattn/1b84ca57ad4165390fb5
- [x] code
- [x] doc
- [x] test

**Comment by tyru** [comment]
:+1:

**Comment by tyru** [comment]
あ、すみません。
これ某所である人が言っていた、`messages 2` で直近の2行だけ取ってきたい、とかの拡張を考えると、bangより `:mes clear` とかのが良い気がします。

**Comment by rhysd** [comment]
:+1:

**Comment by rhysd** [comment]
とりあえず help つくってみましたがどうでしょうか

``` diff
diff --git a/runtime/doc/message.txt b/runtime/doc/message.txt
index 56745f3..651f43b 100644
--- a/runtime/doc/message.txt
+++ b/runtime/doc/message.txt
@@ -52,6 +52,10 @@ If you are lazy, it also works without the shift key: >

    :help e72

+If you want to clear old messages, you can use ":messages!": >
+
+   :messages!
+<
 ==============================================================================
 2. Error messages              *error-messages* *errors*

```

**Comment by mattn** [comment]
あざます。redir だと Messages maintener の文字列も入って若干めんどくさいテストになってしまった。

https://gist.github.com/mattn/d49e97c52c385a24732a

**Comment by h-east** [comment]
履歴用の組み込み関数histadd(),  histdel(),  histget(),  histnr()があるので、
メッセージ用の組み込み関数を追加しましょう！:cat2::dash:
mess_add(),  mess_del(),  mess_get(),  mess_nr()

**Comment by mattn** [comment]
> mess_add(), mess_del(), mess_get(), mess_nr()

個人的にはですが、そこまでニーズ無いんですよねー。hist と比べると。Vim plugin 作っててデバッグする時にメッセージが出すぎるので消したい、というのが第一要件で今回 messages に clear を補完させようかと考えましたがこのニーズの無さ、拡張性の無さから考えてやめました。

**Comment by tyru** [comment]
メッセージはむしろredirをネスト可能にしてもらいたいです。
# それができればVimEnterでredirしておいて全てログに吐くとかも可能なので

**Comment by mattn** [comment]
redir のネストはおそらく無理ですね。
https://github.com/vim-jp/issues/issues/65

**Comment by tyru** [comment]
あー capture() 等の関数を新設する、って流れになったのか…了解です。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/UM_o8fBEMjc

**Comment by mattn** [comment]
まずは興味があるかどうかって事で送付

**Comment by tyru** [comment]
:+1: 

# 関係ないけど issue のタイトルから[これ](https://www.google.co.jp/search?q=%E3%81%8A%E5%89%8D%E3%82%92%E6%B6%88%E3%81%99%E6%96%B9%E6%B3%95&safe=off&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjPssyYtLfLAhWI3KYKHdoqDb8Q_AUIBygB&biw=1680&bih=930)思い出しました

**Comment by k-takata** [comment]
7.4.1735
https://groups.google.com/d/msg/vim_dev/kxVcZCxwOn4/dnBWAdAGBgAJ
7.4.1738
https://groups.google.com/d/msg/vim_dev/zEy36aV9LTY/wkwxt4gLBgAJ
