### ISSUE TITLE
リアクションテスト

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#868]
## 質問・報告の内容

https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

github issue にリアクションが実装されましたので、
この issue で思う存分リアクションしてください。
## その他

気が済んだら閉じてください。

**Comment by tyru** [comment]
連打はできないのか… (はてスタ感覚)

**Comment by koron** [comment]
別の種類のリアクションの追加はできるっぽいw

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/5250612f53f705a3.png)

豆腐？

**Comment by koron** [comment]
ふむ。他人のリアクションはリロードしないと反映されないっぽい。

**Comment by koron** [comment]
あとnotificationにもでないのかな。

**Comment by mattn** [comment]
コメント欄が :+1: で埋まる問題の対策でしょうからねー。初期設定は無いんじゃないすかね。

**Comment by koron** [comment]
10, 100,1000,... に到達した時にはnotificationが飛んでくれるだと、
vote代わりに使えて良さそうなんですけどねw

**Comment by raa0121** [comment]
リアクションの数が少ない…

**Comment by thinca** [comment]
Slack みたいに任意の絵文字が使えるわけではないのか。

**Comment by koron** [comment]
Facebook方式、とでも言うんですかね?

**Comment by tyru** [comment]
> 豆腐？

豆腐が食べたい時に便利

**Comment by crazymaster** [comment]
launchpadのbug heat や bugzillaのvote みたいなのが実装されるのかと思っていたけど、
全然違ったw

**Comment by crazymaster** [comment]
気が済んだと思われるのでcloseします
