### ISSUE TITLE
本家のissueが放置されてるんだけどなんとかならないか?

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#87]
https://code.google.com/p/vim/issues/list

これらが凄い放置されている。実は直ってるのかもしれないけど…
Bramに見るように進言するか、我々でパッチ回して見ざるを得ない状況を作り出すか。
なんかできないかしらねぇ?

**Comment by mattn** [comment]
なんかドキュメントサイトのissueもまざってるので純粋なissueは半分くらいっぽそう

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/5rfnvwu_T5I/KCji1epyoXkJ より、

> I would appreciate if someone volunteers to close issues that have been
> fixed or turn out to be non-issues.  Ben, Christian, someone else?

Bram がボランティアを募集していましたが、Christian が手を挙げたようです。

**Comment by h-east** [comment]
@k-takata We would do it too. We are vim-jp. yeah! でええんちゃいますか？
少なくとも私は空いてる時間にCHECK&DOするようにします。

**Comment by h-east** [comment]
Open issuesが 154個!!   ってvim-jp/issuesの方が多いけどなｗｗ
https://code.google.com/p/vim/issues/list?can=2&q=&colspec=ID+Type+Status+Priority+Milestone+Owner+Summary&cells=tiles

**Comment by k-takata** [comment]
怒濤のclose祭りで残り106個まで減りました。
大幅に状況が改善されましたので閉じます。

**Comment by mattn** [comment]
ここみてるんじゃないか説
