### ISSUE TITLE
Windows では synIDattr() 関数が予期せぬ値を返す場合がある

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#870]
## 質問・報告の内容

`synIDattr()` 関数でセットされていないハイライト要素を取得しようとすると ~~-1~~ `'-1'` (文字列) を返す場合があります。例えばデフォルトの配色だと `Visual` ハイライトグループには `ctermfg` がセットされていないので、

``` vim
echomsg synIDattr(synIDtrans(hlID('Visual')), 'fg', 'cterm')
```

が ~~-1~~ `'-1'` (文字列) を返します。しかし同様に `guifg` について試すと空文字列を返します。ドキュメントには返り値は文字列とあるので両方の場合で空文字列が返ることを期待します。
- 再現方法
  
  ```
  " -1 を返す。期待とは異なる動作
  :echo synIDattr(synIDtrans(hlID('Visual')), 'fg', 'cterm')
  
  " 空文字列を返す。期待通りの動作
  :echo synIDattr(synIDtrans(hlID('Visual')), 'fg', 'gui')
  ```
## Vimのバージョン

7.4.979
## OSの種類/バージョン
-   Windows 10
## その他
- vim と gvim で試しましたがどちらの場合でも `cterm` のハイライト要素を取得しようとしたときに -1 が返るようです。
- Linux では再現しませんでした。
- 再現のコマンドは `hlID()` 関数のヘルプの例にあるものを改変しました。

**Comment by koron** [comment]
コード眺めるだけだと、どうしてそうなるかわからないなw

**Comment by koron** [comment]
> -1 を返します。

これ数字の -1 じゃなくて、文字列の "-1" が返ってきてたw

**Comment by machakann** [comment]
あれ、ほんとですね。すいません勘違いしてました。

**Comment by koron** [comment]
src/syntax.c の `highlight_color()` の終り近くの以下の部分が原因。

``` c
if (modec == 'c')
{
    if (fg)
        n = HL_TABLE()[id - 1].sg_cterm_fg - 1;
    else
        n = HL_TABLE()[id - 1].sg_cterm_bg - 1;
    sprintf((char *)name, "%d", n);
    return name;
}
```

近視眼的には `n < 0` の時に `sprintf()` せずに `NULL` を返せば良い。
が、実際はこの関数を使ってる場所を、念のためチェックしたほうが良さそう。

**Comment by machakann** [comment]
本文に微妙な修正をしました

**Comment by koron** [comment]
とりあえずこんなパッチで直った。

``` diff
diff --git a/src/syntax.c b/src/syntax.c
index e37dacb..9586c82 100644
--- a/src/syntax.c
+++ b/src/syntax.c
@@ -8999,6 +8999,8 @@ highlight_color(
        n = HL_TABLE()[id - 1].sg_cterm_fg - 1;
    else
        n = HL_TABLE()[id - 1].sg_cterm_bg - 1;
+        if (n < 0)
+            return NULL;
    sprintf((char *)name, "%d", n);
    return name;
     }
```

**Comment by koron** [comment]
今ドキュメントを見たら、別に空文字列を返すとは書いてありませんね。

> ```
>   "fg"        foreground color (GUI: color name used to set
>           the color, cterm: color number as a string,
>           term: empty string)
> ```

カラー番号を文字列として返すとしかない。
が…一応チャレンジしてみましょうかね。

**Comment by koron** [comment]
sent a patch https://groups.google.com/d/msg/vim_dev/S-x9R3NSi-c/ihv-vXAjFwAJ

**Comment by machakann** [comment]
ありがとうございます！

一応ですが他の場合 (term, gui) では空文字だったので、これに合わせるのが自然かと思ったのでした。言葉足りずですいません。

**Comment by h-east** [comment]
patch 7.4.1547 :+1: 
https://github.com/vim/vim/commit/385111bd86e0b38667879c3e89506ca1ae98e1df

**Comment by machakann** [comment]
ありがとうございました。
