### ISSUE TITLE
getchar(0) で <BS> キーを拾えない？

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#871]
## 質問・報告の内容

`getchar()` 関数の引数に 0 を与えた時、 `<BS>` キーの入力に反応しないようなのですがなにか使い方がおかしいのでしょうか？

``` vim
function! Getchar0() abort
  while 1
    let c = getchar(0)
    if c != 0
      break
    endif
    sleep 20m
  endwhile
  return type(c) == type(0) ? nr2char(c) : c
endfunction

function! Getchar() abort
  let c = getchar()
  return type(c) == type(0) ? nr2char(c) : c
endfunction
```

このように `Getchar()` 関数と `Getchar0()` 関数を定義した時、

``` vim
echo Getchar()
```

はバックスペースの入力に対し `<80>kb` (=`"\<BS>"`) を返しますが、

``` vim
echo Getchar0()
```

は反応しないようです。
## Vimのバージョン

7.4.979
## OSの種類
-   Windows 10

**Comment by mattn** [comment]
Getchar0 を以下の様に書き換えて下さい。

``` vim
function! Getchar0() abort
  while 1
    let c = getchar(0)
    if !empty(c)
      break
    endif
    sleep 20m
  endwhile
  return type(c) == type(0) ? nr2char(c) : c
endfunction
```

getchar() もしくは getchar(0) は数値が返る場合と文字列が返る場合があり、`<BS>` の場合は文字列が返ります。なのでループを抜けません。empty(c) だと 0 でも空文字列でも 1 が返るので期待の動作になるかと思います。

**Comment by machakann** [comment]
納得しました！ありがとうございます。
