### ISSUE TITLE
packloadallについて

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/issues#873]
## 質問・報告の内容

まだ加わったばかりなのであれですけど、とりあえず上げときます。
- repeat.txtの`:packloadall[!]`にタグが付いてない。
- `:packloadall[!]`の省略形がない。
## Vimのバージョン

7.4.1553

**Comment by h-east** [comment]
> repeat.txtの:packloadall[!]にタグが付いてない。

vim_devにpatch(という程のものでもないですが)送りました。
https://groups.google.com/d/msg/vim_dev/Onh3HLK_S-I/gI6HdDqjFwAJ

> :packloadall[!]の省略形がない。

`packl`でいけます。

**Comment by rbtnn** [comment]
> > 　:packloadall[!]の省略形がない。
> > packlでいけます。

あなるほど、実装はあって、ヘルプに記載されてないだけなんですね。

**Comment by h-east** [comment]
> repeat.txtの:packloadall[!]にタグが付いてない。

付きました。
https://github.com/vim/vim/commit/e18c0b39815c5a746887a509c2cd9f11fadaba07#diff-0b6e62da05b371a3136d47e3d34202d4R252

閉じようと思ったら、次の行が対応漏れだ。
誤: `:packloadall[!]`
正: `:packl[oadall][!]`
後で報告します。

**Comment by rbtnn** [comment]
@h-east 直ったのでクローズします。ありがとうございました。

https://github.com/vim/vim/blob/03413f44167c4b5cd0012def9bb331e2518c83cf/runtime/doc/repeat.txt#L257
