### ISSUE TITLE
revenge of overthespot

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#874]
## 質問・報告の内容

**目標設定**
overthespot 機能を取り込んでもらう。

**背景**
GTK系におけるIMの挙動は onthespot のため、いろいろ問題を起こしている。
これらは overthespot にすることで、解決することが知られている。
過去に onthespot をやめて overthespot にするようにした [パッチは拒否](https://groups.google.com/d/msg/vim_dev/SK3t_RsWMqM/K5Quc2PQftkJ) された。

**方針**
過去のパッチが拒否されたのは、そのパッチが単に onthespot 機能を消してしまうことが原因だったと推測される。
仮にこれが configuration で選択できたり、実行時のオプションで選択が可能だったならば、
結果はまた違ったのではなかろうか。

よって本issueでは
可能ならばオプション設定で、次善の策としてはconfigurationでの選択式による
overthespot 機能の導入を目指す。
## 関連 issues
- https://github.com/vim-jp/issues/issues/53
- https://github.com/vim-jp/issues/issues/545
- https://github.com/vim-jp/issues/issues/663
- https://github.com/vim-jp/issues/issues/730

**Comment by k-takata** [comment]
vim/vim#1215 も over-the-spot で直るのだろうか。

**Comment by k-takata** [comment]
これも関連 issues かな
- #50 
- #223 
- (#239)
- #546

**Comment by k-takata** [comment]
on-the-spot/over-the-spot 両対応パッチ作ってみました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/63e9d7139a6626a9463f70b93ba484a7137437b0/gtk_im_over-the-spot.patch?fileviewer=file-view-default
'imstyle' が 0 (default) で on-the-spot、1 で over-the-spot です。

**Comment by k-takata** [comment]
ところで、`:help xim-input-style`を見ると、

```
  現在、GUI Vimは|OverTheSpot|、|OffTheSpot|、|Root|の3つのスタイルをサポート
  している。
```

とのことですが、これはどの環境でのことなのでしょうか？

**Comment by mattn** [comment]
X11 ですね。昔は .Xresources で preeditType を指定してプリエディットを切り替えていたので。

**Comment by k-takata** [comment]
なるほど。ということは、ヘルプがGTKに対応できていないと。

反応を見るために、とりあえず投げてみました。
https://github.com/vim/vim/issues/1215#issuecomment-279741789

**Comment by k-takata** [comment]
入力スタイルの違いがよく分かる参考資料
http://www.mozilla-japan.org/projects/intl/input-method-spec.html
ユーザーの視点では、on-the-spotのまま問題を修正できるならそれが一番良さそうですが、難しそう。

なお、今回のパッチですが GTK3 対応の修正も入れてあります。

**Comment by mattn** [comment]
一応僕の知見を共有しておくと、GTK には IM を制御する機能がなく、GtkImModule を使うと制御は可能だけど、それは IM のドライバレベルなので GTK アプリ側からは制御不可。imactivatekey 的な事は出来ないです。

**Comment by k-takata** [comment]
```
Patch to support on-the-spot and over-the-spot input method. (Ken Takata, 2017
Feb 14).
```

todo入りしましたが、本issueの目標は取り込まれることなので、openしたままにします。

**Comment by mattn** [comment]
入ってほしい。

On 2/19/17, K.Takata <notifications@github.com> wrote:
> ```
> Patch to support on-the-spot and over-the-spot input method. (Ken Takata,
> 2017
> Feb 14).
> ```
>
> todo入りしましたが、本issueの目標は取り込まれることなので、openしたままにします。
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/874#issuecomment-280893953


-- 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
https://github.com/vim/vim/issues/1215#issuecomment-325175424
パッチ更新。デフォルトを over-the-spot に変更し、それに合わせてドキュメントを修正。

**Comment by k-takata** [comment]
over-the-spot じゃなくて on-the-spot の改良型じゃないのと文句を言っている人がいますが、実際のところどうなんですか？

**Comment by mattn** [comment]
真意は分かりませんが、彼の言ってるのは root window の事かと思ってます。

**Comment by k-takata** [comment]
https://tkng.org/unixuser/200405/column2.html

> * on the spot style
>   アプリケーションで責任を持って描画するスタイル。アプリケーション側で描画するのはこのスタイルだけだ。Gtk+2はウィジェットにもよるが基本的にこのスタイル。他にはOpenOfficeもこのスタイルである。
> * over the spot style
>   キャレット位置をアプリケーションから取得し、XIMサーバが描画するスタイル。Gtk+1.2はこのスタイル。

誰が描画しているかという点で見ると、確かに on-the-spot プロトコル上で over-the-spot 的動作を実現しているということになるのかな？
正直、使う側からしたら、実装の詳細なんてどうでもいいのですが。

**Comment by k-takata** [comment]
8.0.1026
https://groups.google.com/d/topic/vim_dev/-acKWk-MjIo/discussion
長かった…。
（そして私の名前が違うぞｗ）

**Comment by k-takata** [comment]
Big Sky :: Vim と日本語入力の話。 
https://mattn.kaoriya.net/software/vim/20170905113330.htm
リンクを載せずにはいられない。
