### ISSUE TITLE
特定のパッチ（1404）以降で、キーボードのリマップソフトウェアを介した日本語入力の誤判定が増える

### ISSUE THREAD

**Issue by nekowasabi** [vim-jp/issues#877]
## 質問・報告の内容

パッチ1404以降（パッチ1403以下では発生しない）で
親指シフトアプリ（dvorakj）を使って日本語入力を行うとき、
キー入力の判定の遅延が発生する。
半角英数（IME OFF）のときは発生しない。
別の親指シフトアプリ（やまぶきR）での日本語入力時は発生しない。

ex.親指シフトアプリの設定、テスト方法と実行結果
Aキーを打鍵すると『あ』
Bキーを打鍵すると『い』
A,Bキー同時に打鍵で『おはよう』が入力される設定とする。

Aキー→Bキーと順番に打鍵して『あい』という文字列が入力されるはずが、
『おはよう』とA,Bキーの同時打鍵と判定されてしまう。

半角英数（IME OFF）のときは発生しない。
別の親指シフトアプリ（やまぶきR）での日本語入力時は発生しない。
## Vimのバージョン

v7.4.1404: patch 7.4.1404
## OSの種類
-   Windows8
## 使用している or 関係していそうなプラグイン

プラグインの使用なし。
msys2 mingw64でビルドしたバイナリで実行している。
## その他

kaoriyaパッチは適用していない、素のgvimで発生する。

**Comment by koron** [comment]
[7.4.1404 の内容](https://github.com/vim/vim/commit/9186a276222ea8a7c88f4092ac5b4201381f4e20)

**Comment by koron** [comment]
@nekowasabi 

dvorakj というのは http://blechmusik.xii.jp/dvorakj/ このソフトで正しいですか? 

仮にそうだとすれば「親指シフト」ではなく、キーボードのリマップソフトウェアを使っている場合、ということで
タイトルと報告内容を微修正しておいたほうが良いかと思います。

---

該当するパッチ内容をみると、メッセージ処理のタイミングが変わっていたりするので、
そういうのと相性悪そうだなとも。

**Comment by mattn** [comment]
このパッチの修正内容は、元々 WSAAsyncSelect を使って channel を実現していたけどそうすると切断やタイムアウト等がうまくハンドリング出来ないという問題があり、その回避策としてメッセージループ内にスレッドメッセージやあらゆる入力イベントを監視し、channel を受信できるスキを作ってやろうという物です。
この for ではメッセージは抜き取っては無いのですが、一定時間待ってしまっている事で、今回の様に片方ずつキーを押したのにそれがキューイングされ「同時押し」扱いになった(んじゃないかな？)というのが僕が推測するシナリオです。

gui_w32.c:2214

``` c
    /* Check channel while waiting message. */
    for (;;)
    {
        MSG msg;

        parse_queued_messages();

        if (pPeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE)
        || MsgWaitForMultipleObjects(0, NULL, FALSE, 100, QS_ALLEVENTS)
                                != WAIT_TIMEOUT)
        break;
    }
```

この100を少なくすれば重くなる可能性はありますが片方押しの判定精度は上がると思っています。一度試して貰っていいでしょうか？

**Comment by mattn** [comment]
@ynkdir これループせずに parse_queued_messages(); だけだとまずいんですっけ？

**Comment by mattn** [comment]
parse_queued_messages(); だけにしても一応テスト(test_channel.vim)は通りますね。

**Comment by nekowasabi** [comment]
>  http://blechmusik.xii.jp/dvorakj/ 

このソフトです。

> この100を少なくすれば重くなる可能性はありますが片方押しの判定精度は上がると思っています。一度試して貰っていいでしょうか？

20にしたところ、問題なく入力できるようになりました。

**Comment by ynkdir** [comment]
> これループせずに parse_queued_messages(); だけだとまずいんですっけ？

gvim が待機中のときに GetMessage() でブロックするのでチャンネルに応答できなくなります。

**Comment by mattn** [comment]
``` c
#ifdef MESSAGE_QUEUE
    if (pPeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE))
#endif
        process_message();
```

こうだとヘビーループすぎますか？

**Comment by ynkdir** [comment]
ウェイトなしはつらい気がします

**Comment by ynkdir** [comment]
QS_ALLEVENTS は QS_SENDMESSAGE が入ってないみたいなので QS_ALLINPUT に変更するとどうですか

**Comment by mattn** [comment]
@ynkdir さん多忙そうなので本件僕が引き取ります。

**Comment by mattn** [comment]
@nekowasabi このパッチでも問題は発生するでしょうか？

``` diff
diff --git a/src/gui_w32.c b/src/gui_w32.c
index b2ee9ca..0679ed2 100644
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -2218,7 +2218,7 @@ gui_mch_wait_for_chars(int wtime)
        parse_queued_messages();

        if (pPeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE)
-       || MsgWaitForMultipleObjects(0, NULL, FALSE, 100, QS_ALLEVENTS)
+       || MsgWaitForMultipleObjects(0, NULL, FALSE, 100, QS_ALLINPUT)
                                != WAIT_TIMEOUT)
        break;
    }
```

**Comment by ynkdir** [comment]
ありがとうございます。

**Comment by nekowasabi** [comment]
@mattn  1404にパッチを適用したところ、問題が発生しなくなりました。ありがとうございます！

**Comment by mattn** [comment]
@nekowasabi ありがとうございます。中平さんのクレジットで vim-dev に提出させて頂きます。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/DMLfx5bRf8o

**Comment by k-takata** [comment]
>   MsgWaitForMultipleObjects(0, NULL, FALSE, 100, QS_ALLEVENTS)
> 
> But QS_ALLEVENTS doesn't contain keyboard inputs. This should be:
> 
>  MsgWaitForMultipleObjects(0, NULL, FALSE, 100, QS_ALLEVENTS)

s/QS_ALLEVENTS/QS_ALLINPUT/ ですね。

**Comment by mattn** [comment]
まぁパッチは直ってるので。。。指摘が必要と思ったらしておいてください。

**Comment by crazymaster** [comment]
patch 7.4.1694
https://github.com/vim/vim/commit/f28d87146544e3b5d70aaa6a2513019f6de043ad
