### ISSUE TITLE
make installrtbase でhelp tagsの生成に失敗しても無視されてしまう

### ISSUE THREAD

**Issue by Tosainu** [vim-jp/issues#882]
## 質問・報告の内容

[src/Makefile のこの部分](https://github.com/vim/vim/blob/master/src/Makefile#L2113-L2127) にあるように, `make installrtbase` などを行った際にhelp tagsの生成が行われていますが, この時 `$(DEST_BIN)/$(VIMTARGET)` が存在しないなどの特殊な状況により生成に失敗してもエラーが無視されてしまうようです.

```
generating help tags
cd ../runtime/doc; mv -f tags tags.dist
make[1]: Entering directory '/home/cocoa/repo/github.com/vim/vim/runtime/doc'
/tmp/bin/vim -u NONE -esX -c "helptags ++t ." -c quit
/bin/sh: /tmp/bin/vim: No such file or directory
Makefile:314: recipe for target 'vimtags' failed
make[1]: *** [vimtags] Error 127
make[1]: Leaving directory '/home/cocoa/repo/github.com/vim/vim/runtime/doc'
Makefile:2112: recipe for target 'installrtbase' failed
make: [installrtbase] Error 2 (ignored)
cd ../runtime/doc; \
    files=`ls *.txt tags`; \
    files="$files `ls *.??x tags-?? 2>/dev/null || true`"; \
    cp $files  /tmp/share/vim/vim74/doc; \
    cd /tmp/share/vim/vim74/doc; \
    chmod 644 $files
ls: cannot access 'tags': No such file or directory
cp  ../runtime/doc/*.pl /tmp/share/vim/vim74/doc
chmod 755 /tmp/share/vim/vim74/doc/*.pl
cd ../runtime/doc; mv -f tags.dist tags
```

通常このようなことが起こることは無いとは思いますが, [patch 7.4.1556](https://github.com/vim/vim/commit/a3442cb5056ca62fc71fa03f68a9395e4391caf4) の変更からは生成に失敗した場合 `runtime/doc/tags` がインストールされなくなってしまうので, ちゃんとエラーとして扱うべきではないのかなと思います.
## Vimのバージョン

7.4.1529 (Arch Linux 公式repo)
7.4.1555, 7.4.1576 (自分でビルド) など
## OSの種類
-   Linux
## OSのディストリ

Arch Linux
## その他

Arch Linuxでは `vim` と `vim-runtime` というように別々にパッケージが提供されており,  `vim-runtime` の生成段階でこのような状況が発生しています.
もちろん, このような状況を起こしているのはArch LinuxのVimパッケージ側の問題ですが, このようなエラーが無視されてしまうのはVim側の問題ではないかと思い報告しました.
場違いであれば申し訳ありません.

**Comment by koron** [comment]
help tags の作成時には vim を使っているんですが、
そこで成功していても必ずエラーが発生している (非0 でexitする) 可能性があります。
仮にそうなら無視せざるを得ないわけですが…

**Comment by koron** [comment]
@Tosainu 
以前から tags を作るには vim が必要なんですが、
Arch Linux の vim-runtime の作成時にはどうしていたのでしょう?
単にvimがないから、古いままのtagsを用いていたということでしょうか?
そうだとすればそちらのほうが問題だと私は考えます。

Arch Linux には詳しくないので的ハズレなことを言ってるかもしれませんが、
vim-runtime の作成時の依存解決に vim を追加して、
それを使うようにsrc/Makefileへパッチを当ててから installrtbase するのが本筋ではないでしょうか。

それとは別に Vim には `:helptags` の正常動作をどう担保するのかという問題は有ります。
しかし、そもそもVimが利用できない時にinstallrtbaseを失敗させるというケースまで
VimのMakefileが保証する謂れはないでしょう。

**Comment by koron** [comment]
関連して #883 を追加しておきました。

**Comment by Tosainu** [comment]
まず現在のArch LinuxのVimパッケージの作成のされ方ですが,
1. VimのソースのDL, 展開, パッチ適用など
2. `./configure`, `make`
3. `vim` パッケージの作成
   1. fakeroot環境に `make install`
   2. `vim-runtime` でインストールされるファイルを削除しパッケージ化
4. `vim-runtime` パッケージの作成
   1. 3 と違うfakeroot環境(`/bin/vim` が無い) に `make installruntime install-languages installtools`
   2. パッケージ化

という感じになっており, おっしゃるとおりVimのリポジトリに含まれる古いままのtagsが使われてきました.
このため, Arch Linuxの `vim-runtime` のtagsが古い/入っていないという問題の原因はもちろんArch LinuxのVimパッケージ側にあります.

本題のtagsの生成失敗がエラーにならないですが, 生成に成功してもVimが非0でexitしうるというのを考えると, 確かに対処は難しそうですね...

**Comment by koron** [comment]
エラー検出ではなく、tags がなかったら tags.dist をインストールする案は #883 で出ています。
個人的にはあまり良いとは考えていませんが、次善の策ということで。

ただそれが入ったとしても Arch Linux としては、
4-i の時点での動作に何かしらパッチをあてたほうが良いように思います。

**Comment by k-takata** [comment]
``` diff
--- a/src/Makefile
+++ b/src/Makefile
@@ -2116,7 +2116,8 @@ installrtbase: $(HELPSOURCE)/vim.1 $(DES
 # Move the distributed tags file aside and restore it, to avoid it being
 # different from the repository.
    cd $(HELPSOURCE); mv -f tags tags.dist
-   -@cd $(HELPSOURCE); $(MAKE) VIMEXE=$(DEST_BIN)/$(VIMTARGET) vimtags
+   -@cd $(HELPSOURCE); $(MAKE) VIMEXE=$(DEST_BIN)/$(VIMTARGET) vimtags || \
+       if test ! -f tags; then cp tags.dist tags; fi
    cd $(HELPSOURCE); \
        files=`ls *.txt tags`; \
        files="$$files `ls *.??x tags-?? 2>/dev/null || true`"; \
```

こんな感じでどうでしょう。動作未確認。

エラーコードを無視しているのは、vimがない環境でもとりあえずインストールできるようにするためなのか、helptagsの生成時にエラーを返す場合があるのか、どちらでしょうね？

**Comment by koron** [comment]
僕は後者だと思ってます。

vimdoc-ja-working や gen_syn_vim の travis-ci 設定した際に
ちょっとしたことで vim がエラーで終了してイライラしてました。
# 特に ex モード (`-e`) 使うとヒドくて…

**Comment by k-takata** [comment]
vim/vim#740 クロスコンパイルしたときに同様の問題が起きるようになったとのこと。なるほど、確かに。
ということで、パッチ送付。

**Comment by k-takata** [comment]
> I don't like this solution, because an error in generating the tags file would go unnoticed.

うーん、そうは言っても今までエラー見てなかったのに…。どうするのがよいやら。

**Comment by k-takata** [comment]
todoに以下の内容が追加されました。

```
When cross-compiling skip generating the tags file (and moving it out of the
way). (Christian Neukirchen, 2016 Apr 7)  #740
```

クロスコンパイルのときは特別扱いとなると、今回のArch Linuxでの問題はそのまま残ることになってしまいそうです。

**Comment by Tosainu** [comment]
報告が遅れましたが, Arch Linux の Vim パッケージの問題は 3/23の更新で修正されました.
(`vim-runtime` でも `make install` するようになった)
https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/vim&id=388b4da8da1b3f7817350e24c22d3760405154cb

**Comment by k-takata** [comment]
クロスコンパイル時の問題は 7.4.1733 で直りました。
https://groups.google.com/d/topic/vim_dev/7G0SRa9-l_8/discussion
が、エラーコードを見ていないのはそのまま？

**Comment by k-takata** [comment]
エラーコードを見ていないという課題はあるものの、実用上の問題はなくなったと思いますので閉じます。
