### ISSUE TITLE
timer機能を叩く

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#885]
Vimに導入されたばかりのtimer機能について議論しましょう。
- timer APIを叩いてバグを出す。
- timer APIの仕様について議論する。
- その他、timer機能に関すること何でも。

次のリリースが出たら、このissueは閉じます。

**Comment by h-east** [comment]
timer機能が追加されたのは patch 7.4.1578 
https://github.com/vim/vim/commit/975b5271eed4fa0500c24a8f37be0b1797cb9db7

Win32 consoleで`:sleep`なしにコールバックが呼ばれるようになったのが patch 7.4.1584
https://github.com/vim/vim/commit/0e0b3dd335b863603b9a2d415ef18d983e2467ae

GUIの場合はWindows/Linuxともに`:sleep`なしにコールバックが呼ばれる。
現状ではLinux CUIが`:sleep`なしにコールバックが呼ばれない。

**Comment by h-east** [comment]
Linux CUIで`:sleep`なしにコールバックが呼ばれるようにするpatch.
※とりあえず HAVE_SELECT 環境のみ対応。

既知の問題点: タイマが裏で動いている時に`:`でコマンドモードに移行すると、カーソルがバッファ内へ移動してしまう。(コマンド入力は普通にできる)

``` patch
diff --git a/src/os_unix.c b/src/os_unix.c
index f2ae513..6754d51 100644
--- a/src/os_unix.c
+++ b/src/os_unix.c
@@ -5445,6 +5445,7 @@ RealWaitForChar(int fd, long msec, int *check_for_gpm UNUSED)
 {
     int        ret;
     int        result;
+    long   msec_orig = msec;
 #if defined(FEAT_XCLIPBOARD) || defined(USE_XSMP) || defined(FEAT_MZSCHEME)
     static int busy = FALSE;

@@ -5624,6 +5625,22 @@ RealWaitForChar(int fd, long msec, int *check_for_gpm UNUSED)
        return 0;
 # endif

+#ifdef FEAT_TIMERS
+   /* When waiting very briefly don't trigger timers. */
+   if (towait > 10 || towait == -1)
+   {
+       long    due_time;
+
+       /* Trigger timers and then get the time in msec until the
+       * next one is due.  Wait up to that time. */
+       due_time = check_due_timer();
+       if (due_time > 0 && (towait > due_time || towait == -1))
+       towait = due_time;
+       else if (due_time <= 0 && msec_orig < 0)
+       towait = msec_orig;
+   }
+#endif
+
    if (towait >= 0)
    {
        tv.tv_sec = towait / 1000;
```

**Comment by mattn** [comment]
unix 版は上げ忘れだった模様。
https://github.com/vim/vim/commit/943bb2b8eb80266a5de143feeab4c842c4b68c61

**Comment by mattn** [comment]
Windows CUI 版も上げ忘れだったしw

**Comment by h-east** [comment]
@mattn えー！笑うしかないあはははは

**Comment by h-east** [comment]
> 既知の問題点: タイマが裏で動いている時に:でコマンドモードに移行すると、カーソルがバッファ内へ移動してしまう。(コマンド入力は普通にできる)

これ直ってない。直そう。

**Comment by mattn** [comment]
redrawcmdprompt() 呼ぶだけでいけそうなヨカン

redrawcmd() の方がいいか。

**Comment by h-east** [comment]
あえてノーマルモードとインサートモードの時だけ`update_screen(0);`を読んでいる。
その他のモードで呼ぶと、wildmenu中の表示が消されたり、`<C-D>`で出したリストが消されたり、`more`中の表示が消されたりするので。

``` patch
diff --git a/src/screen.c b/src/screen.c
index c1eb1c4..e608aed 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -418,8 +418,13 @@ redraw_asap(int type)
     void
 redraw_after_callback()
 {
-    update_screen(0);
-    setcursor();
+    if (State & CMDLINE)
+   redrawcmdline();
+    else if ((State & NORMAL) || (State & INSERT))
+    {
+   update_screen(0);
+   setcursor();
+    }
     cursor_on();
     out_flush();
 #ifdef FEAT_GUI
```

**Comment by h-east** [comment]
勢いでpatchを送ってみただ。patchが間違っていても問題提起として機能すればOK:+1:
https://groups.google.com/d/msg/vim_dev/MnIeBK-XLgc/i5xzuk2NGQAJ

**Comment by h-east** [comment]
おぉ！私のpatch＋αですんなり取り込まれた。
patch 7.4.1603
https://github.com/vim/vim/commit/bfb96c047b79b2aab5fd57a2472871508819f3ef

**Comment by h-east** [comment]
> > Yeah, I had been waiting for this patch :-) 
> 
> Sorry, somehow I just forgot to include it with the patch that went out earlier. 

patch 7.4.1594は本当に上げ忘れてたみたい:sweat_smile:

**Comment by anekos** [comment]
timer で vim を殺せるようです。

``` timer.vim
let s:meow = {}

function! s:meow.bite (...)
endfunction

call timer_start(100, s:meow.bite)
```

を

```
$ vim -u NORC --noplugin -N ~/sandbox/vim/timer.vim
```

などとして、開いて `:so%` などとすると落ちます。
すぐには落ちない時もあるようです。

Arch Linux の 7.4.1639-1 と手元で make した 7.4.1655 (1e7885abe8daa) で確認しました。

**Comment by h-east** [comment]
@anekos Wao! こちらでも再現しました。再現率100%。今晩調べます。

**Comment by h-east** [comment]
これで直ったと思います。確認をお願いします。

``` patch
diff --git a/src/eval.c b/src/eval.c
index 2256589..06f3585 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -20190,6 +20190,7 @@ get_callback(typval_T *arg, partial_T **pp)
     if (arg->v_type == VAR_PARTIAL && arg->vval.v_partial != NULL)
     {
        *pp = arg->vval.v_partial;
+       ++(*pp)->pt_refcount;
        return (*pp)->pt_name;
     }
     *pp = NULL;
```

**Comment by anekos** [comment]
ありがとうございます。
落ちなくなりました!

**Comment by h-east** [comment]
@anekos 確認Thanks!

この修正した関数`get_callback()`ってjob関係でも使われてますね。

```
./channel.c|3401| opt->jo_callback = get_callback(item, &opt->jo_partial);
./channel.c|3413| opt->jo_out_cb = get_callback(item, &opt->jo_out_partial);
./channel.c|3425| opt->jo_err_cb = get_callback(item, &opt->jo_err_partial);
./channel.c|3437| opt->jo_close_cb = get_callback(item, &opt->jo_close_partial);
```

この辺も直るってことですね。
partialな関数をコールバックに指定するとメモリ解放した部分を参照してしまうのでVimが不安定になってた！

**Comment by k-takata** [comment]
またrefcountかっｗ

**Comment by mattn** [comment]
てかrefcountのバグ多くねw 今回だけじゃないしw

**Comment by h-east** [comment]
sent to vim_dev
https://groups.google.com/d/msg/vim_dev/RVKtRdnbhZQ/Sbu9xaCwGwAJ

**Comment by koron** [comment]
Vim script の元々の関数の取り扱いからして、 partial は無理があった気がする。結果論だけど。

**Comment by h-east** [comment]
anekos さん報告の件、fixされました。
patch 7.4.1656
https://github.com/vim/vim/commit/92e35efaf6a3278e4729115648997f09cd4005f5

@anekos 報告ありがとうございました:+1:

**Comment by ichizok** [comment]
Vim 7.4.1782 / CentOS 7, Ubuntu 16.04 で検証。

**`time` が短いと入力が効かなくなる**

timer1.vim:

``` vim
function! TimerCallback(...)
  call timer_start(0, 'TimerCallback')
endfunction
```

`vim -Nu timer1.vim`
`:call TimerCallback()`

`Ctrl-C` で止められます（入力が効くようになる）。

timer2.vim:

``` vim
function! TimerStart()
  call timer_start(0, 'TimerCallback', {'repeat' : -1})
endfunction
function! TimerCallback(...)
endfunction
```

`vim -Nu timer2.vim`
`:call TimerStart()`

こちらは `Ctrl-C` しても入力を受け付けません。

**`callback` の中で `timer_stop()` が効かない**

timer3.vim:

``` vim
function! TimerStart()
  let s:tr = timer_start(1000, 'TimerCallback', {'repeat' : -1})
endfunction
function! TimerCallback(...)
  call append('$', 'a')
  call TimerStop()
endfunction
function! TimerStop()
  call timer_stop(s:tr)
endfunction
```

`vim -Nu timer3.vim`
`:call TimerStart()`

`a` が追加され続けます。

**Comment by norio13** [comment]
Vim 1.7.1859 / Debian jessie / tmux 2.2-1~bpo8+1

timer_startの第一引数が4006ミリ秒以上を指定した時にのみ、そのミリ秒経過した時にVimが落ちました。
tmux上でvimを使用した時のみ再現します。
ターミナルで直接Vimを起動した場合は落ちません。
Vimと関係なかったらすみません。

**ケース1**

落ちた時のエラーメッセージ

```
Vim: Caught deadly signal ABRT
Vim: Finished.
中止
```

Vim起動時にファイル名を指定するとsignal ABRTで落ちました。
ファイル名を指定しなかった場合はsignal SEGVで落ちました。

```
vim -Nu NONE -S sample1.vim a.txt
```

ファイル名に拡張子を省いて指定して起動すると、下記の2行のエラーメッセージも追加で表示されました。

```
vim -Nu NONE -S sample1.vim a
```

---

```
Vim: Double signal, exiting
Segmentation fault
```

sample1.vim:
スクリプトの中のコメント行も再現に必要です。
コメント行を削除すると再現しませんでした。

```
function Callback(lists, timer)
    " a
    " a
    doautocmd BufRead
endfunction
call timer_start(4006, function('Callback', [['a']]))
```

**ケース2**

落ちた時のエラーメッセージ

```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```

Vim起動
ファイル名を指定した時だけ落ちました。

```
vim -Nu NONE -S sample2.vim a.txt
```

sample2.txt

```
function Callback(lists, timer)
    echo a:lists
endfunction
call timer_start(4006, function('Callback', [['a']]))
```

**Comment by ichizok** [comment]
私の環境では以下で落ちました。 Ubuntu 16.04 / Vim 7.4.1859

sample.vim:

``` vim
function Callback(lists, timer)
endfunction
call timer_start(4006, function('Callback', [['a']]))
```

`vim -Nu NONE -S sample.vim`

---

timer の partial が保持しているオブジェクト (sample.vim における `['a']`) について、copyID を更新する処理がないため、timer 発火以前に GC で解放されてしまうのが原因と思われます。

sample.vim:

``` vim
function Callback(lists, timer)
endfunction
call timer_start(500, function('Callback', [['a']]))
call garbagecollect()
```

↑これで落ちます。

`set_ref_in_timer()` を追加しました。
https://gist.github.com/ichizok/b41ac7f68c3364a38bb07479bc9c7a49

**Comment by h-east** [comment]
@ichizok :+1:
test_timer_gc.vimの中身はtest_timers.vimに含めた方が良い気がしました。

**Comment by ichizok** [comment]
> test_timer_gc.vimの中身はtest_timers.vimに含めた方が良い気がしました。

ありがとうございます。そのように変更しました。

**Comment by norio13** [comment]
@ichizok パッチ適用で落ちなくなりました。
迅速なご対応ありがとうございます。

**Comment by h-east** [comment]
@ichizok `let v:testing = 1`が消えちゃってますね。

**Comment by ichizok** [comment]
> `let v:testing = 1`

runtest.vim で設定されていたので消しました。

**Comment by h-east** [comment]
そうなのね。知らんかった。Thanks!

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/E_2jHYv3wUg
報告しました。

**Comment by ichizok** [comment]
7.4.1860
https://github.com/vim/vim/commit/e3188e261569ae512fb1ae2653b57fdd9e259ca3

**Comment by thinca** [comment]
> `callback` の中で `timer_stop()` が効かない

これまだ直ってないですね(7.4.2295)。vim_dev に報告だけでもした方がいいかな?

**Comment by thinca** [comment]
取り急ぎ拙い英語で簡単に報告だけしてみました。

https://groups.google.com/d/msg/vim_dev/hyMnZpE66do/sydVwPXgCAAJ

**Comment by thinca** [comment]
callback 内で `timer_stop()` できない件、Bram さんに直して頂けました！
7.4.2304
https://github.com/vim/vim/commit/417ccd7138d4d230d328de8b0d3892dd82ff1bee

**Comment by k-takata** [comment]
https://github.com/vim-jp/issues/issues/885#issuecomment-213895746
@ichizok さん指摘の「time が短いと入力が効かなくなる」は、そのままでしたっけ？
報告だけでもしておいたほうがいいのかな。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/_vL0QTcuuA4
`timer_stop()` の修正に問題があった点と合わせてパッチ投げました。

**Comment by ichizok** [comment]
7.4.2332
https://github.com/vim/vim/commit/75537a93e985ef32e6c267b06ce93629855dd983
https://github.com/vim-jp/issues/issues/885#issuecomment-213895746 で報告した件はすべて直ったはず。

**Comment by mattn** [comment]
closable?

**Comment by k-takata** [comment]
残件はないと思いますので、閉じます。

**Comment by mattn** [comment]
this too
