### ISSUE TITLE
Python 2.6.6 で test_channel.vim のテストが失敗する

### ISSUE THREAD

**Issue by wiredool** [vim-jp/issues#886]
## 質問・報告の内容

python 2.6.6 環境で `make test` を実行すると`test_channel.vim` のテストが失敗します。
https://gist.github.com/wiredool/eea5787a80d2f5348687
## Vimのバージョン
- 7.4.1615
## OSの種類
-   Linux
## OSのディストリ
- CentOS-based (OpenLogic)
## OSのバージョン
- 6.7
## その他

原因は、pythonの文字列フォーマット失敗のようです。
内部で実行しているテストコード `test_channel.py` において、python 2.7に追加された `{}` の数字の省略を行っています。
http://docs.python.jp/2/library/string.html#formatexamples

テストコードには python2.6 対応のつもりらしい表記はあります。

> `# This requires Python 2.6 or later.`
>  https://github.com/vim/vim/blob/master/src/testdir/test_channel.py#L6

環境要求を2.7とするか、2.6でも動作する形にした方が良いかと思います。

2.6環境にて、単純な置き換えでのテストは成功を確認できました。
`:%s#{}#{0}#g`
https://gist.github.com/wiredool/049d6101f4fab35a5176

**Comment by koron** [comment]
良いと思います。
そのgist のリンクつけて、vim-devに報告にしたらどうでしょうか?

> test_channel.vim is failed with python 2.6
> this patch will fix it.
> please check it.

みたいな文面だけでも、なんとかなります。 :+1:

**Comment by wiredool** [comment]
ありがとうございます！
文面をそのままお借りして報告してみます。

**Comment by malblue** [comment]
https://github.com/vim/vim/blob/master/runtime/tools/demoserver.py
も同様にした方がいいかも
手元のpython 2.6.5 ではこれで help channel.txt のサンプルが動きました

**Comment by koron** [comment]
1つ報告すれば、Bramが気がついて良い感じにしてくれる可能性もあります。
まぁ、最近頑張ってるので、気がつかない可能性もありますけど、
その時にまた指摘すれば良いのかな、と :sweat_smile:

**Comment by h-east** [comment]
vim_devへの投稿が表示されました。:+1:
https://groups.google.com/d/topic/vim_dev/1agjcgzcR7I/discussion

@wiredool 
たぶん本名を聞かれると思います。問題なければ先に名乗っておいた方が良いかも。

**Comment by h-east** [comment]
`wiredool`名義ですんなり取り込まれました:+1:
patch 7.4.1621
https://github.com/vim/vim/commit/a63cdb5ed685181c377ee89f1d1de6a97dfeb151

**Comment by h-east** [comment]
あー、 @malblue さん指摘の`runtime/tools/demoserver.py`は修正されてない。

**Comment by h-east** [comment]
@malblue さん指摘分も修正されました。:+1:
patch 7.4.1622
https://github.com/vim/vim/commit/17b56c9f8327e6869580e3cfd82efcf8966d797a

閉じます。Issue登録ありがとうございました。

**Comment by wiredool** [comment]
名義気にしないので大丈夫そうですね。
ありがとうございました。:+1:
