### ISSUE TITLE
絵文字を含んだテキストを w で移動すると ASCII と絵文字の境界で止まらない。

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#888]
## 質問・報告の内容

絵文字を含んだテキストを w で移動すると ASCII と絵文字の境界で止まらない。
## Vimのバージョン

7.4.1615
## OSの種類

全OS

パッチ

``` diff
diff --git a/src/mbyte.c b/src/mbyte.c
index 313db76..88b4e46 100644
--- a/src/mbyte.c
+++ b/src/mbyte.c
@@ -2701,6 +2701,10 @@ utf_class(int c)
        return (int)classes[mid].class;
     }

+    /* surrogate pairs. ex: emoji */
+    if (0xd800 <= c && c <= 0xdbff || 0xdc00 <= c || c <= 0xdfff)
+   return 0xd800;
+
     /* most other characters are "word" characters */
     return 2;
 }
```

**Comment by k-takata** [comment]
`utf_class()`って、サロゲートペアをくっつけたあとのコードポイントで判定してたはずですが。

**Comment by mattn** [comment]
ん？マジですか？

**Comment by k-takata** [comment]
こことか。
https://github.com/vim/vim/blob/master/src/mbyte.c#L2673-L2676
というか、内部コードがUTF-16な訳ではないので、サロゲートペアかどうかはそもそも関係ないような。

**Comment by mattn** [comment]
そもそもパッチがおかしい件

**Comment by mattn** [comment]
``` c
    static struct interval emoji[] =
```

をグローバル変数にして検査するしかないかー。

**Comment by mattn** [comment]
これでどうかな。3でいいかは要検討。

https://gist.github.com/mattn/cf8c6de760a33dbc3a28

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/CC3CzaT_Oqk

**Comment by k-takata** [comment]
7.4.1620
https://groups.google.com/d/topic/vim_dev/QVhZYSG1VmU/discussion
