### ISSUE TITLE
set backspaceの値が数値の時に set backspace+=eol すると引数エラーになる

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#89]
※再現手順
vim(gVim)起動

:set backspace=2
:set backspace+=eol
→<code>E474: Invalid argument: backspace+=eol</code>

wiredoolさんの報告ツイート
https://twitter.com/#!/wiredool/status/133048937039937536

※エラー説明
set bs は文字列指定&保持するがVer5.4以前の互換性の為に数値指定&保持も出来る。
現状では数値で保持されている時に set bs+=<em>文字列</em> するとエラーになる。

※改善案
(1) 数値保持に対してset bs+=<em>文字列</em> または set bs-=<em>文字列</em> されたら内部で数値保持を文字列保持に変換して処理する。
(2) エラーmsgを分り易くする。(数値オプションに対して+=や-=は使えないよ 等)
etc...

※備考(個人的に気になったところ)
・set bs-=～ の場合は何を指定してもNO　ERROR。item名が値に含まれている時だけ削除処理が行われる。
(item名削除処理されなかった時にエラーにしなくていいの？)
→set nrformats も全く同じロジックっぽい。Vim共通動作ならそのままでいい？

**Comment by mattn** [comment]
んー。vimscript側でなんとか出来るので、パッチを書いても取り入れられる可能性がかなり低いです。

``` vim
if &bs !~ '^\d\+$'
  set bs=eol
else
  set bs+=eol
endif
```

**Comment by koron** [comment]
`bs`のドキュメントで言及していない限り、わかりにくいってことには変わりないんじゃないかな。
だから修正はできないまでも、ドキュメントで対応するくらいはしといたほうが良い。

**Comment by mattn** [comment]
それは逆に歓迎されるでしょうね。

> ドキュメントで対応するくらいはしといたほうが良い。

**Comment by koron** [comment]
そしてkaoriyaのvimrcのbackspaceを数字で指定するのはやめろ、ということですね。

**Comment by mattn** [comment]
www

**Comment by h-east** [comment]
もしソースを弄るならこうですか？＞＜

``` diff
diff -r 379a6398d462 src/option.c
--- a/src/option.c  Wed Oct 26 23:48:21 2011 +0200
+++ b/src/option.c  Mon Nov 07 19:37:16 2011 +0900
@@ -4567,6 +4567,23 @@
                arg = errbuf;
                }
                /*
+                * Convert 'backspace' number to string, for
+                * adding, prepending and removing string.
+                */
+               else if (varp == (char_u *)&p_bs
+                            && VIM_ISDIGIT(**(char_u **)varp))
+               {
+               i = getdigits((char_u **)varp);
+               switch (i)
+               {
+               case 0: *(char_u **)varp = empty_option; break;
+               case 1: *(char_u **)varp = vim_strsave("indent,eol"); break;
+               case 2: *(char_u **)varp = vim_strsave("indent,eol,start"); break;
+               }
+               vim_free(oldval);
+               oldval = *(char_u **)varp;
+               }
+               /*
                 * Convert 'whichwrap' number to string, for
                 * backwards compatibility with Vim 3.0.
                 * Misuse errbuf[] for the resulting string.
```

vimoption構造体のメンバ var と indir がカオス過ぎる..（＃＾ω＾）ﾋﾟｷﾋﾟｷ

**Comment by koron** [comment]
@h-east △

**Comment by mattn** [comment]
すんません。パッチ見てやりたい事の意味が分かりました！

**Comment by h-east** [comment]
あざす。あざす。
@mattn issue本文を分り易い感じに修正しました。
変更前: set bs+=～
変更後: set bs+=文字列

これでよかですか？

**Comment by mattn** [comment]
いいと思います!

**Comment by mattn** [comment]
@h-east 出せますか？

**Comment by h-east** [comment]
@mattn うーん、今週末に頑張ってみます。englishムズい。
mattnさんの方で処理していただいてもOKですよ？。

**Comment by mattn** [comment]
https://groups.google.com/d/topic/vim_dev/wrT0j0rYG7k/discussion

**Comment by h-east** [comment]
@mattn ありがとうございます。刺身権(ハマチ専用)発生しました。

**Comment by h-east** [comment]
Patch 7.3.354で取り込まれました。
https://groups.google.com/forum/?hl=ja#!topic/vim_dev/F3uFnrdYO3g

**Comment by mattn** [comment]
@h-east++
