### ISSUE TITLE
将来 Vim 10 が出た際に has('patch-10.0.001') が動かなくなる

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#891]
## 質問・報告の内容

`:help has-patch` で説明されている機能、`has('patch-7.4.123')` が、メジャーバージョンとマイナーバージョンが1桁である前提で実装されているため、将来バージョンが上がった時に動かなくなります。

https://github.com/vim/vim/blob/8fdd7210479f0c486822ad8934087b4bfd8a4765/src/eval.c#L13839-L13854

今はいいけど、絶対直し忘れると思う…。早いうちに直した方が良さそう。
## Vimのバージョン

7.4.1657

**Comment by thinca** [comment]
補足:
`v:version` が、メジャーバージョンを100倍した値とマイナーバージョンを足したもの(ex: `Vim 7.4` => `v:version == 704`) なので、少なくともマイナーバージョンは 2 桁まで想定されているはずです。
メジャーバージョンはもちろんどこまで上がるかわからない想定をする必要があるはず。

**Comment by mattn** [comment]
ちょっと外れるけど関連
https://groups.google.com/forum/#!topic/vim_dev/L2iXv8PhPu4

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/10752

**Comment by k-takata** [comment]
9.0.0113: https://github.com/vim/vim/commit/d90f91fe3075bb51668ed926182b2163da9df001
