### ISSUE TITLE
statuslineの%{}などでevalした際に，try-catch でVimのエラーをキャッチしていても statusline が disable されてしまう

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#893]
## 質問・報告の内容

statuslineの%{}などでevalした際に，try-catch でエラーをキャッチしていても statusline が disable されてしまう

(キャッチされないエラーが発生したらstatuslineがdisableされるのは正しい)
#### statusline_test.vimrc

``` vim
set nocompatible

function! StatuslineKiller() abort
  try
    " :throw ではなく Vim のエラー(任意)を発生させる
    call eval('')
  catch
    return 'OK: error catched!'
  endtry
  return 'OK'
endfunction

set laststatus=2
set statusline=%{StatuslineKiller()}
```
1.  `vim -u statusline_test.vimrc -i NONE -N`
   - 'OK: error catched!' がstatuslineに表示される (actual & expected)
2. `:redrawstatus`
   - `" Press ENTER or type command to continue` が表示 (actual & expected)
   - Enter を押す
   - statusline が disable される (`&statusline == ''`)
### Expected な挙動
1.  `vim -u statusline_test.vimrc -i NONE -N`
   - 'OK: error catched!' がstatuslineに表示される
2. `:redrawstatus`
   - 'OK: error catched!' がstatuslineに表示される
### ~~関連問題~~
- ~~actual: statuslineでVimのエラーが発生し，キャッチもされないと， silentlyにstatuslineがdisableされる~~
- ~~個人的な? expected: statuslineでVimのエラーが発生すると，エラーメッセージを表示した上でstatuslineがdisableされる~~

補足: statuslineがdisableされるのはstatuslineのredrawが起こるごとにエラーが出るとうっとおしいからdisableしているようです．
### 修正パッチ案

https://github.com/haya14busa/vim/commit/0cd2c2f736f8c9c4e75ec96d6b8fde53a71c6374

ちょっと詳しくなくて付け焼き刃の調査をしながらの修正です．
なのでこれでいいのかよくわかりませんが，僕が意図した挙動になりました．
## Vimのバージョン

7.4.1386
## OSの種類
-   ArchLinux

どのOSでも再現するはず
#### その他
- 関連 issues
  - https://github.com/lambdalisue/vim-gita/pull/85#issuecomment-202053436
  - https://github.com/vim-jp/vital.vim/pull/415#issuecomment-202070634

両者ともログ長いし読む必要はないですが，上記issueで問題が発覚し，silentlyにstatuslineがdisableされるせいで異常にデバッグが難しかったです．

問題や該当コードを見つけたのは @lambdalisue さんや [watiko](http://lingr.com/room/vim/archives/2016/03/29#message-23172726) さんです．

cc @lambdalisue

**Comment by h-east** [comment]
> 補足: statuslineがdisableされるのはstatuslineのredrawが起こるごとにエラーが出るとうっとおしいからdisableしているようです．

一応、ドキュメントに書いてあります。
`:h 'statusline'`の20行下くらい。

```
    オプションを評価している間にエラーが発生すると、それ以降のエラーを避け
    るためにオプションに空が設定される。そうしないと画面更新がループに陥っ
    てしまう。
```

**Comment by h-east** [comment]
本題とあんまり関係ないけど、LANGで挙動が違いますね。

``` sh
$ LANG=ja_JP.UTF-8 vim -Nu statusline_test.vimrc
```

起動直後に既に'statusline'が空。だからステータスラインに`[無名]`と表示される。
Vim内部のmulti-byte時の処理の中でステータスライン描画処理が呼ばれていると思われる。

## 

``` sh
$ LANG=C vim -Nu statusline_test.vimrc
```

@haya14busa さん報告の動作。

**Comment by mattn** [comment]
did_emsg も前のパッチと同様に saved_did_emsg で退避すべきです。

**Comment by haya14busa** [comment]
> 一応、ドキュメントに書いてあります。

確かに書いてありますね．エラーを出すかどうかについては言及してないけど黙って空に設定するところまで意図していた場合はこの修正ではだめそうですね．どうなんだろうか...

退避なるほど．修正しました．

``` patch
diff --git a/src/screen.c b/src/screen.c
index 9d854a2..edd1dea 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -6779,7 +6779,7 @@ win_redr_status(win_T *wp)
 redraw_custom_statusline(win_T *wp)
 {
     static int     entered = FALSE;
-    int            save_called_emsg = called_emsg;
+    int            saved_did_emsg = did_emsg;

     /* When called recursively return.  This can happen when the statusline
      * contains an expression that triggers a redraw. */
@@ -6787,9 +6787,9 @@ redraw_custom_statusline(win_T *wp)
    return;
     entered = TRUE;

-    called_emsg = FALSE;
+    did_emsg = FALSE;
     win_redr_custom(wp, FALSE);
-    if (called_emsg)
+    if (did_emsg)
     {
    /* When there is an error disable the statusline, otherwise the
     * display is messed up with errors and a redraw triggers the problem
@@ -6798,7 +6798,7 @@ redraw_custom_statusline(win_T *wp)
        (char_u *)"", OPT_FREE | (*wp->w_p_stl != NUL
                    ? OPT_LOCAL : OPT_GLOBAL), SID_ERROR);
     }
-    called_emsg |= save_called_emsg;
+    did_emsg |= saved_did_emsg;
     entered = FALSE;
 }
 #endif
```

**Comment by lambdalisue** [comment]
`try/catch` が入ったのって何時なんだろう？もしも `statusline` が空っぽになるコードが追加されただいぶ後とかだったら「前はそういうの必要だったかもしれないけど今は `try/catch` あんだからそれを使ってない statusline のコンポーネント（ユーザーが書いてるものおよびプラグインの双方）が悪いだろJK」って言ってみるとか？

**Comment by mattn** [comment]
えと、try/catch してても駄目なんですよ。
本来「エラーがtry/catch無しの状態で投げられた」と判断すべきところが「エラーが発生したかどうか(try/catch有無関係なしに)」で判断しちゃってるというバグです。

**Comment by lambdalisue** [comment]
お、それがされてないのは無理だからだと勝手に思ってました。
内部のことは知らないのですが try/catch されたと判定できるのであればそちらの方が良いですね！

**Comment by haya14busa** [comment]
それを直してるつもりのパッチですね〜．(`did_emsg` で本当にいいか厳密に調べきれてませんが)

**Comment by mattn** [comment]
> did_emsg で本当にいいか厳密に調べきれてませんが

did_emsg でいいですよ。

**Comment by haya14busa** [comment]
おお，よかったです:)

**Comment by mattn** [comment]
@haya14busa さん、テスト書けます？

**Comment by haya14busa** [comment]
これでよさそうならテスト書いてみます．(よく考えたらコードが正しいかどうかに関係なくテストかけましたね)

なんかわからなかったら聞くかも知れないですが，その時はよろしくお願いします :bow:

**Comment by haya14busa** [comment]
テストも足してみました https://github.com/vim/vim/compare/master...haya14busa:fix-redrawstatusline-for-catched-error

**Comment by haya14busa** [comment]
キャッチされないエラーもsilentlyにdisableされるとか冒頭コメントに書いていましたが完全に僕の勘違いだったのでコメントを修正しました．問題は try-catchで囲まれたVimのエラーによってstatuslineがdisableされるというところだけです

**Comment by mattn** [comment]
eval('') はコメントではっきりエラーを起こすと書くか、eval('unknown expression') みたいにした方がいいかもです。

**Comment by haya14busa** [comment]
確かにそうですね．unknown expression にしておきました．https://github.com/vim/vim/commit/7564ec7b45bfbd37d0d7c1032e048633ebcd6393

**Comment by haya14busa** [comment]
投げました https://github.com/vim/vim/pull/729

**Comment by haya14busa** [comment]
patch 7.4.1711 https://github.com/vim/vim/commit/a742e084b677f76c67e9e52c4f9fb9ab24002e20

取り込まれました．ありがとうございましたっ :bird:
