### ISSUE TITLE
matchitでmarkdownの%が機能しない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#894]
## 質問・報告の内容

matchit を 使っていると markdown での % が機能しません。
正確には `[]`, `{}`, `()` のペアにマッチしなくなります。
## Vimのバージョン

7.4.1683 
## 使用している or 関係していそうなプラグイン

matchit.vim
## その他

[1649](https://github.com/vim/vim/commit/aedfcbe1e6c7df6edcd6756d7601bfdec7dd2087) の vimrc_example.vim で pkgadd matchit が ON になったので、
その影響で引っかかりやすくなりました。

ftplugin/markdown.vim が ftplugin/html.vim を使っていて、
その中で matchit 有効化時にHTML用の `b:match_words` を設定しています。
それが悪さをしてこの現象がおこっています。
本来であれば ftplugin/markdown.vim が `b:match_words` を追加設定してあげると良いのでしょう。

なお以下を `~/.vim/after/ftplugin/markdown.vim` に設定すれば matchit が正しく動くようになります。

``` vim
if exists("loaded_matchit")
  let b:match_words = '(:),{:},\[:],' . b:match_words
endif
```

**Comment by k-takata** [comment]
https://groups.google.com/d/topic/vim_dev/DIMDJ_6i6ig/discussion

**Comment by thinca** [comment]
タイトルの修正をお願いします。 (´・ω・｀)

**Comment by koron** [comment]
直したつもりでsave忘れてたw

**Comment by k-takata** [comment]
7.4.1832の後のruntime fileの更新で直ったと思われます。
https://github.com/vim/vim/commit/06d2d38ab7564e1f784b1058a4ef4580cd6d1810#diff-f87b2d8283f9205b5663ee98d1c44f8cL125
確認お願いします。

この修正だと、`s:last_words` の cache が有効活用されていない気もするのですが、ま、いいか？

**Comment by k-takata** [comment]
関連: #330, #331

直っているので閉じます。
