### ISSUE TITLE
MacVim 最新版で :Exp でファイルを開いたとき新規で開かれない

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#895]
## 質問・報告の内容

https://gist.github.com/voluntas/8af1b6b5892761ed970a8021d43c7dde より転載

動画を撮ってみました。 :exp で最初開いていないのは色々ファイルが見えてしまうからです。

:version とリリースタグの日付が 1 日づれているので、 :version の方でタイトルを切りました。
## 2016-02-20

**期待した動作をする**

https://dl.dropboxusercontent.com/u/89936/0220.mov

:e で開いたファイルの後に、変更を一切せずに :Exp でファイルを開くと新しいバッファとしてファイルが開かれる。

https://github.com/splhack/macvim-kaoriya/releases/tag/20160219
## 2016-03-26

**期待していない動作をする**

https://dl.dropboxusercontent.com/u/89936/0326.mov

:e で開いたファイルの後に、変更を一切せずに :Exp でファイルを開くと前に開いていたファイルのバッファが上書きされてしまう。

https://github.com/splhack/macvim-kaoriya/releases/tag/20160325
## Vimのバージョン

[7.4.1655 (2016-03-25)](https://github.com/splhack/macvim-kaoriya/releases/tag/20160325)
## OSの種類
-   MacOSX
## 使用している or 関係していそうなプラグイン

netrw.vim

**Comment by voluntas** [comment]
相談者です。.vim/ や .vimrc などを除いて動画と同様のファイルを二つ開くテストして見ました。
- 2016-02-20 では :buffers でバッファは二つありました。
- 2016-03-26 では :buffers のバッファは上書きされたようで一つになりました。

**Comment by mattn** [comment]
動画、逆じゃないです？

**Comment by mattn** [comment]
上書きされるとおっしゃる動画の方だけ `:Explorer` の前で一瞬 bnext コマンドが見えますが、これは @voluntas さんがタイプしてたり autocmd が実行されてたりしますか？

**Comment by k-takata** [comment]
netrwは、作者のサイトから最新版を入手して、どうなるか試してみるとよいでしょう。
http://www.drchip.org/astronaut/vim/index.html#NETRW

**Comment by koron** [comment]
わかった。setl nobl が増えてた。今diffのURL探します。

**Comment by heavenshell** [comment]
netrw v155 で再現しましたが、最新版の v156b では再現しないようです。

**Comment by koron** [comment]
https://github.com/vim/vim/blame/e0fa3742ead676a3074a10edadbc955e1a89153d/runtime/autoload/netrw.vim#L11396-L11398

**Comment by koron** [comment]
こいつのせいです。バッファは消えてない&netrw自体は新しいバッファで開かれていますが、
古い方のバッファに `nobl` が設定されちゃうので、`:ls` などには出なくなり、
statusline に表示されなくなって「新しいバッファで開かれていない」と誤解されたのでしょう。

**Comment by koron** [comment]
@voluntas 一応、`:set stl?` の設定内容を転記しておいてもらえますか?

**Comment by voluntas** [comment]
@koron `:set stl?` を実行しました。

![2016-04-01 9 14 02](https://cloud.githubusercontent.com/assets/15551/14194504/21c699dc-f7ea-11e5-8e9b-9080a0428ddf.png)

朝起きたら解決しているようでびっくりです ... 。

@mattn bnext は、これを読んでも次のバッファに行かないというアピールのつもりで入れた次第でした。すみません、わかりにくくて。

**Comment by koron** [comment]
@voluntas ありがとうございます。

ただこの設定だけでは動画のようにステータスラインに全バッファ名はでない気がするのですが…
なにか関係しそうなプラグインは使っていますか?

**Comment by voluntas** [comment]
@koron 解答が明後日だったらすみません、 buftabs.vim を使っています。
それ以外は使っていないと思います。

```
" buftabs.vim
let g:buftabs_only_basename=1
let g:buftabs_in_statusline=1
let g:buftabs_active_highlight_group="Visual"
set statusline=%=\ [%{(&fenc!=''?&fenc:&enc)}/%{&ff}]\[%Y]\[%04l,%04v][%p%%]
set laststatus=2
```

**Comment by koron** [comment]
https://github.com/vim-scripts/buftabs/blob/master/plugin/buftabs.vim#L230

ここの条件で `buflisted()` を見ているので、 `nobl` だと表示されなくなってしまう。

**Comment by koron** [comment]
http://www.drchip.org/astronaut/vim/index.html#NETRW ＜ここから v156c (ページには156bとあるが、中身は156cだった)をDLして確認したところ、以下のようになってた。

``` vim
  " Want the old buffer to be unlisted.
  " COMBAK: this causes a problem, see P43
"  setl nobl
```

`P43` ってどこだよという思いはあるものの、そういうことらしい。
(本来なら doc/pi_netrw.txt に書かれていそうだけど、見当たらなかった)

@voluntas というわけで以下のどちらかで対応してみてください。
- netrwのv156c を使う
- [該当箇所](https://github.com/vim/vim/blame/e0fa3742ead676a3074a10edadbc955e1a89153d/runtime/autoload/netrw.vim#L11396-L11398) の `set nobl` をコメントアウトして使う。
  
  以下の様な操作で書き換えはできるはずです。
  
  ```
  :e $VIMRUNTIME/autoload/netrw.vim
  11398G
  I"<ESC>:w<Enter>
  ```
  
  私の方では、このスクリプトはテストしていませんので、適宜読み替えてください。

**Comment by voluntas** [comment]
@koron いろいろとありがとうございます。まずは最新版の netrw v156c を使ってみようとおもいます。

**Comment by voluntas** [comment]
@koron setl nobl をコメントアウトして確認しました。 (netrw のインストール方法がわからず ... )

@koron @mattn @k-takata @heavenshell 皆様ありがとうございました、これで幸せな vim 生活がまた後れそうです。

こちら閉じて頂いて問題ありません、本当にありがとうございました。

**Comment by koron** [comment]
最後のまとめ。

netrw.vim の「既存バッファに `set nobl` してしまう」という問題でした。将来の版では正式に修正されると思いますが、簡単な修正だったので当事者の手元で直してもらうことで対応しました。

ラベルは xlose/fixed と xlose/wontfix で迷いましたが、とりあえずということで前者にしました。後者だと、後で掘り返す場合が結構ありますので。

あと個人的には netrw 系には深く関わりたくないなとw

以上。

**Comment by k-takata** [comment]
> (netrw のインストール方法がわからず ... )

vimball形式になっています。*.vba (あるいは *.vba.gz) をVimで開いて、`:so %`してください。
詳細は、`:help vimball`を参照してください。

**Comment by h-east** [comment]
お疲れ様でした。

全platformでの問題だったので`related/mac`のラベルは外しますね。

**Comment by k-takata** [comment]
> あと個人的には netrw 系には深く関わりたくないなとw

#276 がありましたねｗ

**Comment by voluntas** [comment]
@k-takata 情報、ありがとうございます！
