### ISSUE TITLE
CTRL-W gfでE325が発生した時、終了・中止した時に新しいタブを作るべきか

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#897]
## 質問・報告の内容

関連 [E325で終了・中止したのに現在開いているファイルが二重で開く](https://teratail.com/questions/31454)

ノーマルモードでCTRL-W gfでカーソル下のファイル名を開こうとすると、そのファイルが既に別のターミナル上のVimで開かれていた場合、E325が発生して下記5つの選択肢を入力を求められます。
- 読込専用で開く([O])
- とにかく編集する((E))
- 復活させる((R))
- 終了する((Q))
- 中止する((A)):

qかaを押して終了または中止にすると、現在のバッファが新しいタブに開いてしまいます。
この動作が仕様なのか分かりません。

ファイルが存在しない場合は新しいタブが開かれないので、終了・中止した場合でも新しいタブで現在のバッファが開かれない仕様のほうがいいと思いました。
## Vimのバージョン

7.4
適用済パッチ: 1-1707

( `:version` で確認できます)
## OSの種類
-   Linux
## OSのディストリ

Debian jessie
## OSのバージョン

8.4
## 使用している or 関係していそうなプラグイン

なし
## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by h-east** [comment]
`CTRL-W gf`の処理部分です。
do_window() in window.c

``` c
 467 #ifdef FEAT_SEARCHPATH
 468 /* edit file name under cursor in a new window */
 469     case 'f':
 470     case 'F':
 471     case Ctrl_F:
 472 wingotofile:
 473                 CHECK_CMDWIN
 474
 475                 ptr = grab_file_name(Prenum1, &lnum);
 476                 if (ptr != NULL)
 477                 {
 478 # ifdef FEAT_GUI
 479                     need_mouse_correct = TRUE;
 480 # endif
 481                     setpcmark();
 482                     if (win_split(0, 0) == OK)
 483                     {
 484                         RESET_BINDING(curwin);
 485                         (void)do_ecmd(0, ptr, NULL, NULL, ECMD_LASTL,
 486                                                            ECMD_HIDE, NULL);
 487                         if (nchar == 'F' && lnum >= 0)
 488                         {
 489                             curwin->w_cursor.lnum = lnum;
 490                             check_cursor_lnum();
 491                             beginline(BL_SOL | BL_FIX);
 492                         }
 493                     }
 494                     vim_free(ptr);
 495                 }
 496                 break;
 497 #endif
```

482行の`win_split()`でtabpageを開いて、485行の`do_ecmd()`でファイルを読み込んでいます。
`do_ecmd()`の戻り値を見るようにすればファイルを開いたかどうかが分かります。なので`win_split()`呼び出し前にカレントtabpage&カレントwindowを覚えておき、`do_ecmd()`が`FAIL`の場合に以下の処理をおこなえば実現可能かと思います。
- カレントtabpage&カレントwindowを閉じる。
- 覚えていたカレントtabpage&カレントwindowに移動する。

**Comment by norio13** [comment]
一度もVimのソースコードをいじったことがなかったので、良い機会だと思ってチャレンジしてみます。
教えて頂いた手順に沿ってやってみます。
h-eastさん、ありがとうございます。

**Comment by norio13** [comment]
大分遅くなりましたがpatch書けたので投稿します。
make installまで出来てます。

``` diff
diff --git a/src/window.c b/src/window.c
index 2dc2554..c221ebe 100644
--- a/src/window.c
+++ b/src/window.c
@@ -479,12 +479,17 @@ wingotofile:
                    need_mouse_correct = TRUE;
 # endif
                    setpcmark();
+                   tabpage_T   *oldtab = curtab;
+                   win_T       *oldwin = curwin;
                    if (win_split(0, 0) == OK)
                    {
                        RESET_BINDING(curwin);
-                       (void)do_ecmd(0, ptr, NULL, NULL, ECMD_LASTL,
-                                                          ECMD_HIDE, NULL);
-                       if (nchar == 'F' && lnum >= 0)
+                       if (do_ecmd(0, ptr, NULL, NULL, ECMD_LASTL,
+                                                          ECMD_HIDE, NULL) == FAIL) {
+                           win_close(curwin, FALSE);
+                           goto_tabpage_win(oldtab, oldwin);
+                       }
+                       else if (nchar == 'F' && lnum >= 0)
                        {
                            curwin->w_cursor.lnum = lnum;
                            check_cursor_lnum();
```

**Comment by h-east** [comment]
@norio13 :+1: いい感じだと思います。
コーディングスタイルについていくつか指摘させて下さい。
window.c
- L482-483: 変数宣言代入はブロックの先頭(L477)に移動した方が良いです。(`:help style-compiler`)
- L488: `{`は改行して次の行に書きます。(`:help style-examples`)
- インデントがすべてスペースになっています。元はwindow.cの1行目に書かれているとおり`set ts=8 sts=4`ですので合わせて下さい。(issueに貼り付ける時に意図的に置き換えた?)

一度`:help coding-style`に目を通しておくと良いかもです。

残作業はこんな感じでしょうか？
- [ ] testの追加
- [ ] ドキュメントの修正(必要であれば)
- [ ] vim_devへpatch送付(もしくはGitHub経由でPR)

norio13さんどこまでされます？最後までやられます？

**Comment by norio13** [comment]
ご指摘頂いた箇所を修正しました。
インデントの件は、ここにpatchを貼り付けるとタブがスペースに変換されてしまいました。
どうしたら変換されないように表示されるか分からないのでgistの方に載せます。すみません。
[https://gist.github.com/norio13/726c336e3fc770fe0a23250c803cf6d4
](https://gist.github.com/norio13/726c336e3fc770fe0a23250c803cf6d4)

中途半端で申し訳ないのですが、私にはハードルが高くて最後まで出来ません。
大変恐縮ですが続きをh-eastさんにお願いできないでしょうか。

**Comment by h-east** [comment]
@norio13 修正ありがとうございます。
後は私の方で引き取らせていただきます。
あと、patch author名を教えて下さい。少し前まではハンドル名的な名前だとBram氏に「Real name教えて欲しい」と聞かれてました。最近は緩くなりましたけど。

**Comment by norio13** [comment]
@h-east 快くお引き受けくださり、ありがとうございます。
名前はtakagi norioでお願い致します。
よろしくお願い致します。

**Comment by h-east** [comment]
testを追加してpatchをvim_devに送付しました。
https://groups.google.com/d/msg/vim_dev/INMAA-kIFyc/w9DA-19iBgAJ

**Comment by h-east** [comment]
早っ！速攻で取り込まれました。
patch 7.4.1956
https://github.com/vim/vim/commit/5d2ca0402954ff79b73d9c86cc16c8a6454b75a7

閉じます。
@norio13 さんIssue登録&patch作成ありがとうございました。
