### ISSUE TITLE
matchadd() の conceal がうまく適用されないケースがある

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#898]
## 質問・報告の内容

matchadd() の conceal がうまく適用されないケースがある．
### 再現手順

どちらも `:syn off` 状態という前提です． `:syn match .... conceal` があるかないかで挙動が変わります (追記: :`syntax match` でバッファの要素にマッチしていさえいれば conceal は関係なかった)
(さらに追記: 厳密には `syntax on`状態だろうがバッファにsyntaxにマッチしている要素がなければ再現する)
#### with_synmatch.vimrc

``` .vim
"
" -> __CONCEAL__ <-
set nocompatible
set conceallevel=2
call matchadd("Conceal", "CONCEAL", 10, -1, {'conceal': 'c'})
syntax match Search 'hoge' contains=NONE containedin=.* conceal cchar=s
```
1. `vim -u ./with_synmatch.vimrc -i NONE -N ./with_synmatch.vimrc`
   - 2行目の `CONCEAL` が表示されない (`-> ____ <-` こう見える)
2. `jk`
   - 1度カーソルをconcealの行に移動して戻ると 2行目の `CONCEAL` が `c` と表示される (`-> __c__ <-` こう見える)
#### without_synmatch.vimrc

``` .vim
"
" -> __CONCEAL__ <-
set nocompatible
set conceallevel=2
call matchadd("Conceal", "CONCEAL", 10, -1, {'conceal': 'c'})
```
1. `vim -u ./with_synmatch.vimrc -i NONE -N ./with_synmatch.vimrc`
   - 2行目の `CONCEAL` が表示されない (`-> ____ <-` こう見える)
2. `jk`
   - 1度カーソルをconcealの行に移動して戻っても 2行目の`CONCEAL` が表示されない (`-> ____ <-` こう見える)
### 個人的に期待する動作

すべてのケースで 2行目の `CONCEAL` が `c` と表示される．(`-> __c__ <-` こう見える)
## Vimのバージョン

7.4.1689
## OSの種類
-  Linux
## その他

関連パッチ:  [patch 7.4.792 · vim/vim@6561d52](https://github.com/vim/vim/commit/6561d52ecbe6e24d1b90403078cc8b76c53c42fc)

ちょっとコード見てみましたがよくわからなかった(つらい)

**Comment by h-east** [comment]
> 1度カーソルをconcealの行に移動して戻る～

先日の #893 の時も？？？と思ったんですが、
その動作で表示内容が変化するのはありえないと思います。 @haya14busa さんの環境が特殊なのかな？

以下の結果を教えてもらえますか？

``` sh
$ env| grep "LANG\|TERM"
$ cat /etc/os-release | grep PRETTY_NAME
```

**Comment by haya14busa** [comment]
> その動作で表示内容が変化するのはありえないと思います。 @haya14busa さんの環境が特殊なのかな？

はい．実際この挙動はオカシイやろ...と思ったんですが100%再現してるので報告しました．

![conceal](https://cloud.githubusercontent.com/assets/3797062/14286105/e88a770e-fb88-11e5-866a-1912fd96e941.gif)

ただ，そういわれて環境で何かあるかなぁと考えたら tmux を使っていて，

> 1度カーソルをconcealの行に移動して戻ると 2行目の CONCEAL が c と表示される (-> **c** <- こう見える)

という動作の原因はこれでした．tmux なしだと最初から 'c' が見えました．

```
$ env| grep "LANG\|TERM"
TERM=screen-256color
LANG=en_US.UTF-8
$ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Manjaro Linux"
$ tmux -V
tmux 2.1
```

tmux なしでも `:syn match .... conceal`がない場合の挙動は同じでした．

**Comment by haya14busa** [comment]
(少なくとも僕の環境で) ほぼ同じ問題が tmux なしで再現できました．

#### without_synmatch2.vimrc

``` vim
"
" -> __CONCEAL__ <-
" -> ___DUMMY___ <-
" -> __CONCEAL__ <-
set nocompatible
set conceallevel=2
call matchadd("Conceal", "CONCEAL", 10, -1, {'conceal': 'c'})
```

1) `vim -u ./without_synmatch2.vimrc -i NONE -N ./without_synmatch2.vimrc`

2-4 行目が

```
" -> ____ <-
" -> ___DUMMY___ <-
" -> ____ <-
```

上記のようにみえる

2) `:syntax match Search 'DUMMY'`

2-4 行目が

```
" -> ____ <-
" -> ___DUMMY___ <-
" -> __c__ <-
```

上記のようにみえる

3) `jk`

(2行目を何かしらの方法でredrawさせる．`jk` はそのひとつ．`:mes`で2行目を一旦見えなくするとかでも可能．なお`:redraw`は効かない)

2-4 行目が

```
" -> __c__ <-
" -> ___DUMMY___ <-
" -> __c__ <-
```

上記のようにみえる

これは手元で試した挙動からの推測ですが，ほかのsyntax定義にマッチする要素があり，かつ，そのほかのsyntaxが適用された後にredraw的なことをされないと `matchadd()`のconcealで指定した`cchar`が現れないというふうになっている気がします．

`:syntax match Search 'xxx'`といった，バッファの要素にマッチしないsyntaxを定義しても`c`に見えるはずの`CONCEAL`が見えない状態になっています．

**Comment by haya14busa** [comment]
なお，これは問題ではなく単なる対比ですが，`:syntax`を使って conceal を定義した場合は
意図したとおりに`__CONCEAL__`が`__c__`に見えます．

#### synconceal.vimrc

``` vim
"
" -> __CONCEAL__ <-
set nocompatible
set conceallevel=2
syntax match Conceal 'CONCEAL' contains=NONE containedin=.* conceal cchar=c
```
1. `vim -u ./synconceal.vimrc -i NONE -N ./synconceal.vimrc`

この時点で

```
"
" -> __c__ <-
```

のように見える(この挙動を`matchadd()`でも期待してる)

**Comment by h-east** [comment]
了解です。
再現環境は出来るだけ単純にすべきなので`tmux`等は未使用でお願いします。

本題と関係ないですけども、各種履歴が問題となる場合以外は`-i NONE`不要です。
本題は明日(今日!?)確認させていただきます。ありがとうございます。

**Comment by haya14busa** [comment]
了解です．ありがとうございますっ!

**Comment by haya14busa** [comment]
修正内容は `syntax_seqnr` を無理やり弄るダメそうなものになってますが，
ある程度問題の原因がわかったのと修正案です．

``` patch
diff --git a/src/screen.c b/src/screen.c
index 9d854a2..6cc72ab 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -4910,7 +4910,18 @@ win_line(
                    && vim_strchr(wp->w_p_cocu, 'v') == NULL))
        {
        char_attr = conceal_attr;
-       if (prev_syntax_id != syntax_seqnr
+       // PROBLEM: When trying to show cchar by matchadd(),
+       // prev_syntax_id and syntax_seqnr might be 0 with :syntax off.
+       // When trying to show cchar by :syntax match, it's no problem because
+       // syntax_seqnr is not 0.
+       // To support showing cchar by matchadd(), change
+       // syntax_seqnr value to non-zero.
+       // XXX: better solution?
+       if (has_match_conc && syntax_seqnr == 0) {
+           syntax_seqnr = -1;
+       }
+
+       if ((prev_syntax_id != syntax_seqnr)
            && (syn_get_sub_char() != NUL || match_conc
                             || wp->w_p_cole == 1)
            && wp->w_p_cole != 3)
```

branch: https://github.com/vim/vim/compare/master...haya14busa:fix-matchadd-conceal

`matchadd()` の `conceal` は`syntax` と関係なく有効になるように実装されてそうなのですが，
(例えばこの行 https://github.com/vim/vim/commit/6561d52ecbe6e24d1b90403078cc8b76c53c42fc#diff-ceb2e2231c5d45523135ca0cfc492792R4895)
完璧ではなかったようです．

syntax が適用されてる要素がバッファにないときは `syntax_seqnr` が0になってしまっており，
本来なら conceal する対象の最初の文字は `cchar` に置き換えるべきところが，
`prev_syntax_id` と `syntax_seqnr` が両方0なせいで条件にマッチせず `cchar` が表示されなかったのが問題でした．

もし他にsyntax が適用されてる要素がバッファにあれば`syntax_seqnr` がnon-zeroになるはずなので，大部分のケースでは問題にならなかったようです．

`prev_syntax_id != syntax_seqnr` の部分は要するに conceal で cchar に対象を置き換える際に，最初の文字以外はスキップするためのものです．
ですので，なんとかそのロジックを他の方法で実現できれば `syntax_seqnr` に -1 代入するなんていう修正は避けれるはずなのですが，
僕の実装力では今の所うまく行きませんでした...(フラグ作ったりして試したけどダメだった)

1つのファイルで syntax なし，syntax 追加直後，さらに redraw 後の3つを確認できる 最小 Vim script も作ったので貼っておきます．
テストは似た感じで`screenchar()`を使えば書ける気がしますがまだやってないです．

#### matchadd_conceal.vim

``` vim
"
" -> __CONCEAL__ <- " -> __CONCEAL__ <- " -> __CONCEAL__ <-
" -> ___DUMMY___ <-
" -> __CONCEAL__ <- " -> __CONCEAL__ <- " -> __CONCEAL__ <-
set nocompatible
syntax off
set conceallevel=2
call matchadd("Conceal", "CONCEAL", 10, -1, {'conceal': 'c'})
echo 'start!'

function! ScreenBuffer(lnum, cnum) abort
  redraw
  let lines = []
  for l in range(1, a:lnum)
    let line = []
    for c in range(1, a:cnum)
      let line += [nr2char(screenchar(l, c))]
    endfor
    let lines += [join(line, '')]
  endfor
  for l in lines
    echom l
  endfor
endfunction
autocmd BufReadPost *
\   |   :echom '=================='
\   |   :call ScreenBuffer(4, 80)
\   |   :echom '=================='
\   |   :syntax match Search 'DUMMY'
\   |   :call ScreenBuffer(4, 80)
\   |   :echom '=================='
\   |   :1
\   |   :redraw
\   |   :0
\   |   :redraw
\   |   :call ScreenBuffer(4, 80)
\   |   :redraw
\   |   :mes
```

#### 使い方

```
./vim -u ./matchadd_conceal.vim -N ./matchadd_conceal.vim
```

##### Expect Message (修正パッチ適用するとこの挙動になるはず)

とにかく `CONCEAL` はぜんぶ `c`に見える

```
==================
"
" -> __c__ <- " -> __c__ <- " -> __c__ <-
" -> ___DUMMY___ <-
" -> __c__ <- " -> __c__ <- " -> __c__ <-
==================
"
" -> __c__ <- " -> __c__ <- " -> __c__ <-
" -> ___DUMMY___ <-
" -> __c__ <- " -> __c__ <- " -> __c__ <-
==================
"
" -> __c__ <- " -> __c__ <- " -> __c__ <-
" -> ___DUMMY___ <-
" -> __c__ <- " -> __c__ <- " -> __c__ <-
Press ENTER or type command to continue
```

##### Actual Message (現状のVim)

`CONCEAL` が条件によって `c`に見えず消えている

```
==================
"
" -> ____ <- " -> ____ <- " -> ____ <-
" -> ___DUMMY___ <-
" -> ____ <- " -> ____ <- " -> ____ <-
==================
"
" -> ____ <- " -> ____ <- " -> ____ <-
" -> ___DUMMY___ <-
" -> __c__ <- " -> __c__ <- " -> __c__ <-
==================
"
" -> __c__ <- " -> __c__ <- " -> __c__ <-
" -> ___DUMMY___ <-
" -> __c__ <- " -> __c__ <- " -> __c__ <-
```

**Comment by k-takata** [comment]
内容を把握していませんが、とりあえずコーディングスタイルについてだけ。
- C++ スタイルのコメントは使わない。
- 基本的に `{`, `}` が不要なときには使わない。（個人的には、このスタイルはバグの元になりうるので嫌いですが。）
- `{` を使う場合は、改行して次の行から。

**Comment by haya14busa** [comment]
ありがとうございます．修正しておきます．

**Comment by ichizok** [comment]
tmux の有無で挙動が違う件は、Vim の初期化シーケンスが関係していると思われます。
1. ambiguous character width を調べるために端末に DSR-CPR request を投げる
   https://github.com/vim/vim/blob/54f1b7a/src/term.c#L3221
2. 端末から DSR-CPR response が返ると、画面を redraw する
   https://github.com/vim/vim/blob/54f1b7a/src/term.c#L4148
3. response がちょうどいいタイミング (最初にファイル内容を描画している間?) に来ると、画面描画後にさらに redraw が走るため、`__c__` が表示される

`TERM=screen` (`screen-256color`) などの時は DSR-CPR request を投げない (`t_u7` が空) ので、3 の redraw が発生しません。tmux 使用時はこの状況です。
tmux でも `TERM=xterm` にするとか、`t_u7` を設定する (`set t_u7=^[[6n`) と request が投げられ、環境によっては `__c__` が表示されます。
- OS X の tmux (on Terminal.app, iTerm) では表示される
- Linux の tmux は response が早すぎる? (request 直後に来る) ため、表示されない

**Comment by ichizok** [comment]
すみません、2について少し訂正します。
DSR-CPR response の結果 `ambiwidth` がデフォルト値から変更された場合に redraw されます。

**Comment by haya14busa** [comment]
ベターな修正は置いておいてテスト足しました． 

diff: https://github.com/vim/vim/compare/master...haya14busa:fix-matchadd-conceal

travis でテスト追加コミットでテストが落ちて，修正コミットで直ることを確認しました https://github.com/haya14busa/vim/pull/1

**Comment by haya14busa** [comment]
なお redraw の件は，根本の他のsyntax定義にマッチする要素がない場合にccharが見えないという問題を解決すれば，redrawする前から直るので問題なくなります．

**Comment by h-east** [comment]
src/testdir/test_matchadd_conceal.vim の Test_matchadd_conceal()関数冒頭のconceal feature availableチェックはそのファイルの先頭に書いた方が良いと思いました。

``` vim
if !has('conceal')
  finish
endif
```

テストファイル名がtest_matchadd.vimで他にmatchaddのテストを追加していく方針なら今のままで良いと思います。
纏めると、テストファイル名を変更する、または、Conceal feature availableチェックをファイル冒頭に移動する is betterでございます。

**Comment by h-east** [comment]
あー、oldスタイルのテスト`test_match_conceal.in`が既にあるんですね。あと、`test63.in`。
欲を言えば、`test_match_conceal.in`をnewスタイルテストにコンバートして、そこに今回のテストを足すとmore betterですね。

**Comment by haya14busa** [comment]
`test_match_conceal.in` があるのそういえばここで相談してなかった...
~~old 形式ぱっとみてめんどくさそう...と思って~~ まずは new style足せばええやろという考えで足したんですが，`test_match_conceal.in` をconvert してみます．`test63.in` までやると大変そうなのでとりあえずそのままでいきたさ

**Comment by ichizok** [comment]
> 最初の文字以外はスキップ

`v == shl->startcol` を確認すればいけそう
https://gist.github.com/ichizok/d4c615a32217aabee24a5be4e3b207ef

**Comment by haya14busa** [comment]
@ichizok さん++

ichizok さんのパッチ試しましたが，ちゃんと問題直りましたし，自分のブランチに取り込んでみたんですがテストも通りました :tada:
よさそうすぎる．

あと，`test_match_conceal.in` を `test_matchadd_conceal.vim` にコンバートしてそこにテスト足す形式にしました．
100%そのままコンバートではなく，`:syntax on` いらないところで`:syntax on`しないようにしたので，なんならテスト追加しなくてもいまのupstream の HEADのVimでテストしたら落ちたりするはず．
あとold styleの方にあった `set term` をnewの方ではしてないけど travis と appveyor でちゃんとテスト通ってしまった．
`set term` してないのは単純にいるのかな?という疑問と `test_alot.vim` に対応したテストにしようという理由だけなので，`test_alot.vim`に入れない形式にすれば`set term`もできそう．

diff: https://github.com/vim/vim/compare/master...haya14busa:fix-matchadd-conceal

old style のテストを new style にするの思ったより大変だったし，そもそも `matchadd()`の conceal は`test_match_conceal.in`でテストされてたので `test63.in` (`matchadd()`のテストが含まれる) はとりえあえずこのままで :bow:

**Comment by h-east** [comment]
@haya14busa :+1: :+1: 

> old style のテストを new style にするの思ったより大変だったし

お疲れ様でした。
`test_matchadd_conceal.vim`は無理に`test_alot.vim`に属させなくても良いと思います。

**Comment by haya14busa** [comment]
`set term` して`test_alot.vim`から外しました．(冷静に考えると `:so mbyte.vim` してる時点でVimの状態変えちゃってそう)

**Comment by haya14busa** [comment]
テストの追加と修正は僕のブランチにあるので，修正 @ichizok  さんクレジットでvim-dev に僕が投げてもいいでしょうか? https://github.com/vim/vim/compare/master...haya14busa:fix-matchadd-conceal

diff: https://github.com/vim/vim/compare/master...haya14busa:fix-matchadd-conceal

**Comment by k-takata** [comment]
new style testだと、`so mbyte.vim` はいらないはずです。（あえてチェックするなら、`has('multi_byte')`でしょうか。）
`Test_match_using_multibyte_conceal_char()` でencがutf-8かどうかチェックしていますが、Windowsだとこの関数がスキップされてしまうことになるので、いっそ`set enc=utf-8`してしまってもよい気がします。（もともとがそうだったのかもしれませんが。）

**Comment by ichizok** [comment]
@haya14busa おねがいします

**Comment by haya14busa** [comment]
なげました https://github.com/vim/vim/pull/757

`so mbyte.vim` 消して，代わりのチェックが
`has('multi_byte')` だとwindowsでエラーでたので `has("multi_byte_encoding")` にしました．

**Comment by k-takata** [comment]
> has('multi_byte') だとwindowsでエラーでたので has("multi_byte_encoding") にしました．

それって、おそらくAppVeyor上ではこのテストはスキップされているということですよね。
テストスクリプトの中にUnicode文字が書いてあるので、正しく読めていないのだと思います。
日本語Windows環境で実行するとエラーになりそうな気がします。

test_regexp_utf8.vim みたいにして別ファイルに分けてしまった方がよいかもしれません。
（あるいは、test_visual.vim みたいに問答無用で、enc=utf-8 にしてしまうか？）

**Comment by haya14busa** [comment]
はい，スキップされるのでokということになるのだとおもいます．

https://github.com/vim/vim/pull/757/files#diff-c08698a0974753d5e241c7f8c218807bR250

テスト的にはそのマルチバイト関連のテスト1つだけスキップされるようになってるハズですが，別ファイルにしたほうがよいでしょうか..? いちおうメインは matchaddのconcealについてのテストなので，それがマルチバイト用のテストファイルに分散するとそれはそれでつらそう...?

あと `enc=utf-8`はしてた...というかいまも書かれてるんですが，その状態でappveyorでエラーになってたという意味でした．https://ci.appveyor.com/project/haya14busa/vim/build/27/job/42wi4ld782n2t4vv

...と思って test_visual.vim のほう見てみましたがそういえば `scriptencoding utf-8` の方は書いてなかった...

**Comment by k-takata** [comment]
> そういえば scriptencoding utf-8 の方は書いてなかった...

そうなんです。これが重要なんです。で、`scriptencoding utf-8` は `enc=utf-8` のあとに書かないといけないですし、特定の関数だけ utf-8 で実行するというのはやめた方がいいと思います。
そうなると、その関数だけconceal_utf8みたいな別ファイルに切り出すか、ファイル丸ごと utf-8 にしてしまうかのどちらかになるわけですが…まあ、後者でいいんじゃないですかね？

**Comment by k-takata** [comment]
ちょうど 7.4.1734 で utf-8 のテストを別ファイルに分離するというパッチがあったので、参考になりそうです。
https://groups.google.com/d/topic/vim_dev/voALhEC0Uc8/discussion
utf-8 なテストで、まとめて実行できるものは test_alot_utf8.vim にも登録すると良いようですね。

**Comment by haya14busa** [comment]
おーちょうどよさそうですね！そっちに移動させてみます

**Comment by haya14busa** [comment]
なおしました! https://github.com/vim/vim/pull/757/commits/c50276bdf6c3f9e11b88242c45ff4057e69c3c04

**Comment by haya14busa** [comment]
取り込まれましたっ :tada: https://github.com/vim/vim/commit/4d585022023b96f6507e8cae5ed8fc8d926f5140

ありがとうございました．

**Comment by k-takata** [comment]
> 取り込まれましたっ :tada: vim/vim@4d58502

あ、パッチ番号も書いておいた方がよいです。
7.4.1740 ですね。

**Comment by haya14busa** [comment]
ありがとうございます．今後気をつけます :bow:
