### ISSUE TITLE
job_startで起動したjobが変数に保存されている時にGCが走るとSEGV

### ISSUE THREAD

**Issue by miyakogi** [vim-jp/issues#899]
### 再現手順
1. `vim -u NONE -N --noplugin`
2. `:let g:a = job_start(['ls'])`
3. 少し待ってから、`:call garbagecollect()`
4. SEGV

`job_start`の返り値を変数に代入せずに`:call job_start`とするとSEGVは発生しませんでした。
## Vimのバージョン

7.4.1721
## OSの種類
-   Linux
## OSのディストリ

Kubuntu 15.10
## その他

7.4.1718で発生せず、7.4.1719以降で発生するようです。

**Comment by koron** [comment]
from [7.4.1719](https://github.com/vim/vim/commit/107e1eef1df3b786ad3ad49fbdb9e058649303b5)

> Problem:    Leaking memory when there is a cycle involving a job and a
>             partial.
> Solution:   Add a copyID to job and channel.  Set references in items referred
>             by them.  Go through all jobs and channels to find unreferenced
>             items.  Also, decrement reference counts when garbage collecting.

それっぽいw

**Comment by miyakogi** [comment]
すみません、プログラムが終了していなくてもSEGVしたのでタイトルを修正しました。

`job_start(['top'])`やPythonの無限ループするスクリプトでも発生しました。

**Comment by h-east** [comment]
@miyakogi 報告ありがとうございます:+1:

こちらでも再現出来ました。(CUI Vim 7.4.1721 on fedora 23)

``` sh
vim -Nu NONE -c "let g:a = job_start(['top'])"
```

で起動させて

``` vim
:call garbagecollect()
```

すると100% SEGVします。

**Comment by mattn** [comment]
https://groups.google.com/forum/#!topic/vim_dev/iQNehrwBoyw

直すのに時間かかりそうな気がしたのでひとまず投げました。

**Comment by ichizok** [comment]
`set_ref_in_item` で job と channel の copyID を更新してないのが原因？

**Comment by h-east** [comment]
@ichizok 鋭い:+1:

このpatchで落ちなくなったようです。

``` patch
diff --git a/src/eval.c b/src/eval.c
index 1c5a316..0c270b9 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -7326,6 +7326,7 @@ set_ref_in_item(

    if (job != NULL && job->jv_copyID != copyID)
    {
+       job->jv_copyID = copyID;
        if (job->jv_channel != NULL)
        {
        dtv.v_type = VAR_CHANNEL;
@@ -7350,6 +7351,7 @@ set_ref_in_item(

    if (ch != NULL && ch->ch_copyID != copyID)
    {
+       ch->ch_copyID = copyID;
        for (part = PART_SOCK; part <= PART_IN; ++part)
        {
        for (jq = ch->ch_part[part].ch_json_head.jq_next; jq != NULL;
```

**Comment by h-east** [comment]
vim_devに投げました。
https://groups.google.com/d/msg/vim_dev/iQNehrwBoyw/ujH8JBXsBAAJ

test書けそうなら書いて送ります。

**Comment by h-east** [comment]
> test書けそうなら書いて送ります。

test書けないなこりゃ。`timer_start()`や`feedkeys()`とかで頑張ってみたけどpatch適用前のtestでSEGV起こせない:fearful:
誰かtest書ける人お願いします:bow:

**Comment by k-takata** [comment]
> test書けないなこりゃ。

https://groups.google.com/d/msg/vim_dev/iQNehrwBoyw/b7HRNdvNBAAJ

> Reproducible.  Problem is that calling garbagecollect() doesn't work
> from a test, it's always postponed till later.  Will have to find a
> solution for that first.

Bramもできないと言っていますし、現状無理だと思います。

**Comment by ichizok** [comment]
tmux or screen を使ったテスト
https://github.com/vim/vim/compare/master...ichizok:fix-job-channel-gc.test

travis で fail 
https://travis-ci.org/ichizok/vim/builds/122231640

修正後は通ります
https://travis-ci.org/ichizok/vim/builds/122234349

**Comment by k-takata** [comment]
sugoi

**Comment by h-east** [comment]
patch 7.4.1722
https://github.com/vim/vim/commit/0239acb11fe4bfe9b525ea90b782759da5eb7704
