### ISSUE TITLE
enc設定と:makeなどの出力が文字化け

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#9]
Windowsでenc=utf-8かつ:compiler! msvcってな感じで:makeすると結果が文字化け。
外部プログラムがcp932で吐いているからだけど...
外部プログラムの出力結果にfencsの設定を反映させるべき?

**Comment by thinca** [comment]
参照するならどちらかというと tenc ではないでしょうか? fencs の方が柔軟かも知れませんが…。

**Comment by koron** [comment]
tenc設定しちゃうと、Vimから出力するときにも変換しちゃうので、
GUI周りが大変なことになります。
なのでtencは設定しない運用が好ましいです。

**Comment by Shougo** [comment]
`system()` とは違い、組込み機能はプログラムではどうしようもないので、
`:make` や `:!` のときは、Vim が enc=char で自動変換する運用のほうがよいでしょうね。
ただし、Windows 環境でも一部のコマンドは UTF-8 で出力するので問題はより厄介です。

**Comment by k-takata** [comment]
> tenc設定しちゃうと、Vimから出力するときにも変換しちゃうので、
> GUI周りが大変なことになります。

`gvim -N -u NONE -U NONE --cmd "set enc=utf-8 tenc=cp932"` で軽く動かしてみましたが、入力・表示ともに特に問題なさそうな気がしました。ただ、`:help 'tenc'`を見ると、

>   Win32 GUIでは 'termencoding' は入力された文字に対しては適用されない。
>   Win32では常にUnicode文字が渡されるからである。

となっていて、表示に適用されないとは書かれていないですね。

**Comment by k-takata** [comment]
todo.txt の2230行目付近に以下の項目が載っているのを見つけました。

```
Win32: When running ":make" and 'encoding' differs from the system locale, the
output should be converted.  Esp. when 'encoding' is "utf-8". (Yongwei Wu)
Should we use 'termencoding' for this?
```

'tenc' が良いかはともかく…。
この項目が記載された当時(いつ?)と異なっているのは、Win32 では、'tenc' がまったく使われなくなった点ですね。

**Comment by k-takata** [comment]
これも何とかしたいなあ。

`'commandencoding'`, `'cenc'` のようなオプションを新設したほうが良いのではないだろうか。
自動判別も行うなら、`'cencs'` もあったほうがよいかもしれないが、`'fencs'` で代用しても良いかもしれない。

`:make`, `:grep`, `:cfile` 等を実行すると、結果が一時ファイルにリダイレクトされ、それを quickfix.c / qf_get_next_file_line() で1行ずつ読み込みを行うようだ。
1行ずつとなると、自動判別は難しいか？

**Comment by mattn** [comment]
それとは別に system_enc() みたいなのがあっても良いかもしれないですね。コマンドにより入出力エンコーディングが異なったりするのでプログラマ側が指定できるのが良さそうな気がします。

**Comment by k-takata** [comment]
作ってみた。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/ffbb6c7c6299067c6c4e4ae48af52e53d30502e2/add-cmdencoding.patch?at=default

**Comment by k-takata** [comment]
投げた。
https://groups.google.com/d/topic/vim_dev/0258RWaKQvs/discussion

> それとは別に system_enc() みたいなのがあっても良いかもしれないですね。

現行の system() に引数を追加することができれば関数を増やさなくてもいいのですが、それは無理ですよね…。
（いや、第2引数に`0`を許可すれば、第3引数を追加することもできなくもないか…）

**Comment by k-takata** [comment]
system_enc() については #947 を作成しました。

**Comment by k-takata** [comment]
使用例に、`cenc=char` と書いておいたところ…、

> Why they "char" value?  It's using the system locale, wouldn't "system"
> be better?  Hmm, I don't see where "char" is recognized. 

iconvの`char`ってどこに文章化されていますか？ GNU iconv以外でも使えますか？

**Comment by k-takata** [comment]
https://www.gnu.org/software/libiconv/

> Locale dependent, in terms of \`char' or \`wchar_t' (with machine dependent
> endianness and alignment, and with OS and locale dependent semantics)
>      char, wchar_t
>      The empty encoding name "" is equivalent to "char": it denotes the locale
>      dependent character encoding.

GNU libiconvの説明は発見。他のiconvはどうなんだろう。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/0258RWaKQvs/WzMUcTmyBQAJ

> Looking at this patch, I think it also applies the conversion to
> ":cbuffer".  That should not happen.  Also ":cexpr".
> 
> In general, whether the conversion is needed depends on the command
> used.  E.g. for :grep and :make it might be different.  Not sure how to
> deal with that.

おや、":cbuffer" にも適用される？そのつもりはなかったのだが…。あとで確認。

**Comment by k-takata** [comment]
todo listed.

```
Patch to introduce 'cmdencoding'. (Ken Takata, Aug 18?)
Better help Aug 19.
Problem: applies to too many commands, such as :cbuffer.
Should there be a different value for :make and :grep?
    Win32: When running ":make" and 'encoding' differs from the system locale,
    the output should be converted.  Esp. when 'encoding' is "utf-8". (Yongwei
    Wu) Should we use 'termencoding' for this?
```

:cbuffer には適用されないと指摘したはずだが…。
:make と :grep で別の値を持たせるべきか？というのはどうすべきだろう。

**Comment by k-takata** [comment]
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d66cab898d7bb3c8b6ab681d5752d10c99a4e8fd/add-makeencoding.patch?at=default&fileviewer=file-view-default
`'makeencoding'`, `'grepencoding'`, `'errfileencoding'` を足すパッチ。
テストを書くのが難しい。

**Comment by k-takata** [comment]
global-local なオプションの値を参照するのって、もうちょっと簡単にできないのだろうか。

**Comment by koron** [comment]
> global-local なオプションの値を参照するのって、もうちょっと簡単にできないのだろうか。

これどういうことです?
Vim script からそれぞれの値へ明確に区別してアクセスしたいってことですか?

**Comment by koron** [comment]
> Vim script からそれぞれの値へ明確に区別してアクセスしたいってことですか?

`&g:xxx` と `&l:xxx` があるから、違うか…

**Comment by k-takata** [comment]
Cのコードの話です。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/d66cab898d7bb3c8b6ab681d5752d10c99a4e8fd/add-makeencoding.patch?at=default&fileviewer=file-view-default#add-makeencoding.patch-594
こことかで、ローカルの値が空だったらグローバルを見るというのは、関数とか用意されていないのかなと。

**Comment by koron** [comment]
src/options.c の `get_option_value()` ですかね?
Vim script の `&name` の実装に使われているハズなので。

**Comment by k-takata** [comment]
> src/options.c の get_option_value() ですかね?

なるほど。ただ今回の目的には大げさな感じがしました。

**Comment by koron** [comment]
オプションへの汎用的なアクセスはどうしても大げさにならざるを得ないでしょう。
名前=文字列ではなくenum値で指定するところまではいけると思いますが、同じようなものですし。
あと一部のオプションなら簡単なマクロを組めばいける思いますけど、
それはそれであると将来誤用でハマる人がでそう。

というあたりで、現状の方法が丁度良い、のではないでしょうか。

**Comment by k-takata** [comment]
> というあたりで、現状の方法が丁度良い、のではないでしょうか。

やっぱりそうなりますか。
vim_dev送付済みの最新パッチです。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/7a7e13b11921c3ae47c3f2d7c10fea474a74ed7d/add-makeencoding.patch?at=default&fileviewer=file-view-default
テストはまだない。

**Comment by k-takata** [comment]
4ヶ月ぶりにパッチ更新。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/4208dd3dfdd622d48b5b4ae4b7df161f2273fd98/add-makeencoding.patch?fileviewer=file-view-default
テストを追加しました。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/0258RWaKQvs/EjfapFuHBAAJ
投げました。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/0258RWaKQvs/5Z8pnnKGBQAJ
「やっぱ、オプション３つもいらねんじゃね？」
「ぐぬぬ」

**Comment by k-takata** [comment]
todo listed

```
Patch to add 'makeencoding', useful when the system encoding differs from
Vim's 'encoding' setting. (Ken Takata, 2017 Jan 6)
```

**Comment by k-takata** [comment]
8.0.0420
https://groups.google.com/d/topic/vim_dev/Qas9zWqqPKE/discussion

**Comment by k-takata** [comment]
関連パッチ: 8.0.0427
https://groups.google.com/d/topic/vim_dev/th9OA_lD_ng/discussion
