### ISSUE TITLE
go言語関数定義移動するとE926が発生します

### ISSUE THREAD

**Issue by umiyosh** [vim-jp/issues#901]
## 質問・報告の内容

任意のgo言語ファイルを開き vim-goを使ってgd(関数定義にjumpする)と以下のエラーが出力され,ジャンプ位置が関数定義箇所ではなく関数が定義されているgoファイルの先頭にカーソルが移動します。ctrl+iしてもう一度gdすると関数定義箇所にカーソルが移動します。

```
function go#def#Jump[22]..<SNR>195_godefJump の処理中にエラーが検出されました:
行   35:
E926: Current location list was changed
続けるにはENTERを押すかコマンドを入力してください
```

再現用のdotfilesを以下にまとめました。.vimrc*でvim起動のうえ任意のgo言語ファイルを開きgdすると再現すると思います。

https://github.com/umiyosh/dotfiles/tree/E926

なお,scrooloose/syntasticを読み込まないでvim-goのみを読み込んでvim起動しgdするとこの問題は発生しません
## Vimのバージョン

7.4.1655
## OSの種類
-   MacOSX
## OSのバージョン

OSX 10.10.5
## 使用している or 関係していそうなプラグイン

fatih/vim-go
scrooloose/syntastic

**Comment by mattn** [comment]
試してないので不確かな情報ですが、2つの Vim plugin が干渉しているんだと思います。vim-go はジャンプ先リストを作成しておいて ll コマンドでジャンプしてますが、syntastic が location list を書き換えてしまうので ll コマンドでエラーが発生していますね。おそらく

https://github.com/fatih/vim-go/blob/master/autoload/go/def.vim#L70-L102

のどこかで syntastic のイベントフックに反応してしまう何かが実行されたのだと追います。なんとなく `tab split` や `split` をトリガに syntastic が動いて location list を書き換えているんだと思います。
それぞれに noau を付ければなおるかもですが。

**Comment by h-east** [comment]
@umiyosh 登録ありがとうございます。

`E926`足されたのは`patch 7.4.1640`です。(It's my patch)
https://github.com/vim/vim/commit/ffec3c53496d49668669deabc0724ec78e2274fd

このpatchでquickfix/locationlistのファイル読み込み後にquickfix/locationlistが変化しているかチェックするようになりました。(SEGV対策)

以下が報告のあったスレッドです。
[bug] another use of free memory in quickfix code 
https://groups.google.com/d/topic/vim_dev/Sc1OSjl6lKY/discussion

うーん。Vim本体で(SEGV対策入ったままで)対応できるんだろうか。。

**Comment by mattn** [comment]
本体は関係ないと思います。
https://github.com/fatih/vim-go/blob/master/autoload/go/def.vim#L84
この lgetexpr を
https://github.com/fatih/vim-go/blob/master/autoload/go/def.vim#L105
の1行上あたりにもってくれば location list を書き換えられていたとしてもさらに上書きして治る気がします。

**Comment by mattn** [comment]
@umiyosh もしこれで治るようならば、vim-go に pull-request を投げて頂けますか。すみません syntastic を使ってないので。。。

**Comment by umiyosh** [comment]
@mattn @h-east コメントありがとうございます。上記了解ですー。家帰ったらvim-goいじって治るか試してみます。

**Comment by h-east** [comment]
syntasticを最新にすると直っている可能性あり。
https://github.com/scrooloose/syntastic/issues/1738

っちゅうかlcdさん、syntasticのコラボレーターやん。何故↑のリンクをvim_devのこのスレッドに貼らないのかな？
https://groups.google.com/forum/#!topic/vim_dev/t4ei24iwkiY

**Comment by umiyosh** [comment]
@h-east [d9814c5](https://github.com/scrooloose/syntastic/commit/d9814c5233931bb111fcae7cdc623a9f29495e5d)を試してみたですが,E926が起こりました > <
syntasticのissueに上げたほうが良いのですかね（ここってvim本体のissueを解決するところでしょうか。そのあたりわかってないです。。)

**Comment by umiyosh** [comment]
@mattn @mattn [98487a7](https://github.com/fatih/vim-go/blob/98487a7dbde2cffb426f9615293a2a3df63e02bf/autoload/go/def.vim)に対してlgetexpr上書きしてみましたが,E926が起こりました > <
うーんどうしたもんだろ。syntastic使うのやめよかな。。

**Comment by mattn** [comment]
明日僕も同じ環境で試してみます。

**Comment by umiyosh** [comment]
すいません,お手数おかけしますm(_ _)m

**Comment by mattn** [comment]
vim-go を最新にしたあと、以下のパッチをあてて確認してもらえますか。

``` diff
diff --git a/plugin/go.vim b/plugin/go.vim
index 8c57073..65a898b 100644
--- a/plugin/go.vim
+++ b/plugin/go.vim
@@ -169,8 +169,8 @@ augroup vim-go
     endif

     " initialize window-local godef stack
-   au BufReadPre,WinEnter *.go if !exists('w:go_stack') | let w:go_stack = [] | endif
-   au BufReadPre,WinEnter *.go if !exists('w:go_stack_level') | let w:go_stack_level = 0 | endif
+   au FileType go if !exists('w:go_stack') | let w:go_stack = [] | endif
+   au FileType go if !exists('w:go_stack_level') | let w:go_stack_level = 0 | endif
 augroup END


```

**Comment by umiyosh** [comment]
遅レスすみません。先週はちょっと時間が取れなくて上記の修正試せませんでした。すみませんm(__)m
この問題ですがvim-goの[24aeacc
](https://github.com/fatih/vim-go/commit/24aeacc43410136134672a2578912a91bb34edc8)で修正されたようです。最新版では問題なく動作してます。
いろいろ助言ありがとうございました。

**Comment by umiyosh** [comment]
このissueってこちらでcloseしても良いですか？

**Comment by mattn** [comment]
いえ、まったりやってもいいと思います。
