### ISSUE TITLE
DLL を指定するオプション (`pythondll` 等) が環境変数や tilde を展開しない

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#902]
## 質問・報告の内容

http://qiita.com/shuntaroy/items/b9e4092daa701899cf15#ポイント

```
luadll
perldll
pythonthreedll
pythondll
rubydll
tcldll
```

これらのオプションは環境変数や `~` を展開しませんが、できてもよさそうに思います。
(セキュリティ等の問題がある？)
もしくは help に展開しない旨を記述した方がよいかと。

`P_EXPAND` を `flags` に追加
https://gist.github.com/ichizok/63af51836a7192e18bd6c92609b875e2
## Vimのバージョン

7.4.907 以降

**Comment by mattn** [comment]
```
let &pythondll = expand("~/path/to/python.dll")
```

ではだめなんでしょうか？

**Comment by koron** [comment]
@ichizok こんなの vim_dev にパッチ送りつつ聞いちゃうのが速いと思いますけど、
なにか不安な点はありますか?

**Comment by koron** [comment]
ちなみにそれらは最近入ったわけで、あまり深いことは考えていないと思います。

**Comment by ichizok** [comment]
@mattn 同じように path を設定し expand するオプションが他にあるのに、これらは expand しないし help にも特に記載がないというのは不親切であろうという主張です。

expand する/しないの指針や前例とかあれば投げるまでもないと思いましたが、特にないなら投げてみます。

**Comment by ichizok** [comment]
https://groups.google.com/d/msg/vim_dev/d4ihqTA8QLU/zBx-yddUBQAJ
投げました。

**Comment by ichizok** [comment]
7.4.1756 で入りました。
https://github.com/vim/vim/commit/a6e42501424f6670fa864c739d2dc2eb764900b9

**Comment by h-east** [comment]
`test_expand_dllpath.vim`が実行されていなかったので修正patch投げました。
(ついでに `src`ディレクトリで `make test_expand_dllpath`出来るようにしました)

**Comment by ichizok** [comment]
`test_alot.vim` は `source test_expand_dllpath.vim` するので、
各 `call s:generate_test_if_exists()` で `Test_` 関数が作られるはずですが、実行されてませんか？
travis で patch 前のバージョンが fail することは確認してます。 
(`Test_expand_pythondll`, `Test_expand_pythonthreedll`)

`src/Makefile` は忘れてました、ありがとうございます。

**Comment by h-east** [comment]
私の環境はどのI/Fも有効になっていないので、`make test_expand_dllpath`すると

```
From test_expand_dllpath.vim:
Executed 0 test
```

と表示される訳か。そしてこの結果は想定通りってことですね。
失礼しました。vim_devにも取り消し投稿しました。
