### ISSUE TITLE
起動後最初の挿入モードで`complete()`関数での補完時に`noinsert`設定が無視される

### ISSUE THREAD

**Issue by miyakogi** [vim-jp/issues#903]
## 質問・報告の内容

Vim起動後、最初に挿入モードに入った時に`complete()`関数で補完が行われると`set completeopt=noinsert`が設定されていても補完候補が勝手に挿入されてしまいます。
二回目以降の補完では挿入されません。

初回だけなのでそれほど困りませんが、バグっぽい挙動なので一応報告させていただきます。

以下のコードを`a.vim`として保存し、`vim -u a.vim`で起動して挿入モードに入ると発生します。
（補完関数が呼ばれていることをわかりやすくするために、`menu`オプションも設定しています）

``` vim
set nocompatible
set completeopt=menu,noinsert

function! C(...) abort
  if mode() ==# 'i'
    call complete(col('.'), ['aa', 'aaa'])
  else
    call SetCompletion()
  endif
endfunction

function! SetCompletion() abort
  call timer_start(0, 'C')
endfunction

autocmd InsertEnter * call SetCompletion()
```

文章だとわかりにくいので動画を撮ってみました。
起動後に `i<Esc>o` と入力しています。

![out7](https://cloud.githubusercontent.com/assets/3213998/14488850/191f341e-01a5-11e6-9068-330431f41fc4.gif)

タイマーの待ち時間を1000などの長い値にしても発生しました。
## Vimのバージョン

7.4.1725
## OSの種類
-   Linux
## OSのディストリ

Kubuntu 15.10
## その他

外部プロセスで非同期に補完候補を求めて、結果を`complete`関数で表示するプラグインを書いていて気づきました。

**Comment by koron** [comment]
fixed typo: `colplete()` :arrow_right: `complete()` in tilte and body.

**Comment by ichizok** [comment]
`noinsert`, `noselect` の flag (`compl_no_insert`, `compl_no_select`) が設定される前に補完が発動するのが原因です。

https://github.com/vim/vim/blob/3780bb9/src/edit.c#L3676-L3681

`ins_compl_prep()` 内で `compl_no_insert`, `compl_no_select` が設定されます。

https://github.com/vim/vim/blob/3780bb9/src/edit.c#L868 (in `edit()`)
https://github.com/vim/vim/blob/3780bb9/src/edit.c#L2773 (in `set_completion()`)

`ins_compl_prep()` はこの2箇所で呼ばれますが、今回の状況では、この箇所に到達する前に補完が発動します。
具体的には、`edit()` の以下の箇所、`safe_vgetc()` の中で timer が発火します。

https://github.com/vim/vim/blob/3780bb9/src/edit.c#L781-L784

単純な解決としては、`compl_no_insert`, `compl_no_select` の設定を `set completeopt` の時に行うことが考えられます。

https://gist.github.com/ichizok/8b7379406fbbdf16fe17fc7ce5494e8e

**Comment by h-east** [comment]
https://twitter.com/h_east/status/645413447170027521

> Vimのソースedit.cのこの処理、キー入力の度に実行するのは無駄だ。edit.c:637の前に一度やるだけで良い。インサートモード中にcompleteoptオプション代えられなくもないがその変更分は次回から反映でいいだろう。
> https://github.com/vim/vim/blob/master/src/edit.c#L3685-L3690 …

半年ほど前のツイートなので行番号が10行ほどオフセットしてますけど、「無駄だよなぁ」と思っていました。「せめて補完中じゃないときはbypassしろよ」と思ってましたが放置してました。汗。
そうですよね、オプション設定時に更新すれば全く無駄がないんですよね。ナイスです:+1:

**Comment by DeaR** [comment]
そこに追加したの私やわ:fearful:
longestがここにあるし、取り敢えずここで良いや的な適当な奴#385

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/kAc-qoDCgFY
報告しました。

**Comment by miyakogi** [comment]
パッチ＆vim_devへの報告ありがとうございます！
vim_devへの報告後になってしまいましたが、ichizokさんのパッチで問題が発生しなくなることを確認しました。

**Comment by ichizok** [comment]
@h-east これのテスト、既存の new test の仕組みで書けますか？
timer で処理を分断しないと completion が発動しないので、単純に `feedkeys()` だけではできないように思うんですが

**Comment by ichizok** [comment]
``` vim
func Test_finish()
  if [終了条件]
    " テスト完了、結果表示など
    qall!
  endif
endfunc

call Test_foo() " 中で timer 使うかも
call Test_bar() " 中で timer 使うかも
...
call timer_start(1000, 'Test_finish', {'repeat':-1})
```

こんな感じでテスト実行される仕組みが必要かなーと思ったんですが

まあ、今回のケースでは必要なくても、テストできる範囲が広がりそうなので検討する価値はあると思うんですが、どうでしょうか。

**Comment by h-east** [comment]
@ichizok Issueタイトルだけ見て判断しちゃった。0秒タイマー即発動させる必要があるのね。確かにムズい。

**Comment by ichizok** [comment]
7.4.1753
https://github.com/vim/vim/commit/c020042083b9c0a4e932b562c3bef97c76328e18
