### ISSUE TITLE
Vim 8.0 に lambda をねじ込む

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#904]
## 質問・報告の内容

https://github.com/vim-jp/issues/issues/632 で作った lambda パッチを Vim 8.0 にねじ込みたい!
### 必要なこと
- 最新のVimでパッチが動くか確認
- 完全なテストセットを追加する
- jobやチャンネルと組み合わせて、キャッチーなサンプルを書く
- vim-dev へ再プッシュ
### タスク
- [x] 最新のパッチはドレ使うのがよさげ? (@mattn & @haya14busa)
  -    [mattnさんのgist](https://gist.github.com/mattn/5bc8ded21e1033c9c0ea8cd5ecbbce11) をキャンプ地とする!
- [x] テストは揃った?
- [x] 心に響く(job, timer or channel推奨)サンプルは?
- [x] vim-devへ送った?
- [x] 部屋のスミでガタガタふるえて命乞いをする心の準備はOK?

**Comment by koron** [comment]
@mattn 最新のVimに追従したパッチは、他でもない mattn さんが vim-dev へ送ったほうが、変なバリアは作らないで済みそうだと思うのですが、どうですかね?

**Comment by haya14busa** [comment]
Now is the best time to add lambda feature! issue あざます :+1:

### 現状最新情報
- 現状最新パッチ(gist 1ファイル): https://gist.github.com/haya14busa/d1842cff0deb519781a71192dfd6c290
- branchベースパッチ(?): https://github.com/haya14busa/vim/pull/3
  - 最新Vim で動いてる CI の結果も確認可能
  - gistのものと両者ともdiffは同じですが，なにか僕側で弄ることがあれば先にこっちがアップデートされます

mattn さんが送ることに関しては僕はどちらでも構いません．(どうせ元のテスト書いたのはmattnさんやkoronさんやvim-jpメンバーが書いたと書くつもりでした．)
mattn さんが送るなら mattn さん gist をアップデートするとよさそう．

テストに関しては #632 と https://github.com/koron/vim-lambda-tests 見ながら全部入れたつもりです．

サンプルは書いてないです．channelかjobのどちらかで書くとしたら job のほうがサーバー立ち上げるとかいらない周辺の雑事が減ってよさそう．
ただそもそも timer や channel でcallback書くことが増えるから...と雑に書いたものの，lambdaの真価(?)がより発揮されるのは
map/filter/sort や クロージャとして働いたときな気もするのでムズイ．vim 8.0の他の機能と結び付けたいという気持ちもあるけど...

#### warning 懸念

```
eval.c:11806:19: warning: incompatible pointer types passing 'typval_T *' to
      parameter of type 'char_u *' (aka 'unsigned char *')
      [-Wincompatible-pointer-types]
        expr = skipwhite(expr);
                         ^~~~
proto/charset.pro:37:27: note: passing argument to parameter 'q' here
char_u *skipwhite(char_u *q);
                          ^
eval.c:11806:7: warning: incompatible pointer types assigning to 'typval_T *'
      from 'char_u *' (aka 'unsigned char *') [-Wincompatible-pointer-types]
        expr = skipwhite(expr);
             ^ ~~~~~~~~~~~~~~~
```

いまのパッチだとコンパイル時に上記warningがでるんですが，C力なさすぎてシュッと直すにはどうしたらいいかわからず放置してます．
直せればよりかっこよそう．

**Comment by mattn** [comment]
「mattn のパッチを最新版に更新したぜ」って送ってもらって結構です。実際そうなので。

**Comment by mattn** [comment]
警告の部分は

```
expr = (char_u*)skipwhite((char_u*)expr)
```

で

**Comment by haya14busa** [comment]
ありがとうございます! 警告直せました :+1: https://github.com/haya14busa/vim/pull/3/commits/1ee7ebd37045774855933fbc0b7b2afcdc9e41da

**Comment by haya14busa** [comment]
`job_start` に直接lambda渡したら `E117: Unknown function: <LAMBDA>7` いわれたので，jobやchannelに `{callback}` として直接渡した時に参照保持しとく修正+テストいりそう

**Comment by k-takata** [comment]
> テストは揃った?

lambda() で作った Funcref を function() に渡して、partialを作るテストもあったほうがいいかな。
普通はそんな使い方しないと思いますが。

あと、ドキュメントの細かい修正を夜にでも準備予定。英語は苦手なのでネイティブチェックを受けたいところ。

**Comment by mattn** [comment]
job_start って関数リファレンス渡せる仕組みありましたっけ？timer_start の間違い？

**Comment by k-takata** [comment]
E117になってしまいますね。

``` vim
:let timer = timer_start(1000, lambda("echo 'Handler called'"), {'repeat': 3})
```

**Comment by mattn** [comment]
はい。それは確認済みで、job_start と↑に書かれていたので、それって元から出来たっけ？という意味です。

**Comment by haya14busa** [comment]
"callback" とか "out_cb" とか callback 系に渡せると思います．(jobあんまり触ってないのでたぶんですが)
あとすいませんパッチアップデートしたというのはとりあえず単純にパッチ当たるようにしたという意だったので，timerやjob, channelなど新しい系の関数の対応はしてませんでした．

**Comment by mattn** [comment]
@haya14busa さんの lambda ブランチにこれ当てると直るかと思います。

``` diff
diff --git a/src/eval.c b/src/eval.c
index f7c74ac..49051d0 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -15261,7 +15261,6 @@ f_lambda(argvars, rettv)
     ufunc_T    *fp;
     char_u name[20];
     static int lambda_no = 0;
-    funccall_T *fc;

     if (check_secure())
    return;
@@ -15274,7 +15273,7 @@ f_lambda(argvars, rettv)
     if (fp == NULL)
    goto erret;

-    sprintf(name, "<LAMBDA>%d", ++lambda_no);
+    sprintf((char*)name, "<LAMBDA>%d", ++lambda_no);
     rettv->vval.v_string = vim_strsave(name);

     ga_init2(&newargs, (int)sizeof(char_u *), 1);
@@ -20776,8 +20775,17 @@ get_callback(typval_T *arg, partial_T **pp)
    return (*pp)->pt_name;
     }
     *pp = NULL;
-    if (arg->v_type == VAR_FUNC || arg->v_type == VAR_STRING)
+    if (arg->v_type == VAR_FUNC)
+    {
+   ufunc_T     *fp = find_func(arg->vval.v_string);
+   if (fp != NULL)
+       ++fp->uf_refcount;
    return arg->vval.v_string;
+    }
+    if (arg->v_type == VAR_STRING)
+    {
+   return arg->vval.v_string;
+    }
     if (arg->v_type == VAR_NUMBER && arg->vval.v_number == 0)
    return (char_u *)"";
     EMSG(_("E921: Invalid callback argument"));
```

**Comment by mattn** [comment]
元々コールバック系は参照された時点でリファレンスカウンタを上げるべきだけど、なぜかされていないというアレ。

**Comment by mattn** [comment]
ちなみに

```
call timer_start(500, 'Foo')
function Foo()
endfunction
```

が出来るように、意図的にエラーにはしなくしました。

**Comment by mattn** [comment]
デリファレンスもした方がよさげ

**Comment by k-takata** [comment]
> 元々コールバック系は参照された時点でリファレンスカウンタを上げるべきだけど、なぜかされていないというアレ。

lambda関係無しに、現状でも問題が起こる場合があるということですかね。
あと、`func_ref(arg->vval.v_string);` を使ったほうがよくないですか？

**Comment by mattn** [comment]
tskn

**Comment by mattn** [comment]
関数リファレンスがある時には delfunction できない様になってたと思うんですが、リファレンスカウンタを上げてない事で delfunction 出来てしまいそうです。まぁこれは仕様をどうとらえるか次第ですかね。

**Comment by mattn** [comment]
てことでパッチ更新

``` diff
diff --git a/src/eval.c b/src/eval.c
index f7c74ac..6a6cc5b 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -15261,7 +15261,6 @@ f_lambda(argvars, rettv)
     ufunc_T    *fp;
     char_u name[20];
     static int lambda_no = 0;
-    funccall_T *fc;

     if (check_secure())
    return;
@@ -15274,7 +15273,7 @@ f_lambda(argvars, rettv)
     if (fp == NULL)
    goto erret;

-    sprintf(name, "<LAMBDA>%d", ++lambda_no);
+    sprintf((char*)name, "<LAMBDA>%d", ++lambda_no);
     rettv->vval.v_string = vim_strsave(name);

     ga_init2(&newargs, (int)sizeof(char_u *), 1);
@@ -20777,7 +20776,10 @@ get_callback(typval_T *arg, partial_T **pp)
     }
     *pp = NULL;
     if (arg->v_type == VAR_FUNC || arg->v_type == VAR_STRING)
+    {
+   func_ref(arg->vval.v_string);
    return arg->vval.v_string;
+    }
     if (arg->v_type == VAR_NUMBER && arg->vval.v_number == 0)
    return (char_u *)"";
     EMSG(_("E921: Invalid callback argument"));
diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
index 657c772..2c63e43 100644
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -1122,6 +1122,7 @@ remove_timer(timer_T *timer)
     static void
 free_timer(timer_T *timer)
 {
+    func_unref(timer->tr_callback);
     vim_free(timer->tr_callback);
     partial_unref(timer->tr_partial);
     vim_free(timer);
```

**Comment by haya14busa** [comment]
ん，関数リファレンスがあっても delfunction できるような? https://github.com/haya14busa/vim/pull/3/files#diff-7a887ab22b10d0d245b8836793504254R143

**Comment by mattn** [comment]
あーそうですね。
なお誰得感ありますがこんなのは動きますね。

``` vim
function! Foo()
  let n = 0
  call timer_start(1000, lambda("
  \  let n += 1         \n
  \  echo 'foo' . n
  \"),
  \{"repeat": -1})
endfunction

call Foo()
```

**Comment by k-takata** [comment]
`arg->v_type == VAR_STRING` のときは `func_ref()` 必要ないような？

**Comment by mattn** [comment]
VAR_STRING の時もしないと timer が型を持ってないので unref してしまうのです。

**Comment by k-takata** [comment]
VAR_STRING 使って numbered-function が指定されることってあるんでしたっけ。

**Comment by mattn** [comment]
あーそもそも駄目ですね。
関数作って関数リファレンス渡して delfunction してもっかい関数作り直したら余計にデリファレンスされる。
やっぱり numbered-function のみにしないとまずそげ。

**Comment by mattn** [comment]
func_unref は isdigit で見てるからさっきのパッチのままでよかったか。

**Comment by mattn** [comment]
``` diff
diff --git a/src/eval.c b/src/eval.c
index f7c74ac..3c14501 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -15261,7 +15261,6 @@ f_lambda(argvars, rettv)
     ufunc_T    *fp;
     char_u name[20];
     static int lambda_no = 0;
-    funccall_T *fc;

     if (check_secure())
    return;
@@ -15274,7 +15273,7 @@ f_lambda(argvars, rettv)
     if (fp == NULL)
    goto erret;

-    sprintf(name, "<LAMBDA>%d", ++lambda_no);
+    sprintf((char*)name, "<LAMBDA>%d", ++lambda_no);
     rettv->vval.v_string = vim_strsave(name);

     ga_init2(&newargs, (int)sizeof(char_u *), 1);
@@ -20776,8 +20775,15 @@ get_callback(typval_T *arg, partial_T **pp)
    return (*pp)->pt_name;
     }
     *pp = NULL;
-    if (arg->v_type == VAR_FUNC || arg->v_type == VAR_STRING)
+    if (arg->v_type == VAR_FUNC)
+    {
+   func_ref(arg->vval.v_string);
+   return arg->vval.v_string;
+    }
+    if (arg->v_type == VAR_STRING)
+    {
    return arg->vval.v_string;
+    }
     if (arg->v_type == VAR_NUMBER && arg->vval.v_number == 0)
    return (char_u *)"";
     EMSG(_("E921: Invalid callback argument"));
diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
index 657c772..2c63e43 100644
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -1122,6 +1122,7 @@ remove_timer(timer_T *timer)
     static void
 free_timer(timer_T *timer)
 {
+    func_unref(timer->tr_callback);
     vim_free(timer->tr_callback);
     partial_unref(timer->tr_partial);
     vim_free(timer);
```

git diff master したもの
https://gist.github.com/5bc8ded21e1033c9c0ea8cd5ecbbce11

**Comment by k-takata** [comment]
partialのときに、`func_unref(timer->tr_callback);` 呼んで大丈夫なのかな。

**Comment by haya14busa** [comment]
``` vim
function! Foo()
  let n = 0
  call timer_start(1000, lambda("
  \  let n += 1         \n
  \  echo 'foo' . n
  \"),
  \{"repeat": -1})
endfunction

call Foo()
```

これ repeat を 10とかにするとカウントの途中(4とか)でフリーズするんですが再現しますかね? ちょっとまだ詳しく調べてないですが

**Comment by mattn** [comment]
ちょっと調べますね。

**Comment by mattn** [comment]
timer_start はスコープに何も参照を与えないけど、文字列の中のコードは n を見てます。
で、updatetime 時に走る GC で関数スコープ消え去ったのに n がいるスコープを探して無限ループ、という流れらしい。

**Comment by mattn** [comment]
直しました。
https://gist.github.com/mattn/5bc8ded21e1033c9c0ea8cd5ecbbce11

**Comment by k-takata** [comment]
free_timer() こうすべき？

``` C
    if (timer->tr_partial != NULL)
        partial_unref(timer->tr_partial);
    else
        func_unref(timer->tr_callback);
    vim_free(timer->tr_callback);
```

**Comment by mattn** [comment]
lambda はもともと `...` なのですが、それを wrap するかどうかして partial にするって話ですか？

**Comment by k-takata** [comment]
いや、単純に func_unref してしまうと、partial のときに 2回 unref されたりしませんか？

**Comment by mattn** [comment]
あ、そうですね。

**Comment by mattn** [comment]
てか master との差異がよろしくないすね。直します。

**Comment by k-takata** [comment]
ドキュメント関係の追加パッチ、こんな感じでどうでしょう。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/1c50daa4113b924c14e6fd413142ab4835ea319e/lambda-fixtypo.diff?fileviewer=file-view-default
- 関数リストで、戻り値の型が書かれていなかったのを追加。
- それぞれの例の実行結果を追加。
- 冠詞等の修正。（すんません、よく分かってません。ねいちぶちぇっくぷりーず）

あと、"So you can call it like." がよくわからなかったのですが、"So you can call it like a normal function." とかですか？

**Comment by haya14busa** [comment]
mattn さんのパッチ試したらちゃんと直ってました :+1: :+1: :+1:
あとついでに job/channel/partial とlambda一緒に使うテストも書いてはみたんですが，とくに job/channelのテストよくわからんかったのでこれで十分な自信はない... https://github.com/vim/vim/compare/aa618a8...haya14busa:lambda

**Comment by koron** [comment]
https://gist.github.com/mattn/5bc8ded21e1033c9c0ea8cd5ecbbce11 のgist をマスターパッチとしましょう。

**Comment by haya14busa** [comment]
ん bitbucket ファイルにコメント残せないのか...

> Create a new lambda function with constructed with {expr}.

`which constructed with` とかですかね．あと `a function reference` はもう `|Funcref|` とかでもよさそう?

> Lambda function allows to be given variadic arguments.

allows to be given よりは  `can take variadic arguments` とかでしょうか? ([wikipedia](https://en.wikipedia.org/wiki/Variadic) みた)

**Comment by k-takata** [comment]
ドキュメントパッチ更新しました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/39b8881a5997c5ff89597edccc6581cc056cfcd9/lambda-fixtypo.diff?fileviewer=file-view-default
タイマーを使った例も載せてみました。

**Comment by k-takata** [comment]
再度更新
https://bitbucket.org/k_takata/vim-ktakata-mq/src/235fd66/lambda-fixtypo.diff?fileviewer=file-view-default
Funcrefの説明にlambda()を追加。

**Comment by mattn** [comment]
あざます。助かります。

https://gist.github.com/mattn/5bc8ded21e1033c9c0ea8cd5ecbbce11

**Comment by mattn** [comment]
そろそろ出します？

**Comment by k-takata** [comment]
haya14busaさんのjob/channel関係のテスト入ってます？（私のパッチには入っていません。）
あと、partialと組み合わせたテストも入れておいた方がよさそう。

**Comment by haya14busa** [comment]
テスト, gist みたら入れて頂いてた．partialと組み合わせたやつも単に組み合わせただけのものであれば入ってます https://gist.github.com/mattn/5bc8ded21e1033c9c0ea8cd5ecbbce11#file-lambda-diff-L1041

そろそろ出して良さそうだと思います :+1:

**Comment by k-takata** [comment]
お、見落としてました。それならよさそうです。

**Comment by mattn** [comment]
> お、見落としてました。それならよさそうです。

いや、k-takata さんの指摘のあと入れました。そして家事してたら返信忘れてた。

**Comment by k-takata** [comment]
そういえば、Pythonなどとは違って、lambda() の中で return は省略できないのですよね？
どこかに明記した方がいいのかと思いながら、忘れてました。

あと、複数行の関数をlambda()で定義するとき、文字列の配列でも渡せたら便利かも？と思ったのですが、どうですかね。

**Comment by haya14busa** [comment]
個人的にはどうせ `join([...], "\n")` して渡すので文字列の配列はデフォルトでサポートされなくても十分かなぁと思います．executeで動的に関数作るときもそんな感じで今までやってましたし．
ヒアドキュメントとかなら便利度はあがりそうですが，直接的にlambdaと関係はしなさそう

**Comment by k-takata** [comment]
それならいいっか。

returnについては、1個目のExampleの後にこんな感じで追記はどうでしょう。

```
        Note that "return" cannot be omitted unlike Python and other
        languages if you want to return a value.
```

**Comment by koron** [comment]
関係ないけど、 ruby の block 内に `return` 書いてしまい、あとで ぐぬぬ ってよくなる (´・ω・`)

**Comment by thinca** [comment]
> そういえば、Pythonなどとは違って、lambda() の中で return は省略できないのですよね？
> どこかに明記した方がいいのかと思いながら、忘れてました。
> 
> あと、複数行の関数をlambda()で定義するとき、文字列の配列でも渡せたら便利かも？と思ったのですが、どうですかね。

これを見て完全に思いつきで発言しますが、配列で渡したらコマンド列、文字列で渡したら式(return 省略可)とかだったら便利かも? って少し思いました。わかりづらいかもしれないですが… :sweat_smile:

**Comment by Shougo** [comment]
return を省略したら、戻り値が 0 になる仕様にするのはどうでしょうか。

**Comment by koron** [comment]
いまは仕様変更を考慮するフェーズではないと考えています。

引数に配列を渡せるようにするのも、return の省略を許すのも、
取り込まれてからで良いでしょう。

**Comment by thinca** [comment]
考えないならそれはそれで良いですが、私の提案は取り込まれたあとだと後方互換性がなくなるので適用不可能です。

**Comment by k-takata** [comment]
> わかりづらいかもしれないですが… :sweat_smile:

分かりづらいので、その仕様には反対です。

> return を省略したら、戻り値が 0 になる仕様にするのはどうでしょうか。

現状通りな気がします。

**Comment by thinca** [comment]
> 分かりづらいので、その仕様には反対です。

return が省略できるくらいしかメリットはないですしね。
案の1つとして思いついたものを挙げただけなので、私はどっちでもよいです。

**Comment by koron** [comment]
ざっくり確認したところ、テストもサンプルも良い感じに揃ってるきがするので、あとは送るだけですかね?

**Comment by mattn** [comment]
https://gist.github.com/mattn/5bc8ded21e1033c9c0ea8cd5ecbbce11

https://groups.google.com/forum/#!topic/vim_dev/nbvI429-1EE

**Comment by k-takata** [comment]
returnが省略できないのは明記しなくてよい？

**Comment by koron** [comment]
とりあえず最新のパッチを送ったことで、本issueは完了といたします。
引き続き #905 phase 3 をよろしくお願いいたします。

**Comment by k-takata** [comment]
> あと、複数行の関数をlambda()で定義するとき、文字列の配列でも渡せたら便利かも？と思ったのですが、どうですかね。

前のスレッドを見返していたら、すでに却下されてたｗ https://github.com/vim-jp/issues/issues/632#issuecomment-55487831

**Comment by mattn** [comment]
へー、却下されてたんだー。と見に行ったら自分だった。

**Comment by koron** [comment]
僕も、「あ～僕が却下したのかな?(キャラ的に)」と思って確認しに行ったら
まっつんさんで「うへ～」ってなったw
