### ISSUE TITLE
Vim 8.0 に lambda をねじ込む phase 3

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#905]
## TL;DR

lambda パッチの応援をお願いします。
## 質問・報告の内容
#904 の続きです。

最新のコードに対するパッチは送信されました。
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/X84e1UvzBgAJ

ただ過去の経緯(2014年だった)を考えるとスルーされてしまう可能性も依然高いです。
https://groups.google.com/d/msg/vim_dev/7rFZZXea6Gc/JpGBVIaMElcJ

そこで折をみて応援演説的な投稿をしましょう。
単なる :+1: 的なのだとあまり意味はなくて、
- なぜ今こそ lambda が必要なのかを訴える
- lambda を使うとどんな表現が可能なのか
- 将来どんなことが可能になる可能性があるのか (ハードル高い)

みたいなアプローチが良いと考えられます。
## ゴール

いかのいずれかを達成した時点
- パッチが取り込まれる

なおゴール達成後は、自動的にlambda を叩いて鍛えるモードが発動予定です。

**Comment by k-takata** [comment]
https://github.com/vim-jp/issues/issues/904#issuecomment-211044961

> returnが省略できないのは明記しなくてよい？

これに対して、いるともいらないとも反応がありませんが、一応パッチ。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/a3db45d7e1249a8a6e45c0accbda9805490a7832/lambda-doc.diff?fileviewer=file-view-default
より正確に書くなら、lambda() に渡すのは、式ではなく ex コマンド(列)だということになるのでしょうが…。

**Comment by mattn** [comment]
僕も本当ならば lambda という名前の通り式に固執したいのですが、変数代入すら式で書けない Vim script だと文でないと何も便利にならないんすよねw

**Comment by haya14busa** [comment]
大変なことに気づいてしまいました...
個人的にこの lambda 機能の核心部分は2つあって
1. クロージャ
2. 簡単に無名関数を定義できる．特に mapやfilter,sort, またその**ラッパ関数**に渡せる(これは1のクロージャも含む前提)

だと思います．

ただ，この1番目のクロージャ機能とほぼ同等なことが最近，`dict.func`がpartialを返すという仕様変更によって実現可能になっていることに気づきました．
まさかこれを Bram さんは想定していた...!?!?!?

``` vim
function! s:counter_generator(n) abort
  let d = {'n': a:n}
  function! d.increment() abort
    let self.n += 1
    return self.n
  endfunction
  return d.increment
endfunction

let s:counter = s:counter_generator(0)
echo s:counter() | " 1
echo s:counter() | " 2
echo s:counter() | " 3
```

(いままでこのような動作を実現するには `execute` などを駆使して頑張るか script local 変数を使っちゃうしかなかった)

上記のように，
辞書定義をわざわざしなきゃならないこと，
厳密にはクロージャではなくクロージャでやりたかったこと相当ができてるだけってところ，
そもそも `dict.func` がデフォルトでdict bind してるのキモくね?
みたいなモヤモヤはあるものの，既存のシンタックスで，文字列使わずにやりたかったことの半分はできてしまってました．気づいてなかった...

と，いうわけで `lambda` を特に推すなら2つ目のクロージャが**サクッと**定義できちゃう部分になるのかなぁと思います．
具体的には前vim-devスレッドでmattnさんがあげてる map/filter/sort を全部関数渡せるようにしてやりたくて，
かつその際にlambda記法とかがあるとベンリだということ．
そして個人的にもっと重要なのがそれらのラッパー関数やmap/filter/sort的な関数を受け取る関数を定義する際など非常にベンリというところです．

例:
- Vital.Data.List.sort_by() https://github.com/vim-jp/vital.vim/blob/28472cd9b7bb19d3c7b2cb35e651c4615d91d1cc/doc/vital-data-list.txt#L133
- Vital.Data.List.max_by() https://github.com/vim-jp/vital.vim/blob/28472cd9b7bb19d3c7b2cb35e651c4615d91d1cc/doc/vital-data-list.txt#L162
- underscore.vimのmapやfilterのラッパー https://github.com/haya14busa/underscore.vim/blob/master/example/closure.vim#L13-L20
  - なおこれは Vital.Data.Closure https://github.com/vim-jp/vital.vim/blob/master/doc/vital-data-closure.txt が使われています．

このあたりの関数に引数としての関数を定義する際に，既存のvitalのclosureなどでは第2引数で`l:`を渡すなどしないと変数に参照できなかったり，スクリプトローカル変数や関数に定義した関数からアクセスできない問題があり，これが既存のVim scriptで実装されたラムダ/クロージャ(もどき)の限界でした．

こういうケースでは上記した辞書関数によるハックでスコープの問題は解決できるものの，流石に毎回定義するのが面倒なのでここで`lambda`機能がベンリなんですよぉと推すのはありかなぁと思いました．
あと，この用法で推していく場合はlambdaがexprしか受け付けなくなっても個人的には十分ベンリそう...と思いました．
`:return`とか複数行でいろいろやるのは辞書関数ハックで出来ちゃうので．

(なお，クロージャ的に使わず単に無名関数としてtimerなどに渡すという例は，個人的にはもちろんベンリなんですが，
単に関数定義するのがめんどくさいのと定義した結果グローバル/スクリプトローカルスコープがちょっと汚れるというのを
解決しただけで，対していままでの大きい問題を解決してなくてちょっと推すには弱いのかなぁとおもってる．)

#### まとめ
1. クロージャ相当の機能は辞書関数で代用可能なので，sort/map/filterやそのラッパーなどに渡す関数(クロージャ)を簡単に定義できるところは推せそう
2. その場合，別に `lambda`は `expr` だけ受け付けても十分かも?

**Comment by tyru** [comment]
そんな仕様変更があったとは…！
しかしやはり :function を使わずにサクッと無名関数が作れるのは魅力だと思います。

**Comment by tyru** [comment]
> 1. クロージャ
> 2. 簡単に無名関数を定義できる．特に mapやfilter,sort, またそのラッパ関数に渡せる(これは1のクロージャも含む前提)

あとまだ試せていないのですが、スコープをキャプチャできるようになったというのもあるんじゃないでしょうか？

**Comment by haya14busa** [comment]
それがクロージャだという認識です

**Comment by tyru** [comment]
なるほど。
dict.func の場合は明示的に渡す必要があったのに対して、クロージャなので明示的に渡す必要がなくなったのはメリットかなと思いました。

**Comment by haya14busa** [comment]
はい．なのでクロージャではなくクロージャでやりたかったこと相当ができるって感じですね．
明示的にというのはそうですが，個人的には複数行書いたり，1行でも複雑だった時点で dict.func 書いたほうがいろいろメリットあってそっちを使う気がします．
 dict.func のほうがシンタックスハイライトも効くし，引数明示できるし，既存のVim scriptのシンタックスとの互換性もバッチリだし．
なるべく既存のVim scriptのシンタックスを壊さない形で文字列指定ではないlamdaが実現できれば話は変わりそうですが．

**Comment by mattn** [comment]
call の第三引数とは、いったいなんだったのか

**Comment by k-takata** [comment]
todoが更新されて、順位が上がってきました。

```
Patch to support expression argument to sort() instead of a function name.
Yasuhiro Matsumoto, 2013 May 31.
Or should we add a more general mechanism, like a lambda() function?
Patch by Yasuhiro Matsumoto, 2014 Sep 16, update 2016 Apr 17.
```

**Comment by k-takata** [comment]
2つほど問題を見つけたので修正を投げておきました。
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/F2VXnGjRAAAJ

**Comment by k-takata** [comment]
``` diff
--- a/src/eval.c
+++ b/src/eval.c
@@ -654,6 +659,7 @@ static void f_js_decode(typval_T *argvars, typval_T *rettv);
 static void f_js_encode(typval_T *argvars, typval_T *rettv);
 static void f_json_decode(typval_T *argvars, typval_T *rettv);
 static void f_json_encode(typval_T *argvars, typval_T *rettv);
+static void f_lambda(typval_T *argvars, typval_T *rettv);
 static void f_keys(typval_T *argvars, typval_T *rettv);
 static void f_last_buffer_nr(typval_T *argvars, typval_T *rettv);
 static void f_len(typval_T *argvars, typval_T *rettv);
```

関数宣言の追加位置ですが、アルファベット順になってないですね。f_keys() のあとに追加すべきです。

**Comment by k-takata** [comment]
修正したものを投げました。
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/hSkBma9DJgAJ

**Comment by mattn** [comment]
あざます

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/96F1jj5QCAAJ
Bramから反応がありました。要点はこんなところでしょうか。
- 構文を見直した方が良い。
- lambdaに限らず、関数内で関数を定義したときは、クロージャになった方が良い。（が、dictがあるので必須ではない。）
- ローカル変数の保持の仕方を見直した方が良い。
- map(), sort() 等に関数を渡せるのは良いが、VAR_FUNC だけでなく、VAR_PARTIAL にも対応すべき。

**Comment by k-takata** [comment]
パッチをいくつかに分割した方が良いかもしれませんね。
- lambda 構文
- クロージャ
- map(), sort() 等の Funcref 対応

**Comment by k-takata** [comment]
> - map(), sort() 等の Funcref 対応

https://bitbucket.org/k_takata/vim-ktakata-mq/src/3182c79a4bbb47d70866753474fa5799385945e9/support-funcref-in-filter-and-map.patch?fileviewer=file-view-default
partialにも対応したはず。ドキュメントとテストがまだ。

**Comment by k-takata** [comment]
map() と filter() の Funcref 対応って、v:val と v:key ってどうやって関数に渡されるんでしたっけ？
v:val と v:key も使えるが、関数の第一引数にも v:val が渡される？

**Comment by k-takata** [comment]
map() と filter() の Funcref 対応については別issueを作りました。 #924

**Comment by k-takata** [comment]
lambdaの構文をどうするか、もう少し検討が必要なようです。

> 僕も本当ならば lambda という名前の通り式に固執したいのですが、変数代入すら式で書けない Vim script だと文でないと何も便利にならないんすよねw

ZyX氏は、式だけでいいだろうと言っています。（コマンドが必要なら普通の関数を使うべきという考えのようです。）
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/MscPLdz4CAAJ

> `lambda{ v -> if v < 0 | return v * 3.12 | else | return v * -3.12 | endif}` is too verbose. AFAIR I already suggested lambdas implementation once and it was just
> 
> ```
>    \arg1, arg2 : expr1 
> ```

"I already suggested" って、そんなのあったっけと探してみたらありました。

[RFC] Lambdas
https://groups.google.com/d/topic/vim_dev/3lyR_l79O_8/discussion
そして、思いっきり既出でした。 https://github.com/vim-jp/issues/issues/632#issuecomment-55726644

**Comment by mattn** [comment]
Bram はこっち派っぽい？

**Comment by k-takata** [comment]
Bramの提案する表記例:

```
{ a1, a2 -> a1 + a2 }
{ -> string(Today()) }
{ a -> tmp = a * 5; [tmp, tmp + 2, tmp + 5] }
```

`a:` prefix取っちゃって、複数の式を許可して、変数の代入も許可して、とかなり大胆な提案ですね。

**Comment by thinca** [comment]
もはや別言語感がある。

**Comment by rbtnn** [comment]
ww
あくまで複数の**式**なのね。代入は可能だけど、コマンドは無理か。

**Comment by k-takata** [comment]
Bramの最初の案では、コマンド列でしたので、コマンドを使いたいという意見が多ければまた変わるかも？
ただ、式ではなくコマンドとすると、パースが難しくなる気がします。（`{args -> cmds}` の終わりの `}` を見つけるのが困難な気が。）

あとBramは、lambda自体の有用性については同意していますが、クロージャについては意見を待っている状態なので、クロージャが欲しいという人は便利な例を挙げると良いです。

**Comment by k-takata** [comment]
refcount関係の修正は、lambdaパッチから分離して別パッチにした方が良さそうな気がしてきました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/90ea467da862bc2eaf59454f75b8faea34604a1e/func-refcount.patch?at=default

そして、作りかけの何か。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/90ea467da862bc2eaf59454f75b8faea34604a1e/lambda2.patch?at=default
とりあえず、単一の式のみ。

**Comment by mattn** [comment]
← 燃え尽きて情熱が無くなってしまった人

**Comment by k-takata** [comment]
なんてこったい。Bramがやる気になっている今がチャンスなのに。

それはさておき、lambdaを2重にすれば、代入構文を使わずに一時変数が使えるのか。なるほどなー。
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/63u71d6GCQAJ

```
\a -> ((\tmp -> [tmp, tmp + 2, tmp + 5])(a * 5))
```

**Comment by koron** [comment]
> lambdaを2重にすれば、代入構文を使わずに一時変数が使えるのか

ラムダ計算的には当然かもですが、それに輪をかけてヒドイこと(表記)になる予感しか無いw

**Comment by mattn** [comment]
代入から let が無くなったって時点でもう別の言語すよねw

**Comment by k-takata** [comment]
> それに輪をかけてヒドイこと

昨日の作りかけの何かでも動いた！

```
:echo {a -> {tmp -> [a:tmp, a:tmp + 2, a:tmp + 5]}(a:a * 5)}(2)
[10, 12, 15]
```

私のようなlambda初心者には読めません。 :sob:

**Comment by k-takata** [comment]
`a:` を省略できるようにするにはどうすればいいのだろう。さっぱり分からない。

**Comment by k-takata** [comment]
`call_user_func()` が関数を実行している関数で、この中で `a:` のセットアップをしているので、そこをいじることになるのだろうか。

**Comment by thinca** [comment]
TODO 更新されてました。

コミット: https://github.com/vim/vim/commit/063b9d15abea041a5bfff3ffc4e219e26fd1d4fa#diff-38d7929bd26d74d92ceddf984bbfc8dbR123
内容: https://github.com/vim/vim/blob/063b9d15abea041a5bfff3ffc4e219e26fd1d4fa/runtime/doc/todo.txt#L123-L129

文字列ではなくリテラルで定義できるようにする方針は確定っぽい?
文法については異議があるなら早めにしないとこのまま行ってしまいそうな予感…。

**Comment by k-takata** [comment]
> 文字列ではなくリテラルで定義できるようにする方針は確定っぽい?

クロージャなしのlambdaについてはほぼ確定でしょう。議論の余地があるのは、
- 複数の式を許可するかどうか
- 変数の代入も許可するかどうか

ぐらいだと思います。まあ、最初の実装はどちらもなしでよいでしょうが。
クロージャをどうするのかは、まだあまり議論されていません。
- そもそも必要なのか
- 必要ならlambda以外の関数内関数もクロージャに対応すべき
- クロージャとして使いたい場合は、普通の関数と区別できるように専用構文を用意すべきか

**Comment by koron** [comment]
リテラルで定義できるようにするのであれば、
多かれ少なかれ Vim script パーサに手を入れなければならない点が面倒なだけでしょう。
値を返すコマンド(っぽく見えるもの)はこれまでなかったので。

専用構文 たとえば `let f = lambda ... endlambda` みたいなのにするか、
関数内関数を視野にいれて `let f = function ... endfunction` にみたいにするかは、
ほぼ実装の大変さには影響がないと思います。
あえて言えば、前者のほうがロード時の 1st pass の高速化がやりやすいかも。

今、僕が思いつくのはこのくらいです。

**Comment by k-takata** [comment]
パッチ更新
https://bitbucket.org/k_takata/vim-ktakata-mq/src/6d421eab8842ba93c115d57c42fd9eabfa328851/func-refcount.patch?fileviewer=file-view-default
https://bitbucket.org/k_takata/vim-ktakata-mq/src/6d421eab8842ba93c115d57c42fd9eabfa328851/lambda2.patch?fileviewer=file-view-default
手抜きで、`a:arg` と `l:arg` が同じものを指すようにしてみました。
refcount関係の修正は、timer以外の部分も修正が必要ではないかと思い修正してみましたが、動作未確認。

実行例:

```
:echo {a -> {tmp -> [tmp, tmp + 2, tmp + 5]}(a * 5)}(2)
[10, 12, 15]
```

```
:let timer = timer_start(500, {-> execute("echo 'Handler called'", "")}, {'repeat': 3})
Handler called
Handler called
Handler called
```

**Comment by k-takata** [comment]
refcountの修正は、Bramによる追加修正付きで取り込まれました。7.4.2026
https://groups.google.com/d/topic/vim_dev/uoIZQpZ3bTw/discussion

**Comment by k-takata** [comment]
テスト追加とバグ修正。
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/-nstTq57AAAJ

**Comment by k-takata** [comment]
> Thanks!  Unless there is a better proposal soon I'll include this.

近いうちに入りそう。

**Comment by k-takata** [comment]
しかし、現時点のクロージャなしの実装だと、下のような使い方ができないのがつらい。

```
let list = [ something ]
let l:threshold = 10
filter(list, {idx, val -> val > l:threshold})
```

`function()` で部分適用を行えば同じことはできるが、冗長。

```
filter(list, function({th, idx, val -> val > th}, [l:threshold]))
```

**Comment by k-takata** [comment]
`:echo {-> 0}()` は普通に動くが、`:call {-> 0}()` は E15, E475 が出る。なぜだ？

**Comment by tyru** [comment]
違う気がしますが、 https://github.com/vim-jp/issues/issues/17 を思い出しました。

**Comment by k-takata** [comment]
7.4.2044
https://groups.google.com/d/topic/vim_dev/yXtgV69EJbM/discussion
次はクロージャを何とかしないとな。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/-kIetWcaAQAJ
lambdaをパースするときに、使っているローカル変数を調べてキャプチャすれば良いとの指摘。
https://github.com/vim/vim/blob/269f595f9eef584937e7eae70fde68cdd7da5bcf/src/eval.c#L5369
この部分でチェックすれば良いとのこと。確かにできそうな感じはする。

**Comment by koron** [comment]
うへw ガチな実装じゃねぇかw

**Comment by k-takata** [comment]
うーむ、lambdaの入れ子はどうすべきなのか。

```
{x -> {y -> x / y}}
```

**Comment by koron** [comment]
関数の宣言があったらスコープ作って、その中で参照している変数は外側のスコープからキャプチャして…ってのを再帰的にやるのが本当なんですが…

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/rEZjwB7UAQAJ

```
echo {y -> {x -> x(y)(10)}({y -> y})}({z -> z})
10
echo {x -> {y -> x / y}}(10)(2.0)
5.0
```

何かそれっぽいものができた気がする。テストはまだ。

**Comment by k-takata** [comment]
test_alot.vim で落ちるな…

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/aoqp6fkmAgAJ
test_alot.vim で落ちるのは直った模様。

```
let Y = {f -> (({x -> f ({y -> x(x)(y)})}) ({x -> f ({y -> x(x)(y)})}))}
```

がエラーになるがよく分からない。

**Comment by k-takata** [comment]
上のパッチ、外側のスコープのローカル変数 (`l:xx`) はそのままアクセスできるが、関数引数 (`a:xx`) はアクセスできないが良いだろうか。

``` vim
function! Foo(arg1)
  return {x -> x + a:arg1}  " Error
endfunction

function! Bar(arg1)
  let arg1 = a:arg1
  return {x -> x + arg1}  " OK
endfunction
```

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/zkExnamaAgAJ
"a:" で外側のスコープの関数引数にアクセスできるようになりました。代わりに、lambda自身の引数には "a:" を付けられなくしました。

そして、これが動くようになりました。

```
:let Y = {f -> (({x -> f ({y -> x(x)(y)})})({x -> f ({y -> x(x)(y)})}))}
:let Fact = {f -> {x -> (x == 0 ? 1 : x * f(x - 1))}}
:echo Y(Fact)(5)
120
```

（何をやっているのか理解できない。）

**Comment by koron** [comment]
Vimスクリプト的には遅延評価しないから、実行速度とメモリがヒドイことになってそう :sweat_smile:

**Comment by koron** [comment]
誤解を招かないためには `Y` を `Z` に変えておいたほうが良いのかもしれないw

**Comment by k-takata** [comment]
> 誤解を招かないためには Y を Z に変えておいたほうが良いのかもしれないw

あー、Y コンビネータの亜種の Z コンビネータでしたか。

**Comment by k-takata** [comment]
あとは、mattnさんの実装とは異なって、参照キャプチャではなく値キャプチャになっているのは本当に良いのかという点と、メモリリークしていないかという点が気になるところです。

**Comment by k-takata** [comment]
``` vim
function! Test_lambda_closure()
  function! s:foo()
    let x = [0]
    return {-> [execute("let x[0] += 1"), x[0]][-1]}
  endfunction

  let l:F = s:foo()
  call test_garbagecollect_now()
  call assert_equal(1, l:F())
  call assert_equal(2, l:F())
  call assert_equal(3, l:F())
  call assert_equal(4, l:F())
endfunction
```

落ちた。やっぱりGCちゃんと対応しないとダメか。

**Comment by k-takata** [comment]
GCに対応。
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/u5oMfnyFAwAJ

> - lambdaに限らず、関数内で関数を定義したときは、クロージャになった方が良い。（が、dictがあるので必須ではない。）

よく考えると、lambdaを値キャプチャにしてしまうと、通常の関数内関数をクロージャにするときとの整合性が取りづらそう。

**Comment by k-takata** [comment]
[Bramのコメント](https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/96F1jj5QCAAJ)を読み返してみるか。

> In the implementation it seems the dictionary storing the function-local
> variables is kept for a very long time.  This relies on the garbage
> collector.  It's better to use reference counting to be able to free the
> dictionary as soon as it's unused.

元々の実装では、`funccall_T` が lambda から参照されているかどうかを `ref_by_lambda` で管理していたが、これをリファレンスカウンタに変えるべきということかな。

> Also, the lambda always keeps the function-local variable dict, even
> when it's not actually used.  That makes lambdas a expensive.
> It would be better to explicitly state the lambda is using its context.
> Then we can also do that with ":function", so that we are not forced to
> use a lambda if we want a closure.

lambda が外側のスコープの変数を使ってなくても、それを保持しているのを問題視しているが、使っているかどうかは判別できるようになったので、解決できそう。

**Comment by k-takata** [comment]
capture by valueの最新版
https://bitbucket.org/k_takata/vim-ktakata-mq/src/6da42d0c61ecfd1dbcc035b8f3a41896b5e46647/lambda-update.patch?at=default

capture by referenceの作りかけ （上の lambda-update.patch に対するパッチ）
https://bitbucket.org/k_takata/vim-ktakata-mq/src/6da42d0c61ecfd1dbcc035b8f3a41896b5e46647/lambda-capture_by_reference-temp.patch?at=default
`test_lambda.vim` を動かしたら、`Test_lambda_with_timer` で落ちてしまう。

**Comment by k-takata** [comment]
パッチ更新
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/8-aFcgVzBAAJ
capture by referenceもだいぶ安定してきた気がする。(が、Zコンビネータでメモリリークしてる？)
通常の関数をクロージャに対応させるパッチも追加。

``` vim
function! Foo()
  let x = 0
  function! Bar() closure
    let x += 1
    return x
  endfunction
  return function('Bar')
endfunction

let F = Foo()
echo F() " 1
echo F() " 2
echo F() " 3
echo F() " 4
```

**Comment by k-takata** [comment]
closureパッチを更新
https://bitbucket.org/k_takata/vim-ktakata-mq/src/0087d16e11791d1c7a794641deb1ea3d5f5fa25f/closure.patch?at=default&fileviewer=file-view-default

ドキュメントとテストを追加したら、テストで落ちた。

``` vim
function! Test_closure_counter()
  function! s:foo()
    let x = 0
    function! s:bar() closure
      let x += 1
      return x
    endfunction
    return function('s:bar')
  endfunction

  let l:F = s:foo()
  call test_garbagecollect_now()
  call assert_equal(1, l:F())
  call assert_equal(2, l:F())
  call assert_equal(3, l:F())
  call assert_equal(4, l:F())
endfunction
```

ガベコレで回収されてしまった模様。`s:` 関数にしたのが影響してそうだが…？

**Comment by k-takata** [comment]
パッチ更新
- https://bitbucket.org/k_takata/vim-ktakata-mq/src/0d62ba414841e96e1a7778bb92155d17315ee3d5/lambda-update.patch?at=default
- https://bitbucket.org/k_takata/vim-ktakata-mq/src/0d62ba414841e96e1a7778bb92155d17315ee3d5/lambda-capture_by_reference.patch?at=default
- https://bitbucket.org/k_takata/vim-ktakata-mq/src/0d62ba414841e96e1a7778bb92155d17315ee3d5/closure.patch?at=default

`s:` 関数がガベコレに対応できていなかったのを修正、テストを追加、ドキュメントを更新。

https://bitbucket.org/k_takata/vim-ktakata-mq/src/0d62ba414841e96e1a7778bb92155d17315ee3d5/lambda-capture_by_reference.patch?fileviewer=file-view-default#lambda-capture_by_reference.patch-248

ここの `test_garbagecollect_now()` を削除すると、後続のテストがいくつか失敗する怪現象が発生していたが、たぶん気のせいｗ （`assert_fails()` に何かありそう？）

**Comment by k-takata** [comment]
パッチを再構成。
1. Lambda with capture-by-value:
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/9a62b8ce9304e1c0f78c70d524c1d8d8a8015cc7/lambda-capture_by_value.patch?at=default
2. Lambda with capture-by-reference:
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/9a62b8ce9304e1c0f78c70d524c1d8d8a8015cc7/lambda-capture_by_reference.patch?at=default
3. Closure with normal functions:
   https://bitbucket.org/k_takata/vim-ktakata-mq/src/9a62b8ce9304e1c0f78c70d524c1d8d8a8015cc7/closure.patch?at=default

1.と2.は排他。1.の利点はおそらくない。
3.は2.の上に適用。

**Comment by mattn** [comment]
2種類のパッチ管理してるのかw

**Comment by k-takata** [comment]
1.はもうほとんどいじっていませんｗ

**Comment by k-takata** [comment]
> capture by referenceもだいぶ安定してきた気がする。(が、Zコンビネータでメモリリークしてる？)
> 
> ここの test_garbagecollect_now() を削除すると、後続のテストがいくつか失敗する怪現象が発生していたが、たぶん気のせいｗ （assert_fails() に何かありそう？）

ようやく両方の問題が直りました。
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/3o7iurJZBQAJ
今のところ、ローカルでは問題出ていません。

**Comment by k-takata** [comment]
一部古いコードとコメントが混じっていたので更新。
https://groups.google.com/d/msg/vim_dev/4HX2RPM3_BM/jA_XEAClBQAJ

unlet に対応してみようとしたが、SEGVするので断念。

**Comment by k-takata** [comment]
やっとunletも動いた。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/6fd892383533a9a4499665188b413dc10fb86657/closure-unlet.patch?at=default
これで全機能を新文法版に移植し終わったはず。

**Comment by k-takata** [comment]
早い！

7.4.2119 lambdaのclosure対応
https://groups.google.com/d/topic/vim_dev/HNm4R-lDDls/discussion
7.4.2120 通常関数のclosure対応 (unlet対応入り)
https://groups.google.com/d/topic/vim_dev/73BivpCMzTs/discussion
7.4.2121 +lambda feature (by Bram)
https://groups.google.com/d/topic/vim_dev/fXrVil8blEg/discussion

**Comment by k-takata** [comment]
7.4.2136 ～ 7.4.2143で、Bramによるlambda&closure関連の修正が大量に入りました。
7.4.2137では、`funcref()`が追加になりました。
(わずか1日で直してしまうとは)
