### ISSUE TITLE
+termtruecolor の際に E254 が発生する

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#907]
## 質問・報告の内容

7.4.1770 で `+termtruecolor` feature と `'guicolors'` オプションが追加されましたが、GUI 版では引ける色名が引けずに E254 が発生します。
おそらくですが、CUI 版だと `make install` で `$VIMRUNTIME/rgb.txt` がインストールされないのが原因だと思われます。手動でコピーしたところ、エラーが出なくなりました。
## Vimのバージョン

7.4.1770
## OSの種類

Linux で動作を確認

**Comment by tyru** [comment]
原因がそこまで分かってるなら、とりあえず報告でいいのでは。

**Comment by h-east** [comment]
ChrisBさんが報告してくれました。
https://groups.google.com/d/msg/vim_dev/ruRV8HGj_Sg/Ilc6-j92AQAJ

**Comment by h-east** [comment]
patch 7.4.1775
https://github.com/vim/vim/commit/763b684373bf5954445d8d8d99da1e39a4fc5105

**Comment by mattn** [comment]
http://anond.hatelabo.jp/20160422223507
