### ISSUE TITLE
cinoptions=N-s が template で効かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#91]
まだちゃんと検証/仕様確認してないのでバグかどうかわかりませんが、template があると `set cinoptions=N-s` が効かないようです。
補足: これは名前空間内でインデントを行わない設定。 `:help cino-N`

``` cpp
namespace {
// template なし
void func() {}

// template あり
template <class T>
    void func() {}
}
```

**Comment by thinca** [comment]
補足。template 自体がインデントをしているわけではありません。namespace 外だと正常にインデントが揃います。

``` cpp
// namespace {
// template なし
void func() {}

// template あり
template <class T>
void func() {}
// }
```

**Comment by h-east** [comment]
vim hoge.cpp
<code>:set cinoptions=</code>
以下の簡素化したコードでもインデントの挙動が変わりますね。( _ はカーソル位置)

``` c++
a
_
```

``` c++
{
    a
        _
```

ここからは推測です。
[:help cino-+](http://vim-jp.org/vimdoc-ja/indent.html#cino-+)
に<code><strong>関数の内側では</strong> N 文字分インデントする。</code> と書いてあります。
関数の内側かどうかの判断をおそらく<code>{</code> の内側か否かで簡易的にやっているんじゃないかと。
そして関数の内側と判定したときだけ<code>cino-+</code>(デフォルトは'shiftwidth')が適用されるんじゃないかと思います。

**Comment by h-east** [comment]
Hi.
@thinca and vimmer

`:set cino=+3` だとブロック内の`a` `改行` でネストが3文字になったので前のコメントの推測があっているということになります。
(cino-N の不具合ではないという認識です。)

``` c
{
    a
       _
```

問題なければクローズお願いします。

**Comment by thinca** [comment]
名前空間に対応するインデントの機能がある以上、名前空間の `{` と関数の `{` は区別して認識されるべきだと思います。

**Comment by h-east** [comment]
@thinca 
`cino-N` の動作自体には問題ないのでこのIssueはクローズしません？
指摘の件は`cino-+` の動作の話になりますから。

必要でしたら別Issueを立ててください。
おそらく `cino-+` で「namespace の`{`は関数の始まりだと判定しない」というスペシャル処理を入れるのは厳しいんじゃないかと思います。

**Comment by thinca** [comment]
了解です。
