### ISSUE TITLE
string([a,a,a])が正しくない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#911]
## 質問・報告の内容
#169 の修正 (7.4.1644) で、循環参照を `...` で省略するようにした副作用で、リスト内に同じ辞書への参照が含まれるときに正しい結果を返さなくなってしまいました。

``` vim
let a = {}
echo string([a,a,a])
[{}, {...}, {...}]
```

期待値は、`[{}, {}, {}]` です。
## Vimのバージョン

7.4.1644以降
## OSの種類

非依存
## その他
#652 のパッチを適用すれば直りそうな気がしますが未確認です。あと、そのパッチは Bram が難色を示しているので、何らかの追加修正が必要と思われます。

**Comment by k-takata** [comment]
パッチを書いてみました。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/25f657ec113e5901cb8617a9e814a37e850368ad/fix-echo-and-string.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
ちょっと修正
https://bitbucket.org/k_takata/vim-ktakata-mq/src/294961a5221acf8a980181ffd2e9a6a0c7891a17/fix-echo-and-string.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/msg/vim_dev/tUXaR7nWscc/IJ1Zo_-cAAAJ

**Comment by koron** [comment]
7.4.1862 https://github.com/vim/vim/commit/18dfb4404a618c52ee7138630a2381aed4d66eaf でマージされた?

**Comment by k-takata** [comment]
修正が足りないところがあったようで、Bram自身による修正が入った上でマージされました。
（全テストを流すのを忘れてたのは秘密ｗ）
