### ISSUE TITLE
ウィンドウ関連のコマンドを実行するとコマンドラインモードの高さが上に伸びる

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#913]
## 質問・報告の内容

set laststatusの値が0の時、特定の条件でウィンドウの作成や削除を行うとコマンドラインモードの高さが1行分だけ上に伸びました。

**再現方法1**

始めにset laststatus=0とset splitbelowを指定します。
:split,:new,:sview,:sfindのいずれかのコマンドを実行後、分割されたウィンドウのどちらか1つを閉じるとずれます。

vim起動

```
vim -Nu NONE -S sample1.vim 
```

sample1.vimの内容

```
set laststatus=0
set splitbelow
split
quit
call feedkeys(':')
```

**再現方法2**

始めにset laststatus=0を指定します。
:split,:new,:sview,:sfindのいずれかのコマンドと:botrightを組み合わせて実行すると位置がずれます。

Vim起動

```
vim -Nu NONE -S sample2.vim 
```

sample2.vimの内容

```
set laststatus=0
botright split
call feedkeys(':')
```
## Vimのバージョン

7.4.1832
## OSの種類
-   Linux
## OSのディストリ

Debian
## OSのバージョン

8.4

**Comment by h-east** [comment]
@norio13 Issue登録ありがとうございます。

再現方法1と再現方法2はそれぞれ別の不具合のようです。

まずは再現方法2の修正patch

``` patch
diff --git a/src/window.c b/src/window.c
index bbd0a52..d274954 100644
--- a/src/window.c
+++ b/src/window.c
@@ -1165,8 +1165,13 @@ win_split_ins(
     * one row for the status line */
    win_new_height(wp, new_size);
    if (flags & (WSP_TOP | WSP_BOT))
-       frame_new_height(curfrp, curfrp->fr_height
-           - (new_size + STATUS_HEIGHT), flags & WSP_TOP, FALSE);
+   {
+       int new_fr_height = curfrp->fr_height - new_size;
+
+       if (!((flags & WSP_BOT) && p_ls == 0))
+       new_fr_height -= STATUS_HEIGHT;
+       frame_new_height(curfrp, new_fr_height, flags & WSP_TOP, FALSE);
+   }
    else
        win_new_height(oldwin, oldwin_height - (new_size + STATUS_HEIGHT));
    if (before) /* new window above current one */
```

**Comment by h-east** [comment]
両方に対応したpatchです。
再現方法1の修正箇所の元コメントにちょっと不安な事が書いてありますが、frame情報の更新前にwindow情報を更新しないとframeとwindowで不整合が起きるのでこの修正であっていると思います。
もし、変な挙動を見つけたら教えて下さい。

``` patch
diff --git a/src/window.c b/src/window.c
index bbd0a52..14d4af6 100644
--- a/src/window.c
+++ b/src/window.c
@@ -1165,8 +1165,13 @@ win_split_ins(
     * one row for the status line */
    win_new_height(wp, new_size);
    if (flags & (WSP_TOP | WSP_BOT))
-       frame_new_height(curfrp, curfrp->fr_height
-           - (new_size + STATUS_HEIGHT), flags & WSP_TOP, FALSE);
+   {
+       int new_fr_height = curfrp->fr_height - new_size;
+
+       if (!((flags & WSP_BOT) && p_ls == 0))
+       new_fr_height -= STATUS_HEIGHT;
+       frame_new_height(curfrp, new_fr_height, flags & WSP_TOP, FALSE);
+   }
    else
        win_new_height(oldwin, oldwin_height - (new_size + STATUS_HEIGHT));
    if (before) /* new window above current one */
@@ -1179,18 +1184,12 @@ win_split_ins(
    {
        wp->w_winrow = oldwin->w_winrow + oldwin->w_height + STATUS_HEIGHT;
        wp->w_status_height = oldwin->w_status_height;
-       /* Don't set the status_height for oldwin yet, this might break
-        * frame_fix_height(oldwin), therefore will be set below. */
+       oldwin->w_status_height = STATUS_HEIGHT;
    }
    if (flags & WSP_BOT)
        frame_add_statusline(curfrp);
    frame_fix_height(wp);
    frame_fix_height(oldwin);
-
-   if (!before)
-       /* new window above current one, set the status_height after
-        * frame_fix_height(oldwin) */
-       oldwin->w_status_height = STATUS_HEIGHT;
     }

     if (flags & (WSP_TOP | WSP_BOT))
```

**Comment by h-east** [comment]
例のコメントが入ったのが`patch 7.4.706`
https://github.com/vim/vim/commit/5b14f89164fa2f40f52283226c98005887568317

で、大本の報告が以下のスレッド
Re: [bug] cmdline-window given laststatus=0 and vertical split
https://groups.google.com/forum/#!searchin/vim_dev/Yclept$20Nemo/vim_dev/fNq8tHTcKfA/7yg4GZ1h8agJ

確かに私のpatchを適用すると、上記問題が再発する。汗。
おそらく、7.4.706がad hocだと思われる。明日調べます。

**Comment by h-east** [comment]
よしっ！これで本Issue報告の分2つと`7.4.706`関連の`ls=0 and :vsp and q:`がおかしい件も直った:+1: (はず)
https://gist.github.com/h-east/1d6923f070675e3909775654277bbabe

ちょっといろいろ試してみます。
おかしいところ見つけたら教えて下さい。

**Comment by norio13** [comment]
h-eastさんのpatchを適用したら不具合が解消されました。
こちらで確認した範囲ではpatch適用後に異常は見当たりません。

確認したことは
再現方法2については:split,:vsplit,:new,:vnew,:sview,:sfindと
:vertical,:leftabove,:rightbelow,:topleft,:botright:の組み合わせを全通り確認しました。

再現方法1についても:split,:vsplit,:new,:vnew,:sview,:sfindで確認しました。
:splitのみequalalwaysやeadirectionの値を全通り試しました。

vim_devで挙がっていた不具合もpatch適用後に解消されていました。

迅速なご対応ありがとうございます。

**Comment by h-east** [comment]
どうもad hoc感が拭えなかったのでもうちょっと調べてpatch更新&test追加しました。
https://gist.github.com/h-east/430b3f36a677804dded7b9a31ee629a9
(2016-5-24 12:02 Gistの更新ミスってたので再更新しました)

**Comment by h-east** [comment]
Sent to vim_dev.
https://groups.google.com/d/msg/vim_dev/-BMwAIwJBzM/MISNq24EBAAJ

**Comment by h-east** [comment]
patch 7.4.1835
https://github.com/vim/vim/commit/991dea3ab185fb35e577ab0bdfd443cd4b43ccc6

@norio13 issue登録および動作確認ありがとうございました:+1:
