### ISSUE TITLE
挿入モードに入っただけでTextChangedIが発火する

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#914]
## 質問・報告の内容

vimrcにg:loaded_matchparenを定義したり、$VIMRUNTIME/plugin/matchparen.vimを空にするか削除されている状態の時、ノーマルモードでUndoやRedoをしてバッファのテキストが変更された場合に限り、挿入モードに入っただけでTextChangedIが発火します。

**再現する流れ**
1. vimrcでg:loaded_matchparenと自動コマンド(TextChangedI)を定義します。
2. 挿入モードでバッファのテキストを変更します。
3. ノーマルモードでUndoかRedoを実行してb:changedtickを更新させます。
4. 挿入モードに入ります。挿入モードに入っただけで発火しました。

$VIMRUNTIME/plugin/matchparen.vimを空にするか削除すると、g:loaded_matchparenが未定義でも4のタイミングで発火しました。

**検証用サンプル**

TextChangedIが発火した時に変数nに1を加算するサンプルです。

Vim起動

```
$ vim -Nu sample.vimrc
```

Vim起動後に行う操作
発火されていれば2を表示。発火されていなければ1を表示します。

```
ii<esc>ui<esc>:echo n
```

sample.vimrcの内容

```
let g:loaded_matchparen = 1

let n = 0

augroup sample
    autocmd!
    autocmd TextChangedI * let n += 1
augroup END
```

g:loaded_matchparenの他のg:loaded_から始まる変数で検証した結果を貼ります。
**A**は$VIMRUNTIME/plugin/matchparen.vimをいじってない状態で検証した時の変数nの結果です。
**B**は$VIMRUNTIME/plugin/matchparen.vimを空にした状態で検証した時の変数nの結果です。

| 変数名 | A | B |
| --- | --- | --- |
| 変数未定義 | 1 | 2 |
| g:loaded_matchparen | 2 | 2 |
| g:loaded_getscriptPlugin | 1 | 2 |
| g:loaded_gzip | 1 | 2 |
| g:loaded_logiPat | 1 | 2 |
| g:loaded_netrwPlugin | 1 | 2 |
| g:loaded_rrhelper | 1 | 2 |
| g:loaded_spellfile_plugin | 1 | 2 |
| g:loaded_tarPlugin | 1 | 2 |
| g:loaded_2html_plugin | 1 | 2 |
| g:loaded_vimballPlugin | 1 | 2 |
| g:loaded_zipPlugin | 1 | 2 |
| g:loaded_getscriptPlugin | 1 | 2 |
## Vimのバージョン

7.4.1848
## OSの種類
-   Linux
## OSのディストリ

Debian
## OSのバージョン

8.4
## 使用している or 関係していそうなプラグイン

matchparen.vim
## その他

(関連して何か気がついたこと、気になることがあればココに書いてください)

**Comment by ichizok** [comment]
`vim -Nu NONE -S sample.vimrc` で起動したときも、提示された操作を行うと `n==2` になりました。
したがって、プラグインは関係ないと思われます。
もしくは、「matchparen を有効にすると挙動が変わる (`TextChangedI` が1回しか発火しない)」という現象であるとも言えます。

**Comment by h-east** [comment]
matchparenの有効/無効は「TextChangedイベントにautocmd登録している/していない」の違いでした。
TextChangedイベントにautocmd登録している時だけ`last_changedtick`(チェック用変数)を更新するようになっていたのでそこを修正しました。

https://gist.github.com/h-east/f57f192cd232a6d86d2decd0f97a5c34

**Comment by h-east** [comment]
うーん、`TextChanged`イベント、`TextChangedI`イベントどちらか片方しかautocmdしていない時の挙動としては既存のままでいいのかもしれない。
（`TextChangedI`イベントにのみautocmdしている場合、ノーマルモードでの変更は覚えておいて、インサートモードに入った時にその分で`TextChangedI`イベントをトリガさせる)

**Comment by norio13** [comment]
@h-east いつもありがとうございます。
個人的にはh-eastさんのパッチを当てると挙動が統一されるのでこのほうがいいのですが、
h-eastさんのご意見を尊重させていただきます。
現状の挙動については仕様として受け止めます。

ichizokさんもフォローありがとうございます。

**Comment by h-east** [comment]
特に反対意見もないので、現在の動作を仕様とし`works for me`で閉じます。

@norio13 issue登録ありがとうございました。
