### ISSUE TITLE
端末機能、作っちゃわない？

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#915]
neovim にあるのは皆さんご存知ですが、後発であるはずの Visual Studio Code に端末機能が入ってしまった様です。
って事で端末機能、作っちゃわない？
(何も着手してません)

**Comment by k-takata** [comment]
channel.txt より、

```
                                                *job-term*
"term": "open"          Start a terminal and connect the job
                        stdin/stdout/stderr to it.
                        NOTE: Not implemented yet!
```

これは、neoとかVSCの端末機能と比べてどうなんでしょうか。
ともかく、期待!!!

**Comment by mattn** [comment]
stdin/stdout/stderr を使った物なら、以前作った物が近いかもしれません。

https://github.com/mattn/vim-terminal

**Comment by koron** [comment]
windows only?

**Comment by mattn** [comment]
僕はそのつもりはないっす。出来れば分業したいけど。

**Comment by koron** [comment]
端末機能に求めること、挙げてみて共通のイメージを持つのが、先決な気がしてきました。

**Comment by mattn** [comment]
あと個人的には、無駄作業にならないようにBramにも「やるよ」と音頭を取りたい。

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/i6gXZ9lytcA/9HFw01yEBAAJ

> It would be useful, especially when running a job that has output.
> Or when it prompts for input.
> 
> It's not so easy to do.  At least in a way that it works on most
> systems.  But, if someone sends a patch... 

Vim 8.0では見送りかな。

**Comment by mattn** [comment]
結局言い出しっぺで作っちゃった。

https://github.com/vim/vim/pull/1854

あとはバグつぶしだし、本 issue の役目は終わりという事で close
