### ISSUE TITLE
split() 関数の挙動について

### ISSUE THREAD

**Issue by machakann** [vim-jp/issues#917]
## 質問・報告の内容

文字列 `'a+b'` を文字列のリスト `['a', '+', 'b']` にすることを期待して `split()` 関数を次のように使ったところ、 `['a', '+b']` を得ました。

``` vim
echo split('a+b','\%(\ze+\|+\zs\)')
```

期待する動作と違うように感じたのですがいかがでしょうか？使い方が間違っている点などありましたら御教示ください。
## Vimのバージョン

7.4.1862
## OSの種類
-   Windows 10
## その他

関連するかわかりませんが第三引数を与えると `['a', '', '+b']` となるように `+` の前に二回マッチしているように見えます。

``` vim
echo split('a+b','\%(\ze+\|+\zs\)', 1)
```

**Comment by koron** [comment]
正規表現の基本を誤解しているかもしれません。

`\zs` 及び `\ze` はドコにでもマッチするのではなく、
**マッチした場合に** マッチの開始・終了位置をその場所に設定する、ように動作していそうです。

そうであるならば `\%(\ze+|+\zs\)` というパターンは `\(+\|+\)` と簡略化できます。
これは `+` に対しては常に前者(左側)のパターンしかヒットしていないことになります。

それを裏付ける証拠として `\ze+` だけで `split()` してみると、
以下のようにもともとのパターンと同じ結果なります。

``` viml
:echo split('a+b', '\ze+', 1)
['a', '', '+b']
```

> 期待する動作と違うように感じた

期待する動作が明示されていないので推測になりますが、
仮に `+` とそれ以外を分けたいということであれば、以下の様なパターンが使えるかもしれません。

``` viml
echo split('foo+bar', '\%([^+]\+\|+\)\zs', 1)
['foo', '+', 'bar', '']
```

**Comment by koron** [comment]
例示したパターンを簡単に解説しときますと、以下2つのパターンを合成したもの、となります。
- `[^+]\+\zs` : `+` を含まない文字列(1文字以上、複数文字可)の後ろで区切る
- `+\zs` : `+` (1文字) の後ろで区切る

**Comment by k-takata** [comment]
あるいは、戻り読みを組み合わせるか。

``` vim
echo split('a+b', '\%(+\@1<=\|\ze+\)', 1)
['a', '', '+', 'b']
```

`\zs` と戻り読みはほぼ同じように使えますが、全く同じという訳ではありません。

**Comment by machakann** [comment]
丁寧な解説をありがとうございます。

> マッチした場合に マッチの開始・終了位置をその場所に設定する、ように動作していそうです。

これで何とか飲み込めた気がします。頓珍漢なことを言っているかもしれないのですが、`\zs` と戻り読みのそれぞれを使ったパターンの違いについて聞かせてください。
1. `a\zsb`
2. `a\@1<=b`

1 のパターンでは文字列 `a` のマッチ位置を検索して文字列 `b` が続くか確認するのに対し、 2 のパターンでは文字列 `b` のマッチ位置を検索して `a` が先行するか確認している、という認識であっていますか？

**Comment by k-takata** [comment]
あっています。

**Comment by mattn** [comment]
余談ですが今回の様にデリミタも結果に出てくるような分割は、僕なら split を使わず matchlist を使いますね。

**Comment by machakann** [comment]
ありがとうございました。やりたかったことができそうです。
