### ISSUE TITLE
Ctrl-A/Ctrl-Xが文字コードによっては文字化けが発生する

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#920]
例えば`enc=cp932`、`set nrformats+=alpha`で`山1`の行頭で`<C-A>`すると`S1`になります。(期待値は`山2`)

Linuxの端末で確認する場合は以下の設定で起動します。

```
$ vim -Nu NONE --cmd "set enc=cp932 tenc=utf8" -c "set nf+=alpha"
```

**Comment by mattn** [comment]
Where is the patch?

> これが浪花のパチパチパッチや

期待

**Comment by h-east** [comment]
タイトルが「全角数字のインクリメント/デクリメントに対応していない」のを対応するようなニュアンスだったので、そうじゃなくって「全角文字が化けるケースがあるのを修正しますよ」的な文言に修正しました。

Patch is here.
https://gist.github.com/h-east/f03600a8b70c7aa10373ce798b7a1037

コードレビューお願いします。(使ってるmb関数これでいいのかとか、mb関数の使い方等)

**Comment by mattn** [comment]
いいと思います。

**Comment by h-east** [comment]
vim_dev ed.
https://groups.google.com/d/msg/vim_dev/6LtfyZw7NF4/3g9h6LDWJwAJ

**Comment by h-east** [comment]
patch 7.4.1948
https://github.com/vim/vim/commit/ad5ca9bc1e7145474adb082775a805f1731e9e37

> Would be nice to also have a test.  I'll include it anyway. 

テスト書きます。

**Comment by mattn** [comment]
速い

**Comment by h-east** [comment]
test追加。
patch 7.4.1954
https://github.com/vim/vim/commit/d388d2ac8bf8c770bf97dc406e99a20ba5104855
