### ISSUE TITLE
sleep 中の入力が getchar(0) で取れない (on Solaris)

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#921]
## 質問・報告の内容

Solaris 環境の `select(2)` は canonical モードでの入力を non-canonical モードで検出できないという挙動になっているようで、

``` vim
while 1
  let c = getchar(0)
  if c != 0
    break
  endif
  sleep 20m
endif
```

このようなコードにおいて、sleep 中の入力が `getchar(0)` で取れないため while から break できるタイミングが非常に限られてしまいます。

検証用
https://gist.github.com/ichizok/30fd969eb846848e5b548cfe99f9e515

```
$ gcc -o getch getch
$ ./getch
min = 1, time = 0

[0]>
[1]>
[0]>
...
```

linux や mac だと`[1]>` (canonical) でキー入力すると直後の `[0]>` (non-canonical) で検出されて終了しますが、solaris だと `[1]>` で入力しても直後の `[0]>` の `select()` で検出できません。
(`read()` するとそれまでの入力は全て取れるため、入力が捨てられているわけではない)
## Vimのバージョン

7.4.1964 (and prior)
## OSの種類
- Solaris 11
- OpenIndiana
- and maybe other SunOS distributions

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/fXpulibwlV0
報告しました。

**Comment by ichizok** [comment]
@saitoha さんのパッチの一部（TMODE_SLEEP で ICANON フラグを落とす部分）を適用することで改善できました。

**Comment by ichizok** [comment]
7.4.1972
https://github.com/vim/vim/commit/40de45664c20e7ca46a28a3f472202f90e47f8bf

**Comment by saitoha** [comment]
よかったです。
