### ISSUE TITLE
タブページ関連のコマンドと自動コマンドの組み合わせでVimが落ちたりカレントウィンドウが閉じられない

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#923]
### カレントウィンドウが閉じられないケース　

タブページが2つ以上ある時、QuitPreイベント発生時に下記8つのコマンドの内1つを実行すると、
カレントウィンドウが:quitで閉じられなくなりました。
- tabnext
- tablast
- tabprevious
- 1tabprevious
- tabdo echo 1
- tabedit

下記2つのコマンドはファイルを開いた時のみ再現します。
- tabfind sample.txt
- wincmd gf

**再現方法**

`vim -Nu NONE -S sample1.vim`

sample1.vim:

``` vim
tabedit
tabfirst

augroup sample
    autocmd!
    autocmd QuitPre <buffer> tabnext
augroup END

quit
```
### Vimが落ちるケース

BufUnloadイベントとBufDeleteイベントが発生する時、先ほど挙げた8つのコマンドのどれか1つを実行すると、Segmentation faultでVimが落ちます。
BufHidden、BufLeave、BufWipeoutを指定した場合は落ちません。
タブページが2つ以上ある時のみ再現します。

**再現方法**

`vim -Nu NONE -S sample2.vim`

sample2.vim:

``` vim
tabedit
tabfirst

augroup sample
    autocmd!
    autocmd BufUnload <buffer> tabnext
augroup END

quit
```

落ちた時の内容

```
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault
```
## Vimのバージョン

7.4.1979
## OSの種類
-   Linux
## OSのディストリ

Debian
## OSのバージョン

8.5

**Comment by h-east** [comment]
SEGV回避patch
https://gist.github.com/h-east/efb785851bb271c84e02c4c4bd3474b1

tabpageが2つの時に`:quit`出来ない件は仕様かと思います。
- `:quit` する。
- 現tabpageにwindowが1つの場合は別のtabpage&windowに移動
- autocmdで｀:tabnext`が呼ばれてquit対象のtabpage&windowに移動
- safetyチェック(https://github.com/vim/vim/blob/master/src/buffer.c#L602-L609) に引っかかって何もせずreturn

最後のtabpageで`:quit`可能な件についての説明は答えを探しましたがまだ見つけられていません。

**Comment by norio13** [comment]
patch適用後SEGVで落ちなくなりました。
`:quit` 出来ない件については仕様という事で承知しました。
的確で迅速なご対応に感謝致します。ありがとうございます。

**Comment by h-east** [comment]
> 最後のtabpageで:quit可能な件についての説明は答えを探しましたがまだ見つけられていません。

あぁ、`autocmd BufUnload <buffer> tabnext`だからその時のカレントバッファに対してしかautocmd登録されないんだ。だから2番めのtabpage(のwinのbuf)をカレントバッファにしてもautocmdは実行されないから普通にバッファ消せるんですね。

`autocmd BufUnload * tabnext`にしたらtabpageが2つの場合はどうやっても`:quit`でバッファ消せないことを確認しました。(`:bd`や`:bun`や`:bw`や`:qa`で消せる or 終了出来る)

すっきりした。時間掛かったけど:relaxed:

SEGV回避patchは来週中にtest追加してvim_devに投げる予定です。

**Comment by h-east** [comment]
Sent to vim_dev
https://groups.google.com/d/msg/vim_dev/QXIjomlK7p0/MlJwh4E3CgAJ

**Comment by h-east** [comment]
patch 7.4.2006
https://github.com/vim/vim/commit/30445cb6e94698d212ba866ef3e4022ac625540a

@norio13 issue登録ありがとうございました:+1:
