### ISSUE TITLE
filter() と map() を Funcref に対応させる

### ISSUE THREAD

**Issue by k-takata** [vim-jp/issues#924]
#905 からの派生です。

sort() は Funcref を渡せるのに、filter() と map() には Funcref を渡せず、統一性がない問題を修正しようというものです。（関連: #397）
lambda パッチから必要な部分を切り出して、個別に取り込んでもらおうというもくろみです。

現時点のパッチ:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/3182c79a4bbb47d70866753474fa5799385945e9/support-funcref-in-filter-and-map.patch?fileviewer=file-view-default

残課題:
- [x] テスト
- [x] ドキュメント

**Comment by k-takata** [comment]
v:val と v:key をどうやって関数に渡すかという仕様についてですが、現状の実装では、v:val と v:key も使えるが、関数の第一引数にも v:val が渡されるという仕様のようです。
これはこのままでも良いでしょうか？

私としては、どうも中途半端な気がします。関数の引数にも v:val と v:key の両方を渡すようにするか、あるいは逆に関数の引数では v:val も v:key も渡さないようにするか、どちらかにした方が統一されていると思います。

**Comment by k-takata** [comment]
なお、このパッチ単体では単に filter(), map(), sort() に統一性を持たせられるだけなので、あまりうれしくありません。lambdaも取り込まれて真価を発揮するものであり、lambdaを取り込んでもらうための布石と考えています。

**Comment by osyo-manga** [comment]
+1

> 現状の実装では、v:val と v:key も使えるが、

これって `Funcref` の関数内で `v:val` と `v:key` を使うという感じなんでしょうか？
そういう風な挙動なのであれば

> 私としては、どうも中途半端な気がします。関数の引数にも v:val と v:key の両方を渡すようにするか、あるいは逆に関数の引数では v:val も v:key も渡さないようにするか、どちらかにした方が統一されていると思います。

関数内で `v:val` や `v:key` に依存したくないので関数の引数として `v:val` や `v:key` （もしくは `[v:val, v:key]`）で受け取ったほうが柔軟性があると思います。

**Comment by k-takata** [comment]
> これって Funcref の関数内で v:val と v:key を使うという感じなんでしょうか？

そういう感じですね。
関数の引数に v:val だけでなく、v:key も渡すようにする場合、引数の順序はどうすべきですかね。

**Comment by osyo-manga** [comment]
> そういう感じですね。

なるほど、ありがとうございます。

> 関数の引数に v:val だけでなく、v:key も渡すようにする場合、引数の順序はどうすべきですかね。

んー `items()` だと `[v:key, v:val]` になってるので、既存の仕様に合わせるという意味では第一引数に `v:key`, 第二引数に `v:val` が自然かと思います。
リストの場合も `func(index, value)` という風に受け取れば `v:key` という名前の不自然さも改善されると思いますし。

**Comment by k-takata** [comment]
関数の引数として、値だけでなくキーも渡すように修正。引数は、キー、値の順。（`v:key`, `v:val` も引き続き使用可能。）
https://bitbucket.org/k_takata/vim-ktakata-mq/src/494a92ed90d505b834344485a9f2d6732c49e261/support-funcref-in-filter-and-map.patch?at=default&fileviewer=file-view-default

[ここの2行](https://bitbucket.org/k_takata/vim-ktakata-mq/src/494a92ed90d505b834344485a9f2d6732c49e261/support-funcref-in-filter-and-map.patch?at=default&fileviewer=file-view-default#support-funcref-in-filter-and-map.patch-157:158)、単純な値のコピーで問題ないのか、それとも `copy_tv()` を使うべきなのかよく分かっていません。

**Comment by k-takata** [comment]
ところで、テストはどのファイルに追加するのがいいでしょうか。

**Comment by osyo-manga** [comment]
@k-takata ++

**Comment by k-takata** [comment]
testは適当なファイルがなかったので、test_filter_map.vim を追加。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/f14545dd25d8fc5eda70be2fcf6b54475fcfd770/support-funcref-in-filter-and-map.patch?at=default&fileviewer=file-view-default

**Comment by k-takata** [comment]
放った。
https://groups.google.com/d/msg/vim_dev/nbvI429-1EE/8QkgOO3TCAAJ

**Comment by osyo-manga** [comment]
@k-takata ++

**Comment by k-takata** [comment]
7.4.1989
https://groups.google.com/d/msg/vim_dev/OxbsNhu_c5I/6olgkkXqCAAJ

**Comment by osyo-manga** [comment]
お疲れさまでした

**Comment by mattn** [comment]
おー！実は地味に嬉しい人いるんでは。
