### ISSUE TITLE
filter(), map() の第2引数が number だと SEGV する 

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#925]
## 質問・報告の内容

filter(), map() の第2引数が number だと SEGV します。

``` vim
call filter([0], 0)
```
## Vimのバージョン

7.4.1989 以降 (7.4.2000まで確認)
## 原因

https://github.com/vim/vim/blob/245a7cb/src/eval.c#L12054
https://github.com/vim/vim/blob/245a7cb/src/eval.c#L12073

expr の型を確認せずに `skipwhite()` を呼んでいます。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/edca7401330a988501993e170d1388e8
7.4.1989 以前と同様に `get_tv_string_buf_chk()` で `char_u *` に変換

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/AtvDEcjtYms
報告しました。

**Comment by k-takata** [comment]
修正ありがとうございます。取り込まれました。
7.4.2002
https://groups.google.com/d/topic/vim_dev/J1GemCb68rc/discussion
