### ISSUE TITLE
サポートを打切ったOS関連のキーワードをCソース、ドキュメント、同梱Vim scriptから削除する

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#927]
削除可能なdefine:
DOS16, DOS32, OS2, WIN16, DJGPP

削除可能なVim script内の判定
has("win16")
has("dos16")
has("dos32")
has("os2")

**Comment by h-east** [comment]
patch
https://gist.github.com/h-east/3ed23b1b15cb4d959cce70456433d68e

define値 `__EMX__`はOS/2用のものなのでこれも削除可能だけどまだ削除していません。

他に削除可能なキーワードあったら教えて下さい。

**Comment by k-takata** [comment]
`MSDOS` も要りません。

**Comment by h-east** [comment]
`__EMX__`関連消しました。

**Comment by k-takata** [comment]
`has("msdos")` も不要ですね。

**Comment by h-east** [comment]
`MSDOS`と`has("msdos")`を削除してもう vim_devに投げちゃった。
https://groups.google.com/d/msg/vim_dev/Jlcus0eC-tA/ObtueITOAAAJ

**Comment by h-east** [comment]
patch 7.4.2048
https://github.com/vim/vim/commit/a06ecab7a5159e744448ace731036f0dc5f87dd4
0x800ゲットだぜ:+1:

**Comment by h-east** [comment]
やらかしたでござる:cold_sweat: すいませんすいません
https://groups.google.com/d/msg/vim_dev/bYBY2By1KV0/s-NvOeKvAQAJ

**Comment by h-east** [comment]
patch 7.4.2054
https://github.com/vim/vim/commit/b2b050ab16565c117f0e7e411ffef3700d99203b
