### ISSUE TITLE
printf() の %d が 64bit 整数に対応していない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#928]
## 質問・報告の内容

`+num64` の環境にて、`printf()` の `%d` に 32bit では表現できない大きな整数を渡すと、正しく表示されません。

``` vim
:echo 100000000000000
100000000000000
:echo printf('%d', 100000000000000)
276447232
```
## Vimのバージョン

7.4.2025
## OSの種類/ディストリ/バージョン
-   Gentoo Linux

**Comment by koron** [comment]
format を内部的に `%ld` に書き換えないと、ダメでしょな…

もしくは渡すほうが、そうするってのもありかもですが。

**Comment by thinca** [comment]
`'%ld'` 試したら動きました。こういう仕様という感じですかね?
だとすると、help に記述があると良さそうです。私の見た限りだとなさそう。

**Comment by koron** [comment]
直観的には C の sprintf の仕様そのままなんだと思います…
一応、みておくか。

**Comment by koron** [comment]
あ、うそだ。 自前で実装しているわw これ確かにdocだけの問題っぽいですね。

**Comment by koron** [comment]
https://github.com/vim/vim/blob/79815f1ec77406f2f21a618c053e5793b597db7a/src/message.c#L4337-L4376 このあたりに関する説明がなさそう。

`%ld` だけじゃなく `%hd` ってのもあるように見えるが…

**Comment by k-takata** [comment]
Windowsだと、`%lld` じゃないと 64bit 整数は正しく表示できません。

**Comment by koron** [comment]
@k-takata なんか sprintf 相当 は runtime のものではなく、自前で実装しているように見えたんですが、それでも `%lld` である必要がありますか? (僕がなにか見落としてる?)

**Comment by k-takata** [comment]
完全な自前ではなく、半自前です。
https://github.com/vim/vim/blob/79815f1ec77406f2f21a618c053e5793b597db7a/src/message.c#L4469-L4508
この辺りを見れば分かりますが、vim_vsnprintf() では、一部処理を行ってから C の sprintf() に処理を渡しています。
`%l` はシステムの long 型、`%ll` は num64 が有効なら 64bit 型、無効なら long 型として扱います。

**Comment by koron** [comment]
ああ、翻訳してるんですね。

ならば `%lld` まで含めてキッチリドキュメントに書くべきですね。

**Comment by koron** [comment]
ここまでのまとめ: 実は `%hd`, `%ld`, `%lld` があるが、ドキュメントにないので書く必要がある。
意味は左から、 たぶん システムの ~~int~~ short型、システムのlong型、+num64ならば64bit型でそうじゃなければlong型。

**Comment by k-takata** [comment]
`%h` は short 型です。

**Comment by koron** [comment]
thanks 修正しました

**Comment by thinca** [comment]
ちょっと考えたんですが、様々な整数型が存在する C 言語に対して、Vim script で使える整数型は常に1つです。いちいち書き分けるのは面倒なだけであって、必要性も利便性もないかと思います。
書き分けるという意味だと常に `%lld` を使うという選択肢もあるかと思いますが、過去の Vim script の整数は常に 32bit であったのと、ドキュメントに `%d` の記載しかなかったため、基本的にみんな `%d` を使っています。今後は `%lld` を使おうと言うのはバッドノウハウにしかならない気がします。
なので、Vim script の `printf()` は、`%d` だけサポートして、あとは内側でよしなにやってくれると良いのではないかと思うのですが、どうでしょう?

**Comment by mattn** [comment]
個人的な意見だと %lld 常時でいいと思います。逆に %d じゃないと困る人の方が少ないと思います。

**Comment by k-takata** [comment]
その方がいいかもしれませんね。こんな感じで。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/cff160f8772260a7fa76ea63a4d7513a9e9c8f01/printf-num64.patch?fileviewer=file-view-default

**Comment by k-takata** [comment]
https://groups.google.com/d/topic/vim_dev/xuMvBxGSVK0/discussion

**Comment by k-takata** [comment]
あー、テストも追加すべきか。
https://groups.google.com/d/msg/vim_dev/xuMvBxGSVK0/Z7FJp7F-AAAJ

**Comment by thinca** [comment]
さすがすぎる :+1:

**Comment by k-takata** [comment]
タイトルを元に戻しました。

**Comment by k-takata** [comment]
7.4.2029
https://groups.google.com/d/topic/vim_dev/_HuijiVryFI/discussion

**Comment by k-takata** [comment]
しかし #161 の対応の時、printf() のことはすっかり忘れていましたｗ

**Comment by mattn** [comment]
速い
