### ISSUE TITLE
printf() に2進数表示できる変換指示子 %b が欲しい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#929]
## 提案の内容

[Vim 7.4.1027](https://github.com/vim/vim/commit/887c1fea4a114e7170091942d0446c8882701b5b) で、`'nrformats'` に `bin` が追加されました。実際には、Vim 全体で 2 進数に対するサポートが入ったような変更になっています。
であれば、`printf()` 関数に、2進数表示するための変換指示子 `%b` があっても良いのではないか、という提案です。

``` vim
:echo printf('%b', 10)
1010
```
## Vimのバージョン

7.4.2025
## その他

特別これがないと困るというわけではないです。
- [ ] 機能実装
- [ ] ドキュメント
- [ ] テスト

**Comment by koron** [comment]
フォーマッタは src/message.c の `vim_vsnprintf()` で自前で実装されているので、
腕慣らしにちょっと追加するのに向いていそう。

**Comment by thinca** [comment]
ひとまず TODO リストを足しました(やるとは言っていない)。

**Comment by koron** [comment]
他にも準備が必要かもだけど、 https://github.com/vim/vim/blob/79815f1ec77406f2f21a618c053e5793b597db7a/src/message.c#L4712 この行の前に `case 'b':` を追加すれば、そこで実装できるイメージ。

**Comment by k-takata** [comment]
> vim_vsnprintf() で自前で実装されているので、

あっちにも書きましたが（どっち？）、現状の vim_vsnprintf() は完全な自前実装ではなく、システムの sprintf() が使える部分はそれを使っています。
しかし、`%b` については完全に自前で実装する必要がありますね。

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/7acfdf77c9343afbb3ed828e1777f6ae
作りました

**Comment by k-takata** [comment]
`%08b` のようなフィールド幅指定やゼロパディングなどには対応していますか？

**Comment by ichizok** [comment]
> %08b のようなフィールド幅指定やゼロパディングなどには対応していますか？

対応しています。それらのテストを追加しました。

**Comment by ichizok** [comment]
alternate_form に対応してなかった... 後でやります。

**Comment by ichizok** [comment]
alternate_form 対応、テスト追加。

**Comment by k-takata** [comment]
良さそうですね。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/xvWbhFvkH0E
投げました。

**Comment by k-takata** [comment]
todo入りしていますので、閉じます。

> Patch to add %b to printf(). (Ozaki Kiichi, 2016 Aug 5)

**Comment by h-east** [comment]
patch 7.4.2221
https://github.com/vim/vim/commit/91984b9034d3b698459622be277d963e0c6df60e

**Comment by thinca** [comment]
ありがとうございました！
