### ISSUE TITLE
MinGWでのビルド時に`ARCH`を自動設定して欲しい

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#932]
MinGWを使ってのビルド方法 ページの改善提案
https://github.com/vim-jp/vim-jp.github.io/issues/216

↑ 上記から発展
「MinGWを使ってのビルド方法」ページは最後に`ARCH`の説明があるのでわかりにくいのでページの改善提案をしました。その流れの中で、 @k-takata さんが`ARCH`を自動設定するpatchを書いて取り込まれました:+1:
(ページの更新は後日実施します)

patch 7.4.2030
https://github.com/vim/vim/commit/e048539195e1c0a060cf41b39fca118130bdc151

patch 7.4.2032
https://github.com/vim/vim/commit/3e946fdc7b3639f84c96cd8a5d5b4b4b010f56ea

あと、下記の件がfixされればYeahです。
https://groups.google.com/d/topic/vim_dev/yer-4FsBZhc/discussion

**Comment by k-takata** [comment]
最後の件、MinGW-w64じゃない素のMinGWの環境で問題が起きていたようですが、そろそろ捨てたいｗ
（というか、素のMinGWを手元に残していないので検証ができない。）

**Comment by mattn** [comment]
素の MinGW とか良くやるなーという感想

**Comment by nocd5** [comment]
[TDM-GCC](http://tdm-gcc.tdragon.net/)も`mingw32`を返すので引っかかる人は割と多いかもしれませんね。
自分も最近までTDM-GCCでビルドしていたので…

**Comment by k-takata** [comment]
> TDM-GCCもmingw32を返す

mjd!?
TDM-GCCのMinGW-w64だと何を返すのだろう。

**Comment by nocd5** [comment]
64bitの方は`x86_64-w64-mingw32`なので
実際にビルドはしていませんが、今のpatchで問題ないかと思います。

**Comment by k-takata** [comment]
それなら良かったです。

**Comment by k-takata** [comment]
7.4.2034
https://groups.google.com/d/topic/vim_dev/y8eYZjYzoJ0/discussion
これでもう大丈夫なはず
