### ISSUE TITLE
自動コマンドからタブ操作とバッファ削除するとSEGVする

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#933]
## 質問・報告の内容

SEGVするコードを見つけたので報告します。
### サンプル1

`vim -Nu NONE -S sample1.vim`

``` vim
edit a.txt

augroup sample
    autocmd!
    autocmd BufUnload <buffer> tabfirst | 2bwipeout!
augroup END

edit b.txt
```

:bw!で再現します。:bun!と:bd!では再現しません。

**再現するイベント**
- BufUnload
- BufWinLeave

**再現しないイベント**
- BufDelete
- BufHidden
- BufLeave
- BufWipeout
### サンプル2

`vim -Nu NONE -S sample2.vim`

``` vim
setlocal buftype=nowrite

augroup sample
    autocmd!
    autocmd BufUnload <buffer> tabfirst | 2bwipeout
augroup END

normal! i1
edit a.txt

call feedkeys("\<CR>")
```

~~:bw!で再現します。:bun!と:bd!では再現しません。~~
:bwで再現します。:bunと:bdでは再現しません。

**再現するイベント**
- BufUnload
- BufDelete
- BufWinLeave

**再現しないイベント**
- BufHidden
- BufLeave
- BufWipeout
### サンプル3

`vim -Nu NONE -S sample3.vim`

``` vim
tabedit

augroup sample
    autocmd!
    autocmd BufUnload <buffer> tabfirst
augroup END

:%!ls
edit! a.txt
normal! gt
:%!ls

call feedkeys("\<CR>q::q\<CR>")
```

**再現するイベント**
- BufUnload
- BufDelete
- BufWinLeave

**再現しないイベント**
- BufHidden
- BufLeave
- BufWipeout
## Vimのバージョン

7.4.2038
## OSの種類/ディストリ/バージョン

Linux Debian 8.5 (jessie) 64bit

**Comment by mattn** [comment]
サンプル1、サンプル2は解決。サンプル3は以下のパッチをあてても(落ちはしないけど)本来見えちゃダメな E315 が出るけど、`curwin->w_buffer` が NULL というバッファ移動の途中経過を見せないためにも一度カレントバッファを設定した方が安全かと思いますね。

``` diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 7ec17b1..302d055 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -4389,6 +4389,11 @@ delbuf_msg(char_u *name)
        name == NULL ? (char_u *)"" : name);
     vim_free(name);
     au_new_curbuf.br_buf = NULL;
+
+# ifdef FEAT_WINDOWS
+    if (curwin->w_buffer == NULL)
+   enter_buffer(curbuf);
+# endif
 }
 #endif
```

このコードは buffer.c でもやられている手なのでそれほど悪い手ではないと思う。

**Comment by norio13** [comment]
patch作成してくださりありがとうございます。
私の環境ではpatch適用後もサンプル3でSEGVしました。
一瞬チラついてから落ちるのでE315や他のエラーが出たかどうか確認できておりません。

サンプル1とサンプル2についてはSEGVが出なくなりました。
ただ、タブを閉じるときにエラーが出たので、確認するためにタブを新規に作成して自動コマンドを設定したタブに戻って閉じる処理を加えるとSEGVが出ました。
再現するのはBufWinLeaveイベントを指定した時のみです。

sample1a.vim:

``` vim
edit a.txt

augroup sample
    autocmd!
    autocmd BufWinLeave <buffer> tabfirst | 2bw!
augroup END

edit b.txt
tabedit
tabfirst
quit
```

sample2a.vim:

``` vim
setlocal buftype=nowrite

augroup sample
    autocmd!
    autocmd BufWinLeave <buffer> tabfirst | 2bw
augroup END

normal! i1
edit a.txt

call feedkeys("\<CR>")
tabedit
tabfirst
quit
```

**Comment by h-east** [comment]
まっつんさんのpatchに変更を加えました。
`sample1a.vim`, `sample2a.vim`でも落ちなくなりました。
https://gist.github.com/h-east/9f2322ec5225f54d61071d040e1351a5

残るは`sample3.vim`！

**Comment by mattn** [comment]
そう、sample3 がなかなか手ごわい。

**Comment by h-east** [comment]
patch更新。このissueで報告されている問題すべて解決したと思います。
https://gist.github.com/h-east/9f2322ec5225f54d61071d040e1351a5

`sample3.vim`はbuf解放時のautocommand処理でカレントタブページが移動していたらエラーにするようにしました。
たぶん、他の部分も見なおして修正が必要な箇所を直さないといけないと思いますが、まずはお試しを。

**Comment by h-east** [comment]
あぅ、`make test`で10ほどエラーになってる。

**Comment by h-east** [comment]
Fixed:+1:

**Comment by norio13** [comment]
ご対応ありがとうございます。
Vim 7.4.2121にpatchを適用して確認してみた所、サンプル3でBufWinLeaveイベントを指定した場合のみSEGVで落ちました。

**Comment by h-east** [comment]
@norio13 確認ありがとうございます。patch更新しました。(Rev. 4)

**Comment by norio13** [comment]
@h-east patch(Rev.4)適用でSEGVしなくなりました。
ありがとうございます。

**Comment by h-east** [comment]
このpatchですが、autocommandでカレントタブページが移動したらその時点でメッセージも出さずに処理を終わらせているのでよろしくない気がしています。
っと言っても現状でも対象バッファが変更になったらメッセージ無しで処理やめちゃうのでこのままでいいかな？
SEGVするよりはマシってことで。

**Comment by h-east** [comment]
patch 7.4.2312 by Bram
https://github.com/vim/vim/commit/5a49789a9b1f6447aeafbbbdd5b235dd10c471d5
このpatchでsample3.vimがSEGVしなくなったのは確認しました。

残念ながらsample1.vimとsample2.vimは現時点の最新(7.4.2312)でもSEGVします。
まずはtest_autocmd.vimにテスト追加したんだけど落ちない。。単独(`vim -Nu NONE -S sample?.vim`)でやると落ちる。。
もうちょい調べます。

**Comment by h-east** [comment]
patch前のtestでSEGVしないけど、諦めてvim_devに投げました。
https://groups.google.com/d/msg/vim_dev/Gao-PqyS6Tk/IRn1pC_uCQAJ

**Comment by norio13** [comment]
調査と報告ありがとうございます。

vim 7.4.2322
sample3.vimでBufWinLeaveを指定すると落ちました。

**Comment by h-east** [comment]
@norio13 7.4.2323 + 私が投げたpatchだと落ちないです。
「このケースのSEGVも直るよ」と追加報告しておきます。

**Comment by norio13** [comment]
@h-east sample1.vimとsample2.vimの分のみ報告されたのだと勝手に勘違いしてました。
patch適用して全部修正されているのを確認できました。
大変失礼致しました。

**Comment by h-east** [comment]
patch 7.4.2324
https://github.com/vim/vim/commit/e0ab94e7123ca7855f45919114d948ef2bc1e8c3

patch 7.4.2328
https://github.com/vim/vim/commit/f9e687e0681a250e1549ab27b6c7ef2c500395e3

# 

@norio13 説明不足でした。以前作成したpatch(sample1～3全対応)がpatch 7.4.2312(sample3が直ったと思われるもの)とconflictを起こしたので手動でマージして新しくpatchを作成しました。なのでごちゃ混ぜです。

**Comment by h-east** [comment]
7.4.2330で全てのscript(sample1～3, sample1a, sample2a)がSEGVしないことを確認しました。
閉じます。ありがとうございました。
