### ISSUE TITLE
テストをcleanしたあとにファイルが残る

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#934]
## 質問・報告の内容

src/testdir で `nmake -f Make_dos.mak win32 clean` 後に channellog というファイルが残った。
`clean` で消えるべき。
## Vimのバージョン

7.4.2046
## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit (10.0.10586) + MSVC10
## 使用している or 関係していそうなプラグイン

nothing
## その他

clean に足すだけだが、一応いつ作られるファイルなのかと、他のプラットフォームではどうなってるのかを確認したほうが良いかも。

**Comment by k-takata** [comment]
類似: #890 （あっちは、cleanで消えるはずですが。）

> いつ作られるファイルなのか

test_channel.vim の最後のこれのせいですね。

``` vim
" Uncomment this to see what happens, output is in src/testdir/channellog.
 call ch_logfile('channellog', 'w')
```

**Comment by koron** [comment]
うへw

**Comment by k-takata** [comment]
7.4.2039 で有効化されていますね。意図的なものか、ただのミスかは分かりませんが。（ミスかな？）

**Comment by k-takata** [comment]
https://groups.google.com/d/msg/vim_dev/__JdUUt1kf8/JqHltVSoAwAJ

**Comment by k-takata** [comment]
7.4.2093
https://groups.google.com/d/msg/vim_dev/pu4CTlyAl6w/7gkPeEbPAwAJ
