### ISSUE TITLE
'>' を dict の key にすると E125 エラーになる

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#935]
## 質問・報告の内容

`>` から始まる文字列を dict の key にすると `E125: Illegal argument` エラーが出ます。

`vim -Nu NONE`

```
:let x = {'>' : ''}
E125: Illegal argument: '>' : ''}
E115: Missing quote: ' : ''}
E15: Invalid expression: {'>' : ''}
```
## Vimのバージョン

7.4.2044~

**Comment by k-takata** [comment]
すんません、すんません。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/1aa2c4decbdb6091bc35380ed4f42a7e5b9bc7e2/fix-7.4.2044.patch?at=default&fileviewer=file-view-default
これで直りそうな気はしますが、本当にこれで良いかは未確認です。

**Comment by ichizok** [comment]
ありがとうございます。表題のケースが直ったことを確認しました。

**Comment by k-takata** [comment]
こっちの方がよさそう。
https://bitbucket.org/k_takata/vim-ktakata-mq/src/1e32739d0627f2b696c77433aee2b047b13fdb6c/fix-7.4.2044.patch?fileviewer=file-view-default
`get_function_args()` を関数として切り出す際に、エラーチェックが1個抜けていました。

**Comment by k-takata** [comment]
https://groups.google.com/d/topic/vim_dev/-aBR_0mI02U/discussion

**Comment by k-takata** [comment]
7.4.2076
https://groups.google.com/d/topic/vim_dev/AjkTay2aRc4/discussion
