### ISSUE TITLE
printf() に変換指示子 %v を追加する

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#936]
## 提案の内容

https://gist.github.com/ichizok/c1ad7759d7a0a0734fb02f5a4d37445c

`printf()` の変換指示子として、任意の型を取れる `%v` (と `%V`) を追加します。
このパッチでは `echo_string()` で文字列への変換を行っており、`:echo` の表示と同じ文字列になります。

```
:echo printf('%v', [0, 1, 2, 3])
[0, 1, 2, 3]
:echo printf('%v', {'str' : 'abcdef', 'num' : 123, 'pt' : function('printf', ['%%'])})
{'str': 'abcdef', 'num': 123, 'pt': function('printf', ['%%'])}
:echo printf('%v', function('str2nr'))
str2nr
```

元ネタは golang の `fmt.Printf()` です。
## TODO
- [x] 機能実装
- [x] テスト
- [x] ドキュメント

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/RSBn9aLBsi0

**Comment by k-takata** [comment]
> Well, since currently this produces an error, we could just convert to a
> string when using "%s".

"%s" が使われたときに引数が文字列ではなかったら、勝手に文字列に変換してしまえばいいのでは、ということですかね？

**Comment by ichizok** [comment]
それも考えたんですが、`%s` の意味が変わるのが気になったのでした。
機能的には `%s` でいいと言われればその通りなんですが。

というか、Vim script の関数は引数の型がわかるので、変換指定子を使い分けること自体が冗長ではあるんですよね。
必要なのは引数のプレースホルダ（or 文字列に直接埋め込む）と表示形式（n進表示、truncation、padding など）であって。

**Comment by k-takata** [comment]
> 必要なのは引数のプレースホルダ（or 文字列に直接埋め込む）と表示形式（n進表示、truncation、padding など）であって。

ですね。なので、2進数表示も早く出しませんか。

**Comment by k-takata** [comment]
%v ではなく、%s でいろいろ出せるようにしたパッチの方が todo 入りしています。閉じます。

> Patch to make printf() convert to string for %s items. (Ken Takata, 2016 Aug
> 1)

**Comment by h-east** [comment]
「%s でいろいろ出せるようにしたパッチの方」が取り込まれました:+1:
patch 7.4.2220
https://github.com/vim/vim/commit/e5a8f35b4286135f3469f3b00a6c2220553d9658
