### ISSUE TITLE
php で一部のネストしたインデントが正しく行なわれない

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/issues#938]
## 質問・報告の内容

indent/php.vim が読み込まれた状態で以下のインデントが正しく行なわれていないように見えます。

``` php
<?php

if (count([
  1,
  2,
  3,
  4,
])) {
expr;   // not indented
}
```

`expr;` の部分がインデントされません。また `count()` 内の配列の要素も本来はあと 1 レベル深いような気がします。
## Vimのバージョン
- MacVim kaoriya 7.4.1655
- 7.4.1416
## OSの種類/ディストリ/バージョン
-   OS X El Capitan (MacVim)
-   Amazon Linux 2015.09
## 使用している or 関係していそうなプラグイン

indent/php.vim

**Comment by h-east** [comment]
@0xBADDCAFE こちらで反応がなさそうなら、`indent/php.vim`の冒頭に記載の`GitHub`URLに報告した方が良いかもしれません。:cat2::dash:

**Comment by 0xBADDCAFE** [comment]
おっと、確かにそうですね。見てみることにします、ありがとうございます。

**Comment by 0xBADDCAFE** [comment]
https://github.com/2072/PHP-Indenting-for-VIm/issues/49
修正されたようです。こちらの close のタイミングは本体の runtime に取り込まれてからでしょうか。

**Comment by h-east** [comment]
@0xBADDCAFE 
> こちらの close のタイミングは本体の runtime に取り込まれてからでしょうか。

(基本的には)そうです。

**Comment by h-east** [comment]
お願いしたらPR出してくれた:+1:
https://groups.google.com/d/msg/vim_dev/wuCOh-xRePw/ijUf6p1_EAAJ

**Comment by h-east** [comment]
8.0.0517の直前のruntimeファイル更新commitで入りました:ok_hand:
https://github.com/vim/vim/commit/e0720cbf63eb3045be8d965e3182c0c392c7b5e9#diff-9e960cf7c450293f34eac61702755b5e

@0xBADDCAFE Thanks:+1:
