### ISSUE TITLE
matchaddpos() が 1 列余分に強調表示する

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#939]
matchaddpos() ですが、指定した列に文字がない場合に 1 列余分に強調表示してしまいます。
たとえば、12345 の行に、
matchaddpos('Search', [[1, 6]])
とすると、文字のない 6 列目が強調表示されます。
matchaddpos('Search', [[1, 7]])
とすると、どこも強調表示されません。
matchaddpos('Search', [[1, 5]])
として 5 を強調表示し、先頭の 1 を削除すると 5 の後が強調表示されたまま残り、
続いて 2 を削除すると消えます。
また空行に、
matchaddpos('Search', [[1]])
とすると、1 列目が強調表示されます。
ただしその行にカーソルがあれば表示されないこともあります。

さらに、1 列余分に強調表示されているときに set cursorline とすると、
その列ともう一つ先の列の 2 列だけは cursorline で表示されません。

7.4.2136 gvim、7.4.1016 vim (Windows) で再現します。

これは仕様ではないですよね?

**Comment by thinca** [comment]
仕様かどうかはわかりませんが、改行にマッチしているのではないでしょうか?
通常の検索で `\n` を検索すると、各行の最後の文字の後ろがハイライトされます。

**Comment by rickhowe** [comment]
matchaddpos('Search', [[1, 5, 2]])
だと 5 列目しか強調表示されないので、改行にはマッチしていないようです。不思議です。

**Comment by rickhowe** [comment]
matchaddpos('Search', [[1, 5, 2]])
だと 5 列目しか強調表示されないので、改行にはマッチしていないようです。不思議です。

**Comment by h-east** [comment]
@rickhowe issue登録ありがとうございます。

仰るとおり、私も`matchaddpos()`の`位置`指定によるhighlightは文字のある部分だけを対象にした方が良いと思いました。
修正patchを書いたので確認をお願いします。
https://gist.github.com/h-east/37b5bb84fd7e4a572fa052cd18689c64

(`/`や`matchadd()`の`パターン`指定によるhighlightは現状の挙動のままで、`matchaddpos()`のhighlightの挙動だけを変更したつもりです)

**Comment by h-east** [comment]
あーっ。

```
$ vim -Nu NONE -i NONE -c "syntax on" -c "set hls" -c "call setline(1, '12345')"
```

で

```
12345
```

なバッファに対して以下の2コマンドを実行すると、'5'の後ろが`Error`色でhighlightされちゃってますね。

```
/\n
:echo matchaddpos('Error', [[1,6]])
```

**Comment by h-east** [comment]
patch更新しました。(rev. 4)
上記の件を修正しました。

**Comment by rickhowe** [comment]
確認しました。文字がある部分だけ強調表示されてますね。どうもありがとうございました。

**Comment by h-east** [comment]
本issueのpatchを送る前準備として、old style test`test63.{in,ok}` を new style test `test_match.vim`に書き換え&`test_matchstrpos.vim`も統合。
https://groups.google.com/d/msg/vim_dev/hLTFRrzQYJ8/KsSqBk0DAQAJ

**Comment by h-east** [comment]
上記test変更patchが取り込まれました。
patch 7.4.2163
https://github.com/vim/vim/commit/d76a0c15f8bdbc901015879177fd5076d34c7a06

そして、本issueのpatchを送りました。
https://groups.google.com/d/msg/vim_dev/E679fe77wWI/CVrn0rkOAQAJ

正直、patchが取り込まれるかどうかは分かりません。Bram氏次第です。祈りましょう:pray:

**Comment by h-east** [comment]
TODOリスト入りしたので閉じます。
https://github.com/vim/vim/commit/0952131376a517fc12dc5ae908a97018b4ee23f0#diff-38d7929bd26d74d92ceddf984bbfc8dbR177

> Patch to make matchaddpos() not highlight the character after the line.
> (Hirohito Higashi, 2016 Aug 7)

**Comment by h-east** [comment]
patch 7.4.2217
https://github.com/vim/vim/commit/4f416e41243ca151b95d39d81ce23d00b1484755
