### ISSUE TITLE
相対行表示にするとカーソルの表示位置がずれる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#94]
詳細な条件があるので、あとで教えてもらえる約束です。

ujihisa.vim#2 で報告がありました。

**Comment by koron** [comment]
以下条件。
- MacOSXのコンソール
- tmux
- zsh
- CUI MacVim
- relativenumber を設定
- 大量のハイライト定義

という状況で発生。

**Comment by jbking** [comment]
補足です。

:version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov 11 2011 06:30:10)
MacOS X (unix) 版
適用済パッチ: 1-353

tmux + zsh (不具合発生)
zshのみ(不具合発生せず)

**Comment by koron** [comment]
おそらくカーソルを表示したまま動かしてる場所がある。
で間にレイヤーがいくつも入って遅延すると発生するっぽい。

と、推測。ネットワークが遅いサーバにおけばtmuxとか挟まず同じことが起こせるかも。

**Comment by h-east** [comment]
こちらにも貼っておきます。(まだ解析途中です)
[VimのソースコードをVimで解析しよう(Part1-1)](http://d.hatena.ne.jp/h_east/20111230)

**Comment by h-east** [comment]
@jbking ちょっと時間経ってますがいくつか確認させてください。
・`set lz?` の結果を教えて下さい。
・再現率はどれくらいでしょうか？ 頻繁に発生する感じでしょうか？
・再現時のキー操作手順を教えて下さい。(2～3パターン)

**Comment by jbking** [comment]
> set lz?

nolazyredraw

> 再現率

1000行オーバーくらいの大きいソースコードで、シンタックスハイライトと折り畳みが効いているとき、100%。

> 操作手順

jやkを押しっぱなしで行移動しているとき。

**Comment by h-east** [comment]
@jbking ありがとうございます。
うーん、現象が再現出来ていないのでお手数ですがもう少し情報をください。
・`:source $VIMRUNTIME/bugreport.vim` を実行して、作成された bugreport.txt ファイルをgist等にコピペしてURLを貼って頂けないでしょうか？
・現象発生時の編集ファイル名。(可能であれば内容をgistにコピペお願いします)
・折り畳みの設定は何かプラグインをお使いでしょうか？
・現象発生後に `:syntax off` とした後でも現象は起きますでしょうか？

**Comment by mattn** [comment]
@jbking お忙しいところ申し訳ないですが↑の件、お願いします。

**Comment by drakontia** [comment]
相対行表示しなくても、開けた瞬間から表示がずれていて
少し似たような状況かと思い、何かのお役に立てればと
bugreportの結果を貼っておきます。

https://gist.github.com/2481326

**Comment by h-east** [comment]
@drakontia ありがとうございます！
お手数ですが発生時の画面キャプチャ画像とオープンしたファイルの内容を頂けると助かります。

あと、(可能でしたら)新しめのバージョンのVimで再現するか確認してもらえると更に助かります。
お願いだらけですがよろしくです。

**Comment by drakontia** [comment]
発生時の状況はこんな感じです。
http://www.flickr.com/photos/daisuke_miura/6963679752
ファイルはどれというより、どれでもなってしまいます。

vimのバージョンあげるのは、夜までお待ちを。

**Comment by mattn** [comment]
![](http://farm8.staticflickr.com/7125/6963679752_1baee6e8e4.jpg)

**Comment by drakontia** [comment]
yum cronしかけているので、vimは随時最新でした。
MacのTerminalからsshでCentOSにつないでいるのですが、
Terminalでログをとるためにscriptコマンドを実行しています。
これが原因かとおもい、一度Terminalを再起動したところ、
正常に動作するようになってしまいました。。。

**Comment by h-east** [comment]
@drakontia 了解です。また何かありましたらよろしくお願いします。

**Comment by mattn** [comment]
そもそも

> tmux + zsh (不具合発生)
> zshのみ(不具合発生せず)

という時点で、エスケープシーケンスを投げたvimの責任では無い気がする。もしかして tmux+zsh と zshのみ の場合とで $TERM が違う？

**Comment by h-east** [comment]
`relativenumber` の場合
1. (ユーザが)カーソル移動
2. 各ウィンドウの各行データの更新処理(カーソル移動により`relativenumber` 表示データ部分を更新する必要がある)
3. 各ウィンドウの描画処理
4. カーソル描画処理

で 2.や3.が処理されずに4.が処理されるケースがあるのかもしれないと思ってます。
質素Vim状態だと起きないがゴージャスVim(foldとhighlightingが富豪的かつtmux)で発生する感じ。

情報が寄せられたら追っかけてみます。それまでは放置。

**Comment by koron** [comment]
tmuxの代わりにscreen使っても再現させられるのかしら? それ次第で身の振り方変えて良さそう。

**Comment by mattn** [comment]
> tmuxの代わりにscreen使っても再現させられるのかしら? それ次第で身の振り方変えて良さそう。

+1

↑のキャプチャを見る限り、最右端とその後続行で折り返しが見られます。端末によって最右端で文字を出力した場合に次のカーソル位置がどうなるかは端末によって異なったという記憶があります。
（むかーしむかしtelnetを作った程度の知識しかないですが http://mattn.kaoriya.net/tmp/sTelNet.c.txt)

**Comment by h-east** [comment]
drakontiaさんのはVim関係ない気がします。たぶん。

**Comment by mattn** [comment]
まぁ 100% 再現環境がないとつらいすな

**Comment by h-east** [comment]
追加情報が寄せられる気配がないので一旦閉じます。
情報来たら再オープンして対応します。

**Comment by h-east** [comment]
ちょっと関係ありそうなので貼っときます。
Patch 7.4.285
Problem:    When 'relativenumber' is set and deleting lines or undoing that, 
            line numbers are not always updated. (Robert Arkwright) 
https://groups.google.com/d/msg/vim_dev/GaudU36xp9E/oBORRYXFnOgJ

**Comment by koron** [comment]
まとめ

特定の状況で発生する問題の報告。
再現条件を作れず本質をつかめない状態。
その後、関係しそうなパッチもあったが…

いったん backlog に入れますが
このまま2015年半ばまで、追加報告がなければ worksforme に変更で良いでしょう。

**Comment by koron** [comment]
設定した期限を大きく超えて、似たような事例も追加報告もないので、
backlog から worksforme へ振り替えました。
