### ISSUE TITLE
matchaddpos() が 1 列余分に強調表示する

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#940]
(すいません、間違ってクローズしてしまいましたのでもう一度質問させてください)

matchaddpos() ですが、指定した列に文字がない場合に 1 列余分に強調表示してしまいます。

たとえば、12345 の行に、
matchaddpos('Search', [[1, 6]])
とすると、文字のない 6 列目が強調表示されます。
matchaddpos('Search', [[1, 7]])
とすると、どこも強調表示されません。
matchaddpos('Search', [[1, 5]])
として 5 を強調表示し、先頭の 1 を削除すると 5 の後が強調表示されたまま残り、
 続いて 2 を削除すると消えます。
また空行に、
matchaddpos('Search', [[1]])
とすると、1 列目が強調表示されます。
ただしその行にカーソルがあれば表示されないこともあります。

さらに、1 列余分に強調表示されているときに set cursorline とすると、
その列ともう一つ先の列の 2 列だけは cursorline で表示されません。

7.4.2136 gvim、7.4.1016 vim (Windows) で再現します。

これは仕様ではないですよね?

**Comment by thinca** [comment]
間違って閉じたのなら Reopen で再開できますよー。

**Comment by k-takata** [comment]
#939 をreopenしておきましたので、こちらは閉じます。
