### ISSUE TITLE
set go-=mT が効かないことがある

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#942]
## 質問・報告の内容

`gvim -u NONE` で起動した直後に `:set go-=mT` が効かない。

個別に `:set go-=m` (メニュー非表示) や `:set go-=T` (ツールバー非表示) をした時には成功する。

また一度 `:set go+=mT` したあとならば `:set go-=mT` が効く。
## Vimのバージョン

gvim for windows 7.4.1944 and 2046 (+kaoriya)

(他の版では試してない)
## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit (10.0.10586)
## 使用している or 関係していそうなプラグイン

とくになし
## その他

発端:

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">vim (+kaoriya gvim)で set go-=mT はできないんやね。個別指定したらいけた。と思ったら、set go+=mT した後なら set go-=mT でいけた。まあ、だからなんだ、という話なんですけども。</p>&mdash; tAkihiko (@ATA911) <a href="https://twitter.com/ATA911/status/760299404582490112">2016年8月2日</a></blockquote>

まだ +kaoriya パッチありの状態でしか試していない。

**Comment by koron** [comment]
-kaoriya な gvim for Win 7.4.2149 でも発生することを確認した。

**Comment by koron** [comment]
起動直後は `go=egmrLtT` となってる。これが `:set go+=mT` すると `go=egrLtmT` になる。

…つまり `:set go-=mT` は `go` 内から厳密な部分文字列 `mT` を消すにすぎないってこと?

**Comment by koron** [comment]
`:he :set-=` には以下のように書いてある。 ([日本語訳](http://vim-jp.org/vimdoc-ja/options.html#:set-=))

> When the option is a list of flags, {value} must be
> exactly as they appear in the option.  Remove flags
> one by one to avoid problems.

なので仕様ってことで FA で良いだろうか…

**Comment by koron** [comment]
仕様とするか、何か対策するか、要検討。

**Comment by machakann** [comment]
いちおう、`:help add-option-flags` に関係する記述がありますね。

> Note フラグは1個ずつ追加したり取り除いたりするよう注意。オプション
> 'guioptions' が "ab" という値であるとき、"set guioptions-=ba" は機能しない。な
> ぜなら、"ba" という文字列は現れていないからである。

**Comment by koron** [comment]
:+1: 何か対策する
:-1: 仕様を受け入れ、何もしない

vote ｵﾅｼｬｽ!

(個人的には :-1: で良い)

**Comment by k-takata** [comment]
> 起動直後は go=egmrLtT となってる。これが :set go+=mT すると go=egrLtmT になる。

+= で足すとすでにあるものも含めて末尾に移動するのは、そういう仕様なんですかね？

**Comment by koron** [comment]
[`:help :set+=`](http://vim-jp.org/vimdoc-ja/options.html#:set+=) より

> If the option is a list of flags, superfluous flags
> are removed.  When adding a flag that was already
> present the option value doesn't change.

微妙w

**Comment by koron** [comment]
:-1: が優勢ということで wontfix で閉じます。
