### ISSUE TITLE
setlocal errorformatで値を設定してからエラーを取得すると結果がおかしくなる

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#945]
## 質問・報告の内容

setlocalでerrorformatの値を設定後、特定のコマンドでエラーを取得すると無駄な部分も拾ってきてしまいました。
setで値を指定した場合は問題ありません。

sample.vim:

``` vim
let errlist = [
            \ 'sample.vim:1:1:a',
            \ 'sample.vim:xxxxx',
            \ ]

setlocal efm=%f:%l:%c:%m,%-G%.%#
cexpr errlist
cwindow
```

Vim起動

```
vim -Nu NONE -S sample.vim
```

QuickFixリストまたはロケーションリストの内容

```
sample.vim|1 col 1| a
|| sample.vim:xxxxx
```

setでerrorformatの値を設定した場合のQuickFixリストまたはロケーションリストの内容

```
sample.vim|1 col 1| a
```

おかしくなるコマンド
- cbuffer
- lbuffer
- cgetbuffer
- lgetbuffer
- caddbuffer
- laddbuffer
- cexpr
- lexpr
- cgetexpr
- lgetexpr
- caddexpr
- laddexpr

下記の6コマンドでは問題ありません。
- cfile
- lfile
- cgetfile
- lgetfile
- caddfile
- laddfile
## Vimのバージョン

7.4.2205
## OSの種類/ディストリ/バージョン

Linux Debian jessie 64bit

**Comment by h-east** [comment]
以下の3つのコマンドで試してみましたが、ちゃんとローカルの`efm`オプション値を参照しているようです。おそらく`l*buffer`も同様かと思われます。再度確認していただけますでしょうか。
- cbuffer
- cgetbuffer
- caddbuffer

以下のコマンドは`:h :cexpr`に`efm`のグローバル値を使用すると明記されていますので仕様ですね。`{expr}`はVim scriptの変数等ですので、バッファに関係ないということで常にグローバル値を使用するのだと思います。
- cexpr
- lexpr
- cgetexpr
- lgetexpr
- caddexpr
- laddexpr

**Comment by norio13** [comment]
`*expr` についてはヘルプをよく確認しておりませんでした。
`*buffer` について1件質問させてください。

error.txt:

```
sample1.vim:1:1:a
sample1.vim:xxxxx 
```

sample1.vim:

```
set errorformat=
setlocal errorformat=%f:%l:%c:%m,%-G%.%#
cbuffer
cwindow
```

`vim -Nu NONE -S sample1.vim error.txt`

sample2.vim:

```
set efm=
setlocal efm=%f:%l:%c:%m,%-G%.%#
tabedit error.txt
tabfirst
cbuffer 2
cwindow
```

`vim -Nu NONE -S sample2.vim`

sample1.vimのようにしたら`efm`のローカル値が使われましたが、
sample2.vimの場合は、カレントバッファの`efm`のローカル値が使われません。
`cbuffer` で指定したバッファの`efm`のローカル値が使われているのですがこれは仕様でしょうか？

**Comment by h-east** [comment]
> sample1.vimのようにしたら efm のローカル値が使われましたが、
>  sample2.vimの場合は、カレントバッファの efm のローカル値が使われません。
>  cbuffer  で指定したバッファの efm のローカル値が使われているのですがこれは仕様でしょうか？

cbuffer  で指定したバッファの efm のローカル値が使われるのが仕様だと思います。
もし、(指定したバッファではなく)カレントバッファの efm のローカル値が使われるとなるともっと混乱する気がしますがいかがでしょうか？

**Comment by norio13** [comment]
言われてみると納得しました。
現状の動作が仕様であることも理解しました。
いつもありがとうございます。
issueを閉じます。
