### ISSUE TITLE
:tabで[count]に$などの記号を指定できない

### ISSUE THREAD

**Issue by tsukkee** [vim-jp/issues#946]
## 質問・報告の内容

:tabeや:tabnは[count]として".", "+", "-", "$"といった記号を指定できるが、:tabではできない。
## Vimのバージョン

7.4.2196
(:tabe/:tabnの[count]に記号を指定できるようになったバージョン以降全て)
## OSの種類/ディストリ/バージョン
- OS X El Capitan
- Windows 7 Pro 64bit
- (おそらく全OS)
## 使用している or 関係していそうなプラグイン

特になし
## その他

@h-east さんに誘導して頂きました。
https://twitter.com/h_east/status/765524048474312704

**Comment by h-east** [comment]
@tsukkee issue登録ありがとうございます:+1:

patchです。確認をお願いします。
問題なさそうならtest追加してvim_devに投げます。
https://gist.github.com/h-east/e9f05064289d973bea1f1b0b513e2c0b

**Comment by h-east** [comment]
以下の指定が出来るようになります。

```
:$tab help gt                                " 最後に追加
:+tab help \a                               " 相対指定
:+1tab help \a                              " 相対指定 (上と同じ意味)
:-tab help \a                                " 相対指定 (`:-1tab help \a` と同じ)
:-2tab help \A                              " 相対指定
```

また、`:5tab help gt`はタブが5つない場合はエラー`E16`になるようになっています。

**Comment by tsukkee** [comment]
どうもありがとうございます。早速試しました。
少なくともOS X El Capitan上のVim 7.4.2217 + 上記patchでは期待どおり動作しています！

なお、Windows環境は職場にしかなく、Vimをビルドできる環境にないので、
すみませんが、報告しておきながら動作確認はできそうにありません。

**Comment by h-east** [comment]
本題のpatchを送る前準備として関連するテスト`test62.{in,ok}`がOld styleでしたのでNew styleに書き換えたpatchを送りました。
[patch] test62.{in,ok} convert to the new style test `test_tabpage.vim`
https://groups.google.com/d/msg/vim_dev/AWbIA4KiPFw/YVd8fS-NBAAJ

@tsukkee 確認ありがとうございます:+1:
(今回は私が急かしちゃった形になってしまったかもしれません:bow:、)OSS活動は空いた時間に出来ることを出来る範囲でやっていただけるだけで十分有難いです。OS Xでの動作確認だけでも十分でございます。

**Comment by h-east** [comment]
テスト更新patchが取り込まれました。
patch 7.4.2227
https://github.com/vim/vim/commit/1381d791478ee77c8368b89a3d4954316bf839b5

そして、本題のpatchをvim_devに送付しました。
https://groups.google.com/d/msg/vim_dev/4xotxJjG7io/a_E6ATmsBQAJ

**Comment by h-east** [comment]
patch 7.4.2237
https://github.com/vim/vim/commit/9b7f8ce9eb3cb704f8cc14ab659bf86b1d6dc13c
