### ISSUE TITLE
タグジャンプ候補の表示後にヘルプが正常に開けない場合がある

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/issues#949]
## 質問・報告の内容

前提: 複数候補が出るタグを含んだタグファイルが用意されている
1. `vim -u NONE -N` で起動
2. `<C-w>g}` でタグジャンプ候補を表示
3. `<Esc>` で一覧を抜ける
4. `:h tag` 等でヘルプを表示させる

結果: 空のバッファ、ヘルプを表示したプレビューウィンドウ、が新規に開かれる。
## Vimのバージョン
- 7.4.160 (CentOS)
- MacVim kaoriya 7.4.2196
## OSの種類/ディストリ/バージョン
-  CentOS Linux 7 (Core)
-  OS X 10.11.6 (15G31)

**Comment by 0xBADDCAFE** [comment]
post した後に気付いたのですが、help 以外にも `<C-]>` のタグジャンプがプレビューウィンドウになるなど別の影響もあるようです。

分かったことは追記します。

**Comment by h-east** [comment]
@0xBADDCAFE 登録ありがとうございます。

patchです。問題なさそうでしたらtest追加してvim_devに投げます。
https://gist.github.com/h-east/ff7a15518033ebdeceae45c6304ef69d

**Comment by 0xBADDCAFE** [comment]
ありがとうございます、よろしくお願いします。

**Comment by h-east** [comment]
vim_devにpatch送付しました。
https://groups.google.com/d/msg/vim_dev/qa-cl0kjgAU/LWEDX2VqBgAJ

**Comment by h-east** [comment]
patch 7.4.2248
https://github.com/vim/vim/commit/358308dd99abdd56c6540339e505585d8db7bdfe
