### ISSUE TITLE
<c-r>=で関数実行後にコマンドライン補完の補完リストが表示されない

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#950]
## 質問・報告の内容

&lt;c-r&gt;=で関数を実行した後、&lt;C-x&gt;&lt;C-v&gt;を押してもコマンドライン補完の補完リストが表示されません。

sample1.vim

``` vim
function! Sample()
    return 'autocmd '
endfunction

call feedkeys("i\<c-r>=Sample()\<CR>\<C-x>\<C-v>")
```

Vim起動

`vim -Nu NONE -S sample1.vim`

スクリプト実行後に表示されるメッセージ

```
-- コマンドライン補完 (^V^N^P) パターンは見つかりませんでした
```

---

sample2.vimのように一度ノーマルモードに戻ってからカーソルを移動するとコマンドライン補完が出来ました。
ただ、Vim scriptからカーソルを移動すると補完できるようになるんですが、手動でhやlでカーソルを動かした場合は補完できません。

sample2.vim

``` vim
function! Sample()
    return 'autocmd '
endfunction

call feedkeys("i\<c-r>=Sample()\<CR>")
call feedkeys("\<esc>:call cursor(line('.'), col('.'))\<CR>a\<C-x>\<C-v>")
```

Vim起動

`vim -Nu NONE -S sample2.vim`
## Vimのバージョン

7.4.2290 
## OSの種類/ディストリ/バージョン

Debian 8.5 jessie 64bit
## その他

次の補完コマンドは問題ありません。
- i_CTRL-X_CTRL-L
- i_CTRL-X_CTRL-N
- i_CTRL-X_CTRL-K
- i_CTRL-X_CTRL-T
- i_CTRL-X_CTRL-I
- i_CTRL-X_CTRL-]
- i_CTRL-X_CTRL-F
- i_CTRL-X_CTRL-D
- i_CTRL-X_CTRL-U
- i_CTRL-X_CTRL-O

**Comment by h-east** [comment]
@norio13 いつもbug報告ありがとうございます。こんなバグよく見つけますよね。すごいです。
patch書きました。確認をお願いします。
https://gist.github.com/h-east/b81c037113aae6cc505168c7946b27ef

**Comment by norio13** [comment]
@h-east patch適用したら問題が解消されました。ありがとうございます。
多分これは仕様だろうと思いTeratailで質問したのが切欠でこちらに報告させて頂きました。
patchのお陰で使いやすくなりました。
h-eastさんの問題解決能力の高さには頭が上がりません。

**Comment by h-east** [comment]
patchをvim_devに送りました。
https://groups.google.com/d/msg/vim_dev/scUMlBKiyqU/Vkl1zDBuCQAJ

**Comment by h-east** [comment]
Bram said:

> Isn't the problem that the completion is using ccline, but when getting 
> there from insert mode it's never set?  So ccline.cmdfirstc is "=" 
> because of the previous command. 

ccline.cmdfirstc が "=" のままなのがダメっぽいのでその辺をもう少し調査します。

**Comment by h-east** [comment]
調査して更新したpatchをvim_devに再提出しました。
https://groups.google.com/d/msg/vim_dev/scUMlBKiyqU/J69wnVaHAQAJ

**Comment by h-east** [comment]
Bram氏がいい感じにfixしてくれました:+1: (私のpatchはtestのみ採用)
patch 7.4.2331
https://github.com/vim/vim/commit/33a80eeb859a78ba93432da6fa585786cfd77249
