### ISSUE TITLE
翻訳関連の問題

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#951]
## 質問・報告の内容
-   `E904` が2つあった。これが正しいのかどうかはわからない
  -   メッセージ内容を一見するだけだと、別の方が良いように思えたが、実際にどうかは要確認
-   src/po/check.vim が `Ennn` 部分の間違いを検出しなかった
  -   前はしてくれていたと記憶していたので、ちょっと困惑

[この指摘](https://github.com/vim-jp/lang-ja/pull/55/files/09dbfa996177b38633466461c78c6fd43ccdf39c#r76995367) で発覚しました。
## Vimのバージョン

7.4.2259
## OSの種類/ディストリ/バージョン

無関係
## 使用している or 関係していそうなプラグイン

なし
## その他

なし

**Comment by crazymaster** [comment]
> src/po/check.vim が Ennn 部分の間違いを検出しなかった
> 前はしてくれていたと記憶していたので、ちょっと困惑

手動でやったら検出されましたよ。

**Comment by koron** [comment]
> -   src/po/check.vim が `Ennn` 部分の間違いを検出しなかった
>   -   前はしてくれていたと記憶していたので、ちょっと困惑

再試したら表示された。
これは何かしらの理由で実行方法を間違えた可能性がある。
また、 lang-ja では make check でくり返し正しく実行できるようにしたので、解決済み。

**Comment by koron** [comment]
> -   `E904` が2つあった。これが正しいのかどうかはわからない
>   -   メッセージ内容を一見するだけだと、別の方が良いように思えたが、実際にどうかは要確認

ソースによると、どちらも channel 起因で expr/call が実行されたときの引数のエラーを示すもの。
よって何をチェックしているかは異なるものの、意味的な違いは無いと言って良い。
https://github.com/vim/vim/blob/80c3fd7c559c7d329d57afe10db9bfb0adf10e46/src/channel.c#L2141-L2153

またエラーコードの重複自体は下記に示す通り意外とあり、いずれもそれぞれ同じ系統のエラーを示している。

```
4 E456
4 E317
3 E298
2 E904
2 E867
2 E588
2 E563
2 E521
2 E513
2 E505
2 E37
2 E244
2 E216
2 E180
2 E179
2 E173
2 E170
```

よって「正しい」と強く推定できる。

**Comment by koron** [comment]
ということで、思い過ごしであるので worksforme で閉じます。

**Comment by crazymaster** [comment]
https://github.com/vim-jp/lang-ja/pull/58 
ここでやったcheck.vim実行スクリプトの改善の還元はどうされます？

**Comment by koron** [comment]
正直、迷いますね…

Windows の日本語環境(自動でenc=japanが設定され、cp932になる)
で起こりうる問題ってことなんですよね。
また Windows ではビルド時に現状では check.vim が走りませんし
(未確認だが普段のビルドでは走ってないはず)
やるならそこから手を入れたいところです。
で一般化と説明が難しく、かつ作業も少なくないので面倒、というのが正直なところです。

またあれ自体は 8.0 に入ってなくてもそう問題では無いので急がないってのもあります…
別途 issue 建てましょうかね。

**Comment by crazymaster** [comment]
うーん、そうなんですか...
エラー行表示だけならどうでしょう

**Comment by koron** [comment]
現時点では意味がないと考えています。

普通のユーザーがビルド時にそれを見ても何をして良いかわかりませんし、
最悪エンコードが異なる文字化けした内容をみせることになって
(場合によっては端末のresetが要るかも)
何も出さないほうがマシということになりそうです。

なのでやるなら README にそのあたりもしっかりドキュメント書かないと。

**Comment by koron** [comment]
というあたりで #953 に起票しておきました。
