### ISSUE TITLE
イベント発生時にtabeditすると現在のバッファが新規タブに開かれる

### ISSUE THREAD

**Issue by norio13** [vim-jp/issues#954]
## 質問・報告の内容

BufNew、BufAdd、BufCreateの3つのイベントが発生する時に:tabeを実行すると、現在のバッファが新規タブで開かれました。
### サンプル1

Vim起動

```
vim -Nu NONE -S sample1.vim
```

sample1.vim

``` vim
augroup sample
    autocmd!
    autocmd BufNew * tabedit
augroup END

normal! i1
tabedit
```

期待する動作
- 3つのタブページがそれぞれ異なるバッファ

実際の動作
- 左から1番目と2番目のタブページが同じバッファ
- 右端のタブページのみ新しいバッファ
### サンプル2

Vim起動

```
vim -Nu NONE -S sample2.vim
```

sample2.vim

``` vim
augroup sample
    autocmd!
    autocmd BufNew * tabedit
augroup END

edit a.txt
```

期待する動作
- 左側のタブページの名前が`a.txt`、右側のタブページの名前が`[無題]`

実際の動作
- 2つのタブページの名前が`a.txt`
## Vimのバージョン

8.0.3
## OSの種類/ディストリ/バージョン

Debian 8.5 jessie 64bit

**Comment by h-east** [comment]
メモ: git log -p -1 v7.4.2328

**Comment by h-east** [comment]
patch書きました。`make test`はALL DONEです。テストは後で書きます。
https://gist.github.com/h-east/8b18316dcf29cd2bc6d2270891e5e67c
チェックをお願いします。

Vim起動

``` bash
$ vim -Nu NONE -S sample_X.vim
```

sample_X.vim

``` vim
e aa.txt
augroup sample
    autocmd!
    autocmd BufNew * tabedit cc.txt
augroup END

normal! i1
tabedit bb.txt
```

実行結果
- 1つ目のタブ: `aa.txt` (編集あり)
- 2つ目のタブ: `bb.txt` (未編集) ←カレントタブページ
- 3つ目のタブ: `cc.txt`  (未編集)

上記結果になりますがよろしいでしょうか？

**Comment by norio13** [comment]
patch適用したら期待した結果になりました。
実行結果も問題ございません。
ありがとうございます。

**Comment by h-east** [comment]
patchを見直し&test追加してvim_devに投げました。
https://groups.google.com/d/msg/vim_dev/KfMRaOozs1A/RXa5jr1wAgAJ

**Comment by h-east** [comment]
Bram氏の回答

> Hmm, starting to edit another file in a BufNew autocmd event is just asking for trouble.  In general this should not be allowed.  The only reason it's not an error is to allow for using a temp buffer to do some work. 

超意訳: 「おいおい、autocmdで別のバッファの編集を始めたらあかんやろ。それは許されへんで。」

ということなのでこのissueは`worksforme`で閉じてしまおうと思います。

@norio13 & other>
よろしいですか？

**Comment by norio13** [comment]
私は問題ないです。
この挙動を受け容れます。
