### ISSUE TITLE
コマンドの出力末尾が改行の場合の systemlist() の結果がおかしい

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#956]
`systemlist()` の結果は `readfile()` に `b` オプションを指定した場合と同じになるはずなのですが、

> - 最後の行がNLで終わるときは、リストの末尾に余分な空文字列が追加される。

これが行われていないようです。

以下パッチ。

``` diff
diff --git a/src/evalfunc.c b/src/evalfunc.c
index 3207441..ff616b7 100644
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -11863,7 +11863,7 @@ get_cmd_output_as_rettv(
        if (list == NULL)
            goto errret;

-       for (i = 0; i < len; ++i)
+       for (i = -1; i++ < len; )
        {
            start = res + i;
            while (i < len && res[i] != NL)
```

パッチは書けたのですが、テストをどうして良いかわからず、ここで止まっています。どなたか、
- パッチのレビュー
- `systemlist()` のような外部プログラムを使う部分のテストをどう書けばよいのか

この辺りご教授頂けると助かります。
特になければテストなしで一旦投げようかと思っています。

**Comment by h-east** [comment]
> - パッチのレビュー

``` diff
-       for (i = 0; i < len; ++i)
+       for (i = -1; i++ < len; )
```

``` diff
       for (i = -1; i < len; ++i)
```

処理が同じであれば後者の方が良いでしょう。
あと、patchの修正箇所の正当性はチェックしていませんが、直感的に他にbetterなソリューションがあるような気がしています。なんとなく。

> - `systemlist()` のような外部プログラムを使う部分のテストをどう書けばよいのか

`vim/src/testdir/shared.vim`の`RunVim()`か`RunVimPiped()`は使えませんか？
(使用サンプルは`test_startup.vim`)

**Comment by presuku** [comment]
全体の流れを見てないので、的外れならすみません。
`i`の初期値を`0`から`-1`にすると、`while (i < len && res[i] != NL)`の所の`res[i]`が
ループの1回目で`res[-1]`となり、`get_cmd_output()`からの戻り値の1バイト前を読んじゃうので、
よろしくない気がしますが、どうでしょうか？（意図しない`NL`がある可能性がある）

**Comment by thinca** [comment]
> 処理が同じであれば後者の方が良いでしょう。

残念ながらそれだと処理が変わってしまい、ダメなのです。 @presuku さんの言う通り、これだと最初のループ時に `i` が `-1` になってしまい、問題があります。
そもそもなぜこのような修正が必要だったかと言うと、文字列末尾が改行だった場合、ループに戻ってくる時点で `i == len - 1` になっています。この時条件部分が評価される前に `i` がインクリメントされるとそこでループから抜けてしまい、最後の空文字列の要素が生成されなくなるためです。
また、結果が空文字列だった場合(`len == 0`)も、`readfile()` 的には `['']` が返されるのが正しいのですが、パッチ前は `[]` が返っていました。今回のパッチでここも修正されます。

> `vim/src/testdir/shared.vim`の`RunVim()`か`RunVimPiped()`は使えませんか？

ありがとうございます！見てみます！

**Comment by k-takata** [comment]
よく見ていなくてすみませんが、その処理で、文字列末尾が改行でない場合には空文字要素は足されないのでしょうか。

**Comment by thinca** [comment]
@k-takata while の部分で `i == len` まで行くので、バッチリ for ループを抜けます。

**Comment by k-takata** [comment]
あと、`for (i = 0; i <= len; ++i)` ではダメ？

**Comment by koron** [comment]
全く見ないでアレですが `i = len` の時に `res[i]` にアクセスしてなければOK、となるのかしら。

**Comment by h-east** [comment]
机上でしか見ていなくてすみませんが、`get_cmd_output()`の戻り値`res`は`len + 1`(1はNULの分)でallocされているので、iがlenと同値の場合に`end = res + i;`してもアドレス的には問題ないですね。
thincaさんのpatchでもOKですけど、インクリメントの位置が気持ち悪い(ごめんね)のでk-takataさんの案に:+1:です。

**Comment by thinca** [comment]
@k-takata さんので大丈夫でした！明らかにこちらの方がわかりやすいのでこっちにします！ありがとうございます！
@koron @h-east お二方もアドバイスありがとうございます。

> インクリメントの位置が気持ち悪い

同意 :sweat_smile: 最初に思い付いたのがこっちだったので… :tired_face: 

@h-east 教えてもらったテストのところ見てみました。やはりと言うか、割と普通に実行するだけみたいですね。
Linux だと `echo` で良さそうです。Windows だと改行なしのテストが面倒そう :sweat: 一応 `set /p` を使うイディオムはあるみたいですが…。
あ、もしくは一時ファイルに `writefile()` で書き出して `cat` と `type` をそれぞれ使う方がわかりやすいか。
試しにやってみます。(Windows はビルド環境を整えるところからになるので時間かかりそう)

**Comment by k-takata** [comment]
あるいは test_channel.vim みたいに、pythonを使うか。(`let s:python = PythonProg()`)

**Comment by thinca** [comment]
Windows の環境を用意するのに手間取りそうだったので、CI で回してもらおうってことで PR 投げました(手抜き)
https://github.com/vim/vim/pull/1135

**Comment by thinca** [comment]
@k-takata 内容的に Python スクリプトを用意するのは大げさっぽく感じたので、今回は前述の一時ファイルを出力する方向でやってみました。
気になる点などあったら遠慮なく指摘してもらえると 🙇

**Comment by thinca** [comment]
Windows でテスト落ちちゃいました… 😓 
https://ci.appveyor.com/project/chrisbra/vim/build/2068/job/14e6bea58o5vrek9#L1990

> Expected [''] but got ['The syntax of the command is incorrect.\r', '']

`tempname()` で作ったファイル名に対して `systemlist('type {file}')` を実行しているはずで、以前手元では `tempname()` を使わない例は試して、普通に実行できたんですが…(パッチ当たってない版)
今手元に Windows がないので後で調査してみます。心当たりある人がいたら教えてもらえると助かります 🙏

**Comment by thinca** [comment]
一切試していないけどダメ元で `shellescape()` 噛ませてみようかな…。

**Comment by thinca** [comment]
fork先で appveyor 有効にして別ブランチ使えば先方に迷惑かけずにテスト回し放題と言うことに気づき実践中。

**Comment by h-east** [comment]
`let ～_file = fnameescape(tempname())`でいけました。

余談:
`set shellslash`だとエラーになりますけど、これはデフォルトで`noshellslash`なので放置でいいと思いました。

**Comment by h-east** [comment]
あー、
`call assert_equal([～], systemlist(printf('%s %s', cmd, shellescape(～_file))))`
がBestですね。

**Comment by mattn** [comment]
fnameescape は `:` 向けのエスケープなので shellescape が望ましいですね。

**Comment by h-east** [comment]
@mattn そうですね。`'shellslash'`が`on`の時もOKですもんね。

**Comment by thinca** [comment]
ぐぬぬ…

https://github.com/vim/vim/blob/master/src/testdir/runtest.vim#L66-L67

``` vim
" Always use forward slashes.
set shellslash
```

これが原因でした(`'shellslash'` が on だとクォートにシングルクォートが使われて `cmd.exe` ではうまく動かない)。
そもそも `'shellslash'` は Windows で `'shell'` に cmd.exe 以外のシェルを設定する場合に使うもので、ここで設定するのが適切かは怪しい気がしています。

https://github.com/vim/vim/commit/f60b796fa9870bdfc4cdeb91653bac041916077d

これいらないのでは〜。
ちなみにテスト内で試しに `set noshellslash` したらテスト通りました。

**Comment by mattn** [comment]
そのコメント、「なぜ」が書かれていないしだいぶ横暴だなw

**Comment by thinca** [comment]
`runtest.vim` 側から削除したら他のテストがコケまくったw

https://ci.appveyor.com/project/thinca/vim/build/5/job/vvvdx6pshctg4bfh#L1998

`test_system_func.vim` 内でのみ `noshellslash` して終わったら戻す作戦で行きます…。

**Comment by mattn** [comment]
なるほど、テストの期待結果を UNIX だけ(`/`)書きたいんでしょうな。まぁわかる。

**Comment by thinca** [comment]
PR 上でテスト通りました。テストは共通部分を関数にくくりだすようにリファクタリングしてみました。

**Comment by h-east** [comment]
仕事場のPCはWindows 7だけどVimのビルド環境はない(入れられない)です。
ですので、私の今日の発言は実際のtestを動かして確認したものではなく、手打ちで試した結果なのでそのままスルーで良いです。

**Comment by thinca** [comment]
PR のスレが若干荒れ気味みたいですが… 😅 
Bram さん曰く、挙動が変わってしまうのと、最後に空要素が来るのは期待しない場合が多いので、`readfile()` 同様オプション引数を足してそれで挙動を変えるのはどうか、とのこと。
ただ `systemlist()` にはすでに `[{input}]` 引数があるんですよね。しかもうろ覚えですが、渡さなかった場合と空文字列渡した場合で挙動が違ったような? (かなり昔の記憶なので嘘かもしれないですが)
この案で行く場合パッチ作成難易度が若干上がりますね。例のループの条件部分を切り替えるスマートな方法が思い付かない 💦

**Comment by h-east** [comment]
todo入り
https://github.com/vim/vim/commit/dc08328821a2c11e33dfb1980332e4923ec64fca#diff-38d7929bd26d74d92ceddf984bbfc8dbR157

> Patch for systemlist(), add empty item. (thinca, Sep 30, #1135)
> Add an argument to choose binary or non-binary (like readfile()), when omitted
> use the current behavior.
> Include the test.
