### ISSUE TITLE
job_start から起動するコマンドが直ぐに終了するとcallbackが呼ばれない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#957]
再現性が低いですが、報告がそこそこあがっています。
## Vimのバージョン

8.0.0005
## OSの種類/ディストリ/バージョン

とりあえず僕が確認して再現した事のあるOS
-   Windows 7 64bit
-   Windows 10 64bit
-   Linux Ubuntu 16.04 64bit
## 使用している or 関係していそうなプラグイン

なし

再現プログラム

test.go

``` go
package main

import "fmt"

func main() {
    fmt.Print("foo")
}
```

test.vim

``` vim
function! Disp(ch, msg)
    echom a:msg
endfunction

let s:job = job_start("test.exe", { "callback" : function("Disp") })
```

**Comment by norio13** [comment]
Linux Debian 8.6 jessie 64bit
vim 8.0.8

標準出力に改行が含まれていないとcallbackが呼ばれませんでした。
標準出力に改行が含まれていればcallbackが呼ばれました。
私の環境では100%再現しました。
確認した言語はGo、 Python、PHPです。
- go version go1.7 linux/amd64
- Python 3.5.2
- PHP 7.0.0

callbackが呼ばれる時のtest.go

``` go
package main

import "fmt"

func main() {
    fmt.Print("1\n")
}
```

test.py

``` python
print(1, end="") # callbackが呼ばれない
#print(1) # callbackが呼ばれる
```

**Comment by ichizok** [comment]
出力の最後に改行がない場合のflush的な処理を追加
https://gist.github.com/ichizok/a60b96fc5c913b260c34a7e9e1a02de8

**Comment by norio13** [comment]
ichizokさんのパッチを適用したらcallbackが呼び出されました。
ありがとうございます。

**Comment by h-east** [comment]
@mattn さんの報告と @norio13 さんの報告は同根バグでしょうか？( mattnさんのも @ichizok さんのpatchで直る？)

**Comment by mattn** [comment]
なんでかうまくパッチがあたらず

**Comment by haya14busa** [comment]
mattn さんの再現プログラムが ichizok さんのパッチで直ることを確認しました．

が，タイトルの「job_start から起動するコマンドが直ぐに終了するとcallbackが呼ばれない」現象とは違いそう．
このタイトルと似たような現象に僕も遭遇したことがあったのですが，再現コードは作れてないです...
(僕の場合は stderr にメッセージ吐いた直後にjobがexitするとerr_cbがうまく呼ばれない..という感じだったけど素直に再現コード書こうとすると普通にcallback呼ばれる... orz)

**Comment by haya14busa** [comment]
(あっいや修正がflush的な処理を追加だからタイトルどおりの修正でもあるのか...?すいませんよく終えてませんでした)

**Comment by mattn** [comment]
Windows ではこれでも直らないっぽい。

**Comment by mattn** [comment]
ただ再現性が低いのでしばらく使ってみますね。

**Comment by mattn** [comment]
`callback` って stdout だけなんかな。ドキュメントも明記がない。

```
                        *job-callback*
"callback": handler Callback for something to read on any part of the
            channel.
```

`err_cb` (`callback` 指定なし、もしくは `out_cb` 指定あり) だとうまくいく。

**Comment by mattn** [comment]
んー。やはりうまく行かない場合もあるな。
test.vim

```
function! Disp(ch, msg)
    echom a:msg
endfunction

let s:job = job_start("stderr", { "out_cb" : function("Disp"), "err_cb": function("Disp") })
```

stdout.go

```
package main

func main() {
    println("foo")
}
```

Windows 特有なのかもまだ分からない。

**Comment by mattn** [comment]
やっぱり終了時間っぽい。

```
package main

import "time"

func main() {
    println("foo")
    time.Sleep(time.Second)
}
```

これ(1秒)なら foo 出た。

**Comment by haya14busa** [comment]
``` vim
call ch_logfile('/tmp/channellog.txt', 'w')

function! Disp(ch, msg)
  echom a:msg
endfunction

call job_start(['gcc', 'err_notfound.c'], { 'callback' : function('Disp') })
sleep

" log with :sleep
"   ==== start log session ====
"     0.000028 : Starting job: gcc  err_notfound.c
"     0.000052 on 48: Created channel
"     1.001146 ERR on 48: channel_select_check(): Cannot read from channel, will close it soon
"     1.001168 : looking for messages on channels
"     1.001170 on 48: Closing channel because of previous read error
"     1.001171 on 48: Closing channel
"     1.001220 : looking for messages on channels


" log without :sleep
"   ==== start log session ====
"     0.000029 : Starting job: gcc  err_notfound.c
"     0.000056 on 49: Created channel
"     0.001011 : looking for messages on channels
"     0.002848 RECV on 49: 'gcc: error: err_notfound.c: No such file or directory
"   '
"     0.002855 on 49: Invoking channel callback Disp
"     0.002976 RECV on 49: 'gcc: fatal error: no input files
"   compilation terminated.
"   '
"     0.002979 : looking for messages on channels
"     0.002984 on 49: Invoking channel callback Disp
"     0.003017 on 49: Invoking channel callback Disp
"     0.003055 ERR on 49: channel_select_check(): Cannot read from channel, will close it soon
"     0.003059 : looking for messages on channels
"     0.003061 on 49: Closing channel because of previous read error
"     0.003063 on 49: Closing channel
"     1.623960 : looking for messages on channels
```

Vim script 側で sleep したら callback 呼ばれない現象再現しました．( sleep しないとちゃんと呼ばれる)

同じ問題か微妙ですが `channel_select_check(): Cannot read from channel, will close it soon` のエラーのタイミングがあやしい...?

**Comment by haya14busa** [comment]
python で終了時間によって結果が変わる再現コード作れた．
相変わらず僕の環境だと stdout だと時間に関わらず大丈夫なんですがこれは環境の問題かもしれない...?
archlinuxです．

``` vim
function! Disp(ch, msg)
  echom a:msg
endfunction

call job_start(['python3', '-c', 'import sys; print("hi stderr", file=sys.stderr);'], { 'callback' : function('Disp') })
sleep
" sys.stderr なら sleep があると callback 呼ばれない．ないと呼ばれる

call job_start(['python3', '-c', 'import sys; print("hi stdout", file=sys.stdout);'], { 'callback' : function('Disp') })
sleep
" sys.stdout なら sleep があってもなくてもうごく

call job_start(['python3', '-c', 'import sys, time; print("hi with sleep", file=sys.stderr); time.sleep(1)'], { 'callback' : function('Disp') })
sleep
" python proglam 側で Vim script 側よりも長くsleep して待って上げるとちゃんと呼ばれる
```

**Comment by ichizok** [comment]
`channel_select_check` で (sock,) stdout, stderr の順に `channel_read` してますが、
https://github.com/vim/vim/tree/c79d6aa/src/channel.c#L3725

stdout が EOF になった時点で `channel_close_on_error` を呼んで `channel->ch_to_be_closed` を `TRUE` にするため、
https://github.com/vim/vim/tree/c79d6aa/src/channel.c#L3097-L3098
https://github.com/vim/vim/tree/c79d6aa/src/channel.c#L3024

次の、stderr への `channel_read` はすぐ return してしまう。
https://github.com/vim/vim/tree/c79d6aa/src/channel.c#L3056-L3057

よって、最後の例で、先に stdout を close しておくと callback は呼ばれない（はず）

``` vim
function! Disp(ch, msg)
  echom a:msg
endfunction

call job_start(['python3', '-c', 'import sys, os, time; os.close(1); print("hi with sleep", file=sys.stderr); time.sleep(1)'], { 'callback' : function('Disp') })
sleep
```

**Comment by haya14busa** [comment]
なるほど...! ありがとうございます!!! 僕も読んでたのになかなかわからなかった...

``` vim
call job_start(['python3', '-c', 'import sys, os; os.close(1); print("hi with sleep", file=sys.stderr)'], { 'callback' : function('Disp') })
```

だけで再現するということですね．たしかにやってみると再現しました

**Comment by splhack** [comment]
MacVim GUIでも同じ状況です。
https://github.com/macvim-dev/macvim/issues/322
MacVimに限らず、GUIで非同期にchannel_readする場合、子プロセスでexec失敗してperrorしてstderrにバッファしても、stdoutが空なのでchannel closeしてしまい、stderr読まないままです。

**Comment by mattn** [comment]
再現する方、どなたかこれ試して貰えませんか。

https://github.com/vim-jp/issues/issues/820#issuecomment-244603220

Windows 以外の部分も触っているので少しは影響するかも。

**Comment by haya14busa** [comment]
https://github.com/vim-jp/issues/issues/820#issuecomment-244603220 で直りました!

意図的に `os.close(1)` してしまう場合はこれでも直らないけど，まぁこのケースは別に対応しなくてもよさそうな気がしますね

**Comment by mattn** [comment]
んー。やはり。

読み取るより先に `channel->ch_to_be_closed = TRUE` になってしまうので channel_wait が読み取れると判断しても channel_read が無視しちゃうんですよね。

**Comment by ichizok** [comment]
`channel->ch_to_be_closed = TRUE` になると、次の
`mch_inchar > parse_queued_messages > channel_parse_messages > channel_close_now`
で channel が閉じられてしまうので

https://gist.github.com/ichizok/6e0c00daf387b32bebcc2972f0cca137
(socket, ) stdout, stderr が全て閉じるまで channel を閉じない、としてみました。
が、EOF取れた後ってすぐに fd 閉じてもいいんでしょうか？

**Comment by mattn** [comment]
今の実装ってプロセス終了するとすぐに読むのをやめちゃうんですが、read 出来るかぎり読み取るべきだと思うので、ch_to_be_closed は見ない方がいいのは間違ってないと思っています。で、read して EOF が来たなら閉じてしまっていいと思います。そうしないと読むのを辞めなくなるので。

**Comment by splhack** [comment]
@ichizok さんのパッチで、os_unix.cの子プロセスでexecvp失敗によるperrorがGUIで読めないのも治りました。

**Comment by splhack** [comment]
子プロセスがexitすると、stdinがselectで起きてもlength 0なので https://github.com/vim/vim/blob/7ef3810d28b7ab2edbfcafab3fe8ad8bc2c2f138/src/channel.c#L3122 によりchannelまるっとcloseされてしまって、stderrを読まないんですよね。

**Comment by ichizok** [comment]
https://github.com/vim-jp/issues/issues/957#issuecomment-249345160
https://github.com/vim-jp/issues/issues/957#issuecomment-250034587
これらのパッチ投げてしまってもいいですか？

**Comment by mattn** [comment]
テストがWindowsで1件こけています。

**Comment by mattn** [comment]
Test_read_nonl_line が Can't start って言われてるのでおそらく引数関連？

**Comment by ichizok** [comment]
あれ、そうですか...AppVeyorは通ったんですが
https://ci.appveyor.com/project/ichizok/vim/build/110

と思ったらTravisが `Test_pipe_through_sort_some` で落ちたけど、これは既知の問題か
https://travis-ci.org/ichizok/vim/builds/163904629

**Comment by mattn** [comment]
昨晩寝る前に見たエラーメッセージなのでもっかい確認してきます。

**Comment by mattn** [comment]
すみません。エラーの内容が違った。

```
From test_channel.vim:
Found errors in Test_read_nonl_line():
function RunTheTest[9]..Test_read_nonl_line line 8: Expected 3 but got 4
```

**Comment by mattn** [comment]
何が来てるかチェックしますね。お待ちを。

**Comment by mattn** [comment]
```
call job_start([s:python, '-c', 'import sys;sys.stdout.write(\"1\n2\n3\")'], {'callback': 'MyLineCountCB'})
```

これで通りますね。なんか引数の扱いがおかしい？

**Comment by ichizok** [comment]
ダブルクオートをエスケープするとpythonの実行でエラーになりませんか？

**Comment by mattn** [comment]
これ vim が原因じゃないんですよ。

![](http://go-gyazo.appspot.com/412200579ca56ec7.png)

なのでテストそのまま直して貰ったらいいと思います。

**Comment by mattn** [comment]
unix 側の検証はこれからやります。unix 側が NG なら if で分けましょう。あと表題の件と異なるので出来れば issue 分けたいです。

**Comment by mattn** [comment]
UNIX だとエラーになりますね。なので if で分けましょうか。修正後、パッチの提出お願いします。TODO 書いておいて貰ってもいいかなと思います。

**Comment by mattn** [comment]
それか #961 の修正を待って頂くというのもあります(がWindowsの為にパッチ提出を遅らせるのは好きではないですが)

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/LhXQJusQScM
テスト修正して報告しました。

**Comment by mattn** [comment]
ありがとうございます

On 10/3/16, ichizok notifications@github.com wrote:

> https://groups.google.com/forum/#!topic/vim_dev/LhXQJusQScM
> 報告しました。
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/issues/issues/957#issuecomment-251001740

## 
- Yasuhiro Matsumoto

**Comment by h-east** [comment]
出力の最後に改行がない場合にcallbackが呼ばれない件、修正されました:+1:

patch 8.0.0022
https://github.com/vim/vim/commit/ec68a99464055029c01082762517e97245ddae0c

**Comment by ichizok** [comment]
patch 8.0.0027
https://github.com/vim/vim/commit/dc0ccaee68ca24d10050117fbec757ad33590a17
