### ISSUE TITLE
Inconsistency to handle stderr between `ch_status()` and `ch_read()`

### ISSUE THREAD

**Issue by haya14busa** [vim-jp/issues#958]
## Problem (質問・報告の内容)

`ch_status()` sees stdout and stderr to return the status, but `ch_read()`
sees stdout only.

From `:h read-in-close-cb`, we can write following code.
`go build` fails and print message to **stderr**.
#### job.vim

``` vim
func! CloseHandler(channel)
  while ch_status(a:channel) == 'buffered'
    echomsg ch_read(a:channel)
  endwhile
endfunc
let job = job_start(['go', 'build'], {'close_cb': 'CloseHandler'})
```
#### main.go

``` go
package main

func main() {
    a
    b
    c
}
```
### How to Reproduce
- `vim -Nu NONE -S job.vim`

It will be trapped in an infinite loop.

```
Error detected while processing function CloseHandler:
line    2:
E906: not an open channel
E906: not an open channel
E906: not an open channel
E906: not an open channel
...
```
### What's behind

`ch_status` sees `PART_OUT`(stdout) and `PART_ERR`(stderr) to check channel has buffer (`readahead`).

https://github.com/vim/vim/blob/50ba526fbf3e9e5e0e6b0b3086a4d5df581ebc7e/src/channel.c#L2595-L2614

``` c
    char *
channel_status(channel_T *channel)
{
    int part;
    int has_readahead = FALSE;

    if (channel == NULL)
         return "fail";
    if (channel_is_open(channel))
         return "open";
    for (part = PART_SOCK; part <= PART_ERR; ++part)
        if (channel_has_readahead(channel, part))
        {
            has_readahead = TRUE;
            break;
        }

    if (has_readahead)
        return "buffered";
    return "closed";
}
```

On the other hand, `ch_read` only reads `PART_OUT`(stdout) through `get_channel_arg`.

https://github.com/vim/vim/blob/50ba526fbf3e9e5e0e6b0b3086a4d5df581ebc7e/src/channel.c#L4321-L4322

``` c
    has_readahead = channel_has_readahead(channel,
                   part >= 0 ? part : channel_part_read(channel));
```

(`channel_part_read` returns `PART_OUT` or `PART_SOCK` for socket.)
### Expect

I'm not sure what should Vim do, but...
1. `ch_read` should read message from stderr too in addition to stdout.
2. `ch_read` should read message from stderr only if with a option which specify channel part to read.
   - In this case, we have to know which channel part has buffer through `ch_status`.
3. `ch_status` should see messages only in stdout, not in stderr.

I'm :-1: for (2) because channel will be too complicated.

I think the root problem is that it's not clear that channel created by job uses stdout or stderr (or both) for receiving messages.
(1) uses both stdout and stderr and (3) uses only stdout.

As far as I know, help doesn't mention it (e.g. `:h job_getchannel()`), so we should fix the help too to clarify the spec.

What do you think?
## Version

8.0.5
## Other

cc: @fatih
ref: https://twitter.com/fatih/status/778697353872015362

I wrote this issue in English, but we may talk in Japanese.
We'll open the issue in vim-dev if this issue is valid.

vim-jp メンバーの人へ

英語で相談されたのを調べて回答するのと vim-jp
に相談するために英語と日本語両方書くのが面倒だったので英語で報告しましたが，
vim-jp なので日本語で話してokです.
問題と原因くらいは僕の英語でも解ると思いますが，いや日本語でもかけよ!!!
という場合は日本語で書き直します :bow: :bow: :bow:

(一応vim-devに報告する際にもどうせ英語かかないとなぁという思いがあった)

**Comment by fatih** [comment]
Thanks @haya14busa for looking into this. Let me know if there is anything I can do on my side.

**Comment by h-east** [comment]
I found a temporary solution.

``` diff
--- job.vim.orig        2016-09-27 00:40:40.551530330 +0900
+++ job.vim     2016-09-27 00:39:40.181469190 +0900
@@ -1,6 +1,6 @@
 func! CloseHandler(channel)
        while ch_status(a:channel) == 'buffered'
-               echomsg ch_read(a:channel)
+               echomsg ch_read(a:channel, {'part': 'err'})
        endwhile
 endfunc
 let job = job_start(['go', 'build'], {'close_cb': 'CloseHandler'})
```

**Comment by haya14busa** [comment]
yeap, I also noticed. but in this case,  it cannot handle message in stdout.
If there are buffered message in stdout, `ch_read(a:channel, {'part': 'err'})` fails with E906.

**Comment by haya14busa** [comment]
I also looked in to it, but it's very difficult to solve...

`ch_status` returns "buffered" regardless the channel part(stdout/stderr) which has the buffered message.
`ch_read` throws E906 if the specified part (stdout/stderr) has no message for closed channel.

First, I tried (3) solution (ch_status should see messages only in stdout, not in stderr.), but from a quick read of `:h ch_status()`, it should not ignore message that can be obtained with `ch_read()`...

```
        "buffered" is used when the channel was closed but there is
        still data that can be obtained with |ch_read()|.
```

I didn't know 'part' option before, but with that said, solution (1) is invalid...

Finally, I tried (2) solution and fix the code to make `ch_status()` return "buffered_err" for stderr.
However, in this case, we cannot handle the case that there are buffered message both in stdout and stderr.

**Comment by haya14busa** [comment]
As a work around, we can use following code.

``` vim
func! CloseHandler(channel)
  while ch_status(a:channel) == 'buffered'
    echomsg s:ch_read(a:channel)
    echomsg s:ch_read(a:channel, {'part': 'err'})
  endwhile
endfunc

function! s:ch_read(...) abort
  try
    return call('ch_read', a:000)
  catch /^Vim\%((\a\+)\)\=:E906/
    return ''
  endtry
endfunction
let job = job_start(['go', 'build'], {'close_cb': 'CloseHandler'})
```

With that said, we can make  `ch_read`  to return empty string instead of throwing error by default, but I guess it doesn't work for js/json mode  (and it's not good solution in the first place..)

**Comment by haya14busa** [comment]
I reported this to vim-dev. https://github.com/vim/vim/issues/1120

**Comment by h-east** [comment]
This issue was fixed by Bram:+1:

patch 8.0.0015
https://github.com/vim/vim/commit/7ef3810d28b7ab2edbfcafab3fe8ad8bc2c2f138
