### ISSUE TITLE
コマンドラインのコマンドと(英字以外で始まる)引数を続けて指定してもエラーにならずに正常に処理されてしまう

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#96]
コマンドと(英字以外で始まる)引数を続けて指定してもエラーにならずに正常に処理されてしまう。
例)

``` vim
:e_vimrc                          "  カレントdirの _vimrc をedit
:ed~/.vimrc                       " ~/.vimrc をedit
:save_ﾎﾟﾘﾝｷｰ                       ” 現バッファを ファイル名 _ﾎﾟﾘﾝｷｰ で保存
```

helpに記載が無い <code>:redir@*</code> や <code>:redir>>hoge</code> がエラーにならないのも根本は一緒。
（helpには <code>:redir @*</code> や <code>:redir >>hoge</code> とコマンドの直後に空白が入っている）

※対象OS: ALL

※
いまさら <code>:redir@*</code> や <code>:redir>>hoge</code> をエラーにするのはツライ！？
<code>:edit</code> <code>:saveas</code> を個別対応するとか、helpを実状に合わせて修正するとか？
いろいろ議論しましょう。

私のgistで少しだけやってましたが今後はこのIssueに移行します。
https://gist.github.com/1397800

**Comment by h-east** [comment]
まずは私の調査内容をペタリ。
https://gist.github.com/1397800#gistcomment-65683

find_command() [ex_docmd.c : 2838]

``` C
//↓ pは”sav_l”
2855     p = eap->cmd;
//↓ アルファベット文字をスキップ。pは "_l"
2874         while (ASCII_ISALPHA(*p))
2875             ++p;
～
//↓ lenは 3
2884         len = (int)(p - eap->cmd);
～
//↓ strncmp()をlen:3で呼んでいるので "saveas" の先頭3文字に一致する！！。直後の "_l" はファイル名として使われる。
2909             if (STRNCMP(cmdnames[(int)eap->cmdidx].cmd_name, (char *)eap->cmd,
2910                                                             (size_t)len) == 0)
```

でもこの関数find_command()はコマンドラインの解析時に必ず呼ばれるので、ここでiswhiteチェックとNULチェック(と '!' チェック )をすると今までイケていた
<code>:redir@*</code> や <code>:redir>>hoge</code> がエラーになることになる。
（<code>:redir @*</code> や <code>:redir >>hoge</code> とコマンドの直後は空白文字を入れないとダメ）

help的には空白無しは許されてないのでこの修正は正しいといえば正しい。。(例: :redir :e :sav)
でも後方互換＆影響範囲を考えるとpatch送ってもまず取り込まれない！

**Comment by h-east** [comment]
次にmattnさんのadhocパッチをペタリ。
https://gist.github.com/1397800#gistcomment-65690

まずvimには`sav!`や`sav#1`みたいな特別な識別文字があるので、これを禁止する事は出来ない(既にハンドルされているはず)です。
で、問題はハンドルされていない変な文字があとどれだけあるかです。
一通り試した感じ、`_`だけっぽいのでadhocにやっていいかと思います。

``` diff
diff -r 379a6398d462 src/ex_docmd.c
--- a/src/ex_docmd.c    Wed Oct 26 23:48:21 2011 +0200
+++ b/src/ex_docmd.c    Mon Nov 28 21:04:41 2011 +0900
@@ -2906,7 +2906,8 @@

    for ( ; (int)eap->cmdidx < (int)CMD_SIZE;
                   eap->cmdidx = (cmdidx_T)((int)eap->cmdidx + 1))
-       if (STRNCMP(cmdnames[(int)eap->cmdidx].cmd_name, (char *)eap->cmd,
+       if (eap->cmd[len] != '_' &&
+       STRNCMP(cmdnames[(int)eap->cmdidx].cmd_name, (char *)eap->cmd,
                                (size_t)len) == 0)
        {
 #ifdef FEAT_EVAL
```

**Comment by h-east** [comment]
私の現状のhelp通りにするpatch (参考出展: vim_devに送る気は無い)
たぶん抜けありますし。

``` diff
diff -r 379a6398d462 src/ex_docmd.c
--- a/src/ex_docmd.c    Wed Oct 26 23:48:21 2011 +0200
+++ b/src/ex_docmd.c    Mon Nov 28 21:57:22 2011 +0900
@@ -2899,23 +2899,30 @@
            }
        }

-       if (ASCII_ISLOWER(*eap->cmd))
-           eap->cmdidx = cmdidxs[CharOrdLow(*eap->cmd)];
+       if (vim_iswhite(*p) || *p == NUL || *p == '!')
+       {
+           if (ASCII_ISLOWER(*eap->cmd))
+               eap->cmdidx = cmdidxs[CharOrdLow(*eap->cmd)];
+           else
+               eap->cmdidx = cmdidxs[26];
+
+           for ( ; (int)eap->cmdidx < (int)CMD_SIZE;
+                               eap->cmdidx = (cmdidx_T)((int)eap->cmdidx + 1))
+               if (STRNCMP(cmdnames[(int)eap->cmdidx].cmd_name, (char *)eap->cmd,
+                                                               (size_t)len) == 0)
+               {
+#ifdef FEAT_EVAL
+                   if (full != NULL
+                           && cmdnames[(int)eap->cmdidx].cmd_name[len] == NUL)
+                       *full = TRUE;
+#endif
+                   break;
+               }
+       }
        else
-           eap->cmdidx = cmdidxs[26];
-
-       for ( ; (int)eap->cmdidx < (int)CMD_SIZE;
-                              eap->cmdidx = (cmdidx_T)((int)eap->cmdidx + 1))
-           if (STRNCMP(cmdnames[(int)eap->cmdidx].cmd_name, (char *)eap->cmd,
-                                                           (size_t)len) == 0)
-           {
-#ifdef FEAT_EVAL
-               if (full != NULL
-                          && cmdnames[(int)eap->cmdidx].cmd_name[len] == NUL)
-                   *full = TRUE;
-#endif
-               break;
-           }
+       {
+           eap->cmdidx = CMD_SIZE;
+       }

 #ifdef FEAT_USR_CMDS
        /* Look for a user defined command as a last resort.  Let ":Print" be
```

**Comment by ynkdir** [comment]
ex互換ですかね。

http://pubs.opengroup.org/onlinepubs/007908799/xcu/ex.html

```
Zero or more blank characters can precede or follow the addresses, count, flags or command name. Any object following a command name (such as buffer, file and so on) that begins with an alphabetic character will be separated from the command name with at least one blank character. 
```

コマンド名と区別できる(記号とか)ときはスペースは省略できるということじゃないかと思います。
:s/t/u/ みたいに。

Vimのヘルプには書いてないですね。

**Comment by h-east** [comment]
@ynkdir いつも多次元の引き出しから的確なブツを提供頂きありがとうございます。

確かに[私のpatch](https://github.com/vim-jp/issues/issues/96#issuecomment-2896564)だと <code>:s/hoge/moge/</code> が「E492 そんなコマンドねーよ」と怒られました。汗。

やはりソースを修正するよりはhelpに捕捉を足すのが現実的ですね。

**Comment by mattn** [comment]
問題はその文字がコマンドの一部の文字に見えてしまうのが問題で、`.`や`!`や`/`はそれを区別するに値する文字だと思うんですが`_`は精神衛生的に許容しがたいという事だと思います。
もしvim_devに出すとすれば議論という名目で出すのが良いかと。

**Comment by h-east** [comment]
@mattn なるほど。その考えだと数字も許容しがたいですよね。
<code>:w1</code>

<code>:g</code>の区切り文字に関する @ynkdirさんと私のツイート
http://twitter.com/#!/ynkdir/status/109511569951555584
http://twitter.com/#!/h_east/status/109516381799714816

**Comment by mattn** [comment]
前者はpython3コマンドの略名`py3`の為のworkaroundがコードにも入ってますね。
空白については面白いけど、もうネタに近いですねw

``` vim
a
b
c
:g _b_ s _b_a_g
```

**Comment by tyru** [comment]
これができないと`:g`とか`:s`みたいなコマンドが作れないと思います。
別の記法でやればいいだけな気もしますが。

たしかeregex.vimとかは`:S`ってコマンドを定義してて`:S/foo/bar/`とかできた気がします。
と思って`:help :S`ってやってみたらabolish.vim(tpopeさんのプラグイン)のhelpが出てきたのでabolish.vimもこれを利用してるみたいです。

**Comment by h-east** [comment]
@tyru そうですね。いまさらこの辺りを弄るのはさすがにマズいので、もしやるなら個別対応でしょうかね。
例えば<code>:write</code> コマンドだと認識出来た後でコマンドの直後をチェックして <code>_</code> とか <code>[0-9]</code> だったら <code>E492</code> にするとか。

**Comment by thinca** [comment]
`:help user-cmd-ambiguous`

```
The other characters of the user command can be uppercase letters, lowercase
letters or digits.  When using digits, note that other commands that take a
numeric argument may become ambiguous.  For example, the command ":Cc2" could
be the user command ":Cc2" without an argument, or the command ":Cc" with
argument "2".  It is advised to put a space between the command name and the
argument to avoid these problems.
```

```
ユーザコマンドの開始文字以外は、大文字であっても小文字であっても、数字であって
もかまいません。数字を使う場合、数字を引数に取る他のコマンドが曖昧になるかもし
れないので注意してください。例えば、"Cc2" コマンドは ":Cc2" という引数なしの
ユーザーコマンドとしても、"2" という引数を取った ":Cc" コマンドとしても解釈で
きます。これらの問題を避けるため、コマンド名と引数の間にスペースを挿入すること
を勧めます。
```

help に書いてありますねぇ。
ちなみに `_` はそもそもコマンド名として使えないので、処理としては妥当な気がします。直感からは反しますがw

**Comment by h-east** [comment]
モロ関連するので貼っときます。
:global wrong delimiters
https://groups.google.com/d/msg/vim_dev/h0ykPqsCiDM/naW1l3F8bsIJ

**Comment by h-east** [comment]
昔ながらの仕様です。そういうものです。閉じます。
