### ISSUE TITLE
Windows版GVimでカーソル表示のゴミが表示される

### ISSUE THREAD

**Issue by h-east** [vim-jp/issues#960]
再現手順:
1. Vim 8.0.3 Win 64bit +kaoriyaを[ここ](http://vim-jp.org/vimmagazine/2016/09/30/vimmagazine.html)からダウンロードし解凍後、任意のフォルダにリネーム&移動させる。(例: `C:\Program Files\vim`)
2. `$HOME`(C:\Users\_ユーザー名_)に空の`_vimrc`と`_gvimrc`を作成する。
3. `gvim.exe`を起動する。
4. 以下のコマンドをGVim上で実行し、`j`を16回押す。

``` vim
:h
gm
```

実行結果:
カーソル表示？のゴミが表示される。(再現率: 100%)
「を」のカーソル表示が本物でその前のがゴミです。
![cursor_garbage](https://cloud.githubusercontent.com/assets/518808/18998344/46638908-8773-11e6-957b-16b2ca9b2677.png)
## Vimのバージョン

GVim 8.0.3 Win 64bit +kaoriya
## OSの種類/ディストリ/バージョン
- Windows 10 Home 64bit
- Windows 7 Pro 64bit
## その他
- CUI Vimでは発生していない。(Win & Linux)
- GVim for Linuxでは試していない。
- ~~本家のGVimでは試していない。~~→本家のGVimでも発生した。

おそらくマルチバイト絡み。
上記再現手順だと`enc`は`cp932`、`fenc`は`utf-8`だが、どちらも`cp932`の時でも再現した。

**Comment by h-east** [comment]
`enc`が`utf-8`の場合は発生しない。

**Comment by k-takata** [comment]
自前ビルドでも`enc=cp932`で発生しました。
`:set cole=0` すると起きなくなりますね。concealのせいでカーソル位置がずれているのと、スクロールが同時に発生すると起こる？

**Comment by h-east** [comment]
本家のGVim 8.0.19 Win 64bitでも再現しました。
https://github.com/vim/vim-win32-installer/releases/tag/v8.0.0019
のgvim_8.0.0019_x64.zipを解凍してgvim.exeを実行。

ただし、こちらは上記手順では再現しなかったので、`gm`後に`j`や`k`でラフにスクロールさせると再現しました。

``` vim
:so vimrc_example.vim
:e {上記手順にあるヘルプファイルを直接指定}
:h
gm
```

# 

@k-takata concealなしでも発生すると思います。私が最初に気付いた時はconceal未設定かつ普通のテキストファイル(hoge.txt)でした。
寝て起きてからconceal未設定版の再現手順を確立させます。

**Comment by h-east** [comment]
本家GVimで日本語(cp932)入りノーマルテキストで再現出来ました。

https://github.com/vim/vim-win32-installer/releases/tag/v8.0.0019
のgvim_8.0.0019_x64.zipを解凍してgvim.exeを実行。
(予め、`$HOME`(C:\Users\_ユーザー名_)に空の`_vimrc`と`_gvimrc`を作成しておいて下さい。)

**Kaoriya版の**`README.txt`(cp932)を開く。(パスは各自で読み替えて下さい)

``` vim
:e \Program\ Files\vim\README.txt
```

以下のコマンドを入力する。

``` vim
41G
zb
33|
jjjjjjj
```

実行結果:
![cursor_garbage2](https://cloud.githubusercontent.com/assets/518808/19011184/a29ebeee-87c9-11e6-9d5e-032e9423b7ae.png)

補足:
- 最後のカーソルが本物です。
- kaoriya版でも同じ手順で再現します。
- `set enc=utf-8`の場合は発生しません。

**Comment by h-east** [comment]
以下のpatchで問題が発生することを突き止めました。
https://github.com/vim/vim/commit/144445d15f2369a58b94b6fee2fe162fc81c8abe

> patch 7.4.2003
> Problem:    Still cursor flickering when a callback updates the screen. (David
>             Samvelyan)
> Solution:   Put the cursor in the right position after updating the screen.

# 

これが元のスレッド
Draw issue in gvim when calling matchadd() from timer callback.
https://groups.google.com/d/msg/vim_dev/9XHUNo0CT6k/npeBB3XSCAAJ

これがpatch releaseスレッド
Patch 7.4.2003
https://groups.google.com/d/msg/vim_dev/VxEGkXtlxhI/xZFV_PohCgAJ
ここにBram氏が鋭いレスしてる。

> Looks like this fix triggers another cursor positioning problem. 
> When doing "rx" it first gets displayed in the right place, then drawn 
> two characters to the left.  Not sure where that comes from yet... 

# 

7.4.2003って7月初旬。。
GVimでencがDBCS(cp932等)な環境で使っている人少なくないと思うんだけどなぁ。

**Comment by h-east** [comment]
GVim 7.4.2002で元スレッドに書いてある再現手順で再現しなかったので、_gvimrcにカーソルブリンクをまったりさせる設定を書いたら再現するようになった。

``` vim
set guicursor+=a:blinkon1700-blinkoff700
```

で、どう修正しましょうか？

**Comment by mattn** [comment]
んー。kaoriya の README.txt で試してるんですが再現しない。 Windows10

**Comment by h-east** [comment]
@mattn `enc=cp932`にしていますか？
(デフォルトだとそうなっていますが念のため確認しています)

**Comment by mattn** [comment]
はい。guicursor も試したけど再現せず。

**Comment by mattn** [comment]
ちなみに僕は非 kaoriya 版。kaoriya 版使ってる場合、README.txt は ft=memo なんですが h_east さんは ft は空でしょうか？

**Comment by h-east** [comment]
(kaoriyaの)README.txtのmodelineに`ft=memo`が書かれているのでkaoriya版でも非kaoriya版でも`set ft?`の結果は`memo`です。
当然kaoriya版はhighlightされますが、非kaoriya版はhighlightされません。

**Comment by mattn** [comment]
![shoei](https://cloud.githubusercontent.com/assets/10111/19014853/fc38c102-8832-11e6-944c-8e196dd45947.gif)

んー。なんでしょうな。

**Comment by h-east** [comment]
手順の`33|`はエルじゃなくてオアです。

**Comment by mattn** [comment]
お。再現ed

**Comment by mattn** [comment]
これはあれだな。 w_curswant が右端超えてる時に描画が右端までしか描画されてないからもう1セル足らない系かな。

**Comment by mattn** [comment]
zb した行がもう半角ずれて(先頭に半角入れる)ると 33| でも 34| でも発生しない。TOMB っぽい。

**Comment by h-east** [comment]
> これはあれだな。 cursor_want が右端超えてる時に描画が右端までしか描画されてないからもう1セル足らない系かな。

再現手順通り`33|`の後に`j`を7回押すとそうではないことが分かるかと思います。
というか、Patch 7.4.2003を外せば直るんです。あとは[元スレッド](https://groups.google.com/d/msg/vim_dev/9XHUNo0CT6k/npeBB3XSCAAJ)の現象が起きないようにすることが必要です。

**Comment by mattn** [comment]
スクロール後に w_curswant の位置から mb_adjust_cursor してるはずですが、それが効いてないかその時にカーソルがのこりっぱになってるのかも。

**Comment by mattn** [comment]
んー。やっぱりそれっぽい。強制で書いてる箇所をコメントアウトしたら発生しない。

``` c
    if (did_undraw && !gui_mch_is_blink_off())
    {
        /* Put the GUI position where the cursor was, gui_update_cursor()
         * uses that. */
        gui.col = gui_cursor_col;
        gui.row = gui_cursor_row;
        //gui_update_cursor(FALSE, FALSE);
        screen_cur_col = gui.col;
        screen_cur_row = gui.row;
    }
```

**Comment by mattn** [comment]
これでどうでしょう？

``` diff
diff --git a/src/screen.c b/src/screen.c
index 4604ec7..ad9a865 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -765,6 +765,9 @@ update_screen(int type)
         * uses that. */
        gui.col = gui_cursor_col;
        gui.row = gui_cursor_row;
+#ifdef FEAT_MBYTE
+       gui.col = mb_fix_col(gui.col, gui.row);
+#endif
        gui_update_cursor(FALSE, FALSE);
        screen_cur_col = gui.col;
        screen_cur_row = gui.row;
```

**Comment by h-east** [comment]
@mattn 直りました:+1:
patch 7.4.2003(と7.4.2004と7.4.2199)でfixされた挙動も再発していないので大丈夫だと思います。
patchの`#ifdef`と`#endif`は1カラムネストした方がいいです。
`#ifdef`→`# ifdef`。`#endif`→`# endif`

**Comment by mattn** [comment]
確認あざます。

https://groups.google.com/forum/#!msg/vim_dev/VxEGkXtlxhI/xZFV_PohCgAJ

**Comment by h-east** [comment]
patch 8.0.0021
https://github.com/vim/vim/commit/84dbd494dca599ecff05b2c2279d402c12e6d197

@mattn :+1:
