### ISSUE TITLE
C言語プリプロセッサで defined が並ぶとシンタックスがおかしい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#962]
![](http://go-gyazo.appspot.com/9ec135300be0c48e.png)

要調査

再現バージョン: 8.0.0019 Windows10 64bit CUI/GUI

**Comment by h-east** [comment]
同環境(8.0.0019 Windows10 64bit CUI/GUI)で再現しません。
おれおれ`syntax/c.vim`を使用している可能性はないでしょうか？

**Comment by mattn** [comment]
あーすいません。その通りでした。。。

https://github.com/vim-jp/vim-cpp/issues/11#issuecomment-250897717

これの検証環境が残ってしまってました。
