### ISSUE TITLE
matchaddpos() が一部重複する pos を描画しない

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#966]
たとえば

`call matchaddpos('Error', [[1, 1, 5], [1, 3, 5]])
`

のように、複数の pos が 2 カラム(2 バイト?)以上重複する場合、
後ろの位置に描画されるべき pos (この場合は [1, 3, 5]) が描画されません。
getmatches() をみると、指定した pos はすべて設定されています。

`call matchaddpos('Error', [[1, 1, 5], [1, 5, 5]])
`

のように、1 カラムの重複ですと両方とも正常に描画されます。

7.4.648 でも 8.0 でも再現します。

**Comment by h-east** [comment]
Vim 8.0.23 on fedora via PuTTYで正しく表示されているように見えます。

``` bash
$ vim  -Nu NONE --cmd "syntax on" screen.c
```

``` vim
call matchaddpos('Error', [[1, 1, 5], [1, 3, 5]])
```

![matchaddpos](https://cloud.githubusercontent.com/assets/518808/19221405/ee017d44-8e7d-11e6-9b43-26c803350d85.png)
スクリーンショットを貼っていただくか、もう少し説明をしていただけると助かります。

**Comment by itchyny** [comment]
3文字目から5文字 (正確にはbyteかな…) ハイライトされることを期待しているのではないでしょうか

**Comment by h-east** [comment]
@itchyny I see. そうか、リスト3つ目はカラムじゃなくてbyte長でした。Thanks!

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/f34c9018f5e9e452d3bc78cc9026a720
`col < mincol < col + len - 1` のケースが問題なのだと思います。

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/Lrkkr3woyqM
報告しました。

**Comment by h-east** [comment]
@ichizok  テスト私書きます。(書き終えました)

Sent a test patch.
https://groups.google.com/d/msg/vim_dev/Lrkkr3woyqM/vzgvFKt1BAAJ

**Comment by ichizok** [comment]
@h-east すみません、ありがとうございます。
(描画時の問題と思い込んで、テスト書けないケースだと勘違いしてました...

**Comment by h-east** [comment]
patch 8.0.0033
https://github.com/vim/vim/commit/a6c27ee6db2c328e0ab0e6d143e2a295a0bb9c9a

@rickhowe Issue登録ありがとうございました。
@ichizok 👍
