### ISSUE TITLE
job_start に環境変数が渡せない

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#967]
こちらにも転記。

See https://github.com/vim/vim/issues/1158

pull-req にてパッチ送り済み。

https://github.com/vim/vim/pull/1160

**Comment by ichizok** [comment]
travis でテスト落ちてたのでコメントしました。

**Comment by mattn** [comment]
ありがとうございます。時間見つけて対応します。

**Comment by mattn** [comment]
[8.0.0902](https://github.com/vim/vim/commit/05aafed54b50b602315ae55d83a7d089804cecb0)
