### ISSUE TITLE
job_start() してすぐに job_stop() すると job プロセスを終了できない場合がある

### ISSUE THREAD

**Issue by ichizok** [vim-jp/issues#969]
https://github.com/vim/vim/issues/1155
本家の issue に出たので

原因は https://github.com/vim-jp/issues/issues/820#issuecomment-182662968 の2です。
win32 では問題ないようです。

再現スクリプト:

``` vim
let job = job_start(['sleep', '3'])
call assert_equal('run', job_status(job))
echom 'job:' string(job)
" sleep 1m
call job_stop(job)
sleep 10m
call assert_equal('dead', job_status(job))
echom empty(v:errors) ? 'Passed' : string(v:errors)
```

**Comment by ichizok** [comment]
https://gist.github.com/ichizok/26d571401be0685267ebf0790e964903
子プロセス側で `execvp()` する場合は `fork()` 前にPIDを保存し、`deathtrap()` 内で `getpid()` と異なっている場合はすぐ `exit()` する

**Comment by ichizok** [comment]
Mac だとたまに失敗する。<del>&rarr; Linux でも同様</del>
どうも `fork()` が完了する前 (子プロセス側の if 節に到達してない) にシグナルを受信する場合があるようで、
そのとき子プロセス側の `deathtrap()` 内で呼び出した `getpid()` は親プロセスと同じPIDを返している。
(`getpid()` の結果はキャッシュされているので、プロセスの準備が終わってないとそうなる)

**Comment by ichizok** [comment]
- fork 前にフラグ変数を変更して、親は fork 後すぐに戻す。`deathtrap()` 内でフラグ確認

<del>これで十分かも。</del> メモリ共有している段階だと親のメモリ領域を参照する?
その他:
- 親は子の`reset_signals` が完了するまで待つ  
  &rarr; fork が遅い環境だと性能に影響する
- `vfork()` を使う。Mac の場合、子が `execve` か `_exit` を実行するまで親は停止するが  
  `vfork` は即座に完了するので性能への影響はない  
  &rarr; 非推奨の関数。親の動作 (停止するかどうか) が環境依存
- fork 前に `sigprocmask` でブロックして、子は `reset_signals` 完了してからブロック解除する  
  &rarr; うまくいく。`sigprocmask` が使えるか configure で確認

**Comment by ichizok** [comment]
https://groups.google.com/forum/#!topic/vim_dev/tevAPI5T86M
`sigprocmask` 版で投げました。

**Comment by h-east** [comment]
patch 8.0.0045
https://github.com/vim/vim/commit/bb09ceb95477ecc271854b3fdd8d2776eca66adf

Great:+1:
