### ISSUE TITLE
補完時のregister-.の挙動の改善

### ISSUE THREAD

**Issue by Shougo** [vim-jp/issues#97]
neocomplcacheを使っていると、register-.の値がおかしくなるので調べていたんですが、原因が分かりました。

register-.がおかしくなる条件は、「neocomplcacheで単語の一部を補完すること」です。

例えば、hogeのhoの部分からhogeraを補完したとします。
このとき、register-.にはgeraが入って欲しいのですが、hogeraが入ってしまいます。
これはなぜそうなるかというと、補完位置がhogeの前となるからです。
|hoge（|はカーソル）の位置で補完されるので、Vimからは「hogeraが入力された」と錯覚するのでしょう。

ちなみに、これはneocomplcacheでのみ発生する話ではありません。
オムニ補完やユーザー定義補完でも同様に発生します。
neocomplcacheの場合、毎回補完が発生するのでその現象に気付きやすいというだけです。

neocomplcacheで対処しようと思いましたが、register-.は読みとり専用であり、
今のところVim scriptから補完候補が選択されたということを知る術もないため対処が困難でした。

ちなみに、Vim組み込みの補完では問題ありません。
まぁ、こちらは絶対にカーソルにマッチする候補しか出てこないので当然ですが……。

改善する場合は、「a:baseにマッチする部分はregister-.から除外する」となると思います。
つまり、先ほどの例では、hogeraはa:baseのhoにマッチするのでgeraとなる、ということです。
このマッチのとき、マッチには大文字小文字を区別しないほうが良いような気がします。

**Comment by thinca** [comment]
この前の補完周りの変更でエンバグしたんですかね。
これすごく困ってるので直ってくれると嬉しいです。

**Comment by mattn** [comment]
perlomni.vimを使って

``` perl
my $hogera = 1;
$ho
```

という状態のファイルを開いて、`ho`から`i_CTRL-X_CTRL-O`したら`$hogera`が補完され、きちんと`register-.`にも`gera`が入っているようです。

```
:reg
--- Registers ---
"*   my $hogera = 1;^J^J$hogera^J^J
".   gera
"%   a.pl
```

そのomni補完でも再現する環境一式を下さい。

**Comment by Shougo** [comment]
あれ、確認してみたらneocomplcacheの手動補完では再現しませんでした。
おそらく、neocomplcacheの自動補完の呼び出しがおかしいです。
ちょっと調べてくるので待ってください。

**Comment by Shougo** [comment]
しかも、再現するときとしないときがあることが判明……。これは厄介。
ちょっと詳しい条件が分かるまで、この問題は保留としてください。
Vimかneocomplcacheのバグだと思うのですが、ちょっとタイミングが分かりません。

thincaさんも詳しい条件を調べてもらえませんか？

**Comment by Shougo** [comment]
> この前の補完周りの変更でエンバグしたんですかね。
> これすごく困ってるので直ってくれると嬉しいです。

その変更は関係がないです。なぜなら、その変更が入っていない古いVimでも再現するからです。

**Comment by koron** [comment]
補完のleaderとしてhoが指定されてますかねぇ？
私の記憶ではleader文字列と補完結果の差分を計算して、redoレジスタの内容として使ってました。

申告の動作になるのであればleaderに空文字列が指定されてる、と推測されます。

**Comment by Shougo** [comment]
> 補完のleaderとしてhoが指定されてますかねぇ？
> 私の記憶ではleader文字列と補完結果の差分を計算して、redoレジスタの内容として使ってました。

neocomplcacheのleader文字列としては、hoではなく空文字列になります。
なぜなら、そうしないと大文字小文字の区別やneocomplcacheで行っている特別なマッチを判別できないからです。
不思議なのは空文字列でも動いている点。Vim側で挿入された候補との差分を取っているようです。
やはりredoできるようにだと思います。
ただしおかしくなる場合もあって、その条件を調べているところです。

**Comment by koron** [comment]
> neocomplcacheのleader文字列としては、hoではなく空文字列になります。

だとすればredoバッファとしてはその動作がVimの仕様です。
まずは補完関数側でleader文字列を空文字列にしないでやる方法が無いか考えてみてください。

**Comment by koron** [comment]
最初の例でちょいと疑問に思ったんですが
ho|ge から hogera に補完すると普通のキーワード補完なら hogera|ge になるハズですが、
(`|`はカーソルの意味)
neocomplはどうやってもとからあったgeを消してるんですかねぇ?

それがわかればまた違う解法があるかも。

**Comment by Shougo** [comment]
> だとすればredoバッファとしてはその動作がVimの仕様です。
> まずは補完関数側でleader文字列を空文字列にしないでやる方法が無いか考えてみてください。

あ、正確に言うとhoというより

piyo hogeとなっていた場合、補完位置はpiyo ho|geraではなく
piyo |hogeとなるということです。
この仕様は普通のオムニ補完でもあるし普通だと思います。

> 最初の例でちょいと疑問に思ったんですが
> ho|ge から hogera に補完すると普通のキーワード補完なら hogera|ge になるハズですが、

あ、これは私の説明が間違っていますね。
cwでgeを削除していることを前提にしています。だから、hoge->ho->hogeraとなるのです。

**Comment by koron** [comment]
cwで消すのはダレですか?ユーザと補完関数のどちらでしょう?
(仮に消すのが補間関数であれば、それ自体がイレギュラーな動作なわけですが)

a:base(==leader)の作り方は、補間関数が一回目の呼び出しで返した位置から、その呼び出し前のcol('.')までになります。
問題の症状が起こった時の補間関数のそれらの挙動をしっかり例示して説明してもらわないと、
他の人には何が問題を引き起こしているかが伝わりませんよ。

> この仕様は普通のオムニ補完でもあるし普通だと思います。

それはVimでは普通ではありません。
未定義の仕様を利用してたまたま動いてるだけでしょう。

**Comment by koron** [comment]
> 呼び出し前のcol('.')まで

おっと、これウソかも。col('.')の位置は呼び出し後にとってるかもだけど、
仮に補完関数中でカーソルを動かした場合の動作は未定義です。
そもそも動かすことは考えにいれてなかったので。

**Comment by thinca** [comment]
`:help E839`

> 関数の中でカーソルを移動させてもよい。カーソルは実行後に復元される。

**Comment by koron** [comment]
@thinca: thanks!
では、動かすのは良いとして…geはどうやって消してるんでしょうね?
仮に補完関数ならば、同じ場所にある…

> The function is not allowed to move to another window or delete text.

これにぶつかります。

私の主張のポイントは、
- leaderと補完結果の内容でredoバッファの内容が決まるのがVimの仕様だから、それを考慮して補完関数作ってよ
- それ以外に考慮したほうが良い要素があるならば、それを明らかにしてよ(できれば仕様に落としてみてよ)

という感じ。

**Comment by koron** [comment]
現時点での原因の推測と、予測される対処方法。
1. 補完関数内でカーソルを動かしているが、Vimがカーソル復帰前に戻り値とcol('.')からleaderを決めてて、意図しないleaderになっている
2. 補完関数内でテキストを削除(変更)しているために、異常動作に陥っている

前者なら直せそう。後者なら…エラーチェックの強化かなぁ。

**Comment by Shougo** [comment]
> では、動かすのは良いとして…geはどうやって消してるんでしょうね?
> 仮に補完関数ならば、同じ場所にある…

えっと、分かりにくかったようですね。消しているのはユーザーです。
ユーザーがノーマルモードでcwを押してインサートモードに入ったときにneocomplcacheの補完が始まった場合のことを想定しています。
だからプラグインは文字を削除していないです。それは不正な動作ですから。

> > この仕様は普通のオムニ補完でもあるし普通だと思います。
> 
> それはVimでは普通ではありません。
> 未定義の仕様を利用してたまたま動いてるだけでしょう。

うーん、伝わっていないようですね。
補完関数がa:findstart=1のとき、match()でマッチした部分を返す、という実装になるのは普通で、
その動作自体はneocomplcacheと同じだということをいいたかったのです。

現に、普通はneocomplcacheであってもredoやregister-.が動いているし、これ自体に問題はないと思います。

**Comment by Shougo** [comment]
> 補完関数内でカーソルを動かしているが、Vimがカーソル復帰前に戻り値とcol('.')からleaderを決めてて、意図しないleaderになっている
> 補完関数内でテキストを削除(変更)しているために、異常動作に陥っている

ソースを読んで確認してみました。neocomplcache内では、カーソルを動かしていないですね。
テキストの削除もしていません。
ただし、オムニ補完ではそういう動作をするものがあるので、そのときは復元をしています。

自動補完のときだけ起こるみたいですし、ポップアップが出てくるタイミングの問題なのかもしれませんね……。
こちらで100%再現する条件が分からない限り、ちょっと何とも言えないです。済みません。

**Comment by Shougo** [comment]
> a:base(==leader)の作り方は、補間関数が一回目の呼び出しで返した位置から、その呼び出し前のcol('.')までになります。
> 問題の症状が起こった時の補間関数のそれらの挙動をしっかり例示して説明してもらわないと、
> 他の人には何が問題を引き起こしているかが伝わりませんよ。

はい。それを突きとめたかったのですが、また再現しないようになってしまったので条件が分からず説明ができません。
この現象は今まで何度も起こっているので問題があるのは分かっているのですけど……。

**Comment by mattn** [comment]
ネオコン入れて再現確認をしたいので、発生した際の最小構成のファイル内容とキーシーケンス下さい。

**Comment by Shougo** [comment]
それが……私の環境で出なくなってしまったのです。
私の他に再現するという人は、この条件で再現しているようです。

http://twitter.com/#!/rt_sporty/status/141534001860059137

> 再現性を確認しました。やはり単純に二つ同じ単語があって、一方の後半などをcwhelloとかするとレジスターが訳分かんないことになりますね。macvim 7.3 353です。Unite snippet助かります！一旦自動補完OFFで使わせていただきます！

**Comment by sporty** [comment]
rt_sportyです。お世話になります。もう少し詳しく書きます。

# vim・neocomplcacheのバージョン
- MacOS Lion  macvim 7.3 353
- Windows XP  gvim 7.3 353（kaoriyaさん版です）
- neocomplcache 355cbbbb7ea0db32f5ffa27ae889139e6eb552c2 (最新です)

# _vimrc

------ _vimrc ここから
 let g:neocomplcache_enable_at_startup = 1
------ここまで

# 実行したファイル

------ test.py の内容ここから
 # documentation
 # document
------ここまで

# 手順
1. １行目のdocumentationのmにカーソルを持っていき、cwで置換開始
2. a　でdocuaに編集してエスケープ押して完了
3. :di すると　". が壊れているようです。当然２行目のmにカーソルを移動して.しても同じ結果にならず、docuadocuaになります。

整理してみるとかなり単純な環境でも再現します。他に必要な情報がありましたらご指摘ください。

**Comment by mattn** [comment]
ちゃんと動きますね。
WindowsXP vim.exe gvim.exe で確認。

**Comment by mattn** [comment]
あー、再現しました。僕の所pythonでネオコンが発動してないだけでした。
今、発動するC言語のコードなら同じ症状になりました。
ただ、発動しないとうまく動いて、発動すると変になるって所を見ると、vimのバグと言ってしまうのはいささかどうかとも思います。

**Comment by Shougo** [comment]
あ、こちらでも再現しました。たしかにこれはおかしい。
ただし、g:neocomplcache_enable_auto_select = 1だと再現しないようです。
通りでこっちで再現しないわけだ……。

**Comment by koron** [comment]
今北産業。 @sporty さんの手順を見るかぎり、neocomplは動いてないように見えるんですが…
もしやCursorHoldで何かが走って、その副作用でregister-.が壊れる…ってこと?

**Comment by thinca** [comment]
neocomplcache は CursorMovedI をトリガにして自動で補完のポップアップを出すプラグインですよ。(それだけではないけど)

**Comment by koron** [comment]
@thinca いや使ってないのでしらんがな (´・ω・`)

**Comment by thinca** [comment]
はい。ご存知なさそうだったので説明したんですが…余計なお世話でしたか。

**Comment by mattn** [comment]
とりあえずつかんだ。

``` vim
let g:neocomplcache_enable_auto_select = 1
```

で直るはず。

**Comment by mattn** [comment]
alwaysの時の動作がおかしいっぽい

**Comment by mattn** [comment]
あー、かぶった

**Comment by koron** [comment]
気になってるのは特定の条件下でleaderが補完プラグインの意図しない物になっているのが
Vimの穴のせいなのか、プラグイン側の勘違いなのか、或いはその両方かなんだけど
どうかなぁ？

**Comment by tyru** [comment]
今北産業で流れ読めてないのですが
eskkでもneocomplcacheで補完を発動した時と手動で補完を発動した時と
leader(a:base)の値が違うので対応した覚えがあります。
https://github.com/tyru/eskk.vim/blob/af7482a7226fb0da19c02c05c6abfceb07303da9/autoload/eskk/complete.vim#L444-L450

**Comment by Shougo** [comment]
はい。そうみたいですね。
とりあえず、refresh=alwaysを使わなければ大丈夫ですけど……。

**Comment by Shougo** [comment]
試してみましたが、古いVimではこの問題が起こりませんね……。
やはりrefresh=alwaysのときに入った変更に問題があるような気がします。
とりあえず、refresh=alwaysを使わないようにして対応しました。

**Comment by Shougo** [comment]
タイトル変更するべきですかね？
「refresh=always時にregister-.の値がおかしくなる」というほうが適切かもしれません。
neocomplcacheでない補完関数で起こるかどうかは未確認です。
そういえば、この件は前にもあったような……。

**Comment by Shougo** [comment]
> eskkでもneocomplcacheで補完を発動した時と手動で補完を発動した時と
> leader(a:base)の値が違うので対応した覚えがあります。

はい。そういえば、そんな問題がありました。
確か、Vimの補完関数が呼ばれたときには、a:baseがgetline('.')に入っていないのです。
neocomplcacheは補完関数の外からオムニ補完を呼ぶのでそんな問題はないです。
これはどうするべきなのか難しいところ。

**Comment by Shougo** [comment]
予想ですが、refresh=alwaysのときにはregister-.にreader全体が入ってしまうんじゃないかなと思います。
差分じゃなくて。

**Comment by mattn** [comment]
ちょっと解析してみました。

例題は上記の `document` から `docua` への変更トリガ

```
1. document の m の部分(この時colは9)で cw で発動して neocomplcache#manual_complete が呼ばれる
2. neocomplcache#manual_complete は新仕様でalwaysを返している
3. この後自動で neocomplcache#auto_complete が呼ばれる
4. auto_complete から a:findstart = 1 として manual_complete が呼ばれる
5. 補完開始位置として cur_keyword_pos を 4 として返す
```

今回おかしくなったのは、この9と4で差異が発生した為。ここからvimの内部の話。
vimはユーザ補完もしくはオムニ補完が発動すると

```
6. 補完開始位置を貰ってそれを補完候補の表示開始位置にする
7. 補完中の入力位置(compl_pos)を 6 で設定した値で初期化
```

ここで問題なのが、通常の補完や以前の動きのままの場合はこの流れで良いのですが `always` が設定されるという事は、補完中の入力位置は再初期化(ins_compl_restart)したとしても変わるべきじゃないということ。
`always` が設定される事で、昔の仕様としては正しかった 7 の部分の意味がおかしくなります。

``` diff
diff -r 379a6398d462 src/edit.c
--- a/src/edit.c    Wed Oct 26 23:48:21 2011 +0200
+++ b/src/edit.c    Wed Nov 30 16:30:51 2011 +0900
@@ -5182,10 +5196,12 @@
         * Reset extended parameters of completion, when start new
         * completion.
         */
+
+       if (col < 0 || compl_opt_refresh_always)
+       col = curs_col;
+
        compl_opt_refresh_always = FALSE;

-       if (col < 0)
-       col = curs_col;
        compl_col = col;
        if (compl_col > curs_col)
        compl_col = curs_col;
```

この様に `always` が設定されていた場合には、補完継続中を意味するはずなのでユーザ補完関数から得た補完開始位置を信じずにカーソル位置で続行する様にすればうまく動きました。
信じないようにするので、いっそユーザ補完関数を呼ばないという手もありますが、ひとまず解析結果を皆さんに周知。

**Comment by koron** [comment]
@mattn++ エンジニアリング的にはrestart関数をalwaysの時だけ分けたいけど
そのpatchでOKだとおもいます。

**Comment by mattn** [comment]
うん。この

``` diff
+       if (col < 0 || compl_opt_refresh_always)
+       col = curs_col;
```

の部分の判定は少し悩ましい(別の経路でcompl_opt_refresh_always=TRUEが残りっぱなしになる可能性がある)んだけども。

**Comment by koron** [comment]
いまちゃんとコード見だした

@mattn:

> 1. document の m の部分(この時colは9)で cw で発動して

これってつまり補間関数neocomplcache#manual_complete(a:findstart==1)が9を返しているってこと?
だとしたらその時点でもう既におかしいような。
補完開始位置を返すんだから先頭のdを指す値になるべきだと考えるんだけど、どうして9なの?

**Comment by mattn** [comment]
あーいえ、colが9ってのはcol('.')が9って意味です。ネオコンは上に書いた通り4を返します。

**Comment by mattn** [comment]
ん？なんか違う...

**Comment by mattn** [comment]
わかりやすく説明します。

初回`int document`の`m`でcwした際には
- 補完開始位置 = 4
- 実際のカーソル位置 8 (`m`は9だが、cwで`u`の位置に戻るので8)
- 補完入力位置 = 4

になっています。その後、`r`を入力するとalwaysの為に再度ユーザ補完関数が呼ばれるのですが、その際ネオコンは`docura`が候補として見つからないので-1を返します。
そこでvimのedit.c

``` c
    if (col < 0)
        col = curs_col;
```

が発動してしまい、カーソル位置が curs_col に設定されてしまいます。
`int docur`の`r`の`r`の位置なので9ですね。つまり
- 補完開始位置 = 9
- 実際のカーソル位置 9
- 補完入力位置 = 9

になってしまいます。ここから同じ補完を行うと事で補完対象がおかしくなってしまうのです。
本来ならば、単純に1文字入力しただけなので
- 補完開始位置 = 4
- 実際のカーソル位置 9 (`r`を入力したので8+1で9)
- 補完入力位置 = 4

となるべきかと。

**Comment by koron** [comment]
> その後、rを入力するとalwaysの為に再度ユーザ補完関数が呼ばれるのですが、その際ネオコンはdocuraが候補として見つからないので-1を返します。

これってネオコンの動作は変じゃないの? `alwaysの為に再度ユーザ補完関数が呼ばれる`時ってa:findstart==1なのだから、補完開始位置を返すべきなんじゃ? Vimもちょっとおかしくて、-1を返されたら補完キャンセルとして振舞わなきゃダメなんじゃないかな。

**Comment by Shougo** [comment]
> これってネオコンの動作は変じゃないの? alwaysの為に再度ユーザ補完関数が呼ばれる時ってa:findstart==1なのだから、補完開始位置を返すべきなんじゃ?

はい。変ですけど、これが仕様です。
なぜこうなっているのかというと、neocomplcacheは先に候補を計算しているからですね。
これは補完候補がないときのチラツきをなくすため。
チラツかないための提案も却下されてしまったので、仕方がないのです。

> Vimもちょっとおかしくて、-1を返されたら補完キャンセルとして振舞わなきゃダメなんじゃないかな。

はい。これはそうだと思います。

**Comment by koron** [comment]
> はい。変ですけど、これが仕様です。
> なぜこうなっているのかというと、neocomplcacheは先に候補を計算しているからですね。

えっと…Vimの仕様にそぐわない挙動をしておいて、
その結果Vimが誤動作するって報告するのは変ですね。
原因は元から絶たなきゃ。
たぶんこのケースではa:findstart==1で4を返してa:findstart==0で[]を返すのが正しいのでしょう。
あとチラツキの問題はIssueありましたっけ? なければ書いておいてください。

> > Vimもちょっとおかしくて、-1を返されたら補完キャンセルとして振舞わなきゃダメなんじゃないかな。
> 
> はい。これはそうだと思います。

これはこれで実装したほうが良いと思いますが、
ネオコン含めて既存プラグインの動作が問題になりそうですね。
ちょいとこっちは私がIssue建てるので、そちらで別途議論しましょう。

**Comment by koron** [comment]
> > > Vimもちょっとおかしくて、-1を返されたら補完キャンセルとして振舞わなきゃダメなんじゃないかな。
> > 
> > はい。これはそうだと思います。
> 
> これはこれで実装したほうが良いと思いますが、
> ネオコン含めて既存プラグインの動作が問題になりそうですね。
> ちょいとこっちは私がIssue建てるので、そちらで別途議論しましょう。

この件 #99 を追加しました。

**Comment by mattn** [comment]
いま思ったけど

``` diff
+       if (col < 0 || compl_opt_refresh_always)
+       col = curs_col;
```

この部分、pumvisibleもいれた方がいい気がした。

**Comment by Shougo** [comment]
> あとチラツキの問題はIssueありましたっけ? なければ書いておいてください。

前Issuesを書きましたが、「自動補完の問題は興味がない」とKaoriyaさんに言われて結局却下されました。

実装が可能かどうか、誰が実装するかは別として、議論くらいはされるべきだと思っています。
Kaoriyaさんがもう一度議論して問題ない、というならもう一度作りますけど……。

**Comment by Shougo** [comment]
> えっと…Vimの仕様にそぐわない挙動をしておいて、
> その結果Vimが誤動作するって報告するのは変ですね。
> 原因は元から絶たなきゃ。
> たぶんこのケースではa:findstart==1で4を返してa:findstart==0で[]を返すのが正しいのでしょう。
> あとチラツキの問題はIssueありましたっけ? なければ書いておいてください。

うーん、現在の実装がその挙動に依存するようになっていて、おそらく修正するとまたチラつくでしょうし、いろいろと難しいのです。チラつきの問題さえなくなれば、prefetchなどでややこしいことをしなくても済むと思うので実装を変更するのは問題ないのですが、ちょっと今の段階では……。

**Comment by mattn** [comment]
> 前Issuesを書きましたが、「自動補完の問題は興味がない」とKaoriyaさんに言われて結局却下されました。
> 
> 実装が可能かどうか、誰が実装するかは別として、議論くらいはされるべきだと思っています。
> Kaoriyaさんがもう一度議論して問題ない、というならもう一度作りますけど……。

ソースどこですか？
チラツキの話と自動補完の話違うと思うので「興味ない」も違う話の流れの様な気がしますが。

**Comment by koron** [comment]
@mattn さんの言うとおりです。

チラツキ防止のためだけにプラグインが変なことをして、
それが別のバグを誘発するのであれば、そのことを前提に議論し直すべきでしょう。

以前のチケットがあるならば、まずはその参照を貼ってください。

**Comment by Shougo** [comment]
vim-jpのMLだったと思います。

こちらにはIssuesを立てていないので、立てておきました。

https://github.com/vim-jp/issues/issues/100

**Comment by Shougo** [comment]
> ソースどこですか？
> チラツキの話と自動補完の話違うと思うので「興味ない」も違う話の流れの様な気がしますが。

いいえ。実は密接に関係しています。詳しくは、私が立てたIssueを参照してください。

**Comment by Shougo** [comment]
> 以前のチケットがあるならば、まずはその参照を貼ってください。

確か、ここができる前に議論した話なので、ここにはIssuesがありませんでした。

> チラツキ防止のためだけにプラグインが変なことをして、
> それが別のバグを誘発するのであれば、そのことを前提に議論し直すべきでしょう。

はい。もともと、今回のrefresh=alwaysが実装されたのも、それが理由でしたよね。
私としても、チラつきを防止するために妙なギミックは入れたくないです。

**Comment by thinca** [comment]
> 以前の議論

https://groups.google.com/forum/#!topic/vim_jp/Ed3nUiyodIY
これですね。

**Comment by Shougo** [comment]
はい。そうです。

**Comment by koron** [comment]
@mattn さん: #99 の私の推測内容と、こちらのパッチが矛盾しているんですが、向こうの推測内容は間違ってますかねぇ?

特にこの部分、なんか違う気がしてきた。

> refresh=always指定の場合
> (中略)
> (refreshによる呼び出しで)補完関数がa:findstart==1で-1を返したあと、
> a:findstart==0、a:base=="(空文字列)"で再度補完関数を呼び出すべきところを
> a:base="(以前のleader)"になってるんだろう。

**Comment by mattn** [comment]
@koron

まずこの状態というのはalways指定で補完関数を自ら呼ばせるケース、かつカーソル位置はそのままでいてほしいという状態であること。a:findstart==1の戻り値として返す値が無い場合ってのはケースとしてありえると思ってます。
補完候補が変更されて、新しい補完開始位置を探したけどみつからなかった場合に、-1しか返す候補がないはず。

あとはvimの振る舞いとしてどっちが正しいかですが、１つは補完を停止する。もう一つは-1を返して空の補完を行わせる。
これがalwaysじゃなかった場合は、後者は不自然な動きにみえるので出来れば避けたいです。
alwaysの場合は僕個人としてはどちらでもよくて、補完をやめてしまっても良いですし、空の補完で続行しても良いと思ってます。

まぁ、僕はあまり使わない機能なので、希望者が多い方に倒したいと思ってます。

**Comment by mattn** [comment]
Patch 7.3.404

https://groups.google.com/d/topic/vim_dev/YtgEVpjjoGQ/discussion

あとは #100 の件でチラツキ修正パッチを送ります。

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplcache/issues/185

これ、私の環境で見た限りではまだ治っていないように見えます。
再現条件など、詳しい調査はしていませんけど……。

**Comment by mattn** [comment]
候補選択が表示された状態で何か文字を追加した時の処理にレジスタへの追加処理が必要っぽい。
もう少し要調査。

``` diff

diff -r 3482d151136b src/edit.c
--- a/src/edit.c    Wed Apr 25 19:07:41 2012 +0200
+++ b/src/edit.c    Mon May 07 12:53:19 2012 +0900
@@ -3472,10 +3472,14 @@
    (*mb_char2bytes)(c, buf);
    buf[cc] = NUL;
    ins_char_bytes(buf, cc);
+   AppendToRedobuff(buf);
     }
     else
 #endif
+    {
    ins_char(c);
+   AppendCharToRedobuff(c);
+    }

     /* If we didn't complete finding matches we must search again. */
     if (ins_compl_need_restart())
```

**Comment by Shougo** [comment]
ありがとうございます。

**Comment by mattn** [comment]
この件の追加パッチが 7.3.561 で入った。
これでようやく終止符？

**Comment by Shougo** [comment]
対応有り難うございました。

**Comment by Shougo** [comment]
最近、こういうpostがありました。

https://groups.google.com/forum/#!topic/vim_dev/yJyLLbOZPnQ

どうやら、ここでの変更が関係しているみたいですが……。
