### ISSUE TITLE
Test_help_complete が失敗する

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#970]
## 質問・報告の内容

src/testdir で `nmake -f Make_dos.mak win32` すると以下のようにテストが失敗する。

```
From test_alot.vim:
Found errors in Test_help_complete():
function RunTheTest[9]..Test_help_complete line 22: Expected ['h test-char@ab', 'h test-char@en', 'h test-col@ab', 'h test-col@en'] but got ['h test-char@en', 'h test-char@en\t', 'h test-col@ab', 'h test-col@en']
```
## Vimのバージョン

8.0.0039
(without any other patches)
## OSの種類/ディストリ/バージョン

Windows 10 Pro 64bit + MSVC10
## その他

具体的には [`s:get_cmd_compl_list(":h test")`](https://github.com/vim/vim/blob/156919f99afd1ac11d19d4270afbc1afb7245640/src/testdir/test_help_tagjump.vim#L114) の結果がおかしい、のだが、
直前の行に `sleep` を挟んで以下のようにするとテストはパスする。

``` viml
set rtp+=Xdir1/doc-ab
set helplang=
sleep 100m
let list = s:get_cmd_compl_list(":h test")
call assert_equal(sort(['h test-col@en', 'h test-col@ab',
      \             'h test-char@en', 'h test-char@ab']), sort(list))
```

とてもいやらしい。

**Comment by koron** [comment]
vim-win32-installer では起こってないし、私のローカル環境特有の問題であり、
かつ回避方法があるので調査・修正の優先順位は低い。

ただし 8.0.0003 の時は無かった症状なので、
その後 0039 までの間の変更によるものだと考えられる。
気が向いたら bisect するのが良さそう。

なにか気がついたことがあったらコメントいただけるとうれしいです。

**Comment by koron** [comment]
8.0.0082 で再現しなくなった。 +kaoriya での確認だけど、
特になにかをしたわけではないので解決されたとみなして良いでしょう。

**Comment by h-east** [comment]
再オープンします。
この件、Bram氏も把握しておりデバッグに難航しているようです。
https://groups.google.com/d/msg/vim_dev/Zz3pHJUm7xY/Ckz3z0PHBgAJ

> Only happens in console version.

私としては`s:get_cmd_compl_list()`で補完リストを取得する方法が無理やり感があるので、そこをsimpleな実装に書き換えて問題が出なくなればひとまずはそれで良いかなと考えています。
(`s:get_cmd_compl_list()`書いたの私です。汗）
simple実装案2つほど持ってますので再実装して提案してみます。

いや、まずその前に`sleep 100m`入れると安定するという情報を提供するのが有効かも。

**Comment by h-east** [comment]
patch 8.0.0091
https://github.com/vim/vim/commit/9f0e423c2818c0cacd0810f9c3c67cbb6b80963d

コマンドラインの文字列を無理やり変数に入れるhackをやめて`getcompletion()`を使うように変更されました。
https://github.com/vim/vim/commit/9f0e423c2818c0cacd0810f9c3c67cbb6b80963d#diff-a700bb3161e3a175a23c2688e28c315fL84

これで解消されると思います。

# 

送信したpatch
https://groups.google.com/d/msg/vim_dev/Zz3pHJUm7xY/830AnPv7BgAJ
