### ISSUE TITLE
matchaddpos() が行を描画しない

### ISSUE THREAD

**Issue by rickhowe** [vim-jp/issues#971]
8．0.0039 にて #966 の修正を確認いたしました。どうもありがとうございました。

ただし、今度は
`matchaddpos('Error', [[1]])
`
のように、行のみの pos が描画されなくなっているようです。

そのほかの修正の影響かもしれませんが、よくわかりません。

**Comment by h-east** [comment]
@rickhowe あぅ、、
このpatchで確認をお願いします。
https://gist.github.com/h-east/90f60b514295dd78081316bb4941a9b9

testは後で足します。

**Comment by h-east** [comment]
Sent patch to vim_dev.
https://groups.google.com/d/msg/vim_dev/UKULiYiNSaI/sDcYTT_gBAAJ

**Comment by h-east** [comment]
patch 8.0.0040
https://github.com/vim/vim/commit/8507747600bddfd6a68aed057840856bf5548e61

**Comment by ichizok** [comment]
すみません...修正ありがとうございました。

**Comment by rickhowe** [comment]
確認しました。直ってますね。
