### ISSUE TITLE
デュアルモニタで「変更を "無題" に保存しますか？」ダイアログが常にメインモニタ上に現れてしまう

### ISSUE THREAD

**Issue by tyru** [vim-jp/issues#975]
## 質問・報告の内容

デュアルモニタ環境でサブモニタのワークスペース上に GVim を持っていって、バッファに変更がある状態でウインドウを閉じるため×ボタンを押して「変更を "無題" に保存しますか？」ダイアログを表示させると、ダイアログが常にメインモニタ上に現れてしまいます。

## Vimのバージョン

8.0.3

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (バージョン 1607 (OS ビルド14393.351))

## 使用している or 関係していそうなプラグイン

なし（スクリーンショットは `gvim.exe -u NONE -i NONE -N` での様子です）

## スクリーンショット

左がメインモニタ、右がサブモニタです。
サブモニタに GVim があるにも関わらず、メインモニタの方にダイアログが現れてしまっています。

![cwgpejkukaafruc](https://cloud.githubusercontent.com/assets/48169/20030649/c69aa296-a3ac-11e6-9ebe-62076cffe654.jpg)

**Comment by k-takata** [comment]
gui_w32.c / CenterWindow()の中で、マルチモニタ対応のget_work_area()という関数を使わずにSystemParametersInfo()を使っているのが原因ではと思ったのですが、未検証です。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/5L2xi4Y8LfQ/discussion
CenterWindow() が全然マルチモニタに対応できていませんでした。

**Comment by tyru** [comment]
ありがとうございます！

**Comment by k-takata** [comment]
8.0.0113
https://groups.google.com/d/topic/vim_dev/V3DBGSUn3dc/discussion

**Comment by tyru** [comment]
ありがとうございます。
