### ISSUE TITLE
[count]tabnextの挙動が[count]tabcloseや[count]tabonlyなどのcountの解釈と異なる

### ISSUE THREAD

**Issue by itchyny** [vim-jp/issues#976]
## 質問・報告の内容
`:.+2tabnext` が現在のタブの2つ右ではなくて、常に3番目のタブに移動する。

```
:tabnew
:tabnew
:tabnew
:tabnew
:tabnew
:4tabnext (ここまではよい)
:.+2tabnext
```
結果、3番目のタブに移動する。

`:.+2tabclose` は現在のタブの2つ右を閉じる挙動なので、これと同じように現在のタブの2つ右に移動するのが自然だと思います。また、 `$tabnext` は一番最初のタブに移動するようですが、最後に移動するほうが自然だと思います。

https://twitter.com/itchyny/status/795664235397136384

## Vimのバージョン

8.0.71

( `:version` で確認できます)

## OSの種類/ディストリ/バージョン

*   macOS Sierra

## 使用している or 関係していそうなプラグイン

`vim -u NONE`

## その他
ヘルプを見たら `[count]tabnext` についての言及は見当たらないので未定義かもしれないです。
tabpreviousも関連しそうです。今の挙動は `:.+2tabprevious` = `3tabprevious` (= `3gT`) に見えますがこれでよいのかどうかよくわからないです。

**Comment by h-east** [comment]
patchです。確認をお願いします。
https://gist.github.com/h-east/4d42bf152311600c6a11ac06a292d14d

@itchyny issue登録ありがとうございます:+1:

**Comment by itchyny** [comment]
> 常に3番目のタブに移動する

じゃなくて(カーソル行番号+2)番目ということですね… タブの移動のコマンドがカーソル行に依存して挙動が変わるのがおかしいということを主張すれば通せそう。

**Comment by h-east** [comment]
tabnextのtestを追加しました。(rev.2)
tabpreviousのtestを追加したらエラーが出たので一時的にコメントアウトしています。後で調査します。
https://gist.github.com/h-east/4d42bf152311600c6a11ac06a292d14d

**Comment by h-east** [comment]
`tabprevious`と`tabNext`はカウントの体系が他のタブコマンドと異なってますね。常に前方のタブページへの相対指定になってます。他と合わせた方が良い気もしますけどどうでしょうか？。
(その場合、`:+3tabnext`と`:-3tabNext`は同じ動作になる？？)

あと、後方カウント指定で`+2`や`-3`等の相対指定や`$`が出来るのは現状で`tabmove`だけかな？

``` vim
:tabmove +2
:tabmove -3
:tabmove $
```

これを`tabclose`, `tabonly`, `tabnext`, `tabprevious`, `tabNext`で採用してもいいかも。
(`:tabnext $`は`:tablast`があるだろって突っ込みは分かる)

**Comment by h-east** [comment]
patch更新しました。(rev. 4)
https://gist.github.com/h-east/4d42bf152311600c6a11ac06a292d14d
`:tabnext`を後方カウント指定可能にしました。

``` vim
tabnext
tabnext 1
tabnext $
tabnext +
tabnext -
tabnext +2
tabnext -3
...
```

**Comment by ryunix** [comment]
本件と類似で`{count}gT`の挙動が直感的ではなかったので報告させていただきます。

以下は日本語ヘルプから引用
`{count}gt`: {count} 番目のタブページに移動します。
`{count}gT`: {count} の数だけ前のタブページに移動します。

**Comment by ryunix** [comment]
今気付いたのですが、直感的でないのは`{count}gt`のほうですね :sweat:

**Comment by itchyny** [comment]
gtの挙動を変えるのは互換性の関係で難しい気がします… https://groups.google.com/d/msg/vim_dev/CTIIpzvcATY/KGBQxExtCAAJ

**Comment by h-east** [comment]
なるほどです。ということは、`tabprevious`と`tabNext`~~の~~**については**カウント体系~~は変えないほうがよさそうだし、~~**(**後方カウント指定も**含む)は変更**~~対応~~しないほうが良さそうですね。
それか再提案チャレンジするか。でも1年経ってないしやめとこう。

**Comment by itchyny** [comment]
全体引用しているからBramの `the current behavior` がどれなのかよくわからないですね… `{count}gt` の挙動を変えるのはきびしそうだけど `:tabnext +{count}` を変えるのはいけるんじゃないかという印象なのですが、いかがでしょうか。

**Comment by h-east** [comment]
私のさきほどのコメントは「`tabprevious`と`tabNext`」(`gT`)に対してです。相対指定が基本になっているのでどうしようもないかなぁと。
`tabnext`は変える気マンマンですよ:+1:

**Comment by itchyny** [comment]
おっとすみません、後方カウント指定を読み違えてしまったようです 🙇   頼もしいです。

**Comment by h-east** [comment]
こちらこそ微妙な文章でした :bowing_man:
https://github.com/vim-jp/issues/issues/976#issuecomment-261150065 をわかりやすい文章に編集しました。

**Comment by h-east** [comment]
patch更新しました。(rev. 5)
https://gist.github.com/h-east/4d42bf152311600c6a11ac06a292d14d

- `:tabNext`,`:tabprevious`の前方カウント指定を数字だけにした(どうせ相対だけですし)。後方カウント指定に対応した(数字のみ)
- `:tabnext`を後方カウント指定に対応した(数字のみで絶対指定、`+`か`-`付きで相対指定、`$`で最後のタブ)

調整中：
- `:0tabnext`,`:tabnext 0`を受け付けてしまっている。
- `:tabnext 99`,`:tabnext +99`,`:tabnext -99`を受け付けてしまっている。(じつは`:tabmove`も)

**Comment by h-east** [comment]
patch更新。(rev. 6)
コーディング完了、test追加。
残すはドキュメントのみ！

patchのtest_tabpage.vimの差分を見ればどういう動きをするか分かると思う。

**Comment by h-east** [comment]
patch更新。(rev. 7)
完成。

@itchyny and All>
時間のある時に動作確認をお願いします。気になったところがあればコメント下さい。

PS
`:tabonly`も後方カウント対応した方が良いかもしれないけど、今回はやめときます。

**Comment by itchyny** [comment]
動作確認しました。tabnext/tabpreviousのrangeと後方カウントの組み合わせで試してみまて、意図通りに動くようになったのを確認しました。ありがとうございます！

**Comment by itchyny** [comment]
`change the tab page to the {left,right,first,last}` → `go to the {previous,next,first,last} tab page` のほうが良さそうかなと思いました。

**Comment by h-east** [comment]
@itchyny 確認&提案thanks. help修正しました。(ｒev. 8)

**Comment by k-takata** [comment]
> :-tabnext	" go to the tab page to the previous

@itchyny さんの指摘の通り、"go to the previous tab page" の方が自然だと思います。ほかも同様。
あと "Both absolute and relative tab page numbers can be used." とか追加しておくとどうでしょう。

**Comment by h-east** [comment]
@k-takata あっ、 @itchyny さんの指摘どおりに直したつもりになってました。汗。直しました(ｒev. 9)。Thanks:+1:

> あと "Both absolute and relative tab page numbers can be used." とか追加しておくとどうでしょう。

`[range]`自体がそういう仕様なので明記しなくてもいいかも。ただ、`:tanprevious`と`:tanNext`の方は相対指定できないのでそっちに以下の文章を追加しました。
```
Only absolute tab page numbers can be used.
```

**Comment by k-takata** [comment]
そっちだと、"Only absolute {count} can be used." とすべきでしょう。
表記の {count} としては絶対指定ですが、動作としては現在のタブに対する相対番号なので、これでも誤解を招きそうな気もしますが…

**Comment by h-east** [comment]
うーん、悩んだ末に `Only absolute tab page numbers can be used.`消しました。(rev. 10)

**Comment by h-east** [comment]
patch更新。(rev. 11)
- `:tabonly`を後方カウント指定に対応した(数字のみで絶対指定、+か-付きで相対指定、$で最後のタブ)

残
- `:tabclose`も対応したんですが、`make test_tabpage`がfailするのと`make test`でSEGVするので一旦コメントにしています。要調査。
- Write document and test for `:tabonly`and`:tabclose`

**Comment by h-east** [comment]
patch更新。(rev. 12)
- `:tabclose`を後方カウント指定に対応した(数字のみで絶対指定、+か-付きで相対指定、$で最後のタブ)
- `make test_tabpage`がfailしないようにtestを修正。(←いいのか！？)
- `make test` ALL DONE.

残
- Write document and test for `:tabonly`and`:tabclose`

**Comment by h-east** [comment]
patch更新。(rev. 13)
https://gist.github.com/h-east/4d42bf152311600c6a11ac06a292d14d

- Write document for `:tabonly`and`:tabclose`

残
- Write test for  `:tabonly`and`:tabclose`
- `make test_tabpage`がfailしないようにtestを修正。(←ほんとにそれでええんか！？)

**Comment by h-east** [comment]
patch更新。(rev. 14)
- `:tabonly`と`:tabclose`のテストを書いた。
- `:tabonly`のカウント指定値が不正な場合にエラーを表示しつつも処理を続行していたバグを修正。

残り
- `test_tabpage.vim`の既存のテスト1ケースが通らないのでコメントにしてある。(今回エラーチェックが厳しくなった影響。テストが通るようにパラメータを変更すべき)

**Comment by h-east** [comment]
Sent to vim_dev:+1:
https://groups.google.com/d/msg/vim_dev/sFJvAIX6p8I/VQBa3cexCwAJ

**Comment by h-east** [comment]
patch 8.0.0259
https://github.com/vim/vim/commit/2f72c70657129c16e6b0e413752a775c804f02f8

@itchyny Thanks for the reporting this:+1:

**Comment by itchyny** [comment]
Thank you!
