### ISSUE TITLE
'guioptions' の初期値が :help と実際とで違う

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#98]
`'guioptions'` の初期値は `:help` では以下のようになっている。

> 'guioptions' 'go'       string  (default "gmrLtT"   (MS-Windows),
>                                          "agimrLtT" (GTK, Motif and Athena))

しかし、実際に起動してみると少し違う。(`gvim -u NONE -N` で起動)

MS-Windows: `egmrLtT`
GTK(Linux): `aegimrLtT`

比較すると、eが追加されている。
これはドキュメントの修正漏れ? それとも環境によるもの?

**Comment by koron** [comment]
修正漏れでしょう。

タブの機能は比較的最近追加されたので。

**Comment by koron** [comment]
ソースコードの初期化部分の内容を確認し、
- ドキュメントの修正漏れであればドキュメント修正パッチを作る
- それ以外なら再度検討

というところか。

**Comment by ynkdir** [comment]
報告しました。

**Comment by ynkdir** [comment]
修正されました。
