### ISSUE TITLE
PYTHONHOMEをif_pythonとif_python3に同時に設定できない

### ISSUE THREAD

**Issue by splhack** [vim-jp/issues#982]
## 質問・報告の内容

PYTHONHOMEをif_pythonとif_python3に同時に設定できないので、pythonhome, pythonthreehomeを足してみました。が、Travis-CIが失敗してる状態です。誰か助けてください...

https://github.com/vim/vim/pull/1266

## Vimのバージョン

8.0.???

## OSの種類/ディストリ/バージョン

UNIX系

**Comment by ichizok** [comment]
`PYTHON3_HOME` は `L"/usr"` のようにワイド文字列で定義されるので、`p_py3home` のデフォルト値としてうまく扱えないのでは？

**Comment by k-takata** [comment]
`'\0'` は `NUL` がよろしいかと。

**Comment by h-east** [comment]
> `'\0'` は `NUL` がよろしいかと。

私も同じツッコミをしようと思ったんだけど、if_py*.[ch]は既に`'\0'`が使われていたのでやめました。

**Comment by k-takata** [comment]
おっ、確かに。では、なしで。

**Comment by mattn** [comment]
@ichizok さんの言うようにワイド文字です。僕も vim でハマった記憶あります。

**Comment by k-takata** [comment]
`PYTHON3_HOME` を wide 文字から char に変えてしまって、

```C
#define TOWIDE(str) L##str

Py_SetPythonHome(TOWIDE(PYTHON3_HOME));
```

というのはどうだろう？
`configure.ac` と `Make_cyg_ming.mak` も修正対象になってしまうので、ちょっと注意が必要ですが。

**Comment by k-takata** [comment]
`PYTHON3_HOME` を wide 文字から char に変えてしまって、

```C
#define TOWIDE(str) L##str

Py_SetPythonHome(TOWIDE(PYTHON3_HOME));
```

というのはどうだろう？ そうすれば、`p_py3home` のデフォルト値として使えるようになります。
`configure.ac` と `Make_cyg_ming.mak` も修正対象になってしまうので、ちょっと注意が必要ですが。

**Comment by splhack** [comment]
ありがとうございます! p_pyhome, p_py3homeのデフォルトはNULLでよかったのでした。
- pythonhome, pythonthreehomeが設定
  - されている → Py_SetPythonHomeでそれを設定
  - されてない → 次へ
- PYTHONHOME環境変数が設定
  - されている → なにもしないでPythonライブラリにまかせる
  - されてない → 次へ
- コンパイル時PYTHON_HOME/PYTHON3_HOMEをPy_SetPythonHomeで設定

**Comment by splhack** [comment]
MacVimにはexperimentalとして入れちゃいました。一般的な組み合わせを何の設定もせずバイナリリリースで使えるようにするため。

- Python 2.7
  - macOSに最初から入ってる
  - Homebrew python
- Python 3.5.2 or later
  - Homebrew python3
  - https://www.python.org/downloads/mac-osx/

**Comment by k-takata** [comment]
8.0.1451: https://github.com/vim/vim/commit/94073167e3aa8cbe18380e93a2fc8e8165438cc8
1年以上掛かってしまいましたね。

**Comment by mattn** [comment]
closed な issue ですが関連という事で。 https://github.com/vim/vim/pull/2787#event-1565935255

[8.0.1683](https://github.com/vim/vim/commit/0424958bde3d3e74c721ba39ab4d5a4744897393) にてビルド時に PYTHON_HOME と PYTHON3_HOME を設定しない様になりました。
