### ISSUE TITLE
乱数が欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/issues#983]
Vimmer「乱数が欲しい」
Bram「テキストエディタだから...」
Vimmer「ほしい！」
Bram「何に使うねん」
Vimmer「げっゲームとか...」
Bram「はいはい撤収」

**Comment by mattn** [comment]
https://gist.github.com/mattn/3dea45366d1733abeb0839faafa2b53f

できた。

**Comment by thinca** [comment]
必要最低限っぽいですね。本気で入れるならもうちょい便利にしたい感じはあります。
srand は seed の初期化ですが、複数のプラグインから使われる Vim script においてグローバルな srand が1つ提供されてもビミョウな気がします。
srand は意識せずに使えるようにするか、各プラグインが同時に使っても大丈夫なようにオブジェクト的なサムシングをするか、どちらかに振り切るのが良い気がします。

**Comment by mattn** [comment]
パッチ書きながらその辺を考えてたんですが、そうなるともう timer_start や job_start みたいなコンテキストを持つしかないのでどうしようかなーと思った次第。ひとまず叩き台として意見募集。

**Comment by thinca** [comment]
そうなんですよね。Vim script は今のところ組み込み関数としては「オブジェクト」という概念を持っていないので、難しいところ…。いっそオブジェクト追加したい…(ﾎﾞｿｯ (とんでもない yak になる気配しかない)

**Comment by thinca** [comment]
あー。コンテキストですが、例えばコンテキストを bind した partial を生成しちゃうってのは…アリですかね? これがアリだと、メソッド1つだけのインスタンスみたいなものはアリって感じになる。
とは言え、一般的な言語の乱数オブジェクトみたいにメソッド色々生やしたいってなった時点で詰んじゃうので拡張性に難ありですが。

**Comment by tyru** [comment]
簡単にできそうな案として、salt を受け取るとかどうでしょう。

**Comment by mattn** [comment]
xorshift みたいに種から乱数作れる物ならなんでもいいんですよねー。

**Comment by mattn** [comment]
xorshift 版を作ってみた。

https://gist.github.com/mattn/95fef8b7c81ce37ed2fff2a110cc7f78

```vim
let a = srand(-1)
echo rand(a)
echo rand(a)
echo rand(a)
echo rand(a)
echo rand(a)
```

```
111389043
1045553471
1326496467
42854537
427700634
```

srand の引数が負なら time(NULL) で初期化、未指定なら  xorshift お馴染みの 123456789、指定ありならその数値で初期化。

**Comment by mattn** [comment]
ちなみに a は整数4つの配列でしかない。

```vim
echo srand()
[123456789, 362436069, 521288629, 88675123]
echo srand(-1)
[1479837050,, 362436069, 521288629, 88675123]
echo srand(2)
[2, 362436069, 521288629, 88675123]
```

**Comment by tyru** [comment]
こんな記事がありました（どの程度影響があるのか分かってないですが）。

http://d.hatena.ne.jp/gintenlabo/20100925/1285432088

> それは乱数の種を与えて初期化するときの処理で、種を 8bit ずつ rotate したものを用いています。
これは、主に乱数の種として time 関数の戻り値が使われた場合を想定したもので、
その場合、種の下位 bit の方は多様性がありますが、上位 bit の方は殆ど一定と考えられるので、
単純に与えられた種から設定するのではなく、多様性のある部分が少しでもバラけるよう配慮してみました。

**Comment by mattn** [comment]
僕の記憶だと、x の変更だけで十分バラけてた気がしますけどね。シフトしてるので。

**Comment by tyru** [comment]
なるほどです。

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/1277

**Comment by k-takata** [comment]
> Bram「何に使うねん」

予想通りの反応ｷﾀｺﾚｗ

**Comment by thinca** [comment]
テスト落ちてますね。`+num64` の有無で行うべき処理が変わりそうな予感? (ちゃんと見てないですが)

**Comment by thinca** [comment]
テスト落ちてる部分貼っておきますね。

```
From test_rand.vim:
Found errors in Test_Rand():
function RunTheTest[13]..Test_Rand line 3: Expected 597902826 but got 252977563114
function RunTheTest[13]..Test_Rand line 4: Expected 458295558 but got 646616338854
function RunTheTest[13]..Test_Rand line 5: Expected 1779455562 but got 476657867818
function RunTheTest[13]..Test_Rand line 6: Expected 663552176 but got 294684809458
function RunTheTest[13]..Test_Rand line 7: Expected 507026878 but got 517442357777055
```

**Comment by umireon** [comment]
門外漢ですが、XorshiftはLCGの一種なので、初期状態と出力系列の間には線型性があります。
したがって、初期状態の一部にでも定数を与えると、シード値によらず初期系列が常に似たような値になります。
（一方で、統計的な性質にはほとんど影響しません）
多少煩雑でも、与えられたシード値のみを用いて全ての初期状態を生成する方が、PRNGの実装としてはより妥当かと思います。
例えば、[Murmurhashのアバランチ関数](https://github.com/aappleby/smhasher/blob/61a0530f28277f2e850bfc39600ce61d02b518de/src/MurmurHash3.cpp#L68)や[メルセンヌ・ツイスタの初期化関数](https://github.com/MersenneTwister-Lab/TinyMT/blob/master/tinymt/tinymt32.c#L85)などを用いる方法があります

**Comment by k-takata** [comment]
8.1.2342: https://github.com/vim/vim/commit/06b0b4bc27077013e9b4b48fd1d9b33e543ccf99
(and [8.1.2356](https://github.com/vim/vim/commit/f8c1f9200c4b50969a8191a4fe0b0d09edb38979), etc.)
