### ISSUE TITLE
テスト実行後に test29.in の改行コードが書き換わる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#986]
## 質問・報告の内容

Windows で、テストを実行すると (src/testdir で nmake -f `Make_dos.mak win32`)
test29.in の改行コードが書き換わる。

## Vimのバージョン

8.0.0095

## OSの種類/ディストリ/バージョン

*   Windows 10 Pro 64bit (10.0.10586) + MSVC10

---

戻せば良いので実害はないが、書き変わりっぱなしになるのはちょっと気持ち悪い。

**Comment by koron** [comment]
そのうち調べる。

**Comment by k-takata** [comment]
8.1.1331 で test29 は新形式のテストに差し替わりました。
