### ISSUE TITLE
v:register が更新されない場合がある

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#988]
### 再現例と期待値

例えば何かの文字の上で以下の操作を実行します。

```
"_x:echo v:register<CR>
```

結果は以下になります。

```
_
```

期待する結果は以下です。

```
"
```

### 解説と補足

上記の例では `"_` レジスタを指定して `x`(1文字消す) を実行し、その後 `:echo v:register` で `v:register` の中身を確認していますが、`_` の指定は `x` の実行で処理されているため、その後のコマンドでは `v:register` はデフォルトの `"` に戻っているべきです。
実際、`"_x` の後でレジスタの確認を行わずに再度 `x` を実行すると、切り取った文字はデフォルトレジスタ `""` に入ります。
~~いくらかパターンを試しましたが、`dd` などの行が変わるようなコマンドを実行した場合は `v:register` の中身はきちんと更新されるようです。~~
↑これは私の環境がおかしかったようです。(追記)

`"_xxxx` のように連続で行った場合も、`v:register` は最後まで `_`  のままのようです。しかし、2回目以降の x の結果は `"` レジスタに格納されています。(追記)

## Vimのバージョン

8.0.0104

## OSの種類/ディストリ/バージョン

-  Windows 10 Pro 64bit
  - Vim 8.0.0055
-  Gentoo Linux 64bit

## 使用している or 関係していそうなプラグイン

なし

## その他

以下のページで報告されていたのがきっかけです。
[Vim - Vim script の v:register の使い方(56661)｜teratail](https://teratail.com/questions/56661)

**Comment by ghost** [comment]
~~~~diff
diff --git a/src/normal.c b/src/normal.c
index ce8ca53..49a6756 100644
--- a/src/normal.c
+++ b/src/normal.c
@@ -7630,6 +7630,8 @@ nv_regname(cmdarg_T *cap)
 #endif
     if (cap->nchar != NUL && valid_yank_reg(cap->nchar, FALSE))
     {
+	if (cap->nchar == '_')
+	    return;
 	cap->oap->regname = cap->nchar;
 	cap->opcount = cap->count0;	/* remember count before '"' */
 #ifdef FEAT_EVAL
~~~~
それはそうだなという感じですね…。

**Comment by machakann** [comment]
ありがとうございます、元の質問をした者です。

パッチをあてて試してみると

```
"_x:echo v:register<CR>
```

の例は `"` を返すようになりましたが、そもそものブラックホールレジスタ `"_` が機能しなくなっているようです。常にデフォルトレジスタ `""` が更新されています。

**Comment by ghost** [comment]
了解しました。このことを含めいわゆるビルド後のテストで検出できるかというところも調べます。
(またやばいところに手を出してしまったのだろうか…(;´Д`))

**Comment by k-takata** [comment]
eval.c 内の set_reg_var() を呼び出すと、`v:register` の値が更新されるわけですが、その呼び出しが足りないのかな？

**Comment by k-takata** [comment]
https://github.com/vim/vim/pull/5305 で直るのだろうか？

**Comment by machakann** [comment]
Christian Brabandt さんが前にパッチを書かれたんですけど、Bram さんは今の機能が正しいというスタンスみたいなんですよね…

https://groups.google.com/forum/#!msg/vim_dev/GiIKJLzH-AM/8rvajv8YkMQJ

https://groups.google.com/forum/#!searchin/vim_dev/%5BBUG%5D$20Value$20of$20$27v$3Aregister$27$20updates$20too$20late%7Csort:date/vim_dev/GIRqdUm0xVI/Aqh3seiBHgAJ

**Comment by machakann** [comment]
v:register の挙動を変更するのではなく `""{operator}` のように指定されたのか、単に `{operator}` のように省略されたのかがわかれば一応問題は大体解決する気がするけど、どうだろう。

**Comment by andymass** [comment]
Christian's patch didn't work right for some cases and didn't have tests.

I don't think the current behavior makes any sense, hopefully Bram reconsiders at this point.

**Comment by machakann** [comment]
@andymass Thank you, and I agree. Without that kind of fix, there is no hope to handle register appropriately.

**Comment by k-takata** [comment]
Fixed in [8.2.0929](https://github.com/vim/vim/commit/cc613031b96f1cfa5a184253e745c26f1def9be4).
