### ISSUE TITLE
:filter! の help がない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#989]
## 質問・報告の内容

patch 7.4.2263 にて `:filter` の逆バージョンである `:filter!` が実装されましたが、help に記載がないようです。

- `:help :filter!` => `E149: Sorry, no help for :filter!`
- `:help :filter` => `!` についての記載は特になし

## Vimのバージョン

8.0.0104

**Comment by k-takata** [comment]
Fixed.
https://github.com/vim/vim/commit/214641f77df6f318a4b3a0b09723c19859a103f4
