### ISSUE TITLE
:filter の {pat} が / で囲まれていないと {command} の補完が効かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/issues#991]
## 質問・報告の内容

表題の通り、`:filter {pat} {command}` の、`{pat}` が `/` で囲まれている場合のみ `{command}` 部分の補完が効きます。

```vim
" 補完が効く(コマンドライン末尾で <Tab> や <C-d> をタイプしてコマンド一覧が表示される)
:filter /foo/ 
:filter /hoge\/huga/

" 補完が効かない
:filter foo
:filter @hoge/huga@
" ↑{pat} には :s などと同様に / 以外が使えます
```

実装の都合かもしれませんが、補完が効くのが期待される動作かと思います。

## Vimのバージョン

8.0.0104

## OSの種類/ディストリ/バージョン

以下で確認

- Windows 10 Pro 64bit
- Gentoo Linux 64bit

**Comment by ichizok** [comment]
補完できない箇所で `<TAB>` や `<C-D>` を打つと `^I` や `^D` になりますが、表示されない方がいいですか？
https://gist.github.com/ichizok/3256df050c35885dc06c867825ce6893

**Comment by thinca** [comment]
パッチありがとうございます！！
他のコマンド (`:global` のパターン部分とか) も表示されるようなので、表示されて良いと思います。

**Comment by ichizok** [comment]
https://github.com/vim/vim/pull/1299
PR投げました。

**Comment by h-east** [comment]
@ichizok :+1:
vim_devに変な英語でお願いしたけど:sweat_smile:、GitHub経由のPRの場合とvim_dev直メールの場合のauthor nameは結び付けておいた方が良いと思いました。

**Comment by ichizok** [comment]
了解です。ご指摘ありがとうございます。

**Comment by ichizok** [comment]
todo入り。
https://github.com/vim/vim/commit/bc2eada5424bff06f7eb77c032ecc067da52b846#diff-38d7929bd26d74d92ceddf984bbfc8dbR112

**Comment by h-east** [comment]
patch 8.0.0150
https://github.com/vim/vim/commit/7069bf18e1b1b7bc7640335e07d1022b5acc9048
