### ISSUE TITLE
画面描画が遅くなる

### ISSUE THREAD

**Issue by koron** [vim-jp/issues#994]
## 報告の内容

Windows 10 の gvim において、ウィンドウ(正確には Vim text area) の下端が、ある線を超えると画面描画が遅くなります。その度合は様々な条件で異なりますが、最終的なトリガーはそこでした。

また **ある線** はタスクバー(の上端の位置?)に依存しているようです。1920x1200のモニターにおいて、タスクバーを常時表示したデフォルトの状態ではウィンドウの下端がY座標 1130 以上になった場合に症状が発生していたのですが、タスクバーを自動的に隠す設定に変えた際にはその閾値が 1170 に引き上がりました。

遅くなるのが顕著な条件は以下のとおりです。実際にどのくらい遅くなるのかは計測していませんが、これらの条件を満たすと、一度スクリーンがクリアされた後に行単位で描画されているのを目視で確認できるほどです。

* DirectXによる描画をしている (`:set renderoptions=type:directx`)
* `vsplit` 状態
* <kbd>Ctrl</kbd> + <kbd>F</kbd> のような順方向の1画面スクロール実行時(逆方向では観測できない)
* Vimのウィンドウの下端を、画面下部のタスクバーの上端に近い場所に配置する

  (逆にそこから離す(=上に移動させる)と症状は観測されなくなる)

加えて以下の設定がこの症状に影響を与えないこと、は確認済みです。

* ウィンドウの影の有無
* タスクバーの背景が半透明かどうか

また DirectX を使わない pure GDI による描画においても、 DirectX 使用時ほどではないですが描画遅延は発生しているようです。

とりあえず気になって調査したので記録のためにissue化しておきました。

## Vimのバージョン

* 8.0.95 (+kaoriya)
* 8.0.133 (vim-win32-installer)

## OSの種類/ディストリ/バージョン

* Windows 10 Pro 64bit (バージョン 1607)

## その他

将来の調査に際しては、以下の点がいとぐちになる可能性があります。

* ウィンドウの下端の位置がトリガーになっている
* pure GDIでも発生している
* DirectXのほうが相当に速度低下が激しい
* `columns` の値には関係なく `:vsplit` すると顕著になる

またこの症状は、グラフィックボード(RADEON HD7700系)を積んだデスクトップPCと、CPU (Core m5) に内蔵のGPUのノートPC、2つで確認しました。よってグラフィックボードやドライバーへの依存はないと推測されます。

**Comment by koron** [comment]
これ、描画そのものよりもクリアのほうに時間かかってるかもしれない。

**Comment by koron** [comment]
vsplit していなければさほど遅くない例

![vsplitしていなければさほど遅くない](https://cloud.githubusercontent.com/assets/468368/21718114/6c4d4974-d458-11e6-93c2-6968a1a5f390.gif)

vsplit しちゃうとえらく遅い例

![vsplit しちゃうとえらく遅い例](https://cloud.githubusercontent.com/assets/468368/21718133/91d01f14-d458-11e6-9325-52a2e2f5ef09.gif)

**Comment by mattn** [comment]
ずいぶん目立ちますね。分割右側は再描画掛かってないすね。

**Comment by koron** [comment]
なんか不思議ですよね。
よく見てみると描画そのものよりもクリアのほうが遅いように見えてきます。

**Comment by koron** [comment]
> gui_w32.c の `get_scroll_flags()` がウィンドウが縦に大きくなった際に `SW_INVALIDATE` を返すようになってました。で、これは ScrollWindowEx の最後の引数になってて、全体の再描画を発生させるんじゃないかなぁと。

**Comment by koron** [comment]
2019/04/04 現在、自分の主な環境では再現しなくなりました。

* Win10 (1809)
* GTX750Ti 及び GTX1050Ti (+最新の(GEFORCE GAME READY)ドライバー: 419.67)
* Vim 8.1.1048 +kaoriya (gvim)
* `gfn=Cica:h9 linespace=1 rop=type:directx,renmode:5 enc=utf-8`

帰宅後Intelの内蔵グラフィック (Surface Go等)でも試す予定。

現時点で考えられる可能性は3つ。

* Vim の方になにかしらの修正が入った (gui_w32.c をチェックすればわかるはず)
* Win 10 の更新により修正された (再現条件を整えるのは私にはほぼ不可能)
* グラボの変更で解消された=特定のドライバでは問題が発生しない (ノートPCで動作確認が可能)

**Comment by k-takata** [comment]
そもそも、8.0.1343 のカラー絵文字対応&DirectX高速化パッチ、および 8.0.1476 までの複数の高速化パッチでかなり状況が変わっているはず。スクロールも 8.0.1449 以降はDirect2Dを使っていますし。

**Comment by ghost** [comment]
私は set ttyscroll=1 で様子を見ています。デフォルトは =999 のはずです。

**Comment by koron** [comment]
では解消されたってことで、本 issue は閉じます。再発した人がいたら再度開くってことで。
