### ISSUE TITLE
起動時の既存コマンド削除方法

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#997]
## 質問・報告の内容
プラグインで作られるコマンドで、使わないので補完の対象から外す為に、起動時に削除したいのですが、どうすればスマートでしょう?
autocmd BufWinEnter * if v:vim_did_enter == 0 | silent delcommand Explore | endif
を vimrc に書き込んでいますが、もっとスマートな方法はないかな? と

最初 ~/.vim/after/ftplugin.vim に
delcommand Explore
とすれば良いかな? と思ったのですが、上手く行きませんでした

dein.vim でプラグインを管理をしており
set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim
としているので、runtimepath が
runtimepath=~/.vim,/var/lib/vim/addons,~/.vim/bundle/repos/github.com/Shougo/vimproc.vim,~/.vim/bundle/.cache/vimrc/.dein,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vim74/pack/dist/opt/matchit,/usr/share/vim/vim74/pack/dist/opt/editexisting,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after,~/.vim/bundle/repos/github.com/Shougo/dein.vim,~/.vim/bundle/.cache/vimrc/.dein/after
となり、~/.vim/after/ では、プラグイン読み込み前に実行されてしまい当たり前なのですが…

after/ftplugin/ 配下なら行けそうですが、全てのファイルに適用する方法が解らない(^_^;;
## Vimのバージョン
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 22:32:42)
適用済パッチ: 1-1829
追加拡張パッチ: 8.0.0056

## OSの種類/ディストリ/バージョン
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
## その他

**Comment by thinca** [comment]
```vim
augroup delcmd
  autocmd!
  autocmd VimEnter * delcommand Explore
augroup END
```

こういう感じでどうでしょうか?

**Comment by iranoan** [comment]
できました(^-^)
VimEnterを使えばよかったんですね
