### ISSUE TITLE
vim-fugitiveが動かない

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#998]
# 質問・報告の内容
dein.vimでプラグインを管理し dein.toml に
[[plugins]]
repo = 'tpope/vim-fugitive'
として、インストールまでは出来たのですが、
:Gstatus
とすると、
BufReadCmd Auto commands for "index{,.lock}" の処理中にエラーが検出されました:
fugitive: no work tree
とエラーになり全く動きません
他のコマンドも同陽です

$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vimrc

no changes added to commit (use "git add" and/or "git commit -a")
などと無事動きますし、cohama/agit.vim は、cdpath の設定をしてやれば無事動きました

diff を見る時は、fugitive の方が便利そうなので、試してみたいのですが、何がいけないのでしょう?
(何か根本的に使い方を誤っているのかな?)

## Vimのバージョン
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 22:32:42)
適用済パッチ: 1-1829
追加拡張パッチ: 8.0.0056
## OSの種類/ディストリ/バージョン
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
## 使用している or 関係していそうなプラグイン
tpope/vim-fugitive

**Comment by mattn** [comment]
autocmdir を設定してたりしますか？

**Comment by iranoan** [comment]
回答有り難うございます

autocmdirとは何でしょう?
set autochdir
なら、確かにしていますね

これが原因だとすると、回避方法は有るのでしょうか?
offにしつつ autocmd で同等のことをすれば両取りは出来ますか?

**Comment by mattn** [comment]
上記のエラーが発生しうるとすると、working tree 上でコマンドを実行しているつもりが autochdir で working tree  外で git コマンドを実行している可能性があると推測しました。解決方などはまだ思いついていませんが、ひとまず原因切り分けしたいですね。

**Comment by iranoan** [comment]
原因の切り分けは必要ですね
というわけでコメント・アウトしてみましたが、autochdir で結果は変わりませんでした

他でいじっているかも知れないので、念の為 pwd でカレント・ディレクトリは、vimを起動したディレクトリから変わっていないことも確認しました
使い方がよく解っていないので、.git の存在するディレクトリでやってみましたが、それも変わらず

後はどういった可能性がありそうでしょう?

**Comment by mattn** [comment]
この issue と似ている気がしますが、いかがでしょうか。 https://github.com/tpope/vim-fugitive/issues/94

**Comment by iranoan** [comment]
motemen/git-vim
は入れていませんし、agit.vim についても、これを入れる前から起きています

しかし、見直している過程で、少し進みました
どうやら原因は、
$ ls -l .git
lrwxrwxrwx 1 user user 35 11月 18 16:42 .git -> /media/user/USB_HD/git
と、.git がハードリンクにしていることのようです。

ハードリンクを使わない適当な場所にファイルをコピーしても試したら、Gstatus は成功しました
しかし Gdiff は、コマンドが失敗しますし、シンボリック・リンクを使わない様にするのは、私の運用上難しいので、vim-fugitive を使うのは諦めようと思います
(agit.vim の件もこれが原因かな?)

いろいろご助言頂きありがとうございました
