### ISSUE TITLE
agit.vim の AgitDiff コマンドについて

### ISSUE THREAD

**Issue by iranoan** [vim-jp/issues#999]
## 質問・報告の内容
表題の件で、
:help agit
には
>:AgitDiff [{revisions}]
\<snip\>
  When launched from |agit-stat| buffer, AgitDiff trys to pick target file
  from cursor position. (see   ##|\<cfile\>|)

とありますが、agit-stat でどこにカーソルが有っても、:Agit 呼び出し元のファイルとの差分になります
ステータス・ラインやタブ・バーの表示は、カーソル位置のファイル名になっているのですが???
私は何か勘違いしているでしょうか?
[#998](https://github.com/vim-jp/issues/issues/998) の状況なので、vim-fugitive は未インストールです
## Vimのバージョン
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 22:32:42)
適用済パッチ: 1-1829
追加拡張パッチ: 8.0.0056
## OSの種類/ディストリ/バージョン
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
## 使用している or 関係していそうなプラグイン
agit.vim

**Comment by mattn** [comment]
agit については作者が日本人ですので、面倒で無ければ直接お聞きした方が良いかもしれません。

https://github.com/cohama/agit.vim/issues

またここに知見を残すよりもあちらの issues に残す方が今後他の方の参考にもなるかと思います。

**Comment by iranoan** [comment]
そうします
GitHubに使い慣れず、あちらに書き込むという発想が全く出来ませんでした
